### ISSUE TITLE
Presentations

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#10]
Add the possibility to make presentations in a JitMeet conference.

This includes:
- upload a PDF or a number of images
- allow the presenter to pick which one they are showing
- allow participants to switch to slides as they do for regular video 
- allow presenter to navigate through slides
- update slides for participants as the presenter moves through them

**Comment by karanasit** [comment]
Hello @emcho : I have been working to include presentation in jitsi. An application in nodejs has been developed with impress.js and impressr.js. I am able to have basic slide of impress.js where the change in slide is reflecting on each client tab with nodejs app being accessed.However, when trying to access the application from jitsi nginx proxy pass,I am not able to call some javascript libraries.Any suggestion would be helpful

**Comment by KiaraGrouwstra** [comment]
as Prezi is a commercial service, should we not reopen this issue to reflect the fact the original demand wasn't properly addressed?

**Comment by saghul** [comment]
That is accomplished with screen sharing these days.
