### ISSUE TITLE
A better tile layout while using a very short and wide iframe

### ISSUE THREAD

**Issue by hypergig** [jitsi/jitsi-meet#10011]
**Is your feature request related to a problem you are facing?**
Currently if you create a very short and wide iframe for jitsi, and use the tile layout, all the participant windows get clustered up really tight in the middle.

**Describe the solution you'd like**
I would like to see the participant windows be spread out evenly, using all the space available in the iframe. In the case of a very short and wide iframe, I would expect to see a single row of participants, all lined up, single file. Each maximizing the full height of the available space.

**Describe alternatives you've considered**
I have considered migrating off the iframe.

**Related**
https://github.com/cyruzzo/AboveVTT/pull/128

**Comment by saghul** [comment]
An you share a screenshot please?

**Comment by jordan-da** [comment]
> An you share a screenshot please?

https://github.com/cyruzzo/AboveVTT/pull/128#issuecomment-926243795


you can see an example here is this comment

**Comment by hypergig** [comment]
So sorry, you can see a screen shot in the linked issue

https://github.com/cyruzzo/AboveVTT/pull/128#issuecomment-926243795

**Comment by saghul** [comment]
Got it. I suppose you are using the iframe API, right? You can set this interface config override: https://github.com/jitsi/jitsi-meet/blob/c3348bf38ed7dbf8c7e321b3ae104a9f70e89401/interface_config.js#L184

Set it to false and you should get a better experience.

**Comment by hypergig** [comment]
Thank you @saghul for the suggestion, unfortunately it doesn't seem to work like that.

We in fact already have this set to `false`, as you can see here in that very same PR:

https://github.com/cyruzzo/AboveVTT/pull/128/files#diff-8017e3877c21790877e64b77fc0c7199e80f20364b16a4eb771ee562ea931530R67

Correct me if i am wrong but the film strip is a component of the speaker layout, not the tile layout, so it didn't seem to do anything while in tile layout.

I can confirm while in speaker layout, the filmstrip will render as a virtical stript but it does not affect the tile layout whatsoever.

**Comment by saghul** [comment]
Right you'll need to disable tile view.

At that height there will be no large view, so you should see all tiles in a single strip.

Is this what you observe?

**Comment by hypergig** [comment]
Not quite. I do see a strip of tiles on the far right, and the speaker dead in the middle. But nothing is distributed across the full width of the iframe. There is a good deal of empty space on the right side of the speaker, and the left side it completely empty. Everything is rather small.

I can send a screenshot shortly.

**Comment by hypergig** [comment]
is there a way to disable the current speaker, and have the filmstrip render evenly distributed across the whole iframe?

**Comment by saghul** [comment]
I thought that was automatic based on the available space. @horymury can you remind me what the state of this is?

**Comment by hypergig** [comment]
![Screen Shot 2021-09-26 at 10 00 31 PM](https://user-images.githubusercontent.com/8643560/134834843-7f995c6f-70d4-476f-81c4-279a49d556ac.png)

Here is what is looks like with the following settings:
https://github.com/cyruzzo/AboveVTT/blob/cecd531c66bb98e645eea0505e118467660e9b87/Jitsi.js#L38-L68

As you can see, there is a good deal of dead space to the left of the speaker, and to the right under the filmstrip. Ideally, what I would be looking for is _just_ the film strip, filling this space as much as possible without clipping. The speaker isn't required and in fact is getting covered up some by the film strip.

This is why I was suggesting a change to to the tile layout. I basically want a single row tile layout, filling the parent. Like the film strip in a way.

Thanks for your help.

**Comment by hypergig** [comment]
With jquery i was able to create the exact layout i wanted to see however, that was in the devtools console, this method does not work from code because jquery can not _really_ query within an iframe (it isn't really part of your document). The fact that it worked in the the devtools console is pure magic.

Is there a way to inject or run jquery within the iframe context? That would give me exactly what I would need. Can I somehow do this with the `getIfrme()` function? Is there a trick that I am missing? An event handler that will execute code inside the iframe?

**Comment by saghul** [comment]
I don't think that's possible, CORS would block it.

@horymury can you PTAL when you're back? I thought we had changed this at least for the vertical filmstrip, didn't we?

**Comment by hypergig** [comment]
Right right, but does jitsi provide anyway to hook inside the iframe ? Like a handler that runs within it, in a safe context? Or a way to provide our own css, and/or override the jitsi default?

The changes I need to make are really just pure css.

**Comment by hypergig** [comment]
related: https://github.com/jitsi/jitsi-meet/issues/5142

**Comment by saghul** [comment]
We don't have that capability yet, alas. Now if it's just CSS applying it under the right conditions in our codebase should be doable I think.

**Comment by hypergig** [comment]
I just want to take a moment and say thank you @saghul for being so helpful in this matter, I really appreciate it.

So which part is doable? I am pretty new to javascript, and am still learning.

BTW.. this is the jquery I was using to force the layout I think I want:
```
	$('.remote-videos').width("100%").children().first().width("100%").css("display","flex").children().removeAttr("style").width("100%").height("100%").find('video').css("object-fit","cover");
```

The trick it to set the parent of the video `spans` to 100% and `display: flex`, remove all the `absolute` stuff from the videos (and all the rest of the styling), make them 100% for both height and width, and finally setting `object-fit: cover` to max out the video panes.

Simple as pie 😅
