### ISSUE TITLE
Not working inviting videosipgw participants to the conference.

### ISSUE THREAD

**Issue by veratiz** [jitsi/jitsi-meet#10017]
### Description:

Not working inviting videosipgw participants to the conference.

### Steps to reproduce:

1. Open add people dialog
2. Type videosipgw participant name, in my case is "sip"
3. In browser debug tool i see response with text:
```
[
   {
       "id": "10.10.18.174",
       "name": "sip",
       "type": "videosipgw"
   }
]
```
4. But no matches found

### Expected behavior:

Item must be found

### Server information:

- Jitsi Meet version: Last from github
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chrome last
- Operating System: Windows 10

### Additional information:

Solution:

In react/features/invite/components/add-people-dialog/web/InviteContactsForm.js:

```
-       const users = response.filter(item => item.type === INVITE_TYPES.USER);
+       const users = response.filter(item => item.type === INVITE_TYPES.USER || item.type === INVITE_TYPES.VIDEO_ROOM);
```

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/e3ac52908a07017106a1a8e32bb71eba77e271c2
