### ISSUE TITLE
JitsiMeetConferenceOptions causing error 

### ISSUE THREAD

**Issue by kaushal2406** [jitsi/jitsi-meet#10024]
Getting Error Caused by java.lang.RuntimeException: Parcel android.os.Parcel@ff341c6: Unmarshalling unknown type code 7602277 at offset 1136 When using custom activity via extending JitsiMeetActivity.java

I have found problem  in JitsiMeetConferenceOptions.java

need to remove line 299 
**byte tmpAudioMuted = in.readByte();**
  
after removeing above line working .
please remove line 299 from JitsiMeetConferenceOptions.java

**Comment by saghul** [comment]
@tmoldovan8x8 PTAL on Monday

**Comment by saghul** [comment]
This has been fixed.
