### ISSUE TITLE
LIBRE_BUILD sdk pulls in Dropbox dependency

### ISSUE THREAD

**Issue by tepozoa** [jitsi/jitsi-meet#10021]
Hello, I'm using this previous issue as a template: https://github.com/jitsi/jitsi-meet/issues/8956

The F-Droid build of Jitsi Meet and Element Android are using the Jitsi SDK, which is pulling in the Dropbox SDK (a non-free network service - the Dropbox SDK itself is MIT licensed) as shown here:

https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/build.gradle#L47
```
    implementation 'com.dropbox.core:dropbox-core-sdk:4.0.1'
```

Could we investigate removing the Dropbox SDK from the LIBRE_BUILD version of the Jitsi SDK, such that Jitsi Meet and Element Android can take advantage of the change in F-Droid builds?

Thank you for your time!

**Comment by Bubu** [comment]
Afaik the dropbox-core-sdk is free software: https://mvnrepository.com/artifact/com.dropbox.core/dropbox-core-sdk says it's MIT licensed. I didn't look further for the source yet, but I think I've seen in on github somewhere at some point.

**Comment by tepozoa** [comment]
Yes, the SDK is MIT Licensed (that I can see also), the problem is that "talking to Dropbox" (same as saying "talking to Reddit", not picking on Dropbox) is considered an Anti-Feature in F-Droid as it's promoting non-free network services:

* https://f-droid.org/en/docs/Anti-Features/#NonFreeNet

As just an example, here's my favourite Reddit client which is labeled with that tag:

* https://f-droid.org/en/packages/org.quantumbadger.redreader/

It's the act of bundling code which speaks to services which are non-free. Jitsi Meet and Element Android _should_ be tagged with Anti-Features as it stands today, however this issue went unnoticed until a user brought it up today in chat asking why the Dropbox SDK was present in the build.

**Comment by saghul** [comment]
I'd take a patch that puts it under the LIBRE_BUILD flag, but some more extra work would be necessary to make sure the client doesn't try use it still.

**Comment by saghul** [comment]
> It's the act of bundling code which speaks to services which are non-free. Jitsi Meet and Element Android _should_ be tagged with Anti-Features as it stands today, however this issue went unnoticed until a user brought it up today in chat asking why the Dropbox SDK was present in the build.

I strongly disagree. It's a non core, completely optional feature. I'd say labeling applications like that in this scenario is incredibly hostile to users and makers of apps.

**Comment by tepozoa** [comment]
> I strongly disagree. It's a non core, completely optional feature. I'd say labeling applications like that in this scenario is incredibly hostile to users and makers of apps.

This is not for me to say as a user, I've posted to the F-Droid dev chat if anyone from the dev team would like to comment on this. I am just trying to solve a problem as a user within the framework which exists today.

**Comment by saghul** [comment]
I honestly don't understand how, as a user, you have a problem with an open source SDK that does nothing by default.

**Comment by eighthave** [comment]
The `NonFreeNet` Anti-Feature only applies if the proprietary network service is required in order for the app to work.  So if an app only syncs to Dropbox, then it would get `NonFreeNet`.  But if it is configurable between Nextcloud and Dropbox, then it would not be marked with `NonFreeNet.`

**Comment by licaon-kter** [comment]
I never saw actual network connections, so imho no AntiFeature is required.

**Comment by tepozoa** [comment]
Understood, I will close the issue.
