### ISSUE TITLE
Android SDK build failing due to missing "fs" module

### ISSUE THREAD

**Issue by skumarcm** [jitsi/jitsi-meet#10026]
I am trying to build the android SDK using the latest jitsi meet release.
I am getting the following error:

Error: Unable to resolve module `fs` from `react/features/stream-effects/virtual-background/vendor/tflite/tflite-simd.js`: fs could not be found within the project.

Can someone help what is going wrong here?
Many thanks!!!

**Comment by skumarcm** [comment]
The problem was due to the import of a wrong file. One of the local changes were done only for the web product.  But it was imported in a file with ".any" extension which resulted in the error.

**Comment by shooding** [comment]
> The problem was due to the import of a wrong file. One of the local changes were done only for the web product. But it was imported in a file with ".any" extension which resulted in the error.

How did you solve in the end ?
