### ISSUE TITLE
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh should not install cronjob

### ISSUE THREAD

**Issue by trefzer** [jitsi/jitsi-meet#10032]
### Description:

The script /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh installs certbot from Debian package and additionally ads a cronjob for renewal of certs in /etc/cron.weekly/letsencrypt-renew.

Since the debian package of certbot already installs a cronjob and a systemd timer this is useless. 
### Steps to reproduce:
run  /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
### Expected behavior:
The file /etc/cron.weekly/letsencrypt-renew should not be created.

### Actual behavior:
The file /etc/cron.weekly/letsencrypt-renew is created !

### Server information:

- Jitsi Meet version: 1.0.5307-1 of jitsi-meet-web debian package
- Operating System: Debian buster

**Comment by damencho** [comment]
Adding a note: install scripts need to add just the hooks for the renewal to reload the webserver 
/etc/letsencrypt/renewal-hooks
The same way the turnserver does: https://github.com/jitsi/jitsi-meet/blob/f9cc813e915dfe49d7d592563ecac46a0a24a696/resources/install-letsencrypt-cert.sh#L67
