### ISSUE TITLE
No video or audio on meet.jit.si in iOS 15

### ISSUE THREAD

**Issue by jure** [jitsi/jitsi-meet#10039]
### Description:

Video and audio are not present on Jitsi's web version on iOS 15.

### Steps to reproduce:

1. Open e.g. https://meet.jit.si/testiosbug1 in Safari on iOS 15.
2. Open same meeting in a browser (e.g. Chrome) on desktop
3. Observe no audio or video on iOS.

### Expected behavior:

Video and audio should be present.

### Actual behavior:

Video and audio are not present in a 2-user call. Sometimes with 3 meeting attendees it reappears, but appears to be flaky. Video is sometimes present on the remote (e.g. desktop) end, but no audio.

### Server information:

- Jitsi Meet version: current web version
- Operating System: macOS Big Sur

### Client information:

- Browser / app version: iOS Safari 15
- Operating System: iOS

### Additional information:

This is what is in the logs on the device:
[iosnoaudio.log](https://github.com/jitsi/jitsi-meet/files/7242629/iosnoaudio.log)

Some perhaps relevant observations from the wider web: 
https://github.com/twilio/twilio-video.js/issues/1586
https://github.com/AirenSoft/OvenMediaEngine/issues/517

**Comment by saghul** [comment]
I could not reproduce the issue with the provided steps.

**Comment by jure** [comment]
Could you provide a description of your software/hardware combination? Maybe we can find the culprit in the delta.

**Comment by saghul** [comment]
I used iOS 15 on an iPhone 7 and Chrome Version 94.0.4606.54 on macOS Big Sur.

**Comment by jure** [comment]
For reference, I'm on iOS 15 on an iPhone XS Max, on the other end is Chrome 94.0.4606.61.

Have you enabled/disabled any non-default experimental features by any chance? I can not get this to work.

**Comment by saghul** [comment]
I don't remember chasing any of them.

**Comment by jure** [comment]
I've resolved it by going through a list of default values in the experimental features menu (https://m.imgur.com/a/qRNRrik) and noticed that one of my toggles is at a non-default value, though I never toggled it. 

After toggling "**GPU process media**" to **on**, my streams work as they did before iOS 15.

Thank you @saghul for your help! Closing this issue and hopefully it's useful for someone else as well.

**Comment by saghul** [comment]
Great to hear!

**Comment by textreme** [comment]
Hi @jure ,

I am running into this same issue, the imgur link is not showing an image. Is there any way you could post that photo again or let me know where I can find the experimental features menu?

Much appreciated.

**Comment by rishitapotluri** [comment]
> I've resolved it by going through a list of default values in the experimental features menu (https://m.imgur.com/a/qRNRrik) and noticed that one of my toggles is at a non-default value, though I never toggled it.
> 
> After toggling "**GPU process media**" to **on**, my streams work as they did before iOS 15.
> 
> Thank you @saghul for your help! Closing this issue and hopefully it's useful for someone else as well.


Hi,
Can you please provide more insight onto this?
