### ISSUE TITLE
getting constantly disconnected on Jitsi Meet

### ISSUE THREAD

**Issue by mghadam** [jitsi/jitsi-meet#10036]
### Description:

The participants are randomly getting disconnected during a jitsi meet whereas they all have a stable and good quality internet connection. Video calls are all stable on other platforms such as Whatsapp, skype and telegram. However, on jitsi meet clients constantly get disconnected.

### Actual behavior:

![image](https://user-images.githubusercontent.com/10244293/134903799-dd47eef0-63da-46b4-8bb6-6a7399e42557.png)

### Server information:

- Jitsi Meet version: 2.0.6293
- Operating System: Docker

### Client information:

- Browser / app version: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36

- Operating System: Ubuntu 21.04

### Additional information:

- Here is the docker-compose log of a session when this happens:
[docker-compose-log.txt](https://github.com/jitsi/jitsi-meet/files/7236110/docker-compose-log.txt)

**Comment by damencho** [comment]
Upload js client logs when this happens.

**Comment by damencho** [comment]
And in general, please, use the community forum for posting problems and questions before opening new issues, thank you.
