### ISSUE TITLE
Objective-C vs. Swift

### ISSUE THREAD

**Issue by ericgiannini** [jitsi/jitsi-meet#1003]
What barriers are there to refactoring the directories on iOS from Objective-C to Swift?

**Comment by lyubomir** [comment]
The Objective-C files that support the iOS app are automatically generated by React Native (the command line utility react-native with the option init or upgrade). I think we also copied pieces from React Native's website to support link handling. We have applied a minor modification (as far as I remember, changing the background color to black) or two. In other words, the Objective-C source code is not really something we write and we want to keep its maintenance (upon React Native upgrades) to the minimum.
