### ISSUE TITLE
Disable chat polls on mobile (IOS/Android)

### ISSUE THREAD

**Issue by Marinaarimany** [jitsi/jitsi-meet#10033]
I would like to remove the polls in the chat, I don't need them. How can I do to remove them  on ios version 3.10.2 of the sdk please.

Thank you

**Comment by Marinaarimany** [comment]
@saghul

**Comment by damencho** [comment]
What about disabling it in config.js https://github.com/jitsi/jitsi-meet/blob/f9cc813e915dfe49d7d592563ecac46a0a24a696/config.js#L84 does that change anything?

**Comment by Marinaarimany** [comment]
> Que diriez-vous de le calmer dans config.js
> 
> https://github.com/jitsi/jitsi-meet/blob/f9cc813e915dfe49d7d592563ecac46a0a24a696/config.js#L84
> 
> ça change quelque chose ?


I am with React native and I do not have the possibility to access this file: / We can not deactivate it via the features flag?

**Comment by damencho** [comment]
You are using meet.jit.si as a backend? If that is the case, I'm not sure whether that there is a feature flag in latest SDK ...

**Comment by Marinaarimany** [comment]
Ah I don't know at all I go through the library: react-native-jitsi-meet but I updated the sdk manually. I'm trying to deactivate it suddenly .. I don't know if you can help me, thanks for your help and your time

**Comment by Marinaarimany** [comment]
@saghul

**Comment by saghul** [comment]
We currently have no feature flag for it for mobile. I'd take a PR adding it though. It should go around here: https://github.com/jitsi/jitsi-meet/blob/700e809439780cf86d7b38ec503a8375e34bfdd3/react/features/chat/components/AbstractChat.js#L167

**Comment by Marinaarimany** [comment]
Thank you @saghul :)

**Comment by Marinaarimany** [comment]
> We currently have no feature flag for it for mobile. I'd take a PR adding it though. It should go around here:
> 
> https://github.com/jitsi/jitsi-meet/blob/700e809439780cf86d7b38ec503a8375e34bfdd3/react/features/chat/components/AbstractChat.js#L167


When will it be available? Thank :)

**Comment by saghul** [comment]
I don't plan on writing it myself, sorry, I'm busy with other things. I suggested how you can write it and submit it as a PR so we can incorporate it.

**Comment by Marinaarimany** [comment]
@saghul  Ah okay ! Thank you :)
