### ISSUE TITLE
Jibri recording

### ISSUE THREAD

**Issue by uberiain** [jitsi/jitsi-meet#10049]
### Description:

When I record one meeting I obtain the recording with a message on it :

“El nombre de la reunión no debe de contener ninguno de estos caracteres: ?,&,:,’,”,%,#." but the meeting name is video
### Steps to reproduce:

1.   Create meeting with name: Video
2.  Record the meeting
3.  View the meeting recorded

### Expected behavior:

the recorded meeting sould don't have the error

### Actual behavior:
The recorded meeting have this message: “El nombre de la reunión no debe de contener ninguno de estos caracteres: ?,&,:,’,”,%,#."

![vlcsnap-2021-09-08-11h09m28s922](https://user-images.githubusercontent.com/29492430/135149974-b435a7ed-faae-43d3-a0d7-59982aeda7ee.png)

### Server information:

- Jitsi Meet version: 
jitsi-meet 2.0.6345-1 all WebRTC JavaScript video conferences
jitsi-meet-prosody 1.0.5349-1 all Prosody configuration for Jitsi Meet
jitsi-meet-turnserver 1.0.5349-1 all Configures coturn to be used with Jitsi Meet
jitsi-meet-web 1.0.5349-1 all WebRTC JavaScript video conferences
jitsi-meet-web-config 1.0.5349-1 all Configuration for web serving of Jitsi Meet
jitsi-videobridge2 2.1-557-gba6a8492-1 all WebRTC compatible Selective Forwarding Unit (SFU)
prosody 0.11.2-1+deb10u2 amd64 Lightweight Jabber/XMPP server
prosody-modules 0.0~hg20190203.b54e98d5c4a1+dfsg-1+deb10u1 all Selection of community modules for Prosody
jibri 8.0-104-g9871ba1-1 all Jibri

- Operating System:
OS : Linux jitsi 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
debian version: 10.10

### Client information:

- Browser / app version:
Microsoft Edge Versión 93.0.961.47 (Compilación oficial) (64 bits)

- Operating System: Windows 10

### Additional information:

The meeting name is Video

**Comment by saghul** [comment]
This is very weird the only place where we show that text is in the `title` prop of the welcome page input field.

**Comment by saghul** [comment]
Any chance you can get Jibri's browser logs? Are you ablee to reproduce this with other meeting names? Are you able to reproduce this on meet.jit.si?

**Comment by uberiain** [comment]
With other meeting name: OtroNombreReunion. Same result.

![vlcsnap-2021-09-29-13h33m19s762](https://user-images.githubusercontent.com/29492430/135269202-3395f0e0-a4e2-4a3a-bafe-9c87afcf1ec4.png)

Logs and metadata from Jibri:
[ffmpeg.0.txt](https://github.com/jitsi/jitsi-meet/files/7251823/ffmpeg.0.txt)
[log.0.txt](https://github.com/jitsi/jitsi-meet/files/7251824/log.0.txt)
[metadata.json.txt](https://github.com/jitsi/jitsi-meet/files/7251827/metadata.json.txt)

On meet.jit.si no problem.
![vlcsnap-2021-09-29-13h41m46s469](https://user-images.githubusercontent.com/29492430/135270389-8cef0ae3-8c42-40a2-815e-1c406fe61ed6.png)

**Comment by saghul** [comment]
Do you have browser.0.log.txt ?

**Comment by uberiain** [comment]
Yes, sorry.
[browser.0.txt](https://github.com/jitsi/jitsi-meet/files/7251920/browser.0.txt)

**Comment by saghul** [comment]
I don't see anything obvious... @damencho extra pair of eyes?

**Comment by damencho** [comment]
Are you running jibri on a machine where you also X server and mouse (a workstation)? Or it is on a VM with no mouse attached?

**Comment by uberiain** [comment]
Jibri is working on a VM without X server, the OS is a clean debian 10,  only for jitsi and jibri.
No Mouse, no keyboard , no creen.

**Comment by uberiain** [comment]
Hi, I think that I found the problem:

With latest chrome version for debian, the message appears. I have downloaded google chrome to 86.0.4240.75 and chromedriver to LATEST_RELEASE_86.0.4240 and the message disapear.


![vlcsnap-2021-09-30-10h18m36s970](https://user-images.githubusercontent.com/29492430/135427143-35a783fc-cbaf-4e41-934f-03a913713c26.png)

So I think that the problem is with chrome.

**Comment by saghul** [comment]
Oh! Any chance you can update to further versions to check which one fails? Is it just 94? 93 as well?

**Comment by uberiain** [comment]
I test with this versions, and the result:

google-chrome-stable            90.0.4430.72-1 Works
google-chrome-stable            91.0.4472.164-1 Works
google-chrome-stable            93.0.4577.82-1 Don't work
