### ISSUE TITLE
Cannot find `enableFeaturesBasedOnToken` in config.js

### ISSUE THREAD

**Issue by artknight** [jitsi/jitsi-meet#10048]
The config.js file used to contain the `enableFeaturesBasedOnToken` setting that is now not found. 

Would anyone please direct me to its location and of the process has changed.. to the corresponding docs?

Thanks,
Art

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues. 

It is there https://github.com/jitsi/jitsi-meet/blob/ace53c880bebeeefc6c08eb8228499010cde20e9/config.js#L462

**Comment by artknight** [comment]
@damencho It is not available in the latest config.js. I just pulled down master and this setting is not there any longer.

**Comment by damencho** [comment]
It is there: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L462
Where do you pull it from?

**Comment by artknight** [comment]
Yeah I just saw it. I was confused b/c originally this setting was called `enableUserRoleBasedOnToken` and I guess it got renamed at some point. Thank you @damencho !!

**Comment by damencho** [comment]
Nope, that was another setting that we removed a while ago as this should be controlled through the backend whether a participant is a moderator or not and not rely on a client config.

**Comment by artknight** [comment]
@damencho Do you happen to have any documentation on what backend settings are needed for that? Can it work by setting the moderator through JWT?

**Comment by damencho** [comment]
> Can it work by setting the moderator through JWT?

This is not supported out of the box. You need to create your own module or use something from here https://github.com/jitsi-contrib/prosody-plugins
