### ISSUE TITLE
Android sdk 3.3.0 language detector do not work

### ISSUE THREAD

**Issue by cj123195** [jitsi/jitsi-meet#10042]
When I use Android jitsi_meet SDK version 3.3.0, the language of my mobile phone was Chinese, but jitsi_ meet page does not display Chinese correctly, and the SDK does not set the language option. How can I set the default language to Chinese?

**Comment by saghul** [comment]
Please update your SDK to the latest version, 3.3.0 is really old and a lot has changed since.
