### ISSUE TITLE
Respect Casing of the Room Name

### ISSUE THREAD

**Issue by thekief** [jitsi/jitsi-meet#10058]
**Is your feature request related to a problem you are facing?**

Currently, the first letter in the window title is **always** capitalised.

**Describe the solution you'd like**

Respect the casing of all letters, including the first one.
This could be achieved by removing `upperFirst` in the function `safeStartCase` 

**Describe alternatives you've considered**
n/a

**Comment by saghul** [comment]
Meetings are all internally handled in lower case. The casing you is some "beautification" we apply to try to make sense of it, but if you use the API you can set the subject in whatever casing you want.
