### ISSUE TITLE
[iOS15] First unmute doesn't work if everyone starts muted

### ISSUE THREAD

**Issue by cyrusb** [jitsi/jitsi-meet#10053]
Hi,

I know there was a fix for this issue 5 days ago (https://github.com/jitsi/jitsi-meet/commit/35e363577c3073f2ef82601d4baa31e59d94da67), but the issue still remains if everyone joins the meeting with audio muted.

You can trigger this either by ticking "everyone starts muted" in the moderator settings (reproduced on meet.jit.si):

![image](https://user-images.githubusercontent.com/53196/135243902-e3c165b7-6c7d-4abd-9a55-e3321d20d96f.png)

Or by setting startAudioMuted to 1 in config.js, which is what we do on our own servers.

Thanks!

**Comment by damencho** [comment]
Do you reproduce this on beta.meet.jit.si?

**Comment by cyrusb** [comment]
> Do you reproduce this on beta.meet.jit.si?

Yeah, just tried it on beta.meet.jit.si. Same issue.

**Comment by saghul** [comment]
Thanks for the report! I'll take a look.

**Comment by aprocom** [comment]
Hi! We catch the same problem. Have any ideas about fix?
