### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by rudolfschmidt** [jitsi/jitsi-meet#1005]
Creating jitsi.example.com in /etc/nginx/sites/ with content

```
server_names_hash_bucket_size 64;

server {
    listen 80;
    server_name jitsi.example.com;
    # set the root
    root /srv/jitsi.example.com;
    index index.html;
    location ~ ^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }
    location / {
        ssi on;
    }
    # BOSH
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }
}

```
adding jitsi.example.com in /etc/hosts and executing

```
cd /srv
git clone https://github.com/jitsi/jitsi-meet.git
mv jitsi-meet/ jitsi.example.com
```

restarting nginx and opening jitsi.example.com in a web browser leads to not founded css files and other assets

what did I wrong?

**Comment by damencho** [comment]
Please, send questions to the mailinglist before opening issues.
Also there are steps like npm install and make which is also written in the Readme file which you need to execute before using the app. I suppose before trying that, you have already installed jicofo, jitsi-videobridge and had configered prosody.
