### ISSUE TITLE
Share Screen problem in iOS SDK 3.10.2

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#10069]
We make a conference with windows Chrome and iOS App.
We start share screen from windows but iOS App doesn't show it.
And when any new user comes to the conference, iOS suddenly starts to show translation.

It seems that this happens only with windows Chrome.
If we do the same from macOS Chrome - all is fine.

**Comment by saghul** [comment]
What do translations have to do with anything?

**Comment by iospro** [comment]
We start conf, one of its members is from iOS client.

then some windows user starts to show his windows desktop via web sdk using chrome browser.

all attendees except iOS user get translation on screens. 
iOS user starts to get the picture only when someone new comes to conference.

It seems that translation to iOS begins with a signal “new user has come”
