### ISSUE TITLE
"3dots" menu vanished on Android SDK 3.10.1

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#10072]
We updated android sdk to 3.10.1 build and we lost menu button in the bottom row.

Now we need to write 
`setFeatureFlag("overflow-menu.enabled" , true)`
to get back dots menu.

but it differs from its description and iOS behaviour.

<img width="360" alt="Screenshot 2021-10-01 at 00 46 26" src="https://user-images.githubusercontent.com/1611869/135534856-7ab369bf-a750-4d60-b749-6bf19c28c330.png">

**Comment by saghul** [comment]
We have not changed anything in the overflow menu button. The flag defaults to true. Do you see anything in the logs?

**Comment by iospro** [comment]
We set flag in code manually to true and dots menu appeared.
