### ISSUE TITLE
useRoomAsSharedDocumentName parameter in config.js seems to be deprecated

### ISSUE THREAD

**Issue by qwertiko** [jitsi/jitsi-meet#10103]
### Description:

The config.js mentions a parameter called "useRoomAsSharedDocumentName" that seems to be deprecated: https://github.com/jitsi/jitsi-meet/blob/9ef71e3b152b2ed0d3a623f8a8a1b57c2b602bc4/config.js#L976-L979

The comment has been added in https://github.com/jitsi/jitsi-meet/pull/5620.

Toggling said option does not change how Etherpad documents get generated. The name of the document always is the name of the conference, which seems to be the default behavior.

The following commit indicates, that the option got renamed/moved to jicofo and its config: https://github.com/jitsi/jicofo/commit/b3e6abca8b98be178b99f80b7f0b2b8dc556e7f2

I can confirm that adding the following part to the `/etc/jitsi/jicofo/jicofo.conf` changes the behavior as expected:
```
jicofo {
...
  conference {
    shared-document {
      // If `true` the shared document uses a random name. Otherwise, it uses the conference name.
      use-random-name = "true"
    }
  }
}
```

I suggest removing the comment from the config.js and instead mention the setting that has to be changed in the jicofo.conf file.

### Steps to reproduce:

1. Edit config.js and change `useRoomAsSharedDocumentName` from `true` to `false`
2. Start Jitsi meeting
3. Open a shared document
4. Copy link to shared document

### Expected behavior:

The name of the shared document should be random: etherpad/p/00603274833d457d8cd6bbe189aafaef

### Actual behavior:

The name of the shared document is the name of the conference room: etherpad/p/confusingplantsshutarguably

**Comment by saghul** [comment]
You are right, that config option no longer applies. Would you like to make a PR removing it?

**Comment by qwertiko** [comment]
Sure, I can do that. 😊 Should I just completely remove it or do you want me to mention the `use-random-name` setting?

**Comment by saghul** [comment]
Completely remove it please.
