### ISSUE TITLE
Issue on meet.jit.si: frequent disconnects

### ISSUE THREAD

**Issue by onlyjob** [jitsi/jitsi-meet#10107]
I could not find any contacts to report an issue affecting *meet.jit.si* so I hope you'll forgive me for reporting here.

Earlier today _meet.jit.si_ was barely usable due to persistent disconnection issues every minute. We had to fall back to Jitsi instances on call.disroot.org and FSF.org which both worked flawlessly. My network connectivity had no issues. I've been using *meet.jit.si* extensively over the last year and became dependent on it - thank you sincerely for providing such an awesome resource. Until today, there were no serious issues on *meet.jit.si* (except occasional disappearance of video feed that requires disabling and re-enabling camera as workaround).

Please pass this information to whoever is responsible for operating https://meet.jit.si/
Thank you.

**Comment by saghul** [comment]
We had an outage earlier today due to a botched update to the meet.jit.si service. It was restored around 11:30 CET. Sorry for the inconvenience and thanks for the kind words!
