### ISSUE TITLE
"Low internet connection" and dissconnect for 1 minute after 

### ISSUE THREAD

**Issue by Mister-Ice** [jitsi/jitsi-meet#10102]
### Description:

"Low internet connection" and dissconnect for 1 minute after connect to conf. Speedtest show 60 Mb/s. 
Please help with that.
Logs in the attachment.

### Client information:

- Browser / app version:  Google Chrome 94
- Operating System: Windows 10 Pro and one member Windows 7 Pro 64 bit

[logs.txt](https://github.com/jitsi/jitsi-meet/files/7291430/logs.txt)

**Comment by RAurelian** [comment]
I`m also getting disconnected within 1 minute of starting any meeting at meet.jit.si
If I use the console in the browser tools, I get this error just when the disconnection happens: 
`[modules/xmpp/XmppConnection.js] Detected that shard changed from meet-jit-si-eu-central-1b-s17 to all`
the `meet-jit-si-eu-central-1b-s17` part is different each time

**Comment by saghul** [comment]
meet.jit.si is suffering an outage at the moment, we are working to restore the service.

**Comment by RAurelian** [comment]
Thank you very much for the information.

**Comment by saghul** [comment]
Service has been restored.

**Comment by Josias-TopicWorx** [comment]
### **Description:**

The issue seems to persist, it used to disconnect me after 90 seconds, now it barely gets to 10 second before kicking me.

### **Additional information**

- Browser: Brave Browser
- Net speed: 100/100 mbps
- OS: **Edition:** Windows 10 Pro / **Version:** 20H2 / **OS Build:** 19042.1237

**Comment by Josias-TopicWorx** [comment]
I just finished another test this morning, everything seems to be running as expected. Thank you.
