### ISSUE TITLE
[iOS15] audio cannot be unmuted when using JVB and everyone starts muted

### ISSUE THREAD

**Issue by cyrusb** [jitsi/jitsi-meet#10104]
Hi,

This can be reproduced on beta.meet.jit.si by:

- Create a room and join
- Change moderator settings to "everyone starts muted"
- Join the room in another tab
- Join the room on a iOS15 device, using the latest Jitsi Meet app

You'll see that the iOS device cannot unmute.

Thanks!

**Comment by saghul** [comment]
What app and iOS version do you have?

**Comment by cyrusb** [comment]
> What app and iOS version do you have?

App version is 21.4.2 build 132. My iOS version is 15.0.1.

**Comment by saghul** [comment]
Thanks. I am unable to reproduce it with iOS 15.1 beta. I'll try with 15.0

**Comment by cyrusb** [comment]
Not sure if I made it clear in my post, but to reproduce it you need to already have 2 participants in the room before the iOS user joins. Basically, it needs to avoid using p2p.
