### ISSUE TITLE
Duplicate Classes

### ISSUE THREAD

**Issue by muhammedyalcin** [jitsi/jitsi-meet#10117]
While implementing jitsi-meet android SDK, we are experiencing many duplicated classes issues. Our project layout build on the Yoga layout that is being possible  by building the [Yoga framework](https://github.com/facebook/yoga) ourself. 

As observed, jitsi-meet also uses yoga modules. We look for the way of removing/excluding duplicated classes or packages. But that isn't quite possible. 

### Description:

To remove/exclude duplicated classes we have followed below steps;

1- Excluding transitive dependencies;

```
    implementation ('org.jitsi.react:jitsi-meet-sdk:3.9.1') {
        exclude group: 'com.facebook.react', module:'react-native'

        transitive = true
    }

//This contains yoga
    implementation ('com.facebook.react:react-native:0.61.5-jitsi.2'){

       exclude group: 'com.facebook.infer.annotation', module: 'infer-annotation'
       exclude group: 'com.facebook.soloader', module: 'soloader'
       exclude group: 'com.google.code.findbugs', module: 'jsr305'
    }
```
This way, achieved with removing half of the duplicates. But still yoga layout classes and some of its modules exist. 

2. Excluding isn't an exactly solved problem. That's way we need to repackage the `com.facebook.react:react-native:0.61.5-jitsi.2` but not found a opensource repo. Do you have idea how to compile this SDK myselft ?

### Steps to reproduce:

1. Build the [Yoga framework](https://github.com/facebook/yoga)
2. Import the built yoga framework and jitsi meet sdk to your project
3. See output for issues

### Server information:

- Jitsi Meet version: 3.9.1
- Operating System: Android

**Comment by saghul** [comment]
I have no idea sorry.
