### ISSUE TITLE
Android onscreen buttons are hidden

### ISSUE THREAD

**Issue by sophie-la-li** [jitsi/jitsi-meet#10129]
### Description:

The Android onscreen buttons are hidden. I can only (and happily) access them when i opened the menu.
This makes it very hard to access other apps or even getting back to the call from e.g. the chat.

### Steps to reproduce:

1. Join a call

### Expected behavior:

Android navigation buttons need to be accessible.

### Actual behavior:

Android navigation buttons are hidden. Happily they are still accessible in the menu.

![Screenshot_20211008-112559_1](https://user-images.githubusercontent.com/6147076/136533206-4d441845-a224-4da6-9b02-6bd3e0b1f3b5.png)
![Screenshot_20211008-112613_1](https://user-images.githubusercontent.com/6147076/136533211-4fe9f1b7-1d72-46fd-ae1f-d16349f8cd73.png)

### Client information:

- Jitsi Meet version: 21.3.0
- Operating System: Android 11 (build RQ3A.210905.001) 
- Device: Google Pixel 5

**Comment by saghul** [comment]
https://developer.android.com/training/system-ui/immersive
