### ISSUE TITLE
Change a flag while Jitsi Android SDK is running

### ISSUE THREAD

**Issue by EbelloImbox** [jitsi/jitsi-meet#10134]
Hello, I am looking for a way to change a flag while Jitsi Android SDK is running.

**Comment by saghul** [comment]
We don't currently support that. What is your use case?

**Comment by EbelloImbox** [comment]
We have an activity that extends from JitsiMeetActivity, we play a sound like ringing and an user can accept a "call". 

Our problem is that we can't play a sound, accept a call, make a join(JitsiOptions); and play other sound (to give feedback to user) when we did a join(JitsiOptions) because Jitsi has audio focus or we think that is the problem.

PS: Jitsi team have done an awesome job, thank you for Jitsi Meet and Spanish people have to be proud to have developers like you.
