### ISSUE TITLE
screen sharing pop up window not working

### ISSUE THREAD

**Issue by jy2008** [jitsi/jitsi-meet#1013]
I am sure this is an old issue, but i couldn't follow what exactly i should do after i read all the similar issues from other people. So i am using rocket.chat, which is using Jitsi for video chat. i am hosting rocket.chat on my own server but not jitsi. When i tried screen sharing, no window will prompt me to install the desktop sharing extension but saying "failed to install desktop extension". I had to go to chrome store and got it installed. But once other user use this chat, they might not know all this, is there way to make the prompt window work right? so it can install automatically or at least prompt user to chrome store to install it.

**Comment by albert-the-creator** [comment]
Try verifying your property. My suspicion is that inline installation isn't working because the property is unverified in webmaster tools. https://developer.chrome.com/webstore/inline_installation

**Comment by lpatmo** [comment]
Ah, I think this is related to the issue I just filed (https://github.com/jitsi/jitsi-meet/issues/1315). @jy2008 Were you ever able to find a workaround besides directing your users to the chrome store to install the screensharing plugin? Maybe the property needs to be verified re: @albert-the-creator's suggestion, but I don't think that's something we as the API users can do.

**Comment by saghul** [comment]
This should now be working in beta.meet.jit.si, since https://github.com/jitsi/lib-jitsi-meet/commit/d403a25c56229af5c98f79c707ab5aa8c86a5365 landed.
