### ISSUE TITLE
[Blocker] New Jitsi meet Android App is making phone very slow and hanging when screen sharing

### ISSUE THREAD

**Issue by pravasok** [jitsi/jitsi-meet#10147]
### Description:

When we use new jitsi meet app in android phones and do screen sharing and open other app's the phone is getting slow and hanging

When we install older version, the phone is not hanging
### Steps to reproduce:

1. open jitsi meet app
2. do screen sharing
3. open any other apps and use the app and switch apps 

### Expected behavior:

phone should not slow down or hanging

### Actual behavior:

phone is slowing down and hanging

### Client information:

- Browser / app version: latest playstore version
- Operating System: android 10

### Additional information:
When we install previous version of the app , phone is not slowing down or hanging

**Comment by pravasok** [comment]
@saghul  phone is slowing down or laggy when we do screen sharing in jitsi meet app in playstore

so literally, we are unable to use screen sharing, unless it is fixed. We use jitsi meet for all the meetings like lot of other people out there, we are blocked because of this.

**Comment by saghul** [comment]
Closing. Meetings have acceptable performance on mid tier devices and not-so-great on low end ones, but there is nothing specifically actionable here.

Video is just CPU demanding. We tried to use the HW accelerated codecs, but alas they crash a lot.
