### ISSUE TITLE
start muted / hidden by default

### ISSUE THREAD

**Issue by tomryanx** [jitsi/jitsi-meet#1015]
Following on from the 'start muted' and 'start hidden' options from #6 I would like to configure jitsi to start muted and hidden *by default*

I can't find anything in eg `interface_config.js` - it looks like maybe there's something I could tweak in `conference.js` ?

**Comment by damencho** [comment]
Please use the mailinglist for questions, before opening issues.

It is in config.js:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L65
startAudioMuted
startVideoMuted

**Comment by tomryanx** [comment]
Noted, will use the mailing list in future - thanks and apologies!

Feel free to bounce #1016 too and I'll take that to the mailing list also

**Comment by perguth** [comment]
Mitigation noted here: https://github.com/jitsi/jitsi-meet/issues/6#issuecomment-472937287
