### ISSUE TITLE
Face the issue while install node modules

### ISSUE THREAD

**Issue by hiteshsamcom** [jitsi/jitsi-meet#10151]
![Screenshot from 2021-10-12 14-39-20](https://user-images.githubusercontent.com/92365321/136929635-b7cc6a95-3fa8-45ba-934d-2a6b1e06a3cf.png)

**Comment by saghul** [comment]
Update to 7 please.

**Comment by hiteshsamcom** [comment]
![Screenshot from 2021-10-12 16-37-24](https://user-images.githubusercontent.com/92365321/136944864-55965750-503f-41f0-8f1f-91dd88828e13.png)

**Comment by hiteshsamcom** [comment]
![Screenshot from 2021-10-12 16-44-41](https://user-images.githubusercontent.com/92365321/136945926-ca7dbaaa-d92a-4ecb-be95-c32454d4b8fa.png)

**Comment by hiteshsamcom** [comment]
It's successfully generated but in localhost getting blank response.
![Screenshot](https://user-images.githubusercontent.com/92365321/136955417-7e523f8a-e1f7-40c8-876a-ddf979cb4baf.png)
![Screenshot from 2021-10-12 17-52-02](https://user-images.githubusercontent.com/92365321/136955423-ade1da26-f72d-40b1-b1b8-7da9d51653ea.png)

**Comment by shizukanaqun** [comment]
i face the same error  and  there is no https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.3.tgz file 
node ： 16.13.0
npm：8.1.3 
 please ！！！@saghul
