### ISSUE TITLE
Audio output volume instable on IOS 15 webview

### ISSUE THREAD

**Issue by guilhermetog** [jitsi/jitsi-meet#10165]
### Description:

Audio output is instable in IOS 15 webview. It starts very low volume, even cutting the phrases. Once you closes the app, sending it to background. Audio output keeps running, but louder. Then when you come back to app it's very very loud.

### Steps to reproduce: (WebView)

1. Create a simple swift app with webview, that opens site "https://meet.jit.si/sometestroom"
2. Give the app permissions to camera and microphone
2. Run it and open the conference room as web
3. Open the same room on another device
4. Closes the app, sending it to background
5. Reopen the app

### Alternative steps to reproduce: (Web also broken)

1. Open "https://meet.jit.si/sometestroom" on IOS Safari
2. Close Safari
3. Open it again

### Expected behavior:

Audio output working normally. With audible volume. When closes application, the audio should mute (or at least not change it's volume if it's the business rule). After return to app, it should has the same volume as started.

### Actual behavior:

(Webview)
The audio starts very low, and cutting the participant speak. When close the app, the audio keeps on background, but a little louder. After reopen the app, the audio output become very very loud.

(Safari Mobile)
The audio starts very low, and cutting the participant speak. When close the app, the audio keeps on background, but a little louder. After reopen the app, the audio continues the same as background.

### Server information:

- Jitsi Meet version: Current
- Operating System: Current

### Client information:

- Browser / app version: Current
- Operating System: IOS 15.0.0^

### Additional information:

I'm using a complete self hosted jitsi, with interface builted from source (both jitsi-meet and lib-jitsi-meet) and already costumized. I've been use it for a while without problems. This problem started after update to IOS 15. I Already updated to IOS 15.0.2, but the problem persists.

The tests i've proposed here are simplified just to focus on the problem, since it's not working not even opening it from a simple Swift app with webview or Safari Mobile.

I don't know if it's a Jitsi problem, webrtc or IOS. But I've tried all my best to findout what's happening and still have no clue.

Swift ViewController code:

```
class ViewController: UIViewController {
    
    let webview = WKWebView();

    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.addSubview(webview);
        guard let url = URL(string: "https://meet.jit.si/test123456") else{
            return
        }
        
        webview.load(URLRequest(url:url));
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews();
        webview.frame = view.bounds;
    }
}
```

Add to Info.plist

```
<dict>
    ...
    <key>NSMicrophoneUsageDescription</key>
    <string>Flutter requires access to microphone.</string>
    <key>NSCameraUsageDescription</key>
    <string>Flutter requires access to camera.</string>
    ...
</dict>
```

**Comment by saghul** [comment]
Unfortunately this is an issue in Safari / WebKit, there is nothing we can do about it.
