### ISSUE TITLE
Microphone in Google TV ChromeCast [android]

### ISSUE THREAD

**Issue by thorito** [jitsi/jitsi-meet#10160]
### Description:

On the Google Chromecast device it does not capture audio, video is ok

### Steps to reproduce:

1.  OnePlus phone calls Google Chomecast device (webcam connected by usb hub)
2. They both enter the room
3. Google chromecast listens to remote participant (OnePlus) but OnePlus does not listen to Google Chromecast. The video is displayed correctly.

### Expected behavior:

Let all participants see and hear each other

### Actual behavior:

From the Google device the audio of the rest of the participants is heard correctly but they do not listen to the Google Chomecast device

The official Jitsi Android app (version: 21.4.1 build 8992254) is installed and it doesn't work either. In audio devices it does not show anything: Message: "No audio devices available"

### Server information:

- Jitsi Meet version:  Lasted version (https://meet.jit.si)
- Android SDK 3.10.2
- Operating System: 
- OnePlus Android 10
- Google Chromecast Android TV 10

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

WebCam Logitech C270i

**NOTE: With the same hardware a call is made using the app: "Google Duo" and it works correctly.**

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by thorito** [comment]
Sorry I didn’t answer first. 
I tested the patch: https://github.com/jitsi/jitsi-meet/pull/10168 and it works :)
Is it possible to integrate into the next version?

Thank you

**Comment by saghul** [comment]
I reopen the PR and will test it out as time allows. Thanks for confirming it worked!
