### ISSUE TITLE
Flag to use Speaker phone

### ISSUE THREAD

**Issue by EbelloImbox** [jitsi/jitsi-meet#10172]
Hello everybody, I am using Android SDK.

I am looking for a way to start Jitsi with sound throught Speaker or Earpiece choosed by user before to start a Jitsi conference. I am using a little hack right now inside Jitsi code:

AudioModeModule class -> updateAudioRoute method:
```
// Pick the desired device based on what's available and the mode.
        String audioDevice;
        if (bluetoothAvailable) {
            audioDevice = DEVICE_BLUETOOTH;
        } else if (headsetAvailable) {
            audioDevice = DEVICE_HEADPHONES;
        } else {
            //here new code
            if(useConnectionService()) {
                audioDevice = DEVICE_EARPIECE;
            }
            else {
                audioDevice = DEVICE_SPEAKER;
            }
        }
```

With this change, if you use integration calls, audio will use earpiece, but I will like to use other flag to choose the way to reproduce audio. Is there already any flag created to support this feature?

If there aren't other flag, can you help me to use a flag (whatever) to get its value true or false in AudioModeModule and replace useConnectionService() method in this conditional with the value of other flag?

Thank you very much.

**Comment by saghul** [comment]
No follow-up, closing.
