### ISSUE TITLE
support for react-native 0.64+ 

### ISSUE THREAD

**Issue by aizenka** [jitsi/jitsi-meet#10192]
Hi, are you going to add support for react-native v0.64?

**Comment by hardikcc** [comment]
Is this happened? Please advise.

**Comment by saghul** [comment]
Yes, master is on 0.66

**Comment by hardikcc** [comment]
Thanks for the information, however when I am using the app with 0.64.2 with android, buttons on the UI doesn't work. Is this known issue?

**Comment by saghul** [comment]
We jumped from 0.61 to 0.63 to 0.66. If you are running 0.64 you must have made changes yourself. I'm not aware of such issues.

**Comment by hardikcc** [comment]
Strange, I tried with 0.66 too. Buttons on video-call screen don't do any action.

**Comment by saghul** [comment]
What are you trying exactly?

**Comment by hardikcc** [comment]
I am trying to run example video conference. I have tried almost all react-native versions (0.63, 0.64, 0.66, latest), but not able to run it with react navigation which also uses reanimated.

**Comment by saghul** [comment]
This project already uses react-navigation and reanimated. Are you just modifying Jitsi Meet?

**Comment by hardikcc** [comment]
Ok, so I created a new project with 0.66 RN. Added react-native-jitsi-meet and run the project on Android phone. 1st Issue that I am facing with any version after 0.63, is that no buttons work. 

What can be done in this case? I don't want to use 0.63 as it has so many venerability.

**Comment by saghul** [comment]
I see now. We are not the maintainers of react-native-jitsi-meet, so I cannot help you. I can't recommend that package, it uses our native SDK which means there will be RN version conflicts, as you are experiencing.

Unfortunately we have no RN SDK at the moment.

**Comment by rcidt** [comment]
@hardikcc try this solution https://github.com/skrafft/react-native-jitsi-meet/issues/265#issuecomment-1065550409
