### ISSUE TITLE
When joining a room that requires the host to be authenticated, waiting participants on mobile apps don't join after the room was opened

### ISSUE THREAD

**Issue by AliKarpuzoglu** [jitsi/jitsi-meet#10211]
### Description:

When a participant is waiting for the conference to be opened on the mobile app (both iOS and Android) - and a host opens the room on another device (I tested it with Chrome), the waiting users don't get notified that the room is opened, and are stuck on the screen asking to authenticate or wait for the host to arrive.
### Steps to reproduce:

1. Join a conference that requires a login to use with a mobile app
2. open the meeting with another device
3. the meeting is open, but the mobile devices are still waiting

### Expected behavior:

Users on mobile devices should enter the room 
### Actual behavior:

They don't join, they're stuck waiting. They are forced to disconnect and reconnect

### Server information:

- Jitsi Meet version: current stable [(6433)](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_6433)
- Operating System:  Debian

### Client information:

- Browser / app version: iOS 21.4.3 b113/ Android: 21.4.1 b 8662254
- Operating System: iOS 15 /Android 9

**Comment by csett86** [comment]
A public server where this can be reproduced: https://sichere-videokonferenz.de/

**Comment by csett86** [comment]
Confirmed that iOS (and probably android) app version 21.5.0 are still affected.
