### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by AtifShahzed** [jitsi/jitsi-meet#10215]
I am using latest version and hosted on Linux I am using api mode and integrated quite easily.
Now during QA and testing we are getting two errors which is occurring internally details are as follows

1) When someone left the conversation so this is the error is occurring in console.
**Logger.js:154 2021-10-20T21:21:39.533Z [modules/connectivity/ParticipantConnectionStatus.js] <g.onTrackRtcMuted>:  No participant for id: 743b54ea
o @ Logger.js:154
onTrackRtcMuted @ ParticipantConnectionStatus.js:808
a.emit @ events.js:152
_onTrackMute @ JitsiRemoteTrack.js:116
(anonymous) @ JitsiRemoteTrack.js:99**

2) This is another error but not sure the scenario might details would help you to diagnose the issue.
**myApp.js:199 Uncaught TypeError: Cannot set properties of null (setting 'src')
    at M.screenSharingStatusChanged (myApp.js:199)
    at M.a.emit (events.js:152)
    at external_api.js:560
    at Transport.js:128
    at Set.forEach (<anonymous>)
    at L.emit (Transport.js:127)
    at L._onMessageReceived (Transport.js:98)
    at PostMessageTransportBackend.js:43
    at u (postis.js:55)
screenSharingStatusChanged @ myApp.js:199
a.emit @ events.js:152
(anonymous) @ external_api.js:560
(anonymous) @ Transport.js:128
emit @ Transport.js:127
_onMessageReceived @ Transport.js:98
(anonymous) @ PostMessageTransportBackend.js:43
u @ postis.js:55**

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.



> 1. When someone left the conversation so this is the error is occurring in console.
>    **Logger.js:154 2021-10-20T21:21:39.533Z [modules/connectivity/ParticipantConnectionStatus.js] <g.onTrackRtcMuted>:  No participant for id: 743b54ea**

That is normal you can ignore that.



> 2\. This is another error but not sure the scenario might details would help you to diagnose the issue.
>     **myApp.js:199 Uncaught TypeError: Cannot set properties of null (setting 'src')
>     at M.screenSharingStatusChanged (myApp.js:199)
>     at M.a.emit (events.js:152)
>     at external_api.js:560**

This is an error in your code - myApp.js:199.
