### ISSUE TITLE
No Audio Only Video

### ISSUE THREAD

**Issue by Elqul** [jitsi/jitsi-meet#1021]
Hello,

I followed the the instructions from quick-install.md and my instance is running properly but audio is not going through in the conference.
this is the error i see in the browser logs.
```
 Error: No opened data channels found!(…)
[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError:  Script: null Line: null Column: null StackTrace:  Error: No opened data channels found!(…)
```

**Comment by Elqul** [comment]
okay this has been solved. it was because udp ports were closed. ports 10000 through 20000

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems before opening issues.
