### ISSUE TITLE
Enable poll moderation setting

### ISSUE THREAD

**Issue by dimitardelchev93** [jitsi/jitsi-meet#10225]
In big conferences the moderators may not want for normal participant to create polls, it is sometimes very helpful if they are able to show/hide/import/export the polls too. So this setting may be a good feature in those cases.

The solution I propose is to have an `enablePollsModeration`, which when set to `true`, will give the moderators those extra options, and limit the normal participant from creating polls.

What normal participant will see in the polls panel:

![image](https://user-images.githubusercontent.com/43634401/138308963-c49925be-4319-4f28-893f-ec4fe328577e.png)

What moderators will see in the polls panel:

![image](https://user-images.githubusercontent.com/43634401/138311822-d4c65d32-edb9-485a-b870-89a536e55d09.png)

* if `enablePollsModeration` is not set to `true`, the behavior remains the same as before

**Comment by esra9910** [comment]
Hello @dimitardelchev93 can I ask in which File you change the settings of enablePollsModeration?
