### ISSUE TITLE
Suboptimal browser warning

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#10236]
### Description:

The warnings stating of the current browser has a suboptimal experience are not translated.

**main.json** (English)

```
"notify": {
        "suboptimalBrowserWarning": "We are afraid your meeting experience isn't going to be that great here. We are looking for ways to improve this, but until then please try using one of the <a href='{{recommendedBrowserPageLink}}' target='_blank'>fully supported browsers</a>.",
}
```

**main-pt.json** (Portuguese)

```
"notify": {
        "suboptimalBrowserWarning": "Tememos que sua experiência de reunião não seja tão boa aqui. Estamos procurando maneiras de melhorar isso, mas até então, tente usar um dos <a href='{{recommendedBrowserPageLink}}' target='_blank'>navegadores completamente suportados</a>.",
}
```

In the Portuguese language it doesn't show the translation.

![imagem](https://user-images.githubusercontent.com/32515675/138475809-05d16760-f32d-48bb-9609-cb66840bef3f.jpg)

### Steps to reproduce:

In interface_config.js switch to
`OPTIMAL_BROWSERS: []`

In the settings change to other language.

### Expected behavior:

The warning should be configured to other language.

### Actual behavior:

The result is always the same: English text.

### Server information:

- Jitsi Meet version: meet.jit.si

### Client information:

- Browser / app version: Chrome 95
- Operating System: macOS 11.6

**Comment by gpatel-fr** [comment]
This is a timing initialization problem.
Proof, this is fixing it:
```

diff --git a/react/features/conference/functions.web.js b/react/features/conference/functions.web.js
index a2db54596..d8739f5e6 100644
--- a/react/features/conference/functions.web.js
+++ b/react/features/conference/functions.web.js
@@ -1,5 +1,5 @@
 import { isSuboptimalBrowser } from '../base/environment';
-import { translateToHTML } from '../base/i18n';
+import { i18next, translateToHTML } from '../base/i18n';
 import { showWarningNotification } from '../notifications';
 
 export * from './functions.any';
@@ -13,6 +13,7 @@ export * from './functions.any';
  */
 export function maybeShowSuboptimalExperienceNotification(dispatch, t) {
     if (isSuboptimalBrowser()) {
+        i18next.on('initialized', function(options) {
         dispatch(
             showWarningNotification(
                 {
@@ -27,5 +28,6 @@ export function maybeShowSuboptimalExperienceNotification(dispatch, t) {
                 }
             )
         );
-    }
+    });
+  }
 }
```

Now, I'm afraid that such a change could simply paper on another bug, since it's very weird that in master, the key (title) is displyed first in english then replaced with the localized version after a few seconds, but not the description. Could it be a problem with react-i18next ?

**Comment by damencho** [comment]
English is bundled in the app.bundle, where the other languages are downloaded on demand after reading the local config.

**Comment by cristianorolim** [comment]
We are still getting this issue using docker deployment version stable-7001.
