### ISSUE TITLE
Add Library on Maven

### ISSUE THREAD

**Issue by ansh2166** [jitsi/jitsi-meet#10238]
If Library is uploaded on maven, it will be dope !

**Comment by hafizworqapp** [comment]
What they mean is that use mavencentral instead jcenter

**Comment by saghul** [comment]
We use neither, but provide our own repo: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#use-pre-build-sdk-artifactsbinaries

**Comment by hafizworqapp** [comment]
@saghul but if i remove jcenter() it is not working why?

**Comment by saghul** [comment]
Our SDK is not on jcenter, so I don't know what your problem is really.
