### ISSUE TITLE
last-n is set to 1 when entering PiP, isn't raised back when exiting PiP

### ISSUE THREAD

**Issue by lultimouomo** [jitsi/jitsi-meet#10257]
### Description:

Both on Android and iOS, entering PiP sets last-n to 1, but exiting PiP doesn't raise it back, which causes a bunch of video-less rectangles to be shown in grid mode.
I think what is happening is the following: by entering PiP the window becomes smaller than [REDUCED_UI_THRESHOLD](https://github.com/jitsi/jitsi-meet/blob/1793bf460e24591f9e945c2e2294c37cab5f5fb5/react/features/base/responsive-ui/actions.js#L22), this causes the UI to toggle to reduced mode, which [disables the filmstrip](https://github.com/jitsi/jitsi-meet/blob/1793bf460e24591f9e945c2e2294c37cab5f5fb5/react/features/conference/middleware.js#L31).
lastn middleware is [listening for fimstrip changes](https://github.com/jitsi/jitsi-meet/blob/1793bf460e24591f9e945c2e2294c37cab5f5fb5/react/features/base/lastn/middleware.js#L101), and calls `_updateLastN`, which finds that [filmStrip is not enabled and sets last-n to 1](https://github.com/jitsi/jitsi-meet/blob/1793bf460e24591f9e945c2e2294c37cab5f5fb5/react/features/base/lastn/middleware.js#L81). 

When PiP is exited, the filmstrip is enabled again and `_updateLastN` is called; but since [by default it will use the last selected value](https://github.com/jitsi/jitsi-meet/blob/1793bf460e24591f9e945c2e2294c37cab5f5fb5/react/features/base/lastn/middleware.js#L56), it just sets last-n again to 1.

The only way to exit the impasse is enter audio-only mode; this [sets last-n to 0](https://github.com/jitsi/jitsi-meet/blob/1793bf460e24591f9e945c2e2294c37cab5f5fb5/react/features/base/lastn/middleware.js#L79), which is falsey and therefore is not considered [when computing lastNSelected](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/lastn/middleware.js#L56)

This happens both when using the SDK in a 3rd party app and when using the official Jitsi app (at least on Android, on iOS I only tried the SDK)

### Steps to reproduce:

1. Open Jitsi app on mobile
2. Join conference with at least two other participants
3. Enter PiP
4. Exit PiP

### Expected behavior:

When exiting PiP, last-n is restored to the initial value and you can see multiple video streams

### Actual behavior:

last-n is set again to 1 (as shown by android logcat), only your own video + one other participant is shown

### Server information:

Happens both on self-hosted server and meet.jit.si

### Client information:

- Browser / app version: Happens on Jitsi Meet for Android 21.4.1, Android SDK 3.10.2, iOS SDK 3.10.4
- Operating System:

### Additional information:

A possible solution would be to store the requested last-n separately from the one that is applied, which could be lower because of audio-only, PiP, etc.

**Comment by lultimouomo** [comment]
Any chance someone can take a look at the open PR fixing this issue?

**Comment by saghul** [comment]
I just left a review.
