### ISSUE TITLE
Virtual backgrounds Option not available in Android and iOS

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#10254]
I am not able to find "Select Backgrounds"  Option for Mobile (Android and iOS

![Screenshot_1635248618](https://user-images.githubusercontent.com/49673803/138887459-8374895a-b133-49f5-91a6-a34f0da9e7fc.png)

But its there in web.
<img width="239" alt="Screenshot 2021-10-26 at 5 16 49 PM" src="https://user-images.githubusercontent.com/49673803/138871591-98d2520d-4e7e-4d48-9e18-b3756936183c.png">

Thanks

**Comment by beheobong** [comment]
any update?

**Comment by saghul** [comment]
No updates.

**Comment by beheobong** [comment]
Is there a way to integrate deepAR (https://www.deepar.ai/) or faceunity (http://www.faceunity.com/) technology?

**Comment by saghul** [comment]
We haven't investigated integrating those projects.

**Comment by dsvk** [comment]
Still valid.
