### ISSUE TITLE
Allow to raise speaker volume above 100%

### ISSUE THREAD

**Issue by wavexx** [jitsi/jitsi-meet#10267]
**Is your feature request related to a problem you are facing?**
Sometimes in a meeting a single user has a poor microphone he cannot adjust for some reason (browser issue, mic issue, unfamiliarity with mic controls, or any other reason really).

In such cases, it's impossible to raise the speaker volume level above the default, which is already 100%.

**Describe the solution you'd like**
The volume slider should allow to raise the volume of a speaker above 100%, such as 150%.

**Describe alternatives you've considered**
The current work-around I'm using is to lower the volume of every other speaker, then raise the system volume, which works, but is incredibly silly and time consuming.

By the way, local volume control of speakers is why I consider jitsi to be one of the best meeting solutions right now.

**Comment by wavexx** [comment]
Bad bot

**Comment by Bleuzen** [comment]
Yeah, this would be really helpful :)

An idea, please also add text to the slider and a little marker to easily snap the volume back to original, something like this:

![image](https://user-images.githubusercontent.com/12885163/204050536-3a07227a-9948-45f8-830c-7c9119032bf2.png)

Or an alternative, with more fine grain control:

![image](https://user-images.githubusercontent.com/12885163/204050585-a1058631-d1b0-4a3d-af63-d4f1406b2712.png)

**Comment by Bleuzen** [comment]
@saghul why was this closed? would be really useful

**Comment by saghul** [comment]
We have no plans to implement it, sorry.
