### ISSUE TITLE
Getting Delay  in Voice connection 

### ISSUE THREAD

**Issue by kirtirc** [jitsi/jitsi-meet#10272]
Hello @saghul 
we are using jitsi SDK  in IOS, Android  and  when  try to connect them   then it taking 3-4 second delay for voice connection so initial we are not hearing each other  and we tested  in wifi with good internet speed.

Can you help me, how to increase speed  to make voice connection fast .
Thanks

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by kirtirc** [comment]
Hello @saghul  @damencho 
we are using  self-hosted server but  problem also occur  meet.jit.si too
i downloaded your jitsi meet app from app store and checked that   it take 3-4 second  first time connection even if good internet connection

here is step to reproduce  issue 
1.Take 2 Device and open app (make sure app not running in  background ,kill app  and open again )  
2. Enter room name in in first device  then enter same room name in second device 
Thanks
