### ISSUE TITLE
Unable to adjust volume of video someone else is sharing to me.

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#10278]
### Description:

When sharing a YouTube video, the volume is stuck at full blast even when the person sharing lowers the volume using the slider.

### Steps to reproduce:

1. Click Share Video
2. Share YouTube video
3. Other users can't adjust volume.

### Expected behavior:

Every user should be able to adjust the volume locally for themselves.

### Actual behavior:

Right now it's stuck at full volume for every user except the user who shares the video and is very loud.

### Server information:

- Jitsi Meet version: 2.0.6433
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Firefox 93
- Operating System: Windows 11 64x

**Comment by darkHarry** [comment]
Hi @DillFrescott! The `controls` are hidden for other participants and hence volume controls are also hidden for them and as far as I know, the [Youtube Iframe player API](https://developers.google.com/youtube/player_parameters) does not provide any parameter to display only the volume control.

Also, this line of code in `YoutubeVideoManager.js` attaches a callback for the `onVolumeChange` event in the Youtube iframe player.
```
this.player.addEventListener('onVolumeChange', () => {
    this.onVolumeChange();
})
```
which is not documented as one of the events that the Youtube iframe player handles.

This functionality can be achieved by rendering a separate volume control and manually setting/getting the volume level from the Youtube Iframe player.
Maybe someone can shed more light on this. Until then you can adjust your system volume :sweat_smile:

**Comment by DillFrescott** [comment]
@darkHarry Got it! Thanks so much for the info!

**Comment by cloudishBenne** [comment]
I found this issue because my ears are bleeding right now ^^
Wouldn't it be possible to just add a volume slider to the youtube participant just like the other participants have one? This would not need to fiddle with the youtube api.

**Comment by ata-star** [comment]
jo?

**Comment by 0xDjole** [comment]
can someone please fix this?

**Comment by darkHarry** [comment]
hi @saghul ! is this something we are planning to have as a feature ? if so, i can take it up. : )

**Comment by saghul** [comment]
Sure thing! Before jumping in I'd like to see some little design. Not only UI but also how the feature would actually work.
