### ISSUE TITLE
Old browser support: Promise.allSettled is not a function

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#10281]
### Description:
Firefox 68 & Chrome 73 doesn't work:
```
[conference.js] <prejoinStart>:  An error occurred while trying to join a meeting from the prejoin screen: TypeError: Promise.allSettled is not a function Logger.js:154:22
    o Logger.js:154
    prejoinStart conference.js:870
```

### Steps to reproduce:
1. Get https://ftp.mozilla.org/pub/firefox/releases/68.10.0esr/
2. Open https://meet.jit.si
3. Try to start conference

**Comment by saghul** [comment]
Those versions are no longer supported: https://jitsi.github.io/handbook/docs/user-guide/supported-browsers
