### ISSUE TITLE
Android app not working

### ISSUE THREAD

**Issue by xeruf** [jitsi/jitsi-meet#10285]
### Description:

I can join calls and see other participants that are there, but no audio and video works in either direction.

### Expected behavior:

Calling from Android works seamlessly as it did a few months ago.

### Server information:

Any server (including meet.jit.si)

### Client information:

Installed latest on Android 8.0.0 on a Samsung Galaxy S7 Edge, tried both Google Play Store and F-Droid.

**Comment by saghul** [comment]
Any chance you can test the latest beta version? https://jitsi.github.io/handbook/docs/releases#beta-versions

**Comment by xeruf** [comment]
Tested it from Google Play, no better :/

Btw you should publish beta builds on Android as well, potentially through a self-hosted repository to make automation easier.

**Comment by xeruf** [comment]
A friend with a newer android version has no issues

**Comment by saghul** [comment]
Hum so it might be related to Android 8 somehow. Any chance you can get an `adb logcat` and capture the crash?

**Comment by xeruf** [comment]
There is no crash, please read the above again. But I am indeed proficient using `adb` :)

**Comment by saghul** [comment]
Sorry, I must have mixed issues. Anyway, can you please attach the logcat here?

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by xeruf** [comment]
Yeah, migrated to a new phone, seems it works fine there now ^^

**Comment by MaFreiberger** [comment]
Same problem on Android 9 on Galaxy S8.

Worked fine till some months ago. But works fine in Chrome Browser.

And buying a new smartphone is no solution.

**Comment by MaFreiberger** [comment]
by the way, there are numerous reports of that problem

https://community.jitsi.org/t/jitsi-meet-app-for-android-not-working-for-own-server-bug/37232/2

**Comment by saghul** [comment]
This is issue is over a year old. Can you please open a new one and provide as many details as possible?
