### ISSUE TITLE
Remove Amplitude

### ISSUE THREAD

**Issue by EbelloImbox** [jitsi/jitsi-meet#10306]
Hello, is there any way to remove completely amplitude?

I have removed it from every place, but it is part of the generates maven pom yet when I compile android sdk version. Forthermore I am having some issues to compile my android project without amplitude, somebody has got it?

Regards.

**Comment by EbelloImbox** [comment]
Like always, thank you so much @saghul. One last question, is there something similar to LIBRE_BUILD to use in iOS sdk version?

**Comment by saghul** [comment]
No, there currently isn't. I'd take a PR if you're up for it but TBH I don't even know how to make pods optional.
