### ISSUE TITLE
Add command join lobby in IFrame API

### ISSUE THREAD

**Issue by Payetus** [jitsi/jitsi-meet#10307]
I have an application for a client where we have implemented jitsi with IFrame API, that requires the lobby functionality. The display name is set by another backend so the  "ask to join" is unnecesary and we are looking to remove it. 
![image](https://user-images.githubusercontent.com/3797659/140239925-e6093418-5b5e-4434-b763-bae803757588.png)

**Describe the solution you'd like**
I would like a command "join-lobby" that let me join the lobby, Similar to the function you have in lib-jitsi-meet:
https://github.com/jitsi/lib-jitsi-meet/blob/6418984d3a495677315c2e08c76220b91cea3acd/JitsiConference.js#L3834-L3840

**Comment by Payetus** [comment]
Also this is necesary because some of the texts and buttons are not localized, for example  the "ask to join" button

**Comment by saghul** [comment]
You can help the localization effort by sending PRs to the right language files.

**Comment by Payetus** [comment]
PR created #10310. What about the join-lobby command is it feasible @saghul ?

**Comment by saghul** [comment]
Are you using the iframe API? If so, you can pass along the display name your backend already knows in the userInfo object. Does that help?

**Comment by Payetus** [comment]
I am using the IFrame api. And I am adding de displayName in the userInfo. What I want is to skip de ask to join page by automatically joining lobby.

**Comment by saghul** [comment]
Ah I see. That function will return false if you are not using the prejoin screen, which I suspect you aren't. I'd say a new (overridable) config option which makes auto-knock work regardless of the prejoin screen would be appropriate. Are you willing to send a PR?

**Comment by Payetus** [comment]
Yes, I will start working on it

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/10366
