### ISSUE TITLE
I want to limit the number of people who can participate in one room

### ISSUE THREAD

**Issue by norimakiHKS** [jitsi/jitsi-meet#10320]
### Description:
hi.
I want to limit the number of people who can participate in one room in advance.
Does anyone already have this setting or know what to set?

### Server information:

- Jitsi Meet version:2.0.6433
- Operating System:Ubuntu 20.04.3

**Comment by tanandy** [comment]
Hi you can find the answer on the jitsi forum. Just use prosody modules max_occupants

**Comment by norimakiHKS** [comment]
@tanandy 
thank you very much!
I'll try.

**Comment by tanandy** [comment]
you are welcome, im already using it with success

https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_max_occupants.lua

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_max_occupants.lua
