### ISSUE TITLE
Unwanted "Start subtitles"

### ISSUE THREAD

**Issue by joester89** [jitsi/jitsi-meet#10326]
### Description:

After instantiating Jitsi via the IFrame API, even though all configuration is set, the "Start subtitles" button keeps showing up.

### Steps to reproduce:

In the configuration the next fields have been applied:
- in the JWT, set `transcription` to false
- in `interfaceConfigOverwrite` `DISABLE_TRANSCRIPTION_SUBTITLES` is set to `true`
- in `configOverwrite` `enableFeaturesBasedOnToken` is set to `true`

### Expected behavior:

In the dots menu the item "Start subtitles" should not show up.

### Actual behavior:

In the dots menu the item "Start subtitles" does show up.

**Comment by saghul** [comment]
Can you try setting the `transcribingEnabled` config value? It's not overridable, which I consider a bug...

**Comment by joester89** [comment]
@saghul tried that one this morning, didn't work either...

**Comment by saghul** [comment]
Did you put it in config.js ?

**Comment by joester89** [comment]
I put it in the `configOverwrite` since we are including it via the iframe. Or am I missing something?

**Comment by saghul** [comment]
As I mentioned in https://github.com/jitsi/jitsi-meet/issues/10326#issuecomment-963930263 it's not overridable.

**Comment by joester89** [comment]
How could I test it then? 🙈

**Comment by saghul** [comment]
Then you can't, until we whitelist it.

**Comment by Freddie-m** [comment]
@joester89 I'm assuming this is your self-hosted instance? If so, you can disable the closed captioning (transcription) button from the toolbar array.

https://github.com/jitsi/jitsi-meet/blob/48b12b4e00e1dbd1d9ee1f59fefabc6da142bc4a/config.js#L534

**Comment by joester89** [comment]
I am sorry, we are not hosting it ourselves...
