### ISSUE TITLE
How to destory Jitsi Meet Activity when participate not join after 30 s

### ISSUE THREAD

**Issue by hafizworqapp** [jitsi/jitsi-meet#10339]
Hi there i follow tutorial about jitsi meet. My question is that, on broadcast receiver event when will_join_conference and join_conference i started timer 30 s for checking there is no participate join it so this activity is dismiss/destroy or conference_terminate. So how i can do that in broadcastreceiver?

Sample code

````
when (event.type) {
                BroadcastEvent.Type.CONFERENCE_WILL_JOIN->{
                    Toast.makeText(this, "Conference Will JOin", Toast.LENGTH_SHORT).show()
                }
                BroadcastEvent.Type.CONFERENCE_JOINED ->{
                    Toast.makeText(this, "Conference JOin", Toast.LENGTH_SHORT).show()
                    if(mHandlerTime == null){
                         if(!isAnswerCall){  // set time 30s
                             mHandlerTime = Handler(Looper.myLooper()!!)
                             mHandlerTime?.postDelayed(Runnable {
                                     if(!isAnswerCall){
```
                                        
                                     }
                             }, 30000)
                        }
                    }
                }
                BroadcastEvent.Type.PARTICIPANT_JOINED -> {
                    isAnswerCall = true
                }
                BroadcastEvent.Type.PARTICIPANT_LEFT -> {
                    isAnswerCall = false
                }
                BroadcastEvent.Type.CONFERENCE_TERMINATED -> {
                    isAnswerCall = false
                    mHandlerTime = null
                }
            }`

**Comment by saghul** [comment]
Ping @tmoldovan8x8

**Comment by tmoldovan8x8** [comment]
Hi @hafizworqapp If I understand correctly, you want to terminate the conference/dismiss the view after a certain amount of time. If that is the case you can broadcast the action BroadcastAction.HANG_UP

**Comment by hafizworqapp** [comment]
@tmoldovan8x8 how to do that broadcastaction.Hang_UP??

**Comment by hafizworqapp** [comment]
@tmoldovan8x8  inside this code

```
mHandlerTime = Handler(Looper.myLooper()!!)
                             mHandlerTime?.postDelayed(Runnable {
                                     if(!isAnswerCall){
                                        
```
                                     }
                             }, 30000)

how to do that?

**Comment by tmoldovan8x8** [comment]
Please check the documentation here https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#broadcasting-actions

**Comment by hafizworqapp** [comment]
@tmoldovan8x8 BroadcastAction.HANG_UP is not there in the library. consist of only  CONFERENCE_JOINED("org.jitsi.meet.CONFERENCE_JOINED"),
        CONFERENCE_TERMINATED("org.jitsi.meet.CONFERENCE_TERMINATED"),
        CONFERENCE_WILL_JOIN("org.jitsi.meet.CONFERENCE_WILL_JOIN"),
        AUDIO_MUTED_CHANGED("org.jitsi.meet.AUDIO_MUTED_CHANGED"),
        PARTICIPANT_JOINED("org.jitsi.meet.PARTICIPANT_JOINED"),
        PARTICIPANT_LEFT("org.jitsi.meet.PARTICIPANT_LEFT"),
        ENDPOINT_TEXT_MESSAGE_RECEIVED("org.jitsi.meet.ENDPOINT_TEXT_MESSAGE_RECEIVED"),
        SCREEN_SHARE_TOGGLED("org.jitsi.meet.SCREEN_SHARE_TOGGLED"),
        PARTICIPANTS_INFO_RETRIEVED("org.jitsi.meet.PARTICIPANTS_INFO_RETRIEVED"),
        CHAT_MESSAGE_RECEIVED("org.jitsi.meet.CHAT_MESSAGE_RECEIVED"),
        CHAT_TOGGLED("org.jitsi.meet.CHAT_TOGGLED"),
        VIDEO_MUTED_CHANGED("org.jitsi.meet.VIDEO_MUTED_CHANGED");

**Comment by tmoldovan8x8** [comment]
Those are the BroadcastEvents you listed here, for listening for events that happen in the SDK. BroadcastActions are used for sending actions to the SDK. You can use BroadcastIntentHelper class to build the Intent and broadcast it for the SDK to end the conference.

**Comment by hafizworqapp** [comment]
for those who want terminate conference can follow this code for u reference :

`if(mHandlerTime == null){
                         if(!isAnswerCall){  // set time 30s
                             mHandlerTime = object : CountDownTimer(30000,1000){
                                 override fun onTick(millisUntilFinished: Long) {
                                     isRunnigTime = true
                                 }

                                 override fun onFinish() {
                                    isRunnigTime = false

                                    if(!isAnswerCall){
                                        val intent: Intent =
                                            BroadcastIntentHelper.buildHangUpIntent()
                                        LocalBroadcastManager.getInstance(applicationContext)
                                            .sendBroadcast(intent)
                                    }//terminate conference
                                 }
                             }.start()
                        }
                    }`
