### ISSUE TITLE
Why zoomed in footage then go to picture-in-picture always exceed the boundary box?

### ISSUE THREAD

**Issue by alexivaner** [jitsi/jitsi-meet#10346]
### Description:
I have run Jitsi SDK in Android, I tested some meetings and found some problems. When someone shares their screen and we zoom in the screen share then we go to picture-in-picture, the preview of PIP always exceeds the boundary box. It went normal when we are not zooming in on the screen share, is there a way to fix this? I tried to find a way to fix this but still have not yet found any solution. Below I attach the screenshot so we could understand the problem. Thank you

### Steps to reproduce:

1. Start a meeting, then someone joins and shares their screen.
2. We zoomed in to the screen shared by our colleague.
3. Go to Picture-in-Picture mode

### Expected behavior:
Should be able to display the reduced window normally, the screen does not exceed the boundary

### Actual behavior:
![Screenshot_20211110_175410_com huawei android launcher](https://user-images.githubusercontent.com/57290644/141123998-16424697-bb35-4c4f-b681-22e630da5c73.jpg)
The shared screen will exceed the reduced (PIP) window

### Server information:
- Jitsi Meet version: 2.0.6433 and 1.0.4370
- Operating System: Android

### Client information:
- Operating System: Android

**Comment by saghul** [comment]
Looks like an Android bug, since all we do is specify the size of the PiP window, then the system applies the constraints.

**Comment by alexivaner** [comment]
Is there any possible way if we could remove that border in Android-Native? I think that if we do not have that border, the problem will be solved.

**Comment by saghul** [comment]
I don't know, we don't specify any border.

**Comment by alexivaner** [comment]
Or could you give me the clue how to reset back the zoomed image to Scale:1 before going to Picture-in-Picture? Thank you so much

**Comment by saghul** [comment]
There is no way to do that programatically, we only use gestures for that...

**Comment by alexivaner** [comment]
How to invoke VideoTransform again and set back the gesture to Scale:1 before running NativeModules of Picture in Picture?

**Comment by saghul** [comment]
I just told you, we have no way to do that programatically.

**Comment by alexivaner** [comment]
Hi, I already solve this issue, I managed to rescale it back to DEFAULT_TRANSFORM value before doing pip
