### ISSUE TITLE
dynamic-branding url not loaded

### ISSUE THREAD

**Issue by mattiashallstrom** [jitsi/jitsi-meet#10342]
### Description:

When setting config value dynamicBrandingUrl to my json file hosted on a different server it is not requested.

### Steps to reproduce:

set in config file: dynamicBrandingUrl: 'https://myowndomain.se/videobranding.json',

### Expected behavior:

the json file should be requested and configs applied.

### Actual behavior:

Checking accesslog/errorlog on my other server shows that no request is happening. I can't see any requests in chromes network-console either.
Other config changes apply though.

### Server information:

- Jitsi Meet version: 2.0.6433-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chrome / web
- Operating System: Mac

### Additional information:

I noticed there where some recent changes in handling of dynamicBrandingUrl and config file, but can't tell if it affects.
Using JitsiMeetExternalAPI.

**Comment by WLR86** [comment]
Same here...

**Comment by vp8x8** [comment]
It is a know issue.
There was a commit that introduced this defect (the `dynamicBrandingUrl` was no longer considered):

`feat(dynamic-branding): Add branding option for virtual backgrounds`

This was solved with:

`ddcb85a1d fix(jaas): Get dynamic branding url from config file`

**Comment by mattiashallstrom** [comment]
> It is a know issue. There was a commit that introduced this defect (the `dynamicBrandingUrl` was no longer considered):
> 
> `feat(dynamic-branding): Add branding option for virtual backgrounds`
> 
> This was solved with:
> 
> `ddcb85a1d fix(jaas): Get dynamic branding url from config file`
