### ISSUE TITLE
Running inside virtualbox not working

### ISSUE THREAD

**Issue by singpolyma** [jitsi/jitsi-meet#1035]
When I use in the Firefox in my virtualbox (debian jessie guest), I get asked to share my devices but then jitsi meet just sort of sits there looking at me. On my host system and other computers it works fine. Maybe a NAT issue because my VM adds a NAT layer?

**Comment by damencho** [comment]
Please use the mailinglist when asking question or having problems, before opening issues.

You need to check the firefox console for errors. Nat should not be a problem for clients. You can also try apprtc and see does it work there, it can be something with the devices, or the way we handle them.
