### ISSUE TITLE
New event "I joined"

### ISSUE THREAD

**Issue by mattiashallstrom** [jitsi/jitsi-meet#10359]
I would like to suggest a new event signaling when I as a participant has joined the meeting.
Our implementation works like this; one person triggers creation of meeting and becomes moderator (with jwt), invites are sent to participants that joins via guest but needs to "knock" toe be let into the meeting.

I would like to make an ajax request on the participants page when he/she is let in to log they are joining the meeting.
I can't use participantJoined event because it only gives the moderator/others participants.

An event called something like "iJoined" would be great.
Could be complemented with "iWasKickedOut"

**Comment by saghul** [comment]
CONFERENCE_JOINED means you joined. Does that not suffice for your use case?

**Comment by mattiashallstrom** [comment]
Doesn't that event need lib-jitsi-meet API? I am using IFrame API
Can those be used together?

**Comment by saghul** [comment]
If you are using the iframe API you want to listen for this event: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#videoconferencejoined

**Comment by mattiashallstrom** [comment]
> If you are using the iframe API you want to listen for this event: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#videoconferencejoined

Thanks a lot, my misstake. videoconferenceJoined solves my use case. I only notices participantJoined.
