### ISSUE TITLE
Tile View "Landscape Mode" for Two-Party Calls

### ISSUE THREAD

**Issue by VernPace** [jitsi/jitsi-meet#10358]
The current tile view "portrait mode" for two-party calls incorrectly assumes that only two people will be communicating. There are use cases where more than one person will be in a webcam's field of view, thus requiring the webcam's default "landscape mode" as was Jitsi's tile view behavior not too long ago. For the sake of brevity, I will not elaborate on the use cases for landscape mode here, but would be happy to do so upon request.

This is not a request to roll-back to the old behavior. Instead, there should be an option for landscape mode on two-party calls. This can be implemented with a config option: #config.forceLandscapeMode=true. This option would force both parties into landscape mode.

Here are some related links:
https://community.jitsi.org/t/what-happened-to-tile-view-in-meet-jit-si/107673
https://jitsi.github.io/handbook/docs/user-guide/user-guide-advanced

I cannot see alternative solutions without breaking current functionality.

**Comment by Peter200lx** [comment]
This is much desired for family calls where we would like landscape mode as there are multiple people on both sides. We worked around the problem this week by having two monitors and stretching the browser across both, but that is a very hacky fix. The old behavior was ideal and would be great to have it available as an option.

**Comment by jbg** [comment]
```patch
diff --git a/config.js b/config.js
index 1c1dfe71d..d33151c8a 100644
--- a/config.js
+++ b/config.js
@@ -995,6 +995,9 @@ var config = {
     // If true, tile view will not be enabled automatically when the participants count threshold is reached.
     // disableTileView: true,
 
+    // If true, the tiles will be displayed contained within the available space rather than enlarged to cover it.
+    // disableTileEnlargement: true,
+
     // Controls the visibility and behavior of the top header conference info labels.
     // If a label's id is not in any of the 2 arrays, it will not be visible at all on the header.
     // conferenceInfo: {
diff --git a/react/features/base/config/configWhitelist.js b/react/features/base/config/configWhitelist.js
index 0992fd70b..3bb7e8d51 100644
--- a/react/features/base/config/configWhitelist.js
+++ b/react/features/base/config/configWhitelist.js
@@ -122,6 +122,7 @@ export default [
     'disableSimulcast',
     'disableThirdPartyRequests',
     'disableTileView',
+    'disableTileEnlargement',
     'displayJids',
     'doNotStoreRoom',
     'doNotFlipLocalVideo',
diff --git a/react/features/filmstrip/components/web/Thumbnail.js b/react/features/filmstrip/components/web/Thumbnail.js
index 6104f071c..f9dc77e15 100644
--- a/react/features/filmstrip/components/web/Thumbnail.js
+++ b/react/features/filmstrip/components/web/Thumbnail.js
@@ -581,7 +581,7 @@ class Thumbnail extends Component<Props, State> {
         if (!_isScreenSharing) {
             if (canPlayEventReceived || _participant.local) {
                 videoStyles = {
-                    objectFit: _height < 320 && tileViewActive ? 'contain' : 'cover'
+                    objectFit: (_height < 320 && tileViewActive) || disableTileEnlargement ? 'contain' : 'cover'
                 };
             } else {
                 videoStyles = {
@@ -1125,7 +1125,8 @@ function _mapStateToProps(state, ownProps): Object {
         defaultLocalDisplayName,
         disableLocalVideoFlip,
         iAmRecorder,
-        iAmSipGateway
+        iAmSipGateway,
+        disableTileEnlargement
     } = state['features/base/config'];
     const { NORMAL = 8 } = interfaceConfig.INDICATOR_FONT_SIZES || {};
     const { localFlipX } = state['features/base/settings'];
```

**Comment by saghul** [comment]
@jbg Hey Jasper, mind sending that as an actual PR? We can think about incorporating it.

**Comment by jbg** [comment]
@saghul #10494

**Comment by pascaldragon** [comment]
I'm in support of making this at least configurable. I regulary meet with friends that are two persons with one client and with this sudden change I was no longer able to see them both at once cause the viewport in the tile view only displayed the center of camera where no one was to be seen...

**Comment by saghul** [comment]
It's being considered.

**Comment by k2OS** [comment]
I know this topic was closed 14 days ago and the PR by jbg already has been implemented (thank you!), could it be possible to implement this as a UI option, so non-tech savvy people can change this behaviour in a easy way too? 
Who do I bribe with pizza/beer/Christmas cheer to work on a UI implementation?
