### ISSUE TITLE
Trailing slash leads to 404

### ISSUE THREAD

**Issue by lzmartinico** [jitsi/jitsi-meet#10357]
### Description:
On the hosted jitsi instance, a room URL with a trailing slash leads to a 404. This is confusing for some users, who are used to some websites stripping the trailing slash
### Steps to reproduce:
Navigate to https://meet.jit.si/AwesomeJitsiOnlineMeeting/

### Expected behavior:
The website redirects to https://meet.jit.si/AwesomeJitsiOnlineMeeting

### Actual behavior:
User encounters a 404 error and is not able to join the meeting

### Server information:

- Jitsi Meet version: hosted Jitsi Meet

### Client information:

- Browser / app version: all mainstream browsers
- Operating System: all OSs

**Comment by lzmartinico** [comment]
The issue is still unsolved

**Comment by luzpaz** [comment]
Still reproducible

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
bump
