### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by shizukanaqun** [jitsi/jitsi-meet#10371]
### Description:
npm install error ,because
https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.3.tgz can not download.

**Comment by saghul** [comment]
Must be a problem in your network, that file can be downloaded just fine.

**Comment by haojianxuezhang** [comment]
我也下载不了，好像源不在国内，下载不下来，你解决了吗，大佬

**Comment by jbg** [comment]
@haojianxuezhang 
Being under the matrix.org domain, it's probably blocked in China. better to take this discussion to https://community.jitsi.org/ if you need help with that.

**Comment by shizukanaqun** [comment]
用代理下载下来，然后放到自己服务器上，改下packjson里的路径改为自己服务器的路径然后编译





------------------ Original ------------------
From: haojianxuezhang ***@***.***&gt;
Date: Thu,Dec 16,2021 11:25 AM
To: jitsi/jitsi-meet ***@***.***&gt;
Cc: shizukanaqun ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jitsi/jitsi-meet] npm install error (Issue #10371)





 
我也下载不了，好像源不在国内，下载不下来，你解决了吗，大佬

**Comment by haojianxuezhang** [comment]
就是没找到代理源下载这个资源 @shizukanaqun

**Comment by shizukanaqun** [comment]
我用的是欧洲代理，你是哪个没下载到，我可以发给你





------------------ Original ------------------
From: haojianxuezhang ***@***.***&gt;
Date: Thu,Dec 16,2021 11:55 AM
To: jitsi/jitsi-meet ***@***.***&gt;
Cc: shizukanaqun ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [jitsi/jitsi-meet] npm install error (Issue #10371)





 
就是没找到代理源下载这个资源 @shizukanaqun

**Comment by shizukanaqun** [comment]
我用的是欧洲代理，你是哪个没下载到，我可以发给你





------------------ Original ------------------
From: haojianxuezhang ***@***.***&gt;
Date: Thu,Dec 16,2021 11:55 AM
To: jitsi/jitsi-meet ***@***.***&gt;
Cc: shizukanaqun ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [jitsi/jitsi-meet] npm install error (Issue #10371)





 
就是没找到代理源下载这个资源 @shizukanaqun

**Comment by dualven** [comment]
@shizukanaqun 能发一份给我吗？ 我也换了几个代理 没有下到
https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.3.tgz 

dualven@163.com 可以发到这个邮箱，谢谢

**Comment by shizukanaqun** [comment]
> 

已发，请查收

**Comment by dualven** [comment]
@shizukanaqun 不好意思 ，可能是我这个邮箱有问题，再帮我发下到15776324@qq.com吧，谢谢

**Comment by dualven** [comment]
收到了，谢谢！
