### ISSUE TITLE
Audio not coming from video which Playing in youtube and Other Player when we sharing the screen in Android/iOS. But in Web it's working. At the same time Participant and Youtube audio is coming.

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#10373]
Audio not coming from video which Playing in youtube and Other Player when we sharing the screen in Android/iOS. But in Web it's working(at the same time Participant and Youtube audio is coming). Is this is the bug with Jitsi Meet for mobile ? 

Thanks

**Comment by saghul** [comment]
It's not possible to share the system audio while sharing the screen on mobile. It's a system limitation.
