### ISSUE TITLE
jitsi-meet-electron Android client enters the private server and "disconnected" appears

### ISSUE THREAD

**Issue by kda186** [jitsi/jitsi-meet#10370]
jitsi-meet-electron Android client enters the private server and "disconnected" appears

The HTTPS private server is deployed correctly.
Use jitsi-meet-electron IOS, Windows client to work OK
Use WEB client, android, IOS, Windows, Linux client work OK

Use jitsi-meet-electron Android client to set the private server address,

Join the meeting, "disconnected" message appears

Android client version 21.4.1 build 214010 Google market

Issues has similar problem descriptions, but it seems that this will not be an SSL certificate problem, because it works on Android, using a WEB browser.

Any suggestions?

**Comment by saghul** [comment]
jitsi-meet-electron does not work on android or iOS. Can you please clarify what you are experiencing?

**Comment by kda186** [comment]
Sorry, I may have made the wrong expression

My problem is that I use the google store to download jitsi meet and connect to a private server. "Disconnected" will appear.

**Comment by saghul** [comment]
Check if your chain cert is correct: https://whatsmychaincert.com/ that is usually the cause.

**Comment by kda186** [comment]
> 检查您的链证书是否正确：[https](https://whatsmychaincert.com/) : [//whatsmychaincert.com/](https://whatsmychaincert.com/)这通常是原因。

@saghul  


Yes, I checked that the certificate chain is correct.

I also downloaded the certificate chain obtained from https://whatsmychaincert.com/, and replaced it with /etc/nginx/cert/Domain.crt

Restart the server, the problem still exists

Do you have any suggestions?

**Comment by kda186** [comment]
@saghul 

Sorry, you are correct, the problem can be solved by correcting the certificate chain.

My problem is that the configuration path is wrong, resulting in incorrect coverage.

thank you for your help

**Comment by saghul** [comment]
Glad it worked!
