### ISSUE TITLE
Android 11 App Disconnect Loop

### ISSUE THREAD

**Issue by dnisbetjones** [jitsi/jitsi-meet#10396]
### Description:

Android 11 (LineageOS 18.1) Jitsi Meet app enters a disconnect loop on joining private server. The app can connect to Jitsi Meet's default server without problem.

I can confirm that the server has valid certificates, is up to date and works from a web browser on that device. It also connects no problem on iOS, on older versions of Android and on all desktop clients.

### Client information:

- Browser / app version: Android 21.4.1 (F-Droid & Play both)
- Operating System: Android 11 / LineageOS 18.1

Issue may be related to #10370

**Comment by damencho** [comment]
Have you checked the chain for the certs? https://whatsmychaincert.com/

**Comment by dnisbetjones** [comment]
Hi @damencho 

It has the correct chain.

Thank you for the response!

**Comment by saghul** [comment]
Can you check the logs with adb?

**Comment by dnisbetjones** [comment]
@saghul thanks for the reply. I will see if I am able to do that and report back.

**Comment by dnisbetjones** [comment]
Ok, I pulled the logs and here are some relevant errors:

` 11-20 10:07:02.048   718  6596 E JitsiMeetSDK: [features/base/lib-jitsi-meet] Failed to load config from https://*******/config.js?room=test Error(TypeError){"message":"Network request failed","stack":"onerror@index.android.bundle:139:7285\ndispatchEvent@index.android.bundle:130:5676\nvalue@index.android.bundle:125:6095\nvalue@index.android.bundle:125:2835\nvalue@index.android.bundle:50:1280\nvalue@index.android.bundle:37:3685\nindex.android.bundle:37:841\nvalue@index.android.bundle:37:2939\nvalue@index.android.bundle:37:813\nvalue@[native code]"}
11-20 10:07:02.090   718  6596 I JitsiMeetSDK: [features/overlay] The conference will be reloaded after 16 seconds.
11-20 10:07:02.090   718  6596 D JitsiMeetSDK: ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"url":"https://*******/test","error":"TypeError: Network request failed"} }
11-20 10:07:02.093   718   718 D JitsiMeetActivity: Conference terminated: {error=TypeError: Network request failed, url=https://*******/test}`

**Comment by saghul** [comment]
Hum that's odd. That error is either there is no network connection (not the case) or a bogus TLS certificate in the server. Do you get no warnings if you open the URL with your mobile browser?

**Comment by dnisbetjones** [comment]
I went ahead and scrapped the server, started it over and registered a fresh certificate so I will let you know if there are any changes.

**Comment by dnisbetjones** [comment]
It appears that everything is fine now so I will close the issue. I'm not sure what happened but I suppose this is certificate-related.

**Comment by 06065044** [comment]
Failed to load config from https://meet.jit.si/config.js?room=test123

**Comment by 06065044** [comment]
URL serverURL;
        try {
            serverURL = new URL("https://meet.jit.si"); https://meet.jit.si
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions defaultOptions
                = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setWelcomePageEnabled(true)
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);

        JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setRoom("test123")
                .setAudioMuted(false)
                .setVideoMuted(false)
                .setAudioOnly(false)
                .setWelcomePageEnabled(false)
                .build();
        // Launch the new activity with the given options. The launch() method takes care
        // of creating the required Intent and passing the options.
        JitsiMeetActivity.launch(this, options);

**Comment by damian101** [comment]
I have the exact same issue, since switching to LineageOS.

**Comment by saghul** [comment]
Do you get any warnings when opening the URL in the web browser?

**Comment by damian101** [comment]
> Do you get any warnings when opening the URL in the web browser?

No, in browser everything works fine.

**Comment by saghul** [comment]
Not sure what the problem could be :-/

**Comment by lephat08** [comment]
URL: https://record-drimase.ddns.net/

**Comment by saghul** [comment]
The URl you shared (and then deleted it seems) doesn't open for me.

**Comment by lephat08** [comment]
> 

I have re-open it could you help me to resolve the issues on the mobile app that could not add custom URL :(

**Comment by saghul** [comment]
I don't know what you are asking. Without a URL to test with I cannot tell you what is wrong.

**Comment by lephat08** [comment]
> 

URL: https://record-drimase.ddns.net/

**Comment by saghul** [comment]
Got it. There is a bug in our latest stable unfortunately. Edit config.js and at the bottom, replace this:

```
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
```

With this:

```
config.flags = {};
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
```

**Comment by lephat08** [comment]
> Got it. There is a bug in our latest stable, unfortunately. Edit config.js and at the bottom, replace this:
> 
> ```
> config.flags.sourceNameSignaling = true;
> config.flags.sendMultipleVideoStreams = true;
> config.flags.receiveMultipleVideoStreams = true;
> ```
> 
> With this:
> 
> ```
> config.flags = {};
> config.flags.sourceNameSignaling = true;
> config.flags.sendMultipleVideoStreams = true;
> config.flags.receiveMultipleVideoStreams = true;
> ```

It's working thanks so much

**Comment by defuzex61** [comment]
Hello, I have error: [features/base/lib-jitsi-meet] Failed to load config from https://vision-video-node1.hprspc.com/config.js?room=83390... Error(TypeError){"message":"Network request failed","stack":"index.android.bundle:147:8060\nindex.android....
How solve the problem?  My code: val url = URL("https://vision-video-node1.hprspc.com")
            val options: JitsiMeetConferenceOptions = JitsiMeetConferenceOptions.Builder()
                //.setServerURL(URL("https://vision-video-node1.hprspc.com"))
                .setServerURL(url)
                .setRoom(_binding!!.dialogConfEt.text.toString())
                .setToken(token)
                .setAudioMuted(false)
                .setVideoMuted(false)
                .setAudioOnly(false)
                .setFeatureFlag( "setWelcomePageEnabled", false)
                .setConfigOverride("requireDisplayName", true)
                .setConfigOverride("customToolbarButtons", "customToolbarButtons")
                .build() hlp pls...

**Comment by damencho** [comment]
Make sure you use the full chain of certs for the website. You can check it for example here: https://whatsmychaincert.com/

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum.

**Comment by YonLD** [comment]
My solution is to use Apache or Nginx to proxy the Jitsi server to port 443.

https://jitsi.example.com -> https://example.com:8443
