### ISSUE TITLE
Sometimes other's cameras randomly turn off and go inactive or connection lost for no reason

### ISSUE THREAD

**Issue by bertvandepoel** [jitsi/jitsi-meet#10409]
### Description:

Recently, we guess since upgrading to 2.0.6433-1 (and associated stable components through the apt repo: Depends: jicofo (= 1.0-813-1), jitsi-meet-web (= 1.0.5415-1), jitsi-meet-web-config (= 1.0.5415-1), jitsi-meet-prosody (= 1.0.5415-1) PreDepends: jitsi-videobridge2 (= 2.1-570-gb802be83-1)), we've been noticing in group audio+video calls that sometimes for one or some of us, webcams of others suddenly disappear. This doesn't consistently happen for one specific person or for everyone, it seems random in both directions. The cameras disappear with either "connection lost" or that they're inactive, but the person associated can still speak and the person experiencing this bug can still hear them. Either after a while they reappear, or a quick refresh is required. We're not quite sure what is causing this problem since we don't see any clear errors, there's no consistent browser that has this problem, and we haven't noticed any patterns. Feel free to suggest any logs to look in and check for specific messages.

### Steps to reproduce:

1. Join a group call
2. Talk for a while with webcams on

### Expected behavior:

Webcams continue to work

### Actual behavior:

Webcams randomly turn off with messages such as "connection lost" or "inactive" when hovering over the little corner icon

### Server information:

- Jitsi Meet version: 2.0.6433-1
- Operating System: Ubuntu 20.04 LTS

### Client information:

- Browser / app version: Chromium Version 95.0.4638.69 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
- Operating System: Ubuntu 18.04

- Browser / app version: Firefox 94.0
- Operating System: Arch Linux

- Browser / app version: Chromium 95.0.4638.69
- Operating System: Fedora Linux 34

**Comment by saghul** [comment]
Do you see the connection icon going gray or do you see a ghost icon?

**Comment by bertvandepoel** [comment]
When it's marked as "connection lost" it's a gray icon, with "connection inactive" it's the blue and white icon with some kind of symbol I don't recognise. Does that help?

**Comment by saghul** [comment]
That blue and white icon resembles a ghost, it means the bridge thinks you don't have enough bandwidth and thus suspended sending that participant's video.

**Comment by bertvandepoel** [comment]
Oh ok, never noticed it resembled a ghost. Hopefully I'll see it next time :)

More often the problem pops up with the grey icon, the ghost icon might actually be some kind of issue with someone's internet then, but usually it's the grey icon. It happens so frequently and to so many different people, that I can't believe it's anything connection related. In the past we used our Jitsi instance without any trouble, so I guess it's some kind of regression bug in one of the latest releases.

**Comment by davidhalter** [comment]
We have the same issue. It's pretty usual that almost all participants have this issue. The last time I checked the server was on 30% RAM and 0.4 CPU load. Users have Ubuntu/Debian/Mac, sometimes newer machines, sometimes older. It does not really matter.

I'm also pretty sure that a few months ago it was working fine and it's now worse in the latest versions.

We can also probably replicate it if some dev wants to join me.

**Comment by sebasvdonk** [comment]
We also got the same issue, we received alot of warnings from Jicofo that participants were being rate limited.
 Also, this is what the icon with the info looked like for us.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/90688061/143046722-8d58ee4f-d6fe-4947-bc91-b097df612ad6.png)
e.

**Comment by Shubhra1028** [comment]
Same happened with me. The videos just randomly stop showing even though the person at the other side have their camera on.

Any Idea why this is happening?

**Comment by saghul** [comment]
Do you see the same in meet.jit.si ? The current stable release is a couple of months old...

**Comment by bertvandepoel** [comment]
We just tested with 12 people on meet.jit.si and we get the same issue there as well. It doesn't seem to be fixed in unstable/trunk then, I guess.

**Comment by bertvandepoel** [comment]
We've done some more testing on our instance (on the latest stable version). Disabling bandwidth detection does not resolve the issue. In the logs we see entries like the following:
```
JVB 2021-11-30 00:16:09.421 WARNING: [75] [confId=b90326a955a2b237 epId=5e91782d gid=104014 stats_id=Sydnee-4Go conf_name=XXXXX ssrc=3337000809] RetransmissionRequester$StreamPacketRequester.packetReceived#118: 3337000809 large jump in sequence numbers detected (highest received was 427, current is 31411, jump of 30983) , not requesting retransmissions
```
around the time the issue takes places or resolves itself. But we're not sure if it's well-timed enough to be related.

**Comment by capital-G** [comment]
Updating our docker instance to the unstable channel fixed the problem for our instance.
Before this we experienced massive problems with the stable version `6433`. the logs of jvb was spammed with

```
jvb_1      | INFO: Endpoints were suspended due to insufficient bandwidth (bwe=192812 bps): d5f7a7e5
jvb_1      | Nov 30, 2021 2:12:48 PM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | WARNING: Invalid message received (Parameter specified as non-null is null: method org.jitsi.videobridge.message.EndpointStats.put, parameter value (through reference chain: org.jitsi.videobridge.message.EndpointStats["connectionQuality"]): {"colibriClass":"EndpointStats","bitrate":{"upload":147,"download":954,"audio":{"upload":13,"download":47},"video":{"upload":134,"download":907}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":null,"jvbRTT":47,"maxEnabledResolution":180}
jvb_1      | Nov 30, 2021 2:12:48 PM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | INFO: Endpoints were suspended due to insufficient bandwidth (bwe=238805 bps): d5f7a7e5
```

although this also occurred also on "high-quality" internet connections.
Although we had no problems on meet.jit.si today, although I am unsure which version is deployed there.

**Comment by damencho** [comment]
meet.jit.si is running the latest stable version, which hasn't hit docker yet https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md#206689-2021-12-06

**Comment by danielittlewood0** [comment]
I can confirm this is still happening for us with latest stable. It seems to have got worse over time. Any call over 6 people is mostly black squares.

**Comment by prasket** [comment]
We are also seeing this behavior for some time. We used Jitsi for the Seattle GNU/Linux Con this year and had an amusing experience with this with 50+ people on a call with video popping on and off.  :) 

I think I noticed something odd as well, which is what made me look for an issue, what I noticed is that when a user spoke their video would come back, or even made a noise on mic. Made me wonder if it was some kind of new bandwidth saving "feature".

**Comment by jbg** [comment]
That's not a new feature; when bandwidth is limited between server and client, the most recent active speakers are prioritised. The impact of suspending the video of a passive participant who is listening but not speaking is less than the impact of suspending the video of someone who is actively speaking.

With 50+ people on a call and all sending video, the bandwidth requirements (especially at the server) are quite high, it's not very surprising that  there would be some congestion somewhere unless you've provisioned guaranteed bandwidth everywhere.

**Comment by kolAflash** [comment]
@jbg  
How does the server detect when the bandwith limit is too low?
By the rate of package loss?

Have there been changes to this mechanism since summer 2021, which could be the cause to the increased number of reports about this issue?
(I'm affected too on multiple servers maintained by others and one by myself)

And are there config parameters to control that machanism?
E.g. set the limit for the package loss at which a webcam gets suspended?
Or a parameter to explicitly tell the Jisti-Meet server the bandwith of the servers internet connection?

**Comment by kolAflash** [comment]
Just found some settings to control the BWE (BandWith Estimation) mechanism and when webcams are "suspended".

&nbsp;

---

&nbsp;

`/etc/jitsi/videobridge/sip-communicator.properties`
```
# Switches off the BWE mechanism.
org.jitsi.videobridge.TRUST_BWE=false
```

&nbsp;

Search here for "BWE" to find other relevant settings:  
https://github.com/jitsi/jitsi-videobridge/blob/master/CONFIG.md

https://community.jitsi.org/t/videobridge-automatic-bandwidth-too-low/75111

&nbsp;

---

&nbsp;

`/etc/jitsi/meet/<domain>-config.js`
```
# show all participant videos
channelLastN: -1

# show videos of last 4 active speakers only although everyone has video enabled
channelLastN: 4
```

https://community.jitsi.org/t/what-exactly-is-the-effect-of-channellastn/25244

https://www.kuketz-blog.de/jitsi-meet-optimierung-der-performance/

https://github.com/jitsi/jitsi-videobridge/issues/76

**Comment by jbg** [comment]
`org.jitsi.videobridge.TRUST_BWE=false` disables BWE entirely. This means that when users have packet loss / limited bandwidth, the videobridge will not react by adjusting sending rate, and users risk broken video streams and maybe even broken audio, whereas with BWE enabled they would instead have lower resolution or some suspended streams. It's not a good idea on a deployment that users access over the Internet — pretending that connection quality issues don't exist doesn't make them go away. It would be OK on a local, controlled network with guaranteed bandwidth (but in that case it shouldn't be necessary to disable it anyway).

If you have `channelLastN` set to some value > -1, then you'll only receive that many streams no matter what. This setting doesn't affect bandwidth estimation itself; it's a hard maximum regardless of available bandwidth.

**Comment by nicoasi** [comment]
I noticed the same thing, both on meet.jit.si and our own deployments across latest stable versions and it happens when at least one participant joined the meeting with Firefox. Meetings with up to 9 participants using Chrome/Edge run smoothly but when one firefox user joins, it ruins the conference.

**Comment by alan-albuquerque** [comment]
@nicoasi I noticed that Firefox is related to the issue too, I opened an issue about Firefox being the trigger to start the freezing, but no luck to move it forward https://github.com/jitsi/jitsi-meet/issues/10974

**Comment by sellth** [comment]
I also face this issue on latest stable. Also seeing lots of `large jump in sequence numbers detected` messages in jvb log. 

The issue affects only single participants, not the whole conference. Sometimes it spontaneously recovers, sometimes after manually changing video focus. Guaranteed discovery after rejoining the conference.

**Comment by davidhalter** [comment]
We have enabled the VP9 codec. Previously we have used the VP8 codec. All our problems are now gone. Firefox still has a few issues, but in Chrome it works for everybody all the time.

I'm 100% sure that this was an issue with Jitsi and not our bandwith, but the new codec solved it for us I guess.
