### ISSUE TITLE
How to integrate in new android studio version or new build.gradle

### ISSUE THREAD

**Issue by VishalBeepBro** [jitsi/jitsi-meet#10412]
How to integrate in new `android studio version` or new `build.gradle`

**Comment by saghul** [comment]
See here to get started: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

**Comment by VishalBeepBro** [comment]
@saghul in documention `allProjects` are being used and In my `build.gradle` there is no code or word that contains `allProjects`

**Comment by saghul** [comment]
Make sure you are looking at the right file, and add it if it's not  there.
