### ISSUE TITLE
react-native could not be run normally on android

### ISSUE THREAD

**Issue by qinyang1980** [jitsi/jitsi-meet#1041]
I try to build react-native android/ios app and try it:
1. npm install (everything is installed ok)
2. react-native run-android (installed the APP on device success)
3. on android device, open the app, there are errors.
   there are errors.

![screenshot_2016-10-19-11-22-08-071_org jitsi jitsi_meet_react](https://cloud.githubusercontent.com/assets/6745689/19504671/b22102fe-95ee-11e6-9b8f-0364f102c6df.png)

Anyone can help me ?

**Comment by lyubomir** [comment]
It's been almost an year since this issue was opened. We and third parties have been building and running Jitsi Meet for Android and/or Jitsi Meet SDK for Android during that time. So I'm closing this issue because there's not enough information for me to debug the reported problem.
