### ISSUE TITLE
[ios] No Audio track when join a call muted

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#10415]
### Description:

It a really critical issue for every iPhone users on deployments where participants start call muted.
We are using RocketChat mobile app version 4.19.0, I guess it's on [Jitsi mobile SDK 3.6.0](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3292).
That Monday we enabled `startAudioMuted: 1` in our **config.js** file and our iPhone users started comply about audio issues - mic shows enabled (unmuted), but in fact there is no audio track and other participant don't hear iPhone users.
Reading [this](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md#206433-2021-10-07) I decided to update Jitsi Meet deployment to **2.0.6433** version (we were on 2.0.6293 before that). Update was successful and without any major issue (only one - Jitsi conferences metrics are broken now).
Now I'm testing iPhone clients and can say, that issue is still here!
One important note - on RocketChat client (SDK 3.6.0) there is a workaround, which is working pretty stable:
1. Unmute mic
2. Mute mic
3. Unmute mic
4. Audio track is appears and other users can hear you

But then I tested recent **Jitsi Meet app version 21.4.2 build 132 on same iPhone** and that workaround not works there - **so there is no way to enable audio track on iPhone if you connected muted**!

### Steps to reproduce:

1. Enable `startAudioMuted: 1` in **config.js** file
2. Start call on web or some other device
3. Join that call on iPhone with Jitsi Meet app or RocketChat mobile app
4. Enable mic (unmute)
5. No audio track from you, nobody can hear you
6. Then mute, unmute on RocketChat - other users can hear you now
7. Jitsi Meet app - no workaround, nobody can hear you!

### Expected behavior:

Other users should hear iPhone user right after that user unmuted himself.

### Actual behavior:

No audio from join-muted iPhone users on their unmute.
We have `startAudioOnly: true,` and `startVideoMuted: 1,` and `startWithVideoMuted: true,` for a long time now and there is no similar issues with camera - it enables right after you first enable it by pressing a cam button. 
But audio is a real trouble now.

If I comment out `startAudioMuted: 1` in **config.js** file all clients start working properly, both and RocketChat and Jitsi Meet join a call with unmuted mic and other users can hear them.

### Server information:

- Jitsi Meet version: 2.0.6433
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: RocketChat 4.19.0 and Jitsi Meet version 21.4.2 build 132 (tested on iPhone 8)
- Operating System: iOS 15

### Additional information:

`startWithAudioMuted: true,` and `startSilent: false` both commented out in **config.js** file

**Comment by saghul** [comment]
This has been fixed in the latest SDK version. 3.6.0 is quite old at this point, and upgrade is necessary in order to get the latest fixes.

**Comment by ankar84** [comment]
> This has been fixed in the latest SDK version

Hey, @saghul 
Is **Jitsi Meet app version 21.4.2 build 132** on latest SDK version?
If yes, then nothing fixed, please read issue information.
Thanks!

**Comment by ankar84** [comment]
Related to https://github.com/jitsi/jitsi-meet/issues/10053

**Comment by ankar84** [comment]
@saghul actually a tested **Jitsi Meet app version 21.4.2 build 132** on meet.jit.si and beta.meet.jit.si with "everyone starts muted" in the moderator settings to reproduce that bug, but no luck, Jitsi Meet works perfect.
So, I think we have some circumstances, that lead to that incorrect behavior.
Please reopen that issue and help me to investigate that circumstances.
I have a test Jitsi deployment with same actual 2.0.6433 version and there that issue with Jitsi Meet app version 21.4.2 build 132 is reproducible too.
I guess it some setting in **config.js**, so please help me to find that.

**Comment by saghul** [comment]
I reopened, but I won't have time to look into this anytime soon, sorry.

**Comment by ankar84** [comment]
> I reopened, but I won't have time to look into this anytime soon, sorry.

Thank you, Saul!
I will try to investigate that issue by myself.

**Comment by ankar84** [comment]
**Jitsi Meet 21.5.0 build 146** works perfect on our server with `startAudioMuted: 1` in **config.js** file.
Audio track exist right after user unmute - all other users hear him.
So, I guess full fix for that issue will be update [Jitsi SDK to version 4.0.0](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#400-2021-12-03) (at least) in Rocket.Chat ReactNative application.
