### ISSUE TITLE
The term "Follow Jitser" is not in main.json so it can not be localized

### ISSUE THREAD

**Issue by ali-alhaidary** [jitsi/jitsi-meet#10410]
### Description:

The term "Follow Jitser" is not in main.json so it can not be localized

**Comment by gpatel-fr** [comment]
That's true and it may be seen as a problem. However this string can be set in interface_config.js so it can mitigate it a bit.

**Comment by ali-alhaidary** [comment]
>

**Comment by ali-alhaidary** [comment]
> That's true and it may be seen as a problem. However this string can be set in interface_config.js so it can mitigate it a bit.

So it will not be put there? we have to edit this file each time?

**Comment by gpatel-fr** [comment]
if by 'each time' you mean 'for every server setup', yes, that's true - I did not say that it was a fix, it's a workaround.

**Comment by ali-alhaidary** [comment]
Thanks, we will do so until it is added...

**Comment by ali-alhaidary** [comment]
> That's true and it may be seen as a problem. However this string can be set in interface_config.js so it can mitigate it a bit.

not found in that file...

**Comment by gpatel-fr** [comment]
maybe your file version is not complete ?

DEFAULT_REMOTE_DISPLAY_NAME: 'Fellow Jitster',

**Comment by ali-alhaidary** [comment]
> maybe your file version is not complete ?
> 
> DEFAULT_REMOTE_DISPLAY_NAME: 'Fellow Jitster',

No, it is complete, but I was looking for 'Follow' not 'Fellow'  ;-)
My bad
