### ISSUE TITLE
Separate volume for screen shared with audio

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#10414]
**Is your feature request related to a problem you are facing?**
Yes! Sometimes the screen share audio is too loud or quiet compared to my friends mic volume, being able to adjust it separately would be great!

**Describe the solution you'd like**
Just another volume bar for stream volume.

**Describe alternatives you've considered**
n/a

**Comment by GrazingScientist** [comment]
I totally second this. Please implement that!

**Comment by saghul** [comment]
Duplicate: https://github.com/jitsi/jitsi-meet/issues/9249#issuecomment-1010876397

**Comment by DillFrescott** [comment]
Lol the other issue was made by me too oops 😂
