### ISSUE TITLE
Website Icon Broken

### ISSUE THREAD

**Issue by nanderer** [jitsi/jitsi-meet#10428]
Hi,

sorry for posting that here but i found no repository for the site,

i dont know whats the problem, im not a web developer but : 

764422
ah wait 
![grafik](https://user-images.githubusercontent.com/45161625/143085296-42eff489-dbe2-4ffb-9953-89ed93697b7e.png)

there it is, damn forced 2FA, 

the icons on the buttons for example are missing, i dont know how but please fix that.

thanks

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

These are not icons but a character seems for some reason you are missing that font.
