### ISSUE TITLE
Video is only shown when participant speaks - Android/Mobile

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [jitsi/jitsi-meet#10431]
### Description:

In the jitis app on adroid the video of participants is only shown when they speak. otherwise the tile shows the default letters of the participants name.

### Steps to reproduce:

1. Start a conference with more than 2 participants on mobile
2. Watch the video only appear when there is also the blue speaker symbol present
3. 

### Expected behavior:

The video shoudl be shown all the time if activated. If this behavious is intentional there should be an option to disable in the app menu.

### Actual behavior:

The video disappears and changes to the defautlt tile when the participant stops speaking and the speaker symbol disappears.

### Server information:

- Jitsi Meet version: 2.0.6433
- Operating System: Docker

### Client information:

- Browser / app version: Android app 21.4.1 build 214010
- Operating System: Android 8

### Additional information:

I've searched the settings as this could be a feature for low bandwidth calls, but i couldn't find a setting to turn it off.

The issue does not exist on web clients in the same call, so it must be an issue within the mobile app itself.

**Comment by F-Node-Karlsruhe** [comment]
It also happend in the web app recently. I assume that it is the same issue as here: https://community.jitsi.org/t/videostream-stopps-and-goes-to-connection-status-inactive/36981

**Comment by saghul** [comment]
Any chance you can try our nightly server components, and the beta app?

**Comment by F-Node-Karlsruhe** [comment]
If the next release is more than a week away i will give it a shot :)

**Comment by psi-4ward** [comment]
> Any chance you can try our nightly server components, and the beta app?

Which components are affected? Jvb and the lib?
Jicofo should not be involved, isn't it?

**Comment by saghul** [comment]
Unlikely, but we release all components in tandem to avoid incompatibilities.

**Comment by psi-4ward** [comment]
Of course, but most time it works quite well 😄
