### ISSUE TITLE
Cant Build Android App

### ISSUE THREAD

**Issue by Elqul** [jitsi/jitsi-meet#1043]
when i run the android app in Android Studio i get this error on my mac 
```
error: error reading /Users/notuser/Documents/jitsi-meet/android/app/build/intermediates/exploded-aar/jitsi-meet-react/react-native-webrtc/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in opening zip file
error: error reading /Users/notuser/Documents/jitsi-meet/android/app/build/intermediates/exploded-aar/jitsi-meet-react/react-native-webrtc/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in opening zip file
```

how to fix this ??

**Comment by damencho** [comment]
Please use the mailinglist for problems and questions before opening issues.

I think I have seen this problem when there is no git lfs installed on the machine. We need to update docs with instructions and requirements, but the mobile part is still in development.
