### ISSUE TITLE
Store the recording on nextcloud

### ISSUE THREAD

**Issue by wincelau** [jitsi/jitsi-meet#10451]
It is possible to start a recording by storing it in dropbox.

Would it be possible to start a recording from nextcloud?

**Comment by ashiqhassan95** [comment]
You can achieve this feature by creating custom shell script to upload file to nextcloud.

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#uploading-files

**Comment by kpeiruza** [comment]
Hi, you can achieve that quite easily with a finalize.sh script. Just use curl:

curl -s -T $FILENAME  -u "$NC_SHARE:$NC_PASSWORD" -H 'X-Requested-With: XMLHttpRequest' -H 'X-Method-Override: PUT' $NC_SERVER/public.php/webdav/$FILENAME

**Comment by ImaCrea** [comment]
Hello there,

I guess the ability to record was asked at a personal level not an instance level.

It's ok to code a script which stores all recordings into a nextcloud folder. It's something else to let each user be able to store their record to a nextcloud folder of their own.

I see two ways of approaching it : one which goes through authentification process and let you properly connect to your nextcloud account (wherever it is) and upload it there once your record is finished. 

Another without auth which would let simply you paste a shared url of a nextcloud folder with proper permissions to be edited. The record would then be uploaded there.

What do you think? I have no clue about what would be easier in term of code. In term of UX, second way might looks simpler as it's less steps but maybe harder to understand for regular user.

**Comment by ImaCrea** [comment]
Nice then it means most of the UX is ready, right? I wonder how difficult it is to make it work for Nextcloud 🤔

**Comment by valerio-bozzolan** [comment]
> Well, it is not completely ready, so any PRs are welcome.

Can I ask where is the relevant already-existing part in the source code? (if any) Thanks :)

**Comment by valerio-bozzolan** [comment]
I honestly was not able to figure it our where is the part that uploads the file to Dropbox. I only see code related to authentication, quota checks, etc. but this is probably a starting point (?):

https://github.com/jitsi/jitsi-meet/tree/master/react/features/dropbox

**Comment by damencho** [comment]
And the rest is the UI and integration with tokens and such in jitsi-meet and passing it to the appdata which goes through jicofo to reach jibri.

**Comment by valerio-bozzolan** [comment]
Can I request an economical quote to develop this feature? Please open again this issue.

direttore@linux dooot it

Thanks
