### ISSUE TITLE
 Unable to load Maven meta-data from https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/maven-metadata.xml.

### ISSUE THREAD

**Issue by hafizworqapp** [jitsi/jitsi-meet#10457]
![jitsicall2](https://user-images.githubusercontent.com/93766254/143522583-8158d16d-ee53-475b-9eb1-90b43e03162b.PNG)

### Description:
![jitsicall](https://user-images.githubusercontent.com/93766254/143522573-b1039d31-c88f-4036-a08f-fabbf4eed945.PNG)

### Steps to reproduce:

1. compile gradle using method below but get error

`android {
    packagingOptions {
        exclude 'META-INF/*.kotlin_module'
    }

    compileSdkVersion 31

    defaultConfig {
        applicationId "com.nibmeetings.android"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode 206
        versionName "2.0.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

    lintOptions {
        checkReleaseBuilds false
    }
}

implementation ('org.jitsi.react:jitsi-meet-sdk:3.+') { transitive = true }

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://github.com/leonardocardoso/mvn-repo/raw/master/maven-deploy' }
        maven { url 'https://jitpack.io' }
        maven {
            // This is necessary for now, will be removed soon
            url "https://github.com/vector-im/jitsi_libre_maven/raw/master/android-sdk-2.9.3"
        }
    }
}`

**Comment by saghul** [comment]
If you are building master then you need to depend on version 4.0, which is what master is set to.
