### ISSUE TITLE
bulk, one poll insertion BEFORE online session with results storage

### ISSUE THREAD

**Issue by edmundlaugasson** [jitsi/jitsi-meet#10454]
**Is your feature request related to a problem you are facing?**
As a lecturer, would like to insert polls before online lecture. Inserting polls during lecture takes too much time and usually even to copy text from text editor takes too much time.

**Describe the solution you'd like**
In front of Jitsi Meet server, there is a gear wheel, where we can configure Settings before connecting. It would be good, if there could be possible import certain plain text file with simple syntax with one or multiple polls at once. Also manually entering via web interface before starting lecture, would be better than during online lecture. There should be also delete button per poll. Editing could be possible via direct web form editing like currently already exist under Settings. Also clean all polls button would be appreciated. Polls could be stored as other settings in web browser profile. It would be good to also manually browse poll storage file. 

**Even better would be, if using certain syntax, there could be just an option to browse manually a file, that contain poll(s).** This could make all poll management even easier. Then no poll management inside browser profile is not needed as user will browse exact file, that contain poll(s) with questions and answers. Then there are no other management buttons needed, than just browse certain file with appropriate syntax, that contain poll(s) and these will be available during online session. Then there could be decided, which poll and when goes online for participants.

Certainly, also poll(s) results export would be appreciated. Even simpler - allow to store results into separate plain text file, that can be also defined in Settings, like poll file itself. There could be just an option, whether to save poll results into file or not. If yes, then browsing a location and name of file would be required.

**Describe alternatives you've considered**
Well, there are no alternatives in case of Jitsi Meet. Either do or not to do polls during online lecture. Certainly there are many other environments offering poll feature, one of them could be certainly used.

**Comment by gerardw** [comment]
This would be great indeed!
