### ISSUE TITLE
Overlay last chat message on the grid view

### ISSUE THREAD

**Issue by hamoid** [jitsi/jitsi-meet#10467]
**Is your feature request related to a problem you are facing?**

Two issues:
1. With about 30 participants and enough chat interaction, the chat quickly scrolls out of view.
2. Disconnect between faces in the grid view and chat messages (one needs to mentally match names on video with names on chat).

**Describe the solution you'd like**
What I would like is being able to set a text to temporarily overlay my rectangle in the grid view. The simplest approach would be to overlay the last chat message, with an option to enable and disable this feature.

This feature would be great to answer questions by the presenter, with answers appearing over each persons video feed. We could also use it to express feelings (sharing emojis), share links to our home page or social media, etc. I think it has the potential to make the event much more participative (less "one-to-many" and more "many-to-many").

I believe having texts over the video feeds might do a better job at letting people know each other.

The feature I'm requested here has much in common with https://github.com/jitsi/jitsi-meet/issues/7239 but I believe it is simpler to implement (less development and design).

One additional feature: if the text shared is a link to an image, that image is displayed on the grid.

The ultimate idea is to make the grid a bit more of a collaborative playground. A space where we can write text, or display media, etc. to have a shared interactive experience.

**Comment by saghul** [comment]
We have no plans to implement this, sorry.
