### ISSUE TITLE
Wrong "Video has been turned off to save bandwidth" message for FF users after a participant has shut his video off

### ISSUE THREAD

**Issue by soisik** [jitsi/jitsi-meet#10468]
### Description:

On a local install and in meet.jit.si, Firefox users almost always gets the message "Video for XXX has been turned off to save bandwidth" after the other participant XXX turns his video or screen sharing off, and the other participant connection appears inactive with a white and blue icon, while audio (or video if reactivated) are still working for both of them.
Doesn't seems to occurs in another browser (just Firefox on desktop or mobile)

### Steps to reproduce:

1. Open new room
2. Participant A joins using FF
3. Participant B joins and share his screen (or video)
4. Participant B turns screen sharing or his video off
5. Participant A sees a message saying "Video for B has been turned off to save bandwidth" and sees participant B connection status has inactive, with a white/blue circle icon (ghost user icon?)
6. Stays that way until participant B share his screen again.

### Expected behavior:

No message about bandwidth problem, or no inactive status/icon in connection of other participant.

### Actual behavior:

A message about bandwidth problems appears and connection seems lost with other participant, while band width is fine and audio/video communication still working.

### Server information:

- Jitsi Meet version: meet.jit.si and 2.0.6433
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: FF 94
- Operating System: Ubuntu or windows or android

### Additional information

It might help to locate the issue knowing that it does not occur when bandwidth evaluation is disabled in videobridge (org.jitsi.videobridge.TRUST_BWE=false).

**Comment by hhassey** [comment]
I have the same issue with FF 117.0.1 (64-bit)

**Comment by xabicolas** [comment]
Same issue here with FF 117.0.1 (64-bit)

**Comment by saghul** [comment]
Please see https://github.com/jitsi/jitsi-meet/issues/13804
