### ISSUE TITLE
Moderator should remaining at top in thumbnail 

### ISSUE THREAD

**Issue by gigabyteservice** [jitsi/jitsi-meet#10479]
**During the recording or the live streaming If a teacher is a moderator and there are a large number of participants then sometimes moderators’ video goes at the bottom in the thumbnail sequence in the filmstrips, So during that session if someone is speaking then it will appear on the main large screen & during that time if recording going on and if we see that video later then it’s hard to find who was the moderator during that conference** 

So that moderators’ thumbnail should remain at the top in the filmstrip 

** Moderators’ video should remain at top in the filmstrip so that when someone is speaking still moderator Should show up on the top of the film’s trip during the live streaming and recording**

**Comment by damencho** [comment]
What should happen when all participants are moderators? 

Currently, information for most recent speakers is reported from the bridge which is taken into account when ordering.

**Comment by ashiqhassan95** [comment]
Ask the moderator to turn on screen share 😃,

**Comment by psi-4ward** [comment]
We've patched the `react/features/filmstrip/functions.any.js:updateRemoteParticipants()`

```js
....
reorderedParticipants = reorderedParticipants
        .map(id => {
            const participant = remote.get(id);
            let name = '';
            let role = PARTICIPANT_ROLE.PARTICIPANT;

            if (participant && participant.name) {
                name = participant.name;
            }
            if (participant && participant.role) {
                role = participant.role;
            }

            return [
                id,
                name,
                role === PARTICIPANT_ROLE.MODERATOR
            ];
        })
        .sort(([ , aName, aIsMod ], [ , bName, bIsMod ]) => {
            if (aIsMod && !bIsMod) {
                return -1;
            } else if (!aIsMod && bIsMod) {
                return 1;
            } else if (aName && bName) {
                return aName.localeCompare(bName);
            }
            return 0;

        })
        .map(([ id ]) => id);
    store.dispatch(setRemoteParticipants(reorderedParticipants));
```

**Comment by gpatel-fr** [comment]
@gigabyteservice 
Maybe this option could help ?

```
    testing: {
        // Enables/disables thumbnail reordering in the filmstrip. It is enabled by default unless explicitly
        // disabled by the below option.
        // enableThumbnailReordering: true,

```
