### ISSUE TITLE
Race condition: Authentication of two users at the same time in the same room

### ISSUE THREAD

**Issue by shenziro** [jitsi/jitsi-meet#10471]
### Description:

When two users enter a room at the same time and log in at the same time, sometimes they cannot see each other and sometimes they cannot hear each other. A third user sees and hears both others.

### Steps to reproduce:

0. (On a jitsi Instance where login is required to open a room)
1. Open new conference room
2. Authenticate at the same time as another user

### Expected behavior:

The two users should be able to see and hear each other.

### Actual behavior:

The two users sometimes do not see or hear each other.

### Server information:

- Jitsi Meet version: docker-jitsi-meet-stable-6173
- Operating System: Ubuntu 18.04 LTS

### Client information:

- Browser / app version: Google Chrome Version 96.0.4664.45  / recent Firefox version
- Operating System: Windows 10 / Fedora 35

**Comment by gpatel-fr** [comment]
what happens if the users having this condition turn off and on again their camera ?
Can you try to disable p2p to see if it has an impact ?
