### ISSUE TITLE
sharing invidious videos through its instances

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet#10470]
I'd like to share videos in jitsi through invidious instances and not direct YT videos.
https://github.com/iv-org/invidious
I have tried it, but jitsi complains, telling me to correct the URL
e.g. 
https://yewtu.be/watch?v=3Iwiwq7eofE
It does not open because it uses an invidious instance.
:(

**Comment by saghul** [comment]
We don't support that, sorry. YT provides an API we interact with, which this system would need to provide.

**Comment by saghul** [comment]
Nothing actionable on our end until invidious supports the YT iframe API.
