### ISSUE TITLE
Open shared document button stopped working in jitsi-meet_6490

### ISSUE THREAD

**Issue by qwertiko** [jitsi/jitsi-meet#10486]
### Description:

We recently noticed that the "Open shared document" button stopped working in our development environment and decided to investigate a bit.

I was able to pin it down to this version: https://github.com/jitsi/jitsi-meet/releases/tag/jitsi-meet_6490 / this commit: https://github.com/jitsi/jitsi-meet/commit/9df59b4a6f22953d0b10dfa0fb58709dba26e33e

The strange thing is that all the other menu buttons are working fine.

### Steps to reproduce:

1. Setup Jitsi (tag jitsi-meet_6490 or later) and configure Etherpad integration
2. Start a new meeting
3. Open "More actions" menu and click on "Open shared document"

### Expected behavior:

New Etherpad document loads and shows up.

### Actual behavior:

Nothing happens.

### Server information:

- Jitsi Meet version: tag jitsi-meet_6490 or later
- Operating System: Ubuntu Server 20.04.3 LTS

### Additional information:

To debug this I first setup a new VM and installed the stable version of Jitsi: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

Then I used this tutorial to run Jitsi from source and search for the version/commit that broke the feature: https://community.jitsi.org/t/how-to-how-to-build-jitsi-meet-from-source-a-developers-guide/75422

It seems like we are not the only ones experiencing this problem: https://community.jitsi.org/t/nothing-happens-when-open-shared-document-is-clicked-etherpad-lite-integration-is-not-working/107388

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by damencho** [comment]
The etherpad implementation needs to be refactored as we show it in some funny way which is only used for it and we regularly break it. In my opinion, we need to check can we implement it like the shared video where there is a thumbnail for it and you can focus on it or focus on something else ...
