### ISSUE TITLE
Iframe url exceeds max parameter size

### ISSUE THREAD

**Issue by LouisKnuckles** [jitsi/jitsi-meet#10483]
### Description:

When HostPageLocalStorage is true jitsi settings are stored locally in jitsiLocalStorage.  The jitsiLocalStorage is passed to the iframe URL to persist settings. The `features/recent-list` however continues to grow in 
size on each refresh etc. As jitsiLocalStorage is passed to the iframe URL, and is never reset, eventually the iframe fails to load as the max parameter size is exceeded. The only way users can fix the issue is by manually clearing the local storage. 

Relavent files 
jitsi-meet/modules/API/external/external_api.js 
jitsi-meet/react/features/base/jitsi-local-storage/setup.web.js 

* First request 
features/recent-list 
"conference\":\"https://8x8.vc/vpaas- ... appData.localStorageContent=null\",\"date\":1638251474303,\"duration\":0}"

* Second request
features/recent-list 
"conference\":\"https://8x8.vc/vpaas- ... appData.localStorageContent=%22%7B%5C%22features%2Fvideo-quality-persistent-storage% ..."

appData.localStorageContent continues to grow with each refresh. 

### Steps to reproduce:

1. Open browser in incognito mode (I used Chrome)
2. Start a Jitsi iframe using  "new JitsiMeetExternalAPI(jitsiDomain, jitsiOptions)"
3. Keep refreshing the page (a good 50ish+ times)

### Expected behaviour:

Iframe always loads successfully. 

### Actual behaviour:

Iframe fails to load with parameters size exceeded 

See features/recent-list size (continues to grow)
![Screen Shot 2021-11-30 at 7 43 18 pm](https://user-images.githubusercontent.com/12335754/144014040-47ff9b4b-e8f6-45b4-9849-500910d940de.png)

### Server information:

Using JAAS 

### Client information:

- Browser / app version: Chrome / Version 96.0.4664.55 (Official Build) (arm64)
- Operating System: Mac

**Comment by saghul** [comment]
Good catch, thanks for the report!

I'd say we should stop storing items on the recent list when running in the iframe, since it's not going to be visible anyway.

**Comment by hristoterezov** [comment]
@saghul I think we have a limit on the number of recent list entries, isn't it? Also it is possible to show the welcome page in an iframe so I don't think that just disabling recent list entries in an iframe is the best solution. I was looking into something similar some time ago and I have a vague recollection that we store the whole URL with the params. If this is the root cause, maybe we can strip the parameters from the URLs we store? WDYT?

**Comment by hristoterezov** [comment]
I guess the perfect solution would be if we implement all of them :) 

I think storing the parameters is actually a bug. At least the one for external local storage should be removed for sure! I guess this will address many of the issues!

Also I saw that `config. doNotStoreRoom` is stopping the storing of the rooms. @LouisKnuckles I think you can set this to true to mitigate the immediate issue. 

Also I see `interfaceConfig.RECENT_LIST_ENABLED`. I'm not sure if this will stop the storing tho... If not we should probably work to have a single option that disables everything.

**Comment by LouisKnuckles** [comment]
@hristoterezov recent-list size does store the whole parameter which is the problem. 

Also, I don't think max size will help as it is only a single conference. It is not the number of conferences in recent-list that is growing. It's the parameter size passed to the Iframe.

The parameter includes appData.localStorageContent which gets the previous settings saved into it. 
The next refresh then saves the last two settings config into it. And so on. 

Untill appData.localStorageContent is megabytes of data.

However, we can not remove the parameter from the Iframe as that is how jitsi is getting its settings.
