### ISSUE TITLE
Can't build SDK with react-native-reanimated library

### ISSUE THREAD

**Issue by Benefit94** [jitsi/jitsi-meet#10492]
### Description:

Our react native developer added react-native-reanimated:1.13.3 library and some modifications in react part.

Builded own SDK artifacts by command ./android/scripts/release-sdk.sh /tmp/repo

all SDK artifacts including react-native-reanimated was builded successful.

Added SDK artifacts like a local Maven 

![111](https://user-images.githubusercontent.com/18071613/144197527-19bb7596-1540-4833-881b-8ab6429280d3.png)

allprojects {
repositories {
google()
mavenCentral()
maven { url “$rootDir/jitsi/repo” }
}
}

dependencies {
…
implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }
...
}

### Steps to reproduce:

1. Build SDK with react-native-reanimated library
2. Put artifacts like a local maven in android project
3. Build android project

### Expected behavior:

It should build successful

### Actual behavior:

When try to build project, getting this error

What went wrong:
Could not determine the dependencies of task ‘:app:compileDevDebugKotlin’.
Could not resolve all files for configuration ‘:app:devDebugRuntimeClasspath’.
Could not resolve com.swmansion.reanimated:react-native-reanimated:1.13.3-jitsi-9190797.
Required by:
project :app > org.jitsi.react:jitsi-meet-sdk:4.0.0
Could not resolve com.swmansion.reanimated:react-native-reanimated:1.13.3-jitsi-9190797.
Could not parse POM http://oss.jfrog.org/artifactory/oss-snapshot-local/com/swmansion/reanimated/react-native-reanimated/1.13.3-jitsi-9190797/react-native-reanimated-1.13.3-jitsi-9190797.pom
The element type “hr” must be terminated by the matching end-tag “”.

**Comment by saghul** [comment]
What commit are you building? We already depend on reanimated and have fixed that bug in latest master.

**Comment by Khodjaa** [comment]
fix(linguistics) Use 'email' instead of 'e-mail' - sha : 14a422ba8370c20b978bfe9584af26f038f55286,
This one was last commit that we downloaded

**Comment by saghul** [comment]
You need to be at least on this commit: https://github.com/jitsi/jitsi-meet/commit/0a65ec1dfabc021728e4c3549b454437162ef2d9
