### ISSUE TITLE
Invite dialog shows "conference is being created"

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#105]
Hi,

 I'm playing around with jitsi meet.
 Therefor I have installed a VM mit Ubuntu server 14.04 and I followed the
 instructions from the quick-install.
  https://github.com/turint/jitsi-meet/blob/master/doc/quick-install.md

 I can access the jitsi meet but if I click on invite others I receive the
 following:
 Your conference is currently being created...

 Emil ask me to open a ticket for that.

 Best regards
 Timmi

Discussion thread:  http://lists.jitsi.org/pipermail/users/2014-August/007753.html

**Comment by Nhorning** [comment]
Our project is currently getting this issue on both on our test deployment, and on meet.jit.si in chrome, both linux and windows.  The person who gets "Your conference is currently being created..."  see's themselves in the room but cannot see anyone else. The issue appears to be intermittent.

**Comment by maserons** [comment]
I got this error when I change listening port in nginx. What I should change to serve jitsi-meet on different port than 443?

**Comment by bgrozev** [comment]
The port in the 'bosh' variable in config.js.

**Comment by maserons** [comment]
Thanks, I added the port to bosh variable and now it connects successfully.

**Comment by matthiss** [comment]
Hi guys,
please excuse my question. I got the same problem with "Your conference is currently being created..." but cant find the port to change. 
I configured jitsi on Ubuntu server 15.04 with my dynamic dns. During installation I got an error saying "couldnt start hostname.service" or something similar. Does it relate?
Where can I change the port and will it fix it?
I just navigated to /etc/jitsi/meet/my.domain.com-config.js

Thank you!

**Comment by sheaw** [comment]
Yup, same for me. Just completed a clean install of Jitsi Meet on fresh Ubuntu 12.04.2 LTS.

When I attempt to invite someone, it says:

"Your conference is currently being created..."

Otherwise, if I connect directly to the chatroom, it says "unsupported browser" (when in fact the browser is opera).

I sense it is something with https VS http ??  

Config.js is as follows:

var config = {
    hosts: {
        domain: 'meet.example.com',
        //anonymousdomain: 'guest.example.com',
        muc: 'conference.meet.example.com', // FIXME: use XEP-0030
        bridge: 'jitsi-videobridge.meet.vocaone.com', // FIXME: use XEP-0030
        //jirecon: 'jirecon.jitsi-meet.example.com',
        //call_control: 'callcontrol.jitsi-meet.example.com',
        //focus: 'focus.jitsi-meet.example.com' - defaults to 'focus.jitsi-meet.example.com'
    },
//  getroomnode: function (path) { return 'someprefixpossiblybasedonpath'; },
//  useStunTurn: true, // use XEP-0215 to fetch STUN and TURN server
//  useIPv6: true, // ipv6 support. use at your own risk
    useNicks: false,
    bosh: '//meet.example.com/http-bind', // FIXME: use xep-0156 for that
    clientNode: 'https://example.com/meet', // The name of client node advertised in XEP-0115 'c' stanza

**Comment by protosfucion** [comment]
Same here, but no errors in nginx... can anyone guide us with this issue? i tried to replicate changing the capital letter and welcome page, nothing change for me.
