### ISSUE TITLE
Audio not working for iphone user if the other user joins with audio muted

### ISSUE THREAD

**Issue by soisik** [jitsi/jitsi-meet#10503]
### Description:

When a participant joins with audio muted, and then demute himself once he's in the room, if the other participant in the room is using an iphone and a browser (safari or chrome), he cannot hear him. If the participant has join with audio demuted, he can be heard fine by the iphone user.

This does not happen if the iphone user is using jitsi electron app. 

Could be reproduced consistently on meet.jit.si in a one to one meeting (did not test with more than 2 participants).

#### Case 1

1. User A on iphone and chrome or safari enters a room in meet.jit.si
2. User B joins the room with **audio muted**
3. User B demute his audio
4. User A cannot hear user B

#### Case 2

1. User A on iphone and chrome or safari enters a room in meet.jit.si
2. User B joins the room with **active audio**
3. User A can hear user B

### Expected behavior:

User B should hear user A after he has demuted his audio.

### Actual behavior:
User B do not hear user A after he has demuted his audio.

### Server information:

meet.jit.si and on premise install using latest release on ubuntu 20.04

### Client information:

- Browser: Safari or Chrome
- Operating System: Iphone

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by damencho** [comment]
Can you reproduce the same on beta.meet.jit.si?

**Comment by soisik** [comment]
Yes, we could reproduce it on beta.meet.jit.si.

**Comment by saghul** [comment]
This has been fixed recently, it's part of the latest stable release.
