### ISSUE TITLE
Set Display Name Visibility as a Configurable Option

### ISSUE THREAD

**Issue by Freddie-m** [jitsi/jitsi-meet#10502]
**Is your feature request related to a problem you are facing?**
Yes. Recent versions of Jitsi now statically display user names on thumbnails permanently (used to be only visible on hover). While this is useful in many instances, there are several instances where it is not desired. It is especially concerning that these display names are captured as part of the recording in Jibri. 

**Describe the solution you'd like**
A configurable option to show display names on thumbnails (or not) would be appreciated. At the very least, it would be desirable to be able to set a flag to prevent this property from being captured in recordings.

**Describe alternatives you've considered**
Thought of possible CSS hacks, but concerned those could potentially affect the video elements.

**Comment by saghul** [comment]
> It is especially concerning that these display names are captured as part of the recording in Jibri.

Can you elaborate on what you find concerning?

**Comment by Freddie-m** [comment]
Well, for one, we think it takes away from the aesthetics for us and in our use case, it's information that we don't want (or need) captured in a recording for privacy reasons. We typically share our recordings with others outside the firm, with focus on the subject matter, rather than the attendants.

**Comment by saghul** [comment]
Got it.

**Comment by Freddie-m** [comment]
This is now resolved. Thanks!

https://github.com/jitsi/jitsi-meet/blob/7f26e7f9275bbf4871184dec858ac048d484759f/config.js#L494
