### ISSUE TITLE
PRIVACY: Remove amplitude from the official instance

### ISSUE THREAD

**Issue by Kreyren** [jitsi/jitsi-meet#10501]
The official instance https://meet.jit.si is making calls to amplitude.com

```
POST / undefined
Host: api.amplitude.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 16071
Origin: https://meet.jit.si
DNT: 1
Connection: keep-alive
Referer: https://meet.jit.si/
```

Which violate the user privacy by sharing unknown amount of data with:

> (amplitude's) Service providers. For example, we may use third party providers of business contact information. The Personal Data provided by these Service providers to us about you may include your business mailing addresses, job titles, business email addresses and business phone numbers, and LinkedIn URLs for purposes of delivering relevant email content, advertisements and events.  -- https://amplitude.com/privacy

> (amplitude's) Advertising partners. We receive information about you from some of our service providers who assist us with marketing or promotional services, related to how you interact with our Website, event promotions, advertisements or communications. -- https://amplitude.com/privacy

To collect:

Cookies:
> As you navigate through and interact with our Website or Product, we may use cookies, which are small files placed on the hard drive of your computer or mobile device, and web beacons, which are small electronic files located on pages of the Website, to collect certain information about your equipment, browsing actions, and patterns.  You can learn more about cookies and how we use them here.  -- https://amplitude.com/privacy

Third party cookies to track the user across multiple websites:
> We also use cookies to access information when you sign in, store your preferences, to keep you logged in, and to store a limited amount of behavioral data.  -- https://amplitude.com/privacy

Engaging in browser fingerprinting:
> The data automatically collected from cookies and web beacons may include information from your Web browser (such as browser type and browser language) and details of your visits to our Website, including traffic data, location data and logs, page views, length of visit and website navigation paths as well as information about your computer and internet connection, including your IP address and how you interact with our Product. We collect this data in order to help us improve our Website, the Product and the user experience with our Website and Product. You can learn more about cookies and how we use them here.  -- https://amplitude.com/privacy

Among other various processing of personal data further clarified in `3.2 THE WAY AMPLITUDE USES YOUR PERSONAL DATA`

While disregarding `Do Not Track`

> Amplitude currently does not support Do Not Track signals set by your browser because there is not an industry or legal standard for these signals. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. -- https://amplitude.com/privacy

---

For those reasons i believe that it's beyond a reasonable doubt to deduce that usage of amplitude most likely exposes the end-users to be logged in a global surveillance program such as:
- 702 Surveillance granted through FISA Amendments Act of 2008 for US citizens[https://www.youtube.com/watch?v=XEVlyP4_11M&t=1640]
- [PRISM](https://en.wikipedia.org/wiki/PRISM_(surveillance_program)) for US citizens [https://www.youtube.com/watch?v=XEVlyP4_11M&t=1740]
- [Upstream](https://en.wikipedia.org/wiki/Upstream_collection) for both US and EU citizens allegedly [https://www.youtube.com/watch?v=XEVlyP4_11M&t=1761]
- Among other methods https://www.dw.com/en/danish-secret-service-helped-us-spy-on-germanys-angela-merkel-report/a-57721901

---

If 8x8 and jitsi developers are serious about privacy then this tracking should be removed immediately.

---

Possibly relevant to https://github.com/jitsi/jitsi-meet/issues/8627

**Comment by saghul** [comment]
There seems to be a misunderstanding here. We care *deeply* about our user's privacy. Our use of analytics is limited to better understanding how the software is used and helping us debug issues.

From Amplitude's privacy policy:

~~~
2. WHAT THIS PRIVACY NOTICE COVERS

This Privacy Notice covers how we treat Personal Data that we gather when you access or use our Product. Specifically, Amplitude is the controller of your Personal Data as described in this Privacy Notice, when it collects personal information from: (i) Visitors to Amplitude’s publicly available Website; (ii) Customers when our Customers register to use the Product through the Website or access their account through Amplitude’s account portal at: https://analytics.amplitude.com/login; and (iii) when we receive personal information from you related to our marketing activities.  

For clarity, this Privacy Notice does not apply when Amplitude processes Personal Data in the role of a processor on behalf of its Customers, including with respect to the processing of our Customer End User Data (as defined below). In addition, this Privacy Notice does not apply to the mobile applications, websites or services offered by our Customers or other third-parties.  

Throughout this Privacy Notice, “Personal Data” means any information that identifies or relates to a particular individual and also includes information referred to as “personally identifiable information” or “personal information” under applicable data privacy laws, rules or regulations.  
~~~

The policy excerpts you quoted apply to visitors of amplitude.com, **not** to the data we send to Amplitude, which you can check in this repository, in case you want to know what it is.

**Comment by Kreyren** [comment]
> This Privacy Notice covers how we treat Personal Data that we gather when you access or use our Product. 

That doesn't seem to me like what you say it means.. How can you even ensure that they don't collect more data? it's not open-source..

**Comment by saghul** [comment]
You seem to be determined in cutting parts to try to fit your original narrative. I don't think it can be put clearer than the second paragraph:

> For clarity, this Privacy Notice does not apply when Amplitude processes Personal Data in the role of a processor on behalf of its Customers, including with respect to the processing of our Customer End User Data (as defined below). In addition, this Privacy Notice does not apply to the mobile applications, websites or services offered by our Customers or other third-parties.

We are Amplitude's customer here and the data they have on our users is processed on our behalf. How else are you supposed to interpret the above?

In addition, the client is open source: https://github.com/amplitude/Amplitude-JavaScript
