### ISSUE TITLE
Virtual Background does not work when sharing screen - And doesn't work with Safari

### ISSUE THREAD

**Issue by nhandt-nals** [jitsi/jitsi-meet#10512]
**Is your feature request related to a problem you are facing?**
Yes. Im in a out-source company and my client need apply virtual background when share screen and work with safari as well.

**Describe the solution you'd like**
Steps share screen:
- Open camera with virtual background.
- Open share screen (it will turn off camera)
- Open camera again.
- Apply presenter mode with virtual background which you choose in step 1.

Step camera safari:
- Cannot open virtual background when using safari.

**Describe alternatives you've considered**
- I think about use another library virtual background open source what work well with safari but not go well (T.T)
- Cannot think any idea for share screen 

Please help. Any idea will be welcome. Anyone face this problem before ? How can you solved it ?

**Comment by saghul** [comment]
Safari does not implement CSS blue filters so we cannot use virtual backgrounds there.

Using a virtual background while screen sharing is work in progress, no ETA on that.

**Comment by nhandt-nals** [comment]
> Safari does not implement CSS blue filters so we cannot use virtual backgrounds there.
> 
> Using a virtual background while screen sharing is work in progress, no ETA on that.

Thank you for your feedback.

But if i really need to use virtual background when share screen or use it on safari. Any **keyword** or **guides** you can suggest me to research. 

Or you can share any idea for **Using a virtual background while screen sharing** when you are working on ? it will be very helpful.

Thank you !

**Comment by saghul** [comment]
It's not possible to do it in Safari.

**Comment by nhandt-nals** [comment]
@saghul Thank you !
