### ISSUE TITLE
Android SDK 3.10.2 Config toolbarButtons No effect

### ISSUE THREAD

**Issue by iceltt001** [jitsi/jitsi-meet#10515]
Android Studio 4.1.1
Virtual Devices API 30
JitsiMeetConferenceOptions.Builder.setConfigOverride("toolbarButtons", StringArray) No effect
<img width="442" alt="截圖 2021-12-03 下午7 49 51" src="https://user-images.githubusercontent.com/95479091/144598033-49d28f47-9294-474c-ba3d-bffd5a74ca04.png">
![device-2021-12-03-195059](https://user-images.githubusercontent.com/95479091/144598046-cb60348d-22e2-44f8-9d1c-36f89c90d514.png)

**Comment by saghul** [comment]
That setting has no effect on the mobile app. You need to use feature flags: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js
