### ISSUE TITLE
Room name with special characters breaks the breakout room

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#10525]
### Description:

Room name with special characters breaks the breakout room

### Steps to reproduce:

Open https://meet.jit.si/salas_de_reunião_test1234

### Expected behavior:

Breakout room should work

### Actual behavior:

Breakout room do not work with special characters
But without special characters it works
https://meet.jit.si/salas_de_reuniao_test1234

### Server information:

- Jitsi Meet version: meet.jit.si

### Client information:

- Chrome 96, Firefox 94, Safari 15:
- macOS 12.0.1

**Comment by saghul** [comment]
Do normal meetings work alright?

**Comment by jluisfa** [comment]
Yes. Meetings operate normally.

**Comment by saghul** [comment]
Thanks for the report!

**Comment by damencho** [comment]
Yeah, the room name there comes from here: https://github.com/jitsi/jitsi-meet/blob/7396db71fd65056539e4df318fc24c923a97f5e0/resources/prosody-plugins/mod_jitsi_session.lua#L21
And is being decoded here: https://github.com/jitsi/jitsi-meet/blob/7396db71fd65056539e4df318fc24c923a97f5e0/resources/prosody-plugins/mod_jitsi_session.lua#L14
But we needed it not decoded when searching for the room ... the room name must be `t%c3%a4st` this is how this room is created in prosody. `t%c3%a4st@conference.jitsi.example.org`

Not sure how to handle it ... maybe we need to encode the room name and the tenant when storing those in the session variables, wdyt @saghul?

**Comment by csett86** [comment]
Thanks a lot for digging into this, I have tested the proposal @damencho, that works fine, submitted as #10529 if you want to go that route.
