### ISSUE TITLE
Failed to load config from https://meet.jit.si/config.js?room=test123

### ISSUE THREAD

**Issue by 06065044** [jitsi/jitsi-meet#10520]
URL serverURL;
try {
serverURL = new URL("https://meet.jit.si");
} catch (MalformedURLException e) {
e.printStackTrace();
throw new RuntimeException("Invalid server URL!");
}
JitsiMeetConferenceOptions defaultOptions
= new JitsiMeetConferenceOptions.Builder()
.setServerURL(serverURL)
.setWelcomePageEnabled(true)
.build();
JitsiMeet.setDefaultConferenceOptions(defaultOptions);

    JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
            .setServerURL(serverURL)
            .setRoom("test123")
            .setAudioMuted(false)
            .setVideoMuted(false)
            .setAudioOnly(false)
            .setWelcomePageEnabled(false)
            .build();
    // Launch the new activity with the given options. The launch() method takes care
    // of creating the required Intent and passing the options.
    JitsiMeetActivity.launch(this, options);

**Comment by saghul** [comment]
Are you trying your own server or meet.nit.si, as the example shows?

**Comment by 06065044** [comment]
yes. same error

**Comment by saghul** [comment]
Any chance you have a firewall of some sort? I cannot reproduce the problem here.

**Comment by lhqmcy** [comment]
when i use the sdk demo,i get the same error!
