### ISSUE TITLE
Jitsi Meet Web 2.0.6433 - Screenshare not working

### ISSUE THREAD

**Issue by dpanic** [jitsi/jitsi-meet#10534]
### Description:

Hello,

Jitsi Meet >=2.0.6433 doesn’t show Screen Share button.

I am using Chrome Version 96.0.4664.45 (Official Build) (64-bit)

Sreen sharing is by WebRtc

Older versions worked without problems. 

I am using Jitsi with JWT tokens.

### Expected behavior:
Screen share button visible with possibility to share

### Actual behavior:
Hidden screen share button

### Server information:
- Jitsi Meet version: 
ii  jitsi-meet                         2.0.5963-1
ii  jitsi-meet-prosody                 1.0.5056-1
ii  jitsi-meet-tokens                  1.0.5415-1
rc  jitsi-meet-turnserver              1.0.5415-1
ii  jitsi-meet-web                     1.0.5056-1
ii  jitsi-meet-web-config              1.0.5056-1
ii  jitsi-videobridge2                 2.1-508-gb24f756c-1

- Operating System: Linux Ubuntu 20.04

### Client information:

- Browser / app version: Chrome /  96.0.4664.45 (Official Build) (64-bit)
- Operating System: Linux Ubuntu 20.04.04

**Comment by saghul** [comment]
Can you please share your browser console logs?

**Comment by dpanic** [comment]
I have identified issue.

It is Chrome related.
If you open http:// than button is hidden, on https:// it is visible.

**Comment by saghul** [comment]
Phew. WebRTC does not work on non-HTTPS origins, that has been the case for years. Nothing will really work, not even audio / video.
