### ISSUE TITLE
jitsi-meet config.js anonymousdomain breaks login

### ISSUE THREAD

**Issue by lorsulic** [jitsi/jitsi-meet#1053]
### My System:

CentOS Linux release 7.2.1511 (Core) 
Prosody Version 0.9.10 from the epel repo
Videobridge Version 829
Jicofo Version 299
Jitsi-Meet Version 1390
### config files:

jitsi.example-domain.com.cfg.lua: http://pastebin.com/v81zt78L
jitsi-meet config.js: http://pastebin.com/yuBiNktR
sip-communicator.properties: `org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
org.jitsi.jicofo.auth.URL=XMPP:jitsi.{{ devdomain.main }}`
### jicofo started with:

`ExecStart=/PATH/TO/jicofo/dist/linux/{{ jitsi_jicofo_dist_dir }}/jicofo.sh --host=127.0.0.1 --domain=jitsi.{{ devdomain.main }} --secret={{ jitsi.focus_secret }} --user_domain=auth.jitsi.{{ devdomain.main }} --user_name=focus --user_password={{ jitsi.focus_password }}`
### videobridge started with:

`ExecStart=/PATH/TO/{{ jitsi_videobridge_dir }}/jvb.sh --host=localhost --domain=jitsi.{{ devdomain.main }} --port=5347 --secret={{ jitsi.jvb_secret }}`

I can't found any errors in the logs. Google Chrome console is also not showing any errors. Seems to me that everthing is working correctly so far.
Currently I am able to create a conference room, I will be asked for authenticating with my ldap credentials, if succeful I enter the room and have all the presenter possibilities. I can invite other people, the url is shown. When using this url, the next person who is comming in, needs also to enter its ldap credentials, after a succesful login of the next person, the new person also is also a presenter (can kick me out etc.) Chat is working, the cam is working.
### Now the issue:

Right after uncommenting, so putting in the line `anonymousdomain: 'guest.jitsi.{{ devdomain.main }}',` into the jitsi-meet config.js and restarting jicofo, videobridge, prosody and nginx, right after that the complete login is not possible anymore. 
When I visit jitsi.{{ devdomain.main }}, I am able to create a conference room, but looks like I do not have the full permissions. If i want to invite someone, the url shown is undefined, if I try to send a message, i get an "error: your message was not sent."
every few seconds, jicofo log is showing:
`org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().416 Focus request for room: perfectorangesaskhard@conference.jitsi.{{ devdomain.main }}`

Google Chrome console is showing: `conference.js:310 CONFERENCE FAILED: conference.authenticationRequired (){n.allocateConferenceFocus(t)}`
`Logger.js:89 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: error: Cannot read property 'getRoomLocker' of undefined(…)`
`Logger.js:89 [modules/xmpp/strophe.util.js] <Object.Strophe.log>:  Strophe: error: Cannot read property 'getRoomLocker' of undefined
TypeError: Cannot read property 'getRoomLocker' of undefined`

Somehow this one line is breaking the login process.

**Comment by paweldomas** [comment]
Thanks for the report ! We are aware of this issue and are working on fixing it. Sorry for inconvenience. The error printed in Chrome console is the reason of this failure.

**Comment by damencho** [comment]
I think this one is fixed in latest builds. Will confirm this with @paweldomas and will close the issue.

**Comment by lorsulic** [comment]
@damencho oh this would be awesome, I will update the components and look if it works

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/pull/1167
