### ISSUE TITLE
Breakout rooms - numbering in breakout room name inconsistent

### ISSUE THREAD

**Issue by thoemie** [jitsi/jitsi-meet#10533]
First of all, thanks to all people involved in making the breakout rooms possible!

### Description:

A breakout-room has the breakout-room number in its name. When all breakout-rooms are deleted, and a new one is created, it is not named  ".... #1", but instead the numbering continues from the previous breakout-rooms, e.g. it is called "Breakout-room #7".

### Steps to reproduce:

1. Start meeting as a moderator
2. Create a breakout-room
3. Observe the name: "Breakout-room # 1"
3. Delete the breakout-room
4. Create a breakout-room 
5. Observe the name: "Breakout-room # 2"

### Expected behavior:

I would expect that the breakout-rooms be consistently numbered in the name, according to the number of current breakout-rooms. Or that the name of the breakout-room can be set by the user / changed interactively.

### Actual behavior:
Breakout-room name has "wrong" number in the name and name can not be set or changed by user.

### Server information:

- Jitsi Meet version:  jitsi-meet_1.0.5638 (latest release 2.0.6689)
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chromium Version 88.0.4324.150 (RPM Fusion Build) (64-bit)
- Operating System: Fedora 32

**Comment by saghul** [comment]
This is currently a known issue. We'll make the name configurable in the UI in a future update.
