### ISSUE TITLE
Current stable build 6689 tries ssh for remote git

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#10537]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/jitsi/rnnoise-wasm.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: Could not read from remote repository.

I'm behind a proxy (company). How can I configure https method for git download?

**Comment by saghul** [comment]
What npm version are you using?

**Comment by eraArya2601** [comment]
@saghul, I am facing the same issue. I am using npm version 7.8.0. Please suggest is it version problem?

**Comment by tseeling** [comment]
> What npm version are you using?

14.18.0 compiled for s390x, Redhat 7.9

**Comment by saghul** [comment]
That's node, I need to know the npm version too.

**Comment by tseeling** [comment]
> What npm version are you using?

$ npm --version
6.14.15

**Comment by saghul** [comment]
We have updated to 8 and that changes the package-lock format. Can you try updating to 8? You can alternatively use Node 16 which comes with it.

**Comment by tseeling** [comment]
> We have updated to 8 and that changes the package-lock format. Can you try updating to 8? You can alternatively use Node 16 which comes with it.

I have updated to the latest stable 8.2.0 and build script is running into other errors now.
Can you please elaborate why updating npm solves a problem with git accessing a repository?
My problem is that I'm inside a company and I can't ssh outside, only https with proxy is possible.
I can see that the package-lock.json contains a mixture of git+ssh: and https: URLs, and prominently rnnoise-wasm is the one which exposed the problem in the first place.

```
npm WARN tarball tarball data for lib-jitsi-meet@git+ssh://git@github.com/jitsi/lib-jitsi-meet.git#9e5d83f4aceb9f922583c871d933e97ee2b05753 (sha512-qqRAIX1bgqHo1EaaOpsycQ5t7ReBFu1drb6ZKh/MC5fzF3Bov3JSxSlZegYJ7d9ly8e9hAeIaGey6qqObNiLaA==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-VYzZHHsE6JV0igL/UV6i52yNiiWPkHdJIIQmUvKafLs2Np02vMlV05fYtlP6F/tF+BGn/lwZtDIc3VAIv+CxSA== integrity checksum failed when using sha512: wanted sha512-VYzZHHsE6JV0igL/UV6i52yNiiWPkHdJIIQmUvKafLs2Np02vMlV05fYtlP6F/tF+BGn/lwZtDIc3VAIv+CxSA== but got sha512-nqs/YhlFGNuomH620okaM9SAck/Bm/RZfSM2Etl6HCi1zBavOIhlAfLvs6rmOgRrAK5lX8Z/NUbpoVi2eQzXtw==. (26556608 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2021-12-08T11_25_18_907Z-debug-0.log
```

**Comment by tseeling** [comment]
And that's the next showstopper.
```
.../jitsi-meet-web/resources/load-test/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module '@babel/preset-react'
```

**Comment by saghul** [comment]
> Can you please elaborate why updating npm solves a problem with git accessing a repository?
> My problem is that I'm inside a company and I can't ssh outside, only https with proxy is possible.

Honestly, I don't know. We never changed that value, so it's npm creating those URLs. I was hoping using the same version we use would at least help with that.

If you look at our package.json we have no SSH URLs, looks like npm might have added them somewhat automatically to the lock file.

Try `npm install --force`

**Comment by saghul** [comment]
It should not fail with that, we have some `|| true` on the makefile :-/

**Comment by tseeling** [comment]
> It should not fail with that, we have some `|| true` on the makefile :-/

thanks, I missed that. So the Makefile finishes. I take it the missing ".map" file is nothing serious?
I could build a .deb file on my test machine, I'll continue with an updated node.js on Z.
Why was mode 755 missing for webpack and sass?
Thanks for helping so far!

**Comment by saghul** [comment]
Yep the missing files are empty by default and thus don't generate a bundle.

As for the permissions no idea, npm should take care of that usually... what is your unask?

**Comment by tseeling** [comment]
I have another problem when building on s390x. In the meantime I updated to node.js 16.13.1, npm 8.2.0, and started with a fresh download of the jitsi 6689 release.
```
> jitsi-meet-load-test@0.0.0 build
> webpack -p

/homes/DPAORNET/seelinth-admin/jitsi-meet-web/resources/load-test/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module '@babel/preset-react'
```

**Comment by saghul** [comment]
Did the npm install part complete? The "missing" package is a dependency we have and should be installed.

**Comment by tseeling** [comment]
> Did the npm install part complete? The "missing" package is a dependency we have and should be installed.

This was a fresh download and `npm install --force` used.

**Comment by saghul** [comment]
Ah wait, it's the load test that fails! What command are you running to build, `make` ?

**Comment by tseeling** [comment]
> Ah wait, it's the load test that fails! What command are you running to build, `make` ?

`make compile deploy`

**Comment by saghul** [comment]
Can you try `make` and paste the full output in a gist?

**Comment by tseeling** [comment]
> Can you try `make` and paste the full output in a gist?

https://gist.github.com/tseeling/bd3a6ffe86f37b50fbb084af057f1ab5

**Comment by saghul** [comment]
So weird. Not sure why that is happening. Try this: edit the makefile and replace `compile: compile-load-test` with `compile:` then go again.

**Comment by tseeling** [comment]
> 

`npm install` fails before I can even invoke make.

**Comment by saghul** [comment]
I'm at a loss, sorry. I think you can either build it on say Linux and copy it over or download and extract the Debian package or something similar.

**Comment by tseeling** [comment]
That's harsh but I think you're right. Continuing to try to solve this will cost more time than I can invest.
I'll either move to a podman container for building or an x86 VM.
Thanks a lot for your help and patience.

**Comment by saghul** [comment]
Godspeed! I'm going to close this, but feel free to leave a comment if you ever figure it our and we can re-evaluate.
