### ISSUE TITLE
Breakout rooms - can not send phone participant (jigasi) to breakout room

### ISSUE THREAD

**Issue by thoemie** [jitsi/jitsi-meet#10561]
### Description:

A participant that joined by phone/sip (via jigasi, calling into the meeting) can not be sent to a breakrout room.

### Steps to reproduce:

1. Start meeting
2. Call into the meeting by phone/sip (via jigasi)
3. Open participants menu
4. Add breakout room
5. Click the "3-dots-menu" for the participant that joined by phone
6. In the "Send participant to" section, click the breakoutroom that was created in step 4.

### Expected behavior:

Participant is sent to breakout room.

### Actual behavior:

Nothing happens, also no console output in Chrome Dev Tools.

### Server information:

Selfhosted on 
- Jitsi Meet version:  jitsi-meet_1.0.5638 (latest release 2.0.6689)
- Jigasi version jigasi/stable,now 1.1-215-gcab2743-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chromium Version 88.0.4324.150 (RPM Fusion Build) (64-bit)
- Operating System: Fedora 32

**Comment by saghul** [comment]
This has not been implemented yet.

**Comment by holema** [comment]
Hello @saghul,

will this be implemented in the future, or is this not planed in the at all?

**Comment by saghul** [comment]
It's not currently planned.
