### ISSUE TITLE
/base.apk!/lib/arm64-v8a/libjingle_peerconnection_so.so" not found

### ISSUE THREAD

**Issue by hafiz013** [jitsi/jitsi-meet#10570]
Jitsi version:
implementation ('org.jitsi.react:jitsi-meet-sdk:4.0.0') { transitive = true }
![1](https://user-images.githubusercontent.com/6707224/145382000-11240e60-3c45-4871-86c9-25a9d45109fa.PNG)

You can refer above error

**Comment by saghul** [comment]
Can you paste some adb logcat trace when the error happens?

**Comment by hafiz013** [comment]
sorry don't have. You try use your library on android 11 and gradle version   classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"

 compileSdkVersion 31
    //buildToolsVersion "31.0.3"

    defaultConfig {
        applicationId "com.nibmeetings.android"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode 206
        versionName "2.0.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

// To inline the bytecode built with JVM target 1.8 into
// bytecode that is being built with JVM target 1.6. (e.g. navArgs)


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

**Comment by saghul** [comment]
HAve you used our proguard rules?

**Comment by hafiz013** [comment]
@saghul any guideline about that?
