### ISSUE TITLE
Hide self view causes one participant video to stop working on meet.jitsi.com

### ISSUE THREAD

**Issue by andreasmjg** [jitsi/jitsi-meet#10578]
### Description:

Hide self view feature causes one participant video to stop working.

### Steps to reproduce:

1. Open Jitsi Meet App, version 2021.12.2, on Ubuntu 20.04 LTS
2. Start a video call with three participants
3. Click Gallery view. Notice all three participants showing, including self
4. Select "Hide Self View"

### Expected behavior:

5. Tiles shown reduced to two (as self is removed)
6. Both other video feeds except self are still working

### Actual behavior:

5. Tiles shown reduced to two (as self is removed)
6. Only ONE video is working (left). The second video tile is inactive. 

See screenshots.

### Server information:

- Jitsi Meet version: meet.jitsi.com
- Operating System: meet.jitsi.com 

### Client information:

- Browser / app version: Jitsi Meet App 2021.12.2
- Operating System: Ubuntu 20.04 LTS

### Additional information:

The other participant who had "Hide Self View" enabled in browser also had the same problem. 

The participant who's video got inactivated could not see the "Hide Self View" option. Perhaps on an earlier version of Jitsi or older browser. 

The browser versions of other participants not known.

Screenshot before activating "Hide Self View": https://ibb.co/Mc8wg9g

Screenshot after activating "Hide Self View": https://ibb.co/CQqR3mT

**Comment by saghul** [comment]
Thanks for the report, we'll look into it!

**Comment by saghul** [comment]
This was fixed in the linked OR, thanks for the report!
