### ISSUE TITLE
The word 'me" is not localized

### ISSUE THREAD

**Issue by ali-alhaidary** [jitsi/jitsi-meet#10594]
### Description:

The word 'me" is not localized
### Steps to reproduce:

enter jitsi meet in Arabic

### Expected behavior:

The word 'me' should be "أنا"

### Actual behavior:
The word 'me" is displayed as "me" in English

### Server information:

- Jitsi Meet version: 2.0.6726
- Operating System: ubuntu 18.04 LTS

### Client information:

- Browser / app version: varies (N/A)
- Operating System: varies (N/A)

### Additional information:

![Screenshot 2021-12-11 at 01-57-40 Jitsi Meet](https://user-images.githubusercontent.com/75235623/145651989-d6542d26-14a5-46ce-9fcd-52366ce56ce3.png)

**Comment by jluisfa** [comment]
Try putting in the configuration settings (config.js):
defaultLocalDisplayName: 'أنا'

**Comment by ali-alhaidary** [comment]
> Try putting in the configuration settings (config.js): `defaultLocalDisplayName: 'أنا'`

Thank you @jluisfa , hwoever, I do not have a file called config.js, defaultLocalDisplayName is commented in interface_config.js

**Comment by jluisfa** [comment]
This definition is in config.js
[https://github.com/jitsi/jitsi-meet/blob/master/config.js](url)

However, in my work I use the IFrame API:

```
configOverwrite: {
  defaultLocalDisplayName: 'eu'
}
```

**Comment by ali-alhaidary** [comment]
Thank you @jluisfa I have un-commentated defaultLocalDisplayName in interface_config.js and worked :-)
