### ISSUE TITLE
Screenshare in iOS isn't working

### ISSUE THREAD

**Issue by irohitb** [jitsi/jitsi-meet#10600]
### Steps to reproduce:
1. Created meeting on mobile, 
2. Joined from web 
3. Did Screenshare in iOS simulator app 
4. Can't see Screenshare picker in App
5. Can't see stream on web also 

### Expected behavior:
1. Should be able to see ScreenCapturePickerViewManage

### Actual behavior:
1. Screen share should've worked. 
2. https://www.loom.com/share/67e889b17fe045a3b9ae7984f3c35db6

### Server information:

- Jitsi Meet version: git master branch  (as on 13th Dec - IST)
- Operating System: MacOSX

### Client information:

- Browser / app version: Jitsi Website
- Operating System: Macos/chrome

### Additional information:
- Opening issue in react-native-webrtc as well.

**Comment by saghul** [comment]
Screen sharing does not work on the simulator. AFAIK this is a limitation on the Apple side, nothing we can do about it. I just tested the app on a real device and the picker shows up just fine.
