### ISSUE TITLE
Disabling welcome page causing the second meeting inaccessible 

### ISSUE THREAD

**Issue by basilbattikhi** [jitsi/jitsi-meet#10607]
### Steps to reproduce:

1. Open JitsiMeetActivity with disabling the welcome page 
2. Join a room with a specific URL
3.  Terminate the meeting
4. Try to join another meeting without closing the application

### Expected behavior:

The user should join the second meeting normally and the meeting should not be terminated 

### Actual behavior:

The second meeting will be ended immediately 

### Client information:

-  Library 4+
- Android 11

### Additional information:

The above behavior will not be happened if we disposed the JitsiMeetView in onCreate but if we disposed it, it's URL of jitsiMeetView will not be updated so that it will not enter in picture mode when leaving the application.

**Comment by mgkcorty** [comment]
Same issue! Please pay attention @saghul @tmoldovan8x8 

Solved with dirty hack:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    ...
    join(url);
    Thread.sleep(1000);
}
```

You can try yourself on different devices and reduce the sleep latency while the conference is working properly.

**Comment by saghul** [comment]
Can you please share a comer complete example? Are you trying to join a second meeting on the same activity?

**Comment by mgkcorty** [comment]
@saghul Thank you for answer! 

> Can you please share a comer complete example?

I will prepare complete example tonight and attach.

> Are you trying to join a second meeting on the same activity?

No. I join to second meeting in new JitsiMeetActivity, after previous JitsiMeetActivity already destroyed.
