### ISSUE TITLE
Raised hands/requests to speak are not always sorted chronically

### ISSUE THREAD

**Issue by msisov** [jitsi/jitsi-meet#10609]
### Description:

Users are not always sorted based on the order they raise hands.

### Steps to reproduce:

Imagine users participate in the meeting - jack, max, john, pavel.

1. Open 4 different browser sessions (for example, when using google-chrome, pass --user-data-dir=/tmp/user1. Open 4 different browsers with different user dirs to isolate them) and join a meeting room at meet.jit.si (the date when the issue was reproduced was 10th of December.)
2. Disable cameras and mics.
3. Open the "participants" section.
4. Let jack speak.
5. Mute jack.
5. Ensure everybody is muted and then raise hands of the users in the following order - max, pavel, john, jack

### Expected behavior:

All the users must be ordered in the order they raised their hands  - max, pavel, john, jack.

### Actual behavior:

However, the result is different -

max sees the following order -  jack, max, pavel, john
jack sees the following order - max, pavel, john, jack
pavel sees the following order - jack, max, pavel, john
john sees the following order -  jack, max, pavel, john

### Server information:

- unknown. the url is https://meet.jit.si/

### Client information:

- Browser / app version: Google Chrome 96.0.4664.45
- Operating System: Ubuntu 20.04.2 LTS

**Comment by saghul** [comment]
Ping @horymury

**Comment by anarute** [comment]
Any updates on this issue? We are still facing it. Thank you!

**Comment by saghul** [comment]
@horymury please take a look at this.

**Comment by horymury** [comment]
Created a PR to fix this. The issue was that the last dominant speaker was always showing first in the list for all but (him/her)self, regardless of the raised hand state.
