### ISSUE TITLE
Password prompt puts Android keyboard into a visible / hidden loop on tablet in landscape mode.

### ISSUE THREAD

**Issue by eggpi** [jitsi/jitsi-meet#10606]
### Description:

When joining a password-protected meeting from my tablet in landscape mode, the password prompt causes the Android keyboard to go into a visible / hidden loop that makes it impossible to use.

### Steps to reproduce:

1. In another device, create a meeting and set a password to protect it.
2. Open Jitsi Meet on the tablet, make sure it is on landscape mode.
3. Type in the meeting name and wait for the password prompt.

### Expected behavior:

I am able to join the meeting from the tablet.

### Actual behavior:

The password prompt appears and triggers a visible / hidden loop in the Android keyboard, making it impossible to use. See [this screen recording](https://gfycat.com/gorgeousidenticalibis.gif).

I can't reproduce this in portrait mode. I can also join the meeting in portrait mode and then flip to landscape with no issues.

### Server information:

I'm not running my own server, just using the default one for the app.

### Client information:

- Browser / app version: 21.5.0 build 9222825
- Operating System: Android 11
- Tablet model: Samsung Galaxy Tab A (8.0", 2019)

### Additional information:

I'll have the tablet with me only until January 2nd, but I'm happy to grab logs, try patches etc. until then. After that, hopefully we can still figure this out without physical access to it.

**Comment by saghul** [comment]
PTAL @Calinteodor

**Comment by eggpi** [comment]
I can still reproduce this on the same tablet.

**Comment by saghul** [comment]
What app version did you test with? We completely revamped dialogs on the last update.

**Comment by eggpi** [comment]
This is 22.1.1 build 10226502 according to the settings page.

**Comment by saghul** [comment]
@Calinteodor lets take another look at this.

**Comment by saghul** [comment]
I got my hands on some 7 inch Lenovo tablet and cannot reproduce this. Can you please record another video, using the latest Jitsi Meet version? Thanks!

**Comment by eggpi** [comment]
Sure. I don't have the tablet with me now but I think I can arrange that in the next few days.

**Comment by saghul** [comment]
Sounds good, thanks!

**Comment by eggpi** [comment]
[Here you go](https://gfycat.com/madpiercinghapuka.gif). The video should display the app version and reproduce the bug.

It does look a little different, and it looks like it can't be reproduced in portrait mode anymore, but it's still there in landscape.

**Comment by saghul** [comment]
Thanks! TBH I don't know what do do here, since try as I might I couldn't reproduce the problem in order to attempt a fix.

**Comment by eggpi** [comment]
Obvious question, but: would you perhaps be able to try this on an emulator with the same screen dimensions and Android version (I can confirm which one later today)?

Unfortunately I'm not near the device myself. It belongs to my parents and I only get to have it in my hands about once a year. So I _could_ investigate it, but it will be a few months until I can properly do it.

Since there are known workarounds that are not difficult, I guess we could just close this issue if it's not reproducible. I can always eventually reopen it if I figure it out.

**Comment by saghul** [comment]
> Obvious question, but: would you perhaps be able to try this on an emulator with the same screen dimensions and Android version (I can confirm which one later today)?

I could try that yeah.



> Since there are known workarounds that are not difficult, I guess we could just close this issue if it's not reproducible. I can always eventually reopen it if I figure it out.

Let's try to use the simulator to reproduce it and if not we can give up for now :-)

**Comment by eggpi** [comment]
Confirmed it's Android 11, set to pt-BR language.

For the display size, here's what they see on www.whatismyscreenresolution.org:

![](https://user-images.githubusercontent.com/489134/165233260-1d427e99-aa10-4e8b-a215-75556642eaa0.jpeg)
