### ISSUE TITLE
Android and iOS apps can't join a conference if they connect before the moderator creates the room

### ISSUE THREAD

**Issue by kpeiruza** [jitsi/jitsi-meet#10605]
### Description:

Android and iOS app used to be able to "wait for host" and when the host started the room, they simply joined.

They have stopped doing so. Tested against Jitsis from November 2020, March 2021 and latest stable docker release (2021-12-10).

### Steps to reproduce:

1. Connect with the cellphone to a conference in an authenticated Jitsi
2. Expect the "waiting-for-host" dialog (where you're offered to login)
3. Open that same room from a PC and authenticate using login+password or JWT (we've tested in internal_hashed, JWT and LDAP based setups)
4. The user on the PC creates & joins the room, but the user in the cellphone keeps on that screen forever.

Connecting after the conference has been created has no issues, it simply joins as expected.

### Expected behavior:

Just join the room whenever the next bosh request is performed.

### Actual behavior:

It keeps waiting forever.

### Server information:

- Jitsi Meet version: stable-5675 & others
- Operating System: Debian 11 and Ubuntu 20.04

### Client information:

- Browser / app version: Latest Android (7th dec 2021) and iOS versions
- Operating System: Android and iOS

### Additional information:

Tested in environments with just bosh, and bosh + websockets.

Believe me, this worked for ages. IMHO the bug has been just introduced in the latest release.

Thanks!

**Comment by saghul** [comment]
This should have been fixed by https://github.com/jitsi/jitsi-meet/commit/085b07efcd3c415c56227c92d3d096cad5b77c6c

Any chance you can join our betas and test version 21.6.0?

**Comment by kpeiruza** [comment]
Hi, we'll build our branch with that patch so we can tell you if it works in our environments.

We have several custom patches (we need to opensource many of them) so we can't reintegrate everything into -dev right now.

BTW: simultaneous language interpretation & human-fed transcription + add RGPD nottice on preJoinPage are the 3 features we're going to PR you before the end of Christmas.

**Comment by kpeiruza** [comment]
PS: it does also fail on old Jitsis that worked without this bug until very recently.

**Comment by kpeiruza** [comment]
> This should have been fixed by [085b07e](https://github.com/jitsi/jitsi-meet/commit/085b07efcd3c415c56227c92d3d096cad5b77c6c)
> 
> Any chance you can join our betas and test version 21.6.0?

How can we join your beta?

**Comment by kpeiruza** [comment]
21.6.0 fixes it :-)

Any estimated release date?

Thank you so much!

**Comment by saghul** [comment]
Hoping to push the release out this week.
