### ISSUE TITLE
Chrome freezes if I try to save Jitsi webpage

### ISSUE THREAD

**Issue by nk521** [jitsi/jitsi-meet#10601]
### Description:

If you try to save the page while in a call and then close the "Save As" popup then you won't be able to click anywhere in chrome. You also cannot close or minimize the chrome window.

### Steps to reproduce:

1. Join a call
2. ctrl+s to save the webpage
3. the page will go full screen and simultaneously there will be a "Save As" popup
4. close the popup
5. You can hit ESC to close full screen

### Expected behavior:

After closing full screen chrome shouldn't get stuck.

### Actual behavior:

After closing full screen chrome freezes and don't responds to mouse clicks. You cannot close the window, even minimize the window.
You also cannot switch the tabs. I force close the chrome window from Task Manager to fix this issue.

### Client information:

- Browser / app version: Google Chrome 96.0.4664.93
- Operating System: Windows 10 Build 19043

**Comment by saghul** [comment]
I'd say this is a Chrome bug and not something we can fix.
