### ISSUE TITLE
Participant join notification is not shown.

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#10610]
### Description:

Participant join notification message is not displayed unless one of the participants leaves the meetings.

### Steps to reproduce:

1. User A Create and join the meeting.
2. User B join the room after a few moments.
3. User A doesn't get a notification message in the left bottom corner, but get a sound notification,
4. User B leaves the meeting.
5. User C (or B) join the room.
6. User A gets a notification message.

### Expected behavior:

User A gets a toast notification always when participants join the meeting.

### Actual behavior:

Others in the room don't get join the toast notification.

### Server information:

- Jitsi Meet version: 2.0.6689
- Operating System: Ubuntu (20.04)

### Client information:

- Browser / app version: Google chrome (96.0.4664.110)
- Operating System: Ubuntu

### Additional information:

https://github.com/jitsi/jitsi-meet/blob/d2619b4dd3924cf100322bd6f59e715f58ea3a98/react/features/notifications/actions.js#L158-L190

`joinedParticipantsCount` is always zero, that array gets values only when participants leave the meeting.

https://github.com/jitsi/jitsi-meet/blob/d2619b4dd3924cf100322bd6f59e715f58ea3a98/react/features/notifications/actions.js#L300-L313

**Comment by saghul** [comment]
Jikes, looks we mixed up the variable names when adding the same logic for participant left notifications.

Would you like to send a PR with a fix?

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/10628
