### ISSUE TITLE
In iOS and Android there is no way to assign or change moderator to a particular user.

### ISSUE THREAD

**Issue by MeetSoniBV** [jitsi/jitsi-meet#10611]
No way to change JITSI moderator as of now a person or user who join first will assign as moderator and there is no such way to change it as checked over JITSI community.

For Example 

Our app is using JITSI meet for Call conference

1. USER A created a call conference (moderator according to us) and invite USER B (Invited user) to join the conference.
2. Now, If USER B join the meeting first and after then USER A join the meeting then by default USER B becomes moderator instead to of USER A and as checked there is no way to assign or change the moderator type.

**Comment by saghul** [comment]
That's just how meet.jit.si is configured. It's by design.

If you want to create a meeting where you want to make sure you are the o Lu moderator you can create a moderated meeting here: https://moderated.jitsi.net/
