### ISSUE TITLE
User controls messed up in 6726-1

### ISSUE THREAD

**Issue by bugsyb** [jitsi/jitsi-meet#10629]
### Description:

After upgrade from (new container) from 5963 to 6726-1 noticed that user controls are completely messed up. (screenshot below).
The sole reason behind upgrade was log4j issue.

Tested on Firefox and Chromium - both running on Linux.

Please advise how to troubleshoot to provide better information and hopefully to get it fixed soon.

![Screenshot from 2021-12-15 20-55-34](https://user-images.githubusercontent.com/5527773/146256074-ada59665-22cd-4c22-bdce-94a16520778a.png)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Have you tried incognito mode, do you see the same there?

**Comment by bugsyb** [comment]
Yes, tried it in incognito mode too. Sorry I didn't mentioned that and also that missed to first use forums.
Should we close it and I should head to forum first or maybe given mistake made we can try to sort it out here?

**Comment by saghul** [comment]
Have you made any changes to the default install?

**Comment by bugsyb** [comment]
Nope, no changes to install. Using https://github.com/jitsi/docker-jitsi-meet with Ubuntu instead of Debian base due to some arm64 packages were missing in Debian distros.

**Comment by saghul** [comment]
Well, that's a big change. Can you reproduce it with unmodified images?

**Comment by bugsyb** [comment]
Did some tests and this is not related to 6726-1.
What I did test (all based on docker-jitsi-meet repo):
- clean 6726-1 on amd64 - all ok
- ubuntu based 6726-1 on amd64 - all ok
- ubuntu based back on 5675 (though had to rebuild it, so not anymore same image as earlier - same issue.

This tells me two things:
- it is not related to 6726-1, which btw. I've discovered that docker-jitsi-meet repo doesn't really pull it and uses older version still
- it might be somehow related to my arm64 host, but am unclear how as everything works, just looks like as icons would be missing.

Happy to get this one closed, but if you could direct me where to look for, from where the issue comes, I'll investigate and report back with findings.

**Comment by damencho** [comment]
This really sounds like caching issue of the browser, but normally you will not have the problem in incognito...

**Comment by bugsyb** [comment]
Thank you.

Problem solved and here is what was the background. 
Whilst I've completely forgot, I've been using modified version of `app.bundle.min.js`. Because of the way docker images are built (always pull latest packages from repo), rest of jitsi-web was updated, but the `app.bundle.min.js` stayed on old customized version and as such, didn't dance well.

Once discovered, thanks to @damencho  hint it works flawlessly.

Thank you again for amazing support!
