### ISSUE TITLE
编译项目提示错误:找不到webrtc依赖库

### ISSUE THREAD

**Issue by Yanhui7** [jitsi/jitsi-meet#10631]
### Description:
I tried to compile and run this project, but it failed. And it prompted me that I could not find the dependency library org.webrtc. I tried to add implementation'org.webrtc:google-webrtc:1.0.+ in react-native-webrtc build.gradle 'Depending, but there are still errors in some places, I can't find a method in this library. Obviously the version I rely on is wrong.

### Steps to reproduce:

1.  git clone project
2.  sudo  npm install -g cnpm --registry=https://registry.npm.taobao.org
3. cnpm i
4.   Compile and run

### Expected behavior:
The project can be compiled and run normally

### Actual behavior:
Failed to run, prompting that the org.webrtc library could not be found

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Use npm 8 and follow the steps from here https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web
