### ISSUE TITLE
Option to bring back full-width tile view

### ISSUE THREAD

**Issue by k2OS** [jitsi/jitsi-meet#10638]
I was dumbounded to see after a recent update that participants windows are now cropped in the sides in tile view.
This is not a desireable 'feature' when dealing with calls where there are more than one person sharing the same camera. meaning that you suddenly crop out possible important content (I mean.. it's a video communication platform, so we assume video is important.. right?).

In my usecase, I am recording people in a conference call, in tileview which it worked perfectly for,. with the new cropped view, things are missing and going back to only having the active person shown.

I understand that some people like to have as much screeen space filled up as possible, but at least give us an opion in the UI to select which kind of tile view we want. 

Best Regards

/rené

**Comment by gpatel-fr** [comment]
Hello

should work in latest stable thanks to this [PR](https://github.com/jitsi/jitsi-meet/pull/10494)

Please test the disableTileEnlargement config.js parameter and close this issue if this fits your requirements.

**Comment by k2OS** [comment]
This sounds like a server side configuration thing?

I'm looking for a UI option, so I don't have to strong-arm the guy that runs the server I use to implement this (and maybe ruin the fun for other users who might actually like the new default cropped view (for whatever reason, but I'd like there to be room for all of us in this world))

**Comment by k2OS** [comment]
Update; i see it works as a URL-option ( #config.disableTileEnlargement=true ) as well, which helps the tech-savvy of the users*. My request still stands - please implement a UI option as well.

* It works with participants from PCs - if there are only 2 participants and one is a phone client (latest android app version), this persons view is still slightly cropped when in landscape mode. With 3 participants all seems well.
