### ISSUE TITLE
Autoplay policy in Chrome 71

### ISSUE THREAD

**Issue by jefry7** [jitsi/jitsi-meet#10633]
### Description:

If the moderator checks the boxes in the conference "everyone status muted", "everyone status hidden" and "Mute reaction sounds for everyone", then those who connect via the link after the start of the conference receive errors in the browser and the interlocutors are not heard. 
https://developer.chrome.com/blog/autoplay/

### Server information:

- Jitsi Meet version: latest
- Operating System: Debian 11

### Client information:

- Browser / app version:  96.0.4664.110
- Operating System: Windows

### Additional information:

That is, if the user connects and has to go sound immediately without any action, then there will be a problem.
According to the article, we added a key in the registry and then playback becomes normal. 
HKLM\Software\Policies\Google\Chrome\AutoplayAllowed
REG_DWORD 0x00000001

### Proposal to remedy the situation
If a person follows the link, then give him a window with the start conference button and only after that will the conference begin

**Comment by saghul** [comment]
Does enabling the prejoin page solve it for you? That will present a window for the user to select their devices and get ready before actually joining the meeting.

**Comment by jefry7** [comment]
In fact, it should solve the problem. How do I turn it on?

**Comment by jefry7** [comment]
Are you talking about this setting? I will try

/etc/jitsi/meet/<domain>-config.js
```
    // Configs for prejoin page.
    //prejoinConfig: {
    //     // When 'true', it shows an intermediate page before joining, where the user can configure their devices.
    //     // This replaces `prejoinPageEnabled`.
    //     enabled: true,
    //     // List of buttons to hide from the extra join options dropdown.
    //     hideExtraJoinButtons: ['no-audio', 'by-phone']
    // },
```

**Comment by saghul** [comment]
Yep, that's the one.

**Comment by jefry7** [comment]
Thanks for the tip. I passed the initial tests, it remains to be checked in combat conditions
