### ISSUE TITLE
why does jit-si meet not support for latest chrome version

### ISSUE THREAD

**Issue by prasadaher1999** [jitsi/jitsi-meet#10641]
why does jit-si meet not support for latest chrome version #10641

**Comment by jbg** [comment]
Chrome 96 deprecated Plan B SDP, which is used by old versions of Jitsi Meet. If you're using a recent version of Jitsi Meet then it works fine with latest Chrome.

This type of question would ideally be directed to https://community.jitsi.org/ rather than GitHub issues.

**Comment by saghul** [comment]
It does. If you are running an old release you need to update to the latest.
