### ISSUE TITLE
[Android SDK] Broadcasting Actions Type is not public as handbook.

### ISSUE THREAD

**Issue by pqkluan** [jitsi/jitsi-meet#10647]
### Description:

I follow Android guide up to this section [Android Broadcast Actions](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#broadcasting-actions).

Here is the code snippet:

```java
    Intent muteBroadcastIntent = new Intent(BroadcastAction.Type.SET_AUDIO_MUTED.getAction());
    muteBroadcastIntent.putExtra("muted", muted);
    LocalBroadcastManager.getInstance(getApplicationContext()).sendBroadcast(muteBroadcastIntent);
```

The problem is `BroadcastAction.Type` is not public, so I cannot import the type but have copy action string.

Here is the current implementation of Broadcast.

```java
public class BroadcastAction {
  ...
  static enum Type { 
// ^ should be public
    SET_AUDIO_MUTED("org.jitsi.meet.SET_AUDIO_MUTED"),
    HANG_UP("org.jitsi.meet.HANG_UP"),
    SEND_ENDPOINT_TEXT_MESSAGE("org.jitsi.meet.SEND_ENDPOINT_TEXT_MESSAGE"),
    ...
  }
}
```

### Server information:

- Jitsi Meet version: Android SDK 4.1.0

**Comment by saghul** [comment]
Ping @tmoldovan8x8

**Comment by tmoldovan8x8** [comment]
Hello @pqkluan. Indeed we have to update the documentation there. The intended way of using the actions is via the BroadcastIntentHelper static methods. Please go ahead and use buildSetAudioMutedIntent for your usecase.
