### ISSUE TITLE
Voice connection delay Problem  in Jitsi mobile SDK

### ISSUE THREAD

**Issue by kirtirc** [jitsi/jitsi-meet#10646]
Hello @saghul @damencho 
we are using jitsi SDK in IOS, Android and when try to connect them then it taking 3-4 second delay for voice connection so initial we are not hearing each other and we tested in wifi with good internet speed.
we tested  in our self-hosted server  and meet.jit.si  server and problem happen in both server.  

### Steps to reproduce:

1.Take 2 Device and open app (make sure app not running in background ,kill app and open again )
2. Enter room name in in first device then enter same room name in second device
Thanks

**Comment by saghul** [comment]
When do you start measuring exactly?

**Comment by saghul** [comment]
I wonder if this is related to: https://github.com/jitsi/jitsi-meet/issues/10614

**Comment by kirtirc** [comment]
We facing same problem in Native Mobile SDK.
we downloaded jitsi meet app from app store and checked this problem below is step to reproduce.

User A  enter room name (eg - "audiotest") and join room
User B  join same  room name(eg - "audiotest").

User A  see User B joined in the room and starting to speak with User B, but unfortunately User B can not hearing initial 3-4 Second after joining room.
we started stop watch after User B joined and avaialble in room. and trying to check audio inially for first 3-4 second and User A or B can not hear both the side of user A and User B. 

We find conclusion that initially in approximately 3 seconds user can not hear anything from another user.

**Comment by vinitcc** [comment]
Hello @saghul @damencho
I am using latest Jitsi Meet SDK in iOS. I am facing slow connection issue in high speed wifi internet speed.

**Comment by saghul** [comment]
> When do you start measuring exactly?

I have not received an answer to this yet. Are you measuring since you receive the CONFERENCE_JOINED event or earlier?

**Comment by kirtirc** [comment]
@saghul 
I checked and it take minimum 2 second after CONFERENCE_JOINED  event
Thanks

**Comment by saghul** [comment]
After that event the media negotiation takes place. We'll need to check if it am be further optimized, but don't hold your breadth because we have quite a few large fish to fry, te migration to Unified Plan for example may have an impact on this.

**Comment by kirtirc** [comment]
@saghul  do you  improved this  problem 
Thanks

**Comment by saghul** [comment]
No, we haven't looked into it.

**Comment by iampato** [comment]
It isn't a common webtrc thing to happen ?

**Comment by patelnishantk** [comment]
@saghul Any plans to take this up in near future? We do face similar issue. Some of the conversation is lost within these few seconds of delay.

**Comment by saghul** [comment]
You can try enabling WebSocket support (check the testing section in config.js). That should speed up joining the meeting.

How many participants are there when you join and notice the delay?

**Comment by patelnishantk** [comment]
@saghul Just 2 of them. First one already in the meeting, when second participant joins, we see a delay of at least 2 seconds on good network, a few more seconds when using mobile network. This happens for normal audio only meeting.

Thanks for guiding with the configuration! Will try it out and update here
