### ISSUE TITLE
Bridge Channel send: no opened channel

### ISSUE THREAD

**Issue by xuwenbingfor** [jitsi/jitsi-meet#10644]
When there are 3 participants, there is no video and audio on the web page.
The error like this:
"[modules/RTC/BridgeChannel.js] <e.value>:  Bridge Channel send: no opened channel."

server os version: Ubuntu 16.04
chrome version: 92

**Comment by saghul** [comment]
Please port questions like this one in our community.

Review your configuration, looks like the bridge channel between the browser and the JVB is not getting established. Do you have a firewall in place?
