### ISSUE TITLE
stable/jitsi-meet_6726 Doesn't work properly under iOS

### ISSUE THREAD

**Issue by xiaowasly** [jitsi/jitsi-meet#10640]
A problem occurred when I switched the branch to stable/jitsi-meet_6726
<img width="391" alt="123" src="https://user-images.githubusercontent.com/22368246/146474087-36467567-a59e-4a30-9053-992a5df6cf94.png">
<img width="867" alt="234" src="https://user-images.githubusercontent.com/22368246/146474092-040e9b1c-60ff-446b-9fe2-68f0370dd0f7.png">

**Comment by saghul** [comment]
Stable tags are meant for backend components. For the app you can take the latest tag like ios-21.5.0 o the upcoming branch mobile-21.6
