### ISSUE TITLE
Joining meeting from chrome browser is shown as muted to other's participant's and unable to hear the audio of other speaker's on the meeting

### ISSUE THREAD

**Issue by Sbhonagiri** [jitsi/jitsi-meet#10656]
![Screenshot 2021-12-18 at 7 23 13 PM](https://user-images.githubusercontent.com/17709729/146643496-207be19d-43a8-4081-ac67-2637c810eca6.png)

![Screenshot 2021-12-18 at 6 43 30 PM](https://user-images.githubusercontent.com/17709729/146643465-ce8769d2-09a3-4ee1-a6a8-1de9b60353e9.png)

**Comment by Sbhonagiri** [comment]
Anyone could please help in regard with this issue on prirority

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Have you tried enabling prejoin screen, does that change anything?

**Comment by damencho** [comment]
Ah I saw your second screenshot, you need to update, you are using old version and Chrome had dropped support for planB.
