### ISSUE TITLE
Trying to install jitsi meet with apache2

### ISSUE THREAD

**Issue by Gspohu** [jitsi/jitsi-meet#1066]
Hello everyone, 

I know there are already open issues on this subject, but they don't produce good results and I would like to share, here, my thinking on this subject. Feel free to moderate my post if you think it's a bad idea.

Server: Ubuntu 16.04.1, Apache2.4.18
DNS conf:
for Jitsi meet - meet.mydomain.xx ----> ip_of_my_server
for my website - mydomain.xx ----> ip_of_my_server

Like I said I try to run Jitsi meet on apache2.
By following the steps described in Quick install (https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md)

If I install Jitsi meet on my server just after installing Ubuntu so without Apache or Nginx. Jitsi works great.
If I install Jitsi meet on my server after installing Nginx. Jitsi works great.

With the same method of installation, I try to install Jitsi meet after installing Apache2, so I notice that Jitsi meet does not configure itself apache2, so I tried this first configuration:

```
<VirtualHost *:443>
ServerAdmin postmaster@mydomain.xx
ServerName  meet.mydomain.xx
ServerAlias  meet.mydomain.xx
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
DocumentRoot "/usr/share/jitsi-meet/"
<Directory /usr/share/jitsi-meet/>
AllowOverride All
</Directory>

ProxyPass / http://meet.mydomain.xx:5280/http-bind
ProxyPassReverse / http://meet.mydomain.xx:5280/http-bind

ProxyPreserveHost Off

<Location "/http-bind">
   Order allow,deny
   Allow from all
</Location>

<Location "/meet/xmpp-websocket">
    ProxyPass http://meet.mydomain.xx:5280
    ProxyPassReverse http://meet.mydomain.xx:5280
</Location>

ErrorLog /var/www/meet/logs/error.log
CustomLog /var/www/meet/logs/access.log combined
SSLCertificateFile /etc/letsencrypt/live/acert.mydomain.xx/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/acert.mydomain.xx/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

```
When I load the page meet.mydomain.xx I get the following error:

> "It works! Now your customer BOSH points to this URL to connect to Prosody.
> 
> For more information see Prosody. Setting up BOSH "

But when I look at the /etc/prosody/conf.avail/meet.mydomain.xx.cfg.lua file, I notice that bosh is already enabled and the rest of the configuration is ok with what is explain here https://github.com/jitsi /jitsi-meet/blob/master/doc/manual-install.md
The log contains no errors.
If you have an idea to fix this problem I'm interested.

Second configuration that I tested:
```
<VirtualHost *:80>
ServerAdmin postmaster@mydomain.xx
ServerName  meet.mydomain.xx
ServerAlias  meet.mydomain.xx
DocumentRoot "/usr/share/jitsi-meet/"

SSLProxyEngine On
RewriteEngine On
RewriteCond %{REQUEST_URI} ^/[a-zA-Z0-9]+$
RewriteRule ^/(.*)$ / [PT]
RewriteRule ^/http-bind$ https://meet.mydomain.xx:5281/http-bind [P,L]

ErrorLog /var/www/meet/logs/error.log
CustomLog /var/www/meet/logs/access.log combined
</Virtualhost>
```

With this setup the result seems better, I can see the home page of Jitsi meet but without the text, without the logo and when I click on the go button, nothing happend.
The log contains no errors.

So here I don't no really what to do. If someone have some advices or ideas, ​​thank you to share it !

Bye, thank you for reading

Gspohu

**Comment by damencho** [comment]
Please use the mailinglist before opening issues when having a problem or want to discuss something. 
Have you tried these apache settings: http://lists.jitsi.org/pipermail/dev/2014-February/019946.html
webrtc will not work on port 80, you need https (443). Also if you install jitsi-meet without nginx it will configure itself to use port 443 and it will be in conflict with apache.
