### ISSUE TITLE
bluetooth doesn't work with native call integration on

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#10667]
### Steps to reproduce:

0. Connect a bluetooth headset
1. Toggle Disable native call integration off
2. Join a room
3. Internal mic is used instead of headset's one

### Client information:

- Browser / app version: 21.5.0 build 21500 from F-Droid
- Operating System: Android 11

**Comment by saghul** [comment]
Does it work if you reverse the order of the first 2 steps?

**Comment by 532910** [comment]
If I connect a headset after Jitsi start (it doesn't matter native call integration is on or off) it's not even shown in the sound devices select list.

**Comment by saghul** [comment]
What kind of Bluetooth device are you connecting? Is it a headset like thing, with a microphone and a speaker?

**Comment by 532910** [comment]
Yep, Plantronics Edge for example.

linux shows following UUIDs for it:
```
00000000-deca-fade-deca-deafdecacaff Proprietary
00001108-0000-1000-8000-00805f9b34fb Headset
0000110b-0000-1000-8000-00805f9b34fb Audio Sink
0000110c-0000-1000-8000-00805f9b34fb Remote Control Target
0000110e-0000-1000-8000-00805f9b34fb Remote Control
0000111e-0000-1000-8000-00805f9b34fb Handsfree
0000112f-0000-1000-8000-00805f9b34fb Phonebook Access (PBAP) - PSE
00001200-0000-1000-8000-00805f9b34fb PnP Information
82972387-294e-4d62-97b5-2668aa35f618 Proprietary
```

**Comment by 532910** [comment]
still actual
