### ISSUE TITLE
Native call integration setting not saved on exit

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#10666]
### Steps to reproduce:

1. Toggle `Disable native call integration` off
2. Close Jitsi from drawer
3. Open Jitsi
4. `Disable native call integration` is on

### Client information:

- Browser / app version: 21.5.0 build 21500 from F-Droid
- Operating System: Android 11

**Comment by 532910** [comment]
still actual

**Comment by 532910** [comment]
still actual

**Comment by saghul** [comment]
We had many issues with it and disabled it by default. 2 years have passed and clearly nobody cares enough about it to fix it.

**Comment by 532910** [comment]
Possibly native call integration should be removed this way, or it's setting should be hidden for non-developers?

**Comment by saghul** [comment]
It's in the advanced section already.
