### ISSUE TITLE
Each tile in vertical tileview takes the whole height in web version of jitsi.  To see other tiles, one must scroll down

### ISSUE THREAD

**Issue by pmestrum** [jitsi/jitsi-meet#10661]
### Description:

with config 
      VERTICAL_FILMSTRIP: false,
      TILE_VIEW_MAX_COLUMNS: 1,
tiles are ordered vertically in one column, but each tile takes the complete viewHeight.
PR 10201 (https://github.com/jitsi/jitsi-meet/pull/10201) introduces this bug: 
react/features/filmpstrip/functions.web.js:218-219
![image](https://user-images.githubusercontent.com/25814463/146678015-73f44127-d846-4404-a865-94c0091225e9.png)

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:
each tile takes the height needed to keep aspect ratio (as it was before 10201)

### Actual behavior:

![image](https://user-images.githubusercontent.com/25814463/146678093-3b7c6e63-59d4-4d23-8353-c28541c32fa5.png)
each tile takes the complete height (initialHeight)

### Server information:

- Jitsi Meet version: v5666.2368 (embedded in iframe)
- Operating System: ?

### Client information:

- Browser / app version: chrome
- Operating System: macos

**Comment by pmestrum** [comment]
This fixes it and keeps the changes for #10201, but I'm not a contributor so I can't create a PR.

![image](https://user-images.githubusercontent.com/25814463/146681115-d62c9950-ad33-4a4c-a668-b48a36edc7fa.png)

**Comment by quitrk** [comment]
https://github.com/jitsi/jitsi-meet/pull/10645 this fixes the behaviour

**Comment by pmestrum** [comment]
10645 didn't fix this issue. please reopen.
