### ISSUE TITLE
Need document for iOS CallKit

### ISSUE THREAD

**Issue by songoten28** [jitsi/jitsi-meet#10665]
**Is your feature request related to a problem you are facing?**
don't have audio for iOS callkit ( from VOIP push notification ) in Lock screen

![alt text](https://miro.medium.com/max/1500/1*T76lpbewnunOx-nfBhnu9w.png)

**Describe the solution you'd like**
- Need document for this part

**Describe alternatives you've considered**
I already try to implement RNCallKeep to show Callkit from Voip push notification on Lockscreen
and try with these issues but no luck.
I'm not iOS expert 
https://github.com/jitsi/jitsi-meet/issues/9983
https://github.com/jitsi/jitsi-meet/issues/4381

Could you make a document for this part

**Comment by saghul** [comment]
Did you set the voip and audio background modes?

**Comment by songoten28** [comment]
@saghul 
Thank for response
I already did that and try to many time, could you please create example using CallKit in lockscreen?

<img width="654" alt="Screen Shot 2021-12-21 at 11 44 35 AM" src="https://user-images.githubusercontent.com/11750588/146872523-585562bd-7555-4d0b-b0bb-3711e45f242a.png">

**Comment by saghul** [comment]
Why are you using RNCallKeep? The Jitsi Meet SDK already has CallKit integration. If you are not going to use it you'll need to disable it so they don't collide.

**Comment by songoten28** [comment]
You right! I already remove RNCallKeep and Using JMCallKitProxy and it working
But how to connect to Room. It alway say Audio connecting in here
![Screen Shot 2021-12-21 at 6 13 09 PM](https://user-images.githubusercontent.com/11750588/146920871-d946850d-61cc-4395-92ce-e31e3f7ceae0.png)

This is my source code:
<img width="910" alt="Screen Shot 2021-12-21 at 6 14 46 PM" src="https://user-images.githubusercontent.com/11750588/146921096-f41f6da1-d400-4ac3-bbda-ed7b1727da5d.png">

**Comment by songoten28** [comment]
I forgot to addView to self.window.
Closed issue

**Comment by rohmat97** [comment]
> I forgot to addView to self.window. Closed issue

hello, 
can you give me a sample code ? where did you put self.windows?

**Comment by Sh4dord** [comment]
> I forgot to addView to self.window. Closed issue

I also try to understand what it mean....
Can someone help to work with CallKit ?
Thanks you !
