### ISSUE TITLE
Meeting Keeps Closing Automatically

### ISSUE THREAD

**Issue by Thirumalai08** [jitsi/jitsi-meet#10663]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System: 2.0.1

### Additional information:

When i try to connect in the meeting i couldnt able to join in room it keeps on closing automatically

**Comment by saghul** [comment]
There is no way for anyone to help without more details. You didn't even fill in the steps section.
