### ISSUE TITLE
Don't change microphone settings automatically

### ISSUE THREAD

**Issue by schoerg** [jitsi/jitsi-meet#10675]
### Description:

Input volume will change automatically upon joining. 

### Steps to reproduce:

Change input volume to ~50
Join Jitsi meet session
Input volume will change, either increasing, decreasing, whatever the algorithm thinks is best.

### Expected behavior:

Input volume should not change. Or at least ask the user before. I have set my microphone to a value which is not too loud and not too quiet, having Jitsi change it for all other applications on the system is unreasonable.

### Client information:

Chrome/92.0.4515.126
Windows 10 1909

**Comment by damencho** [comment]
Do you see the same here? https://webrtc.github.io/samples/src/content/devices/input-output/
There is no logic in jitsi-meet to change input level, if there is something it is between the browser and the OS ...

**Comment by saghul** [comment]
This could also be due to AGC.

**Comment by schoerg** [comment]
Couldn't trigger it with https://webrtc.github.io/samples/src/content/devices/input-output/

but in Meet it's also not consistent.

**Comment by dsvk** [comment]
This is possible for me to trigger in:

- the [Electron desktop app](https://github.com/jitsi/jitsi-meet-electron) *if* `Disable automatic gain control` is left untoggled in the app settings (the ones available _before_ joining the meeting - where the custom server URL is configured) 
- Chromium (where an AGC toggle doesn't appear to be provided by Jitsi Meet anywhere and hence AGC seems unavoidable unless there is a browser-wide settings flag to disable it globally). However, there's at least one competitor app I know of where an AGC toggle _is_ provided in their web version and makes this user-configurable in the call input device settings so it _does_ seem the technical means are available to do this.  

Firefox doesn't seem to be applying AGC on my end (although my profile is quite customized so I wouldn't call this a definitive finding).
