### ISSUE TITLE
Chat posts are missing names of participants in breakout rooms

### ISSUE THREAD

**Issue by weltfahr** [jitsi/jitsi-meet#10671]
### Description:

When a participant returns to the main room, all chat posts from participants who are currently in breakout rooms do not show the display names, but Fellow Jitster.

### Steps to reproduce:

1. Participant1 posts "test" in the chat panel.
2. Participant2 replies with "test"
3. Both go to a breakout room.
4. Participant1 returns first.
5. Participant2 returns next.

### Expected behavior:

Chat panel of Participant1 should state:
me says:test 
14:36
Participant2
Participant2 says:test 
14:36

### Actual behavior:

Panel shows:
me says:test 
14:36
Fellow Jitster
Fellow Jitster says:test 
14:36

### Server information:

Currently on alpha.jitsi.net.

### Additional information:

It seems like the display name of chat entries are only retrieved from those in the current room and are not looked up in the other rooms of the conference (that is the features/breakout-rooms state).

**Comment by ashiqhassan95** [comment]
The same scenario occurs not only in a breakout room but in the normal conference room too.

Steps to regenerate

1. User A created and joined the meeting.
2. User B joined the meeting, send a chat message.
3. User A gets the message from User B.
4. Now User B leave the conference,
5. User C join the meeting, can see chat messages of User B, but display name will be Fellow Jistster (default remote displayname).

**Comment by weltfahr** [comment]
> The same scenario occurs not only in a breakout room but in the normal conference room too.

Thanks for pointing this out, @ashiqhassan95. I think this is what @damencho referred by "known limitation due to security reasons". There could be privacy concerns, if display names would remain visible to new participants after a participant leaves.

I am not too concerned not seeing the names of participants who left next to their post. But posts of participants who are still in the conference but in a breakout room should be related to the individual by their display name.

**Comment by ashiqhassan95** [comment]
If that is due to security concerns, then why do need to show messages of that user. Correct me if I'm wrong.

**Comment by weltfahr** [comment]
> If that is due to security concerns, then why do need to show messages of that user. Correct me if I'm wrong.

Good point. It might be due to the conversation becoming confusing if "arbitrary" posts are missing. It's like if my initial post above would be removed and it would be hard to understand what this thread is about. One could still follow though the conversation. if just my name would be removed. – This is just my guess, as it would make sense to me.

**Comment by damencho** [comment]
The way this was working few years back, was that when participants send messages, they send and the display name they have. And this is what is stored in room history to be shown for those joining later.
The problem is that someone can use this to impersonate and send messages that will appear from a different participant. So that display name storing was dropped.

**Comment by Shahzad062** [comment]
Can Anyone tell me in react native how can i change this name to Fellow Jitser to any OtherName @ashiqhassan95 @damencho @weltfahr @jcfischer @monkeydom

**Comment by ashiqhassan95** [comment]
https://github.com/jitsi/jitsi-meet/blob/0170c65c7b84979df5b74634134b4e93b0a35c4e/config.js#L626

**Comment by Shahzad062** [comment]
@ashiqhassan95  brother in react native how i can add this beacause i m using  vidit-me react native jitsi meet package  its not getting config prop
