### ISSUE TITLE
Webcam not working in Firefox

### ISSUE THREAD

**Issue by keeza123** [jitsi/jitsi-meet#10682]
### Description:

When I initially start a call my video and audio works fine. However if i stop my video temporarily and then try and restart it, it will not restart. This then affects my other apps using webcam, namely Teams and Zoom i.e. video will no longer work on those apps too. Others' video/audio still works fine. If i restart the browser and join another call then the issue still persists.

I have tested on Chrome and the same issue does not occur when i stop/start the video.

### Server information:

Main Jitsi server: https://meet.jit.si/

### Client information:

- Browser / app version: Firefox 95.0.2 64bit 
- Operating System: Windows 10 Enterprise 10.0.17134

**Comment by saghul** [comment]
How are you stopping the video, by muting it in Jitsi?

**Comment by keeza123** [comment]
Just by pressing the video icon (next to the audio/mute icon) during a call


22 Dec 2021, 16:12 by ***@***.***:

**Comment by saghul** [comment]
Do you get any errors in the browser console, when trying to unmute?

**Comment by keeza123** [comment]
No - muting and unmuting works fine. It is just the start/stop video button that remains stopped (i.e. with a line through it) and if i click it thereafter to start again nothing happens and the icon remains unchanged.

Audio/video browser permissions have already been granted 


23 Dec 2021, 07:59 by ***@***.***:

**Comment by saghul** [comment]
Can you post a screenshot please? I'm not sure what button you mean.

**Comment by keeza123** [comment]
https://cloud.sos-uk.org/s/8ddTb6L3WkWECfB

See video icon underneath the "join meeting" button. The same icon I am referring to after you join the meeting too.

The error message displayed comes up after i stop the video, try and restart it (to no avail) and then try and join another room. Permissions are already granted


23 Dec 2021, 11:31 by ***@***.***:

**Comment by saghul** [comment]
Ah, go it, so the prejoin screen. Don't you get any error messages in the JS console?

**Comment by keeza123** [comment]
not sure what you mean by JS console (i am using the main meet.jit.si server), but the same error message comes up when i am actually in the meeting too if i try and stop/start the video


23 Dec 2021, 12:06 by ***@***.***:

**Comment by saghul** [comment]
If you open developer tools, web console (or JavaScript console) what do you see?

**Comment by keeza123** [comment]
Sorry, i'm not sure how to do this. If it's any help, I've just tried it on a live Parrot OS usb on Firefox and the issue does not replicate. 


Dec 24, 2021, 10:52 by ***@***.***:

**Comment by saghul** [comment]
Here is how to open the JS console: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

**Comment by keeza123** [comment]
Thanks. It comes up with this and doesn't allow access to the camera:

2022-01-03T21:53:29.637Z [modules/RTC/RTCUtils.js] <7273/_getUserMedia/</<>:  Failed to get access to local media. NotReadableError: Failed to allocate videosource {"video":{"height":{"ideal":720,"max":720,"min":180},"width":{"ideal":1280,"max":1280,"min":320},"facingMode":"user"},"audio":false}


27 Dec 2021, 12:48 by ***@***.***:

**Comment by saghul** [comment]
So weird. I see no reason why that would fail. What webcam is that, out of curiosity?

**Comment by keeza123** [comment]
I tried it on a live USB for Linux Mint 20.2 xfce and it works in Firefox fine. Just not Windows it seems!

I ran the relevant command and it just says Laptop_Integrated_Webcam_E4HD i.e. built-in webcam. The laptop is Dell Latitude E5430


Jan 5, 2022, 10:33 by ***@***.***:

**Comment by Helianthropy** [comment]
I’m seeing this (or a similar issue) with Firefox 134 and now with Waterfox 140 (based on Firefox) on macOS 14 using Jitsi version ffcffaa7. In both cases I’m getting the Javascript errors:
`[ERROR] [app:media] <setSinkId/<>:  Error setting sink DOMException: The object can not be found here. [Logger.js:158:27](webpack://jitsi-meet/node_modules/@jitsi/logger/lib/Logger.js)` (this occurs multiple times—39 times by one count)

Then, when trying to enable the camera (after it has been disabled), this specific error occurs:
`[ERROR] [app:tracks] <Sv/</<>:  Failed to create local tracks Array [ "video" ] TypeError: can't access property "ideal", t.height is undefined [Logger.js:158:27](webpack://jitsi-meet/node_modules/@jitsi/logger/lib/Logger.js)` (There’s a stack trace I can share as well.)

Muting and unmuting video works fine with Safari, and a similar number of [app:media] errors (of a different type) are present.

**Comment by tilldoerges** [comment]
> Then, when trying to enable the camera (after it has been disabled), this specific error occurs: `[ERROR] [app:tracks] <Sv/</<>: Failed to create local tracks Array [ "video" ] TypeError: can't access property "ideal", t.height is undefined [Logger.js:158:27](webpack://jitsi-meet/node_modules/@jitsi/logger/lib/Logger.js)` (There’s a stack trace I can share as well.)

What did the trick here, was to delete Cookies and Site Data for the problematic site.
