### ISSUE TITLE
Stereo audio only works when everyone uses Firefox

### ISSUE THREAD

**Issue by slannon97** [jitsi/jitsi-meet#10684]
I'd like to use Jitsi with the highest quality audio settings possible. To that end, I've tried creating a meeting using the following link format:
https://meet.jit.si/test#config.p2p.enabled=false&config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true

If I join using two Firefox browsers on two computers, audio is great! However, if one or both browsers aren't Firefox, it's high quality mono. Why is this? Is it a problem with the code that can be fixed or is this a browser issue that can't be controlled? It would be great if everyone could benefit from high quality stereo audio, no matter the browser combination.

**Comment by saghul** [comment]
Have you tried the new audio quality settings? https://github.com/jitsi/jitsi-meet/blob/a436a889a904016b7cbdc1de4f043d0abbab29fe/config.js#L162

**Comment by slannon97** [comment]
Does this only work if you're hosting your own Jitsi server? I'm a bit confused. Will this do what I want on all browsers or is it still restricted to Firefox only? I've had a little trouble setting up my own server and thought there was a way to do it with the public meet.jit.si one as a test.

**Comment by jbg** [comment]
[The `audioQuality` key is whitelisted as well](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/configWhitelist.js#L20) so you should be able to set the `audioQuality` values in the URL just as you're doing with the others.

e.g. `&config.audioQuality.stereo=true&config.audioQuality.opusMaxAverageBitrate=510000`

**Comment by slannon97** [comment]
Okay, the following link seems to work, but only if joining the meeting from Firefox.
https://meet.jit.si/slannon#config.p2p.enabled=false&config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.audioQuality.stereo=true&config.audioQuality.opusMaxAverageBitrate=510000
It appears any browser can transmit in stereo, but attempting to use anything other than Firefox results in receiving mono audio. For example, hosting a meeting with Brave and joining with Firefox gives stereo, but I can't host the meeting with Brave and join using Safari or another instance of Brave. Is this something that can be fixed or is it a problem with WebKit and Chromium? The bitrate is rather high, can I change the value to something like 96000? The audio quality is great, I'm just irritated I can't hear stereo audio unless I use Firefox.

**Comment by jbg** [comment]
You can set the bitrate to anything you want within what Opus supports — 510k is the max. I seem to remember seeing some logic that triggers Opus "music / general audio" mode (as opposed to voice mode) above a certain bitrate, but can't remember exactly how that works.

As for browser support, both sending and receiving stereo worked on Chrome last time I tried, but that was a year ago. I'll try to test again tomorrow and report back.

**Comment by slannon97** [comment]
I tested Chrome, Firefox, Edge, Brave, and Safari. Out of all those, it appears only Firefox can properly receive stereo sound. This is either an issue with WebKit and Chromium, or something with Jitsi itself. I'm using the latest versions of all these browsers including Safari 15.2 on both macOS Big Sur and iOS 15.

**Comment by gpatel-fr** [comment]
Hello

I tested this today on my test Jitsi-meet instance running unstable (2.0.6795-1) with

``
    audioQuality: {
        stereo: true,
        opusMaxAverageBitrate: null // Value to fit the 6000 to 510000 range.
    },
``

between 2 computers running Ubuntu 20.04 (sender) and 18.04 (receiver), with Chromium 97.0.4692.71 (snap Ubuntu) and this high resolution file that I shared in a Chromium tab:

https://helpguide.sony.net/high-res/sample1/v1/en/index.html

and the file played with the same quality as played locally when stereo = true (and definitely with low quality when stereo not set, that is by default, equal to false). Note that 'same quality' is subjective (I am not an audiophile :-))

So I can't reproduce your problem. 

I have no access to a Mac computer to check on the same kind of hardware, but it does not seem to be a generic Jitsi-meet defect. 

Maybe it has something to do with your hardware, it would be interesting to get the opinion of something else using a Mac.

**Comment by slannon97** [comment]
Hmmm, you're using a beta version? Maybe it's fixed in an upcoming version? I just tried it using the latest versions of Brave and Chrome which both appear to be on Chromium 97 now. I'm still getting very high quality mono, even if I use the share feature to share a YouTube Brave tab. As usual, Firefox worked just fine. It must be something with Chromium and WebKit. I also don't find the need to increase the bitrate that high, 96000 is perfectly acceptable. It's not as big of a deal now that I discovered you can share YouTUbe directly into the meeting which seems to play it for all participants locally. It's still a little disappointing that microphone or even shared coputer sound is in mono, but that's okay. I'll wait to see if this is fixed in future versions of Jitsi itself and/or browsers.

**Comment by gpatel-fr** [comment]
I fired up a stable version (2.0.6726-1)  and stereo seems to works fine too.

**Comment by slannon97** [comment]
Strange, it's not working for me. I tried Chrome and Edge as both the sender and receiver. When I share system audio using the screen share tool or use my mixer, it's always high quality mono in the other browser unless of course I use Firefox. I'm using the latest versions of these browsers as well.

At this point I'm out of ideas. I suppose this isn't a major deal since you can always embed YouTube stereo videos for things like music, but it would have been nice to for example stream game audio from my computer in stereo as well. It works, but only if the receiver is using Firefox. Is this something that should be reported on the Chromium and WebKit projects specifically instead of Jitsi?
I'm using the following link format as a test each time, and I can consistently get Firefox to receive stereo no matter if I'm using Firefox, Edge, Chrome, or Brave as the sender.
https://meet.jit.si/slannon#config.p2p.enabled=false&config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.audioQuality.stereo=true&config.audioQuality.opusMaxAverageBitrate=96000

**Comment by saghul** [comment]
Any chance you have another browser tab doing microphone stuff while you are testing?

Chrome will only open the mic once, with a single set of settings, so if you first open it in mono and then request stereo it will remain mono.

**Comment by gpatel-fr** [comment]
I adapted your URL to my test stable server and got stereo on my Ubuntu workstation with Chromium 97.

This said, I wonder if your music use is a common one. For many videoconferencing uses, stereo is not necessary. In fact I used my test server for a small conference just after, having left the stereo config in place, and got very bad results - the other person was not using a headset and I got Larsen effects and echos. 
What I mean is that for features that are probably not in wide use, like music for a videoconferencing solution, there could be problems that are not easily flushed out because a not insignificant percentage of a very small percentage of persons using a given feature don't make a basis for a lot of bug reports. Did you post on the Jitsi forum asking for experience about this specific problem ?

**Comment by slannon97** [comment]
Hmmm, I wonder if it has something to do with Linux or using Chromium specifically? All my tests have been on Windows and macOS. I haven't posted on the forum, I might just to find out if this is something reproducible. It's not a major issue as I said since you can share YouTube videos. That link creates a meeting with the highest audio quality, so there will definitely be lots of echo if someone is using speakers. You're right that this use case isn't very popular, but Jitsi allows it, so I was simply curious. The best answer I've been able to come up with is that Firefox is the only browser that can handle Opus stereo audio with Web RTC. I mainly wanted to report this so it's out there.

I'm not using the browser for anything else, I literally open a new instance and join the meeting.

**Comment by andytiedye** [comment]
We still care about good stereo sound!

**Comment by saghul** [comment]
So do we. Nobody could reproduce the initial problem.

**Comment by emdrremote** [comment]
I was able to add audio: true into the config overrides and it solved the issue for me. Before adding that in, stereo was only working in Firefox.
