### ISSUE TITLE
Cannot join existing room on iOS with JWT enabled

### ISSUE THREAD

**Issue by xiaowasly** [jitsi/jitsi-meet#10685]
We have enabled JWT on our server and added builder.token to the iOS code, but the meeting cannot be joined normall
<img width="1194" alt="123" src="https://user-images.githubusercontent.com/22368246/147060393-08664183-224a-4de0-a5f1-5a8ff5787825.png">
y

**Comment by saghul** [comment]
What problem do you observe? What do the logs say? What SDK version are you using?

**Comment by xiaowasly** [comment]
We have found the problem, which is the JWT generation error. Really sorry

**Comment by xiaowasly** [comment]
We have found the problem, which is the JWT generation error. Really sorry

**Comment by saghul** [comment]
No worries!
