### ISSUE TITLE
Android hold/resume and audio mute problem

### ISSUE THREAD

**Issue by RakeshPatil111** [jitsi/jitsi-meet#10695]
I am using jitsi meet sdk 3.0.0. I am facing problem for mic (mute/unmute) & hold/resume.
Sometimes if participants joins the meeting earlier that moderator, their audio is not working.
Also, during a meeting if person in meeting gets sim call & after the answering the call, their voice is still audible in meeting, expected he/she should be on hold in meeting or mic should turned off.

**Steps to reproduce**
1. Open app
2. Connect to meeting (only 2 people)
3. Join meeting
4. Call one of the person from mobile (regular sim call)
5. Answer call
6. After the meeting and sim call both are continued simultaneously, other people should able to see XYZ has put meeting on hold.
7. After disconnecting sim call, audio (mute/unmute) does not work. (Sometimes, not always)

**Expected :**
After answering call, he/she should be on hold, their mic should be mute in meeting & other people should also see appropriate status

**Mobile Version** : Android 11 (Oneplus) & Android 10 (Nokia)

I am not using JitsiMeetActivity, I am using jitsimeetview, JitsiMeetActivityDelegates, JitsiMeetActivityInterface, JitsiMeetViewListener & broadcast receiver.

Does anyone knows which events needs to be observed?

**Comment by saghul** [comment]
3.0.0 is incredibly old. Please update to the latest version (4.1.0 as of this writing) and try again.

**Comment by RakeshPatil111** [comment]
Oh, thanks for information. Will try & comment back.

**Comment by RakeshPatil111** [comment]
Checked with latest build, problem still exists.

**Comment by saghul** [comment]
Can you reproduce it with the sample apps, which use JitsiMeetActivity?

**Comment by RakeshPatil111** [comment]
Okay, will try and let you know

**Comment by RakeshPatil111** [comment]
Checked with sample app, it is reproducible

**Comment by saghul** [comment]
Did you have connection services enabled?

**Comment by RakeshPatil111** [comment]
Yes.

**Comment by saghul** [comment]
Can you try to set the feature flag to disable it? We stopped using it by default a while ago.

**Comment by riyas145** [comment]
How to update latest SDK?

**Comment by RakeshPatil111** [comment]
Go to official page, there u can find latest available version.
Just add it in your build gradle

**Comment by riyas145** [comment]
i'm using react-native and i'm new for android can u please share the any documents ?

**Comment by RakeshPatil111** [comment]
Follow the steps 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

Find a version here

https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

**Comment by saghul** [comment]
Let's not diverge here.

@RakeshPatil111 did disabling ConnectionService solve your problem?

**Comment by RakeshPatil111** [comment]
No, problem is still there.
Customising code now.

**Comment by saghul** [comment]
@tmoldovan8x8 Van you please if you can repro, when you get a chance?
