### ISSUE TITLE
Guest domain isn't working

### ISSUE THREAD

**Issue by Riddimshocker** [jitsi/jitsi-meet#10690]
### Description:

Can't bring up guest domain for unauthorized users joining the room

### Steps to reproduce:

Follow the steps from the manual below:
https://jitsi.github.io/handbook/docs/devops-guide/secure-domain

Create a room.

Try to join the room from another device.

See an authorization form.

### Expected behavior:

Joining the existing room without using any credentials.

### Actual behavior:

Authorization form showing up while joining the existing room.

### Server information:

- Jitsi Meet version: 2.0.6726-1
- Operating System: Ubuntu 20.04.3 LTS
- Prosody version: 0.11.4-1

### Client information:

- Browser / app version: any
- Operating System: any

### Additional information:
[jicofo.conf.txt](https://github.com/jitsi/jitsi-meet/files/7768850/jicofo.conf.txt)
[meet.example.org.cfg.lua.txt](https://github.com/jitsi/jitsi-meet/files/7768851/meet.example.org.cfg.lua.txt)
[meet.example.org-config.js.txt](https://github.com/jitsi/jitsi-meet/files/7768852/meet.example.org-config.js.txt)

**Comment by saghul** [comment]
The config looks ok. You should only get authentication for the first user who joins a room, but not for the rest. Isn't this what happens?

**Comment by Riddimshocker** [comment]
Every user trying to join a room gets asked for credentials

**Comment by 0xnor0** [comment]
I think there is one bracket too many, so that your VirtualHost is not read in correctly for the guests. do you get error logs in prosody?

**Comment by Riddimshocker** [comment]
It's not exact config file I used. After bug discovery I had to revert to anonymous auth. This extra bracket remains after inserting "modules_enabled" section, I tried it to make things working and, before uploading, decided to erase the section, cause it didn't help and forgot the bracket. Long story short - it's not the issue. There were no brackets originally. only those:
VirtualHost "guest.meet.example.org"
    authenticaton = "anonymous"
    c2s_require_encryption = false

**Comment by Riddimshocker** [comment]
I can provide the access to the machine, so you can see it for yourself

**Comment by steffenweb** [comment]
I had tried the same thing with secure Domain and it did not working at first place because the first step in the "Jicofo configuration" ( https://jitsi.github.io/handbook/docs/devops-guide/secure-domain#jicofo-configuration ) points to the wrong file on my Debian 11 machine.

The correct path is: /etc/jitsi/videobridge/sip-communicator.properties

**Comment by 0xnor0** [comment]
> I had tried the same thing with secure Domain and it did not working at first place because the first step in the "Jicofo configuration" ( https://jitsi.github.io/handbook/docs/devops-guide/secure-domain#jicofo-configuration ) points to the wrong file on my Debian 11 machine.
> 
> The correct path is: /etc/jitsi/videobridge/sip-communicator.properties
> 
> 
> 

Thats wrong, the Videobridge-config has nothing to do with secure Domain. The jicofo path is correct and it's working as described.

There must be another error in your config.

**Comment by zioalex** [comment]
Hi there,
I am facing the same problem.
Did you find a solution?
Thanks

**Comment by steffenweb** [comment]
Hello,
i could not solve the problem and don't need Jitsi anymore.

**Comment by zioalex** [comment]
Hi there, thanks for the info.
