### ISSUE TITLE
Android Jitsi Meet app can't turn volumn down

### ISSUE THREAD

**Issue by linsui** [jitsi/jitsi-meet#10691]
### Description:
The sound is so loud that I can't use it with earphone at all.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System: Android 11

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
