### ISSUE TITLE
Bug: Searching for users, close menu and reopen menu

### ISSUE THREAD

**Issue by fossdd** [jitsi/jitsi-meet#10700]
Hey, i just was on a meeting and search on the Speaker Stats for a user, then closed the modal. And if I reopen the stats, the search input box has reset but the list still shows only users I searched.

**Comment by saghul** [comment]
Where are you able to reproduce this? It should have been fixed by: https://github.com/jitsi/jitsi-meet/commit/40844afb60b2960940945b334c85a12d5e6e67ee
