### ISSUE TITLE
Add support for Android Desktop Mode

### ISSUE THREAD

**Issue by kreaninw** [jitsi/jitsi-meet#10701]
**Is your feature request related to a problem you are facing?**
Yes, its related to a problem I'm facing.

The desktop mode on Android devices was introduced since Android 10 as a developer option. However, most, if not all, Android 11 devices now make this mode available on differences names. This mode is called Productivity Mode by Lenovo.

![147378060-dad04e7e-b57d-4e3f-af1b-4af89e08e044](https://user-images.githubusercontent.com/1403194/147484290-31a34f81-e848-4676-9161-8e175ab35dca.jpeg)

My tablet has 11 inches display, so I prefer to use the app like I would on my laptop PC.

**Describe the solution you'd like**
I would like to use Jitsi with Android Desktop Mode features. For instance, an ability to maximized the app's window as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/147483729-59b641ca-5bbb-480c-b6f0-2b2696dc0b3b.mp4

Currently, I can't even make the app fullscreen in Android Desktop Mode. The biggest window size I can use in this mode is half-screen.

**Describe alternatives you've considered**
It's impossible to find an alternative.

**Comment by saghul** [comment]
Hum, this should have made it work automatically: https://github.com/jitsi/jitsi-meet/blob/6247d45b9e44945662d44729bdbd177b4bd02280/android/app/src/main/AndroidManifest.xml#L21
