### ISSUE TITLE
Mic is unmuted automatically when starting screen-share specific tab in chrome, but audio input device is not selected

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#10706]
### Description:

The microphone is going to unmuted state when starting sharing a specific tab in chrome. Also audio is not passed to other participants. By checking the audio settings overlay popup above the mute/unmute button, no audio input device is selected.

### Steps to reproduce:

1. User A creates and joins the room from chrome with the muted state.
2. Users B and C join the same room.
3. User A share specific chrome tab (Share audio checkbox is checked by default)
4. User A microphone goes to the unmuted state automatically. No audio input device is selected in audio settings.

### Expected behavior:

The microphone should not go to the unmuted state automatically when screen sharing a specific tab.

### Actual behavior:

The microphone goes to the unmuted state automatically when the screen shares a specific tab and other participants don't hear the presenter. 

### Server information:

- Jitsi Meet version: meet.jitsi.si
- Operating System: 

### Client information:

- Browser / app version: Google Chrome (96.0.4664.110)
- Operating System: Windows

### Additional information:

When going to the unmuted state automatically, the input microphone is not picked automatically, that might be the issue. But auto unmute state is a violation of privacy 😃. 

Temporary solution:-
Once started screen sharing, the mute state goes to unmuted automatically, then picks a microphone device from the audio settings.

**Comment by saghul** [comment]
Does the behavior change if the "share audio" checkbox is not marked?

**Comment by ashiqhassan95** [comment]
If "share audio" is unchecked, then there are no changes in the mute/unmute state, works fine.

**Comment by saghul** [comment]
Thanks for checking. I think we have some bugs around sharing audio there...

**Comment by ashiqhassan95** [comment]
@jallamsetty1 
The issue still exists.

**Comment by saghul** [comment]
@jallamsetty1 @andrei-gavrilescu  PTAL

**Comment by andrei-gavrilescu** [comment]
I'll check it out.

**Comment by andrei-gavrilescu** [comment]
Seems to be happening only if the user doesn't unmute his microphone at least once before sharing audio. Probably due to the audio track not being created yet.
Will log the issue and investigate asap.

**Comment by jallamsetty1** [comment]
I thought I fixed the legacy mode but looks like I didn't. I had noticed this issue when adding support for the multi-stream mode and made sure we don't run into the same issue there, I will open a PR for this one.
