### ISSUE TITLE
Feat: Allow a user to add his own custom background in addition of the custom virtualBackgrounds

### ISSUE THREAD

**Issue by Warziik** [jitsi/jitsi-meet#10712]
Hello,
In the company where i work (Eyeneed), we use jitsi for medical purposes since a long time now and we recently faced a problem. We've set **our custom virtual backgrounds** to replace the default ones but we also need to allow the user **to add his own custom background**. The problem is that right now, if we decide to set the company custom virtual backgrounds, the button allowing the user to add his own is not shown anymore.

We would like the feature to be more flexible so that the user can still add his own custom backgrounds if the config property **disableAddingBackgroundImages** is set to false.

*/react/features/virtual-background/components/VirtualBackgroundDialog.js*
```
_showUploadButton: !(hasBrandingImages || state['features/base/config'].disableAddingBackgroundImages),
```

Thank you for reading and happy new year to all of you!

**Comment by pandel** [comment]
+1 we'd like to have this feature, too!

**Comment by 0xnor0** [comment]
If you overwrite the original background images, participants could upload own backgrounds.

**Comment by pandel** [comment]
> If you overwrite the original background images, participants could upload own backgrounds.

I think, that is not the best way to go. As we already have the branding feature (see https://github.com/jitsi/jitsi-meet/blob/d91e7c3d31d5fd1fa75eb000c98a58781f1d909c/config.js#L974), it would be nice to have a welcomeBackground variable, so that it can be part of the main branding functionality.

**Comment by 0xnor0** [comment]
> > If you overwrite the original background images, participants could upload own backgrounds.
> 
> I think, that is not the best way to go. As we already have the branding feature (see https://github.com/jitsi/jitsi-meet/blob/d91e7c3d31d5fd1fa75eb000c98a58781f1d909c/config.js#L974), it would be nice to have a welcomeBackground variable, so that it can be part of the main branding functionality.

How i activate the branding feature? Is there a Guide? I saw some variables like isBrand in another file on GitHub. 

Thank you!

**Comment by Warziik** [comment]
> > > If you overwrite the original background images, participants could upload own backgrounds.
> > 
> > 
> > I think, that is not the best way to go. As we already have the branding feature (see https://github.com/jitsi/jitsi-meet/blob/d91e7c3d31d5fd1fa75eb000c98a58781f1d909c/config.js#L974
> > ), it would be nice to have a welcomeBackground variable, so that it can be part of the main branding functionality.
> 
> How i activate the branding feature? Is there a Guide? I saw some variables like isBrand in another file on GitHub.
> 
> Thank you!

Hey, check for the **dynamicBrandingUrl** property in the config.js file. It allows you to create a JSON file in order to overwrite some related branding properties such as virtualBakcgrounds.

**Comment by Ronald-Agorsah** [comment]
Dear Community,

We would love to see an update here..
We are struggling as well to find a good tutorial how we could change or customize the Background Logo of the Welcome Page in a Docker install.

Best Regards 
Alpenhost
www.alpenhost.at
