### ISSUE TITLE
Consider making `enableThumbnailReordering` separately configurable for the filmstrip and tile view

### ISSUE THREAD

**Issue by jbg** [jitsi/jitsi-meet#10714]
When `enableThumbnailReordering` is `true` (the default), thumbnails are reordered according to the most recent active speakers, _both in the filmstrip and in the tile view_.

In the filmstrip, or in a large meeting, this is really useful behaviour, since otherwise the recent speakers in the call could be scrolled off-screen.

However, in tile view in a relatively small meeting (where all tiles fit on screen), the constant re-ordering of tiles is really disconcerting, especially in a lively discussion where the active speaker is changing a lot. People are constantly moving around the screen and it makes it difficult to carry on a conversation. This is particularly noticeable in a three-person room where each person is speaking about the same amount. The second and third positions in the tile view constantly swap places. The first time I saw this happening I actually thought it was a bug!

Could it make sense to enable it in tile view only if the tiles don't all fit on-screen without scrolling? Or provide a configurable minimum number of participants before re-ordering is enabled in tile view?

Or maybe just a separate `enableThumbnailReordering` toggle for filmstrip and tile view — deployments that expect large meetings could turn it on for tile view, while deployments whose meetings are mostly small enough that all tiles fit on screen could turn it off.

**Comment by saghul** [comment]
I agree with this :-)

**Comment by jbg** [comment]
I can work up a PR if we can get agreement on which approach would be better:

1. Only enable thumbnail reordering in tile view if there are more tiles than fit on screen
2. Provide a configurable minimum number of participants before thumbnail reordering is enabled in tile view
3. Separate `enableThumbnailReordering` into separate toggles for tile view and filmstrip

I think (1) could have some surprising edge cases with window resizing, so I think maybe 2 is the best option.

**Comment by saghul** [comment]
I need to check with product, since this has wider implications such as JaaS.

**Comment by damencho** [comment]
Covered in https://github.com/jitsi/jitsi-meet/pull/11140 and https://github.com/jitsi/jitsi-meet/pull/11214

**Comment by optimuswhite** [comment]
Hello, I have a problem. There is no reordering between active/inactive speakers on the movie strip. That is, if a speaker is at the bottom of the movie strip and I can only see him when I scroll, even when the speaker is active, his position does not change and I have to constantly scroll down/up to see who is speaking during the meeting. Also, I did not see the enableThumbnailReordering setting you mentioned in the config file. How can I fix this situation?
