### ISSUE TITLE
Join conference without camera not possible anymore

### ISSUE THREAD

**Issue by sat-hub** [jitsi/jitsi-meet#10717]
### Description:

When trying to join a room, I immediately get kicked out when I have no camera connected to my computer.

### Steps to reproduce:

1. Use device with microphone but without camera.
2. Join any room.

### Expected behavior:

In releases before Dec. 2021, joining conferences with a audio-only hardware setup (PC, Headset, no webcam) was supported without any issues. After I installed the latest December release, this is not possible anymore.

### Actual behavior:

When I try to enter a room, I immediately get kicked out again. I see an error message like "Error when connecting to camera" or so for a fraction of a second before the main screen is viewed again.

### Server information:

- Jitsi Meet version: 2.0.6726
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Firefox, Chrome
- Operating System: Ubuntu 20.04

**Comment by saghul** [comment]
Do you have the prejoin page enabled?

Please share your JS console logs?

**Comment by sat-hub** [comment]
Thank you for your quick answer.

I reverted back to the previous version after creating this ticket. When I now tried to reproduce the issue again, the problem has vanished... It may have been a cache issue somewhere.
Prejoin page was not enabled.
