### ISSUE TITLE
API for bots to join/host meetings, access audio/video/chat, send audio/video/chat?

### ISSUE THREAD

**Issue by Joshuao95** [jitsi/jitsi-meet#10715]
Hi,
I was wondering if there is any existent API, or reccomending system for connecting to Jitsi meetings programatically with a bot, in order to record or respond to user messages?

**Describe the solution you'd like**
Discord has a fairly comprehensive API for bots to connect to, I suppose that's the ideal.

**Comment by jbg** [comment]
This would be better asked on community.jitsi.org.

If you don't mind your bot being Web-based, you can use lib-jitsi-meet. Jitsi being WebRTC, there are no mature non-Web ways to send audio and video yet, but you could have a look at some of the in-development ways - [Jitas](https://github.com/jitsi-contrib/jitas) and [gst-meet](https://github.com/avstack/gst-meet).
