### ISSUE TITLE
Feature Request: Allow attendees το provide real-time feedback

### ISSUE THREAD

**Issue by n0toose** [jitsi/jitsi-meet#10710]
**Is your feature request related to a problem you are facing?**
It's very hard to convey whether you are understanding a person in video calls when you're speaking in front of an audience, and it's also hard to interject and say that you do not understand something during a lecture. Video teleconferencing solutions still have a long way to go with making up for the lack of in-person body language, and this is still affecting many people, like myself, close to two years in this pandemic.

I'm suggesting something like an "understand-o-meter", that allows people to click on a button in real time and and convey how well they are following a conversation/lecture, or whether they believe that the moderation/direction of a conversation is productive.

**Describe the solution you'd like**
I'd like to bring up a minigame from one of [Jackbox Games'](https://jackboxgames.com), [Talking Points](https://www.jackboxgames.com/talking-points/), where you get to hold a presentation and then get rated in real-time by other people that assign you a score by pressing on an upvote or a downvote button fast, and the speaker has a score assigned to them according to how well the reception was. Although these games used to be played during actual parties, they also work perfectly well during calls on Discord or other places, from my experience.

I started thinking about it recently, and I think that it would be great if this could be somehow adapted in a way that isn't as fast as in that game, or as slow-paced and disposable as a reaction.

**Describe alternatives you've considered**
What I previously suggested, but with a real-time poll option that greatly reduces the pressure, maybe on regular intervals, could work? I don't know, I'm just throwing ideas here as a user.

**Comment by n0toose** [comment]
Hi, I get that you are doing this for the sake of remaining productive, but I would just like to state that using bots to just automatically dismiss feedback that a person spent time writing without any sort of acknowledgement or a "We don't think this is a good idea and won't do this, sorry. [closes issue]" comes across as extremely hostile to the person that spent some time out of their life that they are never going to get back just to write and edit the issue precisely according to the standards declared in the template.

**Comment by saghul** [comment]
Sorry, we simply get more issues than we can handle and the bot helps us gauge interest and remind us of issues that haven't seen activity.

Not everyone likes it, but as a maintainer with limited resources it's a very useful tool.

Back on topic. We are not currently considering incorporating such feature into Jitsi Meet at this time.
