### ISSUE TITLE
CONFERENCE_TERMINATED fired while moving the users from main room to breakout room

### ISSUE THREAD

**Issue by idrive-pankaj** [jitsi/jitsi-meet#10721]
### Description:

We are using your jisti code base with some custom UI modification and we are creating an Android and iOS SDK from this codebase.
Everything is working fine except when we move any jisti user who is connected via mobile to the breakout room.
When we move any user we are receiving a CONFERENCE_TERMINATED event and it's calling the respected delegate method in the native code where we are removing jitsi view and doing some cleaning steps.
This method we are using previously when the user is leaving the room or when the admin has kicked out any user. The problem is we are unable to differentiate this event when it's called for the breakout room and when it's called based on the user's action.

Could you please let me know how we can differentiate this event when it's called for the breakout room?

### Steps to reproduce:

1. Start a meeting and join with some users
2. create a breakout room and move any user to that breakout room
3. CONFERENCE_TERMINATED event and its respected delegate method (JitsiMeetViewDelegate) will be called in the native code
4. again if you leave that breakout room same method will be called
### Expected behavior:

We need something so we can differentiate this delegate method call based on breakout room and user action.
### Actual behavior:
Bellow delegate method is getting called with the URL data only.
<img width="854" alt="Screenshot 2022-01-05 at 11 20 37 AM" src="https://user-images.githubusercontent.com/79213346/148167121-2acaa191-6140-4972-b8ed-34592f5f3496.png">

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

Please help me to understand this behavior if I am making any mistakes.

Thanks & Regards

**Comment by saghul** [comment]
That is by design.

We mentioned it in the release notes: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#breaking-changes but I see we failed to update the docs, sorry about that!

This is the new delegate method you'll want to listen to, in order to know when to dismiss the SDK view: https://github.com/jitsi/jitsi-meet/blob/6b260c27a5f42fd0b5a90cd48c8d3299f051930e/ios/sdk/src/JitsiMeetViewDelegate.h#L114-L117

**Comment by idrive-pankaj** [comment]
Thanks, @saghul, This is very helpful.
