### ISSUE TITLE
Android screen share not working second time when we have 2 participants in meeting 

### ISSUE THREAD

**Issue by Vamsi-Rayapati** [jitsi/jitsi-meet#10734]
Steps to reproduce 
1) create a meeting and make sure to have 2 participants 
(Moderator +other)
2) share screen
3) stop screen share
4) share again .... Not working

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Is this a browser or mobile app? Which versions? Do you reproduce it on meet.jit.si?

**Comment by Vamsi-Rayapati** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.
> 
> Is this a browser or mobile app? Which versions? Do you reproduce it on meet.jit.si?

issue is occuring in current  jitsii meet app in playstore
