### ISSUE TITLE
dear sir ,please give us a apk download link  without google play and f-droid.

### ISSUE THREAD

**Issue by introspection3** [jitsi/jitsi-meet#10735]
### Description:

dear sir ,please give us a apk download link  without google play and f-droid.because we can't visit them

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Sorry, we cannot maintain more releases. You can either use some kind of apk mirror, or download it directly from the F-Droid site, this is the latest version for example: https://f-droid.org/repo/org.jitsi.meet_216000.apk
