### ISSUE TITLE
Cocoa Pods not updating to the latest framework

### ISSUE THREAD

**Issue by vineethnkforios** [jitsi/jitsi-meet#10747]
OS: iOS

I have updated the framework to  JitsiMeetSDK (4.0.0). But I can't see the following delegates

 (void)participantJoined:(NSDictionary *)data;
- (void)participantLeft:(NSDictionary *)data;
- (void)audioMutedChanged:(NSDictionary *)data;
- (void)videoMutedChanged:(NSDictionary *)data;
- (void)readyToClose:(NSDictionary *)data;

Pod file as follows

platform :ios, '11.0'

workspace 'JitsiMeetSDKTest.xcworkspace'

target 'JitsiMeetSDKTest' do
  project 'JitsiMeetSDKTest.xcodeproj'

  pod 'JitsiMeetSDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

- Jitsi Meet version:  JitsiMeetSDK (4.0.0)
- Operating System: IOS

- Browser / app version:
- Operating System:

![Screen Shot 2022-01-10 at 2 21 19 AM](https://user-images.githubusercontent.com/78809766/148732205-dc75706c-d383-46a1-b2c9-6e3a3aed66cd.png)

**Comment by saghul** [comment]
Check the JitsiMeetViewDelegate file in the SDK. They are there.
