### ISSUE TITLE
getRoomLocker of undefined

### ISSUE THREAD

**Issue by khanhmas** [jitsi/jitsi-meet#1074]
Hello everyone,

I am using ejabberd as XMPP server. I followed the manual-install to setup the jitsi-meet (except the XMPP server part), however, i encountered the getRoomLocker of undefined error. But, above this error, it is said that "Focus jid set to : undefined". I have a few questions : 

1) Does "focus undefined" result in "getRoomLocker" ?
2) What exactly is the "focus" inside jitsi-meet ? Does it relate to jicofo ? Is that mandatory for the LDAP authentification (i am able to authenticate via my LDAP server in the login modal log of jitsi-meet) ? In Ejabberd, i couldn't find any related information about Focus XMPP Component.

Any helps would be appreciated. Thanks you.

![jitsi-bug](https://cloud.githubusercontent.com/assets/8402110/19759017/42a323c4-9c2b-11e6-9f95-442ac7ca1a78.jpg)

**Comment by damencho** [comment]
Please use the mailinglist for problems or questions before opening issues. 
The focus it the jicofo user. It is the controlling point of everything, without it, there is no conference.
