### ISSUE TITLE
After End the meeting Camera is not closing in Android/iOS. Can we close the camera in Hangup button  ?

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#10740]
We are getting issue that after End the meeting Camera is not closing in Android/iOS. 
We used startWithVideoMuted but  this will open the video when meeting started but we need to close the camera after end meeting. Can we close the camera in Hangup button ?

**Comment by saghul** [comment]
That should already be happening. What SDK version are you using? Can you please share the logs right after you hangup?

**Comment by mustahsin64** [comment]
> We are getting issue that after End the meeting Camera is not closing in Android/iOS. We used startWithVideoMuted but this will open the video when meeting started but we need to close the camera after end meeting. Can we close the camera in Hangup button ?

hi, in which jitsi version are you getting this ?

**Comment by saghul** [comment]
I am not able to reproduce this in SDK 4.1.0.
