### ISSUE TITLE
Can't change iOS header and footer color

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#10744]
Hi,

I just tried updating my fork of the iOS app and I can't seem to be able to change the colors of the header and footer in the iOS app.

I've changed the jitsi default blue from [here](https://github.com/jitsi/jitsi-meet/blob/d91e7c3d31d5fd1fa75eb000c98a58781f1d909c/react/features/base/styles/components/styles/ColorPalette.js#L22) but it seems to ignore my change completely and still renders the jitsi blue in the Xcode simulator.

I've searched around to see what's changed re colors in iOS since about 1 year ago but I can't figure it out.

Is the #17A0DB blue hardcoded somewhere for iOS?

Thanks

**Comment by saghul** [comment]
We are changing the UI internals so it's no longer there. @Calinteodor can you please mention how do change that here?

**Comment by pdarcos** [comment]
Thanks @saghul 
You saved me lots of hours of searching in vain.

Looking forward to @Calinteodor 's indications of where to change it now.

**Comment by AliKarpuzoglu** [comment]
I changed the colors by changing primary01-11

in [react/features/base/ui/Tokens.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/ui/Tokens.js)

**Comment by pdarcos** [comment]
Thanks @AliKarpuzoglu 
That was it.
