### ISSUE TITLE
Virtual Background covers the person on MAC

### ISSUE THREAD

**Issue by c-atienza** [jitsi/jitsi-meet#10757]
After Updating to latest, our users on MAC can't use virtual background without the person being covered, our video codec is VP8, VP9 and H264.

### Description:
 Here are the server.com-config.js file changes
    constraints: {
         video: {
             aspectRatio: 16 / 9,
             frameRate: {
                 max: 15,
             },
             height: {
                 ideal: 480,
                 max: 720,
                 min: 144
             }
         }
     },
    disableSimulcast: true,
    enableLayerSuspension: false,
    startWithVideoMuted: true,
    disableH264: true,
    desktopSharingFrameRate: {
         min: 10,
         max: 15
     },

Preffered codec selected is VP9
This changes was provided to stop camera from turning off

### Steps to reproduce:

1. Turn on Virtual Background select any except none
2. No other steps necessary

### Expected behavior:
The person shouldn't be covered by Virtual Background
![image](https://user-images.githubusercontent.com/86337342/148893136-5e4d7458-4f95-4ad2-b1d8-d3d90cedabc8.png)

### Actual behavior:
The Person is being covered by Virtual Background
![image](https://user-images.githubusercontent.com/86337342/148893157-605bbcc0-17f7-4b83-94de-a48da4010994.png)

<--will provide screenshot soon-->
### Server information:

- Jitsi Meet version: 2.0.6726
- Operating System: Ubuntu 18

### Client information:

- Browser / app version: Google Chrome
- Operating System: Apple / Mac

**Comment by saghul** [comment]
That's odd, do you observe the same on meet.jit.si?

**Comment by c-atienza** [comment]
Hello, we don't find the same issue in meet.jit.si, may I know possible code that could affect this? could it be in host.url-config.js settings or jitsi-videobridge2?

**Comment by saghul** [comment]
> Hello, we don't find the same issue in meet.jit.si, may I know possible code that could affect this? could it be in host.url-config.js settings or jitsi-videobridge2?

Can you test beta.meet.jit.si ? We have changed the model last week, but I can't imagine why it would not work on macOS. Also, anything in your JS console.

**Comment by c-atienza** [comment]
no error or warning  related to video in JS console, i can't test it in mac atm, I'll get back to it tomorrow.
other than js console and /var/log/jitsi is there any other places I can check for information regarding this issue?

**Comment by saghul** [comment]
This should be only on the client side, so the browser JS console.

**Comment by c-atienza** [comment]
I see, I also want to mention that the preview is working 100% fine, only after clicking apply is where the problem happens

**Comment by c-atienza** [comment]
Hello, here is a console that might be related to this issue.

![IMG_20220112_164804](https://user-images.githubusercontent.com/86337342/149094276-778796ae-6ecc-40cf-8a02-01703f1c8631.png)

**Comment by saghul** [comment]
It most certainly is. The communication with the JVB is not working.

**Comment by c-atienza** [comment]
I see, I'll check it out. Hoping reinstallation would fix the problem.
