### ISSUE TITLE
Focus keyboard shortcuts change during video sharing

### ISSUE THREAD

**Issue by rfdparker** [jitsi/jitsi-meet#10756]
### Description:

After upgrading to the current (as of 2022-01-10) versions of the Jitsi Meet packages, we have found a change in the behaviour of the "Focus on another person's video" keyboard shortcuts when sharing a video. When a video is shared, the keyboard shortcut "1" focuses on the shared video and this increments by 1 the keyboard shortcut to focus on another person's video/camera.

The previous behaviour was that keyboard shortcuts 1-9 did not change during the sharing of a video.

The issue is particularly problematic for us as since the March 2020 lockdown began, we have been gratefully using Jitsi Meet as platform for our Virtual Church. We use Jitsi with Jibri to stream our Church services to YouTube. We use the 'Everyone follows me' functionality to switch focus between the contributors, shared videos (e.g. hymns) and shared screens (e.g. prayers, presentations, etc). We often switch to the next contributor before stopping a shared video to provide better continuity and to avoid the tile view being displayed. Using the 'Everyone follows me' functionality in this way has been the 'killer' feature of Jitsi Meet over the alternatives.

Would it be possible to use different keyboard shortcut, instead of "1", to focus on a shared video? Perhaps this could be a totally different key or replace "9" while the video is being shared.

### Steps to reproduce:

1. A meeting has three participants - Alice, Bob and Charlie.
2. Prior to any video being shared, Charlie is able to focus on Alice and Bob using the keyboard shortcuts "1" and "2" respectively.
3. A participant shares a video in the meeting.
4. During the sharing of the video, Charlie presses "2" to focus on Bob, but now finds this focuses on Alice, that "3" now focuses on Bob and that "1" now (re)focuses on the shared video.
5. After the shared video is stopped, Charlie observes the keyboard shortcuts for focusing on Alice and Bob return to their original assignments of "1" and "2" respectively.

### Expected behaviour:

The keyboard shortcuts (1-9) to focus on another person's video do not change during the sharing of a video. Ideally a totally different key (i.e. not within 1-9) would be the keyboard shortcut to focus on a shared video, however keyboard shortcut "9" focusing on a shared video would be much less problematic than keyboard shortcut "1" as this would only change the behaviour of one keyboard shortcut.

### Actual behaviour:

During the sharing of a video, keyboard shortcut "1" focuses on the the video and the participants which could previously be focused with keyboard shortcuts 1-8 have to be focused using keyboard shortcuts 2-9 (i.e. they are incremented by 1). After the shared video is stopped, the keyboard shortcuts return to their original assignments.

### Server information:

- Jitsi Meet version: the Jitsi Meet packages for Debian we were using before the issue and now are:

```
PACKAGE                 OLD                     NEW
jicofo                  1.0.636-1               1.0-832-1
jitsi-meet              2.0.5076-1              2.0.6726-1
jitsi-meet-prosody      1.0.4428-1              1.0.5675-1
jitsi-meet-web          1.0.4428-1              1.0.5675-1
jitsi-meet-web-config   1.0.4428-1              1.0.5675-1
jitsi-videobridge2      2.1-351-g04bfaac1c-1    2.1-595-g3637fda4-1
prosody                 0.11.2-1                0.11.2-1+deb10u2
```

- Operating System: Debian 10

### Client information:

- Chromium 90.0.4430.212 on Debian 10 (`amd64`)
- Firefox 78.15.0esr on Debian 10 (`amd64`)
- Chrome 97.0.4692.71 on Ubuntu 20.04 LTS (`amd64`)

### Additional information:

We'd like to thank the Jitsi developers and community for all their hard work. Jitsi, and Jibri for streaming to YouTube, have ensured our community has been able to have Church services and meetings during this pandemic. Thank you.

**Comment by saghul** [comment]
Thanks for the kind words! We're happy Jitsi was of help.

I see that this change was part of a larger effort to reorganize thumbnails in the UI: https://github.com/jitsi/jitsi-meet/pull/9762

The way it works now respects the order you see in the user interface. While it doesn't work as before, it's consistent with what the user sees, so there is no ambiguity.

**Comment by rfdparker** [comment]
Hi @saghul,

Thank you very much for the prompt response.

We're pleased to report the setting the config parameter referenced in the pull request, `enableThumbnailReordering`, to `false` restores the previous keyboard shortcut behaviour which we are using in our installation.

For the benefit of anyone else needing the original behaviour, in `/etc/jitsi/meet/{{DOMAIN}}-config.js` we un-commented and set to `false` the parameter `enableThumbnailReordering`; in our this version of Jitsi Meet, this was nested within the `testing` section/object.

As this has now fixed our problem, we are closing this issue.

Thanks again for your assistance and to wider Jitsi community for a great solution.
