### ISSUE TITLE
Facing issue while archiving the build on Xcode

### ISSUE THREAD

**Issue by Sbhonagiri** [jitsi/jitsi-meet#10761]
Xcode version: 13.1
MacOS Version: 12.01
React native webrtc version: 1.94.1

![Screenshot 2022-01-11 at 4 01 22 PM](https://user-images.githubusercontent.com/17709729/148926529-609b109f-738e-44fc-a768-6e0a4507328f.png)

@saghul @jallamsetty1 Facing issue while arching the build could you please check and advise the solution

**Comment by saghul** [comment]
You need to run the `node_modules/react-native-webrtc/tools/downloadBitcode.sh` script before building.
