### ISSUE TITLE
Chat button is centrally aligned in the overflow menu

### ISSUE THREAD

**Issue by weltfahr** [jitsi/jitsi-meet#10775]
### Description:

The chat button is rendered centrally aligned in the overflow menu.

### Steps to reproduce:

1. Join a meeting at meet.jit.si in the browser.
2. Open the participants pane to reduce the available toolbar width
3. Shrink the width further to have the chat button move to the overflow menu

### Expected behavior:

The chat button should be displayed in the same way as the other buttons, filling the width.

### Actual behavior:

The chat button is centered unlike all other buttons.

**Comment by saghul** [comment]
Can you please attach a screenshot?

**Comment by weltfahr** [comment]
> Can you please attach a screenshot?

I thought of that initially. I might be blind, but I cannot find an option to attach anything (except if I would upload the image to somewhere else and link it here, which is crazy).

**Comment by saghul** [comment]
What's crazy about it? It will upload the image to GitHub itself.

**Comment by weltfahr** [comment]
> What's crazy about it? It will upload the image to GitHub itself.

Sorry. I was really blind. Now I noticed that this works by just drag&drop or pasting. Far too easy for me :wink:

So here we go:
![Screenshot 2022-01-12 at 08 46 23](https://user-images.githubusercontent.com/96427054/149129427-09d60cb6-c401-4880-adda-f5df7951b9ba.png)
:

**Comment by gpatel-fr** [comment]
I never succeeded in reproducing it - the whole screen collapsed to only show the participant pane before the chat button went to the overflow section; however I did succeed with the hand button, with an even more spectacular result:

![image](https://user-images.githubusercontent.com/44170243/149229744-5519fbdc-6654-45d9-a9c6-1dac036ec324.png)

both items (chat and hand) have custom rendering.
