### ISSUE TITLE
'avatarUrl' command

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#10772]
### Description:

In Chrome 97 Mac, this script with 'avatarUrl' command fails most of the time
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Test</title>
    </head>
    <body>
        <script src="https://meet.jit.si/external_api.js"></script>
        <script>
         const domain = 'meet.jit.si';
         const options = {
             roomName: 'test1234567890987654321test',
             width: 700,
             height: 700,
             parentNode: undefined,
             userInfo: {},
             configOverwrite: {},
             interfaceConfigOverwrite: {}
         }
         const api = new JitsiMeetExternalAPI(domain, options);
         api.executeCommand('avatarUrl', 'https://avatars0.githubusercontent.com/u/3671647');
     </script>
    </body>
</html>
```

### Steps to reproduce:

Open https://joseluisandrade.com/test-jitsi.html
Refresh many times

### Expected behavior:

Open Conference

### Actual behavior:
<img width="1298" alt="imagem2" src="https://user-images.githubusercontent.com/32515675/149000510-749ab2f0-55b0-45b5-95e7-011e477695e0.png">

### Server information:

- Jitsi Meet version: meet.jit.si and beta.meet.jit.si
- Operating System:

### Client information:

- Browser / app version: Chrome 97 Mac (Firefox Mac e Safari all OK)
- Operating System: macOS 12.1

### Additional information:

<img width="1298" alt="imagem" src="https://user-images.githubusercontent.com/32515675/149001007-1f0a157d-54f6-4ee5-9ddb-8b80d6edac2a.png">

**Comment by damencho** [comment]
I cannot reproduce it locally. 

What about if you change it to:
```
            api.addListener('videoConferenceJoined', () => {
                       api.executeCommand('avatarUrl', 'https://avatars0.githubusercontent.com/u/3671647');
                });
```

**Comment by jluisfa** [comment]
With this change it works fine on Chrome Mac.
