### ISSUE TITLE
Some files in lang/*.json are not correct according to "jq"

### ISSUE THREAD

**Issue by sanvila** [jitsi/jitsi-meet#10787]
Hi. Today I tried to apply `jq -S` to all json files in `lang/*`. It almost worked. This is what failed:

* In line 46 of `lang/languages-ar.json` there is an extra comma. `jq` complains in this way:

`parse error: Expected another key-value pair at line 47, column 1`

Fix: Drop the extra comma which should not be there.

* Then there is a problem in `lang/main-sq.json`

`parse error: Invalid escape at line 282, column 123`

This is because of a line saying `\“Lejoje\”`. The problem is that those quotes are not the usual ASCII double quotes but some sort of UTF-8 quotes which do not need to be escaped.

Fix: Either use ASCII double quotes or remove the escapes.

While we are at it, it would be nice if json files were automatically checked for correctness at every commit, but I guess this is outside the scope for this bug report.

Thanks.

**Comment by saghul** [comment]
Good catch! Yeah it would be nice to have it fixed, are you up for writing a PR?



> While we are at it, it would be nice if json files were automatically checked for correctness at every commit, but I guess this is outside the scope for this bug report.

Not at all, it's very much in scope. Adding an extra step which validates those files here https://github.com/jitsi/jitsi-meet/blob/master/.github/workflows/ci.yml would be fantastic.

**Comment by sanvila** [comment]
I see there is already a "git diff" in the above setup, which I guess it's there to fail deliberately if anything changed in the previous steps. If this is really the case, then a script like this could be added to those previous steps:

```
#!/bin/sh
set -e
find lang -name "*.json" | while read file; do
  echo "Standardizing ${file}"
  t=$(mktemp)
  jq -S "." ${file} > ${t}
  mv ${t} ${file}
done
```
The only caveat is that once this is working, "not changing when applying jq -S" becomes a requirement for new contributions.

[ Note: I'm not in the business of doing PRs because I'm asked for my scanned signature, which I feel uncomfortable with. Please consider everything I wrote as public domain ].

**Comment by saghul** [comment]
> The only caveat is that once this is working, "not changing when applying jq -S" becomes a requirement for new contributions.

Based on what you observed I'd say it's a good thing.



> [ Note: I'm not in the business of doing PRs because I'm asked for my scanned signature, which I feel uncomfortable with. Please consider everything I wrote as public domain ].

Fair enough, thank you nevertheless!

**Comment by sanvila** [comment]
Please do so :-) It's a one-line change in a file and another one-line change in another file. After that it will be possible to "jq -S" everything.

**Comment by csett86** [comment]
I tested the jq -S, and the diff is quite substantial: https://github.com/jitsi/jitsi-meet/pull/10801

Not sure whether this is worth it now, just ensuring that its valid json would be enough for me: https://github.com/jitsi/jitsi-meet/pull/10800

**Comment by saghul** [comment]
Sorted keys can help eyeball translation gaps, I wouldn't oppose.
