### ISSUE TITLE
No volumen level option on iOS

### ISSUE THREAD

**Issue by ucicarlos** [jitsi/jitsi-meet#10785]
On any browser running on iOS devices the volumen level for each participant is not working. This is not only happening at UI level, the volumen down/up at code level isn’t working either.

I came across this issue by implementing a translation service and is working perfect for non iOS devices.

**Comment by quidlab** [comment]
Same here , I am also want to implement simultaneous translation. It works well on all devices except Iphone and Ipads.
 `api.executeCommand('setParticipantVolume',
    participantID: string,
    volume: number // number between 0 and 1
);`
has no effect on Iphone and Ipad ( safari & chrome).

**Comment by saghul** [comment]
This has been implemented already in the last version.

**Comment by rik-smit** [comment]
I see this issue is closed but I still have this issue with the latest version. Also when using the default Meet.jit.si the volume slider is missing on iOS so it looks like that feature just doesn't work there. Any news on this? Do you also still have this issue @ucicarlos @quidlab ?

**Comment by quidlab** [comment]
I am not sure if this has been implemented or not, to best of knowledge ios did not allow to control volume by script. Hence i used another approach. my requirement was dual language where user could choose live or translation which i achieved by using vanila javascript. however this will work only if you have own jitsi server.

**Comment by rik-smit** [comment]
@quidlab Yes, I am also using it for multilingual support and it works well on all other devices so it's a shame iOS doesn't support it. We have our own hosted Jitsi server so your fix might be useful for us as well. Can you maybe point me to the changes you have made? Is it in your quidlab-jitsi-meet repo? Thanks!

**Comment by quidlab** [comment]
you can check here, if any issues let me know
https://github.com/quidlab/jitiinterpreter/blob/main/README.md
