### ISSUE TITLE
the video not work but permissions camera and microphone are OK

### ISSUE THREAD

**Issue by rem29480** [jitsi/jitsi-meet#1078]
Hello everyone,
Excuse me for my english.
I installed Jitsi meet with an SSL certificate class 1.
The screen is OK at Home. When I create room is going well. 
Permissions for the camera and microphone are OK.
But nothing happens. I don't see me. the video isn't working. My screen is blue.  Have you got a solution ?
Thank you for your help.

you can see and test here : https://www.instants.live/

**Comment by damencho** [comment]
Please use the mailinglist for questions or problems before opening issues.

It seems your config is not working with www. Try accessing your domain without www. Also maybe some port forwarding or something is not working, if your jvb is behind nat.

**Comment by rem29480** [comment]
Thank you
What are the  files configuration i must change?
