### ISSUE TITLE
Seamless switch to mobile from desktop

### ISSUE THREAD

**Issue by laem** [jitsi/jitsi-meet#10798]
**Is your feature request related to a problem you are facing?**

I often use Jitsi on my computer in the browser. But often, meetings take more than 30 minutes, and it becomes recommended for our health to move, walk, anything else than staying seated too long. 

So I'd like to switch to the mobile Jitsi (on my Android phone), but doing so raises the eybrows of my colleagues ("oh someone connecting, ah no ok it's a connexion problem"), so can't be done systematically. You also have to kick yourself, and chose the right self...

Then I know bluetooth headphones exist, but most of us on earth don't have or don't want to buy new headphones. 

**Describe the solution you'd like**

A feature to seamlessly switch from the desktop version to the mobile version and rewind. 
It could be as simple as generating a link from the menu on one device, sending the link to the other device, opening it. 

**Describe alternatives you've considered**

Use a bluetooth headset, but they are quite limited (range from desktop, audio quality), and require new furniture.

**Comment by jbg** [comment]
> A feature to seamlessly switch from the desktop version to the mobile version and rewind.

What do you mean by "rewind"?

> It could be as simple as generating a link from the menu on one device, sending the link to the other device, opening it.

An example design for this would be:

 * "Old" participant generates a token and sends a presence containing the hash of that token, saying "I can be replaced by the participant who presents a token which hashes to this value"
 * "Old" participant gives "new" participant (the mobile device in your scenario) a link which contains that token
 * Upon "new" participant joining by following that link, they signal the token in their presence, which causes all participants in the room to replace the "old" participant with the "new" participant, causes the "old" participant to leave the call, and suppresses the visible join/leave events.

You'd also need to handle the various edge cases: old participant leaves before new one joins, new one never joins, etc.

**Comment by laem** [comment]
> What do you mean by "rewind"?

Say you start a conference on desktop. After 15 minutes of talks, you decide to switch to mobile to walk around. But after 10 minutes, someone starts to share his screen, with details not easily readable on your mobile's screen. So you switch back to desktop, using the same feature, but from mobile to desktop.
