### ISSUE TITLE
I am adding @react-native-picker/picker to Jitsi Meet project But getting issue when building the app in Xcode

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#10795]
I am adding @react-native-picker/picker to Jitsi Meet project But getting issue when building the app in Xcode

My Podfile :- 

`platform :ios, '12.0'
workspace 'jitsi-meet'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
install! 'cocoapods', :deterministic_uuids => false

target 'JitsiMeet' do
  project 'app/app.xcodeproj'

  pod 'Firebase/Analytics', '~> 6.33.0'
  pod 'Firebase/Crashlytics', '~> 6.33.0'
  pod 'Firebase/DynamicLinks', '~> 6.33.0'
end

target 'JitsiMeetSDK' do
  project 'sdk/sdk.xcodeproj'
  pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector/'
  pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec/'
  pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired/'
  pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety/'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon', :subspecs => [
    'turbomodule'
  ]
  pod 'React-Core', :path => '../node_modules/react-native/', :subspecs => [
    'CoreModulesHeaders',
    'DevSupport',
    'RCTWebSocket'
  ], :modular_headers => true
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'amplitude-react-native', :path => '../node_modules/@amplitude/react-native'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'react-native-get-random-values', :path => '../node_modules/react-native-get-random-values'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-performance', :path => '../node_modules/react-native-performance/ios'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNCalendarEvents', :path => '../node_modules/react-native-calendar-events'
  pod 'RNCClipboard', :path => '../node_modules/@react-native-community/clipboard'
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-masked-view/masked-view'
  pod 'RNDefaultPreference', :path => '../node_modules/react-native-default-preference'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNWatch', :path => '../node_modules/react-native-watch-connectivity'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
 

  pod 'CocoaLumberjack', '~>3.5.3'
  pod 'ObjectiveDropboxOfficial', '~>6.1.0'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  use_native_modules!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end`

After running  "pod install" open xcode but it's saying Build Failed. Android side it's working fine. Any help regarding this ?

Thanks

**Comment by saghul** [comment]
We'll, what error are you getting?

**Comment by pankajnegi1893** [comment]
Just getting Build failed. No error. See screenshot
 
<img width="1792" alt="Screenshot 2022-01-17 at 11 42 36 AM" src="https://user-images.githubusercontent.com/49673803/149717034-3bec269f-1584-474c-858d-71b2d14db4dd.png">

**Comment by saghul** [comment]
Scroll down on the left panel, there should be a failure.

**Comment by pankajnegi1893** [comment]
I am at the end in left panel. But error there.
<img width="276" alt="Screenshot 2022-01-17 at 11 46 14 AM" src="https://user-images.githubusercontent.com/49673803/149717451-b91a85a6-46e2-432c-860f-39120676853f.png">

**Comment by saghul** [comment]
Try latest master, I made autolinking work, maybe that helps.

**Comment by pankajnegi1893** [comment]
ok will check
