### ISSUE TITLE
User authentication during a conference not working

### ISSUE THREAD

**Issue by shenziro** [jitsi/jitsi-meet#10796]
### Description:

Guests cannot authenticate during a conference to get moderator rights.

### Steps to reproduce:

(I hope the labels for the buttons are correct - we are not using english for our installation.)
1. During a conference open the Settings dialog
2. In tab Profile and click the Login button
3. Enter your credentials
4. Sign in

### Expected behavior:

Sign in and get moderator rights.

### Actual behavior:

No sign in happens and no moderator rights are granted. You can retry it multiple times.

### Server information:

- Jitsi Meet version: docker-jitsi-meet stable-6726-1
- Operating System: Ubuntu 18.04 LTS

### Client information:

- Browser / app version: recent versions of Google Chrome and Firefox
- Operating System: Windows 10 / Fedora 35

### Additional information:

Log output in the developer-console:
2022-01-17T09:47:57.656Z [modules/xmpp/xmpp.js] <P.connectionHandler>:  My Jabber ID: _correct jabber id_/_some token_?

We use the internal authentication - not ldap.

**Comment by gpatel-fr** [comment]
I confirm that this is not working either on recent unstable (6824). Trying to debug it, I have seen that the problem is at this point in authentication/components/web/LoginDialog.js:
```
149         if (conference) {
150             dispatch(authenticateAndUpgradeRole(jid, password, conference));
151         } else {
152             this.setState({
153                 loginStarted: true
154             });
155 
156             connect(jid, password, roomName)
157                 .then(connection => {
158                     onSuccess && onSuccess(connection);
159                 })
160                 .catch(() => {
161                     this.setState({
162                         loginStarted: false
163                     });
164                 });
```
connect succeeds but 'onSuccess' is undefined. I have no more time today to hunt for it, but a cursory search has found nothing to initialize this variable. So the authentication is working fine (I tested in Prosody log), but Jitsi-meet has decided to do nothing with it.

**Comment by gpatel-fr** [comment]
Tested: 5870 (may 2021) and 5765 (april 2021): identical problem. tested: 5390-3 (january 2021): works. 
This functionality is broken since one full year and no one has complained.

**Comment by 0xnor0** [comment]
We only recently updated to the latest versions and only now have noticed the problem. The old versions work fine.

**Comment by gpatel-fr** [comment]
@0xnor0 : latest ? what does that mean ? we know that 6726 has the problem. What was the last working version for you ?

**Comment by 0xnor0** [comment]
@gpatel-fr  The last working version (for us) was 5390, after that we didn't update. After upgrading to version 6689 we noticed that it's not working anymore.

**Comment by saghul** [comment]
Yep in authenticated environments that's how it works.
