### ISSUE TITLE
Let camera enabled when presenting screen

### ISSUE THREAD

**Issue by zerotobtc** [jitsi/jitsi-meet#10802]
**Is your feature request related to a problem you are facing?**
When you click to share your screen (e.g. for a presentation) in the browser version, jitsi automatically turns off your camera. I know, that this could be seen as a feature but I think it's state of the art to let the camera enabled when switching to screen sharing.

**Describe the solution you'd like**
When you click "share screen" in the browser version of jitsi and you had your camera enabled beforehand, the camera should stay active. This way you save an additional click and the transition to presenting whatever you want to present is smoother.

**Describe alternatives you've considered**
You should at least get a notification that your camera was turned off because you switched to screen sharing. A lot of times you do start sharing and you think that the other paritcipants of the call are still seeing you but that's not the case!

**Comment by saghul** [comment]
At the moment, this is by design. You can use the camera icon to unmute yourself again.
