### ISSUE TITLE
Uncaught ReferenceError: X is not defined 

### ISSUE THREAD

**Issue by dphov** [jitsi/jitsi-meet#1081]
I had this error in browser after running 'make'

![2016-10-28 18 19 25](https://cloud.githubusercontent.com/assets/8191815/19807666/035e6b88-9d43-11e6-93ff-880b84c5aad5.png)

i have this files in directory, in this case but they will not included in js bundle after run 'make'

```
Uncaught ReferenceError: config is not defined
Uncaught ReferenceError: interfaceConfig is not defined

```
How to fix it?
Thanks.

**Comment by damencho** [comment]
Please using mailinglist discussing problems or asking questions, before opening issues.

The browser fails to fetch config.js and interface_config.js. In default nginx config ssi is enabled by default and those files are included in the index.html, so check your ssi option in the virtualhosts for your deployment.
