### ISSUE TITLE
Make a Call only with jitsi ? 

### ISSUE THREAD

**Issue by TienHai** [jitsi/jitsi-meet#10816]
Hi, just a quick question

Can I use jitsi to make a SIP call without video?

do you have an example app of this use case?

Thanks

**Comment by saghul** [comment]
While Jitsi Meet has some integration with SIP devices, its primary focus is to be a video conferencing application/ platform.

You may wat to check the legacy Jitsi desktop app: https://github.com/jitsi/jitsi
