### ISSUE TITLE
IFrame getCurrentDevices() returns incorrect audio input device

### ISSUE THREAD

**Issue by QCWBradleyGebhardt** [jitsi/jitsi-meet#10829]
### Description:

I have an audio device with an id of "communications" that handles both input and output. It's also my default input device. However when I set the input device, using ```setAudioInputDevice```, to the ```default``` and then call ```getCurrentDevices``` the returned input device has the id of ```communications``` and not ```default```. It seems to happen when the "communications" device is selected as the output

### Steps to reproduce:

1. Connect a single device that handles both input and output
2. Select that device as your output device
3. Select the "default" as your input device
4. Call ```api.getCurrentDevices```

### Expected behavior:

```api.getCurrentDevices``` will return the device with the id of ```default``` as the ```audioInput```

### Actual behavior:

```api.getCurrentDevices``` returns the device with the id of ```communications```, the device that handles both input and output, as the ```audioInput```

### Server information:

- Jitsi Meet version: version on meet.jit.si
- Operating System: NA

### Client information:

- Browser / app version: Version 97.0.4692.99 (Official Build) (64-bit)
- Operating System: Windows 11 Pro 21H2

**Comment by 1fabi0** [comment]
I like not planned for a bug
