### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by JakeQZ** [jitsi/jitsi-meet#10822]
### Description:

Audio cannot be heard by more than 50% of participants.  Also it keeps crashing.

This is completely broken and currently unusable.

We had to switch to Skype.

Fix or revert needed ASAP.

### Steps to reproduce:

1. Open https://meet.jit.si/issue10822 in Firefox
2. Open https://meet.jit.si/issue10822 on another computer in Firefox
3. Make some noise.

### Expected behavior:

Noise can be heard on the other computer's speaker.

### Actual behavior:

No sound is heard.

### Server information:

- Jitsi Meet version: As at 19:30 GMT 20/01/2022
- Operating System: N/A

### Client information:

- Browser / app version: Firefox 96.0.1 (64-bit)
- Operating System: Windows 10 Home 21H1

### Additional information:

Surprised there are not already other reports of this bug.

**Comment by JakeQZ** [comment]
FAOD, it normally works fine. Clearly an update/commit (more than 6 hours ago) has broken something quite catastrophically and needs to be undone ASAP.

**Comment by damencho** [comment]
Have you experienced it in the past week? The last change on meet.jit.si happen more than a week ago.

**Comment by damencho** [comment]
Have you tried different computers?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by JakeQZ** [comment]
> Have you experienced it in the past week? The last change on meet.jit.si happen more than a week ago.

On Tuesday it was fine, so that is strange,

> Have you tried different computers?

Yes.

> Please, when you have questions or problems use the community forum before opening new issues, thank you.

If there's an issue that breaks the entire service for all users, you might like to know about it, I think - don't you?

**Comment by JakeQZ** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.

Please remove the tracking pixel from your "community forum".

**Comment by damencho** [comment]
> Please remove the tracking pixel from your "community forum". Please confirm when you have done that. At that juncture, I might consider using your "community forum", but not until.

I have no idea what you are talking about.



> If there's an issue that breaks the entire service for all users, you might like to know about it, I think - don't you?

Yes, we want to know, but we want to open issues after discussing it and figure out it is a problem with our software and to which project it belongs to, which can happen after discussing it in the forum. 



> Audio cannot be heard by more than 50% of participants. Also it keeps crashing.
> * Open https://meet.jit.si/issue10822 in Firefox
> * Open https://meet.jit.si/issue10822 on another computer in Firefox
> * Make some noise.

You are opening a meeting with 2 participants and one of them cannot be heard, and the other one is heard?

I just tried it with two Firefox participants and everything works as expected.

**Comment by JakeQZ** [comment]
> > Please remove the tracking pixel from your "community forum". Please confirm when you have done that. At that juncture, I might consider using your "community forum", but not until.
> 
> I have no idea what you are talking about.

The [forum site](https://community.jitsi.org/t/no-sound-unusable/110366) has a tracking pixel.  It works a bit like Google Analytics.  Please remove it, and don't install Google Analytics.

> You are opening a meeting with 2 participants and one of them cannot be heard, and the other one is heard?

3 participants.  I tried joining via my phone and it didn't work either.

At the start, I could hear the other person but they could not hear me.  I refreshed a couple of times to no avail.  They then refreshed and I couldn't hear them either.  We kept refreshing and eventually gave up and used Skype instead.

> I just tried it with two Firefox participants and everything works as expected.

Maybe you got lucky.

**Comment by JakeQZ** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.

If you want people to use the community forum before opening new issues, you need to fix the tracking and spyware issues you currently have.  I have already indicated what they are.

**Comment by damencho** [comment]
Not sure what is that you are seeing and that is not controlled by us but from the discourse hosting the forum. I do not see any requests to google by the way, but this is out of topic. 

Discussion continues in the forum, will re-open if we need to.

**Comment by JakeQZ** [comment]
> that is not controlled by us

Rubbish.  Unless you are in no part "us".

Your forum is not very good either.

However, Skype is even worse.  It seems online comminication doesn't work at all.  Who knew?
