### ISSUE TITLE
IoS first time load sound not working

### ISSUE THREAD

**Issue by Mihuilk** [jitsi/jitsi-meet#10836]
When I try to start the FIRST video conversation just after the IoS application has been installed permissions popups appeared.
Even if I enable all permissions (including sound) sound still does not work. This issue exists on both IOS SDK 4.1 and the latest application from the store (21.6.0 build 152). Reproduced on both iPhone X IoS 15.1 and iPhone 12 Pro Max version 15.2.1
Mute-unmute usually fix the problem
Each next video session everything is OK

**Comment by saghul** [comment]
This has been fixed in SDK 5.0.2
