### ISSUE TITLE
Changing `defaultLanguage` not working with mobile sdk

### ISSUE THREAD

**Issue by ivorcho** [jitsi/jitsi-meet#10834]
### Description:

Changing Jtsis interface default language of a mobile app not working. I try to set `defaultLanguage` using `new JitsiMeetConferenceOptions.Builder().setConfigOverride("defaultLanguage", "bg")` but it doesn't take effect. iOS doesn't work too.

Mobile SDK version: 4.1.0

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

For mobile, you need to change the system language on the phone.
