### ISSUE TITLE
API: Show custom notification to users

### ISSUE THREAD

**Issue by jHetzer** [jitsi/jitsi-meet#10854]
**Is your feature request related to a problem you are facing?**
Currently and after https://github.com/jitsi/jitsi-meet/commit/a618697e34d947f0cc0d9ee4a0fc79c76fbae5e6 there is no API to show Jitsi style informativ notification to users. API functions to show warnings or errors are available:

APP.UI.messageHandler.showError()
APP.UI.messageHandler.showWarning()

**Describe the solution you'd like**
Add API function APP.UI.messageHandler.showInformation()

**Describe alternatives you've considered**
An alternative would be to create custom html/js notification with seems unreasonable as there is already a feature rich notification component.

**Comment by damencho** [comment]
APP object is there temporary and to satisfy torture adb can vanish any moment. The correct way is using iframAPI and exposing notifications through it.

**Comment by jHetzer** [comment]
Hey @damencho 
the Jitsi Meet Web Interface pretty and neat. Rebuilding the functionality and using the iframAPI seems unnecessary and most likely wouldn't turn out as great as the official interface.
But for some use-cases the options in config.js or interface-config.js are not enough to tweak the user experience. I thought for this reason the APP object was build. An example case would be registering to events (**APP.store.getState()["features/base/conference"].conference**) and perform custom actions (**APP.UI.toggleFilmstrip()**).

So if APP object is not intended for this use case did I miss other options? One option which come to my mind is customizing the js code and build it for my self but the would be excessive.
Also APP Obj can be used within custom.js and therefor tweaks are simple and easy to integrate. This route for modifications is also available for the Jitsi Docker Image.

**Comment by damencho** [comment]
> using the iframAPI seems unnecessary and most likely wouldn't turn out as great as the official interface.

Why do you need rebuild to use iframeAPI and why the interface will be different?

The idea of iframe API is to give you a simple API to embed same meeting experience and extending it. 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

**Comment by damencho** [comment]
> This route for modifications is also available for the Jitsi Docker Image.

Using iframe API gives you the same even more, you can change deployments quickly.

**Comment by jHetzer** [comment]
If I understand you correctly I would need to create an additional webpage which handles the iFrame API part so I could us the API exposed functions. This rises following questions/remarks:

- Are the iFrame API function available within JitsiMeet, if not why?
- Functions of iFrame API and APP Object are not comparable and at least APP.store gives more possibilities in my view
- Are there currently plans to remove APP and therefor APP.store as its only temporary? [app.js#L28](https://github.com/jitsi/jitsi-meet/blob/2f1105e6d2c2b1a7d598b4927bc8a82c720a1013/app.js#L28) does not lock temporary. Refactoring all APP.store.dispatch calls or not exposing APP.store seems unnecessary.
- Even with the iFrame API I don't see how to display Jitsi style notifications?

**Comment by saghul** [comment]
> * Are the iFrame API function available within JitsiMeet, if not why?

They are available within Jitsi Meet, but there is no explicit API for it, the iframe API is that API.

> * Functions of iFrame API and APP Object are not comparable and at least APP.store gives more possibilities in my view

Yes, but APP.store is an implementation detail, not an API we support.

> * Are there currently plans to remove APP and therefor APP.store as its only temporary? [app.js#L28](https://github.com/jitsi/jitsi-meet/blob/2f1105e6d2c2b1a7d598b4927bc8a82c720a1013/app.js#L28) does not lock temporary.

Yes. Once the entirety of the app lives in react/ we'll likely get rid of it.

> * Even with the iFrame API I don't see how to display Jitsi style notifications?

That API call does not exist today indeed. What damencho was pointing out is that your request would make sense for a new command in the iframe API, but not a function in APP.

All that said, I think we have just run into "any observable behavior can be considered API" territory. 🤔
