### ISSUE TITLE
bring back camera-disabled icon (distinguish user-disabled and BWE-suspended webcams)

### ISSUE THREAD

**Issue by md-work** [jitsi/jitsi-meet#10852]
Before the [2.0.6826](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_6826) update there was an icon indicating if a user had disabled his webcam.  
This was very helpful to see if a user had explicitly disabled his webcam or if the webcam was automatically suspended by the [BWE (bandwith estimation)](https://github.com/jitsi/jitsi-meet/issues/10409#issuecomment-1013405095) (see #10409).

**Please bring back the _"webcam disabled"_ icon!**

**Comment by saghul** [comment]
We are gathering feedback on this change at the moment, it may or may not come back. Thanks for your input!

**Comment by photoninger** [comment]
At least it is still present in the participants pane.
I would also like to see the icon come back.

**Comment by nicoasi** [comment]
I also would be interested in this icon coming back for the same reason (or at least an option in config.js to enable/disable this icon). Thanks

**Comment by patricksebastien** [comment]
It should be an option, is there any plan to add this?

**Comment by saghul** [comment]
I don't think we have plans to bring it back at this time, sorry.

**Comment by nordishbynature** [comment]
It would be great if the icon was optionally visible

**Comment by srdjan-job-com** [comment]
+ Vote for bringing back camera icon

**Comment by saghul** [comment]
2 years have passed, we have no plans for it.
