### ISSUE TITLE
Is it possible to host Jitsi Meet on a static web server?

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#10850]
I only say this because the ipade project is basically a slightly modified Jitsi Meet that can be hosted on Github Pages.

If its not possible, could this be something to look into in the future? I believe that the ability to do this would open up a lot of hosting opportunities.

**Comment by jbg** [comment]
It's better to use community.jitsi.org for questions and keep the issue tracker for issues.

The Jitsi Meet frontend uses SSI but nothing else prevents it from being hosted as a static site; you just need to preprocess the SSI includes.

See for example https://github.com/avstack/jitsi-meet-static

**Comment by DillFrescott** [comment]
Gotcha, my bad.

Oh very cool! I'll check that repo out for sure!

Thank you for the response! <3
