### ISSUE TITLE
npm ERR! git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by brlarini** [jitsi/jitsi-meet#10856]
### Description:

Running 'npm install' on jitsi-meet directory causes the following errors after a while:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/jitsi/rnnoise-wasm.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jitsi/.npm/_logs/2022-01-26T12_32_02_709Z-debug.log
```
I've tried to change the download method to 'https' in 'package-lock.json' file but then errors on integrity check start to happen.

### Steps to reproduce:

1. $ git clone https://github.com/jitsi/jitsi-meet.git
2. $ cd jitsi-meet/
3. $ npm install
4. (errors happen)

### Expected behavior:

Successful install.

### Actual behavior:

The errors above.

### Version information:

- Jitsi Meet version: 2.0.6826
- Operating System: Rocky Linux 8.5
- npm: 6.14.6
- git: 2.27.0

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Use the https address not the ssh one.

**Comment by brlarini** [comment]
Sorry, did you even read what I posted?
I have no issues downloading from jitsi-meet, the problem is when I execute 'npm install'.
I said that I already tried changing the json but other errors start to happen.
Is this the expected install behaviour?

**Comment by saghul** [comment]
You need Node 16 / npm 8.

**Comment by brlarini** [comment]
The problem seem to be the chosen download method of the required packages.
Trying to run manually:
`/usr/bin/git ls-remote -h -t ssh://git@github.com/jitsi/rnnoise-wasm.git`
results in the same error.

I guess I shoud try to change to 'https' AND remove the integrity check line from 'package-lock.json'?
Will that work, maybe?

Ok, I tried to report an issue and it seems it wasn't taken seriously.
Thanks anyway.

**Comment by damencho** [comment]
> Sorry, did you even read what I posted?

Nope, my bad, sorry.

But what @saghul said should fix your problem.

**Comment by brlarini** [comment]
Ok, I've updated the version as recommended and the result was yet another error on integrity check.
But then I could search for that one and found this post:
https://community.jitsi.org/t/npm-err-code-eintegrity-sha512-on-npm-install-on-jitsi-meet-web/107799/23

Removing the 'package-lock.json' as told in that post made it possible to run
```
$ npm install
$ make
```
successfully, even with nodejs 12 / npm 6.
I don't know what are the implications of removing that json though.

**Comment by saghul** [comment]
Sorry you are running into this.

There is a bug in a core library used by npm which triggers the integrity errors when using git dependencies.

We've slowly moved away from them, but there are still some, alas.
