### ISSUE TITLE
Sidebar overlapping shared document

### ISSUE THREAD

**Issue by brylie** [jitsi/jitsi-meet#1086]
When using the Shared Document feature, the menu overlays obstruct the text. This makes it difficult to view/edit the text.

![screenshot_20161029_122150](https://cloud.githubusercontent.com/assets/17307/19828574/5e7c11e8-9dd2-11e6-9c5b-aa54eda0ec81.png)

**Comment by wolftune** [comment]
+1

**Comment by yanas** [comment]
I'm adding this to our backlog. If anyone is interested in providing a solution a PR is more than welcome!!! It can be inspired by the desktop sharing specific size calculations.

**Comment by brylie** [comment]
Ah, I guess not.
