### ISSUE TITLE
Poor video quality with live stream and recorded video

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#10862]
### Description:

In the latest stable version (2.0.6826), both the live stream and video recording feature do not display people's cameras in a high resolution (very poor resolution).

### Steps to reproduce:

1. Open up a meet.jit.si room (or a room on your own server that has this version of Jitsi meet)
2. Press start live stream and enter key (or start recording).
3. View the footage outputted and the poor quality.

### Expected behavior:

People's cameras on the live stream or in the recorded video should be in high resolution. I have tested that this issue doesn't appear in the previous stable version (2.0.6726).

### Actual behavior:

The recorded video or live stream video to YouTube is still outputting in HD just fine, but people's cameras are displaying in much lower resolution than that so the camera quality looks horrible on the live stream or the recorded video.

### Server information:

- Jitsi Meet version: 2.0.6826

**Comment by saghul** [comment]
Are you getting these results on meet.jit.si too? Can you share a sample recording?

**Comment by zon3d** [comment]
Yes, same results on meet.jit.si as well. Here is a sample: https://www.dropbox.com/s/ef6wbkqot6rgxo9/sample%20on%202022-01-27%2011-47.mp4?dl=0

**Comment by saghul** [comment]
Thanks for sharing.

**Comment by Pavelb76** [comment]
> Thanks for sharing.

I have the same problem on my own server. The output file is of low quality. After pressing "Record" the resolution is reset to 320x180

**Comment by saghul** [comment]
This was a nasty bug. It was just fixed in https://github.com/jitsi/jitsi-meet/commit/ae5723406d54c325570f9dedb94dd8de85d0598e

The next release will include this fix.

**Comment by Pavelb76** [comment]
> This was a nasty bug. It was just fixed in [ae57234](https://github.com/jitsi/jitsi-meet/commit/ae5723406d54c325570f9dedb94dd8de85d0598e)
> 
> The next release will include this fix.

I have a server on the local network. What do I need to do to fix this issue?

**Comment by saghul** [comment]
You can use the unstable packages or rebuild the frontend to include the linked patch.

**Comment by Pavelb76** [comment]
> You can use the unstable packages or rebuild the frontend to include the linked patch.

Or just apt-get upgrade jitsi-meet?

**Comment by saghul** [comment]
That will only work if you use the unstable repos. We haven't made a stable release with the fix yet.

**Comment by Pavelb76** [comment]
> That will only work if you use the unstable repos. We haven't made a stable release with the fix yet.

And if I wait for a fix for a stable release, can I use this command?

**Comment by Pavelb76** [comment]
> That will only work if you use the unstable repos. We haven't made a stable release with the fix yet.

I have it in the sources.list the next line 
deb https://download.jitsi.org stable/
That means I have a stable release, right?

**Comment by saghul** [comment]
Correct.

**Comment by Pavelb76** [comment]
> Correct.

To fix the problem, you need to update only the "jitsi-meet" package, or do you need to update something else?

**Comment by Pavelb76** [comment]
> Correct.

And one more question. It's better to wait for a fix for a stable release or install an unstable release of the jitsi-meet package?

**Comment by saghul** [comment]
That's up to you really. We try to not have a broken unstable build, but mistakes can and do happen.

**Comment by Pavelb76** [comment]
> That's up to you really. We try to not have a broken unstable build, but mistakes can and do happen.

and how long to wait for a fix for a stable release? If so, do I need to install a package "jitsi-meet" from an unstable release?

**Comment by Pavelb76** [comment]
> That's up to you really. We try to not have a broken unstable build, but mistakes can and do happen.
and how long to wait for a fix for a stable release? If so, do I need to install a package "jitsi-meet" from an unstable release?

**Comment by damencho** [comment]
This had been pushed to stable last week.

**Comment by SignFinder** [comment]
Hi team, it looks like bug was not fixed.
It appearing in our production and in fresh test lab with latest jitsi stale release. When we are srarting conference record via jibri, conference video quality degrade till 360 :-(

**Comment by saghul** [comment]
It's likely not related, even though the symptoms might look similar.

Please open a new issue and provide as many details as possible, including a screen recording of what happens.

**Comment by gauravBasra07** [comment]
Hey @saghul , I still face the same issue. I install jitsi and jibri from https://github.com/jitsi-contrib/installers/blob/main/jitsi-jibri/jitsi-jibri-installer installer. Everything is working fine but the recorded file video quality is very low.

**Comment by saghul** [comment]
I'd recommend you open an issue on that repo. That is a community maintained installer.

**Comment by gauravBasra07** [comment]
I post this issue on the jitsi community and emrah also replying. If anybody have same problem follow this forum

https://community.jitsi.org/t/poor-quality-video-in-recorded-file/129291/3

**Comment by gauravBasra07** [comment]
@saghul , This issue is still on there. I also check the same video quality issue on https://meet.jit.si/. And also the poor video quality in my recorded file. Please guyz help me to resolve this bug.

**Comment by gauravBasra07** [comment]
[DivineSupplementsCelebrateClosely_2024-01-18T12_01_35.199Z.webm](https://github.com/jitsi/jitsi-meet/assets/107847346/1de260a6-a325-4b86-bc0e-093fa58178c7)

Please find the attachment of sample recording file @saghul

**Comment by gauravBasra07** [comment]
Hello @saghul, Is this a bug. Please also check on your side.

**Comment by gauravBasra07** [comment]
@saghul , this issue not only in my self hosted jitsi (which I install through the script by emrah). Its also present on jitsi official meeting site as well. Can you please check it? I'm using the latest version of jitsi and latest version of jibri as well.
And also I'm waiting for your reply on community

Thanks
