### ISSUE TITLE
Users who are screen sharing are not showing in the filmstrip

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#10869]
### Description:

Bug: Doesn't show the screen of any user who is sharing their screen in the filmstrip, even when they aren't the user being viewed.

### Steps to reproduce:

1. Have at least 3 people in a room.
2. Make one of the users share their screen.
3. View the other user in the room, and in the filmstrip you will see your camera but not the person's screen who is screen sharing in the filmstrip (it's like they aren't showing anything at all).

### Expected behavior:

When users are screen sharing, and you are viewing other people, the users screen sharing should show in the filmstrip, rather than just having their name in the filmstrip.

It used to work correctly in earlier versions of Jitsi.

### Actual behavior:

It doesn't show the screen of the users who are screen sharing in the filmstrip, it just shows as if their camera is off.

See below for an example, I am viewing "user 2", and the user called "share screen" is sharing his screen but it doesn't show their screen at all in the filmstrip: 

![Capture](https://user-images.githubusercontent.com/67055226/151503891-00ec8a03-5124-4a23-ad16-7be2f03c136a.JPG)

### Server information:

- Jitsi Meet version: 2.0.6826

**Comment by saghul** [comment]
This is expected behavior. There is a "screen sharing" indicator in the thumbnail. Showing it in such small area is really not practical.

**Comment by zon3d** [comment]
I see, but when we are live streaming we would like to show all the users' screens on the filmstrip, is there a way of enabling it or adding it as an option?

**Comment by saghul** [comment]
No, there is currently no way to enable that. If you use tile view, you'll see all screens though.

**Comment by zon3d** [comment]
Could this possibly be changed to a feature request then?

**Comment by zon3d** [comment]
> This is expected behavior. There is a "screen sharing" indicator in the thumbnail. Showing it in such small area is really not practical.

Now with the new Jitsi and the ability to make the filmstrip on the side very large, the use of being able to see what is being screen shared by other users would be very handy (without having to be on tile view). Your thoughts?

**Comment by saghul** [comment]
We are in the process of making larger layout changes, the resizability is just one of them. We are revisiting the logic for multiple desktop shared.

**Comment by zon3d** [comment]
> We are in the process of making larger layout changes, the resizability is just one of them. We are revisiting the logic for multiple desktop shares.

I notice on meet.jit.si, the screensharing is now showing successfully in the filmstrip. But not on my own server (even though I have the latest version (2.0.7577-1). how do I enable it on my server? Is it a config option?

**Comment by saghul** [comment]
You can now enable `sourceNameSignaling` and `sendMultipleVideoStreams` in the `flags` section in config.js.

**Comment by zon3d** [comment]
> You can now enable `sourceNameSignaling` and `sendMultipleVideoStreams` in the `flags` section in config.js.

Ahh I see that is what it's doing, the screen is a separate participant in the room. 

It is interesting to note that the shared screen is successfully seen on the filmstrip though. That is great! Could it be added in (or is there a line of code I could change) to allow the filmstrip to show any user's shared screens without the screen being it's own participant?

**Comment by saghul** [comment]
That was the previous behavior.

**Comment by zon3d** [comment]
> That was the previous behavior.

I understand, but for live streams via Jitsi with multiple people sharing their screen, do you see why it would be helpful to have an option to enable the filmstrip showing all the screens being shared?

**Comment by saghul** [comment]
Maybe I don't understand the use case, can you elaborate? How is that different from just opening tile view?

**Comment by zon3d** [comment]
> Maybe I don't understand the use case, can you elaborate? How is that different from just opening tile view?

We use Jitsi (with Jibri) to live stream one particular person's screen at a time, but we want on the live stream the filmstrip on the right side to show all the other users in the room who are sharing their screens at the same time.

**Comment by saghul** [comment]
I see. When you disable the new multi-stream mode, are the screen-sharing tiles not always ordered at the top? Any chance you have disabled tile reordering?

**Comment by zon3d** [comment]
> I see. When you disable the new multi-stream mode, are the screen-sharing tiles not always ordered at the top? Any chance you have disabled tile reordering?

I have disabled tile reordering, but even if it is on, it still won't show the people's actual screens in the thumbnails though

**Comment by saghul** [comment]
@jallamsetty1 can you enlighten us here? :-)

**Comment by jallamsetty1** [comment]
@zon3d Don't you see the screenshare in the thumbnails on filmstrip when multi-stream is enabled ? There are 3 flags that need to be enabled https://github.com/jitsi/jitsi-meet/blob/master/config.js#L105. In the legacy mode, i.e., without multi-stream, screenshare is not shown in the thumbnails in the filmstrip, it is shown only when SS is on stage or in tile view.

**Comment by zon3d** [comment]
@jallamsetty1 I would like the SS thumbnails to be showing in the filmstrip for the live stream without having multi-stream on because I don't want users to have a separate participant for their screen and one for their camera.

Would it be a matter of changing the line in /react/features/filmstrip/functions.web.js line 542 ?
```
    if (!tileViewActive && filmstripType === FILMSTRIP_TYPE.MAIN && ((isScreenSharing && isRemoteParticipant)
        || (stageParticipantsVisible && isActiveParticipant))) {
        return DISPLAY_AVATAR;
```
to: return DISPLAY_VIDEO;

Or if this was an option in the config to enable this it would make it much easier, right?

**Comment by jallamsetty1** [comment]
@zon3d Please note that this is how it has been in the legacy mode, previews for SS were not available in the filmstrip. I don't know think it makes sense to make changes to that mode when it's going away soon. Multi-stream will be enabled by default in the code in the upcoming release.

**Comment by zon3d** [comment]
@jallamsetty1 What I am asking for regarding legacy SS would make sense for live streaming scenarios because with the new SS it won't show on the main screen the screen of the person who is speaking, because their sound will be coming from themselves, not the screenshare participant. So the main screen focus will be on the wrong thing.

This is because AUTO_PIN_LATEST_SCREEN_SHARE has to be set to false because there are multiple people sharing their screens on the live stream and I only want to show on the main screen the screen of the person speaking, not the latest screen that was shared.

**Comment by jallamsetty1** [comment]
In that case, won't you be able to achieve what you want by enabling multi-stream and by disabling AUTO_PIN_LATEST_SCREEN_SHARE ?

**Comment by zon3d** [comment]
@jallamsetty1 But wouldn't the live stream focus be on the person's camera and not their screen because the audio is coming from the person and not the screen?

**Comment by zon3d** [comment]
@jallamsetty1 Thoughts?

**Comment by jallamsetty1** [comment]
In the mean time you can enable follow-me and have an administrator pin the tiles that they want to highlight in the livestream.

**Comment by zon3d** [comment]
@jallamsetty1 Make sure not to remove legacy mode until there is a proper solution for live streaming without having to do the follow me thing, as that isn't ideal.

**Comment by jallamsetty1** [comment]
> This is because AUTO_PIN_LATEST_SCREEN_SHARE has to be set to false because there are multiple people sharing their screens on the live stream and I only want to show on the main screen the screen of the person speaking, not the latest screen that was shared.

@zon3d With AUTO_PIN_LATEST_SCREEN_SHARE disabled, the Jibri participant wouldn't even switch to stage view. Even if we implement electing SS tile instead of the camera tile (whenever SS is available) for showing it on stage (main screen), the live stream will be in tile view.

**Comment by jallamsetty1** [comment]
Nevermind, I do see Jibri switching to stage view automatically. I have a fix incoming for this issue.

**Comment by zon3d** [comment]
@jallamsetty1 Thanks for the update, looking forward to it! :)

**Comment by zon3d** [comment]
@jallamsetty1 - Thanks for the update, I just tested it with sendMultipleVideoStreams: true. 

But it looks like there is an issue that the stage (big view) always just shows the latest screen share, even though AUTO_PIN_LATEST_SCREEN_SHARE: false in interface_config.js, rather than showing on the stage the participant who is actually speaking or if that person is sharing their screen, their screen.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 - Thanks for the update, I just tested it with sendMultipleVideoStreams: true.
> 
> But it looks like there is an issue that the stage (big view) always just shows the latest screen share, even though AUTO_PIN_LATEST_SCREEN_SHARE: false in interface_config.js, rather than showing on the stage the participant who is actually speaking or if that person is sharing their screen, their screen.

Are you testing the master or the last stable release ? I am not sure if this fix has been released to stable yet.

**Comment by zon3d** [comment]
@jallamsetty1 You're right, I was trying the latest stable. Just tested the master, and it is working. Thank you very much!

**Comment by zon3d** [comment]
@jallamsetty1 With the new SS mode, is there an option to be able to see your own screen being shared in tile view? A bunch of users keep getting confused whether they are sharing their screen or not because it doesn't appear in tile view.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 With the new SS mode, is there an option to be able to see your own screen being shared in tile view? A bunch of users keep getting confused whether they are sharing their screen or not because it doesn't appear in tile view.

Did you set testing.enableThumbnailReordering  to false in your config.js ? See - https://community.jitsi.org/t/setting-enablethumbnailreordering-to-false-breaks-screenshare-in-grid-view/118092

**Comment by zon3d** [comment]
@jallamsetty1 Thanks for that. Yes that solved it temporarily, as I had set enableThumbnailReordering to false. Thank you.

**Comment by jallamsetty1** [comment]
Please be advised that disabling enableThumbnailReordering is not supported anymore. The config was only added so that we can test it on our deployments (as is the case with all settings under the testing section) before we enable it by default. Thumbnail re-ordering has been enabled by default for a while now and we will removing the option to disable it soon. We do not intent to support the other mode.
