### ISSUE TITLE
Mute whole Jitsi session with a button on the Web

### ISSUE THREAD

**Issue by tgrymatt** [jitsi/jitsi-meet#10872]
There is a button with which I can turn my microphone on and off. Also a button with which I can turn my camera on and off. This is logical and necessary.

But what I personally miss is a button with which I can turn off all sound outputs of Jitsi for me. Basically like pressing the "speaker off" button on my computer.

In the following scenario it would be a useful feature: I have a softphone installed on my computer, which is ringing even though I am in a Jitsi session. Now I want to answer the call but I don't want to leave the jitsi session or ask everyone else to be quiet for a moment. With one push of a button I could mute the sound output of Jitsi for me, accept the call on the softphone and later switch on the Jitsi sound again with another push of a button.

If I use Jitsi in a browser, then I could theoretically mute the tab. But again, that doesn't work in the Jitsi desktop app. Also, it may not work in every browser or the user may not be able to get it to work. A button similar to "Camera on/off" or "Microphone on/off" that can be reached very quickly would therefore be desirable. Alternatively, it could be reached via the menu, but also via a shortcut on the keyboard.

**Comment by darylhutchings1** [comment]
+1 on this feature. We would love a speaker mute option / api that works on desktop and mobile. On our customized application, we do a workaround to "leave audio" which initiates the "join without audio" config, but requires the session to refresh. Same when we then have "join audio" which again refreshes the media. Would be much better for us to have "mute mic" and "mute speaker" controls independently that we can play with and configure without having to refresh the session. We'd be more than happy to contribute some code for this to benefit the community if the jitsi team can point us in the right direction? Thanks Daryl

**Comment by darylhutchings1** [comment]
A couple of screenshots of how it's presented on Zoom as an example

<img width="646" alt="Screen Shot 2022-01-28 at 10 57 32 AM" src="https://user-images.githubusercontent.com/38544361/151535455-a6abe141-41a1-43dd-b771-f1b5ba807885.png">

<img width="575" alt="Screen Shot 2022-01-28 at 10 57 43 AM" src="https://user-images.githubusercontent.com/38544361/151535507-eff107f5-742b-4198-bbcb-c127cd2fc490.png">

And on our app Video Window .....

<img width="523" alt="Screen Shot 2022-01-28 at 11 01 13 AM" src="https://user-images.githubusercontent.com/38544361/151535850-99422eb3-ab27-40c7-aee1-9e13512a1cc4.png">

<img width="495" alt="Screen Shot 2022-01-28 at 11 01 23 AM" src="https://user-images.githubusercontent.com/38544361/151535888-5c711fed-360e-4363-84b6-b9d613ab1533.png">

**Comment by tmatthaeus** [comment]
On BigBlueButton a option like this exists already. Please show the attached screenshot. Sure, for Jitsi the image would be the wrong, there should be more a loudspeaker symbol used. But something like this would be great. Unfortunately I can not provide with code. But if you need something else, please let me know.
![Bildschirmfoto 2022-01-28 um 12 07 18](https://user-images.githubusercontent.com/1618310/151537221-dd4f3577-0dd5-4219-a6b1-382618e79c13.png)

**Comment by saghul** [comment]
Thanks for the feedback folks. We'll take a look.

**Comment by tmatthaeus** [comment]
Hey @saghul any news about this request, before the bot is closing this ticket? We would be willing to pay for that, if this helps ;)

**Comment by saghul** [comment]
It's not about money really. It's about product fit.

Until now, we have not considered having this feature.

I'll check with product and provide some closure here.

**Comment by Penny-L90** [comment]
We would also be interested in a feature like this. 

Our scenario: We have an ongoing meeting and want to join with another device just to manage the meeting / and monitor participants raised hands etc... and NEED to have speaker off for that other device (0 audio out). 

The feature zoom gives to disconnect all audio (shown in screenshots above) is quite useful.

**Comment by kumlali** [comment]
+1

We've been looking for this feature for a long time. A button and/or keyboard shortcut key to turn off/on the microphone, camera and speaker all together would be very useful.

**Comment by saghul** [comment]
If that is what you want the browser's mute tab feature is close enough.

The feature request that pops up every once in a while is Discord's deafen.

**Comment by jpotier** [comment]
> If that is what you want the browser's mute tab feature is close enough

I'm missing the option on the jitsi-meet android application. Here's my use case: my desktop computer doesn't have a webcam, but my phone does. So, I join both from my phone and my desktop. I need the phone to not output any sounds from the jitsi meeting, otherwise participants would get echoes.

I don't think Android makes it possible to mute an app (or please tell me how to do that). Also, reducing the volume to the max still lets audio through even in phone mode. Right now, my workaround is to connect my bluetooth earbuds to that audio goes to them, and I have them on the table, not wearing them so that the phone keeps silent.

**Comment by Beytullahiyigun** [comment]
We also have a need in the same regard. In summary, we need an development that will enabled the microphone, camera and meeting audio to be muted by pressing a single button during a meeting on Jitsi. You can think of it like a magic button. We need a button that can turn on and off it with a single button. Maybe with keyboard shortcut. We would be very pleased if this was included in the planning. We can even talk about it if a paid development can be made for us.

**Comment by kumlali** [comment]
> If that is what you want the browser's mute tab feature is close enough.

This feature only turns off/on incoming audio(speaker) in the tab. What we are looking for is a new button in Jitsi Meet screen (or a new Jitsi API) that is capable of turning off camera, outgoing audio (microphone) and incoming audio (speaker) all together for that meeting. Also, a keyboard shortcut for it would be very beneficial.

**Comment by unfa** [comment]
Yep. Jitsi Meet needs a "deafen" toggle like Discord has.
On a PC you can work this around, on a phone - there's no way.
I see why it's done like this, but it should be possible to override this default behavior without crazy hacking.

**Comment by ajpanton** [comment]
I also need to be connected via multiple phones in the same physical space. Unfortunately none of them can turn their mics on, because they all are forced to have their speakers on. As soon as a mic turns on, the echo kills everyone in the meeting. Just having the speakers on one of the phones would solve this problem.

**Comment by Johnmish** [comment]
Only Teams by microsoft does not offer the deafen option. Is Jitsi on the same level than teams ? If so, this is lame!

People have to work with multiple conference applications. This is a basic option, that should have been present even before the first release of jitsi!

**Comment by ronnyaa** [comment]
this should be reopened. 
But a dedicated speaker off button would not be as needed on mobile, if it was possible to lower the volume all the way down.

**Comment by HannesOberreiter** [comment]
fyi, as workaround I implemented a makeshift solution for us, by displaying a custom button.

**If you use an iFrame AND same origin server**, it is quite "simple", you can get the `<iframe>` object and change the muted state of the video element, eg.:

```ts
const iframe = api.getIFrame();
const videoElement = iframe?.contentDocument?.getElementById('largeVideo');
if (!videoElement) {
   console.warn('Video element not found in jitsi iframe');
   return;
}
videoElement.muted = true;
```

In my case I use iFrame but different origin server, therefore it is a little bit more cumbersome and with multiple downsides, 

- you need to listen on `participantJoined` events to mute new participants
- it does not remember any manual settings in the participants volume

```ts
    api.getRoomsInfo().then((data: {
      rooms: Array<{
        isMainRoom: boolean,
        id: string,
        participants: Array<{
          id: string
        }>
      }>
    }) => {
      if (!data.rooms || data.rooms.length === 0) return;
      for (const participant of data.rooms[0]!.participants) {
        api.executeCommand('setParticipantVolume', participant.id, 0);
      }
    });
```
