### ISSUE TITLE
Custom contact invitation logic in UI

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#10879]
At the moment UI has two variation of the invite button.
Tap leads us to fix search screen and with the share button.
In many cases the search itself is unusefull.
Each application logic has it own inner way to manage local users.

So it would be great to allow set custom handler for the invite button.

In this case each developer could build its own invite logic on tap.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

That is already possible: https://github.com/jitsi/jitsi-meet/blob/9d829003b4337ce3ebdb2e584e6a2d212d119ec5/config.js#L1137

[Some of the APIs are described here: https://github.com/jitsi/jitsi-meet/blob/master/resources/cloud-api.swagger
But not the peopleSearchUrl one ](https://jitsi.github.io/handbook/docs/devops-guide/videosipgw#people-search-service)
