### ISSUE TITLE
Auto Restart Jitsi Video Bridge

### ISSUE THREAD

**Issue by LukeStephen** [jitsi/jitsi-meet#1087]
Every once in a while when two devices try to connect they will get black screens (any devices trying to connect after that point get the same black screen no matter which device it is or which network they're on). To resolve this I restart the Jitsi Video Bridge (JVB) and everything works fine again.

I wonder if there is a way to monitor for a video streaming issue with the JVB and have it auto restart itself? Has anyone setup a script to do this or is there something built into JVB?

**Comment by e-ratio** [comment]
I have the same issue! Actually I restart the service in cron every 12 hours, but I'm searching for a better solution!

**Comment by karras** [comment]
We encountered a similar issue. Have a look at the issue #1231. Maybe this could be a viable workaround for you as well.
