### ISSUE TITLE
Screen share does not work well on browsers with external videobridge

### ISSUE THREAD

**Issue by ddoussot** [jitsi/jitsi-meet#10883]
### Description:

Hello,
I have currently configured 3 servers : 1 with all the components and 2 additional servers which are only running vidobridge, in order to scale.
When there are many conferences, they spread well between the 3 servers.
But, when one of the 2 additional vidobridge servers is used, screen share does not work well. A user can share its screen but the other won’t see anyhting either on chrome or Firefox. But if they’re using the Android app it works…
Any idea to solve this please ?

### Steps to reproduce:

Disable videobridge on main server and start conference, so that another vidobridge server is used.

### Expected behavior:
THe share screen function whould didplay the screen on the attendees screen.

### Actual behavior:
The shared screen does not display unless the user uses the Android App.
It does not display on Chrome neither on Firefox on Windows.

### Server information:

- Jitsi Meet version: jitsi-meet/stable 2.0.6726-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chrome 97.0.4692.99, Firefox 96.0.3 (64 bits)
- Operating System: Windows 

### Additional information:
N/A

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Are the websockets operational with the external jvbs? 
Most probably this is your problem.

**Comment by damencho** [comment]
I see your post in the community let's continue there https://community.jitsi.org/t/problem-with-screen-share-when-videobridge-is-on-another-server/110753?u=damencho
