### ISSUE TITLE
Android App - Media section Track Specification Not Supported by Unified Plan (in P2P)

### ISSUE THREAD

**Issue by Freddie-m** [jitsi/jitsi-meet#10886]
### Description:

After stopping screensharing from Android app in a P2P call, media is no longer received by the remote participant. In order to resume receiving media, remote participant will need to refresh their client.

### Steps to reproduce:

1. Start a two-party meeting with one of the participants using the Android app
2. Start screensharing from the Android app. 
3. Stop screensharing from the app
4. Click the button to re-enable the camera on the Android app

### Expected behavior:

When screensharing is stopped on the app and the camera button activated, the remote participant should resume receiving media from the sending Android client.

### Actual behavior:

When I stopped sharing from the android phone, my camera did not automatically switch back on. When I tap the camera icon to turn it back on, on the phone, it shows that the camera is on (I see my local video), but on the other party's side, they weren't getting my video. If I then refreshed the other party's browser (Chrome on a desktop), the android's camera became visible again. While the feed of the android phone was not showing up on the desktop participant's browser, I noticed that if I tried to screenshare again, nothing shows up on the desktop (Chrome) browser. However, if I refresh the Chrome browser, I'm able to see the screenshare from the Android phone.

Console log shows error message consistent with finding:

![Screen Shot 2022-02-01 at 2 50 08 AM](https://user-images.githubusercontent.com/63688942/151931053-479805b7-738e-4a41-a7cc-63ad22fbe95b.png)

The DOMexception suggests there was an issue renegotiating the streams from the Android app. 

It should be noted that this only happens in a two-party call. In a call with 3 or more participants, everything works as expected.

### Server information:

- Jitsi Meet version: Latest Stable on meet.jit.si

### Client information:

- Browser / app version: Latest Jitsi Android App

**Comment by saghul** [comment]
Thanks for the report Freddie! Were you using the beta Android app?

**Comment by saghul** [comment]
I could not repro with latest beta on iOS, but I can on Android. WAT.

**Comment by Freddie-m** [comment]
No, I used the released version in the store. I didn't test on iOS though, just Android.

**Comment by Vamsi-Rayapati** [comment]
@saghul  Is it fixed ? please provide  that commit links

**Comment by saghul** [comment]
Nope, it has fallen through the cracks I'm afraid. I did fix a bug about screen-sharing on Android recently, so there is a non-zero chance I fixed that too.

**Comment by saghul** [comment]
This has been fixed long ago. Mobile is now fully supporting unified plan.
