### ISSUE TITLE
Avatars are missing

### ISSUE THREAD

**Issue by cmrd-senya** [jitsi/jitsi-meet#1089]
After a recent update in our own installation of jitsi meet  (`git pull` and friends) avatars dissapeared. 

![2016-10-31 15 48 56](https://cloud.githubusercontent.com/assets/10187586/19856663/1f7cf31a-9f83-11e6-9119-192611b82882.png)

Before everything was fine, it showed robots pictures. Maybe this is my misconfiguration. In this case I ask you to help me to configure jitsi meet properly. In any case, this shouldn't work this way, so I guess it is a bug at the same time.

**Comment by damencho** [comment]
Could you please use the mailinglist when heaving questions or problems, before opening issues.

It seems the robohash certificate expired on Oct 29. You can switch to another avatar service (in interface_config.js RANDOM_AVATAR_URL_PREFIX and RANDOM_AVATAR_URL_SUFFIX)
