### ISSUE TITLE
mod_reservations - no api calls for remembered authentication

### ISSUE THREAD

**Issue by qwertiko** [jitsi/jitsi-meet#10892]
### Description:

I have noticed that with a lua authentication in place, as long as the authentication is needed, the api calls to /conference take place. If my authentication was remembered and I start a completely new conference (with a different name) no further api calls to /conference take place, in fact there are no further log entries from mod_reservations to be found.

I even increased the logging in `module:hook("pre-iq/host", function(event)` but it seems this section is not triggered again with a remebered, authenticated session.

### Expected behavior:

The API should always be triggerd on new conference rooms

### Actual behavior:

The API is only triggered after authentication - if the session is rememberd (and thus the user still authenticated) the API is not triggered again.

### Server information:

- Jitsi Meet version: 2.0.6865-2
- Operating System: Ubuntu 20.04 LTS

**Comment by damencho** [comment]
@shawnchin any idea :) ?

**Comment by shawnchin** [comment]
Hmmm... not much the reservation module can do if `pre-iq/host` not triggered. 

I'm afraid I'm not familiar enough with lua auth to guess what might be going on there.

Interestingly, there's a deleted community post specifically mentioning that (https://community.jitsi.org/t/cannot-hook-pre-iq-host-in-prosody-if-auth-is-enabled/102419) ([google cache](https://webcache.googleusercontent.com/search?q=cache:v8DeTG-Cf3cJ:https://community.jitsi.org/t/cannot-hook-pre-iq-host-in-prosody-if-auth-is-enabled/102419+&cd=1&hl=en&ct=clnk&gl=uk)) so that seems like an issue that someone has stumbled on before.

**Comment by qwertiko** [comment]
Is there anything we can do to further debug?

**Comment by shawnchin** [comment]
I have no idea I'm afraid. Personally I would start by:
1. adding another hook to `pre-iq/host` to just log everything to determine if that hook is not called at all, or just the expected iq is not being sent
2. inspect messages client is sending to prosody on join, and compare session before auth and with cached auth.

**Comment by qwertiko** [comment]
`pre-iq/host` is in fact not triggered if the user has a remembered session.

**Comment by damencho** [comment]
Actually you can disable autologin in jicofo and users will always need to login which I think will trigger your logic.

**Comment by damencho** [comment]
You can disable it in jicofo.conf with enable-auto-login = false, like this:
https://github.com/jitsi/jicofo/blob/b88c3148701da4a6f8ce2f1a25cf93b4973dbb60/src/main/resources/reference.conf#L14

**Comment by shawnchin** [comment]
Now I'm curious what the interaction flow is like to set up room for authenticated users. Is there other events reservations module need to intercept in that use case?

Unfortunately all my deployment use JWT only so I can easily play around with that setup.

**Comment by qwertiko** [comment]
@damencho that seems a good workaround for the time being.

but i would like to find the issue. @shawnchin i cannot seem to find a list of all possible hooks so that I could check what is going on in the background. do you have any suggestions on how to test what is being triggered in the two cases?

**Comment by shawnchin** [comment]
If you're referring to possible pre-routing hooks, I usually reference this: https://prosody.im/doc/developers/events#pre-routing

So `"pre-NAME/DEST"` where `NAME = {message, presence, iq}` and `DEST = {full, bare, host}`.

Other than reading up what was needed to write the reservations module, I frankly have not a lot of experience with lua or prosody so not sure what a good debugging strategy here. Logging out all everything and grepping for specific client would probably be how I'd start. :man_shrugging:

**Comment by qwertiko** [comment]
so, with the workaround in place I am still able to open reserved rooms:
 opening an unreserved room - mod_reservations does its thing and this works well.
 while this session is still running proceed with opening the reserved room.
 my authentication seems cached. mod_reservations does nothing (again) and I have a room that was not supposed to be opened, but the api was not triggered and therefore not able to validate.

Next issue: when actually trying to open a reservered room errors are not transported back to the user, I am just stuck with "Obtaining session-id...":

![image](https://user-images.githubusercontent.com/45596432/152151024-f3047cd5-7130-4841-bb30-d9bccc07eff6.png)


And I am not getting anywhere with prosody and what is missing. I only see that no pre-iq/host messages get triggered at all in a cached auth state.

**Comment by qwertiko** [comment]
I would be more than happy to offer a joint session on our test environment if that is of interest to anybody.

**Comment by shawnchin** [comment]
What do you mean by "reserved rooms" vs "unreserved rooms"? Do you mean a room that is already created vs a new room creation when first user attempts to join?

**Comment by qwertiko** [comment]
ah, yes. Well it is mod_reservations... with reserved rooms I mean rooms  for which the reservation API is given a 403 return code.

**Comment by qwertiko** [comment]
So from what I was able to gather: mod_reservations is at the moment not a drop in replacement for the former jicofo implementation. It aims to be but it is not quite there yet. That makes running the latest stable rather difficult for us, as we rely on the reservation implementation, next to standard reservations, to also limit the number of concurrent sessions a user can have.

I have no further ideas in debugging what is actually going on, I can only again offer a joint session on our test environment in order to find what might be missing to make mod_reservations work as the jicofo implementation did.

I am also open for other suggestions / ideas.

**Comment by qwertiko** [comment]
Yes, I do that with jicofo, too.
I keep track of running sessions started with a username and will deny opening another room through the reservation system (and of course return a useful error message).

**Comment by qwertiko** [comment]
Ha - i am getting the `pre-iq/host` on the guest VirtualHost .... must I add mod_reservations there also?

**Comment by shawnchin** [comment]
What happens if you install the module globally? So remove from virtualhosts block, and add to `modules_enabled` in `/etc/prosody/prosody.cfg.lua`. Also move all the `reservations_*` config to global.

**Comment by qwertiko** [comment]
i am getting somewhere with that... had to add 
```lua
    if string.find(jid.bare(stanza.attr.from), '@meet.') == nil then
        module:log("debug", "skipping mail_owner %s", jid.bare(stanza.attr.from));
        return;
    end
```
to the `pre-iq/host` hook, to avoid sending api calls for invalid mail_owners.
Seems that now I am only stuck with not getting the error messages transported back to the client - basically they are not being displayed... with one of the other hooks I did mange to force that though - I'll do some more testing.

**Comment by qwertiko** [comment]
I am not getting anywhere - when loading the module globally I need to filter out any user that is `something@guest.example.org` else my api backend will decline because the user is unknown - not really a surprise but I honestly did not think of that at the time.

I cannot seem to find what is missing - I tried to tap in to every hook I was able to with only debug output as to see what is going on, but it seems the cached authentication is nothing I can get hold of. It does not seem visible in the stanza or anything.
i.e. the conference child in the stanza holds an `identity` attribute, but this is not the case if the authentication was cached...

**Comment by shawnchin** [comment]
Finally had a chance to have a play and managed to repro the two issues:
1. When user authenticates successfully but reservation error raised, user gets stuck on the modal with "Obtaining session-id..."
    * there [was a bug where reservation failure does not properly clear room states](https://community.jitsi.org/t/ux-when-reservation-fails/110095) which is now fixed in master. Not sure if this will get resolved with that or not.
2. Indeed, with auto-login enabled, subsequent room joins does not trigger reservation checks.

I think I can see why (2) is happening, but I am not familiar at all with Jicofo so no idea how to address this. 

Here's how I see the scenario playing out in prosody logs:

1. User is initially unauthenticated and visits page. Recognises as guest user (and sees login modal)
    ```
    Feb 18 22:03:02 c2s55bd4126c7f0	info	Client connected    
    Feb 18 22:03:02 c2s55bd4126c7f0	info	Authenticated as r9sws1akzfzfn15a@guest.meet.domain
    ```
    Note that user is on "@guest.meet.domain" so does not trigger reservations module
2. User logs in and is recognised as valid user on main domain.
    ```
    Feb 18 22:03:14 c2s55bd419ec920	info	Client connected
    Feb 18 22:03:14 c2s55bd419ec920	info	Authenticated as shawn@meet.domain
    Feb 18 22:03:15 c2s55bd419ec920	info	Client disconnected: connection closed
    ```
    Note that user now on "@meet.domain" so reservation module comes into play and everything happens as expected
3. User joins another room. Auth is remembered and user does not need to reauthenticate to join the room. In settings, we do see "Logged in as shawn@_meet.domain_" but for some reason, prosody sees the user as a new guest user (!). 
    ```
    Feb 18 22:03:22 c2s55bd41bd48c0	info	Client connected
    Feb 18 22:03:22 c2s55bd41bd48c0	info	Authenticated as nf00fxwwk4wsokmq@guest.meet.domain
    ```
    For this visit, we see no sign of the "@meet.domain" user in prosody logs, only a new "@guest.meet.domain" one. So "@meet.domain" host is not involved hence no reservation API calls. 

I presume client is still on @guest.meet.domain as far as prosody is concerned but is is somehow establishing identity with Jicofo directly? If so, no idea how to address this. 

@damencho any ideas?

**Comment by shawnchin** [comment]
BTW, if I disable anonymous domain, then everything works as expected and both issues are resolved. 
* On reservation failures, users are not stuck on auth modal and see the notification as expected.
* On rejoining a different room, user has to reauthenticate and reservation API called as expected.

**Comment by damencho** [comment]
> Finally had a chance to have a play and managed to repro the two issues:
> 
> 1. When user authenticates successfully but reservation error raised, user gets stuck on the modal with "Obtaining session-id..."
>    
>    * there [was a bug where reservation failure does not properly clear room states](https://community.jitsi.org/t/ux-when-reservation-fails/110095) which is now fixed in master. Not sure if this will get resolved with that or not.
> 2. Indeed, with auto-login enabled, subsequent room joins does not trigger reservation checks.
> 
> I think I can see why (2) is happening, but I am not familiar at all with Jicofo so no idea how to address this.
> 
> Here's how I see the scenario playing out in prosody logs:
> 
> 1. User is initially unauthenticated and visits page. Recognises as guest user (and sees login modal)
>    ```
>    Feb 18 22:03:02 c2s55bd4126c7f0	info	Client connected    
>    Feb 18 22:03:02 c2s55bd4126c7f0	info	Authenticated as r9sws1akzfzfn15a@guest.meet.domain
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Note that user is on "@guest.meet.domain" so does not trigger reservations module
> 2. User logs in and is recognised as valid user on main domain.
>    ```
>    Feb 18 22:03:14 c2s55bd419ec920	info	Client connected
>    Feb 18 22:03:14 c2s55bd419ec920	info	Authenticated as shawn@meet.domain
>    Feb 18 22:03:15 c2s55bd419ec920	info	Client disconnected: connection closed
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Note that user now on "@meet.domain" so reservation module comes into play and everything happens as expected
> 3. User joins another room. Auth is remembered and user does not need to reauthenticate to join the room. In settings, we do see "Logged in as shawn@_meet.domain_" but for some reason, prosody sees the user as a new guest user (!).
>    ```
>    Feb 18 22:03:22 c2s55bd41bd48c0	info	Client connected
>    Feb 18 22:03:22 c2s55bd41bd48c0	info	Authenticated as nf00fxwwk4wsokmq@guest.meet.domain
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    For this visit, we see no sign of the "@meet.domain" user in prosody logs, only a new "@guest.meet.domain" one. So "@meet.domain" host is not involved hence no reservation API calls.
> 
> I presume client is still on @guest.meet.domain as far as prosody is concerned but is is somehow establishing identity with Jicofo directly? If so, no idea how to address this.
> 
> @damencho any ideas?

Not sure there is an easy way of solving this, jicofo authenticates based on the session-id it receives and does not return to the client an error asking the client to authenticate and the client uses the guest domain ... if there is an error user provides username and password as this is what is needed to authenticate ... so you need user and password to authenticate ... it is like disabling auto-login ...

**Comment by shawnchin** [comment]
So only solution for now is to disable auto login. That still leaves the issue where user is stuck on "obtaining session id" instead of seeing reservation error when auth is success but reservation rejected.

**Comment by dihedral** [comment]
Even with auto login disabled, a user could start a new session and be asked to authenticate. After that the user could start a second session in another browser tab and that too will skip mod-reservations.

**Comment by dihedral** [comment]
> BTW, if I disable anonymous domain, then everything works as expected and both issues are resolved.
> 
> * On reservation failures, users are not stuck on auth modal and see the notification as expected.
> * On rejoining a different room, user has to reauthenticate and reservation API called as expected.

I will give this a try

**Comment by dihedral** [comment]
Just as an update - disableing anonymous domain resulted in unauthenticated guests not being able to join a meeting at all.
All my attempts in trying to get this to work fail.
