### ISSUE TITLE
Call hold/unhold feature

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#10898]
**Is your feature request related to a problem you are facing?**
If user participate in Jitsi call and want to temporary make a telephone call, he must end Jitsi call and then start it over again.

**Describe the solution you'd like**
Some Hold/Unhold option could be solution for that situation. 
User remain in Jitsi call (signaling) but frees mic and speakers for telephone call

**Describe alternatives you've considered**
Zoom have such [Hold/Unhold feature](https://support.zoom.us/hc/en-us/articles/360036228011-Using-in-call-controls)

**Comment by saghul** [comment]
We are not very keen on implementing this feature due to its complexity. Muting local audio / video is easy, but making sure the remote audio is not sent to us would require nontrivial backend changes.

**Comment by ankar84** [comment]
> We are not very keen on implementing this feature due to its complexity. Muting local audio / video is easy, but making sure the remote audio is not sent to us would require nontrivial backend changes.

Ok, I get is Saul! Thanks for your quick response!
Can you tag that issue with most far away milestone?
You can close if that feature will not implemented in future.

**Comment by Sanjeev0414** [comment]
@saghul any updates?

**Comment by saghul** [comment]
We are not planning to work on this feature any time soon.
