### ISSUE TITLE
Jitsi Meet not Connecting with 2 or more participants

### ISSUE THREAD

**Issue by fatuleta** [jitsi/jitsi-meet#10899]
### Description:

The application disconnects as soon as someone else joins the meeting. I have tried all possible fixes with no effect.

### Steps to reproduce:

1. Go to https://meet.pexenterprises.co.uk/
2. Create a meeting
3. Join the meeting with another device

### Expected behavior:

The Jitsi Meeting should work without interruption

### Actual behavior:

It disconnects as soon as another person joins.

### Server information:

- Jitsi Meet version: latest one available 
- Operating System: Ubuntu 18

### Client information:

- Browser / app version: Chrome, Microsoft Edge
- Operating System: Windows 11

**Comment by saghul** [comment]
Please use the community forum for asking questions.

You don't seem to have a working JVB:

```
2022-02-02T13:52:11.836Z [conference.js] <zte._onConferenceFailed>:  CONFERENCE FAILED: conference.videobridgeNotAvailable
```

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
