### ISSUE TITLE
Max 1 person for each videoconference.

### ISSUE THREAD

**Issue by ZIODIOZIO** [jitsi/jitsi-meet#10908]
Hello,

I am testing jitsi-meet after installing it on ubuntu.
Unfortunately when someone tries to join a meet with someone inside everything crash
![image](https://user-images.githubusercontent.com/74601229/152445573-149dfa0c-5de5-4d51-87af-e0245689cca4.png)

It seems like each meet can hold 1 person only.

Logs:

root@testfrompanel:/usr/share/jitsi-meet# tail /var/log/jitsi/jvb.log
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
        ... 17 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 22 more
JVB 2022-02-04 00:20:55.765 WARNING: [27] [hostname=localhost id=shard] MucClient.setPresenceExtensions#449: Cannot set presence extension: not connected.

root@testfrompanel:/usr/share/jitsi-meet# tail /var/log/jitsi/jicofo.log
Jicofo 2022-02-04 00:19:04.920 INFO: [113] [room=ciao@conference.meeting.space-hosting.net meeting_id=0ece65af-8c5a-4f97-8a56-1b38eeebc872] JitsiMeetConferenceImpl.rescheduleSingleParticipantTimeout#1869: Scheduled single person timeout.
Jicofo 2022-02-04 00:19:05.185 INFO: [113] [room=ciao@conference.meeting.space-hosting.net meeting_id=0ece65af-8c5a-4f97-8a56-1b38eeebc872] JitsiMeetConferenceImpl.onMemberLeft#795: Member left:42e1d592
Jicofo 2022-02-04 00:19:05.185 INFO: [113] [room=ciao@conference.meeting.space-hosting.net meeting_id=0ece65af-8c5a-4f97-8a56-1b38eeebc872] JitsiMeetConferenceImpl.terminateParticipant#837: Terminating 42e1d592, reason: gone, send session-terminate: false
Jicofo 2022-02-04 00:19:05.186 INFO: [113] [room=ciao@conference.meeting.space-hosting.net meeting_id=0ece65af-8c5a-4f97-8a56-1b38eeebc872] JitsiMeetConferenceImpl.terminateParticipant#860: Removed participant 42e1d592 removed=true
Jicofo 2022-02-04 00:19:05.186 INFO: [113] [room=ciao@conference.meeting.space-hosting.net meeting_id=0ece65af-8c5a-4f97-8a56-1b38eeebc872] JitsiMeetConferenceImpl.stop#436: Stopped.
Jicofo 2022-02-04 00:19:31.486 INFO: [114] ConferenceIqHandler.handleConferenceIq#63: Focus request for room: ciao@conference.meeting.space-hosting.net
Jicofo 2022-02-04 00:19:31.495 INFO: [114] [room=ciao@conference.meeting.space-hosting.net] JitsiMeetConferenceImpl.<init>#275: Created new conference.
Jicofo 2022-02-04 00:19:31.496 INFO: [114] [room=ciao@conference.meeting.space-hosting.net] JitsiMeetConferenceImpl.joinTheRoom#459: Joining ciao@conference.meeting.space-hosting.net
Jicofo 2022-02-04 00:19:31.681 INFO: [117] [room=ciao@conference.meeting.space-hosting.net meeting_id=6c07ef92-0ea4-43b0-bb18-cd9503aad0bd] JitsiMeetConferenceImpl.onMemberJoined#609: Member joined:afb4ce1a
Jicofo 2022-02-04 00:19:31.684 INFO: [117] AutoOwnerRoleManager.electNewOwner#106: Electing new owner: ChatMember[ciao@conference.meeting.space-hosting.net/afb4ce1a, jid: null]@982041904

root@testfrompanel:/usr/share/jitsi-meet# tail /var/log/prosody/prosody.log
Feb 04 00:20:38 c2s55a0872535c0 info    Client connected
Feb 04 00:20:38 c2s55a0872535c0 info    Client disconnected: ssl handshake error: sslv3 alert certificate unknown
Feb 04 00:20:43 c2s55a086de5b60 info    Client connected
Feb 04 00:20:43 c2s55a086de5b60 info    Client disconnected: ssl handshake error: sslv3 alert certificate unknown
Feb 04 00:20:48 c2s55a086cff5b0 info    Client connected
Feb 04 00:20:48 c2s55a086cff5b0 info    Client disconnected: ssl handshake error: sslv3 alert certificate unknown
Feb 04 00:20:53 c2s55a086b92ff0 info    Client connected
Feb 04 00:20:53 c2s55a086b92ff0 info    Client disconnected: ssl handshake error: sslv3 alert certificate unknown
Feb 04 00:20:58 c2s55a086d97880 info    Client connected
Feb 04 00:20:58 c2s55a086d97880 info    Client disconnected: ssl handshake error: sslv3 alert certificate unknown
root@testfrompanel:/usr/share/jitsi-meet#

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Restart jitsi-videobeidge2 service.

This had been fixed in latest versions https://github.com/jitsi/jitsi-meet/pull/10885

**Comment by ZIODIOZIO** [comment]
hello,

sorry for writing in the wrong location.
I have now opened a thread here: https://community.jitsi.org/t/restart-jitsi-videobeidge2/110921

Thank you!
