### ISSUE TITLE
IOS no sound on web app

### ISSUE THREAD

**Issue by donnierisk** [jitsi/jitsi-meet#10911]
### Description:

On IOS using the web app we tested the latest meet.jitsi that is live as well as via the API where we are able to retrieve available devices. The iphones doesn't pick up any to select. The sound either comes out of the top speaker (which is very soft, as if on phonecall) or it doesn't work at all.

### Steps to reproduce:

1. Go to meet.jit.si/anyroom on an iphone (safari / chrome)
2. Click on 'launch in web'
3. Can't hear other participants or it is coming through phone's soft speaker. 

OR

1. Make a call to iframe API: api.getAvailableDevices()
2. On list of devices, there's no speakers to select

### Expected behavior:

Should be able to hear from correct speaker or have any sound at all. OR Should be able to select different speakers on iframe API

### Server information:

- Jitsi Meet version: Latest
- Operating System: Iphone 12 latest OS

### Client information:

- Browser / app version: Safari / Chrome latest

**Comment by saghul** [comment]
What iOS version do you have? This is relevant because some important improvements made it to 15.4 IIRC. Also, does changing the device from control center change anything?

**Comment by donnierisk** [comment]
Hi thanks for reply @saghul so IOS version is 15.1.1. Does this mean an update would have to be done to confirm if it'll work or not?

Regarding control center: I requested the person to try, they said "There's no option to change speaker output in control center"

**Comment by saghul** [comment]
> Hi thanks for reply @saghul so IOS version is 15.1.1. Does this mean an update would have to be done to confirm if it'll work or not?

Yes, I recommend updating.



> Regarding control center: I requested the person to try, they said "There's no option to change speaker output in control center"

There is. It's an icon that looks like an antenna in the area where there is a play button.

**Comment by donnierisk** [comment]
Hi @saghul thanks for the response.

So our one user has IOS 15.1.1 and sound was problematic. Our other user has 15.2.1 and he seemed fine. He had issues when switching between his earphones and the phone (robotic voice), but besides that it worked fine.
![Image from iOS](https://user-images.githubusercontent.com/17927429/152552104-5e1e8dfc-c530-4168-b29d-fa2fe221a522.png)

Regarding the control center, there weren't any extra devices to select it seems, I have attached a screenshot

**Comment by saghul** [comment]
That's odd, I'd expect to see the speaker there!

Anyway, iOS 15's Safari has been quite a mess. The last couple of versions improve a lot, so please do update and re-test.

**Comment by saghul** [comment]
@jallamsetty1 are we are of any bugs in this scenario?

@donnierisk Out of curiosity, why are you setting disableInitialGUM?

**Comment by donnierisk** [comment]
Hi i'm creating webinars where there would be a default speaker; only when any of the other people want to speak do we give them a button through the iframe API to be able to speak. so it's mostly a one to many talk.

We recently upgraded to a newer version of Jitsi; In the past, I figured out that the prejoin page was enough to allow audio/video to be shown so I enabled that. But now even with the prejoin page it doesn't "activate" the audio to come through if that makes sense. It was a matter of having to interact with the page before autoplay was allowed.

**Comment by saghul** [comment]
Can you try replacing that with startWithAudioMuted (and the analogous for video) ?

**Comment by donnierisk** [comment]
I just found a random way to fix it. I tried what you suggested before, but with no luck.

I don't know what the best way would be to get it working, but I added an <audio id="audio-activator" /> element onto react/features/prejoin/components/Prejoin.js. Then in the _onJoinButtonClick() function I added:
document.querySelector('#audio-activator').play();

After that all subsequent audio worked.

**Comment by saghul** [comment]
Hum. Maybe we ought to do that. Any chance you can create a PR with that so we can bring in more team members to discuss it? Cheers!

**Comment by donnierisk** [comment]
I will do shortly, it seems that it only solved for safari on Mac. On iphones it still isn't working sadly.

**Comment by saghul** [comment]
Ah, bummer.

**Comment by jallamsetty1** [comment]
> 

I am not sure if we can make audio playback to work without a local capture. The behavior changed in iOS 15.0 and we had to add the audio track and then mute even if the user joins muted on iOS Safari. AFAIK, audio playback will not work when disableInitialGUM is being used.

**Comment by donnierisk** [comment]
Hi, thanks for the reply. So I managed to get it working by adding another button called 'enable audio', after that i present the join button on the prejoin page which loads the audio and plays. IOS 15.0 + requires 2 user interactions for audio to work like this.

I think my problem is a niche case, so not sure if it's worth pursuing for the main branch of Jitsi?

**Comment by saghul** [comment]
IMHO, not at this time.

**Comment by donnierisk** [comment]
Cool thanks for all the replies appreciate it. i'll close the issue now.
