### ISSUE TITLE
select user video from pane

### ISSUE THREAD

**Issue by slesru** [jitsi/jitsi-meet#10919]
Hello!

There is users list aka pane, it is quite useful, but if you want to watch video from user from list you have to find this user in small videos,
is it possible to add option show video from user using users list?

Thank you!

**Comment by slesru** [comment]
Hi! Nothing wrong here, but I don't see a way to choose participant as video source from here, only from thumbnails.
Is it possible?

**Comment by saghul** [comment]
Ah I think I know what you mean. You'd like to select a user to see it in the large view, right?

**Comment by slesru** [comment]
Yes, you are absolutely right, thank you!

**Comment by saghul** [comment]
Ops this was implemented, but we forgot to close this!

It's accessible through the 3 dots menu for a participant entry in the list.
