### ISSUE TITLE
Matrix ID is deformed in chat if colon is followed by chars that are relatet to smileys 

### ISSUE THREAD

**Issue by tigexplorer** [jitsi/jitsi-meet#10936]
### Steps to reproduce:

1. Paste a Matrix ID like `@name:singledomain.org` in the chat entry and hit enter

### Expected behavior:

The ID should not changed

### Actual behavior:

The ID is malformed on two lines with a smiley
![Auswahl_008](https://user-images.githubusercontent.com/43775552/153274991-7a4926e1-b447-421a-85ef-a1b6a8f6e13f.png)

### Server information:

- Jitsi Meet version: 
- Operating System: 

### Client information:

- Browser / app version: 2022.1
- Operating System: ubuntu 20.4

**Comment by haansn08** [comment]
Another great workaround is to use proper internet standards like XMPP, instead of custom protocols by some startup,  that for some reason must reinvent not only XMPP but also how URIs work.

**Comment by csett86** [comment]
Still relevant

**Comment by csett86** [comment]
As my matrix server starts with the letter "s" and thus I am affected by this, I may give it a try to fix this
