### ISSUE TITLE
vulnerable ciphersuites really removed?

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#10939]
According to this commit [Fix master secret extraction, support and use ECDSA and DTLS 1.2 · jitsi/libjitsi@60f54cc · GitHub](https://github.com/jitsi/libjitsi/commit/60f54cce9ca719f9d6b6bd1489e73f9966d0ca8a) a lot of deprecated ciphersuites have been removed, but later in the code the default algorithm is fetched from the certificate in use, and the case switch still refers to some algorithms with SHA1.
So I wonder if a MitM attack could still force a downgrade to a vulnerable protocol?

**Comment by damencho** [comment]
libjitsi is not used in any of the jitsi-meet components. libjitsi was removed from jitsi-videobridge 3 years ago.

**Comment by tseeling** [comment]
Thanks for that, I wasn't aware.
How can I find out which ciphersuites are currently supported in jitsi?
My security guy wants to confirm that no deprecated ciphersuites are available via MitM downgrade attacks.

**Comment by JonathanLennox** [comment]
For DTLS used by the Jitsi-Videobridge, you can see the cipher suites chosen at https://github.com/jitsi/jitsi-media-transform/blob/7926280a962a791d660a451e8f686c2967e2dd46/src/main/kotlin/org/jitsi/nlj/dtls/TlsClientImpl.kt#L128 and https://github.com/jitsi/jitsi-media-transform/blob/7926280a962a791d660a451e8f686c2967e2dd46/src/main/kotlin/org/jitsi/nlj/dtls/TlsServerImpl.kt#L102 .

(Peer-to-peer calls will use the browser's configured behavior, which isn't within our control.)

**Comment by tseeling** [comment]
I see that the outdated SHA1 is in one of the remaining cipher suites.
`CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA`
May I humbly suggest that this one will be removed as well?
