### ISSUE TITLE
Jitsi Meeting still using the audio source in Android 10 

### ISSUE THREAD

**Issue by aymanayyad19** [jitsi/jitsi-meet#10942]
### Description:
This issue just happen in android 10 and app show this error 
AudioSystem: invalid attributes { Content type: AUDIO_CONTENT_TYPE_MOVIE Usage: AUDIO_USAGE_MEDIA Source: -1 Flags: 0x800 Tags:  } when converting to stream

- Jitsi Meet version: 4.1.0
- Operating System: Android 10

**Comment by aymanayyad19** [comment]
2022-02-10 18:17:09.287 1784-9650/? E/IAudioPolicyService: listAudioProductStrategies: permission denied
2022-02-10 18:17:09.287 1784-9650/? E/AudioSystem: invalid attributes { Content type: AUDIO_CONTENT_TYPE_MOVIE Usage: AUDIO_USAGE_MEDIA Source: -1 Flags: 0x800 Tags:  } when converting to stream

**Comment by saghul** [comment]
Again, what exactly is the issue you are facing? Are you using the app or the SDK? What version?

**Comment by aymanayyad19** [comment]
I'm working on an android application that uses the Jitsi meet sdk feature  and show video media 
The Problem Is:
when I finish the Jitsi meeting call the media stop working and show this error 

> 2022-02-10 18:17:09.287 1784-9650/? E/IAudioPolicyService: listAudioProductStrategies: permission denied
> 2022-02-10 18:17:09.287 1784-9650/? E/AudioSystem: invalid attributes { Content type: AUDIO_CONTENT_TYPE_MOVIE Usage: AUDIO_USAGE_MEDIA Source: -1 Flags: 0x800 Tags: } when converting to stream

This Problem Just happen on android 10 after Jitsi meeting 


Device: Physical Device

Android Version: 10

Used Service: Jitsi Meet SDK (Android)
Log Error :

E/JitsiMeetLogger: [modules/xmpp/moderator.js] Focus error, retry after 1000 { _nsMap: { '': 'jabber:client' },
E/JitsiMeetLogger: attributes:
E/JitsiMeetLogger: { '0':
E/JitsiMeetLogger: { ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'xmlns',
E/JitsiMeetLogger: name: 'xmlns',
E/JitsiMeetLogger: namespaceURI: 'http://www.w3.org/2000/xmlns/',
E/JitsiMeetLogger: specified: true,
E/JitsiMeetLogger: localName: 'xmlns',
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 152,
E/JitsiMeetLogger: nodeValue: 'jabber:client',
E/JitsiMeetLogger: value: 'jabber:client',
E/JitsiMeetLogger: ownerElement: [Circular] },
E/JitsiMeetLogger: '1':
E/JitsiMeetLogger: { ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'type',
E/JitsiMeetLogger: name: 'type',
E/JitsiMeetLogger: namespaceURI: undefined,
E/JitsiMeetLogger: specified: true,
E/JitsiMeetLogger: localName: 'type',
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 173,
E/JitsiMeetLogger: nodeValue: 'error',
E/JitsiMeetLogger: value: 'error',
E/JitsiMeetLogger: ownerElement: [Circular] },
E/JitsiMeetLogger: '2':
E/JitsiMeetLogger: { ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'from',
E/JitsiMeetLogger: name: 'from',
E/JitsiMeetLogger: namespaceURI: undefined,
E/JitsiMeetLogger: specified: true,
E/JitsiMeetLogger: localName: 'from',
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 186,
E/JitsiMeetLogger: nodeValue: 'focus.jitsi.ethelcare.com',
E/JitsiMeetLogger: value: 'focus.jitsi.ethelcare.com',
E/JitsiMeetLogger: ownerElement: [Circular] },
E/JitsiMeetLogger: '3':
E/JitsiMeetLogger: { ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'id',
E/JitsiMeetLogger: name: 'id',
E/JitsiMeetLogger: namespaceURI: undefined,
E/JitsiMeetLogger: specified: true,
E/JitsiMeetLogger: localName: 'id',
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 217,
E/JitsiMeetLogger: nodeValue: '4540509d-2dd2-4279-bf00-11dcb5d96e84:sendIQ',
E/JitsiMeetLogger: value: '4540509d-2dd2-4279-bf00-11dcb5d96e84:sendIQ',
E/JitsiMeetLogger: ownerElement: [Circular] },
E/JitsiMeetLogger: '4':
E/JitsiMeetLogger: { ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'to',
E/JitsiMeetLogger: name: 'to',
E/JitsiMeetLogger: namespaceURI: undefined,
E/JitsiMeetLogger: specified: true,
E/JitsiMeetLogger: localName: 'to',
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 266,
E/JitsiMeetLogger: nodeValue: '[966c8872-69ce-43c7-a78c-51edf4994e08@jitsi.ethelcare.com](mailto:966c8872-69ce-43c7-a78c-51edf4994e08@jitsi.ethelcare.com)/wh9dAodb',
E/JitsiMeetLogger: value: '[966c8872-69ce-43c7-a78c-51edf4994e08@jitsi.ethelcare.com](mailto:966c8872-69ce-43c7-a78c-51edf4994e08@jitsi.ethelcare.com)/wh9dAodb',
E/JitsiMeetLogger: ownerElement: [Circular] },
E/JitsiMeetLogger: _ownerElement: [Circular],
E/JitsiMeetLogger: length: 5 },
E/JitsiMeetLogger: childNodes:
E/JitsiMeetLogger: { '0':
E/JitsiMeetLogger: { _nsMap: {},
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'error',
E/JitsiMeetLogger: tagName: 'error',
E/JitsiMeetLogger: namespaceURI: 'jabber:client',
E/JitsiMeetLogger: localName: 'error',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 334,
E/JitsiMeetLogger: firstChild: [Object],
E/JitsiMeetLogger: lastChild: [Object] },
E/JitsiMeetLogger: length: 1 },
E/JitsiMeetLogger: ownerDocument:
E/JitsiMeetLogger: { implementation: { _features: {} },
E/JitsiMeetLogger: childNodes: { '0': [Object], length: 1 },
E/JitsiMeetLogger: doctype: null,
E/JitsiMeetLogger: documentURI: undefined,
E/JitsiMeetLogger: documentElement:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: ownerDocument: [Circular],
E/JitsiMeetLogger: nodeName: 'body',
E/JitsiMeetLogger: tagName: 'body',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger: localName: 'body',
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 1,
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild: [Object] },
E/JitsiMeetLogger: firstChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: ownerDocument: [Circular],
E/JitsiMeetLogger: nodeName: 'body',
E/JitsiMeetLogger: tagName: 'body',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger: localName: 'body',
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 1,
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild: [Object] },
E/JitsiMeetLogger: lastChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: ownerDocument: [Circular],
E/JitsiMeetLogger: nodeName: 'body',
E/JitsiMeetLogger: tagName: 'body',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger: localName: 'body',
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 1,
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild: [Object] },
E/JitsiMeetLogger: _inc: 35 },
E/JitsiMeetLogger: nodeName: 'iq',
E/JitsiMeetLogger: tagName: 'iq',
E/JitsiMeetLogger: namespaceURI: 'jabber:client',
E/JitsiMeetLogger: localName: 'iq',
E/JitsiMeetLogger: parentNode:
E/JitsiMeetLogger: { _nsMap:
E/JitsiMeetLogger: { '': 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger: stream: 'http://etherx.jabber.org/streams' },
E/JitsiMeetLogger: attributes:
E/JitsiMeetLogger: { '0': [Object],
E/JitsiMeetLogger: '1': [Object],
E/JitsiMeetLogger: '2': [Object],
E/JitsiMeetLogger: _ownerElement: [Circular],
E/JitsiMeetLogger: length: 3 },
E/JitsiMeetLogger: childNodes: { '0': [Circular], '1': [Object], '2': [Object], length: 2 },
E/JitsiMeetLogger: ownerDocument:
E/JitsiMeetLogger: { implementation: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: doctype: null,
E/JitsiMeetLogger: documentURI: undefined,
E/JitsiMeetLogger: documentElement: [Circular],
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild: [Circular],
E/JitsiMeetLogger: _inc: 35 },
E/JitsiMeetLogger: nodeName: 'body',
E/JitsiMeetLogger: tagName: 'body',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger: localName: 'body',
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: parentNode:
E/JitsiMeetLogger: { implementation: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: doctype: null,
E/JitsiMeetLogger: documentURI: undefined,
E/JitsiMeetLogger: documentElement: [Circular],
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild: [Circular],
E/JitsiMeetLogger: _inc: 35 },
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 1,
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'iq',
E/JitsiMeetLogger: tagName: 'iq',
E/JitsiMeetLogger: namespaceURI: 'jabber:client',
E/JitsiMeetLogger: localName: 'iq',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: [Circular],
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 529,
E/JitsiMeetLogger: firstChild: [Object],
E/JitsiMeetLogger: lastChild: [Object] } },
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling:
E/JitsiMeetLogger: { _nsMap: { '': 'jabber:client' },
E/JitsiMeetLogger: attributes:
E/JitsiMeetLogger: { '0': [Object],
E/JitsiMeetLogger: '1': [Object],
E/JitsiMeetLogger: '2': [Object],
E/JitsiMeetLogger: '3': [Object],
E/JitsiMeetLogger: '4': [Object],
E/JitsiMeetLogger: _ownerElement: [Circular],
E/JitsiMeetLogger: length: 5 },
E/JitsiMeetLogger: childNodes: { '0': [Object], length: 1 },
E/JitsiMeetLogger: ownerDocument:
E/JitsiMeetLogger: { implementation: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: doctype: null,
E/JitsiMeetLogger: documentURI: undefined,
E/JitsiMeetLogger: documentElement: [Object],
E/JitsiMeetLogger: firstChild: [Object],
E/JitsiMeetLogger: lastChild: [Object],
E/JitsiMeetLogger: _inc: 35 },
E/JitsiMeetLogger: nodeName: 'iq',
E/JitsiMeetLogger: tagName: 'iq',
E/JitsiMeetLogger: namespaceURI: 'jabber:client',
E/JitsiMeetLogger: localName: 'iq',
E/JitsiMeetLogger: parentNode:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'body',
E/JitsiMeetLogger: tagName: 'body',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger: localName: 'body',
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: parentNode: [Object],
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 1,
E/JitsiMeetLogger: firstChild: [Circular],
E/JitsiMeetLogger: lastChild: [Circular] },
E/JitsiMeetLogger: previousSibling: [Circular],
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 529,
E/JitsiMeetLogger: firstChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: {},
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'query',
E/JitsiMeetLogger: tagName: 'query',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/disco#info',
E/JitsiMeetLogger: localName: 'query',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 722 },
E/JitsiMeetLogger: lastChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: {},
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'query',
E/JitsiMeetLogger: tagName: 'query',
E/JitsiMeetLogger: namespaceURI: 'http://jabber.org/protocol/disco#info',
E/JitsiMeetLogger: localName: 'query',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 722 } },
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 142,
E/JitsiMeetLogger: firstChild:
E/JitsiMeetLogger: { _nsMap: {},
E/JitsiMeetLogger: attributes: { '0': [Object], _ownerElement: [Circular], length: 1 },
E/JitsiMeetLogger: childNodes: { '0': [Object], '1': [Object], '2': [Object], length: 3 },
E/JitsiMeetLogger: ownerDocument:
E/JitsiMeetLogger: { implementation: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: doctype: null,
E/JitsiMeetLogger: documentURI: undefined,
E/JitsiMeetLogger: documentElement: [Object],
E/JitsiMeetLogger: firstChild: [Object],
E/JitsiMeetLogger: lastChild: [Object],
E/JitsiMeetLogger: _inc: 35 },
E/JitsiMeetLogger: nodeName: 'error',
E/JitsiMeetLogger: tagName: 'error',
E/JitsiMeetLogger: namespaceURI: 'jabber:client',
E/JitsiMeetLogger: localName: 'error',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 334,
E/JitsiMeetLogger: firstChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: {},
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'not-acceptable',
E/JitsiMeetLogger: tagName: 'not-acceptable',
E/JitsiMeetLogger: namespaceURI: 'urn:ietf:params:xml:ns:xmpp-stanzas',
E/JitsiMeetLogger: localName: 'not-acceptable',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: [Object],
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 355 },
E/JitsiMeetLogger: lastChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: {},
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'session-invalid',
E/JitsiMeetLogger: tagName: 'session-invalid',
E/JitsiMeetLogger: namespaceURI: 'http://jitsi.org/protocol/focus',
E/JitsiMeetLogger: localName: 'session-invalid',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: [Object],
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 458 } },
E/JitsiMeetLogger: lastChild:
E/JitsiMeetLogger: { _nsMap: {},
E/JitsiMeetLogger: attributes: { '0': [Object], _ownerElement: [Circular], length: 1 },
E/JitsiMeetLogger: childNodes: { '0': [Object], '1': [Object], '2': [Object], length: 3 },
E/JitsiMeetLogger: ownerDocument:
E/JitsiMeetLogger: { implementation: [Object],
E/JitsiMeetLogger: childNodes: [Object],
E/JitsiMeetLogger: doctype: null,
E/JitsiMeetLogger: documentURI: undefined,
E/JitsiMeetLogger: documentElement: [Object],
E/JitsiMeetLogger: firstChild: [Object],
E/JitsiMeetLogger: lastChild: [Object],
E/JitsiMeetLogger: _inc: 35 },
E/JitsiMeetLogger: nodeName: 'error',
E/JitsiMeetLogger: tagName: 'error',
E/JitsiMeetLogger: namespaceURI: 'jabber:client',
E/JitsiMeetLogger: localName: 'error',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 334,
E/JitsiMeetLogger: firstChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: {},
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'not-acceptable',
E/JitsiMeetLogger: tagName: 'not-acceptable',
E/JitsiMeetLogger: namespaceURI: 'urn:ietf:params:xml:ns:xmpp-stanzas',
E/JitsiMeetLogger: localName: 'not-acceptable',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: null,
E/JitsiMeetLogger: nextSibling: [Object],
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 355 },
E/JitsiMeetLogger: lastChild:
E/JitsiMeetLogger: { _nsMap: [Object],
E/JitsiMeetLogger: attributes: [Object],
E/JitsiMeetLogger: childNodes: {},
E/JitsiMeetLogger: ownerDocument: [Object],
E/JitsiMeetLogger: nodeName: 'session-invalid',
E/JitsiMeetLogger: tagName: 'session-invalid',
E/JitsiMeetLogger: namespaceURI: 'http://jitsi.org/protocol/focus',
E/JitsiMeetLogger: localName: 'session-invalid',
E/JitsiMeetLogger: parentNode: [Circular],
E/JitsiMeetLogger: previousSibling: [Object],
E/JitsiMeetLogger: nextSibling: null,
E/JitsiMeetLogger: lineNumber: 1,
E/JitsiMeetLogger: columnNumber: 458 } } }

**Comment by saghul** [comment]
That seems to be part of an error. Have you made sure the meeting was left properly?

**Comment by aymanayyad19** [comment]
My code is :
`

@AndroidEntryPoint
class VideoCallActivity : JitsiMeetActivity() {

    private val viewModel: VideoCallActivityViewModel by viewModels()

    private lateinit var jitsiMeetView: JitsiMeetView

    private lateinit var broadcastReceiver: BroadcastReceiver

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        JitsiMeetActivityDelegate.onActivityResult(
            this@VideoCallActivity,
            requestCode,
            resultCode,
            data
        )
    }
    //init Jitsi view with option on OnCreate 
    jitsiMeetView = JitsiMeetView(this@VideoCallActivity)

        val options = JitsiMeetConferenceOptions.Builder()
            .setServerURL(URL(BuildConfig.JITSI_URL))
            .setToken(getToken())
            .setRoom(getRoomId())
            .setFeatureFlag("meeting-name.enabled", false)
            .setFeatureFlag("meeting-password.enabled", false)
            .setFeatureFlag("toolbox.alwaysVisible", true)
            .setFeatureFlag("add-people.enabled", false)
            .setFeatureFlag("calendar.enabled", false)
            .setFeatureFlag("chat.enabled", false)
            .setFeatureFlag("invite.enabled", false)
            .setFeatureFlag("kick-out.enabled", false)
            .setFeatureFlag("live-streaming.enabled", false)
            .setFeatureFlag("raise-hand.enabled", false)
            .setFeatureFlag("video-share.enabled", false)
            .setFeatureFlag("filmstrip.enabled", false)
            .setFeatureFlag("tile-view.enabled", true)
            .setFeatureFlag("overflow-menu.enabled", false)
            .setFeatureFlag("conference-timer.enabled", false)
            .build()

        jitsiMeetView.join(options)

        setContentView(jitsiMeetView)
        //end init
        
        //on Activity Destroy 
          override fun onDestroy() {

        jitsiMeetView.leave()

        getRoomId()?.let { roomId ->
            viewModel.notifyCallEnd(roomId)
        }

        jitsiMeetView.dispose()
        JitsiMeetActivityDelegate.onHostDestroy(this@VideoCallActivity)



        super.onDestroy()
    }
    //end on Destroy
    
      override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        JitsiMeetActivityDelegate.onNewIntent(intent)
    }
    
    
    override fun onResume() {
        super.onResume()
        JitsiMeetActivityDelegate.onHostResume(this@VideoCallActivity)
        viewModel.stopRingtone()
    }

    override fun onStop() {
        super.onStop()
        JitsiMeetActivityDelegate.onHostPause(this@VideoCallActivity)
    }
`

**Comment by saghul** [comment]
Why are you not using JitsiMeetActivity?

**Comment by aymanayyad19** [comment]
I use it as a parent 
`class VideoCallActivity : JitsiMeetActivity() {`
with JitsiMeetView

**Comment by saghul** [comment]
Please put the entire logcat in a gist.
