### ISSUE TITLE
Can't access user functions easily for any user underneath the room name

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#10946]
### Description:

Since the Jitsi layout changes, you can't access the three dots for a particular user (like to mute or private message them) easily due to the room name and LIVE label being in the way. 

I assume this would be fixed just by making z-index for the three dots to be greater than the z-index of the room name and LIVE label. 

### Steps to reproduce:

1. Tile mode, and have a bunch of people in the room.
2. Try access the 3 dots for a particular user who appears right near the room name.

### Expected behavior:

The three dots for a particular user should appear above the room name so you can click on them easily.

### Actual behavior:

Very hard to click the 3 dots that is hidden by the room name and LIVE label.
![Capture](https://user-images.githubusercontent.com/67055226/153546828-cee73ab5-48be-40ca-b1ba-3c551d732979.PNG)

### Server information:

- Jitsi Meet version: jitsi-meet 1.0.5818

**Comment by saghul** [comment]
Yep, we've known this for a while and are working on design changes to address it.

**Comment by zon3d** [comment]
Ok thank you!
