### ISSUE TITLE
The image in README.md is too large

### ISSUE THREAD

**Issue by farooqkz** [jitsi/jitsi-meet#10952]
### Description:

The image in README.md is too large

### Steps to reproduce:
:)

### Expected behavior:

The image much be much more lightweight.

**Comment by saghul** [comment]
I don't see the problem. You are going to download it once and then it will be cached. Compared with all dependencies you need to install it's most likely in rounding error territory.

**Comment by farooqkz** [comment]
> I don't see the problem. You are going to download it once and then it will be cached. Compared with all dependencies you need to install it's most likely in rounding error territory.

The problem's not for those who wanna clone the repo and install but for those who want to have a quick look at README.md and learn about the project perhaps because they somehow have found the repository.

Also for me it takes ages for it to download so it doesn't get to the cache thing you are talking about anytime soon. I believe it is the same for many other users too. Surely not all but a majority.
