### ISSUE TITLE
Disabling logging is not working!

### ISSUE THREAD

**Issue by artknight** [jitsi/jitsi-meet#10962]
### Description:

I have tried disabling all the logging in production by setting these settings in the `logging_config.js`

```
var loggingConfig = {
    // default log level for the app and lib-jitsi-meet
    defaultLogLevel: 'error',

    // Option to disable LogCollector (which stores the logs on CallStats)
    disableLogCollector: true,

    // The following are too verbose in their logging with the
    // {@link #defaultLogLevel}:
    'modules/RTC/TraceablePeerConnection.js': 'info',
    'modules/statistics/CallStats.js': 'info',
    'modules/xmpp/strophe.util.js': 'log'
};

```

However, I am still seeing a LOT of non-error logging in the browser console

<img width="1185" alt="Screen Shot 2022-02-14 at 2 09 37 PM" src="https://user-images.githubusercontent.com/157762/153930043-7e1f586f-015c-495f-a9a4-4a7b78eeaa76.png">

### Steps to reproduce:

1. start a conference and see the logging in the browser console

### Expected behavior:

Only error logs are shown

### Actual behavior:

All logs and user messages are shown

### Server information:

- Jitsi Meet version: 2.0.6826
- Operating System: Ubuntu 20.04 LTS

### Client information:

- Browser / app version: Chrome Version 98.0.4758.80 (Official Build) (x86_64) 
- Operating System: MacOS Monterey

**Comment by NewEraCracker** [comment]
@artknight Notice the 3 override entries. Have you tried changing those from `'info'` and `'log'` to `'error'` (or `'warn'`) ?
