### ISSUE TITLE
PhaseScriptExecution [CP-User]\ Generate\ Specs

### ISSUE THREAD

**Issue by Mahesh160393** [jitsi/jitsi-meet#10968]
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/mahesh/Library/Developer/Xcode/DerivedData/jitsi-meet-gdtskvbfsklokyejubyevxbcngzn/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E00026150.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)
error: the path does not point to a valid framework: /Users/mahesh/Desktop/jisticaseverification/ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework

XCODE : 13.1
COCOPD : /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods.rb

NPM Version :

'jitsi-meet': '0.0.0',
  npm: '8.3.1',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'

**Comment by saghul** [comment]
Did you make any changes to our codebase?

**Comment by Mahesh160393** [comment]
@saghul yes.

**Comment by saghul** [comment]
How exactly are you building the SDK?

**Comment by Mahesh160393** [comment]
@saghul from this command. Using ZSH and BASH both terminal 

cd /Users/maheshmac/Desktop/Mahesh/iOS/Jist/

npm install 

cd ios 

pod install

cd /Users/maheshmac/Desktop/Mahesh/iOS/Jist/

mkdir -p /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out
xcodebuild clean \
  -workspace /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/jitsi-meet.xcworkspace \
  -scheme JitsiMeetSDK
xcodebuild archive \
  -workspace /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/jitsi-meet.xcworkspace \
  -scheme JitsiMeetSDK \
  -configuration Release \
  -sdk iphonesimulator \
  -destination='generic/platform=iOS Simulator' \
  -archivePath /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out/ios-simulator \
  VALID_ARCHS=x86_64 \
  ENABLE_BITCODE=NO \
  SKIP_INSTALL=NO \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive \
  -workspace /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/jitsi-meet.xcworkspace \
  -scheme JitsiMeetSDK \
  -configuration Release \
  -sdk iphoneos \
  -destination='generic/platform=iOS' \
  -archivePath /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out/ios-device \
  VALID_ARCHS=arm64 \
  ENABLE_BITCODE=NO \
  SKIP_INSTALL=NO \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
  -framework /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
  -framework /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out/ios-simulator.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
  -output /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out/JitsiMeetSDK.xcframework
cp -a /Users/maheshmac/Desktop/Mahesh/iOS/Jist/node_modules/react-native-webrtc/apple/WebRTC.xcframework /Users/maheshmac/Desktop/Mahesh/iOS/Jist/ios/sdk/out/

**Comment by saghul** [comment]
Are you on an M1 machine by any chance?

**Comment by Mahesh160393** [comment]
It's MacBook Air (13-inch, 2017). But I'm able to generate the SDK from https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_5870 this codebase.  On the same machine with the same react version.

**Comment by saghul** [comment]
Hum, that'd odd. I have no idea, I've never seen this error.

**Comment by Mahesh160393** [comment]
For the  https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_6865 codebase I'm getting this error

**Comment by saghul** [comment]
The SDK does not follow the same release cadence as the stable releases for web.

We haven't made a stable release in a while, so you should try to build master.

**Comment by Mahesh160393** [comment]
@saghul Downloaded master and still have same issue.

**Comment by saghul** [comment]
Thanks for trying. I'll give it a try when I get some time.

**Comment by Mahesh160393** [comment]
Thank you @saghul

**Comment by saghul** [comment]
I made some changes around this area yesterday on master. Can you give it another try? It worked for me.

**Comment by Mahesh160393** [comment]
Hello, @saghul today get the chance to check this issue. But the issue is still present. 

Master  --> SDK did not generate
2.0.7001 --> SDK did not generate
2.0.6865-2 --> SDK did not generate
2.0.6826 --> SDK Generated

**Comment by saghul** [comment]
Web stable releases are not related to mobile.

The current SDK stable release is ios-sdk-5.0.2, please try to build that tag.

**Comment by Mahesh160393** [comment]
Hello @saghul. Did the customization in react code. That's why I need to create the SDK from react code. Right now I'm using the 2.0.6826 repo and did the customization and am also able to generate the SDK. That is good for now. 

Thank you

**Comment by Rajibshrestha59** [comment]
> Are you on an M1 machine by any chance?

@saghul Hello I am getting this error and i am using Mac M1 chip

**Comment by saghul** [comment]
> Hello @saghul. Did the customization in react code. That's why I need to create the SDK from react code. Right now I'm using the 2.0.6826 repo and did the customization and am also able to generate the SDK. That is good for now. 
> 
> 
> 
> Thank you 

Good to hear!

**Comment by saghul** [comment]
> > Are you on an M1 machine by any chance?
> 
> 
> 
> @saghul Hello I am getting this error and i am using Mac M1 chip

M1 support has been added in SDK 5.
