### ISSUE TITLE
Jitsi starts choosing random endpoints to send through the video bridge

### ISSUE THREAD

**Issue by alan-albuquerque** [jitsi/jitsi-meet#10974]
### Description:

Some video streams are stopping working for no visible reason and I noticed looping behavior in the console log with a "New forwarded endpoints:" message.

For some reason, Jitsi starts choosing random endpoints to send through the video bridge when a user joins using Firefox (I only could reproduce with Firefox but I didn't test all possible browsers).

### Steps to reproduce:

1. Open https://meet.jit.si/ and join with 3 users using Chrome.
2. Open the console of the 3 Chrome users.
2. Open https://meet.jit.si/ and join with 3 users but using Firefox.
3. Start talking with some Firefox users as a regular meeting.
4. After a few minutes some of the Chrome users should experience the issue (videos going off and on randomly)

### Expected behavior:

All the videos should be on while the users turn them off.

### Actual behavior:

Some videos are turned on and off randomly without user interaction.

**Logs during the event:**

https://user-images.githubusercontent.com/5943786/154359606-c9e6acb9-3ed0-433d-9c8d-f747c6f3fa18.mp4

**My PC Network usage:** 

![2022-02-16_20-28](https://user-images.githubusercontent.com/5943786/154375454-17c50455-2791-4280-b737-7f43ea401ba2.png)

**My PC Network limits:** 

![2022-02-16_20-22](https://user-images.githubusercontent.com/5943786/154375441-a4e4f739-0fd4-4138-9476-4c03c1e8eff6.png)

**Chrome cam video info:**
![image](https://user-images.githubusercontent.com/5943786/154375796-2ffe0969-60db-4da3-9b0c-1852dac08a09.png)

**Firefox virtual cam video info:**
![image](https://user-images.githubusercontent.com/5943786/154375870-930ad0e9-2940-4c5a-9b1b-fd32629254cb.png)

### Server information:

**Meeting ID**: IronicFaultsPlaceBrisklyp

- Jitsi Meet version: the current version of https://meet.jit.si/
- Operating System: the current operating system of https://meet.jit.si/

### Client information:

- Browser / app version: 
  - Chrome: Version 98.0.4758.80 (Official Build) (64-bit)
  - Firefox: 97.0 (64-bit)

- Operating System: Ubuntu 20.04.3 LTS

### Additional information:

I had this issue originally on my own hosted server, but as I could reproduce on Jitsi production, I'm not sharing my server info here, let me know if needed.

Meeting ID: IronicFaultsPlaceBrisklyp

**Comment by jbg** [comment]
As shown in the the stats popups, your clients have 4% and 7% packet loss in the downstream direction.

This network instability is what is causing streams to be suspended.

If you can reproduce it also on meet.jit.si then it's a client side issue, not your server.

If you resolve the network problem then the streams will stop being suspended. If you're using Wi-Fi, you could test with an Ethernet cable - if that resolves it then you have an interference or signal strength issue. If you're already plugged in, it could be your router, or maybe your ISP is overselling and there is congestion.

In general for this type of question it's best to use community.jitsi.org and only file an issue if you determine that there is an actionable issue with Jitsi Meet itself.

**Comment by alan-albuquerque** [comment]
@jbg the issue I reported is happening in my own hosted server too, do you think some client is causing the issue to the other participants? Because sometimes I have call with more than 15 participants and nothing happens, but sometimes with less than 10 participants the issue happens.

**Comment by jbg** [comment]
I can only answer based on the info you provided, which is that both those clients in your screenshots have packet loss which will certainly be causing suspended streams. If you get the stats for the other clients I can answer for those. Suggest moving this discussion to the forums.

**Comment by alan-albuquerque** [comment]
Thanks I will do that
