### ISSUE TITLE
When i install master im getting error Execution failed for task ':react-native-gesture-handler:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by riyas145** [jitsi/jitsi-meet#10975]
Releasing Jitsi Meet SDK 5.0.0
Using file:/tmp/repo as the Maven repo
Pushing React Native 0.66.4 to the Maven repo
~/dhana/practice/jitstmeetpoc/node_modules/react-native/android/com/facebook/react/react-native/0.66.4 ~/dhana/practice/jitstmeetpoc
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy-file (default-cli) @ standalone-pom ---
Uploading to remote-repository: file:/tmp/repo/com/facebook/react/react-native/0.66.4/react-native-0.66.4.aar
Uploaded to remote-repository: file:/tmp/repo/com/facebook/react/react-native/0.66.4/react-native-0.66.4.aar (18 MB at 45 MB/s)
Uploading to remote-repository: file:/tmp/repo/com/facebook/react/react-native/0.66.4/react-native-0.66.4.pom
Uploaded to remote-repository: file:/tmp/repo/com/facebook/react/react-native/0.66.4/react-native-0.66.4.pom (4.3 kB at 4.3 MB/s)
Downloading from remote-repository: file:/tmp/repo/com/facebook/react/react-native/maven-metadata.xml
Downloaded from remote-repository: file:/tmp/repo/com/facebook/react/react-native/maven-metadata.xml (360 B at 60 kB/s)
Uploading to remote-repository: file:/tmp/repo/com/facebook/react/react-native/maven-metadata.xml
Uploaded to remote-repository: file:/tmp/repo/com/facebook/react/react-native/maven-metadata.xml (352 B)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.780 s
[INFO] Finished at: 2022-02-17T12:06:30+05:30
[INFO] ------------------------------------------------------------------------
~/dhana/practice/jitstmeetpoc
Pushing JSC r250230 to the Maven repo
~/dhana/practice/jitstmeetpoc/node_modules/jsc-android/dist/org/webkit/android-jsc/r250230 ~/dhana/practice/jitstmeetpoc
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy-file (default-cli) @ standalone-pom ---
Uploading to remote-repository: file:/tmp/repo/org/webkit/android-jsc/r250230/android-jsc-r250230.aar
Uploaded to remote-repository: file:/tmp/repo/org/webkit/android-jsc/r250230/android-jsc-r250230.aar (11 MB at 44 MB/s)
Uploading to remote-repository: file:/tmp/repo/org/webkit/android-jsc/r250230/android-jsc-r250230.pom
Uploaded to remote-repository: file:/tmp/repo/org/webkit/android-jsc/r250230/android-jsc-r250230.pom (452 B at 452 kB/s)
Downloading from remote-repository: file:/tmp/repo/org/webkit/android-jsc/maven-metadata.xml
Downloaded from remote-repository: file:/tmp/repo/org/webkit/android-jsc/maven-metadata.xml (338 B at 56 kB/s)
Uploading to remote-repository: file:/tmp/repo/org/webkit/android-jsc/maven-metadata.xml
Uploaded to remote-repository: file:/tmp/repo/org/webkit/android-jsc/maven-metadata.xml (338 B at 338 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.609 s
[INFO] Finished at: 2022-02-17T12:06:32+05:30
[INFO] ------------------------------------------------------------------------
~/dhana/practice/jitstmeetpoc
Building and publishing the Jitsi Meet SDK
~/dhana/practice/jitstmeetpoc/android ~/dhana/practice/jitstmeetpoc

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
28 actionable tasks: 28 up-to-date

> Configure project :app
WARNING:: The option setting 'android.enableDexingArtifactTransform.desugaring=false' is experimental.
The current default is 'true'.

> Task :sdk:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated

info Writing bundle output to:, /home/dhanasekaran/dhana/practice/jitstmeetpoc/android/sdk/build/generated/assets/react/release/index.android.bundle
info Done writing bundle output
info Copying 16 asset files
info Done copying assets

> Task :sdk:processReleaseManifest
/home/dhanasekaran/dhana/practice/jitstmeetpoc/android/sdk/src/main/AndroidManifest.xml:52:9-57:20 Warning:
        provider#com.reactnativecommunity.webview.RNCWebViewFileProvider@android:authorities was tagged at AndroidManifest.xml:52 to replace other declarations but no other declaration present

> Task :react-native-async-storage:compileReleaseJavaWithJavac
Note: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-background-timer:compileReleaseJavaWithJavac
Note: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/react-native-background-timer/android/src/main/java/com/ocetnik/timer/BackgroundTimerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-community_netinfo:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-device-info:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-reanimated:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-google-signin:compileReleaseJavaWithJavac
Note: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/@react-native-google-signin/google-signin/android/src/main/java/com/reactnativegooglesignin/RNGoogleSigninModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/@react-native-google-signin/google-signin/android/src/main/java/com/reactnativegooglesignin/RNGoogleSigninModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-gesture-handler:compileReleaseKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/dhanasekaran/.gradle/caches/transforms-3/1ffbb3a85398736c1d1592a503f099cb/transformed/jetified-kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/dhanasekaran/.gradle/caches/transforms-3/0d8fcb7da3628f9c7f0cf8355a509a13/transformed/jetified-kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/dhanasekaran/.gradle/caches/transforms-3/edbfc4cbec9dd0624275f334e0ade88c/transformed/jetified-kotlin-stdlib-1.5.20.jar (version 1.5)
    /home/dhanasekaran/.gradle/caches/transforms-3/dcec15d1d7d71cda63d30c7fd08aba01/transformed/jetified-kotlin-stdlib-common-1.5.20.jar (version 1.5)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (11, 22): Unresolved reference: common
e: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (17, 47): Unresolved reference: GestureHandlerStateManager
e: /home/dhanasekaran/dhana/practice/jitstmeetpoc/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.kt: (400, 3): 'setGestureHandlerState' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 59s
278 actionable tasks: 278 executed

**Comment by saghul** [comment]
<img width="1094" alt="Screenshot 2022-02-14 at 15 23 01" src="https://user-images.githubusercontent.com/317464/154428894-9b970dc3-2c28-40fc-b173-9a494878cf29.png">

Make sure your JAVA_HOME points to a installation with JDK 11. If you are using Android Studio's then make sure it uses the embedded one.

**Comment by riyas145** [comment]
yes now working can i copy that folder (tmp/repo) and make a build from windows ? or i have to publish into github if yes how can i publish do u have links to do that?
pls share that thanks

**Comment by saghul** [comment]
There is nothing special about publishing to GH, it's just the files. You can move that folder over to windows too.

**Comment by riyas145** [comment]
I was getting this error 

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeReleaseAssets'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:4.1.0.
     Required by:
         project :app
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:4.1.0.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/4.1.0/jitsi-meet-sdk-4.1.0.pom'.
            > Could not HEAD 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/4.1.0/jitsi-meet-sdk-4.1.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:4.1.0.
     Required by:
         project :app > project :bortolilucas_react-native-jitsimeet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:4.1.0.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/4.1.0/jitsi-meet-sdk-4.1.0.pom'.
            > Could not HEAD 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/4.1.0/jitsi-meet-sdk-4.1.0.pom'. Received status code 401 from server: Unauthorized
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 1m 36s

**Comment by saghul** [comment]
But that's your app isn't it? Have you correctly specified your maven repo URL?

**Comment by riyas145** [comment]
yeah in my project i have my local repo intro my build.gradle file

 url("$rootDir/../node_modules/repo")
 my repo location " node_modules/repo
 
 repo - contains two folders com and org
@saghul

**Comment by saghul** [comment]
The answer is right there in the error message. Adjust the compile SDK to match.
