### ISSUE TITLE
Release build Have crash error with jitsi local repo

### ISSUE THREAD

**Issue by riyas145** [jitsi/jitsi-meet#10979]
Process: com.i2global, PID: 19668
    com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:236)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)

**Comment by saghul** [comment]
What steps can someone follow to reproduce?

**Comment by riyas145** [comment]
My package.json 
this was working fine in debug mode when make release build app crashed immediately i tried with local maven repo and official maven repo please help to retrieve this error  

  implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true
     exclude group: 'com.facebook.react',module:'react-native-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-reanimated'
        exclude group: 'com.facebook.react',module:'react-native-gesture-handler'
        exclude group: 'com.facebook.react',module:'react-native-slider'
        exclude group: 'com.facebook.react',module:'react-native-screens'
        exclude group: 'com.facebook.react',module:'react-native-safe-area-context'
        exclude group: 'com.facebook.react',module:'react-native-video'
        exclude group: 'com.facebook.react',module:'react-native-google-signin'
     }

 "@bortolilucas/react-native-jitsimeet": "^1.3.3",
    "@react-native-async-storage/async-storage": "^1.15.15",
    "@react-native-community/slider": "^4.2.0",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^5.8.2",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^5.5.1",
    "axios": "^0.25.0",
    "formik": "^2.2.9",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-date-picker": "^4.1.3",
    "react-native-document-picker": "^8.0.0",
    "react-native-fbsdk-next": "^7.0.1",
    "react-native-flash-message": "^0.2.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-orientation-locker": "^1.4.0",
    "react-native-paper": "^4.11.2",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^1.9.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^3.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-video": "https://github.com/MatrixFrog/react-native-video#11ca8a6799f932a5f24da85dfe68c696ad13a753",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },

**Comment by saghul** [comment]
> "@bortolilucas/react-native-jitsimeet": "^1.3.3",

We don't maintain that package. You need to ask the author.
