### ISSUE TITLE
Prosody errors when jwt is random string without a dot

### ISSUE THREAD

**Issue by nosmicek** [jitsi/jitsi-meet#10970]
### Description:

When jitsi is configured with jwt auth and allowEmptyToken=false, when a user tries to go to url like https://< conference domain >/< roomname >?jwt=123 he doesn't get any error, is left in what appears to be empty room. There are errors in prosody log.

### Steps to reproduce:

1. Go to https://< conference domain >/< roomname >?jwt=123, notice no dot in jwt token
2. Check prosody logs
3. Check conference - no "Authentication failed" error in jitsi

### Expected behavior:

No errors in prosody, "Authentication failed" error notification in jitsi

### Actual behavior:

In prosody logs:
```
Feb 16 16:56:50 c2s55f1c52aeb70 error   Traceback[c2s]: /usr/lib/prosody/util/stanza.lua:54: invalid tag name: expected string, got nil
stack traceback:
        [C]: in function 'error'
        /usr/lib/prosody/util/stanza.lua:54: in function 'check_name'
        /usr/lib/prosody/util/stanza.lua:94: in function 'new_stanza'
        /usr/lib/prosody/util/stanza.lua:117: in function 'tag'
        /usr/lib/prosody/modules/mod_saslauth.lua:32: in function 'build_reply'
        /usr/lib/prosody/modules/mod_saslauth.lua:82: in function </usr/lib/prosody/modules/mod_saslauth.lua:69>
        (...tail calls...)
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (...tail calls...)
        /usr/lib/prosody/core/stanza_router.lua:142: in function 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:287: in function 'func'
        /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>

```
### Server information:

- Jitsi Meet version: latest stable

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

The problems seems to be in wrong response from jitsi-meet/resources/prosody-plugins/token/util.lib.lua, we fixed this internally by this patch snippet:

```
         pubKey = session.public_key;
     elseif self.asapKeyServer and session.auth_token ~= nil then
         local dotFirst = session.auth_token:find("%.");
-        if not dotFirst then return nil, "Invalid token" end
+        if not dotFirst then return false, "not-allowed", "Invalid token" end
         local header, err = json_safe.decode(basexx.from_url64(session.auth_token:sub(1,dotFirst-1)));
         if err then
             return false, "not-allowed", "bad token format";

```

**Comment by saghul** [comment]
Can you send a PR with the change?

**Comment by nosmicek** [comment]
I'm sorry, i cannot send a PR.

**Comment by saghul** [comment]
Might be a one liner, but we technically cannot take your change unless you sign the CLA or place your patch in the public domain.

**Comment by nosmicek** [comment]
my first PR to jitsi-meet, do i have to sign some CLA also? is it ok this way?

**Comment by saghul** [comment]
Yep you do need to sign it.
