### ISSUE TITLE
How to get participants info in android?

### ISSUE THREAD

**Issue by bhaviksoni12** [jitsi/jitsi-meet#10976]
Hello guys,

I have created a demo with iOS in which I am getting participants info using "retrieveParticipantsInfo" but I am not able to get in android. I am getting "PARTICIPANT_LEFT" event but not able to get "PARTICIPANTS_INFO_RETRIEVED".

Can somebody guide me how to get participants info?

Thank you in advance.

**Comment by iskugor** [comment]
@bhaviksoni12 did you find a solution?
