### ISSUE TITLE
Command `setParticipantVolume` doesn't seem to work

### ISSUE THREAD

**Issue by shravan-shandilya** [jitsi/jitsi-meet#10980]
Hello, I'm using `JitsiExternalMeetAPI` to join a meeting through my web widget. 

Here's my code:
```
import * as JitsiMeetExternalAPI from "../utils/external_api.js";

// options contains 'startSilent': false,
let api = new JitsiMeetExternalAPI("<domain>", "<options>");

api.addListener("videoConferenceJoined", () => {
  let host = api
    .getParticipantsInfo()
    .filter((participant) => participant.displayName === "Host");

  api.executeCommand("setParticipantVolume", {
    participantID: host.participantId,
    volume: 0,
  });
});
```
From my understanding, the expected behavior is that call will be joined and host's audio should be turned down to 0. But, that doesnt happen.

I have tried replacing `participantID` by `participantId`. It also doesnt seem to work.

Can someone please help if something is wrong with my code or understanding?

**Comment by izakgl** [comment]
You are not calling the command correctly. The function does not in fact expect an object as a parameter but rather 2 parameters, first being participantID as a string, and the second being volume as a number between 0 and 1: [Docs](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#setparticipantvolume)

In your case this would be:
```js
api.executeCommand("setParticipantVolume", host.participantId, 0);
```

**Comment by saghul** [comment]
@izakgl can you confirm it works that way?

**Comment by izakgl** [comment]
I tried on Firefox/Chrome on Windows and on Firefox/Chrome/Safari on MacOS. It works on all those browser. I am not able to test iPhone however, so I'm not sure about that one.

**Comment by shravan-shandilya** [comment]
Thanks for the help @izakgl. I have fixed my code, it's working now 🙏

**Comment by quidlab** [comment]
@shravan-shandilya have you tested it on iPhone and ipad? 
setParticipantVolume does not work on iOS in my implementation.

**Comment by shravan-shandilya** [comment]
@quidlab I didn't test this feature on iPhone/iPad.
