### ISSUE TITLE
Application sharing - missing context menu

### ISSUE THREAD

**Issue by piterq** [jitsi/jitsi-meet#10988]
### Description:

Sharing a selected window produces bad output - context menus are blinking or aren't visible at all.

### Steps to reproduce:

1. Click on "Start / Stop sharing your screen"
2. Select application to share.
3. Select something from context menu in the shared application.

### Expected behavior:

Context menu should be visible to all participants.

### Actual behavior:

Participants don't see context menu at all.

### Server information:

- Jitsi Meet version: current on-line version.
- Operating System: n/a

### Client information:

- Browser / app version: Chrome 98.0.4758.102 and Firefox 91.6.0 (both have the same issue)
- Operating System: Windows 11

### Additional information:

This issue occurs when I'm sharing "Total commander" application (dark theme). I've reproduced the same issue in 2 ERP applications (these applications use devexpress controls).
This issue doesn't occur when sharing full screen.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

There is nothing we can do about it, this is entirely handled in the browsers. You better check the browser bugtracker for similar issue and report it there. 

If you are doing the test on the same machine, try another one, do you repro there. It can be and something around the graphic card drivers ...
