### ISSUE TITLE
Endpoint to start streaming via API

### ISSUE THREAD

**Issue by turi4200** [jitsi/jitsi-meet#10995]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

Someway to start a streaming session in a given room via API.

**Comment by saghul** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#startrecording-1
