### ISSUE TITLE
IOS Screen Sharing with AudioInApp

### ISSUE THREAD

**Issue by zooperzhou** [jitsi/jitsi-meet#11008]
hello

now  IOS Screen Sharing is OK，but,the voice with otherapp like play music  or others can't share voice 

 case RPSampleBufferTypeAudioApp:------------not contains any code ,So I wonder how send voice CMSampleBufferRef to the meeting

**Comment by saghul** [comment]
That's correct we are not sharing any system audio.

**Comment by zooperzhou** [comment]
currently.I almost know how to send video data

> `var socketFilePath: String {
      let sharedContainer = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Constants.appGroupIdentifier)
        
        return sharedContainer?.appendingPathComponent("rtc_SSFD").path ?? ""
    }`

send the voice data as same? only different with "rtc_SSFD"?

**Comment by saghul** [comment]
I think you probably should use a different socket.

**Comment by zooperzhou** [comment]
previously,I use the same socket,and same file
`        case RPSampleBufferType.video:
            // very simple mechanism for adjusting frame rate by using every third frame
            frameCount += 1
//            if frameCount % 3 == 0 {
//                uploader?.send(sample: sampleBuffer)
//            }
            break
        case RPSampleBufferType.audioApp:
            uploader?.send(sample: sampleBuffer)
//            audiouploader?.send(sample: sampleBuffer)
            break`
only send audio,not video ,but it desn't work normaly.
now I don't know how to do
