### ISSUE TITLE
Found an issue when the user starts screen sharing in the mobile app and stops and tries to open his camera, the user in the browser cant see his video in p2p

### ISSUE THREAD

**Issue by zaki-vempower** [jitsi/jitsi-meet#11010]
### Steps to reproduce:

1. Open android/ios app and join the conference  p2p
2. start screensharing 
3. stop screen sharing 
4. Try to open your video cam
5. The user in the browser cant see the video of the user in the app

### Actual behavior:
when the user shares screen in android or ios  and tries to open his camera the user in the web cant see his video in p2p
The error =>  addRemoteStream failed: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.

![Screenshot from 2022-02-23 15-30-12](https://user-images.githubusercontent.com/64267273/155297434-8289d47e-a895-4982-ae22-78e2ea7170b3.png)

### Server information:

- Jitsi Meet version: main website idk what version its running on.
- Operating System:Ubuntu 20.04

### Client information:

- Browser / app version:
- Operating System: Chrome

### Additional information:

Thanks ,

**Comment by saghul** [comment]
Thanks for the report! @jallamsetty1 this sounds very close to what I told you yesterday. If you can take a look that would be great I also plan to do so tomorrow.

**Comment by jilson-johnson** [comment]
am having same issue

**Comment by saghul** [comment]
While it might manifest in the same way, it's unlikely to be the same. Please open a new issue and gather logs on both ends of the call.
