### ISSUE TITLE
"Meeting end" black screen blocking video call management

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#11012]
If we make repeated joins between different rooms then we regularly get such screen and can start the next conference before we close the app.

![IMG_1359](https://user-images.githubusercontent.com/1611869/155371797-45683fd0-47ca-4641-ba47-7fe63d37c5f6.PNG)

Also in the previous SDKs there was no such first screen in video navigation.
Not it looks like some empty first controller in navigation. After connection we get next stack navigation screen with video conference.

When we leave video room then this "end conf" screen stays instead of the video conference screen.

**Comment by saghul** [comment]
What exact steps are you following? How are you triggering the multiple joins?

**Comment by saghul** [comment]
What SDK were you using previously? [2.0.6865-2](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_6865) is not an SDK version. Are you using the `readyToClose` event?

**Comment by themoonlitknight** [comment]
I was using that version built for iOS.

No, I'm not using the `readyToClose` event.

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#breaking-changes

**Comment by saghul** [comment]
@Calinteodor FYI We need to consider this, when adding the connecting screen.

**Comment by saghul** [comment]
The meeting ended screen has since been removed.
