### ISSUE TITLE
Etherpad does not work with breakout rooms 

### ISSUE THREAD

**Issue by fmuscetra** [jitsi/jitsi-meet#11014]
### Description:

We are experiencing that when a participant enters a breakout room and launches Etherpad, he will get a blank screen and is even not able to close it. It seems, that the menu item is not working anymore. This failure also exists after leaving the breakout room. For all the other participants (outside the breakout room) Etherpad works fine.
Even if a participant only enters and leaves a breakout room (without starting Etherpad) it will not work anymore.
It seems, that entering a breakout room will break Etherpad functionality in general.

### Steps to reproduce:

1. A participant enters a breakout room and launches Etherpad
2. He gets a blank screen and is even not able to close it
3. The menu item does not work anymore
4. Same problem when the user leaves the breakout room
5. For all the other participants (outside the breakout room) Etherpad works fine

### Expected behavior:

Etherpad should work in breakout rooms and main room without problems.

### Actual behavior:

Blank screen when the problem happens and Jitsi Meet menu not reactive.

### Server information:

- Jitsi Meet version: 2.0.6865-2
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chrome  v97
- Operating System: Win10

**Comment by jvkassi** [comment]
Hello, is there any hints ? How can we bypass this ?

**Comment by fmuscetra** [comment]
In our current configuration, one Etherpad document is shared with all participants. So it is impossible to have a document for the breakout room and another for the main room. We are not investigating more on this topic.

**Comment by saghul** [comment]
Hey there. This is indeed not high on the priority list. Any PRs with fixes would be very welcome of course!
