### ISSUE TITLE
Chrome on IOS, not able to use microphone at all

### ISSUE THREAD

**Issue by donnierisk** [jitsi/jitsi-meet#11029]
### Description:
Using iphone IOS 15.3.1, safari jitsi web app works fine. but latest chrome version doesn't request for your microphone at all so there is no way to unmute yourself. we even tried adding startWithAudioMuted=false config in the URL and still no luck. this is on the latest version of jitsi.

### Steps to reproduce:

1. Open Chrome on IOS device
2. Visit https://meet.jit.si/VerticalArraysGazeSomewhat
3. Only requests for video, not microphone

### Expected behavior:
Should be able to use microphone and speak.

### Actual behavior:

No way to speak

### Server information:

- Jitsi Meet version: Latest online at meet.jitsi
- Operating System: IOS 15.3.1

### Client information:

Google Chrome	98.0.4758.97 (Official Build) stable (64-bit) 
Revision	d3dcbbeaf7c3...
OS	iOS
User agent	Mozilla/5.0 (iPhone; CPU iPhone OS 15_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/98.0.4758.97 Mobile/15E148 Safari/604.1

### Additional information:

![Image from iOS (1) (1)](https://user-images.githubusercontent.com/17927429/155712588-4918368f-ede5-4cf7-8a48-9fc937816a82.jpg)

**Comment by saghul** [comment]
Cannot reproduce, I get the prompts just fine. Can you check if you have removed the permission in Settings? In that case iOS no longer asks.

![IMG_0006 2](https://user-images.githubusercontent.com/317464/155714648-cfc23c40-f35d-492b-9f32-aefc50913c62.PNG)
![IMG_0005](https://user-images.githubusercontent.com/317464/155714664-92b0d0ab-6cc1-4a7f-9d96-2d434c345817.PNG)
![IMG_0004](https://user-images.githubusercontent.com/317464/155714667-e3b1358b-7bdd-4bb2-bb10-91e84e27ab73.PNG)

**Comment by donnierisk** [comment]
You're right, apologies. chrome microphone permissions were disabled, i will close the comment.
