### ISSUE TITLE
Pre-join page camera layout hides major part of the video

### ISSUE THREAD

**Issue by humanamburu** [jitsi/jitsi-meet#11027]
### Description:
We are trying to have Jitsi Call embedded into the page as a widget and unfortunately, the pre-join camera layout is broken and hides a major part of the video output, and makes the pre-join page not usable.

### Steps to reproduce:
1. Open the pre-join page and scale it to 820x520
2. Video camera image is cropped 

### Expected behavior:

Users can see the video correctly, possibly as columns instead of rows.

### Actual behavior:

<img width="858" alt="Screenshot 2022-02-25 at 11 32 33" src="https://user-images.githubusercontent.com/14282222/155701497-fbd49bb8-bcf4-425e-90fa-1138f400375f.png">

<img width="852" alt="Screenshot 2022-02-25 at 11 32 42" src="https://user-images.githubusercontent.com/14282222/155701444-09b60194-feef-413d-bd24-bbfc74a3c4c5.png">

### Server information:

- Jitsi Meet version:  2.0.6865
- Operating System: Linux

### Client information:

Browser / app version: Chrome v98
Operating System: MacOS

**Comment by saghul** [comment]
The cutting point is at 1000, if you go above it it will show columns.

**Comment by humanamburu** [comment]
@saghul thanks for the suggestion, but we can't fix the size of the widget and want to support sizes less than 1k.

Seems like it should use columns layout for sizes less than 1k?

**Comment by saghul** [comment]
Maybe try to change the value here and find one that makes more sense? https://github.com/jitsi/jitsi-meet/blob/1d275e19761d8ff5986ba45b147df239f960402b/css/premeeting/_premeeting-screens.scss#L157 we'd take a PR.

**Comment by humanamburu** [comment]
@saghul thanks for referring, I'll submit a PR soon!
