### ISSUE TITLE
Allowing to stream to a Jitsi meeting through rtmp ?

### ISSUE THREAD

**Issue by jcelerier** [jitsi/jitsi-meet#11020]
Hello,
is there any way to send a RTMP stream to a jitsi instance / meeting, just like it is possible to stream to twitch, youtube, etc. without requiring any kind of virtual camera / fake browser / anything like this ?

Ideally, just sending a stream to, say, rtmp://meet.jit.si/my_chatroom should make a new participant appear with the A/V data of the stream.

**Comment by saghul** [comment]
We don't provide RTMP ingestion. I think you could accomplish what you need with `gst-meet` and using an RTMP feed as the audio / input pipelines: https://github.com/avstack/gst-meet

**Comment by zsinba** [comment]
> 
There is no readily available open source solution for pushing RTMP to Jitsi Meet. I tried to implement this feature by converting RTMP to WEBRTC and then WEBRTC to Jitsi.

https://youtu.be/T8hdn2np8W8

**Comment by saghul** [comment]
I literally linked one in my comment: https://github.com/avstack/gst-meet -- With that and a gstreamer pipeline it can be done.

**Comment by zsinba** [comment]
> I literally linked one in my comment: https://github.com/avstack/gst-meet -- With that and a gstreamer pipeline it can be done.

Can you record a running flow? It's best to use Docker

**Comment by jcelerier** [comment]
@zsinba having to adding a whole gstreamer-based abstraction layer in a separate process between my rtmp packets and jitsi is really not a solution for various reasons:

- I can't ask my users to install this and run the pipelines themselves (they are non technical) ; adding who knows how many megabytes to download to my software just for some UI which would wrap it and make this feature accessible is a no-go
- things being done in separate processes makes deployment much more complicated in "restricted" environments, e.g. windows store
-  gstreamer would likely add some latency overhead which does not work for the use cases I'm often faced with (live music & visuals) 

webrtc sadly is not good either, now we have to worry about signaling, STUN TURN and whatnot when we just have a very basic OS process which can send standard A/V packets over the internet to a known public IP address ; and I have yet to see a low-latency webrtc implementation (less than 15ms for getting an image from A to B would be my threshold assuming A and B are on gigabit fiber links with 1-2ms latency to the ISP)

**Comment by saghul** [comment]
I think this could be done as a backend, which uses that library and ingests the RTMP feed and joins the meeting.

This doesn't need to be available from within the Jitsi Meet UI itself.

Adding it to the UI would mean we'd need to decide if that is something we want to support and I'm not sure we would at this stage.

**Comment by zsinba** [comment]
> @zsinba由于各种原因，必须在我的 rtmp 数据包和 jitsi 之间的单独进程中添加整个基于 gstreamer 的抽象层实际上不是一个解决方案：
> 
> * 我不能要求我的用户安装它并自己运行管道（它们是非技术性的）；添加谁知道要下载多少兆字节到我的软件只是为了一些可以包装它并使此功能可访问的 UI 是不行的
> * 在单独的进程中完成的事情使得部署在“受限”环境中变得更加复杂，例如 Windows 商店
> * gstreamer 可能会增加一些延迟开销，这不适用于我经常遇到的用例（现场音乐和视觉效果）
> 
> 遗憾的是，webrtc 也不好，现在我们不得不担心信令、STUN TURN 等等，因为我们只有一个非常基本的操作系统进程，可以通过互联网将标准 A/V 数据包发送到已知的公共 IP 地址；而且我还没有看到低延迟的 webrtc 实现（假设 A 和 B 位于千兆光纤链路上，到 ISP 的延迟为 1-2 毫秒，那么从 A 到 B 获取图像的时间小于 15 毫秒将是我的阈值）

Do you want to do it in the 10ms range from RTMP to Jitsi? Did you do it?
I have tried to get from RTMP to Jitsi Meet. The delay is over 200ms as shown on the web page. Instead of using GST, I used the server-side conversion service to convert RTMP to WEBRTC and then add it to Jitsi Meet

**Comment by zsinba** [comment]
> @zsinba having to adding a whole gstreamer-based abstraction layer in a separate process between my rtmp packets and jitsi is really not a solution for various reasons:
> 
> * I can't ask my users to install this and run the pipelines themselves (they are non technical) ; adding who knows how many megabytes to download to my software just for some UI which would wrap it and make this feature accessible is a no-go
> * things being done in separate processes makes deployment much more complicated in "restricted" environments, e.g. windows store
> * gstreamer would likely add some latency overhead which does not work for the use cases I'm often faced with (live music & visuals)
> 
> webrtc sadly is not good either, now we have to worry about signaling, STUN TURN and whatnot when we just have a very basic OS process which can send standard A/V packets over the internet to a known public IP address ; and I have yet to see a low-latency webrtc implementation (less than 15ms for getting an image from A to B would be my threshold assuming A and B are on gigabit fiber links with 1-2ms latency to the ISP)

If you just transmit and collaborate with audio, I think you can do that. This can be achieved even without using Webrtc, using only socket. IO communication. Because it transmits less data, and does not need too much coding and decoding computation. If it's a video, I'm afraid it doesn't meet that requirement.

> @zsinba having to adding a whole gstreamer-based abstraction layer in a separate process between my rtmp packets and jitsi is really not a solution for various reasons:
> 
> * I can't ask my users to install this and run the pipelines themselves (they are non technical) ; adding who knows how many megabytes to download to my software just for some UI which would wrap it and make this feature accessible is a no-go
> * things being done in separate processes makes deployment much more complicated in "restricted" environments, e.g. windows store
> * gstreamer would likely add some latency overhead which does not work for the use cases I'm often faced with (live music & visuals)
> 
> webrtc sadly is not good either, now we have to worry about signaling, STUN TURN and whatnot when we just have a very basic OS process which can send standard A/V packets over the internet to a known public IP address ; and I have yet to see a low-latency webrtc implementation (less than 15ms for getting an image from A to B would be my threshold assuming A and B are on gigabit fiber links with 1-2ms latency to the ISP)

If you just transmit and collaborate with audio, I think you can do that. This can be achieved even without using Webrtc, using only socket. IO communication. Because it transmits less data, and does not need too much coding and decoding computation. If it's a video, I'm afraid it doesn't meet that requirement.
