### ISSUE TITLE
Screen sharing button in audio only mode

### ISSUE THREAD

**Issue by c0m1t** [jitsi/jitsi-meet#11032]
### Description:

When user is in audio only mode and clicks on screen sharing button, there is no notification or whatsoever indicating that the user cannot start the share screen in audio only mode. So user may not understand why the share screen button is not working.

There's only an error logged in the console:

```
[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: No screensharing in audio only mode Script: null Line: null Column: null StackTrace:  n/a
```

### Steps to reproduce:

1. Open performance settings
2. Adjust for best performance
3. Click on screen sharing button

### Expected behavior:

I expect one of the followings:
- When audio only mode is enabled, starting the camera would result in changing the performance settings and audio only mode ends. So licking on screen sharing button should exit the audio only mode just like starting the camera, so user can start screen sharing.
- Clicking on the screen sharing button must notify the user that he/she cannot start screen sharing in audio only mode.
- It should be disabled.

### Actual behavior:

Throws an error, without telling the user why screen sharing can not be started.

**Comment by saghul** [comment]
Hum, the bandwidth saving mode should allow you to share the screen, we'll take a look at this.

**Comment by c0m1t** [comment]
I just took a look at the code, you would show a dialog when user is in audio only mode. But the issue is `audioOnlySharing` is `undefined`, so the code skips the if block and tries to toggle the screen share, hence it throws an error.

``` js
export function startScreenShareFlow(enabled: boolean) {
    return (dispatch: Object => Object, getState: () => any) => {
        const state = getState();
        const audioOnlySharing = isAudioOnlySharing(state);

        // If we're in an audio screen sharing session, warn the user.
        if (audioOnlySharing) {
            dispatch(openDialog(ShareMediaWarningDialog, { _isAudioScreenShareWarning: false }));

            return;
        }

        dispatch(toggleScreensharing(enabled));
    };
}

export function isAudioOnlySharing(state: Object) {
    return isScreenAudioShared(state) && !isScreenVideoShared(state);
}

export function isScreenAudioShared(state: Object) {
    return state['features/screen-share'].isSharingAudio; // <------ This returns `undefined`
}
```

When user enters audio only mode, `state['features/screen-share'].isSharingAudio` is `undefined`.

**Comment by c0m1t** [comment]
Removing 

``` js
        if (this.isAudioOnly()) {
            return Promise.reject('No screensharing in audio only mode');
        }
```

in `toggleScreenSharing` function in `conference.js` fixes the issue.
