### ISSUE TITLE
Room crashes when connecting 3 participants

### ISSUE THREAD

**Issue by roman04204** [jitsi/jitsi-meet#11043]
Created a conference: meet.jit.si

The room falls when connecting 3 participants.
Browser: chrome 98.0.4758.102

I also tried to deploy my server and the same situation ...

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Can you upload the js console logs from the browser that experience the problem?

**Comment by roman04204** [comment]
Sorry ((
I am attaching the log

[meet.server-work.ru-1646057992072.log](https://github.com/jitsi/jitsi-meet/files/8153974/meet.server-work.ru-1646057992072.log)

**Comment by damencho** [comment]
This is no meet.jit.si but some other server. And that server seems to be running an older version of jitsi-meet which is no longer supported with new chrome versions and also the websocket connection to jvb is not working.

**Comment by roman04204** [comment]
Yes, sorry, this is my installation, installed today, but on Meet.jit.si the same error

**Comment by roman04204** [comment]
jitsi-meet is already the newest version (2.0.6865-2).
Problem persists (

**Comment by damencho** [comment]
Hu, that is strange, I have no problem using latest chrome on meet.jit.si, let me check your logs again. 
Can you upload logs from meet.jit.si when you experience the problem.

**Comment by damencho** [comment]
Have you tried on another computer in the same network? Or in incognito mode?

**Comment by roman04204** [comment]
Yes, I tried in Incognito mode, through different providers and from different PCs
with the following servers:
meet.jit.si
meet.server-work.ru (Ubuntu 20.04) (latest install 2.0.6865-2)
meet-test.f1group.ru (Debian 10) (old install)

It all started on February 27, 2022

**Comment by roman04204** [comment]
[meet.jit.si-1646061776233.log](https://github.com/jitsi/jitsi-meet/files/8154444/meet.jit.si-1646061776233.log)

**Comment by roman04204** [comment]
If necessary, I can remove some logs from the server or remove a video of the problem

Previously, there were no such problems, and then 2 independent installations of different versions, on different providers, through different PCs suddenly stopped working

**Comment by roman04204** [comment]
3rd participant joins, everyone has only their own video, after some time it reboots.  If Any of the 3 comes out, then everything works between the 2 remaining ones.

**Comment by roman04204** [comment]
If necessary, I can record a video of the problem tomorrow

**Comment by damencho** [comment]
Nope, video is not needed, thank you. Please wait for the reload screen to appear and then collect the meet.jit.si logs and upload them here. 
You can enable preserve logs from the console settings in chrome so you don't lose them if could not manage to save them before the reload happens.

**Comment by jallamsetty1** [comment]
> If necessary, I can record a video of the problem tomorrow

Thanks, a full console log will be more useful in this case since we are not able to reproduce this issue. You can check the preserve log setting in the console settings so that the page reload doesn't clear the logs from the previous session.

**Comment by roman04204** [comment]
Seems to be:
https://support.google.com/chrome/thread/149820183/webrtc-not-working-after-chrome-update-to-version-98-0-4758-82?hl=en

**Comment by roman04204** [comment]
Everything works on the latest version of Mozilla firefox

**Comment by roman04204** [comment]
Before rebooting, the following errors occur:

Logger.js:154 2022-03-01T09:48:47.698Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: No SSRC lines found in remote SDP for remote stream[msid=cbc8b31a-audio-1,type=audio] Script: null Line: null Column: null StackTrace:  Error: No SSRC lines found in remote SDP for remote stream[msid=cbc8b31a-audio-1,type=audio]
    at pa._remoteTrackAdded (https://web-cdn.jitsi.net/meetjitsi_5852.2585/libs/lib-jitsi-meet.min.js?v=5852.2564:2:429666)
    at _usesUnifiedPlan.onTrack (https://web-cdn.jitsi.net/meetjitsi_5852.2585/libs/lib-jitsi-meet.min.js?v=5852.2564:2:422770)
    at RTCPeerConnection.r (https://web-cdn.jitsi.net/meetjitsi_5852.2585/libs/lib-jitsi-meet.min.js?v=5852.2564:2:667708)
r @ lib-jitsi-meet.min.js?v=5852.2564:2
getGlobalOnErrorHandler @ lib-jitsi-meet.min.js?v=5852.2564:2
window.onerror @ app.bundle.min.js?v=5852.2564:138
callErrorHandler @ lib-jitsi-meet.min.js?v=5852.2564:2
pa._remoteTrackAdded @ lib-jitsi-meet.min.js?v=5852.2564:2
_usesUnifiedPlan.onTrack @ lib-jitsi-meet.min.js?v=5852.2564:2
r @ lib-jitsi-meet.min.js?v=5852.2564:2

Logger.js:154 2022-03-01T09:48:47.708Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: TPC[id=2,type=JVB] remote track removal failed - track not found Script: null Line: null Column: null StackTrace:  Error: TPC[id=2,type=JVB] remote track removal failed - track not found
    at pa._remoteTrackRemoved (https://web-cdn.jitsi.net/meetjitsi_5852.2585/libs/lib-jitsi-meet.min.js?v=5852.2564:2:432190)
    at MediaStream.<anonymous> (https://web-cdn.jitsi.net/meetjitsi_5852.2585/libs/lib-jitsi-meet.min.js?v=5852.2564:2:422856)
	
	
Logger.js:154 2022-03-01T09:48:49.353Z [modules/statistics/AvgRTPStatsReporter.js] <pc._calculateAvgStats>:  No "bitrate"
r @ lib-jitsi-meet.min.js?v=5852.2564:2
_calculateAvgStats @ lib-jitsi-meet.min.js?v=5852.2564:2
t._onLocalStatsUpdated @ lib-jitsi-meet.min.js?v=5852.2564:2
r.emit @ lib-jitsi-meet.min.js?v=5852.2564:2
(анонимная) @ lib-jitsi-meet.min.js?v=5852.2564:2
r.emit @ lib-jitsi-meet.min.js?v=5852.2564:2
id._onIceConnectionInterrupted @ lib-jitsi-meet.min.js?v=5852.2564:2
r.emit @ lib-jitsi-meet.min.js?v=5852.2564:2
peerconnection.oniceconnectionstatechange @ lib-jitsi-meet.min.js?v=5852.2564:2
peerconnection.oniceconnectionstatechange @ lib-jitsi-meet.min.js?v=5852.2564:2
Logger.js:154 2022-03-01T09:48:53.668Z [modules/statistics/AvgRTPStatsReporter.js] <hc.addNext>:  bandwidth_upload - invalid value for idx: 0 undefined
r @ lib-jitsi-meet.min.js?v=5852.2564:2
addNext @ lib-jitsi-meet.min.js?v=5852.2564:2
_calculateAvgStats @ lib-jitsi-meet.min.js?v=5852.2564:2
t._onLocalStatsUpdated @ lib-jitsi-meet.min.js?v=5852.2564:2
r.emit @ lib-jitsi-meet.min.js?v=5852.2564:2
_updateLocalStats @ lib-jitsi-meet.min.js?v=5852.2564:2
r.emit @ lib-jitsi-meet.min.js?v=5852.2564:2
On._processAndEmitReport @ lib-jitsi-meet.min.js?v=5852.2564:2
On.processStatsReport @ lib-jitsi-meet.min.js?v=5852.2564:2
(анонимная) @ lib-jitsi-meet.min.js?v=5852.2564:2
Объект Promise.then (асинхронный)
t @ lib-jitsi-meet.min.js?v=5852.2564:2
Объект setInterval (асинхронный)
On.start @ lib-jitsi-meet.min.js?v=5852.2564:2
$n.startRemoteStats @ lib-jitsi-meet.min.js?v=5852.2564:2
id._acceptJvbIncomingCall @ lib-jitsi-meet.min.js?v=5852.2564:2
id.onIncomingCall @ lib-jitsi-meet.min.js?v=5852.2564:2
r.emit @ lib-jitsi-meet.min.js?v=5852.2564:2
onJingle @ lib-jitsi-meet.min.js?v=5852.2564:2
run @ lib-jitsi-meet.min.js?v=5852.2564:2
(анонимная) @ lib-jitsi-meet.min.js?v=5852.2564:2
forEachChild @ lib-jitsi-meet.min.js?v=5852.2564:2
_dataRecv @ lib-jitsi-meet.min.js?v=5852.2564:2
_onMessage @ lib-jitsi-meet.min.js?v=5852.2564:2
Logger.js:154 2022-03-01T09:48:53.669Z [modules/statistics/AvgRTPStatsReporter.js] <hc.addNext>:  bandwidth_download - invalid value for idx: 0 undefined


I also attach the entire console log at the time of the reboot
[meet.jit.si-1646127837421.log](https://github.com/jitsi/jitsi-meet/files/8160580/meet.jit.si-1646127837421.log)

**Comment by roman04204** [comment]
[meet.jit.si-1646061776233.log](https://github.com/jitsi/jitsi-meet/files/8160588/meet.jit.si-1646061776233.log)

**Comment by jallamsetty1** [comment]
Thanks for the full log @roman04204, it appears that some traffic blocking is happening in your providers network as the ICE connection between the client and the bridge is failing. FYI, google meet also seems to have the same issue. Are you able to verify if you are able to get the media to work on https://meet.google.com ? This is the Chrome bug for your reference - https://bugs.chromium.org/p/chromium/issues/detail?id=1301270

**Comment by shawnchin** [comment]
Not sure if this is related or helpful, but we've been seeing similar issue since yesterday where a user from Russia is unable to join room using Chrome. User was able to join using Firefox. Other users on same Chrome version from different countries were able to join the same call. We're on the latest stable version of Jitsi.

Client logs look similar to the above.

On the JVB side, we see logs like this:
```
JVB 2022-03-01 16:07:17.005 INFO: [162] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=at2dp1ft33oi4v epId=626dd530 local_ufrag=at2dp1ft33oi4v] ConnectivityCheckClient.processTimeout#874: timeout for pair: 10.1.1.
112:10000/udp/host -> 5.164.X.X:54164/udp/prflx (stream-626dd530.RTP), failing.
JVB 2022-03-01 16:07:17.005 INFO: [161] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=at2dp1ft33oi4v epId=626dd530 local_ufrag=at2dp1ft33oi4v] ConnectivityCheckClient.updateCheckListAndTimerStates#456: CheckList
will failed in a few seconds if no succeeded checks come
JVB 2022-03-01 16:07:21.867 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=akoj21ft33oi3f epId=0f84876b local_ufrag=akoj21ft33oi3f] ConnectivityCheckClient$1.run#466: CheckList for stream stream-0f8487
6b FAILED
JVB 2022-03-01 16:07:21.867 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=akoj21ft33oi3f epId=0f84876b local_ufrag=akoj21ft33oi3f] Agent.checkListStatesUpdated#1883: Suspicious ICE connectivity failur
e. Checks failed but the remote end was able to reach us.
JVB 2022-03-01 16:07:21.867 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=akoj21ft33oi3f epId=0f84876b local_ufrag=akoj21ft33oi3f] Agent.checkListStatesUpdated#1887: ICE state is FAILED
JVB 2022-03-01 16:07:21.868 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=akoj21ft33oi3f epId=0f84876b local_ufrag=akoj21ft33oi3f] Agent.setState#908: ICE state changed from Running to Failed.
JVB 2022-03-01 16:07:21.868 INFO: [155] [confId=cb15f465004d49be epId=0f84876b local_ufrag=akoj21ft33oi3f gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain] IceTransport.iceStateChanged#334: ICE state changed old=Running new=Failed
JVB 2022-03-01 16:07:22.005 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=at2dp1ft33oi4v epId=626dd530 local_ufrag=at2dp1ft33oi4v] ConnectivityCheckClient$1.run#466: CheckList for stream stream-626dd5
30 FAILED
JVB 2022-03-01 16:07:22.005 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=at2dp1ft33oi4v epId=626dd530 local_ufrag=at2dp1ft33oi4v] Agent.checkListStatesUpdated#1883: Suspicious ICE connectivity failur
e. Checks failed but the remote end was able to reach us.
JVB 2022-03-01 16:07:22.006 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=at2dp1ft33oi4v epId=626dd530 local_ufrag=at2dp1ft33oi4v] Agent.checkListStatesUpdated#1887: ICE state is FAILED
JVB 2022-03-01 16:07:22.006 INFO: [155] [confId=cb15f465004d49be gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain ufrag=at2dp1ft33oi4v epId=626dd530 local_ufrag=at2dp1ft33oi4v] Agent.setState#908: ICE state changed from Running to Failed.
JVB 2022-03-01 16:07:22.006 INFO: [155] [confId=cb15f465004d49be epId=626dd530 local_ufrag=at2dp1ft33oi4v gid=64397 stats_id=Laverne-pJi conf_name=test@conference.meet.domain] IceTransport.iceStateChanged#334: ICE state changed old=Running new=Failed
```
