### ISSUE TITLE
Hide the option to start recording and share screen in android SDK

### ISSUE THREAD

**Issue by cristianrabadiaimbox** [jitsi/jitsi-meet#11041]
Details of my project:
Jitsi SDK 3.10.2
minSdkVersion 21
targetSdkVersion 30

Hello, I am trying to hide the options to hide recording and share screen with the corresponding flags but it does not work.
The flags I am trying:

.setFeatureFlag("invite.enabled", false)
.setFeatureFlag("recording.enabled",false)
.setFeatureFlag("video-share.enabled",false)

**Comment by saghul** [comment]
Please update your SDK to the latest version. As of right now that's 4.1.0

**Comment by cristianrabadiaimbox** [comment]
@saghul I can't upload the SDK

**Comment by saghul** [comment]
Why not? You cannot magically get the functionality you want in an SDK that does not have it.
