### ISSUE TITLE
Anomaly when the prejoin page asks to participate with the webcam turned off. After reactivating it, no one sees us.

### ISSUE THREAD

**Issue by MarcoScammacca** [jitsi/jitsi-meet#11064]
Differences in the prejoinpage if you come from the lobby enabled (with prejoin disabled by config) or from the prejoin enabled by config.

### Description:
If the prejoin is enabled by config, the prejoinpage works correctly. 
Otherwise in case of prejoinpage disabled on the config file, if you arrive at the prejoinpage because there is an active lobby in the room, there are anomalies when you ask to participate with the webcam turned off. 

In fact, as soon as the participant reactivates the webcam, the others in the room do not see him. 

### Steps to reproduce:
Okay, I think I have located the bug.

I have set up a solution based on the 6865 stable version clean, without custom code.

1. prejoin disabled
2. moderator opens the room and enables the lobby
3. a participant tries to enter the room and is presented with the prejoin page
4. the participant enters with the webcam turned off, then inside the room he enables the webcam → no one sees him

When I redid everything but with the prejoin enabled, both the moderator and the participant go to the prejoin page, and following points 2, 3 and 4 the final result is that the participant is seen correctly by the others.

ps. we want to keep the prejoin page disabled.
For us the moderator is whoever opens the room.
We do not want the moderator to see the prejoin, because this further preparation step does not make sense since it will be the only one in the room.

### Expected behavior:

That the prejoin that pops up with the lobby enabled, behaves as well as the prejoin that pops up, given by the prejoin enabled by the config file. 

In particular:
the participant enters with the webcam off, then inside the room enables the webcam → everyone sees him 

### Actual behavior:

the participant enters with the webcam turned off, then inside the room he enables the webcam → no one sees him

### Server information:

- Jitsi Meet version: stable 6865
- Operating System: win 11

### Client information:

- Browser / app version: Edge
- Operating System: win 11

### Additional information:

the problem only comes up if the prejoin Page is disabled

**Comment by saghul** [comment]
@jallamsetty1 this one sounds right up your alley 😄

**Comment by MarcoScammacca** [comment]
The difference I noticed is on the writing of the button in prejoin Page.

With the prejoin page enabled, it shows the message “Ask to Join”, instead with the prejoin disabled but the lobby active, present “Join meeting”.

Apparently they are called two different prejoin pages …
