### ISSUE TITLE
Not able to join the meeting using iOS SDK | Sample code is also having the same issue if we use SDK using the master code

### ISSUE THREAD

**Issue by idrive-pankaj** [jitsi/jitsi-meet#11060]
### Description:

I have taken pull from the master branch and created a new SDK using the terminal. Now from the native iOS app, I am trying to join the meeting but the user can connect a meeting for a while and just get disconnected.

I tested the same thing using the sample code available here but the same issue is there in the sample code as well.

### Steps to reproduce:

1. Clone master repo and run NPM install - (deleted package-lock.json first)
2. Create SDK using the bellow command
`mkdir -p ios/sdk/out
xcodebuild clean \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphonesimulator \
    -destination='generic/platform=iOS Simulator' \
    -archivePath ios/sdk/out/ios-simulator \
    VALID_ARCHS=x86_64 \
    ENABLE_BITCODE=NO \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphoneos \
    -destination='generic/platform=iOS' \
    -archivePath ios/sdk/out/ios-device \
    VALID_ARCHS=arm64 \
    ENABLE_BITCODE=NO \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
    -framework ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -framework ios/sdk/out/ios-simulator.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -output ios/sdk/out/JitsiMeetSDK.xcframework
cp -a node_modules/react-native-webrtc/apple/WebRTC.xcframework ios/sdk/out`
4. Instead of pod library, use this SDK in the sample code downloaded from here - https://github.com/jitsi/jitsi-meet-sdk-samples
5. try to create one room and join that meeting, I am getting one error like bellow
`[JitsiMeetSDK] [modules/xmpp/strophe.util.js] Strophe: error: undefined /Users/pankaj/Library/Developer/Xcode/DerivedData/JitsiSDKTest-glhtiqikkatwtthimvbobirxgbvh/Build/Products/Debug-iphonesimulator/JitsiMeetSDK.framework/main.jsbundle:1502 - TypeError: undefined is not an object (evaluating 'S.email')`
`example-app[11049:315949] [JitsiMeetSDK] [modules/xmpp/strophe.util.js] Strophe: User connection callback caused an exception: TypeError: undefined is not an object (evaluating 'S.email')`

I have not added any changes to the master repository for now after merging the latest code from the master repo I am also facing this issue in my current repository which was previously working fine.

### Expected behavior:

User should be able to join the meeting.
### Actual behavior:

https://user-images.githubusercontent.com/79213346/156317276-70cd266e-111a-4851-8401-db8eb787a5ff.mov

### Server information:

- Jitsi Meet version: (HEAD -> master, tag: jitsi-meet_6981, tag: jitsi-meet_6980, tag: 5895)
- Operating System: Mac OS BigSur
- Xcode 13.0

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

Thanks in Advance.

**Comment by idrive-pankaj** [comment]
@saghul can you please share that branch URL with me, it's not showing when I fetch all the branches from the origin.

**Comment by idrive-pankaj** [comment]
@saghul still facing the same issue, is there something wrong with my machine?
My NPM version is 8.0.0 and I can share the demo project with you if needed.

Here with mobile-22.0 branch same error I am getting.
`TypeError: undefined is not an object (evaluating 'l.email')
2022-03-02 15:34:17.659180+0530 example-app[21769:459753] [JitsiMeetSDK] [modules/xmpp/strophe.util.js] Strophe: User connection callback caused an exception: TypeError: undefined is not an object (evaluating 'l.email')`

**Comment by saghul** [comment]
Does the app work, if you build that instead?

**Comment by idrive-pankaj** [comment]
Yes it's working fine

**Comment by saghul** [comment]
Thanks for giving it a try. We'll test this soon, since we intend to make a release shorty.

**Comment by idrive-pankaj** [comment]
no problem @saghul , but what about the current master branch? I am still getting the same error in that master as well.
it's something related to email value which it is getting undefined but not sure where I can check this.

**Comment by idrive-pankaj** [comment]
> Yes it's working fine if I just run iOS code from react-native.

Here I mean if we run the iOS app from the react-native code then it's working fine but if I try to create an SDK and use it then the issue is there.

**Comment by idrive-pankaj** [comment]
Okay, Thanks

**Comment by saghul** [comment]
I pushed SDK 5.1.0-rc.2, can you give that one a try?

**Comment by idrive-pankaj** [comment]
Yeah sure, I will check it today.
Thanks

**Comment by saghul** [comment]
Make that SDK 5.1.0-rc.3

**Comment by idrive-pankaj** [comment]
@saghul I tried to test the latest release code and created SDK from the react-native code but unfortunately that SDK is not working.
I am getting this error - Dyld: Library not loaded: @rpath/GiphyUISDK.framework/GiphyUISDK and I think this is known the issue as mentioned [here](https://community.jitsi.org/t/dyld-library-not-loaded-rpath-giphyuisdk-framework-giphyuisdk/113505) so will wait for the fixes.

**Comment by saghul** [comment]
The SDK now depends on the Giphy SDK. The best way to manage dependencies is to use CocoaPods, which solves this automatically. SDK 5.1.0-rc.3 is released on CocoaPods too.

**Comment by idrive-pankaj** [comment]
Thanks, but we are building custom SDK as we have added many changes in the react native code.

**Comment by saghul** [comment]
Then you'll need to add the dependencies manually. You now need the giphy iOS SDK.

**Comment by idrive-pankaj** [comment]
Okay, I will check and give some try.

**Comment by idrive-pankaj** [comment]
I have added giphy iOS SDK manually and created SDK. Tested it with our application and it's working as expected.
Thanks @saghul
