### ISSUE TITLE
How to fix: Caused by: groovy.lang.MissingPropertyException: Cannot get property 'react' on extra properties extension as it does not exist  in Android Studio for Android version

### ISSUE THREAD

**Issue by Andreea1003** [jitsi/jitsi-meet#11076]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
We cannot help you if you don't provide any details.

**Comment by Love-Fat** [comment]
android studio 
I also met
Cannot get property 'react' on extra properties extension as it does not exist
