### ISSUE TITLE
Joining a breakout room with JWT authentication enabled is not possible

### ISSUE THREAD

**Issue by brjasha** [jitsi/jitsi-meet#11075]
### Description:

With JWT authentication enabled it is not possible to join breakout room as moderator - access is denied.

### Steps to reproduce:

0. JWT token should include "room" claim with the name of the conference room
1. Start the conference with JWT token (you get the moderator role)
2. Create a new breakout room
3. Join the breakout room
4. Get "Sorry! You are not allowed to be here" page

### Expected behavior:

The user should join the breakout room with moderator role.

### Actual behavior:

I suspect, that breakout room tries to validate JWT and validation fails, because "room" claim doesn't match name of the breakout room. If the "room" claim is set to "*", then joining breakout rooms with moderator role works without problems.

Extract from prosody logs:
`breakout.<myhost>:token_verification error Token eyJ0eXAi..... not allowed to join: bb747194-be1d-4d61-b7b5-d276706c4513@breakout.<myhost>/b8612835`

### Server information:

- Jitsi Meet version: latest Debian package
- Operating System: Ubuntu 20.04

**Comment by saghul** [comment]
@damencho Looks like we might need to add some BR logic to the token verification code, right? I can take a stab at it next week.

**Comment by shahru1013** [comment]
Hi @saghul, we faced this same issue too. Is there any chance to get it fixed with the next release please?
Thank you for your support!

**Comment by derekhinchliffe** [comment]
I had this problem after setting up a JWT enabled server from scratch using deb packages. The `jitsi-meet-tokens` package added the `"token_verification"` module to the `breakout.<domain>` muc component in the prosody config.

I tried removing the `token_verification` from the breakout component  and everything works as I'd expect it to. Main rooms still verify the token, but breakout rooms don't, so there is no issue with the room name not matching the token.

Does anyone know if there are downsides to just removing token verification from breakout component? Would this expose access to the breakout rooms by an un-authenticated user somehow? I haven't found any downsides in my testing but I might be missing something.

**Comment by damencho** [comment]
Other authenticated users on your system that are not in the main room, if they know the breakout room name can join the breakout room ... this is the only thing that any jwt protection can offer on the breakout muc component.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/commit/03c91de5c1a7e5854c4279179577501e9358730d
