### ISSUE TITLE
Participants list is not visible in jitsi flutter library.

### ISSUE THREAD

**Issue by MeriGarala09** [jitsi/jitsi-meet#11081]
I have downloaded the jitsi meet application from the AppStore and check the option for participants. From where I can find all participants list but in this library in menu option participants list is missing.

If the user is not able to see current participants in the meeting then it is not a user-friendly library.

Kindly add this option to the menu.

**Comment by saghul** [comment]
We are not the maintainers of the Flutter library, please ask them.
