### ISSUE TITLE
[Jitsi iOS SDK] App blocked on closing dialog for username and password

### ISSUE THREAD

**Issue by Carmelo992** [jitsi/jitsi-meet#11088]
Hello! Starting a call as admin (passing a jwt in the builder) a dialog appears and I've to insert email and password.
Closing this dialog the flow doesn't return to the view controller that started the call, but a progress indicator is displayed and the user can't go back.

![screen 1](https://user-images.githubusercontent.com/24452864/157191462-5c5dbfcd-5a1a-42c1-8df4-393315ac6013.png)
![screen 2](https://user-images.githubusercontent.com/24452864/157191468-febae224-e67c-4eff-860b-c520adb0b66c.png)

I tried to intercept the error using the delegate, but no one method has been called after the user has closed the dialog

### Steps to reproduce:

1. Open app
2. Start a call as admin, passing a jwt into the header
3. Wait that the login dialog appears
4. Close the dialog

### Expected behavior:

The view controller that shows the JitsiMeetView should be closed after the user close the dialog

### Actual behavior:

The view controller that shows the JitsiMeetView has a Progress Indicator and there aren't any buttons to close the view controller

- Jitsi Meet version: 3.10.4
- Operating System: iOS 15

**Comment by saghul** [comment]
> * Jitsi Meet version: 3.10.4

THis SDK version is incredibly old, please update.

**Comment by xuezhihuixzh** [comment]
Android 也是同样的问题 怎么解决楼主

**Comment by xuezhihuixzh** [comment]
Android 也是同样的问题 怎么解决楼主4.1.0版本

**Comment by xuezhihuixzh** [comment]
这个是什么意思

**Comment by Carmelo992** [comment]
> THis SDK version is incredibly old, please update.

@saghul I know, but this is the latest version that support iOS 11, from 4.0.0 the support for iOS 11 has been dropped

**Comment by saghul** [comment]
There is nothing we can do, sorry.
