### ISSUE TITLE
How to set theme Theme.AppCompat programmatically?

### ISSUE THREAD

**Issue by hafiz013** [jitsi/jitsi-meet#11080]
Hi i got this problem : unable to start activity ComponentInfo{com.nibmeetings.android/org.jitsi.meet.sdk.JitsiMeetActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity. My question is that, how to set theme before   JitsiMeetActivity.launch() <-

**Comment by saghul** [comment]
You need to do that in your AndroidManifest.xml

**Comment by Gokulkannan08** [comment]
What is the solution for this?

**Comment by Sarim-Sohail** [comment]
This issue remains unfixed, i tried @saghul 's solution but it did not resolve anything unfortunately.

Perhaps I'm missing some precise instructions/placement? could you give more detail? I'm new to app development
