### ISSUE TITLE
I can take a room for myself forever and this is a cost for the company 

### ISSUE THREAD

**Issue by salah-yousef** [jitsi/jitsi-meet#11099]
### Description:

When I add a password to a room I can stay alone for a long time which I think is an expensive 

### Steps to reproduce:

1. open the site 
2. login to any room 
3. make a password and don't close the session

### Expected behavior:

the session has a time if I am muted and not talking to give it free to other people 

### Actual behavior:

I can stay forever and I can create some bots to take do some problems to the servers 

### Server information:

the website server, not my own one 

### Client information:

chrome on windows 

### Additional information:

thanks

**Comment by damencho** [comment]
This is not considered a problem. You will spend more money on resources to stay in the rooms than the actual cost of that server side.

**Comment by salah-yousef** [comment]
I agree with you, but this is not good from an energy point of view.
I think it will be much better if the system kicks the user out if he is silent for a long time.
It is kind of save energy on a laptop if you are on there for a long time without using your pc it will log you out and then close after some time.

**Comment by damencho** [comment]
> I think it will be much better if the system kicks the user out if he is silent for a long time.

It already does, no media is sent after 20 seconds alone in the room. The rest is just one socket open which is nothing. We do not plan on implementing anything different as there are many usecases. There are people using it as a watch the house, where there is one participant 24h in the room, and you join when interested to check something.

You can always implement a custom module to destroy a room when there is only one participant there on your deployment.
