### ISSUE TITLE
[Jitsi Android SDK] App 视频通话建立连接之后  弹出用户名和密码对话框时

### ISSUE THREAD

**Issue by xuezhihuixzh** [jitsi/jitsi-meet#11094]
你好！以好友身份启动呼叫（在构建器中传递 jwt）会出现一个对话框，我必须插入电子邮件和密码。
关闭此对话框，流程不会返回到开始调用的视图控制器，但会显示失败

![c1e2be253306e8a1981db73a175bd85](https://user-images.githubusercontent.com/46469901/157356081-b03d9dbb-bfa1-4b5b-848a-ddabe64c4a36.jpg)
![e363983d827d26492e1acd68d89142c](https://user-images.githubusercontent.com/46469901/157356085-3d3b48b3-87db-4982-895f-263e6d34f2de.jpg)
![336a6328b4bde8ca0249d22a7af6639](https://user-images.githubusercontent.com/46469901/157356089-2526d663-ad0a-4c14-823f-c34c6b429611.jpg)

打开应用
以管理员身份启动呼叫，将 jwt 传递到标头
等待登录对话框出现4。
关闭对话框 5 失败
预期行为：
为什么会弹出对话框 是缺少什么参数 邮箱和密码从哪里获取 为什么不能建立连接 谢谢

Jitsi Meet 版本：4.1.0
操作系统：Android  10

**Comment by xuezhihuixzh** [comment]
这个是什么意思

**Comment by saghul** [comment]
Please post in English, we can't understand you.
