### ISSUE TITLE
Web moderator enable the webcam in mobile that webcam is not showing

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#11096]
Video not showing mobile side when web moderator enable the webcam.

Step to reproduce the issues : 
1) Enable "Start with audio muted" and "Start with video muted" before joining the meeting.
2) Only 2 participant should be in the meeting. 1 from web and another from mobile.
3) If both person in the meeting. Now web person enable the webcam. mobile side webcam not showing.

But if there is more than 2 person in the meeting then webcam is showing. Other case also working fine. like mobile to mobile, mobile to web and web to web.

Please check this bug in Jitsi Meet app.

Thanks

**Comment by saghul** [comment]
What app version are you using?

**Comment by pankajnegi1893** [comment]
version 22.0.1 build 169

**Comment by saghul** [comment]
Thanks! That must be iOS. Have you reproduced the same on Android?

**Comment by pankajnegi1893** [comment]
yes Android also same issue

**Comment by pankajnegi1893** [comment]
Any update regarding this issue ?

**Comment by saghul** [comment]
This should be fixed in the latest Jitsi Meet version, can you reproduce it with the current meet.jit.si?
