### ISSUE TITLE
Ability to add profile picture 

### ISSUE THREAD

**Issue by SiddheshKukade** [jitsi/jitsi-meet#11103]
![Screenshot_2022-03-10-18-40-03-830_org.jitsi.meet.jpg](https://user-images.githubusercontent.com/65951872/157668500-45a22617-42a3-496f-8304-6c2c6a3919e0.jpg)

**Describe the solution you'd like**
As we can see above currently there is no option to to upload profile picture in the video call app

There should be option to upload your profile picture in the settings of the video call app

**are you working on the issue**
No

**Comment by saghul** [comment]
You can upload your avatar to gravatar.com and we'll use it. We have no plans to add custom avatar uploading.
