### ISSUE TITLE
No video in p2p if other participant has joined with his camera turned off

### ISSUE THREAD

**Issue by soisik** [jitsi/jitsi-meet#11100]
## Description

In p2p mode, a user using the app on mobile (android or iphone) will not receive the video from the other participant if there are in p2p and if other participant has joined with his camera turned off.

## Current behavior

- user1 join room on desktop using chrome with his camera turned off
- user2 join room on a mobile (android or iphone)
- user1 turn on his video (or share his screen)
- user2 do not see any video 

## Expected Behavior
user2  should see the video 

## Possible Solution

Does not occur if either:
- user1 join with video turned on,
- p2p is disabled in config.js,
- p2p is stopped during the conference (executing `APP.conference._room.stopP2PSession()` in user1 console): user2 sees the video right after the command is executed.

# Environment details

First noticed on our on premise install (2.0.6826-1) and also reproduced on meet.jit.si 
Using latest jitsi app (built dec 2021).

**Comment by damencho** [comment]
We had recently fixed an issue like that, and the fixes are deployed on meet.jit.si recently.

**Comment by soisik** [comment]
> When did you reproduce it on meet.jit.si?
A few minutes before opening the issue.
I did another test just now, issue still occurs.

**Comment by saghul** [comment]
Can you reproduce it with Jitsi Meet 22.0.1? We started the rollout earlier this week.

**Comment by saghul** [comment]
> I can confirm that there is something off with the video streams. It is somewhat solved by disabling p2p, but screen sharing still does not work.
> 
> If a person disables the camera and enables screen sharing, I can only see the previous image of the camera as a frozen image.
> 
> I updated jitsi yesterday via repositories.

IS this with the mobile apps or using a desktop browser?

**Comment by ClundXIII** [comment]
> IS this with the mobile apps or using a desktop browser?

I was on firefox, the other Person was using brave. The other person could see me screen, but I was not able to see the screenshare.

**Comment by AjayShivanagol** [comment]
> We had recently fixed an issue like that, and the fixes are deployed on meet.jit.si recently.

@damencho  is this JVB issue or native issue?

can you please attach the commit link for reference?

**Comment by damencho** [comment]
https://github.com/jitsi/lib-jitsi-meet/commit/f881b3c745016c045162f9a608ed22d4ac307ecf

**Comment by AjayShivanagol** [comment]
@damencho Thanks! the issue is still happening is there any workaround for this?

**Comment by damencho** [comment]
You reproduce this on meet.jit.si with latest app?

**Comment by AjayShivanagol** [comment]
@damencho Yes I am able to reproduce this on 

Android version 22.1.0 (Beta) on meet.jit.si

**Comment by damencho** [comment]
Yep, @saghul and @jallamsetty1, I can reproduce this.

**Comment by jallamsetty1** [comment]
Happens only when the receiver is running in plan-b mode and the sender is running in Unified-plan mode, debugging the issue still.

**Comment by anonid64** [comment]
`ii  jitsi-meet                            2.0.8319-1                             all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                    1.0.6991-1                             all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver                 1.0.6991-1                             all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                        1.0.6991-1                             all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.6991-1                             all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                    2.2-79-gf6426ea0-1                     all          WebRTC compatible Selective Forwarding Unit (SFU)`

I using that version and i have same error. When user1 create meeting with video, user2 join with video. 2 user can view video of both user. But when user3 join without video (PC), then i lost all video of all user.

**Comment by damencho** [comment]
> But when user3 join without video (PC), then i lost all video of all user.

And if the 3rd join with video everything works?

**Comment by anonid64** [comment]
> > But when user3 join without video (PC), then i lost all video of all user.
> 
> And if the 3rd join with video everything works?

Yes, 3rd join with camera everything work properly. What is my config mistake?

**Comment by mostafaamr1** [comment]
Any solution?
