### ISSUE TITLE
Devices with poor acoustic design cause issues by echoing the sound they play to other participants, echo cancellation has to be improved 

### ISSUE THREAD

**Issue by LauriLaakk** [jitsi/jitsi-meet#11102]
Hi,

I've encountered this issue with my tablet device where having maximum volume enabled and a another user speaking to me, they are able to hear themselves / distorted voices of themselves when in a video call. The issue happens also with certain types of casings, which disrupt the audio design balance, where the tablet is encased with a material which bounces the sound from speaker to the microphone. But for example with my device, Lenovo Tab M10 HD / TB-X505SF, has this issue with high volume levels. And the issue happens always when i have medium to high volume, with worsening effect depending on the level. 

To reproduce this issue im using the said Lenovo Tab M10 HD (TB-X505SF) device, and calling a another device using a recent meet jitsi app. The issue happens at differing severity depending on the volume level, and increasing the volume to maximum ensures for me that the issue happens always.

When comparing with other applications, skype and zoom seem to work better. Skype seems to have less effect from the same device combination and zoom basically nullifies the effect. 

Here is some comparison material:

Jitsi sound clip of the issue:
https://drive.google.com/file/d/1Zhb9PYT2yOaKUEF1GNOHa4Mp6FfGzn-n/view?usp=sharing

Skype sound clip of the issue:
https://drive.google.com/file/d/1R3rwHXpJOZr4a_aDC7EbbF4q-WrzTzlC/view?usp=sharing

Zoom was completely silent.

Device im using is running with following specs:

<html>
<body>

Model | Lenovo Tab M10 HD (TB-X505SF)
-- | --
SW version | TB-X505F_RF01_190430
Ram | 2GB
CPU | 2GHz
Android | 10
Connection type | Wifi

</body>
</html>

Feel free to contact me at lauri.laakkonen@vooler.fi, if you have any follow up questions of the issue.

**Comment by saghul** [comment]
We use the system provided hardware acoustic echo canceller. Not much else we can do here. There are options like Krisp, but they are proprietary.

**Comment by jcalfee** [comment]
Why is this "Not planned?"
