### ISSUE TITLE
Adding shortcuts inside the tooltips

### ISSUE THREAD

**Issue by aashimawadhwa** [jitsi/jitsi-meet#11106]
**Is your feature request related to a problem you are facing?**
Including shortcuts in the tool-tips to icons of toolbar to enhance user experience .

**Describe the solution you'd like**

currently it is like this -

![Screenshot from 2022-03-10 23-14-33](https://user-images.githubusercontent.com/73706697/157723856-c36b4edc-50e2-49c9-a4d0-e178c7688637.png)

something like this -

![Screenshot from 2022-03-10 23-18-34](https://user-images.githubusercontent.com/73706697/157724354-012db09c-2f61-4844-a78b-c42d7cfe7225.png)

**Comment by aashimawadhwa** [comment]
I would like to work on this issue .

**Comment by saghul** [comment]
Sounds interesting. We'll check with our design team and let you know if that's a direction we'd like to go into.

**Comment by aashimawadhwa** [comment]
> Sounds interesting. We'll check with our design team and let you know if that's a direction we'd like to go into.
okay sure , I had one doubt,  do jitsi have a forum where I can connect with mentors and other fellow developers.

**Comment by saghul** [comment]
Sure thing! You can get in touch at https://community.jitsi.org

**Comment by saghul** [comment]
Alright, I checked and we are good to go. Feel free to work on it and send a PR when ready!

**Comment by aashimawadhwa** [comment]
> Alright, I checked and we are good to go. Feel free to work on it and send a PR when ready!

okay thanks !
