### ISSUE TITLE
Unexpected end of input in node_modules/resolve/test/resolver/malformed_package_json/package.json:2:1 when running npm run lint in Build Frontend

### ISSUE THREAD

**Issue by juliusyam** [jitsi/jitsi-meet#11110]
```
Please wait. Server is handling a request (collating errors)
Error --------------------------------------- node_modules/resolve/test/resolver/malformed_package_json/package.json:2:1

Unexpected end of input

   2|
      


Found 1 error
Error: Process completed with exit code 2.
```

![2022-03-11 10_14_28-Fix_css · 115one_one_fifteen_one_jitsi@7d1788e](https://user-images.githubusercontent.com/60099078/157850471-0ecba228-ff5d-441b-b040-4dfee56a0c0f.png)
![2022-03-10 16_54_53-Fix_css · 115one_one_fifteen_one_jitsi@7d1788e](https://user-images.githubusercontent.com/60099078/157850473-42a7bafc-f716-4b08-8730-4b52b75ae789.png)

Works fine locally but not in Github Build

**Comment by saghul** [comment]
How are you building on GH? You seem to be using an old release too, we no longer run flow...

**Comment by juliusyam** [comment]
> How are you building on GH? You seem to be using an old release too, we no longer run flow...

I am using an older release back in early December 2021. Is that the issue?

**Comment by saghul** [comment]
I don't think so, but I thought I'd mention it. Anyway, what exact steps are you following to make the build? Using what node / npm versions?
