### ISSUE TITLE
Expose connection quality as an event

### ISSUE THREAD

**Issue by robintown** [jitsi/jitsi-meet#11114]
**Is your feature request related to a problem you are facing?**
In my web app which embeds Jitsi Meet, I would like to be able to show an indicator of connection quality in the UI, outside of the iframe.

**Describe the solution you'd like**
Emit an event over the iframe API whenever the connection quality changes (e.g. good → poor).

**Describe alternatives you've considered**
Not sure.

**Comment by emdrremote** [comment]
This would be a very helpful feature as my clients constantly have performance issues and assume the system is "broken" even though it's really just their poor connection. It would be great to be able to set up custom messages to let them know what is really happening.
