### ISSUE TITLE
Strange color effect on screensharing

### ISSUE THREAD

**Issue by StillUpgrade** [jitsi/jitsi-meet#11125]
First of all, Hello 😄 
Thanks for all your work on this awesome lib

### Description:

During a meeting, I share my screen and I see my screen correctly mirrored but with strange color effect.

### Steps to reproduce:

1. Launch a meeting on meet.jit.si
2. Share your screen

### Expected behavior:

Normal color

### Actual behavior:

It looks like a sepia / saturate effect is applied on my screensharing video

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/10169092/158167262-24d95a30-ffcd-4571-9e69-8da5b6dbd708.png">

<img width="409" alt="image" src="https://user-images.githubusercontent.com/10169092/158167306-fc979b57-2519-48dc-91a0-db6e213a53af.png">

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: meet.jit.si

### Client information:

- Browser / app version: Brave [Version 1.35.100 Chromium: 98.0.4758.87 (x86_64)](https://brave.com/latest/)
- Operating System: Macos Monterey 12.0.1

### Additional information:

I also tried in private window, same result. Can't reproduce the bug on google chrome, only on Brave.
It bug alone in a meeting, but also when there are other people.

**Comment by StillUpgrade** [comment]
As i looked to my Brave version, I saw I had an update available.
After relaunch, the bug disappeared !!! 

Hope it'll help someone to know that updating Brave fix the bug.

**Comment by saghul** [comment]
Yep, this was a fix in Chromium which was promptly fixed.
