### ISSUE TITLE
Xcode App Archive Fails

### ISSUE THREAD

**Issue by SeveHo** [jitsi/jitsi-meet#11135]
### Description:

Hi, I am trying to archive the app on a Intel Mac but get the following error:

```
.../Library/Developer/Xcode/DerivedData/jitsi-meet-
hlelemwgmxxsijfxgkpysuhtybwd/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-
iphoneos/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting
ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file
.../Library/Developer/Xcode/DerivedData/jitsi-meet-
hlelemwgmxxsijfxgkpysuhtybwd/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-
iphoneos/WebRTC.framework/WebRTC' for architecture arm64
```

I tried it on current **master** and on **ios-22.0.1** but get the same result on both branches/tags. I did not change the build settings. `Enable Bitcode` is set to `yes` for Release. I do not use a custom WebRTC or JitsiMeet SDK. The Podfile contains `config.build_settings['ENABLE_BITCODE'] = 'YES'` as per default. Running a debug build on a simulator works fine.

Do you have an idea what the problem could be?

### Versions
Xcode 13.2.1
MacOS 12.2.1
Node 16

**Comment by saghul** [comment]
You need to run this script from your node_modules directory: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/downloadBitcode.sh

**Comment by SeveHo** [comment]
Thanks a lot @saghul. Should I create a PR for the Handbook? I'm sure this is a pretty important information for others as well.

**Comment by saghul** [comment]
Indeed, please do!

**Comment by tj0xin** [comment]
> Thanks a lot @saghul. Should I create a PR for the Handbook? I'm sure this is a pretty important information for others as well.

Hi SeveHo, 

Can you please guide on how to run this script? 

I'm not able to figure out this, i have the same error as you on latest Jitsi Meet app from Github.
