### ISSUE TITLE
Webcam starts automatically when stopping desktop screen-share

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#11131]
### Description:

The video cam is automatically turned on and turned off after stopping desktop screen-share. Webcam flashlight blinks for around 2 seconds.

### Steps to reproduce:

1. Join a room.
2. Start screenshare.
3. After a few moments, stop screeenshare.
4. Webcam flashlight blinks.

### Expected behavior:

Either webcam shouldn't start when stopping screen share or flashlight.

### Actual behavior:

Webcam start and blinks for around 2 seconds.

### Server information:

- Jitsi Meet version: 2.0.7001
- Operating System: Ubuntu

### Client information:

- Browser / app version: Chrome
- Operating System: Ubuntu

### Additional information:

This issue was not found in the previous version.
This issue exist in https://meet.jit.si/

**Comment by saghul** [comment]
I think this might be because we need the video track to exist but it's muted. @jallamsetty1 can you confirm?

**Comment by saghul** [comment]
Can you please add a link to the bug here, for reference?

**Comment by anoopsnm** [comment]
> Yes, we need the video track to exist and to replace the screenshare track after screenshare stops. It does get muted immediately though, no media is sent across the connection. We had to implement this to workaround a Chrome bug.
@jallamsetty1 

But from a user experience perspective, causing the webcam light to blink when it was, in fact, off, would make the users question the reliability of the Jitsi. The user will think their webcam got turned on and the video was transmitted.

**Comment by saghul** [comment]
The alternative is to have video stop working altogether.

**Comment by AjayShivanagol** [comment]
@saghul @jallamsetty1 Can we have a separate track for Video and Screenshare?

**Comment by jallamsetty1** [comment]
> @saghul @jallamsetty1 Can we have a separate track for Video and Screenshare?

This issue will be gone with multi-stream mode that we are currently in development. We hope to release the new mode in a couple of weeks.

**Comment by saghul** [comment]
> @saghul  @jallamsetty1 I think it’s a Major privacy issue as per me…
> 
> 
> 
> I was in a meeting with the remote participant sharing his screen after some time he stopped his screen share…
> 
> 
> 
> I was able to see his video for 1 sec.!!!
> 
> 
> 
> which describes a privacy issue right?
> 
> 
> 
> his intention was not to TURN the video ON but without a user click video is turning ON.

We know. Have you read my previous comment?

**Comment by AjayShivanagol** [comment]
@saghul You mean we should not give permission for video right?

**Comment by saghul** [comment]
No I mean that without the workaround video would stop working altogether.

It will stop happening when we release multi-stream support.
