### ISSUE TITLE
Pinned video disappears on large video if user scrolldown or up from the thumbnail list on web until pinned participant is hidden in the list

### ISSUE THREAD

**Issue by mabocoglu** [jitsi/jitsi-meet#11147]
### Steps to reproduce:

1. Add enough participant into meeting to fill the screen with thumbnails
2. Select or pin the filmstrip view from the menu
3. Select one of the small thumbnails and ensure that is shown on the large video
4. Scroll down or the thumbnail list until the selected thumbnail is not visible on the window

### Expected behavior:

If the thumbnail is pinned, it should not stop the video even it is hidden in the vertical thumbnail list

### Actual behavior:

Pinned participant's large video becomes hidden when thumbnail list scrolled down or up until it's thumbnail go outside of the visible window

### Server information:

- Jitsi Meet version: 2.0.7001
- Operating System: Ubuntu 20.04.4 LTS

### Client information:

- Browser / app version: Google Chrome 99.0.4844.51
- Operating System: Windows 10 Pro 64-bit 21H2 

### Additional information:

![hidden_pinned_participant](https://user-images.githubusercontent.com/4979958/158594355-66919473-751e-4594-90b8-2cbb79868c48.png)

**Comment by saghul** [comment]
Can you reproduce this on meet.jit.si ? It's slightly ahead of stable.

**Comment by mabocoglu** [comment]
I have tested on meet.jit.si today. I haven't notice such a problem. I can see the video for pinned participant even it is hidden in the thumbnail list on right side.
