### ISSUE TITLE
Non-p2p connection doesn't work for Chrome 98+

### ISSUE THREAD

**Issue by chernodub** [jitsi/jitsi-meet#11158]
### Description:
Hi, we're having an issue when several (3 and more) Chrome users connect to a room. Nobody can see or hear each other. Other browsers (Firefox, Safari) work fine. Presumably, this only appears when p2p mode is not active.

### Steps to reproduce:

Join the same room in http://meet.jit.si from 3 windows (Chrome 99), in order to emulate 3 users. This way, p2p mode is disabled.

### Expected behavior:

The participants can see/hear each other.

### Actual behavior:

The participants can not see/hear each other, and pages are being crashed/auto-refreshed every ~10 sec.

https://user-images.githubusercontent.com/37013688/158766563-29adf294-0ffe-479c-a953-4002b6919ac4.mp4

[Chrome logs.txt](https://github.com/jitsi/jitsi-meet/files/8282679/Chrome.99.logs.txt)

### Client information:

- Browser / app version: Chrome 99 (tested this on 98, doesn't work too)
- Operating System: macOS 12.2.1

### Additional information:
I was also able to reproduce this by hosting my own version of jitsi-meet using [the latest docker-compose image (7001)](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-7001) with disabled the p2p mode (via `ENABLE_P2P` in `.env`). This also breaks the communication, in this case, even for 2 Chrome users. And again, other browsers work just fine.

Tests for firefox (everything seems to be alright):
https://user-images.githubusercontent.com/37013688/158766629-d5355914-176b-4240-8d58-82529e27172c.mp4

I've added this information as a start point, please feel free to ping me for any information needed. I'd appreciate if you guys could give me your thoughts on how to resolve this as soon as possible. Thanks!

**Comment by chernodub** [comment]
Yeah, these issues could totally be related. And that's what I'm trying to figure out. I'm testing this from Russia, but decided to create the issue anyway, in case other people face this from other regions. And actually, our clients from US experience similar problems. I'm quite a newbie in networking, so I don't get why VPN doesn't help in this case. Do you have any ideas @saghul? And thanks for the quick answer!

**Comment by saghul** [comment]
Are any of the participants or the servers in Russia?

**Comment by chernodub** [comment]
Both servers and clients are not in Russia (servers are hosted via AWS), but the infrastructure is quite different and there we use a `lib-jitsi-meet` with some custom UI, unfortunately it stopped working at some point.

In order to reduce the scope of our issue, I hosted my own Jitsi server (in SF, US), but this seems not to be working as expected too. I did some tests on meet.jit.si. Same issue, so here I am.

This bug report I created is based on the data I've gathered using Chrome from Russia, so yeah, this may be related to the issue you mentioned @saghul.

Anyway, I'd appreciate if you'd answered a question I mentioned before. And thanks.
> Also, I assume you've tested this for 3 participants (using Chrome 98+) and this is working alright for you on [meet.jit.si](https://meet.jit.si/)?

**Comment by saghul** [comment]
> Also, I assume you've tested this for 3 participants (using Chrome 98+) and this is working alright for you on [meet.jit.si](https://meet.jit.si/)?

Sure thing, otherwise we'd all be all hands on deck.



> This bug report I created is based on the data I've gathered using Chrome from Russia, so yeah, this may be related to the issue you mentioned @saghul.

Yep, it looks that way.

**Comment by chernodub** [comment]
I see, happy to hear everything works as expected. Then I should close the issue, since there's really nothing you can suggest in this case. I will continue investigating the possible workarounds for this somewhere else then. Thanks for your time @saghul!
