### ISSUE TITLE
token_auth_url not working on mobile

### ISSUE THREAD

**Issue by d3473r** [jitsi/jitsi-meet#11157]
### Description:

The `token_auth_url` parameter is not working on the mobile app (android tested)

### Steps to reproduce:

1. Configure `token_auth_url` to redirect for a jwt
2. Start a new meeting with the android app and click on i am the host
3. Not redirected, instead a username and password prompt is shown

### Expected behavior:

The mobile app should open a browser and open the configured `token_auth_url`

### Actual behavior:

A login prompt is shown, jwt auth is configured

### Server information:

- Jitsi Meet version: [stable-7001](https://hub.docker.com/layers/jitsi/web/stable-7001/images/sha256-a7f572ef4204c08cb1fa65ab2e52d0fb022386a228b03fb875693a2e9fcf3d69?context=explore)
- Operating System: Docker

### Client information:

- Browser / app version: 22.0.1
- Operating System: Android

**Comment by saghul** [comment]
This is a known limitation since the mobile app is not a browser.

It would need to open a WebView and get the token to send it back.

It's doable, any PR is welcome.

**Comment by d3473r** [comment]
I don't think you even need a web view, because the way from auth app to the jitsi mobile app works fine. If i authorize first, then click 'use the app' in the browser window i am authorized in the app.
A simple url open from the app should do the trick a la https://stackoverflow.com/a/2201999
Sure, if you don't need the second click on'open in app' in the browser with the webview, than that way would be preferable

**Comment by saghul** [comment]
Right, you could use Linking.openURL then I guess.

**Comment by celevra** [comment]
+1

**Comment by saghul** [comment]
This is working now!

The meet.jit.si auth works on mobile as well starting with version 23.4 and SDK 8.4.
