### ISSUE TITLE
Incorrect browser detection "It looks like you're using a browser we don't support"

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi-meet#11170]
Eeeehhhh yes I do, just blocked the UA. 

Is it not a bit old fashioned to rely a User Agent string? And why not have link to try anyway?

apt list --installed | grep -i jitsi

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

jitsi-meet-prosody/stable,now 1.0.4628-1 all [installed,upgradable to: 1.0.5913-1]
jitsi-meet-web/stable,now 1.0.5913-1 all [installed,auto-removable]
jitsi-meet-web-config/stable,now 1.0.5913-1 all [installed,auto-removable]
jitsi-videobridge2/stable,now 2.1-634-gff8609ad-1 all [installed,auto-removable]

**Comment by saghul** [comment]
Generally speaking we do feature detection, but there are things one can't detect (for example transceivers being slow in Chromium < 96) so we have to use UA string based version detection.

**Comment by f1-outsourcing** [comment]
Currently it is like this that if the UA is not set, you can not do anything. That is worse than trying to join somehow.
An option is also to make the links for browsers clickable so if a there is an unknown UA, someone can just click firefox or what ever he wants try.

**Comment by saghul** [comment]
You are welcome to give it a try and send PRs with fixes.

**Comment by f1-outsourcing** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.

I am not getting the password reset email. (Although I do not need to reset, because I have the correct password here)
