### ISSUE TITLE
React-native-webrtc not found package org.webrtc 

### ISSUE THREAD

**Issue by daxiondi** [jitsi/jitsi-meet#11178]
For some reason, I'm building my own sdk, after cloning *jitsi-meet*, installing all dependencies using 
```
npm install, 
```
and then using
```
./android/scripts/release-sdk.sh /tmp/repo
````
command, I got the following 

```
error node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCView.java:21: error: package org.webrtc not foud
```

I try to rebuild react-native-webrtc using npm. And delete node_modelus during the install, there is no error, but still, is there any error in the distribution of jitsi-meet?

## version
```
 "react-native-webrtc": "1.94.1"
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```
node -v

v14.19.1

npm -v
8.5.5

**Comment by saghul** [comment]
Do you see a message about downloading the WebRTC binaries?

**Comment by daxiondi** [comment]
> 您是否看到有关下载 WebRTC 二进制文件的消息？

Yes, I used npm rebuild react-native-webrtc to see the downloaded webrtc binary info

**Comment by saghul** [comment]
And do they show up in node_modules/react-native-webrtc/android/libs/

**Comment by daxiondi** [comment]
Thanks, I re-deleted the project, and cloned and it works fine now
