### ISSUE TITLE
bad quality of outgoing video / Not getting password reset link

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi-meet#11182]
1. Can someone email me a password for the community forum access.

2. After upgrading and testing, it looks like my outgoing video quality is just bad what ever I try, received video is much better. Quality of the video stream is still low when having 2 clients on the same wifi network (which should activate the p2p mode not?)

I was wondering how jitsi is deciding on what video quality to use
- where/what test is being done?
- can this test be influenced because of limited access due to firewall or qos settings

maybe it is good to have an option to see the 'real' video quality 
https://github.com/jitsi/jitsi-meet/issues/11181

current config:
```
    resolution: 544,
    constraints: {
        video: {
             height: {
                 ideal: 720,
                 max: 800,
                 min: 480
             }
         }
    },

    channelLastN: -1,
    enableWelcomePage: true,
    p2p: {
        enabled: true,
        stunServers: [
            { urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443' }
        ]
    },
```

**Comment by paweldomas** [comment]
have you tried removing the setting for custom resolution? does it change anything?

**Comment by saghul** [comment]
> 1. Can someone email me a password for the community forum access.

Looks like Discourse had received too many email bounces in the past. I reset the counter, try resetting your password again please.

**Comment by f1-outsourcing** [comment]
I did not get it still. Is it possible to just enable it? I just keep unique passwords in a offline password manager, so the password that I have is ok.
