### ISSUE TITLE
dyld: Library not loaded: @rpath/WebRTC.framework/WebRTC

### ISSUE THREAD

**Issue by yanghuabiao** [jitsi/jitsi-meet#11180]
Hi, I have a problem ：

dyld: Library not loaded: @rpath/WebRTC.framework/WebRTC
  Referenced from: /private/var/containers/Bundle/Application/D1987A51-8248-4E0A-9155-B06AF74B6DFD/MyTest_1.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
Message from debugger: Terminated due to signal 6

what should i do?

![截屏2022-03-21 下午5 01 52](https://user-images.githubusercontent.com/16264932/159231521-6b8da9ba-96dd-46d0-827e-b7b0945f973e.png)

**Comment by saghul** [comment]
You need to add the WebRTC framework too.
