### ISSUE TITLE
key and cert invalid + conference focus error

### ISSUE THREAD

**Issue by Adavo** [jitsi/jitsi-meet#1118]
Hello,

I wanted to try jitsi-meet on a VM.
I start from a clean debian, latest version with nginx installed.

I install jitsi-meet and specify my ip address as hostname.
Everything seems "ok", but when I executed nginx -t , nginx tell me that the key/crt is invalid (indeed, the key is an empty file).

I have created a RSA key myself through openssl and I can access to the jitsi-meet website.

But then when I want to join a chan, I have multiples popup at the bottom right corner of the video 
"Conference focus"
"focus MY_IP not available"

I can see my webcam on the bottom right corner but I can't see other's.
I don't understand what I have to do next. I check https://github.com/jitsi/jicofo/blob/master/README.md but don't really understand if I need to change some settings or not.

Thanks for your help.

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems before opening an issue.
Check your jicofo logs, those popups means that jicofo is not connected to prosody. I don't get the key errors, if you do not specify any certs, self signed will be autogenerated.
