### ISSUE TITLE
DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer.

### ISSUE THREAD

**Issue by umairgillani94** [jitsi/jitsi-meet#11192]
### Description:
Jitsi crashing with Mic and sound issue when room is created in audio mode. Following are the errors
<img width="577" alt="image" src="https://user-images.githubusercontent.com/31413820/159468947-d6c75620-432c-45de-9643-a096ac53d5e2.png">

### Steps to reproduce:

1. User A join room in audio mode and audio muted as well. (Permissions asked and allowed)
2. User B join room in audio mode and audio muted as well. (Permissions asked and allowed)
3. User A or User B unmute the mic either of both user will get the error and will not be able to send voice to user user (error logs shared above)

### Expected behavior:

User should be able to talk and listen each other

### Actual behavior:

User A or B not able to listen each other because of error on any side

Errors:
[modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=P2P,initiator=true,sid=49b1c954bc46] Replace track error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

[JitsiConference.js] replaceTrack failed: Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer. Script: null Line: null Column: null StackTrace:  Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

[modules/statistics/RTPStatsCollector.js] <ti._processAndEmitReport>:  No participant ID returned by LocalTrack[2,audio]

### Server information:

- Jitsi Meet version: latest deployed on meet.jit.si, and for on premise deployment 2.0.7001-1
- Operating System: Linux

### Client information:

- Browser / app version: Google Chrome/
- Operating System: Version 99.0.4844.83 (Official Build)

### Additional information:

Have faced this issue on both meet.jit.si and my on premise deployment.

@saghul Can you please look into this.

**Comment by jallamsetty1** [comment]
Fixed here - https://github.com/jitsi/lib-jitsi-meet/commit/e2b453a24847a5b9d64161d8431edd2073ec6473
