### ISSUE TITLE
Errors when installing jitsi-meeting

### ISSUE THREAD

**Issue by adambarnett52** [jitsi/jitsi-meet#1119]
Hi

I have cloned the latest version of jitsi-meet and are getting some errors when trying to install 

OS: Unbuntu  14.0.4 
- sudo apt-get install npm nodejs-legacy 
- git clone https://github.com/jitsi/jitsi-meet.git
- npm install 

``
> lib-jitsi-meet@0.0.0 install /usr/share/jitsi-meet/node_modules/lib-jitsi-meet
> webpack -p
/usr/share/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:23
                    child_process.execSync( // eslint-disable-line camelcase
                                  ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/usr/share/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:23:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/share/jitsi-meet/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/share/jitsi-meet/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:456:26)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.13.0-100-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
``
``
npm ERR! lib-jitsi-meet@0.0.0 install: `webpack -p`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the lib-jitsi-meet@0.0.0 install script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lib-jitsi-meet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lib-jitsi-meet
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lib-jitsi-meet
npm ERR! There is likely additional logging output above.
``
``
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/jitsi-meet/npm-debug.log
root@meet:/usr/share/jitsi-meet#
``

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems, before opening issues.
Can you use the latest LTS version (6.x.x) from https://nodejs.org/ and share your results.
