### ISSUE TITLE
Custom room settings before building container

### ISSUE THREAD

**Issue by EforestHD** [jitsi/jitsi-meet#11197]
Hi, we are using jitsi meet web on docker and would like to have a proper way to customize the room settings. 
We would like to remove some buttons like "prejoin conference". We are aware of manipulating certan code of the GUI after we build our container, but we would like to customize the settings before we build the container.

Could it be possible to parameterize the desired settings right before we build our container?

Thank you very much for your help!

Kind regards,
Ewald.

**Comment by saghul** [comment]
Are you using our Docker images? It's already possible to set many configuration settings, which generate the appropriate config file on container boot.
