### ISSUE TITLE
Cut off alert message

### ISSUE THREAD

**Issue by EforestHD** [jitsi/jitsi-meet#11198]
Hi, we noticed a bug that cuts off the last letters of an alert message. We are using jitsi meet as a plugin inside our element web matrix.
Here are the steps to reproduce our bug:

A moderator creates an appointment inside element web for a jitsi conference as well as a lobby.
After that a guest uses the link to join the appointment.
Then the guest tries to join the lobby.
The moderator gets an inquiry from the guest for joining the lobby and declines said inquiry.
Then the guest gets an alert message thats too short for him to interpret.

As you can see on my screenshot we can't clearly interpret what the last letters are saying. 

Thank you for your help!

Kind regards,
Ewald.

![issueBug](https://user-images.githubusercontent.com/57798772/159654932-3d07f64b-3003-4740-b2cc-5de997574978.png)

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/pull/11208
