### ISSUE TITLE
Screen sharing does not go above 5 FPS when the VP9 codec is enabled

### ISSUE THREAD

**Issue by TiberiuD** [jitsi/jitsi-meet#11206]
### Steps to reproduce:

1. Two people join a Jitsi room. We have tested this on the official Jitsi instance: https://meet.jit.si/HandyActivistsSealFormerly, yet the issue persists on our self-hosted Jitsi running on Docker.
2. One of the participants starts a screen share. Regardless of the setting in the Settings>More>Desktop sharing frame rate, the stream runs at 5-6 FPS.
3. If that same participant also enables their webcam, the combined screenshare + camera stream runs at 30 FPS.

### Expected behavior:

The screen sharing stream should run at the framerate configured in the Settings.

### Actual behavior:

The screen sharing stream ignores any settings in the client side or in config.js:

Screen sharing without camera:
![image](https://user-images.githubusercontent.com/10258201/159763475-ec2ce236-9904-40ee-ac9b-31a25c671979.png)

Screen sharing with camera:
![image](https://user-images.githubusercontent.com/10258201/159763657-1e114c64-503a-40b8-9f4d-afc4933c6b4c.png)

Settings during both scenarios:
![image](https://user-images.githubusercontent.com/10258201/159763591-c0efff6f-0b3f-4068-804a-d09603a3f930.png)

### Server information:

- Jitsi Meet version: jitsi/web:stable-6865 + jitsi/prosody:stable-6865 + jitsi/jicofo:stable-6865 + jitsi/jvb:stable-6865 (AS WELL AS the version running on meet.jit.si)
- Operating System: `Linux jitsi 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`
- Docker version: `Docker version 20.10.12, build e91ed57`

### Client information:

- Browser / app version: Google Chrome `Version 99.0.4844.82 (Official Build) (64-bit)`
- Operating System: Windows 10 `Microsoft Windows Version 21H2 (OS Build 19044.1586)`

### Additional information:

This started happening after we enabled VP9 as a preffered codec. Running the same configuration while using VP8, the bug doesn't manifest.

Relevant .env settings (the equivalent settings were tried directly in the config.js file):
```
DESKTOP_SHARING_FRAMERATE_MIN=5
DESKTOP_SHARING_FRAMERATE_MAX=30
ENABLE_CODEC_VP9=true
ENABLE_CODEC_VP8=true
ENABLE_CODEC_H264=false
VIDEOQUALITY_PREFERRED_CODEC=VP9
P2P_PREFERRED_CODEC=VP9
```

**Comment by fippo** [comment]
sounds like https://bugs.chromium.org/p/webrtc/issues/detail?id=13016

**Comment by rasos** [comment]
This is a known issue and has been discussed [here](https://community.jitsi.org/t/suddenly-shared-screen-is-hard-to-read-blurred-meet-jit-si/102716/61).

We have chosen the workaround: 

      DESKTOP_SHARING_FRAMERATE_MAX=5

If a user needs to show higher framerates s:he can try by setting those manually.
