### ISSUE TITLE
Error installed jicofo

### ISSUE THREAD

**Issue by adambarnett52** [jitsi/jitsi-meet#1120]
I tired to do the following 

- apt-get install default-jdk ant
- git clone https://github.com/jitsi/jicofo.git
- cd jicofo && ant dist.{os-name}

``
Buildfile: /usr/share/jicofo/build.xml

BUILD FAILED
/usr/share/jicofo/build.xml:54: Problem: failed to create task or type antlib:org.apache.maven.artifact.ant:dependencies
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration.
Action: Check that the implementing library exists in one of:
        -/usr/share/ant/lib
        -/root/.ant/lib
        -a directory added on the command line with the -lib argument

Total time: 1 second

``

**Comment by damencho** [comment]
Please use the mailinglist for problems and questions.
When using ant you need maven-ant-tasks installed, instructions are in the beginning of the build.xml file.
You can also skip ant and just use maven:
mvn -U clean package -DskipTests -Dassembly.skipAssembly=false
