### ISSUE TITLE
remoteVideoMenu options not working as expected

### ISSUE THREAD

**Issue by corby-github** [jitsi/jitsi-meet#11213]
### Description:

The `remoteVideoMenu` options are not working as expected. (self hosted, 2.0.7001)

https://github.com/jitsi/jitsi-meet/blob/fd9d19a951c53d915570fb3834f23060d81bcdd3/config.js#L981

When the following options are modified, not all work properly in the browser or SDKs.
```
remoteVideoMenu: 
{
      disabled: true,
      disableKick: true,
      disableGrantModerator: true,
      disablePrivateChat: true
}
```

### Steps to reproduce:

1. Add the above `remoteVideoMenu` options to your `/etc/jitsi/meet/[domaine]-config.js`
2. Join a meeting with 2 or more people. 

Note: In the browser and the SDK: `disableKick: true` works properly

### Behavior:

|  property | Browser      | Android SDK | iOS SDK |
| ----------- | ----------- | ----------- |----------- |
|  disabled = true | still shows      | still shows | still shows |
|  disableKick = true  | ✓ ok     | ✓ ok| ✓ ok |
|  disableGrantModerator  = true | ✓ ok      | still shows | still shows |
|  disablePrivateChat = true  | still shows      | still shows | still shows |

### Server information:

- Jitsi Meet version: [2.0.7001](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_7001)
- Operating System: Ubuntu 20.04.3 LTS

### Client information:

- Browser: Chrome Version 99.0.4844.83 (Official Build) (arm64)
- SDK: Latest as of today
- Operating System: macOS

**Comment by damencho** [comment]
> remoteVideoMenu: 
> {
>       disabled: true,

Where did you see the disabled option, in which doc?

**Comment by damencho** [comment]
Ups I saw it, it is in master.

**Comment by damencho** [comment]
The options were added 10 days ago, and are not available in the stable release.

**Comment by damencho** [comment]
You can switch to the latest from unstable to use them.

**Comment by corby-github** [comment]
👍 Sorry for the confusion. Yeah - This is what I get for pulling config.js from master after an update. I ended up with a mismatch of options <--> release

**Comment by damencho** [comment]
:) No worries.
