### ISSUE TITLE
feat : Pinned chats feature in Chats and Polls 

### ISSUE THREAD

**Issue by kb-0311** [jitsi/jitsi-meet#11220]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

After using jitsi meet for a while a lot of my peers feel that the one key feature it is missing is the pinned chat feature where the important chats could be pinned 

**Describe the solution you'd like**
Please describe the desired behavior.

![20220317_162350 (1)](https://user-images.githubusercontent.com/96020697/160137130-58823963-2e86-4569-8c31-49d2b9728a22.jpg)

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
I like the idea!

**Comment by kb-0311** [comment]
Thanks :smiley:  !!

Btw as you know I am the original author of [this post ](https://community.jitsi.org/t/adding-the-pinned-chat-feature-and-resizable-chat-window-on-mobile/112616/8) .

I would like to start working on the pinned feature that I proposed, please.
