### ISSUE TITLE
JWT token generation with lobby feature as parameter in the payload

### ISSUE THREAD

**Issue by Sbhonagiri** [jitsi/jitsi-meet#11227]
Hello @saghul @jallamsetty1 

Could you please let me know the parameter to be set for lobby feature in the JWT token payload, so that lobby could be enabled for a meeting through JWT token

{
  "aud": "jitsi",
  "iss": "",
  "sub": "",
  "room": "*",
  "iat": 1648289335,
  "exp": 1648292935,
  "context": {
    "user": {
      "name": "Santosh",
      "email": "santosh@abc.com",
      "affiliation": "owner"
    },
    "features": {
      "recording": true,
      "livestreaming": true,
      "screen-sharing": true
    }
  }
}

**Comment by saghul** [comment]
There is no such a thing.

The lobby can be enabled once you enter the meeting.

**Comment by Sbhonagiri** [comment]
> There is no such a thing.
> 
> The lobby can be enabled once you enter the meeting.

Thanks for the information
