### ISSUE TITLE
Add Noise Cancellation feature

### ISSUE THREAD

**Issue by IplaygamesIhate** [jitsi/jitsi-meet#11224]
**Is your feature request related to a problem you are facing?**
Yes, I have a dynamic mic and picks up a lot a noise. 

**Describe the solution you'd like**
Add Noise Cancellation feature like in discord or an audio gate for now

**Describe alternatives you've considered**

**Comment by emdrremote** [comment]
We also have clients that have issues with background noises and would love to see this implemented.

**Comment by Freddie-m** [comment]
It exists already. If you're hosting your own server, you can configure it in your config.js (disableNS: true). If not, you can pass it as a URL param e.g. https://meet.jit.si/meetingname#config.disableNS=true

**Comment by emdrremote** [comment]
Is there a reason this isn't enabled by default?

**Comment by saghul** [comment]
It is enabled by default already. This capability is provided by the browser. We are currently not adding anything on top.

**Comment by emdrremote** [comment]
Ah, okay, thanks.

**Comment by IplaygamesIhate** [comment]
If I add Jitsi integration in element. It doesn't enable noise suppression. Can you do something to it

**Comment by saghul** [comment]
I don't know what configuration the Element integration has, but I doubt it disables noise suppression.

**Comment by G2G2G2G** [comment]
@IplaygamesIhate it has it, but jitsi doesn't really suppress noise well so you don't really notice it vs other softwares that have a bigger budget to do things like that

**Comment by saghul** [comment]
Please follow https://github.com/jitsi/jitsi-meet/pull/11547
