### ISSUE TITLE
Latest jitsi screen sharing not working 

### ISSUE THREAD

**Issue by riyas145** [jitsi/jitsi-meet#11231]
I'm Using latest jitisi maven repo and latest react native version when i click screenshare app request permission if i give yes then my camera will go off automatically (that works expected ) but my mobile screen not get shared  there is anything that i  need to from my side? @saghul  please help me regard this

**Comment by saghul** [comment]
Can you reproduce it with the Jitsi Meet app?

**Comment by riyas145** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk
followed the steps in hand book and use example code to run  in same page
![image](https://user-images.githubusercontent.com/57698276/160352924-2e270152-e428-45d6-83a1-d85b01e697f5.png)
![image (1)](https://user-images.githubusercontent.com/57698276/160352960-1cc4f209-72f2-44c8-8301-728e780dc3cb.png)

**Comment by riyas145** [comment]
@saghul  please check this

**Comment by riyas145** [comment]
@saghul  ples check this

**Comment by riyas145** [comment]
any Updates @saghul

**Comment by riyas145** [comment]
Sorry don't mind, im on clue less  
I'm really need you help 😢
