### ISSUE TITLE
Filmstrip and tile view are blinking when participants join or left.

### ISSUE THREAD

**Issue by nekym** [jitsi/jitsi-meet#11237]
### Description:
The problem is connected with the implementation of the FixedSizeGrid which you started to use in the web/Filmstrip.js.
When any user are left the room then all participants with video after him are blinking in the filmstrip/tile view.
It's happening because of update of the array with participants and react recreates all ThumbnailWrapper component after the exited participant.

### Steps to reproduce:
1. You have a room with 3+ participants. All participants turn the video on.
2. Open tileview or just check filmstrip. You have an array with participants [1, 2, 3, 4, 5, ... ]
3. Participant number 2 are left the room.
4. You will see that participant 3, 4, 5... will switch off their video for a while and then turn it on again (I call it blinking).

### Expected behavior:
Participants will not blink when somebody join or left.

**Comment by robertpin** [comment]
This seems to be fixed. I can repro the issue on meet.jit.si, but not on master
