### ISSUE TITLE
stop recording when the person who started the recording hangs up.

### ISSUE THREAD

**Issue by backidvteam** [jitsi/jitsi-meet#11241]
**Is your feature request related to a problem you are facing?**

Currently we record the video call with Jibri, there are cases where the user who started the recording (room administrator) hangs up the video call without stopping the recording previously. This action of hanging up also implies that the rest of the users are expelled and the video is available approximately 45 to 60 seconds later, this happens when Jibri detects that there is no one in the video call adding extra content in the video with no one in the video call.

**Describe the solution you'd like**

The hang up button may trigger the stop recording action.

We need the recording to stop automatically to download and make it available in a quick period (less than 5 seconds), yet Jibri makes the recording available when everyone leaves with a timeout of about 15 to 30 seconds.

Indicate that we have implemented this action in our repository and we have tested this action, but we have detected that if the video should last 20 seconds for example, it cuts the final seconds, it does not record everything until the moment of hanging up.

**Comment by saghul** [comment]
We have no plans to implement this, sorry.
