### ISSUE TITLE
Help user know they can refresh if they encounter a problem

### ISSUE THREAD

**Issue by ImaCrea** [jitsi/jitsi-meet#11246]
Hi there,

We're hosting jitsi for many organizations here and we're very happy with it. Thank you for such a great piece of software.

I've been doing workshops recently where I introduce people to Jitsi and help them getting familiar with it. The recent improvements in terms of UX/UI are helping making it easier with each version but there's something I've noticed that might interest you.

From my observations, many "average" users don't get they can refresh their browser in case something is not working well. They're not used to it with this kind of software I guess. Instead, they see there's a problem (for example I'm the only one who can't hear this person's mic) they explain it in the chat ("I can't hear you"), everyone gets frustrated, there's no apparent solution ("user tries to switch on/off their mic but nothing changes), finally blame the software and leave. Whereas a simple refresh could have solved the issue.

Therefore, I'm pretty convinced that if there was an elegant way to suggest users to refresh his/her browser in case of an error such little add could be a great win for the overall experience in many cases.

Do you know if there's such feature already planned eventually ?

**Comment by saghul** [comment]
We don't have anything like this planned at this time.

I think it would be really hard to know when to offer that possibility. We already do this for the obvious cases like if the connection breaks, but how would we know if there is some glitch or the user has muted their mic with a hardware button?

**Comment by pierreozoux** [comment]
Hi @saghul!

We discussed this topic, in [this context](https://community.jitsi.org/t/sound-doesnt-work-reload-and-then-it-is-ok-for-the-rest-of-the-conference/113040).

In general, it is true that if there is an issue, if we reload the page, whatever issue it was, it will fix maybe 90% of the issues. So the idea is to help users with this information (regular users, not like us IT engineers, don't have this reflex to reload the page).
Do we present it on the first page before joining the conf "by the way, if you have any troubles, try reloading the page first"?
Do we try to search for an "heuristic" to find out there is an issue and offer the user to reload?
Do we present this info on the "help button" ?

I think this is the kind of discussion.

**Comment by saghul** [comment]
> I think this is the kind of discussion.

Happy to discuss :-)

> Do we present it on the first page before joining the conf "by the way, if you have any troubles, try reloading the page first"?

I think that looks bad, also, there might be no first page if the user joins directly without the prejoin screen.

> Do we try to search for an "heuristic" to find out there is an issue and offer the user to reload?

I'd say this is the way to go, but it's also the hardest thing to do...

> Do we present this info on the "help button" ?

Currently the help button just redirects to a page in the handbook. Maybe we could put some useful stuff there too.

**Comment by emdrremote** [comment]
On our site, reloading will actually break the connection and will not rejoin those in the meeting, they would have to manually rejoin. So I wouldn't want a "reload" feature built into the system unless it was off by default or able to be turned off via a flag in the iframe api.

**Comment by saghul** [comment]
Why would reloading break the conference?
