### ISSUE TITLE
Unable to share screen to Firefox 98.0 viewers on Ubuntu more than once when video cam is off

### ISSUE THREAD

**Issue by OskJonsdottir** [jitsi/jitsi-meet#11240]
### Description:

When the camera permissions are not given, a Firefox user cannot share their screen twice or more (only the first time works, subsequent times show a blank screen in all recipients)

### Steps to reproduce:

1. Start a conference using any browser, and reject video permissions (sender side)
2. Join the same conference from Firefox 96.0 or 96.0.3 or 98.0 in Ubuntu (recipient side)
3. Share screen from the sender side (any browser), then stop sharing, then start again.

### Expected behavior:
 The second time the screen sharing should work just as fine as the first time

### Actual behavior:
The second time (or any subsequent time), the shared screen appears as a blank screen on the recipient side (Firefox).

### Server information:
- Jitsi Meet version: whatever is running right now in meet.jit.si
- Operating System: whatever is running right now in meet.jit.si

### Client information:

- Browser / app version:  Firefox 98.0 / Firefox 96.0.3
- Operating System: Ubuntu 20.10

### Additional information:

This doesn’t happen if a video cam track is created first, probably because, in that case, internally, the video track is replaced by the desktop track when the sharing starts, then replaced again by the video (camera) track when the screen sharing stops, then replaced again by the desktop track when sharing again and so on, so on the client side the event is **“track updated”**, not **“track added”**. Whereas if the video permissions are rejected, the first desktop track is removed (not replaced) from the conference room when the sharing stops and a new track is created when trying to share the video again later on. For some reason, Firefox 98 (latest version) fails when a single participant adds more than one video track to the conference. 

It doesn’t fail on Firefox 90, though.

It might be tangentially related to https://github.com/jitsi/jitsi-meet/issues/7369

**Comment by maxired** [comment]
Not certain it is related, but this seems similar to https://github.com/jitsi/lib-jitsi-meet/issues/1687

**Comment by Bluewind** [comment]
I am also seeing this issue with self-hosted stable/jitsi-meet_6726 and stable/jitsi-meet_7210 instances, as well as the current meet.jit.si instance (as of 2022-04-27).

Recipient (with the problem): Firefox 98.0.2 on Arch Linux
Sender: Chromium 100.0.4896.60 (Official Build) Arch Linux (64-bit)

As for reproduction steps:
* Permissions do not seem to matter, but what matters is whether a camera stream is active or not at the time the firefox receiver joins.
* start a screen share on chrome sender
* observe the screen share on firefox receiver
* stop screen share on chrome sender
* observe firefox not showing screen share any more and going back to tile view
* start screen share on chrome sender again
* observe firefox receiver trying to display screen share, but only showing a black screen instead

When the screen share is disabled for the second time, the firefox console shows this error:
```
[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: TPC[id=1,type=JVB] remote track removal failed - track not found Script: null Line: null Column: null StackTrace:  3924/Ja.prototype._remoteTrackRemoved@https://web-cdn.jitsi.net/meetjitsi_6085.2805/libs/lib-jitsi-meet.min.js?v=6085.2805:2:573166
3924/Ja/this.onTrack/<@https://web-cdn.jitsi.net/meetjitsi_6085.2805/libs/lib-jitsi-meet.min.js?v=6085.2805:2:563530
EventListener.handleEvent*3924/Ja/this.onTrack@https://web-cdn.jitsi.net/meetjitsi_6085.2805/libs/lib-jitsi-meet.min.js?v=6085.2805:2:563489
```

As mentioned in the original description of this issue, if a camera stream is active before the screen share is started (and thus active again once the screen share is stopped), the problem does not occur and the firefox receiver can properly display the second screen share attempt.

Has anyone from the Jitsi team managed to reproduce this yet, or do you need more information?
