### ISSUE TITLE
Can no longer access camera and mic on latest Brave on linux (ubuntu)

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#11244]
Hi guys,

I noticed in the last few days that suddenly my perfectly working self-hosted setup stopped working and I didn't change anything on the server.
Did something change in Chromium recently regarding GUM, because now I can no longer give permission to use my cam and microphone using Brave V1.36.122 based on Chromium 99.0.4844.88 in linux? I suspect the autoupdate of the browser is responsible for this breaking change.

Strangely I tested the same up to date Brave V1.36.122 on my MacBook running Monterey and it worked as expected.

Is anyone else experiencing this behavior?

2022-03-28T20:38:06.063Z [features/base/tracks] Failed to create local tracks ['audio']0: "audio"length: 1[[Prototype]]: Array(0)
...
['audio']0: "audio"length: 1[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}[[Prototype]]: Object DOMException: Requested device not found

2022-03-28T20:38:06.096Z [features/base/tracks] Failed to create local tracks 
['video'] DOMException: Requested device not found

I ended up compiling the latest electron build and have the exact same issue.

I also did a fresh git clone of master and recompiled jitsi-meet but that didn't fix it.

Any ideas?

Thanks

**Comment by saghul** [comment]
I wonder if it's something like this: https://github.com/jitsi/jitsi-meet/issues/11229

**Comment by pdarcos** [comment]
Thanks @saghul 
Sounds like the same issue indeed. I'm going to take a closer look

**Comment by petervnv** [comment]
Not sure what the issue was, maybe it was a hardware bug with the Logitech USB camera, but a recent kernel update seems to have fixed it.
Thanks for your help Saghul

Closing this ticket.
