### ISSUE TITLE
aspectRatio does not work in tile mode if two participants

### ISSUE THREAD

**Issue by slesru** [jitsi/jitsi-meet#11252]
### Description:

We have in config:

 resolution: 720,
    constraints: {
     video: {
        aspectRatio: 16 / 9,
        height: {
            ideal: 720,
            max: 720,
            min: 240
        },
        width: {
            ideal: 1280,
            max: 1280,
            min: 320
        }
      }
    },

It works if we have 3 or more participants,  but if there are two- then  picture is cropped in width to fill screen up, so we get almost 1:1 aspect ratio this is not what we want, we want 16:9 ratio.

### Steps to reproduce:

connect 2 participants to jitsi meet , switch to tile.

### Expected behavior:

keep 16:9 ratio, don't fill empty height and don't crop width

### Actual behavior:

picture is cropped in width, ratio is 1:1

### Server information:

- Jitsi Meet version:  2.0.7001-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version:  chromium  99.0.4844.84  , firefox 98.0.2
- Operating System: Ubuntu 21.10

**Comment by saghul** [comment]
I see the confusion here.


The video constraints are about how the camera is opened, not about how we display video tiles. That constraint helps the browser pick the right resolution when opening the camera.

The tiles size / aspect ratio is a separate concern. You can disable the current tile enlargement behavior with `disableTileEnlargement: true` in the config file.

**Comment by slesru** [comment]
Thank you very much.
Not a bug, just lazy user :-(
