### ISSUE TITLE
CallKit get interrupted after upgrade to iOS 15

### ISSUE THREAD

**Issue by mohammadebrahim** [jitsi/jitsi-meet#11263]
Before iOS15 Jitsi Meet was working well.
From iOS15 and above Jitsi Meet doesn't work properly.

There is a different bug in different versions:

**Jitsi Meet 3.4.2:-**

- When call end status green bar is not going and call kit throw - com.apple.CallKit.error.requesttransaction Code=2

**Jitsi Meet 5.0.0:-**

- When call end status green bar is not going and call kit throw - com.apple.CallKit.error.requesttransaction Code=4.

- During incoming call Jitsi Meet controller dismiss automatically but the audio is ON.

# SDK & iOS version
- Jitsi Meet version: 5.0.0 & 3.4.2

- Operating System: iOS15

**Comment by saghul** [comment]
> From iOS15 and above Jitsi Meet doesn't work properly.

Can you please a bit more detailed?



> **Jitsi Meet 3.4.2:-**
> 
>     * When call end status green bar is not going and call kit throw - com.apple.CallKit.error.requesttransaction Code=2

SDK 3 is old and unsupported.



> **Jitsi Meet 5.0.0:-**
> 
>     * When call end status green bar is not going and call kit throw - com.apple.CallKit.error.requesttransaction Code=4.

I cannot reproduce this, when the call is hangup the green bar disappears. Can you reproduce this with our sample apps?



> * During incoming call Jitsi Meet controller dismiss automatically but the audio is ON.

Not sure what you mean, we don't do incoming calls. Is this part of your app?

**Comment by mohammadebrahim** [comment]
@saghul can you please share a sample code with Callkit would be helpful for me.

**Comment by saghul** [comment]
CallKit integration is built right in, you don't need anything special, look at the samples here: https://github.com/jitsi/jitsi-meet-sdk-samples

**Comment by mohammadebrahim** [comment]
@saghul  Thanks for your quick response.

When I get a push notification I initiate Callkit below is the code -

` let configuration = CXProviderConfiguration(localizedName: "App Name")`
           ` configuration.maximumCallGroups = 1`
            `configuration.maximumCallsPerCallGroup = 1`
          `  configuration.supportsVideo = true`
       `     configuration.supportedHandleTypes = [.generic]`
       `     if(Global.shared.provider == nil){
                Global.shared.provider = CXProvider(configuration: configuration)
            }`
          `  Global.shared.provider!.setDelegate(self, queue: nil)`
           ` var handle : CXHandle?`
           ` handle = CXHandle(type: .generic, value: notification.title)`
          `  let update = CXCallUpdate()`
            `update.remoteHandle = handle`
           ` update.hasVideo = true`
            `update.supportsHolding = true`
            `update.localizedCallerName = Global.shared.tabletUser.full_name //Caller name is given as fullname`
            `Global.shared.provider!.reportNewIncomingCall(with: incommingCallUUID, update: update, completion: { error in
                print("Error in the call \(error)")
            })`

When the user accepts the call Jitisi controller is presented with all the options like url, etc

And you are saying Callkit is inbuild I want to know how to implement inbuild Callkit.

**Comment by saghul** [comment]
Look into the JMCallKitProxy class.

**Comment by mohammadebrahim** [comment]
@saghul I set this `JMCallKitProxy.enabled = false` than also.

**Comment by saghul** [comment]
Are you using CallKit in any other way in your app? If not then use JMCallKitProxy, since it's already integrated.

**Comment by mohammadebrahim** [comment]
Okay thanks a lot @saghul

**Comment by Aydogdyshka** [comment]
I used JMCallkitProxy when receiving voip, on answer I launch the jitsi but the CallKit call disappears and nothing happens in iOS 17
