### ISSUE TITLE
Event that is triggered before the user hangup

### ISSUE THREAD

**Issue by turi4200** [jitsi/jitsi-meet#11274]
Tried 

videoConferenceLeft
readyToClose

I am trying to stop the streaming ( api.executeCommand('stopRecording', 'stream') ) 
when user hangs up.

but Conference is undefined when the events are triggered
(it is triggered after the user leaves, not before)...

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
You can try: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#toolbarbuttonclicked
