### ISSUE TITLE
Incorporate custom branding options into the normal config

### ISSUE THREAD

**Issue by robintown** [jitsi/jitsi-meet#11276]
**Is your feature request related to a problem you are facing?**
I want to be able to theme Jitsi Meet at runtime, without necessarily having control over the `dynamicBrandingUrl` used by the deployment.

**Describe the solution you'd like**
To take all of the branding config options normally controlled by `dynamicBrandingUrl`, and additionally make them configurable through `config.js` and overridable at runtime.

**Describe alternatives you've considered**
https://github.com/jitsi/jitsi-meet/issues/11273

**Comment by damencho** [comment]
What is the problem with implementing the dynamicBrandingUrl service that will be returning what you want to change?

**Comment by damencho** [comment]
That's the thing, those deployments may want to keep how they look when used. The same and for meet.jit.si.

**Comment by saghul** [comment]
We have no plans to implement this, sorry.
