### ISSUE TITLE
Allow the dynamic branding URL to be overridden at runtime

### ISSUE THREAD

**Issue by robintown** [jitsi/jitsi-meet#11273]
**Is your feature request related to a problem you are facing?**

The web app in which I am embedding Jitsi Meet can be configured to connect to any arbitrary Jitsi Meet instance. I would like to be able to specify custom colors to create a consistent experience that feels more native to the host app, regardless of which instance is being used. However, the IFrame API ignores any `dynamicBrandingUrl` overrides that you give it.

**Describe the solution you'd like**

Add `dynamicBrandingUrl` to the list of config options that can be overridden.

**Describe alternatives you've considered**

Even if I were only dealing with a single Jitsi Meet deployment, a static `dynamicBrandingUrl` wouldn't work for my use case, since my web app supports multiple color themes.

**Comment by robintown** [comment]
That's unfortunate. Perhaps what I should really be requesting, then, is to incorporate branding parameters into the main config?

**Comment by damencho** [comment]
What parameters do you mean?

**Comment by stat1x** [comment]
Hi @damencho,
What are security issues allowing dynamicBrandingUrl to be overwritten?
I need this aspect in the app I am developing now which has different theme.

**Comment by saghul** [comment]
If you have your own deployment you can change it in your config.js

Making it overridable would mean you can trigger a user visiting an arbitrary URL you crafted.

**Comment by stat1x** [comment]
Let me explain the issue I have.

I have two themes in the app.

One for student and one for teacher.

The app is constructed like this :

```
teacher/page.js
<TeacherLayout>
  <JitsiMeeting /> this one should have yellow as primary color
</TeacherLayout>

student/page.js
<StudentLayout>
  <JitsiMeeting /> this one should have pink as primary color
</StudentLayout>
```

How would you achieve this ?

I have my own deployment with the dynamicBrandingUrl set in the custom-config.js.

But I don't see how I could have 2 different themes from the same instance if this parameter is not overridable.

**Comment by saghul** [comment]
I'm afraid we currently can't suopport your use case. My suggestions are:

- Add it yourself to the whitelist and rebuild the frontend (this might also be attainable by manually patching the JS bundle)
- Make the color distinction outside of the meeting, in the enclosing component
