### ISSUE TITLE
Joining breakout room function failure on latest IOS app

### ISSUE THREAD

**Issue by NicoleYWDu** [jitsi/jitsi-meet#11290]
### Description:

When using Jitsi Meet version 22.1.1 on IOS app, user can only add breakout rooms but cannot join in or remove breakout rooms

### Steps to reproduce:

1. Join the meeting and open 'participants'
2. Click on 'Add Breakout Room'
3. Click on 'Breakout room 1 (0)'

### Expected behavior:

Join in the room and can also remove the room

### Actual behavior:

Can only expand and contract the participants list for the breakout room by clicking on the room name. No 'join' button like web shown or other methods to join in the room.

### Server information:

- Jitsi Meet IOS app version: whatever is running right now in meet.jit.si
- Operating System: whatever is running right now in meet.jit.si

### Client information:

- IOS app version: version 22.1.1
- Operating System: IOS 15.0.2

**Comment by saghul** [comment]
You need to long press on the breakout room name and a bottom sheet will be presented with options to join or remove the room.
