### ISSUE TITLE
Could not get resource 

### ISSUE THREAD

**Issue by PartapSBimrah** [jitsi/jitsi-meet#11300]
I got this error while processing. Am using the 3.5.0 version. Please see this and let me know 

`Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.5.0/jitsi-meet-sdk-3.5.0.pom'.
`

**Comment by saghul** [comment]
Looks like you might be missing our maven repo, we don't publish to jitpack. See: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#use-pre-build-sdk-artifactsbinaries

Also, 3.5.0 is ancient, I recommend to you update to SDK 5.
