### ISSUE TITLE
URL param taking precedence over requireDisplayName (config.js)

### ISSUE THREAD

**Issue by federico-ntr** [jitsi/jitsi-meet#11309]
**Is your feature request related to a problem you are facing?**
I'm in a scenario in which authenticated users (LDAP) have to set their display name, since Jitsi doesn't take it from the LDAP server, while anonymous user should join the meeting with the name already set. To do so I set requireDisplayName to true, but doing so Jitsi requires the display name even if it's been passed as a URL param.

**Describe the solution you'd like**
I think it would be better for the url param setting to take precedence over config.js. I don't know the codebase enough to understand if it's difficult or not possible at all.

**Comment by saghul** [comment]
How are you passing the display name?

**Comment by federico-ntr** [comment]
By appending #userInfo.displayName="displayName" to the URL. With requireDisplayName set to false it works as expected.

**Comment by saghul** [comment]
I think we apply those parameters too early on web, the local participant doesn't yet exist. @damencho do you remember where we sync those with the local participant on web?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/d22d95e8a5b419940856391933d01a057ad6e370/react/features/base/settings/middleware.js#L201
This is on SET_LOCATION_URL ... 
And I see we handle requireDisplayName on CONFERENCE_JOINED ... so I'm not sure how this can happen.

**Comment by damencho** [comment]
And I cannot reproduce this on my dev instance.

**Comment by saghul** [comment]
> https://github.com/jitsi/jitsi-meet/blob/d22d95e8a5b419940856391933d01a057ad6e370/react/features/base/settings/middleware.js#L201
> 
> This is on SET_LOCATION_URL ... 
> 
> And I see we handle requireDisplayName on CONFERENCE_JOINED ... so I'm not sure how this can happen.
> 
> 

But does the local participant exist that early?

**Comment by damencho** [comment]
Well if it worked for me, maybe it exists ... but yeah maybe in some cases that causes the issue ...

**Comment by federico-ntr** [comment]
That's weird, I have disabled requireDisplayName to follow the steps again and detail them and when I enabled it again everything worked fine. Maybe it was some caching problem but it's strange because I open a new Incognito window everytime.

I'm closing the issue, thanks for your help!
