### ISSUE TITLE
(multi-stream) no remote video on large screen for screenshare

### ISSUE THREAD

**Issue by mabocoglu** [jitsi/jitsi-meet#11323]
### Description:

While source name signalling and multi stream enabled on the system, screenshare video cannot be visible on the remote side on large video thumbnail. It can be seen on the small video on the right thumbnail list.

### Steps to reproduce:

1.  Open a conference
2.  Add another participant to this conference (opened another tab in browser)
3.  Share a screen from the first participant

### Expected behavior:

Screenshare video should be seen the large screen

### Actual behavior:

Screenshare video can be seen only in the small thumbnail on the right side. While it is on the large screen, there is only title of the participant's name.

### Server information:

- Jitsi Meet version: 2.0.7170
- Operating System: Ubuntu 20.04.4 LTS

### Client information:

- Browser / app version: Google Chrome 100.0.4896.75
- Operating System: Windows 10 x64 21H2

### Additional information:

sourceNameSignalling and sendMultipleVideoStreams enabled on JMT and multi-stream is enabled on JVB

![screenshare-no-video](https://user-images.githubusercontent.com/4979958/161912716-c9f85de5-5e3d-4184-b2b5-dc70ca1202ab.png)

**Comment by gpatel-fr** [comment]
Why do you think that this is ready ?
See this [PR](https://github.com/jitsi/jitsi-meet/pull/11272). Seems necessary it is merged for anything to begin to work for real.

**Comment by mabocoglu** [comment]
> Why do you think that this is ready ?
> See this [PR](https://github.com/jitsi/jitsi-meet/pull/11272). Seems necessary it is merged for anything to begin to work for real.

Because there is commit on master about the PR you mentioned. And it is verified. I don’t know why this PR is not defined as merged while there is a verified commit on master branch. 

https://github.com/jitsi/jitsi-meet/commit/70090fd716e0aedc55ec1ea1c09bf1a91ee4e3ca

**Comment by gpatel-fr** [comment]
Duh. You are correct; I missed this one. It's too late now for me, but you could give a try to alpha.jitsi.net

**Comment by gpatel-fr** [comment]
This morning updated to 7173 and Tada ! the new tile appears. 
A preliminary test shows already bugs, but that's to be expected. FTR, after joining a third workstation to the party, the new user don't see anything on the share tile (shown as N/A in the bandwidth indicator), even if the sharing is stopped and shared  again. This is not caused by initial connexion as P2P since it's disabled at config level. Also the screen shared shows in participants pane. Trying to send a message to X's screen is possible but results in an error - X's screen is not in the room.
Why am I dreading the new stable, I don't know :-)

**Comment by mabocoglu** [comment]
> Duh. You are correct; I missed this one. It's too late now for me, but you could give a try to alpha.jitsi.net

As I see, alpha.jitsi.net does not use sendMultipleVideoStreams. Because, whenever I share something, it replaces the camera video.

**Comment by gpatel-fr** [comment]
@mabocoglu 
these parameters are included in the whitelist now, you can turn them on by URL. I am doing so on my test server. What is not possible to turn on this way is the JVB flag for sure.

**Comment by mabocoglu** [comment]
Resolved on 2.0.7185

I am closing this issue
