### ISSUE TITLE
Ability to disable "face centering" feature

### ISSUE THREAD

**Issue by gwillen** [jitsi/jitsi-meet#11322]
### Description:

Jitsi Meet recently started wiggling my video around in a mysterious and extremely unaesthetic way. Although this is undocumented, I eventually managed to use the chrome dev tools javascript debugger to determine that it was being done by something called "Face Centering Worker", which enabled me to find the source of the problem.

### Steps to reproduce:

Use a recent version of Jitsi Meet. Possibly required: use a camera with a fairly wide aspect ratio, so that Jitsi is cropping the video horizontally.

### Expected behavior:

The visible camera viewport is stable, and if cropped, shows the center of the entire camera viewport.

ALTERNATIVELY: If the visible camera viewport must try to track faces, it does this smoothly and without significantly disrupting the meeting.

### Actual behavior:

Jitsi at first starts very slightly twitching my camera left-right, by maybe 5-10% of the width, at very high speed, making it look like I'm bumping my desk or something. Then later, Jitsi starts wildly flailing my camera view around like it's trying to wave a fly away from its face with the camera. The meeting proceedings are halted, as everyone first starts laughing about the bizarre behavior, then trying increasingly desperately to figure out what the fuck is causing it, and eventually overriding it with a CSS rule by forcing `object-position: initial` on `video` tags to make the suffering stop.

I can't usefully attach a screenshot because the offending behavior is not visible in a static image, as the problem is the wild motion of the camera. It's hard to capture a video of it because it happens sporadically; I think it's very sensitive to lighting and pose conditions, and the worst of it was happening around sunset. Here's an example of the "twitching" behavior, which is significantly less bad than the "wild flailing" behavior seen at other times.

https://user-images.githubusercontent.com/458997/161886586-7c95817e-1e09-4046-b37d-57e70e2cdd18.mov

### Server information:

- Jitsi Meet version: I'm not sure how to tell; whatever's running on meet.jit.si.
- Operating System: No idea.

### Client information:

- Browser / app version: Microsoft Edge 99.0.1150.55
- Operating System: macOS 11.4 "Big Sur"

(The other participants were on differently-configured systems, but my video was the only one going totally crazy, just in case this is somehow an OS or browser issue, rather than just something about my lighting conditions.)

### Additional information:

The idea is cool, but I don't see how this feature can possibly work well for all users in all configurations, poses, camera angles, lighting conditions, etc., and when it fails the failure mode is really bad. I would really like a way to turn this off. Sorry for being snarky; I know that's not a fun way to get a bug report, but the feature is REALLY REALLY ANNOYING. It's twitching at me right now, as I'm typing this. It's like my computer has a tic.

**Comment by saghul** [comment]
PTAL @quitrk

**Comment by quitrk** [comment]
it shouldn't be enabled on the prod site

**Comment by gwillen** [comment]
> it shouldn't be enabled on the prod site

Ah, that makes this make a lot more sense. It definitely was enabled there as of when I filed the issue, as far as I can tell.

**Comment by damencho** [comment]
Yep, we disabled it after we synced offline with @quitrk after your report @gwillen. Thank you!

**Comment by gwillen** [comment]
Awesome, thanks for the quick response!
