### ISSUE TITLE
Support reanimated v2

### ISSUE THREAD

**Issue by yatishAgrawal** [jitsi/jitsi-meet#11339]
### Description:

With the latest react-native-reanimate version 2.6.0 and React Native version 0.68, android is showing a black screen but calls get initiated.

In iOS, everything is working fine as expected. It would be really great help for me if anyone can help me or fix the Jitsi issue side the  SDK

### Steps to reproduce:

1. Create a new project with React Native 68
2. Install the react-native-reanimate version 2.6.0
3. After that start the call with Jitsi, you will see the blank screen. 

### Server information:

- Jitsi Meet version: org.jitsi.react:jitsi-meet-sdk:4.1.0
- Operating System: Android

**Comment by saghul** [comment]
We don't currently support reanimated 2.

**Comment by yatishAgrawal** [comment]
Can you please guide me on how I can implement react-native-reanimate 1 in the case of React Native 68 or 67 version? It would be a great help if you can fix the black screen issue with reanimated 2 other than that everything is working fine.

**Comment by saghul** [comment]
Update to SDK 5, it contains Reanimated v1 integrated already.

**Comment by yatishAgrawal** [comment]
> Update to SDK 5, it contains Reanimated v1 integrated already.


But the react-native-reanimate 1 does not support the above React native 0.65.0, so please do suggest the solution for this.

**Comment by yatishAgrawal** [comment]
@saghul Any update on it please?

**Comment by nirajsharma2022** [comment]
Contact me for jitsi meet installation 
https:/wa.me/+919782533298
skype : ersonusaini

Contact me setup jisti meet android or ios apps or desktop app also we provide scable jitsi meet

**Comment by saghul** [comment]
As I said in https://github.com/jitsi/jitsi-meet/issues/11354#issuecomment-1094709121 the current SDK works just fine with a drawe and reanimated v1.

**Comment by saghul** [comment]
The reason is that it's not straightforward to integrate for our use case and we don't really need it so it hasn't been prioritized.

That said, v3 looks better so we'll probably jumó to v3 directly at some point hopefully soon.
