### ISSUE TITLE
Jitisi Chat Box Pane Showing Blank

### ISSUE THREAD

**Issue by umerbutt03** [jitsi/jitsi-meet#11333]
### Steps to reproduce:

Click on Chat Button from Toolbar Option Buttons

### Server information:

- Jitsi Meet version: 2.0.7001-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chrome
- Operating System: Windows

### Additional information:

![jitsi_chat_box](https://user-images.githubusercontent.com/33699720/162167747-86331cb5-2742-46d7-8ca8-dbfb4c370f8e.png)

**Comment by saghul** [comment]
Do you have any modifications applied to the code?

**Comment by umerbutt03** [comment]
> Do you have any modifications applied to the code?
modifications in below files
All.css
Custom.css
head.html
index.html
interface_config.js
title.html

**Comment by saghul** [comment]
Try to undo them it's likely they are the culprit. Our chat no longer has that blue color for instance.
