### ISSUE TITLE
make: git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by franciscopaniskaseker** [jitsi/jitsi-meet#11344]
### Description:

When  I try to execute make I get:

```bash
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/jitsi/eslint-config-jitsi.git
npm ERR!
npm ERR! Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```
### Steps to reproduce:

1. cd /usr/local/src/
2. git clone https://github.com/jitsi/jitsi-meet.git
3. git clone https://github.com/jitsi/lib-jitsi-meet.git
4. cd /usr/local/src/jitsi-meet/
5. npm update
6. npm install
7. rm -R node_modules/lib-jitsi-meet
8. ln -s /usr/local/src/lib-jitsi-meet /usr/local/src/jitsi-meet/node_modules/lib-jitsi-meet
9. cd /usr/local/src/lib-jitsi-meet
10. npm update
11. npm run build
12. cd /usr/local/src/jitsi-meet/
13. make

### Expected behavior:

Finish the make command with exit code 0.

### Actual behavior:
Exit code 128

### Server information:

- Jitsi Meet version: last version from git
- Operating System: ubuntu 20.04

### Client information:

- Browser / app version: -
- Operating System: -

### Additional information:

The problem is the same of https://github.com/jitsi/jitsi-meet/issues/10856
It is trying to user git instead of https protocol.

**Comment by damencho** [comment]
Is this master of jitsi-meet?

**Comment by saghul** [comment]
Don't run `npm update` you are going to break stuff. I don't see any ssh links in any package-lock file, I judiciously removed them some time ago.

What npm version are you using though, even if there are any ssh links, npm > 8.5.1 should ignore those.

**Comment by nirajsharma2022** [comment]
Contact me for jitsi meet installation 
https:/wa.me/+919782533298
skype : ersonusaini

**Comment by sagarsabhadiya** [comment]
`22422 error Error while executing:
22422 error /usr/bin/git ls-remote -h -t ssh://git@github.com/jitsi/strophejs-plugin-stream-management.git
22422 error
22422 error git@github.com: Permission denied (publickey).
22422 error fatal: Could not read from remote repository.
22422 error
22422 error Please make sure you have the correct access rights
22422 error and the repository exists.
22422 error
22422 error exited with error code: 128
22423 verbose exit [ 1, true ]`

Getting the same error:
1. git clone [https://github.com/jitsi/jitsi-meet]
2. Navigate to the jitsi-meet folder path in terminal
3. run npm install

Then getting this error in logs.

**Comment by saghul** [comment]
What npm version are you using?

**Comment by sagarsabhadiya** [comment]
**npm: '6.14.18',**

**Comment by saghul** [comment]
We don't support npm < 8, please check the documentation: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-jitsi-meet
