### ISSUE TITLE
https://meet.jit.si/ 

### ISSUE THREAD

**Issue by GrosSacASac** [jitsi/jitsi-meet#11369]
### Description:

400 Bad Request
Request Header Or Cookie Too Large
nginx/1.20.2

### Steps to reproduce:

With Firefox 100.0b
1. Open https://meet.jit.si/
2. Nginx error page

### Expected behavior:

It works

**Comment by saghul** [comment]
Can you check the stores cookies for the domain?

**Comment by GrosSacASac** [comment]
I manually cleared the cookies and page loads again
