### ISSUE TITLE
Black screen while using screen share

### ISSUE THREAD

**Issue by sunilitechnotion** [jitsi/jitsi-meet#11363]
I'm using below SDK in Android
implementation ('org.jitsi.react:jitsi-meet-sdk:4.1.0') { transitive = true }

We have hosted Jitsi on our own server. When i try to share the screen from Android 11 it shows black screen to participants. But if i use in Android 8 screen share is working fine. 
I tried the same thing with Jitsi App from Play store in Android 11 and screen share is working fine in that App.

**Comment by nirajsharma2022** [comment]
Contact me for jitsi meet installation 
https:/wa.me/+919782533298
skype : ersonusaini

**Comment by saghul** [comment]
Please update to SDK v5. Also, does your app implement a foreground service with the MEDIA_PROJECTION flag?

**Comment by sunilitechnotion** [comment]
No didn't implement a foreground service with MEDIA_PROJECTION. Can you help me with the snippet how to achieve it?

**Comment by saghul** [comment]
Hum, you shouldn't need to do anything actually, our manifest has it covered: https://github.com/jitsi/jitsi-meet/blob/ed6759c6cfd3da7a17642e7c860e5cadb81c80aa/android/sdk/src/main/AndroidManifest.xml#L48

Can you try updating to SDK 5?

**Comment by sunilitechnotion** [comment]
Have upgraded jitsi to SDK 5

implementation ('org.jitsi.react:jitsi-meet-sdk:5.0.2') { transitive = true }

But i'm using below code and in this one screen sharing is not working

```
public class MainActivity extends FragmentActivity implements JitsiMeetActivityInterface {
    private JitsiMeetView view;

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data) {
        JitsiMeetActivityDelegate.onActivityResult(
                this, requestCode, resultCode, data);
    }

    @Override
    public void onBackPressed() {
        JitsiMeetActivityDelegate.onBackPressed();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        view = new JitsiMeetView(this);
        JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
            .setRoom("https://meet.jit.si/test123")
            .build();
        view.join(options);

        setContentView(view);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        view.dispose();
        view = null;

        JitsiMeetActivityDelegate.onHostDestroy(this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

    @Override
    public void onRequestPermissionsResult(
            final int requestCode,
            final String[] permissions,
            final int[] grantResults) {
        JitsiMeetActivityDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onResume() {
        super.onResume();

        JitsiMeetActivityDelegate.onHostResume(this);
    }

    @Override
    protected void onStop() {
        super.onStop();

        JitsiMeetActivityDelegate.onHostPause(this);
    }
}
```

**Comment by saghul** [comment]
Why are you not using JitsiMeetActivity? It's already wired with the delegate and everything, including the foreground service, which you are missing: https://github.com/jitsi/jitsi-meet/blob/95baf34ba6706fd5103b2b804f09bfa0432f0866/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java#L216

**Comment by sunilitechnotion** [comment]
I need to add overlay view in the Jitsi meeting screen
