### ISSUE TITLE
api change displayName error

### ISSUE THREAD

**Issue by gerfigna** [jitsi/jitsi-meet#1136]
I get an js error
[JitsiMeetJS.js] <B.getGlobalOnErrorHandler>:  UnhandledError: TypeError: e.trim is not a function "Script: https://jitsimeet.xxxxx.com/libs/app.bundle.min.js?v=140" Line: 35 Column: 90 StackTrace:  TypeError: e.trim is not a function

when try to:
api.executeCommand('displayName', ['New Nickname']);

**Comment by damencho** [comment]
Api doc updated in https://github.com/jitsi/jitsi-meet/commit/c6296821c00e1b9e2dfebbfa9c5e4b6568065be6. Thanks.
