### ISSUE TITLE
Audio/video streams broken after conference.max_users encountered

### ISSUE THREAD

**Issue by shawnchin** [jitsi/jitsi-meet#11382]
### Description:

When mod_muc_max_occupants is used and conference.max_users error is triggered, the app ends up in a bad state where audio/video gets muted, and media streams do not get established upon successful rejoin (without reloading app).

More details and error logs posted on community forum: https://community.jitsi.org/t/audio-video-streams-broken-after-conference-max-users-encountered/113600

### Steps to reproduce:

Pre-requisite: mod_muc_max_occupants enabled

1. Populate room up to max occupants
2. Join as another user. Expect to see max_user error.
    * Note that audio/video automatically muted
4. Have one user leave the room
5. Click the join button again from session in step (2)
6. Join successful and user shows up in room, but user cannot see anyone's video
7. User not able to unmute video

### Expected behavior:

Rejoin should behave just a join, with everything working as expected.

### Actual behavior:

Cannot see other users' video, cannot send video stream (probably audio too?)

### Server information:

- Jitsi Meet version: 2.0.7001
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: Brave [Version 1.37.111 Chromium: 100.0.4896.79]
- Operating System:

**Comment by shawnchin** [comment]
This has been addressed in https://github.com/jitsi/lib-jitsi-meet/pull/1986 and https://github.com/jitsi/jitsi-meet/pull/11388.

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/bbfe7b4f3206e67d2e4bb65134e27ac7123659d0 and https://github.com/jitsi/lib-jitsi-meet/commit/da6d04c2a35abb0162db394ec6e3a7eb85dc5961
