### ISSUE TITLE
changing roles when sharing screen must done with permission!

### ISSUE THREAD

**Issue by elarabyelaidy19** [jitsi/jitsi-meet#11380]
when I was sharing my screen in the meeting I finished sharing the screen and gives access to another participant, but when he finished I found my screen shared with others without any further updates. 
You must lock sharing to the previous one sharing screen unless he accepts the role again. 
I have not found a solution for that except you stop sharing on your part when you give access to another person, which is not good and frustrating.

**Comment by saghul** [comment]
Many participants can share their screen simultaneously.

It is impossible for us to start screen sharing without permission, the browser enforces this.

Any chance you didn't actually stop screen sharing? That would explain what you observed.

**Comment by elarabyelaidy19** [comment]
yes. I didn't stop screen sharing giving access to other participants to share after he finish I found my screen exposed to everyone in the meeting without any prior notice. 
what I am talking about here is you should lock screen sharing to previous shared unless they want to share their screen again.

**Comment by damencho** [comment]
As @saghul already said, many participants can share their screen simultaneously. There is no restriction for how many screen sharings can be in the meeting. 
And when you are sharing your screen there is already a notification above all windows that warns you about it:
Chrome <img width="451" alt="image" src="https://user-images.githubusercontent.com/3263098/163306209-c1734552-9372-4531-a628-a3df35f110b3.png">
Fiirefox <img width="462" alt="image" src="https://user-images.githubusercontent.com/3263098/163306342-ac207cac-5547-4f5e-9f93-04838418e37e.png">
