### ISSUE TITLE
config.js is not defined

### ISSUE THREAD

**Issue by bharath-naik** [jitsi/jitsi-meet#11387]
I tried to setup jibri on my existing jitsi server after following proper documentation, I came accross an issue where my browser console says config. js is not defined and there is a grey sacreen on ui. tried few solutions on GitHub and community forum but it didn't help. can some let me know where this config.js file can be found and include in index.html.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

the file is in /etc/jitsi/meet/....-config.js
The file is server-side included in index.html here:
https://github.com/jitsi/jitsi-meet/blob/4a375aa2a493d1e02693f971b3f7e8047bfef57e/index.html#L184
A common problem is if you forget a `,` and make the config file invalid, you can see the error in the js console in the browser.
