### ISSUE TITLE
Firefox - Audio is not working for a second track

### ISSUE THREAD

**Issue by maxired** [jitsi/jitsi-meet#11385]
### Description:

When using the unified plan, a firefox user can't hear a second audio track from a remote participant.
Just to be clear, I am not talking about the new multiple simultaneous track feature, but more like, add a track, remove it, add a new track.

### Steps to reproduce:

1. Using chrome, open a new conference with your microphone being muted
2. Join the conference with a firefox browser
3. On the Chrome instance, start sharing your screen - choose to share a tab, with Audio sharing
4. Notice that the firefox user can hear the audio from chrome
5. Stop the screen share
6. On the chrome instance, unmute yourself

### Expected behavior:

The firefox user should be able to hear the chrome user

### Actual behavior:

The firefox user does not hear the chrome user

### Server information:

- Jitsi Meet version: I could reproduce on the currently deployed https://meet.jit.si 

### Client information:

- Browser / app version: Chrome 100 / Firefox 99
- Operating System: tested on mac os, but users also reported it on window

### Additional information:

I believe this might be related to https://github.com/jitsi/jitsi-meet/issues/11240
To be honest, I am not sure if this is a Jitsi or a firefox bug.
One thing that I noticed is that on firefox, the peerconnection `track` event seems to return the same reference as before.

**Comment by damencho** [comment]
Have you tried using replaceTrack?

**Comment by maxired** [comment]
@damencho here the logs I could get on the frontend using `JitsiMeetJS.setLogLevel(9999)` 

> 2022-04-14T17:16:34.957Z [modules/RTC/RTCUtils.js] <$i.<anonymous>>:  Got media constraints:  {"video":false,"audio":{"autoGainControl":true,"deviceId":"","echoCancellation":true,"noiseSuppression":true}} lib-jitsi-meet.min.js?v=5959.2677:formatted:354
2022-04-14T17:16:34.997Z [modules/RTC/RTCUtils.js] onUserMediaSuccess lib-jitsi-meet.min.js?v=5959.2677:formatted:354
2022-04-14T17:16:34.998Z [JitsiConference.js] <Vd._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession lib-jitsi-meet.min.js?v=5959.2677:formatted:354
2022-04-14T17:16:35.020Z [modules/xmpp/JingleSessionPC.js] <zr.notifyMySSRCUpdate>:  JingleSessionPC[session=JVB,initiator=false,sid=5v9ab596bn1pa] Sending source-add for audio ssrcs=3260888442 lib jitsi-meet.min.js?v=5959.2677:formatted:354
2022-04-14T17:16:35.020Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=5v9ab596bn1pa]  Replace track done! app.bundle.min.js?v=5959.2677:138
2022-04-14T17:16:35.022Z [features/base/tracks] Replace audio track - unmuted lib-jitsi-meet.min.js?v=5959.2677:formatted:354
2022-04-14T17:16:35.028Z [modules/RTC/RTCUtils.js] <$i.<anonymous>>:  Got media constraints:  {"video":false,"audio":{"autoGainControl":true,"deviceId":"default","echoCancellation":true,"noiseSuppression":true}} lib-jitsi-meet.min.js?v=5959.2677:formatted:354
2022-04-14T17:16:35.036Z [modules/RTC/BridgeChannel.js] <To.sendNewReceiverVideoConstraintsMessage>:  Sending ReceiverVideoConstraints with {"constraints":{"30aa2425":{"maxHeight":2160}},"defaultConstraints":{"maxHeight":0},"lastN":25,"onStageEndpoints":["30aa2425"],"selectedEndpoints":[]} lib-jitsi-meet.min.js?v=5959.2677:formatted:354 2022-04-14T17:16:35.067Z [modules/RTC/RTCUtils.js] onUserMediaSuccess

From what I understand, it looks like replace trace is called

**Comment by damencho** [comment]
Yeah, sorry. I'm not a big help here. But if @jallamsetty1 can step in when she is around :)

**Comment by nils-ohlmeier** [comment]
Firefox and Jitsi have a complicated interaction, because Jitsi uses MID identifiers in it's SDP, but doesn't support the MID header yet. Instead Jitsi relies on SSRCs for all tracks. This can lead to situations where Firefox gets confused if it receives audio packets from a new audio stream, before the signaling tells it about the new SSRC. Recently there were some attempts to improve this specific handling of new audio streams without MID RTP identifiers in these bugs on the Firefox side here https://bugzilla.mozilla.org/show_bug.cgi?id=1754027 and here https://bugzilla.mozilla.org/show_bug.cgi?id=1756222.

Could you test with Firefox 100 which is currently in Beta and see if that fixes the issue for you?

**Comment by jallamsetty1** [comment]
@nils-ohlmeier, do you think [this](https://community.jitsi.org/t/screen-share-black-screen-on-firefox-meet-jit-si/113631) could be related as well ? When I check the source signaling and SDPs on Firefox, I don't see anything suspicious. When the Chrome user stops sharing screen, a source-remove is sent and the next time they start sharing their screen again, the ep sends a source-add. On the Firefox side, the m-line associated with the first set of SSRCs is set to inactive and a new m-line is added as a result of the second source-add message. The JVB forwards the media stream but the browser doesn't render the media in this case.

remote SDP on Firefox

```
"v=0
o=- 1650288917045 5 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=group:BUNDLE 0 1 2 3
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=candidate:2 1 udp 1694498815 150.136.220.0 10000 typ srflx raddr 0.0.0.0 rport 9 generation 0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fingerprint:sha-256 6D:2A:FF:96:22:1C:BE:D7:81:1C:7D:77:2F:F0:C5:3C:22:D1:1F:5D:ED:B7:13:3E:16:13:26:48:79:77:4D:B9
a=ice-pwd:30nmqk7cks7v16d0d9l2sjn0qm
a=ice-ufrag:buopm1g0ue4ugq
a=mid:0
a=msid:mixedmslabel mixedlabelaudio0
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000/1
a=rtpmap:104 ISAC/32000/1
a=rtpmap:126 telephone-event/8000
a=setup:actpass
a=ssrc:1149701235 msid:mixedmslabel mixedlabelaudio0
m=video 9 UDP/TLS/RTP/SAVPF 100 101 96 97
c=IN IP4 0.0.0.0
a=candidate:2 1 udp 1694498815 150.136.220.0 10000 typ srflx raddr 0.0.0.0 rport 9 generation 0
a=sendrecv
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fingerprint:sha-256 6D:2A:FF:96:22:1C:BE:D7:81:1C:7D:77:2F:F0:C5:3C:22:D1:1F:5D:ED:B7:13:3E:16:13:26:48:79:77:4D:B9
a=fmtp:96 apt=100
a=fmtp:97 apt=101
a=ice-pwd:30nmqk7cks7v16d0d9l2sjn0qm
a=ice-ufrag:buopm1g0ue4ugq
a=mid:1
a=msid:mixedmslabel mixedlabelvideo0
a=rid:1 recv
a=rid:2 recv
a=rid:3 recv
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:97 rtx/90000
a=setup:actpass
a=simulcast:recv 1;2;3
a=ssrc:4282573566 msid:mixedmslabel mixedlabelvideo0
m=video 9 UDP/TLS/RTP/SAVPF 100 101 96 97
c=IN IP4 0.0.0.0
a=candidate:2 1 udp 1694498815 150.136.220.0 10000 typ srflx raddr 0.0.0.0 rport 9 generation 0
a=inactive
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fingerprint:sha-256 6D:2A:FF:96:22:1C:BE:D7:81:1C:7D:77:2F:F0:C5:3C:22:D1:1F:5D:ED:B7:13:3E:16:13:26:48:79:77:4D:B9
a=fmtp:96 apt=100
a=fmtp:97 apt=101
a=ice-pwd:30nmqk7cks7v16d0d9l2sjn0qm
a=ice-ufrag:buopm1g0ue4ugq
a=mid:2
a=msid:fc29ba77-video-1 c3a2f18f-4ea1-4d3a-8986-5046e7da86fb-1
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:97 rtx/90000
a=setup:actpass
m=video 9 UDP/TLS/RTP/SAVPF 100 101 96 97
c=IN IP4 0.0.0.0
a=candidate:2 1 udp 1694498815 150.136.220.0 10000 typ srflx raddr 0.0.0.0 rport 9 generation 0
a=sendonly
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fingerprint:sha-256 6D:2A:FF:96:22:1C:BE:D7:81:1C:7D:77:2F:F0:C5:3C:22:D1:1F:5D:ED:B7:13:3E:16:13:26:48:79:77:4D:B9
a=fmtp:96 apt=100
a=fmtp:97 apt=101
a=ice-pwd:30nmqk7cks7v16d0d9l2sjn0qm
a=ice-ufrag:buopm1g0ue4ugq
a=mid:3
a=msid:fc29ba77-video-1 c3a2f18f-4ea1-4d3a-8986-5046e7da86fb-1
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:97 rtx/90000
a=setup:actpass
a=ssrc:253646294 msid:fc29ba77-video-1 c3a2f18f-4ea1-4d3a-8986-5046e7da86fb-1
a=ssrc:811012838 msid:fc29ba77-video-1 c3a2f18f-4ea1-4d3a-8986-5046e7da86fb-1
a=ssrc-group:FID 253646294 811012838
"
```

**Comment by nils-ohlmeier** [comment]
@jallamsetty1 yes I think the problem I tried to fix in the Firefox bug reports mentioned above I think essentially any source add operation from the Jitsi side can lead to a problem with not rendering a stream. The reason being that media could potentially arrive at the Firefox browser before the signaling and thus confuse Firefox.

Can you still repro with Firefox >= 100?

**Comment by maxired** [comment]
@nils-ohlmeier @jallamsetty1 I can confirm this bug still exists with firefox 100.0b7 (on https://meet.jit.si)

**Comment by nils-ohlmeier** [comment]
@maxired ugh. Thank you for checking. Then I'll have a closer look if I can find what else is going on, or if the fix in the above mentioned bug reports for some reason doesn't work for this scenario.

**Comment by maxired** [comment]
@nils-ohlmeier do you have any update to provide on this bug?
For now, I am using plan B instead of unified plan, but this will not work anymore with Chrome 102

**Comment by nils-ohlmeier** [comment]
@maxired I started looking into this. And I have some theories to follow up onto, but no solution yet. I'll keep you posted.

**Comment by maxired** [comment]
@nils-ohlmeier that is great news. Feel free to ping me when you need some testing.

**Comment by maxired** [comment]
This seems to be fixed with firefox 101, on the currently https://meet.jit.si/ deployed version.

**Comment by saghul** [comment]
Thanks  for confirming!
