### ISSUE TITLE
Participant context menu opening above name sometimes renders top options inaccessible

### ISSUE THREAD

**Issue by nbeckindy** [jitsi/jitsi-meet#11392]
### Description:

When the participant context menu opens above the participants' name, depending on the position of the participant and the number of options, the context menu won't scroll up to access the all the options. 

### Steps to reproduce:

1. Open a meeting in meet.jit.si.
2. Join with several participants.
3. Decrease the browser height so that the context menu will open above a participant's name.
4. Have the selected participant unmute and start video so the max amount of options are available. Maybe open some breakout rooms too.

### Expected behavior:

The context menu should be able to be scrolled all the way to the top.

### Actual behavior:

In the screenshot below from meet.jit.si, the Mute Everyone Else and Mute options for the selected participant at the top of the context menu can't be accessed. (Also Stop Video is slightly cut off.) Scrolling down still works however. 

<img width="305" alt="Screen Shot 2022-04-17 at 4 26 54 PM" src="https://user-images.githubusercontent.com/9885067/163731419-98d010af-395b-47f9-975f-f82bbef7bdf7.png">

### Server information:

- Jitsi Meet version: meet.jit.si as of 4/17

### Client information:

- Browser / app version: Chrome 100
- Operating System: macOS

**Comment by saghul** [comment]
@robertpin PTAL when you can.

**Comment by robertpin** [comment]
Will do

**Comment by saghul** [comment]
@mihhu can you pl check if this is is still an issue?

**Comment by mihhu** [comment]
> @mihhu can you pl check if this is is still an issue?

Seems fixed!

**Comment by saghul** [comment]
Thank you!
