### ISSUE TITLE
webview layout breaks in chrome only

### ISSUE THREAD

**Issue by beavermml** [jitsi/jitsi-meet#11400]
### Description:

webview breaks when user open the link as shown above. only happen in Chrome Mobile version 100.0.4896.127

### Steps to reproduce:

1. user open link to jitsi hosted ( 8x8.com )
2. user click name textfield to change name,
3. layout breaks when onscreen keyboard appear

### Expected behavior:

layout should stay and not changes at all

### Actual behavior:

![image](https://user-images.githubusercontent.com/3795219/163938497-fe974ee2-07f6-4eb8-93d8-17b5d5f9ee30.png)

screenshot taken from actual device ( connected via usb debugging and screen casted to Chrome Inspect Device )

doesnt happen in Firefox

**Comment by beavermml** [comment]
![image](https://user-images.githubusercontent.com/3795219/163939969-6032b307-618d-41a2-9cfd-d3ef7d90cbd0.png)

if i remove the JWT, the layout is correct

**Comment by saghul** [comment]
I don't think the JWT is the culprit. The problem is likely the UA since it's not a mobile browser.

**Comment by beavermml** [comment]
> I don't think the JWT is the culprit. The problem is likely the UA since it's not a mobile browser.

what is UA? but when i delete the JWT token in the query text... the layout is proper ( but i need to clear cache/cookie/data/etc in Chrome first )

this doesnt happen if the user use Firefox in android.. only reproducable in Chrome ( atleast what i have test )

**Comment by beavermml** [comment]
> UA is User Agent. FIrefox on Android will identify as a mobile browser, but your screenshot looks like the device simulator in Chrome, was that the case?

those screenshot is from chrome debug.. i connect my phone and enable usb debugging and try to use chrome inspect device to see if there is any meaningful error

**Comment by saghul** [comment]
Hum, that's so odd. Can you paste the user agent string you get from `navigator.userAgent` on the console?

**Comment by beavermml** [comment]
'Mozilla/5.0 (Linux; Android 11; RMX3081) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36'
