### ISSUE TITLE
jitsi-meet debian repo 2.0.7210 relies on nginx and removes apache2

### ISSUE THREAD

**Issue by martinschniewind** [jitsi/jitsi-meet#11411]
When jitsi-meet is installed from debian repo "deb https://download.jitsi.org stable/", upgrading to 2.0.7210-1 (from 2.0.7001-1)  will **remove apache2**:

```
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  jicofo jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web
  jitsi-meet-web-config jitsi-videobridge2 libnginx-mod-http-image-filter
  libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream nginx
  nginx-common nginx-core openjdk-11-jre-headless
Suggested packages:
  fcgiwrap nginx-doc libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic
  fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic
The following packages will be REMOVED:
  apache2 python3-certbot-apache
The following NEW packages will be installed:
  jitsi-meet-turnserver libnginx-mod-http-image-filter
  libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream nginx
  nginx-common nginx-core openjdk-11-jre-headless
The following packages will be upgraded:
  jicofo jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config
  jitsi-videobridge2
```
Of course, on a system based on apache http service, this behaviour is undesired.

**Comment by saghul** [comment]
IIRC this is a side effect of the web package no longer depending on Apache but on nginx alone.

**Comment by gpatel-fr** [comment]
I have a test instance with Jitsi stable 7001 and Nginx on Ubuntu 20.04, tried to install apache2 on it, no problem, it does not start (of course, the port is already taken), then tried to upgrade: it does NOT try to uninstall apache2. IMO your report could give more detail.  We don't even know the OS.
Also, I don't see change in dependencies in apt-cache show jitsi-web-config or jitsi-web from previous stable to current.

**Comment by scsaht** [comment]
I upgraded jitsi-meet as usual.
(Because the upgrade was held up, I did "apt install jitsi-meet" without thinking too much, it's my mistake) 
As a result, apache was deleted and I was in big trouble.

**Comment by mario-spitze** [comment]
I was wondering about the nginx dependency, too. I am attaching some information to you.
In my configuration it works well with apache2. But it doesn't want to uninstall apache2.

> apt upgrad:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-image-4.19.0-18-amd64 linux-image-5.10.0-11-amd64
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  coturn geoip-database libevent-core-2.1-7 libevent-extra-2.1-7 libevent-openssl-2.1-7 libevent-pthreads-2.1-7 libgeoip1 libhiredis0.14 libmariadb3 libnginx-mod-http-geoip
  libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream libnginx-mod-stream-geoip mariadb-common mysql-common nginx nginx-common nginx-core sqlite3 telnet
The following packages have been kept back:
  jicofo jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jitsi-videobridge2
The following packages will be upgraded:
  gzip jigasi liblzma5 xz-utils
4 upgraded, 22 newly installed, 0 to remove and 6 not upgraded.
Need to get 75.1 MB of archives.
After this operation, 19.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

> dpkg --list "ji*"
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version             Architecture Description
+++-=====================-===================-============-=================================================
ii  jicofo                1.0-862-1           all          JItsi Meet COnference FOcus
ii  jigasi                1.1-227-gb97e1fa-1  amd64        Jitsi Gateway for SIP
ii  jitsi-meet            2.0.7001-1          all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody    1.0.5913-1          all          Prosody configuration for Jitsi Meet
un  jitsi-meet-tokens     <none>              <none>       (no description available)
un  jitsi-meet-turnserver <none>              <none>       (no description available)
ii  jitsi-meet-web        1.0.5913-1          all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config 1.0.5913-1          all          Configuration for web serving of Jitsi Meet
un  jitsi-videobridge     <none>              <none>       (no description available)
ii  jitsi-videobridge2    2.1-634-gff8609ad-1 all          WebRTC compatible Selective Forwarding Unit (SFU)
```

>apt update
```
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://httpredir.debian.org/debian bullseye InRelease                
Hit:3 https://download.jitsi.org stable/ InRelease
```

**Comment by saghul** [comment]
Ah, I think I know. It's this line: https://github.com/jitsi/jitsi-meet/blob/97b958e9eab23d2898c74cbc51e89430725d379b/debian/control#L55 the `jitsi-meet-turnserver` package breaks apache, and it's a recommended dependency.

Now, that was 2 years ago, not sure why we are hearing about this now.

IIRC the intent here was not to end up in a situation where a user thinks TURN will be working, but it won't because we only provide Ngninx configs.

So I think we have 2 outs:

- Leave it as is, and users who are using Apache can ignore recommended packages, and configure their TURN servers by hand.
- Remove the "Breaks" line so we don't accidentally break Apachae installations, but a working setup would require manual user intervention, which is not ideal.

I don't like any of them TBH.

Thoughts @damencho ?

**Comment by damencho** [comment]
But this is there because of sharing a port between nginx and coturn. We no longer do that by default, and for that you need a second dns and manual steps from the handbook, so we should drop it.

**Comment by ychromosome** [comment]
I have a similar, but less severe issue on Ubuntu 20.04.
After the latest update, apt-install pulled nginx as well, but did not remove (huh ...) apache2.

That should be the culprit:
apt-cache depends jitsi-meet-web-config 
jitsi-meet-web-config
  Hängt ab von: openssl
    openssl:i386
 |Hängt ab von: nginx
    nginx-core
    nginx-extras
    nginx-full
    nginx-light
 |Hängt ab von: nginx-full
 |Hängt ab von: nginx-extras
  Hängt ab von: apache2

**Comment by martinschniewind** [comment]
As I realised two weeks ago, the dependencies have been changed. Upgrading jitsi-meet from the deb-repository no longer breaks apache2 nor removes it.
Can anyone confirm this? If so, I would tend to close the issue...

**Comment by saghul** [comment]
We made adjustments to fix that issue indeed.

**Comment by martinschniewind** [comment]
Thanks @gpatel-fr for your input - so sorry, I misconfigured my notification settings on GitHub, so I missed your question.
OS is Ubuntu 20.04, apt repository is deb https://download.jitsi.org stable/
