### ISSUE TITLE
version 7210 - feat GIPHY integration leads to loading woff2 font files from third party (aws) - CSP is required to block the requests

### ISSUE THREAD

**Issue by amsnek** [jitsi/jitsi-meet#11419]
### Description:

Since version 7210 the resuling build attempts to load woff2 fonts from amazonaws. It is blocked by CSP settings, but this shouldnt happen. 
It is from the '@giphy/js-brand' NPM module -> commit 190041fc5a : feat(gif) Added GIF support (GIPHY integration)(#11021)

https://s3.amazonaws.com/giphyscripts/react-giphy-brand/fonts/InterFace_W_Rg.woff2
https://s3.amazonaws.com/giphyscripts/react-giphy-brand/fonts/InterFace_W_Rg.woff
...

### Steps to reproduce:

1. Open the meet site with the build in question, Loading welcome page suffices

### Expected behavior:

No attempts to load fonts or files from third party sites.

### Actual behavior:

attempts to load .woff/.woff2 fonts from aws

### Server information:

- Jitsi Meet version: 7210
- Operating System: Linux

### Client information:

- Browser / app version: Chrome Version 100.0.4896.127
- Operating System: Linux

**Comment by damencho** [comment]
@robertpin @mihhu Can you take a look? Can we have those resources locally on the deployment and configure giphy to use those?

**Comment by gpatel-fr** [comment]
Did you enable the feature in config.js ? because I did not enable it (option is off by default) and I see no such access.

**Comment by amsnek** [comment]
> Did you enable the feature in config.js ? because I did not enable it (option is off by default) and I see no such access.

No, it was not enabled, also tried  explicitly disabling it without effect. This is a self build though, not a debian package.

**Comment by mihhu** [comment]
I'll take a look this week.

**Comment by mihhu** [comment]
@amsnek could you please help us with some more steps or details? I can't seem to reproduce it.

**Comment by gpatel-fr** [comment]
I still don't see any font query, but in searching for another problem I noticed in the browser calls to a pingback.giphy.com, and I found in the @giphy/js-analytics/src/send-pingback.ts file this disturbing comment:

// TODO remove api key

well, the Api key that I see queried in the network tab is hard coded in this file. Is this normal, IDK.

**Comment by saghul** [comment]
Good catch, that's bad. We could potentially patch it with patch-package.

**Comment by saghul** [comment]
Fixed both here: https://github.com/jitsi/jitsi-meet/pull/11457
