### ISSUE TITLE
No PIP mode option during Screen Sharing

### ISSUE THREAD

**Issue by gensspl** [jitsi/jitsi-meet#11410]
### Description: 
I am using Jitsi Mobile SDK in one of my Android project. Where when I am using "Start screen sharing" option, automatically the PIP mode (down arrow) gets hidden/disabled. Resulting there is no way to navigate inside my app to share the content. 

Is there any way to keep the PIP mode enabled during screen sharing?

### Steps to reproduce:

1. Connect to a room
2. Click Start screen sharing
3. Try to switch to PIP mode

### Expected behavior:

App is switched to PIP mode

### Actual behavior:

No option for PIP mode, even clicking the back button on the device doesn't change the view to PIP mode.

### Server information:

https://meet.jit.si

### Client information:

JitsiSDKTest with SDK version 5.0.2

### Additional information:

![image](https://user-images.githubusercontent.com/104065662/164217296-be33a8c9-3348-4ba1-a0d4-1bd8134fee71.png)

**Comment by saghul** [comment]
This is intentional.

Otherwise people will see themselves on your PiP creating a confusing effect. Not to mention, the loss of screen real state when sharing.

**Comment by gensspl** [comment]
I understand, but my app requirement is to show the content of the page after sharing the screen. Do you think if there is any way to achieve this?

Thanks

**Comment by saghul** [comment]
Not without code changes.

**Comment by gensspl** [comment]
@saghul Can you please give me a little direction that where and what changes I need to do in order to achieve this?

Many thanks!

**Comment by saghul** [comment]
You can try to comment out the contents of this function so it does nothing: https://github.com/jitsi/jitsi-meet/blob/master/react/features/mobile/picture-in-picture/functions.js#L11
