### ISSUE TITLE
Having issue on connecting "meet.jit.si" on Mobile App(Android)

### ISSUE THREAD

**Issue by hiteshbpatel** [jitsi/jitsi-meet#11417]
Hi Team,

I have implemented **lib-jitsi-meet** library in my React-Native Mobile app and I am able to connect **beta.meet.jit.si** & it's working fine, but when I am trying to connect **meet.jit.si**, it's giving below **error:**

LOG  2022-04-22T10:01:28.644Z [modules/xmpp/xmpp.js] (TIME) Strophe connecting:         1650621688644
 INFO  2022-04-22T10:01:28.670Z [modules/RTC/RTCUtils.js] list of media devices has changed: [{"deviceId": "0", "facing": "environment", "groupId": "", "kind": "videoinput", "label": "0"}, {"deviceId": "1", "facing": "front", "groupId": "", "kind": "videoinput", "label": "1"}, {"deviceId": "audio-1", "groupId": "", "kind": "audioinput", "label": "Audio"}]
 LOG  2022-04-22T10:01:29.322Z [modules/xmpp/xmpp.js] (TIME) Strophe connfail[item-not-found]:   1650621689322
 LOG  2022-04-22T10:01:29.325Z [modules/xmpp/xmpp.js] (TIME) Strophe disconnected[item-not-found]:       1650621689325
 LOG  2022-04-22T10:01:29.327Z [modules/statistics/statistics.js] {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.otherError","error_message":"item-not-found","suspend_time":0,"time_since_last_success":null}}
 LOG  🔥----------------connection failed----------------🔥

Please check my Config Settings as below:
 ```
bosh: "https://meet.jit.si/http-bind",
 hosts: {
    domain: "meet.jit.si",
    muc: "conference.meet.jit.si",
    focusUserJid: 'focus@auth.meet.jit.si',
    role:"moderator",
    isFocus:true,
    isHiddenDomain:false,
    affiliation:"owner"
  },
  clientNode: "http://jitsi.org/jitsimeet",
 p2p: {
    enabled: false,
    useStunTurn: true,
    stunServers: [{ urls: "stun:meet-jit-si-turnrelay.jitsi.net:443" }],
  },
```

Any help will be appreciated.

**Comment by Freddie-m** [comment]
Seeing as this is a support request, you should probably post it in the [community](https://community.jitsi.org/). Posts here on github are mainly for bugs and features.

**Comment by damencho** [comment]
https://community.jitsi.org/t/having-issue-on-connecting-meet-jit-si-on-mobile-app-react-native/113848/3?u=damencho
