### ISSUE TITLE
participants are never prompted for password, if they require access to a conference with lobby mode on

### ISSUE THREAD

**Issue by chipechop** [jitsi/jitsi-meet#11418]
### Description:

participants are never prompted for password, if they require access to a conference with lobby mode on

### Steps to reproduce:

1. create conference in meet.jit.si/EXAMPLE and set BOTH the lobby mode on and a conference password
2. connect to the conference with your smartphone and require access WITHOUT inputing any password

you'll see that your access request will be forwarded to the moderator, without any prompt to input the (so called) required password for the conference.

The moderator will see your request in the lobby and will be able to admit you to the conference, without knowing that you never typed the (so called) required password

### Expected behavior:

that before processing the request to the lobby, the user would be prompted for password

### Actual behavior:

the access request to the lobby is processed before the password check

### Server information:

- Jitsi Meet version: using both meet.jit.si and beta.meet.jit.si
- Operating System: 

### Client information:

- Browser / app version: moderator: chrome; participant: android jitsi meet app
- Operating System: Windows 11 (moderator) and Android 9 (participant)

### Additional information:

none

**Comment by damencho** [comment]
This is how it is supposed to work. When lobby is enabled the room is protected by having a manual step from a moderator (vs automatic one with pre announced password). In this case when password is used with lobby, when you enter the password on the perjoin/lobby screen you can bypass the lobby step. This is used for moderators who now the password to directly enter vs guests asking to Join.

Please, when you have questions or problems use the community forum before opening new issues, thank you.
