### ISSUE TITLE
Mobile app does not show remote video when remote user starts video after the conference is started

### ISSUE THREAD

**Issue by skumarcm** [jitsi/jitsi-meet#11421]
### Description:

Mobile app does not show the video of the remote user (from web) if the remote user starts the video after the conference call is started. This issue occurs only in an edge case when a conference with a specific id starts for the first time. 
The problem does not occur If the test is done for a second time without closing the app (without ending the app by swiping out the stack) using the same conference id. Also, the problem does not occur if the conference is started with the video on to begin with.

### Steps to reproduce:

1. User 1 starts a conference call with a NEW conference id on web. Video must be off when starting the call
2. User 2 joins the conference from Android app(iOS may have the same problem as well)
3. User 1 turns on the video
4. User 2 does not see User 1's video

### Expected behavior:

User 2 must see User 1's video on User 2's mobile app.

### Actual behavior:

User 1's video is not shown on User 2's mobile app.

### Server information:

Online jitsi server

### Client information:

meet.jit.si from google chrome (Version 100.0.4896.88 (Official Build) (64-bit))
jitsi meet app on Android 11

**Comment by saghul** [comment]
What app version did you try?

**Comment by skumarcm** [comment]
I downloaded the latest version from google play store today.

**Comment by skumarcm** [comment]
Just some additional findings:
The problem does not occur under the following conditions:
1. If the above test is done after ending the conference call on both sides and without closing the mobile app using the same conference id.
2. When there are three participants in the call. This may prove that the issue is related to p2p

**Comment by saghul** [comment]
This was on meet.jit.si, right?

**Comment by skumarcm** [comment]
Yes. It was on meet.jit.si.

**Comment by saghul** [comment]
I cannot reproduce this with the latest betas. Can you please test those? https://jitsi.github.io/handbook/docs/releases#beta-versions

**Comment by skumarcm** [comment]
Hey @saghul , It works fine with the betas you provided!!
I am actually using the JitsiMeetView in my app to integrate jitsi with my app.
I was wondering, what updates fixed this problem in the betas.

It would be great if you can provide any hint.

If not, I will build the sdk with the latest updates and test.
Thanks!!! and Keep up the great work on this product!!

**Comment by saghul** [comment]
Good to hear!

I recall it took several iterations to cover all cases, and the web was also involved... so not a single change I can point you to.

We are expecting to make a release in the next few weeks.
