### ISSUE TITLE
Black screen shows when pick up video calls in Android sdk

### ISSUE THREAD

**Issue by huaxiaxueyuan** [jitsi/jitsi-meet#11439]
I update jitsi-meet version from 2.4.0 to 5.0.2.
When I pick up a video call,  it shows only blackscreen in both side, 
and there is no error message shows in my logcat log .
Since the old version works well,Is there any changes in params configs ?
The activity code is below, the methods no exit in source code is created by other developers：
 @Override
    protected void onCreate(Bundle savedInstanceState) {

       mFrameLayout = (FrameLayout) findViewById(R.id.jitsi_view);
        boolean inited = false;
        mJitsiMeetView = JitsiCacheHelper.get(mCallType, answer, () -> {
            mFrameLayout.post(this::onJoined);
        });
        if (mJitsiMeetView == null) {
            mJitsiMeetView = new JitsiMeetView(this);
        } else {
            inited = true;
        }
        mFrameLayout.addView(mJitsiMeetView);
}

if (!inited) {
            // 配置房间参数
            JitsiMeetConferenceOptions.Builder options = new JitsiMeetConferenceOptions.Builder()
                    .setWelcomePageEnabled(false)
                    .setFeatureFlag("pip.enabled", false);
            if (CallConstants.isAudio(mCallType)) {
                options.setVideoMuted(true);
            } else if (CallConstants.isScreenMode(mCallType) && answer) {
                options.setVideoMuted(true);
            } else if (CallConstants.isLive(mCallType) && answer) {
                options.setAudioMuted(true);
                options.setVideoMuted(true);
                options.setSubject("{\"videoDisable\": \"true\",\"tileDisable\": \"true\"}");
            }

            try {
                options.setServerURL(new URL(mLocalHost));
            } catch (MalformedURLException e) {
                throw new IllegalStateException("jitsi地址异常: " + mLocalHost);
            }
            if (mCallType == CallConstants.Audio_Meet) {// 群组语音添加标识，防止和群组视频进入同一房间地址
                options.setRoom("audio" + getRoomId());
            } else {
                options.setRoom(getRoomId());
            }
            loadJwt(options);
            // 开始加载
            mJitsiMeetView.join(options.build());
        }
        JitsiMeetActivityDelegate.onHostResume(this);
}

 @Nullable
    public static JitsiMeetView get(int type, boolean answer, JoinedCallback joinedCallback) {
        if (sJitsiMeetView == null) {
            return null;
        }
        JitsiMeetView view = sJitsiMeetView;
        sJitsiMeetView = null;
        if (view.getParent() instanceof ViewGroup) {
            ((ViewGroup) view.getParent()).removeView(view);
        }
        if (sJoined) {
            joinedCallback.joined();
            sJoined = false;
        } else {
            sJoinedCallbackReference = new WeakReference<>(joinedCallback);
        }
        return view;
    }

@Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

**Comment by saghul** [comment]
A lot has changed since SDK 2.\

Please check the JitsiMeetActivity implementation, you might be missing some wiring since you are using the view directly, which we don't recommend.

**Comment by huaxiaxueyuan** [comment]
Hi, thanks for your reply
I did't publish my own project to maven, and I use the aar and jar Instead.
it includes libjingle_peerconnection.so.jar,libuvccamera-release.aar,
libwebrtc.jar ,react-native-0.67.4.aar and every module related to react-native except webrtc(conflict with libwebrtc.jar ) and org.webkit:android-jsc:+(cannot solve path).

The whole gradle file in jitsi module is below:
apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
    }
    dependencies {
        classpath 'gradle.plugin.io.pry.gradle.offline_dependencies:gradle-offline-dependencies-plugin:0.5.0'
    }
}

apply plugin: 'io.pry.gradle.offline_dependencies'
offlineDependencies {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://github.com/jitsi/jitsi-maven-repository/raw/master/releases' }
    }

    includeSources = false
    includeJavadocs = false
    includePoms = true
    includeIvyXmls = false
    includeBuildscriptDependencies = false
}

android {
    compileSdkVersion compile_version

    defaultConfig {
        minSdkVersion min_version
        targetSdkVersion target_version
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
            details.useVersion '0.67.4'
        }
    }
}
dependencies {
    // jitsi，
    api files('libs/jitsi-meet-5.0.2.aar')
    api fileTree(dir: 'libs', include: ['*.jar'])
    api fileTree(dir: 'libs', include: ['*.aar'])
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    //noinspection GradleDynamicVersion
    //implementation 'org.webkit:android-jsc:+'

    implementation 'com.facebook.fresco:animated-gif:2.5.0'
    implementation 'com.dropbox.core:dropbox-core-sdk:4.0.1'
    implementation 'com.jakewharton.timber:timber:4.7.1'
    implementation 'com.squareup.duktape:duktape-android:1.3.0'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation "androidx.startup:startup-runtime:1.1.0"


    implementation 'com.facebook.infer.annotation:infer-annotation:0.18.0'

    api 'com.facebook.fbjni:fbjni-java-only:0.2.2'
    api 'com.facebook.soloader:nativeloader:0.10.1'
    compileOnly("org.glassfish:javax.annotation:10.0-b28")
    compileOnly 'com.github.pengrad:jdk9-deps:1.0'
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'androidx.appcompat:appcompat:1.6.0-alpha01'
}

**Comment by saghul** [comment]
So you are using a different WebRTC build? Then I can't help you since I don't know what changes you made to it. I do know our SDK works just fine with the version we ship.

**Comment by huaxiaxueyuan** [comment]
All arr and jar files are taken form jitsi-meet-master project, libwebrtc.jar is from jitsi-meet-master/node_modules/react-native-webrtc/android/build/intermediates/aar_libs_directory/release/libs floder.

I replace libjingle_peerconnection.so.jar and libwebrtc.jar with react-native-webview-release.aar this morning, but it still shows black screen.

**Comment by saghul** [comment]
I really don't know what you are doing. All the SDK dependencies are published onto our maven repository. There are more than those.

I suspect something g might be missing at runtime because you are not using the SDK properly.

Please follow the instructions in the handbook and add our maven repo and the implements line, otherwise you are on your own.
