### ISSUE TITLE
Memory leak with screen share + camera

### ISSUE THREAD

**Issue by Bluewind** [jitsi/jitsi-meet#11442]
### Description:

I'm seeing an apparent memory leak when starting a screen share and also enabling the camera. Within roughly 1 minute the browser consumes upwards of 3GB of memory and within 2 minutes it exhausts my laptops memory and displays a "this tab is not responding" message. Even when disabling the camera before the failure, the memory usage does not go back down to usual levels, but stays somewhat elevated.

### Steps to reproduce:

1. start a screen share (only tested with entire screen, did not test single windows)
2. start the camera share in addition to the screen share
3. observe screen share with overlaid camera on the other participant (no issues there)
4. monitor memory usage on the sending participant's browser

### Server information:

- Jitsi Meet version: stable/jitsi-meet_7210
- Operating System: Ubuntu + official meet.jit.si instance

### Client information:

- Browser / app version: Chromium Version 100.0.4896.60 (Official Build) Arch Linux (64-bit)
- Operating System: Arch Linux

### Additional information:

I have reproduced this issue on the official meet.jit.si instance (today on 2022-04-27), but initially discovered it on a self-hosted instance with version stable/jitsi-meet_7210.

Version stable/jitsi-meet_6726 (also self-hosted) appears to be working fine and I am unable to reproduce the issue there. Memory usage does increase when starting the shares, but the browser maintains roughly 700-1000MB over multiple minutes.

**Comment by gpatel-fr** [comment]
Have you the new screensharing feature enabled ? If yes can you disable it by setting flags.sendMultipleVideoStreams to false in the URL? (that should switch back to the older Picture in Picture mode)

**Comment by pcvengros** [comment]
I can confirm this is happening with/without that flag. Browser tab will shortly after enabling camera during screenshare freeze and browser "eats" memory

**Comment by saghul** [comment]
I am not able to reproduce this on macOS using Chrome 101 beta.

**Comment by pcvengros** [comment]
my test setup: linux, chrome 100, p2p enabled, 2 participants

**Comment by saghul** [comment]
Ping @jallamsetty1 any chance you can take a look?

**Comment by jallamsetty1** [comment]
I am not able to reproduce the issue either with Chrome 100 on macOS. Is it happening only on Linux ?

**Comment by pcvengros** [comment]
I will test this next 2-3 days on Windows/Linux/Mac with Chrome/Firefox and report back

**Comment by saghul** [comment]
Thanks!

**Comment by Bluewind** [comment]
Has there been any more progress on this? @pcvengros were you able to reproduce it on other OSes as well?

**Comment by Bluewind** [comment]
With Chromium 101.0.4951.41 this has improved somewhat and it is more difficult to trigger the memory leak. It took about 10 tries before I saw it happen again. Each time, refresh the page, start a screen share, start the camera and wait for 20 seconds. I've also tried some variations, e.g. starting a camera stream before starting a screen share and turning the camera off and back on again while the screen share is active, but that does not appear to trigger it more often. With Chromium 100 I was able to consistently reproduce the leak each time.

FWIW I am using Chromium on Xorg + pulseaudio (though pipewire is installed, but not specifically configured) so I don't think that this is a wayland issue.

Any idea why it worked in the old version of Jitsi and why it might have broken in the newer one? That sounds more like a change on the Jitsi side either caused this, or you are now using unstable features in Chrome that were not used before.

**Comment by saghul** [comment]
Can you reproduce it with Google Meet?

**Comment by javierckr** [comment]
@saghul I can not reproduce it with Google Meet, but meet is sending video in 360p while jitsi in 720p, it requires less resources.

Could it be related to this: https://community.jitsi.org/t/ffmpeg-eats-all-the-memory-and-crash-within-a-minute-recording-or-streaming/34944/27.

**Comment by javierckr** [comment]
> Can you try to disable HW acceleration and see if that makes a difference?

With HW acceleration disabled it's not happening! Thanks!

**Comment by saghul** [comment]
We are still not 100% sure what's up. Initially I thought disabling HW acceleration had avoided the issue, but then it still happens so more investigation is necessary.

**Comment by saghul** [comment]
Update: we just fixed a leak in face centering. Did you have that enabled?

**Comment by javierckr** [comment]
Not in self-hosted server, but I test it also on public server meet.jit.si, it's happening on both
