### ISSUE TITLE
Issues with Dial in at https://meet.jit.si

### ISSUE THREAD

**Issue by Lastofthefirst** [jitsi/jitsi-meet#11448]
When dialing in to meetings we often find that the connection hangs after navigating the menu and never connects to the meeting. Other times there is a constant busy signal.

**Comment by saghul** [comment]
Please provide more details: what phone number did you use?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This has nothing to do with jitsi-meet project.

Can you send me personally (damencho at jitsi org) the approximate time, the number you used to dial in, and the number you dialed so I can check.

Thank you
