### ISSUE TITLE
Chrome - after using `share this tab instead`, tab still marked as shared

### ISSUE THREAD

**Issue by maxired** [jitsi/jitsi-meet#11458]
### Description:

On the current https://meet.jit.si/ deployed version,
using google chrome 101,  when I screenshare a tab, switch tab, and stop screensharing using Jitsi interface button,
Chrome still displays a message explaining that the tab is shared.

<img width="740" alt="Screenshot 2022-04-29 at 10 41 29" src="https://user-images.githubusercontent.com/1194083/165912161-f8ddb177-cc0f-4b35-b9ce-fd2a04dcc700.png">

This does not seems to be a chrome bug, since I canno't reproduce on https://meet.google.com/

### Steps to reproduce:

1. create and join new jitsi conference https://meet.jit.si/ using google chrome
2. start a screen share. When asked, shared a google chrome tab 
3. open a new google chrome tab. 
4. click on `Share this tab instead`
5. on the Jitsi tab, stop the screen share by clicking on the screen share icon of the bottom toolbar

### Expected behavior:

Chrome hides the banner screen share is in progress.

### Actual behavior:

Chrome still shows the banner screen share is in progress.

### Server information:

- Jitsi Meet version: https://meet.jit.si/
- Operating System: 

### Client information:

- Browser / app version: Google chrome 101
- Operating System: macos 11.3.1

**Comment by saghul** [comment]
Do you get any errors in the JS console?

**Comment by maxired** [comment]
@saghul , no there is absolutely no error.
Jitsi considers the track to be correctly stopped

> <i.then.videoSwitchInProgress>:  Screen sharing stopped.

**Comment by saghul** [comment]
Looks like a (fixed) Chrome bug. On `Version 102.0.5005.27 (Official Build) beta (x86_64)` it switches the tab correctly. Since the switch happens in Chrome without any part on the app there is nothing we can do here.

**Comment by maxired** [comment]
thanks. I do confirm this is fixed in chrome 102
