### ISSUE TITLE
 Issue: Jitsi Iframe API Toggle filmstripe when clicking the name only in Chrome

### ISSUE THREAD

**Issue by holema** [jitsi/jitsi-meet#11452]
### Description:

I integrate the JItsi Iframe Api into an project.
On a Desktop Browser everything works fine but on a mobile Chrome Browser when I click in the iframe on the input to change the name, I get the issue that the filmstripe is opened automaticcally. After some research I figured out, that when I trigger the api command toggleFilmstripe I can toggle the filmstripe back.

I discussed the issue already in the forum with @saghul :
https://community.jitsi.org/t/issue-jitsi-iframe-api-toggle-filmstripe-when-clicking-the-name-only-in-chrome/113930

### Steps to reproduce:
```

<!DOCTYPE html>
<html>
<head>
    <title>{{ room.name }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
</head>
<body style="margin: 0" >
    <div id="jitsiWindow" style="height:500px; overflow:hidden">

    </div>

</body>

    <script src='https://{{ room.server.url }}/external_api.js'></script>
    <script>
        const domain = '{{ room.server.url }}';
        const options = {
            roomName: '{{ room.uid }}',
           // width: '100%',
  configOverwrite: {
        disableDeepLinking: true,

    },
    interfaceConfigOverwrite: {
       MOBILE_APP_PROMO: false,
    },
            height: 700,
            parentNode: document.querySelector('#jitsiWindow'),
            userInfo: {
                displayName: '{{ name }}'
            }
        };
        api = new JitsiMeetExternalAPI(domain, options);
```

__Open the page in a mobile Browser. not in the Mobile Emulator__  

- [ ] Chrome mobile Browser

- [x] In the Emulator everything works fine.

- [x] In the mobile firefox everything works fine

- [x] in the mobile opera everything works fine

My user agent:

'Mozilla/5.0 (Linux; Android 11; moto g(9) plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36'

### Expected behavior:

Not showing the filmstripe

### Actual behavior:

![jitsi_iframe_issue](https://user-images.githubusercontent.com/22790152/165788567-0a3573a6-0715-407b-a9fa-3644dd123ed1.gif)

### Server information:

The standard meet.jit.si instance and every other instance I try

### Client information:

'Mozilla/5.0 (Linux; Android 11; moto g(9) plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36'

**Comment by saghul** [comment]
@horymury can you PTAL when you can?

**Comment by holema** [comment]
Hey @saghul and @horymury 
I created a test conference for the issue. There the Issue happens on the mobile browser.
If the link is not working anymore, I will restart the service
https://try.dev.jitsi-admin.de/myRoom/start/Test__for_jitsiiframe-516
