### ISSUE TITLE
Jitsi-meet Conference Focus, focus not available

### ISSUE THREAD

**Issue by lorsulic** [jitsi/jitsi-meet#1145]
my last setup had the versions:

CentOS Linux release 7.2.1511 (Core)
Prosody Version 0.9.10 from the epel repo
Videobridge Version 829
Jicofo Version 299
Jitsi-Meet Version 1390

it was working, there were only one issue described here: #1053 
But no errors in the console or logs. I'm using ldap for authentication.

Now I'm on the following versions:

CentOS Linux release 7.2.1511 (Core)
Prosody Version 0.9.10 from the epel repo
jitsi-meet: 1504
jitsi-videobridge: 844
jitsi-jicofo: 309

I also tried some of the previous versions, between the running and the latest, but I'm getting the samer Error:

`Conference Focus, focus not available , retry in x sec`
Also the chat is not working, when I send a message I get: 
`Error: Your message was not sent.` in the chat window and in the console:
`CONFERENCE Error: conference.chatError Array [ "", "" ]`
`Not well formed`

The server logs are not showing any errors, only the console inside chrome:
`[JitsiMeetJS.js] <B.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 64000`
`[modules/xmpp/moderator.js] <i.prototype._allocateConferenceFocusError>:  Focus error, retry after 64000`
`CONFERENCE FAILED: conference.focusDisconnected focus.jitsi.example-domain.com`
`not well formed`

When I tried to go back to the versions where everything was running, the installation process of jicofo died at: 
`ant -lib ~/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar dist.lin64`
As I did not want to examine why it died on the old version, I again installed the latest.
Is anything broken with the current versions or did someone examine similar issues?
My Configs are still the same, listed here: #1053

**Comment by damencho** [comment]
Could you please use the mailinglist for discussing problems and asking questions, before opening issues.
Did you check your jicofo logs? Seems your deployment is missing the jicofo, it is not connected or not running.

**Comment by lorsulic** [comment]
@damencho I've send this issue to issues@jitsi.org mailing list on the 11th of november. Few days before that, I asked twice in the irc. Nobody answered me. So I openend this issue, because everything was already running with the previous version, after the update not. 
Now you asked me if I looked in the the jicofo logs? I said already "The server logs are not showing any errors, only the console inside chrome". 
So what now? I do not get help inside the irc, nor from the mailing list, you now closed my issue here. What can I do now?

**Comment by damencho** [comment]
Hi, again. So we prefer discussing problems on mailinglist before opening issues, so we put on most of the projects a note:
"Discuss
Please use the Jitsi dev mailing list to discuss feature requests before opening an issue on Github."
As said on https://jitsi.org/mailinglists about "issues@jitsi.org": "issues is not a discussion list".

Sorry, I have missed the part with "The server logs are not showing any errors". Normally when the client cannot connect to the focus, the reason is jicofo is not running or there is a problem with jicofo connecting to the xmpp server.
I just talked offline with @paweldomas and he confirmed that there is currently an issue in jitsi-meet/lib-jitsi-meet when using authentication.
And I just found there is already an open issue on the subject, but we still haven't found time to work on that (https://github.com/jitsi/jitsi-meet/issues/1053). So any help is welcome.

**Comment by lorsulic** [comment]
@damencho hi, okay Ohh I've overlooked that I cannot send messages to the issues@jitsi.org. Yeah I'm aware of the Issue #1053, I've opened it. But nevertheless the setup was running, even though not with the anonymousdomain guest but it was working fine for me. This here is definitly an other issue here. But yeah, I will use the dev mailing list for discussing this. Thanks

**Comment by damencho** [comment]
I see. I'm not aware of your setup other then that your are starting everything from source. 
Currently we have PR testing activated, which tests all PRs opened on one of the main projects (jitsi-meet, lib-jitsi-meet, jicofo, libjitsi, jitsi-videobridge). This PR testing checkouts everything from source, compiles and runs it and then executes default jitsi-meet-torture using the deployment that is running from source. Nothing should not be merged before passing that test, so running from source is fine with latest versions.

**Comment by bamania8** [comment]
Please check if jicofo service is running or not.

**Comment by nicolasform** [comment]
I just got the same issue, it appears randomly on a particular room id when the first participant enters. Using another room id solves the problem. I'm doing a lot of testing so maybe it is caused by the fact that I enter/leave the room very frequently.
The link to https://jitsi.org/mailinglists does not work so I can't check if somebody explained this behavior.
Any idea where it can come from?

**Comment by lukaslaskovski** [comment]
> I just got the same issue, it appears randomly on a particular room id when the first participant enters. Using another room id solves the problem. I'm doing a lot of testing so maybe it is caused by the fact that I enter/leave the room very frequently.
> The link to https://jitsi.org/mailinglists does not work so I can't check if somebody explained this behavior.
> Any idea where it can come from?

I have had the same problem for several days. One room with a similar token works and another does not :/

```
2021-01-19T12:04:43.298Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Focus error, retry after 1000 Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 1000
    at l._allocateConferenceFocusError (https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:10:177319)
    at https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:10:176370
    at I.Handler.handler (https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:1:31250)
    at I.Handler.run (https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:1:26549)
    at https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:1:34987
    at Object.forEachChild (https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:1:18211)
    at I.Connection._dataRecv (https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:1:34836)
    at N.Websocket._onMessage (https://web-cdn.jitsi.net/meetjitsi_4628.1244/libs/lib-jitsi-meet.min.js?v=4628.1244:1:64074)
o @ lib-jitsi-meet.min.js?v=4628.1244:10
getGlobalOnErrorHandler @ lib-jitsi-meet.min.js?v=4628.1244:17
window.onerror @ app.bundle.min.js?v=4628.1244:240
callErrorHandler @ lib-jitsi-meet.min.js?v=4628.1244:1
l._allocateConferenceFocusError @ lib-jitsi-meet.min.js?v=4628.1244:10
(anonymous) @ lib-jitsi-meet.min.js?v=4628.1244:10
(anonymous) @ lib-jitsi-meet.min.js?v=4628.1244:1
run @ lib-jitsi-meet.min.js?v=4628.1244:1
(anonymous) @ lib-jitsi-meet.min.js?v=4628.1244:1
forEachChild @ lib-jitsi-meet.min.js?v=4628.1244:1
_dataRecv @ lib-jitsi-meet.min.js?v=4628.1244:1
_onMessage @ lib-jitsi-meet.min.js?v=4628.1244:1
Logger.js:154 2021-01-19T12:04:43.299Z [modules/xmpp/moderator.js] <l._allocateConferenceFocusError>:  Focus error, retry after 1000 <iq xmlns=​"jabber:​client" to=​"edefaeac-fe35-40c1-bd10-40016eb5bc0e@meet.jit.si/​z4VUVYEC" type=​"error" id=​"a97f29dc-9693-41a9-b903-f0188ee59779:​sendIQ" from=​"focus.meet.jit.si">​…​</iq>​
o @ lib-jitsi-meet.min.js?v=4628.1244:10
l._allocateConferenceFocusError @ lib-jitsi-meet.min.js?v=4628.1244:10
(anonymous) @ lib-jitsi-meet.min.js?v=4628.1244:10
(anonymous) @ lib-jitsi-meet.min.js?v=4628.1244:1
run @ lib-jitsi-meet.min.js?v=4628.1244:1
(anonymous) @ lib-jitsi-meet.min.js?v=4628.1244:1
forEachChild @ lib-jitsi-meet.min.js?v=4628.1244:1
_dataRecv @ lib-jitsi-meet.min.js?v=4628.1244:1
_onMessage @ lib-jitsi-meet.min.js?v=4628.1244:1
Logger.js:154 2021-01-19T12:04:43.321Z [features/overlay] <Object.componentDidMount>:  The conference will be reloaded after 25 seconds.
Logger.js:154 2021-01-19T12:04:43.339Z [conference.js] <Z._onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected focus.meet.jit.si 1
```

**Comment by damencho** [comment]
Do you see any errors in jicofo logs?
