### ISSUE TITLE
camera on after screenshare in startAudioOnly=true mode

### ISSUE THREAD

**Issue by dpanic** [jitsi/jitsi-meet#11460]
### Description:

I have started call with config.startAudioOnly=true, screenshare is turned on, but camera is turned on instead (nobody asked for this).

### Steps to reproduce:
1. Start call with config.startAudioOnly=true
2. Everything is off, screenshare is off, video is off
3. One turns on screen share
4. Camera is on, it shouldn't be, screenshare is off still
5. One turns on screen share again
6. Camera is off, screen share is on

### Expected behavior:

Camera off

### Actual behavior:

Camera on

### Server information:

- Jitsi Meet version: 2.0.7210 (2.1-665-g3a90ccdc)
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Google Chrome 101.0.4951.41 / 
- Operating System: macOS Monterey 12.3.1 (21E258)

### Additional information: 2.0.7210 
- This looks like Chrome on macOS related issue

**Comment by saghul** [comment]
How did you set that option, in config.js or with an override?

I wonder if you are running into https://github.com/jitsi/jitsi-meet/issues/8144

**Comment by saghul** [comment]
Can you reproduce this on meet.jit.si ? Here is what I'm doing and I can't:

- navigate to https://meet.jit.si/something#config.startAudioOnly=true
- I get asked for mic permission only in the pprejoin screen
- hit join
- i'm in the meeting and have no video
- I then enable video (get asked for permission)
- close the tab
- open it again
- same thing, the prejoin screen shows no video

**Comment by dpanic** [comment]
I am able to reproduce bug on meet.jit.si

Here is proof:

https://www.youtube.com/watch?v=s8-d5Rdy2aM

**Comment by saghul** [comment]
So weird, I tried but I couldn't repro. I didn't have much time, so I'll test again.

**Comment by dpanic** [comment]
Ok, I will remind you in couple of days in case you forget. Thanks
