### ISSUE TITLE
raise-hand.enabled and security-options.enabled not working

### ISSUE THREAD

**Issue by amjidkhanmohmand** [jitsi/jitsi-meet#11469]
Hello Team Jitsi
Hopefully, you are in good health. I just found a bug in SDK version 5.0.2. What I am trying to do is to hide **"Security options"** and **"Raise Hand option"**, I have added the flags as they were supposed to be added but unfortunately, nothing happened.
I am using Android version 12, I have also tested in Android 11 but the results are still the same. Below is my code, please provide me the guidance ASAP because I am adding it to my project.

`

    private void StartMeeting()
    {
        if (currentMeeting != null) {

            if (currentMeeting.user_id.equals(userProfileId))
            {
                isHost=true;
                user_status_in_meet=3;
            }
            String lobbyMode="disabled";
            if (!isHost)
            {

            }

            boolean isKickOut=false;

            if (isHost)
            {
                isKickOut=true;
            }

            boolean isMenuEnabled=false;
            if (isHost)
            {
                isMenuEnabled=true;
            }

            //Simple Listner
            boolean audio_video_button_show=true;
            if (user_status_in_meet==1)
            {

                audio_video_button_show=false;
            }

            registerForBroadcastMessages();
            try {
                String meet_title = PublicFunctions.decode(currentMeeting.title);

                txt_title.setText(""+meet_title);

                pf.activeText(MeetingActivity.this, txt_title, meet_title, null, null);

                options = new JitsiMeetConferenceOptions.Builder()
                        .setServerURL(new URL("https://meet.jit.si"))
                        .setRoom("" + currentMeeting.meet_code)
                        .setAudioMuted(true)
                        .setVideoMuted(true)
                        .setAudioOnly(false)

                        .setFeatureFlag("kick-out.enabled", isKickOut)
                        .setFeatureFlag("invite.enabled", false)
                        .setFeatureFlag("help.enabled", false)
                        .setFeatureFlag("meeting-password.enabled", false)
                        .setFeatureFlag("recording.enabled", false)
                        .setFeatureFlag("overflow-menu.enabled",isMenuEnabled)
                        .setFeatureFlag("raise-hand.enabled", false)
                        .setFeatureFlag("notifications.enabled", false)

                        .setFeatureFlag("lobby-mode.enabled", lobbyMode)
                        .setSubject("" + meet_title)
                        .setFeatureFlag("add-people.enabled", false)
                        .setFeatureFlag("security-options.enabled", false)
                        .setFeatureFlag("security-options.enabled", "disabled")

                        .setFeatureFlag("audio-mute.enabled", audio_video_button_show)
                        .setFeatureFlag("video-mute.enabled", audio_video_button_show)
                        .setFeatureFlag("pip.enabled","enabled")
                        .setUserInfo(jitsiMeetUserInfo)
                        .build();

                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        JitsiMeetActivity.launch(MeetingActivity.this, options);

                    }
                });

            } catch (MalformedURLException e) {
                e.printStackTrace();
            }

        }
    }

`

**Comment by saghul** [comment]
I believe the security dialog flag has been fixed in master, I'll check the other one.

**Comment by amjidkhanmohmand** [comment]
Above is mey code that i have implemented in my app and this is the screenshot of the app. ![IMG_20220430_154107.jpg](https://user-images.githubusercontent.com/36640903/166102271-16379a03-eaa3-42b5-afe2-ff1f46357b81.jpg)

**Comment by saghul** [comment]
Alright, found it.

> .setFeatureFlag("raise-hand.enabled", false)

You need to also disable "reactions.enabled" or you'll get the emojis menu.

> .setFeatureFlag("security-options.enabled", false)
>  .setFeatureFlag("security-options.enabled", "disabled")

Yu need to drop that second line. A string will basically make the value "truthy" since we don't parse it, you need to use a real boolean.

**Comment by saghul** [comment]
I did notice a bug though. If you want the reactions but not the raise hand functionality, that was broken. Fixed in https://github.com/jitsi/jitsi-meet/pull/11497
