### ISSUE TITLE
Question: Modifying the Jitsi-Meet React Native App

### ISSUE THREAD

**Issue by RudraSen2** [jitsi/jitsi-meet#11468]
Hello, I am creating a modified version of the jitsi-meet app with platforms including Web, Electron (Desktop), and React Native (Mobile). I have created Web and Desktop. Can you please tell me how to modify ONLY the react native app as I am new to development (I'm a student) and want to create the mobile app?

**Comment by saghul** [comment]
Please post in our community, we use the issue tracker for bugs.

This repo also contains the code for the mobile app, it shares code with the web app. So you are right where you need to make the changes.
