### ISSUE TITLE
GiphyUISDK files not found in latest 2.0.7210

### ISSUE THREAD

**Issue by chrismcclune** [jitsi/jitsi-meet#11485]
### Steps to reproduce:

1. Close repository
2. run command 'npm install'
3. cd ios
4. pod install
5. follow steps to clean the build and build to output folder the 2 archives etc.
6. Transfer JitsiMeetSDK.xcframework and WebRTC.xcframework into project and include as 'embed and sign'
7. Run application

Xcode console output:

dyld[713]: Library not loaded: @rpath/GiphyUISDK.framework/GiphyUISDK
  Referenced from: /private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK
  Reason: tried: '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/../../Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/System/Library/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file)
Library not loaded: @rpath/GiphyUISDK.framework/GiphyUISDK
  Referenced from: /private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK
  Reason: tried: '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/../../Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/var/containers/Bundle/Application/49698375-181F-4D54-B7F6-4C92F3340AAA/myapp.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (no such file), '/private/va

### Expected behavior:

Application should not crash on launch.

### Actual behavior:

Application crashes on splash screen.

### Server information:

- Jitsi Meet version: 2.0.7210
- Operating System: Xcode 13.3, macOS 12.2.1, iOS 15.x

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
We are in the process of changing how the SDK deals with its own dependencies: https://github.com/jitsi/jitsi-meet-ios-sdk-releases/blob/master/JitsiMeetSDK.podspec.tpl

In the next release the SDK will be released standalone and WebRTC and Giphy will be depended upon with cocoapods.

Alternatively you can manually add those 2 frameworks, if you are not using cocoapods.
