### ISSUE TITLE
Missing key name in config.js

### ISSUE THREAD

**Issue by federico-ntr** [jitsi/jitsi-meet#11491]
As @WestleyArgentum already brought to attention [here](https://github.com/jitsi/jitsi-meet/pull/6957#discussion_r492666268_), I think [this line](https://github.com/jitsi/jitsi-meet/blob/346aadc23d6f20b5f8815a682147a45090194acb/config.js#L1050) misses key name.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

There is nothing missing there, as the text describes this documents a response returned by a separate service.

**Comment by federico-ntr** [comment]
I thought there was an issue in that line, this is why I opened an issue and not a topic in the forum.

By the way, my bad for not noticing the double `*` at the start of the comment, I thought that and `// dynamicBrandingUrl: ''` were two separate things. I still think it's a bit unclear how to use it from those four lines. Maybe someone who knows how that work can make it more clear (or maybe I'm just dumb).

Also, I think JS docs should have a `*` as the start of every line. At list this is how I always saw JS docs used and it would help distracted people like me to notice that is a doc comment and not actual code 😄
