### ISSUE TITLE
Add a separate button to ask user to activate their camera

### ISSUE THREAD

**Issue by JohannesPertl** [jitsi/jitsi-meet#11503]
In addition to "Ask to unmute" in the participants pane, it would be great to have a similar button, but for asking the user to activate their camera.
Maybe inside the context menu on the right. 

![image](https://user-images.githubusercontent.com/45853628/167082585-b9e3bd55-a189-4cc9-a5c4-bd34dbac23f7.png)

**Comment by saghul** [comment]
IIRC right now that action unlocks both media types. Maybe we should reword it, come to think of it...

**Comment by JohannesPertl** [comment]
In the german localization, the notification message specifically mentions activating the microphone, so localization should probably be reworded too.

Also, the "Ask to unmute" button is only displayed, if the microphone of the participant is muted. If only the camera is deactivated, the button doesn't show.

**Comment by saghul** [comment]
> If only the camera is deactivated, the button doesn't show.

Oh...

**Comment by nawed2611** [comment]
Hey, Can I work on this issue?

**Comment by saghul** [comment]
We haven't yet decided how the feature should behave, sorry.

It's on the (long) task list...
