### ISSUE TITLE
Stable 7210 version includes old sources

### ISSUE THREAD

**Issue by benni3223** [jitsi/jitsi-meet#11502]
### Description:

Hi, 
we are using Jitsi via https://download.jitsi.org/stable/ deb packages, we use the iframe API for our integration. Our implementation is not released yet, just as pilot, but we have the legal requirement that all calls have to be e2ee, therefor we need to activate it automatically. 
I looked into the jitsi-meet source code and mentioned that you have added the toggleE2EE in the external_api.js, which we need necessarily, otherwise we cannot get rid of our own mesh implementation in our application right now.

So we installed the newest version jitsi-meet_2.0.7210-1_all.deb, but i mentioned that there is a really old state of jitsi-meet delivered, seems to be version 6091 (10 months old) and not the version of the tag [stable/](https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_7210).  

### Steps to reproduce:
1. Deploy 7210 version
2. Open chrome dev tools
3. prettify the external_api.js as example
4. Compare to the code in the stable 7210 tag

### Expected behavior:
The version bundle of 7210 should also include the sources of the according stable-tag.

### Actual behavior:
It seems to be an older source code state which is delivered.

![image](https://user-images.githubusercontent.com/26083510/166976799-890c79a6-522f-48b7-aeeb-336946049dce.png)
Here you see on our 7210 environment, we don't have the toggleE2EE, also not other commands like the ones for the breakoutroom. In the 7210 tag they are included.
https://github.com/jitsi/jitsi-meet/blob/stable/jitsi-meet_7210/modules/API/external/external_api.js#L74

### Server information:
- Jitsi Meet version: 7210

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

I went and downloaded the debian package:
wget https://download.jitsi.org/stable/jitsi-meet-web_1.0.6091-1_all.deb
those corresponds to jitsi-meet_2.0.7210-1_all.deb
opened the external_api.min.js and I see:
![image](https://user-images.githubusercontent.com/3263098/166979837-2d948963-5c67-4070-a77d-e0ad92b6900e.png)

Probably it is cached on your side or you are serving some other version.

**Comment by bennihoss** [comment]
Hey, thanks for the fast response. I confirmed it, you are right. Somehow the application itself got an update, but it seems that only the external_api.js is somehow cached somewhere, because this one is really old. I will check with our devops whats wrong there, sorry for the wrong alarm.

**Comment by damencho** [comment]
👍
