### ISSUE TITLE
iOS Video is not working if the lock screen is actived 

### ISSUE THREAD

**Issue by mohammadebrahim** [jitsi/jitsi-meet#11500]
### Description:

The video is not working when coming from the lock screen.

### Steps to reproduce:

1. Close App send the app to the background
2. Lock the Phone
3. Wait for 30Sec
4. Make an incoming call.
5. Accept call

### Expected behavior:

Should enter the room.

### Actual behavior:

App stuck in the connecting black screen for reference please see the screenshot attached

![IMG_0006](https://user-images.githubusercontent.com/3043204/166930761-e898a4ca-beff-4424-b37c-d4b597c15496.PNG)

### Client information:

- Jitsi SDK Version: 5.0.0
- Operating System: iOS15.4

**Comment by mohammadebrahim** [comment]
okay @saghul

**Comment by saghul** [comment]
I don't think so. We don't do incoming calls so I have never been able to have a proper way to reproduce this.

**Comment by mohammadebrahim** [comment]
@developerashish01 I have added a 2-second delay.
