### ISSUE TITLE
Blue screen while joining Jitsi Videoconference

### ISSUE THREAD

**Issue by RaphaelNemec** [jitsi/jitsi-meet#11515]
### Description:
This Bug relates to: https://community.jitsi.org/t/blue-screen-while-joining-jitsi-videoconference/114200

We have the problem that users more and more often get into a “blue screen”.
At the moment, the error does not occur every time. On average every 4th-5th attempt to join a Jitsi video conference.

### Steps to reproduce:

1. Go into a room
2. Click "Join Conference
3. Click “Join Conference” again
4. Gray/blue blank page appears in Jitsi

### Expected behavior:

The user joins the video conference and is able to talk with other people.

### Actual behavior:

Gray/blue blank page appears in Jitsi.
Nothing can be done on the users perspective.
![blue_screen_copy](https://user-images.githubusercontent.com/103118350/167370744-e2541c51-6dce-465b-9144-2e09220d14ef.png)

### Server information:

- Jitsi Meet version: stable-6865
- Operating System: 

### Client information:
- Operating System: Windows 10
- Browser: Desktop Browser (Chrome, Edge, Firefox). Even in incognito mode the error appears meanwhile.
- Browser / app version: latest

### Additional information:

I already created a Ticket in the Jitsi Community. https://community.jitsi.org/t/blue-screen-while-joining-jitsi-videoconference/114200
As you can see, Manuel provided additional information.

Attached here is the log: 
[jitsi_blue_screen.log](https://github.com/jitsi/jitsi-meet/files/8649979/jitsi_blue_screen.log)

**Comment by saghul** [comment]
At a quick glance the problem starts in this line: https://github.com/jitsi/jitsi-meet/blob/36578696bb1e162ef6b61fb5a2b53e414bf24865/conference.js#L3159

Looks like the local participant is `undefined`.

Any chance you are trying to change the display name before the conference joined event?
