### ISSUE TITLE
Able to mute a participant just for me, not for the whole conference

### ISSUE THREAD

**Issue by mailinglists35** [jitsi/jitsi-meet#11523]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
When I am in the same physical room with other conference members, I hear my colleagues with echo, first their natural voice over the air, then the voice electronically over IP in jitsi

**Describe the solution you'd like**
Please describe the desired behavior.
able to mute my room participants one by one just for me (not for everyone) by clicking a button in the interface

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
1. buy expensive central bluetooth/usb speaker with microphones dedicated conference device
2. each participant go away alone in their own room which does not exist

**Comment by mailinglists35** [comment]
I see a volume slider for each participant, but adjusting it does nothing

**Comment by mailinglists35** [comment]
ah lol it works on the website. I was sliding the slider on web but listening in the mobile app 🙈

sooo, cand we have this volume slider in the mobile apps as well, please? :)

**Comment by saghul** [comment]
It's on the TODO list...

**Comment by fleaz** [comment]
Regarding the volume slider:

Why does only the conference admin has a "Mute" button  (Talking about "Mute" not the "Mute for everyone else" button)? Sliding the volume slider down to zero is effectively the same as muting the participant just with more work so it's not really a permission thing to not show this button to non-moderators.

**Comment by saghul** [comment]
It's a bit confusing indeed.

Mute a participant means mute it in the meeting, so for everyone.

The "mute everyone else" means just that, mute everyone in the meeting except the selected participant.

The slider is the only local action.

**Comment by fleaz** [comment]
Oh, thanks for clarification! Apparantly I never read the labels of the buttons correctly :D

**Comment by saghul** [comment]
It now works on the app too!
