### ISSUE TITLE
Android + Expo + React Native causing : FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by dfabreguette-ap** [jitsi/jitsi-meet#11527]
Hi,
Since a recent update to expo 44, JitsiMeet SDK won't launch on android devices, getting this crash :

https://gist.github.com/dfabreguette-ap/20fedf4fc3c53d624a1632bbe650a009

### Description:

As my JitsiMeetView component is getting initialized through RNJitsiMeetView, I end up with this crash in release variant mode.

I'm using https://github.com/skrafft/react-native-jitsi-meet npm package.

### Steps to reproduce:

I'm manage to recreate the bug with a fresh expo app in SDK 44 : 
https://github.com/dfabreguette-ap/expo-jitsi-error

1. Clone
2. yarn install
3. cd android && ./gradlew assembleRelease
4. adb install -r path/to/release/apk
5. Launch the app and click the "Jitsi" Button

### Expected behavior:

Should not crash

### Actual behavior:
Should open up Jitsi room

### Server information:

Using Jitsi meet main instance

### Client information:

- Browser / app version: 3+
- Operating System: android

**Comment by saghul** [comment]
> I'm using https://github.com/skrafft/react-native-jitsi-meet npm package.

We are not the maintainers of such package, please ask the maintainer.
