### ISSUE TITLE
Jitsi Meet not supported

### ISSUE THREAD

**Issue by shaheryarbabar** [jitsi/jitsi-meet#11532]
### Description:
 After Updating the Flutter Latest Version to 3.0 The Jitsi Meet is not working It gives the error "Execution failed for task ':jitsi_meet:compileDebugKotlin'.
". 

### Steps to reproduce:

1. Open 'Project' 
2.  Type Flutter Run
3. the error Will Come "Execution failed for task ':jitsi_meet:compileDebugKotlin'."

### Expected behavior:

 Like the previous Version it has to be work Smooth.

### Actual behavior:

 Execution failed for task ':jitsi_meet:compileDebugKotlin'. 

### Server information:

- Jitsi Meet version: 4.0
- Operating System: Flutter For Mobile

### Client information:

- Browser / app version: 4.0
- Operating System: Flutter for Mobile

### Additional information:

Please provide additional information about the bug, if any.

**Comment by saghul** [comment]
We are not the authors of the Flutter plugin, you should ask them.
