### ISSUE TITLE
Jitsi Meet is unable to access to microphone and camera in Firefox

### ISSUE THREAD

**Issue by ghost** [jitsi/jitsi-meet#11535]
### Description:

Jitsi Meet is unable to access to microphone and camera in Firefox even if it's allowed.
So, no one can hear me or see me in a call.

### Steps to reproduce:

1. Open Firefox
2. Open a call with Jitsi Meet (example : https://meet.jit.si/test)
3. Allow Jitsi Meet to access to microphone and camera
4. Jitsi Meet say that he can't access to microphone and camera

### Expected behavior:

Jitsi Meet should be able to access to the microphone and the camera

### Actual behavior:

Jitsi Meet can't access to the microphone and the camera

### Client information:

Firefox 100 on all operating system (Linux, Windows etc...)

### Additional information:

I join a screenshot in attachment
![Jitsi](https://user-images.githubusercontent.com/104614882/168425214-c37b6145-3256-4812-9c03-4d2ddff0d539.png)

**Comment by saghul** [comment]
Can you please paste the JS console logs?

**Comment by Pictor13** [comment]
How did you re-enabled it?

I have the same issue as you, just on Firefox (over Ubuntu 20.04), but in `about:config` I already have `media.peerconnection.enabled` set to `true`.
