### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by dpanic** [jitsi/jitsi-meet#11530]
### Steps to reproduce:
1. npm install

### Actual behavior:
npm ERR! code ERESOLVE                                                                          
npm ERR! ERESOLVE could not resolve
npm ERR!                                                                                        
npm ERR! While resolving: @atlaskit/button@15.1.4
npm ERR! Found: react@17.0.2                                                                    
npm ERR! node_modules/react                                                                     
npm ERR!   react@"17.0.2" from the root project                                                 
npm ERR!   peer react@"*" from @amplitude/react-native@2.7.0         
npm ERR!   node_modules/@amplitude/react-native                                                 
npm ERR!     @amplitude/react-native@"2.7.0" from the root project
npm ERR!   62 more (react-transition-group, ...)       
...

### Additional information:
node v16.14.2

**Comment by saghul** [comment]
What npm version are you using? What commit are you trying to build?

**Comment by dpanic** [comment]
> What npm version are you using? What commit are you trying to build?

npm 6.9.0

2.0.7287
stable/jitsi-meet_7287

**Comment by saghul** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web#building-the-sources

You need npm >= 8.

**Comment by dpanic** [comment]
Actually it is.
I made mistake when copy pasting, sorry.


dpanic@master:jitsi.com/src on  master [!?] ➜ npm --version
8.8.0

dpanic@master:jitsi.com/src on  master [!?] ➜ node --version
v16.14.2

**Comment by saghul** [comment]
Can you please gist the entire error message? Did you do `npm update` by any chance?

**Comment by dpanic** [comment]
https://gist.github.com/dpanic/75387ddd580bd30679e2160cd736f5a7

No I wasn't doing any ```npm update```. It was clean ZIP downloaded from release.

**Comment by saghul** [comment]
I tried but cannot reproduce this. Busted my cache with `npm cache clean --force` so I have no idea what could be causing this :-/

**Comment by dpanic** [comment]
Problem identified on my side. 

I was unziping archive and moving files, with command ```mv archive/*``` but I left .* files.

Among them was .nvmrc ...
