### ISSUE TITLE
setup help required

### ISSUE THREAD

**Issue by KanwarPadda** [jitsi/jitsi-meet#11545]
### Steps to reproduce:
1> npm install
2> npm start 
error > 
> jitsi-meet@0.0.0 start
> make dev

'make' is not recognized as an internal or external command,
operable program or batch file.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Please use our community to ask such questions, we ise the issue tracker for bugs in the software itself.

You need to install the `make` utility in your system.
