### ISSUE TITLE
Participants joining a call get assigned a different / wrong encryption key

### ISSUE THREAD

**Issue by herwin06** [jitsi/jitsi-meet#11556]
I work as part of a virtual team We start every day with a short audio call (ie we turn of the video). I have convinced our organisation to use Jitsi for this call. We use e2ee.

For over a month now, every morning we have the same problem:

At least once when a person joins the call, the sound get garbled for everyone. I assume that means that they get a different encryption key? That person can sign out and sign in again many times, but the problem will remain each time to join the call.

The only solution that works is that everyone else leaves the call and re-join; then everything works fine.

Sometimes the problem re-occurs a second time when someone else joins the call (not necessarily the next person to join the call, everything may work fine for the next few people to join and then it re-occurs when someone joins). Sometimes the problem does not re-occur a second time.

It is extremely rare for the problem not to occur at all.

Any idea what causes this? And even more importantly: what, if anything, can we do to prevent this from happening?

Thanks

**Comment by herwin06** [comment]
Thanks. We will try this in tomorrow's call.

(just FYI, next week we have our annual face-to-face staff meetings, so after tomorrow, there will be no Jitsi calls for a week)

**Comment by herwin06** [comment]
OK, we have been  overriding the preferred codec as per your suggesting last week, by using a link like:

https://meet.jit.si/blablabla#config.videoQuality.preferredCodec="VP8"

The problem does not occur as often now as it did before, but there are days that the problem still occurs, so it does solve the problem.

**Comment by saghul** [comment]
Thanks for the feedback.

**Comment by saghul** [comment]
We have made a few fixes but I don't think they have been deployed to production yet.

**Comment by benni3223** [comment]
thats good to hear, i have implemented a feature toggle to disable the managed keymode, so as soon it is deployed on our test stage then, our QA can test it :)

**Comment by saghul** [comment]
You should be able to test it on beta.meet.jit.si too.
