### ISSUE TITLE
applyVirtualBackground overwrites doNotFlipLocalVideo

### ISSUE THREAD

**Issue by psi-4ward** [jitsi/jitsi-meet#11553]
Set `doNotFlipLocalVideo=true` in config and choose a virtual background image => flipped 

https://github.com/jitsi/jitsi-meet/blob/master/react/features/virtual-background/components/VirtualBackgroundDialog.js#L483

```js
 if (_localFlipX && options.backgroundType === VIRTUAL_BACKGROUND_TYPE.DESKTOP_SHARE) {
    dispatch(updateSettings({
        localFlipX: !_localFlipX
    }));
} else {

    // Set x scale to default value.
    dispatch(updateSettings({
        localFlipX: true
    }));
}
```

We need something like `else if !config.doNotFlipLocalVideo` ...

 btw: `localFlipX: false` is much more readable than `localFlipX: !_localFlipX` :wink:

**Comment by saghul** [comment]
Ping @tudor-phd do you remember why this was done this way?

**Comment by saghul** [comment]
A PR would be welcome, but alas we don't have time look into this now, sorry.
