### ISSUE TITLE
“Share audio” and Bluetooth headset not working

### ISSUE THREAD

**Issue by BoOwnrs** [jitsi/jitsi-meet#11559]
### Description:

The fairly new feature where you share audio from a chrome tab is cool, but I can’t get it to work as intended.

When a meeting host, using a Bluetooth headset with built-in mic, shares audio from a chrome tab, the host can hear the audio, but the participants can’t, they can only hear the host microphone.

I tried with another Bluetooth headset which resulted in that the participants can hear shared audio, but the microphone used is the computers, so the voice coming from the host is bad.

### Steps to reproduce:

1. Connect Bluetooth headset to computer(windows 10)
2. Start a jaas meeting as a host (from chrome)
3. Start a “Share audio” from another tab in chrome
4. Join the meeting as a participant

### Expected behavior:

The participant can hear sound from the host headset mic and the shared audio from the chrome tab.

### Actual behavior:

I have two scenarios:
1. The partipant can hear sound from the host headset mic only
2. The partipant can hear the shared audio from chrome, but the host mic is coming from the computer mic

### Server information:

- Jitsi Meet version:
- Operating System: Using Jaas (their support say they can't reproduce, which I find odd)

### Client information:

- Browser / app version: Chrome
- Operating System: Windows 10

**Comment by saghul** [comment]
@andrei-gavrilescu @jallamsetty1 can you PTAL when you get a chance?

**Comment by andrei-gavrilescu** [comment]
So this issue has been recently fixed by https://github.com/jitsi/jitsi-meet/pull/11325/files. Should be available in the next release. Feel free to test it out on https://alpha.jitsi.net/.

**Comment by saghul** [comment]
JaaS is usually a few weeks behind, so you can expect it in the next couple of weeks or so. You can also test with the JaaS staging platform.

**Comment by andrei-gavrilescu** [comment]
It was just added so it might take a while. Please follow https://developer.8x8.com/jaas/docs  under `Release Notes` to stay up to date.
