### ISSUE TITLE
Failed to parse URL parameter value: _ SyntaxError: Unexpected token _ in JSON at position 0

### ISSUE THREAD

**Issue by jindovu** [jitsi/jitsi-meet#11565]
Hi There!
      I got bug with using external link with jitsi-meet like image bellow and I don't know why it happend, when I try to deploy in production it's working fine with mobile version, but for the PC it's not working, Could everyone can let's me know this issue?

Thanks a lot! 

![image](https://user-images.githubusercontent.com/19401173/169645562-d3ddef48-076e-4f53-a0b7-2486ac97ac60.png)

**Comment by saghul** [comment]
What URL are you using?

**Comment by jindovu** [comment]
> What URL are you using?

I using this link https://ezpztalk.com/#!/room/english-for-everyone#_=_

**Comment by saghul** [comment]
We will try to parse the hash Paraná as JSON, that's why it's failing.

**Comment by jindovu** [comment]
That's issue come from url and I'm using AngularJS for now, do you have suggestion for that?

**Comment by saghul** [comment]
I am not familiar with Angular, sorry!

**Comment by jindovu** [comment]
I’m very appreciate your comment, Thanks

**Comment by oanguenot** [comment]
Hi @saghul, I have the same problem with Angular too

external_api.js:1 Failed to parse URL parameter value: DC614671494732 SyntaxError: Unexpected token 'D', "DC614671494732" is not valid JSON

The URL that loads the IFrame is something like: https://my.domain.com/#/home/pcs?reference=DC614671494732&asDelegate=true

On my side, I load the script like this:

```
// Load the Jitsi Meet library (depending on the hosted domain)
const scriptEl = window.document.createElement('script');
scriptEl.src = `https://${environment.jitsiDomain}/external_api.js`;
window.document.body.appendChild(scriptEl);
```

**Comment by saghul** [comment]
I think I've found the problem. Fix here: https://github.com/jitsi/jitsi-meet/pull/13597

**Comment by oanguenot** [comment]
Thank you very much @saghul :-)
