### ISSUE TITLE
IOS app starts with internal phone speakers instead of speakers

### ISSUE THREAD

**Issue by jklippel** [jitsi/jitsi-meet#11563]
### Description:

IOS app starts with internal phone speakers instead of speakers

### Steps to reproduce:

1. Open jitsi on iOS
2. Join a meeting

### Expected behavior:

The sound is connected to the general speaker. This should be the default or it should be configured as a default.

### Actual behavior:

The sound is connected to the internal phone speaker.

### Server information:

- Jitsi Meet version: 2.0.7287 (Docker build stable-7287)
- Operating System: Linux

### Client information:

- Jitsi Meet version: 22.2.0 build 1652454796
- Operating System: iOS

### Additional information:

It would be nice if this could be configured, but the internal phone speaker being the default is breaking UX. Users expect to use the camera and the external speaker when joining a VC.

**Comment by saghul** [comment]
Hum that's odd we explicitly default to the speaker, which is what I see when I try to repro.

**Comment by jklippel** [comment]
Speaker meaning the internal phone speaker or the loudspeaker that everyone can hear?
I just tested it again and it defaulted to the internal phone speaker. (Maybe someone can come up with better vocabulary here, as a non native speaker I am having problems expressing which speaker I mean :))

**Comment by saghul** [comment]
Sorry hehe yeah Yerma can get confusing.

We default to the loudspeaker, not the earpiece.

**Comment by jklippel** [comment]
Ok and this is not true with my app(s) (multiple installation, multiple phones).
It is even weirder. It seems to be random.

The loudspeaker was used when I was the first participant in a meeting.
The earpiece was used on joining an existing meeting.

I even tested with a different server. Always with another person. Both apps used are on the current test flight version.

**Comment by saghul** [comment]
That's very odd! The server shouldn't matter.

I'll keep an eye open and see if we can repro.

**Comment by marwenmoalla** [comment]
I'm able to reproduce the issue with iPhone 12 iOS 15.4.1  using JitsiMeetSDK 5.1.0. 
Issue not reproduced with same device when using JitsiMeetSDK 5.0.2
It's a regression with 5.1.0
CallKit is disabled for my test. Here is the list of feature flags

builder.serverURL = weakSelf.jitsiConfig.server;
        builder.room = weakSelf.jitsiConfig.room;
        builder.token = weakSelf.jitsiConfig.token;
        builder.userInfo = userInfos;
        builder.videoMuted = true;
        [builder setFeatureFlag:@"invite.enabled" withBoolean:false];
        [builder setFeatureFlag:@"add-people.enabled" withBoolean:false];
        [builder setFeatureFlag:@"server-url-change.enabled" withBoolean:false];
        [builder setFeatureFlag:@"meeting-password.enabled" withBoolean:false];
        [builder setFeatureFlag:@"live-streaming.enabled" withBoolean:false];
        [builder setFeatureFlag:@"pip.enabled" withBoolean:false];
        [builder setFeatureFlag:@"ios.recording.enabled" withBoolean:false];
        [builder setFeatureFlag:@"calendar.enabled" withBoolean:false];
        [builder setFeatureFlag:@"close-captions.enabled" withBoolean:false];
        [builder setFeatureFlag:@"video-share.enabled" withBoolean:false];
        [builder setFeatureFlag:@"security-options.enabled" withBoolean:false];
        [builder setFeatureFlag:@"reactions.enabled" withBoolean:false];
        [builder setFeatureFlag:@"speakerstats.enabled" withBoolean:false];
        [builder setFeatureFlag:@"call-integration.enabled" withBoolean:false]; // CallKit integration
        [builder setFeatureFlag:@"chat.enabled" withBoolean:true];
        [builder setFeatureFlag:@"raise-hand.enabled" withBoolean:true];

**Comment by idrive-pankaj** [comment]
Hi @saghul I am also facing the same issue, by default, it's using the mobile device's internal speaker instead of a loud speaker.
same for the Android as well.

**Comment by saghul** [comment]
I could reproduce it on iOS now. Looking into it.

**Comment by idrive-pankaj** [comment]
> I could reproduce it on iOS now. Looking into it.

Great, thanks @saghul

**Comment by idrive-pankaj** [comment]
Thanks @saghul it's working with your fixes.
