### ISSUE TITLE
External API: TypeError: 'https://meet.jit.si/xxxxxxx' is not a valid URL

### ISSUE THREAD

**Issue by thijzert** [jitsi/jitsi-meet#11567]
### Description:

When embedding Jitsi Meet in an application using the IFrame API, it initially works fine, but crashes with a TypeError after 10-13 reloads.

The embedded Jitsi Meet application does not have access to the parent frame's LocalStorage, so the external API provides what would normally be stored there through the IFrame's URL. Unfortunately, `jitsiLocalStorage` also has the `features/recent-list` field, which apparently contains a list of all Jitsi URL's the user has previously visited. This means that each time you visit a new room, an entry is appended to the `recent-list` which among other things contains the entire `recent-list` itself in encoded form, effectively doubling its size every time.

After about ~11 iterations the resulting URL will be over one megabyte in size, at which point my browser refuses to parse it and instead throws an exception.

### Steps to reproduce:
1. Host the following HTML page somewhere:
```javascript
<!DOCTYPE html>
<html><body>
	<div id="parent"></div>
	<script src="https://meet.jit.si/external_api.js"></script>
	<script>
		const randomRoom = () => {
			return Math.random().toString().substr(2) + Math.random().toString().substr(2) + Math.random().toString().substr(2) + Math.random().toString().substr(2);
		}
		const dw = (t) => {
			let p = document.createElement("P");
			p.textContent = t;
			document.body.appendChild(p);
		}

		try {
			const api = new JitsiMeetExternalAPI("meet.jit.si", {
				parentNode: document.getElementById("parent"),
				roomName: randomRoom()
			});
		} catch ( e ) {
			dw(e.toString());
		}

		if ( localStorage.hasOwnProperty("jitsiLocalStorage") ) {
			dw("Local Storage size: " + localStorage["jitsiLocalStorage"].length);
		} else {
			dw("(no jitsi local storage)");
		}
	</script>
</body></html>
```

2. Open it in your browser, and reload it several times. (Being careful to wait until all code has run. Actually entering the meeting is not necessary.)
3. Watch the localStorage size balloon. Once it reaches above 1MB, an exception is thrown.

### Expected behavior:

The fifteenth time I expect it to work as well as it did the first time.

### Actual behavior:

[error.txt](https://github.com/jitsi/jitsi-meet/files/8749307/error.txt)

### Client information:

- Browser / app version: Firefox 100.0
- Operating System: Linux

### Workaround
In my client code, I've added the following lines.
```javascript
if ( localStorage.hasOwnProperty("jitsiLocalStorage") ) {
	let jls = JSON.parse(localStorage["jitsiLocalStorage"]);
	jls["features/recent-list"] = "[]";
	localStorage["jitsiLocalStorage"] = JSON.stringify(jls);
}
```
This clears the recents list just before creating the API object.

**Comment by saghul** [comment]
You can disable the recents list like so: https://github.com/jitsi/jitsi-meet/blob/b4febf728dc8a956b76440d3a48e50637d811d32/config.js#L1013

Set that to true in a config override to the iframe API.

**Comment by thijzert** [comment]
Ah, that's a much nicer workaround than what I had!

As for the actual solution: I think that if something does get added to the recents list, it should not itself contain a copy of the recents list.

**Comment by saghul** [comment]
The entire state needs to be part of the URL when there is no usable local storage available.

I think we should default to not storing the room on the iframe.

**Comment by thijzert** [comment]
> The entire state needs to be part of the URL when there is no usable local storage available.
I concur. For the purposes of setting the IFrame's `src`, nothing should be left out. But does the entire state also need to be stored in the recents list, or will the room name be sufficient in that context?

> I think we should default to not storing the room on the iframe.
That'd do it.
