### ISSUE TITLE
Not Sound Received by participants when speaking in Android TV

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#11562]
Hi Jitsi Meet Team,
Sound is not received by other participants when speaking in Android TV. Please check Android TV Detail :-

![Skype_Picture_2022_05_19T13_14_51_568Z](https://user-images.githubusercontent.com/49673803/169302054-5ad5ec7b-87a4-44ef-a537-2ab5f583d70f.jpeg)

Can you please help regarding this ?

Thanks

**Comment by pankajnegi1893** [comment]
We are external camera and there mic option is there also. but sound not coming for other participant. same we tested in other conference app in TV there it's working

**Comment by saghul** [comment]
Is there any other mic in the system? TBH I'm not sure how the system will behave with multiple mics since the API is just setting a Boolean for mic on or off.
