### ISSUE TITLE
Could not find com.facebook.fresco:ui-common:2.0.0

### ISSUE THREAD

**Issue by 337077418** [jitsi/jitsi-meet#11561]
implementation ('org.jitsi.react:jitsi-meet-sdk:5.1.0') { transitive = true }
please help me

* What went wrong:
Execution failed for task ':skWeiChatBaidu:mergeDebugAssets'.
> Could not resolve all files for configuration ':skWeiChatBaidu:debugRuntimeClasspath'.
   > Could not find com.facebook.fresco:ui-common:2.0.0.
     Searched in the following locations:   
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://www.jitpack.io/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://developer.huawei.com/repo/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://maven.aliyun.com/repository/central/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://maven.aliyun.com/repository/google/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://maven.aliyun.com/repository/jcenter/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://maven.aliyun.com/nexus/content/groups/public/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://jitpack.io/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - file:/C:/Users/Administrator/Desktop/temp/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
       - https://repo.maven.apache.org/maven2/com/facebook/fresco/ui-common/2.0.0/ui-common-2.0.0.pom
     Required by:
         project :skWeiChatBaidu > project :meeting > org.jitsi.react:jitsi-meet-sdk:5.1.0 > com.facebook.react:react-native:0.68.1

**Comment by 337077418** [comment]
Required by:
         project :skWeiChatBaidu > project :meeting > org.jitsi.react:jitsi-meet-sdk:5.1.0 > com.facebook.react:react-native:0.68.1   

I use local Maven and online address, and both of these two methods will report the above errors

maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
//            url("file:C:\\Users\\Administrator\\Desktop\\temp")
        }

**Comment by 337077418** [comment]
I've tried many ways, and this always happens

Could not find com.facebook.fresco:ui-common:2.0.0.
Required by:
    project :skWeiChatBaidu > com.facebook.react:react-native:0.68.1

**Comment by saghul** [comment]
Do you have mavenCentral in your Gradle repos?

**Comment by 337077418** [comment]
Yes, here's mine Gradle 

buildscript {
    ext.kotlin_version = '1.5.0'
    ext {
        compile_version = 30
        min_version = 23
        target_version = 30
    }
    repositories {
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google/' }
        maven { url 'https://repo1.maven.org/maven2' }

        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
//        maven {
//            url 'http://maven.aliyun.com/nexus/content/repositories/releases/'
//        }
    }
    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core:1.6.0'
            force 'androidx.core:core-ktx:1.6.0'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
//        classpath 'com.android.tools.build:gradle:4.1.3'
//        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // 添加emas-services插件
//        classpath 'com.aliyun.ams:emas-services:1.0.1'
    }

}

allprojects {
    repositories {
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
//            url("file:C:\\Users\\Administrator\\Desktop\\temp")
        }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google/' }
        maven {
            url rootProject.file('repository')
        }
        //        maven { url "file:/tmp/repo" }
//        maven { url "file://C:/Users/Administrator/Desktop/jitsi_aar/repo" }
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
   }
}

**Comment by saghul** [comment]
The error says it also looked in jcenter, but you don't have it here. Did you update the file since?

**Comment by 337077418** [comment]
Sorry, it's CC Aoeiuv020: imaging: 1.0 conflicting relationships have been resolved

**Comment by MrLizhiguang** [comment]
hello  我也遇到  这个问题  请问你是怎么搞定的
