### ISSUE TITLE
Participant name hidden behind toolbar

### ISSUE THREAD

**Issue by ZettaScript** [jitsi/jitsi-meet#11566]
### Description:

In mosaic view, the participant names of the tiles at the bottom are not visible because of the toolbar. As there is no other obvious way to get the participant name, we have to change window size or switch off mosaic view.

### Steps to reproduce:

1. Join a meet with e.g. 4 or 9 participants.
2. Switch to mosaic view.

### Expected behavior:

There should be an easy way to see all the participants' names.

Solution ideas:
* Being able to move or reduce the toolbar
* Decrease the toolbar height or distance to viewport bottom
* Move the hidden participant name to another place so they are visible

### Actual behavior:

The bottom-right or bottom-center one has their name hidden behind the toolbar.

### Server information:

- Jitsi Meet server: https://jitsi.hadoly.fr/

### Client information:

- Browser / app version: Firefox 100.0.1
- Operating System: Archlinux, XFCE

**Comment by icekool** [comment]
Also an issue in Chrome. A simple solution might be to move the position of the participants name to the top-lefr

**Comment by saghul** [comment]
That would clash with the top bar.

**Comment by ZettaScript** [comment]
There is at least one way in plain HTML/CSS (using `float` for both names and toolbar, I think) so only the colliding elements will move.

**Comment by saghul** [comment]
This has been fixed. The oil at will now show a bit higher when there is a clash.
