### ISSUE TITLE
There is no way to access settings in the IOS app.

### ISSUE THREAD

**Issue by tarkowski** [jitsi/jitsi-meet#11564]
### Description:

There seems to be no way to access the settings in the IOS app.
This causes some serious problems for the user, for instance after hiding ones view there seems to be no way to bring it back (as it's in the settings).

### Steps to reproduce:

Not applicable.

### Expected behavior:

Settings should be available in the "three dot" menu.

### Actual behavior:

No settings

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
The settings are currently only accessible from the welcome page.

@robertpin Where did we put the "un-hide" self on mobile?

**Comment by robertpin** [comment]
I was sure there was a button in the meeting menu, but it's not there. I'll have a look and fix it today
