### ISSUE TITLE
giphy: cannot use space bar in giphy search (space closes the search window)

### ISSUE THREAD

**Issue by himpierre** [jitsi/jitsi-meet#11579]
### Description:

hello devs. i'm not able to use the space bar in giphy search. for instance when I try to search for "doc brown" the giphy search window closes when I hit space after entering doc.

### Steps to reproduce:

1. click reactions -> giphy
2. giphy search window opens
3. try to search for "doc brown"
4. after entering the space the search window closes

### Expected behavior:

I should be able to search for things containing a space

- Jitsi Meet version: 2.0.7287
- Operating System: Linux

### Client information:

- Browser / app version: firefox 100 / chrome 101
- Operating System: Linux

cheers, t.

**Comment by robertpin** [comment]
I'll have a look
