### ISSUE TITLE
Update pt-BR translation.

### ISSUE THREAD

**Issue by filhocf** [jitsi/jitsi-meet#1157]
Please, update the pt-BR translation. It already is finished.

**Comment by filhocf** [comment]
Hi

I found more some errors into translated interface without corresponding string into translate.jitsi.org site. Follow some screenshots.
![image](https://cloud.githubusercontent.com/assets/952596/21452512/80e60fda-c8ee-11e6-8fcd-501990a2451d.png)

![image](https://cloud.githubusercontent.com/assets/952596/21452569/ff86864e-c8ee-11e6-8670-1c1123046948.png)

**Comment by filhocf** [comment]
More one screen:

![image](https://cloud.githubusercontent.com/assets/952596/21453175/bf01976c-c8f3-11e6-9762-712541bbb76a.png)

**Comment by ibauersachs** [comment]
The templates in Pootle have been updated.

**Comment by filhocf** [comment]
Done.

**Comment by ibauersachs** [comment]
Committed from Pootle.
