### ISSUE TITLE
[iOS] [AudioMode] Cannot route audio output from one bluetooth device to other.

### ISSUE THREAD

**Issue by junaiddarajat** [jitsi/jitsi-meet#11576]
### Description:

When multiple bluetooth devices are connected, only the last connected bluetooth shall have audio output routed to it, even if you select the previous / other bluetooth device(s).

The same issue apparently exists on [iOS itself as asked here](https://developer.apple.com/forums/thread/62954).

### Steps to reproduce:

1. Open Jitsi Mobile App from your iPhone
2. Join any meeting, preferably one hosted at Laptop with their mic unmuted so you can test this.
3. Connect Bluetooth Device 'A', such as AirPods. The iPhone shall automatically route audio output to it.
4. Now, once verified that you can hear audio output on Device 'A', now connect Device 'B', let's say Sony MX4 Pods. The iPhone shall automatically route audio output to the newly connected Device 'B'.
5. Now, from the mobile app, on top right; tap on the 'Speaker' icon which opens Audio Device Selection prompt / bottom sheet.
6. Select Device 'A' from here.

### Expected behavior:

Audio should have been routed to the Device 'A'

### Actual behavior:

Audio remains routed to Device 'B', the last connected Bluetooth device.

### Server information:

[https://meet.jit.si]

### Client information:

- Browser / app version: 22.2.0 build 1652454796
- Operating System: iPhone 11, iOS 14.6

### Additional information:

Unsure if the same happens on Android or not, haven't tested it.

I tried debugging to see if AVAudioSession setPrefferedInput is returning false, but apparently it's also successful. However, just AFTER it if you log AVAudioSession currentRoute, it's still the last connected bluetooth device. I've tried changing categories, mode, setActive, etc, and their orders, to no avail, the same as the referred link about iOS issue on description.

**Comment by saghul** [comment]
If this is an iOS bug / limitation I'm not sure what we can do about it...

**Comment by saghul** [comment]
We don't use the system audio route picker, maybe that's why.

I'll be honest, it's the first time such a use case comes up, so I'll investigate when I get some spare cycles...
