### ISSUE TITLE
In Jitsi Meet when we are getting phone call in iPhone it's only showing End & Accept option. It also show Hold & Accept option.

### ISSUE THREAD

**Issue by pankajnegi1893** [jitsi/jitsi-meet#11578]
In iOS device when we are getting Phone call it's only displaying End & Accept option and meeting get End after that. It also display "Hold & Accept" options. like Other app display (Zoom).

![Skype_Picture_2022_05_24T13_14_32_120Z](https://user-images.githubusercontent.com/49673803/170043647-5adda0b5-0f2b-43b1-bc4d-ef2d9228200b.jpeg)

Is this feature there for iOS ?

Platform :- iOS

Thanks

**Comment by maksudur-rahman** [comment]
> In iOS device when we are getting Phone call it's only displaying End & Accept option and meeting get End after that. It also display "Hold & Accept" options. like Other app display (Zoom).
> 
> ![Skype_Picture_2022_05_24T13_14_32_120Z](https://user-images.githubusercontent.com/49673803/170043647-5adda0b5-0f2b-43b1-bc4d-ef2d9228200b.jpeg)
> 
> Is this feature there for iOS ?
> 
> Platform :- iOS
> 
> Thanks


Have you implemented this feature on your project, then how to do it ? please suggest me.

**Comment by saghul** [comment]
No we haven't.
