### ISSUE TITLE
Picture-in-Picture (PiP) is not working during screen sharing

### ISSUE THREAD

**Issue by amjidkhanmohmand** [jitsi/jitsi-meet#11577]
Hello team Jitsi!
Hopefully, you are doing well. I am facing a problem during screen sharing in a meeting. When I click the "screen sharing" option then there is not an option to call PIP mode unless and until I stop the screen sharing. To be more specific I am unable to navigate when I am sharing the screen, please have a look at this issue. I will be waiting for your response.

**Comment by saghul** [comment]
Is this on the mobile apps?

**Comment by amjidkhanmohmand** [comment]
I think it would be more effective if you add a button to minimize the activity

**Comment by amjidkhanmohmand** [comment]
Thanks for you help and support
