### ISSUE TITLE
Exception in firefox when joining meetings

### ISSUE THREAD

**Issue by justmax437** [jitsi/jitsi-meet#11581]
### Description:

In firefox, following a link to any meeting only shows jitsi meet UI for a second, than everything turns into plain gray screen.
On JS console there is an exception `2022-05-24T16:20:59.407Z [features/base/app] <componentDidCatch>:  TypeError: Ko.getStreamID is not a function`

Full stacktrace used to be [here](https://pastebin.com/EZs9qVCX). Pastebin seems to be broken. Every created paste is removed instantly.

### Steps to reproduce:

1. Start a meeting on some other device\browser. This reproduces on both self-hosted and meet.jit.si.
2. Open this meeting's link in firefox. I'm able to reproduce this with any recent version.
3. Check dev tools console.

### Expected behavior:

Meeting works as intended, prejoin page in displayed.

### Actual behavior:

Prejoin page UI flashes for a second, than whole screen turns gray, exception thrown in console.

### Server information:

- Jitsi Meet version: Selfhosted is dockerized 7210 release, meet.jit.si is latest, i think.
- Operating System: Debian 11.3

### Client information:

- Browser / app version: Firefox 95-100.0.2
- Operating System: Windows 11 (10.0.22000.556)

**Comment by saghul** [comment]
Are you able to reproduce this with Firefox 101 ?

**Comment by justmax437** [comment]
Yes

**Comment by saghul** [comment]
That's odd, I'm not.

Do you do any kind of UA spoofing?
