### ISSUE TITLE
AspectRatio Mobile App

### ISSUE THREAD

**Issue by David-CMC** [jitsi/jitsi-meet#11593]
### Steps to reproduce:

1. Open jitst meet
2. Join meetings from Desktop and Mobile and Website

### Expected behavior:

How to know what is platform website or desktop or mobile and the AspectRatio of it?

**Comment by David-CMC** [comment]
@saghul s
Can you help me?

**Comment by saghul** [comment]
Please use our community for such questions, we use GH for tracking bugs and features.

The stats for a participant will give you information about the resolution, so you can get the aspect ratio that way.
