### ISSUE TITLE
Adding breakout room with name from web/mobile app.

### ISSUE THREAD

**Issue by imuli** [jitsi/jitsi-meet#11599]
I'd evaluating jitsi as a informal meeting space. I'd like a low-friction way for members to be able split off and discuss a particular topic - and for other members to easily see what topic is being discussed.

As most people will be joining through the web app or mobile, this would mean adding breakout room names when they are created. Something like adding a text field to `AddBreakoutRoomButton` or `ParticiplantsPane` and plumbing its contents through to the `createBreakoutRoom` call.

Renaming breakout rooms would also be nice, but looks like a more involved change, and of course would be a different feature.

From the bug reports it looks like there are other clients that allow adding breakout room names, but I haven't found what they are yet.

(For the purposes of the CLA: Not a Contribution. However, this comment is released under [CC-0](https://creativecommons.org/publicdomain/zero/1.0/).)

**Comment by saghul** [comment]
We don't currently have the capability, but it is planned.Can't provide an ETA though, sorry.
