### ISSUE TITLE
[iOS] Picture-in-Picture (PiP): app freezes after dragging the view

### ISSUE THREAD

**Issue by robertogvieira** [jitsi/jitsi-meet#11597]
### Description:

When the call starts and view is displayed in PiP, after dragging the view around and finish dragging, the app freezes.
If there are other participants on the call (i.e. more than 1), the issue doesn't happen.

### Steps to reproduce:

- start the call;
(view is displayed in PiP from the start)
- drag the view around;
- stop dragging, "dropping" the view.

### Expected behavior:

- the call continues, with the view displaying the video feed;
- the view can be dragged again, changed to full size, etc;
- the app is responsive.

### Actual behavior:

- the video feed in the PiP view is stuck, displaying the same image (frame);
- the view cannot be dragged and is not responsive;
- the app is not responsive.

https://user-images.githubusercontent.com/7226114/171015049-d0424c8a-8e55-494a-a800-cee92823fe1b.mov

(after reaching the top-right, dragging ended and app just froze)

### Client information:

- Browser / app version: **_Jitsi SDK_** from **4.0.0** up to latest (**5.1.1** by the time I post this)
- Operating System: iOS

### Additional information:

- If there are more participants in the call, this issue doesn't happen;
- On version **3.8.1**, this issue doesn't happen in any case, so I'm discarding any Server-related issues.

**Comment by saghul** [comment]
Can you test 5.2.0-alpha.2? We landed some PiP fixes there.

**Comment by saghul** [comment]
Ping @alexbumbu

**Comment by saghul** [comment]
> Side-question: those PiP fixes made `initialPositionInSuperview` private; how can we change the initial position now? Or is that limitation part of the fix itself

That was probably unintentional.
