### ISSUE TITLE
After a successful build, the /tmp/repo directory could not be found.

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#11600]
Following the documentation, I am able to create my own SDK artifacts/binaries.

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk 

However, we are unable to identify /tmp/repo to use artifacts/binaries in our project after a successful build.
(./android/scripts/release-sdk.sh /tmp/repo)

 I am building on mac for android project.

please help me.

**Comment by saghul** [comment]
What URL did you put in the gradle file?

**Comment by vinayseasia** [comment]
if you are asking about maven url, I have these variables

   // Maven repo where artifacts will be published
    mavenRepo = System.env.MVN_REPO ?: ""
    mavenUser = System.env.MVN_USER ?: ""
    mavenPassword = System.env.MVN_PASSWORD ?: ""

**Comment by saghul** [comment]
No, I mean in your project, how are you using it?

**Comment by vinayseasia** [comment]
in my app gradle file :  api fileTree(include: ['*.aar'], dir: 'libs') 

and in libs foder I have "sdk-release.aar" file.

while building my app getting the exception:

com.facebook.react.modules.core.PermissionListener not found .........     which is used in JitsiMeetActivity.

**Comment by vinayseasia** [comment]
I am not able to locate /tmp/repo in jitsi-meet project. how I can add? please let me know the path where I can find that.

**Comment by saghul** [comment]
It's in your filesystem, the path is `/tmp/repo` since it starts with `/` you need to start at the root, it's not a relative path.

**Comment by vinayseasia** [comment]
why I cant build jisti-meet sdk with with different path means 

if I am changes ./android/scripts/release-sdk.sh /tmp/repo to ./android/scripts/release-sdk.sh /my/path I am not able to build artifacts.
