### ISSUE TITLE
Ongoing Meeting notification does not terminate.

### ISSUE THREAD

**Issue by selcukkpolat** [jitsi/jitsi-meet#11604]
### Description:

Ongoing Metting notification does not go away when internet is gone

### Steps to reproduce:

1. Connection JitsiCall
2. Internet connection is disconnected.
3. Notification continues

### Expected behavior:

The notification disappears when the internet is gone and the counter resets when jitsi call is installed again.

### Actual behavior:

JitsiCall terminates when internet connection goes down, but Ongoing Meeting notifications keep counting.

### Client information:

- Browser / app version: 
- Operating System: Android

**Comment by selcukkpolat** [comment]
Hi @tmoldovan8x8 ,
Device: Google Pixel 3
Api Version: 27
![image](https://user-images.githubusercontent.com/11459173/171645803-4bdc2556-9db4-4836-8dbb-39ae9e035208.png)

Although there is no internet, the session continues notification did not go away

**Comment by selcukkpolat** [comment]
Hi,
@tmoldovan8x8  @saghul 
Has any improvement been made on this issue?
I'm waiting for your answer

**Comment by saghul** [comment]
Yes we have a PR ready over at: https://github.com/jitsi/jitsi-meet/pull/11642

Should land next week.

**Comment by selcukkpolat** [comment]
hello,
 when I apply this solution, the ongoing-meeting notification remains after the internet connection is lost.

**Comment by saghul** [comment]
Actually I mixed up 2 PRS, the one I linked is unrelated.

**Comment by selcukkpolat** [comment]
buildOngoingConferenceNotification() 
The situation was resolved when I added a listener that listens to the internet status.

`        ConnectivityManager conMgr = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);

        if (conMgr.getActiveNetworkInfo() != null) {
            if (startingTime == 0) {
                startingTime = System.currentTimeMillis();
            }
            builder
                .setCategory(NotificationCompat.CATEGORY_CALL)
                .setContentTitle(context.getString(R.string.ongoing_notification_title))
                .setContentText(context.getString(R.string.ongoing_notification_text))
                .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                .setContentIntent(pendingIntent)
                .setOngoing(true)
                .setWhen(startingTime)
                .setUsesChronometer(true)
                .setAutoCancel(false)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                .setOnlyAlertOnce(true)
                .setSmallIcon(context.getResources().getIdentifier("ic_notification_jitsi", "drawable", context.getPackageName()));
            NotificationCompat.Action hangupAction = createAction(context, JitsiMeetOngoingConferenceService.Action.HANGUP, R.string.ongoing_notification_action_hang_up);

            JitsiMeetOngoingConferenceService.Action toggleAudioAction = isMuted
                ? JitsiMeetOngoingConferenceService.Action.UNMUTE : JitsiMeetOngoingConferenceService.Action.MUTE;
            int toggleAudioTitle = isMuted ? R.string.ongoing_notification_action_unmute : R.string.ongoing_notification_action_mute;
            NotificationCompat.Action audioAction = createAction(context, toggleAudioAction, toggleAudioTitle);

            builder.addAction(hangupAction);
            builder.addAction(audioAction);

            return builder.build();
        }
        resetStartingtime();
        return null;`

**Comment by saghul** [comment]
I don't think that'd a good idea. The disconnection might be transient and you might be able to recover.

**Comment by tmoldovan8x8** [comment]
@selcukkpolat yeah, the current flow takes into consideration that the failure might be temporary and after 10 secs or something, when the conference actually fails for real, we send the specific events that hide the notification.

**Comment by saghul** [comment]
Maybe we need a fail safe in case the activity is swiped s way, without the chance for a proper termination?
