### ISSUE TITLE
Problem using IP address to join Jitsi-Meet chat via Android App

### ISSUE THREAD

**Issue by wxie2017** [jitsi/jitsi-meet#11605]
### Description:

when entering IP address in the meeting bar from Jitis-meet APP from F-Droid:

xxx.xxx.xxx.xxx/test
User cannot join the meeting

### Steps to reproduce:

1. Open 'JItis meet from android phone APP' 
2. enter meeting IP 'xxx.xxx.xxx.xxx/test' 
3. start joining

### Expected behavior:

user should be able to join the meeting, and start the meeting

### Actual behavior:

User stays in joining page or the APP stops.

### Server information:

- Jitsi Meet version: latest
- Operating System: GNU/Linux

### Client information:

- Browser / app version: 22.2.0
- Operating System: android 11/lineage 18.1

### Additional information:

This also happened with other phones from other meeting takers. 
Joining from browser (Firefox or other) is working using IP address.

**Comment by saghul** [comment]
The apps do not work with invalid TLS certificates. You need to have a real domain with a real cert.

**Comment by wxie2017** [comment]
Thanks.
1. why ip is working for web login?
2. ip without domain can also have real cer, so this should not be a problem. Right?

**Comment by damencho** [comment]
> 2\. ip without domain can also have real cer, so this should not be a problem. Right?

Yes, iif you have a valid certificate it will work.

> 1. why ip is working for web login?

Cause the browser allows you to skip the cert verification step, while this is a limitation and cannot be skipped on mobile.
