### ISSUE TITLE
jitsi-meet artifact not compiling with our android app

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#11606]
**jitsi-meet sdk uses** 

compileSdkVersion = 31
minSdkVersion        = 23
targetSdkVersion    = 31
jdk                            = 11

**our android app uses**

compileSdkVersion = 30
minSdkVersion        = 23
targetSdkVersion    = 30
jdk                            = 1.8

As a result of the aforesaid version mismatch, jitsi-meet SDK artifacts/binaries are not compiling with our android app.

so can I compile jitsi-meet with **sdk version 30 and jdk 1.8** ? 

- Jitsi Meet version: 5.0.0
- Operating System: Mac

**Comment by saghul** [comment]
Our SDK requires a Java 11 compiler.

Also, why can't you raise the target SDK to 31? We tend to target the latest while maintaining the minimum at 23, you should be able to do the same.

**Comment by vinayseasia** [comment]
ok, thank you
