### ISSUE TITLE
Cannot type in the chat box.

### ISSUE THREAD

**Issue by karta2155802** [jitsi/jitsi-meet#11613]
### Description:

When the web size is small in a certain range, lobby function is activated, and people try to chat with someone in lobby, the one in lobby cannot type in chat box.

### Steps to reproduce:
Condition: web size is small in some certain range
1. User1 enters a room
2. User1 enables lobby option
3. User2 tries to enter the same room and waits in lobby
4. User1 chats with user2 in lobby
5. User2 cannot type in chat box

https://user-images.githubusercontent.com/41221410/171823568-4c9c80bf-b4bf-4c18-8328-1449c15e5f61.mp4

### Expected behavior:
People in lobby should be able to type in chat box.

### Actual behavior:
People in lobby cannot type in chat box.

### Client information:

- Browser / app version: Chrome: 102.0.5005.63
- Operating System: Windows10

**Comment by saghul** [comment]
What size triggers this problem?

**Comment by karta2155802** [comment]
![image](https://user-images.githubusercontent.com/41221410/171902221-d85199d4-b391-44e6-9a2a-9759159ea108.png)
![image](https://user-images.githubusercontent.com/41221410/171900658-b6212a11-4e7a-4191-b7d8-8290ea7a6cb2.png)
The chat box in the lobby will change from a box(top image) to a button(buttom image) if the width of page size is smaller than 1000px. In this situation, the problem occurs.

**Comment by saghul** [comment]
IIRC we fixed something along these lines recently. Can you please test on alpha.jitsi.net?

**Comment by karta2155802** [comment]
It seems the bug has been fixed. Thank you.
