### ISSUE TITLE
automatic subject tracking is unsteady with multiple subjects on one camera, cannot be disabled

### ISSUE THREAD

**Issue by mutualaidwork** [jitsi/jitsi-meet#11619]
### Description:

When there are multiple participants within view on a single camera/panel, and the panel is square, or tall and narrow, the automatic face/subject tracking fails, and moves back and forth unsteadily, and makes some users sick

### Steps to reproduce:

Have a number of connections and window aspect ratio which causes the panels to be near-square or narrow width, and have one of the near-square or narrow connections feature multiple people within camera view

### Expected behavior:

subject-tracking view panning doesn't make people sick

### Actual behavior:

subject-tracking view panning makes people sick from moving back and forth

### Server information:

current meet.jit.si web client

### Client information:

current meet.jit.si web client
various operating systems

### Additional information:

Please include an option in the settings to force native aspect ratio on the panels, to turn off subject tracking, or give the user control over view panning in their own clients

**Comment by saghul** [comment]
Thanks for the feedback.
