### ISSUE TITLE
version 7287 - feat GIPHY integration leads to loading woff2 font files from third party (aws) - CSP is required to block the requests - again

### ISSUE THREAD

**Issue by amsnek** [jitsi/jitsi-meet#11611]
Description:
Since version 7210 / 7287 the resuling build attempts to load woff2 fonts from amazonaws. It is blocked by CSP settings, but this shouldnt happen.

My previous Issue: https://github.com/jitsi/jitsi-meet/issues/11419 -> was closed and fixed -> waited for next release but it seems the issue still happens (again?)

Fixed in https://github.com/jitsi/jitsi-meet/pull/11457  -> but seems to happen again

Its probably related to these errors i get when building?

````
> [jitsi-meet@0.0.0](mailto:jitsi-meet@0.0.0) postinstall
> patch-package && jetify

patch-package 6.4.7
Applying patches...
[eslint-plugin-flowtype@8.0.3](mailto:eslint-plugin-flowtype@8.0.3) ✔
[react-native@0.68.1](mailto:react-native@0.68.1) ✔
[react-native-dialog@9.2.1](mailto:react-native-dialog@9.2.1) ✔
[react-native-gesture-handler@2.1.0](mailto:react-native-gesture-handler@2.1.0) ✔

**ERROR** Failed to apply patch for package @giphy/js-analytics at path

    node_modules/@giphy/js-analytics

  This error was caused because @giphy/js-analytics has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run

    patch-package @giphy/js-analytics

  Info:
    Patch file: [patches/@giphy+js-analytics+4.0.7.patch](mailto:patches/@giphy+js-analytics+4.0.7.patch)
    Patch was made for version: 4.0.7
    Installed version: 4.1.0


**ERROR** Failed to apply patch for package @giphy/js-brand at path

    node_modules/@giphy/js-brand

  This error was caused because @giphy/js-brand has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run

    patch-package @giphy/js-brand

  Info:
    Patch file: [patches/@giphy+js-brand+2.0.4.patch](mailto:patches/@giphy+js-brand+2.0.4.patch)
    Patch was made for version: 2.0.4
    Installed version: 2.1.0

---
patch-package finished with 2 error(s).

````

https://s3.amazonaws.com/giphyscripts/react-giphy-brand/fonts/InterFace_W_Rg.woff2
https://s3.amazonaws.com/giphyscripts/react-giphy-brand/fonts/InterFace_W_Rg.woff
...

Steps to reproduce:
Open the meet site with the build in question, Loading welcome page suffices
Expected behavior:
No attempts to load fonts or files from third party sites.

Actual behavior:
attempts to load .woff/.woff2 fonts from aws

Server information:
Jitsi Meet version: 7287
Operating System: Linux
Client information:
Operating System: Linux

**Comment by saghul** [comment]
Hum the build should have failed so we can catch these. I'll take another look, thanks for the report.

**Comment by amsnek** [comment]
> > Patch was made for version: 4.0.7
> > Installed version: 4.1.0
> 
> Did you run npm update yourself? Our depedency is pinned to 4.0.7 (see package-lock.json) so you must have made changes that resulted in an update.
> 
> I have however created #11612 just a safety net so the patch process always fails if they cannot be applied.

Yes, I did run npm update within my build script (which I usually do 🙈) -> so that has been the culprit. Will remove that step and try again. 

Thank you for looking into it and the new safety net, into which I would have run next 👍

**Comment by saghul** [comment]
As a general rule, running npm update yourself is a terrible idea. You are running package versions we have not tested.

**Comment by amsnek** [comment]
> As a general rule, running npm update yourself is a terrible idea. You are running package versions we have not tested.

That is very good to know! Thanks, removing that step right now 👍

**Comment by zhouhao27** [comment]
When I tried to build iOS framework, I got this error. What is the fix?
