### ISSUE TITLE
Unable to Join Meeting with Prosody Reservations on Docker

### ISSUE THREAD

**Issue by Mahdhir** [jitsi/jitsi-meet#11623]
### Steps to reproduce:

1. set PROSODY_RESERVATION_ENABLED=true in .env
2. set PROSODY_RESERVATION_REST_BASE_URL=`<your-reservations-api-url>`
3. Join meeting on hosted jitsi server

### Expected behavior:

Join Call as usual. Reservation API should be hit with calls from Jitsi Server.

### Actual behavior:

When Join Meeting button is clicked, nothing happens on the UI. When checking the prosody logs, the error given is, 
```
c2saaabf9af8e30                                              error      Traceback[c2s]: /prosody-plugins/mod_reservations.lua:349: attempt to concatenate a table value (upvalue 'api_prefix')
        stack traceback:
        /prosody-plugins/mod_reservations.lua:349: in method 'call_api_create_conference'
        /prosody-plugins/mod_reservations.lua:239: in method 'enqueue_or_route_event'
        /prosody-plugins/mod_reservations.lua:559: in field '?'
        /usr/share/lua/5.4/prosody/util/events.lua:81: in function </usr/share/lua/5.4/prosody/util/events.lua:77>
        (...tail calls...)
        /usr/share/lua/5.4/prosody/core/stanza_router.lua:184: in upvalue 'core_post_stanza'
        /usr/share/lua/5.4/prosody/core/stanza_router.lua:128: in upvalue 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:326: in upvalue 'func'
        /usr/share/lua/5.4/prosody/util/async.lua:144: in function </usr/share/lua/5.4/prosody/util/async.lua:142>
```

![image](https://user-images.githubusercontent.com/37553533/172122412-0fc1364f-9d2b-467d-a02e-1b08ced1879e.png)

### Server information:

- Jitsi Meet version: Jitsi Docker Master
- Operating System: Oracle Linux 8

### Client information:

- Browser / app version: Chrome
- Operating System: Windows 10

**Comment by shawnchin** [comment]
Looks like a bug in the docker setup. See https://github.com/jitsi/docker-jitsi-meet/pull/1301/files#r889947361
