### ISSUE TITLE
Notification offers to mute, while it's already muted

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#11638]
### Description:
![image](https://user-images.githubusercontent.com/14617699/172507981-0c398346-f858-443d-9d24-dc548c688cea.png)

### Steps to reproduce:

1. Set `Start with audio muted`
2. Join a room

### Client information:

22.2.0 build 222000 from fdroid, lineage+microG 18.1 on android 11

**Comment by saghul** [comment]
@tmoldovan8x8 for when you get a chance.

**Comment by AFZL210** [comment]
can I work on this? is this issue still active?

**Comment by saghul** [comment]
Oh, this is actually already fixed on the latest release :-)
