### ISSUE TITLE
Urgent issue with JitsiMeetSDK to distribute App in app store

### ISSUE THREAD

**Issue by drottemberg** [jitsi/jitsi-meet#11632]
### Description:

Apple just made some changes in the way to verify apps. 
I never had any issues when using it before and suddenly it happened.

### Steps to reproduce:

Distribute app wit JitsiMeetSDK

### Expected behavior:

All good

### Actual behavior:

The app references non-public selectors in Payload/App.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK: estimatedProgress, evaluateScript:, initWithFrame:configuration:, isMainFrame, isPassthrough, navigationType, onSuccess:, removeValuesForKeys:completion:, setNavigationDelegate:, setProcessPool:, showLoading, targetFrame, userContentController, websiteDataStore With error code STATE_ERROR.VALIDATION_ERROR.50 for id 8e37a28d-2947-4056-9434-517d84f568cf –

**Comment by ppanuwatpr** [comment]
I also got the similar problem. It just suddenly happened when I try to distribute my app this morning.

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by TangXT** [comment]
I got the same problem

**Comment by saghul** [comment]
Same question: what SDK version are you using?

**Comment by saghul** [comment]
We have not received such problem when submitting to the store ourselves. Not sure what you can do. I'd suggest contacting support.

**Comment by saghul** [comment]
Glad to hear!

**Comment by chandananand** [comment]
How to hide this close button? Are there any Feature flags for this to hide?

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-03 at 17 03 43](https://user-images.githubusercontent.com/12099699/216593943-cebd801e-f836-49e1-9698-16e5e4d2421d.png)
