### ISSUE TITLE
APP in interface-config.js take no effect

### ISSUE THREAD

**Issue by DmitruMoth** [jitsi/jitsi-meet#11639]
### Description:

Hello, i want to change application name in welcome page, now there is default "Сервер видеоконференцсвязи". I want to see "Test VKS". I set APP in interface-config.js, but is takes no effect. I tried change other properties, they all works. How can i change it?

**Comment by saghul** [comment]
Are you trying to change it in your own server? Where do you still see the default value?

**Comment by DmitruMoth** [comment]
> Are you trying to change it in your own server? Where do you still see the default value?

Im trying it on my own server. line from main-ru.json: `"headerTitle": "...... {{app}}",`
I set `APP` and `app` in interfaceConfig.js - there is no app name.
In the browser console i can see app name by running interfaceConfig.app

**Comment by saghul** [comment]
Looks like we messed up that parameter: https://github.com/jitsi/jitsi-meet/blame/aee94ad6fb78a02ae0ec4c5ca18e98c8450bc5cb/lang/main.json#L1295 you cannot change it now. A PR fixing that would be welcome.

**Comment by DmitruMoth** [comment]
> Looks like we messed up that parameter: https://github.com/jitsi/jitsi-meet/blame/aee94ad6fb78a02ae0ec4c5ca18e98c8450bc5cb/lang/main.json#L1295 you cannot change it now. A PR fixing that would be welcome.

I want to change the {{app}} variable, how can i do it?

**Comment by osiktech** [comment]
@saghul could you elaborate what could have messed this up. look at the linked git blame, it was just sorting and therefore standardise the language json files?

How could this break this? 

> Looks like we messed up that parameter: https://github.com/jitsi/jitsi-meet/blame/aee94ad6fb78a02ae0ec4c5ca18e98c8450bc5cb/lang/main.json#L1295 you cannot change it now. A PR fixing that would be welcome.

Thanks in advance.
