### ISSUE TITLE
Safari 16 sends low definition video in two participant call, possibly P2P, possibly not

### ISSUE THREAD

**Issue by kode54** [jitsi/jitsi-meet#11640]
### Description:

When using Jitsi Meet self install to place a call between two users, one running Microsoft Edge for macOS, and one running Safari 16 on macOS Ventura beta, the video quality sent by the Safari system is 180p.

### Steps to reproduce:

1. Open Jitsi Meet on a macOS Monterey or other system, running Microsoft Edge
2. Open the same call on a macOS Ventura system in Safari 16.
3. Observe the call quality.

### Expected behavior:

I expect the same 1080p call stream as I see when using Edge to Edge calls.

### Actual behavior:

Instead, the Safari browser sends a 180p video stream to the other end. The other end sends full 1080p quality back.

### Server information:

- Jitsi Meet version: 2.0.7287-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Safari 16.0 (18614.1.14.1.15)
- Operating System: macOS 13.0 Beta (22A5266r)

Other client:

- Browser / app version: Microsoft Edge 102.0.1245.33 (arm64)
- Operating System: macOS 12.4

### Additional information:

This is testing on the initial developer beta of macOS Ventura. I haven't tested if this also affects Safari 15 under Monterey. Or whether it's specific to the M1 Mac mini I'm running it on.

**Comment by saghul** [comment]
Can you check your browser console JS logs? Any errors there? Specifically bridge channel errors, that would explain.

**Comment by kode54** [comment]
I'll attempt to run the tests again during the daytime hours and report back here.

**Comment by kode54** [comment]
It does show some network cost status, but unfortunately, the entire console log is cleared the moment I leave the call. I'll try again later.

I just noticed, though, that the incoming video was terrible as well.

**Comment by saghul** [comment]
There should be a check in the console window for "preserve logs" that should avoid clearing the console.

**Comment by kode54** [comment]
It may have been a cached service worker from when the server was configured to constrain video bitrate to 200kbps. Server is also configured to prefer H.264.

**Comment by saghul** [comment]
Well you can't to HD video at 200kbps, that's for sure.

We can't do simulcast on H264 and generally speaking H264 is not something we test extensively, I'd recommend you test with the default configuration.
