### ISSUE TITLE
[iOS] the app freezes on iphone XR,iphone13, iPad 

### ISSUE THREAD

**Issue by erasingla20** [jitsi/jitsi-meet#11649]
### Description:

The iOS app periodically freezes when in video conference with 4 or more participants and camera on All the participants.

### Steps to reproduce:

Go to the video conference on ihone/ipad, the camera should be on for all participants then app freeze 

### Expected behavior:

Go to Video Conference & particiapnt joined.

### Server information:

- Jitsi Meet version:6726
![Skype_Picture_2022_06_09T06_01_47_684Z](https://user-images.githubusercontent.com/107169666/172775525-07ae6129-dcbe-4070-b4cb-8bd39154a0ed.jpeg)

Thanks

**Comment by saghul** [comment]
What app version are you using?

I see you are using a custom deployment, can you reproduce the issue with meet.jit.si ?
