### ISSUE TITLE
Flip doesn't flip two video correctly

### ISSUE THREAD

**Issue by linsui** [jitsi/jitsi-meet#11652]
### Description:

In browser there is two video, one in the sidebar and one is the main view. When I flip it the first time, only one is flipped. Then they are always in the different orientation.

### Steps to reproduce:

1. Open a video meet.
2. Flip
3. 

### Expected behavior:

The two video view should both be flipped at the same time.

### Actual behavior:

The first time only one is flipped.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Firefox 101
- Operating System: Linux

**Comment by saghul** [comment]
Video flipping only applies to the local view, remote views are not flipped.

**Comment by saghul** [comment]
Right. That's because you are alone. Flipping the video only affects the way you see yourself (top right) not how your video is sent to the remote end.

**Comment by saghul** [comment]
Because it's your own local view too. Check with another participant.

**Comment by linsui** [comment]
Yes, I checked with another participant.

**Comment by shawnchin** [comment]
I can repro the issue. When viewing yourself in stage view, if you keep flipping, your self view on stage flips too except it is always in opposite direction of what's in the filmstrip.

https://user-images.githubusercontent.com/348157/173022022-4bb0c26b-7f02-4bbc-87cb-d6876d15f675.mov

This happens both when you're only user in room, as well as in multi-party sessions.
