### ISSUE TITLE
[iOS] PiP option not available on call as the call initiator.

### ISSUE THREAD

**Issue by chrismcclune** [jitsi/jitsi-meet#11650]
### Description:

When having the 'pip.enabled' feature flag enabled, as a caller I do not see the option to enter PiP. As a call receiver I do see the option.

### Steps to reproduce:

1. Make a call
2. Top left where the option to enter PiP should be next to the call timer. The option is missing.
3. As a call receiver the option appears.

### Expected behavior:

The ability to enter PiP should be present for both the call initiator and other participants.

### Actual behavior:

PiP option is only available to call receivers.

### Server information:

- Jitsi Meet version: 2.0.7287
- Operating System: iOS

### Client information:

- Browser / app version: N/A
- Operating System: iOS 14.7.1

### Additional information:

N/A

**Comment by saghul** [comment]
On iOS the only requirements for the icon to be visible are the flag and the delegate method being implemented. Are both of this satisfied?

**Comment by chrismcclune** [comment]
Yes exitPictureInPicture is being implemented. It is working for the receiver. Could this be something to do with the isLocalVideoTrackDesktop flag that I can see being checked?

**Comment by saghul** [comment]
Ah correct. PiP is explicitly disabled when screen sharing.

**Comment by saghul** [comment]
Is the initiator sharing their screen?

**Comment by chrismcclune** [comment]
No screen sharing in progress. I do not even have it enabled for iOS to iOS. Desktop has it enabled and the same missing PiP happens.

**Comment by saghul** [comment]
Very odd. What SDK version are you using? Can you try the latest in cocoapods?

**Comment by chrismcclune** [comment]
Using 5.1.0 from the latest release.

**Comment by saghul** [comment]
Hum, I honestly see no problem. There is no real difference between an initiator or the other party, they both join the meeting the same way from Jitsi's perspective.

Do you have separate options for them in your app?

**Comment by chrismcclune** [comment]
It is confusing for sure as the logic seems simple. I don't have any other options set. Only thing I can think of is that the flag 'isLocalVideoTrackDesktop' is not returning the expected value.

**Comment by chrismcclune** [comment]
When you test this your end, is it working as expected and showing for both the creator and joiner?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/ios/swift

**Comment by chrismcclune** [comment]
Strange one, but I have it sorted now. Having a different object being responsible for the PiP Coordinator has fixed it. Not sure why, but there you go. Thanks for your time.
