### ISSUE TITLE
Problem with scrolling the audio settings

### ISSUE THREAD

**Issue by brknapik** [jitsi/jitsi-meet#11656]
### Description:

Hi,

The problem concerns the display of microphone and video settings in the jitsi welcome menu before entering the conference. It does not support scrolling, which means that sometimes there is a problem with checking all available options for selecting a device.

### Steps to reproduce:

1. Create a conference and go to the perjoin site
2. Click on Audio settings
3. Minimize the page window
4. Reducing / enlarging the page size is not customized with settings dialog

### Expected behavior:

The ability to adapt the application window to the settings dialog eg. using the scrollbar

### Actual behavior:

No possibility to control windows when changing the application window.

### Server information:

- Jitsi Meet version: stable-7287 (Docker)
- Operating System: CentOS Linux 7

### Client information:

- Browser / app version: Version 102.0.5005.63 / Rocket.Chat Electron with Jitsi plugin (3.8.4)
- Operating System: Windows10

**Comment by saghul** [comment]
Can you share a screenshot please?

**Comment by brknapik** [comment]
In this case, I have access to 3 microphone settings, while reducing the screen I am not able to see the other options.
![image](https://user-images.githubusercontent.com/93321802/173047844-025f7a4e-d49a-48f7-a9ce-943eef393c88.png)

**Comment by saghul** [comment]
How small are you making it? We don't really support very small sizes well.

**Comment by brknapik** [comment]
Like 748px x 580px
![image](https://user-images.githubusercontent.com/93321802/173053443-4d916c99-f62c-4d08-aaa5-59d488b0dddf.png)

**Comment by saghul** [comment]
A PR would be welcome, but I'd say this control is not optimized for such small sizes.

**Comment by saghul** [comment]
The names now scroll on hover.
