### ISSUE TITLE
FF Screen sharing without the plugin

### ISSUE THREAD

**Issue by ChrisRatty** [jitsi/jitsi-meet#1165]
I saw that it's possible to use screen sharing feature without the jidesha plugin on meet.jit.si.
I'm unable to do it on my own jitsi meet server. Whenever i try to use screen sharing i get "Failed to install desktop sharing extension".

Console logs:

[modules/RTC/RTCUtils.js] <y/<>:  failed to obtain desktop stream - stop gum.general: The request is not allowed by the user agent or the platform in the current context.
Stack trace:
t@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:1:26883
Y.getUserMediaWithConstraints/<@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:29634
p@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:24216
h/</<@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:24404
h/<@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:24273
Y.getUserMediaWithConstraints@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:29474
o@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:22:4832
k.obtainScreenOnFirefox@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:22:9309
y@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:24960
Y.obtainAudioAndVideoPermissions/<@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:30293
_@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:41:27957
Y.obtainAudioAndVideoPermissions@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:29849
a.obtainAudioAndVideoPermissions@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:2:5099
j.createLocalTracks@https://jitsi01.example.local/libs/lib-jitsi-meet.min.js?v=1338:1:2421
h@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:37:4835
t.default.toggleScreenSharing@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:37:16461
i.prototype.emit@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:14:27953
g.toolbar_button_desktopsharing@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:15:3222
b.init/</<@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:15:8795
ae.event.dispatch@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:87:14740
ae.event.add/m.handle@https://jitsi01.example.local/libs/app.bundle.min.js?v=1338:87:11520

**Comment by bgrozev** [comment]
You didn't describe your configuration: did you configure jitsi-meet to not require an extension (desktopSharingFirefoxMaxVersionExtRequired=0) and did you manually add you domain to firefox's whitelist?

**Comment by ChrisRatty** [comment]
I use same configuration as meet.jit.si, so yes desktopSharingFirefoxMaxVersionExtRequired=0.
What do you mean by "manually add you domain to firefox's whitelist"?

**Comment by ChrisRatty** [comment]
Config file:

var config = {
    hosts: {
        domain: 'jitsi01.example.local',

        muc: 'conference.jitsi01.example.local', // FIXME: use XEP-0030
        focus: 'focus.jitsi01.example.local',
    },
    disableSimulcast: false,
    resolution: 1080,
    useStunTurn: false, // use XEP-0215 to fetch STUN and TURN server
    useIPv6: false, // ipv6 support. use at your own risk
    useNicks: false,
    bosh: '//jitsi01.example.local/http-bind', // FIXME: use xep-0156 for that
    //desktopSharing: 'ext', // Desktop sharing method. Can be set to 'ext', 'webrtc' or false to disable.
    chromeExtensionId: 'diibjkoicjeejcmhdnailmkgecihlobk', // Id of desktop streamer Chrome extension
    desktopSharingSources: ['screen', 'window'],
    minChromeExtVersion: '0.1.3', // Required version of Chrome extension
    desktopSharingFirefoxExtId: "",
    desktopSharingFirefoxDisabled: false,
    desktopSharingFirefoxMaxVersionExtRequired: 0,
    desktopSharingFirefoxExtensionURL: "",
    useRoomAsSharedDocumentName: false,
    enableRtpStats: false, // Enables RTP stats processing
    openSctp: true, // Toggle to enable/disable SCTP channels
    channelLastN: -1, // The default value of the channel attribute last-n.
    minHDHeight: 540,
    startBitrate: "800",
    adaptiveLastN: false,
    disableAudioLevels: false,
    useRtcpMux: true,
    useBundle: true,
    disableAdaptiveSimulcast: true,
    enableLipSync: true,
    stereo: false,
    enableTalkWhileMuted: true,


    hiddenDomain: 'recorder.meet.jit.si',
    enableRecording: true,
    requireDisplayName: false,
    recordingType: 'jibri',
    enableWelcomePage: true,
    isBrand: false,
    logStats: false,

    startAudioMuted: 9,
    startVideoMuted: 9,
    enableUserRolesBasedOnToken: false,
};

**Comment by bgrozev** [comment]
> I use same configuration as meet.jit.si, so yes desktopSharingFirefoxMaxVersionExtRequired=0.
> What do you mean by "manually add you domain to firefox's whitelist"?

In order for screensharing to work, the domain has to be in the whitelist. This can happen in one of three ways:
Be in the list distributed by firefox (like meet.jit.si)
Use an extension to add it (jidesha)
Add it manually (media.getusermedia.screensharing.allowed_domains)

**Comment by ChrisRatty** [comment]
That worked :), Thank you very much!
