### ISSUE TITLE
Display name is HTML encoded if set via userInfo

### ISSUE THREAD

**Issue by robintown** [jitsi/jitsi-meet#11664]
### Description:

If you use the userInfo parameter of the iframe API to set a display name, what you actually see in the app is the HTML-encoding of that name.

### Steps to reproduce:

1. Start a conference via the iframe API with a `userInfo` parameter of `{ displayName: "Robin ('robintown')" }`
2. Look at the display name on your video tile

### Expected behavior:

![Screenshot 2022-06-10 at 11-46-54 Element Robin's video room 1](https://user-images.githubusercontent.com/48614497/173103068-12328560-a7a2-4db4-b2b9-d1ac92a4eae3.png)

### Actual behavior:

![Screenshot 2022-06-10 at 11-47-16 Element Robin's video room 1](https://user-images.githubusercontent.com/48614497/173103114-8093099d-0acb-4e0e-b708-e527462b0d32.png)

### Server information:

- Jitsi Meet version: 10.06155
- Operating System: NixOS unstable

### Client information:

- Browser / app version: Firefox 100.0.2
- Operating System: NixOS unstable

**Comment by MAX-786** [comment]
Hello, if this issue is still up and no one is working on it can you assign it to me?

**Comment by sudhanshu154** [comment]
I waana contribute in this issue

**Comment by abhijeet-26** [comment]
I would like to work on it.

**Comment by robintown** [comment]
This issue is still relevant

**Comment by IshaanDasgupta** [comment]
Hi, I was trying to re-create the bug but, I am not able to

**Comment by robintown** [comment]
I am referring to this API: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe/#creating-the-jitsi-meet-api-object That section of the page also contains an example of setting the display name via userInfo.

**Comment by robintown** [comment]
Still relevant

**Comment by kozubp** [comment]
I am facing similar issue, also when using External Api Iframe.
`userInfo: {
     displayName: 'user "alias" name'
}`
When user displayName contains quitations marks, prejoin page loads with character replaces as &quot; and displays incorrecly later if user doesn't correct it. 
Problem also occurs for: ' (&#39;) & (&amp;) < (&lt;) > (&gt;)
It seems it's not properly parsed/decoded when setting name input field.
