### ISSUE TITLE
error=conference.connectionError.notAllowed

### ISSUE THREAD

**Issue by webtecsoteam** [jitsi/jitsi-meet#11665]
I am using jitsi_meet_wrapper 0.0.5 flutter plugin, when i am going to join a room its giving error

I/JitsiMeetSDK(12949): Conference terminated: {error=conference.connectionError.notAllowed, url=https://8x8.vc/vpaas-magic-cookie-dc8bab739d084ce2977cd9e87531778c/ZakariyaAwanPrivateLesson-23}

and this error also

W/JitsiMeetSDK(12949): [JitsiConference.js] Failed to set subject, not in a room, participant is not a moderator

can you please let me know how i can fix this please ?

**Comment by saghul** [comment]
We are not the maintainers of the flutter plugin. Does it allow you to set the JWT?

**Comment by webtecsoteam** [comment]
Yes i am generating JWT from server and set in function..

**Comment by saghul** [comment]
Can you please share the code snippet of how you are trying to connect?

**Comment by webtecsoteam** [comment]
var options = JitsiMeetingOptions(
      roomNameOrUrl: "https://8x8.vc/vpaas-magic-cookie-<Our tenant ID>/test-5",
      serverUrl: "https://8x8.vc",
      subject: "Test",
      token: token,
      userDisplayName: "Pulkit",
      isAudioMuted: true,
      isVideoMuted: true,
    );
    await JitsiMeetWrapper.joinMeeting(options: options);


so in token field, firstly i am generating JWT from server and pass in this function..

**Comment by webtecsoteam** [comment]
roomNameOrUrl: "https://8x8.vc/vpaas-magic-cookie-xxx/test-5",

in place of xxx i am putting our api ID which we already register in jaas portal..

**Comment by saghul** [comment]
Does your token allow joining that room? Any chance it's expired?

**Comment by webtecsoteam** [comment]
the token working very well in PHP application, but not with this flutter application, and i am joining the meeting in 1 minute after token generate, so its not expired

**Comment by thisisnkc** [comment]
Hey @webtecsoteam, is the problem solved ?

**Comment by radwanhossain** [comment]
@saghul Is the problem solved ? I am facing same issue

**Comment by saghul** [comment]
Yes it's solved. We have published an official flutter plugin which uses the latest SDK.

**Comment by dlievanoC** [comment]
How did I resolve it, I have the same problem.
