### ISSUE TITLE
Give me the option to control my own mic's volume instead of Jitsi automatically controlling it for me.

### ISSUE THREAD

**Issue by monstro1** [jitsi/jitsi-meet#11668]
Jitsi automatically lowers my microphone volume when it erroneously thinks I'm being loud. I don't want my microphone's volume to be lowered. If I want the volume to be lower, I will lower it myself. No other voice chat app does this.

**Comment by saghul** [comment]
It's not possible for web apps to control the mic input gain. What you see is a result of the builtin Acoustic Gain Control kicking in.

Can you please give us some details about the call you were having? How many participants, who was wearing a headset and who was experiencing the problem.

**Comment by monstro1** [comment]
Was in a call with about 3 other people. One of them complained that this was happening. For all I know they all suffered from this and just didn't notice or care. I'm running Manjaro Linux and using a Blue Yeti. My friend is on Windows, I don't know what model microphone he's using. Is there a way to disable the Acoustic Gain Control? I saw some people suggesting that appending `#config.disableAGC=true` to the call URL would fix it, but it didn't

**Comment by saghul** [comment]
> saw some people suggesting that appending `#config.disableAGC=true` to the call URL would fix it, but it didn't

Did you make sure to do that before joining the meeting? If you add it later the setting does not take effect.

If you are using the Electron app there is a toggle in the setting panel.

**Comment by monstro1** [comment]
> > saw some people suggesting that appending `#config.disableAGC=true` to the call URL would fix it, but it didn't
> 
> Did you make sure to do that before joining the meeting? If you add it later the setting does not take effect.
> 
> If you are using the Electron app there is a toggle in the setting panel.

This seems to have done it. This doesn't work if you're using the widget in Element

**Comment by saghul** [comment]
We are considering adding a switch for it on the web too.

Thanks for the feedback.
