### ISSUE TITLE
Name of audio devices is cut off and makes selection of the correct device cumbersome

### ISSUE THREAD

**Issue by FreeMinded** [jitsi/jitsi-meet#11672]
### Description:

The audio device selection menu seems to be of fixed (or limited) width. Having many audio devices with sometimes long names makes the selection of the correct audio device cumbersome. The issue appears on the welcome screen before joining, as well as within a call.
 
### Steps to reproduce:

1. Connect to a Jitsi Meeting
2. Click on Audio Device Selector
3. If Audio Device Name is longer, than the Selection Windows is wide, the Name is cut of.

### Expected behavior:

The Selection Windows for Audio Devices enlarges dynamically if space permits to show full Audio Device name

### Actual behavior:

Welcome Screen
![grafik](https://user-images.githubusercontent.com/1763127/173537813-b9a0f13f-05b7-4e42-9cab-bdf5d7244f57.png)

in Call
![grafik](https://user-images.githubusercontent.com/1763127/173537993-0c8eeaa1-c793-4e0f-8a28-1b97d3275080.png)

### Server information:

https://meet.jit.si/

### Client information:

- Browser / app version: Chrome/Chromium
- Operating System: Linux / Windows

**Comment by FreeMinded** [comment]
Might be connected to #11656

**Comment by saghul** [comment]
I don't think it's related to #11656, the width of that menu is fixed.

We chose a value (arbitrarily, mind you) that should allow for showing enough of the name to be able to distinguish them.

In your example I see how you could mix up that Cannon Point thing. Hum.

**Comment by saghul** [comment]
Device names now scroll on hover revealing the full display name.
