### ISSUE TITLE
Multiple recording files for a single session

### ISSUE THREAD

**Issue by hemant2capgemini** [jitsi/jitsi-meet#11677]
### Description:

I can see multiple files are created for a single session on Jibri. and all files are corrupted and not playable.
Is there any way to know the cause of it?

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
We are going to need more details here.

Does this happen on your own servers or meet.jit.si? If it's the former, please check the Jibri logs.

**Comment by hemant2capgemini** [comment]
This happened on our server, we are using the latest jitsi release, I couldn't find anything in the jibri logs, but I will again go through and paste it here as well.

**Comment by ashiqhassan95** [comment]
We had the same issue in the latest jibri docker version. There were two files, the first one with a lengthy video (98% meeting) and the second one was shorter. This occurred only once.
