### ISSUE TITLE
Missing Debian packages for latest version

### ISSUE THREAD

**Issue by moufmouf** [jitsi/jitsi-meet#11683]
### Description:

Version 7287-2 was released 2 days ago.

I see this new version on Docker Hub for all images.
However, when I look at the Debian packages on https://download.jitsi.org/stable/, the latest package is 7287-1 (released on May 9th).

It has been 2 days since the release, so I suspect it is more than a simple caching issue and that something went wrong.

### Steps to reproduce:

Go to https://download.jitsi.org/stable/

### Expected behavior:

I should see a file named: jitsi-meet_2.0.7287-2_all.deb 

### Actual behavior:

No such file

This is not strictly related to code, but I guess related to the CI deploy process so I took the liberty to open an issue here rather than putting this in the forums.

Thanks a lot for Jitsi to all the team!

**Comment by saghul** [comment]
The release is really 7287. All the -X are revisions which are specific to Docker, not the Debian packages.

**Comment by moufmouf** [comment]
Thanks! Sorry for the noise :pray:

**Comment by saghul** [comment]
No worries!
