### ISSUE TITLE
Unable to get the JitsimeetView again once I close the PIP window

### ISSUE THREAD

**Issue by amjidkhanmohmand** [jitsi/jitsi-meet#11690]
Hello team Jitsi!
Hopefully, you all are doing well. I ran into a problem when I added Jitsi meet SDK to my android app. All features are working fine, but when I switch to the PIP mode and drag it to the bottom. Then I am unable to get the pip window or the JitsimeetView again. I am using SDK 3.5.+ and I have used the default JitsiMeetAcivity as recommended. I have attached a Gift file that illustrates the problem, please have a look at it and help me out ASAP. 
![ezgif-1-5d0d2f5b2b](https://user-images.githubusercontent.com/36640903/174097278-c779d9b1-f32c-45fd-b2df-44d98306dda9.gif)

**Comment by saghul** [comment]
Isn't the activity terminated when you drag it there?

**Comment by amjidkhanmohmand** [comment]
No its still there, its the pending intent created by JitsiMeetActivity. The pip window is removed but the activity is still running which you can see in the notifications area

**Comment by saghul** [comment]
Ah so it's like pressing the cross then? IN that case it goes into the background and you should be able to bring it back by tapping in the ongoing notification or with the task switcher.

**Comment by amjidkhanmohmand** [comment]
Yes exactly thats what I want but as you can see in the gift file i am unable to get it back. Could you please help me with that?

**Comment by saghul** [comment]
Hum that notification is not our ongoing notification. Our notification says you are in a meeting and allows to hangup or mute right from it.

I think we might have added it later. Your SDK version is way too old. Can you please update and re-test? We don't have the resources to support all old releases, sorry.

**Comment by amjidkhanmohmand** [comment]
Ok I will update it again and will share the results upto then Kindly don't close this issue

**Comment by amjidkhanmohmand** [comment]
I am using SDK version "5.0.2", and below is my code. Please have  a look at it and let me know. I have checked jitsi's app from playstore its working fine but mine is not.

`
 private void StartMeeting()
    {

        setUpButtonStates();

        MeetingSharedClass meetingSharedClass=new MeetingSharedClass(MeetingActivity.this);
        if (meetingSharedClass.getIsMeetActive()!=null &&
        meetingSharedClass.getMeetUserStatus().equalsIgnoreCase("true"))
        {

            meetingSharedClass.setIsFromRejoin("true");
//            Toast.makeText(MeetingActivity.this, "Currently Active", Toast.LENGTH_SHORT).show();
            hangUp();
        }

        if (currentMeeting != null) {


            if (currentMeeting.user_id.equals(userProfileId))
            {
                isHost=true;
                user_status_in_meet=3;
            }

            if (user_status_in_meet==2 || user_status_in_meet==3)
            {
                lay_requests.setVisibility(View.GONE);
            }

            String lobbyMode="disabled";
            if (!isHost)
            {
//                lobbyMode="enabled";
            }

            boolean isKickOut=false;

            if (isHost)
            {
                isKickOut=true;
            }

            boolean isMenuEnabled=false;
            if (isHost || user_status_in_meet==2)
            {
                isMenuEnabled=true;
//                Toast.makeText(MeetingActivity.this, "Menu enabled", Toast.LENGTH_SHORT).show();
            }

            //Simple Listner
            boolean audio_video_button_show=true;
            if (user_status_in_meet==1)
            {

                audio_video_button_show=false;
            }


            registerForBroadcastMessages();
            try {
                String meet_title = PublicFunctions.decode(currentMeeting.title);

                txt_title.setText(""+meet_title);

                pf.activeText(MeetingActivity.this, txt_title, meet_title, null, null);

                  options = new JitsiMeetConferenceOptions.Builder()
                        .setServerURL(new URL("https://meet.jit.si"))
//                                .setRoom("isporty123")
                        .setRoom("" + currentMeeting.meet_code)
                        .setAudioMuted(true)
                        .setVideoMuted(true)
                        .setAudioOnly(false)

                        .setFeatureFlag("kick-out.enabled", isKickOut)
                        .setFeatureFlag("invite.enabled", false)
                        .setFeatureFlag("help.enabled", false)
                        .setFeatureFlag("meeting-password.enabled", false)
                        .setFeatureFlag("recording.enabled", false)
                        .setFeatureFlag("overflow-menu.enabled",isMenuEnabled)
//                        .setFeatureFlag("raise-hand.enabled", "disabled")
                        .setFeatureFlag("raise-hand.enabled", false)
                        .setFeatureFlag("notifications.enabled", false)
                        .setFeatureFlag("reactions.enabled", false)

                        .setFeatureFlag("lobby-mode.enabled", lobbyMode)
//                                .setSubject("My test Meeting")
                        .setSubject("" + meet_title)
                        .setFeatureFlag("add-people.enabled", false)
                        .setFeatureFlag("security-options.enabled", false)
//                        .setFeatureFlag("security-options.enabled", "disabled")

                        .setFeatureFlag("audio-mute.enabled", audio_video_button_show)
                        .setFeatureFlag("video-mute.enabled", audio_video_button_show)
                        .setFeatureFlag("pip.enabled","enabled")
//                                .setFeatureFlag("android.screensharing.enabled","disabled")
//                                    .setWelcomePageEnabled(false)
//                                .setConfigOverride("requireDisplayName", true)
                        .setUserInfo(jitsiMeetUserInfo)
                        .build();
//
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {


                        jitsiMeetActivity.launch(MeetingActivity.this, options);



//                        Toast.makeText(MeetingActivity.this, "Hello"+user_status_in_meet, Toast.LENGTH_SHORT).show();
//
                    }
                });



            } catch (MalformedURLException e) {
                e.printStackTrace();
                Toast.makeText(MeetingActivity.this, ""+e.getMessage(), Toast.LENGTH_SHORT).show();

            }

        }
    }

`

**Comment by saghul** [comment]
Do you see any errors in logcat when launching the meeting?

**Comment by amjidkhanmohmand** [comment]
No nothing in logcat. Let me show you the difference between my app and jitsi's official app that is available on the playstore

**Comment by amjidkhanmohmand** [comment]
Here you can see the difference between my app and Jitsi's app, you will notice the behavior.

### Jitsi's App
![ezgif-1-e63bf77fa9](https://user-images.githubusercontent.com/36640903/174771462-f8e3d105-5cd6-4fbb-a72d-e44f0c5a56b2.gif)


### My APP

![ezgif-1-5d0d2f5b2b](https://user-images.githubusercontent.com/36640903/174771674-ce8cc318-32dc-46dd-809f-909e0a14063b.gif)

**Comment by saghul** [comment]
But you are not doing the same thing. You care not dragging the pip view to the bottom in the Jitsi Meet store app case. Am I missing something?

**Comment by amjidkhanmohmand** [comment]
Please have a look at this one, How can I achieve this in my App

![ezgif-1-3e893ad3a9](https://user-images.githubusercontent.com/36640903/174774543-6913b514-33f0-4ea3-b9f4-2f95703e0095.gif)

**Comment by saghul** [comment]
Right. Looks like the ongoing notification is not working.

Can you please send the full logcat?

**Comment by amjidkhanmohmand** [comment]
This is the complete logcat. I think there is nothing in it.

**Comment by amjidkhanmohmand** [comment]
`
E/usman: run: App Running 52
I/okhttp.OkHttpClient: --> POST https://isporty.net/ispanel/public/api/v1/meeting_attendances
    Content-Type: application/json; charset=UTF-8
    Content-Length: 18
    {"meeting_id":"4"}
    --> END POST (18-byte body)
I/okhttp.OkHttpClient: --> POST https://isporty.net/adminpanel/polling/new
    Content-Type: application/json; charset=UTF-8
    Content-Length: 52
I/okhttp.OkHttpClient: {"user_id":"957","after_date":"2022-06-21 11:53:41"}
    --> END POST (52-byte body)
I/okhttp.OkHttpClient: --> POST https://isporty.net/adminpanel/polling/new
    Content-Type: application/json; charset=UTF-8
    Content-Length: 52
    {"user_id":"957","after_date":"2022-06-21 11:53:41"}
    --> END POST (52-byte body)
I/okhttp.OkHttpClient: --> POST https://isporty.net/adminpanel/polling/new
    Content-Type: application/json; charset=UTF-8
    Content-Length: 52
    {"user_id":"957","after_date":"2022-06-21 11:53:41"}
    --> END POST (52-byte body)
D/FA: Application going to the background
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/adminpanel/polling/new (2004ms)
    Date: Tue, 21 Jun 2022 11:55:52 GMT
    Server: Apache
    Access-Control-Allow-Origin: *
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate
    Pragma: no-cache
    Set-Cookie: ci_session=112a0bd0f022d2ea770076fc9894670e6de1d71c; expires=Tue, 21-Jun-2022 13:55:53 GMT; Max-Age=7200; path=/; HttpOnly
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: {"status":"Success","update":{"available":"false","check_date":"2022-06-21 11:55:53"},"message":"Success"}
    <-- END HTTP (106-byte body)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/ispanel/public/api/v1/meeting_attendances (1412ms)
    Date: Tue, 21 Jun 2022 11:55:53 GMT
I/okhttp.OkHttpClient: Server: Apache
    Cache-Control: no-cache, private
    X-RateLimit-Limit: 60
    X-RateLimit-Remaining: 38
    Access-Control-Allow-Origin: *
    Vary: Authorization
    Keep-Alive: timeout=5, max=99
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json
I/okhttp.OkHttpClient: {"status":true,"message":"Meeting Open","meeting":{"id":4,"title":"testing","user_id":957,"status":1,"meet_code":"isporty_957acdb126d-3a03-41ec-80b8-59115733dfd5","deleted_at":null,"created_at":"2022-06-21T11:53:41.000000Z","updated_at":"2022-06-21T11:53:41.000000Z"},"attendances":[{"id":4,"firstname":"Amjid","lastname":"Khan Mohmand","username":"Khan123","email":"amjidk113@gmail.com","user_bio":" Android Developer \\uD83D\\uDCCD\\u26BD\\uFE0F\\uD83C\\uDFCF\\uD83C\\uDFBD #football #volcano ","phone_number":"92","sport_type":"Football","country":"Pakistan","profile_pic":"https%3A%2F%2Fres.cloudinary.com%2Fdleop8bf0%2Fimage%2Fupload%2Fv1636459598%2FiSporty%2Fuser_profile_images%2F1636459597.png","profile_pic_public_id":"iSporty%2Fuser_profile_images%2F1636459597","cover_photo":"https%3A%2F%2Fres.cloudinary.com%2Fdleop8bf0%2Fimage%2Fupload%2Fv1636459596%2FiSporty%2Fuser_cover_pictures%2F1636459592.png","cover_photo_public_id":"iSporty%2Fuser_cover_pictures%2F1636459592","theme_color":"green","registration_status":2,"profile_status":0,"followers":["963","956","968","1054","1069"],"follower_request":[],"muted_users":["961"],"blocked_users":"","private_profile":0,"device_id":"f-PQcXDPQoebY4t6mjemEr:APA91bHds_KYKhLgSpDhyeA6AOzIsKa14xRla22JWdzPB1Ja8jd7um76Y8h8khMo5pKssmNPInxFfduzNpP3OuMfgibZXZkT98UmhYXEBDpRpNfI5yPr_bo9wp6RVNK5J2KCyYIVuYqN,dhAixNtMTDCM_Rz2jJC_2_:APA91bHskayCxRMtW7mfD0PvujYKI_vcHjD76aYiIpEXrWPY9wwohnDrmZXDYqLn_UImA9h8b9Cr2TJvje9FoDqHcVVI44cDeznOMZefwmQN3jJVaeFlm1Ifml0r2k6XoIoqW_R9ox7p,fqOm8ELfTsCLatSMwtYwrt:APA91bG8kSm2bhOqqzkzjzTYEOcAMGVHeRmboO_VfuAuIq49OhujgaMAfAhUNDevLi3Ot68YFrXW8lFkm4Pv9h6D2MSHG6pGyEfPO9YPztzyolQR1RiWyGLjr_745Tqj3gdvTqdYW9uA, ","admin_verified":0,"suspension_status":0,"user_verification_status":1,"verification_token":"","token_entered":null,"modified":"2022-06-21 11:52:52","created":"2021-06-04 16:21:54","deleted":null,"club_type":"Barcelona","access_token":"$2y$10$Mc\/67NNiGc\/1o3yLdO2q\/eVp\/olESJG9i7Kt4lR1uqaIn15W0E5a2","created_at":"2022-06-21T11:53:41.000000Z","updated_at":"2022-06-21T11:53:41.000000Z","user_id":957,"meeting_id":4,"raise_hand_state":0,"request_to_speak":0,"attendee_status":3,"deleted_at":null}]}
    <-- END HTTP (2182-byte body)
I/okhttp.OkHttpClient: --> POST https://isporty.net/adminpanel/polling/new
    Content-Type: application/json; charset=UTF-8
    Content-Length: 52
    {"user_id":"957","after_date":"2022-06-21 11:53:41"}
I/okhttp.OkHttpClient: --> END POST (52-byte body)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/adminpanel/polling/new (1563ms)
    Date: Tue, 21 Jun 2022 11:55:53 GMT
    Server: Apache
    Access-Control-Allow-Origin: *
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate
    Pragma: no-cache
    Set-Cookie: ci_session=c922dc751b1fb4107ab33a7bc140e939087fe937; expires=Tue, 21-Jun-2022 13:55:53 GMT; Max-Age=7200; path=/; HttpOnly
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: {"status":"Success","update":{"available":"false","check_date":"2022-06-21 11:55:53"},"message":"Success"}
    <-- END HTTP (106-byte body)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/adminpanel/polling/new (1929ms)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/adminpanel/polling/new (642ms)
    Date: Tue, 21 Jun 2022 11:55:53 GMT
I/okhttp.OkHttpClient: Date: Tue, 21 Jun 2022 11:55:53 GMT
I/okhttp.OkHttpClient: Server: Apache
I/okhttp.OkHttpClient: Server: Apache
I/okhttp.OkHttpClient: Access-Control-Allow-Origin: *
I/okhttp.OkHttpClient: Access-Control-Allow-Origin: *
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
I/okhttp.OkHttpClient: Expires: Thu, 19 Nov 1981 08:52:00 GMT
I/okhttp.OkHttpClient: Cache-Control: no-store, no-cache, must-revalidate
I/okhttp.OkHttpClient: Cache-Control: no-store, no-cache, must-revalidate
I/okhttp.OkHttpClient: Pragma: no-cache
I/okhttp.OkHttpClient: Pragma: no-cache
I/okhttp.OkHttpClient: Set-Cookie: ci_session=a9a192b77456d2114f752fbc993bcff00502e934; expires=Tue, 21-Jun-2022 13:55:53 GMT; Max-Age=7200; path=/; HttpOnly
I/okhttp.OkHttpClient: Set-Cookie: ci_session=9633f4d043fcfea20a60ffdf71280e6dfbab9b35; expires=Tue, 21-Jun-2022 13:55:53 GMT; Max-Age=7200; path=/; HttpOnly
    Keep-Alive: timeout=5, max=99
I/okhttp.OkHttpClient: Keep-Alive: timeout=5, max=100
I/okhttp.OkHttpClient: Connection: Keep-Alive
I/okhttp.OkHttpClient: Connection: Keep-Alive
    Transfer-Encoding: chunked
I/okhttp.OkHttpClient: Transfer-Encoding: chunked
I/okhttp.OkHttpClient: Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: {"status":"Success","update":{"available":"false","check_date":"2022-06-21 11:55:53"},"message":"Success"}
I/okhttp.OkHttpClient: {"status":"Success","update":{"available":"false","check_date":"2022-06-21 11:55:53"},"message":"Success"}
    <-- END HTTP (106-byte body)
I/okhttp.OkHttpClient: <-- END HTTP (106-byte body)
I/ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_RUNNING_CRITICAL) received by JS VM, running a GC
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/adminpanel/polling/new (1598ms)
    Date: Tue, 21 Jun 2022 11:55:53 GMT
    Server: Apache
    Access-Control-Allow-Origin: *
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate
    Pragma: no-cache
    Set-Cookie: ci_session=7836b39d3bdcfc8691fc7917174efec298551a90; expires=Tue, 21-Jun-2022 13:55:54 GMT; Max-Age=7200; path=/; HttpOnly
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: {"status":"Success","update":{"available":"false","check_date":"2022-06-21 11:55:54"},"message":"Success"}
    <-- END HTTP (106-byte body)
E/usman: run: App Running 53
I/okhttp.OkHttpClient: --> POST https://isporty.net/ispanel/public/api/v1/meeting_attendances
    Content-Type: application/json; charset=UTF-8
    Content-Length: 18
    {"meeting_id":"4"}
    --> END POST (18-byte body)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/adminpanel/polling/new (2306ms)
    Date: Tue, 21 Jun 2022 11:55:53 GMT
    Server: Apache
    Access-Control-Allow-Origin: *
I/okhttp.OkHttpClient: Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate
    Pragma: no-cache
    Set-Cookie: ci_session=bd50e2ff3d6e47898977bb6297897c2257e937eb; expires=Tue, 21-Jun-2022 13:55:53 GMT; Max-Age=7200; path=/; HttpOnly
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: {"status":"Success","update":{"available":"false","check_date":"2022-06-21 11:55:53"},"message":"Success"}
    <-- END HTTP (106-byte body)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/ispanel/public/api/v1/meeting_attendances (624ms)
I/okhttp.OkHttpClient: Date: Tue, 21 Jun 2022 11:55:54 GMT
    Server: Apache
    Cache-Control: no-cache, private
    X-RateLimit-Limit: 60
    X-RateLimit-Remaining: 37
    Access-Control-Allow-Origin: *
    Vary: Authorization
    Keep-Alive: timeout=5, max=98
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json
I/okhttp.OkHttpClient: {"status":true,"message":"Meeting Open","meeting":{"id":4,"title":"testing","user_id":957,"status":1,"meet_code":"isporty_957acdb126d-3a03-41ec-80b8-59115733dfd5","deleted_at":null,"created_at":"2022-06-21T11:53:41.000000Z","updated_at":"2022-06-21T11:53:41.000000Z"},"attendances":[{"id":4,"firstname":"Amjid","lastname":"Khan Mohmand","username":"Khan123","email":"amjidk113@gmail.com","user_bio":" Android Developer \\uD83D\\uDCCD\\u26BD\\uFE0F\\uD83C\\uDFCF\\uD83C\\uDFBD #football #volcano ","phone_number":"92","sport_type":"Football","country":"Pakistan","profile_pic":"https%3A%2F%2Fres.cloudinary.com%2Fdleop8bf0%2Fimage%2Fupload%2Fv1636459598%2FiSporty%2Fuser_profile_images%2F1636459597.png","profile_pic_public_id":"iSporty%2Fuser_profile_images%2F1636459597","cover_photo":"https%3A%2F%2Fres.cloudinary.com%2Fdleop8bf0%2Fimage%2Fupload%2Fv1636459596%2FiSporty%2Fuser_cover_pictures%2F1636459592.png","cover_photo_public_id":"iSporty%2Fuser_cover_pictures%2F1636459592","theme_color":"green","registration_status":2,"profile_status":0,"followers":["963","956","968","1054","1069"],"follower_request":[],"muted_users":["961"],"blocked_users":"","private_profile":0,"device_id":"f-PQcXDPQoebY4t6mjemEr:APA91bHds_KYKhLgSpDhyeA6AOzIsKa14xRla22JWdzPB1Ja8jd7um76Y8h8khMo5pKssmNPInxFfduzNpP3OuMfgibZXZkT98UmhYXEBDpRpNfI5yPr_bo9wp6RVNK5J2KCyYIVuYqN,dhAixNtMTDCM_Rz2jJC_2_:APA91bHskayCxRMtW7mfD0PvujYKI_vcHjD76aYiIpEXrWPY9wwohnDrmZXDYqLn_UImA9h8b9Cr2TJvje9FoDqHcVVI44cDeznOMZefwmQN3jJVaeFlm1Ifml0r2k6XoIoqW_R9ox7p,fqOm8ELfTsCLatSMwtYwrt:APA91bG8kSm2bhOqqzkzjzTYEOcAMGVHeRmboO_VfuAuIq49OhujgaMAfAhUNDevLi3Ot68YFrXW8lFkm4Pv9h6D2MSHG6pGyEfPO9YPztzyolQR1RiWyGLjr_745Tqj3gdvTqdYW9uA, ","admin_verified":0,"suspension_status":0,"user_verification_status":1,"verification_token":"","token_entered":null,"modified":"2022-06-21 11:52:52","created":"2021-06-04 16:21:54","deleted":null,"club_type":"Barcelona","access_token":"$2y$10$Mc\/67NNiGc\/1o3yLdO2q\/eVp\/olESJG9i7Kt4lR1uqaIn15W0E5a2","created_at":"2022-06-21T11:53:41.000000Z","updated_at":"2022-06-21T11:53:41.000000Z","user_id":957,"meeting_id":4,"raise_hand_state":0,"request_to_speak":0,"attendee_status":3,"deleted_at":null}]}
    <-- END HTTP (2182-byte body)
E/usman: run: App Running 54
I/okhttp.OkHttpClient: --> POST https://isporty.net/ispanel/public/api/v1/meeting_attendances
I/okhttp.OkHttpClient: Content-Type: application/json; charset=UTF-8
    Content-Length: 18
    {"meeting_id":"4"}
    --> END POST (18-byte body)
I/okhttp.OkHttpClient: <-- 200 OK https://isporty.net/ispanel/public/api/v1/meeting_attendances (745ms)
I/okhttp.OkHttpClient: Date: Tue, 21 Jun 2022 11:55:56 GMT
    Server: Apache
    Cache-Control: no-cache, private
    X-RateLimit-Limit: 60
    X-RateLimit-Remaining: 36
    Access-Control-Allow-Origin: *
    Vary: Authorization
    Keep-Alive: timeout=5, max=97
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json
    {"status":true,"message":"Meeting Open","meeting":{"id":4,"title":"testing","user_id":957,"status":1,"meet_code":"isporty_957acdb126d-3a03-41ec-80b8-59115733dfd5","deleted_at":null,"created_at":"2022-06-21T11:53:41.000000Z","updated_at":"2022-06-21T11:53:41.000000Z"},"attendances":[{"id":4,"firstname":"Amjid","lastname":"Khan Mohmand","username":"Khan123","email":"amjidk113@gmail.com","user_bio":" Android Developer \\uD83D\\uDCCD\\u26BD\\uFE0F\\uD83C\\uDFCF\\uD83C\\uDFBD #football #volcano ","phone_number":"92","sport_type":"Football","country":"Pakistan","profile_pic":"https%3A%2F%2Fres.cloudinary.com%2Fdleop8bf0%2Fimage%2Fupload%2Fv1636459598%2FiSporty%2Fuser_profile_images%2F1636459597.png","profile_pic_public_id":"iSporty%2Fuser_profile_images%2F1636459597","cover_photo":"https%3A%2F%2Fres.cloudinary.com%2Fdleop8bf0%2Fimage%2Fupload%2Fv1636459596%2FiSporty%2Fuser_cover_pictures%2F1636459592.png","cover_photo_public_id":"iSporty%2Fuser_cover_pictures%2F1636459592","theme_color":"green","registration_status":2,"profile_status":0,"followers":["963","956","968","1054","1069"],"follower_request":[],"muted_users":["961"],"blocked_users":"","private_profile":0,"device_id":"f-PQcXDPQoebY4t6mjemEr:APA91bHds_KYKhLgSpDhyeA6AOzIsKa14xRla22JWdzPB1Ja8jd7um76Y8h8khMo5pKssmNPInxFfduzNpP3OuMfgibZXZkT98UmhYXEBDpRpNfI5yPr_bo9wp6RVNK5J2KCyYIVuYqN,dhAixNtMTDCM_Rz2jJC_2_:APA91bHskayCxRMtW7mfD0PvujYKI_vcHjD76aYiIpEXrWPY9wwohnDrmZXDYqLn_UImA9h8b9Cr2TJvje9FoDqHcVVI44cDeznOMZefwmQN3jJVaeFlm1Ifml0r2k6XoIoqW_R9ox7p,fqOm8ELfTsCLatSMwtYwrt:APA91bG8kSm2bhOqqzkzjzTYEOcAMGVHeRmboO_VfuAuIq49OhujgaMAfAhUNDevLi3Ot68YFrXW8lFkm4Pv9h6D2MSHG6pGyEfPO9YPztzyolQR1RiWyGLjr_745Tqj3gdvTqdYW9uA, ","admin_verified":0,"suspension_status":0,"user_verification_status":1,"verification_token":"","token_entered":null,"modified":"2022-06-21 11:52:52","created":"2021-06-04 16:21:54","deleted":null,"club_type":"Barcelona","access_token":"$2y$10$Mc\/67NNiGc\/1o3yLdO2q\/eVp\/olESJG9i7Kt4lR1uqaIn15W0E5a2","created_at":"2022-06-21T11:53:41.000000Z","updated_at":"2022-06-21T11:53:41.000000Z","user_id":957,"meeting_id":4,"raise_hand_state":0,"request_to_speak":0,"attendee_status":3,"deleted_at":null}]}
    <-- END HTTP (2182-byte body)
`

**Comment by amjidkhanmohmand** [comment]
Hello Team Jitsi!
Hopefully, you are doing well. Any updates on the above issue?

**Comment by saghul** [comment]
That logcat contains no messages from the SDK.

**Comment by amjidkhanmohmand** [comment]
Yes, that was the overall logcat report. Don't know why there is nothing for the sdk. But its something like a pending intent with a notification. The functionality should be assigned in the sdk because there is no way to access it outside the sdk

**Comment by saghul** [comment]
Sorry I have no idea right now :-/

Any chance you can repro with the sample apps?

**Comment by amjidkhanmohmand** [comment]
Hmm no worries, I can share the idea. When you put the notification in the notification area which indicates that app is running when you start a meeting. Inside the code for that notification just put .setContenAction(which takes an intent)
Or I think its .setAction, there you can define the functionality for assigning the functionality for opening the pip again when notification is clicked

**Comment by saghul** [comment]
But we already have that, we have the mute and hangup actions and tapping the notification itself brings back the app.

Not sure why this doesn't happen for you.

**Comment by amjidkhanmohmand** [comment]
Hmm, don't know why its not working fine with me. Because I have added the sdk as per the sample app. Anyways, thanks for your time and help. You can close the issue. I will recheck the whole thing again.
