### ISSUE TITLE
jitsi-meet-tokens: the deb package doesn't update the prosody config file

### ISSUE THREAD

**Issue by emrahcom** [jitsi/jitsi-meet#11702]
### Description:

 The `Prosody` config file remains unchanged after installing `jitsi-meet-tokens`. So the authentication mode remains as "`anonymous`" instead of "`token`" 

### Steps to reproduce:

1. Install the `jitsi-meet-tokens` package
2. Check the `prosody` config file. Normally it should be updated but not updated.

### Expected behavior:

`authentication`, `app_id` and `app_secret` parameters should be updated in the `prosody` config file.

### Actual behavior:

There is no change in the config file.

### Server information:

- Jitsi Meet version:
  - jitsi-meet 2.0.7416-1
  - jitsi-meet-tokens 1.0.6239-1
- Operating System:
  - Debian 11 Bullseye

### Additional information:

The `if` block in [jitsi-meet-tokens.postinst](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-tokens.postinst#L53) doesn't work anymore because [The Prosody config template](https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L150) has already `authentication = "token"` and the `if` condition will never come `true`

**Comment by emrahcom** [comment]
Related with this issue, `apt-get remove jitsi-meet-tokens`  breaks the `authentication` line which is inside the `VirtualHost "jigasi.meet.jitsi"` block. It should not change this line.

**Comment by emrahcom** [comment]
IMO adding `VirtualHost "jigasi.meet.jitsi"` block as a seperate file solves both issues.

- moving this block into `/etc/prosody/conf.available/jigasi.meet.jitsi.cfg.lua`
- and creating a symbolic link for this file in `/etc/prosody/conf.d/`

**Comment by saghul** [comment]
Ping @damencho WDYT?

**Comment by damencho** [comment]
In general I like it :) If we start from scratch I will do it that way. 

But I think, the extra file will complicate the situation a bit for jaas users, we want to keep it as simple as possible. 
So I have this on my immediate to-do list, so I will come up with something ... and that should be before the next stable release, I hope.

**Comment by damencho** [comment]
I was even thinking that we should drop this package, and keep it by default configured with tokens.
For some future changes we have planned, we will be generating some tokens and stuff by default and there will be a pre-configured HTTP endpoint for public keys, so then we can do that and drop it completely and default with tokens allowing empty tokens.

**Comment by saghul** [comment]
> I was even thinking that we should drop this package, and keep it by default configured with tokens.

I agree!
