### ISSUE TITLE
Audio output defaults to ear speaker

### ISSUE THREAD

**Issue by regentcid434** [jitsi/jitsi-meet#1171]
Running on an iPhone, the audio in a conference only uses the ear speaker and not the speaker phone. Holding the phone to your ear defeats the purpose of using the camera. Is there a way to change this?

**Comment by coosamatt** [comment]
Yeah same issue here. Anyone know a solution?

**Comment by pcw0002** [comment]
I'm having this same issue also. Any solution would be great.

**Comment by lyubomir** [comment]
We need to implement it. We have it on our roadmap so it'll surely be taken care of.

**Comment by regentcid434** [comment]
Is this something we could help with if you pointed us in that direction?

**Comment by lyubomir** [comment]
@regentcid434, that'd be awesome. I haven't finished with the research so there's that part to be completed before we jump to a specific implementation. What I've read on the Internet is the following. On the Web with the JavaScript WebRTC API we'd have these as separate output devices.   The native WebRTC API doesn't provide such a direct way and merely picks some output as default so one has to instruct the underlying audio output used by the native WebRTC API to switch to the speaker. I may be wrong though. We need to finish this research, see what others are doing, probably modify react-native-webrtc so that we have a semblance of the Web/JavaScript WebRTC API implemented there.

**Comment by regentcid434** [comment]
The native code is a bit out of my realm, but I seem to have gotten it working for my use case by adding in react-native-incall-manager and using it to force the audio to use the speaker once the connection has been established and then reverting after disconnecting. It's not ideal, but even WebRTC currently recommends using it for native control. I've only used this in iOS so far, but it was very little code. Hopefully, it will be robust across platforms. 

If this is something people would find useful, I could put in a pull request or share the code for critique.

**Comment by quangcm** [comment]
I found a quick solution and already tried in my project, it works well

**iOS:**
In project `RCTWebRTC`
File `WebRTCModule+RTCDataChannel.m`
Method: `- (void)dataChannel:(RTCDataChannel *)channel didReceiveMessageWithBuffer:(RTCDataBuffer *)buffer`
add these line of code in the bottom of method above

```
    NSError *error = nil;
    AVAudioSession *session = [AVAudioSession sharedInstance];
    [session setCategory:AVAudioSessionCategoryPlayAndRecord
             withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker
                   error:&error];
```

**Android** (it is more complicated a bit):
In project `react-native-webrtc`
Class: `WebRTCModule`
add more declaration as below:
```
    public static final String ACTION_DATA_CHANNEL_RCVMSG = "com.oney.WebRTCModule.action.datachannelrcvmsg";

    public void onDataChannelReceiveMessage() {
        Intent intent = new Intent(ACTION_DATA_CHANNEL_RCVMSG);
        getReactApplicationContext().sendBroadcast(intent);
    }
```

Class: `DataChannelObserver`
Method: `onMessage`
add this line of code in the bottom of method
```
    webRTCModule.onDataChannelReceiveMessage();
```

Finally, in your custom class `ReactActivity`, handle this broadcast event `ACTION_DATA_CHANNEL_RCVMSG`. For example:
```

    private BroadcastReceiver broadcastReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
            switch (action) {
                case ACTION_DATA_CHANNEL_RCVMSG: {
                    AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                    boolean useHeadphone = am.isWiredHeadsetOn();
                    am.setMode(AudioManager.MODE_IN_CALL);
                    am.setSpeakerphoneOn(!useHeadphone);
                    break;
                }
            }
        }
    };
```

**Comment by saghul** [comment]
Oops, this is old :-) We now default to the speaker for video calls and switch to the earpiece for audio-only mode is enabled.

**Comment by carotkut94** [comment]
I have added bundle config as below
 ` Bundle config = new Bundle();
        config.putBoolean("startAudioOnly", true);
        Bundle urlObject = new Bundle();
        urlObject.putBundle("config", config);
        urlObject.putString("url", "https://meet.jit.si/demo");
        view.loadURLObject(urlObject);
        setContentView(view);`

call starts as audio only, but audio gets routed to speaker, instead of earphone, and i press on select the sound device, i only get the option of "Speaker".
and if i start the jitsi-meet android app(downloaded from play store) and start the voice only call, it works as expected.
What am i missing?

**Comment by LucaComanducci** [comment]
Hi, the problem still happen to me
(i'm building the sdk at commit 14855f3255b91960079da5a4ff38a8ceb3441222).

This problem happen to me randomly, sometimes the Jitsi view start and output audio to earpiece and I can't force the output to speakers: if I try to select "speakers" in the menu "select the sound device" this has no effect, the sound still output on earpiece.

I debugged the native iOS part of the sdk (AudioMode.m) and I can confirm that this code is correctly called when I select "speakers":

`success = [session overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:&error];`

Can you help me?

**Comment by erandakarachchi** [comment]
@carotkut94  did you found any solution to this?

**Comment by kaswan24** [comment]
@saghul this is still a problem and audio calls are not using earpiece as default.

**Comment by saqibomer** [comment]
@kaswan24 @erandakarachchi Did you find solution for earphones instead of default speaker?

**Comment by kbhutani0001** [comment]
@saghul any workaround this? or atleast any way to move the audio output select button to toolbar so it is quick to access and switch to earpiece ?

**Comment by saghul** [comment]
It's now on the title bar, so no longer one menu away.

**Comment by saghul** [comment]
Not sure it made it to the latest SDK release but we'll be releasing a new one very soon. This is how it looks like:

![image](https://user-images.githubusercontent.com/317464/175295932-621d1a1f-387a-4a54-aab9-305741085692.jpeg)

**Comment by kbhutani0001** [comment]
Got it. Thanks

**Comment by smd-mobileteam** [comment]
https://github.com/jitsi/jitsi-meet/issues/16610

**Comment by Ahmad-Mustafaa** [comment]
> audio-only mode

Hi 
Still not working it always on **speaker** when in Audio mode even. I am using android SDK 11.3.0
Already Tried All these 
```
.setFeatureFlag("startAudioOnly", true)
.setConfigOverride("startAudioOnly", true)
.setAudioMuted(false)
.setAudioOnly(true)
```

**Comment by saghul** [comment]
That is by design. The output device is speaker by default.
