### ISSUE TITLE
pour performance running on AWS EC2 T2.micro 

### ISSUE THREAD

**Issue by rbdevr** [jitsi/jitsi-meet#11713]
Hi all,

I'm running jitsi meet on AWS EC2 T2. micro. with the latest version (17-Jun-2022 20:45)

I'm always facing slow down on with 3~4 users logged and very low fps on screen sharing.

Is there specific settings that I can use to improve my experience?

I also notice some iOS crashes with latest version right after logging and enabling mute.

Cheers

**Comment by saghul** [comment]
A t2.Micro is not nearly enough to run the Jitsi meet stack. You need at least 4 cores and 8 GB of RAM. Anything less can o my be used for just a little testing.

Note that by default screen sharing works at a low fps, if you want to increase that there is an option in the settings panel.

What iOS version of the app were you using and what steps did you follow to make it crash?

**Comment by fleaz** [comment]
> I'm running jitsi meet on AWS EC2 T2.micro

Slightly unrelated: If you use a t2.micro because it's part of the AWS Free Tier, you can also just use a t3.micro or even a t4g.micro, they all apply for the same FreeTier scheme and give you two vCPU instead of one :)
