### ISSUE TITLE
keep the camera turned on when sharing

### ISSUE THREAD

**Issue by erasingla20** [jitsi/jitsi-meet#11735]
While sharing a screen , I would like my camera to stay switched on. Currently camera should be disabled in Android/IOS devices.

For Mobile (Android/IOS) this feature is added or not?

**Comment by saghul** [comment]
This is not currently implemented. We might be able to add it now with multi-stream, right @jallamsetty1 ?

**Comment by jallamsetty1** [comment]
> This is not currently implemented. We might be able to add it now with multi-stream, right @jallamsetty1 ?

Yes it should be possible when RN switches to unified-plan mode.

**Comment by nawed2611** [comment]
Can I work on this issue?

**Comment by saghul** [comment]
We are not ready for this, on iOS we need to enable multi-tasking mode first. You can take a stab at Android though.

**Comment by saghul** [comment]
We chose not to allow this for performance reasons.
