### ISSUE TITLE
Iframe API-initiated audio moderation breaks participants' mics

### ISSUE THREAD

**Issue by jlightfoot** [jitsi/jitsi-meet#11730]
### Description:

Toggling audio moderation works as expected in the GUI.  If it's toggled on with the api.executeCommand('toggleModeration', true, 'audio') command, any new participants will have their mic permanently disabled.  Even moderators can unmute but no audio is captured from their mic.  The mic muting of participants who connected prior and the moderator who turned on the feature works as expected.

### Steps to reproduce:

1. Moderator creates a conference 
2. In the Chrome console, moderator issues the command: api.executeCommand('toggleModeration', true, 'audio')
3. Another participant connects to the conference and unmutes (or asks the moderator to unmute them if not another moderator).
4. With the mic unmuted, nobody in the conference can hear the new participant.

### Expected behavior:

When a moderator toggles on the audio moderation feature, everyone is muted.  Moderators can unmute at will.  Other participants must ask permission from the moderator before unmuting.  In either case, once the mic is unmuted, audio from the mic is heard in the conference.

### Actual behavior:

After moderation is turned on by command, any new participant is able to turn their mic to an unmuted state but the mic audio is not audible in the conference.  Any participant in the conference prior to the moderator issuing the command (including the moderator themselves) can operate their mic as usual.

### Server information:

- Jitsi Meet version:  Current JAAS
- Operating System:

### Client information:

- Browser / app version:  Chrome 102 and 103
- Operating System: Windows 11 and MacOS Monterrey

**Comment by robertpin** [comment]
@jlightfoot will close this as we already have this issue on JaaS Support
