### ISSUE TITLE
Android screen sharing problem

### ISSUE THREAD

**Issue by ysbutuner** [jitsi/jitsi-meet#11740]
### Steps to reproduce:

1. I'm starting a conference.
2. Participants gain access to the room.
3. I turn on screen sharing from my Android device.
4. I throw the app into the background and open the slideshow
5. I don't touch the screen while I'm telling a slide
6. My screen sharing to the participants is not going to go
7. My screen sharing continues when I read to the screen

### Expected behavior:

Screen sharing continues as long as I don't touch the screen

### Actual behavior:

Screen sharing stops when the app is in the background and I don't touch the screen

### Server information:

- Jitsi Meet version: 22.2.0
- Operating System:  Android

### Client information:

- Browser / app version: 22.2.0
- Operating System: Android

**Comment by saghul** [comment]
This is a known issue with screen sharing on mobile devices, when the content doesn't change they may stop sending media at all and this is perceived by the remote endpoints as a sign that there is a problem but in reality it's just that the content hasn't changed.

**Comment by ysbutuner** [comment]
Hi sahul,
This is displayed as a problem for the remote device, can you please let me know if there will be any improvement for it?

**Comment by saghul** [comment]
Not anytime soon.

**Comment by ysbutuner** [comment]
As a matter of fact, if I want to make a development on this subject, what kind of way should I follow, where should I fight.

**Comment by saghul** [comment]
Most likely the changes will need to happen in react-native-webrtc.

**Comment by ysbutuner** [comment]
thank you
