### ISSUE TITLE
[Android SDK][5.1.0] Trackers GIPHY Analytics and IAB Open measurement

### ISSUE THREAD

**Issue by bmarty** [jitsi/jitsi-meet#11759]
### Description:

I am using the LIBRE_BUILD SDK but some trackers are detected with version 5.1.0.

See the log from this PR:
- https://github.com/vector-im/element-android/pull/6195
- build: https://buildkite.com/matrix-dot-org/element-android/builds/8696
- exodus report: https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/8696/jobs/01811a21-a9f5-43c8-8473-8dbc6a5e2026/artifacts/01811a3c-1043-4fb3-8634-8250810bfb25

```json
  "trackers": [
    {
      "name": "GIPHY Analytics",
      "id": 299
    },
    {
      "name": "IAB Open Measurement",
      "id": 328
    }
  ]
```
 
Is it possible to have a LIBRE_BUILD version without any trackers?

### Steps to reproduce:

1. Use SDK 5.1.0 LIBRE_BUILD version
2. Run exodus

### Expected behavior:

No tracker is added when using the LIBRE_BUILD of the Jitsi SDK

### Actual behavior:

Trackers GIPHY Analytics and IAB Open measurement are detected

### Server information:
N/A

### Client information:

- Operating System: Android

### Additional information:

Using

```groovy
implementation('org.jitsi.react:jitsi-meet-sdk:5.1.0') {
    exclude group: 'com.giphy.sdk'
}
```

works, but the application crashes at runtime when joining a Jitsi conf.

```shell
Thread: create_react_context, Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/GPHSettings;
```

Using 

```groovy
implementation('org.jitsi.react:jitsi-meet-sdk:5.1.0') {
        exclude group: 'com.giphy.sdk', module: 'analytics'
        exclude group: 'com.giphy.sdk', module: 'tracking'
}
```

does not exclude the package from the generated APKs.

Please let me know if you need more information. Thanks!

**Comment by saghul** [comment]
Hi there!

Ah bummer, I could nuke those on the JS side, but the RN SDK uses their Android SDK, so that's more complicated. HEre is what we can do (PRs are welcome):

- Exclude the `com.giphy.sdk` group entirely in case of a libre build
- Detect if Giphy is available at runtime: https://github.com/jitsi/jitsi-meet/blob/730d42cba1671cab2149350a3aef59621e43406e/android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java#L113 (we do a similar thing for amplitude or gooogle signin)
- Add some JS code to check for the native module before we use the feature, to prevent a JS crash at runtime

I can help with review, but I'm a bit busy these days to work on it myself, it may take me a few weeks.

**Comment by licaon-kter** [comment]
F-Droid is cleaning up too and this popped up, fyi: https://gitlab.com/fdroid/fdroidserver/-/issues/1004#note_1031396665

I'll disable versions that are tainted.

**Comment by saghul** [comment]
Fix on https://github.com/jitsi/jitsi-meet/pull/11894

@bmarty The libre build was not really intended for the SDK but for the app. At any rate, once that PR lands and a new release is made you can `exclude group: 'com.giphy.sdk'` and that will work.

@licaon-kter Once it lands I'll tag a new 22.4.0 tag so you can give it a go.

**Comment by licaon-kter** [comment]
@saghul do ping me when it's merged, thanks

**Comment by saghul** [comment]
@licaon-kter Can you please try to build tag https://github.com/jitsi/jitsi-meet/tree/android-22.4.0-hf.1 ?

**Comment by licaon-kter** [comment]
Trying now...

**Comment by licaon-kter** [comment]
@saghul Done, APK is clean, updated: https://gitlab.com/fdroid/fdroiddata/-/commit/3f37a85b40808ee53d8fa9e965db0ed642af0248

**Comment by saghul** [comment]
Wonderful news, thank you!
