### ISSUE TITLE
Opening a dialog fixes the body height

### ISSUE THREAD

**Issue by weeman1337** [jitsi/jitsi-meet#11765]
### Description:

If I open any dialog something sets a static height to `body`.  
This can cause issues esp. when you started with a small height.

### Steps to reproduce:

1. Start a meeting on https://meet.jit.si/
2. Give the window a small height
3. Click on the settings
4. Resize the window to a larger height

### Expected behavior:

Everything visible

### Actual behavior:

Body size limited. I cannot see the dialog contents.

![dialogue_resize](https://user-images.githubusercontent.com/6216686/176429866-6ba9e01a-11b0-4c21-bdb1-0ebc410b2661.gif)

### Server information:

- Jitsi Meet version: https://meet.jit.si/
- Operating System: -

### Client information:

- Browser / app version: Firefox 102.0 (64-bit)
- Operating System: Ubuntu 22.04 LTS

**Comment by saghul** [comment]
This is likely something AtlasKit does... hope we can remove it soon.

**Comment by weeman1337** [comment]
Workaround:

In Jitsi Meet web, add the following to the `head.html`:

```
<style>
html body {
    height: 100% !important;
}
</style>
```

For Docker setups you can use a volume to provide this file under `/usr/share/jitsi-meet/head.html`.

**Comment by saghul** [comment]
AtlasKit is now gone.
