### ISSUE TITLE
Allow to hide the recording cloud info message

### ISSUE THREAD

**Issue by ocarreterom** [jitsi/jitsi-meet#11760]
**Is your feature request related to a problem you are facing?**
The message displayed when activating the cloud recording may be wrong since you can store the recordings on your own server.
Our users do not have to worry about JaaS limitation.

![image](https://user-images.githubusercontent.com/11599942/176365334-29a0a047-f641-4751-9a89-c6e84cd267d9.png)

> https://developer.8x8.com/jaas/v5/docs/jaas-prefs-recording
> 
> JaaS allows meeting recording, but it only stores it for 24 hours. In order to preserve the recording, you must listen for RECORDING_UPLOADED event on a [webhook](https://developer.8x8.com/jaas/v5/docs/webhooks-overview) and download the recording from the preAuthenticatedLink of the [payload](https://developer.8x8.com/jaas/v5/docs/webhooks-payload#recording_uploaded).

https://github.com/jitsi/jitsi-meet/blob/3f795cd1ffbc9cc6483acca35e2b9972d65d25b8/react/features/recording/components/Recording/StartRecordingDialogContent.js#L280

**Describe the solution you'd like**
Allow to hide the info message from the config.

**Comment by saghul** [comment]
Are you using your own deployment? What config options did you set in config.js ?

**Comment by ocarreterom** [comment]
I am using [8x8 JaaS](https://jaas.8x8.vc/#/) with [webhooks](https://developer.8x8.com/jaas/v5/docs/webhooks-events) to copy the recording to AWS S3.

**Comment by saghul** [comment]
Can you raise a support ticket please?

**Comment by ocarreterom** [comment]
Ok, I'm going to create a support ticket. Thanks.

**Comment by saghul** [comment]
Ping @robertpin

**Comment by ocarreterom** [comment]
Thanks for updating the config.js! 8x8 will work on this issue to allow hiding the message. For now I will overwrite the config.js in frontend when the next version is released.

You can close this issue 👍 

Thanks.

**Comment by saghul** [comment]
It will be part of the next 8x8.vc deployment.

**Comment by ocarreterom** [comment]
@saghul I am overriding config.js to hide the storage warning but It's not working.

```js
new JitsiMeetExternalAPI('', {
  configOverwrite: {
    recordingService: {
      hideStorageWarning: true
    }
  }
})
```

Is the error at this line?
https://github.com/jitsi/jitsi-meet/blob/94074836ec3a5c8c184310938bca81dd42d1e36d/react/features/recording/components/Recording/StartRecordingDialogContent.js#L766

Should be `recordingService?` instead of `recording?`?
https://github.com/jitsi/jitsi-meet/blob/94074836ec3a5c8c184310938bca81dd42d1e36d/config.js#L291-L305

**Comment by saghul** [comment]
Sigh, looks like we forgot to whitelist that setting.

**Comment by saghul** [comment]
Fix: https://github.com/jitsi/jitsi-meet/pull/11938
