### ISSUE TITLE
CocoaPods could not find compatible versions for pod "PromisesObjC"

### ISSUE THREAD

**Issue by wfleischer** [jitsi/jitsi-meet#11766]
### Description:

I get a `CocoaPods could not find compatible versions for pod "PromisesObjC"` error when running pod install.

### Steps to reproduce:

1. Checkout master
2. Run `npm install` and in the `ios` dir run `pod install`

### Expected behavior:

Pod dependencies should be installed.

### Actual behavior:

This error message is thrown:

```
[!] CocoaPods could not find compatible versions for pod "PromisesObjC":
  In snapshot (Podfile.lock):
    PromisesObjC (< 3.0, = 2.1.1, >= 1.2)

  In Podfile:
    Firebase/Analytics (~> 8.0) was resolved to 8.15.0, which depends on
      Firebase/Core (= 8.15.0) was resolved to 8.15.0, which depends on
        FirebaseAnalytics (~> 8.15.0) was resolved to 8.15.0, which depends on
          GoogleUtilities/AppDelegateSwizzler (~> 7.7) was resolved to 7.7.0, which depends on
            GoogleUtilities/Environment (= 7.7.0) was resolved to 7.7.0, which depends on
              PromisesObjC (< 3.0, >= 1.2)

None of your spec sources contain a spec satisfying the dependencies: `PromisesObjC (< 3.0, = 2.1.1, >= 1.2), PromisesObjC (< 3.0, >= 1.2)`.
```

### Server information:

- Jitsi Meet version: master
- Operating System: macOS on Apple Silicon

### Solution:

Setting `PromisesObjC` to version `2.1.0` in Podfile.lock (instead of `2.1.1`) fixes the issue for me. Do you want me to submit a PR?

**Comment by wfleischer** [comment]
btw: thanks @alexbumbu, for https://github.com/jitsi/jitsi-meet/pull/11750, fixing running the native app in the simulator!

**Comment by saghul** [comment]
Can you try to do `pod install --repo-update` ?

**Comment by saghul** [comment]
Ops, sorry for closing, wrong button!

**Comment by wfleischer** [comment]
> Can you try to do `pod install --repo-update` ?

Thank you @saghul! This works and I see why. Sorry for the noise /o\\.

**Comment by saghul** [comment]
🚀
