### ISSUE TITLE
An option to disable low bandwidth mode

### ISSUE THREAD

**Issue by bitinn** [jitsi/jitsi-meet#11771]
**Is your feature request related to a problem you are facing?**

- I recently had a few meetings with teams in US and EU, while I am based in China.
- Jitsi Meet app on iOS detects my bandwidth and locks itself under low bandwidth mode.
- But I am pretty certain I have sufficient bandwidth for video and screen sharing.
- Google Meet, Skype, Youtube etc. runs fine for me, as my VPN were pretty decent.

**Describe the solution you'd like**

- I would like to disable this automatic low bandwidth mode altogether on iOS.

**Describe alternatives you've considered**

- Maybe I am not whitelisting enough traffic, but `meet.jitsi.net` requests are all I have seen.
- I would have to switch back to Google Meet.

**Comment by saghul** [comment]
When you say it "locks itself in low bandwidth mode" did you enable low bandwidth mode, or do you mean the general adaptation to available network conditions? The former is an option you can control in the menu, but the latter is a server setting.

**Comment by bitinn** [comment]
@saghul can you explain which one this is?

![IMG_4602](https://user-images.githubusercontent.com/1484279/176854124-45b096b8-9f3a-4ff4-a88f-c3b7f290fcb4.jpg)

**Comment by saghul** [comment]
That's the former, the manual audio only / low bandwidth mode.

You can tap on the ... menu and disable it.

**Comment by bitinn** [comment]
@saghul could you show a screenshot where that is? I certainly didn't enable this myself and pressing the green button does nothing for me.

**Comment by saghul** [comment]
What version of the app are you using? The previous one used to have an "audio / video" toggle switch on the first screen. We have redone an UI in the latest release.

This is the option you want to toggle:

![image](https://user-images.githubusercontent.com/317464/176890091-ac34668c-521e-4956-afc8-e334de968281.jpeg)

**Comment by saghul** [comment]
What version of the app are you using? The previous one used to have an "audio / video" toggle switch on the first screen. We have redone an UI in the latest release.

This is the option you want to toggle:

![image](https://user-images.githubusercontent.com/317464/176890091-ac34668c-521e-4956-afc8-e334de968281.jpeg)

**Comment by bitinn** [comment]
ok found it but I wasn't using the latest release in my last meeting. Also in my case, even though I have explicitly not click the low bandwidth mode button, the meeting still starts in low bandwidth mode. This is not something I enabled myself otherwise I would have known where the option was.

**Comment by saghul** [comment]
In the previous version it was enabled also when you started a meeting with the switch in the "audio" position. The app never enables this mode automatically.

**Comment by bitinn** [comment]
Which menu, could you show me a screenshot because I certainly cannot get out of this mode on iOS? I didn’t activate it myself, clicking on the green button does nothing.

**Comment by saghul** [comment]
Press the "3 dots" button and then the option I mentioned in https://github.com/jitsi/jitsi-meet/issues/11771#issuecomment-1172268135 allows you to toggle it.
