### ISSUE TITLE
Is It possible when Internet goes for some time we should not disconnect from room ?

### ISSUE THREAD

**Issue by erasingla20** [jitsi/jitsi-meet#11772]
**Is your feature request related to a problem you are facing?**
when 2 persons are on call ,when 1 person internet lose it should go outside the room 

**Describe the solution you'd like**
when 2 persons are on call ,when 1 person internet lose it should not go outside the room .

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

When the interruption is less than a minute, the connection should recover. If more than a minute there is no way to recover as serverside sessions had expired and reload is scheduled.

**Comment by erasingla20** [comment]
@damencho When the interruption is less than a minute and connection should recover but reload happens in mobile.but In web reload not happens.Can you suggest a way to stop reloading in mobile?

**Comment by damencho** [comment]
@saghul do you know why is that? We always try to reconnect bosh on web and only when we receive item-not-found (in case the session is expired) we do a reload, I guess the reason on mobile is not bosh, but something else?

**Comment by saghul** [comment]
Not sure. Maybe we broke something since we only use BOSH on mobile? It's possible we are able to detect the disconnect faster, and we actually timeout 3 times.

I can test and check next week.
