### ISSUE TITLE
F-Droid: App icon not available

### ISSUE THREAD

**Issue by hamishmb** [jitsi/jitsi-meet#11786]
### Description:

The application icon is not on F-Droid, which makes it hard to find, and also decreases confidence that this is an official app.

### Steps to reproduce:

N/A

### Expected behavior:

As above.

### Actual behavior:

F-Droid should have the application icon.

### Client information:

- App version: 22.2.0 build 222000
- Operating System: Android 11

### Additional information:

N/A

**Comment by saghul** [comment]
You need to file this request on F-Droid, since we don't make the builds.

If an icon needs to be placed somewhere, happy to do that, but we need to be told where.

**Comment by licaon-kter** [comment]
F-Droid can't extract some types of newer icons, .xml iirc.

So the current recommended setup is to have, in source repe eg. here, a [Fastlane](https://gitlab.com/-/snippets/1895688) or [Triple-T](https://gitlab.com/-/snippets/1901490) type of folder structure _(no tooling needed)_ which can hold screenshots, description, changelog, banner, summary and... icon. But you do have some Fastlane stuff, unfortunately it's not in the right place.

Would a PR be accepted?

Ref: https://forum.f-droid.org/t/applications-icons-not-visible-in-f-droid/18955

**Comment by saghul** [comment]
Sure thing!

**Comment by hamishmb** [comment]
Okay, guess we should open this again - I will eventually probably do a PR if no one else does.

**Comment by licaon-kter** [comment]
Did I miss the positive answer here? Odd... brb
