### ISSUE TITLE
screenshare crash！with 3 more person

### ISSUE THREAD

**Issue by aylitat** [jitsi/jitsi-meet#11780]
when I use jitsi meet with chrome ,then using screenshare .
it  worked well, when only two people in room.
when the 3rd one comes in,screenshare crashed with blackscreen...
I dont know why?

**Comment by saghul** [comment]
Please share the browser console logs. Did this happen in meet.jit.si or a different deployment?

**Comment by aylitat** [comment]
when I use 3 phones in room
![image](https://user-images.githubusercontent.com/48346244/177730536-ba647781-a270-49c6-9692-ab879aa3f5a6.png)
![image](https://user-images.githubusercontent.com/48346244/177730578-6570ca22-1918-4569-917c-ecc3774cc498.png)

**Comment by aylitat** [comment]
> Please share the browser console logs. Did this happen in meet.jit.si or a different deployment?

and I don't know how to edit this file
![A5I1SS65BL2))~F CB5UX9N](https://user-images.githubusercontent.com/48346244/177730905-a1cff984-69e1-41e7-994c-934513b0f2b3.png)

**Comment by aylitat** [comment]
> Please share the browser console logs. Did this happen in meet.jit.si or a different deployment?

I use the docker self-serve

**Comment by aylitat** [comment]
I did this following steps
https://community.jitsi.org/t/solved-screen-sharing-not-working-for-3-or-more-participants/96319/10
but I used a docker program
so I don't know hot to edit and it doesn't work

**Comment by saghul** [comment]
You seem to have  some bad configuration. You can't seem to connect to the JVB. I see you are testing on localhost, so not a real setup. Can you share your .env file?

**Comment by saghul** [comment]
Also, I have never tested our Docker setup on Windows, FWIW.
