### ISSUE TITLE
Jitsi is not working 

### ISSUE THREAD

**Issue by vishnushelar** [jitsi/jitsi-meet#11789]
Hi,

We have installed jitsi on oracle cloud as per your instructions (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart). But it is not working properly when user starts their meeting. We have not made any application level changes. We are using installed version as it is. Please check attached screen shots and test cases. Let us know if we are missing anything while doing configuration.

Testing : on oracle cloud

Test case :-1
server configuration : 1 OCPU (2vVPCU) with 8 GB Ram 1 GBP Bandwidth
Issue: Jitsi not working with more than 1 user . Users automatically exited.

Test case :-2
server configuration : 2 OCPU (2vCPU) with 32 GB Ram 2 GBP Bandwidth
Issue: Multiple users are able to join the meeting but unable to listen each other, video calling also not working. Although users are in unmute state but it still showing muted on Jitsi portal

Test case :-3
server configuration : 4 OCPU (2vCPU) with 64 GB Ram 4 GBP Bandwidth
Issue: 
Check following attached screenshots, where 2 users have joined a meeting. Camera and microphone is ON for both the users, but non of them are able to hear and see to each other.

<img width="1440" alt="User 1" src="https://user-images.githubusercontent.com/5018918/177270476-8646d577-40e3-449a-9525-210e74b1ddd7.png">
<img width="1440" alt="User 2" src="https://user-images.githubusercontent.com/5018918/177270489-510541be-7f23-450c-ac6f-698e3ebfd27d.png">

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Make sure the firewall is open for port udp 10000, and that port is forwarded to the machine hosting the videobridge.

https://community.jitsi.org/t/tip-how-to-check-udp-10000-connectivity/73031
