### ISSUE TITLE
Single-key shortcuts are the devil

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet#11788]
This was originally logged as https://github.com/jitsi/jitsi-meet-electron/issues/712 so it's not quite constructed according to the https://github.com/jitsi/jitsi-meet/ template.  I hope what's here is sufficiently clear as-is.

## Description

Not having the chat input selected (but thinking it is) can result in all sorts of mischief, when one starts typing a comment, because single-key shortcuts are triggered... turning sound and/or video on and/or off, among other things.

## Current behavior

Typing various single keys causes **Jitsi Meet.app** (a/k/a [**`jitsi-meet-electron`**](https://github.com/jitsi/jitsi-meet-electron/)) to take unintended actions 

## Expected Behavior

Require key-chords, i.e., one or more modifier keys (i.e., alt/option/`⌥`, shift/`⇧`, command/`⌘`, control/`^`) *plus* the key that triggers the action. (Trigger keys might differ from the current shortcut list where there is overlap with standard shortcuts, e.g., `⌘-V` should be disallowed from shortcut list, as it is all-but-globally `PASTE`)

## Possible Solution

Implement key-chords for all keyboard shortcuts

## Steps to reproduce

Deselect the chat text-entry box, and type some words.  See what actions *you* accidentally trigger!

# Environment details

Latest **Jitsi Meet.app** (`2022.1.1`) on macOS Sierra 10.12.6 (16G2136)

**Comment by TallTed** [comment]
Auto-staling and auto-closing issues is also evil. Lack of activity doesn't indicate that the issue has been fixed, which *should* be the trigger for such closure.

**Comment by saghul** [comment]
We are not going to change our shortcuts, sorry. They have been there for too long to change them now and would disrupt too many users and customers.

What we have done is check that no modifier keys are pressed in order to avoid detecting them in case a system shortcut is used: https://github.com/jitsi/jitsi-meet/commit/8acce9a2f5350265d01a85e1cf99935c721c34bf

If any modifier is missing please do open an issue about that.

**Comment by TallTed** [comment]
I'm pretty sure I've never had a system shortcut captured by Jitsi Meet.app, so I'm not sure how that's supposed to be a useful response to my issue.

My major issue shows up when the chat is open (and less frequently, when it's closed) and I think I'm typing *there*, but for some reason (there appear to be multiple possible), the cursor is not in that input box, and instead my rapid typing takes multiple app actions without any confirmation or undo, nor even any way to know what actions I've just taken.

Maybe the modifier-less shortcuts could be (possibly switchable via a user preference) disabled when the chat box is open?

Maybe a user preference could be added, which adds a modifier requirement (possibly always the same modifier, if any would have no collisions with other chords; possibly adjusting to dodge such collisions when they occur; possibly entirely user configurable, action by action, within the app) to every otherwise modifier-free shortcut?

You could even make every shortcut user-configurable ([at least, every one that corresponds to a menu item, as they really all should](https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/10.14/mac/10.14)).
