### ISSUE TITLE
Jicofo error when one videobrige is down. Room and participants are nor reionvited to another jvb.

### ISSUE THREAD

**Issue by rchaconmolero** [jitsi/jitsi-meet#11798]
### Description:

Room is created in one Jitsi videobridge. When this server is down, room and participants are not automatically created in another videobridge.

Jicofo.log registers this lines:

Jicofo 2022-07-06 10:49:15.791 INFO: [85] [type=bridge brewery=jvbbrewery] BaseBrewery.removeInstance#353: Removed brewery instance: jvbbrewery@internal.auth.video.local/video2-jvb2
Jicofo 2022-07-06 10:49:15.793 INFO: [85] BridgeSelector.removeJvbAddress#114: Removing JVB: jvbbrewery@internal.auth.video.local/video2-jvb2
Jicofo 2022-07-06 10:49:15.793 INFO: [37] JvbDoctor.bridgeRemoved#103: Stopping health-check task for: Bridge[jid=jvbbrewery@internal.auth.video.local/video2-jvb2, version=2.2.9-g8cded16e, relayId=null, region=null, stress=0.00]
Jicofo 2022-07-06 10:49:15.794 INFO: [37] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.removeBridge#492: Removing bridges: Bridge[jid=jvbbrewery@internal.auth.video.local/video2-jvb2, version=2.2.9-g8cded16e, relayId=null, region=null, stress=0.00]
Jicofo 2022-07-06 10:49:15.794 INFO: [37] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.removeParticipantInfosBySession#151: Removing session with no remaining participants: Colibri2Session[bridge=video2-jvb2, id=eb9bc1c7-417c-44ba-9678-9d916fd8f0e2]
Jicofo 2022-07-06 10:49:15.798 SEVERE: [88] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154 bridge=video2-jvb2] ExtensionsKt.sendIqAndLogResponse$lambda-17#162: Received an unexpected colibri2 response: <iq xmlns='jabber:client' to='focus@auth.video.local/focus' from='jvbbrewery@internal.auth.video.local/video2-jvb2' id='D3RLC-72' type='error'><error type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Recipient not in room</text></error></iq>
Jicofo 2022-07-06 10:49:15.798 INFO: [37] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.removeBridge#497: Removed participants: [org.jitsi.jicofo.conference.colibri.v2.ParticipantInfo@7016bc9b, org.jitsi.jicofo.conference.colibri.v2.ParticipantInfo@7dc4dec7]
Jicofo 2022-07-06 10:49:15.798 INFO: [37] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] JitsiMeetConferenceImpl$BridgeSelectorEventHandler.bridgeRemoved#1976: Removed jvbbrewery@internal.auth.video.local/video2-jvb2, re-inviting [1fb25e44, 9ba6c2e9]
Jicofo 2022-07-06 10:49:15.802 INFO: [37] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.updateParticipant#463: Updating Participant[sala1@conference.video.local/1fb25e44]@1972955557 with transport=null, sources={}
Jicofo 2022-07-06 10:49:15.806 INFO: [37] AbstractOperationSetJingle.terminateSession#509: Terminate session: sala1@conference.video.local/1fb25e44, reason: success, send terminate: true
Jicofo 2022-07-06 10:49:15.807 INFO: [88] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.allocate#252: Allocating for 1fb25e44
Jicofo 2022-07-06 10:49:15.807 INFO: [37] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.updateParticipant#463: Updating Participant[sala1@conference.video.local/9ba6c2e9]@2137031381 with transport=null, sources={}
Jicofo 2022-07-06 10:49:15.807 INFO: [37] AbstractOperationSetJingle.terminateSession#509: Terminate session: sala1@conference.video.local/9ba6c2e9, reason: success, send terminate: true
**Jicofo 2022-07-06 10:49:15.808 SEVERE: [88] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154 participant=1fb25e44] ParticipantInviteRunnable.run#174: Channel allocator failed:
java.lang.IllegalStateException: participant already exists
        at org.jitsi.jicofo.conference.colibri.v2.ColibriV2SessionManager.allocate(ColibriV2SessionManager.kt:260)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.doRun(ParticipantInviteRunnable.java:204)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.run(ParticipantInviteRunnable.java:170)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2022-07-06 10:49:15.808 INFO: [88] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154] ColibriV2SessionManager.allocate#252: Allocating for 9ba6c2e9
Jicofo 2022-07-06 10:49:15.808 SEVERE: [88] [room=sala1@conference.video.local meeting_id=7e06392c-f3ac-491a-bd52-681158582154 participant=9ba6c2e9] ParticipantInviteRunnable.run#174: Channel allocator failed:
java.lang.IllegalStateException: participant already exists
        at org.jitsi.jicofo.conference.colibri.v2.ColibriV2SessionManager.allocate(ColibriV2SessionManager.kt:260)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.doRun(ParticipantInviteRunnable.java:204)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.run(ParticipantInviteRunnable.java:170)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)**
^C

### Steps to reproduce:

1.  Create a conference with 2 or more users.
2.  stop jitsi videobridge service or powerdown the server. Regardless of the server. The error occurs in both cases.

### Expected behavior:
In a few seconds users continue de conference with no break or problems. Test with versio actually in production (Jitsi-meet                           2.0.6433-1), with no problem.

### Actual behavior:
Video and Audio stop and users have to enter newly.

### Server information:
video.local:
- Jitsi Meet version:
 jicofo                               1.0-900-1
 jitsi-meet                         2.0.7439-1
 jitsi-meet-prosody          1.0.6260-1
 jitsi-meet-turnserver       1.0.6260-1
 jitsi-meet-web                 1.0.6260-1
 jitsi-meet-web-config     1.0.6260-1
 jitsi-videobridge2            2.2-9-g8cded16e-1

video2-jvb2: 
jitsi-videobridge2            2.2-9-g8cded16e-1

- Operating System:
Description:    Ubuntu 20.04.3 LTS
Release:        20.04

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Ping @bgrozev ?
