### ISSUE TITLE
When Screen sharing is turned on/off . The user's camera is automatically mirrored (currently)

### ISSUE THREAD

**Issue by yakupseker** [jitsi/jitsi-meet#11791]
### Description:

When Screen sharing is turned on/off . The user's camera is automatically mirrored (currently)

### Steps to reproduce:

1. Moderator starts a meeting.
2. Moderator starts screen sharing.
3. Moderator stop screen sharing.
4. The user's camera is automatically mirrored (currently)

### Expected behavior:

Camera does not open.

### Actual behavior:

When Screen sharing is turned on/off . The user's camera is automatically mirrored (currently)

### Server information:

- Jitsi Meet version: 2.0
- Operating System: Windows

### Client information:

- Browser / app version: Chrome 99.xx
- Operating System: Windows 10

**Comment by JustCryen** [comment]
Do you mean that when you're not using a camera, after you start screen sharing the camera automatically turns on?
Because that's what happens in my case.

**Comment by yakupseker** [comment]
Exactly

**Comment by saghul** [comment]
Do you observe the same behavior in meet.jit.si ?

**Comment by yakupseker** [comment]
Sorry for my late return.
I didn't live with Jitsi 7648 stable version.

**Comment by saghul** [comment]
So, do you no longer see the bug?

**Comment by saghul** [comment]
This has already been fixed.
