### ISSUE TITLE
Salesforce Integration

### ISSUE THREAD

**Issue by kutayinclr** [jitsi/jitsi-meet#11793]
Hello,

I was checking the source code to customize SDK while doing that I noticed there is salesforce API integration in the source code. 

When I checked the documentation I couldn't find any resource describing how to integrate type info.

First I noticed there is _salesforceUrl_ in config.js after that I started tailing the source code and saw that it uses jwt token to authenticate as Bearer. So get access_token from salesforce APIs and give it try but got an error which says,

`<table cellspacing=10>
<tr><td><span style="font-weight: bold; font-size: 12pt;">URL No Longer Exists</span></td></tr>
<tr><td>You have attempted to reach a URL that no longer exists on salesforce.com. <br/><br/>

You may have reached this page after clicking on a direct link into the application. This direct link might be: <br/>
&#8226; A bookmark to a particular page, such as a report or view <br/>
&#8226; A link to a particular page in the Custom Links section of your Home Tab, or a Custom Link <br/>
&#8226; A link to a particular page in your email templates <br/><br/>
If you reached this page through a bookmark, you are probably trying to access something that has moved. Please update your bookmark. <br/>
<br/>If you reached this page through any of the other direct links listed above, please notify your administrator to update the link. <br/><br/>If you reached this page through a link on our site, please <a href="/cases/logabug.jsp">report the broken link directly to our Support Team</a> and we will fix it promptly. Please indicate the page you were on when you clicked the link as well as any other related information. We apologize for the inconvenience. <br/><br/>Thank you again for your patience and assistance. And thanks for using salesforce.com!</td></tr>
</table>

After that started checking the endpoints to understand the problem and see that jitsiSDK is using the following as described in config file and also in the source code:

`// listing the most recent records - salesforceUrl/records/recents`
`    // searching records - salesforceUrl/records?text=${text}`
  `  // retrieving record details - salesforceUrl/records/${id}?type=${type}`
    `// and linking the meeting - salesforceUrl/sessions/${sessionId}/records/${id}`

When I check the endpoints in the Salesforce API doc I noticed that endpoints are completely different. 

So my question is, is there any other app in salesforce that I need to activate in the panel to maybe activate those endpoints? 

When will this feature will publicly available?

Thanks.

**Comment by saghul** [comment]
Ping @mihhu

**Comment by mihhu** [comment]
Hello @kutayinclr, I'm glad this code section picked your interest. It really depends on what you're seeking - for our use case, we link Salesforce records to meeting sessions.

There was some interest in open sourcing the backend side, but it's not a priority at the moment, and we can't say when it will be. So unfortunately for now this will involve building your in-house backend. These endpoints (that aren't properly documented and for that I'm at fault, sorry) are actually from our adapter service over the Salesforce API. I will link the corresponding API calls next to each other and improve the docs sometime soon:

`// listing the most recent records - salesforceUrl/records/recents`
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_recent_items.htm

`// searching records - salesforceUrl/records?text=${text}`
We use the POST method for https://developer.salesforce.com/docs/atlas.en-us.238.0.api_rest.meta/api_rest/resources_search_parameterized.htm

`// retrieving record details - salesforceUrl/records/${id}?type=${type}`
https://developer.salesforce.com/docs/atlas.en-us.238.0.api_rest.meta/api_rest/resources_sobject_basic_info_get.htm

`// and linking the meeting - salesforceUrl/sessions/${sessionId}/records/${id}`
https://developer.salesforce.com/docs/atlas.en-us.238.0.api_rest.meta/api_rest/resources_composite_graph_introduction.htm

I hope this throws a little light on this matter. Please let me know if you have further questions.
