### ISSUE TITLE
Fragment is already executing transactions on close (custom android sdk build)

### ISSUE THREAD

**Issue by hypnocill** [jitsi/jitsi-meet#11820]
I have a custom Android sdk build and it works fine but when I close the video call and navigate back from Jitsi screen to my app's previous screen, I'd get "Fragment is already executing transactions on close" (see screenshot

Any clues on how to debug that will be very helpful. Thank you!

<img width="331" alt="Screenshot 2022-07-08 at 20 20 15" src="https://user-images.githubusercontent.com/21131651/178040492-d9cdc936-26e1-4336-8ff8-c847f8264451.png">
)

**Comment by saghul** [comment]
What version are you using?

**Comment by hypnocill** [comment]
I'm using this release for my custom SDK: https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_5870
And it's required by the RN wrapper I use (https://github.com/vidit-me/react-native-jitsi-meet#readme) as 5.1.0

**Comment by hypnocill** [comment]
I found a workaround for that crash with this: https://github.com/software-mansion/react-native-screens#disabling-react-native-screens

It's not ideal for the app but it's better than a crash for now. Other solutions are welcome but if this workaround can be considered a fix, we can close this issue

**Comment by saghul** [comment]
We have stopped using the native navigator, at least for a while. Please check SDK 6.0.0.

**Comment by hypnocill** [comment]
I will, thank you. Closing this issue now
