### ISSUE TITLE
Additional setting to disable password options in security dialog and lobby page

### ISSUE THREAD

**Issue by dimitardelchev93** [jitsi/jitsi-meet#11829]
Add an additional configuration setting to jitsi-meet, when this setting has a `true` value, the lobby page "Enter meeting password" button must be hidden hidden, and there must not be a "Add password" option in security dialog.

Some meetings need to have a controlled access (with JWT tokens as an example) and having the ability to add password to the meeting is not needed or wanted.

Setting description in config.js:

```
// Disables password features
// disableMeetingPassword: false,
```

Add password option location:

![image](https://user-images.githubusercontent.com/43634401/178298690-b6152248-a892-4704-9b7e-86ee85198700.png)

Lobby password button location:

![image](https://user-images.githubusercontent.com/43634401/178298493-54205e76-6d53-402d-ad36-c393711227f8.png)

**Comment by saghul** [comment]
A PR would be welcome, disables by default of course.
