### ISSUE TITLE
Low contrast of the font colors

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#11838]
### Steps to reproduce:

1. Open meet.jit.si
2. Create a room
3. Click on the "Participants" button

### Expected behavior:

Good contrast of the font colors

### Actual behavior:

Low contrast of the font colors with poor accessibility
![c54b67c166f235263caf477c20e524a6f94e482b](https://user-images.githubusercontent.com/32515675/178466359-12192aac-86ea-4b15-a538-5da5349dc0bc.jpg)

### Server information:

- Jitsi Meet version: meet.jit.si | beta.meet.jit.si | alpha.jitsi.net
- Operating System:

### Client information:

- Browser / app version: Chrome, Firefox, Safari
- Operating System: macOS 12.4

**Comment by damencho** [comment]
Will be fixed with 
https://github.com/jitsi/jitsi-meet/pull/11822

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/139fa9b3f25ee07f7bd432dfd765fc450aea3329
Verified it on alpha jitsi net.

**Comment by jluisfa** [comment]
No fixed in Lobby mode.
Tested on alpha jitsi net
<img width="388" alt="imagem" src="https://user-images.githubusercontent.com/32515675/179204039-1351a6a9-d93b-4475-b181-14d10c2cabcc.png">
