### ISSUE TITLE
How to setup without a domain?

### ISSUE THREAD

**Issue by TheFearlessHeart** [jitsi/jitsi-meet#1183]
Hello Jitsi-meet Team
       I am a newbie who just switched to linux a few months ago and I am unsure on where to ask about setting up jitsi-meet. I am installing it on Virtualbox using the [quick install](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) method and Ubuntu 14.04. Im am able to set it up with my ip on the local network but I can not figure how access it from outside the local network. The ports are open on the router and for good measure the firewall is turned off. I have a very basic understanding of setting up apache  with a domain but no understanding on how to setup a subdomain. 
       Here is my question. Is there a way to view (and use) the jitsi server from my public ip address like a Minecraft server without a domain or at least without the subdomain (meaning I just type in example.com and the server page is the website?)?  Hopefully what I am asking makes some sense please ask me to explain differently. Are there any log or config files I need to provide?

Regards,
TheFearlessHeart    :]

Ps: I'm in college and finals are in full swing so my response time might be the day after.

**Comment by gpolitis** [comment]
You can do that for sure. Depending on how your network is configured, it might be as simple as setting the domain to be your public IP address during the installation process. Again, this depends on how your network is configured, what your port forwardings are etc. So you might have to fiddle with the configuration of the various components.

**Comment by TheFearlessHeart** [comment]
I went back and set the up the router and server again. The thing is now working. I plugged my domain in (like example.com with out and sub domain) when the install process requested it. Im sorry but its working now I think I was looking at the wrong tutorial because they didn't complete their steppes right, skipped to the demo, and then I got really confused. I sorry, user error.

**Comment by gpolitis** [comment]
Glad you got it working @TheFearlessHeart :)
