### ISSUE TITLE
Additional setting to order participants in video layouts (role, name, video, audio)

### ISSUE THREAD

**Issue by dimitardelchev93** [jitsi/jitsi-meet#11844]
Add an additional configuration setting to jitsi-meet, when this setting has values, the sorting of participants in video layouts must be in the order of the sorting criteria in the setting.

Some meetings have many participants and it sometimes is convenient to be able to see participants in a specific order.

Setting description in config.js:

```
// Specifies whether participants in video layouts should be ordered or not, and with what priority
// videoLayoutSort = [
//  'role', <- Moderators on top
//  'name', <- Alphabetically by name
//  'audio', <- Audio muted on bottom
//  'video', <- Video muted on bottom
// ] <- the order of the array elements determines priority
```

**Comment by saghul** [comment]
I don't think we want to add all that complexity, but I'll check with Product.
