### ISSUE TITLE
runtime java lang exception error unable to start service

### ISSUE THREAD

**Issue by tirumalarajajee** [jitsi/jitsi-meet#11847]
java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@2970c3f with Intent { cmp=com.kalla.neyuktadentasoft2019.conferencecall/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by tirumalarajajee** [comment]
implementation ('org.jitsi.react:jitsi-meet-sdk:6.0.0') { transitive = true }

**Comment by tirumalarajajee** [comment]
implementation ('org.jitsi.react:jitsi-meet-sdk:5.1.0') { transitive = true } working fine

**Comment by tirumalarajajee** [comment]
Tq for the great job

**Comment by saghul** [comment]
> Invalid notification (no valid small icon)

@tmoldovan8x8 should we have this set in the SDK?

**Comment by tmoldovan8x8** [comment]
I kind of feel that this should be an app thing. Maybe we could set a default one in the SDK, but the notification icon is more something the app should customise.

**Comment by saghul** [comment]
Makes sense, but why did the previous SDK work then?

**Comment by renannazar** [comment]
> I kind of feel that this should be an app thing. Maybe we could set a default one in the SDK, but the notification icon is more something the app should customise.

Excuse me, how to implement the notification icon with the android sdk? my application is also crash with that error. Thank you.

**Comment by Swapnilsimplecrm** [comment]
For Android SDK v 6.0.0

java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@8895689 with Intent { cmp=com.simplecrm.maisarahbank_test/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)

**How to fix this? please let me know**

**Comment by saghul** [comment]
You need to set an icon for the ongoing notification.

We might add a placeholder in a future version, but you likely want to customize it anyway.

**Comment by vishnu-simplecrm** [comment]
> You need to set an icon for the ongoing notification.
> 
> We might add a placeholder in a future version, but you likely want to customize it anyway.

How to do that? There is no doc available to add it from the native SDK

**Comment by spidi123q** [comment]
I found the fix, do steps below @tirumalarajajee @vishnu-simplecrm 
1. Right click on res folder in android project and choose image asset from new section
2. Create icon with following config 
  Name: `ic_notification`
  Icon Type: `Notification Icons`

**Comment by NilabhB** [comment]
> I found the fix, do steps below @tirumalarajajee @vishnu-simplecrm
> 
>     1. Right click on res folder in android project and choose image asset from new section
> 
>     2. Create icon with following config
>        Name: `ic_notification`
>        Icon Type: `Notification Icons`

This really worked, thank you so much!

**Comment by dctesaikat** [comment]
> I found the fix, do steps below @tirumalarajajee @vishnu-simplecrm
> 
> 1. Right click on res folder in android project and choose image asset from new section
> 2. Create icon with following config
>    Name: `ic_notification`
>    Icon Type: `Notification Icons`

Thanks Man 
My Error also Fixed

**Comment by itsVnp** [comment]
> 2\. ic_notification

thanks buddy
its worked for me. Fixed

**Comment by vlad909** [comment]
@spidi123q oh my god. thank you very much!!!

**Comment by ndizihiwesimon** [comment]
Am using flutter, how do I create that icon in android studio or vscode @spidi123q @vlad909 @itsVnp 
Thank you

**Comment by YashSharmaas** [comment]
> I found the fix, do steps below @tirumalarajajee @vishnu-simplecrm
> 
> 1. Right click on res folder in android project and choose image asset from new section
> 2. Create icon with following config
>    Name: `ic_notification`
>    Icon Type: `Notification Icons`

Amazing it worked
Thanks man...

**Comment by aqsashaikh88** [comment]
> Am using flutter, how do I create that icon in android studio or vscode @spidi123q @vlad909 @itsVnp
> Thank you

did you find a solution for flutter?

**Comment by SyedHuzaifaAli-1998** [comment]
@saghul its works fine after adding ic_notification icon for debug mode but When I do it on release mode or release apk its get crashed and I don't know how to provide any logcat or any error message from release mode

**Comment by saghul** [comment]
What SDK version are you using? The latest has a placeholder icon.

**Comment by SyedHuzaifaAli-1998** [comment]
> What SDK version are you using? The latest has a placeholder icon.

  jitsi_meet_wrapper: ^0.0.6


**AndroidMenifiest**
`
    <uses-sdk tools:overrideLibrary="dev.saibotma.jitsi_meet_wrapper, org.jitsi.meet.sdk, co.apptailor.googlesignin, com.calendarevents, com.reactnativecommunity.asyncstorage, com.reactnativecommunity.netinfo, com.rnimmersive, com.corbt.keepawake, com.BV.LinearGradient, com.horcrux.svg, com.oney.WebRTCModule, com.ocetnik.timer, com.kevinresol.react_native_default_preference, com.learnium.RNDeviceInfo, com.amplitude.reactnative, com.reactnativegooglesignin, com.reactnativecommunity.clipboard, com.swmansion.gesturehandler.react, org.linusu, org.reactnative.maskedview, com.reactnativepagerview, com.oblador.performance, com.swmansion.reanimated, com.th3rdwave.safeareacontext, com.swmansion.rnscreens, com.reactnativecommunity.slider, org.devio.rn.splashscreen, com.brentvatne.react, com.reactnativecommunity.webview"/>

        <meta-data
            android:name="com.gunschu.jitsi_meet_example"
            android:resource="@mipmap/ic_launcher" />`


app\build.gradle

`    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.CalkTalk"
        // You can update the following values to match your application needs. 
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 24
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
//        multiDexEnabled true
    }



    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            xxxx.xxxxx.xxxxx.xxxxxx

//            runProguard false

//            minifyEnabled true
//            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }`

**Comment by SyedHuzaifaAli-1998** [comment]
`    <uses-sdk tools:overrideLibrary="dev.saibotma.jitsi_meet_wrapper, org.jitsi.meet.sdk, co.apptailor.googlesignin, com.calendarevents, com.reactnativecommunity.asyncstorage, com.reactnativecommunity.netinfo, com.rnimmersive, com.corbt.keepawake, com.BV.LinearGradient, com.horcrux.svg, com.oney.WebRTCModule, com.ocetnik.timer, com.kevinresol.react_native_default_preference, com.learnium.RNDeviceInfo, com.amplitude.reactnative, com.reactnativegooglesignin, com.reactnativecommunity.clipboard, com.swmansion.gesturehandler.react, org.linusu, org.reactnative.maskedview, com.reactnativepagerview, com.oblador.performance, com.swmansion.reanimated, com.th3rdwave.safeareacontext, com.swmansion.rnscreens, com.reactnativecommunity.slider, org.devio.rn.splashscreen, com.brentvatne.react, com.reactnativecommunity.webview"/>
`

`        <meta-data
            android:name="com.gunschu.jitsi_meet_example"
            android:resource="@mipmap/ic_launcher" />`



`    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.CalkTalk"
        // You can update the following values to match your application needs. 
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 24
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
//        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

//            runProguard false

//            minifyEnabled true
//            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }`

> What SDK version are you using? The latest has a placeholder icon.

**Comment by SyedHuzaifaAli-1998** [comment]
From Where I Can Find That
I just followed the documentation of it
[https://pub.dev/packages/jitsi_meet_fix](url)
I didn't do anything for iOS I just need to deliver The android right now as soon as possible

**Comment by saghul** [comment]
You need to ask the plugin authors, we didn't write it.
