### ISSUE TITLE
[IOS] Native PIP Not working

### ISSUE THREAD

**Issue by SindhujaKanukolanu** [jitsi/jitsi-meet#11843]
I have updated JitsiSDK with latest PIP changes. PIP is not working at all. Are there any properties need to be set?
This is the latest commit i consumed for PIP
https://github.com/jitsi/jitsi-meet/commit/7f2fec756d8095000dd6976e2cc4f6906cf9d32e

**Comment by saghul** [comment]
We have released SDK 6.0.0, please test that release.

**Comment by SindhujaKanukolanu** [comment]
I have added below code by incorporating latest changes. Jitsi meet view delegate is not calling the methods. Please let me know if anything is missing
```
let sampleBufferVideoCallView = SampleBufferVideoCallView()
      sampleBufferVideoCallView.sampleBufferDisplayLayer.preventsCapture = false
      pipVideoCallViewController = AVPictureInPictureVideoCallViewController()
      pipVideoCallViewController?.preferredContentSize = CGSize(width: 500, height: 500)
      pipVideoCallViewController?.view.addSubview(sampleBufferVideoCallView)
      let pipContentSource = AVPictureInPictureController.ContentSource(activeVideoCallSourceView: jitsiMeetView,contentViewController: pipVideoCallViewController!)

      pipController = AVPictureInPictureController(contentSource: pipContentSource)
      pipController?.canStartPictureInPictureAutomaticallyFromInline = true
      pipController?.delegate = self
      DispatchQueue.main.async {
        self.pipController?.startPictureInPicture()
      }
```

**Comment by SindhujaKanukolanu** [comment]
Okay thanks for the update

**Comment by saghul** [comment]
It is in our roadmap, yeah.

**Comment by SindhujaKanukolanu** [comment]
Any timeline update you can give

**Comment by saghul** [comment]
Not at the moment, sorry.

**Comment by MahmoudMamdoouh** [comment]
Hello,
 is there any progress in this issue

**Comment by saghul** [comment]
We are not aware of any PiP issues on our latest SDK, 7.0.0.

Can you reproduce the problem with the sample app?

**Comment by MahmoudMamdoouh** [comment]
I meant the ios pip outside the app

**Comment by saghul** [comment]
Ah no, sorry. We tried it but we need to implement it se lowest level, in the WebRTC plugin, so it went back to the TODO list.

**Comment by MahmoudMamdoouh** [comment]
is there any expected time for it?

I really appreciate your hard work.

**Comment by saghul** [comment]
I'll be honest: no there isn't.

Thanks for your kind words!

**Comment by tmbiOS** [comment]
@saghul Hi! Any updates? Or when do you plan to integrate this feature?

**Comment by saghul** [comment]
No updates. We have no short term plans to tackle this, sorry.
