### ISSUE TITLE
Watermark getting displayed even though the configuration is set to false. 

### ISSUE THREAD

**Issue by AkshayNakraEverest** [jitsi/jitsi-meet#11853]
### Description:
The watermark is getting displayed (8*8) even though SHOW_JITSI_WATERMARK is set to false in the interfaceConfigOverwrite. 
        interfaceConfigOverwrite: {
            SHOW_JITSI_WATERMARK: false,
            SHOW_WATERMARK_FOR_GUESTS: false,
        },

### Expected behavior:
The watermark was not shown until yesterday and today it started to show up. 

### Actual behavior:
The watermark should disappear. 

### Server information:

- Jitsi Meet version: Using Jitsi as a Service

### Client information:

- Browser / app version: Firefox/Chrome
- Operating System: MacOs/Windows

**Comment by saghul** [comment]
We noticed and rolled back the release. We are in the process of fixing it. It should be working now since we rolled back the last update. Sorry about the trouble.

**Comment by saghul** [comment]
This is fixed now.
