### ISSUE TITLE
Firefox will not playback Jitsi Meet interface `wav` files under the default configuration.

### ISSUE THREAD

**Issue by BinaryWizard904** [jitsi/jitsi-meet#11860]
### Description:

As with `wasm`, nginx does not include a mimetype mapping for `wav` files in it's default mime.types file.  Nor does Jitsi Meet provide this mapping in the default nginx configuration files.  This results in Firefox refusing to load `wav` files, decreasing the user experience as Jitsi Meet uses some wavs in it's interface (the chat notification sound for example).  A simple workaround is to include the `audio/wav    wav;` mimetype mapping alongside the `wasm` one, whereupon Firefox happily loads and plays back these files.

I think it would go here.
https://github.com/jitsi/jitsi-meet/blob/39793110b68da40dd82626b9d4f5f568fb156d5b/doc/debian/jitsi-meet/jitsi-meet.example#L3-L6

### Steps to reproduce:

1. Open a developer console in firefox
2. Navigate to a Jitsi Meet instance.
3. Note that you receive warning messages like: `HTTP “Content-Type” of “application/octet-stream” is not supported. Load of media resource https://meet.example.com/sounds/incomingMessage.wav failed.`
4. Start a meeting.
5. Have another participant join the meeting and send you a chat message.
6. Note that you do not hear the `incomingMessage.wav` sound.

### Expected behavior:

Firefox can load and playback standard Jitsi Meet sounds that are stored in wav files.

### Actual behavior:

Firefox GETs but does not load Jitsi Meet `wav` files.

### Server information:

- Jitsi Meet version: 2.0.7439-1
- Operating System: Debian 11 (bullseye)

This is a Fresh Debian 11 Minimal VM.  Jitsi Meet was installed per [instructions](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) in the Jitsi Handbook.  Nginx was installed and configured automatically by the Jitsi Meet installation process.

### Client information:

- Browser / app version: Firefox 102.1
- Operating System: Windows 10 Pro (21H1)

**Comment by saghul** [comment]
I am unable to reproduce this on meet.jit.si. I wonder if it's because our nginx is configured like so, or because more recent nginx versions have it builtin.

**Comment by BinaryWizard904** [comment]
Going by the [mime.types](http://hg.nginx.org/nginx/file/tip/conf/mime.types) file in nginx's repo, it is sill missing from the latest version of nginx.

I do not know how nginx is setup on the meet.jit.si instance, but when I visit the meet.jit.si website the Firefox Network log shows that the downloaded wav files are properly typed as x-wav.  So the mime.type is certainly defined on that instance.

**Comment by JonathanLennox** [comment]
We actually serve files on meet.jit.si from a CDN - if you check the console network log you'll see that the message is loaded from https://web-cdn.jitsi.net/meetjitsi_6330.3057/sounds/incomingMessage.wav, which isn't being served from nginx.

**Comment by BinaryWizard904** [comment]
@saghul, PR created.
