### ISSUE TITLE
Jitsi meet requires a lot of GPU power when screen sharing

### ISSUE THREAD

**Issue by Crown0815** [jitsi/jitsi-meet#11878]
### Description:

Jitsi eats up 3D computation power of graphics card when screen sharing. I am a little surprised by that, since the shared screen is (only) a Full-HD screen. There are two other screens present (one Full-HD and one 4K) but those were not shared. I was a little surprised by how strongly the GPU was utilized, and it made working together with the shared screen a strong pain. Is this maybe related to the [recent adjustments made to the screen sharing](https://community.jitsi.org/t/screen-share-quality-in-the-end-of-2021/106176)?

### Steps to reproduce:

1. Open Jitsi Meets room;
2. Share Screen.

(settings set to 5 FPS for sharing)
![image](https://user-images.githubusercontent.com/36126706/179746357-94c68b8e-04cc-4d8c-a85e-493c1228524a.png)

### Expected behavior:

Moderate usage.

### Actual behavior:

Clogged GPU

### Server information:

- Jitsi Meet version: https://meet.jit.si

### Client information:

- Browser / app version: Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)
- Operating System: Windows 10 

### Additional information:

* I was alone in the room on https://meet.jit.si, no other participants.
* The `Desktop Window Manager` was the main process associated with the GPU usage (far more than 50% of GPU usage)
* Screenshot from task manages with marked `start` and `end` of the screen sharing session:

![image](https://user-images.githubusercontent.com/36126706/179747291-2a39b64d-0e1e-4860-a83f-605e730795b2.png)

**Comment by Crown0815** [comment]
Not with Jitsi itself, but the actual program I am sharing become slow and sometimes even the mouse stutters and hangs. As context, we were using Jitsi for remote pair-programming (no shared control, only shared screen).

**Comment by saghul** [comment]
Can you reproduce this behavior with Google Meet for example?
