### ISSUE TITLE
On Android, response to org.jitsi.meet.RETRIEVE_PARTICIPANTS_INFO intent is not legal json

### ISSUE THREAD

**Issue by shaulr** [jitsi/jitsi-meet#11895]
I send the intent:

```
Intent participantsIntent = new Intent( "org.jitsi.meet.RETRIEVE_PARTICIPANTS_INFO");
intent.putExtra("requestId ", "myId");
LocalBroadcastManager.getInstance( this ).sendBroadcast( participantsIntent );
```

This is nearly json I get in response:
`{participantsInfo=[{participantId=3e9fe448, name=viewing, role=moderator, isLocal=true}, {participantId=e6353c2b, name=sharing, role=moderator, isLocal=false}]}`
It is missing quotes.

I tried using ParticipantInfoService, it is broken because of the same bug, it fails to parse JSON from the response.

**Comment by Ahmad-Mustafaa** [comment]
> ParticipantInfoService

If you found any solution Please share with us as well.
