### ISSUE TITLE
Share a part of the screen of a specific application

### ISSUE THREAD

**Issue by dieg467** [jitsi/jitsi-meet#11898]
Hello. Is it planned so that, in the future, only a part of the screen of a specific third-party application selected by the user can be shared? Something similar does "Zoom", by sharing a part of the screen, but it shares everything that appears in that part of the screen, and I only want to share a part of the screen of a specific application. The use I give it is for virtual classes and I don't like that when sharing the screen all the commands, buttons, options, etc. of the shared application are seen. I just want guests to see the active screen where the content I want to share is. Thank you very much.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Jitsi-meet uses webrtc and its browser implementation that is responsible for selecting screen and sharing. What you want is not possible with the current implementation of the browsers, so there is nothing we can do about it.

**Comment by saghul** [comment]
This exists now, but it's Chrome only and behind an origin trial: https://developer.chrome.com/docs/web-platform/region-capture/

If it moves forward we'll likely end up adopting it I suppose.

**Comment by dieg467** [comment]
Thank you very much for the answers!
