### ISSUE TITLE
Add keyboard shortcuts support.

### ISSUE THREAD

**Issue by fouksf** [jitsi/jitsi-meet#119]
Add support for keyboard shortcuts like ctrl + <number> for showing the n-th video and ctrl + m for muting the microphone.

**Comment by tamlyn** [comment]
Seeing as this comes top for a search of "jitsi keyboard shortcuts", it might be worth noting that you can view the currently supported keyboard shortcuts by typing <kbd>?</kbd> while in Jitsi.
