### ISSUE TITLE
Bring back the moderator indicator

### ISSUE THREAD

**Issue by angelaki** [jitsi/jitsi-meet#11905]
After some time I've lately updated my Jitsi-Setup. As far as I can see the moderator indicator (star) is missing. Is this correct? I have found no option to re-enable it.

**Comment by saghul** [comment]
You should be able to enable it by setting this to false: https://github.com/jitsi/jitsi-meet/blob/2f42af0b70426a6b9a5993d08e41eca28087e184/config.js#L102

**Comment by angelaki** [comment]
Ups ... Thank you so much! And sorry for circumstances!
