### ISSUE TITLE
Javascript Error in Firefox esr (102.0.1)"TypeError: Da.attachMediaStream is not a function"

### ISSUE THREAD

**Issue by hype11** [jitsi/jitsi-meet#11924]
### Description:

When I open a meeting with firefox esr nothing appears

### Steps to reproduce:

open a meeting at https://meet.jit.si

### Expected behavior:

all buttons are visible an clickable und the video stream is visible

### Actual behavior:

nothing happens, screen is black, no video occurs, no buttons are visible

### Server information:

- Jitsi Meet version: 6380
- Operating System:

### Client information:

Firefox 102.0.1esr (64-Bit) / Windows 10 21H2
all firefox plugins was disabled

### Additional information:
StackTrace:

TypeError: Da.attachMediaStream is not a function
    attach JitsiTrack.js:309
    _attachTrack Video.js:300
    componentDidMount Video.js:200
    React 2
        ms
        Pl
    unstable_runWithPriority resemble.js:250
    React 3
        Wr
        Dl
        gl
[react-dom.production.min.js:216:187](webpack://jitsi-meet/node_modules/react-dom/cjs/react-dom.production.min.js)

componentStack: "\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886109\ndiv\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:884361\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\ndiv\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886109\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886109\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886109\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\ndiv\ndiv\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886961\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886109\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\ndiv\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:884361\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:884361\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:885779\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:886109\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:884361\n463/</</<@https://web-cdn.jitsi.net/meetjitsi_6380.3114/libs/app.bundle.min.js?v=6380.3114:138:888578"

When I test another installation at kuketz-meet.de, I can start the meeting with disabled micro and video by default, but if I want to enable video, the same javascript error occurs und meeting will be automatically canceled

**Comment by saghul** [comment]
Are you spoofing the USer Agent by any chance?

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by hype11** [comment]
sorry, I didn't see the question. I didn't spoof the user agent. all addons was disabled

**Comment by saghul** [comment]
Can you still reproduce the issue on meet.jit.si ?

**Comment by hype11** [comment]
no, thank you. Now there is no error with my Firefox ESR and everything works
