### ISSUE TITLE
Android app: main web view is not scrollable

### ISSUE THREAD

**Issue by nomadbyte** [jitsi/jitsi-meet#11931]
Running the Jitsi Meet Android app (`org.jitsi.meet_224001.apk`, from F-Droid) on Kindle Fire HD8.

The main app menu links (for example, Privacy, Terms) properly open the expected Jitsi web page within the app's view. However, the page content in the view is not scrollable as it should.

Similarly, selecting Dial-in from pop-up menu for a recent meeting, correctly displays the phone numbers. However, when in landscape mode, the content needs scrolling (also a scrollbar appears), yet the scrolling is not functional. This obscures some rows with dial-in numbers at the bottom of the list.

**Comment by saghul** [comment]
@Calinteodor PTAL when you have a chance.
