### ISSUE TITLE
Android app: in low-bandwidth mode the Android navigation bar does not auto-hide

### ISSUE THREAD

**Issue by nomadbyte** [jitsi/jitsi-meet#11943]
Running the Jitsi Meet Android app (org.jitsi.meet_224001.apk, from F-Droid) on Kindle Fire HD8.

When running in the Jitsi's regular mode, the Android's main navigation bar (on the bottom) auto-hides as usual and could be slid up into view (half-transparent) by a drag up. This does not change the layout of the Jitsi screen.

However, when the low-bandwidth mode is enabled, the Android's navigation bar shows up as solid (in blue) and stays fixed on the bottom. It does not auto-hide. The Jitsi's view layout is shortened  to accommodate the bar.

Disabling the low-bandwidth mode properly re-enables the auto-hide behavior.

**Comment by saghul** [comment]
This is the intended behavior. We use immersive mode when there is video, but since there is none in audio only mode, we disable immersive mode.
