### ISSUE TITLE
Disabling local recording disables recording option altogether 

### ISSUE THREAD

**Issue by debendraoli** [jitsi/jitsi-meet#11941]
### Description:

As title states disabling local recording hides recording option from ui and local recording option which is enabled by default forbids using backend recording (jibri). This problem makes recording service impossible to use. 

### Steps to reproduce:
1. Disable local recording from config.js
2. Join room.
3. Try recording 

### Server information:

- Jitsi Meet version: latest release
- Operating System: linux

### Client information:

- Browser / app version: Chrome/Brave 103
- Operating System:  Archlinux

**Comment by saghul** [comment]
What recording options did you configure in config.js?

**Comment by debendraoli** [comment]
Its k8s setup actually, enabling local recording brings back the recording option but unchecking the local recording button is not possible. So it's defaults to local recording.

The set up was working perfectly before the local recording came. 


```
config.fileRecordingsEnabled = true;
config.localRecording = {};
config.localRecording.disable = true;
```

**Comment by saghul** [comment]
What image version are you using?

**Comment by debendraoli** [comment]
latest unstable.

**Comment by saghul** [comment]
That image is updated daily. Can you try yesterday's image (there are daily tags) to be sure?

**Comment by debendraoli** [comment]
yes, same result. I'm tried stable too.

**Comment by saghul** [comment]
@robertpin Can you please check if there are any logic issues here?

**Comment by robertpin** [comment]
> Its k8s setup actually, enabling local recording brings back the recording option but checkbox button is disabled, so it's defaults to local recording. Perhaps something to do with recordings setup?
> 
> Jibris are joining without error.
> 
> The set up was working perfectly before the local recording came.
> 
> ```
> config.fileRecordingsEnabled = true;
> config.localRecording = {};
> config.localRecording.disable = true;
> ```

In order for this to work you need to enabled both `fileRecordingsEnabled` and `fileRecordingsServiceEnabled`. But we deprecated these to options in favor of one `recordingService.enabled`

**Comment by debendraoli** [comment]
Thanks, worked. It looks like deprecated value has preferences over  new one.
