### ISSUE TITLE
Wrong CSS-Formatting in Poll-Screen with latest stable 2.0.7577

### ISSUE THREAD

**Issue by 0xnor0** [jitsi/jitsi-meet#11955]
### Description:
With latest stable (7577) the poll screen has display errors.

### Steps to reproduce:
1. open conference
2. create a poll

### Expected behavior:
![image](https://user-images.githubusercontent.com/38582847/182573762-5bbcbbbe-0efe-4bd2-904f-f3b314799c72.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/38582847/182573822-2e3e1daf-343a-43d5-aa88-681ab7b4ee5c.png)

### Server information:
- Jitsi Meet version: 2.0.7577
- jitsi-meet-prosody/stable,now 1.0.6380-1 all  [installiert]
- jitsi-meet-web-config/stable,now 1.0.6380-1 all  [installiert]
- jitsi-meet-web/stable,now 1.0.6380-1 all  [installiert]
- jitsi-videobridge2/stable,now 2.2-18-gade06bf8-1 all  [installiert]

- Operating System: Ubuntu 20.04.4 LTS

### Client information:
- Browser: Brave v1.41.100
- Operating System: Ubuntu 22.04.1 LTS

According to our developers, it may be due to a syntax problem in the CSS, -> https://github.com/jitsi/jitsi-meet/blob/master/css/_polls.scss#L78 (flex instead of 'flex').
![image](https://user-images.githubusercontent.com/38582847/182575561-76200bd6-9aa3-4c9f-8054-c41abfa0a7ec.png)

**Comment by saghul** [comment]
Ping @robertpin

**Comment by robertpin** [comment]
Looks like Brave doesn't parse CSS flex if they're strings. I'll create a fix
