### ISSUE TITLE
token_verification error after update

### ISSUE THREAD

**Issue by kiliankoller** [jitsi/jitsi-meet#11967]
### Description:

If I upgrade a JWT enabled Jitsi installation on **Ubuntu 20.04.4 LTS** from

- ii  jitsi-meet                      2.0.7439-1                        all          WebRTC JavaScript video conferences
- ii  jitsi-meet-prosody              1.0.6260-1                        all          Prosody configuration for Jitsi Meet
- ii  jitsi-meet-tokens               1.0.6260-1                        all          Prosody token authentication plugin for Jitsi Meet
- ii  jitsi-meet-web                  1.0.6260-1                        all          WebRTC JavaScript video conferences
- ii  jitsi-meet-web-config           1.0.6260-1                        all          Configuration for web serving of Jitsi Meet
- ii  jitsi-videobridge2              2.2-9-g8cded16e-1                 all          WebRTC compatible Selective Forwarding Unit (SFU)
- hi  prosody                         0.11.13-1~focal1                  amd64        Lightweight Jabber/XMPP server

to the current version **2.0.7577**, JWT authentication is no longer working. In the Prosody log, I see this type of error:

`token_verification error Token eyJ0eXAi..... not allowed to join`

I did not update Prosody to 0.12.X, as this was not working before.

Do I need to update any config settings?

**Comment by damencho** [comment]
Any error logs you see in the js console of the browser?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by kiliankoller** [comment]
I see 2022-08-05T09:20:11.380Z [conference.js] <_onConferenceFailed>:  CONFERENCE FAILED: conference.connectionError.notAllowed

**Comment by kiliankoller** [comment]
OK, I will open the issue on the forum...

**Comment by damencho** [comment]
Are there more errors in the prosody logs?

**Comment by kiliankoller** [comment]
OK, I solved the problem for the moderator. The requirements for the token seen to have changed with this update. I used this tool https://jitok.emrah.com/ for debugging.

Although, guest are still not able to join the open conference without a token, even though this block exists:

`
VirtualHost "guest.###HOSTNAME###"
        authentication = "token";
        app_id="###HOSTNAME###"
        app_secret="###TOKEN_SECRET###"
        c2s_require_encryption = true;
        allow_empty_token = true;
`

**Comment by damencho** [comment]
> allow_empty_token = true;

This should be under your main domain. guest domain is used when you have secure domain setup (user & pass case).

**Comment by kiliankoller** [comment]
We have a setup, where moderators with tokens should be allowed to create rooms, but guest should only be allowed to join existing rooms.

This was deeply discussed here: [https://community.jitsi.org/t/jwt-tokens-and-guest-access/18119](https://community.jitsi.org/t/jwt-tokens-and-guest-access/18119)

The solution with the guest VirtualHost seemed to be the only solution for this case, which worked perfectly for us for years now.

What could be the breaking change in the last update?

Thanks so much!

**Comment by kiliankoller** [comment]
The same problem is described here: https://community.jitsi.org/t/jwt-authentication-anonymous-guest-domain-bugged-or-working-as-intended/115999

**Comment by keithdanielll** [comment]
> > allow_empty_token = true;
> 
> This should be under your main domain. guest domain is used when you have secure domain setup (user & pass case).

That saved my day!

**Comment by ankar84** [comment]
> We have a setup, where moderators with tokens should be allowed to create rooms, but guest should only be allowed to join existing rooms.
> 
> This was deeply discussed here: https://community.jitsi.org/t/jwt-tokens-and-guest-access/18119
> 
> The solution with the guest VirtualHost seemed to be the only solution for this case, which worked perfectly for us for years now.
> 
> What could be the breaking change in the last update?
> 
> Thanks so much!

We have completely same situation.
We need only authenticated via JWT token users can create calls. And all other users (guests) can join that existing call via direct URL link.
We had 2 domains in prosody - main and guest. And only guest domain was with `allow_empty_token = true;` directive all that time before recent update. And all worked perfect as we expected. And all was logic - guests have no token and `allow_empty_token = true;` in guest domain settings grant guest users to access call, but not to create it.
Now that straightforward logic is broken to me, I don't understand why main domain must have `allow_empty_token = true;` directive to work.

@damencho please explain that recent changes in details.

**Comment by damencho** [comment]
You can set enable_domain_verification = false and it will work.

This is duplicate of https://github.com/jitsi/jitsi-meet/issues/11999
I will try to look at it next week.

The mix of jwt and guest domain was bever intended to work together. If that is the case it can be broken at anytime.
While refactoring the authentication logic as a whole, we will take in mind this usecase and will offer a solution for it.

**Comment by khiemnd5** [comment]
> You can set enable_domain_verification = false and it will work.
> 
> This is duplicate of #11999 I will try to look at it next week.
> 
> The mix of jwt and guest domain was bever intended to work together. If that is the case it can be broken at anytime. While refactoring the authentication logic as a whole, we will take in mind this usecase and will offer a solution for it.

right, after upgrade new version jitsi have this problem (reload can not access this room, other person also didn't access if without token). And must change **enable_domain_verification = false**  in file **/usr/share/jitsi-meet/prosody-plugins/token/util.lib.lua** detail is https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/token/util.lib.lua#L74 then **work fine**.
Thank you @damencho

**Comment by kiliankoller** [comment]
Setting enable_domain_verification = false in /etc/prosody/conf.avail/DOMAIN.cfg.lua solved the issue as described here:

https://community.jitsi.org/t/jwt-authentication-anonymous-guest-domain-bugged-or-working-as-intended/115999/34?u=kiliankoller

**Comment by damencho** [comment]
The fix discussed here https://community.jitsi.org/t/intent-to-deprecate-and-remove-external-auth-mechanisms/115332
