### ISSUE TITLE
Mic&Cam are disabled after rejoining a session

### ISSUE THREAD

**Issue by fleaz** [jitsi/jitsi-meet#11961]
### Description:

Sometimes I disconnect from a running meeting due to network problems (e.g. starting a VPN). When that happens Jitsi disconnect the meeting and the timer for rejoin starts. After doing stuff with e.g. the VPN I click rejoin and have no problems reconnecting to the session but my camera and my microphone are both disabled and I need to remember to click on the icons in the bar at the bottom to activate them again.

Installed a Jitsi update last week, but the problem also happended before that, so this is probably not related to the current version.

### Steps to reproduce:

1. Join a meeting with both cam and mic enabled
2. Do something which will disconnect you from the session (e.g. delete default route, disconnect network cable, etc)
3. wait until Jitsi recognizes the problem and stops the meeting
4.  Undo step 2
5. Click "Rejoin"

### Expected behavior:

State of camera and microphone should be the same like before I left the meeting.

### Actual behavior:

Camera and microphone are both disabled after rejoining.
![2022-08-03T17:40:37,235447611+02:00](https://user-images.githubusercontent.com/2489598/182651025-ad6cafb3-eb77-40b3-be11-a456664d394e.png)
![2022-08-03T17:41:01,352328069+02:00](https://user-images.githubusercontent.com/2489598/182651038-21130742-58f1-40ee-b3d2-e46471edb9a1.png)

### Server information:

- Jitsi Meet version: 2.0.6173-1
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: Chromium 103
- Operating System: NixOS 22.05

**Comment by Bharat-2000** [comment]
hey i test the whole scenario myself and i think the issue has been already resolved!!
issue - Mic&Cam are disabled after rejoining a session #11961
