### ISSUE TITLE
Camera feeds on mobile stopped working

### ISSUE THREAD

**Issue by geiszla** [jitsi/jitsi-meet#11977]
### Description:

In a Jitsi meeting using the mobile SDK no camera feed is visible and a camera off icon is present next to everyone's avatar, while, in reality their camera is on.

### Steps to reproduce:

1. Start a meeting using the Jitsi mobile SDK
2. Have at least 2 people in the meeting and turn on their camera

### Expected behavior:

Video feed from camera of one user should be visible to the other user and vice versa.

### Actual behavior:

I can see my own camera feed, but not my meeting partner's, and it's the same from the meeting partner's side.

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: meet.jit.si

### Client information:

- Browser / app version: `org.jitsi.react:jitsi-meet-sdk:4.1.0`
- Operating System: Android 11/12 (probably others as well)

**Comment by saghul** [comment]
is there screen sharing involved?

@bgrozev @jallamsetty1 could this be related to the multi-stream changes? Alas we do seem to have people on old SDKs in the form of third-party wrappers...

**Comment by geiszla** [comment]
Screen sharing also doesn't show up, but neither does any normal camera feed, so I don't think it's a problem with screen sharing.

**Comment by geiszla** [comment]
Any news on this? It feels like quite a big issue considering that it affects all the React Native apps that would use Jitsi as well as all the Android apps that use `v4` or lower.

**Comment by jallamsetty1** [comment]
@saghul Do you know how we can reproduce this ?

**Comment by saghul** [comment]
I can try to repro with an old app version I guess.

**Comment by sandypriyatna** [comment]
Hi, is there already a solution related to this issue?

**Comment by saghul** [comment]
Sorry, I haven't been able to test this yet.

**Comment by saghul** [comment]
It's unlikely this is the same issue since the RN SDK didn't cost back then.

What server are you testing with?

**Comment by TheUsmanBhatti** [comment]
We have hosted the jitsi on our own server around 1 year ago

**Comment by saghul** [comment]
Is it up to date?

**Comment by TheUsmanBhatti** [comment]
No

**Comment by saghul** [comment]
You are going to need to update it,

**Comment by TheUsmanBhatti** [comment]
Okay, I will update
