### ISSUE TITLE
Preloading page

### ISSUE THREAD

**Issue by lihang1232** [jitsi/jitsi-meet#11975]
I don't need this page,How do I set it up?
![image](https://user-images.githubusercontent.com/29720163/183021530-a7d740e6-c1df-4677-ae27-e1244ec6b5bf.png)

**Comment by saghul** [comment]
It's currently not possible to disable it on mobile.

**Comment by lihang1232** [comment]
I don't need to share this feature, what do I need to do?
![image](https://user-images.githubusercontent.com/29720163/183025954-25a71071-fbb5-4dbb-bcb4-aeeb6b6cbf44.png)

**Comment by saghul** [comment]
That one you can disable with the `video-share.enabled` feature flag.
