### ISSUE TITLE
Cannot chat or type password with both prejoin page and lobby enabled

### ISSUE THREAD

**Issue by verement** [jitsi/jitsi-meet#11986]
With `prejoinConfig.enabled` set to `true`, if a moderator also enables the Lobby function, new participants cannot use the keyboard to chat with moderators or enter a password after clicking the “Ask to Join” button. (The input fields lose focus immediately after clicking on them.)

Jitsi Meet version: 2.0.7577-1

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This had been fixed and will be part of the next stable release.
https://github.com/jitsi/jitsi-meet/commit/a2c3bdf05f704304b96d32330289248a3ce0b8f4
