### ISSUE TITLE
showNotification command not available

### ISSUE THREAD

**Issue by bogdanghervan** [jitsi/jitsi-meet#11985]
We are trying to use the newly released command `showNotification` (#11897) but our loaded version of the Jitsi Iframe API (JaaS) does not seem to contain it.

We see a "Not supported command name." error message in the console.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/585130/183249214-e02cb22d-e231-4802-b291-e6a448c97738.png">

The 6380.3155 version seems to be loaded from the CDN. Should I assume this new feature was not yet made available for JaaS or is there a way to force this new version to be loaded?

**Comment by mihhu** [comment]
It's not yet released for JaaS (jitsi-meet [changelog](https://github.com/jitsi/jitsi-meet/compare/release-6305...release-6380) for the [latest release](https://developer.8x8.com/jaas/docs/release-3192)).

**Comment by bogdanghervan** [comment]
Thanks @mihhu. When is `showNotification` expected to be released?

Generally speaking, is there a way to tell if the commands documented in the [handbook](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands) would work with JaaS or not?

So far I couldn't get `sendChatMessage`, `kickParticipant` and `askToUnmute` to work, but I suspect others don't work as well (`displayName` or `grantModerator`).

**Comment by mihhu** [comment]
> Thanks @mihhu. When is `showNotification` expected to be released?

I can't say for sure, but most probably next month at the latest. 

> Generally speaking, is there a way to tell if the commands documented in the [handbook](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands) would work with JaaS or not?

Currently there isn't, newly added features get documented asap, because they become available for those forking the repo. However, it's a good idea to mark the ones that aren't yet available in JaaS. @saghul, maybe we can use a badge the way we do for deprecated options, wdyt?

> So far I couldn't get `sendChatMessage`, `kickParticipant` and `askToUnmute` to work, but I suspect others don't work as well (`displayName` or `grantModerator`).

Usually it's the new features that take a while to catch the release, the ones you mentioned are quite old now, they should work (can't test atm). Could you please share a snippet?

**Comment by saghul** [comment]
Not sure TBH I have the feeling it could go out of sync easily.

**Comment by shawnchin** [comment]
Might it help if there was a `api.getSupportedCommands()` and `api.getSupportedEvents()` function? It would make it easier for devs to inspect what commands/events are available for the version they are using. 

As a bonus it also makes it possible to programmatically infer if a command is available and fallback to some alternative mechanism if it were not.

**Comment by saghul** [comment]
That's not a bad idea!

**Comment by shawnchin** [comment]
Release [7648](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_7648) just landed in stable which I believe contains the showNotification command 🕺 .

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/12011
