### ISSUE TITLE
'Desktop share' is not available in virtual backgrounds selection 

### ISSUE THREAD

**Issue by nomadbyte** [jitsi/jitsi-meet#11992]
### Description:

Using [meet.jit.si](https://meet.jit.si). Trying to set a screen share as a virtual background, however the "Desktop share" choice is not available in the list of the Virtual backgrounds.

### Steps to reproduce:

1. Open [meet.jit.si](https://meet.jit.si)
2. Create and join a room with both Microphone and Camera active
3. From the main menu choose "Select background"
4. The backgrounds list loads but it does not have "Desktop share" choice

### Expected behavior:

4. "Desktop share" choice is available in the list of virtual backgrounds

### Client information:

- Browser: Firefox 103.0
- Operating System: Linux Ubuntu 18.04

**Comment by saghul** [comment]
This is because we now support sharing your camera and desktop at the same time, so that mode is deprecated.

**Comment by nomadbyte** [comment]
Thanks. I wonder how should we now set up Jitsi Meet in Presenter mode (shared screen + own camera super-imposed)?

**Comment by saghul** [comment]
There is no such a thing now / yet. When you unmute people will see 2 tiles for you now. Super-imposing them will come at a later stage I think.

The previous effect can be accomplished with a virtual camera (the OBS one for example).

**Comment by jluisfa** [comment]
@saghul if that is deprecated, perhaps this is the opportune time to remove the "disableScreensharingVirtualBackground" from the "config.js".
https://github.com/jitsi/jitsi-meet/blob/5c52ee97edfd0beee1ee53815bf90da5ad948e96/config.js#L1216

**Comment by saghul** [comment]
Good point. It will likely get removed when completely remove the feature. Multi-stream is not on by default yet.

**Comment by holzi1005** [comment]
@saghul 
How can I enable the Desktop and Video sharing? Is there a new config option instead of the existing one

**Comment by saghul** [comment]
It's already enabled on meet.jit.si. You just start sharing and both camera and screen are sent. The recipient will see 2 tiles for you.

If you have your own deployment you need to add https://github.com/jitsi/jitsi-meet/blob/02e4d2b9026575a66ab04f1c3724b4f45ba9953c/config.js#L105 to the config.
