### ISSUE TITLE
preventExecution is not working for Hangup button in toolbar

### ISSUE THREAD

**Issue by shakibait** [jitsi/jitsi-meet#12014]
### Description:
I need to overwrite hangup button functionality to show a popup message before end meeting to make sure user didn't click on hangup button accidentally.

### Steps to reproduce:
In configOverwrite property i used buttonsWithNotifyClick to overwrite some toolbar button actions but this configuration is not working for hangup button.

`const options = {
    roomName: 'JitsiMeetAPIExample',
    width: 700,
    height: 700,
	configOverwrite: {
		toolbarButtons:
			['camera','chat','fullscreen','hangup','microphone','noisesuppression'],
		hideConferenceTimer:true,
		buttonsWithNotifyClick: ['camera','chat','fullscreen','microphone','noisesuppression',{key:'hangup',preventExecution:true}]
	},
    parentNode: document.querySelector('#meet'),
    lang: 'en'
};`

### Expected behavior:
Need to prevent hangup operation in web iframe api.

### Server information:

- Jitsi Meet version: 2.0.7001-1
- Operating System: Ubuntu 20.04.4 LTS

### Client information:

- Browser / app version: Chrome 104.0.5112.80
- Operating System: Window 10

### Additional information:
I'm using web iframe api via javascript.

**Comment by saghul** [comment]
IIRC we fixed this not so long ago, right @horymury ? Not sure in which release it went.

Can you test against meet.jit.si, since it runs the latest?

**Comment by horymury** [comment]
@saghul @shakibait  yep this is the PR:
https://github.com/jitsi/jitsi-meet/pull/11401/files

I just tested with the above configOverwrites on meet.jit.si and 8x8.vc domains, it works as expected on both.

@shakibait  on what domain are you experiencing the issue?

thank you

**Comment by shakibait** [comment]
> @saghul @shakibait yep this is the PR: https://github.com/jitsi/jitsi-meet/pull/11401/files
> 
> I just tested with the above configOverwrites on meet.jit.si and 8x8.vc domains, it works as expected on both.
> 
> @shakibait on what domain are you experiencing the issue?
> 
> thank you

I'm using jitsi in my ubuntu server with this domain: meet.px5.ir 
So i think that need to update jitsi on this server.

Thank you so much guys @horymury @saghul
