### ISSUE TITLE
Admin password to create meeting

### ISSUE THREAD

**Issue by trymeouteh** [jitsi/jitsi-meet#12032]
**Is your feature request related to a problem you are facing?**
For those who want to run their own private instance of Jitsi Meet but do not want the public to be able to create meetings.

**Describe the solution you'd like**
Allow the admin to enable a setting and set a password which is require to create a meeting.

**Describe alternatives you've considered**
None

**Comment by saghul** [comment]
You can enable authentication (secure domain) for that purpose. Please see: https://jitsi.github.io/handbook/docs/devops-guide/secure-domain
