### ISSUE TITLE
Building SDK error

### ISSUE THREAD

**Issue by lihang1232** [jitsi/jitsi-meet#12037]
Building SDK error, what should I do? Can you provide detailed steps for Building SDK?
Xcode Version:13.4.1 (13F100)
cocoapodsVersion:1.10.1
![image](https://user-images.githubusercontent.com/29720163/185360796-24f93b42-2db6-498d-99ba-bf8b44edf6c9.png)

**Comment by saghul** [comment]
Do you have the WebRTC framework in node_modules/react-native-webrtc/apple ?

**Comment by lihang1232** [comment]
This is the only file in node_modules/react-native-webrtc/apple,Am I missing something?
![image](https://user-images.githubusercontent.com/29720163/185520542-b8067a18-2297-4b05-9673-c166c1a6a11a.png)
