### ISSUE TITLE
Adjust language list

### ISSUE THREAD

**Issue by thttg** [jitsi/jitsi-meet#12047]
**Is your feature request related to a problem you are facing?**
It's difficult for the users to select their native language when the name of all languages has been translated.

![20220819164225](https://user-images.githubusercontent.com/28702320/185706261-31a04453-0c65-4a2e-81e1-0bb0ee39f9a6.png)
![_20220819170514](https://user-images.githubusercontent.com/28702320/185707062-78f20177-c50b-4dda-a207-88c6909ff948.png)

**Describe the solution you'd like**
Remove those language lists (e.g. languages-ja.json) that have been translated, leaving only languages.json.
And use its native form to display the language in languages.json.

Here are a few examples from Microsoft and Discord.

![20220819163306](https://user-images.githubusercontent.com/28702320/185703732-8df300de-1d0e-412a-859a-c568c5321696.png)

![20220819163408](https://user-images.githubusercontent.com/28702320/185703744-eac6aa9c-614a-43f2-a230-af4fe487244d.png)

**Comment by saghul** [comment]
I'm mildly supportive of this approach.

**Comment by Flying-Light** [comment]
Good point

**Comment by thttg** [comment]
#12475
