### ISSUE TITLE
iOS Screen Capture shows red screen when displayed in local `RTCView`

### ISSUE THREAD

**Issue by matallui** [jitsi/jitsi-meet#12040]
### Description:

When sharing your screen from an iOS (15.6) device, the `RTCView` that displays the stream locally shows a red screen.
I've also noticed the same issue on a demo app I've created very similar to [this one](https://github.com/irohitb/screenshare-webrtc).

With the same demo app on Android, I do get the hall of mirrors effect, but on iOS, for some reason, it just shows a red screen.

### Steps to reproduce:

1. Open Jitsi-Meet on iPhone device
2. Connect to a conference room
3. Start screen sharing

### Expected behavior:

Like Android, I'd expect to see a hall-of-mirrors effect on the local `RTCView`.

### Actual behavior:

Instead, we get a straight red screen. Below is a screenshot of the iOS app with the issue exposed.

![red-screen](https://user-images.githubusercontent.com/6828071/185450985-d86ae65d-9bf4-42fb-b335-cf814fd89871.jpg)

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: 22.4.0 build 1657277707
- Operating System: iOS 15.6

### Additional information:

I've also created a very similar demo app that, instead of displaying the screen capture locally, it uses PeerJS to share the stream to a remote device.
In that case, I can see the iPhone screen fine on the remote device. So, this seems to be an issue when displaying the screen capture on a local `RTCView`.
Not sure if this is an iOS restriction to prevent hall-of-mirrors, or if it's a bug, hence the creation of this issue.

**Comment by saghul** [comment]
Screen sharing does not work on the simulator, alas.

**Comment by matallui** [comment]
> 

@saghul this is not on a simulator. This is on a real iPhone device.

**Comment by saghul** [comment]
Sorry not sure why I got that idea 😅 

Can you reproduce this with meet.jit.si or your own deployment?

Have you tried our latest beta?

**Comment by matallui** [comment]
Haven't really looked into `meet.jit.si` or having my own deployment.
I literally just installed the app for the first time to test screen sharing and I noticed that.

Also not sure how to test the beta version on iOS (sorry, kind of new to mobile dev).

**Comment by saghul** [comment]
You can test it here: https://jitsi.github.io/handbook/docs/releases

If you just installed the app and joined a meeting without doing anything else then you have used meet.jit.si, since it's the default server.

**Comment by matallui** [comment]
Gotcha! Then I definitely used the default servers.
I'll give the beta build a try when I get a chance.

**Comment by matallui** [comment]
@saghul just tested the Beta, and still see the same issue.

**Comment by rcidt** [comment]
@saghul could you please provide some details on the fix? We are on an older version (not by choice) and would like to cherry pick the fix into our fork.
