### ISSUE TITLE
[iOS] UITabBarController becomes visible on conferenceTerminated

### ISSUE THREAD

**Issue by anirudhamahale** [jitsi/jitsi-meet#12045]
### Description:

UITabBar becomes visible once the conference is terminated

### Steps to reproduce:

1. Present Jitsi-meet from 2nd view controller from navigation stack, add the navigation stack to one of the UITabBarController. 
2. Make `hidesBottomBarWhenPushed` to true on UITabBarController.
3. Terminate the conference by clicking on end call button on jitsi-meet view.
4. Observe that the hidden UITabBar becomes visible on call end.

### Expected behavior:

The hidden UITabBar should not become visible on call end.

### Server information:

- Jitsi Meet version: 6.0.0

### Client information:

- Browser / app version: 
- Operating System: iOS 15.5

**Comment by saghul** [comment]
On what event are you hiding the JitsiMeetView ?

**Comment by anirudhamahale** [comment]
In `func conferenceTerminated(_ data: [AnyHashable : Any]!)` I am hiding the JitsiMeetView view

**Comment by saghul** [comment]
You need to use the readyToClose delegate method instead.

**Comment by anirudhamahale** [comment]
@saghul I don't see it in `JitsiMeetViewDelegate`, Can you tell me where it's located?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/blob/e458eed931f09e489ba41246d229224265c759a4/ios/sdk/src/JitsiMeetViewDelegate.h#L117

**Comment by anirudhamahale** [comment]
I am using (6.0.0) but the above method is not there. 
`pod 'JitsiMeetSDK', '~> 6.0.0'`

**Comment by saghul** [comment]
That has been available since version 4.0.0: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

**Comment by anirudhamahale** [comment]
@saghul I installed it using Pod
`pod 'JitsiMeetSDK', '~> 6.0.0'`

**Comment by saghul** [comment]
Then the API is certainly there. Even this example still on 5.1.0 has it: https://github.com/jitsi/jitsi-meet-sdk-samples/blob/463af642aa985cae5d1b2abf68dafacca7fc20d5/ios/objc/JitsiSDKTest/JitsiSDKTest/ConferenceViewController.m#L53
