### ISSUE TITLE
Authentication and Guest Access simple configuration per domain auth doc causes JS error and does not permit guest  "anonymous"

### ISSUE THREAD

**Issue by michaelpro** [jitsi/jitsi-meet#12059]
### Description:

Simple  domain authentication malfunctions. Guests are asked to authenticate. Browsers on MacOS crash, including Jitsi desktop app. 

### Steps to reproduce:

Set up a 22.04.1 server. 
Install nginx
Install pre-requisites and jitsi via apt per https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
Install a valid TLS certificate (letsencrypt)
Test vanilla set up (works without authentication, no jS console errors)
Set up domain authentication per https://jitsi.github.io/handbook/docs/devops-guide/secure-domain
Create accounts using prosodyctl

### Expected behavior:

A user should be prompted to authenticate in apps and browsers to create a meeting. Guests to the meeting should be allowed without authentication. 
There should be no JS error stacks on browser. 

Might be related to https://github.com/jitsi/jitsi-meet/issues/11144

### Actual behavior:

Browsers and Mac desktop App present a grey window without any content.
IOS app behaves better- It allows creation and correctly requests authentication.
However, on apps, guests are also required to authenticate, so anonymous log in does not function properly.
Browsers encounter an error in the  JS console (see additional information). 

more concisely: Apps do present dialogue box. browser encounters errors. Guests are incorrectly required to authenticate.

### Server information:

- Jitsi Meet version: 2.0.7648-1
- Operating System: Ubuntu 22.04.1 LTS

### Client information:

- Browser / app version: Safari, Firefox, Brave and Jitsi desktop app (latest of all as of 8/23/2022) 
- Operating System: MacOS 12.5.1 

### Additional information:

[Error] 2022-08-23T18:42:18.604Z – "[JitsiMeetJS.js]" – "UnhandledError: Right side of assignment cannot be destructured" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – "@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1495729↵asyncFunctionResume@[native code…"
"@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1495729
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1495844
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1625550
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1624981
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1619623
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1618987
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1613073
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1591274
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1586045
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1580106
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1577914
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1565227
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1558584
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1550252
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1549989
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1549919
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1541500
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1536613
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1535349
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1522276
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1512010
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1511654
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1509753
asyncFunctionResume@[native code]
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1506082
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1504739
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1502048
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1499653
generatorResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1486601
Promise@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1486361
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1495488
generatorResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1486601
Promise@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1486361
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:136:630523
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1625550
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1624981
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1619623
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1618987
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1613073
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1591274
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1586045
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1580106
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1577914
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1565227
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1558584
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1550252
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1549989
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1549919
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1541500
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1536613
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1535349
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1522276
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1512010
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1511654
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1509753
asyncFunctionResume@[native code]
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1506082
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1504739
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1502048
asyncFunctionResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1499653
generatorResume@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1486601
Promise@[native code]
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:138:1486361
@https://meet.redacted.com/libs/app.bundle.min.js?v=6447:136:630472
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]"
	error
	r (lib-jitsi-meet.min.js:2:33529)
	r
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:2:746075)
	(anonymous function) (app.bundle.min.js:138:1537541)

**Comment by saghul** [comment]
Can you try to find the broken line by clocking on the first URL in the JS console logs?

**Comment by michaelpro** [comment]
[Error] ReferenceError: Can't find variable: config
(anonymous function) — sha512.js:866
_start — Dropbox-sdk.min.js:1:30877
componentDidMount — Dropbox-sdk.min.js:1:28847
ms — frequency_lists.coffee:4
Pl — frequency_lists.coffee:4
Pl
(anonymous function) — frequency_lists.coffee:4
Dl — frequency_lists.coffee:4
gl — frequency_lists.coffee:4
gl
(anonymous function) — frequency_lists.coffee:3
(anonymous function) — frequency_lists.coffee:4
Kr — frequency_lists.coffee:3
Gr — frequency_lists.coffee:3
dl — frequency_lists.coffee:4
enqueueSetState — frequency_lists.coffee:3
(anonymous function) — frequency_lists.coffee:4
(anonymous function) — KeyboardAvoider.js:8
Promise
_navigate — KeyboardAvoider.js:8
promiseReactionJob

	ss (app.bundle.min.js:138:2531502)
	(anonymous function) (app.bundle.min.js:138:2533932)
	hi (app.bundle.min.js:138:2497705)
	ms (app.bundle.min.js:138:2535178)
	Pl (app.bundle.min.js:138:2551767)
	Pl
	(anonymous function) (app.bundle.min.js:138:2763055)
	Dl (app.bundle.min.js:138:2548506)
	gl (app.bundle.min.js:138:2544617)
	gl
	(anonymous function) (app.bundle.min.js:138:2494212)
	(anonymous function) (app.bundle.min.js:138:2763055)
	Kr (app.bundle.min.js:138:2494158)
	Gr (app.bundle.min.js:138:2494093)
	dl (app.bundle.min.js:138:2541777)
	enqueueSetState (app.bundle.min.js:138:2498067)
	(anonymous function) (app.bundle.min.js:138:2744558)
	(anonymous function) (app.bundle.min.js:136:631514)
	Promise
	_navigate (app.bundle.min.js:136:631495)
	promiseReactionJob

**Comment by michaelpro** [comment]
In further looking at the console, I found a subtle configuration error.  A trailing comma in the hosts section of .js file.
That's so easy to miss!  Hopefully this will help someone else.  I am closing this issue.
