### ISSUE TITLE
When showing a video from YouTube, the video avatar doubles

### ISSUE THREAD

**Issue by ildarKashapov** [jitsi/jitsi-meet#12057]
### Description:
The user is in an active conference and is the organizer\moderator

### Steps to reproduce:

1. Click 'more actions'
2. Click on 'Share a YouTube video '
3. Paste video link
4. Click on 'Share'

### Expected behavior:

One avatar of a YouTube video is displayed.

### Actual behavior:

Еhe avatar of the broadcast video is doubled.

### Server information:

- Jitsi Meet version: 2.0.7648

### Client information:

- Browser / app version: Chrome 104.0.5112.81
- Operating System: Win10, 64

**Comment by ildarKashapov** [comment]
![Screenshot_239](https://user-images.githubusercontent.com/111888704/186194664-044a1de7-60b6-4f13-ae5d-158a00c017b9.png)

**Comment by damencho** [comment]
Are you able to reproduce on meet.jit.si?

When you reproduce it, can you attach the js console logs?
