### ISSUE TITLE
IFrame API: Share a Youtube Video does not work

### ISSUE THREAD

**Issue by taihoa** [jitsi/jitsi-meet#12064]
Share video Youtube not working when using jitsi meet iframe.
I added allow="autoplay" to iframe but not working
Please help me!

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Which browser is this? Any errors in the ja console?

**Comment by taihoa** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.
 Yes. I understand.
> Which browser is this? Any errors in the ja console?
I using on chrome. Nothing error console

**Comment by damencho** [comment]
I just tested it using this example and everything works as expected. 
https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html

**Comment by taihoa** [comment]
> I just tested it using this example and everything works as expected. https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html

Yes. I tried with this example. But it not working on participant.
Step:
- User A start share video youtube
- User B see video but not play

**Comment by damencho** [comment]
Strange works here. Are you going through the pre-join screen first?
