### ISSUE TITLE
Incompatible with uMatrix User-Agent spoofing

### ISSUE THREAD

**Issue by lanodan** [jitsi/jitsi-meet#1206]
I use uMatrix with the User-Agent spoofing on. I believe you should not rely on the User-Agent for features. Seriously where do you think the huge mess(Mozilla/5.0 … instead of Firefox/5.0)  comes from.

Relates with #370

**Comment by bgrozev** [comment]
What would you suggest we use instead?

Boris

**Comment by lanodan** [comment]
I don’t know any javascript but I think there is a way to test if something works without using the user-agent(which is not reliable) or at least there is something mozilla uses on it’s addons pages to have something similar to the user agent but javascript-side.
In python it would probably be a Try/Except, in the little C I know it would be an #ifdef or/and an if().

**Comment by tcitworld** [comment]
@bgrozev What's the user-agent detection for ? Can you point it to me where it's used ?

**Comment by bgrozev** [comment]
Mostly to handle differences in the WebRTC APIs between firefox and chrome. See for example JitsiLocalTrack.js, RTCUtils.js, RTPStatsCollector.js, JingleSessionPC.js, TraceablePeerConnection.js
