### ISSUE TITLE
alpha.jitsi.net when we start meeting it always reconnects. 

### ISSUE THREAD

**Issue by SindhujaKanukolanu** [jitsi/jitsi-meet#12075]
Connect to https://alpha.jitsi.net/. 
Start Meeting.
We will be reconnected to the meeting even when we have good internet connection. This happens every time. 
Please find the console logs below 

Logger.js:154 2022-08-26T05:01:33.241Z [modules/xmpp/xmpp.js] <sa.createRoom>:  JID 6a653d3d-407a-444d-9d4f-a5c5fc7322cf@alpha.jitsi.net/ZkRgzE6u using MUC nickname 6a653d3d
Logger.js:154 2022-08-26T05:01:33.242Z [modules/xmpp/ChatRoom.js] <new Sr>:  Joined MUC as frequentpenaltiespicturefairly@conference.alpha.jitsi.net/6a653d3d
Logger.js:154 2022-08-26T05:01:33.243Z [modules/connectivity/ParticipantConnectionStatus.js] <new Ln>:  RtcMuteTimeout set to: 10000
Logger.js:154 2022-08-26T05:01:33.246Z [JitsiConference.js] <Mh._init>:  Using VAD detection for generating talk while muted events
Logger.js:154 2022-08-26T05:01:33.247Z [modules/statistics/AvgRTPStatsReporter.js] <new Vl>:  Avg RTP stats will be calculated every 15 samples
Logger.js:154 2022-08-26T05:01:33.248Z [JitsiConference.js] <new Mh>:  backToP2PDelay: 5
Logger.js:154 2022-08-26T05:01:33.248Z [JitsiConference.js] <new Mh>:  End-to-End Encryption is supported
Logger.js:154 2022-08-26T05:01:33.263Z [modules/xmpp/moderator.js] <pr.setFocusUserJid>:  Focus jid set to:  undefined
Logger.js:154 2022-08-26T05:01:33.263Z [modules/xmpp/moderator.js] <pr.createConferenceIq>:  Session ID: null machine UID: c620576c69b23b6fce6d8cc38c2bee57
index.js:154 2022-08-26T05:01:33.265Z [conference.js] Initialized with 0 local tracks
Logger.js:154 2022-08-26T05:01:33.342Z [modules/statistics/CallStats.js] Reported wifi addresses: undefined
Logger.js:154 2022-08-26T05:01:33.630Z [modules/statistics/CallStats.js] <a._initCallback [as initCallback]>:  CallStats Status: err=success msg=SDK authentication successful.
Logger.js:154 2022-08-26T05:01:33.648Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Focus error, retry after 1000 Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 1000
    at pr._allocateConferenceFocusError (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:340507)
    at https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:339548
    at I.Handler.handler (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:154228)
    at I.Handler.run (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:149527)
    at https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:157965
    at Object.forEachChild (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:141195)
    at I.Connection._dataRecv (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:157814)
    at D.Bosh._onRequestStateChange (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:177798)
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:532
window.onerror @ middleware.js:99
callErrorHandler @ GlobalOnErrorHandler.js:61
pr._allocateConferenceFocusError @ moderator.js:382
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
(anonymous) @ XmppConnection.js:525
sendIQ2 @ XmppConnection.js:523
ping @ strophe.ping.js:89
(anonymous) @ strophe.ping.js:120
Logger.js:154 2022-08-26T05:01:33.648Z [modules/xmpp/moderator.js] <pr._allocateConferenceFocusError>:  Focus error, retry after 1000 <iq xmlns=​"jabber:​client" from=​"focus.alpha.jitsi.net" id=​"f6416685-e169-456c-b7f6-bf0193f72feb:​sendIQ" type=​"error" to=​"6a653d3d-407a-444d-9d4f-a5c5fc7322cf@alpha.jitsi.net/​ZkRgzE6u">​…​</iq>​
r @ Logger.js:154
pr._allocateConferenceFocusError @ moderator.js:383
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
(anonymous) @ XmppConnection.js:525
sendIQ2 @ XmppConnection.js:523
ping @ strophe.ping.js:89
(anonymous) @ strophe.ping.js:120
index.js:154 2022-08-26T05:01:33.659Z [features/overlay] <Ioe.componentDidMount>:  The conference will be reloaded after 14 seconds.
index.js:154 2022-08-26T05:01:33.662Z [conference.js] <Mce._onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected focus.alpha.jitsi.net 1
i @ index.js:154
_onConferenceFailed @ conference.js:321
r.emit @ events.js:153
r.emit @ events.js:153
pr._allocateConferenceFocusError @ moderator.js:393
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
(anonymous) @ XmppConnection.js:525
sendIQ2 @ XmppConnection.js:523
ping @ strophe.ping.js:89
(anonymous) @ strophe.ping.js:120
Logger.js:154 2022-08-26T05:01:34.664Z [modules/xmpp/moderator.js] <pr.setFocusUserJid>:  Focus jid set to:  undefined
Logger.js:154 2022-08-26T05:01:34.664Z [modules/xmpp/moderator.js] <pr.createConferenceIq>:  Session ID: null machine UID: c620576c69b23b6fce6d8cc38c2bee57
Logger.js:154 2022-08-26T05:01:34.918Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Focus error, retry after 2000 Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 2000
    at pr._allocateConferenceFocusError (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:340507)
    at https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:339548
    at I.Handler.handler (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:154228)
    at I.Handler.run (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:149527)
    at https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:157965
    at Object.forEachChild (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:141195)
    at I.Connection._dataRecv (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:157814)
    at D.Bosh._onRequestStateChange (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:177798)
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:532
window.onerror @ middleware.js:99
callErrorHandler @ GlobalOnErrorHandler.js:61
pr._allocateConferenceFocusError @ moderator.js:382
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:355
(anonymous) @ moderator.js:315
pr.allocateConferenceFocus @ moderator.js:301
(anonymous) @ ChatRoom.js:193
join @ ChatRoom.js:186
Mh.join @ JitsiConference.js:581
connect @ conference.js:430
(anonymous) @ conference.js:775
startConference @ conference.js:774
prejoinStart @ conference.js:899
await in prejoinStart (async)
(anonymous) @ actions.js:256
await in (anonymous) (async)
(anonymous) @ resemble.js:11
(anonymous) @ middleware.js:30
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:19
(anonymous) @ middleware.web.js:29
(anonymous) @ middleware.any.js:47
(anonymous) @ middleware.js:87
(anonymous) @ middleware.js:45
(anonymous) @ middleware.js:65
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:181
(anonymous) @ middleware.js:71
(anonymous) @ middleware.js:87
(anonymous) @ middleware.js:40
(anonymous) @ middleware.ts:161
(anonymous) @ middleware.js:80
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.js:80
(anonymous) @ middleware.js:31
(anonymous) @ middleware.web.js:46
(anonymous) @ middleware.web.js:24
(anonymous) @ middleware.any.js:94
(anonymous) @ middleware.js:80
(anonymous) @ middleware.web.js:325
(anonymous) @ middleware.js:50
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:106
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.js:231
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:28
(anonymous) @ middleware.web.js:20
(anonymous) @ middleware.js:42
(anonymous) @ middleware.js:357
(anonymous) @ middleware.js:21
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.js:46
(anonymous) @ middleware.js:97
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.web.js:100
(anonymous) @ middleware.any.js:109
(anonymous) @ middleware.js:207
(anonymous) @ middleware.js:106
(anonymous) @ middleware.any.js:46
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:27
(anonymous) @ middleware.js:23
(anonymous) @ middleware.web.js:11
(anonymous) @ middleware.web.js:36
(anonymous) @ middleware.any.js:124
(anonymous) @ middleware.js:19
(anonymous) @ middleware.js:91
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:197
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:76
(anonymous) @ middleware.js:244
(anonymous) @ middleware.web.js:25
(anonymous) @ middleware.web.ts:37
(anonymous) @ middleware.any.js:147
(anonymous) @ middleware.js:201
o @ middleware.ts:44
(anonymous) @ middleware.ts:7
(anonymous) @ middleware.ts:3
(anonymous) @ middleware.web.js:126
(anonymous) @ middleware.js:180
(anonymous) @ redux.js:475
_onJoinButtonClick @ Prejoin.web.js:185
Ue @ index.js:52
Ke @ index.js:52
(anonymous) @ index.js:53
Aa @ index.js:100
Ta @ index.js:101
(anonymous) @ index.js:113
Re @ index.js:292
(anonymous) @ index.js:50
Ma @ index.js:105
Qt @ index.js:75
Jt @ index.js:74
t.unstable_runWithPriority @ index.js:18
Wr @ index.js:122
Ie @ index.js:292
$t @ index.js:73
Show 95 more frames
Logger.js:154 2022-08-26T05:01:34.918Z [modules/xmpp/moderator.js] <pr._allocateConferenceFocusError>:  Focus error, retry after 2000 <iq xmlns=​"jabber:​client" from=​"focus.alpha.jitsi.net" id=​"a5706a96-a29f-4260-85de-f8bbe3221c69:​sendIQ" type=​"error" to=​"6a653d3d-407a-444d-9d4f-a5c5fc7322cf@alpha.jitsi.net/​ZkRgzE6u">​…​</iq>​
r @ Logger.js:154
pr._allocateConferenceFocusError @ moderator.js:383
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:355
(anonymous) @ moderator.js:315
pr.allocateConferenceFocus @ moderator.js:301
(anonymous) @ ChatRoom.js:193
join @ ChatRoom.js:186
Mh.join @ JitsiConference.js:581
connect @ conference.js:430
(anonymous) @ conference.js:775
startConference @ conference.js:774
prejoinStart @ conference.js:899
await in prejoinStart (async)
(anonymous) @ actions.js:256
await in (anonymous) (async)
(anonymous) @ resemble.js:11
(anonymous) @ middleware.js:30
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:19
(anonymous) @ middleware.web.js:29
(anonymous) @ middleware.any.js:47
(anonymous) @ middleware.js:87
(anonymous) @ middleware.js:45
(anonymous) @ middleware.js:65
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:181
(anonymous) @ middleware.js:71
(anonymous) @ middleware.js:87
(anonymous) @ middleware.js:40
(anonymous) @ middleware.ts:161
(anonymous) @ middleware.js:80
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.js:80
(anonymous) @ middleware.js:31
(anonymous) @ middleware.web.js:46
(anonymous) @ middleware.web.js:24
(anonymous) @ middleware.any.js:94
(anonymous) @ middleware.js:80
(anonymous) @ middleware.web.js:325
(anonymous) @ middleware.js:50
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:106
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.js:231
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:28
(anonymous) @ middleware.web.js:20
(anonymous) @ middleware.js:42
(anonymous) @ middleware.js:357
(anonymous) @ middleware.js:21
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.js:46
(anonymous) @ middleware.js:97
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.web.js:100
(anonymous) @ middleware.any.js:109
(anonymous) @ middleware.js:207
(anonymous) @ middleware.js:106
(anonymous) @ middleware.any.js:46
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:27
(anonymous) @ middleware.js:23
(anonymous) @ middleware.web.js:11
(anonymous) @ middleware.web.js:36
(anonymous) @ middleware.any.js:124
(anonymous) @ middleware.js:19
(anonymous) @ middleware.js:91
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:197
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:76
(anonymous) @ middleware.js:244
(anonymous) @ middleware.web.js:25
(anonymous) @ middleware.web.ts:37
(anonymous) @ middleware.any.js:147
(anonymous) @ middleware.js:201
o @ middleware.ts:44
(anonymous) @ middleware.ts:7
(anonymous) @ middleware.ts:3
(anonymous) @ middleware.web.js:126
(anonymous) @ middleware.js:180
(anonymous) @ redux.js:475
_onJoinButtonClick @ Prejoin.web.js:185
Ue @ index.js:52
Ke @ index.js:52
(anonymous) @ index.js:53
Aa @ index.js:100
Ta @ index.js:101
(anonymous) @ index.js:113
Re @ index.js:292
(anonymous) @ index.js:50
Ma @ index.js:105
Qt @ index.js:75
Jt @ index.js:74
t.unstable_runWithPriority @ index.js:18
Wr @ index.js:122
Ie @ index.js:292
$t @ index.js:73
Show 93 more frames
index.js:154 2022-08-26T05:01:34.924Z [conference.js] <Mce._onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected focus.alpha.jitsi.net 2
i @ index.js:154
_onConferenceFailed @ conference.js:321
r.emit @ events.js:153
r.emit @ events.js:153
pr._allocateConferenceFocusError @ moderator.js:393
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:355
(anonymous) @ moderator.js:315
pr.allocateConferenceFocus @ moderator.js:301
(anonymous) @ ChatRoom.js:193
join @ ChatRoom.js:186
Mh.join @ JitsiConference.js:581
connect @ conference.js:430
(anonymous) @ conference.js:775
startConference @ conference.js:774
prejoinStart @ conference.js:899
await in prejoinStart (async)
(anonymous) @ actions.js:256
await in (anonymous) (async)
(anonymous) @ resemble.js:11
(anonymous) @ middleware.js:30
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:19
(anonymous) @ middleware.web.js:29
(anonymous) @ middleware.any.js:47
(anonymous) @ middleware.js:87
(anonymous) @ middleware.js:45
(anonymous) @ middleware.js:65
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:181
(anonymous) @ middleware.js:71
(anonymous) @ middleware.js:87
(anonymous) @ middleware.js:40
(anonymous) @ middleware.ts:161
(anonymous) @ middleware.js:80
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.js:80
(anonymous) @ middleware.js:31
(anonymous) @ middleware.web.js:46
(anonymous) @ middleware.web.js:24
(anonymous) @ middleware.any.js:94
(anonymous) @ middleware.js:80
(anonymous) @ middleware.web.js:325
(anonymous) @ middleware.js:50
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:106
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.js:231
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:28
(anonymous) @ middleware.web.js:20
(anonymous) @ middleware.js:42
(anonymous) @ middleware.js:357
(anonymous) @ middleware.js:21
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.js:46
(anonymous) @ middleware.js:97
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.web.js:100
(anonymous) @ middleware.any.js:109
(anonymous) @ middleware.js:207
(anonymous) @ middleware.js:106
(anonymous) @ middleware.any.js:46
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:27
(anonymous) @ middleware.js:23
(anonymous) @ middleware.web.js:11
(anonymous) @ middleware.web.js:36
(anonymous) @ middleware.any.js:124
(anonymous) @ middleware.js:19
(anonymous) @ middleware.js:91
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:197
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:76
(anonymous) @ middleware.js:244
(anonymous) @ middleware.web.js:25
(anonymous) @ middleware.web.ts:37
(anonymous) @ middleware.any.js:147
(anonymous) @ middleware.js:201
o @ middleware.ts:44
(anonymous) @ middleware.ts:7
(anonymous) @ middleware.ts:3
(anonymous) @ middleware.web.js:126
(anonymous) @ middleware.js:180
(anonymous) @ redux.js:475
_onJoinButtonClick @ Prejoin.web.js:185
Ue @ index.js:52
Ke @ index.js:52
(anonymous) @ index.js:53
Aa @ index.js:100
Ta @ index.js:101
(anonymous) @ index.js:113
Re @ index.js:292
(anonymous) @ index.js:50
Ma @ index.js:105
Qt @ index.js:75
Jt @ index.js:74
t.unstable_runWithPriority @ index.js:18
Wr @ index.js:122
Ie @ index.js:292
$t @ index.js:73
Show 95 more frames
Logger.js:154 2022-08-26T05:01:36.927Z [modules/xmpp/moderator.js] <pr.setFocusUserJid>:  Focus jid set to:  undefined
Logger.js:154 2022-08-26T05:01:36.927Z [modules/xmpp/moderator.js] <pr.createConferenceIq>:  Session ID: null machine UID: c620576c69b23b6fce6d8cc38c2bee57
Logger.js:154 2022-08-26T05:01:37.194Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Focus error, retry after 4000 Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 4000
    at pr._allocateConferenceFocusError (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:340507)
    at https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:339548
    at I.Handler.handler (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:154228)
    at I.Handler.run (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:149527)
    at https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:157965
    at Object.forEachChild (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:141195)
    at I.Connection._dataRecv (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:157814)
    at D.Bosh._onRequestStateChange (https://alpha.jitsi.net/libs/lib-jitsi-meet.min.js?v=6494:2:177798)
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:532
window.onerror @ middleware.js:99
callErrorHandler @ GlobalOnErrorHandler.js:61
pr._allocateConferenceFocusError @ moderator.js:382
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:355
(anonymous) @ moderator.js:315
pr.allocateConferenceFocus @ moderator.js:301
(anonymous) @ moderator.js:402
setTimeout (async)
pr._allocateConferenceFocusError @ moderator.js:401
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
(anonymous) @ XmppConnection.js:525
sendIQ2 @ XmppConnection.js:523
ping @ strophe.ping.js:89
(anonymous) @ strophe.ping.js:120
Logger.js:154 2022-08-26T05:01:37.194Z [modules/xmpp/moderator.js] <pr._allocateConferenceFocusError>:  Focus error, retry after 4000 <iq xmlns=​"jabber:​client" from=​"focus.alpha.jitsi.net" id=​"d01860d0-b233-4b8c-88e1-d2b6992e9c8a:​sendIQ" type=​"error" to=​"6a653d3d-407a-444d-9d4f-a5c5fc7322cf@alpha.jitsi.net/​ZkRgzE6u">​…​</iq>​
r @ Logger.js:154
pr._allocateConferenceFocusError @ moderator.js:383
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:355
(anonymous) @ moderator.js:315
pr.allocateConferenceFocus @ moderator.js:301
(anonymous) @ moderator.js:402
setTimeout (async)
pr._allocateConferenceFocusError @ moderator.js:401
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
(anonymous) @ XmppConnection.js:525
sendIQ2 @ XmppConnection.js:523
ping @ strophe.ping.js:89
(anonymous) @ strophe.ping.js:120
index.js:154 2022-08-26T05:01:37.200Z [conference.js] <Mce._onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected focus.alpha.jitsi.net 4
i @ index.js:154
_onConferenceFailed @ conference.js:321
r.emit @ events.js:153
r.emit @ events.js:153
pr._allocateConferenceFocusError @ moderator.js:393
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:355
(anonymous) @ moderator.js:315
pr.allocateConferenceFocus @ moderator.js:301
(anonymous) @ moderator.js:402
setTimeout (async)
pr._allocateConferenceFocusError @ moderator.js:401
(anonymous) @ moderator.js:309
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5294
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
(anonymous) @ XmppConnection.js:525
sendIQ2 @ XmppConnection.js:523
ping @ strophe.ping.js:89
(anonymous) @ strophe.ping.js:120

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
