### ISSUE TITLE
Screen Sharing Flickering in Android 13

### ISSUE THREAD

**Issue by alexivaner** [jitsi/jitsi-meet#12098]
### Steps to reproduce:

1. Open Jitsi like usual on Android 13, join the conference as User A
2. User B join to see the behavior
3. User A start to share the screen.
4. User B will see that screen sharing of user A is flickering to black and white (happens randomly)

### Expected behavior:

When Android 13's user starts screen sharing, it will appear normal and smooth.

### Actual behavior:

When the user starts screen sharing on android 13, it will flicker on the opposite user. It looks normal on the owner's phone. Not sure whether this is android 13 bugs, jitsi, or react-native bugs

### Client information:

- Browser / app version:
- Operating System: Android 13

### Additional information:

Anyone facing the same issues?

**Comment by saghul** [comment]
I have been able to reproduce it on a Pixel 6 running Android 13.

**Comment by alexivaner** [comment]
@saghul This bug, is it related to Android 13 Bugs or react-native?

**Comment by saghul** [comment]
I suppose it's Android 13 related, since we haven't changed anything in the RN side and it works well with Android 12.
