### ISSUE TITLE
When on mute and noise suppression is turned on, the microphone blue bubbles are still visible

### ISSUE THREAD

**Issue by cedricroijakkers** [jitsi/jitsi-meet#12092]
### Description:

The little blue bubbles that indicate you are speaking in a meeting are normally switched off when you are on mute. However, if you have noise suppression turned on, and you are on mute, the blue bubbles still show when you are speaking. This leads you to think other people can hear you, but you are effectively on mute, so so you cannot be heard.

### Steps to reproduce:

1. Open Jitsi and log into any room
2. Switch mute on and off again (some people have reported they need to have been on mute at least once for this issue to work)
3. Switch noise suppression on
4. Switch mute on
5. Speak into your microphone

### Expected behavior:

Since you are on mute, the blue bubbles should not appear.

### Actual behavior:

When speaking, the blue bubbles will appear, as if other people can hear you, but since you are on mute they cannot.

### Server information:

- Jitsi Meet version: Docker container version stable-7648-4
- Operating System: Kubernetes 1.23.5 on Ubuntu 18.04.6

### Client information:

- Browser / app version: jisti-meet-electron 2022.8.1
- Operating System: Linux and Windows (possibly others too)

### Additional information:

You can see me talking while also on mute:

![image](https://user-images.githubusercontent.com/15158042/187436544-9793c877-0335-4bc2-b7d1-8e094d911969.png)

**Comment by saghul** [comment]
Ping @andrei-gavrilescu

**Comment by andrei-gavrilescu** [comment]
I'll check it out.
