### ISSUE TITLE
Jitsi Behind OpenVPN

### ISSUE THREAD

**Issue by superteece** [jitsi/jitsi-meet#1209]
I have the Jitsi-Meet package installed from the official repo. The default install works great with no tweaking.

However, when I modify the nginx file for my Jitsi-Meet page to listen on the VPN interface, I am able to connect to the VPN, browse to my Jitsi-Meet page, enter a chat name, proceed to the chat (where I'm asked to share my mic/cam) then nothing happens. I'm stuck on the blue page shown in the attached screenshot.

Switching the nginx file back to listening on all interfaces fixes the issue to where the service works as expected but is accessible from the internet which is not the desired configuration.

My camera light is on and Firefox thinks it is sharing the mic and cam with something.
![jitsi error](https://cloud.githubusercontent.com/assets/9064374/21335536/9b3e973a-c62d-11e6-8c58-05cfb0d1e003.PNG)

**Comment by ZuzooVn** [comment]
@superteece Did you find the solution?
