### ISSUE TITLE
Is it possible to enable camera while doing screen sharing in Jitsi mobile?

### ISSUE THREAD

**Issue by alexivaner** [jitsi/jitsi-meet#12106]
**Is your feature request related to a problem you are facing?**
Hi everyone, currently if we are doing screen sharing in Jitsi Mobile, it will replace the camera track with the screen sharing track, so participants could not see our faces.

**Describe the solution you'd like**
It is possible to do screen sharing while keeping streaming our camera to the conference on mobile devices. I think this is already implemented on the desktop.

**Describe alternatives you've considered**
Is there a way that we could change this programmatically? When creating local tracks for screen sharing, is it possible to instead of  `dispatch(replaceLocalTrack(currentJitsiTrack, track));` we can just add track?

**Comment by saghul** [comment]
That's possible, but more changes would also be necessary. If you look at the last few commits you'll see that we effectively disabled sending multiple tracks on mobile.

This is for performance reasons.

It may change in the future, but for now you won't be able to share your camera and screen at the same time.
