### ISSUE TITLE
Screen sharing stucked in P2P mode

### ISSUE THREAD

**Issue by dbeaudoin** [jitsi/jitsi-meet#12102]
### Description:
Once screen sharing is started in P2P mode it does not transition to server mode if a 3rd participants joins.

### Steps to reproduce:

1- Start meeting with Participant1
2- Join meeting with Participant2
3- From Participant1 start screen sharing
4- Participant2 see Participant1 screen: OK
5- Join meeting with Participant3
6- Participant2 and Participant3 do not see Participant1 screen anymore: NOT OK

From that point on it seems that Participant1 screen sharing connectivity is locked in P2P mode, if Participant1 tries to stop screen sharing and start screen sharing again then it will never work as it seems to only try to connect in P2P mode. In previous sequence, if Participant3 leaves meeting than meetings goes back in P2P mode and then screen sharing becomes visible again for Participant2.

Sequence that works:

1- Start meeting with Participant1
2- Join meeting with Participant2
2- Join meeting with Participant3
3- From Participant1 start screen sharing
6- Participant2 and Participant3 see Participant1 screen anymore: OK

In this sequence when Participant1 initiated its screen sharing, meeting was already in server mode and then screen sharing was functional for evreyone.

### Server information:
Reproducible 100% of the time with meet.jit.si

### Client information:
Tested with latest version of Chrome

**Comment by saghul** [comment]
I am not able to reproduce this.

**Comment by dbeaudoin** [comment]
Tested it also and I cannot reproduce it anymore either. It was reproducible 100% of the time when I opened the issue last week. Is it possible meet.jit.si was updated? Looking through the changes now, it seems that the issue got fix in the lib-jitsi-meet not soo long ago:

https://github.com/jitsi/lib-jitsi-meet/compare/v1493.0.0+3cf3db1a...v1494.0.0+c9be46e2

**Comment by damencho** [comment]
Yep, that is exactly the fix and we released it on meet.jit.si on Aug 31.

**Comment by dbeaudoin** [comment]
Then it all makes sense, thanks for the update @damencho!
