### ISSUE TITLE
iphone ios 16 beta mic issue

### ISSUE THREAD

**Issue by Arzar** [jitsi/jitsi-meet#12111]
When a user joins a meeting with an iphone 12 ios 16 (BETA), other participants on meet.jit.si can not hear them.
When turning on and off the mic of the iphone (by clicking on the mic button in jitsi app), other participants can see the mic icon turning on and off, but no sound.

The mic is working OK if downgrading to ios 15.6

### Steps to reproduce:

1) Having a meeting on meet.jit.si from PC
2) A user with iphone 12 and ios 16 joins the meeting, mic on, and start speaking
3) Check that other participants can hear the iphone user.

### Client information:
Iphone 12
iOS 16.0 (20A5358a) Beta
Jitsi Meet (22.4.0 build 1657277707)

PC users
Windows 10, chrome 104.0
meet.jit.si

**Comment by saghul** [comment]
Thanks for the feedback!

**Comment by saghul** [comment]
Have you observed this behavior in our beta app?

**Comment by Arzar** [comment]
Yes, we did the test today with the beta app (version 22.5.1 build 1662035155) and it's the same issue.

**Comment by saghul** [comment]
Thanks for confirming.

**Comment by saghul** [comment]
I could reproduce this with iPadOS 16 beta 17.

**Comment by Arzar** [comment]
Are you using a bluetooth headset by any chance? We tried today with a bluetooth headset and couldn’t reproduce the bug too. 

It happens only when we join the meeting with an iphone without any headset plugged. 

Also, even without headset, we found that sometimes the sound is delivered as expected for an instant just after joining the meeting. And in some rare cases the sound is actually delivered as expected (no bug). In this case switching the audio device to "phone" trigger the bug again and the sound stop being delivered.

**Comment by saghul** [comment]
I was not using a headset with the iPad, just on the desktop.

**Comment by Arzar** [comment]
Thanks... Not sure what's going on with our device then.

Just one last thing, it's also easier to reproduce when leaving and joining again the same conference. First time joining the sound issue is not always triggered but after leaving/joining we never have sound.

**Comment by Arzar** [comment]
Thanks.
On our side, we still have the same sound issue, even with the latest RC (20A362)

**Comment by saghul** [comment]
Our QA was unable to repro either.
