### ISSUE TITLE
trying to deploy on netlify

### ISSUE THREAD

**Issue by deepakgit1** [jitsi/jitsi-meet#12119]
hello,
I am trying to deploy jitsi-meet frontend on netlify but getting this issue
![Screenshot from 2022-09-02 18-16-59](https://user-images.githubusercontent.com/93158532/188149052-c000fa60-7dc8-4550-837d-5eebf82d2175.png)

**Comment by saghul** [comment]
Did you configure CORS correctly? (I have no experience with netlify)

**Comment by deepakgit1** [comment]
It is running properly on local.. but when i deployed it on netlify. it gives "UnhandledError: Strophe: request id 2.2 error 0 happened Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 2.2 error 0 happened" this error.
