### ISSUE TITLE
Changes in the main.json file under lang folder are not reflecting in the UI

### ISSUE THREAD

**Issue by Swapnilsimplecrm** [jitsi/jitsi-meet#12112]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
You need to rebuild the frontend with `make`.

**Comment by haseeb-neslit** [comment]
@saghul I am stuck in the same issue that Changes in the main.json file not getting reflected. And I am running [Jitsi Meet docker](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/)

How can i resolve this. If i run `make .` inside /usr/share/jitsi-meet. It says `make: Nothing to be done for '.'.`

**Comment by damencho** [comment]
You need to checkout the source code and compile that and deploy the result
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-jitsi-meet#building-the-sources
