### ISSUE TITLE
Highlight private message

### ISSUE THREAD

**Issue by opk12** [jitsi/jitsi-meet#12128]
**Is your feature request related to a problem you are facing?**
The Android app's group video chat view displays incoming messages in the bar at the top. But there is no visual clue that I got a private message, for example

- it has the same rendering as any group message
- it is easily missed, if you were looking away for the few seconds that it was visible in the top bar, or if the top bar is taken over by a subsequent group message

So I often find myself wondering whether a message looks like it may be private (and not sent to the group by error) and switching to the chat window to check "just in case".

**Describe the solution you'd like**

Receiving a private message should be marked even after the message is not rendered anymore in the top bar. Some ideas:

- a specific rendering at the top bar
- a specific rendering on the relevant user's video tile (if I am only interested in PMs from a specific user)
- a clickable marker somewhere, to go to the unread message (or make the chat button go to the first unread)

**Comment by saghul** [comment]
Thanks for providing feedback. I agree, we can improve there.

**Comment by saghul** [comment]
This got fixed a while ago but we forgot to close this.

**Comment by opk12** [comment]
This is actually unsolved on the current latest (23.3.1 23301001). I think this should be reopened, so it is not forgotten.
* Private messages **in the video chat view** have the same appearance as group messages
* No permanent trace **in the video chat view** of an expired private message

**Comment by saghul** [comment]
Are you sure you tested the latest version?

They are clearly differentiated:

![image](https://github.com/jitsi/jitsi-meet/assets/317464/7484ea8a-49f6-4fbc-b88d-b8216ce7873b)

**Comment by saghul** [comment]
What is an "expired" chat message?

**Comment by opk12** [comment]
Sorry, I mean the view with the webcams :)

* I cannot tell if this is a private or non-private message
* A previous private message was above this one, then disappeared, but left no trace

![out](https://github.com/jitsi/jitsi-meet/assets/40740650/6513a921-d8dc-430f-9050-5a361edfcfca)

**Comment by saghul** [comment]
That is just meant to be an indicator for you to go and check, not the main way to see messages. Otherwise the screen would be flooded with them.

That said, we should indicate in the notification a message is private, indeed.

**Comment by opk12** [comment]
So this can be reopened?

> That is just meant to be an indicator for you to go and check

I'd just expect the indicator to behave like the mainstream chat apps. This could be as simple as a colored dot in the corner.

The doorbell rings, or I go to pick a document. I return, my mind prepares to smile to family and argue with the coworker. As it is now, I find myself obsessively thinking about messages and risk closing the call without checking.
