### ISSUE TITLE
 Mobile Jitsi Meet SDK not honoring disablednotifications for kickParticipant

### ISSUE THREAD

**Issue by corby-github** [jitsi/jitsi-meet#12126]
### Description:

When using the JitsiMeet SDK on Android and iOS version `6.0.0` it looks like the config `disabledNotifications` is not honoring `kickParticipant`. 

Note: We did not test others notifications keys, however `kickParticipant` does appear to work properly on the browser. 

### Expected behavior:

The dialog should not be displayed

### Actual behavior:
The dialog is displayed.
![image](https://user-images.githubusercontent.com/63730925/188461840-60e3c6e5-d7cf-4896-aa8f-f2598b402310.png)

### Details:
This was tested with the following keys: (none seemed to have any any impact)

- dialog.kickParticipantTitle
- notify.kickParticipant
- dialog.kickTitle
- dialog.kickParticipantDialog
- dialog.kickMessage

This was testing in the following scenarios:
#### Scenario 1 - meet.jit.si + JitsiSDKTest w/setConfigOverride
https://meet.jits.si with the [JitsiSDKTest](https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/ios/objc/JitsiSDKTest) mobile app. 
```
JitsiMeetConferenceOptions *defaultOptions
        = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
            builder.serverURL = [NSURL URLWithString:@"https://meet.jit.si"];
            [builder setFeatureFlag:@"welcomepage.enabled" withBoolean:NO];
          [builder setConfigOverride:@"disabledNotifications" withArray:[NSArray arrayWithObjects:@"dialog.kickParticipantTitle", @"notify.kickParticipant", @"dialog.kickTitle", @"dialog.kickParticipantDialog", @"dialog.kickMessage",  nil]];
        }];
    [JitsiMeet sharedInstance].defaultConferenceOptions = defaultOptions;
```

#### Scenario 2 - selfhosted + custom app with SDK w/disabledNotifications added to config.js

Our server running version `2.0.7648`  and using the SDK `6.0.0`

We have modified the config.js to include the following:

```
...
disabledNotifications: [
        'notify.kickParticipant',
        'dialog.kickParticipantTitle',
        'dialog.kickTitle',
        'dialog.kickParticipantDialog',
        'dialog.kickMessage',
    ],
...
```

### Also See:
https://community.jitsi.org/t/mobile-jitsi-meet-sdk-should-disablednotifications-be-honored/116942

**Comment by saghul** [comment]
Ah, wait a minute, I see what's happening.

On mobile we took the liberty of implementing the kicked out notification a bit differently, because it's a final state, so leaving the user in a meeting with just a notification is weird.

We are currently looking into refactoring that experience on web too, and it will probably look something similar to what you saw on mobile: a dialog indicating what happened, and an OK button that would take you to the welcome page or would close the meeting.

So the reason why you are seeing it is because it's not a notification, it's a dialog. It's not possible to prevent dialogs from opening.

What are you trying to accomplish exactly? By hiding that notification a web participant won't know what's happening and they will just see an empty meeting screen.

**Comment by corby-github** [comment]
The goal would be to capture the `CONFERENCE_TERMINATED ` event and handle it ourselves.  This event is also fired on connection issues,  but in those cases an  `error` is provided that can be treated differently.

Having said that, ideally, the SDK would be sent `PARTICIPANT_KICKED` (thats not happening today) and process it that way, never showing the kick dialog to the user.

Like this:
```
 intentFilter.addAction(BroadcastEvent.Type.PARTICIPANT_KICKED.getAction());
 ```

**Comment by saghul** [comment]
I see. That sounds alright.

Are you up for submitting a PR?

**Comment by corby-github** [comment]
Unfortunately, not at this point due to the contributor agreements. I will let you know when that changes.

**Comment by saghul** [comment]
No worries. We'll keep this open and get to it when we can.
