### ISSUE TITLE
Meeting does not start in Chrome on Android

### ISSUE THREAD

**Issue by alexeyvolkoff** [jitsi/jitsi-meet#12121]
Hi,
I have an issue with joining a call from Chrome on Android. Join button sends me back to name input, whatever I enter - it sends me back and opens the keyboard.
![IMG_20220903_190937 width="960"](https://user-images.githubusercontent.com/5536986/188281605-5204e431-5491-45dc-8de3-32e9eb39fef1.jpg)

Tried to debug over USB, the only suspicious thing is  this
`er>:  (TIME) Strophe connected:	 156730
lib-jitsi-meet.min.js:2 2022-09-03T16:26:03.424Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  My Jabber ID: 988724b3-c269-419c-9391-289cd20f8407@meet.jit.si/0aX00u7aW_lj
lib-jitsi-meet.min.js:2 2022-09-03T16:26:03.686Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Strophe: Websocket closed unexpectedly Script: null Line: null Column: null StackTrace:  Error: Strophe: Websocket closed unexpectedly
    at ut.Strophe.log (https://web-cdn.jitsi.net/meetjitsi_6516.3261/libs/lib-jitsi-meet.min.js?v=6516.3261:2:449245)
    at Object.error (https://web-cdn.jitsi.net/meetjitsi_6516.3261/libs/lib-jitsi-meet.min.js?v=6516.3261:2:146409)
    at O.Websocket._onClose (https://web-cdn.jitsi.net/meetjitsi_6516.3261/libs/lib-jitsi-meet.min.js?v=6516.3261:2:185221)
r @ VM11 lib-jitsi-meet.min.js:2
getGlobalOnErrorHandler @ VM11 lib-jitsi-meet.min.js:2
window.onerror @ VM10 app.bundle.min.js:138
callErrorHandler @ VM11 lib-jitsi-meet.min.js:2
ut.Strophe.log @ VM11 lib-jitsi-meet.min.js:2
error @ VM11 lib-jitsi-meet.min.js:2
_onClose @ VM11 lib-jitsi-meet.min.js:2
lib-jitsi-meet.min.js:2 2022-09-03T16:26:03.687Z [modules/xmpp/strophe.util.js] <ut.Strophe.log>:  Strophe: Websocket closed unexpectedly
r @ VM11 lib-jitsi-meet.min.js:2
ut.Strophe.log @ VM11 lib-jitsi-meet.min.js:2
error @ VM11 lib-jitsi-meet.min.js:2
_onClose @ VM11 lib-jitsi-meet.min.js:2
lib-jitsi-meet.min.js:2 2022-09-03T16:26:03.688Z [modules/xmpp/strophe.ping.js] <Vs.stopInterval>:  Ping interval cleared`

Any idea?

**Comment by saghul** [comment]
The screenshot shows some site but the logs suggest you are being connected to meet.jit.si. Are you using the iframe API?

The logs you pasted show a connection error.

**Comment by alexeyvolkoff** [comment]
Yes, we use iframe API to public instance

**Comment by saghul** [comment]
Can you use Chrome's remote inspector to capture the full log?

**Comment by alexeyvolkoff** [comment]
Here is the full log

2022-09-06T12:15:25.676Z [modules/RTC/RTCUtils.js] <Wn.<anonymous>>:  Got media constraints:  {"video":false,"audio":{"autoGainControl":true,"deviceId":"default","echoCancellation":true,"noiseSuppression":true}}
Logger.js:154 2022-09-06T12:15:25.739Z [modules/RTC/RTCUtils.js] onUserMediaSuccess
TrackVADEmitter.js:112 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
_initializeAudioContext @ TrackVADEmitter.js:112
hl @ TrackVADEmitter.js:66
(anonymous) @ TrackVADEmitter.js:91
Promise.then (async)
create @ TrackVADEmitter.js:85
(anonymous) @ VADAudioAnalyser.js:162
Promise.then (async)
_trackAdded @ VADAudioAnalyser.js:161
r.emit @ events.js:158
Mh._setupNewTrack @ JitsiConference.js:1443
(anonymous) @ JitsiConference.js:1335
Promise.then (async)
Mh.replaceTrack @ JitsiConference.js:1333
Mh.addTrack @ JitsiConference.js:1158
mF @ app.bundle.min.js?v=6516.3261:136
(anonymous) @ app.bundle.min.js?v=6516.3261:136
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
o @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
_createRoom @ app.bundle.min.js?v=6516.3261:138
startConference @ app.bundle.min.js?v=6516.3261:138
prejoinStart @ app.bundle.min.js?v=6516.3261:138
await in prejoinStart (async)
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
o @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:2
_onJoinButtonClick @ app.bundle.min.js?v=6516.3261:138
Ue @ app.bundle.min.js?v=6516.3261:138
Ke @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
Aa @ app.bundle.min.js?v=6516.3261:138
Ta @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
Re @ app.bundle.min.js?v=6516.3261:138
(anonymous) @ app.bundle.min.js?v=6516.3261:138
Ma @ app.bundle.min.js?v=6516.3261:138
Qt @ app.bundle.min.js?v=6516.3261:138
Jt @ app.bundle.min.js?v=6516.3261:138
t.unstable_runWithPriority @ app.bundle.min.js?v=6516.3261:138
Wr @ app.bundle.min.js?v=6516.3261:138
Ie @ app.bundle.min.js?v=6516.3261:138
$t @ app.bundle.min.js?v=6516.3261:138
Show 160 more frames
Logger.js:154 2022-09-06T12:15:35.219Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Strophe: Websocket closed unexpectedly Script: null Line: null Column: null StackTrace:  Error: Strophe: Websocket closed unexpectedly
    at ut.Strophe.log (https://web-cdn.jitsi.net/meetjitsi_6516.3261/libs/lib-jitsi-meet.min.js?v=6516.3261:2:449245)
    at Object.error (https://web-cdn.jitsi.net/meetjitsi_6516.3261/libs/lib-jitsi-meet.min.js?v=6516.3261:2:146409)
    at O.Websocket._onClose (https://web-cdn.jitsi.net/meetjitsi_6516.3261/libs/lib-jitsi-meet.min.js?v=6516.3261:2:185221)
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:532
window.onerror @ app.bundle.min.js?v=6516.3261:138
callErrorHandler @ GlobalOnErrorHandler.js:61
ut.Strophe.log @ strophe.util.js:88
error @ strophe.umd.js:1392
_onClose @ strophe.umd.js:5676
Logger.js:154 2022-09-06T12:15:35.221Z [modules/xmpp/strophe.util.js] <ut.Strophe.log>:  Strophe: Websocket closed unexpectedly
r @ Logger.js:154
ut.Strophe.log @ strophe.util.js:89
error @ strophe.umd.js:1392
_onClose @ strophe.umd.js:5676
Logger.js:154 2022-09-06T12:15:35.223Z [modules/xmpp/strophe.ping.js] <Vs.stopInterval>:  Ping interval cleared
Logger.js:154 2022-09-06T12:15:35.224Z [modules/xmpp/ResumeTask.js] <Os._scheduleResume>:  Will try to resume the XMPP connection in 1852ms
Logger.js:154 2022-09-06T12:15:37.078Z [modules/xmpp/ResumeTask.js] <Os._resumeConnection>:  Trying to resume the XMPP connection
Logger.js:154 2022-09-06T12:15:37.081Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  (TIME) Strophe connecting:	 63048
Logger.js:154 2022-09-06T12:15:37.608Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  (TIME) Strophe bindrequired:	 63575.7999997139
Logger.js:154 2022-09-06T12:15:37.712Z [modules/xmpp/ResumeTask.js] <Os._cancelResume>:  Canceling connection resume task
Logger.js:154 2022-09-06T12:15:37.715Z [modules/xmpp/strophe.ping.js] <Vs.startInterval>:  XMPP pings will be sent every 10000 ms
Logger.js:154 2022-09-06T12:15:37.715Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  (TIME) Strophe connected:	 63682.7999997139
Logger.js:154 2022-09-06T12:15:37.716Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  My Jabber ID: f4b77e49-4231-4744-ba05-95cf09d4040d@meet.jit.si/eg9u0_-3eE_R

**Comment by saghul** [comment]
Are you being any filtering firewall? Looks like your WebSocket connections are getting interrupted.

**Comment by alexeyvolkoff** [comment]
@saghul Just tested the same web app running on my development PC and it works just fine. The same app running on production server does not work. With the same mobile phone, same mobile Chrome. The only difference is - development setup does not have https, production has https.

**Comment by saghul** [comment]
WebRTC does not work over HTTP, so that's weird...

**Comment by alexeyvolkoff** [comment]
it does not allow camera, but works, at least Jont button works as expected

**Comment by saghul** [comment]
That's a very loose definition of "works" :-)

I really don't know what's going on, but if it works when not being embedded maybe there is something there, like a strict CSP policy or something.

I don't think there is anything we can do on our end.

**Comment by alexeyvolkoff** [comment]
I know, but at least I need a idea.
-My web app is using public instance jitsi.meet.si
-Running on my PC 192.168.0.xxx: Join button works. No mic, no camera allowed because of http, but conversation starts.
-Running on server with https: - same mobile phone, same browser: Join button does not work.
-Desktop browsers work fine in both scenarios.

**Comment by alexeyvolkoff** [comment]
@saghul 
I got some interesting updates.
Just tried the same web app with Brave on Android - and it works!  
The issue is only with Chrome. Did they remove WebRTC or what?

**Comment by saghul** [comment]
Surely they didn't. I still have no idea, sorry...

**Comment by alexeyvolkoff** [comment]
The same problem with official meet.jit.si page. Meeting does not start in Chrome but starts in Brave. 
Please can anyone confirm?

**Comment by saghul** [comment]
I cannot reproduce this. Just tried on a Pixel 6 with Chrome. Android 13 Beta, but that doesn't really matter.

Must be something in your device / environment...

**Comment by alexeyvolkoff** [comment]
hmmm very interesting,  thank you! I have Android 10, Mi 9SE.  Chrome 108.0.5359. I will continue investigating
