### ISSUE TITLE
Self host Jitsi Server: Microfon doesn't work, participant cannot hear each other

### ISSUE THREAD

**Issue by esra9910** [jitsi/jitsi-meet#12131]
### Description: 
Hello Everyone, I tried to Self host my Jitsi Server with an Ubuntu Machine. 

### Steps to reproduce:

1.  I start the Meeting with other participants
2.  I click on the allowed Microphone 
3.  No one can hear me , nor can I hear them

### Server information:

- Jitsi Meet version: 2.0.7648 
- Operating System: Ubuntu VM 

### Client information:

- Browser / app version: tried with Chrome and Safari
- Operating System:  MacOS

### Additional information:

I tried this Documentation:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/#domain-of-your-server-and-set-up-dns
https://www.youtube.com/watch?v=hpMqUAuHAtY this helps also with the understanding

**Comment by saghul** [comment]
Please share your browser console logs.

**Comment by dakur** [comment]
@esra9910 Do other participants hear each other? Do you have iOS? We noticed such problem with iOS users – they see other participants, but can't hear them and they can't hear him, but the others can talk to each other.

**Comment by esra9910** [comment]
@dakur No i don't have IOS but good to know. So I solve this Problem.

**Comment by dakur** [comment]
@esra9910 Ok. But maybe you could elaborate on how did you solve it, so that others who might have the same problem know what to do.
