### ISSUE TITLE
muteEveryone command improvement

### ISSUE THREAD

**Issue by Flying-Light** [jitsi/jitsi-meet#12134]
**Is your feature request related to a problem you are facing?**
Some moderators do not know how to dis-allow participants to unmute themselves later, and some maybe also forget to change the checkbox.

**Describe the solution you'd like**
Solution is to improve the muteEveryone command to be like this

`api.executeCommand('muteEveryone', 'video', moderated: boolean);`
`api.executeCommand('muteEveryone', 'audio', moderated: boolean);`

This way we can set "whether to let participants unmute themselves later" from commands without need to use the GUI.

That is it :)

**Comment by blazmonster** [comment]
Is nobody working on this feature?

**Comment by Flying-Light** [comment]
As far as I know, no one working on it, it seems that no one interested on it:).

**Comment by Flying-Light** [comment]
> Is nobody working on this feature?

As far as I know, no one working on it, it seems that no one interested on it:).
