### ISSUE TITLE
User Name from LDAP

### ISSUE THREAD

**Issue by sumarokov89** [jitsi/jitsi-meet#12137]
**Is your feature request related to a problem you are facing?**
We are using Docker Jitsi with LDAP authentication, problem is that users can write any Display Name they want e.g. a swear word

**Describe the solution you'd like**
Active directory already have all necessary information about users, so that would be great if Display Name will come from AD. And users won't be able to change it.

There should be two environment variables i gues, like:
LDAP_DISPLAY_NAME - getting name from ldap
DISPLAY_NAME_BLOCK - name change prohibition

**Comment by damencho** [comment]
Is this supported by the ldap module? 
We do not maintain that, so you first need to check that part.

**Comment by saghul** [comment]
Blocking the display name change is also not something standard. There is a community module that does it.

I'd say we close here, since there is nothing actionable from our end. LDAP support is community maintained.

**Comment by sumarokov89** [comment]
Got it. Thanks for your time!

**Comment by filoucrackeur** [comment]
i need the feature and i'm not the only one

https://community.jitsi.org/t/jitsi-meet-ldap-active-directory-and-see-displayname-of-users-this-is-possible/22596

i need to specify field for jitsi to display name

LDAP_DISPLAY_NAME is a good solution instead of "me"
