### ISSUE TITLE
remote video resolution too low on iPad

### ISSUE THREAD

**Issue by quangcm** [jitsi/jitsi-meet#1214]
I tried to run app on iPhone and iPad. There's no problem with iPhone. But on iPad, the remote video resolution is very low. 
I tried conference of iPad and browser (google chrome).
Even if I set resolution 720 for browser, then the video stream which received on iPad still has very low resolution.
Does any one know why and how to configure to retrieve higher resolution of remote video on iPad?

**Comment by lyubomir** [comment]
@quangcm, I suppose the following could be involved:

- The network bandwidth available to the iPad. Both the client and the server continually estimate the available network bandwidth and adjust the video resolution received by the client. If there's not enough network bandwidth available to the client to received the high quality resolution, lower quality resolutions will be received.

- We haven't worked on iPad support yet so the app gets displayed as an iPhone app in 1x or 2x scale. The 2x scale tends to look as lower quality in general.

**Comment by quangcm** [comment]
@lyubomir, Thank you for responding, I will try to study more in source code

**Comment by lyubomir** [comment]
https://github.com/jitsi/jitsi-meet/commit/b96ca538e47f37baa70e0e7f59babcce561cfc5d added support for iPad which should allow the app to run in the native resolution rather than being scaled up from an iPhone app. I expect that to improve the perceived video quality. Is that the case for you, @quangcm?

**Comment by quangcm** [comment]
@lyubomir thank you for informing me. I will try it
