### ISSUE TITLE
Can't see participant's camera (SDK Android)

### ISSUE THREAD

**Issue by sandypriyatna** [jitsi/jitsi-meet#12146]
I'd like to ask you a question with using the SDK on Android. When I started entering the video meet room then I was able to activate the camera, and my camera appeared another device. However, when other participants activated the camera, I couldn't see it, even though the participant's camera was on. I tried this case only on Android when using the SDK via Android.

There may be a solution to this problem, thanks for the help

Same case as the following issue #11977

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by sandypriyatna** [comment]
I'm using the 2.9.0 version

**Comment by saghul** [comment]
Sorry that version is ancient. https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#290-2020-05-28 Please update, we cannot afford to support such old versions.

**Comment by sandypriyatna** [comment]
Thank you so much, I forgot to check the release notes as well. Have a nice day
