### ISSUE TITLE
Only one user can see translated captions

### ISSUE THREAD

**Issue by devByGelu** [jitsi/jitsi-meet#12153]
### Description:

Only one moderator can receive translated subtitles from other participants.
Other participants and delegated moderators can't toggle their subtitles/choose a language.

Only the moderator who clicked subtitles first can see the translated transcripts from other people (closed captions).

### Steps to reproduce:

0. Set up `docker-jitsi-meet-stable-7648-4`
1. Create and join a meeting 
2. At toolbar, find subtitles and choose a language
3. Invite another participant and let them speak

4. **Notice that you can receive translated transcripts from their voice input, while the other participant cannot choose a language**

5. Grant the said participant moderator status 
6. As the other participant, find subtitles and choose a language

7. **Notice that when the other moderator speaks, you don't receive translated transcripts**

### Actual behavior:

Other users must be able to enable translation and receive translated transcripts

### Server information:

- Jitsi Meet version: `docker-jitsi-meet-stable-7648-4`
- Operating System: `Docker desktop 4.10.1 (82475)`

### Client information:

- Browser / app version:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/41291228/189382326-9f7c56ca-52da-4b00-bf01-205c36782c85.png">

- Operating System:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/41291228/189381095-821ea5c7-5b63-4a2b-8b78-6bbb12e74f0d.png">

### Additional tests

I compiled a custom `jitsi-meet` where the **subtitles button always shows** 

Then I integrated the build/image to `docker-jitsi-meet-stable-7648-4`

`react/features/subtitles/components/AbstractClosedCaptionButton.js`
<img width="537" alt="image" src="https://user-images.githubusercontent.com/41291228/189380064-2861ec51-8565-4ed2-bc84-946fa7eb964e.png">

..still doesn't work for other participants other than the first moderator who enabled subtitles

**Comment by saghul** [comment]
IIRC this is intentional. Once the moderator enables CC, the guests will also see the CC button and they can toggle them on. Is this not what you observe.

**Comment by charles-zablit** [comment]
Thanks you for the quick reply @saghul 

> Is this not what you observe

No, when the moderator enables CC, the guest do not see the CC button, and do not see the subtitles either. If I promote the guest to moderator, they will have the CC button and the subtitles will show up.

**Comment by devByGelu** [comment]
> Hi, I am having the exact same issue, when using the VOSK trancription server. Are you using the Google transcription API or another service? I'm not sure if this comes from Jigasi or jitsi-web.
> 
> Thanks in advance

I'm using the Google transcription API. I'm quite convinced that the problem lies somewhere in jigasi, but I have yet to understand the code. 

Right now we're testing if using http://jaas.8x8.vc this is no longer a problem.

**Comment by devByGelu** [comment]
> IIRC this is intentional. Once the moderator enables CC, the guests will also see the CC button and they can toggle them on. Is this not what you observe.

My bad, I've updated the label:
Only one user can activate subtitles -> Only one user can see translated captions

Only the first participant who activated subtitles (most likely moderator) can actually see translated captions on their screens.

**Comment by charles-zablit** [comment]
Thanks for the reply!

> Only the first participant who activated subtitles (most likely moderator) can actually see translated captions on their screens.

I am having the same issue as well.
Once the moderator has activated the subtitles, do the regular participants see the "CC" button?

Also, it seems to be working on the Linto AI jitsi demo: https://jitsi.linto.ai/
I believe they are also using Jigasi, but I don't know which version.

**Comment by saghul** [comment]
Sorry, I misspoke. It was almost correct. This is what should be happening:

- Moderator enables subtitles: the button shows for everyone, and it's ON
- The "TR" label should be visible for all
- Non-moderators can stop it for themselves

If you are not seeing this, what versions of everything did you deploy?

**Comment by charles-zablit** [comment]
> Moderator enables subtitles: the button shows for everyone, and it's ON

In my case, subtitles show only for the moderator, and the button doesn't show for anyone that is not a moderator. Subtitles are hidden as well for guests.

```
- jitsi/web stable-7648-4
- jitsi/jvb stable-7648-4
- jitsi/jicofo stable-7648-4
- jitsi/prosody stable-7648-4
- jigasi latest
- vosk latest
```

**Comment by charles-zablit** [comment]
After some analysis, it looks like the issue comes from the Jigasi Transcriber joining as a visible participant. [Related code](https://github.com/jitsi/jitsi-meet/blob/f4985d8028803e8afd95f517e498bb4b43a22e23/react/features/transcribing/middleware.js#L50-L56).

I am having issues setting up a `hiddenDomain` for the transcriber.

@devByGelu do you think your issue is caused by a similar thing?

**Comment by devByGelu** [comment]
> I am having the same issue as well. Once the moderator has activated the subtitles, do the regular participants see the "CC" button?
> 
They don't IIRC. I'll try to revisit this issue this weekend.

**Comment by devByGelu** [comment]
> After some analysis, it looks like the issue comes from the Jigasi Transcriber joining as a visible participant. [Related code](https://github.com/jitsi/jitsi-meet/blob/f4985d8028803e8afd95f517e498bb4b43a22e23/react/features/transcribing/middleware.js#L50-L56).
> 
> I am having issues setting up a `hiddenDomain` for the transcriber.
> 
> @devByGelu do you think your issue is caused by a similar thing?

I couldn't say for sure. 
Do you need help getting the "CC" button to show up for other participants?

**Comment by charles-zablit** [comment]
> Do you need help getting the subtitles button to "artificially" show up for other participants? @charles-zablit
No problem, thanks :)

I've managed to fix the issue. You have to specify a `hiddenDomain` in jitsi's `config.js`. You can use `recorder.meet.jitsi` if using docker. Then create a user in prosody for that domain named `jigasi`, give it a password and fill in the config in sip-communications.properties.
Jigasi should login as a hidden participant and subtitles should be working as expected, for moderators and hosts.

**Comment by devByGelu** [comment]
You're awesome!

I'll try if i can recreate your fix in docker, then hopefully create a PR for the docs for other people to see.
Were there any other resources that helped you implement the fix?

**Comment by charles-zablit** [comment]
Here are the forums threads that helped me to find the issue:
- [jigasi open source alternative of Google Speech to Text](https://community.jitsi.org/t/jigasi-open-source-alternative-of-google-speech-to-text/20739)
- [Jigasi Transcriber needs to be hidden participant](https://community.jitsi.org/t/jigasi-transcriber-needs-to-be-hidden-participant/117649)

**Comment by oerodriguezn** [comment]
> > Do you need help getting the subtitles button to "artificially" show up for other participants? @charles-zablit
> > No problem, thanks :)
> 
> I've managed to fix the issue. You have to specify a `hiddenDomain` in jitsi's `config.js`. You can use `recorder.meet.jitsi` if using docker. Then create a user in prosody for that domain named `jigasi`, give it a password and fill in the config in sip-communications.properties. Jigasi should login as a hidden participant and subtitles should be working as expected, for moderators and hosts.

Question: Does it works both ways? I mean with 2 differents traslations, for example the moderator traslating from english to spanish and the guest traslating from spanish to english.

**Comment by shooding** [comment]
Update on this issue, the latest stable-9457 version includes updates of refactor transcriptions api from pull request merged to master [https://github.com/jitsi/jitsi-meet/pull/14144](https://github.com/jitsi/jitsi-meet/pull/14144). From there you see `AbstractClosedCaptionButton.tsx` is now using an updated function `canStartSubtitles` as replacement.
@devByGelu 's method is forcing visible = true for all participants is not enough if you're building from an legacy version prior to that, participants still not getting the transcription.

Do some code tracing, participants other than the moderator is automatically receiving `endpointMessageReceived` in `conference.js`.

Then `react/features/subtitles/middleware.ts` is registering (listening) to this event `ENDPOINT_MESSAGE_RECEIVED` and then output `newTranscriptMessage` to screen.

Therefore, it's recommended to upgrade server version to stable-9457 and do your customization from there.

**Comment by shooding** [comment]
confirm hiddenDomain solves the problem. 
setup jitsi-meet 
`VirtualHost recorder.<domain>`
and set recorder.<domain> as hiddenDomain. Only one domain can be hiddenDomain, and most of the time recorder will be used first. In my scenario, only transcriber is needed but still use `recorder.<domain>` is fine.

```
/etc/init.d/prosody restart
```
then you can use 
```
prosodyctl register jigasi recorder.<domain> <raw-password> 
```
and found newly created account at /var/lib/prosody/conf.d/recorder.<domain>/accounts/jigasi.dat
Then fill the `base64(password)` to sip-communicator.properties of jigasi and everything works.

I was wrongly registering jigasi under `auth.<domain>` and therefore it joins as normal participant.
