### ISSUE TITLE
Disable sound for presentation mode

### ISSUE THREAD

**Issue by dronmaxman** [jitsi/jitsi-meet#12161]
**Describe the solution you'd like**
Disable sound (not microphone) in web interface  and mobile client for presentation mode. If I want to use ipad for share screen and PC or other device at same room at same time I can't disable sound and get echo.

**Comment by omarY23** [comment]
I would like to work on this issue. I will be done with setting up the development environment by tomorrow. Please assign this to me and since I am new to this repo, kindly guide me through

**Comment by saghul** [comment]
> 
> 
> **Describe the solution you'd like**
> 
> Disable sound (not microphone) in web interface  and mobile client for presentation mode. If I want to use ipad for share screen and PC or other device at same room at same time I can't disable sound and get echo.
> 
> 
> 
> 

This is not currently possible. The volume can't go all the way down to 0 while "in a call" and when in a meeting we are "in a call" from the system standpoint.

**Comment by omarY23** [comment]
Ok..I got it!

**Comment by Kreshnik** [comment]
@saghul I am in need of the same feature but on the Android SDK, which components (classes) would need to be changed to make this feature available there?

**Comment by saghul** [comment]
I don't know. AFAIK it's not possible because when the audio has been marked as a call it just can't go to zero.

**Comment by Kreshnik** [comment]
Thank you @saghul for the swift response, I see. This will be a tough nut to crack.
