### ISSUE TITLE
Self Host Jitsi Server: Polls aren't anonymous and others can create Polls too.

### ISSUE THREAD

**Issue by esra9910** [jitsi/jitsi-meet#12165]
### Description:
**I successfully self hosted my Jitsi server but I have a Problem. 
As a Moderator I create polls but others can create polls too(Persons who aren't Moderators). How can I disable it? 
Also the answer of the polls aren't anonymous anyone can see the voters answers.How can I change that?**

### Steps to reproduce:

1.  Moderator open polls
2.  Creates and Click on Polls
3.  Other participants can see answer (isn't anonymous) and others can start polls too.

### Server information:

- Operating System: Ubuntu

### Client information:

- Browser / app version: Safari

### Additional information:

I want that the polls are **anonymous** and that **ONLY the moderator** can create Polls. How can I do it?

<img width="496" alt="Jitsi" src="https://user-images.githubusercontent.com/65394101/189892310-c5b813b7-2c0b-42c7-8048-bc22025f547b.png">

**Comment by saghul** [comment]
This is not currently possible. We have open issues / PRs for both of those requirements, please search in the issue list.
