### ISSUE TITLE
iOS Only - Camera Enable not working - red screen - when only 2 participants in the conference and one of them enable video.  

### ISSUE THREAD

**Issue by SayyedUmar** [jitsi/jitsi-meet#12173]
### Description:
iOS Only - Camera Enable not working - red screen - when only 2 participants in the conference and one of them enable video.  

the same is working fine for android is all scenarios. its showing only in iOS when both of the participants are iPhone users.
I have attached simulator screen shot in this scenario the other user is iphone user. server url is default jitsi server url. 

### Steps to reproduce:

1. install in 2 ios devices
2. connect both of them in same conference
3. ask one of them to share their screen  or enable video
4. shows red screen to the other user

### Server information:
![simulator_screenshot_2207F4BF-020A-4E24-BFB1-D06429E19B62](https://user-images.githubusercontent.com/7055884/190158561-d304562e-d90a-41c9-9bdb-2490c6912d88.png)

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by psi-4ward** [comment]
Did you try it meet.jit.si? Or on a self hosted instance?

**Comment by saghul** [comment]
Please specify the server and client SDK versions.

**Comment by SayyedUmar** [comment]
client stdk: stable/jitsi-meet_7648 
server sdk: jitsi default server ie https://meet.jit.si

**Comment by saghul** [comment]
> client stdk: stable/jitsi-meet_7648

That is not a client SDK release. Please use 6.1.0 or 6.2.0-beta.1.
