### ISSUE TITLE
Start call screen directly on Android

### ISSUE THREAD

**Issue by Topstar88** [jitsi/jitsi-meet#12180]
![image](https://user-images.githubusercontent.com/54676035/190270903-b00de9ee-672e-40ff-8fcb-6e2658c0b528.png)
Hi, I have been struggling to disable this screen and start calling directly on the android platform. But no luck yet.
Please let me know if anyone could help me with this topic.
Regards.

**Comment by saghul** [comment]
Set this feature flag to false: https://github.com/jitsi/jitsi-meet/blob/f0a45a997618112819a4fd82f05e3c9fba737140/react/features/base/flags/constants.ts#L167
