### ISSUE TITLE
Javascript- heap out of memory Error with 2.0.7648 

### ISSUE THREAD

**Issue by Abhishek-Vijay** [jitsi/jitsi-meet#12190]
Hi,

I have used jitsi-meet tag 2.0.7439 and it was working fine.
but as I am trying to get latest stable release, 2.0.7648 or 2.0.7577 , I am getting javascript - heap out of memory error when I am doing make dev. I have already tried updating "--max-old-space-size=8192" for node but still same error I am getting in 2 windows machines.
I am having windows 11 and wsl2. 
can you please check if anyone else is getting same issue.

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[BABEL] Note: The code generator has deoptimised the styling of /jitsi-meet-web/jitsi-meet-web_7648/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.

<--- Last few GCs --->

[907:0x505b5a0]    77076 ms: Mark-sweep (reduce) 2042.8 (2082.2) -> 2042.1 (2083.0) MB, 1483.8 / 0.4 ms  (average mu = 0.099, current mu = 0.012) allocation failure scavenge might not succeed
[907:0x505b5a0]    78491 ms: Mark-sweep (reduce) 2043.5 (2083.0) -> 2042.5 (2083.2) MB, 1405.9 / 0.6 ms  (average mu = 0.055, current mu = 0.007) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [webpack]
 2: 0xa1c193 node::FatalError(char const*, char const*) [webpack]
 3: 0xcf8dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
 4: 0xcf9137 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
 5: 0xeb09d5  [webpack]
 6: 0xec069d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
 7: 0xec339e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
 8: 0xe848da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
 9: 0x11fd626 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
10: 0x15f2099  [webpack]
Makefile:112: recipe for target 'dev' failed
make: *** [dev] Aborted

these are the console logs above.

**Comment by saghul** [comment]
How did you set the `"--max-old-space-size=8192"` option on Windows?

**Comment by Abhishek-Vijay** [comment]
$env:NODE_OPTIONS="--max-old-space-size=8192"

I have used this command in powershell. 
but it worked if I use this command in wsl - "export NODE_OPTIONS=--max-old-space-size=8192"

**Comment by saghul** [comment]
I'm not familiar with the Powershell syntax, but the latter is correct.
