### ISSUE TITLE
Mobile app: some UI elements not available for localization 

### ISSUE THREAD

**Issue by nomadbyte** [jitsi/jitsi-meet#12207]
### Description:

Android app Jitsi-Meet (22.5.1) on Android 12.0 (Pixel 4a). Some UI elements always appear in English instead of the corresponding locally set System Language.

For example,

- the App's main menu (on the bottom): Recent, Calendar, Settings
- Settings: Help, Privacy, Terms

### Steps to reproduce:

1. Enable non-English System Language (e.g. Deutch)
2. Open Jitsi-Meet app on Android (close it first, if it's already running)
3. App's menu on the bottom still appears in English (Recent, Calendar, Settings)
4. Open "Settings" -- some of the strings are still in English (Help, Privacy, Terms)

### Expected behavior:

The UI elements are localized properly, per localized version of `main.json` (`main-de.json` for Deutch).

Apparently, the corresponding strings used in Android app UI are missing from `main.json`.

For example, currently, `main.json` references only one instance of "Recent" and this one is for Welcome page for web-app, and this appears correctly localized.

### Actual behavior:

1. Android's app UI strings are referenced in `main.json`
2. The referenced strings are properly localized

### Client information:

- App version: Jitsi-Meet 22.5.1
- Operating System: Android 12.0

**Comment by saghul** [comment]
We rely on community contributions for translations.

That means that until a given language is fully translated the English / original translation will show in its place.

**Comment by saghul** [comment]
Note that translations are frozen in the app, so what tou see on the repo is usually ahead.

You can use our beta versions for a more up to date app.

**Comment by nomadbyte** [comment]
I don't think the strings in question are present in the `main.json`. That is these controls/labels are not set up to be translatable in the UI code for the app.

**Comment by saghul** [comment]
Ah, you're right. We missed this when we refactored the tabs as we moved to react-navigation: https://github.com/jitsi/jitsi-meet/blob/e38f9a293b4cb4378b58903026d115af6c3df93c/react/features/mobile/navigation/components/welcome/components/WelcomePageTabs.js#L80

**Comment by saghul** [comment]
Fixed in 22.6.0 / SDK 6.2.2
