### ISSUE TITLE
Firefox with media.autoplay.enabled=false

### ISSUE THREAD

**Issue by mleduque** [jitsi/jitsi-meet#1221]
I tried to use jitsi-meet (the version deployed on meet.jit.si) with firefox 50 (ubuntu 16.10), but couldn't get it to work. It took me some time to find out that if I changed back media.autoplay.enabled to its default value, true, all worked correctly.

Now, media.autoplay.enabled=false is mostly required to bring some sanity to the web nowadays.

Symptoms: with media.autoplay.enabled=false, jitsi-meet shows the controls correctly (side bar, top bar, border of the miniatures in the lower right corner), but all video content is black (main big video in the app window and miniatures in the bottom).
Also, no sound.

I discovered that you could right click in the window and use "Play" line the context menu. That shows the main video and the miniatures. In the same menu, the Unmute entry brings back the sound. But this is not very discoverable (I only thought about it once I understood the cause).

**Comment by lyonzy** [comment]
+1 for this - I had almost given up on Jitsi on Firefox until I stumbled on right click -> play. Perhaps a big play button if the video is paused would help users understand what's happened?
