### ISSUE TITLE
setWelcomePageEnabled(false) not working

### ISSUE THREAD

**Issue by siddiquixfaraz** [jitsi/jitsi-meet#12235]
try {
            serverURL  = new URL("https://meet.jit.si");

            JitsiMeetConferenceOptions defaultOptions =
                    new JitsiMeetConferenceOptions.Builder()
                            .setServerURL(serverURL)
                            .setWelcomePageEnabled(false) // not showing any method
                            .build();

            JitsiMeet.setDefaultConferenceOptions(defaultOptions);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

**Comment by saghul** [comment]
What problem are you running into?

**Comment by hunter-kaan-dev** [comment]
@saghul some problem, isn't work only on android

```
setFeatureFlag("welcomepage.enabled", false)
```

**Comment by siddiquixfaraz** [comment]
> What problem are you running into?

Cannot resolve method 'setWelcomePageEnabled' in 'Builder' 
showing this when implementing the method

**Comment by saghul** [comment]
`setWelcomePageEnabled` got deprecated long time ago and was since removed: https://github.com/jitsi/jitsi-meet/commit/c843744df1ee20f22a7da9eaf1ffc98d5c00909a You can use the feature flag now.

**Comment by hunter-kaan-dev** [comment]
@saghul im using `welcomepage.enabled` flag and on my 12 android i see welcome page

```
implementation ('org.jitsi.react:jitsi-meet-sdk:6.1.0') { transitive = true }
```

```kotlin
        optionsBuilder.setFeatureFlag("call-integration.enabled", false)

        // Build with meeting options and feature flags
        val options = optionsBuilder
            .build()

        JitsiMeetPluginActivity.launchActivity(activity, options)
```

**Comment by saghul** [comment]
The default value is `false`, do you see the welcome page if you don't set it at all?
