### ISSUE TITLE
need help in creating multiple conference rooms for individual users

### ISSUE THREAD

**Issue by kkoilada** [jitsi/jitsi-meet#1223]
Hi everyone,

I am new to jitsi github and so wondering if I could receive any help in setting up the multiple conference rooms for individual users and authenticating users before given access to the conf room. Is it possible to integrate this product with freeswitch? Can anyone provide me contacts who can get this work done if it requires more hours to work. Thanks in advance. Any help is much appreciated.

thanks
krish

**Comment by damencho** [comment]
Could you please use the mailinglist for questions and problems before opening issues.

You can use https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md for a quick install on debian/ubuntu server (there was a bug in recent stable configuration so you can try unstable for testing: https://jitsi.org/Main/InstallJitsiMeetDebianNightlyRepository).
Also there is a jigasi for integrating sip peers audio only: https://github.com/jitsi/jigasi, which you can use for integrating it with freeswitch. 

There are people on the mailinglist that can contact you for doing commercial deployment and setup.
