### ISSUE TITLE
dynamic links failure with microg

### ISSUE THREAD

**Issue by tol4711** [jitsi/jitsi-meet#12237]
### Description:
On android devices with microg, clicking the "Join this meeting using the app" link in the browser does not make the jitsi meet app connect to the specified meeting unless it is already running.

### Steps to reproduce:

1. Kill the jitsi meet app if it's runnnig.
2. Browse to a suitable meeting in browser.
3. Click the "Join this meeting using the app" link in browser.

### Expected behavior:
The Jitsi Meet app starts and connects to the expected meeting.

### Actual behavior:
The Jitsi Meet app starts without connecting to meeting.

### Client information:

- Browser / app version: Jitsi Meet 22.5.1
- Operating System: Android 10 / 12.1 with microg.

### Additional information:

Everything works as expected when the app is already running, this is only an issue when the app is started by the intent. The link in the intent is processed as expected and the app joins with the correct link. However, microg GmsCore then sends an empty dynamic link object to the app, which joins this empty string instead (GoogleServicesHelper.java). Stock GMS sends a null pendingDynamicLinkData which is properly ignored by the app.

**Comment by saghul** [comment]
Hey there! Sounds like a reasonable fix, care to send a PR?

**Comment by tol4711** [comment]
My apologies, not right now. My working but unpolished fix is [here](https://github.com/jitsi/jitsi-meet/commit/d9e819d453efb6451769239c991f8593c6d19c45) but maybe it's better to handle in join() or so.
