### ISSUE TITLE
Jitsi link to be opened directly in android app

### ISSUE THREAD

**Issue by istodorionut** [jitsi/jitsi-meet#12230]
Hi guys,

Is there any configuration that enables the jitsi link to be open directly in the Jitsi android application without being redirected to the browser firefox/chrome on android?

I'm running the jitsi in a docker container.

Best Regards,
Ionut.

**Comment by saghul** [comment]
Here you go: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe/#opening-meetings-in-the-jitsi-meet-app
