### ISSUE TITLE
make dev -> Live refresh not working on browser such as chrome or safari  

### ISSUE THREAD

**Issue by testGumar** [jitsi/jitsi-meet#12255]
when running web build using 'make dev' -> Live refresh not working on browser such as chrome or safari  

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version: latest master branch
- Operating System: Mac os 

### Client information:

- Browser / app version: Chrome & Safari latest 
- Operating System: Mac latest

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

What file are you editing? It will refresh only when you touch a file that is bundled in app.bundle.

**Comment by SayyedUmar** [comment]
each n every file such as index.web.js, Conference.js, Toolbox.tsx for web. testing it on chrome, safari, firefox with latest version in latest macOS.
