### ISSUE TITLE
No voice audio on mobile

### ISSUE THREAD

**Issue by ligi** [jitsi/jitsi-meet#12274]
Some people reported they did not hear anything when using the mobile app. Switching to browser helped them for now - but is not ideal.
I just reproduced it on android with app version v22.5.1
Interesting: I hear sound from jitsi (the entry sample) - but no people speaking - but on the browser I hear them speaking at the same time
From reports I also hear it happens on iOS - but cannot reproduce this here.
I do not really see anything relevant in adb logcat - but if needed I can provide a log - just need to see what information I need to remove potentially.
People could use mobile before so I guess it is coming from an app update. 
Maybe this one: 
![image](https://user-images.githubusercontent.com/111600/193076998-a937c3ae-e406-498b-a56c-2d166d80a000.png)
This could fit time-wise with the reports coming in.

**Comment by damencho** [comment]
Please, do not open multiple issues for the same thing. Thank you.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/12273
