### ISSUE TITLE
Broken Installation after #11686 More-Settings

### ISSUE THREAD

**Issue by holema** [jitsi/jitsi-meet#12271]
### Description:
PR 11686 Breaks more-Settings
We got some feedback, that the More-Button in the Settings is disappeard.
After some research we found this PR
https://github.com/jitsi/jitsi-meet/pull/11686

In this PR, there is a new settings to disable the more tabs. This is great, but the settings are made in the interface-config.js which is marked as depreceated and should not be changed.

That´s why we do not deploy this file in our deployments. But if the interface-config.js is not deployed, then the more tabs is deactiavted.

### Steps to reproduce:

1. install Jitsi without interface-config.js file
2. open settings
3. More tab is gone

### Expected behavior:

The more tab should be visible

### Actual behavior:

no more button

### Server information:

- Jitsi Meet version: Latest
- Operating System: Debian 11

### Client information:

- Browser / app version: on all browsers
- Operating System: on all OS

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

> But if the interface-config.js is not deployed, then the more tabs is deactiavted.

Why this is not deployed? That file is part of the jitsi-meet install and always was.

```
$ dpkg --contents jitsi-meet-web_1.0.6600-1_all.deb | grep interface_config
-rw-r--r-- root/root      8717 2022-08-30 11:55 ./usr/share/jitsi-meet/interface_config.js
```
