### ISSUE TITLE
`Start with video muted` not honored since update

### ISSUE THREAD

**Issue by opk12** [jitsi/jitsi-meet#12279]
### Description:

Since 22.5.1 (f-droid), I have to disable the camera manually in the name input form, although `Start with video muted` is set. This was not the case in 22.4.0 (f-droid).

### Steps to reproduce:

1. Set `Start with video muted` in the settings
2. Join a room

### Expected behavior:

The camera is not streamed.

### Actual behavior:

The camera is streamed to the meeting, as confirmed by another participant.

### Client information:

- Browser / app version: Jitsi Meet app 22.5.1 from f-droid. This worked in 22.4.0.
- Operating System: Android 7.1

**Comment by saghul** [comment]
Are you able to test the 22.6.0 beta version (Play Store beta, sorry). We have fixed this in the latest release.

**Comment by opk12** [comment]
I confirm that it is fixed.
