### ISSUE TITLE
No voice audio on mobile

### ISSUE THREAD

**Issue by ligi** [jitsi/jitsi-meet#12273]
Some users reported they did not hear anything when using the mobile app. Switching to browser helped them for now - but is not ideal.
I just reproduced it on android with app version v22.5.1
Interesting: I hear sound from jitsi (the entry sample) - but no people speaking - but on the browser I hear them speaking at the same time
From reports I also hear it happens on iOS - but cannot reproduce this here.
People could use mobile before so I guess it is coming from an app update. 
Maybe this one: 
![image](https://user-images.githubusercontent.com/111600/193076998-a937c3ae-e406-498b-a56c-2d166d80a000.png)
This could fit time-wise with the reports coming in.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Is this on meet.jit.si?

**Comment by ligi** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.

oh - thought this is clearly a bug and so thought an issue is OK in this case. But can also close this and open it on the forum.

> Is this on meet.jit.si?

no it is an own instance

**Comment by saghul** [comment]
What version of the backend are you running?

**Comment by alariej** [comment]
I can confirm this issue with the JistiMeetSDK on iOS. I just released a new version of my app (https://github.com/alariej/quadrix) a few days ago, so I assume the podfile automatically fetched the latest JitsiMeetSDK version via `pod 'JitsiMeetSDK'`. Users now get video, but no audio from iOS to iOS. I can't test Android as I use a WebView and not the SDK on that platform. Interestingly, iOS to web works without problem. We use the server at https://jitsi.riot.im/, so not sure what version they are running.

**Comment by saghul** [comment]
What SDK version did it pickup?

**Comment by alariej** [comment]
6.1.0 according to the Podfile.lock

**Comment by saghul** [comment]
Can you try 6.2.0-beta.2 ?

**Comment by abulkalam-dsi** [comment]
> 6.2.0-beta.2

when try to install mentioned version, Cocoapods shows that it could not find compatible versions.

**Comment by saghul** [comment]
My bad, it's beta.1

**Comment by abulkalam-dsi** [comment]
thanks

**Comment by saghul** [comment]
You may want to run "pod repo update"

**Comment by alariej** [comment]
We did a test today with one iPhone on JitsiMeetSDK 6.1.0 and another one with 6.2.0-beta.1 and audio was available on both phones. We then re-tested with both phones on 6.1.0 and audio was also available. So not sure what happened. I'm sure we tested at least 3-4 times yesterday, and never got audio. The variable that is not under our control is the server, so perhaps something has been upgraded on their side since yesterday. In any case, I can't reproduce the issue anymore.

**Comment by rasos** [comment]
I can confirm that the Jitsi Android app Version 22.5.1 is not sending audio or video when connecting to a half-year old Jitsi set-up,  (jicofo 1.0-862, jitsi-videobridge2 2.1-665). 

I see in the jicofo.log: 

> org.jitsi.jicofo.conference.UnsupportedFeatureConfigurationException: Participant doesn't support bundle, which is required

Though it works with p2p and with an older version of the Jitsi app or when using a web browser.

**Comment by saghul** [comment]
> org.jitsi.jicofo.conference.UnsupportedFeatureConfigurationException: Participant doesn't support bundle, which is required

This is really weird, I don't think we have changed anything regarding bundle, have we @jallamsetty1 ?

**Comment by saltenhub** [comment]
> 

Same issue here running on a larger scale deployment, where we cannot easily update to newer component versions...

**Comment by saltenhub** [comment]
> I can confirm that the Jitsi Android app Version 22.5.1 is not sending audio or video when connecting to a half-year old Jitsi set-up, (jitsi-meet 2.0.7001, jicofo 1.0-862, jitsi-videobridge2 2.1-665). The microphone at other participants is shown muted, even if unmuted o the mobile.
> 
> I see in the jicofo.log:
> 
> > org.jitsi.jicofo.conference.UnsupportedFeatureConfigurationException: Participant doesn't support bundle, which is required
> 
> Though it works with p2p and with an older version of the Jitsi app or when using a web browser or on meet.jit.si.

Same issue here on a larger scale deployment where we cannot just quickly update the jitsi components. It would be great if someone could look into this

**Comment by saghul** [comment]
This has been looked into. The latest beta should work fine with older deployments.

**Comment by sa-bre** [comment]
Any chance you know when this should be rolled out to the stable versions in the app stores?

**Comment by saltenhub** [comment]
Just tested again with v22.6.0 beta on Android against an older deployment on 6865 docker containers. Browser to browser works, app to app works (even though authentication via JWT seems flawed: username can be changed even though provided in token, moderator flag is not properly respected, video is muted for everyone on join except for the first participant). App 2 browser does not work (no video, other side has muted flag set).

Happy to provide you with any logs (server components, logcat, browser console log) - just let me know which ones are useful for troubleshooting the issue.

**Comment by saghul** [comment]
> Any chance you know when this should be rolled out to the stable versions in the app stores?

It started to roll out today.

**Comment by saghul** [comment]
> Just tested again with v22.6.0 beta on Android against an older deployment on 6865 docker containers. Browser to browser works, app to app works (even though authentication via JWT seems flawed: username can be changed even though provided in token, moderator flag is not properly respected, video is has to be disabled an enabled to work for everyone on join except for the first participant). App 2 browser does not work (no video, other side has muted flag set).
> 
> Happy to provide you with any logs (server components, logcat, browser console log) - just let me know which ones are useful for troubleshooting the issue.

I'd take a patch, but we have no resources to dig into what's broken with that old release I'm afraid. There have been some fundamental changes this year, like the migration to Unified Plan and the introduction of multi-stream, which make that a complex task.

You could try this at least:

```
    // Feature Flags.
    flags: {
        // Enables source names in the signaling.
        sourceNameSignaling: false,

        // Enables sending multiple video streams, i.e., camera and desktop tracks can be shared in the conference
        // separately as two different streams instead of one composite stream.
        sendMultipleVideoStreams: false,

        // Signal that this client supports receiving multiple video streams. Without this flag jicofo will enable
        // multi-stream backward compatibility.
        receiveMultipleVideoStreams: false,
    },
```

In your config.js

**Comment by q9f** [comment]
I have the same issue on iOS, app version 22.6.0 build 1666600335. It always takes a couple of minutes to realize that I'm the only one who cannot see/hear others. It feels like you enter a room of afk participants.

**Comment by saghul** [comment]
> I have the same issue on iOS, app version 22.6.0 build 1666600335. It always takes a couple of minutes to realize that I'm the only one who cannot see/hear others. It feels like you enter a room of afk participants.

What deployment are you connecting to? Do you know what versions of the software it runs? Can you reproduce this on meet.jit.si ?

**Comment by moskaland** [comment]
Hi @saghul,
I'm facing the same problem. On SDK 6.0.0 everything works fine, on newer versions 6.1.0 all the way to 7.0.0) Android did not receive nor send audio/video.

Versioning of server is not that old, form August '22:
wget_version: 1.21-1+deb11u1
jitsi_meet_web_version: 1.0.6447-1
jitsi_meet_web_config_version: 1.0.6447-1
jitsi_meet_tokens_version: 1.0.6447-1

**Comment by damencho** [comment]
@moskaland Do you have this at the end of config.js?
```
config.flags = {};
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
```

**Comment by rasos** [comment]
I tested setting the feature flags to false - still no audio or video with more than two participants with Android App 22.6.0 against Jicofo 1.0-862.

**Comment by saghul** [comment]
Those need to be set to true.

22.7.0 is out btw, any chance you can test that one?

**Comment by rasos** [comment]
Tested with 22.7.0 App on Android and iOS - no audio & video, even not with p2p. When setting the flags to true, it is even worse: no video when using mobile browser (/e/ OS Browser 100.0 based on Android 12) which works when no flags are set.

**Comment by moskaland** [comment]
I'll try to update our servers to latest version.
@saghul to avioid multiple deployments, I want to double check,  as there were different advices [here](https://github.com/jitsi/jitsi-meet/issues/12273#issuecomment-1290282746) and [here](https://github.com/jitsi/jitsi-meet/issues/12273#issuecomment-1334044749): 

`sourceNameSignaling` `sendMultipleVideoStreams`  `receiveMultipleVideoStreams` should be eventually set to true or to false ?

**Comment by saghul** [comment]
I agree this has been confusing, the reasoning is somewhat obtuse, the default value of some of the flags changed at some point internally but that requires  mobile app update so it created quite a bit of churn...

**Comment by rasos** [comment]
@saghul  as mentioned above we use a half-year old Jitsi set-up, (jitsi-meet 2.0.7001, jicofo 1.0-862, jitsi-videobridge2 2.1-665).  We had to cancel an update procedure as the JWT mechanism seems to have changed we need some more time to test it with our Keycloak setup or migrate that part.

**Comment by saghul** [comment]
Then you can't use 22.7 because that release dropped compatibility with setups that don't have source-name signalling, and I think that might be case with your setup.

**Comment by moskaland** [comment]
@saghul , unfortunatelly updating server to lates stable release ([2.0.8133](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_8133 / jitsi-meet_1.0.6850 ) does not change situation.
Android SDK 6.0.0 connects and works just fine.
Android SDK 6.1.0/7.0.0 connect and do not send/receive audio and video.

**Comment by kubilaykaptanoglu** [comment]
Hi, I had same problem. I had stable-6865 version on kubernetes and I changed with version stable-8138-1. However I needed two extra change. Firstly I changed jvb deployment.yaml. I changed DOCKER_HOST_ADDRESS of variable to JVB_ADVERTISE_IPS variable with my public ip and then I added extra variable JVB_DISABLE_STUN: "true". everything looks good now.

my configmap example:
```
- apiVersion: v1
  data:
    COLIBRI_REST_ENABLED: "true"
    ENABLE_COLIBRI_WEBSOCKET: "true"
    JVB_BREWERY_MUC: ****
    JVB_DISABLE_STUN: "true"
    JVB_PORT: "****"
    JVB_TCP_HARVESTER_DISABLED: "1"
    XMPP_SERVER: *****
```
my deployment.yaml example
```
     - env:
        - name: JVB_ADVERTISE_IPS
          value:  MY_PUBLIC_IP
```

**Comment by xBelladonna** [comment]
If anyone is getting this problem using Docker (or Kubernetes, etc) then it may be because of deprecation of `latest` tag in favor of `stable` instead. Please switch to latest stable and check again. Once jicofo updated, that solved the problem for me.
