### ISSUE TITLE
[Debian] Video not shown on mobile since September server update

### ISSUE THREAD

**Issue by steepnought** [jitsi/jitsi-meet#12281]
On 2022-09-27 there were the following Debian package updates:

```
jicofo 1.0-911-1 -> 1.0-934-1
jitsi-meet 2.0.7648-1 -> 2.0.7830-1
jitsi-meet-prosody 1.0.6447-1 -> 1.0.6600-1
jitsi-meet-web 1.0.6447-1 -> 1.0.6600-1
jitsi-meet-web-config 1.0.6447-1 -> 1.0.6600-1
jitsi-videobridge2 2.2-22-g42bc1b99-1 -> 2.2-43-gce94dbb2-1
```

plus a new install of lua-inspect 3.1.1-2

With these updates, videos of participants using a desktop browser (Firefox, Edge) are no longer visible for users of the Android app (tested with 22.4.0 and 22.5.1 on different Android versions from 7 to 12). Also, the microphone of the browser participants is shown as muted in the app although sound is audible.

Downgrading the Debian packages to the previous versions solves the problem. This is on Debian Bullseye if that matters.

**Comment by saghul** [comment]
Can you share your config.JS please?

**Comment by Gerard64** [comment]
Same here.
I restored vps backup then it worked again.
So i am not upgrading again for the time being.

**Comment by maccaches** [comment]
I'm having the same problem and am seeing the following error message in the Jicofo logs:
`org.jitsi.jicofo.conference.UnsupportedFeatureConfigurationException: Participant doesn't support bundle, which is required
	at org.jitsi.jicofo.conference.Participant.setSupportedFeatures(Participant.java:371)
	at org.jitsi.jicofo.conference.ParticipantInviteRunnable.createOffer(ParticipantInviteRunnable.java:330)
	at org.jitsi.jicofo.conference.ParticipantInviteRunnable.doRun(ParticipantInviteRunnable.java:198)
	at org.jitsi.jicofo.conference.ParticipantInviteRunnable.run(ParticipantInviteRunnable.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`
Mobile Device is a Pixel 6 Pro running Android 13.

**Comment by saghul** [comment]
> [config.js.gz](https://github.com/jitsi/jitsi-meet/files/9689798/config.js.gz)
> 
> Find it attached.

Can you try setting `sourceNameSignaling` and `sendMultipleVideoStreams` to true ?

**Comment by saghul** [comment]
> With these two settings it works for me, thanks. Is it documented somewhere that these settings are now needed and why? Is there any general documentation on which settings are needed in which version?
> 
> 

They shouldn't be, I'm trying to pinpoint the source of the problem.

**Comment by Gerard64** [comment]
> > [config.js.gz](https://github.com/jitsi/jitsi-meet/files/9689798/config.js.gz)
> > Find it attached.
> 
> Can you try setting `sourceNameSignaling` and `sendMultipleVideoStreams` to true ?

After setting those the problem still persist.

**Comment by saghul** [comment]
> > > [config.js.gz](https://github.com/jitsi/jitsi-meet/files/9689798/config.js.gz)
> > > Find it attached.
> > 
> > 
> > Can you try setting `sourceNameSignaling` and `sendMultipleVideoStreams` to true ?
> 
> After setting those the problem still persist.

What version of the server components do you run? Can you share your config.js please?

**Comment by Gerard64** [comment]
> What version of the server components do you run? Can you share your config.js please?

[config.js.gz](https://github.com/jitsi/jitsi-meet/files/9700823/config.js.gz)

Debian 10.13

jitsi-meet                      2.0.7830-1
jitsi-meet-prosody              1.0.6600-1
jitsi-meet-turnserver           1.0.6600-1
jitsi-meet-web                  1.0.6600-1
jitsi-meet-web-config           1.0.6600-1
jitsi-videobridge2              2.2-43-gce94dbb2-1
lua-basexx                      0.4.1-jitsi1
lua-cjson:amd64                 2.1.0.10-jitsi1
jicofo                          1.0-934-1

**Comment by damencho** [comment]
A workaround is implemented and will be available woth next stable
https://github.com/jitsi/jitsi-meet/commit/5c2ec5df5448180bc3da8e14eb771d207450472d

**Comment by Gerard64** [comment]
With these latest updates and both sourceNameSignaling and sendMultipleVideoStreams set to true i still have no video on mobile devices. Android 9 & 10.

jicofo                          1.0-940-1
jitsi-meet                      2.0.7882-1
jitsi-meet-prosody              1.0.6644-1
jitsi-meet-turnserver           1.0.6644-1
jitsi-meet-web                  1.0.6644-1
jitsi-meet-web-config           1.0.6644-1
jitsi-videobridge2              2.2-45-ge8b20f06-1
lua-basexx                      0.4.1-jitsi1
lua-cjson:amd64                 2.1.0.10-jitsi1
lua-inspect                     3.1.1-1

**Comment by damencho** [comment]
@Gerard64 Have you tried adding these at the end of your config.js file?
```
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
```
Does that fixes it?

**Comment by Gerard64** [comment]
I tested a minute ago with:
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
set in config.js

It doesn't change anything.
No video on the mobile devices.

**Comment by saghul** [comment]
Since you are not the OP, what Android SDK / app versions are you using?

**Comment by Gerard64** [comment]
re-installed no change

**Comment by Gerard64** [comment]
After the re-install all the settings were saved maybe also the cache?

**Comment by Gerard64** [comment]
I deleted the cache and all settings.
Reconfigured the Jistsi Meet app to connect to my server again but still no video on the mobile.

**Comment by saghul** [comment]
😢  Are you on Android? If so, are you able to grab the `adb logcat` output?

**Comment by saghul** [comment]
Oh and one more thing: does the problem also manifest with meet.jit.si ?

**Comment by Gerard64** [comment]
> 😢 Are you on Android? If so, are you able to grab the `adb logcat` output?
Not right now i am sorry to say.

> Oh and one more thing: does the problem also manifest with meet.jit.si ?
On meet.jit.si it does work normal.

**Comment by saghul** [comment]
meet.jit.si is pretty much stable right now, I have no idea what the problem could be :-/ If you could grab that logcat it would be useful.

**Comment by Gerard64** [comment]
Oke i have saved the output of adb logcat.
I wil send it by e-mail to you.

**Comment by peterkuma** [comment]
Hi,

I just want to let you know that I had the same issue - remote participant video was not shown on the mobile client on Android. Video from the mobile client was visible on the desktop web client. Setting the flags (`sourceNameSignaling` and `sendMultipleVideoStreams`) fixed the issue.

Versions:

- jitsi-meet 2.0.7439-1 (17-Jun-2022) OK
- jitsi-meet 2.0.7577-1 (02-Aug-2022) OK
- jitsi-meet 2.0.7648-1 (11-Aug-2022) OK
- jitsi-meet 2.0.7830-1 (27-Sep-2022) not OK – works only with the flags
- jitsi-meet 2.0.7882-1 (06-Oct-2022) not OK – works only with the flags

Mobile client: Jitsi Meet 22.2.0 on Adroid 8.1.0
Server: Debian GNU/Linux 11 (bullseye)
Jitsi packages from https://download.jitsi.org/stable/

**Comment by Gerard64** [comment]
With the Android Jitsi meet app version 22.6.0
And server components:
jitsi-meet                      2.0.7882-1
jitsi-meet-prosody              1.0.6644-1
jitsi-meet-turnserver           1.0.6644-1
jitsi-meet-web                  1.0.6644-1
jitsi-meet-web-config           1.0.6644-1
jitsi-videobridge2              2.2-45-ge8b20f06-1
lua-basexx                      0.4.1-jitsi1
lua-cjson:amd64                 2.1.0.10-jitsi1

Everything seems to be working as normal again 👍

**Comment by saghul** [comment]
Thanks for the feedback!
