### ISSUE TITLE
Adding a password is visible in plaintext

### ISSUE THREAD

**Issue by fulldecent** [jitsi/jitsi-meet#12290]
### Description:

I was live and screensharing and want to stop people from Jitsibombing. But whenever I type the password, other people can see it!

<img width="1136" alt="Screen Shot 2022-10-03 at 22 37 44" src="https://user-images.githubusercontent.com/382183/193722709-55ad6ba5-87a9-48c8-b1ca-dd0f5c39823b.png">

Please make typing in this box hidden by default and showable using a button.

**Comment by sameergupta4873** [comment]
Hey , I would Like to work on this issue , can you please guide me to the location of the file , that need the above change .

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/12295
