### ISSUE TITLE
Pop-out windows

### ISSUE THREAD

**Issue by fulldecent** [jitsi/jitsi-meet#12291]
**Is your feature request related to a problem you are facing?**

I am livestreaming using OBS and want to position speakers into my templates/scenes. (Thank you! Yes I know Jitsi can send to RTMP but I have a lot more going on and this does not do what I need.)

**Describe the solution you'd like**

Right-click on a person and have them pop-out to a new window. Then I can use OBS to capture that window as a separate source and load into my scene.

**Describe alternatives you've considered**

I understand other broadcasters do this with Zoom.

I have also tried having all speakers in the window, dicing up the exact pixel location of people into my scene, but I have to stop the broadcast and rearrange if anybody were to drop/join the call.

**Comment by saghul** [comment]
This is not a feature we are currently considering, sorry.
