### ISSUE TITLE
jitsi-meet-web-config and jitsi-meet-prosody package upgrade fails

### ISSUE THREAD

**Issue by wsldankers** [jitsi/jitsi-meet#12300]
### Description:

The `jitsi-meet-web-config` and `jitsi-meet-prosody` packages reference debconf questions from the `jitsi-meet` package but do not depend on it. This causes upgrades (and presumably new installs) on systems that do not have the `jitsi-meet` package to fail.

### Steps to reproduce:

1. Make sure you are on a system that never had the `jitsi-meet` meta-package installed;
2. Upgrade `jitsi-meet-prosody` from an earlier version (such as 1.0.6447-1).

### Expected behavior:

```
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following NEW packages will be installed:
   lua-inspect (3.1.1-2)
The following packages will be upgraded:
   jicofo (1.0-911-1 => 1.0-934-1)
   jitsi-meet-prosody (1.0.6447-1 => 1.0.6600-1)
   jitsi-videobridge2 (2.2-22-g42bc1b99-1 => 2.2-43-gce94dbb2-1)
3 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 80.2 MB of archives.
After this operation, 27.8 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 lua-inspect all 3.1.1-2 [6060 B]
Get:2 https://download.jitsi.org stable/ jitsi-videobridge2 2.2-43-gce94dbb2-1 [38.4 MB]
Get:3 https://download.jitsi.org stable/ jicofo 1.0-934-1 [41.7 MB]
Get:4 https://download.jitsi.org stable/ jitsi-meet-prosody 1.0.6600-1 [64.5 kB]
Preconfiguring packages ...
Fetched 80.2 MB in 33s (2433 kB/s)
(Reading database ... 34256 files and directories currently installed.)
Preparing to unpack .../jitsi-videobridge2_2.2-43-gce94dbb2-1_all.deb ...
Unpacking jitsi-videobridge2 (2.2-43-gce94dbb2-1) over (2.2-22-g42bc1b99-1) ...
Selecting previously unselected package lua-inspect.
Preparing to unpack .../lua-inspect_3.1.1-2_all.deb ...
Unpacking lua-inspect (3.1.1-2) ...
Preparing to unpack .../jicofo_1.0-934-1_all.deb ...
Unpacking jicofo (1.0-934-1) over (1.0-911-1) ...
Preparing to unpack .../jitsi-meet-prosody_1.0.6600-1_all.deb ...
Unpacking jitsi-meet-prosody (1.0.6600-1) over (1.0.6447-1) ...
Setting up jitsi-videobridge2 (2.2-43-gce94dbb2-1) ...
* Applying /etc/sysctl.d/20-jvb-udp-buffers.conf ...
net.core.rmem_max = 10485760
net.core.netdev_max_backlog = 100000
* Applying /usr/lib/sysctl.d/50-pid-max.conf ...
kernel.pid_max = 4194304
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /usr/lib/sysctl.d/protect-links.conf ...
fs.protected_fifos = 1
fs.protected_hardlinks = 1
fs.protected_regular = 2
fs.protected_symlinks = 1
* Applying /etc/sysctl.conf ...
Setting up jicofo (1.0-934-1) ...
Setting up lua-inspect (3.1.1-2) ...
Setting up jitsi-meet-prosody (1.0.6600-1) ...
```

### Actual behavior:

```
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following NEW packages will be installed:
   lua-inspect (3.1.1-2)
The following packages will be upgraded:
   jicofo (1.0-911-1 => 1.0-934-1)
   jitsi-meet-prosody (1.0.6447-1 => 1.0.6600-1)
   jitsi-videobridge2 (2.2-22-g42bc1b99-1 => 2.2-43-gce94dbb2-1)
3 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 80.2 MB of archives.
After this operation, 27.8 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 lua-inspect all 3.1.1-2 [6060 B]
Get:2 https://download.jitsi.org stable/ jitsi-videobridge2 2.2-43-gce94dbb2-1 [38.4 MB]
Get:3 https://download.jitsi.org stable/ jicofo 1.0-934-1 [41.7 MB]
Get:4 https://download.jitsi.org stable/ jitsi-meet-prosody 1.0.6600-1 [64.5 kB]
Preconfiguring packages ...
Fetched 80.2 MB in 33s (2433 kB/s)
(Reading database ... 34256 files and directories currently installed.)
Preparing to unpack .../jitsi-videobridge2_2.2-43-gce94dbb2-1_all.deb ...
Unpacking jitsi-videobridge2 (2.2-43-gce94dbb2-1) over (2.2-22-g42bc1b99-1) ...
Selecting previously unselected package lua-inspect.
Preparing to unpack .../lua-inspect_3.1.1-2_all.deb ...
Unpacking lua-inspect (3.1.1-2) ...
Preparing to unpack .../jicofo_1.0-934-1_all.deb ...
Unpacking jicofo (1.0-934-1) over (1.0-911-1) ...
Preparing to unpack .../jitsi-meet-prosody_1.0.6600-1_all.deb ...
Unpacking jitsi-meet-prosody (1.0.6600-1) over (1.0.6447-1) ...
Setting up jitsi-videobridge2 (2.2-43-gce94dbb2-1) ...
* Applying /etc/sysctl.d/20-jvb-udp-buffers.conf ...
net.core.rmem_max = 10485760
net.core.netdev_max_backlog = 100000
* Applying /usr/lib/sysctl.d/50-pid-max.conf ...
kernel.pid_max = 4194304
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /usr/lib/sysctl.d/protect-links.conf ...
fs.protected_fifos = 1
fs.protected_hardlinks = 1
fs.protected_regular = 2
fs.protected_symlinks = 1
* Applying /etc/sysctl.conf ...
Setting up jicofo (1.0-934-1) ...
Setting up lua-inspect (3.1.1-2) ...
Setting up jitsi-meet-prosody (1.0.6600-1) ...
dpkg: error processing package jitsi-meet-prosody (--configure):
 installed jitsi-meet-prosody package post-installation script subprocess
returned error exit status 10
Errors were encountered while processing:
 jitsi-meet-prosody
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Server information:

- Jitsi Meet version: 1.0.6447-1
- Operating System: Debian GNU/Linux 11.5 “bullseye”

### Client information:

- Browser / app version: not applicable
- Operating System: not applicable

### Additional information:

The problem was likely introduced in https://github.com/jitsi/jitsi-meet/commit/1b4bbcba3d1d630f2a29ce8d678865bb719e74f1

After discussing this with a Debian Developer (joostvb%debian.org) he recommended putting the common configuration in a separate `jitsi-meet-config` package and having both `jitsi-meet-web-config` and `jitsi-meet-prosody` depend on that.

Please do not make `jitsi-meet-web-config` and `jitsi-meet-prosody` depend on `jitsi-meet`: that would make it impossible to install the frontend and backend on separate systems.

**Comment by damencho** [comment]
The problem is that you cannot order the package configuration, which made us add another trigger of the choice there. Any advice on how to order that is welcome.

When installing jitsi-meet we need information for the choices when installing the prosody-config package.

I see on the same machine you have installed jicofo and jvb, but you do not want to install jitsi-meet, but you install jitsi-meet-prosody ... why is that? What is the use case here?

**Comment by damencho** [comment]
I also do not understand why the rest of the db_get calls succeed but not this one, doesn't make sense.

**Comment by wsldankers** [comment]
The usecase for not wanting `jitsi-meet` is that I have a separate web server and ‘backend’ jitsi server. I'll ask about the ordering.

**Comment by damencho** [comment]
I see. We have never seen the need to move nginx away from prosody ... it is even better as the connection for the websockets is proxied on localhost. nginx only serves index.html, config.js in case of mobile and proxies the websockets, the rest comes from cdn.

**Comment by wsldankers** [comment]
Just depending should be enough:

>`Depends`
>This declares an absolute dependency. A package will not be configured unless all of the packages listed in its `Depends` field have been correctly configured […].

From https://www.debian.org/doc/debian-policy/ch-relationships.html

**Comment by damencho** [comment]
I agree but what is the order?
https://github.com/jitsi/jitsi-meet-debian-meta/blob/036f6fe156f6502b3db9df2d366c30bd2a460f8d/control-tmpl#L13

I have seen sometimes its jitsi-meet-config first sometimes its jitst-meet-prosody the first ...

**Comment by wsldankers** [comment]
If jitsi-meet-prosody depends on jitsi-meet-config, jitsi-meet-config will be configured first.

**Comment by damencho** [comment]
> If jitsi-meet-prosody depends on jitsi-meet-config, jitsi-meet-config will be configured first. If you're seeing something else I'm going to have to reproduce that first if I am to be of further assistance.

This means that when you want to install jitsi-meet-prosody you depend on 
https://github.com/jitsi/jitsi-meet/blob/f935b29629ae5f657e5d739e2bd6803650357e5a/debian/control#L21 first 
and you need to install nginx or apache there... 

I still don't get why the other db_get does not return an error just the one that we recently added returns an error ... 

Seems to me the PR I created is the best option for now.

**Comment by damencho** [comment]
> I still don't get why the other db_get does not return an error just the one that we recently added returns an error ...

And because of that, even a new config package will have the same problem. db_get will again return an error ...

**Comment by wsldankers** [comment]
The proposed solution was to create a new package called `jitsi-meet-config` and move all common debconf questions there. This package would have no dependencies itself but would be depended upon by all packages that need to reference those common questions.

The `jitsi-meet` package would become an empty meta-package without any debconf questions, that just depends on the same things it currently depends on.

**Comment by damencho** [comment]
> The proposed solution was to create a new package called `jitsi-meet-config` and move all common debconf questions there. This package would have no dependencies itself but would be depended upon by all packages that need to reference those common questions.
> 
> The `jitsi-meet` package would become an empty meta-package without any debconf questions, that just depends on the same things it currently depends on.

That will not work, as currently, the failure is here 
https://github.com/jitsi/jitsi-meet/blob/f935b29629ae5f657e5d739e2bd6803650357e5a/debian/jitsi-meet-prosody.postinst#L88
The same db_get will need to be done from all packages that depend on jitsi-meet-config and will fail as the current one.

**Comment by wsldankers** [comment]
That line would become:
```
db_get jitsi-meet-config/cert-choice
```
…and because jitsi-meet-prosody would depend on jitsi-meet-config, that question would have been answered by the time that line runs.

**Comment by wsldankers** [comment]
I realize that would be quite a bit of work, and apparently moving debconf questions to a new package without bothering the users to answer them again is… gnarly.
Would you be willing to consider a PR that implements the idea?

**Comment by damencho** [comment]
I'm not sure that will work. Why this works `db_get jicofo/jicofo-authpassword` but this doesn't `db_get jitsi-meet-config/cert-choice`.

**Comment by damencho** [comment]
For now I don't think we would want to complicate that stuff more. And if we are going to ask users same questions on update, nope ...

**Comment by wsldankers** [comment]
I never suggested we re-ask the same questions on update.
