### ISSUE TITLE
Jitsi doesn't start connect on locked iPhone

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#12303]
iOS JITSI SDK 6.1.0 (the same was for 6.0.0)
iOS 15 and iOS 16 onboard

If we get voip push and start Jitsi while iPhone is locked we get callkit screen with ordinary buttons.
Nor audio nor video sessions don't start. Jitsi is waiting for opening the application to start connect.

So it is impossible to make audio answer for incoming call before we unlock and open the app.

If we press cancel ("red button with cross") then jitsi will stop with the following log in console

2022-10-04 21:14:39.606743+0300 OneFChat-test[1373:275059] [JitsiMeetSDK] '2022-10-04T18:14:39.602Z', '[modules/browser/BrowserCapabilities.js]', 'This appears to be react-native, ver: 0.68.1'
2022-10-04 21:14:39.795642+0300 OneFChat-test[1373:275059] [JitsiMeetSDK] Running "App
2022-10-04 21:14:40.191541+0300 OneFChat-test[1373:275060] [JitsiMeetSDK] TypeError: undefined is not an object (evaluating 'this.state.store.dispatch')

This error is located at:
    in R
    in c
    in RCTView
    in Unknown
    in Portal.Host
    in s
    in Unknown
    in h
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in b
2022-10-04 21:14:40.197128+0300 OneFChat-test[1373:275059] [JitsiMeetSDK] Unable to find module for RedBox
2022-10-04 21:14:40.209340+0300 OneFChat-test[1373:275060] [JitsiMeetSDK] TypeError: undefined is not an object (evaluating 'this.state.store.dispatch')

**Comment by saghul** [comment]
I think you'll need to implement a workaround like this one: https://developer.apple.com/forums/thread/712817

We don't implement incoming calls so alas I cannot really test this.

**Comment by iospro** [comment]
> I think you'll need to implement a workaround like this one: https://developer.apple.com/forums/thread/712817
> 
> We don't implement incoming calls so alas I cannot really test this.

The Question seems to be of another kind.

We want to start jitsi SDK while in background and when iPhone is locked

We get voip invite push, make slide to unlock, see CalKit screen, prepare SDK and start join the room.

In this case the SDK strongly wait fr unlock and open our application. JItsiVIew starts immediately on enter foreground.

But it seems that should be no obstacles to start media in background.

**Comment by saghul** [comment]
> But it seems that should be no obstacles to start media in background.

There is obviously some obstacle, but as I said, we don't have that usecase, so I have no way to test.

**Comment by somparkash** [comment]
Hey @saghul @iospro, I got same issue. My Jitsi Meet View not able to join the into room if application state is background or inactive. @saghul I have also used your above mentioned solutions, but same problem.

**Comment by saghul** [comment]
Does that mean there is nothing actionable on our end?

**Comment by iospro** [comment]
> Does that mean there is nothing actionable on our end?

It is hard to say. There are a lot of different video messengers that can start calls in iOS background.
There are no restrictions for this.

Jitsi also has native integration with callKit, so it kindly should support background calls on the locked iPhone.

It iPhone is not locked then callKit answer button opens voip app.
But locked state with slide to unlock control starts Callkit screen with voip app staying in the background.
Jitsi "Join with options" method doesn't start the connection process until one unlocks iPhone and opens the app.

**Comment by saghul** [comment]
What SDK version are you using? Are you skipping the prejoin screen in that case?

**Comment by iospro** [comment]
Prejoin is off by flags.
SDK 6.1.0, the same problem was at 5.x.x SDK and 6.0.0

**Comment by saghul** [comment]
Than I'm back to being out of ideas on this one :-/

**Comment by andreipro1002** [comment]
@saghul @iospro Hello, any news about this? I'm facing the same issue using the Jitsi iOS SDK 6.1.0 on iPad with 15.4.1, but on iPhone with 12.5.6 works correctly. Previously we had integrated in project the Jitsi SDK 2.9.0 and we had no such problems. I don't know if it's a coincidence, but since it was introduced the prejoin screen on 5.x.x, this problem appeared. I'm also skipping the prejoin screen using the feature flag as @iospro mentioned.

**Comment by andreipro1002** [comment]
@saghul @iospro 

Hello,

I did a bit of digging on this issue and it seems it was caused by some changes on iOS SDK version 5.1.0 (this commit: https://github.com/jitsi/jitsi-meet/commit/e6ce5fd75f3ce60978b918cffd8a5cad3bbd8c12). With those changes, the issue with being stuck at "Connecting screen" got resolved, but created the issue with call not being started when the user unlocks the phone and stays on the CallKit screen. Before version 5.1.0, the issues were reversed, the user could speak on the CallKit screen, but as soon as he pressed the app button he was stuck on "Connecting screen".

This can be easily tested just by commenting the following code in App.native.js:

```
// HACK ALERT!
// Wait until the root navigator is ready.
// We really need to break the inheritance relationship between App,
// AbstractApp and BaseApp, it's very inflexible and cumbersome right now.
const rootNavigationReady = new Promise(resolve => {
    const i = setInterval(() => {
        const { ready } = getState()['features/app'] || {};

        if (ready) {
            clearInterval(i);
            resolve();
        }
    }, 50);
});

await rootNavigationReady;
```

Note: The CallKit part for the incoming call works correctly on version 3.10.4, but a lot of things were changed since then (https://github.com/jitsi/jitsi-meet/blob/ios-sdk-3.10.4/react/features/app/components/App.native.js)

I'm not familiar with react / javascript, and was not able to find a solution. Can you please take a look and see if you can find a fix for this? Thanks in advance.

**Comment by AlvaroBro** [comment]
Hi!

@saghul , @iospro , @andreipro1002 

I'm facing the same problem.

I have an app that uses Jitsi + CallKit to implement VoIP, including incoming calls.

I was using Jitsi 3.10.2, and I was able to join and start the call with the iPhone locked.

Now I am trying to upgrade to the new Jitsi SDK (trying version 7.0.1), and the problem is that now the conference won't start until the iPhone is unlocked.

I was doing some digging and I also think it has something to do with react-native.

I noticed that Jitsi applies a npm patch for react-native, in which it does something regarding the initial value of a variable suggesting logic for background app state (see image bellow). I removed that patch but it didn't fix anything.

Anyone has any update on this? Any clue? I'm ready to collaborate to fix this issue!

Regards.

![Captura de pantalla 2022-12-21 a las 13 04 22](https://user-images.githubusercontent.com/1628717/208901385-378b7add-ee9c-4161-8cd4-dff021fc1db2.png)

**Comment by AlvaroBro** [comment]
I confirm what @andreipro1002 said.

I just removed this line: 

`await rootNavigationReady;`

And now I can start the conference from the locked iPhone CallKit screen, but as soon as I unlock the screen, this is what I see (the conference is working):

![IMG1671626340834](https://user-images.githubusercontent.com/1628717/208907204-44ab35ed-8679-471e-ac3a-a2b8c6fdfc94.jpeg)

I am now working with SDK 7.0.1

**Comment by AlvaroBro** [comment]
Hi,

I found a simple hack-ish solution that works for me.

I just skip the "connecting" screen. Maybe I will make it a bit more sophisticated by making it configurable using a new feature flag so that I skip that screen only when the iPhone is locked, but you get the idea.

![Captura de pantalla 2022-12-21 a las 16 14 10](https://user-images.githubusercontent.com/1628717/208939212-de17f3ba-608d-44b2-9ffc-e0e1f1db703b.png)

**Comment by iospro** [comment]
It works! Great.

By it could damage other scenaria of use as anonymous connect, lobby etc.
I will check all.

And also the question is what we make wrong in the whole start logic by commenting await in that "hack".

**Comment by andreipro1002** [comment]
@AlvaroBro Nice work! Tested and works good. Indeed this can be improved so the "Connecting screen" will get skipped only when phone is locked. Anyway it's way better than it was before.

**Comment by AlvaroBro** [comment]
Yes, I created a flag to enable this behavior from the app using the SDK, where you could, at least when launching the conference, specify if the hack should be applied or not.

I attach the path file from the commit where I implemented it.

Please note that the patch includes other things, but it is quite obvious which files are modified regarding this issue.

Regards.

[0001-Build-bug-fixes-and-customizations.patch](https://github.com/jitsi/jitsi-meet/files/10286748/0001-Build-bug-fixes-and-customizations.patch)

**Comment by saghul** [comment]
Hey folks!

Interesting analysis!

That change was introduced in https://github.com/jitsi/jitsi-meet/commit/e6ce5fd75f3ce60978b918cffd8a5cad3bbd8c12 to prevent the connecting screen from remaining stuck when joining a URL directly when the app is closed. In that scenario the navigator could be null when the navigation is attempted and it's created just a touch later, so you're stuck in connecting.

What's surprising is why you don't get to the ready part. 

If you add a log line here: https://github.com/jitsi/jitsi-meet/blob/27754c88746b33c3fa99322a42a1ea49820e824b/react/features/app/components/App.native.js#L117 do you see it printed every 50ms?

Do you see the app getting here? https://github.com/jitsi/jitsi-meet/blob/27754c88746b33c3fa99322a42a1ea49820e824b/react/features/mobile/navigation/components/RootNavigationContainer.js#L47

And here? https://github.com/jitsi/jitsi-meet/blob/27754c88746b33c3fa99322a42a1ea49820e824b/react/features/app/reducer.native.js#L14

Adding some logs might help uncover the real issue.

Thanks for persevering!

**Comment by saghul** [comment]
Has anyone managed to find the root cause of this?

**Comment by AlvaroBro** [comment]
Nope sorry, I'll give a try to what you propose in the previous comment sometime when I have time.

**Comment by saghul** [comment]
Thank you! Alternatively, how could we reproduce this with the smallest example possible?

**Comment by softavail** [comment]
@saghul I put the logs as you suggested like this
``` 
        const rootNavigationReady = new Promise(resolve => {
            const i = setInterval(() => {
                const { ready } = getState()['features/app'] || {};

                logger.info(`[TEST] rootNavigationReady ${ready}`);
```

```
const RootNavigationContainer = ({ dispatch, isWelcomePageAvailable }: Props) => {
    const initialRouteName = isWelcomePageAvailable
        ? screen.welcome.main : screen.connecting;
    const onReady = useCallback(() => {

        logger.info('[TEST] RootNavigationContainer');
```

```
ReducerRegistry.register('features/app', (state = {}, action) => {
    switch (action.type) {
    case _ROOT_NAVIGATION_READY:
        logger.info(`[TEST] ReducerRegistry.register ${action.ready}`);
```

I decorated the logs with comments starting with "#"

Find attached logs
[Jitsi_IOS_SDK_Locked.txt](https://github.com/jitsi/jitsi-meet/files/10498492/Jitsi_IOS_SDK_Locked.txt)

**Comment by saghul** [comment]
Thank you! I still cannot explain why it won't get ready, I wonder if that prop won't be called because it's in the background...

I'll take another look and let you know what we can try.

Thanks for the help here!

**Comment by saghul** [comment]
Can you please try this patch?

```
diff --git a/react/features/mobile/navigation/components/RootNavigationContainer.js b/react/features/mobile/navigation/components/RootNavigationContainer.js
index 54001c8bd..1c660bbf6 100644
--- a/react/features/mobile/navigation/components/RootNavigationContainer.js
+++ b/react/features/mobile/navigation/components/RootNavigationContainer.js
@@ -1,6 +1,6 @@
 import { NavigationContainer } from '@react-navigation/native';
 import { createStackNavigator } from '@react-navigation/stack';
-import React, { useCallback } from 'react';
+import React, { useEffect } from 'react';
 import { StatusBar } from 'react-native';
 
 import { connect } from '../../../base/redux';
@@ -44,17 +44,17 @@ type Props = {
 const RootNavigationContainer = ({ dispatch, isWelcomePageAvailable }: Props) => {
     const initialRouteName = isWelcomePageAvailable
         ? screen.welcome.main : screen.connecting;
-    const onReady = useCallback(() => {
+
+    useEffect(() => {
         dispatch({
             type: _ROOT_NAVIGATION_READY,
             ready: true
         });
-    }, [ dispatch ]);
+    }, []);
 
     return (
         <NavigationContainer
             independent = { true }
-            onReady = { onReady }
             ref = { rootNavigationRef }
             theme = { navigationContainerTheme }>
             <StatusBar
```

**Comment by softavail** [comment]
@saghul I applied the changes and made a build. Unfortuately It is not working :(. Do you want me to provide logs as well?

**Comment by saghul** [comment]
Damn. Yes please, can you add a log there inside useEffect?

I'm starting to believe the cause might be RN is not fully running because the app was launched in the background.

**Comment by softavail** [comment]
@saghul 
The log I put is not printed until I unlock the device ( i.e. when the app goes foreground )

I put the log like this
```
const RootNavigationContainer = ({ dispatch, isWelcomePageAvailable }: Props) => {
    const initialRouteName = isWelcomePageAvailable
        ? screen.welcome.main : screen.connecting;

    useEffect(() => {

        logger.info('[TEST] RootNavigationContainer useEffect');
        dispatch({
            type: _ROOT_NAVIGATION_READY,
            ready: true
        });
    }, []);
```

When I answer the call in background and do not unlock the device I see these two lines
```
[JitsiMeetLog] '2023-02-02T13:23:01.918Z', '[modules/browser/BrowserCapabilities.js]', 'This appears to be react-native, ver: 0.68.5'
[JitsiMeetLog] Running "App
```

When I unlock the device and bring the app in foreground, I see rest of the logs
```
[JitsiMeetLog] RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
[JitsiMeetLog] RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
[JitsiMeetLog] [features/app] [TEST] RootNavigationContainer useEffect
[JitsiMeetLog] [features/app] appNavigate to https://dev-jitsi.qamyjitsi.com/5Rz6fYBQSMkcsor5jheE74?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhbnktYXVkLWFjY2VwdHMiLCJzdWIiOiIqIiwiY29udGV4dCI6eyJ1c2VyIjp7ImlkIjoiMjg3MTJmY2QtYzZmOC00ZjVkLTkyNzYtNDRiOTJkYjk4NWI1IiwibWVtYmVySWQiOiJxTHJob2dpdks2eDRhem4zV3pPVWk3IiwiZW1haWwiOm51bGwsImF2YXRhciI6bnVsbCwibmFtZSI6IkFuZ2VsICBBMSJ9fSwiaXNzIjoiQ29tZXJhQ29uZiIsInJvb20iOiI1Uno2ZllCUVNNa2Nzb3I1amhlRTc0IiwiZXhwIjoxNjc1NDMwNTU3fQ.lDQfkoqsKssKabZM31dcdJz2IAH363iCKS0WbxlsdXs#config.startWithVideoMuted=false&config.subject=%22jitsi%20Conference%22
[JitsiMeetLog] [features/base/connection] No connection found while disconnecting.

etc.

```

**Comment by softavail** [comment]
One more thing, I do not kill the app at all. I launch the app, put it in background and lock the screen. Then receive a call, answer and stay in locked screen

**Comment by softavail** [comment]
@saghul did you have a chance to analyse the latest logs. Any update is highly appreciated.

**Comment by saghul** [comment]
Hi there! Sorry for the delay. Yes I saw the logs but forgot to reply.

I'm not sure what's going on TBH. I suspect the App component doesn't start because the application is in the background, but I need to try and dig in the react native code to find the answer.

**Comment by alirezarabiei7239** [comment]
Hi,
Any update on this issue?

**Comment by saghul** [comment]
Sorry we got no leads.

**Comment by abdurrahmancuce** [comment]
Hi,
Any update on this issue?

**Comment by saghul** [comment]
Nope, sorry.

**Comment by softavail** [comment]
@saghul I can help you investigate and fix this. Can you let me know what additional logs to put and where and I can do it. 
Seems that the React doesn't start until the phone is unlocked and the app is foregrounded.
Do you have some thoughts I can try?
If you can spend some time troubleshooting this issue, it will be great!
Thanks!!!

**Comment by saghul** [comment]
Let me try to look into it this week, I need to re-remember everything here 😅
