### ISSUE TITLE
Issue in Jitsi-meet audio

### ISSUE THREAD

**Issue by venkateshyella** [jitsi/jitsi-meet#1231]
Hi ,

We have issue in jitsi-meet : audio is not working if jitsi is in idle state for some hours

Once i restart it is working fine but what is the permanent solution for this issue

We found below error in "jicofo.log" file

Jicofo 2017-01-09 16:03:01.332 SEVERE: [99] org.jitsi.jicofo.ChannelAllocator.log() Failed to allocate channels for testvideocall@conference.10.0.0.150/sreeni-0ec2d3
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to allocate channels - no bridge configured
at org.jitsi.jicofo.ChannelAllocator.allocateChannels(ChannelAllocator.java:372)
at org.jitsi.jicofo.ChannelAllocator.createOffer(ChannelAllocator.java:307)
at org.jitsi.jicofo.ChannelAllocator.discoverFeaturesAndInvite(ChannelAllocator.java:166)
at org.jitsi.jicofo.ChannelAllocator.run(ChannelAllocator.java:135)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Jicofo 2017-01-09 16:03:01.333 SEVERE: [99] org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.checkIfDisposed().148 Not doing expireConference - bridge not initialized
Jicofo 2017-01-09 16:03:01.407 INFO: [86] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverParticipantFeatures().146 testvideocall@conference.10.0.0.150/venky-2a39f4, features:
Jicofo 2017-01-09 16:03:01.407 INFO: [86] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverParticipantFeatures().149 http://jabber.org/protocol/caps

**Comment by corecache** [comment]
Got this error recently too - upgraded to latest version around beginning 5th of January - from a 2-3 week old stable version (sorry cant remember the exact version, hence the time indicatons)

**Comment by damencho** [comment]
Jicofo is doing health checks against jvb and if jvb has a problem or health check fails it is marked as faulty and is no longer used, when this happens you need to check the logs and there you should see the failed health check and the reason for it. Those logs should be somewhere before the log about the "Failed to allocate channels - no bridge configured"

**Comment by damencho** [comment]
We discovered an issue where if jvb is not used for long time at can fill all allowed file descriptors for jvb system user fail on a health check and have the same symptoms as described.
If this is your case before the unsuccessful meeting you should have an error like this in jicofo logs:
Jicofo 2017-01-10 09:51:06.216 WARNING: [15] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.damencho.jitsi.net error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="u
rn:ietf:params:xml:ns:xmpp-stanzas">Failed to acquire DatagramSocket specific to STUN communication</text></error>

And as this one in jvb logs:
JVB 2017-01-10 09:51:06.207 SEVERE: [117] org.ice4j.ice.HostCandidate.log() Failed to acquire DatagramSocket specific to STUN communication.
java.net.SocketException: Too many open files (Error creating socket)
        at java.net.PlainDatagramSocketImpl.datagramSocketCreate(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.create(AbstractPlainDatagramSocketImpl.java:80)

A fix was provided and soon it will land in nightlies.

**Comment by venkateshyella** [comment]
The problem solved when we have disabled Jicofo health checks.
We added below property in /etc/jitsi/jicofo/sip-communicator.properties

org.jitsi.jicofo.HEALTH_CHECK_INTERVAL=-1

**Comment by rasos** [comment]
Disabling health checks did not work for us. No conference call could be established at all. Nightly did the job, though.

**Comment by karras** [comment]
We encountered the exact same issue. I can see the STUN entries in the jvb.log:
```
jvb.log.1:JVB 2017-03-21 19:20:05.987 SEVERE: [312] org.ice4j.ice.HostCandidate.log() Failed to acquire DatagramSocket specific to STUN communication.
```
Then today we could no longer join any channels:
```
Jicofo 2017-03-22 09:30:00.677 SEVERE: [99] org.jitsi.jicofo.ChannelAllocator.log() Failed to allocate channels for test42@conference.example.com/904ca21f
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to allocate channels - no bridge configured
```

I've disabled the health checks for now and we'll see if it resolves the problem.

Thanks a lot! 🎉

**Comment by damencho** [comment]
If you are hitting the problem in jvb with leaking file descriptors you will need restart of jvb. This is fixed in nightlies and I hope to release to stable soon.

**Comment by mchris22** [comment]
We experience the same problem after just running Jitsi Meet for a short while:

`net.java.sip.communicator.service.protocol.OperationFailedException: Failed to allocate channels - no bridge configured`

Already tried to disable health checks which did not help. Currently running the latest nightly build from .deb package (1.0.2010-1).

**Comment by scream4ik** [comment]
Hello. I get same error when i try open room between two or more different users (two different browsers / sessions) on one computer localy or between two or more different users using stage server
On web interface users get error: unfortunately something went wrong

I try to stable and nightly builds. But nothing helped.

**Comment by damencho** [comment]
For some reason the bridge is missing, you need to check jvb and jicofo logs, to provide more info.

**Comment by manang** [comment]
Hi, did you solve this issue?

**Comment by bfjeje** [comment]
> Hello. I get same error when i try open room between two or more different users (two different browsers / sessions) on one computer localy or between two or more different users using stage server
> On web interface users get error: unfortunately something went wrong
> 
> I try to stable and nightly builds. But nothing helped.

I have the exactly same problem.
