### ISSUE TITLE
Details in screenSharingStatusChanged event is empty object

### ISSUE THREAD

**Issue by KrzysiekBro** [jitsi/jitsi-meet#12319]
### Description:

Details in screenSharingStatusChanged event is empty object

After start screen sharing i received empty object in property details { details : {} on :  true }

There should be sourceType in details, documentation below

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events/#screensharingstatuschanged

### Steps to reproduce:

1. Create event handler on screenSharingStatusChanged
For example
jitsiApiRef?.current?.on('screenSharingStatusChanged', onScreenShare);
const onScreenShare = (status: { on: boolean, details: { sourceType: string | undefined } }) => { //some method }
2. Run screen sharing
3. After running screen sharing event receive empty object in details { details : {} on :  true }

### Expected behavior:

After running screen sharing event should receive sourceType in details

### Actual behavior:

After running screen sharing event receive empty object in details { details : {} on :  true }

### Server information:

- Jitsi Meet version: jitsi-meet-web_1.0.6155
- Operating System: Ubuntu 20.04.5 LTS

### Client information:

- Browser / app version: Chrome 106.0.5249.103, Firefox 105.0.2
- Operating System: Windows 10 Pro 64bit

### Fix code ###

File react\features\base\conferencefre\middleware.web.js:222

Update line 222  screensharingDetails.sourceType = desktopVideoTrack.metadata.displaySurface;

**Comment by jallamsetty1** [comment]
@KrzysiekBro, thanks for the report. Looks like sourceType for the desktop track was not implemented for the browser client, currently its supported only on electron and spot.

**Comment by KrzysiekBro** [comment]
@jallamsetty1 @saghul thanks for quick fix

**Comment by KrzysiekBro** [comment]
@jallamsetty1 @saghul can you tell me when this fix will be released in jitsi-meet library ? This is very important fix for our business feature. Best regards.

**Comment by saghul** [comment]
We just made a stable release yesterday and this just landed, so it'll take a few weeks to hit stable. If what you ask is when we'll bump lib-jitsi-meet in jitsi-meet, that will likely happen today.

**Comment by KrzysiekBro** [comment]
I mean stable release with this fix. Thanks for answer.
