### ISSUE TITLE
Make Kickout term and Kickout message configurable

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [jitsi/jitsi-meet#12337]
When I removed someone from the meeting, it showed him a notification saying: you have been Kicked Out of the meeting! (Not a professional approach)

Currently, there seems to be no way of changing the Kickout message.
It'd be great if we can modify this programmatically in android and ios SDK's.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/113885801/194537624-bc53f8b0-3fbc-4bf5-950a-8f27255cf2a9.png)

**Comment by saghul** [comment]
Translations are not directly configurable. You'd need to rebuild the SDK. We have no plans to make individual terms configurable, it's just a slippery slope.

If you have your own deployment you can configure label overrides per language with dynamic branding: https://github.com/jitsi/jitsi-meet/blob/68f79e52e7d3341e98411df402fb504bb4b612bc/react/features/base/i18n/middleware.ts#L19

I just realized this is currently not documented in config.js, so I'll do that.
