### ISSUE TITLE
Thanks to the author

### ISSUE THREAD

**Issue by qinvb** [jitsi/jitsi-meet#12345]
1. I use "pod" to install JitsiMeetSDK, and can make audio and video calls normally
2. Download the github source code and compile the SDK for use. The jitsiMeetView object is found to be uninitialized and cannot display audio and video pages
![20221009093247](https://user-images.githubusercontent.com/31240237/194733416-bacee69d-ca43-4f22-ad25-9dc99e511452.jpg)

**Comment by saghul** [comment]
What Xcode version are you using? Did you run pod install?

**Comment by qinvb** [comment]
Hello, I ran npm install. After success, I ran pod install, and then directly compiled sdk for export and use
![20221009144820](https://user-images.githubusercontent.com/31240237/194742336-b9ea45f6-ffc0-4c81-9b32-5b8edb07cd61.jpg)
![20221009144425](https://user-images.githubusercontent.com/31240237/194742339-7b654722-83be-4598-8079-5c7827578f94.jpg)
![20221009144602](https://user-images.githubusercontent.com/31240237/194742340-30699306-d834-4745-b736-82d91f6b7736.jpg)
![20221009144812](https://user-images.githubusercontent.com/31240237/194742342-1895919f-b1fe-4b08-9402-b026baf07084.jpg)

**Comment by qinvb** [comment]
This is where I use pod 'JitsiMeetSDK', '~> 5.0.0 ', automatically configured, and it works fine.
![20221009150018](https://user-images.githubusercontent.com/31240237/194742699-7691ce8b-6db4-4a6c-8c94-42509e49beb3.jpg)

**Comment by qinvb** [comment]
Manual configuration In addition to importing the JitsiMeetSDK and WebRTC, do you need to configure other areas?

**Comment by saghul** [comment]
No, just adding the framework should be enough.

Any reason why you can't use our released pod?
