### ISSUE TITLE
i have this issue

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [jitsi/jitsi-meet#12343]
Caused by: java.lang.RuntimeException: Duplicate class org.webrtc.AndroidVideoDecoder found in modules jetified-google-webrtc-1.0.30039-runtime (org.webrtc:google-webrtc:1.0.30039) and jetified-react-native-webrtc-1.100.0-jitsi-10639879-runtime (com.facebook.react:react-native-webrtc:1.100.0-jitsi-10639879)

**Comment by saghul** [comment]
You are using some library which also uses the WebRTC framework, albeit a different build, than react-native-webrtc.

That won't work.

Your only way out is to exclude it from one of the 2 libraries and hope for the best.

**Comment by Jaymin-Bhadani** [comment]
if i exclude this :- 

    //meeting
    implementation ('org.jitsi.react:jitsi-meet-sdk:5.1.0') { transitive = true
        exclude group: 'com.facebook.react', module: 'react-native-webrtc'
    }

they not work

i also using this 

    implementation 'org.webrtc:google-webrtc:1.0.30039'

**Comment by Jaymin-Bhadani** [comment]
if i have this line     exclude group: 'com.facebook.react', module: 'react-native-webrtc'

in jitsi that not work

**Comment by saghul** [comment]
You can't exclude react-native-WebRTC. You need to exclude WebRTC itself.
