### ISSUE TITLE
Excuse me? How can I set the default earpiece and speaker, front camera and rear camera

### ISSUE THREAD

**Issue by ldm0330** [jitsi/jitsi-meet#12347]
When entering the conference, the default external player will be frightened. I need to set the default earpiece and the default rear camera. What should I do

**Comment by saghul** [comment]
This is not possible, sorry. You need to do it once in the meeting.

**Comment by 337077418** [comment]
> This is not possible, sorry. You need to do it once in the meeting.

What he wants to ask is whether there is an API that sets the default camera as front or rear. The default handset is in the SDK source code:

// Pick the desired device based on what's available and the mode.

String audioDevice;

if (bluetoothAvailable) {

audioDevice = DEVICE_ BLUETOOTH;

} else if (headsetAvailable) {

audioDevice = DEVICE_ HEADPHONES;

} else {

audioDevice = DEVICE_ SPEAKER;

}

------------------------------
I also want to know how to modify the default rear camera

**Comment by saghul** [comment]
We currently have no API to modify the default behavior for audio devices or cameras. A patch would be acceptable if it retrains the current behavior and is not too involved.
