### ISSUE TITLE
I'm developing my own video-conference Android-App and using the jitsi-sdk. But I want to set the back camera of my Smartphone as default. The user can change it once the conference is launched, but my goal is to change it before the conference begins without user interactions.

### ISSUE THREAD

**Issue by 337077418** [jitsi/jitsi-meet#12352]
I'm developing my own video-conference Android-App and using the jitsi-sdk. But I want to set the back camera of my Smartphone as default. The user can change it once the conference is launched, but my goal is to change it before the conference begins without user interactions.

I tried  CameraCaptureController.java

@Override
protected VideoCapturer createVideoCapturer() {
    String deviceId = ReactBridgeUtil.getMapStrValue(this.constraints, "deviceId");
    String facingMode = ReactBridgeUtil.getMapStrValue(this.constraints, "facingMode");
    return createVideoCapturer(deviceId, facingMode);
}

to this 

@Override
protected VideoCapturer createVideoCapturer() {
    String deviceId = ReactBridgeUtil.getMapStrValue(this.constraints, "deviceId");
    String facingMode = ReactBridgeUtil.getMapStrValue(this.constraints, "facingMode");
    return createVideoCapturer(deviceId, "environment");
}

---But it didn't work

**Comment by 337077418** [comment]
I also tried these
.........................1......................
 // Unconditionally express the desires/expectations/intents of the app and
    // the user i.e. the state of base/media. Eventually, practice/reality i.e.
    // the state of base/tracks will or will not agree with the desires.
    dispatch(setAudioMuted(audioMuted));
    dispatch(setCameraFacingMode(CAMERA_FACING_MODE.ENVIRONMENT));
    dispatch(setVideoMuted(videoMuted));
----------2---------
// FIXME Technically, _VIDEO_INITIAL_MEDIA_STATE is a constant internal to the
// feature base/media and used in multiple files so it should be in
// constants.js. Practically though, VideoMediaState would then be used in
// multiple files as well so I don't know where and how to move it.
/**
 * Initial state for video.
 *
 * @type {VideoMediaState}
 */
export const _VIDEO_INITIAL_MEDIA_STATE = {
    available: true,
    facingMode: CAMERA_FACING_MODE.ENVIRONMENT,
    muted: 0,

---But it didn't work   please！help help help

**Comment by saghul** [comment]
Please don't duplicate issues. You have already commented on https://github.com/jitsi/jitsi-meet/issues/12347, follow up there.
