### ISSUE TITLE
Flag config.prejoinConfig.enabled is not working.

### ISSUE THREAD

**Issue by andreipro1002** [jitsi/jitsi-meet#12354]
### Description:
Flag **config.prejoinConfig.enabled** is not working.

### Steps to reproduce:

1. Open the meeting with room url: https://${serverUrl}/${roomName}#config.prejoinConfig.enabled=false
2. After connecting, the pre-join screen is displayed

### Expected behavior:

Pre-join screen should not be displayed.

### Actual behavior:

Pre-join screen is displayed.

### Client information:

- Jitsi Meet version: iOS SDK 6.0.0
- Operating System: iOS 12.5.6 and iOS 15.4.1

### Additional information:

I've tried also with https://${serverUrl}/${roomName}#config.prejoinConfig.enabled=false&config.requireDisplayName=false&config.prejoinConfig.hideDisplayName=true but with no succes

**Comment by saghul** [comment]
The prejoin screen is currently not configurable on the mobile apps, it defaults to ON.

**Comment by andreipro1002** [comment]
@saghul Can you please tell me what it needs to be modified in the sdk / react source code for it to work? Or can you tell me what's the newest iOS SDK version that doesn't have the pre-join screen? Thanks in advance.

**Comment by andreipro1002** [comment]
The main problem with the Pre-join screen on iOS is that when the app is in background or the device screen is locked, and the user receives a call, after the accept button is pressed the CallKit screen is displayed but the user can't participate in call until he goes through the Pre-join screen. The main idea is that when the user accepts a call through CallKit, he should automatically join the call. In this case after he accepts the call, he has to press the App button from the CallKit screen and after that the "join meeting" button.

**Comment by saghul** [comment]
Sorry I forgot about the feature flag which can be used to disable it 😅 https://github.com/jitsi/jitsi-meet/blob/4a54f4bedc6f3781dc474191e5d65dcb6b252b4e/react/features/base/flags/constants.ts#L167
