### ISSUE TITLE
Beta version of Jitsi Meet

### ISSUE THREAD

**Issue by jdjohnson6149** [jitsi/jitsi-meet#1236]
Hello,

When i visit https://meet.jit.si/ I realize that the interface is a newer version than the one that is installed on my server. I tried installing the latest version but It does not have the side menu that is on that site. You can visit my videobridge for reference. https://videobridge.phonoscope.com/video

Any help is much appreciated, you guys rock. We love jitsi and look forward to using it more.

Thanks,

James Johnson

**Comment by damencho** [comment]
Could you please use the mailinglists for questions and problems before opening issues.

You are using version of jitsi-meet 1075, which I'm not sure where did you get it. Current stable is 1592 and nightly is 1598.
You can find up-to-date instructions for installation:
- stable here: https://jitsi.org/Main/InstallJitsiMeetDebianStableRepository
- nightly here: https://jitsi.org/Main/InstallJitsiMeetDebianNightlyRepository

**Comment by jdjohnson6149** [comment]
Hey so sorry about that! I appreciate your help. I have the correct version there now but for some reason the images for the buttons only show up on mozilla and not chrome. Do you know why this is? Is there somewhere I can donate to you guys? I appreciate the help so much. thanks again.
