### ISSUE TITLE
Raisehand icon in top bar

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#12365]
Raisehand icon has little contrast. I suggest coloring the icon to white.

Before
<img width="343" alt="imagem2" src="https://user-images.githubusercontent.com/32515675/195296843-4525948f-e115-42d6-a7cf-f6f2364108a9.png">

After
<img width="335" alt="imagem3" src="https://user-images.githubusercontent.com/32515675/195298450-863291e9-1e78-4428-b49a-de69f7d03591.png">

Change SVG. Fill to white.
`<svg fill="white" height="16" width="16" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.917 3.208v8.709a.917.917 0 0 0 1.833 0V4.833c0-.097.168-.25.458-.25.29 0 .459.153.459.25v7.084a.917.917 0 0 0 1.833 0V6.875a.458.458 0 1 1 .917 0v6.913c-.25 2.552-2.425 4.545-5.042 4.545a5.037 5.037 0 0 1-4.205-2.258l-.003.001-3.495-5.255c-.168-.24-.117-.526.09-.671a.458.458 0 0 1 .638.112l1.173 1.753h-.001a.917.917 0 0 0 1.676-.482h.002V5.043a.458.458 0 0 1 .917-.001V11.918a.917.917 0 0 0 1.833 0V3.208a.458.458 0 1 1 .917 0Zm7.317 10.56.016-.008V6.876a2.292 2.292 0 0 0-2.76-2.244c-.112-1.055-1.091-1.881-2.282-1.881-.17 0-.335.017-.495.049a2.292 2.292 0 0 0-4.51.004 2.292 2.292 0 0 0-2.786 2.238v3.663a2.293 2.293 0 0 0-3.27 3.135l3.302 4.94a6.875 6.875 0 0 0 12.785-3.01Z"></path></svg>`

Thank you very much
José Luís Andrade

**Comment by saghul** [comment]
Yep, this has regressed. Generally speaking we should not specify the full in the SVG so the code colors it.
