### ISSUE TITLE
How to set live stream to youtube

### ISSUE THREAD

**Issue by alfredogt** [jitsi/jitsi-meet#1237]
Someone can explain me how to configure jitsi-meet to transmit to youtube, there is not much documentation about it ...

And install Jitsi in Ubuntu 16.04 and I have managed to transmit in the traditional way, now I want to integrate Jitsi with Youtube.

Thank you.

**Comment by damencho** [comment]
Please use the mailinglist for problems or questions, before opening issues.

Take a look at: https://github.com/jitsi/jibri.
