### ISSUE TITLE
Add markdown/file upload to chat

### ISSUE THREAD

**Issue by nsde** [jitsi/jitsi-meet#12377]
**Is your feature request related to a problem you are facing?**
No.

**Describe the solution you'd like**
Please add a WYSIWGYG field for the chat. If you have enough server capacity, I'd also be very happy to see a file upload feature, even if it limits to like 8MB.

**Describe alternatives you've considered**
–

**Comment by nsde** [comment]
See
- https://en.wikipedia.org/wiki/WYSIWYG
- https://html-cleaner.com/wysiwyg-html-editor/
![image](https://user-images.githubusercontent.com/67185896/195590992-8f46bfc5-3310-4961-900f-1e1a2984ce54.png)

**Comment by saghul** [comment]
Sorry, we like to keep the chat simple. A WYSIWYG editor is the opposite of that.



> I'd also be very happy to see a file upload feature, even if it limits to like 8MB.

That would mean we need to host the files, with all the associated privacy implications. This is not something we want to do.
