### ISSUE TITLE
Authentication dialog user and password are in white text on white background with autofill on Firefox

### ISSUE THREAD

**Issue by peterkuma** [jitsi/jitsi-meet#12389]
### Description:

When authenticating to a room, an authentication dialog is shown. In Firefox 102.3.0esr on Linux, when autofill is enabled in the browser for the website, the text in the `User` and `User password` input is white on white background. This is mostly likely because the browser overrides the `background-color` CSS property on the input elements to white, but does not change the color of the text to black. It can be fixed by setting the property `background: rgb(61, 61, 61)` instead of `background-color: rgb(61, 61, 61)` for `.css-vq8mnb-input`.

### Steps to reproduce:

1. Open web page of a room which requires authentication.
2. Click on `I am the host`. The authentication dialog appears.

### Expected behavior:

The autofilled user and password are either bright on dark background or vice versa.

### Actual behavior:

The text as well as the background are white.

<img src="https://user-images.githubusercontent.com/1387136/196004228-1c813acb-6c51-4584-b545-b39b3d50d1b8.png" width="400" />

### Server information:

- Jitsi Meet version: 2.0.7882-1
- Operating System: Debian GNU/Linux 11 (bullseye)

### Client information:

- Browser / app version: Firefox 102.3.0esr
- Operating System: Devuan GNU/Linux 4 (chimaera)

**Comment by saghul** [comment]
Ping @robertpin

**Comment by robertpin** [comment]
Works fine on Firefox on macOS and I can't test it on Linux. I can make the suggested change but I can't test it

**Comment by saghul** [comment]
@peterkuma Can you reproduce it on meet.jit.si ?

**Comment by peterkuma** [comment]
It only happens when `privacy.resistFingerprinting` is enabled in `about:config` in Firefox. It should be reproducible on macOS too. Sorry for not providing this information before, I only found out later.

**Comment by robertpin** [comment]
Even with `privacy.resistFingerprinting` set to `true` it still works fine on macOS (latest Firefox)
![image](https://user-images.githubusercontent.com/11474153/197718722-81f341db-181d-44b8-ba8e-0f58656372d3.png)

**Comment by robertpin** [comment]
Managed to repro. I'll create a fix
