### ISSUE TITLE
Disable "security options" not working on iOS

### ISSUE THREAD

**Issue by andreipro1002** [jitsi/jitsi-meet#12380]
### Description:

I'm trying to remove some of the buttons from toolbar but doesn't seem to have any effect. One of the buttons is the 
"Security options".

### Steps to reproduce:

1. use the feature flag "security-options.enabled'" = false in the JitsiMeetConferenceOptions builder
2. Jitsi call contains the "Security Options" button in the menu

### Expected behavior:

Jitsi call should not contain the "Security Options" button in the menu

### Actual behavior:

Jitsi call contains the "Security Options" button in the menu

### Client information:

- Jitsi iOS SDK version: 3.10.4
- Operating System: iOS 12 and iOS 15

### Additional information:

I've tried also with adding the toolbar buttons via config in the room url, but it seems it gets ignored and all the buttons are being displayed: https://${serverUrl}/${roomName}#config.toolbarButtons=["camera", "microphone", "participants-pane"]".

Probably the mobile library doesn't support this yet, if this is the case, can I get some info how to disable it from the react source code?  Thanks in advance.

**Comment by saghul** [comment]
That option didn't exist in that SDK version. It's too old. Please update.

**Comment by andreipro1002** [comment]
@saghul I would update it if there would be a good newer iOS SDK version. Version 4.x.x has that audio echo bug which was solved in 5.x.x, but from there it was introduced the Pre-join screen which can't be disabled on mobile (see https://github.com/jitsi/jitsi-meet/issues/12354). It's literally impossible to use newer versions if you don't support basic functionality for it on mobile. At least please tell me how to disable the toolbar buttons from the react source code.

**Comment by saghul** [comment]
I made a mistake in the other issue, the prejoin screen can be disabled with a feature flag: https://github.com/jitsi/jitsi-meet/blob/4a54f4bedc6f3781dc474191e5d65dcb6b252b4e/react/features/base/flags/constants.ts#L167

**Comment by andreipro1002** [comment]
@saghul Ok thanks I will try it, but from what I tested I got a lot of random call fails with CallKit... On versions 3.x.x or less I had no such problems.

**Comment by saghul** [comment]
Without a proper bug report I cannot help you.
