### ISSUE TITLE
View with more than 23 attendees : provide a layout with hexagonal images of each attendee

### ISSUE THREAD

**Issue by jerome-bouat** [jitsi/jitsi-meet#12392]
**Is your feature request related to a problem you are facing?**
When many attendees are in the meeting, there is a difficulty to view each attendee. The rectangular view of each attendee displays a part of meaningless information in the edges of the rectangle. On another side, providing a circle view would increase the ratio between useful image part and the meaningless image part. However this later alternative would infer a loss a place because of the layout of the circle views besides each other.

**Describe the solution you'd like**
The bees provided a solution in order to lower the consumption of beeswax between each alveolus. The hexagonal pattern is close to a circle pattern but it allows an optimal layout in order to lower the total borders length between the patterns.

**Comment by saghul** [comment]
We have no plans to move away from rectangular tiles, sorry.

You could configure more columns and rows which would make tiles smaller, hope that helps.
