### ISSUE TITLE
chat.sendButton not translate

### ISSUE THREAD

**Issue by janitorku** [jitsi/jitsi-meet#12390]
minor bug report

![chat sendbutton](https://user-images.githubusercontent.com/61498019/196024836-aedfbf1a-c965-42c6-815f-4cb785493ae7.png)

### Description:

i can't see translation chat.sendButton.
Fixed by adding sendButton variable into language files.

   "chat": {
        "error": "Error: your message was not sent. Reason: {{error}}",
        "fieldPlaceHolder": "Type your message here",
        "messageTo": "Private message to {{recipient}}",
        "messagebox": "Type a message",
        **"sendButton": "Send",**
...

### Steps to reproduce:

1. https://meet.jit.si
2. click Open Chat
3. mouseover on submit button

**Comment by saghul** [comment]
Sounds good, can you send a PR?

**Comment by janitorku** [comment]
Sure. done. #12391
