### ISSUE TITLE
JWT token authorization fails when room name is a regex

### ISSUE THREAD

**Issue by lianzhi-bc** [jitsi/jitsi-meet#12398]
### Steps to reproduce:

When I enable "token_verification" plugin then construct a JWT token with a regex room name like this, it always fails authorization.
```json
{
  "sub": "meet.example.com",
  "moderator": true,
  "context": {
    "room": {
      "regex": true
    },
    "user": {
      "name": "guest",
      "email": "guest@example.com",
      "id": "1234567"
    }
  },
  "room": "trymeet_.*",
  "iss": "coret",
  "aud": "coret"
}
```

### Expected behavior:

Authorization succeeded.

### Actual behavior:

Authorization failed, log looks like this:
```log
meet.example.com:token_verification     error   Token eyXXXXXXX not allowed to join: trymeet_abcdefg@meet.example.com/xxxxxxx
```

### Server information:

- Jitsi Meet version: stable,now 2.0.7648-1
- Operating System: Debian GNU/Linux 10 (buster)

### Client information:

- Browser / app version: Any
- Operating System: Any

### Additional information:

I think it's a bug [here](https://github.com/jitsi/jitsi-meet/blob/66cddddd3e213d8fa1878c70cad91a6fe4763dfe/resources/prosody-plugins/token/util.lib.lua#L294). I modify it like this then it works:
```lua
    if not self.enableDomainVerification and not (session.jitsi_meet_context_room and (session.jitsi_meet_context_room["regex"] == true or session.jitsi_meet_context_room["regex"] == "true")) then
        -- if auth_room is missing, this means user is anonymous (no token for
        -- its domain) we let it through, jicofo is verifying creation domain
        if auth_room and (room ~= auth_room and not ends_with(room, ']'..auth_room)) and auth_room ~= '*' then
            return false;
        end

        return true;
    end
```
I'm not sure how to modify this line of code correctly and gracefully, please help me, thanks!

**Comment by saghul** [comment]
I'm not sure we ever intended to support that use case. @damencho ?

**Comment by abora8x8** [comment]
The JWT structure for regex matching looks ok. if you enable `enableDomainVerification` by setting `enable_domain_verification` to true in `prosody.cfg.lua` should work.

**Comment by lianzhi-bc** [comment]
I add 'enable_domain_verification = true' in prosody.cfg.lua and it works, thank you!
