### ISSUE TITLE
Authentication dialog not shown (secure domain with LDAP auth)

### ISSUE THREAD

**Issue by drpetersen** [jitsi/jitsi-meet#12406]
### Description:

I am unable to start a conference from the web client when secure domain (with LDAP auth) is enabled. LDAP auth as such and everything else works, as the conference can be initiated from the Android client. Once in the conference, authentication does work from the Profile tab of the settings dialog (moderator rights are granted), so I suspect a problem with the Jitsi Meet Web App.

### Steps to reproduce:

1. Open conference URL on a secure domain-enabled host, e.g. https://meet.example.com/MyConferenceName, in web browser
2. Click the "Join meeting" button
3. In the "Waiting for the host …" dialog, click the "I am the host" button

### Expected behavior:

The "Authentication required" dialog should open, allowing to enter username and password.

### Actual behavior:

After a short time, the "Waiting for the host …" dialog reappears instead of the "Authenticaiton required" dialog.

### Server information:

- Jitsi Meet version: 2.0.7948
- Operating System: Debian GNU/Linux 11

### Client information:

- Browser / app version: Tested with
   - Chromium Version 106.0.5249.119 (Official Build) built on Debian bookworm/sid, running on Debian bookworm/sid (64-bit)
   - Brave [Version 1.45.104 Chromium: 106.0.5249.126 (Offizieller Build) beta (64-Bit)](https://brave.com/latest/)
   - Firefox 105.0.1 (64-Bit)
   - LibreWolf 105.0.3-1
- Operating System: Debian GNU/Linux bookworm/sid

### Additional information:

The bug was introduced with version 2.0.7948 (and persists at least up to version 2.0.7956), versions 2.0.7947 and before are working fine.

**Comment by gpatel-fr** [comment]
For the record, the problem is not specific to LDAP, it can be reproduced with secure domain for current unstable (7982)

**Comment by gpatel-fr** [comment]
As far as I know, this is now fixed for vanilla secure domain at least since version 2.0.8004. Unsure if it will help you since Jitsi-meet LDAP auth is more or less destined to the dustbin of history....

**Comment by saghul** [comment]
Damn I was searching for this message to drop a line and couldn't find it 😅  Thanks @gpatel-fr !

**Comment by drpetersen** [comment]
Thank you for the info, I can confirm that LDAP auth works again with 2.0.8004.
