### ISSUE TITLE
SetSubject requires moderator rights

### ISSUE THREAD

**Issue by andreipro1002** [jitsi/jitsi-meet#12409]
### Description:

Using the iOS SDK version 6.1.0 you cannot longer set subject in the _JitsiMeetConferenceOptionsBuilder_ object when the user is callee. 

Error: _[JitsiConference.js] Failed to set subject, participant is not a moderator_

The problem with this is that it affects the CallKit display name.
When the user receives an incoming call it displays correctly:

![Screen Shot 2022-10-19 at 05 02 03](https://user-images.githubusercontent.com/4287792/196581134-43046386-fa9f-4b0c-9c17-68ad607002bd.png)

But after he joins the conference, the display name is changed to the Call UUID.

![Screen Shot 2022-10-19 at 05 02 09](https://user-images.githubusercontent.com/4287792/196581237-8001068f-cc5c-4568-9b3d-41f9cde7ab90.png)

Setting the subject on older SDK versions (ex v2.9.3), would override the display name, but in last version (v6.1.0) you cannot longer set the subject since the user doesn't have moderator rights.

What I tried was to modify _JitsiConference.js_ file inside the _node_modules_ folder removing the _this.room.isModerator()_ condition, reinstall the pods and generate the .framework. But this didn't seem to work, any ideas how can I accomplish this?

**Comment by saghul** [comment]
You can set the localSubject config override, which does not propagate the subject and as such does not require to be a moderator.
