### ISSUE TITLE
How do I switch between cameras and speakers after a meeting starts

### ISSUE THREAD

**Issue by qinvb** [jitsi/jitsi-meet#12414]
I didn't use the toolbar that comes with sdk. 
I customized 5 buttons, 3 of which have realized corresponding functions
 but I didn't find the API for speaker microphone switch and camera
![Screen Shot 2022-10-19 at 17 49 18](https://user-images.githubusercontent.com/31240237/196659841-e42153ee-79cf-4f95-8d1d-67f492b34bd1.png)

**Comment by 337077418** [comment]
> 我没有使用sdk自带的工具栏。 我自定义了5个按键，其中3个已经实现了相应的功能 ，但是没有找到扬声器麦克风开关和摄像头的API ![屏幕截图 2022-10-19 在 17 49 18](https://user-images.githubusercontent.com/31240237/196659841-e42153ee-79cf-4f95-8d1d-67f492b34bd1.png)

Hello, I'm currently implementing video call related functions. It seems that you are ahead of me. I'd like to ask what you suggest for A to hang up the phone and B to automatically exit the conference room synchronously

**Comment by qinvb** [comment]
My iPhone is set in simplified Chinese, and the Xcode project is also set in Chinese language. I don't know why the JitsimeetView still displays English.

**Comment by qinvb** [comment]
> > 我没有使用sdk自带的工具栏。 我自定义了5个按键，其中3个已经实现了相应的功能 ，但是没有找到扬声器麦克风开关和摄像头的API ![屏幕截图 2022-10-19 在 17 49 18](https://user-images.githubusercontent.com/31240237/196659841-e42153ee-79cf-4f95-8d1d-67f492b34bd1.png)
> 
> Hello, I'm currently implementing video call related functions. It seems that you are ahead of me. I'd like to ask what you suggest for A to hang up the phone and B to automatically exit the conference room synchronously

可以通过监听会议室有多少人可能实现
![20221020162531](https://user-images.githubusercontent.com/31240237/196896791-7a1b16dd-cfa2-42ae-ba04-ab0231da85da.jpg)

**Comment by saghul** [comment]
We don't have an API for changing the camera or speaker selection. But since you modified the UI you can just invoke the functionality that ToggleCameraButton and SoundDeviceButton implement.

**Comment by PREM24JSK** [comment]
@qinvb how hou modify ui. Can you please explain. I need to customise my ui.
