### ISSUE TITLE
Feature request: Video Support for SIP Gateway

### ISSUE THREAD

**Issue by aamoyg** [jitsi/jitsi-meet#1244]
I'm running Jitsi Meet Nightly with Jigasi on Ubuntu server. I'm able to use Jigasi through the Jitsi Meet conference to call a Linphone SIP address. However, it only works for voice (though it seems that Linphone supports video).

Is video support already implemented, or is this something that can be implemented in the future?

**Comment by damencho** [comment]
Could you please use the mailinglist for questions before opening an issue.

Currently there is no video support and jigasi, and adding it would be a substantial effort adding a lot of unimplemented stuff for the video codecs in jitsi. So this is not currently in the roadmap.
