### ISSUE TITLE
Ubuntu 20.04 The following packages have unmet dependencies error

### ISSUE THREAD

**Issue by Bryantsmith20** [jitsi/jitsi-meet#12442]
I have tried to install jitsi-meet in ubuntu 20.04 using the following code 

`apt install jitsi-meet` 

But it keeps on giving me the following error even after reinstalling the OS more than 3 times

`The following packages have unmet dependencies:
 jitsi-meet : Depends: jicofo (= 1.0-940-1) but it is not going to be installed
              Depends: jitsi-meet-prosody (= 1.0.6644-1) but it is not going to be installed
              Recommends: jitsi-meet-turnserver (= 1.0.6644-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

Please I would appreciate whatever help that can be rendered for me to continue my project.
Thanks

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Follow the [quick install guide](https://jitsi.org/qi) and install the latest prosody first
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/#add-the-prosody-package-repository
