### ISSUE TITLE
initialPositionInSuperview is immutable since 5.1.0

### ISSUE THREAD

**Issue by bozek-lu** [jitsi/jitsi-meet#12446]
### Description:

Variable used for initial position of PiP in `PiPViewCoordinator` is immutable since version 5.1.0

### Steps to reproduce:

1. Use jitsi-meet ver. 5.1.0 or newer
2. See that code changing `initialPositionInSuperview` does not work

### Expected behavior:

Ability to change `initialPositionInSuperview`

### Actual behavior:

`initialPositionInSuperview` is immutable

### Client information:

- Jitsi Meet version: 6.2.1
- Operating System: MacOS 12.6

**Comment by saghul** [comment]
Ping @alexbumbu

**Comment by robertogvieira** [comment]
@alexbumbu it's a small one like [this one](https://github.com/jitsi/jitsi-meet/pull/11643), just to change a `let` to `var`  😄

**Comment by saghul** [comment]
Can you send a PR?

**Comment by robertogvieira** [comment]
> Can you send a PR?

@saghul glad you asked 😉
Here: #12619
(FYI @alexbumbu )
