### ISSUE TITLE
Option to only show myself in the side bar

### ISSUE THREAD

**Issue by mcapodici** [jitsi/jitsi-meet#12440]
In 1 to 1 conversations, I would like to be able to restrict the sidebar to only show myself, and not the other speaker.

Therefore the resulting interface would look like this:

![image](https://user-images.githubusercontent.com/3528831/197366279-2d07d768-515e-4b44-b0f1-434262ac5edc.png)

At the moment, looking at the Jitsi options, I can only hide the side bar, or hide myself, but not the other people on the call.

**Comment by saghul** [comment]
This is already the case, once the mouse stops moving and the toolbar hides.

<img width="2672" alt="Screenshot 2022-10-25 at 15 22 17" src="https://user-images.githubusercontent.com/317464/197784741-f918661e-1a1d-4ba7-8ee4-8e2f1b0c6543.png">

**Comment by mcapodici** [comment]
I don't think that has been my experience. I am using JaaS - is this the same code. Usually it shows the other person in a small window too, and they don't disappear. You can hide the entire side bar but that would also hide the view of yourself.

**Comment by damencho** [comment]
Yep, meet.jit.si and JaaS are using the same project - jitsi-meet.

> I just checked again and I think you are right! It does hide when the mouse is left alone. Is there any option to have it hidden at all times regardless of mouse?

Nope, there is no such option.

**Comment by mcapodici** [comment]
Thanks, so I guess this ticket is a request to add such an option! Based on that you can decide whether to accept or reject it. I think it would be generally useful to people to have more control over what appears in the sidebar.

**Comment by damencho** [comment]
We do not have plans for adding that at the moment. Any PRs are welcome.

**Comment by saghul** [comment]
Since this is JaaS related you can also raise this in a support ticket.
