### ISSUE TITLE
Pin to stage doesn't work in Chromium Edge

### ISSUE THREAD

**Issue by cfischer69** [jitsi/jitsi-meet#12459]
### Description:

When using MS Edge Pin To Stage causes the participant pinned to no longer display camera/

### Steps to reproduce:

1. Start a meeting
2. Verify that all participants cameras display when in tile view
3. Click on one participant's video feed, or click the three dots and click Pin to stage

### Expected behavior:

Pinned participant's camera feed to fill the entire Jitsi tab

### Actual behavior:

Pinned participant's camera feed goes black.

![image](https://user-images.githubusercontent.com/27776818/197905918-d30dd477-9da5-4e25-867f-49ef58769de3.png)

![image](https://user-images.githubusercontent.com/27776818/197905936-73e6f22d-94e1-44fd-ab52-f5e672c976c0.png)

### Server information: n/a

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: MS Edge 106.0.1370.52 (Official build) (64-bit)
- Operating System: 
- Edition	Windows 10 Pro
- Version	21H2
- OS build	19044.2130
- Experience	Windows Feature Experience Pack 120.2212.3030.0

**Comment by saghul** [comment]
We updated meet.jit.si yesterday, and I cannot reproduce this, can you please retry?
