### ISSUE TITLE
[Browser] the share screen button should be helpful when it is failing

### ISSUE THREAD

**Issue by fulldecent** [jitsi/jitsi-meet#12457]
I work in a company with 20 people.

When doing video conferences, I need to help about 15 of them figure out how to enable screensharing EVERY TIME WE USE A NEW SOFTWARE. For those people, their experience is worse—not only does it not work but they are helpless because they are not computer nerds—they are on a phone call with their boss and they are wasting time on a meeting not making a good impression.

---

# Test case

Join a meeting where, for some reason, Jitsi is not able to share your screen.

# Expected outcome

1. Jitsi takes ownership of the problem, it is not the customer's fault
2. Jitsi provides helpful advice to fix the problem
3. Jitsi makes it apparent to the customer that this advice is up-to-date and is better than trying to search YouTube or TikTok for a solution

Here is an example:

> Sorry! Jitsi is having trouble sharing your screen. Please see our guide for your computer at:
>
> jitsi.org/screen-sharing/macOS-13.0/DuckDuckGo-0.30.1

And then on that page at the top it says:

> This information was last reviewed by [Bob Stevens](jitsinews) on 2022-10-24.

And then correct, useful information follows.

P.S. Because jitsi.org is a parent domain of meet.jit.si, that means it can diagnose the problem using JavaScript. And if it can make it work in jit.si, then it should work in meet.jit.si.

P.P.S. Recognize that people might have to restart their browser for a change to take effect. Tell them about the applicable shortcut to reopen windows (different for each browser/OS) BEFORE they disappear. This will help them get back into their meeting.

# Actual outcome

In Jitsi when I join a meeting and click here it does nothing. I'm literally clicking harder on my mouse because I don't even know if I clicked right.

Jitsi knows there's a problem, and it even has some stuff in the web console.

<img width="1167" alt="Screenshot 2022-10-25 at 10 28 30" src="https://user-images.githubusercontent.com/382183/197819266-a12be425-eb2e-40b1-9126-2f34c8d1ac73.png">

---

# Discussion

I don't care about fixing this problem on my computer. Please don't provide advice on that. I'm using macOS and I manually added my browser to System Settings / Privacy / Screen Recording and restarted the browser. That didn't work. I don't care.

What I care about is that right now the easiest way to solve this problem is:

> Bob: it's not working
> Mary: hmmm, okay, do you use Google Meet?
> Bob: yes
> Mary: okay I'll send you a Google Meet link you and you worry about fixing your computer stuff later
> Bob: kthx

**Comment by saghul** [comment]
Thanks for the feedback!

This is a hard problem because it means Jitsi needs to actually know the root cause.

> I'm using macOS and I manually added my browser to System Settings / Privacy / Screen Recording and restarted the browser. That didn't work. I don't care.

This, for example is very weird. Looks like some system / browser issue. Are you able to share your screen in other tools?

**Comment by fulldecent** [comment]
Yes, works for me with the same browser in Chrome. I can make a separate issue to debug this later.

---

Yes, it's hard. Even a web page we can link to and include an EDIT THIS ON GITHUB link could be a fast start and maybe some people will help it get better.
