### ISSUE TITLE
[iOS][SDK 6.1.0] Hide Settings button from menu

### ISSUE THREAD

**Issue by andreipro1002** [jitsi/jitsi-meet#12460]
Hello,

Is it possible to hide/remove the Settings button from menu? I'm using the iOS SDK v6.1.0, and couldn't find the option in the feature flags list https://github.com/jitsi/jitsi-meet/blob/ios-sdk-6.1.0/react/features/base/flags/constants.js

If it's not possible to hide it through interface, can I get some info how to remove it from the source code? 

![Settings](https://user-images.githubusercontent.com/4287792/197905713-91cef302-f41b-4b8e-afe6-2043964b709b.png)

**Comment by saghul** [comment]
We don't have such a flag yet, but a PR would be welcome!

**Comment by iospro** [comment]
PR for this feature
https://github.com/jitsi/jitsi-meet/pull/12513
