### ISSUE TITLE
Youtube webview issue after its relased using the bash

### ISSUE THREAD

**Issue by zaki-vempower** [jitsi/jitsi-meet#12463]
### Steps to reproduce:
1. Join any room 
2. paste a yt link in the dialog

### Actual behavior:

![Screenshot_20221026-194441_Jitsi SDK test](https://user-images.githubusercontent.com/64267273/198053849-0f245124-653b-4159-81ba-8385f94132b9.jpg)
![Screenshot_20221026-200054_Jitsi SDK test](https://user-images.githubusercontent.com/64267273/198054466-22675ba4-6cec-4d4a-a59a-eae7157f8c3c.jpg)

https://user-images.githubusercontent.com/64267273/198053877-14a469e4-225d-4406-a320-d85a4e3d2339.mp4

### Server information:

- Jitsi Meet version:
- Operating System: 

### Client information:

- Browser / app version:

- Operating System:

**Comment by saghul** [comment]
Closing as this belong in the samples repo and it has been opened there.

**Comment by zaki-vempower** [comment]
> ### Description:
> ### Steps to reproduce:
> 1. Join any room
> 2. paste a yt link in the dialog
> 
> ### Expected behavior:
> ### Actual behavior:
> ![Screenshot_20221026-194441_Jitsi SDK test](https://user-images.githubusercontent.com/64267273/198053849-0f245124-653b-4159-81ba-8385f94132b9.jpg) ![Screenshot_20221026-200054_Jitsi SDK test](https://user-images.githubusercontent.com/64267273/198054466-22675ba4-6cec-4d4a-a59a-eae7157f8c3c.jpg)
> 
>  20221026_195242.mp4 
> ### Server information:
> * Jitsi Meet version:
> * Operating System:
> 
> ### Client information:
> * Browser / app version:
> * Operating System:
> 
> ### Additional information:

but I can see the recording,
btw the issue is that when a user added a youtube video to the conference (especially if its a Samsung device and if its a released version like an aar file)  the youtube video doesn't play at all and whenever I try to play it pauses it on its own .
