### ISSUE TITLE
Desktop sharing icon not shown in Firefox

### ISSUE THREAD

**Issue by dbareiro** [jitsi/jitsi-meet#1247]
Hi!

I intend to try the desktop sharing in Firefox ESR but I see that the icon is not shown. In Chromium it is shown. Can this be a bug with Firefox?

Thanks in advance.

Kind regards,
Daniel

**Comment by damencho** [comment]
Could you please ask question and post problems to the mailinglist before opening issues.

I just tested Firefox ESR on meet.jit.si and it is working fine. Maybe your deployment is not configured for firefox desktop sharing. You need to whitelist your domain in firefox, which rules I'm not familiar with and it takes several FF versions till it come to public.
The other way is deploy your own plugin on your deployment: https://github.com/jitsi/jidesha/tree/master/firefox
