### ISSUE TITLE
Screen sharing does not work in Chrome

### ISSUE THREAD

**Issue by audouts** [jitsi/jitsi-meet#12480]
### Description:

We tried screen sharing from two different Windows 10 computers. Edge and Firefox worked. Google Chrome did not.

### Steps to reproduce:

1. Install Google Chrome in Windows 10
2. Join a meeting
3. Attempt to share your screen

### Expected behavior:

Screen sharing works.

### Actual behavior:

The user trying to share sees a shared screen. Everyone else sees an empty/blank window, where resolution and frame rate are "N/A".

### Server information:

- Jitsi Meet version: stable-7882 (Docker)
- Operating System: Debian GNU/Linux 11

### Client information:

- Browser / app version: Google Chrome Version 107.0.5304.88 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by damencho** [comment]
Were you able to reproduce the same on meet.jit.si?

**Comment by damencho** [comment]
#
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by audouts** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.

Ah, of course. I should have done that. Thanks for the reminder. I'll see about repro'ing the issue on meet.jit.si.

**Comment by audouts** [comment]
Looks like meet.jit.si works, so it must be something in our configuration. Should I close this and move to the forums? I'd like to know if anyone has ideas for what we might check.

**Comment by damencho** [comment]
Maybe publish some js console logs from the browser so we can see the error.

**Comment by audouts** [comment]
@damencho 
Thanks. Here is the error:

```
2022-10-31T21:35:13.620Z [features/base/tracks] Replace video track - unmuted
BridgeChannel.js:84 WebSocket connection to 'wss://meet.private.com/colibri-ws/172.18.0.4/1fdd0747556a7cb/07a8bee7?pwd=4fhbuakg310tgmirj3g43t3t1t' failed: 
_initWebSocket @ BridgeChannel.js:84
t @ BridgeChannel.js:103
Logger.js:154 2022-10-31T21:35:14.301Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-10-31T21:35:14.301Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
e.onclose @ BridgeChannel.js:433
```

**Comment by damencho** [comment]
The websockets to your bridge are not working ... you need to fix that. Not sure what can be the problem when deploying that with docker... you can open an issue in [the docker tracker ... ](https://github.com/jitsi/docker-jitsi-meet/) ...

**Comment by audouts** [comment]
Okay. I'll try that.
