### ISSUE TITLE
How to hangup automatically if the participant is rejected while knocking.

### ISSUE THREAD

**Issue by thisisnkc** [jitsi/jitsi-meet#12510]
When the participant clicks on ask to join, Jitsi does not provide any event, command or function that allows us to automatically hang up the meeting if the participant is rejected by the moderator. He(the participant) simply gets a message that you are rejected by the moderator and remains in the meeting page which I do not want. Is there any solution for this problem.

**Comment by saghul** [comment]
Don't you get the `participantKickedOut` event on the iframe? https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events#participantkickedout

**Comment by erengms** [comment]
same issue

**Comment by thisisnkc** [comment]
@saghul, I think you do not get it. The participantKickedOut event fires when (in a room) the moderator kicks some participant when the participant is already entered in the meeting. I want an event that fires when the participant is rejected while he is knocking outside the room.(he hasn't entered the room yet).

**Comment by saghul** [comment]
Ah, gotcha. I don't think we have an event for that, but a PR adding it would be welcome!
