### ISSUE TITLE
How to record the whiteboard content by jibri?

### ISSUE THREAD

**Issue by gaocunbin** [jitsi/jitsi-meet#12519]
**Is your feature request related to a problem you are facing?**
White-board is great feature in jitsi-meet ([feat(whiteboard): add whiteboard](https://github.com/jitsi/jitsi-meet/pull/12185/files#top)
#12185), but we found that the content I drew on whiteboard can not be recorded by jibri on server.

I wonder whether it is supported or not for now.
if it is supported, Would you please share your light on this?
Thanks and wait for your reply

**Describe the solution you'd like**
is it possible to share the whiteboard content stream to jibri just like the screen share functionality

**Describe alternatives you've considered**
For now, when the white-board is opened, i have to use local recording function of jitsi to record the meeting

**Comment by saghul** [comment]
It's an unreleased feature, we are still testing it.

Looks like wiring it up to follow-me is missing. @mihhu can you PTAL?

**Comment by saghul** [comment]
It's on git yeah, but it's not on any stable release nor enable don meet.jit.si. The usual path for features is to first land on git, then get enabled on meet.jit.si, then end up in a stable release.

**Comment by ahmedusama250** [comment]
Is this issue is resolved?

**Comment by aslam-t** [comment]
Hey @saghul, was this feature got released? If not, can you point to the implementation PRs.

Thanks

**Comment by saghul** [comment]
Yes it has been released.

Just enable follow-me.
