### ISSUE TITLE
Screen Sharing is not working

### ISSUE THREAD

**Issue by KshubhamK** [jitsi/jitsi-meet#12524]
### Description:

After the recent update (24th oct 2022) screen sharing is not working. Screen get freeze for moment and camera set to disable automatically and suddenly application get crashed, it lead to rebooting device. Even back button gets hid when screen share is on. Can not access background screen or any other applications because "current screen share screen" can't move to the background. After disabling screen share, camera still set to disable mode. Tapping on camera icon its not operable. Same thing I is happing with jitsi play store application.

### Server information: Jitsi Server

- Jitsi Meet version: v5.1.0, v6.2.1, v6.2.2
- Operating System: Android SDK

**Comment by KshubhamK** [comment]
I am using jitsi server

LOG : 
W/DynamiteModule: Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
D/libMEOW: meow delete tls: 0xb4000073795da9c0
I/DynamiteModule: Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller: Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
I/JitsiMeetSDK:  JitsiConnectionService updateCall: 5208C989-08F2-4D8B-A4EF-F5FE9A338A9C hasVideo: true
I/JitsiMeetSDK: [features/base/tracks] Replace video track - unmuted
D/JitsiMeetSDK: ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK:  JitsiConnectionService updateCall: 5208C989-08F2-4D8B-A4EF-F5FE9A338A9C hasVideo: true
I/FIAM.Headless: Successfully fetched 0 messages from backend
I/OplusCameraManagerGlobal: setClientInfo, packageName: com.shubham.deb, uid: 10818, pid: 11970
I/OplusCameraManagerGlobal: setClientInfo, packageName: com.shubham.deb, uid: 10818, pid: 11970
I/OplusCameraManagerGlobal: setClientInfo, packageName: com.shubham.deb, uid: 10818, pid: 11970
I/BufferQueueProducer: [SurfaceView[com.md.alveo.dev/org.jitsi.meet.sdk.JitsiMeetActivity]#5(BLAST Consumer)5](id:2ec200000006,api:1,p:11970,c:11970) disconnect: api 1
E/BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
I/BufferQueueProducer: [SurfaceView[com.md.alveo.dev/org.jitsi.meet.sdk.JitsiMeetActivity]#5(BLAST Consumer)5](id:2ec200000006,api:0,p:-1,c:11970) disconnect: api -1
I/BLASTBufferQueue: [SurfaceView[com.md.alveo.dev/org.jitsi.meet.sdk.JitsiMeetActivity]#5] destructor()
I/BufferQueueConsumer: [SurfaceView[com.md.alveo.dev/org.jitsi.meet.sdk.JitsiMeetActivity]#5(BLAST Consumer)5](id:2ec200000006,api:0,p:-1,c:11970) disconnect
I/org.webrtc.Logging: EglRenderer: Releasing.
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
I/org.webrtc.Logging: GlShader: Deleting shader.
I/org.webrtc.Logging: EglRenderer: eglBase detach and release.
I/org.webrtc.Logging: EglRenderer: Releasing done.
I/org.webrtc.Logging: EglRenderer: Quitting render thread.
D/libMEOW: meow delete tls: 0xb4000069710af200
I/Quality: Skipped: false 1 cost 31.457384 refreshRate 0 processName com.shubham.deb
I/BLASTBufferQueue: releaseBufferCallbackThunk bufferId:51410758533161 framenumber:325 blastBufferQueue is dead
D/JitsiMeetSDK: ExternalAPI Sending event: SCREEN_SHARE_TOGGLED with data: { NativeMap: {"participantId":"d0d6f829","sharing":true} }
V/FA: Inactivity, disconnecting from the service
E/ActivityThread: Failed to find provider info for com.oplus.statistics.provider
E/OplusStatistics--: IllegalArgumentException:java.lang.IllegalArgumentException: Unknown URL content://com.oplus.statistics.provider/track_event
E/com.amplitude.api.AmplitudeClient: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/om.md.alveo.de: Cleared Reference was only reachable from finalizer (only reported once)
I/om.md.alveo.de: Background young concurrent copying GC freed 564298(21MB) AllocSpace objects, 34(876KB) LOS objects, 46% free, 25MB/48MB, paused 368us,172us total 147.560ms
W/JitsiMeetSDK: [modules/xmpp/strophe.ping.js] Ping timeout null

this log generated after screen share

**Comment by KshubhamK** [comment]
>This is expected and intentional. You can swipe up from the bottom and the navigation bar will be displayed. This is the standard behavior of immersive mode.

yes I knew about navigation button. For more reference I shared video file please check.

https://user-images.githubusercontent.com/60210710/200553615-eb6e3018-e6a1-4c32-a81b-89d06653fa8a.mp4

This recorded on jitsi latest play store application : 08 Nov 2022

**Comment by saghul** [comment]
> >This is expected and intentional. You can swipe up from the bottom and the navigation bar will be displayed. This is the standard behavior of immersive mode.
> 
> 
> 
> yes I knew about navigation button. For more reference I shared video file please check.
> 
> 
> 
> https://user-images.githubusercontent.com/60210710/200553615-eb6e3018-e6a1-4c32-a81b-89d06653fa8a.mp4
> 
> 
> 
> This recorded on jitsi latest play store application : 08 Nov 2022
> 
> Android OS : 12
> 
> Device : OnePlus Nord
> 
> Same issue is also on Oppo A16 device with android 12 Version

This looks like a bug in that Android device. We don't do anything to prevent the app from going to the background.

**Comment by KshubhamK** [comment]
>This looks like a bug in that Android device. We don't do anything to prevent the app from going to the background.

How this Bug is preventing only jitsi application and not the other? Rest other applications are working fine on both the devices
