### ISSUE TITLE
Unable to disable welcome/pre-join screen

### ISSUE THREAD

**Issue by Newsigmasoftware** [jitsi/jitsi-meet#12547]
### Description:
Basically, I want to remove the welcome screen we get before joining a call. So I used flags as per docs
 
 .setFeatureFlag("welcomepage.enabled", false)

### Expected behavior:
It shouldn't display the Join meeting page again.

### Actual behavior:
![image](https://user-images.githubusercontent.com/77768911/201288364-10090960-2f72-450d-af7c-9246a5750dbe.png)

- Jitsi Meet version: 6.2.2
- Operating System: 10+

**Comment by saghul** [comment]
That's not the welcome page. That is the prejoin page. You can disable it with `prejoinpage.enabled`.
