### ISSUE TITLE
Bluetooth Volume Issue in Samsung devices

### ISSUE THREAD

**Issue by AnuraagKotnala** [jitsi/jitsi-meet#12540]
When we start Jitsi meeting and end the conference, Bluetooth volume control stops working, i.e. the meter changes but volume doesnt change. Only restarting the device fixes issue.

Steps to reproduce - 
1) Check audio on Youtube to see volume changes.
2) Start a jitsi meeting.
3) Stop the meeting.
4) Go to Youtube again, and try changing volume.

**Comment by saghul** [comment]
You usually have multiple volume knobs, one for calls and one for media. After a call it may get stuck in the call know, but you should be able to change the media knob by hand and then it will switch to that.

This is unfortunately an Android rom bug we can do nothign about.
