### ISSUE TITLE
Drawing on Shared Screen

### ISSUE THREAD

**Issue by etma101** [jitsi/jitsi-meet#12556]
Hi, Being able to draw on shared screen would be an amazing feature because it would allow to communicate visually about the shared content. This is extra essential for graphic oriented meetings like designers, architects, planners, production teams etc.

This feature could be implemented by simply using a transparent drawing layer on top of the shared screen (drawing tools would be same as the whiteboard)

**Comment by w3rm** [comment]
+1

**Comment by FerLuisxd** [comment]
+1
