### ISSUE TITLE
prosody error log

### ISSUE THREAD

**Issue by un99known99** [jitsi/jitsi-meet#12552]
Hi,
got the following error in the /var/log/prosody/prosody.err:

Nov 11 20:35:04 jitsi.example.org:end_conference    error   No muc_component specified. No muc to operate on!

Any hint on how to fix this?

Thanks.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/blob/53ccb97d344dc0dcf605bde2e54887818bb7d554/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L131

**Comment by un99known99** [comment]
thanks for the info, ur spam filter is keeping my community post blocked:
![grafik](https://user-images.githubusercontent.com/1615207/201463426-aa500d9b-e2fe-4646-aada-5a7348129bf0.png)

**Comment by un99known99** [comment]
also not sure what u want to tell me with the link u send, required entries are in:
end_conference_component
and
muc_component = "conference.jitsi.example.com"
as well

**Comment by un99known99** [comment]
hm, might be fixed with yesterdays update?
