### ISSUE TITLE
Share System Audio Entire Screen Not Working Windows 10 Chrome Browser

### ISSUE THREAD

**Issue by captroper** [jitsi/jitsi-meet#12553]
Expected Behavior: Toggling the "Share System Audio" button in the share screen menu shares both the screen video and audio. 

Actual Behavior: NEITHER the video nor the audio get shared. Nothing appears to happen. 

Steps to reproduce: 

1) Click toggle screenshare
2) Select Screen under entire screen
3) Toggle Share System Audio button
4) Click Share

Running up to date chrome browser on windows 10, using a meet.jit.si link. Sharing a screen WITHOUT toggling the share system audio button works as expected. Sharing a chrome tab with audio also works as expected.

**Comment by damencho** [comment]
Can you try reproducing it here: https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/ ? Does it work there?

**Comment by captroper** [comment]
It does not. It produces the following error: "getDisplayMedia error: NotReadableError"

**Comment by damencho** [comment]
Do you see the same error in the js console in the browser on meet.jit.si? 
I suspect this is a permissions issue or a browser bug and there is nothing we can do about it.

**Comment by captroper** [comment]
Here's the error that I see there: 

Logger.js:154 2022-11-11T23:35:26.614Z [modules/RTC/ScreenObtainer.js] getDisplayMedia error {video: {…}, audio: true, cursor: 'always'} {errorName: 'NotReadableError', errorMsg: 'Could not start audio source', errorStack: undefined}

Logger.js:154 2022-11-11T23:35:26.615Z [features/base/tracks] Failed to create local tracks ['desktop'] Ht {name: 'gum.screensharing_user_canceled', message: 'User canceled screen sharing prompt', stack: 'Error\n    at new Ht (https://web-cdn.jitsi.net/mee…2/libs/lib-jitsi-meet.min.js?v=6776.3542:2:158842'}

Logger.js:154 2022-11-11T23:35:26.616Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: User canceled screen sharing prompt Script: null Line: null Column: null StackTrace:  Error
    at new Ht (https://web-cdn.jitsi.net/meetjitsi_6776.3542/libs/lib-jitsi-meet.min.js?v=6776.3542:2:17001)
    at https://web-cdn.jitsi.net/meetjitsi_6776.3542/libs/lib-jitsi-meet.min.js?v=6776.3542:2:158842

Uncaught (in promise) Ht {name: 'gum.screensharing_user_canceled', message: 'User canceled screen sharing prompt', stack: 'Error\n    at new Ht (https://web-cdn.jitsi.net/mee…2/libs/lib-jitsi-meet.min.js?v=6776.3542:2:158842'}

**Comment by damencho** [comment]
Yep, its either the browser does not have permissions to record audio from the system or something like that, or there is some bug in the browser. If you think its the second one you can report it with the link I provided to the chromium bug tracker.
