### ISSUE TITLE
Change polling feature to allow only one vote per participant

### ISSUE THREAD

**Issue by paulg10me** [jitsi/jitsi-meet#12572]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
I have a team who would like to use the polling feature to vote. Problems arise because while any participant can make one vote and their response is recorded, they can also opt to change their vote, and when making a change they are able to leave their initial selection and choose another response option. This causes skewed and therefore unreliable results.

**Describe the solution you'd like**
Please describe the desired behavior.
An example - 
Participant A makes a poll question - What colour is the sky?
Answer options - Blue, Green, Red
Voting -
Participant A responds "Blue"
Participant B responde "Green"
Participant B changes their response and checks the "Blue" answer, but does not remove the check from their original answer of "Green"

Results -
The results will show 2 votes for Blue and one vote for Green.
Participant B has voted twice!

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Currently there appears to be no way to control this behaviour, and the "double voting" error can occur.
Instead of checkboxes the voting options should behave like radio buttons where only one response is allowed. Changes can still be allowed while polling is open, but if a participant makes a change their first selection must be eliminated.

**Comment by saghul** [comment]
That would mean there is no way to have multiple choice options.

For now we chose to make the polling feature more generic / flexible which means it does have this shortcoming. It's a compromise we are comfortable with.

**Comment by saghul** [comment]
We disagree on that front, sorry.

**Comment by lionep** [comment]
Hi, is there something on the roadmap like adding the option to choose the type of answers (checkbox vs radio) in polls ?

**Comment by saghul** [comment]
No, there isn't.
