### ISSUE TITLE
Everbody follows me doesn't work when a user is sharing the screen

### ISSUE THREAD

**Issue by luisvillagraies** [jitsi/jitsi-meet#12576]
### Description:

The "everbody follows me" option works excellent when anybody is sharing the screen. For example, when a moderator who has the option selected pin the screen on a participant, everybody follows the target.
The issue occurs when a user shares the screen; because everyone sees only the shared screen and the moderator can select other users to pin to the screen but the participants continues seeing the shared screen.
When the user stops sharing the screen, everything works normal again. Everyone follows the moderator.

### Steps to reproduce:

1. A moderator checks  "everybody follows me" option
2. A user shares the screen
3. The moderator pins a user to the screen but everyone still seeing the shared screen

### Expected behavior:

When the moderator pins a user, everyone will see the pinned user until the moderator selects another user or the shared screen.

### Actual behavior:

When the moderator pins a user, the shared screen will be the one visible for everyone

### Server information:

- Jitsi Meet version: 2.0.8044
- Operating System: Debian 11 and Docker version

### Client information:

- Browser / app version: Every Browser
- Operating System: Windows, Linux, MacOS

### Additional information:

We also tried in jitsi meet and 8x8, and we got the same results.

**Comment by saghul** [comment]
Hum, nice catch of a corner case :-)

When a user shares their screen that will be pinned, so the action the moderator took is discarded...

**Comment by SatyarajRana** [comment]
@saghul , may i work on this issue?

**Comment by saghul** [comment]
You may, of course! Please note that many of us are hoping to catch a break now so there might not be anyone that can provide guidance around.
