### ISSUE TITLE
AppCompat Theme conflict problem

### ISSUE THREAD

**Issue by Sarim-Sohail** [jitsi/jitsi-meet#12588]
### Description:

I'm making a video conferencing type feature for an app.
When running the create meeting function using jitsi, the app crashes to the phones home screen and throws the following error: 

D/AndroidRuntime(17678): Shutting down VM
E/AndroidRuntime(17678): FATAL EXCEPTION: main
E/AndroidRuntime(17678): Process: com.example.tutor_me, PID: 17678
E/AndroidRuntime(17678): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tutor_me/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

I have attempted to add '@style/Theme.AppCompat' + variants to my Manifest file, alongside adding it as parent in styles xml to no avail, the error simply doesn't go away.

### Steps to reproduce:

In terminal:
flutter run
Click on Meetings
Click on New Meeting

### Expected behavior:

The application should start a new meeting

### Actual behavior:

The application crashes to the phones home page

### Server information:

- Jitsi Meet version: 4.0.0
- Operating System: Windows 10 

### Additional information: 

I attempted to configure the sdk using it's requirements, however the difference in gradle dependency versions causes other errors that doesnt even let the app run, so this is the best compromise version so far.

Adding these in build gradle causes another error, which is about app not being able to be found:
minifyEnabled true
useProguard true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro

Here's the entire error for what I mentioned in the first paragraph/detailed information:

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:62671/ieB9a4ds1yY=/ws
E/SurfaceSyncer(17678): Failed to find sync for id=0
W/Parcel  (17678): Expecting binder but got null!
D/EGL_emulation(17678): app_time_stats: avg=6460.26ms min=148.00ms max=18703.68ms count=3
D/JITSI_MEET_PLUGIN(17678): method: joinMeeting
D/JITSI_MEET_PLUGIN(17678): arguments: {videoMuted=true, subject=Meeting, iosAppBarRGBAColor=null, serverURL=null, audioOnly=null, audioMuted=true, userDisplayName=testuser, userEmail=randomemail@gmail.com, room=17662726, token=null, featureFlags={}}
D/JITSI_MEET_PLUGIN(17678): Joining Room: 17662726
D/JITSI_MEET_PLUGIN(17678): Server URL: https://meet.jit.si, https://meet.jit.si
D/EGL_emulation(17678): app_time_stats: avg=666.74ms min=24.63ms max=1308.85ms count=2
D/AndroidRuntime(17678): Shutting down VM
E/AndroidRuntime(17678): FATAL EXCEPTION: main
E/AndroidRuntime(17678): Process: com.example.tutor_me, PID: 17678
E/AndroidRuntime(17678): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tutor_me/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(17678): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/AndroidRuntime(17678): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime(17678): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(17678): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17678): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17678): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(17678): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17678): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17678): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17678): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(17678): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(17678): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
E/AndroidRuntime(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
E/AndroidRuntime(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
E/AndroidRuntime(17678): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/AndroidRuntime(17678): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:81)
E/AndroidRuntime(17678): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/AndroidRuntime(17678): 	at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime(17678): 	at android.app.Activity.performCreate(Activity.java:8269)
E/AndroidRuntime(17678): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime(17678): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/AndroidRuntime(17678): 	... 12 more
E/JitsiMeetSDK(17678): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(17678): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tutor_me/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/JitsiMeetSDK(17678): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/JitsiMeetSDK(17678): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(17678): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/JitsiMeetSDK(17678): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(17678): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(17678): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/JitsiMeetSDK(17678): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(17678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(17678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(17678): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(17678): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:81)
E/JitsiMeetSDK(17678): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(17678): 	at android.app.Activity.performCreate(Activity.java:8290)
E/JitsiMeetSDK(17678): 	at android.app.Activity.performCreate(Activity.java:8269)
E/JitsiMeetSDK(17678): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/JitsiMeetSDK(17678): 	... 12 more
E/JitsiMeetSDK(17678):
E/JitsiMeetSDK(17678): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tutor_me/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/JitsiMeetSDK(17678): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/JitsiMeetSDK(17678): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(17678): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/JitsiMeetSDK(17678): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(17678): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(17678): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/JitsiMeetSDK(17678): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(17678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(17678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(17678): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
E/JitsiMeetSDK(17678): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(17678): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:81)
E/JitsiMeetSDK(17678): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(17678): 	at android.app.Activity.performCreate(Activity.java:8290)
E/JitsiMeetSDK(17678): 	at android.app.Activity.performCreate(Activity.java:8269)
E/JitsiMeetSDK(17678): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/JitsiMeetSDK(17678): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/JitsiMeetSDK(17678): 	... 12 more
I/Process (17678): Sending signal. PID: 17678 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by saghul** [comment]
SDK 4 is too old for us to look at. Please update.

**Comment by Sarim-Sohail** [comment]
I am currently using flutter and https://pub.dev/packages/jitsi_meet and using flutter pub get to get jitsi meet, so I removed the following lines from my pubspec.yaml

  jitsi_meet: ^4.0.0
  jitsi_meet_wrapper: ^0.0.5
  
  and downloaded the code from https://github.com/jitsi/jitsi-meet/releases/tag/android-sdk-6.2.2
  and then added it to my pubspec.yaml after extracting it to desktop by writing this

jitsi_meet:    
    path: C:/Users/myname/Desktop/jitsi-meet-android-sdk-6.2.2

however, I face another issue as it says there is no pubspec.yaml
	
	message: "The directory 'C:/Users/myname/Desktop/jitsi-meet-android-sdk-6.2.2' doesn't contain a pubspec.\nTry creating a pubspec in the referenced directory or using a path that has a pubspec.",

I have no experience creating pubspecs, am I doing something incorrectly to face this kind of error? I tried using git in pubspec yaml and pointing to that release, but it threw the same error at one point or failed to find the repository

**Comment by saghul** [comment]
I have no idea either, sorry. We don't maintain our he Flutter plugin. I'd suggest you ask the plugin maintainers.
