### ISSUE TITLE
Android Samsung Galaxy Z Flip Bottom options issue

### ISSUE THREAD

**Issue by mukulkumar1703** [jitsi/jitsi-meet#12582]
### Description:
Android Samsung Galaxy Z Flip Bottom options issue. please suggest how to resolve following issue

![IMG_2817](https://user-images.githubusercontent.com/51224745/202704398-ad93cdd2-8c79-417e-96cf-a5e53b2d6898.jpeg)

**Comment by saghul** [comment]
What exactly is the issue?

**Comment by mukulkumar1703** [comment]
The following issue only getting for flip Devices showing white space not showing bottom options

**Comment by saghul** [comment]
Does the same happen in the stock Jitsi Meet app? That UI looks modified.

**Comment by mukulkumar1703** [comment]
Yes getting the same issue with jitsi meet app. I added one button above jitsiview but it's working fine on all devices only getting issues in the flip device please check and let us know how to resolve the following issue.

**Comment by saghul** [comment]
Please share a screenshot using Jitsi Meet, I cannot help you with your changes until we know how it behaves with the stock app.

**Comment by janitorku** [comment]
I found no UI issue from samsung galaxy flip 4, both web and android app version accesing meet.jit.si

**Comment by saghul** [comment]
Again, screenshots please.

**Comment by janitorku** [comment]
![flipz](https://user-images.githubusercontent.com/61498019/202835289-d108c4b2-983b-401a-916f-4edf45294ab9.jpg)

**Comment by janitorku** [comment]
![flipz](https://user-images.githubusercontent.com/61498019/202835473-5f25faad-f90a-42f7-82cd-0c22ac791b6d.jpg)
![flipz2](https://user-images.githubusercontent.com/61498019/202835477-2072e077-b38a-47bb-812f-a76161771e99.jpg)

**Comment by saghul** [comment]
What is the problem?

**Comment by mukulkumar1703** [comment]
I resolved the above-shared issue
filmstrip.enabled: Flag indicating if the filmstrip should be enabled
Needs to add the following property in the featured list after that able to see bottom sections.
