### ISSUE TITLE
feature request: visible shortcut keys

### ISSUE THREAD

**Issue by edmundlaugasson** [jitsi/jitsi-meet#1258]
Please make visible shortcut keys. They were former times visible when moved mouse over a button. But not anymore. Even better - small table with current shortcut keys under settings would be appreciated. If possible, also customisable shortcuts would be appreciated.

**Comment by damencho** [comment]
Could you please ask questions on the mailinglist before opening issues. 

If you enter in a room and press Shift + ? it will show you all available shortcuts. Currently customizing shortcuts is not possible.
