### ISSUE TITLE
Registering custom intent to support joining self-hosted setups

### ISSUE THREAD

**Issue by msva** [jitsi/jitsi-meet#12587]
**Is your feature request related to a problem you are facing?**

For now, default Jitsi Meet application from mobile appstores (for example, android's), only supports `https://meet.jit.si` links, and it is not possible to make user-transparent way to open link to custom self-hosted Meet installation in application (and not in brower), and many people just fork and build android (don't know about ios) app on their own with their domains.

**Describe the solution you'd like**

I think, it would be nice to register custom intent (again, I speak on how it is in Android, and don't know iOS details), so, **at least**, when user opens link to selfhosted meet in browser, it would be possible to redirect user to the application, with selectedspecified server and room.

**Describe alternatives you've considered**

Another way, I think, is to just support all "https" links in application, so it would be possible to set it as "open with" on the link-opening dialog, but I think it is bad way.

**Comment by saghul** [comment]
You can already use Intent links pointing to any domain: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe/#opening-meetings-in-the-jitsi-meet-app
