### ISSUE TITLE
ReferenceError in ReactNativeJS after updated SDK

### ISSUE THREAD

**Issue by JoeyAndroidDev** [jitsi/jitsi-meet#12608]
### Description:

I use an own jitsi server and the configured SDK in my Android Project.
A few days ago I had to update the sdk because of the webRTC-Version, that was rejected from Google Play. After the update I made the same configurations as in the version before.
But now I receive following error:

ReferenceError: Can't find variable: buttonStyles     This error is located at:
                                                                                                        in Unknown
                                                                                                        in T
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in P
                                                                                                        in w
                                                                                                        in Unknown
                                                                                                        in T
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in A
                                                                                                        in Unknown
                                                                                                        in PanGestureHandler
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in A
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in G
                                                                                                        in Unknown
                                                                                                        in RNSScreen
                                                                                                        in A
                                                                                                        in Unknown
                                                                                                        in U
                                                                                                        in k
                                                                                                        in Unknown
                                                                                                        in RNSScreenContainer
                                                                                                        in ScreenContainer
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in w
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in y
                                                                                                        in GestureHandlerRootView
                                                                                                        in Unknown
                                                                                                        in w
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in E
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in A
                                                                                                        in Unknown
                                                                                                        in PanGestureHandler
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in A
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in G
                                                                                                        in Unknown
                                                                                                        in RNSScreen
                                                                                                        in A
                                                                                                        in Unknown
                                                                                                        in U
                                                                                                        in k
                                                                                                        in Unknown
                                                                                                        in RNSScreenContainer
                                                                                                        in ScreenContainer
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in w
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in y
                                                                                                        in GestureHandlerRootView
                                                                                                        in Unknown
                                                                                                        in w
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in T
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Unknown
                                                                                                        in RNCSafeAreaProvider
                                                                                                        in Unknown
                                                                                                        in c
                                                                                                        in Unknown
                                                                                                        in A
                                                                                                        in c
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in Portal.Host
                                                                                                        in s
                                                                                                        in Unknown
                                                                                                        in h
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in RCTView
                                                                                                        in Unknown
                                                                                                        in b

The error results in an black full screen on my Android device. I got in the screen, where I can choose my displayname and "Join conference". But when I click on the Join-Button, the screen turns only black. I see in the logs, that the device joined the conference and the other user can see the participant, but without camera or sound. 
Are there any other changes I have to do with the new SDK version?

By the way the same is happening when I try it with the meet.jit.si server. The Android screen stays black.

Hope the community can help

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by JoeyAndroidDev** [comment]
5.1.0

**Comment by JoeyAndroidDev** [comment]
Got the source of the error, in the version before we changed avatar images and buttons, and the new version seems to have problems with our custom changes.
I will try to set own JitsiMeetUserInfo Object and setConfigOverride, if this will work, we can use the normal sdk 5.1.0

**Comment by JoeyAndroidDev** [comment]
> That is not an SDK version.
> 
> Please use a released SDK version, the latest is 6.2.2.

Sorry, looked wrong, sdk was newest, loaded it a few days ago
