### ISSUE TITLE
Disabling the Settings Feature Flag not working

### ISSUE THREAD

**Issue by mehul4795** [jitsi/jitsi-meet#12601]
### Description:
While using the Jitsi Meet SDK in an Android app, I am trying to disable the Settings options using the code below.

`.setFeatureFlag("settings.enabled", false)`

### Steps to reproduce:

1.  Add the above code while setting the default conference options.
2.  Start the meeting and click on the overflow icon.

### Expected behavior:
The Settings options should be hidden in the Bottom Sheet.

### Actual behavior:
The Settings option is still present in the Bottom Sheet.

![Screenshot_20221122-153448_Meetly_2](https://user-images.githubusercontent.com/13131390/203288886-0df632f7-a861-4293-83aa-e1c7fca3bd00.png)

### Server information:

- Jitsi Meet SDK version: 6.2.2
- Operating System: Android

**Comment by saghul** [comment]
THis feature has landed recently (https://github.com/jitsi/jitsi-meet/commit/c32866f6a2bb6b6104bb6a4b40330d7880b56fe7) and it's not yet part of any released SDK version.

**Comment by mehul4795** [comment]
Thanks for the clarification. I Hope, it gets added to the SDK soon.

**Comment by miracuves** [comment]
I am also waiting for this to be fixed !!

**Comment by mehul4795** [comment]
It's already fixed in the latest SDK.
