### ISSUE TITLE
Support for Android 13 Material You

### ISSUE THREAD

**Issue by mdebus** [jitsi/jitsi-meet#12627]
Please implement an adaptive monochromatic app icon.

**Comment by saghul** [comment]
We do have an adaptive icon: https://github.com/jitsi/jitsi-meet/blob/f42772ec5bcc87ff6de17423d36df9bcad6e770d/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L3

Is there anything else that needs to be done?

**Comment by saghul** [comment]
Ah, looks like we're missing the monochromatic icon: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by mdebus** [comment]
Exactly, I meant the themable monochromatic icon. Updated title

**Comment by naren951** [comment]
This issue can be closed @saghul @tmoldovan8x8
