### ISSUE TITLE
Is that possible to Annotate over the camera screen

### ISSUE THREAD

**Issue by itsankitjha** [jitsi/jitsi-meet#12621]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
No, sorry, it's not possible.

**Comment by itsankitjha** [comment]
Thanks for you quick response Sir,
Is that functionality not be possible in Jitsi itself  or webRTC does not have support for this?
Can you please explain me why this can't be possible?

**Comment by saghul** [comment]
WebRTC just allows to send media streams. This functionality would need to be developed. We currently have no plans to do this.
