### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by pangsgithub** [jitsi/jitsi-meet#12637]
NODE_OPTIONS=--max-old-space-size=8192 \
        ./node_modules/.bin/webpack
[BABEL] Note: The code generator has deoptimised the styling of /Users/xuexiapang/jitsi-meet/node_modules/@vladmandic/human/dist/human.esm.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/xuexiapang/jitsi-meet/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/xuexiapang/jitsi-meet/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/xuexiapang/jitsi-meet/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/xuexiapang/jitsi-meet/node_modules/@jitsi/excalidraw/dist/excalidraw.production.min.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/xuexiapang/jitsi-meet/node_modules/zxcvbn/lib/frequency_lists.js as it exceeds the max of 500KB.
asset app.bundle.min.js 4.73 MiB [emitted] [minimized] (name: app.bundle) 2 related assets
orphan modules 6.47 MiB [orphan] 2561 modules
runtime modules 2.87 KiB 9 modules
cacheable modules 10.6 MiB
  modules by path ./node_modules/ 5.06 MiB
    javascript modules 5 MiB 347 modules
    json modules 57.4 KiB
      modules by path ./node_modules/@giphy/ 2.66 KiB 2 modules
      2 modules
  modules by path ./react/features/ 60.3 KiB
    modules by path ./react/features/base/ 42 bytes 3 modules
    modules by path ./react/features/stream-effects/ 57.9 KiB 2 modules
    ./react/features/screenshot-capture/createImageBitmap.js 705 bytes [built] [code generated]
    ./react/features/face-landmarks/createImageBitmap.ts 1.68 KiB [built] [code generated]
    ./react/features/invite/components/callee-info/styles.web.js 1 bytes [built] [code generated]

WARNING in ./node_modules/@atlaskit/button/dist/esm/shared/button-base.js 80:17-28
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/button/dist/esm/custom-theme-button/custom-theme-button.js 42:0-47 217:46-56
 @ ./node_modules/@atlaskit/button/dist/esm/custom-theme-button/index.js 1:0-48 1:0-48
 @ ./node_modules/@atlaskit/button/dist/esm/entry-points/custom-theme-button.js 1:0-56 1:0-56 1:0-56
 @ ./node_modules/@atlaskit/flag/dist/esm/flag-actions.js 36:0-58 65:25-31
 @ ./node_modules/@atlaskit/flag/dist/esm/flag.js 104:0-37 260:25-32
 @ ./node_modules/@atlaskit/flag/dist/esm/index.js 1:0-33 1:0-33
 @ ./react/features/notifications/components/web/Notification.js 1:0-34 49:44-48
 @ ./react/features/notifications/components/web/index.js 1:0-57 1:0-57
 @ ./react/features/notifications/components/index.web.js 1:0-22 1:0-22
 @ ./react/features/notifications/index.js 3:0-29 3:0-29
 @ ./conference.js 34:0-208 253:29-45 256:13-44 599:25-41 602:9-39 805:11-44 1814:27-43 1817:11-42 1822:25-41 1822:42-77 1826:25-48 1829:13-48 1830:9-41
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/button/dist/esm/shared/button-base.js 81:20-34
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/button/dist/esm/custom-theme-button/custom-theme-button.js 42:0-47 217:46-56
 @ ./node_modules/@atlaskit/button/dist/esm/custom-theme-button/index.js 1:0-48 1:0-48
 @ ./node_modules/@atlaskit/button/dist/esm/entry-points/custom-theme-button.js 1:0-56 1:0-56 1:0-56
 @ ./node_modules/@atlaskit/flag/dist/esm/flag-actions.js 36:0-58 65:25-31
 @ ./node_modules/@atlaskit/flag/dist/esm/flag.js 104:0-37 260:25-32
 @ ./node_modules/@atlaskit/flag/dist/esm/index.js 1:0-33 1:0-33
 @ ./react/features/notifications/components/web/Notification.js 1:0-34 49:44-48
 @ ./react/features/notifications/components/web/index.js 1:0-57 1:0-57
 @ ./react/features/notifications/components/index.web.js 1:0-22 1:0-22
 @ ./react/features/notifications/index.js 3:0-29 3:0-29
 @ ./conference.js 34:0-208 253:29-45 256:13-44 599:25-41 602:9-39 805:11-44 1814:27-43 1817:11-42 1822:25-41 1822:42-77 1826:25-48 1829:13-48 1830:9-41
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/flag/dist/esm/auto-dismiss-flag.js 28:17-28
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/flag/dist/esm/index.js 2:0-65 2:0-65
 @ ./react/features/notifications/components/web/Notification.js 1:0-34 49:44-48
 @ ./react/features/notifications/components/web/index.js 1:0-57 1:0-57
 @ ./react/features/notifications/components/index.web.js 1:0-22 1:0-22
 @ ./react/features/notifications/index.js 3:0-29 3:0-29
 @ ./conference.js 34:0-208 253:29-45 256:13-44 599:25-41 602:9-39 805:11-44 1814:27-43 1817:11-42 1822:25-41 1822:42-77 1826:25-48 1829:13-48 1830:9-41
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/flag/dist/esm/auto-dismiss-flag.js 29:20-34
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/flag/dist/esm/index.js 2:0-65 2:0-65
 @ ./react/features/notifications/components/web/Notification.js 1:0-34 49:44-48
 @ ./react/features/notifications/components/web/index.js 1:0-57 1:0-57
 @ ./react/features/notifications/components/index.web.js 1:0-22 1:0-22
 @ ./react/features/notifications/index.js 3:0-29 3:0-29
 @ ./conference.js 34:0-208 253:29-45 256:13-44 599:25-41 602:9-39 805:11-44 1814:27-43 1817:11-42 1822:25-41 1822:42-77 1826:25-48 1829:13-48 1830:9-41
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/flag/dist/esm/flag.js 111:15-26
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/flag/dist/esm/index.js 1:0-33 1:0-33
 @ ./react/features/notifications/components/web/Notification.js 1:0-34 49:44-48
 @ ./react/features/notifications/components/web/index.js 1:0-57 1:0-57
 @ ./react/features/notifications/components/index.web.js 1:0-22 1:0-22
 @ ./react/features/notifications/index.js 3:0-29 3:0-29
 @ ./conference.js 34:0-208 253:29-45 256:13-44 599:25-41 602:9-39 805:11-44 1814:27-43 1817:11-42 1822:25-41 1822:42-77 1826:25-48 1829:13-48 1830:9-41
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/flag/dist/esm/flag.js 112:18-32
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/flag/dist/esm/index.js 1:0-33 1:0-33
 @ ./react/features/notifications/components/web/Notification.js 1:0-34 49:44-48
 @ ./react/features/notifications/components/web/index.js 1:0-57 1:0-57
 @ ./react/features/notifications/components/index.web.js 1:0-22 1:0-22
 @ ./react/features/notifications/index.js 3:0-29 3:0-29
 @ ./conference.js 34:0-208 253:29-45 256:13-44 599:25-41 602:9-39 805:11-44 1814:27-43 1817:11-42 1822:25-41 1822:42-77 1826:25-48 1829:13-48 1830:9-41
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/inline-dialog/dist/esm/InlineDialog/index.js 195:15-26
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/inline-dialog/dist/esm/index.js 1:0-41 1:0-41
 @ ./react/features/base/react/components/web/MultiSelectAutocomplete.js 1:0-53 162:44-58
 @ ./react/features/base/react/components/web/index.js 7:0-79 7:0-79
 @ ./react/features/base/react/components/_.web.js 1:0-22 1:0-22
 @ ./react/features/base/react/components/index.js 1:0-20 1:0-20
 @ ./react/features/base/react/index.js 1:0-29 1:0-29
 @ ./react/index.web.js 6:0-49 10:11-22
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/inline-dialog/dist/esm/InlineDialog/index.js 196:18-32
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/inline-dialog/dist/esm/index.js 1:0-41 1:0-41
 @ ./react/features/base/react/components/web/MultiSelectAutocomplete.js 1:0-53 162:44-58
 @ ./react/features/base/react/components/web/index.js 7:0-79 7:0-79
 @ ./react/features/base/react/components/_.web.js 1:0-22 1:0-22
 @ ./react/features/base/react/components/index.js 1:0-20 1:0-20
 @ ./react/features/base/react/index.js 1:0-29 1:0-29
 @ ./react/index.web.js 6:0-49 10:11-22
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/inline-dialog/dist/esm/InlineDialog/index.js 203:19-30
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/inline-dialog/dist/esm/index.js 1:0-41 1:0-41
 @ ./react/features/base/react/components/web/MultiSelectAutocomplete.js 1:0-53 162:44-58
 @ ./react/features/base/react/components/web/index.js 7:0-79 7:0-79
 @ ./react/features/base/react/components/_.web.js 1:0-22 1:0-22
 @ ./react/features/base/react/components/index.js 1:0-20 1:0-20
 @ ./react/features/base/react/index.js 1:0-29 1:0-29
 @ ./react/index.web.js 6:0-49 10:11-22
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/inline-dialog/dist/esm/InlineDialog/index.js 204:22-36
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/inline-dialog/dist/esm/index.js 1:0-41 1:0-41
 @ ./react/features/base/react/components/web/MultiSelectAutocomplete.js 1:0-53 162:44-58
 @ ./react/features/base/react/components/web/index.js 7:0-79 7:0-79
 @ ./react/features/base/react/components/_.web.js 1:0-22 1:0-22
 @ ./react/features/base/react/components/index.js 1:0-20 1:0-20
 @ ./react/features/base/react/index.js 1:0-29 1:0-29
 @ ./react/index.web.js 6:0-49 10:11-22
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/modal-dialog/dist/esm/components/Modal.js 228:15-26
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/components/ModalWrapper.js 45:0-28 93:50-55
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/index.js 1:0-52 1:0-52
 @ ./react/features/base/ui/components/web/DialogContainer.tsx 1:0-57 30:139-154
 @ ./react/features/app/components/App.web.js 5:0-75 39:40-55
 @ ./react/features/app/components/index.js 1:0-22 1:0-22
 @ ./react/index.web.js 4:0-48 39:7-10
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/modal-dialog/dist/esm/components/Modal.js 229:18-32
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/components/ModalWrapper.js 45:0-28 93:50-55
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/index.js 1:0-52 1:0-52
 @ ./react/features/base/ui/components/web/DialogContainer.tsx 1:0-57 30:139-154
 @ ./react/features/app/components/App.web.js 5:0-75 39:40-55
 @ ./react/features/app/components/index.js 1:0-22 1:0-22
 @ ./react/index.web.js 4:0-48 39:7-10
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/modal-dialog/dist/esm/components/Modal.js 236:19-30
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/components/ModalWrapper.js 45:0-28 93:50-55
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/index.js 1:0-52 1:0-52
 @ ./react/features/base/ui/components/web/DialogContainer.tsx 1:0-57 30:139-154
 @ ./react/features/app/components/App.web.js 5:0-75 39:40-55
 @ ./react/features/app/components/index.js 1:0-22 1:0-22
 @ ./react/index.web.js 4:0-48 39:7-10
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/modal-dialog/dist/esm/components/Modal.js 237:22-36
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/components/ModalWrapper.js 45:0-28 93:50-55
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/index.js 1:0-52 1:0-52
 @ ./react/features/base/ui/components/web/DialogContainer.tsx 1:0-57 30:139-154
 @ ./react/features/app/components/App.web.js 5:0-75 39:40-55
 @ ./react/features/app/components/index.js 1:0-22 1:0-22
 @ ./react/index.web.js 4:0-48 39:7-10
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/modal-dialog/dist/esm/components/Positioner.js 15:24-39
export 'PositionerFixed' (imported as 'PositionerFixed') was not found in '../styled/Modal' (possible exports: Dialog, FillScreen, PositionerAbsolute, PositionerRelative, dialogHeight, dialogWidth)
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/components/Modal.js 52:0-38 171:45-55
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/components/ModalWrapper.js 45:0-28 93:50-55
 @ ./node_modules/@atlaskit/modal-dialog/dist/esm/index.js 1:0-52 1:0-52
 @ ./react/features/base/ui/components/web/DialogContainer.tsx 1:0-57 30:139-154
 @ ./react/features/app/components/App.web.js 5:0-75 39:40-55
 @ ./react/features/app/components/index.js 1:0-22 1:0-22
 @ ./react/index.web.js 4:0-48 39:7-10
 @ ./app.js 53:0-17

WARNING in ./node_modules/@atlaskit/tabs/dist/esm/components/Tabs.js 236:15-26
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/tabs/dist/esm/index.js 1:0-44 1:0-44
 @ ./react/features/desktop-picker/components/DesktopPicker.tsx 1:0-34 248:36-40
 @ ./react/features/desktop-picker/components/index.js 1:0-59 1:0-59
 @ ./react/features/desktop-picker/index.js 2:0-29 2:0-29
 @ ./conference.js 29:0-68 79:23-40
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/tabs/dist/esm/components/Tabs.js 237:18-32
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/tabs/dist/esm/index.js 1:0-44 1:0-44
 @ ./react/features/desktop-picker/components/DesktopPicker.tsx 1:0-34 248:36-40
 @ ./react/features/desktop-picker/components/index.js 1:0-59 1:0-59
 @ ./react/features/desktop-picker/index.js 2:0-29 2:0-29
 @ ./conference.js 29:0-68 79:23-40
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/tabs/dist/esm/components/Tabs.js 244:19-30
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/tabs/dist/esm/index.js 1:0-44 1:0-44
 @ ./react/features/desktop-picker/components/DesktopPicker.tsx 1:0-34 248:36-40
 @ ./react/features/desktop-picker/components/index.js 1:0-59 1:0-59
 @ ./react/features/desktop-picker/index.js 2:0-29 2:0-29
 @ ./conference.js 29:0-68 79:23-40
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/tabs/dist/esm/components/Tabs.js 245:22-36
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/tabs/dist/esm/index.js 1:0-44 1:0-44
 @ ./react/features/desktop-picker/components/DesktopPicker.tsx 1:0-34 248:36-40
 @ ./react/features/desktop-picker/components/index.js 1:0-59 1:0-59
 @ ./react/features/desktop-picker/index.js 2:0-29 2:0-29
 @ ./conference.js 29:0-68 79:23-40
 @ ./app.js 13:0-38 28:2-12

WARNING in ./node_modules/@atlaskit/tooltip/dist/esm/Tooltip.js 55:15-26
Should not import the named export 'name' (imported as 'packageName') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/tooltip/dist/esm/index.js 1:0-36 1:0-36
 @ ./react/features/base/tooltip/components/TooltipWrapper.js 1:0-40 21:42-49
 @ ./react/features/base/tooltip/components/index.js 1:0-54 1:0-54
 @ ./react/features/base/tooltip/index.js 1:0-29 1:0-29
 @ ./react/features/virtual-background/components/VirtualBackgroundDialog.tsx 26:0-45 380:36-43 384:36-43 388:36-43 392:58-65
 @ ./modules/API/API.js 48:0-113 704:38-61
 @ ./modules/API/index.js 1:0-29 2:0-31
 @ ./app.js 14:0-32 27:2-5

WARNING in ./node_modules/@atlaskit/tooltip/dist/esm/Tooltip.js 56:18-32
Should not import the named export 'version' (imported as 'packageVersion') from default-exporting module (only default export is available soon)
 @ ./node_modules/@atlaskit/tooltip/dist/esm/index.js 1:0-36 1:0-36
 @ ./react/features/base/tooltip/components/TooltipWrapper.js 1:0-40 21:42-49
 @ ./react/features/base/tooltip/components/index.js 1:0-54 1:0-54
 @ ./react/features/base/tooltip/index.js 1:0-29 1:0-29
 @ ./react/features/virtual-background/components/VirtualBackgroundDialog.tsx 26:0-45 380:36-43 384:36-43 388:36-43 392:58-65
 @ ./modules/API/API.js 48:0-113 704:38-61
 @ ./modules/API/index.js 1:0-29 2:0-31
 @ ./app.js 14:0-32 27:2-5

webpack 5.57.1 compiled with 21 warnings in 293434 ms

asset alwaysontop.min.js 282 KiB [emitted] [minimized] (name: alwaysontop) 2 related assets
orphan modules 357 KiB [orphan] 247 modules
runtime modules 1.04 KiB 5 modules
cacheable modules 1.06 MiB
  modules by path ./node_modules/react/ 9.87 KiB
    modules by path ./node_modules/react/*.js 402 bytes 2 modules
    modules by path ./node_modules/react/cjs/*.js 9.48 KiB 2 modules
  modules by path ./node_modules/hoist-non-react-statics/ 6.19 KiB 3 modules
  modules by path ./node_modules/react-dom/ 175 KiB
    ./node_modules/react-dom/index.js 1.32 KiB [built] [code generated]
    ./node_modules/react-dom/cjs/react-dom.production.min.js 173 KiB [built] [code generated]
  modules by path ./node_modules/scheduler/ 6.84 KiB
    ./node_modules/scheduler/index.js 197 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 6.65 KiB [built] [code generated]
  4 modules
webpack 5.57.1 compiled successfully in 193756 ms

asset dial_in_info_bundle.min.js 489 KiB [emitted] [minimized] (name: dial_in_info_bundle) 2 related assets
orphan modules 385 KiB [orphan] 187 modules
runtime modules 1.04 KiB 5 modules
cacheable modules 1.4 MiB
  modules by path ./node_modules/moment/ 316 KiB 52 modules
  modules by path ./node_modules/i18next-browser-languagedetector/ 11.6 KiB 10 modules
  modules by path ./node_modules/html-parse-stringify2/ 4.75 KiB 4 modules
  modules by path ./react/features/ 383 KiB 2 modules
  modules by path ./node_modules/react/ 8.5 KiB 2 modules
  modules by path ./node_modules/react-dom/ 175 KiB
    ./node_modules/react-dom/index.js 1.32 KiB [built] [code generated]
    ./node_modules/react-dom/cjs/react-dom.production.min.js 173 KiB [built] [code generated]
  modules by path ./node_modules/scheduler/ 6.84 KiB
    ./node_modules/scheduler/index.js 197 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 6.65 KiB [built] [code generated]
webpack 5.57.1 compiled successfully in 187739 ms

asset do_external_connect.min.js 2.82 KiB [emitted] [minimized] (name: do_external_connect) 1 related asset
orphan modules 24.8 KiB [orphan] 5 modules
cacheable modules 29.3 KiB
  ./connection_optimization/do_external_connect.js + 5 modules 27.2 KiB [built] [code generated]
  ./node_modules/@hapi/bourne/lib/index.js 2.02 KiB [built] [code generated]
webpack 5.57.1 compiled successfully in 112779 ms

asset analytics-ga.min.js 2.26 KiB [emitted] [minimized] (name: analytics-ga) 1 related asset
orphan modules 7.11 KiB [orphan] 2 modules
./react/features/analytics/handlers/GoogleAnalyticsHandler.ts + 2 modules 11.9 KiB [built] [code generated]
webpack 5.57.1 compiled successfully in 60990 ms

asset close3.min.js 0 bytes [emitted] [minimized] (name: close3)
./static/close3.js 1 bytes [built] [code generated]
webpack 5.57.1 compiled successfully in 18275 ms

asset external_api.min.js 34.3 KiB [emitted] [minimized] (name: external_api) 1 related asset
orphan modules 52.8 KiB [orphan] 18 modules
runtime modules 718 bytes 3 modules
cacheable modules 127 KiB
  modules by path ./node_modules/ 35 KiB
    modules by path ./node_modules/@jitsi/ 19.1 KiB
      ./node_modules/@jitsi/logger/lib/index.js 3.74 KiB [built] [code generated]
      ./node_modules/@jitsi/logger/lib/Logger.js 5.41 KiB [built] [code generated]
      ./node_modules/@jitsi/logger/lib/LogCollector.js 9.92 KiB [built] [code generated]
    ./node_modules/events/events.js 14 KiB [built] [code generated]
    ./node_modules/@hapi/bourne/lib/index.js 2.02 KiB [built] [code generated]
  modules by path ./modules/API/external/ 91.5 KiB
    ./modules/API/external/index.js 171 bytes [built] [code generated]
    ./modules/API/external/external_api.js + 13 modules 91.3 KiB [built] [code generated]
webpack 5.57.1 compiled successfully in 114307 ms

asset face-landmarks-worker.min.js 1.81 MiB [emitted] [minimized] (name: face-landmarks-worker) 2 related assets
orphan modules 3.02 MiB [orphan] 508 modules
runtime modules 969 bytes 5 modules
cacheable modules 2.69 MiB
  modules by path ./ 2.69 MiB
    modules by path ./node_modules/@tensorflow/tfjs-backend-wasm/ 138 KiB
      ./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.js 95.5 KiB [built] [code generated]
      ./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js 42.5 KiB [built] [code generated]
    ./react/features/face-landmarks/faceLandmarksWorker.ts + 293 modules 2.52 MiB [built] [code generated]
    ./node_modules/long/src/long.js 36 KiB [built] [code generated]
  7 modules
webpack 5.57.1 compiled successfully in 187710 ms

asset noise-suppressor-worklet.min.js 154 KiB [emitted] [minimized] (name: noise-suppressor-worklet) 1 related asset
orphan modules 182 KiB [orphan] 5 modules
./react/features/stream-effects/noise-suppression/NoiseSuppressorWorklet.ts + 5 modules 189 KiB [built] [code generated]
webpack 5.57.1 compiled successfully in 86559 ms
rm -fr libs
mkdir -p libs
cp \
                build/app.bundle.min.js \
                build/app.bundle.min.js.map \
                build/do_external_connect.min.js \
                build/do_external_connect.min.js.map \
                build/external_api.min.js \
                build/external_api.min.js.map \
                build/dial_in_info_bundle.min.js \
                build/dial_in_info_bundle.min.js.map \
                build/alwaysontop.min.js \
                build/alwaysontop.min.js.map \
                ./analytics-ga.js \
                build/analytics-ga.min.js \
                build/analytics-ga.min.js.map \
                build/face-landmarks-worker.min.js \
                build/face-landmarks-worker.min.js.map \
                build/noise-suppressor-worklet.min.js \
                build/noise-suppressor-worklet.min.js.map \
                libs
cp \
                build/close3.min.js \
                build/close3.min.js.map \
                libs || true
cp: build/close3.min.js.map: No such file or directory
cp \
                node_modules/@jitsi/rnnoise-wasm/dist/rnnoise.wasm \
                libs
cp -R \
                node_modules/@jitsi/excalidraw/dist/excalidraw-assets \
                libs/
cp \
                react/features/stream-effects/virtual-background/vendor/tflite/*.wasm \
                libs
cp \
                react/features/stream-effects/virtual-background/vendor/models/*.tflite \
                libs
cp \
                node_modules/lib-jitsi-meet/dist/umd/lib-jitsi-meet.min.js \
                node_modules/lib-jitsi-meet/dist/umd/lib-jitsi-meet.min.map \
                node_modules/lib-jitsi-meet/dist/umd/lib-jitsi-meet.e2ee-worker.js \
                node_modules/lib-jitsi-meet/connection_optimization/external_connect.js \
                node_modules/lib-jitsi-meet/modules/browser/capabilities.json \
                libs
cp \
                node_modules/@matrix-org/olm/olm.wasm \
                libs
cp \
                node_modules/@tensorflow/tfjs-backend-wasm/dist//*.wasm \
                libs
./node_modules/.bin/sass css/main.scss css/all.bundle.css && \
        ./node_modules/.bin/cleancss --skip-rebase css/all.bundle.css > css/all.css && \
        rm css/all.bundle.css
([ ! -x deploy-local.sh ] || ./deploy-local.sh)
cp \
                node_modules/@vladmandic/human-models/models/blazeface-front.bin \
                node_modules/@vladmandic/human-models/models/blazeface-front.json \
                node_modules/@vladmandic/human-models/models/emotion.bin \
                node_modules/@vladmandic/human-models/models/emotion.json \
                libs
rm -fr build

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This is a successful build. What does not work?

**Comment by pangsgithub** [comment]
Where are the packaged files？

**Comment by saghul** [comment]
In libs
