### ISSUE TITLE
Whiteboard improvements

### ISSUE THREAD

**Issue by maymage** [jitsi/jitsi-meet#12639]
Hi all, 

using the new Whiteboard feature, I'd propose a few suggestions to improve the experience:

* the default arrow shape is very unclean and should default the the cleanest version offered by `excalidraw`
* the default text font is not hand-write-y and doesn't fit the whiteboard idea. This is in contrast to the default font on `excalidraw`, which is very nice. Use that or a similar font.
* when in writing mode, the always on tool bar to the left is always visible, when the window width is larg - like in `excalidraw`. For cleanness the collapsed version with the bottom toolbar could be always on. 
* The eraser is a the bottom left instead of at the top, which creates confusion and contrasts to `excalidraw` again. Follow the `excalidraw` default. 
* Should the Whiteboard be zoomable at all? 

![Bildschirmfoto vom 2022-12-04 09-45-55](https://user-images.githubusercontent.com/36572014/205482330-51c6f2f2-5269-4446-adf4-f43bfa2fd3df.png)

**Comment by maymage** [comment]
Version

```
flatpak  info org.jitsi.jitsi-meet 
Jitsi Meet - Jitsi Meet - Secure, Simple and
Scalable Video Conferences
         Kennung: org.jitsi.jitsi-meet
             Ref: app/org.jitsi.jitsi-meet/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         Version: 2022.11.0
          Lizenz: Apache-2.0
        Ursprung: flathub
        Sammlung: org.flathub.Stable
    Installation: system
     Installiert: 235,1 MB
Laufzeitumgebung: org.freedesktop.Platform/x86_64/21.08
             Sdk: org.freedesktop.Sdk/x86_64/21.08

          Commit: f39ab24eb998fb6ad4b5db479f1a3f…
          Parent: 4b0774a5ea9880e60cf230df8b963a…
         Betreff: Update jitsi-meet-x86_64.AppImage to 2022.11.0 (92824397)
           Datum: 2022-11-20 17:59:44 +0000
```

**Comment by saghul** [comment]
Hi there! Thanks for the feedback, some comments below.

> * the default arrow shape is very unclean and should default the the cleanest version offered by `excalidraw`

I just tried excalidraw.com and it looks the same to me, we are a few versions behind though. What do you mean by "unclean"?

> * the default text font is not hand-write-y and doesn't fit the whiteboard idea. This is in contrast to the default font on `excalidraw`, which is very nice. Use that or a similar font.

Not sure if this was deliberate or not, can you confirm @mihhu ?

Bear in mind that we don't aim to provide the exact same experience as vanilla Excalidraw. You can just go to excalidraw.com for that. We have made conscious decisions to hide some controls and tweak some behavior for a better product fit. This may not match your expectations, but it currently matches ours.

> * when in writing mode, the always on tool bar to the left is always visible, when the window width is larg - like in `excalidraw`. For cleanness the collapsed version with the bottom toolbar could be always on.

Not sure what you mean here. If you mean the options that show on the left, those are shown for each specific tool you are using, a pen or text etc. That comes straight from excalidraw.

> * The eraser is a the bottom left instead of at the top, which creates confusion and contrasts to `excalidraw` again. Follow the `excalidraw` default.

As I said above, we don't necessarily want to embed it just as-is. That said, I don't know if we moved that control deliberately, did we @mihhu ?



> * Should the Whiteboard be zoomable at all?

It should, and it is.

**Comment by maymage** [comment]
> I just tried excalidraw.com and it looks the same to me, we are a few versions behind though. What do you mean by "unclean"?

I refer to the cleanness of the arrow, that is how tidy and neat it is drawn. Below a screen shot from excalidraw
with a clean and less clean arrow, where you can see, that the unclean arrow is actually consisting of several lines. 
I don't think, this is a good default.

![Arrows](https://user-images.githubusercontent.com/36572014/205615634-f2951489-6d70-4711-b7f3-c39320cead05.png)


You can adjust the cleanness in the arrow-settings-panel, see below

![Arrow_Settings](https://user-images.githubusercontent.com/36572014/205615134-7097e78b-1a5c-49ac-86a7-150251d13c15.png)

**Comment by maymage** [comment]
> Not sure what you mean here. If you mean the options that show on the left, those are shown for each specific tool you are using, a pen or text etc. That comes straight from excalidraw.

Here I refer to the uncollapsed (large width of the browser) to the collapsed (small width of the browser) view of excalidraw, see the screenshots below. 

---

Uncollapsed

![Excalidraw_Uncollapsed](https://user-images.githubusercontent.com/36572014/205616863-8d8f1969-6e0e-427e-8b28-8930b0398286.png)

---

Collapsed

![Excalidraw_Collapsed](https://user-images.githubusercontent.com/36572014/205616899-3e9fcf6e-be24-43ac-b8b3-d46ca1d0b92c.png)

---

As you can see, in the collapsed view the settings to the left are hidden behind an icon on the bottom (the second from the left). Designwise it may be desirable to always have the collapsed view to expose less settings and increase the writable space. In fact the settingspanel to the left in the uncollapsed view poses a problem for writing on the space, that is covered by that settings panel.

**Comment by mihhu** [comment]
> > * the default text font is not hand-write-y and doesn't fit the whiteboard idea. This is in contrast to the default font on `excalidraw`, which is very nice. Use that or a similar font.
> 
> Not sure if this was deliberate or not, can you confirm @mihhu ?

It is one of the font options excalidraw provides and it was a design choice on our part to stick to the sans-serif version.

> > * The eraser is a the bottom left instead of at the top, which creates confusion and contrasts to `excalidraw` again. Follow the `excalidraw` default.
> 
> As I said above, we don't necessarily want to embed it just as-is. That said, I don't know if we moved that control deliberately, did we @mihhu ?

At the time we created the fork, excalidraw had a much different layout and the eraser was placed on the bottom. We can move on to update our fork with their latest looks, but we're still waiting for their [reply](https://github.com/excalidraw/excalidraw/discussions/5902), as we're interested in making this solution easy to embed for everyone else.

> > I just tried excalidraw.com and it looks the same to me, we are a few versions behind though. What do you mean by "unclean"?
> 
> I refer to the cleanness of the arrow, that is how tidy and neat it is drawn. Below a screen shot from excalidraw with a clean and less clean arrow, where you can see, that the unclean arrow is actually consisting of several lines. I don't think, this is a good default.
> 
> ![Arrows](https://user-images.githubusercontent.com/36572014/205615634-f2951489-6d70-4711-b7f3-c39320cead05.png)

We can tweak it to use the clean version, I believe here the sketchy one came as default and the UX team requested that we keep the tool options at a minimum, to avoid cluttering and simplify the experience.

In regards to the settings menu on the small size view, I agree with you, it does take a lot of space, but I wonder if it doesn't come handy when looking for the tool options to have them just one tap away? We'd need a bit of testing there to see how it feels.

**Comment by maymage** [comment]
> ..it was a design choice on our part to stick to the sans-serif version

Was it for license reasons or because the [font](https://virgil.excalidraw.com/) was not good enough? 
Would this perhaps warrant an upstream issue? The current plain font just doesn't seem right in
a hand-write-y sketch context and in fact excalidraw defaults to the vergil font. 

---

> We can move on to update our fork ... but we're still waiting for their reply ..

No hurry though.

---

> We can tweak it to use the clean version, ...

Yes, please.. on the other hand this could also warrant an upstream issue. Perhaps it's just that the 
"dirty" arrow is just not visually nice, but could be made better than the clean one. 

---

> In regards to the settings menu on the small size view, .. we'd need a bit of testing there to see how it feels.

If the collapsed view would become the standard view, the lower panel should not span all the screen width though.

**Comment by maymage** [comment]
Probably most issues here could be easily resolved by updating to the latest excalidraw and choosing better defaults. 

In fact Jitsi's Excalidraw implementation [seems](https://github.com/jitsi/excalidraw) to be  based on v0.9, 
while Excalidraw is on [v0.15](https://github.com/excalidraw/excalidraw/tree/v0.15.0) at least. 

So perhaps, when an update from Jitsi's side comes, this issue could be addressed?

**Comment by maymage** [comment]
A further issue. Go to a Jitsi Whiteboard

* select pen and draw
* select arrow and draw

Result: Fall back to Selection [1]
Expected: Fall back to Pen [7]

Exalidraw has the same behaviour, 
unless you lock to the last action.
Jitsi doesn't offer the lock.

**Comment by saghul** [comment]
We haven't received enough feedback to warrrant bringing back the lock icon IMHO.

**Comment by maymage** [comment]
@saghul  How do you get that feedback though? You could ask on the Discourse Channel or, what else are the usual way for Jitsi to actively query feedback? Waiting for people to file issues on Github is.. risky.. for feedback driven design.

On the other hand the upstream project will have had their reasons for their design.

**Comment by saghul** [comment]
> @saghul How do you get that feedback though? You could ask on the Discourse channel or, what else are the usual way for Jitsi to actively query feedback? Waiting for people to file issues on Github is.. risky.. for feedback driven design.

Our community indeed, and GH issues too.

> On the other hand the upstream project will have had their reasons for their design.

And we have ours. While it's the same tool, our use case is slightly different.

**Comment by maymage** [comment]
@mihhu 

would you update this issue? Or should I close and open new ones to clean up the discussion? 
I don't think, any of the issues raised has been addressed, right?

**Comment by maymage** [comment]
@saghul if this issue is not useful for you or @mihhu, then just close it.

**Comment by saghul** [comment]
I think there nothing we plan on action on here, so I'm closing it.
