### ISSUE TITLE
JavaScript error when filmStripOnly: true

### ISSUE THREAD

**Issue by RedWolves** [jitsi/jitsi-meet#1263]
The [api.html](https://github.com/jitsi/jitsi-meet/blob/master/doc/api/api.html) example causes a JavaScript error and kicks the participant out of the conference. 

The cause is setting the filmStripOnly interfaceConfigOverwrite property to true:

```
var interfaceConfigOverwrite = {
                filmStripOnly: true
            };
```

```
[app.js] <>:  TypeError: Cannot read property 'firstElementChild' of null
    at Object.addInviteButton (ContactListView.js:107)
    at Object.setup (ContactListView.js:97)
    at new e (ContactList.js:18)
    at conference.js:510
```

**Comment by hristoterezov** [comment]
This error is fixed in the latest versions of jitsi-meet but the fix is not yet deployed to meet.jit.si deployment. We'll update meet.jit.si soon.
