### ISSUE TITLE
Speaker statistics and learning dashboard

### ISSUE THREAD

**Issue by alfredonodo** [jitsi/jitsi-meet#12638]
Hi,
jitsi has recently introduced native whiteboard support. At the moment it does not have the functionality to export speaker statistics and this is the last missing piece to be on a par with [BBB](https://docs.bigbluebutton.org/2.4/new.html#learning-analytics-dashboard) or other video conferencing services.
So please take your time, but implement a speaker statistics dashboard from the UI.

**Comment by saghul** [comment]
Speaker statistics are available while in the meeting (you can access them either via the overflow menu button or by pressing T).

**Comment by alfredonodo** [comment]
Right. However, it is not possible to export speaker statistics and have a good evaluation of user activity as in the learning dashboard of BBB other video conferencing services.

**Comment by saghul** [comment]
I see. We have no plans to create a dashboard for this.

I believe we do have events for this data so one could build their own export feature. @gabiborlea ?

**Comment by alfredonodo** [comment]
Any news about this?
Thank you

**Comment by saghul** [comment]
@gabiborlea do we have speaker stats available in the iframe API?

@alfredonodo JUst to be clear, we have no plans to implement a dashboard. What we can do is make sure all the necessary data to build one is available on the API boundary.

**Comment by gabiborlea** [comment]
Hello! At the moment the speaker stats are not available though the iframe api at the moment
