### ISSUE TITLE
Screen sharing not visible on mobile after 2.0.8044 upgrade

### ISSUE THREAD

**Issue by jplandry908** [jitsi/jitsi-meet#12636]
Upgrading from "2.0.7882 (2022-10-06)" to "2.0.8044 (2022-11-11)" appears to break mobile devices from viewing a users screen share (video, audio, etc all work correctly). Other web browser users are still able to see screen shares after this upgrade; however, mobile users cannot. I was also able to reproduce this issue on "https://meet.jit.si".

To reproduce, join a video conference using 2 browsers (I used Chrome) and via a mobile device (I used iOS). Share your screen using one of your browsers. You should be able to view the screen share on the second browser, but it is not displayed on the mobile device.

FYI - I rolled back my Jitsi implementation to v2.0.7882 and was able to restore this functionality.

**Comment by saghul** [comment]
What mobile app version are you using?

**Comment by jplandry908** [comment]
Hi @saghul. I'm on the latest iOS v16.1.2. I also downloaded the current version of Jitsi Meet from the App Store today (v22.7.0) to help rule out my self-hosted environment and test the current Jitsi production version.

**Comment by saghul** [comment]
Thanks I'll take a look.

**Comment by jplandry908** [comment]
Hi @saghul. I just noticed that the Jitsi production version is now working after your last update. I'll upgrade my self-hosted version and let you know if the issue has been resolved.

**Comment by sernik** [comment]
Same on ios `v15.1` after the update to `v22.7.0`. Others shared screen not displayed in the app. Works fine in a browser. Self hosted instance.

**Comment by jplandry908** [comment]
Hi @saghul. I attempted to upgrade my self-hosted version to the latest release, but screen sharing is still not visible on mobile devices (everything still appear to work correctly in the browser).

2.0.8138 (2022-12-07) - MOBILE SCREEN SHARING BROKE
2.0.8133 (2022-12-07) - NOT TESTED
2.0.8127 (2022-12-06) - NOT TESTED
2.0.8044 (2022-11-11) - MOBILE SCREEN SHARING BROKE
2.0.7882 (2022-10-06) - CURRENT WORKING VERSION

Do you know what version is currently running on meet.jit.si? When I opened up this issue, I was able to replicate it using the Jitsi website and the latest version of the Jitsi mobile client in the iOS app store (v22.7.0). However, in my recent testing it now appears to be working. I assume something changed on the website (since the iOS client app is still the same version) in the past 5 days that resolved the issue on your end.

Thank you for your time and assistance.

**Comment by jplandry908** [comment]
How strange. My self-hosted instance works fine until I upgrade to 8044 and beyond. Although, I have the Jitsi SDK within a custom react-native app (iOS and Android). It sounds like you may be using the Jitsi app from the app store and just pointing it to your self-hosted instance?

**Comment by sernik** [comment]
> How strange. My self-hosted instance works fine until I upgrade to 8044 and beyond. Although, I have the Jitsi SDK within a custom react-native app (iOS and Android). It sounds like you may be using the Jitsi app from the app store and just pointing it to your self-hosted instance?

Correct. I use the config from https://github.com/jitsi-contrib/jitsi-traefik/tree/main/traefik-v2

**Comment by jplandry908** [comment]
Hi @saghul. I may have discovered a possible cause. The custom app is react-native, so it is still using SDK 5.1.0 (awaiting for your new react-native SDK to be released). This hosted Jitsi is still running 2.0.7882. The common use case is someone connects on a computer and shares video and a slide, and the other user sometimes connects on a mobile device. Once upgrading to anything after 2.0.7882 (starting with 2.0.8044), both video and screen share cannot be simultaneously displayed on the mobile device. Screen sharing seems to works fine if video is not also being shared by the computer, but if video is being shared then the screen share is not.

As a test, I just pointed the custom app to "https://meet.jitsi.si" as a test. Using your production instance, I am able to reproduce the exact results. I assume your production instance is on a current version and there is a conflict between SDK 5.1.0 and the most recent versions of Jitsi (starting with 2.0.8044) that impacts multiple streams (video and screen sharing) to be displayed from one user.

Do you happen to know if there is a feature flag or something on the mobile device that could be added to correct this until the new SDK comes out and the mobile device implementation can be updated?

Thank you for your time and assistance. I appreciate all of your efforts on such a great product.
