### ISSUE TITLE
Call Recording

### ISSUE THREAD

**Issue by Hassanilyas143** [jitsi/jitsi-meet#12630]
Hi Team!
is it possible can I to record a call?
And I also can we present a custom screen to invite people?

**Comment by saghul** [comment]
Yes you can, use the Start recording button. Note that if you are using meet.jit.si then it will only be available in Chrome at this time.



> And I also can we present a custom screen to invite people?

What do you mean?

**Comment by Hassanilyas143** [comment]
In iOS, I can't able to record calls only screen sharing is available.
For the second question, I need to present another screen when the user clicks on add member button is it possible?

**Comment by saghul** [comment]
As I said, if you are using meet.jit.si (the default server) could recording is not possible, but local recordings are, but that feature is only supported in desktop Chrome.

Regarding the screen, no you cannot do that unless you build your own SDK.

**Comment by saghul** [comment]
No plans to add local recording there. Cloud recording is available if your deployment supports it, as I said.
