### ISSUE TITLE
Can not drag (sort) option poll

### ISSUE THREAD

**Issue by taihoa** [jitsi/jitsi-meet#12640]
After get source code lastest, I cannot drag option in poll create. At source code older I can drag option move up down.
Version: 2.0.8044

https://user-images.githubusercontent.com/8847573/205535955-5b170a11-7f95-4c01-b2c2-d9f433ee02c9.mp4

**Comment by saghul** [comment]
@Calinteodor we removed that feature, right?

**Comment by Calinteodor** [comment]
This feature is not available on mobile, but it's still available on web.

**Comment by taihoa** [comment]
@Calinteodor I use on web but it not working

**Comment by saghul** [comment]
@taihoa It's getting removed here: https://github.com/jitsi/jitsi-meet/pull/12641

**Comment by taihoa** [comment]
@Calinteodor if I want to keep this function then How to do?

**Comment by saghul** [comment]
You can revert the PR locally, but as you discovered the functionality was broken anyway, so you'd also need to fix it. We don't intend to keep supporting it, so it's being removed.
