### ISSUE TITLE
Ability to hide 'End meeting for all' button

### ISSUE THREAD

**Issue by schtoporok** [jitsi/jitsi-meet#12653]
**Is your feature request related to a problem you are facing?**
It would be great to hide 'End meeting for all' button in some cases.

**Describe the solution you'd like**
Add ability to add/remove button to/from toolbarButtons property in config.js.

**Comment by thisisnkc** [comment]
If you are using docker-jitsi, add **ENABLE_END_CONFERENCE=false** in your env file.
