### ISSUE TITLE
Add whiteboard tooltips to l10n

### ISSUE THREAD

**Issue by sellth** [jitsi/jitsi-meet#12652]
**Is your feature request related to a problem you are facing?**
Our Jitsi instance is mainly used by non-native English speakers. While I love the new whiteboard feature, all text in there is in English and cannot be localized as it's not pulled from lang/main.json.

**Describe the solution you'd like**
Add whiteboard tooltip texts to lang/main.json

**Describe alternatives you've considered**
- Make all users learn English > not feasible.
- Button symbols might be enough to get what's going on, but that's not optimal.

**Comment by saghul** [comment]
This might be tricky because the whiteboard is an external project, Excalidraw, so we'd need to sync the language with the one used in Jitsi Meet, which may or may not be available in Excalidraw.
