### ISSUE TITLE
Android Invite Others button debounce

### ISSUE THREAD

**Issue by cylimyuan** [jitsi/jitsi-meet#12666]
Invite Others button is not disabled after tapped

https://user-images.githubusercontent.com/19247537/206924864-40693c9f-8ce6-495c-a517-a05f693c41ee.mp4

**Comment by saghul** [comment]
Good catch. This might be a bit tricky to fix since IIRC we don't know when the system presents the sheet, but maybe there is a way around it...

**Comment by saghul** [comment]
This has been fixed in https://github.com/jitsi/jitsi-meet/pull/12765
