### ISSUE TITLE
"ghost" raised hand using android sdk 7.0.0

### ISSUE THREAD

**Issue by PO-jfiniel** [jitsi/jitsi-meet#12671]
### Description:

After a participant has raised its hand during a meeting, it looks like the raised hand list is not cleared when leaving the meeting (or starting a new one).

### Steps to reproduce:

1. Start a meeting with jitsi-meet-sdk-samples application built with jitsi-meet-sdk:7.0.0 on [meet.jit.si](http://meet.jit.si/) server.
2. On another device (not important which one), join the meeting using a web browser.
3. Raise hand from the web browser (the raised hand icon pops up in the top left corner of the android device), then lower it (the icon disappears).
4. Stop the meeting on the android app, and start a new one where no one else is present.
5. Now there is an icon in the upper left saying that there is one raised hand whereas the android device is alone in the meeting and no one raised its hand.
6. When raising hand on the android device, the icon now shows 2 raised hands.
We can accumulate raised hand using the same process again, and get to a point where we start an empty meeting and have the icon say there are 10 raised hands in the room.
![screen](https://user-images.githubusercontent.com/90033965/207065884-7b1f11d1-b8f0-4e20-a14a-169e79cf6b4d.png)

### Expected behavior:

When a meeting starts, there should be no raised hand shown if nobody has raised its hand.

### Actual behavior:

The number of raised hands is not null if we start a meeting after one where somebody raised its hand.

### Server information:

Public [meet.jit.si](http://meet.jit.si/)

### Client information:

Android 11
Android application build from jitsi-meet-sdk-samples in java version on master with only the jitsi-meet-sdk version updated to 7.0.0 on app/build.gradle.

### Additional information:

This is not reproducible on native android app.
Is something done to clean the participants redux at end of a meeting or at beginning of a meeting or something like that?
I did not find anything like that on native android source code on jitsi-meet repository.

**Comment by Calinteodor** [comment]
Cannot reproduce.

**Comment by PO-jfiniel** [comment]
I can reproduce this every time using the [jitsi-meet-sdk-samples](https://github.com/jitsi/jitsi-meet-sdk-samples) by simply changing the SDK version to a newer version (like 8.1.2).
Should I open an issue in this sdk-samples repository (even though I strongly believe it is related to this SDK repository)?

**Comment by Calinteodor** [comment]
Yes, please open an issue there. Thank you!
