### ISSUE TITLE
Popup closed after entering wrong password

### ISSUE THREAD

**Issue by bogdanovr** [jitsi/jitsi-meet#12687]
Authorization popup closing and nothing happens after entering wrong username/password.

### Description:

LDAP auth via sasl

### Steps to reproduce:

Setup ldap auth.
Use wrong username/password.
Press Login button.
Window closes without any information

### Expected behavior:

Write "incorrect password" without closing popup

### Actual behavior:

Popup window is closed.

### Server information:

- Jitsi Meet version: 2.0.8138
- Operating System: Debian 11

### Client information:

- Browser / app version: Chrome 10
- Operating System: Ubuntu 20.04

### Additional information:

2.0.7648 version is ok mobile and desktop browsers.

**Comment by saghul** [comment]
@robertpin can you PTAL?

**Comment by ashish960** [comment]
hey i am new to open source can i work on this issue

**Comment by saghul** [comment]
You are very welcome to do so! Alas we currently don't have many spare cycles for providing guidance.

**Comment by ashish960** [comment]
ok ,i will do my best to solve that issue .Can you join me in any of your group for further discussion.

**Comment by Ashwin-hp** [comment]
I would like to work on this issue. Could you please assign it to me.

**Comment by Ashwin-hp** [comment]
@saghul I would like to work on this issue.Pls assign it to me.

**Comment by MohitBansal321** [comment]
hey this issue still resolve or not 
if not I will work on it

**Comment by bogdanovr** [comment]
Latest version is ok, you may close issue. Thanks
