### ISSUE TITLE
Wrong clicking the "Leaving meeting" button.

### ISSUE THREAD

**Issue by DmitriyMurzin** [jitsi/jitsi-meet#12688]
**Is your feature request related to a problem you are facing?**

There are often problems with clicking the "Leaving meeting" button, a user with moderator rights may accidentally click the "End meeting for all" button and close the conference for everyone (

**Describe the solution you'd like**
Add a confirmation window for closing the conference with a warning that it will be closed to everyone.

**Describe alternatives you've considered**
Disabling the option to close the conference, but this feature is useful in itself.

**Comment by saghul** [comment]
This is not a single click action first the user needs to click on the hangup button, then on the second option on the menu. Another confirmation doesn't sound right IMHO.

**Comment by DmitriyMurzin** [comment]
But the user may accidentally click the "End meeting for all" button instead of "Leaving meeting" and interrupt the conference for everyone (I think this is a problem.

**Comment by DmitriyMurzin** [comment]
Confirmation is only needed for "End meeting for all"

**Comment by thisisnkc** [comment]
If you don't want this obviously you can directly hangup the meeting on click of the hangup button, add **ENABLE_END_CONFERENCE=false** in your env file, if using docker-jitsi.

otherwise follow this https://community.jitsi.org/t/how-to-disable-hangup-button-moderator-end-meeting-for-all/118415
