### ISSUE TITLE
During the conference on devices with Android 8 and 9, when an outside call comes in, the sounds are reflected in the conference.

### ISSUE THREAD

**Issue by yakupseker** [jitsi/jitsi-meet#12698]
### Description:

During the conference on devices with Android 8 and 9, when an outside call comes in, the sounds are reflected in the conference.

### Steps to reproduce:

1.  The microphone is turned on in the active meeting.
2.  At that moment, a phone call comes in.
3. The microphone is reflected in the meeting. (expected)
4.  The phone is answered.

### Expected behavior:

No sound should be reflected in the meeting while talking on the phone.

### Actual behavior:

While talking on the phone, all conversations are reflected in the meeting.

### Server information:

- Jitsi Meet version: stable/jitsi-meet_7648
- Operating System:  Android 8 & 9 

### Client information:

- Browser / app version: stable/jitsi-meet_7648
- Operating System: Android 8 & 9 

### Additional information:
The same problem is not observed in different android versions.

**Comment by saghul** [comment]
Do you have call integration enabled? Check settings -> advanced.
