### ISSUE TITLE
Flutter jitsi-meet error Could not resolve org.jitsi.react:jitsi-meet-sdk:3.3.0

### ISSUE THREAD

**Issue by omee-flut-begain** [jitsi/jitsi-meet#12709]
### Description:

This error occurred when I try to run project. I try all solution but nothing work please help me

### Error
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.3.0.
     Required by:
         project :app > project :jitsi_meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.3.0.
         > Could not get resource 'https://github.com/jitsi/jitsi-maven-repository/raw/master/releases/org/jitsi/react/jitsi-meet-sdk/3.3.0/jitsi-meet-sdk-3.3.0.pom'.
            > Could not GET 'https://raw.githubusercontent.com/jitsi/jitsi-maven-repository/master/releases/org/jitsi/react/jitsi-meet-sdk/3.3.0/jitsi-meet-sdk-3.3.0.pom'.      
               > Connect to raw.githubusercontent.com:443 [raw.githubusercontent.com/49.44.79.236, raw.githubusercontent.com/2405:200:1607:2820:41:0:0:36] failed: Connection timed out: connect
`

**Comment by saghul** [comment]
You must have a connection problem, that file is there and the URL loads just fine.

Also, that SDK is years old and won't work with the latest Jitsi Meet versions, you should ask the flutter plugin author to upgrade.

**Comment by saghul** [comment]
You should ask the flutter plugin authors to update.
