### ISSUE TITLE
After Ninja-Mode Jitsi is partially unable to restore video

### ISSUE THREAD

**Issue by LameOphil** [jitsi/jitsi-meet#12707]
Description
In order to test quality settings in Jitsi-Version, every user (12 total) adjusted their video settings simultaneously.
Resulting in ninja-icon for everyone immediately, after 10 or so seconds some videos could be seen again where others were kept in "ninja-mode". After a few minutes ninja-icons were alternating between users without a distinguishable pattern.
Neither of the group was able to see all of the others.

**We in general experienced issues where Jitisi has problems after ninja-mode (shortly dropping bandwidth) to reestablish video, even though bandwidth was again adequate**. 

### Steps to reproduce:

Simultaneously alter video quality settings.

### Expected behavior:

Short ninja-mode, then reestablish video connection.

### Actual behavior:

Ninja-mode appeared for everyone immediately, after 10 or so seconds some videos could be seen again where others were kept in "ninja-mode". After a few minutes ninja-icons were alternating between users without a distinguishable pattern.
Neither of the group was able to see all of the others.

### Server information:

- Jitsi Meet version: 2.0.8138 (2022-12-07)
- Operating System: Various: Chrome, Safari, Firefox

### Client information:

- Browser / app version: latest
- Operating System: MacOs

**Comment by saghul** [comment]
How did you alter video quality settings? Did you use network conditioner?

**Comment by LameOphil** [comment]
Actually, we alter video quality in the application itself under performance settings where you can choose one of four options. Highest quality is selected as default

**Comment by saghul** [comment]
And what value do you select?

**Comment by LameOphil** [comment]
Arbitrary, the problem occurred for everyone though. Even when setting quality back to default.

**Comment by saghul** [comment]
Gotcha. @hristoterezov any thoughts?

**Comment by LameOphil** [comment]
Problem might be more general though as we have experienced that after low bandwidth (and resulting ninja-mode) video reestablishment did not always work and the video stayed off even though bandwidth was back to full.
