### ISSUE TITLE
JMCallKitProxy's hasActiveCallForUUID method performs incorrect string comparison

### ISSUE THREAD

**Issue by AlvaroBro** [jitsi/jitsi-meet#12716]
![Captura de pantalla 2022-12-22 a las 11 19 05](https://user-images.githubusercontent.com/1628717/209113317-44d3d956-37d5-449e-8603-f6ee472a9ec6.png)

**Comment by saghul** [comment]
Good catch! We must have missed it when we translated from Swift back to ObjC.

**Comment by saghul** [comment]
Would you like to submit a PR?
