### ISSUE TITLE
Android: Connection issue to own server

### ISSUE THREAD

**Issue by jans23** [jitsi/jitsi-meet#12719]
### Description:

I use Jitsi Meet Android app and can't establish a connection to own Jitsi server meet.nitrokey.com Connecting to meet.jit.si works fine.

### Steps to reproduce:

1. Open Jitsi Meet Android app
2. Configure meet.nitrokey.com as server
3. Open or access any room
4. Connection error is shown:

![Screenshot_20221222-162409](https://user-images.githubusercontent.com/1450547/209167238-07003983-c6e4-406e-8cc9-56eddfa98a0b.png)

### Server information:

- Jitsi Meet version: latest
- Operating System: Linux

### Client information:

- Browser / app version: 22.7.0 build 227000
- Operating System: Android

**Comment by saghul** [comment]
Can you share your config.js ?

**Comment by jans23** [comment]
[config.js.txt](https://github.com/jitsi/jitsi-meet/files/10288938/config.js.txt)

**Comment by saghul** [comment]
Got it. At the bottom, before the lines which begin with "config.flags." add the following line:

"config.flags = {};"

No quotes.

**Comment by jans23** [comment]
That solved it. Thank you so much!

**Comment by saghul** [comment]
Sorry about that, this is fixed in the next stable release.

**Comment by anonid64** [comment]
Hello, this issue is solved or not?

**Comment by saghul** [comment]
Yes it is.

**Comment by anonid64** [comment]
> Yes it is.

Now i try connect with my android phone but it still error when about 3 month before it connect normal. What is wrong, please help me. Thank you
