### ISSUE TITLE
Screen Sharing Freeze / ANR in Android 13 

### ISSUE THREAD

**Issue by Arlovzki** [jitsi/jitsi-meet#12710]
### Steps to reproduce:

1. Open the Jitsi App on Android 13
2. Create/Join a meeting
3. Screen share

### Expected behavior:

The app should run smoothly and not freeze

### Actual behavior:

The app freezes and opens the ANR dialog and closed.

### Client information:

- Browser / app version: 22.7.1
- Operating System: Android 13

**Comment by saghul** [comment]
Are you able to capture a logcat?

**Comment by saghul** [comment]
Can you try the latest beta? I cannot reproduce it in a Pixel 6 running Android 13.

**Comment by Arlovzki** [comment]
Hello @saghul. Thank you for responding.

I tried the beta, the app runs smoothly now when screen sharing on Android 13.

**Comment by Arlovzki** [comment]
Please let me know if the beta branch has been merged into the master branch. Thank you!

**Comment by saghul** [comment]
The beta branch is mobile-23.0 and it is also part of master, but we recommend release branches.
