### ISSUE TITLE
First letters of participant name not properly centered on Firefox Ubuntu

### ISSUE THREAD

**Issue by braintweak** [jitsi/jitsi-meet#12727]
### Description:
First letters of participant name not properly centered on Firefox 108.1 Ubuntu 22.04.
Its centered properly on same system in chrome.

The issue does not reproduce on windows 10 firefox 108.0.1

### Steps to reproduce:

1. Open Jitsi web version in firefox 108 on ubuntu 22.04.
2. Enter any room with other participant.
3. The name is not aligned properly.

### Expected behavior:
Name should be properly centered.
Screenshots from windows firefox:
https://ibb.co/F0V06vT
https://ibb.co/Kmz9Bw9

### Actual behavior:
Name is moved up in the circle for some reason.
Screenshots from ubuntu firefox:
https://ibb.co/D1Jk0hJ
https://ibb.co/LtYYjws

### Server information:

- Jitsi Meet version: jitsi-meet/stable,now 2.0.8138-1
- Operating System: Self hosted LXC container,  Ubuntu 20.04.5 LTS

### Client information:

- Browser / app version: Firefox 108.0.1
- Operating System: Ubuntu 22.04

### Additional information:
None.

**Comment by saghul** [comment]
If this only happens on Firefox on Linux I'd assume it's a font rendering problem, not something for us to fix?

**Comment by braintweak** [comment]
> If this only happens on Firefox on Linux I'd assume it's a font rendering problem, not something for us to fix?

Is it a font rendering problem for firefox only then? Since it doesn't happen on chrome.

I don't know what is a better place to put this bug then.

**Comment by saghul** [comment]
> Is it a font rendering problem for firefox only then? Since it doesn't happen on chrome.

That would be my guess, yeah.



> I don't know what is a better place to put this bug then.

The Firefox bugzilla would be better IMHO.
