### ISSUE TITLE
The Android app needs to be optimized for Eink devices

### ISSUE THREAD

**Issue by farooqkz** [jitsi/jitsi-meet#12729]
### Description:

Eink displays have got very low refresh rate. Thus the animations are really horrible on the devices which use such these screens and therefore, must be disabled.

### Expected behavior:

There must be options to disable animations. Page turn could be used instead whenever having such a thing is necessary(e.g. when opening a menu). Also light theme must be used everywhere.

### Actual behavior:

Animations are shown everywhere.

### Client information:

- Operating System: Android

### Additional information:

I've got such a device and can help with testing. But I don't have development environment to compile and produce an APK.

**Comment by saghul** [comment]
There are so few of these devices we are unlikely to be able to allocate resources for it.

Pull requests are welcome though.

**Comment by farooqkz** [comment]
@saghul Should not this stay open in the case someone was interested in implementing it? "Not planned" gives me the deduction that even if someone is interested, you won't merge their PR.

**Comment by saghul** [comment]
"Not planned" means there are no plans to work on that feature. The issue is not locked, so people are still welcome to ask.

Generally speaking i'd accept a non-invasive PR.
