### ISSUE TITLE
Share screen on Firefox show black screen

### ISSUE THREAD

**Issue by taihoa** [jitsi/jitsi-meet#12726]
1. Open jitsi meet on firefox
2. Start meeting
3. Start share screen
4. Open link meeting on chrome
5. Join meeting
Result: Not show share screen on chrome, only black screen
Expected: On chrome show share screen of firefox.

https://user-images.githubusercontent.com/8847573/209759237-5917a5bd-ae19-40bb-84af-41502748d9ab.mp4

When I using chrome vs chrome then share screen working.

**Comment by saghul** [comment]
Can you reproduce this on meet.jit.si?

What versions of Firefox and Chrome are you testing?

**Comment by taihoa** [comment]
> 

Cannot reproduce on meet.jit.si
Firefox version 108.0
Chrome version 108.0.5359.124

**Comment by taihoa** [comment]
> Can you reproduce this on meet.jit.si?
> 
> What versions of Firefox and Chrome are you testing?

Cannot reproduce on meet.jit.si
Firefox version 108.0
Chrome version 108.0.5359.124

**Comment by saghul** [comment]
What version of the server components did you install?

**Comment by taihoa** [comment]
> What version of the server components did you install?

This is version of the server components
![image](https://user-images.githubusercontent.com/8847573/210477018-a610bce4-fefd-4954-95f8-24e264fa7ccd.png)

**Comment by saghul** [comment]
Can you please update to the latest and re-test?

**Comment by ghomem** [comment]
This is now reproducible on meet.jit.si . Can this issue be reopened?

**Comment by damencho** [comment]
We had fixed some issues with Firefox we will soon update meet

**Comment by ghomem** [comment]
@damencho Thank you. I volunteer to test once you have it updated.
