### ISSUE TITLE
Android Warning Unchecked cast: 'java.io.Serializable' to 'java.util.HashMap<java.lang.String,java.lang.Object>' 

### ISSUE THREAD

**Issue by PREM24JSK** [jitsi/jitsi-meet#12723]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

this line in JitsiMeetOngoingConferenceService gives warning (**Unchecked cast: 'java.io.Serializable' to 'java.util.HashMap<java.lang.String,java.lang.Object>'** )

 HashMap<String, Object> extraData = (HashMap<String, Object>) intent.getBundleExtra(EXTRA_DATA_BUNDLE_KEY).getSerializable(EXTRA_DATA_KEY);

**Comment by saghul** [comment]
What are you passing in the intent?

**Comment by PREM24JSK** [comment]
this is not My code its Jitsi SDK Code in method tryParseIsAudioMuted In JitsiMeetOngoingConferenceService .java file

**Comment by saghul** [comment]
@tmoldovan8x8

**Comment by tmoldovan8x8** [comment]
Did you encountered any issues here? It is indeed a warning, but that Serializable will be a HashMap (from the launch method) and even it weren't the block is guarded by the try-catch.
