### ISSUE TITLE
Not receiving video stream from iOS SDK after commit f3e4c57

### ISSUE THREAD

**Issue by ClassicalDude** [jitsi/jitsi-meet#12732]
### Description:

When connecting to a conference from an app implementing the iOS SDK, other devices do not receive a video stream from the iOS device, sometimes with the notification that video is turned off to conserve bandwidth. I am using a lite-sdk xcframework, compiled with the provided script from stable version 8044. This behavior only occurs when connecting to recently updated servers. When connecting to servers running earlier versions, such as 6776, the video feed behaves as expected.

This bug is mentioned also in the RocketChat bug list [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4775), and the people in RocketChat traced it to the commit I mentioned in the title - see [here](https://github.com/jitsi/jitsi-meet/pull/12499).

### Steps to reproduce:

1. Connect to meet.jit.si from an iOS client
2. Connect from any web client to the same meeting

### Expected behavior:

Web clients should see the video feed from the iOS client

### Actual behavior:

No video is shown, and sometimes a "Video is disabled to conserve bandwidth" notification is added, even with the fastest internet connections.

### Server information:

- Jitsi Meet version: most recent official meet.jit.si

### Client information:

iOS client, framework compiled from stable release no. 8044

**Comment by ClassicalDude** [comment]
Apology - I see that with server v. 6890 this issue is now fixed.

**Comment by ClassicalDude** [comment]
Apologies - I see that with server v6890 this is now fixed.

**Comment by MelanyG** [comment]
@ClassicalDude  Could you please clarify about how did you manage to fix video with iOS client? You mentioned server, but how does you select server with iOS SDK?
