### ISSUE TITLE
Three dots menu goes off the screen on Firefox with scaled display

### ISSUE THREAD

**Issue by exercismnow** [jitsi/jitsi-meet#12739]
### Description:

![Jitsi 3 dots menu overflow](https://user-images.githubusercontent.com/119020198/210644551-42ce14b2-11f2-44fc-940b-dbed7aa83738.png)

The 3 dots menu goes up and off the screen when using Firefox with a scaled display. This is inconvenient because you cannot click on the top-most items that have been cutoff:
- Profile
- Invite people
- Performance settings

The only way to click on them is to zoom out of the webpage, or change your scaling settings.

Context:
Many people use their computer with scaled displays for different reasons. (Inconvenient resolution for laptop screen form factor, bad eyesight, etc). The screen can be scaled via system settings, or application interfaces scaled. This bug report is about scaling Firefox's application display.

### Steps to reproduce:

1. Open Firefox
2. Navigate to `about:config`
3. Change `ui.textScaleFactor` = 150
4. Navigate to `meet.jit.si` and start a new meeting
5. Click on 3 dots menu

### Expected behavior:

The 3 dots menu should become scrollable, if the menu goes off the screen. This way, the user can access and click on all the items.

Another alternative is for the menu items to stack in multiple columns so that all of them can fit on the screen at the same time.

### Actual behavior:

The the top part of the 3 dots menu is off the screen

### Server information:
Using https://meet.jit.si on Jan 4, 2023. Not sure how to find version #.

### Client information:

- Browser / app version: Firefox 108.0.1
- Operating System: Linux Mint 21.1

### Additional information:

N/A

**Comment by saghul** [comment]
Can you share a screenshot of the full window? What size is it?

**Comment by exercismnow** [comment]
I don't have a screenshot right now, but it's a maximized Firefox window on a standard 1080p screen.

**Comment by SAGARGAUD01** [comment]
I am going to try this one.

**Comment by saghul** [comment]
This has been closed already.

**Comment by SAGARGAUD01** [comment]
okay then
