### ISSUE TITLE
Recording Not working

### ISSUE THREAD

**Issue by 515solutions** [jitsi/jitsi-meet#12747]
Recording not working with or without Jibri.
All UDP and TCP ports are opened for development.

Another error display on console
Uncaught TypeError: Cannot set properties of undefined (setting 'sourceNameSignaling')

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://community.jitsi.org/t/mobile-app-you-have-been-disconnected-can-see-connection-in-nginx-but-nothing-in-jitsi-logs/120093/2?u=damencho
