### ISSUE TITLE
Hello I want to ask about config reverse proxy for aws load balancer controller

### ISSUE THREAD

**Issue by dang-hoang-hieu** [jitsi/jitsi-meet#12746]
I am deploying jitsi docker to AWS EKS, I successfully deployed the containers and access to the web page.
But I can not start the meeting due to connection, as I read the wiki, the problem is we have reverse proxy which is AWS load balancing.
The current ver of [aws elb](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/) not support adding custom config yet. So I couldnt add the custom config as [here](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/#running-behind-a-reverse-proxy)

anyone experience the same? and have solution for this?
thank you a lot!!

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
