### ISSUE TITLE
Local recording still showed as "REC" on my end after my peer hit the limit

### ISSUE THREAD

**Issue by sethp** [jitsi/jitsi-meet#12742]
### Description:

My friend & I were trying the local recording feature on https://meet.jit.si  (which, by the way, is very cool!): at the beginning of our conversation, he hit "record." By the end (about 90 minutes later) he went to go stop the recording to ensure it was saved, and found instead of an ongoing recording he'd very quietly gotten a 1.07GB download about 20 minutes prior. On his end, he reported the "REC" indicator had gone away to match the end of the recording, but on my end I still saw it.

### Steps to reproduce:

I haven't reproduced this myself, but the steps we followed were:

1. Start local recording with two people in a call
2. Record for long enough to exceed the size limit (this would probably be easier to do if the limit were artificially reduced by a lot)

### Expected behavior:

When my peer hits the recording limit, my end of the meeting reflects that recording has stopped. Or, additionally, we have a much more significant notification that recording has ended (similar to the excellent "recording is on" notification). 

Alternatively, if the recording had continued by "rolling over" to a new file, that would have also matched my expectations and what I saw in the UI. 

### Actual behavior:

No recording was ongoing, but I still saw the "REC" indicator at the top of the screen.

### Client information:

- Browser / app version: Chrome 108.0.5359.124
- Operating System: macOS

**Comment by saghul** [comment]
Thanks for the report! @robertpin can you PTAL?
