### ISSUE TITLE
Whiteboard: unintended copy functionality

### ISSUE THREAD

**Issue by maymage** [jitsi/jitsi-meet#12749]
Hi all, 

I'm using a `One by Wacom` graphical tablet with a two button pen on a standard GNOME installation. 

The following situation as appearing in the below video is reproducible as follows:

*  Copy some text to your clipboard `Ctrl+C`
*  Open Jitsi's whiteboard
*  Select the pen drawer and start to draw
*  During drawing, press the lower button and release it
*  End the drawing by lifting the pen

This sequence of actions inserts the before copied text. It's been happening to me
many, many times involuntarily. 

[Bildschirmaufzeichnung vom 2023-01-09, 13-39-14.webm](https://user-images.githubusercontent.com/36572014/211311077-383f2558-1c57-4b58-aa10-f8f1e4de6f2c.webm)

If Jitsi wishes to support pen buttons, it should in my opinion probably point  at most one button to the eraser,
but due to a lack of configurability and the many existing, different drawing tablets, that should be it for the sake of
usability.

**Comment by saghul** [comment]
Hum, that is really odd. We haven't added any extra input handling for pen buttons, let alone make one act as paste. Not sure where this comes from TBH.

**Comment by maymage** [comment]
Okay.. I was suspicious, because I remembered some c&p logics discussions from a wayland channel. Anyway..

* Not reproducible on Excalidraw + Firefox on Wayland or Xorg
* Not reproducible on Excalidraw + Chromium on Xorg
* **Reproducible** on Excalidraw + Chromium on Wayland

All apps run unmodified from Flathub.

**Comment by saghul** [comment]
In that case there is nothing we can do.

**Comment by maymage** [comment]
Apart from bringing the issue up upstream, I suppose. 

Excalidraw, Electron, Chromium, Gnome? What do you think?

**Comment by saghul** [comment]
Great question :-) 

What happens on Firefox on Wayland? If it works I'd say Chrome, otherwise it could be GNOME, you could also try to reproduce it with a different desktop environment.

I'm closing this, but feel free to comment on your further finds for reference.

**Comment by maymage** [comment]
Filed against Chromium 

https://bugs.chromium.org/p/chromium/issues/detail?id=1407092
