### ISSUE TITLE
Jitsi video and audio not working when auth mode is JWT and there are 2+ participants in a room

### ISSUE THREAD

**Issue by gogent01** [jitsi/jitsi-meet#12767]
Hello!
When I enable token auth mode, any first connection to a room is OK. But when a second participants joins, neither participant can see or hear another. Switching camera and microphone on/off does not help.

When second participant joins, Strophe error appears in console of the first participant: "TypeError: JSON.stringify cannot serialize cyclic structures" (screenshots below). Prosody logs are ok.

There's no such problem in auth modes "anonymous" or "internal_hashed". Also no problem in "token" mode when entering without JWT (with `allow_empty_token=true` in Prosody config) — anybody who joins without JWT can see and hear each other, but not those who joins with JWT.

Console ouptut:
<img width="809" alt="Screenshot 2023-01-12 at 14 16 46" src="https://user-images.githubusercontent.com/52747644/212054811-c20b9026-0928-4c46-a7c7-ff07c4baee8a.png">
<img width="809" alt="Screenshot 2023-01-12 at 14 16 56" src="https://user-images.githubusercontent.com/52747644/212054823-e2dc52b8-605b-49e4-b2f0-bb15f574387b.png">
<img width="809" alt="Screenshot 2023-01-12 at 14 17 07" src="https://user-images.githubusercontent.com/52747644/212054824-a2bf078e-bca6-41e3-9263-3177cf38cd12.png">
<img width="809" alt="Screenshot 2023-01-12 at 14 17 53" src="https://user-images.githubusercontent.com/52747644/212054828-0fcbea0b-5656-4e5f-a7c7-fa2c8afd0596.png">

Prosody logs:
<img width="1085" alt="Screenshot 2023-01-12 at 14 21 57" src="https://user-images.githubusercontent.com/52747644/212054902-85d74b94-ef9d-4784-9673-5dda00ccdcb2.png">

Can you please help me out?

**Comment by saghul** [comment]
Hey there! What Jitsi Meet version (all components) are you running?

**Comment by gogent01** [comment]
This is what i get with `dpkg -l | grep jitsi`:
```
jitsi-meet: 2.0.7882-1
jitsi-meet-prosody: 1.0.6644-1
jitsi-meet-tokens: 1.0.6854-1
jitsi-meet-web: 1.0.6644-1
jitsi-meet-web-config: 1.0.6644-1
jitsi-videobridge2: 2.2-45-ge8b20f06-1
```

The OS of server is Ubuntu 22.04.1 LTS

**Comment by gogent01** [comment]
I did not find a solution except for completely uninstalling jitsi and reinstalling it again, according to instructions from [here](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/). Now jwt authorization works fine with following versions of components:
```
jitsi-meet: 2.0.8218-1
jitsi-meet-prosody: 1.0.6918-1
jitsi-meet-tokens: 1.0.6918-1
jitsi-meet-web: 1.0.6918-1
jitsi-meet-web-config: 1.0.6918-1
jitsi-videobridge2: 2.2-67-gc7f2b2d5-1 
```

**Comment by saghul** [comment]
Good to hear you got it working!
