### ISSUE TITLE
Jitsimeet not working on webview IOS

### ISSUE THREAD

**Issue by taihoa** [jitsi/jitsi-meet#12764]
I am trying to open jitsi website on a webview,

if I open it in the Safari builtin browser, it works fine.

if I open it in a Webview inside application, it said "It looks like you're using a browser we don't fully support"

is not it supposed the Webview uses Safari by default? then, why Safari works, while the Webview is not supported?

**Comment by saghul** [comment]
It should work, yes. What iOS version are you using? Are you overriding the UA string by any chance?

**Comment by taihoa** [comment]
> I using IOS version 15.7. I tried overriding the UA string to 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36' But it work only on iphone not work on ipad.
> 
> Have you the UA string work good for IOS?



> It should work, yes. What iOS version are you using? Are you overriding the UA string by any chance?

I using IOS version 15.7.
I tried overriding the UA string to 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'
But it work only on iphone not work on ipad.

Have you the UA string work good for IOS?

**Comment by taihoa** [comment]
> It should work, yes. What iOS version are you using? Are you overriding the UA string by any chance?

I using IOS version 15.7.
I tried overriding the UA string to 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'
But it work only on iphone not work on ipad.

Have you the UA string work good for IOS?

**Comment by empongpat** [comment]
I am encountering this problem too with iOS version 16.2. Opening the Jitsi Meet via WebView too and didn't override any user-agent. There might be a false detection in this part:
<img width="510" alt="Screenshot 2023-01-30 at 12 45 54" src="https://user-images.githubusercontent.com/2202516/215397158-c285edbc-54d9-402c-8c42-2d49a521f92e.png">

**Comment by saghul** [comment]
What UA string are you presenting?

That check is for the legacy IE 11 so not relevant here.

**Comment by mokkymiah** [comment]
Did anyone find a solution to this?

**Comment by ealbers** [comment]
same issue

**Comment by dlatikaynen** [comment]
Why has this been closed? It is an active issue, the problem still persists and our users don't understand what's going on and why we can't solve it because it works on some iPhones but not on some iPad with comparable iOS version.

**Comment by GalensGan** [comment]
same issue +1, hope to resolve

**Comment by GalensGan** [comment]
> I think this is due to incorrect browser detection. Ping @hristoterezov

Yes，you are correct，I resolved this issue by the arctile [jitsi not supported in IOS xamarin webview](https://stackoverflow.com/questions/72526457/jitsi-not-supported-in-ios-xamarin-webview)
When I append ` Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0` to the webview UserAgent，it works well
