### ISSUE TITLE
Knocking list buttons on native obscure moderately long names

### ISSUE THREAD

**Issue by nbeckindy** [jitsi/jitsi-meet#12762]
### Description:

The buttons in the knocking list (Admit, Chat, Reject) on native devices obscure the names of those in the lobby if their names are moderately long.

### Steps to reproduce:

1. Enable Lobby on a meeting from a mobile device.
2. Join the meeting with a moderately-long name.

### Expected behavior:

Ideally, it would be nice to see the entire name. Possibly the buttons could be smaller or bumped down to another line.

### Actual behavior:

![image](https://user-images.githubusercontent.com/9885067/211860864-f02f6fc0-5336-4cd6-87dc-50048ef86366.png)

### Client information:

- App version: 22.7.1
- Operating System: iPhone & Android

**Comment by saghul** [comment]
@Calinteodor Can we put the buttons in "a second line" please?

**Comment by Calinteodor** [comment]
Will tackle this for sure.

**Comment by Calinteodor** [comment]
@saghul @nbeckindy New notifications on mobile have been added. They will be available, pretty soon, in the new release.
Thank you for your patience!
