### ISSUE TITLE
 Unpin all no longer working

### ISSUE THREAD

**Issue by Salocin42** [jitsi/jitsi-meet#12778]
### Description:

We often use follow me to switch between “one person pinned” and “show dominant speaker”. This is no longer possible in the current version (also on meet.jit.si)

Generally there seem to be problems with unpinning. No matter how many people can be pinned according to the new setting (1-6). It is no longer possible to be unpinned remotely via follow me and also not via the api.

If on the client the tileview is briefly switched on and off again the info who should be pinned is however correctly updated.

### Steps to reproduce:

1.  Pin someone
2. `api.executeCommand('pinParticipant',null)`

gives the error message “Trying to pin a non-existing participant with pin-participant command.” and the client is still pinned

OR

1. enter a meeting with 3 clients (A,B,C)
2. switch on "follow me" on A
3. click on B in the flimstrip of A to pin it
4. click again on B to unpin him

B is unpinned on A, but remains pinned on C

### Server information:

```
apt show jitsi-meet
Package: jitsi-meet
Version: 2.0.8194-1
```
And meet.jit.si (2023-01-12)

### Client information:

- Browser / app version: Chrome/Edge/Firefox
- Operating System: Windows 11

**Comment by saghul** [comment]
@horymury Can you please look into this?

**Comment by Salocin42** [comment]
Have now tested the new version 2.0.8252 (2023-01-30). 
Generally the problem exists there too, but if 
`disableStageFilmstrip: true `
is set, unpinning via the UI works again:
1. enable follow me
2. click on someone in the movie strip pins the participant to all users
3. click a second time on the picture unpins the user from all users

But unpin with 
`api.executeCommand('pinParticipant',null)`
still does not work despite this option.

A version where it still works is 2.0.7648 (2022-08-11)

**Comment by Arshlan-Raza** [comment]
i want to contribute in this , can you please assign it to me

**Comment by shivam2562001** [comment]
As I can see no one working on it, So I going to work on it.  let me know if anyone else working on it.

**Comment by horymury** [comment]
I'll also have a look today

**Comment by shivam2562001** [comment]
unfortunately, This project cannot be install over windows and I only have 8gb ram system so I think I cannot contribute.

**Comment by horymury** [comment]
Created PR with a fix for pin/unpin when follow-me is active. Now unpinning will unpin for all
