### ISSUE TITLE
Missing config.flags in config.js

### ISSUE THREAD

**Issue by emrahcom** [jitsi/jitsi-meet#12788]
### Description:

`config.flags` is not initialized in `config.js` after a new installation. So `javascript` fails while setting a subatrribute such as `config.flags.sourceNameSignaling`

### Steps to reproduce:

1. Install `jitsi` on a fresh server
2. Check the browser log for `Uncaught TypeError: Cannot set properties of undefined (setting 'sourceNameSignaling')`
3. Or check `/etc/jitsi/meet/domain-config.js` for the missing initialization

### Expected behavior:

`config.flags = config.flags || {};` should be in `/etc/jitsi/meet/domain-config.js` before setting any subattribute

### Actual behavior:

No initialization and `javascript` code fails

### Server information:

- Jitsi Meet version: 
```
jitsi-meet            2.0.8218-1
jitsi-meet-prosody    1.0.6918-1
jitsi-meet-turnserver 1.0.6918-1
jitsi-meet-web        1.0.6918-1
jitsi-meet-web-config 1.0.6918-1
```
- Operating System: `Debian 11 Bullseye`

### Client information:

- Browser / app version: `Chrome 109.0.5414.74`
- Operating System: `Debian 11 Bullseye`

### Additional information:

There is no `config.flags.sourceNameSignaling` in the default [config.js](https://github.com/jitsi/jitsi-meet/blob/master/config.js). So [the following line](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst#L181) which is in postinst script always fails and cannot add the initialization

https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst#L181

`sed` cannot find a string to replace

**Comment by damencho** [comment]
Yep, will take a look tomorrow :(

**Comment by damencho** [comment]
Not really, I think.

**Comment by saghul** [comment]
We could put them, with a comment mentioning they are no longer useful, expect for legacy mobile clients, so we'll keep them around for a while.

Sometimes the simplest option is the best 😅  I'll create a PR.
