### ISSUE TITLE
iOS Keyboard is overlapping the chat text field

### ISSUE THREAD

**Issue by bonninf** [jitsi/jitsi-meet#12785]
### Description:

The JitsiMeetSDK has been integrated into an iOS Swift app and is working fine. However when launching the chat feature and trying to write a new message, the keyboard is overlaping the text field.

### Steps to reproduce:

1. In the iOS app join a new meet
2. Tap the Chat button
3. Tap in the text field such as the keyboard is shown --> the keyboard is completely overlapping the text field 
4. Close the Chat view
5. Tap the Chat button to open the chat view again
6. Tap in the text field such as the keyboard is shown --> This time the keyboard is partially overlaping the text field

### Expected behavior:

The text field should always be visible and should be moved above the keyboard.

### Actual behavior:

First time the Chat view is shown the text field is fully overlapped by the keyboard.
The following times that the Chat view is shown then the text field is partially overlapped by the keyboard.

We can see on the screenshot that the navigation bar is wider the first time the chat view is displayed than the following times.

![Simulator Screen Shot - iPhone 12 - 2023-01-16 at 10 07 28](https://user-images.githubusercontent.com/1090995/212661564-fba8c907-6ec5-41d7-b12f-bc757ca1739d.png)
![Simulator Screen Shot - iPhone 12 - 2023-01-16 at 10 07 48](https://user-images.githubusercontent.com/1090995/212661596-377e8247-e10b-4652-9062-8bef5d77e900.png)
![Simulator Screen Shot - iPhone 12 - 2023-01-16 at 10 08 40](https://user-images.githubusercontent.com/1090995/212661648-3e2ebee2-e899-4b23-8fdf-298fa554ffd7.png)

 

### Client information:

- app version: pod 'JitsiMeetSDK', '6.2.1'
- Operating System: iOS 12 --> 16

### Additional information:

Reproduced with both emulator and iOS devices.

**Comment by saghul** [comment]
Ha you tested the latest version? That would be 7.0.1 at this time.

**Comment by bonninf** [comment]
With the latest versions including 7.0.1, I encoutered the following compatibility error: 
"Failed to build module 'JitsiMeetSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK."

I have some project constraints which prevent me to upgrade my Xcode version and I don't think I can fix this build error without upgrading Xcode. I'm using Xcode Version 13.2.1 (13C100).

Do you know if a correction betwen JitsiMeetSDK 6.1.0 and 7.0.1 could be to fix the overlapping issue?

**Comment by saghul** [comment]
We made some fixes to fix this yeah. Can you confirm @Calinteodor ?

**Comment by Calinteodor** [comment]
The screenshots are not related to the latest version. And yes, there are alot of fixes implemented. 
It needs an update.

**Comment by bonninf** [comment]
The issue occurs with the latest jitsi-meet-ios-sdk-releases  release 9.2.2
Tested within several devices:
- iPhone 8 iOS 16.7.8
- iPhone XR iOS 16.0
- Simulator iPhone 15 Pro iOS 17.4

![image](https://github.com/jitsi/jitsi-meet/assets/1090995/9709e37b-3358-4d8c-ae72-98c2b3913bfc)

**Comment by saghul** [comment]
What is that red banner?
