### ISSUE TITLE
Notification sounds ignore output device settings

### ISSUE THREAD

**Issue by pbirkants** [jitsi/jitsi-meet#12783]
### Description:

Changing the output device in Jitsi settings affects only call audio instead of all sounds emitted by Jitsi.

This seems counter-intuitive, especially when embedding Jitsi via IFrame API and controlling device selection externally.

### Steps to reproduce:

1. Start a new meeting.
2. Open Jitsi sound settings, select a non-default output device, play test sound.
3. Close settings.
4. Trigger any sound in Jitsi UI, e.g. by sending a reaction or joining the meeting in another browser tab.

### Expected behavior:

All sounds are played via selected output  device.

### Actual behavior:

Only the sound test tone and actual call audio is played through the selected device. Other UI sounds are played through the default output device.

### Server information:

Reproducible on https://meet.jit.si/

### Client information:

I'm using Chromium 108 on Debian sid, but, looking at the source code, this is not implemented and not a browser issue.

**Comment by anikdhabal** [comment]
please assign me to this issue.

**Comment by saghul** [comment]
You are welcome to work on a fix, we don't "assign" issues per se here.

**Comment by code0monkey1** [comment]
Could not reproduce it.  All sounds ( Voice / Polls created ) came through the connected Bluetooth headset. 

[Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (x86_64)](https://brave.com/latest/)

Am I missing something  ? Has this already been fixed ?

**Comment by saghul** [comment]
I think the problem is reproducible if you change the device inside Jitsi but leave the default to be a different one.

**Comment by horizenight** [comment]
> code0monkey1

change your output from headphones to speakers and then it will be reproducible.

**Comment by horizenight** [comment]
@saghul I have gone through the docs and set up everything on my computer. I am not sure where I should begin in order to resolve this issue. Could you please help me out? I am struggling to find the find the folder where code for this is written. Thank you

**Comment by Bhavya-Desai** [comment]
Hi, I am currently trying to fix this issue.

**Comment by mashukur-rahman** [comment]
@Bhavya-Desai  Hi, Are you still working on it? Otherwise I would like to work on this issue. Thank you.

**Comment by saghul** [comment]
AFAIK nobody is working on this issue.

**Comment by Nith567** [comment]
Does anyone working on this issue

**Comment by saghul** [comment]
This has been fixed already and it's applied in master.
