### ISSUE TITLE
videoContainerFocused css-class not set (participant.pinned not longer valid?)

### ISSUE THREAD

**Issue by psi-4ward** [jitsi/jitsi-meet#12790]
In [Thumbnail. _getContainerClassName()](https://github.com/jitsi/jitsi-meet/blob/817a05cf7b306a288488c4c5d4269ab4e64f311a/react/features/filmstrip/components/web/Thumbnail.tsx#L881) `participant.pinned` gets used to derive the pinned state but this was reworked to active-pinned-participants from the filmestrip wasn't it?

Using `state['features/filmstrip'].activeParticipants[].pinned` is also used for the [PinnedIndicator](https://github.com/jitsi/jitsi-meet/blob/master/react/features/filmstrip/components/web/PinnedIndicator.tsx#L60)

So if the pinned-code from base/participants obsolete or can anyone clarify the things?

**Comment by robertpin** [comment]
This was changed with the introduction of stage filmstrip (multiple participants on stage). So now by default the pinned participants are here `state['features/filmstrip'].activeParticipants[].pinned`. However, if you disable stage filmstrip (`config.filmstrip.disableStageFilmstrip=true`) the old way to pin participants is used (`participant.pinned`)

**Comment by robertpin** [comment]
This was changed with the introduction of stage filmstrip (multiple participants on stage). So now by default the pinned participants are here `state['features/filmstrip'].activeParticipants[].pinned`. However, if you disable stage filmstrip (`config.filmstrip.disableStageFilmstrip=true`) the old way to pin participants is used (`participant.pinned`)

**Comment by psi-4ward** [comment]
Ahh thanks @robertpin so there is missing code for `activeParticipants`? 

```typescript
    // old 
    // if (_thumbnailType !== THUMBNAIL_TYPE.TILE && _participant?.pinned) {
       
        if (_thumbnailType !== THUMBNAIL_TYPE.TILE
            && (_activePinnedParticipants.includes(participantId) || _participant?.pinned)
        ) {
            className += ' videoContainerFocused';
        }
```

**Comment by robertpin** [comment]
Not really. The class `videoContainerFocused` was used by some tests and that's why we didn't remove it. However I think that the tests were updated and we can remove this css class

**Comment by psi-4ward** [comment]
We use it for styling but you can also remove it - we produce our own builds anyways :)
