### ISSUE TITLE
Self view very dark

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#12796]
### Description:

Self view appears too dark

### Steps to reproduce:

Open meeting in meet.jit.si or beta.meet.jit.si or alpha.jitsi.net

### Expected behavior:
<img width="137" alt="image2" src="https://user-images.githubusercontent.com/32515675/213128461-d451014f-457a-435a-aa2c-7bf1f292c93c.png">
<img width="153" alt="imagem4" src="https://user-images.githubusercontent.com/32515675/213129009-ad66efa4-80db-40e7-96ca-400e0c65e7fe.png">

### Actual behavior:

<img width="140" alt="image1" src="https://user-images.githubusercontent.com/32515675/213128521-769baa08-cad7-47c2-a3c2-0ff65374f005.png">
<img width="210" alt="image3" src="https://user-images.githubusercontent.com/32515675/213128775-506bcfaa-5717-4ae0-8973-cae7f3cc1652.png">

### Client information:

- Browser / app version: Google Chrome 109, Firefox 109, Safari 16.2
- Operating System: macOS 12.6.2

**Comment by saghul** [comment]
Hey there!

That is intentional. We are bringing back a behavior that got lost at some point: the thumbnails of the participants in the large view (on stage) are dimmed so it's easier to see who is on stage in a large meeting.

**Comment by saghul** [comment]
Interesting point, we'll take a look.

**Comment by SatyarajRana** [comment]
Hey @saghul , I've wanted to start contributing to jitsi meet for quite some time now but need guidance on where to start, as I'm new to Open Source, could you please help me out?

**Comment by saghul** [comment]
HI @SatyarajRana , love the enthusiasm! I am very sorry but right now we are swamped and bringing someone up to speed requires an effort we currently can't spend much time on.

@dudumanbogdan I think you implemented this, right? Maybe you can take a look / provide some guidance?

**Comment by SatyarajRana** [comment]
@saghul , I understand, will Jitsi be coming to GSoC this year?

**Comment by saghul** [comment]
Not this year.

**Comment by dudumanbogdan** [comment]
@SatyarajRana the changes for tint background have been added in this PR https://github.com/jitsi/jitsi-meet/pull/12584/files . I did lots of tests and didn't find an issue.

From what I remember, we are adding the tint background if the filmstrip type is main view, layout is not TILE_VIEW and if participant is active or displayed currently on large video. 

Based on the print-screens, the screen share is on main screen  so it's normal the tint and the participant speaking is active and this is the reason it also got a tint.

@saghul , @SatyarajRana  probably we want to extend the logic that if the person is sharing the screen, is on main screen, even if it's active person, to not show the tint for him? 
Or to decrase the opacity / change the color of this tint?

The logic is in `Thumnail.tsx`, if you need to debug and see what's in redux just enter in Browser console - `APP.store.getState()` (for example to see the store data for large-video, use this `APP.store.getState()['features/large-video']`

**Comment by jluisfa** [comment]
@dudumanbogdan  The goal was, when sharing the screen, make the Self View clear, in order to better see the speaker.

**Comment by jluisfa** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/12944
Thank you very much @saghul, @dudumanbogdan and @jallamsetty1
