### ISSUE TITLE
Add Some Features in the Chat

### ISSUE THREAD

**Issue by anikdhabal** [jitsi/jitsi-meet#12795]
### _Is your feature request related to a problem you are facing?_

There are no chat disable option in jitsi meet. It would be better if this feature is add. This feature  stop chat spamming in important meeting.
Apart from this if there is a feature  like someone can directly send message to the moderator without showing other.

### Describe the solution you'd like

I would like to add chat Disable feature in jitsi meet and also an option in the chat section that someone could send a direct message to the moderator or he/she can post in publically.

**Comment by damencho** [comment]
> direct message to the moderator or he/she can post in publically.

This is already possible use 3 dot menu for the person you want to message.

**Comment by anikdhabal** [comment]
@damencho  yeah i understand but what,s about chat disable feature.It should be added.

**Comment by damencho** [comment]
I don't think this will be useful for the majority of users. So however wants to disable it, can do it with a param in the url. I don't see such a param though so that can be added.

**Comment by Jaya-sys** [comment]
Hey I would like to work on this feature?
