### ISSUE TITLE
waitForOwnerDialog appears after successful authorization

### ISSUE THREAD

**Issue by W0olFy** [jitsi/jitsi-meet#12806]
### Description:

When you press "Login" button on loginDialog it hides itself immediately, and waitForOwnerDialog appears after you saw "CONFERENCE FAILED: conference.authenticationRequired" error in browser console, but authorization process is not finished yet... If user do nothing, he will be moved to conference and waitForOwnerDialog will close, but usually users think that they do something wrong and trying to authorize one more time. Confusing..

### Steps to reproduce:

1. Configure [secure domain](https://jitsi.github.io/handbook/docs/devops-guide/secure-domain/) and authorization (ldap for example)
2. Create new conference
3. Press "Join meeting" button
4. Press "I am the host" button
5. Input your login/password (do not press "Login" button)
6. Wait for "CONFERENCE FAILED: conference.authenticationRequired" error appears in browser console
7. Count to 3 or 4
8. Press "Login" button

You should see waitForOwnerDialog appears, but authorization process is in progress.

### Expected behavior:

loginDialog shows status of authorization process and closes when finished

### Actual behavior:

waitForOwnerDialog appears after successful authorization

### Server information:

- Jitsi Meet version:

- jitsi-meet 2.0.8218-1        
- jitsi-meet-prosody 1.0.6918-1        
- jitsi-meet-turnserver 1.0.6918-1        
- jitsi-meet-web 1.0.6918-1        
- jitsi-meet-web-config 1.0.6918-1        
- jitsi-videobridge 22.2-67-gc7f2b2d5-1

- Operating System: Ubuntu Server 22.04

### Client information:

- Browser / app version: Google Chrome 109.0.5414.87
- Operating System: MacOS 

### Additional information:

To correct this bug, please add `disableAutoHideOnSubmit = { true }` after or before this line: https://github.com/jitsi/jitsi-meet/blob/507d88350320521de51d27f908b6708fb14f278d/react/features/authentication/components/web/LoginDialog.tsx#L256

**Comment by saghul** [comment]
> To correct this bug, please add `disableAutoHideOnSubmit = { true }` after or before this line:

Not sure that's the right fix, because the dialog shows the auth pogress in a text line, doesn't it? We might have broken that with the dialogs refactoring.

**Comment by W0olFy** [comment]
> > To correct this bug, please add `disableAutoHideOnSubmit = { true }` after or before this line:
> 
> Not sure that's the right fix, because the dialog shows the auth pogress in a text line, doesn't it? We might have broken that with the dialogs refactoring.

Patched it in `app.bundle.min.js` and bug is gone. Before, loginDialog just close immediatly after "Login" button was pressed. Now it works as expected, showing authorization status while it is in progress and closes right after it finishes. 
In previous versions, before dialog refactoring, `Event.preventDefault()` method was used and all was working.

**Comment by saghul** [comment]
Ah, sorry I got it backwards. You are right. Would you like to send a PR?

**Comment by W0olFy** [comment]
> Ah, sorry I got it backwards. You are right. Would you like to send a PR?

https://github.com/jitsi/jitsi-meet/pull/12808

Done, Thanks!
