### ISSUE TITLE
Whats the diference between JitsiMeetSDKLite and JitsiMeetSDK?

### ISSUE THREAD

**Issue by GleidsonDaniel** [jitsi/jitsi-meet#12804]
### Additional information:

I saw the two sdks deployed in the iOS repo but I couldn’t find the difference between them anywhere.

**Comment by saghul** [comment]
The Lite version trades some "heavy" dependencies, like Google SignIn and Giphy for size.

**Comment by GleidsonDaniel** [comment]
> The Lite version trades some "heavy" dependencies, like Google SignIn and Giphy for size.

Thanks for the quick response.
