### ISSUE TITLE
Show name when participants join

### ISSUE THREAD

**Issue by anikdhabal** [jitsi/jitsi-meet#12809]
**Is your feature request related to a problem you are facing?**
No

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
Add a feature to show name when participants join. It would be good when name is pop up when participants join the meeting.

**Comment by saghul** [comment]
This is already the case, there a notification.

However, if multiple participants join in a short amount of time we change the text to "X participants joined" to avoid having tons of notifications.
