### ISSUE TITLE
New local recording stops immediately after starting if a previous recording hit the limit

### ISSUE THREAD

**Issue by sethp** [jitsi/jitsi-meet#12810]
### Description:

To record a longer call, my friend & I attempted to create several smaller recordings to stay under the 1GB limit. Unfortunately, this didn't work: he had to leave and re-join our call in order to start new recordings.

### Steps to reproduce:

1. Start local recording
2. Record for long enough to exceed the size limit
3. Try to start a new local recording

### Expected behavior:

The next 1GB of the call will be recorded into a new file.

### Actual behavior:

The 1GB limit seems to be per-session rather than per-recording: we actually tried at the 45 minute mark to stop & start the recording, and we only got about 15 more minutes (to 1 hour total) before the recording announced it stopped. Thereafter, when he tried to start a new recording, it would immediately stop.

### Client information:

- Browser / app version: Chrome, I think: a recent one
- Operating System: macOS

### Additional information:

I wonder if `stopLocalRecording()` should be resetting `this.totalSize` to `1073741824` bytes? It looks like it currently doesn't:

https://github.com/jitsi/jitsi-meet/blob/2c59b44df549f229f1d71de2b249381a699faa52/react/features/recording/components/Recording/LocalRecordingManager.web.ts#L158-L166

So the only way to reset the "size remaining" amount there is to re-initialize the object, i.e. leave and rejoin the call.

**Comment by saghul** [comment]
@robertpin can you please take care of this?
