### ISSUE TITLE
RHEL 7.2 + IE 11: microphone issues

### ISSUE THREAD

**Issue by flippolis** [jitsi/jitsi-meet#1281]
I have installed Jitsi Meet on a CentOS 7.2 machine and configured manually all the services. I experience an error using the microphone when trying to open a room with IE 11 with the Temasys plugin installed. Following is a screenshot:

![jitsi-meet](https://cloud.githubusercontent.com/assets/1741073/22468464/a4545ece-e7c8-11e6-9eb8-d8c0c724cde9.png)

I only need a video conference between two persons, no need for the microphone. Any chances to disable it from a configuration file or any other solution? Thank you.

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems before opening issues.

Webrtc will not work when using https, you need to make sure your deployment is using https.
