### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNGestureHandlerRootView" was not found in the UIManager.

### ISSUE THREAD

**Issue by karan-appgambit** [jitsi/jitsi-meet#12822]
Invariant Violation: requireNativeComponent: "RNGestureHandlerRootView" was not found in the UIManager.

This error is located at:
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:23)
    in GestureHandlerRootView (at StackView.tsx:429)
    in StackView (at createStackNavigator.tsx:121)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:713)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createStackNavigator.tsx:120)
    in StackNavigator (at app-stack.js:14)
    in AppStack (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:281)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:279)
    in RCTView (at View.js:32)
    in View (at CardSheet.tsx:45)
    in CardSheet (at Card.tsx:557)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at Card.tsx:536)
    in PanGestureHandler (at GestureHandlerNative.tsx:14)
    in PanGestureHandler (at Card.tsx:530)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at Card.tsx:526)
    in RCTView (at View.js:32)
    in View (at Card.tsx:520)
    in Card (at CardContainer.tsx:219)
    in CardContainer (at CardStack.tsx:663)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:266)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:169)
    in DelayedFreeze (at src/index.native.tsx:265)
    in InnerScreen (at src/index.native.tsx:445)
    in Screen (at Screens.tsx:38)
    in MaybeScreen (at CardStack.tsx:655)
    in RNSScreenContainer (at src/index.native.tsx:343)
    in ScreenContainer (at Screens.tsx:20)
    in MaybeScreenContainer (at CardStack.tsx:566)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at CardStack.tsx:564)
    in CardStack (at StackView.tsx:437)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:87)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at StackView.tsx:430)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:23)
    in GestureHandlerRootView (at StackView.tsx:429)
    in StackView (at createStackNavigator.tsx:121)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:713)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createStackNavigator.tsx:120)
    in StackNavigator (at root.js:27)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at root.js:26)
    in App (at root.js:42)
    in AppContainer (created by Connect(AppContainer))
    in Connect(AppContainer) (at App.js:22)
    in RCTView (at View.js:32)
    in View (at App.js:21)
    in App (at nexus-react-native/index.js:19)
    in PersistGate (at nexus-react-native/index.js:18)
    in Provider (at nexus-react-native/index.js:17)
    in defaultRedux (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in AwesomeProject(RootComponent) (at renderApplication.js:60)

### Description:

I have react native project with native jitsi meet sdk (android and ios) 
recently i upgrade jitsi meet android sdk from 3.+ to 5.0.2 and react native version 0.63.4 to 0.66.4 
and when i try to run app it show above error in android 
 
case 1 : when I remove jitsi completely app work fine (jitsi not work)
case 2 : when I remove react navigation code app work fine with jitsi code (navigation not work)
case 3 : with both jitsi and react navigation app show above error 

here is complete package.json of my project 
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/hooks": "^2.8.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/toolbar-android": "0.2.1",
    "@react-navigation/drawer": "^6.5.7",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/stack": "^6.3.11",
    "kuzzle-sdk": "^7.4.0",
    "moment": "^2.29.3",
    "native-base": "^2.13.14",
    "path": "^0.12.7",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-a-beep": "^1.1.0",
    "react-native-agora": "3.3.2",
    "react-native-camera": "^4.2.1",
    "react-native-device-info": "^7.0.2",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^2.2.1",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-intent-launcher": "^0.2.1",
    "react-native-material-dialog": "^0.7.7",
    "react-native-nfc-manager": "^2.3.1",
    "react-native-orientation": "^3.1.3",
    "react-native-prompt-android": "^1.1.0",
    "react-native-reanimated": "^1.13.3",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-serial-port-api": "^1.1.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-splash-screen": "^3.2.0",
    "react-native-sqlite-2": "^3.5.2",
    "react-native-tts": "^3.2.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-view-pdf": "^0.13.2",
    "react-native-webview": "^11.26.0",
    "react-native-webview-invoke": "^0.6.2",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.24",
    "@types/react": "^17.0.16",
    "@types/react-native": "^0.64.12",
    "@types/react-native-vector-icons": "^6.4.8",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

**Comment by saghul** [comment]
What Jitsi Meet RN plugin are you using?

**Comment by karan-appgambit** [comment]
@saghul I'm using android sdk version 5.0.2

**Comment by saghul** [comment]
That is quite old, I'd suggest you update to 7.0.1.
