### ISSUE TITLE
Entering in a call using jwt not working - iOS SDK

### ISSUE THREAD

**Issue by GleidsonDaniel** [jitsi/jitsi-meet#12835]
### Description:
Currently I have a url something like this: `https://SERVER_URL/ROOM_NAME?TOKEN#SOME_CONFIGS`
I have taken these properties and am passing them to the SDK manually:
```
  JitsiMeetConferenceOptions *options = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
      builder.serverURL = [NSURL URLWithString:@"SERVER_URL"];
      builder.room = @"ROOM_NAME";
      builder.audioOnly = YES;
      builder.token = TOKEN;
      builder.userInfo = userInfo;
      builder.setFeatureFlag = SOME_FLAGS;
  }];

  [jitsiMeetView join:options];
```
But when entering these rooms he is always asking me to authenticate ...
However, if I use the deep link by opening a url in the browser and opening it directly in the app, it works, without the need to pass all these properties from the builder.

Is there any method that works like the deeplink works, just pass the url and the sdk itself understands what to do?
Otherwise I'll have to parse the url, token, configs etc every time and that's a lot of work...

### Server information:

- Jitsi Meet version: iOS SDK 7.0.1
- Operating System:

### Client information:

- Browser / app version: Safari
- Operating System: iOS

**Comment by saghul** [comment]
Can you please gather the Xcode console logs?

**Comment by saghul** [comment]
You could pass the full URL in the `room` parameter too.

**Comment by GleidsonDaniel** [comment]
> Can you please gather the Xcode console logs?
Yes, I'll run the project again and let you know.

> You could pass the full URL in the `room` parameter too.
Like that?
```
  JitsiMeetConferenceOptions *options = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
      builder.room = @"https://SERVER_URL/ROOM_NAME?TOKEN#SOME_CONFIGS";
      builder.userInfo = userInfo;
  }];

  [jitsiMeetView join:options];
```

**Comment by saghul** [comment]
Yep, that should do.
