### ISSUE TITLE
Android outbound video broken in 22.7.0/22.7.1

### ISSUE THREAD

**Issue by hax0rbana-adam** [jitsi/jitsi-meet#12836]
# Problem
The Android version of the mobile app no longer works as of version 22.7.0.

# Details
The camera permissionis requested and granted. The user can see themselves on their screen and believe that other participants can see them. To other participants, it appears as though the Android user is not sharing video.

At first I though it was poor network connectivity, but it happens regardless of network conditions and video works fine in old versions of the app.

# Steps to reproduce
1. Install latest jitsi app on Android
2. Connect to a conference
3. Share your video
4. Ask if anyone can see your video

# Workarounds
Using a web browser on the same mobile device transmits video as expected.

Downgrading to 22.6.0 transmits video as expected.

# Testing environment
- Android 13
- GrapheneOS
- Jitsi app from F-droid
- Pixel 4a

**Comment by saghul** [comment]
Are you connecting to meet.jit.si or your own deployment?

**Comment by hax0rbana-adam** [comment]
I was connecting to my own deployment. I tested it on meet.jit.si and found that the latest Android app works there.

Any idea what changed in the 22.7.0 release that caused this incompatibility or what is needed to resolve it on the server side to get the latest Android app to work? I'm installing from the jitsi.org apt repo, the server running the latest version, and video works from all mobile and desktop browsers.

**Comment by saghul** [comment]
What version of the backend software are you running?

Please share your config.JS too.

**Comment by hax0rbana-adam** [comment]
Wow, this is embarrassing. :facepalm:  I was running jitsi-meet 2.0.7648-1 because my automatic update script didn't automatically bump me up to 2.0.8218-1. Once I updated to 2.0.8218-1, everything worked fine.

Thank you for taking the time to help me out and asking exactly the correct questions! :slightly_smiling_face:

**Comment by saghul** [comment]
I'm glad it's working for you now!
