### ISSUE TITLE
Can not view other people's screen share on the latest firefox/firefox-based 109 browsers

### ISSUE THREAD

**Issue by notmentaloutlaw** [jitsi/jitsi-meet#12841]
### Description:

When using firefox to access meet.jit.si it is possible to share your screen and also see what you are sharing. Other people in your meeting who are browsing via chrome or safari etc can see the screen shared content perfectly. However, should any of them use firefox/librewolf or anything similar it is not possible for them to see your screen. Likewise if the members of the conference who use chrome or another browser (thats not ff) chooses to share content, you on firefox would not be able to see it. I don't think this was an issue before but after the updates something may have changed. This has been detected on different distributions so its not distro specific.

### Steps to reproduce:

1. Get firefox 109 + and join a jitsi meeting
2. Open up another browser (can be another ff window) and share content
3. You will see on your firefox browser that you cant see what the other person is sharing

### Expected behavior:

Firefox users should be able to see screenshared content.

### Actual behavior:

Firefox users cant see screenshared content

### Further info:

Should there be anything else ask.

**Comment by saghul** [comment]
Can you reproduce this on meet.jit.si ?

**Comment by notmentaloutlaw** [comment]
Yes this was all on meet.jit.si

**Comment by notmentaloutlaw** [comment]
It appears that a flatpak installation of firefox 109 works. Which makes me wonder that when I used firefox and userjs as well as librewolf there could be some features blocked that prohibits meet.jit.si working properly. However, this is another issue. I will close this one.
