### ISSUE TITLE
IRC color characters break jitsi

### ISSUE THREAD

**Issue by kompowiec** [jitsi/jitsi-meet#12845]
### Description:

IRC color characters causes jitsi crash 

### Steps to reproduce:

enter some of these characters: 
to chat

### Expected behavior:

should works fine

### Actual behavior:

crash:
![break](https://user-images.githubusercontent.com/15860246/215470707-4b468623-efe9-4bfc-917b-0a8ff7deda21.png)

### Server information:

- Jitsi Meet version: meet.jit.si, jitsi.member.fsf.org and others
- Operating System: Unknown/Trisquel

### Client information:

- Browser / app version: Firefox 102.6.0esr 
- Operating System: Debian 11

**Comment by saghul** [comment]
Can  you please show the JS console output? Also, what characters are those? I'm looking at his in Firefox for macOS and see a broken character.

**Comment by kompowiec** [comment]
yea now i noticed that it was converted, so you have in base64:
Ah8dDwMwMAo=
or on graphic:
![hexchat](https://user-images.githubusercontent.com/15860246/215521807-ca31a73a-4718-4ccd-b85e-d31b689e278f.png)
also documentation:
https://modern.ircdocs.horse/formatting.html#characters

> Can you please show the JS console output?
i used browser console in firefox but no log showed up after inputting the character.

**Comment by saghul** [comment]
An you he the output when the connection failure happens?

**Comment by Kavish1802** [comment]
hey @saghul are you currently working on this issue mate?
