### ISSUE TITLE
install-letsencrypt-cert.sh seems broken

### ISSUE THREAD

**Issue by 1ma** [jitsi/jitsi-meet#12840]
### Description:

Executing the `install-letsencrypt-cert.sh` script produces an empty .crt file.

### Steps to reproduce:

1. $ sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh 

The output ends with:
```
...
[Sat 28 Jan 2023 04:12:26 PM UTC] Install success!
[Sat 28 Jan 2023 04:12:27 PM UTC] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat 28 Jan 2023 04:12:27 PM UTC] Single domain='jitsi.mydomain.dedyn.io'
[Sat 28 Jan 2023 04:12:27 PM UTC] Getting domain auth token for each domain
[Sat 28 Jan 2023 04:12:29 PM UTC] Getting webroot for domain='jitsi.mydomain.dedyn.io'
[Sat 28 Jan 2023 04:12:29 PM UTC] jitsi.mydomain.dedyn.io is already verified, skip http-01.
[Sat 28 Jan 2023 04:12:29 PM UTC] Verify finished, start to sign.
[Sat 28 Jan 2023 04:12:29 PM UTC] Lets finalize the order.
[Sat 28 Jan 2023 04:12:29 PM UTC] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/936672797/161518614907'
[Sat 28 Jan 2023 04:12:30 PM UTC] Downloading cert.
[Sat 28 Jan 2023 04:12:30 PM UTC] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03668313be226fc1a274f170815d3fbb3f43'
[Sat 28 Jan 2023 04:12:31 PM UTC] Cert success.
-----BEGIN CERTIFICATE-----
MIIEcDCCA1igAwIBAgISA2aDE74ib8GidPFwgV0/uz9DMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzAxMjgxNTEyMzBaFw0yMzA0MjgxNTEyMjlaMCYxJDAiBgNVBAMT
G2ppdHNpLmluc2F0d2V0cnVzdC5kZWR5bi5pbzBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABJlnOx2EzKmVOmrqnZPTW3CvQLMMP/X7GcLIK3GUM7sytD9YxLZiHu7H
nw7E4NSK1GGxvOeeYulJ09nEHES3O3ijggJVMIICUTAOBgNVHQ8BAf8EBAMCB4Aw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYD
VR0OBBYEFKqvTvhoZ+7ZvjTqeUSDd6+GS2JXMB8GA1UdIwQYMBaAFBQusxe3WFbL
rlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDov
L3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5v
cmcvMCYGA1UdEQQfMB2CG2ppdHNpLmluc2F0d2V0cnVzdC5kZWR5bi5pbzBMBgNV
HSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpo
dHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQMGCisGAQQB1nkCBAIEgfQEgfEA
7wB2ALc++yTfnE26dfI5xbpY9Gxd/ELPep81xJ4dCYEl7bSZAAABhfkm2CgAAAQD
AEcwRQIhAI63eRA7oT6cF1AfjAI0AvrJBpnoddV99k48OVG0+2k4AiAt1Tx6ZBD5
UsXUhw4G9pEPEBnmi+d9j8V8Sa7v5bd0RwB1AHoyjFTYty22IOo44FIe6YQWcDIT
hU070ivBOlejUutSAAABhfkm2EQAAAQDAEYwRAIgTmZ2xvSnb7a15C/8i3VxkSB6
THnXeO7+CEmwrXuXaFgCICh7/FL98Eq8M+rggvoLeugT4/VQd3DWvXEvaPXmc187
MA0GCSqGSIb3DQEBCwUAA4IBAQCIXExE8kpxre50jb7hLaU3HQr8nf42Gbq0Jo0n
C6EFOIwMKQn/bTmRuoFwmXxAgaHDVy8G2rW8iz3hdKTlhCiuy8wsbaXlVjKYtGt8
jLpOFZPMhs8wyrB/dnw4Xb//GjDF7IH1mgZ5GkMiWY9Y6B0O6QvITsZWOcy/xGAk
jj4FmXB+7P56h9vxfqSU6i4WHzsjS46dOv1h5fNl8SXmSAsd9N0KNIMEo/0+8Fde
A/80IrUp2nqf5feksQMvk3OWMDLsfW5/a2KDD6GSvRZZOub7RFaiKvsevIPd+l73
Z3NJnSVMB+446Mwv1iceF/nphRXWFgBldzDiCBoK0PL+Ws/H
-----END CERTIFICATE-----
[Sat 28 Jan 2023 04:12:31 PM UTC] Your cert is in: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io_ecc/jitsi.mydomain.dedyn.io.cer
[Sat 28 Jan 2023 04:12:31 PM UTC] Your cert key is in: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io_ecc/jitsi.mydomain.dedyn.io.key
[Sat 28 Jan 2023 04:12:31 PM UTC] The intermediate CA cert is in: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io_ecc/ca.cer
[Sat 28 Jan 2023 04:12:31 PM UTC] And the full chain certs is there: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io_ecc/fullchain.cer
[Sat 28 Jan 2023 04:12:31 PM UTC] Installing key to: /etc/jitsi/meet/jitsi.mydomain.dedyn.io.key
[Sat 28 Jan 2023 04:12:31 PM UTC] Installing full chain to: /etc/jitsi/meet/jitsi.mydomain.dedyn.io.crt
cat: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io/fullchain.cer: No such file or directory
```

2. $ echo $?
```
1
```

3. The certificate file is empty:

```
$ cd /etc/jitsi/meet/
$ ls -l
total 72
-rw-r--r-- 1 root root 65768 Jan 27 22:13 jitsi.mydomain.dedyn.io-config.js
-rw-r--r-- 1 root root     0 Jan 28 16:12 jitsi.mydomain.dedyn.io.crt
-rw------- 1 root root  1679 Jan 28 16:12 jitsi.mydomain.dedyn.io.key
```

### Expected behavior:

The full chain certificate is generated properly, nginx can load it and serves jitsi over a valid LetsEncrypt certificate.

### Actual behavior:

Running the script returns error code 1 and shows `cat: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io/fullchain.cer: No such file or directory`, and the certificate file in `/etc/jitsi/meet` is empty (nginx cannot even run).

### Server information:

- Jitsi Meet version: 2.0.8218-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Firefox
- Operating System: Ubuntu 22.04

**Comment by damencho** [comment]
While installing what did you chose - self signed or LE?

**Comment by 1ma** [comment]
Self-signed, and it worked. Then I ran the LE script manually because I wanted the Android app to work, too.

**Comment by damencho** [comment]
Strange I just tried it out and it worked without a problem. The only difference was I did not use sudo.

**Comment by damencho** [comment]
Yep, creating an account and installing using sudo again no problems. Every try was on a new VM 20.04. 
What do you have in `/opt/acmesh/.acme.sh/`? What about `/opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io/ `?

**Comment by damencho** [comment]
Did you have acmesh installed before installing jitsi-meet?

**Comment by damencho** [comment]
> [Sat 28 Jan 2023 04:12:31 PM UTC] Your cert is in: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io_ecc/jitsi.mydomain.dedyn.io.cer
> [Sat 28 Jan 2023 04:12:31 PM UTC] Installing full chain to: /etc/jitsi/meet/jitsi.mydomain.dedyn.io.crt
> cat: /opt/acmesh/.acme.sh/jitsi.mydomain.dedyn.io/fullchain.cer: No such file or directory

And this is strange, using different folders, it is nothing we control in the script... 

We use these two commands
https://github.com/jitsi/jitsi-meet/blob/42838e756c5540e6b48afe84b3e2f0d3316c16c4/resources/install-letsencrypt-cert.sh#L59
https://github.com/jitsi/jitsi-meet/blob/42838e756c5540e6b48afe84b3e2f0d3316c16c4/resources/install-letsencrypt-cert.sh#L62

You may find better help in acmes.sh forum on the subject.
