### ISSUE TITLE
When sharing video, participants in Tile View are not switched to normal mode

### ISSUE THREAD

**Issue by nbeckindy** [jitsi/jitsi-meet#12852]
### Description:

When using the Share Video feature, participants that were in Tile View when the video started remain in Tile View.

### Steps to reproduce:

1. Join a meeting with two participants.
2. Switch one participant to Tile View.
3. Have the other participant use Share Video.
4. For the first participant, they remain in Tile View and the shared video appears as another user with a thumbnail for the video.

### Expected behavior:

If a shared video starts, all remote participants should be swapped to normal mode to be able to see the video.

### Actual behavior:

Any remote participants that were in Tile View when the video started remain in Tile View. The shared video appears as another user with a thumbnail for the video. If they click on the user, the video is displayed in a LargeVideo, but it's not apparent that you should do this. If the participant sharing the video is in Tile View, they are switch to normal mode.

### Server information:

Jitsi Meet version: meet.jit.si & alpha.jisti.net

### Client information:

Appears to happen in browsers only. Native devices are fine.

**Comment by nbeckindy** [comment]
After some investigation, it seems the problem stems from the video-layout middleware, when handling the PIN_PARTICIPANT action. (This action is called when video sharing starts, because the newly-added share-video participant gets pinned.)

https://github.com/jitsi/jitsi-meet/blob/b4bf36323700da18893b92c35971109de68cabd7/react/features/video-layout/middleware.any.ts#L45-L56

In my local test, the getPinnedParticipant function always returns undefined here, so the _restoreTileViewState function is called every time. My local fix was just to get the participant off of the action object:

`const pinnedParticipant = action.participant;`

I'm not sure if there could be unintended consequences to this or if it's a viable solution.

**Comment by saghul** [comment]
@mihhu can you PTAL?
