### ISSUE TITLE
Pinning >1 participant doesn't work on native, including if moderator is followed

### ISSUE THREAD

**Issue by nbeckindy** [jitsi/jitsi-meet#12853]
I realize pinning is still experimental, so if you're already aware of this you can disregard. Thanks!

### Description:

Can't pin more than one participant in native Jitsi app. This means that when the moderator has "Everyone follows me" set, the moderator's pinning is not quite followed.

### Steps to reproduce:

1. Join a meeting with the Jitsi native app.
2. As a moderator in a browser, in Settings select "Everyone follows me" and allow more than one participant to be pinned.
3. As a moderator, pin a couple participants.

### Expected behavior:

The native app would work similarly to the browser and see multiple pinned participants.

### Actual behavior:

The native app only shows one pinned participant, the first one that was pinned by the moderator.

### Server information:

Tested on alpha.jitsi.net

### Client information:

Tested on native app version 22.7.1.

**Comment by damencho** [comment]
There are two fixes that went in today that probably will fix the problem, but mobile need to be updated with new version first.

**Comment by saghul** [comment]
Mobile doesn't yet support multi-pinning.
