### ISSUE TITLE
Audio does not belong to pc

### ISSUE THREAD

**Issue by cgri1** [jitsi/jitsi-meet#12858]
### Description:

Participant join a Conference. Participant mute or unmute the audio. When participant mute audio in a part of the conference, he or she see that the audio is muted but the other clients see that participant audio is unmuted. At the same time, they hear participant's voice. I analyze participant's log. And I found error that shows below.

modules/RTC/TraceablePeerConnection.js <Cl._assertTrackBelongs>:  TPCid=1,type=JVB removeTrack: track=LocalTrack10,audio does not belong to pc,

or 

[JitsiConference.js] <bh.replaceTrack>:  JitsiConference.replaceTrack oldTrack (LocalTrack[41,audio] does not belong to this conference
(anonymous) @ 625.min.js:2
[JitsiConference.js] <bh._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
[modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=dt44fmqr061rn] Replace track error: Error: Replace track failed - no transceiver for old: null, new: LocalTrack[59,audio]

### Expected behavior:

Other clients should not hear participant voice when participant muted audio.

### Actual behavior:

Other clients hear participant's voice

### Server information:

- Jitsi Meet version: 8044
- Operating System: MacOS

### Client information:

- Browser / app version: Chrome
- Operating System: MacOs

**Comment by saghul** [comment]
Are you able to reproduce this consistently?

**Comment by cgri1** [comment]
No, I came across this issue two times.

**Comment by HimanshuJakhmola356** [comment]
it is solved, i test it..

**Comment by codebeginer** [comment]
> 

I am also facing the same issue. How did you solved it?
