### ISSUE TITLE
Webcams of others only showed after enabling own

### ISSUE THREAD

**Issue by tiro-reflact** [jitsi/jitsi-meet#12865]
### Description:

For example: we have 2 Users: User A and B

User A and B joined a room without a camera. When User A starts their webcam, it is not displayed to User B until he also starts his webcam. This behavior appeared after we updated our Jitsi-Server to the latest version.

### Steps to reproduce:

1. Configure the Jitsi with startWithAudioMuted=true
2. At least 2 users join a room
3. One user starts their webcam and its not displayed for anyone until you start the webcam for yourself.

### Expected behavior:
When a user starts its webcam, it should automatically be shown to everyone.

### Actual behavior:
Webcam is not shown to others, until they start their webcam too.
(It is enough to start and stop it too see them in the future)

### Server information:

- Jitsi Meet version: 2.0.8252
- Operating System: Ubuntu 20.04.5

### Client information:

- Browser / app version: Safari Version 16.1 (18614.2.9.1.12) / Chrome Version 109.0.5414.119 / Firefox 109.0.1 
- Operating System: Macbook Air M1 - MacOS Ventura 13.0 (22A380)

### Additional information:

If you have any questions or anything is missing, just comment and I'll answer asap.

**Comment by saghul** [comment]
Are you able to reproduce this on meet.jit.si, by muting the camera before entering, in the prejoin screen?

**Comment by damencho** [comment]
Can you share your config.js ?

**Comment by tiro-reflact** [comment]
> Are you able to reproduce this on meet.jit.si, by muting the camera before entering, in the prejoin screen?

No, I couldn't. But I'm not sure if this is not reproducible, because at the moment you join, your camera gets activated in the tab already, weather you deactivate it afterwords or not. I'll send my config.js, maybe there's the mistake 🤷🏼‍♂️



> Can you share your config.js ?
https://pastebin.com/tMFjeAiU (07.02.2023 - expires in 1 Month)

**Comment by saghul** [comment]
```    // Start the conference in audio only mode (no video is being received nor
    // sent).
    startAudioOnly: true,
```

This is the expected behavior of audio-only mode. You only send or receive audio. When you enable your camera you implicitly disable this mode. But the other participant still needs to get out of audio only mode in order to receive it.

Generally speaking, it's not a good idea to have that as a default. Users can still opt into it in the prejoin screen, before actually joining.
