### ISSUE TITLE
meetFeatureFlags don't work 

### ISSUE THREAD

**Issue by Larens94** [jitsi/jitsi-meet#12866]
### Description:
When I pass the owner meet Feature Flags jitsi does not change anything.
For example:
   const meetFeatureFlags = {
         chatEnabled: false,
         ....
       };

I will disable the chat but I will show it this way.

- Jitsi Meet version:
   "react-native-jitsi-meet": "^2.3.1",

### Client information:

- Browser / app version:
-     "react-native": "0.70.6",

**Comment by saghul** [comment]
We are not the authors of react-native-jitsi-meet, I suggest you contact them instead.

**Comment by Larens94** [comment]
sorry, wrong repository
