### ISSUE TITLE
Add Names with their Icon In Share Meeting invitation

### ISSUE THREAD

**Issue by MohitBansal321** [jitsi/jitsi-meet#12867]
**Is your feature request related to a problem you are facing?**
Suppose I want to share meeting invitations on Gmail or direct email or outlook
when I want to share on Gmail if I should see their name so I do  fast
And the same case with other
![Normal Picture](https://user-images.githubusercontent.com/78220157/216781493-dee644a1-78f5-4dcb-9a1c-a7b1bef8ec5d.png)

**Describe the solution you'd like**
![After Change](https://user-images.githubusercontent.com/78220157/216781516-fe20f1d2-12a9-45a9-95e5-b20dc1695c13.png)
This is the only example
style it later

**Comment by saghul** [comment]
Our design team chose not to have labels.
