### ISSUE TITLE
IOS Build Directory Permission issues

### ISSUE THREAD

**Issue by charlesgigipo** [jitsi/jitsi-meet#12875]
### Description:
We are trying to use Jitsi Meets iOS SDK through Cocoapods. When I try to generate a build on XCode, it is failing with a permission denied error. But I have verified that the build folder on my laptop has the right permissions. So I am trying to understand what is causing the build to crash with a permission error.

I am having this issue ever since we received a new release of Jitsi SDK when it was updated for M2 platform. I have not done any changes on my end except updating the Jitsi SDK and XCode on my end. I have also tried to delete and recreate the project on XCode but still having the same issue. So I strongly believe it is not a proj ct folder permission issue at this point.

### Steps to reproduce:

1. Installed cocoapods
2. When I am trying to take a project build, I am facing xcode directory permission error.

### Expected behavior:

1. The build should run the project without any permission issues.

### Actual behavior:

 1.When I am trying to take a project build, I am facing xcode directory permission error.

### Server information:

- Jitsi Docker version : stable-6826
- Operating System: Ubuntu

### Client information:

- Browser / app version: Jitsi iOS sdk version (7.0.1)
- Operating System: Mac OS ventura 13.2

### Additional information:

I have also attached screen shots for below

1.https://prnt.sc/QEVZ7Sn3Hr0r
2.https://prnt.sc/X20JCIxUONgy
3.https://prnt.sc/96rZYsnB5vhe
4.https://prnt.sc/_86YyBBdqjpG

**Comment by charlesgigipo** [comment]
No Saghul

**Comment by charlesgigipo** [comment]
I have downloaded a sample SDK from the below link, but the sample project also has not run. I have attached my error screenshots.

Screenshots
1. https://prnt.sc/RE1pT1v0X6HF
2. https://prnt.sc/QMHV7Wwj-dlD

**Comment by saghul** [comment]
Did you run pod install ?

**Comment by charlesgigipo** [comment]
Yes I have run the pod install but still that issue same

**Comment by saghul** [comment]
@Calinteodor @tmoldovan8x8 can any of you repro this?

**Comment by Calinteodor** [comment]
@saghul @charlesgigipo 
I tested out the sdk sample apps. Build succeeded for all them, so I cannot reproduce this.
