### ISSUE TITLE
Screen sharing issues : After a few minutes, the shared screen is just a gray screen for some users

### ISSUE THREAD

**Issue by edi9999** [jitsi/jitsi-meet#1287]
On https://meet.jit.si/, with latest chrome on Linux and others on mac or Linux, sometimes, the screensharing seems to disappear for some users (but only some users don't see the screen anymore, others may continue to see the screen.), but audio continues to work. Usually, refreshing the page and sharing the screen again seems to work most of the time.

However this is still annoying. What do you think ?

**Comment by gpolitis** [comment]
Could you please try on our staging environment (https://beta.meet.jit.si/) and see if you're able to repro?

**Comment by edi9999** [comment]
I can reproduce the issue on beta.meet.jit.si when using two instances of chrome , however the screen appears grayed out and is not black as I previously reported. Refreshing the page of the instance that sees the screen-sharing makes it possible to see the screen again.

**Comment by gpolitis** [comment]
Interesting; I just tried a few times and it worked. Could you please share your webrtc-internals and JS console logs?

**Comment by edi9999** [comment]
I somehow cannot reproduce this anymore. Did you change something in beta environnment ?

I will retry on Monday to see if I can reproduce it.n

**Comment by gpolitis** [comment]
No, we haven't changed anything afaik. If you're able to repro again, please make sure to capture the debugging information. Thank you!

**Comment by edi9999** [comment]
I think I reproduced it : 

On : https://beta.meet.jit.si/foobar

I opened session A in Chrome in a normal tab, and started sharing my screen.
Then I opened a session B on a new instance of Chrome running in incognito mode.

For about three minutes, I couldn's see the screen of A from B browser, but instead saw the base icon of that user.

Here are the three log files that you asked for : 

(A) [user_who_shares_screen.txt](https://github.com/jitsi/jitsi-meet/files/752208/user_who_shares_screen.txt)
(B) [user_who_views_screen.txt](https://github.com/jitsi/jitsi-meet/files/752209/user_who_views_screen.txt)
(in same instance as A) [webrtc_internals_dump.txt](https://github.com/jitsi/jitsi-meet/files/752210/webrtc_internals_dump.txt)

**Comment by lpatmo** [comment]
I saw this issue as well in a screensharing session between two Chrome browsers. Even though the first person thought they were screensharing, the second person could only see a black box.

**Comment by edi9999** [comment]
For information, it sometimes also happens that the screen is shared by A, and neither B,C,D, or E see the remote screen (they all see the base icon of the user)

**Comment by edi9999** [comment]
Any updates on this ?

**Comment by edi9999** [comment]
It seems that I have found a workaround for this. 

If a share-screen session becomes gray (happens every minute or so), you can open a new tab with the same URL (and keep the first tab open). Whenever the second tab is loaded completely, it seems that the first tab can recover and sees the shared screen again. This is quite cumbersome to do, but at least there is a way to fix it.

However, I still think that this is a very critical bug !

**Comment by huiminsi** [comment]
so many bugs!

**Comment by edi9999** [comment]
I still have this issue on the public jitsi. Reloading the page makes the screen appear again.

**Comment by jakobbraun** [comment]
I had the same issue yesterday with screen sharing from Firefox on Ubuntu Linux and https://meet.jit.si/
