### ISSUE TITLE
Badge button not responsive for Dimension 368 X 619 (Assign me)

### ISSUE THREAD

**Issue by abhijeet-26** [jitsi/jitsi-meet#12878]
![image](https://user-images.githubusercontent.com/68768410/217225097-d0ea877f-6f18-46ac-a80a-555e7a9ba619.png)

### Description:

For Dimension Size 368 X 619  , badge icon just moves left side.

I have already solved this issue **please assign me this issue**.
![image](https://user-images.githubusercontent.com/68768410/217225526-43d179af-003c-45ea-954f-0be9a068a394.png)

### Expected behavior:

![image](https://user-images.githubusercontent.com/68768410/217225652-05166b34-8094-488f-939b-32b72f996ef2.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/68768410/217225097-d0ea877f-6f18-46ac-a80a-555e7a9ba619.png)

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Thanks for the report! We don't use issue assignments. If you have solved and are willing, you are welcome to send a Pull Request, thank you!

**Comment by abhijeet-26** [comment]
I will make PR. Thanks for your response

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/12880
