### ISSUE TITLE
Issue with com.facebook.react.modules.core.PermissionAwareActivity, when I use JitsiMeetActivity.launch(context, JitsiMeetConferenceOptions) in android app required activity.

### ISSUE THREAD

**Issue by satish-ziroh** [jitsi/jitsi-meet#12888]
### Description:

I’m able to build my customized Jitsi SDK in .aar format and integrated in my Android project by giving these steps in build file :
implementation fileTree(dir: ‘libs’, include: [‘.aar’, '.jar’], exclude: [])
implementation (‘org.jitsi.react:jitsi-meet-sdk:+’) { transitive = true }

Integration is successful & I’m able to access the Jitsi Meet classes, but it shows error at launch() when i use
JitsiMeetActivity.launch(context, JitsiMeetConferenceOptions) , 
it shows this error - **Cannot access 'com.facebook.react.modules.core.PermissionAwareActivity' which is a supertype of 'org.jitsi.meet.sdk.JitsiMeetActivity'. Check your module classpath for missing or conflicting dependencies** 
at launch() in my required activity class.

### Steps to reproduce:

1. Build the Jitsi SDK in .aar format
2. Implementation fileTree(dir: ‘libs’, include: [‘.aar’, '.jar’], exclude: [])
implementation (‘org.jitsi.react:jitsi-meet-sdk:+’) { transitive = true }  in android project build.gradle
3. Use JitsiMeetActivity.launch(context, JitsiMeetConferenceOptions) , 
it shows this error - **Cannot access 'com.facebook.react.modules.core.PermissionAwareActivity' which is a supertype of 'org.jitsi.meet.sdk.JitsiMeetActivity'. Check your module classpath for missing or conflicting dependencies** 
at launch()

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System: mac OS & Windows

**Comment by saghul** [comment]
Do you have react-native in your maven repo?

**Comment by satish-ziroh** [comment]
you mean this - 
maven { url "$rootDir/../node_modules/react-native/android" }
        // Android JSC is installed from npm.
        maven { url("$rootDir/../node_modules/jsc-android/dist") }
in my jitsi-meet/android/build.gradle file.

**Comment by saghul** [comment]
No, check the files in the generated maven repo. Do you see the react-native package?

**Comment by satish-ziroh** [comment]
you mean in the genersated SDK ?
actually after running this step in jitsi-meet - **./android/scripts/release-sdk.sh tmp/repo**
it created the sdk-release.aar file & there is no react-native package in that file.
![Screenshot_20230209_061621](https://user-images.githubusercontent.com/106305935/217817848-fdad75e7-b706-4f07-b958-aa96f460f632.png)

under the sdk folder - it contains all the java class files related to Jitsi. but there is no react-native package in that.

**Comment by satish-ziroh** [comment]
or else please tell me how to create [jitsi-maven](https://github.com/jitsi/jitsi-meet) to [jitsi-maven-repository](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases).
I followed these steps [Build and use your own SDK artifacts/binaries](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk/) but it created the sdk-release.aar file.

**Comment by saghul** [comment]
the `tmp/repo` folder is an actual maven repo. Check its contents. You need to add that repo to your project, not just the Jitsi SDk aar.

**Comment by satish-ziroh** [comment]
nothing is generated in tmp/repo folder, it is empty. the sdk-release.aar is generated in jitsi-meet/android/sdk/outputs/aar/sdk-release.aar .

**Comment by saghul** [comment]
If you passed the path /tmp/repo then the result will be in /tmp/repo, not tmp/repo.

**Comment by satish-ziroh** [comment]
yeah sorry, I mean `/tmp/repo` is empty nothing is generated in that. but the terminal message says 
```
Build Successful
Finished! Don't forget to push the tag and the Maven repo artifacts.
```
but `/tmp/repo` is empty, I'm stuck with this issue from last 2 days, help me to solve this.

**Comment by saghul** [comment]
What does this return in your terminal: `find /tmp/repo/`

**Comment by satish-ziroh** [comment]
@saghul  
finally after doing some changes, I run `./android/scripts/release-sdk.sh tmp/repo` now the artifacts are generated in tmp/repo folder, but there are only two packages `com` & `org`.
I push the artifacts to my github repo and I gave the   
`maven { url "https://github.com/myRepo/jitsisdk/raw/main/releases" }` in `settings.gradle` file.
but I'm unable to access - JitsiMeetActivity, JitsiMeet, JitsiMeetConferenceOptions.

your [jitsi-maven-repository](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases) consists of multiple packages, where as my repo consists of only `com` & `org`

is there anything wrong in generating the artifacts ?

**Comment by saghul** [comment]
Aren't there any more files inside those directories?

**Comment by satish-ziroh** [comment]
yeah there are.
1. `com` -> `facebook` -> `react` -> some react-native directories.

2. `org` ->  

- `jitsi` (contains some maven-metadata files and jitsi-meet-sdk .aar, sha1, pom etc. files) 
- `webkit` ( contains some maven-metadata files and android-jsc .aar, sha1, pom etc. files)

**Comment by saghul** [comment]
That looks about right. Is your repo public?

**Comment by satish-ziroh** [comment]
yeah it is, please have a look - [myJitsiMavenRepo](https://github.com/satish-ziroh/jitsi-maven-repository/tree/main/releases)

**Comment by saghul** [comment]
The content looks ok. Can you try to refresh dependencies, in the Gradle tab in Android Studio?

**Comment by satish-ziroh** [comment]
yeah I tried gradle sync & invalidate caches Restart also,
but I'm unable to access - JitsiMeetActivity, JitsiMeet, JitsiMeetConferenceOptions.

**Comment by saghul** [comment]
Does it compile or do you get errors?

**Comment by satish-ziroh** [comment]
errors (Unresolved reference). when I type for those, they don't show the references, So I copied them from the example.

**Comment by saghul** [comment]
Do the sample projects work for you?

**Comment by saghul** [comment]
Glad it works for you now!

**Comment by satish-ziroh** [comment]
but, may I know why it shows errors for the versions.

**Comment by saghul** [comment]
Because the version you released is set to 99.0.0.

Our repo contains them all.

**Comment by satish-ziroh** [comment]
@saghul 
I'm able to access the JitsiMeetActivity, JitsiMeet, JitsiMeetConferenceOptions, only if I make this repo [myJitsiRepo](https://github.com/satish-ziroh/jitsi-maven-repository/tree/main/releases) public. 
If I make it as private I'm unable to access those classes and shows error. How can I resolve this ?

**Comment by saghul** [comment]
I don't think Maven can work with private GH repos.

You would need to host a proper Macen repo with Nexus or something like that. Not sure if GH packages supports Maven.

**Comment by bradfordcan** [comment]
I am using this sdk with 7.0.1 version for my Android app and I am also having this error.  Is there a way I can resolve this?
or is there a stable version of  the sdk that I can use that supports sdkVersion >31.

**Comment by saghul** [comment]
What Gradle version and Gradle Plug-in version do you use?

**Comment by bradfordcan** [comment]
> 

com.android.tools.build:gradle:4.1.2
gradle-7.5-bin

Let me know if that helps.  Thanks!

**Comment by saghul** [comment]
@tmoldovan8x8 can you PTAL?

**Comment by Rainbow87** [comment]
> yeah there are.
> 
> 1. `com` -> `facebook` -> `react` -> some react-native directories.
> 2. `org` ->
> 
> * `jitsi` -> `react` -> `jitsi-meet-sdk` -> maven-metadata files & `99.0.0` -> jitsi-meet-sdk-99.0.0.aar(md5, sha1, sha256, sha512) & jitsi-meet-sdk-99.0.0.pom(md5, sha1, sha256, sha512)
> * `webkit` -> `android-jsc` -> maven-metadata files & `r250230` -> android-jsc-r250230.aar(md5, sha1 files) & android-jsc-r250230.pom(md5, sha1 files)
> 
> that's it.

Hi @satish-ziroh 
i'm able to build the custom SDK, and the repo same as yours above.
I try to push sdk repo to my github repo and add url to JitsiSDKTest app, but not able to compile, always error "Failed to resolve: com.github.xyz".

Please help me, how can i import sdp repo to my project? or how can you push the artifact to github repo?
My public repo here: https://github.com/Rainbow87/jitsi-maven-repository
