### ISSUE TITLE
Get Email or Slack Notification When Someone Joins a Room

### ISSUE THREAD

**Issue by luminous706** [jitsi/jitsi-meet#12897]
**Is your feature request related to a problem you are facing?**

Yes, we use a randomly generated Jitsi room URL per customer. A customer can join their Jitsi room at any time if they have a question for us, 24/7. Problem is, we never know when they do so, they see to notify us by email to tell us they have joined their room and are waiting for us to show up.

**Describe the solution you'd like**

Get a Slack or Email notification when someone joins a room, along with the link so we can join as soon as client shows up.

**Describe alternatives you've considered**

I couldn't think of any alternative.

**Comment by saghul** [comment]
You can implement that on top of this Prosody module: https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync

You'll need to write the code that sends the actual Slack message, but since it's a webhook you could something like Zapier or a lambda.

**Comment by luminous706** [comment]
> You can implement that on top of this Prosody module: https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync
> 
> You'll need to write the code that sends the actual Slack message, but since it's a webhook you could something like Zapier or a lambda.

Thanks for the reply, will look into this but it might take a while to implement. Would there be running logs I can just grep something like "room event: someone created or joined a room", then I can use my own email script?

**Comment by saghul** [comment]
We don't currently have such logs, a MUC event is the equivalent.
