### ISSUE TITLE
Whiteboard “Everyone follows me” enhancement

### ISSUE THREAD

**Issue by VernPace** [jitsi/jitsi-meet#12895]
The Jitsi whiteboard is a wonderful tool. We think it could be made better with respect to presentations where the presenter enables the “Everyone follows me” moderator option - It should behave like the tile view toggle. An “Everyone follows me” presenter may need to jump back and forth between whiteboard, screen share, tile view, ,,, , and back to whiteboard all being rendered to the other users. This will be a welcomed enhancement to presenters.

There are also cases when users leave and return to an ongoing conference. The current behaviors for the whiteboard are as follows:

- When a user returns, the whiteboard is shown with updated (refreshed) drawings that occured while the user was away.
- If a screen sharing session started after a user leaves, upon return, the screen sharing is shown to the user and the whiteboard is shown in the filmstrip.

The above current behaviors are good and occur _**without**_ the “Everyone follows me” moderator option. However, if the presenter enables “Everyone follows me”, returning users should not be shown the whiteboard if the presenter is not showing the whiteboard.

**Comment by saghul** [comment]
> n. However, if the presenter enables “Everyone follows me”, returning users should not be shown the whiteboard if the presenter is not showing the whiteboard.

This is expected. If the moderator who enabled follow-me is not viewing it, users (including new joiners) are expected to follow the moderator.

**Comment by VernPace** [comment]
@saghul 

Please don't forget about this. I realize there may be other priorities now, but this will be a good feature !
