### ISSUE TITLE
chat: avatar doesn't keep its width if message is long

### ISSUE THREAD

**Issue by webstalt** [jitsi/jitsi-meet#12890]
### Steps to reproduce:

1. Open video conference
2. Connect user without avatar, with name of one word, for ex, 'Mario'
3. Send several lines long chat message by this user

### Expected behavior:

The avatar should keep its width 32px, as it's declared in css styles.

### Actual behavior:

Avatar becomes 16px width, because parent is display flex and there we should keep the shape of its children.

### Server information:

- Jitsi Meet version: current, css hash: css/all.css?v=6943.3715
- Operating System:

### Client information:

- Browser / app version: Chrome/109.0.0.0 
- Operating System: Intel Mac OS X

**Comment by saghul** [comment]
@robertpin any chance this is covered in the latest chat changes?
