### ISSUE TITLE
for more than 2 participants with camera on, i can see only 2 cameras and the rest with avatar

### ISSUE THREAD

**Issue by fatima-gloqal** [jitsi/jitsi-meet#12908]
### Description:

i installed the jitsi and for this use case it happends once we have more than 2 participants all, the cameras are hidden and we can only see the initials or avatar, even they have all cameras open, when i pin on someone then i can see his camera, but it's always 2 cameras in the list of participants

**Comment by saghul** [comment]
Do you have your own deployment or are you observing this on meet.jit.si ?

**Comment by fatima-gloqal** [comment]
@saghul yeah my own deployment

**Comment by saghul** [comment]
Does your server have enough bandwidth? Did you configure channelLastN to 2 by any chance? Can you share your browser console logs?

**Comment by fatima-gloqal** [comment]
how to know the exact good bandwidth for the server ? i updated to different channels but it gives me always  for 4 participants with camera enabled only 2 cameras that are showed, is there any config that is limiting the cameras number that we can view

**Comment by fatima-gloqal** [comment]
@saghul how to remove the problem of not showing cameras that are hidden if we have scroll for non tile view

**Comment by fatima-gloqal** [comment]
thank you my issue is fixed

**Comment by damencho** [comment]
And the problem was?
