### ISSUE TITLE
With three video sources, in tile mode, video is improperly cropped into portrait orentation

### ISSUE THREAD

**Issue by drboone** [jitsi/jitsi-meet#12905]
### Description:

With three video sources, in tile mode, video is improperly cropped into portrait orentation.  Jitsi Meet has no clue where in the incoming videos humans may be found, and therefore cropping down to portrait mode is exceedingly inappropriate.
This is a regression.

### Steps to reproduce:

Join three landscape video sources (i.e. the garden variety webcam) to a conference.  Enter tile mode.

### Expected behavior:

Previous behavior where multiple landscape windows would be tiled in multiple rows.

### Actual behavior:

Three cropped portrait windows side by side.

### Server information:

- Jitsi Meet version: 2.0.8218-1
- Operating System: Debian bullseye, kernel 5.10.0-20-amd64

### Client information:

- Browser / app version: Multiple browsers have the same experience
-- Linux / "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
-- Windows / "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41"
-- Mac laptop / "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
- Operating System:

### Additional information:

I believe the problem started after this set of upgrades:

jicofo:amd64 (1.0-954-1, 1.0-980-1)
jitsi-meet-turnserver:amd64 (1.0.6776-1, 1.0.6918-1)
jitsi-meet:amd64 (2.0.8044-1, 2.0.8218-1)
jitsi-meet-web-config:amd64 (1.0.6776-1, 1.0.6918-1)
jitsi-meet-prosody:amd64 (1.0.6776-1, 1.0.6918-1)
jitsi-videobridge2:amd64 (2.2-61-g98c9f868-1, 2.2-67-gc7f2b2d5-1)
jitsi-meet-web:amd64 (1.0.6776-1, 1.0.6918-1)

However it's possible it was the previous round:

jicofo:amd64 (1.0-846-1, 1.0-954-1)
jitsi-meet:amd64 (2.0.6865-2, 2.0.8044-1)
jitsi-meet-web-config:amd64 (1.0.5818-1, 1.0.6776-1)
jitsi-meet-prosody:amd64 (1.0.5818-1, 1.0.6776-1)
jitsi-videobridge2:amd64 (2.1-617-ga8b39c3f-1, 2.2-61-g98c9f868-1)
jitsi-meet-web:amd64 (1.0.5818-1, 1.0.6776-1)

**Comment by saghul** [comment]
This is by design, we try to fill up the available space.

You can disable tile enlargement with the config.js setting of that name.

**Comment by drboone** [comment]
Well, I'm not sure if they're getting enlarged or not.  They're certainly getting cropped.  I'll try the setting.

**Comment by drboone** [comment]
This setting reverts the behavior to the expected lanscape format.
