### ISSUE TITLE
Problems with sound when startAudioMuted is set.

### ISSUE THREAD

**Issue by shevchukma** [jitsi/jitsi-meet#12903]
### Description:

We recently enabled the startAudioMuted setting with a value of two.
`startAudioMuted: 2`
After that, the user received complaints about the lack of sound.
I found such conditions to reproduce the problem. If participant 3 (that is, the first one on whom the microphone mute setting worked) uses the latest versions of Chrome> 109, then the next participant (number 4) cannot hear him.

### Steps to reproduce:

1. In config.js set startAudioMuted: 2
2. Connect with 4 clients, while 3 and 4 must be Chrome
3. Try talking to clients 3 and 4.

### Expected behavior:

Each participant hears each other.

### Actual behavior:

The fourth client does not hear the 3rd.

### Server information:

- Jitsi Meet version: 2.0.8252-1
- Operating System: Ubuntu 22.04.1 LTS

### Client information:

- Browser / app version: Chrome 110
- Operating System: Windows 11

### Additional information:

We get into the Jitsi call from a chat in Rocket Chat. They are integrated. But I don't think it matters in this case.

**Comment by saghul** [comment]
Are you able to reproduce this on meet.jit.si ?

You can use an URL override for setting the parameter.

**Comment by shevchukma** [comment]
Hey @saghul 
No, I couldn't repeat it on meet.jit.si.

**Comment by saghul** [comment]
I don't think we have fixed any related issues recently, have we @jallamsetty1 ?

**Comment by jallamsetty1** [comment]
Nope, I don't think we have fixed anything related to startAudioMuted recently.
