### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by Flying-Light** [jitsi/jitsi-meet#12917]
**Is your feature request related to a problem you are facing?**
 Sometimes we face notifications with missed or incorrect translations for our use. 
Or in some cases we want to change the notification box design. we may need to color it, add icons, and so on.
Or even just change the appear behavior of the notification box,

**Describe the solution you'd like**

 The solution is to add "incomingNotification" event like this:
api.addListener("incomingNotification", incomingNotification); 
function incomingNotification(e) { }

This event will fire for all available notifications list (All Of Them), not the selected ones
Why?
1-
I will pass empty array to prevent any notifications to appear
, configOverwrite: { notifications: [], }

2-
I will add listener to "incomingNotification" event

3-
I will receive the event with this data
{ notificationKey // string with the value of one of the ["dialog.kickTitle", "notify.disconnected", "notify.connectedOneMember", ........ and all the available notification]  } 

4-
I will create my own notification, with my own text, with my own design and icons based on the notificationKey.

Note:
We can also pass the registered notifications to be fired to avoid the not needed ones like:

var notification = ["dialog.kickTitle", "notify.connectedOneMember"];
api.addListener("incomingNotification", notifications , incomingNotification); 
function incomingNotification(e)
{
}

This way I muted all built-in notifications, and created my own.

**Comment by saghul** [comment]
I think this is a good idea. Let me check with the team.

**Comment by Flying-Light** [comment]
This is an example of some problems that can be fixed with the above suggestion,
I created my own chat element, and keep it visible on half of the screen,
the chat element background is black with transparency,
works great, but I cannot interact with the "Notifications" or even click "X" to close it,
If I can receive it and then show it using my own html element, this will be amazing.
![Screen Shot 2023-03-20 at 11 37 31](https://user-images.githubusercontent.com/46743639/226276573-d7c773b8-9e4c-4511-83bc-0edff7b93f27.png)
