### ISSUE TITLE
participants can't hear all and talk to other participants

### ISSUE THREAD

**Issue by de1phi48** [jitsi/jitsi-meet#12924]
### Description:

In meeting with >10 participants and recording sometimes participants can't hear other participants and can't talk to all meeting. 

### Server information:

- Jitsi Meet version: 2.0.8252
- Operating System: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-60-generic x86_64)

### Client information:

- Browser / app version: rocket.chat integration
- Operating System: windows 11 pro

### Additional information:

if count of participant less 10, we dont have problem.

**Comment by saghul** [comment]
Does the server have enough resources to handle the load?

**Comment by de1phi48** [comment]
yes, in server installed processor Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz 10-core and 32 Gb memory. Load of cpu abot 5% in meeting.

**Comment by saghul** [comment]
Do you observe any errors in the JS console of the clients beyond 10?

**Comment by de1phi48** [comment]
i cant open js console in integration. logs in server havent errors

**Comment by saghul** [comment]
Not sure I understand. Why can't you?

**Comment by de1phi48** [comment]
if i dont check options "everyone starts muted" in settings of meeting, all participants can hear all and can talk to other.

**Comment by saghul** [comment]
If you check that that option then participants will join muted. Do they hear all other participants who have unmuted? Any chance people are muted but they don't know?

**Comment by de1phi48** [comment]
participants know that they are connected muted. They try to press the spacebar and turn on the microphone, but there is no effect.

**Comment by saghul** [comment]
The spacebar works in "push to talk" mode, you need to keep it pressed to be unmuted.

**Comment by de1phi48** [comment]
I know, but there is no reaction from these members when pressed.

**Comment by saghul** [comment]
Hum that's odd. Any chance you can gather some browser console logs of those users?

**Comment by de1phi48** [comment]
we use Rocket.Chat integration and dont have console in webkit app

**Comment by de1phi48** [comment]
we make test in Google Chrome and can catch problem. In logs have some records:

`Logger.js:154 
        
       2023-03-03T11:08:13.527Z [modules/statistics/AudioOutputProblemDetector.js] A potential problem is detected with the audio output for participant a8be20df, local audio levels: [null,null], remote audio levels: undefined`

and 

`events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 conference.userLeft listeners added. Use emitter.setMaxListeners() to increase limit`
