### ISSUE TITLE
Can i run npm install on windows

### ISSUE THREAD

**Issue by tal007** [jitsi/jitsi-meet#12939]
**Is your feature request related to a problem you are facing?**
Sorry.My boss want me to ues this to develop app. But in the offical website shows not support window.
![image](https://user-images.githubusercontent.com/25813059/220295650-325ca466-4b23-4fb8-9d31-dd1e5a9d8eeb.png)

There is a issue at 2021.https://github.com/jitsi/jitsi-meet/issues/8763

I just develop web app, not native app.

**Describe the solution you'd like**
It can develop on windows.

**Describe alternatives you've considered**
No.

**Comment by saghul** [comment]
The web app can work on Windows. The simplest way is probably through WSL.

**Comment by tal007** [comment]
> 
I use WSL，but when i run `npm insrall` , there is a problem.
![image](https://user-images.githubusercontent.com/25813059/220540648-9833040a-e456-4133-a20b-efb937f69cb8.png)

I am in China, may be my network question.

**Comment by saghul** [comment]
All those are warnings. Does it get stuck? If so it might be a network problem indeed.

**Comment by tal007** [comment]
> > All those are warnings. Does it get stuck? If so it might be a network problem indeed.
> 
> Yes. I found there are two packages i can not download.
> 
> react-native-webrtc@106.0.5
> 
> > there is a android zip i can not download
> > resemblejs@4.0.0
> > i can not find the problem.
> 
> if i just run on web not native. without these packages, dose it work. Comment these code? ![image](https://user-images.githubusercontent.com/25813059/220576385-b4443bf1-7b05-4e66-822a-0c04d08c85fa.png) ![image](https://user-images.githubusercontent.com/25813059/220576818-53e90465-2d28-4782-8324-7735de61abb6.png)

Do these, i can run.
![image](https://user-images.githubusercontent.com/25813059/220581783-4eb657b6-3118-4b5a-9060-53dcef5f7ab0.png)
But if i change the code, it's not refresh. webpack-dev-server hot not word.
![image](https://user-images.githubusercontent.com/25813059/220582433-d50ecf68-bc93-482c-b218-4eebe28149d4.png)
Is this due to the influence of WSL?

**Comment by saghul** [comment]
It should hot reload indeed, not sure why it doesn't work

**Comment by tal007** [comment]
OK. I'll try again.

**Comment by tal007** [comment]
因为自己遇到了坑，所以记录了一下，仅供给中国使用windows开发的开发者。

Because of the pitfalls I encountered, I recorded it and only supplied it to developers using windows development in China.

https://tal007.notion.site/jitsi-meet-064dfb51da31489ba2834fffa839271f

**Comment by iim-norse** [comment]
i have this when run npm start but after i close window with this error everything works (macos)
Compiled with problems:X

ERROR in ./node_modules/resemblejs/resemble.js 63:13-30

Module not found: Error: Can't resolve 'canvas' in '/Users/username/projects/jitsi/node_modules/resemblejs'
