### ISSUE TITLE
echo sound when opening camera 

### ISSUE THREAD

**Issue by Beartx** [jitsi/jitsi-meet#12936]
I am using jitsi_meet: ^4.0.0 on my mobile flutter app, everything works fine except that when I open my camera or the person who I am contacting open his camera, echo with high noise starts occurring and it will keep going until I end the meeting and start a new meeting without enabling the camera. 

I am using these versions:
Flutter SDK3.3.6
Dart SDK2.18.2
 jitsi_meet: ^4.0.0

**Comment by saghul** [comment]
SDK 4 is really old, you should update.

Even then, however, we use the hardware echo canceller and there is nothing else we can do if that is not sufficient.

**Comment by gurvirbaraich** [comment]
The echo is from who's side. Do you hear you voice again.

**Comment by saghul** [comment]
Please test the latest SDK.

**Comment by Beartx** [comment]
the problem gone after upgrading to jitsi 5, but it seems sometimes there is problem with camera when I open it, it shows black screen, where I have to leave the meeting and join again
