### ISSUE TITLE
Participants counter

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#12931]
**Before**
`padding-top: 2px;`

<img width="220" alt="imagem1" src="https://user-images.githubusercontent.com/32515675/219693716-3d8debca-d128-4141-a426-d440edbaefb8.png">

![imagem2](https://user-images.githubusercontent.com/32515675/219693771-bbe1605c-8ca1-43fe-8f4b-6acaec402e7c.png)

**After**
`padding: 1px;`

<img width="219" alt="imagem3" src="https://user-images.githubusercontent.com/32515675/219693814-2c4e615c-1682-4825-8754-a01314a9a4d2.png">

![imagem4](https://user-images.githubusercontent.com/32515675/219693834-b9cede2f-41d2-4f88-bb02-e3ee0826acf3.png)

### Server information:

meet.jit.si

### Client information:

- Browser / app version: Chrome, Firefox, Safari
- Operating System: macOS

**Comment by saghul** [comment]
PIng @robertpin

**Comment by Yash-Ambekar** [comment]
I have found the above written code in ParticipantsCounter.tsx
![Screenshot from 2023-02-17 22-25-12](https://user-images.githubusercontent.com/96481913/219715578-4546da6c-e5d1-4fda-92ac-e1ddbe70606e.png)
Should I make the change and request a PR?
If I misunderstood the issue in anyway please tell me.

**Comment by nitishkumar333** [comment]
Created a PR for this issue please check

#12933
