### ISSUE TITLE
Language List is out of the page in Small screen

### ISSUE THREAD

**Issue by anikdhabal** [jitsi/jitsi-meet#12938]
### Steps to reproduce:

1. Open Jitsi Meet
2. Restore Down the Page
3. Click the Language list

### Expected behavior:

List height Would be in between  the page

### Actual behavior:

List is Out of the page

### Client information:

- Browser / app version: Microsoft Edge 108.0.1462.76 (Official build) (64-bit)
- Operating System: windows 10(22H2)

**Comment by saghul** [comment]
Can you please share a screenshot?

**Comment by anikdhabal** [comment]
<img width="489" alt="Screenshot 2023-02-20 215105" src="https://user-images.githubusercontent.com/81948346/220182116-cbd4d37d-5b8f-40e7-934b-37fb04f9b16e.png">

@saghul

**Comment by saghul** [comment]
Ping @robertpin

**Comment by alimurtaza026** [comment]
Hi, Can I solve this issue.  Please assign this to me

**Comment by alimurtaza026** [comment]
I am working on it to fix it

**Comment by sohamtembhurne** [comment]
This issue appears while using mobile resolution on web browser. It appears differently on the actual mobile device. Similiar issue is addressed [here](https://stackoverflow.com/questions/59678338/select-dropdown-going-out-of-screen-in-mobile-view).

**Comment by KIET7UKE** [comment]
Hey, @anikdhabal I'm looking forward to fixing this asap!

**Comment by Saxenaa218** [comment]
Hey @anikdhabal, is this issue fixed, I can see a scroll on the language dropdown's overflowed content which removes the problem

**Comment by robertpin** [comment]
We use the HTML `<select>` so this is more of a browser issue. Closing this
