### ISSUE TITLE
Allow virtualBackground in branding and upload of custom backgrounds at the same time

### ISSUE THREAD

**Issue by MrMarlin** [jitsi/jitsi-meet#12941]
Hello Team

Since we are using virtual backgrounds with the branding feature, there is no possibility for users to upload custom backgrounds. 
This line prevents the upload button from showing. Is there any reason why the upload is disabled when using custom background via the branding feature? 

https://github.com/jitsi/jitsi-meet/blob/b4bf36323700da18893b92c35971109de68cabd7/react/features/virtual-background/components/VirtualBackgroundDialog.tsx#L107

It would be nice to have both options at the same time.

Best regards

**Comment by saghul** [comment]
Good question. I'll ask around.

**Comment by MrMarlin** [comment]
Hi All

Do you know, when this commit will released?

cheers

**Comment by saghul** [comment]
I believe a new release is scheduled for next week.

**Comment by MrMarlin** [comment]
thanks for your answer. seems like the commit didn't make it into the release :(

**Comment by saghul** [comment]
AFAIS it did. Are you asking about the stable release or 8x8.vc ?

**Comment by MrMarlin** [comment]
I am talking about the stable release. But seems like i mixed up release numbers. Thanks for your fast response :)
