### ISSUE TITLE
react iframe sdk cannot join with mobile app at chrome

### ISSUE THREAD

**Issue by dev-hanyahmed** [jitsi/jitsi-meet#12948]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

Unsafe attempt to initiate navigation for frame with origin  from frame with URL The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

## Current behavior
---

mobile join meeting button not working

## Expected Behavior
---

to work

## Possible Solution
---

add these tags 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' to externaljs sandbox iframe 

## Steps to reproduce
---

use another domain at react sdk
open chrome 
change device to phone
refresh the page
click join the meeting

# Environment details
---

**Comment by saghul** [comment]
We cannot allow top navigation for security reasons. Not sure what to do about this TBH.

**Comment by Tipuch** [comment]
would it be able to allow end users to send iframe options through the Iframe api when initiating the API?
`new JitsiMeetExternalAPI`

Also as far as security goes we could use "allow-top-navigation-by-user-activation" which would require user interaction

**Comment by Tipuch** [comment]
adding "allow-top-navigation-by-user-activation" to the sandboxing options would work --> https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js:396
