### ISSUE TITLE
Pinning behavior behind whiteboard when "Maximum number of participants who can be pinned to the main stage" is greater than one.

### ISSUE THREAD

**Issue by VernPace** [jitsi/jitsi-meet#12942]
**Description | Actual behavior**

User appears to be pinned behind a whiteboard when "Maximum number of participants who can be pinned to the main stage" is set to a value greater than one.  In addition, the same user is shown with a black background in the filmstrip.

_**Image 1**_
![WhiteboardIssue](https://user-images.githubusercontent.com/94239732/220488334-bd9f1369-2051-49ea-ae39-355ffb95b587.PNG)

**Steps to reproduce:**

1.  User A initiates a conference in meet.jit.si.  User A goes to Settings > More > Sets "Maximum number of participants who can be pinned to the main stage" to 6 and clicks OK as shown below.

_**Image 2**_
![image](https://user-images.githubusercontent.com/94239732/220491707-2e40a05b-3b79-4158-8dee-dd7188d1680a.png)

2.  User B joins the conference and also sets "Maximum number of participants who can be pinned to the main stage" to 6 and clicks OK as shown above.

3.  User A shows the whiteboard
4.  User B sees User A pinned behind the whiteboard as shown in _**Image 1**_.  On most occasions, User A will see User B pinned behind the whiteboard as well.
5.  Note that this also occurrs when passing &config.filmstrip.stageFilmstripParticipants=6 as part of a URL parameter string.

**Expected behavior:**

Users should not see pinning behavior behind whiteboard when "Maximum number of participants who can be pinned to the main stage" is set to a value greater than one.

**Server information:**

- Jitsi Meet version: Latest release
- Operating System:

**Client information:**

- Browser / app version:  Chrome 110.0.5481.104
- Operating System: Windows 10

**Comment by saghul** [comment]
@mihhu can you PTAL?

**Comment by AlexJAB21** [comment]
How could I change the maximum number of participants set? Currently I get the same 6, I would like to increase it to 10.
Thank you.

**Comment by saghul** [comment]
The maximum is currently hard-coded to 6.

**Comment by AlexJAB21** [comment]
Is it possible to modify it to be 10?

**Comment by saghul** [comment]
YoI'm r have to dig in the code, make the change and rebuild it.

**Comment by AlexJAB21** [comment]
Could the file name indicate?
