### ISSUE TITLE
Breakout rooms: enabling hideJoinRoomButton makes impossible for moderator to join any of the breakout rooms

### ISSUE THREAD

**Issue by encrypt94** [jitsi/jitsi-meet#12946]
### Description:

Enabling the config option  breakoutRooms -> hideJoinRoomButton makes impossible for moderator to join any of the breakout rooms

### Steps to reproduce:

1. Enable breakoutRooms -> hideJoinRoomButton in config.js
2. Join as moderator 
3. Open the partecipants  panel
4.  Create a breakout roomi

### Expected behavior:

As a moderator i should be able to join one of the breakout rooms using the Join button (that should be hidden only for normal users) or using a context menu to move myself in one of the rooms as i do to move other users.

### Actual behavior:

As a moderator i cannot join any of the breakout rooms.

### Server information:

- Jitsi Meet version: master

### Proposed change

Change the check in https://github.com/jitsi/jitsi-meet/blob/master/react/features/participants-pane/components/breakout-rooms/components/web/RoomList.js#L68

from 
```
{!hideJoinRoomButton && <JoinActionButton room = { room } />}
```
to

```
{(!hideJoinRoomButton || isLocalModerator ) && <JoinActionButton room = { room } />}
```
and explicit in config.js comments that `hideJoinRoomButton` hides the button only for non moderator users.

**Comment by saghul** [comment]
The intent of that setting is for integrators to decide when it should be shown or not. Usually the way it goes it either people don't want to see it at all (your proposal breaks that) or want to selectively show it.

Your suggestion would break existing behavior and thus is not acceptable.

A new option to hide it just to non moderators would be acceptable.

**Comment by encrypt94** [comment]
Your point about breaking the existing behavior and the intent of the settings totally makes sense and to be honest i was expecting this kind of answer, that's why i added "or using a context menu to move myself in one of the rooms as i do to move other users" in the expected behavior section (without elaborating in the proposed change, silly me).

Do you think it would be a good solution to show a context menu when `localVideoOwner  && isModerator` showing the list of the breakout rooms and a label like "Move to:" or something similar but not "Send participant to"? Otherwise the moderator cannot leave the main room and this looks like a bug to me.

> A new option to hide it just to non moderators would be acceptable.
About that and semi OT, some context: i'm using jitsi on a project where we do strongly moderated meetings (relying on jitsi-moderated), we had the need to enable some features (like join breakout rooms, screen sharing, poll creation) only to the moderators right now we did it tweaking the code.
Do you think it woud be interesting to extend the config with something like the following example or do you think it is a high specific scenario and there is some kind of other correct way to do it?
```
moderatatorOnlyOptions {
    shareScreen: true,
    createPoll: true
}
```
if there is some interest i can work on it and submit a PR

**Comment by saghul** [comment]
> Do you think it would be a good solution to show a context menu when `localVideoOwner && isModerator` showing the list of the breakout rooms and a label like "Move to:" or something similar but not "Send participant to"?

This is already possible from the participants pane, which is where breakout rooms are created too, so I think having a duplicate way of doing it doesn't add much.

> Otherwise the moderator cannot leave the main room and this looks like a bug to me.

They can, moving participants from within a BR should still be possible.



> bout that and semi OT, some context:

We have done that with JWT features instead. It's a more flexible mechanism since the features are attached to the token. Adding extra features would be ok I'd say.

**Comment by encrypt94** [comment]
>This is already possible from the participants pane, which is where breakout rooms are created too, so I think having a duplicate way of doing it doesn't add much.

Maybe i was not clear with the description, when talking about the context menu i was talking about the one in participants pane.  This menu is not showed for the current user so as moderator when hideJoinRoomButton is enabled i see no way in the UI i can join a breakout room. I can only move _other_ users in and out not myself.

Can you please explain if i'm missing something?

**Comment by saghul** [comment]
Oh right, yeah. That new option would solve that.
