### ISSUE TITLE
Microphone mute not working

### ISSUE THREAD

**Issue by zeynepbasaranaksu** [jitsi/jitsi-meet#12960]
Hello everyone,

A user who participated in the meeting via desktop opens his camera and microphone after joining the meeting. We can see the information that the tracks have been added. After approximately 45 minutes, the user wants to mute the sound. Although he sees his own voice muted, he receives the information that the voice is transmitted to other meeting participants.

When I examine it, I can see the following log;

**_Mute LocalTrack3,audio: true_**

However, we saw from the logs that the TRACK_MUTE_CHANGED event was not triggered and the presence message was not sent at the same time.

He also stated that the problem was fixed when the user exited the meeting and re-entered.

According to my investigations, the promise.then inside the _setMuted function on the lib-jitsi-meet side may not have worked.

A few more users reported the same problem. The situation also occurred in the windows desktop application. It is not always a repeatable situation.

How could this happen? Have you encountered a similar situation before?

Requesting your help and guidance
Thanks

- Jitsi Meet version: 8044
- Operating System: MacOs
- Browser / app version: Desktop app / 8044

**Comment by saghul** [comment]
I'm not aware of such an issue in recent times... any chance you could grab some logs?

**Comment by zeynepbasaranaksu** [comment]
[mute-logs.txt](https://github.com/jitsi/jitsi-meet/files/10824763/mute-logs.txt)
There are some console logs here.

**Comment by B1TSH3LL** [comment]
i would like to work on this issue. please assign this to me. if it isn't solved!

**Comment by piyush09-05** [comment]
I could contribute to this, can you please assign this issue to me?

**Comment by Joy1654** [comment]
@zeynepbasaranaksu claim
