### ISSUE TITLE
JitsiMeetSDK iOS listener not working 

### ISSUE THREAD

**Issue by bellus93** [jitsi/jitsi-meet#12964]
### Description:

I have a native swift application that integrate Jitsi SDK v.7.0.1. In this application I have a custom layout for the meetings  and when I try to call some method in jitsiview I can see an error in log:

[JitsiMeetSDK] Sending `org.jitsi.meet.OPEN_CHAT` with no listeners registered.

or 

[JitsiMeetSDK] Sending `org.jitsi.meet.SET_VIDEO_MUTED` with no listeners registered.

### Steps to reproduce:

1. set as options: 
 -  setFeatureFlag("toolbox.enabled",withValue: false)
 -  setFeatureFlag("audio-mute.enabled", withValue:true)
 - setFeatureFlag("chat.enabled", withValue: true)
3. Create a UIButton 
4. as click action  call jitsiMeetView?.openChat(nil) or jitsiMeetView?.setVideoMuted(true)

### Expected behavior:

I expect chat to open or mute to be activated 

### Actual behavior:

[JitsiMeetSDK] Sending `org.jitsi.meet.OPEN_CHAT` with no listeners registered.
[JitsiMeetSDK] Sending `org.jitsi.meet.SET_VIDEO_MUTED` with no listeners registered.

### Server information:

- Jitsi Meet version: 7.0.1
- Operating System: iOS 16.2

**Comment by saghul** [comment]
Have you made any changes to the SDK? Can you reproduce it with an unmodified SDK?

**Comment by bellus93** [comment]
No i didn't make any changes.. i used only the featured flags to enable or
disable some area

Il sab 25 feb 2023, 12:52 Saúl Ibarra Corretgé ***@***.***>
ha scritto:

**Comment by saghul** [comment]
No news sorry, we've been quite busy :-/
