### ISSUE TITLE
Ongoing meeting push notification always in english language (Android)

### ISSUE THREAD

**Issue by shabanov-krl** [jitsi/jitsi-meet#12975]
### Description:

On Android for change UI language of Jitsi need to change default system language, but ongoing meeting push notification keep english language

![image](https://user-images.githubusercontent.com/46450095/221860293-97560909-2fce-4992-9e59-bc7601b52646.png)

### Steps to reproduce:

1. Join meeting

### Expected behavior:

Ongoing push notification in english language

### Actual behavior:

Ongoing push notification in system language

### Server information:

- Jitsi Meet version: 7.0.1
- Operating System: default jitsi meet server

### Client information:

- Browser / app version: official android sdk example with 7.0.1 sdk version 
- Operating System: Android 13

**Comment by FlavioGoncalves-Cayas** [comment]
I am having the same issue. Why is there no feedback on this? Neither here nor in the forums...
@saghul tagging you for visibility

**Comment by saghul** [comment]
That notification is sent fron the native side so alas it doesn't follow the same translation process than the rest of the JS code.

A PR would be welcome adding translated resources to the Android side.

**Comment by philitell** [comment]
@saghul  Yes this feature would be great - i would like to use it for german clients

**Comment by saghul** [comment]
A PR would still be welcome if you're up for it 👍
