### ISSUE TITLE
Make "Your microphone appears to be noisy" togglable

### ISSUE THREAD

**Issue by trafotin** [jitsi/jitsi-meet#12986]
Hi I keep getting the notification "Your microphone appears to be noisy!" even though I am clearly talking and intend to talk. I was wondering if there was a way to implement the value `enableNoisyMicDetection: true,`  configurable through the API and a checkbox in the UI, so the people who don't want this can turn it off rather than using their instance's settings.

https://github.com/jitsi/jitsi-meet/blob/06110d1dfb72a893f86ecebba9042edf5c0b4393/config.js#L105

**Comment by quitrk** [comment]
@trafotin you could use `config.disabledNotifications` array populated with `toolbar.noisyAudioInputTitle`

**Comment by trafotin** [comment]
> @trafotin you could use `config.disabledNotifications` array populated with `toolbar.noisyAudioInputTitle`

But there's no toggle in the GUI. I'd understand if I were to fork Jitsi, but what if you use an instance you don't own and doesn't have this configuration? When I'm on a call to someone, this popup is universally annoying to everyone I know, and even if it wasn't done in the nicest way, there have been complaints about this and it's never been resolved.

#9273 

Additionally, this notification gets reset if you mute the offending device. For example, this can be replicated if you mute the device, and unmute again, then the notification will appear again. As a compromise, could there be a way where the notification wouldn't appear again unless you change your active microphone?

#5101

**Comment by saghul** [comment]
This have changed in the recent past. With the new settings dialog we do have a good place for such a setting:

<img width="778" alt="Screen Shot 2023-07-07 at 11 52 18" src="https://github.com/jitsi/jitsi-meet/assets/317464/3ed2dd7a-126e-4b65-8091-9badc6d7e01e">

A PR adding the option would be welcome.
