### ISSUE TITLE
as a mobile user i would like to to be able to disallow video on metered connections to avoid unwittingly incurring excessive charges

### ISSUE THREAD

**Issue by KiaraGrouwstra** [jitsi/jitsi-meet#12988]
Presently, Android users get to pick whether to allow video on a meeting level through the low-bandwidth mode.
However, this does not account for the case where a user starts out on an unmetered connection, but ends up losing access this (by walking out of range, by network hickups) and ends up on a metered connection instead, unwittingly incurring excessive charges.

**Describe the solution you'd like**

Have a global setting to automatically disable video on metered connections.

**Describe alternatives you've considered**

- Always pick low-bandwidth mode, foregoing non-verbal communication
- Use Jitsi only on devices without access to metered connections
- Procure lenient data plans
- Pray

**Comment by saghul** [comment]
I am not sure we want to request the necessary permissions to gather that kind of data.

Even if we knew your connection is metered, we won't be able to j is if it's expensive or not.

**Comment by KiaraGrouwstra** [comment]
> Even if we knew your connection is metered, we won't be able to know if it's expensive or not.

Hence I'd make this a setting, such as to leave this up to the user.

> I am not sure we want to request the necessary permissions to gather that kind of data.

I'm under the impression Android allows delaying permission requests. I believe it would be possible to delay requesting such permissions no earlier than once the user opts into this feature. I hope this might empower users to use the software as they prefer without asking more permissions from others.

**Comment by G2G2G2G** [comment]
What would need to be gathered? You have a button to turn on/off video.

**Comment by saghul** [comment]
More detailed xonnection information. We don't know if it's metered.

**Comment by KiaraGrouwstra** [comment]
it seems connection metering may be checked as follows on Android:
https://developer.android.com/training/monitoring-device-state/connectivity-status-type

**Comment by saghul** [comment]
Just to adjust everyone's expectations: we do t have the cycles to dive into this anything soon.

**Comment by G2G2G2G** [comment]
-.-

**Comment by G2G2G2G** [comment]
Why do we need to spam threads? issues exist until they're resolved. Talking more doesn't magically make it better

**Comment by saghul** [comment]
Then don't. There is no momentum here, it's unlikely to get implemented anytime soon.

**Comment by G2G2G2G** [comment]
that isn't relevant, that's the exact reason the thread can just be left open.

**Comment by saghul** [comment]
Feel free to manage your projects the way you want, and stop telling others how to manage theirs.

**Comment by G2G2G2G** [comment]
Nobody told anyone to do anything (other than you telling others what to do) they asked a question
