### ISSUE TITLE
join button not working

### ISSUE THREAD

**Issue by fatima-gloqal** [jitsi/jitsi-meet#12980]
i cloned jitsi long time and it was working until last week when i try to click on join button to join the meeting it doesnt work and i tried to clone the latest version of jitsi stable one and i tried to run it and it gives the same problem i click on join and then its disabled i cannot click anymore, does anyone know the solution for this problem is the server is full ?

https://user-images.githubusercontent.com/79281713/222075987-603ff266-f9c0-47fc-9a3d-653a63fa6a5e.mp4

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

You have an error in the js console preventing some script from loading ... what is that error.

**Comment by fatima-gloqal** [comment]
because in the forum i cannot share video describing the problem

**Comment by fatima-gloqal** [comment]
@damencho  thank you for your quick reply this is the error i'm getting, is this error what is causing the conference to load

<img width="630" alt="Screen Shot 2023-03-01 at 11 36 09 PM" src="https://user-images.githubusercontent.com/79281713/222281588-23bff7ae-bcb8-4125-b7c8-95c286956163.png">

**Comment by denzel-magtheridon** [comment]
Same issue, can you please help me?
