### ISSUE TITLE
Migrate DISPLAY_WELCOME_PAGE_* from interface_config.js to config.js to be update-safe

### ISSUE THREAD

**Issue by ychromosome** [jitsi/jitsi-meet#12998]
**Is your feature request related to a problem you are facing?**
When using the Debian package `jitsi-meet-web` (without the Docker container), the file `/usr/share/jitsi-meet/interface_config.js` gets overwritten during each update of Debian package and any configuration change needs to be re-applied.

The configuration options used/changed are `DISPLAY_WELCOME_PAGE_ADDITIONAL_CARD`, `DISPLAY_WELCOME_PAGE_CONTENT` and `DISPLAY_WELCOME_PAGE_TOOLBAR_ADDITIONAL_CONTENT`.

**Describe the solution you'd like**
As @damencho mentioned in https://github.com/jitsi/jitsi-meet/issues/9208, `/usr/share/jitsi-meet/interface_config.js` is deprecated. https://github.com/jitsi/jitsi-meet/issues/10929 reports more or less the same issue, but for another configuration option and suggests the migration of the configuration options to `config.js`.

Based on this the proper solution is hopefully to migrate `DISPLAY_WELCOME_PAGE_ADDITIONAL_CARD`, `DISPLAY_WELCOME_PAGE_CONTENT` and `DISPLAY_WELCOME_PAGE_TOOLBAR_ADDITIONAL_CONTENT` to `config.js`.

**Describe alternatives you've considered**
Changing the configuration options in `/usr/share/jitsi-meet/interface_config.js` after each update of the Debian package `jitsi-meet-web`. Ideally these configuration options can be made update-safe.

**Comment by saghul** [comment]
Now that we have a `welcomePage` config section it should be pretty straightforward to migrate.

**Comment by robert-scheck** [comment]
Is there an example for a previously migrated option to the `welcomePage` configuration section?

**Comment by saghul** [comment]
Yes, search for enableWelcomePage in the code and you'll see how it got migrated.
