### ISSUE TITLE
Add suppor for GNOME Web (aka Epiphany)

### ISSUE THREAD

**Issue by Odi-3** [jitsi/jitsi-meet#12996]
Please add support for GNOME Web (aka Epiphany). I thought Jitsi Meet would work on Web (it uses WebKit rendering engine like Safari), but it doesn't.

**Comment by saghul** [comment]
What does the JS console say when you open meet.jit.si ?

**Comment by Odi-3** [comment]
What I can tell you is that a page appears where it says: "It looks like you're using a browser we don't fully support."

No errors appear in the JS console.

**Comment by saghul** [comment]
The console should show something like "This looks like XXX version YYY".

**Comment by javierckr** [comment]
My console log show this:
![image](https://user-images.githubusercontent.com/42911254/223461713-217f8aa2-7b97-4c8b-99b0-ed21897866cf.png)

**Comment by saghul** [comment]
It's weird, we detect it as Safari 16, which is expected. Does meet.jit.si work if you override the UA?

**Comment by javierckr** [comment]
It works, with lots of console errors and you can not open camera or mic...

**Comment by saghul** [comment]
I haven't been able to confirm if Epiphany supports WebRTC. Does it? Can you open your camera on this test site? https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by Odi-3** [comment]
I apologize for the error and thank you for your interest in the issue. To answer your last question: no, the camera doesn't work.

**Comment by saghul** [comment]
No worries. I'm afraid there is nothing we can do then, until there is proper support for WebRTC in Epiphany.

**Comment by Odi-3** [comment]
Based on your answer, I think I've found the cause: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1185
So I just have to wait, since WebRTC was recently implemented using GSWebRTC in WebKitGTK+ but which, however, it is still inactive by default: https://webkitgtk.org/2022/07/12/webkitgtk2.37.1-released.html

**Comment by saghul** [comment]
Makes sense. Now we know!
