### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#13]
Make it possible to record a JitMeet conference. This includes audio, video and potentially even text.

**Comment by danboid** [comment]
SimpleScreenRecorder does a great job of this under Linux. I don't see the need to duplicate the functionality under JM.

**Comment by galuel** [comment]
@danboid SSR allows you to record your microphone, but a conference have 2 different audio sources not only one : incoming audio from people connected and your own microphone, so how to run it to record all audio !?

**Comment by danboid** [comment]
@galuel 

Under the SSR Audio Input settings, set the backend to Pulseaudio and the source to "Monitor of built in audio..."

**Comment by ZuzooVn** [comment]
@emcho  Jibri is a set of tools for recording and/or streaming a Jitsi Meet conference.

**Comment by saghul** [comment]
heh, @emcho created the Jitsi project, I bet he knows :-) This issue seems resolved now that we have jibri, closing!

**Comment by carbonrider** [comment]
With Jibri, the suggested approach is to record only one conference at a time. What if there are multiple conferences are going on? Can you please recommend an approach to scale Jibri for multiple conferences.

**Comment by bbaldino** [comment]
@carbonrider you can deploy multiple jibris to an environment to handle multiple recordings.
