### ISSUE TITLE
Failed to build module 'JitsiMeetSDK' from its module interface

### ISSUE THREAD

**Issue by zhanghuiDev** [jitsi/jitsi-meet#13001]
Hello, can I ask if the new version does not support xcode12.4,
Xcode12.4 cannot compile the framework, and xcode13.4 compiled framework xcode12.4 cannot run

The xcode12.4 operation reported the following error:

/Users/imac/Desktop/111/JXScreenShare/SampleHandler.swift:18:8: Failed to build module 'JitsiMeetSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

**Comment by saghul** [comment]
That's right, you need Xcode >= 13.

**Comment by zhanghuiDev** [comment]
Is there any way to temporarily use xcode12

**Comment by saghul** [comment]
I am afraid not, sorry.

**Comment by omershafique0** [comment]
Failed to build module 'JitsiMeet'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.

I'm using Xcode 14.3 and getting this error, any way around?

**Comment by saghul** [comment]
We don't support Xcode 14.3 yet.

**Comment by omershafique0** [comment]
How would I run my project then? can you guide me through

**Comment by saghul** [comment]
You can use Xcode 14.2 and it will work just fine.

**Comment by omershafique0** [comment]
`pod 'MatrixSDK', '~> 0.20.13'`
`pod 'MatrixSDK/JingleCallStack'`
`pod 'MatrixKit', '~> 0.16.11'`
`pod 'MatrixKit/AppExtension'`

These are the version I'm using in my project and getting the error No such module 'JitsiMeet' while building my project.
Any leads on this?

`Xcode version: 14.3`

**Comment by saghul** [comment]
> JitsiMeetSDK (3.10.2)

This SDK is years old and no longer supported.

**Comment by omershafique0** [comment]
is there any way around it? running this because my project is developed based on this SDK

**Comment by saghul** [comment]
You'll need to ask the Matrix folks to update the SDK dependency.
