### ISSUE TITLE
Stop video in a conference in tiled view

### ISSUE THREAD

**Issue by ivanzh89** [jitsi/jitsi-meet#13002]
Jitsi meet pauses video for random users, and doesn't restore on its own in tiled view. Solved by double-clicking on a conference participant, and turning on a tiled view for a specific conference participant. If five participants are not displayed, you need to do this for five. This does not display ninja mode.

### Server information:

- Jitsi Meet version:
ii  jitsi-meet                            2.0.8252-1
ii  jitsi-meet-prosody                    1.0.6943-1
ii  jitsi-meet-turnserver                 1.0.6943-1
ii  jitsi-meet-web                        1.0.6943-1
ii  jitsi-meet-web-config                 1.0.6943-1
ii  jitsi-videobridge2                    2.2-69-gad606ca2-1
ii  lua-basexx                            0.4.1-jitsi1
ii  lua-cjson:amd64                       2.1.0.10-jitsi1

- Operating System: Ubuntu 22.04.2 LTS

### Client information:

- Browser / app version: RocketChat electron
- Operating System: Windows

### Additional information:
/etc/jitsi/videobridge/jvb.conf
videobridge {
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "jitsi.example.com:443"
        tls = true
    }
    cc {
        trust-bwe=false
    }
    apis {
        rest {
           enabled = true
        }
    }
}

 /etc/jitsi/meet/jitsi.example.com-config.js

[07032023.txt](https://github.com/jitsi/jitsi-meet/files/10905578/07032023.txt)

**Comment by saghul** [comment]
> trust-bwe=false

Why did you disable bandwidth estimation?
