### ISSUE TITLE
TypeError: Cannot read property '_navigate' of undefined

### ISSUE THREAD

**Issue by frol** [jitsi/jitsi-meet#1300]
Trying to open meet.jit.si in Google Chrome with old session results in the following error log in console:

```
Uncaught (in promise) TypeError: Cannot read property '_navigate' of undefined
    at s (app.bundle.min.js:23)
    at app.bundle.min.js:23
    at app.bundle.min.js:136
    at app.bundle.min.js:84
    at app.bundle.min.js:85
    at app.bundle.min.js:84
    at app.bundle.min.js:84
    at app.bundle.min.js:84
    at dispatch (app.bundle.min.js:136)
    at o (app.bundle.min.js:23)
```

Incognito mode and other browsers on the same laptop work just fine.

**Comment by lyubomir** [comment]
If you have Redux DevTools installed, please disable it. We discovered the same problem today and narrowed it down to Redux DevTools so I'll look into fixing the problem soon.

**Comment by frol** [comment]
@lyubomir That was it!
