### ISSUE TITLE
Unable to record any Window other than the browser.

### ISSUE THREAD

**Issue by rinmon** [jitsi/jitsi-meet#13034]
When using the recording function
- Full screen.
- screen other than the browser (Google Chrome).
Recording of screens other than the full screen browser (Google Chrome) is not possible.

**Comment by saghul** [comment]
Aare you on macOS? The you need to grant screen sharing permissions in system settings.

**Comment by rinmon** [comment]
Thank you.
I am using Chrome on my Mac to connect to the Jitsi Meet server, which I set up myself.
When recording with Jitsi Meet, I have no problem recording Chrome tabs or the entire Chrome.
However, when I try to record the full screen of the Mac (other applications) or the screens of two displays, I get an error.

**Comment by saghul** [comment]
What type of recording are you using the builtin local recording? In that case we only support recording the actual tab where the meeting is taking place.

**Comment by rinmon** [comment]
Thank you very much. I understood that the standard support is for recording within Chrome. This will be supported by a third party.

**Comment by rinmon** [comment]
Thanks. I, like the ZOOM application, am hoping for the ability to record shared objects outside of the browser screen only on JITSIMEET. If that's not possible, then I'll have to give up; I'd like to see it accomplished either by a small vibrator app in JITSIMEET or by a mechanism that works asynchronously with the browser.

**Comment by saghul** [comment]
I'll try one last time.

What is it exactly that you want?

Local recordings ONLY record the meeting, there is no way around that.

If you use cloud recording and share your screen the recording will contain all of that.

Jitsi Meet is not Zoom nor do we intend to build everything they have.

**Comment by rinmon** [comment]
Thanks for the response, I will try to get back to you on that.

>Jitsi Meet is not Zoom, nor do we intend to build all of Zoom.

Exactly! That's why we want to go beyond what ZOOM has to offer.
I will try cloud recording once.
For example, I want to hold a meeting with VSCode and PowerPoint Window as a share while doing Jitsi Meet and record it.
