### ISSUE TITLE
Can't see other peoples screen shares on librewolf 110.0-2 (meet.jit.si)

### ISSUE THREAD

**Issue by notmentaloutlaw** [jitsi/jitsi-meet#13035]
I have posted another issue on this before, which I followed up with the librewolf team over at gitlab https://gitlab.com/librewolf-community/browser/gentoo/-/issues/55. However, I am still experiencing an issue where I can't see other people's streams unless I am in troubleshoot mode. Here are some logs:

I have created a brand new profile in order to reset all the settings etc however I can't view other's screens:
[new_profile_cant_see_others_share.txt](https://github.com/jitsi/jitsi-meet/files/10949338/new_profile_cant_see_others_share.txt)

This is the log where I am in trouble shoot mode and I can see other people's screen shares:
[troubleshootmode_can_see_others_share.txt](https://github.com/jitsi/jitsi-meet/files/10949342/troubleshootmode_can_see_others_share.txt)

Please let me know if there is anything else you would like me to add.

**Comment by notmentaloutlaw** [comment]
This is an issue with firefox itself and I have to file a bug report with them.

**Comment by saghul** [comment]
Please drop a link to the bug when you file it.

**Comment by notmentaloutlaw** [comment]
This fixes the issue https://bugzilla.mozilla.org/show_bug.cgi?id=1834227 and probably from firefox 114 onward it will no longer be present.
