### ISSUE TITLE
 Android : ongoing notification tap hangup the meeting 

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#13048]
Ongoing notification, below screenshoot, click hangup the ongoing meeting. Ongoing notification click event should open the meeting screen.

![Screenshot_20230314](https://user-images.githubusercontent.com/1655033/225085748-2d228bfa-ef91-49bd-b69b-c531d173a20b.png)

**Steps to reproduce:**

1. join the meeting
2. minimize the application, click the ongoing notification

**Expected behavior:**
Meeting screen should be opened on notification click

**Actual behavior:**
Hangup the ongoing meeting

**Jitsi Meet version: 5.1.0**

**Operating System: Android 11**

**Comment by saghul** [comment]
Please test with the latest SDK, 5.1.0 is really old at this point.

**Comment by vinayseasia** [comment]
I tested with 7.0.1
[https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#701-2022-12-08]

same issue is there.

**Comment by saghul** [comment]
I have been unable to reproduce this with our latest beta app version. I don't remember fixing anything related to this, but be that as it may, it will be part of the next SDK release which is due shortly.

**Comment by vinayseasia** [comment]
okay thanks.
yes, same for me. On your beta build I am not able to reproduce but the demo I created have only the code from yours [documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk/#using-the-api). So it's strange..
