### ISSUE TITLE
Video turned off to save bandwidth on jibri

### ISSUE THREAD

**Issue by javierckr** [jitsi/jitsi-meet#13059]
### Description:
We made about 50 recordings per day with jitsi meet, jibri and youtube but randomly in some recordings, the recorder(jibri) says 
"Video turned off to save bandwidth".
The videobridge and the jibri are on the same cloud zone, we've tested bandwidth issues with iperf3 and we have 0 packet loss between the videobridge and the jibri, which is telling video turned off...
If we join the recorded meeting with another computer we could see the camera without problems, it seems to be a bad bandwidth estimation bwe.
### Steps to reproduce:
It's difficult to reproduce this issue, but we are monitoring this issue with this script:
```
#!/bin/bash
# monitorjibribwe.sh
# This script monitors the jvb logs for bandwidth issues with the jibri

tail -f /var/log/jitsi/jvb.log | while read LOGLINE
do

    echo $LOGLINE | grep -q "stats_id=jibri" &&\
        echo $LOGLINE | grep -q "Sources suspended due to insufficient bandwidth" &&\
        echo $LOGLINE | sed s/.*bwe=// | cut -d ' ' -f 1 | (( $(cat /dev/stdin) < 600000 )) &&\
        echo "Jibri bandwidth issue $(date): $LOGLINE" | mail -s "Jibri bandwidth issue" example@example.com ,\
        example1@example.com &&\
        sleep 5
done
```

### Server information:

- Jitsi Meet version: 
   jitsi-meet-prosody                 1.0.6600-1
   jitsi-meet-web                        1.0.6854-1
   jitsi-meet-web-config            1.0.6854-1
   jitsi-videobridge2                   2.2-63-g252d14bc-1
   jibri chrome                             108.0.5359
   jibri                                            8.0-140-gccc7278-1
   But we had this issue on older versions too
- Operating System: Debian 10

### Client information:

- Browser / app version: Latest Google Chrome
- Operating System: Ubuntu 22.04, Arch Linux, Ubuntu 20.04

### Additional information:
Probably this bwe issue affects other users, but you could easily solve it by reloading the page. 
The recorder doesn't reload the page so you end with a recording of a black screen.

**Comment by javierckr** [comment]
We have noticed that this issue is also happening without the message "Video turned off to save bandwidth".
Have you faced any of these issues?
In our config.js we use the default values except: "enforcePreferredCodec: true" and "preferredCodec: 'VP9'", we block firefox browsers because vp9 is not working on firefox. Could this issue be related to vp9 codec?

**Comment by saghul** [comment]
I don't think it's codec related though it might have an effect if the Jibri machine is not very powerful, since it consumes more cpu.

**Comment by javierckr** [comment]
These are the cpu and latency logs of a jibri that make a black recording saying "Video turned off to save bandwidth":

```
Jun  1 10:26:44 autojibri23 root: CPU Usage: 0.3% Load: 1.87 - NumProcs: 2/190 MemUsed: 357Mi - MemFree: 7.1Gi Youtube: 1.130ms jitsipro03: 1.458ms
Jun  1 10:27:14 autojibri23 root: CPU Usage: 63% Load: 1.99 - NumProcs: 3/264 MemUsed: 505Mi - MemFree: 6.8Gi Youtube: 1.297ms jitsipro03: 1.469ms
Jun  1 10:27:45 autojibri23 root: CPU Usage: 22.6% Load: 1.77 - NumProcs: 2/337 MemUsed: 673Mi - MemFree: 6.4Gi Youtube: 1.194ms jitsipro03: 1.823ms
Jun  1 10:28:16 autojibri23 root: CPU Usage: 28% Load: 2.59 - NumProcs: 3/330 MemUsed: 699Mi - MemFree: 6.3Gi Youtube: 0.997ms jitsipro03: 2.528ms
Jun  1 10:28:47 autojibri23 root: CPU Usage: 20.7% Load: 1.86 - NumProcs: 5/325 MemUsed: 700Mi - MemFree: 6.3Gi Youtube: 1.039ms jitsipro03: 1.324ms
Jun  1 10:29:17 autojibri23 root: CPU Usage: 20.3% Load: 1.43 - NumProcs: 4/323 MemUsed: 701Mi - MemFree: 6.3Gi Youtube: 1.245ms jitsipro03: 1.559ms
Jun  1 10:29:47 autojibri23 root: CPU Usage: 20.2% Load: 0.86 - NumProcs: 2/320 MemUsed: 708Mi - MemFree: 6.3Gi Youtube: 1.316ms jitsipro03: 1.613ms
Jun  1 10:30:17 autojibri23 root: CPU Usage: 21.3% Load: 0.75 - NumProcs: 3/319 MemUsed: 708Mi - MemFree: 6.3Gi Youtube: 1.230ms jitsipro03: 1.422ms
Jun  1 10:30:48 autojibri23 root: CPU Usage: 21.3% Load: 1.81 - NumProcs: 2/320 MemUsed: 711Mi - MemFree: 6.3Gi Youtube: 0.944ms jitsipro03: 1.644ms
Jun  1 10:31:18 autojibri23 root: CPU Usage: 22.1% Load: 1.50 - NumProcs: 2/319 MemUsed: 722Mi - MemFree: 6.3Gi Youtube: 1.313ms jitsipro03: 1.242ms
Jun  1 10:31:49 autojibri23 root: CPU Usage: 21.7% Load: 1.04 - NumProcs: 2/316 MemUsed: 728Mi - MemFree: 6.3Gi Youtube: 1.320ms jitsipro03: 1.287ms
Jun  1 10:32:20 autojibri23 root: CPU Usage: 21.2% Load: 0.63 - NumProcs: 4/317 MemUsed: 735Mi - MemFree: 6.3Gi Youtube: 1.089ms jitsipro03: 1.498ms
Jun  1 10:32:51 autojibri23 root: CPU Usage: 20.8% Load: 0.89 - NumProcs: 3/321 MemUsed: 733Mi - MemFree: 6.3Gi Youtube: 1.144ms jitsipro03: 1.541ms
Jun  1 10:33:21 autojibri23 root: CPU Usage: 22.1% Load: 1.79 - NumProcs: 3/324 MemUsed: 731Mi - MemFree: 6.3Gi Youtube: 1.262ms jitsipro03: 1.594ms
Jun  1 10:33:51 autojibri23 root: CPU Usage: 20.4% Load: 1.54 - NumProcs: 3/318 MemUsed: 736Mi - MemFree: 6.3Gi Youtube: 1.206ms jitsipro03: 1.452ms
Jun  1 10:34:21 autojibri23 root: CPU Usage: 43.6% Load: 1.55 - NumProcs: 5/330 MemUsed: 757Mi - MemFree: 5.8Gi Youtube: 1.254ms jitsipro03: 1.293ms
Jun  1 10:34:52 autojibri23 root: CPU Usage: 20.5% Load: 1.11 - NumProcs: 2/322 MemUsed: 737Mi - MemFree: 5.8Gi Youtube: 1.297ms jitsipro03: 1.375ms
Jun  1 10:35:23 autojibri23 root: CPU Usage: 21.3% Load: 0.74 - NumProcs: 4/324 MemUsed: 740Mi - MemFree: 5.8Gi Youtube: 1.339ms jitsipro03: 1.445ms
Jun  1 10:35:54 autojibri23 root: CPU Usage: 21.3% Load: 2.05 - NumProcs: 2/323 MemUsed: 739Mi - MemFree: 5.8Gi Youtube: 1.259ms jitsipro03: 2.064ms
Jun  1 10:36:25 autojibri23 root: CPU Usage: 20.6% Load: 1.46 - NumProcs: 6/318 MemUsed: 730Mi - MemFree: 5.8Gi Youtube: 1.194ms jitsipro03: 1.593ms
Jun  1 10:36:55 autojibri23 root: CPU Usage: 29% Load: 1.02 - NumProcs: 3/319 MemUsed: 733Mi - MemFree: 5.8Gi Youtube: 1.193ms jitsipro03: 1.534ms
Jun  1 10:37:25 autojibri23 root: CPU Usage: 20.7% Load: 0.73 - NumProcs: 4/316 MemUsed: 734Mi - MemFree: 5.8Gi Youtube: 1.231ms jitsipro03: 1.369ms
Jun  1 10:37:56 autojibri23 root: CPU Usage: 20.5% Load: 0.92 - NumProcs: 2/318 MemUsed: 732Mi - MemFree: 5.8Gi Youtube: 1.126ms jitsipro03: 1.220ms
Jun  1 10:38:27 autojibri23 root: CPU Usage: 20.4% Load: 1.72 - NumProcs: 2/320 MemUsed: 740Mi - MemFree: 5.8Gi Youtube: 1.228ms jitsipro03: 1.701ms
Jun  1 10:38:58 autojibri23 root: CPU Usage: 21.6% Load: 1.77 - NumProcs: 2/317 MemUsed: 739Mi - MemFree: 5.8Gi Youtube: 1.230ms jitsipro03: 1.693ms
Jun  1 10:39:29 autojibri23 root: CPU Usage: 22.7% Load: 1.11 - NumProcs: 3/319 MemUsed: 740Mi - MemFree: 5.8Gi Youtube: 1.296ms jitsipro03: 1.301ms
Jun  1 10:39:59 autojibri23 root: CPU Usage: 22.6% Load: 0.80 - NumProcs: 3/321 MemUsed: 741Mi - MemFree: 5.8Gi Youtube: 1.243ms jitsipro03: 1.508ms
Jun  1 10:40:29 autojibri23 root: CPU Usage: 20.5% Load: 0.56 - NumProcs: 2/319 MemUsed: 742Mi - MemFree: 5.8Gi Youtube: 1.215ms jitsipro03: 1.421ms
Jun  1 10:41:00 autojibri23 root: CPU Usage: 24.2% Load: 1.88 - NumProcs: 2/319 MemUsed: 742Mi - MemFree: 5.8Gi Youtube: 1.375ms jitsipro03: 1.623ms
```

With these logs it doesn't seem to be a bandwidth or cpu issue.

**Comment by saghul** [comment]
How about the ffmpeg logs?

**Comment by javierckr** [comment]
Here are the ffmpeg  and the statuscheck logs, the ffmpeg bitrate is low because it's sending a black screen to youtube.
I think this issue is not related to ffmpeg as ffmpeg only makes a screenrec of the chromium.
[Statuscheck.log](https://github.com/jitsi/jitsi-meet/files/11624516/Statuscheck.log)
[ffmpeg.log](https://github.com/jitsi/jitsi-meet/files/11624467/ffmpeg.log)

**Comment by saghul** [comment]
The speed is good, around 1x which means it's not constrained by the system.

Is the network between Jibri and the JVB good?

**Comment by javierckr** [comment]
We tested with iperf3 and there is a good network, the latency should be about 1 ms, they are on the same cloud zone.

**Comment by saghul** [comment]
Any packet loss?

Can you consistently reproduce the problem?

**Comment by javierckr** [comment]
In the tests we did with iperf3 we had 0 packet loss, this problem happens in about 1 of 100 recordings.

**Comment by saghul** [comment]
Then it must be some transient condition or it would happen all the time.

Not sure there is anything we can do about it.

**Comment by saghul** [comment]
Most likely. The recording is written onto the storage so it's likely it was backed up and thus ffmpeg consumed more resources and caused Chrome to not have enough.

**Comment by hshaharia064** [comment]
im facing the same issue, the video goes of with the message 'the video has been diabled to save bandwidth, i have tried adjusting the simulcast, lastN, resolution, bitrate, i have self hosted on a 10vcpu vps, and its bandwidth is enough (2tb), also the uplink/downlink is 3Gbps, how to get rid of that

**Comment by pzw520125** [comment]
I also encountered the same problem. Has anyone solved it?

**Comment by hshaharia064** [comment]
> I also encountered the same problem. Has anyone solved it?

Yeah.... Check you internet speed. I solved it by using a highspeed internet and no issues were faced
