### ISSUE TITLE
left the meeting  after clicking stats button

### ISSUE THREAD

**Issue by 297297sid** [jitsi/jitsi-meet#13051]
Please take a look at the images linked to this thread and give me advice on where to make changes to resolve the problem I'm having with Jitsi Meet version 2.0.8044 anytime I click on the stats button during title view and the video on it closes the meeting.
![is](https://user-images.githubusercontent.com/97450680/225209173-477f49fd-2fb6-49f7-ae6d-1564481d4bfd.jpeg)
![is2](https://user-images.githubusercontent.com/97450680/225209191-ebe0a916-3090-45e2-94a5-bd7bf4813152.jpeg)

**Comment by saghul** [comment]
Can you check your browser console logs?
