### ISSUE TITLE
Firefox: unable to select webcam if combined infrared webcam is present

### ISSUE THREAD

**Issue by md-work** [jitsi/jitsi-meet#13062]
### Description:

Some notebooks have webcams which appear as 4 `/dev/video*` devices and show up as two webcams in Jitsi-Meet inside Firefox. If another external USB webcam is connected the whole webcam selection menu gets broken.  

_Notes:_  
_Common scenario if the notebook is in a docking station with lid closed._  
_These combined infrared webcams seems to become more common because of [Microsoft Hello requirements](https://en.wikipedia.org/w/index.php?title=Windows_10&oldid=1144760643#System_security)._

&nbsp;

### Steps to reproduce:

1. Use a notebook with combined infrared webcam.
2. Connect another normal USB webcam.
3. Try to change the webcam selection via the Jitsi-Meet menu in Firefox.

&nbsp;

### Expected behavior:

Can select a webcam.

&nbsp;

### Actual behavior:

Whole Jitsi-Meet webcam selection menu is broken.
![grafik](https://user-images.githubusercontent.com/29978077/225626977-c54cbeef-1a14-4172-ae7c-6996e5bceb29.png)

&nbsp;

### Server information:

- Jitsi Meet version: [meet.jit.si](https://meet.jit.si/) and `2.0.8319-1` on custom Debian-10 server _(both tested with same result)_

&nbsp;

### Client information:

- Browser / app version: Firefox-111.0
- Operating System: openSUSE-15.4 and Debian-11 _(both tested with same result)_

&nbsp;

### Additional information:

Workaround: Select webcam via settings menu.
![grafik](https://user-images.githubusercontent.com/29978077/225627380-89951dd1-34b4-4c28-8988-d4e3c37c1723.png)

&nbsp;

&nbsp;

**Notebooks:**

HP EliteBook 845 G8  
_Internal and external camera connected:_  
```bash
$ ls -lAhs /dev/video*
0 crw-rw----+ 1 root video 81, 0 Mar 15 10:39 /dev/video0
0 crw-rw----+ 1 root video 81, 1 Mar 15 10:39 /dev/video1
0 crw-rw----+ 1 root video 81, 2 Mar 15 10:39 /dev/video2
0 crw-rw----+ 1 root video 81, 3 Mar 15 10:39 /dev/video3
0 crw-rw----+ 1 root video 81, 4 Mar 16 14:11 /dev/video4
0 crw-rw----+ 1 root video 81, 5 Mar 16 14:11 /dev/video5
$ lsusb | grep Camera
Bus 005 Device 069: ID 0c45:636b Microdia Terra HD1080PC Camera
Bus 001 Device 002: ID 04f2:b6bf Chicony Electronics Co., Ltd HP HD Camera
```

&nbsp;

HP EliteBook 735 G6  
_Just internal camera connected:_  
```bash
# ls -lAhs /dev/video*
0 crw-rw----+ 1 root video 81, 0 16. Mär 13:57 /dev/video0
0 crw-rw----+ 1 root video 81, 1 16. Mär 13:57 /dev/video1
0 crw-rw----+ 1 root video 81, 2 16. Mär 13:57 /dev/video2
0 crw-rw----+ 1 root video 81, 3 16. Mär 13:57 /dev/video3
$ lsusb | grep Camera
Bus 003 Device 003: ID 04ca:7089 Lite-On Technology Corp. HP HD Camera
```

**Comment by saghul** [comment]
What does the browser JS console say?

**Comment by stunivention** [comment]
I can confirm the problem (Firefox 118 on Ubuntu 22.04). How can I re-open the issue?

**Comment by stunivention** [comment]
> Can you reproduce the problem on meet.jit.si ?

I don't have an account there, but it happends even in the onboarding situation -- see Screenshot:

- the onboard cam of my notebook is pre-selected -- it is black due to a hardware barrier
- while trying to choose the USB Cam there are two issues: 1. the onboard cam is shown twice 2. the other cam fails and can't be selected

![grafik](https://github.com/jitsi/jitsi-meet/assets/26623205/48d657db-999e-472b-9bef-68270c044e02)

**Comment by md-work** [comment]
> > Can you reproduce the problem on meet.jit.si ?
> 
> I don't have an account there, but it happends even in the onboarding situation -- see Screenshot:
> [...]

Just select to open a meeting at https://https://meet.jit.si/ . Then there will be a prompt to login with an account created at GitHub (Microsoft), Google or Facebook.

**Comment by stunivention** [comment]
> > > Can you reproduce the problem on meet.jit.si ?
> > 
> > 
> > I don't have an account there, but it happends even in the onboarding situation -- see Screenshot:
> > [...]
> 
> Just select to open a meeting at https://https://meet.jit.si/ . Then there will be a prompt to login with an account created at GitHub (Microsoft), Google or Facebook.

yeah, sorry, but I don't want to create more places storing and potentially distributing my personal information if not needed. I can already reproduce it while trying to join a meeting as guest, so I don't see a need here.

**Comment by saghul** [comment]
If it reproduces in the pre-join page that's enough.

This is very weird. Does the same happen with a Chromium based browser?

**Comment by stunivention** [comment]
> This is very weird. Does the same happen with a Chromium based browser?

No, Brave & Chromium work fine. I switched back to Firefox ~3 months ago and this happens also in an other Jitsi deployment that I use, and it happens also for other Firefox users.
