### ISSUE TITLE
Jitsi not showing up on F-droid + screenshot

### ISSUE THREAD

**Issue by jasonbrown1965** [jitsi/jitsi-meet#13081]
### Description:

Searching for "Jitsi" on F-droid android returns "No matching applications available." 

### Steps to reproduce:

1. Open F-droid
2. Click on search
3. Type in "jitsi" also "Jitsi" 

### Expected behavior:

That Jitsi will show up in f-droid search pages, as per [this page](https://f-droid.org/en/packages/org.jitsi.meet/) on the website. 

### Actual behavior:

"No matching applications available." 
Screenshot attached.

### Server information:

- Jitsi Meet version: not available
- Operating System: ? win 10 ?

### Client information:

- Browser / app version: not available
- Operating System: f-droid on android 11

### Additional information:

Happy to share logs or whatever.

![image](https://user-images.githubusercontent.com/11400799/226152197-f3d98130-12cc-4daa-a6c8-9de01d1f76ce.png)

**Comment by saghul** [comment]
We have no control over the f-droid repository. You'll need to ask this question on the f-droid mailing-list / forum / issue tracker.

**Comment by licaon-kter** [comment]
@jasonbrown1965 shows up fine, not sure what happened there for you, maybe you didn't download (update) the index
