### ISSUE TITLE
How to console.log Connection details in Jitsi IFrame API

### ISSUE THREAD

**Issue by Jagroop-RTE** [jitsi/jitsi-meet#13088]
Currently we are facing problem like sometime for some user's jitsi is not working properly  but the worst thing is that we don't know their network status unitll they hover network tower .

Is it possible to console.log **Connection** Details in Jitsi ?

**Comment by saghul** [comment]
The connection quality information is not currently available via API.

It would be interesting to expose that information indeed.

**Comment by Jagroop-RTE** [comment]
@saghul If we use **8x8 Jitsi as a Service** then it is possible in that case ?

**Comment by saghul** [comment]
It's no different.
