### ISSUE TITLE
Android app to Android app calls not usable

### ISSUE THREAD

**Issue by atomjump** [jitsi/jitsi-meet#13111]
### Description:

When an Android phone, with the app installed, calls _one_ other Android phone with the app installed (both ver 22.7.1), there are audio and video interference/pauses which make a call impossible.  When there are other users on the call, on different platforms, such as Windows, the audio and video are fine on the Android phone app.

Tested on meet.jit.si

### Client information:

- Browser / app version: 22.7.1
- Operating System: Android on both

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Can you try (while not in a call) open settings and disable peer to peer mode. Does that change anything?

**Comment by atomjump** [comment]
No problem, will post on the J community forums, sorry. Also confirming that when we disabled peer-2-peer the problem went away. This is a good workaround for us personally, immediately, and we have notified our users of the workaround too.
