### ISSUE TITLE
Conference focus not available

### ISSUE THREAD

**Issue by gitzhang** [jitsi/jitsi-meet#1312]
I use ubuntu repository to install jitsi-meet
And I fill ip to hostname.

when i open index.html . I got error message.

![image](https://cloud.githubusercontent.com/assets/2832192/22859701/50eb1f64-f120-11e6-8b02-91c35308fdcb.png)

**Comment by gitzhang** [comment]
"192.168.1.185" is reconfiged in /etc/jitsi/meet/192.168.1.185-config.js . default focus is 'focus.192.168.1.185'

**Comment by sanjeevghimire** [comment]
what was the fix @gitzhang

**Comment by sanjeevghimire** [comment]
I am also seeing the same issue after doing the quick install

**Comment by chris-dk** [comment]
I get the same error message and can't find the problem. Can somebody help us please? :)

**Comment by bamania8** [comment]
Dear Chris/sanjeev,
Kindly check status of the jicofo service....
Start it in-case it is stopped.

**Comment by sanjeevghimire** [comment]
the issue was with Centos. I moved to ubuntu.
