### ISSUE TITLE
 DTMF is not working on mobile apps?

### ISSUE THREAD

**Issue by iim-norse** [jitsi/jitsi-meet#13128]
I am using `dispatch(sendTones(number, 150, 40));`
For web (React) it works, but for react native no
![image](https://user-images.githubusercontent.com/99746223/228472208-dd37be02-9534-4505-b7a1-9cc849e27721.png)
```
2023-03-27 13:12:38.540587+0300 jitsi-meet[6188:472393] [JitsiMeetSDK] [modules/RTC/TraceablePeerConnection.js] [iim] 2!this._dtmfSender LocalTrack[1,audio]
2023-03-27 13:12:38.540650+0300 jitsi-meet[6188:472393] [JitsiMeetSDK] [modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] sendTones - failed to select DTMFSender
```
for web log is:
`initialized DTMFSender using getSenders` 
and everything works

can you please point me a way why on react native miss DTMFSender ? is this miss configuration or something

**Comment by saghul** [comment]
Sending DTMF is not supported in the mobile apps.

**Comment by Chaman-Sahu-iOS** [comment]
Are there any updates on the Above Issue? I am also facing the same with React Native Mobile Apps

**Comment by saghul** [comment]
No updates, there is still no support for DTMF on rn-webrtc.

**Comment by iim-norse** [comment]
@Chaman-Sahu-iOS we apply patch for webrtc with this changes https://github.com/react-native-webrtc/react-native-webrtc/pull/1293 to be able use dtmf on mobiles

**Comment by Chaman-Sahu-iOS** [comment]
Thanks, @iim-norse  for the prompt response. Please ping me here once the PR is merged.
