### ISSUE TITLE
Join breakout room directly when joining meeting

### ISSUE THREAD

**Issue by Ayko1595** [jitsi/jitsi-meet#13138]
**Is your feature request related to a problem you are facing?**
Currently, you can create breakout rooms in Jitsi before the meeting has started but there does not seem to be a way to connect to a specific breakout room directly. You still have to join the meeting and then select the breakout room in the participants list.

**Describe the solution you'd like**
Perhaps this could be added as part of the url? There seems to be a lot of config options through the url and this would be added as an extra query parameter: 

`/roomname#config.breakoutRoom="1"`

**Comment by damencho** [comment]
At the moment there is no way to find a breakout room name in order to join it. You need to join the main conference, receive the breakout rooms and then join the chosen breakout room. Discovering breakout rooms for a room outside of the room needs to be authenticated in some way as there are checks to be done, whether you are allowed to do so. It is a complicated matter. Just mentioning for completeness.

**Comment by Ayko1595** [comment]
@damencho Alright, thank you for the quick reply! Yes I suspected that that was the case. Would an alternative be that the participant is redirected to the main conference if it fails to find the appropriate room?

**Comment by Ayko1595** [comment]
Well in the aforementioned scenario I was thinking in line with these steps:

**Person creating the meeting**:
1. Create meeting
2. Create breakout rooms (1, 2)
3. Send out link to participants with `/roomname#config.breakoutRoom="1"`

**Participant**:
1. Participant clicks link
2. Participant joins main conference
3. Client receives existing breakout rooms
4. Jitsi reads URL parameter and identifies breakoutRoom="1"
5. Redirect participant to breakoutRoom 1

In this scenario the url does not guarantee that the breakout room exists (the breakout rooms are fetched when the participant joins the main conference as you mentioned) but will then redirect on the client if the specified room number exists in the conference.

Is this feasible? 🙂

**Comment by damencho** [comment]
Yeah, this scenario is possible. I'm not sure that room number is the correct way to do it as I'm not sure the order is guaranteed, I guess id is better.

**Comment by Ayko1595** [comment]
Okay! Thank you for your response. Would this feature be accepted into the main repository?

**Comment by saghul** [comment]
I don't see why not.

**Comment by Ayko1595** [comment]
Hello again! I am going to take on this feature request. Is there a way to assign myself to it?

**Comment by saghul** [comment]
We don't assign issues on GH, if you'd like to work on it (thank you!) you can just send a PR when ready.
