### ISSUE TITLE
"Activity Not Responding" while user trying to share the screen 

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#13131]
**Steps to reproduce:**

1. join the meeting
2. starts screen sharing 

**Expected behavior:**
Screen should be shared

**Actual behavior:**
ANR dialog appers

**Jitsi Meet version:** [7.0.1](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#701-2022-12-08)

**AGP version       :    4.2.2
Gradle version   :    7.4.2
CompileSdk       :    33,
MinSdk               :    26,
TargetSdk          :    32,
java                     :    11
Android OS        :    12 (Samsung Galaxy S20)
Android Studio  :    Chipmunk | 2021.2.1 Patch 1 Build #AI-212.5712.43.2112.8609683, built on May 18, 2022**

![Screen Shot 2023-03-29 at 9 50 41 PM](https://user-images.githubusercontent.com/1655033/228605346-b125f84e-f624-40b1-add0-7acdc7bc804f.png)

**Comment by saghul** [comment]
Aaare you able to reproeuce this with the latest Jitsi Meet app version?

**Comment by saghul** [comment]
No. We have not been able to reproduce it.

**Comment by mhamed0httb** [comment]
I also got the same problem with **Jitsi** version 6.0.0, **compileSdkVersion** 33, running on Android 13 with Samsung Galaxy S21, when trying to share the screen, the ANR dialog appears, is there any possibility to identify the problem ?
