### ISSUE TITLE
Firefox: Screen sharing will be frozen when sharing secondary monitor

### ISSUE THREAD

**Issue by sontran-nals** [jitsi/jitsi-meet#13134]
### Description:

While using secondary monitor and screen sharing. The desktop screen will freeze.

### Steps to reproduce:

1. Access a meet.jit.si room on firefox browser and second user on any browser
2. Firefox user share secondary screen
3. Perform any action on the shared screen

### Expected behavior:

On firefox browser, when using secondary monitor screen sharing function can work properly

### Client information:

- Firefox / app version: 111.0.1
- Operating System: macOS montery (12.0.1)

### Evidence:

https://user-images.githubusercontent.com/86598557/228721608-6cf1ba3d-aa05-4839-a2d2-c9c149f4ba43.mp4

**Comment by TheHussein** [comment]
I came here cause I'm having the same issue with google meets. Maybe this is a firefox issue?

**Comment by fippo** [comment]
@pehrsons might know of any current bugs

**Comment by Pehrsons** [comment]
You sure this was Firefox 111? Because we had a regression like this in 112 that was fixed just before release (rc2): https://bugzilla.mozilla.org/show_bug.cgi?id=1826483
