### ISSUE TITLE
Jitsi screensharing chrome extension popup ask fails to appear for first-time screensharer user when the jitsi iframe is embedded

### ISSUE THREAD

**Issue by lpatmo** [jitsi/jitsi-meet#1315]
In Chrome, when I click to screenshare for the first time while on a jit.si link such as meet.jit.si/helpeless, I automatically see a popup that asks me to install the Chrome extension that'll let me screenshare:
![screen shot 2017-02-13 at 1 30 11 am](https://cloud.githubusercontent.com/assets/4512699/22877914/767783fa-f18c-11e6-99d0-52fcb7d307d3.jpg)

However, when I click to screenshare for the first time on an *embedded* jitsi iframe -- such as in 
https://jsfiddle.net/1vq278cj/3/ (please test this using an incognito window to ensure the screensharing plugin is not installed) -- the Chrome extension popup never appears, and all I see is the "Failed to install desktop sharing extension" alert box, which is what I would've seen if I had clicked 'cancel' on that Chrome extension popup.

![screen shot 2017-02-13 at 1 36 50 am](https://cloud.githubusercontent.com/assets/4512699/22878117/47961b7c-f18d-11e6-9229-cfcc10837294.jpg)

 The problem, of course, is that I never saw it in the first place. And this only happens when the jitsi iframe is embedded, not when I'm accessing the jitsi via a http://jit.si/example link.

**Comment by saghul** [comment]
Hi,

This is due to Chrome not allowing ifames to install extensions directly. In beta.mett.jit.si we changed the popup to direct users to the Chrome Store for installing the extension. Can you give that a go? I made a quick check here: https://jsfiddle.net/c2opzqn1/1/ and I see the new popup. (The link is not followed but I guess it's a jsfiddle thing?)

**Comment by saghul** [comment]
Double-checked using a local copy of the file and the popup is shown correctly.

**Comment by lpatmo** [comment]
@saghul Thank you!! Do you have an idea of when Jitsi beta will be released, or where I can find that information? Or should I be asking in one of the mailing threads?

**Comment by lpatmo** [comment]
@saghul I tested using `beta.meet.jit.si` locally in Chrome, and it works very well! :) Unfortunately I just saw that Safari has the problem I talked about in this thread, heh. I can file a separate issue for Safari if that's helpful.

**Comment by saghul** [comment]
@lpatmo Thanks!  We are aiming  for a release this week.

**Comment by saghul** [comment]
Let's continue the Safari issue on its dedicated issue, this can now be closed.
