### ISSUE TITLE
You have been disconnected 

### ISSUE THREAD

**Issue by Micraow** [jitsi/jitsi-meet#13150]
### Description:

On debian 11，self-hosted,  without NAT or Firewall,  using quick installation,  let's encrypt for SSL certification,  I get "You have been disconnected... join again in .. s"
I followed the guide step by step,  on my server,  I have runned some other services but they don't use ports that jitis use.  When I install,  there was no warning or error.  The jitis website on my server can be open with https,  but when i create a room and join,  It says that i have been disconnected. 

i tested on android,  windows, linux, ios with firefox and chrome,  none of them worked. 

my domain is   meet.pengs.top. 

I hope you can help me,  thank you. 

p. s.  I am not an English speaker,  so there may be some mistakes in my words,  sorry.

**Comment by Micraow** [comment]
here are some prosody's log

`Apr 02 22:00:28 portmanager     error   Error binding encrypted port for https:
No certificate present in SSL/TLS configuration for https port 5281
Apr 02 22:00:28 portmanager     error   Error binding encrypted port for https:
No certificate present in SSL/TLS configuration for https port 5281`

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Open you browser js console logs to check the errors. There you can see `CONFERENCE FAILED: conference.focusDisconnected` this means to check your jicofo logs for errors.
