### ISSUE TITLE
No notifications about muted in tiles view in BETA version of Jitsi Meet mobile app for Android

### ISSUE THREAD

**Issue by klebanj** [jitsi/jitsi-meet#13173]
### Description:

Notifications about audio muted aren't shown in tiles view in BETA Jitsi Meet mobile app for Android. 

### Steps to reproduce:

1. User 1 from web browser creates room A
2. User 2 joins room A from Android mobile app. User 2 has microphone enabled
3. User 2 enables tiles view in mobile app. 
4. User 1 mutes User 2.  

### Expected behavior:

User 2 should see notification about muted

### Actual behavior:

No notifications. 

### Server information:

https://meet.jit.si/room1291
Bug reproducted 05.04.2023.

### Client information:

Browser: Google Chrome 111.0.5563.110
Operating System: Ubuntu 22.04.02 LTS

Mobile App: 23.0.0 build 13326597
Mobile Phone: Huawei P30 Pro with Android 12 

### Additional information:
Notifications are visible in tiles view in current stable Jitsi Meet mobile app.

**Comment by saghul** [comment]
@Calinteodor PTAL

**Comment by saghul** [comment]
Cannot reproduce this with the latest beta.

![image](https://user-images.githubusercontent.com/317464/232421561-da8f1d73-2a9d-4858-8b94-c64fae3fc7ba.jpeg)
