### ISSUE TITLE
No "Ask to unmute button" in breakout room

### ISSUE THREAD

**Issue by klebanj** [jitsi/jitsi-meet#13172]
### Description:

In breakout rooms there is no option to ask participant to unmute. This feature is available in main room only.

### Steps to reproduce:

1. User 1 creates conference A 
2. User 2 joins the conference A
3. User 1 creates breakout room B
4. User 1 sends User 2 to the breakout room B
5. User 1 joins breakout room B
6. User 1 opens "Particpants panel" and mutes User B  

### Expected behavior:

User 1 should see "Ask to unmute" button when the cursor is on User 2.
 
### Actual behavior:

There is no button "Ask to unmute". This button is visible in main room only but not in breakout rooms.

![bug1](https://user-images.githubusercontent.com/129974413/230130707-0e8b488e-045c-4911-9927-eac81642289b.png)

### Server information:

https://meet.jit.si/room1291
Bug reproducted 05.04.2023.

### Client information:

- Browser / app version: Google Chrome 111.0.5563.110
- Operating System: Ubuntu 22.04.02 LTS

### Additional information:
Nothing

**Comment by damencho** [comment]
This is known, audio/video moderation has never been tested with breakout rooms.

**Comment by saghul** [comment]
IIRC we just disable it there.

**Comment by saghul** [comment]
No, it was disabled because it doesn't work inside a BR.
