### ISSUE TITLE
JitsiMeetActivity::OnDestory() is called but the conference continues to run 

### ISSUE THREAD

**Issue by softavail** [jitsi/jitsi-meet#13175]
### Description:

`JitsiMeetActivity::OnDestory()` is called but the conference continues to run 

### Prerequisites
For displaying meetings My application uses JitsiMeetActivity as a second Activity, while there is another "main" Activity with other content.

### Steps to reproduce:

 - Join a meeting via `JitsiMeetActivity.launch` method
 - Enter PIP
 - Close PIP ( by clicking 'x' in top right corner )
   - This causes `JitsiMeetActivity::onStop()` 
 - 'Swipe' up the main activity 
 - Start launching other applications to try to load the system and monitor when `JitsiMeetActivity::OnDestory()` will be called
 - Once this has been called, note that the meeting is still alive ( other parties in the meting can hear you )

### Expected behavior:

When the `JitsiMeetActivity::OnDestroy()` is being called, meeting to stop on the android device

### Actual behavior:

When the `JitsiMeetActivity::OnDestroy()` is called, meeting continues without any visual indication of that. Meeting stops at some later point ( depends on when the OS will be loaded enough )

### Client information:

- SDK version: JitsiMeetSDK 7.0.1
- Operating System: Android 10/11/12

### Additional information:

The code written in the JitsiMeetActivity::onDestory() looks like tries to end the meeting but in fact it doesn't.

**Comment by tmoldovan8x8** [comment]
Actually this is a bug in jitsi-meet app, as well, thanks for pointing this to us. We're working on the fix.

**Comment by harshpatel63** [comment]
Hi @saghul 

The issue still persist. You can recreate with the same steps mentioned by @softavail.

**Comment by saghul** [comment]
On which SDK version?

**Comment by harshpatel63** [comment]
I figured out, it was my mistake. I was initializing two views. This was the reason for the conference still running. 


By the way, it shouldn't call the onDestroy() by just pressing the home button.

Any idea, we can fix it?

**Comment by saghul** [comment]
The home button should put the meeting in PiP mode, we don't destroy it.

**Comment by harshpatel63** [comment]
**Steps to reproduce:**

1. Join a meeting via JitsiMeetActivity.launch method
2. Enter PIP by pressing Home button.
3. Close PIP ( by clicking 'x' in top right corner )
4. This causes JitsiMeetActivity::onStop()
5. Open the app from the app drawer. In my case my app's launcher activity is recreated.
6. Press Home button again
7. JitsiMeetActivity::OnDestory() will be called.

**Comment by saghul** [comment]
On step 5 jutsimeetactivity should still be around, it's just in the background.

**Comment by harshpatel63** [comment]
The onDestroy for JitsiMeetActivity.java has a comment mentioning an edge case. I am encountering the same case I believe.

**Comment by saghul** [comment]
That only applies if your main app's activity is swipped out. Then all the activities of your app will be destroyed. I don't think that's the same case.
