### ISSUE TITLE
Jitsi getting slow when more than 5 people connect in the same room.

### ISSUE THREAD

**Issue by SalomeDrevet** [jitsi/jitsi-meet#13183]
### Description: 
I am from Talkspirit, a french company, and we currently using your solution. Sometimes, when there a more than 5 people in the same room, Jitsi is getting very slow. But sometimes it works. For information, we already checked our connexion, our proxy, vpn and other security tools, nothing's blocking our use of Jitsi.

### Steps to reproduce:

1. Unfortunately, I don't know how to reproduce ... It just happen...

### Expected behavior:
Jitsi shouldn't get slow.

### Server information:

- Jitsi Meet version: 2.0.7830-1
- Operating System: Debian 11.6

### Client information:

- Browser / app version: Firefox, Chrome
- Operating System: Mac OS; Windows 10, 11

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Have you tried meet.jit.si? Do you experience the same there?

Have you tried updating to latest, do you reproduce the same with latest?

**Comment by damencho** [comment]
Are all participants in the meeting experiencing this slowness? What browser and version do the participants use - those that  experience it?
