### ISSUE TITLE
Safari: Failure to share screen in an embedded Jitsi

### ISSUE THREAD

**Issue by lpatmo** [jitsi/jitsi-meet#1318]
I'm using beta.meet.jit.si, and have it embedded on a page. I am noticing that when I try to share my screen, I get an automatic "failed to share screen" message. And downloading the Temasys plugin did not help solve my screensharing issues.

![screen shot 2017-02-14 at 12 01 36 am](https://cloud.githubusercontent.com/assets/4512699/22920475/1029bc44-f24a-11e6-8049-269cf434d00f.jpg)

Is screensharing simply not supported in embedded Jitsi instances in Safari yet? I found this thread from October (http://lists.jitsi.org/pipermail/users/2016-October/011873.html), which indicates that there were still some problems being worked on as of October 2016.

**Comment by saghul** [comment]
I can confirm the issue. It's also present in the current production environment (meet.jit.si), even when not using the iframe API.
