### ISSUE TITLE
Adding Jitsi pod crashes app

### ISSUE THREAD

**Issue by diegolmello** [jitsi/jitsi-meet#13194]
### Description:

I'm trying to add Jitsi to an app, but adding the pod makes it crash.

### Steps to reproduce:

Checkout and run this sample: https://github.com/diegolmello/glowing-octo-palm-tree

### Expected behavior:

App runs without a crash

### Actual behavior:

App crashes on runtime with the following error

[log.txt](https://github.com/jitsi/jitsi-meet/files/11193591/log.txt)

### Server information:

- Jitsi Meet version: not related
- Operating System: not related

### Client information:

- Browser / app version: 'JitsiMeetSDK', '7.0.1'
- Operating System: macOS 13.0.1

### Additional information:

It works on React Native 0.70.7, but it fails on React Native 0.71.5

**Comment by diegolmello** [comment]
@saghul Can you help please?

**Comment by saghul** [comment]
Our native SDK also uses RN internally so using RN within RN will not work properly.

You can try downgrading to the same version we use, but that will be a band-aid.

We are working on a RN SDK which would avoid having the RN-in-RN scenario. No ETA yet, but check the open PRs in this repo for it.
