### ISSUE TITLE
Feature request : Join meetings with virtual backgrounds

### ISSUE THREAD

**Issue by Razor1700** [jitsi/jitsi-meet#13199]
Hello,
I have a project where I use Jitsi to handle video call and before joining the meeting, I want to show a component where users can select input/output devices and apply background effect to video track. I can easily send all data except background effect to the jitsi api. Is there a way to do it currently ?

To join the meeting, I use JitsiMeetExternalAPI with configOverwrite and interfaceConfigOverwrite.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This is already available, we call it prejoin screen. You can test it on meet.jit.si.
