### ISSUE TITLE
iOS: Class implemented in both App and JitsiMeetSDK

### ISSUE THREAD

**Issue by a-voronov** [jitsi/jitsi-meet#13201]
### Description:

When I'm importing JitsiMeetSDK as a dependency to another ReactNative-based iOS project, I'm getting: 
`Class X is implemented in both .../TestApp.app/TestApp and .../Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK. One of the two will be used. Which one is undefined.`

### Steps to reproduce:

1. Create template ReactNative project
2. Include JitsiMeetSDK as an iOS project pod dependency
3. Run iOS project

### Expected behavior:

Not having conflicting symbols

### Actual behavior:

Getting many warnings in logs during runtime, which can potentially lead to a crash or undefined behavior if RN versions are different.

### Client information:

- Browser / app version: JitsiMeetSDK 7.0.1
- Operating System: macOS 13.3, Xcode 14.3

### Additional information:

I'm trying to understand how this issue should be addressed as it seems like it should be a common thing for RN-based applications. Yet it seems like there's no clear answer on how to cope with it, after spending several days on it.

Attaching part of Xcode log with described above warnings: [warnings.txt](https://github.com/jitsi/jitsi-meet/files/11212598/warnings.txt).

**Comment by saghul** [comment]
Pretty much the same answer as here: https://github.com/jitsi/jitsi-meet/issues/13194#issuecomment-1506547835

We use RN for the SDK and running 2 versions will cause trouble.

**Comment by a-voronov** [comment]
@saghul do you think there could be a way to solve it by somehow hiding RN symbols and changing the way Jitsi meet SDK is being built? I mean if I can just build it myself, let's say from a fork, so it doesn't affect original repo.

**Comment by saghul** [comment]
Probably yes. Not sure how you'd go about doing that though. Do you have any ideas?

**Comment by a-voronov** [comment]
yeah, so far the most feasible option I could find, would be to mangle external defined symbols of dependencies by adding a prefix inside of `GCC_PREPROCESSOR_DEFINITIONS`.

there seems to be even a cocoapods plugin https://github.com/intercom/cocoapods-mangle, however right now it combines all the symbols from all the frameworks together, and there're too many of them to pass to a cli, so there's an error `unable to spawn process '/bin/sh' (Argument list too long)`.

I'll try to separate symbols per each dependency and just hope that this way none of them will exceed the limit

**Comment by saghul** [comment]
Sounds good, let me know how it goes!

**Comment by lucacomanduccirmg** [comment]
> yeah, so far the most feasible option I could find, would be to mangle external defined symbols of dependencies by adding a prefix inside of `GCC_PREPROCESSOR_DEFINITIONS`.
> 
> there seems to be even a cocoapods plugin https://github.com/intercom/cocoapods-mangle, however right now it combines all the symbols from all the frameworks together, and there're too many of them to pass to a cli, so there's an error `unable to spawn process '/bin/sh' (Argument list too long)`.
> 
> I'll try to separate symbols per each dependency and just hope that this way none of them will exceed the limit

Hi, I am stuck on the same problem, any news about it?

**Comment by saghul** [comment]
If you are using RN then you can use our RN SDK now: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-react-native-sdk

**Comment by lucacomanduccirmg** [comment]
I'm not using RN

**Comment by saghul** [comment]
Then please open a new issue and provide as many details as possible.

**Comment by a-voronov** [comment]
@saghul thanks for the update! is it something that we can use in native iOS/Android apps (i.e. if I have native codebase which is using Jitsi's RN functionality)?

or it's intended to be used only with another RN code?

I'm trying to figure out if it helps the issue described above, maybe you could suggest something that I can't properly see here?

**Comment by saghul** [comment]
Then you need to use the native SDKs: https://jitsi.github.io/handbook/docs/category/sdks
