### ISSUE TITLE
"Enable lobby" does not save for meeting room, allowing people to join as soon as the moderator joins

### ISSUE THREAD

**Issue by tomuta** [jitsi/jitsi-meet#13213]
### Description:

Because the "Enable lobby" checkbox does not appear to save to the meeting room, the next time the moderator starts a meeting and numerous people are already waiting, as soon as the moderator joins, all people are let in. The "Enable lobby" checkbox reverted back to being unchecked.

This wouldn't be a problem if there was a way for the moderator to set the "Enable lobby" checkbox before starting the meeting. But at least the web interface does not appear to provide such an option.

### Steps to reproduce:

1. Moderator creates a meeting
2. Moderator goes to Security settings, check the "Enable lobby" checkbox
3. Moderator send a meeting link to people
4. Moderator leaves the meeting
5. People other than the moderator connect to the meeting, they will be waiting until the moderator joins
6. Moderator joins

### Expected behavior:

The "Enable lobby" setting should stick, or the moderator needs to be able to enable the lobby before starting the meeting. When the moderator joins, no other person should be in the meeting and the moderator should have to accept each participant.

### Actual behavior:

As soon as the moderator joins, all people that were waiting get admitted. Now the moderator has to enable the "Enable lobby" feature again and kick all unwanted participants out.

### Server information:

- Jitsi Meet version: stable-8319
- Operating System: Debian 11 (docker)

### Client information:

- Browser / app version: Firefox 112.0.1
- Operating System: Ubuntu 22.04

**Comment by saghul** [comment]
This is currently a limitation we have, right @damencho ?

**Comment by damencho** [comment]
The moment the moderator leaves, the meeting is destroyed and so its state, this is by design.

To enable this you need some custom modules and work on the backend. It can be achieved with this module https://github.com/jitsi-contrib/prosody-plugins/tree/main/lobby_autostart
Make sure you check the warning in the beginning.

**Comment by EoinStronge** [comment]
> The moment the moderator leaves, the meeting is destroyed and so its state, this is by design.
> 
> To enable this you need some custom modules and work on the backend. It can be achieved with this module https://github.com/jitsi-contrib/prosody-plugins/tree/main/lobby_autostart Make sure you check the warning in the beginning.

The documentation for these prosody-plugins don't cover the docker version of Jitsi. I can make a pretty good guess at it for:
* https://github.com/shawnchin/prosody-plugins/tree/main/lobby_autostart, and
  (although I can't find a Component "conference.meet.mydomain.com" "muc" section)
* https://github.com/shawnchin/prosody-plugins/tree/main/token_lobby_bypass
  (same Component "conference.meet.mydomain.com" "muc" missing)

But the 2nd one has a prerequisite requirement:
* https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

And that documentation is much harder to understand in the context of the docker version. Would be very useful to have some clear documentation for Docker here. 

Thanks
