### ISSUE TITLE
[Android SDK] Screen sharing not working for Android 10, 11, 12 [Edit]

### ISSUE THREAD

**Issue by KacperL98** [jitsi/jitsi-meet#13210]
### Description:

for devices above Android 9, screen sharing does not work.

### Steps to reproduce:

1. Set the toolbox.enabled flag to true
2. Click on the three dots and choose screen sharing
3. There is a black screen on the screen sharing

or

1. according to the documentation use TOGGLE_SCREEN_SHARE
2. Click the button of your choice and share the screen
3. There is a black screen on the screen sharing

### Expected behavior:
Screen sharing works on any version of Android. Screen Sharing only works with Api 28 and lower versions.

### Actual behavior:

Screen sharing doesn't work above Android 9.

### Server information:

- Jitsi Meet version:
- I checked a few versions (6.2.2, 7.0.0, 7.0.1)

### Client information:

- Browser / app version: latest mobile app
- Operating System: Android 10, 11, 12

### Additional information:

Has there been anything changed for Screen sharing? I think it might be something with MediaProjection.

**Comment by saghul** [comment]
What error do you get? (please check with adb logcat)

**Comment by KacperL98** [comment]
I checked, but there is no specific information. I found similar problems, however they are not solved:

- https://community.jitsi.org/t/jitsi-android-sdk-screen-sharing-issue/110235
- https://github.com/jitsi/jitsi-meet/issues/11367

Now, I tested in Android 12 for Samsung A51

It looks as if in the flag does not work something properly  toolbox.enabled  or TOGGLE_SCREEN_SHARE

I also found repository, where is working fine for version 2.11.0 (2020-11-17)

Could you check if something has changed for Screen sharing in the latest versions?

**Comment by saghul** [comment]
I don't recall anything changing. I also cannot reproduce the problem on the Jitsi Meet app. At any rate, we are planning to release SDK 8 soon, which is built to target more modern Android versions, that might have something to do with it.

**Comment by KacperL98** [comment]
In the Jitsi meet app it works. A lot of examples on Android use older versions of Jitsi. After adding the latest version 7.0.1 in the app, it only works for me up to API 28 (Android 9).
