### ISSUE TITLE
Screensharing and saving bandwidth

### ISSUE THREAD

**Issue by ibrahimBeladi** [jitsi/jitsi-meet#13212]
### Steps to reproduce:

1. Join a meeting
2. Someone share their screen
3. Wait and see

### Expected behavior:

See the screensharing most of the time, even if it is stuttering. So that, I don't miss out most of the video/presentation,

### Actual behavior:

I don't get to see the screen sharing most of the time, I get "Video for X's screen has been turned off to save bandwidth"

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: meet.jit.si

### Client information:

- Browser / app version: Latest firefox, latest chrome, latest mobile app
- Operating System: Linux (firefox, chrome), Android 9

### Additional information:

I tried toggling between the 4 modes of performance/quality, but it does not get any better

**Comment by damencho** [comment]
How many participants were in the call two or more?

**Comment by ibrahimBeladi** [comment]
5 people, including myself

**Comment by ibrahimBeladi** [comment]
un-stale

**Comment by saghul** [comment]
We have received reports of bad bandwidth estimation with Firefox in the last release. Also not receiving these reports in general and anecdotally I haven't seen this myself. Does your connection have packet loss?

**Comment by azzid** [comment]
I recently installed images version 8960 and tried using them with firefox 102.15.0esr - screensharing refuse to load due to percieved missing bandwidth. Switched to chrome and the screen sharing works fine.

Is there any data I can provide to facilitate troubleshooting this further?

**Comment by saghul** [comment]
Ping @jallamsetty1 :arrow_up:

**Comment by numeropi** [comment]
I'm having the same issue in Firefox 119 64bits...

![imagen](https://github.com/jitsi/jitsi-meet/assets/56868560/7329235f-e8b7-4cff-b618-5b665f509b6d)

after few seconds seeing the screen shared by another user, jitsi removes the sharing for me with the message:

"Video has been turned off to save bandwidth"

my connection works fine...

**Comment by jallamsetty1** [comment]
This issue should be fixed in the latest stable.
