### ISSUE TITLE
Multistreaming on multiple platforms and destination like Twitch, Facebook, YouTube, Telegram, etc.

### ISSUE THREAD

**Issue by sirinath** [jitsi/jitsi-meet#13218]
**Is your feature request related to a problem you are facing?**
Yes

**Describe the solution you'd like**
Want to stream on multiple platforms.

**Describe alternatives you've considered**
Screen capture and stream with OBS Studio

**Comment by saghul** [comment]
This is already possible if you use a full RTMP URL in the live streaming dialog.

**Comment by sirinath** [comment]
Can you give a pointer to the documentation or tutorial please.

This is to live stream to FB, YT, Twitch, Telegram simultaneously.

**Comment by saghul** [comment]
All of those services will give you an RTMP URL that begins with `rtmp://` you can use that, similarly to OBS.

**Comment by sirinath** [comment]
The functionality to streaming to multiple platforms simultaneously is still not added. Can this be reponed?

**Comment by saghul** [comment]
We have no plans to enable that functionality, sorry.
