### ISSUE TITLE
Bug in shouldComponentUpdate method of base/media/components/web/AudioTrack.tsx 

### ISSUE THREAD

**Issue by arunnadesh** [jitsi/jitsi-meet#13231]
### Description:
In shouldComponentUpdate method of base/media/components/web/AudioTrack.tsx, currentMuted is checked against nextVolume instead of nextMuted which is wrong.

```
            if (typeof nextMuted === 'boolean' && currentMuted !== nextVolume) {
                this._ref.muted = nextMuted;
            }
```
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/media/components/web/AudioTrack.tsx#L155

### Steps to reproduce:

Found through code review 

### Expected behavior:

```
            if (typeof nextMuted === 'boolean' && currentMuted !== nextMuted) {
                this._ref.muted = nextMuted;
            }
```

### Server information:

- Jitsi Meet version: 2.0.8319 Latest
- Operating System: All

### Client information:

- Browser / app version: Chrome
- Operating System: All

\

**Comment by saghul** [comment]
Sounds good! Care to send a PR?

**Comment by arunnadesh** [comment]
> Sounds good! Care to send a PR?

Sure. Will do

**Comment by arunnadesh** [comment]
> > Sounds good! Care to send a PR?
> 
> Sure. Will do

PR raised.. FYI..
https://github.com/jitsi/jitsi-meet/pull/13234

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/13234
