### ISSUE TITLE
How to prevent every participant becoming a moderator?

### ISSUE THREAD

**Issue by arladmin** [jitsi/jitsi-meet#13245]
### Description:

Currently, in my self-hosted instance, every participant who joins automatically becomes a moderator.
This is a bug, right? 
Because i didn't find any config parameter to disable this behaviour.

### Server information:

- Jitsi Meet version: Jitsi 2.0.7882
- Operating System: Ubuntu

### Client information:

- Browser / app version: Chrome 112.0.5615.86
- Operating System: Win 11

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Are you running with default install and no modifications of it? What is your prosody config?

**Comment by arladmin** [comment]
@damencho 
Yes, default install on Cloudron.

config.js overrides:
```
{
    enableNoAudioDetection: true,
    enableNoisyMicDetection: true,
    enableWelcomePage: false,
    startWithAudioMuted: true,
    startWithVideoMuted: true,
    requireDisplayName: true,
    
    p2p: {
        enabled: true
    }
}
```

What's/where's the Prosody config?

**Comment by saghul** [comment]
Do you have the allowners Prosody plugin enabled? Check your Prosody config.

**Comment by arladmin** [comment]
This a Cloudron default installation.

I can't find any Prosody config or any plugin config for that matter.

**Comment by saghul** [comment]
Sorry, I'm not familiar with that setup. Don't they let you edit the Prosody config?

**Comment by arladmin** [comment]
@saghul The only thing we can edit is the `config.js`

**Comment by saghul** [comment]
Then I'm afraid you're out of luck. I'd raise a support ticket with them if I were you.

**Comment by arladmin** [comment]
@saghul Could you tell me what actually needs to be done to achieve a resolution to my issue?

**Comment by surpriselearning** [comment]
I have same issue with android sdk
