### ISSUE TITLE
Lib Folder and its lib-jitsi-meet.min.js file missen

### ISSUE THREAD

**Issue by bamms** [jitsi/jitsi-meet#1324]
The folder and file as required by the index file are missen and fresh installation will show error page. Please add missen files to the compilation because of new developers.

Quick question, will previous folder and file of older versions work well with new new compilation?

**Comment by saghul** [comment]
Did you rebuild the site using the supplied Makefile or webpack directly?

**Comment by bamms** [comment]
Use the git clone url from here

https://github.com/jitsi/jitsi-meet

**Comment by saghul** [comment]
Well, that's not nearly enough. You need to install the dependencies with npm and then bundle everything, see https://github.com/jitsi/jitsi-meet#building-the-sources

**Comment by bamms** [comment]
Thanks

Then one more question, I had my jitsi running excellently. Then I decided to upgrade just jitsi-meet, but when i finished, I can only see a pure blank screen. What else do I need to do? **Must** I upgrade prosody, Jicofo, Videobridge to have it all running well?

Whats the minimum I have to upgrade to have newest features

Thanks @saghul

**Comment by saghul** [comment]
You should update all components to matching tag names. The easiest is to use the packages we provide for Debian-like distros, since that's all taken care of.

**Comment by bamms** [comment]
Ok thanks

**Comment by bamms** [comment]
Just to confirm, the guide below is still valid and not outdated right:

https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

Used it for first installation

**Comment by saghul** [comment]
Yes, that should still work.  If you want to save yourself some trouble though, I suggest you use the provided packages.

**Comment by bamms** [comment]
Please confirm link to the stated provided packages just to be sure am in sync
Thanks alot

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 16, 2017 at 1:43 PM, Saúl Ibarra Corretgé<notifications@github.com> wrote:   
Yes, that should still work. If you want to save yourself some trouble though, I suggest you use the provided packages.

**Comment by saghul** [comment]
https://jitsi.org/Main/InstallJitsiMeetDebianStableRepository

Please read the README next time ;-)

**Comment by bamms** [comment]
Thank you

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 16, 2017 at 2:09 PM, Saúl Ibarra Corretgé<notifications@github.com> wrote:   
https://jitsi.org/Main/InstallJitsiMeetDebianStableRepository

Please read the README next time ;-)
