### ISSUE TITLE
sigill / sigsegv on chromium and Firefox

### ISSUE THREAD

**Issue by jmozd** [jitsi/jitsi-meet#13250]
### Description:

We're running a fresh install of Jitsi (Docker container, latest stable-8319). Generally, everything seemed to work out fine.

With our first longer session (> 30 min), we started to experience failing browser-based clients (Chromium & Firefox, always Linux-based), where the browser tab suddenly displayed  SIGILL or SIGSEGV messages.

Running the sessions in Jitsi-Meet/Android does not show these issues, and using old browser versions (i.e. Chromium < 100) seems to work stable, too. The latest version of Chromium showing this bug is "Version 112.0.5615.121 (openSUSE Build) stable (64-Bit)", where it is alway a SEGV. The issue seems related to "changes" in the Jitsi session - the more people come and go, the more likely the error is to happen. It may take as long as 30 minutes to happen for an individual user, but we've seen this after already a few minutes, too.

This Jitsi installation is replacing a much older version of Jitsi - we've not seen that happen even once with that version, but I just mentioning this here for completeness sake.

When just testcasing a Jitsi meeting with three participants (no more join/leave of participants, no change of the participant currently active), the browser will not show problems.

### Steps to reproduce:

1. Participate in in a Jitsi meeting with at least audio activated, unsing Chromium 112.0.5615.121 openSUSE 64bit
2. Cause actions in the meeting (leave/join, different participants talking)

### Expected behavior:

The browser tab should continue to show the Jitsi Meet session content.

### Actual behavior:

After a few minutes, the browser tab will fail and show a SIGSEGV

- Jitsi Meet version: 2.0.8319
- Operating System: client: openSUSE Leap 15.4, Jitsi Meet: image jitsi/web:stable-8319 running on K3s/containerd 

### Client information:

- Browser / app version: Chromium 112.0.5615.121 openSUSE 64bit
- Operating System: Linux openSUSE Leap 15.4

### Additional information:
Before the update to the latest Chromium, the error message displayed by the browser tab was SIGILL instead of SIGSEV.

**Comment by damencho** [comment]
You reproduce this only with Chromium 112 under openSUSE? You don't experience it on other OS?

**Comment by jmozd** [comment]
I also experienced this with Chromium 111, Firefox 102.9 and 102.10 (all on openSUSE Leap 15.4), which is all we use on desktops in our team. An old test system with Chromium 98.x (on openSUSE Leap) does work. Browser on Android wasn't tested yet, Jitsi Meet app on Android does work.

**Comment by damencho** [comment]
Crashes like that are problems with the browser most of the time. But the fact you see it with Chromium and Firefox means it is most probably something on OS level.

**Comment by damencho** [comment]
There is nothing we can do. And I haven't seen reports like that, sorry.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by jmozd** [comment]
ok, will do. closing this for now.
