### ISSUE TITLE
Cann't run [ npm install ] successfully. [master branch]

### ISSUE THREAD

**Issue by kevin-wang-online** [jitsi/jitsi-meet#13252]
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://github.com/jitsi/strophejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a failed, reason: connect ETIMEDOUT 198.51.44.8:443

The resrouce is 404
https://github.com/jitsi/strophejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a

**Comment by saghul** [comment]
The timeout looks like a network problem on your end, the CI is currently green.

**Comment by woaini521** [comment]
> npm 错误！代码 ETIMEDOUT npm 错误！系统调用连接 npm 错误！errno ETIMEDOUT npm 错误！[到https://github.com/jitsi/stropejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a](https://github.com/jitsi/strophejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a)的网络请求失败，原因：连接 ETIMEDOUT 198.51.44.8:443
> 
> 资源是404 [https://github.com/jitsi/stropejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a](https://github.com/jitsi/strophejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a)
问下解决了吗？我也卡到这里了

**Comment by woaini521** [comment]
> npm 错误！代码 ETIMEDOUT npm 错误！系统调用连接 npm 错误！errno ETIMEDOUT npm 错误！[到https://github.com/jitsi/stropejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a](https://github.com/jitsi/strophejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a)的网络请求失败，原因：连接 ETIMEDOUT 198.51.44.8:443
> 
> 资源是404 [https://github.com/jitsi/stropejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a](https://github.com/jitsi/strophejs-plugin-stream-management/tar.gz/001cf02bef2357234e1ac5d163611b4d60bf2b6a)

问下你的项目可以正常运行了吗？
