### ISSUE TITLE
 The android app clicks the button to join the meeting and reports an exception

### ISSUE THREAD

**Issue by MrLizhiguang** [jitsi/jitsi-meet#13268]
[features/base/app] Error(TypeError){"message":"b is not a function. (In 'b()', 'b' is false)","stack":"s@index.android.bundle:1694:782\nyr@index.android.bundle:67:42052\nql@index.android.bundle:67:90906\nFa@index.android.bundle:67:81678\nUa@index.android.bundle:67:81580\nLa@index.android.bundle:67:81345\nEa@index.android.bundle:67:78308\nEa@[native code]\nft@index.android.bundle:67:26100\nTe@index.android.bundle:67:94258\nPe@index.android.bundle:67:12967\nNe@index.android.bundle:67:13344\nreceiveTouches@index.android.bundle:67:14143\nvalue@index.android.bundle:47:3557\nindex.android.bundle:47:674\nvalue@index.android.bundle:47:2504\nvalue@index.android.bundle:47:646\nvalue@[native code]"} { componentStack: '\n    in s\n    in S\n    in Unknown\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in A\n    in Unknown\n    in PanGestureHandler\n    in Unknown\n    in RCTView\n    in Unknown\n    in A\n    in Unknown\n    in RCTView\n    in Unknown\n    in G\n    in Unknown\n    in RNSScreen\n    in A\n    in Unknown\n    in U\n    in k\n    in Unknown\n    in RNSScreenContainer\n    in ScreenContainer\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in w\n    in RCTView\n    in Unknown\n    in y\n    in RNGestureHandlerRootView\n    in Unknown\n    in w\n    in Unknown\n    in u\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in C\n    in Unknown\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in RCTView\n    in Unknown\n    in A\n    in Unknown\n    in PanGestureHandler\n    in Unknown\n    in RCTView\n    in Unknown\n    in A\n    in Unknown\n    in RCTView\n    in Unknown\n    in G\n    in Unknown\n    in RNSScreen\n    in A\n    in Unknown\n    in U\n    in k\n    in Unknown\n    in RNSScreenContainer\n    in ScreenContainer\n    in Unknown\n    in RCTView\n    in Unknown\n    in Unknown\n    in w\n    in RCTView\n    in Unknown\n    in y\n    in RNGestureHandlerRootView\n    in Unknown\n    in w\n    in Unknown\n    in u\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in T\n    in RCTView\n    in Unknown\n    in Unknown\n    in RNCSafeAreaProvider\n    in Unknown\n    in c\n    in Unknown\n    in k\n    in c\n    in RCTView\n    in Unknown\n    in Portal.Host\n    in RNCSafeAreaProvider\n    in Unknown\n    in y\n    in v\n    in Unknown\n    in h\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in b' }

**Comment by MrLizhiguang** [comment]
[modules/statistics/AudioOutputProblemDetector.js] A potential problem is detected with the audio output for participant 74f8680a, local audio levels: [null,null], remote audio levels: undefined

**Comment by saghul** [comment]
What SDK version are you using? If it's the app, same question.
