### ISSUE TITLE
Better display name configuration (hideDisplayName broken?)

### ISSUE THREAD

**Issue by fritzgithub** [jitsi/jitsi-meet#13262]
**Is your feature request related to a problem you are facing?**
The display names are always shown, written on top of the bottom part of default view, tile view and thumbnails.
The following setting:
`  // Hides the display name from the participant thumbnail `
`   hideDisplayName: true`
does not work as expected, because it removes all names everywhere. Unlike defined in  #10502 (Set Display Name Visibility as a Configurable Option)

**Describe the solution you'd like**
I would appreciate a better configurability, e.g.
- general option(s)
  - always show 
  - never show
  - display only on hover/touch for some seconds
- specific settings 
  - don't show on thumbnails
  - don't show my own name

**Comment by fritzgithub** [comment]
Any news?

**Comment by fritzgithub** [comment]
Dear Bot, 
I would rather let the jitsi team close this as done or rejected.
If you (the great people working on jitsi, btw. a big thank you!)  decide, that this is currently of too low priority, I fully understand.
Otherwise, it still would be nice to have this some day.
Kind regards

**Comment by saghul** [comment]
It's low priority, so a PR would be welcome indeed.

**Comment by fritzgithub** [comment]
Understood. Since we don't have resources for this in the near (and not so near) future ourselves, I'll close this.

**Comment by fritzgithub** [comment]
Ok, I obvioulsly cannot close this ticket ...

**Comment by fritzgithub** [comment]
or can I?
