### ISSUE TITLE
How to view 2 participants continuously. Like when there is 3 participants. Right now it will hide one view which is in large picture. Need to show fixed visible for 2 participants? .  

### ISSUE THREAD

**Issue by Mahesh160393** [jitsi/jitsi-meet#13271]
Hello @saghul . 

We are creating Android SDK from react native code. I'm trying to view 2 participants continuously in small view but when user click on small view. Large video is changing and small video view is showing alternate user name or video. 
![1](https://user-images.githubusercontent.com/24999844/234582840-638cda61-c167-4ef5-853f-9193bb124398.png)

![2](https://user-images.githubusercontent.com/24999844/234582865-b9338219-98f2-47b9-bddf-1413e28c65bd.png)

Attached 2 screenshot. Need same as 2nd screen shot after click also. Could you please tell me where should i change the flag or fix the flag so small view don't get collapsed .

**Comment by saghul** [comment]
Sorry, look like this fell through the cracks.

Do you want to always show the thumbnail for the remote participant? Even when shown in the large view?

**Comment by Mahesh160393** [comment]
Yes i want always show the thumbnail for the remote participant

**Comment by Mahesh160393** [comment]
Could you please tell me in which class i will find the click event for selfview?
