### ISSUE TITLE
ios sdk error on xcode 14.3

### ISSUE THREAD

**Issue by alirezarabiei7239** [jitsi/jitsi-meet#13274]
Hi ,
Im getting this error after update code to 14.3
the following build commands failed:
	SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\ Promises.swiftinterface Library/Developer/Xcode/DerivedData/jitsi-meet-gorwcpnzjlogvphecsfvunpkxocf/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/PromisesSwift.build/Objects-normal/arm64/Promises.swiftinterface (in target 'PromisesSwift' from project 'Pods')
	SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\ Promises.private.swiftinterface Library/Developer/Xcode/DerivedData/jitsi-meet-gorwcpnzjlogvphecsfvunpkxocf/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/PromisesSwift.build/Objects-normal/arm64/Promises.private.swiftinterface (in target 'PromisesSwift' from project 'Pods')

**Comment by alirezarabiei7239** [comment]
@saghul where can I find the version ?
i have downloaded from github 3 moth ago

**Comment by saghul** [comment]
You shouldn't just get a random checkout. The latest iOS SDK tag is ios-sdk-8.0.0 you can also check the release notes.

**Comment by alirezarabiei7239** [comment]
@saghul 
the version is 6.2.0 
I have downloaded full jitsii-meet-master and have changes in ui and js file the android build sdk is successful but ios cant archive 
thnaks for help

**Comment by saghul** [comment]
What error do you get with master?

**Comment by rcidt** [comment]
@saghul @alirezarabiei7239 I am seeing the same thing after upgrading to Xcode 14.3

**Comment by saghul** [comment]
We are not yet using Xcode 14.3 to build, there might be something that needs adjusting.

I'd downgrade for now.

**Comment by rcidt** [comment]
Will try that

**Comment by saghul** [comment]
14.2 is what we use to make production builds at the moment.

**Comment by alirezarabiei7239** [comment]
@saghul 
Hi,
 Xcode 14.3 is steel unsupported or no?

**Comment by saghul** [comment]
Still not officially supported.

**Comment by alirezarabiei7239** [comment]
@saghul 
Any update ?

**Comment by saghul** [comment]
Last I tested I got no errors. Do you?

**Comment by alirezarabiei7239** [comment]
I will check and say the result, thanks.

**Comment by Osein** [comment]
Hello @saghul i just started using jitsi in our project and i get same error in xcode 14.3. Building it with 14.2 is fine

**Comment by saghul** [comment]
What SDK are you using? Please share the build output.

**Comment by shooding** [comment]
Same issue here. Downgrade to XCode 14.2 works. You need to login Apple developer.
https://download.developer.apple.com/Developer_Tools/Xcode_14.2/Xcode_14.2.xip

**Comment by saghul** [comment]
What exact issue did you run into?

I tried to reproduce it but couldn't so I'm not sure what needs fixing.

**Comment by shooding** [comment]
To build iOS SDK, follow developer guide https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk
Using XCode 14.3
pod install you will have error:
`SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\ Promises.private.swiftinterface /Users/shooding/Library/Developer/Xcode/DerivedData/jitsi-meet-cwnafcnoqcznkodjpympwbxevnxn/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/Pods.build/Release-iphonesimulator/PromisesSwift.build/Objects-normal/arm64/Promises.private.swiftinterface (in target 'PromisesSwift' from project 'Pods')`

**Comment by saghul** [comment]
You mean you have an install error if the SDK was generated with 14.3?

**Comment by alirezarabiei7239** [comment]
> Last I tested I got no errors. Do you?

The error still exist for me

**Comment by alirezarabiei7239** [comment]
Hi everybody 
for anyone who has this issue 
I have solved this by adding= -no-verify-emitted-module-interface to Other Swift Flags to your Build Settings 
for each pod that mentioned in error
and then run success in Xcode 14.3.1

**Comment by saghul** [comment]
Oh, interesting!

Do you run into the problem when consuming the SDK which was compiled with 14.3 or when trying to build the SDK itself?

**Comment by alirezarabiei7239** [comment]
> Oh, interesting!
> 
> Do you run into the problem when consuming the SDK which was compiled with 14.3 or when trying to build the SDK itself?

Buildin sdk itself

**Comment by saghul** [comment]
That is what I tried and couldn't repro, so that's weird.

I'll try again.

**Comment by shooding** [comment]
Error when trying to build the iOS sdk itself

Saúl Ibarra Corretgé ***@***.***> 於 2023年8月29日 週二 01:07 寫道：

**Comment by ClassicalDude** [comment]
I modified the Podfile of release 8960 and added the following to the post_install section:

```
  # https://github.com/jitsi/jitsi-meet/issues/13274
  xcconfig_path = ""
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      new_xcconfig_path = config.base_configuration_reference.real_path
      if new_xcconfig_path != xcconfig_path
        xcconfig_path = config.base_configuration_reference.real_path
          
        # read from xcconfig to build_settings dictionary
        build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]
          
        # modify OTHER_SWIFT_FLAGS
        if build_settings['OTHER_SWIFT_FLAGS'] != nil
          puts "Updating #{target.name} #{config} OTHER_SWIFT_FLAGS"
          no_verify_flag = "-no-verify-emitted-module-interface "
          build_settings['OTHER_SWIFT_FLAGS'].gsub!(no_verify_flag, "")
          build_settings['OTHER_SWIFT_FLAGS'] = "#{no_verify_flag} #{build_settings['OTHER_SWIFT_FLAGS']}"

          # clear current file content
          File.open(xcconfig_path, "w") {|file| file.puts ""}

          # write build_settings dictionary to xcconfig
          build_settings.each do |key,value|
            File.open(xcconfig_path, "a") {|file| file.puts "#{key} = #{value}"}
          end
        end
      end
    end
  end
```

This code goes through every pod, and when the OTHER_SWIFT_FLAGS are not nil, it adds the "-no-verify-emitted-module-interface" flag. Running `pod install` with this Podfile yields successfully building the SDK from the scripts.

**Comment by saghul** [comment]
@ClassicalDude Thanks for sharing! Did you have to use that to build the SDK itself?

**Comment by ClassicalDude** [comment]
> @ClassicalDude Thanks for sharing! Did you have to use that to build the SDK itself?

Yes. You have to add that flag to the OTHER_SWIFT_FLAGS of 3 pods for the lite script to run, and to 4 of them for the regular script to run.

**Comment by saghul** [comment]
Thanks for confirming. I'll try to reproduce the problem.

**Comment by saghul** [comment]
I could reproduce the problem.

**Comment by saghul** [comment]
This seems like a simplified version that did the job: https://github.com/jitsi/jitsi-meet/pull/13858

**Comment by ClassicalDude** [comment]
> This seems like a simplified version that did the job: #13858

The existing flags were explicit, not `$(inherited)`. In my solution I wanted to make sure I copy all of the existing flags verbatim and add to them, rather than replace them altogether. After all, these pods have their own maintainers. But my knowledge of the subject is really not significant.

**Comment by saghul** [comment]
My understanding is that the `$(inherited)` would take care of the ones that trickle down. I didn't see any problems with this, so in general I'd rather go with a simpler solution if it works, and make it more complex if we need to :-)
