### ISSUE TITLE
Share system audio

### ISSUE THREAD

**Issue by saibotma** [jitsi/jitsi-meet#13280]
**Is your feature request related to a problem you are facing?**
No

**Describe the solution you'd like**
When sharing the screen it should be possible to also share the system audio.

**Describe alternatives you've considered**
Forwarding system audio to a virtual audio device. This only works on PC and not on mobile unfortunately and requires additional configuration.

**Comment by saghul** [comment]
What operating system are you using?

**Comment by saibotma** [comment]
I am using macOS, however my customers are also using Linux and Windows.

**Comment by saghul** [comment]
Sharing system audio is only supported by Chrome on Windows, when you choose the entire desktop.

We have no control over that UI or its behavior, alas.

**Comment by hamletmun** [comment]
I am using 2 workarounds on Linux
1. Link media player output to the browser input
2. Create a virtual microphone and link your headset/speaker monitor to it

See [Use PipeWire to link audio ports](https://gist.github.com/hamletmun/95acc8f280258c33b18f5c328e6bff75)
