### ISSUE TITLE
Add new disableCalendar config option

### ISSUE THREAD

**Issue by VernPace** [jitsi/jitsi-meet#13290]
We would like an option to disable the Calendar tab in the Settings dialog.

The new config option could be called **disableCalendar** and would be similar in behavior to config.disableProfile

**Comment by saghul** [comment]
Sure, a PR would be welcome.

**Comment by VernPace** [comment]
@shawnchin  The url parm will do for us. Thanks for the tip!  Unless anyone else is interested in the **disableCalendar** approach, I will close this out.
