### ISSUE TITLE
Speaker stats : order by speaking time

### ISSUE THREAD

**Issue by Dynnammo** [jitsi/jitsi-meet#13293]
**Is your feature request related to a problem you are facing?**
When organizing a meeting with multiple person, as a facilitator, I would like to know who are the main speaker at the current time. This need is currently  filled by the _Speaker time_ button available in the hamburger menu

However, if we are many, I have no way but to read each time in order who is speaking "too much".

**Describe the solution you'd like**
When opening the modal of speaker stats, it would be great to order the list of speakers on the time they spoke : one click order by decreasing order, two clicks by increasing order.

In the same movement, we could also think about ordering speakers by their name, but it's not direclty related to the current issue.

**Describe alternatives you've considered**
Do it manually without changing the UI of the modal Speaker stats

**Comment by damencho** [comment]
There is already option for ordering you can extend that. Any PRs are welcome.
https://github.com/jitsi/jitsi-meet/blob/d381ceb040fa02e24d8becba16045c781e5bcde3/config.js#L229
