### ISSUE TITLE
Youtube volume is very low in IOS & Android app 

### ISSUE THREAD

**Issue by gigabyteservice** [jitsi/jitsi-meet#13297]
When we play youtube videos on jitsi mobile then it has a lower volume as compared to youtube’s official app and this volume is noticeably low in IOS 16.1.1 any suggestion to resolve this issue,[ already shared the issue here](https://community.jitsi.org/t/youtube-volume-issue-is-very-low-in-ios-app/122393)

**Comment by saghul** [comment]
Hi there! I didn't notice a low volume in some quick testing, but the volume slider in the YouTube video is set to 50%. You can move it. Doe sit improve that way?

**Comment by MahmoudMamdoouh** [comment]
> Hi there! I didn't notice a low volume in some quick testing, but the volume slider in the YouTube video is set to 50%. You can move it. Doe sit improve that way?

No, it doesn't

**Comment by saghul** [comment]
What video did you use for the test?

**Comment by MahmoudMamdoouh** [comment]
Any  youtube video

**Comment by saghul** [comment]
Please write detailed steps to reproduce, since I couldn't last I tried.
