### ISSUE TITLE
(Settings) Notifications tab

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#13300]
### Description:

When the text is long, the selection boxes become misaligned, as well as the arrows and text.

<img width="685" alt="imagem" src="https://user-images.githubusercontent.com/32515675/235433634-5d8ce181-945d-46fe-82db-22fe4cd94767.png">

### Expected behavior:

<img width="687" alt="imagem2" src="https://user-images.githubusercontent.com/32515675/235434012-58caad8c-c78d-4843-ab68-34e91162a4f5.png">

### Server information:

meet.jit.si
alpha.jitsi.net

### Client information:

- Browser / app version: Chrome, Firefox, Safari
- Operating System: macOS

**Comment by saghul** [comment]
I think the current behavior is correct, or at least consistent. The checkbox is rendered in the center of the label. So if the first label is 2 lines the box will be a bit lower.

What's the expected behavior here @robertpin ?

**Comment by jluisfa** [comment]
It is vertically unaligned...
I put the image with zoom.

<img width="868" alt="imagem3" src="https://user-images.githubusercontent.com/32515675/235438706-b36ba25d-3243-4e82-8ccf-61f9161c76ed.png">

**Comment by saghul** [comment]
Ah, I see now, thanks!

**Comment by robertpin** [comment]
I'll have a look
