### ISSUE TITLE
Unfortunately something went wrong we're trying to fix this

### ISSUE THREAD

**Issue by MaralCh** [jitsi/jitsi-meet#1331]
Hello, I've just started using Jitsi-meet and trying to make some changes with it's design. It works fine when only I use, but when someone try to connect to the server on my localhost both got the error: "Unfortunately something went wrong we're trying to fix this". Maybe it seems simple question, but I want to know what causes this error and how to fix this?

**Comment by saghul** [comment]
Can you please check the console logs? (use a gist or a pastebin service and link them here). That should give us a good starting point. But first: does it run ok if you don't make any changes?

**Comment by designgurudotorg** [comment]
I think I'm having the same problem - ref https://github.com/jitsi/jitsi-meet/issues/1375 (the thread has a console log with a couple errors... hope that helps the bug hunt!)

**Comment by saghul** [comment]
There are a number of reasons why you might see that screen. Logs usually help pinpoint the issue. #1375 specifically seems to be related to no Jitsi Video Bridges being available. Maybe you can also check for that @MaralCh.

**Comment by kevincolten** [comment]
I've seen this problem twice now, but upgrading to the latest version seemed to have fixed it both times

`sudo apt-get update`
`sudo apt-get upgrade jitsi-meet`

**Comment by saghul** [comment]
I'm closing this since there is nothing actionable. Holler if you have logs so we can reopen!

**Comment by afcady** [comment]
I have the same problem.  The logs in `/var/log/prosody/prosody.err` did show what happened:

    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/fifty.childrenofmay.org.key': Check that the permissions allow Prosody to read this file. (for focus.fifty.childrenofmay.org)
    Dec 03 14:49:55 focus.fifty.childrenofmay.org:tls   error   Unable to initialize TLS: error loading private key (Permission denied)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/fifty.childrenofmay.org.key': Previous error (see logs), or other system error. (for focus.fifty.childrenofmay.org)
    Dec 03 14:49:55 focus.fifty.childrenofmay.org:tls   error   Unable to initialize TLS: error loading private key (system lib)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/fifty.childrenofmay.org.key': Previous error (see logs), or other system error. (for conference.fifty.childrenofmay.org)
    Dec 03 14:49:55 conference.fifty.childrenofmay.org:tls      error   Unable to initialize TLS: error loading private key (system lib)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/fifty.childrenofmay.org.key': Check that the permissions allow Prosody to read this file. (for conference.fifty.childrenofmay.org)
    Dec 03 14:49:55 conference.fifty.childrenofmay.org:tls      error   Unable to initialize TLS: error loading private key (Permission denied)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/fifty.childrenofmay.org.key': Previous error (see logs), or other system error. (for jitsi-videobridge.fifty.childrenofmay.org)
    Dec 03 14:49:55 jitsi-videobridge.fifty.childrenofmay.org:tls       error   Unable to initialize TLS: error loading private key (system lib)

    [etc.]


Somehow the certificates in `/var/lib/prosody/` got installed with ownership `root:root`.

This fixed the issue:

    sudo chown prosody:prosody -R /var/lib/prosody/
    sudo service prosody restart

This was a fresh install of jitsi-meet (1.0.2635-1).  I had never touched that directory.  So there must be a bug in the jitsi-meet certification install code.

Here is some more information about my system:

    ||/ Name               Version      Architecture Description
    +++-==================-============-============-=================================================
    ii  jitsi-meet         1.0.2635-1   all          WebRTC JavaScript video conferences
    ii  jitsi-meet-prosody 1.0.2441-1   all          Prosody configuration for Jitsi Meet
    ii  jitsi-videobridge  1011-1       amd64        WebRTC compatible Selective Forwarding Unit (SFU)
