### ISSUE TITLE
Knocking Invokes Chrome Notification

### ISSUE THREAD

**Issue by jsrobinson3** [jitsi/jitsi-meet#13318]
**Is your feature request related to a problem you are facing?**
We recently had an incident where a user was knocking but the moderator of the meeting was screensharing and did not see the knocking notification in the Jitsi window. It appears that there is a documented bug when a user changes their speaker source that other sounds within the conference do not go to their preferred source. see: https://github.com/jitsi/jitsi-meet/issues/12783. While I do think its a good idea to resolve this issue I was also thinking that a Chrome notification that someone is knocking would really improve the user experience as you may miss the knocking sound if you are engaged in conversation. 

**Describe the solution you'd like**
I believe invoking a Chrome notification that alerts moderators to a knocking person(s) with the option to let them in, would make the meeting experience better and increase user productivity. Even when a moderator hears a person knock (say they had to refresh or switch devices) they have to stop what they are doing, navigate back to the meeting and let the person in. If there was a quick pop-up with a button to let the user in then the moderator can quickly let them in without interrupting their presentation.

![image](https://user-images.githubusercontent.com/16910828/235903845-bc4a2c21-ea82-4ecd-bfcb-afcd6d195d05.png)

**Describe alternatives you've considered**
I am open to suggestions

**Comment by saghul** [comment]
I think this would need to use the web notifications API: https://developer.mozilla.org/en-US/docs/Web/API/Notification

Not sure that is something we'd like to do because we already have in-meeting notifications.

Fixing the audio cue output device should bring the user's attention to the meeting, and the knocking notifications won't vanish because they are sticky.
