### ISSUE TITLE
only store 'clean' URLs in recent conference list on start page

### ISSUE THREAD

**Issue by D1eter** [jitsi/jitsi-meet#13313]
### Description:

Filing an issue as requested in https://community.jitsi.org/t/intent-to-deprecate-and-remove-external-auth-mechanisms/115332/81

Conferences a user has attended are stored in the recent conferences list on the start page with the full URL including the JWT, rather than the "clean" URL without the '?JWT=...' part. If a user clicks on one of the recent conferences and the token in the URL has since expired, they are told already on the prejoin page that they are not allowed to join the call. In order to get anywhere they have to manually remove the token from the URL.

### Expected behavior:

Recent conference URLs are stored without the  '?JWT=...' part such that the link remains usable

### Actual behavior:

The '?jwt=...' part is not removed from the URL stored in the recent conferences list which causes the link to be unusable in case JWT has expired. Error message on prejoin screen:

![recent-conf-expired-JWT](https://user-images.githubusercontent.com/83979440/235731139-09267f9e-1f2a-46cd-85e2-434a1267d6e4.png)

### Server information:

- Jitsi Meet version: 2.0.8615-1
- Operating System: any

### Client information:

- Browser / app version: any
- Operating System: any

**Comment by apt-get-sahil** [comment]
Hi D1eter,

I noticed that you opened issue #13313 and I think I have a solution for it. However, before I start working on it and submitting a PR, I wanted to confirm that this issue is open for contributions and if it's okay for me to submit a PR.

Thank you for your time and consideration.

**Comment by saghul** [comment]
Yes, a PR would be welcome.

**Comment by D1eter** [comment]
Yes of course, you're welcome to submit a PR.

**Comment by apt-get-sahil** [comment]
Actually i was not able to recreate the problem you are suggesting i.e. "authentication failed" , it would be great if you can let me know how you encoutered that problem step by step , as i am trying to recreate the problem , it directly join the meeting without showing any such error.

**Comment by saghul** [comment]
You can test this using moderated.jitsi.net, it will use tokens but doesn't require extra setup.

**Comment by D1eter** [comment]
Tokens on moderated.jitsi.net do not expire, do they?

**Comment by D1eter** [comment]
Token I got on moderated.jitsi.net contains this payload, no expiry:

{
  "sub": "moderated",
  "aud": "jitsi",
  "iss": "jitsi",
  "context": {
    "group": "moderated"
  },
  "room": "09a427fc47bd9b015ef39da5fe640222da193404ddb1148b7bfc2fce3f3b89d4"
}
Meeting URL is saved with '?jwt=...' in recent-list though the page is custom and doesn't display the list.

I'm pretty sure we'll be fine when storing 'clean' meeting URL in recent-list.

**Comment by D1eter** [comment]
To see the problem on moderated.jitsi.net: start and stop moderated conference, get the meeting link including '?jwt=...' part and artificially make the token invalid by chopping a few letters from the end of the token. Paste modified link into browser address bar. Error message will show

**Comment by D1eter** [comment]
@apt-get-sahil I'm not sure what you mean. Do you have a working jitsi meeet setup and want to add token auth to it for testing?

**Comment by D1eter** [comment]
Problem still present in latest Version 2.0.8719 (2023-06-12). Maybe someone from the team can take a look? Fixing this would improve user experience quite a bit. I'm afraid I can't contribute much to fixing it myself but of course I can test and report results.

**Comment by saghul** [comment]
Sorry I'm afraid this is not high on the priority list.

**Comment by D1eter** [comment]
I have fixed this locally with a minimal change. I'm afraid a pull request is beyond my capabilities but here's the diff. Any chance this may be accepted?

```
diff --git a/react/features/recent-list/reducer.ts b/react/features/recent-list/reducer.ts
index c274d051c..c33ccbf90 100644
--- a/react/features/recent-list/reducer.ts
+++ b/react/features/recent-list/reducer.ts
@@ -82,7 +82,7 @@ function _deleteRecentListEntry(
  * @returns {Object}
  */
 function _storeCurrentConference(state: IRecentListState, { locationURL }: { locationURL: { href: string; }; }) {
-    const conference = locationURL.href;
+    const conference = getURLWithoutParamsNormalized( new URL(locationURL.href) );
 
     // If the current conference is already in the list, we remove it to re-add
     // it to the top.
```

**Comment by saghul** [comment]
I think that would be acceptable!

Sending a PR can be daunting, but if you follow the GitHub help you should be able to do it since you already did the harder at part: write the actual fix.
