### ISSUE TITLE
[Android Mobile] Newest version 8.1.2 status bar is always white

### ISSUE THREAD

**Issue by John7890M** [jitsi/jitsi-meet#13342]
After initializing video connection status bar is always white, I can't change color manually in the Android.
I checked that this situation is in the versions:

- 8.0.0
- 8.1.0
- 8.1.1
- 8.1.2

How can I change the color of the status bar?

**Comment by saghul** [comment]
We initialize it to be translucent, do you have any settings that would prevent that?

**Comment by saghul** [comment]
Actually, me made it hide again while in a meeting. I guess you only see it white when in reduced bandwidth mode?

**Comment by John7890M** [comment]
All the time I see a white status bar. Is there anything I can do to not hide the status bar during a meeting?

**Comment by John7890M** [comment]
> Actually, me made it hide again while in a meeting. I guess you only see it white when in reduced bandwidth mode?

I noticed that you use full screen and the screen goes into immersive mode, while in my application, I do not want to use it. 
I would like to have a visible top bar and status bar during the meeting.

**Comment by saghul** [comment]
That is not currently possible. We plan to leave the status bar visible instead of going full immersive mode, but haven't gotten around making the change yet.
