### ISSUE TITLE
Have you tried the cluster deployment

### ISSUE THREAD

**Issue by SlamDunkDcc** [jitsi/jitsi-meet#1335]
Did anyone give some advice?

**Comment by saghul** [comment]
Please, be more specific. What cluster deployment? Did you have any problem? If you are actually asking a question, please do so in our mailing list, the issue tracker is best suited for issues. Cheers.

**Comment by trda** [comment]
Is deploying jitsi-video-bridge more than one server possible?

Use case:
1 load balancer and 2 server.
2 users
they will see each other.

**Comment by damencho** [comment]
So currently you can easily add more than one JVB instances and jicofo will auto-discover them and will balance them.

If you want two jicofo and prosody instances, basically to balance between two deployments, you need to implement your balancer that way that if user1 and user2 want to enter the same room you need to make sure they land on the same deployment. This is easily achievable as most of the request the client is making has a parameter room= with the value of the room the users are joining.
This is how meet.jit.si is currently deployed and used.
If the two users for the same room go to different deployments they will be alone in the room and will not see each other, like they are in different rooms.

**Comment by roeycohen** [comment]
i think this can help:
https://github.com/jitsi/jicofo/blob/master/doc/load_balancing.md
