### ISSUE TITLE
Need help with getting data of me joining meetings.

### ISSUE THREAD

**Issue by bowenbest10** [jitsi/jitsi-meet#13353]
I was using this platform for drivers ed.  My drivers ed teacher died a couple hours after the last class before being able to send the data to the registry.  I really don’t want to take 30 hours again it would be great if there’s a chance I can get something that says I joined the meeting.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

If you are talking about meet.jit.si, there is nothing we can do as the system is anonymous and nothing is being stored after the meeting.
