### ISSUE TITLE
[IOS] cannot connect micro when in background mode

### ISSUE THREAD

**Issue by vantuan88291** [jitsi/jitsi-meet#13366]
When i join a room with more than 2 people, open micro and stream micro track to speak each other, and then hide the app and goto the background mode, still working. But when i goto other application like facebook or youtube, play a video and micro from jitsi was disconnect, just go to foreground mode again and then i can still keep talking again.
My concern is: How to keep talking with microphone when in background mode and play video or something like that, like google meet or zoom i can do that.
I guess need to implement IOS call keep feature to make its work, how can i do that? Thanks

**Comment by saghul** [comment]
Are you using the app or our SDK?

**Comment by vantuan88291** [comment]
i am implement jitsi-meet library to our react native app and its work very well without the background mode, i enabled audio background mode and voip in xcode before

**Comment by saghul** [comment]
Can you reproduce the issue with our oficial apps?

**Comment by vantuan88291** [comment]
Hi, i have just tested on your app on store, but seem like still working. The reason is your app is using callkeep on ios, that why still work. I will try to implement callkeep to my app

**Comment by vantuan88291** [comment]
i just wondering how to display this screen in your app?, which feature should i implement?
![2023-05-17 19 41 04](https://github.com/jitsi/jitsi-meet/assets/9206731/c3e4d7bf-665f-439c-919a-1858233d2017)

**Comment by vantuan88291** [comment]
i have resolve this issue by implement react native call keep feature, thanks
