### ISSUE TITLE
Jitsi master branch not functional on Android due "Invariant Violation" errors

### ISSUE THREAD

**Issue by pcvengros** [jitsi/jitsi-meet#13378]
### Description:

Current master branch is not functional on Android due TypeError and "Invariant Violation"

### Steps to reproduce:

1. git clone
2. npm install
3. start Android Studio 2022.2.1
4. open project directory "android"
5. build "Make project"
6. run Metro with "npx react-native start"
7. run App in Android studio in emulator

### Expected behavior:

Android studio will build app and run in emulator

### Actual behavior:
` WARN  'new NativeEventEmitter()' was called with a non-null argument without the required 'addListener' method.
 WARN  'new NativeEventEmitter()' was called with a non-null argument without the required 'removeListeners' method.

 INFO  2023-05-19T16:13:27.637Z [modules/browser/BrowserCapabilities.js] This appears to be react-native, ver: 0.69.10

 ERROR  TypeError: undefined is not an object (evaluating 'error.stack.split')

 LOG  Running "App" with {"initialProps":{"flags":{"pip.enabled":true,"call-integration.enabled":false,"server-url-change.enabled":true,"resolution":360,"welcomepage.enabled":true},"timestamp":1684512776946,"url":{"serverURL":"https://meet.jit.si","config":{}}},"rootTag":1}

 ERROR  Invariant Violation: "App" has not been registered. This can happen if:
 Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
 A module failed to load due to an error and 'AppRegistry.registerComponent' wasn't called.

 ERROR  Invariant Violation: "LogBox" has not been registered. This can happen if:
 Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
 A module failed to load due to an error and 'AppRegistry.registerComponent' wasn't called.
`
### Server information:

- Jitsi Meet version: master
- Operating System:

### Client information:

- Browser / app version: master
- Operating System: Gentoo Linux

### Additional information:

![Screenshot_20230519_181438](https://github.com/jitsi/jitsi-meet/assets/6336945/3a435255-437d-4c96-b34a-c21279ce7ffd)

**Comment by saghul** [comment]
Thanks for the report! Did you make any changes? Or did you just take master as is?

**Comment by pcvengros** [comment]
Hello, no changes. Just did git clone and next steps as reported. Tried few times, same result. App will be stuck on splash screen.

**Comment by saghul** [comment]
Thanks, we'll take a look.

Ping @Calinteodor

**Comment by pcvengros** [comment]
I have backtracked commits, error starts with 4c0c36d23 - upgrade to RN-0.69.10

**Comment by saghul** [comment]
Can you try building the mobile-23.2 branch?

**Comment by pcvengros** [comment]
same result...
checkout out branch, did all steps as above, same error when started project in android emulator

**Comment by saghul** [comment]
Thanks for testing. That's odd out betas we're built off that branch and don't seem to have that problem.

**Comment by saghul** [comment]
Hey there. I have not been able to reproduce the problem. What operating system are you using to build? What Node and npm versions?

**Comment by pcvengros** [comment]
OS: Gentoo Linux
NodeJS: v20.2.0
NPM: 9.6.6
Android Studio: 2022.2.1 Patch 1

I don't have react-native installed globally (via npm -g)
I will test this on Ubuntu 22.04 (in VM) next 2-3 days and report back

**Comment by saghul** [comment]
> NodeJS: v20.2.0
> NPM: 9.6.6

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet

> Node 16.x and npm 8.x are required. Any other version may result in runtime errors.

**Comment by pcvengros** [comment]
OK, will test it our on nodejs-16.X and npm-8.x.
Any chance the nodejs compatibility will be upgraded to latest LTS version (nodejs-18.x) ?

**Comment by saghul** [comment]
Yes, we have plans to update shortly!

**Comment by michel1tonon** [comment]
Any news? ... I'm facing exactly this problem in react-native update.

React-native: 0.72.3
node: 16.20.0
npm: 8.19.4

I would really be very grateful if you could help me.

**Comment by saghul** [comment]
We have no short term plans to move from version 0.69 at this time.

**Comment by amed12** [comment]
Hi @saghul , this issue still happen with error like below on branch mobile-23.4 , 
i use node v16.20.2, npm 8.19.4 , macOs Monterey v12.4
please inform me when need other data , 
` ERROR  TypeError: undefined is not an object (evaluating 'error.stack.split')
 LOG  Running "App" with {"initialProps":{"flags":{"pip.enabled":true,"call-integration.enabled":false,"server-url-change.enabled":true,"resolution":360,"welcomepage.enabled":true},"timestamp":1694749574412,"url":{"serverURL":"https://meet.jit.si","config":{}}},"rootTag":1}
 ERROR  Invariant Violation: "App" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
 ERROR  Invariant Violation: "LogBox" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
`

this error still happen right now , please help us to fix this

**Comment by saghul** [comment]
Sorry but I cannot reproduce this. I made a new beta fro mobile-23.4 just a few hours ago.

Have you tried cleaning up node_modules end reinstalling?

**Comment by amed12** [comment]
okay i will try to pull new changes from this https://github.com/jitsi/jitsi-meet/commits/mobile-23.4 , and report later , thank you

**Comment by amed12** [comment]
Hi @saghul , I wanted to update you on the issue I've been facing with the mobile-23.4 branch. 

I have done following steps:

1. Reinstalled the latest pull from the mobile-23.4 branch.
2. Cleared the Node modules.
3. Cleared the npm cache.
4. Cleared Watchman and babel.
5. Uninstalled the previous APK on my emulator.
However, despite these measures, the issue remains unresolved. I noticed that a similar issue has been reported on the React Native GitHub repository  , which you can find here: [link to the GitHub issue](https://github.com/facebook/react-native/issues/36101). are you aware about this or just different issue with jitsi lib ?

 Please let me know if you need any further information from me to assist in diagnosing the issue.

**Comment by saghul** [comment]
That is really strange! Do you have any changes or are you trying to build the code as is?

**Comment by amed12** [comment]
previously I only changed the UI for the purposes of the self custom library jitsi meet, I had no issue of this before, and started developing from mobile-23.2, but after moving laptops and re-cloning from the beginning this issue occurred in my repository, and tried re-cloning from latest version mobile-23.4 without changing any code from the jtsi meet repository and apparently this issue still occurs, is there a cache or something that causes this issue to occur?

**Comment by saghul** [comment]
Can you please detail the exact steps you are following?

**Comment by amed12** [comment]
Hi @saghul , now I can run normally Jitsi Meet on my Android emulator with api level 33, while the issue that occurs above occurs on Android api level 29, have you tried it on the android emulator with android api level 29 version?

**Comment by saghul** [comment]
Why do you think the API level is relevant? Does it work on an API level 33 emulator?

**Comment by amed12** [comment]
i dont know why, but its now normal on android emulator api level 33

**Comment by ysbutuner** [comment]
I encounter the same error in versions lower than API level 33. Is there a solution?

**Comment by saghul** [comment]
Please provide step by step reproduction details, try as I might I have been unable to do so.

**Comment by ysbutuner** [comment]
1. Reloaded latest pull from https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_8719 branch.
2. npm install
3. react-native run-android

It works at API level 33, but it does not work at API level 29,30,31,32

**Comment by saghul** [comment]
> 1. Reloaded latest pull from https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_8719 branch.

That is NOT a mobile release.

Please use the mobile app or SDK tags.



> It works at API level 33, but it does not work at API level 29,30,31,32
> 
> Note: It works on real phones, no problems

I'll be honest, simulators are not great to test most of the things RTC related, no this problem is not high priority, sorry.

**Comment by ysbutuner** [comment]
Reinstalled the latest pull from the mobile-23.4 branch.
npm install
react-native run-android
It works at API level 33, but it does not work at API level 29,30,31,32

Note: It works on real phones, no problems

the situation is still the same

**Comment by Vantam1601** [comment]
Are there any solutions?

**Comment by saghul** [comment]
I don't know, sorry.
