### ISSUE TITLE
Replace stock photos in README with something believable for a videoconference

### ISSUE THREAD

**Issue by fpesari** [jitsi/jitsi-meet#13398]
Hello,

sorry if this bug report sounds like a joke or trolling, it's actually not! This is the current mock screenshot for Jitsi Meet, as shown in README.md

![image](https://github.com/jitsi/jitsi-meet/assets/52702101/e4940703-f0d6-403b-a87e-3e9522ca2bc3)

Due to the:
- High image quality
- Professional-grade lighting
- Obvious model poses (who videochats like John Doe, Alexandra Williams or Michael Chase!)

this image does not look very believable for a video conference software and IMHO should be replaced with something more realistic (e.g. an actual screenshot, with all the imperfections of actual videochats), because Jitsi Meet is actually great software which works in real-life settings and this image does not do it justice.

**Comment by saghul** [comment]
These images go on app stores etc.

Random screenshots would likely  do a disservice, on the opposite direction.
