### ISSUE TITLE
Focus on chat textbox after clicking "Send private message"

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#13394]
When opening the chat, it rightly auto focuses on the textbox to write a message. That is convenient.

But if I hover over a user in the meeting and click 'Send private message' it doesn't auto focus on the textbox to write a message, and that is rather annoying.

Similarly if I click the reply button to a private message I have received in the chat, it doesn't auto focus on the textbox where I can type, when it should.

Version: 2.0.8695-1

**Comment by saghul** [comment]
Ping @horymury / @robertpin
