### ISSUE TITLE
Options.userEmail is not attached

### ISSUE THREAD

**Issue by a7mdragab** [jitsi/jitsi-meet#13395]
Hello
I have assigned the userEmail with a value but when joining the room, I receive it null
💡 onParticipantJoined: email: null, name: User1, role: participant, participantId: db3c991c

D/JitsiMeetSDK( 3306): ExternalAPI Sending event: PARTICIPANT_JOINED with data: { NativeMap: {"name":"User11","participantId":"db3c991c","role":"participant"} }

**Comment by saghul** [comment]
Can you please paste a code sample of how you are passing it?

**Comment by a7mdragab** [comment]
Flutter code: 

    var options = JitsiMeetingOptions(
      roomNameOrUrl: room,
      serverUrl: meetingServer,
      userEmail: 'email@domain.com',
      userAvatarUrl: "imageURl",
      featureFlags: featureFlags,
    );

      await JitsiMeetWrapper.joinMeeting(
        options: options,
        listener: JitsiMeetingListener(
          onParticipantJoined: (email, name, role, participantId) {
            print(
              "onParticipantJoined: (email: $email, name: $name, role: $role, "
              "participantId: $participantId)",
            );
          },
        ),
      );

**Comment by saghul** [comment]
The Flutter plugin was not written by us and last I checked it used and old and no longer supported SDK version. Unless you can reproduce it with our SDK I cannot really help you, sorry.

**Comment by a7mdragab** [comment]
Any help？

**Comment by a7mdragab** [comment]
> The Flutter plugin was not written by us and last I checked it used and old and no longer supported SDK version. Unless you can reproduce it with our SDK I cannot really help you, sorry.

Thanks for your reply.
I have upgraded ths jitsi sdk to the latest but with no luck.
I will try it. Thanks

**Comment by a7mdragab** [comment]
Can you check this:
```
dispatch(participantJoined({
            botType: user.getBotType(),
            conference,
            id,
            email: email,
            name: displayName,
            presence: user.getStatus(),
            role: user.getRole(),
            isReplacing,
            sources: user.getSources()
        }));
```

in [https://github.com/jitsi/jitsi-meet/tree/master/react/features/base/conference/functions.ts](url) line 102

**Comment by saghul** [comment]
Good catch! Can you please send it as a PR?

**Comment by a7mdragab** [comment]
> Good catch! Can you please send it as a PR?

Ready.
[https://github.com/jitsi/jitsi-meet/pull/13432](url)

**Comment by a7mdragab** [comment]
Please let me know the updated version ASAP to update the flutter plugin to it

**Comment by a7mdragab** [comment]
Hello,
Can you check this please.

[https://github.com/jitsi/jitsi-meet/pull/13447](url)

**Comment by saghul** [comment]
Sorry for the confusion. The participant has no "getEmail" property. The email is updated after the fact, but I don't think we have a PARTICIPANT_UPDATED event indicating that.
