### ISSUE TITLE
[Auto Recording Save]: If meet ends abruptly.

### ISSUE THREAD

**Issue by swastkk** [jitsi/jitsi-meet#13396]
**Is your feature request related to a problem you are facing?**
I was holding a meet for a Project and there I started `Meet Recording` but unfortunatly I ended the meet without using the option `Stop recording` and my recording for the meet was not saved. 

**Describe the solution you'd like**
If a user ends the meeting, the recording of the meet should automatically  saved like the `Stop recording` does.

**Comment by saghul** [comment]
👍 We will be working on this shortly.

**Comment by saghul** [comment]
This has been fixed in master.

**Comment by francedovan** [comment]
I also ended the meet without clicking "Stop recording" and I've lost my recording! Is there a way to recover it?

**Comment by saghul** [comment]
Have you checked your downloads folder?

**Comment by francedovan** [comment]
Yes, there's nothing in the downloads. I didn't send a meeting invitation to the other person, I just emailed them the jitsi meeting link. Is this the reason?

**Comment by saghul** [comment]
I'm afraid it has been lost :-(

Were you using meet.jit.si or your own deployment? In case it's the latter, what version of the server components are you running?

**Comment by francedovan** [comment]
meet.jit.si

**Comment by jmurphree77** [comment]
Just accidentally lost half my YouTube interview by closing the tab - I thought this was fixed? Is the file in a cached directory anywhere - please?

**Comment by saghul** [comment]
I thought we had fixed it... but I just tested and while there is an alert panel, I see no file being saved.

**Comment by jmurphree77** [comment]
This is the second and third time Jitsi has let me down for an interview, we were doing pre-recorded today because I was trying to avoid the interruptions we had live-streaming from Jitsi. Now I find out that the recordings I do have don't even use the cameraman. This is so disappointing, I looked in my browser cache and temporary folders... this is terrible.

**Comment by saghul** [comment]
So sorry about that :-/
