### ISSUE TITLE
Default Message Change for Microphone Permission

### ISSUE THREAD

**Issue by Jagroop-RTE** [jitsi/jitsi-meet#13409]
Is it possible to change the default message of :
"Meeting needs to user microphone and camera"
![Screenshot from 2023-05-30 13-41-26](https://github.com/jitsi/jitsi-meet/assets/122356764/25a997ec-59fe-4059-abee-cecea8ebeea8)

As it confuse user to allow Camera as well which is not needed in our case .
I also asked this question on community but didn't get any response that's why asking on github:  
https://community.jitsi.org/t/changing-default-message-in-jitsi/123929

**Comment by damencho** [comment]
You can change it here and rebuild the source and redeploy it.
https://github.com/jitsi/jitsi-meet/blob/804f9041a6676cf675440f205d096aef4b488a1a/lang/main.json#L1087
