### ISSUE TITLE
Three dots menu doesn't show under certain widths

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#13402]
### Description:

When the Jitsi's window width is 825px or less, if the chat is open on the sidebar, hovering over a user's three dots button doesn't bring up the menu (it used to months ago in previous versions).

Same with clicking the three dots on the bottom, it doesn't open up the menu there either when Jitsi is that width or less.

### Steps to reproduce:

1.  Open the chat.
2.  Make the Jitsi browser width to 825px or less.
3.  In tile view, click on the three dots over any user. Or click three dot at bottom of screen.

### Expected behavior:

Menu should appear.

### Actual behavior:

It doesn't appear.

### Server information:

- Jitsi Meet version:  2.0.8695-1

### Client information:

- Browser / app version: Google Chrome
- Operating System: Windows

**Comment by HJoshi012802** [comment]
I am taking this Issue

**Comment by saghul** [comment]
@robertpin can you PTAL next week?

**Comment by robertpin** [comment]
Works fine for me
<img width="736" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/11474153/b704f68d-c86c-4140-a1d6-54280dedd78b">

**Comment by zon3d** [comment]
> @zon3d can you try again now and see if you can still repro the issue?

Sorry for the delay. Yes, still same issue occurring on meet.jit.si

![Capture5](https://github.com/jitsi/jitsi-meet/assets/67055226/81a4b5bd-9d3d-43d6-9416-766cd44c3b42)

As you see, the three dots button has been pressed, but it's not showing the menu. It will only show the menu if the page width is widened.

**Comment by zon3d** [comment]
@robertpin Does that screenshot help?

**Comment by robertpin** [comment]
> @robertpin Does that screenshot help?

I can't repro the issue. Does it work with other browsers?

**Comment by zon3d** [comment]
@robertpin 
Yes, it works fine on Firefox and Edge, but not on Chrome. I tried on multiple computers too, never works on Chrome.

**Comment by zon3d** [comment]
@robertpin , are you able to reproduce it on Chrome?

**Comment by saghul** [comment]
Edge is Chrome on the inside, so I'd be very surprised if they behave differently.

**Comment by robertpin** [comment]
> @robertpin , are you able to reproduce it on Chrome?

I am not. It works fine for me
