### ISSUE TITLE
On some rare occasions PARTICIPANT_JOINED event is not broadcasted

### ISSUE THREAD

**Issue by smelfungus** [jitsi/jitsi-meet#13413]
Hello! We're facing a rare and flaky issue with a `PARTICIPANT_JOINED` event. It is not broadcasted in some rare random cases. We tried listening for local broadcasts and modifying SDK to inject our listener directly to `OngoingConferenceTracker`.

Correct event chain:
```
VIDEO_MUTED_CHANGED
CONFERENCE_WILL_JOIN
CONFERENCE_JOINED
PARTICIPANT_JOINED <===
VIDEO_MUTED_CHANGED
READY_TO_CLOSE
CONFERENCE_TERMINATED
```

Erroneous chain:
```
VIDEO_MUTED_CHANGED
VIDEO_MUTED_CHANGED
CONFERENCE_WILL_JOIN
CONFERENCE_JOINED
VIDEO_MUTED_CHANGED
READY_TO_CLOSE
CONFERENCE_TERMINATED
```

SDK version: 8.1.0, 8.1.2.

**Comment by damencho** [comment]
Have you tried in the case where you miss the PARTICIPANT_JOINED  to retrieve participants info on CONFERENCE_JOINED?

**Comment by saghul** [comment]
Are you expecting that event for the local participant or for remote ones?

**Comment by smelfungus** [comment]
Thank you for getting back to me!
It seems like the issue was related to the slow first SDK warmup, causing the participant on the web to join earlier than the SDK client. @damencho idea is brilliant, `PARTICIPANTS_INFO_RETRIEVED` broadcast and `RETRIEVE_PARTICIPANTS_INFO` request on `CONFERENCE_JOINED` did the trick.
Thank you!
