### ISSUE TITLE
possible to configure the volume slider?

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#13414]
This is more a question than a bug report.
We noticed that the volume slider has gone after updating to 8319.
Is this a configurable item that we can switch back on?
I perused all the menus and dialogues and I cannot find it.

**Comment by saghul** [comment]
It should be there, can you please share a screenshot?

**Comment by tseeling** [comment]
> It should be there, can you please share a screenshot?

A colleague pointed out to me that this is a configurable setting "config.remoteVideoMenu" which is set to "false" in our setup.
The "3 dot menu" in the upper right corner of the video pictures does not appear at all in our system.
Has the default setting changed between versions?
We only noticed because a teacher complained that the slider is gone
(we offer services for public schools).

**Comment by saghul** [comment]
Ah that explains.

If you set it to false the defaults won't matter, no menu will be shown.
