### ISSUE TITLE
Android share youtube video pauses

### ISSUE THREAD

**Issue by MahmoudMamdoouh** [jitsi/jitsi-meet#13415]
**when sharing a youtube video the video keeps on playing/pausing forever !!**

Log :

```
D/JitsiMeetSDK(24116): [features/share-video] User with id: b7cfb2e2 is playing video sharing.

V/AudioManager(24116): registerAudioFocusListener…

D/JitsiMeetSDK(24116): [features/share-video] User with id: b7cfb2e2 pause video sharing.

I/org.webrtc.Logging(24116): CameraStatistics: Camera fps: 30.

D/JitsiMeetSDK(24116): [features/share-video] User with id: b7cfb2e2 is playing video sharing.

V/AudioManager(24116): registerAudioFocusListener…
```

**Comment by saghul** [comment]
What version of the app / SDK are you using?

**Comment by MahmoudMamdoouh** [comment]
The latest release on the jitsi meet 2.0.8615 when running this version local works fine but if i made the sdk and used the issue appears, and if i used the latest mobile sdk example the issue is there

**Comment by saghul** [comment]
That's not an SDK release. The latest SDK version is 8.1.2.

**Comment by MahmoudMamdoouh** [comment]
I used the repo itself to customize then make my own sdk and there was no problem it works fine in the repo

i even used the sample in the documentation 
https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/android/java
And it also doesn’t work and I tried the 8.1.2 version too

**Comment by saghul** [comment]
Sorry you lost me. First you say it works on the repo then that it doesn't on version 8.1.2. Which one is it?

**Comment by MahmoudMamdoouh** [comment]
sorry for the confusion,
I used this " https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_8615 " to make my custom SDK  while working on it everything is fine but when I finished and build up my custom SDK the issue appeared,
so I tried to use the sample SDK test on  https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/android/java/JitsiSDKTest 
and the issue is  there too
when you try to s`hare a youtube video it keeps on pausing and playing without touching the phone

**Comment by saghul** [comment]
Ok. Si I assume you are also able to reproduce it with the stock Jitsi Meet app, right?

**Comment by MahmoudMamdoouh** [comment]
@saghul did you find anything?
