### ISSUE TITLE
Reaction Sounds are not playing with bluetooth earphones

### ISSUE THREAD

**Issue by SamarthBagga** [jitsi/jitsi-meet#13420]
### Description:
The reaction sounds are not audible while using bluetooth earphones. I have tried using two different bluetooth earphones one is JBL Live Pro+ and Boat AirDopes 441 but the issue is the same. Also these issues are also happening which are mentioned in this discussion - [jitsti community discussion](https://community.jitsi.org/t/jitsi-meet-causes-whole-system-to-have-no-sound-win10/20544/22).

### Steps to reproduce:

1.  Jitsi meet and connect your bluetooth earphones
2.  try to react using the reactions there is no sound
3.  change output device to the speaker and the sound is visible 

### Expected behavior:
Reaction sounds should be available even with bluetooth earphones.

- Browser / app version: Chrome
- Operating System:

**Comment by damencho** [comment]
<img width="280" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/3263098/eebcb1fd-ed89-4c81-9dee-fc133d21ff3a">

**Comment by SamarthBagga** [comment]
I am using windows 10. The test sounds are playing correctly through the bluetooth earphones but the reaction sounds are not. If I select my bluetooth earphones as the output device, the test sounds are heard but when i react there are no reaction sounds .

**Comment by saghul** [comment]
What is your default system output? THey are likely being played through it, this is a known issue currently.
