### ISSUE TITLE
Start The Meeting with Full-Screen Mode

### ISSUE THREAD

**Issue by ahmedkhairydev** [jitsi/jitsi-meet#13425]
**Is your feature request related to a problem you are facing?**
I'm facing a problem because I want to start the meeting in full-screen mode. I searched for a way to do that but I didn't get it.

**Describe the solution you'd like**
I suggest that should be a property in the config to be able the user to start the meeting in full-screen mode and add a custom command to execute it in the API to toggle the full-screen mode.

**Describe alternatives you've considered**
the alternative is a method that returns the toolbar HTML DOM.

**Comment by saghul** [comment]
There is no way to trigger full-screen unless it's from a user gesture, aka a button press. You can press the option in the 3 dots menu and make th emeeting full-screen there.

**Comment by ahmedkhairydev** [comment]
@saghul  I know that there's no way to do it. I wrote this issue to suggest you do it as a config property OR do a command to let me execute it whenever I want!

**Comment by saghul** [comment]
<img width="251" alt="Screen Shot 2023-06-06 at 17 01 24" src="https://github.com/jitsi/jitsi-meet/assets/317464/bd86a5bf-3e37-4a3a-8f52-a90d67a69b11">

You have the option in the menu. A command or API won't work because they are not user gestures.

**Comment by ahmedkhairydev** [comment]
@saghul Thank you for your effort to help me.
I know the option but my business case requires that the meeting starts in Full-Screen mode like Zoom for example.
So, I think you can do it by simulating the `Keyboard` `keydown` event by using `dispatchEvent` method.

```dispatchEvent(new KeyboardEvent("keydown", { key: "S" }))```

I tried to do it in TS from my project but I couldn't find the body or any HTML element else inside the iframe of the meeting.

**Comment by damencho** [comment]
This is not a user gesture and will not work. You just need to start chrome in fullscreen mode by adding `–start-fullscreen`

**Comment by ahmedkhairydev** [comment]
@damencho Thanks for your help. Your solution is not fitting my case.

@saghul I find a way to open a meeting in full-screen mode without user gesture 😎

In `videoConferenceJoined` event I added this below line of code.
```this.api.getIFrame().requestFullscreen()``` and for exit full-screen ```document.exitFullscreen()```

It works for me perfectly but after doing that, the `Full Screen` btn doesn't work properly because it doesn't know that the full screen is active.
![image](https://github.com/jitsi/jitsi-meet/assets/15922118/41c99faf-ae53-4927-b607-94d4f607dad8)
