### ISSUE TITLE
[Conf Call]- "Enable low bandwidth mode " label is having some issues when set to German (iOS)

### ISSUE THREAD

**Issue by marwenmoalla** [jitsi/jitsi-meet#13422]
Preconditions / test setup:
iOS device or application language set to German

Steps to reproduce:
Join a video conf call
Click on the 3 dots menu

Actual result or description of the tests done:
There is a display problem with the quotation mark on the label "Nur Audio"

**Comment by damencho** [comment]
Yeah the trasnslation seems suspicious 
https://github.com/jitsi/jitsi-meet/blob/ed37bedee27bc8721590c73479167196c32fb2f7/lang/main-de.json#L1093
