### ISSUE TITLE
Mirror my video button and pin to stage button not translated

### ISSUE THREAD

**Issue by marctemp1** [jitsi/jitsi-meet#13421]
### Description:

In any other language then English, the button "Mirror my video" on the video arrow is not translated (the button "Background" above it is translated properly. Same for the button "Pin to stage" in the thumbnail menu, while the buttons above are translated properly.

### Steps to reproduce:

1. Go to meet.jit.si/xuy123test (no need to add another participant)
2. Change the language to Dutch (or any other language than English, I tested Spanish and German)
3. Check the menu behind the triangle in the videobutton and the menu on the thumbnail

### Expected behavior:

Should be translated

### Actual behavior:

Doesn't translate
![image](https://github.com/jitsi/jitsi-meet/assets/66696480/ff029872-699e-4b80-b91e-cb5d4f3fb73e)

### Server information:

- Jitsi Meet version: actual meet.jit.si
- Operating System: latest stable

### Client information:

- Browser / app version: Chrome 113
- Operating System: W10

**Comment by damencho** [comment]
Thanks for the report, but the translations are contribution based, so if you want something translated any PRs are welcome.
More information you can find: https://github.com/jitsi/jitsi-meet/tree/master/lang#readme

**Comment by marctemp1** [comment]
It is not the translation. The translation files are fine. The bug is that it doesn’t select the correct language for these two buttons. It is always EnglishKind regards,Marc Op 4 jun. 2023 om 19:46 heeft Дамян Минков ***@***.***> het volgende geschreven:﻿
Thanks for the report, but the translations are contribution based, so if you want something translated any PRs are welcome.
More information you can find: https://github.com/jitsi/jitsi-meet/tree/master/lang#readme

**Comment by damencho** [comment]
I see, thank you
