### ISSUE TITLE
[iOS] chatToggled delegate not triggering when i tap on chat

### ISSUE THREAD

**Issue by yasserosama07** [jitsi/jitsi-meet#13434]
### Description:

When i tap on chat button the chat UI opens but chatToggled delegate not triggering, but it triggers when i close the chat UI

### Steps to reproduce:

1. Download JitsiMeetSDK ios samples
2. open swift sample
3. add chatToggled function in delegate 
4. run app and join conference & click on chat button

### Expected behavior:

It should trigger that the chat isOpen when i open Chat ui

### Actual behavior:

It only trigger when the chat is closed with ["isOpen": 0] & not when it's open.

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by yasserosama07** [comment]
7.0.0

**Comment by saghul** [comment]
Can you try 8.1.2? I don't remember when we added that delegate method.

**Comment by yasserosama07** [comment]
updated to 8.1.2 and still same behavior, triggering on close only.

**Comment by yasserosama07** [comment]
still exists in version 10.1.2
