### ISSUE TITLE
audioMuteStatusChanged not called on remote mute

### ISSUE THREAD

**Issue by garysmith058** [jitsi/jitsi-meet#13435]
### Description:

Using the web / iFame API.
When a participant is muted by a moderator, the iFrame API audioMuteStatusChanged is not called on the participant's system.

### Steps to reproduce:

1. Start a meeting with a moderator and a participant.
2. When the participant mutes, the audioMuteStatusChanged API event is called.
3. When the moderator mutes the participant, audioMuteStatusChanged is not called. This makes it difficult to keep track of the participants current mute status in the containing web page.

### Expected behavior:

The audioMuteStatusChanged API event should be called when the mute status changes, regardless of who does the muting.

### Actual behavior:

As above.

### Server information:

- Jitsi Meet version: Current on meet.jit.si
- Operating System: N/A

### Client information:

- Browser / app version: Any, using web iFrame API.
- Operating System: Any.

### Additional information:

In media/subscriber.ts there is a listener that only gets called when the local mute gets changed.
In conference.ts around line 1890 there is an event that gets called on remote mute.

I can see possible options: 

1. Introduce a new event like audioMutedRemotely and call that in conference.ts
2. Add sending the audioMuteStatusChanged event in conference.ts if it is an audio track
3. Add a global audio mute status listener in tracks/subscriber.ts (matching the video one already there) and then remove the call from media/subscriber.ts to prevent 2 audioMuteStatusChanged events being dispatched on local mute.

**Comment by saghul** [comment]
This event is only for the local user.
