### ISSUE TITLE
Add participantMenuButtonWithNotifyClick

### ISSUE THREAD

**Issue by Flying-Light** [jitsi/jitsi-meet#13446]
**Is your feature request related to a problem you are facing?**
While I am a moderator, I want to customize the participant Menu Button Click, 
but I have problems with the "**participantMenuButtonClicked**" Event:
1- It works only with the "**customParticipantMenuButtons**", it does not catch the built-in buttons click.
2- It has spelling mistake "**participantMenuButtonClicked**" not works, unless I used "**participantMenuButtonClick**"
while the API said it is **buttonsWithNotifyClicked** https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events/#participantmenubuttonclicked

**Describe the solution you'd like**
Add "**participantMenuButtonWithNotifyClick**" same way like "**buttonsWithNotifyClick**", so that we can select which buttons to trigger their clicks, and set "**preventExecution**" for these buttons.

**Comment by Flying-Light** [comment]
Any updates about this?
"**participantMenuButtonClicked**" event cannot be used as expected because of the mentioned problems,

Thanks

**Comment by mihhu** [comment]
> Any updates about this? "**participantMenuButtonClicked**" event cannot be used as expected because of the mentioned problems,

The docs have been amended to reference [participantMenuButtonClick](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events#participantmenubuttonclick) as you have guessed, thanks for reporting this!

> 1- It works only with the "customParticipantMenuButtons", it does not catch the built-in buttons click.

We'll discuss implementing it 🙌

**Comment by Flying-Light** [comment]
> We'll discuss implementing it 🙌

Thanks a million, and do not forget about "**preventExecution**" option, please 👏🏻

**Comment by mihhu** [comment]
hey @Flying-Light, did you have the chance to check out this feature? I'd like to close the issue

**Comment by Flying-Light** [comment]
> hey @Flying-Light, did you have the chance to check out this feature? I'd like to close the issue

Hi Mihhu,
I am using 8x8, and I do not think it is updated yet!!!
this is my current version:
**4245 – June 21, 2023 Release**
    Release: 4245
    Jitsi Meet: 7322
    Jitsi Videobridge: 2.3-25-g1da507fa
    Jicofo: 1038

Is this update included in this version?

**Comment by mihhu** [comment]
Ooh got it, no, it's not. It'll land next month most probably.
