### ISSUE TITLE
Screen sharing show a blank screen until other user reloads

### ISSUE THREAD

**Issue by prudloff-insite** [jitsi/jitsi-meet#13448]
### Description:

We are using the jitsi-meet Debian package.
We recently updated to 2.0.8615-1 and since then, screen sharing seems to be partially broken.
We tried to update to 2.0.8719-1 but it did not fix the problem.

We tried to reproduce on https://meet.jit.si/: it also shared a blank screen and also broke audio for both users as soon as the screen was shared.

### Steps to reproduce:

1. User A joins a room.
2. User B joins the same room.
3. User A shares its screen.
4. User B sees a blank screen.
5. User B reloads the page and now they can see the shared screen.

### Expected behavior:

Screen sharing should work the first time.

### Actual behavior:

Screen sharing only works after a page reload.

### Server information:

- Jitsi Meet version: 2.0.8719-1
- Operating System: Debian GNU/Linux 10 (buster)
 
### Client information:

- Browser / app version: Firefox 114.0.1
- Operating System: Linux Mint 21

### Additional information:

It seems to happen almost every-time when there are only 2 users in the room, but we also sometimes have the bug with more users.

**Comment by damencho** [comment]
Have you tried with different browser on the same machine? 
Is always the problem with the browser sharing from the Linux machine?

**Comment by prudloff-insite** [comment]
We were able to reproduce on several machines with the following browsers initiating sharing:
* Firefox on Linux
* Firefox on Windows
* Chromium on Linux

**Comment by jallamsetty1** [comment]
@prudloff-insite We are unable to reproduce this issue with Firefox on Windows, macOS and Ubuntu. Can you please share the browser console logs of the sender and receiver when this happens? Can you also if sender is actually sending media for the screenshare when this happens ? You can check the total upload bandwidth on the sender.

**Comment by prudloff-insite** [comment]
For this test both users are on the same network (but we can also reproduce from different networks).

Logs from receiver (Firefox 114.0.1 on Linux Mint 21) before reload (can't see screenshare): [receiver_before.txt](https://github.com/jitsi/jitsi-meet/files/11786308/receiver_before.txt)
Logs from receiver after reload (can now see screenshare): [receiver_after.txt](https://github.com/jitsi/jitsi-meet/files/11786309/receiver_after.txt)
Logs from sender (Firefox 114.0.1 on Linux Mint 20.3): [sender.txt](https://github.com/jitsi/jitsi-meet/files/11786310/sender.txt)

What the receiver sees about the sender when screenshare is blank:
![image](https://github.com/jitsi/jitsi-meet/assets/50333926/e28fee11-9b00-455d-ad41-63ec61ba3b30)

**Comment by foMXdsyZHPY0** [comment]
We have the same issue, running jitsi-meet 2.0.8719-1 on Debian 12.0. Tested with browsers

Firefox 114.0.1 Windows
Chrome 114.0.5735.134 Windows
Edge 114.0.1823.51 Windows

Connection details look the same as @prudloff-insite provided. How can we get the receiver and sender logs?

**Comment by saghul** [comment]
@jallamsetty1 We are currently experiencing the same on mobile (latest beta).

I told @Calinteodor to take a look, but if it manifests on web too, maybe it's a common problem?

Basically SS is not visible unless you join the meeting after the user started sharing.

**Comment by jallamsetty1** [comment]
@saghul I don't know if its the same problem. I don't have the logs for the issue on mobile but looking at the logs that @prudloff-insite shared here, this seems to be a jvb issue.

In this call, p2p ICE was never established and the media was being sent/received over jvb connection even though it was a 1-1 call. Before the receiver reloaded, there were issues with JVB ICE connection and the client was restarted via session-terminate. The bridge did not forward the screenshare (only video source) after the new session was established.

```
2023-06-19T08:41:21.248Z [modules/xmpp/JingleSessionPC.js] <5047/_addOrRemoveRemoteStream/</<>:  JingleSessionPC[session=JVB,initiator=false,sid=c7s0q5iv718jt] addRemoteStream - OK Logger.js:154:22
2023-06-19T08:41:26.446Z [modules/xmpp/JingleSessionPC.js] <5047/doInitialize/this.peerconnection.oniceconnectionstatechange>:  (TIME) ICE disconnected JVB:	 42116 Logger.js:154:22
2023-06-19T08:41:31.123Z [modules/xmpp/JingleSessionPC.js] <5047/doInitialize/this.peerconnection.oniceconnectionstatechange>:  (TIME) ICE connected JVB:	 46795 Logger.js:154:22
2023-06-19T08:41:40.074Z [modules/xmpp/JingleSessionPC.js] <5047/doInitialize/this.peerconnection.oniceconnectionstatechange>:  (TIME) ICE disconnected JVB:	 55746 Logger.js:154:22
WebRTC: ICE failed, add a STUN server and see about:webrtc for more details
2023-06-19T08:42:01.124Z [modules/xmpp/JingleSessionPC.js] <5047/doInitialize/this.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed JVB:	 76796 Logger.js:154:22
2023-06-19T08:42:01.124Z [modules/RTC/BridgeChannel.js] <5047/_handleChannel/e.onclose>:  Channel closed by server Logger.js:154:22
2023-06-19T08:42:01.125Z [modules/RTC/BridgeChannel.js] <5047/_handleChannel/e.onclose>:  Channel closed: undefined undefined Logger.js:154:22
2023-06-19T08:42:03.276Z [modules/connectivity/IceFailedHandling.js] <_actOnIceFailed>:  ICE failed, enableForcedReload: undefined, enableIceRestart: undefined, supports restart by terminate: true Logger.js:154:22
```

```
2023-06-19T08:42:04.275Z [modules/RTC/BridgeChannel.js] <5047/_handleChannel/e.onmessage>:  New forwarded sources: Logger.js:154:22
**2023-06-19T08:42:04.275Z [modules/RTC/RTC.js] <_onForwardedSourcesChanged>:  Fowarded sources changed leaving=c687cfa0-v0, entering= at 1687164124275 Logger.js:154:22**
```

@prudloff-insite Are you able to reproduce this reliably on meet.jit.si ? If so, can you please provide logs from there so that we can take a look at the bridge logs. We won't be able to debug calls from your deployment.

**Comment by foMXdsyZHPY0** [comment]
If I may add, we tested again with p2p setting enabled and disabled:

p2p disabled:
1. User A creates a room.
2. User B joins the same room.
3. User A shares its screen.
4. User B sees a blank screen.
5. User B reloads the page and now they can see the shared screen.

p2p enabled:
1. User A creates a room.
2. User B joins the same room.
3. User A shares its screen.
4. User B sees the screen, everything ok.
5. User C joins the room: User C sees screen of A, but B turns to blank screen.
6. User B reloads the page and can see the shared screen of A. User C unchanged.

Not sure if my logs help?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 We are currently experiencing the same on mobile (latest beta).
> 
> I told @Calinteodor to take a look, but if it manifests on web too, maybe it's a common problem?
> 
> Basically SS is not visible unless you join the meeting after the user started sharing.

@saghul We were able to repro the issue again today and it turned out to be an issue with receiver constraints in audio-only mode. I am working on a fix. Trying to confirm if this is the same issue as that one.

**Comment by foMXdsyZHPY0** [comment]
@jallamsetty1 
Yes, my tests were conducted in audio-only mode. I did not test on meet.jitsi.si.

With p2p disabled and when I activate the camera explicitely on the welcome screen before joining the room, the screen sharing works immediately without reload.
