### ISSUE TITLE
Timer Feature for Breakout Rooms

### ISSUE THREAD

**Issue by franzihei** [jitsi/jitsi-meet#13456]
**Is your feature request related to a problem you are facing?**
In bigger calls (40ish people) I use the breakout room feature frequently. It works well, except for the part when I want to reconvene everybody back into the main room. To my knowledge there is currently no way for me to set a timer that appears in all breakout rooms to let them know I will be closing the breakout room soon. This creates a very harsh and abrupt ending for the people in the breakout rooms since they are basically thrown out without warning.

**Describe the solution you'd like**
Implement a "timer" feature: I think a global timer that I could set from the main room (e.g. a 1, 5 or 10 mins countdown) to all breakout rooms would be an amazing feature to have.

This could be implemented either by just displaying the countdown to all rooms, or opening rooms that by default will close after a certain predefined period of time and will lead everybody back to the main room.

**Describe alternatives you've considered**
There is no good viable alternative to this that I know of.

Edit: Just for context, I also posted this idea / feature request in the forum a while ago [here](https://community.jitsi.org/t/timer-feature-for-breakout-rooms/122797).

**Comment by franzihei** [comment]
_ping_ on the above 👆 

Is a feature like this feasible / planned?

**Comment by saghul** [comment]
We have no plans to work on this anytime soon.

**Comment by rasos** [comment]
An alternative approach would be to give moderators the option to send a chat message to all breakout rooms. This way the gathering back to the main room could be announced to all participants.
