### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by quidlab** [jitsi/jitsi-meet#13452]
There seems to be a typo error " should be : 
https://github.com/jitsi/jitsi-meet/blob/19185665815c535e0f603733bb2f967988881e42/resources/extra-large-conference/prosody.cfg.lua.visitor.template#LL44C4-L44C11

**Comment by neshvig10** [comment]
I would like to work on this issue , can you please assign this to me , as well as elaborate some more

**Comment by saghul** [comment]
We don't assign issues. If you want to fix it please do and send a PR :-)

**Comment by damencho** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/commit/60a995d6542accee31d015aa6ea2df9780d6fc33
