### ISSUE TITLE
SDK screenShareToggled method or SCREEN_SHARE_TOGGLED event no longer triggered when screen share button pressed

### ISSUE THREAD

**Issue by widetechidmobile** [jitsi/jitsi-meet#13454]
### Description:

Hi Jitsi Team,
I’ve using Jitsi Meet Mobile SDK 6.3.6 and developing my own native toolbox and listening for native events emitted for my button icon, status, and function. One of the methods I used is screenShareToggled. But later when I update to Jitsi Meet Mobile SDK 8.1.2 that method never gets triggered anymore.

I check on mobile/external-api/middleware.js and the code still there. I don’t see any code change

```
StateListenerRegistry.register(
    /* selector */ state => state['features/base/tracks'],
    /* listener */ debounce((tracks, store) => {
        const oldScreenShares = store.getState()['features/mobile/external-api'].screenShares || [];
        const newScreenShares = tracks
            .filter(track => track.mediaType === 'video' && track.videoType === 'desktop')
            .map(track => track.participantId);

        oldScreenShares.forEach(participantId => {
            if (!newScreenShares.includes(participantId)) {
                sendEvent(
                    store,
                    SCREEN_SHARE_TOGGLED,
                    /* data */ {
                        participantId,
                        sharing: false
                    });
            }
        });

        newScreenShares.forEach(participantId => {
            if (!oldScreenShares.includes(participantId)) {
                sendEvent(
                    store,
                    SCREEN_SHARE_TOGGLED,
                    /* data */ {
                        participantId,
                        sharing: true
                    });
            }
        });

        store.dispatch(setParticipantsWithScreenShare(newScreenShares));

    }, 100));
```

### Steps to reproduce:

1. On the mobile (android/ios) press start screen share/ stop screen share 

### Expected behavior:

screenShareToggled method will be triggered on the native side of the app

### Actual behavior:

screenShareToggled never get triggered

### Server information:

- Jitsi Meet version:  Any Version
- Operating System: Ubuntu

### Client information:

- Browser / app version: SDK version 8.0.0 and above
- Operating System: Android & IOS

**Comment by saghul** [comment]
@Calinteodor can you PTAL?

**Comment by widetechidmobile** [comment]
Hi Jitsi Team, any update on this?

**Comment by Calinteodor** [comment]
Thanks for the report and patience! Fix has been merged and will be available in the latest release.
