### ISSUE TITLE
Login from Settings -> Profile isn't working as expected

### ISSUE THREAD

**Issue by pabelenda** [jitsi/jitsi-meet#13455]
### Description:

I am the maintainer of a jitsi-meet infrastructure. The configuration is such that to create a new conference you have to authenticate against our corporate LDAP server. That make the first user to be a moderator. Following users join in without such a privilege and without having to authenticate (unless we setup a password). If they want to gain moderators rights by themselves they have to login. They are ale to login, but they have to reload to be able to use the moderator functions.

### Steps to reproduce:

1.  Open Settings
2.  Go to Profile
3.  Click on the Login blue button inside Authenticate
4. The login dialog appears
5. Enter the data

### Expected behavior:

The login dialog disappears and the user is now a moderator

### Actual behavior:

The login dialog remains visible. If the user reloads, the call recognizes them as moderators.

### Server information:

- Jitsi Meet version: started to happen in 2.0.8615-1, still happening in 2.0.8719-1
- Operating System: Debian 11

### Client information:

- Browser / app version: Firefox 102.11.0esr, Chrome 114.0.5735.106 (Official Build) , Chromium  114.0.5735.106 (Official Build) built on Debian 12.0, running on Debian 12.0, Electron app 2023.5.3
- Operating System: Debian 12

### Additional information:

I'm pasting console output here:

```
2023-06-14T10:36:18.609Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: [object Object] Script: null Line: null Column: null StackTrace:  n/a
s @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.ts:511
window.onunhandledrejection @ middleware.ts:96
systems:1 Uncaught (in promise) {authenticationError: undefined, message: 'this.room.moderator.allocateConferenceFocus is not a function'}
```

**Comment by pabelenda** [comment]
Hi! Is there anything I could be adding to this report to make it easier to track down or something?

**Comment by saghul** [comment]
We were actually planning on removing that button.

What is your use case?

cc @damencho

**Comment by damencho** [comment]
Yep, actually @saghul I got it working. We have it working for mobile so I will consolidate the code.
There is a small fix it need in ljm for this one.
I'm working on it, hope to have a PR tomorrow or the day after.

**Comment by saghul** [comment]
Excellent!

**Comment by pabelenda** [comment]
> We were actually planning on removing that button.
> 
> What is your use case?
> 
> cc @damencho

Oh really? For us it's really handy! Not like we use it everyday but... Let me explain.

We run every two months (sometimes a bit more, sometimes less) long meetings in which almost all of our people is invited. We are around 140 and getting bigger and our attendance peak was around 120. 

Those meetings are divided on topics and there's an small portion for each one in which there's a debate. For that to be sane, there's an appointed moderator assigned to each topic the have to keep an eye on the clock, introduce speakers and manage people in the turns list (*).

As you can imagine, in a more than a 100 people meeting the possibilities of an rogue open microphone/camera skyrocket. For the appointed moderators to be able to manage that they need to be recognized by jitsi as Moderators.

Our deployment is configured such as to be able to create a meeting you need to log in and authenticate against our LDAP server. First one to arrive creates the meeting, next attendants go in directly (we later on add a password to be protected). So people that has logged in first (usually me, the sysadmin) are moderators but that's not the case for appointed moderators. Without this feature, we will have to manually look for them and make them moderators which is not ideal for us, as we are running a more than a 100 people meeting that have other needs on top of this one. If people can manage this themselves would be quite nice for us.

(*) We where really happy when this feature was finally implemented, life changing for us. Thank you so much!

**Comment by damencho** [comment]
That functionality was broken for more than half a year and we got a single complaint two weeks back. That's why we initially decided to drop it, as it seems nobody is using it. 
While doing the implementation it turns out we can keep it as some logic existed already in the part of the code we will keep.
So that stays for now. But check the forum we plan at some point to drop all auth methods and leave just jwt, so people can implement their own authentication mechanisms or integrate easily in existing one.

**Comment by pabelenda** [comment]
> That functionality was broken for more than half a year and we got a single complaint two weeks back. That's why we initially decided to drop it, as it seems nobody is using it. While doing the implementation it turns out we can keep it as some logic existed already in the part of the code we will keep. So that stays for now. But check the forum we plan at some point to drop all auth methods and leave just jwt, so people can implement their own authentication mechanisms or integrate easily in existing one.

For us was a bit less of a problem for some time because we keep two different platforms in case there are regressions, which was kinda common years ago but not really much of a thing lately. We keep testing the latest release and also have a previous version running that we consider "our stable" version. But on some occasions, if enough time passes, we need to move forward the stable environment no matter what otherwise the platform starts to have trouble on some of our clients systems, browsers and that sort of stuff.

In hindsight we should have reported this straight away, sorry about that.

Thanks for the pointer to the forum regarding dropping all auth methods, we will stay tuned
