### ISSUE TITLE
User entered values shown in white color in chat textfield in landscape mode

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13469]
- User entered values shown in white color in chat textfield in landscape mode
- Image Link: [https://drive.google.com/file/d/1slqn8w3vsNgJp5jhEnz_dCmCZ3dXIQW5/view?usp=drive_link](url)
![viber_image_2023-06-19_17-47-48-159](https://github.com/jitsi/jitsi-meet/assets/60642304/ca0ee3d3-76a5-4791-bf71-e27319b9c591)

**Comment by saghul** [comment]
What app or SDK version is that?

@Calinteodor 👀

**Comment by JagaranMaharjan** [comment]
@saghul SDK version is 8.1.2
I solve this issue by following ways:

**Step 1:** Open style.ts file and add own css as
customInput:{
color:'#000000'
}

<img width="879" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/60642304/8d103559-0a11-4fb9-a13e-07bd0283ea22">

Step 2: Open ChatInputBar.tsx and update line no. 78 as
customStyles == {{container: styles.customInputContainer, input: styles.customInput}}
<img width="876" alt="viber_image_2023-06-20_11-13-49-166" src="https://github.com/jitsi/jitsi-meet/assets/60642304/b8a8011c-6e09-490a-a034-6186d76ace19">
