### ISSUE TITLE
Only chromium shows `Start recording` button

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#13465]
On https://meet.jit.si and my own instance the `Start recording` button is present only in chromium browser.
Neither firefox 114 nor jitsi-meet-electron 2023.5.3 show it. I see no errors in browser console. I'm on debian sid.
In chromium recording works as expected.

**Comment by saghul** [comment]
This is expected if your deployment doesn't have Jibris, aka cloud recording. In that case only local recordings are possible, and currently only Chromium supports the necessary APIs.
