### ISSUE TITLE
Quirks Mode is used

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#13466]
Firefox and electron client show warning about Quirks Mode due to lack of `<!DOCTYPE html>`

**Comment by saghul** [comment]
I tried to fix it but got a bunch of weird layout issues. A PR would be most welcome!

**Comment by Leimi** [comment]
Hey @saghul,

i'm willing to work on this but I have trouble understanding how to change the html code when working locally. It seems just editing the index.html doesn't work. Any tips?

**Comment by saghul** [comment]
Yeah the proxy target hunk code is used. If you have a VM you can point the proxy there. Alas that's the o my way I know.

**Comment by 532910** [comment]
I believe the `stale` fact is not a reason to close this issue.
