### ISSUE TITLE
Edit HTML files in new version of Jitsi MEet

### ISSUE THREAD

**Issue by bamms** [jitsi/jitsi-meet#1346]
Installed the latest version. Been trying to locate the HTML files so I can make some editing but haven't been able to locate them. I know react.js might have been implemented, but please guide on how I can make UI changes. Searched for over 2 days and not found
Please help

**Comment by saghul** [comment]
What are you looking for specifically? They are all here. Except for the parts written with react, which are in the react/ directory.

PS: Please use the mailing list for questions, we keep the issue tracker just for issues.

**Comment by bamms** [comment]
For instance, Looking for the welcome page HTML folder to make adjustments
They are all where please?

**Comment by bamms** [comment]
Din't really get the directory you referred to as 'They are all here'. Please guide
Thanks

**Comment by saghul** [comment]
I meant "here" as in "in this repo". Here is the welcome page, for example: https://github.com/jitsi/jitsi-meet/blob/master/react/features/welcome/components/WelcomePage.web.js

**Comment by bamms** [comment]
Thanks
But all the changes I try to make in the file is not reflecting online.
And even when I try to rename the file so the jisto home page disappears, it still didnt make any difference on the Home page. What I still have on the home page is the jisti design and i need to adjust it. 


Please kindly guide on how to make adjustments to the jitsi home page UI
Thanks

**Comment by saghul** [comment]
You need to "build" the site after you make changes, this is no different than any modern web application using React.

Please use the mailing list for such questions.

**Comment by bamms** [comment]
Hi Saúl,Hi All,
Tried following your guide Saul, to build the site after making changes.
Tried running "npm run start:web" Inside path/jitsi-meet
But got the error 
"Missing script: start:web"
Kindly guide me to  let me know how to do the building. Just started playing with react on ubuntu server
Thank you.


Please all, find initial orginal issue below:

All the changes I try to make in the latest jitsi home page file online is not reflecting online.
And even when I try to rename the file so the jisti home page disappears, it still didnt make any difference on the Home page. What I still have on the home page is the jisti design and i need to adjust it. 


Please kindly guide on how to make adjustments to the jitsi home page UI
Thanks

**Comment by bamms** [comment]
PLEASE HELP!!!!
The new react system really needs a proper guide/documentation.
Tried and Tried and Tried to build as Saul suggested
Home page changes are not reflecting and my application is live! 
keep getting error when I try building. Maybe because am a bit new to REact, but a guide will help.
I copied the package.json and webpack.config.js from here "https://github.com/jitsi/jitsi-meet" into my ubuntu.
 But the "npm run start:web" will still not run. Various errorsLatest one is attached
I need a guide please!



      From: Abayomi Bamiwo <baa_yoo@yahoo.com>
 To: dev@jitsi.org 
 Sent: Tuesday, February 28, 2017 6:22 AM
 Subject: Fw: [jitsi/jitsi-meet] Edit HTML files in new version of Jitsi MEet (#1346)
   


     
----- Forwarded Message -----

**Comment by saghul** [comment]
Please, be polite, suing caps in an online communication is considered shouting, and that's not welcome here.

Now, when I told you you needed to build the app I also told you to have a look at the README. Please see here: https://github.com/jitsi/jitsi-meet#building-the-sources

I'm not sure where you got the idea that `npm run start:web` would work, but definitely not from our documentation.

So, after making your changes and running `make` as the README suggests your app should reflect the changes just fine.

Last, while I agree our documentation is sorely lacking, there is nothing special about Jitsi Meet, it's a web application which uses React, so official react documentation applies.

**Comment by bamms** [comment]
Thanks alot saul
I applogize for the 

Had alot of pressure because I was live and needed to make the adjustment urgently
Will also see how I can gelp with the doc once I get it and also master the react appropiately
Will follow your guide and revert
Thank for always being patience with response. you deserve the nomination :)

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 2, 2017 at 10:39 AM, Saúl Ibarra Corretgé<notifications@github.com> wrote:   
Please, be polite, suing caps in an online communication is considered shouting, and that's not welcome here.

Now, when I told you you needed to build the app I also told you to have a look at the README. Please see here: https://github.com/jitsi/jitsi-meet#building-the-sources

I'm not sure where you got the idea that npm run start:web would work, but definitely not from our documentation.

So, after making your changes and running make as the README suggests your app should reflect the changes just fine.

Last, while I agree our documentation is sorely lacking, there is nothing special about Jitsi Meet, it's a web application which uses React, so official react documentation applies.
