### ISSUE TITLE
An error occurred during the conversion from P2P to JVB.

### ISSUE THREAD

**Issue by MovingBrick-er** [jitsi/jitsi-meet#13477]
When deploying Jitsi Meet using Docker Desktop and switching from p2p (peer-to-peer) mode to JVB (Jitsi Videobridge) mode, you encountered the following warning: "Received request for a nonexistent conference: d7a888a035f8441f". Additionally, when a third user joins the conference, other users can only see their own video, and the videos of other participants are not displayed. However, when a user leaves the conference, the audio in p2p mode resumes normally.

----------------------------
I am a Chinese user, and this question is submitted to you through translation software. If there is anything unclear, I can provide more context. Please help me translate it into English.

**Comment by MovingBrick-er** [comment]
Set up in docker, LAN deployment, but now I install a blog deployment

**Comment by MovingBrick-er** [comment]
Set up in docker, LAN deployment, but I now deploy according to a blog

**Comment by MovingBrick-er** [comment]
Now that this problem has been solved, I would like to ask if we have the function of integrating the whiteboard

**Comment by saghul** [comment]
> Now that this problem has been solved, I would like to ask if we have the function of integrating the whiteboard

There is currently no builtin support, but you can run the backend yourself and use the whiteboard URL env variable.
