### ISSUE TITLE
meet.jit.si: should warn about blocked JavaScript

### ISSUE THREAD

**Issue by 4cq2** [jitsi/jitsi-meet#13471]
I ran into this today:

> Uh oh! We couldn't fully download everything we needed :( We will try again shortly. In the mean time, check for problems with your Internet connection!

https://github.com/jitsi/jitsi-meet/blob/d608cf40f5c63d6c7f81688acad97c3eae036ddd/index.html#L136-L139

turns out its because I am blocking JavaScript, and this rule for uBlock Origin is needed:

~~~
jit.si jitsi.net * noop
~~~

I think the current message is misleading, and could be helpful with something added such as:

> make sure `jitsi.net` is not blocked

use whatever wording you like.

**Comment by saghul** [comment]
We already provide the noscript tag: https://github.com/jitsi/jitsi-meet/blob/169c8ecb62645a49f9ad2485747e51d659672677/index.html#L204

You blocking JavaScript is indistinguishable from a network problem, from the web apps perspective.

If you are blocking random JS you should not be surprised that things don't work as expected.

**Comment by saghul** [comment]
I like to think I treat our users fairly. You not liking the answer is a different story.

You can't assume that downloading one asset failing means it was blocked. There is zero indication of that happening.

If you, the user, are choosing for a degraded experience then it's up to you to fix it. We simply can't.

We do provide an indication in case all JS is blocked, but as I said, we can't know if selective JS is blocked or if there is a network error. If such way exists, of course I'd be happy to take a PR adding a more meaningful error message.

**Comment by 4cq2** [comment]
> I like to think I treat our users fairly. You not liking the answer is a different story.

you don't get to decide how people feel about your responses. the people impacted by your decisions can decide if its fair or not. that would be like slapping someone in the face, and then saying "that didn't hurt". you don't get to make that decision.

> You can't assume that downloading one asset failing means it was blocked. There is zero indication of that happening.

and you cant assume its because of a bad connection. if first party resource works and third party fails, its LIKELY because of ad blocking. so in that case, the website could report:

> having trouble, make sure to allow `jitsi.net`

then if the problem IS adblocking, then user will know how to fix. if the issue IS NOT ad blocking, then having that message doesnt hurt anything.

> If you, the user, are choosing for a degraded experience then it's up to you to fix it. We simply can't.

I am choosing a bloat free experience. I accept the tradeoffs for that. I dont accept websites giving misleading error messages. most websites that break from blocking scripts just end up as a mostly white page, honestly that would be preferred to the current misleading message.

> We do provide an indication in case all JS is blocked, but as I said, we can't know if selective JS is blocked or if there is a network error. If such way exists, of course I'd be happy to take a PR adding a more meaningful error message.

done

**Comment by saghul** [comment]
> you don't get to decide how people feel about your responses. the people impacted by your decisions can decide if its fair or not. that would be like slapping someone in the face, and then saying "that didn't hurt". you don't get to make that decision.

You are just twisting words because you don't like that I disagree with your solution. This is my last reply in this thread.
