### ISSUE TITLE
Custom UI: Archive failed on IOS 

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13478]
Step 1: Clone project from https://github.com/jitsi/jitsi-meet.git
Step 2: Checkout to branch mobile-23.2
Step 3: Install node modules 
Step 4: Pod install
Step 5: Run following script 
mkdir -p ios/sdk/out
xcodebuild clean \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphonesimulator \
    -destination='generic/platform=iOS Simulator' \
    -archivePath ios/sdk/out/ios-simulator \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphoneos \
    -destination='generic/platform=iOS' \
    -archivePath ios/sdk/out/ios-device \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
    -framework ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -framework ios/sdk/out/ios-simulator.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -output ios/sdk/out/JitsiMeetSDK.xcframework
Step 6: After running script got following error	
Error:
	SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\ Promises.swiftinterface /Users/Jagaran/Library/Developer/Xcode/DerivedData/jitsi-meet-elufcejokxjialammxvfjyyskogb/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/PromisesSwift.build/Objects-normal/arm64/Promises.swiftinterface (in target 'PromisesSwift' from project 'Pods')
(1 failure)
error: the path does not point to a valid framework: /Users/Jagaran/Desktop/jitsi-meet/jitsi-meet/ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework

**Comment by saghul** [comment]
What Xcode version are you using?

**Comment by JagaranMaharjan** [comment]
@saghul my Xcode version is 14.3

**Comment by saghul** [comment]
Can you test 14.2?

**Comment by denuka-rai** [comment]
@saghul  on xcode version 14.2 archive build was success  but following issues were arised
step 6 : Archived build success
step 7 : as per documentation https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk JitsiMeetView was created
 code snippet

import UIKit
import JitsiMeetSDK

class CustomJitSiViewController: UIViewController,JitsiMeetViewDelegate {
    
    @IBOutlet weak var jitsiMeetView: JitsiMeetView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        jitsiMeetView.delegate = self
        let options = JitsiMeetConferenceOptions.fromBuilder { builder in
            builder.serverURL = URL(string: "https://meet.jit.si")
            builder.room = "test123"
            builder.setFeatureFlag("audioOnly", withValue: true)
        }
        
        jitsiMeetView.join(options)
    }
    
}
step 8 : while building application following issue was arised
dyld[3846]: Library not loaded: @rpath/GiphyUISDK.framework/GiphyUISDK
  Referenced from: <8C0F96DA-1D5C-3A63-87E1-FF97821331DC> /private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK
  Reason: tried: '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/preboot/Cryptexes/OS@rpath/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/JitsiMeetSDK.framework/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/private/var/containers/Bundle/Application/9818DE7C-F929-461D-A8AA-25E5952BA0CC/Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2), '/System/Library/Frameworks/GiphyUISDK.framework/GiphyUISDK' (errno=2, not in dyld cache)

**Comment by JagaranMaharjan** [comment]
@saghul 
Step 9:  by adding missing dependency Giphy it Archive Build was success
Step 10: Integrated to project works well but host shared video & screen is not visible to ios user.
**Jitsi Framework was build from branch mobile-23.2**

Because of this reason, we checkout from branch mobile-23.2 to mobile-23.1. Here, Archive Build was failed with following error:
warning: Run script build phase 'Copy sounds' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'JitsiMeetSDK' from project 'sdk')
warning: Run script build phase 'Package React bundle' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'JitsiMeetSDK' from project 'sdk')
** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/Jagaran/Library/Developer/Xcode/DerivedData/jitsi-meet-elufcejokxjialammxvfjyyskogb/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-bridging.build/Objects-normal/arm64/LongLivedObject.o /Users/Jagaran/Desktop/jitsi-meet/jitsi-meet/node_modules/react-native/ReactCommon/react/bridging/LongLivedObject.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-bridging' from project 'Pods')
(1 failure)
error: the path does not point to a valid framework: /Users/Jagaran/Desktop/jitsi-meet/jitsi-meet/ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework
<img width="1792" alt="Screenshot 2023-06-22 at 12 09 10" src="https://github.com/jitsi/jitsi-meet/assets/60642304/13e7a4f6-77fd-400a-8815-2f3131a153ec">

**Comment by saghul** [comment]
Did you reinstall all libraries and pods after switching branches?

**Comment by JagaranMaharjan** [comment]
@saghul yes we did

**Comment by JagaranMaharjan** [comment]
@saghul why host shared video and screen is not visible to ios user from branch mobile-23.2

**Comment by saghul** [comment]
That bug got fixed yesterday :-) If you refresh your 23.2 banch it should start working now.

**Comment by JagaranMaharjan** [comment]
@saghul I checkout on branch mobile-23.0.1, archive build & integration works well but while leaving meeting following issue was aries which i have shown you on video below
https://github.com/jitsi/jitsi-meet/assets/60642304/4fe00609-17cd-4f8a-8956-86d5301c2cc3

**Comment by saghul** [comment]
Are you getting the ready to close event?

**Comment by JagaranMaharjan** [comment]
@saghul yes

**Comment by JagaranMaharjan** [comment]
@saghul how to set our default meeting view layout to landscape orientation

**Comment by saghul** [comment]
Are you not hiding the view on that event?

**Comment by JagaranMaharjan** [comment]
@saghul I made changes on AppDelegate.m file & info.plist file to make default orientation of jitsi meet as landscape but did not work why?
<img width="531" alt="Screenshot 2023-06-22 at 17 22 15" src="https://github.com/jitsi/jitsi-meet/assets/60642304/de10d294-79fc-47e0-b2
<img width="1070" alt="Screenshot 2023-06-22 at 17 22 30" src="https://github.com/jitsi/jitsi-meet/assets/60642304/87b36470-6aeb-4a4d-9fcb-d46acb875671">
d6-865f509a77c6">

**Comment by JagaranMaharjan** [comment]
@saghul we fixed it. Thank you

**Comment by saghul** [comment]
How did you solve it?
