### ISSUE TITLE
React Native SDK Imports

### ISSUE THREAD

**Issue by UsamaAbdulAziz** [jitsi/jitsi-meet#13473]
### Description:

I was checking out the jitsi-meet repository and I found that react-native sdk has been added. So I followed the readme and performed following steps:
1) Packed the react-native sdk. 
2) Installed this sdk into my react native project. 
3) Pod install on iOS project. 
4) Added Sounds copy script in iOS projects. 

After above steps I was able to run the project on iOS device. 

Now I have tried a lot of ways to use the newly added library in the react-native project but I am unable to import anything from the installed npm package.
Is there a way to import this new package into the project (like where I can add meeting options, url, observe conference events etc.).

Thanks in advance.

### Steps to reproduce:

1. Install react native sdk. 
2. Pods install. 
3. Try to import the Jitsi package into the project. 

### Expected behavior:

There should be a way to import the package in react native project where one can add meeting options, url, observe conference events etc.

### Actual behavior:

There is nothing to import from the react native sdk. 

### Server information:

- Jitsi Meet version: 2.0.8719
- Operating System: Linux (Docker)

### Client information:

- Browser / app version: 2.0.8719
- Operating System: iOS

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by UsamaAbdulAziz** [comment]
> @UsamaAbdulAziz  you should try "react-native-jitsi-meet" ,its Jitsi Meet SDK wrapper for React Native. follow https://github.com/skrafft/react-native-jitsi-meet

I tried integrating it in a project built with latest react-native and I couldn't make it run. May be I need to downgrade react-native in the application in order for this wrapper to work. For me, that is not possible since it will have breaking effects.

**Comment by saghul** [comment]
> @UsamaAbdulAziz  you should try "react-native-jitsi-meet" ,its Jitsi Meet SDK wrapper for React Native. follow https://github.com/skrafft/react-native-jitsi-meet

No, this is bad advice. The reason why we are getting out our own RN SDK is because wrapping our native SDK for RN is the wrong thing to do.

**Comment by GleidsonDaniel** [comment]
it won't work because the main is pointing to an index.js that doesn't exist (just look at the package.json), the main is the JitsiComponent that is in the components folder.
However, even if you renamed it to index.js it would not work because there are still some imports that are not done correctly and libs that are outside the dependency of the lib.

**Comment by Jiayuwalker** [comment]
May I know the plan or schedule of RN sdk? desperately need it!

**Comment by saghul** [comment]
Getting closer! @Calinteodor can give more details, we hope to make a first release soon.

**Comment by Calinteodor** [comment]
We are finishing up some updates and we will send today the release for review.

**Comment by skrafft** [comment]
> > @UsamaAbdulAziz  you should try "react-native-jitsi-meet" ,its Jitsi Meet SDK wrapper for React Native. follow https://github.com/skrafft/react-native-jitsi-meet
> 
> No, this is bad advice. The reason why we are getting out our own RN SDK is because wrapping our native SDK for RN is the wrong thing to do.

@saghul I've added a deprecation message stating that users should use the official sdk

**Comment by saghul** [comment]
> > > @UsamaAbdulAziz  you should try "react-native-jitsi-meet" ,its Jitsi Meet SDK wrapper for React Native. follow https://github.com/skrafft/react-native-jitsi-meet
> > 
> > 
> > No, this is bad advice. The reason why we are getting out our own RN SDK is because wrapping our native SDK for RN is the wrong thing to do.
> 
> @saghul I've added a deprecation message stating that users should use the official sdk

Thank you very much! The popularity of your package was one of the reasons that finally made us get our act together and do an official RN SDK.

**Comment by skrafft** [comment]
The RN SDK works very well, I'm glad you could provide an official one. Thanks for the awesome work to all the jitsi team.
