### ISSUE TITLE
Re-request: Deleting individual chat messages

### ISSUE THREAD

**Issue by queerterpreter** [jitsi/jitsi-meet#13486]
I'd like to bring back old feature request #8087 (labeled wontfix in 2021)

**Is your feature request related to a problem you are facing?**
Sorta? I just accidentally copypasted the wrong text into the chat. I sent a very personal message I'd been drafting, and it was supremely embarrassing. Thankfully only 3 people were in the meeting, but that's 3 too many people who now may have read that text. Yes, I could have double-checked, but we were trying to have a quick meeting. The ability to delete the message right away would have spared me a terrible interaction.

**Describe the solution you'd like**
An option to delete messages sent in the chat, ideally upon clicking on the specific message for intuitive design purposes

**Describe alternatives you've considered**
Screaming "NO DON'T READ THAT i'm sorry i copied the wrong thing but that's very personal, please don't read it" and wishing lightning would strike me dead

**Comment by rasos** [comment]
Not only myself, but also moderators should be able to delete chat messages. This should be at least a config option. Use case is having a video watch party with lots of viewers, and we seldomly have participants that simply require moderation, which would be more polite than kicking the user out (which does not remove his/her chat message in the timeline).
