### ISSUE TITLE
iOS: every time you turn on the camera it goes into live mode

### ISSUE THREAD

**Issue by GleidsonDaniel** [jitsi/jitsi-meet#13484]
### Description:
Given that the sdk for react native is outdated and does not work with the new versions of RN we are using view webview, on android it works normally, however on iOS when activating the camera it goes into "live" mode (I don't know if this is the correct word), being necessary to click on the x to exit this screen/modal.

### Steps to reproduce:
Video below with the error occurring:
https://github.com/jitsi/jitsi-meet/assets/18687097/b651b234-9e85-4e55-8de2-c995456533fa

**Comment by saghul** [comment]
What iOS version is that? Can you reproduce it in a real device and not a simulator?

**Comment by GleidsonDaniel** [comment]
> What iOS version is that? Can you reproduce it in a real device and not a simulator?
Yes, on physical devices the error is the same.
Here is a recording of my device:
https://streamable.com/xro0n8

**Comment by saghul** [comment]
Is that meet.jit.si or a different deployment? I am unable to reproduce it with an iPhone 12 running the same iOS version. Very weird!

**Comment by GleidsonDaniel** [comment]
Yes, it's very strange, the strangest thing is that this only happens on ios, on android it works normally using a webview.
I made a repo and an expo snack showing the error. (using meet.jitsi as server for the call)
repo: https://github.com/GleidsonDaniel/jitsi-test
expo snack: https://snack.expo.dev/@kbca/jitsi-test?platform=ios

**Comment by saghul** [comment]
Oh so this is on a WebView, I tried to repro on the native browser.

There must be a way to turn that off from the WebView I'd hope.

**Comment by GleidsonDaniel** [comment]
> Oh so this is on a WebView, I tried to repro on the native browser.
> 
> There must be a way to turn that off from the WebView I'd hope.

I looked for some settings that could disable this behavior but I couldn't.

I even used this url generator and I couldn't find a config to disable it.
https://shawnchin.github.io/jitsi-url-generator/

**Comment by saghul** [comment]
I don't think it's something we can disable from the Jitsi side, but rather on the WebView props side.

**Comment by GleidsonDaniel** [comment]
> I don't think it's something we can disable from the Jitsi side, but rather on the WebView props side.

Got it!
Do you have any idea what can be done?

**Comment by ankar84** [comment]
Confirm that issue on iOS 16.5.1
Android using WebView works perfectly. But iOS have that live layer bug enabling camera.

**Comment by GleidsonDaniel** [comment]
> Did you set the allowsInlineMediaPlayback option on the WebView?

Yes, but seeing your message I had an idea and I solved it here.

https://media4.giphy.com/media/T9JtEyoJ43gY4wLOqW/200w.gif?cid=6c09b952bzfbt4uhobzjv20jmgo7pgqprlurl7gwgl42wu88&ep=v1_gifs_search&rid=200w.gif&ct=g

**Comment by sagarsq** [comment]
hey can you post the solution?
