### ISSUE TITLE
Add an option to disable virtual backgrounds

### ISSUE THREAD

**Issue by javierckr** [jitsi/jitsi-meet#13495]
**Is your feature request related to a problem you are facing?**
Virtual background is running with low fps on low end computers and there is no option to disable this feature in the config file.

**Describe the solution you'd like**
An option in the config file "disableVirtualBackground=false", that allows disabling this feature for everyone.

**Describe alternatives you've considered**
Hiding this feature with a custom css, but will be easier to maintain an option in the config file.

**Comment by saghul** [comment]
Makes sense! Would you like to send a PR?
