### ISSUE TITLE
Whiteboard Layout

### ISSUE THREAD

**Issue by maymage** [jitsi/jitsi-meet#13490]
Hi all, 

below you can see Jitsi Meet on Firefox with the Whiteboard active

![grafik](https://github.com/jitsi/jitsi-meet/assets/36572014/7b06f93b-c4d8-4158-bd32-f6ae0e4c5a5e)

I believe, this layout is suboptimal, because the whiteboard space, especially the vertical hight, is quite restricted - at least on a smaller screen.  Perhaps

```
+------------------------------------------------------------------+
|[Save]       [Shapes][Eraser|Back|Forth]         |  +---------+   |
|                                                 |  |    ME   |   |
+---+                                             |  +=========+   |
| + |            Whiteboard Area                  |  | Viewer1 |   |
| % |                                             |  +=========+   |    
| - |                                      ( > )  |  | Viewer2 |   |
+---+                                             |       *        |
|                                                 |       *        |
|               (Selfhiding Toolbar)              |       *        |	
+------------------------------------------------------------------+
```

where the `(>)` collapses the preview list of participants

**Comment by saghul** [comment]
There are limitations due to how the whiteboard is integrated, that's why it doesn't go below the toolbar. Otherwise we wouldn't know when to show it as we can't track it properly.

**Comment by mihhu** [comment]
> where the (>) collapses the preview list of participants

The list of participants is already collapsible, allowing the whiteboard to spread horizontally.

**Comment by fatemehmarzoughi** [comment]
@mihhu  Are you asking for the same arrow which is on the right side for the bottom toolbox?

**Comment by mihhu** [comment]
> @mihhu Are you asking for the same arrow which is on the right side, for the bottom toolbox (while the whiteboard is visible)?

I'm saying the arrow to hide the filmstrip is already there.
<img width="497" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/20574669/30844b34-90e1-4e15-b196-72dd2de01648">

**Comment by fatemehmarzoughi** [comment]
> > @mihhu Are you asking for the same arrow which is on the right side, for the bottom toolbox (while the whiteboard is visible)?
> 
> I'm saying the arrow to hide the filmstrip is already there. <img alt="image" width="497" src="https://user-images.githubusercontent.com/20574669/252299734-30844b34-90e1-4e15-b196-72dd2de01648.png">

So please close the issue if it has been solved :)

**Comment by maymage** [comment]
@saghul  Why did you close? This issue is not about the arrow to collapse the sidebar at all, but the suboptimal layout of the whiteboard as is. 

Look at the "is" versus "could be" :  different heights, distribution of buttons etc.

**Comment by saghul** [comment]
Ah gotcha. We are working on a toolbar refactor that may allow us to gain more space on the top at least.

**Comment by maymage** [comment]
.

**Comment by fatemehmarzoughi** [comment]
> @saghul Why did you close? This issue is not about the arrow to collapse the sidebar at all, but the suboptimal layout of the whiteboard as is.
> 
> Look at the "is" versus "could be" : different heights, distribution of buttons etc.

Would you please explain the issue more clearly for me, Maybe I can work on it.
