### ISSUE TITLE
Ongoing Notification Does Not End & App Crash

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13491]
**Branch:** mobile-23.1

**Issues:** After integrating custom jitsi meet sdk, app crash frequently even if our app is not running on background. Additionally, the ongoing notification does not end once the meeting is ended by host.
 
**Steps to replicate:**
1. Start meeting
2. Put your app on background
3. End Meeting By Host or Disconnect Your Internet & End Meeting By Host
4. Try to remove your ongoing notification
![353074959_954000705817801_9018525017208375438_n](https://github.com/jitsi/jitsi-meet/assets/60642304/3f38c2d3-7b2c-4e58-9098-f0f0115f1b50)

**Comment by saghul** [comment]
> After integrating custom jitsi meet sdk, app crash frequently even if our app is not running on background.

Can you please share a crash trace?



> Additionally, the ongoing notification does not end once the meeting is ended by host.

Are you using the "end meeting for all" functionality?

**Comment by JagaranMaharjan** [comment]
@saghul yes we are using end meeting for all functionality
