### ISSUE TITLE
Defining tile view as default in android

### ISSUE THREAD

**Issue by lrh378728213** [jitsi/jitsi-meet#13493]
Defining tile view as default view in android, I suggest that can do it by meet SDK.

**Comment by saghul** [comment]
You want tile view also for 1-1 calls?

**Comment by lrh378728213** [comment]
> > pc web video display in android was incomplete
> 
> What does this mean?

The video on pc is horizontal screen, and only the middle part can be displayed on Android.

**Comment by saghul** [comment]
Can you share a screenshot? For desktop content we letterbox the video and you can pinch-to-zoom and pan to focus on the specific are of the desktop that you care about.

**Comment by lrh378728213** [comment]
> Can you share a screenshot? For desktop content we letterbox the video and you can pinch-to-zoom and pan to focus on the specific are of the desktop that you care about.

pc 
![1687786823380](https://github.com/jitsi/jitsi-meet/assets/62747206/2da4f941-1fab-4396-a949-240fd4c24bf7)

andorid
![微信图片_20230626213802](https://github.com/jitsi/jitsi-meet/assets/62747206/511ddfe0-b9c6-4ca1-9182-78c6f93f9304)

**Comment by saghul** [comment]
Ah, I see what you mean. It's not the screen but the video. We use object-fit "cover" on both, but there is usually less space on mobile.

We currently have no config or flag for this beahvior. If you'd like to add a "always tile view" mode I think a PR would be acceptable.
