### ISSUE TITLE
Audio playing in Bluetooth headset, and speakers simultaneously 

### ISSUE THREAD

**Issue by goddoll** [jitsi/jitsi-meet#13509]
### Description:

The android app fresh installed on Motorola One 5g Ace. It will play through the speaker on any option. Selecting handset will play through phone handset, and speakers. Selecting Bluetooth will play through Bluetooth headset, and speakers. Selecting speakers will play through only speakers. 

### Steps to reproduce:

1. Download app
2. Wear Bluetooth headset
3. Open meeting

### Expected behavior:

It should play through the selected device, and mute the other devices. 

### Actual behavior:

Speakers play through everything! 
Can't screenshot sounds, but imagine a meeting where your voice is obstructed by someone mimicking you with a tenth of a second delay. 

### Server information:

- Jitsi Meet version: 23.2.0 build 14412073
- Operating System: Android 11

### Client information:

- Browser / app version: unknown
- Operating System: unknown

### Additional information:

I signed up for beta, and updated the app. The bug persisted. The headphones I'm using are Soundbot sb220, though it probably doesn't make a difference since the bug is repeatable just using the handset.

**Comment by saghul** [comment]
That's a first! Any chance you could grab the `adb logcat` output?

**Comment by goddoll** [comment]
So, it's not the app, it's my phone... It makes no sense, but it's doing it everywhere now. So.. I just hope I don't need to reboot to fix it.
Also, I am very green at this site. I would have replied sooner if there were some notification of your reply. I regret my overall ignorance in this matter, and hope to rectify the user error post haste.

**Comment by saghul** [comment]
No worries. Hopefully you can find a fix for your device!
