### ISSUE TITLE
WebRTC.xcframework not created in "out" directory inside "ios: directory

### ISSUE THREAD

**Issue by Mahesh160393** [jitsi/jitsi-meet#13505]
Hello @saghul 

After executing following command not able to generate WebRTC.xcframework but JitsiMeetSDK.xcframework is generated 

```
mkdir -p ios/sdk/out
xcodebuild clean \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphonesimulator \
    -destination='generic/platform=iOS Simulator' \
    -archivePath ios/sdk/out/ios-simulator \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphoneos \
    -destination='generic/platform=iOS' \
    -archivePath ios/sdk/out/ios-device \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
    -framework ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -framework ios/sdk/out/ios-simulator.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -output ios/sdk/out/JitsiMeetSDK.xcframework
```

Because of this used WebRTC.xcframework from "node_modules/react-native-webrtc/apple" 

Now meeting only connecting continuously.

**Comment by saghul** [comment]
The WebRTC framework comes from the JitsiWebRTC CocoaPod, it's no longer in node_modules.

**Comment by Mahesh160393** [comment]
@saghul then how to download bitcode. Right now ./node_modules/react-native-webrtc/tools/downloadBitcode.sh this is not valid path. Need to enable the bitcode

**Comment by saghul** [comment]
Bitcode was deprecated by Apple and we sropped support for it.

**Comment by Mahesh160393** [comment]
I need bitcode enable for 'JitsiWebRTC', '~> 111.0.0. Is there any way to execute this command? 

`./node_modules/react-native-webrtc/tools/downloadBitcode.sh`

**Comment by saghul** [comment]
It's not possible to build 111 with bitcode because support for it was dropped from webrtc as Apple removed it in Xcode 14 as well.

**Comment by Mahesh160393** [comment]
ok thank you. When i'm using react-native-webrtc -> 1.94.1 and generate the sdk with above command then call not getting connected continue showing connecting to meeting screen. No error is log. 

Here is details 

Jitsi-meet repo -> 2.0.6826
Cocoapods --> cocoapods-1.12.1
Node -> v16.16.0
NPM -> 8.11.0

**Comment by saghul** [comment]
Sorry that's a very old release we now longer support.

I'm afraid your only choice is to upgrade and drop bitcode support.

**Comment by Mahesh160393** [comment]
ok thank you for response @saghul
