### ISSUE TITLE
Bug/Feature - Disable Jitsi Hotkeys while in Whiteboard

### ISSUE THREAD

**Issue by Bloodiko** [jitsi/jitsi-meet#13510]
### Description:

We are using the Whiteboard feature quite often. 
While using the Whiteboard, we do like to keep a base drawing inside our session, keeping an extra tab for excalidraw is not practical. 
Thus we usually tend to copy and paste the drawing, which will provide the drawing "JSON" formatted into the clipboard. 
Downloading a Picture is not our usecase here. 

Using Hotkeys to Copy, will always trigger Jitsi's own hotkeys, despite a modifier key being pressed as well. 
Like CTRL + A will open Performance Options,
CTRL + C will open Chat,
CTRL + V will enable or disable camera feed. (which is really annoying since you dont notice it first hand.)

While i could disbable Jitsi Hotkeys in the Settings, i dont want to, because those are quite practical. 
But i think, while the focus is inside the Whiteboard - OR when any modifying key is pressed, the Key should not run the KeyEvent Function but break after a guarding check. 

### Steps to reproduce:

(Just for clarity - i'm using the newest Chrome version at the time of writing, and we are on a self hosted server, so It might not be a valid submit, as it might have been fixed already, but i didnt find any corresponding Issues or Commits.) 
1. Open Whiteboard
2. Draw anything
3. Mark the Drawing with ctrl+a (Performance option should pop up)
4. try to copy with ctrl c (you now should have JSON Code of the drawing inside your clipboard)
5. try to paste again with ctrl v 

### Expected behavior:

Whiteboard does Copy and Paste correctly.
Jitsi does not catch the presses while focused on the Whiteboard or Ignores the pressen when using modifier keys. 

### Actual behavior:

The Hotkeys are opening their functions even when a modifier key like Shitft, Alt, Win or ctrl. 

### Server information:

- Jitsi Meet version: (Unknown due to having an self hosted instance not managed by me) should be the current public beta version
- Operating System: Running in Kubernetes (i guess)

### Client information:

- Browser / app version: Chrome  114.0.5735.199
- Operating System: Windows 

### Additional information:

This can be either a bug report or a feature request, so do with it as you please.
I just wanted to bring this up. 

We are using the Copy feature to save our whiteboard and restore it the next day. It would be cool if we could automate this somehow (maybe using api ? ), but crawling through a minified firebase app code is not fun (yes i tried) - or having it built-in to restore the whiteboard automatically on next join the next day. 

Thanks, 
Bloodiko

**Comment by saghul** [comment]
IMHO taking modifier keys into account makes sense here. @mihhu can you PTAL ans see if that would work?

**Comment by Bloodiko** [comment]
It would also be possible to detect the context, html makes this quite easy with the event propagation system. 

If the event is inside the canvas, drop it,m for everything outside the canvas, and don't propagate further
Typing inside the whiteboard actually does it already, not Really sure how the context allowes this within a canvas without having an html element inside the canvas, but it works.
