### ISSUE TITLE
More Actions visible while not needed

### ISSUE THREAD

**Issue by Flying-Light** [jitsi/jitsi-meet#13515]
### Description:

If I selected few buttons for the Toolbar, which expected to be visible, it appears only inside the "More Actions"
![image](https://github.com/jitsi/jitsi-meet/assets/46743639/6443a523-778c-4007-a1f0-d5e7b2cb09a7)

It seems that some buttons designed to be listed in the "More Actions" list, even if the toolbar is not full.

**Comment by saghul** [comment]
@robertpin can you PTAL as part of the work on the toolbar?

**Comment by neshvig10** [comment]
I would like to work on this issue , can you please elaborate it

**Comment by saghul** [comment]
@robertpin is working on some toolbopx refactoring right now, this fits that scope, sorry!

**Comment by saghul** [comment]
@robertpin This is fixed now, isn't it?

**Comment by robertpin** [comment]
> @robertpin This is fixed now, isn't it?

Not yet
