### ISSUE TITLE
Border gets cut off around PiP window on Android

### ISSUE THREAD

**Issue by saibotma** [jitsi/jitsi-meet#13514]
### Description:

The borders of the PiP window on Android are cut off because of the rounded edges on e.g. Pixel 7.

### Steps to reproduce:

1. Download the JitsiMeet app
2. Start a new meeting
3. Enter PiP mode

### Expected behavior:

The borders should not get cut off at the edges. Are the borders even necessary?

### Actual behavior:

The borders get cut off at the edges.
![photo_2023-07-01 12 48 41](https://github.com/jitsi/jitsi-meet/assets/26022902/35b494ba-cee4-457f-b22c-40a3d34a5df5)

### Client information:

- App version: 23.1.2 build 13680351
- Operating System: Android 13

**Comment by saghul** [comment]
IIrC we have no control over that, the system does it. Do you observe the same behavior from other apps when going PiP?

**Comment by saibotma** [comment]
No, I don't observe the same behaviour. Telegram for example does not draw any border around the PiP window.

**Comment by saghul** [comment]
Thanks for the report!
