### ISSUE TITLE
Video stream stops working when the video call `iframe` shrinks

### ISSUE THREAD

**Issue by LSViana** [jitsi/jitsi-meet#13524]
### Description:

When the `iframe` that hosts the video call shrinks, the video stream does not show anymore.

### Steps to reproduce:

1. Create and start a video call via Jitsi Meet
2. Shrink the `iframe` of the video call and notice the video stream stopping

### Expected behavior:

The video stream shouldn't stop working when the `iframe` of the video call is resized.

### Actual behavior:

The video stream stops working when the `iframe` of the video call is resized.

### Server information:

- Jitsi Meet version: (not sure)
- Operating System: (not sure)

### Client information:

- Browser / app version: Google Chrome 114
- Operating System: Windows 11 and macOS 13.4.1

### Additional information:

For more context, I'm creating an application that uses [JaaS from 8x8](https://jaas.8x8.vc/) and the video call is part of the experience of the application. As the flow of the application happens, the video call changes place on the screen and also size.

When the video call becomes smaller, the video stream of the other person (it's always 1-on-1 so far) doesn't show up anymore.

This is how the video call starts, it's on the right half of the screen:
<img width="923" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/21217790/5c11837a-ec9d-4fb4-84de-cd25d203b863">

And this is what it looks like after its size is reduced (please, ignore the overlay):
<img width="851" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/21217790/2a5a293f-562a-495d-87eb-9949dda59155">

(Notice how the video stream is still there, it's just "blurred". It looks like a visual bug because the video stream is still running.)

The current workaround that I applied is to enable and disable the tile view very quickly. This works all times but if there's another way to force a "layout" operation on the video call `iframe` this could solve the issue.

I noticed that, through the DevTools, when I toggled the visibility of the `.videocontainer` element sometimes it'd recover the video (probably because the layout process is forced that way). However, I can't do that programmatically since this is all happening inside the video call `iframe`.

Lastly, I noticed that this issue happens more frequently on slower machines. On more powerful machines, I could reproduce this with better consistence by enabling the "CPU slowdown" through the Chrome DevTools in the "Performance" tab.

**Comment by LSViana** [comment]
If this is not the best place to post this issue, please let me know. I believe that since JaaS by 8x8 builds on top of Jitsi Meet, I could report the bug here and, in the meantime, find some useful information to get rid of that workaround. 🙂

If more information is needed, please let me know.

**Comment by saghul** [comment]
Thanks for the detailed report! Some questions:

- Does the same happen if you resize a browser window instead?
- What size triggers the problem? Or is it not a exact number?

**Comment by LSViana** [comment]
Hi, @saghul!

> Does the same happen if you resize a browser window instead?

No, it doesn't. When my application changes the size of the `iframe`, it's actually changing the dimensions in a single frame.

An additional detail is that the `iframe` is I'm moving the location of a Web Component slot. This is meant to prevent the `iframe` from reloading and disconnecting the call, which would happen if I manually changed its parent element.

---

> What size triggers the problem? Or is it not a exact number?

It's not an exact number. It happens after this single-frame resize.

This video demonstrates the problem from the user's point of view (I blurred some elements of the UI so you can focus on the video):

https://github.com/jitsi/jitsi-meet/assets/21217790/9ccc67a2-64a9-4ae5-9d6e-7e50edd37a11

Notice how the video stream keeps showing at first but suddenly disappears. Then, it shows the brand color that's configured as background in the JaaS portal.

**Comment by LSViana** [comment]
Not stale, still actual.

**Comment by saghul** [comment]
Since you are using JaaS, can you please open a support ticket. Link this issue for context.
