### ISSUE TITLE
API Password

### ISSUE THREAD

**Issue by AndyNormore** [jitsi/jitsi-meet#1354]
I need the ability to use:

`var password = "example";`

to specify a room password. How can this be done?

**Comment by saghul** [comment]
Hi Andy,

Can you please elaborate? To set a password when creating a room? To request it when joining a room? Both? Are you using the iframe API?

**Comment by AndyNormore** [comment]
Hi Saghul.

So my application at www.SkyRooms.io (incase you want to look) has users log in. From this MySQL Database driven platform, they create rooms. In the database is where they set passwords, and if the room is audio + video, or just audio for example.

When they click join, I'm calling a Jitsi window like this:

`<script src="https://jitsi.skyrooms.io/external_api.js"></script>
<script>
var domain = "jitsi.skyrooms.io";
var room = "andy";
var width = "100%";
var height = 800;
var api = new JitsiMeetExternalAPI(domain, room, width, height);
</script>`

So how can I set a password? Also, how can I set a moderator here?

**Comment by saghul** [comment]
Hi @AndyNormore,

I'm afraid none of those are currently supported by the current external API. We are working on making a better external API, I'll keep those in mind.

Cheers,

**Comment by AndyNormore** [comment]
Hi Saghul, if you wouldn't mind coming to www.SkyRooms.IO and clicking the DEMO room, where you can see how we're making use of Jitsi. I feel like this will open your eyes to the kinds of needs we have! :)

**Comment by saghul** [comment]
I did :-)

I'd like to understand your use case better. Why do you need a password? You can just create uniquely named rooms instead of creating a password. Since rooms are volatile, when everyone leaves it, the name can be used again, without any password anyway.

If you have user profiles you can use the external API to set the user avatar and display name, thus making a more personalized experience, without the complications of having the users authenticate, since they are already authenticated in your system anyway...

**Comment by AndyNormore** [comment]
Okay, so what we're attempting at SkyRooms is 'persistent rooms'. I work for a University, and we have students bookmark URLs often times. 

But, those users must be authenticated through an account, so that's why I'm calling Jitsi via an API. This way, I can authenticate a user in my platform and redirect if they're not logged in.

If they are logged in, I can then call up the Iframe Jitsi API, and have them join the room based on the URL.

So here's the demo URL: https://www.skyrooms.io/meet/AndrewNormore2981/demo

This room is open to the public for example.

But this url: https://www.skyrooms.io/meet/AndrewNormore2981/private-room

would NOT be open to the public, requires a user account, and that user account must be in a certain group.

All this is controlled by my database, and only calls the API if the conditions are correct. Now of course, there are some security issues regarding sniffing html source and grabbing passwords, but for now, it's fine.

So I'd like an API to do things like:

- if email="andrewnormore@gmail.com" then Jitsi.Api.SetModerator = true
- if user != logged in then Jitsi.Api.DisableWebcam = true

By having this kind of API, it really opens your platform up to a variety of uses. Would you like to Jitsi Meet and discuss in person? ;)

**Comment by zalmoxisus** [comment]
The best way to achieve this is via a prosody plugin. Similarly to [this plugin](https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_allowners.lua), you return "outcast" if the user shouldn't have access to the room. Also, you can return affiliations depending on the user's group: "owner", "admin", "member". I didn't try that though.
