### ISSUE TITLE
High CPU usage if camera on. Low if camera off

### ISSUE THREAD

**Issue by mankoff** [jitsi/jitsi-meet#13544]
This bug has been addressed several times, most recently on jitsi/jitsi-meet-electron#77.

However, that bug seems to be focused on OS X and importantly says,

    if I turn my camera off altogether, the CPU usage does not go down

I'm opening a new bug because I'm on Linux and CPU drops as soon as I turn off my camera.

I've turned `performance` to one-above-lowest (where lowest turns off the camera) and am using a URL with:  `MyMeetingRoom#config.disableAudioLevels=true&config.channelLastN=3&config.startSilent=false` and in the GUI set `Disable automatic gain control`.

I much prefer Jitsi to other tools and would be happy to help debug this if you can provide any suggestions.

## Description

After about 1-5 minutes of running Jitsi (Firefox or Electron app installed via Flathub), all 8 cores on my laptop peg to 100 % and the system becomes unusable. Audio and video drop. Mouse becomes laggy. If I turn off my camera (in Jitsi) CPUs immediately drop. This is therefore due to outbound video, not inbound.

## Possible Solution

Audio only.

# Environment details

```bash
$ flatpak list|grep jitsi
Jitsi Meet      org.jitsi.jitsi-meet    2023.5.3        stable  user
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

```
$ uname -a
Linux t480 5.15.0-72-generic jitsi/jitsi-meet-electron#79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by saghul** [comment]
Done!

**Comment by mankoff** [comment]
It appears this bug is primarily triggered by `self view`. Without that, I have run into all 8 cores at 100 %, but it is rare. With `self view` it is consistent but takes ~5 minutes.

**Comment by saghul** [comment]
The self view is just another video tile that needs to be rendered.

I think you are on the edge of what your hardware can handle, and one more video is enough to push it over the edge.

**Comment by maymage** [comment]
@mankoff  can you tell us, what kind of jitsi meeting we're talking about? How many participants?

@saghul 

> I think you are on the edge of what your hardware can handle, and one more video is enough to push it over the edge.

In view of the intel core i7, 8 core, 32gb ram machine of @mankoff , which from my perspective sounds like a pretty decent one, and in view of him stating "I've turned performance to one-above-lowest", would you tell us roughly,  what  cpu/gpu specifications, how many cores and how much ram you'd expect to be sufficient for a smooth experience on a low performance level? I'm thinking about getting a new machine..

**Comment by saghul** [comment]
There are too many variables to give a good estimate. Note this was on Linux, and video card drivers also play a part.

**Comment by mankoff** [comment]
@maymage sorry for the late reply, perhaps influenced by @saghul suggesting this machine is just not powerful enough.

The meetings I'm talking about are 1 other participant, just me +1. 

I agree with your comment - this is a fine machine, and should not peg all 8 cores at 100 % in this use case. No other video software (Teams, Meet, Zoom) take any noticable CPU.
