### ISSUE TITLE
android browser imposes to use android app, but fails to use it

### ISSUE THREAD

**Issue by pciavald** [jitsi/jitsi-meet#1356]
Hello, 
I was using this version of jitsi-meet from the official apt repos : 
```
Version: 1.0.1622-1
Depends: jitsi-videobridge (= 879-1), jicofo (= 1.0-320-1), jitsi-meet-web (= 1.0.1592-1), jitsi-meet-web-config (= 1.0.1592-1), jitsi-meet-prosody (= 1.0.1592-1)
```
Then I had to modify the home page, realized I had to clone `jitsi-meet` instead to be able to recompile it. I found the `/react/features/welcome/components` folder where it happens, and recompiled.
Then I tried on my phone where I discovered the new feature that if you connect from an android phone it redirects you to the appstore. It's a great feature as such, but I have 2 problems with it :
- Probably because I modified the home page, even though I do have the jitsi app on my phone, the `start a conference` button does nothing. Which makes jitsi totally unusable on smartphone while it used to work without the app.
- The biggest problem : we are setting up a solution to be used by professionals of sensitive information. They are provided by their companies with smartphones that don't allow installing third party apps, which is why we chose Jitsi. Now that Jitsi requires a third party app, it is not an option for us anymore.

Is there any way to disable this feature in the config files, or manually as a temporary hack ?
Rolling back to version 1592 while i can't disable the enforced android app.

Thank you

**Comment by pciavald** [comment]
just tried to rollback to 29001c3 and then 9f332ff : both previous versions include the enforcement. I just tried without any modification on the files, and I can't `start a conference`, so this seems to be a proper bug

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems before opening issues. 

There are reasons we are forwarding from web to the app all the clients, like user experience, mobile UI and some features like mobility will be available only for the mobile app.
Not sure why 'start a conference' doesn't forward you to the app, does it happen when using meet.jit.si?
You can always build the app yourself and make it not third party but internal.

**Comment by pciavald** [comment]
Sorry I forgot about the mailing list, too used to working with github...
Yes, it happens also when using meet.jit.si : the `start a conference button` does not respond, Otherwise  and I double checked the app's installation is correct and it works flawlessly standalone. 
I understand you have reasons to support a mobile app, but i think it should be a choice in the config files. We love your tool and want to promote it, but even packaging the app ourselves doesn't solve the problem that our clients can't install apps. We are not our client's smartphones' providers.
Any hack I can do while i find something suitable ?

**Comment by pciavald** [comment]
for instance would you know which commit should I rollback to or which line should I comment ?

**Comment by damencho** [comment]
In chrome you can always click request desktop site, and it will work without any modifications. Is this ok?

**Comment by pciavald** [comment]
Why is it restricted to chrome ? our users have branded browsers, not vanilla chrome or firefox. Seems to be a good option though, even though i have to understand how it can integrate with our login portal

**Comment by pciavald** [comment]
Ah ok got it it's actually a functionality of the browser. Not sure the users have access to this setting though. I still think it should be a setting in the config, but i'll work with it for now.

**Comment by pciavald** [comment]
So I checked with the clients and it's not an option to go to the browser's settings and enable the "desktop version" option. So I've changed this line [here](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/util/interceptComponent.js#L39) from 
```
if (OS === 'android' || OS === 'ios')
```
to
```
if (false && OS === 'android' || OS === 'ios')
```
and it seems to work. From commit 88eabf23f I see it is still in reflexion though, and it is said that there is a switch somewhere to properly dismiss the app promo, but I can't find it. Can you help ?

**Comment by buddhikajay** [comment]
You can set `MOBILE_APP_PROMO: false` in `interface_config.js` usually in `/usr/share/jitsi-meet/` to disable app promo.
