### ISSUE TITLE
Android Error on upgrading sdk from 8.1.2 to 8.2.0

### ISSUE THREAD

**Issue by nitinbehal1212** [jitsi/jitsi-meet#13566]
We have upgraded sdk from 8.1.2 to 8.2.0 , But getting below error on line JitsiMeetActivity.launch(activity, options)

The Error is mentioned below:-

Cannot access 'com.facebook.react.modules.core.PermissionAwareActivity' which is a supertype of 'org.jitsi.meet.sdk.JitsiMeetActivity'. Check your module classpath for missing or conflicting dependencies

**Comment by saghul** [comment]
Are you using ProGuard?

**Comment by nitinbehal1212** [comment]
No I am not using Proguard. I just upgrade the SDK and start facing this issue.

**Comment by saghul** [comment]
Does your project use React Native in any capacity?

**Comment by nitinbehal1212** [comment]
No, our project is not using React Native. But we have integrated the sdk 8.1.2 and It was working perfectly fine. Now, after upgrading to 8.2.0 we are facing this issue.

**Comment by saghul** [comment]
Any chance you can create a simple project which exhibits the issue?

**Comment by nitinbehal1212** [comment]
For your reference, I have created a simple hello world project and added Jitsi sdk 8.1.2 to launch the JitsiMeetActivity. And it’s working fine.

But when I upgraded the version to 8.2.0, I faced the same issue mentioned above.

I have also attached the simple project code zip.
[Simple Project with SDK 8.1.2.zip](https://github.com/jitsi/jitsi-meet/files/12053596/Simple.Project.with.SDK.8.1.2.zip)
[Simple Project with SDK 8.2.0.zip](https://github.com/jitsi/jitsi-meet/files/12053601/Simple.Project.with.SDK.8.2.0.zip)

**Comment by saghul** [comment]
I'll take a look, thanks!

**Comment by zarini** [comment]
SAME HERE, We have upgraded sdk from 8.1.2 to 8.2.0 then got this error.

**Comment by gauravdua27** [comment]
I had a similar experience. We recently upgraded our SDK from version 8.1.2 to 8.2.0, but unfortunately, it resulted in getting the same error as mentioned.

**Comment by nitinbehal1212** [comment]
> I'll take a look, thanks!

Hey @saghul ,  any updates on my reported issue?

**Comment by saghul** [comment]
It's Sunday, so no.

**Comment by saghul** [comment]
8.2.2 is out with a fix for this. Thanks for your patience!
