### ISSUE TITLE
Provide APK under Releases on Github

### ISSUE THREAD

**Issue by m0byn** [jitsi/jitsi-meet#13561]
**Is your feature request related to a problem you are facing?**
Unfortunately, I cannot download the apk file of the android app. Under releases I can only find the source code, but no apk files are provided.

**Describe the solution you'd like**
I use the application obtainium in order to update the apps on my android device directly through Github. So, it would be nice if you could provide apk files in order to use it with obtainum as well.

**Comment by saghul** [comment]
We already distribute the app via Google Play an f-droid.

You can grab the f-droid APK directly from here: https://f-droid.org/packages/org.jitsi.meet/

These are the only distribution mechanisms we currently support and we don't have plans to expand the list.

GH releases are not too great for projects which release several packages off the same repository, at different cadences. For historical reasons web releases are made into GH releases, whereas mobile releases are tagged and have their release notes and changelog live elsewhere.
