### ISSUE TITLE
Can't scroll in the participants menu

### ISSUE THREAD

**Issue by enoch85** [jitsi/jitsi-meet#13578]
## Actual result
When you have a meeting with 5 participants or more, the breakout room "tab" gets hidden, and the only way to show the breakout rooms are to click the `^` to the left of the participants list to hide the list.

## Expected behavior
It should be able to scroll through all participants down to the breakout rooms, it's the most natural behavior.

## Device information
* Brand: `OnePlus`
* Device: `OP516FL1`
* Model: `NE2213`
* Id: `SKQ1.221119.001`
* Product: `NE2213EEA`

## App version
23.2.0 build 14279208

**Comment by saghul** [comment]
Ping @Calinteodor can you pl add this to your list?

**Comment by enoch85** [comment]
It's not stale.

**Comment by saghul** [comment]
This is now fixed!
