### ISSUE TITLE
IntelXDK Embedded Jitsi Not Displaying

### ISSUE THREAD

**Issue by AndyNormore** [jitsi/jitsi-meet#1357]
Hello Jitsi,

I'm trying to build a mobile and desktop app using IntelXDK. I understand it's not a native app for Jitsi.

I instead want to have Jitsi load in using the JavaScript API, but it never works.

Uncaught ReferenceError: JitsiMeetJS is not defined

The same meeting room works perfectly well from a browser. I'm not sure if this question is better here, or with IntelXDK community. Is there some trick? Perhaps it's the native browser on Android doesn't support WebRTC and simply fails? I'd like to hear the thoughts. My goal is to have the web version working in a mobile app. Not perfect, but it's early days still.

**Comment by saghul** [comment]
I'm not familiar with Intel XDK, but I assume it's a framework that enables you to build hybrid apps. In that case you need WebRTC support, which I'm not sure if it's included.

This is out of the scope of Jitsi Meet really. Whatever the environment, be that React Native, Cordova or whatever, WebRTC is needed for Jitsi Meet to work, and some tweaking might be necessary to have Meet believe it's running in a browser.
