### ISSUE TITLE
Bolutooth headset keep connect in android 

### ISSUE THREAD

**Issue by SaeedNoshadi89** [jitsi/jitsi-meet#13589]
Bolutooth is not disconnected When Im connecting on a meet with bolutooth headset, and leave the meeting.

How can I fix this?

**Comment by saghul** [comment]
What exactly is not disconnected?

**Comment by SaeedNoshadi89** [comment]
> What exactly is not disconnected?

When I use wireless headphones and live is interrupted, the headphone connection is not disconnected and I can no longer use the headphones for calls or... I have to disconnect the Bluetooth connection and connect it again

**Comment by SaeedNoshadi89** [comment]
> Are you leaving the meeting normally?

Yes, i use this code: 

`private fun stopLiveStream() {
        val muteBroadcastIntent = Intent("org.jitsi.meet.STOP_RECORDING")
        muteBroadcastIntent.putExtra("mode", "stream")
        LocalBroadcastManager.getInstance(applicationContext).sendBroadcast(muteBroadcastIntent)
    }
    
      @ReactMethod
    private fun exitLive() {
        stopLiveStream()
        jitsiMeetView!!.leave()
        LocalBroadcastManager.getInstance(this).unregisterReceiver(broadcastReceiver)
        JitsiMeetActivityDelegate.onHostDestroy(this)
    }
    
     binding.txtExit.setOnClickListener {
            exitLive()
        }
    `
    
    If i remove stopLiveStream(), It's not working yet

**Comment by saghul** [comment]
How are you integrating the SDK? What package are you using?
