### ISSUE TITLE
Can't build Jitsi meet

### ISSUE THREAD

**Issue by Mohamed5550** [jitsi/jitsi-meet#13595]
### Description:

The `make` command always fails with this log

```
NODE_OPTIONS=--max-old-space-size=8192 \
./node_modules/.bin/webpack
[BABEL] Note: The code generator has deoptimised the styling of /srv/jitsi-meet/node_modules/@vladmandic/human/dist/human.esm.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /srv/jitsi-meet/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /srv/jitsi-meet/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /srv/jitsi-meet/node_modules/@jitsi/excalidraw/dist/excalidraw.production.min.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /srv/jitsi-meet/node_modules/zxcvbn/lib/frequency_lists.js as it exceeds the max of 500KB.
make: *** [Makefile:30: compile] Killed
```

### Steps to reproduce:

I've followed the instructions here 
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual

```
cd /srv
git clone https://github.com/jitsi/jitsi-meet.git
cd jitsi-meet
npm install
make
```

### Server information:

- Operating System: Ubuntu 22.04.2
- npm version: 8.11.0
- node version: v17.9.1
- RAM: 8GB

**Comment by saghul** [comment]
> * RAM: 8GB

I'm afraid this won't be enough.

**Comment by Mohamed5550** [comment]
Thanks for your reply

this is a test environment
I have another server with 12GB RAM, will it be enought?

BTW In the documentation it is said 4GB will work for small meetings. I don't understand the conflict here
![image](https://github.com/jitsi/jitsi-meet/assets/25209735/fc510507-dafa-4621-b5a6-fe1806ef90e7)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
