### ISSUE TITLE
The user's avatar is not displayed in the list of participants in the breakout room

### ISSUE THREAD

**Issue by SkyTaurus** [jitsi/jitsi-meet#13594]
Both users have uploaded avatars set

Steps:

1 user1 create a conference
 connect
2. user2 connect to the conference
3.  user1 create a session room
Connect to it
4 user2 open the list of participants
Check the display of the user's avatar1 in the session room

**Expected Result:**

Member avatar is displayed

**Actual result:**

When going to the breakout Room, participants in the main room are shown a blank with a letter instead of an avatar

**Comment by saghul** [comment]
THis is a known limitation.

**Comment by SkyTaurus** [comment]
Are there any plans to fix it?

**Comment by saghul** [comment]
Not at the moment, but PRs are welcome.
