### ISSUE TITLE
g is cropped in the username

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#13606]
![image](https://github.com/jitsi/jitsi-meet/assets/14617699/6f15972a-3107-4bf5-b4c4-77130ad450d1)

### Client information:
- Browser / app version: 23.1.2 from f-droid
- Operating System: Android

**Comment by saghul** [comment]
The text doesn't seem to be vertically aligned properly.

Are you using the default system font size?

@Calinteodor pl take a look at this as time allows.

**Comment by 532910** [comment]
I have changed screen resolution (1080 -> 1440) and increased font size. And increased font size and DPI to compensate resolution setting. So it looks like it was by default.

**Comment by Calinteodor** [comment]
Thank you for the info @532910! Fix has been merged! It will be available soon!
