### ISSUE TITLE
"The room name is unsafe" alert regardless of URL path (ex: https://meet.jit.si/{my_custom_hash}/{meeting_name})

### ISSUE THREAD

**Issue by candideu** [jitsi/jitsi-meet#13603]
**Is your feature request related to a problem you are facing?**
Jitsi Meet allows you to add a custom path to your URL, such as: https://meet.jit.si/{custom-path}/{meeting-name}, and the meeting name will only include the last part of the URL / page name (see https://github.com/jitsi/jitsi-meet/issues/5407#issuecomment-1522595249). Doing so allows you to have a "common" room name under a more secure URL.

However, Jitsi will put a "The room name is unsafe" alert if the meeting name (last part of the URL) is determined to be too easy to guess -- even though another person wouldn't be able to access the meeting. So https://meet.jit.si/b06be4f9-6b1c-4874-a6a0-4fd59ad77b16/My-meeting and https://meet.jit.si/My-meeting are treated the same, even though they're not the same meeting room.

![image](https://github.com/jitsi/jitsi-meet/assets/55474996/b16f8028-a2fb-4c0b-a45e-fa399549b4db)

**Describe the solution you'd like**
I would like the insecure meeting name checker (created in response to https://github.com/jitsi/jitsi-meet/issues/5407) to also check the path/directory of the meeting room.

**Describe alternatives you've considered**
I've considered adding extra digits to the end of the URL, but those digits get added to the meeting room name, which is an undesirable effect.

**Comment by c-prompt** [comment]
As mentioned multiple other places (that seem to keep getting closed/stale/ignored - e.g., [6754](https://github.com/jitsi/jitsi-meet/pull/6754#issuecomment-632894449), #6801,  [5407](https://github.com/jitsi/jitsi-meet/issues/5407#issuecomment-634718078), for those of us who have closed environments, a warning the room name is unsafe only scares users and discourages use. Some of us who also use JWT and set the room name programmatically haven't any need for this warning.

Just so the use case is clear: a user on a mobile browser clicks  a link to "Join in app" (the link being in the format of intent://meet.my_secure_server.org/test123/jwt=some_token_characters#jitsi_meet_external_api_id=0&userInfo.displayName=%22my_secure_username%22&appData.localStorageContent=null#Intent;scheme=org.jitsi.meet;package=org.jitsi.meet;end) and the mobile app (e.g., Android v 23.2.0 build 14279208) opens with a scary message and big yellow scary icon that makes them think they just clicked on a fishing link. Doesn't give the user a whole lot of confidence participating in the meeting.

Thus, continuing to request a configurable option (perhaps as part of the intent link?) to suppress the big, yellow, scary message.

**Comment by saghul** [comment]
That has been possible for a flong time. Add `enableInsecureRoomNameWarning: false,` to your cnfig.js and you'll never see that warning again.

OP's issue is an interesting corner case when tenants are used.

**Comment by c-prompt** [comment]
> That has been possible for a flong time. Add `enableInsecureRoomNameWarning: false,` to your cnfig.js and you'll never see that warning again.
> 
> OP's issue is an interesting corner case when tenants are used.

But this doesn't prevent the mobile app (e.g., Android Jitsi-Meet) showing the warning, correct? Again, just so we're clear: the user is in Chrome and clicks on the "Join in app" link which opens the Jitsi-Meet mobile app - the scary message shows in the Jitsi-Meet mobile app (not in Chrome).

**Comment by saghul** [comment]
Correct, at the moment the check only looks for the feature flag, but checking for the config should be easily doable: https://github.com/jitsi/jitsi-meet/commit/63761d515a9e1900cda4c00fdd51fea7c13164e4#diff-45843e5b142323ecab2f9390b8db8c0e4cb7c85f7b2cae668c78aae698c705e4R182

**Comment by c-prompt** [comment]
> Correct, at the moment the check only looks for the feature flag, but checking for the config should be easily doable: [63761d5#diff-45843e5b142323ecab2f9390b8db8c0e4cb7c85f7b2cae668c78aae698c705e4R182](https://github.com/jitsi/jitsi-meet/commit/63761d515a9e1900cda4c00fdd51fea7c13164e4#diff-45843e5b142323ecab2f9390b8db8c0e4cb7c85f7b2cae668c78aae698c705e4R182)

I can't think of any use case when it would matter where the check is (e.g., the mobile app checking the server config or the mobile app checking the intent URL sent from the browser), just as long as it can prevent the mobile app from showing the scary message. The mobile app is a better user experience than the mobile browser so anything that encourages its use is preferable. Thanks.

**Comment by saghul** [comment]
> > Correct, at the moment the check only looks for the feature flag, but checking for the config should be easily doable: [63761d5#diff-45843e5b142323ecab2f9390b8db8c0e4cb7c85f7b2cae668c78aae698c705e4R182](https://github.com/jitsi/jitsi-meet/commit/63761d515a9e1900cda4c00fdd51fea7c13164e4#diff-45843e5b142323ecab2f9390b8db8c0e4cb7c85f7b2cae668c78aae698c705e4R182)
> 
> I can't think of any use case when it would matter where the check is (e.g., the mobile app checking the server config or the mobile app checking the intent URL sent from the browser), just as long as it can prevent the mobile app from showing the scary message. The mobile app is a better user experience than the mobile browser so anything that encourages its use is preferable. Thanks.

Fix here: https://github.com/jitsi/jitsi-meet/pull/13658

**Comment by candideu** [comment]
Commenting so this doesn't become stale

**Comment by c-prompt** [comment]
ping

**Comment by candideu** [comment]
> Makes sense that we check both the tenant / namespace and the meeting name. A PR would be most welcome!

Is there any way to reopen the issue? This is still a bug, unfortunately 😔
