### ISSUE TITLE
In Android, there is no local video flip option that is there on the Web.

### ISSUE THREAD

**Issue by nitinbehal1212** [jitsi/jitsi-meet#13601]
In Android, we wanted to record the meeting with an Android phone screen recorder but that video is recorded in reverse and the content shown in the meeting is not readable due to this issue. 

The web has a flip option that enables us to record the meeting well.

Flip is very useful and necessary for the mobile also.

**Comment by nitinbehal1212** [comment]
@saghul ,  Is there any way we achieve Flip in Android? Any Suggestions from your side?

**Comment by saghul** [comment]
The feature doesn't exist, it needs to be implemented.

It shouldn't be very hard since we already have a menu for the local participant and the ability to "mirror" the local video.

It's more a matter of time and priorities.
