### ISSUE TITLE
react-dom could not be found within the project or in these directories (react-native-sdk)

### ISSUE THREAD

**Issue by KolissnikBogdan** [jitsi/jitsi-meet#13609]
Hello everyone) Currently I can't run the rn project after adding the @jitsi/react-native-sdk package.
I also tried to run the project located in this repository - https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/react-native, but I see the same error.

Here is the error description:
<img width="360" alt="Снимок экрана 2023-07-24 в 16 14 25" src="https://github.com/jitsi/jitsi-meet/assets/43568935/96e46789-11cf-4a1d-97c1-b5da99ac50ea">

### Steps to reproduce:

1.  Add @jitsi/react-native-sdk to the project
2.  Run the project using the information from README.md - https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/react-native/README.md (I tested it only on Android so far)

### Client information:

- Operating System: macos 12.5 (Monterey)

### Additional information:

For testing I use Samsung Galaxy A13 (android 13)

**Comment by saghul** [comment]
Can you run the sample project without changes?

**Comment by KolissnikBogdan** [comment]
I already tried running the sample project without making any changes

**Comment by saghul** [comment]
What problem do you run into with the sample project? It works ok here...

**Comment by KolissnikBogdan** [comment]
@saghul As I already wrote, after starting the project with the commands: `npm start & npm run android`, I get this error:
![image](https://github.com/jitsi/jitsi-meet/assets/43568935/73a7723b-3b64-468f-9c5f-b875f429d591)

`react-dom could not be found within the project or in these directories ...`

**Comment by saghul** [comment]
Sorry, I cannot reproduce the problem with the sample app. Neither on iOS nor Android.

<img width="2081" alt="Screen Shot 2023-07-24 at 22 34 01" src="https://github.com/jitsi/jitsi-meet/assets/317464/c36ed521-e433-471e-8087-0b7d387d8740">
<img width="2013" alt="Screen Shot 2023-07-24 at 22 23 42" src="https://github.com/jitsi/jitsi-meet/assets/317464/6cb42d84-de1a-421b-8932-673c2592c193">

**Comment by KolissnikBogdan** [comment]
@saghul Thanks for the answer. Can you tell me what versions of node and npm you are using?

**Comment by saghul** [comment]
Node 16 and npm 8.

**Comment by mubashiralisiddiqui** [comment]
i have the same issue 

  "@giphy/react-native-sdk": "2.3.0",
    "@jitsi/react-native-sdk": "^0.3.0",
    
 "react-native": "0.72.4",
 node v16.20.2.  npm 8.19.4

**Comment by saghul** [comment]
@Calinteodor can you pl take a look again?

**Comment by mubashiralisiddiqui** [comment]
I have also tried with node 18 and also try to run the sample project
https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/react-native
and getting the same error 


<img width="660" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/16689214/801f5f70-b7f0-4477-92e4-b4761658455a">
i am trying for a long time can someone please look into it

**Comment by KolissnikBogdan** [comment]
> i have the same issue
> 
> "@giphy/react-native-sdk": "2.3.0", "@jitsi/react-native-sdk": "^0.3.0",
> 
> "react-native": "0.72.4", node v16.20.2. npm 8.19.4

which package manager did you use? yarn or npm?

**Comment by KolissnikBogdan** [comment]
I had the same problem, just switch yarn to npm (node - v16.20.1 and npm - 8.19.4)

**Comment by KolissnikBogdan** [comment]
this problem is mostly related to yarn

**Comment by mubashiralisiddiqui** [comment]
> I had the same problem, just switch yarn to npm (node - v16.20.1 and npm - 8.19.4)

ok let me try

**Comment by KolissnikBogdan** [comment]
@mubashiralisiddiqui https://ncoughlin.com/posts/switching-yarn-npm/

**Comment by Calinteodor** [comment]
Did you run the script that updates your dependencies to match our peer dependencies?

**Comment by mubashiralisiddiqui** [comment]
> Did you run the script that updates your dependencies to match our peer dependencies? You can check the scripts object in the sample app package.json, update-deps.

I have uninstalled the Jitsi package 
Then I installed my other dependencies like gesture handler and etc
then when you i tried to install the package of @jitsi/react-native-sdk using npm 
it throws error 
<img width="609" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/16689214/8b22aa7d-dadc-4b8f-9ee9-0b95c861dab7">
you said to run the script which can be only run after installing the jitsi module
so how can we run the scripts?
and I am aware of running the scripts but as i said It will not work first i have to install jitsi which is not installing using npm

**Comment by Calinteodor** [comment]
Right, sorry for misguiding you. Try taking all the dependency updates step by step, please. Try downgrading your dependencies to match our module ones version. We are now finishing up updating all our native dependencies to the latest.

**Comment by mubashiralisiddiqui** [comment]
> Right, sorry for misguiding you. Try downgrading your dependencies to match our module one version. We are now finishing up updating all our native dependencies to the latest.

I am waiting for the updates as downgrading the version of dependencies causing issues with other libraries
This only happens with npm, with yarn Installing dependencies are fine so I suggest finding a way to get this work with yarn
thanks

**Comment by saghul** [comment]
Sorry we don't have the bandwidth to support yarn.

**Comment by mubashiralisiddiqui** [comment]
> Sorry we don't have the bandwidth to support yarn.

okay then make this compatible with library versions that are conflicting with npm

**Comment by mubashiralisiddiqui** [comment]
> > Sorry we don't have the bandwidth to support yarn.
> 
> okay then please make this compatible with library versions that conflict with npm

**Comment by saghul** [comment]
> > Sorry we don't have the bandwidth to support yarn.
> 
> 
> 
> okay then make this compatible with library versions that are conflicting with npm

That's what we are doing, as Calin mentioned.
