### ISSUE TITLE
Failed to load sound (react-native-sdk)

### ISSUE THREAD

**Issue by KolissnikBogdan** [jitsi/jitsi-meet#13616]
After joining the conference in the logs, there are many errors related to sound files:

<img width="975" alt="Снимок экрана 2023-07-25 в 16 55 59" src="https://github.com/jitsi/jitsi-meet/assets/43568935/27e625a7-c8f2-47fa-91df-995a54c473a8">

Maybe I missed something during the installation of the package?

The problem seems to be with this import (although I could be wrong):

<img width="516" alt="Снимок экрана 2023-07-25 в 16 59 51" src="https://github.com/jitsi/jitsi-meet/assets/43568935/3881d3b5-67f3-4964-addb-166c4d4699c8">

(.../react-native/node_modules/@jitsi/react-native-sdk/react/features/base/sounds/components/SoundCollection.ts)

### Client information:

- RN Jitsi: 0.2.1
- Operating System: Android 13

**Comment by KolissnikBogdan** [comment]
> Looks like the sound copy step didn't quite work...

I also noticed similar warnings, but they referred to different folders
for example:

<img width="477" alt="Снимок экрана 2023-07-25 в 17 35 40" src="https://github.com/jitsi/jitsi-meet/assets/43568935/5a3f6f9c-82c1-4be1-9811-1fcd566fb0a5">

**Comment by saghul** [comment]
Those are really the same, since no sound was apparently copied.

**Comment by JijoBose** [comment]
Still getting the same error even with the latest release [jitsi-meet_8916](https://github.com/jitsi/jitsi-meet/releases/tag/jitsi-meet_8916)

**Comment by JijoBose** [comment]
Hi,

I have implemented the React Native SDK in my App, and when the meeting loads, 
I get the "'Failed to load sound" error.
 

Error Log:

> 2023-08-25 19:04:15.059312+0530 SampleApp[84559:7769818] [javascript] '2023-08-25T13:34:15.057Z', '[features/base/media]', 'Failed to load sound', { code: 'ENSOSSTATUSERRORDOMAIN2003334207',
>   message: 'The operation couldn’t be completed. (OSStatus error 2003334207.)',
>   domain: 'NSOSStatusErrorDomain',
>   userInfo: {},
>   nativeStackIOS: 
>    [ '0   SampleApp                      0x0000000102e75c30 RCTJSErrorFromCodeMessageAndNSError + 112',
>      '1   SampleApp                      0x0000000102e75b70 RCTJSErrorFromNSError + 256',
>      '2   SampleApp                      0x0000000102d39d0b -[RNSound prepare:withKey:withOptions:withCallback:] + 1675',
>      '3   CoreFoundation                      0x000000010cae02fc __invoking___ + 140',
>      '4   CoreFoundation                      0x000000010cadd529 -[NSInvocation invoke] + 305',
>      '5   CoreFoundation                      0x000000010cadd7bc -[NSInvocation invokeWithTarget:] + 70',
>      '6   SampleApp                      0x0000000102e09b56 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2534',
>      '7   SampleApp                      0x0000000102e0dfea _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1402',
>      '8   SampleApp                      0x0000000102e0d89c _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 156',
>      '9   SampleApp                      0x0000000102e0d7f9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25',
>      '10  libdispatch.dylib                   0x0000000111909d18 _dispatch_call_block_and_release + 12',
>      '11  libdispatch.dylib                   0x000000011190af5b _dispatch_client_callout + 8',
>      '12  libdispatch.dylib                   0x0000000111912d41 _dispatch_lane_serial_drain + 1064',
>      '13  libdispatch.dylib                   0x0000000111913b1b _dispatch_lane_invoke + 441',
>      '14  libdispatch.dylib                   0x0000000111921f13 _dispatch_workloop_worker_thread + 959',
>      '15  libsystem_pthread.dylib             0x000000011277ac55 _pthread_wqthread + 327',
>      '16  libsystem_pthread.dylib             0x0000000112779bbf start_wqthread + 15' ] }




I generated the React Native SDK using the  
```node prepare_sdk.js```,  after making a few UI customisation changes to the Jitsi meet 

And referred the sample SDK repo to implement the RN SDK into my app

package.json

```
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "update-deps": "node node_modules/@jitsi/react-native-sdk/update_dependencies.js"
  },
```

**Comment by KolissnikBogdan** [comment]
@saghul any update?

**Comment by KolissnikBogdan** [comment]
@saghul 🙄

**Comment by Jiayuwalker** [comment]
I solved the problem by adding a "Run Script Phase" and naming it Copy Sounds (same as the sample react-native code). The script's content is as follows:

```
SOUNDS_DIR="${PROJECT_DIR}/../node_modules/@jitsi/react-native-sdk/sounds"
    cp $SOUNDS_DIR/* ${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/
```

**Comment by shahsawar344** [comment]
> I solved the problem by adding a "Run Script Phase" into project "Build Phases" and naming it Copy Sounds (same as the sample react-native code). The script's content is as follows:
> 
> ```
> SOUNDS_DIR="${PROJECT_DIR}/../node_modules/@jitsi/react-native-sdk/sounds"
>     cp $SOUNDS_DIR/* ${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/
> ```

@Jiayuwalker  just do like this 
<img width="666" alt="Screenshot 2023-12-22 at 7 50 24 AM" src="https://github.com/jitsi/jitsi-meet/assets/98263806/380b36ac-85c2-4ffd-8068-5a486c987c4e">
