### ISSUE TITLE
jitsi-meet-tokens: broken installation with secret containing forward slash character on debian

### ISSUE THREAD

**Issue by athoik** [jitsi/jitsi-meet#13610]
### Description:

Installing jitsi-meet-tokens on debian 12 will break if the secret contains forward slash character.

```
sed: -e expression #1, char 26: unknown option to `s'
```

That issue happens because the `APP_SERCRET` variable should be escaped before used by sed.

https://github.com/jitsi/jitsi-meet/blob/83196cda102db87d87afb2b244564b268d066d41/debian/jitsi-meet-tokens.postrm#L42

A possible solution is to escape the forward slashes.

```
             db_get jitsi-meet-tokens/appsecret
-            APP_SECRET=$RET
+	    APP_SECRET=$(echo "$RET" | sed 's/\//\\\//g')
```

### Steps to reproduce:

1.  apt-get install jitsi-meet-tokens
2.  set a secret that contains a forward slash
3.  installation will fail with sed error
4.  uninstall fails with sed error

### Expected behavior:

Installing jitsi-meet-tokens should allow secrets with a forward slash character.

### Actual behavior:

There is a problem installing jitsi-meet-tokens and uninstall fails as well, resulting in a broken installation.

### Server information:

- Jitsi Meet version: 1.0.1072-1
- Operating System: Debian 12

### Additional information:

In case you find your self in broken installation due to secret containing forward slash, you can the following commands to replace the password in debian configuration.

```
# display the values used by debconf

$ debconf-show  jitsi-meet-tokens
* jitsi-meet-tokens/appsecret: (password omitted)
  jitsi-meet-prosody/prosody_config: /etc/prosody/conf.avail/meet.example.com.cfg.lua
* jitsi-meet-tokens/appid: meet-example-com

# display the problematic password

$ echo "get jitsi-meet-tokens/appsecret" | debconf-communicate

# set a new password without a forward slash

$ echo "set jitsi-meet-tokens/appsecret this-is-a-very-secure-secret-not" | debconf-communicate

# install / uninstall now will work
```

Thank you Jitsi Team 🥇 💯

**Comment by damencho** [comment]
Filtering characters is not a solution, as you will end up configured with different secret. 
Maybe validating input and not allowing problem characters is better.

**Comment by damencho** [comment]
Any PRs are welcome.

**Comment by damencho** [comment]
Addressed in https://github.com/jitsi/jitsi-meet/commit/85fb7513dbd881065fa586a40a6dbac5620c70c3
