### ISSUE TITLE
[Conf Call]-  label issues related to the videoconferencing

### ISSUE THREAD

**Issue by marwenmoalla** [jitsi/jitsi-meet#13619]
### Description:

 label issues related to the videoconferencing with French language 

### Steps to reproduce:

1. Join any VideoConference
2. Go to Chat & Sondages
3. Go to Sondages

### Expected behavior:

Créer un sondage

### Actual behavior:

"Créer Un Sondage" is with capital letters

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- iOS SDK 8.1.2:
- Operating System: iOS

Similar issue found on Participants Screen.
"Couper Le Micro De Tout Le Monde" should be "Couper le micro de tout le monde" without capital letters

**Comment by MeghanaNalla** [comment]
@marwenmoalla The sentences are already without capitals. Here are some screenshots of the same:

![jitsi french](https://github.com/jitsi/jitsi-meet/assets/123588774/5ba1140b-0529-4718-8235-22acb204b5af)
![jitsi](https://github.com/jitsi/jitsi-meet/assets/123588774/a22aa103-abf5-43f8-aac0-ddc1b63b228f)
