### ISSUE TITLE
Custom Jitsi SDK: White box appear at top left

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13617]
**Customer Jitsi SDK Generated from branch: 23.1.0**

While joining the jitsi meeting,  on host shared screen it shows white box at top left

![123](https://github.com/jitsi/jitsi-meet/assets/60642304/b95c8818-025c-445b-8e43-0d5d1576fa0e)

**Comment by saghul** [comment]
Can you reproduce this with stock SDK 8.2.2?

**Comment by JagaranMaharjan** [comment]
@saghul using latest jitsi sdk?

**Comment by saghul** [comment]
Yes, 8.2.2. Test that one without any modifications please. Does it also happen?

**Comment by JagaranMaharjan** [comment]
@saghul its ok on 8.2.2

**Comment by saghul** [comment]
I don't know since I didn't make whatever changes you made.
