### ISSUE TITLE
RN SDK userInfo avatar, displayName, email

### ISSUE THREAD

**Issue by Larens94** [jitsi/jitsi-meet#13628]
Hi, I'm noticing that there are no attributes needed to set the **username, avatar and email.**

for example: 

```
 const options = {
        domain: config.stage.URL_MEET,
        onReadyToClose,
        roomName: `ExMeet_${stateJitsiMeet.meetRoomId}`,
        userInfo: {
            displayName: username,
            email: state.user?.email,
            avatar: avatarUrl,
        },
        settings: {
          startWithAudioMuted: stateVideoCall.audioMuted,
          startWithVideoMuted: stateVideoCall.videoMuted,
          startAudioOnly: false,
        },
      };
```
Are you planning to add this information?

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-react-native-sdk/

Sincerely

**Comment by danilvalov** [comment]
And you also need to update the typescript interface for `options` to support it

**Comment by Larens94** [comment]
I saw that you have to add on:
node_modules\@jitsi\react-native-sdk\index.tsx

on setAppProps:
```
  'flags': { ...flags },
   'userInfo': {
       email: 'testing@gmail.com',
       displayName: 'test'
   }
```

so it seems to work.


This is because the available props are:
```
/**
  * The type of React {@code Component} props of {@link App}.
  */
interface IProps extends AbstractAppProps {

     /**
      * An object with the feature flags.
      */
     flags: Object;

     /**
      * An object with user information (display name, email, avatar URL).
      */
     userInfo?: Object;
}
```
Sincerely

**Comment by Larens94** [comment]
Hi, I don't know if it can help you.

I added userInfo to set the avatar, name and email.

Sincerely


pull-request: https://github.com/jitsi/jitsi-meet/pull/13630
