### ISSUE TITLE
Screen share with chrome tab popup problem

### ISSUE THREAD

**Issue by cgri1** [jitsi/jitsi-meet#13624]
The participant starts screen sharing with the Chrome tab then the moderator stops everyone's video. The participant's screen stopped but the sharing popup was still visible.

### Steps to reproduce:

1. The moderator starts a meeting.
2. The participant joins a meeting.
3. The participant clicks the screen share button and chooses the Chrome tab.
4. The moderator stops everyone's video.
5. The participant's screen sharing stopped. But the 'Sharing' popup was still visible.

### Expected behavior:

The 'Sharing' popup was also must hidden.

### Actual behavior:

The participant's screen sharing stopped. But the 'Sharing' popup was still visible.

### Server information:

- Jitsi Meet version: Latest version
- Operating System: MacOs

### Client information:

- Browser / app version: Chrome
- Operating System:  MacOs

### Additional information:
<img width="1728" alt="Screen Shot 2023-07-27 at 08 26 05" src="https://github.com/jitsi/jitsi-meet/assets/39028198/72b1a5a9-e250-424c-b29a-72f9615613df">

**Comment by cgri1** [comment]
Is there any progress on this situation?

**Comment by saghul** [comment]
I'm not sure we can do much about it. The screen-share stopped but Chrome didn't vanish the indicator... we ha no control over it.
