### ISSUE TITLE
React-native-sdk: Typescript files are not transpiled to JS

### ISSUE THREAD

**Issue by rcidt** [jitsi/jitsi-meet#13629]
I am running the new React Native SDK and am seeing this error as soon as the app starts up:

```log
SyntaxError: /my/workspace/path/node_modules/@jitsi/react-native-sdk/react/features/toolbox/components/native/AudioMuteButton.tsx: Unexpected token (6:81)

  4 | import AbstractAudioMuteButton, { IProps, mapStateToProps } from '../AbstractAudioMuteButton';
  5 |
> 6 | export default translate(connect(mapStateToProps)(AbstractAudioMuteButton<IProps>));
```

To be more clear, it’s complaining about the Typescript syntax (AbstractAudioMuteButton\<IProps\>).

The SDK is written in Typescript, but none of it is transpiled to JS.

Is this intended?

**Comment by saghul** [comment]
It should be transpired automatically. What RN version are you using?

**Comment by rcidt** [comment]
@saghul I am using 0.66.3

**Comment by saghul** [comment]
That's too old of a version, it's now not even supported upstream.

**Comment by rcidt** [comment]
@saghul thanks. I will upgrade and test again
