### ISSUE TITLE
[react-native-sdk] Error when tapping on "Chat" button

### ISSUE THREAD

**Issue by rcidt** [jitsi/jitsi-meet#13638]
### Description:

```
Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'?

This can also happen if there are multiple copies of '@react-navigation' packages installed.
```

![image](https://github.com/jitsi/jitsi-meet/assets/37703740/09ec18ec-7c25-42b2-884e-99d97a01aa35)

### Steps to reproduce:

1. Join meeting
2. Tap on chat button on bottom tool bar

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- jitsi/react-native-sdk: 0.2.1
- react-native: 0.70.0

**Comment by rcidt** [comment]
I found a workaround:

I needed to ensure that the `@react-navigation` packages in my package.json were the same version as the ones found in `node_modules/@jitsi/react-native-sdk/package.json`.

I would have thought the `update_dependencies.js` script would have take care of it.

**Comment by saghul** [comment]
@Calinteodor we might need to tweak the script to at least print a warning if there are incompatible (different major number) dependencies...
