### ISSUE TITLE
Invite People Pop-Up displaying even if I prevent its execution

### ISSUE THREAD

**Issue by ahmedkhairydev** [jitsi/jitsi-meet#13647]
### Description:

I can't run my custom implementation of the invite because it's not working properly when I click on the  `Invite Someone` button on the `Participants` panel.

### Steps to reproduce:

1. prevent invite execution. `buttonsWithNotifyClick: [{ key: "invite", preventExecution: true, }]`
2. Click on `Participants` icon.
3. Click on `Invite Someone` button.

### Expected behavior:

invite event should be prevented.

### Actual behavior:

`Invite more people` pop-up displaying. 

### Server information:

- Jitsi Meet version: latest.
- Operating System: Linux.

### Additional information:
- actual behavior image:

![image](https://github.com/jitsi/jitsi-meet/assets/15922118/e4872fe1-efc2-44bf-88f9-b97031eda154)

**Comment by MeghanaNalla** [comment]
@ahmedkhairydev Can you be more sepcific about what you want your custom implementation of the invite to be?

**Comment by ahmedkhairydev** [comment]
@MeghanaNalla @saghul  @mihhu  My custom implementation is opening a dialog. So, The `toolbarButtonClicked` event should be fired.

**Comment by ahmedkhairydev** [comment]
@saghul any updates?

**Comment by mihhu** [comment]
I'll take a look

**Comment by mihhu** [comment]
I believe the config works as designed: it prevents the execution of the Invite People button that shows up in the overflow menu. The button in the screenshot is not part of the toolbar. @saghul wdyt?

**Comment by saghul** [comment]
Ah, that's a tricky one because it's not a toolbar button indeed. I do think it makes sense for it to be configurable, but let's discuss this with the team.

**Comment by mihhu** [comment]
@ahmedkhairydev we've discussed this matter with the team and we'll implement it. If you happen to encounter this particular discrepancy with other buttons, please let me know in this thread and we'll cover it 🙌

**Comment by ahmedkhairydev** [comment]
@mihhu Can you tell me when it deploying?

**Comment by saghul** [comment]
It usually takes up to a couple of weeks.

**Comment by ahmedkhairydev** [comment]
Okay, Can you let me know after the release?

**Comment by saghul** [comment]
I believe this is released already.
