### ISSUE TITLE
Default nginx config is wrong

### ISSUE THREAD

**Issue by enoch85** [jitsi/jitsi-meet#13644]
### Description:
After debugging why websockets doesn't work for a whole day, we finally found that adding an additional section in the default Nginx config did the trick.

**Default config:**
```
    # colibri (JVB) websockets for jvb1
    location ~ ^/colibri-ws/default-id/(.*) {
        proxy_pass http://jvb1/colibri-ws/default-id/$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        tcp_nodelay on;
    }
```

**What ended up using:**
```
    # colibri (JVB) websockets for jvb1
    location ~ ^/colibri-ws/default-id/(.*) {
        proxy_pass http://jvb1/colibri-ws/default-id/$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        tcp_nodelay on;
    }

    # colibri (JVB) websockets for additional JVBs
    location ~ ^/colibri-ws/([^/]+)/(.*) {
        proxy_pass http://jvb1/colibri-ws/$1/$2$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        tcp_nodelay on;
    }
```

As you can see, we added the second config, and not until then it started working. That's why I think the second config should be added as default. Or maybe improve the first one to catch all cases. Note; we only have *one* JVB here, and it's the internal one configured per default.

### Steps to reproduce:

1. Default install of Jitsi meet (Ubuntu 22.04)
2. Added our own turn server (which we use for other projects as well without any issues)
3. Start a meeting

### Expected behavior:

Websockets should work

### Actual behavior:

Websockets couldn't connect, no matter what we did. Even opened up `*` in the firewall. 

### Server information:

- Jitsi Meet version: https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_8719
- Operating System: Ubuntu 22.04

### Client information:

- Browser / app version: Firefox / Chrome / Brawe (latest as of today)
- Operating System: Ubuntu 22.04

### Additional information:
N/A

**Comment by saghul** [comment]
Sounds sensible to me. @damencho WDYT?

**Comment by damencho** [comment]
And what is the problem with the first rule? By default jvb is using the `default-id` as id. 
This enables any id to be used for jvb, other than default value ... when you start playing with that or adjusting it anyway you need modifications ... not a must have, as default works.

**Comment by enoch85** [comment]
OK, but could it least be added as commented out in the default config?

**Comment by damencho** [comment]
> location ~ ^/colibri-ws/default-id/(.*) {

That. matches the default config of jvb: https://github.com/jitsi/jitsi-videobridge/blob/1a8621977a7e7166b0a2ed717251d2d7d4b3e5fc/jvb/src/main/resources/reference.conf#L211

You have changed that, or? If you haven't touch that I don't see the difference between the two rules.

**Comment by enoch85** [comment]
> > location ~ ^/colibri-ws/default-id/(.*) {
> 
> That. matches the default config of jvb: https://github.com/jitsi/jitsi-videobridge/blob/1a8621977a7e7166b0a2ed717251d2d7d4b3e5fc/jvb/src/main/resources/reference.conf#L211
> 
> You have changed that, or? If you haven't touch that I don't see the difference between the two rules.

It was me and another guy that debugged this, the config I posted worked, then we stopped. I'm not 100% sure what changed or not. I only know that the suggested config works, and the old one didn't.

**Comment by damencho** [comment]
So probably you changed the default id of the bridge and that is the reason for it.
