### ISSUE TITLE
jitsi meet website is blank on iPhone

### ISSUE THREAD

**Issue by fulldecent** [jitsi/jitsi-meet#13646]
### Description:

Accessing the Jitsi Meet website produces a blank page on iPhone.

### Steps to reproduce:

1. Access meet.jit.si on a computer
2. Create a quick meeting code like a123 and join
3. Get an iPhone
4. Turn on lockdown mode on the iPhone (not sure if this step matters)
5. Access like meet.jit.si/a123 on the iPhone

### Expected behavior:

a) The meeting starts; or

b) You are directed to download an app to proceed; or

c) You are shown a message that iPhone is not supported

### Actual behavior:

The page loads but you see only black pixels.

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: dunno

### Client information:

- Browser / app version: 
- Operating System:

Computer / Edge / Current

iPhone / Safari / Current

**Comment by saghul** [comment]
WebRTC does not work in lockdown mode, so Jitsi Meet won't work.

We should have a better message about it thoguh.
