### ISSUE TITLE
Cannot read properties of null (reading 'offsetHeight')

### ISSUE THREAD

**Issue by oanguenot** [jitsi/jitsi-meet#13640]
### Description:

Migration from Jitsi-meet 2.0.8044-1 to Jitsi-meet 2.0.8719-1

### Steps to reproduce:

Open any Jitsi Meet URL (eg: https://meet-xxx.xxx/ProfoundSpotlightsPublishCautiously

### Expected behavior:

Jitsi-Meet page to be loaded successfully

### Actual behavior:

Crash

TypeError: Cannot read properties of null (reading 'offsetHeight')
    at MD (Filmstrip.js:18:43)
    at r6.getDimensions (SharedVideo.tsx:40:44)
    at r6.render (SharedVideo.tsx:76:99)
    at Is (react-dom.production.min.js:204:189)
    at As (react-dom.production.min.js:203:149)
    at xl (react-dom.production.min.js:292:172)
    at vc (react-dom.production.min.js:280:389)
    at bc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at lc (react-dom.production.min.js:273:245)
    at qa (react-dom.production.min.js:127:105)
    at nc (react-dom.production.min.js:266:390)
    at Object.enqueueSetState (react-dom.production.min.js:145:225)
    at b.setState (react.production.min.js:12:237)
    at BaseApp.tsx:208:18
    at new Promise (<anonymous>)
    at APP._navigate (BaseApp.tsx:207:16)
    at middleware.ts:125:48

### Server information:

jitsi-meet                      2.0.8719-1                              all          WebRTC JavaScript video conferences
jitsi-meet-prosody              1.0.7322-1                              all          Prosody configuration for Jitsi Meet
jitsi-meet-tokens               1.0.7322-1                              all          Prosody token authentication plugin for Jitsi Meet
jitsi-meet-turnserver           1.0.7322-1                              all          Configures coturn to be used with Jitsi Meet
jitsi-meet-web                  1.0.7322-1                              all          WebRTC JavaScript video conferences
jitsi-meet-web-config           1.0.7322-1                              all          Configuration for web serving of Jitsi Meet
jitsi-videobridge2              2.3-25-g1da507fa-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)
lua-basexx                      0.4.1-jitsi1                            all          baseXX encoding/decoding library for Lua
lua-cjson:amd64                 2.1.0.10-jitsi1                         amd64        JSON parser/encoder for Lua

- Operating System: MacOS 13.5

### Client information:

- Browser / app version: Version 115.0.5790.114 (Official Build) (arm64)
- Operating System: MacOS 13.5

### Additional information:

/usr/share/jitsi-meet/interface_config.js
VERTICAL_FILMSTRIP: false,

--> No crash when setting VERTICAL_FILMSTRIP: true

**Comment by oanguenot** [comment]
They were no issue with previous version used (Jitsi-meet 2.0.8044-1)

**Comment by saghul** [comment]
Fixed on https://github.com/jitsi/jitsi-meet/commit/5425b526154c5788a2170fcf90f8de8bcb4cab4c but it's not part of a stable release yet. Will be part of the next one.
