### ISSUE TITLE
jitsi-meet-web-config debian package is misguiding

### ISSUE THREAD

**Issue by Ppjet6** [jitsi/jitsi-meet#1364]
I already have jitsi-meet installed and configured, and when upgrading I get asked to choose between:
- "Self-signed certificate will be generated"
- "A certificate is available and the files are uploaded on the server"

I assume I have to choose the latter but I am not sure I understand the meaning of it. Would it be possible to clarify the sentence a bit?

**Comment by Ppjet6** [comment]
On 2017/03/01, Saúl Ibarra Corretgé wrote:
> When you installed it for the first time, did you specify your own cert files? Or did you let the installer create them for you?
> 
> If you already have Jitsi Meet configured in your server you must have the cert files available anyway, so you can just choose the second option and specify the path.

The first time I did that with in non-interactive mode (via Chef). I
wasn't expecting to be prompted really.

But what I'm asking really is can you clarify the sentence a bit? By
"files are uploaded on the server", do you mean to ask if certificates
are already in place?

-- 
Maxime Buquet

**Comment by damencho** [comment]
It asks: do you want to use your own certs, if choosing this option you
need your certs uploaded on the server, later in the process the
configuration will ask you for path of the cert files.

**Comment by saghul** [comment]
> On Mar 1, 2017, at 17:12, Maxime Buquet <notifications@github.com> wrote:
> 
> On 2017/03/01, Saúl Ibarra Corretgé wrote:
> > When you installed it for the first time, did you specify your own cert files? Or did you let the installer create them for you?
> > 
> > If you already have Jitsi Meet configured in your server you must have the cert files available anyway, so you can just choose the second option and specify the path.
> 
> The first time I did that with in non-interactive mode (via Chef). I
> wasn't expecting to be prompted really.
> 
> But what I'm asking really is can you clarify the sentence a bit? By
> "files are uploaded on the server", do you mean to ask if certificates
> are already in place?
> 

It means you need the file to be on the server’s filesystem somewhere. A prompt will ask you for the location and will make the appropriate configuration changes.

--
Saúl
