### ISSUE TITLE
JS Error:Rejecting session-initiate from non-focus user

### ISSUE THREAD

**Issue by Ppjet6** [jitsi/jitsi-meet#1366]
```
[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Rejecting session-initiate from non-focus user: foo@conference.example.com/focus
[JitsiConference.js] <o.onIncomingCall>:  Rejecting session-initiate from non-focus user: foo@conference.example.com/focus
```

I am using the package from the debian unstable repository, but I get the same error on stable.

Please ask if you need more information.

**Comment by saghul** [comment]
Did you do any custom changes to the installation? Are you using Nginx / Apache or the builtin server? What browser are you using?

I tried to reproduce it on a freshly installed VM with latest Jitsi Meet unstable, to no avail.

Can you provide full console logs? (use Gist or PasteBin please).

**Comment by Ppjet6** [comment]
My setup might not be your usual setup, but I don't know if it's related to this particular error.

`hostA` that has prosody (0.9.x) running `example.com` and `conference.example.com`, on Debian Jessie. `hostB` on Stretch with jitsi related stuff and another prosody (0.9.x) running `meet.example.com`. I also have `focus.meet.example.com` and `videobridge.meet.example.com` that points to hostB.

I have an nginx in front to serve meet (among others), and I emptied videobridge/sip-communicator.properties so jetty doesn't try to bind 443.

I created a local user for focus (focus@meet.example.com), and added it as admin on conference.example.com.

Here is the config for the whole thing: https://paste.bouah.net/L0z0VEp41-H/

Logs of jicofo: https://paste.bouah.net/QCGlrlexnvh
Logs of jvb: https://paste.bouah.net/1mdiIdplpOH

We both use Chromium version 56.0.2924.87 (64-bit) to test.

**Comment by saghul** [comment]
have you adjusted `/etc/jitsi/jicofo/config` to match the focus user you created? Look at `JICOFO_AUTH_DOMAIN`, `JICOFO_AUTH_USER` and `JICOFO_AUTH_PASSWORD` options.

**Comment by Ppjet6** [comment]
I created a user `focus@meet.example.com`, as specified in the config I linked. I can see it connect to the muc on conference.example.com. I didn't create it on example.com because we're using some fancy auth method I need to fix first, but it shouldn't be a problem right?

**Comment by Ppjet6** [comment]
I created a user `focus@meet.example.com`, as specified in the config I linked above. I can see it connect to the muc on conference.example.com. I didn't create it on example.com because we're using some fancy auth method I need to fix first, but it shouldn't be a problem right?

**Comment by saghul** [comment]
@damencho maybe you can help here?

**Comment by damencho** [comment]
I don't really get the configuration here, and something is messed up in the configuration I think.
The focus user needs to be admin for its domain: meet.example.com. And from the config it feels like the meet client is trying to connect to different server/domain ... so the meet client needs to connect to the same server where jicofo is connected, and the focus user needs to be admin in order to grand ownership to the first user that enters in a room and will send session initiate to the users connected to that room.
