### ISSUE TITLE
Less invasive insecure room name warning

### ISSUE THREAD

**Issue by MaxHillebrand** [jitsi/jitsi-meet#13666]
**Is your feature request related to a problem you are facing?**

When using insecure room names, there is a warning message that others might join the call, this now has to be clicked away every time, a frustrating time waster. 

**Describe the solution you'd like**

Do not require a user interaction, just make it a "silent" notification that disappears after some time.

Minimize the number of clicks until the call starts, anything more than 1 click is a bug.

**Comment by saghul** [comment]
We cannot do that, sorry. The user must know before joining.

If you have your own deployment you can disable that warning altogether in config.js. It's on and shall remain that way in meet.jit.si.

**Comment by MaxHillebrand** [comment]
> We cannot do that, sorry. The user must know before joining.

Notifying the user is one thing, but requiring his interaction is another. I would he happy with a non-interactive notification. 

Another option would be to require confirmation once for a given room, but not the subsequent time the same room is entered.

**Comment by saghul** [comment]
> Notifying the user is one thing, but requiring his interaction is another. I would he happy with a non-interactive notification.

As I said, a user action is necessary. People ignore notifications.



> Another option would be to require confirmation once for a given room, but not the subsequent time the same room is entered.

That's a slippery slope, people are forgetful.

Sorry, we have no intention to modify the current warning at this time.

**Comment by MaxHillebrand** [comment]
> Sorry, we have no intention to modify the current warning at this time.

I understand, thanks for the swift reply, keep up the good work! 🖤🚀
