### ISSUE TITLE
Option for "join in low bandwidth mode" by default

### ISSUE THREAD

**Issue by MaxHillebrand** [jitsi/jitsi-meet#13665]
**Is your feature request related to a problem you are facing?**

I always want to join in low bandwidth mode, but I have to click every time I join a call, that's a frustrating time waster. 

**Describe the solution you'd like**

Either:
1. Add a toggle to the settings that picks between low and high bandwidth as default for new calls
2. Remember the user choice of the previous call, and automagically use that again.

**Comment by Re-Dei** [comment]
I would like to work on this issue. Can I get assigned to it?

**Comment by saghul** [comment]
We don't assign issues in this project. In addition, we are not sure we will be adding this yet, it needs to be discussed first.

**Comment by izozo** [comment]
> We don't assign issues in this project. In addition, we are not sure we will be adding this yet, it needs to be discussed first.

hahah,if i can hide the "join in low bandwidth mode" button ?  if @jitsi/react-native-sdk": "0.3.0" has  provide an api to hide the button
