### ISSUE TITLE
[Android] Allow disabling of pop-up "You're now a moderator"

### ISSUE THREAD

**Issue by andreiciubancanWD** [jitsi/jitsi-meet#13662]
I would like to be able to disable the pop-up that appears once the client has entered the call stating **"You're now a moderator"**

Currently this is not possible via Android SDK feature flags.

<img width="387" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/55138713/be1b08ea-1d1e-4d4d-9f11-6d3aab1635ae">

**Comment by saghul** [comment]
You can disable it via config.js in your deployment.

**Comment by andreiciubancanWD** [comment]
Yes, it is disabled in config.js in the deployment

More details here:
https://community.jitsi.org/t/jitsi-android-disable-moderator-indicator/125029/6

**Comment by saghul** [comment]
It's the `notify.moderator` notification. Did you disable that?

**Comment by andreiciubancanWD** [comment]
This flag could only be set `notify.grantedTo` - the popup still appears
`notify.moderator` flag was not found.

**Comment by saghul** [comment]
We seem to have missed to document it, but it's cdertainly there: https://github.com/jitsi/jitsi-meet/blob/1066c65a6af40160ae76921157fae0564ad83c55/react/features/notifications/middleware.ts#L182

**Comment by benydc** [comment]
@saghul we added both:
```javascript
config.disabledNotifications = ['notify.grantedTo', 'notify.moderator']
```
and the popup still shows up

**Comment by benydc** [comment]
@saghul I see, is there documentation on this that mobile uses config.js instead of interface_config.js? We will try with this and see if it works, thank you!

**Comment by saghul** [comment]
No, sorry. The interface config has been deprecated and we are slowly moving everything to config.js.

**Comment by benydc** [comment]
@saghul it worked, thank you!

**Comment by saghul** [comment]
Glad to hear!
