### ISSUE TITLE
Zoom into screenshare

### ISSUE THREAD

**Issue by Bleuzen** [jitsi/jitsi-meet#13675]
**Is your feature request related to a problem you are facing?**

Yeah some people have ultrawide or huge screens with tiny elements on them. When watching a screenshare from such a screen, it can be really hard or impossible to read anything.

**Describe the solution you'd like**

Allow to zoom within a screenshare and move within this zoomed view

**Describe alternatives you've considered**

getting eye strain

**Comment by Bleuzen** [comment]
![kjsefniu4wbg8734](https://github.com/jitsi/jitsi-meet/assets/12885163/f2404fcd-c503-4c69-9e9a-f390b0f13ca5)
nice try

**Comment by Bleuzen** [comment]
> It will be closed

![image](https://github.com/jitsi/jitsi-meet/assets/12885163/86a18df1-332c-488e-accc-fca073068199)

**Comment by Bleuzen** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/12885163/02b7a879-fd01-4e7c-ab37-663c0018066b)
you don't just close this

**Comment by juanigaray** [comment]
This is one of the big reasons why I might prefer a different conferencing solution over Jitsi. Just had a call with a coworker and I couldn't see anything because his screen has a higher resolution than mine.

**Comment by Bleuzen** [comment]
.

**Comment by NadineKhis** [comment]
Why it's not planned anyway? To much work?

**Comment by johnathanz** [comment]
+1

would love to see this fixed. Screensharing across team is difficult as most members on the team have a different resolution monitor. Text from wide screens are the hardest to read, so zoom (e.g. using ctrl+mouse click) would be great, and put it on par with likes of MS Teams

**Comment by small1** [comment]
I just got this request right now. For some it can be solved by pinch on a touch screen but not on a normal screen without touch.

**Comment by lixiaotaowx** [comment]
I really need such a function. Can it be realized in the future? TX

**Comment by psy-q** [comment]
Can this be reopened? It's causing issues when conferencing between users with different screen resolutions as pointed out above. And it's also an accessibility issue.

What is the reason it isn't planned?

**Comment by saghul** [comment]
We simply don't have plans to add this feature, sorry.
