### ISSUE TITLE
label issues

### ISSUE THREAD

**Issue by HajerMehemdi** [jitsi/jitsi-meet#13671]
### Description:
with an Android device 
some labels are not translated 

1- Home page/waiting room:
The "Enable low bandwidth mode" label is not translated into French

In the FR label "Rejoindre La Réunion", La Réunion is written with capital letters. When "La Réunion" is written like this means the island.

2- Sondages/survey:
*U*n *S*ondage" is with capital letters

3-Mute the mic:

"Couper Le *M*icro *D*e *T*out Le *M*onde" is with capital letters

### Expected behavior:

1- Home page/waiting room:

The "Enable low bandwidth mode" should be translated into French.
"Rejoindre La Réunion" should be "Rejoindre la réunion" without capital letters. 
2- Sondages/survey:

"Créer Un Sondage" should be "Créer un sondage" without Capital letters

3- Mute the mic:

"Couper Le Micro De Tout Le Monde" should be "Couper le micro de tout le monde" without capital letters

### Server information:

- Jitsi Meet version: 6.0.0

### Client information:

- Browser / app version: Android device

**Comment by saghul** [comment]
We rely on the community for translations. If you'd like to help you can check the README in the lang/ directory.

**Comment by Rahil2507** [comment]
This issue has already been fixed, so it's requested to close this issue.

**Comment by mhamdihajer1** [comment]
Thank you i will check can you please the stable version conatain the fix

**Comment by HajerMehemdi** [comment]
HI EVEN WITH jitsiMeetSdk = "8.5.0" the translation not changed for android
