### ISSUE TITLE
If startAudioOnly is "true", be screen sharing is black

### ISSUE THREAD

**Issue by oktay454** [jitsi/jitsi-meet#13682]
### Description:

If startAudioOnly is "true", be screen sharing is black

### Steps to reproduce:

1. Set startAudioOnly value is true in `/etc/jitsi/meet/FQDN-config.js`
`sed -i 's~// startAudioOnly: .*~startAudioOnly: true,~g' /etc/jitsi/meet/FQDN-config.js`
2. Open private tabs(for bypassing cookies) and start a meeting.
3. Second step again other browsers (Have at least 3 participants in total).
4. Have a participant share their screen

### Expected behavior:

Showing shared screen at all participants

### Actual behavior:

Showing black screen at all participants.
But if participants open self camera, screen sharing is showing

### Server information:

- Jitsi Meet version: 2.0.8719-1
- Operating System: Debian 11

### Client information:

- Browser / app version: Firefox, Brave and Chrome etc.
- Operating System: Linux and Windows

**Comment by saghul** [comment]
This is a dublicate of https://github.com/jitsi/jitsi-meet/issues/13448 I think. It's fixed on master (and meet.jit.si) but it's not yet part of any stable release. It shall be part of the next one.

**Comment by oktay454** [comment]
I applied manual. But not work

**Comment by saghul** [comment]
There might be more commits.

Are you able to reproduce it on meet.jit.si using a config override? I wasn't.

**Comment by oktay454** [comment]
> There might be more commits.
> 
> Are you able to reproduce it on meet.jit.si using a config override? I wasn't.

Sorry my english not good.
I didn't understand what you mean.

**Comment by oktay454** [comment]
Should I replace the https://meet.jit.si/libs/app.bundle.min.js.map file with the one on my own server?

**Comment by oktay454** [comment]
I tried replacing the https://meet.jit.si/libs/app.bundle.min.js.map file with the one on my own server, but it didn't work.

**Comment by saghul** [comment]
You need to replace the JS file not the js.map file.

**Comment by oktay454** [comment]
> You need to replace the JS file not the js.map file.
I'm unfamiliar with web-side technologies. Sorry...

I replaced the app.bundle.min.js file on my own server with the one on the meet.jit.si server and it worked. Thanks a lot.
`wget https://meet.jit.si/libs/app.bundle.min.js -O /usr/share/jitsi-meet/libs/app.bundle.min.js`

**Comment by saghul** [comment]
Yes, it will be part of the next stable release.
