### ISSUE TITLE
Moment locale changed after joining conference

### ISSUE THREAD

**Issue by jplandry908** [jitsi/jitsi-meet#13688]
I recently implemented the new '@jitsi/react-native-sdk' module, first using v0.2.1 and now v0.3.0. The module seems to be working well; however, I discovered a strange issue with my 'moment' module changing locale after joining a video call and navigating back to the app.

Prior to launching a video call, all times within the app will show 'am/pm' since the locale is set to 'en'. However, after connecting to a video conference, the moment locale is changing to 'zh-tw' (showing Chinese characters and not 'am/pm').

As a workaround, I have implemented an 'onReadToClose' eventListener and manually forcing moment back to 'en'.

eventListeners={{
     onReadyToClose,
}}

const onReadyToClose = () => {
  console.log(moment.locale());  // <-- This is returning 'zh-tw' when closing the video conference.
  moment.locale('en');
};

Is there any way to prevent the locale from being changed when joining a video call?

**Comment by saghul** [comment]
What is your system locale?

**Comment by jplandry908** [comment]
All devices tested are US devices set to 'en'. Testing has been performed using both iOS and Android emulators. It was also deployed (v0.2.1) to others using TestFlight and they are receiving the same results (without the workaround).

**Comment by saghul** [comment]
Can you reproduce this with the sample app?

**Comment by jplandry908** [comment]
Yes. I can reproduce this on the sample app.

_On a side note, the 'react-dom' dependency is missing from the dependency file. I just downloaded a fresh copy of the sample app and it produced an error that 'react-dom' was not installed. Running 'npm install react-dom' resolved the issue._

To reproduce this within the sample app:
1. First install the 'moment' module (npm install moment)
2. Import moment at the top of 'Meeting.tsx'
import moment from 'moment';
3. Add a console log command in the 'onReadyToClose' event to print the changed locale when you exit the meeting
console.log("***********************", moment.locale());

In the sample app, it also prints 'zh-tw' only making the changes above.

Note: The locale is not changed until you actually join a meeting and then exit out of the meeting.

**Comment by jplandry908** [comment]
The 'react-dom' error is from a clean install using the sample app within react-native once the app is running. It points to the 'import ReactDom from 'react-dom';' (line 6) within the VideoContainer.js file. Once you install 'react-dom', it works fine.

![image](https://github.com/jitsi/jitsi-meet/assets/14008273/236aa056-b519-47ac-9f61-48f0105ef0f8)

**Comment by saghul** [comment]
That import shouldn't be there!

Can you trace which file is importing VideoContainer?

**Comment by jplandry908** [comment]
VideoContainer appears to be called within VideoLayout and LargeVideoManger. And the VideoLayout file appears to be called in a few modules\UI\* files as well as within a bunch of react\features\* files.

**Comment by yabelka** [comment]
> The 'react-dom' error is from a clean install using the sample app within react-native once the app is running. It points to the 'import ReactDom from 'react-dom';' (line 6) within the VideoContainer.js file. Once you install 'react-dom', it works fine.
> 
> ![image](https://user-images.githubusercontent.com/14008273/259851927-236aa056-b519-47ac-9f61-48f0105ef0f8.png)

I have the same problem 
 
![IMG_2563BECB23E5-1](https://github.com/jitsi/jitsi-meet/assets/64382508/5e60024b-4fba-4cfa-9aa2-ef67baefabe2)

**Comment by jplandry908** [comment]
@saghul - FYI - react-dom is no longer required in v0.4.1. However, the moment locale still changes to 'zh-tw' when returning from a conference. Just wanted to let you know about react-dom.

**Comment by jplandry908** [comment]
This issue has not been resolved

**Comment by jplandry908** [comment]
This appears to have been fixed in the latest release. I can no longer reproduce this issue.
