### ISSUE TITLE
Sound still coming through when muted but sharing screen

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#13697]
### Description:

When a user is muted, if they then share their screen with the tab audio button checked, the sound from the screen will come through despite the user still being muted.

It is then impossible for a mod to mute the user because they are shown to already be on mute in Jitsi.

### Expected behavior:

If muted, the user's screen sound shouldn't be coming through at all even if they shared screen with the tab audio button checked.

### Server information:

- Jitsi Meet version: Latest

**Comment by saghul** [comment]
Is this expected @andrei-gavrilescu ?

**Comment by andrei-gavrilescu** [comment]
Yes, this is the intended behavior, I don't recall the exact reasoning but It was discussed extensively and this was the consensus.
