### ISSUE TITLE
full-screen sharing disappears if the image doesn't change

### ISSUE THREAD

**Issue by jefry7** [jitsi/jitsi-meet#13698]
full-screen sharing disappears if the image doesn't change. If you move the mouse or something happens, the picture does not disappear. At the same time, the sound and chat do not disappear. Noticed during the slide show. But with an empty desktop, this is also observed. if you share a webcam, then the demonstration of the camera does not disappear

jitsi has not been updated for a long time, it previously worked. There is an updated to the latest version, the same thing. I can't figure out how to diagnose yet.

OS Client: Windows

**Comment by jefry7** [comment]
it's about self-server

**Comment by jefry7** [comment]
when it disappears, a message appears in the browser console:
2023-08-11T13:16:58.575Z [modules/UI/videolayout/LargeVideoManager.js] hover in 9ab74de4

**Comment by damencho** [comment]
You need to update to latest from unstable. This was addressed there and will be available in next stable release.

**Comment by jefry7** [comment]
what to update? some single component or all? jacopo, videobridge, Jitsi Meet files. Is there an instruction?

**Comment by jefry7** [comment]
jicofo/unstable 1.0-1044-1 all [может быть обновлён с: 1.0-1038-1]
jitsi-meet-prosody/unstable 1.0.7475-1 all [может быть обновлён с: 1.0.7322-1]
jitsi-meet-turnserver/unstable 1.0.7475-1 all [может быть обновлён с: 1.0.7322-1]
jitsi-meet-web-config/unstable 1.0.7475-1 all [может быть обновлён с: 1.0.7322-1]
jitsi-meet-web/unstable 1.0.7475-1 all [может быть обновлён с: 1.0.7322-1]
jitsi-meet/unstable 2.0.8891-1 all [может быть обновлён с: 2.0.8719-1]
jitsi-videobridge2/unstable 2.3-38-g1a862197-1 all [может быть обновлён с: 2.3-25-g1da507fa-1]

**Comment by jefry7** [comment]
updated, the problem is really gone. Thanks!
