### ISSUE TITLE
jitsi ldap auth design

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi-meet#13704]
If I currently read the ldap authentication manual[1], it looks like most of this is just handed over to saslauthd and not much can be filtered. I thought of changing this to using ldap/ldap2 auth directly in prosody. This would enable me to configure ldap settings directly in prosody's VirtualHost section. However I am then still stuck with that I would like to configure a 'static variable' in config.js and use that in the ldap filtering rules. 

Question is it possible to use a config.js variable in ldap connection. I have the impression from this ldap man page[3] that the %% means any token that is parsed. If this is indeed correct it should be possible to parse any value as a token. 

It would be nice if this type of customization is documented somewhere, someone else already requested this[2] quite a while ago. Afaik the software modules support this all, question is how to set and parse these tokens.

[1]
https://jitsi.github.io/handbook/docs/devops-guide/ldap-authentication/

[2]
https://projects.task.gda.pl/ansible-roles/jitsi/-/issues/10

[3]
https://github.com/cyrusimap/cyrus-sasl/blob/master/saslauthd/LDAP_SASLAUTHD

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

The ldap is server side, config.js is client side, so any ldap settings are to go in prosody.

In general, we plan to deprecate and remove username/password integration and leave only jwt. So the recommended way is to implement your ldap login integration the way you want and use jitsi-meet with the generated jwt tokens.

https://community.jitsi.org/t/intent-to-deprecate-and-remove-external-auth-mechanisms/115332

**Comment by f1-outsourcing** [comment]
@damencho  I am not getting the password resets from the forum.

**Comment by damencho** [comment]
Are you trying to login with github? Your account is associated with github login.
