### ISSUE TITLE
IOS Custom Jitsi SDK: Host Videos, Shared Screen Shown As Black Screen To End Users

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13703]
IOS Custom Jitsi SDK: Host Videos, Shared Screen Shown As Black Screen To End Users

**Generated SDK From Following Branch:**

**Branch: mobile-23.2 (on latest changes)**

Note 1: No any modification was done while generating custom jitsi sdk from branch mobile-23.2.
Note 2: Frequently message was shown as Video has been turned off by ..... to save bandwidth 

**Branch: mobile-23.1**
Note 1: Shared Screen  was Shown but while sharing host videos to end users, on end users screen message was shown as Video has been turned off by ..... to save bandwidth

**Comment by saghul** [comment]
Looks like there isn't enough bandwidth to sustain a video meeting, since you're getting the same error on both versions.

There are likely subtleties as to how long it may take for you to see it, but that doesn't change the underlying issue.

**Comment by JagaranMaharjan** [comment]
@saghul I tried from 4G/5G internet as well, it works well on official sdk but not on custom sdk. On generated custom sdk, i didn't made any modification but also it did not work why? (shown message as: Video has been turned off by ..... to save bandwidth)

**Comment by saghul** [comment]
The connection type is not as relevant as the amount of packet loss in it.

You can checkout the specific tag for a version like so (check the release notes too): ios-sdk-8.2.2.

I'm leaning towards the environment being the problem here because we'd have noticed on the latest Jitsi Meet release, where we are not observing this.

**Comment by JagaranMaharjan** [comment]
@saghul i faced same issue from branch: ios-sdk-8.2.2.

**Comment by JagaranMaharjan** [comment]
@saghul any update on these issue?

**Comment by JagaranMaharjan** [comment]
@saghul I tried from different branch by generating sdk without any modification but I faced same issue which i have listed below:

**mobile-23.2:** 
1. host video, host shared screen shown as black screen

**mobile-23.1.0:** 
1. host video, host shared screen shown as black screen

**mobile-23.1:** 
1. Video has been turned off by ..... to save bandwidth (tried on 4G/5G internet)

**ios-sdk-8.2.0:** 
1. host video, host shared screen shown as black screen

**ios-sdk-8.2.1:** 
1. host video, host shared screen shown as black screen

**ios-sdk-8.1.2:**
1. Video has been turned off by ..... to save bandwidth (tried on 4G/5G internet)

**ios-sdk-8.1.0:**
1. Video has been turned off by ..... to save bandwidth (tried on 4G/5G internet)

**ios-sdk-8.0.0:**
1. Video has been turned off by ..... to save bandwidth (tried on 4G/5G internet)

**Comment by saghul** [comment]
Are you able to replicate the results when connecting to meet.jit.si?

As I said, I suspect an environment issue, that could involve either the server or the client.
