### ISSUE TITLE
Best option to Embed a jitsi room

### ISSUE THREAD

**Issue by JtLively** [jitsi/jitsi-meet#1370]
I'd like to put a jitsi room in my website. Whats the best way to do that?

**Comment by saghul** [comment]
The best (and easiest!) way to do it is through our iframe API. Have a look at [the documentation](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md).

**Comment by JtLively** [comment]
Responded so fast I don't even remember seeing your answer. :+1:
