### ISSUE TITLE
'Copy Sound Files'  Phase fails when archiving project

### ISSUE THREAD

**Issue by jplandry908** [jitsi/jitsi-meet#13705]
In '@jitsi/react-native-sdk' v0.3.0, a commit was added (compared to the v0.2.1 release) to copy sound files.

https://github.com/jitsi/jitsi-meet/commit/8b6728c65d9504d76c08807da282bb090e9810dc
https://github.com/jitsi/jitsi-meet/commit/d3336192c3a7984ace63cb50934564d9b5abef71

The Android version appears to be working, but the iOS version fails when attempting to archive the app. Xcode reports that "Command PhaseScriptExecution failed with a nonzero exit code".

![Screenshot 2023-08-10 212213](https://github.com/jitsi/jitsi-meet/assets/14008273/b26f6f3c-2926-4c1e-a0d3-11d057dbec1f)

I was able to resolve this issue with the following patch (mainly just adding some quotes).

```
diff --git a/node_modules/@jitsi/react-native-sdk/jitsi-meet-rnsdk.podspec b/node_modules/@jitsi/react-native-sdk/jitsi-meet-rnsdk.podspec
index 8facbaa..f33c087 100644
--- a/node_modules/@jitsi/react-native-sdk/jitsi-meet-rnsdk.podspec
+++ b/node_modules/@jitsi/react-native-sdk/jitsi-meet-rnsdk.podspec
@@ -26,10 +26,10 @@ Pod::Spec.new do |s|
   s.script_phase = {
       :name => 'Copy Sound Files',
       :script => '
-          SOURCE_PATH="${PODS_TARGET_SRCROOT}/sounds"
-          TARGET_PATH="$(dirname ${CONFIGURATION_BUILD_DIR})"
-          PROJECT_NAME=$(basename $(dirname $(dirname ${PROJECT_DIR}))).app
-          cp -R "${PODS_TARGET_SRCROOT}/sounds/" "${TARGET_PATH}/${PROJECT_NAME}"
+          SOURCE_PATH="${PODS_TARGET_SRCROOT}/sounds/"
+          TARGET_PATH=$(dirname "${CONFIGURATION_BUILD_DIR}")
+          PROJECT_NAME=$(basename $(dirname $(dirname "${PROJECT_DIR}"))).app
+          cp -R "${SOURCE_PATH}" "${TARGET_PATH}/${PROJECT_NAME}"
       ',
   }
 end
```

**Comment by saghul** [comment]
Nice! Care to send a PR?
