### ISSUE TITLE
Camera jumpy after playing a video

### ISSUE THREAD

**Issue by zon3d** [jitsi/jitsi-meet#13701]
### Description:

This is a new bug that isn't in the latest stable but is in the latest nightly (and it can be reproduced on meet.jit.si).

I use OBS with the in-built virtual camera to show my camera on Jitsi so that I can also use OBS to play videos. Since upgrading to the latest nightly, after playing a full screen video, when it shows my camera again (after the video), it will then be very jumpy (at like 1 frame per second) for the next 2 to 10 seconds.

The issue only occurs if there are at least 3 people in the room, but doesn't happen if there are only 2. And it doesn't show on my screen, but on everyone else's screen.

I have tested the issue on multiple different computers too, same problem when going from a video back to my camera. It's not OBS as it shows perfectly on my screen on Jitsi.

### Steps to reproduce:

1. Open a room at meet.jit.si
2. Have at least 3 participants.
3. Have someone use OBS as a virtual camera for their web cam.
4. Have that person play a video on OBS and then after the video when it shows the person's camera, see the jumpyness for the next 2 to 10 seconds of that person's camera if viewed from everyone else's screen.

### Server information:

- Jitsi Meet version: Latest nightly

**Comment by saghul** [comment]
Is the frame rate of the virtual camera constant all throughout?

**Comment by zon3d** [comment]
Yes that doesn't change. The evidence for that is the person's virtual camera looks just fine  (without any freezing or reducing of frame rate) on the person's own Jitsi screen, but to everyone else in the room they will be showing at 1 frame per second or so or completely frozen for 2 to 10 seconds.

**Comment by zon3d** [comment]
@saghul I have done some more testing and it has the same problem even I don't use OBS.

Steps to reproduce:

1. Open a room at meet.jit.si
2. Have at least 3 participants.
3. Put your webcam to completely black (like with a cover over the webcam)
4. Remove the cover to show your face and on the other participant's screens your webcam will be shown to be freezing (running at like 1-2 frames per second) for the next 2 to 10 seconds.

**Comment by saghul** [comment]
That sounds like an encoder issue.

If all is black there is almost nothing to encode and if the image changes so dramatically suddenly, the encoder will need to do more work all of a sudden.

Do you observe similar behavior with any other online meetings product?

**Comment by zon3d** [comment]
@saghul 

You're right! Because the same issue is occurring on Google Meet, so not a Jitsi problem.

Looks like it's the latest Google Chrome stable version 115 that is causing the performance issue. I just updated to Chrome version 116 (beta version) and that solved the issue.

**Comment by saghul** [comment]
Good to hear! I'm going to go ahead and close this since there is nothing actionable for us.

**Comment by zon3d** [comment]
@saghul 

I spoke too soon. It turns out it's still having the same problem on the upgraded version of Chrome.

I have detected it is an issue with the nightly version of Jitsi.

Because I just downgraded my Jitsi server to the latest stable and it's working perfectly. But on the nightly build it has this lag issue. And since meet.jit.si uses the nightly builds, it's having the same problem.

So the bug has been introduced somehow between the latest stable and latest nightly builds. This issue needs to be reopened again.

Any thoughts?

**Comment by paweldomas** [comment]
It can also be an issue with layer forwarding on the jvb (forwards only the lowest temporal layer).

**Comment by paweldomas** [comment]
Also switching from black to picture means the layer's weight is changing drastically on the jvb (from tiny bitrate to a much higher one).

**Comment by zon3d** [comment]
Just checking in, and this issue is still occurring on meet.jit.si

But it only happens when there are at least 3 participants in the meeting. With 2 participants it doesn't have this issue at all.
