### ISSUE TITLE
android:exported needs to be explicitly specified for element <service#org.jitsi.meet.sdk.ConnectionService> (Only on API 31, not on 30)

### ISSUE THREAD

**Issue by adrianbartyczak** [jitsi/jitsi-meet#13700]
### Description:

I'm bringing an old app to life which has Jitsi as a dependency, and I've looked everywhere online for this solution.

But it keeps saying "android:exported needs to be explicitly specified for element <service#org.jitsi.meet.sdk.ConnectionService>"

This is only on API level 31, not 30. But Google Play requires API 31 at least to publish an app.

### Steps to reproduce:

I have this in my AndroidManifest.xml:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:node="replace" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />
    <uses-permission android:name="android.permission.STORAGE" />
    
    <uses-permission
        android:name="android.permission.WRITE_SETTINGS"
        tools:ignore="ProtectedPermissions" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />

    <uses-permission
        android:name="android.permission.WRITE_SETTINGS"
        tools:ignore="ProtectedPermissions" />

    <supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true"
        android:resizeable="true"
        android:smallScreens="true"
        android:xlargeScreens="true" />

    <application
        android:name=".utils.MyApplication"
        android:allowBackup="false"
        android:configChanges="uiMode"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:requestLegacyExternalStorage="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true"
        tools:ignore="AllowBackup,GoogleAppIndexingWarning"
        tools:node="merge"
        tools:replace="android:allowBackup,android:label">

        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_naoti" />
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.myvirtualway.resident.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>

        <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </receiver>

        <service
            android:name=".utils.CallForegroundService"
            android:enabled="true"
            android:exported="true" />
        <service
            android:name=".firebase.MyFirebaseMessagingService"
            android:stopWithTask="false"
            tools:ignore="ExportedService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
                <action android:name="OPEN_ACTIVITY_1" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </service>

        <receiver
            android:name=".utils.GeofenceBroadcastReceiver"
            android:enabled="true"
            android:exported="true" />
        <receiver android:name=".utils.PhoneStateReceiver"
                  android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.PHONE_STATE" />
            </intent-filter>
        </receiver> 
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"
                tools:replace="android:resource" />
        </provider>

        <receiver
            android:name=".utils.NetworkChangeReceiver"
            android:enabled="true"
            android:exported="false"
            android:label="NetworkChangeReceiver">
            <intent-filter
                android:exported="true">
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
                <action android:name="android.net.wifi.WIFI_STATE_CHANGED" />
            </intent-filter>
        </receiver>

        <activity
            android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
            android:theme="@style/Base.Theme.AppCompat"
            android:exported="true" />
        <activity
            android:exported="true"
            android:name=".splash.SplashActivity"
            android:configChanges="uiMode"
            android:theme="@style/AppTheme">
            <intent-filter
                android:exported="true">
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".homescreen.EditProfile"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />

        <activity
            android:name=".suspended.SuspendedActivity"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" >

        </activity>
        <activity
            android:name=".managerview.Profile"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".managerview.VirtualListBuilding"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".login.LoginActivity"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".forgotpassword.ForgotPassword"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".homescreen.BaseActivity"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".homescreen.HomeActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".managerview.HomeManager"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".verification.VerficationActivity"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".calling.AcceptCall"
            android:allowTaskReparenting="true"
            android:excludeFromRecents="true"
            tools:ignore="LockedOrientationActivity"
            android:taskAffinity=""
            android:configChanges="orientation|screenSize"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:showOnLockScreen="true"
            android:theme="@style/AppTheme"
            android:exported="true" />

        <activity
            android:name=".managerview.Building_verifiy"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />
        <activity
            android:name=".managerview.Building_verifiy_tooltip"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true" />

        <service
            android:name=".calling.ConnectionService"
            android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE"
            tools:ignore="MissingClass"
            android:exported="true">
            <intent-filter>
                <action android:name="android.telecom.ConnectionService"
                        android:exported="true" />
            </intent-filter>
        </service>
    </application>

</manifest>`

### Expected behavior:

The app to build.

### Actual behavior:

I get the following error log:

`
...
/home/ajb/Downloads/v-edited/virtualway-resident_android/app/src/main/AndroidManifest.xml:129:13-132:52 Warning:
	meta-data#android.support.FILE_PROVIDER_PATHS@android:resource was tagged at AndroidManifest.xml:129 to replace other declarations but no other declaration present
/home/ajb/Downloads/v-edited/virtualway-resident_android/app/src/main/AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present
/home/ajb/Downloads/v-edited/virtualway-resident_android/app/src/main/AndroidManifest.xml:45:9-51:19 Error:
	android:exported needs to be explicitly specified for element <service#org.jitsi.meet.sdk.ConnectionService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
`

### Client information:

App version:

Min SDK: 24
Compile SDK: 31

**Comment by saghul** [comment]
What Jitsi Meet SDK are you using? I believe this has already been fixed in the past few releases.

**Comment by adrianbartyczak** [comment]
It's likely an old SDK version. It was packaged with the application.

But if I update the SDK, I'll likely have to make a whole bunch of code changes, which I don't really want to do. Is there any quick solution for this I can apply?

If I do update the SDK, I get a range of new errors, like this:

error: AudioModeModule is not public in org.jitsi.meet.sdk  
error: package org.jitsi.meet.sdk.CustomModuleEvents does not exist  
error: cannot find symbol import org.jitsi.meet.sdk.JitsiMeetFragment

And the codebase is like this:

![screenshot-23-08-12_11-43-45](https://github.com/jitsi/jitsi-meet/assets/26193935/044d7741-49c9-4044-837b-8566c9f21619)

I can tell the developers used an old version of the Jitsi Meet SDK, and changing this might require a whole bunch of code changes. (Or could it possibly by easy?)

**Comment by saghul** [comment]
You could get the source for their build and change that flag in the Manifest file.

**Comment by adrianbartyczak** [comment]
Oh. Perfect! I'll try that. Thanks.

**Comment by saghul** [comment]
Good luck!
