### ISSUE TITLE
Nginx - Jitsi takes over Vhosts when adding a second domain

### ISSUE THREAD

**Issue by AndyNormore** [jitsi/jitsi-meet#1371]
Hi all,

I have followed the setup guide, and Jitsi works just great. 

So I add a second domain to vhosts file, but for some reason Jitsi completely overwrites, becoming the default vhost served.

When I disable the /sites-enabled/jitsi.mydomain.com.conf and restart nginx, the problem goes away. 

Can this be a conflict or setting from prosody? Which I have no idea what it does?

**Comment by saghul** [comment]
Prosody is and XMPP server, so it's not related to the Nginx configuration. What file did you edit? You should add the new vhost as a new site file, and Nginx will do the matching based on the domain.

**Comment by AndyNormore** [comment]
Ahhhh, I see. Well I ended up just spinning up a new box to run the other sites on. 

I'll just keep a dedicated Jitsi box as it's a BIG part of the operations we're building at www.SkyRooms.IO :)
