### ISSUE TITLE
i18next 403 Forbidden

### ISSUE THREAD

**Issue by hamletmun** [jitsi/jitsi-meet#13716]
### Description:

i18next tries to get non-existent json files, when the chosen language option is not English.

### Steps to reproduce:

1. Open 'https://meet.jit.si/'
2. Click on 'Settings' icon
3. Click on 'General' option
4. Change 'Language' option to 'Spanish' (actually, any other than 'English')

### Expected behavior:

`i18nextXHRBackend.js` does not try to get `languages-es.json` and `translation-languages-es.json`,
or provide the proper json files for the language options.

### Actual behavior:
```
GET https://web-cdn.jitsi.net/meetjitsi_7458.4287/lang/translation-languages-es.json 403
GET https://web-cdn.jitsi.net/meetjitsi_7458.4287/lang/languages-es.json             403
```

### Client information:

- Browser / app version: Microsoft Edge
- Operating System: 115.0.1901.203

**Comment by damencho** [comment]
Ah, yeah this is known issue as there are no such files. We only use one file languages.json and that is embedded in the bundle. Same and for translation-languages.json.

This can be fixed with some i18next magic, which I have not discovered yet.

**Comment by hamletmun** [comment]
Based on https://stackoverflow.com/a/57990586, this might work
``` js
...
const constructLoadPath = (lng: string, ns: string) => {
    if (ns[0] === 'main') {
        return 'lang/{{ns}}-{{lng}}.json'
    } else {
        return 'lang/{{ns}}.json'
    }
}

const options: i18next.InitOptions = {
    backend: <HttpBackendOptions>{
        loadPath: constructLoadPath
    },
    defaultNS: 'main',
    fallbackLng: DEFAULT_LANGUAGE,
    interpolation: {
        escapeValue: false // not needed for react as it escapes by default
    },
    load: 'languageOnly',
    ns: [ 'main', 'languages', 'countries', 'translation-languages' ],
...
```
[react/features/base/i18n/i18next.ts#L68](../blob/master/react/features/base/i18n/i18next.ts#L68)

**Comment by damencho** [comment]
Thanks, I will try it out.
