### ISSUE TITLE
authorization stops working when the connection pre-configuration option is enabled

### ISSUE THREAD

**Issue by jefry7** [jitsi/jitsi-meet#13721]
### Description:

Authorization stops working when the connection pre-configuration option is enabled.
Authorization is required to appoint moderators (otherwise, when the page is updated, the rights are transferred to another) and restrict access to create rooms in order to save resources

### Steps to reproduce:

On the prejoinConfig page, click start, then
We enter the username and password and then nothing happens

### Server information:

- Jitsi Meet version: jitsi-meet/unstable,now 2.0.8901-1 all
- Operating System: Debian

### Client information:

- Browser / app version: Google Chrome / 115.0.5790.111
- Operating System: Windows 10

### Additional information:

There are errors in the browser:

[JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: connection.passwordRequired Script: null Line: null Column: null StackTrace:  n/a
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.ts:505
window.onunhandledrejection @ middleware.ts:96
test:1 Uncaught (in promise) connection.passwordRequired

**Comment by saghul** [comment]
What kind of authentication did you configure?

**Comment by jefry7** [comment]
cyrus
https://jitsi.github.io/handbook/docs/devops-guide/ldap-authentication

**Comment by jefry7** [comment]
if disable the pre-configuration option, authentification works

**Comment by jefry7** [comment]
/etc/jitsi/meet/vk.agrokultura.com-config.js
    
```
// Configs for prejoin page.
    prejoinConfig: {
        // When 'true', it shows an intermediate page before joining, where the user can configure their devices.
        // This replaces `prejoinPageEnabled`.
        enabled: true,
        // Hides the participant name editing field in the prejoin screen.
        // If requireDisplayName is also set as true, a name should still be provided through
        // either the jwt or the userInfo from the iframe api init object in order for this to have an effect.
        hideDisplayName: false,
        // List of buttons to hide from the extra join options dropdown.
        hideExtraJoinButtons: ['no-audio', 'by-phone'],
    },

```

**Comment by saghul** [comment]
You mean if you enable the pre-join page? That's odd. Can you share the browser console logs when that happens?

**Comment by damencho** [comment]
@saghul I reproduce it. I will take a look.

**Comment by jefry7** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/58741446/8fe2fb8d-7b32-485f-9fc4-1bf6f11b5bb1)
