### ISSUE TITLE
iPhone Problem: Your mic is muted by your system settings

### ISSUE THREAD

**Issue by Flying-Light** [jitsi/jitsi-meet#13734]
### Description:

Description: On (iPhone 14, using Safari) I received "**Your mic is muted by your system settings**" and not one can hear me,
Mic permission is ok, Mic is not muted from the interface,
This is the meeting log for the user who has the problem,
https://rtc-visualizer.jitsi.net/?dumpId=cdaf0b70-848c-4c2b-a5f5-871a715b2440.gz

And this is the log for the other participant who do not have any problem (same meeting)
https://rtc-visualizer.jitsi.net/?dumpId=2bf65405-0253-45d7-aff0-0e6c061ed11b.gz

I did not find anything about this problem on the internet,

As far as I knew, the "Your mic is muted by your system settings" error appears for the PC users only, not mobile phones.

### Server information:

**8x8 JAAS: 4340 – August 16, 2023 Release**
    Release: 4340
    Jitsi Meet: 7458
    Jitsi Videobridge: 2.3-34-g44a05334
    Jicofo: 1044

### Client information:

iPhone 14, using Safari

**Comment by saghul** [comment]
If you are a JaaS customer please open a support ticket.

This issue tracker is more targeted towards managing the open source Jitsi Meet project.

**Comment by Flying-Light** [comment]
> If you are a JaaS customer please open a support ticket.
> 
> This issue tracker is more targeted towards managing the open source Jitsi Meet project.

I did open a support ticket 18/08/2023 (since 6 days), but I get a very slow response asking me to wait only.
I thought there may be anything I can do from my side to avoid this problem.
Thanks

**Comment by saghul** [comment]
@andrei-gavrilescu Can you PTAL at the dumps and follow up in the support ticket?

Closing this in favor of that.

**Comment by andrei-gavrilescu** [comment]
I'll check it out.

**Comment by andrei-gavrilescu** [comment]
It looks like the ticket has an ongoing discussion thread. There's a pending follow-up question on the ticket to which the customer didn't respond yet.

**Comment by Flying-Light** [comment]
I confirm it is a problem with the "16-Aug update" the version "Release 4340 – August 16, 2023",
I Pin the "Release 4245 – June 21, 2023" and the problem disappeared.
But this means that I cannot use the new versions,

This is the last response I get from the support:

_We are looking into the issue but we cannot currently reproduce it.
Have you tried updating the config to remove the VP9 codec?
You can change the videoQuality.mobileCodecPreferenceOrder to remove VP9 and see if the issue persists.
We apologize for the inconvenience and thank you for your understanding on this matter._

**Comment by andrei-gavrilescu** [comment]
Thank you for the followup. In their response support suggest:
"
_Have you tried updating the config to remove the VP9 codec?
You can change the videoQuality.mobileCodecPreferenceOrder to remove VP9 and see if the issue persists._
"
Could you try that? Also, if it's not too much trouble, could you please reply on the support thread for better visibility? Thank you.
