### ISSUE TITLE
The Jitsi app doesn't open external links to meet.jitsi.

### ISSUE THREAD

**Issue by javm94** [jitsi/jitsi-meet#13736]
When creating a meeting using the 8x8.vc server, the browser opens instead of the app directly. When tapping on "Join" in the app, an error is displayed: "The page cannot be opened because the address is not valid." This issue occurs on both the Android and iPhone versions of the app

**Comment by saghul** [comment]
@Calinteodor PTAL

**Comment by saghul** [comment]
I took a quick look and noticed currently 8x8.vc links are being opened with 8x8 Work.

So, the error you see if expected.

I'll see what can be done here, but in the meantime you can copy the full meeting URL, paste it in the Jitsi Meet app as if it was the room name and that will work. Not ideal, I know.

**Comment by Calinteodor** [comment]
Hello! Here is a recording I did on latest beta release. As you can see, I changed the server url to https://8x8.vc and the conference opens inside the Jitsi app.

https://github.com/jitsi/jitsi-meet/assets/26413496/f23553d7-1aec-4967-8293-088f4586a6b6

**Comment by javm94** [comment]
How can I subscribe to the iPhone app betas?
El 23 ago 2023, a la(s) 3:18, Calinteodor ***@***.***> escribió:

﻿

Hello! Here is a recording I did on latest beta release. As you can see, I changed the server url to https://8x8.vc and the conference opens inside the Jitsi app.

https://github.com/jitsi/jitsi-meet/assets/26413496/f23553d7-1aec-4967-8293-088f4586a6b6

**Comment by saghul** [comment]
Check here: https://jitsi.github.io/handbook/docs/releases

**Comment by javm94** [comment]
Tanks! Ready now runing the beta for iPhone.

El 24 ago 2023, a la(s) 1:47, Saúl Ibarra Corretgé ***@***.***> escribió:

﻿

Check here: https://jitsi.github.io/handbook/docs/releases
