### ISSUE TITLE
Android/IOS rnsdk not working video button to enable cameras

### ISSUE THREAD

**Issue by Larens94** [jitsi/jitsi-meet#13740]
https://github.com/jitsi/jitsi-meet/assets/32598073/c47c919c-6009-4828-a080-a949489ad287

### Description:
sometimes clicking on the video icon to activate the camera doesn't work.
the click has no effect.

- Operating System: app android    @jitsi/react-native-sdk:^0.3.0"

**Comment by damencho** [comment]
Which version of the Jitsi Meet app is this? 

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by saghul** [comment]
Was the permission denied?

**Comment by Larens94** [comment]
Hello, it does not seem that the permissions have been denied because he sees me.

I am sending you here 2 videos and also the logs.



https://github.com/jitsi/jitsi-meet/assets/32598073/118660e4-88fb-4fce-899c-2edfb7660f4c


https://github.com/jitsi/jitsi-meet/assets/32598073/ca505ede-f184-47bf-8a58-bd9338994b1b




Sincerely
[logs_no_click_icon_video.txt](https://github.com/jitsi/jitsi-meet/files/12429904/logs_no_click_icon_video.txt)
[log_black_screen.txt](https://github.com/jitsi/jitsi-meet/files/12429905/log_black_screen.txt)

**Comment by Larens94** [comment]
I add that the same problem is on IOS.
also it seems to me that only the call master has this problem.

**Comment by Larens94** [comment]
I read the issues of 2022, by disabling the p2p mode it seems to me that now I no longer encounter the problem on IOS. I still haven't been able to try it on android but I will keep you updated.

once I've run the tests on multiple devices with multiple people I'll give you confirmation.

to disable p2p I changed the disableP2P flag

issue links:
https://github.com/jitsi/jitsi-meet/issues/11100
I don't know if they are closely related but I repeat it seems that on IOS the problem no longer exists.

Sincerely
