### ISSUE TITLE
RNSDK - Android and iOS - Chat screen - incorrect margin/space between input text field and keyboard

### ISSUE THREAD

**Issue by alexander-at-t** [jitsi/jitsi-meet#13748]
### Description:

On mobile devices, using Jitsi RNSDK, chat input text box looks too far from keyboard on Android and overlapping on iOS.

<img src="https://github.com/jitsi/jitsi-meet/assets/74536256/d4b8ac96-2e3f-4335-8b0e-9e8ab50edc37" width="200" />

<img src="https://github.com/jitsi/jitsi-meet/assets/74536256/52e3fb6d-e6f0-4efb-a35b-c78de92b9f9f" width="200" />

Is it expected?

### Steps to reproduce:

1. Open mobile app developed using RNSDK (and React Native 0.72.4 - maybe other versions too)
2. Open chat
3. Start typing text

**Comment by alexander-at-t** [comment]
The bug is still reproducible.

Steps to reproduce:
1. Clone https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/react-native
2. Run on iOS simulator
3. Join call
4. Open chat
5. Start typing message (open virtual keyboard)

At this moment, this sample app uses @jitsi/react-native-sdk 0.5.0 version.

Screenshot of bug:
<img width="372" alt="Screenshot 2023-10-24 at 11 47 13 PM" src="https://github.com/jitsi/jitsi-meet/assets/74536256/5cb549cf-e84a-4c88-a8d3-13f11bb03ddc">

@Calinteodor is this bug reproducible for you too?

**Comment by Calinteodor** [comment]
Unfortunately, we weren't able to look into this.
