### ISSUE TITLE
Android - unfortunately something went wrong

### ISSUE THREAD

**Issue by seifeibrahim** [jitsi/jitsi-meet#13744]
The SDK& Calls were working efficiently, but suddenly it stopped showing me this message

Note: This issue is on the Android platform only

![MicrosoftTeams-image (2)](https://github.com/jitsi/jitsi-meet/assets/15933375/24999f9a-f68b-4da6-b663-a15ac0403358)

**Comment by saghul** [comment]
What server are you using? Please check the logs with adb logcat

**Comment by seifeibrahim** [comment]
<img width="1350" alt="Screenshot 2023-08-29 at 11 03 54 AM" src="https://github.com/jitsi/jitsi-meet/assets/15933375/7b8e1781-bf68-44d5-83cf-79c45b740f92">

@saghul

**Comment by saghul** [comment]
Looks like losing the config from https://call.sonann.org/config.js was unsuccessful.

**Comment by seifeibrahim** [comment]
Issue solved it was an issue with the server certificate

Thanks so much
