### ISSUE TITLE
Getting "Waiting for a moderator" popup when creating anonymous meeting

### ISSUE THREAD

**Issue by ilmai** [jitsi/jitsi-meet#13751]
### Description:

Like mentioned in the title, I'm trying to create an anonymous meeting (i.e. not logged and not a "moderated meeting") on https://meet.jit.si/ but getting the "Waiting for a moderator" popup as if I'm joining an already existing moderated meeting. I tried with various improbable names, including really long random strings of characters, but this happens every time.

### Steps to reproduce:

1. Open https://meet.jit.si/
2. Enter a name for the meeting
3. Click Start meeting

### Expected behavior:

A new meeting is created and joined

### Actual behavior:

The "Waiting for a moderator" popup appears

<img width="935" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/3365471/ed6a35fa-1048-4fe1-90b2-fd9f536dd629">

### Server information:

https://meet.jit.si/

### Client information:

- Browser / app version: Tested on Firefox 116.0.3 and iPad app version 23.2.0
- Operating System: Mac OS 13.5 / iPad OS 16.6

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://jitsi.org/blog/authentication-on-meet-jit-si/

**Comment by JakeQZ** [comment]
> community forum

See https://community.jitsi.org/t/waiting-for-moderator-and-forced-login-on-https-meet-jit-si/126008

> problems

I think there is a major issue with this change.  Many people don't want to be forced to use Facebook or Google to "log in", and others (like the first to arrive at a meeting) won't have a GitHub account.  There are no links to create an account, and no first-party account creation available.

IMO this change has been poorly thought-out.
