### ISSUE TITLE
UI and documentation don't reflect new log-in requirements

### ISSUE THREAD

**Issue by Vectornaut** [jitsi/jitsi-meet#13754]
### Description:

Starting a [meet.jit.si](https://meet.jit.si/) meeting in what used to be the standard way now leads to the "Waiting for a moderator..." dialog, which doesn't clearly explain what has changed or how to start a meeting now. The [meet.jit.si](https://meet.jit.si/) and documentation don't reflect the new log-in requirements. Instead, they suggest that starting a meeting without logging in should still create a meeting where everyone is a moderator.

### Steps to reproduce:

1. Go to [meet.jit.si](https://meet.jit.si/)
2. Enter a meeting name and click *Start meeting.*
3. Enter a display name and click *Join meeting.*
4. Read the new "Waiting for a moderator..." dialog.
5. Re-read the instructions on [meet.jit.si](https://meet.jit.si/). The  "Or book a meeting URL in advance where you are the only moderator" message suggests that starting a meeting without logging in should, as usual, create a meeting where everyone is a moderator.
6. Read the [FAQ](https://jitsi.github.io/handbook/docs/faq/) in the Jitsi Meet Handbook. The phrase "If you are the moderator of a conference (everyone is a moderator if you are using meet.jit.si)" seems to confirm that starting a meeting without logging in should create a meeting where everyone is a moderator.

### Expected behavior:

- Before the new log-in requirements come into effect, the UI warns users about the upcoming change, giving them time to prepare.
- After the new log-in requirements come into effect, the UI changes to help users navigate the updated system—even if they missed the previous warnings.
- The documentation changes to help users understand the new log-in requirements.

### Actual behavior:

- I didn't encounter any advance warning of the new log-in requirements.
- The "Waiting for a moderator..." dialog doesn't clearly explain what has changed, or how to start a meeting now.
- The documentation doesn't reflect the new log-in requirements. This makes the failure of the usual meeting start process look like a bug rather than an intentional change.

### Client information:

- Browser: Firefox 116.0.3 (64-bit)
- Operating System: Ubuntu 22.04

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
We try to keep the issue tracker for issues for the jitsi-meet project.

This was announced more than a month ago on the community calls. And when the date was known it was announced in the forum https://community.jitsi.org/t/authentication-on-meet-jit-si/125922 and in the news on the web https://jitsi.org/blog/authentication-on-meet-jit-si/

**Comment by Vectornaut** [comment]
I'm neither a Jitsi developer nor the maintainer of a Jitsi installation, so I never knew about the Jitsi community call, and I certainly don't check the Jitsi community forum or blog every three or four days. I do frequently create meetings on [meet.jit.si](https://meet.jit.si/), so a warning in the UI would've been more likely to reach me. I'm used to being warned about breaking changes in the UI on other conferencing platforms, which is why I listed this as expected behavior.

**Comment by JakeQZ** [comment]
> breaking changes

I would expect some teething troubles with a significant software design change such as this.  But I would like to resolve them, rather than close them out without any apparent investigation or dialogue.  I don't think closing these issues point-blank is any good for anyone in the long term.

**Comment by damencho** [comment]
This is jitsi-meet issue tracker, nothing from the above is a jitsi-meet problem.

If the docs that mention meet.jit.si are not correct, open an issue in the handbook repo or better a PR is more than welcome.

**Comment by JakeQZ** [comment]
> nothing from the above is a jitsi-meet problem.

I disagree,  There is a major *problem* with *jitsi-meet* due to the Aug 24 change requiring log-in via a third-party global conglommerate.  Please see discussions elsewhere as to why this is absolutely objectionable.  Many people do not want to share their information with Google, Meta, or Microsoft, for various good reasons.

Please rethink how you have solved this 'problem' you've never even properly described.

**Comment by damencho** [comment]
There was no change in the project of jitsi-meet on Aug 24 concerning any of these. 
meet.jit.si is not jitsi-meet. It just uses it as any other deployment of jitsi-meet. You refuse to understand that.
Jitsi-meet when installed by default does not require authentication and this has not changed and is still the case.

**Comment by Vectornaut** [comment]
> If the docs that mention meet.jit.si are not correct, open an issue in the handbook repo

Whoops, I didn't notice that the handbook was in a separate repo! I've struck out the parts of this issue that deal with the documentation problem, and opened [handbook issue 464](https://github.com/jitsi/handbook/issues/464) in their place. I still think that the (meet.jit.si)[https://meet.jit.si/] UI text I mentioned is misleading enough to warrant an issue here.

> or better a PR is more than welcome.

[Done](https://github.com/jitsi/handbook/pull/465). This is just a quick fix, but I don't know enough to do anything more nuanced.

**Comment by JakeQZ** [comment]
> There was no change in the project of jitsi-meet on Aug 24 concerning any of these. meet.jit.si is not jitsi-meet.

OK, in that case, where do we file bugs reports against `meet.jit.si`, instead of here?

> You refuse to understand that.

Not so.  I sometimes cannot understand something that has never been explained to me.  I actually have a thirst for knowledge, and keenly seek explanations.  This is why I want to know the rationale behind this change.  Never do I refuse to understand something.

Your accusation is incredibly insulting, and as ill-guided as this software change you keep defending for reasons you never give..

Why won't you provide more information about the TOS violations?  We don't need or want specific case details, which should not be posted on a public forum anyway,  But a general representatitve overview of types of violations would be not just helpful, but essential.

> Jitsi-meet when installed by default does not require authentication and this has not changed and is still the case.

I have a web server, and am sure it's easy to set up.  But since the service was already operational on `meet.jit.si`, it seemed unnecessary for the occasional meeting.

**Comment by JakeQZ** [comment]
> meet.jit.si is not jitsi-meet

So why do you keep aggressively defending it against criticism re the change requiring Google/Facebook login.

And who the heck are you?  Shouldn't we like to know before spilling our details online upon using your service?  It's a two-way process, you know?

**Comment by JakeQZ** [comment]
> meet.jit.si is not jitsi-meet. It just uses it as any other deployment of jitsi-meet.

As far as I understood, `meet.jit.si` always ran the latest main branch version of `jitsi-meet`.

So they are inextricably linked, even if not identical.

I have already explained this elsewhere.

Please stop being defensive about this change, and accept mistakes have been made.

"To Err is Human."

**Comment by JakeQZ** [comment]
Test
