### ISSUE TITLE
As soon as someone else joins, error message printed on screen

### ISSUE THREAD

**Issue by designgurudotorg** [jitsi/jitsi-meet#1375]
I have a fresh install running on one of my own servers on Digital Ocean and everything looks good, when I start a new video session the interface loads as expected and I can see my camera, but as soon as someone else joins the video both/all participants see an error message as attached ("Unfortunately, something went wrong We're trying to fix this" with a loader bar) and suddenly no one can use jitsimeet properly.

Any ideas whats wrong?

q./
![screen shot 2017-03-06 at 12 05 22 am](https://cloud.githubusercontent.com/assets/12697545/23597600/48de9efc-0202-11e7-8f97-47649dcb3f37.png)

**Comment by designgurudotorg** [comment]
BTW that screen was taken from within RocketChat but I'm getting the same problem when I use my jitsimeet install on its own

**Comment by designgurudotorg** [comment]
Here's a console log - looking at it I'm not sure if the problem is the app is appending my subdomain where jitsimeet is installed with 'conference' or not. http://pastebin.com/8AJYUaDL
q./

**Comment by saghul** [comment]
> looking at it I'm not sure if the problem is the app is appending my subdomain where jitsimeet is installed with 'conference' or not.

No, that's not related, that's appended as part of the XMPP setup.  On your logs I see there is no Jitsi Video Bridge detected. Is it running?

**Comment by designgurudotorg** [comment]
Weird, I had done the quick install (https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) so I assumed it was installed.  

Sidenote: when I use the self-cert option everything works flawlessly on the exact server environment (different URL and machine of course)

**Comment by saghul** [comment]
> Weird, I had done the quick install (https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) so I assumed it was installed.

Yes, it should be, if you installed the "jitsi-meet" meta-package. Just make sure it's running, in case it's not, for whatever reason.

> Sidenote: when I use the self-cert option everything works flawlessly on the exact server environment (different URL and machine of course)

What option were you using now? A custom certificate? Do you have the full chain? Are you using HTTPS?

**Comment by designgurudotorg** [comment]
It seems like this was indeed some SSL cert problem - I was using Lets Encrypt but then when I started fresh just now and installed everything on a new server using a custom SSL from godaddy it all worked flawlessly ;)

**Comment by saghul** [comment]
I know Let's Encrypt works, any chance you didn't choose the fullchain file?

**Comment by designgurudotorg** [comment]
Blargh - I may have spoken too soon - everything was working fine and then suddenly it happened again just now - I power cycled the server and its back to normal and working again.

Whats the minimum system resources a server running Jitsi should have?

q./

**Comment by paweldomas** [comment]
Try opening JS console in Chrome and there should be more details on why this error happened. Also make sure to have the "Preserver log" checkbox checked to see what happened prior to reload.
![screen shot 2017-03-07 at 14 02 32](https://cloud.githubusercontent.com/assets/2965063/23675369/c6b05c52-033e-11e7-8eef-8a0731fddf76.png)

**Comment by afcady** [comment]
See #1331 for a likely explanation of the underlying issue here.
