### ISSUE TITLE
Authentication issue with mobile SDK 8.3.0

### ISSUE THREAD

**Issue by gauravdua27** [jitsi/jitsi-meet#13766]
After the recent update to Jitsi, a new feature allows users to log in before starting a session.

 In the latest mobile SDK version 8.3.0 (released on August 23, 2023), it's highlighted that Firebase authentication is now supported. 
This brings up the question: How can we implement Firebase authentication or any other method to eliminate the need for users to repeatedly log in every time they begin a meeting? 

Our current Jitsi version is mobile SDK 8.3.0, and we're utilizing the Jitsi Instance at https://meet.jit.si/."

**Comment by damencho** [comment]
> This brings up the question: How can we implement Firebase authentication or any other method to eliminate the need for users to repeatedly log in every time they begin a meeting?
> 
> Our current Jitsi version is mobile SDK 8.3.0, and we're utilizing the Jitsi Instance at https://meet.jit.si/."

You should not be using meet.jit.si in production with the SDK as this breaks the [terms and conditions](http://jitsi.org/meet-jit-si-terms-of-service/). Use your own self-hosted instance or you can consider using [jaas](https://jaas.8x8.vc).

**Comment by dvkedkd** [comment]
您好，我这边网页访问Jitsi-meet（https://meet.jit.si/）时总会出现Firebase 身份验证失败，您遇到过这种情况吗？
