### ISSUE TITLE
customToolbarButtons not work for external api

### ISSUE THREAD

**Issue by ThonyBat** [jitsi/jitsi-meet#13769]
### Steps to reproduce:

1.  Create app angular typescript
2.  add on index.html <script  src="https://meet.jit.si/external_api.js">
3.  create call with new window["JitsiMeetExternalAPI"](domain, options);

### Expected behavior:

See customToolbarButtons on iFrame toolbar

### Actual behavior:

parameter customToolbarButtons not work
![image](https://github.com/jitsi/jitsi-meet/assets/73229853/f2e4b00d-895a-4617-a90d-fbfdc484f61d)

### Server information:

- Jitsi Meet version: last version
- Operating System: your like

### Client information:

- Browser / app version: chrome 116.0.5845.111
- Operating System: Windows 11

### Additional information:

![image](https://github.com/jitsi/jitsi-meet/assets/73229853/3ca92a4a-80a4-4bca-a364-0f8be6548e2e)

**Comment by damencho** [comment]
Here you can find a list of all config params that you can override via the external API:
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/configWhitelist.ts

**Comment by saghul** [comment]
Closing since the option is not meant to be overridable.
