### ISSUE TITLE
Bug with Edge integration - API jitsi

### ISSUE THREAD

**Issue by JehanO** [jitsi/jitsi-meet#13762]
### Description:

Doing the API integration through bubble. Works well on google chrome, but with edge, I run into an error:
![image](https://github.com/jitsi/jitsi-meet/assets/57331591/638f0422-290a-46ef-8e72-e34caa36ef8f)

code error: JITSIMeetExternalAPI is not defined at eval

### Steps to reproduce:

Run it with bubble on my own website: https://app.thewokies.fr/test_jitsi
On Chrome it works well, but on Microsoft EDGE, lead to the issue.

### Expected behavior:

The page should load a JITSI meeting

### Actual behavior:

The page stays blank on Microsoft Chrome

### Server information:

- Jitsi Meet version: 
- Operating System: Mac, Microsoft Edge

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

Here is my code:
HTML element:
`<html>
      <head>
        <script src='https://8x8.vc/vpaas-magic-cookie-xxx/external_api.js' async></script>
        <style>html, body, #jaas-container { height: 100%; }</style>
        <script type="text/javascript">
          window.onload = () => {
            const api = new JitsiMeetExternalAPI("8x8.vc", {
              roomName: "vpaas-magic-cookie-xxx/test_jitsi",
              parentNode: document.querySelector('#jaas-container'),
            });
          }
        </script>
      </head>
      <body><div id="jaas-container" /></body>
    </html>`
    
And Javascript element:
`const sessionName='test-jitsi'
const userNickname='Test'
const userEmail='test@test.fr'
const encodedSessionName = encodeURI(sessionName);
const lang='fr-fr'

console.log(sessionName,'sessionName')
console.log(userNickname ,'userNickname ')
console.log(encodedSessionName ,'encodedSessionName ')

const domain = '8x8.vc';
const options = {
  roomName: `vpaas-magic-cookie-xxx/${encodedSessionName }`,
  parentNode: document.querySelector('#jaas-container'),
  userInfo: {
    email: '${userEmail}',
    displayName: `${userNickname}`
  },
  lang: '${lang}',
  configOverwrite: {
    startWithAudioMuted: false,
    startWithVideoMuted: false,
    toolbarButtons: [
      'camera',
      'microphone',
      'chat',
      'tileview',
      'desktop',
      'select-background',
      'settings'
    ]
  }
};

const api = new JitsiMeetExternalAPI(domain, options);`

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

It seems like a code error in some plugin toolbox in your code. The external API loads successfully and shows the UI. The problem is not Edge only, I reproduce it locally in chrome.

**Comment by JehanO** [comment]
Alright, will have a look. Thanks
