### ISSUE TITLE
Random disconnects on meet.jit.si

### ISSUE THREAD

**Issue by monstro1** [jitsi/jitsi-meet#13771]
using meet.jit.si, randomly disconnecting for no reason

![image](https://github.com/jitsi/jitsi-meet/assets/67171463/593262e6-287a-4106-a38e-2869ffdb1a06)

Not an issue with my Internet

also it keeps changing my name when I authenticate via gmail

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Can you grab the js console logs and upload it?

**Comment by Petteri** [comment]
I have seen this same issue recently. Started to happen about month ago.

**Comment by damencho** [comment]
Please grab the console logs from the browser in the moment you see this and upload it here, so we can take a look. Thank you.

**Comment by bryanboateng** [comment]
@Petteri @monstro1 which OS are you using? Is it macOS?

**Comment by Petteri** [comment]
I am using Ubuntu Linux with the Google Chrome.

**Comment by aleksan4eg** [comment]
The same thing happens to me with Google Chrome (Version 118.0.5993.117 (Official Build) (64-bit)) on Ubuntu 22.10.
