### ISSUE TITLE
Insert pictures into whiteboard (and stamps)

### ISSUE THREAD

**Issue by girasole123** [jitsi/jitsi-meet#13776]
Hi,

It would be great to be able to insert images (and possibly other types of file) into the whiteboard. I believe that SVG can do `<image xlink:href="image.png">`.

Another idea is to be able to quickly insert stamps (such as ✓ or ♥).

Thanks!

**Comment by saghul** [comment]
Excalidraw unfortunately uses Firebase for storage so we disabled picture upload until a way around it can be found.

**Comment by vpzomtrrfrt** [comment]
What sort of solution would you expect? Another server for handling file uploads? Storing them in the room somehow?

**Comment by saghul** [comment]
> What sort of solution would you expect? Another server for handling file uploads? Storing them in the room somehow?

I'd expect a small storage service, yes.

**Comment by vpzomtrrfrt** [comment]
Maybe integrated into excalidraw-backend? Unless you want it for other non-whiteboard features too

**Comment by saghul** [comment]
> Maybe integrated into excalidraw-backend? Unless you want it for other non-whiteboard features too

Maybe, yeah. But there is no interdependency there, a separate service should also be possible I guess.

**Comment by vpzomtrrfrt** [comment]
Started an initial effort as https://github.com/jitsi/excalidraw/pull/3

**Comment by longuto** [comment]
The open-source software minio works quite well

**Comment by 18x9** [comment]
Hi, I would love to able to paste images on the whiteboard as well. Are there any ways to do this with Jitisi or other FOSS software? Thank you.
