### ISSUE TITLE
Crash (Aw, Snap) on Google Chromium 112.0.5615.165

### ISSUE THREAD

**Issue by franzos** [jitsi/jitsi-meet#13772]
### Description:

Web application crashes immediately.

### Steps to reproduce:

Visit https://meet.jit.si/

### Expected behavior:

No crash.

### Actual behavior:

Crash: "Aw, Snap"

```
Error code: RESULT_CODE_KILLED_BAD_MESSAGE
```

Here's the console log:

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
(index):73 (TIME) index.html loaded:	 675.5
Logger.js:154 2023-08-31T11:00:51.581Z [modules/statistics/LocalStatsCollector.js] <fi.connectAudioContext>:  Connecting audio context
LocalStatsCollector.js:169 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl.qjz9zk/7K7WLu
fi.connectAudioContext @ LocalStatsCollector.js:169
7193 @ LocalStatsCollector.js:177
__webpack_require__ @ bootstrap:19
4449 @ index.js:1
__webpack_require__ @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ startup:4
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1
Logger.js:154 2023-08-31T11:00:52.549Z [modules/RTC/RTCUtils.js] <Vc>:  list of media devices has changed: (8) [InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo]
Logger.js:154 2023-08-31T11:00:52.742Z [features/base/redux] <Object.persistState>:  redux state persisted. 99914b932bd37a50b983c5e7c90ae93b -> d89ed438f5eff5fdcd6ab57ff40f1395
```

### Server information:

- Jitsi Meet version: Hosted (https://meet.jit.si/)
- Operating System: N/A

### Client information:

- Browser / app version: Version 112.0.5615.165 (Official Build, ungoogled-chromium) (64-bit)
- Operating System: Guix

### Additional information:

I read in other issues that it's probably related to the Browser or OS.

- On the same OS, using Firefox 116.0.3 (64-bit) everything is OK
- Chrome Version 114.0.5735.106 (Official Build) (64-bit) is also OK
- Using Chromium, I see the crash

I have no other issues with Chromium whatsoever, so if this happens to be a 'browser-issue', kindly share what could be the problem, so I can investigate further / provide additional information.

**Comment by damencho** [comment]
If the browser is crashing you better report it to chromium and send the crash report to them.

**Comment by damencho** [comment]
So you see the crash with latest chromium? I think in 112 the had a bug that was causing such thing ... Don't remember what was that about ... Something with codecs and p2p maybe.

**Comment by franzos** [comment]
> So you see the crash with latest chromium? I think in 112 the had a bug that was causing such thing

@damencho thank you for the hint. I will investigate further.

I assumed maybe something is missing; So I came here, to find out what it could be.
