### ISSUE TITLE
JitsiMeetExternalAPI: htmlElement "Uncaught TypeError: this.parentNode.appendChild is not a function"

### ISSUE THREAD

**Issue by AndyNormore** [jitsi/jitsi-meet#1377]
Hi folks, when embedding a Jitsi room, I want to set the custom HTML tag for it to be in. I can't however. 

`var domain = "meet.jit.si";

var room = "demo"; 

var width = "100%";

var height = 800;

var htmlElement = "skyroom_meeting";

var api = new JitsiMeetExternalAPI(domain, room, width, height, htmlElement);`

Results in: 

Uncaught TypeError: this.parentNode.appendChild is not a function
    at new JitsiMeetExternalAPI (external_api.js:111)
    at <anonymous>:28:22

**Comment by AndyNormore** [comment]
Sorry, solved by using a document selector. Please update the documentation for us JS noobs.

var htmlElement = document.getElementById("jitsi_meeting_id");

**Comment by saghul** [comment]
You're right, the parameters are not clearly documented, I'll fix that.

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/pull/1378

**Comment by AndyNormore** [comment]
Awesome! Thanks.
