### ISSUE TITLE
GitHub account's private mail address visible in jitsi-meet UI

### ISSUE THREAD

**Issue by MK-3PP** [jitsi/jitsi-meet#13778]
Hello,

I have (reluctantly) logged into jitsi-meet at meet.jit.si with my GitHub account.
In the jitsi-meet UI under "Settings" -> "Profile" I can see my private mail address.

How is this possible if there is only an authentication token is fetched and the meeting is loaded with it, like @saghul mentions here
https://github.com/jitsi/jitsi-meet/issues/13753#issuecomment-1697301570?

I'm not an expert in the field, but "token" sounds to me like an anonymous ID. And "load the meeting with it" sounds like an ephemeral thing. Both those assumptions must be false, since the Mail Address is visible in jitsi-meet. Can you please clarify?

Also, if I join a meeting anonymously, the same field in "Settings" -> "Profile" shows a text input box for a mail address for Gravatar.
This implies, in case of a logged in usage of jitsi-meet, the unintentionally (for me) shared mail address is then used with a third service, Gravatar, to unintentionally (for me) get my profile picture. Is this correct? Or is Gravatar only used as an option for users that are not logged in?

If it can be avoided, please don't read or forward personal information anywhere.

**Comment by saghul** [comment]
The token is a JWT token, that is provided to us by Firebase, which in turn does the GH login part.

We'd have to look it up, but if you see your email there is means it's in the token.

**Comment by MK-3PP** [comment]
Thank you. Just to clarify, "there" is in the jitsi UI. I am not analyzing any tokens or traffic.

![grafik](https://github.com/jitsi/jitsi-meet/assets/60696116/403dad54-1eac-487e-841c-6f16d7058388)

**Comment by saghul** [comment]
Right. Jitsi Meet will read that information from the token (if available) and update itself.

Jitsi Meet does not directly talk to GH, and he Firebase app does, and just reloads the page with a token. All the information is in the token.

You can get ahold of one and paste it in the debugger in jwt.io to see the contents.

**Comment by saghul** [comment]
You can open developer tools and see the URL redirect, the token is in the jwt= URL query parameter.

A quick glance at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address makes me think GH is not being very clear about what making your e-mail private means. According to that page it's only about git operations on the web, only that.
