### ISSUE TITLE
How can i add this in react native

### ISSUE THREAD

**Issue by Shahzad062** [jitsi/jitsi-meet#13785]
https://github.com/jitsi/jitsi-meet/blob/0170c65c7b84979df5b74634134b4e93b0a35c4e/config.js#L626

**Comment by saghul** [comment]
Set it in the config prop, it will override the server configured options.

**Comment by Shahzad062** [comment]
npm i --save @vidit-me/react-native-jitsi-meet  i m using this package but config not working

**Comment by Shahzad062** [comment]
Can u tell me how i can integrate jitisi official sdk for react native

**Comment by saghul** [comment]
Please check the README or the npm docs, there is even an example linked.
