### ISSUE TITLE
When i stop a record with Jibri, stop recording button doesn't turn back to start recording

### ISSUE THREAD

**Issue by ChrisPices** [jitsi/jitsi-meet#13787]
### Description:

In my infrastructure, we need to create meetings and record them, Sometimes, it happens we need to restart the record during the call.
When i start a record on a Jitsi meet with Jibri, and then i stop it, the "stop recording" button doesn't turn back to "start recording". I can't start a new record next to one.

Record works perfectly, and is saved on my server, The only issue is the web interface that doesn't refresh the record button.

### Steps to reproduce:

1. Start a meet and a record with Jibri
2. Stop the record
3. Start a new record again

### Expected behavior:

Stop nicely the record then start another one. the start/stop recording button toggle nicely

### Actual behavior:

Record button doesn't change to "Start recording" when i stop it.

![image](https://github.com/jitsi/jitsi-meet/assets/143708831/a148fba0-7230-4487-9de4-6fe3a77932cd)
![image](https://github.com/jitsi/jitsi-meet/assets/143708831/cc1139bb-0a21-48d4-b824-bfdeaccf594a)
![image](https://github.com/jitsi/jitsi-meet/assets/143708831/c52965c0-d015-44f6-b750-5459e28f85ad)
![image](https://github.com/jitsi/jitsi-meet/assets/143708831/2b097ecb-83e4-4e2d-b45b-85cfbe9753e4)

then it stays lock on "Arrêter l'enregistrement" -> stop recording

### Server information:

- Jitsi Meet version: Last one , Java 17
- Jibri version: Last one , Java 11
- Operating System: Debian 12 bookworm

### Client information:

- Browser / app version: All browser
- Operating System: W10 and iPhone

**Comment by ChrisPices** [comment]
Just downgrade to august 2022 version and everything works.

**Comment by rdlab-upc** [comment]
I have the same issue with latest versions of jitsi/meet/prosody/jibri/jvb

@ChrisPices Did you downgrade just jitsi-meet? From [2.0.8960] to [2.0.8922]? Any other component?

https://github.com/jitsi/jitsi-meet/releases

If this is a bug, why close it?

Thank you.

**Comment by ChrisPices** [comment]
Hey,

There's no bugs, i only forgot to put the hiddendomain on the config.js file, these makes me issues first time but after checks, made it works perfectly on the latest version.

If you still want downgrade, i suggest you to check on https://download.jitsi.org/stable/ and take all the components with the same version / release date, and that's makes it works. You don't need to add the hiddendomain BUT it still an old release....

**Comment by ChrisPices** [comment]
and also i downgraded to the 2.0.7830-1, but now i'm back to the latest release in date

**Comment by rdlab-upc** [comment]
Thank you for your comments. Sorry for the late answering, It was a very time-consuming debugging issue...

In our case, we have a user self-authentication system that check any jitsi-meet URL access and if it wasn't approved (exists in an internal database), redirects you to an error page.

We founded out the hard way that jibri service fetches an "HTTP get /" request to the main jitsi domain, so in our case thus request was refused and jibri behaves in a strange fashion. Like the one described by you (You can start the recording properly, but you cannot ¿? stop the recording or get the buttons to their initial state).

```
nginx meet server log:
`<Jibri_IP> - [08/Oct/2023:12:45:13 +0200] "GET / HTTP/2.0" 200 9161 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "2.68"`
```

After we whitelisted the jibri IPs in our nginx self-authentication system, everything works like a charm. 

Thank you!

**Comment by ChrisPices** [comment]
Great, that's perfect if you made it works :)

In my case, I was able to stop the record (in my logs the video was save properly and jibri turn back to idle mode) but the recording button was locked to "stop recording". So I was unable to start a new recording without refreshing the page.

Also I am using Jitsi & Jibri hosted in the same server, so it wasn't a IP problem like you.

Have a good day !
