### ISSUE TITLE
Unable to Access - https://moderated.jitsi.net/

### ISSUE THREAD

**Issue by Sajeev12345** [jitsi/jitsi-meet#13782]
Description: When users visit https://moderated.jitsi.net they are unable to view the site, showing the "This site can't be reached" error message.

Client information: - Browser / app version: Chrome Version 116.0.5845.141 (Official Build) (64-bit)- Operating 

System: Windows

Additional information: Experiencing this same issue on multiple devices

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Yes, that is down for maintenance, we are working on it.
