### ISSUE TITLE
[android] Unnecessary login required when raising hand

### ISSUE THREAD

**Issue by opk12** [jitsi/jitsi-meet#13784]
### Description:

In the Android app, when I raise the hand to talk in a room that allows unregistered users, the app almost always shows a mandatory username / password input dialog, whose `Cancel` button brings me back to the room history. If I try many times in a row, eventually the dialog does not appear and I join the conversation.

Instead, the web browser client does not ask for login for the same room.

### Steps to reproduce:

1. Join the room in the web browser (`meet.jit.si`). Works as expected and no login is requested.
2. Join the same room in the Android app.
3. Raise the hand.
4. The username and password input dialog pops up. `Ok` gives connection error, `Cancel` returns to the room history.
5. Close app and repeat 2-4, a few times.
6. Eventually, you don't get 4. Instead: you join the conversation.
7. The conversation, microphone and camera work correctly.

### Expected behavior:

I am not asked to login, similar to the Web version.

Also, there may be a second issue here (maybe it's intentional, I'm not familiar with Jitsi's permission system) but what about an option in the login window to try to join as unregistered user? This would have worked around my issue.

### Actual behavior:

I am required to login.

### Server information:

The server is `meet.jit.si`.

### Client information:

- Browser / app version: 23.1.2 (currently the latest on F-droid)
- Operating System: Android 7.1

**Comment by saghul** [comment]
The latest version is 23.3.1, available on google play. Not sure when it will be available on f-droid.

All auth related work went on the 23.3 series, you should be checking that one out.

**Comment by opk12** [comment]
Updated to 23.3.1 from F-drod, appears solved. Thank you.
