### ISSUE TITLE
Don't join room as moderator

### ISSUE THREAD

**Issue by komainu8** [jitsi/jitsi-meet#13795]
### Description:

When I join room as moderator, Jitsi Meet send error message as below.

```
Sorry, you’re not allowed to join this call. Possible reasons: Invalid `nbf` value. The `context` object is missing from the payload
```

We can't meeting forever. Because anyone don't join as moderator. 

### Steps to reproduce:

1. We access https://meet.jit.si/
2. We write meeting name and push "Start meeting" button.
3. We push "Log-in" button in "Waitting for a moderator...".
4. Jitsi Meet send error message as below after log in.

   "Sorry, you’re not allowed to join this call. Possible reasons: Invalid `nbf` value. The `context` object is missing from the payload".

5. Anyone don't join as host in this room. Therefore, we don't start meeting.

### Expected behavior:

We log-in a room as moderator and other attendee can join the room.

### Actual behavior:

1. Jitsi Meet send error message as below after log in.

   "Sorry, you’re not allowed to join this call. Possible reasons: Invalid `nbf` value. The `context` object is missing from the payload".

2. Anyone don't join as host in this room. Therefore, we don't start meeting.

### Server information:

- Jitsi Meet version: Unknown
- Operating System: Unknown

### Client information:

- Browser / app version: Mozilla Firefox for Fedora 117.0(64 bit), Chromium 116.0.5845.96 (Official Build) Fedora Project (64 bit)
- Operating System: Fedora release 37 (Thirty Seven)

### Additional information:

This problem much more likely when we generate room  that the number of character of room name is 14 or more.

**Comment by saghul** [comment]
What login option did you choose?

Are you able to get ahold of the JWT (use the developer console) when the redirect happens?

@damencho Someone has reported the same in the community.

**Comment by komainu8** [comment]
Thank you for your comments.

I tried get JWT as below.

```
[{"name"=>"xxxx", "picture"=>"xxxxxx", "iss"=>"https://securetoken.google.com/meet-jit-si-66cbd", "aud"=>"meet-jit-si-66cbd", "auth_time"=>1693966693, "user_id"=>"xxxxxxx", "sub"=>"xxxxxx", "iat"=>1693988531, "exp"=>1693992131, "email"=>"xxxxx", "email_verified"=>true, "firebase"=>{"identities"=>{"google.com"=>["xxxxxx"], "email"=>["xxxxxxxx"]}, "sign_in_provider"=>"google.com"}}, {"alg"=>"RS256", "kid"=>"190ad118a940adc9f2f5376b35292fede8c2d0ee", "typ"=>"JWT"}]
```

Also,  https://community.jitsi.org/t/sorry-youre-not-allowed-to-join-this-call-possible-reasons-invalid-nbf-value-the-context-object-is-missing-from-the-payload/126467 smae as this issue.

**Comment by saghul** [comment]
Hum so no context not nbf?

Can you pl share the unparsed token with me please? saghul @ jitsi . org

**Comment by ljflores** [comment]
I've also experienced this problem.

**Comment by damencho** [comment]
@ljflores Do you see this every time? Are you experiencing this with Firefox only?

**Comment by damencho** [comment]
@saghul there was a problem with the shards on Thursday showing the same error, and I suspect it was because token_verification was enabled. I just checked all shards and everything seems fine.

**Comment by ljflores** [comment]
> @ljflores Do you see this every time? Are you experiencing this with Firefox only?

@damencho I had this happen in Firefox and Chrome.

**Comment by komainu8** [comment]
> Can you pl share the unparsed token with me please? saghul @ jitsi . org

Is it fine like that base64 encoded string?

**Comment by rotorri** [comment]
Hello. I've just met this message when created host at Korea, too : 
> Sorry, you're not allowed to join this call. Possible reasons: Invalid `nbf` value. The `context` object is missing from the payload.
> *Chrome build 116.0.5845.180 (64bit).*

I first discovered it during lunch (KST) yesterday, but maybe there was an issue like this before that.
Also other browser based on Chromium has same problem. that browser's build version is here :

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Whale/3.22.205.14 Safari/537.36

**Comment by saghul** [comment]
> > Can you pl share the unparsed token with me please? saghul @ jitsi . org
> 
> 
> 
> Is it fine like that base64 encoded string?

Yep the base64 encoded version is fine.

**Comment by komainu8** [comment]
@saghul 
Thank you for your reply.
I sent the unparsed token to your mail address.

**Comment by saghul** [comment]
Hum, I haven't received anything...

**Comment by Rpnpif** [comment]
Hello, same issue here with Firefox 102.15 on Debian.

**Comment by damencho** [comment]
This is now fixed. If it happens again, please grab that shard you are on and report it.

![Screenshot 2023-09-07 at 12 27 20 PM](https://github.com/jitsi/jitsi-meet/assets/3263098/c6983b21-54c2-4731-bcc3-7a03609aed93)

**Comment by komainu8** [comment]
Thank you for resolving the issue!

**Comment by pascuflow** [comment]
Getting the same issue on a self hosted using latest Jitsi, happened as soon as I enabled token auth, any idea when the fix will be public?

**Comment by saghul** [comment]
The original issue and fix only apply to the Firebase auth which is deployed in meet.jit.si, it does not apply to self-hosted installations.

Your problem is likely something else.
