### ISSUE TITLE
User authentication loads resources from gstatic.com even when not using google account to authenticate

### ISSUE THREAD

**Issue by gdt** [jitsi/jitsi-meet#13794]
### Description:

(First, I know there is a new requirement to authenticate to become a moderator, to disallow fully anonymous room creation, and I am not trying to argue against that.)

When creating a room and joining and clicking login, the browser is sent instructions to load from gstatic.com, and the page fails to function if that is blocked.  If one is going to use github which is the least problematic of the three options, that should work without loading anything from google.

### Steps to reproduce:

1. Go to https://meet.jit.si/
2. Click 'start meeting'.
3. Type a letter in 'name' and click join
4. Get the no-moderator screen and click login
5. At a URL like https://web-cdn.jitsi.net/auth-static/meet-jit-si/v6/signin.html#room=officialimplementationsweighappallingly&subdir=&skipPrejoin=true observe that it tries to load https://www.gstatic.com/firebasejs/ui/6.0.2/firebase-ui-auth.js
6. Ponder what google is going to do, if this is going to result in google having a record that a particular  github account on this IP address logged into this jitsi room, etc. Wonder how this possible information leak relates to 
https://jitsi.org/meet-jit-si-privacy/  (I'm not really sure, but it opens a lot of questions.)

### Expected behavior:

OAUTH flow is implemented with Free Software js served from the jitsi meet server.

### Actual behavior:

The page attempts to load proprietary js from google.
No screenshot, because surely this is manifest in the sources.

### Server information:

- observed on flagship instance

### Client information:

- firefox on NetBSD

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Your topic has nothing to do or fix in jitsi-meet and is only related to meet.jit.si.

For authentication on meet.jit.si we use firebase that's why it uses gstatic addresses for resources.
