### ISSUE TITLE
Display Remote Name: 'Fellow Jitster'

### ISSUE THREAD

**Issue by Shahzad062** [jitsi/jitsi-meet#13791]
i want change this Fellow Jitster text  how can i change this?

**Comment by ChrisPices** [comment]
never tryied but on the config.js file, there is a "defaultRemoteDisplayName" , try to change it.

![image](https://github.com/jitsi/jitsi-meet/assets/143708831/c6886bcb-a58f-4f97-9fb6-c8984a76f533)

**Comment by saghul** [comment]
Please don't open duplicate issues.

Pass it in the `config` prop: https://github.com/jitsi/jitsi-meet/blob/83e404266898bfb3f768892d0b6ab63146446da1/react-native-sdk/index.tsx#L39

**Comment by Shahzad062** [comment]
i m using vidit-me react native jitsi meet package its not getting config prop 
what should i do

**Comment by saghul** [comment]
I have no idea what that is. If you are using our plugin then our docs apply, else ask the maintainer of the plugin you are suing.
