### ISSUE TITLE
Cross Platform Native Communication Issue (Android)

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13799]
**Note: Native communication between flutter and kotlin.**

**Description:** 
I made a two function i.e. joinJitsiMeeting to join jitsi meet & retrieveJitsiParticipantInfo metthod to retrieve participant list. on koltin.

**What was my issues:**
From flutter, after triggering **joinJitsiMeeting** method **retrieveJitsiParticipantInfo** method was triggered but does not execute. And did not broad cast participant info. Why?

**kotlin code (on main activity):**
    private var eventStreamHandler = JitsiMeetEventStreamHandler.instance
    private lateinit var eventChannel: EventChannel

"joinJitsiMeeting" -> {
    val params = call.arguments as Map<*, *>
    val userInfo = JitsiMeetUserInfo().apply {
        this.displayName = "${params["userName"]}"
        this.email = "${params["email"]}"
    }

    val defaultOptions = JitsiMeetConferenceOptions.Builder()
        .setServerURL(URL("${params["serverURL"]}"))
        .setFeatureFlag("welcomepage.enabled", false)
        .setFeatureFlag("resolution", "${params["resolution"]}").build()
    JitsiMeet.setDefaultConferenceOptions(defaultOptions)
    val options = JitsiMeetConferenceOptions.Builder()
        .setRoom("${params["meetingId"]}") // Settings for audio and video
        .setAudioMuted(true).setVideoMuted(true).build()

    JitsiMeetActivity.launch(this, options)
    eventChannel.setStreamHandler(JitsiMeetEventStreamHandler.instance)

}
"retrieveJitsiParticipantInfo" -> {
    val retrieveParticipantsInfoIntent =
        Intent(BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED.action);
    LocalBroadcastManager.getInstance(this)
        .sendBroadcast(retrieveParticipantsInfoIntent)
    result.success("Successfully retrieved participants info")
}

  private fun onBroadcastReceived(intent: Intent?) {
        if (intent != null) {
            val event = BroadcastEvent(intent)
            val data = event.data
            println("jitsi event: ${event}, ${intent}")
            flutterChannel.invokeMethod(
                "jitsiMeetingStatus", "{\"eventType\":${event.type}, \"data\":$data\"}"
            )

            when (event.type!!) {
                BroadcastEvent.Type.CONFERENCE_JOINED -> eventStreamHandler.onConferenceJoined(data)
                BroadcastEvent.Type.CONFERENCE_TERMINATED -> eventStreamHandler.onConferenceTerminated(
                    data
                )
                BroadcastEvent.Type.CONFERENCE_WILL_JOIN -> eventStreamHandler.onConferenceWillJoin(
                    data
                )
                BroadcastEvent.Type.AUDIO_MUTED_CHANGED -> eventStreamHandler.onAudioMutedChanged(
                    data
                )
                BroadcastEvent.Type.PARTICIPANT_JOINED -> eventStreamHandler.onParticipantJoined(
                    data
                )
                BroadcastEvent.Type.PARTICIPANT_LEFT -> eventStreamHandler.onParticipantLeft(data)
                BroadcastEvent.Type.ENDPOINT_TEXT_MESSAGE_RECEIVED -> eventStreamHandler.onEndpointTextMessageReceived(
                    data
                )
                BroadcastEvent.Type.SCREEN_SHARE_TOGGLED -> eventStreamHandler.onScreenShareToggled(
                    data
                )
                BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED -> eventStreamHandler.participantsInfoRetrieved(
                    data
                )
                BroadcastEvent.Type.CHAT_MESSAGE_RECEIVED -> {
                    eventStreamHandler.onChatMessageReceived(
                        data
                    );
                }
                BroadcastEvent.Type.CHAT_TOGGLED -> eventStreamHandler.onChatToggled(data)
                BroadcastEvent.Type.VIDEO_MUTED_CHANGED -> eventStreamHandler.onVideoMutedChanged(
                    data
                )
                BroadcastEvent.Type.READY_TO_CLOSE -> eventStreamHandler.onClosed()
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
  

        val intentFilter = IntentFilter()
        intentFilter.addAction(BroadcastEvent.Type.CONFERENCE_JOINED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.READY_TO_CLOSE.getAction())
        intentFilter.addAction(BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.CHAT_TOGGLED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.AUDIO_MUTED_CHANGED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.CHAT_MESSAGE_RECEIVED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.CHAT_TOGGLED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.CONFERENCE_TERMINATED.getAction())
        intentFilter.addAction(BroadcastEvent.Type.CONFERENCE_WILL_JOIN.getAction())
        intentFilter.addAction(BroadcastEvent.Type.PARTICIPANT_LEFT.getAction())
        intentFilter.addAction(BroadcastEvent.Type.VIDEO_MUTED_CHANGED.getAction())
        LocalBroadcastManager.getInstance(this).registerReceiver(broadcastReceiver, intentFilter)

       }

**Comment by saghul** [comment]
Are you using our Flutter SDK?

**Comment by JagaranMaharjan** [comment]
@saghul No, I am not using your Flutter SDK. It's totally customized by my self.

**Comment by saghul** [comment]
> "retrieveJitsiParticipantInfo" -> {
> val retrieveParticipantsInfoIntent =
> Intent(BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED.action);
> LocalBroadcastManager.getInstance(this)
> .sendBroadcast(retrieveParticipantsInfoIntent)
> result.success("Successfully retrieved participants info")
> }

This is not how you should request it. Check this out: https://github.com/jitsi/jitsi-meet/blob/463c823d3bee964e4258c8b18e7ea6fc11a62d01/android/sdk/src/main/java/org/jitsi/meet/sdk/ParticipantsService.java#L51

**Comment by saghul** [comment]
Sorry you'll need to debug why it's not working for you, since you are working a custom environment, or provide us a with a sample using one of our SDKs which exhibits the problem.

**Comment by JagaranMaharjan** [comment]
@saghul sure I will provide you a sample repository of my custom environment

**Comment by JagaranMaharjan** [comment]
private fun onBroadcastReceived(intent: Intent?) {
        if (intent != null) {
            val event = BroadcastEvent(intent)
            val data = event.data
            println("jitsi event: ${event}, ${intent}")
            flutterChannel.invokeMethod(
                "jitsiMeetingStatus", "{\"eventType\":${event.type}, \"data\":$data\"}"
            )

            when (event.type!!) {
                BroadcastEvent.Type.CONFERENCE_JOINED -> eventStreamHandler.onConferenceJoined(data)
                BroadcastEvent.Type.CONFERENCE_TERMINATED -> eventStreamHandler.onConferenceTerminated(
                    data
                )
                BroadcastEvent.Type.CONFERENCE_WILL_JOIN -> eventStreamHandler.onConferenceWillJoin(
                    data
                )
                BroadcastEvent.Type.AUDIO_MUTED_CHANGED -> eventStreamHandler.onAudioMutedChanged(
                    data
                )
                BroadcastEvent.Type.PARTICIPANT_JOINED -> eventStreamHandler.onParticipantJoined(
                    data
                )
                BroadcastEvent.Type.PARTICIPANT_LEFT -> eventStreamHandler.onParticipantLeft(data)
                BroadcastEvent.Type.ENDPOINT_TEXT_MESSAGE_RECEIVED -> eventStreamHandler.onEndpointTextMessageReceived(
                    data
                )
                BroadcastEvent.Type.SCREEN_SHARE_TOGGLED -> eventStreamHandler.onScreenShareToggled(
                    data
                )
                BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED -> eventStreamHandler.participantsInfoRetrieved(
                    data
                )
                BroadcastEvent.Type.CHAT_MESSAGE_RECEIVED -> {
                    **val retrieveParticipantsInfoIntent =
                        Intent(BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED.action);
                    LocalBroadcastManager.getInstance(this)
                        .sendBroadcast(retrieveParticipantsInfoIntent)**
                    eventStreamHandler.onChatMessageReceived(
                        data
                    );
                }
                BroadcastEvent.Type.CHAT_TOGGLED -> eventStreamHandler.onChatToggled(data)
                BroadcastEvent.Type.VIDEO_MUTED_CHANGED -> eventStreamHandler.onVideoMutedChanged(
                    data
                )
                BroadcastEvent.Type.READY_TO_CLOSE -> eventStreamHandler.onClosed()
            }
        }
    }


@saghul I added broadcast action to retrieve participant info in when chat message is recieved. 
Broadcast Action event was triggered [PARTICIPANTS_INFO_RETRIEVED] with empty data and contains error message in console as ParticipantsServiceerror parsing participantsList. This issue aries on my sdk as well as on your sdk too.

I build custom sdk for android from mobile-23.3 branch

<img width="1320" alt="Screenshot 2023-09-08 at 20 45 27" src="https://github.com/jitsi/jitsi-meet/assets/60642304/c7c3b4e7-b48a-4d99-8fc9-19325805a974">
