### ISSUE TITLE
[RNSDK] Android: "No audio devices available" 

### ISSUE THREAD

**Issue by JijoBose** [jitsi/jitsi-meet#13800]
### Description:

Using the React Native SDK in Android, 
When we select the "audio" (speaker icon) from the top toolbar, it shows "No audio devices available".

### Steps to reproduce:

1. Click on the Top Toolbar icon
2. I'm getting the bottom sheet with No audio devices available

### Expected behavior:

2. Expected to show the "speaker" option

### Actual behavior:

<img src="https://github.com/jitsi/jitsi-meet/assets/13100108/31211d8c-0a5f-4361-bcb9-4567b04f224a" height="600px" />

### Client information:

- Browser/app version: `stable/jitsi-meet_8922`
- Operating System: `Android`

### Additional information 

- Tested the same with the React Native Sample project and still seeing the same issue

**Comment by saghul** [comment]
Can you please grab a logcat output?

**Comment by JijoBose** [comment]
@saghul Here is the logcat output


[Info] 09-07 16:03:11.748  5919  5979 I ReactNativeJS: '2023-09-07T10:33:11.748Z', '[modules/xmpp/xmpp.js]', 'P2P STUN servers: ', [ { urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443' } ]


[Info] 09-07 16:03:11.763  5919  5979 D ReactNativeJS: '2023-09-07T10:33:11.763Z', '[modules/xmpp/xmpp.js]', 'Source-name signaling is enabled'


[Info] 09-07 16:03:11.765  5919  5979 D ReactNativeJS: '2023-09-07T10:33:11.765Z', '[modules/xmpp/xmpp.js]', 'Receiving multiple video streams is enabled'


[Info] 09-07 16:03:11.773  5919  5979 I ReactNativeJS: '2023-09-07T10:33:11.772Z', '[modules/xmpp/xmpp.js]', '(TIME) Strophe connecting:\t', 161261.395252


[Info] 09-07 16:03:12.007  5919  5979 I ReactNativeJS: '2023-09-07T10:33:12.007Z', '[modules/RTC/RTCUtils.js]', 'Got media constraints: ', '{"video":false,"audio":{"autoGainControl":true,"echoCancellation":true,"noiseSuppression":true}}'


[Info] 09-07 16:03:12.101  5919  5919 I ReactNative: [GESTURE HANDLER] Gesture handler is already enabled for a parent view


[Info] 09-07 16:03:12.210  5919  5979 W ReactNativeJS: '2023-09-07T10:33:12.209Z', '[features/calendar-sync]', 'Calendar access not granted.'


[Info] 09-07 16:03:12.243  5919  5979 D ReactNativeJS: '2023-09-07T10:33:12.240Z', '[modules/RTC/RTCUtils.js]', 'Available devices: ', [ { kind: 'videoinput',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     label: '0',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     groupId: '',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     deviceId: '0',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     facing: 'environment' },
09-07 16:03:12.243  5919  5979 D ReactNativeJS:   { kind: 'videoinput',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     label: '1',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     groupId: '',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     deviceId: '1',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     facing: 'front' },
09-07 16:03:12.243  5919  5979 D ReactNativeJS:   { kind: 'audioinput',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     label: 'Audio',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     groupId: '',
09-07 16:03:12.243  5919  5979 D ReactNativeJS:     deviceId: 'audio-1' } ]


[Info] 09-07 16:03:12.348  5919  5979 I ReactNativeJS: '2023-09-07T10:33:12.348Z', '[features/base/redux]', 'redux state persisted. 6ead46c5cc453a429d07fde7eac5bf41 -> 425cd47fc2d9745a964d9d4a7a9996fe'


[Info] 09-07 16:03:12.615  5919  5979 I ReactNativeJS: '2023-09-07T10:33:12.615Z', '[modules/RTC/RTCUtils.js]', 'onUserMediaSuccess'
09-07 16:03:12.616  5919  5979 D ReactNativeJS: '2023-09-07T10:33:12.616Z', '[modules/RTC/JitsiLocalTrack.js]', 'Setting new MSID: 5e1122e8-60e8-cd61-44b2-5e796c18ffdf 53e7a2f5-89ac-40e8-9b42-fded78eefbd4 on LocalTrack[undefined,audio]'


[Info] 09-07 16:03:12.667  5919  5979 I ReactNativeJS: '2023-09-07T10:33:12.667Z', '[features/base/media]', 'Sync audio track muted state to muted'
09-07 16:03:12.668  5919  5979 I ReactNativeJS: '2023-09-07T10:33:12.667Z', '[modules/RTC/JitsiLocalTrack.js]', 'Mute LocalTrack[2,audio]: true'


[Info] 09-07 16:03:14.372  5919  5979 W ReactNativeJS: '2023-09-07T10:33:14.371Z', '[modules/xmpp/XmppConnection.js]', 'Stream resume enabled, but WebSockets are not enabled'


[Info] 09-07 16:03:14.375  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.375Z', '[modules/xmpp/strophe.ping.js]', 'XMPP pings will be sent every 10000 ms'


[Info] 09-07 16:03:14.376  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.375Z', '[modules/xmpp/xmpp.js]', '(TIME) Strophe connected:\t', 163864.637094


[Info] 09-07 16:03:14.378  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.377Z', '[modules/xmpp/xmpp.js]', 'My Jabber ID: ff87c63a-813e-4f41-862c-1b97d7fe8781@meet.alpha.oci.ooma.dev/iDKFbMt7njcC'


[Info] 09-07 16:03:14.420  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.420Z', '[modules/RTC/CodecSelection.js]', 'Codec preference order for jvb connection is vp9,vp8'


[Info] 09-07 16:03:14.423  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.421Z', '[modules/RTC/CodecSelection.js]', 'Codec preference order for p2p connection is vp8,vp9'


[Info] 09-07 16:03:14.425  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.425Z', '[modules/xmpp/xmpp.js]', 'JID ff87c63a-813e-4f41-862c-1b97d7fe8781@meet.alpha.oci.ooma.dev/iDKFbMt7njcC using MUC nickname ff87c63a'


[Info] 09-07 16:03:14.433  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.432Z', '[modules/xmpp/moderator.js]', 'Using xmpp for conference requests.'


[Info] 09-07 16:03:14.495  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.494Z', '[modules/statistics/AvgRTPStatsReporter.js]', 'Avg RTP stats will be calculated every 15 samples'


[Info] 09-07 16:03:14.497  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.496Z', '[JitsiConference.js]', 'backToP2PDelay: 5'


[Info] 09-07 16:03:14.497  5919  5979 D ReactNativeJS: '2023-09-07T10:33:14.497Z', '[modules/videosipgw/VideoSIPGW.js]', 'creating VideoSIPGW'


[Info] 09-07 16:03:14.503  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.500Z', '[JitsiConference.js]', '_doReplaceTrack - no JVB JingleSession'


[Info] 09-07 16:03:14.511  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.508Z', '[JitsiConference.js]', '_doReplaceTrack - no P2P JingleSession'


[Info] 09-07 16:03:14.609  5919  5979 I ReactNativeJS: '2023-09-07T10:33:14.607Z', '[modules/xmpp/moderator.js]', 'Sending conference request over XMPP to focus.meet.alpha.oci.ooma.dev'


[Info] 09-07 16:03:15.320  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.320Z', '[modules/xmpp/moderator.js]', 'Adding focus JID: focus@auth.meet.alpha.oci.ooma.dev'


[Info] 09-07 16:03:15.321  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.320Z', '[modules/xmpp/moderator.js]', 'Authentication enabled: false'
09-07 16:03:15.321  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.321Z', '[modules/xmpp/moderator.js]', 'External authentication enabled: false'


[Info] 09-07 16:03:15.341  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.340Z', '[modules/xmpp/moderator.js]', 'Sip gateway enabled: true'


[Info] 09-07 16:03:15.341  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.341Z', '[modules/xmpp/moderator.js]', 'Conference-request successful, ready to join the MUC.'


[Info] 09-07 16:03:15.674  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.673Z', '[modules/version/ComponentsVersions.js]', 'Got focus version: 1.0.996'


[Info] 09-07 16:03:15.694  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.694Z', '[JitsiConference.js]', 'Audio unmute permissions set by Jicofo to false'


[Info] 09-07 16:03:15.713  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.713Z', '[JitsiConference.js]', 'Video unmute permissions set by Jicofo to false'


[Info] 09-07 16:03:15.844  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.844Z', '[features/video-quality]', 'Setting sender resolution to 480'


[Info] 09-07 16:03:15.884  5919  5979 I ReactNativeJS: '2023-09-07T10:33:15.883Z', '[features/video-quality]', 'Configured preferred receiver video frame height to: 480'


[Info] 09-07 16:03:16.162  5919  5979 I ReactNativeJS: '2023-09-07T10:33:16.162Z', '[JitsiConference.js]', 'Auto P2P disabled'

**Comment by saghul** [comment]
I don't see anything strange there.

@Calinteodor can you try to repro?

**Comment by Calinteodor** [comment]
> I don't see anything strange there.
> 
> 
> 
> @Calinteodor can you try to repro?

Cannot repro on latest beta.https://github.com/jitsi/jitsi-meet/assets/26413496/8df92d64-32d8-4187-aa2f-76a2b434b124

**Comment by JijoBose** [comment]
Could you use the react native code from the sample here.
https://github.com/jitsi/jitsi-meet-sdk-samples

I am able to see the speaker when running it in Flutter  but not in React Native

**Comment by JijoBose** [comment]
I am using `stable/jitsi-meet_8922`

**Comment by saghul** [comment]
> I am using `stable/jitsi-meet_8922`

That is not a valid RN SDK release. Please use a released version, the latest is 0.3.0.

**Comment by JijoBose** [comment]
Yes, I generated the RNSDK using the `node prepare_sdk.js` after customizing the icon changes in Jitsi meet  from the latest stable release `stable/jitsi-meet_8922`

Also I tried the sample https://github.com/jitsi/jitsi-meet-sdk-samples which uses `"@jitsi/react-native-sdk": "0.3.0"`

I'm still getting "No audio devices available" in the options in both versions.

**Comment by saghul** [comment]
> > I don't see anything strange there.
> > @Calinteodor can you try to repro?
> 
> Cannot repro on latest beta.https://github.com/jitsi/jitsi-meet/assets/26413496/8df92d64-32d8-4187-aa2f-76a2b434b124

That was iOS wan't it? The issue seems to affect Android.

**Comment by Calinteodor** [comment]
> > > I don't see anything strange there.
> 
> > > @Calinteodor can you try to repro?
> 
> > 
> 
> > Cannot repro on latest beta.https://github.com/jitsi/jitsi-meet/assets/26413496/8df92d64-32d8-4187-aa2f-76a2b434b124
> 
> 
> 
> That was iOS wan't it? The issue seems to affect Android.

Will take a look.

**Comment by JijoBose** [comment]
Were you able to look into it ?

**Comment by edritech93** [comment]
same issue for me

**Comment by saghul** [comment]
We haven't been able to look into this yet.

**Comment by JijoBose** [comment]
❓

**Comment by saghul** [comment]
When there is an update, we'll post it here. We haven't been able to look into this yet.

**Comment by Anfieldd** [comment]
Hi guys! It seems like I have found the problem related to this one. I hear very quiet audio from the other side on my Android device(IOS works fine).

**Steps to reproduce**
1. Start jitsi react-native sdk sample and join the conference on Android.
2. On the other side join the conference from web or mobile.
3. Unmute and say something.
4. The android user will hear quiet audio.

The mobile app works fine, it's only sdk problem

**Comment by saghul** [comment]
Not sure how that is related. Do you see audio devices in the list?

**Comment by Anfieldd** [comment]
> Not sure how that is related. Do you see audio devices in the list?

No, I don't. I see this message "No audio devices available"

**Comment by saghul** [comment]
Can you please try to add the "call-integration.enabled" to `true`  and see if that makes a difference?

**Comment by JijoBose** [comment]
Yes, I did set the "call-integration.enabled" to true, and I still see "No Audio devices available"


```
    <JitsiMeeting
      style={{flex: 1}}
      flags={{
        'call-integration.enabled': true,
      }}
    />
```

**Comment by saghul** [comment]
🤦  Sorry I meant the opposite, set it to `false`

**Comment by JijoBose** [comment]
Yes, I'm able to see the options now after setting it to false.

![Screenshot_20230922-212252](https://github.com/jitsi/jitsi-meet/assets/13100108/46944873-fed7-434a-81c5-184d10823eb0)

**Comment by JijoBose** [comment]
Could you explain what exactly disabling this feature flag does?
Does it break any existing features provided by Jitsi?
@saghul

**Comment by saghul** [comment]
It's the integration with Android's ConnectionService API.

In principle it allows integrating Jitsi with other calling applications, but in practice we saw many quirks (it's vendor dependent unfortunately) so our app has had it disabled for a couple of years.

If / when we enable it ourselves we can re-enable it, but as it stands it's better if users run the same way we do.

**Comment by JijoBose** [comment]
Thanks for the details.
This solves the issue with audio devices 😄

**Comment by saghul** [comment]
Fix: https://github.com/jitsi/jitsi-meet/pull/13866
