### ISSUE TITLE
"android.audio-focus.disabled"  Does not work on 12 and 11 android

### ISSUE THREAD

**Issue by Ewrei** [jitsi/jitsi-meet#13803]
### **Description:**

I am using JitsiView and WebView on the same screen.
I need a WebView to display video and audio workouts.
There is a problem, when I connect to a JitsiView room, my WebView stops working audio or video, on startup the video or audio it stops right away.

### **Steps to reproduce:**
1.  Create layout where have WebView and JitsiView.
2. Add Initialization JistiView in your activity/fragment 

```
   val options: JitsiMeetConferenceOptions = JitsiMeetConferenceOptions.Builder()
            .setServerURL(URL(serverUrl))
            .setRoom(roomId)
            .setToken(token)
            .setVideoMuted(false)
            .setAudioMuted(false)
            .setAudioOnly(false)
            .setFeatureFlag("toolbox.enabled", true)
            .setFeatureFlag("toolbox.alwaysVisible", false)
            .setFeatureFlag("android.audio-focus.disabled", true)
            .setFeatureFlag("audio-mute.enabled", true)
            .setFeatureFlag("video-mute.enabled", true)
            .setFeatureFlag("video-share.enabled", true)
            .setFeatureFlag("invite.enabled", false)
            .setFeatureFlag("meeting-name.enabled", false)
            .setFeatureFlag("prejoinpage.enabled", false)
            .setFeatureFlag("disableH264", true)
            .setFeatureFlag("invite.enabled", false)
            .setFeatureFlag("mobileCodecPreferenceOrder", "VP9")
            .build()

        dataBinding.remoteVideoView.join(options)
```

3. Add initialization Webview and loud url which have video or audio
```
    dataBinding.webView.settings.javaScriptEnabled = true
    dataBinding.webView.settings.domStorageEnabled = true
    dataBinding.webView.settings.mediaPlaybackRequiresUserGesture = false
    dataBinding.webView.webChromeClient = object : WebChromeClient() {}
    dataBinding.webView.webViewClient = object : WebViewClient() {}I found solutions to use
    setFeatureFlag("android.audio-focus.disabled", true)
```

4.  Run on android 12 or below

### **Expected behavior:**
When starting a video or audio in a WebView, it immediately stops

### **Actual behavior:**
Wideo and audio works in WebView without stopping

### **Client information:**
`targetSdkVersion: 33`
Jitsi version:` org.jitsi.react:jitsi-meet-sdk:8.3.1`

### **Additional information**
If I added flag in options setFeatureFlag("android.audio-focus.disabled", true) then on 13 android everything works correctly.
As I understand it, this is due to the fact that JitsiView takes over the audio stream after all ((

**Comment by dimaBazhan** [comment]
Maybe someone knows the solution because I have the same problem

**Comment by saghul** [comment]
The flag is called `audio-focus.disabled` not `android.audio-focus.disabled` it got renamed 2 years ago: https://github.com/jitsi/jitsi-meet/commit/751644db16c18c195892afdb8eec142dc548bef0

**Comment by saghul** [comment]
> `targetSdkVersion: 33`
> Jitsi version:` org.jitsi.react:jitsi-meet-sdk:8.3.1`

Note that we don't officially support target API 33 until 8.4.0, coming soon.

**Comment by Ewrei** [comment]
@saghulI tried using audio-focus.disabled, but unfortunately it didn't help.
I'll wait for the new version **8.4.0**

Do you have any ideas where to look to solve this problem?

**Comment by saghul** [comment]
Do you see the audio mode changing on `adb logcat` ?

**Comment by Ewrei** [comment]
@saghul
When I enter the room
`dispatching onAudioFocusChange(-2) to android.media.AudioManager@69ce1cforg.chromium.content.browser.AudioFocusDelegate@2b3675c`

When I leave the room, I get 
`dispatching onAudioFocusChange(1) to android.media.AudioManager@69ce1cforg.chromium.content.browser.AudioFocusDelegate@2b3675c`

When I am in the room and try to start the video, I see in the logs that the audio start process is starting, but less than a second passes, the video stop process begins immediately.

I wrote above that it works correctly on Android 13, I was wrong, for some reason it stopped working, there were no changes in the code. At the same time, I was able to get it to work for 10-20 minutes on Android 12. Unfortunately, this only happened twice and I was not able to find out what caused it and have time to take the logs.

I created a test project where you can quickly reproduce this situation, you just need to add a room

https://github.com/Ewrei/TestJitsiVideoRoom
