### ISSUE TITLE
Android APP cannot enter domain name conferences for mirror deployment

### ISSUE THREAD

**Issue by 414647311** [jitsi/jitsi-meet#13809]
After modifying the domain name address and entering the conference number, an error message will pop up

**Comment by saghul** [comment]
I have no idea what you mean, sorry. Can you please provide some examples?

**Comment by 414647311** [comment]
I changed the Android default server URL, but entering the room will prompt an error .
The edit file is settings/constants.ts

**Comment by 414647311** [comment]
![4373d6a33a201748c16f8e1382f9bef](https://github.com/jitsi/jitsi-meet/assets/50956624/7028802b-7a7d-472f-8e8d-a2097fb38cba)
This is a pop-up error when entering a room.
I would like to ask where is the problem.

**Comment by 414647311** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/50956624/fb2cc908-a5e6-44f5-90ab-97462db4755d)
This is what I modified server URL.

**Comment by saghul** [comment]
That error is expected due to a reference cycle, but you can ignore it, it only shows up during development, not production / release builds.

**Comment by 414647311** [comment]
![a2fe5eea5e7b1bd39e9d13e3380b6b5](https://github.com/jitsi/jitsi-meet/assets/50956624/190d2800-7920-49e8-b3d7-b05ce4da1054)
What about this mistake

**Comment by 414647311** [comment]
Unfortunately, something went wrong

**Comment by 414647311** [comment]
I modify the server URL ，Failed to join the meeting.

**Comment by saghul** [comment]
Does your server have the proper certificate chain and is config.js syntactically correct?

**Comment by 414647311** [comment]
<img width="422" alt="5fa7d278a2706da6bdecc19d8d9d471" src="https://github.com/jitsi/jitsi-meet/assets/50956624/4b53ebd9-113c-4086-a18a-0d955b75a6ab">
Do these addresses need to be changed？

**Comment by saghul** [comment]
THat looks ok, but I could help you better if you shared the URL of your deployment. ALso, check the certificate chain.

**Comment by 414647311** [comment]
https://jitis.meet.gxdly.net:8443/

**Comment by saghul** [comment]
You need a valid certificate or the mobile apps will refuse to load the meeting.
