### ISSUE TITLE
Mobile Landscape Mode Displays 20% Black Screen During Screen Share by Host in Meetings

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#13819]
In landscape mode on mobile devices during a meeting, there is a black area covering 20% of the screen, not allowing the shared content by the host to fully display.

![viber_image_2023-09-11_21-20-01-568](https://github.com/jitsi/jitsi-meet/assets/60642304/3c3ae2e2-0e30-4cce-b9ef-1e1ec88c6482)

**Comment by saghul** [comment]
The mobile apps maintain the aspect ratio of the desktop track.

You pan and pinch to zoom to position it to your liking.
