### ISSUE TITLE
No camera/microphone in google-chrome when authentication enabled without guest domain

### ISSUE THREAD

**Issue by stephane-chazelas** [jitsi/jitsi-meet#13815]
### Description:

When configuring authentication in my instance, in my case LDAP using the "cyrus" module as per https://jitsi.github.io/handbook/docs/devops-guide/ldap-authentication/, without a guest subdomain enabled, in google-chrome, upon starting or joining a meeting (upon which authentication is prompted as expected and works OK), camera and microphone icons remain "greyed out" with a spinning wheel spinning indefinitely.

![Screenshot from 2023-09-09 10-50-10](https://github.com/jitsi/jitsi-meet/assets/1226347/32ee4baf-e484-4c5f-91a0-f55038088494)

Hovering over them gives "connecting your camera" / "connecting your microphone". The camera LED on the laptop turns on so it's not about accessing the camera. Camera works fine in the settings.

It works fine in Firefox. It also works fine if I disable authentication or enable a guest subdomain (as per https://jitsi.github.io/handbook/docs/devops-guide/secure-domain/), though neither is an option for me as users should not be able to join a meeting without authenticating in my case.

### Steps to reproduce:

1. configure LDAP authentication as per https://jitsi.github.io/handbook/docs/devops-guide/ldap-authentication/
2. Start a meeting in google-chrome

### Expected behavior:

Same as in Firefox with microphone and camera working as expected during meetings.

### Actual behavior:

Camera and microphone icons remain "greyed out" with a spinning wheel spinning indefinitely.

### Server information:

- Jitsi Meet version: 2.0.8922
- Operating System: Ubuntu 20.04

```
$ aptitude -q search -F '%v %p' '~S~i (~m jitsi | prosody)'
1.0-1048-1     jicofo
1.0.1          jitsi-archive-keyring
2.0.8922-1     jitsi-meet
1.0.7499-1     jitsi-meet-prosody
1.0.7499-1     jitsi-meet-web
1.0.7499-1     jitsi-meet-web-config
2.3-41-ga8d8a7 jitsi-videobridge2
0.12.4-1~focal prosody
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal


### Client information:

- Browser / app version: google-chrome-stable 116.0.5845.179-1
- Operating System: Ubuntu 20.04

**Comment by saghul** [comment]
Can you please share your browser console logs?

**Comment by stephane-chazelas** [comment]
Thanks Saúl. Here are console logs. That's from the start of a new incognito window, going to https://video-bridge.example.com, starting a new meeting room and authenticating.

[video-bridge.example.com-1694261144536.log](https://github.com/jitsi/jitsi-meet/files/12565701/video-bridge.example.com-1694261144536.log)

**Comment by stephane-chazelas** [comment]
For comparison, here are console logs from the same browser when the guest domain is enabled:

[video-bridge.example.com-guest-domain-1694266183825.log](https://github.com/jitsi/jitsi-meet/files/12565911/video-bridge.example.com-guest-domain-1694266183825.log)

And a console log for a working firefox when guest domain is not enabled:

[console-export-2023-9-9_14-35-12.txt](https://github.com/jitsi/jitsi-meet/files/12565913/console-export-2023-9-9_14-35-12.txt)

**Comment by damencho** [comment]
When you are disabling guest domain you remove it from prosody config and from config.js and restart prosody?

**Comment by stephane-chazelas** [comment]
> When you are disabling guest domain you remove it from prosody config and from config.js and restart prosody?

Initially, the guest domain was not configured in prosody and google-chrome wasn't working. I then tried configuring the guest domain to see if that helped and that did. The console logs above are  with only guestauthdomain removed from config.js.

Here is another console log from a failing chrome with the guest subdomain fully disabled by disabling in prosody, config.js and removing the authentication section in jicofo.conf.

[video-bridge.example.com-guest-fully-disabled-1694269183286.log](https://github.com/jitsi/jitsi-meet/files/12566006/video-bridge.example.com-guest-fully-disabled-1694269183286.log)


AFAICT, except for timestamp some unique ids and the name of the meeting room, that's the same as in the first log I sent above.

**Comment by eggepegge** [comment]
I see a similar problem. Unfortunately I have no firefox available to test with. Problem occur with Chrome and Edge.

Running on Ubuntu 22.04 LTS. No guest domain active, authentication done via saslauthd and cyrus. Camera is working in the camera settings but mic and cam buttons are grey and spinning saying "connecting your microphone/camera"

```
ii  jicofo                                 1.0-1048-1                              all          JItsi Meet COnference FOcus
ii  jitsi-meet-prosody                     1.0.7499-1                              all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                         1.0.7499-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                  1.0.7499-1                              all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                     2.3-41-ga8d8a786-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  prosody                                0.12.4-1~jammy1                         amd64        Lightweight Jabber/XMPP server
```

If I downgrade jitsi-meet-web to 1.0.7322-1 and keep all others as above, it starts to work as it should again by just reconnecting to the meeting in the browser. Nothing need to be restarted on the server end.

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

```

**Comment by VennStone** [comment]
Upgraded our Jiti server today and ran across the same issue. Greyed out icons with a spinning wheel with Google Chrome and Chromium. Works fine in Firefox. 

I have authentication enabled and no guest domain. 

Jitsi Meet version: 2.0.8922-2
Operating System: Debian 10

**Comment by d-shiri** [comment]
after upgrading our Jitsi server we ran into a problem as well. 
`~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
~$ dpkg -l | grep jitsi-meet
ii  jitsi-meet                      2.0.8922-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.7499-1                              all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.7499-1                              all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.7499-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.7499-1                              all          Configuration for web serving of Jitsi Meet
`

**Comment by saghul** [comment]
> Upgraded our Jiti server today and ran across the same issue. Greyed out icons with a spinning wheel with Google Chrome and Chromium. Works fine in Firefox.
> 
> I have authentication enabled and no guest domain.
> 
> Jitsi Meet version: 2.0.8922-2 Operating System: Debian 10

What type of auth did you enable?

**Comment by d-shiri** [comment]
> > Upgraded our Jiti server today and ran across the same issue. Greyed out icons with a spinning wheel with Google Chrome and Chromium. Works fine in Firefox.
> > I have authentication enabled and no guest domain.
> > Jitsi Meet version: 2.0.8922-2 Operating System: Debian 10
> 
> What type of auth did you enable?
this is what I found in /etc/prosody/conf.avail/meet.mysite.app.cfg.lua
if you mean sth else, please let me know how to collect that info.
```
VirtualHost "auth.meet.mysite.app"
    ssl = {
        key = "/etc/prosody/certs/auth.meet.mysite.app.key";
        certificate = "/etc/prosody/certs/auth.meet.mysite.app.crt";
    }
    modules_enabled = {
        "limits_exception";
    }
    authentication = "internal_hashed"
------------------------------------------------
in another part of the file was
VirtualHost "meet.drposture.app"
    authentication = "internal_plain" --"jitsi-anonymous" -- do not delete me


```

**Comment by saghul** [comment]
Can you please share the entire Prosody, Jicofo and config.js? I suspect some kind of config issue. I just tried the latest stable Docker setup and it works just like before, when no guests are allowed.

**Comment by VennStone** [comment]
> Can you please share the entire Prosody, Jicofo and config.js? I suspect some kind of config issue. I just tried the latest stable Docker setup and it works just like before, when no guests are allowed.

Here we go. I very well may have something misconfigured and the latest update exposed it. 

[meet.website.bob.cfg.lua.txt](https://github.com/jitsi/jitsi-meet/files/12612341/meet.website.bob.cfg.lua.txt)
[meet.website.bob-config.js.txt](https://github.com/jitsi/jitsi-meet/files/12612342/meet.website.bob-config.js.txt)
[sip-communicator.properties.txt](https://github.com/jitsi/jitsi-meet/files/12612343/sip-communicator.properties.txt)

**Comment by saghul** [comment]
> > Can you please share the entire Prosody, Jicofo and config.js? I suspect some kind of config issue. I just tried the latest stable Docker setup and it works just like before, when no guests are allowed.
> 
> Here we go. I very well may have something misconfigured and the latest update exposed it.
> 
> [meet.website.bob.cfg.lua.txt](https://github.com/jitsi/jitsi-meet/files/12612341/meet.website.bob.cfg.lua.txt) [meet.website.bob-config.js.txt](https://github.com/jitsi/jitsi-meet/files/12612342/meet.website.bob-config.js.txt) [sip-communicator.properties.txt](https://github.com/jitsi/jitsi-meet/files/12612343/sip-communicator.properties.txt)

A couple of issues I noticed:

- You still have the guest virtual host defined in Prosody
- authdomain is commented out in config.js
- jicofo is ok

**Comment by VennStone** [comment]
> > > Can you please share the entire Prosody, Jicofo and config.js? I suspect some kind of config issue. I just tried the latest stable Docker setup and it works just like before, when no guests are allowed.
> > 
> > 
> > Here we go. I very well may have something misconfigured and the latest update exposed it.
> > [meet.website.bob.cfg.lua.txt](https://github.com/jitsi/jitsi-meet/files/12612341/meet.website.bob.cfg.lua.txt) [meet.website.bob-config.js.txt](https://github.com/jitsi/jitsi-meet/files/12612342/meet.website.bob-config.js.txt) [sip-communicator.properties.txt](https://github.com/jitsi/jitsi-meet/files/12612343/sip-communicator.properties.txt)
> 
> A couple of issues I noticed:
> 
> * You still have the guest virtual host defined in Prosody
> * authdomain is commented out in config.js
> * jicofo is ok

Corrected issues with the virtual host and authdomain. No joy. Camera and microphone icons remain "greyed out" on Chrome. 

Still works in Firefox.

**Comment by saghul** [comment]
Then it must be unrelated to auth.

Can you pl share the browser console logs when you open the prejoin page?

**Comment by d-shiri** [comment]
For me, it does not work on Firefox as well.

**Comment by saghul** [comment]
Can any of you share your deployment URL so we can test it out?

**Comment by d-shiri** [comment]
sure, this is the url, although password protected: https://meet.drposture.app/
and here are the config files.
[jicofo.conf.txt](https://github.com/jitsi/jitsi-meet/files/12618342/jicofo.conf.txt)
[meet.drposture.app-config.js.txt](https://github.com/jitsi/jitsi-meet/files/12618343/meet.drposture.app-config.js.txt)

**Comment by saghul** [comment]
Jicofo is lacking the auth config. At any rate I am unable to properly test it because the credentials screen happens before prejoin.

**Comment by d-shiri** [comment]
> Jicofo is lacking the auth config. At any rate I am unable to properly test it because the credentials screen happens before prejoin.

please check your email, I sent you test credentials.

**Comment by prudloff-insite** [comment]
We have a similar problem: auth is required on our instance and since we upgrade to 2.0.8922-1, the microphone icon is greyed out with a loader on Chromium.
(We use `internal_plain` auth in Prosody.)

**Comment by stephane-chazelas** [comment]
For the record, issue is still there after upgrade to 2.0.8960.

Note that in my case (OP here), that was a fresh reinstall on Ubuntu 20.04 following the instructions in the handbook as upgrades were failing (the old 2.0.6826 still works fine with both firefox and chrome).

Since the only person who reported it working was using the docker deployment, it may be worth checking  whether the configurations there differs from the ones given in the handbook. I suppose another difference could be the version of prosody used.

**Comment by eggepegge** [comment]
In my case, it all starts to work again when I roll back *only* jitsi-meet-web to 1.0.7322-1 while the other packages still are on the updated release. Only thing needed is to reload the webpage. Nothing need to be restarted on the server. I have now frozen that package, and the update on the PROD environment went just fine, updating all other jitsi-related packages but this one to the latest stable.

hi  jitsi-meet-web                         1.0.7322-1

The package contain html files and javascripts. My guess is that some change has been done to a javascript here causing issues with Chrome. I haven't looked into it yet but will try to find some time for it soon.

**Comment by saghul** [comment]
> > Jicofo is lacking the auth config. At any rate I am unable to properly test it because the credentials screen happens before prejoin.
> 
> please check your email, I sent you test credentials.

Thanks I could test it now!

I think I know where the problem originates: it doesn't seem to be related to auth but to the prejoin screen. It's disabled in your instance, but if I force it with a URL parameter, things work as expected. You can do that as a workaround, while we look for the problem.

**Comment by saghul** [comment]
Hum, however, I couldn't reproduce it on meet.jit.si :-/

Are any of you running any Prosody plugins not in the base install?

**Comment by prudloff-insite** [comment]
I confirm setting `prejoinConfig.enabled` to true fixes the problem for us.

**Comment by julian70400** [comment]
> We have a similar problem: auth is required on our instance and since we upgrade to 2.0.8922-1, the microphone icon is greyed out with a loader on Chromium. (We use `internal_plain` auth in Prosody.)

Same problem here ! It worked like a charm since 2 years, without any configuration modification, and since last upgrade, something is broken. 
When I connect in a meeting, audio/video are greyed ("connecting to.."), and if I try to configure my audio/video in parameters, I can see them.
Debian 10.5
1.0-1050-1     jicofo
1.0.6644-1     jitsi-meet-prosody
1.0.7531-1     jitsi-meet-turnserver
1.0.7531-1     jitsi-meet-web
1.0.7531-1     jitsi-meet-web-config
2.3-44-g8983b1 jitsi-videobridge2
0.11.2-1+deb10 prosody

Thanks for your help !

**Comment by saghul** [comment]
Do you have the prejoin page enabled?

**Comment by julian70400** [comment]
Yes, and now, I rollback the only test I did (modifying /etc/prosody/conf.avail/videoconference.mydomain.cfg.lua and rollback with the old file, sure of this) but no more user are reconnized.. I do not understand.. I tryed to create a new user, when I try to connect to it, I am directly disconnected.

**Comment by saghul** [comment]
Not sure what you mean about the prosody config here.

**Comment by eggepegge** [comment]
I can confirm enabling the prejoin page resolve the issue for us as well, when unholding the jitsi-meet-web package upgrading it to 1.0.7499-1.

**Comment by saghul** [comment]
Did your upgrade complete successfully? I see some packages marked as rc.

**Comment by julian70400** [comment]
I just upgrade to Debian 11, but still same here : 

`--# dpkg -l | grep jitsi
ii  jitsi-meet                            2.0.8960-1              
ii  jitsi-meet-prosody                    1.0.7531-1              
ii  jitsi-meet-tokens                     1.0.7531-1              
ii  jitsi-meet-turnserver                 1.0.7531-1              
ii  jitsi-meet-web                        1.0.7531-1              
ii  jitsi-meet-web-config                 1.0.7531-1              
ii  jitsi-videobridge2                    2.3-44-g8983b11f-1      
ii  lua-basexx                            0.4.1-jitsi1            
ii  lua-cjson:amd64                       2.1.0.10-jitsi1

**Comment by julian70400** [comment]
Same problem on Debian 12, fully upgraded.

**Comment by saghul** [comment]
Does the prejoin page trick not work for you?

**Comment by julian70400** [comment]
> Does the prejoin page trick not work for you?

Not at all :(

![image](https://github.com/jitsi/jitsi-meet/assets/43498802/505a90df-6c3a-441c-a8bc-3b3aa62477f9)

**Comment by julian70400** [comment]
> Does the prejoin page trick not work for you?

Not at all :(

![image](https://github.com/jitsi/jitsi-meet/assets/43498802/1461ddb2-3f3c-45b4-bea8-244a431e8d92)

**Comment by saghul** [comment]
@damencho ANy ideas? I've ran out of talent!

**Comment by damencho** [comment]
@julian70400 Can you gather the following: 
- client logs, from the browser js console
-  Prosody logs, lean them and restart prosody and include the complete log
- Jicofo logs, you can do again clean and restart to include the complete logs
And after restarting do one attempt and attach the logs here or send it to me to damencho at jitsi dot org.

**Comment by damencho** [comment]
the pastebins are private and cannot be accessed.

**Comment by damencho** [comment]
Basically you are running without jicofo.

Wrong username or password: 
```
Jicofo 2023-11-10 16:04:10.166 GRAVE: [20] [xmpp_connection=client] XmppProvider.doConnect#181: Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:286)
        at org.jivesoftware.smack.AbstractXMPPConnection.lambda$new$2(AbstractXMPPConnection.java:407)
        at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.accept(NonzaCallback.java:177)
        at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.access$200(NonzaCallback.java:166)
        at org.jivesoftware.smack.NonzaCallback.onNonzaReceived(NonzaCallback.java:46)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessNonza(AbstractXMPPConnection.java:1440)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1700(XMPPTCPConnection.java:131)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1010)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Cannot connect to prosody:
```
Jicofo 2023-11-10 16:07:01.265 GRAVE: [14] [xmpp_connection=client] XmppProvider.doConnect#181: Failed to connect/login: java.net.SocketException: Socket closed
org.jivesoftware.smack.SmackException$SmackWrappedException: java.net.SocketException: Socket closed
        at org.jivesoftware.smack.AbstractXMPPConnection.setCurrentConnectionExceptionAndNotify(AbstractXMPPConnection.java:687)
        at org.jivesoftware.smack.AbstractXMPPConnection.notifyConnectionError(AbstractXMPPConnection.java:987)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$5400(XMPPTCPConnection.java:131)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1419)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$4200(XMPPTCPConnection.java:1172)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1222)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Socket closed
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
        at org.jivesoftware.smack.util.ObservableWriter.flush(ObservableWriter.java:51)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1367)
        ... 3 more
Jicofo 2023-11-10 16:07:01.274 AVERTISSEMENT: [24] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[not-authenticated] (0) closed with error
java.net.SocketException: Socket closed
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
        at org.jivesoftware.smack.util.ObservableWriter.flush(ObservableWriter.java:51)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1367)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$4200(XMPPTCPConnection.java:1172)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1222)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by julian70400** [comment]
Ok, got this working fine now (password problem between jicofo, videobridge and prosody).

Now, got again the initial problem : no video/mic.

But, not every time. I just start a meeting with a colleague, and he had mic & video OK, but not me. 
==> For his side, it was not working on Chrome, but working on Firefox  **120.0.1**.
==> For my side, all browsers failed, and Firefox **120.0.1**

Please, find my Firefox logs [here](https://pastebin.com/ebhsmiKV), logs start just before login.

**Comment by hbarnard** [comment]
Prejoin is looking good for me with Firefox too.
