### ISSUE TITLE
Use full screen real estate when viewing a shared screen

### ISSUE THREAD

**Issue by jmandel** [jitsi/jitsi-meet#13824]
Below is a screenshot of the Jitsi Meet UI when viewing a screenshare.

There is a "frame" around the top/bottom _as well as_ the left/right of the view, meaning that the screenshare is displayed at a smaller size than it could be.

There should be a way to grow the view until it hits the edge of my screen, to maximize viewing area. (Of course, because aspect ratios can differ, there might be blank areas above/below *or* left/right -- but there shouldn't be a frame all around.)

![image](https://github.com/jitsi/jitsi-meet/assets/313089/2b3d67e2-47f9-4c04-b678-fe37193b7819)

**Comment by jmandel** [comment]
This issue has not been resolved.

**Comment by jmandel** [comment]
This has not been resolved

**Comment by lixiaotaowx** [comment]
> Sorry this fell through the cracks. We have no plans to change the current layout, sorry.

I really need such a function. Can it be realized in the future? TX
