### ISSUE TITLE
Error net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep when accessing external_api.js

### ISSUE THREAD

**Issue by fishfree** [jitsi/jitsi-meet#13821]
In fact, I post my problem [here ](https://github.com/jitsi/docker-jitsi-meet/issues/1595)but no response. Please help me.

**Comment by saghul** [comment]
Please do not open duplicate issues. Wait.

**Comment by fishfree** [comment]
@saghul I'm sorry. Could you please answer me there? Almost desperately :-(
