### ISSUE TITLE
no audio on IOS app, but when using safari i get audio

### ISSUE THREAD

**Issue by idnawsi** [jitsi/jitsi-meet#13822]
### Description:
so when i am joining meet using IOS App and on WAN, i only get video but no audio, but when using web browser / Safari, i get sound and video. on LAN i get audio and sound using IOS App

### Expected behavior:

when i connect using ios app, it should be having audio
### Actual behavior:
i just get video and no sound

### Server information:

- Jitsi Meet version: Docker STABLE-8922
- Operating System: UBUNTU 20.04.6 LTS

### Client information:

- Browser / app version: IOS APP version 23.3.1
- Operating System: IOS

**Comment by saghul** [comment]
Si you observe the same behavior when you connect to meet.jit.si ?

**Comment by idnawsi** [comment]
Yes i get the same problem using meet.jit.si

**Comment by saghul** [comment]
Well that's really odd! What audio device are you using?

**Comment by idnawsi** [comment]
Just my iphone and my ipad
