### ISSUE TITLE
Share video not working in Android App

### ISSUE THREAD

**Issue by jaswant-saini** [jitsi/jitsi-meet#13823]
Hello,

I have noticed that share video is not working in the Android App but it is working on the web.
When a user tries to share a YouTube video from Android it is not able to play in Android but it play on web. Vice versa also not working. If a user try to share the video from WebApp it is not showing in Android but showing in WebApp only.
I have tried it with stable branch_8615 and just downloaded the jitsi meet App from Play store. Not working in both.
Im getting below error

2023-09-12 11:27:24.314 30000-30294 ReactNativeJS           org.jitsi.meet                       W  'Encountered an error loading page', { 
                                                                                                       code: -6,
                                                                                                      canGoForward: false,
                                                                                                      loading: false,
                                                                                                      title: '',
                                                                                                      canGoBack: false,
                                                                                                      description: 'net::ERR_CONNECTION_RESET',
                                                                                                      url: 'https://lonelycpp.github.io/react-native-youtube-iframe/iframe.html?data=%7B%22rel_s%22:0,%22loop_s%22:0,%22videoId_s%22:%22tBgNpc39FJk%22,%22controls_s%22:0,%22contentScale_s%22:1,%22cc_lang_pref_s%22:%22%22,%22allowWebViewZoom%22:false,%22modestbranding_s%22:1,%22preventFullScreen_s%22:0,%22showClosedCaptions_s%22:0%7D',
                                                                                                      target: 5323 }

**Comment by saghul** [comment]
I don't think we support that type of URLs. It's likely failing because it thinks it's a video file. If you want to play a YouTube video you'll need to use a YT URL and not a page with an iframe. In your case: https://www.youtube.com/watch?v=tBgNpc39FJk
