### ISSUE TITLE
Android/F-Droid: Creating rooms from the app on any third party server results in connection error

### ISSUE THREAD

**Issue by CryptGoat** [jitsi/jitsi-meet#13829]
### Description:

I have set a third party instance on my Jitsi Meet Android app. Whenever I try to create a room by providing a name, the connection attempt results in "Unfortunately something went wrong" message. Also the redirection to the app from an Android browser does not work as the Jitsi App is not listed when clicking the app option (before joining) .  I have tried this on instanced with and without authentication.

### Steps to reproduce:

1. Open Jitsi App
2. Open settings and enter any third party server.
3. Return to the start screen, try to create a room (it doesn't matter if you provide a custom name).

### Expected behavior:
You should be able to join the conference and use Jitsi Meet as usual.

### Actual behavior:
Error pops up: "Unfortunately something went wrong".

### Client information:

- Browser / app version: Android 23.3.1 (F-Droid)
- Operating System: GrapheneOS, Android 13, latest updates

### Additional information:
I am pretty sure that this issue was also present in at least some of the previous F-Droid builds.

**Comment by saghul** [comment]
Are you able to try the Play Store beta version?

**Comment by CryptGoat** [comment]
> Are you able to try the Play Store beta version?
Sadly no, I don't have a Google account.

**Comment by saghul** [comment]
Version 23.4.0 is now rolling out. It should also be picked up by F-Droid soon.

**Comment by licaon-kter** [comment]
Updated recipe https://gitlab.com/fdroid/fdroiddata/-/commit/53561929923d266b4babc4f6870b436a2d6342e6 next cycle will build it

**Comment by saghul** [comment]
Excellent, thank you @licaon-kter ! 🙏
