### ISSUE TITLE
Skip the screen with the choice of opening the room

### ISSUE THREAD

**Issue by Ewrei** [jitsi/jitsi-meet#13838]
### Description:
Open the room in a mobile browser, skip the screen with the choice of where to open the room (download the application, open in the Jitsi application...)
![2023-09-15 16 52 40](https://github.com/jitsi/jitsi-meet/assets/17156323/af4571ef-c522-4eb9-9ab0-ae8aafec734f)

### Steps to reproduce:

1. Open any Jitsi room in a mobile browser
2. You will see a screen asking you how to open this room

### Expected behavior:
Open the room immediately in a mobile browser

### Actual behavior:
A screen opens with a choice of options for how to open a room

### Client information:

- Browser / app version: Chrome: 116.0.5845.173
- Operating System: Android

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/8304e77a040e512b8c6ec9bf094b191f136c1d96/config.js#L1176
