### ISSUE TITLE
Raise hand remains after disconnect/reconnect

### ISSUE THREAD

**Issue by marwenmoalla** [jitsi/jitsi-meet#13830]
### Description:

The raised hand remains after disconnecting-reconnecting the video conf call.

### Steps to reproduce:

1- connect the video conference from the iOS or Android

3- Connect another user from the web.

4- iOS/Android user raise the hand

5- Everybody leaves the video conf

7- Same iOS/Android user connect the video conference from the same URL

### Actual behavior:

The raised hand remains on iOS/Android (not for the user connected from web)

### Server information:

- Jitsi Meet version:
- Operating System: 

### Client information:

- Browser / app version: JitsiMeetSDK (8.2.2)
- Operating System: iOS 16.6

I'm not sure if this issue can be solved from server or not. 
In any case we don't have a method from mobile SDKs to unraise hand when terminating/ending a session

**Comment by saghul** [comment]
I cannot reproeuce this with the store app, which uses SDK 8.3. Can you please give it a try?

**Comment by marwenmoalla** [comment]
I migrated to JitsiMeetSDK 8.3.1 and able to reproduce it. You are right it's not reproducing with Jitsi store app.
Do you know if this can be configured from server or not ?

**Comment by saghul** [comment]
It's not a configuration option... can you reproduce the issue with one of the test apps?

**Comment by marwenmoalla** [comment]
Yes, I'm able to reproduce it with https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/ios/swift/JitsiSDKTest
Testing with V8.3.1 and also 8.4.0 released today using standard URL : https://meet.jit.si

**Comment by saghul** [comment]
Can you please detail the steps you follow?

**Comment by marwenmoalla** [comment]
- Go to Browser https://meet.jit.si/roomName
- Connect to the videoconf
- install JitsiSDKTest into my iOS Device 
- Fill the same roomName 
- Tap on 3 dots then RaiseHand
- Disconnect from iOS
- Connect again
- Raise hand still displayed on iOS 
- It's not displayed on Web
-
Even we disconnect From Web and we connect again => Same behavior, iOS continue to dislay Raise Hand after disconnect/Connect

FYI : Recompliling (close/open again) iOS application do not reproduce the issue.

**Comment by marwenmoalla** [comment]
@saghul Any update on this please ?
