### ISSUE TITLE
"The room name is unsafe" when joining (not creating) room

### ISSUE THREAD

**Issue by opk12** [jitsi/jitsi-meet#13831]
### Description:

When I join a room made by other people, the app asks me to choose a better name. In general it's good to educate the userbase to choose good names, but I already know that and I cannot change the name anyway.

### Client information:

- Browser / app version: App 23.3.1 (23301001) from F-droid

**Comment by saghul** [comment]
You don't know if a room exists before joining. Allowing room enumeration would have security implications.

Aside, the creator might have been careless, so participants can at least tell them.
