### ISSUE TITLE
'startWithVideoMuted: true' not working properly

### ISSUE THREAD

**Issue by sidm033** [jitsi/jitsi-meet#13835]
if you set `startWithVideoMuted: true` before joining a Jitsi video call and later turn on your camera, the other participant is unable to see your video. 

- "@jitsi/react-native-sdk": "^0.3.0",
- Operating System: macOS

**Comment by saghul** [comment]
What options is the other user using?

**Comment by sidm033** [comment]
same options, actually, we use the same app, but with different users

**Comment by sidm033** [comment]
Can you provide an update?

**Comment by sidm033** [comment]
In the console, an error appears after the camera has been turned on
 
`2023-09-14T18:32:35.089Z [modules/statistics/RTPStatsCollector.js] <anonymous>:  No participant ID returned by LocalTrack[2,video]`

**Comment by saghul** [comment]
Please share the full log you het with logcat. Also, are you using your own server or meet.jit.si?

**Comment by sidm033** [comment]
<img width="1428" alt="Screenshot 2023-09-15 at 12 08 09 PM" src="https://github.com/jitsi/jitsi-meet/assets/29774020/0bc7ec70-ce2e-4ba2-b5bd-7c327f07ce0a">

**Comment by sidm033** [comment]
<img width="1407" alt="Screenshot 2023-09-15 at 12 10 15 PM" src="https://github.com/jitsi/jitsi-meet/assets/29774020/d61570b1-f2ea-4ee1-bd09-d2fd7303a1de">

**Comment by sidm033** [comment]
We are using our server, yes

**Comment by saghul** [comment]
Can you reproduce the problem with meet.jit.si?

**Comment by saghul** [comment]
Ah damn, that SDK does not support the auth we use. Good thing I was planning on making a release today :-P

**Comment by sidm033** [comment]
With the updated version @ 0.4.1, it isn't working

**Comment by sidm033** [comment]
<img width="342" alt="Screenshot 2023-09-15 at 12 54 24 AM" src="https://github.com/jitsi/jitsi-meet/assets/29774020/88e11b86-7c25-406b-b40e-13fd279029b9">

<img width="342" alt="Screenshot 2023-09-15 at 12 60 24 AM" src="https://github.com/jitsi/jitsi-meet/assets/29774020/da7800ad-40b2-425d-987c-89db10cde4f4">

**Comment by saghul** [comment]
@Calinteodor can you please check this when you get a chance?

**Comment by sidm033** [comment]
Would you be able to give us an update?

**Comment by saghul** [comment]
We haven't been able to look into this yet.

**Comment by Calinteodor** [comment]
Hello. Please update to 0.5.0. I didn't manage to reproduce it on latest version.
Also when you are testing screen share or video capabilities, please consider real devices and not emulators. Thank you!
