### ISSUE TITLE
Android app: can no longer join/create meeting on community Jitsi instance without logging in through Google, Facebook, or Microsoft (Github)

### ISSUE THREAD

**Issue by exercismnow** [jitsi/jitsi-meet#13843]
### Steps to reproduce:

1. Open desk-top browser. Create meeting at https://meet.mayfirst.org (community Jitsi instance).
2. Notice that you are the moderator, and did not need to login through Google, Facebook, or Microsoft to create the meeting.
3. Open Jitsi Android app. Navigate to your meeting URL
4. Receive authentication wall message: "The conference has not yet started because no moderators have yet arrived. If you'd like to become a moderator, please log-in. Otherwise, please wait."
5. The same thing happens when you try to create a meeting on meet.mayfirst.org by entering the complete URL of a new room into the Jitsi app.

Possibly related to this issue? https://github.com/jitsi/jitsi-meet/issues/13753

### Expected behavior:

If you're trying to join a Jitsi instance that does not require authentication on the desktop browser, then the app should not require you to login either. 

### Actual behavior:

The app forces you to login via Google, Facebook, or Microsoft.

![jitsi-auth](https://github.com/jitsi/jitsi-meet/assets/119020198/cad67b7d-a826-4e24-8f62-f5190af678e1)

### Server information:

- URL: meet.mayfirst.org

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: 23.3.1 build 23301002, F-droid
- Operating System: Android

**Comment by saghul** [comment]
> The app forces you to login via Google, Facebook, or Microsoft.

First of all, this is not the case. That only applies to meet.jit.si. It's deployment specific, and the deployment you mentioned has not enabled any auth.

It's weird you are getting the authentication screen though. Looks like a bug in detecting the need for auth.

I can confirm it works on version 23.4.0, currently rolling out on the Play Store. You can either get it from there (or opt-in to the beta and guarantee it) or wait for F-Droid to pick it up.

**Comment by exercismnow** [comment]
》 First of all, this is not the case. That only applies to meet.jit.si. It's deployment specific, and the deployment you mentioned has not enabled any auth.

Was referring to my experience with the android app downloaded from F-Droid, which we're thinking is a bug in detecting the need for auth. I'm aware that the desktop web-browser app for 3rd party Jitsi instances configured to not require auth works as expected (not requiring auth).

If this is fixed with the next update, that's good news!

**Comment by Franco-Sparrow** [comment]
@exercismnow Hi Sir, I am opening this issue because is not working for Jitsi meet Android App `24.2.2`, with Jitsi Meet server `2.0.9457-1`. The app was downloaded from the Play Store.

**Comment by Franco-Sparrow** [comment]
Tested with `23.4.0` same error if I try to access to the invitation

![WhatsApp Image 2024-06-17 at 12 17 11 AM](https://github.com/jitsi/jitsi-meet/assets/56793015/fc1d73a1-10fb-44ff-bacb-e9cbae91f49f)

If I set the URL o name of the room, it stays forever waiting for the moderator:

![WhatsApp Image 2024-06-16 at 10 08 30 PM](https://github.com/jitsi/jitsi-meet/assets/56793015/c3dd7885-afac-42fe-981c-27be2703167f)

**Comment by Franco-Sparrow** [comment]
UPDATE!!!

I was able to joing with the Android app, but I had to become in the moderator and invite others (my laptop) to the room. I dont know if other Android could have same problem if try to joing without moderator permissions
