### ISSUE TITLE
Video shutting down supposedly due to low bandwith

### ISSUE THREAD

**Issue by Beyond01E** [jitsi/jitsi-meet#13841]
### Description:

Hi Just wanted to check in regarding the issue of video shutting down supposedly due to low bandwith. I saw this issue reported here from 2017 in combination with screensharing, but I actually encounter it in regular video chat without screensharing with as little as three people total participants where I suddenly don't have any video anymore on my screen and among tring to figure out the reason it says low bandwith. Does jitsi require so much more bandwith than similar video conferencing tools? Or is this a seperate bug because by comparison from the same location I can easily host video conferences with no video issues with up to 30 people in the room with other platforms. For security and privacy reasons I seek to move away from the other platforms hence the attempt to make it work with jitsi. Is there a way to force the video to stay on?

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
What is the jitsi-meet you use on your deployment?

What is the browser and version where you experience the problem?
