### ISSUE TITLE
Virtual backgrounds still visible in Camera/Video menu when virtual backgrounds disabled

### ISSUE THREAD

**Issue by reinforce** [jitsi/jitsi-meet#13842]
### Description:
Virtual backgrounds still visible in Camera/Video menu when virtual backgrounds disabled

### Steps to reproduce:

1. Disable virtual backgrounds in /etc/jitsi/meet/$(hostname)-config.js (set disableVirtualBackground: true,)
2. Restart services or reboot host
3. Start new conference or connect to exists

### Expected behavior:

Virtual backgrounds settings should not be visible from all menus.

### Actual behavior:

Virtual backgrounds menu still visible in Camera/Video menu. When clicking to it, settings window appears.

### Server information:

- Jitsi Meet version: 2.0.8922
- Operating System: Debian 12.1

### Client information:

- Browser / app version: Google Chrome 116.0.5845.140 / Firefox 117.0
- Operating System: Gentoo Linux / Microsoft Windows 10

### Additional information:

![Снимок экрана в 2023-09-17 23-15-24](https://github.com/jitsi/jitsi-meet/assets/1038834/0bfa0df2-13a4-42d4-b9ae-8c7ef3185900)
![Снимок экрана в 2023-09-17 23-29-39](https://github.com/jitsi/jitsi-meet/assets/1038834/a8e8cb9e-e010-48a6-9e1c-072e86d5c553)
![Снимок экрана в 2023-09-17 23-29-29](https://github.com/jitsi/jitsi-meet/assets/1038834/6adda215-4b84-41b4-87ad-1d7a9a12732d)

**Comment by reinforce** [comment]
Jitsi meet 2.0.8960 fresh install - same issue

**Comment by javierckr** [comment]
I forgot that button, fixed in this PR #13851

**Comment by reinforce** [comment]
Closing as fixed
