### ISSUE TITLE
Add Debian Salsa, GitLab, and others as authentication provider for jitsi meet moderator requirement

### ISSUE THREAD

**Issue by programmerjake** [jitsi/jitsi-meet#13848]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
Jitsi Meet requires authenticating with GitHub, Google, or Facebook in order to be a moderator which is required to start a meeting. Some people prefer to not use those services to authenticate and would like additional options. https://github.com/jitsi/jitsi-meet/issues/13753

**Describe the solution you'd like**
Please describe the desired behavior.
Add more authentication providers to the list. I suggest:
* [Debian Salsa](https://salsa.debian.org/)
* [GitLab](https://gitlab.com/)
* [Codeberg](https://codeberg.org/)
* Stackexchange/Stackoverflow

As far as I can tell, these all support OAuth2

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
N/A

**Comment by saghul** [comment]
We are currently not considering any more providers. We might look into adding more in the future, however.
