### ISSUE TITLE
Malformed PARTICIPANTS_INFO_RETRIEVED JSON

### ISSUE THREAD

**Issue by smelfungus** [jitsi/jitsi-meet#13853]
### Description:

Hello! It seems like `BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED` `event.data["participantsInfo"]` contains malformed JSON - none of its keys and values are using quotes. That leads to potential bugs and unexpected behaviour even with the lenient JSON parser modes, especially for the fields like `name` and `avatarUrl`, which generally makes this JSON impossible to parse properly.

- SDK version: 8.4.0
- Operating System: Android

**Comment by saghul** [comment]
Ops! Any chance you could submit a PR?

**Comment by sagarsabhadiya** [comment]
> ### Description:
> 
> Hello! It seems like `BroadcastEvent.Type.PARTICIPANTS_INFO_RETRIEVED` `event.data["participantsInfo"]` contains malformed JSON - none of its keys and values are using quotes. That leads to potential bugs and unexpected behaviour even with the lenient JSON parser modes, especially for the fields like `name` and `avatarUrl`, which generally makes this JSON impossible to parse properly.
> 
>     * SDK version: 8.4.0
> 
>     * Operating System: Android

Getting same issue while retrieving participants info.

Is there any other way to get get participant info?
