### ISSUE TITLE
Presentation flickering in Firefox when screen share is in focus

### ISSUE THREAD

**Issue by augusto-herrmann** [jitsi/jitsi-meet#13860]
### Description:

When joining a Jitsi meeting using Firefox 117.0.1 for Linux, whenever someone shares their screen or window (presentation mode), it automatically comes into focus (as expected), but the video flickers a lot. It's as if a glitch with the frame buffer or motion codec was happening or something: a constant flashing back and forward with the previous frames in the video.

### Steps to reproduce:

1. Join any meeting using Firefox 117.0.1
2. Any other participant starts sharing their screen

### Expected behavior:

See the screen that's being shared clearly and without any issues.

### Actual behavior:

We get to see the screen, but the video flickers and glitches a lot.

However, when the screen is minimized (press W or click the four squares icon), there is no flickering. The image displays normally, but pretty small.

### Server information:

- Jitsi Meet version: Not sure, according to [this post](https://github.com/jitsi/jitsi-meet/issues/5748#issuecomment-610383704) it seems to be 7531. Happens both on the instance at meet.jit.si and video.devloprog.org
- Operating System: Unknown

### Client information:

- Browser / app version: Firefox 117.0.1
- Operating System: Ubuntu 20.04 LTS

### Additional information:

I have been using Jitsi Meet for years and this did not happen until about a couple of months ago. I thought it was temporary and was going to be fixed soon. But since it was taking a long time, I decided to look if the issue was already reported, but the only similar issue I could find was an old one (#7274) about Chrome in 2020.

It happens on the meet.jit.si instance since at least a couple of weeks before they started requiring a login (as we've abandoned that instance since). But it also happens on the instance we use now: video.devloprog.org.

**Workaround:** if you minimize the screen that's being shared (press W or click the four squares icon), it displays normally, it's just often too small to be usable. You can, however, use the Picture in Picture feature (#6989) to make it as large as you want, or even display it full screen. When displayed this way there is no flickering at all and image quality is good. However, it's inconvenient because the Picture in Picture window has priority over everything else and you constantly need to close it even to interact with Jitsi's interface.

**Comment by saghul** [comment]
Any chance you can provide a screen recording?

**Comment by md-work** [comment]
Same issue here.

<details>
<summary>screenshots</summary>

OS: openSUSE-15.5  
Firefox: 117.0.1 from mozilla.org (not from openSUSE)

A friend shares his terminal window with an open editor, typing the two lines `foo` and `bar`. See upper left corner for distortions.  
![grafik](https://github.com/jitsi/jitsi-meet/assets/29978077/f9b2f8cb-da15-4359-ba10-faf85b12b8bc)

![grafik](https://github.com/jitsi/jitsi-meet/assets/29978077/a256d1c6-a126-4b91-9378-e7e96f39df69)

</details>

**Comment by himpierre** [comment]
I have the very same issues. Only Firefox, in my case 117.0.1, is affected. Flickering screenshare + green participants. Jitsi latest stable.

cheers, t.

**Comment by saghul** [comment]
For those running self-hosted instances, please try this:

Edit your config.js file and locate this section (or add it if missing): https://github.com/jitsi/jitsi-meet/blob/4b4bc1c8236e988e1f6f1cf6c4459e26f1167b26/config.js#L432

Uncomment it and make sure VP9 is at the end.

Does that help?

**Comment by himpierre** [comment]
I'll check it out. Thanks!

Am 26. September 2023 12:09:50 MESZ schrieb "Saúl Ibarra Corretgé" ***@***.***>:
>For those running self-hosted instances, please try this:
>
>Edit your config.js file and locate this section (or add it if missing): https://github.com/jitsi/jitsi-meet/blob/4b4bc1c8236e988e1f6f1cf6c4459e26f1167b26/config.js#L432
>
>Uncomment it and make sure VP9 is at the end.
>
>Does that help?
>

**Comment by md-work** [comment]
> For those running self-hosted instances, please try this:
> 
> Edit your config.js file and locate this section (or add it if missing):
> 
> https://github.com/jitsi/jitsi-meet/blob/4b4bc1c8236e988e1f6f1cf6c4459e26f1167b26/config.js#L432
> 
> Uncomment it and make sure VP9 is at the end.

Hint:  
It seems `codecPreferenceOrder` must be changed twice. One occurence seems to be the general setting and the other for P2P mode (with exactly 2 participants in a conference).

**Comment by saghul** [comment]
True that. Did making the change help?

**Comment by RealSebFox** [comment]
> True that. Did making the change help?

I'll get a chance to test it later today. You will be updated.

**Comment by himpierre** [comment]
For me the flickering is gone. The green picture effect did not occur either till now.

cheers, t.

Am 27. September 2023 13:32:15 MESZ schrieb RealSebFox ***@***.***>:
>> True that. Did making the change help?
>
>I'll get a chance to test it later today. You will be updated.
>

**Comment by RealSebFox** [comment]
I'm in a meeting now and it looks great! Thanks!

**Comment by jallamsetty1** [comment]
@RealSebFox Thanks for verifying. With the default settings, did you notice degraded video quality for camera streams or was it only for screenshare?

**Comment by jallamsetty1** [comment]
Also, can you please try with Firefox 118? I am not able to reproduce this on meet.jit.si.

**Comment by RealSebFox** [comment]
> @RealSebFox Thanks for verifying. With the default settings, did you notice degraded video quality for camera streams or was it only for screenshare?

Both degraded video quality and screenshare jittering were issues with the default settings. Video quality was only an issue when performance settings were set to "optimal quality", though. I have tested the recommended fix today on Firefox 118.0 (Ubuntu) in a p2p call.

My instance runs on a Debian11 cloud server with 2vCPUs and 8GB RAM.

**Comment by himpierre** [comment]
So with Firefox 118 no problems at all?

cheers, t.

Am 27. September 2023 17:48:45 MESZ schrieb RealSebFox ***@***.***>:
>> @RealSebFox Thanks for verifying. With the default settings, did you notice degraded video quality for camera streams or was it only for screenshare?
>
>Both degraded video quality and screenshare jittering were issues with the default settings. Video quality was only an issue when performance settings were set to "optimal quality", though. I have tested the recommended fix today on Firefox 118.0 (Ubuntu) in a p2p call.
>
>My instance runs on a Debian11 cloud server with 2vCPUs and 8GB RAM.
>

**Comment by RealSebFox** [comment]
> So with Firefox 118 no problems at all? cheers, t. 

I had a smooth and pleasant call today. Video was disabled during parts of the call due to low bandwith, but that is nothing new or uncommon. There was no flicker in the shared screen and there were no green faces. :-)

**Comment by RealSebFox** [comment]
> Was this on your instance with the modified codec list or was it on meet.jit.si?

This was on my own instance with the modified codec list. I love Jitsi because I can host it myself. I'll try if meet.jit.si works for me as well.

**Comment by RealSebFox** [comment]
I just tested meet.jit.si with Firefox 118.0 on Ubuntu and it works well for me.

**Comment by md-work** [comment]
The fix works well for me.

Can this be fixed in the next update, so the `config.js` does not have to be adjusted manually again and again?  
_(`config.js` is usually overwritten on `apt upgrade`)_

**Comment by saghul** [comment]
Arguable, Firefox needs to fix it, which they seem to have done. It's not practical to flip defaults when browsers introduce bugs...

**Comment by md-work** [comment]
> Arguable, Firefox needs to fix it, which they seem to have done. It's not practical to flip defaults when browsers introduce bugs...

Unfortunately I still have the issue when the screen sharing client uses a Chromium based browser and I use Firefox.

Software versions:  
Tested up to date Firefox: `118.0.1` and `Nightly-20230928` (tested on Debian and openSUSE)  
Chromium: `117.0.5938.92`  
Private Jitsi-Meet server: `jitsi-meet-2.0.8960-1` on `Debian-10`  
The general `codecPreferenceOrder` is set to `[ 'VP8', 'H264', 'VP9' ]`on that server. And P2P is disabled.

But the issue does not happen when I use https://meet.jit.si/ . Even not when the screen sharing side uses Chromium. Are there any extra tweaks enabled on that server?

&nbsp;

I completely agree. The problem should be fixed by the software which is causing it! I just wasn't sure if the root cause is in Jitsi or in Firefox. If you're think Firefox is causing the issue, then I'll open a bug at https://bugzilla.mozilla.org/    
_(I've already searched Mozillas bugtracker, but I couldn't find a bug that seemed to match)_

**Comment by saghul** [comment]
> And P2P is disabled.

Can you try enabling it?

**Comment by himpierre** [comment]
For me it still only works with VP9 pushed back in the config. Even with firefox 118.0.1.

cheers, t.

Am 29. September 2023 12:40:23 MESZ schrieb md-work ***@***.***>:
>> Arguable, Firefox needs to fix it, which they seem to have done. It's not practical to flip defaults when browsers introduce bugs...
>
>Unfortunately I still have the issue when the screen sharing client uses a Chromium based browser and I use Firefox.
>
>Software versions:  
>Tested up to date Firefox: `118.0.1` and `Nightly-20230928` (tested on Debian and openSUSE)  
>Chromium: `117.0.5938.92`  
>Private Jitsi-Meet server: `jitsi-meet-2.0.8960-1` on `Debian-10`  
>The general `codecPreferenceOrder` is set to `[ 'VP8', 'H264', 'VP9' ]`on that server. And P2P is disabled.
>
>But the issue does not happen when I use https://meet.jit.si/ . Even not when the screen sharing side uses Chromium. Are there any extra tweaks enabled on that server?
>
>&nbsp;
>
>I completely agree. The problem should be fixed by the software which is causing it! I just wasn't sure if the root cause is in Jitsi or in Firefox. If you're think Firefox is causing the issue, then I'll open a bug at https://bugzilla.mozilla.org/    
>_(I've already searched Mozillas bugtracker, but I couldn't find a bug that seemed to match)_ 
>

**Comment by jallamsetty1** [comment]
> But the issue does not happen when I use https://meet.jit.si/ . Even not when the screen sharing side uses Chromium. Are there any extra tweaks enabled on that server?

Yes, meet.jit.si is ahead of the stable release. It has 2 Firefox fixes which fix improper BWE calculations made by bridge when Firefox client is involved but nothing related to VP9 decode.

**Comment by jallamsetty1** [comment]
> For me it still only works with VP9 pushed back in the config. Even with firefox 118.0.1.

What platform are you testing this on?

**Comment by himpierre** [comment]
It's a linux desktop machine.

Am 2023-10-02 16:11, schrieb Jaya Allamsetty:
>> For me it still only works with VP9 pushed back in the config. Even 
>> with firefox 118.0.1.
> 
> What platform are you testing this on?

**Comment by himpierre** [comment]
I'm not sure. Triggered by the mouse of the presenter? Maybe. It does not happen with chrome which I prefer not to use. :)

cheers, t.

Am 2. Oktober 2023 17:34:12 MESZ schrieb Jaya Allamsetty ***@***.***>:
>> It's a linux desktop machine.
>
>We are able to reproduce something similar on Linux. Whenever the mouse moves, the screenshare flickers and then we see something like this. This seems to be a mouse composting bug
>
>![Screenshot 2023-10-02 at 11 29 46 AM](https://github.com/jitsi/jitsi-meet/assets/54324652/13f9f2c1-fb72-448b-854c-171b93467345)
>Is this what you observe as well?
>

**Comment by RealSebFox** [comment]
> > It's a linux desktop machine.
> 
> We are able to reproduce something similar on Linux. Whenever the mouse moves, the screenshare flickers and then we see something like this. This seems to be a mouse composting bug
> 
> ![Screenshot 2023-10-02 at 11 29 46 AM](https://user-images.githubusercontent.com/54324652/272016005-13f9f2c1-fb72-448b-854c-171b93467345.png) Is this what you observe as well?

I have seen this issue for a long time on my self-hosted instance, when connecting with Firefox on Ubuntu, but it didn't disturb me much. Then those mouse-glitches became flickering with green faces after the updates I made listed further above. That's how I found this ticket. Moving VP9 to the end of the line fixed all those issues for me.

**Comment by jallamsetty1** [comment]
> Then those mouse-glitches became flickering with green faces after the updates I made listed further above

Can you please elaborate on what you mean by green faces?

**Comment by RealSebFox** [comment]
> > Then those mouse-glitches became flickering with green faces after the updates I made listed further above
> 
> Can you please elaborate on what you mean by green faces?

Please look at this comment: https://github.com/jitsi/jitsi-meet/issues/13860#issuecomment-1734053002.

With "green faces" I mean, the video was looking green. Mouse-glitches and later jittering/flickering happened on screen share, green faces were an issue with video.

**Comment by RealSebFox** [comment]
I don't know what it's worth, but here is my full config: 

```
var config = {
    hosts: {
        domain: 'example.com',
        anonymousdomain: 'anonymous.example.com',
        muc: 'conference.<!--# echo var="subdomain" default="" -->example.com'
    },
    testing: {

    },
    flags: {

    },
    enableNoAudioDetection: true,
    enableNoisyMicDetection: true,
    channelLastN: -1,
    videoQuality: {
       codecPreferenceOrder: [ 'VP8', 'H264', 'VP9' ],   
       preferredCodec: 'VP8',   
       maxBitratesVideo: {
             H264: {
                 low: 200000,
                 standard: 500000,
                 high: 1500000
             },
             VP8 : {
                 low: 200000,
                 standard: 500000,
                 high: 1500000
             },
             VP9: {
                 low: 100000,
                 standard: 300000,
                 high: 1200000
             }
       },   
       minHeightForQualityLvl: {
           360: 'standard',
           720: 'high'
       },   
    },
    enableWelcomePage: true,
    p2p: {
        enabled: true,
        codecPreferenceOrder: [ 'VP8', 'H264', 'VP9' ],
        stunServers: [
            { urls: 'turn:turn.example.com', credential: 'redacted' }
        ]
    },
    analytics: {
    
    },
    deploymentInfo: {
    
    },
    mouseMoveCallbackInterval: 1000,
    makeJsonParserHappy: 'even if last key had a trailing comma'
};

config.flags = config.flags || {};
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
config.flags = config.flags || {};
```
I hope this helps!

**Comment by saghul** [comment]
With the default config you will be using VP9. Can you try and make VP8 the default?

**Comment by RealSebFox** [comment]
> With the default config you will be using VP9. Can you try and make VP8 the default?

I think VP8 is the default. 

```
       codecPreferenceOrder: [ 'VP8', 'H264', 'VP9' ],   
       preferredCodec: 'VP8', 
```

I'm not complaining. This config is working for me!

**Comment by saghul** [comment]
Oh, sorry, I got the messages mixed up :-/

**Comment by Pehrsons** [comment]
This is plausibly a linux variant of [firefox bug 1832276](https://bugzilla.mozilla.org/show_bug.cgi?id=1832276). We don't support svc, which is what I understand you use here, so it's not entirely unexpected. If you want to use libwebrtc's libvpx software codec instead, set the pref `media.navigator.mediadatadecoder_vpx_enabled=false`.

**Comment by jallamsetty1** [comment]
This should be fixed in Firefox 120 which is already in stable now.

**Comment by augusto-herrmann** [comment]
I can confirm that issue has been fixed. Using Firefox 120.0.1.
