### ISSUE TITLE
User can't minimize the video conference when he try sharing the screen

### ISSUE THREAD

**Issue by mhamdihajer1** [jitsi/jitsi-meet#13875]
**Is your feature request related to a problem you are facing?**
Yes, the user needs to click on the home button of the Android device to be able to share the desired view.

**Describe the solution you'd like**
Add a floating button to minimize the video conference session

**Describe alternatives you've considered**
Click the home button to go to the screen that needs to be shared

**Comment by saghul** [comment]
What app / SDK version are you using? We have fixed that in the latest release.

**Comment by mhamdihajer1** [comment]
we use 
jitsiMeetSdk = "6.0.0"
jitsiMeetSdkSw = "5.1.0-sw-r7"

**Comment by mhamdihajer1** [comment]
Thanks, forget for jitsiMeetSdkSw

**Comment by mhamdihajer1** [comment]
can you please reopen it

**Comment by saghul** [comment]
How are you launching JitsiMeetActivity?

**Comment by HajerMehemdi** [comment]
Hi
 // Build options object for joining the conference. The SDK will merge the default
        // one we set earlier and this one when joining.
        JitsiMeetConferenceOptions options
                = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setFeatureFlag(WELCOME_PAGE_ENABLED, false)
                .setRoom(roomName)
                .setToken(token)
                .setVideoMuted(true)
                .setFeatureFlag(CALL_INTEGRATION_ENABLED, false)
                .setUserInfo(userInfo)
                .setFeatureFlag(CHAT_ENABLED,true)
                .setFeatureFlag(INVITE_ENABLED,false)
                .setFeatureFlag(LIVE_STREAMING_ENABLED,false)
                .setFeatureFlag(RECORDING_ENABLED,false)
                .setFeatureFlag(VIDEO_SHARE_BUTTON_ENABLED,false)
                .setFeatureFlag(CLOSE_CAPTIONS_ENABLED,false)
                .setFeatureFlag(KICK_OUT_ENABLED,false)
                .setFeatureFlag(MEETING_PASSWORD_ENABLED,false)
                .setFeatureFlag(ENABLE_SECURITY_OPTIONS,false)
                .setFeatureFlag(CAR_MODE_ENABLED,false)

                .build();

        // Launch the new activity with the given options. The launch() method takes care
        // of creating the required Intent and passing the options.
        if (context != null){
            Intent intent = new Intent(context, JitsiMeetActivity.class);
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            intent.setAction(CONFERENCE_ACTION);
            intent.putExtra(CONFERENCE_OPTIONS_EXTRA, options);
            context.startActivity(intent);
        }else{
            Logger.error(CLASS_NAME, "Error Context is null");
        }

**Comment by saghul** [comment]
What SDK version is that? You should see a carat button on the top left.

**Comment by HajerMehemdi** [comment]
jitsiMeetSdk = "6.0.0"

**Comment by saghul** [comment]
Please read: https://github.com/jitsi/jitsi-meet/issues/13875#issuecomment-1735144287
