### ISSUE TITLE
JitsiMeetUncaughtExceptionHandler FATAL ERROR Targeting S+ (version 31 and above)

### ISSUE THREAD

**Issue by hussi-emblem** [jitsi/jitsi-meet#13876]
JitsiMeetUncaughtExceptionHandler FATAL ERROR
                                                                                                    java.lang.IllegalArgumentException: : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/commit/767e23f34c822952eb3e024c5be787318c41cb84

Will be part of the next release.

**Comment by hussi-emblem** [comment]
when is the next release, App is in production and crashing

**Comment by saghul** [comment]
Next week likely.

**Comment by hussi-emblem** [comment]
is it released ? @saghul

**Comment by saghul** [comment]
Yes it's part of Edison 23.5.0

**Comment by hussi-emblem** [comment]
org.jitsi.react:jitsi-meet-sdk:8.4.0 i am using this version but still facing the issue

**Comment by saghul** [comment]
Oh right, sorry. No, we'll have an 8.5.0 release soon.
