### ISSUE TITLE
How to test jitsi-meet?

### ISSUE THREAD

**Issue by carlesm95** [jitsi/jitsi-meet#1387]
Hi, I'm new on Jitsi. I'm doing my final project about Jitsi and I have already installed jitsi-meet in ubuntu following the quick install guide. Can someone tell me how can I do a test conferences to try it? I only know that to start it I have to enter /etc/init.d/jitsi-videobridge start, but what I have to do then?

Many thanks.

**Comment by saghul** [comment]
You need to open the website with your browser. It will typically be https://IP-of-your-server/.

PS: USe the mailing list for such questions, we keep the issue tracker just for issues. Cheers!
