### ISSUE TITLE
help translate into Russian please open on weblate

### ISSUE THREAD

**Issue by ghost** [jitsi/jitsi-meet#13874]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
I want to complete the Russian translation in its entirety.
**Describe the solution you'd like**
will be fully translated into Russian
Please describe the desired behavior.
user friendliness
**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
Check this out: https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md
