### ISSUE TITLE
Unable to get  Participant Info Event in BroadcastEvents listener (Android).

### ISSUE THREAD

**Issue by sagarsabhadiya** [jitsi/jitsi-meet#13889]
**case PARTICIPANT_JOINED:
          Timber.i("Participant joined%s", event.getData());
           break;
case PARTICIPANT_LEFT:
          Timber.i("Participant left%s", event.getData());
           break;
case PARTICIPANTS_INFO_RETRIEVED:
           Log.e(TAG, "onBroadcastReceived: " + event.getData());
           break;**

Hello,

I have added listener to access all broadcast events in my activity. Other events are working fine. But getting an issue with PARTICIPANTS_INFO_RETRIEVED this event. Unable to get data from this event.

**Comment by saghul** [comment]
You are you sending the broadcast event?

**Comment by sagarsabhadiya** [comment]
No, I'm not sending the broadcast event.

**Comment by sagarsabhadiya** [comment]
Hi, @saghul ,

Can you help with this?

How to send broadcast event to jitsi meet and retrieve participant info?

Thanks,
Sagar

**Comment by saghul** [comment]
You should be able to use the ParticipantsService helper:

`ParticipantsService.getInstance().retrieveParticipantsInfo(callback);`

You can check the source in ParticipantsService.java
