### ISSUE TITLE
Disconnected as soon as a 2nd person joins the conference

### ISSUE THREAD

**Issue by DarkTexas** [jitsi/jitsi-meet#13896]
I've done a clean installation of Jitsi using the way noted at https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ because I upgraded my installation yesterday and noticed that the conference does crash as soon as the 2nd participant joins the call. However, even with a fresh build (and fresh VM) the same problem occurs.

Is there currently an error on the build preventing jitsi from working correctly and/or is there a way (if there's something wrong the current file available) to install a working version?

Reporting from Debian 12.1

ii  jitsi-meet                      2.0.8960-1                     all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.7531-1                     all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                  1.0.7531-1                     all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.7531-1                     all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.3-44-g8983b11f-1             all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                      0.4.1-jitsi1                   all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                 2.1.0.10-jitsi1                amd64        JSON parser/encoder for Lua

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

There is no problem with current versions. Check your logs for errors.

Please follow https://jitsi.org/qi

**Comment by DarkTexas** [comment]
The manual was followed. It worked just fine before the update - and/or new installation, hence opening a new issue.

I've downloaded and installed a .deb file with the version before the current release, that does work just fine. Now upgrading the installation to the current version does result in failing again! How can this be not an issue with the release? I can not find anything suspicious on the logs..

**Comment by damencho** [comment]
Downloading a deb file is not the way to upgrade, you need to upgrade via apt command as there are many dependencies involved.

We prefer discussing problems on the forum, before opening an issue.

Check your js console logs what is the error you see?

**Comment by DarkTexas** [comment]
Yeah, I'm aware. I've used the deb file to downgrade.

I've followed the official installation instructions before that. The deb file was just to test if it's related to the version, which seems to be confirmed. I've made a post on the forums as well.
