### ISSUE TITLE
"Enable low bandwidth mode " label is having some issues when set to German (Anrdoid)

### ISSUE THREAD

**Issue by HajerMehemdi** [jitsi/jitsi-meet#13890]
Preconditions / test setup:
Android device or application language set to German

Steps to reproduce:
Join a video conf call
Click on the 3 dots menu

Actual result or description of the tests done:
There is a display problem with the quotation mark on the label "Nur Audio"

**Comment by saghul** [comment]
We rely on community translations, would you be able to provide a PR? See the README in the lang/ directory.

**Comment by HajerMehemdi** [comment]
Hi
must check https://github.com/jitsi/jitsi-meet/blob/master/lang/main-de.json
the quotation mark are incorrect 
"audioOnlyOff": "Modus **„**Nur Audio“ deaktivieren",
 "audioOnlyOn": "Modus **„**Nur Audio“ aktivieren",

**Comment by HajerMehemdi** [comment]
Hi even with the jitsi version8.6.1 the issue persist 

**„**Nur Audio“ deaktivieren",
 **„**Nur Audio“ aktivieren",
