### ISSUE TITLE
Error "TypeError: ad.attachMediaStream is not a function" in Opera

### ISSUE THREAD

**Issue by antkey1** [jitsi/jitsi-meet#13900]
### Description:

After updating to version 2.0.8960, conferences in the Opera browser stopped working.

Shows a pre-join screen for a split second, then a black screen.

The problem is reproduced on meet.jit.si

### Steps to reproduce:

1. Click "Start meeting" in https://meet.jit.si

### Expected behavior:

The prejoin screen opens.

### Actual behavior:

Black screen opens.

<img src="https://i.imgur.com/gun0nhz.png" alt="drawing" width="200"/>

### Server information:

https://meet.jit.si

### Client information:

- Browser / app version: Opera 102.0.4880.78 arm64
- Operating System: macOS Version 13.2.1 (Build 22D68) 13.2.1 arm64

### Additional information:

Also reproduces on Windows 11

<details><summary>Error in console </summary>

```
TypeError: ad.attachMediaStream is not a function
    at hd.attach (JitsiTrack.js:235:22)
    at aG._attachTrack (Video.tsx:119:38)
    at aG.componentDidMount (Video.tsx:42:14)
    at wl (react-dom.production.min.js:261:217)
    at vl (react-dom.production.min.js:260:446)
    at yl (react-dom.production.min.js:259:431)
    at react-dom.production.min.js:283:96
    at kc (react-dom.production.min.js:281:398)
    at lc (react-dom.production.min.js:273:439)
    at qa (react-dom.production.min.js:127:105)
    at cc (react-dom.production.min.js:274:82)
    at Object.notify (Subscription.js:15:7)
    at Object.notifyNestedSubs (Subscription.js:85:15)
    at a (Subscription.js:90:20)
    at p (redux.js:220:32)
    at index.js:20:16
    at middleware.ts:20:12
    at middleware.ts:29:12
    at middleware.ts:19:20
    at middleware.ts:14:20
    at middleware.web.ts:23:20
    at middleware.any.ts:33:20
    at middleware.ts:63:12
    at middleware.ts:48:12
    at middleware.ts:60:12
    at middleware.ts:102:12
    at middleware.ts:50:12
    at middleware.ts:46:20
    at middleware.ts:28:12
    at middleware.ts:155:12
    at middleware.ts:44:20
    at middleware.ts:22:12
    at middleware.ts:52:12
    at middleware.ts:45:28
    at middleware.web.ts:35:12
    at middleware.web.ts:19:12
    at middleware.any.ts:52:20
    at middleware.ts:60:12
    at middleware.web.ts:273:22
    at middleware.ts:39:12
    at middleware.ts:21:12
    at middleware.ts:11:20
    at middleware.ts:16:12
    at middleware.ts:18:12
    at middleware.web.ts:24:12
    at middleware.any.ts:35:20
    at middleware.ts:41:12
    at middleware.ts:83:12
    at middleware.ts:26:12
    at middleware.web.ts:90:12
    at middleware.any.ts:83:12
    at middleware.ts:27:12
    at middleware.web.ts:17:12
    at middleware.any.ts:19:12
    at middleware.web.ts:17:20
    at middleware.any.ts:18:20
    at middleware.ts:32:20
    at middleware.web.ts:15:20
    at middleware.ts:254:12
    at middleware.ts:15:20
    at middleware.ts:36:12
    at middleware.ts:38:12
    at middleware.ts:65:20
    at middleware.ts:8:20
    at middleware.ts:29:12
    at middleware.ts:20:12
    at middleware.web.ts:105:12
    at middleware.any.ts:496:25
ps @ react-dom.production.min.js:189
```

</details>

**Comment by maihe** [comment]
I've been having the same problem for a week

**Comment by saghul** [comment]
What browser are you using?

**Comment by maihe** [comment]
@saghul Also Opera, OperaGX LVL5 (core: 102.0.4880.90) to be more specific

**Comment by Tursiops-G** [comment]
Same problem here (Black screen when starting Jit.si Meet)...Disabling adblocker/tracker/extensions didn't help.
Issue Started after a previous Opera One Update (Currently at 103.0.4928.16 )... Was Working Fine before all the updates.
If Opera doesn't address this issue soon, I'll have to kick Opera to the curb and move on to another browser. :(

**Comment by saghul** [comment]
Can you reproduce the problem on beta.meet.jit.si ?

**Comment by Tursiops-G** [comment]
YES... Works with the Beta site you posted...:)
What went afoul with the original site?

(FYI Also, (with the Original site), Opera would crash out when right-clicking on the lock icon in the URL bar)

**Comment by saghul** [comment]
> It WORKS with the Beta site you posted... :)
> What went afoul with the original site?

Beta is more current, which means it will all be fine when we update, which should happen soon.



> (FYI Also, (with the Original site), Opera would crash out when right-clicking on the lock icon in the URL bar)

That is part of Opera itself, so alas there is nothing we can do about it.

**Comment by Tursiops-G** [comment]
> Beta is more current, which means it will all be fine when we update, which should happen soon.

Hopefully Sooner, (because there's no inter-operability between the Beta site and the Current one).

Thanks! :)
