### ISSUE TITLE
Retrieve Participant Info data from Jitsi Meet (Android)

### ISSUE THREAD

**Issue by sagarsabhadiya** [jitsi/jitsi-meet#13908]
How to access Participant info list from Jitsi Meet?

**BroadcasrIntentHelper.class**

_public static Intent buildRetrieveParticipantsInfo(String requestId) {
        Intent intent = new Intent(Type.RETRIEVE_PARTICIPANTS_INFO.getAction());
        intent.putExtra("requestId", requestId);
        return intent;
    }_

### Description:

I am trying to get Participant Info list using this method from **BroadcastIntentHelper.class**. But getting issue with how to send request id from my activity class. Can you please help me with this?

- Jitsi Meet version: 6.0.0

Thanks,
Sagar

**Comment by saghul** [comment]
Please don't open duplicate issues.
