### ISSUE TITLE
No video between users

### ISSUE THREAD

**Issue by Mumuf** [jitsi/jitsi-meet#1391]
Hello!

I'm new to Jitsi Meet, with a fresh install in Debian Jessie with Nginx (and I'm French ... My English is bad :( )
I've read a lot here, but my problem is still unresolved ... So I ask for help!

My install is on Debian in a Virtual Machine.
In the web interface to Jisti meet:
* Create a room ok;
* Tchat ok;
* Local video ok ...
But no sharing of the video and micro between users.
I noticed this curious trick: the remote address show the local ip ???

How do change that?

Thank you for your help :)

![local_remote_address](https://cloud.githubusercontent.com/assets/26286124/23825392/47ac3036-0689-11e7-8ef1-04799c75ca6a.jpg)

**Comment by damencho** [comment]
Please use the mailinglist when having questions or problems, before opening issues.

Have you taken care of the ports forwarding tcp: 443 and 4443 and udp: 10000. If your virtual machine has internal address you need to setup in jvb its internal and external address, you need to setup NAT_HARVESTER_LOCAL_ADDRESS and NAT_HARVESTER_PUBLIC_ADDRESS 
https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_local_address.

**Comment by Mumuf** [comment]
Many thanks!! 

Yes, I had correctly taken care of the ports forwarding tcp: 443 and 4443 and udp: 10000 in the firewall, and as soon I put the local and the public ip in /ect/jitsi/videobridge/sip-communicator.properties then restarted, the video was ok for all. 
Even though now everything is ok, I will register to the mailinglist, to learn more and get a Jitsi Meet "aux petits oignons" ^^

**Comment by SlamDunkDcc** [comment]
The "NAT_HARVESTER_PUBLIC_ADDRESS" must be IP?   Can I configure the domain name?

Now I configured Nat, but it always show "CONFERENCE FAILED: conference.setup_failed Error: ICE fail"

**Comment by damencho** [comment]
Yes, those should be ip addresses, you need local and public.
