### ISSUE TITLE
safari safari-17.0, obs studio 30.0.0-beta3, osx sonoma: virtual cam selectable but not working

### ISSUE THREAD

**Issue by ikzelf** [jitsi/jitsi-meet#13917]
### Description:
When using safari on osx sonoma on Apple M2, with a running virtual camera presented by obs studio 30.0.0-beta3 I can see the virtual cam, even with content in the cam selector but when I select it, jitsi falls back to the built in Facetime HD camera.
The virtual cam is working fine in other apps, even Skype and also in [https://webcamtests.com/](https://webcamtests.com/)

### Steps to reproduce:

1. download OBM studio from [https://obsproject.com](https://obsproject.com) Choose Apple Silicon when needed.
2. start OBM studio after installing
3. go to the general settings and enable the Beta / Release candidate channels
4. check updates and download and install the latest beta
5. download a nice plugin from [https://github.com/obs-ai/obs-backgroundremoval/releases/tag/1.1.6](https://github.com/obs-ai/obs-backgroundremoval/releases/tag/1.1.6)
6. install it
7. restart OBS studio
8. Follow the instructions in the video on the obs-ai GitHub repository (it's about a v29 but works for the 30.0 beta too)
9. open [https://meet.jit.si](https://meet.jit.si)
10. start meeting (any meeting)
11. change preferences for Video and select OBS Virtual Camera
12. OK -> back to the default camera

### Expected behavior:

After selecting the OBS Virtual Camera I was hoping to see it in the meeting window.

### Actual behavior:

The selected camera is ignored and the actual camera is again the built in camera

### Server information:

- Jitsi Meet version: the hosted one, no idea how to list the version
- Operating System: macOS Sonoma - 14.0

### Client information:

- Browser / app version: safari 17.0
- Operating System: macos Sonoma - 14.0

### Additional information:

The same response as with ManyCam as virtual camera provider.

no logs / traces to show here. Since it works on [https://webcamtests.com/](https://webcamtests.com/) I hope there is an easy fix for jitsi too.

**Comment by saghul** [comment]
What resolutions does the virtual camera support?

**Comment by ikzelf** [comment]
taken from [https://webcamtests.com/](https://webcamtests.com/):
Webcam Name:	OBS Virtual Camera
Quality Rating:	269
Built-in Microphone:	None
Built-in Speaker:	None
Frame rate:	0 FPS
Stream Type:	video
Image Mode:	rgb
Webcam MegaPixels:	2.07 MP
Webcam Resolution:	1920×1080
Video Standard:	FHD
Aspect Ratio:	1.78
PNG File Size:	1.02 MB
JPEG File Size:	1.01 MB
Bitrate:	NaN undefined/s
Number of Colors:	3370

I hope this helps.

**Comment by saghul** [comment]
Can you try checking the supported resolutions in chrome://media-internals ?

**Comment by ikzelf** [comment]
Not sure if I understand you correctly, I am using Safari and not chrome. Where should I look for those supported resolutions?

**Comment by ikzelf** [comment]
I just found a private jitsi instance where the OBS Virtual Camera is working. How/where can I find the version of jitsi? It still is not working on https://meet.jit.si/

**Comment by saghul** [comment]
> Not sure if I understand you correctly, I am using Safari and not chrome. Where should I look for those supported resolutions?

Does Chrome work?

> I just found a private jitsi instance where the OBS Virtual Camera is working. How/where can I find the version of jitsi? It still is not working on https://meet.jit.si/

It be related to configuration. Check the video constraints in the instance's config.js vs https://meet.jit.si/config.js

**Comment by ikzelf** [comment]
What I see in the meet.jit.si/config.js:
constraints: {
        video: {
                    height: {
                ideal: 720,
                max: 720,
                min: 180
            },
            width: {
                ideal: 1280,
                max: 1280,
                min: 320
            },
            frameRate: {
                max: 30,
                min: 15
            }
        }
    }
in the private instance:
    // constraints: {
    //     video: {
    //         height: {
    //             ideal: 720,
    //             max: 720,
    //             min: 240,
    //         },
    //     },
    // }
I am not sure how to read this .... 1280*720 the max allowed resolution? Does this explain that the virtual cam is shown in the cam selector and refused to show after it has been selected?

**Comment by saghul** [comment]
Constraint processing can be tricky since it's quite browser dependent. Does your camera **only** support 1080p ?

**Comment by ikzelf** [comment]
working with OBS beta support channel to get that fixed. It should be possible to have different output resolutions.

**Comment by ikzelf** [comment]
Working with obs studio beta group to find how I can run with an other resolution. It should be possible.

**Comment by ikzelf** [comment]
For some reason the changes I do in obs have no success in jitsi. There is quite a list of predefined resolutions:
![image](https://github.com/jitsi/jitsi-meet/assets/496774/a45d9dec-bb8e-4fb9-87e1-3727e74bf8c0)

**Comment by saghul** [comment]
Does 720p not work?
