### ISSUE TITLE
BreakoutRoom Raise Condition In Timer

### ISSUE THREAD

**Issue by yilmazesrahatice** [jitsi/jitsi-meet#13914]
### Description:

Hi,

To prevent flooding of breakout messages, broadcasting of latest breakout rooms are done by a timer. 
However, we found a raise condition in this timer functionality.

If moderator tries to remove a breakoutroom, it is removed from main_rooms_map. Then broadcast_breakout_rooms is called. If timer is already set for another action (occupant join, occupant left etc..)  then broadcast is not done at the moment. 

```
function destroy_breakout_room(room_jid, message)
    local main_room, main_room_jid = get_main_room(room_jid);

    if room_jid == main_room_jid then
        return;
    end

    local breakout_room = breakout_rooms_muc_service.get_room_from_jid(room_jid);

    if breakout_room then
        message = message or 'Breakout room removed.';
        breakout_room:destroy(main_room and main_room_jid or nil, message);
    end
    if main_room then
        if main_room._data.breakout_rooms then
            main_room._data.breakout_rooms[room_jid] = nil;
        end
        main_room:save(true);

        **main_rooms_map[room_jid] = nil;**
        broadcast_breakout_rooms(main_room_jid);
    end
end

```

Then, when the timer is expired, main_room is been searched by breakoutroom_jid. However, it can not be found since it has been removed.  In that case following code returns and this timer is remains forever in main_room. That's why any other broadcast mesage is not send any more. 

```
function broadcast_breakout_rooms(room_jid)
    local main_room = get_main_room(room_jid);

    if not main_room or main_room.broadcast_timer then
        return;
    end
```

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/09c085477907527cb19c1651312ed1701d9092dd
