### ISSUE TITLE
Chromium users' videos are green on firefox clients

### ISSUE THREAD

**Issue by laurentS** [jitsi/jitsi-meet#13918]
### Description:

People's cameras look green when more than 2 people join a meeting.
The screenshot below is from a call today on meet.jit.si. The one participant top left is myself.
![2023-10-06_10-33](https://github.com/jitsi/jitsi-meet/assets/1745184/1ba0db15-c5ae-4443-8a60-730334e78098)

### Steps to reproduce:

1. Start a call with firefox (it does not seem to matter whether it's started here or not)
2. Join the same call with chrome/chromium and share video (not screen, just the webcam). So far, so good.
3. Join the same call as a third participant (I used my android phone)
4. See the green faces in firefox for the participant that use chrome/chromium turn green.
5. Participants using other clients seem to work fine (tested with firefox 118 and android 23.4.0, both work fine)
6. If android participant drops out, the video reverts to normal colours after a few seconds.
7. if android participant joins in again, chromium user becomes green again almost immediately

### Expected behavior:

People shouldn't look green :)

### Actual behavior:

See above.

### Server information:

- Jitsi Meet version: not sure, it's on meet.jit.si (observed at least from August 4th up to today). I do not run my own server, so can't comment further.

### Client information:

- Browser / app version: Firefox `118.0-1` (debian package version) (and I suspect 117 which was my version back when this first appeared), and chromium 117 (at least, I'm not sure about other people's versions/OSes)
- Operating System: debian sid/unstable

### Additional information:
Seems related to #13860 

I am not entirely sure if this is firefox or jitsi, but jitsi is the only calling app I have seen this in.

**Comment by saghul** [comment]
I was unable to reproduce this using Firefox on macOS, I'll try Linux.

**Comment by fippo** [comment]
I can reproduce with two Windows Chrome's and a Linux Firefox.
Does setting `media.hardware-video-decoding.enabled` in about:config and restarting fix it?

**Comment by saghul** [comment]
Ping @JonathanLennox @jallamsetty1

**Comment by Pehrsons** [comment]
This seems like a typical hw codec issue. Could you [file a bug with Firefox](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Audio/Video:%20Playback)?

**Comment by laurentS** [comment]
> Does setting `media.hardware-video-decoding.enabled` to `false` in about:config and restarting Firefox fix it?

@fippo yes it does, with the setting to `false`, the video looks fine.

With hw decoding enabled, I noted that when changing the "performance setting", the video is only green for the 2 highest perf settings. On the lower ones, video is either off or not green. This applies whether I change the setting in firefox (receiving the video stream from chromium) or chromium (the sender of the video stream).
When using picture-in-picture, it's still green.
It says it's using codec `VP9`.

@Pehrsons Happy to open a ticket there if you think the issue belongs there.

**Comment by Pehrsons** [comment]
Please do. I don't think we have this issue with green video when doing vp9 hw decode on file.

**Comment by laurentS** [comment]
> Please do. I don't think we have this issue with green video when doing vp9 hw decode on file.

Filed under https://bugzilla.mozilla.org/show_bug.cgi?id=1858904

**Comment by laurentS** [comment]
Just to confirm that this is now solved for me :) Thank you everyone who worked on it!
