### ISSUE TITLE
Shared Whiteboard issue with JWT auth

### ISSUE THREAD

**Issue by daimoc** [jitsi/jitsi-meet#13921]
### Description:

When using the Whiteboard feature in a JItsi-Meet instance secured by JWT, people connected with the token are not connected to the same Whitebord as other users.

In fact the room id used to connect to the excalidraw backend is made with  the variable LocationURL.href  : 
https://github.com/jitsi/jitsi-meet/blob/a4d3fb6c708d191057c3452f9c840bbb6bf9193c/react/features/whiteboard/functions.ts#L78

This href variable contains the url parameters with the jwt token so the computed Whiteboard room is deferent for people with token and other peoples. It is also different for 2 peoples with different token. 

### Steps to reproduce:

1. Open a new room in meet.jit.si and authenticate yourself.
2. Open a new browser in this room, (in incognito mode, to avoid sending the Token from the first user)
3. Open the Whiteboard in the two browser. 

### Expected behavior:

The shared whiteboard should work.

### Actual behavior:

Whiteboard content is not shared between the 2 participants.

### Server information:

- Jitsi Meet version: last stable 
- Operating System: any

### Client information:

- Browser / app version: Chrome or Firefox
- Operating System: any

### Additional information:

I'll make a Pull Request to avoid using the JWT in the Whiteboard Room Id computation.

**Comment by damencho** [comment]
I think, we should be using instead of href, the pathname.

**Comment by damencho** [comment]
Good catch!

**Comment by daimoc** [comment]
Hi, 
After looking a little more into how the ID of the Whiteboard is generated, it seems it can be easily predictable if a user knows the conference URL.
For the Etherpad integration, there is an option to generate a shared document random id in the Jicofo side : https://github.com/jitsi/jicofo/blob/839b2126cddbc3a35e591aa942e61bc0149a2b09/jicofo-selector/src/main/resources/reference.conf#L222 

Do you think, it can be a good idea to extend this mechanism to enable a more secure Whiteboard ID generation ?

**Comment by saghul** [comment]
I don't think it's important because the content is end to end encrypted and the user would need to be part of the meeting to get the randomly generated key.

Just fixing the room ID would be enough.

Great catch!
