### ISSUE TITLE
Separate audio input and output settings

### ISSUE THREAD

**Issue by MaxHillebrand** [jitsi/jitsi-meet#13924]
**Is your feature request related to a problem you are facing?**

It is not possible to receive audio on Bluetooth earbuds while using a USB wired microphone.

In the audio setting, there is Bluetooth, which uses the earbuds for both sound and microphone; or headphones, which uses the USB microphone but does not emit sound at all.

**Describe the solution you'd like**

Enable separate controls for audio inputs (microphone) and audio output (speakers/headphones) 

**Describe alternatives you've considered**

Handle the case automatically in the background.

**Comment by saghul** [comment]
I suppose this is on mobile? Are you using Android or iOS?

**Comment by MaxHillebrand** [comment]
Mobile Android, in both the app and the browser.

**Comment by saghul** [comment]
Have you seen support for that in other apps? Last I checked there wasn't an API available to select the input device.

**Comment by MaxHillebrand** [comment]
For example with Signal, in a voice message the USB microphone is picked up, and the voice message playback is on the Bluetooth earbuds. But in a call, it is the same problem as with jitsi, only a single audio setting, with either Bluetooth earbuds (both input and output), or USB microphone (but no Audio output at all).

**Comment by saghul** [comment]
Si it's the same then. Recording audio as a dedicated action is different than having a call.
