### ISSUE TITLE
Recording with Jitsi

### ISSUE THREAD

**Issue by jacq0123** [jitsi/jitsi-meet#1392]
Hello,
Has the recording issue on Jitsi been fixed? We couldn't make it work months ago.

**Comment by saghul** [comment]
Please be specific. What issue? What did you test? What didn't work? Have you tried again?

AFAICT recording works fine, please send an email to the mailing list for questions, or open an issue detailing your problem.

**Comment by jacq0123** [comment]
Hello, Could you please check the contents of the page and screenshot below? It seems like the recording is still in experimental stage. 
https://github.com/jitsi/jibri 
https://neu1-api.asm.skype.com/v1/objects/0-neu-d4-6cd40ebdcc1ec4006173f04aa689df24/views/imgpsh_fullsize

**Comment by saghul** [comment]
> screenshot below?

I can't open it :-O Can you attach it here please?

> It seems like the recording is still in experimental stage.

Not really the case. We have been using it in production for a long time now. There has been a lot of work stabilizing it recently (https://github.com/jitsi/jibri/pull/26), plus adding SIP gateway support (https://github.com/jitsi/jibri/pull/29). I agree we currently don't have good documentation though.

**Comment by jacq0123** [comment]
Could you please help providing some documentation on the installation and configuration of the recording? I'm attaching the screenshot here.

________________________________

**Comment by saghul** [comment]
I still don't see any screenshot :-S

**Comment by jacq0123** [comment]
![screen shot 2017-03-15 at 6 42 43 am](https://cloud.githubusercontent.com/assets/26360432/23949569/15ea2bca-095e-11e7-9767-aaf3047a4cbe.png)
I included a screenshot.

**Comment by saghul** [comment]
> Please we need directions on how to configure the recording.

Please open an issue in the jibri repo (https://github.com/jitsi/jibri) so we track it down.

**Comment by jacq0123** [comment]
Done here https://github.com/jitsi/jibri/issues/31


Thanks!


________________________________
