### ISSUE TITLE
Lobby "ask to join" page does not respect "readOnlyName" setting in config.js

### ISSUE THREAD

**Issue by Dzeinuda** [jitsi/jitsi-meet#13928]
### Description:

We are selfhosting our Jitsi setup. We are using our own external JWT provider, which supplies a display name in the payload. We are using the "readOnlyName: true" setting to prevent participants from changing the name supplied by the JWT. In Prosody we are using the "frozen_nick" module to prevent changes to display_name). If a moderator enables the lobby feature, participants will be able to change the JWT-provided display name while on the "ask to join" page. This only happens if the "prejoinPage" is disabled.

### Steps to reproduce:

(0. "readOnlyName: true", "prejoinPageEnabled: false")

1. Utilize JWT authentication and start a meeting as a moderator.
2. Enable the lobby feature.
3. Guest joins with JWT and is now able to change displayname before asking to join.

### Expected behavior:

the readOnlyName: true setting should prevent participants from chaning their displayname, supplied by the JWT payload.

### Actual behavior:

Participants are allowed to change their displayname before asking to join, if lobby is enabled and prejoinPage is disabled.

### Server information:

- Jitsi Meet version: 2.0.7303-1
- Operating System: Debian 11,  Linux 5.10.0-25-amd64

### Client information:

- Browser / app version: Chromium
- Operating System: Linux Mint LMDE 4

**Comment by saghul** [comment]
@Calinteodor can you PTAL?

**Comment by Calinteodor** [comment]
Hey! Thank you for your patience. The fix will be available in the next release.

**Comment by Dzeinuda** [comment]
Absolutely! Thanks for reviewing the issue.
Have a good weekend.
