### ISSUE TITLE
Video artifacts when sharing screen

### ISSUE THREAD

**Issue by prudloff-insite** [jitsi/jitsi-meet#13932]
### Description:

When some users shares their screen, the other users gets heavy video artifacts.

![Screenshot 2023-10-09 at 16-18-40 Jitsi Meet](https://github.com/jitsi/jitsi-meet/assets/50333926/4452ad8d-1b3d-42c9-99e4-32b748dd04f6)

This seems to only happen when specific users are sharing their screen, but we couldn't identify what could be different with their setup.

### Steps to reproduce:

1. User A start sharing their screen.
2. User B sees the screen with a correct resolution, but when user A moves things around in their UI (windows, etc.), user B starts getting heavy artifacts.

### Expected behavior:

Screen sharing sends a clear picture.

### Actual behavior:

Screen sharing sends a buggy video feed.

### Server information:

- Jitsi Meet version: 2.0.8922-1
- Operating System: Debian GNU/Linux 11 (bullseye)

### Client information:

- Browser / app version: Firefox 118.0.1
- Operating System: Linux Mint 21

### Additional information:

Here is a browser log from the user sharing their screen (Chrome on Linux):
[Jitsi-screenshare-sender-logs.txt](https://github.com/jitsi/jitsi-meet/files/12847259/Jitsi-screenshare-sender-logs.txt)

And from the other user (Firefox on Linux):
[Jitsi-screenshare-receiver-logs.txt](https://github.com/jitsi/jitsi-meet/files/12847258/Jitsi-screenshare-receiver-logs.txt)

**Comment by prudloff-insite** [comment]
It seems the bug only happens when the receiving user uses Firefox.

**Comment by prudloff-insite** [comment]
Duplicate of #13860

**Comment by saghul** [comment]
Closing as a dupe
