### ISSUE TITLE
Remote controle of Android Tv doesn’t work 

### ISSUE THREAD

**Issue by SmarterVision** [jitsi/jitsi-meet#13938]
Hello there,
I’m Using JitsiMeet Kotlin SDK for my Android TV app, everything is working, but when I start the meeting the remote control doesn’t work on the JitsiMeetActivity
Can you please advice

**Comment by saghul** [comment]
Hey there! I'm afraid we don't currently have support for Android TV on the SDK.

While it will runs, as you saw, the input handling is not implemented so navigating with the remote does not work.

**Comment by SmarterVision** [comment]
Thank you for your response 
is there any way to remove all Jitsi Meet buttons?

**Comment by saghul** [comment]
Not at this time. You'd need to go and edit the code and rebuild the SDK.
