### ISSUE TITLE
Language detector finds `sv-SE`, unable to resolve to `sv`, falls back to defaultLanguage

### ISSUE THREAD

**Issue by jgarplind** [jitsi/jitsi-meet#13935]
### Description:

I've spent some time trying to understand why the Jitsi UI is in English (default language on the server) in some browsers (specifically Android WebView), and in Swedish in other browsers (really any "normal" browser that I use in my daily workflow).

[This great comment](https://community.jitsi.org/t/default-language/114671/20) lead me to the [implementation of the language detector](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/customNavigatorDetector.ts#L20) (great feature!), and by comparing the `window.navigator.languages` in each browser, I found that:
:white_check_mark: `['sv', 'en', 'en-GB', 'en-US']` resolves to Swedish
:x: `['sv-SE', 'en-US']` does not resolve to Swedish

This I suppose is because our Jitsi server (as would most, it is an unchanged server running Jitsi meet `2.0.8615-1`) has language files for `sv`, but not for `svSE` (which is what I expect the language detector to output).

### Steps to reproduce:

Run Jitsi Meet inside Android WebView on a Swedish device.

### Expected behavior:

Swedish language should be detected.

### Actual behavior:

English language (defaultLanguage from server) is shown instead.

### Server information:

- Jitsi Meet version: 2.0.8615-1
- Operating System: Ubuntu 22.04.2 LTS

### Client information:

- Browser / app version: @jitsi/react-sdk@1.3.0 inside a WebView
- Operating System: Android

### Additional information:

I assume this is a (small) bug in the language detector? I can't speak for all language variations, but for Swedish, any variation is minor, so falling back from `svSE` to `sv` makes a lot more sense than jumping from `svSE` to whatever the server default is.

**Comment by saghul** [comment]
We do some of that on the native app: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/languageDetector.native.ts#L19 maybe we out to do something similar here.

Is this something you want to try out?

**Comment by jgarplind** [comment]
I might have, but I just found a solution (which is not documeted?) for my use case using the client side config set in the React SDK: https://github.com/jitsi/jitsi-meet-react-sdk/issues/36.

As such, I can't motivate spending time on improving the language detector right now, even though I think it would be a nice thing to do.
