### ISSUE TITLE
Reconnect should always skip preJoin page

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#13948]
### Description:

When a conference fails, the browser is trying to re-connect and counts down the seconds. However, the user then is shown the preJoin page instead of being again in the video conference. 

### Steps to reproduce:

1. Let conference fail (restart bridge or prosody)
2. Wait 30 seconds
3. You are on the preJoin page so that you have to actively click a button to join again the conference

### Expected behavior:

When the conference fails, users expect that after some period they are automatically reconnected to the room. 

### Actual behavior:

When conference fails, users are waiting and probably do not recognize that they have to click on the join button again. 

Typical use case is a remote yoga session - all participants would need to go to their laptop and click to join again the conference. They would not even recognize when the conference fails for some seconds, if it would automatically reconnect diectly into the session.  

Prosody can not be configured for HA on kubernetes as it does not support clustering, so in rare cases when the prosody pod moves to another worker all conferences are interrupted.

### Workaround:

         ENABLE_PREJOIN_PAGE: "0"

However, we would like to offer users to check their camera and audio before joining a conference.

### Server information:

- Jitsi Meet version: stable-8960 (Docker)              
- Operating System: Jitsi on kubernetes 

env:        
         ENABLE_PREJOIN_PAGE: "1"

**Comment by saghul** [comment]
I believe this was done already.

**Comment by dberardo-com** [comment]
is this also the case for lobbies when admitting users ? 

would be nice that in case of reconnection moderators should not readmit all users again, the first admission should be enough, unless of course the moderator decides to reject the user for reasons other then disconnection
