### ISSUE TITLE
Hide Participant in mobile App

### ISSUE THREAD

**Issue by vshalvaghasiya** [jitsi/jitsi-meet#13941]
pod 'JitsiMeetSDK', '~> 8.4'

```
            builder.setFeatureFlag("add-people.enabled",withBoolean: false)
            builder.setFeatureFlag("invite.enabled",withBoolean: false)

```

![189880606-c9b20547-9715-40b5-836b-d30a05f075be](https://github.com/jitsi/jitsi-meet/assets/24429336/9cb3313f-e160-4f16-80e1-7399c81f9467)

**Comment by saghul** [comment]
You are using an old SDK version. Please supdate. The one you are using does not support those flags.

**Comment by vshalvaghasiya** [comment]
Now I'm Install latest Version

**Comment by vshalvaghasiya** [comment]
@saghul check my comment.

**Comment by saghul** [comment]
Yes, that is the participants list, the invite participabts button (add people) is hidden. What do you want to hide?

**Comment by vshalvaghasiya** [comment]
I was trying to Hide this one button. but the button always showing. 
Top right Participant button.

![274554824-8153bb46-ffef-4055-ac87-5c5a7d1af11e](https://github.com/jitsi/jitsi-meet/assets/24429336/dbb25bc2-06f5-430b-a078-3277785f127a)
