### ISSUE TITLE
On premeeting-screen, below <div> with new-toolbox id, <div> alert role have forgetting parameter css 

### ISSUE THREAD

**Issue by ThonyBat** [jitsi/jitsi-meet#13945]
### Description:

Green circle device status isn't round but oval

### Steps to reproduce:

1. Open firefox
2. Go to Jitsi Meet
3. Start conference
4. See status device

### Expected behavior:

Green dot expected round

### Actual behavior:

Green dot oval actual
![image](https://github.com/jitsi/jitsi-meet/assets/73229853/a6fccad3-f146-421b-8ccb-c5ff92dca630)

### Server information:

- Jitsi Meet version: lib-jitsi-meet.min.js?v=7542.4367
- Operating System: meet.jit.si at 2023-12-10

### Client information:

- Browser / app version: Firefox 118.0
- Operating System: Windows 11

### Additional information:

Solution is just add "flex: 1;" on span
![image](https://github.com/jitsi/jitsi-meet/assets/73229853/a05988c1-e502-413b-8502-671b03c3c7d9)

**Comment by tony83033** [comment]
@ThonyBat  Sir, can I work on this issue?

**Comment by saghul** [comment]
No need to ask, feel free to send a PR!
