### ISSUE TITLE
How can I Hide the participant List Button in the IOS App?

### ISSUE THREAD

**Issue by vshalvaghasiya** [jitsi/jitsi-meet#13943]
I was using Lates Lib.
pod 'JitsiMeetSDK', '~> 8.5'

```
builder.setFeatureFlag("add-people.enabled",withBoolean: false)
builder.setFeatureFlag("invite.enabled",withBoolean: false)
builder.setFeatureFlag("participants-pane", withBoolean: false)
```

![IMG_0110](https://github.com/jitsi/jitsi-meet/assets/24429336/3fa74b05-119b-411f-9b4f-49b2463b3f94)
![IMG_0111](https://github.com/jitsi/jitsi-meet/assets/24429336/8153bb46-ffef-4055-ac87-5c5a7d1af11e)
![Screenshot 2023-10-12 at 3 07 59 PM](https://github.com/jitsi/jitsi-meet/assets/24429336/80b486ec-9c83-4f7a-a117-0efae0740dc4)

If any solution, please send me.

**Comment by saghul** [comment]
The invite button (add people) is hidden. What you see is the participants list.

**Comment by vshalvaghasiya** [comment]
I was trying to Hide this one button. but the button always showing.

![274554824-8153bb46-ffef-4055-ac87-5c5a7d1af11e](https://github.com/jitsi/jitsi-meet/assets/24429336/b4b2ac2e-3b8e-4723-b634-6cb17feea63e)

**Comment by vshalvaghasiya** [comment]
> The invite button (add people) is hidden. What you see is the participants list.

how to hide the Participants list button?

**Comment by ShivaniBhojani** [comment]
@saghul  I have Same Issue in Android. How to hide Participant List Button?

**Comment by saghul** [comment]
There is currently no flag to hide that button.

**Comment by vshalvaghasiya** [comment]
@saghul any other treat? I can hide this button.

**Comment by saghul** [comment]
No, there currently isn't a way to hide it. A PR would be acceptable though.

**Comment by vshalvaghasiya** [comment]
@saghul

**Comment by saghul** [comment]
PR s are welcome :-)
