### ISSUE TITLE
Jitsi not working on deployed React TS

### ISSUE THREAD

**Issue by JMSevilla** [jitsi/jitsi-meet#13944]
I have this code on my C# 

var jwtBuilder = JitsiServerSide.Builder();
            var privateKey = JitsiServerSide.ReadPrivateKeyFromFile("Templates/jitsi_api_key.pk", PKType.PKCS8);
            jwtBuilder
                .WithAudienceAndIssuer()
                .WithApiKey("--key--")
                .WithUserName(userName)
                .WithUserEmail(userEmail)
                .WithUserAvatar("")
                .WithAppID("--key--")
                .WithLiveStreamingEnabled(false)
                .WithRecordingEnabled(true)
                .WithOutboundCallEnabled(true)
                .WithTranscriptionEnabled(true)
                .WithModerator(true)
                .WithRoomName("*")
                .WithUserId(Convert.ToString(userId));

            // Sign the JWT token
            var jwtToken = jwtBuilder.SignWith(privateKey);
            return jwtToken;

Whenever I try to use it on localhost it is working fine. but whenever I want to access it on my deployed react TS it didn't work. 

I deploy my .net core on heroku

**Comment by saghul** [comment]
We don't have a C# library, so I don't know what could go wrong there.

Check your server has valid TLS certificates, it might be due to that.
