### ISSUE TITLE
Jitsi Library Version 8.5.0 is not working in Android

### ISSUE THREAD

**Issue by ShivaniBhojani** [jitsi/jitsi-meet#13947]
Latest Jitsi Library not working in android. I'm getting this error which shown in below screenshot.

![ipmsgclip_r_1697170199_0](https://github.com/jitsi/jitsi-meet/assets/85148949/1bdb8480-eb71-4290-8c21-c31d94c8a712)

**Comment by saghul** [comment]
Did you add our maven repo URL?

**Comment by ShivaniBhojani** [comment]
yes, Look at this.

![img_20231013](https://github.com/jitsi/jitsi-meet/assets/85148949/4b5ac0de-89f1-48ed-a1a9-f92f60e4c25d)

**Comment by ShivaniBhojani** [comment]
@saghul Jitsi Version 8.1.2 is working properly in my android studio. but Latest version is not working

**Comment by saghul** [comment]
Closing since this was an error on the user side (commented on the community).
