### ISSUE TITLE
Jitsi Android app allows user to change DisplayName when user should be unable to enter a DisplayName

### ISSUE THREAD

**Issue by c-prompt** [jitsi/jitsi-meet#13946]
### Description:

When using either a desktop or Android browser, the pre-defined display name shows but is **correctly not changeable** based upon my configuration:

In /etc/jitsi/meet/config.js, I have:

```
     // Require users to always specify a display name.
    requireDisplayName: false,

    prejoinConfig: {
    //     // When 'true', it shows an intermediate page before joining, where the user can configure their devices.
    //     // This replaces `prejoinPageEnabled`.
         enabled: true,
    //     // Hides the participant name editing field in the prejoin screen.
    //     // If requireDisplayName is also set as true, a name should still be provided through
    //     // either the jwt or the userInfo from the iframe api init object in order for this to have an effect.
         hideDisplayName: true,
    //     // List of buttons to hide from the extra join options dropdown.
         hideExtraJoinButtons: ['no-audio', 'by-phone']
    },
```

My meeting token includes:

```
// Create token payload as a JSON string
$payload = json_encode([
	"context" => [
		"user" => [
		"name" => $username
		]
	],
```

My script includes:

```
$script = "<script>
            var domain = 'meet.mydomain.com';
            var options = {
                roomName: '$room',
		userInfo: { 'displayName': '$username' },
                width: '100%',
                height: '100%',
		jwt:'" . $jwt . "',
            }
            var api = new JitsiMeetExternalAPI(domain, options);
        </script>";
```

However, when selecting "Join in app":

![Jitsi Android screenshot_1](https://github.com/jitsi/jitsi-meet/assets/10625352/e452f2f0-2594-4ffa-a650-5c4b386256d4)

...and using the Jitsi app (version 23.5.0 build 14934615), the display name is automatically populated but **incorrectly able to be changed**. The DisplayName is specifically sent to prevent users changing their names to appear as someone else.

When ```requireDisplayName: false```, the DisplayName should be unable to be changed in the Jitsi Android app. (Again, to be clear, it does work correctly on the desktop and Android browsers.)

Additionally, when ```hideDisplayName: true```, the DisplayName shouldn't be shown but it is on desktop browsers, Android browsers, and the Jitsi app (this isn't an issue to me though as long as the DisplayName can't be changed).

Reference: #7905 

### Server information:

- Jitsi Meet version: 2.0.8960-1
- Operating System: 11 (bullseye)

### Client information:

- Browser / app version: Android Chrome (works) / Jitsi app 23.5.0 build 14934615 (doesn't work)
- Operating System: Android 13.1

**Comment by Dzeinuda** [comment]
We have the exact same issue - just as well on the iOS app i think.

I believe it has to do with some hardcoded settings in the smartphone application code that essentially "overwrites" the serverside config.js, the same with the jitsi-meet-electron app. In the latter case the electron app can be unpacked and these configOverwrite values can be changed so that the displayName cannot be altered - but we havn't yet found a way to do this for the iOS or Android app.

**Comment by saghul** [comment]
@Calinteodor can you PTAL when you get a chance?

**Comment by mysterty** [comment]
Actually, the issue still happen, also in firefox, can't change username... It always switch to default login name
