### ISSUE TITLE
Jitsi not working properly, throwing error (very likely user error when configured)

### ISSUE THREAD

**Issue by LongShanksBraveHeartKiller** [jitsi/jitsi-meet#1394]
HI all, thanks for the great work on this project.

I am having an issue or several. I rolled an internal Jitsi videobridge/meet server on our local LAN(no outside connectivity). When I navigate to the IP I am put into a room with limited options(when compared to public test) and when someone else connects to the same room we don't see each other in the user list. The buttons also appear to be non functional(mostly) and the session data all says N/A. After a few minutes and error pops up. Screen shots below. Any idea? This is using both FF and Chrome, same behavior on both. 
![jitsierror](https://cloud.githubusercontent.com/assets/17896650/23869913/1fb0a616-07fb-11e7-8025-a4c304bc3ab4.JPG)
![jitsierror3](https://cloud.githubusercontent.com/assets/17896650/23869915/1fb54054-07fb-11e7-9f21-6a3eefc7727f.JPG)
![jitsierror2](https://cloud.githubusercontent.com/assets/17896650/23869914/1fb28da0-07fb-11e7-9ef4-dbe876aa33ea.JPG)

Thanks in advance!

**Comment by saghul** [comment]
Can you please check the console errors and jicofo logs?

**Comment by LongShanksBraveHeartKiller** [comment]
Got it figured out.. brutally. Turns out anything less than the server IP set as the "hostname" for jitsi would result in these errors. Thanks again!

**Comment by saghul** [comment]
Glad it's working for you! I'll go ahead and close this then!
