### ISSUE TITLE
Room destruction/creation timing issue -> "Sorry! You are not allowed to be here :("

### ISSUE THREAD

**Issue by jgarplind** [jitsi/jitsi-meet#13957]
### Description:

If a user leaves a room right before a user joins, the second user sometimes faces a screen saying "Sorry! You are not allowed to be here :(", rather than the expected empty room.

### Steps to reproduce:

1. User 1 joins the room, and we can see in prosody logs that a part of this process is that the room is created.
2. User 1 leaves the room, and we can see in prosody logs that a part of this process is that the room is destroyed.
3. ⏲️(timing critical, window of ~2 seconds?) User 2 joins the room at basically the same time as User 1 leaves the room
4. User 2 faces the auth error screen, saying "Sorry! You are not allowed to be here :("

### Expected behavior:

In order of preference:
1. The room should be re-created
2. User 2 could is "kicked out" automatically, avoiding the strange state
3. There is some way to recover from the auth error page, e.g. a button/link with configurable behavior

### Actual behavior:

User 2 faces the auth error screen, saying "Sorry! You are not allowed to be here :("

### Server information:

`dpkg -l | grep jitsi`
ii  jitsi-meet                             2.0.8615-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                     1.0.7235-1                              all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-tokens                      1.0.7235-1                              all          Prosody token authentication plugin for Jitsi Meet
ii  jitsi-meet-turnserver                  1.0.7235-1                              all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                         1.0.7235-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                  1.0.7235-1                              all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                     2.3-19-gb286dc0c-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                             0.4.1-jitsi1                            all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                        2.1.0.10-jitsi1                         amd64        JSON parser/encoder for Lua

- Jitsi Meet version: 2.0.8615-1
- Operating System: Ubuntu 22.04

### Client information:

- Browser / app version: Android WebView / Chrome / Edge, roughly latest version
- Operating System: Windows/macOS/Android

### Additional information:
We are using `mod_claim_moderator.lua` to support our use case where 1-on-1 calls between "power users" (User 1 in scenario above) and "normal users" (User 2 in scenario above) are supposed to have only the "power users" as moderators.

See attachments "OK" and "NOT_OK":
[OK.txt](https://github.com/jitsi/jitsi-meet/files/12916028/OK.txt)
[NOT_OK.txt](https://github.com/jitsi/jitsi-meet/files/12916029/NOT_OK.txt)

OK: Room is destroyed upon User 1 leaving, and re-created (2 seconds later) upon User 2 joining
NOT_OK: Room is destroyed upon User 1 leaving, but never re-created (prosody logs don't have any information about User 2 not being able to join)

**Comment by damencho** [comment]
Do you reproduce the issue if you disable the custom modules you added to config? 
Using the stock prosody config.

**Comment by jgarplind** [comment]
I'll try to set off some time and investigate that.

Thanks for engaging.

**Comment by jgarplind** [comment]
@damencho in fact, it reproduces with approximately the same frequency, even when `mod_claim_moderator` is disabled.

**Comment by damencho** [comment]
Even with event_sync disabled?

**Comment by jgarplind** [comment]
.. we shall soon find out :)

**Comment by damencho** [comment]
If you still reproduce, try enabling prosody debug and attach the logs reproducing it with debug on.

**Comment by jgarplind** [comment]
Sorry, can you clarify where I can increase the prosody log level? Can't find any resource which makes it clear exactly how to do it.

**Comment by jgarplind** [comment]
We did in fact reproduce it.

Will share debug logs soon, just need to sharpen my rusty remote Linux-server skills and mask any sensitive data before sharing.

**Comment by damencho** [comment]
Is the debug just from the non working case?

**Comment by jgarplind** [comment]
It's a 5 minute window in which there were some successful attempts (error not reproduced), and finally, one non-successful attempt (error reproduced).

Roughly 3-4 successful attempts before the error re-surfaced.

.. I assume you are asking because you want the most isolated logs possible? Would it help if we cleared the logs after every successful attempt, to ensure you only see what happens when the error re-produces?

**Comment by damencho** [comment]
> .. I assume you are asking because you want the most isolated logs possible? Would it help if we cleared the logs after every successful attempt, to ensure you only see what happens when the error re-produces?

yes, please.

**Comment by damencho** [comment]
Is this the upstream jitsi-meet with no modifications? Can you reproduce the same on alpha.jitsi.net? 
And the second user tries directly to join the room without sending a conferenceIq to jicofo ... which maybe is the problem as   the room is destroyed and jicofo is the one that needs to be the room creator/the first to join ...

**Comment by jgarplind** [comment]
I'll check with my colleague tomorrow morning. Thanks for your insights and continued engagement :)

**Comment by jgarplind** [comment]
> Hum, it is not just leaving but destroying the room via end_conference.
> 
> ```
> Oct 16 15:14:33 endconference.meet-test.company.com:end_conference	info	Room dcc35593-daed-43b6-ae57-7741fbf4f672@conference.meet-test.company.com destroyed by occupant 1116d55b-76e8-4231-9932-a52f3646394d@meet-test.company.com/shlQBuvTR_Fz
> ```
> 
> Is this the case?

Indeed, we have observed that the room is being _destroyed_.

I am not aware of what `end_conference` translates to, but we have tested 2 scenarios:
1. The moderator clicks "End call for everyone" and the other user joins the call at that same moment.
2. The moderator clicks "Leave call" and the other user joins the call at that same moment.

So no matter which UI control the moderator uses when he/she is alone in the conference, the behavior reproduces.

> Is this the upstream jitsi-meet with no modifications?

Yes, with the versions mentioned in the issues.

> Can you reproduce the same on alpha.jitsi.net?

Yes, in fact, my colleague just managed to do that, using a room name called `sagasrum`

> And the second user tries directly to join the room without sending a conferenceIq to jicofo ... which maybe is the problem as the room is destroyed and jicofo is the one that needs to be the room creator/the first to join ...

Sorry, I don't understand these details fully. It was now reproduced simply by joining the same room from 2 different browser tabs, with the sequencing mentioned before.

**Comment by jgarplind** [comment]
@damencho does this input, in particular the fact that it reproduces on alpha.jitsi.net help us move this forward in any way?

I understand that you have many priorities to attend to, however, I just wanted to confirm that we now share the view that this is an issue with stock Jitsi, and that you will hopefully let us know if you plan to address it, postpone it, or want help to further investigate.

Thanks in advance.

**Comment by damencho** [comment]
Yep, we will take a look. Probably next week. It seems to me this is a jicofo issue, but we will see.

**Comment by jgarplind** [comment]
Hi @damencho. Thanks a lot for looking into the issue and resolving it 🎉

What is the (typical) road from here to getting it to run on our self-hosted Jitsi?

Will you include it in a future release (supposedly weeks or months from now based on your typical release schedule?) that we can download and upgrade to?

**Comment by damencho** [comment]
It will soon go into unstable, then just changing to unstable repo and updating will bring it on to your deployment.
We should soon release meet.jit.si and soon after that a stable release, so it will soon hit stable.
