### ISSUE TITLE
Self view of screensharing is initially wrongly sized

### ISSUE THREAD

**Issue by vpzomtrrfrt** [jitsi/jitsi-meet#13968]
### Description:
Usually, the large video is scaled to allow the whole shared screen to be displayed. However, this does not appear to be the case for viewing your own shared screen until resizing the window.

### Steps to reproduce:

1. Join a meeting
2. Share your screen
3. Choose your shared screen
4. Click "Show me what I'm sharing"

### Expected behavior:

I expect the shared screen to be scaled down to fit the whole thing

### Actual behavior:
The screen fills the available width and cuts off the remaining height

![Screen Shot 2023-10-18 at 11 04 03](https://github.com/jitsi/jitsi-meet/assets/3528358/872d98bc-9df3-44ef-8576-019a879a0072)

But after resizing the window, it shows as expected:
![Screen Shot 2023-10-18 at 11 04 10](https://github.com/jitsi/jitsi-meet/assets/3528358/680facf7-9b9c-40ef-be48-f0d9bdb64eca)

### Server information:

- Jitsi Meet version: 8961 (also observed on meet.jit.si and alpha.jitsi.net)
- Operating System: Ubuntu 22.04.3

### Client information:

- Browser / app version: Firefox 115.3.0esr
- Operating System: Debian GNU/Linux 12

**Comment by VernPace** [comment]
I concur.  Noticed this just today.
