### ISSUE TITLE
Unable to see or hear all other Jitsi participants

### ISSUE THREAD

**Issue by ljflores** [jitsi/jitsi-meet#13962]
### Description:

When joining a Jitsi call, I was unable to hear anyone or see anyone's video (just saw their Jitsi profile pictures, but no video feed). I was able to communicate via the chat box. Despite leaving and rejoining several times, I still couldn't see or hear anyone. I seemed to be the only one affected in the call.

### Steps to reproduce:

1. Join a Jitsi call
2. Verify sound and camera are authorized in web browser
3. Notice that despite people unmuting themselves and turning on their cameras, you cannot see or hear them.

### Expected behavior:

Should be able to see and hear people in the meeting.

### Actual behavior:

Unable to see or hear all other Jitsi participants.

### Server information:

- Jitsi Meet version: I'm using the latest Jitsi web version. Not sure if this is relevant from the console log: `2023-10-16T14:59:28.550Z [features/base/lib-jitsi-meet] lib-jitsi-meet version:255d8f49`
- Operating System: Jitsi web version

### Client information:

- Browser / app version: Chrome, version 117.0.5938.92
- Operating System: Fedora 36

**Comment by damencho** [comment]
Is this your deployment?

**Comment by ljflores** [comment]
> Is this your deployment?

Hi, I'm not sure what you mean.

**Comment by damencho** [comment]
We are aware of an issue in one of the regions for meet.jit.si and we are looking into it.

**Comment by ljflores** [comment]
Thanks @damencho !

**Comment by damencho** [comment]
Should be fine now.

**Comment by damencho** [comment]
You can report problems like this in the community forum. 

Thank you for the report.
