### ISSUE TITLE
Cannot login on meet.jit.si

### ISSUE THREAD

**Issue by jmakov** [jitsi/jitsi-meet#13963]
### Description:

When selecting logging in with e.g. Google or Github, I end up with "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared."

### Steps to reproduce:

1. open meet.jit.si
2. create a new room
3. login

### Expected behavior:

Should be logged in

### Actual behavior:
After selecting my Google account, I'm redirected to a page saying:  "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared."

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
> This may happen if browser sessionStorage is inaccessible or accidentally cleared."

Is this your case?

**Comment by saghul** [comment]
Can you open the JS console and type `sessionStorage` ? What do you get?

I could not reproduce it by enabling strict privacy on macOS, using Firefox 119.

**Comment by jmakov** [comment]
![Screenshot_20231017_154609](https://github.com/jitsi/jitsi-meet/assets/2602122/239b3cc5-c13e-4d5f-906f-20f8113ff66f)

**Comment by saghul** [comment]
Looks like some of those settings may trigger wiping `sessionStorage` across navigations, which breaks auth.

Can you try dialing down the browser privacy setting to see if that is the cause?

**Comment by jmakov** [comment]
Can confirm that it works with Chromium. In Firefox I'm using multi-account container extension. If I open the tab in the same container as I'm using for Google, it works. Thanks for helping with debugging the problem.
