### ISSUE TITLE
Ignore encryption SSL local network

### ISSUE THREAD

**Issue by Amir-yazdanmanesh** [jitsi/jitsi-meet#13970]
In my local network, I do not have access to the global network connection, and we do not have any SSL encryption in our local network. We use the Android Jitsi SDK, but there is no functionality to ignore SSL in our local network and connect to JitsiMeetView. I see this error in the log:

11:28:39.536 E [features/base/lib-jitsi-meet] Failed to load the configuration from https://meets.hivaa.im/config.js?room=tnidbhbqnbeyaxmfq54f4b59. Error (TypeError) {"message": "Network request failed", "stack": "index.android.bundle:115:8201\nindex.android.bundle:548:498\[nvalue@index.android.bundle](mailto:nvalue@index.android.bundle):29:1293\[nvalue@index.android.bundle](mailto:nvalue@index.android.bundle):45:3557\nindex.android.bundle:45:674\[nvalue@index.android.bundle](mailto:nvalue@index.android.bundle):45:2504\[nvalue@index.android.bundle](mailto:nvalue@index.android.bundle):45:646\nvalue@[native code]"}.

**Comment by saghul** [comment]
You can rebuild you app by whitelisting the ranges here: https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/res/xml/network_security_config.xml

We will not ship that to production for security reasons.
