### ISSUE TITLE
Add renameBreakoutRoom command to iframe API

### ISSUE THREAD

**Issue by Ayko1595** [jitsi/jitsi-meet#13976]
**Is your feature request related to a problem you are facing?**
I am using the iFrame API and can see that there are commands for both creating (with a specific name) and deleting a breakout room. There also seems to be support for renaming breakout rooms and I want to be able to rename breakout rooms with the iFrame API just like you create and delete.

**Describe the solution you'd like**
It should be possible to use the API object like this:

`api.executeCommand('renameBreakoutRoom', "new name here")`

**Comment by Akhilbisht798** [comment]
![Screenshot from 2023-11-02 20-39-34](https://github.com/jitsi/jitsi-meet/assets/92508481/67bae08b-426b-4e5c-8005-69fce97cff5a)
Hey, I looked up this and found that there is a function that handles that. 
I am new to this project, so I don't know this but can you not see that option on UI or something.
