### ISSUE TITLE
make the URL used for the "Open shared document" configurable during the call

### ISSUE THREAD

**Issue by artificial-intelligence** [jitsi/jitsi-meet#13987]
**Is your feature request related to a problem you are facing?**
When using shared documents in jitsi it's afaik only possible to configure a base url:

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#etherpad_base

however I'd like to point to specific, diverse shared documents, maybe even hosted on different servers|URLs.

so, if you already have prepared a shared document in advance and are just a jitsi user, it would be nice to be able to set a deep link, e.g. etherpad.example.com/my-topic for the "my-topic" call, instead of the general "etherpad.example.com" base URL which only opens a new clean etherpad.

I at least couldn't find how to achieve this or find an already existing issue for this.

Thanks for the great software, btw :slightly_smiling_face:

**Comment by saghul** [comment]
The shared document support is tied to Etherpad, so it would need to be tied that still.

**Comment by ehudettun** [comment]
I second that. This seems to be one of the only easy ways to integrate other kinds of iframes into the meeting.
