### ISSUE TITLE
rnsdk: Update Rejected SSL Error Handler com.reactnativecommunity.webview.RNCWebViewClient

### ISSUE THREAD

**Issue by Larens94** [jitsi/jitsi-meet#13982]
I'm trying to solve this problem but unfortunately I can't.

I checked on react-native-webview as indicated by the error: SSL Error Handler For more information on how to address WebView SSL Error Handler alerts, please see this Google Help Center article.

com.reactnativecommunity.webview.RNCWebViewClient

On RNCWebViewClient it seems that "onReceivedSslError" is handled correctly

you can view the code here: https://github.com/react-native-webview/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java

I created an issue but I have not received a response to resolve the problem, at the moment I am in a critical situation I cannot update the application in playstore.

link: https://github.com/react-native-webview/react-native-webview/issues/3079

it is used on jitsi meet for the youtube iframe and other components.

- rn sdk Jitsi Meet version: 0.5.0
- Operating System: Android

Thank you 
Cordially.

**Comment by saghul** [comment]
When exactly are you getting that error?

**Comment by Larens94** [comment]
After I submitted the application in playstore google rejects the application indicated this problem.
<img width="1004" alt="Screenshot 2023-10-25 alle 12 40 03" src="https://github.com/jitsi/jitsi-meet/assets/32598073/3e5155af-36c4-40de-94ce-e5af462ba881">
<img width="885" alt="Screenshot 2023-10-25 alle 12 40 23" src="https://github.com/jitsi/jitsi-meet/assets/32598073/482190af-bde5-4033-906f-8691f534095d">

**Comment by saghul** [comment]
Interesting, I've never seen that one.

I'd suggest you ask on the react-native-WebView repo, they should have more experience.

**Comment by Larens94** [comment]
> Interesting, I've never seen that one.
> 
> I'd suggest you ask on the react-native-WebView repo, they should have more experience.

I asked them but no one answered.
link: react-native-webview/react-native-webview#3079
if you don't understand this problem everyone who uses jisi meet's rnsdk and those who use react-native-webview cannot release a new app.

now I'm trying to remove the components that use the webview.. removing some functionality from rnjitsi.

Thank you

**Comment by saghul** [comment]
We use it and we release it no problem. There are many moving parts in an app, the fact that you run into a problem doesn't mean everyone is.

**Comment by zsl890728** [comment]
这个最终有解决么？ 我最近也遇到了
