### ISSUE TITLE
In the android app, participants who raise their hands are not put on top of the participants list.

### ISSUE THREAD

**Issue by cybergon** [jitsi/jitsi-meet#13989]
### Description:

We set up a moderated room and due to personal logistics I had to moderate it with my phone. This was the first time I used the app to moderate and the first thing I noticed was that whenever people raised their hands, I had to scroll through the entire participants list to actually see them. This is unlike the desktop web version where anyone who raises their hand is automatically put on top of the list.

### Steps to reproduce:

1. Set up a modetarted room
2. Access it through the app with more than two people
3. Have someone at the bottom of the list raise their hand

### Expected behavior:

The person raising their hand should now appear on top of the participants list.

### Actual behavior:

They remain in alphabetical order regardless of hand state.

### Server information:

- Jitsi Meet version: moderated.jitsi.net
- Operating System: 

### Client information:

- App version: 23.5.0 build 14934615
- Operating System: Android 11

**Comment by saghul** [comment]
@Calinteodor can you PTAL?

**Comment by saghul** [comment]
Fix in https://github.com/jitsi/jitsi-meet/pull/13997

**Comment by saghul** [comment]
Continues in https://github.com/jitsi/jitsi-meet/pull/13997
