### ISSUE TITLE
Conflict with Firebase Authentication and New Moderator Requirement Leading to Redirection to Official Jitsi Meet Android App

### ISSUE THREAD

**Issue by NilabhB** [jitsi/jitsi-meet#14017]
## Description
---
I am the lead developer of **SkyMeet**, a video conferencing application for Android leveraging the Jitsi Meet SDK. We are currently facing a challenge with the new moderator authentication feature introduced in recent SDK updates, which is not compatible with our custom Firebase authentication. This incompatibility leads to an undesirable redirection for our users to the official Jitsi Meet app in the Google Play Store after they attempt to log in. This redirection starts with a dialog box that sends them to a Chrome browser session and then to the Play Store for Jitsi Meet.

- **SkyMeet Repo**: https://github.com/NilabhB/SkyMeet
- **Playstore Link**: https://play.google.com/store/apps/details?id=com.skymeet.videoConference

Previously, users could log in via Firebase, enter a meeting room name, and proceed to start or join a meeting in SkyMeet without issue. The mandatory moderator authentication now disrupts this user flow.

## Current behavior
---
- Users log in with Firebase using SkyMeet's email and password authentication.
- Attempting to create a meeting triggers the new Jitsi moderator authentication process.
- This process leads to a redirect out of SkyMeet to the official Jitsi Meet app in the Playstore, rather than staying within our app.

## Expected Behavior
---
**The optimal outcome would be to bypass the new Jitsi moderator authentication, retaining our Firebase authentication to manage moderator privileges in SkyMeet. Should bypassing not be an option, we're looking for advice on how to integrate this new moderator requirement with our Firebase setup in a way that doesn't redirect users out of SkyMeet, thus preserving the intuitive experience our users have come to expect.**

## Steps to Reproduce
---
1. Authenticate via Firebase on SkyMeet's sign-in screen.
2. Enter a meeting room name on the main screen.
3. Click 'join' to start or enter a meeting.
4. User encounters the moderator authentication step and is redirected to the Jitsi Meet app in the Playstore.

## Environment details
---
- Android version: 13
- Device: Poco F4
- Jitsi Meet SDK version: 8.5.0 (the issue did not exist in version 7.0.1, which is now outdated due to the lack of moderator creation functionality)

**Note for Contributors:**
We need help addressing this significant issue from a coding standpoint. We would greatly appreciate any insights on how to adapt our codebase to bypass the new moderator authentication requirement or integrate it without causing user redirections. Our goal is to maintain the seamless experience of SkyMeet that our users have valued.

@saghul if you have the opportunity, your input would be incredibly helpful. Thank you for considering our request.

**Comment by damencho** [comment]
You should consider using your own deployment or jaas.8x8.vc.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by saghul** [comment]
You are not abiding by our "fair use" terms of service. Your app uses our backend: https://github.com/NilabhB/SkyMeet/blob/dev/app/src/main/java/com/skymeet/videoConference/SkyMeetApp.java

If you want to have your own authentication you have a couple of choices, as Damencho mentioned:

- Run your own backend: this has the utmost flexibility

- Use JaaS: you can use whatever auth you want and then get a JaaS token to drop users into meetings


Hope that helps!

**Comment by NilabhB** [comment]
Thank you, @damencho, for pointing me towards the appropriate channels for support; I'll be sure to consult the community forum for future inquiries.

@saghul, I appreciate your swift response and the options you've outlined. I would like to note that SkyMeet is a non-commercial, educational project I created, which operates without any revenue model. Hence, the suggested solutions present a financial challenge as they involve ongoing costs.

Could you advise on any alternative solutions that might accommodate the financial constraints of an educational project to keep SkyMeet operational?

Additionally, while I'm intrigued by the idea of running my own backend or using JaaS, I must confess I'm quite new to these concepts. Any guidance, or a point in the direction of detailed tutorials, would be invaluable. Should my circumstances change to where I can invest in the project, I am eager to learn and later contribute documentation for Android integration with Jitsi.

Thank you for your understanding and any assistance you can provide.

Please help!!

**Comment by damencho** [comment]
You can use links in your app, which will deeplink and open the official Jitsi Meet app for the meetings.
