### ISSUE TITLE
Android: Duplicate tile user

### ISSUE THREAD

**Issue by thienvq** [jitsi/jitsi-meet#14018]
I having two user in call then enter PiP mode and reopen it, user 3rd join this room and happen duplicated tile.
Hope everyone can help.
Thanks.
![Screenshot_20231103_132437](https://github.com/jitsi/jitsi-meet/assets/41584741/26300ebf-0e09-46dc-908b-f3989eab4824)

**Comment by saghul** [comment]
What version of the app or ask are you using? Can you reproduce it every time?

**Comment by thienvq** [comment]
> What version of the app or ask are you using? Can you reproduce it every time?

Yes you can reproduce it every time, im using version 6.0.0

**Comment by saghul** [comment]
That version is really old, please try to reproduce with the latest version.

We have fixed this bug in the past.

**Comment by thienvq** [comment]
> That version is really old, please try to reproduce with the latest version.
> 
> We have fixed this bug in the past.

Tks
Im upgrading source code follow new jitsi version, i will let you know result when its done
