### ISSUE TITLE
Chat input bar layout issues with SDK 8.5.0

### ISSUE THREAD

**Issue by mwjdev1** [jitsi/jitsi-meet#14010]
### Description:

Using SDK 8.5.0 on Android 13.0, the chat input bar is obscured by the keyboard. After applying commit 29d02f0a2bce1a271daf7414703f8ed1815f0239, the chat input bar varies between being obscured or being over halfway up the screen.

### Steps to reproduce:

1. Tap the chat input bar to bring up the keyboard.

### Expected behavior:

The chat input bar should be anchored to the top of the keyboard.

### Actual behavior:

The chat input bar is either not visible or pushed too far up the screen.

Without commit 29d02f0a2bce1a271daf7414703f8ed1815f0239:
![without-commit](https://github.com/jitsi/jitsi-meet/assets/149603060/70fbcb8a-aefe-4ec1-aeda-e073f4593700)

With commit 29d02f0a2bce1a271daf7414703f8ed1815f0239:
![with-commit](https://github.com/jitsi/jitsi-meet/assets/149603060/f8d99655-2e42-4696-ab34-e19d11781887)

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: SDK 8.5.0 (also observed using Jitsi Meet 23.4.0)
- Operating System: Android 13.0
- Device: Pixel C

### Additional information:

Tablets seem to be affected more so than phones.

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by Calinteodor** [comment]
Hello. Cannot repro, sorry. But it seems that the input is hidden when the device is on portrait mode.

Pixel C tablet simulator, landscape mode.
![image](https://github.com/jitsi/jitsi-meet/assets/26413496/6c418628-9f1d-4630-a4ea-5b34d3b1aa9f)
