### ISSUE TITLE
If a special charachter is pasted in the chat the user gets disconnected. 

### ISSUE THREAD

**Issue by small1** [jitsi/jitsi-meet#14037]
### Description:

This word if pasted in the jitsi chat will diconnect the user and make the user rejoin:

egenskapskrav

A special char snuk in a a document that was discussed in a few meetings. When the text was pasted in the chat it kils the meeting for the users that pastes it

### Steps to reproduce:

1. start conference and open chat
2. paste this word: egenskapskrav
3. get disconnected

### Expected behavior:

User would still be in the chat,

### Actual behavior:

User gets disconnected and has to rejoin

### Server information:

- Jitsi Meet version: several including meet.jit.si

### Client information:

- Browser / app version: Firefox and chrome
- Operating System: windows and linux

**Comment by small1** [comment]
Note github converts the char  So i could apparently not be paste it here .... Ill try to relay it  in some other way

**Comment by small1** [comment]
This pastebin contains a word with the char: https://pastebin.com/ggryTRNL

**Comment by saghul** [comment]
Can you paste the JS console logs when that happens?

**Comment by small1** [comment]
Logger.js:154 2023-11-08T20:11:20.050Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: Strophe: WebSocket stream error: not-well-formed Script: null Line: null Column: null StackTrace:  Error: Strophe: WebSocket stream error: not-well-formed

2023-11-08T20:12:13.804Z [modules/xmpp/strophe.util.js] <vt.Strophe.log>:  Strophe: WebSocket stream error: not-well-formed
s @ Logger.js:154
vt.Strophe.log @ strophe.util.js:89
error @ strophe.umd.js:2020
_checkStreamError @ strophe.umd.js:5747
_onMessage @ strophe.umd.js:6172
socket.onmessage @ strophe.umd.js:5920
21:12:13.804

**Comment by saghul** [comment]
Thanks for the report!

**Comment by coderwithsense** [comment]
I can help, but i am a beginner. Can you please guide me on how to solve this one.
