### ISSUE TITLE
Some button labels are not fully displayed.

### ISSUE THREAD

**Issue by AoEiuV020** [jitsi/jitsi-meet#14039]
### Steps to reproduce:

1. The OverflowMenu pops up when you click the "More" button.
2. check the RaiseHandButton  at the bottom.

### Expected behavior:

 label fully displayed.

### Actual behavior:
 label are not fully displayed.
### Server information:

- Jitsi Meet version: 
- Operating System: android

### Client information:

- Browser / app version: 23.5.0 from google play
- Operating System: android

### Additional information:

 In an English environment, the issue may not be very apparent, but it becomes noticeable when the screenshot is enlarged.
 In languages like Chinese, the problem is much more pronounced. 

![zh](https://github.com/jitsi/jitsi-meet/assets/11682198/e1ce7e10-5182-4985-845d-4d92b0fc7ed1)

![en](https://github.com/jitsi/jitsi-meet/assets/11682198/b6938633-d540-442b-ab2d-93b0541d8da5)

**Comment by AoEiuV020** [comment]
@Calinteodor Please review this issue.

**Comment by Calinteodor** [comment]
> @Calinteodor Please review this issue.

Thank you!
