### ISSUE TITLE
Microphone Issues After November 8, 2023 Update of Google Chrome for Android

### ISSUE THREAD

**Issue by LOIZoclock** [jitsi/jitsi-meet#14043]
### Description:

When using Jitsi Meet on Google Chrome for Android, after the update on November 8, 2023, users experience microphone issues. Specifically, the microphone does not enhance or reduce echo and noise. When a user is connected on web Jitsi with Google Chrome on Android, others in the meeting can hear their own voice, indicating that Google Chrome is not enhancing the voice of the participant coming from the speaker. This issue does not occur when using Firefox on the same devices.

### Steps to reproduce:

1. Open Jitsi Meet on Google Chrome for Android.
2. Join a meeting.
3. Speak, and observe that others can hear their own voice.

### Expected behavior:

The microphone should function correctly, enhancing and reducing echo and noise as needed, ensuring a clear audio experience for all participants.

### Actual behavior:

Microphone functionality is not working as expected on Google Chrome for Android after the update on November 8, 2023. Other participants can hear their own voice, indicating a failure to enhance the audio from the speaker.

### Client information:

- Browser version: Google Chrome for Android
- Operating System: Android

**Comment by saghul** [comment]
Have you reported this to Chrome?

**Comment by LOIZoclock** [comment]
> Have you reported this to Chrome?

Reported on Google Chrome's "Help & feedback"

**Comment by LOIZoclock** [comment]
Update: Bug fixed with the new update of Google Chrome on 16/11/2023.

Thank you @saghul.
