### ISSUE TITLE
https://meet.jit.si/  Is it working normally?

### ISSUE THREAD

**Issue by HongSeokHwan** [jitsi/jitsi-meet#1404]
The following error message appears and it is not working.

"Fellow jitster is having connectivity issues."

I tested it between two browsers using Chrome.

**Comment by saghul** [comment]
Yes, it's working fine as far as we can tell. Please check for connectivity issues (as in packet loss) on your side.

**Comment by HongSeokHwan** [comment]
Is there any location issue? I live in South Korea. I've tested in various network situation like 4G(hotspot), WIFI, and LAN. All results are same (Fellow jitster is having connectivity issues)

What should I test? Please help me.

**Comment by paweldomas** [comment]
Do you get this message occasionally or all the time like it's impossible to see any video ?
