### ISSUE TITLE
IOS Browser doesn't support Jitsi. 

### ISSUE THREAD

**Issue by mgloes** [jitsi/jitsi-meet#14050]
Hello. I wrote a web application with flutter. This app has web view. This web view is open a html code. When I try to use stream on Ios mobile Safari, Jitsi view show that "doesn't support". On the other hand, Google chrome is working clearly. I need help about this issue. I'm added all html codes on the end of the description. Have a nice day.

 <!DOCTYPE html>
    <html>
      <head>
        <script src='https://8x8.vc/vpaas-magic-cookie-e1e1cb8f29c143878bd85ac6e8b72539/external_api.js' async></script>
        <style>html, body, #jaas-container { height: 100%; }</style>
        <script type="text/javascript">
          window.onload = () => {
            const api = new JitsiMeetExternalAPI("8x8.vc", {
              userInfo: {"displayName":"$name"},
              roomName: "vpaas-magic-cookie-e1e1cb8f29c143878bd85ac6e8b72539/SampleAppThoughtfulToiletsSuitNeither",
              parentNode: document.querySelector('#jaas-container'),
				configOverwrite: {prejoinConfig:{enabled: false},hideDominantSpeakerBadge: false ,toolbarButtons: [],startWithVideoMuted: true,startWithAudioMuted:true,disableResponsiveTiles:true ,hideConferenceSubject: true,hideParticipantsStats: true, tileView: {disabled: true}, filmstrip: {disabled:true},enableNoisyMicDetection: false,enableNoAudioDetection: false,enableEncodedTransformSupport:true,sendMultipleVideoStreams: false,notifications:[],localRecording: {disable: true}, liveStreaming: {enabled: false},disableDeepLinking: true,startAudioMuted: 0,startSilent: true,webrtcIceTcpDisable: false,webrtcIceUdpDisable:false,useTurnUdp:true,disableRtx:false,
        videoQuality: {
          codecPreferenceOrder:[ 'H264', 'VP8'  , 'VP9']
        },mobileCodecPreferenceOrder:[  'H264', 'VP8' , 'VP9'],disabledCodec:'',preferredCodec: 'H264',
        }
        
            });
          }
        </script>
      </head>
      <body><div id="jaas-container" /></body>
    </html>

**Comment by saghul** [comment]
Hey @mgloes I see you are a JaaS customer. Can you please open a new support ticket instead? We use this issue tracker for issues related to the open source project.

**Comment by mgloes** [comment]
How can i reach new release. I got this code on the web site yesterday. @gabiborlea
