### ISSUE TITLE
Android can't connect to my Server

### ISSUE THREAD

**Issue by SlamDunkDcc** [jitsi/jitsi-meet#1405]
I used the Android React-Native, in order to connect to my server. It shows like this pic.

![qq 20170316202538](https://cloud.githubusercontent.com/assets/13446749/23996054/0e7c7986-0a87-11e7-9a4c-650565f2b216.jpg)

**Comment by saghul** [comment]
What host are you trying to connect to? Is it reachable y the mobile? Does it work with the Jitsi Meet app on the store? (use the full URL as the room)

**Comment by SlamDunkDcc** [comment]
I download the jitsi-meet and build myself,my server is in local area network.In browser this go ok

**Comment by saghul** [comment]
Are you using HTTP or HTTPS? The mobile apps only support HTTPS.

**Comment by SlamDunkDcc** [comment]
I use http because the mobile can't'get the config.js from my https server. I used OpenSSL created my crt.Is the certificate generated in this way not available？thanks

**Comment by Yonysun** [comment]
The same problem happened to me,hope good ideas. Thanks !

**Comment by saghul** [comment]
The mobile apps don't support HTTP nor self-signed certificates. Support for those might never come because of platform limitations (iOS doesn't allow it, for example).

I suggest you get a proper SSL cert (with Lets Encrypt for example), or add the CA to the system trust store.

**Comment by SlamDunkDcc** [comment]
thanks
