### ISSUE TITLE
RNSDK - Support all events available in iOS/Android SDK

### ISSUE THREAD

**Issue by alexander-at-t** [jitsi/jitsi-meet#14059]
https://github.com/jitsi/jitsi-meet/blob/8cdde88049442186129ac36d0a063bf9eca9f0f7/react-native-sdk/index.tsx#L109-L118

Could you please add support of all available iOS/Android Jitsi SDK events to RNSDK?

For example, iOS and Android Jitsi SDK support the following events, but RNSDK doesn't:
- `endpointTextMessageReceived` / `ENDPOINT_TEXT_MESSAGE_RECEIVED`
- `chatMessageReceived` / `CHAT_MESSAGE_RECEIVED `
- `audioMutedChanged` / `AUDIO_MUTED_CHANGED`
- `videoMutedChanged` / `VIDEO_MUTED_CHANGED`

**Comment by saghul** [comment]
We'll gradually add them but PRs are welcome.

**Comment by abbasrm** [comment]
I added `AUDIO_MUTED_CHANGED` and  `VIDEO_MUTED_CHANGED` here: https://github.com/jitsi/jitsi-meet/pull/14064

**Comment by abbasrm** [comment]
Also added `onParticipantLeft` and  `getRoomsInfo` here: https://github.com/jitsi/jitsi-meet/pull/14145

**Comment by saghul** [comment]
Closing. We'll add them as necessary.
