### ISSUE TITLE
Conference starts before _obtainConfigAndInit return back.

### ISSUE THREAD

**Issue by jiyeyuran** [jitsi/jitsi-meet#1406]
Conference should not start before _obtainConfigAndInit return back. Because _obtainConfigAndInit will update config.

RouteRegistry.register({
    component: Conference,
    onEnter: () => {
        // XXX If config or jwt are set by hash or query parameters
        // Getting raw URL before stripping it.
        _obtainConfigAndInit();
    },
    path: '/:room'
});

**Comment by saghul** [comment]
Can you please elaborate what problem you're running into? `_initConference` won't be called until the config has been fetched. Note that this code path is only executed for the web, not mobile, currently. This is due to the efforts for bringing the web to React.

**Comment by jiyeyuran** [comment]
I want to update config object based on the http cookie. `obtainConfig` in `HttpConfigFetch.js` is using async ajax, when the data from server is available, the conference UI and connection already started. It causes that the config or interfaceConfig fails to update. This didn't happen before moving the web to React. 
componentDidMount in the conference.web.js will run and not wait the config updating from `_obtainConfigAndInit`. `_initConference ` now is doing very little functions.

```
    componentDidMount() {
        APP.UI.start();

        APP.UI.registerListeners();
        APP.UI.bindEvents();

        this.props.dispatch(connect());
    }
```
