### ISSUE TITLE
onReadyToClose when call second time

### ISSUE THREAD

**Issue by thienvq** [jitsi/jitsi-meet#14063]
Hi everyone,
I just ended calling and then i call again (about after 1 second or faster), Jitsi emit onReadyToClose event.
Hope everyone can help.
Thanks.

**Comment by saghul** [comment]
Please share some logs when that happens and what SDK version you are using.

**Comment by thienvq** [comment]
> Please share some logs when that happens and what SDK version you are using.

Log:
-ExternalAPI Sending event: READY_TO_CLOSE with data: { NativeMap: {} }
-[modules/xmpp/xmpp.js] (TIME) Strophe disconnecting:	 1700124954710
-[modules/xmpp/strophe.util.js] Strophe: Disconnect was called because: undefined
-[features/calendar-sync] Calendar access not granted.
-[modules/xmpp/xmpp.js] (TIME) Strophe disconnected:	 1700124954776
-ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"url":"https://meet.tocdoweb.com/JlcXrSl64twGci5vTEY8aGU6XWCXhm"} }

My version: 6.0.0

**Comment by saghul** [comment]
Can you please update the latest version? 6.0.0 is very old at this point.

**Comment by thienvq** [comment]
My project is big, i cant upgrade latest jitsi version.
You can let me know which version did you fix it and i just upgrade that version.
Thanks

**Comment by saghul** [comment]
A whole lot has changed, I cannot point you to a single commit, sorry.

**Comment by thienvq** [comment]
> A whole lot has changed, I cannot point you to a single commit, sorry.

Okay, thanks
