### ISSUE TITLE
RNSDK [Android] "Cannot find symbol method getCurrentActivity()"

### ISSUE THREAD

**Issue by danilvalov** [jitsi/jitsi-meet#14074]
### Description:

When I try to build an Android React Native app, I see the following error:
```
node_modules/@jitsi/react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JMOngoingConferenceModule.java:27: error: cannot find symbol
        Context activityContext = context.getCurrentActivity();
                                         ^
  symbol:   method getCurrentActivity()
  location: variable context of type Context
```
on [this line](https://github.com/jitsi/jitsi-meet/blob/master/react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JMOngoingConferenceModule.java#L27)

### Steps to reproduce:

1. Integrate `@jitsi/react-native-sdk` to react-native project
2. Try to build it for Android

### Expected behavior:

It should build

### Actual behavior:

I receive an error `Cannot find symbol method getCurrentActivity()`

### Client information:

- Operating System: Android
- React Native: 0.72.3
- Jitsi React Native SDK: 1.0.0
- Android Gradle config:
```
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "30.0.0"

        ndkVersion = "23.1.7779620"
        kotlinVersion = "1.8.21"
```

### Additional information:

I switched from `@jitsi/react-native-sdk` v0.5.0 to v1.0.0, and I got this error

**Comment by saghul** [comment]
Ping @Calinteodor
