### ISSUE TITLE
Mobile app (iOS) forgets server URL

### ISSUE THREAD

**Issue by tendsgn** [jitsi/jitsi-meet#14079]
### Description:
Jitsi Meet on iOS doesn't save custom server address. It changes back to meet.jit.si on each relaunch.

### Steps to reproduce:
Open the Jitsi Meet app on iOS.
Open Settings view.
Enter a server address, other than meet.jit.si.
Leave settings.
Leave app and then force quit.
Reopen app 
Go to the Settings view, look at the server address. 

### Expected behavior:
The entered server address should be saved (and the address should be used when making a connection.)

### Actual behavior:
Entered server address is forgotten and replaced with meet.jit.si.

### Server information:
Jitsi Meet version: not relevant
Operating System: not relevant

### Client information:
Browser / app version: Jitsi Meet SDK 23.6.0 (23.6.0 build 1700060292)
Operating System: iOS 17.1.1 (iPhone)

### Additional information:
Tried on three different iPhones (one was on iOS 16.6.1)

**Comment by saghul** [comment]
@Calinteodor can you PTAL at this tomorrow?

**Comment by krassle** [comment]
FYI, Android is affected as well. App Version: 23.6.0

**Comment by saghul** [comment]
I'm pretty sure I broke it here: https://github.com/jitsi/jitsi-meet/commit/5854e38a0916aa3d863b1958723f01bfd73c6a14

**Comment by krassle** [comment]
Language Option in Settings also gets reset to System/Android Default on relaunch! Related maybe...?!

**Comment by Calinteodor** [comment]
This is not related.
