### ISSUE TITLE
Be able to hide TitleBar Buttons

### ISSUE THREAD

**Issue by ugmlr** [jitsi/jitsi-meet#14073]
**Is your feature request related to a problem you are facing?**
I want to implement video meeting into an app for elderly people, therefore they should have no/little options to click on, because it could easily confuse them

**Describe the solution you'd like**
FeatureFlags for disabling/enabling the buttons on the titleBar (e.g. ParticipantsPane Button, Switch Camera & Speaker Button)

**Describe alternatives you've considered**
There's currently no way to disable the Buttons (there's already issues that are asking this). I have considered doing it myself, but I am unfortunately extremely new to github and not sure if I'm able to produce a clean code.

**Comment by shawnchin** [comment]
This is already possible using the toolbarButtons config: https://github.com/jitsi/jitsi-meet/blob/109b83d6f1fab2fba2382fb8b94b0729dade0cfb/config.js#L775

If you have your own deployment, you can change that in your config.js. If you are embedding a hosted Jitsi service, you can use the [configOverwrite](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe/#creating-the-jitsi-meet-api-object) option to specify custom toolbar buttons.

For mobile apps, the official SDKs should have similar options to pass in config overrides.

p.s. in the future, it might be worth asking on the [community forum](https://community.jitsi.org/) first before raising a github issue.

**Comment by ugmlr** [comment]
HI, I did search for similar issues (although i didn't find them on the community forum) & in this issue #13943 it was said that there's currently no possibility to disable the participants pane button.
I am using the flutter SDK for jitsi and have tried the toolbarButtons Option, but it doesn't work, so I'll probably raise an issue there, thanks :)

**Comment by ugmlr** [comment]
Just in case anyone else is interested: The toolbarButtons is only for Web Use, currently there's no option like that for mobile Apps, so the Feature request still stands.
I will try to implement some featureFlags  or something similar myself, we'll see how that goes

**Comment by saghul** [comment]
Let us know if you need any guidance.
