### ISSUE TITLE
Allow linking to preference pages.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [jitsi/jitsi-meet#14072]
0.	**Is your feature request related to a problem you are facing?**
	
	I'm unable to link to

	![screenshot-calls disroot org-2023 11 19-19_03_17](https://github.com/jitsi/jitsi-meet/assets/42837531/db688c61-9065-4302-b971-ac89c32fe7e9)

	using a URI, meaning that my autofill manager is unable to update the Gravatar address when it changes.
	
0.	**Describe the solution you'd like**
	
	Allow linking to preference sections.
	
0.	**Describe alternatives you've considered**
	
	None exist.

**Comment by saghul** [comment]
This is an SPA not sure how that would be handled, but the URL remains unchanged all across the meeting. Changing it is not an option.

**Comment by RokeJulianLockhart** [comment]
**https://github.com/jitsi/jitsi-meet/issues/14072#issuecomment-1817962071**

> but the URL remains unchanged all across the meeting. Changing it is not an option.

What are you referring to, @saghul? This shouldn't impact any meetings.

**Comment by saghul** [comment]
It does have an impact because a meeting is represented by the location URL.

An SPA is a Single Page Application, a page where all internal navigation happens in JS without effectively leaving the page.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/jitsi/jitsi-meet/issues/14072#issuecomment-1818210387

@saghul, even if this application is an SPA, as long as the URI doesn't use any from-root hierarchical modifications - just have all preferences be added using arguments like `?navigate_to='/settings/<setting>'` - it shouldn't affect anything, right? After all, the URI displayed to the client doesn't have to represent whatever's occurring on the server.

**Comment by saghul** [comment]
The url is the canonical identifier of the meeting and used as such.
