### ISSUE TITLE
RNSDK [iOS] "TypeError: Cannot read property 'abort' of null"

### ISSUE THREAD

**Issue by danilvalov** [jitsi/jitsi-meet#14089]
### Description:

When I stop the call, I see an error in logs: `[features/base/redux] [TypeError: Cannot read property 'abort' of null]`
I think the problem is on [this line](https://github.com/jitsi/jitsi-meet/blob/master/react/features/mobile/react-native-sdk/middleware.js#L81) (because I see a `StateListenerRegistry.ts` file as the last action before starting error handling).

As I undestand there is not a native `JMOngoingConference` module for iOS platform (for Android only), so we have this error.

<details>
  <summary>App error screen (click it)</summary>

  ![app_screenshot](https://github.com/jitsi/jitsi-meet/assets/2463767/7e65bd7c-2043-47bf-b4bb-90946e02341f)
</details>

### Steps to reproduce:

1. Start Jitsi call on iOS
2. Stop Jitsi call

### Expected behavior:

There is an error `[features/base/redux] [TypeError: Cannot read property 'abort' of null]` in logs

### Actual behavior:

There is not the error in logs

### Client information:

- Operating System: iOS
- React Native: 0.72.7
- Jitsi React Native SDK: 1.0.0

**Comment by saghul** [comment]
Right. @Calinteodor since that only works on Android we should skip this listener on iOS.

**Comment by apt-get-sahil** [comment]
@saghul as you have mentioned that it doesnt work on ios , so i think we can check for the os if its iOS then we can skip that specific listener in ios, we can use platform from react-native for this, will it be correct to do?
