### ISSUE TITLE
RNSDK - Cannot share screen, [Android] sharing screen is black, [iOS] share screen not working

### ISSUE THREAD

**Issue by Jiayuwalker** [jitsi/jitsi-meet#14080]
### Description:

I'm using the Jitsi Meet React Native SDK on Android, after pressing the screen sharing button, the permission request to record the screen appears as expected. Upon granting permission, a new participant is added to the meeting for screen sharing. However, the shared screen from this participant appears entirely black.

On iOS, following the official documentation for Screen Sharing integration, after pressing screen sharing and consenting to the screen recording request, nothing happens.

And the issue persists even when using the sample code provided in the official [samples for React Native](https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/react-native). On Android the shared screen participant is added, but the screen is black.

### Steps to reproduce:

1. Launch the React Native SDK sample code and run it on an Android tablet.
2. Enter the room name "rnsdk-testing" and join the meeting.
3. Click on the screen sharing button.
4. Grant permission for screen recording.

### Expected behavior:
The shared screen participant should show the tablet screen.

### Actual behavior:
The sharing screen is entirely black.
![image](https://github.com/jitsi/jitsi-meet/assets/121848665/fc5102f4-fb7d-4cd8-9989-6e06722f200c)

**Comment by saghul** [comment]
What SDK version are you using? Did you follow the steps to set the permissions on your app?

**Comment by Jiayuwalker** [comment]
> What SDK version are you using? Did you follow the steps to set the permissions on your app?

In our app that we're building, I try to keep all the versions in sync with your [sample code](https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/react-native). We also make sure to follow the settings in the [documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-react-native-sdk#android-permissions).

react-native: 0.72.3
@jitsi/react-native-sdk: ^0.5.0

**Comment by Calinteodor** [comment]
Please try following the documented steps again and also, you are not using the latest version.

**Comment by saghul** [comment]
> @jitsi/react-native-sdk: ^0.5.0

Try 1.0.0.

**Comment by Calinteodor** [comment]
Update to 1.0.2. please.

**Comment by Jiayuwalker** [comment]
> Update to 1.0.2. please.

It works!!!!!!!!! Thanks a lot!
