### ISSUE TITLE
Jitsi update fails on Ubuntu 20.04.6 according to dependency on prosody >= 0.11

### ISSUE THREAD

**Issue by chamchawala** [jitsi/jitsi-meet#14100]
apt-get update  &  apt-get upgrade leaves the followinh packages untouched:
The following packages have been kept back:
fwupd jicofo jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jitsi-videobridge2 libfwupd2 libfwupdplugin5 ubuntu-advantage-tools

Next try:
sudo apt-get install fwupd jicofo jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jitsi-videobridge2 libfwupd2 libfwupdplugin5 ubuntu-advantage-tools

results in:
The following packages have unmet dependencies:
 jitsi-meet-prosody : Depends: prosody (>= 0.11.7) but 0.11.4-1 is to be installed or
                               prosody-trunk but it is not installable or
                               prosody-0.12 but it is not installable or
                               prosody-0.11 but it is not installable
E: Unable to correct problems, you have held broken packages.

apt list --installed prosody shows:
prosody/focal,focal,now 0.11.4-1 amd64 [installed,automatic]

This Jitsi instance is running on a machine hoosted by Hetzner in Germany.
Any idea on how to proceed would be appreciated

**Comment by saghul** [comment]
You could add the upstream Prosody repository from prosody.im, install Prosody 0.12 from there and then update Jitsi Meet.

@damencho Looks like our docs are worng, we no longer support Ubuntu 20.04 out of the box, without a manually installed Prosody beforehand, or is this an oversight?

**Comment by damencho** [comment]
One of the steps in the docs is "Add the Prosody package repository" which says: "Ubuntu 18.04 and 20.04 .. echo deb http://packages.prosody.im/debian.... sudo apt install lua5.2" and that will bring prosody 0.12.

**Comment by saghul** [comment]
Hum, I guess we might have in 2 places then. This page only mentions 18.04: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/handbook/commit/72d7d643c6e185136af246db7fd4c74d66eeb68d to match what's below in the page.

**Comment by chamchawala** [comment]
thanks - both of you - for your hints :-)
