### ISSUE TITLE
iOS callkid cannot be disabled

### ISSUE THREAD

**Issue by NimbleDev** [jitsi/jitsi-meet#14109]
### Description:

We built our mobile app using react native sdk.  And we've set CALL_INTEGRATION_ENABLED to false in flags. But still when user joins a meeting thru iOS app, CallKid still appears as below.
![image](https://github.com/jitsi/jitsi-meet/assets/51120096/8e09e48a-a7c3-419d-8b0f-f8f43e2ba0fa)

### Steps to reproduce:

join a meeting thru iOS app

### Expected behavior:

CallKid should not appear

### Actual behavior:

CallKid appears as thought we've set CALL_INTEGRATION_ENABLED to false.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
How exactly did you pass the flag?

**Comment by NimbleDev** [comment]
> How exactly did you pass the flag?

I pass the flag as below in rn where call-integration.enabled is set to false:

<JitsiMeeting
      eventListeners={eventListeners}
      flags={{
        'call-integration.enabled': false,
        'unsaferoomwarning.enabled': false, 
        'prejoinpage.enabled': false,
        'raise-hand.enabled': false,
        'chat.enabled': false,
        'reactions.enabled': false,
        'server-url-change.enabled': false,
      }}
      ref={jitsiMeeting}
      style={{
        flex: 1,
      }}
      room={room}
      serverURL={config.roomServerURL}
      userInfo={{
        displayName: userName || '',
        serverURL: config.roomServerURL || '',
      }}
    />

**Comment by saghul** [comment]
@Calinteodor can you PTAL when you have a chance?

**Comment by NimbleDev** [comment]
> 406835844_6968942709860057_423477639581848983_n.mp4 
> I used
> 
> flags={{ 'call-integration.enabled': false, 'unsaferoomwarning.enabled': false, 'prejoinpage.enabled': false, 'raise-hand.enabled': false, 'chat.enabled': false, 'reactions.enabled': false, 'server-url-change.enabled': false, }}
> 
> and they seem to work as expected. Issue is not reproducible on my end.

Indeed, it did not occrur in every iPhone. That's so wired. Any suggestion?
