### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME in video call by Jitsi app

### ISSUE THREAD

**Issue by paymanzafar1** [jitsi/jitsi-meet#14103]
### Description:
I want to use Jitsi as the default conference call provider in Rocket Chat.

 I installed Jisti on my own infrastructure, and configured it in Rocket Chat as the default provider for conference calls.

I opened the Rocket Chat widget in Chrome browser on my mobile phone, and then a Rocket Chat agent called me. I see the following image:

![jitsi1](https://github.com/jitsi/jitsi-meet/assets/91053236/2db2a2bd-2239-4aa0-b4c0-d16f99c0c364)

If I select join in browser, everything is OK. But if I select join in app, the follwoing error message is displayed:

![jitsi2](https://github.com/jitsi/jitsi-meet/assets/91053236/1f642422-0ad3-45a4-934f-dc5a81ee9f64)

The complete error message is here:

Webpage not available
The webpage at intent://********-64f43b71231cadd08438b434#config.desktopSharingChromeExtId=%22nocfbnnmjnndkbipkabodnheejiegccf%22&config.callDisplayName=%22guest-15%22#Intent;scheme=org.jitsi.meet;package=org.jitsi.meet;end could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME

I think it is because I am using my own infrastructure, and server URL. 

### Expected behavior:

Jitsi mobile application can be used in this call.

**Comment by saghul** [comment]
Do you have the Jitsi Meet mobile app installed?

**Comment by paymanzafar1** [comment]
Yes

**Comment by saghul** [comment]
Ugh that's very weird. The link points to the right package: `org.jitsi.meet` so it should have been launched. What browser did you open that on? Maybe they restricted intent links?

**Comment by paymanzafar1** [comment]
I used Chrome browser.

**Comment by saghul** [comment]
Ugh, I'm at a loss then...
