### ISSUE TITLE
Android application crashes when sharing a chrome tab

### ISSUE THREAD

**Issue by ysbutuner** [jitsi/jitsi-meet#14117]
I am sharing a chrome tab from the Jitsi web application. When I join a meeting from my Android device, the application crashes. Do you have any ideas?

Case:
1- Jitsi web meeting is started.
2- Chrome tab screen sharing is done
3- Android participant joins the meeting and the application crashes when the screen sharing is focused

[qarth_debug:] get PatchStore::createDisableExceptionQarthFile method fail.
2023-11-29 13:41:22.647 25852-26327 AndroidRuntime org.jitsi.meet E FATAL EXCEPTION: EglRenderer
Process: org.jitsi.meet, PID: 25852
android.opengl.GLException: compileShader: GLES20 error: 1281
at org.webrtc.GlUtil.checkNoGLES2Error(GlUtil.java:39)
at org.webrtc.GlShader.compileShader(GlShader.java:31)
at org.webrtc.GlShader.<init>(GlShader.java:7)
at org.webrtc.GlGenericDrawer.createShader(GlGenericDrawer.java:11)
at org.webrtc.GlGenericDrawer.prepareShader(GlGenericDrawer.java:29)
at org.webrtc.GlGenericDrawer.drawYuv(GlGenericDrawer.java:9)
at org.webrtc.GlRectDrawer.drawYuv(GlRectDrawer.java:1)
at org.webrtc.VideoFrameDrawer.drawFrame(VideoFrameDrawer.java:24)
at org.webrtc.EglRenderer.renderFrameOnRenderThread(EglRenderer.java:194)
at org.webrtc.EglRenderer.e(Unknown Source:0)
at org.webrtc.m.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:907)
at android.os.Handler.dispatchMessage(Handler.java:105)
at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:1)
at android.os.Looper.loop(Looper.java:216)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by saghul** [comment]
What Android app version is that?

**Comment by ysbutuner** [comment]
Android app version 23.6.1

**Comment by saghul** [comment]
@Calinteodor can you try to repro please?

**Comment by Calinteodor** [comment]
1. Create meeting in web.
2. Start screen sharing from web.
3. Join from mobile Android.
4. I can see both web participant and screen share.
5. Ended screen share from web.
6. Android participant still in the conference and nothing crashed.

**Comment by ysbutuner** [comment]
When I try the same steps, I also get a crash. My device information is as follows.

Huawei Y6s Android 9 
![phone](https://github.com/jitsi/jitsi-meet/assets/91797113/e96935df-3116-4bf7-803c-7b4abac27b12)

**Comment by Calinteodor** [comment]
I don't get a crash. Everything works as expected. Please try updating you os.

**Comment by Calinteodor** [comment]
I am sorry, but this is not reproducible on our end. This is all that we can do.

**Comment by ysbutuner** [comment]
This is actually a problem with all of these devices. Don't you have a chance to purchase and try these devices?
I can provide device support

@saghul  @Calinteodor 

1. Huawei P Smart 2019 Android 10
2. Reno2 Z  Android 11
3. Galaxy Tab A (2016) With S Android 8.1
4. Huawei Y6s Android 9

**Comment by saghul** [comment]
Let's check the WebRTC bug tracker @Calinteodor . This is an OpenGL rendering crash.

**Comment by ysbutuner** [comment]
It is definitely caused by webrtc opengl. We tried our best to come across the case. I'm sure you will encounter problems with the devices I mentioned. @Calinteodor I'm waiting for your support.

**Comment by saghul** [comment]
Can you try our beta app? That would be 23.7.0, you can opt-in in the Play Store. It has an updated WebRTC version. I didn't see anything relevant in the release notes, but those are known to not be comprehensive.

**Comment by ysbutuner** [comment]
I tried to repeat it, I couldn't repeat it in my 23.7.0 version, I will be adding a case. Thank you for your support

**Comment by SabihaCetin** [comment]
Hi,
We continue to receive the same error in the beta version you mentioned. You can check it from your logs. The screen recording of the error is attached. We are waiting for your urgent support.

https://github.com/jitsi/jitsi-meet/assets/32906878/edf78b5b-9003-4f59-a383-044e4a017377

**Comment by saghul** [comment]
Can you share the log at output? Is it the same as the previous one?

**Comment by SabihaCetin** [comment]
Yes, the crash log is the same as before. In the meeting, a user had already shared a chrome tab.
