### ISSUE TITLE
jitsi android ios system requirements

### ISSUE THREAD

**Issue by ysbutuner** [jitsi/jitsi-meet#14116]
Hello, what are the minimum system requirements for the jitsi meet application for android and ios devices? can you support me in this regard?

**Comment by saghul** [comment]
The minimum supported Android API level is 24 (7.0) and the minimum supported iOS version is 12.

**Comment by saghul** [comment]
CPU usage is certainly the determining factor. Core count, however, is a bad metric because not all cores are created equal, specially in the cheap device Android market.

**Comment by ysbutuner** [comment]
Thank you for your answers.
CPU usage is definitely the determining factor, but are there any limits you set?

**Comment by saghul** [comment]
No we don't set any limits.

**Comment by ysbutuner** [comment]
Thank you for the support
