### ISSUE TITLE
VIDEO_LAYOUT_FIT in interface_config has not taken effect in mobile app

### ISSUE THREAD

**Issue by NimbleDev** [jitsi/jitsi-meet#14110]
### Description:

We built our mobile app using react native sdk.  We've set VIDEO_LAYOUT_FIT to "width" instead of default "both". 

When we join a meeting thru mobile web brower, we found this config change does take effect as shown below.
![image](https://github.com/jitsi/jitsi-meet/assets/51120096/eb82809e-45a2-4e93-b262-073c08bd7662)

But when we join a meeting thru mobile app (both android and ios), it seems that the layout does not fit to the width of the screen as expected as shown below.
![image](https://github.com/jitsi/jitsi-meet/assets/51120096/44eddb4f-2d22-4b89-8a7d-8866d7cb262c)

### Steps to reproduce:

join a meeting thru mobile app

### Expected behavior:

the layout should fit to the width of the screen

### Actual behavior:

the layout does not fit to the width of the screen

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by NimbleDev** [comment]
> The mobile apps do not use interface_config.
> 
> In the screenshot below, did you pinch to zoom?

I've tried but it didn't work either.

**Comment by saghul** [comment]
Do you observe the same behavior in the official apps?
