### ISSUE TITLE
While sharing the screen, the camera cannot be turned on again after obtaining camera permission.

### ISSUE THREAD

**Issue by HacerBusraKILIC** [jitsi/jitsi-meet#14126]
### Description:

While sharing the screen, the camera cannot be turned on again after obtaining camera permission.

### Steps to reproduce:

1. join a meeting of two people
2. someone shares screen from mobile app
3. Camera permission is turned off during screen sharing
4. The participant sharing the screen can no longer turn on the camera

### Expected behavior:

The person sharing the screen should also be able to open the camera

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:  23.6.1,23.7.0 android app
- Operating System:

**Comment by HacerBusraKILIC** [comment]
@saghul

**Comment by saghul** [comment]
This is by design. Regardless of the permission mobile users cannot share their screen and camera at the same time.

This is for performance reasons.

**Comment by HacerBusraKILIC** [comment]
Hello @saghul ,
It does not open at the same time. While one participant shares the screen, another participant gets permission to share the camera & screen screen. When the permissions are returned, the camera of the person sharing the screen becomes active, but they press the camera button and the camera does not turn on.

**Comment by HacerBusraKILIC** [comment]
It happens on Android devices. I was able reproduce on 23.6.1,23.7.0 versions

**Comment by saghul** [comment]
Did you test by using the "video mute evetyone" moderator control, like in the video?

**Comment by Calinteodor** [comment]
So, yeah, sorry. With moderation, Android cannot open video again. Weird. Looking into it.

**Comment by HacerBusraKILIC** [comment]
Hi @saghul @Calinteodor ,
Is there any progress?
