### ISSUE TITLE
Can you support custom ui

### ISSUE THREAD

**Issue by RebelTinker** [jitsi/jitsi-meet#14120]
Can you support custom ui

**Comment by RebelTinker** [comment]
And how should I close the selection page of h5 page 
![a36a833a49297fb77c9342edcf5edc1](https://github.com/jitsi/jitsi-meet/assets/58228765/b30ef8ff-e5cb-4094-8e49-c68d5916d52c)

**Comment by saghul** [comment]
I don't know what you're asking, sorry.
