### ISSUE TITLE
resolution constraints on mobile apps

### ISSUE THREAD

**Issue by ysbutuner** [jitsi/jitsi-meet#14127]
Video quality looks shaky when focused. My values are as follows, do you have any solution suggestions?

resulation 360
constraints: {
        video: {
            frameRate: {
                    max: 24
            },
            height: {
                ideal: 720,
                max: 720,
                min: 180
            },
            width: {
                ideal: 1280,
                max: 1280,
                min: 320
            }
        }
    },

**Comment by ysbutuner** [comment]
@saghul

**Comment by saghul** [comment]
The apps are hardcoded at 360p. The SDK isn't.

**Comment by Corey-Maler** [comment]
@saghul just to clarify your answer: it is kind of not possible to get high resolution from mobile web clients right now? We are fighting with it now after update to 9111 and cannot make iOS web send more than 360.

**Comment by saghul** [comment]
How does your config.js look like?

**Comment by Corey-Maler** [comment]
We are trying with default config.js first, then tried to add
```js
if (!config.hasOwnProperty('constraints')) config.constraints = {};
if (!config.constraints.hasOwnProperty('video')) config.constraints.video = {};

config.resolution = 1280;
config.constraints.video.height = { ideal: 1280, max: 1280, min: 320 };
config.constraints.video.width = { ideal: 1280, max: 1280, min: 320};
config.disableSimulcast = false;
config.startVideoMuted = 10;
config.startWithVideoMuted = false;

```

**Comment by saghul** [comment]
Your options look very weird. I suppose you want to use 720p, right? The it should be:

```
if (!config.hasOwnProperty('constraints')) config.constraints = {};
if (!config.constraints.hasOwnProperty('video')) config.constraints.video = {};

config.resolution = 720;
config.constraints.video.height = { ideal: 720, max: 720, min: 180 };
config.constraints.video.width = { ideal: 1280, max: 1280, min: 320};
config.disableSimulcast = false;
config.startVideoMuted = 10;
config.startWithVideoMuted = false;
```

**Comment by Corey-Maler** [comment]
Yeah, I guess we copied config before portrait / landscape fix (since mobile devices sends in portrait, height is now width). Will try suggested config.

But anyhow, even if I join meet.jit.si via mobile browser (iOS safari), it still would send 360p. And I assume it has default config not far from what did you suggest

**Comment by saghul** [comment]
I'm not sure.

@jallamsetty1 Did we add that 360p for mobile in lib-jitsi-meet? I cannot find it.

**Comment by Corey-Maler** [comment]
Actually tried safari / chrome on the same machine right now on meet.jit.si and results like this. Is it expected?

![Screenshot 2024-01-25 at 10 43 48](https://github.com/jitsi/jitsi-meet/assets/8354173/57ce40ac-d6f3-4376-b896-bc00276435ca)

**Comment by saghul** [comment]
I think you are experiencing this recently fixed bug: https://github.com/jitsi/lib-jitsi-meet/pull/2437

**Comment by Corey-Maler** [comment]
O nice, did check on beta.meet.jit.si, it fixed issues for desktop safari, but mobile safari is... I call it "stylish", but it is 0.5fps and very very pixilated when you are moving and super sharp when you sit still. (picture on iOS itself sometimes freezes for 10 seconds).


![Screenshot 2024-01-25 at 11 01 34](https://github.com/jitsi/jitsi-meet/assets/8354173/4b475162-a6e0-426c-8e6b-e9254a43938a)

**Comment by saghul** [comment]
What resolution and fps do you get? Note that with 2 participants you'll be using P2P, so we won't be handling the media, that's just between browsers.

**Comment by Corey-Maler** [comment]
Yeah, makes sense. Anyhow, just using regular iPhone 12 on beta.meet.jit.si causes this behaviour. And do you use simulcast in 1-2-1 (p2p) calls?

**Comment by saghul** [comment]
That's because beta has 4K configured by default as we are testing it right now.
