### ISSUE TITLE
Android 14 Crash - FOREGROUND_SERVICE_MEDIA_PROJECTION or CAPTURE_VIDEO_OUTPUT

### ISSUE THREAD

**Issue by dakshay-devstree** [jitsi/jitsi-meet#14137]
**Jitsi Meet SDK Versioin - 8.6.0
Device - Google Pixel 6 and Google Pixel 6a
Android OS - 14**

> java.lang.RuntimeException: Unable to create service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{c721d92 17287:com.example.android/u0a1009} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media]
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4664)
> 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:205)
> 	at android.os.Looper.loop(Looper.java:294)
> 	at android.app.ActivityThread.main(ActivityThread.java:8177)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{c721d92 17287:com.example.android/u0a1009} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media]
> 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
> 	at android.os.Parcel.createException(Parcel.java:3041)
> 	at android.os.Parcel.readException(Parcel.java:3024)
> 	at android.os.Parcel.readException(Parcel.java:2966)
> 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
> 	at android.app.Service.startForeground(Service.java:775)
> 	at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onCreate(JitsiMeetOngoingConferenceService.java:97)
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4651)
> 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264) 
> 	at android.os.Handler.dispatchMessage(Handler.java:106) 
> 	at android.os.Looper.loopOnce(Looper.java:205) 
> 	at android.os.Looper.loop(Looper.java:294) 
> 	at android.app.ActivityThread.main(ActivityThread.java:8177) 
> 	at java.lang.reflect.Method.invoke(Native Method) 
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
> Caused by: android.os.RemoteException: Remote stack trace:
> 	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2611)
> 	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2322)
> 	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1679)
> 	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13281)
> 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3385)

![image](https://github.com/jitsi/jitsi-meet/assets/53896356/e4f52b3d-1c00-42b5-bee6-cc1e08bf8fe8)

**Comment by saghul** [comment]
Are you building with a target SDK level of 34? Our SDK does not support it yet, it's being worked on here: https://github.com/jitsi/jitsi-meet/pull/14129

**Comment by dakshay-devstree** [comment]
Yes, I'm building the project with Target SDK 34. Hope it get it resolve soon. Thanks for updates.

**Comment by raanaYavari** [comment]
Please merge this pull request as soon as possible!!

**Comment by saghul** [comment]
This is not a pull request.
