### ISSUE TITLE
How should I close this page, the effect I need is to provide the browser directly into the room, instead of this selection page

### ISSUE THREAD

**Issue by RebelTinker** [jitsi/jitsi-meet#14136]
![image](https://github.com/jitsi/jitsi-meet/assets/58228765/25350603-3572-4eff-8c22-7fb66266f203)

**Comment by saghul** [comment]
Configure this on your deployment: https://github.com/jitsi/jitsi-meet/blob/7de88f4e475765b78cb6229918a9ec06520f6b9c/config.js#L1200

**Comment by RebelTinker** [comment]
@saghul I installed it using docker, where should I change it
