### ISSUE TITLE
The toolbar box remains shifted up when the tile view mode is off

### ISSUE THREAD

**Issue by LSViana** [jitsi/jitsi-meet#14148]
### Description:

The toolbar box shifts up even when it's not in tile view mode.

In more detail, PR #13384 added a behavior to slightly shift the toolbar box up to make sure the names of the participants are shown correctly and it works very well, as this image shows:
![Toolbar box correctly shifted up demo](https://github.com/jitsi/jitsi-meet/assets/21217790/f22c10fe-9898-4314-ad2a-41d91a07d6f4)

However, when disabling the tile view mode (via `executeCommand('setTileView', false)`), the toolbar box remains shifted up, as this image shows: ![Toolbar box incorrectly shifted up demo](https://github.com/jitsi/jitsi-meet/assets/21217790/ccdba30f-45eb-4d1b-9062-97fc8987555a)

### Steps to reproduce:

1. Create a video call with a small `<iframe>` to turn the floating toolbar box into a "bottom docked" toolbar
2. Toggle the tile view mode off (as shown below)
3. Notice how the toolbar box remains shifted up — this is the bug

### Expected behavior:

The toolbar box shouldn't shift up when the tile view mode is off.

### Actual behavior:

The toolbar box remains shifted up when the tile view mode is off.

### Server information:

~- Jitsi Meet version:~
~- Operating System:~

Using Jitsi as a Service.

### Client information:

- Browser / app version: Chrome 119
- Operating System: macOS

**Comment by saghul** [comment]
@horymury cab you ptal when you get a chance?

**Comment by hharshas** [comment]
sir i would like to work on this.

**Comment by saghul** [comment]
It has already been assigned, sorry!

**Comment by horymury** [comment]
created PR with fix .

@saghul  @LSViana
