### ISSUE TITLE
Some API Features Doesn't Working

### ISSUE THREAD

**Issue by nzhtrtlc** [jitsi/jitsi-meet#1414]
Hi, i followed the doc which is  https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

`api.executeCommand('toggleChat');` and methods like who doesnt take any arguments works fine.

But methods which is takes arguments and the eventListeners doesnt work.

For example:
`api.executeCommand('displayName', 'New Nickname');`

**throws** 

> Uncaught TypeError: e.trim is not a function
>     at n.g (conference.js:290)

`api.executeCommand('avatarUrl', 'https://avatars0.githubusercontent.com/u/3671647');`

this code doesnt work.

And event listeners doesnt work too.

I wrote two listeners

`var listener1 = function(){
  console.log(" LISTINER_1_TRIGGERED ");
}
api.addEventListener("outgoingMessage", listener1);`
 returns nothing but not working too.

`var listener2 = function(){
  console.log(" LISTINER_2_TRIGGERED ");
}
api.addEventListener("displayNameChanged", listener2);`
returns error 

> Not supported event name.

And how i can manage user roles like moderator with API ?

May you update/fix API ?

I heard you're working on the new version.
When will it be published?

**Comment by nzhtrtlc** [comment]
<script src="https://meet.jit.si/external_api.js"></script> **DEPRECATED**

use anything upto-date instead of this url.

Problem solved.

**Comment by trda** [comment]
@nzhtrtlc, What is the updated version of this API? What will come in place of this external URL(https://meet.jit.si/external_api.js) ?

**Comment by ic-hv** [comment]
I am still curious, what we shall use instead of "external_api.js".

It seems the "api.executeCommand" (taking two params) only works, when connecting the second(!) time, but not when connecting the first time ...

**Comment by anshulbisen** [comment]
try

`https://meet.jit.si/lib/external_api.js`
