### ISSUE TITLE
IOS Screen Share is not working

### ISSUE THREAD

**Issue by Bruno-Megaleios** [jitsi/jitsi-meet#14160]
In the IOS, the screen share is not working, the app its not appearing in record menu. I tryed the example App too.

![image](https://github.com/jitsi/jitsi-meet/assets/86243188/484a965e-4b8a-41e7-bb44-569cbfc793db)

**Comment by saghul** [comment]
What SDK are you using?

**Comment by Bruno-Megaleios** [comment]
Flutter, [jitsi-meet-flutter-sdk](https://github.com/jitsi/jitsi-meet-flutter-sdk)

**Comment by saghul** [comment]
The Flutter SDK does not currenrly support screen sharing on iOS.

**Comment by Bruno-Megaleios** [comment]
Do you have any predictions?

**Comment by saghul** [comment]
Not in the short term, sorry.
