### ISSUE TITLE
React Native App use jitsi-meet-sdk must setup bundleAssetName to app.bundle

### ISSUE THREAD

**Issue by Symous** [jitsi/jitsi-meet#14162]
### Description:

Hi, awesome lib. I just install org.jitsi.react:jitsi-meet-sdk to my React Native Android App and trying to write my own Jitsi module, and refer some of thrid party jitsi react native lib, I have just found that we must setup bundleAssetName to app.bundle to make it possible to work fine in release mode(otherwise crash). It  broke my app structure and I do know whether it is a bug.  I am just curious about why jitsi do like this and where I can find the code logic handle this to point the bundle asset name to app.bundle. Any one can help me? thanks!
### Steps to reproduce:

1. implementation org.jitsi.react:jitsi-meet-sdk in app/build.gradle of React Native App
3. write module and call jitsi
4. works fine in debug mode and crash in release mode if dont modify bundleAssetName to app.bundle

### Expected behavior:

works fine with default index.android.bundle

### Actual behavior:

crash in release mode

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: 
- Operating System:

**Comment by saghul** [comment]
If you have a RN app then you should be using our RN SDK and not the native one.

Please see: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-react-native-sdk

**Comment by Symous** [comment]
@saghul  I am certainly want to use @jitsi/react-native-sdk from your team, but I just maintaining a old project with former React Native version seems like that not satisfy the dependencies requirements, and it also need to install many additional third-party libs by `node node_modules/@jitsi/react-native-sdk/update_dependencies.js` which may broke my original project. 

So can you please just tell me why the app.bundle assetName is required to setup when I integrate the android sdk to my app? thanks again.

**Comment by saghul** [comment]
> So can you please just tell me why the app.bundle assetName is required to setup when I integrate the android sdk to my app? thanks again.

That's because our native SDK is just a wrapper around the RN SDK.

**Comment by Symous** [comment]
@saghul thanks for your reply, I understand that the native sdk is a wrapper around the RN SDK, but generally the bundle name is default to *index.android.bundle* instead of app.bundle, I have dived into the source code and try to find the where is the code make the configuration to rename to **app.bundle**, but I found nothing. can you please provide me more details, I am just straggle with this with my project. thanks for your patient.

**Comment by saghul** [comment]
It might depend on what RN version you are using. Sorry I don't know it right off the bat because we sue this modified layout ourselves.

**Comment by Symous** [comment]
Just one thing I need to confirm: 
Your jitsi team has never made this **app.bundle** modification in the past versions, right?

**Comment by saghul** [comment]
No, we haven't.

**Comment by Symous** [comment]
@saghul thanks. in fact I have been closely following and testing @jitsi/react-native-sdk for a while now, and have strong willings to integrate to my project. But it seems like not an official release I guess. Why the react-native-sdk can not install thoese addtional packages automatically but need we manually run `node node_modules/@jitsi/react-native-sdk/update_dependencies.js`?  it make the based project looks like chaotic. :(

**Comment by Symous** [comment]
and another problem is the react-native-sdk is not friendly to old react-native version, there are lot of compatibility issues need to sloved by ourselves.

**Comment by saghul** [comment]
> But it seems like not an official release I guess.

I don't know what that means. We make it, it's in our GH org and published on our own npm namespace. Not sure how much more "official" you want it.



> Why the react-native-sdk can not install thoese addtional packages automatically but need we manually run `node node_modules/@jitsi/react-native-sdk/update_dependencies.js`?

Great question. Rn won't auto-link dependencies of your dependencies. See for example the installation docs of libraries like react-navigation. You are asked to install many dependencies yourself because if they would depend on them they wouldn't be auto-linked.

With a project as large as this our dependency list is lasge, so we chose to write a script to help and automate that. If yopu have suggestions on how to improve it, we'd be happy to apply them!

> and another problem is the react-native-sdk is not friendly to old react-native version, there are lot of compatibility issues need to sloved by ourselves.

We cannot support every RN version under the sun, sorry.

**Comment by Symous** [comment]
that's wired, I can not understand why I integrate jitsi-meet-sdk android to my react native app need to specify index.android.bundle to app.bundle, but I have to. still thanks.
