### ISSUE TITLE
Add Config to change the default view camera at start

### ISSUE THREAD

**Issue by aristech** [jitsi/jitsi-meet#14163]
**Is your feature request related to a problem you are facing?**
I'm facing a problem where a client wants to show own camera as default view in browser.
Tiles or filmstrip is off the table, just self camera at start up.

**Describe the solution you'd like**
I was hopping maybe would be possible to make a config change for the startup UI view.
When user joins room, firs thing he sees is it's own camera (USER || ENVIROMENT)

**Describe alternatives you've considered**
I have search the forum for a solution and found a [post](https://community.jitsi.org/t/set-self-view-by-default-when-joining-a-meeting-in-android/114722) about native view where is possible to make the default view own camera by changing participantId to localId in props.
I tried this implimentation in the .../jitsi-meet/react/features/large-video/components/LargeVideo.web.tsx but it doesn't  make any difference

**Comment by saghul** [comment]
We do have support for this now, right @horymury ? Can you point at the right option?

**Comment by horymury** [comment]
Yep, here it is:
https://github.com/jitsi/jitsi-meet/blob/990d21038ee896aab1206e8d7e4de652920883a2/config.js#L226
