### ISSUE TITLE
Name of who sent to breakout room

### ISSUE THREAD

**Issue by opk12** [jitsi/jitsi-meet#14179]
**Is your feature request related to a problem you are facing?**
A vandal pressed the button to send everyone to the breakout rooms. After a couple rounds, we got what was going on, and chose to set a password.

**Describe the solution you'd like**
A community member suggested that it would have been slightly easier for us if the breakout room joining notification mentioned the responsible user.

**Comment by saghul** [comment]
At that point the meeting would have already been disrupted, however.

Adding the name of the moderator who sent you to a breakout room (or asking for approval, maybe) sound reasonable.

**Comment by Sadaf-A** [comment]
Hey @saghul could you assign this to me I would like to work on this

**Comment by saghul** [comment]
We don't assign issues. Feel free to send a pull request!

**Comment by opk12** [comment]
Is it a good reason to close the feature request though?

**Comment by opk12** [comment]
The issue tracker is subject to heavy end-user pressure (spam-borderline sometimes), but I'd assume that spamming a no-op and artificially keeping the issue count low can not help and may worsen things.

From a quick look, the recently closed issues are not older than a month I think, so the bot should reply on the *new* issues instead and annoy the user: search the forum, update the app, release schedule...

**Comment by opk12** [comment]
I have not seen a bot malfunction. Waiting for years on open tickets is usual and expected in the global FLOSS community of smallish projects with limited manpower. Your repo, your rules, but while authors of poor tickets are reinforced with dev attention, I am incentivized to decide in your place if XYZ will be a WONTFIX, or to not log into GH at all, because Closed nowhere means CONFIRMED / accepted.
