### ISSUE TITLE
Click through menu

### ISSUE THREAD

**Issue by opk12** [jitsi/jitsi-meet#14178]
### Description:

Yesterday, in the web version: clicking on `Private Message` enlarged the tile of the user who was behind the menu. I cannot reproduce after closing Firefox, but I thought you'd want to know.

### Steps to reproduce:

I joined `meet.jit.si/convo`, hovered the three-dots blue button, clicked on `Private Message`. This had the effect of clicking on the tile that was sitting behind the menu, that tile was enlarged. I tried messaging various people, same result.

I cannot reproduce this. It worked again after closing and restarting Firefox. It is also working today.

### Server information:

This is `meet.jit.si` from Dec 20, 2023.

### Client information:

- Browser / app version: 115.5.0esr-1~deb11u1 from Debian 11 repo
- Operating System: Debian 11

**Comment by Harshalvk** [comment]
I would like to work on this!

**Comment by saghul** [comment]
If this is no longer reproducible, there might be nothing to fix :-)

**Comment by opk12** [comment]
Yes, this is just a heads-up. Feel free to close this if you cannot reproduce (I still cannot).

Happy holidays :)

**Comment by saghul** [comment]
Tentatively closing this then.

Happy holidays!
