### ISSUE TITLE
Audio/Video not working: Error message: <user> is having connectivity issues

### ISSUE THREAD

**Issue by freibadschwimmer** [jitsi/jitsi-meet#1417]
I seem to cannot get jitsi-meet running. I have tried it now on 2 different machines (both running Debian Jessie), where I get stuck at the same problem.
I tried the quick install (apt install jitsi-meet) and it seems to install fine. I tried all branches (stable, testing, unstable), all result in the same problem. Currently running jitsi-meet testing.

I am not sure if this could be connected with certificate issues, though I am using letsencrypt certificates. However, I ran into the same issues when using self signed certificates.

When starting a new session, I can connect audio & video devices to the browser and also see my own video in my browser. When other users log in, I can see them joining, and can also send & receive text messages. However, when one tries to open the video of other users, the image remains black. When turning off other users' video, the avatar becomes visible, while when turning on video again the image turns black again.

When I check the jicofo.log I only see information messages, but no errors or warnings.
When I check the jvb.log, I also get warnings and errors:
> WARNUNG: [17] org.jitsi.videobridge.Endpoint.log() SCTP connection with fd644301 not ready yet.

and
> SCHWERWIEGEND: [10671] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.

When I try to open the video of other users in Chromium, in the browser window it tells me : 
> user is having connectivity issues.

Moreover the Chromium console gives me the following errors:

> [modules/util/helpers.js] <a>:   Error: No opened data channels found!
    at r.send (DataChannels.js:273)
    at r._onXXXEndpointChanged (DataChannels.js:236)
    at r.sendPinnedEndpointMessage (DataChannels.js:204)
    at t.value (RTC.js:206)
    at o.pinParticipant (JitsiConference.js:820)
    at n.<anonymous> (conference.js:1352)
    at n.emit (events.js:84)
    at Object.handleVideoThumbClicked (VideoLayout.js:420)
    at HTMLSpanElement.i (RemoteVideo.js:660)
i @ Logger.js:125
a @ helpers.js:44
(anonymous) @ conference.js:1354
n.emit @ events.js:84
handleVideoThumbClicked @ VideoLayout.js:420
i @ RemoteVideo.js:660

> Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError:  Script: null Line: null Column: null StackTrace:  Error: No opened data channels found!
    at r.send (DataChannels.js:273)
    at r._onXXXEndpointChanged (DataChannels.js:236)
    at r.sendPinnedEndpointMessage (DataChannels.js:204)
    at t.value (RTC.js:206)
    at o.pinParticipant (JitsiConference.js:820)
    at n.<anonymous> (conference.js:1352)
    at n.emit (events.js:84)
    at Object.handleVideoThumbClicked (VideoLayout.js:420)
    at HTMLSpanElement.i (RemoteVideo.js:660)

Any help on how to find the cause and solve the problem is very much appreciated!
Thanks,
freibadschwimmer

**Comment by damencho** [comment]
Please use the mailinglist when asking questions or want to discuss something, before opening an issue.

Did you forward all the needed ports to the jvb (tcp 443 or 4443, udp 10000)? If your jvb is running on a private address you need to configure its private and public address in the configuration: https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_local_address

**Comment by freibadschwimmer** [comment]
Thank you very much for your reply.

I am sorry, I missed the point to first use the mailing list. Will of course consider this in future.

Thanks for your hints. Opening ports 4443 and 10000 seem to have solved the problem in the current set up.

Thanks!
freibdschwimmer

**Comment by alexdorn87** [comment]
Hi 

I met same problem.
Could you help me to know where I need to open port 4443, please?

**Comment by damencho** [comment]
@alexdorn87 If you have a firewall you need to open 10000 udp and 443, 4443 tcp ports. If you are installing behind nat, you need to make sure you forward those ports to the machine running the deployment, where to do that depends on your deployment, whether it is your router or your hosting provider's configuration console.

**Comment by alexdorn87** [comment]
Hi @damencho 

thanks for your help.
I am using AWS EC2.
I checked my server on "http://www.yougetsignal.com/tools/open-ports/".
it said 443 port is open.
when I use AWS EC2, do I need to set something for NAT?

My server's outside ip address is 35.157.23.249
ubuntu@ip-10-0-0-57:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 06:b5:2b:f1:8a:59
          inet addr:10.0.0.57  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::4b5:2bff:fef1:8a59/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:706583 errors:0 dropped:0 overruns:0 frame:0
          TX packets:496203 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:34631537 (34.6 MB)  TX bytes:1272398811 (1.2 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:47593 errors:0 dropped:0 overruns:0 frame:0
          TX packets:47593 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:11689307 (11.6 MB)  TX bytes:11689307 (11.6 MB)

thanks

**Comment by alexdorn87** [comment]
do I need to open port 4443, too?

**Comment by alexdorn87** [comment]
My OS is ubuntu 16.04

**Comment by alexdorn87** [comment]
Could you check https://35.157.23.249 for me, please?
If you have a look at it for me, It will be very thanksful on me

**Comment by damencho** [comment]
Currently your jicofo is not running or haven't connected to the xmpp server.

**Comment by alexdorn87** [comment]
oh~ sorry for that.
I run them now
Could you see again it, please?

**Comment by alexdorn87** [comment]
Hi @damencho 
sorry for requesting too many help.

**Comment by alexdorn87** [comment]
I can see other guys.
But when I click the guy, browser shows "No opened data channels found!" and shows following error.

[modules/xmpp/JingleSessionPC.js] <o.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed P2P? false:	 42349.285
app.bundle.min.js?v=139:60 [conference.js] <e.value>:  CONFERENCE FAILED: conference.setup_failed Error: ICE fail
    at o.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:327)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TraceablePeerConnection.js:258)

**Comment by damencho** [comment]
It is working fine now.

**Comment by alexdorn87** [comment]
thanks very much

**Comment by RonakMutha12** [comment]
@damencho  facing the same issue, 443 TCP port is open and UDP 10000-20000.
Still my browser shows "No opened data channels found!" and shows following error. and CONFERENCE FAILED: conference.setup_failed Error: ICE fail

**Comment by damencho** [comment]
@RonakMutha12 if jvb is running on a private address behind NAT, did you [configure the public and private address](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration)?
