### ISSUE TITLE
[RNSDK - IOS] The app crashes when turn off network on the Ipad

### ISSUE THREAD

**Issue by quanganh9527** [jitsi/jitsi-meet#14188]
### Description:

I'm using source code from jitsi example and I found a problem. When I join the meeting and am placed in the lobby screen, if I turn off Wi-Fi for a moment, the app crashes.

### Steps to reproduce:

1. Join a meeting screen and then navigate to lobby screen
2. Turn off the wifi
3. For a moment, the app crashes

### Expected behavior:

The app rejoins the meeting 

### Actual behavior:

The app crashes

### Server information:

- Jitsi Meet version: unknow
- Operating System: unknow

### Client information:

- Browser / app version: @jitsi/react-native-sdk: ^1.0.2
- Operating System: Ipad - IOS 16.3

### Additional information:
[RNSDKTester-2023-12-28-031354.log](https://github.com/jitsi/jitsi-meet/files/13785196/RNSDKTester-2023-12-28-031354.log)

**Comment by saghul** [comment]
Does this happen in debug mode or release?

**Comment by quanganh9527** [comment]
that just happens in release mode

**Comment by quanganh9527** [comment]
> Does this happen in debug mode or release?



> Does this happen in debug mode or release?



> Does this happen in debug mode or release?

that just happens in release mode

**Comment by saghul** [comment]
Must be an uncaught exception. Do you get a red or yellow box in debug mode?

**Comment by quanganh9527** [comment]
> Must be an uncaught exception. Do you get a red or yellow box in debug mode?
When I run on the simulator in debug mode, It also crashes and I get these error messages
![Screen Shot 2023-12-29 at 15 02 13](https://github.com/jitsi/jitsi-meet/assets/12388946/3260ff22-4f0d-45cb-836f-93fba6db6ff5)

**Comment by saghul** [comment]
Those are ok, I see no crash there.

**Comment by quanganh9527** [comment]
> Those are ok, I see no crash there.

Can you provide me some advice to fix the crash issue on release mode?
On my project I also encountering the same Jitsi example issue :(

**Comment by AnithaFrontm** [comment]
Facing same issue.. Please provide any solution for this crash

**Comment by saghul** [comment]
THat should've been fixed with the latest beta (24.3.0) can you give it a try?

**Comment by AnithaFrontm** [comment]
Already i am in a latest verion as for echo voice issue you said and i updated to latest version but in latest version when call started and i disconnect my wifi or network, app crashes

**Comment by saghul** [comment]
@Calinteodor PTAL

**Comment by Calinteodor** [comment]
Hello @AnithaFrontm. 
Do you repro this issue with latest Jitsi Meet beta app? 
Thank you.

**Comment by AnithaFrontm** [comment]
> Hello @AnithaFrontm. Do you repro this issue with latest Jitsi Meet beta app? Thank you.

Hi @Calinteodor  can you share me the link for the latest jitsi meet beta app so i can confirm once and download and try to repro this issue

**Comment by saghul** [comment]
https://testflight.apple.com/join/isy6ja7S

**Comment by AnithaFrontm** [comment]
Hi @saghul @Calinteodor  i am using package sdk for jitsi : "@jitsi/react-native-sdk": "^2.2.1"
this is latest sdk as per your documentation

in iOS, when we disconnect network while in a call, still app crashes
Please help us asap

**Comment by saghul** [comment]
Can you please answer our question?

The latest beta app contains a fix for that, and we cannot reproduce the problem.

Can you double check?

The next RN SDK release will include a fix.

**Comment by AnithaFrontm** [comment]
i installed from above testflght link.. 
At this beta app from testflight app not crashing while turning off network

So when can i get this release in RN SDK

**Comment by saghul** [comment]
We are planning to release it soon.

**Comment by AnithaFrontm** [comment]
Ok please let me know whenever its released
