### ISSUE TITLE
Issue With Speaker Time Not Stoping

### ISSUE THREAD

**Issue by HarshPatel5940** [jitsi/jitsi-meet#14183]
## Description:
 When we someone is speaking in the meeting the speaker time starts increasing slowly and as soon as the speaker mutes, the speaker time is supposed to stop but the speaker time continue to increase, which leads to incorrect participants stat.

### Steps to reproduce:

1. Starts an Jitsi meet with one another participant
2. Let the other participant start speaking and mute.

### Expected behavior:
The speaker time should stop as soon as the speaker mutes.

### Actual behavior:
The speaker time continues increasing and then we end up in incorrect statistic's of speaker time data.

### Server information:
> Using the public jitsi web app
- Jitsi Meet version: 
- Operating System: 

### Client information:

- Browser / app version: Arc v1.0
- Operating System: Sonoma 14.2

--- 

- [x] I am willing to learn about the repo and fix this issue.

**Comment by saghul** [comment]
Is this happening on meet.jit.si?

**Comment by damencho** [comment]
I think, it was working like that since we introduced speaker stats...

**Comment by HarshPatel5940** [comment]
> I think, it was working like that since we introduced speaker stats...

Since it's working this way, don't we not end up getting invalid stats at the end of the meeting?

**Comment by damencho** [comment]
In most of the meetings there are not so many occasions where all participants stay muted for long time, which is why we have not seen many complaints about it and it works in the general use case.

**Comment by HarshPatel5940** [comment]
> In most of the meetings there are not so many occasions where all participants stay muted for long time, which is why we have not seen many complaints about it and it works in the general use case.

Yeah that's true and exactly why I did not notice until recently, even though I use jitsi quite regularly.

I would like to know, What are your opinions on this issue? Is it irrelevant? Is it good? Or is it a feature request and not a bug?

**Comment by damencho** [comment]
Not sure ... as we haven't seen so many complaints about it, I would say that's a new feature to update the speakerstats backend module to detect those.

**Comment by HarshPatel5940** [comment]
> Not sure ... as we haven't seen so many complaints about it, I would say that's a new feature to update the speakerstats backend module to detect those.

Ok, sounds good. Can you suggest me some actionable steps to steer this issue? Would like to open a new issue which says about this and will be a feature request issue instead of a bug?

**Comment by HarshPatel5940** [comment]
Hello, @saghul @damencho. firstly i would like to know if this issue is valid. if yes, i really want to contribute to jitsi.

---

In the meantime after some digging i think that the silence is not getting detected [here](https://github.com/jitsi/jitsi-meet/blob/master/react/features/rtcstats/middleware.ts#L91-L101) as if it was doing it would. we would not encounter this issue.
```ts
  case DOMINANT_SPEAKER_CHANGED: {
        if (isRTCStatsEnabled(state)) {
            const { id, previousSpeakers, silence } = action.participant;

            RTCStats.sendDominantSpeakerData({
                dominantSpeakerEndpoint: silence ? null : id,
                previousSpeakers
            });
        }
        break;
    }
```

**Comment by damencho** [comment]
This is for just sending data to rtcStats, has nothing to do with speaker stats.
Speaker stats, works by counting the time someone was dominant speaker. Dominant speaker is changed when a message from the bridge is received that a new dominant speaker is detected. 
So when the last dominant speaker mutes and nobody talks there will be no change so the time will continue counting for the last dominant speaker.

**Comment by HarshPatel5940** [comment]
> This is for just sending data to rtcStats, has nothing to do with speaker stats. Speaker stats, works by counting the time someone was dominant speaker. Dominant speaker is changed when a message from the bridge is received that a new dominant speaker is detected. So when the last dominant speaker mutes and nobody talks there will be no change so the time will continue counting for the last dominant speaker.

So this concludes that the cause of the issue is from the [video bridge](https://github.com/jitsi/jitsi-videobridge) not detecting the dominant speaker muting, right?

**Comment by HarshPatel5940** [comment]
@damencho can we close this issue?
