### ISSUE TITLE
Zip distribution

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/jitsi-meet#1418]
Would it be possible to distribute package as signed tar as well as deb packages?

This would ease some deployment options (like Docker).

**Comment by saghul** [comment]
We are not doing releases *per se* at the moment. The project is managed as a "rolling release" of sorts. Now, you can use GitHub's builtin zip support to download it, for example: https://github.com/jitsi/jitsi-meet/archive/master.zip so as long as you can trust github.com you should be fine. You can get specific tags for having reproducible builds.

**Comment by pierreozoux** [comment]
The idea of this is to have one day official docker images.
If we don't have signed tar or zip, it will not be possible.

So what do you think?

**Comment by damencho** [comment]
What about https://download.jitsi.org/jitsi-meet/src/?
We can add signitures the same way we have and for debian packages https://download.jitsi.org/unstable/signatures/.
Will this work?

**Comment by saghul** [comment]
@damencho Yep, that should do. I guess what we need is a detached signature file: 

```
gpg -a --output foo.tar.gz.sign --detach-sign foo.tar.gz
```

**Comment by damencho** [comment]
Added it for jitsi-meet and lib-jitsi-meet. Will close the issue after one build passes and uploads those signitures.

**Comment by saghul** [comment]
@damencho Awesome! Where are they located? I couldn't find them on the src URL.

**Comment by damencho** [comment]
https://download.jitsi.org/jitsi-meet/src/signatures/
https://download.jitsi.org/lib-jitsi-meet/src/signatures/

But it failed on the first build and I disabled the command for now. Your command failed with: gpg: cannot open tty `/dev/tty': No such device or address

**Comment by saghul** [comment]
Hum, I looked around and you might need to add `--no-tty` to the command because Jenkins has some weird stuff going on with ttys.

**Comment by damencho** [comment]
signatures available in pointed locations

**Comment by saghul** [comment]
@damencho Excellent! ❤️
