### ISSUE TITLE
Is it possible to turn off the "you are the only one in the meeting" message in react-native sdk

### ISSUE THREAD

**Issue by vnphu** [jitsi/jitsi-meet#14184]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
Please can you fill in the issue template?

**Comment by vnphu** [comment]
> Please can you fill in the issue template?

Is there a way to turn off "you are the only one in the meeting" when there is only one person in the room?

**Comment by saghul** [comment]
Not at this time, but a PR adding a feature flag would be welcome.
