### ISSUE TITLE
RNSDK [iOS] Add support for Picture-in-Picture

### ISSUE THREAD

**Issue by danilvalov** [jitsi/jitsi-meet#14185]
**Is your feature request related to a problem you are facing?**
Now there is [a stub for PIP button pressing on iOS](https://github.com/jitsi/jitsi-meet/blob/36963d6dfb0ec8a7b4d1e208aac2f4aa0f527b3d/react/features/mobile/picture-in-picture/actions.ts#L34).
It will be nice to have correct logic for this feature.

**Describe the solution you'd like**
`react-native-video` was updated some time ago, and fixed iOS PIP logic: https://github.com/react-native-video/react-native-video/pull/3221
Maybe we can update `react-native-video` to v.6.0.0-alpha.8 or later to enable PIP for iOS?

P.S. I haven't dived deep into this issue, so perhaps there are other technical difficulties besides `react-native-video` library-side issues that I'm not aware of.

**Comment by saghul** [comment]
For the sake of completeness: that won't be anough. We render video using react-native-webrtc, which does not use AVPlayer, so some significant custom code would be required to make this work.
