### ISSUE TITLE
Event cameraError not send if can't access thread

### ISSUE THREAD

**Issue by ThonyBat** [jitsi/jitsi-meet#14198]
### Description:

When executeCommand("toggleVideo"), nothing happens
I check if it's possible to get error and i see event "cameraError" but nothing listen returning

### Steps to reproduce:

1. Open first navigator (chrome)
2. Open iframe with JitsiMeetExternalAPI
3. Open camera on call
4. Open second navigator (edge)
5. Open iframe with JitsiMeetExternalAPI on same call
6. Execute command "toggleCamera"

### Expected behavior:

Expect to get error with listen "cameraError" event

### Actual behavior:

Nothing event catch

### Server information:

- Jitsi Meet version: sourceMappingURL=lib-jitsi-meet.min.map
- Operating System: Debian

### Client information:

- Browser / app version: Edge 120.0.2210.91 / Chrome 120.0.6099.130
- Operating System: Windows 11

### Additional information:

On conference.js, i see catch error videoTrack but no reject localTracksF
![image](https://github.com/jitsi/jitsi-meet/assets/73229853/c2452519-5ad1-43f3-9591-c34c4bb6075f)

**Comment by saghul** [comment]
Can you check if you get the error reported on this event? https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events#erroroccurred
