### ISSUE TITLE
Camera and Microphone get stuck at connecting

### ISSUE THREAD

**Issue by ageekhere** [jitsi/jitsi-meet#14191]
### Description:

When joining a room the Camera and Microphone icons can get stuck at connecting and you cannot enable them.

Camera used Logitech HD Pro Webcam C910

### Steps to reproduce:

1. Restart jicofo, jitsi-videobridge2, prosody and nginx
2. Enter a room in Chrome using Windows 11 with another user in the call which is using android phone app (mic and camera should be working for both).
3. End the call from the chrome user
4. Have the chrome user enter the same call, now the Camera and Microphone icons get stuck at connecting and you have to restart prosody to fix the issue (no issue for the android user).

### Expected behavior:

The Camera and Microphone should not get stuck at connecting

### Actual behavior:

Camera and Microphone get stuck at connecting
![Screenshot 2023-12-30 112749](https://github.com/jitsi/jitsi-meet/assets/13173133/3d25cb8c-96ed-4c21-8758-9737aefae794)

### Server information:

- Jitsi Meet version: 2.0.9164-1
- Operating System: Ubuntu 20.04.6 LTS 

### Client information:

**Client 1**
- Google Chrome Version 120.0.6099.130 (Official Build) (64-bit)
- Firefox 121.0 (64-bit)
- Operating System: Windows 11

**Client 2**
- Android app 23.6.1

**Comment by saghul** [comment]
Did you disable the prejoin screen in config.js?

**Comment by ageekhere** [comment]
> Did you disable the prejoin screen in config.js?

No, prejoinConfig is commented out.

**Comment by ageekhere** [comment]
It seems that when the rejoin screen comes up when you restart the service it unlocks the camera and mic again.

**Comment by ageekhere** [comment]
Update: if i disabled authentication = "internal_hashed" and set it back to authentication = "anonymous" under prosody cfg.lua the issue has gone a way. So it seems to happen when login password is enabled.

**Comment by hsmbfg80** [comment]
same here, how to fix that? i want to use the authentication = "internal_hashed"

**Comment by lucasvmx** [comment]
Worked for me after enabling prejoinConfig in config.js
