### ISSUE TITLE
Impossible to connect to my own server with the android app

### ISSUE THREAD

**Issue by yorffuoj** [jitsi/jitsi-meet#14199]
### Description:

Hi, I have a bug similar to https://github.com/jitsi/jitsi-meet/issues/12719, but I could not resolve it this way. I think this was unnecessary because you've already made the fix.

I have installed a Jitsi instance (version 2.0.9164) on my own server using Yunohost. It works fine on the web or with the Linux flatpak.
When I use the Android app (version 23.6.1 build 23600102), I cannot join any room of this server, see the following screenshot

![Screenshot_20240104-215002_Jitsi_Meet](https://github.com/jitsi/jitsi-meet/assets/47420551/28fc2fec-1f8a-4cd1-8179-cd5382621d6a)

Approximate translation: Sadly a problem occurred. We are trying to fix it. Reconnection in 29 seconds...

This also happens when I open the link with the browser and it asks me to open it with the app.
This does not happen for meetings on other servers that are not mine so I suppose the problem comes from the server configuration and not the app.

Here is my config.js: 
https://pastebin.com/NJR5y5mp

### Server information:

- Jitsi Meet version: 2.0.9164
- Operating System: Debian 11

### Client information:

- Browser / app version: 23.6.1 build 23600102
- Operating System: Android

I tried to find other issues that look like mine and I just found the one I mentioned above.

Thank you a lot for the time you will take to answer me.

**Comment by saghul** [comment]
Do you have a valid TLS certificate on your server?

**Comment by yorffuoj** [comment]
Yes, it is signed with let's encrypt, automatic renewal

**Comment by saghul** [comment]
Share your sever URL please.

**Comment by yorffuoj** [comment]
https://jitsi.jouf.fr

**Comment by User778076** [comment]
Hi - have the same issue and resolved. You need one certificate file contain full chain of certificates - you certificate, middle certificate (if have) and CA of authority center. 
I generate certificate by command - change example.com to you domain 

/opt/acmesh/.acme.sh/acme.sh -f --issue -d example.com --standalone --server letsencrypt

and got files - one of files have name fullchain.cer - use this file.
