### ISSUE TITLE
Need start recording feature for custom UI in Jitsi IOS SDK

### ISSUE THREAD

**Issue by maulikgoyanidbc** [jitsi/jitsi-meet#14206]
We are using custom UI in meeting. and we have out own button to start and stop recording. We need give start and stop recording feature for custom UI. (I can see start recording option in jitsi toolbar. but we are hiding jitsi toolbar and showing our custom toolbar)

Thanks in advance.

**Comment by saghul** [comment]
If you have a custom UI you should do your own recording UI and just call the underlying API once recording should start.

What are you missing?

**Comment by maulikgoyanidbc** [comment]
@saghul 
Can you send me iOS swift code to start and stop recording?

**Comment by saghul** [comment]
We don't currently have a native API to start recording. You'd need to modify the JS code to do that.

**Comment by maulikgoyanidbc** [comment]
Recording is already working fine in our web app. In web we are using iFrame API. 
We also installed Jibri in our server for recording. 
As you said we don't have native api to start but still we can do it using JS code. so could you please  guide me more on this? like how can I achieve recording feature by modifying JS. some code snippet or documentation.

Thanks

**Comment by maulikgoyanidbc** [comment]
any update @saghul ?

**Comment by saghul** [comment]
You can use this iframe API: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands#startrecording
