### ISSUE TITLE
Video views cut off too much in tiled view - people invisible 

### ISSUE THREAD

**Issue by ned64** [jitsi/jitsi-meet#14200]
When in a meeting with three people altogether, each with a 16:9 camera and the own browser window maximised on a 16:9 screen, tiled view shows the three video feeds next to each other.:

    [O] [O] [O] I

In order to fit the feeds into the available area most of the video images is cut (approx. the left&right thirds).  When one feed has two people in it

    [O O]

neither of them is visible unless they are very close together in the middle of the frame.

Due to the browser headline, OS taskbar etc. the effect may even be stronger.

I would like to have an *option to not cut off more than, say 20% (configurable) of the video image area when tiling*.  A meeting with 3 video participants should then use 2x2 tiling on a 16:9 screen.

**Comment by netFLOw95** [comment]
There is a feature called "Face Centering" which might help you. See https://community.jitsi.org/t/face-centering/129334

**Comment by saghul** [comment]
In addition to that, you can set this config option to not do that:

```
    // If true, the tiles will be displayed contained within the available space rather than enlarged to cover it,
    // with a 16:9 aspect ratio (old behaviour).
    // disableTileEnlargement: true,
```

**Comment by ned64** [comment]
Thanks a lot, will try both.
