### ISSUE TITLE
Self view on iPad wrongly rotated in landscape mode, does not auto-rotate with device rotation

### ISSUE THREAD

**Issue by ned64** [jitsi/jitsi-meet#14201]
On a recent (2022/2023) iPad and using the Jitsi Meet app, the self view is not rotated when I rotate the device. That means all other participants are visible in their correct orientation while my self view is rotated by 90 degrees (ccw).

The only way to make everyone has the same orientation is to rotate the device back to portrait mode (which is how JM was started).  However, with a keyboard stand attached this isn't really ideal.

So: **How can I rotate the self view, or make it autorotate with all over views**?

**Comment by saghul** [comment]
How do you start the call? Does the problem persist if you rotate twice?

**Comment by ned64** [comment]
During startup the iPad is in landscape orientation, due to the keyboard stand. The room was joined by clicking a link in an e-mail.

IIRC I did try to rotate it back and forth and that did not help.

**Comment by saghul** [comment]
Are you able to reproduce this without the stand, as in, holding it in your hands? (I ask because I'm aware of an issue when the ipad if in a specific rotation position, but it doesn't apply if you hold it because the accelerometer works it out correctly).

**Comment by ned64** [comment]
I can try this but not today.

However, all other views are rotated correctly and automatically, only the self view isn't. Could that still be dependent on the iPad's sensor?

Who rotates the others' and self views, is it our JS app or the OS?
