### ISSUE TITLE
Improve cognitive ease, efficiency, and usability by adding labels to interactive elements

### ISSUE THREAD

**Issue by adamzea** [jitsi/jitsi-meet#14215]
**Is your feature request related to a problem you are facing?**
People don't know what the buttons at the bottom do because they aren't labeled in any discernable language. Literally every video conference meeting has some amount of wasted time from people asking "How do I share my screen?" because the navigation buttons are essentially unintelligible "mystery meat" icons that normal people can't understand. The issue persists for many even after being told a lengthy description of the button icon as they don't spend cognitive energy remembering these things between sessions. They DO remember how to read their native language between sessions though. 
Also see: [https://community.jitsi.org/t/label-the-ui-icons-so-people-can-recognize-them/31241](https://community.jitsi.org/t/label-the-ui-icons-so-people-can-recognize-them/31241)
Basically, all usability studies done on the subject in the past 30 years or so show that labeled interactive elements improve cognitive ease, engagement, efficiency, and usability significantly. 

**Describe the solution you'd like**
Add labels to the buttons by default so people can understand them instantly without having to ask other meeting attendees what they mean or where certain features are located.  Perhaps a hidden option in the settings can be added for removing the labels for people that really want the current less-usable design. 
![Image of Jitsi UI with labels](https://global.discourse-cdn.com/business4/uploads/jitsi/optimized/3X/2/4/2400be1e7242aea11636ca16a8f37139d25094a2_2_1344x998.jpeg)

**Describe alternatives you've considered**
- Wasting an extra few minutes during every meeting manually describing the icons at the bottom and translating what they do for the meeting attendees when requested (every time).
- Use a competing product that is better designed for usability such as Zoom which does show labels for its interactive elements (this is one of the reasons why Zoom has the majority 57% market share):
![Zoom video call screenshot](https://global.discourse-cdn.com/business4/uploads/jitsi/optimized/3X/5/5/55fc85d0a719c2aa3ecc18a2730638a56e2f870e_2_1380x756.jpeg)
- Adding custom CSS to enable labels on the toolbar:

`<style>
/* add labels to toolbar */
.toolbox-button {
width: 7vw;}

.toolbox-button:after {
content: attr(aria-label); 
font-size: 0.7rem;
line-height: 0.8rem;
}

.toolbox-icon { 
width: 100%; }

.welcome-page-settings .toolbox-button {
display: flex;}

.reactions-row .toolbox-button { width: 30%; }
.reactions-row .toolbox-icon span.emoji { width: 5rem; }
.reactions-row .toolbox-icon { width: 5rem; }
</style>`

**Comment by adamzea** [comment]
If people actually don't want the user interface to be easier to use, perhaps the labels can be hidden with a preference in the settings, but they should definitely be visible by default so that new users will have an improved user experience.

**Comment by saghul** [comment]
Thanks for the thought you put in this.

It may seem like a small change, but we have many customers now and we need to be cautious specially with UI/UX changes.

**Comment by adamzea** [comment]
So far on my server it's been a HUGE improvement in user experience. People no longer ask how to share their screens every day because they can see the button that has the words "start sharing your screen" on it.  They no longer have problems leaving the meeting because they can see the button with the words "leave the meeting" on it. They no longer have trouble muting or unmuting themselves because they can see the button with the word "mute" on it. It's a massive and obvious improvement to the usability.  I hope y'all decide to test it at some point. 
![image](https://github.com/jitsi/jitsi-meet/assets/24486391/ee130539-3bb9-4cad-b2bc-31962ab89163)

**Comment by adamzea** [comment]
Don't close as stale, robot.
That CSS code should also work for whatever language the user chooses as well, but I'm not sure how good it will look.

**Comment by hxrshxz** [comment]
i want to work on this issue

**Comment by damencho** [comment]
> Thanks for the thought you put in this.
> 
> It may seem like a small change, but we have many customers now and we need to be cautious specially with UI/UX changes.

Look at this ^. 

We do not assign tickets, just create a PR or ask is this reasonable to be done.
