### ISSUE TITLE
interface_config.js doesnt applies changes

### ISSUE THREAD

**Issue by nzhtrtlc** [jitsi/jitsi-meet#1422]
Hi, i am trying to edit interface_config.js i removed some buttons from toolbars but its still appears in the conferance screen.

In this file modules/UI/toolbars/Toolbar.js there is a function which is init toolbar from interfaceConfig

`
_initToolbarButtons() {
        interfaceConfig.TOOLBAR_BUTTONS.forEach((value, index) => {
            let place = getToolbarButtonPlace(value);

            if (value && value in defaultToolbarButtons) {
                let button = defaultToolbarButtons[value];
                this._addToolbarButton(
                    button,
                    place,
                    (interfaceConfig.MAIN_TOOLBAR_SPLITTER_INDEX !== undefined
                        && index
                            === interfaceConfig.MAIN_TOOLBAR_SPLITTER_INDEX));
            }
        });
    }
`

I removed microphone from interface_config.js but it still appears.

In my research there is nothing changed in the root files. But i can change react.js source codes.
How to apply changes in interface_config.js ?

note: i'am usign webpack for development server.

**Comment by saghul** [comment]
What option are you editing? You want to change MAIN_TOOLBAR_BUTTONS.

**Comment by nzhtrtlc** [comment]
`
TOOLBAR_BUTTONS: [
        _//main toolbar_
        'microphone', 'camera', 'desktop', 'invite', 'fullscreen', 'hangup',
        _//extended toolbar_
        'profile', 'contacts', 'chat', 'recording', 'etherpad', 'sharedvideo', 'sip', 'dialpad', 'settings', 'raisehand', 'filmstrip']
`

This is orjinal code. I removed **chat** from the list. But it stills appears.
Also i changed index.html i added just a basic `<h1>test</h1>` but it doesnt applies too.

Its look like something overrides my configs.

**Comment by saghul** [comment]
How did you install Jitsi Meet? Where (in the filesystem, that is) are you changing the files?

**Comment by nzhtrtlc** [comment]
I cloned the repo in to my local system then i followed these commands.

> npm install
make
webpack
webpack-dev-server

I used webpack to create an development server.
When i changed react files its okay but when i changed files which is in the root path like interface_config.js or index.html it doesnt appears.

**Comment by saghul** [comment]
When you use webpack-dev-server it will proxy to beta.meet.jit.si and use the file hosted there, maybe? Try serving the files locally for example with Python's builtin HTTP server: `python -m SimpleHTTPServer`

**Comment by nzhtrtlc** [comment]
> nzh@nezih-pc:~/Documents/jitsi-meet-master$ python -m SimpleHTTPServer

Started local server in localhost:8000

When  i visited localhost:8000 there is nothing only white page.
What should i do now ?

**Comment by saghul** [comment]
Any errors in the JS console?

**Comment by nzhtrtlc** [comment]
No, Only this info.

`(TIME) index.html loaded:	 151.85500000000002` (index):9

**Comment by bubomancer** [comment]
I'm facing a similar issue except with app.bundle.js (in /libs), how do I use webpack to properly reflect the changes on the server?

**Comment by nzhtrtlc** [comment]
@bubomancer I think they don't know either.
I installed the repo (you can find in jitsi.org)
now it reflects changes.
If you just clone the github repo then it doesn't reflect your changes.

**Comment by brecke** [comment]
@nzhtrtlc what do you mean you installed the repo? I'm facing the same issue but I can't understand how you overcame it through your last comment.

**Comment by nzhtrtlc** [comment]
@brecke 
I installed jitsi in to ubuntu server running on docker.
Go to https://jitsi.org/Main/InstallJitsiMeetDebianStableRepository
Then follow the steps.

**Comment by nzhtrtlc** [comment]
@brecke I'm not sure thats the reason.

> 
    <script></script>
    <script></script>

When you clone the repo this part of code it loads theese js files from remote server.
Thats why interface_config.js overrides always.
That's my opinion of course.

**Comment by saghul** [comment]
You're correct.

**Comment by mck9** [comment]
Did someone find a solution for this?

**Comment by shubhamsharma4587** [comment]
Any solution?

**Comment by ismael-bernier** [comment]
so, I do not understand solution... Seems to be that the reference is to a remote file instead of the local one that you create when building... odd choice. I can however affect change to the react files... Changed the welcome page and the react/features/base/config/functions.any.js file variable interfaceConfig as follows:


```
    interfaceConfig.DISPLAY_WELCOME_PAGE_CONTENT=false;
    interfaceConfig.SHOW_JITSI_WATERMARK=false;
    interfaceConfig.SHOW_WATERMARK_FOR_GUESTS=false;
    interfaceConfig.PROVIDER_NAME='Planitou';
    interfaceConfig.APP_NAME='Planitou Meet';
    interfaceConfig.DEFAULT_REMOTE_DISPLAY_NAME='User';
    interfaceConfig.TOOLBAR_BUTTONS= [
        'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection', 'hangup', 'profile', 'chat', 'etherpad', 'settings', 'raisehand',
        'videoquality', 'filmstrip', 'feedback', 'stats', 'shortcuts',
        'tileview', 'videobackgroundblur', 'help', 'security'
    ];

    overrideConfigJSON(config, interfaceConfig, loggingConfig, json);

Hope this can help someone else!
