### ISSUE TITLE
Text in start meeting page is not clear

### ISSUE THREAD

**Issue by Febin-Joseph** [jitsi/jitsi-meet#14224]
Hi everyone , here in the start meeting page I personally feel that when The room name is unsafe that the text color is not visible clearly because of the background image like this

![Screenshot 2024-01-12 124800](https://github.com/jitsi/jitsi-meet/assets/128711401/f93d2b0a-0b63-459d-b1a0-fb69dec5507d)

And if the user wanted to see it clearly then they needed to select it or needed to do something like that, so if changing the color of this message to a little dark `The room name is unsafe. Unwanted participants may join your meeting. Consider using a more unique meeting name, or pick one of the suggestions. Learn more about securing you meeting` will be helpfull for everyone can be seen clearly whats written there.

Thank you.

**Comment by richardshaju** [comment]
Can I Work on this?

**Comment by Febin-Joseph** [comment]
Sure @richardshaju you can work on, i think nobody is currently working on the same.

**Comment by P-FardeenMalik** [comment]
Seems no one fixed this issue, so I am working on it.
