### ISSUE TITLE
Where should I ask if I have a question about jitsi meet?

### ISSUE THREAD

**Issue by seonggookang** [jitsi/jitsi-meet#14223]
Where should I ask if I have a question about jitsi meet?
- Do you have a tutorial how to use docker desktop for jitsi meet?
- JSDoc types may be moved to TypeScript types << I can see this warning lots of times. Can I jus tleave it?

**Comment by damencho** [comment]
Use the community forum for questions please, it is already stated in the template of the issues.



> * Do you have a tutorial how to use docker desktop for jitsi meet?

https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker



> * JSDoc types may be moved to TypeScript types << I can see this warning lots of times. Can I jus tleave it?

yes.
