### ISSUE TITLE
Add granular audio controls for shared music in Jitsi Meet

### ISSUE THREAD

**Issue by rasrobo** [jitsi/jitsi-meet#14230]
When sharing audio through Jitsi Meet for background music (e.g. YouTube, Spotify), there is currently no way to finely adjust the volume of the shared audio track within Jitsi. Even at the lowest system volume, shared music can be too loud for background usage during conversations.

**Proposed Enhancement:**

- Add a volume slider for shared audio tracks within the Jitsi interface
- Allow volume to be adjusted in smaller increments, like 5% changes
- Add compressor/limiter effects to prevent clipping and normalize volume
- Allow per-user volume adjustment of shared tracks

**Benefits:**

- Will allow shared music to be adjusted to ideal background volume levels
- Improves use case of sharing background music during conversations
- Volume can be tuned on a per-user basis
- Music sharing can happen seamlessly without disrupting conversations
- Please consider adding more granular volume controls for shared audio tracks like background music in Jitsi Meet. Current volume adjustment options are too coarse for ideal background music usage. More fine-grained controls would greatly improve the user experience.

**Comment by anarute** [comment]
I support this request. The audio sharing feature is awesome but impossible to use if the goal is to share background music during a call.

Even when trying to set the volume of the tab with javascript it seems that Jitsi ignores it and shares the sound with the regular volume.

**Comment by saghul** [comment]
I think this is a nice proposal.

It does need careful UI/UX design since we currently don't have any UI to handle audio sharing.

We currently don't have the cycles to tackle this, just to adjust everyone's expectations here.

**Comment by 1ace** [comment]
@jitsi you really should remove that "stale" bot. In case you are not yet aware of its consequences, you'll want to read up on articles such as:
- https://drewdevault.com/2021/10/26/stalebot.html
- https://blog.benwinding.com/github-stale-bots/

The short version is: by throwing away your users' contributions (especially using an automated script, not even having the decency to let a human decide to do that) you are throwing away your users' incentive and motivation to talk to you and work with you, killing your community and as a result damaging your own product 😉

The solution is simple: remove that bot and shift your mentality to stop thinking that users reporting bugs and wanting features is a bad thing, and accept that some bugs/features requests will stay open for a while before they get fully addressed/resolved.

I really hope you do the right thing here, we all like Jitsi and it would be a shame if you killed it with such a trivially uninformed decision.

**Comment by 1ace** [comment]
@jisti it's ok that you made mistakes (we all do), but please learn from them 🙃

**Comment by saghul** [comment]
The bot shall stay. You are welcome to handle your projects the way you see fit.

What we learn here is that this feature-request is not important enough for anyone to tackle, keeping it open for no reason won't make it magically be implemented.

Hence, I'm closing this. If someone is willing to work on it I'd be happy to review a PR.

**Comment by spookyvision** [comment]
Using stalebot is extremely disrespectful to your users. You're *obviously* free to use it, but that doesn't change it being disrespectful.
