### ISSUE TITLE
Pause / Resume recording feature 

### ISSUE THREAD

**Issue by VirajMadhu** [jitsi/jitsi-meet#14238]
**Is your feature request related to a problem you are facing?**
Yes

**Describe the solution you'd like**
I would like if jitsi have pause / resume recording options as well. (Like zoom meeting. They have that features)

**Comment by saghul** [comment]
Hey there!

We discussed this and decided the complexity of it vs the benefit is too high to tackle it at the moment.

This might change in the future base on customer needs but this is where we stand today.
