### ISSUE TITLE
Unmute doesn't work for random users on mobile

### ISSUE THREAD

**Issue by alexander-potemkin** [jitsi/jitsi-meet#14237]
### Description:

Some users can't unmute during the call, if they muted themselves.
That seems to occur at both iOS and Android.

### Steps to reproduce:

1. Join Jitsi call
2. Mute yourself
3. Try to unmute. Sometimes that won't work.

### Expected behavior:

Unmute to work persistently.

### Actual behavior:

Person can't unmute.

### Server information:

- Jitsi Meet version: 2.0.9164-1
- Operating System: Ubuntu 22.04.3

### Client information:

- Browser / app version: that's happening for quite some time, always on latest version.
- Operating System: iOS, Android.

### Additional information:

I understand that I didn't provide much information, but it's happening with people I have a call and I can't get more information from them for now; please, let me know if there are any directions I shall check extensively.

**Comment by saghul** [comment]
Does this happen for mobile web users or native app users?

**Comment by saghul** [comment]
No follow-up, closing.
