### ISSUE TITLE
Previous video frame stay

### ISSUE THREAD

**Issue by cgri1** [jitsi/jitsi-meet#14235]
### Description:

Previous video frame stay.

### Steps to reproduce:

1. Open camera
2. Close camera
3. Change position of camera
4. open camera

### Expected behavior:

The transition must be smooth.

### Actual behavior:

previous video frame stay

### Server information:

- Jitsi Meet version: Latest version
- Operating System: Mac, Windows

### Client information:

- Browser / app version: Chrome 120
- Operating System: MacOs, Win 10, Win 11

### Additional information:

https://github.com/jitsi/jitsi-meet/assets/39028198/041affed-175a-4786-ae52-51f4368d7e9b

**Comment by saghul** [comment]
I'm not sure we have control over this. When playing back a video stream the browser will have the frames queued up.
