### ISSUE TITLE
Sharing video: Works great for some, nothing happens for one participant, one other has stuttering

### ISSUE THREAD

**Issue by ned64** [jitsi/jitsi-meet#14247]
I use the Jitsi Meet builtin "Share Video" feature which allows everyone to watch a video together. The video is self hosted, server bandwith is excellent.

For me and a few others the video plays perfectly.  One participant (native App on new iPad) has stuttering. For one participant (old iPhone) nothing is happening at all when Share Video is started. In fact, they are not even muted.

Could it be that the video codec is not usable on some devices, or software rendered?

 The video is h264 640x360 25.000fps
 the audio is aac 1ch 32000Hz

in an MP4 container.  Not too demanding I thought.  Why a 2023 iPad cannot show that without stuttering I do not get.

Is there a better or recommended encoding, perhaps one that works on an old iPhone?  Or, can I specify more than one format, one subsampled?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
> Could it be that the video codec is not usable on some devices, or software rendered?
> 
> The video is h264 640x360 25.000fps the audio is aac 1ch 32000Hz
> 
> in an MP4 container. Not too demanding I thought. Why a 2023 iPad cannot show that without stuttering I do not get.

Possible. All jitsi-meet does is open an iframe with the video link a file or youtube video, it is up to the browser to play it.

**Comment by nbeckindy** [comment]
I'm experiencing a similar issue. Specifically it seems to be a problem with the native iOS app, which may indicate some issue with react-native-video.

Some notes when testing this on meet.jit.si (w/app version 23.6.1 build 1700670272):
1. When a participant using a native app shares a video, some browser participants get a video that's frozen, others get a video that plays. The participant sharing the video can't see the video, nor can any other native app participants.
2. The native app participant can't control the video. If they click on the video to access the controls, the video goes into a state where it frantically pauses and unpauses itself. The video for browser participants will either stutter or repeatedly stop and start over. At this point, the native app participant can no longer end the video share. Also, alerts with the message "Video and many others joined the meeting" spam the native app participant doing the share.
3. When a participant using a browser (whether on desktop or mobile) shares a video, native app users get a massively laggy video (like one image every 5 seconds). Other browser participants see the video as normal.
4. This only happens with direct links video links. Sharing YouTube videos works fine.
5. This seems to only happen on iOS devices. It's been reported that Android devices work fine.

Running a locally hosted instance in XCode logs this infinitely.
![image](https://github.com/jitsi/jitsi-meet/assets/9885067/3496f835-8ed5-47d9-8727-f5efa954128c)
It also spams this in the logs:
Participant joined: [URL to shared video]

**Comment by char112233** [comment]
Hello,
I’ve seen this happen when one person’s connection or device struggles with real-time playback. A simple workaround is to download the video first and then share it locally. I’ve used https://dvtik.com/ to grab clean HD files without watermark, and playback becomes much smoother for everyone involved.
