### ISSUE TITLE
App tries to load Gravatar with isableThirPartyRequest enabled

### ISSUE THREAD

**Issue by Corey-Maler** [jitsi/jitsi-meet#14249]
### Description:

We are using self-hosted jitsi meet with JWT authorisation. 

Well, in fact, whole ticket is identical to https://github.com/jitsi/jitsi-meet/issues/9214 (and also https://github.com/jitsi/jitsi-meet/issues/5670 )

But if we check [solution](https://github.com/jitsi/jitsi-meet/pull/9300/files#diff-3549109f22ba23955422c1711dc95e1ac69dc0af31b484f817a80bab3503b351R412)  we see that it checks that config has no keys.

Unfortunately, in some cases it has those two keys now (`error` an `LocationURL`). See screenshot (`temp1` is `getStore()`)

![Screenshot 2024-01-18 at 10 08 27](https://github.com/jitsi/jitsi-meet/assets/8354173/bf1a0f25-737d-40d9-b592-e3a9444f4789)

### Steps to reproduce:

Set disableThirdPartyRequests: true, and check the network inspector during a page reload.

### Expected behavior:

gravatar.com should not be called.

### Actual behavior:

gravatar.com is still being called.

### Server information:

Jitsi-meet 9111

### Additional information:

By some reason it is not always reproducible, I can investigate more If someone would point out where Error and LocationURL comes from.

**Comment by saghul** [comment]
How are you setting the config option? In the URL? As iframe parameters? In your server's config.js?

Did you modify the config after having a meeting with gravatar on?

Try an incognito window so there is no local storage.

**Comment by Corey-Maler** [comment]
This is what is logged with "config override"
![Screenshot 2024-01-19 at 09 17 09](https://github.com/jitsi/jitsi-meet/assets/8354173/468f3d6b-80df-43ba-ae13-c0fb33826983)

We use `@jitsi/react-sdk` and `configOverwrite={configOverwrite}` prop in react. (We also override few configs via config.js). 


But again, don't really understand why in one case when participant joins, there are fields in `features/base/config`, while in another case there are no.

**Comment by Corey-Maler** [comment]
After some digging I found that state is equal to a moment when this https://github.com/jitsi/jitsi-meet/blob/e2a02f4b2165e3a018f8830c458beacfd2e8a9ee/react/features/base/config/reducer.ts#L84 reducer is set, which is result of `CONFIG_WILL_LOAD` action.

And that action is dispatched in [`appNavigate`](https://github.com/jitsi/jitsi-meet/blob/a843406cb099c7cabe78b9908fd35009c9a2dec4/react/features/app/actions.web.ts#L39)

So, feels like app joins conference, then something makes it navigate, but we already received new participants and now in some wrong state when config is almost clear, but we already in the room. Can it be a case? What can make it happen then?

Also I noted that request is sent only for guest, never for moderator (set it JWT).

**Comment by saghul** [comment]
Sorry, I have no idea what you try to say in your last message.

If you set the room name there shouldn't be more than 1 navigation.

Since you are using config overrides, my guess is we are reading the config value too early, before the overrides have been applied.

**Comment by Corey-Maler** [comment]
Sorry, would try to fix myself.

Request to gravatar happens here (at least based on stack trace)
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/participants/middleware.ts#L686C5-L698C6

Issue in my case that when it tries to read from the state, `features/base/config` is not empty, but also does not have overwritten configs yet. Instead it is has fields `error` and `locationUrl`. That looks similar to the reducer here https://github.com/jitsi/jitsi-meet/blob/e2a02f4b2165e3a018f8830c458beacfd2e8a9ee/react/features/base/config/reducer.ts#L84C1-L95C11  which sets those exact fields in that exact state.

And the only place I found where this action is dispatched is https://github.com/jitsi/jitsi-meet/blob/a843406cb099c7cabe78b9908fd35009c9a2dec4/react/features/app/actions.web.ts#L72 (inside `appNavigate`).

So, what I'm tried to say is that seems like in some cases "onParticipantJoinedOrUpdated" can happen during navigation.

**Comment by Corey-Maler** [comment]
I will make a MR in a few minutes.

**Comment by saghul** [comment]
Thank you!
