### ISSUE TITLE
Outgoing audio stops working on network change

### ISSUE THREAD

**Issue by sergey-ovdienko** [jitsi/jitsi-meet#14256]
### Description:

We are experiencing issues with audio in our mobile apps. The audio from some participants disappears and it is confusing to understand if those participants are just silent or there is an issue. Users have to restart the meeting to fix the issue.

It happens randomly, but we were able to found a scenario when it occurs almost always. It is reproduced on the current Jitsi Meet apps form App Store and Google Play, so we believe it's not a misconfiguration on our side.

### Steps to reproduce:

1. Launch Jitsi Meet app downloaded from the App Store or Google Play on 2 separate devices
2. Join to the same room from these 2 devices
3. Change network on one of the devices e.g. switch from Wi-Fi to cellular

### Expected behavior:

Let's say Alice and Bob do the test described above and Bob's network changes.

Alice expects audio to disappear and video to freeze or to go blank, when Bob has connectivity issues. But Alice also expects that after some time it will get restored. Both video and audio.

### Actual behavior:

What actually happens is that video gets restored most of the time, but not the audio. Alice start seeing Bob again but doesn't hear anything. Bob continues to hear and see Alice normally, after new network connection is ready.

So this missing audio is a problem we're trying to fix.

### Client information:

- Browser / app version: latest app from app stores
- Operating System: Android and iOS

### Additional information:

Let me know if you need more details

**Comment by saghul** [comment]
Doh, sorry this one fell through the cracks!

We'd need device logs to see what's happening. Are you able to capture those?

**Comment by sergey-ovdienko** [comment]
Well, we weren't able to gather any meaningful logs.

However, setting the `websocketKeepAlive` config to `5000` (instead of the default `60000`) did improve the situation.

So not an issue for us anymore.

**Comment by KaKi87** [comment]
Hi,

I'm still experiencing this issue : whenever I leave home or go back from outside, my phone switches between 4G and wifi, which leads to my interlocutor not hearing me even though I can hear them.

Since I always forget this bug exists, I have to talk to a brick wall for a while before they start telling me there might be an issue, which is very annoying.

Thank you

**Comment by Ahmad-Mustafaa** [comment]
Hi, 
I have been experience the issue is there any solution yet @sergey-ovdienko or @KaKi87 

Thanks

**Comment by alikaraarslan** [comment]
Add internet control for the device with @react-native-community/netinfo. You can resolve this by unmounting and remounting the relevant JitsiMeeting using the key property value during Wi-Fi, LTE, or VPN transitions. @Ahmad-Mustafaa
