### ISSUE TITLE
ios manual build sdk framework error

### ISSUE THREAD

**Issue by pedrozarin2024** [jitsi/jitsi-meet#14263]
Hi,
After a successful archive, I put a framework to my app but when Jitsi launched in my app I got this error

Invariant Violation: "App" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
Unhandled JS Exception: Invariant Violation: "App" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
FATAL ERROR: RCTFatalException: Unhandled JS Exception: Invariant Violation: "App" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
Unhandled JS Exception: Invariant Violation: "App" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., stack:
<unknown>@33:290
runApplication@146:1613
value@42:3860
<unknown>@42:675
value@42:2510
value@42:646

### Server information:

- Jitsi Meet version: 2.0.9164
- Operating System: mac os 

### Client information:

- Operating System: iOS 17.1

any help will be appreciated.

**Comment by saghul** [comment]
Please try the official CocaPods Pod before venturing into your own build.

**Comment by pedrozarin2024** [comment]
hi @saghul 
cocoa pod works fine

but i need manually build sdk
I have cloned the repo without no changes just build manually but i got this error
can you please help me ?

**Comment by saghul** [comment]
First, take an SDK release tag. They are like this: `ios-sdk-X.Y.Z`. Then, what exact steps did you follow?
