### ISSUE TITLE
Sidebar causes high CPU load when there is screen share

### ISSUE THREAD

**Issue by parfumdaventure** [jitsi/jitsi-meet#14265]
### Description:

When someone shares his screen, the layout changes automatically and a sidebar appears on the right of the screen.
The CPU load on casual computer (i3 laptop) is extremly high (100% load) (I think this is an proper issue but some are already opened on this subject).

When you hide this sidebar, the CPU load is significantly lower (40 - 50% with a i3 laptop).
It's not only because there are less screens displayed : if you change the layout to have "mosaic", the CPU load is lower too. So it seems that the sidebar has a significant and specific effect.

### Steps to reproduce:

1. Open one meeting
2. Someone shares his screen
3. Check your CPU load
4. Close the sidebar
5. Check your CPU load

### Expected behavior:

The expected behavior is that this sidebar uses less CPU load when screen share (example : 40% on i3 laptop)

Another solution (less interesting but easier I think) would be to have an option to hide by default the sidebar when a screen is shared.

### Actual behavior:

The sidebar uses high CPU load when screen share (100% on i3 laptop)

### Server information:

- Jitsi Meet version : v2.0.8319
- Operating System : unknown

### Client information:

- Browser / app version : Edge Version 120.0.2210.144. Also tested with last firefox, last chrome.
- Operating System: Windows 10

### Additional information:

Tested in a large scale organization. Asked other large organization to test that, and the result is the same.

**Comment by saghul** [comment]
I suppose it might be related to the fact that the screen is also rendered on the sidebar, in a small form factor.

@jallamsetty1 / @hristoterezov can you folks PTAL to see if you can repro?

**Comment by parfumdaventure** [comment]
> I suppose it might be related to the fact that the screen is also rendered on the sidebar, in a small form factor.
> 
> @jallamsetty1 / @hristoterezov can you folks PTAL to see if you can repro?

If you're right, it may be interesting to hide the screen of the share screen by default.

**Comment by jallamsetty1** [comment]
@parfumdaventure Have you tested this in a smaller conference? I do not see any noticeable change in the cpu consumption when I hide the side bar with a 4K screenshare on stage. How many thumbnails did you have on the filmstrip when you experienced the issue? Does the same thing happen when you have a video on stage instead of screenshare?

**Comment by parfumdaventure** [comment]
@saghul With the thumbnail view, the problem is not so high, that's why I suspect a specific issue with this sidebar

**Comment by parfumdaventure** [comment]
@jallamsetty1 same issue with smaller conference. What CPU do you have ? We notice this issue with i3 CPU, from i5 to i7 there is no problem. Observed with all the ~6000 i3 laptops of my organization

**Comment by nabahr** [comment]
I believe this is an issue that I have been experiencing for a while now and couldn't figure out.

When someone shares their screen and the participant list on the right side is open, my system becomes almost unusably slow.
After finding this thread and suspecting the sidebar, now when I close the sidebar my system responds normally.
It looks like CPU load is not affected much, but GPU usage goes from ~90-100% down to ~10-40%.

We've been using Jitsi in our office for at least a couple years now and I don't remember this being an issue previously, but I do not know when this problem started for me. I'd say I've noticed it being a real problem for at least the last 2-3 months.
