### ISSUE TITLE
Wait for moderator button is not translated iOS and Android 8.6.x

### ISSUE THREAD

**Issue by gasci** [jitsi/jitsi-meet#14279]
### Description:

"Wait for Moderator" button is not translated according to the device language in both mobile SDKs.

### Steps to reproduce:

1. Change your device language to a language other than English
2. Join a call without being a modertor
3. Wait in the lobby

### Expected behavior:

"Wait for moderator" button should be translated as well.

### Actual behavior:

 You will see that apart from the "Wait for moderator" button everything else is translated to the device language
![photo_2024-01-26_15-08-04](https://github.com/jitsi/jitsi-meet/assets/29505701/97adc563-b671-4df6-8285-ea8f99d10608)

### Server information:

- Jitsi Meet version: latest JaaS, [meet.jit.si](https://meet.jit.si/)

### Client information:

- Browser / app version: Android & iOS (Capacitor) 8.6.x [capacitor-jitsi-meet](https://github.com/calvinckho/capacitor-jitsi-meet?tab=readme-ov-file)
- Operating System: Mac Sonoma 14.1.2

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Translations are community based, you are welcome to translate it in your language:
https://github.com/jitsi/jitsi-meet/blob/06f434e9248b6093df68c639d1cc94fbf79b826c/lang/main.json#L264

More info at:
https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md
