### ISSUE TITLE
Jitsi.meet demo server freezing

### ISSUE THREAD

**Issue by mbcote1111** [jitsi/jitsi-meet#1427]
Hello, 

The Jistsi Meet demo server has been freezing on me. I have tested numerous times on many different devices. After just a few moments the video feed freezes up. Are you experiencing issues with http://meet.jitsi.com/

Thanks,

Matt

**Comment by saghul** [comment]
Hi!

I'm not observing this. What browser and version have you tested?

**Comment by mbcote1111** [comment]
Chrome and Firefox. Also across multiple devices across the country. I have had many people test and they are all having the same issue.

**Comment by mbcote1111** [comment]
I have personally tested on 3 different devices - 2 PCs and 1 iPad. Frozen video about a minute after the meeting starts. Running latest Chrome and Firefox. Have tested on both. Same issues. This is also occurring with my clients as previously mentioned.

**Comment by githubtefo** [comment]
Same for me. I tested with Firefox 52 under Arch Linux, calling another Firefox 52 (Ubuntu), Chrome (Win7) or the Android App.

**Comment by mbcote1111** [comment]
Still experiencing the same issues today. Chrome and Firefox both latest versions.

**Comment by mbcote1111** [comment]
Firefox 46.0.1 is the version I am having issues with. Seems to be working okay with 57.0.2987.110 (64-bit) of Chrome.

**Comment by saghul** [comment]
@mbcote1111 We have not updated the deployment yet. Can you see if beta.meet.jit.si makes it any better? Thanks!

**Comment by mbcote1111** [comment]
beta.meet.jit.si seems to be working fine with Firefox 46.0.1

When are you planning on updating the deployment?

**Comment by mbcote1111** [comment]
It is not working for Chrome (beta.meet.jit.si) though. Neither Microphone or video start or can be enabled.

**Comment by mbcote1111** [comment]
I have continued to test. The beta.meet.jit.si works great for Firefox but **does not** work for Chrome (video and mic are not able to be shared)

meet.jit.si works nicely on **latest version** of Chrome... but freezes as previously mentioned on Firefox.

**Comment by gpolitis** [comment]
@mbcote1111 make sure you use "https" to access beta from Chrome.

We are actively working on fixing the freezes and the bad video quality, apologies for that. Most of the issues are related to the adaptivity work that enables the bridge to adapt to your downlink channel's capacity, but it wasn't ready for production yet and it was prematurely released.

The PR to watch is this one https://github.com/jitsi/jitsi-videobridge/pull/439. Once it gets merged it will be automatically available on beta (but not on meet, that requires a scheduled release on our side).

**Comment by githubtefo** [comment]
It seems to work fine between Firefox 52 (Linux) and Android App/ Firefox 51 (Windows XP) using the beta.meet.jit.si!
Thanks for the efforts to solve the issues, meanwhile Firefox users switch to the beta version.
Jitsi Meet results the best alternative for linux user at this moment for video calling, given Google Hangouts broke in Firefox 52 and Skype (beta) for Linux sucks since Microsoft buy the Company.

**Comment by saghul** [comment]
Thanks for testing and the kind words! ❤️

**Comment by mbcote1111** [comment]
Yes, thank you. Do you know when the next scheduled release will be with the fix? Until then, I will use beta

**Comment by githubtefo** [comment]
Since today Jitsi Meet Beta can't detect the webcam ("your camera doesn't fit with the requirements").

**Comment by damencho** [comment]
Working fine here. Are you using https? Which browser and version are you using?

**Comment by githubtefo** [comment]
Yes, we use https. Firefox 52 under linux in both sides, and both have the issue.

**Comment by mbcote1111** [comment]
I am still using the beta version which seems to work fine. When will the next stable release be complete so I can start using the meet.jit.si again?

**Comment by damencho** [comment]
Well, we updated meet.jit.si few days ago, and version are almost the same. I think we will be pushing new release to meet and next week.

**Comment by githubtefo** [comment]
I can verify that the webcam detection issue only occurs with the built-in laptop webcam and not with an USB-connected Logitech webcam. It doesn't occur with others webrtc services that need access to webcam in Firefox 52. In Chromium the detection works fine. Jitsi Meet and Jisti Meet Beta has the issue since the last update of meet.jit.si few days ago.

**Comment by mbcote1111** [comment]
Thanks for the update. Does the update you released a few days ago fix the issue with the video freezing?

**Comment by mbcote1111** [comment]
Any update here?

**Comment by LVBK** [comment]
how about schedule of stable build version. 
Latest version was released on February 5

**Comment by damencho** [comment]
Its easy to update, the process takes few minutes.
But there are still few issues in the bridge which we work on, we will discuss it this week and try to do a release the following weeks.

**Comment by mbcote1111** [comment]
Do we have an update on this fix?

**Comment by gpolitis** [comment]
We released earlier this week and we believe we've fixed this issue. Could you please give it a try?
