### ISSUE TITLE
HDMI audio output

### ISSUE THREAD

**Issue by testman42** [jitsi/jitsi-meet#14273]
Issue is related to Jitsi Meet Android application.

**Is your feature request related to a problem you are facing?**
I would like to direct caller's voice to my headphones, which are physically pluggeed into a monitor, which is connected to the phone through HDMI.

**Describe the solution you'd like**
Option for HDMI audio present in the output selection list, which appears when you tap on sound speaker icon at the top right side of the screen.

**Describe alternatives you've considered**
Holding phone next to my ear lol.

**Comment by saghul** [comment]
Lol looks like I made a PR... 2 years ago! https://github.com/jitsi/jitsi-meet/pull/10168 will merge that today.

**Comment by testman42** [comment]
wow, thank you :+1: 
now that I think about it, technically, I think that the connection between android phone and the USB dock is DisplayPort. But then dock has HDMI port, so connection from dock to the monitor is HDMI.
But you get the point, it would be nice to have connected devices that have speakers be listed as well.
