### ISSUE TITLE
iOS SDK 8.6.x - camera in use indicator remains on after "End Meeting For All"

### ISSUE THREAD

**Issue by bmt2018** [jitsi/jitsi-meet#14278]
### Description:

I’m using the latest iOS SDK (v8.6.3) in my iOS app. Our server is configured such that everyone in the call is a moderator. When I’m connected to a call, I see the green dot in the iPhone’s status bar indicating that the camera is in use as expected. When I leave the call, if I use the “Leave Meeting” button, I see the view controller get deinitialized and the green dot in the status bar disappears. But if I use the “End Meeting For All” button, the stream still ends and the view controller’s deinit method is still called but the green dot in the status bar stays on until I force quit the app. Checking the control center confirms that it is, in fact, my app that is still using the camera.

I noticed some differences in the Xcode debugger output when using "Leave Meeting" vs "End Meeting For All", as well.  Here's the output for "Leave Meeting":

```
[JitsiMeetSDK] [features/app] appNavigate to undefined
[JitsiMeetSDK] [features/full-screen] Setting full-screen mode: false
[JitsiMeetSDK] [JitsiMeetJS.ts] This appears to be react-native, ver: 0.69.12
[JitsiMeetSDK] [modules/statistics/statistics.js] Cannot initialize WatchRTC in a react native environment!
[JitsiMeetSDK] [modules/RTC/RTCUtils.js] Disable AP: false
[JitsiMeetSDK] [modules/RTC/RTCUtils.js] Stereo: false
[JitsiMeetSDK] [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
[JitsiMeetSDK] [features/base/lib-jitsi-meet] lib-jitsi-meet version:93c167d3
[JitsiMeetSDK] [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
[JitsiMeetSDK] [features/analytics] Initialized 0 analytics handlers
[JitsiMeetSDK] [features/base/media] Start muted:
[JitsiMeetSDK] [features/base/media] Start audio only set to false
[JitsiMeetSDK] [VideoCaptureController] Capture will stop
[JitsiMeetSDK] [modules/RTC/RTCUtils.js] Available devices:  [ { groupId: '',
    facing: 'environment',
    deviceId: 'com.apple.avfoundation.avcapturedevice.built-in_video:0',
    label: 'Back Camera',
    kind: 'videoinput' },
  { groupId: '',
    facing: 'front',
    deviceId: 'com.apple.avfoundation.avcapturedevice.built-in_video:1',
    label: 'Front Camera',
    kind: 'videoinput' },
  { groupId: '',
    deviceId: 'com.apple.avfoundation.avcapturedevice.built-in_audio:0',
    label: 'iPhone Microphone',
    kind: 'audioinput' } ]
[JitsiMeetSDK] [modules/xmpp/xmpp.js] (TIME) Strophe disconnecting:	 123049281.578541
[JitsiMeetSDK] [VideoCaptureController] Capture stopped
[JitsiMeetSDK] [AudioMode] Route changed, reason: 3
[JitsiMeetSDK] [modules/xmpp/strophe.ping.js] Ping interval cleared
[JitsiMeetSDK] [modules/xmpp/xmpp.js] (TIME) Strophe disconnected:	 123049326.75275
[application] JitsiViewController is being deinitialized
[JitsiMeetSDK] [features/base/sounds] PLAY_SOUND: no sound found for id: PARTICIPANT_LEFT_SOUND
[JitsiMeetSDK] [features/base/redux] redux state persisted. 02e58a302d052d6d7271ffaa636a4ac0 -> 5eea549a015d52a089dd2e45d7713d42

```
And here's the output after using "End Meeting For All":

```
[JitsiMeetSDK] [features/full-screen] Setting full-screen mode: false
[JitsiMeetSDK] [AudioMode] Route changed, reason: 3
[application] JitsiStreamingViewController is being deinitialized
[JitsiMeetSDK] [features/base/sounds] PLAY_SOUND: no sound found for id: PARTICIPANT_LEFT_SOUND

```
### Steps to reproduce:

1. Connect to a meeting (as a moderator)
2. Note that the green dot in the iPhone status bar is on while the camera is in use
3. End the meeting using the "End Meeting For All" button and note that the green dot in the iPhone status bar remains on until you switch away from the app or force quit it

### Expected behavior:

The green dot "camera in use" indicator in the iPhone status bar area should disappear when ending the meeting (as it does when you leave the meeting using the "Leave Meeting" button).

### Actual behavior:

The green dot "camera in use" indicator in the iPhone status bar area remains on after ending a meeting using the "End Meeting For All" button

### Server information:

- Jitsi Meet version: stable-9111 (Docker)

### Client information:

- Jitsi iOS SDK version: 8.6.3
- Operating System: iOS 16 and iOS 17

**Comment by saghul** [comment]
@Calinteodor PTAL, looks like we are leaving too abruptly without properly closing the local tracks.

**Comment by Calinteodor** [comment]
So I managed to test with our native sdk tester app

https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/ios/swift/JitsiSDKTest

and I am not able to repro this issue.
If the mobile moderator ends the meeting for all the green indicator on the left side disappears and the participants are sent out of that conference.
Same goes for when the web moderator ends the meeting.

I used SDK 8.6.3 for this test.

**Comment by saghul** [comment]
> [application] JitsiViewController is being deinitialized

When are you doing this? On what delegate method?

**Comment by bmt2018** [comment]
It was just logging in the view controllers deinit method that was left over from what I was troubleshooting what I thought was a retain cycle.  There's nothing else in the deinit method other than that log statement.

**Comment by saghul** [comment]
can you share your controller code please?

**Comment by bmt2018** [comment]
Doh!  I think I figured out what is happening.


```
extension JitsiStreamingViewController: JitsiMeetViewDelegate {
    
    func conferenceTerminated(_ data: [AnyHashable : Any]!) {
        presentingViewController?.dismiss(animated: false, completion: nil)
    }
}

```

As you can see, in the `conferenceTerminated(_:)` delegate method, my code was dismissing the VC.  I never encountered an issue with this code when using "Leave Meeting" but maybe I was just lucky with the timing there.  When I use "End Meeting For All", I noticed that the "camera/mic in use" indicator in the status bar would remain on.  It stands to reason that "End Meeting For All" could take longer to complete but my code was dismissing the VC before all of the clean up was fully completed.

In looking through the JitsiMeetViewDelegate delegate methods, I saw `ready(toClose:)` and when I comment out the dismiss call in `conferenceTerminated(_:)` and implement it in `ready(toClose:)`, that seems to get called when I tap on the 'OK' button in the 'The meeting has been terminated' alert.  So I think this was basically my own fault for dismissing the VC too early in the wrong delegate method.  Thank you both for looking at this and I apologize for having wasting your time!  :-(

**Comment by bmt2018** [comment]
On a related note, if my assumption about the `ready(toClose:)` delegate method being called when the user taps on the 'The meeting has been terminated' alert is correct, is there a way to suppress that alert and just have the delegate method be called as soon as cleanup is complete so that the user doesn't have to interact with the UI to dismiss the VC?

**Comment by saghul** [comment]
I'm glad we figured it out!
