### ISSUE TITLE
Android: Jitsi Meet app saves JWT authenticated meetings without token

### ISSUE THREAD

**Issue by muks** [jitsi/jitsi-meet#14276]
### Description:

When a meeting attendee is authenticated using a JWT meeting, all goes well. After the meeting is complete, the attendee can see that the meeting has been saved in the history under "Earlier" on the "Recent" page.

However, the JWT token in the URL is not saved, and so the attendee cannot click the list item and join the meeting again. In any case, as JWT tokens are time-bound and typically launched from external applications, it may be better not to save JWT token authenticated meetings in the "Recent" history at all.

### Steps to reproduce:

1. Attend a JWT token authenticated meeting in the Jitsi Meet Android app
2. Leave the meeting
3. Try to re-join the meeting from the "Recent" page

### Expected behavior:

- The attendee should be able to join the meeting, or
- The meeting should not be saved in the "Recent" page.

### Actual behavior:

- The meeting is saved in the "Recent" page without the JWT token
- The attendee is not able to re-join the meeting by clicking the saved meeting in the "Recent" page, as it is missing the JWT token

### Server information:

```
ii  jitsi-meet                      2.0.9164-1                     all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.7712-1                     all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-tokens               1.0.7712-1                     all          Prosody token authentication plugin for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.7712-1                     all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.7712-1                     all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.7712-1                     all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.3-64-g719465d1-1             all          WebRTC compatible Selective Forwarding Unit (SFU)
```
### Client information:

- Browser / app version: Android app 23.6.1
- Operating System: Android 14

### Additional information:

It would be best not to save JWT token authenticated meetings in the "Recent" page at all as the JWT token is time-bound (`exp` and `nbf` claims).

**Comment by saghul** [comment]
> However, the JWT token in the URL is not saved, and so the attendee cannot click the list item and join the meeting again. In any case, as JWT tokens are time-bound and typically launched from external applications,

This is exactly why we strip the token when saving the URL in history.

> it may be better not to save JWT token authenticated meetings in the "Recent" history at all.

If your deployment uses a URL for token auth you'll be redirected again, grab a token and join no problem. This is, for example, how meet.jit.si works.

I think adding an option to not store the URL altogether iff it has a token and the config we loaded has no token auth URL would be accetable. Are you willing to send a PR?

**Comment by muks** [comment]
> If your deployment uses a URL for token auth you'll be redirected again, grab a token and join no problem. This is, for example, how meet.jit.si works.

If you mean the `tokenAuthUrl` field in the `config.js` file, I don't know if this scheme would work with the kind of meetings manager webapp we use. In this webapp, each attendee's meeting invitation page has its own unique URL (`https://lobby.<domain>/<uuid>`) in which an attendee clicks the meeting URL (`https://meet.<domain>/<room>?jwt=<jwt>`) to join the meeting. There's no single meeting manager `tokenAuthUrl` where attendees could authenticate and then visit the meeting URL. Attendees may consist of the general public; the `https://lobby.<domain>/<uuid>` invitation page grants them access.

> I think adding an option to not store the URL altogether iff it has a token and the config we loaded has no token auth URL would be accetable.

- Add a field in the signed JWT instructing to not save the meeting in history?
- Pass a meeting-specific `tokenAuthUrl` as a field in the signed JWT token (e.g., containing the meeting manager invitation link `https://lobby.<domain>/<uuid>` ) to be used in "Recent" history page? This could take the attendee back to the unique meeting invitation page specific to each attendee.

> Are you willing to send a PR?

I've never tried building Jitsi Meet or even have an idea of what repositories would be involved for such a change. I can try, but don't hold it against me if I fail to come up with  a patch.

**Comment by saghul** [comment]
> * Add a field in the signed JWT instructing to not save the meeting in history?

I think this is a good idea.
