### ISSUE TITLE
Cannot start a Jitsi React app on Iphone in any browser neither in mobile/desktop mode

### ISSUE THREAD

**Issue by zioalex** [jitsi/jitsi-meet#14283]
### Description:

I wrote a simple ReactApp to connect to jitsi and do some other commands:

The code I use is:
```  
<JitsiMeeting
                domain={jitsiDomain}
                roomName={generateRoomName()}
                spinner={renderSpinner}
                jwt={process.env.REACT_APP_JWT}
                configOverwrite={{
                    subject: '{process.env.REACT_APP_LANG}',
                    hideConferenceSubject: false
                }}
                onApiReady={handleApiReady}
                onReadyToClose={handleReadyToClose}
                getIFrameRef={handleJitsiIFrameRef1} 
            />
```

This code works correctly on a desktop computer and on an Android phone browser in desktop mode.
Accessing the same webapp from an Iphone produce the black screen image saying:
```
How do you join this meeting?.

Join in app

it looks like you're using a browser we don't support
...
```

I got the same result in Chrome, Firefox and Safari in both mobile and desktop mode.
### Steps to reproduce:

1.  open the webapp 10.0.0.2:3000
2. Check if the app join the meeting
3. Switch to desktop mode 

### Expected behavior:
The app join the meeting:
![Screenshot from 2024-01-26 22-28-35](https://github.com/jitsi/jitsi-meet/assets/3593840/9a37a263-ce47-4519-8c1e-50f756ef4e6c)

### Actual behavior:

The app doesn't join the meeting and I get this message
```
How do you join this meeting?.

Join in app

it looks like you're using a browser we don't support
...
```
### Server information:

- Jitsi Meet version:
ii  jitsi-meet                            2.0.8960-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                    1.0.7531-1                              all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-tokens                     1.0.7712-1                              all          Prosody token authentication plugin for Jitsi Meet
ii  jitsi-meet-turnserver                 1.0.7531-1                              all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                        1.0.7531-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.7531-1                              all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                    2.3-44-g8983b11f-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)

- Operating System:
Ubuntu 22.04.3 LTS (Jammy Jellyfish)" on Raspberry 4
### Client information:

- Browser / app version: Chrome/ Firefox / Safari the latest available
- Operating System:  Iphone iOS 16.7.2

### Additional information:
On Android phone works with the Browser in Desktop mode.

From the Iphone I can connect to the jitsi server via the normal web access:
![image](https://github.com/jitsi/jitsi-meet/assets/3593840/f942fa92-da40-438e-b4b5-09eec8753208)

The working user-agent in desktop mode is: 
"Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"

While the failing from Iphone is:
"Mozilla/5.0 (iPhone; CPU iPhone OS 16_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/121.0.6167.66 Mobile/15E148 Safari/604.1"

I tried to customize the app presented by the React App with
```
     useEffect(() => {
         Object.defineProperty(navigator, 'userAgent', {
           get: function () { "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"; }
         });
       }, []);
      // "Mozilla/5.0 (Android 13; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0" - Android mobile
      // Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0 - Android desktop mode
```
But if fails in every case from Iphone.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

That was fixed at some point, you should update.

**Comment by zioalex** [comment]
Can you point me to the thread? Didn't find it.
From which version was it fixed?

**Comment by zioalex** [comment]
@damencho  ^^^ thank you

**Comment by zioalex** [comment]
See https://community.jitsi.org/t/react-sdk-app-on-iphone-doesnt-work/129551 for a resolution.
