### ISSUE TITLE
iOS CallKit UI: Initial subject Replaced by Room Name

### ISSUE THREAD

**Issue by AlanHilal** [jitsi/jitsi-meet#14281]
### Description:

Subject is initially displayed on the CallKit UI when set. However, it is subsequently replaced by the room name.

### Steps to reproduce:

1. Start a meeting and give it a subject name.
2. Check CallKit UI. for a brief moment and then replaced by room name.

### Expected behavior:

The subject should be shown not room name.

### Actual behavior:

<img src="https://github.com/jitsi/jitsi-meet/assets/8134301/bd94ff66-cb9a-4ee6-90d9-fdce623abe0c" width="300">
<img src="https://github.com/jitsi/jitsi-meet/assets/8134301/7cbaf063-8995-4709-9f04-8296208dde1a" width="300">

### Client information:

- SDK version: 8.6.3 
- Operating System: IOS

**Comment by saghul** [comment]
> 1. Start a meeting and give it a subject name.

How are you setting it?

**Comment by AlanHilal** [comment]
> > 1. Start a meeting and give it a subject name.
> 
> How are you setting it?

By setting subject property in jitsiMeetView options.

```
  jitsiMeetView.delegate = self;

  JitsiMeetConferenceOptions *options = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
      ...
      builder.subject = @"Groups!";
     ...
  }];

  [jitsiMeetView join:options];
```

**Comment by saghul** [comment]
We'll take a look, thanks!

**Comment by AlanHilal** [comment]
I tried to fix it and open PR but I run into some problem building the SDK.
I will share my findings here.

`callUpdate` is called three times in `react/features/mobile/call-integration/middleware.ts` on line `283`, `425` and `490`.
in the first call `displayName` is passed but in the other two not.
I think the problem could be solved by passing the displayName for other two calls or not setting `localizedCallerName` in `ios/sdk/src/callkit/JMCallKitProxy.m` on line `275` when the displayName is not passed.

**Comment by saghul** [comment]
@Calinteodor this is what you fixed yesterday, right?

**Comment by Calinteodor** [comment]
@saghul tested and fixed. Will be available in the next release.
