### ISSUE TITLE
2.0.9220-1 does not work if org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS is not set

### ISSUE THREAD

**Issue by slesru** [jitsi/jitsi-meet#14287]
Hello! 

After upgrade to latest stable jitsi meet I hit error:

2024-01-29 09:24:31.945 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000735S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)

client's can connect.

so I set org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=myserverip

Now looks like it works.

But server is in local network and have no nat .

Previous several versions worked...

Server is Ubuntu 22.04.

**Comment by slesru** [comment]
btw, unfortunately,   org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS  does not always help,
I had to restore VM from backup...

**Comment by slesru** [comment]
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS  is not set

Here is jvb.log:
2024-01-29 14:16:52.944 WARNING: [1] ColibriWebSocketService.<init>#51: Websockets enabled, but no domains specified: URLs=[wss://meet.server:443/colibri-ws/default-id], Relay URLs=[]
2024-01-29 14:16:54.272 WARNING: [1] org.glassfish.jersey.server.wadl.WadlFeature.configure: JAXBContext implementation could not be found. WADL feature is disabled.
2024-01-29 14:16:54.472 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Health registered in SERVER runtime does not implement any
 provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Health will be ignored.
2024-01-29 14:16:54.473 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Version registered in SERVER runtime does not implement an
y provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Version will be ignored.
2024-01-29 14:16:54.473 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.prometheus.Prometheus registered in SERVER runtime does no
t implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.prometheus.Prometheus will be ignored.
2024-01-29 14:17:52.466 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.00092S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP ad
dresses available for harvesting.)


And here is jicofo.log:
янв. 29, 2024 2:16:53 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Discovered components: [Component(type=speakerstats, address=speakerstats.meet.server), Component(type=conference_duration, address=conferenceduration.meet.server)]
янв. 29, 2024 2:16:54 PM org.glassfish.jersey.server.wadl.WadlFeature configure
WARNING: JAXBContext implementation could not be found. WADL feature is disabled.
янв. 29, 2024 2:16:54 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider org.jitsi.rest.Version registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems
the provider org.jitsi.rest.Version will be ignored.
янв. 29, 2024 2:16:54 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider org.jitsi.rest.prometheus.Prometheus registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configura
tion problems the provider org.jitsi.rest.prometheus.Prometheus will be ignored.
янв. 29, 2024 2:16:54 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider org.jitsi.jicofo.rest.ConferenceRequest registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint config
uration problems the provider org.jitsi.jicofo.rest.ConferenceRequest will be ignored.
янв. 29, 2024 2:17:57 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Health check failed for: Bridge[jid=jvbbrewery@internal.auth.meet.server/4eba223a-6370-41b9-959b-64d890f8a42f, version=2.3.67-gb2d4229f, relayId=null, region=null, stress=0,00]:
 <error xmlns='jabber:client' type='cancel'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en'>No valid IP addresses available for harvesting.</text></er
ror>
янв. 29, 2024 2:18:06 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: There are no operational bridges.
янв. 29, 2024 2:18:06 PM org.jitsi.utils.logging2.LoggerImpl log
SEVERE: Can not invite participant, no bridge available.
янв. 29, 2024 2:18:06 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: There are no operational bridges.
янв. 29, 2024 2:18:06 PM org.jitsi.utils.logging2.LoggerImpl log
SEVERE: Can not invite participant, no bridge available.
янв. 29, 2024 2:18:06 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Can not remove 64bba0ad, no participantInfo
янв. 29, 2024 2:18:07 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Can not remove ddfe5c83, no participantInfo


I have another server which is behind NAT as has 
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS
and I can't reproduce problem there.

about STUN- this server has no public address and have no internet access.
I have 
#org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES
i.e. commented

**Comment by slesru** [comment]
btw, STUN is disabled on server which is behind NAT too.

anyway, if I set 
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS

to just local interface address I can't reproduce this, but don't shure it works, just because if I set only
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS
I can't reproduce this too, but users can.

**Comment by saghul** [comment]
Aah right. Not sure what changed there, maybe @bgrozev knows?

If your server is not exposed to the internet, you shouldn't need to set anything... Can you please share your full config?

**Comment by slesru** [comment]
btw,
2.0.9164-1
is previous version which just works

**Comment by saghul** [comment]
Can you edit your jvb.conf file and set this option to false? https://github.com/jitsi/jitsi-videobridge/blob/573abcdf4c7b3f17493d30550811ad7a8fd27a64/jvb/src/main/resources/reference.conf#L27

I suspect it was this commit: https://github.com/jitsi/jitsi-videobridge/commit/e41cad1e476efef0cd0efae1b44b80cb7f432b03

**Comment by slesru** [comment]
Thank you!
Looks like this helps, at least I can't reproduce this.
Waiting for user's complains if any ;-)

**Comment by bgrozev** [comment]
Yes, that's the expected behavior if the server is not exposed to the internet, and setting `require-valid-address = false` is the intended solution. I'm sorry for the braking change.

**Comment by saghul** [comment]
Good to know!

**Comment by ravench** [comment]
Is there a central documentation somewhere on running jitsi internally? Just spent an hour figuring this out..

**Comment by saghul** [comment]
Alas no. @bgrozev I added some docs on that to the handbook but they are Docker specific (need to add this one too). We need to document this somewhere.

**Comment by DirkFries** [comment]
Just ran into the same issue on 2.0.9220-1 on Ubuntu 22.04 and I tried to set "require-valid-address = false" in jvb.conf, but in my case.

Instead I got this error messsage in the logfile:

`JVB 2024-02-27 08:35:59.456 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Health registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Health will be ignored. `

This is my jvb.conf:

`
videobridge {

        health {
        require-valid-address = false
        interval = 1 minute
        timeout = 90 seconds
        max-check-duration = 3 seconds
        sticky-failures = false
        require-stun = false
    }

    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "meet.host.tld:443"
        tls = true
    }
    apis: {
      rest: {
        enabled: true
      }
    }
}
`
Does anyone have a hint why jvb still fails ?

**Comment by saghul** [comment]
That warning is harmless, please share the full log.

**Comment by saghul** [comment]
> JVB 2024-02-27 08:35:58.199 SEVERE: [12] org.ice4j.ice.harvest.MappingCandidateHarvesters.createStunHarvesters: Failed to parse STUN server address:
> JVB 2024-02-27 08:35:58.215 WARNING: [12] org.ice4j.ice.harvest.MappingCandidateHarvesters.createStunHarvesters: STUN mapping harvesters are configured, but no allowed local addresses were found. Not using STUN.

I think the problem here is STUN is not enabled and there is no local / public IP pair set, so there is nothing the JVB can offer.

**Comment by bgrozev** [comment]
I see sip-communicator.properties is loaded. It probably contains an empty STUN server address. Suggest migrating everything to jvb.conf

**Comment by ara-mark** [comment]
for anyone stumbling upon the same issue, setting `**videobridge.health.require-valid-address = false;**` resolved my issue.
For me sessions crashed after 30 seconds due to health check even  though publicAddress and localAddress were set.

Reference: https://github.com/jitsi/jitsi-videobridge/pull/2077
