### ISSUE TITLE
Audio and video not working in my sdk react native

### ISSUE THREAD

**Issue by Amanhak** [jitsi/jitsi-meet#14295]
Here in the video you can see a vc call started on mobile app and web . You can see in video chat is working fine from mobile to web and vice versa. but you can see even we have camera on and mic on in web it is reflecting as both are close on mobile app and viceversa. This is the main issue I hope this [[video](https://drive.google.com/file/d/1wtVP6EKVDSsn-glYGlcrt-3b5_vvlaxy/view?usp=sharing)] explains whats I am facing.

**Comment by Amanhak** [comment]
And it is working for 3 user in backend and also on web side on different network.

**Comment by RohanChauhan472y** [comment]
Hey Aman,did your issue solved?
I am also getting same issue.
