### ISSUE TITLE
Missing live stream and share doc from extended toolbar

### ISSUE THREAD

**Issue by Radnik** [jitsi/jitsi-meet#1429]
Hi,

All works fine audio, video, connections....etc.

Though, we are missing "Start / Stop live stream" and Open / Close shared document" icons.
Am I missing some additional packages?

Installation was done as "quick install" against ubuntu server 16.10.

thanks,
Ivan

**Comment by damencho** [comment]
Please when having questions or problem use the mailinglist before opening issues.

For live streaming you need to install and configure https://github.com/jitsi/jibri with your system, which is not a trivial work. And then enable it in your jitsi-meet instance, with config props enableRecording and recordingType (like enableRecording: true, recordingType: 'jibri',).

About sharing a document, you need to install etherpad and configure jitsi-meet to use it using config property: etherpad_base (like etherpad_base: 'https://jitsi-meet-example/etherpad/p/',)
