### ISSUE TITLE
How to create connect websocket in meeting chat online in jitsimeet room ?

### ISSUE THREAD

**Issue by khaimp** [jitsi/jitsi-meet#14292]
Hi everybody!

I need a solution for Jitsi Meet web. Specifically, I am working on ChatInput.tsx, where I want to establish a WebSocket connection with my WebSocket server. I have successfully connected my WebSocket server in a standalone web application. However, when I try to override the connection logic in ChatInput.tsx within the Jitsi Meet environment, it doesn't connect during a video call meeting.
I am using stompjs and sockjs-client. The connection function in the constructor is the same:
![Capture](https://github.com/jitsi/jitsi-meet/assets/108779587/9c0e3077-9088-49bd-9134-1cbc7cb43685)
But it's not working, and I encounter an error when running and trying to chat in a room during an online meeting. The console shows the following error:
![Capture1](https://github.com/jitsi/jitsi-meet/assets/108779587/66ac4f53-fdb1-4850-a101-e651df5d6cf3)

**Comment by saghul** [comment]
Please use our community forum to ask such questions. This is not really about Jitsi Meet, your changes seem to be incorrect / incomplete.

**Comment by khaimp** [comment]
> Please use our community forum to ask such questions. This is not really about Jitsi Meet, your changes seem to be incorrect / incomplete.

what do you mean ?

**Comment by saghul** [comment]
https://community.jitsi.org/
