### ISSUE TITLE
Camera is not working even all the permissions are given 

### ISSUE THREAD

**Issue by Jagroop-RTE** [jitsi/jitsi-meet#14293]
I am getting below error :
`2024-01-29T12:01:06.743Z [features/base/tracks] Failed to create local tracks [‘video’] DOMException: Permission denied`

Even when I ovewite config and allow permission.
If I use the same code in codepen then it is working correctly but when we integrate this in our site it not working even permission is given.

How we can solve that @saghul  ? I also try to find other resources on internet but didn't found any relevant result ?

**Comment by saghul** [comment]
Please provide some details about your environment. What browser are you using, how are you integrating Jitsi Meet, etc.

**Comment by Jagroop-RTE** [comment]
Here is the sample of config overwrite : 
```
const chooseConfigObjects = (computerAudioEnabled, startSilentMeeting) => {
		// Interface Config Overwrite
		const interFaceConfigOverwriteObject = {
			SHOW_PROMOTIONAL_CLOSE_PAGE: false,
			DISABLE_JOIN_LEAVE_NOTIFICATIONS: true,
		}
		// Config Overwrite
		const configOverWriteObject = {
			startScreenSharing: false,
			startWithAudioMuted: computerAudioEnabled,
			startWithVideoMuted: false,
			startSilent: startSilentMeeting,
			notifications: [
				'recording.busy', // shown when recording service is busy
				'recording.failedToStart', // shown when recording fails to start
				'recording.unavailableTitle', // shown when recording service is not reachable
				'dialog.serviceUnavailable', // shown when server is not reachable
				'dialog.sessTerminated', // shown when there is a failed conference session
				'connection.CONNFAIL', // shown when the connection fails,
				'dialog.micNotSendingData', // shown when user's mic is not sending any audio
				'toolbar.noAudioSignalTitle', // shown when a broken mic is detected
				'toolbar.noisyAudioInputTitle', // shown when noise is detected for the current microphone],
				'notify.startSilentTitle', // shown when user joined with no audio
			],
			toolbarButtons: ['microphone', 'fullscreen', 'fodeviceselection', 'profile', 'desktop'],
			disableDeepLinking: true,
		}

		return { interFaceConfigOverwriteObject, configOverWriteObject }
	}
```

**Method Used :** iFrame Integration 

Here we interated iframe : 
`<div id={props.jitsiContainerId} />`

Issue occured in every browser  ( web and mobile).

**Jitisi error Logger :**

2024-01-29T06:17:39.975Z [conference.js] Video track creation failed with error gum.permission_denied: User denied permission to use device(s): video


name: 'gum.permission_denied', message: 'User denied permission to use device(s): video', stack: 'Error\n    at new Gt ([https://getgeeker.com/libs/li…er.com/libs/lib-jitsi-meet.min.js?v=7322:2:595908'}](https://getgeeker.com/libs/li%E2%80%A6er.com/libs/lib-jitsi-meet.min.js?v=7322:2:595908%27%7D)


fs.js:4 2024-01-29T06:17:42.555Z [features/base/conference] Error while requesting wake lock for screen: NotAllowedError: Failed to execute 'request' on 'WakeLock': Access to Screen Wake Lock features is disallowed by permissions policy

**Comment by saghul** [comment]
Was your site loaded over https?

**Comment by Jagroop-RTE** [comment]
> Was your site loaded over https?

yes

**Comment by saghul** [comment]
Is your site publicly accessible? Without being able to test I don't know what else you could test... oh right, does it work in incognito mode?

**Comment by Jagroop-RTE** [comment]
> Is your site publicly accessible? Without being able to test I don't know what else you could test... oh right, does it work in incognito mode?

No not even in incognito window it's not working. But same code is working in the codepen.
Do we have to give access to jitsi from our frontend server or something ?

**Comment by saghul** [comment]
No, im asking if there is a way for me to test it.

**Comment by Jagroop-RTE** [comment]
Yes, @saghul , it's publicly accessible but for that credentials are required.

**Comment by Jagroop-RTE** [comment]
Also in iframe it shows : 
allow=**camera ‘none’;** microphone; display-capture; autoplay; clipboard-write

**Comment by saghul** [comment]
That like is wrong and might explain what's going on.

Where are you sourcing external_api.js from?

**Comment by Jagroop-RTE** [comment]
Hi @saghul , we are hosted the jitsi .
**Also it's version is :** jitsi-meet     2.0.8719-1 

Also we have generated the same case in codesandbox, actually if we directly add this in index.js file then it will work but for child component it start producing same issue : 
**Here is the codesandbox link :**https://codesandbox.io/p/sandbox/react-jitsi-demo-forked-vx6fp5 ( will be removed in future)

**Comment by saghul** [comment]
I'll try to take a look tomorrow.

**Comment by saghul** [comment]
<img width="2004" alt="Screen Shot 2024-02-01 at 11 59 20" src="https://github.com/jitsi/jitsi-meet/assets/317464/c4f5d7a9-64ef-42a2-9090-0928341e8a6e">

Your deployment works ok.

The problem I see is that codesandbox runs your code in an iframe and then in turn our external API uses another iframe, and permissions are not delegated correctly.

If you test this using a standalone html page on a server is will just work.

**Comment by Jagroop-RTE** [comment]
Yes , exactly.
Is there any way to solve this.

**Comment by saghul** [comment]
Not without permission delegation from the 1st iframe (the allow= directive) which you have no control over in codepen, AFAIK.

I'm closing this since there is nothing actionable on the Jitsi Meet side of things.

**Comment by Jagroop-RTE** [comment]
**Solved :** 
Add this script in index.html file : 
`<script src="https://meet.jit.si/external_api.js"></script>`

Thanks @saghul , for giving hint

**Comment by gabrielcayres1** [comment]
Hi, tks for solution, but it´s necessary to indicates de custom URL, if is your case. 

`<script src='https://<your-domain>/external_api.js'></script>`
