### ISSUE TITLE
How to setup a language after the package installation?

### ISSUE THREAD

**Issue by tangmeng09** [jitsi/jitsi-meet#1430]
I setup jitsi-meet on a debian host by the quick-install method. The bundled languages do not have my preferred language. I tried to create 2 new json files in the lang directory. Of course, they are not working. After I read the readme.md, I go to your translation project website. But can not find any document about the language setup. 
I notice the latest jitsi-meet code has more languages, such as language_zhCN.json and main_zhCN.json. But the string translations in the files are empty. The translation project website only have .po files to download. 
How can I install the language files?

**Comment by damencho** [comment]
Please when having questions or problem use the mailinglist before opening issues.

Adding new languages cannot be done after deployment if you do not want to edit minified js files. Adding new language is done in this file: https://github.com/jitsi/jitsi-meet/blob/master/lang/languages.json and then you need to make jitsi-meet, eventually if you want create debian package.
If you see the languages in the source and do not see it in deployment I suspect you have installed stable, while the new languages are in testing or nightlies, so you can update to those to see the languages. 
If something is missing translation you can login to translate.jitsi.org and contribute with translation and some of the devs will commit those translation to the source code. If you finish a translation you can ping us on the mailinglist to push it to master.
