### ISSUE TITLE
another option to start broadcasting

### ISSUE THREAD

**Issue by wanghaisheng** [jitsi/jitsi-meet#14304]
**Is your feature request related to a problem you are facing?**
![image](https://github.com/jitsi/jitsi-meet/assets/2363295/5619d115-51d9-4ce3-b8c3-d8ba7ea7c12e)

**Describe the solution you'd like**
OBS is  a popular live streaming tools.
can we provide a link or something that we can copy to OBS and other tools  instead of the default option to youtube livestream

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by wanghaisheng** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/2363295/c091683d-c50a-4fe5-ac56-f6dca5d8bfd1)
@saghul   where can I entry a rtmp url.. I can not find this 

yes we use obs   push to diff destinations

I think we should give user a free option instead of youtube only

**Comment by wanghaisheng** [comment]
> Put the full RTMP URL right there where it says to input the YouTube broadcast ID.

you mean I need login in google first and see this id field

**Comment by damencho** [comment]
Nope, there is an input field that says "Enter your YouTube livestream key here", there you paste the rtmp URL you have.

**Comment by wanghaisheng** [comment]
thanks very much .

**Comment by longuto** [comment]
Is this released in which version? Is there an update on Docker

**Comment by saghul** [comment]
THis has been working for years.

**Comment by longuto** [comment]
What I mean is not using YouTube during live streaming, but using the RTMP protocol.  @saghul

**Comment by saghul** [comment]
Yes, that feature was implemented years ago.

**Comment by longuto** [comment]
我用rtmp协议直播失败了，但是录制是正常的。 我用的是docker的9220版本。 是不是有什么没有设置。 
![微信截图_20240206185031](https://github.com/jitsi/jitsi-meet/assets/21220020/a6c3dd65-e497-48de-b395-26052efda8d4)
![微信截图_20240206185042](https://github.com/jitsi/jitsi-meet/assets/21220020/3dcfc464-7b96-4642-89d0-8c9914d69aa2)

**Comment by longuto** [comment]
I failed to live stream using the RTMP protocol, but the recording is normal. I am using Docker's 9220 version. Is there something that hasn't been set.
![微信截图_20240206185031](https://github.com/jitsi/jitsi-meet/assets/21220020/d889202e-4484-4a76-9185-587b7a0ca0f6)
![微信截图_20240206185042](https://github.com/jitsi/jitsi-meet/assets/21220020/3e3cc662-4212-4f3c-bf85-a36d98edac8e)

**Comment by saghul** [comment]
Check the Jibri logs

**Comment by longuto** [comment]
![微信截图_20240206191500](https://github.com/jitsi/jitsi-meet/assets/21220020/9550039d-e6f6-46d3-aaa4-2227aa1bb086)
![微信截图_20240206191518](https://github.com/jitsi/jitsi-meet/assets/21220020/773e8516-eff3-4ca2-896a-39a49c487c67)

**Comment by saghul** [comment]
Is there anything else, in the other Jibri log files?

**Comment by longuto** [comment]
[browser.0.txt](https://github.com/jitsi/jitsi-meet/files/14179401/browser.0.txt)
Which file do you need, I have uploaded the < browser.0.txt
![微信截图_20240206201804](https://github.com/jitsi/jitsi-meet/assets/21220020/8553a99e-4556-4db1-9f56-bab4d5ce7a93)
> file.

**Comment by longuto** [comment]
[Uploading log.0.txt…]()

**Comment by longuto** [comment]
i have not set public url.  use ip:844

**Comment by damencho** [comment]
Is your deployment using self signed certificates?

**Comment by longuto** [comment]
i use ip:8443, have not self signed certificates

**Comment by longuto** [comment]
![Uploading 微信截图_20240206210951.png…]()

**Comment by longuto** [comment]
![微信截图_20240206210951](https://github.com/jitsi/jitsi-meet/assets/21220020/e5b99eeb-0adb-430a-8e03-0e2d5b702dfc)

**Comment by saghul** [comment]
Yes that is a self-signed certificate.
