### ISSUE TITLE
[Modal "Waiting for the host"] cancel CTA not cancelling 

### ISSUE THREAD

**Issue by MatheoJaouen** [jitsi/jitsi-meet#14312]
### Description:
Once the "waiting for the host" modal is displayed, even if we cancel or close the modal it will still try to join the conference. Then display again the modal if the host os still not here.
It should stop trying to join the conference.

### Steps to reproduce:

1. Join a meeting where you are not the host
2. See the waiting for the host modal
3. Cancel ("cancel" CTA in the modal or press escape on the keyboard.
4. Go in for instance the settings
5. "Waiting for the host" Modal re-appears after a few seconds, still trying to join the conference

### Expected behavior:
Do not try to join the conference once we cancel (or when the modal is not visible).

### Server information:

- Jitsi Meet version: last one
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Is this for meet.jit.si or your deployment?

**Comment by damencho** [comment]
Currently on meet.jit.si it does not try to join the conference and when you cancel it it waits for the creator of the room to arrive.
