### ISSUE TITLE
Screen sharing on Android 10+

### ISSUE THREAD

**Issue by ISalikhzyanov** [jitsi/jitsi-meet#14318]
Hello. I'm learning webrtc in React Native and chose the jitsi app as an example. I became interested in the screen sharing feature, but unfortunately I had problems with this functionality
I try to fix screen sharing feature on Mobile device. On all versions of IOS and on Android < 10 it works fine. But when it starts on platform Android 10+ it shows only black screen and i did not see problems in metro terminal. I think the problem is somewhere in lib-jitsi-meet, but i can't find it yet. 
<img width="841" alt="Снимок экрана 2024-02-05 в 10 39 33" src="https://github.com/jitsi/jitsi-meet/assets/94790556/b92a76bd-689b-413d-8c2e-a84ec6e75c97">
<img width="583" alt="Снимок экрана 2024-02-05 в 10 40 22" src="https://github.com/jitsi/jitsi-meet/assets/94790556/2d539f1a-b684-4053-a934-c217db6b7ee9">

**Comment by saghul** [comment]
What SDK and version are you using on Android?

**Comment by ISalikhzyanov** [comment]
I'm using a fairly old release and gradually adding new features from jitsi releases. Now i have latest android and react-native-sdk folder from Jitsi.

This is my actual React-native dependencies
"react-native": "0.69.12",
    "react-native-background-timer": "2.4.1",
    "react-native-calendar-events": "2.2.0",
    "react-native-callstats": "3.73.22",
    "react-native-check-box": "^2.1.7",
    "react-native-collapsible": "1.5.1",
    "react-native-default-preference": "1.4.2",
    "react-native-device-info": "^8.0.0",
    "react-native-document-picker": "^7.1.3",
    "react-native-gesture-handler": "2.9.0",
    "react-native-get-random-values": "1.7.2",
    "react-native-image-picker": "^7.1.0",
    "react-native-immersive-mode": "2.0.1",
    "react-native-keep-awake": "4.0.0",
    "react-native-orientation-locker": "1.5.0",
    "react-native-pager-view": "5.4.9",
    "react-native-paper": "4.8.1",
    "react-native-performance": "2.0.0",
    "react-native-progress": "^5.0.1",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "3.13.1",
    "react-native-sound": "github:jitsi/react-native-sound#3fe5480fce935e888d5089d94a191c7c7e3aa190",
    "react-native-splash-screen": "3.2.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-transformer": "0.14.3",
    "react-native-url-polyfill": "1.2.0",
    "react-native-use-file-upload": "^0.2.0",
    "react-native-video": "https://git@github.com/react-native-video/react-native-video#7c48ae7c8544b2b537fb60194e9620b9fcceae52",
    "react-native-watch-connectivity": "0.4.3",
    "react-native-webrtc": "111.0.6",
    "react-native-webview": "13.5.1",
    "react-native-youtube-iframe": "2.1.1"

**Comment by saghul** [comment]
It's very hard to debug with that level of uncertainty. Please test again once everything has been updated to match the latest release.

**Comment by ISalikhzyanov** [comment]
Maybe you can tell me what points and functions I need to pay attention to? According to my observations, the problem occurs in lib-jitsi-meet, maybe in screenObtainer? Thanks for the help

**Comment by saghul** [comment]
The problem is screen-sharing on Android is quite involved since it requires a foreground service, which the SDK uses, the obtainer just calls to the getDisplayMedia API which react-native-webrtc exposes.

**Comment by ISalikhzyanov** [comment]
Thank you so much!)
