### ISSUE TITLE
[Bug] White status bar in a meeting (Jitsi Meet Android SDK 8.6.0)

### ISSUE THREAD

**Issue by vadym-mytrenko-923** [jitsi/jitsi-meet#14325]
Hi team! We are facing an issue with a white status bar while the meeting is ongoing. The status bar color can't be changed via window parameters so looks like it's an internal Jitsi Meet SDK issue. 

- **Device:** Any Android device
- **SDK version:** 8.6.0+ (the problem still exists in 8.6.1)

This issue duplicates two closed earlier (but not resolved) issues: 
https://github.com/jitsi/jitsi-meet/issues/13342﻿
﻿https://github.com/jitsi/jitsi-meet/issues/13909

Screenshot: 
![image](https://github.com/jitsi/jitsi-meet/assets/159130206/728ba3cd-87c4-4eec-a463-d5899fc4e840)

**Expected result:** The user should be able to see the time, notifications, battery status, etc.; the status bar color matches the application theme.
**Actual result:** The status bar is white (doesn't match the app theme), and no icons are visible there

We kindly ask you to resolve this issue as soon as possible to give the users a good experience.

**Comment by vadym-mytrenko-923** [comment]
Hi @saghul! Can you please give an update about this bug? 

P.S. Unfortunately, it's also reproducible on the Jitsi SDK 9.0.0 version.

**Comment by saghul** [comment]
We are not actively working on it, but a PR would be welcome.
