### ISSUE TITLE
Start screen sharing menu/button doesn't appear in android chrome

### ISSUE THREAD

**Issue by mahive89** [jitsi/jitsi-meet#14336]
I am using Android 14 and latest chrome. 
Screen sharing option/menu doesn't show up in mobile browser. (tried firefox too)

to be very specific - 
Phone - Samsung A23 5G
Chrome 121.0.6167.144
Android 14; SM-A236E Build/UP1A.231005.007

I tried this using example meeting at - https://meet.jit.si/
I tried this using custom iframe api with domain - 8x8.vc
I tried by manually adding button in my html and triggering command 'toggleShareScreen' using javascript - 
api.executeCommand('toggleShareScreen');

All of these attempts failed. We badly need feature in mobile browsers as its supported in desktop browsers.
Please check attached screenshot.

I tried it in Jitsi App download from Play Store. And this feature works there. So its really strange why its not available from mobile browser.
Please help me with resolution.

![Screenshot_20240208_000208_Chrome](https://github.com/jitsi/jitsi-meet/assets/48735915/0044b286-79ae-4f03-b300-35e5ab3e60af)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

To use screen sharing on mobile, you need to use the app. The browsers do not provide the needed API for us to implement it, once they release that we will work on adding it.
