### ISSUE TITLE
Have "email" as a people search query type supported in the "Add People" dialog

### ISSUE THREAD

**Issue by raphaelbadawi** [jitsi/jitsi-meet#14331]
**Is your feature request related to a problem you are facing?**

In my hosted Jitsi instance, I would like to use the AddPeopleDialog widget to get **emails** from an autocomplete API, and when a selection is made, another API endpoint is called (sending the actual invites would be the responsibility of this API endpoint, which would return 200 OK if everything went accordingly).

**I don't actually authenticate users in my Jitsi instances, so the AddPeopeDialog doesn't even show when trying to sort things out for this kind of autocompletion.**

**Describe the solution you'd like**

Currently, the AddPeopleDialog supports phone (with SIP protocol), rooms and users (registered in Prosody). Since I don't actually authenticate users in my Jitsi instances, I just want to have the AddPeopleDialog widget being able to send email invites using my own email directory. Right now, if SIP is not enabled, JWT token is required to show the dialog (as it is handled by the isAddPeopleEnabled function). If emails were to be their own peoleSearchQueryType, JWT token would be required only if we have "user" or "room" in peopleSearchQueryTypes config.

**Describe alternatives you've considered**

If I want to make things work for email autocompletion, I have to make ugly overrides in the source code before building my front app. I would much prefer doing a clean development respecting the contributing guidelines and making a pull request. I'm willing to make the actual development but I prefer to make the feature request first to see if such a PR with those specs may be accepted or not.

**Comment by abhinavs1920** [comment]
I would like to work on this issue. Thank You!!!

**Comment by jlemangarin** [comment]
@damencho What do you think ? Can we start to work on it ?

**Comment by damencho** [comment]
How will you authenticate the http requests that are executed in the addPeopleDialog?

**Comment by raphaelbadawi** [comment]
Well right now in my current build I've added "credentials: \"include\"" in the fetch calls coming from searchDirectory and invitePeopleAndChatRooms. So cookies are included in the request and so my directory service can work things out.

This is not an ideal solution.

I guess it would be better to be able to add custom keys and values in the query string, via the config.js, so whatever the directory service is expecting it could just be added to the query string by tweaking config.js.

**Comment by raphaelbadawi** [comment]
Even if the something actually refers to a localStorage key for example?

**Comment by damencho** [comment]
Yeah, maybe read a value from there and add it as Authorization to the request, that will work. 
If you are preparing a PR, make sure this is turned off by default and current behaviour is not changed.

**Comment by raphaelbadawi** [comment]
Okay I will base the PR on those specs ;-) Thanks!
