### ISSUE TITLE
Youtube video sharing 

### ISSUE THREAD

**Issue by HacerBusraKILIC** [jitsi/jitsi-meet#14330]
### Steps to reproduce:

1. Start a meeting.
2. Joined participants
3. Any participant shares youtube video
4. Internet connection interrupted at least 2-3 minutes.
5. Internet connection comes back  and then joining the meeting again.
6. Opens the overflow menu.
7. Share Video button disable 

### Expected behavior:

Share video button is not disabled

### Actual behavior:
My internet connection is disconnected. When reconnected, the share video button appears disabled.

### Server information:

- Jitsi Meet version: 
- Operating System:

### Client information:

- Browser / app version: 23.6.1 mobile app version
- Operating System:

### Additional information:

Sample video =>(https://lifeboxtransfer.com/s/3a4919fc-c9d9-457c-a9a9-0a3acd9b5bf8)

**Comment by abhinavs1920** [comment]
I would like to work on this issue. Thank You!!!
