### ISSUE TITLE
Jitsi mobile app shows meeting name on prejoin screen when `meeting-name.enabled: false`

### ISSUE THREAD

**Issue by danilvalov** [jitsi/jitsi-meet#14332]
**Is your feature request related to a problem you are facing?**
I use genarating UUID as meeting names to create unique rooms for users.
I wanted to enable the prejoin screen to show audio/video mute buttons for users.
But there is a meeting name in the top of prejoin screen (with cropped non-beautiful UUID), and I can't disable it.

**Describe the solution you'd like**
I think good solution is one from the following:
1. Use `meeting-name.enabled` flag to hide/show meeting name on the prejoin screen too (not only on meeting screen)
2. Add a new flag to `prejoinpage` group (ex.: `prejoinpage.hideMeetingName`)

**Comment by saghul** [comment]
@Calinteodor Please add this to your list.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/14339

**Comment by danilvalov** [comment]
Thank you!
It was so... fast :)

**Comment by alikhancherli** [comment]
Is there this feature on the web side?
I need it.

**Comment by saghul** [comment]
This is the config option for the web: https://github.com/jitsi/jitsi-meet/blob/c7cfb5218d368faf2381e5042d19448d5cf86f3b/config.js#L1535
