### ISSUE TITLE
 In the JWT token I have set moderator:false but after I joined the meet via token , showing the message that you`re joined as a moderator. Please help me to sort this issue.  I have self hosted Jitsi in AWS EC2 Ubuntu 22.04

### ISSUE THREAD

**Issue by karthikeyanreactdev** [jitsi/jitsi-meet#14341]
I edited /etc/prosody/conf.avail/xxxx.xxxx.xxxx.cfg.lua

VirtualHost "xxx.xxxx.xxxx"
authentication = "token" -- do not delete me
-- Properties below are modified by jitsi-meet-tokens package config
-- and authentication above is switched to "token"
app_id="xxxxx"
app_secret="xxxxx"
allow_empty_token = false;
-- Assign this host a certificate for TLS, otherwise it would use the one
-- set in the global section (if any).
-- Note that old-style SSL on port 5223 only supports one certificate, and will always
-- use the global one.

Component "conference.xxx.xxxxxx.xx" "muc"
restrict_room_creation = true
storage = "memory"
modules_enabled = {
    "muc_hide_all";
    "muc_meeting_id";
    "muc_domain_mapper";
    "polls";
    "token_verification";
    "muc_rate_limit";
    "muc_password_whitelist";
    "muc_allowners";
    "token_moderation";
}
admins = { "focus@auth.xxx.xxxxx.xx" }
muc_password_whitelist = {
    "focus@auth.xxx.xxxx.xx"
}
muc_room_locking = false
allowners_moderated_subdomains = { "moderated"}
muc_room_default_public_jids = true

**Comment by saghul** [comment]
Where did you get that `token_moderation` plugin from?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Disable `muc_allowners `.

**Comment by saghul** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.
> 
> Disable `muc_allowners `.

LoL I should have caught that!
