### ISSUE TITLE
The user is not heard when his mobile screen is locked.(systematic in Android 14 , randomly in other  Android versions)

### ISSUE THREAD

**Issue by HajerMehemdi** [jitsi/jitsi-meet#14351]
### Description:

when user A and user B are  connected to a Video Conference
 and the user A has a screen is locked and already talking
==> User B can't hear User A

### Steps to reproduce:

1. user A with android 14 
2. user A and B in video conference
3. user A turn off the device (Screen Locked)
4. user A talk
5. user not hear user B

### Expected behavior:

user B should hear user A even Screen of mobile is locked

### Actual behavior:

 user B  not hear user A

### Server information:

- Jitsi Meet version: 8.6.1
- Operating System: mobile Android

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
I suspect this is due to the changes in foreground service usage. We are currently working on re-doing that.

**Comment by saghul** [comment]
@Calinteodor let's make sure to test this.
