### ISSUE TITLE
Hi even with Jisti 8.6.1

### ISSUE THREAD

**Issue by HajerMehemdi** [jitsi/jitsi-meet#14354]
Hi even with Jisti 8.6.1

Expected behavior:
1- Home page/waiting room:

The "Enable low bandwidth mode" should be translated into French. ==> Fixed
"Rejoindre La Réunion" should be "Rejoindre la réunion" without capital letters.
2- Sondages/survey:

"Créer Un Sondage" should be "Créer un sondage" without Capital letters

3- Mute the mic:

"Couper Le Micro De Tout Le Monde" should be "Couper le micro de tout le monde" without capital letters

i need to add that with Android 14 even after change tha lanquage in the sytem the Jitsi not take the change in concideration ==> need te restart the app to ahve the language of the system

_Originally posted by @HajerMehemdi in https://github.com/jitsi/jitsi-meet/issues/13671#issuecomment-1938356757_

**Comment by saghul** [comment]
The SDK is community translated, please see: https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md
