### ISSUE TITLE
Meeting login doesnt work.

### ISSUE THREAD

**Issue by nsmith1024** [jitsi/jitsi-meet#14350]
Hello,

I just added jitsi meet to my android java app. However when it starts up it asking me to log in. I tried loggin in with both facebook and google, but it doesnt work, trying both methods simply just returns to the page showing buttons to select which way i want to sign in, or it goes to the play store to show the jisti meet app.

Is it a bug? Is there mode code i need to add in my android java app for this to work?

Thanks

**Comment by Prateek-Fst** [comment]
When I tried to reproduce this issue , It was logged in but the problem I am facing is that it asks for log-in every time I try to start a meet. Instead I should get a message "start meeting as moderator" , once I logged in.

**Comment by saghul** [comment]
I guess you are using the meet.jit.si server?

That is not meant to be used in your apps. If you point it to your own backend you can have it with no auth or whatever other mechanism.
