### ISSUE TITLE
Hi even with the jitsi version8.6.1 the issue persist :

### ISSUE THREAD

**Issue by HajerMehemdi** [jitsi/jitsi-meet#14353]
Hi even with the jitsi version8.6.1 the issue persist :
"Enable low bandwidth mode " label is having some issues when set to German (with the quotation mark on the label)

**„**Nur Audio“ deaktivieren",
 **„**Nur Audio“ aktivieren"
==> should be ** " **Nur Audio " deaktivieren

_Originally posted by @HajerMehemdi in https://github.com/jitsi/jitsi-meet/issues/13890#issuecomment-1938307019_

**Comment by saghul** [comment]
Please don't open dupliocate issues.
