### ISSUE TITLE
How to Enable Remote Control ?

### ISSUE THREAD

**Issue by gulteking** [jitsi/jitsi-meet#1437]
Hi, 

Remote control has been implemented as i see from commits and source.
 But i couldn't find any documentation or guide about how can we use this feature.
i also tried to do remote control from meet.jit.si, but couldn't find anything.

i have an ubuntu 16.04 server, installed jitsi-meet from jitsi repositories (apt install jitsi-meet). 
After i enable desktopSharing from config.js file, what are next steps?

Thans, regards.

**Comment by damencho** [comment]
Hi, when having questions or problems, please use the mailinglist before opening an issue.

For the controlled part you need to use desktop client, which is based on electron https://github.com/jitsi/jitsi-meet-electron. The controlling client can be web. Keep in mind that this is still work in progress.

**Comment by MurzNN** [comment]
@gulteking Did you find the way to enable Screen Remote Control feature on jitsi-meet-electron?

**Comment by arts111188** [comment]
Hi,

Please could you share some information regarding Screen Remote Control feature like how to enable it in Jitsi Meet and use it.

**Comment by codejamninja** [comment]
Hey, I can't figure out how to enable it

**Comment by damencho** [comment]
There is nothing to enable. Just the participant that will be controlled needs to be running jitsi-meet inside the jitsi-meet-electron app https://github.com/jitsi/jitsi-meet-electron. The controlling part can still be on regular chrome.

**Comment by codejamninja** [comment]
How do you run jitsi-meet inside the electron app?

**Comment by codejamninja** [comment]
Oh, I finally figured it out. I don't know why it took me so long to find the place to take control.
![0018](https://user-images.githubusercontent.com/6234038/43942808-088d4ca8-9c3f-11e8-8934-22a2a2debb0b.jpg)

**Comment by MurzNN** [comment]
Confirm that the place is hard to find, will be good to place this feature in more visible place in interface.

**Comment by codejamninja** [comment]
I don't think the location is the problem. The real problem is the docs.

**Comment by tuxayo** [comment]
@damencho 
> There is nothing to enable. Just the participant that will be controlled needs to be running jitsi-meet inside the jitsi-meet-electron app https://github.com/jitsi/jitsi-meet-electron. The controlling part can still be on regular chrome.

Thanks, I would never have found without your help!
This feature is huge, I wasn't seeing an easy alternative to TeamViewer until then.

**Comment by tuxayo** [comment]
@codejamninja
> I don't think the location is the problem. The real problem is the docs.

Thanks you for your screenshot!
Maybe the location isn't intuitive? Or should there be a visual hint/message about remote control when screensharing is started from Jitsi Meet desktop?

**Comment by hpcbjdic** [comment]
Hi,

unfortunately I can't see the "Remote control" button as depicted in the screenshot above. "Kick out", "Mute" and "Mute all" is there but not "Remote control".
I'm using https://github.com/jitsi/jitsi-meet-electron/releases v.1.1.0, the other side is using Chromium @ Linux.

Is someone out there who has ideas and can help me?

Best,
Björn

**Comment by sushantdanekar** [comment]
Is it possible to enable remote control menu in web version ?

**Comment by gulteking** [comment]
@sushantdanekar as i know, it s not possible to allow control your pc from web browser. Because you can't allow to control your desktop from your browser.  

You can only control another pc from browser app.

**Comment by MurzNN** [comment]
But [Chrome Remote Desktop](https://chrome.google.com/webstore/detail/chrome-remote-desktop/inomeogfingihgjfjlpeplalcfajhgai) solve this limitation via WebExtension, can Jitsi implement same way?

**Comment by saghul** [comment]
I don’t think it’s just a web extension, that may enable some functionality in the browser itself.

**Comment by charuchinmay** [comment]
Hi all,

Apart from the jitsi electron based desktop app, is there any other way to enable remote desktop control through jitsi ? We have installed standalone jitsi-meet as well as containerised jitsi-meet application in our servers and we have embedded jitsi into our custom application through external jitsi APIs. So, I wanted to ask if it’s possible to enable remote desktop control feature through external jitsi APIs ?

@damencho you kind help here will be highly appreciated.

**Comment by damencho** [comment]
There is nothing to enable through external API, if you add the electron-utils to your electron app as in the example when running the client in electron, will see and advertise the new feature ...

**Comment by jeisoncp** [comment]
> Hi,
> 
> unfortunately I can't see the "Remote control" button as depicted in the screenshot above. "Kick out", "Mute" and "Mute all" is there but not "Remote control".
> I'm using https://github.com/jitsi/jitsi-meet-electron/releases v.1.1.0, the other side is using Chromium @ Linux.
> 
> Is someone out there who has ideas and can help me?
> 
> Best,
> Björn

It was disabled because of a security issue: https://github.com/jitsi/jitsi-meet-electron/issues/431

**Comment by Raajprabhuc** [comment]
Hi,

I need to know how to enable remote control option via cli in Jitsu meet standalone server 
Is there any option available to enable remote control option to view on screen

**Comment by saghul** [comment]
It's not possible to enable it unless you rebuild the app yourself.

**Comment by builder555** [comment]
without digging too much through the code, is the security issue inherent to electron? the advisory doesn't provide those details.

**Comment by vmsman** [comment]
Sadly, even after making the appropriate changes on the Jitsi Meet self hosted server, it was also necessary to rebuild the jitsi electron client.  I then ran into a wall where the "remote" module is missing in the electron client even with a custom build.
