### ISSUE TITLE
websocket initializing issue prosody log jitsi meet 2.0.9220

### ISSUE THREAD

**Issue by sparashetti820** [jitsi/jitsi-meet#14372]
modulemanager: Error initializing module 'websocket' on 'recorder.preprod.dialtm.in': /usr/share/lua/5.2/prosody/core/m>
                                                        stack traceback:
                                                        [C]: in function 'error'
                                                        /usr/local/share/lua/5.2/halo/class.lua:396: in function '__index'
                                                        /usr/local/share/lua/5.2/net/stream.lua:45: in main chunk
                                                        [C]: in function '_real_require'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:203: in function 'require'
                                                        /usr/local/share/lua/5.2/net/stream/inet.lua:33: in main chunk
                                                        [C]: in function '_real_require'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:203: in function 'require'
                                                        /usr/local/share/lua/5.2/net/http/server.lua:30: in main chunk
                                                        [C]: in function '_real_require'
                                                        ...
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:270: in function 'do_load_module'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:353: in function 'load'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:131: in function '?'
                                                        /usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
                                                        (...tail calls...)
                                                        /usr/share/lua/5.2/prosody/core/hostmanager.lua:108: in function 'activate'
                                                        /usr/share/lua/5.2/prosody/core/hostmanager.lua:58: in function '?'
                                                        /usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
                                                        (...tail calls...)
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:428: in function 'prepare_to_start'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:707: in function 'f'
                                                        /usr/share/lua/5.2/prosody/util/async.lua:156: in function 'func'
                                                        /usr/share/lua/5.2/prosody/util/async.lua:144: in function </usr/share/lua/5.2/prosody/util/async.lua:142>
                                                        stack traceback:
                                                        [C]: in function 'error'
                                                        /usr/share/lua/5.2/prosody/core/moduleapi.lua:167: in function 'depends'
                                                        /usr/lib/prosody/modules/mod_websocket.lua:357: in function 'add_host'
                                                        /usr/lib/prosody/modules/mod_websocket.lua:374: in main chunk
                                                        [C]: in function 'xpcall'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:270: in function 'do_load_module'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:353: in function 'load'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:131: in function '?'
                                                        /usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
                                                        (...tail calls...)
                                                        /usr/share/lua/5.2/prosody/core/hostmanager.lua:108: in function 'activate'
                                                        /usr/share/lua/5.2/prosody/core/hostmanager.lua:58: in function '?'
                                                        /usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
                                                        (...tail calls...)
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:428: in function 'prepare_to_start'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:707: in function 'f'
                                                        /usr/share/lua/5.2/prosody/util/async.lua:156: in function 'func'
                                                        /usr/share/lua/5.2/prosody/util/async.lua:144: in function </usr/share/lua/5.2/prosody/util/async.lua:142>
Feb 15 04:06:20 preprod-dialtm prosody[950590]: modulemanager: Error initializing module 'http_errors' on '*': /usr/local/share/lua/5.2/halo/class.lua:396: class "Sock>
                                                        stack traceback:
                                                        [C]: in function 'error'
                                                        /usr/local/share/lua/5.2/halo/class.lua:396: in function '__index'
                                                        /usr/local/share/lua/5.2/net/stream.lua:45: in main chunk
                                                        [C]: in function '_real_require'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:203: in function 'require'
                                                        /usr/local/share/lua/5.2/net/stream/inet.lua:33: in main chunk
                                                        [C]: in function '_real_require'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:203: in function 'require'
                                                        /usr/local/share/lua/5.2/net/http/server.lua:30: in main chunk
                                                        [C]: in function '_real_require'
                                                        ...
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:270: in function 'do_load_module'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:353: in function 'load'
                                                        /usr/share/lua/5.2/prosody/core/modulemanager.lua:131: in function '?'
                                                        /usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
                                                        (...tail calls...)
                                                        /usr/share/lua/5.2/prosody/core/hostmanager.lua:108: in function 'activate'
                                                        /usr/share/lua/5.2/prosody/core/hostmanager.lua:58: in function '?'
                                                        /usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
                                                        (...tail calls...)
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:428: in function 'prepare_to_start'
                                                        /usr/share/lua/5.2/prosody/util/startup.lua:707: in function 'f'
                                                        /usr/share/lua/5.2/prosody/util/async.lua:156: in function 'func'
                                                        /usr/share/lua/5.2/prosody/util/async.lua:144: in function </usr/share/lua/5.2/prosody/util/async.lua:142>

### Description:
Getting this issue after updating jitsi-meet from old version to new version in linux own instance setup. And trying to start call rejoining automatically and getting above error in prosody log.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version: 2.0.9220
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
What Prosody version are you running?

**Comment by sparashetti820** [comment]
it is resolved, it was issue with lua, after resintalling lua 5.2 it is resoved.
