### ISSUE TITLE
Microphone not working on iPad

### ISSUE THREAD

**Issue by GeorgeTuz** [jitsi/jitsi-meet#14389]
**Description:**
When starting a session from an iPad with an iOS version lower than 16, access to the microphone gives an error

**Steps to reproduce:**
Joined a call using Safari or Chrome
Confirming access to the microphone
We get an error

**Expected behavior:**
The microphone will be available for calls

**Actual behavior:**
The microphone is not available for calls

**Server information:**
lib-jitsi-meet version: 0748d89a

**Client information:**
Browser: Safary, Google Chrome

**Operating System:** 
iOS 15 and lower 

**Additional information:**
On version 16 of iOS and higher there are no errors and the microphone works

![image-20240208-110922](https://github.com/jitsi/jitsi-meet/assets/31877721/f36ffa0a-4572-46da-8242-e9483361af1c)

**Comment by damencho** [comment]
So you reproduce the same on meet.jit.si?
