### ISSUE TITLE
Safari - Screen share stop not working

### ISSUE THREAD

**Issue by surya-atheer** [jitsi/jitsi-meet#14386]
### Description:

Screen share in Safari not removing the stopping the screen share.  Not removing the screen share thumbnails.

### Steps to reproduce:

1. Joined a call with safari (one user) and the second user in chrome
2. From Safari browser start screen share.  It shows the OS dialog on Right top with "Stop Screen Share" button.
3. Click the Stop Screen share button from the OS dialog ( not form the toolbox)
4. It not stops the screen share

### Expected behavior:
It should stop the screen share and need to remove the virtual thumbnail 

### Actual behavior:
looks like it showing stopped the screen share but virtual screen share thumnail not removing and also large video still showing the screen share screen

### Server information:

- Jitsi Meet version: https://meet.jit.si
- Operating System: 

### Client information:

- Browser / app version: Safari 17.0
- Operating System: MAC Sonoma 14.0

### Additional information:
If I stops the screen share using toolbox button it working properly.

**Comment by surya-atheer** [comment]
<img width="332" alt="Screenshot 2024-02-19 at 12 03 32 PM" src="https://github.com/jitsi/jitsi-meet/assets/106060964/1e2fdbff-9df9-44c9-b55b-13e0c31a8a48">

**Comment by saghul** [comment]
Ping @jallamsetty1
