### ISSUE TITLE
Need Documentation for 'jitsi/web' , How docker image is created ?

### ISSUE THREAD

**Issue by RohitArora7** [jitsi/jitsi-meet#14390]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

That is created cia the docker file
https://github.com/jitsi/docker-jitsi-meet/blob/master/web/Dockerfile
