### ISSUE TITLE
[react-native-sdk] resume() can only be called in the DISCONNECTED state

### ISSUE THREAD

**Issue by Anfieldd** [jitsi/jitsi-meet#14399]
### Description:

Hi all! I found the problem with react-native-sdk. When I'm in the conference and switch from wi-fi to the mobile network and then again switch to wi-fi I have this error 

> resume() can only be called in the DISCONNECTED state

I think it's related to lib-jitsi-meet and stream management. It happens only for rnsdk.
![IMG_1363](https://github.com/jitsi/jitsi-meet/assets/32684253/e78c8c2e-4ad3-4911-bfd4-578c089666fc)

### Steps to reproduce:

1. Build and open the app from https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/react-native (ios)
2. Join to the conference
3. Switch off wi-fi
4. Wait a few seconds
5. Switch on wi-fi

### Expected behavior:

I connect to wi-fi and stay in the conference without any errors

### Actual behavior:

prod env: I don't see any error, I was kicked from the app.
dev env: I see the error in the attached screenshot

### Server information:

- Jitsi Meet version: meet.jit.si server
- Operating System:

### Client information:

- Browser / app version: "@jitsi/react-native-sdk": "1.0.3"
- Operating System: ios

**Comment by saghul** [comment]
Ping @damencho

**Comment by damencho** [comment]
@saghul what is the difference between the two?

**Comment by saghul** [comment]
The SDK is behind, we haven't made a release since late last year.
