### ISSUE TITLE
Conference video quality drops when a user is on an Electron window

### ISSUE THREAD

**Issue by jeanfbrito** [jitsi/jitsi-meet#14396]
### Description:

Hello, I work on Rocket.Chat and we are having some users reporting an issue with Jitsi.
On our Desktop app we open Jitsi inside a new Electron window.

In a conference (a meeting with more than 2 users) when a user is inside our Desktop App, the quality is dropped of video sharing for everyone.
I tried investigating what we could do to fix that, but doesn't seem to be something from our side.
On the console log, I could find that when an Electron client is connected the `ReceiverVideoConstraints` is set to `"maxHeight":360`.
![image](https://github.com/jitsi/jitsi-meet/assets/1177482/1d5d4bd1-88a0-447f-ab4b-98da5b22c710)

There is any way we can change this? The only way today is to make the video call open on the browser.

### Steps to reproduce:

1. Create a meeting with more than 2 clients.
2. Enter the meet with an Electron window.
3. All the videos will drop quality, users said that even webcam video drops the quality.

### Expected behavior:

Work on Electron as it works on Chrome, if possible.

### Actual behavior:

The video quality is dropped to 360p.

### Server information:

- Jitsi Meet version: [meet.jitsi.si ](https://meet.jit.si/) version
- Operating System: unknown

### Client information:

- Browser / app version: Rocket.Chat Desktop App
- Operating System: MaOS and Windows

**Comment by damencho** [comment]
Which version of electron is that?
It is normal to drop the video to 360 when you show the meeting in tileview. If you switch to stage view, only the stage participant will be requested with HD and the rest with 180p.

**Comment by jallamsetty1** [comment]
Can you check what is the tile height thats calculated on the electron client? The log should look something like this

`2024-02-22T18:02:43.997Z [features/video-quality] <sF.register.deepEquals [as listener]>:  Video quality level for thumbnail height: 587.5, is: 360, override: false, max full res N: 2`

For example, in this case, the height of each of the tiles is 587.5 pixels, so the client is going to request the bridge to send 360p videos.

Only if the calculated height >= 720, the client will request 720p videos from the bridge as seen in the below log.

`2024-02-22T18:04:57.845Z [features/video-quality] <sF.register.deepEquals [as listener]>:  Video quality level for thumbnail height: 1078.1333333333334, is: 720, override: false, max full res N: 2
`

**Comment by moell9** [comment]
We have the same problem on our site. How can I check this in the electron client ?

**Comment by saghul** [comment]
You can enable developer tools and check in the console tab.

**Comment by jeanfbrito** [comment]
Sorry for the late reply, I got sick last week. 
The size doesnt seem to deteriorate, I tried opening on big window sizes and seems to do the same thing.
The unique thing that I could see is that when there are more than two users the call changes to conference and stop using p2p and start using a url that shows on the console.
I tried opening more clients on safari and Firefox along and seems to be deteriorating too. So I dont know if there is any limitation on quality for conference?
I need help to understand what could do the screen sharing video decrease it quality and how this can be handled on this cases.

**Comment by jeanfbrito** [comment]
> Can you check what is the tile height thats calculated on the electron client? The log should look something like this
> 
> `2024-02-22T18:02:43.997Z [features/video-quality] <sF.register.deepEquals [as listener]>: Video quality level for thumbnail height: 587.5, is: 360, override: false, max full res N: 2`
> 
> For example, in this case, the height of each of the tiles is 587.5 pixels, so the client is going to request the bridge to send 360p videos.
> 
> Only if the calculated height >= 720, the client will request 720p videos from the bridge as seen in the below log.
> 
> `2024-02-22T18:04:57.845Z [features/video-quality] <sF.register.deepEquals [as listener]>: Video quality level for thumbnail height: 1078.1333333333334, is: 720, override: false, max full res N: 2 `

This will show on the console as the new users enter the call?

**Comment by saghul** [comment]
It will show up with layout changes.

**Comment by jeanfbrito** [comment]
> /video-quality

There isnt any log with `video-quality` nor nothing that is on the line of example. So dont seem to be this the change.
 
[jitsi.rocket.chat-1709657134854.log](https://github.com/jitsi/jitsi-meet/files/14498662/jitsi.rocket.chat-1709657134854.log)

**Comment by jeanfbrito** [comment]
Chrome Screen sharer console log:
[chrome screen sharer.log](https://github.com/jitsi/jitsi-meet/files/14498782/chrome.screen.sharer.log)

Chrome viewer console log:
[chrome viewer.log](https://github.com/jitsi/jitsi-meet/files/14498786/chrome.viewer.log)
quality:
![SCR-20240305-mkwb](https://github.com/jitsi/jitsi-meet/assets/1177482/ca49a032-6894-4885-a8e1-f0f67357c4a5)

Electron viewer console log:
[electron viewer.log](https://github.com/jitsi/jitsi-meet/files/14498796/electron.viewer.log)

quality after electron client enter the call:
![SCR-20240305-mlqr](https://github.com/jitsi/jitsi-meet/assets/1177482/4e4ff029-7c68-4eae-9165-4f2518957065)

**Comment by saghul** [comment]
Did you make window size changes, for example?

**Comment by moell9** [comment]
We did the following change from:
`disableSimulcast: false,`
to:
`disableSimulcast: true,`
And now we can use the application window again.
But I don't think this is a proper solution ?

**Comment by saghul** [comment]
Not it isn't. How big is your window and are you resizing it at runtime?

**Comment by moell9** [comment]
We are always working in fullscreen mode. The application window is I think around 800x600 at the beginning. That is the standard size. And we normally resize it to fullscreen.

**Comment by saghul** [comment]
Then you should see the messages @jallamsetty1 mentioned in the console logs.

**Comment by moell9** [comment]
Perhaps @jeanfbrito can test this. He is the developer at RocketChat.

**Comment by jallamsetty1** [comment]
> Chrome Screen sharer console log:
> [chrome screen sharer.log](https://github.com/jitsi/jitsi-meet/files/14498782/chrome.screen.sharer.log)

Can you please share the full log from the screen sharer? I see the logs only upto the moment when the electron client joined and nothing after so it is hard to tell if having the electron client in the call changed the sender characteristics. Please share the full log for both the sender and the electron clien.

**Comment by jallamsetty1** [comment]
Are you seeing that you are seeing the share blurry only on the electron client? If everyone in the call is seeing the share blurry as soon as the electron client joins the call then the problem should be on the sender.

**Comment by moell9** [comment]
Yes. Not only is the sharing blurred, but also the participants are all displayed with too low a resolution. Mostly in 180p.
With `disableSimulcast: true,` the resolution is fine, up to 720p and also the sharing.

**Comment by jeanfbrito** [comment]
> Did you make window size changes, for example?

No because I was using fullscreen windows for testing, something near 1440p height.

**Comment by jeanfbrito** [comment]
> > Chrome Screen sharer console log:
> > [chrome screen sharer.log](https://github.com/jitsi/jitsi-meet/files/14498782/chrome.screen.sharer.log)
> 
> Can you please share the full log from the screen sharer? I see the logs only upto the moment when the electron client joined and nothing after so it is hard to tell if having the electron client in the call changed the sender characteristics. Please share the full log for both the sender and the electron clien.

It was my intention, let me do again, maybe I cleaned up before entering with other clients.

**Comment by moell9** [comment]
I can't see here any progress. The RocketChat users are waiting for a solution.
@jeanfbrito What about your logs ?

**Comment by saghul** [comment]
You can also try to repro with our Electron app, though we haven't received any reports like this one...

**Comment by jeanfbrito** [comment]
> > Chrome Screen sharer console log:
> > [chrome screen sharer.log](https://github.com/jitsi/jitsi-meet/files/14498782/chrome.screen.sharer.log)
> 
> Can you please share the full log from the screen sharer? I see the logs only upto the moment when the electron client joined and nothing after so it is hard to tell if having the electron client in the call changed the sender characteristics. Please share the full log for both the sender and the electron clien.

Here are all the logs from the screen sharer since the start until I close the Electron window. Resized the window on Electron, other windows was very big already.
[jitsi.rocket.chat-1711566752911.log](https://github.com/jitsi/jitsi-meet/files/14780147/jitsi.rocket.chat-1711566752911.log)

**Comment by jeanfbrito** [comment]
> I can't see here any progress. The RocketChat users are waiting for a solution. @jeanfbrito What about your logs ?

Until we found whats going on you can ask the users to open the calls inside web browser. Dont seems to be nothing that we changed from our side.

**Comment by jeanfbrito** [comment]
Here is the degradation that users are reporting. You can see that I open the Electron window. Even resizing it dont changes, if I close the Electron window it maintains that quality. I sent the screen sharer logs for this video. I kept it very small so I could attach here, if needed I can record more.
https://github.com/jitsi/jitsi-meet/assets/1177482/a64f33f8-7372-4ce3-ac37-193d10af7407
[jitsi.rocket.chat-1711567793807.log](https://github.com/jitsi/jitsi-meet/files/14780296/jitsi.rocket.chat-1711567793807.log)

**Comment by jeanfbrito** [comment]
I really don't know if is intended behavior and if there is something we can do to change this.

**Comment by moell9** [comment]
What happens here now? The whole thing used to work and now all of a sudden it doesn't anymore. So there must have been a change.
We continue to work around this with the setting `disableSimulcast: true,`.

**Comment by jallamsetty1** [comment]
` 2024-03-27T19:27:57.184Z [FeatureFlags] <Object.init>:  Source name signaling: false, Send multiple video streams: false, SSRC rewriting supported: false, uses Unified plan: true`

It appears that you are running a very old version of the client that has source-name signaling and multi-stream mode disabled. We have made them the default behavior long time back and the backwards compat code has been removed from the bridge already. Are the client and backend versions out of sync by any chance? 

If you are running the older versions of both client and backend and the issue started happening recently then it could be something in your application or settings.

**Comment by damencho** [comment]
Filter console logs with word version

**Comment by jeanfbrito** [comment]
> Filter console logs with word version

Only one is this:
```
Logger.js:154 2024-03-27T19:27:59.133Z [modules/version/ComponentsVersions.js] Got focus version: 1.0.900
```

**Comment by damencho** [comment]
Nope this is jicofo, path of backend that was released on 17-Jun-2022. For The frontend you need to check the index.html source there are several places with v= which match the jitsi-meet-web version

**Comment by moell9** [comment]
In our environment the version is `v=7712` (/usr/share/jitsi-meet/index.html).

**Comment by damencho** [comment]
Which is from 20-Dec-2023. Your frontend and backend are not compatible with each other. Not sure how you managed to update the packages with such a combination.

**Comment by moell9** [comment]
What does that mean now ?
The problem is with the RocketChat Electron ?
**Reminder:** When I start a videocall from the RocketChat Electron, I have the choice between an application window or within a web browser.
The problem only occurs with the application window within the RocketChat Electron client.
Not when the call is opened in the web browser.
The application window takes default settings from the RocketChat Electron client, the web browser uses Jitsi Meet directly.
Would that be summarized correctly?

**Comment by damencho** [comment]
As mentioned by @jallamsetty1 it can be the settings passed to the jitsi-meet client. Can you extract from the electron window the settings that are passed to the iframe that loads jitsi-meet?

**Comment by jeanfbrito** [comment]
> No, sorry, I can't. But @jeanfbrito can do perhaps. He is the developer of the RocketChat Electron.

On electron side we don't add any settings, we just open the URL on a new window. But I'm reaching the people who maintain the Jitsi app on the Marketplace so we can update it and see what's going on.

**Comment by moell9** [comment]
But the Jitsi app is also needed when the web browser is used for video calls. Or am I wrong ?

**Comment by damencho** [comment]
Both load the same web app, it is just when loading with iframeAPI config overrides are done, I was thinking about those.

**Comment by moell9** [comment]
I was looking for this now:
`[FeatureFlags] <Object.init>: Source name signaling: false, Send multiple video streams: false, SSRC rewriting supported: false, uses Unified plan: true`
But I can't find it. Can you give me some advice please ?

**Comment by saghul** [comment]
It's in the JS console logs.

**Comment by moell9** [comment]
Still can't find it. Can you show me in a screenshot or screencast ?

**Comment by saghul** [comment]
It should show very early when the iframe was loaded.

**Comment by moell9** [comment]
Can't see any [FeatureFlags] ...

**Comment by saghul** [comment]
That log line was removed when we changed the defaults. What lib-jitsi-meet version are you seeing? The log should look like this:

```
2024-04-11T13:43:03.031Z [features/base/lib-jitsi-meet] lib-jitsi-meet version:d1333434
```

**Comment by moell9** [comment]
`[features/base/lib-jitsi-meet] lib-jitsi-meet version:ca40744f`

**Comment by jallamsetty1** [comment]
> `[features/base/lib-jitsi-meet] lib-jitsi-meet version:ca40744f`

This client version is from Dec 2023 and your backend is from Jun 2022. They are not compatible. The client logs @jeanfbrito shared doesn't have the above log line but instead prints the old log that has since been removed. Something is wrong with the client versions, sometimes the new version gets loaded and its the older one at other times.

**Comment by moell9** [comment]
We updated yesterday Jitsi Meet to version 2.0.9364 and RocketChat to version 6.7.0.
Now wit have the lib-jitsi-meet version: `[features/base/lib-jitsi-meet] lib-jitsi-meet version:311766e3`

**Comment by saghul** [comment]
Did you update all components? Do you observe the problem now?

**Comment by moell9** [comment]
What do you mean with all components ?
We have upgraded all Jitsi components that were offered to us via upgrade (apt upgrade --> Ubuntu Server).

**Comment by moell9** [comment]
BTW, the problem seems to be solved after the updates. Just had a meeting with 15 users and the quality is back to normal.
