### ISSUE TITLE
Move Hide Self View to the Video Tab

### ISSUE THREAD

**Issue by jeffabailey** [jitsi/jitsi-meet#14407]
**Is your feature request related to a problem you are facing?**
Yes, finding the **Hide Self View** in the General tab is non-intuitive.

**Describe the solution you'd like**
Move **Hide Self View** to the video tab under **Mirror my video** .

**Describe alternatives you've considered**
Add a hotkey for toggling Hide Self View?

I noticed this PR.

https://github.com/jitsi/jitsi-meet/pull/13339

I'm happy to create a similar PR to move the checkbox if project leads consider this is a desirable change.

**Comment by damencho** [comment]
Then when you hide your self-view how can you revert that setting back?

**Comment by saghul** [comment]
I think they mean to move it to the Video tab, which semantically makes more sense IMHO.
