### ISSUE TITLE
Add input sensitivity / microphone threshold feature

### ISSUE THREAD

**Issue by crabdancing** [jitsi/jitsi-meet#14405]
In Discord, and a number of other VOIP apps, there is a feature that allows the user to cap minimum volume at an arbitrary threshold. If dB are beneath this threshold, the mic switches off. This means that you can easily tune it so that background noise such as fans, typing, and breathing are ignored by your microphone.

![image](https://github.com/jitsi/jitsi-meet/assets/28266167/56caf06e-207d-4f2e-aba3-94035b9b2635)

To make Jitsi Meet more useful for larger business meetings, and to stay competitive with apps like Discord, it seems like a good idea to implement this feature.

Note that this feature request is a replacement for #9934, which met its tragic end at the hands of a stale bot.

**Comment by saghul** [comment]
To adjust reader's expectations: we have no plans to work on this.

**Comment by inceptionabhishek** [comment]
Hey @saghul , Can i work on this feature?

**Comment by inceptionabhishek** [comment]
ok @saghul , I will keep an eye on this :)

**Comment by schoerg** [comment]
At least don't override microphone volume from the OS.

**Comment by saghul** [comment]
We are not doing that. It's a feature the browser has called Acoustic Gain Control.

**Comment by schoerg** [comment]
You could set `autoGainControl ` to false to disable that behaviour.

**Comment by saghul** [comment]
I know. And we have a config option for that too. We just don't have a switch in the UI for it. Most of the times, it does the right thing.
