### ISSUE TITLE
PiP not working while screen shared eventhough feature flag is enabled

### ISSUE THREAD

**Issue by Aykan125** [jitsi/jitsi-meet#14406]
### Description:

I would like to use pip mode while screen sharing, to share the screen of the app itself, I enabled the feature flag 'pip-while-screen-sharing.enabled', and the button for pip on the top left does show up(downward arrow), however when clicked nothing happens, nothin really shows up in the log cat either.

### Steps to reproduce:

Enable feature flag 'pip-while-screen-sharing.enabled'
Start screen share on android app.
Click PiP button.

### Expected behavior:
Screen should minimize and app behind should be visible

### Actual behavior:

Nothing happens, video conference continues.

### Server information:

- Jitsi Meet version: 8.6.1
- Operating System: Windows 10

### Client information:

- Operating System: Android 11, API level 30

**Comment by Calinteodor** [comment]
@Aykan125 Can you please try using other Android versions? I could be that Android 11 doesn't support PiP in screen-share mode? Thanks.

**Comment by Aykan125** [comment]
I've tried with API 32 and 33(android 12L and android 13) still does not work, I believe android 14 is not supported yet so I could not test that.

**Comment by Aykan125** [comment]
Hi,
The issue on my Android app persists. Does the merge to master you did fix the issue, if so will it be released in a later version? Or do I have to do something else to get it working?

**Comment by saghul** [comment]
The app needs to be updated, of course.

**Comment by Aykan125** [comment]
May I inquire about the expected release schedule for the SDK update regarding this change? I'm looking forward to it and would appreciate any details you could provide.

**Comment by saghul** [comment]
We are planning on a release in the next couple of weeks.
