### ISSUE TITLE
I am using JitsiMeetView in Custom Activty and hide all the buttons and toolbar. I want to mute / unmute using my own activity button click but nothing found

### ISSUE THREAD

**Issue by Ahmad-Mustafaa** [jitsi/jitsi-meet#14400]
I have my own activity i disabled all flags to hide Jitsi buttons. I use 
```
view.dispose();
view.abort();
```
these to abort call. Now i want to mute / unmute jitsi on going call within my activity using my own activity but its not working.
I used already flags for toolbar disable and start audio only . I am using `JitsiMeetView view`  and i have layout of activity where i am adding it `binding.framelayoutjitsi.addView(view)` .

These are not the features for SDK then it will be a feature

**Comment by saghul** [comment]
You can use the following broadcast actions: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

**Comment by Ahmad-Mustafaa** [comment]
> You can use the following broadcast actions: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

@saghul Thanks for the answer. Broadcast for the listening purpose. For example i can listen to the broadcast of leaving the meeting but i cannot perform the event actions. 
My use case is I want to mute / unmute jitsi meeting using my Custom UI button which i created in my activity. 
Why i want to do this in jitsi meet hung-up button it shows pop-up Leave Meeting or Leave meeting for all I dont want these messages thats why I created my own activity with hung-up button but i am unable to mute call if i wanted.

**Comment by saghul** [comment]
Search for Broadcast Actions on that page. For example:

```
    Intent muteBroadcastIntent = new Intent(BroadcastAction.Type.SET_AUDIO_MUTED.getAction());
    muteBroadcastIntent.putExtra("muted", muted);
    LocalBroadcastManager.getInstance(getApplicationContext()).sendBroadcast(muteBroadcastIntent);
```

**Comment by Ahmad-Mustafaa** [comment]
`BroadcastAction.Type.SET_AUDIO_MUTED` are not working as Doc or available in SDK . 
using latest sdk version `org.jitsi.react:jitsi-meet-sdk:+` and also tried `org.jitsi.react:jitsi-meet-sdk:8.6.1`

**Comment by Ahmad-Mustafaa** [comment]
I create own enum for this and it worked.
```
public static class BroadcastAction {
        public static enum Type {
            SET_AUDIO_MUTED("org.jitsi.meet.SET_AUDIO_MUTED"),
            HANG_UP("org.jitsi.meet.HANG_UP"),
            SET_VIDEO_MUTED("org.jitsi.meet.HANG_UP"),
            ;
            private final String action;

            Type(String action) {
                this.action = action;
            }

            public String getAction() {
                return action;
            }
            }
    }
```

**Comment by Ahmad-Mustafaa** [comment]
Is there any event for Audio Source ? If i want to switch form Speaker to Ear OR ear to speaker using my own activity buttons ? because in doc i didn't found.

**Comment by saghul** [comment]
There isn't.

**Comment by Ahmad-Mustafaa** [comment]
Thanks for you reply .Is there any possibility for showing only Audio button UI from jitsi disable else like i already said that i have disabled toolbar and all other stuff . I just want to Visible the jitsi Audio button. Because there is by default it speaker is selected so Audio call on speaker for user is not making sense. Is there any possibility i can do that i am trying to do. Any solution is appreciable because im really stuck just at the end . Thanks

**Comment by saghul** [comment]
I think the level of customization you require can only currenrtly be attained by modifying the code (yourself) and rebuilding the SDK.

**Comment by Ahmad-Mustafaa** [comment]
Thats sad for me . This is the only Requirement left and whole sdk custom for this is too much and time taken i guess for me. And also default Audio selection is Speaker if it was EarPhone it may work for my scenario . For SDK it cannot be customize on Windows PC also 
I also `setAudioOnly : true` but audio is on speaker. There is not broadcast for speakers at all. I think with this flag audio should not be on speaker
