### ISSUE TITLE
Build error on android when trying to use 9.0.0

### ISSUE THREAD

**Issue by Aykan125** [jitsi/jitsi-meet#14404]
### Description:
Failed to resolve: org.jitsi.react:jitsi-meet-sdk:9.0.0
### Steps to reproduce:

Sync Gradle files after editing the line and changing it to implementation('org.jitsi.react:jitsi-meet-sdk:9.0.0') { transitive = true }
Then you get the warning Failed to resolve: org.jitsi.react:jitsi-meet-sdk:9.0.0

### Expected behavior:

9.0.0 should be downloaded

### Actual behavior:

Project does not run
<img width="1249" alt="problemJitsi" src="https://github.com/jitsi/jitsi-meet/assets/63281684/80ee0820-dffc-48aa-b4d6-57a47eda1260">

### Server information:
Android Studio Hedghog stable version
Windows 10
Jitsi meet version 9.0.0

### Client information:
Android API level 30
Android 11
### Additional information:
Also Jitsi is not working on API level 34, was wondering if this was the cause?
The button for PiP while share screening is also not working, was wondering if this was the cause as well?

**Comment by saghul** [comment]
9.0.0 has not been released yet.

**Comment by Aykan125** [comment]
Oh my bad then, where can I find the list of released versions? I thought 9.0.0 was out because the release page has 9.0.0 on it.

**Comment by saghul** [comment]
The tags are not linked because the release hasn't happened yet. The notes went out early by mistake.

We hope to make it really soon.

**Comment by Aykan125** [comment]
Ah, thanks for you help.
