### ISSUE TITLE
Recording is not working in some jitsi meet

### ISSUE THREAD

**Issue by Jagroop-RTE** [jitsi/jitsi-meet#14411]
We are having trouble with jitsi since it does not create records for some jitsi meetings. For those whose recording is not generated, gives the error of : 
`Conference is not defined.`
You can refer to the screenshot below for more clarity: 
![jistimeetrecissue](https://github.com/jitsi/jitsi-meet/assets/122356764/eceea901-be2b-48f3-b213-133489f2d265)

In Jibri we get `isJibri=False` for those meetings.

We also attempted many approaches to fix this, however they did not work.
How can we resolve this bug?
**Here are some details concerning our jitsi:** 
![jitsiversions](https://github.com/jitsi/jitsi-meet/assets/122356764/2301e3fa-377a-4fb5-97b1-87d137f4a757)

**Comment by saghul** [comment]
Do you have the full Jibri logs?

**Comment by Jagroop-RTE** [comment]
@saghul , here it is : 
[RZQNZBdJtFmKsHgKt_logs.csv](https://github.com/jitsi/jitsi-meet/files/14416376/RZQNZBdJtFmKsHgKt_logs.csv)

**Comment by saghul** [comment]
Weird, I see no jibri logs there at all. Also I see some Jigasi joining, but not jibri.

**Comment by Jagroop-RTE** [comment]
We only got the following logs about Jibri. I believe it is not invoked or something like that : 
![MicrosoftTeams-image](https://github.com/jitsi/jitsi-meet/assets/122356764/1ee30582-d026-487f-ac5a-cb4e9fbf15fc)

**Comment by saghul** [comment]
You should check the logs that the actual Jibri process generates.

**Comment by Jagroop-RTE** [comment]
@saghul , here it is : 
[jibri-logs.log](https://github.com/jitsi/jitsi-meet/files/14418981/jibri-logs.log)

**Comment by saghul** [comment]
I see Jibri lost connection to the XMPP server a number of times, otherwise a couple of recordings seem to have happened. There should be 2 other log files: browser and ffmpeg. Can you please attach both?

**Comment by Jagroop-RTE** [comment]
@saghul ,
here it is : 
[Jibri_browsers.zip](https://github.com/jitsi/jitsi-meet/files/14429880/Jibri_browsers.zip)
[jibri_ffmpeg.zip](https://github.com/jitsi/jitsi-meet/files/14429881/jibri_ffmpeg.zip)

**Comment by saghul** [comment]
The logs you sent are not for the domain in the pictures. In the logs I see recording worked. Can you see a pattern, in the cases it fails?

**Comment by karun-dhir** [comment]
Main domain jitsi is getgeeker.com and logs are also pointing to this domain, But it is binded with meeting.geeker.co, which you can ignore.

The pattern when recording not created, We have noticed is that 
1. On fronted, We are getting "Conference is not defined" Error.
2. On Jitsi logs, We are getting "isJibri : False".

**Comment by Jagroop-RTE** [comment]
> Main domain jitsi is getgeeker.com and logs are also pointing to this domain, But it is binded with meeting.geeker.co, which you can ignore.
> 
> The pattern when recording not created, We have noticed is that
> 
> 1. On fronted, We are getting "Conference is not defined" Error.
> 2. On Jitsi logs, We are getting "isJibri : False".

@saghul

**Comment by saghul** [comment]
Do all jibris have the same configuration? Please do share it.

**Comment by karun-dhir** [comment]
Yes, all jibri's have same recording. Please see attached files.
[jibri-configs.zip](https://github.com/jitsi/jitsi-meet/files/14477995/jibri-configs.zip)

**Comment by karun-dhir** [comment]
Hi @saghul,
Same thing happened again, no recording created by jitsi.
Any update on it, or you need more information or latest logs?

**Comment by saghul** [comment]
I see all your jibris have no ID set, it's just the empty string. Please set it to something unique.
