### ISSUE TITLE
Problem share screen with LibreOffice + FireFox + Windows 7

### ISSUE THREAD

**Issue by JFMALBI** [jitsi/jitsi-meet#1442]
Using https://meet.jit.si
When I want to share a LibreOffice window with FireFox on Windows 7, I've got  a flashing screen
I've ugraded FF and  LibreOffice version and have same issue
With Acrobat Reader or Wordpad windows, the shared screen is OK 

When I try on an Ubuntu desktop with Firefox and LibreOffice :  the shared screen is OK. No flashing

I have tried also with my own jitsi-meet server and have the same issue

**Comment by saghul** [comment]
Hard to say, but it looks like it might be a problem in Firefox's screen capturer. Not sure what we can do here...

**Comment by JFMALBI** [comment]
You're right 

I've tested with https://mozilla.github.io/webrtc-landing/gum_test.html and i get the same issue if I use the Windows share. 
When I use Screen share, all is OK. 

Do you think we could expect that FF Screen Share (vs window share) will be implemented in jitsi-meet ? 

PS : I've posted au bug in Bugzilla : Bug 1351597 

Regards 

Jean-François MARTEL 
Directeur des Systèmes d'Information 

Direction Système d'Information - Mairie d'Albi 
tel : 05 63 49 13 78 
fax: 05 63 49 10 50 
jean-francois.martel@mairie-albi.fr 

----- Mail original -----

**Comment by saghul** [comment]
Thanks for the feedback! I'm afraid we currently don't have it in the roadmap, but let's keep this open, so we can come back to it.
