### ISSUE TITLE
Language not being detected in Chromium browsers

### ISSUE THREAD

**Issue by Elaborendum** [jitsi/jitsi-meet#14432]
### Description:

Currently, meet.jit.si and other instances hosting what I presume is the same version, don't seem to be able to detect the browser language in most chromium based browsers, defaulting to english instead.

### Steps to reproduce:

1. On Google Chrome, set the browser language to (for example) Spanish
2. Go to meet.jit.si
3. See that the site stays in english, having to manually set it to Spanish

Repeating the process on Firefox does result in the site changing to Spanish

### Expected behavior:

The site should change to the browser's language.

### Actual behavior:

The site defaults to english in Chromium browsers.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Google Chrome, Brave, Microsoft Edge
- Operating System: Windows 10

### Additional information:

It only seemed to work properly in Vivaldi

**Comment by saghul** [comment]
What does navigator.language return on your browser? (Open a JS console)

**Comment by saghul** [comment]
@damencho any ideas?

**Comment by saghul** [comment]
That wouldn't explain why it's detected in some browsers and not in others...

**Comment by saghul** [comment]
You fied this recently, right @damencho ?

**Comment by damencho** [comment]
Yep
