### ISSUE TITLE
website navbar is not responsive for mobile

### ISSUE THREAD

**Issue by rahulX001** [jitsi/jitsi-meet#14430]
Navbar is not responsive, due to that horizontal scroll is coming for all devices with width lass then 320 px.
I can fix this issue if you will assign this issue to me

**Comment by ansar062** [comment]
You can't fix your own problems

**Comment by saghul** [comment]
You are welcome to send a PR!

Can you share a screenshot of the problem?

**Comment by rahulX001** [comment]
white space is there in right of device
this is the screenshot 
![jisti](https://github.com/jitsi/jitsi-meet/assets/110256609/690478b9-1d78-4612-8af0-f3cfff8bf4db)

**Comment by saghul** [comment]
Ah, I see. Alas that is a wordpress install and the repo is not public.

**Comment by rahulX001** [comment]
missed it
