### ISSUE TITLE
App.bundle.min.js file missing from libs folder.

### ISSUE THREAD

**Issue by brijesh231199** [jitsi/jitsi-meet#14439]
I am changing in welcome page and after run make dev command, don't show app.bundle.min.js file in libs folder.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
make dev does not build app.bundle.min file. Mind that when using `make dev` it uses index.html from the deployment not from local sources.

**Comment by brijesh231199** [comment]
@damencho 
Can you guide me how to generate app.bundle.min.js file from local source. when i run make command its generating?

**Comment by saghul** [comment]
Yes, running make will build the app.

**Comment by brijesh231199** [comment]
@damencho 
Let suppose I am comment  footer code in welcom page after run in local its working good. Then I am running make command and generate app.bundle.min file above changes not reflected in app bundle file.

**Comment by saghul** [comment]
You might be looking at a cached version. Did you check visiting the page in incognito mode?

**Comment by brijesh231199** [comment]
@saghul Resolved my issue, thank for the supporting.

**Comment by brijesh231199** [comment]
@saghul @damencho 
How to disable info log from jitsi web, jicofo, jibri, jigasi repo in local environment?
