### ISSUE TITLE
RCTVideoView setOnClick Error - React-Native 0.73 (iOS only, not Android)

### ISSUE THREAD

**Issue by jplandry908** [jitsi/jitsi-meet#14441]
After upgrading to React-Native 0.73.* an exception is thrown within iOS when trying to join a conference. Android appear to be working correctly.

![image](https://github.com/jitsi/jitsi-meet/assets/14008273/cd60b519-9c33-42fd-9b2c-343591ef7c20)

**Comment by saghul** [comment]
We don't support RN 0.73 yet, so use it at your own peril.

**Comment by tswiejkowski** [comment]
Similar issue: https://github.com/rive-app/rive-react-native/pull/215

[react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) may not be fully compatible with rn73. 
Possible fix: 
RTCVideoViewManager.m (react-native-webrtc)
Add #import <React/RCTView.h>
Replace UIView by RCTView

**Comment by sunil-digimantra** [comment]
> Similar issue: [rive-app/rive-react-native#215](https://github.com/rive-app/rive-react-native/pull/215)
> 
> [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) may not be fully compatible with rn73. Possible fix: RTCVideoViewManager.m (react-native-webrtc) Add #import <React/RCTView.h> Replace UIView by RCTView

Thanks @tswiejkowski it's working for me.

**Comment by diovanedm** [comment]
> Similar issue: [rive-app/rive-react-native#215](https://github.com/rive-app/rive-react-native/pull/215)
> 
> [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) may not be fully compatible with rn73. Possible fix: RTCVideoViewManager.m (react-native-webrtc) Add #import <React/RCTView.h> Replace UIView by RCTView



> Similar issue: [rive-app/rive-react-native#215](https://github.com/rive-app/rive-react-native/pull/215)
> 
> [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) may not be fully compatible with rn73. Possible fix: RTCVideoViewManager.m (react-native-webrtc) Add #import <React/RCTView.h> Replace UIView by RCTView

Thanks, it's working for me
