### ISSUE TITLE
Problems with Quick install

### ISSUE THREAD

**Issue by ttjaden** [jitsi/jitsi-meet#1444]
I have problems with the QuickInstall.
Ubutnu Server 16.04. LTS with nginx

The first time I installed I choosed the Option with my own Certs-Files by mistake and cancelled the installation within the process. The i removed "apt-get -y purge jitsi-meet" and made a second try with "apt-get -y install jitsi-meet". But then i wasn't asked anymore.

The Problem with the deinstallation with "apt-get purge jitsi-meet jicofo jitsi-videobridge" is that when doing "apt-get autoremove" afterwards the deinstallation of  "jitsi-meet-web-config" fails with an error.

So the question is the a possibility to run the graphical configuration (FQHN and Certificate) by terminal account again? Or second: How to purge completely the whole installation?

**Comment by saghul** [comment]
Try this and start from scratch: `sudo apt purge $(dpkg -l | grep -i jitsi | awk '{ print $2 }')`

**Comment by damencho** [comment]
When having questions or problems can you first write to the mailinglist, before opening issues.

Normally if I want to purge all I do
`apt-get --purge remove jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jicofo jitsi-videobridge`.
When you have packages installed run this command, if you still have an error paste it here to be able to help.

@saghul your command will not purge jicofo. And also jicofo and jitsi-videobridge should be last or I have seen some errors when doing it...

**Comment by ttjaden** [comment]
@damencho The deinstallation fails
`apt-get --purge remove jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jicofo jitsi-videobridge
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  authbind ca-certificates-java default-jre-headless java-common liblcms2-2 libnspr4 libnss3 libnss3-nssdb
  lua-event lua-expat lua-filesystem lua-sec lua-socket lua5.1 openjdk-8-jre-headless prosody
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden Pakete werden ENTFERNT:
  jicofo* jitsi-meet* jitsi-meet-prosody* jitsi-meet-web* jitsi-meet-web-config* jitsi-videobridge*
0 aktualisiert, 0 neu installiert, 6 zu entfernen und 0 nicht aktualisiert.
2 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 102 MB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] j
(Lese Datenbank ... 202693 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von jitsi-meet (1.0.1622-1) ...
Löschen der Konfigurationsdateien von jitsi-meet (1.0.1622-1) ...
Entfernen von jitsi-meet-web-config (1.0.1592-1) ...
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "reload" failed.
dpkg: Fehler beim Bearbeiten des Paketes jitsi-meet-web-config (--purge):
 Unterprozess installiertes post-removal-Skript gab den Fehlerwert 1 zurück
Entfernen von jitsi-meet-prosody (1.0.1592-1) ...
Löschen der Konfigurationsdateien von jitsi-meet-prosody (1.0.1592-1) ...
Entfernen von jicofo (1.0-320-1) ...
Löschen der Konfigurationsdateien von jicofo (1.0-320-1) ...
Entferne Benutzer »jicofo« ...
Warnung: Die Gruppe »jitsi« hat keine Mitglieder mehr.
Fertig.
Entfernen von jitsi-meet-web (1.0.1592-1) ...
Entfernen von jitsi-videobridge (879-1) ...
Löschen der Konfigurationsdateien von jitsi-videobridge (879-1) ...
Entferne Benutzer »jvb« ...
Warnung: Die Gruppe »jitsi« hat keine Mitglieder mehr.
Fertig.
Fehler traten auf beim Bearbeiten von:
 jitsi-meet-web-config
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by damencho** [comment]
May German is not fluent :) but can you follow these steps and paste the result: 
See "systemctl status nginx.service" and "journalctl -xe" for details.
Maybe if you delete the nginx config for jitsi-meet purge will work, just a guess as nginx is the one complaining and jitsi-meet-web-config fails, cause it depends on reloading nginx.
You need to fix this command to pass: $ service nginx reload

**Comment by ttjaden** [comment]
Tanks! The Problem with nginx was:
`nginx[28126]: nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/nginx.conf:63
`
I commented it out and then the purge worked. The new installation also worked and within that, I chosed fs-meeting.f1.htw-berlin.de as FQHN and choosed to generate self-signed certs.

Now JITSI MEET is working. So the next steps would be to change the SSL-Certs by letsencrypt SSL-Certs. I generated the certs a few days ago and now changed the *.conf file to this one

`erver_names_hash_bucket_size 64;

server {
    listen 80;
    server_name fs-meeting.f1.htw-berlin.de;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name fs-meeting.f1.htw-berlin.de;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!M$

    add_header Strict-Transport-Security "max-age=31536000";

    #ssl_certificate /etc/jitsi/meet/fs-meeting.f1.htw-berlin.de.crt;
    #ssl_certificate_key /etc/jitsi/meet/fs-meeting.f1.htw-berlin.de.key;
    ssl_certificate /etc/letsencrypt/live/fs-meeting.f1.htw-berlin.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fs-meeting.f1.htw-berlin.de/privkey.pem;


    root /usr/share/jitsi-meet;
    index index.html index.htm;
    error_page 404 /404.html;

    location /config.js {
        alias /etc/jitsi/meet/fs-meeting.f1.htw-berlin.de-config.js;
    }

    location ~ ^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }

    location / {
        ssi on;
    }

    # Backward compatibility
    location ~ /external_api.* {
        root /usr/share/jitsi-meet/libs;
    }

    # BOSH
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }
}
`
But then I get an error: NET::ERR_CERT_AUTHORITY_INVALID

**Comment by damencho** [comment]
Works fine here, I see your certificate ok.

**Comment by ttjaden** [comment]
Tanks a lot. Must have been the browser cache. I Firefox it works but in Chrome there is still an Cert-Error. Despite of that: 
Where I find information on howto:
-- secure the app with login
-- enable screen sharing
-- shared notes

P.s. Perhaps a recent example nginx conf-File would be reat to find out, why chrome has an error about the SSL-Cert.

Tanks a lot!

**Comment by damencho** [comment]
For authentication take a look: https://github.com/jitsi/jicofo#secure-domain
For screensharing: https://github.com/jitsi/jidesha/tree/master/chrome for chrome, for newer FF versions (52+) you do not need anything, for older you can create an extension again take a look at jidesha project.
For shared document, there is no documentation, you just need to install etherpad and set its link to access it in config.js.
