### ISSUE TITLE
When i joined the conference with same internet connection it worked otherwise mic and video muted

### ISSUE THREAD

**Issue by Ahmad-Mustafaa** [jitsi/jitsi-meet#14454]
I am using android SDK for call purposes. here is my conf setting which i am using while connecting conference
```
JitsiMeetConferenceOptions options = null;
        try {
            options = new JitsiMeetConferenceOptions.Builder()
                    .setServerURL(new URL(room))
                    .setRoom(String.valueOf(callHash))
                    .setFeatureFlag("chat.enabled",false)
                    .setFeatureFlag("invite.enabled",false)
                    .setFeatureFlag("pip.enabled", false)
                    .setFeatureFlag("add-people.enabled",  false)
                    .setFeatureFlag("raise-hand.enabled", false)
                    .setFeatureFlag("settings.enabled", false)
                    .setFeatureFlag("breakout-rooms.enabled", false)
                    .setFeatureFlag("notifications.enabled", false)
                    .setFeatureFlag("overflow-menu.enabled", false)
                    .setFeatureFlag("recording.enabled", false)
                    .setFeatureFlag("meeting-name.enabled", false)
                    .setFeatureFlag("welcomepage.enabled", false)
                    .setFeatureFlag("unsaferoomwarning.enabled", false)
                    .setFeatureFlag("audio-only.enabled", true)

                    .setFeatureFlag("fullscreen.enabled", false)
                    .setFeatureFlag("filmstrip.enabled", false)
                    .setFeatureFlag("tile-view.enabled", true)
                    .setAudioMuted(false)
                    .setAudioOnly(true)
                    .setToken(jwtHash)
                    .setFeatureFlag("prejoinpage.enabled", false)
                    .setConfigOverride("requireDisplayName", false)
                    //.setConfigOverride("startAudioOnly", true)
                    .build();
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
        view.join(options);
```

### Description:

When i joined the conference with same internet connection (Android SDK) it worked otherwise mic and video muted and i am unable to enable them

### Steps to reproduce:

Create Custom Server (JWT enabled)
Join using android sdk with above options 

### Expected behavior:

Should allow to enable disable mic 

### Actual behavior:

When call join permanently disabled both mic and video (I m not using video audio only) 
### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

```
Sdk version 
implementation("org.jitsi.react:jitsi-meet-sdk:+") {
        isTransitive = true
    }
```

**Comment by damencho** [comment]
What deployment is this using? Does it work if you open 3 tabs in the browser?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by Ahmad-Mustafaa** [comment]
> What deployment is this using? Does it work if you open 3 tabs in the browser?

No its not working. What i tried 
---------------For Different WIFI--------------
I tried on multiple tabs on same pc (not work)
I tried of Different Pc's and android (not work)
Audio video not work but it shows user joined but mic icon automatically toggled between mute/unmute 
----------------Same WIFI-------------------
It worked on same wifi Audio video both.

**Comment by saghul** [comment]
Looks like port 10000 is not properly open / forwarded on your setup.

**Comment by Ahmad-Mustafaa** [comment]
> Looks like port 10000 is not properly open / forwarded on your setup.

Yup Thanks . It was the Port 10000 Issue from the portal it self actually. We also need to enable it from the VM setting by provider as well
