### ISSUE TITLE
Android, jitsi version 9.0.0, Failed to resolve: com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.3.3

### ISSUE THREAD

**Issue by Aykan125** [jitsi/jitsi-meet#14458]
When I try to do gradle sync after changing jitsi to 9.0.0, I get this error 
![image](https://github.com/jitsi/jitsi-meet/assets/63281684/c849b626-bc48-4171-bee8-d1f1446ae823)

And then when building it seems it is required as I get this error:
![image](https://github.com/jitsi/jitsi-meet/assets/63281684/6fdaed31-31ba-4447-b1d4-2451232e40a2)

I'm using android studio Iguana. Gradle version 8.3.0

**Comment by saghul** [comment]
What maven repos do you have?

**Comment by pelpanagiotis** [comment]
I face the same issue for a couple of days now

**Comment by saghul** [comment]
Make sure the jitpack maven repo is in your config.

**Comment by pelpanagiotis** [comment]
Thanks @saghul, i used your tip, and the issue is fixed, maybe it will help avoid confusion, if you included the line for the Jitpack Maven Repo inside the settings.gradle code snippet, for the recent versions of Android Studio

**Comment by saghul** [comment]
It's already there: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#use-pre-build-sdk-artifactsbinaries

**Comment by Aykan125** [comment]
Ah thank you, I was putting jitpack in my build.gradle not settings.gradle.
