### ISSUE TITLE
Option to define the duration of session vailidity or refresh period for self-hosted instances

### ISSUE THREAD

**Issue by BreakfastSerial** [jitsi/jitsi-meet#14456]
**Is your feature request related to a problem you are facing?**

The _problem_ is concerning the usability of the self-hosted Jitsi server. The short-lived sessions require us to authenticate approximately every other day.

**Describe the solution you'd like**

For self-hosted instances of Jitsi, I'd love to have the option to define how long a session should remain valid or can be refreshed without requiring a login.

**Describe alternatives you've considered**

I haven't considered alternatives, as Jitsi is our alternative to other to common web meeting solutions, that can't be self-hosted. The alternative is to live with the behavior and re-login every other day or so.
I couldn't find any option to define this as an application administrator.

**Comment by saghul** [comment]
Hey there!

Not sure what you mean. For self-hosted instances we impose no limits on authentication. What you see on meet.jit.si does not apply to self-hosted.

**Comment by BreakfastSerial** [comment]
Thank you for the feedback. Maybe I wasn't quite clear. We self-host our own Jitsi server.

I can log-in as a moderator just fine and everything works as expected. However, this session, where I am logged in with my moderator account will only stay valid for a couple of days. Afterwards I have to log-in again to start a meeting.

I am looking for an option, to define a time frame (e.g. one month) during which my session will stay valid and I don't have to log-in again. Unless of course I clear my browser caches/storage or log out explicitly.

**Comment by saghul** [comment]
Ah, right! There is a setting for that. Check `authentication-lifetime` in the `authentication` section in Jicofo's config file.

**Comment by BreakfastSerial** [comment]
Thank you, I must have overlooked that.

**Comment by saghul** [comment]
No sweat, we have a million settings 😅
