### ISSUE TITLE
Install fail! Error: [@jitsi/excalidraw@https://github.com/jitsi/excalidraw/releases/download/v0.0.16/jitsi-excalidraw-0.0.16.tgz] read ECONNRESET

### ISSUE THREAD

**Issue by woaini521** [jitsi/jitsi-meet#14467]
when npn install 
![image](https://github.com/jitsi/jitsi-meet/assets/38653546/90a12e44-b5be-48cc-8331-d5d7064cd2aa)
![image](https://github.com/jitsi/jitsi-meet/assets/38653546/eb8e532c-ade9-4db8-a126-e1bebb96a80d)

**Comment by saghul** [comment]
What Node / npm version are you using?

**Comment by woaini521** [comment]
> What Node / npm version are you using?
node -v 16.12.0
npm -v  8.1.0
