### ISSUE TITLE
 Screen share issue in Android 13 & 14.Using Jitsi 9.0.0 

### ISSUE THREAD

**Issue by shubham7111999** [jitsi/jitsi-meet#14463]
Recently I update the Jitsi version 9.0.0 now the Screen sharing is working randomly in android 13 & 14 .Please help me how to resolve this .

**Comment by saghul** [comment]
We need more details. What is "randomly"? Please provideo logcat logs.

**Comment by shubham7111999** [comment]
"Randomly" mean sometime It is working or some time it is not working when I stop and start to share the screen in room .

**Comment by shubham7111999** [comment]
Here is my Logs -->

**Comment by saghul** [comment]
Interesting.

The problem seems to be in in the UVC camera enumerator, which is a recent addition.

Is that all you get? There is nothing related to screen sharing there.

**Comment by shubham7111999** [comment]
but how when  were using compile SDK 33 with jitsi version 8.6.1 Screen share were working properly , when compile Sdk upgrade to 34 &  Jitsi version 9.0.0 it stops working

**Comment by shubham7111999** [comment]
what is it mean I not able to understant.Please  let me know is I need to do changes in my project or your team is working on this issue?

**Comment by saghul** [comment]
We are working on a fix.

**Comment by saghul** [comment]
I took a look and cannot reproduce the problem. The exception about UVC cameras is not fatal. I will fix that, but I see no problem with screen sharing. Tested both Android 13 and 14.

**Comment by shubham7111999** [comment]
but @saghul I not able to understand whats the problem . Can you help me to tell what is Android configuration required by jitsi version 9.0.0

**Comment by shubham7111999** [comment]
Currenty i am using the  Jitsiview

**Comment by saghul** [comment]
I don't understand what your problem is to begin with. "Screen sharing is working randomly" doesn't add much to it.

> Currently i am using the Jitsiview

That is not an API we encourage people to use. You should try to use JitsiMeetActivity instead.

**Comment by shubham7111999** [comment]
but my requirment is jitsiview so i able to customize the screen and controls

**Comment by Ewrei** [comment]
Has this problem been fixed? I also encounter this problem on Samsung S23

**Comment by saghul** [comment]
Yes, you need version 9.2.2.

**Comment by saghul** [comment]
Hum, I'll double check. At any rate the artifacts are there in our maven repo.

**Comment by saghul** [comment]
Here is the proper link, we'll fix it in the release notes: https://github.com/jitsi/jitsi-meet/releases/tag/android-sdk-9.2.2
