### ISSUE TITLE
CallKit sets previous meeting's title in Dynamic Island and Call History

### ISSUE THREAD

**Issue by sultanalmukhan** [jitsi/jitsi-meet#14461]
CallKit sets previous meeting's title in Dynamic Island and Call History

**Comment by saghul** [comment]
Can you show how you are calling the SDK?

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/commit/3d158fb2b451b189a1d92a039e1388da2a62850f
