### ISSUE TITLE
[RN] TypeError: Illegal invocation in debug mode 

### ISSUE THREAD

**Issue by huy-lv** [jitsi/jitsi-meet#14477]
### Description:

It run very smooth on normal mode, but got this error in debug mode

### Steps to reproduce:

1. create new project using react-native-cli, version 0.70.6
2. install @jitsi/react-native-sdk 2.0.2, install peer dependencies
3. render normal jitsi room, it work fine in non-debug mode
4. in console, press D to open developer menu
5. select `Debug` in developer menu
6. log start showing in chrome -> TypeError: Illegal invocation

Use can checkout code here: https://github.com/huy-lv/newproject0_70_6

### Actual behavior:

<img width="712" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/7688070/42cd941b-68b1-44d5-9031-eb0e0621bc84">

### Server information:

using https://meet.jit.si

### Client information:

- Jitsi Meet version: 2.0.2
- Operating System: MacOS 14.0
- RN 0.70.6, hermes enabled
- Node 18.17.1

**Comment by saghul** [comment]
Our SDK uses RN 0.72 and we have not tested Hermes. We have received reports indicating it doesn't work out of the box.

**Comment by huy-lv** [comment]
Thanks for your advice. 
In my company project(not the above one), I have installed @jitsi/react-native-sdk 2.0.2, in react native 0.70.6, hermes disabled, and got this error when navigate to jitsi call:
```
03-13 19:31:27.145 11353 11353 F DEBUG   : Build fingerprint: 'google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.220630.001.A1/9056438:userdebug/dev-keys'
03-13 19:31:27.145 11353 11353 F DEBUG   : Revision: '0'
03-13 19:31:27.145 11353 11353 F DEBUG   : ABI: 'arm64'
03-13 19:31:27.145 11353 11353 F DEBUG   : Timestamp: 2024-03-13 19:31:26.866022913+0700
03-13 19:31:27.145 11353 11353 F DEBUG   : Process uptime: 0s
03-13 19:31:27.145 11353 11353 F DEBUG   : Cmdline: com.myproject.dev
03-13 19:31:27.145 11353 11353 F DEBUG   : pid: 11210, tid: 11299, name: mqt_js  >>> com.myproject.dev <<<
03-13 19:31:27.145 11353 11353 F DEBUG   : uid: 10160
03-13 19:31:27.145 11353 11353 F DEBUG   : tagged_addr_ctrl: 0000000000000001
03-13 19:31:27.145 11353 11353 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa
03-13 19:31:27.145 11353 11353 F DEBUG   : Cause: null pointer dereference
03-13 19:31:27.145 11353 11353 F DEBUG   :     x0  0000000000000000  x1  0000006e4bc83b00  x2  0000000000000000  x3  0000000000000001
03-13 19:31:27.145 11353 11353 F DEBUG   :     x4  0000006e1e082848  x5  0000000000000000  x6  00000000ffffffff  x7  9100007f35ffffa1
03-13 19:31:27.145 11353 11353 F DEBUG   :     x8  0000006e07c96b60  x9  0000000000000000  x10 0000000000000000  x11 000000000000006e
03-13 19:31:27.145 11353 11353 F DEBUG   :     x12 0000006e12f2bc80  x13 f8616be2d1002021  x14 0000000000000001  x15 00000000a339faff
03-13 19:31:27.145 11353 11353 F DEBUG   :     x16 0000006e4c2d53d8  x17 00000071728523cc  x18 0000006e1d546000  x19 0000006e4c2de680
03-13 19:31:27.145 11353 11353 F DEBUG   :     x20 0000006e07cd9a10  x21 0000006e12f2b888  x22 0000006e12f2b88c  x23 00000064e7a61480
03-13 19:31:27.145 11353 11353 F DEBUG   :     x24 0000006e07cdb230  x25 0000000000000000  x26 0000000014000000  x27
```
Have you ever see that

**Comment by saghul** [comment]
Is that a simulator? We recommend testing with a real device.

Also note your RN version doesn't match the one we use or test with.

**Comment by huy-lv** [comment]
Thank you very much, it works fine on real device :D
