### ISSUE TITLE
Speed up the initialization process for a meeting with hundreds of participants

### ISSUE THREAD

**Issue by NimbleDev** [jitsi/jitsi-meet#14483]
### Description:

For a meeting with hundreds of participants, when a new participant joins the meeting, he/she has to wait quit a long time (over 1 minute, for some users even serveral minutes) as the app has to load all participants' information one by one thru the xmpp-websocket connection.

Is there any configuration that can speed up this initialization process?

**Comment by saghul** [comment]
Is this on web or mobile?
