### ISSUE TITLE
Joining a breakout room with JWT authentication enabled AND command:joinBreakoutRoom is not possible

### ISSUE THREAD

**Issue by ag4u** [jitsi/jitsi-meet#14482]
### Description:

With JWT authentication enabled and "api.executeCommand('joinBreakoutRoom' ..." it is not possible to join breakout room as moderator - access is denied.

### Steps to reproduce:

1. Start the conference with JWT token (you get the moderator role)
2. Create a new breakout room
3. Get id by api.listBreakoutRooms()
4. Join the breakout room via api.executeCommand('joinBreakoutRoom', id)
5. Get "Sorry! You are not allowed to be here" page

### Expected behavior:

The user should join the breakout room with moderator role.

### Actual behavior:

I suspect, that breakout room tries to validate JWT and validation fails, because "room" claim doesn't match name of the breakout room. BUT if you click "Join" at breakout room, it works. It only fails when using the joinBreakoutRoom command!
There was a similar problem fixed here: https://github.com/jitsi/jitsi-meet/issues/11075 .

### Server information:

Jitsi Meet version: stable-9258
Operating System: Ubuntu 20.04

**Comment by atz3n** [comment]
same issue here :)

**Comment by damencho** [comment]
Do you reproduce this if trying to join the breakout room through the UI?

**Comment by damencho** [comment]
@ag4u @atz3n 
Do you have "token_verification" enabled under the breakout room muc component in your prosody config?

**Comment by ag4u** [comment]
Hey @damencho, thanks for the reply. We have only the entry of "token_verification" in >Component "muc.meet.jitsi" "muc"<. By clicking JOIN it works as expected, but with the command >joinBreakoutRoom< it seems, that there is a token_verification in the background.

**Comment by damencho** [comment]
> By clicking JOIN it works as expected, but with the command >joinBreakoutRoom< it seems, that there is a token_verification in the background.

Well, if the module is not loaded, there is nothing to verify the room from the token. What error do you see in prosody when this happens? What error do you see in the js console?

**Comment by ag4u** [comment]
command `.executeCommand('joinBreakoutRoom', '633ee655-bef9-430a-ae7a-5512aaad7ac8');` (roomId)
[console.txt](https://github.com/jitsi/jitsi-meet/files/14749130/console.txt)
[prosody.txt](https://github.com/jitsi/jitsi-meet/files/14749131/prosody.txt)
![websocket_and_screenshot](https://github.com/jitsi/jitsi-meet/assets/109415612/83b46c02-ad5e-4c46-9667-4e81da43770b)

**Comment by ag4u** [comment]
more beautiful console view :)
![console](https://github.com/jitsi/jitsi-meet/assets/109415612/cf33fef8-1158-4148-8bd7-f7e98c73bd2e)

**Comment by ag4u** [comment]
@damencho i found a workaround :D i can send myself into other rooms without problems `.executeCommand('sendParticipantToRoom', '12f32984-3a88-4394-9cd4-f5401d56aa9e@meet.jitsi/18cKeTNK50Dn', '82d561ba-71be-53db-afb3-2ea230d01b71');`

**Comment by ag4u** [comment]
**and the documentation is wrong**
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands/#sendparticipanttoroom
it should be participantJid instead of participantId

**Comment by damencho** [comment]
> command `.executeCommand('joinBreakoutRoom', '633ee655-bef9-430a-ae7a-5512aaad7ac8');` (roomId)

I think, that is the problem. It should be '633ee655-bef9-430a-ae7a-5512aaad7ac8@breakout.meet.jitsi'.

I will check those and correct it if needed.

**Comment by damencho** [comment]
It tries to join 633ee655-bef9-430a-ae7a-5512aaad7ac8@muc.meet.jitsi

**Comment by damencho** [comment]
> @damencho i found a workaround :D i can send myself into other rooms without problems `.executeCommand('sendParticipantToRoom', '12f32984-3a88-4394-9cd4-f5401d56aa9e@meet.jitsi/18cKeTNK50Dn', '82d561ba-71be-53db-afb3-2ea230d01b71');`

The docs are correct, it is just a workaround added that it will work and with jid.

**Comment by ag4u** [comment]
> > @damencho i found a workaround :D i can send myself into other rooms without problems `.executeCommand('sendParticipantToRoom', '12f32984-3a88-4394-9cd4-f5401d56aa9e@meet.jitsi/18cKeTNK50Dn', '82d561ba-71be-53db-afb3-2ea230d01b71');`
> 
> The docs are correct, it is just a workaround added that it will work and with jid.

sure? if i try with id, i get this `Could not find participant 8bc936a7`

**Comment by damencho** [comment]
interesting, I will test those, thanks

**Comment by ag4u** [comment]
solved
