### ISSUE TITLE
Screen Sharing and Participant Removal Causes Duplicate Participant Display

### ISSUE THREAD

**Issue by silencexw** [jitsi/jitsi-meet#14491]
## Environment:

* Operating System: Windows 11, version 22H2 (KB5034467), x64-based
* Browser: Microsoft Edge 122.0.2365.80 (Official build) (64-bit)
## issue Description:
When conducting a meeting with more than three participants on Jitsi Meet, we encountered an issue related to screen sharing and participant removal that results in an inconsistent participant display.

## Steps to Reproduce:

* Navigate to the Jitsi Meet official website and create a meeting with at least three participants.
* Have one participant share their screen.
* While screen sharing is active, have another participant remove the individual who is sharing their screen from the meeting.
* Observe the issue where "Fellow Jitster" is duplicated in the participant list, making it impossible to interact with these entries. Additionally, the participant counter shows four members, whereas only two icons are displayed.
![image](https://github.com/jitsi/jitsi-meet/assets/125251449/26d55e3b-3ec5-41ff-8fc0-4e28f7d7a51e)

## Expected Behavior:
Removing a participant who is sharing their screen should update the participant list and counters accurately without creating duplicate or inaccessible participant entries.
## Actual Behavior:
The participant list displays duplicate entries for "Fellow Jitster" that cannot be interacted with. The participant counter inaccurately reflects the number of participants compared to the displayed icons.

## Reproducibility:
This issue occurs under specific conditions as outlined in the steps above.

## Additional Information:

* This anomaly affects the user experience by presenting misleading information about meeting participation.
* No error messages were observed in the browser console when the issue occurred.

**Comment by saghul** [comment]
I have been unable to reproduce this on meet.jit.si, are you still able to?

**Comment by nitinkushwaha17** [comment]
Hey @saghul 
I was able to reproduce this bug

![Screenshot from 2024-03-21 02-48-30](https://github.com/jitsi/jitsi-meet/assets/79357960/e356c371-97a1-4894-92c8-413b8f5506d6)
<img src="https://github.com/jitsi/jitsi-meet/assets/79357960/2ad4debb-b455-41b5-9320-59b744e7a3c0" width=250>
<img src="https://github.com/jitsi/jitsi-meet/assets/79357960/90629406-b05c-47a1-b4b8-51f58e4ad4d2" width=250>

**Comment by saghul** [comment]
What steps did you follow?

**Comment by nitinkushwaha17** [comment]
@saghul I followed the same steps as listed in the issue

**Comment by saghul** [comment]
And does it reproduce every time?

**Comment by nitinkushwaha17** [comment]
@saghul Try this

1. Create a meet with at least 3 participants.
2. Have one of the participant **unmute** and **share their screen** simultaneously.
3. Any other participant removes the person who is sharing their screen from the participants pane.

This seems to reproduce the bug every time.

**Comment by saghul** [comment]
Sorry, I'm still unable to. Here is what I'm doing:

1. Have a meeting with 3 participants in it (1, 2 and 3). All have video.
2. Participant 3 starts sharing their screen.
3. Participant 1 kicks participant 3.

I'm using Chrome in this test.

**Comment by damencho** [comment]
@nitinkushwaha17 I followed the exact same steps and I cannot reproduce it. 
Can you get the javascript console logs from the client where you kick at the end and where you see the problem and upload them here?

**Comment by nitinkushwaha17** [comment]
[jitsi-console.log](https://github.com/jitsi/jitsi-meet/files/14720987/jitsi-console.log)

**Comment by damencho** [comment]
Yeah nothing in the logs. But in order to reproduce this you need to share tab, sharing the whole screen does not reproduce it. @saghul I was able to reproduce it ... strange and no errors or something.

**Comment by saghul** [comment]
Oh I wasn't aware of that, I always tried to share the whole screen!

**Comment by damencho** [comment]
Yep, interestingly the store has the correct remote participants in base/participants.

**Comment by damencho** [comment]
features/filmstrip remoteParticipants is the problem.
