### ISSUE TITLE
JitsiMeet build iOS causes Memory Leak in app.

### ISSUE THREAD

**Issue by hainhathoang1988** [jitsi/jitsi-meet#14493]
### Description:

I followed this guide https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#building-it-yourself to "build it yourself" Jitsimeet to use in iOS native app. Then after running, I found leaks related to Jitsi

### Steps to reproduce:

1. Build and integrate JitsiMeetSDK based on the guide on Jitsi Home page
2. Profile the app with Instruments and check Leaks
3. Observe

### Expected behavior:

No leaks related to JitsiMeet

### Actual behavior:

Have leaks related to JitsiMeet

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: JitsiMeet current latest release version (2.0.9258)
- Operating System: iOS 16.4.1

### Additional information:

Please refer to the screenshot, we don't have any "JavascriptCore" Library in app except Jitsimeet (since it's written in RN?)

![Screenshot 2024-03-18 at 17 03 44](https://github.com/jitsi/jitsi-meet/assets/156660619/74be5dae-da5a-4caf-963e-5fe5ee588993)

**Comment by saghul** [comment]
Yes, RN uses JSC. Unless the leaks grow over time, those should be harmless. We allocate an RN bridge, which has JSC and keep it around for as long as the app is running. Unless you destroy it manually, those resources will still be in use.

**Comment by hainhathoang1988** [comment]
> Yes, RN uses JSC. Unless the leaks grow over time, those should be harmless. We allocate an RN bridge, which has JSC and keep it around for as long as the app is running. Unless you destroy it manually, those resources will still be in use.

Thanks for your explanation.
