### ISSUE TITLE
How to build code jitsimeet affter update source code with target custom chat of it?

### ISSUE THREAD

**Issue by khaimp** [jitsi/jitsi-meet#14509]
I update code of jitsi and try build source with target custom chat it subrice my server (ws) , but when i run "make" it can't build . Thanks anything support me !
![image](https://github.com/jitsi/jitsi-meet/assets/108779587/9f9c7bfb-9352-4f47-9874-8aeade67b3a2)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Can you build it without modifications?

**Comment by damencho** [comment]
Discussing in the forum
