### ISSUE TITLE
jitsi-meet config to interact with rocketchat

### ISSUE THREAD

**Issue by mhenninghaus77** [jitsi/jitsi-meet#1450]
If i use the Default Server within rocketchat everything is working fine.
but if i use my own hosted jitsi-server nothing happens within rocketchat, the only Thing is see is the Default page from jitsi where i can specify a room Name.
Direct accessing jitsi-meet through a browser works fine.

**Comment by saghul** [comment]
I believe RocketChat uses the iframe API, so have you exposed external_api.js? Also, do you see any errors in the console?

**Comment by mhenninghaus77** [comment]
no, there are no errors

**Comment by mhenninghaus77** [comment]
mmmh, i see 

VM70:1 Uncaught SyntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at https://srvl043.ac.aixigo.de/utils.js?v=1:48:32
    at Array.forEach (native)
    at getConfigParamsFromUrl (https://srvl043.XXXX/utils.js?v=1:46:21)
    at Object.r.41../Util (https://srvl043.XXXXXX/libs/app.bundle.min.js?v=905:8:4032)
    at s (https://srvl043.XXXX/libs/app.bundle.min.js?v=905:1:614)
    at https://srvl043.XXXX/libs/app.bundle.min.js?v=905:1:665
    at Object.r.1../conference (https://srvl043.XXXXXXX/libs/app.bundle.min.js?v=905:1:1090)
    at s (https://srvl043.XXXXXXXX/libs/app.bundle.min.js?v=905:1:614)
    at e (https://srvl043.XXXXXXX/libs/app.bundle.min.js?v=905:1:785)

in developer Modus of chrome

**Comment by saghul** [comment]
do you override config options? can you paste your override objects?

**Comment by mhenninghaus77** [comment]
prosody config file:

-- Plugins path gets uncommented during jitsi-meet-tokens package install - that's where token plugin is located
--plugin_paths = { "/usr/share/jitsi-meet/prosody-plugins/" }

VirtualHost "srvl043.XXXXXX"
        -- enabled = false -- Remove this line to enable this host
        authentication = "anonymous"
        -- Properties below are modified by jitsi-meet-tokens package config
        -- and authentication above is switched to "token"
        --app_id="example_app_id"
        --app_secret="example_app_secret"
        -- Assign this host a certificate for TLS, otherwise it would use the one
        -- set in the global section (if any).
        -- Note that old-style SSL on port 5223 only supports one certificate, and will always
        -- use the global one.
        ssl = {
                key = "/etc/prosody/certs/srvl043.XXXXXX.key";
                certificate = "/etc/prosody/certs/srvl043.XXXXXX.crt";
        }
        -- we need bosh
        modules_enabled = {
            "bosh";
            "pubsub";
            "ping"; -- Enable mod_ping
        }

Component "conference.srvl043.XXXXXX" "muc"
    --modules_enabled = { "token_verification" }
admins = { "focus@auth.srvl043.XXXXXX.de" }

Component "jitsi-videobridge.srvl043.XXXXXX"
    component_secret = "jq0KNT3f"

VirtualHost "auth.srvl043.XXXXXX"
    authentication = "internal_plain"

Component "focus.srvl043.XXXXXX"
    component_secret = "YvH0dqpo"

**Comment by mhenninghaus77** [comment]
jicofo config

# Jitsi Conference Focus settings
# sets the host name of the XMPP server
JICOFO_HOST=localhost

# sets the XMPP domain (default: none)
JICOFO_HOSTNAME=srvl043.XXXX

# sets the secret used to authenticate as an XMPP component
JICOFO_SECRET=YvH0dqpo

# sets the port to use for the XMPP component connection
JICOFO_PORT=5347

# sets the XMPP domain name to use for XMPP user logins
JICOFO_AUTH_DOMAIN=auth.srvl043.XXXX

# sets the username to use for XMPP user logins
JICOFO_AUTH_USER=focus

# sets the password to use for XMPP user logins
JICOFO_AUTH_PASSWORD=yy4PoM3d

# extra options to pass to the jicofo daemon
JICOFO_OPTS=""

# adds java system props that are passed to jicofo (default are for home and logging config file)
JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=jicofo -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/jicofo/logging.properties"

**Comment by mhenninghaus77** [comment]
videobridge  config

# Jitsi Videobridge settings

# sets the XMPP domain (default: none)
JVB_HOSTNAME=srvl043.XXXXX

# sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
JVB_HOST=

# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347

# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=jq0KNT3f

# extra options to pass to the JVB daemon
JVB_OPTS=""

# extra jvm params
#JVB_EXTRA_JVM_PARAMS="-javaagent:/usr/share/newrelic/newrelic.jar -Dnewrelic.config.file=/etc/jitsi/videobridge/newrelic.yml"

**Comment by mhenninghaus77** [comment]
meet config
`/* jshint -W101 */
var config = {
//    configLocation: './config.json', // see ./modules/HttpConfigFetch.js
    hosts: {
        domain: 'srvl043.XXXX.de',
        //anonymousdomain: 'guest.example.com',
        //authdomain: 'srvl043.XXXXXX',  // defaults to <domain>
        muc: 'conference.srvl043.XXXXXX', // FIXME: use XEP-0030
        bridge: 'jitsi-videobridge.srvl043.XXXXXX', // FIXME: use XEP-0030
        //jirecon: 'jirecon.srvl043.XXXXXX',
        //call_control: 'callcontrol.srvl043.XXXXXX',
        //focus: 'focus.srvl043.XXXXXX', // defaults to 'focus.srvl043.XXXXXX'
    },
//  getroomnode: function (path) { return 'someprefixpossiblybasedonpath'; },
//  useStunTurn: true, // use XEP-0215 to fetch STUN and TURN server
//  useIPv6: true, // ipv6 support. use at your own risk
    useNicks: false,
    bosh: '//srvl043.XXXXXX/http-bind', // FIXME: use xep-0156 for that
    clientNode: 'http://jitsi.org/jitsimeet', // The name of client node advertised in XEP-0115 'c' stanza
    //focusUserJid: 'focus@auth.srvl043.XXXXXX', // The real JID of focus participant - can be overridden here
    //defaultSipNumber: '', // Default SIP number

    // Desktop sharing method. Can be set to 'ext', 'webrtc' or false to disable.
    desktopSharingChromeMethod: 'ext',
    // The ID of the jidesha extension for Chrome.
    desktopSharingChromeExtId: 'diibjkoicjeejcmhdnailmkgecihlobk',
    // The media sources to use when using screen sharing with the Chrome
    // extension.
    desktopSharingChromeSources: ['screen', 'window'],
    // Required version of Chrome extension
    desktopSharingChromeMinExtVersion: '0.1',

    // The ID of the jidesha extension for Firefox. If null, we assume that no
    // extension is required.
    desktopSharingFirefoxExtId: null,
    // Whether desktop sharing should be disabled on Firefox.
    desktopSharingFirefoxDisabled: true,
    // The maximum version of Firefox which requires a jidesha extension.
    // Example: if set to 41, we will require the extension for Firefox versions
    // up to and including 41. On Firefox 42 and higher, we will run without the
    // extension.
    // If set to -1, an extension will be required for all versions of Firefox.
    desktopSharingFirefoxMaxVersionExtRequired: -1,
    // The URL to the Firefox extension for desktop sharing.
    desktopSharingFirefoxExtensionURL: null,

    // Disables ICE/UDP by filtering out local and remote UDP candidates in signalling.
    webrtcIceUdpDisable: false,
    // Disables ICE/TCP by filtering out local and remote TCP candidates in signalling.
    webrtcIceTcpDisable: false,

    openSctp: true, // Toggle to enable/disable SCTP channels
    disableStats: false,
    disableAudioLevels: false,
    channelLastN: -1, // The default value of the channel attribute last-n.
    adaptiveLastN: false,
    adaptiveSimulcast: false,
    enableRecording: false,
    enableWelcomePage: true,
    disableSimulcast: false,
    logStats: false, // Enable logging of PeerConnection stats via the focus
//    requireDisplayName: true, // Forces the participants that doesn't have display name to enter it when they enter the room.
//    startAudioMuted: 10, // every participant after the Nth will start audio muted
//    startVideoMuted: 10, // every participant after the Nth will start video muted
//    defaultLanguage: "en",
// To enable sending statistics to callstats.io you should provide Applicaiton ID and Secret.
//    callStatsID: "", // Application ID for callstats.io API
//    callStatsSecret: "", // Secret for callstats.io API
    /*noticeMessage: 'Service update is scheduled for 16th March 2015. ' +
    'During that time service will not be available. ' +
    'Apologise for inconvenience.',*/
    disableThirdPartyRequests: false,
    minHDHeight: 540
};
`

**Comment by mhenninghaus77** [comment]
I took the docker Image from docker hub an started it. i only put in the FQDN and said to the System that it has to generate a self signed certificate
After this i added my own ssl-certificates to the nginx

**Comment by saghul** [comment]
That is not an image we provide.

**Comment by saghul** [comment]
Check the options RocketChat passes when creating the Jitsi Meet iframe, sorry I wasn't too specific earlier.

**Comment by mhenninghaus77** [comment]
Problem is solved, but i don´t know why

**Comment by saghul** [comment]
I'm going to close this then. If you run into issues again we can reopen. Cheers!

**Comment by saadqbal** [comment]
@mhenninghaus77 have you managed to use Jitsi along with realm in react native?

I am stuck with Realm issue on ios. Realm won't configure together with Jitsi.
