### ISSUE TITLE
Local camera turn off and on immediately every 30 seconds

### ISSUE THREAD

**Issue by hungtd97** [jitsi/jitsi-meet#14503]
### Description:

Sometimes video track is muted and re-opens immediately every 30 seconds. I didn't find any specific action in logs, so I don't know which action triggered the camera off.

Here is the log from JitsiMeetSDK

GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
BufferQueueProducer    I  [SurfaceTexture-6-2919-1](this:0x7bc000a000,id:1,api:4,p:644,c:2919) queueBuffer: fps=9.98 dur=1002.07 max=102.77 min=98.44
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#2](this:0x7165c95800,id:43,api:1,p:2919,c:501) queueBuffer: fps=9.99 dur=1000.75 max=102.75 min=97.34
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#1](this:0x7165c94000,id:42,api:1,p:2919,c:501) queueBuffer: fps=9.96 dur=1003.80 max=103.17 min=98.49
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#0](this:0x715a165000,id:33,api:1,p:2919,c:501) queueBuffer: fps=9.99 dur=1100.84 max=111.52 min=93.65
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
ActivityTaskManager    I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.applicationid cmp=com.applicationid/.MainActivity} from uid 1000
GED                    I  ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
PhoneWindow            V  DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@7e22165, this = DecorView@a932e3a[MainActivity]
ReactNativeJS          I  '2024-03-20T06:32:25.563Z', '[modules/RTC/JitsiLocalTrack.js]', 'Mute LocalTrack[4,video]: true'
ReactNativeJS          D  '2024-03-20T06:32:25.567Z', '[modules/xmpp/SignalingLayerImpl.js]', 'Mute state of bfb387ce-v0 changed to muted=true'
ReactNativeJS          D  '2024-03-20T06:32:25.570Z', '[JitsiConference.js]', 'Mute state of LocalTrack[4,video] changed to muted=true'
org.webrtc.Logging     I  CameraCapturer: Stop capture
org.webrtc.Logging     I  CameraCapturer: Stop capture: Nulling session
org.webrtc.Logging     I  CameraCapturer: Stop capture done
org.webrtc.Logging     I  Camera2Session: Stop camera2 session on camera 1
org.webrtc.Logging     I  Camera2Session: Stop internal
org.webrtc.Logging     I  SurfaceTextureHelper: stopListening()
ReactNativeJS          I  '2024-03-20T06:32:25.575Z', '[modules/RTC/BridgeChannel.js]', 'Sending SourceVideoTypeMessage with video type bfb387ce-v0: none'
ReactNativeJS          I  '2024-03-20T06:32:25.631Z', '[modules/RTC/BridgeChannel.js]', 'Sending SourceVideoTypeMessage with video type bfb387ce-v0: none'
ReactNativeJS          I  Entering immersive mode
Surface                D  Surface::disconnect(this=0x7bc0255000,api=1)
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#1](this:0x7165c94000,id:42,api:1,p:2919,c:501) disconnect(P): api 1
Surface                D  Surface::disconnect(this=0x7bc0255000,api=-1)
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#1](this:0x7165c94000,id:42,api:1,p:-1,c:501) disconnect(P): api -1
ReactNativeJS          I  '2024-03-20T06:32:25.652Z', '[modules/RTC/JitsiLocalTrack.js]', 'Mute LocalTrack[4,video]: false'
org.webrtc.Logging     I  EglRenderer: Releasing.
org.webrtc.Logging     I  GlShader: Deleting shader.
org.webrtc.Logging     I  EglRenderer: Releasing done.
org.webrtc.Logging     I  CameraCapturer: startCapture: 640x480@5
ReactNativeJS          D  '2024-03-20T06:32:25.655Z', '[modules/xmpp/SignalingLayerImpl.js]', 'Mute state of bfb387ce-v0 changed to muted=false'
Surface                D  Surface::disconnect(this=0x7bc20c2000,api=1)
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#2](this:0x7165c95800,id:43,api:1,p:2919,c:501) disconnect(P): api 1
Surface                D  Surface::disconnect(this=0x7bc20c2000,api=-1)
BufferQueueProducer    I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#2](this:0x7165c95800,id:43,api:1,p:-1,c:501) disconnect(P): api -1
ReactNativeJS          D  '2024-03-20T06:32:25.658Z', '[JitsiConference.js]', 'Mute state of LocalTrack[4,video] changed to muted=false'
org.webrtc.Logging     I  EglRenderer: Releasing.
org.webrtc.Logging     I  GlShader: Deleting shader.
org.webrtc.Logging     I  EglRenderer: Releasing done.
BufferQueue            I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#1](this:0x7165c94000,id:42,api:1,p:-1,c:-1) ~BufferQueueCore
ReactNativeJS          I  '2024-03-20T06:32:25.662Z', '[modules/RTC/BridgeChannel.js]', 'Sending SourceVideoTypeMessage with video type bfb387ce-v0: camera'
BufferQueue            I  [SurfaceView - com.applicationid/com.applicationid.MainActivity#2](this:0x7165c95800,id:43,api:1,p:-1,c:-1) ~BufferQueueCore
BufferQueueProducer    I  [com.applicationid/com.applicationid.MainActivity#0](this:0x715a265800,id:15,api:1,p:2919,c:501) queueBuffer: fps=0.13 dur=29996.99 max=29450.67 min=14.23
BufferQueueProducer    D  [SurfaceTexture-6-2919-1](this:0x7bc000a000,id:1,api:4,p:644,c:2919) cancelBuffer: slot 1
BufferQueueProducer    D  [SurfaceTexture-6-2919-1](this:0x7bc000a000,id:1,api:4,p:644,c:2919) cancelBuffer: slot 2
BufferQueueProducer    D  [SurfaceTexture-6-2919-1](this:0x7bc000a000,id:1,api:4,p:644,c:2919) cancelBuffer: slot 3
BufferQueueProducer    D  [SurfaceTexture-6-2919-1](this:0x7bc000a000,id:1,api:4,p:644,c:2919) cancelBuffer: slot 4
ovisit.custome         E  No package ID ff found for ID 0xffffffff.
org.webrtc.Logging     I  EglRenderer: setMirrorHorizontally: true
ovisit.custome         E  No package ID ff found for ID 0xffffffff.
org.webrtc.Logging     I  EglRenderer: setMirrorHorizontally: true
ReactNativeJS          I  '2024-03-20T06:32:25.716Z', '[modules/RTC/BridgeChannel.js]', 'Sending SourceVideoTypeMessage with video type bfb387ce-v0: camera'
org.webrtc.Logging     I  EglBase14Impl: Using OpenGL ES version 2
org.webrtc.Logging     I  EglRenderer: Initializing EglRenderer
org.webrtc.Logging     I  EglBase14Impl: Using OpenGL ES version 2
org.webrtc.Logging     I  EglRenderer: Initializing EglRenderer
org.webrtc.Logging     I  EglRenderer: setLayoutAspectRatio: 1.3333334
org.webrtc.Logging     I  EglRenderer: setLayoutAspectRatio: 1.3333334
BufferQueueProducer    I  [SurfaceTexture-6-2919-1](this:0x7bc000a000,id:1,api:4,p:644,c:2919) disconnect(P): api 4
org.webrtc.Logging     I  Camera2Session: Stop done
org.webrtc.Logging     I  Camera2Session: Create new camera2 session on camera 1
org.webrtc.Logging     I  Camera2Session: start

### Steps to reproduce:

1. Make a normal call point to point call.

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: [2.0.9258](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_9258)
- Operating System: Android 10

**Comment by saghul** [comment]
What SDK version are you using? The one you listed is not a released version.

**Comment by hungtd97** [comment]
@saghul I forked and self-deployed to my registry, but I used release tag [2.0.9258](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_9258)

**Comment by saghul** [comment]
That is a web release tag not an SDK one.

Also, we can't help you with your fork because I have no idea what you changed.

Please test with the official SDK and report back.

**Comment by hungtd97** [comment]
@saghul I tried latest public version [2.0.2](https://www.npmjs.com/package/@jitsi/react-native-sdk/v/2.0.2), but it still happens. What kind of log you may think that can help you?

**Comment by saghul** [comment]
Full logcat logs please.

**Comment by hungtd97** [comment]
@saghul 
This is logcat file please change file extension to .logcat if it's hard to trace.
[LENOVO-Lenovo-TB-X606X-Android-10_2024-03-21_083820.txt](https://github.com/jitsi/jitsi-meet/files/14756196/LENOVO-Lenovo-TB-X606X-Android-10_2024-03-21_083820.txt)

**Note**:  '[modules/RTC/JitsiLocalTrack.js]', 'Mute LocalTrack[4,video]: true'
I saw this log but don't know what's the reason that makes local track turn off and on again. 

_React Native: 0.72.4
Bug still occurs with Hermes's enabled and disabled_

**Comment by hungtd97** [comment]
@saghul it's from Android Studio, you can import into it for better view.

**Comment by saghul** [comment]
Oh, I didn't know that! I renamed it to foo.logact but opening it with AS just shows the content raw. IS there something special that needs to be done to browse it?

**Comment by hungtd97** [comment]
@saghul It has a button to import from logcat file. I think you may use an older version of Android Studio. I'll give you txt file tomorrow when I'm on my office

**Comment by saghul** [comment]
I finally found it 😅 

I see the local track being muted and then unmuted, but no specific event that would lead to that :-/

**Comment by hungtd97** [comment]
@saghul do you think another software outside my app can affect camera status :-?

**Comment by saghul** [comment]
It can, but I see the JS logs for track mute which are logged when a user presses the mute button for example.

**Comment by saghul** [comment]
Yes, but then there would be some related native log in the surrounding, like when the app goes in the background, for example. I see none of that.
