### ISSUE TITLE
No option to turn off the breakout rooms on the Participants screen.

### ISSUE THREAD

**Issue by vadym-mytrenko-923** [jitsi/jitsi-meet#14507]
Hi! We are using the Jitsi Meet Android SDK and are trying to turn off the breakout rooms. We already used the `breakout-rooms.enabled` parameter and set it to false, but the "Breakout Rooms" button is still visible on the Participants screen. 

Feature flag off:
<img width="481" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/159130206/b4166a53-8ab0-46cb-9db9-445a22706c65">

"Breakout Rooms" button is still visible:
![image](https://github.com/jitsi/jitsi-meet/assets/159130206/434b4eb3-d38d-43dc-aea4-59d5392674f9)

Is it a separate feature flag to disable this button on the Participants screen or it can't be disabled now? Can you provide the solution to fully remove the breakout rooms option from the Android Jitsi SDK? Thank you!

**Comment by damencho** [comment]
What about disabling it in the backend?

**Comment by vadym-mytrenko-923** [comment]
Can you please describe how it can be achieved? Maybe some helpful links that I can provide to our web-engineer?

**Comment by damencho** [comment]
Just comment the breakout related stuff in prosody config.

This virtual host:
https://github.com/jitsi/jitsi-meet/blob/5d84a4cc9055dca1d03150eb537cd78eea73c99a/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L94

And the module:
https://github.com/jitsi/jitsi-meet/blob/5d84a4cc9055dca1d03150eb537cd78eea73c99a/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L64

**Comment by saghul** [comment]
I hate SDK version are you using?

**Comment by vadym-mytrenko-923** [comment]
Hi! I'm using the 8.6.0 SDK version.

**Comment by vadym-mytrenko-923** [comment]
No, but I'll update the SDK to the 9 version. Is there an inside feature flag or just backend option?

**Comment by saghul** [comment]
The sdk flag will just disable the UI. You can disable the feature altogether in the backend.

**Comment by vadym-mytrenko-923** [comment]
Ok, I'll try to update the SDK and answer here. Thank you.

**Comment by vadym-mytrenko-923** [comment]
Hi! It's already implemented in the SDK 9.0.0 version. Thanks a lot, closing the issue <3
