### ISSUE TITLE
Sharing screen with stereo sound

### ISSUE THREAD

**Issue by jinkhya** [jitsi/jitsi-meet#14513]
**Is your feature request related to a problem you are facing?**
Hello, when I share my screen playing a stereo sound, the people in my meeting only hear it as mono. 

**Describe the solution you'd like**
Unless I missed it could you add an option somewhere to toggle stereo please.

Best Regards,
Jin

**Comment by saghul** [comment]
It's not currently possible because even if you enable the stereo audio setting, we mix the audio from the screen with the local microphone using a single channel.

**Comment by jinkhya** [comment]
AH ok, thanks for the answer, have a good day!
