### ISSUE TITLE
Poll submit button overflows in android

### ISSUE THREAD

**Issue by nitinkushwaha17** [jitsi/jitsi-meet#14514]
### Description:

Poll submit button overflows in android application

### Steps to reproduce:

1. Create a poll and vote

### Expected behavior:

Submit button should be inside the container

### Actual behavior:

Submit button overflows outside the container
<img src="https://github.com/jitsi/jitsi-meet/assets/79357960/89a1358d-7be6-46b8-9d47-39be648be6b3" width=250>

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: 24.0.1
- Operating System: Android 13

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by Calinteodor** [comment]
What device are you using? I am unable to reproduce this while testing on an OnePlus 5 with Android 10 and Pixel 6 with Android 14. Also, can you please update to latest, which is 24.0.1?

**Comment by nitinkushwaha17** [comment]
Hey @Calinteodor
I have updated the app to version 24.0.1 but the issue still persists
I am using a Realme device

**Comment by Calinteodor** [comment]
Ok, so this means that your phone uses either ColorOS or realme UI. 
Both are Android based, but I expect them to have some differences from the native Android.
I'll see if I can find a way to get my hands on one of these devices so I can test, but I don't guarantee I will be able to find one. 
In the meantime, If you want and are able to, you can propose a PR with a fix.
