### ISSUE TITLE
alphabet sorting in tile mode

### ISSUE THREAD

**Issue by slesru** [jitsi/jitsi-meet#14511]
Hello!

For several reasons it is good to have video sorted in tile mode.

I see several request for this feature here, all of them are closed.
https://github.com/jitsi/jitsi-meet/issues/11844
https://github.com/jitsi/jitsi-meet/issues/5298

Now we use code from here, auto
https://github.com/kaiyazeera/jitsi-bookmarklets/
I just added it java script code to ...config.js

Unfortunately, it doesn't work since jitsi meet  2.0.9364 .

Could you, please, consider including of this to jitsi meet?

Thank you!

**Comment by damencho** [comment]
We had experimented with that in the past and its hard to achieve a good experience for the users, we got a lot of complains about it and we dropped it, if I recall correctly.
The problem is the constant sorting in big calls where people join and leave all the time, it can be really distracting. Most of the users want the order of thumbnails to be kept for the time of the meeting, if you know the place of a person and you want to see that person you know where to find it.

**Comment by slesru** [comment]
Well,  this sorting helps to stay user on the same place on top, if, let's say, user have nickname started with digit and other users are not. 
So it really helps users know place of person.
And I'm not talking about thumbnail, but about video placing in tile mode.
If it is possible to move user's video in this mode to specific position and keep it there - please tell me.
Thank you!

**Comment by damencho** [comment]
Yes, I mean tile.
Nope there is no such option. And this reordering was bothering users and we needed to turn it off. As I said this is problematic in big calls with many people joining and leaving and having tiles reorder constantly on your screen.

**Comment by slesru** [comment]
There are several scenarios how jitsi meet can be used. In our scenario we'd like to always have user's video on the same place.
And usually we have no many people joining and leaving.
Why not implement this and make it configurable, so everybody will be happy ? ;-)

**Comment by slesru** [comment]
btw, we have jitsi meet installation on premise, so this can be static option :-)

**Comment by saghul** [comment]
Adding the option is not the problem. Maintaining it is. The logic there is already complex enough and we don't want to make it even more complicated.

**Comment by slesru** [comment]
I understand that maintaining is main problem here. 
This is why I'm asking. Just because this is second time it became broken.

But! It is very useful feature already requested several times...

Can't add anything else.

Thank you.

**Comment by saghul** [comment]
We have no plans to implement this.

**Comment by slesru** [comment]
Not listening to user's needs is always bad idea ;-)

**Comment by saghul** [comment]
If we implemented all people want this is what you end up with:

![image](https://github.com/jitsi/jitsi-meet/assets/317464/c66b2c17-2141-48b6-8c28-db0909ffa48c)

We need to balance what (some) people want and many other things.

Sorry the outcome doesn't match your expectation, things are not as simple as one thinks, specially in large projects like this one.

**Comment by slesru** [comment]
I'd like to have such car ;-)
