### ISSUE TITLE
Partecipants disconnected after the first guest join

### ISSUE THREAD

**Issue by supporto-wifiproject** [jitsi/jitsi-meet#14526]
### Description:
I installed jitsi-meet according to this guide (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart).
the site is meet.wifi-project.cloud
I activated secure domain authentication according to https://jitsi.github.io/handbook/docs/devops-guide/secure-domain.
I'm able to create a new room after entering username and paswored but when the first guest join, we both diconnect from the room.

### Server information:

- Jitsi Meet version: 2.0.9364-1 (package for deabin distribution)
- Operating System: Rspi OS bookworm

I attache the modifcation according to the guide:
File: /etc/prosody/conf.avail/meet.wifi-project.cloud.cfg.lua
`VirtualHost "meet.wifi-project.cloud"`
`      authentication = "internal_hashed"`

File: /etc/jitsi/meet/meet.wifi-project.cloud-config.js
`hosts: {`
        `// XMPP domain.`
`        domain: 'meet.wifi-project.cloud',`
`        anonymousdomain: 'guest.meet.wifi-project.cloud',`

File /etc/jitsi/jicofo/jicofo.conf
`jicofo {`
`  authentication {`
`    enabled: true`
`    type: XMPP`
`    login-url: meet.wifi-project.cloud`
`  }`
`  xmpp: {`
`    client: {`
`      client-proxy: "focus.meet.wifi-project.cloud"`
`      xmpp-domain: "meet.wifi-project.cloud"`
`      domain: "auth.meet.wifi-project.cloud"`
`      username: "focus"`
`      password: "ae32lrJL2K83OV0R"`
`    }`
`    trusted-domains: [ "recorder.meet.wifi-project.cloud" ]`
`  }`
`  bridge: {``
`    brewery-jid: "JvbBrewery@internal.auth.meet.wifi-project.cloud"`
`  }`
`}`

The console from my browser says `CONFERENCE FAILED: conference.videobridgeNotAvailable`
What's wrong?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Try restarting jitsi-videobridge2 service does that change anything? 
What do you see in jvb logs?

**Comment by supporto-wifiproject** [comment]
Sorry for not writing in the forum.
Restarting videobridge doesn't change nothing.
These lines are from jvb log:
`JVB 2024-03-22 20:54:34.153 GRAVE: [23] HealthChecker.run#181: Health check failed in PT0.000100036S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=Failed to bind single-port)`
`JVB 2024-03-22 20:55:34.153 GRAVE: [23] HealthChecker.run#181: Health check failed in PT0.000115906S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=Failed to bind single-port)`

**Comment by damencho** [comment]
Yep, port already used by some other service.

**Comment by supporto-wifiproject** [comment]
Which port have I to check? For example i have Webmin to port 10000 and I moved it to port 15000 but the problem persist.

**Comment by supporto-wifiproject** [comment]
With `ss -tapnu` I see that Webmin still occupies port 10000. Fixing this issue now everything is working fine. Thanks for your precious help.
Bye!
