### ISSUE TITLE
Translate main-hi.json some object array in hindi

### ISSUE THREAD

**Issue by AnshuPathak-88825** [jitsi/jitsi-meet#14531]
these some value need to be translate in hindi 
![image](https://github.com/jitsi/jitsi-meet/assets/78332454/ad2b1726-8d62-4d8a-a781-cc71e2922e0a)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.


The translations are community contributed, so PRs are welcome.

More information https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md
