### ISSUE TITLE
 Config option to disable “Move to visitor” menu item

### ISSUE THREAD

**Issue by VernPace** [jitsi/jitsi-meet#14539]
Because none of our meetings (https://meet.jit.si) have more than 16 participants, there is no need for anyone to be demoted to visitor. Therefore, we have no need for the “Move to visitor” item in the right click context menu for localVideo - We don't want our participants clicking it as it could create confusion.

![image](https://github.com/jitsi/jitsi-meet/assets/94239732/fca8b432-c251-4fc7-8d0c-1b501643f303)

We are proposing a new config option to disable the “Move to visitor” item in the right click context menu for localVideo. We are already using _config.remoteVideoMenu.disableDemote=true_ for the remote participant menu.

Unfortunately, we don't have the resources to submit code for this proposal.

**Comment by saghul** [comment]
Ping @damencho

**Comment by danileon04** [comment]
How can I take back the participant that i moved to visitor?

**Comment by damencho** [comment]
The participant can raise hand and be promoted back to the main meeting.

**Comment by anirbandas18** [comment]
@damencho Does this require the visitor mode of prosody to be enabled ?

**Comment by damencho** [comment]
Yes
