### ISSUE TITLE
Replace Voice by "Trial Version " in https://meet.jit.si/

### ISSUE THREAD

**Issue by VuDn5** [jitsi/jitsi-meet#14533]
Dear PO,

Whenever I create a meeting on https://meet.jit.si/, my voice gets replaced by a trial version voice every time I speak. I don't know why this is happening. Can you please assist me?

Thank you.

**Comment by saghul** [comment]
What do you mean by "trial version voice" ?

**Comment by VuDn5** [comment]
> What do you mean by "trial version voice" ?
Dear Saghul

When I create a meeting with two participants and try to speak from the moderator's device, my voice is immediately muted and replaced by a repetitive bot voice saying "Trial Version". Other participants can still speak normally.

**Comment by saghul** [comment]
Sounds like some virtual audio device on your machine. We are not doing that on our end.

**Comment by VuDn5** [comment]
> Sounds like some virtual audio device on your machine. We are not doing that on our end.

Oh, i'm sorry and thank you. My app is IVCam is root cause problem. 
I uninstalled it and everything alright.
