### ISSUE TITLE
The language JSON files are incomplete

### ISSUE THREAD

**Issue by hkien2310** [jitsi/jitsi-meet#14542]
I am using your library for my application.
I want to use Vietnamese language for my application.
I noticed that the main-vi.json file (https://github.com/jitsi/jitsi-meet/blob/33db2bed34ab0bad1dc811a99fbe6751ded3655c/lang/main-vi.json) is not as complete as main.json (https://github. com/jitsi/jitsi-meet/blob/33db2bed34ab0bad1dc811a99fbe6751ded3655c/lang/main.json) in multiple sections like (polls, toolbar)

<img width="259" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/91368172/4c68613c-3ede-45d6-b03c-357a09708938">

<img width="1440" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/91368172/915b9152-6c09-4678-923c-9cbf0b33dccd">
<img width="1440" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/91368172/352387b4-c2bc-479f-9c39-8c6722bfdc13">

Can you guys update them and update them soon? I thank you for your help

**Comment by saghul** [comment]
We rely on the community to update the languages we don't speak.

If you can, take a look at the README file inside the lang/ folder with instructions on how to contribute.

**Comment by hkien2310** [comment]
@saghul I've used comman 
cd lang
node update-translation.js main-vi.json
Then update main-vi.json, now how can I contribute main-vi.json

**Comment by saghul** [comment]
Thanks! You need to create a fork, then push your branch to the fork and last open a PR to merge your branch here.

**Comment by hkien2310** [comment]
> Thanks! You need to create a fork, then push your branch to the fork and last open a PR to merge your branch here.

I created a pull request but it is currently blocking. Can you take a look and tell me what to do next?
This is the pull request link: https://github.com/jitsi/jitsi-meet/pull/14544

**Comment by saghul** [comment]
Thanks! I approved the CI. If it passes I'll merge it.

**Comment by hkien2310** [comment]
> Thanks! I approved the CI. If it passes I'll merge it.
@saghul  I see there's just a line error that shouldn't leave the last line blank. So I made modifications to it. Can you check again for me? Thank you

**Comment by hkien2310** [comment]
> ```
>  diff --git a/lang/main-vi.json b/lang/main-vi.json
> index 81d1bc1c6..1839586d7 100644
> --- a/lang/main-vi.json
> +++ b/lang/main-vi.json
> @@ -1535,8 +1535,8 @@
>      },
>      "whiteboard": {
>          "accessibilityLabel": {
> -          "heading": "Bảng trắng"
> +            "heading": "Bảng trắng"
>          },
>          "screenTitle": "Bảng trắng"
>      }
> -}
> \ No newline at end of file
> +}
> diff --git a/lang/main.json b/lang/main.json
> index 240b0b4f0..02a2ba36c 100644
> --- a/lang/main.json
> +++ b/lang/main.json
> @@ -1541,4 +1541,4 @@
>          },
>          "screenTitle": "Whiteboard"
>      }
> -}
> \ No newline at end of file
> +}
> ```
> 
> There are still a couple of issues.

@saghul  I have done the update. Please help me check. Thank you

**Comment by saghul** [comment]
There is still a lint issue

**Comment by hkien2310** [comment]
> There is still a lint issue

Can you check a pull request again. This is pull rq link: https://github.com/jitsi/jitsi-meet/pull/14544 
Thank you

**Comment by hkien2310** [comment]
@saghul  
<img width="920" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/91368172/2f7c266a-3a43-4c59-bfb2-ca87ae2e64a0">
please check pull rq. i saw it passed all case

**Comment by saghul** [comment]
Merged, thank you!
