### ISSUE TITLE
Join Without Audio + Moderator Ask to Unmute Bug

### ISSUE THREAD

**Issue by nbeckindy** [jitsi/jitsi-meet#14559]
### Description:

If a participant joins without audio (aka startSilent), they can still become unmuted if the moderator requests it.

### Steps to reproduce:

1. Start a moderated meeting with two participants. One participant should be a moderator, the other should join without audio. 
2. With the moderator participant, click Ask to Unmute on the participant that joined without audio.
3. The "Moderator would like you to speak" popup will appear to the participant who joined without audio. Click "Unmute" from that popup.

### Expected behavior:

Ideally, the moderator should have some indication that a participant has joined without audio. The option to ask that participant to unmute shouldn't be available. Also, maybe the microphone icon in the participant pane could be hidden. If a popup does appear somehow, the participant who joined without audio should not be able to unmute themselves from it.

### Actual behavior:

If the participant who joined without audio clicks on the "Unmute" button from the popup, their mic will be turned on. Since joining without audio disables the mic button in the toolbox, they can't mute themselves again. The moderator has to mute them.

### Server information:

Present on alpha.jitsi.net as of 2024-03-27

**Comment by saghul** [comment]
Interesting edge case! WDYT @damencho ?

**Comment by damencho** [comment]
If you are using startSilent config, we do not do any special signalling for it to know that participant will not hear and talk and is just watching...

**Comment by saghul** [comment]
Perhaps we should put it in presence?

**Comment by damencho** [comment]
Yeah, maybe in features, as its like capability....

**Comment by saghul** [comment]
Good point!

**Comment by VirajDilshanKumarage** [comment]
is this issue fixed?

**Comment by saghul** [comment]
No.
