### ISSUE TITLE
User can never join meeting due to membersOnly

### ISSUE THREAD

**Issue by Divide-By-0** [jitsi/jitsi-meet#14566]
I'm getting this error: `[conference.js] conference.connectionError.membersOnly` on a variety of devices and tools for an embedded jitsi-container on the sidebar of a website with this API: JitsiMeetExternalAPI("meet.jit.si",  options). I am on latest Chrome on M1.

I use this code:
```
  // Most of the magic happens here
  // for reference: https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js
  // https://github.com/jitsi/jitsi-meet/blob/master/config.js
  // for overwrites see https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe
  const options = Object.assign(
    {
      roomName,
      parentNode: "jitsi-container",
    },
    optionsConfig
  );
  ```

With this config:
```
export const optionsConfig = {
  interfaceConfigOverwrite: {
    SHOW_JITSI_WATERMARK: false,
    SHOW_WATERMARK_FOR_GUESTS: false,
    SHOW_CHROME_EXTENSION_BANNER: false,
    VERTICAL_FILMSTRIP: true,
    SETTINGS_SECTIONS: ["devices"],
    filmStripOnly: false,
    FILM_STRIP_MAX_HEIGHT: 80,
    DEFAULT_BACKGROUND: "transparent",
    JITSI_WATERMARK_LINK: "https://jitsi.org",
    MOBILE_APP_PROMO: false,
    DISABLE_FOCUS_INDICATOR: true,
    DISABLE_DOMINANT_SPEAKER_INDICATOR: true,
    DISPLAY_WELCOME_PAGE_CONTENT: false,
    TILE_VIEW_MAX_COLUMNS: 1,
    DEFAULT_REMOTE_DISPLAY_NAME: "Player",
    DISABLE_VIDEO_BACKGROUND: true, // reduces CPU by 25%: https://community.jitsi.org/t/high-cpu-utilization-on-client-end/25764/25
    VIDEO_QUALITY_LABEL_DISABLED: true,
    CONNECTION_INDICATOR_DISABLED: true,
    HIDE_KICK_BUTTON_FOR_GUESTS: true,
    HIDE_INVITE_MORE_HEADER: true, // their "Invite" button doesn't fit screen/has bad UI
  },
  configOverwrite: {
    enableNoisyMicDetection: false,
    enableTalkWhileMuted: false,
    enableNoAudioDetection: false,
    enableWelcomePage: false,
    prejoinPageEnabled: false,
    resolution: 480,
    startWithVideoMuted: true,
    startWithAudioMuted: true,
    disableInviteFunctions: true,
    toolbarButtons: ["microphone", "camera", "tileview"],
  },
};

```

### Description:

Videochat does not initialize/user cannot join due to error/

### Steps to reproduce:

Run that config in an HTML file/React client, and fail to join.

### Expected behavior:

It should open a videochat and the user should join with audio and video, even without auth.

### Actual behavior:

Errors in console and no videochat joined.

### Additional information:

This used to work fine so would love to hear what changed.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

You should not be embedding meet.jit.si. That environment is configured in a way that the creator of the room needs to authenticate via Google, Facebook or Github. If you still want to test with it, you can use the browser to create the meeting and then test your code, the embedding of iframe has a limit of 5 mins.

Consider hosting your own deployment or you can use jaas.

**Comment by Divide-By-0** [comment]
Thanks! I used one of the links from here: https://web.archive.org/web/20240105221345/https://jitsi.github.io/handbook/docs/community/community-instances/

**Comment by saghul** [comment]
Well that page was deleted, that should tell you something...
