### ISSUE TITLE
Displaying emoji descriptions when hovering in smileys panel

### ISSUE THREAD

**Issue by ilaydadastan** [jitsi/jitsi-meet#14568]
**Is your feature request related to a problem you are facing?**
I would like to see the emoji descriptions when hover over the emoji. Also, when selecting emoji, I would like to select it with the enter key instead of using the space key.

**Describe the solution you'd like**
Seeing emoji descriptions as tooltips when hovering over emojis in the chat. Adding the ability to select emoji with the enter key in addition to the ability to select emoji with the space bar.

**Comment by damencho** [comment]
Just a note, that you can add Fixes#14568 in the commit description and that will automatically close issues when a commit is merged. 

More info you can read here: https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue

**Comment by ilaydadastan** [comment]
> Just a note, that you can add Fixes#14568 in the commit description and that will automatically close issues when a commit is merged.
> 
> More info you can read here: https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue

Okay, I'll take into consideration, thanks
