### ISSUE TITLE
Adding single answer poll type

### ISSUE THREAD

**Issue by HazemAbdo** [jitsi/jitsi-meet#14576]
**Is your feature request related to a problem you are facing?**
As a meeting moderator maybe sometime I want to make a poll that other participants should choose only one answer of poll choices
![image](https://github.com/jitsi/jitsi-meet/assets/59124058/619b1bf3-ded2-4c8a-92eb-9a3219188bd5)
![image](https://github.com/jitsi/jitsi-meet/assets/59124058/ca1963be-858b-4867-a6e7-47603101ec4f)

**Describe the solution you'd like**
I want to have a question that asks me if I want the poll to be single answer question or multi answer during poll creation step.I will make this changes on `react/features/polls/components/AbstractPollCreate.tsx` `react/features/polls/components/AbstractPollCreate.tsx` `react/features/polls/components/web/PollAnswer.tsx` `react/features/polls/components/web/PollCreate.tsx`

I want to work on this task by myself if I got approvals from community maintainers.

**Comment by saghul** [comment]
We are currently working on some polls changes, so your work would likely conflict. Thanks for taking the time to file the issue though, duly noted!

**Comment by catFurr** [comment]
@saghul  can we consider reopening this issue now that polls are stable?  i can contribute a PR if the team would be interested in having polls with single choice.  we hear from clients its a common use case

this seems like a single days of work with really positive UX boost

i havent checked yet, but most likely this involves:
- update poll ui to show single/multi mode
- possibly update mod_polls_component to enforce the single option
- ideally not needed, but may require updating lib-jitsi-meet based on prosody plugin
