### ISSUE TITLE
Build a new SmileysPanel(emoji picker)

### ISSUE THREAD

**Issue by HazemAbdo** [jitsi/jitsi-meet#14575]
**Is your feature request related to a problem you are facing?**
The emoji picker has a very limited number of options and don't have a search functionality
![image](https://github.com/jitsi/jitsi-meet/assets/59124058/6f56bd68-bfbc-4ced-a19f-b8271bf18490)

**Describe the solution you'd like**
I'd like to use this vanillaJS emoji picker and build a react function component on top of it https://github.com/woody180/vanilla-javascript-emoji-picker/blob/master/vanillaEmojiPicker.js and make a merge between it and the current `react/features/chat/components/web/SmileysPanel.tsx` and for this purpose I will update the` react/features/chat/smileys.ts` with this list of emojis https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

**Describe alternatives you've considered**
- We can use a ready made emoji picker package like https://www.npmjs.com/package/emoji-picker-react
- We can just make a bigger list of supported emojis while keeping the current component and without adding the searching functionality

I want to work on this task by myself if I got approvals from community maintainers.

**Comment by saghul** [comment]
Looks really nice, go ahead!
