### ISSUE TITLE
Fixes RaiseHand label ParticipantPane issue

### ISSUE THREAD

**Issue by astro-dally** [jitsi/jitsi-meet#14579]
### Description:

When a user clicks  on the raisehand button which is shown on the top it shows the participants pane.

### Steps to reproduce:

1. Create a jitsi meet 
2. Click on raisehand 
3. After clicking on the top a raisehand icon will appear
4. Click on the raisehand icon on the top

### Expected behavior:

When a user clicks on the raisehand button which is shown on the top, it shows all participants pane.

<img width="1840" alt="RaiseHandParticipants" src="https://github.com/jitsi/jitsi-meet/assets/145124717/fa72c55a-da3b-4ca8-895b-84bb9355cb1e">

### Actual behavior:
On clicking the raisehand icon, only the participants who have raised their hand should appear

<img width="1840" alt="Participants" src="https://github.com/jitsi/jitsi-meet/assets/145124717/d0067acc-8efd-4812-a8ba-124de2a50d85">

### Server information:

- Jitsi Meet version: [2.0.9364](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_9364)
- Operating System: MacBook Pro Apple M2 

### Client information:

- Browser / app version: Chrome Version 123.0.6312.87
- Operating System: MacBook Pro Apple M2 

### Additional information:

I have attached the demo video,

https://github.com/jitsi/jitsi-meet/assets/145124717/7e722db4-5666-4716-8cfb-7ae9f110d95c

**Comment by damencho** [comment]
And how do you get out of this mode for the participants pane?

**Comment by astro-dally** [comment]
Currently when the user clicks on the "Show Participants" icon, the default participants pane is displayed. However, when the user clicks on the "Raise Hand" icon, it shows the participants with raised hands.

Could you provide suggestions on how to manage the switching between modes?

**Comment by astro-dally** [comment]
Is the current approach correct?
or Should we have different components to handle different modes?

**Comment by damencho** [comment]
@saghul wdyt?

**Comment by saghul** [comment]
I think the UX complexity this adds is not great. The raised hand users are already sorted to the top, so that's not a problem for large meetings.

This should be evaluated in the context of the GSoC speaker queue project, not ad-hoc, IMHO.
