### ISSUE TITLE
Render Emoji in chat input messagebox

### ISSUE THREAD

**Issue by HazemAbdo** [jitsi/jitsi-meet#14577]
**Is your feature request related to a problem you are facing?**
When I choose an emoji in chat box input field it doesn't render the emoji instead it shows its corresponding code until the msg is sent then in the messages box it renders the emoji
![image](https://github.com/jitsi/jitsi-meet/assets/59124058/bb477571-4912-42e5-95fc-6f447a865ad3)
![image](https://github.com/jitsi/jitsi-meet/assets/59124058/49ba79cb-379c-40c2-80bc-e75cca83b2fc)

**Describe the solution you'd like**
I will make changes into `react/features/chat/components/web/ChatInput.tsx` to make it renders the emoji and I will get used of `react/features/chat/components/web/ChatMessage.tsx ` `react/features/base/react/components/web/Message.tsx`

I want to work on this task by myself if I got approvals from community maintainers.

**Comment by saghul** [comment]
Go ahead!
