### ISSUE TITLE
GIF rendering issue when a new participant joins the meeting

### ISSUE THREAD

**Issue by ilaydadastan** [jitsi/jitsi-meet#14578]
### Description:
The GIF shared in the chat is rendered in the participant profile on the conference screen when a new participant joins the meeting.

### Steps to reproduce:

1. Participants send GIFs from chat
2. Then a new person joins the meeting.
3. And the GIF sent in the chat appears on the screen above their profile for a few seconds. 

### Expected behavior:
When a new participant joins the meeting, no GIFs should be rendered in the participant profile on the conference screen.

### Actual behavior:
When a new participant joins the meeting, the GIF previously sent in the chat is displayed in the participant profile on the conference screen.

https://github.com/jitsi/jitsi-meet/assets/43909097/d134fbab-4238-4779-bbbd-5220ab756372

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Chrome 122
- Operating System: MacOS

**Comment by saghul** [comment]
It's just the last one, right? Fair enough, a PR would be welcome!

**Comment by ilaydadastan** [comment]
Yes @saghul this is the last one for now. I could not progress in solving it but I'm continue. I’m open to your suggestions.
