### ISSUE TITLE
[React native SDK] [iOS] - Screen share cannot working

### ISSUE THREAD

**Issue by AndrewTotsky** [jitsi/jitsi-meet#14588]
### Description:
When starting screen sharing in lib-jitsi-meet, an error is thrown **Replacing a track of videoType=camera with a track of videoType=desktop is not supported in this mode.** in JitsiConference.js

What is meant by mode? Why can't camera/desktop tracks be replaced? Any ideas how to get round this?

### Steps to reproduce:

1. Join to conference with participants.
2. Click on share screen button.

### Expected behavior:
Screen sharing for participants.

### Actual behavior:
Screen not sharing for participants, lib-jitsi-meet thrown error.
<img src="https://github.com/jitsi/jitsi-meet/assets/26544121/4ce506ea-b8bd-4c59-819a-cdbf0ac8ea7c" width="260">

react/features/base/tracks/actions.any.ts
<img width="560" alt="Screenshot 2024-04-02 at 13 17 45" src="https://github.com/jitsi/jitsi-meet/assets/26544121/06db63ae-2020-49f7-a232-4202c9da0ac0">

JitsiConference.js
<img width="1025" alt="Screenshot 2024-04-02 at 13 22 16" src="https://github.com/jitsi/jitsi-meet/assets/26544121/c0e2451f-2c74-4fac-b58d-fbe039be95c9">

### Additional information:
The camera track type and sharing screen track type are indeed different, but why can't they be replaced? What is the reason for the prohibition of this action?

**Comment by saghul** [comment]
What version of LJM are you using?

**Comment by AndrewTotsky** [comment]
[v1787.0.0+9ec93dc6](https://github.com/jitsi/lib-jitsi-meet/releases/tag/v1787.0.0%2B9ec93dc6)

**Comment by saghul** [comment]
So you are using our RN SDK, right? What server are you connecting to?

**Comment by AmilKey** [comment]
@saghul any updates on this issue?

**Comment by saghul** [comment]
Nope, sorry.

**Comment by AmilKey** [comment]
@saghul  Can you give a simple example of how this function can be replaced now? I do upgrade litsi lib now
