### ISSUE TITLE
ECHO while calling from android to ios and both are in speaker echo voice comes.. how to solve this issues?

### ISSUE THREAD

**Issue by AnithaPra** [jitsi/jitsi-meet#14589]
While calling from android to ios, and in both its set to speaker , so on call echo voice is coming
How to remove this echo voice? 
Please help if someone has solved this already

**Comment by saghul** [comment]
We use the hardware echo canceller on mobile, so there is nothing else you can enable at the moment, other than system wide things like "voice isolation" like in iOS.

**Comment by AnithaPra** [comment]
> We use the hardware echo canceller on mobile, so there is nothing else you can enable at the moment, other than system wide things like "voice isolation" like in iOS.

Can i know how can i do voice isolation for ios ? and also for echo canceller which key is currectly used so i can check in code if it is there or not

**Comment by saghul** [comment]
There is no key, WebRTC itself enables the builtin hardware one, if available.
