### ISSUE TITLE
Not join room after upgrade

### ISSUE THREAD

**Issue by MorganReid** [jitsi/jitsi-meet#14582]
The problem I encountered is almost exactly the same as this [issue](https://github.com/jitsi/jitsi-meet/issues/14289), but I don't see a solution.

### Description:

Install jitsi through office [doc](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart). When accessing jitsi, i cannot join and` join meeting` becomes inoperable.
![企业微信截图_17119640039715](https://github.com/jitsi/jitsi-meet/assets/52235796/34db581d-323f-4aaa-a14d-93facb89d9c1)

### Expected behavior:

join successful

### Actual behavior:
join fail

/jitsi/jicofo.log
![企业微信截图_17119637198763](https://github.com/jitsi/jitsi-meet/assets/52235796/276be454-624e-4de1-80e5-743799f506dd)

/jitsi/jvb.log
![企业微信截图_17119637964513](https://github.com/jitsi/jitsi-meet/assets/52235796/dd499775-9ca3-4a08-9379-eddb2127d826)

/prosody is empty,and  prosody status

![企业微信截图_17119642621896](https://github.com/jitsi/jitsi-meet/assets/52235796/cf72ba69-e845-4177-a689-47a415174878)

### Server information:

- Jitsi Meet version:newest
- Operating System:ubuntu 20.04

### Client information:

- Browser / app version:firefox/google

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Do you have this in your main prosody config
Include "conf.d/*.cfg.lua"

**Comment by MorganReid** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.
> 
> Do you have this in your main prosody config Include "conf.d/*.cfg.lua"

Sorry, I will pay attention next time.
Yes,i have
![image](https://github.com/jitsi/jitsi-meet/assets/52235796/cb69434c-597d-4f55-bbf6-94ebc24d9ddc)

**Comment by damencho** [comment]
Clear prosody logs and restart prosody, then check for errors.

**Comment by MorganReid** [comment]
> Clear prosody logs and restart prosody, then check for errors.

After restart prosody,There is still nothing in` /var/log/prosody`. and ` cat /var/log/syslog | grep prosody`
![image](https://github.com/jitsi/jitsi-meet/assets/52235796/dbb3c686-80d3-452e-89c1-0fca0a1bdebd)

**Comment by damencho** [comment]
Is your prosody config containing only the include

**Comment by MorganReid** [comment]
> conf.d/*.cfg.lua

yes .only one line
![image](https://github.com/jitsi/jitsi-meet/assets/52235796/59df51b8-66d4-41c1-a770-d9ea75f22f77)

**Comment by MorganReid** [comment]
> Is your prosody config containing only the include

yes,only one line
![image](https://github.com/jitsi/jitsi-meet/assets/52235796/dc81bdf1-9604-4642-beee-a4bc4b00c3b5)

**Comment by damencho** [comment]
I would move that file and reinstall prosody l.

**Comment by jayachandra9** [comment]
not able to join main room from breakout room for single participant
