### ISSUE TITLE
[Android] JitsiMeetView mic got muted when app is in background or turn off screen.

### ISSUE THREAD

**Issue by phuocvinasaver** [jitsi/jitsi-meet#14583]
JitsiMeetView mic got muted when app is in background or turn off screen after a while.

### Description:

Use JitsiMeetView in custom activity in background or turn off screen. Mic got mute until turn on android device or open app.

### Steps to reproduce:

1. Open app with custom activity has JitsiMeetView, say something -> app working (can hear mic)
2. Turn off screen (power button), say something -> app working (can hear mic)
3. Some minutes pass, say something -> app not working (can not hear mic)

### Expected behavior:

Can hear mic from turn off/background device like Jitsi App on Play Store.

### Actual behavior:

Can not hear mic from turn off/background device like Jitsi App on Play Store.

**Comment by saghul** [comment]
Can you reproduce it when using JitsiMeetActivity ?

You need to wire your activity to the view with the help of JitsiMeetActivityDelegate.

**Comment by hellocrane** [comment]
> Can you reproduce it when using JitsiMeetActivity ?
> 
> You need to wire your activity to the view with the help of JitsiMeetActivityDelegate.

I was checked with JitsiMeetActivity. It's work well. How to make JitsiMeetView work well like JitsiMeetActivity. I was implemented all JitsiMeetActivityDelegate method on CustomActivity, but it not work like JitsiMeetActivity itself.

**Comment by saghul** [comment]
Double check our activity and yours and make sure you delegate the same methods we do.

**Comment by phuocvinasaver** [comment]
@saghul Thank you for advice. It work now if I implement all like JitsiMeetActivity itself.
About it, please make `AudioModeModule.useConnectionService()` and `ConnectionService.abortConnections()` to public method. We can't access it from outside class (CustomActivity).

**Comment by saghul** [comment]
ConnectionService support is currently disabled in the code, you can ignore that.
