### ISSUE TITLE
Redirection if JWT is invalid or expired

### ISSUE THREAD

**Issue by roycecaballero** [jitsi/jitsi-meet#14584]
Hi, we are trying to deploy a Jitsi server that has JWT authentication.  If the authentication fails it will redirect to another site.

We have considered to add an nginx module for the jwt checking but it will add complexity to the setup. Is there a way that we can have this feature? If it is already available can you provide the documentation?

**Comment by damencho** [comment]
There is no such feature at the moment

**Comment by roycecaballero** [comment]
> There is no such feature at the moment

Hi @damencho thanks for the reply. What can you suggest for us to implement this? and is there any plans adding this feature?

**Comment by damencho** [comment]
> Hi @damencho thanks for the reply. What can you suggest for us to implement this? and is there any plans adding this feature?

You can try implementing it and create a PR, some config like tokenAuthUrl, but a different URL that when set and the backend returns jwt error to be redirected there the same way the redirection to tokenAuthUrl works.



> Also is there a way that we can transfer the JWT to the headers instead in the URL params?

I guess you can, but you will need to do a lot of modifications in jitsi-meet, the prosody modules and lib-jitsi-meet. You may need to also modify strophe.js and maintain a for of that, along the jitsi-meet and lib-jitsi-meet forks.

**Comment by roycecaballero** [comment]
Thanks for the input @damencho 

> You can try implementing it and create a PR, some config like tokenAuthUrl, but a different URL that when set and the backend returns jwt error to be redirected there the same way the redirection to tokenAuthUrl works.

Ill try to look into this sometime soon. We are still developing our app and my hands are kinda full.

> I guess you can, but you will need to do a lot of modifications in jitsi-meet, the prosody modules and lib-jitsi-meet. You may need to also modify strophe.js and maintain a for of that, along the jitsi-meet and lib-jitsi-meet forks.

I am planing to assemble an upstream url for this in nginx instead of maintaining a fork of jitsi meet. Would that be possible?

**Comment by saghul** [comment]
That sounds about right. You could pass it una header and put it in a query parameter with nginx.

**Comment by roycecaballero** [comment]
@saghul thanks for the confirmation. on what section can i add it in the nginx config? Upon reviewing it will be a round robin call. 

`location / {
        set $authenticator "";
        set $room "";

        if ($http_auth) {
            set $authenticator $http_auth;
        }
        if ($http_room) {
            set $room $http_room;
        }

        proxy_pass https://meet.enov8tive.app$request_uri;

        if ($authenticator != "") {
            proxy_pass https://meet.app/room=$room?jwt=$authenticator;
        }

        if ($authenticator = "") {
            proxy_pass https://app.com;
        }

        set $url 1;
        if ($arg_jwt = ''){
            set $url 0;
        }
        if ($url = 1){
            return 301 https://$host$request_uri;
        }
        return 301 https://app.com;
    }`

**Comment by saghul** [comment]
That looks alright to me. What's the problem with round-robin?
