### ISSUE TITLE
Jitisi audio only mode, disables my own camera

### ISSUE THREAD

**Issue by mikewguo** [jitsi/jitsi-meet#14586]
**Is your feature request related to a problem you are facing?**
In zoom, there is 'stop incoming video' capabiliity.  This is almost the same as Jitisi audio only mode. But there is an important difference: jitsi audio only mode disables my own camera.   Zoom's 'stop incoming video' still allows my own camera. In zoom, it’s possible to stop incoming video, but can still send my own camera over for others to see. So that others don’t feel i am strange, even though i have made the decision not to see their video, which is my private / personal decision, and it's because my own end of network bandwidth is limited.   It would be great if i can make my camera decision separate from 'stop incoming video' decisoin.

**Describe the solution you'd like**
i can make my camera decision separate from 'stop incoming video' decision.

**Describe alternatives you've considered**
There doesn't appear to be any settings in jitsi to allow me to do this.

**Comment by saghul** [comment]
Our feature is different, as you saw.

It's symmetric. You don't receive video and you don't send any either.

This is how we designed audio-only mode.

At this point we have no plans to implement a "stop incoming video" feature.
