### ISSUE TITLE
Recording could be auto-saved when meeting disconnects

### ISSUE THREAD

**Issue by sivaraam** [jitsi/jitsi-meet#14581]
### Description:

When a user has started a local recording of a meeting and the meeting seems to have been disconnected accidentally (due to network issue etc.), the local recording doesn't seem to have been saved. It's just completely lost in the void.

It would be great if the recording were retained in some way.

### Steps to reproduce:

1. Join a meeting
2. Initiate a local recording of the meeting.
3. Interrupt the meeting in some way (disconnect network / put the machine to sleep etc.)

### Expected behavior:

The recording of the meeting should be accessible in some way. It could stored automatically. Or user could be prompted on what to do about the recording when they get back to the meeting.

### Actual behavior:

The recording of the meeting is completely lost.

### Server information:

Used https://meet.jit.si

### Client information:

- Browser / app version: Chromium based browser
- Operating System: Ubuntu 22.04.4

**Comment by saghul** [comment]
Good catch. We do save the recording when the user reloads the page for example, but not if the meeting failed. Are you interested in sending a PR?

**Comment by sivaraam** [comment]
I'm not sure how easy it would be for someone with rusty JavaScript knowledge and no TypeScript experience. I could give a shot if anyone is willing to guide me a bit. Otherwise, I'll just let this be handled by the other contributors 🙂
