### ISSUE TITLE
[React Native][Android] Black screen instead of video

### ISSUE THREAD

**Issue by qnafin** [jitsi/jitsi-meet#14607]
black screen instead of video until some event occurs (moving to another screen, displaying a message, opening modal windows). I noticed on Android 11, in new versions of Android there is no such problem, in IOS there is no such problem.
```
OS: Android 11
{
   "react-native": "0.72.3",
   "@jitsi/react-native-sdk": "^2.0.2",
   "react-native-video": "6.0.0-beta.8",
   "react-native-gesture-handler": "2.14.1",
}

 ```

https://github.com/jitsi/jitsi-meet/assets/18189519/1d3b170b-4fc7-43f4-846d-b662b7a2b781

**Comment by saghul** [comment]
Does a device rotation also help?

**Comment by qnafin** [comment]
No
