### ISSUE TITLE
No video when attempting to use meet.jit.si, "this._constraints.height undefined"

### ISSUE THREAD

**Issue by jmbreuer** [jitsi/jitsi-meet#14609]
### Description:

When I launch a video meeting in https://meet.jit.si/ the call interface "works" but I can't use my camera / there is no video of me.

### Steps to reproduce:

1. Open https://meet.jit.si/
2. Click on "Start meeting"
3. (give browser consent to camera/microphone access, if necessary)
4. Below my name and the blue "Join meeting" button, there's an orange box "You need to enable microphone and camera access" (although my browser address bar icons show those to be enabled)
5. There is an error in the JavaScript console, see below

### Expected behavior:

Meet.jit.si works with video and audio.

### Actual behavior:

Meet.jit.si cannot access my camera/microphone.

There's an error message in the JavaScript console:

```
2024-04-09T09:20:54.370Z [features/base/tracks] <PE/</<>:  Failed to create local tracks 
Array [ "video" ]
 TypeError: this._constraints.height is undefined
    sc JitsiLocalTrack.js:118
    hl RTC.js:66
    hl RTC.js:48
    obtainAudioAndVideoPermissions RTC.js:186
    promise callback*obtainAudioAndVideoPermissions RTC.js:186
    createLocalTracks JitsiMeetJS.ts:344
    PE functions.web.ts:51
    promise callback*PE functions.web.ts:48
    i conference.js:539
    promise callback*createInitialLocalTracks conference.js:523
    init conference.js:724
    _start actions.web.ts:53
    promise callback*_start/< actions.web.ts:53
    R1 Redux
    <anonymous> middleware.ts:20
    <anonymous> middleware.ts:106
    <anonymous> middleware.ts:19
    <anonymous> middleware.ts:14
    <anonymous> middleware.web.ts:23
    <anonymous> middleware.any.ts:33
    <anonymous> middleware.ts:37
    <anonymous> middleware.ts:55
    <anonymous> middleware.ts:60
    <anonymous> middleware.ts:112
    <anonymous> middleware.ts:50
    <anonymous> middleware.ts:48
    <anonymous> middleware.ts:28
    <anonymous> middleware.ts:155
    <anonymous> middleware.ts:44
    <anonymous> middleware.ts:22
    <anonymous> middleware.ts:58
    <anonymous> middleware.ts:50
    <anonymous> middleware.web.ts:35
    <anonymous> middleware.web.ts:19
    <anonymous> middleware.any.ts:52
    <anonymous> middleware.ts:60
    <anonymous> middleware.web.ts:273
    <anonymous> middleware.ts:41
    <anonymous> middleware.ts:21
    <anonymous> middleware.ts:11
    <anonymous> middleware.ts:16
    <anonymous> middleware.ts:18
Logger.js:155:26
```

### Server information:

- Jitsi Meet version: https://meet.jit.si/ as of 2024-04-09 09:24 UTC

### Client information:

- Browser / app version: LibreWolf 124.0.1-1
- Operating System: Gentoo Linux x86_64

### Additional information:

As a baseline check, I tried https://brie.fi/ng in the same browser, works without issues.

**Comment by saghul** [comment]
Are you able to reproduce this with a different browser?

**Comment by jmbreuer** [comment]
I can reproduce it in a freshly created profile for LibreWolf. I'll try some Windows browsers I have access to "soon" (within the week or so).

It does work for me in Vivaldi 6.6.3271.50 (stable), and in Firefox (www-client/firefox-bin-124.0.1).

Should I (also) take this up with LibreWolf, then?

**Comment by saghul** [comment]
If it works with Firefox but not LibreWolf it's clear where the problem is.

I don't even know if we detect that browser and turn on the Firefox code paths.

**Comment by jmbreuer** [comment]
> I don't even know if we detect that browser and turn on the Firefox code paths.

How/where are you doing that? Is there a way to see the results of your browser detection?

LibreWolf identifies as Firefox of the release it is based on - [deviceinfo.me](https://deviceinfo.me/), for example, shows my LibreWolf as "Firefox 124.0.1".
From a JavaScript perspective, all the respective Firefox APIs should work as in Firefox itself; minus ones that give fingerprintable instance information, which will be replaced with generic, but compatible, data.

**Comment by saghul** [comment]
Check from of the first log lines when you open Jitsi Meet. Example: `2024-04-12T10:36:37.933Z [JitsiMeetJS.ts] <init>:  This appears to be firefox, ver: 125.0`

> From a JavaScript perspective, all the respective Firefox APIs should work as in Firefox itself; minus ones that give fingerprintable instance information, which will be replaced with generic, but compatible, data.

I don't know what they do, but if Firefox works and LibreWolf doen't, it does look like a problem with LibreWolf.

**Comment by saghul** [comment]
Can you try to place a breakpoint in the JitsiLocalTrack.js around line 105:

```
this._constraints = track.getConstraints();
```

What does that `this._constraints` get set to?

**Comment by jmbreuer** [comment]
> Can you try to place a breakpoint in the JitsiLocalTrack.js around line 105:
> 
> ```
> this._constraints = track.getConstraints();
> ```
> 
> What does that `this._constraints` get set to?

Aah, thank you, looks like we're onto something!

I hit that breakpoint a total of three times when the page loads; in all three instances, `track` is not defined ("unspecified"). I tried following up the call stack, and there's no place where track is defined; or where it would be obvious to me where it would come from (I'm not used to reading JavaScript / the future-promise coding model).

I'm happy to poke around further!

**Comment by Kobaxidze256** [comment]
> Does `getConstraints()` return `undefined` ?

If this was directed towards me, I don't have the time to check.

**Comment by saghul** [comment]
Ok, I have caught the problem! PR coming soon.
