### ISSUE TITLE
UI: observed failure of user to connect due to obscured button

### ISSUE THREAD

**Issue by afcady** [jitsi/jitsi-meet#14612]
User attempted to connect to room.

User failed to perform "press JOIN ROOM" step.

User reported that they believed they were in the room already, so did not need to perform the step.  User noted that self-view camera display was on.

Button was obscured by on-screen keyboard for touchscreen interface.

Possible solutions:

* Eliminate "JOIN ROOM" step entirely.
* Ensure application takes account of on-screen keyboards in its layout.
* Ensure user understands clearly whether or not they have joined the meeting using some other user interface indicator.
* Make JOIN ROOM a giant button in the middle of the video display.

**Comment by saghul** [comment]
Can you share a screenshot?

**Comment by afcady** [comment]
Platform was iphone/safari.  I'll try to reproduce it next time I have one of those at hand.

**Comment by afcady** [comment]
...I tried with android/fennec and it scrolled the background down behind the keyboard so that the button was still visible.  Although it seems to me that this UI still makes it too hard to know whether you are connected.  It should be obvious from a distance and _not_ require reading text.  A giant red border around the entire screen maybe that flashes green during connection attempts, turns solid during connection, then you can have it fade out with the menu.  I am just coming up with random ideas here.  The problem can be solved in as many ways as you can skin a cat.

It seems to me the most correct solution is to join the room automatically and then immediately start forwarding information to the user via the speaker and video display.  So that the user does not miss any information.  Allowing the user to be timely.  _Concurrent_ with the timely audio/video display of precious remote-originating information, the user can be prompted for information about their username and to connect local information streams -- i.e. the user can be given separate options to reveal (1) a name they type locally (2) audio they record locally (3) video they record locally.  The user can expose and unexpose their own local name information through a separate menu or option field on top of the remote video display just like exposing and unexposing their mic and camera.  None of these need to hold closed the remote video display or the audio stream.  The menu (a submenu, etc) could still be forced "always-on" on the display to capture required user input, without closing these streams.

The user shouldn't be prevented from timely access to remotely broadcast streams, just because they haven't interacted with the system (yet).  The system is losing information while waiting for a user interaction that isn't logically required.  The system is bleeding data.

Just my thoughts since I came back here, and thought about this some more!

**Comment by damencho** [comment]
To start getting and transmitting video/audio user interaction is needed. This is coming from protection implemented in webrtc itself, in the browsers.

**Comment by afcady** [comment]
I don't think that you are correct about user interaction needed after the self-view camera is already started?

**Comment by damencho** [comment]
We have recently updated the pre-join page to be enabled by default. We had many reports in the past few years people having problems with meetings because of that and after enabling pre-join screen where there is a user interaction before starting the webrtc session, those problems disappear. We have been running all our deployments like that for many years now.

**Comment by damencho** [comment]
You can read more about it here: https://webrtchacks.com/autoplay-restrictions-and-webrtc/

**Comment by afcady** [comment]
I'm not sure what you mean by pre-join page.  The problem I'm describing isn't the need for user-interaction at all, but that the user has to interact to switch between self-view and self+other view, which are two views that the user did visually confuse with one another, and falsely inferred a network connection.  (But the onscreen keyboard was obscuring 'JOIN ROOM" so that did make it harder than by design.)

Maybe the self-view when disconnected should be inconspicuously in the corner like it is normally when connected?

> Can you share a screenshot?

I got a screenshot but then I realized it contains a *lot* of personally identifying information.  But the effect was easy to reproduce every time the page loaded.  

I found another project talking about the same Safari issue:

https://github.com/element-hq/hydrogen-web/issues/181

They say their solution only works on iOS 13+.

Maybe helpful.  Maybe you are using the same solution and this iPhone is iOS 12-.  Sorry I neglected to get the versions.

**Comment by afcady** [comment]
Yeah I think there should be like an outer OSD frame that incorporates the corner self-view visually as the same layer.  A self-view of the mic audio over time there too.  And incoming/outgoing network over time.  The inside of the frame shows either the page or the connection form.  The OSD frame only ever disappears when connected.

Well I threw in some random stuff there.  But if you can see all that in your head you can see how much visual ambiguity it removes.  Anyway really the main issue is the layout is not displayed correctly on Safari.  But I just started thinking how easy a phone was to use when I was a kid and how hard to use this kind of software is for kids...

**Comment by afcady** [comment]
Yes that's the same screen.  I'm not sure if it's an old Safari version or what.  Will have the phone again some time later.  It would be better to fix or even leave in place the layout issue than redirect the phone to an error though.

**Comment by afcady** [comment]
Did you try screenshotting before pressing 'A' tho?

**Comment by saghul** [comment]
> Did you try screenshotting before pressing 'A' tho?

There is no difference.

> Yes that's the same screen. I'm not sure if it's an old Safari version or what. Will have the phone again some time later. It would be better to fix or even leave in place the layout issue than redirect the phone to an error though.

Well, iOS 12 has Safari 12, which we don't support unfortunately.
