### ISSUE TITLE
Bridge Channel Error when doing a Meeting in our Company Network 

### ISSUE THREAD

**Issue by DavisHahn** [jitsi/jitsi-meet#14616]
Hello there,

When I start a meeting with moderator rights and invite one person, the connection (mostly) works.
If more people join you cant hear them or see them if they are also in the company network. If you join using your mobile data for example there is no problem.

In our Sophos firewall we opened all needed ports (HTTP, HTTPS, UDP 10000 up to 20000 and TCP 4443) to our hosting server, which is hosted by another service provider.

![image](https://github.com/jitsi/jitsi-meet/assets/166624371/9f7042c6-1dfb-44f0-a76c-07b7bc4b36ad)

So the problem is most likely our Sophos firewall, but Jitsi was running fine with these opend ports for at least 2 months after a big infrastructure redesign.
The problem started to occur a month ago.

Everything below is hosted by only one server:
	|
||/ Name                          Version            Architecture         Description
+++-=====================-==================-============-=================================================
ii  jicofo                           1.0-1075-1               all          JItsi Meet COnference FOcus
ii  jitsi-meet                     2.0.9364-1               all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody      1.0.7874-1               all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web             1.0.7874-1               all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config 1.0.7874-1               all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2        2.3-92-g64f9f34f-1 all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  prosody                      0.11.9-2+deb11u2   amd64    Lightweight Jabber/XMPP server

Client information:
Lenovo Thinkpad with Ryzen 7 5700U
16GB RAM

- Browser / app version: Chrome version 123.0.6312.106
- Operating System: Windows 11 Pro

Additional information:
I looked in the console of chrome when more people are connected, this error occurs:

BridgeChannel.js:91 WebSocket connection to 'wss://konferenz.berdingbeton.de/colibri-ws/default-id/c32a2e246d4a4152/7b5c82c6?pwd=7fjhjqau3v5o1jsvd1qbik80s3' failed: 
_initWebSocket @ BridgeChannel.js:91
Logger.js:155 2024-04-09T06:56:12.441Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:155 2024-04-09T06:56:12.441Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 r @ Logger.js:155 Show 1 more frame Show less

**Comment by DavisHahn** [comment]
I just see that the picture is badly cropped, my bad.
![Network](https://github.com/jitsi/jitsi-meet/assets/166624371/4c735c95-3bc2-4f78-9b2a-bc297011c8d4)

**Comment by DavisHahn** [comment]
I have to test that with multiple people, but I got this error multiple times after a co worker joined my meeting.

**Comment by damencho** [comment]
You can try using sctp with the bridge 
https://github.com/jitsi/jitsi-meet/blob/36671d7c4f35d2ffaa021d366d7d931319f028ae/config.js#L77

Make sure it is not disabled in jicofo config: 
https://github.com/jitsi/jicofo/blob/5de340148fc19ccfc505322faf4117cc5c93965b/jicofo-selector/src/main/resources/reference.conf#L346
By default that is on. 

And same and for the bridge, make sure it is not disabled in its config
https://github.com/jitsi/jitsi-videobridge/blob/b08f133c24cdb3f5d4a213a3535f144a26d1a901/jvb/src/main/resources/reference.conf#L221
