### ISSUE TITLE
[Android] Microphone cuts out when app isn't in foreground

### ISSUE THREAD

**Issue by boppii** [jitsi/jitsi-meet#14615]
### Description:

Microphone cuts out when swapping apps and not going to homescreen first (enables pip and mic works fine)

### Steps to reproduce:

1. Open Jitsi app and go into call
2. Half swipe up / tap recent apps
3. Mic bubble will disappear and no noises will be picked up

### Expected behavior:

Microphone should continue to pick up noises

### Actual behavior:

Microphone stops working

### Server information:

- Jitsi Meet version: 
- Operating System: 

### Client information:

- Browser / app version: 24.0.1
- Operating System: One UI 6 | Android 14

### Additional information:

Bug disappears after downgrading to 24.0.0

**Comment by saghul** [comment]
Can you test 24.1.0?

**Comment by boppii** [comment]
i cant find apk for that version, do i have to compile it?

**Comment by saghul** [comment]
It's the upcoming beta, you can test it by joining the Play Store beta program.

**Comment by boppii** [comment]
tested 24.1.0 and it is still happening.
