### ISSUE TITLE
Start conference with screen sharing instead of camera

### ISSUE THREAD

**Issue by luca-rmg** [jitsi/jitsi-meet#14617]
**Platform**
iOS and Android 

**Is your feature request related to a problem you are facing?**
We are trying to start a conference with screen sharing as default video input instead of camera.

**Describe the solution you'd like**
A new feature flag to set the default video input can be a good solution

**Describe alternatives you've considered**
I tried to override the config "startScreenSharing", I'm not sure if it's an available key, I found it in source code, not in documentation. Anyway it doesn't work on iOS.

**Comment by damencho** [comment]
This is not supported by the browsers and by the spec: https://github.com/jitsi/jitsi-meet/commit/9cd42b988ddcc8cfeb884e660bf2c187922f2d83

**Comment by luca-rmg** [comment]
Ok, but I think on mobile clients this feature can be achieved using the native screen sharing
