### ISSUE TITLE
Gender roles on meeting close

### ISSUE THREAD

**Issue by mixmix** [jitsi/jitsi-meet#14614]
It's minor but this image annoys me a bunch:

![image](https://github.com/jitsi/jitsi-meet/assets/2665886/46771192-def8-483f-8102-7a8c8d14c906)
You see it after you close every call on meet.jit.si

Link: https://meet.jit.si/static/close3.html

It has a strong ["women laughing alone with salad"](https://knowyourmeme.com/memes/women-laughing-alone-with-salad) vibe. If you've done any media studies you probably also recognise the difference between the masculine and femanine stereotypes represented here:
- MAN: ready for everything, is stoic, looking for the threats, calm
- WOMAN: not really ready, just goofing around, flopping around, looking vulnerable and sexy (thankfully this one isn't present)

I LOVE jitsi, it's an integral part of my work. I couldn't have built tools for the commons without it.
I'd love a tiny change which is to make the closing experience of every call not feel like a boring and annoying gender stereotype :cry

**Comment by bumblefudge** [comment]
yapsi

**Comment by emcho** [comment]
Any discussion aside, this is simply not a Meet issue. I suggest you download Jitsi Meet and deploy it with an image that you approve of.

**Comment by mixmix** [comment]
@emcho can you suggest where to raise this? I tried looking for a contact or feedback. I'm honestly trying to make this tool more accessible, I'm a huge advocate

**Comment by metasj** [comment]
Propose some alternate images for the default?

**Comment by saghul** [comment]
To clarify, these images are not part of the open source project but of the deployment running as meet.jit.si, hosted by 8x8, Inc.

We will get feedback, but not contributions since that's up to the design team.

**Comment by emcho** [comment]
@mixmix I don't particularly love the image either. I am not particularly worried about possible interpretations, but I do dislike the fact that the images used for all people feel very stocky and not something one would see on an actual meeting. We will likely get to it at some point.

**Comment by mixmix** [comment]
Suggestions: could generate a few statically or dynamically

https://unsplash.com/s/photos/persona

thanks for further context. I hear it's not part of this repo. how do I feed back to the instance operator? Anyone know?
