### ISSUE TITLE
[React Native][Android] Buttons on Android 14 cannot be pressed

### ISSUE THREAD

**Issue by qnafin** [jitsi/jitsi-meet#14611]
Buttons on Android 14 cannot be pressed, but show animation. Everything works on lower versions of Android and iOS.

I had to patch and replace all the buttons with “react-native-gesture-handler” because I couldn’t find any other solution.

```import {TouchableOpacity, TouchableHighlight} from 'react-native-gesture-handler';```

You can still press, but only if you shift the pressure. The same applies to text input.

```
OS: Android 14
{
   "react-native": "0.72.3",
   "@jitsi/react-native-sdk": "^2.0.2",
   "react-native-gesture-handler": "2.14.1",
   "react-native-screens": "3.24.0",
}
```
https://github.com/jitsi/jitsi-meet/assets/18189519/8cf8e514-ce81-4624-bc88-825a13b55ad5

**Comment by saghul** [comment]
> "react-native-gesture-handler": "2.14.1",

We use version 2.9.0. Can you try downgrading? There might be some incompatibilities.

**Comment by qnafin** [comment]
> We use version 2.9.0. Can you try downgrading? There might be some incompatibilities.

it does not change anything, the error remains.

**Comment by saghul** [comment]
Can you reproduce the problem with our sample app?

**Comment by qnafin** [comment]
yes. if enable isNewArchEnabled. 

android/gradle.properties
> newArchEnabled=true

android/build.gradle 
> ndkVersion = "25.2.9519653"

Сan't disable this isNewArchEnabled in my application.

**Comment by saghul** [comment]
Gotcha.

I'm afraid you're out of luck at the moment.

We haven't enabled new arch on our side yet.

**Comment by saghul** [comment]
@Calinteodor is this similar to the other issue you are looking into?

**Comment by Calinteodor** [comment]
Yep. Seems the same.

**Comment by saghul** [comment]
Can you please drop a link here? Then let's close it and follow-up the other one, it has more context...

**Comment by Calinteodor** [comment]
Issue continues here #14794
