### ISSUE TITLE
E2EE option not available in Firefox

### ISSUE THREAD

**Issue by Be-ing** [jitsi/jitsi-meet#14626]
### Description:

Implementing E2EE with RTCRtpScriptTransform (https://github.com/jitsi/jitsi-meet/issues/9585) was implemented in https://github.com/jitsi/lib-jitsi-meet/pull/1696. At the time it was implemented in Jitsi, only WebKit supported that API. [As of Firefox 117](https://bugzilla.mozilla.org/show_bug.cgi?id=1631263), Firefox also supports RTCRtpScriptTransform. However, no option for E2EE appears in the security setting when Jitsi is run in Firefox 124.

### Steps to reproduce:

1. Join a meeting
2. Right click and go to security options

### Expected behavior:

Option to toggle E2EE is shown among the security options.

### Actual behavior:

No option regarding E2EE is shown.

Opening the meeting in Chromium shows the E2EE setting as expected.

### Server information:

Using meet.jit.si

### Client information:

- Browser / app version: Firefox 124.0.1 
- Operating System: Fedora Linux 39

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This is already available and implemented as you pointed the PR. 
You can use the URL params to enable it.

As the comment says it is experimental and turned off by default in jitsi-meet and on meet.jit.si
https://github.com/jitsi/jitsi-meet/blob/42a0c31a3acdf8a9886e9ac00a7bd8b85996ca2b/config.js#L615

**Comment by Be-ing** [comment]
Did you read the bug report? Within the same meeting on meet.jit.si, the option was available in Chromium. It is a bug that it was not shown in Firefox.

**Comment by saghul** [comment]
It's behind an experimental flag still. You can flip the flag with a URL parameter for testing.

**Comment by Be-ing** [comment]
If it's behind an experimental flag, why does the option appear in Chromium without any special URL parameter?

**Comment by saghul** [comment]
No, the experimental flag is for the Script transform approach taken by Safari and lately Firefox.

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/blob/b470c201b28a8103d7d1bd8cf44c6dc3651caa34/config.js#L619

**Comment by Be-ing** [comment]
> No, the experimental flag is for the Script transform approach taken by Safari and lately Firefox.

Ah, that explains it. So adding `#enableEncodedTransformSupport=true` to the URL should enable the option? What is required for this to no longer be experimental?

**Comment by saghul** [comment]
> So adding `#enableEncodedTransformSupport=true` to the URL should enable the option?

Correct.

> What is required for this to no longer be experimental?

For it to work properly. Safari had a bug where they only passed one of the simulcast layers through the transformer, for example.

**Comment by neuhaus** [comment]
Appending #enableEncodedTransformSupport=true to the URL still doesn't work for me with Firefox 150. Is it my Jitsi instance?

**Comment by neuhaus** [comment]
> Appending #enableEncodedTransformSupport=true to the URL still doesn't work for me with Firefox 150. Is it my Jitsi instance?

For what it's worth, I do see the E2EE option in a Chromium based browser such as Brave.

Also I just tested it on beta.meet.jit.si using Firefox 151:

Result: Even when adding #enableEncodedTransformSupport=true to the URL, the e2ee option doesn't show up on Firefox. It does show up on Brave.

The documentation over at https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#enableencodedtransformsupport no longer even mentions Firefox as a browser that requires this option, it only mentions Safari.

@saghul Is it supposed to work? Can you reproduce the issue? Do I need to change configuration of my firefox browser to make it work? I was under the impression that's no longer the case. Thanks!

**Comment by saghul** [comment]
TBH I haven't tested that in a while. I'll give it a try while working on a couple of e2ee PRs.
