### ISSUE TITLE
Ordered list of when hands were raised for moderators

### ISSUE THREAD

**Issue by jayofdoom** [jitsi/jitsi-meet#14625]
**Is your feature request related to a problem you are facing?**
In a busy meeting, with lots of people attempting to participate, it can be difficult to correctly execute "FIFO" style flows due to difficulty identifying the order hands were raised. When multiple hands are raised, there is no way to indicate which one was raised first -- this means a human moderator must pay perfect attention to order speakers properly.

**Describe the solution you'd like**
Some sort of ordered list of hands-raised accessible to moderators (or all users?). Ideally it'd be consistently ordered across all clients.

**Describe alternatives you've considered**
Watching very carefully. This wears down as quantity of video meetings in a day increases :)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This is already the case in the participants pane.

**Comment by jayofdoom** [comment]
Thanks damencho, sorry for the churn.

**Comment by damencho** [comment]
👍
