### ISSUE TITLE
State features/base/participants -> local -> role is all time "moderator" but put on jwt moderator false

### ISSUE THREAD

**Issue by ThonyBat** [jitsi/jitsi-meet#14633]
### Description:

Role value in state "features/base/participants" then "local" is always "moderator" even without moderator: true in jwt token

### Steps to reproduce:

1. Generate token JWT without specify moderator true
2. Use token on connect Jitsi Meet
3. See on state "features/base/participants" and "local", role is "moderator" waiting "participant"

### Expected behavior:

role on local waiting "participant"

### Actual behavior:

role on local is "moderator"

### Server information:

- Jitsi Meet version: /
- Operating System: jitsi.panlalab.fr

### Client information:

- Browser / app version: Chrome 123.0.6312.107
- Operating System: Windows 11

### Additional information:

Testing with add on user context, affiliation but not work

![image](https://github.com/jitsi/jitsi-meet/assets/73229853/471ee5b9-da84-4168-8432-18770e5a835a)

**Comment by saghul** [comment]
What prosody modules have you loaded? That doesn't work out of the box unless module is loaded.
