### ISSUE TITLE
Let's encrypt fails on fresh install on Ubuntu 22.04

### ISSUE THREAD

**Issue by maxfloden** [jitsi/jitsi-meet#14635]
### Description:

Let's encrypt fails when I am following the self hosting install guide for Ubuntu to make a fresh install on Ubuntu 22.04 using nginx-full.
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/ 

### Steps to reproduce:

Following the guide:
1. `sudo apt install jitsi-meet`
1. UI screen to select Let's Encrypt - runs ok
2. UI screen to enter email address - after this script stops for a long time (minutes) on `Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz` before producing error `Download error` 
3.  If I try to download file manually by pasting link into a browser, it downloads fine.

### Actual behavior:

```
This script will:
- Need a working DNS record pointing to this machine(for hostname )
- Install additional dependencies in order to request Let’s Encrypt certificate (acme.sh)
- Configure and reload nginx or apache2, whichever is used
- Configure the coturn server to use Let's Encrypt certificate and add required deploy hooks
- Configure renew of certificate

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1032    0  1032    0     0   3703      0 --:--:-- --:--:-- --:--:--  3712
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  217k  100  217k    0     0   954k      0 --:--:-- --:--:-- --:--:--  968k
[Mon Apr 15 22:00:22 UTC 2024] Installing from online archive.
[Mon Apr 15 22:00:22 UTC 2024] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Mon Apr 15 22:02:35 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
[Mon Apr 15 22:02:35 UTC 2024] Download error.
Install error
中国大陆用户请参考:
https://github.com/acmesh-official/acme.sh/wiki/Install-in-China
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh: line 60: /opt/acmesh/.acme.sh/acme.sh: No such file or directory
Issuing the certificate from Let's Encrypt failed, continuing ...
You can retry later by executing:
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh info@xxx.yy

```
### Server information:

- Jitsi Meet version: 9364
- Operating System: Ubuntu 22.04

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

Script continues to run, so it is easy to miss the error, you need to scroll up to see it
It suggests this `You can retry later by executing:
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh info@xxx.yy`  but it just keeps failing

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
> Install error
> 中国大陆用户请参考:
> https://github.com/acmesh-official/acme.sh/wiki/Install-in-China

I guess this will give you more details. 

If you install it before running the installation it will work.

**Comment by maxfloden** [comment]
> > Install error
> > 中国大陆用户请参考:
> > https://github.com/acmesh-official/acme.sh/wiki/Install-in-China
> 
> I guess this will give you more details.
> 
> If you install it before running the installation it will work.

I am in Europe and I don't speak Chinese so that link is not very helpful in my case.

**Comment by damencho** [comment]
Then that is strange. I was thinking that it detects something to show that to you. 
I have never seen the error above and this error message.

**Comment by damencho** [comment]
What os and version you are using?

**Comment by damencho** [comment]
Try executing this with filling up the correct email:
```
export HOME=/opt/acmesh
curl https://get.acme.sh | sh -s email=$EMAIL
```
I think that is failing for you. If the above command is failing you can look for help: https://github.com/acmesh-official/acme.sh/issues

**Comment by maxfloden** [comment]
For anyone else who may encounter this - it turned out problem was because my server was ipv6 only (ie no ipv4 support) which is not supported by get.acme.sh

More info in this community thread: https://community.jitsi.org/t/lets-encrypt-fails-on-fresh-install-on-ubuntu-22-04/131134/6

**Comment by saghul** [comment]
You are living too far ahead in the future! 😅
