### ISSUE TITLE
android release-sdk throws error

### ISSUE THREAD

**Issue by xaldarof** [jitsi/jitsi-meet#14634]
### Description:
I am running
sudo ./android/scripts/release-sdk.sh /opt

### Steps to reproduce:

- Clone repository
- npm install
- sudo ./android/scripts/release-sdk.sh /opt #(MacOS M1)

### Expected behavior:

I am updated icon color, and I want to publish changes to own repository

### Client information:

- Jitsi Meet version: Newer
- Operating System: MacOS M1 (14.4.1 (23E224))

### Additional information:
Here is log:

Germes.Messenger.jitsi-meet % sudo ./android/scripts/release-sdk.sh /opt

Releasing Jitsi Meet SDK 99.0.0

Node.js v21.7.2

> Task :sdk:bundleReleaseJsAndAssets FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 19s
242 actionable tasks: 241 executed, 1 up-to-date

**Comment by saghul** [comment]
> Node.js v21.7.2

Try Node 16.

**Comment by xaldarof** [comment]
Node.js 21 is not installed

node --version
- v16.20.2

**Comment by xaldarof** [comment]
Thanks for support, helped [issue](https://github.com/jitsi/jitsi-meet/issues/3807)
