### ISSUE TITLE
[Android] Whiteboard is not available in Android client

### ISSUE THREAD

**Issue by ildar** [jitsi/jitsi-meet#14630]
### Description:

Whiteboard works in web but not in Android app

### Steps to reproduce:

1. open

### Expected behavior:

view and change the white board contents

### Actual behavior:

none

### Server information:

meet.jit.si

### Client information:

- Browser / app version: 23.6.1
- Operating System: Android 14

**Comment by saghul** [comment]
Update to the latest version, it is now available.

**Comment by ildar** [comment]
Thanks for the info!
Are the Android app versions __tagged__ in the git repo? I don't see it.
Otherwise how can one know that a new version is out?

P.S. using F-Droid version.

**Comment by saghul** [comment]
It's available on the latest Play Store beta version, a new stable will be tagged soon.

**Comment by ildar** [comment]
Landed in F-Droid, thanks.
/close
