### ISSUE TITLE
The effect of noise suppression on Mobile app (android and ios)  is poor

### ISSUE THREAD

**Issue by NimbleDev** [jitsi/jitsi-meet#14632]
### Description:

The effect of noise suppression on Mobile app (android and ios)  is so poor that when two participants are in the same and they turn on the mic at the same time, the noise is unbearable.

### Steps to reproduce:

when two participants are in the same and they turn on the mic at the same time, the noise is unbearable.

### Expected behavior:

Is there any config to improve the effect of noise suppression?

### Client information:

Android / ios APP

**Comment by NimbleDev** [comment]
> What version of the app are you using? We just fixed a bad audio quality regression in the upcoming 24.2.0 release.

We use react native sdk to build the app. Has the fix been applied to rn sdk？

**Comment by saghul** [comment]
It will be part of the next release.

**Comment by NimbleDev** [comment]
> It will be part of the next release.

may I ask when will the release come out?

**Comment by saghul** [comment]
It should come out this week.

**Comment by NimbleDev** [comment]
> It should come out this week.

so the rn sdk update is part of the release?

**Comment by NimbleDev** [comment]
> Each SDK is a separate release, but we usually do them in tandem.

ok，thx a lot!  Looking forward to your release~
