### ISSUE TITLE
efficient voice call recording in jitsi

### ISSUE THREAD

**Issue by alirexanaserpour** [jitsi/jitsi-meet#14644]
I'm trying to create a call application that has a recording feature for each call, I found Jitsi Meet which has the recording feature supported internally, Jitsi uses a service called jibri for recording, Also jibri uses virtual screen and a headless chrome to record calls and it consumes too much resources even for simple voice calls. (Note that jitsi doesn't have a voice call feature, It supports only simple meetings with video and audio enabled and I use a meeting with video muted to simulate a audio call)

My question is, is there any way to record these calls without processing too much data like what jibri does ?

I tried to use [gst-meet](https://github.com/avstack/gst-meet), It does work and consumes a lot less resources, but I wanted to know if there is a way to use jibri, but without processing video data so it consumes less resources.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
