### ISSUE TITLE
Adding no video images to Android requires a single click to appear

### ISSUE THREAD

**Issue by Love-Fat** [jitsi/jitsi-meet#14653]
Adding no video images to Android requires a single click to appear

**Comment by saghul** [comment]
Can you please elaborate or show a screenshot? Not sure what "video images" means here.

**Comment by Love-Fat** [comment]
![_20240419153230](https://github.com/jitsi/jitsi-meet/assets/22971447/df021aea-e540-4869-9f2f-63f03f0c62e8)

Both sides have turned on their cameras, but they can't see the footage

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by Love-Fat** [comment]
The server uses 7001, while the SDK uses 9364

**Comment by Love-Fat** [comment]
As long as the screen is displayed once, only one phone will not display, and the other phone will display normally. Turn on and off the camera button, and the other phone will display normally

**Comment by saghul** [comment]
That SDK is too new for thaty backend. Also, we don't support builds at random commits.

If you are building your own SDK please build a release tag: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md
