### ISSUE TITLE
No visible network error when trying to connect to a meet and network is blocked by captive portal

### ISSUE THREAD

**Issue by afcady** [jitsi/jitsi-meet#14660]
Platform is Android LineageOS with native Jitsi app.

Pressing "Join Meeting" causes the self-view to dim and a spinner to display over the center of the screen.

There is no other information presented to the user.  The spinner will probably spin forever.

The correct behavior would be to:

*  detect the network situation
* report it to the user
* since it's a captive portal compliant with the standards to publish itself, either:
    * redirect to the Wifi network / captive portal login page
    * notify the user of the need to log in to the network with an error
 
It would be really nice if there would be some network debugging information visible in the app.  Like tell me if I have connectivity to the next hop, if I have an IP on the internet or not, if I can reach local DNS, if I can reach 8.8.4.4 style global DNS, etc.  In a way that lets me get this information over the phone from a non-technical person that is looking at a screen that I can't see.

**Comment by damencho** [comment]
Can you upload logs from this?
