### ISSUE TITLE
Changing Default Virtual Background

### ISSUE THREAD

**Issue by sentaycan** [jitsi/jitsi-meet#14665]
I connect to my container and replace one of the default backgrounds in /usr/share/jitsi-meet/images/virtual-background with my own background.I make the names the same i.e. background-6.jpg.But the replaced background is black and cannot be clicked.As in the following picture

![Ekran görüntüsü 2024-04-22 154338](https://github.com/jitsi/jitsi-meet/assets/167755398/df82d40f-51a0-4561-b7a9-28990ebfcb69)

Can anyone help me why I'm getting this error or how do I add my own background permanently?

**Comment by saghul** [comment]
What image format did you use?
