### ISSUE TITLE
After logging into the local network captive portal, Jitsi Meet needs a "disconnect/reconnect" operation to connect.

### ISSUE THREAD

**Issue by afcady** [jitsi/jitsi-meet#14661]
Platform is LineageOS with native Jitsi Meet app.

If I'm required to log into the wifi.  Then Jitsi will spin forever trying to connect.  See  #14660.

If I log into the wifi while Jitsi is alread yspinning, then Jitsi still spins continuously apparently forever.

(I let it run at least two whole minutes.)

If I press the red DISCONNECT button then rejoin the meeting, the connection is established.

The user should not be required to reset the connection manually.

**Comment by damencho** [comment]
Can you upload logs from such session?

**Comment by afcady** [comment]
Sorry I can't find out how to do that.  It's very easy to reproduce though.  You can just put on airplane mode, press join room in jitsi, then turn off airplane mode.

**Comment by saghul** [comment]
That is a good test, thanks for pointing it out.

You can use adb logcat to grab all the logs when testing the condition.

**Comment by afcady** [comment]
Pretty sure the issue is still there.
