### ISSUE TITLE
Jitsi freezes at "Waiting For Moderator to let you join" after logging in on web

### ISSUE THREAD

**Issue by CSMMaster** [jitsi/jitsi-meet#14679]
### Steps to reproduce:

1.  Create a new room in Jisti Meet app, Select to Join and Login as Moderator
2.  Login via Github as per usual. Enter code from SMS
3.  Github confirms my login, window closes, and website fails to provide option to switch to app. App stays frozen "Waiting for Moderator to let you join"

### Expected behavior:

 After entering my credentials, a dropdown should appear letting me choose to open the meeting in the app.

### Actual behavior:

 No dropdown menu provided
 Screenshot not feasible since it shows nothing.

### Server information:

- Jitsi Meet version: webbased jit.si
- Operating System: unknown

### Client information:

- Browser / app version: Brave v1.65.114
- Operating System: Ubuntu

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
I just tested the flow and it works with Brave. 

Is is possible that you logged in with Google or Facebook before and that uses the same email as the github account?

**Comment by CSMMaster** [comment]
> I just tested the flow and it works with Brave.
> 
> Is is possible that you logged in with Google or Facebook before and that uses the same email as the github account?

Negative. I have always used the GitHub account to login. That is why I am a little confused as to why it is not redirecting me to the app.

It worked great until the last update. I have tried uninstalling and reinstalling several times with a full purge each time. Still the same outcome.

**Comment by damencho** [comment]
Do you have any console errors?

**Comment by CSMMaster** [comment]
> Do you have any js console errors in the browser?

No errors.

**Comment by asmaloney** [comment]
Could this be related to https://github.com/jitsi/jitsi-meet/issues/14672 ?

That one's a show-stopper for me and results in similar symptoms to those described.

**Comment by CSMMaster** [comment]
Based on their findings, if I remove the “#” before “config” it should work. I’ll give this a try. If that works, def a coding issue for the URL called out by the login function.

**Comment by asmaloney** [comment]
I couldn't get it to work no matter what I changed, so I'm just going to have to wait until they update production to see if it worked.

**Comment by CSMMaster** [comment]
> I couldn't get it to work no matter what I changed, so I'm just going to have to wait until they update production to see if it worked.

Just gave it a try. No go. Found a single "#", removed it, and still failed to load into the app.

**Comment by damencho** [comment]
Can you open the js console, click preserve logs, try to join with login and upload the logs here after the failure?

**Comment by saghul** [comment]
I am a bit confused since you also mentioned the app. Are you using the Brave browser exclusively for this test?

**Comment by CSMMaster** [comment]
> I am a bit confused since you also mentioned the app. Are you using the Brave browser exclusively for this test?

I am using the app to create the meeting room. When I try to join as Moderator, it takes me to the login page on the browser. After entering my “credentials”, it freezes, leaving me in limbo waiting for the moderator to let me in.

I did the same exercise strictly through Jitsi online, and it worked flawlessly. So, there is a disconnect between the app and the browser login.

@damencho - I have not had a chance to perform the js console log report. Will try to do that today.

**Comment by CSMMaster** [comment]
Sorry, guys. Been a long weekend/week. I’ll try to get this js error report posted this evening.

**Comment by sivaraam** [comment]
I faced a version of this issue randomly on the browser itself. It's not clear what triggers it but when we try to join them eeting using a room link, it randomly gets stuck with the "Waiting for moderator..." screen. If there's something that we might be potentially doing wrong with how we're joining, kindly let us know.

<details><summary>Screenshot</summary>
<p>

![240614_16h35m34s_screenshot](https://github.com/jitsi/jitsi-meet/assets/12448084/e85caffb-5a49-46b7-af61-04b5479a7b4e)

</p>
</details>

**Comment by sivaraam** [comment]
This still occurs.
