### ISSUE TITLE
Emojis reactions cover menu bottom buttons

### ISSUE THREAD

**Issue by magdawernik** [jitsi/jitsi-meet#14687]
### Description:

In the mobile version emojis reactions are covering the last buttons in the dropdown menu, disabling clicking in the last options.

### Steps to reproduce:

1. Enter the call 
2. Click on the ¨three dots¨ icon of ¨More Options¨

### Expected behavior:

The user should be able to click on the last possible option from the dropdown menu of ¨More Options¨

### Actual behavior:

In the mobile version emojis reactions are covering the last buttons in the dropdown menu, disabling clicking in the last options.

![image](https://github.com/jitsi/jitsi-meet/assets/134924316/1d908172-cccc-4caa-be04-aea379037741)

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Chrome
- Operating System: Android

**Comment by ishsarin** [comment]
Hi, if this is still open, can I work on this?
