### ISSUE TITLE
The ability to join as a visitor without capturing video and audio(like startWithVideoMuted for visitors)

### ISSUE THREAD

**Issue by Anfieldd** [jitsi/jitsi-meet#14681]
Hi guys, I'm facing a problem when I join a conference as a visitor with enabled audio and video, the following happens:

1. app initializes, local tracks are created
2. then we see that I should be a visitor and execute dispatch(redirect()) which destroyed local tracks(but not stop, they're still active)
3. then I joined as a visitor but my camera is still working(mic too) and glowing green
<img width="1679" alt="Screenshot 2024-04-25 at 11 31 50" src="https://github.com/jitsi/jitsi-meet/assets/32684253/c8deea91-1c1d-4396-86c0-1f0aba77f0a9">

Perhaps you can add startWithAudioMuted and startWithVideoMuted for visitors to the config or destroy the tracks and not capture audio and video?

**Comment by saghul** [comment]
What version of Jitsi Meet are you using?

**Comment by Anfieldd** [comment]
[2.0.9164](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_9164) release with some new commits for visitors. Can you please check it on meet.jit.si? Because I don't know how I can join the meeting as a visitor in meet.jit.si

**Comment by saghul** [comment]
Ping @damencho

**Comment by damencho** [comment]
@Anfieldd you can enter with 2 participants, send one of them as visitor and then anter with 3rd which will be a visitor. Do you repro with that?

**Comment by Anfieldd** [comment]
> ou can enter with 2 participants, send one of them as visitor and then anter with 3rd which will be a visitor. Do you repro with that on meet?

Thank you, it's not reproduced in meet.jit.si. I'll try to update my project to the latest version)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
