### ISSUE TITLE
Android app will go to low bandwith mode whenever on mobile network (LTE)

### ISSUE THREAD

**Issue by denisvitez** [jitsi/jitsi-meet#14686]
### Description:

Mobile app (Android) will go to low bandwidth mode and disable video whenever I would switch from WiFi to mobile network LTE. If I run speed test on mobile, it shows about 130Mbps down and 40Mbps up with 24ms ping. So I think the connection should be more than enough to support 2 people on call. Also when there is no video, there is no audio too, so not sure if this is related or a separate issue. I have checked in the mobile app if there is any setting to disable this "saving bandwidth" mode, but didn't found any.

### Steps to reproduce:

1. Join a call with WiFi
2. Enable camera and see that it works, green bars are shown next to the person
3. Disconnect WiFi to connection is made over LTE
4. Camera will stop working and red bars are shown next to the person
5. Reconnect to WiFi
6. Video will start working again

### Expected behavior:

Video and audio should continue working on LTE given a sufficient bandwidth (130/40).

### Actual behavior:

Application displays message "Video has been turned off to save bandwidth".
Video and audio stop working.

### Server information:

- Jitsi Meet version: 2.0.9457-1
- Operating System: Ubuntu Server 22.04

### Client information:

- Browser / app version: Android application from GPlay, version 24.2.2 build 16757163
- Operating System:

### Additional information:

/

**Comment by saghul** [comment]
It doesn't look like a low bandwidth problem but rather a connectivity issue when youa re using LTE. Can you reproduce the problem if you start on LTE directly?

Do you observe the same when using meet.jit.si rather than your own server?

**Comment by denisvitez** [comment]
Hello,
so if starting directly on LTE it is the same (doesn't work). But joining with LTE to meet.jit.si works. So this then seems more like a server issue, are there any settings related to this?

**Comment by saghul** [comment]
In your tests, where the server and the mobile part of the same network?

**Comment by denisvitez** [comment]
Uff I did just test with WiFi outside the office network and it is the same issue. I have also tried joining with my PC using the LTE hotspot (doesn't work). So my guess is now that there is something not correctly configured either with port forwarding or with Nginx reverse proxy manager on the server.

**Comment by saghul** [comment]
Looks like the media port (10000 UDP by default) might not be properly forwarded to the JVB server.
