### ISSUE TITLE
Visitor forcePromote work not as well

### ISSUE THREAD

**Issue by SkyTaurus** [jitsi/jitsi-meet#14699]
If I send a message from the plugin from the visitor prosody with parameters

` local promotion_request = st.iq({
        type = 'set',
        to = 'visitors.'..main_domain,
        from = local_domain,
        id = iq_id })
                                :tag('visitors', { xmlns = 'jitsi:visitors',
                                                   room = jid.join(jid.node(room.jid), muc_domain_prefix..'.'..main_domain) })
                                :tag('promotion-request', {
        xmlns = 'jitsi:visitors',
        jid = occupant.jid,
        time = 5,
        userId = user_id,
        forcePromote = true;
      }):up();`

then the moderator will receive a message about the need to confirm the role change. Discussion here https://community.jitsi.org/t/jwt-and-extra-large-conference/129944/134

**Comment by saghul** [comment]
Ping @damencho

**Comment by damencho** [comment]
Yeah, I asked for this issue in the forum thread from the link above. I will try to look at it this weeks when I have some time.

**Comment by damencho** [comment]
https://community.jitsi.org/t/jwt-and-extra-large-conference/129944/339?u=damencho
