### ISSUE TITLE
HTTP instead HTTPS

### ISSUE THREAD

**Issue by ARogovsky** [jitsi/jitsi-meet#1469]
Hi!
Is this prossible for switch jitsi-meet from 443 to 80 without ssl?

**Comment by damencho** [comment]
Please use the mailnglist for questions and problems, before opening issue.

No, it will not work, https is a requirement for webrtc to work. If you do not have a certificate you need to use self-signed certificates or use let's encrypt one.

**Comment by lizhaoch** [comment]
I used the **starssl** certificate issued, but the ios has been an error like :  
cannot load "/config" from "https://********^&(&*.com/abc?^*^*"

I don't know why

**Comment by lizhaoch** [comment]
@damencho @tomdee @ibc @geekgonecrazy @ARogovsky

**Comment by ibc** [comment]
@lizhaoch, as told above, please use the mailing list for questions, and don't force other persons into this invalid issue.

**Comment by lizhaoch** [comment]
OK  I just do it
