### ISSUE TITLE
remove Jitsi sample URLs

### ISSUE THREAD

**Issue by fredc15** [jitsi/jitsi-meet#1470]
Hi,

I've successfully setup Jitsi on my server.  I want to remove the sample urls after my main url.

any help is appreciated

**Comment by saghul** [comment]
Please use the mailing list for questions.

**Comment by fredc15** [comment]
how do I use the mailing list?

**Comment by damencho** [comment]
https://jitsi.org/Development/MailingLists
Just subscribe and send email, or just send email and wait for admin approval of the mail.
