### ISSUE TITLE
Autoexport whiteboard upon termination of meeting.

### ISSUE THREAD

**Issue by TreyThomas93** [jitsi/jitsi-meet#14709]
**Is your feature request related to a problem you are facing?**
We are needing to automatically export the whiteboard to our backend server upon termination of a meeting.

**Describe the solution you'd like**
Set a config url to send the whiteboard data to.

**Comment by saghul** [comment]
While desirable, implementing this has some challenges. The backend does not have access to the data because it's end-to-end encrypted. As such, a snapshot can only be created by the client.

**Comment by TreyThomas93** [comment]
> While desirable, implementing this has some challenges. The backend does not have access to the data because it's end-to-end encrypted. As such, a snapshot can only be created by the client.

Any idea how we can automatically take a snapshot from a moderator or host when meeting is terminated?

**Comment by saghul** [comment]
Not sure. @mihhu ia the a programmatic way to get a snapshot?
