### ISSUE TITLE
deep-linking-image.png missing, relates to " File deep-linking-image.png is missing #5409 "

### ISSUE THREAD

**Issue by un99known99** [jitsi/jitsi-meet#14708]
As far as I have seen from nginx logfile the issue reported as #5409 is again alive:

root@jitsi[/var/log/nginx] # ll /usr/share/jitsi-meet/images/deep-linking-image.png
ls: cannot access '/usr/share/jitsi-meet/images/deep-linking-image.png': No such file or directory

root@jitsi[/var/log/nginx] # zgrep deep-linking-image.png *.log
access.log:88.888.888.888 - - [03/May/2024:12:31:47 +0200] "GET /images/deep-linking-image.png HTTP/1.1" 404 435 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0"
error.log:2024/05/03 12:31:47 [error] 1421#1421: *173 open() "/usr/share/jitsi-meet/images/deep-linking-image.png" failed (2: No such file or directory), client: 88.888.888.888, server: jitsi.meet.example.org, request: "GET /images/deep-linking-image.png HTTP/1.1", host: "host.jitsi.meet.example.org"

According to #5409 the correct one is already there:
root@jitsi[/var/log/nginx] # ll /usr/share/jitsi-meet/images/logo-deep-linking.png
-rw-r--r-- 1 root root 6436 Feb 23  2023 /usr/share/jitsi-meet/images/logo-deep-linking.png

**Comment by damencho** [comment]
Are you using jitsi-meet without modifications? What version is that?

I see the image is still referenced in the CSS: https://github.com/jitsi/jitsi-meet/blob/5601a62b60800708d08fa9183d0c00d95a16b8cb/css/deep-linking/_desktop.scss#L41
But it is referenced from a class that is no longer used `deep-linking-desktop`. 

@saghul @horymury any ideas is that used somewhere, can we drop it?

**Comment by saghul** [comment]
We can probably drop it. It used to be a static file but got rewritten to React and likely forgotten.

**Comment by un99known99** [comment]
my version is latest official:

ii  jitsi-meet                          2.0.9457-1                       all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                  1.0.7952-1                       all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver               1.0.7952-1                       all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                      1.0.7952-1                       all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config               1.0.7952-1                       all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                  2.3-105-ge155b81e-1              all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                          0.4.1-jitsi1                     all          baseXX encoding/decoding library for Lua
