### ISSUE TITLE
Desktop three dots options menu are different in web and desktop.

### ISSUE THREAD

**Issue by suryakantgupta321** [jitsi/jitsi-meet#14705]
Description:
We are facing issue with three dots menu in Desktop we are not able to see all options as it is visible in Web.

Actuall menu in Desktop
![image](https://github.com/jitsi/jitsi-meet/assets/106071580/afdc6eef-b75b-4041-91a8-08920064f446)

Expected menu in Desktop
![image](https://github.com/jitsi/jitsi-meet/assets/106071580/658c29b4-bfa7-4245-91cc-25b75aca7bab)

**Comment by saghul** [comment]
Are you passing any config overrides?

**Comment by suryakantgupta321** [comment]
> Are you passing any config overrides?

Yes we are doing override on these parameter 
{
          filmstrip,
          subject,
          hideConferenceSubject,
          requireDisplayName,
          defaultLocalDisplayName,
          enableWelcomePage,
          startWithVideoMuted,
          hideDisplayName,
          prejoinConfig,
          fileRecordingsEnabled,
          faceLandmarks,
          startAudioOnly,
          recordingService,
          toolbarButtons,
          constraints,
        }

But its not related to config as I checked in iframe .
![image](https://github.com/jitsi/jitsi-meet/assets/106071580/050b20cb-d11a-46dc-85ec-eca8b2859577)

There is this css overflow hidden that is causing the issue when I manually change it to overflow auto then those elements becomes visible

**Comment by damencho** [comment]
`toolbarButtons,` is exactly what controls show/hide of those buttons.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
