### ISSUE TITLE
[Debian] Videos of app participants keep flapping

### ISSUE THREAD

**Issue by steepnought** [jitsi/jitsi-meet#14707]
On 2024-04-23 there were the following Debian package updates:

```
jicofo 1.0-1075-1 -> 1.0-1078-1
jitsi-meet 2.0.9364-1 -> 2.0.9457-1
jitsi-meet-web-config 1.0.7874-1 -> 1.0.7952-1
jitsi-meet-prosody 1.0.7874-1 -> 1.0.7952-1
jitsi-videobridge2 2.3-92-g64f9f34f-1 -> 2.3-105-ge155b81e-1
jitsi-meet-web 1.0.7874-1 -> 1.0.7952-1
```

With these updates,  the videos of participants joining with the Jitsi Meet app (23.6.1 from f-droid) keep flapping between on and off.

The jvb.log gets filled with
```
BandwidthAllocator.allocate#278: Sources suspended due to insufficient bandwidth
```
although available bandwidth is definitely not the problem (neither server-side nor client-side). This is on Debian Bookworm if that matters.

**Comment by saghul** [comment]
Can you try release 24.2? It might not have reached f-droid yet, but it's on the Play Store.

**Comment by saghul** [comment]
I don't think so.

@jallamsetty1 do have an idea of what could cause that behavior?

**Comment by jallamsetty1** [comment]
@steepnought What codec settings are you using on your deployment for mobile endpoints?
