### ISSUE TITLE
Noise Suppression Enabled by default

### ISSUE THREAD

**Issue by crjo** [jitsi/jitsi-meet#14719]
We allways need to enable noise suppression.

Is it possible to enable this feature by default for all meetings and participants?

Or at least, once you have enabled it, it's enabled for the next meetings.

**Comment by saghul** [comment]
Noise suppression is always enabled. The dedicated setting adds some extra suppression.

Do you need that every time?

**Comment by crjo** [comment]
yes i would like this every time

**Comment by saghul** [comment]
@andrei-gavrilescu IIRC you took a look at this last, didn't you?

**Comment by andrei-gavrilescu** [comment]
Hello there. Yes it's possible.
First option is the settings toggle 
![Screenshot 2024-05-13 at 11 20 58](https://github.com/jitsi/jitsi-meet/assets/51706180/65a6fa9d-106d-4f81-97af-adc9633850d7)
This will enable noise suppression for all subsequent meetings for that browser instance.
If you're using an iframe integration, the ```setNoiseSuppressionEnabled``` command can be used as described here https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands/#setnoisesuppressionenabled.

**Comment by saghul** [comment]
Is the option persisted though?

**Comment by andrei-gavrilescu** [comment]
Yes it is.

**Comment by saghul** [comment]
@andrei-gavrilescu Thanks mate!

@crjo Can you please test that!

**Comment by DamianoP** [comment]
can this function be activated by default by modifying config.js or interface_config.js ?

**Comment by saghul** [comment]
No. Note it's extra noise suppression, the default mode already has the standard NS enabled.

**Comment by rbustos** [comment]
> No. Note it's extra noise suppression, the default mode already has the standard NS enabled.

I have same question same as @DamianoP..  is there a way to activate this "extra noise suppression" option by default when a new room is created for all? 

This option (even beta) is really good.

**Comment by rbustos** [comment]
> If you enable it once it will be remembered, for any room.

Yes, for that specific browser. It would be ideal to have it enable by default regarding what browser are you using. It could be very helpful for guest and will avoid to depend on local browser cache.

I'be been testing standard NS and this extra option.. and last one is an important improvement. Should be enable by default from my prospective. Will be fantastic.
