### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'source')

### ISSUE THREAD

**Issue by valyaevadaria** [jitsi/jitsi-meet#14716]
### Description:

When enabling end-to-end-encryption on a call, there's an error message in the browsers console and end-to-end-encryption doesn't work.
  
### Steps to reproduce:

1. Join a call
2. Open the browsers console
3. Enable the E2EE from the security options
4. There is an error in the console, see below
5. Try to start recording the call

### Expected behavior:

- No errors in the console
- Recording the call doesn't start

### Actual behavior:

- There's an error message in the console:
```
    content.bundle.js:3 Uncaught TypeError: Cannot read properties of null (reading 'source')
    at va (content.bundle.js:3:2062)
```
- Recording the call is starting

### Server information:

- Jitsi Meet version: https://meet.jit.si/ as of 2024-05-06 01:18 UTC

### Client information:

- Browser / app version: Chrome 124.0.6367.119 
- Operating System: macOS Monterey 12.6

**Comment by saghul** [comment]
Hum, I am not able to reproduce the problem, but I do see another, and video goes only one way as a result:

```
UnhandledPromiseRejection: InvalidModificationError: Failed to execute 'setParameters' on 'RTCRtpSender': Attempted to set RtpParameters scalabilityMode to an unsupported value for the current codecs. StackTrace:  Error: Failed to execute 'setParameters' on 'RTCRtpSender': Attempted to set RtpParameters scalabilityMode to an unsupported value for the current codecs.
```

@jallamsetty1 Can you PTAL? Just enable E2EE and check the browser JS console for these logs.

**Comment by jallamsetty1** [comment]
Yep I was looking into it yesterday. Damian and I reproduced the same issue as you. The error is a red herring, it didn't have any impact on the send video. On the receiver side though when the video is not being rendered, it is being decoded but just not rendered as the browser doesn't fire the canplaythrough event. Will continue debugging it today.

**Comment by jallamsetty1** [comment]
Hi @valyaevadaria, we identified the issue that is causing this behavior on meet.jit.si. We will fix be fixing it in the next release.
