### ISSUE TITLE
[RNSDK] Duplicates of `@react-native/metro-config` package in `dependencies` and `devDependencies`

### ISSUE THREAD

**Issue by danilvalov** [jitsi/jitsi-meet#14717]
### Description:

When I run `prepare_sdk.js` script after installation/updating I see duplicates of `@react-native/metro-config` dependency in my `package.json`:
1. Original React Native dependency in `devDependencies` section: [github/react-native](https://github.com/facebook/react-native/blob/v0.72.14/packages/react-native/template/package.json#L21)
2. Jitsi dependency in `dependencies` section: [github/jitsi-meet](https://github.com/jitsi/jitsi-meet/blob/master/package.json#L39)

And there is a conflict of versions because:
- my `react-native: "0.72.14"` (latest stable version) uses `@react-native/metro-config: "0.72.12"`
- Jitsi RN SDK uses `@react-native/metro-config: "0.72.9"`.

Jitsi doesn't update a version of `@react-native/metro-config`, just adds a new dependency.

P.S. I don't sure it is correct to overwrite a React Native dependency

**Comment by saghul** [comment]
Thanks for the report!

**Comment by Calinteodor** [comment]
@danilvalov Thanks again for the report! Fix will be available in the next React Native SDK release.
