### ISSUE TITLE
iOS microphone permanently in use when stop screen share

### ISSUE THREAD

**Issue by luca-rmg** [jitsi/jitsi-meet#14726]
On iOS the microphone remain active when stop the screen share (the orange dot remain visible on the status bar).
This behavior seem to happen only when the feature flag "call-integration.enabled" is set to "false".

### Steps to reproduce:

1. Start a new conference with "call-integration.enabled" set to "false"
2. Manually start screen share
3. Join with a second device <-- IMPORTANT
4. Stop the screen share from the jitsi UI of the first device

### Expected behavior:

The orange dot should disappear

### Actual behavior:

The orange dot remain visible

### Server information:

https://meet.jit.si/

### Client information:

- Browser / app version: Sample app at tag stable/jitsi-meet_9364
- Operating System: iOS 17.3

### Additional information:
This is the code I'm using:

```
    JitsiMeetView *view = (JitsiMeetView *) self.view;
    view.delegate = self;
  
    JitsiMeetConferenceOptions *options = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {      
      [builder setVideoMuted:true];
      [builder setAudioMuted:true];
      [builder setFeatureFlag:@"call-integration.enabled" withBoolean:false];
    }];

    [view join: options];
```

**Comment by saghul** [comment]
Stopping the screen share shouldn't stop the microphone at all. Do you mean this happens after your hangup?

> 1. with "call-integration.enabled" set to "false"

Any reason why you are doing this? It's not very well supported because we never disable it, since it makes staying alive in the background for a long time not possible.

Does the mic mute button properly mute / unmute?

**Comment by luca-rmg** [comment]
> Stopping the screen share shouldn't stop the microphone at all. Do you mean this happens after your hangup?
I mean this happen after a screen share stop, also if the mic is muted.

> Any reason why you are doing this?
We need to disable the call-integration because it is a requirement of our app UX.

>  It's not very well supported because we never disable it, since it makes staying alive in the background for a long time not possible.
So call-integration should be enabled to prevent background problems?

> Does the mic mute button properly mute / unmute?
Yes, before a screen share start. No, after a screen share stop.

**Comment by saghul** [comment]
> So call-integration should be enabled to prevent background problems?

Correct.

> I mean this happen after a screen share stop, also if the mic is muted.

So, let's recat:

- Meeting between 2 participants
- You're audio muted
- Start a screen-share
- Stop it
- Mic is now unmuted or is it just the orange dot?
- Can remote participant hear you?

**Comment by saghul** [comment]
I cannot reproduce this with the Jitsi Meet app, but that one has callintegration enablled. Do you reproduce this if that is enabled too?

**Comment by luca-rmg** [comment]
No, this happen only with "call-integration.enabled" set to false

**Comment by saghul** [comment]
Sorry, I'm afraid I cannot look into it anytime soon, that is not something we support well.
