### ISSUE TITLE
Can't user customToolbarButtons via setConfigOverride (Android)

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#14725]
According to documentation 9.2.2 SDK build supports `customToolbarButtons`.

It works for iOS, but in Android code snipped fails.

```
JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
    .setServerURL(new URL("https://meet.jit.si"))
    .setRoom("test123")
    .setAudioMuted(false)
    .setVideoMuted(false)
    .setAudioOnly(false)
    .setWelcomePageEnabled(false)
    .setConfigOverride("requireDisplayName", true)
    .setConfigOverride("customToolbarButtons", [
        {
            icon: "https://w7.pngwing.com/pngs/987/537/png-transparent-download-downloading-save-basic-user-interface-icon-thumbnail.png",
            id: "btn1",
            text: "Button one"
        }, {
            icon: "https://w7.pngwing.com/pngs/987/537/png-transparent-download-downloading-save-basic-user-interface-icon-thumbnail.png",
            id: "btn2",
            text: "Button two"
        }])
    .build();
```

It seems that we have no method to set List of dictionaries.

<img width="924" alt="Screenshot 2024-05-08 at 06 51 46" src="https://github.com/jitsi/jitsi-meet/assets/1611869/b5802c6a-9e0b-4782-bbe2-8bab4847a4c6">

P.S.
Also for both platforms it is strange to see default custom button "invite" at the menu top.
In iOS it is possible to hide it by settings empty array but there is a visual remnant of it at the empty top.

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by Calinteodor** [comment]
Fix will be available in the next release.
