### ISSUE TITLE
Recording spliting issue while continues recording for 1-1.30 hr with 2 users.

### ISSUE THREAD

**Issue by PratikNanavare20** [jitsi/jitsi-meet#14729]
### Steps to reproduce:

1. Start Meeting with 2 users
2. Click on 'Start recording for 1-1.30 hr recording
3. and so on... and do all the events inbetween meeting like like do multiple times share screen and share video hand raise and all

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Not sure what the question is here. If you start / stop a recording multiple times then you'll get multiple files.

**Comment by PratikNanavare20** [comment]
> Not sure what the question is here. If you start / stop a recording multiple times then you'll get multiple files.


If I start recording in 1 meeting and use multiple events like screen sharing and share video etc for long time then it is automatically spitting the recording in multiple parts.

**Comment by saghul** [comment]
I guess you are using local recordings. That is a limitation of the recording system since it needs to store the content in RAM and we have some size limits.

**Comment by PratikNanavare20** [comment]
> I guess you are using local recordings. That is a limitation of the recording system since it needs to store the content in RAM and we have some size limits.

We have store recording in external storage which is connected with our VM and once recording completed we moved that recording to azure blob storage.

**Comment by saghul** [comment]
So you are using Jibri then. That shouldn't happen I think. Please share Jibri logs.
