### ISSUE TITLE
Microphone is not working on android 8

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#14727]
Our app using :

- Jitsi Meet version 5.1.0
- Jdk 11
- android sdk 26

we have installed the app into car(android8 OS), we are able to make the calls but the problem is that mic is not working. It’s seems jitsi set VOIP as the audio mode. How can I set VOICE_CALL as audio source.

**Comment by saghul** [comment]
That SDK version is too old and unsupported, sorry. You need to update to a more recent version: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md
