### ISSUE TITLE
[react-native-sdk] resume() can only be called in the DISCONNECTED state (up)

### ISSUE THREAD

**Issue by Anfieldd** [jitsi/jitsi-meet#14728]
I'm sorry for the duplicate, but the previous topic was closed.
Everything about the problem has already been described here https://github.com/jitsi/jitsi-meet/issues/14399
The problem still reproduces with the latest SDK version, maybe do you have any ideas on how to fix this?

**Comment by saghul** [comment]
Fix: https://github.com/jitsi/lib-jitsi-meet/pull/2523
