### ISSUE TITLE
Meeting with more than two people will automatically disconnect

### ISSUE THREAD

**Issue by TwoDogs2** [jitsi/jitsi-meet#14738]
Hello，I encountered a problem while using jitsimeet, which is that the meeting will end when there are more than two people, and everyone will exit the meeting. I checked the log information and did not see any related errors. Please help me take a look. Thank you very much！
jicofo.log
`Jicofo 2024-05-13 16:01:45.100 INFO: [68] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.<init>#81: Using org.jitsi.jicofo.bridge.SingleMeshTopologyStrategy
Jicofo 2024-05-13 16:01:45.100 INFO: [68] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.inviteChatMember#815: Creating participant 2be970a8 with features=[XMPP_CAPS, JSON_SOURCES, RECEIVE_MULTIPLE_STREAMS, REMB, SOURCE_NAMES, SSRC_REWRITING_V1, VISITORS_V1, RTX, JINGLE, DTLS, JINGLE_RTP, AUDIO, VIDEO, SCTP, JINGLE_ICE, RAYO]
Jicofo 2024-05-13 16:01:45.100 INFO: [69] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.allocate#278: Allocating for 67746ded
Jicofo 2024-05-13 16:01:45.100 WARNING: [69] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-05-13 16:01:45.100 SEVERE: [69] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19 participant=67746ded] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
Jicofo 2024-05-13 16:01:45.100 INFO: [70] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.allocate#278: Allocating for 2be970a8
Jicofo 2024-05-13 16:01:45.101 WARNING: [70] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-05-13 16:01:45.101 SEVERE: [70] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19 participant=2be970a8] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
Jicofo 2024-05-13 16:01:45.335 INFO: [64] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.onMemberLeft#957: Member left:2be970a8
Jicofo 2024-05-13 16:01:45.335 INFO: [64] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.terminateParticipant#1036: Terminating 2be970a8, reason: gone, send session-terminate: false
Jicofo 2024-05-13 16:01:45.335 INFO: [64] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.terminateParticipant#1050: Removed participant 2be970a8 removed=true
Jicofo 2024-05-13 16:01:45.335 WARNING: [64] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.removeParticipant#126: Can not remove 2be970a8, no participantInfo
Jicofo 2024-05-13 16:01:45.335 INFO: [64] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.rescheduleSingleParticipantTimeout#2028: Scheduled single person timeout.
Jicofo 2024-05-13 16:01:45.336 INFO: [69] AutoOwnerRoleManager.electNewOwner$lambda$3#101: Electing new owner: ChatMember[id=67746ded role=PARTICIPANT]
Jicofo 2024-05-13 16:01:45.402 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.onMemberLeft#957: Member left:67746ded
Jicofo 2024-05-13 16:01:45.402 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.terminateParticipant#1036: Terminating 67746ded, reason: gone, send session-terminate: false
Jicofo 2024-05-13 16:01:45.402 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.terminateParticipant#1050: Removed participant 67746ded removed=true
Jicofo 2024-05-13 16:01:45.402 WARNING: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.removeParticipant#126: Can not remove 67746ded, no participantInfo
Jicofo 2024-05-13 16:01:45.403 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.expire#110: Expiring.
Jicofo 2024-05-13 16:01:45.403 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.maybeStop#1004: Last member left, stopping.
Jicofo 2024-05-13 16:01:45.403 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] ColibriV2SessionManager.expire#110: Expiring.
Jicofo 2024-05-13 16:01:45.403 INFO: [59] [room=test@conference.meeting.soc.rd meeting_id=a5d44be1-5430-4bb8-8a25-0d74a2336a19] JitsiMeetConferenceImpl.stop#476: Stopped.`
jvb.log
`JVB 2024-05-13 15:43:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000062S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:44:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000063S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:45:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.00005S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:46:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000062S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:47:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000046S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:48:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000043S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:49:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000052S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:50:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000031S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:51:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000032S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:52:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000032S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:53:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000049S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:54:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000045S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:55:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000043S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:56:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000033S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:57:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000073S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:58:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000055S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 15:59:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000032S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 16:00:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000043S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 16:01:11.664 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000031S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 16:02:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000031S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 16:03:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000088S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)
JVB 2024-05-13 16:04:11.663 SEVERE: [19] HealthChecker.run#181: Health check failed in PT0.000066S: Result(success=false, hardFailure=true, responseCode=null, sticky=false, message=No valid IP addresses available for harvesting.)`
![jitsi](https://github.com/jitsi/jitsi-meet/assets/121689365/38a32c5b-daf7-4631-af7c-3bb831f0ffcc)

**Comment by saghul** [comment]
> Can not invite participant, no bridge available.

You have no bridges available. There is likely a configuration problem.

Please direct your question to our community forum.
