### ISSUE TITLE
How to integrate StarGate Authorization in Jitsi instead of OKTA?.

### ISSUE THREAD

**Issue by rajavelrajpcr** [jitsi/jitsi-meet#14731]
Need to integrate StarGate Authorization in Jitsi instead of OKTA. Do we have any existing solution.

**Comment by damencho** [comment]
Not sure where you see okta. 
You should configure your deployment to use jwt tokens and implement a page which logins your users via any authorization you want and generate a token to pass it to the jitsi-meet app. 
https://github.com/jitsi/jitsi-meet/blob/383b53475351a7ab0bf4f2e43ff70d76f90c26f7/config.js#L1506

**Comment by damencho** [comment]
Please, when you have questions or problems in the future use the community forum before opening new issues, thank you.
