### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException

### ISSUE THREAD

**Issue by ekirifaldi** [jitsi/jitsi-meet#14734]
For iOS Swift, I already success to join the call, 
But if I move to iOS Hompage and reopen the app, It will be force close (terminated)

My code:
<img width="850" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/17934578/ec7bd669-9454-4ebb-a63c-62119653d316">

The error:
<img width="912" alt="Screenshot 2024-05-12 at 14 40 53" src="https://github.com/jitsi/jitsi-meet/assets/17934578/d7cdfe09-7598-4c0d-9fbd-d7e7b34434da">

Thank you

**Comment by saghul** [comment]
Are you using SwiftUI?

**Comment by ekirifaldi** [comment]
No, I'm using UIKit

**Comment by ekirifaldi** [comment]
This is the video. I also tried to create a new project, but the result is the same. 
strangely, there is no force close when building the sample project from Jitsi.

Already, Always Embed Swift Standard Libraries is YES, permission for camera and microphone are given, selected the "audio" and "voip" background modes.

https://github.com/jitsi/jitsi-meet/assets/17934578/3a17a52c-95a2-4189-9a31-919016e54a89

**Comment by saghul** [comment]
How does your main app delegate look like?

**Comment by saghul** [comment]
It needs to look something like this: https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/ios/swift/JitsiSDKTest/src/AppDelegate.swift
