### ISSUE TITLE
Voice echo problem with audio call in IOS

### ISSUE THREAD

**Issue by nikul-nyu** [jitsi/jitsi-meet#14733]
When we call using IOS device , it seems like double voice or echo problem.

**Comment by saghul** [comment]
What app or SDK version are you using? This was fixed in the last release.

**Comment by AnithaFrontm** [comment]
Hi @saghul  Can you tell us in new sdk version where did you changed the code for this echo issue for ios.. so we can check in our latest code too

**Comment by nikul-nyu** [comment]
@saghul So we should upgrade version of Jitsi sdk or just version upgrade of react-native-webrtc will work?

**Comment by saghul** [comment]
I'd recommend you update the SDK, since it contains that and more fixes.

**Comment by AnithaFrontm** [comment]
i am using latest version of jitsi react native sdk
Following m using : "@jitsi/react-native-sdk": "^2.2.1",

Still from receiver side of call we are able to listen echo..

Please help on this asap

**Comment by saghul** [comment]
Echo won't completely go away.

We fixed duplicated audio.

If you want to really avoid echo using a headset is recommended.

**Comment by AnithaFrontm** [comment]
"We fixed duplicated audio." this is fixed in "@jitsi/react-native-sdk": "^2.2.1" or it will come in next release

**Comment by saghul** [comment]
That is fixed in 2.2.1 indeed.

**Comment by AnithaFrontm** [comment]
> That is fixed in 2.2.1 indeed.

Oh but still we are getting echo now means there is no solution for this now..

**Comment by AnithaFrontm** [comment]
In future if any fixes happend for echo please let us know

**Comment by saghul** [comment]
Check you dependencies to make sure you are using react-native-webrtc 118.0.6 or higher.

**Comment by AnithaFrontm** [comment]
> Check you dependencies to make sure you are using react-native-webrtc 118.0.6 or higher.

Yeah we are using latest dependencies as "react-native-webrtc": "118.0.6"

**Comment by saghul** [comment]
Then the audio duplication bug should not affect you. Cancelling all echo is very hard. We currently use the hardware echo canceller in the device, but even that is not perfect.
