### ISSUE TITLE
User tiles turn black after a user with share screen leaves the meet

### ISSUE THREAD

**Issue by amioan97** [jitsi/jitsi-meet#14740]
### Description:

After a user with screen sharing enabled leaves the meeting or refreshes the page, some of the user tiles will disappear for other participants. However, the tiles will reappear and return to normal once the user rejoins the meeting.

### Steps to reproduce:

1. User A, B, C and D join a meeting
2. All the users enable the "toggle tile view" option
3. User A starts screen sharing
4. User A leaves the meeting without stopping the screen sharing

### Expected behavior:

Each user will see 3 tiles, one for each user.

### Actual behavior:

Some of the user tiles are replaced by black squares.

### Server information:

- Jitsi Meet version: 2.0.8922, jitsi/web:web-1.0.7895-1

### Client information:

- Browser / app version: Google Chrome Version 124.0.6367.60 (Official Build) (64-bit)
- Operating System: Linux Mint 21 Cinnamon 5.4.12, Windows 10

### Additional information:

You can see a screen shot here: 
![jitsi_problem_tile](https://github.com/jitsi/jitsi-meet/assets/169665418/ba317daa-5150-437e-9215-f3faf0b385f3)

**Comment by amioan97** [comment]
No errors, that's why I didn't added the console logs.

**Comment by damencho** [comment]
Do you reproduce on meet.jit.si?

**Comment by saghul** [comment]
THat release is over 6 months old: https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_8922 I'd suggest you update and test again.

**Comment by amioan97** [comment]
OK, thxnk you.
I'll try it and come back with an update.

**Comment by ArpitShukla3** [comment]
> OK, thank you. I'll try it and come back with an update.

have you checked it

**Comment by amioan97** [comment]
Hello,

Not yet. We'll try to make an update next week.

**Comment by amioan** [comment]
Hello,

Sorry for the late update. The problem was fixed after updating the jitsi version.
Thank you!
