### ISSUE TITLE
Feature Request: Enhancements to Polling Functionality in Jitsi

### ISSUE THREAD

**Issue by lea-aglz** [jitsi/jitsi-meet#14744]
Hello, 

I would like to submit a feature request for enhancements to the polling functionality in Jitsi:

1. The possibility to vote anonymously
2. The possibility to have predefined polls prior to the meeting and open votes when needed – it could a functionality to import a predefined list of votes
3. The possibility to limit the votes to single choice votes
4. Export/Save voting results
5. The possibility to open and close votes
6. The possibility to limit the launch of the votes to the moderator only

Thanks 
Best regards, 

Léa Angelloz

**Comment by saghul** [comment]
Hi @lea-aglz ! Good news, we are currently working on some of those already! @rpurdel can you confirm which of them are being worked on right now?

**Comment by netFLOw95** [comment]
Any news on that? I would particularly appreciate anonymous voting.

**Comment by saghul** [comment]
We are not currently working on that one IIRC.

**Comment by lea-aglz** [comment]
Hi, 
Do you have any updates on this feature request?

Thanks
Best regards,

Léa Angelloz
