### ISSUE TITLE
Android microphone doesn`t work

### ISSUE THREAD

**Issue by vinay11sight** [jitsi/jitsi-meet#14750]
I installed the Jitsi sample app from the Play Store in our car Android player, which has Android 10.

(https://play.google.com/store/apps/details?id=org.jitsi.meet&hl=en&gl=US)

Calling is going well, but there is a problem with the mic. The mic does not work.

I also built the jitsi SDK (https://github.com/jitsi/jitsi-meet/releases/tag/android-sdk-9.0.0) and created a demo app, but I am facing the same problem.

I want to change the recording mode to VOICE_CALL but unable to locate the MediaRecorder in the source code.

If you can check, please. thank you

**Comment by saghul** [comment]
I don't think our SDK works in a car view because it expects a different type of activity.

**Comment by vinay11sight** [comment]
It functions effectively. Calls are proceeding well; the microphone isn't working, and I believe MediaRecorder mode is the source of the problem. If you could assist, I would like to switch the mode to VOICE_CALL.

**Comment by saghul** [comment]
When WebRTC creates a `android.media.AudioRecord`, it uses `AudioSource.VOICE_COMMUNICATION` as the source.

**Comment by vinay11sight** [comment]
I tried to change Audio source but it takes VOICE_COMMUNICATION.
Could you please help? Here are the logs.
I note one thing in the logs : Audio source is changed by other app

05-20 16:32:10.457  1494  1494 I AudioManagerImp: Audio source package changed: Package = [tr.com](http://tr.com/).togg.radiomanager
05-20 16:32:10.457  1918  1918 D ARAFA   : onAudioFocusRequest usage: USAGE_MEDIA response: 1

[20May.log](https://github.com/jitsi/jitsi-meet/files/15379847/20May.log)

**Comment by vinay11sight** [comment]
I tried to change Audio source but it takes VOICE_COMMUNICATION.
Could you please help? Here are the logs.
I note one thing in the logs : Audio source is changed by other app

05-20 16:32:10.457  1494  1494 I AudioManagerImp: Audio source package changed: Package = en.com.taudio.radiomanager
05-20 16:32:10.457  1918  1918 D ARAFA   : onAudioFocusRequest usage: USAGE_MEDIA response: 1
05-20 16:32:10.457  1918  1918 D ARAFA   :         Activating the usageUSAGE_MEDIA
05-20 16:32:10.457  1918  1918 D ARAFA   : >>>>>>>> Sending Audio of Interest as >>>>>>>>USAGE_MEDIA
05-20 16:32:10.458  6681  7810 D AudioManagerHMI: onAudioFocusPackageNameChanged: en.com.taudio.radiomanager
05-20 16:32:10.458  6880  6898 D AudioManagerHMI: onAudioFocusPackageNameChanged: en.com.taudio.radiomanager


[20May.log](https://github.com/jitsi/jitsi-meet/files/15379958/20May.log)


thank you so much for your support.

**Comment by saghul** [comment]
When are you changing it?
