### ISSUE TITLE
The heading in a component on the landing page is overflowing.

### ISSUE THREAD

**Issue by Success1308** [jitsi/jitsi-meet#14753]
Description:

The heading in a component on the landing page is overflowing.

Steps to reproduce:

    Open the landing page.
    Observe the heading in the specified component.

![image](https://github.com/jitsi/jitsi-meet/assets/167788445/574ceca3-dfee-42b6-a4f1-9c8a00e434e9)

https://github.com/jitsi/jitsi-meet/assets/167788445/1c3c8035-81ff-49e3-8586-4c14dacd2e65

Expected behavior:

The heading should fit properly within its container without overflowing.

Actual behavior:

The heading overflows outside of its container, affecting the layout and readability of the date section.
Server information:

    Jitsi Meet version: unknown
    Operating System: Windows 11

Client information:

    Browser / app version: Mozilla firefox 
    Operating System: Windows 11

**Comment by saghul** [comment]
Thanks for the report!

**Comment by Success1308** [comment]
Can I work on it ?

**Comment by saghul** [comment]
No, sorry, that website is not editable for the public.

**Comment by saghul** [comment]
Fixed!
