### ISSUE TITLE
How to switch between the front and rear cameras on a mobile device:

### ISSUE THREAD

**Issue by yumu7777777** [jitsi/jitsi-meet#14767]
### What problem are you trying to solve?

How to switch between the front and rear cameras on a mobile device:
![image](https://github.com/jitsi/jitsi-meet/assets/104643678/3cd25964-4e7f-496d-97f0-756de82e0e26)
I can switch from the front camera to the rear camera normally, but when I switch back to the front camera, it gives an error. How can I fix this?
![d781925788dd336c48251c16ddb9f660](https://github.com/jitsi/jitsi-meet/assets/104643678/b4ba1a93-4c45-4cee-8f49-8780418346da)

**Comment by saghul** [comment]
This is not a feature request. Please file the bug correctly as a bug and fill in all the requested data.
