### ISSUE TITLE
Polish language detection does not work properly on Google Chrome.

### ISSUE THREAD

**Issue by Maniues** [jitsi/jitsi-meet#14764]
### What happened?

Jitsi Meet does not detect Polish language encoded in `navigator.language` as `pl-PL` and sets English language.

On Firefox or MS Edge, Polish is encoded as `pl` and Jitsi Meet's language detection properly works with these browsers.

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome 124.0.6367.208 / 125.0.6422.61 (tested on both)

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

Tested on meet.jit.si and on internal deployment.

**Comment by damencho** [comment]
Have you tried in incognito?

**Comment by saghul** [comment]
@damencho IIRC there was a similar report for Spanish, being `es-ES`.

**Comment by damencho** [comment]
Yeah. And a PR will look at it when I find some time

**Comment by saghul** [comment]
Excellent, thanks!

**Comment by saghul** [comment]
Does it happen in normal mode? What value do you get for the language in that case?

**Comment by damencho** [comment]
@saghul I took a look. So it is issue #8261 and PR https://github.com/jitsi/jitsi-meet/pull/8690.
In the case reported here when only 'pl-PL' is available it will normalize it to 'plPL', I guess we can change it to make it 'pl' and that will fix the issue, I would guess.
