### ISSUE TITLE
dyld[324]: Symbol not found: _JSGlobalContextSetInspectable

### ISSUE THREAD

**Issue by alirezarabiei7239** [jitsi/jitsi-meet#14761]
### What happened?

in ios 15 after building sdk for ios in copy the framework to my app I got this error : 
dyld[324]: Symbol not found: _JSGlobalContextSetInspectable
  Referenced from: /private/var/containers/Bundle/Application/A30EFC43-5D01-46A3-BE82-7A0B7F059677/X.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK
  Expected in: /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

2.0.9457

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Are you making anu changes to the SDK yourself?

**Comment by alirezarabiei7239** [comment]
@saghul yes some ui changes

**Comment by saghul** [comment]
It's really odd because that symbol comes from the system JavaScriptCore framework. We don't call any private APIs or anything.

I don't know how to help you, sorry.

**Comment by luca-rmg** [comment]
Hi, I think the problem was fixed in react-native:
https://github.com/facebook/react-native/releases/tag/v0.75.0-rc.0
please, integrate the fix when a react-native stable version will be released.

In the meantime we can build the Jitsi SDK with Xcode 15.0 that is still working and don't cause the problem.

**Comment by saghul** [comment]
What Xcode version are you using?

**Comment by luca-rmg** [comment]
> What Xcode version are you using?

I was using Xcode 15.4 that cause the problem. Then I tried with Xcode 15.0 and don't cause the problem.

**Comment by saghul** [comment]
Since the problem is fixed in RN, you can use `patch-package` to apply the fix locally.

**Comment by mssvijaykumar** [comment]
I was also facing the same issue, I resolved this issue by changing this below code.

change 
#ifdef _JSC_HAS_INSPECTABLE
  if (__builtin_available(macOS 13.3, iOS 16.4, tvOS 16.4, *)) {
    JSGlobalContextSetInspectable(ctx_, true);
  }

to

#if (__OSX_AVAILABLE_STARTING(MAC_NA, IPHONE_16_4))
  if (__builtin_available(macOS 13.3, iOS 16.4, tvOS 16.4, *)) {
    JSGlobalContextSetInspectable(ctx_, true);
  }
