### ISSUE TITLE
为什么不能单独出一下Android ｊａｒ？？？？？而且ｗｉｎｏｄｗ不能编译

### ISSUE THREAD

**Issue by Cuiernao** [jitsi/jitsi-meet#14762]
### What happened?

为什么不能单独出一下Android ｊａｒ？？？？？而且ｗｉｎｏｄｗ不能编译，各种问题，太差劲了

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

ｎｅｗ　ｖｅｒｓｉｏｎ

### Relevant log output

```shell
为什么不能单独出一下Android ｊａｒ？？？？？而且ｗｉｎｏｄｗ不能编译，各种问题，太差劲了
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

为什么不能单独出一下Android ｊａｒ？？？？？而且ｗｉｎｏｄｗ不能编译，各种问题，太差劲了

**Comment by Cuiernao** [comment]
二次开发太不友好了

**Comment by saghul** [comment]
Please post in English.
