### ISSUE TITLE
How to switch between the front and rear cameras on a mobile device:

### ISSUE THREAD

**Issue by yumu7777777** [jitsi/jitsi-meet#14768]
### What happened?

How to switch between the front and rear cameras on a mobile device:
![image](https://github.com/jitsi/jitsi-meet/assets/104643678/5ad86201-5eec-431d-ab9c-d273369580ec)
I can switch from the front camera to the rear camera normally, but when I switch back to the front camera, it gives an error. How can I fix this?
![image](https://github.com/jitsi/jitsi-meet/assets/104643678/0ca6acb7-d7d0-402f-8d6b-00eb627ef429)

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

安卓14

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
You need to make sure the existing camera track is disposed before creating the new one.

**Comment by yumu7777777** [comment]
Could you please specify which method to execute? I couldn't find the corresponding action. Thank you very much.

**Comment by yumu7777777** [comment]
I have tried this method, and it works in some browsers. However, after switching, some browsers cannot get the video, such as the WeChat browser.

**Comment by saghul** [comment]
Remember to `await` it, since it returns a promise.
