### ISSUE TITLE
Add input sensitivity / microphone threshold feature

### ISSUE THREAD

**Issue by crabdancing** [jitsi/jitsi-meet#14779]
### What problem are you trying to solve?

In Discord, and a number of other VOIP apps, there is a feature that allows the user to cap minimum volume at an arbitrary threshold. If dB are beneath this threshold, the mic switches off. This means that you can easily tune it so that background noise such as fans, typing, and breathing are ignored by your microphone.

### What solution would you like to see?

![image](https://github.com/jitsi/jitsi-meet/assets/28266167/56caf06e-207d-4f2e-aba3-94035b9b2635)

To make Jitsi Meet more useful for larger business meetings, and to stay competitive with apps like Discord, it seems like a good idea to implement this feature.

Note that this feature request is a replacement for #14405, which met its tragic end at the hands of a stale bot.

**Comment by crabdancing** [comment]
stale bot, I need you to chill for real. I've been keeping this issue alive for years.

**Comment by crabdancing** [comment]
@github-actions, real talk. I need you to stop forcing me to spam Github issues to keep the issue open. This helps no one. Now half of what someone sees is me talking to a bot that's only capable of saying two things. :/

**Comment by NicoleKai** [comment]
![images](https://github.com/user-attachments/assets/37c3c373-93fd-4111-8265-4a26dfcfa2a4)

**Comment by crabdancing** [comment]
Oof, really?  :/
