### ISSUE TITLE
when joining 3 more people,they are evicted 

### ISSUE THREAD

**Issue by kenkenjp1** [jitsi/jitsi-meet#14771]
### What happened?

Hi,I'm investigating if similar issues have been reported on Jitsi's community forums or GitHub issue tracker, specifically concerning a situation where existing meeting participants 1 and 2 are being kicked out when a third person joins. Are there any documented solutions or workarounds available?

I'll provide the actual logs and the verification I've conducted below:
JVB 2024-05-20 00:01:50.841 情報: [305598] [confId=d5584aae382b382 epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp gid=28526 conf_name=24186711716130719@xxxxxxxxxxxxxxxx ufrag=eeoit1hu8lv4jp] Agent.gatherCandidates#622: Gathering candidates for component stream-19b0a0ee.RTP.
JVB 2024-05-20 00:01:50.842 警告: [305598] [confId=d5584aae382b382 gid=28526 type=video conf_name=24186711716130719@xxxxxxxxxxxxxxxx] ChannelShim.lambda$setSourceGroups$2#289: Ignoring source group with <2 sources: <ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>
JVB 2024-05-20 00:01:50.842 警告: [305598] MediaSourceFactory.getSourceSsrcs#400: Unprocessed source groups: Optional[<ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>]
JVB 2024-05-20 00:01:50.842 情報: [305598] [confId=d5584aae382b382 epId=19b0a0ee gid=28526 conf_name=24186711716130719@xxxxxxxxxxxxxxxx] Endpoint.setTransportInfo#684: Ignoring empty DtlsFingerprint extension: <transport xmlns='urn:xmpp:jingle:transports:ice-udp:1'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' required='false'/></transport>
JVB 2024-05-20 00:01:51.283 情報: [305598] [confId=d5584aae382b382 epId=19b0a0ee gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx] DtlsTransport.setSetupAttribute#120: The remote side is acting as DTLS client, we'll act as server
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx] IceTransport.startConnectivityEstablishment#188: Starting the Agent without remote candidates.
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx ufrag=eeoit1hu8lv4jp epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp] Agent.startConnectivityEstablishment#713: Start ICE connectivity establishment.
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx ufrag=eeoit1hu8lv4jp epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp] Agent.initCheckLists#949: Init checklist for stream stream-19b0a0ee
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx ufrag=eeoit1hu8lv4jp epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp] Agent.setState#923: ICE state changed from Waiting to Running.
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx] IceTransport.iceStateChanged#327: ICE state changed old=Waiting new=Running
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719@xxxxxxxxxxxxxxxx ufrag=eeoit1hu8lv4jp epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp] Agent.startConnectivityEstablishment#735: Trigger checks for pairs that were received before running state
JVB 2024-05-20 00:01:51.284 情報: [305598] [confId=d5584aae382b382 gid=28526 stats_id=Giovanny-Adi conf_name=24186711716130719xxxxxxxxxxxxxxx ufrag=eeoit1hu8lv4jp epId=19b0a0ee local_ufrag=eeoit1hu8lv4jp] Agent.triggerCheck#1714: Add peer CandidatePair with new reflexive address to checkList: CandidatePair (State=Frozen Priority=7962116751041232895):
	LocalCandidate=candidate:2 1 udp 2130706431 10.255.251.164 10000 typ host
	RemoteCandidate=candidate:10000 1 udp 1853824767 10.25.1.21 51001 typ prflx

here are my actions categorized into patterns:
Pattern 1:
If the host enters the web conference first, the connections of the two participants who were in the conference are terminated and become unusable when the third person connects.

Pattern 2:
If the host enters the web conference second, the connections of the two participants who were in the conference are terminated and become unusable when the third person connects.

Pattern 3:
If the host enters the web conference third, they can conduct the web conference. Other participants can join even after the fourth person.

Pattern 4:
If the host enters the web conference fourth, they can conduct the web conference. Other participants can join even after the fifth person.

I suspect there's an issue with the server hosting the Jitsi Videobridge. If you have any insights into potential solutions or causes, I'd appreciate your guidance.

p.s I apologize for my poor English as I am Japanese.

Thank you for your suports!

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

dont know

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
> * The problem is reproducible on meet.jit.si

Are you reproducing this on meet.jit.si? If yes, what does host mean? There is no such thing as a host of the meeting.

**Comment by damencho** [comment]
This sounds that on your deployment clients cannot send media to the jvb. Normally this is cause by firewall, missing port forwarding for port 10000 udp, or jvb not reporting its public address.

**Comment by damencho** [comment]
If you are reproducing it on meet.jit.si, upload the js console logs from the browser.

**Comment by kenkenjp1** [comment]
> This sounds that on your deployment clients cannot send media to the jvb. Normally this is cause by firewall, missing port forwarding for port 10000 udp, or jvb not reporting its public address.

This server have the firewall disabled...
I will try restarting the jitsi-videobridge service for now.
