### ISSUE TITLE
Recoding not downloaded after ending a session 

### ISSUE THREAD

**Issue by SRE-23** [jitsi/jitsi-meet#14789]
### What happened?

Session was ended but unable to find the recording for my session 

This is my moderated link 

https://moderated.jitsi.net/644de6868480451d8cf00bac5a841b6dcdf986ab28a84ab19980bf1a9a02d575 

Please help me to get the video recordings

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Microsoft Edge Version 125.0.2535.79 (Official build) (64-bit)

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

Kindly make my todays video available and update on career.next.training@gmail.com

**Comment by saghul** [comment]
The video should be available in your downloads folder.

**Comment by SRE-23** [comment]
No its not available

**Comment by saghul** [comment]
Did you start the recording? Did your browser crash?

**Comment by SRE-23** [comment]
I had started the recording after ending it wasn’t downloaded

**Comment by saghul** [comment]
How did you end the meeting? Did you close the browser / tab?

**Comment by SRE-23** [comment]
I had click on end meeting and left

**Comment by saghul** [comment]
There must have been a problem then, but since it all happens locally we cannot see the logs :-/ I did a quick test locally and I did get the file downloaded.

Sorry, but I'm afraid your recording is lost.

**Comment by SRE-23** [comment]
Oh 😯

I need to go through again with same process

Thanks
Tanveer
