### ISSUE TITLE
Video call crashes on OnePlus Devices with Android version 14 

### ISSUE THREAD

**Issue by nikul-nyu** [jitsi/jitsi-meet#14785]
### What happened?

Connect from an android device to An Oneplus android 14 device video call crashes on oneplus device after connecting 1 second

I have check these in around 8-9 devices including iphone 11, iphone 13, Oneplus nord, Oneplus 10R, samsung galaxy A53, Google pixel 7, etc.

Please share if you find anything , that would be great help. Thanks!!

Crash logs::

      Crashed: Thread: SIGABRT  0x0000000000000000
#00 pc 0x9ce10 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
#01 pc 0x9cde0 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
#02 pc 0x417f10 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#03 pc 0x418554 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#04 pc 0x4077a8 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#05 pc 0x4076b8 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#06 pc 0x4e1ce4 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#07 pc 0x8c0060 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#08 pc 0x5dcc24 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#09 pc 0x5de6fc libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#10 pc 0x5dd424 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#11 pc 0x427bbc libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#12 pc 0x427aa4 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085)
#13 pc 0x104fc4 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
#14 pc 0x9e764 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

React-native sdk - 2.2.1

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by nikul-nyu** [comment]
Yes

**Comment by thanviavinash** [comment]
> ### What happened?
> Connect from an android device to An Oneplus android 14 device video call crashes on oneplus device after connecting 1 second
> 
> I have check these in around 8-9 devices including iphone 11, iphone 13, Oneplus nord, Oneplus 10R, samsung galaxy A53, Google pixel 7, etc.
> 
> Please share if you find anything , that would be great help. Thanks!!
> 
> Crash logs::
> 
> ```
>   Crashed: Thread: SIGABRT  0x0000000000000000
> ```
> 
> #00 pc 0x9ce10 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6) #1 pc 0x9cde0 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6) #2 pc 0x417f10 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #3 pc 0x418554 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #4 pc 0x4077a8 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #5 pc 0x4076b8 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #6 pc 0x4e1ce4 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #7 pc 0x8c0060 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #8 pc 0x5dcc24 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #9 pc 0x5de6fc libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #10 pc 0x5dd424 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #11 pc 0x427bbc libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #12 pc 0x427aa4 libjingle_peerconnection_so.so (BuildId: 4bbf0f3487b96085) #13 pc 0x104fc4 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6) #14 pc 0x9e764 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
> 
> ### Platform
> * [ ]  Chrome (or Chromium based)
> * [ ]  Firefox
> * [ ]  Safari
> * [ ]  Other desktop browser
> * [ ]  Android browser
> * [ ]  iOS browser
> * [ ]  Electron app
> * [ ]  Android mobile app
> * [ ]  iOS mobile app
> * [ ]  Custom app using a mobile SDK
> 
> ### Browser / app / sdk version
> React-native sdk - 2.2.1
> 
> ### Relevant log output
> _No response_
> 
> ### Reproducibility
> * [ ]  The problem is reproducible on meet.jit.si
> 
> ### More details?
> _No response_

Also getting same issue, if anyone find anything then please share.
Thanks!!
