### ISSUE TITLE
Echo in meeting

### ISSUE THREAD

**Issue by janvlug** [jitsi/jitsi-meet#14787]
### What happened?

We had a Jitsi meeting on https://meetme.bit.nl (lib-jitsi-meet version:178f9bbf).

There were four participants. The system of one participant caused an echo. When this participant muted the echo was gone.

This participant uses:
Browser: Safari 17,5 on a MacBook Pro M1 (14", 2021), OS= Sonoma 14.5.
Using the microphone from a LG Ultrafine 27" display, sold by Apple.

### Browser / app / sdk version

All other participants hear the echo, except the participant from where the echo was coming.

**Comment by DhruvLamba** [comment]
Were two or more than two participants in the same room because it happens in google meet too.

**Comment by janvlug** [comment]
There were four participants.

**Comment by saghul** [comment]
There is nothing we can do here, I'm afraid. We use the browser provided echo canceller, which is alas not perfect.

In situations when participants are in the same room or when no headsets are being used it's possible to still have echo.
