### ISSUE TITLE
There was noise in the audio, and the video was not visible. 

### ISSUE THREAD

**Issue by piyushbzluck** [jitsi/jitsi-meet#14816]
### What happened?

When I joined a meeting using Chrome and another participant joined using Safari, we encountered issues: there was noise in the audio, and the video was not visible. 

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [X] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome version 125.0.6422.142 (Official Build) (x86_64)

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
What is the jitsi-meet version that is being used?

**Comment by piyushbzluck** [comment]
"@jitsi/excalidraw": "https://github.com/jitsi/excalidraw/releases/download/v0.0.19/jitsi-excalidraw-0.0.19.tgz"
"@jitsi/js-utils": "2.2.1",
"@jitsi/logger": "2.0.2",
"@jitsi/rnnoise-wasm": "0.1.0",
 "@jitsi/rtcstats": "9.5.1",
"lib-jitsi-meet": "https://github.com/jitsi/lib-jitsi-meet/releases/download/v1830.0.0+5a14bd43/lib-jitsi-meet.tgz",

**Comment by saghul** [comment]
Now that, how did you install Jitsi Meet on your server?

**Comment by piyushbzluck** [comment]
Please excuse me for the delayed response, and thank you for listening to my query.

I didn't perform any installation. I only checked out the repository and ran "npm install". After that, I executed "make dev", which successfully ran the project. However, when I tested it in Chrome and Safari, this issue appeared.

**Comment by saghul** [comment]
Make dev uses our alpha deployment,not meant for public use, but simple testing only.

You need to deploy the entire stack of you want to use your own Jitsi meet.

**Comment by piyushbzluck** [comment]
Okay. But I want to run it on my local system. How can I set up my own Jitsi Meet so that this problem is solved for my local system? Can you provide a website or guide for this?

**Comment by saghul** [comment]
You can start here: https://jitsi.github.io/handbook/docs/devops-guide/

**Comment by piyushbzluck** [comment]
> Make dev uses our alpha deployment,not meant for public use, but simple testing only.
> 
> You need to deploy the entire stack of you want to use your own Jitsi meet.

When I use Chrome to Chrome, everything works properly. However, when I use Safari to Safari or Chrome to Safari, I experience issues with voice and sound. Why is that?

**Comment by saghul** [comment]
We don't provide support for alpha.jitsi.net, sorry. Please see if you can reproduce the problem directly on meet.jit.si.

**Comment by piyushbzluck** [comment]
I have set up Jitsi Meet on a private network, but it is not connecting on Safari.
