### ISSUE TITLE
There was noise in the audio, and the video was not visible. 

### ISSUE THREAD

**Issue by piyushbzluck** [jitsi/jitsi-meet#14817]
### What happened?

When I joined a meeting using Chrome and another participant joined using Safari, we encountered issues: there was noise in the audio, and the video was not visible. 

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [X] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome version 125.0.6422.142 (Official Build) (x86_64),  Safari Version 14.1.1 (16611.2.7.1.4)

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Please do not open duplicate issues for the same problem.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
