### ISSUE TITLE
Setting 'call-integration.enabled' value to true makes impossible to play video when shared via youtube link

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [jitsi/jitsi-meet#14812]
Hi, 

I've installed Jitsi demo app from :- https://github.com/jitsi/jitsi-meet-sdk-samples

In the code :- 

`MainActivity File `

```
val defaultOptions = JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                // When using JaaS, set the obtained JWT here
                //.setToken("MyJWT")
                // Different features flags can be set
                //.setFeatureFlag("toolbox.enabled", false)
                //.setFeatureFlag("filmstrip.enabled", false)
                .setFeatureFlag("call-integration.enabled", true).  // Add this flag and set to true
                .build()
        JitsiMeet.setDefaultConferenceOptions(defaultOptions)
```
        
        
If I add `.setFeatureFlag("call-integration.enabled", true)` at any place it makes impossible to play video when shared via youtube url. 

This happens in Jitsi sample demo as well.

Although this is not mentioned in the description of the given feature flag which makes it confusing.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

9.2.2

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
We ran into many problems with ConnectionService, that's why it's off by default :-( I wasn't aware of this one though...

**Comment by mdhanif-simformsolutions** [comment]
<img width="716" alt="Screenshot 2024-06-07 at 8 00 06 PM" src="https://github.com/jitsi/jitsi-meet/assets/63775307/8a9d5bb8-8fb7-4bc6-9fc4-9794a145f218">

Still documentation shows it ON by default 

Should probably update that as well

**Comment by saghul** [comment]
Good point!

**Comment by mdhanif-simformsolutions** [comment]
Do you think this can be fixed ? We need this feature enable for all platforms and not run into this kind of issues ?

**Comment by saghul** [comment]
I don't know how, but if you figure it out, a PR would be welcome.
