### ISSUE TITLE
impossible start subtitles when a conference has a password

### ISSUE THREAD

**Issue by MahmoudSamy201** [jitsi/jitsi-meet#14810]
### What problem are you trying to solve?

Is there feature request related to a problem Iam facing ?

The problem : when a conference started and "Password" exists, enable transcription/subtitles has no effect without any notifications. I understand that the problem in password from my logs

Jigasi 2024-07-06 04:35:54.401 SEVERE: [27453] org.jitsi.jigasi.JvbConference.joinConferenceRoom().726 net.java.sip.communicator.service.protocol.OperationFailedException: Failed to join chat room test@conference.test.grade.com with nickname: 66b63668. The chat room requests a password.

### What solution would you like to see?

Describe the solution I would like

when I start a conference with "Password" , enable transcription/subtitles , it should be worked fine so how can I do that .

**Comment by saghul** [comment]
You need to make the Jigasi user an admin IIRC. Right @damencho ?

**Comment by MahmoudSamy201** [comment]
So how can I do that "make the Jigasi user an admin" ?

**Comment by saghul** [comment]
In the prosody config, list its JID in the admin config.

**Comment by damencho** [comment]
Nope, you need to enable this module 
https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_password_whitelist.lua
and list in the config the jis of the transcriber to be whitelisted.

**Comment by saghul** [comment]
🙏

**Comment by MahmoudSamy201** [comment]
I installed this module but can you clarify in some details how can I list in the config the jis of the transcriber to be whitelisted ?

**Comment by MahmoudSamy201** [comment]
as I create user jigasi@recorder.mydomain to make transcriber hidden so how can I whitelist this user and in which part of configuration ?

**Comment by MahmoudSamy201** [comment]
Still not working , I downloaded "mod_muc_password_whitelist.lua" and put it in /usr/share/jitsi-meet/prosody-plugins/ then in prosody config file "mydomain.cfg.lua" in Component "conference.mydomain" "muc" section I put 

modules_enabled = {
        "muc_meeting_id";
        "muc_domain_mapper";
        "token_verification";
        "mod_muc_password_whitelist";
    }

muc_password_whitelist = { "jigasi@recorder.mydomain" }

**Comment by damencho** [comment]
Glad it worked!

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by MahmoudSamy201** [comment]
Oki , Thank you .
