### ISSUE TITLE
Audio/Video Call Issues with Jitsi Meet on Flutter Mobile Application

### ISSUE THREAD

**Issue by linkzeeshan** [jitsi/jitsi-meet#14813]
### What happened?

I am writing to report an issue I am currently facing with the Jitsi Meet server configured on Azure using Docker Compose. 

Initially, the audio and video functionality was working perfectly on both the browser and mobile application. However, I am now encountering the following problems:

1- Flutter mobile app : The call connects, but the audio and video are not working.
2- Browser: The call connects, but only the audio works; the video is not working.
It is important to note that when I use your Jitsi server at https://meet.jit.si/, both the browser and the mobile application work as expected.

Could you please provide guidance and a proper solution to resolve these issues?

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

v10

### Relevant log output

```shell
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2qjbocrctodm7urflr1hutuam7' failed: 
BridgeChannel.js:393 2024-06-07T19:13:58.613Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=1phksgjg53rmss7ugsqolod1ni' failed: 
BridgeChannel.js:393 2024-06-07T19:14:00.829Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2qjbocrctodm7urflr1hutuam7' failed: 
BridgeChannel.js:393 2024-06-07T19:14:02.308Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=1phksgjg53rmss7ugsqolod1ni' failed: 
BridgeChannel.js:393 2024-06-07T19:14:05.296Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2qjbocrctodm7urflr1hutuam7' failed: 
BridgeChannel.js:393 2024-06-07T19:14:07.008Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:393 2024-06-07T19:14:09.735Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1001 endpoint closed
BridgeChannel.js:393 2024-06-07T19:14:27.944Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1001 endpoint closed
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2c7vqhnbjq83kogcafe79mdbu1' failed: 
BridgeChannel.js:393 2024-06-07T19:14:30.131Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2c7vqhnbjq83kogcafe79mdbu1' failed: 
BridgeChannel.js:393 2024-06-07T19:14:32.001Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2c7vqhnbjq83kogcafe79mdbu1' failed: 
BridgeChannel.js:393 2024-06-07T19:14:33.912Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://meet2.medchois.com/colibri-ws/172.24.0.5/57b9e0039c3c5d8e/e0cc590a?pwd=2c7vqhnbjq83kogcafe79mdbu1' failed: 
BridgeChannel.js:393 2024-06-07T19:14:37.872Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
﻿
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Do you have any Azure proxy of any kind in front of the Docker HTTP entry?

**Comment by damencho** [comment]
Port udp 10000 on the bridge is not accessible to the clients. It is blocked by firewall, or it is not forwarded from the public IP to the machine hosting jvb.

**Comment by linkzeeshan** [comment]
No firewall. Firewall is deactivated.

**Comment by linkzeeshan** [comment]
[saghul](https://github.com/saghul) No

**Comment by athenadever** [comment]
Could you please explain about udp 10000?
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/3e55466f-9699-4edb-b041-8e8b86602615)

**Comment by damencho** [comment]
This is by default the port used by the videobridge that needs to be exposed to the clients so they can send media to the bridge.

**Comment by linkzeeshan** [comment]
[damencho](https://github.com/damencho) Resolved! I activated Port udp 10000 Now working as expected.
Thanks.

**Comment by linkzeeshan** [comment]
Resolved
