### ISSUE TITLE
Enable auto transcription using jigasi for jitsi meets after moderator comes in (like auto recording using jibri)

### ISSUE THREAD

**Issue by MahmoudSamy201** [jitsi/jitsi-meet#14822]
### What problem are you trying to solve?

I now face a problem that I need transcription to be enabled by default when create meet and moderator comes in without any user interaction as I want to transcribe all meets to be used as reference even if the users doesn't use subtitles buttons by him self .

in another words , I need to auto transcribe meets when moderator comes in like auto recording option . 

### What solution would you like to see?

I would like to see solution for my case , for example option in config.js or prosody module that can be used to enable auto transcribe after moderator comes in meet .

**Comment by grape9292** [comment]
It would be a great feature.
