### ISSUE TITLE
Web Client Accessibility Status Messages

### ISSUE THREAD

**Issue by stormdragon2976** [jitsi/jitsi-meet#14823]
### What happened?

The status messages, when someone raises their hand, joins or leaves the meeting, or uses a reaction are not automatically read to screen reader users. This is fixable with aria live regions. More information at <https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html>.

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [X] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

All versions.

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Ops, looks like this fell through the cracks. Do you intend to send a PR?
