### ISSUE TITLE
(FR) Please provide official FlatPak for Jitsi Meet

### ISSUE THREAD

**Issue by zWhdmB5T** [jitsi/jitsi-meet#14831]
### What solution would you like to see?

Dear all,

there is a [Jitsi Meet FlatPak](https://flathub.org/apps/org.jitsi.jitsi-meet) available. Unfortunately, it is not officially maintained like others (e.g. [Firefox FlatPak](https://flathub.org/apps/org.mozilla.firefox), [LibreOffice FlatPak](https://flathub.org/apps/org.libreoffice.LibreOffice) or [digiKam FlatPak](digiKam)).

I would appreciate that very much. I expect high security as well as an up-to-date release (including all used libraries and such) of an official package.

Thank you!

**Comment by saghul** [comment]
We already maintain many packages and SDKs.

We cannot afford to support every packaging system under the sun, so alas we won't be supporting official builds.

**Comment by zWhdmB5T** [comment]
OK. Sad, but OK.
