### ISSUE TITLE
Use Jitsi without Google Meta or Microsoft

### ISSUE THREAD

**Issue by AausHall** [jitsi/jitsi-meet#14838]
### What problem are you trying to solve?

I try to use Jitsi without Google Microsoft or Meta

### What solution would you like to see?

Create an Jitsi Account or use without an account

### Is there an alternative?

Do not use Jitsi

**Comment by saghul** [comment]
You can use Jitsi Meet just fine without any of those. Just not meet.jit.si. On our free deployment we had to enable authentication, you can read more details here: https://jitsi.org/blog/authentication-on-meet-jit-si/
