### ISSUE TITLE
Unable to Log-In as moderator in Custom Android App using Sdk - Redirect me to Download the application

### ISSUE THREAD

**Issue by shivam-sometime** [jitsi/jitsi-meet#14837]
### What happened?

When I start a meeting in Custom android app using android mobile sdk, it ask me to login as moderator or wait. If i click login then it open my default browser i.e. chrome in my case and then redirect to install Jitsi Mobile Application to install.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [X] Custom app using a mobile SDK

### Browser / app / sdk version

9.2.2

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
When using the SDK you cannot control authentication if you are using our free server meet.jit.si.

You need to either use JaaS (jaas.8x8.vc) or host your own Jitsi meet instance.
