### ISSUE TITLE
Video Quality Impaired - The bridge Channel has been disconnect

### ISSUE THREAD

**Issue by DL7BJ** [jitsi/jitsi-meet#14841]
### What happened?

Hello,

I've running 3 machines, one is only a control server and two others configured as Videobrigdes. There are no firewall rules, no appamor, no selinux, no docker and all three machines are in the same network. The Jitsi installation is only for internal use in a separeted network. Also all Clients (Windows 10 and Raspberry) with different Browsers (Edge, Firefox, Chrome - all updated to newest versions) are in the same network.

Nearly four years these systems worked like a charme!

Yesterday, I update all 3 machines to Debian 11.9 and these Jitsi parts.

Server:
```
root@labomsvv142:/etc/jitsi# dpkg -l | grep jitsi
ii  jitsi-meet                     2.0.9457-1                     all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody             1.0.7952-1                     all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver          1.0.7952-1                     all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                 1.0.7952-1                     all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config          1.0.7952-1                     all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2             2.3-105-ge155b81e-1            all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                     0.4.1-jitsi1                   all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                2.1.0.10-jitsi1                amd64        JSON parser/encoder for Lua
```
Videobridges:
```
root@labomcl1611:/etc/jitsi/videobridge# dpkg -l | grep jitsi
ii  jitsi-videobridge2            2.3-105-ge155b81e-1            all          WebRTC compatible Selective Forwarding Unit (SFU)
```
Since this update I got also the message "Video Quality Impaired - The bridge Channel has been disconnect" if two users are connected to one room. This is a problem, which I could found in many other reports, but only in context with Docker and NAT.

The only SEVERE log entry is this one on the videobridge (for testing I use only one videobridge) (full log attached as file)

[xx.log](https://github.com/user-attachments/files/15883724/xx.log)

```
JVB 2024-06-18 10:09:43.629 INFO: [75] [confId=ecde7d5d355118f2 conf_name=kd@conference.meet.labom.local meeting_id=4a2d7a80 epId=3d07ce6c stats_id=Lilly-2Gg] Endpoint$createSctpConnection$3.onReady#610: SCTP connection is ready, creating the Data channel stack
JVB 2024-06-18 10:09:43.630 INFO: [75] [confId=ecde7d5d355118f2 conf_name=kd@conference.meet.labom.local meeting_id=4a2d7a80 epId=3d07ce6c stats_id=Lilly-2Gg] Endpoint$createSctpConnection$3.onReady#634: Will wait for the remote side to open the data channel.
JVB 2024-06-18 10:10:10.153 SEVERE: [22] [confId=ecde7d5d355118f2 conf_name=kd@conference.meet.labom.local meeting_id=4a2d7a80 epId=7a1c8f76 stats_id=Ludie-i9e] Endpoint.scheduleEndpointMessageTransportTimeout$lambda$26#689: EndpointMessageTransport still not connected.
JVB 2024-06-18 10:10:10.422 SEVERE: [22] [confId=ecde7d5d355118f2 conf_name=kd@conference.meet.labom.local meeting_id=4a2d7a80 epId=3d07ce6c stats_id=Lilly-2Gg] Endpoint.scheduleEndpointMessageTransportTimeout$lambda$26#689: EndpointMessageTransport still not connected.
```
jvb.conf

```
videobridge {
        health {
            require-valid-address = false
            interval = 1 minute
            timeout = 90 seconds
            max-check-duration = 3 seconds
            sticky-failures = false
            require-stun = false
        }
        http-servers {
                public {
                        port = 9090
                }
        }
        websockets {
                enabled = true
                domain = "meet.labom.local:443"
                tls = true
                server-id=jvb3
        }
        apis {
          rest: {
             enabled: true
          }
        }
}
```
Videobridge conf

```
JVB_HOSTNAME=meet.labom.local
# sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
JVB_HOST=meet.labom.local
# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347
# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=LheE6yRE
# adds java system props that are passed to jvb (default are for home and logging config file)
JAVA_SYS_PROPS="-Dconfig.file=/etc/jitsi/videobridge/jvb.conf -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
```
Please, where could I have a look to get a working system?
Or I have to restore the backups, never change a running system? ;-)

Tom

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Edge 126.0.2592.56, Firefox 127.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
`server-id=jvb3` this part should be different in your different videobridges. Share your nginx config about `colibri-ws` endpoints and the endpoints used there. You should have 
At least 2 rules, one of them should be 
```
location ~ ^/colibri-ws/jvb3/(.*) {
   proxy_pass http://jvb3/colibri-ws/default-id/$1$is_args$args;
...
```
That should connect to the upstream:
```
upstream jvb3 {
    zone upstreams 64K;
    server 127.0.0.1:9090;
    keepalive 2;
}
```
Where the IP address instead of localhost will be the jvb internal address and port 9090 will be accessible from nginx machine to the jvb machine.

**Comment by DL7BJ** [comment]
Thanks for answer!

There is one virtual machine with jitsi-meet, nginx and two hardware boxes. The videobridge on the VM is jvb1 and is always deactivated. jicofo and nginx are running on this VM. 

On the two hardware boxes, only videobridges are running, that's jvb2 and jvb3. 

Attached is the nginx conf. There is only one location for colibri-ws with parameter for the videobridges. 
[nginx.txt](https://github.com/user-attachments/files/15884650/nginx.txt)

**Comment by damencho** [comment]
Your nginx config expects that you have a single jvb that is running on the same machine as nginx (on 127.0.0.1:9090) and that its server-id is `default-id`, it doesn't know anything about a jvb with `server-id=jvb3` and the ip address where to reach it.

```
    # colibri (JVB) websockets for jvb1
    location ~ ^/colibri-ws/default-id/(.*) {
        proxy_pass http://127.0.0.1:9090/colibri-ws/default-id/$1$is_args$args;
```

You need to fix your nginx config to connect to the two jvbs with correct id that is configured in the jvb.conf and the correct ip address, make sure nginx machine has access on that ip address and port.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by DL7BJ** [comment]
That's strange! I have restored the backup and now everything is working again. With the nginx configuration, which can't work at all :-) All 3 video bridges are active, no problems.
