### ISSUE TITLE
Audio Source Selection Issue with AirPods on iPhone 11 Pro Max in Jitsi Meet

### ISSUE THREAD

**Issue by CyberStranger** [jitsi/jitsi-meet#14840]
### What happened?

On an iPhone 11 Pro Max running iOS 17.5.1 with connected AirPods, the Jitsi Meet app does not automatically select the AirPods as the audio source during calls. Instead, the audio defaults to the phone's loudspeaker, requiring manual selection of AirPods from the audio sources each time. The phone also has Apple Watch Series 5 connected.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

24.2.2 build 1713875644

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
@Calinteodor

**Comment by Calinteodor** [comment]
I cannot reproduce this issue while testing with latest beta release on TestFlight.
Can you also test it @CyberStranger ? Thanks.
