### ISSUE TITLE
Update Jitsi Meet to get current external_api.js (need little support)

### ISSUE THREAD

**Issue by nzhtrtlc** [jitsi/jitsi-meet#1484]
Hi, i have very basic question.
I installed [this stable repo](https://jitsi.org/Main/InstallJitsiMeetDebianStableRepository)  into my docker container. Everything went okay until i released that external_api.js has an older version.
I can not use avatarUrl command or jwt token option. So i need to update my jitsi installation to get lastest API.
I tried to type some update commands but nothing happend.
Should i install [this nighlty repo](https://jitsi.org/Main/InstallJitsiMeetDebianNightlyRepository) ? 
Or what should i do to get lastest external_api codes.
I need to be able to use everything which is in current [external_api.js](https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js) file.

Thanks for your help.

**Comment by saghul** [comment]
The latest changes to the external API haven't made it to the stable repo yet, you'll need to use the nightly if you want the latest and the greatest.

**Comment by nzhtrtlc** [comment]
Okay, thank you. Thats what i wanted to learn !

**Comment by nzhtrtlc** [comment]
Hi, i just installed jitsi-meet nightly repo. But still i couldn't use new commands in external_api.js

![screen shot 2017-04-11 at 16 42 24](https://cloud.githubusercontent.com/assets/17534778/24912127/e706ec52-1ed5-11e7-956b-72882facdb3c.png)

Any suggestions ?

**Comment by nzhtrtlc** [comment]
Also video bridge doesnt work in unstable version. When someone try to join the room app crashes.

**Comment by damencho** [comment]
Not an issue here with jvb, check you logs for errors. If you are not using pubsub for balancing bridges, when updating only the bridge sometimes you need to restart jicofo.

**Comment by nzhtrtlc** [comment]
@damencho I already restarted all service, actually main problem is about external_js. How i can use lastest commands like change avatarUrl ?

**Comment by damencho** [comment]
You mentioned jvb problem, that's why I wrote that. 
I do not see why avatarUrl will not work. I'm waiting for @hristoterezov to chime in about that.
Are you sure, you are using the latest code from unstable?
Can you paste the result of: $ dpkg -l | grep jitsi

**Comment by hristoterezov** [comment]
If this is not working definitely external_api.js is not the latest one. But I don't have any idea why.

**Comment by nzhtrtlc** [comment]
@damencho I took a screenshot check this out please.
![screen shot 2017-04-12 at 10 00 12](https://cloud.githubusercontent.com/assets/17534778/24945154/e1869d40-1f66-11e7-95e8-0c0bab6893fc.png)

**Comment by saghul** [comment]
@nzhtrtlc I just did a test and it's working fine locally. Can you double check your external_api.js file looks like the one in the repo? Also make sure you flush all caches or start in incognito mode when testing.

**Comment by nzhtrtlc** [comment]
@saghul I opened in incognito mode. Caches are disabled.
Still same in external_api.js. No avatarUrl.

![screen shot 2017-04-12 at 14 50 37](https://cloud.githubusercontent.com/assets/17534778/24956244/7f0ec3b2-1f8f-11e7-9279-a5b54842a098.png)

Also as i said before there is an issue about conferance, when some one try to join room it causes an error.
> [conference.js] <e.value>:  CONFERENCE FAILED: conference.videobridgeNotAvailable

![screen shot 2017-04-12 at 15 07 26](https://cloud.githubusercontent.com/assets/17534778/24956766/d2c82a64-1f91-11e7-8e14-7b9f55e78dd0.png)


I didn't get any error in stable repo. Its works just fine.

But in nightly..

I setup Ubuntu 14.04 into docker. Then i installed java 8 and some software packages ubuntu need. After that i followed the Jitsi Nightly Repo install guide.
Everything went fine until i realize the video conferance has error and there is an old version of external_api.js
I just want to be able to use lastest external_api.js and working video conferance.

**Comment by saghul** [comment]
@nzhtrtlc You seem to have more than one issue here:

- external API, which I cannot reproduce
- no videobridges available

Can you restart the JVB and try to join a conference normally? Does that work?

**Comment by nzhtrtlc** [comment]
@saghul ,
I restarted the JVB but still getting conferance failed error.

**Comment by saghul** [comment]
@nzhtrtlc Hum, how about Jicofo? Can you see the JVB connecting to it in its logs?

**Comment by nzhtrtlc** [comment]
@saghul  I dont know how to check the Jicofo's logs. I don't know even what is it.

**Comment by nzhtrtlc** [comment]
@damencho I just updated nighlty repo to the lastest one. Here is the new screen.

<img width="570" alt="screen shot 2017-04-13 at 16 47 20" src="https://cloud.githubusercontent.com/assets/17534778/25007461/3f05acba-2069-11e7-80c2-5f59c2411267.png">
**1.0.1992-1** is the lastest version in the nightly repo list.
As you can see i have the lastest version of jitsi-meet but still i can not use **avatarUrl** command.
BTW after the update jitsi-meet nighlty repo the conferance issue has gone. 
Now the only thing that i need to be able to use **avatarUrl** command.

Also is there any way to update my jitsi version without the install from stratch ?

**Comment by nzhtrtlc** [comment]
Well, here is the solution.
external_api.js not up to date.
But external_api.min.js is up to date.
So just call the external_api.min.js so you can use the lastest version.

Problem solved.
