### ISSUE TITLE
Android app: cant join meeting on community Jitsi instance without logging in through Google, Facebook, or Microsoft (Github) [PART II]

### ISSUE THREAD

**Issue by Franco-Sparrow** [jitsi/jitsi-meet#14846]
### What happened?

@saghul @exercismnow Hi guys, I opened this issue, following [this one](https://github.com/jitsi/jitsi-meet/issues/13843) you had before

I am opening this issue because is not working for me eather on Jitsi Meet Android App `24.2.2` nor `23.4.0`, with Jitsi Meet server `2.0.9457-1`. The app was downloaded from the Play Store. I am not using auth, it is a self-hosted server on public network. I can join using mobile browser on Desktop mode, but not able to do it using the app. I configured the app to join meetings with the name Franco (mobile), I invite myself with a link invitation (made from my PC desktop browser) and the apps keeps saying that there is no moderator in the room, that I have to wait for one or become in the moderator. There is indeed a moderator in the room, my other account which created the room using my Desktop browser on my PC.

I was able to joing with the Android app, but I had to become in the moderator and invite others (my laptop) to the room. I dont know if other Android could have same problem if try to joing without moderator permissions

PS: the iOS app works, but not the Android app (big problem here, as this is most used)

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Android app `24.2.2` and `23.4.0`

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

if I try to access to the invitation

![WhatsApp Image 2024-06-17 at 12 17 11 AM](https://github.com/jitsi/jitsi-meet/assets/56793015/c850b662-f2c6-4642-8e9b-a7dd0b6f2e39)

If I set the URL o name of the room, it stays forever waiting for the moderator:

![WhatsApp Image 2024-06-16 at 10 08 30 PM](https://github.com/jitsi/jitsi-meet/assets/56793015/a80efdcf-16e8-4265-81f9-fb9e46509c86)

**Comment by saghul** [comment]
Can you please share your server's URL so we can test?

**Comment by Franco-Sparrow** [comment]
> Can you please share your server's URL so we can test?

Hi Sir

This is my server

https://meet.parallaxnet.com/

**Comment by saghul** [comment]
Looks like you have XMPP auth enabled in your server.

Can you please share your Prosody config?

**Comment by saghul** [comment]
To be clear, the auth in your server has nothing to do with the app or the Firebase auth we use on meet.jit.si.

You might have enabled XMPP with by mistake. With that auth mechanism you can create users in the local Prosody instance and have them authenticate to your server.

**Comment by Franco-Sparrow** [comment]
Hi Saul.

Sorry for the late reply, I was sleeping. To connect to the server and
become a moderador you need an admin account, previously created with the
prosody. If I just want to join an existence meet, created from a Desktop
browser, where there is already a moderator inside, and has invited me with
a shared link, or I know the full link to the meet...it just doesn't work
from the Android App.

I have created an admin account with prosody, so you can test this by
yourself.

```
prosodyctl register saghul meet.parallaxnet.com saghuladmin123
general             warn        Lua 5.1 has several issues and support is
being phased out, consider upgrading
```

Thanks in advance, and let me know the results of your tests :)

**Comment by Franco-Sparrow** [comment]
Hi @saghul 

Sorry for the late reply, I was sleeping. To connect to the server and become a moderador you need an admin account, previously created with the prosody. If I just want to join an existence meet, created from a Desktop browser, where there is already a moderator inside, and has invited me with a shared link, or I know the full link to the meet...it just doesn't work from the Android App.

This is the config in the prosody:

![imagen](https://github.com/jitsi/jitsi-meet/assets/56793015/030cd8b3-7834-49bd-9bc1-a87c10a02d72)

![imagen](https://github.com/jitsi/jitsi-meet/assets/56793015/0cbe9ba8-566b-441b-b21f-5ed7dfc4e485)

I have created an admin account with prosody, so you can test this by yourself.

```
prosodyctl register saghul meet.parallaxnet.com saghuladmin123
general             warn        Lua 5.1 has several issues and support is being phased out, consider upgrading
```

Thanks in advance, and let me know the results of your tests :)

**Comment by saghul** [comment]
Hum, I see. We must have broken guest login :-/ 

@Calinteodor can you PTAL?

**Comment by Calinteodor** [comment]
I managed to test with a standard authentication instance I am not able to reproduce your issue. Everything works as expected.
Can you send us your config.js and your full prosody configuration? 

Thank you!

**Comment by saghul** [comment]
The apps and browser use the same ports.

**Comment by Franco-Sparrow** [comment]
> I managed to test with a standard authentication configured instance and I am not able to reproduce your issue. Everything works as expected. Can you send us your config.js and your full prosody configuration?
> 
> Thank you!

Hi SIr

Did you find anything wrong on my configuration?

**Comment by Franco-Sparrow** [comment]
May I have a follow up on this please?

**Comment by saghul** [comment]
The config looks ok in general. We have a `jitsi-anonymous` auth type which extends anonymous with some Jitsi session data, but that is mostly used for WS IIRC, so you should be fine since you use BOSH.

I wonder if something got broken with the deprecated Jicofo config. Could you test migrating to jicofo.conf rather than using the properties file?

**Comment by Franco-Sparrow** [comment]
Hi Saul, thanks for your reply

I will try to follow the official documentation, to configure jicofo.conf
rather than properties file. Will let you know.

Thanks in advance

**Comment by Franco-Sparrow** [comment]
@saghul Hi Sir

Related with what you suggested to me, to edit the deprectaed jicofo config file instead the properties file...what should I edit here?

`/etc/jitsi/jicofo/jicofo.conf`
```bash
# Jicofo HOCON configuration. See reference.conf in /usr/share/jicofo/jicofo.jar for
#available options, syntax, and default values.
jicofo {
  xmpp: {
    client: {
      client-proxy: "focus.meet.parallaxnet.com"
      xmpp-domain: "meet.parallaxnet.com"
      domain: "auth.meet.parallaxnet.com"
      username: "focus"
      password: "MxBEgXwBUg3kRLF3"
    }
    trusted-domains: [ "recorder.meet.parallaxnet.com" ]
  }
  bridge: {
    brewery-jid: "JvbBrewery@internal.auth.meet.parallaxnet.com"
  }
}
```

The `/etc/jitsi/jicofo/`
```bash
org.jitsi.jicofo.auth.URL=XMPP:meet.parallaxnet.com
```

You said that my config looks OK, that I should try with the deprecated jicofo.conf file. I am following latest jitsi documentation.
