### ISSUE TITLE
Sharing my HDR enabled screen through Edge browser makes views for others overly bright

### ISSUE THREAD

**Issue by thadguidry** [jitsi/jitsi-meet#14847]
### What happened?

When I share my screen, others complain that it appears extremely bright and washed out.
We think it might be HDR setting since my screens are HDR capable, and I enable it also for HDR video streaming since I often watch HDR content online.
If I disable HDR by simply toggling it off, even while screen sharing, then everything appears normal to others.
Any options other than disabling HDR prior to meetings?  A preference Jitsi setting perhaps?

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Edge Version 126.0.2592.61 (Official build) stable app, beta channel (64-bit)

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

**OS:** Windows 11 Pro
**Monitors :** AOC Q32G3WG3 
**Graphics card:**  Nvidia GeForce RTX 2070
**Windows 11 HDR Settings:**
![image](https://github.com/jitsi/jitsi-meet/assets/986438/abf966ce-194a-4a60-928b-d6eb01a71313)

**Comment by saghul** [comment]
We don't touch anything in the video feed, we just forward it.

I think this is something that needs to be addressed in the browser itself.

**Comment by thadguidry** [comment]
Thanks!  Looks like I just found a Microsoft Answer that's probably just as effective for anyone on Windows.
To quickly easily toggle HDR On/Off you can use **`Win + Alt + B`** keys to toggle HDR on and off for all HDR-capable displays.

I'll close this issue as resolved enough (since a pretty decent toggle keys workaround, that doesn't need preferences, already exists on Windows)

**Comment by thadguidry** [comment]
@saghul Might be wise to put that into the Jitsi docs somewhere?

**Comment by saghul** [comment]
Awesome!
