### ISSUE TITLE
Disruptions with poor connection

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#14856]
### What happened?

A VC between Firefox Nightly 129.0a1~20240620040816 on Debian sid/unstable and Windows 11 with Google Chrome, the network connection was very poor (due to country and probably WiFI) and that caused audio loss, stalled video and in the end connection interruption. Using a BigBlueButton 2.3 server there was no loss of connection and only partly stalled video which then gracefully recovered.

How could this be debugged so a newer Jitsi is on par with an old BigBlueButton server?

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

*firefox-nightly* 129.0a1~20240620040816 on Debian sid/unstable and MS Windows 11 with Google Chrome

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

*jitsi-meet* 2.0.9578-1

**Comment by jallamsetty1** [comment]
There were some breaking changes in Firefox w.r.t to DTLS. Are you able to upgrade to the latest stable jitsi-meet 2.0.9584 and check if the issue persists? You can run a quick test on meet.jit.si as well.

**Comment by paulmenzel** [comment]
Thank you. I am running 2.0.9635-1 now, but unfortunately, I won’t be able to reproduce the issue as the communication partner is not at that location anymore. If you know how to simulate bad network connection I could try it though.

**Comment by jallamsetty1** [comment]
You can use a tool like network link conditioner on macOS to simulate bad network connection.

**Comment by paulmenzel** [comment]
Thank you. Sorry for not specifying my system. I am using GNU/Linux.
