### ISSUE TITLE
DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. Duplicate a=msid lines detected at RTCPeerConnection.setRemoteDescription 

### ISSUE THREAD

**Issue by yjt-sys** [jitsi/jitsi-meet#14857]
### What happened?

Help me!!!
This may be due to an issue with the updated version of Google Chrome. This issue occurred when my Google version was 126, but when I downgraded my Google version to 120, the issue disappeared. However, I now need a solution to the 126 issue. Because I cannot guarantee that every user's browser version is below 126, is there anyone who can help me solve it? Thank you

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

126.0.6478.114

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by yjt-sys** [comment]
This issue seems to have been caused by a change in the RTP mechanism after upgrading from Chrome browser to version 123.

**Comment by saghul** [comment]
Are you able to reproduce this on meet.jit.si? If you run your own server, what version of the components do you run?

**Comment by yjt-sys** [comment]
lib-jitsi-meet [1836.0.0+d05325f3 ]

**Comment by saghul** [comment]
You didn't answer any of my questions.

**Comment by yjt-sys** [comment]
I'm sorry, but I'm using the lib-jitsi-meet library and I'm using the latest version

**Comment by yjt-sys** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/154602644/6074c8ac-0871-43a3-82f5-fb96d8ef158f)

**Comment by saghul** [comment]
You can't just use a random lib-jitsi-meet version, you need to use the one the deployment is using.

What code are you using to reproduce the problem?

**Comment by yjt-sys** [comment]
options: {
                hosts: {
                    domain: "meet.jitsi",
                    muc: "muc.meet.jitsi",
                },
                serviceUrl: "wss://upgrader.zjyltech.com:8443/xmpp-websocket",
                disableSimulcast: false,
                enableRemb: true,
                enableTcc: true,
                resolution: 720,
                constraints: {
                    video: {
                        height: {
                            ideal: 640,
                            max: 640,
                            min: 180
                        },
                        width: {
                            ideal: 720,
                            max: 720,
                            min: 320
                        }
                    }
                },
                enableInsecureRoomNameWarning: true,
            },
            connection: null, //连接对象
            room: null, //房间对象
            name: "工作",
            selfMedia: {}, //本地媒体流对象
            userList: [], //其他用户列表
            beVideoStart: false,
            beInRoom: false,

            userNumber: 1,
            // 功能按钮
            ishow1: true,
            ishow2: true,
            ishow3: false,
            chatIsShow: false,
            nowtime: 0,
            nowMine: 0,
            nowMiao: 0,
            timeSet: null,
            inviteIsShow: false,
            tipInfo: null,
            isShowTip: false,
            timeSetOver: null,

            mediaRecorder: null,
            chunks: [],
            isTab: false,
            recordMedia: {},
            record: null,
            streamArr: [],
            mixer: null,
            screenShow:false,
            srtime: 0,
            srMine: 0,
            srMiao: 0,
            srSetTime:null
        };
    },
    created() {
        // 初始化库
        JitsiMeetJS.init();
        // 设置日志级别，如果是INFO控制台东西会很多
        JitsiMeetJS.setLogLevel(JitsiMeetJS.logLevels.ERROR);
    },


Then in my vue project, I introduced the library in script

<script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>

**Comment by saghul** [comment]
You seem to be using Docker, is that so? In that case, you need to source your own lib-jitsi-meet, not the one in meet.jit.si.

**Comment by yjt-sys** [comment]
ok
