### ISSUE TITLE
How to overwrite react native SDK config overwrite  and custom toolbar event binding

### ISSUE THREAD

**Issue by Bhoomi-tgs** [jitsi/jitsi-meet#14872]
### What happened?

I have assign in config object fullscreen options but it's not reflects on mobile sdk side so in another way we have tried to add custom button and on button click we can manage this from mobile side in that scenario button is loaded but SDK doesn't provide any type **custom event binding**

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

"@jitsi/react-native-sdk": "^2.2.1",

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by mapirpg** [comment]
Hello! 

Have you tried using prop flags?
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.ts

**Comment by Bhoomi-tgs** [comment]
> Hello!
> 
> Have you tried using prop flags? https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.ts

Thanks, Marcel Perin for your update,
I have tried this flag but it's won't  work, is there any specific configuration for that? I have to followed for android and iOS devices.

**Comment by mapirpg** [comment]
> > Hello!
> > Have you tried using prop flags? https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.ts
> 
> Thanks, Marcel Perin for your update, I have tried this flag but it's won't work, is there any specific configuration for that? I have to followed for android and iOS devices.

The flags property worked to change the interface on Android (including removing the full-screen), but I didn't test it on iOS.
The config property only worked in the React SDK, unfortunately I had a lot of problems with the React Native SDK, due to the 'onReadyToClose' and 'onConferenceLeft' listener, I ended up choosing to develop using WebView with React for the mobile app :/
