### ISSUE TITLE
Feature : count number of sessions

### ISSUE THREAD

**Issue by nderambure** [jitsi/jitsi-meet#14883]
### What problem are you trying to solve?

For stats purpose, in order to show to public funding than using FLOSS software works great and is well used.

### What solution would you like to see?

What would be cool is to count sessions lasting more than 5mn and retrieve a number for last week, last month, last year... sessions. Maybe via a shell command ?

And why not count also number of participants in each session ;)

**Comment by damencho** [comment]
You can already obtain that information: 
`curl http://localhost:8888/stats | jq .conferences` for number of ongoing conferences. 
Or number of conferences for the life of jicofo: `curl http://localhost:8888/stats | jq .total_conferences_created`
And the same for participants:
`curl http://localhost:8888/stats | jq .participants`
`curl http://localhost:8888/stats | jq .total_participants`.

You also have `curl http://localhost:8888/debug/conferences-full` to have a detailed output you can count participants per conference.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by nderambure** [comment]
Thx @damencho, and my bad I wrote too fast, I should have searched forums first !
