### ISSUE TITLE
How to get the onPress event of customToolbarButtons for particular button?

### ISSUE THREAD

**Issue by RiteshTriveni** [jitsi/jitsi-meet#14880]
### What happened?

How to get the onPress event of customToolbarButtons for a particular button?
like passing into the config 
customToolbarButtons: [
          {
            icon: "https://w7.pngwing.com/pngs/987/537/png-transparent-download-downloading-save-basic-user-interface-icon-thumbnail.png",
            id: "btn1",
            text: "Button one",
            onClick: () => {
              console.log('Hello');
            }
          }, {
            icon: "https://w7.pngwing.com/pngs/987/537/png-transparent-download-downloading-save-basic-user-interface-icon-thumbnail.png",
            id: "btn2",
            text: "Button two"
          }
        ],
        
i want to get onPress event of above buttons

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

"@jitsi/react-native-sdk": "2.2.1",

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by Bhoomi-tgs** [comment]
Facing Same issue, can anyone please suggest here?

**Comment by saghul** [comment]
@Calinteodor can you PTAL?

**Comment by Bhoomi-tgs** [comment]
@saghul @Calinteodor
Is there any update here?

**Comment by Calinteodor** [comment]
We are still looking into it.

**Comment by Bhoomi-tgs** [comment]
@Calinteodor any update for this issue?

**Comment by Calinteodor** [comment]
Not yet. As soon as a fix will be available you will be able to see it here.

**Comment by Bhoomi-tgs** [comment]
okay, Thank you

**Comment by Bhoomi-tgs** [comment]
Hello, is there any update here?

**Comment by Calinteodor** [comment]
Please take in consideration what I mentioned above. Thank you.
