### ISSUE TITLE
When doing audio call default voice option is speaker instead of phone

### ISSUE THREAD

**Issue by PaurushFrontM** [jitsi/jitsi-meet#14885]
### What happened?

When doing audio call default voice option is speaker instead of phone. How can we change default voice option to phone.
Please let us know how we can set default option to phone in this case?

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

"@jitsi/react-native-sdk": "^2.2.1"

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by 7mada123** [comment]
I am facing the same issue, it can be reproduced on the last version off official app on appstore on IOS 18..0.1.
Plus if the selected audio device is bluetooth and the user switch it to speaker or microphone the bluetooth option disappeared


https://github.com/user-attachments/assets/adb1ce7f-94c8-4cb7-bb7c-9c93a2c4c572
