### ISSUE TITLE
ReactNativeSDK. Duplicates the room name in Cyrillic.

### ISSUE THREAD

**Issue by qnafin** [jitsi/jitsi-meet#14892]
### What happened?

 "@jitsi/react-native-sdk": "^2.2.1"
 
```
const room = 'кгб';

<JitsiMeeting
        room={room}
        serverURL={'https://example.com/'}    
 />
 
Will return https://example.com/кгб/кгб
 
 ```
 
The solution is ``encodeURIComponent(room)``
if the library solved this on its own, it would reduce the number of errors and possible requests for technical support

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [X] Custom app using a mobile SDK

### Browser / app / sdk version

 "@jitsi/react-native-sdk": "^2.2.1"

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
@Calinteodor I think this is a pretty sensible thing to do, which I thought we already did, maybe we missed a spot.
