### ISSUE TITLE
Error while building deb files

### ISSUE THREAD

**Issue by LEAGUEDORA** [jitsi/jitsi-meet#14899]
### What happened?

So, I have modified jisti code to fit my needs. I am trying to host by following https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-jitsi-meet#building-debs guide. I am running on a debian 12 system. I am getting the following error 

```bash
dh_install: warning: jitsi-meet-web missing files: css/all.css
dh_install: error: missing files, aborting
mv: cannot stat 'debian/jitsi-meet-web/usr/share/jitsi-meet/lang/af.json': No such file or directory
make[1]: *** [debian/rules:20: af] Error 1
make[1]: Leaving directory '/home/sandeep/meet-repo'
make: *** [debian/rules:10: binary-indep] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-indep subprocess returned exit status 2
```

when running 

```bash
dpkg-buildpackage -A -rfakeroot -us -uc -tc
```

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

latest

### Relevant log output

```shell
dh_install: warning: jitsi-meet-web missing files: css/all.css
dh_install: error: missing files, aborting
mv: cannot stat 'debian/jitsi-meet-web/usr/share/jitsi-meet/lang/af.json': No such file or directory
make[1]: *** [debian/rules:20: af] Error 1
make[1]: Leaving directory '/home/sandeep/meet-repo'
make: *** [debian/rules:10: binary-indep] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-indep subprocess returned exit status 2
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Have you successfully executed `npm install` and `make` before executing `dpkg-buildpackage`?

**Comment by LEAGUEDORA** [comment]
Yes. There were no errors @damencho

**Comment by damencho** [comment]
And you do not have such a file css/all.css?

**Comment by LEAGUEDORA** [comment]
Yeah I dont have. I checked in the jitsi original code also I didn't find any

**Comment by LEAGUEDORA** [comment]
Sorry guys! There is an error while doing make. We fixed it. Working fine. Sorry to waste your time @damencho

**Comment by damencho** [comment]
There is no such file in the code. That code is produced after successful building. I suspect the build did not succeed on your end and that's why the file is missing and the errors you see.

**Comment by damencho** [comment]
👍

**Comment by damencho** [comment]
It depends on what you want to do?

Please, when you have questions or problems use the community forum before opening new issues, thank you.
