### ISSUE TITLE
[ios] I can mute/unmute in visitors mode from CallKit

### ISSUE THREAD

**Issue by Anfieldd** [jitsi/jitsi-meet#14897]
### What happened?

It looks like a small bug with IOS mobile app. As a visitor, I can mute/unmute from CallKit.  Maybe it should be disabled?

https://github.com/jitsi/jitsi-meet/assets/32684253/faa40fd4-abc3-4efd-a146-9e48950d7831

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

24.2.2

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
This is a fun one @damencho. I'm not sure we can disable the CallKit mute button 😅

**Comment by damencho** [comment]
Well, I guess it does not work, so we will have it :)

**Comment by Anfieldd** [comment]
Ok, I understand) What do you think about requesting a promotion when the user clicks the CallKit unmute button? Is it possible?

**Comment by Anfieldd** [comment]
Ok, thanks for the answers)
