### ISSUE TITLE
Jitsi Meet Mobile app for IOS opens only on WiFi

### ISSUE THREAD

**Issue by housecat** [jitsi/jitsi-meet#1490]
App freezes on the launch screen and then crashes. Is that intentional? If not, does anyone have a fix for it?

**Comment by saghul** [comment]
I do know we have a bug when you try to open the app without any connectivity at all (even if we fix that there is nothing you can do without connectivity though), but the app works just fine over 3/4G. Is this what you're experiencing?

**Comment by housecat** [comment]
Not what I experience. For me app opens about half the time when it's not on the WiFI. Maybe you van point me to a class where the connection is being set?

**Comment by lizhaoch** [comment]
maybe U should try to deploy it on web server
like that : only have  ip ,don't use two ip with NAT


I‘ve’ created a QQ group ， groupid:638328355
welcome join and discuss!
[//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7](url)

**Comment by lizhaoch** [comment]
maybe U should try to deploy it on web server
like that : only have ip ,don't use two ip with NAT

I‘ve’ created a QQ group for jitsi-meet in China ， groupid:638328355
IM:QQ (U can google it)
welcome join and discuss the R&D about JITSI !
[//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7](url)

**Comment by lyubomir** [comment]
As of Jitsi Meet for Android and iOS v1.9 which was built from source code before what's in master today, the app no longer downloads any files on the Welcome/launch screen so it should not rely on the availability of Internet.
