### ISSUE TITLE
can client send tow video streams (camera and screenshare) at the same time?

### ISSUE THREAD

**Issue by qllqzy** [jitsi/jitsi-meet#1491]
if , so how to do it? 
the demo is only one video. when open screenshare, will stop camera.

**Comment by LVBK** [comment]
@qllqzy i did this trick before.
i write a wrapper library work with lib-jitsi-meet allow connect to many meeting room and control everything at the same time. 
you need connect to 2 room for video stream and share screen without lib-jitsi-meet modified.

**Comment by saghul** [comment]
@qllqzy You can only share your video or your camera, not both at the same time. If you really need to, you can join twice and mute the tab with the camera share, so the screenshare will be selected as the active endpoint.

Please use the mailing list for questions in the future. Thanks!
