### ISSUE TITLE
Video recoding not available after finishing a meeting 

### ISSUE THREAD

**Issue by Next-Career** [jitsi/jitsi-meet#14919]
### What happened?

https://moderated.jitsi.net/644de6868480451d8cf00bac5a841b6dcdf986ab28a84ab19980bf1a9a02d575

above is my moderator id 

Kindly help on the same please 

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Microsoft Edge Version 125.0.2535.79 (Official build) (64-bit)

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

please try to recover the video

**Comment by saghul** [comment]
Did you not stop the recording before closing the tab?

**Comment by Next-Career** [comment]
I stopped it manually which is mandatory.

**Comment by saghul** [comment]
Did you not get a file in your downloads folder?

**Comment by Next-Career** [comment]
No I didn’t get the file

**Comment by saghul** [comment]
Then unfortunately it's lost. Sorry about that 😢
