### ISSUE TITLE
luajwtjitsi not working with lua5.4 and required for prosody 0.12.3

### ISSUE THREAD

**Issue by holzi1005** [jitsi/jitsi-meet#14918]
### What happened?

I installed the jitsi-meet-tokens package together with prosody 0.12.3 and I get an lua5.4 error in the prosody logs, that the tokens module cannot be found.

I can downgrade Prosody to 0.11.13 so it will use lua5.2 and the token module will work as expected. When I try to install the luajwtjitsi module with luarocks 5.4, I get a lot of errors an I can still not run prosody 0.12.

Prosody 0.12 must be installed bacause of an upgrade to Debian 12 and that has only prosody 0.12

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Browser current and  lates jitsi meet version

### Relevant log output

```shell
Jul 14 00:39:51 modulemanager	error	Error initializing module 'auth_token' on 'meeting.xxxxx': /usr/lib/prosody/util/startup.lua:203: module 'inspect' not found:
	No LuaRocks module found for inspect
	no field package.preload['inspect']
	no file '/usr/lib/prosody/inspect.lua'
	no file '/usr/local/share/lua/5.4/inspect.lua'
	no file '/usr/local/share/lua/5.4/inspect/init.lua'
	no file '/usr/local/lib/lua/5.4/inspect.lua'
	no file '/usr/local/lib/lua/5.4/inspect/init.lua'
	no file '/usr/share/lua/5.4/inspect.lua'
	no file '/usr/share/lua/5.4/inspect/init.lua'
	no file ''
	no file '/var/lib/prosody/.luarocks/share/lua/5.4/inspect.lua'
	no file '/var/lib/prosody/.luarocks/share/lua/5.4/inspect/init.lua'
	no file '/var/lib/prosody/custom_plugins/share/lua/5.4/inspect.lua'
	no file '/var/lib/prosody/custom_plugins/share/lua/5.4/inspect/init.lua'
	no file '/usr/lib/prosody/inspect.so'
	no file '/usr/local/lib/lua/5.4/inspect.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.4/inspect.so'
	no file '/usr/lib/lua/5.4/inspect.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file ''
	no file '/var/lib/prosody/.luarocks/lib/lua/5.4/inspect.so'
	stack traceback:
	[C]: in upvalue '_real_require'
	/usr/lib/prosody/util/startup.lua:203: in function 'require'
	/usr/share/jitsi-meet/prosody-plugins/token/util.lib.lua:21: in main chunk
	(...tail calls...)
	/usr/share/jitsi-meet/prosody-plugins/mod_auth_token.lua:8: in main chunk
	[C]: in function 'util.xpcall.xpcall'
	/usr/lib/prosody/core/modulemanager.lua:270: in upvalue 'do_load_module'
	/usr/lib/prosody/core/modulemanager.lua:353: in function 'core.modulemanager.load'
	/usr/lib/prosody/core/usermanager.lua:97: in function 'core.usermanager.initialize_host'
	/usr/lib/prosody/util/events.lua:81: in function </usr/lib/prosody/util/events.lua:77>
	(...tail calls...)
	/usr/lib/prosody/core/hostmanager.lua:108: in function 'core.hostmanager.activate'
	/usr/lib/prosody/core/hostmanager.lua:58: in field '?'
	/usr/lib/prosody/util/events.lua:81: in function </usr/lib/prosody/util/events.lua:77>
	(...tail calls...)
	/usr/lib/prosody/util/startup.lua:428: in function 'util.startup.prepare_to_start'
	/usr/lib/prosody/util/startup.lua:707: in function 'util.startup.prosody'
	/usr/lib/prosody/util/async.lua:156: in upvalue 'func'
	/usr/lib/prosody/util/async.lua:144: in function </usr/lib/prosody/util/async.lua:142>
Jul 14 00:39:51 mod_websocket	info	The 'cross_domain_websocket' option has been deprecated
```

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

jitsi-meet-prosody/stable,now 1.0.8043-1 all [installed]
jitsi-meet-tokens/stable,now 1.0.8043-1 all [installed]
jitsi-meet-turnserver/stable,now 1.0.8043-1 all [installed]
jitsi-meet-web-config/stable,now 1.0.8043-1 all [installed]
jitsi-meet-web/stable,now 1.0.8043-1 all [installed]
jitsi-videobridge2/stable,now 2.3-149-g793df5a9-1 all [installed]
lua-basexx/stable,now 0.4.1-jitsi1 all [installed,automatic]
lua-cjson/stable,now 2.1.0.10-jitsi1 amd64 [installed,automatic]

Prosody:
prosody/now 0.11.13-1 amd64 [installed,upgradable to: 0.12.3-1] --> This version is working. Installed from Ubuntu Archive Repo

**Comment by holzi1005** [comment]
related to this stale and closed issue: https://github.com/jitsi/jitsi-meet/issues/11490

**Comment by holzi1005** [comment]
when I install the inspect lua module before installing the luajwtjitsi, for lua5.4, it is working also with prosody 0.12
luarocks --lua-version 5.4 install inspect

Is it possile to add the module as an dependency into the jitsi-meet-tokens package

**Comment by saghul** [comment]
Ping @damencho

**Comment by holzi1005** [comment]
@saghul @damencho 
I found out, that I need to install lua5.4, liblua5.4-dev, and luarocks package before installing prosody 0.12 and then luarocks will be able to install the inspect rock for lua5.4

**Comment by gordnhoo** [comment]
This issue is still present i have just had it on debian

**Comment by saghul** [comment]
We now have it included in the jitsi repo, it's not necessary to install separately.

**Comment by gordnhoo** [comment]
Hmm why am I facing this issue then

**Comment by gordnhoo** [comment]
exactly what this person showed back in february  also on debian https://fiat-tux.fr/2024/02/29/jitsi-meet-avec-authentification-par-jwt-le-chainon-manquant/

Feb 06 10:14:30 modulemanager	error	Error initializing module 'token_verification' on 'conference.jitsi.test.com: /usr/lib/prosody/util/startup.lua:203: module 'inspect' not found:
	No LuaRocks module found for inspect
	no field package.preload['inspect']
	no file '/usr/lib/prosody/inspect.lua'
	no file '/usr/local/share/lua/5.4/inspect.lua'
	no file '/usr/local/share/lua/5.4/inspect/init.lua'
	no file '/usr/local/lib/lua/5.4/inspect.lua'
	no file '/usr/local/lib/lua/5.4/inspect/init.lua'
	no file '/usr/share/lua/5.4/inspect.lua'
	no file '/usr/share/lua/5.4/inspect/init.lua'
	no file ''
	no file '/var/lib/prosody/.luarocks/share/lua/5.4/inspect.lua'
	no file '/var/lib/prosody/.luarocks/share/lua/5.4/inspect/init.lua'
	no file '/var/lib/prosody/custom_plugins/share/lua/5.4/inspect.lua'
	no file '/var/lib/prosody/custom_plugins/share/lua/5.4/inspect/init.lua'
	no file '/usr/lib/prosody/inspect.so'
	no file '/usr/local/lib/lua/5.4/inspect.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.4/inspect.so'
	no file '/usr/lib/lua/5.4/inspect.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file ''
	no file '/var/lib/prosody/.luarocks/lib/lua/5.4/inspect.so'
	stack traceback:
	[C]: in upvalue '_real_require'
	/usr/lib/prosody/util/startup.lua:203: in function 'require'
	/usr/share/jitsi-meet/prosody-plugins/token/util.lib.lua:21: in main chunk
	(...tail calls...)
	...re/jitsi-meet/prosody-plugins/mod_token_verification.lua:34: in main chunk
	[C]: in function 'util.xpcall.xpcall'
	/usr/lib/prosody/core/modulemanager.lua:270: in upvalue 'do_load_module'
	/usr/lib/prosody/core/modulemanager.lua:353: in function 'core.modulemanager.load'
	/usr/lib/prosody/core/modulemanager.lua:131: in function 'core.modulemanager.load_modules_for_host'
	/usr/lib/prosody/util/events.lua:81: in function </usr/lib/prosody/util/events.lua:77>
	(...tail calls...)
	/usr/lib/prosody/core/hostmanager.lua:108: in function 'core.hostmanager.activate'
	/usr/lib/prosody/core/hostmanager.lua:58: in field '?'
	/usr/lib/prosody/util/events.lua:81: in function </usr/lib/prosody/util/events.lua:77>
	(...tail calls...)
	/usr/lib/prosody/util/startup.lua:428: in function 'util.startup.prepare_to_start'
	/usr/lib/prosody/util/startup.lua:707: in function 'util.startup.prosody'
	/usr/lib/prosody/util/async.lua:156: in upvalue 'func'
	/usr/lib/prosody/util/async.lua:144: in function </usr/lib/prosody/util/async.lua:142>

**Comment by saghul** [comment]
> module 'inspect' not found:

Have you installed the inspect module? The Debian version was a bit botched last I checked. You need to install the `lua-inspect` package, but then copy it to the Lua 5.4 libraries folder: `cp /usr/share/lua/5.3/inspect.lua /usr/share/lua/5.4/`

I hope that helps!

**Comment by gordnhoo** [comment]
it fixed it thanks

**Comment by enribar** [comment]
Other than the error mentioned by @gordnhoo and fixed with @saghul advice, on my Debian 12 with Prosody 0.12.3-1 I also had another error:

> modulemanager   error   Error initializing module 'jitsi_permissions' on 'breakout.jitsi.coossacademy.org': /usr/lib/prosody/util/startup.lua:203: module 'prosody.core.modulemanager' not found
>      no field package.preload['prosody.core.modulemanager']
>      no file '/usr/lib/prosody/prosody/core/modulemanager.lua'
>      no file '/usr/local/share/lua/5.4/prosody/core/modulemanager.lua'
>      no file '/usr/local/share/lua/5.4/prosody/core/modulemanager/init.lua'
>      ....

I fixed it this way:
```
mkdir -p /usr/lib/prosody/prosody/core/
ln -s /usr/lib/prosody/core/modulemanager.lua /usr/lib/prosody/prosody/core/
```
Maybe is there a better way to fix that?

**Comment by damencho** [comment]
@enribar what if you delete this line: https://github.com/jitsi/jitsi-meet/blob/0f5412715aafc97eeabd9a772936065dcf6a6d6f/resources/prosody-plugins/mod_jitsi_permissions.lua#L4

**Comment by photoninger** [comment]
I got the same error as @enribar after upgrading from jitsi-meet-2.0.10133-1 to jitsi-meet-2.0.10169-1 on Debian-12 and prosody-0.12.3-1.

Deleting the line as suggested by @damencho resolves the error and prosody starts again and jitsi is running again.

**Comment by damencho** [comment]
👍 we will update stable soon with fixes.

**Comment by damencho** [comment]
Yes it can, when we merge the change and have it released and then just updating will fix it.
Sorry for the inconvenience. A. quick workaround is deleting this line.
