### ISSUE TITLE
flipping Background image permanently as it is mirrored across different meetings  

### ISSUE THREAD

**Issue by MahmoudSamy201** [jitsi/jitsi-meet#14914]
### What problem are you trying to solve?

I realize when I use background image which contains words in Meet , it had been mirrored for me but in the other participant it looked like normal , also I know if I use flip option , it will resolve the issue .

but my question is there any other option that can disable mirroring background image permanently across different meetings as flip option is not persistent when create meetings through API ?

### What solution would you like to see?

option that can disable mirroring background image permanently across different meetings or make flip option persistent when create meetings through API

**Comment by saghul** [comment]
If you are using the API then there is no need to persist the setting since you can override it when joining. I'd say this applies more to the general case of using the software without the API.

**Comment by MahmoudSamy201** [comment]
Oki , so how can I override flip option to solve mirroring issue permanently every time I create new meeting  ?
