### ISSUE TITLE
Native part of Reanimated doesn't seem to be initialized on Android

### ISSUE THREAD

**Issue by Holofox** [jitsi/jitsi-meet#14925]
### What happened?

Hello!

There was a need to add a [react-navigation/drawer](https://www.npmjs.com/package/@react-navigation/drawer) and connect the [react-native-reanimated](https://www.npmjs.com/package/react-native-reanimated) dependency. I'm currently using jitsi-meet with commit ce727d87a8072c0b9a1cb70c8a9186374e3702b1 (tried also the latest changes 1376f5909c1548d507d4d4b11a332a8a6a217613).

**package.json**
```
"@react-navigation/drawer": "6.7.1",
"react-native-reanimated": "3.14.0",
```

**babel.config.js**
```
module.exports = {
    presets: [ 'module:metro-react-native-babel-preset' ],
    env: {
        production: {
            plugins: [ 'react-native-paper/babel' ]
        }
    },
    plugins: [ 'optional-require', 'react-native-reanimated/plugin' ]
};
```

On **iOS** everything works great, but on **Android** there is a problem when going to the router with drawer:

```
ERROR  Error: [Reanimated] Native part of Reanimated doesn't seem to be initialized.
See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized for more details. 
```

**ConferenceDrawerNavigator.tsx**
```tsx
import {Dimensions} from "react-native";
import ChatWebView from "../../../../../chat/components/native/ChatWebView";
import {screen} from "../../../routes";
import Conference from "../../../../../conference/components/native/Conference";
import React from "react";
import {createDrawerNavigator} from "@react-navigation/drawer";

const ConferenceDrawer = createDrawerNavigator();

const ConferenceDrawerNavigator = () => {
    return (
        <ConferenceDrawer.Navigator
            screenOptions = {{
                headerShown: false,
                drawerPosition: 'right',
                drawerStyle: {
                    width: Dimensions.get('window').width,
                },
            }}
            drawerContent = { (props) => <ChatWebView { ...props } /> } >
            <ConferenceDrawer.Screen
                name = { screen.conference.main }
                component = { Conference } />
        </ConferenceDrawer.Navigator>
    )
}

export default ConferenceDrawerNavigator;
```

**ConferenceNavigationContainer.tsx**
```tsx
<ConferenceStack.Screen
    // This component changed to ConferenceDrawerNavigator from Conference
    component = { ConferenceDrawerNavigator }
    name = { screen.conference.main }
    options = { conferenceScreenOptions } />
```

I'm new to React Native, can you please tell me what could be causing this? Is there anything that might be preventing this from happening in Jitsi right now? I tried different dependency versions, but it didn't solve the problem.

I understand that my problem does not apply to the stable version of Jitsi Meet, but I really need help to understand the problem. Any comments will help figure this out.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

9.2.2

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by Holofox** [comment]
With great difficulty, but I solved the problem. To do this, we had to implement the following changes:

**android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java**:
```java
// ...
    static List<ReactPackage> getReactNativePackages() {
        List<ReactPackage> packages
            = new ArrayList<>(Arrays.asList(
            // ...
            new com.swmansion.reanimated.ReanimatedPackage() {
                @Override
                public ReactInstanceManager getReactInstanceManager(ReactApplicationContext reactContext) {
                    return ReactInstanceManagerHolder.getReactInstanceManager();
                }
            },
            // ...
            ));
// ...
```

**android/sdk/build.gradle**:
```gradle
dependencies {
    // ...
    implementation project(':react-native-reanimated')

    testImplementation 'junit:junit:4.12'
}
```


**android/build.gradle**:
```gradle
allprojects {
// ...
    project.ext.react = [
        enableHermes: false,
    ]
// ...
}
```

**android/gradle.properties**:
```properties
// ...
hermesEnabled=false
```

**android/settings.gradle**:
```gradle
// ...
include ':react-native-reanimated'
project(':react-native-reanimated').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/android')
```

FYI @saghul

**Comment by saghul** [comment]
Great to hear!
