### ISSUE TITLE
Hebrew typos

### ISSUE THREAD

**Issue by carmeltsadok** [jitsi/jitsi-meet#14927]
### What happened?

Hi :)
In `lang/main-he.json` there are a couple of typos.
1. `notify.connectedOneMember` - should be `{{name}} הצטרף למפגש` instead of `{{name}} הצטרף למפדש`.
2. `addPeople.noResults` - should be `לא נמצאו תוצאות מתאימות` instead of `לא נמצאו תואצות מתאימות`.
3. `chat.fieldPlaceHolder` - should be `הקלד הודעתך כאן` instead of `הקלד הודעתך כאו`.

Thank you !!

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

sdk

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Are you up for sending a PR? You can edit the correspondig file in lang/

**Comment by pradyutf** [comment]
Hi @saghul 
As suggested, I have edited the corresponding file in lang/main-he.json and will be raising a PR with the fixes.

As I am new to the Jitsi project, I would love to start contributing by addressing this issue. Could you please assign it to me so I can proceed with the PR?

Thank you!
