### ISSUE TITLE
How can I improve video quality

### ISSUE THREAD

**Issue by DaiYuanchuan** [jitsi/jitsi-meet#14922]
### What happened?

We have an intranet deployment, and our intranet has a gigabit bandwidth.
We mainly use screen sharing, and not many people use it.
So I want to know what configuration settings can be modified to provide video quality while sacrificing some bandwidth to improve video quality?

I use the web side, docker deployment
Latest version

Can you give me a sample or demo?

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Latest version

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
What settings (config.js) are you currently using?

**Comment by DaiYuanchuan** [comment]
> What settings (config.js) are you currently using?

I haven't changed anything. I'm using the default Settings, okay

**Comment by saghul** [comment]
Did you deploy Docker or our Debian setup? What versions of the images / packages did you install?

**Comment by DaiYuanchuan** [comment]
> Did you deploy Docker or our Debian setup? What versions of the images / packages did you install?

I refer to the documentation and use docker deployment。

wget $(curl -s https://api.github.com/repos/jitsi/docker-jitsi-meet/releases/latest | grep 'zip' | cut -d\" -f4)
docker compose up -d

**Comment by DaiYuanchuan** [comment]
jitsi-docker-jitsi-meet-5a5b8f9-web-1
jitsi-docker-jitsi-meet-5a5b8f9-jvb-1
jitsi-docker-jitsi-meet-5a5b8f9-jicofo-1
jitsi-docker-jitsi-meet-5a5b8f9-prosody-1
