### ISSUE TITLE
[RNSDK][IOS] Hitting `failure: socket file missing` error in SocketConnection when screen sharing 

### ISSUE THREAD

**Issue by rcidt** [jitsi/jitsi-meet#14928]
### What happened?

I am running the latest Jitsi RN SDK on iOS against a custom Jitsi server also running the latest version.

I have implemented the Screen Sharing instructions for iOS found in the Jitsi docs. I have quadruple-checked that the implementation is correct and that the app groups, minimum deployment version, bundle identifiers, etc are all matching on both the host app and the extension.

When I start a screen sharing session, nothing happens in the conference. No samples are uploaded, the socket connection is never established. I pinpointed the issue to the error thrown in the SocketConnection class: `failure: socket file is missing`.

This leads me to think that the server side (in this case, the host app acts as the server) is not creating the socket file for some reason.

Any ideas on what I can do to continue debugging this further?

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

rnsdk 2.2.1

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
The RN SDK does not currently wire the screen-sharing support at all, so even if you do all things right, there are a couple of things missing on the SDK side.

**Comment by rcidt** [comment]
@saghul so iOS screen sharing is not officially supported for RN SDK? If so, are there any plans on supporting it?

**Comment by saghul** [comment]
We have plans for it yeah!

**Comment by rcidt** [comment]
@saghul I took a stab at it here https://github.com/jitsi/jitsi-meet/pull/14929

**Comment by saghul** [comment]
Awesome!
