### ISSUE TITLE
App crashed on ios - [track.kind isEqualToString:@"audio"]

### ISSUE THREAD

**Issue by mspvirajpatel** [jitsi/jitsi-meet#14921]
### What happened?

RN - 0.74

I have integrated the latest SDK but I am facing an issue after the build success.

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/6d77e32a-08d0-47aa-8e65-14a670c4019b">

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

0.74

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
What SDK version did you integrate? Did you make any changes to the code?
