### ISSUE TITLE
[JITSI] Video and voice issues and unexpected ejection from Jitsi meeting sessions

### ISSUE THREAD

**Issue by sirinebenabbes** [jitsi/jitsi-meet#14924]
### What happened?

When initiating a video call with two or more users almost no one hears the other participants, nor see the shared cameras, they can only see the jitsi profile photo while the cameras weren't turned off.

Also, sometimes users find themselves kicked out of the call without any action made from the moderator, and when they rejoin the same behavior reproduces again. This makes the use of Jitsi so frustrating...

I attach three har files of three users who experienced the camera and microphone issue, the files were saved by selecting the option "All" in network tab of  their firefox browser.

The same test with the same machines and browsers is done using other visio tools (ZOOM or GOTOMEETING) and we got no issue. So clearly this issue is absolutely does not come from the workstation or the Jitsi settings and users confirm that the settings are ok from their side.

Also, switching the device in the device selection popup doesn't solve the voice issue.

Can you please share from where such hearing and video issues can come from ? 

[har files.zip](https://github.com/user-attachments/files/16264762/har.files.zip)

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [X] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

128.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Is this your own deployment? Are you able to have a 3 participant conference with and video at all?

**Comment by sirinebenabbes** [comment]
Yes, it's self-deployed.
Yes we're able to join the Jitsi conferences with more than two users, yet some of them are facing the issues I described earlier.

**Comment by saghul** [comment]
What versions of the software did you deploy?

**Comment by sirinebenabbes** [comment]
jitsi-web:stable-8719

**Comment by saghul** [comment]
That release is a bit more than a year old, I'd suggest you update to the latest.

**Comment by sirinebenabbes** [comment]
I'm afraid we can't currently change it due to compatibility with our own product.
Is there any other recommandation ?

**Comment by saghul** [comment]
Alas no. You might be suffering a problem due to a change in Firefox for example, that requires a new JVB.

**Comment by sirinebenabbes** [comment]
Thanks for your reply @saghul !

According to our tests, it's not only related to Firefox, it's also reproduced on other browsers, it's even reproduced on mobile devices using our application where no browser is used; the users are directed instantly to the Jitsi session.

And if it's not related to the firefox browser itself, the JVB should be changed anyway? 
If yes, what's the right JVB should we use instead?

**Comment by saghul** [comment]
That was just an example. There are many things that have happens in a year.

**Comment by sirinebenabbes** [comment]
Taking into consideration our compatibility point, is there any further information that I can share with you to diagnostic the source of such issues ?

**Comment by saghul** [comment]
The problem is that being 1 year behind in updates is not something you can fix with a config change. We know the JVB fixes an issue with Firefox but you can't update the JVB without updating Jicofo and prosody and lib-jitsi-meet, since they are all working in tandem.

Sorry about this.
