### ISSUE TITLE
PIP mode for iOS

### ISSUE THREAD

**Issue by mssvijaykumar** [jitsi/jitsi-meet#14930]
### What happened?

I want to integrate pip functionality for my app. I'm using jitsi latest version which is 9457. I want to integrate pip by using react-native. My react-native version is "react-native": "0.72.9". Please provide block of code for this functionality.

Version of jitsi meet:- https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_9457

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

9457

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
PiP is only supported within the app views, and not at all suppported on the RN SDK, sorry.
