### ISSUE TITLE
How to lock a room? 

### ISSUE THREAD

**Issue by Morse6690** [jitsi/jitsi-meet#14933]
I'm new to jitsi, but I have searched everywhere I can but can't seem to find some basic information, how do I lock a meeting room?

According to the following link... 
https://jitsi.support/wiki/secure-jitsi-meetings-guide

"Lock the Room: Once all participants have joined, lock the room. This prevents unauthorized access during the session." 

According to this link...
https://jitsi.support/how-to/secure-jitsi-meeting-room-guide

" Lock the Meeting Room
Once all invited participants have joined the meeting, consider locking the meeting room to prevent additional attendees from joining. Locking the meeting room ensures that only approved participants can access the discussion and minimizes the risk of unauthorized entry."

What are the specific steps to locking a room?
Can this be done on ios?

**Comment by saghul** [comment]
Hey there!

You can lock a room by enabling lobby or setting a password in the Security Options dialog in the "..." menu:

![image](https://github.com/user-attachments/assets/4959dbbe-ac71-4222-ba5f-4ce2dc1d4a7e)

![image](https://github.com/user-attachments/assets/5e48c7cc-919e-4681-88ad-81c59330b362)

**Comment by Morse6690** [comment]
Thanks. I was aware of those two features.
The link I sent mentions the security steps including "strong password", "waiting room" and "Lock the Meeting Room" as 3 seperate steps.
Can I ask why this is the case?
Is the error with the app meaning the lock feature no longer exists or is the error with the  support page? Seemingly both cannot be correct.

**Comment by saghul** [comment]
We are not behind that web page.

**Comment by Morse6690** [comment]
No worries. Thanks
