### ISSUE TITLE
 Room crashes when connecting  client on jitsi room  

### ISSUE THREAD

**Issue by mohammadforghani99** [jitsi/jitsi-meet#14942]
### What happened?

 Room crashes when  client2 join on jitsi room  
 and on mobile app i cant connect to my jitsi server 

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Check browser js console logs, what errors do you see?
The mobile client to connect the deployment needs to use valid certificates, is this the case?
