### ISSUE TITLE
Ability to make all participants join as Visitors

### ISSUE THREAD

**Issue by 0WN463** [jitsi/jitsi-meet#14969]
### What problem are you trying to solve?

We have a conference where we only want the speaker/host to be seen, and the participants to be always hidden from each other (at least such that they are muted and their video is **forced** to be off).

I think this is what the Visitor concept is for, and moving the participants to Visitor does fit our use case rather well.

But is it possible for people to be forced to join as visitors instead of having the host move them after they join?

### What solution would you like to see?

Ability to set a flag in the moderator setting that forces everyone to be visitors (or forces to join as visitors).

### Is there an alternative?

Or maybe it could be a special invite link that joins as visitor for the person clicking the link

**Comment by damencho** [comment]
You can control visitors easily with jwt by adding `role: 'visitor'` in the user context part of the token.
