### ISSUE TITLE
I can't kickout the user after configured with the JWT

### ISSUE THREAD

**Issue by krishnakingdom** [jitsi/jitsi-meet#14967]
### What happened?

I configured my jitsimeet with JWT and working fine with all application. But when I tried to kickout the user it is not working but it was working before configured the JWT. So please suggest me the solution for this.

And I found a prosody plugin will this useful any way to perform the kick out function after configuring the JWT, but I enabled it still not working. May be some other configuration is needed for the plugin enabling could you please suggest me on this.

![image](https://github.com/user-attachments/assets/10832fc5-b728-4c8d-a601-451754da0b59)
![jitsi issue-github](https://github.com/user-attachments/assets/e76224af-ae12-4c63-bbce-e1e68857475e)
![image](https://github.com/user-attachments/assets/941a284a-b06f-4893-a850-6571a515f657)
![image](https://github.com/user-attachments/assets/8fb4b3ae-ea2e-4b7e-b8b5-c7d9ac241376)

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [X] Custom app using a mobile SDK

### Browser / app / sdk version

all versions

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
What is the error you see when this happens?

The module kick_jigasi is not relevant in this context. 

Which prosody version are you using?

Do you have allowners module enabled?

**Comment by krishnakingdom** [comment]
Please excuse for the delay response.

In the browser debug console, I am not getting any error but in the prosody error log I found this error.

Prosody Error :

Aug 12 10:17:40 portmanager     error   Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
Aug 12 10:17:40 portmanager     error   Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
Aug 12 10:17:40 video.aauti.com:token_verification      error   'app_id' must not be empty

**This is my prosody version**

![image](https://github.com/user-attachments/assets/8fff6dcc-bf40-4789-b4d2-6e6ac05df3f0)


Allowners module is enabled in the prosody configuration file, but still it is giving the same issue. I am attaching you the details for your reference.


**this is the path : /etc/prosody/conf.d/video.aauti.com.cfg.lua**     

  ssl = {
        key = "/etc/prosody/certs/video.aauti.com.key";
        certificate = "/etc/prosody/certs/video.aauti.com.crt";
    }
    av_moderation_component = "avmoderation.video.aauti.com"
    speakerstats_component = "speakerstats.video.aauti.com"
    conference_duration_component = "conferenceduration.video.aauti.com"
    end_conference_component = "endconference.video.aauti.com"
    -- we need bosh
    modules_enabled = {
        "bosh";
        "pubsub";
        "ping"; -- Enable mod_ping
        "speakerstats";
        "external_services";
        "conference_duration";
        "end_conference";
        "muc_lobby_rooms";
        "muc_breakout_rooms";
        "av_moderation";
        "room_metadata";
        "token_verification";
       "http";
       "muc_allowners";

    }
    c2s_require_encryption = false
    lobby_muc = "lobby.video.aauti.com"
    breakout_rooms_muc = "breakout.video.aauti.com"
    room_metadata_component = "metadata.video.aauti.com"
    main_muc = "conference.video.aauti.com"
    --muc_lobby_whitelist = { "recorder.video.aauti.com" } -- Here we can whitelist jibri to enter lobby enabled rooms
    
Component "conference.video.aauti.com" "muc"
    restrict_room_creation = true
    storage = "memory"
    modules_enabled = {
        "muc_hide_all";
        "muc_meeting_id";
        "muc_domain_mapper";
        "polls";
        "token_verification";
        "muc_rate_limit";
        "muc_password_whitelist";
        "token_moderation";
        "jibri_autostart";
        "token_verification";
         "http";
         "muc_allowners";
          }
    admins = { "focus@auth.video.aauti.com", "recorder@recorder.video.aauti.com" }
    muc_password_whitelist = {
        "focus@auth.video.aauti.com"

    }

**Please verify this and suggest me the solution.**

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/muc_owner_allow_kick.patch
Apply this patch to prosody and restart prosody.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by krishnakingdom** [comment]
@damencho  l did the same thing as you suggested but still my issue is not solved, even I allowed the allowners modules also as you suggested in the above thread. 

**This command i used to patch**
sudo patch -d /usr/lib/prosody/modules/muc -p0 < /usr/share/jitsi-meet/prosody-plugins/muc_owner_allow_kick.patch

I am not getting any error also, in browser debug console and in error log also, could you please help me on this , should I need to enable any other module to solve this issue.


![image](https://github.com/user-attachments/assets/83defa6c-0557-4d8c-b08c-f41643bed40a)
![image](https://github.com/user-attachments/assets/e0f66a87-8dc8-4b9b-9e86-681688fc8893)
![image](https://github.com/user-attachments/assets/2bfe5712-6f7d-4e80-b1e0-d74f6ef6f77a)
![image](https://github.com/user-attachments/assets/7b360551-7500-4c7c-be2c-7835d7d176e1)
![image](https://github.com/user-attachments/assets/5936ef3a-dbd2-44c1-b501-0849c5937e4a)
![image](https://github.com/user-attachments/assets/90c4d26a-c766-43d4-a82c-90bf425c3f43)
![image](https://github.com/user-attachments/assets/607b0ea5-dd8d-4fe1-9cb1-08239744f812)
![image](https://github.com/user-attachments/assets/9085aba1-0f46-4c46-917b-f44133572b9f)
![image](https://github.com/user-attachments/assets/6944c9a7-454f-41d3-b484-d437dea080cf)

**Comment by damencho** [comment]
Upload here the js console log from the participant trying to kick.

**Comment by krishnakingdom** [comment]
@damencho  
I am uploading the log files here which I collected from the Browser console log 
The moderator log is where i use the kick out button and user log is which user I am trying to kick out that user console log.

[video.aauti.com-user log-kickout.log](https://github.com/user-attachments/files/16582132/video.aauti.com-user.log-kickout.log)
[video.aauti.com-moderator log.log](https://github.com/user-attachments/files/16582133/video.aauti.com-moderator.log.log)

**Comment by damencho** [comment]
No logs in prosody logs?

**Comment by krishnakingdom** [comment]
@damencho 
I found these logs in prosody , jicofo I am attaching here for your reference. Please verify once.

[prosody-err.txt](https://github.com/user-attachments/files/16595024/prosody-err.txt)
[prosody-log.txt](https://github.com/user-attachments/files/16595025/prosody-log.txt)
[jicofo-log.txt](https://github.com/user-attachments/files/16595026/jicofo-log.txt)

**Comment by damencho** [comment]
Reproduce and execute this in the js console
APP.conference.saveLogs()
Attach the result file

**Comment by krishnakingdom** [comment]
@damencho 
I am attaching the console logs here for your reference.
[meetlog-user.json](https://github.com/user-attachments/files/16608166/meetlog-user.json)
[meetlog-moderator.json](https://github.com/user-attachments/files/16608168/meetlog-moderator.json)

**Comment by damencho** [comment]
There is no attempt to kick participant in the signaling of the moderator logs.

**Comment by krishnakingdom** [comment]
@damencho 
I have press the kickout button but why it is not recording I don't know, I am sending you the logs and video again for your reference.

[meetlog-user-neww.json](https://github.com/user-attachments/files/16608647/meetlog-user-neww.json)
[screen-capture (1).webm](https://github.com/user-attachments/assets/a35b26f0-85bf-4180-b9be-dbab02814e3b)
[meetlog-moderator-neww.json](https://github.com/user-attachments/files/16608649/meetlog-moderator-neww.json)

**Comment by damencho** [comment]
Is this latest version of jitsi-meet with no modifications? 
It is obvious that kick button is not working.

**Comment by krishnakingdom** [comment]
@damencho 

This is the present installed version which I am using, please check once.


![image](https://github.com/user-attachments/assets/94a798a8-240b-4e13-87ae-95be1722e64b)

**Comment by damencho** [comment]
This is from Dec 2023. Can you update to latest and try with it?

**Comment by krishnakingdom** [comment]
@damencho 

I am updated the jitsi meet and attaching the versions for your reference  and now also same situation I think after I enabling the jwt kick out is not working , before the jwt it was working actually.


![image](https://github.com/user-attachments/assets/2af5258c-5bf4-448a-a9c4-7ab78596ec40)
Please find the below console logs after the upgrade.
[meetlog.json](https://github.com/user-attachments/files/16613802/meetlog.json)

**Comment by damencho** [comment]
Do you still do not see:
<img width="474" alt="image" src="https://github.com/user-attachments/assets/52849686-0085-4c3f-8686-8a2780485a46">
?

**Comment by krishnakingdom** [comment]
@damencho 

No, I am not getting this popup, it was working before on without JWT.
I think there is some configuration mistake or issue with jwt ?
Other than configuration and jwt module enabling we didn't modify anything on Jitsi meet.

Do I need to check any other configuration or any files or something ?

**Comment by damencho** [comment]
I suspect it maybe a bug in the UI. You should test the latest versions.

**Comment by krishnakingdom** [comment]
@damencho 

it is working now, after updated the new version. Now I can be able to kickout the user.

Thank you for the support
