### ISSUE TITLE
Not able to Pin more than one user 

### ISSUE THREAD

**Issue by Bhoomi-tgs** [jitsi/jitsi-meet#14963]
### What happened?

I am not able to Pinning more than one user in my meeting screen

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

"@jitsi/react-native-sdk": "^2.2.1",

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by Aryankarma** [comment]
Hello @Bhoomi-tgs can i look upon this issue?

**Comment by Bhoomi-tgs** [comment]
Yes please, It will help for me
