### ISSUE TITLE
Authentication dialog is missing autocomplete attributes

### ISSUE THREAD

**Issue by otbutz** [jitsi/jitsi-meet#14974]
### What happened?

The login mask should use the HTML `autocomplete` attribute for its input fields to assist password managers:

![grafik](https://github.com/user-attachments/assets/e4de1b18-1bc1-43e8-8bcc-d96fa76ba3b8)

Username:

```html
autocomplete="username"
```

Password:

```html
autocomplete="current-password"
```

see https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands/

### Platform

- [ ] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Firefox 128.0.3

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Sounds reasonable! Would you be open to sending a PR?
