### ISSUE TITLE
 Help Needed: XMPP Server Connection Issues with Jitsi Meet on Kubernetes

### ISSUE THREAD

**Issue by TGC-PratikNanavare** [jitsi/jitsi-meet#14971]
### What happened?

Hello community,

I have set up a Kubernetes deployment for Jitsi Meet using the provided YAML file. However, I am facing issues with the XMPP server connection. The components (JVB, Jibri, Jicofo) are not connecting to the XMPP server, and I am seeing the following errors:

**Colibri Connection Error in the console.
Video Impaired Error on the screen.**
Here are my questions:

How can I create a reliable XMPP server on Kubernetes to connect with all Jitsi components (JVB, Jibri, Jicofo)?
What might be causing the Colibri connection error and the Video Impaired error, and how can I resolve them?
Any guidance or help would be greatly appreciated. Thank you!

I have check this issue [https://community.jitsi.org/t/jvb-colibri-ws-connecting-to-wrong-domain/112284](url)
and also check git issue but it's not help me.

I have created a Kubernetes deployment for Jitsi Meet with the following YAML file.

here I have attached that files

[deployment.txt](https://github.com/user-attachments/files/16494092/deployment.txt)
[env-config.txt](https://github.com/user-attachments/files/16494093/env-config.txt)
[jvb.txt](https://github.com/user-attachments/files/16494095/jvb.txt)
[service.txt](https://github.com/user-attachments/files/16494096/service.txt)

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

latest

### Relevant log output

```shell
BridgeChannel.js:91 WebSocket connection to 'wss://pratik.meet.com/colibri-ws/10.244.0.18/7b6728345da6b73d/30f6e9ee?pwd=74b5gfbi3tfp2elgek08len1uk' failed: Error during WebSocket handshake: Unexpected response code: 200
BridgeChannel.js:393 2024-08-05T09:59:05.865Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:393 2024-08-05T09:59:07.440Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://pratik.meet.com/colibri-ws/10.244.0.18/7b6728345da6b73d/30f6e9ee?pwd=3frbdj0orpco3rc6blrlf2ssfo' failed: Error during WebSocket handshake: Unexpected response code: 200
BridgeChannel.js:393 2024-08-05T09:59:08.171Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://pratik.meet.com/colibri-ws/10.244.0.18/7b6728345da6b73d/30f6e9ee?pwd=3frbdj0orpco3rc6blrlf2ssfo' failed: Error during WebSocket handshake: Unexpected response code: 200
BridgeChannel.js:393 2024-08-05T09:59:14.874Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
BridgeChannel.js:91 WebSocket connection to 'wss://pratik.meet.com/colibri-ws/10.244.0.18/7b6728345da6b73d/30f6e9ee?pwd=502hnaeab04plaiuj4ar7hv1sj' failed: Error during WebSocket handshake: Unexpected response code: 200
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Our k8s support is community maintained. Please ask in our community forum rather than opening an issue here.

**Comment by TGC-PratikNanavare** [comment]
> Our k8s support is community maintained. Please ask in our community forum rather than opening an issue here.

Sure!.
