### ISSUE TITLE
Black screen instead of share screen. 

### ISSUE THREAD

**Issue by kasAlx** [jitsi/jitsi-meet#14984]
### What happened?

When logging in via web ios safari, the sharing screen is not visible. Instead of broadcasting, there is a black screen. If another user connects from the iOS web, the broadcast will appear.
![screen black1](https://github.com/user-attachments/assets/7d59d648-a9d3-4ac0-975a-d55a91a00096)

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [X] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

17.5.1

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
@kasAlx Can you please some more information about this issue?

1. Is this issue reproducible on meet.jit.si?
2. If so, what are the steps to reproduce? Is there a certain order of events for this to reproduce?
3. Is this a regression for jitsi-meet client or for the Safari browser?

I am not able to reproduce this on meet.jit.si using iOS 17.4.1
