### ISSUE TITLE
Excalidraw Error

### ISSUE THREAD

**Issue by robbie1-uk** [jitsi/jitsi-meet#15007]
I'm using Excalidraw for the whiteboard on the server where I run Jitsi. I've set up the necessary redirections, and Excalidraw opens, but when a second person joins the meeting, they receive a "Couldn't decrypt data" error. I've reviewed the related issues and tried the suggested solutions, but the problem still persists. Can you help me with this?

https://github.com/jitsi/excalidraw-backend/tree/master -> This is the repo I use

![image (1)](https://github.com/user-attachments/assets/30a9cf36-f5b9-46a7-8124-7af9fd0e9179)
<img width="452" alt="image" src="https://github.com/user-attachments/assets/d033c82c-943f-446b-ba91-bbe32914159d">

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [X] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome, Safari, Opera -> latest version

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Look at the request URL in the network tab on the browser console. Does it have the room and key parameters?

**Comment by EmreGundogdu** [comment]
We had the same issue. Are you trying to open whiteboard feature with a non-moderator participant?

**Comment by robbie1-uk** [comment]
No, these parameters do not appear ://  There are only the following errors.


<img width="1385" alt="Ekran Resmi 2024-08-15 12 11 10" src="https://github.com/user-attachments/assets/90e7f644-3b4f-4f3d-9066-f5ef3f438e5d">

**Comment by saghul** [comment]
Ah, there we go. You are not a moderator so you shouldn't be able to open the whiteboard at all, until a moderator does.

What version of the backend components are you running?

**Comment by EmreGundogdu** [comment]
Yeah thats right we were trying to open whiteboard by non-moderator participant. Could it gonna be able to open whiteboard for all participants in the next updates?

**Comment by saghul** [comment]
No, the feature is designed so a moderator needs to start it.

**Comment by EmreGundogdu** [comment]
Thanks for your feedback, that was very usefull and helpfull. We couldn't understood the reason. Thank you for your help! :)

**Comment by SH20RAJ** [comment]
> No, the feature is designed so a moderator needs to start it.

🚀 Need a better way to visualize ideas & collaborate? Check out SketchFlow – an AI-powered whiteboard for brainstorming, planning, and designing with ease! 🎨🤖 With real-time collaboration, infinite canvas, and smart object recognition, it's perfect for developers, designers, and teams. And it’s free! Try it now: https://sketchflow.space/ 🚀 #SketchFlow #AIWhiteboard
