### ISSUE TITLE
Option : "Allow attendees to unmute themselves"  has no effect.

### ISSUE THREAD

**Issue by Saidhoussem** [jitsi/jitsi-meet#15016]
### What happened?

1. User A and User B are in a meeting 
2. User A clicks on participants button and Mute all participants.
**Expected result:**

1. If "Allow attendees to unmute themselves" is **CHECKED** ==> User B **can** unmute himself.
2. If "Allow attendees to unmute themselves" is **UNCHECKED** ==> User B **cannot** unmute himself.

**Actual results :** 

"Allow attendees to unmute themselves" has no effect, User B can unmute himself all the time.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [x] Custom app using a mobile SDK

### Browser / app / sdk version

SDK : 8.6.1, Jitsi APP 24.3.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

i don't test with : meet.jit.si
But i do testes with the SDK and the application android "org.jitsi.meet"

**Comment by saghul** [comment]
Please try to reprooduce this on meet.jit.si. It requires the av moderation modules to be configured on the server.

**Comment by AlaaAbbass** [comment]
Hi @saghul  , I'm collaborating with @Saidhoussem on this issue. After investigation, it appears that the problem is reproducible in the webchat.

**Comment by saghul** [comment]
What do you mean by webchat?

**Comment by AlaaAbbass** [comment]
@saghul it means meet.jit.si

**Comment by AlaaAbbass** [comment]
@saghul 
![Screenshot 2024-08-19 at 10 52 58 AM](https://github.com/user-attachments/assets/8a3358ce-84c5-4728-b77a-a92808c5507f)

**Comment by saghul** [comment]
That is not our application.

**Comment by AlaaAbbass** [comment]
@saghul Hi Saghul,

The previous screenshot shows the version of our web application. As you know, this version is integrated with Jitsi. I can confirm that the bug occurs with this version of our web application. Additionally, I tested the same behavior directly on Jitsi and confirmed that the bug is also present there (https://meet.jit.si/) .

FYI @Saidhoussem

**Comment by saghul** [comment]
meet.jit.si is a tad different because every participant is a moderator, so that's why they can unmute themselves.

@damencho what is the expeced behavior here?

**Comment by damencho** [comment]
So when AV moderation is on, when a participant want to talk or turn on camera the request is sent to all moderators for approval. When a participant is a moderator there is no point of asking for permission. Moderators can unmute themselves without asking for permission.

**Comment by saghul** [comment]
So then this is working as intended.

**Comment by AlaaAbbass** [comment]
Hi @saghul @damencho @Saidhoussem ,

I’d like to clarify that when the "Allow attendees to unmute themselves" button is deactivated, users are unable to unmute themselves. From the user's perspective, the microphone should appear as disabled. In the current solution users can unmute themselves even the button is disabled.
![Screenshot_20240819_144955_Team on the Run](https://github.com/user-attachments/assets/e0bd91fa-0ea1-4a9f-b876-1cd13a54709f)

**Comment by damencho** [comment]
I just tested this on meet.jit.si and it works as expected:
<img width="722" alt="Screenshot 2024-08-19 at 9 04 01 AM" src="https://github.com/user-attachments/assets/6c936838-5110-436e-89e8-bcd94f5a360a">
<img width="579" alt="Screenshot 2024-08-19 at 9 04 46 AM" src="https://github.com/user-attachments/assets/bddf962d-4bce-41fc-af2a-a47178062a32">

You need to use moderated.jitsi.net to test this, as there are guests and moderators there.

**Comment by AlaaAbbass** [comment]
Hi, I’ve submitted the change request [SMARTMS-53626](https://jira.streamwide.com/browse/SMARTMS-53626) and will keep you updated on the progress.
Thank's for your collaboration @Saidhoussem  @saghul @damencho

**Comment by saghul** [comment]
This got me thinking @damencho. Should the room broadcast if all-owners is set in disco-info and hide the controls in that case?

**Comment by damencho** [comment]
Well we have all owners on meet, but when using moderated tenant those are valid.

**Comment by saghul** [comment]
Good point, nevermind! 😅
