### ISSUE TITLE
Collaborative Editor like in MiroTalk

### ISSUE THREAD

**Issue by webRTCv1** [jitsi/jitsi-meet#15010]
### What problem are you trying to solve?

1. **Real-Time Collaboration**: Multiple users can work on the same document simultaneously, seeing each other’s changes in real-time. This enhances teamwork and allows for instant feedback.

2. **Improved Productivity**: Everyone working in one place and on the same version of the document, the process is streamlined, reducing the need for back-and-forth emails and version control issues.

3. **Enhanced Communication**: With the chat or comment features, allowing team members to discuss changes and provide feedback without leaving the document.

4. **Version Control**: Changes are tracked, and previous versions are often saved, so you can revert to earlier drafts if needed. This helps in managing revisions and understanding the evolution of the document.

5. **Accessibility**: Documents can be accessed from anywhere with an internet connection, which is ideal for remote teams or individuals working across different locations.

6. **Consistency**: Ensure that everyone is working on the same version of a document, reducing inconsistencies that can arise from multiple copies and edits.

7. **Efficiency**: By integrating tools for tracking changes, commenting, and task assignments, collaborative editors can streamline the editing and review process, making it more efficient.

8. **Cross-Platform Compatibility**: Work across various devices and operating systems, allowing for flexibility in how and where documents are accessed and edited.

9. **Increased Engagement**: The ability to work together in real-time can foster a more engaged and collaborative environment, encouraging active participation from all team members.

10. **Enhanced Accuracy**: Real-time updates and shared access help to minimize errors and ensure that all team members are working with the most current information.

### What solution would you like to see?

Collaborative editor like in MiroTalk (our favorite solution together with Jitsi)

<img width="864" alt="mirotalk_collaborative_editor" src="https://github.com/user-attachments/assets/9148cac7-605c-4c7d-8c07-76b3daab7139">

### Is there an alternative?

I recently noticed that **[MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu)** has introduced an exciting new feature called the **collaborative editor**. It got me thinking wouldn't it be great to see something similar in Jitsi? It seems like a lot of major companies have been incorporating features that were originally unique to MiroTalk! :)

**Comment by saghul** [comment]
We support interating with the Etherpad collaboorative editor. You can deploy it yourself together with the rest of the stack, we currently don't provide a public instance.

**Comment by webRTCv1** [comment]
> You can deploy it yourself together with the rest of the stack

Can you let us know if it's possible to have a collaborative editor in Jitsi similar to the one in MiroTalk? 

![mirotalksfu-collaborative-editor](https://github.com/user-attachments/assets/f68eada8-8b1f-4599-88cf-c8c5d3cccc1a)

If so, could you please explain how we can set this up, or provide information on where we can find documentation?

**Comment by saghul** [comment]
The simplest way is with Docker. Take a look here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#shared-document-editing-using-etherpad

**Comment by webRTCv1** [comment]
Thank you. Could you please clarify whether the intention is to **continue relying on third-party solutions for this functionality**, rather than integrating it directly as a customizable feature within Jitsi?

**Comment by saghul** [comment]
Yes, our intention, currently, is to continue down this path.
