### ISSUE TITLE
Unable to have only one moderator when using external API ?

### ISSUE THREAD

**Issue by ggustin93** [jitsi/jitsi-meet#1501]
Hello,

I am developping a platform where Alzheimer patients can meet and discuss, under the supervision of a "moderator". To that end, I'm trying to embed Jitsi Meet with the external API provided (see https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md).
However,  I can't figure out how to not grant "moderator" rights to a specific user. Every user is automatically moderator, no matter when he joins the room.
Is there another command that the following one : `var api = new JitsiMeetExternalAPI(domain, room, width, height, htmlElement);` allowing the user to join (and not "create"/be moderator) a certain conference ?

Thank you

**Comment by peillis** [comment]
It would be great to have a command in the API to grant moderator rights. I'm with a pretty similar problem.

**Comment by k1000** [comment]
Similar here!

**Comment by trda** [comment]
I have the same problem.

**Comment by ztl8702** [comment]
> Every user is automatically moderator 

This behavior is decided by the Prosody server. The solution is to remove `muc_allowners` from `prosody.cfg` on the server (if you are running your own instance).

Seem related: https://github.com/jitsi/jitsi-meet/issues/2106#issuecomment-339547637

**Comment by saghul** [comment]
@alonelion1987 After you removed the plugin, have you restarted prosody? Also, when you use the external API, you do load and point it to your own domain, right?

**Comment by alonelion1987** [comment]
> After you removed the plugin, have you restarted prosody

Of course. Even more than that, I restart jicofo and jitsi-videobridge, although perhaps this is not necessarily.

> Also, when you use the external API, you do load and point it to your own domain, right

Yes, right!

One moment when the muc_allowners module is run is when I really connect it. But this happens for every participant in the room as if repeatedly (re-obtaining the rights of a moderator). And when I set the return of some other value in this module (muc_allowners), unlike "owner", the conference run incorrect.

**Comment by saghul** [comment]
Hum. Is every user authenticated using JWT? If so, how did you create the users in prosody?

**Comment by saghul** [comment]
I see. I discussed this with @damencho and your config looks ok, so we'll need to dig deeper. It may take us a bit of time to do so though.

**Comment by dustinphipps** [comment]
Has there been any progress on this? I'm experiencing the same issue. Thanks!

**Comment by dimm0** [comment]
Would love to have this fixed

**Comment by damencho** [comment]
Can you give us a link where this is happening so we can take a look?

**Comment by dimm0** [comment]
This is default behaviour (I don't have an instance running at the moment)
I did not see an option to make only one user a moderator. Does it exist?

**Comment by damencho** [comment]
The first one to join the conference is a moderator this is the default deployment. There is nothing to enable. Its jicofo that creates and joins as first and the room and that grants that to the first to join, so if your conference is working I don't see why this will not work, that's why I asked for a deployment where you reproduce it and there is no moderator in the conference.

**Comment by dimm0** [comment]
The proble is to make only one user a moderator. If he leaves, and then joins, he still has to be a moderator

**Comment by damencho** [comment]
The only way to do that is to enable authentication https://github.com/jitsi/jicofo#secure-domain. There will be host which is username/password authenticated user and guests cannot join till the host is available. The host will be modertor.

**Comment by Ruairi59** [comment]
> It would be great to have a command in the API to grant moderator rights. I'm with a pretty similar problem.





https://lnkr.fun/8318e0d
