### ISSUE TITLE
Camera is permanently disabled since last Android App Update to 24.3.0 (with changed video constraints on server) 

### ISSUE THREAD

**Issue by taimon** [jitsi/jitsi-meet#15027]
### What happened?

I'm running a private Jitsi server and starting from last week, one user is not able to use his camera at all anymore. (Camera button is permanently disabled)
The client uses the newest android app (24.3.0) on a Samsung Galaxy Tab A (1080p camera).

It turns out this is related to a configuration change I did on the server a couple of years back.
I modified the [default video constraints](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#constraints) to allow a max height of 1080.
The section is commented out in the default config, it looks like this by default:
```
constraints: {
    video: {
        height: {
            ideal: 720,
            max: 720,
            min: 240
        }
    }
}
``` 
I had changed the max value to 1080 and this seems to be causing the issue on the new android version. 
Just commenting this part out and restarting the server enables the camera again.
Maybe I didn't understand this config section correctly and there are no constraints by default or the documentation is incorrect. But apparently it was working fine for the client until last week.

Since I have a workaround, I don't really need a fix for this. Just wanted to let you guys know that the last update might have had some unintended side effects. (And maybe someone else has this problem too.)
I don't have direct access to the android client and cannot test development builds. (So someone else might need to replicate this.)

Thanks for developing and maintaining Jitsi Meet!

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

24.3.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

Jitsi Package Versions on the server:
```
jitsi-meet                         2.0.9646-1
jitsi-meet-prosody                 1.0.8091-1
jitsi-meet-web                     1.0.8091-1
jitsi-meet-web-config              1.0.8091-1
jitsi-videobridge2                 2.3-160-g97a1f15b-1
```

**Comment by saghul** [comment]
Thanks for the heads up! We'd need device logs to try and understand why falling back to a lower resolution is not working :-/

An important chance in 24.3.0 is that the mobile app now follows the server constraints, rather than ignoring them and doing 360p.

**Comment by taimon** [comment]
> We'd need device logs to try and understand why falling back to a lower resolution is not working :-/

Unfortunately, I won't be able to provide you with those, since I don't have direct access to the device. (At least not in the near future.)
Or is there a way to configure the client to dump those logs either to the server side or in any other way, so that either me or the user can somehow retrieve them?

I'm not familiar with developing on android at all, but I guess you would want to have the relevant "adb logcat" output.
I had a quick skim over the code and you probably want to see the messages from [lib-jitsi-meet RTCUtils](https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTCUtils.js), especially the ones from `_getUserMedia()` and `getConstraints()`, right?

If nobody else has this problem, I don't think debugging this is worth the effort.
So I'd suggest we wait for a while before diving deeper into this.

**Comment by saghul** [comment]
> Or is there a way to configure the client to dump those logs either to the server side or in any other way, so that either me or the user can somehow retrieve them?

Alas not the type of logs we'd need.



> I'm not familiar with developing on android at all, but I guess you would want to have the relevant "adb logcat" output.

That's right!



> I had a quick skim over the code and you probably want to see the messages from [lib-jitsi-meet RTCUtils](https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTCUtils.js), especially the ones from `_getUserMedia()` and `getConstraints()`, right?

Those would be useful too, but there is native logging that logcat would also contain.



> If nobody else has this problem, I don't think debugging this is worth the effort.
> So I'd suggest we wait for a while before diving deeper into this.

Makes sense!

**Comment by Foxdynamics** [comment]
Hi everyone,

I'm experiencing exactly the same issue described here. I've narrowed down the problem:

-     **Jitsi Meet Server:** Self-hosted, latest stable
-     **Mobile Apps:** Issue appears from version 24.3.0 onwards (both Android and iOS)
-     **Browser:** Not affected, camera works perfectly fine
-     **Cause:** Custom video constraints in my configuration (/etc/jitsi/meet/<domain>-config.js):

```
constraints: {
    video: {
        height: {
            ideal: 720,
            max: 1080,
            min: 720,
        },
    },
},
```

When I comment out this custom constraints block (thus reverting to the default 720p limit), the camera instantly works again on mobile apps from version 24.3.0 onward:

```
// constraints: {
//     video: {
//         height: {
//             ideal: 720,
//             max: 1080,
//             min: 720,
//         },
//     },
// },
```

**Expected Behavior:**
Higher video constraints (like max:1080) should be respected by the mobile apps, or gracefully downgraded if unsupported.

**Actual Behavior:**
The camera stays disabled (button greyed out) completely in mobile apps when using custom constraints greater than the default 720p.

I've confirmed this on multiple devices, both Android and iOS.

I hope this helps narrow down the cause, and hopefully it can be resolved soon. Let me know if you need more info or tests from my side!
