### ISSUE TITLE
Unable to share screen

### ISSUE THREAD

**Issue by Saidhoussem** [jitsi/jitsi-meet#15021]
### What happened?

Steps to reproduce the issue : 

1. User A and User B are in the connected to the same meeting room.
2. User A attempts to share his screen
**Current behavior** 
Share screen work properly
**Actual result**
Share screen does not work

I tested with Android 10,12, 14,15
With you application From the Play store version 24.3.0 the issue does not happens, it happen only when i use my app that integrate the SDK 8.6.1.

I catched same logs but they are not clear, can you please tel me what does this means : 

**[modules/RTC/ScreenObtainer.js] MediaStreamTrack contentHint attribute not supported**
**[modules/xmpp/XmppConnection.js] Stream resume enabled, but WebSockets are not enabled**
**[modules/statistics/statistics.js] Cannot initialize WatchRTC in a react native environment!**

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [X] Custom app using a mobile SDK

### Browser / app / sdk version

SDK : 8.6.1

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Please test SDK 10.0.1.

**Comment by Saidhoussem** [comment]
nothing change.
i catch this log : 
[modules/RTC/ScreenObtainer.js] MediaStreamTrack contentHint attribute not supported

**Comment by saghul** [comment]
Please share the full `adb logcat` output

**Comment by Saidhoussem** [comment]
[CrosscallCoreX5Android12_logcat.txt](https://github.com/user-attachments/files/16625498/CrosscallCoreX5Android12_logcat.txt)
[GooglePixel7ProAndroid15_logcat.txt](https://github.com/user-attachments/files/16625501/GooglePixel7ProAndroid15_logcat.txt)

**Comment by saghul** [comment]
I don't see anything obvious. Are you ablee to reproduce the problem with an unmodified SDK?

Are you running your own server? What versions of the server components do you have?

**Comment by Saidhoussem** [comment]
Hello, yes it is reproducible?
What do you mens by unmodified SDK?
The issue is not related on the server it is on the mobile side.

Best regards,
Houssem
