### ISSUE TITLE
Bug issue template

### ISSUE THREAD

**Issue by webRTCv1** [jitsi/jitsi-meet#15028]
### What happened?

Hi there,
We wanted to point out that in GitHub bug issue template, the [validations](https://github.com/jitsi/jitsi-meet/blob/896fc29af7a499dc9ad3296e5e37a285b1614338/.github/ISSUE_TEMPLATE/1-bug.yml?plain=1#L33) property doesn’t support checkboxes, so you can’t directly enforce a required selection. Also, there’s a small [typo fix](https://github.com/jitsi/jitsi-meet/blob/896fc29af7a499dc9ad3296e5e37a285b1614338/.github/ISSUE_TEMPLATE/1-bug.yml?plain=1#L38).

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

*

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

1. Remove validations from checkboxes

```yml
    validations:
      required: true
```

2. Fix typo

`provice` become provide

**Comment by saghul** [comment]
Thanks for the heads up! Would you like to send a PR?

**Comment by webRTCv1** [comment]
> Would you like to send a PR?

Feel free to make any adjustments you think are necessary, it's just a minor fix :)

**Comment by thepiyush-303** [comment]
Hello @saghul ,
How would it work if I send you a pull request on this issue?
Thanks
