### ISSUE TITLE
Moderator Breakout Room Connection Error

### ISSUE THREAD

**Issue by Glaukom** [jitsi/jitsi-meet#15024]
### What happened?

When I join a room as "non moderator" and I authenticate myself vie "login" in the settings->profile section, to get the "moderator" status, I get an error when creating a breakout room and I try to join it.

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

2.0.9646

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

- The error occurs when I'm the first person to join the breakout room
- prosody config, see below
- we have one prosody user and share credentials for different users to gain mod permissions

```
Component "conference.XXX.de" "muc"
    restrict_room_creation = true
    storage = "memory"
    modules_enabled = {
        "muc_hide_all";
        "muc_meeting_id";
        "muc_domain_mapper";
        "polls";
        --"token_verification";
        "muc_rate_limit";
        "muc_password_whitelist";
    }
    admins = { "focus@auth.XXX.de" }
    muc_password_whitelist = {
        "focus@auth.XXX.de"
    }
    muc_room_locking = false
    muc_room_default_public_jids = true

Component "breakout.XXX.de" "muc"
    restrict_room_creation = true
    storage = "memory"
    modules_enabled = {
        "muc_hide_all";
        "muc_meeting_id";
        "muc_domain_mapper";
        "muc_rate_limit";
        "polls";
    }
    admins = { "focus@auth.XXX.de" }
    muc_room_locking = false
    muc_room_default_public_jids = true
```

**Comment by damencho** [comment]
What is the error you see? Share browser ja console logs and prosody logs.

**Comment by Glaukom** [comment]
Hi there, sorry for my late answer.
I added prosody, jicofo, jvb and console.logs, I truncated the data to the timing when the error occurs.
For your understanding:
- For joining a room, we restricted access (creating rooms) only to mods
- if I authenticate inside the react app before joining, it's not a problem to join breakout rooms
- But when I enter a room that's already created and I authenticate via the profile login, I get the error when joining a breakout room

The name of the main room was 123, the created breakout room was (default naming) Number 1, my authentication name was "tahameln"
[jicofo.log](https://github.com/user-attachments/files/16748818/jicofo.log)
[jms-test.MYDOMAIN.de-1724673978708.log](https://github.com/user-attachments/files/16748819/jms-test.MYDOMAIN.de-1724673978708.log)
[jvb.log](https://github.com/user-attachments/files/16748820/jvb.log)
[prosody.log](https://github.com/user-attachments/files/16748821/prosody.log)
![jms-test MYDOMAIN de-error-2024-08-26 141839](https://github.com/user-attachments/assets/270d6cbc-aff7-4579-a5ab-20bb2c325f81)

**Comment by damencho** [comment]
Can you execute in the client where you see the error `APP.conference.saveLogs()` and upload the file here.

**Comment by Glaukom** [comment]
Sure, here it is
[meetlog.json](https://github.com/user-attachments/files/16749337/meetlog.json)

**Comment by damencho** [comment]
```
    <presence
        from = "69064573-1afe-42eb-ae8e-59377263959a@breakout.jms-test.MYDOMAIN.de/fa1739b2"
        to = "snxahnw7dmbboyhty1l_tss4@guest.jms-test.MYDOMAIN.de/HUHW_bjrWqRk"
        type = "error" xmlns = "jabber:client">
        <error
            by = "breakout.jms-test.MYDOMAIN.de" type = "cancel">
            <not-allowed xmlns = "urn:ietf:params:xml:ns:xmpp-stanzas" />
            <text xmlns = "urn:ietf:params:xml:ns:xmpp-stanzas">Room creation is restricted</text>
        </error>
    </presence>

```
Hum, this means jicofo was not in the room.

**Comment by damencho** [comment]
Who created the breakout room? Is the same participant that was logged in via Profile tab?

**Comment by Glaukom** [comment]
Yes, I already wondered, because it seems like I'm joining the room as guest and that's causing the issue.
Would it help to share the prosody config?

**Comment by Glaukom** [comment]
But the problem also occurs if anyone else (as moderator) is joining the room, if a non-moderator joins the room first, everything is fine

**Comment by damencho** [comment]
yep, it is strange. This is a bug as this kind of authentication is something we do not use and break occasionally. And this exact case is not something we test. 
Will take a look when time permits.
