### ISSUE TITLE
YouTube is no longer streaming from "play video" to "Live Streaming" (via YouTube)

### ISSUE THREAD

**Issue by pikurasa** [jitsi/jitsi-meet#15026]
### What happened?

It used to be possible to do a live stream via YouTube (YT), and broadcast another YT video as part of that feed.

But, now it asks you to "log in", presumably Jitsi needs to log in.

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Version 120.0.6099.224 (Official Build) built on Debian 11.8, running on Debian 11.7 (64-bit)

### Relevant log output

```shell
N/A
```

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

Notes:
* The first video(s) may or may not work
* This happens despite the user being logged into YT themselves
* The people in the room can see the YT video, but the YT video is not being sent to the live broadcast

**Comment by pikurasa** [comment]
This is the error that's displayed for the viewer of the broadcast (but not for the people in the Jitsi room): 
![Screenshot from 2024-08-16 13-47-26](https://github.com/user-attachments/assets/175621c0-0ed1-46c2-9a67-972cb09a6e90)

**Comment by saghul** [comment]
This is a change on the YouTube side, not much we can do about it I'm afraid.

**Comment by pikurasa** [comment]
> This is a change on the YouTube side, not much we can do about it I'm afraid.

I understand that may be the case, but I wanted to let people know about it.

If the issue persists, it may be worth a warning, so that users know not to try it.

Also, as a workaround, I wonder if screensharing a YT page with sound would work.
