### ISSUE TITLE
Cannot limit screen sharing resolution

### ISSUE THREAD

**Issue by DamirDautov** [jitsi/jitsi-meet#15033]
### What happened?

While using self-hosted Jitsi we happened to notice that we cannot limit max resolution of screen sharing by environment variables.
The common scenario is when user has 4k monitor and tries to share their screen to several users (so not p2p) which leads to high traffic consumption and reduce of video resolution (from camera and etc).
We tried to limit it by setting variables such as `config.resolution` and `config.constraints`:
```js
config.resolution = 1080;
config.constraints = {
    video: {
        height: { ideal: 1080, max: 1080, min: 720 },
        width: { ideal: 1920, max: 1920, min: 1024},
    }
};
```
but that didn't take any affect on screensharing, only for camera video. 
Also we've tried to set `desktopSharingFrameRate` to high numbers so that users get lower resolution, but also no luck:
```
config.desktopSharingFrameRate = { min: 30, max: 60 };
```

Do we have any opportunity to lower or limit screen sharing resolution? Maybe I'm just blind and could not find something obvious. 
Any help appreciated. Thanks in advance!

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

127.0.6533.120

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
I'm not sure that's possible. @jallamsetty1 ?

**Comment by jallamsetty1** [comment]
Yes, it is not possible. The video constraints has no affect on screenshare capture resolution. The WebRTC spec doesn't let you control the capture resolution only the type of display surface. You will have to use applyContraints on the captured stream to change the resolution. I am closing this issue for this reason.

**Comment by jallamsetty1** [comment]
`Constraints serve a different purpose in [getDisplayMedia](https://www.w3.org/TR/screen-capture/#dom-mediadevices-getdisplaymedia) than they do in [getUserMedia](https://www.w3.org/TR/mediacapture-streams/#dom-mediadevices-getusermedia)(). They do not aid discovery, instead they are applied only after user-selection.` - From the link you shared. You cannot limit the capture resolution instead you can use these  constraints to modify the captured stream using applyConstraints after the browser returns the MediaStream using gDM.

**Comment by andrew-samson** [comment]
@jallamsetty1 
> instead you can use these constraints to modify the captured stream using applyConstraints

Can you please advise me how I can do this in Jitsi?

**Comment by jallamsetty1** [comment]
Sure, here is how we do it for min fps - https://github.com/jitsi/lib-jitsi-meet/blob/2e402970acd5239b294ebaec8bad1b69212fd8f3/modules/RTC/ScreenObtainer.js#L275

Please be advised that messing with the resolution of the captured stream has led to browser crashes in the past, especially when captured window is being resized. For e.g - https://issues.chromium.org/issues/40672396

**Comment by andrew-samson** [comment]
@jallamsetty1 
Pardon my stupid questions, but using only jitsi-meet, without fixing the low-level lib-jitsi-meet library, there is no way to set my constraints?

**Comment by jallamsetty1** [comment]
Nope. Unfortunately, we don't have an iframe API for this.

**Comment by lixiaotaowx** [comment]
> Nope. Unfortunately, we don't have an iframe API for this.

I really need such a function. Can it be realized in the future
