### ISSUE TITLE
The api stays empty

### ISSUE THREAD

**Issue by Kaki-In** [jitsi/jitsi-meet#15032]
### What happened?

I installed my server some four monthes ago, and everything works fine (the web browser version).

BUT when I use the api, it seems to stay totally empty, even if the room is succesfully entered and without any optional option. 

It was like that since the beginning, excepted at one moment, when the api gave me some great results, but since, it fails again and I can't understand why

You can find some screenshots of what my web console gives me [there](https://community.jitsi.org/t/cannot-use-the-api/131365/3?u=kakiin) . 

I hope to have been clear and that you'll be able to fix my issue, 
Kaki In

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

jitsi-meet: 2.0.9646 ; jitsi-meet-... : 1.0.8091 ; jitsi-videobridge2 : 2.3.160-g97...-1

### Relevant log output

As said, you can find some screenshots of what my web console gives me [there](https://community.jitsi.org/t/cannot-use-the-api/131365/3?u=kakiin) because console logs are really really hard to read.

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

```
ubuntu@host:~$ dpkg -l | grep jitsi
ii  jitsi-meet                             2.0.9646-1                                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                     1.0.8091-1                                   all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver                  1.0.8091-1                                   all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                         1.0.8091-1                                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                  1.0.8091-1                                   all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                     2.3-160-g97a1f15b-1                          all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                             0.4.1-jitsi1                                 all          baseXX encoding/decoding library for Lua
```

**Comment by saghul** [comment]
Please continue the discussion in the community forum.
