### ISSUE TITLE
In meeting video on then flicker issue occurred.

### ISSUE THREAD

**Issue by samadhan-dhangar** [jitsi/jitsi-meet#15037]
### What happened?

Hello team, 

In Meeting:- Where 4 to 6 users are in the meeting and if I have pinned 2 users and they are continuously speaking and their camera is also 'on' then at the same time the flicker issue occurred.
 there any configuration am I missing or I have to update any driver?  

For more detail please check video.

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [X] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

latest

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

https://drive.google.com/file/d/1VQI7r506jZy3h3mmvjdTNgTvdcGrAivB/view

**Comment by saghul** [comment]
You are setting the experimentall multi-pinning to 2, right?

**Comment by samadhan-dhangar** [comment]
@saghul , Yes. I changed pinning 5 to 6 also getting same issue.

**Comment by saghul** [comment]
Thanks for the report. That feature is still somewhat experimental, we'll keep this in mind next time we go and make improvements there.

**Comment by samadhan-dhangar** [comment]
@saghul , Thanks for quick support,
