### ISSUE TITLE
Jibri recording driver's issue - shows unnecessary chrome tab for jibri recording

### ISSUE THREAD

**Issue by triveni-radhik** [jitsi/jitsi-meet#15036]
### What happened?

I have configured Jitsi and Jibri on Azure K8s and It's communication working fine and it's record my meeting as well. But after recording when I play that recording it's showing me chrome tab and other unnecessary size of video and there is no audio in that recording but video working fine is there any configuration am I missing or I have to update any driver?

For more details check screen shot this is screen when I play recorded meeting.

![image](https://github.com/user-attachments/assets/25f63f9f-b7a5-42b7-803e-9783f4171a89)

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [X] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [X] Custom app using a mobile SDK

### Browser / app / sdk version

Latest

### Relevant log output

```shell
Jibri 2024-08-20 13:15:02.956 INFO: [18] [session_id=kpxckdehtryhlhfu] MediaReceivedStatusCheck.run#45: Jibri client receive bitrates: {audio={download=30, upload=0}, download=405, upload=0, video={download=375, upload=0}}, num participants: 1, numMutedParticipants: 0, numJigasis: 0, all clients muted? false
Jibri 2024-08-20 13:15:04.210 FINE: [18] WebhookClient$updateStatus$1.invokeSuspend#109: Updating 0 subscribers of status
Jibri 2024-08-20 13:15:17.951 INFO: [18] [session_id=kpxckdehtryhlhfu] MediaReceivedStatusCheck.run#45: Jibri client receive bitrates: {audio={download=31, upload=0}, download=277, upload=0, video={download=246, upload=0}}, num participants: 1, numMutedParticipants: 0, numJigasis: 0, all clients muted? false
Jibri 2024-08-20 13:15:32.961 INFO: [18] [session_id=kpxckdehtryhlhfu] MediaReceivedStatusCheck.run#45: Jibri client receive bitrates: {audio={download=31, upload=0}, download=189, upload=0, video={download=158, upload=0}}, num participants: 1, numMutedParticipants: 0, numJigasis: 0, all clients muted? false
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

![image](https://github.com/user-attachments/assets/592513e7-050a-484a-aa27-35a714ca6598)

**Comment by saghul** [comment]
What Jibri image did you use?

**Comment by triveni-radhik** [comment]
@saghul Thanks for quick support, 

I have used Jibri-9111 release version.

**Comment by saghul** [comment]
Did you modify the image in any way? What env vars did you pass?

**Comment by triveni-radhik** [comment]
No, I haven't modify It but I have used finalize script.

Below are the envs I have passed,

`env:
            - name: JIBRI_XMPP_USER
              value: jibri
            - name: JIBRI_XMPP_PASSWORD
              value: '******'
            - name: JIBRI_RECORDER_USER
              value: recorder
            - name: JIBRI_RECORDER_PASSWORD
              value: '******'
            - name: AUTH_TYPE
              value: "jwt"
            - name: ENABLE_AUTH
              value: "1"
            - name: ENABLE_COLIBRI_WEBSOCKET
              value: "1"
            - name: ENABLE_GUESTS
              value: "1" 
            - name: ENABLE_OCTO
              value: "1"
            - name: ENABLE_RECORDING
              value: "1"
            - name: ENABLE_XMPP_WEBSOCKET
              value: "1"
            - name: JWT_ALLOW_EMPTY
              value: "0"
            - name: JWT_AUTH_TYPE
              value: token
            - name: PUBLIC_URL
              value: https://domain.com/
            - name: TZ
              value: UTC
            - name: XMPP_AUTH_DOMAIN
              value: auth.domain.com
            - name: XMPP_DOMAIN
              value: record-stage.domain.com
            - name: XMPP_GUEST_DOMAIN
              value: guest.record-stage.domain.com
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.record-stage.domain.com
            - name: XMPP_MUC_DOMAIN
              value: muc.record-stage.domain.com
            - name: XMPP_RECORDER_DOMAIN
              value: recorder.record-stage.domain.com
            - name: XMPP_SERVER
              value: "prosody.rm.svc.cluster.local"
            - name: COLIBRI_WS_TLS
              value: "1"
            - name: JVB_ADVERTISE_IPS
              value: "IP_ADDRESS"
            - name: DISPLAY
              value: ":0"
            - name: JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
              value: /opt/jitsi/jibri/finalize_recording.sh
            - name: JIBRI_LOGS_DIR
              value: /config/logs
            - name: JIBRI_RECORDING_DIR
              value: /config/recordings
            - name: CHROMIUM_FLAGS
              value: --start-fullscreen --start-maximized --window-size=1280,720 --kiosk --disable-infobars --no-sandbox --disable-translate --ignore-certificate-errors --autoplay-policy=no-user-gesture-required
            - name: JIBRI_RECORDING_RESOLUTION
              value: 1280x720
            - name: JIBRI_STRIP_DOMAIN_JID
              value: muc
            - name: JIBRI_USAGE_TIMEOUT
              value: "0"
            - name: JWT_APP_ID
              value: jitsi
            - name: JWT_APP_SECRET
              value: ******
            - name: JWT_APP_SECRET
              value: ******
            - name: JWT_TOKEN_AUTH_MODULE
              value: token_verification
            - name: JWT_ACCEPTED_AUDIENCES
              value: radiantmeetui
            - name: JWT_ACCEPTED_ISSUERS
              value: radiantmeet
            - name: JICOFO_AUTH_PASSWORD
              value: '******'
            - name: JVB_PORT
              value: "10000"`

**Comment by saghul** [comment]
If you uppdate to the latest image version you can use this env var: https://github.com/jitsi/docker-jitsi-meet/blob/f893e497df2d625657384e5896b1148a9ebc401c/jibri.yml#L26 to avoid passing all the chrome flags, which I think is what might cause trouble.

**Comment by triveni-radhik** [comment]
Yes, Have checked without flag as well, But still facing the same issues, 

Any other things I need check from config side?

**Comment by triveni-radhik** [comment]
@saghul , Thanks for your update and for my bad I have wrong configurations For chrome flags and Now it's working.

Closing  the issue. and Again Thanks for quick support.
