### ISSUE TITLE
iframe API: support defining user interface language for every user

### ISSUE THREAD

**Issue by mikkorantalainen** [jitsi/jitsi-meet#15047]
### What problem are you trying to solve?

I'm trying to use meet.jit.si in an IFRAME and I have users which would prefer to see the user interface in English or Finnish depending on user. I know the preferred language of the user while generating the iframe element but I cannot set the language for the content inside the iframe that's visible for the given user.

And if possible, I'd like to set the <title> element inside the iframe SRC address (in case I load the address in toplevel window) according to the user language (I would set title according to the language of the UI). I know that I can change to subject of the room with config.subject (I think this used to be config.roomName earlier but I couldn't find information about this change).

### What solution would you like to see?

Jitsi should support specifying per iframe language instead of site global language.

### Is there an alternative?

I've tried to pass config options lang, defaultLanguage, configOverwrite.lang, configOverwrite.defaultLanguage and URL parameter ?lang=fi but nothing seems to work.

**Comment by damencho** [comment]
The options you pass to JitsiMeetExternalAPI can have `lang` option. 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe
Make sure when testing you use incognito window and close the window between tests.

Once the language is set in the browser (you have loaded it at least once) you can change it only from the settings menu, changing the parameter you pass, does not work.

**Comment by dhlavaty** [comment]
Still does not work - tested on Firefox 134.0, Brave 1.69.160 and Safari 17.6 ( incognito and non-incognito tired as well ). Tried all the options mentioned ☝️ 

I've noticed an error in console (trying to use `de` for example):

```
JSON Parse error: Unexpected identifier "de"
```

**Comment by damencho** [comment]
How are you setting it?
