### ISSUE TITLE
Video Stopped working after upgrading the SDK

### ISSUE THREAD

**Issue by Anasmirza20** [jitsi/jitsi-meet#15076]
After upgrading the SDK from version 5.2.0 to 10.1.0 to support Android 14, the video functionality suddenly stopped working when transitioning between apps. Other features, like audio calls, continue to work as expected, but video calls fail to function.

Steps to Reproduce:

Upgrade the SDK from version 5.2.0 to 10.1.0.
Attempt to initiate a video call between two apps.
Observe that the video does not work, although audio and other features function correctly.
Expected Behavior: The video should continue to work seamlessly after the SDK upgrade, just as it did with version 5.2.0.

Actual Behavior: The video stops working when transitioning between apps after the SDK upgrade.

Additional Information:

The issue began only after upgrading to version 10.1.0.
Audio calls and other functionalities remain unaffected.
Request for Help: Any guidance on debugging this issue or insights into potential causes would be greatly appreciated.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

34

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by Anasmirza20** [comment]
Here is our config file

https://drive.google.com/file/d/1UUiXpFZS_-87YkghmEOn96F3e0p9Y3NQ/view?usp=sharing

**Comment by damencho** [comment]
What is the backend version?

**Comment by Anasmirza20** [comment]
Our current version is 2.7.0.

**Comment by Anasmirza20** [comment]
@damencho Let me know If we can get paid support on a priority. This issue is impacting many of our current users.

you guys can connect me here: anas.ma854@gmail.com

**Comment by Anasmirza20** [comment]
QHD Jitsi Version

ii jitsi-meet 2.0.7419-1 all WebRTC JavaScript video conferences
ii jitsi-meet-prosody 1.0.6242-1 all Prosody configuration for Jitsi Meet
ii jitsi-meet-tokens 1.0.6258-1 all Prosody token authentication plugin for Jitsi Meet
ii jitsi-meet-web 1.0.6242-1 all WebRTC JavaScript video conferences
ii jitsi-meet-web-config 1.0.6242-1 all Configuration for web serving of Jitsi Meet
ii jitsi-videobridge2 2.2-8-g3c9d3c52-1 all WebRTC compatible Selective Forwarding Unit (SFU)

**Comment by damencho** [comment]
Your version is more than two years old, you need to update it.

**Comment by Anasmirza20** [comment]
If you don't mind can you please let us know which component versions are compatible with the Android Sdk version 10.1.0?

**Comment by damencho** [comment]
In general you should be updating on regular basis. The development of jitsi-meet system follows the browsers which change every month.
Updating to latest version from stable should be fine, as this is the latest sdk release.

**Comment by Anasmirza20** [comment]
Okay Thanks for the fast response, Let me try to update
