### ISSUE TITLE
Duplicate Participants icons while sharing Video in Meeting

### ISSUE THREAD

**Issue by thepiyush-303** [jitsi/jitsi-meet#15077]
### What happened?

While sharing a video during a meeting, I noticed an issue where hovering over participants shows two participant option icons instead of one. This creates confusion and clutters the UI.

Steps to Reproduce:

    Start a meeting.
    Begin sharing a video.
    Hover over participants.

Expected Behavior: Only one participant options icon should be visible when hovering over participants.

Actual Behavior: Two participant option icons are displayed,

### Platform

- [ ] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Firefox 129.0.2 (64-bit)

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

[Screencast from 2024-08-31 21-58-43.webm](https://github.com/user-attachments/assets/78597202-8339-4c8b-bf31-eaa1bb08c2d1)

**Comment by damencho** [comment]
Can you share the js console logs from both sides?

**Comment by thepiyush-303** [comment]
[console-export-2024-9-3_17-28-26.txt](https://github.com/user-attachments/files/16848206/console-export-2024-9-3_17-28-26.txt)

**Comment by damencho** [comment]
These are the logs from which side?
You use video sharing to share a video file?
It is normal to see a thumbnail for the shared video.

**Comment by thepiyush-303** [comment]
To clarify, the logs I provided are from the moderator side. As the moderator, I am sharing a video file during the meeting.

The issue isn't just about seeing a thumbnail for the shared video; it's about the presence of two participant option icons when hovering over participants while sharing the video. This duplication is causing confusion in the UI.

I understand that a thumbnail for the shared video is expected, but the problem I'm highlighting is specifically with the participant option icons that appear twice.

**Comment by damencho** [comment]
Hum, interesting I cannot reproduce this on meet.jit.si. 

Here is what I see when I share a video:
https://github.com/user-attachments/assets/a188b837-31ac-4a5f-8709-3aa197f7c511

What URL are you sharing to test with it?

**Comment by thepiyush-303** [comment]
I understand that you're looking at it from the perspective of the participants who are not sharing their video. However, if you view it from the perspective of the participant who is sharing their video, you'll notice the actual issue.

**Comment by damencho** [comment]
Yep, noted. I see it now, thanks. 
We will take a look.

**Comment by thepiyush-303** [comment]
I'm having difficulty locating the files that are causing this issue. Could you help me with this?

**Comment by damencho** [comment]
This is feature shared video:
https://github.com/jitsi/jitsi-meet/tree/master/react/features/shared-video
The problem is in the participant pane:
https://github.com/jitsi/jitsi-meet/tree/master/react/features/participants-pane
But it is possible the problem comes from the participants stored in the redux store:
https://github.com/jitsi/jitsi-meet/tree/master/react/features/base/participants

**Comment by damencho** [comment]
This is fixed now on meet.jit.si, you can try it there.

**Comment by thepiyush-303** [comment]
Thankyou @damencho 
For quick guidance, I already checked the application now there are no more duplicate icon and I noticed you also add Thumbnail to sharer side which is also user friendly 
Thanks,
