### ISSUE TITLE
jitsi meet login

### ISSUE THREAD

**Issue by Rawand-1** [jitsi/jitsi-meet#15075]
### What happened?

i have problem with jitsi meet app on android every time i lunch the app it requires me login with my google account 

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

24.4.0 build 17777652

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
This is expected when connecting to meet.jit.si. Authentication is specific to each deployment.
