### ISSUE TITLE
iPhone screen sharing isn't very high definition

### ISSUE THREAD

**Issue by strangerBen** [jitsi/jitsi-meet#15094]
### What problem are you trying to solve?

When screen sharing is enabled on an iPhone, the screen that the web attendees see will be blurry when the iPhone switches screens quickly. It will only become clear when the iPhone is still. In the iOS Extension, I can see that there is an fps value adjustment (frameCount % 3). I removed this judgment, but it still cannot achieve clarity when switching screens quickly. Are there other settings that can solve this requirement? For example, server settings or property settings?

### What solution would you like to see?

Specific setting instructions

**Comment by eric-gitta-moore** [comment]
any news?

**Comment by strangerBen** [comment]
still need help

**Comment by saghul** [comment]
It's a performance tradeoff. Just like browsers, which default to low fps but high resolution.

In our implementation we limit the fps because of performance reasons and the limitations around broadcast extensions.
