### ISSUE TITLE
Jitsi Meet SDK Lite SPM

### ISSUE THREAD

**Issue by Brandon-T** [jitsi/jitsi-meet#15095]
### What problem are you trying to solve?

https://github.com/jitsi/jitsi-meet-ios-sdk-releases/tree/master

Doesn't have a `Package.swift` for the `Lite` version of the SDK. Currently `Package.swift` would pull in the `GiphyUI.framework` always.

### What solution would you like to see?

- Add a `Package.swift` for just the `Lite` framework: https://github.com/jitsi/jitsi-meet-ios-sdk-releases/tree/master/lite/Frameworks

**Comment by saghul** [comment]
It's here now: https://github.com/jitsi/jitsi-meet-ios-sdk-releases/blob/master/lite/Package.swift
