### ISSUE TITLE
'Old' browser version number warning

### ISSUE THREAD

**Issue by danboid** [jitsi/jitsi-meet#151]
I have been told in the Jitsi IRC channel that Chromium/Chrome < 36 has buggy webrtc support. 

If so, Jitsi webrtc should print a warning for users of sufficiently 'old' browsers to tell them they may experience issues if they don't upgrade to a suitable version.

I don't know nor did I ask about the minimum Opera version required but this should be detected too if it has similar issues.

**Comment by damencho** [comment]
Currently, there is an unsupported browser webpage.
