### ISSUE TITLE
Jitsi meet  React Native speaker problem 

### ISSUE THREAD

**Issue by McCrayCircle** [jitsi/jitsi-meet#15106]
### What happened?

Hello.
I'm developing meeting app using jitsi meet React native sdk.
I hosted the jitsi server to my own server.
On meeting page, speaker is not working now.
I'm using this module
"@jitsi/react-native-sdk": "^10.1.2",``
![Uploading Untitled.png…]()

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Andorid 14

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?
No available audio devices
_No response_

**Comment by damencho** [comment]
What does speaker is not working? 
Are you able to have a 3 tab call in the browser with video on your slef-hosted server?

**Comment by McCrayCircle** [comment]
I don't know why speaker doesn't work now.
I upgraded the module to 10.1.2 as you told on community.

**Comment by McCrayCircle** [comment]
What is 3 tab call?

**Comment by damencho** [comment]
Open a meeting in your browser , the same link in 3 tabs.

**Comment by damencho** [comment]
Please when we are in conversation already in the forum, avoid opening new issues if not instructed so.

**Comment by McCrayCircle** [comment]
Yes, got it
but I don't know how to find  @saghul  and @Calinteodor .
As I mentioned, I need to enable speaker on mobile. not web browser. 
How to solve that problem?

**Comment by McCrayCircle** [comment]
![Uploading Untitled.png…]()
Speaker button is not working now

**Comment by McCrayCircle** [comment]
@damencho  can you see the image I sent?

**Comment by damencho** [comment]
No, I don't see the image. I already mentioned them, and when they have time they will take a look and maybe give you an advise.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by McCrayCircle** [comment]
ok,. I will close this.

**Comment by damencho** [comment]
When you said speaker, I thought that the active speaker is not working, which may mean there is no media coming from your deployment. 
I make no connection between your post in the forum and this one, which leads to confusion as I already understood the problem you are trying to fix, which is another point of not discussing the same thing in a few places.

**Comment by damencho** [comment]
https://community.jitsi.org/t/speaker-is-not-working-on-jitsi-videos-call/133534/14

**Comment by McCrayCircle** [comment]
I didn't get solution. please open again
