### ISSUE TITLE
Set virtual background through jitsi meet external API

### ISSUE THREAD

**Issue by Razor1700** [jitsi/jitsi-meet#15104]
### What problem are you trying to solve?

I got an application including jitsi meet external API to handle video call feature. Before joining a call, the user can setup his devices similar to what meet.jit.si behavior. From there, the api does not provide any endpoint to change the user virtual background so I cannot give the user that ability. During the call, I got a blur background checkbox to allow the user to quickly blur its background if wanted but same issue here.

### What solution would you like to see?

If possible, I want to get a parameter to apply the background directly at the start of the iframe using configOverwrite and an endpoint to apply an equivalent of at least these 2 const from VirtualBackgrounds.tsx :

`const enableBlur = useCallback(async () => {
        onOptionsChange({
            backgroundEffectEnabled: true,
            backgroundType: VIRTUAL_BACKGROUND_TYPE.BLUR,
            blurValue: 25,
            selectedThumbnail: 'blur'
        });
        logger.info('"Blur" option set for virtual background preview!');

    }, []);`

`const enableSlideBlur = useCallback(async () => {
        onOptionsChange({
            backgroundEffectEnabled: true,
            backgroundType: VIRTUAL_BACKGROUND_TYPE.BLUR,
            blurValue: 8,
            selectedThumbnail: 'slight-blur'
        });
        logger.info('"Slight-blur" option set for virtual background preview!');

    }, []);`

### Is there an alternative?

I considered to use the default jitsi feature of the iframe but some features doesn't fit what we are looking for. I also considered to use the jitsi meet external api but I don't have enough time to recreate an equivalent of what the iframe is doing so it's why I'm using iframe api.

**Comment by damencho** [comment]
This was implemented with https://github.com/jitsi/jitsi-meet/commit/97930bfef21391e270b8a85ebc2a01b3fcc1feff
