### ISSUE TITLE
You have been disconnected

### ISSUE THREAD

**Issue by MahmoudSaidHaggag** [jitsi/jitsi-meet#15103]
### What happened?

I installed jitsi on this domain https://meet.eduloop.net/, but when i connect to it, it give me you have been disconnected

Please can help me

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

https://meet.eduloop.net

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
You can see an error in the js console in the browser:
```
[conference.js] <D$._onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected
```
Check your jicofo logs what errors do you see there?

**Comment by damencho** [comment]
Will continue at https://community.jitsi.org/t/installation-problem/133538/2
