### ISSUE TITLE
Remove title

### ISSUE THREAD

**Issue by AlexGit1984** [jitsi/jitsi-meet#15118]
### What happened?

How to remove the title "Conference root"?

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

6.0.0

### Relevant log output

```shell
How to remove feature flag "title" - Conference root
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

<img width="223" alt="image" src="https://github.com/user-attachments/assets/d5461044-5ea4-4ae6-a398-dc9cdb807e6c">

**Comment by damencho** [comment]
Override this config:
https://github.com/jitsi/jitsi-meet/blob/756c4afbdd95eca99e04fe36e7b8f7026e3e6414/config.js#L1516

**Comment by AlexGit1984** [comment]
I've changed the config but nothing changed.
<img width="585" alt="image" src="https://github.com/user-attachments/assets/4f29ed9a-3afe-4c0c-aa02-c073bedfa7d2">


> Override this config:
> 
> https://github.com/jitsi/jitsi-meet/blob/756c4afbdd95eca99e04fe36e7b8f7026e3e6414/config.js#L1516

**Comment by damencho** [comment]
Do you see the change if you access the file directly? https://yourdoomain.com/config.js?
Try clearing cache of the app.

**Comment by AlexGit1984** [comment]
I've fixed, thank you.

> Do you see the change if you access the file directly? https://yourdoomain.com/config.js? Try clearing cache of the app.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
