### ISSUE TITLE
how to unmute for participant jitsi meet?

### ISSUE THREAD

**Issue by nguyendatdh93** [jitsi/jitsi-meet#1511]
Hi all.

I want to custom some thing jitsi meet for my website.  I want that : Moderator can unmute for any participant in room. How to do that?.

sorry all . My english is not good. 

Thank all.

**Comment by damencho** [comment]
Please when you have questions or problems, use the mailinglist before opening issues.

This is currently not possible and is a security concern, to not implement it. If you want to implement it in your deployment you need to consider that there can be changes needed and inside jicofo, not only in the UI.
