### ISSUE TITLE
AutoGainControl doesn't updating

### ISSUE THREAD

**Issue by vabyars** [jitsi/jitsi-meet#15133]
### What happened?

Hello. I try to turn off or turn on AGC during a call. But this setting applies only after page reload. So, when I paste this command `jitsiTrack.track.getConstraints()` to the console to check AGC status, it returns the correct value. However, there is no difference in recorded audio, while after reload there is.

I found this [issue](https://github.com/jitsi/jitsi-meet/issues/11668#issuecomment-1153945666). Maybe you can tell more information about this functionality.

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

128.0.6613.138 

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
There is no such feature at the moment to turn on and off those settings during a call.

**Comment by vabyars** [comment]
Okay. Can u tell why? I'm just intresting, maybe there are some limitation

**Comment by damencho** [comment]
There is no UI for it in jitsi-meet, and there is no API for this in lib-jitsi-meet. But there is no technical limitation this to be done.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by vabyars** [comment]
Ok, thanks!
