### ISSUE TITLE
 Unable to Join a new room while being connected to another one

### ISSUE THREAD

**Issue by wiemrh95** [jitsi/jitsi-meet#15144]
### What happened?

 Unable to Join a new room while being connected to another one , the join meeting room  button doesn't work  
 , it happen when i use my app that integrate the SDK 8.6.1.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [x] Custom app using a mobile SDK

### Browser / app / sdk version
SDK : 8.6.1
Android

### Reproducibility

- [] The problem is reproducible on meet.jit.si

**Comment by wiemrh95** [comment]
Are there any updates on this issue?

**Comment by damencho** [comment]
Currently the sdk and the jitsi-meet app are designed to serve only one room and one connection.
