### ISSUE TITLE
How i can Bypass Lobby for the owner of the room.

### ISSUE THREAD

**Issue by TGC-PratikNanavare** [jitsi/jitsi-meet#15156]
### What happened?

Hello team,

I have encountered an issue in Jitsi Meet. When I join a meeting(own meeting) with an active lobby and accidentally leave the meeting—either due to a network issue or by mistake—upon trying to rejoin, I see a window that prevents me from entering.

My jwt authentication.
AUTH_TYPE=jwt
JWT_AUTH_TYPE=token

![image](https://github.com/user-attachments/assets/06b4c2cd-7214-4544-bbe6-f1f106bf3349)
 

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [X] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

latest

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by shawnchin** [comment]
If you have questions, you should probably ask on the [Jitsi Community Forum](https://community.jitsi.org/) first rather than post an issue on this repo.

Since you're using JWT auth, you can use something like this prosody module to allow users with the right token claims to always bypass lobby -- https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_lobby_bypass

**Comment by damencho** [comment]
Another option is to set password for the room, which can be used to bypass lobby.

**Comment by TGC-PratikNanavare** [comment]
> If you have questions, you should probably ask on the [Jitsi Community Forum](https://community.jitsi.org/) first rather than post an issue on this repo.
> 
> Since you're using JWT auth, you can use something like this prosody module to allow users with the right token claims to always bypass lobby -- https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_lobby_bypass

I have added this plugin and loaded also.
but it is not going inside "muc-occupant-pre-join" hook.

**Comment by shawnchin** [comment]
How did you add the plugin?

**Comment by TGC-PratikNanavare** [comment]
> How did you add the plugin?

In the README file, they provided some steps. I followed those steps to add the plugin.

**Comment by TGC-PratikNanavare** [comment]
> Another option is to set password for the room, which can be used to bypass lobby.

Is there any other way to byPass the lobby?

**Comment by fruworg** [comment]
any updates?
