### ISSUE TITLE
Users cannot hear meeting when disableInitialGUM is true

### ISSUE THREAD

**Issue by pascuflow** [jitsi/jitsi-meet#15158]
### What happened?

I have the following config for visitors and would like to not have to ask for mic permissions in order to hear the conference.

Jitsi 2.0.9753
```
const viewerOptions = {
      roomName: session.id,
      jwt: jitsiToken,
      parentNode: document.getElementById("jitsi-container"),
      configOverwrite: {
        toolbarButtons: ["chat", "hangup", "fullscreen", "invite"],
        defaultRemoteDisplayName: "Visitor",
        prejoinConfig: { enabled: false },
        disableSelfView: true,
        hideDisplayName: false,
        requireDisplayName: true,
        disableSelfViewSettings: true,
        startWithAudioMuted: true,
        startWithVideoMuted: true,
        disableInitialGUM: false, ---> set to true breaks audio reception
        disableTileView: true,
        breakoutRooms: {
          hideAddRoomButton: true,
          hideAutoAssignButton: true,
          hideJoinRoomButton: true,
        },
        brandingRoomAlias: "session-start?sessionId=" + session.id,
        disableProfile: true,
        hideEmailInSettings: true,
        participantsPane: {
          hideModeratorSettingsTab: true,
          hideMoreActionsButton: true,
          hideMuteAllButton: true,
        },
        remoteVideoMenu: {
          disabled: true,
          disableKick: true,
          disableGrantModerator: true,
          disablePrivateChat: true,
        },
      },
    };
   
```
### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome 129.0.6668.58

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
When it is broken, do you see an error in the ja console, what it is?
Does it change if you enable pre join?
There is this thing that browsers requires user input in certain cases before playing anything, I suspect you are hitting this. And if that is the case you should use prejoin screen.

**Comment by pascuflow** [comment]
Enabling pre join allowed me to disable GUM without losing audio reception. Wanted to skip a prejoin since it's useless for visitors, but it's no big deal.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
