### ISSUE TITLE
Hide “Leave Meeting” button for Moderator

### ISSUE THREAD

**Issue by Anasmirza20** [jitsi/jitsi-meet#15153]
### What happened?

Hi Team,

I would like to know how I can customize the end-call functionality after upgrading the SDK on the Android side. Currently, when the moderator clicks the end call, two options appear: "Leave Meeting" and "End meeting for all". 

My requirement is to hide the "Leave Meeting" option and only show "End meeting for all" to the moderator. 

**SDK Information:**
I am using the following SDK version in my Android project:

implementation ('org.jitsi.react:jitsi-meet-sdk:10.1.0') { transitive = true }

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

10.1.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by MayconProg** [comment]
Hello Anasmirza20, I read what you said, but one question comes to mind: if the moderator wants to leave the room, just him, he won't be able to do so.
