### ISSUE TITLE
Draw on top of a shared screen

### ISSUE THREAD

**Issue by FerLuisxd** [jitsi/jitsi-meet#15155]
### What problem are you trying to solve?

In my presentations and at work, there are many occasions where you want to point at a location on the screen or to explain something more effectively.

### What solution would you like to see?

I would like to see a way to let users draw on top of the screen optionally. 

### Is there an alternative?

No, there is a whiteboard but it cannot be used on top of the shared screen.

**Comment by damencho** [comment]
Please stop opening duplicate issues.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/15121

**Comment by damencho** [comment]
A PR with implementing the feature is welcome.
