### ISSUE TITLE
Allow page refresh with token authentication

### ISSUE THREAD

**Issue by fsantner** [jitsi/jitsi-meet#15165]
### What problem are you trying to solve?

We use token authentication for our self hosted jitsi installation and everything works quite well. The only thing that is currently quite annoying is, that when  a user is successfully logged in by passing a valid JWT in the browser, the conference starts and then reloads the browser window, the user is prompted to enter username and password, which it does not have. 

### What solution would you like to see?

The user should be automatically logged in again, or at least the JWT should be added again so he can rejoin the conference.

**Comment by damencho** [comment]
> the conference starts and then reloads the browser window,

What is this reload? How does it happen? Are you using tokenAuthUrl in config.js?

**Comment by fsantner** [comment]
Hi @damencho and thx for the quick reply. We are joining a conference by passing the JWT in the URL. e.g. https://path-to-our-jitsi-server/ROOM12345?jwt=<JWT>. 
When I press F5 in the browser to reload the page, the user is logged out and sees the jitsi  "Join conference" page again instead of being in the conference again. 

![image](https://github.com/user-attachments/assets/caeefdf6-7b95-47c8-9371-c59ae0b91e6e)

I think the problem is, that the ?jwt=<JWT> is stripped away when the user entered/joined the conference, so when I press F5 the information is not sent anymore to jitsi.

**Comment by damencho** [comment]
Yep. You have two options, use the iframeAPI to pass the token, and then when users refresh you can pass it again. Another option is to implement the [tokenAuthUrl](https://github.com/jitsi/jitsi-meet/blob/5da69192e395f0c944b2200fe6fe41e583eb5d32/config.js#L1551)  to be passing the token and when people are not authenticated they will be redirected to it to get the token.
