### ISSUE TITLE
Cloud recording is not working when password is set.

### ISSUE THREAD

**Issue by TGC-PratikNanavare** [jitsi/jitsi-meet#15179]
### What happened?

When i set the password for the meeting and try to start recording the recording is not able to start.

Jibri Logs :-

`Jibri 2024-10-09 07:04:38.829 INFO: [207] XmppApi.updatePresence#212: Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
Jibri 2024-10-09 07:04:38.829 FINE: [207] MucClientManager.setPresenceExtension#160: Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@709eee1f
Jibri 2024-10-09 07:04:38.830 FINE: [207] MucClientManager.saveExtension#185: Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@62e0db92
Jibri 2024-10-09 07:04:38.832 INFO: [207] XmppApi.handleStartJibriIq#284: Sending 'pending' response to start IQ
Jibri 2024-10-09 07:04:38.836 FINE: [229] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
Jibri 2024-10-09 07:04:38.837 INFO: [239] AbstractPageObject.visit#32: Visiting url https://record.viziondev1.com:9445/
Jibri 2024-10-09 07:04:38.838 FINE: [229] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
Jibri 2024-10-09 07:04:41.397 INFO: [239] AbstractPageObject.visit#38: Waited 2.559459583s for driver to load page
Jibri 2024-10-09 07:04:41.398 INFO: [239] [session_id=umlyinyokazocbnb] JibriSelenium.joinCall$lambda$3#306: callStatsUsername is working
Jibri 2024-10-09 07:04:41.610 INFO: [239] AbstractPageObject.visit#32: Visiting url https://record.viziondev1.com:9445//pratik_nanavare-717#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"&config.analytics.disabled=true&config.p2p.enabled=false&config.prejoinPageEnabled=false&config.prejoinConfig.enabled=false&config.requireDisplayName=false
Jibri 2024-10-09 07:04:42.110 INFO: [239] AbstractPageObject.visit#38: Waited 499.611762ms for driver to load page
Jibri 2024-10-09 07:04:42.432 FINE: [239] CallPage$visit$1$1.invoke#58: Not joined yet: Cannot read properties of undefined (reading 'isJoined')
Jibri 2024-10-09 07:05:12.270 SEVERE: [239] CallPage.visit#65: Timed out waiting for call page to load
Jibri 2024-10-09 07:05:12.270 INFO: [239] [session_id=umlyinyokazocbnb] JibriSelenium.joinCall$lambda$3#325: cromeDriver not working
Jibri 2024-10-09 07:05:12.270 INFO: [239] [session_id=umlyinyokazocbnb] JibriSelenium.onSeleniumStateChange#218: Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2024-10-09 07:05:12.270 INFO: [239] [session_id=umlyinyokazocbnb] StatefulJibriService.onServiceStateChange#39: File recording service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2024-10-09 07:05:12.271 INFO: [239] XmppApi$createServiceStatusHandler$1.invoke#320: Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq <iq xmlns='jabber:client' to='jibribrewery@internal-muc.meet.jitsi/focus' id='12L73-325' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
Jibri 2024-10-09 07:05:12.271 FINE: [239] JibriStatsDClient.incrementCounter#38: Incrementing statsd counter: stop:recording
Jibri 2024-10-09 07:05:12.271 INFO: [239] JibriManager.stopService#274: Stopping the current service`

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [X] Android browser
- [X] iOS browser
- [X] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

latest

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by aaronkvanmeerten** [comment]
Please post your questions on the discourse: https://community.jitsi.org/

It's likely you don't have the proper prosody settings for allowing the recorder to join without a password.  Please check that the jibri is logging in with recorder credentials, and that that JID is allowed to join with no password.

**Comment by TGC-PratikNanavare** [comment]
> When i set the password for the meeting and try to start recording the recording is not able to start.
> 
> Jibri Logs :-

https://community.jitsi.org/t/cloud-recording-is-not-working-when-password-is-set/134741

i have added this issue/quesstion on community.
please check
