### ISSUE TITLE
Disable Screenshare for non-moderators

### ISSUE THREAD

**Issue by Tech-TK** [jitsi/jitsi-meet#15170]
### What problem are you trying to solve?

Currently sharing screen is all-or-nothing. If your meeting has screenshare enabled, every user can share their screen. If its disabled, no one can share their screen. No middle ground

### What solution would you like to see?

Add a configurable option that allows moderators to share their screen, but not other users

**Comment by damencho** [comment]
To be able to disable that it needs to be enforced server-side, and such a feature already exists - Audio/Video moderation where when enabled in a room non moderator participants need to ask for permission to speak or turn their camera, depends which option is enabled or both.

You can enable AV moderation as a moderator and allow just certain people to share video content when they request to do so.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
