### ISSUE TITLE
Jitsi Meet JWT Authentication Token removed after site refresh

### ISSUE THREAD

**Issue by mastro-vtg** [jitsi/jitsi-meet#15172]
### What happened?

Hello

We are using Jitsi Meet with JWT authentication, which works quite well so far.
One minor issue we noticed is that the token is removed from the URL once the user has entered the conference, which leads to a user being unauthorized when refreshing the page.

Are there any plans to keep the JWT in the URL after joining the conference so that the user can rejoin directly after a site reload?

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Edge Version 129.0.2792.52 (Official build) (64-bit)

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
> Are there any plans to keep the JWT in the URL after joining the conference

Nope, we specifically remove that so it disappears from any future bookmarks or site history.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
