### ISSUE TITLE
connection timeout for rejoin

### ISSUE THREAD

**Issue by erengms** [jitsi/jitsi-meet#15177]
### What happened?

I turn off wifi to test my scenarios while moving, it throws me out of the call after 5 seconds. But if I turn wifi back on before 5 seconds, I can rejoin the call. Where can we change this timeout period, from which file? What do I need to do, I would be glad if you could inform me.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

jitsi meet 9753 stable version

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Do you reproduce the same with meet.jit.si?

**Comment by erengms** [comment]
https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_9753
I compile this version for myself and extract libraries for ios and android. I am using the installation on my own server, not meet.jit.si, but I did not make any settings on my server regarding this period, I was compiling and using previous versions of jitsi (8044 stable), there was no such problem.

**Comment by damencho** [comment]
> https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_9753
> I compile this version for myself and extract libraries for ios and android. I am using the installation on my own server, not meet.jit.si, but I did not make any settings on my server regarding this period, I was compiling and using previous versions of jitsi (8044 stable), there was no such problem.

In general you should not do that, you need to use mobile release tags: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

Is your backend configured correctly for using websockets? Are you using websockets or bosh for connection?

Can you upload logcat logs from working and non working case.

Do you reproduce the same if you use the Jitsi Meet app from the store and meet.jit.si?

**Comment by erengms** [comment]
I couldn't reproduce it for the Jitsi Meet application in the store. I'm using bosh, not websocket, could this be related?

**Comment by damencho** [comment]
I suspect so, as resuming sessions is more graceful with websockets and this is what we have been using for a while now and for mobile on meet.jit.si.
