### ISSUE TITLE
The microphone does not turn on when there is only one person in the room.

### ISSUE THREAD

**Issue by erengms** [jitsi/jitsi-meet#15186]
### What happened?

I create a room and enter it, my camera light turns on on my Android and IOS devices, but my microphone does not turn on until a second person joins the room, my microphone light starts turning on when someone joins the room. I want my microphone to be on even when I am alone in the room, is there a way to do this?

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

2.0.9753

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
What is the point of doing that? It is not used at this point ... when a second participant joins it strat to be used.
There is no option to change that at the moment.

**Comment by erengms** [comment]
Actually, the audioMuteButton is not muted on my screen, but my microphone light is not on, but if I still want to fix this myself, where should I start? I want to turn on the microphone even if it is just one person.

**Comment by damencho** [comment]
Not sure, how would you do that, but probably you need changes in jitsi meet.

**Comment by damencho** [comment]
That is not an issue with existing code, so I will close this ticket.
Please, when you have questions or problems use the community forum before opening new issues, thank you.
