### ISSUE TITLE
Displaying "Fellow Jitser" for guests in Jitsi Android

### ISSUE THREAD

**Issue by oguzozturk** [jitsi/jitsi-meet#15187]
### What happened?

**Steps to reproduce**

1. Start a jitsi call.
2. Join the call from the guest invite link.
3. Check on Android and see "Fellow Jitster"

After the participant join the meeting, displays "Fellow Jitser" on the screen android devices. Although set feature flags and set user display name property as below, see "Fellow Jitser" on the screen. How can I remove "Fellow Jitser" display name?

**Android Device screenshot:**
![image](https://github.com/user-attachments/assets/ad91592a-2fcd-4ea8-99b1-6887c9fa602b)

`.setFeatureFlag("meeting-name.enabled", false)`
`.setFeatureFlag("prejoinpage.hideDisplayName", true)`

`JitsiMeetUserInfo userInfo=new JitsiMeetUserInfo();`
`userInfo.setDisplayName("");`

Server config:
`defaultRemoteDisplayName: ''`
`hideDisplayName: true`

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Android All Sdk Versions

### Relevant log output

```shell
No
```

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

### More details?

Jitsi Meet Sdk version :10.2.1

**Comment by damencho** [comment]
Have you tried setting defaultRemoteDisplayName to something other than an empty string? Try with Guest for example.

**Comment by oguzozturk** [comment]
Fellow Jitser appears on both Android and iOS platforms. I added text with one space. The image looks like below. It doesn't look nice like this and We don't want any text to show up on the image. Is there any way to remove it completely? 

![Image](https://github.com/user-attachments/assets/1a2c3224-57b7-4282-962c-49700073bcd6)

Which should we use Jitsi web version that is compatible with the Android and iOS Jitsi below versions? Is there any document that we can use to check this compatibility?

Android Sdk version: 10.2.1
IOS Sdk version: 10.1.2
Jitsi meet Web version:
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md

![Image](https://github.com/user-attachments/assets/a22db831-f686-4881-923e-7fc576aa7f93)

**Comment by saghul** [comment]
But also, that UI looks to be customized, so I guess you could remove what you don't like?

**Comment by oguzozturk** [comment]
We are using Android FragmentActivity which displays a single JitsiMeetView to join meeting. So we do not customize JitsiMeetView, just added Android UI elements on JitsiMeetView, make changes according to conference events. We are using different keyword but the text is not required to appear. Is there any way to remove it completely? Should we update Jitsi web server?

**Comment by saghul** [comment]
It's currently not possible to disable it. You'd need to customize the SDK and rebuild it.

**Comment by oguzozturk** [comment]
Thank you for support
