### ISSUE TITLE
Incorrect Apple link on https://jitsi.org/Projects/JitsiMeet

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [jitsi/jitsi-meet#1519]
The link "Jitsi Meet for iPhone and iPad" takes one to Google Play Store instead at https://jitsi.org/Projects/JitsiMeet. Link should probably be https://itunes.apple.com/us/app/jitsi-meet/id1165103905.

**Comment by damencho** [comment]
Fixed, thanks.
