### ISSUE TITLE
IOS bluetooth audio device

### ISSUE THREAD

**Issue by 7mada123** [jitsi/jitsi-meet#15196]
### What happened?

I am facing the same issue as [14885](https://github.com/jitsi/jitsi-meet/issues/14885), it can be reproduced on the IOS sdk and the last version of the official app on appstore on IOS 18.0.1.
Plus if the selected audio device is bluetooth and the user switch it to speaker or microphone the bluetooth option disappeared

https://github.com/user-attachments/assets/db640422-0191-4a25-9578-d6a3578c365f

**Comment by rheeturajmishra23** [comment]
Any update on this issue ?
