### ISSUE TITLE
Performance settings does not work

### ISSUE THREAD

**Issue by WirelessManWM** [jitsi/jitsi-meet#15192]
### What happened?

Hello! I found this critical bug for me.

The performance settings do not work at all. I don't care about the resolution of the screen share that much, but I am unable to switch to audio-only mode—the stream is still visible. 

![image](https://github.com/user-attachments/assets/9eb958f9-4775-4736-a7a7-e2a08e9e4b0c)

I tried it on all devices through the browser and Android app. On both meet.jit.si and self-hosted versions

Thank you!

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [X] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Version 129.0.6668.90 (Offizieller Build) (64-Bit)

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
What are the steps to get to it?
You are screen sharing, is that right?
The performance settings are what to receive, the low bandwidth mode means I want to receive only audio and screenshares if someone is sharing their screen.

**Comment by WirelessManWM** [comment]
Dear @damencho,
Sorry for the confusing screenshot. 
I tested it with multiple people, and they can't enter audio-only mode.
![SmartSelect_20241013_120526_Chrome](https://github.com/user-attachments/assets/e3902b67-3fe9-4b45-b6d1-bad296fea5fd)
It is easy to recreate this issue. It works in any instance of jitsi, both selfhosted and public one. I just created a meeting on the PC and watched the screen on my phone with audio only enabled. I still see my screen sharing, which should not be the case.

Best regards

**Comment by damencho** [comment]
As I said earlier, this is normal. It is not audio only mode(it used to be called that way, but was renamed), I see it is called in the UI of performance settings - best performance. You are supposed to see screenshare, but not video of other participants. What you are describing is what is expected.

**Comment by WirelessManWM** [comment]
Thank you for explaining. Then, it is a feature that is needed)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
