### ISSUE TITLE
add AI features to jitsi to improve user experience

### ISSUE THREAD

**Issue by hthabti** [jitsi/jitsi-meet#15197]
### What problem are you trying to solve?

current use of jitsi does not allow artificial intelligence features to transcribe meetings and calls and take notes (fireflies, otter...)

### What solution would you like to see?

consideration to integrate artificial intelligence solutions into the jitsi tool such as "fireflies" or "otter"... to improve user experience

**Comment by damencho** [comment]
You can integrate stuff like that. You can use jigasi to transcribe meetings and get transcription chunks via iframeAPI to do client-side AI stuff if you want, or you can forward transcriptions from prosody sending them to some other processing of your choice.
This gives you the flexibility to integrate whatever you want.

**Comment by damencho** [comment]
There is nothing actionable here so I will close it.
Please, when you have questions or problems use the community forum before opening new issues, thank you.
