### ISSUE TITLE
Add something better than opus

### ISSUE THREAD

**Issue by cprkv** [jitsi/jitsi-meet#15190]
### What problem are you trying to solve?

Opus is best encoder in jitsi and it sounds like shit from phone.

### What solution would you like to see?

It is not hard to implement other codecs for you, so implement something like alac (it is free)

### Is there an alternative?

There is also flac codec, and many other high quality codecs. Vorbis is good too. Main problem with high quality codecs is that they could introduce big latency.

**Comment by damencho** [comment]
We use the codecs that are available and supported in the browsers, we do not do any encoding/decoding in jitsi-meet, this is done by the browser. Is that codec available in the major browsers? Is that codec available in the webrtc spec?
You should open tickets in Chromium, Firefox or Safari for that.

> Opus is best encoder in jitsi and it sounds like shit from phone.

I disagree here. Listening to a wideband codec on the phone is the same as on the computer. 
If you are dialing in ... there are different codecs involved and the audio being used is 8kHz, so it cannot be compared to wideband.
