### ISSUE TITLE
didn't redirect to [undefined] 

### ISSUE THREAD

**Issue by mustafasanli0** [jitsi/jitsi-meet#15202]
### What happened?

I am getting an error when i use ?credentialsFor=/xxx redirection doesn't  work
URL: https://8x8.vc/hello?credentialsFor=/hello1
Error:
`didn't redirect to [undefined], reason: Failed to construct 'URL': Invalid URL`

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

https://8x8.vc

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
> ?credentialsFor=/xxx redirection doesn't work

There is no such feature, what are you trying to do?

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
If you are a jaas user, open a support ticket. Thank you.
