### ISSUE TITLE
There is no translation of the save button in Russian.

### ISSUE THREAD

**Issue by lMorpheil** [jitsi/jitsi-meet#15208]
### What happened?

There is no translation of the save button in Russian.

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [X] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Версия 130.0.6723.58 (Официальная сборка), (64 бит)

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Translations are contribution based, so if you have missing translations in your language you can create a PR with those translations. More information you can see at https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md.

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
Thank you
