### ISSUE TITLE
Adding Heart Reaction 💖

### ISSUE THREAD

**Issue by elucidator8918** [jitsi/jitsi-meet#15211]
### What problem are you trying to solve?

To enhance the experience and functionality of our platform, we aim to make it more closely resemble Google Meet.

### What solution would you like to see?

Adding the 💖 reaction in the Reaction pane makes reactions friendlier for everyone worldwide.

**Comment by hamzamehmood67** [comment]
I want to work on this issue!

**Comment by elucidator8918** [comment]
@matehat @jcfischer can you assign the issue to @hamzamehmood67?

**Comment by damencho** [comment]
We are not assigning any issues. If you are willing to make the change, then just open a PR.
