### ISSUE TITLE
Just a little typo in swedish

### ISSUE THREAD

**Issue by fueleh** [jitsi/jitsi-meet#15212]
### What happened?

https://github.com/jitsi/jitsi-meet/blob/3d85202987aeaf5de9466db0d79bd464117c3d67/lang/main-sv.json#L157

"maxEnabledResolution": "Sänd maxiamlt",
should be
"maxEnabledResolution": "Sänd maximalt",

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

All

### Relevant log output

```shell
https://github.com/jitsi/jitsi-meet/blob/3d85202987aeaf5de9466db0d79bd464117c3d67/lang/main-sv.json#L157

"maxEnabledResolution": "Sänd maxiamlt",
should be
"maxEnabledResolution": "Sänd maximalt",
```

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Translations are community based. If you want to fix those or add translations create a PR.
More information you can find at https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md
