### ISSUE TITLE
[iOS][videoconferencing] - French Labels - Consistent Capitalization Issues

### ISSUE THREAD

**Issue by Rabeb-Ch** [jitsi/jitsi-meet#15224]
### What happened?

I would like to report some inconsistencies in the French localization. Specifically, several phrases (button titles) use capital letters where they should not. Here are the details:

1. Home page screen /Waiting room:
"Rejoindre La Réunion" should be "Rejoindre la réunion" (lowercase "la réunion").

2. Chat and Polls screen:
"Créer Un Sondage" should be "Créer un sondage" (lowercase "un sondage").

3. Participants screen:
"Couper Le Micro De Tout Le Monde" should be "Couper le micro de tout le monde" (lowercase "le micro de tout le monde").

These changes will improve consistency with standard French capitalization rules. Thank you for considering this!

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

JitsiMeetSDK 10.1.2

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by Nader-Khedhri** [comment]
Hello, Any updates ?

**Comment by damencho** [comment]
https://community.jitsi.org/t/jitsi-localization-french/134987/4?u=damencho

**Comment by damencho** [comment]
That is expected.

**Comment by Calinteodor** [comment]
Sorry for misleading here. It seems that we no longer need to force capitalise button labels on our end. 
There were some issues in the past with react native paper button component label, but right now it seems that is fixed.
