### ISSUE TITLE
Focus Mode For Jitsi

### ISSUE THREAD

**Issue by aquariusmike** [jitsi/jitsi-meet#15228]
### What problem are you trying to solve?

I'm searching if Jitsi has something similar in Zoom called focus mode which is used to make participants only available for hosts and co-hosts and participants can't see each other.

### Is there an alternative?

add sticker or something for iframe api? I would like to hide participants face to can't see each others for security reasons.

**Comment by saghul** [comment]
We don't have plans to implement such a feature, sorry.

**Comment by jamesgreen-moj** [comment]
@saghul This feature would be really useful for us, is there any way I can upvote it? Or request this feature?
