### ISSUE TITLE
Skip the mobile app promo

### ISSUE THREAD

**Issue by davidmoreno** [jitsi/jitsi-meet#15233]
### What problem are you trying to solve?

Currently it's possible to disable the app promo on mobile by setting `MOBILE_APP_PROMO=false` but this disables the full jitsi meet with a "mobile not supported" screen.

### What solution would you like to see?

To allow to skip this screen when set `MOBILE_APP_PROMO` interface config to `false`. This would mean a change of behaviour, but I think it would be a better behaviour than actually, as it does work on all current mobile browsers, or at least all I tried.

### Is there an alternative?

I just compiled my own version, commenting the lines 72-80 at `react/features/deep-linking/funcitons.ts`. The patch should be straight forward change the if to do the current behaviour on undefined, but just return the `_openDesktopApp` call on false.

**Comment by damencho** [comment]
> Works perfectly! Thanks! Still I think the other interface_config.js is a bit confusing, but problem solved!

https://github.com/jitsi/jitsi-meet/blob/b562176062cb6ebc3e53ec3138d0b17651666513/interface_config.js#L7
