### ISSUE TITLE
 "Transcribing Failed" : Issue with Subtitles / Captions in Hosted Jitsi Meet Public Instance #262 

### ISSUE THREAD

**Issue by candideu** [jitsi/jitsi-meet#15247]
### What happened?

I've used the public Jitsi Meet a few times, but was looking for a simple way of transcribing my meetings and offer captions. 

I learned today that it's possible to turn on Subtitles on https://beta.meet.jit.si:

![image](https://github.com/user-attachments/assets/07b25538-8ed7-438d-8b23-cc007379bea7)

The function didn't work when I turned it on and spoke into the mic on Firefox, but it did when I used a Chromium-based browser and spoke. When speaking from a Chromium browser, the captions were displayed for the other Jitsi participants (I tested on Win10 Firefox, Win10 Chromium, and Android Firefox simultaneously).

However, after a few minutes of testing, the subtitles text turned off by itself on all the participants, and I got an error saying that the transcription failed:

![Screenshot_20241029-125841](https://github.com/user-attachments/assets/aa51a887-da1d-4542-8ef7-73fb4efd717a)

Anyway, I was excited to give this a try because many third-party transcription options don't work with Jitsi... I've tried all of the following apps unsuccessfully, and put in Jitsi integration feature requests:

- Fireflies
- OtterPilot
- Tactiq
- Krisp.ai
- Notta Bot
- Meeting Baas Trancript Seeker
- Speechnotes
- Reduct.video

I don't have the skills or time to self-host Jitsi + Jigasi, and even the 8x8 Jitsi-as-a-Service seems to involve some level of self-hosting and dev skills.

I simply want an easy way of offering live captions and/or transcripts for my Jitsi meeting participants, without having to self-host or set up JWT tokens.

I'm willing to pay for captions/subtitles as an add-on in the public instance, but there doesn't seem to be an intermediary service between the public Jitsi Meet instance and the enterprise 8x8 JaaS solutions for people looking for privacy-friendly and open-source Zoom and Google Meet alternatives...

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chromium

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
You can use jaas and have subtitles or self host, these are your options. Beta is used for testing and we had subtitles for a bit today while testing something and probably that's why you saw the error.

We will not offer subtitles on meet.jit.si due to its cost and meet.jit.si is a free service.

You can transcribe any audio on android devices for free.

**Comment by candideu** [comment]
Hopefully, someone out there is able to offer a paid, easy-to-use hosted Jitsi service which offers captions out of the box... The need is certainly there.

**Comment by damencho** [comment]
There is no actionable item for this project, jitsi-meet already supports captions. So I will close the ticket. 

Please, when you have questions or problems use the community forum before opening new issues, thank you.
