### ISSUE TITLE
Start transcription on all rooms by default

### ISSUE THREAD

**Issue by baminou** [jitsi/jitsi-meet#15257]
### What problem are you trying to solve?

Over the last days, I have been trying to figure out a way to have the captions activated by default with Jigasi. I don't want users to have to go under the more settings to activate the captions. Is it possible to do that? I don't see anything about that in the documentation.

### What solution would you like to see?

I would like a setting to start with the captions ON instead of the captions OFF.

**Comment by damencho** [comment]
Nope, there is no such option. The first one to invite jigasi needs to be a moderator. 
You can use the iframeAPI where the first moderator invites jigasi and the rest when jigasi is in the meeting (when transcribingStatusChanged) they can turn on captions again using the iframeAPI.

**Comment by baminou** [comment]
I don't have the best understanding of Jitsi at the moment, but would it be possible to create a lua module to do that? I am trying to work on one at the moment, but I am not sure if it's going to work.

**Comment by damencho** [comment]
Nope, you need a moderator to invite jigasi, sending an xmpp IQ to jicofo. 
Your best bet is the option I described above with iframeAPI. 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

**Comment by baminou** [comment]
Thank you! This is helpful!

**Comment by damencho** [comment]
As there is nothing to be done for jitsi-meet, I will go and close the issue. 

Please, when you have questions or problems use the community forum before opening new issues, thank you.
