### ISSUE TITLE
Firefox crashes when trying to use sound setting shortcut

### ISSUE THREAD

**Issue by Thatoo** [jitsi/jitsi-meet#15262]
### What happened?

On Firefox 131 or Firefox dev 132 (on NixOS 24.11), going to Jitsi (including meet.jit.si), if I click on the shortcut to change sound setting, this firefox tab freeze and crashes.

![image](https://github.com/user-attachments/assets/b3a81d04-e47c-424d-bc31-e98dc3a496b0)

![image](https://github.com/user-attachments/assets/e999e5ca-f773-4f75-978c-7893ce849885)

### Platform

- [ ] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

131

### Relevant log output

```shell
La mise en page a été forcée avant le chargement complet de la page. Si les feuilles de style ne sont pas encore chargées, cela peut provoquer un flash de contenu non stylisé. markup.js:250:53
```

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
If a website crashes the browser it's a browser bug, can you please report it to Firefox?

**Comment by Thatoo** [comment]
I did first, but as Firefox works fine for everything else except this button, the issue might also come from the software that provide this button I guess.

**Comment by saghul** [comment]
It's a browser problem.

**Comment by saghul** [comment]
The browser provides a JS sandbox. If there is a bug in there it may cause a crash, but there is nothing we can do about it.
