### ISSUE TITLE
Jitsi Video Enabled by Default not working 

### ISSUE THREAD

**Issue by lvxhnat** [jitsi/jitsi-meet#15261]
### What happened?

I am using the following code

```
import { JitsiMeeting } from "@jitsi/react-sdk";

<JitsiMeeting
            domain="videocall.sentioweb.com"
            roomName={props.roomName}
            configOverwrite={{
              startWithAudioMuted: false, 
              startWithVideoMuted: false, 
              disableModeratorIndicator: true,
              startScreenSharing: true,
              enableEmailInStats: false,
            }}
            interfaceConfigOverwrite={{
              DISPLAY_WELCOME_FOOTER: false,
              VIDEO_LAYOUT_FIT: "both",
              MOBILE_APP_PROMO: false,
              TILE_VIEW_MAX_COLUMNS: 4,
              DISABLE_JOIN_LEAVE_NOTIFICATIONS: true,
              DEFAULT_WELCOME_PAGE_LOGO_URL: "",
            }}
            getIFrameRef={(iframeRef: any) => {
              iframeRef.style.height = "100%";
              iframeRef.style.width = "100%";
            }}
          />
```

this line `  startWithVideoMuted: false, ` should enable my video by default, but it starts off disabled. The `startWithAudioMuted` works (audio enabled by default) but not video. why is that?

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

1.4.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Have you tried loading in incognito, does it work there?

**Comment by lvxhnat** [comment]
@damencho I have tried Incognito, it doesnt work either. I see in the console logs this line
2024-11-01T16:15:56.329Z [modules/RTC/RTCUtils.js] <Mr.<anonymous>>:  Got media constraints:  {"video":false,"audio":{"autoGainControl":true,"echoCancellation":true,"noiseSuppression":true}}

**Comment by damencho** [comment]
Do you have video permissions allowed?

**Comment by saghul** [comment]
I think it might be a bad interaction with start screen sharing.

You should disable it because it's deprecated as the permissions model doesn't work anymore in all browsers and eventually won't work on any of them.

**Comment by lvxhnat** [comment]
Removed `startScreenSharing: true,` and it works now. Thank you!

**Comment by lvxhnat** [comment]
Removed startScreenSharing: true, and it works now. Thank you!

**Comment by damencho** [comment]
@saghul we need to 🔥 that option :)

**Comment by saghul** [comment]
Let's 🔥 it!!

**Comment by damencho** [comment]
startScreenSharing is used by spot.

**Comment by saghul** [comment]
Argh. And it will work there because it's special... At least we can undocument it from everywhere and remove it from any API.
