### ISSUE TITLE
Jitsi Meet prejoinPageEnabled false still requires join meeting click

### ISSUE THREAD

**Issue by lvxhnat** [jitsi/jitsi-meet#15265]
### What happened?

I have a jitsi component that looks like this 

```
<JitsiMeeting
            domain="...."
            roomName="test-room"
            userInfo={{
              displayName: "test",
              email: "test@gmail.com",
            }}
            configOverwrite={{
              prejoinPageEnabled: false, 
            }}
            interfaceConfigOverwrite={{
              DISPLAY_WELCOME_FOOTER: false,
              VIDEO_LAYOUT_FIT: "both",
              MOBILE_APP_PROMO: false,
              TILE_VIEW_MAX_COLUMNS: 4,
              DISABLE_JOIN_LEAVE_NOTIFICATIONS: true,
              DEFAULT_WELCOME_PAGE_LOGO_URL: "",
            }}
            onReadyToClose={() => console.log('Jitsi Meeting ready to close')}
            getIFrameRef={(iframeRef: any) => {
              iframeRef.style.height = "100%";
              iframeRef.style.width = "100%";
            }}
          />
```

right now, what I am trying to achieve is for this component to immediately join an existing meeting without the need to click the "Join Meeting" button.

I can see that the default room name and user name is filled in as expected, however, the component still renders with the prefilled name with the join meeting button, see below:
![Screenshot 2024-11-02 at 10 55 54 PM](https://github.com/user-attachments/assets/cc83dbbc-8b14-4c5d-8523-96356f572ab9)

How can I immediately start the meeting when it is rendered?

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

1.4.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
That has been removed use this one:
https://github.com/jitsi/jitsi-meet/blob/afac97e7d48ad43ef55668cc00c44808670335fc/config.js#L754

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
