### ISSUE TITLE
When user with the "moderator" role in mobile browser, the end meeting button do not work

### ISSUE THREAD

**Issue by uyoufu** [jitsi/jitsi-meet#15288]
### What happened?

When user with the "moderator" role in mobile browser, the end meeting button do not work

https://github.com/user-attachments/assets/a47f1fc1-cbca-4f03-ae67-a11747c2a1ad

In mobile browsers, any user who is assigned the moderator role cannot end the conference. 

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [X] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

docker stable-9779

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
@mihhu Can you PTAL?

**Comment by shawnchin** [comment]
Possibly same issue as this? https://github.com/jitsi/jitsi-meet/issues/15273

**Comment by mueed-hasan** [comment]
In interface_config.js set TOOLBAR_ALWAYS_VISIBLE: true ..it will be solved
