### ISSUE TITLE
jitsi meet won't prompt for password

### ISSUE THREAD

**Issue by alevoski** [jitsi/jitsi-meet#15281]
### What happened?

Hi,

I just did an install from scratch of jitsi meet following your tutorials.
Everything was working great until I tried to enable access control (https://jitsi.github.io/handbook/docs/devops-guide/secure-domain/).

Now, when I create a new meeting, it does not ask to authenticate, instead it shows an error message "Unfortunately, something went wrong...Reconnecting in n sec...".

See logs attached :
[jvb.log](https://github.com/user-attachments/files/17664041/jvb.log)
[jicofo.log](https://github.com/user-attachments/files/17664044/jicofo.log)
[prosody.log](https://github.com/user-attachments/files/17664046/prosody.log)

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Brave Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit)

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
What is the error you see in the js console logs.

**Comment by alevoski** [comment]
Here are the console logs from the client side :
[meet.ingeservice.lan-1730999089146.log](https://github.com/user-attachments/files/17666965/meet.ingeservice.lan-1730999089146.log)

**Comment by damencho** [comment]
```
moderator.js:309 2024-11-07T17:13:26.325Z [modules/xmpp/moderator.js] Sending conference request over XMPP to focus.meet.ingeservice.lan
moderator.js:487 2024-11-07T17:13:26.394Z [modules/xmpp/moderator.js] <hc._handleError>:  Failed to get a successful response, giving up.
```
There is a problem with jicofo, it is not responding to conference requests. 

Fix your jicofo config first and see whether it logins correctly. Have you looked at jicofo logs at all?

```
Jicofo 2024-11-07 16:18:14.918 SEVERE: [1] Main.lambda$main$0#50: An uncaught exception occurred in thread=Thread[main,5,main]
java.lang.ExceptionInInitializerError
	at org.jitsi.jicofo.Main.main(Main.java:58)
Caused by: com.typesafe.config.ConfigException$Parse: /etc/jitsi/jicofo/jicofo.conf: 25: expecting a close parentheses ')' here, not: end of file

```

**Comment by alevoski** [comment]
I must be tired, it was in front of my eyes.. The problem was indeed in jicofo.conf.
Everything work fine now.

Thank you very much !

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
