### ISSUE TITLE
Screensaver with a time and music before the start

### ISSUE THREAD

**Issue by jefry7** [jitsi/jitsi-meet#15289]
### What problem are you trying to solve?

 check the equipment

### What solution would you like to see?

is it possible to make a screensaver with a timer and music before the start of the conference so that participants have the opportunity to check the equipment?

### Is there an alternative?

demonstration of a separate page with a website that shows the time and timer

**Comment by saghul** [comment]
The pre-join screen already accomplishes that. We have no plans to add music or a screen saver, but you could that in an iframe of your own when integrating Jitsi Meet.

**Comment by jefry7** [comment]
This solves only part of the problem. I meant the problems with the broadcast. Ports are closed, or something else like that

**Comment by jefry7** [comment]
This is often done in webinars

**Comment by saghul** [comment]
If configured a pre-join test can run while the user is waiting. That would detect network problems.

**Comment by jefry7** [comment]
Can I have a little more detail? where is it configured?

**Comment by saghul** [comment]
See https://github.com/jitsi/jitsi-meet/blob/86d1bd3c7804aa894ecf111a0ae68143fe227281/config.js#L764 You need to configure a TURN server there.
