### ISSUE TITLE
Duplicate participation of Chromium-based browsers

### ISSUE THREAD

**Issue by Inperpetuammemoriam** [jitsi/jitsi-meet#15286]
### What happened?

A conference participant using a Chromium-based browser joins twice if the conference is joined from a lobby before the devices have been configured.

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome 130.0.6723.117/Edge 130.0.2849.80

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

This has been tested on a [Docker](https://github.com/jitsi/docker-jitsi-meet)-based installation running the release [stable-9646](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-9646) of Jitsi Meet.

In order to reproduce the described behavior, the conference page can be reloaded followed by a rapid submission of the form displayed in the lobby using the ENTER key.

**Comment by damencho** [comment]
That was recently fixed. You can update to https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md#209823-2024-11-11, the docker images will be out in a few hours or tomorrow.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/commit/960a08c0663c63d4ddcc8d7100f6bfc509ee0913
