### ISSUE TITLE
Debian package signature problem

### ISSUE THREAD

**Issue by geroldr** [jitsi/jitsi-meet#1528]
Error message when updating repository is as follows:
W: GPG error: http://download.jitsi.org/deb unstable/ Release: The following signatures were invalid: 040F57608F84BAF1BF844A62C697D823EB0AB654
W: The repository 'http://download.jitsi.org/deb unstable/ Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

**Comment by damencho** [comment]
Do not use that repo, it is an old one and not used anymore. Where did you take that link from? 
Use those described here: https://github.com/jitsi/jitsi-meet#download
