### ISSUE TITLE
Admin panel with statistics

### ISSUE THREAD

**Issue by jefry7** [jitsi/jitsi-meet#15290]
### What problem are you trying to solve?

Speeding up the identification of problems and the search for solutions in conferences.
As well as centralized monitoring of the service status

### What solution would you like to see?

Is it possible to make a page that displays all the rooms and the participants in the? And also for each participant his condition? Is there an audio/video transmission and at what speed? From which ip to which ip and which ports?

### Is there an alternative?

I don't know

**Comment by saghul** [comment]
You can take a look at this: https://github.com/jitsi/docker-jitsi-meet/tree/master/prometheus
