### ISSUE TITLE
Make Developer Built .apk's Available on Github?

### ISSUE THREAD

**Issue by DiagonalArg** [jitsi/jitsi-meet#15295]
### What problem are you trying to solve?

I wonder if the team might consider making .apk's available here on github.  A number of us run GrapheneOS with [Obtainium](https://github.com/ImranR98/Obtainium).  That allows us to use developer signed packages directly from github or other developer websites, which is preferable to those signed by f-droid.

### What solution would you like to see?

.apk's published here.

**Comment by saghul** [comment]
We don't have the time bandwidth or desire to add more build artifacts, sorry.

**Comment by DiagonalArg** [comment]
I gather there are automated ways to do this on github.  

My use of Obtainium is not ideosyncratic.  Until [Accrescent](https://accrescent.app/) is out of beta, which may be a while, Obtainium is the default direct-from-dev app store for those of us concerned with security.

**Comment by saghul** [comment]
It's not that simple, because we use Google managed keys due to some historical reasons.
