### ISSUE TITLE
I install and deploy successful,can text chat with others,but no video and voice

### ISSUE THREAD

**Issue by Jokder** [jitsi/jitsi-meet#1530]
hi,I installed and deployed jitsi-meet with this guid https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
and everything works ok,and i can type text with others,but no video and voice.
here is my site:https://meet.icephenix.com
and how should i know how to trace and find where the problem caused?

**Comment by damencho** [comment]
If you open chrome://webrtc-internals/ you can see the remote description coming from jicofo/jvb that there is no public address in the description, just the internal addresses.
You need to configure in your jvb the public and private addresses and make sure you forward ports to jvb 10000 udp, and tcp 4443 or 443 (depending whether you are using jvb's jetty to serve meet or nginx is serving it and then jvb binds by default to 4443).
Take a look at: https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#mapping-harvesters

**Comment by Jokder** [comment]
thanks,finally i build everything from source .
