### ISSUE TITLE
Mobile Jitsi-meet app useless conference owner

### ISSUE THREAD

**Issue by gradinaruvasile** [jitsi/jitsi-meet#1533]
If you happen to join a conference from the mobile app first, it becomes the owner.
But it cannot fulfill the role because the UI does not have the options to kick people, set passwords etc. 
The mobile app should be prevented to become owner until the mobile UI will have all the needed functions.

**Comment by lyubomir** [comment]
@gradinaruvasile, when you said "set passwords", did you mean locking the room? I'm asking because the mobile app is able to (1) lock a room and (2) join a locked room. Did you have a different experience?

**Comment by gradinaruvasile** [comment]
Related to passwords: I looked at it and there is an issue with the action button overlay (buttons are transparent most of the time, need another issue for that) and i missed the option to set passwords.
But how can you kick people or set default conference details such as start hidden etc?
Also there is no chat support which can be an issue if someone has audio problems.

**Comment by saghul** [comment]
> I looked at it and there is an issue with the action button overlay (buttons are transparent most of the time, need another issue for that) and i missed the option to set passwords.

Buttons are not transparent. We have seen some rendering problems in some Android devices in the past. What device are you using? A screenshot would be helpful.

> But how can you kick people or set default conference details such as start hidden etc?

That is not yet implemented in the mobile apps.

> Also there is no chat support which can be an issue if someone has audio problems.

Also not implemented. The mobile apps are being actively worked on now, but they are not on par feature wise.

**Comment by gradinaruvasile** [comment]
Some screenshots. Sometimes the buttons on the right are not visible, sometimes the main 3 buttons too show up cropped. Sometimes all are visible.
Device is Alcatel Idol 3 (4.7" version) with Android 5.0.2 (the 6.0 upgrade is not available on it yet, it is carrier locked).

![screenshot_2017-04-24-12-50-51](https://cloud.githubusercontent.com/assets/16729939/25476594/57e33614-2b43-11e7-9bb8-0de3486e7735.png)
![screenshot_2017-04-24-12-57-20](https://cloud.githubusercontent.com/assets/16729939/25476595/57e3b5b2-2b43-11e7-900a-da6718b389c3.png)

**Comment by saghul** [comment]
Thanks for confirming. I have seen this issue on a Moto X Play running Android 7.1, so it doesn't seem to be strictly related to the Android version...

**Comment by saghul** [comment]
We added a fix for the buttons not showing which will be part of the next (1.8) release.

**Comment by dearjulian** [comment]
Hello!
Where can I find instructions on how to use Jitsi Meet on the Web (Windows)?
I'm interested e.g. in moderation functions.

**Comment by gradinaruvasile** [comment]
The video buttons not showing are solved by some of the recent releases. I used the app recently and everything was ok, even after device rotation.

**Comment by saghul** [comment]
@gradinaruvasile Yep, thanks for confirming!
