### ISSUE TITLE
Set Lobby as default for new rooms with support of JWT auth

### ISSUE THREAD

**Issue by DimitryVo** [jitsi/jitsi-meet#15346]
### What problem are you trying to solve?

Hello, could you recommend anything for set lobby by default for new rooms with JWT auth (KeyCloak)? I have tried to use prosody-plugins [lobby_autostart](https://github.com/jitsi-contrib/prosody-plugins), but I cant't login as moderator (first user of room) because I see knock offer. 

### What solution would you like to see?

I need some config option or module for autostart lobby for room with possibility login by moderator (first user of room).

**Comment by DimitryVo** [comment]
Hello, thank you for you answer. I have installed [bypass lobby based on token attributes](https://github.com/jitsi-contrib/prosody-plugins/blob/main/token_lobby_bypass) with [jitsi-keycloak-adapter-v2](https://github.com/nordeck/jitsi-keycloak-adapter-v2) but result is absent. Could you recommend anything?

**Comment by saghul** [comment]
I recommend you ask in the repo for those plugins. They are community maintained.
