### ISSUE TITLE
When moderator mute all he cannot unmujte all or anyone also 

### ISSUE THREAD

**Issue by KarimElhedaby** [jitsi/jitsi-meet#15349]
### What happened?

When moderator mute all he cannot unmute all or anyone also  .. I think he as a moderator he should has the ability to unmute who he need 

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [X] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

10.0.0

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
That would have huge privacy implications.

The moderator can _request_ a user to unmute themselves.
