### ISSUE TITLE
Add numbers to raised hands 

### ISSUE THREAD

**Issue by netFLOw95** [jitsi/jitsi-meet#15343]
### What problem are you trying to solve?

It is not very intuitive or easy to recognize that the participants are sorted by "Raised hands".

### What solution would you like to see?

Adding numbers would make the order easier to see.
Example:
![image](https://github.com/user-attachments/assets/724879ba-1f02-4c1c-b4fc-44c7a6a536fb)

**Comment by saghul** [comment]
The number doesn't really add much, other than visual clutter. I'm sorry but this is not a change we can make.

**Comment by netFLOw95** [comment]
Thanks for the quick response. Just that you got me right: For those who know that the participants are ordered according to "Raised hands", I fully agree. But I think many people don't know that feature respectively are not aware that the participants are ordered and then the numbers would help to kind of "recognize that feature".

**Comment by saghul** [comment]
Yes, I understood what you meant :-)

The train of thought here is that in most cases it's not relevant to the user, and for those who are interested, it's easy to discover, as people raise / lower hands.
