### ISSUE TITLE
localRecording : not possible in firefox ? Button not present

### ISSUE THREAD

**Issue by tomdereub** [jitsi/jitsi-meet#15351]
### What happened?

I modified my config.js to add localRecording : 
```
    localRecording: {
       // Whether to disable local recording or not.
       disable: false,

       // Whether to notify all participants when a participant is recording locally.
       notifyAllParticipants: true,

        // Whether to disable the self recording feature (only local participant streams).
        disableSelfRecording: false,
    },
```
It works on chrome, but not on firefox, there is no button "start recording" : 
On chrome : 
![image](https://github.com/user-attachments/assets/f59aa57d-6786-4e84-85d9-9b3f436f6a64)

On Firefox : 
![image](https://github.com/user-attachments/assets/31c333bd-79c9-4dbd-a040-0978ba074463)

Is there a plan to get it work on firefox ?

### Platform

- [ ] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Firefox 133.0 (64 bits)

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Alas it's not possible, since Firefox does not allow tab sharing.

**Comment by saghul** [comment]
I'm afraid we don't have such a list.

**Comment by tomdereub** [comment]
Issue open on firefox's side : https://bugzilla.mozilla.org/show_bug.cgi?id=1934833
I let you decide if you prefer to close this ticket or to keep it open to keep this in mind until firefox's team corrects it.
