### ISSUE TITLE
How can I use port 8443 and SSl ? How can I config?

### ISSUE THREAD

**Issue by huashuiwujiale** [jitsi/jitsi-meet#15356]
### What happened?

![image](https://github.com/user-attachments/assets/ee83fab1-332f-4e7a-953d-7105b0bd5f2b)

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

1

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
I suppose you mean SSL? Do you have a valid certificate?
