### ISSUE TITLE
"Oh! SnaP!" error on Chrome 58

### ISSUE THREAD

**Issue by webintoit** [jitsi/jitsi-meet#1537]
Hi guys. 
meet.jit.si instance crashes with "oh snap" error with chrome 58. I was test this on 3 different machines.
It also repeatable with custom instances, that using jvb. (https://beta.talky.io/). 
My custom app uses ljm + jicofo + jvb , and it also crashes my browser. 
![pasted image at 2017_04_25 09_41 am](https://cloud.githubusercontent.com/assets/5518513/25376092/ada803d4-29ab-11e7-8b2e-cd5856f60770.png)
![image](https://cloud.githubusercontent.com/assets/5518513/25376272/39880502-29ac-11e7-9dc0-51bdeab81fbb.png)

**Comment by saghul** [comment]
See https://bugs.chromium.org/p/webrtc/issues/detail?id=7505, it seems to be the culprit and @bbaldino reported it, hopefully there is a fix available soon :-S

**Comment by webintoit** [comment]
Thanks. I will disable simulcast for some time) 
![image](https://cloud.githubusercontent.com/assets/5518513/25378090/fcb63db4-29b1-11e7-90d0-0a19514fc337.png)
