### ISSUE TITLE
We recommend to try with the latest version of Chrome or Chromium

### ISSUE THREAD

**Issue by gentryhuang** [jitsi/jitsi-meet#15384]
### What happened?

![jitsi-error](https://github.com/user-attachments/assets/800f2be4-c9db-4c52-8794-4034a8010d9a)
Google Chrome is the latest version, but the version is still low! Jitsi version is "stable-7439".
Asking for help. Thank you very much!

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

131.0.6778.109

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Your Jitsi Meet version is over 2 years old! You need to update.
