### ISSUE TITLE
The whiteboard is accessible by other participants

### ISSUE THREAD

**Issue by alikhancherli** [jitsi/jitsi-meet#15394]
### What happened?

Hi dears,
I have been deploying the JITSI including the whiteboard feature but there's an issue.
When I toggle the whiteboard in moderator side, all participants can edit the moderator's whiteboard and I do now want this. Only moderator should be able to open whiteboard and draw. Actually, participants just have to see the details.

### ENV :
```
WHITEBOARD_COLLAB_SERVER_URL_BASE=http://whiteboard.meet.jitsi
WHITEBOARD_COLLAB_SERVER_PUBLIC_URL=https://localhost:PORT
```

### Config : 
```
const options = {
                        ...,
                        configOverwrite: {
                            ...,
                            lobby: {
                                autoKnock: true,
                                enableChat: false,
                            },
                            securityUi: {
                                hideLobbyButton: true,
                                disableLobbyPassword: true,
                            },
                            breakoutRooms: {
                                hideAddRoomButton: true,
                                hideAutoAssignButton: true,
                                hideJoinRoomButton: true
                            }
                        }

```
### Deploy instructions :
`docker compose -f docker-compose.yml -f whiteboard.yml up -d --force-recreate
`

Everything is working but I'm currently working on this issue.
Please help
Thanks, Ali

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

jitsi version 9823

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
This is by design, everyone is allowed to draw. The moderator needs to start it.

**Comment by alikhancherli** [comment]
Thanks for help.
