### ISSUE TITLE
Config InviteDomain does not apply

### ISSUE THREAD

**Issue by khoaakt** [jitsi/jitsi-meet#15425]
### What happened?

I'm self hosting my Jitsi instance and want to change some configuration to match my needs. 
However, I can't change the invite domain on Jitsi Web UI even I modified the config inside /etc/jitsi/meet.

Here is a screenshot:
![image](https://github.com/user-attachments/assets/1b5ac8f9-b374-4793-9ac4-6ca8aa3b1621)

The config already changed, but the Jitsi Meet UI still show the original "conference.mydomain" URL.

Output of dpkg Jitsi
![image](https://github.com/user-attachments/assets/66b925e3-4a75-4ac9-9734-f78a443faaf9)

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome 131 / Jitsi Meet 2.0.9909-1

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
That is a field that needs to be used with dynamic-branding, you do not set it in config.js directly:
https://github.com/jitsi/jitsi-meet/blob/174c4418fbc008bceec32adf8e457926ce4a980b/config.js#L1423

Here is an example of how to use it: https://community.jitsi.org/t/customize-outlook-email-invitation/128511/5?u=damencho

Please, when you have questions or problems use the community forum before opening new issues, thank you.
