### ISSUE TITLE
Support for deployments with self-signed certificates

### ISSUE THREAD

**Issue by hzsdu2016** [jitsi/jitsi-meet#1544]
when I give the full URL of my own server in the room text field, it show like this:
![image](https://cloud.githubusercontent.com/assets/19379762/25552272/8a44c11a-2cc7-11e7-942c-99263f0a8d76.png)
Do my server deployment have some errors ?  how to change the source code if I want to change the server in source code?

**Comment by saghul** [comment]
Does your server have a valid TLS certificate? It must, otherwise an error such as the one you got will be produced.

**Comment by lizhaoch** [comment]
I‘ve’ created a  QQ group ， groupid:638328355 
welcome join and discuss!

**Comment by lizhaoch** [comment]
[//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7](url)

**Comment by lizhaoch** [comment]
We apply for the certificate in starssl @saghul

**Comment by lizhaoch** [comment]
I‘ve’ created a QQ group ， groupid:638328355
welcome join and discuss!
[//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7](click to join)

**Comment by lizhaoch** [comment]
I‘ve’ created a QQ group ， groupid:638328355
welcome join and discuss!
[//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7](url)

**Comment by arminfelder** [comment]
I think this is the same issue, as mentioned here: https://github.com/jitsi/jitsi-meet/issues/1251

**Comment by haofanning** [comment]
Did it solved?

**Comment by saghul** [comment]
Sort of. We now support using certs in the user trust store, so if you add your CA there it should work.
