### ISSUE TITLE
The "videobridge is unavailable" message isn't shown to the focus

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#155]
When the bridge is down, the non-focus participants see a "Jitsi Videobridge is currently unavailable. Please try again later!" message. The focus does not see it.

**Comment by kosmosby** [comment]
hi, follow your instructions and have exactly the same error:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
23:33:23.531 SEVERE: [1] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[main,5,main] and message was: conflict
org.xmpp.component.ComponentException: conflict
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.videobridge.Main.main(Main.java:273)

please help.

**Comment by sheaw** [comment]
is there a way to auto-start this ?

it seems when i run it from my terminal, the bridge fails as soon as i log out.  is there a way to execute as a start-up script ?

**Comment by bgrozev** [comment]
Locking the issue, as we are still receiving unrelated comments. The original problem (where the error message was *not* shown, in a case where it should have been shown) has long been fixed, and it is unlikely to appear again because we are not using the JS focus anymore.
