### ISSUE TITLE
cannot load "/config" from https//URL

### ISSUE THREAD

**Issue by lizhaoch** [jitsi/jitsi-meet#1550]
I used the starssl certificate issued, but the ios has been an error like :
cannot load "/config" from "https://********^&(&.com/abc?^^*"

I don't know why，please help me @yanas  @all creater master
======================magic parting line=============================
I've use jitsi for nearly 10 months,now i 've try use it on IOS , and then  a big wave problem comes...
jitsi is a very good video framework，and it grow quickly， I want to promote this technology in China,
so  I created a QQ group for jitsi-meet in China ， groupid:638328355
IM:QQ (U can google it)
welcome join and discuss the R&D about JITSI !
//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7

**Comment by geekgonecrazy** [comment]
I'm not sure why you've mentioned me in two of your comments... Not part of the jitsi team ;) So I won't have any answers for you

**Comment by lizhaoch** [comment]
I'm sorry, just wrong @ibc  @geekgonecrazy

**Comment by ibc** [comment]
Please, don't open an issue in GitHub. Instead use the mailing list. And please NEVER mention other users just to force them into the issue. Don't do that please.

**Comment by damencho** [comment]
Hey @ibc till recently I was pointing everybody to the mailinglist :) But all devs agreed to stop that. And yesterday we removed the description of this policy from README, sorry for not announcing it.

**Comment by SlamDunkDcc** [comment]
@ibc Why must use mailing list?

**Comment by bug4code** [comment]
I have the same question, please help me, it's important for me! Help! Help! Thanks @damencho

**Comment by saghul** [comment]
Do you have a publicly available deployment we can test against?
