### ISSUE TITLE
Configuration: host name on local network?

### ISSUE THREAD

**Issue by ttoine** [jitsi/jitsi-meet#1553]
I am trying to install and run Jitsi Meet on a local network. So I don't have a FQDN or a domain name, just the IP address of the server (x86, I install using apt-get). Jitsi Meet will be the only web service running on this machine.

And I can't make it to work: when the installation is finished and I browse the IP address from an other computer, I get the default Nginx html page. 

What should I put in the configuration for "hostname"? I tested with the name of the server on the network but this is not working. Should I use the IP adress? or create vhost with a different port so Nginx can point to the right vhost instead of default? What would you recommend?

All the documentation I can find about Jisti use a FQDN. That's why I am asking.

**Comment by ttoine** [comment]
I tested with the IP address, it's working, but this is an issue in case it changes.

Two questions:
- Is there a configuration that would work even if the IP address changes?
- Is there an easy way to update it so it works without breaking everything? (like just in the vhost configuration of nginx?)

**Comment by lizhaoch** [comment]
In my experience , U can modify the host, like:   video.mine.com  127.0.0.1;;

**Comment by damencho** [comment]
If you have setup everything using an ip-address and it is working on the same machine. 
If you want to change the dns/ipaddress to access it, you only need to mess with nginx config.
You need to make sure that virtual host works and the only tricky change is make sure on this line:
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L46
You change the parameter from $http_host to the initial ip address you configured it.
