### ISSUE TITLE
cannot get jitsi-meet working - website starts but no camera / no focus etc

### ISSUE THREAD

**Issue by ranweb** [jitsi/jitsi-meet#1554]
hi!

i tried installing jitsi-meet @ http://conf.shidur.net
but i cannot get it to work for some reason... i even changed the cert keys to letsencrypt using a script but still cannot connect to camera, there is no connection to focus server...

any ideas?!
thanks!!!
ran

**Comment by damencho** [comment]
Check your jicofo logs in /va/log/jitsi/jicofo.log. Are there any errors?
Also make sure you access it using https, http will not work.

**Comment by ranweb** [comment]
Ah ok :) HTTPS does work! why does http work with the meet.jit.si but not with local?

**Comment by ranweb** [comment]
BTW: thanks for the SUPER QUICK response :) 👍

**Comment by damencho** [comment]
http is redirected to https on meet.jit.si. 
https is a requirement for webrtc, loaded on http page it fails to connect to camera or microphone.

**Comment by ranweb** [comment]
Tnx Damencho - I got it working atleast for moderator but it says that the other users have connection issues?? as far as I know - i have no firewall etc:
link: https://conf.shidur.net

any ideas??

**Comment by ranweb** [comment]
Tnx Damencho - I got it working atleast for moderator but it says that the
other users have connection issues?? as far as I know - i have no firewall
etc:
link: https://conf.shidur.net

any ideas??

**Comment by damencho** [comment]
You are running jvb behind nat, because it only advertises its internal address 172....
You need to configure its private and public address, and also make sure you forward udp 10000 and tcp 443 or 4443(4443 in jvb is on the same machine as jitsi-meet and is served by nginx or apache2) to the jvb.
These are the settings you need: https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_local_address

**Comment by ranweb** [comment]
hi where do u change these settings? what is the config file name? I
couldn't locate any file with contents of ICE4j for some reason...

**Comment by damencho** [comment]
/etc/jitsi/videobridge/sip-communicator.properties

**Comment by ranweb** [comment]
Do I need to change all ports in this file to 4443 if it runs on the same machine as nginx? Also do I configure nginx to forward 443 traffic to job port 4443 ? Which location to forward?

נשלח ממכשיר הSamsung שלי

-------- הודעה מקורית --------
מאת: Дамян Минков <notifications@github.com> 
תאריך: 6.5.2017  23:28  (GMT+02:00) 
אל: jitsi/jitsi-meet <jitsi-meet@noreply.github.com> 
עותק: ranweb <ranweber@gmail.com>, Author <author@noreply.github.com> 
נושא: Re: [jitsi/jitsi-meet] cannot get jitsi-meet working - website starts
  but no camera / no focus etc (#1554) 

/etc/jitsi/videobridge/sip-communicator.properties

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jitsi/jitsi-meet","title":"jitsi/jitsi-meet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jitsi/jitsi-meet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@damencho in #1554: /etc/jitsi/videobridge/sip-communicator.properties"}],"action":{"name":"View Issue","url":"https://github.com/jitsi/jitsi-meet/issues/1554#issuecomment-299664018"}}}

**Comment by damencho** [comment]
In /etc/jitsi/videobridge/sip-communicator.properties
You need to configure 2 ip addresses in these properties.
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=

On your router/administrative console, you need to forward port 10000 udp and port 4443 tcp to go from the public address to the private address, I suppose you already have such a rule about port 443 and 80. That's it.

**Comment by ranweb** [comment]
sorry I think i fixed it...
one other question - is it possible to stream my own RTP (or other
protocol) video instead of YOUTUBE?

**Comment by ranweb** [comment]
I thought i fixed it... but no...

**Comment by ranweb** [comment]
it seems i "sort of" got it working because it works but suddenly i see
"fello jister is having..."
but then i tried connecting to meet.jit.si with my 3 laptops and also there
it happened!
any ideas why?? maybe my app is properly configured? can you have a look@
https://conf.shidur.net

**Comment by ranweb** [comment]
i reinstalled on new server: https://conf1.shidur.net
this time the quick install was really quick and seemed all conf is "out of
the box" - (it even tries 443 and then moves to 4443 etc. it seems like a
new install script, but 1/ this time the sip-communicator file is
completely empty! also 2/ it seem gives me "user is having connectivity
issues"...

do u need log file to help??

**Comment by damencho** [comment]
https://conf1.shidur.net - I got videobridgeNotAvailable
While https://conf.shidur.net seems fine here and it is working. Having connectivity are caused by problems with the network on the client side you are testing and you also confirmed this trying with meet.jit.si.
