### ISSUE TITLE
Is this prossible for switch jitsi-meet from 443 to 81 without ssl?

### ISSUE THREAD

**Issue by lizhaoch** [jitsi/jitsi-meet#1556]
i cannot load  /config from  https://mywebsite   ,so  I want use http ,if  replace all  'https'  to 'http' in project ,can it work?

**Comment by damencho** [comment]
webrtc requires https, it will not connect yo your microphone or camera when loaded from http.

**Comment by lizhaoch** [comment]
thk U,we have try open jitsimeet 's URL in mac safria，it show cannot support webrtc
but I searched ,after 2016.10，safria can support webrtc
do U have some suggest?

**Comment by damencho** [comment]
If you are talking for safari, it is supported using a temasys plugin, which in my experience doesn't have a good performance. 
I'm not aware that safari supports webrtc, where are you reading this?

**Comment by lizhaoch** [comment]
and I use startcom crt,ios version cannot read /config.js,will it better when I change GO DADDY?

**Comment by saghul** [comment]
Use whatever SSL certificate provider which works with no warnings, or add their CA to the trust store.

Also, I recommend using a different browser for a superior user experience, at least for now.
