### ISSUE TITLE
After make, Missing all.css

### ISSUE THREAD

**Issue by SlamDunkDcc** [jitsi/jitsi-meet#1561]
After make it shows  Missing https://XXXX/css/all.css?  I can't open the page

Uh oh! We couldn't fully download everything we needed :(
We will try again shortly. In the mean time, check for problems with your Internet connection!

**Comment by damencho** [comment]
Have you checked for errors while building? 
Can you show us the output of make?

**Comment by SlamDunkDcc** [comment]
/bin/sh: 1: ./node_modules/.bin/node-sass: not found
rm: cannot remove 'css/all.bundle.css': No such file or directory
Makefile:45: recipe for target 'deploy-css' failed
make: *** [deploy-css] Error 1

it happens

**Comment by SlamDunkDcc** [comment]
I have tried npm install node-sass, but it always failed.

**Comment by damencho** [comment]
I was about to ask you to do that 'npm install node-sass', humm...
Which versions of npm and node are you using?

**Comment by damencho** [comment]
$ node -v
v6.10.0
$ npm -v
3.10.10
Works fine, running them on osx. 

Same npm and node v6.10.3 work fine on Ubuntu LTS.

**Comment by SlamDunkDcc** [comment]
My node is v6.10.3,and my npm is v.4.5.0
Ubuntu 16.04.2 LTS

**Comment by damencho** [comment]
I just did a clean checkout and 
$ npm install node-sass
npm WARN prefer global node-gyp@3.6.1 should be installed with -g

> node-sass@3.13.1 install /home/damencho/jitsi-meet/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/damencho/.npm/node-sass/3.13.1/linux-x64-48_binding.node

> node-sass@3.13.1 postinstall /home/damencho/jitsi-meet/node_modules/node-sass
> node scripts/build.js

Binary found at /home/damencho/jitsi-meet/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
jitsi-meet@0.0.0 /home/damencho/jitsi-meet
└─┬ node-sass@3.13.1
......

But I think and newer npm should be fine ... not sure what can be wrong

**Comment by SlamDunkDcc** [comment]
Thanks I will try again!

**Comment by SlamDunkDcc** [comment]
yp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/htimeadmin/work/Video/jitsi-meet-master-iOS/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/home/htimeadmin/work/Video/jitsi-meet-master-iOS/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/htimeadmin/work/Video/jitsi-meet-master-iOS/node_modules/node-sass
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.
npm WARN eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-05-09T16_44_21_417Z-debug.log

**Comment by Toumassa** [comment]
I faced the same kind of issues on Centos 7.2.

After trying some versions of npm and node i ended with:
npm@4.5.0
node v5.11.1

BTW: you may face issues with clean-css. In this case install -g clean-css-cli and change the makefile's VARIABLE CLEANCSS to the clean-css binary file

**Comment by Gk19011994** [comment]
Uh oh! We couldn't fully download everything we needed :(
We will try again shortly. In the mean time, check for problems with your Internet connection!

Missing http://127.0.0.1:5500/css/all.css




logs:- 
> git-validate@2.2.2 install /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/git-validate
> node bin/install

WARNING: Unable to find a .git directory for this project, installation aborted.

> fsevents@1.2.4 install /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/fsevents
> node install

[fsevents] Success: "/Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.10.0 install /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/darwin-x64-64_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/xx/.npm/node-sass/4.10.0/darwin-x64-64_binding.node

> precommit-hook@3.0.0 install /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/precommit-hook
> node bin/install


> styled-components@3.4.9 postinstall /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components

> lib-jitsi-meet@github:jitsi/lib-jitsi-meet#2e1436e20d4d8fb6020497a87b2714dff38a6c86 postinstall /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/lib-jitsi-meet
> webpack -p

Hash: 910f02aa041785d23013
Version: webpack 4.26.1
Child
    Hash: 910f02aa041785d23013
    Time: 32040ms
    Built at: 03/13/2019 3:52:30 PM
                     Asset      Size  Chunks                    Chunk Names
     lib-jitsi-meet.min.js   685 KiB       0  [emitted]  [big]  lib-jitsi-meet
    lib-jitsi-meet.min.map  2.61 MiB       0  [emitted]         lib-jitsi-meet
    Entrypoint lib-jitsi-meet [big] = lib-jitsi-meet.min.js lib-jitsi-meet.min.map
      [2] ./JitsiConferenceEvents.js 8.21 KiB {0} [built]
      [3] ./modules/browser/index.js 98 bytes {0} [built]
      [4] ../jitsi-meet-logger/lib/index.js 3.6 KiB {0} [built]
      [6] ./modules/statistics/statistics.js 28.1 KiB {0} [built]
      [7] ./service/statistics/AnalyticsEvents.js 15 KiB {0} [built]
      [9] ./service/RTC/MediaType.js 110 bytes {0} [built]
     [10] ./modules/util/GlobalOnErrorHandler.js 2.37 KiB {0} [built]
     [12] ./JitsiTrackErrors.js 2.68 KiB {0} [built]
     [13] ./modules/RTC/RTC.js 34.3 KiB {0} [built]
     [15] ./JitsiTrackError.js 6.07 KiB {0} [built]
     [17] ./JitsiTrackEvents.js 1.31 KiB {0} [built]
     [20] ./modules/videosipgw/VideoSIPGWConstants.js 1.44 KiB {0} [built]
     [21] ./JitsiConferenceErrors.js 2.12 KiB {0} [built]
    [121] ./index.js 160 bytes {0} [built]
    [122] ./JitsiMeetJS.js 19.4 KiB {0} [built]
        + 141 hidden modules
    
    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      lib-jitsi-meet.min.js (685 KiB)
    
    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      lib-jitsi-meet (685 KiB)
          lib-jitsi-meet.min.js
    
    
    WARNING in webpack performance recommendations: 
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/

> node-sass@4.10.0 postinstall /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/xx/Downloads/jitsi-meet-stable-jitsi-meet_3548/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
added 1839 packages from 978 contributors and audited 31114 packages in 86.956s
found 13 vulnerabilities (9 low, 2 moderate, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by damencho** [comment]
Please use the community forum. 
Did you invoke `make` after `npm install` as said in the README?

**Comment by kyronjoves** [comment]
Hi,

It also shows on my end that all.css is missing.

![image](https://user-images.githubusercontent.com/61576972/81528218-c4865b00-938e-11ea-90bd-275dbbe2011c.png)

**Comment by TivanDev** [comment]
your nginx cannot access to folders
run this command in terminal 
`sudo chown -R "$USER":www-data jitsi-meet`
