### ISSUE TITLE
Chat private jitsi meet?

### ISSUE THREAD

**Issue by nguyendatdh93** [jitsi/jitsi-meet#1563]
Hi team.

I am using jitsi meet for my whiteboard app. I want to build chat private for whiteboard. But i can not find any idea for this issue. Team can help me?.

Sorry because my english is not good.

Thank you so much.

**Comment by damencho** [comment]
Currently, there are two options:
- enable authentication on the server and create users for the participants that will create a room or and let guests join without authentication, or disable guests and make everybody use username and password
- and the easier approach is when someone joins to set a password for entering the room from the invite people dialog, this way everybody who tries to join will need to enter that password
