### ISSUE TITLE
Procedure for Installing Jitsi in Node.JS App?

### ISSUE THREAD

**Issue by VikR0001** [jitsi/jitsi-meet#1567]
The Read Me references Ubuntu and Debian, but my dev system is OS X.  Can I install jitsi-meet like so:

```
npm install lib-jitsi-meet --force && make
npm install jitsi-meet-logger
npm install react-native-webrtc
```

Thanks in advance for the info.

**Comment by damencho** [comment]
Do you want to make a full deployment on OSX?
You need a xmpp server, web server, installing, configuring and running jicofo and jitsi-videobridge. It is possible on OSX but will not be a trivial task.
Other than that, just making the sources of jitsi-meet you need: npm install && make, the command you mention is a special case where you a referring lib-jitsi-meet from a local checkout in your package.json and you force making it before making jitsi-meet.

**Comment by VikR1000** [comment]
The deployment will be as a node.js web application, to be run in users' browsers.  Is that possible with Jitsi?

**Comment by damencho** [comment]
For the web part, yes, but you also need a backend which consists of several different components.
Here is a network diagram showing those components: https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#network-description

**Comment by VikR1000** [comment]
I think I'm starting to get this. So, in development the back-end runs on my local dev system, and in testing/production it runs on my production server.

**Comment by amohideen** [comment]
@damencho 
Why do not I see the text editor on my local installation (ubuntu:stable)?
Is it possible to merge another node js project into jitsi-meet (i.e. a whiteboard)

**Comment by damencho** [comment]
@amohideen If you are talking about etherpad you need to configure it in config.js putting the url to your etherpad deployment.
@VikR1000 I don't see why not, you can bundle whatever you want in app.bundle of the app.

**Comment by VikR0001** [comment]
@damencho is it possible to use Jitsi without running the back-end on my local dev system, or on my production server? I.e. by tying into another service?

**Comment by VikR0001** [comment]
Does Jitsi handle STUN and TURN, or enable me to tie in to a service that handles STUN and TURN?

**Comment by damencho** [comment]
STUN is needed only in P2P mode if it is enabled. You do not need TURN cause jitsi-videobridge is relaying media for users. TURN is a media relay as it is and the jvb.

**Comment by VikR0001** [comment]
If STUN is needed, does Jitsi provide it directly, or is STUN for Jitsi available from a paid service?

**Comment by darktheft** [comment]
@darktheft
Is that possible Build custom jitsi Ui and SDK
if possible pls help me on @darktheft
darktheft.github@gmail.com
    thanks.
