### ISSUE TITLE
Jitsi Newbie Q: Errors Running Source From https://meet.jit.si/testtttt?

### ISSUE THREAD

**Issue by VikR0001** [jitsi/jitsi-meet#1570]
I was advised by a Jitsi user to download the source from `view-source:https://meet.jit.si/testtttt` and load the local file into a browser. I'm getting some console errors in Chrome Dev Tools:

> Uncaught TypeError: Cannot read property 'caller' of undefined
> 
> external_connect.js?v=1:50 Refused to get unsafe header "X-Jitsi-Shard"
> xhttp.onreadystatechange	@	external_connect.js?v=1:50

How can I correct this? Thanks very much in advance to all for any info.

**Comment by bgrozev** [comment]
I don't see how downloading the html would be any use. What are you trying to accomplish?

**Comment by VikR0001** [comment]
I'm trying to install Jitsi so I can become more familiar with it. A Jitsi user on another forum told me:

```
view-source:https://meet.jit.si/testtttt

Go copy the source of that page in to a new .html doc on your desktop. Bam. Meetings. You can use Jitsi Embed on any page you want, and change rooms with a parameter...

```
Do I need to install a Jitsi back-end on my local computer in order to run Jitsi? That's fine of course-- I just would like to learn the correct procedure.

**Comment by saghul** [comment]
@VikR0001 This is the best way to quickly get it working and test things out: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

**Comment by VikR0001** [comment]
Thanks @saghul. That page notes that "Debian 8 (Jessie) or later, and Ubuntu 14.04 or later are supported out-of-the-box."  My development system is Mac OS X.  Is there a way to install Jitsi on OS X?

**Comment by saghul** [comment]
@VikR0001 not the backend. I suggest you install it all on a virtual machine running one of the supported systems.

**Comment by VikR0001** [comment]
@saghul Is there a reference page that describes how to install it all on a virtual machine?

**Comment by bgrozev** [comment]
https://github.com/jitsi/jitsi-meet/#installation

**Comment by VikR0001** [comment]
@bgrozev I don't yet see anything about virtual machines on that link.

**Comment by saghul** [comment]
@VikR0001 There is no difference from using a regular server.

**Comment by VikR0001** [comment]
Oh okay, I see. I would use a virtual server running debian or ubuntu. Okay, thanks for the info!
