### ISSUE TITLE
npm install is failing to install dependency

### ISSUE THREAD

**Issue by cyberbandya007** [jitsi/jitsi-meet#1571]
npm ERR! 404 'atlaskit' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/sandeep/jitsi-src/jitsi-meet
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404

When I try to run 'npm install', is gives me above error. It looks like mentioned dependency doesn't exist. This needs to be updated.

**Comment by lyubomir** [comment]
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10

Upgrade node and npm to their latest stable version.

**Comment by cyberbandya007** [comment]
Hello,

Thanks. Trying this.

I checked later about
https://github.com/jitsi/jitsi-meet/blob/master/CONTRIBUTING.md. I believe
I could have mailed this problem to some mailing list and got the answer
without creating issue in GitHub. Can you tell me which mailling list I
should prefer for these kind of issues?

Thanks in advance.

**Comment by cyberbandya007** [comment]
It worked. Thanks.
