### ISSUE TITLE
Not trusted certificate 

### ISSUE THREAD

**Issue by alcaporal** [jitsi/jitsi-meet#1572]
I followed the quick install and everything seems nice except for ssl.
The server's certificate is not trusted. 
Can anyone help me to fix this please?

**Comment by damencho** [comment]
You can obtain a certificate from any provider and install it or you can install let's encrypt certificate.
In latest builds, there is a script that installs let's encrypt certificate /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

**Comment by alcaporal** [comment]
I don't have this folder or script but i'll try to install let's encrypt manually. Thanks for your feedback. @damencho

**Comment by MattB98** [comment]
incase anyone hits this on a search, the script is now in /usr/share/jitsi-meet/resources - and running it resolved the certificate issues I was experiencing.

**Comment by Inbydev** [comment]
> incase anyone hits this on a search, the script is now in /usr/share/jitsi-meet/resources - and running it resolved the certificate issues I was experiencing.

for me now its /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
