### ISSUE TITLE
Issue API commands once 'ready'?

### ISSUE THREAD

**Issue by kneeki** [jitsi/jitsi-meet#1588]
Is it possible to issue commands once the External API has successfully created a connection? Doing something like this doesn't work:

```javascript
// ...
    api = new JitsiMeetExternalAPI(domain, room, width, height, htmlElement, undefined, interfaceOverwrite, noSSL);
    api.executeCommand('displayName', window.displayName);
    api.executeCommand('avatarUrl', window.user.profile_picture);
```

**Comment by saghul** [comment]
What version are you running? @hristoterezov you fixed this is a while ago, right?

**Comment by kneeki** [comment]
Sorry for my lack of knowledge on this, but I am unsure how to check the version.

**Comment by saghul** [comment]
No problem, you can check as follows, in your terminal:

`dpkg -l | grep -i jitsi`
