### ISSUE TITLE
Please add Vietnamese translation for Jitsi Meet

### ISSUE THREAD

**Issue by ZuzooVn** [jitsi/jitsi-meet#1590]
Hi Jitsi team, 

Could you please add Vietnamese translation to your Pootlet server [0]?

Btw, can we add new translation json file without building the source code?
I mean Can I add more language with Jitsi Meet quick install [1] ?

[0] http://translate.jitsi.org/projects/jitsi-meet/
[1] https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

Regards,

Nam Vu from ThinkLabs-VN

**Comment by bgrozev** [comment]
Hi Nam Vu,

On 22/05/2017 06:08, Nam Vu wrote:
> Hi Jitsi team,
>
> Could you please add Vietnamese translation to your Pootlet server [0]?

Added, thank you for your interest.

>
> Btw, can we add new translation json file without building the source code?
> I mean Can I add more language with Jitsi Meet quick install [1] ?

I don't know.

Regards,
Boris

**Comment by ZuzooVn** [comment]
Hi Boris

> Added, thank you for your interest.

Thanks, I will help you to translate Jitsi Meet to Vietnamese.

>I don't know.

Can anybody help me?

Thanks, 

Nam Vu from ThinkLabs-VN

**Comment by ZuzooVn** [comment]
I translated Jitsi Meet to Vietnamese.
Please check Pootlet server.

Can somebody tell me Does it possible to add new translated language without building from source code?

Thanks,
Nam Vu from ThinkLabs-VN

**Comment by LVBK** [comment]
@ZuzooVn: I found main-vi and lang-vi in folder of source code in branch master.
You just need register to become a contributor of Jitsi-Meet for create merge request with translated version. When it merged, all you need to do is go to:
For  nightly build versions: https://download.jitsi.org/nightly/
Or stable build versions: https://download.jitsi.org/stable/

**Comment by ZuzooVn** [comment]
@LVBK Thanks
> I found main-vi and lang-vi in folder of source code in branch master.

I translated all of the Vietnamese string: http://translate.jitsi.org/vi/jitsi-meet/

How can I build translated version on my local machine?

Thanks,
Nam Vu from ThinkLabs-VN

**Comment by bgrozev** [comment]
@ZuzooVn I've pushed the Vietnamese language files from pootle to github.

**Comment by ZuzooVn** [comment]
Thank @bgrozev 
Would you happen to know when will Vietnamese interface live on http://meet.jit.si/ ?

Thanks,
Nam Vu from ThinkLabs-VN
