### ISSUE TITLE
Improve visualization of raise hand feature [UX/UI]

### ISSUE THREAD

**Issue by Xaviju** [jitsi/jitsi-meet#1597]
Hi!

I'd like to suggest an improvement on the **raise hand** feature regarding its visualization.

## How to reproduce
Currently when a user raises its hand there is a really small badge on the user camera. Sometimes, when a user raises its hand the team ignores it involuntarily.
With the latest changes, if the camera is hidden behind the new scroll on the right side, the hand is completely hidden.

## Expected
Since it is a very interesting feature, it would be nice to raise some visual indicator. Enough to get noticed by every user, not too big to disturb the conversation 

## Browser and version
We are using Jitsi in latest versions of both Chromium and Firefox through the web interface.

## UX suggestion
Our UX/UI team wire-framed a proposal. Notice the stacked flash message in the top right of the page and the larger badge on the user cam. The behavior remains as it is, the flash message and the badge should disappear when the user is allowed to talk.

![jitsi_issue](https://cloud.githubusercontent.com/assets/1343702/26398690/86a78d1e-407a-11e7-9ad4-011babbfe9a2.jpg)

Let us know what you think, we could try to work on this feature with some mentorship if you think is worth a PR.

**Comment by saghul** [comment]
Thanks for putting together such a complete issue report! You definitely raise a valid concern. The new filmstrip position just landed, so some follow-up fixes are expected.

@yanas WDYT?

**Comment by ulab** [comment]
I just wanted to suggest a similar feature - to reorder the video list so that "raised hands" are on top.

The list that is suggested in the wireframe from @Xaviju looks really nice too though and I like that you can see the order of people that wanted to speak.

Any chance that this ticket can get reopened?

**Comment by novell1974** [comment]
finally, the option to raise hand, is it possible that the icon is bigger?

**Comment by delacosta456** [comment]
hi

Please i am also looking for this. is there already any help or workaround
