### ISSUE TITLE
Blank grey jitsi screen on load for embedded meet.jit.si

### ISSUE THREAD

**Issue by lpatmo** [jitsi/jitsi-meet#1605]
![image](https://cloud.githubusercontent.com/assets/4512699/26442492/95eca1e6-40e9-11e7-9b37-983b732e15dc.png)

Browser: Chrome 56
OS: OSX 10.11.6

Today for the first time, I saw a blank grey screen in place of the Jitsi hangout when the page load. The problem disappeared after a while after a couple of refreshes.

**Comment by turbo** [comment]
Same thing here

**Comment by saghul** [comment]
Can you see any errors in the console?

**Comment by turbo** [comment]
The browser console is clean from errors. The jitsi and nginx logs are clean, too.

After rebooting the server, I can access the site for a short amount of time, then it's grey-ing out again. You can see for yourself at https://steelmountain.org

**Comment by turbo** [comment]
Probably the same issue as #1222

**Comment by saghul** [comment]
Can you try to disable CloudFlare's rocketscript? No JS is getting executed, which looks suspicious.

**Comment by turbo** [comment]
There's nothing enabled in the CF panel. I'm just using them for DNS. Caching, minification etc. is off. Additionally, the server is currently in development mode.

**Comment by turbo** [comment]
Oh well, now it works. I applied the workaround from the linked issue, and set Cache to bypass in CF.
