### ISSUE TITLE
Welcome Page Config Variable /etc/jitsi/meet/config.js ( enableWelcomePage: false, ) does not work

### ISSUE THREAD

**Issue by frebsdparty** [jitsi/jitsi-meet#1620]
Hello Friends, 

After installing more than 2 times with a fresh debian 8 ( jessie ) and the Stable Jitsi-meet repository.

I can't disable the Welcome Page.

Can someone point me if it's a bug ? 

I double check if jitsi show any log about it, but nothing...i suspect that it's not ok.

Can confirm that please !!!

Thank you.

Brancher.

**Comment by saghul** [comment]
I believe @lyubomir just fixed this one a couple of days ago, so it's not yet part of a stable release.

**Comment by frebsdparty** [comment]
Thank you @saghul, i will change my repository to check that out.
Good day friend.
This helps me 👍 
t+

**Comment by lizhaoch** [comment]
QQ group for jitsi-meet in China :638328355
welcome join and discuss the R&D about JITSI !
//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7

**Comment by lyubomir** [comment]
We've surely released the fix in a stable build by now.

**Comment by frebsdparty** [comment]
Thank you friend, big hug from Brazil.

**Comment by khiladiusman** [comment]
How do I customize my server for video and audio call seprately.
I wanna do only audio call.
I wanna do video call .
Is this write approach by making two Instance of of the jitsi on my two server.
If I can implement this functionalty by just applying the change in Config.js file dynamically. 
then please help me.
