### ISSUE TITLE
when filmStripOnly=true, white screen shows in large video

### ISSUE THREAD

**Issue by jlightfoot** [jitsi/jitsi-meet#1621]
Thought I'd take a look at this feature but when turned on, only the small video shows camera output.  The large video window shows nothing but white.  I confirmed in stable and nightly builds.

**Comment by damencho** [comment]
Yep, this option enables film strip only. This means only the videos on the buttom work and there is no large video. This is a mode to be used normally through the API when embedding a jitsi-meet instance in an iframe in another page and there is no need for large video.

**Comment by jlightfoot** [comment]
I see.  Am I misremembering that the feature originally included local and remote videos but eliminated toolbars?  I was thinking that its purpose was to pare down control features for guest participants.
