### ISSUE TITLE
Try jitsi meet with raspberry pi

### ISSUE THREAD

**Issue by quancao** [jitsi/jitsi-meet#1645]
I tried to use jitsi meet for video conference on raspberry. First, I use the public server at https://meet.jit.si/ to create a room and joins to that room from my raspberry pi 3 board. I have a picam camera v1 plug in to pi board and an external usb speaker. Second, I use chromium-browser to join the meeting from raspberry and the preview video looks good. After that, I join that room from my pc using chrome browser then I notice the video is lagged and sluggish on both preview (on raspberry) and the peer (PC browser). I think the bottleneck is network so I tried to host jitsi meet to one of my PC running ubuntu 16.04 and the result is the same.

I do think that Jitsi Meet implements SFU by videobridge so it should not affect the performance of preview in local browser.

Have anyone success with jitsi meet on raspberry with HD 720p for video conferencing ? Any recommendations are appreciated. Thanks

**Comment by saghul** [comment]
@quancao I have tested this very recently. The reason why video is sluggish on the Pi is due to the fact that the video codec we use is VP8, which is not hardware accelerated in the Pi. The Pi will encode / decode VP8 video in software, and the CPU is just not powerful enough.

**Comment by crosofg** [comment]
How to use h264 encoding for jitsimeet in RPI?
