### ISSUE TITLE
Desktop view available on mobile

### ISSUE THREAD

**Issue by rscastil** [jitsi/jitsi-meet#1647]
It is possible to show the desktop version view on mobile? I'm using external API and did some customization on it ex: email add, avatar using the profile data on the website.  The problem is when the user using mobile app all of the settings are lost.

**Comment by damencho** [comment]
In chrome on mobile there is an option request desktop site and when clicking it you can access your deployment, but the experience will not be optimal for the mobile users, so it is better to use the mobile app.

**Comment by rhodelcastil** [comment]
Thank you Damencho. I guess we're good on that but is there any possibility on mobile app it will adapt any customization? Thanks

**Comment by damencho** [comment]
Its a mobile app, if you need custom stuff there you need to implement them and build new custom app.

**Comment by rscastil** [comment]
Yah I understand damencho. Thanks

**Comment by rscastil** [comment]
Please correct me if I should not reopen this topic. 
I tried to remove this on the head of my html  <meta name="viewport" content="width=device-width, initial-scale=1.0"> but its still detecting I'm using mobile device so I conclude that the mobile detection is base on actual mobile device not on the width.

I'm trying to use the desktop view on specific page. Is there a way on the api to force them to use mobile view?  


![mobile](https://user-images.githubusercontent.com/2825333/26954706-156416f6-4ce4-11e7-95a4-99166d8f49ca.png)
