### ISSUE TITLE
Use Jitsi in native app

### ISSUE THREAD

**Issue by jishuo1213** [jitsi/jitsi-meet#1648]
I want use jitsi in my app,but I don't want use react-native because I don‘t familiar with javascript language,so I want use jitsi in native way,I have build webrtc library,is there some document about how client Interaction with the jitsi server,like xmpp and mediastream,I want implement a client in java.Thank you very much.

**Comment by saghul** [comment]
I think you underestimate the effort required to do that. It's a non-trivial task which could take a tremendous effort, in the order of man-years.

Now, I have some good news for you: we are working on native SDKs for Android and iOS, which wrap all the react-native parts under a native API, so while there is JavaScript, you don't need to writer any JS nor know about it! Isn't that wonderful? :-)

Keep an eye here: https://github.com/jitsi/jitsi-meet/pull/1593

Cheers,
