### ISSUE TITLE
Jitsi meet stops on Chrome due to DevTools 

### ISSUE THREAD

**Issue by bahiamartins** [jitsi/jitsi-meet#1650]
I have jitsi-meet installed in a Debian server https://live.jobconvo.com/ but it freezes on Chrome. The console shows the message: "DevTools was disconnected from the page".

It works fine on Firefox.

I'm using Chrome 58.

Any help is appreciated

Thanks

**Comment by jnelson62** [comment]
Hate to be a "me too" but alas...I've been experiencing this since Chrome 58 update. We have started using Firefox for meetings.

**Comment by gpolitis** [comment]
@bahiamartins what's your stack version? (versions for jvb, jicofo, jitsi-meet)

**Comment by bahiamartins** [comment]
Sorry for the late replay.
Here is:

jvb - I don't know how to find it. But java-common is 0.52
jicofo 1.0-320-1
jitsi-meet 1.0.1622-1

Thanks
