### ISSUE TITLE
Implement session timer in jitsi-meet

### ISSUE THREAD

**Issue by bahiamartins** [jitsi/jitsi-meet#1663]
Hi, is there a way to implement a timer while a conference is happing?
I've seen this library: https://github.com/BroadSoft-Xtended/Library-WebRTC-Timer but I don't know how to integrate it in my jitsi-meet project.

Thanks in advance

**Comment by saghul** [comment]
That is related to SIP Sesstion Timers, which have nothing to do with Jitsi Meet. What are you trying to accomplish?

**Comment by bahiamartins** [comment]
I'd like to show to users the time of a conference and store it

**Comment by jseremba** [comment]
> I'd like to show to users the time of a conference and store it

Did you manage to archive this...
