### ISSUE TITLE
Chinese (China) interface

### ISSUE THREAD

**Issue by OmniGuardianFight** [jitsi/jitsi-meet#1664]
There's a post saying the Chinese (China) support is merged to Main. Would anyone happen to know when will Chinese (China) interface live on http://meet.jit.si/ ?

**Comment by lizhaoch** [comment]
QQ group for jitsi-meet in China :638328355
welcome join and discuss the R&D about JITSI !
//shang.qq.com/wpa/qunwpa?idkey=e79ccfa96ef5afac7c48ce0a18cdaf0f28b3268b2a9954926586194df01a58d7
