### ISSUE TITLE
https 验证错误；

### ISSUE THREAD

**Issue by chenguozhi** [jitsi/jitsi-meet#1668]
在测试环境下，我们用的是https，但是遇到了同样的问题 https://github.com/jitsi/jitsi-meet/issues/1544；我想在测试环境下跳过验证，我们需要你们的帮助！！！
ps：In the test environment, we used HTTPS, but we ran into the same problem https://github.com/jitsi/jitsi-meet/issues/1544. I want to skip validation in the test environment, we need your help!!!

**Comment by haofanning** [comment]
解决了吗，自签名证书能用吗？
