### ISSUE TITLE
Javascript in translation key notify##grantedToUnknown

### ISSUE THREAD

**Issue by ibauersachs** [jitsi/jitsi-meet#1679]
The translation key [notify##grantedToUnknown](../tree/master/lang/main.json#L213) contains Javascript (introduced in the original translation project in commit 79cdd948333f542c27b2a2bc97cdfeae18e0d2ee). This seems wrong and should be an i18next placeholder (e.g. `__moderator__`).

**Comment by damencho** [comment]
Actually, this is allowed in i18next:
https://www.i18next.com/nesting.html

**Comment by ibauersachs** [comment]
True. But the translation is still of:
```
"somebody": "Somebody",
"grantedTo": "Moderator rights granted to __to__!",
"grantedToUnknown": "Moderator rights granted to $t(notify.somebody)!",
```
The second translation is either not needed at all OR the casing is wrong. And both should probably end with a period, not an exclamation mark.
