### ISSUE TITLE
JitsiMeetExternalAPI <=> Screen Sharing

### ISSUE THREAD

**Issue by philrykoff** [jitsi/jitsi-meet#1690]
Hi together,

when clicking on the Screen Sharing button in an iFrame created using JitsiMeetExternalAPI, jitsi always offers to reinstall the Chrome extension. It then fails to recognize that it was successfully (or rather already) installed.

Any way around this? 💃 

Thanks a lot!

**Comment by philrykoff** [comment]
So I tried to reproduce the issue using regular iFrame, but failed. So tt does not seem to be a general iFrame issue.

```
<html itemscope itemtype="http://schema.org/Product" prefix="og: http://ogp.me/ns#" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
    </head>
    <body>
        <script>
		
			var frame = document.createElement("iframe");
			frame.src = "/conferencing/JitsiMeetAPIExample#jitsi_meet_external_api_id=0";
			frame.name = "";
			frame.id = "";
			frame.width = "100%";
			frame.height = "100%";
			frame.setAttribute("allowFullScreen", "true");
			frame = document.body.appendChild(this.frame);
		
        </script>
    </body>
</html>
```

**Comment by philrykoff** [comment]
As soon as I attach Postis, Screen sharing does not work. I tried to hook into Postis in order to see wheter it swallows any messages which were meant for the browser extension, but there don't seem to be any. Yet, Postis seems to be the culprit.

Any ideas?

```
			var postis = Postis({
				window: frame.contentWindow,
				scope: "jitsi_meet_external_api_0"
			});
```

**Comment by ibeardslee** [comment]
For desktop sharing to work, the chrome extension needs to be compiled for the server. It is possible that that the extension is seeing the server that is providing the iframe as a different server. If that is the case the extension will then need to be recompiled with the additional different server included.

**Comment by philrykoff** [comment]
Well the only distinction above between working / not-working is the use of Postis. If Postis is off, then everything works with the iFrame code I have shown above. 

Both that iFrame and the API generated iFrame use the same domain, though, so that can't be the issue. I've got it working now with the manual solution outlined above. Via localStorage I can even set the displayname. But as soon as Postis is in the way, the extension is not recognized.

Nobody else has Screen Sharing isses via API?

**Comment by kullmar** [comment]
This problem still exists.
