### ISSUE TITLE
Can not use my camera

### ISSUE THREAD

**Issue by detectiveHLH** [jitsi/jitsi-meet#1698]
I set it up  on my own domain,and use my usable certificate,but when i use it , the dialog that ask the permission to use camera has shown up,and i choose yes,but the page is still like this
![default](https://user-images.githubusercontent.com/24632081/27474619-30098200-5835-11e7-82b0-3677d4d68c79.PNG)
I do not know what's going on

**Comment by damencho** [comment]
Could you open the javascript console and paste the output here. There should be a hint there.

**Comment by detectiveHLH** [comment]
Of course.My browser is FireFox 54.0 and there are the screenshot of the console
![default](https://user-images.githubusercontent.com/24632081/27504088-d280bdec-58b6-11e7-9235-bea8d8461f0e.PNG)
![2](https://user-images.githubusercontent.com/24632081/27504090-d639552a-58b6-11e7-9577-54196bfc8547.PNG)

**Comment by detectiveHLH** [comment]
I change a server to do the same thing,but is still not working,Maybe it have something to do with my domain?The server run good if i use the ip address only

**Comment by saghul** [comment]
I can't even connect to your server, I get an SSL error: "An error occurred during a connection to xiexianbo.xin. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG"

Is that doman accessible everywhere?

**Comment by detectiveHLH** [comment]
@saghul Hi
Now it is accessible,i still running test on my server,and now it's stable,please try agian

**Comment by saghul** [comment]
@detectiveHLH You SSL certificate seems to contain the wrong common name:

"Redirecting navigation xiexianbo.xin -> www.xiexianbo.xin because the server presented a certificate valid for www.xiexianbo.xin but not for xiexianbo.xin. To disable such redirects launch Chrome with the following flag: --disable-features=SSLCommonNameMismatchHandling"

The first request kinda succeeds due to the redirect, but not the rest, since they point at the bare domain (without www).

**Comment by saghul** [comment]
I'm closing this since it's not a Jitsi Meet bug.

**Comment by detectiveHLH** [comment]
@saghul 
Hi,thank u for helping me,but i am still don't know what wo do,Am i suppose to change xiexianbo.xin to www.xiexianbo.xin during the installation or disabel redirects?Or both?

**Comment by saghul** [comment]
Your SSL cert has "www.xiexianbo.xin" in the common name, so you either put that in the installation or get a cert for the bare domain.

**Comment by detectiveHLH** [comment]
I have try put it in my installation like www.xiexianbo.xin,but it still don't work.I can not see other guys either.
Have it something to do with the cache?
