### ISSUE TITLE
Screen Share not working on P2P

### ISSUE THREAD

**Issue by anatomism** [jitsi/jitsi-meet#1701]
Hi,

Like the update for P2P calls - very useful.

I have the latest testing implementation of meet on my server (as of 2 hours ago), along with custom Jidesha plugin for screen sharing.

Screen sharing works well when running through the JVB (tested with 3-5 people), but as soon as I try P2P it just shows blank (or the camera) on the receiving browser, but all looks like it works on the sending browser (no console errors).

On the receiving console, the following error shows in the Chrome console 
`[modules/statistics/RTPStatsCollector.js] <a.processStatsReport>:  JitsiTrack not found for SSRC 3630250572 in TPC[1,p2p:true]`

If I start a conference P2P and a screen share is done, it doesn't work - if a third person joins (therfore forcing through JVB) the screen sharing starts working. As soon as the third person leaves and it goes back to P2P the screen sharing stops. Again, with no errors or warnings on the senders end.

Any ideas?

Thanks

**Comment by paweldomas** [comment]
Thanks for the report ! I will take a look on Monday

**Comment by paweldomas** [comment]
Are you able to reproduce it on https://beta.meet.jit.si ? Because I can't... Are there any extra steps ?

**Comment by anatomism** [comment]
Hi Pawel,

I've just tried again on the office network and it seems fine. However at home it didn't work (which is strange). I confirm it works on my custom install as well...

Please close - thanks

**Comment by JitendraSingh1995** [comment]
hello,
        when i want change the camera then these type error occur. And i old tracks removed from conference and detach the track and also with the new camera device create new track and addTrack old 
conference and attach track with the help of jitsi meet api .

https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md
