### ISSUE TITLE
How integrate to my existed react-native app

### ISSUE THREAD

**Issue by redwind** [jitsi/jitsi-meet#1703]
Hi Jitsi team !
First, thank to your awesome repo !
I would like to integrate jitsi-meet framework to my existed RN app but i don't see any document for api integrate. Seem that this repo is an standalone app.
Could you guide to me some part of repo's source code that i should focus to find integrate api.
Thank so much !

**Comment by philrykoff** [comment]
You can have a look at the "app" directory, which is an implementation of the "sdk" directory sources.

Basically, you would have to do the same which the jitsi developers did within the "app" directory, just within your app - implement the sdk.

**Comment by themakerman** [comment]
So do you mean we should go through the source code and figure out everything? @philrykoff
