### ISSUE TITLE
Unable to compile on Android Studio

### ISSUE THREAD

**Issue by klorydryk** [jitsi/jitsi-meet#1706]
I'm working on the last version of the code (tag: jitsi-meet_2191)
Trying to compile the code jitsi-meet/android/ on Android Studio 2.3, it says it is impossible to compile and need Android Studio 3.0.
After downloading this 3.0 version, it says it is unable to compile because 
`Error:Failed to resolve: Could not resolve project :react-native-background-timer.
Required by:
    project :sdk`
List continue with all other node_modules dependancies .

It is needed to do something before to be able to compile this project?

**Comment by pawankhandal52** [comment]
Any one help i also getting same error.
Error:Failed to resolve: Could not resolve project :react-native-background-timer. Required by: project :sdk

**Comment by RonakMutha12** [comment]
Facing the same issue

**Comment by lyubomir** [comment]
The preview of the next Android Studio version became required recently because Gradle 4 and Android plugin 3 solve an issue with building Debug and Release configurations regardless of which configuration was requested.

Did you run `npm install` first as specified at https://github.com/jitsi/jitsi-meet/blob/master/README.md ?

**Comment by saket424** [comment]
I am coming back to jitsi after a long hiatus I am able to compile and build and run android react-native-jitsi-meet But when I specify the room number to join, I get the following error 

console error:"[modules/xmpp/strophe.util.js]","<r>:","Strophe: User connection call back caused an exception: TypeError: undefined is not an object (evaluating 'this.options.p2p.useStunTurn')"

Any ideas what I am doing incorrectly?

**Comment by lyubomir** [comment]
On Wed, Jul 5, 2017 at 12:10 PM, saket424 <notifications@github.com> wrote:
> console error:"[modules/xmpp/strophe.util.js]",":","Strophe: User connection call back caused an exception: TypeError: undefined is not an object (evaluating 'this.options.p2p.useStunTurn')"
>
> Any ideas what I am doing incorrectly?

It's not you, it's us - we broke the latest master of jitsi-meet on
mobile and I'm working at the moment to fix it.

**Comment by saket424** [comment]
Commit 9aaf9a484da63a600ac35e81a5b503aba478ac10 cleared things up/ I am able to build and run the android version now. Thanks
