### ISSUE TITLE
meet.jit.si requires Safari Technology Preview to install a WebRTC plug-in

### ISSUE THREAD

**Issue by youennf** [jitsi/jitsi-meet#1714]
Safari Technology Preview supports WebRTC.
It should therefore be possible to enable it without plugin.

**Comment by youennf** [comment]
Ideally, in case browser sniffing detects Safari, meet.jit.si should check whether RTCPeerConnection is present. If so, no plugin install prompt should be proposed.

**Comment by bbaldino** [comment]
@youennf i've been working on getting Safari Tech Preview to work natively but I ran into what seems like a bug.  I reported it [here](https://bugreport.apple.com/web/?problemID=33358476), but perhaps webkit would've been a better place?  do you know if that's a bug or is it intended behavior?

**Comment by seanmheff** [comment]
Any update on your progress getting Safari Tech Preview to work @bbaldino?

**Comment by bbaldino** [comment]
i stopped after encountering that bug...i was hoping to at least get confirmation that it was legit but haven't heard anything back.  i did check at least one subsequent release of tech preview but the issue was still there.

**Comment by youennf** [comment]
@bbaldino sorry for not following up.
bugs.webkit.org would be a better place for those kind of bugs.
Looking at it, this is probably a bug in the implementation of WebKit that should be fixed at some point.
Do you need that active flag to move on?

**Comment by bbaldino** [comment]
thanks @youennf ...could probably work around it but didn't really want to write a bunch of throwaway code as a workaround.  i'll file something on webkit.

**Comment by seanmheff** [comment]
Can you put a like to the webkit ticket in here please?

I can't access the Apple ticket.

**Comment by bbaldino** [comment]
filed a bug here https://bugs.webkit.org/show_bug.cgi?id=175434

**Comment by youennf** [comment]
It should be fairly easy to implement.
I'll see whether it can ship in next STP then so that you can move forward.
If you have some time, it should be easy to shim an active getter.
That may allow more testing and identify missing pieces in STP for jitsi.
