### ISSUE TITLE
Password Required Dialog does not contain translated Text & Wrong Dialog?

### ISSUE THREAD

**Issue by ctel** [jitsi/jitsi-meet#1717]
![invalidpassworddialog](https://user-images.githubusercontent.com/9321348/27732536-121c0a6c-5d92-11e7-902c-2c94afa835d8.png)
As you can see there is a problem with user friendly text within the dialog.
Also this dialog might not be semantically correct: As you can see the network log shows a *not-authorized* tag and the text shows that a password had been provided, so the message should not be that _a password is required_, but rather that _the *correct* password is required_ for a successful login. Maybe there should be a dialog with the title: _Invalid User Credentials_ or _Invalid Password_?!?

**Comment by damencho** [comment]
Hum, that is strange which version of jitsi-meet are you using? And what is the xmpp server?
Currently when I enable password authentication and I enter wrong credentials I see the following dialog:
<img width="647" alt="screen shot 2017-06-30 at 10 19 48" src="https://user-images.githubusercontent.com/3263098/27742324-db957d02-5d7d-11e7-90cb-6cf95cbe045d.png">

**Comment by ctel** [comment]
XMPP Server is Prosody and it's using SASL (plain-insecure; but TLS protected) auth (you can see the rest of the tag in the screenshot) because we use an LDAP with bind auth (only seems to support plain sasl with allow flag in config). Maybe that is the cause of it? I will look up the version and add it here.
