### ISSUE TITLE
not able to build since npm install failing

### ISSUE THREAD

**Issue by cyberbandya007** [jitsi/jitsi-meet#1718]
npm install on fresh checkout failing to build

> lib-jitsi-meet@0.0.0 postinstall /home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet
> webpack -p

/home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:11
    new webpack.LoaderOptionsPlugin({
    ^

TypeError: webpack.LoaderOptionsPlugin is not a constructor
    at Object.<anonymous> (/home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:11:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/skarambelkar/src/jitsi-meet/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/skarambelkar/src/jitsi-meet/node_modules/webpack/bin/webpack.js:39:40)

**Comment by cyberbandya007** [comment]
lib-jitsi-meet is not there in node_modules

skarambelkar@localhost:~/src/jitsi-meet$ ls node_modules/lib*
ls: cannot access node_modules/lib*: No such file or directory

**Comment by virtuacoplenny** [comment]
What version of node/npm are you using? I was having trouble too but was advised to use node 6.x and npm 3.x

**Comment by cyberbandya007** [comment]
skarambelkar@convene-2017:~/src/jitsi-meet$ node -v
v8.0.0
skarambelkar@convene-2017:~/src/jitsi-meet$ npm -v
5.0.0

I will try with node 6.x and npm 3.x. It was working for some time when I tried before few weeks with latest stable node and npm. Let me try with these versions.

**Comment by cyberbandya007** [comment]
Facing the same issue with node 6.11 and npm 3.10.

> lib-jitsi-meet@0.0.0 postinstall /home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet
> webpack -p

/home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:11
    new webpack.LoaderOptionsPlugin({
    ^

TypeError: webpack.LoaderOptionsPlugin is not a constructor
    at Object.<anonymous> (/home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:11:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/skarambelkar/src/jitsi-meet/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/skarambelkar/src/jitsi-meet/node_modules/webpack/bin/webpack.js:39:40)
npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.
npm WARN eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but none was installed.
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by bbaldino** [comment]
Have you tried deleting node_modules and redoing npm install?

**Comment by ctel** [comment]
Maybe [this issue](https://github.com/jitsi/jitsi-meet/issues/1726) is related to this problem?
@cyberbandya007 Did you encounter similar problems during `npm install`?

**Comment by cyberbandya007** [comment]
@bbaldino, yes. I tried removing node_modules and building it with node
6.11 and npm 3.10.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules/ch
okidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@                                                      1.1.2:
wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"}
)
npm WARN eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but
none was                                                       installed.
npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was
installed.
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! Exit status 1

It fails there too.

**Comment by lyubomir** [comment]
> npm install on fresh checkout failing to build

Which jitsi/jitsi-meet commit hash are you on? (For example, do `git log --oneline -1`.)

**Comment by max-allan-surevine** [comment]
If I install webpack with -g first, then do an npm install I get an error :
```
root@ip-10-66-2-27:~/jitsi-meet# npm install

> git-validate@2.2.2 install /root/jitsi-meet/node_modules/git-validate
> node bin/install

module.js:328
    throw err;
    ^

Error: Cannot find module '/root/jitsi-meet/node_modules/git-validate/bin/install'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

I'm just following the instruction in the manual install guide (https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md) and trying to build with npm. 

```root@ip-10-66-2-27:~/jitsi-meet# git log --oneline -1
4eacbd9 fix(tracks): remove mute and videotype listeners on track remove```
Using packaged versions of node and npm from an Ubuntu 16.04 deployment on AWS:
```root@ip-10-66-2-27:~/jitsi-meet# node -v
v4.2.6
root@ip-10-66-2-27:~/jitsi-meet# npm -v
3.5.2
```

I note that the `/root/jitsi-meet/node_modules/git-validate` it mentions, doesn't exist.


I also tried it on 14.04. And had a similar issue. After installing latest node and doing the npm install :
```npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> git-validate@2.2.2 install /root/jitsi-meet/node_modules/git-validate
> node bin/install

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/jitsi-meet/node_modules/git-validate/bin/install'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
jitsi-meet@0.0.0 /root/jitsi-meet
├─┬ @atlaskit/avatar@4.0.5 
│ ├── @atlaskit/util-shared-styles@2.6.0 
```
..... 
```npm ERR! node v6.11.1
npm ERR! npm  v3.10.10```

I can drop full logs here if anyone is interested. I think those are the interesting bits though.

**Comment by RavinduRoshan** [comment]
@max-allan-surevine  Install nodejs-legacy by `sudo apt-get install nodejs-legacy` and try `npm install` again. use nodev6.11 and npmv3.10.
