### ISSUE TITLE
"API" for mobile SDK

### ISSUE THREAD

**Issue by philrykoff** [jitsi/jitsi-meet#1720]
When using the JavaScript API as described at https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md, I can execute commands within the embedded Jitsi instance, e.g. change displayName, toggle audio / video or hang up.

As I am implementing Jitsi within my iOS app, I look for a similar functionality, but the only thing configurable seems to be the `welcomePageEnabled` property (both within Android / iOS). Maybe I could "hang up" by loading an invalid URL / null with `loadURL`.

Are there any other possibilities yet on how to override UI parameters or execute commands (e.g. set displayName, toggle audio / video)?

As the code seems to be shared from within web and mobile apps, maybe you could give me a hint on how to approach that?

**Comment by saghul** [comment]
Hi!

The mobile SDK is pretty recent, and we are making changes as we go. There is currently no more functionality implemented in the (mobile) API as what you already saw.

**Comment by philrykoff** [comment]
Okay, thanks!
