### ISSUE TITLE
no audio and Video 

### ISSUE THREAD

**Issue by wangxue16292016** [jitsi/jitsi-meet#1722]
i install jitsi with quick install .we can access the website correct in a lan ,but in the website we can't see the video and audio .

the log 
JVB 2017-07-03 16:11:40.612 WARNING: [54449] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2017-07-03 16:11:40.612 WARNING: [54449] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 6ee0e78e not ready yet.
how could i handle this

**Comment by saghul** [comment]
What browser are you using? Do you see any other errors in the JavaScript console?

**Comment by wangxue16292016** [comment]
no error in the console,but we can get the infomation form the chat panel 
<img width="210" alt="default" src="https://user-images.githubusercontent.com/17420512/27792708-a12f99e2-602d-11e7-8d92-b306d1b951b5.png">

**Comment by wangxue16292016** [comment]
Jicofo 2017-07-03 20:16:41.475 INFO: [58] org.jitsi.jicofo.BridgeState.log() Adding 3 video streams on jitsi-videobridge.csimy.com video channels: 0 video streams: 0 diff: 4 (estimated: 4)
Jicofo 2017-07-03 20:16:41.490 INFO: [125] org.jitsi.jicofo.LipSyncHack.log() Not merging A/V streams from test1@conference.csimy.com/f052926a to test1@conference.csimy.com/58f8c9b9
Jicofo 2017-07-03 20:16:41.490 INFO: [125] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.initiateSession().106 INVITE PEER: test1@conference.csimy.com/58f8c9b9
Jicofo 2017-07-03 20:16:43.959 INFO: [57] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Received SSRCs from test1@conference.csimy.com/58f8c9b9 SSRCs{ audio: [2814085831 3959933500 ] video: [826246394 3666630042 ] }@2045977810
Jicofo 2017-07-03 20:16:43.961 INFO: [57] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.sendAddSourceIQ().432 Notify add SSRC test1@conference.csimy.com/f052926a SID: 4f61klrq9p140 SSRCs{ audio: [2814085831 3959933500 ] video: [826246394 3666630042 ] }@2045977810 SSRC_Groups{ }@1214302686

**Comment by wangxue16292016** [comment]
this is jvb.log and jicofo.log

**Comment by saghul** [comment]
None of those indicate an error, are you sure you don't see anything at all in the browser JavaScript console?

**Comment by wangxue16292016** [comment]
sorry ,i made a mistake ,the error in the console :
`Error: Permission denied to access property "apply"`

[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 29.1 error 0 happened
堆栈跟踪：
t.default/Strophe.log@https://csimy.com/libs/lib-jitsi-meet.min.js?v=1967:30:27446
error@https://csimy.com/libs/app.bundle.min.js?v=1967:104:7409
_onRequestStateChange@https://csimy.com/libs/app.bundle.min.js?v=1967:105:3731

[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: Error: Permission denied to access property "apply" "Script: https://csimy.com/libs/lib-jitsi-meet.min.js?v=1967" Line: 1 Column: 5470 StackTrace:  Error: Permission denied to access property "apply"

堆栈跟踪：
n@https://csimy.com/libs/lib-jitsi-meet.min.js?v=1967:1:5470
init/window.onerror@https://csimy.com/libs/app.bundle.min.js?v=1967:87:11352
callErrorHandler@https://csimy.com/libs/lib-jitsi-meet.min.js?v=1967:1:5773
t.default/Strophe.log@https://csimy.com/libs/lib-jitsi-meet.min.js?v=1967:30:27419
error@https://csimy.com/libs/app.bundle.min.js?v=1967:104:7409
_onRequestStateChange@https://csimy.com/libs/app.bundle.min.js?v=1967:105:3731
