### ISSUE TITLE
Building after fresh checkout fails!

### ISSUE THREAD

**Issue by ctel** [jitsi/jitsi-meet#1726]
I have trouble "installing" jitsi-meet sources after successful checkout (version 152427e on master) into a clean directory. The development system runs on _Ubuntu 16.04 LTS_ (within VirtualBox), npm (Version _3.5.2-0ubuntu4_), nodejs-legacy (Version _4.2.6~dfsg-1ubuntu4.1_). Everything has been installed as instructed [here](https://github.com/jitsi/jitsi-meet#building-the-sources).
Errors occour during the execution of `npm install`
It seems that the _webpack_ dependencies (is referenced multiple times as dependency) could not be fetched! Additionally I encountered several deprecation (easy-fix?) warnings during `npm install` (see below).
This issue might be related to https://github.com/jitsi/jitsi-meet/issues/1718
Maybe this (stripped) log sheds light on the problem (I also stripped the loading bars for better readablity; `[...]` means I omitted a part to shorten this text):

> _npm_ **WARN** deprecated jssha@1.5.0: jsSHA versions < v2.0.0 will no longer receive features
> _npm_ **WARN** deprecated strophe@1.2.4: This package is no longer maintained; use 'strophe.js' instead.
> **WARN** engine skatejs@0.13.17: wanted: {"node":">=0.12.x","npm":"2.x.x"} (current: {"node":"4.2.6","npm":"3.5.npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> _npm_ **WARN** deprecated bower@1.7.7: ..psst! While Bower is maintained, we recommend Yarn and Webpack for \*new\* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
> _npm_ **WARN** deprecated ignore@2.2.19: several bugs fixed in v3.2.1
> _npm_ **WARN** deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> _npm_ **WARN** deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> _npm_ **WARN** deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> _npm_ **WARN** deprecated node-uuid@1.4.8: Use uuid module instead
> _npm_ **WARN** deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> _npm_ **WARN** deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> _npm_ **WARN** deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> _npm_ **WARN** deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> _npm_ **WARN** deprecated node-uuid@1.4.7: Use uuid module instead
*`[...]`*
> **WARN** engine loader-runner@2.3.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
*`[...]`*
> `├─┬` @ atlassian/aui@6.0.6
*`[...]`*
> `│ ├──` UNMET DEPENDENCY eslint@2.1.0
*`[...]`*
> `├─┬` babel-preset-es2015@6.24.1
*`[...]`*
> `│ ├──` babel-plugin-transform-es2015-modules-amd@6.24.1
> _npm_ **WARN** optional Skipping failed optional dependency /chokidar/fsevents:
> _npm_ **WARN** notsup Not compatible with your operating system or architecture: fsevents@1.1.2
> _npm_ **WARN** notsup Not compatible with your operating system or architecture: fsevents@1.1.2
> _npm_ **WARN** eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but none was installed.
> _npm_ **ERR!** Linux 4.4.0-83-generic
> _npm_ **ERR!** argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> _npm_ **ERR!** node v4.2.6
> _npm_ **ERR!** npm v3.5.2
> _npm_ **ERR!** path ../acorn/bin/acorn
> _npm_ **ERR!** code EROFS
> _npm_ **ERR!** errno -30
> _npm_ **ERR!** syscall symlink
> _npm_ **ERR!** rofs EROFS: read-only file system, symlink '../acorn/bin/acorn' -> '/media/sf_share/jitsi/jitsi-meet/node_modules/.bin/acorn'
> _npm_ **ERR!** rofs This is most likely not a problem with npm itself
> _npm_ **ERR!** rofs and is related to the file system being read-only.
> _npm_ **ERR!** rofs
> _npm_ **ERR!** rofs Often virtualized file systems, or other file systems
> _npm_ **ERR!** rofs that don't support symlinks, give this error.
> `│ │ └──` babel-plugin-transform-strict-mode@6.24.1
*`[...]`*
> `├──` **UNMET PEER DEPENDENCY** eslint@>=2.0.0
*`[...]`*
> `├──` **UNMET PEER DEPENDENCY** webpack@2
*`[...]`*
> `├─┬` webpack-dev-server@2.4.5
*`[...]`*
> `│ ├──` **UNMET PEER DEPENDENCY** webpack@^1.0.0 || ^2.0.0 || ^3.0.0
*`[...]`*
> _npm_ **ERR!** Linux 4.4.0-83-generic
> _npm_ **ERR!** argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> _npm_ **ERR!** node v4.2.6
> _npm_ **ERR!**
> _npm_ v3.5.2
> _npm_ **ERR!** path npm-debug.log.1641229291
> _npm_ **ERR!** code ETXTBSY
> _npm_ **ERR!** errno -26
> _npm_ **ERR!** syscall rename
*`[...]`*

Is there an easy solution for my problem or is this a mayor problem? Should I try another version? Which one is considered stable enough to include latest fixes?

**Comment by cyberbandya007** [comment]
@ctel, I don't believe jitsi-meet supports 16.04 LTS yet. Please try to build on ubuntu 14.04 and let us know how you find out.

**Comment by cyberbandya007** [comment]
@ctel, you also need to upgrade your node and npm versions to make it work on ubuntu 14.04. 'npm install' fails on legacy nodejs. Try with latest stable version.

**Comment by lyubomir** [comment]
```
npm ERR! path ../acorn/bin/acorn
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall symlink
npm ERR! rofs EROFS: read-only file system, symlink '../acorn/bin/acorn' -> '/media/sf_share/jitsi/jitsi-meet/node_modules/.bin/acorn'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
```

Is there anything special about the file system as mentioned in the above?

**Comment by ctel** [comment]
Yup that problem is probably not jitsi related: I checked out jitsi-meet within a host-shared folder of VirtualBox. The filesystem is writable, but symbolic links cannot be created. Strangely ubuntu reports that the filesystem being not writable, but creating folders and files work just fine, so the problem was unnoticed before. So this portion of the problem can be ignored...
Thus I again cloned the repository and executed `npm install` at a safe location within my virtual user home, and the errors vanished. Only some warnings are still thrown (_Skipping failed optional dependency /chokidar/fsevents:_ `[...]`), but I think thats okay?
