### ISSUE TITLE
blank screen 

### ISSUE THREAD

**Issue by FanHoo** [jitsi/jitsi-meet#1729]
first I did "setWelcomePageEnabled(false)" in MainActivity , then  I use "loadURL()" into a room .  when I press "hangup" It's not exit app , a blank screen  shows up ,please take a look .

**Comment by saghul** [comment]
This is the expected behavior. If no welcome screen is used the activity renders nothing after the conference is ended. What are you trying to accomplish?

**Comment by FanHoo** [comment]
@saghul we expect user can invite other users into a specified room (we have already got a IM ,so we can use it to send the invitation)   the user been invited just click "accept" to join the meet room 
,so I don't need the welcome page .

**Comment by saghul** [comment]
Sure, that makes sense. Then you'd need to start an activity upon pressing accept, and add a listener for the disconnect event, in which case you'd finish the activity.

**Comment by FanHoo** [comment]
@saghul what exactly the listener is ?  I just saw a Interface file "JitsiMeetViewListener" in your sdk module , but it not work for me.
