### ISSUE TITLE
Android sdk as standalone aar/library

### ISSUE THREAD

**Issue by jackwang1** [jitsi/jitsi-meet#1748]
Any examples or recommendations on how this can be done?

**Comment by lyubomir** [comment]
The Jitsi Meet SDK for Android has multiple dependencies and we do not provide a way to bundle them all in a fat AAR. We've published the dependencies as Maven artifacts in our Maven repository at https://github.com/jitsi/jitsi-maven-repository - take a look at https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/com/facebook/react. We'll open source the script that publishes them and we'll also publish the SDK artifact in the same Maven repository. But I cannot give you an ETA of multiple other priorities.

**Comment by lyubomir** [comment]
* We now provide Jitsi Meet SDK for Android as a Maven artifact. Please refer to https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#install for details.
* The build.gradle files in master have been updated with the source code which produces the Maven artifact.
