### ISSUE TITLE
website confusion: 2 URLs? one doesn't work fully

### ISSUE THREAD

**Issue by knocte** [jitsi/jitsi-meet#1749]
I know two URLs to access Jitsi:

- https://meet.jitsi.net/
- https://meet.jit.si/

The first one has limited capabilities for me (screen sharing doesn't work). Why have two websites instead of one?

**Comment by saghul** [comment]
Where did you get a reference to the first one?

**Comment by knocte** [comment]
I don't remember, google?

**Comment by aaronkvanmeerten** [comment]
The short answer is that the first one is a development URL and probably won't be around very long.  It’s not clear where you might have found it, but we don’t advertise it and we don’t recommend it for use.

Cheers,

-Aaron

**Comment by saghul** [comment]
> I don't remember, google?

Holler if you find a reference to it so we can change it. Cheers!
