### ISSUE TITLE
Chat is not functional in conferences with more participants.

### ISSUE THREAD

**Issue by tkd4444** [jitsi/jitsi-meet#1752]
Hi Guys,

I'm having a little issue.
When we having conferences with more participants (like 10 or so ) for some, the chat is not functional. It's just blank. After some page refreshes the chat suddenly start working and loads all the previous written comments.

Any ideas ?

From which component will you need the log file from ?

Thanks !

**Comment by damencho** [comment]
Have you checked the console logs of the browser when it is not working? We had a similar issue which for sure was fixed in nightlies.

**Comment by damencho** [comment]
This is the fix: https://github.com/jitsi/jitsi-meet/commit/2a0973a8979b72cdb0f26fb68e0dcaabae29b81e
And I see this is not yet in stable.

**Comment by tkd4444** [comment]
I haven't, I'm gonna check. Thanks ! But it's not so easy to reproduce :-)
We are not using nightlies really. Do you plan to release a stable update soon ?

Thanks a lot !

**Comment by damencho** [comment]
I hope so, there is still a UI work to be done for one dialog which is blocking the release.

**Comment by tkd4444** [comment]
Cool, I was looking, but haven't find anything. Do you track some release-notes on updates ?

**Comment by damencho** [comment]
Currently no.
