### ISSUE TITLE
unstable debian package unmet web-config dependency

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1753]
Freshly installed Debian 8 64 bit (all up to date).

apt-get -y install jitsi-meet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-web-config (= 1.0.2087-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by damencho** [comment]
That is strange, the only explanation I have is hitting the server in
the moment that version was uploading. Can you try again?
apt-get udpate
apt-get install jitsi-meet

I just tried it and it works here.

**Comment by petervnv** [comment]
Strange. Still getting the same error after doing a fresh apt-get update

uname -a
Linux hero 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
cat /etc/debian_version
8.8

apt-get install jitsi-meet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-web-config (= 1.0.2087-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Should I try the testing repo instead? How far back is it from testing? Is there any changelog somehwere?

**Comment by petervnv** [comment]
Or perhaps there's some package I need to install beforehand considering this is a minimal debian install?

**Comment by petervnv** [comment]
Hmmm, just realized my minimal debian installation doesn't even have java.
Let me install jdk 8 and try again

**Comment by damencho** [comment]
This should be installed automatically, java 7 or java 8 ... I will bring up a debian 8 machine and will test it in the afternoon.

**Comment by petervnv** [comment]
OK, I installed jdk 8 and now it installed as expected.
Going to test it out now.

It seems some minimal debian 8 distros don't even have java by default and we need to install is ourselves.

Go ahead and close this ticket. Sorry for wasting your time

cheers
