### ISSUE TITLE
nightly debian testing feedback

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1754]
I figured it was better to open a new issue instead of continuing on previous one.

Just did a fresh install on debian 8 and the nightly seems buggy.

When using Firefox (54), as soon as the 2nd participant enters we get a black screen and no audio from remote.

Did the same exact test on Chrome (59.0.3071.115) and indeed p2p works as expected even though the chrome console shows the following ICE error:

Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.setup_failed Error: ICE fail
    at r.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:414)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TraceablePeerConnection.js:242)

But as soon as a 3rd participant enters, and I presume the conference is moved to jvb, then we get the same black screen result we had with Firefox previously.

**Comment by petervnv** [comment]
testing again with firefox 54 with both clients behind same LAN (previously p2p worked fine), and I'm able to get audio/video although it is relayed through jvb instead of the expected p2p.

Interestingly, if one of the clients is chrome, and the other firefox, then the conference fails.

If both use chrome, p2p works as expected, but when 3rd participant enters we get black screen.

**Comment by petervnv** [comment]
Here are the errors I see on ffox console when the 2nd ffox participant joins:

XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168

[modules/xmpp/JingleSessionPC.js] <value>:  Renegotiate: setting remote description  lib-jitsi-meet.min.js:2:161499
Halt: There are no SSRC groups in the remote description.  lib-jitsi-meet.min.js:2:566959
[modules/xmpp/JingleSessionPC.js] <a/<>:  Error renegotiating after setting new remote answer: TypeError: e.payloads.split is not a function Object { media: Array[2], raw: "v=0 o=- 1923518516 2 IN IP4 0.0.0.0…", session: "v=0 o=- 1923518516 2 IN IP4 0.0.0.0…" }  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/JingleSessionPC.js] <value/<>:  setAnswer failed:  TypeError: e.payloads.split is not a function
Stack trace:
preferVideoCodec@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:33587
r.prototype.setRemoteDescription@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:338133
value@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:502872
value/<@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:502101
_@https://jitsi.my.domain/libs/app.bundle.min.js?v=2087:2:1851067
value@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:501957
a@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:495681
value@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:500876
process@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:218632
o@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:574343
a@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:574521
n@https://jitsi.my.domain/libs/lib-jitsi-meet.min.js?v=2087:2:575054
  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/JingleSessionPC.js] <r/<>:  addIceCandidate failed! DOMException [InvalidStateError: "setRemoteDescription needs to called before addIceCandidate"
code: 11
nsresult: 0x8053000b]  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/JingleSessionPC.js] <r/<>:  addIceCandidate failed! DOMException [InvalidStateError: "setRemoteDescription needs to called before addIceCandidate"
code: 11
nsresult: 0x8053000b]  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/JingleSessionPC.js] <value/this.peerconnection.oniceconnectionstatechange>:  (TIME) ICE connected P2P? false:	 194598.855  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/strophe.jingle.js] <value>:  on jingle source-add from 123@conference.jitsi.my.domain/focus <iq type="set" to="4a44a99c-3ec9-46fd-9143-246f186b9dac@jitsi.my.domain/dc3ccfba-d412-4da5-ac68-c6bf344f22ee" from="123@conference.jitsi.my.domain/focus" id="NGE0NGE5OWMtM2VjOS00NmZkLTkxNDMtMjQ2ZjE4NmI5ZGFjQGJ1YmJsZS5wcml2dXMubmV0d29yay9kYzNjY2ZiYS1kNDEyLTRkYTUtYWM2OC1jNmJmMzQ0ZjIyZWUAeXRXd0stMjQzAH1VDwsdlWuIcNaC/I11B24=" xmlns="jabber:client">  lib-jitsi-meet.min.js:2:161499
[modules/RTC/BridgeChannel.js] <e>:  constructor() with peerconnection  lib-jitsi-meet.min.js:2:161499


XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168
[modules/xmpp/JingleSessionPC.js] <i>:  Processing addRemoteStream  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/JingleSessionPC.js] <i>:  ICE connection state:  connected  lib-jitsi-meet.min.js:2:161499
[modules/xmpp/JingleSessionPC.js] <value>:  Renegotiate: setting remote description

**Comment by petervnv** [comment]
Is this feedback on testing the nightly package useful to the dev team?
Do you need me to perform any other tests?

Cheers,
Peter

**Comment by saghul** [comment]
We (@damencho ?) are currently chasing some Firefox bugs, let's keep this open. Sorry for the delay and thanks for your report!

**Comment by damencho** [comment]
Well, the one I'm chasing is an actual crash, where the whole browser crashes or the tab itself.

**Comment by petervnv** [comment]
No problem, I thought it was just me having issues so I closed it.

I'll update my installation to latest nightly over the weekend and will perform some more tests

**Comment by petervnv** [comment]
OK, well I updated my nightly install yesterday and I've done some more testing.

When using Chrome on both ends everything seems to work as expected (p2p when only 2 participants and moves to jvb when 3rd joins), although for some reason the resolution that comes out the camera on an iMac seems to be pretty bad even when in p2p on same LAN.

With Firefox (on ubuntu and OSX, haven't tried windows) p2p does not seem to work at all, even though both clients are in the same LAN like the Chrome tests. In fact it seems with Firefox that more than one transport (udp and tcp) and port are used which makes no sense. When hovering over the "antenna" it shows transport: udp and tcp and remote ports: also shows 2 ports.

**Comment by petervnv** [comment]
Here's what I mean by firefox weirdness https://imagebin.ca/v/3UUcgNg8nmGi

**Comment by petervnv** [comment]
Also still getting a lot of 
XML Parsing Error: not well-formed Location: Line Number 1, Column 168:
errors in the console

and after the other Firefox peer joins the room I still get a lot of the XML parsing error messages above, as well as
non-maplike pc.getStats access is deprecated, and will be removed in the near future! See http://w3c.github.io/webrtc-pc/#getstats-example for usage.

but the most important ones which seem to explain the problems:

[modules/xmpp/JingleSessionPC.js] <a/<>:  Error renegotiating after setting new remote answer: Error: An unmapped SSRC was found. Object { media: Array[2], raw: "v=0 o=- 1923518516 2 IN IP4 0.0.0.0…", session: "v=0 o=- 1923518516 2 IN IP4 0.0.0.0…" }  lib-jitsi-meet.min.js:2:162321
[modules/xmpp/JingleSessionPC.js] <value/<>:  setAnswer failed:  Error: An unmapped SSRC was found.
Stack trace:
r.prototype.toUnifiedPlan/</<@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:568794
r.prototype.toUnifiedPlan/<@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:568121
r.prototype.toUnifiedPlan@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:567373
r.prototype.setRemoteDescription@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:342875
value@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:508921
value/<@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:508150
_@https://my.domain.com/libs/app.bundle.min.js?v=2151:2:2101319
value@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:508006
a@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:501696
value@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:506925
process@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:219879
o@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:580509
a@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:580687
n@https://my.domain.com/libs/lib-jitsi-meet.min.js?v=2151:2:581220
  lib-jitsi-meet.min.js:2:162321
[modules/xmpp/JingleSessionPC.js] <r/<>:  addIceCandidate failed! DOMException [InvalidStateError: "setRemoteDescription needs to called before addIceCandidate"
code: 11
nsresult: 0x8053000b]  lib-jitsi-meet.min.js:2:162321

**Comment by petervnv** [comment]
Let me know if you need me to do any more tests

**Comment by petervnv** [comment]
Is it normal to have 2 transports and 2 remote ports as I described above?
 screenshot here https://imagebin.ca/v/3UUcgNg8nmGi

**Comment by damencho** [comment]
Not sure about that, it can be jvb and p2p stats.
I was recently fixing this for FF https://github.com/jitsi/lib-jitsi-meet/commit/4db182d22e73eaa3f0a3902ca94cdc64496bfbdc
It can be that something changed in FF not sure, this needs checking. When I go to meet.jit.si and create chrome to FF call I see two addresses and two ports.

**Comment by petervnv** [comment]
Yeah I get the same thing. Pretty weird. It doesn't seem to happen from Chrome to Chrome, only when Ffox is mixed in.

**Comment by petervnv** [comment]
Just tested again with FF 54 on Ubuntu and Mint in beta.meet.jit.si and
indeed FF is pretty buggy.

I didn't get a black screen this time, but I also didn't get a p2p
connection between both browsers (both lying behind same router), and I did
get that weird scenario I mentioned above where FF shows 2 transports and 2
ports.

I also got frozen video coming from the Mint machine and had to refresh on
Ubuntu to get video back. And after that I got a FF crash.

I think others are also experiencing similar issues as reported here
http://lists.jitsi.org/pipermail/users/2017-August/013424.html


I'm about to test out beta.meet.jit.si with latest Chrome Version
60.0.3112.90 (Official Build) (64-bit) on Ubuntu.

Cheers,
Peter

**Comment by petervnv** [comment]
OK, just tested beta.meet.jit.si with newest Chrome (60.0.3112.90) and the site rejected my camera and mic right away, so not much testing possible at all.

See screenshot with console here https://imagebin.ca/v/3VdQ7za3eOhm

Let me know when you need more testing done.

Cheers

**Comment by damencho** [comment]
Hey, 
You are trying to access http://beta.meet.jit.si, try https://beta.meet.jit.si. There is no automatic redirection there between http and https.

**Comment by petervnv** [comment]
By the way, I never got prompted to give access to mic and camera. The console shows user denied permission but in fact there was no usual prompt asking for permission. Even refreshing the page did not lead to any prompt.

P.S. I just saw damencho's message and will test again with https

**Comment by petervnv** [comment]
OK, testing Chrome (60.0.3112.90) with https://beta.meet.jit.si seems OK and I do get p2p and only UDP transport as expected.
I'll try again FF later and report back.

Cheers

**Comment by petervnv** [comment]
OK, tested on https://beta.meet.jit.si this time with Firefox 54.0 on Ubuntu 16.04 and Firefox 64.0.1 on OSX 10.12.6

I'm not able to get p2p (unlike with Chrome) and there are lots of errors in the console, as well as the weird 2 transports + 2 ports I've described before.

Screenshots of the console are here https://imagebin.ca/v/3VjLwOklL8ym, here https://imagebin.ca/v/3VjMtigKlhFA , here https://imagebin.ca/v/3VjN2SgzEKKO and here https://imagebin.ca/v/3VjNviyOjE8W

Let me know when these issues have been corrected in nightly packages so I can update and then test again.

Cheers

**Comment by saghul** [comment]
> there are lots of errors in the console,

You can disregard the XML parsing errors.

**Comment by saghul** [comment]
@paweldomas can you PTAL at the 3rd image? That looks like a legit issue.

**Comment by petervnv** [comment]
Hi again,

Just updated to latest unstable (jicofo 1.0-365-1, jitsi-meet-web 1.0.2237-1, jitsi-meet-web-config 1.0.2237-1, jitsi-meet-prosody 1.0.2237-1, jitsi-videobridge 989-1) and the multiple transports/ports issue in FFox remains.

Also, only with Chrome was I able to have a p2p session. Firefox (55.0.2 on Mint x64) always relays through JVB with the weird transports/ports issue mentioned before, even when both clients are behind same NAT and can talk directly (p2p works fine with Chrome)

Cheers,
Peter

**Comment by petervnv** [comment]
Hi guys,

Is this feedback of any use? I'm still seeing the bugs with Ffox (p2p never works, multiple transports and ports) I've mentioned many times.
Not sure if you guys need me to do any more testing...

Cheers,
Peter

**Comment by saghul** [comment]
Definitely useful. Sorry if we haven't been more responsive, our hands are pretty full, but all feedback is appreciated, even if it may take some time for us to react to it.

**Comment by petervnv** [comment]
No problem. Not sure if you need any console logs or whatever other info I can get you regarding the ffox bugs.

Just let me know how can I help further.

Cheers,
Peter

**Comment by petervnv** [comment]
Hi guys,

Just tested with Ffox 55.0.2 on beta.meet.jit.si and still not able to get p2p working despite the same exact setup working fine with Chrome.

In fact the old multiple transports/ports bug is still there. See  screenshot here https://imagebin.ca/v/3apH8pQVKl6P

Are you guys able to get p2p working with Firefox? If so, what version and platform?

Cheers,
Peter

**Comment by petervnv** [comment]
Closing this issue and opening a new firefox specific ticket since that problem seems to remain unaddressed.
