### ISSUE TITLE
Make fails after clean `npm install`

### ISSUE THREAD

**Issue by ctel** [jitsi/jitsi-meet#1758]
After clone and `npm install` a subsequent `make` fails with:
> ./node_modules/.bin/webpack -p
> /home/mml/Dokumente/jitsi-meet/webpack.config.js:206
> function devServerProxyBypass({ path }) {
> ___________________________________^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at requireConfig (/home/mml/Dokumente/jitsi-meet/node_modules/webpack/bin/convert-argv.js:96:18)
>     at /home/mml/Dokumente/jitsi-meet/node_modules/webpack/bin/convert-argv.js:109:17
>     at Array.forEach (native)
> Makefile:16: recipe for target "compile" failed
> make: *** [compile] Error 1

**Comment by saghul** [comment]
What Node version are you using?

**Comment by ctel** [comment]
This bug is subsequent to this one [#1726](https://github.com/jitsi/jitsi-meet/issues/1726) here. I'm on ubuntu 16.04 and `node --version` shows `v4.2.6`. I followed the guide from the readme [here](https://github.com/jitsi/jitsi-meet#building-the-sources). I haven't tried ubuntu 14.04 yet (as @cyberbandya007 suggested), because other parts of the system run on ubuntu 16.04 and having two machines is uncool...)

**Comment by saghul** [comment]
Can you try to update to Node 6? I checked and 4 does support object literal property shorthands, but we all use Node >= 6 around here, so maybe it's time we update the requirements.

**Comment by ctel** [comment]
Okay. I installed `node v6.11.0` from `deb.nodesource.com/node_6.x`. `npm install` executed in a clean git-repository `clone` works as expected, despite several deprecation warnings are thrown (**jssha**@_1.5.0_, **strophe**@_1.2.4_, **bower**@_1.7.7_, several times **minimatch**, **ignore**@_2.2_, ...). Are there any plans to adress those warnings soon?
Even `make` within the old (`npm install` had been executed by node `v4.2.6`) folder worked now with `v6.11.0`. Both `make` runs produced some files. I appended the log from my clean install with node `v6.11.0` in [make_log.txt](https://github.com/jitsi/jitsi-meet/files/1136341/make_log.txt)

**Comment by saghul** [comment]
IIRC those warnings are not coming from jitsi-meet itself, but from its dependencies.

**Comment by saghul** [comment]
See https://github.com/jitsi/jitsi-meet/pull/1760

**Comment by ctel** [comment]
Okay! Thanks 👍
