### ISSUE TITLE
How to set own DisplayName from XMPP stream?

### ISSUE THREAD

**Issue by ctel** [jitsi/jitsi-meet#1759]
We do prosody authentication via LDAP. Strangely on login the own DisplayName is not set. Which XMPP stanzas does jitsi need to set the own DisplayName properly?

**Comment by damencho** [comment]
This is a lib-jitsi-meet feature which is not implemented and was mentioned recently by @guusdk. The feature missing should retrieve the vcard for the account in case of authentication enabled, and this way it can retrieve display name and avatar from the server.

**Comment by ctel** [comment]
How complex is this to implement? Where would one start implementing this? Are there any plans yet? Is there a way to integrate custom scripts/style without having to use the iframe? If there is a way, could we build on a stable api while directly subscribing somehow to connection events from strophe.js as a temporary workaround?

**Comment by damencho** [comment]
This feature is not currently on our roadmap. This should be implemented somewhere in: 
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/xmpp.js
or
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/ChatRoom.js
Not sure that this can be done over iframe API, maybe it can be done, but I haven't look at it in details. Any PRs are welcome.

**Comment by inkhey** [comment]
This feature will be very useful in order to integrate correctly with XMPP. Ability to have the feature in both way (jitsi room nickname are xmpp room nickname) will be great.

**Comment by inkhey** [comment]
Same bug as #1270 .
Jitsi meet use XEP-0172 to display nickname in muc chatroom of xmpp. This usage is now discouraged according to the XEP itself : https://xmpp.org/extensions/xep-0172.html#former . In order to provide correct compatibility with other xmpp program, jitsi should find a solution to provide the standard resource as nickname, so no possibility of 2 same nickname.
