### ISSUE TITLE
Jitsi Meet API does not work with Chromium (Debian Jessie)

### ISSUE THREAD

**Issue by dbareiro** [jitsi/jitsi-meet#1762]
Hi!

Doing some testing in Debian Jessie, Firefox 52.2.0 ESR seems to work well with the API, but in Chromium 57.0.2987.98 I only get a gray iframe with nothing else. These are the errors I'm seeing in the Chromium Javascript console:

https://ibin.co/3Sc2FI7onOQG.jpg

Talking with Saúl at dev@jitsi.org, he was also able to reproduce this, so he asked me to open this issue.

Thanks in advance.

Kind regards,
Daniel

**Comment by dbareiro** [comment]
Hi again!

Apparently this is related to the default security settings in Chromium. Unchecking Settings-> Show advanced settings-> Privacy-> Content Settings-> Block third-party cookies and site data, I can access the conference room.

I've tried with Chrome stable and I did not have this problem so it looks like Chrome has a more permissive security setting.

Is there anything we can do in this scenario with Chromium users?

Kind regards,
Daniel

**Comment by saghul** [comment]
I think we should fail gracefully if window.localStorage doesn't work for whatever reason.

**Comment by dbareiro** [comment]
Hi, Saúl.

> I think we should fail gracefully if window.localStorage doesn't work for whatever reason.

Do you mean to show some text asking the users to check theirs security settings or you were thinking something different?

Kind regards,
Daniel

**Comment by guyviner** [comment]
Chrome Version 80.0.3987.132  , still experiencing this issue because of "Block Third-Party Cookies" 

I think most people have this setting "Enabled", which prevents the Jitsi Web Meet API from being useful in Production ... is there a workaround yet ?

**Comment by saghul** [comment]
I have that setting turned on and I have no such problem (on macOS). Is local storage available for you if you access the site directly? Or just when using the iframe API?

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/6529
