### ISSUE TITLE
Mobile app can't open the local camera

### ISSUE THREAD

**Issue by TangXT** [jitsi/jitsi-meet#1764]
I intalled the jitsi app v1.6 from AppStore on my iPad3 with iOS 9.3.5 and I find it can't open the local camera but before I install v1.6, The jitsi app v1.4 works fine on my iPad3.
The Android app also has the similar problems, while I use jitsi app v1.3 it works fine on my Android TV(Android 6.0.1), but v1.4 can't open the local camera.
That's why??

**Comment by MetroMarv** [comment]
I experience the same problem on my iPad 2 using iOS 9.3.5.

**Comment by lyubomir** [comment]
@TangXT & @MetroMarv, thank you for your feedback! It's certainly nothing that we did on purpose so we'll need to debug/investigate. In the meantime, please feel free to look into it yourself and contribute a fix.

**Comment by TangXT** [comment]
This is my debug logs with Android 6.0.1  @lyubomir
D/AudioMode: Update audio route for mode: 0
D/AudioManager: setMode: mode = 0
D/AudioManager: setSpeakerphoneOn(false)
D/AudioManager: setBluetoothScoOn: on = false
D/AudioManager: stopBluetoothSco
I/ReactNativeJS: '[modules/RTC/ScreenObtainer.js]', '<n>: ', 'Screen sharing not supported by the current browser: ', 'rtc_browser.react-native', 'react-native'
I/ReactNativeJS: '[modules/RTC/ScreenObtainer.js]', '<n>: ', 'Desktop sharing disabled'
I/ReactNativeJS: '[__filename]', '<r>: ', 'Start muted: '
I/ReactNativeJS: '[modules/RTC/RTCUtils.js]', '<n>: ', 'Get media constraints', { audio: false,
                   video: 
                    { mandatory: { minWidth: 1280, minHeight: 720, maxWidth: 1280, maxHeight: 720 },
                      optional: [ { facingMode: 'user' } ],
                      facingMode: 'user',
                      width: { ideal: 1280 },
                      height: { ideal: 720 } } }
I/com.oney.WebRTCModule.WebRTCModule: getUserMedia(video): { NativeMap: {"height":{"ideal":720},"width":{"ideal":1280},"facingMode":"user","optional":[{"facingMode":"user"}],"mandatory":{"maxHeight":720,"maxWidth":1280,"minHeight":720,"minWidth":1280}} }
I/CameraManagerGlobal: Connecting to camera service
D/com.oney.WebRTCModule.WebRTCModule: Creating video capturer using Camera1 API.
I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 0
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 0
I/ReactNativeJS: '[modules/RTC/RTCUtils.js]', '<n>: ', 'Available devices: ', [ { facing: 'back',
                     label: 'Camera 0, Facing back, Orientation 0',
                     kind: 'videoinput',
                     deviceId: '0',
                     groupId: null },
                   { facing: null,
                     label: 'Audio',
                     kind: 'audioinput',
                     deviceId: 'audio-1',
                     groupId: null } ]
W/ReactNativeJS: '[modules/RTC/RTCUtils.js]', '<n>: ', 'Failed to get access to local media. Error ', { name: null,
                   message: 'Failed to create new track',
                   constraintName: undefined }, { audio: false,
                   video: 
                    { mandatory: { minWidth: 1280, minHeight: 720, maxWidth: 1280, maxHeight: 720 },
                      optional: [ { facingMode: 'user' } ],
                      facingMode: 'user',
                      width: { ideal: 1280 },
                      height: { ideal: 720 } } }
E/ReactNativeJS: '[modules/RTC/RTCUtils.js]', '<n>: ', 'failed to obtain video stream - stop', [gum.general: Failed to create new track]
E/unknown:ReactNative: console.error: "[modules/RTC/RTCUtils.js]", "<n>: ", "failed to obtain video stream - stop", {"gum":{"error":{"name":null,"message":"Failed to create new track"},"constraints":{"audio":false,"video":{"mandatory":{"minWidth":1280,"minHeight":720,"maxWidth":1280,"maxHeight":720},"optional":[{"facingMode":"user"}],"facingMode":"user","width":{"ideal":1280},"height":{"ideal":720}}},"devices":["video"]},"name":"gum.general","message":"Failed to create new track","stack":"r@index.android.bundle:406:88431\nindex.android.bundle:406:216566\nc@index.android.bundle:406:201935\nindex.android.bundle:406:202303\nindex.android.bundle:399:1156\nvalue@index.android.bundle:35:3467\nindex.android.bundle:35:1240\nvalue@index.android.bundle:35:2606\nvalue@index.android.bundle:35:1210\n[native code]"}, stack:
                       <unknown>@333:2270
                       n@406:303122
                       <unknown>@406:203056
                       <unknown>@406:216558
                       c@406:201935
                       <unknown>@406:202303
                       <unknown>@399:1156
                       value@35:3467
                       <unknown>@35:1240
                       value@35:2606
                       value@35:1210
E/ReactNativeJS: '[__filename]', '<r>: ', 'Failed to create local tracks', [ 'video' ], [gum.general: Failed to create new track]
E/unknown:ReactNative: console.error: "[__filename]", "<r>: ", "Failed to create local tracks", ["video"], {"gum":{"error":{"name":null,"message":"Failed to create new track"},"constraints":{"audio":false,"video":{"mandatory":{"minWidth":1280,"minHeight":720,"maxWidth":1280,"maxHeight":720},"optional":[{"facingMode":"user"}],"facingMode":"user","width":{"ideal":1280},"height":{"ideal":720}}},"devices":["video"]},"name":"gum.general","message":"Failed to create new track","stack":"r@index.android.bundle:406:88431\nindex.android.bundle:406:216566\nc@index.android.bundle:406:201935\nindex.android.bundle:406:202303\nindex.android.bundle:399:1156\nvalue@index.android.bundle:35:3467\nindex.android.bundle:35:1240\nvalue@index.android.bundle:35:2606\nvalue@index.android.bundle:35:1210\n[native code]"}, stack:
                       <unknown>@333:2270
                       r@380:727
                       <unknown>@546:1124
                       <unknown>@68:613
                       <unknown>@68:641
                       <unknown>@40:1785
                       a@40:527
                       o@40:891
                       callImmediates@40:3186
                       value@35:2778
                       <unknown>@35:1360
                       value@35:2606
                       value@35:1330
                       value@35:1265
I/[MALI][Gralloc]: [+]r_hnd(0xe83e65a0), client(51), share_fd(75)
D/GraphicBuffer: register, handle(0xe83e65a0) (w:1920 h:1080 s:1920 f:0x1 u:0x000b00)
D/OpenGLRenderer: CacheTexture 1 upload: x, y, width height = 0, 0, 174, 170
I/[MALI][Gralloc]: [+]r_hnd(0xe83e7ae0), client(51), share_fd(77)
D/GraphicBuffer: register, handle(0xe83e7ae0) (w:1920 h:1080 s:1920 f:0x1 u:0x000b00)
I/org.webrtc.Logging: WebRtcAudioManager: VOICE_CALL stream volume: 7 (max=7)
I/org.webrtc.Logging: WebRtcAudioManager: VOICE_CALL stream volume: 7 (max=7)
I/org.webrtc.Logging: WebRtcAudioManager: VOICE_CALL stream volume: 7 (max=7)
I/org.webrtc.Logging: WebRtcAudioManager: VOICE_CALL stream volume: 7 (max=7)
I/org.webrtc.Logging: WebRtcAudioManager: VOICE_CALL stream volume: 7 (max=7)

**Comment by omaramer3** [comment]
We also having same problem with iPad running iOS 9
