### ISSUE TITLE
How to set a user displayname in Jitsi mobile app？

### ISSUE THREAD

**Issue by TangXT** [jitsi/jitsi-meet#1781]
How to set a user displayname in Jitsi mobile app with the Jitsi Meet SDK for iOS and Android？

**Comment by saghul** [comment]
This is not yet supported, sorry!

**Comment by TangXT** [comment]
Why？

**Comment by saghul** [comment]
Because there are more important things at the top of the TODO list :-)

**Comment by lyubomir** [comment]
The display name of the local user may be set through JWT (specified to `loadURLObject` on its own or as part of the URL itself).
