### ISSUE TITLE
Share the link button

### ISSUE THREAD

**Issue by tkd4444** [jitsi/jitsi-meet#1783]
Hi,

We are using token based authentication, there is this button for inviting other people with a link to the current conference. Shouldn't the link also include the token ? Now it's just the conference room name and if you don't have anonymous auth enabled people can't get in.

Thanks !

**Comment by damencho** [comment]
token is something serverside generated and the current user cannot generate the token for the invited user as tokens are supposed to be user specific ... in other words invites are to invite guests to the conference.

**Comment by tkd4444** [comment]
I understand that, but we do share the whole token URL between each other. We don't have anonymous auth yet. Thanks for the answer!
