### ISSUE TITLE
[Documentation] Installing Jitsi-meet with a web server present

### ISSUE THREAD

**Issue by panagiks** [jitsi/jitsi-meet#1789]
Hi,

I've noticed that when installing Jitsi-meet with a web server present (Apache in my case) it creates a new VirtualHost and uses it to serve jitsi-meet, whereas if none is present jitsi-meet is served directly through Java. I've found this rather confusing (mainly because it wasn't documented) so I'd like to open a PR to add it as a note in the [quick install guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md).

Is there any objection?

**Comment by damencho** [comment]
No.
Just a note, package first search for nginx, than for apache and than uses embedded jetty from jvb. When using jetty it uses port 443 for serving content and for media.
