### ISSUE TITLE
Webcam quality really low (almost unusable)

### ISSUE THREAD

**Issue by scalfitura** [jitsi/jitsi-meet#1795]
Hi All,

I have a question about the webcam quality in Jitsi, I tried Jitsi the last year several times and we have always the same problem:

the webcam quality is really low, this makes the entire setup unusable. of course, this can have a lot of various reasons/ to eliminate the problem I tried various setups, various hardware, and network settings. what I tried already:

* VM; Ubuntu 14.04, 16GB RAM 4 vCPU's E5-2699A (XeonV5), 1Gbit/s up /down. (public setup)
* Ubuntu 17.04 Bare metal setup, 32GB RAM, 1 x Xeon E3-1585 v5, local area network setup 1Gbit/s 

I used the latest stable version of Jitsi, tried various browsers, but I cannot pinpoint the problem. the online hosted demo version of Jitsi is working fine.

Audio is also working fine.

Hopefully, someone can point me in the right direction.

Thanks anyway

**Comment by saghul** [comment]
Let's focus on a simple setup:

- join meet.jit.si with 3 endpoints
- see if you local view is ok
- check the transport in use (is it udp? you can do this by clicking "show more" in the local view signal bars tooltip)
- check the resolution of the remote participants: what is it?
- if you click on a remote participant so it becomes full-screen, does it improve?

**Comment by damencho** [comment]
What is the value for resolution setting in config.js?
