### ISSUE TITLE
api command to start livestream?

### ISSUE THREAD

**Issue by tansaku** [jitsi/jitsi-meet#1807]
Is there an API command that would start a livestream from a jitsy, e.g.

```
api.executeCommand('startLiveStream', YOUTUBE_STREAM_TOKEN)
```

**Comment by saghul** [comment]
Not currently.

**Comment by tansaku** [comment]
thanks @saghul - is the livestream starting system a plugin that could be reached any other way?  Do you have any suggestions if we wanted to implement a feature that made it easier to start livestreams?

Should we be looking at a different codebase, or putting in a PR to this codebase to extend the API?

**Comment by Meridix** [comment]
keep open

**Comment by DamianoP** [comment]
keep open

**Comment by saghul** [comment]
This has already been implemented: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#startrecording-1
