### ISSUE TITLE
Question: Video turned of because of low bandwith, during screensharing

### ISSUE THREAD

**Issue by amenk** [jitsi/jitsi-meet#1813]
What does it mean that the video has been turned of because of low bandwidth?

During screensharing this is a big problem, can it be forced to stay on? Is it about the sender's or the receiver's bandwidth?

**Comment by saghul** [comment]
> What does it mean that the video has been turned of because of low bandwidth?

It means the receiver doesn't seem to have enough bandwidth to receive the video.

> During screensharing this is a big problem, can it be forced to stay on?

Nope.

> Is it about the sender's or the receiver's bandwidth?

The receiver's.

**Comment by amenk** [comment]
Thanks for your quick answer. Do you know how much bandwidth is required? Can this be improved, i.e. to allow screensharing also with a very low bandwidth (thus resulting in worse resolution or slower updates)

**Comment by saghul** [comment]
It varies. The desktop is shared at full resolution, but low framerate. This means that if you have a native 4k monitor, runnit at 4k, that's the redolution you are going to share your screen at.

I believe Google is working on enabling simulcast for screens sharing, but it's not there yet.

**Comment by gpolitis** [comment]
@amenk estimating the available bandwidth is a complex task and our implementation may contain bugs and also improvements possible.

What kind of network link is associated with the restricted receiver? How much data is your sender uploading when the problem occurs (you can find that if you hover your mouse over your GSM bars)? Does the problem happen "all the time"? Does the receiver (or some other machine in the local network) run any other network hungry programs while participating in the conference (torrents, video streaming)?

**Comment by amenk** [comment]
It happens sometimes more sometimes less. We do not have a very broad connection and bandwidth may be limited. 
Might it also be related to meet.jit.si?  Would it make sense to install on own server?

**Comment by amenk** [comment]
Can the reason be that we ouse meet.jit.si ? Would it make sense to setup an own server?
![screenshot_auswahl_032](https://user-images.githubusercontent.com/1087128/29111513-db30cb8c-7cea-11e7-9d10-dd0a2dd41098.png)

**Comment by gpolitis** [comment]
I don't think running your own server would improve things.

Could you please give https://beta.meet.jit.si a try and let us know if it works any better for you? We have fixed an issue related to bandwidth estimations. The problem we've fixed was in the opposite direction of the problem that you're describing but I'm still curious to check.

just be aware that this is our staging environment and it may restart, become unavailable at any point, so it's not appropriate for every day use

**Comment by amenk** [comment]
Okay, we are running some tests on beta.meet.jit.si - we will see.
When is that change going to be live? Do you have a issue # ?

**Comment by amenk** [comment]
When exactly is it turning of the video? Woudln't be a more lossy screen compression help?

**Comment by gpolitis** [comment]
Actually.. I think the bridge on beta is broken as of a few hours ago, so it can’t be used to draw any conclusions, sorry about that.

The bridge is detecting that there’s not enough upload bandwidth towards a specific receiver and it suspends/turns off the video.

You can disable this behavior if you launch your own instance, at the risk of causing congestion.

**Comment by amenk** [comment]
And how much upload bandwith do I need for a high resolution screen share? Can the update frequency of the screen just be turned down? Is there a special compression in place or is the same one use as is for webcam videos ? (my guess is, that screensharing can or should be compressed differently than webcam video)

**Comment by amenk** [comment]
Yesterday I was having connectivity issues even I were in the same LAN as
the other party.
In addition we have a 1 gbps symmetric connection to the Internet.

**Comment by openaspace** [comment]
Where we can find documentation settings about this problem?

**Comment by openaspace** [comment]
I want to use it in a private and professional environment for medial meeting, but without underdstand why all this happen, i can't propose jitsi as solution.

Thank you to all. :)

**Comment by tuxayo** [comment]
@openaspace There you can disable this feature if you are sure you are not in a case where it's useful. (considering your bandwidth, then that might be the case) https://github.com/jitsi/jitsi-meet/blob/ac83432/config.js#L122

You can just try and see there are no issues. If so, you could report here so the dev will know that the detection might give too much false positives.

**Comment by amenk** [comment]
Would self-hosting it help? Does meet.jit.si use public servers which might be on low bandwidth?

**Comment by damencho** [comment]
No, meet.jit.si is on high available nodes, with a lot of bandwidth, with conservative rules for auto scaling new jvb instances when bandwidth is high. 
This issue is for screensharing and low bandwith ... We had already fixed a problem around that in the beginning of the year, are you still seeing this with latest meet.jit.si?

**Comment by amenk** [comment]
Thanks. Yes recently had problems again ... try to investigate further and use meet.jit.si more often :-)

**Comment by damencho** [comment]
Haha.

**Comment by paweldomas** [comment]
@amenk technically, under the hood it's a different issue. This message is displayed when video can't be rendered or when it freezes at some point. We may have another bug there, but it's not about bandwidth.

**Comment by amenk** [comment]
Thanks for clarifying...
Okay, shall I open another issue for this or is there a matching one?
