### ISSUE TITLE
Mobile phone more than three participant has a larger delay

### ISSUE THREAD

**Issue by SlamDunkDcc** [jitsi/jitsi-meet#1818]
I set up a jitsi service by myself, When I use the browser link is very smooth, almost no delay.But when the client links with my mobile phone, as long as there will be more than three larger delay.Android and iOS phone will have the same problem.Mobile client need other configuration?

**Comment by saghul** [comment]
We are aware of this and are looking for a solution. FTR, the problem seems to be caused by using HW acceleration (or H264 codec, or a combination).

**Comment by SlamDunkDcc** [comment]
I done a test with android phones, I used the webview although sometimes can't see the video, but there is no delay.

**Comment by TangXT** [comment]
Jitsi Meet on mobile using HW acceleration with react-native-webrtc ?

**Comment by TangXT** [comment]
Is Jitsi Meet on mobile using HW acceleration with react-native-webrtc ?
