### ISSUE TITLE
[query] How can I test my outgoing audio on Jitsi Meet / WebRTC?

### ISSUE THREAD

**Issue by kwill** [jitsi/jitsi-meet#1823]
I want to test my audio quality (as heard by others) before I join a call. How can I do this?

**Notes:**

* On Skype there was a contact called "Skype call testing service". You called it, it recorded a message, and then played the message back to you.

* I found https://test.webrtc.org for generic WebRTC troubleshooting, but to test connectivity and throughput you need details for a TURN or STUN server. Are these available for Jitsi Meet?

**Comment by kwill** [comment]
Also posted query at https://webapps.stackexchange.com/questions/108042

**Comment by varac** [comment]
There's an external echo test hosted at https://janus.conf.meetecho.com/echotest.html.

**Comment by saghul** [comment]
Closing since we don't have plans to implement a pre-call device testing screen. While in a call though, you can open the device selection dialog and it will preview audio and video devices.

**Comment by bluikko** [comment]
I would love to see this feature.

Currently joining a test room shows the local video stream. Some kind of loopback room would be great for testing the actual connection to the server. Apparently this could be achieved by opening the same room in three tabs but it is a bit much to ask from regular users (or customers!). And I do get the irony of that sentence regarding dev resources..
I am new to Jitsi and don't know the internals very well yet - maybe this would be very difficult to add? If so, expanding a bit on why it will not be done could prevent further queries for the feature.

Just checking if anything in the official stancehas changed in the last 2.5 years.

**Comment by amsnek** [comment]
I agree, this feature could help a lot, especially for less technical people (who will probably just open 3 tabs). It may however not be too trivial to implement. Ideally, it should loop audio back with a time delay and ensure its being passed over the videobridge. 

Would be interested as well if the official stance has changed the past years.

**Comment by SkizzoSaar** [comment]
+1
In my opinion this is a must have feature. Especially when the number of meeting participants increases you wouldn't want to wait till every participant has found its correct settings (right audio/video devices, privacy settings in windows 10, browser settings for accessing audio/video devices, acceptable volumes, etc.) at the beginning of a conference.

**Comment by t-var-s** [comment]
+1
In general, anything to help better debug device/connection issues would be great as problems described by random users are often difficult to recreate.

**Comment by GregOriol** [comment]
There are also cases like enterprise networks blocking connectivity, and having an echo test available would help users test if they can successfully connect to self-hosted jitsi, without having other real users in (so they can perform the test at any time, not just when joining the real meeting they are invited to).

**Comment by fullstack1128** [comment]
I am integrating jitsi meeting to my web project. It is simple and really interested in it.
But I have an issue.
Could you let me know how to use the webhook locally?
Thank you so much
