### ISSUE TITLE
Conference focus not available

### ISSUE THREAD

**Issue by sanjeevghimire** [jitsi/jitsi-meet#1826]
i did the quick installation. I could access the jitsi-meet page but other folks cannot join the conference and they only see themselves even if they join using the same url

any help is appreciated

thanks
Sanjeev

**Comment by damencho** [comment]
Are there any js console errors? You could also check jicofo logs for errors, are there any?

**Comment by sanjeevghimire** [comment]
yes please see attached
![screen shot 2017-07-26 at 8 39 43 pm](https://user-images.githubusercontent.com/1693915/28650617-b3536032-7242-11e7-930b-324a3b030af4.png)


![screen shot 2017-07-26 at 8 39 22 pm](https://user-images.githubusercontent.com/1693915/28650621-b922eafa-7242-11e7-8496-7aefcac5daba.png)

**Comment by sanjeevghimire** [comment]
does focus.216.14.120.83 subdomain need to exist?

**Comment by damencho** [comment]
For some reason jicofo failed to connect to the xmpp server. Check jicofo logs for more info.

**Comment by sanjeevghimire** [comment]
the log at /var/log/jitsi/jicofo.log.1 has this: not sure when though

Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by damencho** [comment]
Check in the beginning, just stop jicofo, delete the logs and start it again. There can be another error on startup that can lead to some memory leak and come to the point of exiting the process, as shown in the logs you've pasted.

**Comment by sanjeevghimire** [comment]
i deleted the logs. this is what i see after: /etc/init.d/jicofo stop and then start

Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by damencho** [comment]
How much free memory do you have, jicofo by default opens with instructions for taking up to 3GB RAM but this is the maximum... not sure how much is the minimum for normal operation under low load.

**Comment by sanjeevghimire** [comment]
![screen shot 2017-07-26 at 11 16 20 pm](https://user-images.githubusercontent.com/1693915/28654249-8145a6f2-7258-11e7-8035-40dec5a70b50.png)

**Comment by sanjeevghimire** [comment]
when i run java command i get this as well
Error occurred during initialization of VM
Unable to allocate 46272KB bitmaps for parallel garbage collection for the requested 1480704KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by sanjeevghimire** [comment]
I have open jdk installed. should i uninstall and install Oracle JRE?

**Comment by saghul** [comment]
What Java version did you install? How did you install it? There seems to be some problem with your Java installation.

**Comment by sanjeevghimire** [comment]
I have open-jdk-7-amd-64

**Comment by sanjeevghimire** [comment]
I did clean install with oracle java 8 and looks like ti worked.
thanks for your help guys!

**Comment by walterzielony** [comment]
Hi  @damencho what can you say for x86 architectures? Java version 1.8.0 x86, but having the same problem...
Thanks!
