### ISSUE TITLE
Can see buttons during call are only partially

### ISSUE THREAD

**Issue by tobiasmuecksch** [jitsi/jitsi-meet#1834]
As you can see in the following picture, on Android, once a call partner has joined the buttons to control the call are only shown partially.

I've observed this bug on these two devices:
- Moto G (2nd gen, Android 6.0)
- Samsung Galaxy J5 (Model 2017, Android 7.0)

![img_0232](https://user-images.githubusercontent.com/1294854/28711261-4c2da75a-7387-11e7-91b3-fc8f83516018.JPG)

**Comment by saghul** [comment]
We have a fix for this and should be part of the next release, 1.8. See https://github.com/jitsi/jitsi-meet/commit/2094b15432383c00380b5c471b3764651255d927
