### ISSUE TITLE
Room name not passed to the URL when using External Api

### ISSUE THREAD

**Issue by scarnia** [jitsi/jitsi-meet#1836]
Hi, 
 
We are using the external API to embed Jitsi in an application. We managed to use JWT but it seems that the External Api is obviating the room passed as an option. We generate our JWT properly (an we can verify it directly accessing the url https://servername/RoomName?jwt= ........ )

Nonetheless when using the external api with the config parameter set to the proper RoomName, we are always redirected to the "home page" of jitsi instead to the room. If we enter the RoomName in the box we get access to the room but it seems logical that we should be redirected to it automatically when supplying the room parameter (not only in JWT but also in the config of the constructor).

Looking into the code, it seems as it is clearly ignoring the room name:

```
function generateURL(domain, options = {}) {
    return urlObjectToString({
        ...options,
        url:
            `${options.noSSL ? 'http' : 'https'}://${domain
                }/#jitsi_meet_external_api_id=${id}`
    });
```
while, IMHO it should be:
function generateURL(domain, options = {}) {
    return urlObjectToString({
        ...options,
        url:
            `${options.noSSL ? 'http' : 'https'}://${domain
                }/${options.roomName ? options.roomName : ''}#jitsi_meet_external_api_id=${id}`
    });

-------------------------------------
While writing the issue we discovered the problem but we will still publish it because it is still a problem in the documentation:

* In the External Api documentation says:

Example:

var options = {
    domain: "meet.jit.si",
    room: "JitsiMeetAPIExample",
    width: 700,
    height: 700,
    htmlElement: document.querySelector('#meet')
}
var api = new JitsiMeetExternalAPI(domain, options);

* Nonetheless, the options in the js source file uses different names:
 const [
            roomName,
            width,
            height,
            parentNode,
            configOverwrite,
            interfaceConfigOverwrite,
            noSSL,
            jwt
        ] = args;

So in the documentation (although the change seems to be pretty recent (15 days) (commit 70122789e7b6f8544cec6af779d67179906d3a99) the next change should be made

room -> roomName
htmlElement -> parentNode

Thanks for your great work!

**Comment by saghul** [comment]
Ping @hristoterezov

**Comment by lyubomir** [comment]
```
function generateURL(domain, options = {}) {
    return urlObjectToString({
        // roomName is inside options here. room should also work as an alias.
        ...options,
        url:
            `${options.noSSL ? 'http' : 'https'}://${domain
                }/#jitsi_meet_external_api_id=${id}`
    });
```

**Comment by lyubomir** [comment]
````
function generateURL(domain, options = {}) {
return urlObjectToString({
...options,
url:
// No, urlObjectToString will look at options and add the roomName or room to the url provided here. 
${options.noSSL ? 'http' : 'https'}://${domain }/${options.roomName ? options.roomName : ''}#jitsi_meet_external_api_id=${id}
});
````

**Comment by lyubomir** [comment]
No need to ping @hristoterezov, I made the change yesterday.

**Comment by scarnia** [comment]
Hi, please notice that as a explained in the last part (sorry for the length of the text) of the issue, the system is indeed now working properly and the system puts you in the proper room. The problem was a documentation one (examples of external Api).

Nonetheless is still curious how the code of the generateURL does not seem to include the roomName and yet, it is finally included (not sure where).

**Comment by saghul** [comment]
The docs were just fixed, closing.
