### ISSUE TITLE
Integrating jitsi meet with cordova based mobile app

### ISSUE THREAD

**Issue by sanjeevghimire** [jitsi/jitsi-meet#1840]
Hello all,

I have a cordova based mobile app that runs on both android and ios

how can i integrate jitsi-meet with this cordova app since it has dependencies with react native modules?

thanks in Advance
Sanjeev

**Comment by sanjeevghimire** [comment]
Any help is really appreciated?

**Comment by saghul** [comment]
Ok, here we go :-)

There are 2 ways in which you can integrate it:

- Using lib-bitsi-meet and writing your own UI
- Wrapping the Jitsi Meet SDK as a Cordova plugin

If you choose the former, you will need to use this Cordova plugin: https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc but you'll probably need to tewak stuff so lib-jitsi-meet is comfortable in that environment. (for example register all globals and such). And then you'll have to do the UI yourself, which is not an easy feat.

Alternatively, you could create a simple Cordova plugin in Objective-C which uses the Jitsi Meet SDK to display a view when you tell it to. The API is descrived here: https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md. The idea would be to have a plugin which loads the conference URL by creating a Jitsi Meet View full-screen, and hides it when it disconnects. There are events (documented in the aofrementined README) which can help you with that.

With my experience (I am one of the maintainers of cordova-plugin-iosrtc, and made an app with it, and now work on the Jitsi Meet SDK) I'd go with the latter. It will shield you from dealing with the low-level aspects of the conference (that is all confined in the SDK) so you can focus on your app.

Of course, YMMV, these are just my 2 cents, and all that :-) I hopw that helps.

**Comment by sanjeevghimire** [comment]
Thanks @saghul for helpful tips. I think latter sounds better as well. BTW has anyone already work on creating the plugin that you know?

**Comment by saghul** [comment]
I don't think so, note that the SDK is quite young (a couple of months).

**Comment by Alexmartinez3** [comment]
Hi @sanjeevghimire and @saghul I am developing and Cordova or Ionic app and I am valorating the best option to do this. Do you help me with this? I need it works in Android and iOS.

I am trying integrate with the API: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md but I can not make it work.

Thanks in advance.

**Comment by saghul** [comment]
@Alexmartinez3 That is the iframe API, which is not going work on mobile. Pease see my previous repy here: https://github.com/jitsi/jitsi-meet/issues/1840#issuecomment-318890944 If you opt for the second option (the one I think it's better) you'll need to write a small native Cordova plugin.

**Comment by gaganinvic** [comment]
I have written a small Cordova plugin to use Jitsi with Ionic. Hope this helps.

https://github.com/gaganinvic/cordova-plugin-jitsi-meet

**Comment by saghul** [comment]
@gaganinvic that's prety awesome! thanks for sharing!

I think we can close this now.

**Comment by Alexmartinez3** [comment]
Fantastic @gaganinvic <https://github.com/gaganinvic>

thanks for sharing!




2018-04-12 22:58 GMT+02:00 Saúl Ibarra Corretgé <notifications@github.com>:

**Comment by slothstronaut** [comment]
The above plugin will only work for iOS, as you can no longer submit 32-bit binaries to the Play store. After doing a bit of research, I ended up creating my own repo which combines the plugin from @gaganinvic and the latest version hosted by npmjs which works with Android, but not iOS.

Here is my plugin, which also has installation/usage documentation

https://github.com/findmate/cordova-plugin-jitsi-meet/

Good luck!

**Comment by damsorian** [comment]
@slothstronaut your plugin is very nice, you can open the issue feature in your repository in order to get feedback? for example how we can pass config to the init function?

**Comment by slothstronaut** [comment]
Sure, its been enabled, thanks for the suggestion.

**Comment by HarshMalve** [comment]
@slothstronaut Thanks! Was looking for something similar to your plugin. Is there any way we can get jitsi events using your plugin ?
