### ISSUE TITLE
Issue while deploying jitsi-meet

### ISSUE THREAD

**Issue by RavinduRoshan** [jitsi/jitsi-meet#1842]
**npm ERROR at lib-jitsi-meet@0.0.0 postinstall: `webpack -p`**
I have this issue while deploying jitsi meet. I have **Ubuntu 14.04 LTS** installed and current **node@v6.11.1** and **npm@3.10.10**. Please help me with this.

**Comment by damencho** [comment]
Can you post more detailed errors?

**Comment by RavinduRoshan** [comment]
npm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/home/ravindu/.nvm/versions/node/v6.11.1/bin/node" "/home/ravindu/.nvm/versions/node/v6.11.1/bin/npm" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lib-jitsi-meet@0.0.0 postinstall script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lib-jitsi-meet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lib-jitsi-meet
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lib-jitsi-meet
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/jitsilive/npm-debug.log

this is the error. I think the problem with webpack -p.

**Comment by RavinduRoshan** [comment]
@damencho can you please suggest me a solution for this. I have blocked with this.

**Comment by saghul** [comment]
What command are you running? You must run `npm install` from the jitsi-meet directory or you'd need to have webpack installed beforehand.

**Comment by RavinduRoshan** [comment]
Yup. The command I ran is npm install from the jitsi-meet directory. When I run this command I get this error. Should I need to have webpack installed before run npm install?

**Comment by saghul** [comment]
That's weird. You seem to be doing things right and using the recommended versions of Node and npm and yet you get the error 😞 Can you try to install webpack before running `npm install`?

**Comment by RavinduRoshan** [comment]
Finally It was worked for me. You saved my day. Thank you very much.   :) :+1:

**Comment by saghul** [comment]
Glad it works for you!
