### ISSUE TITLE
Reverse Proxy Compatibility?

### ISSUE THREAD

**Issue by tiredofit** [jitsi/jitsi-meet#1853]
I've been hard at work building a Docker Image for Jitsi Meet (Prosody, Jicofo, Videobridge, Jitsi Meet along with nginx under Debian) and have it to the point where I can get the container to respond and start and join a conference. Others can join, however we cannot exchange Audio or Video. I can see my own Video and the other participants can see their own, but in the filmstrip it is either avatars or black screen.

We use a Nginx proxy which forwards from port 80-> 443 (jwilder/nginx-proxy and jrcs/letsencrypt-proxy-companion) which forwards to port 80 of the container running nginx. I'm wondering if this could be the cause of the problem. Since the nginx proxy, we are unable to directly map port 443 to the outside world. I was also thinking that NAT could be suspect here, I have opened ports (4443+10000-10020/udp) for the container and also run a script upon container startup to get our public IP and private container IP to populate the sip-communicator.properties files which looks like this:

````bash
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.meet.xxxx.org/.*
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.18.0.24
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=1xx.xx.xxx.6
````

I don't see anything in the logs that jumps out, so I was wondering if anyone had any experience or faced the same struggles. Thanks alot!

**Comment by saghul** [comment]
Port 443 is the ICE TCP port, which is used when you use the JVB also as your webserver. Otherwise it would be 4443 by default.

A way to solve this would be to use the "host" network mode for the JVB so UDP traffic can flow properly.

**Comment by tiredofit** [comment]
I'm afraid setting the container to host mode would eliminate the ability for our SSL (also dockerized, using 80 and 443) to communicate to the container. 

Our Docker container goes against the grain of one process per container where I have all services running concurrently in one for ease of use, If I was to remove the web based component, how would I be able to force communication to occur via 4443? I see that it has been noted as a default/backup port but unsure how it is able to distinguish if it should be used or not. 
FWIW last night I also rebuilt the container to listen at 443 instead of 80 between the reverse proxy and the in place nginx service->bosh. No such luck.

Here's an example of my docker-compose.yml which gives a little hint to how networking is currently setup. Once setup will be glad to share this to the community, I feel there may be others running into this issue as well.

````bash
version: '2'

services:
  meet-xxx-org-app:
    container_name: meet-xxx-org-app
    image: registry.xxx.org/docker/jitsi-meet:latest
    ports:
      - 4443:4443
      - 10000-10020:10000-10020
    volumes:
      - ./assets:/assets
      - ./logs:/www/logs
    environment:
      - VIRTUAL_HOST=meet.xxx.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=meet.xxx.org
      - LETSENCRYPT_EMAIL=techsupport@xxx.org

      - JITSI_VIDEO_PASS=secret1

      - JICOFO_PASS=secret2
      - JICOFO_USER_PASS=secret3

    networks:
      - proxy-tier
      - host
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
````

**Comment by saghul** [comment]
> I'm afraid setting the container to host mode would eliminate the ability for our SSL (also dockerized, using 80 and 443) to communicate to the container.

How so?



> Our Docker container goes against the grain of one process per container where I have all services running concurrently in one for ease of use, If I was to remove the web based component, how would I be able to force communication to occur via 4443?

Have a look at this diagram: https://github.com/jitsi/jitsi-meet/blob/b8189a31adc2cb3351402799f694a2ebe809fcaf/doc/manual-install.md#network-description

Media would only go through 4443 iff ICE fails for UDP. You really don't want that.

Without any logs is hard to say, but I guess the problem is the communication with the JVB. Can you paste (please use a gist) what you see in the JS console when you join with a second participant?

**Comment by tiredofit** [comment]
Hi, attached is a gist. It does seem (line 117) that it is explicit that ICE has failed, yet I'm uncertain as I do know the ports in question for UDP are available and seemingly have made correct statements in my sip-communicator.properties file to account for the public and private IP address.

https://gist.github.com/tiredofit/3430fd410aa669ad4b02e4f4a2bef23e

In regards to the question of not being able to run in host mode in Docker, the nginx-proxy requires it's own seperate network to communicate to the containers, and from what I can see is not possible to run a container in host mode and also be a part of a private (bridged) network.

**Comment by ageis** [comment]
@tiredofit, this is an old issue, but you might want to look at https://github.com/freedomofpress/ansible-role-jitsi-meet as a reference point.
