### ISSUE TITLE
[iOS] jitsi-meet ios sdk pod

### ISSUE THREAD

**Issue by manuroe** [jitsi/jitsi-meet#1854]
Hi,

The iOS sdk seems very young and my question may be premature but is there a plan to make JitsiMeet.framework available through a pod?

Thanks

**Comment by saghul** [comment]
Probably yes, but it's indeed too early for that.

**Comment by aaronraimist** [comment]
Still applicable

**Comment by aaronraimist** [comment]
Still applicable

**Comment by saghul** [comment]
Oops, forgot to close this. It's already available as a pod. Please see: https://github.com/jitsi/jitsi-meet-ios-sdk-releases
