### ISSUE TITLE
Setting - deactivate the jitsi-meet redirection to native applications for android devices

### ISSUE THREAD

**Issue by psaavedra** [jitsi/jitsi-meet#1856]
I wonder if could be possible a new setting in Jitsi-meet which deactivates the redirection to the native app in the browser when you loads jitsi-meet JS application in the Android browser, for example.

**Comment by saghul** [comment]
It's possible, but you would need to modify the code yourself and have your own deployment. We will not do it for meet.jit.si. The reason is that the web (our web, that is) is not optimized for mobile, we have dedicated apps for that.

An alternative way is to request the desktop site with Chrome on Android.

**Comment by psaavedra** [comment]
I agree but, lately,  I realized that the Android application doesn't work with others jitsi service different than meet.jit.si one even if you use the absolute URL as the room name.

**Comment by saghul** [comment]
Oh, that's bad! Definitely unintentional, and definitely a bug. This looks the same as https://github.com/jitsi/jitsi-meet/issues/1858, I'll update the title and follow up there. Can you please share a URL we can test with?

**Comment by psaavedra** [comment]
We are experimenting this issue on Android devices in https://jitsi.igalia.com/. The same doesn't happends in the iOS native app which works as usual using the absolute URL:

```
ii  jitsi-meet                         1.0.2098-1                        all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                 1.0.1967-1                        all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                     1.0.1967-1                        all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config              1.0.1967-1                        all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge                  953-1                             amd64        WebRTC compatible Selective Forwarding Unit (SFU)
