### ISSUE TITLE
[mobile] jitsi meet not working with custom deployment

### ISSUE THREAD

**Issue by tkd4444** [jitsi/jitsi-meet#1858]
Hi,

After your recent update of  jitsi-meet-iOS the application stoped working with our Jitsi install.
When we pass our domain URL with token or without token (guest virtual host enabled) the screen is just black.

I have checked the log of prosody and jicofo, there is no trace of any request from the IOS app.

Any ideas ?

Thanks !

**Comment by lyubomir** [comment]
@tkd4444, could you please give me an example URL from your deployment? (If you don't feel comfortable pasting it here, please send it privately.)

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/1856 reports the same on Android

**Comment by tkd4444** [comment]
@lyubomir I could send it to you privately but I can't send you a PM.

**Comment by saghul** [comment]
Feel free to send it to me, saghul (at) jitsi (dot) org.

**Comment by tkd4444** [comment]
sent.

**Comment by lyubomir** [comment]
@tkd4444, thank you very much! We'll try to look into resolving this problem as soon as possible. The first problem I hit was a known bug which has been there from the inception of the mobile app so a bit unsure how your deployment used to work before... Is it possible that your deployment changed as well in between the last two releases of the mobile app? Something around authentication and/or anonymous access? Again, you may shoot your answers to @saghul and/or lyubomir [ dot ] marinov [ at ] jitsi [ dot ] org if you don't feel comfortable discussing your deployment's specifics in public.

**Comment by saghul** [comment]
I think I've located the issue. The 3 sites which have reported issues have the `anonymousdomain` config option set, which triggers a lookup in `window.location.search`, which doesn't exist for React Native. We are working on a fix. Can you please comment out that option in your config.js and see if it works in that case?

**Comment by psaavedra** [comment]
Works for me. 

What implications has comment out this setting. I guess this setting is necesary for Jitsi instances where there are registered but also anoynimous participants in the conferences. isn't it?

**Comment by saghul** [comment]
Correct. We don't yet support authenticated deployments on mobile, we plan to work on that shortly. That option, however, caused the app not to work even when no authentication was configured. Just being there creates trouble.

**Comment by premanandmanimaran** [comment]
Hello 

My custom deployment ( deployed in EC2 Micro Instance in AWS) , when trying to open home page (subdomain page)
1.  won't open in Mobile Chrome Browser (using Mobile Network) , 

2.   Won't work for few users when they using Laptop with Wifi or Ethernet.

3. Works fine when using Wifi in the Mobile device

4. When I connect Jitsi API through iframe Inside Custom Web Application scenario 1 and 2,3  are working ( but takes long time to load)

I followed the settings in quick install
ports are (TCP/443 or TCP/4443 and UDP 10000 - 20000)
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>
DefaultLimitNOFILE=65000
DefaultLimitNPROC=65000
DefaultTasksMax=65000

Please help

Thanks in advance

**Comment by damencho** [comment]
@premanandmanimaran Please, when you have questions or problems use the community forum before opening new issues or hijacking old ones.

Try moving the instance to something bigger. 1 GB of RAM for running jvb and jicofo is not enough.
I would say the system needs 8GB RAM. The issues you have are very strange and there seems no pattern that something is wrong. So try a bigger instance in a region closer to you.

**Comment by premanandmanimaran** [comment]
@damencho I am sorry i am new to this.
I created an account in Jitsi meet community and posted the same in that forum. Also created a new Larger Instance in AWS with 32 Gb RAM and I still have the same issue.
Thanks
