### ISSUE TITLE
Deeplinks on iOS don't work

### ISSUE THREAD

**Issue by fkhan0520** [jitsi/jitsi-meet#1864]
![20662810_10155570611139715_1341816819_o](https://user-images.githubusercontent.com/6452859/29002142-c7c58dd6-7a50-11e7-986f-636de0bb1b11.jpg)

These two buttons don't lead anywhere with an iPhone 6s running iOS 10.3.2

**Comment by saghul** [comment]
What version of the app are you running?

**Comment by fkhan0520** [comment]
Version 1.7

I downloaded it yesterday. It's also happening on a friend's phone with the
same specs.

**Comment by saghul** [comment]
What browser and deployment is that? I just tried it and had no issues.


![Image](http://i.imgur.com/QU1HUBj.jpg)

**Comment by lyubomir** [comment]
@fkhan0520, we'll need the version of the deployment in order to continue here.

**Comment by lyubomir** [comment]
It's been almost an year now since this issue was last commented on and since further information was requested so I'd wager it's safe to close this issue now.
