### ISSUE TITLE
How can I change the video frame rate of all clients?

### ISSUE THREAD

**Issue by RavinduRoshan** [jitsi/jitsi-meet#1865]
I just need to reduce the frame rate of all clients in a meeting. What are the changes has to be done?

**Comment by saghul** [comment]
You can't do that manually. The bridge will do it automatically for you. The thumbnails should have less fps and the large view will adapt to the available bandwidth by adjusting resolution and bitrate.

**Comment by RavinduRoshan** [comment]
So that means there is no way to change the frame rate in source code. I need to connect at least 20 participants in a meeting. So I'm gonna do a stress test by reducing the frame rate. Because the bandwidth is a problem in sfu. It is possible to change the resolution. But the default frame rate is 8. I'm finding a way to reduce it.

**Comment by bbaldino** [comment]
@RavinduRoshan the resolution (and framerate, if you're using vp8) will scale dynamically on the call based on each sender and receiver's bandwidth, so i think it'd be a good idea to try a test and see how things perform before worrying about manually changing the framerate.

**Comment by bbaldino** [comment]
@RavinduRoshan if, for some reason, you really had to you could change the getUserMedia call on the client to use a lower source framerate, but really the bridge should be taking care of this problem for you.
