### ISSUE TITLE
Cannot get JWT authentication to work

### ISSUE THREAD

**Issue by a544jh** [jitsi/jitsi-meet#1871]
I'm trying to set up JWT authentication as per https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

I found out that the basexx dependency was missing and installed it manually (#1870)

I use https://jwt.io to generate a JWT according the documentation, with the following payload data
```
{
  "sub": "[our domain]",
  "iss": "[our app_id]",
  "room": "asd",
  "exp": "1512278751"
}
```

I cannot however get jitsi-meet to accept my JWT. I get the "Sorry, you're not allowed to join this call" error. If no JWT is supplied in the URL, I get a username/password prompt.

I tried setting prosody's logging level to debug, but I get no logging from the token_verification plugin. Is there a way to get debug output from it?

**Comment by damencho** [comment]
The easiest way to debug this is to open the js console and the network tab and check the xmpp replay messages and its content, they will contain the reason for rejection.

**Comment by a544jh** [comment]
Thanks for the reply! I simply had to remove the quotes around the `exp` parameter and add the `aud` claim. This could also reflected in the documentation.

**Comment by damencho** [comment]
Yep, I'm currently looking at those and we will definitely fix those in the documentation. I'm looking at adding some debug log of showing the errors at least in prosody logs and stuff like that.
