### ISSUE TITLE
[iOS] How to disable React yellow (and red) debug boxes?

### ISSUE THREAD

**Issue by manuroe** [jitsi/jitsi-meet#1877]
There is no issue with the jitsi-meet iOS app but I am getting these annoying boxes within my app using the JitsiMeet.framework. See the screenshot below.

I cannot see how jitsi-meet iOS  avoids their display :/

Thanks in advance!

![](https://matrix.org/_matrix/media/v1/download/matrix.org/MhBtvBOpzQHmeRHyNLvSPkUA)

**Comment by ara4n** [comment]
@saghul heya - hope you're well :) as you've probably inferred, we're trying to integrate Jitsi into Matrix... is there something obvious we're missing with these yellow boxen?

**Comment by lyubomir** [comment]
The red and yellow boxes are automatically enabled by react-native itself in Debug builds only and, respectively, automatically disabled in Release builds. If you're seeing them, it means that you built the Jitsi Meet SDK for iOS or Android) and Jitsi Meet for iOS or Android with the Debug configuration. If you don't want to see them, build with the Release configuration.

**Comment by ara4n** [comment]
@lyubomir cool, thanks :)

**Comment by saghul** [comment]
Hey @ara4n, sorry I missed GitHub notifications, sorry about that. Let us know if you run into other issues while using the SDK! Thanks @lyubomir for chiming in!

**Comment by manuroe** [comment]
It works. Thanks @lyubomir
