### ISSUE TITLE
Library not loaded, Image not found when trying to run on device

### ISSUE THREAD

**Issue by subsub** [jitsi/jitsi-meet#1878]
I always get this error `dyld: Library not loaded: @rpath/JitsiMeet.framework/JitsiMeet
  Referenced from: /var/containers/Bundle/Application/704B8848-20B9-4A4F-B1A0-3A6ECB72A85F/jitsi-meet.app/jitsi-meet
  Reason: image not found` whenever I try to run the app on my device, however it runs well on simulator.
Can anyone help?
Thank you

**Comment by subsub** [comment]
I managed to solve this issue which is to put JitsiMeet.framework to the target Embedded Binaries. However I run into another issue:
Whenever I try to archive the app and validate, it gives these errors:


    iTunes Store operation failed.
    Unsupported Architectures. The executable for jitsi-meet.app/Frameworks/JitsiMeet.framework/Frameworks/WebRTC.framework contains unsupported architectures '[x86_64, i386]'.

    iTunes Store operation failed.
    Invalid Segment Alignment. The app binary at 'jitsi-meet.app/Frameworks/JitsiMeet.framework/Frameworks/WebRTC.framework/WebRTC' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

    iTunes Store operation failed.
    Invalid Bundle. The bundle at 'jitsi-meet.app/Frameworks/JitsiMeet.framework' contains disallowed nested bundles.

    iTunes Store operation failed.
    Invalid Bundle. The bundle at 'jitsi-meet.app/Frameworks/JitsiMeet.framework' contains disallowed file 'Frameworks'.

    iTunes Store operation failed.
    The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

XCode version: Version 8.3.3 (8E3004b)

Thanks for your help.

**Comment by saghul** [comment]
You need to directly link with WebRTC.framework, Apple doesn't allow framework embedding. You also need to filter the achitectures of your frameworks, to only include ARM, and not x86/64 (the simulators).

**Comment by subkhansarif** [comment]
@saghul I'm new to iOS development. Do I need to add `WebRTC.framework` from `sdk>framework` to `app>target>jitsi-meet>general>Linked Frameworks and Libraries` ?

**Comment by saghul** [comment]
Oh, I hadn't noticed this was the same question as in SO. I replied there: https://stackoverflow.com/a/45659911/280310

**Comment by saghul** [comment]
> I'm new to iOS development. Do I need to add WebRTC.framework from sdk>framework to app>target>jitsi-meet>general>Linked Frameworks and Libraries ?

Check our Xcode project as a sample. The toplevel app must link with WebRTC.framework.

**Comment by FaizalMalik** [comment]
@saghul  -  I have tried with the Example pip-up app - its also showing the same error

**Comment by FaizalMalik** [comment]
![screen shot 2018-07-24 at 5 42 32 pm](https://user-images.githubusercontent.com/32692684/43137260-000eb9aa-8f69-11e8-9cb5-c6bb08794c89.png)
