### ISSUE TITLE
Change Circle Icons within Jitsi-Meet

### ISSUE THREAD

**Issue by solocircuit** [jitsi/jitsi-meet#1883]
Hello!

I am currently in the process of setting up this wonderful application for a group of older people to use.
I was wondering if it possible to change the colored monster faces into something else like a blank person icon? because as of right now it doesn't look very professional and would like something else.

I have tried changing the interface_config.js and setting the profile picture that way but it does not change.
I currently have random_avatar_url_suffix and prefix set to false and tried changing the app.bundle.min.js to no luck.
If I am being honest I have no Idea what I am doing I am used to editing video and uploading stuff to wordpress and a most of this is over my head so any help would be greatly appreciated :)

Anyway I love what you guys are doing keep up the good work!

**Comment by saghul** [comment]
Are you trying to modify the website or the mobile apps?

> I have tried changing the interface_config.js and setting the profile picture that way but it does not change.

I assume you are using your own deployment. In that case, changing interface_config.js should suffice. Alternatively you can set `disableThirdPartyRequests` to true in config.js: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L234 that way we won't show monsters, but a black and white default avatar.

> I currently have random_avatar_url_suffix and prefix set to false and tried changing the app.bundle.min.js to no luck.

There is no need to edit that file.

**Comment by solocircuit** [comment]
Hi thanks for getting back to me! 
I am just trying to edit it for the website

**Comment by solocircuit** [comment]
Also I should add I did use the quick install but I installed nginx beforehand

**Comment by saghul** [comment]
> I am just trying to edit it for the website

Ack. Then my suggestions above stand.

> Also I should add I did use the quick install but I installed nginx beforehand

That's ok, it shouldn't affect how the config needs to be modified.

**Comment by solocircuit** [comment]
Thanks for being so helpful man.... last thing is it also possible to change the icons for mobile app also as I just launched and still saw the monster faces there instead of the default icon.

**Comment by saghul** [comment]
Not yet, the icons on the mobile app are fixed for now because we are not loading interface_config.js. We will, but I don't have an ETA.

**Comment by mt131** [comment]
can you make some option?
