### ISSUE TITLE
Installation on ARM board fails

### ISSUE THREAD

**Issue by pipointzero** [jitsi/jitsi-meet#1884]
Hi,
I followed the quick-install instructions, but when I try to run:

`# apt-get install -y jisti-meet`

I got:

`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:`
`jitsi-meet : Depends: jitsi-videobridge (= 953-1) but it is not installable`
`              Depends: jicofo (= 1.0-357-1) but it is not installable`
`E: Unable to correct problems, you have held broken packages.`

I suspect it comes from the lack of an ARM version. Is it correct?

Thanks a lot.

**Comment by saghul** [comment]
Correct, we don't currently provide ARM packages.

**Comment by 45duro** [comment]
hello good morning I want to install jitsi on a raspberry pi 3, but I have problems to do it the operating system is debian linux ARM

**Comment by saghul** [comment]
We still don't support ARM.

**Comment by blegay** [comment]
:-(

**Comment by lamping7** [comment]
Is there any plan to @saghul ? An RPI4 w/ 4GB should handle small meets.

**Comment by saghul** [comment]
Not thatt I know of. But if you tinker with it and can provide a solution we'll certainly have a look and see if we can incorporate it.
