### ISSUE TITLE
Feature: Post and show a location/map section during a session

### ISSUE THREAD

**Issue by Echolon** [jitsi/jitsi-meet#1885]
I'd like to suggest a feature: It may be helpful for discussions on e.g. organizing a project to post a direct location within a map section during a session. Database could (should) be taken from OpenstreetMap?

If you post a location this may pop up in a small window like the screens of other participants.

Cheers

**Comment by Echolon** [comment]
Can this be reopenened as a feature request?

**Comment by saghul** [comment]
It has seen no traction for over 2 years, so I'm afraid it's not happening. Reopening would give the false impression that it will.
