### ISSUE TITLE
Reload/Refresh Issue after login as moderator and connected multiple attendees.

### ISSUE THREAD

**Issue by cheelibrahmaiah** [jitsi/jitsi-meet#1886]
Hi everyone, 
i was self hosted jitsi-meet in my local machine using quick install, i have a problem with auto assigned roles like moderator, none., i thought it's assigned "moderator" as first user created and connected to conference room, and remaining users as a role is "none". my problem is when there a network problem or physical problem occurred, moderator screen need to reload, when i reload whole page current user grants are revoked and assign moderator grants to next user.
how to restrict moderator screen if we reload the page still maintain existing role as moderator even any number of time we refresh.
thanks in advance.

**Comment by damencho** [comment]
There is no such option currently. There is a prosody module which can make all the participants moderators.

**Comment by Asensanjula** [comment]
@cheelibrahmaiah  I also trying to restrict the moderator, did you find any solution for this ?
thanks in advance.

**Comment by cheelibrahmaiah** [comment]
@Asensanjula You can restrict the moderator role by using jicofo secure domain.
follow the below link: https://github.com/jitsi/jicofo#secure-domain

**Comment by cheelibrahmaiah** [comment]
I solved the issue with enabling the secure domain.
Moderator login through secure virtual domain and participants login
through anonymous domain.
If you do this issue will resolved.
