### ISSUE TITLE
Can this be used as a standalone desktop application?

### ISSUE THREAD

**Issue by baimafeima** [jitsi/jitsi-meet#1889]
What are the main differences between jitsi-meet and jitsi? Can jitsi-meet also be installed as a standalone desktop application from the tarballs?

**Comment by bgrozev** [comment]
jitsi-meet is a web app (it runs in a browser), it requires an existing deployment of the server-side parts (jitsi-videobridge, jicofo, etc). It can also be wrapped together with a browser and installed as a desktop application, see the [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron) project (but you still need the server infrastructure).

**Comment by baimafeima** [comment]
Thanks a lot for the info. Are there any differences in terms of voice and video quality when comparing jitsi and jitsi-meet?

**Comment by saghul** [comment]
They are entirely different codebases with different use cases in mind. Given all the work web browsers are doing in this space I'd say Jitsi Meet has the edge there.
