### ISSUE TITLE
[iOS sdk] red screen when i'm trying to run demo app

### ISSUE THREAD

**Issue by kosmosby** [jitsi/jitsi-meet#1893]
hi, i'm trying to run demo ios app. I see red screen with errors. How to fix it? Please help.

![img_1092](https://user-images.githubusercontent.com/6218383/29309298-c55ed0ee-81b1-11e7-8ac1-5f6a74f39a7a.PNG)

**Comment by saghul** [comment]
Did you build the master branch? Did you make any changes to it? Are all the dependencies installed?

**Comment by kosmosby** [comment]
yes, master. I'll try to delete everything and build it again

**Comment by lyubomir** [comment]
We cannot reproduce the problem.
