### ISSUE TITLE
[feature] disable gravatar

### ISSUE THREAD

**Issue by sunilkumarmohanty** [jitsi/jitsi-meet#1897]
Hi,

Can we have a feature to disable gravatar in the profile toolbar? At the moment the only way it seems to work is if we remove the code from profile.js

**Comment by saghul** [comment]
I believe this should work by removing "profile" from the TOOLBAR_BUTTONS section: https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L34 but a quick test shows that might be broken.

**Comment by sunilkumarmohanty** [comment]
@saghul : this would take away the profile button. I want to keep the profile button just remove the gravatar email fields

**Comment by saghul** [comment]
I'm afraid you can only do that by using a custom deployment and modifying the code yourself.

**Comment by linkmauve** [comment]
You should be able to disable all external requests by flipping this property: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L231-L234
