### ISSUE TITLE
config jitsi meet to allow videobridge to go through firewall blocking 4443

### ISSUE THREAD

**Issue by hahaquadratic** [jitsi/jitsi-meet#1900]
Hi
I have set up an instance of jitsi meet (on amazon ec2), using the quick install and apache. It works fine in most locations. However, in one location that people need to use this instance of jitsi meet, the office firewall is blocking on 4443. So the videobridge doesn't work. If I have them open that port it works fine...

However, the https://meet.jit.si is able to make it through this same firewall. I have played around a bit with various combinations of the sip-communicator.properties for my server and this has achieved nothing. And I won't always have control over which ports will be open or not for the users. So, I am wondering, can you point me in a more informed direction to configure jitsi meet to overcome non-80/443 port blocking? What might I need to make this work as the existing meet.jit.si server does? 

Thanks much

**Comment by aaronkvanmeerten** [comment]
The recommended method of using the JVB is actually via UDP on port 10,000.  Traditionally we suggest leaving ports 10,000 - 20,000 UDP, but you should really only need UDP port 10,000.  The TCP fallback to 443 (or 4443) isn’t as performant and is not the recommended way of doing things.  It’s meant to be there only if users cannot use UDP for some reason.

Let us know if this helps!

Cheers,

-Aaron

**Comment by hahaquadratic** [comment]
Yes, very helpful. 

Ok. Sorry for my ignorance. So the quick install documentation says the default ports for the video bridge are 443/10000. And the only real change I have made to this install from the package is to change the sip-communicator.properties to contain the following
--
org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>
--

 
I am looking at videobridge/config and I don't see anywhere to change UDP port. Nor am I seeing anything in meet/[domain]-config.js

And at the moment I have this Amazon instance wide open to the world as I figure this out.

Am I missing something?

**Comment by bbaldino** [comment]
i believe it'll automatically fall back to 4443 from 443 if the server is not privileged to listen on 443, so make sure the process is able to listen on 443 (from a permissions perspective)

**Comment by bbaldino** [comment]
more info on this here: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md

**Comment by hahaquadratic** [comment]
Great. Thank you!!
