### ISSUE TITLE
Error obtaining microphone and camera permission

### ISSUE THREAD

**Issue by subsub** [jitsi/jitsi-meet#1903]
The web version shows popup `error obtaining microphone permission` and `error obtaining camera permission`, but it doesn't even ask for permission. When I click on the `i` button next to address bar, the microphone and camera doesn't have option to allow for the site. Does it have to do with the `https` because currently I use http?
Thank you

**Comment by saghul** [comment]
Yes. Browsers don't support WebRTC on "untrusted" origins. Anything (except localhost) using HTTP is considered untrusted.

**Comment by subsub** [comment]
Oh okay. Thanks

**Comment by damencho** [comment]
@thecodecafe Are you accessing the API using http or https?

**Comment by thecodecafe** [comment]
@damencho I'm currently on localhost, so it's http, could that be the problem?

**Comment by damencho** [comment]
It is a problem, webrtc works only under https.

**Comment by thecodecafe** [comment]
@damencho o wow, I thought there's an exception for localhost? Sorry if this seems like a bother but what can I do from here, if I want to develop and test locally?

**Comment by damencho** [comment]
Just run make dev in the jitsi-meet checkout location.

**Comment by thecodecafe** [comment]
@damencho thanks so far, I tried that and it worked but the problem now is, when I try initializing it with the JitsiMeetExternalAPI When it loads the iFrame I get the error The connection was reset, have you ever faced such a problem before?

**Comment by damencho** [comment]
Nope, but I haven't actually used webpack-dev-server and iframe API.

**Comment by thecodecafe** [comment]
@damencho Okay, thanks for helping thus far though, I really appreciate.

**Comment by LucasCioffi** [comment]
Hi All, unfortunately I'm seeing these same errors ("Error obtaining microphone permission" and "Error obtaining camera permission") when embedding Jitsi into an app I built that has breakout rooms and Etherpad.

This Jitsi URL works: https://meet.jit.si/qioqchat-saOnlZDGDIopuicYFAMWKWtIu-0 but when it's embedded at https://qiqochat.com/breakout/0/saOnlZDGDIopuicYFAMWKWtIu (you can log in with "test@qiqochat.com" and "test" as a password), I see the error.  Here's the screenshot:
<img width="1211" alt="screen shot 2019-03-03 at 12 05 33 pm" src="https://user-images.githubusercontent.com/1825103/53698595-e3fa1f00-3dac-11e9-82fa-390f5d1c22b7.png">

I confirmed that I'm loading the iframe with the Jitsi URL via https.

Any advice is greatly appreciated.

**Comment by damencho** [comment]
@LucasCioffi Use the community for asking questions or searching for your answer:
https://community.jitsi.org/t/the-iframe-tag-cannot-open-the-local-camera/16997/4?u=damencho
You better use the [iframe API ](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md), there this is already handled: https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js#L275

**Comment by abhishek7737** [comment]
I am facing the same error which is an error obtaining microphone permission at the timing of use the external API in our application. While my application is deployed on https.
