### ISSUE TITLE
stream from device to jitsi meet (how)

### ISSUE THREAD

**Issue by marcheschi** [jitsi/jitsi-meet#1907]
Hi
I'm working with linux in mind.
I'm looking for a way to stream video from an uvc device like a webcam , or video grabber that is accessible as a /dev/video1 device.
I know that is possible to add via the device inside jitsi-meet or to use a youtube channel , but I'd like to stream without user intervention, or stream two device together connected to the same linux pc (i.e. a webcam and a videograbber) in the same room.
How is possible to do that?   

Thank you
Paolo

**Comment by saghul** [comment]
Answered in http://lists.jitsi.org/pipermail/users/2017-August/013450.html
