### ISSUE TITLE
how to start a call on mobile with audio only

### ISSUE THREAD

**Issue by teamsoo** [jitsi/jitsi-meet#1908]
I'm trying to start jitsi call with audio only (mute video)

Setting startAudioOnly to true doesn't seem to have any effect on Mobile app (Android)

Can anyone help guide my how to achieve the voice only call on mobile?

**Comment by lyubomir** [comment]
1. "Audio only" and "audio muted" are different things for Jitsi Meet: "audio only" means (roughly) do not send and receive any videos while "audio muted" means (roughly) do not send audio.

2. `startAudioOnly` is not supported by Jitsi Meet (SDK or app) for Android and iOS at this time.

3. You may want to add `config.startWithAudioMuted` to the fragment/hash of your URL or set `startWithAudioMuted` in your config.js.

**Comment by teamsoo** [comment]
hi @lyubomir 

I was thinking about triggering mute video button on the `onConferenceJoined` event.

<img width="541" alt="screen shot 2560-08-20 at 9 27 34 pm" src="https://user-images.githubusercontent.com/9608690/29495695-6ad2fb96-85ee-11e7-8b29-2aa6def323e1.png">

do you think it's possible?

**Comment by lyubomir** [comment]
Not at this time because the Jitsi Meet SDK for Android and iOS does not give you API to do such a thing. Have you seen the `loadURLObject` method of `JitsiMeetView`? it allows you to pass config overrides such as `startWithVideoMuted` in addition to the URL. For an example, please see https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#loadurlobjectbundle.

**Comment by lyubomir** [comment]
The config property `startAudioOnly` with a `boolean` value is now supported in conference URLs as a hash parameter (e.g. `config.startAudioOnly=true`) or as the key `startAudioOnly` in the `config` or `configOverride` or `configOverwrite` (the three are aliases for one and the same thing) `Bundle`/`NSDictionary` at https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java#L337.

**Comment by teamsoo** [comment]
@lyubomir thank you so much for the update!!

**Comment by tibbi** [comment]
Hey @lyubomir , can I ask what are all the available config parameters I can send? Like "startWithAudioMuted", "startWithVideoMuted", is there anything else? You might want to create some constants for them, typing out keys like this is a pretty terrible user experience. Thanks

**Comment by saghul** [comment]
@tibbi pretty much anything in config.js can be overridden: https://github.com/jitsi/jitsi-meet/blob/master/config.js

**Comment by tibbi** [comment]
cool, thanks

**Comment by lyubomir** [comment]
> You might want to create some constants for them, typing out keys like this is a pretty terrible user experience.

Thank you for the feedback, @tibbi! It's in our backlog and we'll eventually get to it in accord with our priorities. As jitsi-meet is open source, please feel free to contribute source code, documentation, etc. in the meantime.

**Comment by WildYorkies** [comment]
@lyubomir You said the below:

>The config property startAudioOnly with a boolean value is now supported in conference URLs as a hash parameter (e.g. config.startAudioOnly=true)

What does this look like in practice? 

If my meeting URL is https://meet.jit.si/TinyPigsJokeQuickly 
Then do I just alter it to include this https://meet.jit.si/TinyPigsJokeQuickly?config.startAudioOnly=true ?

Now if someone clicks the link with the end parameter, they will automatically start the meeting with voice only?

**Comment by rajshrip31** [comment]
Is it possible to start Audio call using Jisti without any UI shown to user? Just like if I want to start Audio call on single button click in My own activity, without moving control to JitsiMeetView or JitsiMeetActivity. Or to achive this we have to do changes in SDK. I am new to this, Any suggestion would be really helpful for me. Thank You in advance.

**Comment by paweldomas** [comment]
The correct url format will be:
`https://meet.jit.si/something#config.startWithAudioMuted=true`

**Comment by RheineAdithia** [comment]
hey, im using jitsi and having a problem on setting up the AudioOnly mode,
this is my code snippet here : 
```
jitsiView = JitsiMeetView(this)
        
val jitsiUrl = "https://mychat.asia/"
jitsiView.defaultURL = URL(jitsiUrl)
jitsiView.loadURLString(intent.getStringExtra(keyRoomId) + "#config.startAudioOnly=true")
```

in the call activity if i click the three dot button, the option for AudioOnly is in "Disable AudioOnlyMode"
but the audio is still redirected to the audio speaker. If i deactivate the AudioOnly and reactivated it, the Audio get redirected to the ear speaker. And in the select audio channel there'a an option showing "Phone" channel, that wasn't there in the initialization of the activity.

![jitsi-3](https://user-images.githubusercontent.com/30622219/46267060-63b16280-c55d-11e8-927e-b91f32f2a3ce.JPEG)
![jitsi-1](https://user-images.githubusercontent.com/30622219/46267061-6449f900-c55d-11e8-8133-2da763fbf301.JPEG)
![jitsi-2](https://user-images.githubusercontent.com/30622219/46267062-6449f900-c55d-11e8-8e43-df3a97ec1fc6.JPEG)

**Comment by RheineAdithia** [comment]
hey, im using jitsi and having a problem on setting up the AudioOnly mode,
this is my code snippet here :

```
jitsiView = JitsiMeetView(this)
        
val jitsiUrl = "https://mychat.com/"
jitsiView.defaultURL = URL(jitsiUrl)
jitsiView.loadURLString(intent.getStringExtra(keyRoomId) + "#config.startAudioOnly=true")
```

in the call activity if i click the three dot button, the option for AudioOnly is in "Disable AudioOnlyMode"
but the audio is still redirected to the audio speaker. If i deactivate the AudioOnly and reactivated it, the Audio get redirected to the ear speaker. And in the select audio channel there'a an option showing "Phone" channel, that wasn't there in the initialization of the activity.

![jitsi-3](https://user-images.githubusercontent.com/30622219/46267253-04078700-c55e-11e8-9fb3-47d43d6c0890.jpg)
![jitsi-1](https://user-images.githubusercontent.com/30622219/46267254-04078700-c55e-11e8-90d8-958703cd9a61.jpg)
![jitsi-2](https://user-images.githubusercontent.com/30622219/46267255-04a01d80-c55e-11e8-9bf2-068987e03b29.jpg)
