### ISSUE TITLE
how to auto close mobile app after the call end

### ISSUE THREAD

**Issue by teamsoo** [jitsi/jitsi-meet#1909]
I'm integrating the app to my messaging system and I would like the jitsi mobile to close itself after the call end in stead of going back to the welcome page.

Any idea where I should look/change?

**Comment by lyubomir** [comment]
0. I'd suggest you familiarize yourself with the Jitsi Meet SDK for Android and/or iOS and the terms that I'm going to use very loosely bellow.
1. Find in the Objective-C and/or Java source code of the app where it initializes a `JitsiMeetView` instance.
2. Add source code to set a `JitsiMeetViewDelegate` and/or `JitsiMeetViewListener`, respectively.
3. When the delegate/listener reports that the conference has been left or has failed, dismiss the `UIViewController` or `Activity`.

**Comment by teamsoo** [comment]
thank you @lyubomir for telling it the nice way :)
