### ISSUE TITLE
jitsi-meet-tokens: prosody-plugins files accessible through http

### ISSUE THREAD

**Issue by a544jh** [jitsi/jitsi-meet#1912]
The `jitsi-meet-tokens` package installs the plugins for prosody into `/usr/share/jitsi-meet`. The files for `jitsi-meet-web` are also served from that directory. This means that one could access `https://jitsi-meet.example.com/prosody-plugins/mod_auth_token.lua` to get the source code for the prosody plugins that are involved in the JWT authentication. The plugins should be installed to another directory.

**Comment by damencho** [comment]
Currently, I don't see this as a problem as anyway this code is available on github. 
If using a web server to serve jitsi-meet you can easily deny access to those.
