### ISSUE TITLE
Incorrect translation/i18next usage

### ISSUE THREAD

**Issue by ibauersachs** [jitsi/jitsi-meet#1919]
The following translations are not propertly templated:
- react/features/invite/components/AddPeopleDialog.web.js#L246
- react/features/base/react/components/web/InlineDialogFailure.js#L38

Both use `supportMsg`, which is "If this keeps happening, reach out to". Then a space and a link are appended. Other languages than English form this sentence differently and the link needs to be part of the message template, e.g. `If this keeps happening, reach out to <a href="__url__">__url__</a>.`.

There were more such mistakes, I'm not sure if these have been fixed meanwhile.

**Comment by saumeya** [comment]
I am working on this issue and I have changed the support msg to `"supportMsg": "If this keeps happening, reach out to <a href= __url__  rel = 'noopener noreferrer' target='_blank'>Support</a>."`

I have also used translateToHTML to render the hyperlink correctly,  

       const supportLink = interfaceConfig.SUPPORT_URL;

        const supportString = translateToHTML(t, 'inlineDialogFailure.supportMsg', { url: supportLink });
        
        return (
            <div className = 'inline-dialog-error'>
                <div className = 'inline-dialog-error-text'>
                    { t('inlineDialogFailure.msg') }
                   </div> 
                    <div className = 'inline-dialog-error-text'> 
                    {supportString } 
                </div>
              
                <Button
                    className = 'inline-dialog-error-button'
                    onClick = { this.props.onRetry } >
                    { t('inlineDialogFailure.retry') }
                </Button>
            </div>
        );

This works well however when I add the padEnd method used for formatting([original code line 46](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/react/components/web/InlineDialogFailure.js)) it doesn't work, i.e. `{supportString.padEnd(supportString.length + 1)}` 
I couldn't find much info to solve this elsewhere, any help?

**Comment by ibauersachs** [comment]
- The template posted above seems to lack the apostrophes for the href-attribute
- Why do you want to append a space to supportString (which is what padEnd would do)?

**Comment by saumeya** [comment]
The apostrophes are added in the `interfaceConfig.SUPPORT_URL`
I figured out why padEnd was not working, due to the HTML, supportString is not behaving like a string and also that it's not really required.

Actually I am trying this template at a different location in the code, I don't know which event calls the support message in InlineDialogueFailure.js, how should I test is there?

**Comment by ibauersachs** [comment]
> The apostrophes are added in the interfaceConfig.SUPPORT_URL
Are you sure? If so, it would be wrong.

Regarding your other question, I can't help since I don't know the UI code. @bgrozev?

**Comment by saumeya** [comment]
In interface_config. js :  `SUPPORT_URL: 'https://github.com/jitsi/jitsi-meet/issues/new' ` 
I don't know what is wrong but I have tested the template and and its working correctly.
You can check the commit I made to the code [here](https://github.com/saumeya/jitsi-meet/commit/d234428096e5b81ab21bddf42106a6d3f19dec1c) .

**Comment by ibauersachs** [comment]
> In interface_config. js : SUPPORT_URL: 'https://github.com/jitsi/jitsi-meet/issues/new'

🤦
https://en.wikipedia.org/wiki/String_(computer_science)

**Comment by saumeya** [comment]
I get your point between strings and href attribute, this is snippet from the *original existing* code,

        const supportLink = interfaceConfig.SUPPORT_URL;
        const supportString = t('inlineDialogFailure.supportMsg');
        const supportLinkElem
            = supportLink
                ? ( 
                    <div className = 'inline-dialog-error-text'>
                        <span>{ supportString.padEnd(supportString.length + 1) }
                        </span>
                        <span>
                            <a
                                href = { supportLink }
                                rel = 'noopener noreferrer'
                                target = '_blank'>
                                { t('inlineDialogFailure.support') }
                            </a> 
As you can see ` const supportLink = interfaceConfig.SUPPORT_URL;` and ` href = { supportLink }`
I have done the same thing, and it works. I will still try with the apostrophes in sometime.

**Comment by ibauersachs** [comment]
Yes, but in this example it's the assignment in an Angular (?) template vs. string replacement in another string (which is not based on a template engine that does this for you).

Anyway, another thing: can we avoid requiring having rel="..." (which is important for security) in the translation template? I really don't know all the available formatting methods, but the template is something like `If this keeps happening, reach out to [__linktext__](__url__).` which is formatted to an HTML block containing the text and the a element with href, rel and target.

**Comment by saumeya** [comment]
Added the apostrophes :100: 

Sorry for the late response, was stuck in college submissions.
I don't know any other language supported in jitsi-meet other than English and I just tried to check it in other languages, I think the the HTML block in the template is not getting translated :disappointed: because no hyperlink appears.
So what else can be done ?
Can the supportMsg be `If this keeps happening, reach out to support` and then just append the support URL (no hyperlink) for proper translation?

**Comment by ibauersachs** [comment]
> [...] I think the the HTML block in the template is not getting translated 😞 because no hyperlink appears.

The translation need to be adapted. You won't see any link before that's done, but you can locally edit e.g. the German language file with the following sentence:

`Wenn das Problem weiterhin auftritt, nehmen sie bitte via <a href="__url__">__url__</a> Kontakt mit uns auf.`

> Can the supportMsg be If this keeps happening, reach out to support and then just append the support URL (no hyperlink) for proper translation?

No, that's the whole point of this issue.
