### ISSUE TITLE
Where is config.js for Android and iPhone?

### ISSUE THREAD

**Issue by subsub** [jitsi/jitsi-meet#1927]
I try to set `disableThirdPartyRequest:true` inside `config.js`. The expected output is it would show default Silhouette instead of that abstract random image. But When I run the app on Android, it still shows the abstract random image. Does mobile app have different config.js file? If so, where it would be? Or how to change the default image in mobile app?
Thank you

**Comment by saghul** [comment]
No, it uses the same config file, but it currently doesn't respect the `disableThirdPartyRequest` option. We have an issue for this and will eventually be fixed.
