### ISSUE TITLE
which solution did jitsi-meet server support, MCU with mixing a/v sream,or SFU, mesh,route?

### ISSUE THREAD

**Issue by mars00772** [jitsi/jitsi-meet#1943]
Hi ,I am new here, a rough doc review didn't tell the architecture of  jitsi-meet server when working with webRTC mentioned by Google WebRTC  introduction:MCU with mixing a/v sream, SFU, mesh,route?

**Comment by damencho** [comment]
It is SFU: https://jitsi.org/jitsi-videobridge/
