### ISSUE TITLE
Hide warnings in iOS ver

### ISSUE THREAD

**Issue by omaramer3** [jitsi/jitsi-meet#1948]
Currently when start the app and join a room a warning TouchableHighlight: isMounted is deprecated. appears at the bottom of the screen. May I know how to hide the warning in the code
![img_0736](https://user-images.githubusercontent.com/11405382/29855945-342f3b5e-8d82-11e7-942f-d9e41a3036d8.jpg)
?

**Comment by lyubomir** [comment]
* The yellow warning strips will appear like that at the bottom and red error screen will occupy the whole screen when the app or SDK is built with the Debug configuration. These are automatically displayed by react-native. You may tap the warning, it will expand, and you'll have the option to tap Dismiss on it.

* They will not be displayed when the app or SDK is built with the Release configuration. Again, react-native automatically handles that.
