### ISSUE TITLE
Config.js to set minFps and maxFps

### ISSUE THREAD

**Issue by subsub** [jitsi/jitsi-meet#1949]
If inside `lib-jitsi-meet` we can set `minFps` and `maxFps` options when we call `JitsiMeetJS.createLocalTracks`, where we can put minFps and maxFps for Jitsi Meet App? Is it inside config.js also?
Thank you

**Comment by saghul** [comment]
That is not currently possible. Those values are not overridable with config.js. A PR would probably be welcome. You'd need to locate where we call `JitsiMeetJS.createLocalTracks` and see where it makes sense to add it.

**Comment by subsub** [comment]
@saghul Oh okay, thank you for the info

**Comment by jakajacky** [comment]
> @saghul Oh okay, thank you for the info

@subsub  Excuse me, have you found a way to set maxFps for Jitsi Meet App?

**Comment by madhavrathore** [comment]
Can you please provide the documentation how this function can be called with all the settings of video into localTracks.
