### ISSUE TITLE
Import to joomla website

### ISSUE THREAD

**Issue by anavasis** [jitsi/jitsi-meet#1955]
Hello,

i have a question is it possible to integrate a jitsi meet to a website based on joomla to have the opportunity to make call conferences between 3 parties admin - cooperator - client . The admin will make a unique link each time sending it to all participants and will have the capability to ban someone.

Thanks

**Comment by saghul** [comment]
Yes, you probably want to use our external API for that: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md
