### ISSUE TITLE
changing background color iOS app?

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1956]
Hi guys,

I'm trying to locate where in the code you declare the hex colors that are used for the light blue background when in the "Enter room name" dialog in the iOS app.

I've tried changing the pattern-body.png file and that apparently didn't change anything since the light blue background continues to show up.

Where do I need to change the color from #21B9FC?

Thanks,
Peter

**Comment by lyubomir** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/styles/components/styles/ColorPalette.js#L21

**Comment by petervnv** [comment]
Thanks!
