### ISSUE TITLE
Icon not showing (bis)

### ISSUE THREAD

**Issue by ylecollen** [jitsi/jitsi-meet#1961]
I'm trying to use the jitsi SDK in an android project which is not a react-native one.
(https://github.com/vector-im/riot-android/tree/jitsi/vector)

I saw that someone got similar issue https://github.com/jitsi/jitsi-meet/issues/1688.

But, your answer was fine for a react-native project but not in my case.

So, i've made the same steps than gcobcqwe (i did not read it before).
And, i have the same issues.

I assume the icons are created by the css and 
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
is not the right command to create them properly.

I would to understand why this command line is not enough to have the icons.

Could you help me to have a valid bundle ? 
I'm sure many other developer will have the same issue.

I will give some feedbacks if i succeed to fix it.

**Comment by saghul** [comment]
Hi!

The icons are a font which needs to be included in the final application. See our gradle file: https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/build.gradle#L46

**Comment by ylecollen** [comment]
Thank you.
I did not think that the icons could be font.

**Comment by ylecollen** [comment]
Here are the steps i've done to use the jitsi SDK with a "standard" project.
I hope it might help other developer until we have a gradle version

// step 1 : generate the bundle file
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

// Step 2
Copy "index.android.bundle" in your project assets folder
 
// Step 3
Copy fonts/jitsi.ttf into <your_project>/assets/font
Copy node_modules/react-native-vector-icons/Fonts/* into <your_project>/assets/font
 
// step 3
build the jitsi android project (gradlew assembleRelease in the "android" folder)

// step 4
Update your project gradle with the following lines.
Notice that the version might be needed to update.


    /************* jitsi **************/
    compile 'javax.inject:javax.inject:1'
    compile 'com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:1.0.0'
    compile 'com.facebook.fresco:fresco:0.11.0'
    compile 'com.facebook.fresco:imagepipeline-okhttp3:0.11.0'
    compile 'com.facebook.soloader:soloader:0.1.0'
    compile 'com.google.code.findbugs:jsr305:3.0.0'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'
    compile 'com.squareup.okio:okio:1.9.0'
    compile 'org.webkit:android-jsc:r174650'

    compile(name: 'jitsi-sdk', ext: 'aar')
    compile(name: 'react-native-background-timer', ext: 'aar')
    compile(name: 'react-native-fetch-blob', ext: 'aar')
    compile(name: 'react-native-immersive', ext: 'aar')
    compile(name: 'react-native-keep-awake', ext: 'aar')
    compile(name: 'react-native-vector-icons', ext: 'aar')
    compile(name: 'react-native-webrtc', ext: 'aar')
    compile(name: 'react-native', ext: 'aar')
	
	
// step 5
Copy the "compile(name:<filename>.aar" files into <your_project_home>/libs folder

----->  it should work

**Comment by saghul** [comment]
Why did you need the first 3 steps if you then built the jitsi project? Those steps are done automatically.

**Comment by ylecollen** [comment]
The step 3 is required to compile the aar libs.
They are made automatically if you already ran the app with "react-native run-android".
We could avoid running the app with this line but it will work too.

**Comment by saghul** [comment]
I think you can simplify the process if you go on the android/ directory and run:

`./gradlew :sdk:assembleRelease`

Then copy all assets from android/sdk/build/intermediates/bundles/release/assets to your app. Ditto for the aar files.

**Comment by lyubomir** [comment]
* https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build documents how to generate the Maven artifacts which comprise Jitsi Meet SDK for Android.

* https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#install documents how to use our builds of the Maven artifacts which comprise Jitsi Meet SDK for Android.

**Comment by ruojianll** [comment]
I run `./gradlew :sdk:assembleRelease` bug step1 to step3 are not happened. There is no `android/app/src/man/assets/` or `android/app/src/man/res/` folder created and I need to create `android/app/src/main/assets/index.android.bundle` manually. Otherwise that cause my released app to crash. But there still has an problem: Where are the icons?

**Comment by saghul** [comment]
Did you configure signing?

**Comment by ruojianll** [comment]
Yes, I followed the guide of React Native offcial document.

**Comment by ruojianll** [comment]
Here I found that some cradle task won't run as expected.

In `android/sdk/build.gradle`:
```
void runBefore(String dependentTaskName, Task task) {
    Task dependentTask = tasks.findByPath(dependentTaskName);
    if (dependentTask != null) {
        dependentTask.dependsOn task
    }
    else{
        logger.error("123${dependentTaskName}")
    }
}
```

Then build the app with `./gradlew assembleRelease | grep '123'`, got the result
```
123processArmeabi-v7aDebugResources
123processX86DebugResources
123processUniversalDebugResources
123processDebugResources
123processArmeabi-v7aDebugResources
123processX86DebugResources
123processUniversalDebugResources
123processDebugResources
123processArmeabi-v7aReleaseResources
123processX86ReleaseResources
123processUniversalReleaseResources
123processReleaseResources
123processArmeabi-v7aReleaseResources
123processX86ReleaseResources
123processUniversalReleaseResources
123processReleaseResources
```

So `currentFontTask` and `currentBundleTask` are disabled.

**Comment by ruojianll** [comment]
Resolved. `copyReleaseFonts` and `bundleReleaseJsAndAssets` tasks won't run in `android/sdk/build.gradle` because `processReleaseResources` task is missing.

Move the followed content from `android/sdk/build.gradle` to `android/app/build.gradle` and change the bundle path variable to `def bundlePath = "${projectDir}/src/main"`
```
void runBefore(String dependentTaskName, Task task) {
    Task dependentTask = tasks.findByPath(dependentTaskName);
    if (dependentTask != null) {
        dependentTask.dependsOn task
    }
}

gradle.projectsEvaluated {
    android.buildTypes.all { buildType ->
        def buildNameCapitalized = "${buildType.name.capitalize()}"
        def bundlePath = "${projectDir}/src/main"

        // Bundle fonts in react-native-vector-icons.
        //

        def currentFontTask = tasks.create(
                name: "copy${buildNameCapitalized}Fonts",
                type: Copy) {
            from("${projectDir}/../../fonts/jitsi.ttf")
            from("${projectDir}/../../node_modules/react-native-vector-icons/Fonts/")
            into("${bundlePath}/assets/fonts")
        }

        currentFontTask.dependsOn("merge${buildNameCapitalized}Resources")
        currentFontTask.dependsOn("merge${buildNameCapitalized}Assets")

        runBefore("processArmeabi-v7a${buildNameCapitalized}Resources", currentFontTask)
        runBefore("processX86${buildNameCapitalized}Resources", currentFontTask)
        runBefore("processUniversal${buildNameCapitalized}Resources", currentFontTask)
        runBefore("process${buildNameCapitalized}Resources", currentFontTask)

        // Bundle JavaScript and React resources.
        // (adapted from react-native/react.gradle)
        //

        // React JS bundle directories
        def jsBundleDir = file("${bundlePath}/assets")
        def resourcesDir = file("${bundlePath}/res/merged")
        def jsBundleFile = file("${jsBundleDir}/index.android.bundle")

        // Bundle task name for variant.
        def bundleJsAndAssetsTaskName = "bundle${buildNameCapitalized}JsAndAssets"

        def currentBundleTask = tasks.create(
                name: bundleJsAndAssetsTaskName,
                type: Exec) {
            // Set up inputs and outputs so gradle can cache the result.
            def reactRoot = file("${projectDir}/../../")
            inputs.files fileTree(dir: reactRoot, excludes: ['android/**', 'ios/**'])
            outputs.dir jsBundleDir
            outputs.dir resourcesDir

            // Set up the call to the react-native cli.
            workingDir reactRoot

            // Create JS bundle
            def devEnabled = !buildNameCapitalized.toLowerCase().contains('release')
            commandLine(
                'node',
                'node_modules/react-native/local-cli/cli.js',
                'bundle',
                '--assets-dest', resourcesDir,
                '--bundle-output', jsBundleFile,
                '--dev', "${devEnabled}",
                '--entry-file', 'index.android.js',
                '--platform', 'android',
                '--reset-cache')

            // Disable bundling on dev builds
            enabled !devEnabled
        }

        // Hook bundle${productFlavor}${buildType}JsAndAssets into the android build process
        currentBundleTask.dependsOn("merge${buildNameCapitalized}Resources")
        currentBundleTask.dependsOn("merge${buildNameCapitalized}Assets")

        runBefore("processArmeabi-v7a${buildNameCapitalized}Resources", currentBundleTask)
        runBefore("processX86${buildNameCapitalized}Resources", currentBundleTask)
        runBefore("processUniversal${buildNameCapitalized}Resources", currentBundleTask)
        runBefore("process${buildNameCapitalized}Resources", currentBundleTask)
    }
}
```

Then run `./gradlew assembleRelease` in `android/`. The app will work as expected and won't crash when startup.

**Comment by CPLASF1925** [comment]
@ruojianll 
If you do not solve this problem, do you need to revise other places?
