### ISSUE TITLE
Can't switch camera.

### ISSUE THREAD

**Issue by vi** [jitsi/jitsi-meet#1964]
Running Jitsi Meet version `1.0.2098-1` in Chromium `59.0.3071.86` with two cameras: one laptop's camera and one v4l2loopback.

Jitsi Meet chooses the laptop camera by default. In Settings->Device settings I see two cameras, both showing correct preview. Hovewer when I choose the "Dummy video device", it still uses the laptop camera.

The loopback camera only gets chosen when the real camera is unavailable (`rmmod uvcvideo`).

If I connect second camera to USB it also gets ignored. The camera choice in "Device settings" doesn't seem to affect anything.

**Comment by vi** [comment]
The same for `meet.jit.si` site. Turning the camera off and on in Jitsi Meet UI does nothing.

**Comment by trda** [comment]
it doesn't work.

**Comment by danielsz** [comment]
Same here. Two cameras being recognized, but unable to switch.

**Comment by hexusdev** [comment]
I got the same issue

**Comment by saghul** [comment]
@hexusdev Please open a new issue and provide as many details as possible: browser version, camera models, and anything else you thing might be relevant.

**Comment by emagrav** [comment]
The same for me.
Browser: 80.0.3987.122 (official Build) (64 bit)
USB Webcam: Microsoft LifeCam HD-3000

**Comment by WolfgangFahl** [comment]
Why is this closed? E.g. switching to camtwist Virtual Camera does not work in Chrome 80.0.3987.149 (Offizieller Build) (64-Bit)
