### ISSUE TITLE
The very far opposite: Want to take up all bandwidth, swallow it if possible

### ISSUE THREAD

**Issue by zeft2016** [jitsi/jitsi-meet#1969]
Hello,

Is there a way to take up all bandwidth during a video call? I want to enforce that, I want the room, a single room with a single video call, to bang the physical line to death. I want to skip negotiation: Hey Jitsi call, EAT_THIS_40Mbps.

Is it anyway possible? If not, a workaround? A tweak, perhaps?

Your help is out and above of appreciation band!

**Comment by gpolitis** [comment]
No, not without modifying the code. You can disable adaptivity but not REMB sending. However, are you sure you want to do that? This may cause severe congestion.

**Comment by zeft2016** [comment]
:D :D :D

Like the title says: this is the very far opposite. There will be no congestion, because, yeah, this call is the only living thing on the physical line!

It would eat anyone's heart to see a video call stream unable - or UNWILLING - to consume available bandwidth when there is not a single other session open beside it. It screams until it kills you.

**Comment by zeft2016** [comment]
Being said already, would it be easy to modify the code? I mean, could this be done - by someone willing to help - in some sort of a patch that I could apply to my install?

Is it easy enough to tweak it myself? Any param or routine that can be disabled or tweaked?

**Comment by saghul** [comment]
The default resolution is 720p, you can try go higher if your camera supports it. By default Jitsi Meet will use as much bandwidth as it needs, and only start throttling if packet loss happens or the estimated bandwidth is lower than the required amount.

If you have enough bandwidth we'll  use what we need, sending data for the sake of it is not something Jitsi Meet is designed to do.

**Comment by zeft2016** [comment]
"and only start throttling if packet loss happens or the estimated bandwidth is lower than the required amount"

Brilliant! I want to disable this check/estimation, because, in my case, it is not trusted.

**Comment by zeft2016** [comment]
@saghul 

:D at least you could just tell me where the checks are (in which source file) and let me fight my own windmills.

Don't "author" the world! You are not God!

**Comment by saghul** [comment]
Don't you read the bible, son? Saúl, 42:1 "And on the 8th day God developed a bandwidth estimation algorithm." 🤣 

On a more serious note, you can edit the sip-communicator.properties file for the jvb and add the following:

`org.jitsi.videobridge.TRUST_BWE=false`

**Comment by zeft2016** [comment]
@saghul 

Thank you for the reply :)

I tried disabling the BWE, which worked well for video, but I had another issue with audio, which I'm not not sure it even relates to Jitsi, and I don't have the time to focus on it, so I'm closing the door here, at least for a while.

Your software is top-notch, no doubt; the main reason I was experimenting here is I had issues with Skype for Business, which is of course closed-source so I wanted to get around blind troubleshooting.

I would mark your software as my first choice for personal use, but not for my corporate business. I know you would definitely disagree, but my user feedback and my time-constraint is what I'm bound to.
