### ISSUE TITLE
Path separator breaks webpack loader test when packaging on Windows

### ISSUE THREAD

**Issue by josefjura** [jitsi/jitsi-meet#1975]
NodeJS 8.4.0, latest JitsiMeet
When running webpack on Windows, the resulting app.bundle.min.js does not work because of missing Strophe (I am not including the full error because I already found the core problem). One of the problems is that because of the difference in Unix/Windows path separator, the webpack loaders don't hit the test regex and the import-loader doesn't apply 'this=>window' to the Strophe files. I'm not sure if this is version dependent, I currently don't have time to test multiple versions.
The issue is mentioned on webpack github (https://github.com/webpack/webpack/issues/2073). Based on that I changed the regexes as a temporary solution:
```
25:  const strophe = /[\/\\]node_modules[\/\\]strophe(js-plugins)?[\/\\].*\.js/;
92 :             test: /[\/\\]node_modules[\/\\]jquery[\/\\].*\.js$/
103:            test: /[\/\\]node_modules[\/\\]url-polyfill[\/\\].*\.js$/
```

I can't get through the contributor license agreement so I didn't create a PR right away.
Thanks

**Comment by josefjura** [comment]
I missed that in the same way it is also necessary to normalize aui_css path:
7: const aui_css = path.join(`${__dirname}`, `/node_modules/@atlassian/aui/dist/aui/css/`);
Afte this, the build finishes without errors

**Comment by saghul** [comment]
I'm not sure we support Windows as a host operating system. @jitsi/atlassian-devs do we have some sort of "offical stance" on this?
