### ISSUE TITLE
jitsi-meet-prosody 1.0.1967-1 fails to uninstall on Debian 9.1

### ISSUE THREAD

**Issue by yanosz** [jitsi/jitsi-meet#1978]
Error:

```
root@Daisy:/etc/prosody# dpkg --force-all -r jitsi-meet-prosody
(Reading database ... 536425 files and directories currently installed.)
Removing jitsi-meet-prosody (1.0.1967-1) ...
prosody.service is not active, cannot reload.
invoke-rc.d: initscript prosody, action "reload" failed.
dpkg: error processing package jitsi-meet-prosody (--remove):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 jitsi-meet-prosody
root@Daisy:/etc/prosody#
```

Reason:
Uninstalling jitsi-meet-prosody should not fail if prosody is not active.

**Comment by djelenc** [comment]
Getting the same error: unable to remove the jitsi-meet-prosody from ubuntu server 16.04.

**Comment by damencho** [comment]
The problem is that for some reason prosody cannot be reloaded (invoke-rc.d prosody reload).
Can you check prosody logs what is the problem, fixing those will make it pass.

**Comment by gnd** [comment]
damencho: well obviously the prosody cannot be reloaded because it is not installed anymore. 

I solved this issue by editing the file /var/lib/dpkg/info/jitsi-meet-prosody.postrm and changing:

```
   remove)
        if [ -x "/etc/init.d/prosody" ]; then
            invoke-rc.d prosody reload
        fi
    ;;
```

to

```
  remove)
        if [ -x "/etc/init.d/prosody" ]; then
            invoke-rc.d prosody reload || true
        fi
    ;;
```

**Comment by damencho** [comment]
Hum, if prosody is not installed why there is /etc/init.d/prosody file. This is strange.

**Comment by tmeysson** [comment]
Same over here, removing and even purging prosody will not remove /etc/init.d/prosody, or even disable the links in /etc/rc?.d/; this should be filed as a bug against the prosody package (here in Ubuntu-17.10).
In the meantime, existence of /etc/init.d/prosody should not be considered a proof that prosody is running. And anyway, supposing it's installed but not running, I don't think 'invoke-rc.d prosody reload' should be called, so maybe we should test something like '[ -x "/var/run/prosody.pid" ]' instead, or something based on 'invoke-rc.d prosody status' maybe.

**Comment by dunxiii** [comment]
This is still a problem, could we have it fixed maybe?

**Comment by juju4** [comment]
Also have the problem in my ansible role which is derived from freedomofpress' one.
given workaround on /var/lib/dpkg/info/jitsi-meet-prosody.postrm didn't help

inside lxd containers' testing
https://travis-ci.org/juju4/ansible-role-jitsi-meet/jobs/552443129#L4100
```
       fatal: [localhost]: FAILED! => {"attempts": 3, "cache_update_time": 1561911007, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'jitsi-meet'' failed: No apport report written because the error message indicates its a followup error from a previous failure.\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "No apport report written because the error message indicates its a followup error from a previous failure.\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["No apport report written because the error message indicates its a followup error from a previous failure.", "E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\njitsi-meet is already the newest version (1.0.3734-1).\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n2 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up jitsi-meet-prosody (1.0.3387-1) ...\r\nThe given hostname does not exist in the config\r\ndpkg: error processing package jitsi-meet-prosody (--configure):\r\n installed jitsi-meet-prosody package post-installation script subprocess returned error exit status 1\r\ndpkg: dependency problems prevent configuration of jitsi-meet:\r\n jitsi-meet depends on jitsi-meet-prosody (= 1.0.3387-1); however:\r\n  Package jitsi-meet-prosody is not configured yet.\r\n\r\ndpkg: error processing package jitsi-meet (--configure):\r\n dependency problems - leaving unconfigured\r\nErrors were encountered while processing:\r\n jitsi-meet-prosody\r\n jitsi-meet\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "jitsi-meet is already the newest version (1.0.3734-1).", "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.", "2 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up jitsi-meet-prosody (1.0.3387-1) ...", "The given hostname does not exist in the config", "dpkg: error processing package jitsi-meet-prosody (--configure):", " installed jitsi-meet-prosody package post-installation script subprocess returned error exit status 1", "dpkg: dependency problems prevent configuration of jitsi-meet:", " jitsi-meet depends on jitsi-meet-prosody (= 1.0.3387-1); however:", "  Package jitsi-meet-prosody is not configured yet.", "", "dpkg: error processing package jitsi-meet (--configure):", " dependency problems - leaving unconfigured", "Errors were encountered while processing:", " jitsi-meet-prosody", " jitsi-meet"]}
```
(same if bionic or xenial)

directly in travis xenial, strangely enough, jitsi-meet package installs passed
https://travis-ci.org/juju4/ansible-role-jitsi-meet/builds/552447113#L1741
but failed later on nginx binding
https://travis-ci.org/juju4/ansible-role-jitsi-meet/builds/552447113#L3416
as references tasks' files have not changed since a while
https://github.com/juju4/ansible-role-jitsi-meet/commits/master/tasks
limited in https://github.com/juju4/ansible-role-jitsi-meet/commits/devel/tasks

interactive kitchen+lxd testing gives same result than travis. same with kitchen+docker
not sure if there is container condition or something else.

last good travis test
https://travis-ci.org/juju4/ansible-role-jitsi-meet/jobs/483279783#L2497
jitsi-meet 1.0.3383-1 
(current package jitsi-meet 1.0.3734-1)

don't see any obvious conflict from last 6months debian package changes
https://github.com/jitsi/jitsi-meet/commits/master/debian

**Comment by muxlux** [comment]
yeah, this is super annoying 
i can't uninstall jitsi-meet &, when i try, it breaks dpkg & i can't install or uninstall anything else afterwards
there should be a warning on the install guide that installing on debian may break your system's package manager

**Comment by atelierscym** [comment]
Hello, same problem here, unable to unsisntall properly jitsi-meet. Got following error message :
`E: prosody: installed prosody package post-installation script subprocess returned error exit status 1
`
It's probably not an easy problem to solve for developers, so my full support to them ;-)

**Comment by StephanEggermont** [comment]
Still a problem

**Comment by StephanEggermont** [comment]
High priority, as https://jitsi.org/downloads/ install instructions are broken, so everyone not following the quick install ends up with a broken install

**Comment by jkozak** [comment]
This is still an issue - given the predictable demand for videoconferencing right now it really should be fixed.

**Comment by damencho** [comment]
This is already fixed in latest packages

**Comment by StephanEggermont** [comment]
Where? I can’t find a commit fixing in the past quarter. 5 days ago I installed on Ubuntu 18.04 LTS using the website instructions. Entering through the manual install step breaks the install, and apt-get remove breaks apt.

**Comment by muxlux** [comment]
i think it's a serious issue. if jitsi-meet is installed on an existing
server, the only way that i know to cleanly uninstall is to re install the
whole server or a backup

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/commit/9344138303da182d28a0c2510a49f6bf396a99f6

**Comment by damencho** [comment]
Manual install is not updated and has a warning to not use it as it can break in many places.

**Comment by StephanEggermont** [comment]
But that is no manual install, just following the (broken) instructions on the website

**Comment by StephanEggermont** [comment]
Just talked an the prosody im: https://chat.prosody.im
It's recognised there as a packaging problem, has a fix that needs releasing. 
Please coordinate for a fast patch

08:29
Hi Prosody team. I'm looking at an issue installing and deinstalling Jitsi-Meet on Ubuntu 18.04 LTS. It depends on Prosody, and there seem to be some package management problems. https://github.com/jitsi/jitsi-meet/issues/1978. Is this something you are aware of/already have a solution for?
MattJ
08:49
Stephan Eggermont: hey! I wasn't aware of this jitsi issue, but we are aware of the prosody package issue that seems to be at the heart of it
MattJ
08:49
The fix is already done (for a while actually), we just need to make the release
MattJ
08:49
Which depending on the time I get, could be as early as today

**Comment by stml** [comment]
I am struggling with the instructions in Quick Install (https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) on Ubuntu 18.04

For a novice, the instruction on what to do in `/etc/hosts` and `/etc/hostname` are not clear - I will start another request about this.

However, I have not managed to set up Jitsi correctly, and am trying to uninstall with `apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2`

As above, prosody is not starting and thus can't be removed. How should I proceed?

**Comment by muxlux** [comment]
there may be a problem with prosody when it comes to uninstalling.
you may want to do apt-get purge twice but, if that doesn't work, you may
have to reinstall the whole OS
that's what i have to do when i want to reinstall

are you using a FQDN or are you testing on a local network?
