### ISSUE TITLE
"blinking" Chrome in jitsi-meet conference

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1979]
Hi,

Has anyone else had the experience that Chrome (on OSX and Ubuntu in my case) keeps blinking on and off (seems almost like a constant page refresh but it is not) when in a jitsi meet conference?

**Comment by bbaldino** [comment]
is this basically a flickering of the video?  with maybe another video flickering in the main window? (e.g. the self-view video).  if so we have seen this a bit, and have even seen it when doing other things like watching youtube.  have you seen it on any other sites?

**Comment by petervnv** [comment]
Yes, that's exactly what it is. It seems the video keeps flickering during a meet which is very annoying.
I've only noticed this behavior with jitsi-meet. Not with other sites

**Comment by bbaldino** [comment]
since we've seen it on other sites we think it's a chrome issue, but we haven't really had the time (or much data) to dig into it further.  how often are you seeing it?  can you reliably reproduce?

**Comment by virtuacoplenny** [comment]
Here is the chromium bug report that seems like the same issue: https://bugs.chromium.org/p/chromium/issues/detail?id=702369.

**Comment by petervnv** [comment]
@bbaldino yeah it is hard to reproduce consistently. It just seems to happen once in awhile (in my case always on Ubuntu although I've seen it also on Mac).
The chromium bug that @virtuacoplenny references seems to be spot on. This likely won't be fixed for jitsi-meet until that bug is fixed since the origin seems to be somewhere in Chrome.

**Comment by parveensachdeva** [comment]
Its still happening a lot..
