### ISSUE TITLE
adaptiveLastN is nit present in config.js | Jitsi Meet

### ISSUE THREAD

**Issue by nishachar** [jitsi/jitsi-meet#1980]
Hello all,

As per https://github.com/jitsi/jitsi-videobridge/blob/master/doc/adaptive-last-n.md, the variable 'adaptiveLastN' must be present in config.js, but its not in the latest master branch. I have a need to implement this variable and will be very thankful to any one who could guide me on how to properly set it up.

More Desc - My requirement is to stream a conference of around 40 people. To do it in most cost effective way, i need to enable this param. This problem is discussed in Attalasian's official dev blog - 
https://developer.atlassian.com/blog/2015/07/video-conferencing/

Thank you in advance.

**Comment by saghul** [comment]
This parameter no longer exists, it's on by default.

**Comment by nishachar** [comment]
Thanks for your quick reply Sagul !Just one more question, How can we control the number 'lastN' ?

**Comment by saghul** [comment]
With this configuration option: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L161

It's set to -1 by default, that is, adaptive / unlimited, dynamically adjusted based on your capabilities.

**Comment by nishachar** [comment]
Thanks Saghul for guiding me. I am testing it and will uodate on my final finding.

**Comment by nishachar** [comment]
Hi Saghul, i donw think this resolved the issue. Here is what we did - i changed "channelLastN" in my config.js and restarted everthing ( just to be sure ). channelLastN was set to 3. We connected 5 devices and all 5 were receiving video of everyone connected. 
Did we do something wrong ? Or this gets activated only when bandwidth is in crunch. Our server was relatively free at the time of testing. 
Are we missing something ?

**Comment by saghul** [comment]
Double check your configuration. I just tested it by overriding the config value to 3 in meet.jit.si and look:

![screen shot 2017-09-12 at 11 54 59](https://user-images.githubusercontent.com/317464/30319850-4753b5f0-97b1-11e7-8e3f-a164a26d448d.png)

It takes a couple of seconds, and then 2 of the participants get the "ninja" icon, indicating that their video was suspended.
