### ISSUE TITLE
http -> welcome to nginx   but   https -> can’t be reached

### ISSUE THREAD

**Issue by webstations** [jitsi/jitsi-meet#1981]
I installed jitsi meet by following the "manual install" guide.
I've had success until "Deploy Jitsi Meet" step
after the install process. I tried to open my server address at http://meeting.ptquantum.com and displayed the "wellcome to nginx" page.
at the "Install nginx" stage I notice that the port used is 443 (https)
but when I try to open the page https://meeting.ptquantum.com the page can not be opened (This site can not be reached)

ps:
the domain I use (ptquantum.com) is located on another server (shared hosting), and the subdomain meeting.ptquantum.com I use to install jitsi on another server (VPS)

OS : Debian 8 64bit
jitsi-videobridge-linux-x64-992
Nodejs V 6.11.3

edited:
i have installed certificate from https://certbot.eff.org/
but still, i can't open https://meeting.ptquantum.com

can anyone help me? because I'm still really beginner about linux

**Comment by saghul** [comment]
On that guide, on the nginx configuration part you'll see this:

```
server {
    listen 443;
    # tls configuration that is not covered in this guide
    # we recommend the use of https://certbot.eff.org/
```

You need to configure the SSL certificate to be used with your server. You can get a free one with letsencrypt, check that URL.

**Comment by webstations** [comment]
@saghul , thanks for your reply,
i have done it as i mentioned on my "edited" question, but it still not solve my case

**Comment by saghul** [comment]
@webstations have you updated your nginx configuration? What does it look like? Have you restarted nginx afterwards?

**Comment by webstations** [comment]
@saghul 
yes I've updated the configuration, as mentioned in the instalation's manual.
I have replaced all the words "jitsi.example.com" to "meeting.ptquantum.com"
I also have restarted nginx

**Comment by webstations** [comment]
@saghul 
or maybe you can check inside my vps, if only there is something wrong in my server configuration

**Comment by saghul** [comment]
Please paste your nginx configuration.

**Comment by saghul** [comment]
Please ask in our community: https://community.jitsi.org
