### ISSUE TITLE
android release compilation

### ISSUE THREAD

**Issue by artur** [jitsi/jitsi-meet#1982]
Hi guys,

I'm trying to generate the release apk but through android studio it gets corrupted and when I do the variant=release on react-native run-android I get this error:

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installRelease' not found in root project 'jitsi-meet'. Some candidates are: 'uninstallRelease'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

Does this happen to anyone ? Or am I doing something wrong ?

**Comment by saghul** [comment]
Hi there! If you want to build the release apk you need to run the `assembleRelease` task. There is no `installRelease` unless you configure the signing options: https://stackoverflow.com/questions/33897802/gradle-build-task-installrelease-missing-in-android-project

**Comment by petervnv** [comment]
Quick followup question.
Where's the proper place to change the packageID from org.jitsi.meet?

Is it in the Android Manifest file or here? https://github.com/jitsi/jitsi-meet/blob/master/android/app/build.gradle

Cheers

**Comment by artur** [comment]
Hi @saghul I tried that before but it created a corrupted release apk (couldn't install on a device) everytime I ran it, that's why I tried to see if there's another way.

Do you know how to debug this type of errors ?

**Comment by artur** [comment]
@saghul quick update. I can run on debug on the device, but using the apk created using ./gradlew assembleRelease

I did a package name change and it compiled all good, so my guess is that it's either generating the apk wrong or something it being linked to the old package name.

Have you ever encountered some error like this ?

Regards

**Comment by saghul** [comment]
I haven't sorry. I'm not sure if installing an unsigned release apk is even supported. You'll need to look into that.

**Comment by artur** [comment]
Thanks @saghul !
Although i'm a little bit confused, I generated the signed apk through android studio, it installed and when I start the app it crashes.

Is there another signing method that needs to be used ?

**Comment by saghul** [comment]
> I generated the signed apk through android studio,

That's one way to do it, I gather from a quick search.

> it installed and when I start the app it crashes.

Anything meaningful on `adb logcat` ?

**Comment by artur** [comment]
adb logcat gave this output

> 09-13 14:36:39.261 21438 21453 E         : Unable to load script from assets: index.android.bundle
09-13 14:36:39.262 21438 21477 E AndroidRuntime: FATAL EXCEPTION: mqt_js
09-13 14:36:39.262 21438 21477 E AndroidRuntime: Process: network.privus.bubble, PID: 21438
09-13 14:36:39.262 21438 21477 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:158)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:471)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(CatalystInstanceImpl.java:51)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:487)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: Caused by: com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	... 3 more
09-13 14:36:39.262 21438 21477 E AndroidRuntime: Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
09-13 14:36:39.262 21438 21477 E AndroidRuntime: 	... 7 more

**Comment by petervnv** [comment]
This sounds a lot like the problems I've been reporting on this list!

Can someone walk us through compiling a working release build of jitsi-meet.apk?

It seems this BatchedBridge error is happening to everyone so I doubt it's just a mistake on my end.

**Comment by artur** [comment]
@saghul I tried again from scratch without changing anything:

- git clone from this repo
- npm install && make
- open android studio in the ./android directory
- build signed apk in android studio
- uploaded the apk to phone and installed
- open jitsi and crashes

Now I know that the problem here is when I build the signed apk on android studio, I think this may be the cause, because when using debug I can only run jitsi when using the command "react-native run-android" otherwise the bridge error would appear.

So my guess here is how do I create a signed apk ? 
The gradlew doesn't have a installRelease task

Kind regards and thanks for all the help so far

**Comment by saghul** [comment]
I think somehow the bundling process is not working. The bundling process will create the JS bundle with the entire app's JavaScript code.

I myself don't know (yet) why this is happening.

**Comment by saghul** [comment]
@artur Have a look at this: https://facebook.github.io/react-native/docs/signed-apk-android.html You may need to make small adjustments since we deviated from the sample gradle files, but it shouldn't be too big of a change.

**Comment by khatanbaatar** [comment]
There is a problem with one camera device. the camera does not look.
![20170926_213617](https://user-images.githubusercontent.com/203731/30863196-6570b582-a30b-11e7-9a28-5404ff55a253.jpg)

**Comment by saghul** [comment]
I'm closing this since there is nothing actionable on our side. @artur please holler if you still have issues. @khatanbaatar please open a new issue instead of "hijacking" others.
