### ISSUE TITLE
Failed to load config from https://xxx.xxx.x.xxxx/config.js?room=re", {}

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#1983]
Hi       I have a problem      Ask for help!
    
I replace the project server address  https://meet.jit.si    To the local server address https://192.168.1.174  
<img width="1013" alt="wx20170913-171936 2x" src="https://user-images.githubusercontent.com/9635493/30369823-5181968a-98a8-11e7-9cda-7fc36094f3f7.png">

￼
I   Run the command:   
        react-native  run-android 

report a  question  :

console.error

: "Failed to load config from https://192.168.1.174/config.js?room=re", {}
<unknown>
    polyfills-browser.js:256:45
error
    YellowBox.js:62:16
<unknown>
    functions.js:79:20
tryCallOne
    core.js:37:14
<unknown>
    core.js:123:25
<unknown>
    JSTimers.js:100:50
callTimer
    JSTimersExecution.js:95:8
callImmediatesPass
    JSTimersExecution.js:199:36
callImmediates
    JSTimersExecution.js:214:11
<unknown>
    MessageQueue.js:220:16
guard
    MessageQueue.js:46:4
__callImmediates
    MessageQueue.js:220:10
<unknown>
    MessageQueue.js:109:6
guard
    MessageQueue.js:46:4
callFunctionReturnFlushedQueue
    MessageQueue.js:107:10

The browser use https://192.168.1.174 /test123  is ok
 but to use https://192.168.1.174 /test123 on  jitsi-meet projects to report a  errors  

thanks

**Comment by saghul** [comment]
Do you have a valid (non self-signed) cert there? Those are not supported in the mobile apps.

**Comment by yxwandroid** [comment]
I don't see what you mean        
I built a server ,address is   https://192.168.1.174
I want to connect to my server through the jitsi-meet project, so I changed the jitsi-meet project server address https://meet.jit.si to https://192.168.1.174

**Comment by saghul** [comment]
The change you did is OK, but it won't work unless you have valid TLS certificate.  On the desktop you can just continue despite of a warning, not so on mobile.

**Comment by yxwandroid** [comment]
Thank you very much            
 
I see what you mean,  and  If I have TLS certificate, can I add to the jitsi-meet project?
If yes, how do I add TLS certificates to the jitsi-meet project

**Comment by saghul** [comment]
No, you cannot add it to the project. We use the system provided facilities / trust store. You can get a free one with LetsEncrypt, those are trusted no problem.

**Comment by yxwandroid** [comment]
How I can get a free LetsEncrypt is believable.
Can you give me more details
@saghul 
thinks

**Comment by saghul** [comment]
I don't know what other details you need.  Have a look at their website: https://letsencrypt.org/ Alternatively, reinstall your server and choose to use LetsEncrypt during the installation, it's builtin.

**Comment by yxwandroid** [comment]
ok  thinks
