### ISSUE TITLE
Issue with jistsi meet/nginx

### ISSUE THREAD

**Issue by Jdierssen** [jitsi/jitsi-meet#1985]
At first my nginx worked perfectly but atm it doesnt work. it says: err_connection_refused on all browsers. And my Jitsi-Meet gives me an error with the conference focus. I`ve tried the original setup. if you guys need to know some more info just say so
![knipsel](https://user-images.githubusercontent.com/31985506/30476941-da1e34a8-9a0b-11e7-9ad7-61a9b98e2910.PNG)
{Translation from the screenshot: This site is not reachable, im.cns-it.local refused the connection.}
![1](https://user-images.githubusercontent.com/31985506/30477141-71ca0c96-9a0c-11e7-91b1-0f42cb3ad051.PNG)
{This is my config, im am new to all of this so im just learning}

**Comment by saghul** [comment]
Hi @Jdierssen, welcome! Can you ping that host? Can you check if nginx is running?

**Comment by Jdierssen** [comment]
@saghul Thanks for the quick reply. i can ping the host.

**Comment by saghul** [comment]
Is it listening on port 443? Any chance another application is listening on it too? (you can check with `netstat -tunapl`

**Comment by Jdierssen** [comment]
I still get this error message when i try to start the service
![2](https://user-images.githubusercontent.com/31985506/30531097-46a2c214-9c4c-11e7-9d2d-14ee8e745657.PNG)

**Comment by Jdierssen** [comment]
When im on the jitsimeet webpage i get this error
![3](https://user-images.githubusercontent.com/31985506/30539538-3ce6ac5a-9c73-11e7-951e-d9964dfe9d67.PNG)

**Comment by Jdierssen** [comment]
I reinstalled nginx and the server worked perfect
