### ISSUE TITLE
Jitsi meet error

### ISSUE THREAD

**Issue by Jdierssen** [jitsi/jitsi-meet#1992]
If i go to the jitsi meet site i get the following errors
![5](https://user-images.githubusercontent.com/31985506/30583148-751d5d54-9d26-11e7-9959-8d96361263ae.PNG)
Does anybody know the issue

**Comment by damencho** [comment]
Is im.cns-it.local the DNS you entered while installing jitsi-meet?
Your bosh setting inside meet seems wrong to me, by default it doesn't have any port and is the same as the address of your deployment (the DNS you enter during installation) with just http-bind at the end.
im.cns-it.local:5280 will try contacting directly prosody on a clear port, as I remember, but you are trying to access it using https. Even if you fix to access prosody using the secure port, prosody doesn't have the certificates that the web server has... 
So I think you have a problem with configuring your deployment, did you install it using the [quick-install guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md)?

**Comment by Jdierssen** [comment]
@damencho  i removed jitsi-meet completly and i`ve followed the quick-install-guide but after i dit that i get these error messages
![6](https://user-images.githubusercontent.com/31985506/30630228-eb37173c-9ddf-11e7-97e5-e3db4caf9004.PNG)

**Comment by Jdierssen** [comment]
After a few tutorials i got everything working, Thanks

**Comment by H7-25** [comment]
How did you fix this ?

**Comment by cantoute** [comment]
I seem to have a similar problem... anyone could give clues? thanks.
