### ISSUE TITLE
Video/Audio on meet.jit.si stopped working with Chromium

### ISSUE THREAD

**Issue by perburn** [jitsi/jitsi-meet#200]
Hi,

I don't know if this is the right place for reporting problems about meet.jit.si,
I was regulary using meet.jit.si sucessfully with Chromium (Debian unstable, now Version 38.0.2125.101).

Some weeks ago it stopped showing the remote video/audio.

Regardless of configuration or network (local, internet, etc). It shows the remote participant box, chatting etc. works but remote video/audio is not working. Own video is displayed.

Let me know if I can collect additional debug info.

**Comment by wngr** [comment]
I have the same problem with fedora 21.
Name        : chromium
Arch        : x86_64
Version     : 38.0.2125.101

**Comment by perburn** [comment]
Quick update: A workaround seems to be to start Chromium with "--no-sandbox"

**Comment by jmcclelland** [comment]
I have the same problem on Debian Jessie running Chromium 41.0.2272.76-2. Running chromium with the --no-sandbox flag fixes it for me.

**Comment by muellert** [comment]
Just tried on Jessie with 41.0.2272.76-2, and it does not fix it for me.

**Comment by jmcclelland** [comment]
Here is more information on what is probably the same bug in the debian bug tracker:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770659

**Comment by magicvince** [comment]
I'm using Chromium (41.0.2272.118 Built on 8.0, running on Debian 8.0 (64-bit) on LMDE2 - Mint Debian)

I've the same problem

In the jmcclelland's threads there's a temporary solution: 

`chromium --no-sandbox`

It's woking for me

**Comment by groceryheist** [comment]
I'm using Chromium (46.0.2490.71 Built on Debian stretch/sid, running on Debian stretch/sid (64-bit))
The work-around works for me. But I don't like it.
