### ISSUE TITLE
Internet Explorer 11 not work for latest jitsi meet

### ISSUE THREAD

**Issue by jeffvfren** [jitsi/jitsi-meet#2010]
I can't make Jitsi Meet run on internet explorer 11, please refer screenshot below.
I remember one month ago when I install the stable builds on Ubuntu, IE11 still able to support voice & video.

![explorer11](https://user-images.githubusercontent.com/11296467/30781134-62923b1c-a14c-11e7-8529-54f8ab1f935b.png)

SCRIPT438: Object doesn't support property or method 'assign'
AnalyticsAdapter.js (123,9)
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead. 
No stack trace of the deprecated usage is available in your current browser.
SCRIPT5009: 'JitsiMeetJS' is undefined
app.bundle.min.js (5859,1)

**Comment by rasos** [comment]
Don't you have to install the TEMASYS plugin on IE11 and Adapter.js on the server first? See https://confluence.temasys.com.sg/display/TWPP/How+to+integrate+the+Temasys+WebRTC+Plugin+into+your+website

**Comment by jeffvfren** [comment]
Hi rasos, I'm trying https://meet.jit.si, believe that the server is ready for test.
I have TEMASYS plugin installed. Just now I try many time reinstall & repair, until it gone :(

Are you able to access from your IE 11? If this is my personal issue, this issue should be closed now.

**Comment by jean-ben-guigui** [comment]
I am not able too, did you find a way around?

**Comment by daimoc** [comment]
It still did'nt work last commited version.
In fact the Object doesn't support property or method 'assign' Error is link to IE11 not supporting Object.assign Method.
It's possible to support it by importing 'core-js/fn/object/assign' in lib-jitsi-meet code before any use of Object.assign for exemple in JitsiMeetJS.js file.
After that UI is loading correctly and GetUserMedia works (You could get your media).
But there'are still some issues with peerconnection.addtrack and Jitsi-meet is still not functional with IE11. 
I got this error now :
Unable to get property 'i' of undefined or null reference in JingleSessionPC (857,30).

**Comment by chrisrobbo** [comment]
Is this something which someone is looking at ? It's pretty serious ... is there a usable workaround ?

**Comment by rasos** [comment]
@arminfelder is working on it. IE11 worked for us with the 2017-05-24 stable version at https://download.jitsi.org/stable/ but did not work with an earlier dev or the 2017-09-21 stable version. Latest stable 2017-11-20 not tested yet.

**Comment by daimoc** [comment]
@virtuacoplenny have already commit some fix for ie11 last weeks. And it seem to be  working well in https://meet.jit.si server. 
AnalyticsAdapter.js  error is fixed, audio and video transmission are working fine.

**Comment by chrisrobbo** [comment]
All seems to be working now, thanks !
