### ISSUE TITLE
Nginx fail

### ISSUE THREAD

**Issue by Jdierssen** [jitsi/jitsi-meet#2011]
I have installed nginx the correct way but i get the following error when i try to go to the web page. does anybody know this problem or how to solve it

![7](https://user-images.githubusercontent.com/31985506/30795674-f3f45464-a1ce-11e7-9d84-a5c3e5d8d9f3.PNG)
{This is my config }

![knipsel](https://user-images.githubusercontent.com/31985506/30795688-00880ff4-a1cf-11e7-9196-187308e7bd96.PNG)
{This is the error on the webpage. translation: The website refused connection}

**Comment by blackkara** [comment]
Just try `sudo su nginx -t` to see what's wrong

**Comment by Jdierssen** [comment]
@blackkara 
![8](https://user-images.githubusercontent.com/31985506/30901028-8d0bbb18-a366-11e7-9c97-15699f9217cf.PNG)
Everything is good
