### ISSUE TITLE
Using Jitsi Desktop with Jitsi meet

### ISSUE THREAD

**Issue by stoilkov** [jitsi/jitsi-meet#2014]
Hi all, first of all, thanks for the great job! Браво :) 
Is it possible to use a standalone app ( not a browser plugin ) for a private jitsi meet installation? Thanks in advance.

**Comment by Sam-Njine** [comment]
Hi stoilkov. I would also like to know how to use jitsi meet as a standalone app. Were you able to do this?

**Comment by damencho** [comment]
You can use https://github.com/jitsi/jitsi-meet-electron
