### ISSUE TITLE
Read-only (audio and video) users

### ISSUE THREAD

**Issue by magatz** [jitsi/jitsi-meet#202]
Hello I'm trying to understand the code...
I've modified the app.js code, to avoid the webcam detection, but injecting the xmpp user, according to the Openfire registered users. (IE: i've got a standard jitsi-meet client, as broadcaster, and a modified application acting a a read-only user)

As expected the owner of the conference, sees the presence of the read-only users, via the user roster , or chat, and doesn't see the user in the bottom user's strip , and can chat correctly.
After joining the room, the read-only user waits up to ten minutes (minimun 3 mins), before receiving the "owner" video stream.

Can you give me any hint, about the possibility to have a pure read-only user? Seems like i need to notify something to the video-bridge, so that the read-only users clients are getting a notification, without waiting up to 10 minutes

Thanks

**Comment by bgrozev** [comment]
This should be available now, see https://github.com/jitsi/jitsi-meet/issues/253
