### ISSUE TITLE
luajwtjitsi can't be installed in Debian Stretch : Authentification with Token impossible

### ISSUE THREAD

**Issue by inkhey** [jitsi/jitsi-meet#2029]
Jitsi meet token debian package from repos doesn't work on debian Stretch.

Prosody failed to authenticate with token due to missing dependencies.
I do some research and i add  `basexx` package : https://github.com/jitsi/jitsi-meet/issues/1870.
Then i tried and find that i need also  `luajwtjitsi` , as notified [here](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-tokens.postinst) .
This package just refused to be installed because a dependency is broken : `luacrypto`.
It's look like debian Stretch use openSSL 1.1 and luacrypto package from luarock doesn't support it.
[This fork](https://github.com/evanlabs/luacrypto) of luacrypto seems to be compatible with openSSL 1.1 but i just don't know how to compile it correctly in a way that luarock can see it as installed.

**Comment by inkhey** [comment]
It's working now in my test env 👍
Not really straightforward. You always have to check prosody logs in` /var/log/prosody ` to understand what's wrong .
You have to download [lthis fork of luacrypto](https://github.com/evanlabs/luacrypto) .
Then you have to compile it correctly with luarocks .
`luarocks make`

(you maybe need to fix configure.ac in order to set the correct lua version, look at 
binarym comment [here](https://stackoverflow.com/questions/5350086/no-package-lua-found-but-i-have-it-installed) , it's required for normal build but maybe not for luarocks build , i tried normal build first so i didn't know if it's important ).

then you can install ` luajwtjitsi`

`luarocks install  luajwtjitsi`

In my own installation luacrypto file, `crypto.so`, isn't placed correctly for prosody, so i've created a symlink
`ln -s /usr/local/lib/lua/crypto.so /usr/local/lib/lua/5.1/crypto.so`

Normally you now just have to relaunch prosody service and tokens are working if your prosody config is correct.

for me, on my test env, i got `https://prosody/` as server.

`
https://prosody/test?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcm9zb2R5IiwiaXNzIjoidGVzdCIsInJvb20iOiJ0ZXN0IiwiYXVkIjoiKiIsImp0aSI6IjlmZDRiYWUyLWE4Y2QtNGRmNS04NDk5LTMzYjYzYTNjNjE3YyIsImlhdCI6MTUwNzEwNjgzNywiZXhwIjoxNTA3MTEwNDM3fQ.g4LLFJjAigPYc1vvCaLdkTvLaYheStq9VtW9slBIbQs
`

as correcty url with :

```
{
 "sub": "prosody",
 "iss": "test",
 "room": "test",
 "aud": "*"
}
```
as JWT payload.

`secret` as secret .

So, you can workaround this bug.

**Comment by yoosefi12** [comment]
Thanks, i ran into the same problem and your solution worked for me.

**Comment by Bogdaneshtu** [comment]
Thank you! I've faced this issue too and completely resolve it due to your instructions!
