### ISSUE TITLE
Audio problems

### ISSUE THREAD

**Issue by Slawutich** [jitsi/jitsi-meet#203]
we have audio issues (intermittent audio) when a user is connected via Jigasi on all webrtc browser clients. Browsers hears the problem, SIP clients hear everything correctly.

**Comment by gpolitis** [comment]
In the "simple" case where only browsers speak with each other, do you have any audio issues? Where are the various components located? Do you run jvb/jicofo/jigasi on a lan or in the cloud?

**Comment by bgrozev** [comment]
This is probably due to the opus FEC issue in chrome M39 which we worked around by disabling FEC in jigasi (https://github.com/jitsi/jigasi/commit/33cb1c75d2776e8c84f3adef8b0139e061522f73).

**Comment by Slawutich** [comment]
Yes! The problem was resolved with disabling FEC in jigasi

**Comment by bgrozev** [comment]
This works with current chrome versions (>=40 IIRC), so we should enable it again. Opened https://github.com/jitsi/jigasi/issues/11
