### ISSUE TITLE
No mic audio via bluetooth headset

### ISSUE THREAD

**Issue by jinnko** [jitsi/jitsi-meet#2034]
Steps to reproduce:

1. Establish link between handset and bluetooth headset
2. Launch Jitsi Meet & join a room with other users
3. Headset seems to go into listen mode, but no audio is sent to other users.
3. Disable bluetooth on the handset and audio is sent to other users normally.

I've confirmed the behavoiur several times.  The headset works with other apps such as Signal and Google Duo.

**Comment by vincent-ledu** [comment]
Hello, 
I have the same issue.
only my usb camera is detected, not my bluetooth headset.
