### ISSUE TITLE
accessing jitsi meet

### ISSUE THREAD

**Issue by pzaver** [jitsi/jitsi-meet#2046]
I have done the setup in ubuntu using quick install and when I given localhost its showing me default nginx page. But when I try to access using domain jitsi-meet.example.com/http-bind its giving me can’t find the server at jitsi-meet.example.com
and
 When I try to access localhost:5280/http-bind, its giving me unknown host error 

How can I verify its working properly

**Comment by saghul** [comment]
Hi!

You need to configure a valid domain. example.com needs to be replaced by a domain you own. If you don't have any you can use localhost or your local IP address.

**Comment by pzaver** [comment]
I have done the setup using quick installation so there is a separate config file for the domain jitsi-meet.example.com and thats included in the prosody main config.

Is there any other setting to be done because there are no details in installation guide.

**Comment by priyakh** [comment]
i have installed jitsi-meet on i am not able to accessing it from public ip . How can i make it work.
