### ISSUE TITLE
set own avatar

### ISSUE THREAD

**Issue by borune-k12** [jitsi/jitsi-meet#2060]
i want to set user avatar as described [there](https://github.com/jitsi/jitsi-meet/issues/935) doing it as folows:
`view = new JitsiMeetView(this);`
`Bundle config = new Bundle();`
      `config.putBoolean("startWithAudioMuted", false);`
        `config.putBoolean("startWithVideoMuted", true);`
        `config.putString("RANDOM_AVATAR_URL_PREFIX","https://i.imgur.com/FN3kSip.jpg");`
        `Bundle urlObject = new Bundle();`
        `urlObject.putBundle("config", config);`
        `urlObject.putString("url", "https://meet.jit.si/Test123");`
        `view.loadURLObject(urlObject);`

but it doen't work

**Comment by lyubomir** [comment]
Thank you for reaching out to us!

* Generally, `RANDOM_AVATAR_URL_PREFIX` is an `interfaceConfig` property, not a `config` property.
* We do not support `interfaceConfig` on mobile yet.

In other words, even if we respected `RANDOM_AVATAR_URL_PREFIX ` on mobile, you'd need something like the following:
````java
Bundle interfaceConfig = new Bundle();
interfaceConfig.putString("RANDOM_AVATAR_URL_PREFIX","https://i.imgur.com/FN3kSip.jpg");
urlObject.putBundle("interfaceConfig", interfaceConfig);
````

How severe to you is the lack of the support on mobile for the feature in question?

**Comment by borune-k12** [comment]
@lyubomir thank you for quick reply.

This feature is desirable but is not mandatory.  And since you don't support this interface on mobile is there any way to hide avatars at all?

**Comment by lyubomir** [comment]
Unfortunately, the only way at the time of this writing is to modifiy the JavaScript source code to your liking. (Of course, doing that opens the can of worms that you're basically creating a fork of the project, you have to build the Jitsi Meet SDK for Android binary yourself, etc.)

**Comment by borune-k12** [comment]
@lyubomir okay. and are you planning to enable this feature and if yes when it will comes approximately?

**Comment by lyubomir** [comment]
We'll definitely support `interfaceConfig` specified by `loadURLObject` and/or in the deployment's `interface_config.js` file. I don't have an ETA at the time of this writing. (I asked you about severity because I'm trying to prioritize based on how desirable features are.)

**Comment by borune-k12** [comment]
But if there are currently no tools for even hiding avatars then severity of implementing this feature grows up.

**Comment by jsimoes** [comment]
Depending on whether you are extending your app with Swift/Objective-C or React. I had the same issues with a few of the options and using react (javascript) on the interface / view I was able hide a few icons. I believe one could do the same with the avatars, right? That would not impact features or require a fork, just a tweak on your end.

**Comment by borune-k12** [comment]
Yep, but this tweak should be done before compiling sdk as i understand. And obviously it is not so convinient then having interfaceConfig support "from the box".

**Comment by BaherHosni** [comment]
Hi @lyubomir 

Any news about supporting interface config for mobile?

Thanks in advance, 
Baher

**Comment by saghul** [comment]
No news, we are not working on this at the moment.

**Comment by gh4tg** [comment]
@rugk
Thank you very much for this, it is working as desired! You just can not use a local "file://"-ressource for the image, but you have to upload it to any webserver.

**Comment by Manjunath-VM** [comment]
How to set an profile image from base64 String can any one help me on this working with flutter plugin
https://pub.dev/packages/jitsi_meet

**Comment by rugk** [comment]
Actually there is also this quite convenient Jitsi hack to set an avatar as your liking: https://jitsi-hacks.cketti.eu/hacks/change_avatar/

**Comment by xariusdrake** [comment]
> Actually there is also this quite convenient Jitsi hack to set an avatar as your liking: https://jitsi-hacks.cketti.eu/hacks/change_avatar/

That's cool. How I can change the display name?
