### ISSUE TITLE
Microphone echo (Debian, Firefox)

### ISSUE THREAD

**Issue by worldmind** [jitsi/jitsi-meet#2069]
I test https://meet.jit.si/ in Firefox 52.4.0 and Firefox 57 Beta (Debian GNU/Linux 9.2 Stretch), I did not install any plugins/addons for browser and did not change sound system preferences.
I got sound echo, look like AEC does not working. In Skype I have no any echo.
After some searching I found http://forums.debian.net/viewtopic.php?t=128306
Run command: `pactl load-module module-echo-cancel aec_method=webrtc` and echo canceled (but some small noise exists).
It is very strange that is does not work by default, may be somebody understand why?

**Comment by gagarine** [comment]
This issue is still their on Ubuntu/Firefox. Their is **a lot** of echo if you don't use headphone.
