### ISSUE TITLE
Screen sharing not working in Opera (Chromium core)

### ISSUE THREAD

**Issue by nidelius** [jitsi/jitsi-meet#2070]
The screen share function is not available, I guess it's been disabled in the gui because the browser tag is not supported. BUT it's easy and possible to install the jitsi chrome plugin also in opera.
https://addons.opera.com/sv/extensions/details/download-chrome-extension-9/?display=en

This is how it looks in opera.

![image](https://user-images.githubusercontent.com/142629/31578839-c0686468-b129-11e7-9c6a-02b3e8f77fa3.png)

![image](https://user-images.githubusercontent.com/142629/31578850-e495fa76-b129-11e7-94d5-c0b413b9fad0.png)

**Comment by damencho** [comment]
Hum, I didn't know about this "Download Chrome Extension" extension, thanks. I had submitted jitsi-meet extension in opera webstore and it was waiting for approval for 5 months now, with no sign of activity. For the part that this is not available in jitsi-meet, I had working changes, that are not submitted, I will test them and submit a PR.

**Comment by damencho** [comment]
An initial version is pushed:
https://github.com/jitsi/lib-jitsi-meet/commit/f742218e4ab2690a74fc1e72e4e2fd4552b4eca4
Will be available on meet.jit.si on next deployment.
When trying to share screen a popup will be opened to install the extension and when done everything should work.
