### ISSUE TITLE
 "null is not an object (evaluating '_libJitsiMeet.analytics.sendEvent')"

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#2072]
I update the latest master code    

Come across this question

The following
![img_0135](https://user-images.githubusercontent.com/9635493/31642266-b1b02730-b2af-11e7-81a2-a1193700230b.PNG)

It happens on ios and android

jitsi-meet[960:612471] Exception '-[NSNull integerValue]: unrecognized selector sent to instance 0x1b3a7e580' was thrown while invoking updateExceptionMessage on target ExceptionsManager with params (
    "null is not an object (evaluating '_libJitsiMeet.analytics.sendEvent')",

How to solve it

The code that I should pull to that branch is fairly stable

**Comment by lyubomir** [comment]
I suppose you've `git pull`ed the latest master of jitsi-meet but you haven't run `npm update` so lib-jitsi-meet is not as recent as jitsi-meet. (Alternatively, you may delete the whole `node_modules` of jitsi-meet and issue `nom install`.)

**Comment by yxwandroid** [comment]
@lyubomir     
I  haven't run npm update   but      Have a problem
![error2](https://user-images.githubusercontent.com/9635493/31698733-98e9c514-b384-11e7-9b70-8e59d93272ac.png)

**Comment by yxwandroid** [comment]
my  node  verson is  v6.11.3  
my npm verson is 5.4.2


My step is
1 ，delete  delete the whole node_modules 
2， npm install 
    
I have the following problems
<img width="793" alt="1018" src="https://user-images.githubusercontent.com/9635493/31753445-32c840d0-b456-11e7-80cc-7ce94f02a3be.png">

 log  
[2017-10-19T03_34_51_721Z-debug.log](https://github.com/jitsi/jitsi-meet/files/1397048/2017-10-19T03_34_51_721Z-debug.log)

I don't know how to deal with it
continue step 3。

3，npm update   
  I have the following problems
<img width="800" alt="10181" src="https://user-images.githubusercontent.com/9635493/31753534-d500cf66-b456-11e7-8672-ba6c1a4060a6.png">

 log  
[2017-10-19T03_50_27_935Z-debug.log](https://github.com/jitsi/jitsi-meet/files/1397056/2017-10-19T03_50_27_935Z-debug.log)

I don't know how to deal with it

continue step 4。
4. react-native  run-ios
  I have the following problems


<img width="350" alt="1111" src="https://user-images.githubusercontent.com/9635493/31754892-461b6b4e-b460-11e7-87e1-83ef62c25c0f.png">








thanks  

@saghul 
@lyubomir 

I got a problem   because  use Taobao  source  Rather than The official source
solutions   The following
<img width="685" alt="10182" src="https://user-images.githubusercontent.com/9635493/31754825-f085f046-b45f-11e7-8fa6-1f3a0479ec15.png">

**Comment by saghul** [comment]
Well, we only support the official npm repo, if you are using a different one we cannot support that, sorry. If you run into other problems please make sure you are using the official repo.

**Comment by lyubomir** [comment]
@yxwandroid, my general advice in a case in which nothing seems to work is to rinse and repeat/start from scratch on a different computer with a different operating system. For example, the message "???? Thanks for using Babel" is strange. Maybe you could try changing your system-wide locale/encoding and that's going to make all the difference? You may also want to try with the latest stable of node which is v6.11.4 and the latest nom which is v5.5.1? I've seen people switch from Linux to macOS and have all their build and/or runtime woos go away.
