### ISSUE TITLE
Distinct xmpp private message from muc message .

### ISSUE THREAD

**Issue by inkhey** [jitsi/jitsi-meet#2073]
Xmpp support private message directly to user of the same MUC chatroom:
https://xmpp.org/extensions/xep-0045.html#privatemessage

This issue isn't about supporting this feature (see https://github.com/jitsi/jitsi-meet/issues/2073), but finding a correct way to handle now thoses messages almost correctly. Those message should not anymore be display like standard MUC message . 

I see 2 simple way to handle this :
- Add something referring to the fact this message are private and not visible to others participants.
- ignore thoses privates messages.

**Comment by saghul** [comment]
Closing since https://github.com/jitsi/lib-jitsi-meet/pull/616 landed, cheers!
