### ISSUE TITLE
npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#2082]
I run npm update   At the command line
There is an error

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the lib-jitsi-meet@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2017-10-18T02_06_42_448Z-debug.log

What should I do , I need  help

**Comment by lyubomir** [comment]
@yxwandroid, please thoroughly follow the READMEs in jitsi-meet/, jitsi-meet/android, etc. As I told you in another issue that you opened, the problem is that you're not performing required steps.

**Comment by kangzhe0000** [comment]
I also have this problem for building ios app, and I did the required steps:
1.brew install node     brew install watchman  npm install -g react-native-cli
2.npm install webpack -g
3. cd ios     npm install 
 then it had the problem:lib-jitsi-meet@0.0.0 postinstall: webpack -p
