### ISSUE TITLE
npm ERR! Unexpected token n in JSON

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#2083]
I'm running in the jitsi-meet root directory 
 npm install 

How do you handle the following error

npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! Unexpected token n in JSON at position 13558 while parsing near '...908a","size":13657,"noattachme'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yangxuewu/.npm/_logs/2017-10-18T02_36_59_846Z-debug.log
![error](https://user-images.githubusercontent.com/9635493/31698536-9f93b6be-b383-11e7-872f-1cfec2510b1a.png)

**Comment by saghul** [comment]
What Node and npm versions are you using?

**Comment by lyubomir** [comment]
@yxwandroid, please thoroughly follow the READMEs in jitsi-meet/, jitsi-meet/android, etc. As I told you in another issue that you opened, the problem is that you're missing steps.
