### ISSUE TITLE
Unable to resolve module lib-jitsi-meet/lib-jitsi-meet.min

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#2084]
![deerr](https://user-images.githubusercontent.com/9635493/31703836-0a01b42c-b3a4-11e7-9243-487ac1b1bd29.jpg)

I can't run successfully according to the above operation

**Comment by saghul** [comment]
Did you install all dependencies and tried the suggested fix in the error?

**Comment by lyubomir** [comment]
@yxwandroid, please thoroughly follow the READMEs in jitsi-meet/, jitsi-meet/android, etc. As I told you in another issue that you opened, the problem is that you're missing steps.
