### ISSUE TITLE
Video mute (toggleVideo) doesn't work on an empty room

### ISSUE THREAD

**Issue by Zalmoxisus** [jitsi/jitsi-meet#209]
This issue appeared after merging branch 'ssfocus'.
When there's no other participants in the room, getConferenceHandler() returns null, as we can see here https://github.com/jitsi/jitsi-meet/commit/4776605dec7effe18ac0acf8ab80b06eb678859f#diff-0364f57fbff2fabbe941ed20c328ef1aR1025 (before this commit it returned focus object), and toggleVideo stops here - https://github.com/jitsi/jitsi-meet/blob/master/app.js#L1043

**Comment by guilhem** [comment]
:+1:

**Comment by Zalmoxisus** [comment]
Fexed in https://github.com/jitsi/jitsi-meet/commit/44e558e5a0415bf1ff2802dd91f0e6ea6fee06eb
