### ISSUE TITLE
Putting room "on hold" and switсhing to another call

### ISSUE THREAD

**Issue by InternalVoice** [jitsi/jitsi-meet#2092]
Hello guys! Do we have possibility to switсh jitsi between different calls (room names) putting ones kinda "on hold"? Currently I'm just reinitialize jitsi module, but it takes pretty long time so it's not very suitable for a general user. Thanx for your replies!

**Comment by subodh-au** [comment]
Hello. Did you find some solution for it? I am looking for a similar thing.

**Comment by karansharma27** [comment]
Hello, did you find some solution for it? I am looking for a similar thing. Please help me here

**Comment by deva-gopalani** [comment]
@karansharma27 @InternalVoice Did you find any sort of solution for this? If yes, then do let me know. I just want to put the jitsi call on hold...
