### ISSUE TITLE
Many android phone device connections is lost

### ISSUE THREAD

**Issue by mr-kin** [jitsi/jitsi-meet#2101]
Many android phone device connections will be lost, the chance of recovery is too low, what can be solved? What does this have to do with anything?
1. Is it related to server configuration?
2. Mobile phone performance?
3. Can you make a configurable thumbnail video not show video that only shows the image click to switch to main video and then connect again?

**Comment by saghul** [comment]
Currently, when the connection is lost with the server we don't reconnect. This is a known issue which we plan on fixing in the future.

**Comment by mr-kin** [comment]
Oh, I see.
If want to try fixed it by my self , can you please tell me which part of the source code I should take a look.
By the way, If there any chance to reduce the live video frame rate and turn off the thumbnail video stream ?

**Comment by saghul** [comment]
> If want to try fixed it by my self , can you please tell me which part of the source code I should take a look.

TBH I don't know right off the bat.

> By the way, If there any chance to reduce the live video frame rate and turn off the thumbnail video stream ?

Not at the moment. The bridge will adapt to the perceived bandwidth, and you can use the "eye" icon to switch into audio only mode, which will completely disable video.

**Comment by mr-kin** [comment]
You misunderstood. I just want to get rid of the preview of the video stream so that I can reduce the amount of data. Then click on the head below to start connecting to user video.

**Comment by mr-kin** [comment]
sorry，my English is poor。
I can only translate by translating software。
Chinese description：
奥，对不起可能是我没有描述把问题描述清楚。现在3个android 手机同事视频就会出现主视图黑屏或者只显示头像的情况。缩略视频绝大多数也一样。我已经试过用更快的带宽和更好性能的手机效果会好一些，但是视频有时还是会出问题。服务器有性能要求么？什么样的配置合适？我想把运行的图片发给你但是不能上传。
English：
Oh, I'm sorry maybe I didn't describe the problem clearly. Now, three android phone colleagues, video, will appear with a black screen or a profile. The vast majority of video is the same. I've tried to do better with faster bandwidth and better performance, but video sometimes has problems. Does the server have performance requirements? What kind of configuration is appropriate?

**Comment by mr-kin** [comment]
Oh, I'm sorry maybe I didn't describe the problem clearly. Now three or more android devices and video will appear in the main view black screen or only the picture of the avatar. The vast majority of video is the same. I've tried to do better with faster bandwidth and better performance, but video sometimes has problems. Does the server have performance requirements? What kind of configuration is appropriate? I want to send you the running pictures but can't upload.
