### ISSUE TITLE
Jitsi meet gray screen

### ISSUE THREAD

**Issue by Jdierssen** [jitsi/jitsi-meet#2102]
I just installed my jitsi meet and i only get a gray screen. i have seen other issue`s like this but i cant get it to work. i get thes html errors. if you want to see some configs just let me know. sorry for the bad english. 
![knipsel](https://user-images.githubusercontent.com/31985506/31987860-6dc19ada-b96d-11e7-8e80-db7102220147.PNG)

**Comment by saghul** [comment]
can you please paste the contents of your interface_config.js file?

**Comment by Jdierssen** [comment]
![1](https://user-images.githubusercontent.com/31985506/31989024-4b717eec-b971-11e7-9b87-8e494544a3e4.PNG)
![2](https://user-images.githubusercontent.com/31985506/31989025-4b890c4c-b971-11e7-8793-499b4f06f5cd.PNG)
![3](https://user-images.githubusercontent.com/31985506/31989026-4ba0dfc0-b971-11e7-9786-338b5d72583e.PNG)

**Comment by rototom** [comment]
same here

**Comment by saghul** [comment]
Is the file getting served properly by your web server? It should work like this: https://meet.jit.si/interface_config.js

**Comment by filipposfilippides** [comment]
same here
do we have a solution to it?
