### ISSUE TITLE
Send invitation mail

### ISSUE THREAD

**Issue by zemzema** [jitsi/jitsi-meet#2103]
It would be great if you put an option to send link with room via mail direct from jitsi-meet server.

**Comment by damencho** [comment]
If you are talking about the web part, we used to have this feature, but it was removed.
We consider it more convenient just copying the text in the clipboard, so one can paste it in their mail, or chat client or any communication tool they have.

**Comment by rasos** [comment]
We are also missing the E-Mail feature. We have several users to which the "Share" dialog with the "Copy" button and the link is not intuitive. 

But offering to send E-Mails is also an open door for spammers. Hence I would suggest to add an E-Mail icon in the share dialog, which contains a mailto with a predefined subject and body.

**Comment by Mogoro321** [comment]
Hello, we use authorization by ldap, I would like to implement sending a link to the conference via mail. You say that you removed this function, please tell me how can I return it? Can there be additional demons or scripts with plugins? Thank.

**Comment by Mogoro321** [comment]
> 
> 
> If you are talking about the web part, we used to have this feature, but it was removed.
> We consider it more convenient just copying the text in the clipboard, so one can paste it in their mail, or chat client or any communication tool they have.

Hello, we use authorization by ldap, I would like to implement sending a link to the conference via mail. You say that you removed this function, please tell me how can I return it? Can there be additional demons or scripts with plugins? Thank.

**Comment by miradam** [comment]
Agree with @Mogoro321 
Lack of easy "Send invite" and sparse LDAP authentication howto is preventing Jitsi from being used in the corporate world.
BTW, lack of authentication/authorization is an open door to resource exhaustion / denial of service type attacks and this is preventing Jitsi from being adopted at the premises.
Any plans to restore that or shall the community search through git log?
