### ISSUE TITLE
Moderator Rights - Transfer, Grant, etc?

### ISSUE THREAD

**Issue by daytonturner** [jitsi/jitsi-meet#2106]
Hi everyone!

Question:  In my current installation (Quick Install) the behavior is that the first person to join a room is given moderator rights.  Is there a mechanism in place right now that would allow that moderator to transfer (or grant, so there's more than one) moderator rights to another user?  Alternatively, is there a way to have a room where everyone is a moderator?  Perhaps even a "dont allow guests to start until the moderator has arrived" option?

Just looking for a way to guide users through the sometimes frustrating issue of their guest joining the conference room before they do.

Thanks in advance :)

**Comment by damencho** [comment]
There is no option currently to grant moderator to a particular participant or transfer it.

You can enable [mod_muc_allowners](https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_allowners.lua) prosody module.

Or you can setup your deployment as described here, https://github.com/jitsi/jicofo#secure-domain the guests will need to wait till an authenticated user joins the room, and that user will be a moderator. Authenticated users must be created in prosody and they will need to authenticate with username and password.
