### ISSUE TITLE
Using JITSI with my IP address

### ISSUE THREAD

**Issue by erelsgl** [jitsi/jitsi-meet#2112]
I have just installed JITSI on my Ubuntu 16.05 using this guide: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

I was asked to enter the hostname, so I looked for the IP of my machine in [WhatIsMyIpAddress.com](http://whatismyipaddress.com/) and found that it was "2a02:ed0:5373:5000:4c3c:8bac:9a95:9fa2".

I entered this address into the prompt and continued the installation. Then, I tried to open this address: http://2a02:ed0:5373:5000:4c3c:8bac:9a95:9fa2/ in a browser, but it did not open.

Is it possible to use IPv6 addresses?

If not, how can I change the hostname of JITSI and what value should I put there?

**Comment by damencho** [comment]
It should be possible to use ip address, not sure about ipv6 though(as it contains : ). The hostname you enter normally has a DNS entry, like meet.jit.si.
Opening http will not work as jitsi-meet uses webrtc application and  webrtc cannot open microphone or camera when using http protocol.

The easiest way to change the hostname is purge everything from the system and install it again. There are too many configurations you need to change...
To remove everything including the configs you can use:
# apt-get remove --purge jitsi-meet jitsi-meet-prosody jitsi-meet-web-config jitsi-meet-web jicofo jitsi-videobridge

**Comment by erelsgl** [comment]
I try to remove and get the following error message:

(Reading database ... 311316 files and directories currently installed.)
Removing jitsi-meet-web-config (1.0.2301-1) ...
apache2.service is not active, cannot reload.
invoke-rc.d: initscript apache2, action "reload" failed.
dpkg: error processing package jitsi-meet-web-config (--remove):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 jitsi-meet-web-config
E: Sub-process /usr/bin/dpkg returned an error code (1)


*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by saghul** [comment]
Does it work if you try again? (same command)

**Comment by erelsgl** [comment]
No, I tried several times

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by damencho** [comment]
Can you try invoke-rc.d apache2 reload? Apparently, this gives an error, try fixing that and then retry.

**Comment by erelsgl** [comment]
I do not have apache2 installed - I have lampp

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by damencho** [comment]
I'm not familiar with lamp, but I suppose it has an apache dependency as dpkg is finding it.
Did you try the command?

**Comment by erelsgl** [comment]
Yes, it says:

apache2.service is not active, cannot reload.
invoke-rc.d: initscript apache2, action "reload" failed.

LAMPP is a package that contains Apache, MySQL and PHP with all their
inter-dependencies.  I usually start it with:
     sudo /opt/lampp/lampp start
It automatically starts all three services.


*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by damencho** [comment]
Yep, you need to check apache logs what is the problem and fix that. And the the jitsi-meet-web-config scripts will work.

**Comment by erelsgl** [comment]
I think the problem is simple: jitsi tries to invoke the apache2 service,
while in my computer the service is not called apache2 - it is called
lampp. Here is an explanation about the system:
https://www.apachefriends.org/index.html

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by damencho** [comment]
I see. So the script assumes that if there is a debian package installed named apache2 there is a standard init script for it. If lampp is modifying this behavior in some way, we do not support it at the moment. If you want to add lampp detection in the script (https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst) feel free to submit a PR I will be happy to review it.

**Comment by erelsgl** [comment]
OK, thanks!

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by erelsgl** [comment]
Here is a simple solution that allowed me to cleanly remove jitsi:

     https://askubuntu.com/a/982519/42073

I am not sure where  to change it in the code.

**Comment by damencho** [comment]
Modifying this in upstream will break all new installations that use apache2, so this is not acceptable. 
This should be solved by checking why apache2 cannot be reloaded. 
How it is possible that this check is true:
        APACHE_INSTALL_CHECK="$(dpkg-query -f '${Status}' -W 'apache2' 2>/dev/null | awk '{print $3}' || true)"

And there is no service apache2 on the system, it seems to me you have installed a broken apache2.
Can you run $ dpkg-query -f '${Status}' -W 'apache2' 
What is the output of it?
What is the output of the command: $ invoke-rc.d apache2 reload?

**Comment by erelsgl** [comment]
​The first output is: deinstall ok config-files

The second output is:
apache2.service is not active, cannot reload.
invoke-rc.d: initscript apache2, action "reload" failed.
​
