### ISSUE TITLE
Best cloud services to host Jitsi

### ISSUE THREAD

**Issue by Pitufo72** [jitsi/jitsi-meet#2116]
Hi there,

we have set up jitsi meet private instance in a OVH VPS Cloud with the following features:

OpenStack KVM
SLA 99.99%
2 vCore(s)
3.1 GHz
4 GB RAM
50 GB
High Availability (Ceph)

However, we see some quality issues and would like to know if anyone has any recommendations on how to improve the service quality or what other cloud provider can be better suited for Jitsi.

Any help/recommendations would be appreciated.

Thanks

**Comment by damencho** [comment]
How are you installing, using the debian packages? Cause there are some sysctl config values that are added when installing jvb, and if you skip those you can have some linux kernel buffers filled, which can cause issues.
Sometimes the quality issues can be coming from the client connections.
Have you tested meet.jit.si, do you see such issues there? The meet.jit.si deployment is using aws.

**Comment by Pitufo72** [comment]
Thanks for your response. To be honest our jitsi was installed by someone else and I don't have the technical details. 
We compared with meet.jitsi.si and the quality seems to be worse with the same computer, internet connection, etc. We suspect it may have something to do with our cloud service provider or the specifications of the VPS that is hosting our jitsi instance. Do you know what are the specifications of the aws instance that is hosting meet.jitsi.si ?

**Comment by bertho-zero** [comment]
Jitsi can be deployed in 1 click on any provider using Jelastic, for example on infomaniak.com.

https://github.com/jelastic-jps/jitsi
