### ISSUE TITLE
Focus error, retry after...

### ISSUE THREAD

**Issue by buubui** [jitsi/jitsi-meet#212]
I followed the instruction to install jitsi-meet (https://github.com/jitsi/jitsi-meet/blob/master/INSTALL.md) for server "cooler.pullerits.com". But it didn't work.
The errror bubbles show:

```
Conference focus
focus.cooler.pullerits.com is not available, retry in...
```

Error log in chrome console:

```
Focus jid set to: undefined
Focus error, retry after ...
<iq xmlns="jabber:client" type="error" to="e6870a26-cafc-4e7f-8cea-aea4976cba98@cooler.pullerits.com/5e60119c-4906-4533-b4ce-fef9cf7da201" from="focus.cooler.pullerits.com" id="1:sendIQ"><error type="cancel"><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Communication with remote domains is not enabled</text></error></iq>
```

Can anyone help me to figure out what's problem in here? Thanks.

**Comment by RavinduRoshan** [comment]
I had the same issue. I fixed it by running jicofo again with my secrets. 
go to `jicofo/target/jicofo-{os-name}-1.0-SNAPSHOT`
and run 
`./jicofo.sh --host=localhost --domain=jitsi.example.com --secret=YOURSECRET2 --user_domain=auth.jitsi.example.com --user_name=focus --user_password=YOURSECRET3`

**Comment by bamania8** [comment]
Please check if jicofo service is running or not.
