### ISSUE TITLE
microphone is not working with firefox 56.0.{1,2}

### ISSUE THREAD

**Issue by castilma** [jitsi/jitsi-meet#2124]
EDIT: its actually the stable version, not nightly. the problem persists with 56.0.2

when i try to use meet.jit.si with firefox  56.0.1, i get two error notes. one is because it cant access the cam(i don't have one) an the other is:

> Cannot use microphone for a unknown reason.

Besides the missing >n< after >a<, this is strange, since I allowed the page to use my microphone.
In the popup firefox gave me, I can choose between 'default: default' and 'default'. it does not matter which one i choose. 

i am on nixos 17.9.
it works with chromium.

i don't know how i can possibly get some debug output for you. please tell me.

~~this might be a problem in nightly. after all, i had and have a lot of problems with many programs on nix(os).~~ (EDIT: it is 'stable', no 'nightly'). but i don't know how to pin down the problem.

**Comment by saghul** [comment]
Firefox nightly is now on 58, which means your version of Nightly is quite old. Can you update it and give it another try?

**Comment by saghul** [comment]
Also, do you nee anything in the JavaScript console?

**Comment by castilma** [comment]
note: i use noscript to blog analytics, but obviously allowed jit.si and jitsi.net

logging gives me 
```
[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 10.1 error 0 happened
Stack trace:
t.a/i.Strophe.log@https://cdn.jitsi.net/2407/libs/lib-jitsi-meet.min.js?v=2407:2:680810
error@https://cdn.jitsi.net/2407/libs/lib-jitsi-meet.min.js?v=2407:2:24279
_onRequestStateChange@https://cdn.jitsi.net/2407/libs/lib-jitsi-meet.min.js?v=2407:2:54335
  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/strophe.util.js] <t.a/i.Strophe.log>:  Strophe: request id 10.1 error 0 happened  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/strophe.util.js] <t.a/i.Strophe.log>:  Strophe: request errored, status: 0, number of errors: 1  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe disconnected:	 27561.920000000002  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/strophe.ping.js] <value>:  Ping interval cleared  lib-jitsi-meet.min.js:2:293209
(TIME) index.html loaded:	 1594.8  CrazyFungiSpel:9:9
(TIME) Sending external connect XHR:	 2076.1150000000002  external_connect.js:65:5
[modules/RTC/RTCBrowserType.js] <o>:  This appears to be Firefox, ver: 56  lib-jitsi-meet.min.js:2:293209
(TIME) external connect XHR done:	 3007.185  external_connect.js:40:13
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 t.default@https://cdn.jitsi.net/2407/libs/app.bundle.min.js?v=2407:2:61667  app.bundle.min.js:2:236534
[react/index.web.js] <>:  (TIME) document ready:	 5273.825  app.bundle.min.js:2:718891
[react/features/base/media/middleware.js] <t>:  Start muted:   app.bundle.min.js:2:718891
[react/features/base/media/middleware.js] <t>:  Start audio only set to false  app.bundle.min.js:2:718891
[modules/URL/ConferenceUrl.js] <e>:  "Stored original conference URL: https://meet.jit.si/CrazyFungiSpel"  app.bundle.min.js:2:718891
[modules/URL/ConferenceUrl.js] <e>:  "Conference URL for invites: https://meet.jit.si/CrazyFungiSpel"  app.bundle.min.js:2:718891
[modules/RTC/RTCUtils.js] <value>:  Get media constraints Object { audio: true, video: false }  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/strophe.jingle.js] <t>:  Configured STUN servers:  Array [ Object, Object, Object ]  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe Attaching	:5975.8  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe attached:	 5979.485  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/xmpp.js] <value>:  My Jabber ID: 8be76517-19ee-440f-a400-5bf81aa8f8e0@meet.jit.si/6ac8a6c1-376b-4850-85c2-f285ce424c2a  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <E/<>:  Available devices:  Array [ MediaDeviceInfo, MediaDeviceInfo ]  lib-jitsi-meet.min.js:2:293209
[react/features/analytics/functions.js] <a/<>:  Loaded 2 analytics handlers  app.bundle.min.js:2:718891
[modules/xmpp/strophe.ping.js] <value>:  XMPP pings will be sent every 10000 ms  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <value/<>:  Failed to get access to local media. Error  MediaStreamError { name: "NotReadableError", message: "Failed to allocate audiosource", constraint: "", stack: "" } Object { audio: true, video: false }  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <T/<>:  failed to obtain audio stream - stop Object { gum: Object, name: "gum.general", message: "Failed to allocate audiosource", stack: "r@https://cdn.jitsi.net/2407/libs/l…" }  lib-jitsi-meet.min.js:2:293209
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio", "video" ] Object { gum: Object, name: "gum.general", message: "Failed to allocate audiosource", stack: "r@https://cdn.jitsi.net/2407/libs/l…" }  app.bundle.min.js:2:718891
[modules/RTC/RTCUtils.js] <value>:  Get media constraints Object { audio: true, video: false }  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <value/<>:  Failed to get access to local media. Error  MediaStreamError { name: "NotReadableError", message: "Failed to allocate audiosource", constraint: "", stack: "" } Object { audio: true, video: false }  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <T/<>:  failed to obtain audio stream - stop Object { gum: Object, name: "gum.general", message: "Failed to allocate audiosource", stack: "r@https://cdn.jitsi.net/2407/libs/l…" }  lib-jitsi-meet.min.js:2:293209
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio" ] Object { gum: Object, name: "gum.general", message: "Failed to allocate audiosource", stack: "r@https://cdn.jitsi.net/2407/libs/l…" }  app.bundle.min.js:2:718891
[modules/RTC/RTCUtils.js] <value>:  Get media constraints Object { audio: false, video: Object }  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <value/<>:  Failed to get access to local media. Error  MediaStreamError { name: "NotFoundError", message: "The object can not be found here.", constraint: "", stack: "" } Object { audio: false, video: Object }  lib-jitsi-meet.min.js:2:293209
[modules/RTC/RTCUtils.js] <T/<>:  failed to obtain video stream - stop Object { gum: Object, name: "gum.not_found", message: "Requested device(s) was/were not fo…", stack: "r@https://cdn.jitsi.net/2407/libs/l…" }  lib-jitsi-meet.min.js:2:293209
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "video" ] Object { gum: Object, name: "gum.not_found", message: "Requested device(s) was/were not fo…", stack: "r@https://cdn.jitsi.net/2407/libs/l…" }  app.bundle.min.js:2:718891
[conference.js] <init/<>:  initialized with %s local tracks 0  app.bundle.min.js:2:718891
[modules/xmpp/ChatRoom.js] <t>:  Joined MUC as crazyfungispel@conference.meet.jit.si/8be76517  lib-jitsi-meet.min.js:2:293209
[modules/connectivity/ParticipantConnectionStatus.js] <e>:  RtcMuteTimeout set to: 2000  lib-jitsi-meet.min.js:2:293209
[modules/statistics/AvgRTPStatsReporter.js] <e>:  Avg RTP stats will be calculated every 15 samples  lib-jitsi-meet.min.js:2:293209
[JitsiConference.js] <r>:  backToP2PDelay: 5  lib-jitsi-meet.min.js:2:293209
[modules/remotecontrol/RemoteControl.js] <value>:  Initializing remote control.  app.bundle.min.js:2:718891
[conference.js] <updateAudioIconEnabled>:  Microphone button enabled: false local audio: null audio devices: undefined device count: 0  app.bundle.min.js:2:718891
[conference.js] <updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices: undefined device count: 0  app.bundle.min.js:2:718891
[modules/xmpp/moderator.js] <i.prototype.setFocusUserJid>:  Focus jid set to:  undefined  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/moderator.js] <i.prototype.createConferenceIq>:  Session ID: null machine UID: 53a820381cca0cb40425b9989087cd51  lib-jitsi-meet.min.js:2:293209
[conference.js] <updateAudioIconEnabled>:  Microphone button enabled: true local audio: null audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo] device count: 2  app.bundle.min.js:2:718891
[conference.js] <updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices:  device count: 0  app.bundle.min.js:2:718891
[modules/xmpp/moderator.js] <i.prototype.setFocusUserJid>:  Focus jid set to:  focus@auth.meet.jit.si  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  Authentication enabled: false  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  External authentication enabled: false  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  Sip gateway enabled:  true  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/ChatRoom.js] <value>:  entered crazyfungispel@conference.meet.jit.si/focus Object { show: "", affiliation: "owner", role: "moderator", jid: "focus@auth.meet.jit.si/focus1714828…", isFocus: true, isHiddenDomain: false }  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/ChatRoom.js] <value>:  Ignore focus: crazyfungispel@conference.meet.jit.si/focus, real JID: focus@auth.meet.jit.si/focus171482845970  lib-jitsi-meet.min.js:2:293209
[modules/UI/UI.js] <O.initEtherpad>:  Etherpad is enabled  app.bundle.min.js:2:718891
[modules/version/ComponentsVersions.js] <r.prototype.processPresence/<>:  Got xmpp version: Prosody(trunk nightly build 747 (2017-02-19, 428d4abee723),Linux)  lib-jitsi-meet.min.js:2:293209
[modules/version/ComponentsVersions.js] <r.prototype.processPresence/<>:  Got focus version: JiCoFo(1.0.1.0-384,Linux)  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/recording.js] <i.prototype.handleJibriPresence>:  Handle Jibri presence : off null  lib-jitsi-meet.min.js:2:293209
[conference.js] <_setupListeners/<>:  Received recorder status change:  available undefined  app.bundle.min.js:2:718891
[conference.js] <_setupListeners/<>:  My role changed, new role: moderator  app.bundle.min.js:2:718891
[JitsiConference.js] <r.prototype._maybeStartOrStopP2P>:  P2P? isModerator: true, peerCount: 0 => false  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/ChatRoom.js] <value>:  (TIME) MUC joined:	 11724.36  lib-jitsi-meet.min.js:2:293209
[modules/xmpp/ChatRoom.js] <value>:  Subject is changed to   lib-jitsi-meet.min.js:2:293209
[modules/UI/videolayout/LargeVideoManager.js] <value/<>:  hover in %s 8be76517
```

js gives me
```
          navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia  RTCUtils.js:528:12
Use of attributes’ nodeValue attribute is deprecated. Use value instead.  lifecycle.js:212
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  CrazyFungiSpel:1
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 168:  (unknown):1:168
Using more than two STUN/TURN servers slows down discovery callstats-ws.min.js:21
```

**Comment by foss-** [comment]
I do not understand the response of jitsi dev team here. Are you testing jitsi with Firefox at all? I have been seeing audio and screensharing issues for years now.

User reports issues for Firefox stable version, dev team asks to check nightly. Have the devs actually checked nightly themselves? What were their results?

We are now at Firefox 59.0.1 stable which supersedes the suggested v58 (which was nightly at the time it was suggested) and I am still unable to get an audio chat working using https://meet.jit.si .

**Comment by damencho** [comment]
Audio and video work with Firefox, we are testing that. We know for a problem with screensharing from Firefox, but we are looking at it at the moment.
So you have audio problems with Firefox, do you have problems if you try chrome/chromium and meet.jit.si? Can you test with your Firefox with https://appr.tc/, is the audio working for you there?
What is the operating system where you are experiencing the problem?

**Comment by foss-** [comment]
Hi damencho. Excuse the tone in my last reply. Situation felt a bit hopeless looking at the past years and how Jitsi has been performing on Firefox.

OS: macOS 10.13.3

When I use Chromium with Jitsi Meetings 0.2.8.14 I do not have audio issues. It works seamless.

When joining https://appr.tc/ with Firefox I see no errors. Since I am the only person in the room then I can't tell wether audio is working or not.

**Comment by castilma** [comment]
still having the problem with firefox 59.0.1.
i tested again with Chromium 65.0.3325.146 . it worked first, but then it didn't.

**Comment by damencho** [comment]
What is your operating system? You can try on https://appr.tc/ by opening two tabs and you will hear your own sound like echo, do you have audio with Firefox there?

**Comment by foss-** [comment]
Using Firefox 59.0.1 with two tabs of the same session of https://appr.tc I do hear audio.

**Comment by castilma** [comment]
@damencho I'm on nixos 18.03. on appr.tc I don't get any sound. neither with firefox nor chromium.

**Comment by damencho** [comment]
@castilma I think there is some general problem with the devices used by the browsers, not sure what can be the cause of it, maybe alsa and problem accessing devices from different applications ... it something to do with how stuff are configured on your system. 

@foss- if appr.tc is working for you this means a problem on our side with your devices. Are you using the built-in devices on your computer (is it a macbook?) or you are using some usb devices?

**Comment by foss-** [comment]
@damencho Tested: no USB devices, all internal mic / speaker.
**imac** default internal mic + speakers, two tabs of same room on https://appr.tc/ → no audio, video works
noticed: "internal mic" does show twice in the settings (tried both with same results), probably expected since it's a system default, but it's confusing to users.
![internal mic](https://user-images.githubusercontent.com/5708172/37895755-8cd9b44c-30e2-11e8-955c-e716ebe29e88.png)
**macbook** audio + video working as expected

Interesting: while on the macbook where a connection works and is actually happening, on the imac there is no phone icon displayed in the appr.tc active call window. so on macbook the icons are: mic, video, fullscreen, hangup but on imac: mic, video, fullscreen. no hangup button which to me suggests, the connection is not happening.

So assuming macbook is working as expected, I revisited meet.jit.si on macbook / iOS app and audio worked just fine in Firefox 59.0.1.

So the problem is now isolated to not being related to Firefox, but to some audio setup on the imac. On the imac looking at system preferences > sound > input I do see the mic being active and receiving sound when making noise.

I hope this is helpful in further debugging this and getting jitsi to work on the imac as well.

**Comment by damencho** [comment]
Ok, glad you figure out it is a specific device issue. Problems like this are very hard to fix without having access to such device, and the fact that it is not working even with appr.tc seems to me that it can be a firefox issue, nothing which we can fix. 
When using meet.jit.si or appr.tc do you see any js errors? It will be useful to see them. 
Other than that, if on that particular machine chrome/chromium works, can you use that as a workaround?

**Comment by foss-** [comment]
Played with this some more on imac. This time it seems one tab indeed created a connection. I am seeing the hangup icon (which previously did not show).

When trying to access the same appr.tc session in a second tab I received the following error messages in chronological order:

![error1](https://user-images.githubusercontent.com/5708172/37915493-f3a810f6-3119-11e8-8af7-89912ae52ab7.png)
![error2](https://user-images.githubusercontent.com/5708172/37915494-f3c87c92-3119-11e8-9c8b-3b2890934dba.png)
![error3](https://user-images.githubusercontent.com/5708172/37915496-f3e3a60c-3119-11e8-97cd-6a9419f9f467.png)

**Comment by damencho** [comment]
I've been checking over the Internet and it seems it is a common Firefox issue with some devices, not able to use the microphone/camera when used from two tabs or from two processes on the same machine. 
So in order to test this one, you need two different PCs, can you do that?
Open a tab with appr.tc on the imac and open that tab on another machine and check whether you have audio/video. Then close those, and do the same experiment using meet.jit.si, is there a difference?

**Comment by foss-** [comment]
Created new room and joined the room on imac + macbook.

Somewhat funny situation: macbook said "remote side hung up" so reloaded macbook with active connection on imac.
Result: imac says "remote side hangup" and macbook has active connection. Reload imac tab.
Result: macbook says "remote side hangup" start from the top.

Tried a new room. The initial situation seems to be what this bug is about: video working on both sides, audio working on neither. No hangup button on neither machine. No error messages in appr.tc.

meet.jit.si is behaving the same. If you want to get in touch to remote debug this, feel free to do so.

This has been a common issue for webRTC over the past years and imo jitsi is suffering from it in a serious way. As you correctly state, it seems to be a bug in Firefox / webRTC. But there should be an interest from jitsi to get this bug filed in the correct place and ideally solved, so we can all move on and rely on webRTC working in Firefox as expected.

**Comment by foss-** [comment]
For what it's worth the problematic hardware is a 27" iMac late 2012. Not sure if your team has a similar mac? So likely jitsi unrelated and yet I am unsure how to properly debug this. I'll keep trying and let you know when I have news to share.
