### ISSUE TITLE
prosody plugin setting to make all users owners/moderators , it can`t work!

### ISSUE THREAD

**Issue by zxy123** [jitsi/jitsi-meet#2127]
Hi, everyone! 
      How to set it up correctly？

**Comment by saghul** [comment]
What problem are you getting?

**Comment by zxy123** [comment]
I installed jitsi-meet by default, I copy mod_muc_allowners.lua to prosody modules path, and in prosody.cfg.lua modules_enabled . prosody service error Error initializing module 'muc', MUC should be loaded as a component, and error initializing module 'muc_allowners' Unable to load required module, mod_muc: MUC should as component.
thanks!

**Comment by damencho** [comment]
Which version are you using? We are using it with trunk 747 for meet.jit.si. 
Not sure about compatability with the other prosody versions.
We had added all our prosody modules in the tokens deb package and it depends to prosody-trunk:
Package: jitsi-meet-tokens
Architecture: all
Depends: ${misc:Depends}, prosody-trunk (>= 1nightly607), libssl-dev, luarocks, jitsi-meet-prosody

**Comment by zxy123** [comment]
I install jitsi-meet by quick-install.md.

**Comment by damencho** [comment]
Did you add the module under your muc component?
Component "conference.your.domain" "muc"
    modules_enabled = { "muc_allowners"}

**Comment by damencho** [comment]
If you have done the things from the comment above and it is still not working.
You can install prosody-trunk as described here https://prosody.im/download/package_repository
And try again. Make sure you first stop the previous prosody just in case, before installing the new one.

Also when you run the muc_allowners module, there is an interface config property that disables the stars:     DISABLE_FOCUS_INDICATOR: true

**Comment by zxy123** [comment]
I update prosody to the newest version, and add the module under my muc component. it is still not working, error: Error initializing module 'muc_allowners' on 'conference.my.domain ': /usr/lib/prosody/modules/mod_muc_allowners.lua:13: attempt to index local 'room_mt' (a nil value)

**Comment by damencho** [comment]
That is strange I do not see this using latest prosody-trunk. 
I still see some problem in the UI, but both users I see in the console as moderators.

**Comment by zxy123** [comment]
thanks @damencho
