### ISSUE TITLE
Logitech ConferenceCam Connect microphone not working

### ISSUE THREAD

**Issue by backpuller** [jitsi/jitsi-meet#2132]
The microphone can not be select as an input
It is in the list of devices, and can be selected. But after I save, no settings is applied
![skaermbillede_110317_085624_am](https://user-images.githubusercontent.com/33342303/32366027-a9490d7a-c07c-11e7-86db-e5d901a7f2ec.jpg)

**Comment by saghul** [comment]
Do you see any error in the JavaScript console? Do you get a prompt saying that the microphone doesn't work?

**Comment by backpuller** [comment]
I get a prompt saying there was an error with the microphone.  
I have a Danish Windows language pack under suspicion, since it involves Æ Ø Å
And the dicive is listed with Æ and Ø used in the device name

And I know this microphone has worked on another machine running a Windows with US language pack only
Tried to change language on the machine to en-us, but system language is still Danish. Can not rename the device
On other machine system language Is en-us and there is no problems

**Comment by backpuller** [comment]
I can confirm that the issue was related to the ÆØÅ in the letters
Once the client wa running ENG virsion of windows, it connected just fine
