### ISSUE TITLE
Hidding invite button over filmstrip

### ISSUE THREAD

**Issue by danielmonroy** [jitsi/jitsi-meet#2134]
https://github.com/jitsi/jitsi-meet/blob/c3efa4f088c9efeab57db215da2a9472a7626823/interface_config.js#L54

Hi! I was trying to disable the invite options in the interface config and the one that I can't get rid of is the invite button that is placed in the filmstrip area. How can I disable that option?

Thanks!

**Comment by webmagnets** [comment]
Me too. I tried making INVITE_OPTIONS a blank array, but it still shows the invite button.

**Comment by modecolems** [comment]
Hi, interested by that feature too. thx

**Comment by burgalon** [comment]
me too
