### ISSUE TITLE
 no such file JSCSamplingProfiler.m

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#2135]
I  run  jitsi-meet  with xcode        error occurred

![image](https://user-images.githubusercontent.com/9635493/32421187-c8891440-c2d0-11e7-9410-e8a4c5d98438.png)
What should I do

**Comment by saghul** [comment]
We have recently updated to React 16 and React Native 0.49. Have you updated your checkout and reinstalled all pods?

**Comment by saghul** [comment]
No follow-up, closing.
