### ISSUE TITLE
patch muc_all_owner_allow_kick.patch error!

### ISSUE THREAD

**Issue by zxy123** [jitsi/jitsi-meet#2137]
I put file "muc.lib.lua" "muc_owner_allow_kick.patch" to same path in the ubuntu system. use the command "patch -p0 < muc_owner_allow_kick.patch" , get error "Hunk #1 FAILED at 1256".  vi file "muc.lib.lua" , total lines is 1186,

**Comment by damencho** [comment]
Are you using prosody trunk? 
The patch was done with old prosody-trunk, apparently it is not correct with your version. The patch is simple enough to do it by hand, so open muc.lib.lua and try adding the changes manually.

**Comment by zxy123** [comment]
@damencho I didn't find the corresponding function location to modify it, Can you give me some information about it.

**Comment by damencho** [comment]
Which version of prosody do you use?

**Comment by zxy123** [comment]
version of prosody is .0.10.0.

**Comment by damencho** [comment]
This patch is for prosody-trunk.

**Comment by zxy123** [comment]
I'm a beginner for jitsi-meet, I can't find the difference prosody and prosody-thunk, I installed jitsi-meet in ubuntu 16 system by quick-install.

**Comment by damencho** [comment]
`echo deb http://packages.prosody.im/debian $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list
wget https://prosody.im/files/prosody-debian-packages.key -O- | sudo apt-key add -
apt-get update
apt-get install prosody-trunk
`
These are sintructions from: https://prosody.im/download/package_repository

**Comment by zxy123** [comment]
It worked Correctly！thanks @damencho
