### ISSUE TITLE
Change redirect URL after call end button click

### ISSUE THREAD

**Issue by KesavanSanthosh** [jitsi/jitsi-meet#2141]
I am using jisti-meet with my web application for video and voice call.After finishing call, when I click end call button the rating model will open after click submits go to jisti home page. I don't want this alert and redirect how to handle this?

**Comment by FelipeMiranda** [comment]
That's a good question, I also need to redirect to a callback URL. It's funny this answer hasn't been answered yet, I'm looking for a solution

**Comment by damencho** [comment]
I don't think there is an option to disable the feedback on hangup, other than disabling callstats at all.  After the hangup, what do you want to show? 
There is an option to show a close page(https://github.com/jitsi/jitsi-meet/blob/master/config.js#L223). Or when using the iframeAPI there is an event that local user has left the conference and you can show something else.

**Comment by FelipeMiranda** [comment]
I want to redirect user after he gives the feedback to the root of my website, I'm trying with the close page option but it is not working right even thought I did set in config.js.

I'm building it from source.

**Comment by ihimydv** [comment]
I was looking for the same, didn't fount any way to customize, anyone have any suggestions for me?

**Comment by Helius01** [comment]
I have the same problem, any ideas?
