### ISSUE TITLE
Android SSL cont not pass on RN 0.49.5

### ISSUE THREAD

**Issue by qinyuanmao** [jitsi/jitsi-meet#2151]
I can go into the room when I dont update the project and I use the 
```
OkHttpClientProvider.replaceOkHttpClient(OkHttpCertUtil.initCustomOkHttpClientAndCert());
```
or
```
OkHttpClientProvider.replaceOkHttpClient(OkHttpCertUtil.initCustomOkHttpClientNoCert());
```
but I cant go into the room when I update my project and the error is
```
E/ReactNativeJS: 'Failed to load config from https://192.168.1.100/config.js?room=qq', [TypeError: Network request failed]
```

**Comment by qinyuanmao** [comment]
I found the commit update RN0.49.5, When the promble create.

**Comment by saghul** [comment]
I think the okhttp library got updated as a dependency of React Native. You'll need to find out how to chieve the same goal as before, using the new API. Alas I personally haven't used okhattp directly so I can't guide you there.

**Comment by qinyuanmao** [comment]
I got the https://gethttpsforfree.com/ free https and resolve the promble
