### ISSUE TITLE
Bypass Android Authentication

### ISSUE THREAD

**Issue by tanvir8269** [jitsi/jitsi-meet#2152]
Hi guys,
I have an android app that uses jitsi-meet sdk. Now I was wondering if there is way to by pass the authentication, like a function call that can accept the username and password and create the room?  
example,

JitsiMeetView.CreateRoom("user@example.com","password");

**Comment by saghul** [comment]
No, that is not currently implemented. Sorry!

**Comment by Ace2222** [comment]
Does your app run on an android 6.0 device well?My app open camera failed
