### ISSUE TITLE
Jigasi and Video support

### ISSUE THREAD

**Issue by zemzema** [jitsi/jitsi-meet#2153]
Is there any chance to implement into Jigasi Video over SIP? I'm having video SIP phone, and Jigasi is working only in audio mode.

**Comment by saghul** [comment]
Have a look at jibri, it supports video too!

**Comment by zemzema** [comment]
Can Jibri do SIP call?

**Comment by damencho** [comment]
Yes, jibri can be configured to call a video sip device.
