### ISSUE TITLE
Thumbnail sometimes is not visible in Chromium/Chrome

### ISSUE THREAD

**Issue by dbareiro** [jitsi/jitsi-meet#2160]
Hi!

I would like to mention something that I note at times in Chromium/Chrome. Sometimes the thumbnail is not on the screen. I think this does not happen in Firefox (at least I do not remember seeing it).

In addition, when this happens, the button to invite people that is usually under the thumbnail, appears shifted to the right outside the visible space of the screen. You can barely see the left edge of that button.

Here you can see a screenshot.

https://ibin.co/3fhBQ50lc4cd.jpg

When I toggle the filmstrip visibility the issue resolves itself (that forces recalculations by the javascript and by that time the css should be loaded.). If I understood correctly what Leonard Kim told me in the `dev` list, it seems that this is caused by some kind of race condition (which is a dependency load order issue), although it is strange that only happens in Chromium/Chrome (I think this does not happen with Firefox).

That seems to be a workaround when this problem happens, but it would be nice to have this solved.

Leonard told me that there is an internal ticket for it so I only open this issue in Github to have here also the updates about it so that those of us who are experiencing it are up to date about the progress on this opened issue.

Thanks in advance for your time.

Kins regards,
Daniel

**Comment by virtuacoplenny** [comment]
This one might be fixed now. It's been on my radar for months and became a personal goal of mine and I was able to maybe fix it while doing something else, https://github.com/jitsi/jitsi-meet/pull/2228.

**Comment by dbareiro** [comment]
Hi, virtuacoplenny.

That's great! Thank you very much!

Do you think this fix will be available in the next build of packages for the testing repo? In any case, I will be happy to do tests when this happens, reporting the results later.

Kind regards,
Daniel

**Comment by virtuacoplenny** [comment]
Looks like it's in https://github.com/jitsi/jitsi-meet/releases/tag/2489 and should be going to meet.jit.si soon.

**Comment by dbareiro** [comment]
Perfect! Thanks for confirm!

I will do some tests after updating the packages and I will inform the results.

Thanks again!

Kind regards,
Daniel
