### ISSUE TITLE
Configure jitsi-meet

### ISSUE THREAD

**Issue by birender** [jitsi/jitsi-meet#2162]
Facing Issue to configure meet-jitsi
please assist me

**Comment by damencho** [comment]
People can help you, if you provide any details about your problem and provide some questions around that.

**Comment by birender** [comment]
Facing issue to configure meet-jitsi
Demo URL : https://webrtc.ajdevdemos.com/
Unable to create room in demo url

Live URL for Reference
https://meet.jit.si/

**Comment by saghul** [comment]
Continuin at #2170 since it has more details.
