### ISSUE TITLE
updateActiveSpeakerAudioLevel causing CPU spike.

### ISSUE THREAD

**Issue by serviewcare** [jitsi/jitsi-meet#217]
Using Google Chrome 39 on OSX, I have noticed after being in a call for a period of time the performance of the calls began to degrade.

After disconnecting all participants, the CPU use still stayed ~90-100%.

After doing a CPU Profile, I noticed that updateActiveSpeakerAudioLevel was the primary contribution.

Upon commenting out the call to updateActiveSpeakerAudioLevel in AudioLevels.js, the CPU use remains stable.

**Comment by Zalmoxisus** [comment]
The same issue is when we focus an user video, the cpu increases a lot, and after unfocusing it decreases a bit. It happens after a continuous discussion with many participants. Sometimes it slows so much that it is almost impossible to type something in chat.
I thought it is an issue of webrtc.
I also use Google Chrome 39 on OSX, but reproduced it on Windows too.

**Comment by bgrozev** [comment]
Has anyone seen this with a recent (>=365) version of Jitsi Meet? We saw it with 333 and 339, but fail to reproduce with 365.

**Comment by bgrozev** [comment]
Nevermind, @hristoterezov can repro.

**Comment by gpolitis** [comment]
@hristoterezov you've fixed this, right?

**Comment by hristoterezov** [comment]
Yes. This is fixed.
