### ISSUE TITLE
Trouble to Configure Meet JitSI 

### ISSUE THREAD

**Issue by birender** [jitsi/jitsi-meet#2170]
I am facing trouble while I configured meet-jetsi into my server
Link : https://webrtc.ajdevdemos.com
When I try to create room, always 404 error show

Please let me know where I am doing wrong

**Comment by saghul** [comment]
Your Apache configuration could be wrong. Can you paste it here?

**Comment by birender** [comment]
Apache Configuration
Server : webrtc.ajdevdemos.com
<VirtualHost _default_:443>
                ServerAdmin webmaster@localhost
                ServerName webrtc.ajdevdemos.com
                DocumentRoot /var/www/html/html/jit
                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                <Directory /var/www/html/html/jit>
                  Options Indexes FollowSymLinks
                  AllowOverride None
                  Require all granted
                </Directory>
    SSLEngine on
SSLCertificateFile      /usr/local/etc/janus/SSL/webrtc_ajdevdemos_com.crt
SSLCertificateKeyFile /usr/local/etc/janus/SSL/webrtc.ajdevdemos.com.key
</VirtualHost>
=================================================
Apache Modules
=================================================
core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 proxy_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)

**Comment by damencho** [comment]
There is a debian package, which you can use to install all dependencies and which can configure apache2.
Here is the template used for apache, you can use it to configure your instance: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example-apache
Did you also install and configure jicofo and jvb?

**Comment by birender** [comment]
No I didn't install yet
can you directory communicate with me on skype "birender.rana@ajdevtech.com"

**Comment by birender** [comment]
Add the configuration on my local system
 https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example-apache

**Comment by birender** [comment]
Apache Configured successfully
But When I try to update the 
hosts: {
        domain: 'webrtc.ajdevdemos.com',

        muc: 'conference.meet.jit.si', // FIXME: use XEP-0030
        focus: 'focus.meet.jit.si',
    }
host when connection failed error show

if I use the domain name "meet.jit.si" then it's works fine

Can you please let me where I doing wrong

**Comment by damencho** [comment]
Your problem is that you do not have jvb and jicofo. This is a system which consists of web webrtc app and server side components.
My advice is to use the quick install guide https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

**Comment by birender** [comment]
I have installed the vb and jicofo on my server but and Easily make call other stuff but One thing I noticed that call disconnected after 1-2 min.......
can you have any idea about this issue

**Comment by damencho** [comment]
What about logs, did you see an error, exception on jicofo or jvb side?

**Comment by birender** [comment]
I am attached error log . kindly assist me

![error](https://user-images.githubusercontent.com/1873263/32901644-553704e0-cb16-11e7-86bf-5182a2f9ee56.png)
![error1](https://user-images.githubusercontent.com/1873263/32901818-c2c2bc8e-cb16-11e7-8c29-ce28efafb8dd.png)

**Comment by damencho** [comment]
Uploading jicofo and jvb logs will help to identify the problem.

**Comment by birender** [comment]
Hi,
I have upload the log. can you check (jvb and jicofo) log
[jvb.log](https://github.com/jitsi/jitsi-meet/files/1479397/jvb.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1479399/jicofo.log)

**Comment by damencho** [comment]
Can you upload all of them even older ones, I have a suspicion but needs the older logs, cause there is no info in these.

**Comment by birender** [comment]
Currently I have only these logs.
