### ISSUE TITLE
Issue with audio device not persisting

### ISSUE THREAD

**Issue by lloydwatkin** [jitsi/jitsi-meet#2173]
This issue has appeared recently. My audio device is not persisting, audio used to be selected as my USB headset, now each time I open up on a conference (on meet.jit.si) the audio device has reverted to default. I am able to switch back to my headset during a call, but it is reverted on next load.

Browser: Version 62.0.3202.75 (Official Build) (64-bit)
OS: Ubuntu 16.04

**Comment by virtuacoplenny** [comment]
Preferred devices is saved in local storage to be used again on app initialize. https://github.com/jitsi/jitsi-meet/blob/90dcb251c3f953b741a3e8b9792995f23a58009e/modules/settings/Settings.js. Could there by something going on with your local storage settings? Do you see any logged errors in the console related to devices?

**Comment by lloydwatkin** [comment]
I cleared localStorage, but that hasn't helped. I see this in the console (screenshot), the device its picking is my headset ID but sound comes from speakers.

![screenshot from 2017-11-15 17-22-32](https://user-images.githubusercontent.com/271622/32850428-036d18b2-ca2a-11e7-82b2-71c619d1dc39.png)

**Comment by virtuacoplenny** [comment]
You're referring to audio output then, not input? Could you try testing on beta? I pushed a fix related to audio output selection yesterday.

**Comment by lloydwatkin** [comment]
Sorry @virtuacoplenny, should have been more specific!
Is there a version of meet.jit.si that runs on beta?

**Comment by virtuacoplenny** [comment]
Yeah, beta is automatically deployed when commits get pushed whereas meet.jit.si is deployed manually. So beta is bleeding edge and considered unstable.

**Comment by virtuacoplenny** [comment]
Reposting link to beta in case my edited comment was missed: https://beta.meet.jit.si

**Comment by lloydwatkin** [comment]
Ok, audio seems better, its coming from the correct source after refresh.

However now when people join they can see/hear me but I have to refresh in order to see/hear them (in fact I'm not even are they are in the call until I do that). I think this is happening on standard meet.jit.si too.

Confirmed. I also see lots of these in my console...

![screenshot from 2017-11-15 17-43-47](https://user-images.githubusercontent.com/271622/32851319-939a57ae-ca2c-11e7-8c52-369112a2f5db.png)

**Comment by virtuacoplenny** [comment]
So I can't tell where this is coming from and I'm also not able to reproduce the issue. I searched around and see this issues crops up with react debugging tools. Do you run any react dev tools running?

**Comment by lloydwatkin** [comment]
Yes both react and redux

**Comment by lloydwatkin** [comment]
Yes both react and redux

**Comment by lloydwatkin** [comment]
Note: I haven't recently added these. The problem has arisen a long time since.

**Comment by virtuacoplenny** [comment]
I'm assuming you're using redux-devtools-extension. They have an open ticket about this issue. The line throwing this problem is: https://github.com/zalmoxisus/redux-devtools-extension/blob/a0dfcf65d2cca6394cebd0656cf4d9b9c933421a/src/app/api/index.js#L18. The problem is jitsi-meet js dispatches the action CONFERENCE_JOINED, passing along with it the lib-jitsi-meet conference object. That conference object cannot be stringified due to a circular reference--you can try this out in the console with JSON.stringify(APP.conference._room).

**Comment by virtuacoplenny** [comment]
Because the issue is caused by a debugging tool, and might be worked around by disabling the tool, I don't think the team will have time to fix it right now. Contributions are definitely welcome if you feel inclined to try a fix.

**Comment by lloydwatkin** [comment]
Using meet.jit.si this morning, sound went directly to headset without resetting. I'm closing this as it now seems to to be fixed :+1:
