### ISSUE TITLE
Unable to install on centos

### ISSUE THREAD

**Issue by AdamMiltonBarker** [jitsi/jitsi-meet#2179]
Hi guys have found a few tutorials about installing on centos but they all fail with dependency errors, is there an official guide anywhere to installing this on centos, thanks in advance.

**Comment by damencho** [comment]
No, there is no such document. 

You can use the [manual installation guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md), which usually is outdated. The most up-to-date configuration scripts are the debian packages.

Or you can do a mix of both, reading the manual installation guide and looking at the configuration postinst scripts from [jvb](https://github.com/jitsi/jitsi-videobridge/blob/master/resources/install/debian/postinst), [jicofo](https://github.com/jitsi/jicofo/blob/master/resources/install/debian/postinst), [jitsi-meet-prosody](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst
) and [jitsi-meet](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst) in this order.
