### ISSUE TITLE
Webcam isn't closed when muting it

### ISSUE THREAD

**Issue by guilhem** [jitsi/jitsi-meet#219]
When using meet.jit.si , camera is still in use even if muted (activation led is on).

Same things happen on `appear.in` but not on `Hangout`

**Comment by hristoterezov** [comment]
We fixed this in 3a0ee11ccd55b2734e6d6ef697c5290738ac4aef.

Currently the camera is stopped only for https connection.

**Comment by guilhem** [comment]
it works! yeah :)
Thanks
