### ISSUE TITLE
The app crash when hangup.

### ISSUE THREAD

**Issue by qinyuanmao** [jitsi/jitsi-meet#2195]
```
E/libc: Access denied finding property "persist.camera.cfa.packagelist"
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x2a in tid 19902 (t.jitsimeetdemo)
```

**Comment by lyubomir** [comment]
Which jitsi/jitsi-meet commit hash did you hit the crash with please? On which Android version? On what device?

**Comment by qinyuanmao** [comment]
Oneplus3T with Android O，I commit master branch.

**Comment by lyubomir** [comment]
Could you please try with https://github.com/jitsi/jitsi-meet/commit/0aa377fcfc5fc528c985c0bf789bad2466729f22 (or later/newer)?

**Comment by qinyuanmao** [comment]
@lyubomir still crash

**Comment by saghul** [comment]
@paweldomas what Android version are you running on your OnePlus?

**Comment by paweldomas** [comment]
Android 7.1.1 OxygenOS 4.5.14

**Comment by saghul** [comment]
Thanks @paweldomas! @qinyuanmao does the Jitsi Meet app crash for you?

**Comment by qinyuanmao** [comment]
@saghul yes

**Comment by qinyuanmao** [comment]
I try to close the camera before hangup and wait 250ms, and the problem is close , but have and new problem on android 5.0 and 5.1, I cant find the camera at the twice, the page is black.

**Comment by saghul** [comment]
You shouldn't close the camera yourself. The SDK opens and closes the camera when necessary. When a conference ends / fails a black page will be rendered and the camera will be closed. At that point, that is, when the conferenceFailed or conferenceEnded interface methods are called, you should finish the activity or hide it.

**Comment by xioamins** [comment]
I also encountered when I hung up, has been in a black state, the program can not be withdrawn
