### ISSUE TITLE
Mobile App - issue connecting to private server using interdemiate certificate

### ISSUE THREAD

**Issue by JFMALBI** [jitsi/jitsi-meet#2196]
I have an issue when I try to connect to our own autenticated jitsimeet server with the mobile app (Android)
I fill the full URL on the mobile app (with the room), but when I try to join the server the mobile app returns to main page
It works with FireFox and Chrome on desktop (and also with my mobile phone when I use the Firefox deskstop interface)
We use a GlobalSign certificate

I have looked forward with certificate issues (https://github.com/jitsi/jitsi-meet/issues/1251) and I think that the problem is that our certificate is delivered by an intermediate certificate (for all our sub-domains : *.mydomain.com) : GlobalSignOrganizationValidationCA-SHA256-G2 which is certified by the root certificate GlobalSign Root CA

On the mobile phone, the GlobalSign Root CA root certificate is loaded but not the intermediate certificate.
When I import the intermiedate certificate localy on my phone, JistiMeet wotks fine !

Do you think it will be possible (as Firefox or Chrome does) to improve the mobile app to work even if intermediate certifiacte is used for private server ?

**Comment by tcmalloc** [comment]
resolved

**Comment by lyubomir** [comment]
Down the road we'll probably want to do something like the Web browsers which show a warning and allow you to continue. I'm unable to give you an ETA at this time though.

**Comment by JFMALBI** [comment]
Hi
With intermediate certificate signed  by a trusted AC you dont have anything to allow with browsers 
The warning is only when the  AC is not installed  (like  self certificate)




Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : Любомир Маринов <notifications@github.com> 
Date :21/11/2017  20:24  (GMT+01:00) 
À : jitsi/jitsi-meet <jitsi-meet@noreply.github.com> 
Cc : JFMALBI <jean-francois.martel@mairie-albi.fr>, Author <author@noreply.github.com> 
Objet : Re: [jitsi/jitsi-meet] Mobile App - issue connecting to private server using interdemiate certificate (#2196) 

Down the road we'll probably want to do something like the Web browsers which show a warning and allow you to continue. I'm unable to give you an ETA at this time though.

**Comment by pinkrickshaw** [comment]
Hello sir ,our private server have the ssl certificate but got this error "ReactNativeJS: 'Failed to load config from https://............../config.js?room=rahul', [TypeError: Network request failed]
07-13 15:49:09.518 30756-30800/com.vc.prd.confab E/unknown:React: console.error: "Failed to load config from https://..................../config.js?room=rahul", {}, stack:
    <unknown>@401:2404
    <unknown>@489:602
    u@211:133
    <unknown>@211:919
    <unknown>@86:966
    callTimer@81:601
    callImmediatesPass@81:1746
    callImmediates@81:1862
    <unknown>@79:2436
    <unknown>@79:106
    value@79:2401
    <unknown>@79:1039
    <unknown>@79:106
    value@79:985"


Its working and live in our one project but when we clone it on another app we got this error please help.

**Comment by manang** [comment]
@pinkrickshaw did you solve?

**Comment by JFMALBI** [comment]
Not really 

I use Letsencrypt certification and it works 

Jean-François MARTEL 
Directeur des Systèmes d'Information 

Direction Système d'Information - Mairie d'Albi 
tel : 05 63 49 13 78 
jean-francois.martel@mairie-albi.fr 

----- Mail original -----

**Comment by reesericci** [comment]
Can this be re-opened? I created my own CA and trusted it on my iPad but the app won't join to it.
