### ISSUE TITLE
java.net.ConnectException: Connection refused 

### ISSUE THREAD

**Issue by tcmalloc** [jitsi/jitsi-meet#2204]
JVB 2017-11-21 23:21:56.354 SEVERE: [18] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Connection refused (Connection refused), host:localhost, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)

**Comment by damencho** [comment]
Make sure prosody is configured to use component port 5347 and is listening on localhost on that port.
