### ISSUE TITLE
Configure jitsi on non-HTTP port

### ISSUE THREAD

**Issue by jobinelv** [jitsi/jitsi-meet#2210]
i want to configure jitsi meet video calling on non-HTTP port, ex: domain.com:4000. My jitsi app currently work in apache2 virtualhost *:80 .

**Comment by saghul** [comment]
If you are using Apache then you need to configure apache to listen on port 4000 and serve the website there. You'll need to add `Listen 4000` and then modify your virtual host to use that port: `<VirtualHost *:4000>`.
