### ISSUE TITLE
Cannot connect microphone: "i.GetSettings is not a function" 

### ISSUE THREAD

**Issue by SergioArbarviro** [jitsi/jitsi-meet#2213]
I and all participants in a meeting have tried several times since 21 November 2017 to connect to the meet.jit.si service (and to the Framatalk.org service based on it), in a private meeting room that we had successfully used under exactly the same name on 07 November 2017. 

The failure was always the same: after requesting to connect to the microphone (be it the internal microphone of the computer or an external Plantronics microphone, as a default microphone or not), the microphone appears as "muted" with no capacity to unmute it, and the following message appears.

"_Failed to access microphone
There was an error connecting to your microphone
i.GetSettings is not a function_"

The Framatalk.org repeatedly attempts to re-initialise the session to solve the issue, but in vain.

**Comment by saghul** [comment]
What browser were you using? What version? Can you please paste some more of the console logs? Thanks!

**Comment by SergioArbarviro** [comment]
## Browser: 
Firefox 48.0.2 running on Mac OSX 10.6.8, Processor Intel Core Duo

## Console log (in which I highlighted the instances of the error "i.GetSettings is not a function":
      OpenGL compositor Initialized Succesfully.
Version: 1.4 APPLE-1.6.36
Vendor: Intel Inc.
Renderer: Intel GMA 950 OpenGL Engine
FBO Texture Target: TEXTURE_2D
Error while loading prefs: Error: Type error for parameter filter (Error processing tabId: Integer -1 is too small (must be at least 0)) for webRequest.onCompleted.background.js:422:18
JQMIGRATE: Migrate is installed, version 1.4.1jquery-migrate.min.js:2:542
(TIME) index.html loaded:	 260.075CosmoPol1:9:9
(TIME) Sending external connect XHR:	 347.71external_connect.js:65:5
[modules/RTC/RTCBrowserType.js] <o>:  This appears to be Firefox, ver: 48(source inconnue)
(TIME) external connect XHR done:	 595.85external_connect.js:40:13
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 t.default@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:60998app.bundle.min.js:2:221934
[react/index.web.js] <>:  (TIME) document ready:	 2513.63(source inconnue)
[react/features/base/media/middleware.js] <t>:  Start muted: (source inconnue)
[react/features/base/media/middleware.js] <t>:  Start audio only set to false(source inconnue)
[modules/URL/ConferenceUrl.js] <e>:  "Stored original conference URL: https://meet.jit.si/CosmoPol1"(source inconnue)
[modules/URL/ConferenceUrl.js] <e>:  "Conference URL for invites: https://meet.jit.si/CosmoPol1"(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/xmpp/strophe.jingle.js] <t>:  Configured STUN servers:  Array [ Object, Object, Object ](source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  (TIME) Strophe Attaching	:3282.495(source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  (TIME) Strophe attached:	 3285.37(source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  My Jabber ID: f8ce6ac2-bdc5-45e7-9c78-86744b6daa18@meet.jit.si/b166f261-4611-4977-82a5-35b5847a687a(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: Object, audio: Object }(source inconnue)
L’utilisation de l’attribut « nodeValue » d’un attribut est obsolète. Utiliser « value » à la place.app.bundle.min.js:2:2300681
NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onDataAvailable]WebRequest.jsm:223
Erreur de sécurité : le contenu situé à https://cdn.jitsi.net/2459/images/smileys/smiley8.svg a essayé de charger https://cdn.jitsi.net/2459/images/smileys/C639C8864CE51060.png, mais ne peut pas charger de données externes lorsqu’il est utilisé comme une image.Erreur de sécurité : le contenu situé à https://cdn.jitsi.net/2459/images/smileys/smiley8.svg a essayé de charger https://cdn.jitsi.net/2459/images/smileys/C639C8864CE51061.png, mais ne peut pas charger de données externes lorsqu’il est utilisé comme une image.[modules/RTC/RTCUtils.js] <E/<>:  Available devices:  Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ](source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/xmpp/strophe.ping.js] <f</<.value>:  XMPP pings will be sent every 10000 ms(source inconnue)
[react/features/analytics/functions.js] <a/<>:  Loaded 2 analytics handlers(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  Failed to get access to local media.  NotFoundError: The object can not be found here. [object Object] (source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio", "video" ] Object { gum: Object, name: "gum.not_found", message: "Requested device(s) was/were not fo…", stack: "e.exports/n.mediaDevices.getUserMed…" }app.bundle.min.js:2:707807

[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: false, audio: Object }(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  onUserMediaSuccess(source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio" ]
### TypeError: i.getSettings is not a function
Trace de la pile :
s/<@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:186863
s@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:186719
A</<.value/<@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:193351
T/</<@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:2364225
T/<@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:2364095
e.exports/l@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:1341117
app.bundle.min.js:2:707807

[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: Object, audio: false }(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  Failed to get access to local media.  NotFoundError: The object can not be found here. [object Object] (source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "video" ] Object { gum: Object, name: "gum.not_found", message: "Requested device(s) was/were not fo…", stack: "r@https://cdn.jitsi.net/2459/libs/l…" }app.bundle.min.js:2:707807

[conference.js] <t.a.init/<>:  initialized with %s local tracks 0(source inconnue)
[modules/xmpp/ChatRoom.js] <t>:  Joined MUC as cosmopol1@conference.meet.jit.si/f8ce6ac2(source inconnue)
[modules/connectivity/ParticipantConnectionStatus.js] <e>:  RtcMuteTimeout set to: 2000(source inconnue)
[modules/statistics/AvgRTPStatsReporter.js] <e>:  Avg RTP stats will be calculated every 15 samples(source inconnue)
[JitsiConference.js] <r>:  backToP2PDelay: 5(source inconnue)
[modules/remotecontrol/RemoteControl.js] <g</<.value>:  Initializing remote control.(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: false local audio: null audio devices: undefined device count: 0(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices: undefined device count: 0(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.setFocusUserJid>:  Focus jid set to:  undefined(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.createConferenceIq>:  Session ID: null machine UID: ced29acc81877a754ac6b804fe195ad7(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.setFocusUserJid>:  Focus jid set to:  focus@auth.meet.jit.si(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  Authentication enabled: false(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  External authentication enabled: false(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  Sip gateway enabled:  true(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: true local audio: null audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo] device count: 3(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices:  device count: 0(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  entered cosmopol1@conference.meet.jit.si/focus Object { show: "", affiliation: "owner", role: "moderator", jid: "focus@auth.meet.jit.si/focus1917885…", isFocus: true, isHiddenDomain: false }(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  Ignore focus: cosmopol1@conference.meet.jit.si/focus, real JID: focus@auth.meet.jit.si/focus191788501836(source inconnue)
[modules/UI/UI.js] <O.initEtherpad>:  Etherpad is enabled(source inconnue)
[modules/version/ComponentsVersions.js] <r.prototype.processPresence/<>:  Got xmpp version: Prosody(trunk nightly build 747 (2017-02-19, 428d4abee723),Linux)(source inconnue)
[modules/version/ComponentsVersions.js] <r.prototype.processPresence/<>:  Got focus version: JiCoFo(1.0.1.0-388,Linux)(source inconnue)
[modules/xmpp/recording.js] <i.prototype.handleJibriPresence>:  Handle Jibri presence : off null(source inconnue)
[conference.js] <t.a._setupListeners/<>:  Received recorder status change:  available undefined(source inconnue)
[conference.js] <t.a._setupListeners/<>:  My role changed, new role: moderator(source inconnue)
[JitsiConference.js] <r.prototype._maybeStartOrStopP2P>:  P2P? isModerator: true, peerCount: 0 => false(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  (TIME) MUC joined:	 11050.935(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  Subject is changed to (source inconnue)
[modules/UI/videolayout/LargeVideoManager.js] <k</<.value/<>:  hover in %s f8ce6ac2(source inconnue)
[modules/RTC/RTCUtils.js] <m>:  list of media devices has changed: Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ](source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: false, audio: Object }(source inconnue)
[modules/statistics/CallStats.js] <f</<.value>:  CallStats Status: err=success msg=SDK authentication successful.(source inconnue)
TURNS is not yet supported.callstats-ws.min.js:21
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  onUserMediaSuccess(source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio" ]
### TypeError: i.getSettings is not a function
Trace de la pile :
s/<@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:186863
s@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:186719
A</<.value/<@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:193351
T/</<@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:2364225
T/<@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:2364095
e.exports/l@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:1341117
app.bundle.min.js:2:707807

[conference.js] <t.a._onDeviceListChanged/<>:  Audio mute: device list changed(source inconnue)
[conference.js] <t.a._onDeviceListChanged/<>:  Video mute: device list changed(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: true local audio: null audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo] device count: 3(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices:  device count: 0(source inconnue)
NotFoundError: The object can not be found here.lib-jitsi-meet.min.js:2
[modules/RTC/RTCUtils.js] <m>:  list of media devices has changed: Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ](source inconnue)
[conference.js] <t.a._onDeviceListChanged/<>:  Audio mute: device list changed(source inconnue)
[conference.js] <t.a._onDeviceListChanged/<>:  Video mute: device list changed(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: true local audio: null audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo] device count: 3(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices:  device count: 0(source inconnue)
OpenGL compositor Initialized Succesfully.
Version: 1.4 APPLE-1.6.36
Vendor: Intel Inc.
Renderer: Intel GMA 950 OpenGL Engine
FBO Texture Target: TEXTURE_2D
[modules/statistics/CallStats.js] <f</<.value>:  CallStats Status: err=httpError msg=Connection to the server closed.(source inconnue)
downloadable font: download failed (font-family: "Open Sans" style:normal weight:600 stretch:normal src index:2): status=2152398850 source: moz-extension://009b18e9-2371-ef4e-89de-362cff6656ad/app/fonts/opensans-semibold-latin.woff2panel.css:1:5047
[modules/xmpp/xmpp.js] <w</<.value>:  (TIME) Strophe disconnecting:	 130347.24500000001(source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  (TIME) Strophe disconnected:	 130441.76000000001(source inconnue)
[modules/xmpp/strophe.ping.js] <f</<.value>:  Ping interval cleared(source inconnue)
(TIME) index.html loaded:	 397.23CosmoPol1:9:9
(TIME) Sending external connect XHR:	 612.42external_connect.js:65:5
[modules/RTC/RTCBrowserType.js] <o>:  This appears to be Firefox, ver: 48(source inconnue)
(TIME) external connect XHR done:	 987.335external_connect.js:40:13
DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
 t.default@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:60998app.bundle.min.js:2:221934
[react/index.web.js] <>:  (TIME) document ready:	 3923.63(source inconnue)
[react/features/base/media/middleware.js] <t>:  Start muted: (source inconnue)
[react/features/base/media/middleware.js] <t>:  Start audio only set to false(source inconnue)
[modules/URL/ConferenceUrl.js] <e>:  "Stored original conference URL: https://meet.jit.si/CosmoPol1"(source inconnue)
[modules/URL/ConferenceUrl.js] <e>:  "Conference URL for invites: https://meet.jit.si/CosmoPol1"(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/xmpp/strophe.jingle.js] <t>:  Configured STUN servers:  Array [ Object, Object, Object ](source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  (TIME) Strophe Attaching	:4708.745(source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  (TIME) Strophe attached:	 4712.7300000000005(source inconnue)
[modules/xmpp/xmpp.js] <w</<.value>:  My Jabber ID: 28fd6978-048f-4383-9940-941295851151@meet.jit.si/0350e8df-c953-491e-a27a-e36703c7eabd(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: Object, audio: Object }(source inconnue)
GET 
https://cdn.jitsi.net/2459/ [HTTP/2.0 403 Forbidden 27 ms]
L’utilisation de l’attribut « nodeValue » d’un attribut est obsolète. Utiliser « value » à la place.app.bundle.min.js:2:2300681
NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onDataAvailable]WebRequest.jsm:223
[modules/xmpp/strophe.ping.js] <f</<.value>:  XMPP pings will be sent every 10000 ms(source inconnue)
[modules/RTC/RTCUtils.js] <E/<>:  Available devices:  Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ](source inconnue)
[react/features/analytics/functions.js] <a/<>:  Loaded 2 analytics handlers(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  Failed to get access to local media.  NotFoundError: The object can not be found here. [object Object] (source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio", "video" ] Object { gum: Object, name: "gum.not_found", message: "Requested device(s) was/were not fo…", stack: "e.exports/n.mediaDevices.getUserMed…" }app.bundle.min.js:2:707807

[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: false, audio: Object }(source inconnue)
[modules/RTC/RTCUtils.js] <m>:  list of media devices has changed: Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ](source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  onUserMediaSuccess(source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "audio" ]
### TypeError: i.getSettings is not a function
Trace de la pile :
s/<@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:186863
s@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:186719
A</<.value/<@https://cdn.jitsi.net/2459/libs/lib-jitsi-meet.min.js?v=2459:2:193351
T/</<@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:2364225
T/<@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:2364095
e.exports/l@https://cdn.jitsi.net/2459/libs/app.bundle.min.js?v=2459:2:1341117
app.bundle.min.js:2:707807

[modules/RTC/RTCUtils.js] <me</<.value>:  Using the new gUM flow(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/i<>:  Got media constraints:  Object { video: Object, audio: false }(source inconnue)
[modules/RTC/RTCUtils.js] <me</<.value/</<>:  Failed to get access to local media.  NotFoundError: The object can not be found here. [object Object] (source inconnue)
[react/features/base/tracks/functions.js] <r/<>:  Failed to create local tracks Array [ "video" ] Object { gum: Object, name: "gum.not_found", message: "Requested device(s) was/were not fo…", stack: "r@https://cdn.jitsi.net/2459/libs/l…" }app.bundle.min.js:2:707807

[conference.js] <t.a.init/<>:  initialized with %s local tracks 0(source inconnue)
[modules/xmpp/ChatRoom.js] <t>:  Joined MUC as cosmopol1@conference.meet.jit.si/28fd6978(source inconnue)
[modules/connectivity/ParticipantConnectionStatus.js] <e>:  RtcMuteTimeout set to: 2000(source inconnue)
[modules/statistics/AvgRTPStatsReporter.js] <e>:  Avg RTP stats will be calculated every 15 samples(source inconnue)
[JitsiConference.js] <r>:  backToP2PDelay: 5(source inconnue)
[modules/remotecontrol/RemoteControl.js] <g</<.value>:  Initializing remote control.(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: false local audio: null audio devices: undefined device count: 0(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices: undefined device count: 0(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.setFocusUserJid>:  Focus jid set to:  undefined(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.createConferenceIq>:  Session ID: null machine UID: ced29acc81877a754ac6b804fe195ad7(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.setFocusUserJid>:  Focus jid set to:  focus@auth.meet.jit.si(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  Authentication enabled: false(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  External authentication enabled: false(source inconnue)
[modules/xmpp/moderator.js] <i.prototype.parseConfigOptions>:  Sip gateway enabled:  true(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: true local audio: null audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo] device count: 3(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices:  device count: 0(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  entered cosmopol1@conference.meet.jit.si/focus Object { show: "", affiliation: "owner", role: "moderator", jid: "focus@auth.meet.jit.si/focus1917885…", isFocus: true, isHiddenDomain: false }(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  Ignore focus: cosmopol1@conference.meet.jit.si/focus, real JID: focus@auth.meet.jit.si/focus191788501836(source inconnue)
[modules/UI/UI.js] <O.initEtherpad>:  Etherpad is enabled(source inconnue)
[modules/version/ComponentsVersions.js] <r.prototype.processPresence/<>:  Got xmpp version: Prosody(trunk nightly build 747 (2017-02-19, 428d4abee723),Linux)(source inconnue)
[modules/version/ComponentsVersions.js] <r.prototype.processPresence/<>:  Got focus version: JiCoFo(1.0.1.0-388,Linux)(source inconnue)
[modules/xmpp/recording.js] <i.prototype.handleJibriPresence>:  Handle Jibri presence : off null(source inconnue)
[conference.js] <t.a._setupListeners/<>:  Received recorder status change:  available undefined(source inconnue)
[conference.js] <t.a._setupListeners/<>:  My role changed, new role: moderator(source inconnue)
[JitsiConference.js] <r.prototype._maybeStartOrStopP2P>:  P2P? isModerator: true, peerCount: 0 => false(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  (TIME) MUC joined:	 11558.395(source inconnue)
[modules/xmpp/ChatRoom.js] <w</<.value>:  Subject is changed to (source inconnue)
[modules/UI/videolayout/LargeVideoManager.js] <k</<.value/<>:  hover in %s 28fd6978(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
https://meet.jit.si/http-bind?room=cosmopol1 : Unable to run script because scripts are blocked internally.(source inconnue)
mal formé(source inconnue)
[modules/statistics/CallStats.js] <f</<.value>:  CallStats Status: err=success msg=SDK authentication successful.(source inconnue)
TURNS is not yet supported.callstats-ws.min.js:21
NotFoundError: The object can not be found here.lib-jitsi-meet.min.js:2
[modules/RTC/RTCUtils.js] <m>:  list of media devices has changed: Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ](source inconnue)
[conference.js] <t.a._onDeviceListChanged/<>:  Audio mute: device list changed(source inconnue)
[conference.js] <t.a._onDeviceListChanged/<>:  Video mute: device list changed(source inconnue)
[conference.js] <t.a.updateAudioIconEnabled>:  Microphone button enabled: true local audio: null audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo] device count: 3(source inconnue)
[conference.js] <t.a.updateVideoIconEnabled>:  Camera button enabled: false local video: null video devices:  device count: 0(source inconnue)
[modules/statistics/CallStats.js] <f</<.value>:  CallStats Status: err=httpError msg=Connection to the server closed.

**Comment by bbaldino** [comment]
This is related to @virtuacoplenny 's work on the new constraints flows...this version of Firefox is quite old though, is there a reason you haven't updated (Firefox is on 57 now)

**Comment by SergioArbarviro** [comment]
My computer itself is rather old: 

- Intel Core Duo 1.66 GHz
- 2 Gbytes SDRAM
- Mac OS X 10.6.8 (10K549)
 
This explains why I have not been able to upgrade Firefox beyond the version that I indicated. Sorry about this.

I am afraid that all users were confronted with the same problem as me - and were most probably using much more recent versions of Firefox.

Do you have any idea of when @virtuacoplenny will have finished his work on the constraints flows, and how users will be informed? I am eager to be able to use the meet.jit.si service again!

**Comment by saghul** [comment]
Can't you at least use the latest ESR version, that is 52? I'm not sure if we have a strong line about what versions we support and which we don't, but WebRTC being (still) a moving target, supporting anything older than ESR may not be a priority.

**Comment by SergioArbarviro** [comment]
Indeed I cannot use this last ESR version Firefox 52.0esr, because [it requires Mac OSX 10.9 ](https://www.mozilla.org/en-US/firefox/52.0esr/system-requirements/) , and my OS is 10.6.8. I have no means to upgrade my system to Mac OSX 10.9. I apologise for this.

**Comment by crashla** [comment]
Same problem here in France, same conclusion, I was a daily user of jitsi during my projects in last autumn. I don't want to move for a less stable OS, 10 6 8 never crash. I use firefox 45 7 ESR, faster than 48.0.2. Could it be possible to have a jitsimeet instance running (few weeks ago)-old-style  ?

**Comment by saghul** [comment]
It's not that simple. While it might be fixable, support for an operating system and browser which are not supported by their respective manufacturers (OSX 10.16 is EOL, as is ESR < 52) doesn't rank high on the priority list. I'm really sorry, but keeping up with browser releases is a daunting task.

If you feel like digging in, fixing the bug and sending a PR, we could get some eyes on it.
