### ISSUE TITLE
Android code conflict

### ISSUE THREAD

**Issue by Ace2222** [jitsi/jitsi-meet#2216]
![image](https://user-images.githubusercontent.com/32385369/33255522-066ce1e2-d389-11e7-9c6a-c22e7dbbb064.png)

My project contains okhttp3.9.1, when I integrated jitsi Android sdk, the code conflicts, how to solve？

**Comment by saghul** [comment]
The Android SDK uses React Native, which in turn uses another version of okhttp. I'd say the simplest solution is for you to use the same version as React Native: https://github.com/facebook/react-native/blob/0.49-stable/ReactAndroid/build.gradle#L288 that is, 3.6.0.

**Comment by Ace2222** [comment]
The Android SDK uses React Native0.42.3,How to update it?

**Comment by saghul** [comment]
We have updated to 0.49 a while ago, have you updated your packages?

**Comment by Ace2222** [comment]
How to update the packages? The react-native version in jitsi-maven-repository is still 0.42.3
![image](https://user-images.githubusercontent.com/32385369/33296493-ef3b99da-d416-11e7-9f3b-996d6ac0ae3c.png)
https://github.com/jitsi/jitsi-maven-repository/blob/master/releases/org/jitsi/react/jitsi-meet-sdk/1.9.0/jitsi-meet-sdk-1.9.0.pom

**Comment by lyubomir** [comment]
We'll have to release a new binary in jitsi-maven-repository to get you on the latest react-native that we support. Alternatively and in the meantime, you may build a binary yourself by following https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build.

**Comment by Ace2222** [comment]
Thank you very much!
