### ISSUE TITLE
Jitsi meet. Couldn`t connect to the conference

### ISSUE THREAD

**Issue by FareeZz** [jitsi/jitsi-meet#2217]
I know there are a  lot of posts about this error. but i can`t relate to any of them. I dont get any console error`s and i don`t see anything weird in the error.log`s. The problem is that when i create a room it creates it but i dont see my webcam and microphone. and after a few minutes i get an error message saying `

> `Oops! Something went wrong and we couldn't connect to the conference: connection.otherError`

**Comment by saghul** [comment]
Are you running your own infrastructure or using meet.jit.si? What do you see on the JavaScript console (even if it's not an error)? What browser are you using?

**Comment by FareeZz** [comment]
@saghul i run jitsi on my own server. in my own infrastructure
![screenshot](https://user-images.githubusercontent.com/34023512/33259227-871a0e6e-d35c-11e7-87f6-0af2f9cbf60a.png)

**Comment by saghul** [comment]
is that everything you get in the logs?

**Comment by FareeZz** [comment]
@saghul Yes thats everything

**Comment by saghul** [comment]
Can you send me the URL of your deployment? (email is on my profile, if you don't want to post it here)

**Comment by FareeZz** [comment]
@saghul the url is jitsi.cns-it.local i host it local. My idea was that i could use this instead of teamviewer. i wasn`t planning it to be public.

**Comment by saghul** [comment]
I see. You'll need to gather the jvb and jicofo logs then. Also note that people won't be able to connect to your server unless you open it up...

**Comment by FareeZz** [comment]
@saghul i don`t neet to open it up for local use?

**Comment by saghul** [comment]
If you are going to use in a LAN then no.

**Comment by FareeZz** [comment]
@saghul 
![jicofolog](https://user-images.githubusercontent.com/34023512/33325249-067e5930-d452-11e7-828c-22936b8120b4.PNG)

> Jicofo log

![jvblog](https://user-images.githubusercontent.com/34023512/33325259-1092a62e-d452-11e7-88e1-f1eb54b45e40.PNG)

> Videobridge log

![prosodylog](https://user-images.githubusercontent.com/34023512/33325277-1b216b52-d452-11e7-8638-4f8c093e3065.PNG)

> Prosody log

This is everything what the logs say. Do you want screenshots of the configurations. is yes, What configs?

**Comment by damencho** [comment]
How did you install, were you using the debian packages?
If you were not, you need to fix the certificate for the auth.domain virtual host in prosody. This is normally taken care by the debian packages install or upgrade.
To fix it manually you can take a look at the script that takes care of it:
https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L125

**Comment by damencho** [comment]
The comment above was for the jicofo error.

About the jvb one, you are passing an address that is not DNS resolvable as host parameter when starting jvb, by default this is localhost.

**Comment by FareeZz** [comment]
@damencho Thanks for the reply, i checked the directory of the certificate location and it is there. But when i installed jitsi of run the script i got an error so i created the certificate manually. Is that a problem

**Comment by FareeZz** [comment]
@damencho The jitsi-videobridge error is fixed so thanks for that. But i stil have the jicofo error

**Comment by damencho** [comment]
Did you do and:

`ln -sf /var/lib/prosody/$JICOFO_AUTH_DOMAIN.crt /usr/local/share/ca-certificates/$JICOFO_AUTH_DOMAIN.crt

update-ca-certificates`
?

What was the error if you remember?

**Comment by FareeZz** [comment]
@damencho The error was `Name does not end in a public suffix`

**Comment by FareeZz** [comment]
@damencho i executed the command you said. but now when i join my room i get a login page. and when i login i imediatly get kicked out

**Comment by damencho** [comment]
Can you check the js console logs, and maybe and jicofo logs is there something?

**Comment by FareeZz** [comment]
![jicofo](https://user-images.githubusercontent.com/34023512/33425964-9ab19382-d5c0-11e7-8cf5-7c92a1973719.PNG)
![jvb](https://user-images.githubusercontent.com/34023512/33425965-9acf7348-d5c0-11e7-94d4-573dda963988.PNG)
![prosody](https://user-images.githubusercontent.com/34023512/33425966-9aec8226-d5c0-11e7-92e6-9cb36244ddae.PNG)

**Comment by damencho** [comment]
Wrong prosody config you can see this in all of your messages that you send it.
auth.jitsi....local is not defined as a virtual host in your prosody config.
jitsi-videobridge.jitsi....local is not defined in prosody config.

For future, please do not attach screenshots. Upload logs files somewhere and paste links, or paste directly the log fragments here. There is a nice editor in which you can click code and paste it, so it can be nice formatted. Its hard to read screenshots, and I cannot copy anything from it to show you. Make life easier for those that you want to help you.

I suggest using the debian packages, to save you from all this hassle.

**Comment by FareeZz** [comment]
@damencho Thanks for all the info. Would you think if it would be better if i start over from scratch?

**Comment by damencho** [comment]
If you will move from manual install to quick install, this will mean you are starting from scratch.

**Comment by FareeZz** [comment]
@damencho I will do that. Thanks for al the help and support! If i run into problems again i will use the mailing list
