### ISSUE TITLE
Problem with last update

### ISSUE THREAD

**Issue by arnoooooo** [jitsi/jitsi-meet#2218]
Hi

I tried to update my jitsi-meet today (Debian 8) seems no problem. But when i go to my jitsi URL, impossible to use video conferencing (purple screen). So, i tried to reinstall all my server and jitsi (apt-get install jitsi-meet). But i have this problem and i can't install it :
jitsi-meet : Depends: jitsi-videobridge (= 1011-1) but will not be installed
              Depends: jicofo (= 1.0-388-1) but will not be installed

Is someone can help me ?

Thanks.

**Comment by damencho** [comment]
Do you have java8 installed?

For the problem of no conference, can you check jicofo, jvb and javascript logs there should be some info about the problem?

**Comment by arnoooooo** [comment]
It is necessery to oracle-java8-installer or just default-jre ? With older version it was not.

**Comment by damencho** [comment]
We started switching to java8, so it is a requirement for the new versions.

**Comment by arnoooooo** [comment]
Ok. Thanks. I will try with oracle-java8-installer.
