### ISSUE TITLE
Browser not requesting to use Camera and Mic Permissions when embedded on page

### ISSUE THREAD

**Issue by jpotts-IIL** [jitsi/jitsi-meet#2225]
When using Jitsi Meet for conference calls in Rocket Chat, it does not work unless it is used in a new window. When the video chat is embedded in the Rocket Chat page, Jitsi opens with two errors: "Failed to access your microphone" and "Failed to access your camera". Jitsi is open, but with no video or audio. Furthermore, there is no way for me to grant the page permissions to use Camera or Microphone (tested in Chrome and Firefox).
However, if I choose the Admin option to have Jitsi open in a new window, the popup requests permissions for Jitsi and it works fine.
How do I use Jitsi embedded in the page?

**Comment by bbaldino** [comment]
Is this chrome 63? If so, it might be due to this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/32natnrbP6U/0dgpWLMkAwAJ

**Comment by jpotts-IIL** [comment]
No, it is Chrome Version 62.0.3202.94

**Comment by saghul** [comment]
Can you spot any errors in the JS console?

**Comment by jpotts-IIL** [comment]
There are a few errors, but these ones are the first and I suspect the relevent ones: [Errors](https://i.imgur.com/0kMua2v.png)

**Comment by saghul** [comment]
Any chance you are using HTTP and not HTTPS? WebRTC requires a secure origin, thus HTTPS.

**Comment by jpotts-IIL** [comment]
Yeah, the page its embeded in is HTTP. Ill check about getting it in HTTPS to see if that fixes it. Thanks.

**Comment by saghul** [comment]
Cool. I'm closing this then, cheers!
