### ISSUE TITLE
Run jitsi-meet at suburl via apache reverse-proxy

### ISSUE THREAD

**Issue by skug67** [jitsi/jitsi-meet#223]
Rather than create a dedicated http subdomain for jitsi-meet (e.g., jitsi-meet.my.domain), I would rather access it via a suburl from my existing website (e.g. www.my.domain/jitsi-meet).  And I currently host my site using apache, not nginx.  Other than figuring out the proper rewrite rules for apache from what's currently in nginx (which I _might_ be able to do), how much else would be involved -- for example, to what extent is a root url ("/") hard coded into any of the javascripts.

Is what I'm trying to accomplish do-able relatively easily?

**Comment by fippo** [comment]
check if the getroomnode function as part of the config (https://github.com/jitsi/jitsi-meet/blob/master/config.js#L11) still works. Extract your room from the path component inside.

**Comment by skug67** [comment]
How would I go about doing that?  I can see that the function is commented out in the default config, and it would be easy enough to reactivate it.  But what do you mean by "extract your room from the path component inside"?  (Sorry to be dense, but I'm barely competent with server config files (even that might be overstating my skills) and pretty much useless when it comes to actual coding.

**Comment by Zalmoxisus** [comment]
Yes, it works, I used it few days ago for testing.

Just use something like that:
getroomnode: function (path) { return
location.pathname.replace('/jitsi-meet',''); },

Regards,
Zalmoxisus

**Comment by cpnadal** [comment]
Hi skug67, have you been able to fix your issue? If yes, could you please tell me how?

Many thanks,

Cyrille

**Comment by skug67** [comment]
Sorry.  Messed around w/it a little bit but never got it working.

Quoting cpnadal <notifications@github.com>:

> Hi skug67, have you been able to fix your issue? If yes, could you
> please tell me how?
>
>   Many thanks,
>
>   Cyrille
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/jitsi/jitsi-meet/issues/223#issuecomment-72919393

**Comment by pb13** [comment]
Hi, I got this working in a subdirectory with apache.

The following parameter needs to be set in the jitsi-meet config.js:
```
getroomnode: function (path) { return location.pathname.replace('/meet/',''); },
```

The following apache configuration works in a virtualhost block:
```
RewriteEngine On
RewriteCond %{REQUEST_URI} ^/meet/[a-zA-Z0-9]+$
RewriteRule ^/meet/(.*)$ /meet/ [PT]

ProxyPreserveHost Off

<Location "/meet/http-bind">
    RequestHeader set Host "jitsi.domain.tld"
    ProxyPass http://jitsi.domain.tld:5280/http-bind
    ProxyPassReverse http://jitsi.domain.tld:5280/http-bind
</Location>
<Location "/meet/xmpp-websocket">
    ProxyPass http://jitsi.domain.tld:5280
    ProxyPassReverse http://jitsi.domain.tld:5280
</Location>
```

**Comment by dmwaren** [comment]
Hi,

I am trying to make jitsi meet working on apache server by the suburl "/meet" but i only get the index.html view without possibility to load a room.

First i proceeded a package install, stopping nginx and configuring apache virtualhost with parameters given by pb13. After a lot of test, i uninstalled all packages to try a manuel install, but the result is the same.

I installed jitsi-videobridge and jicofo. Jicofo is not launched automatically but i managed to make it work for my tests. I have renowned "jitsi-meet" directory sources for "meet" and put it on my apache DocumentRoot directory.

My last solution will be running nginx on another port (with the proper default configuration for jitsi) and making a proxy on apache for enable jitsi on port 443. But nginx doesn't have much more features than apache so I think apache is able to make jitsi-meet work without nginx, don't you think the same ? Maybe a module for apache is missing ?

I have the same apache configuration than pb13. I am running a Debian Jessie server with apache 2.4.10, NodeJS 0.12 is installed and the firewall is disable (this is a test server). I enabled headers, proxy-http, ssl and rewrite module.

Does anyone can help me to make it work with apache please ? I doesn't write often in english, i am sorry.

**Comment by aroquen** [comment]
How should one deal with xmpp components like `conference.jitsi.example.com`, `jitsi-videobridge.jitsi.example.com` etc in the suburl scenario?

**Comment by bgrozev** [comment]
These are within XMPP and there shouldn't be any changes necessary.
