### ISSUE TITLE
Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by db-007** [jitsi/jitsi-meet#2234]
I am seeing this error on Windows 10 "Could not get BatchedBridge, make sure your bundle is packaged correctly".  Existing issue was closed without being resolved [(https://github.com/jitsi/jitsi-meet/issues/1800)](https://github.com/jitsi/jitsi-meet/issues/1800) because of missing information.
But the steps to reproduce it are simple:

1. Clone this repo [https://github.com/JamesMarino/Firebase-ReactNative](https://github.com/JamesMarino/Firebase-ReactNative)
2. issuing react-native run-android threw this error in emulator, so I dropped node_modules completely and from proj dir, issued npm i
3. Open Android emulator
4. do react-native run-android
5. project builds successfully, app is started on emulator and error shows
6. reload on emulator shows error again

This is happening on Windows 10, I have installed very latest Android Studio (today).

I also tried issuing:

- from my Android\sdk\platform-tools following: `reverse tcp:8081 tcp:8081` but no effect.
- react-native start from proj root
- react-native start --reset-cache from proj root
- $ react-native start > /dev/null 2>&1 & 
 $ curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"
  $ (cd android/ && ./gradlew assembleDebug)

None of this helped, still same issue. 

Windows 10
Android Studio 3.0.1
npm 5.5.1
node 8.2.1
react-native-cli 2.0.1
react-native 0.32.0

![batchedbridge](https://user-images.githubusercontent.com/17257073/33341073-a1ccf3f8-d432-11e7-9f1b-3716b7b1ceab.png)

**Comment by saghul** [comment]
I don't understand. What does your project have to do with Jitsi Meet? You are not using it AFACT.  Your problem seems to be related to React Native itself, not to our project in particular.

Can you please clarify?

Also note: we do not develop on Windows, so if there is something on **our** project which does not work, we'll take patches but we can't work on a fix for it ourselves.

**Comment by db-007** [comment]
Just close it, you are correct, I am not using it; mistakenly landed on here and posted based on other question.  Thanks
