### ISSUE TITLE
Video is black

### ISSUE THREAD

**Issue by Ace2222** [jitsi/jitsi-meet#2235]
I integrated the android sdk into rocket chat project, the video interface is black when I open the video.But in the other project, it is ok. why???

![image](https://user-images.githubusercontent.com/32385369/33419622-2bce4548-d5e6-11e7-8a9c-67685b2dba8e.png)

**Comment by saghul** [comment]
Your server seems to be configured incorrectly. When I access https://cc.nomalis.com/config.js I get back HTML, instead of the JS configuration.
