### ISSUE TITLE
Not working with node.js 8

### ISSUE THREAD

**Issue by sapkra** [jitsi/jitsi-meet#2237]
I'm getting an error because the `node-sass` version 3.13.1 is no compatible with node.js 8.

> Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node"
> 
> HTTP error 404 Not Found

More information you can find [here](https://github.com/sass/node-sass/issues/2034).

**Comment by sachinrkeche** [comment]
@sapkra ,this issue with sass , not supporting the latest node version,  try to build it on v6 will definitely build.

**Comment by sapkra** [comment]
I think if you update `node-sass` to a newer version then it will be compatible with node 8.

**Comment by dvn0** [comment]
I ran into this problem as well. Is there a good reason that `node-sass` is still at version **3.13.1**? It seems to be the only thing keeping us from using **Node 8**.

I changed node-sass to version **4.5.3** and `npm install` runs successfully. Can we go forward with applying this dependency upgrade?

**Comment by dvn0** [comment]
It should be noted that when using nodejs built with musl (as is the case by default with Alpine Linux for example) node-sass _only_ works with `Node 8` and above, so this dependency upgrade would broaden the platform compatibility.
