### ISSUE TITLE
[feature request] Fullscreen screensharing in Firefox currently not possible

### ISSUE THREAD

**Issue by foss-** [jitsi/jitsi-meet#2240]
Currently only single windows can be shared. there are many use cases where the best option is to share the entire screen. from what I understand this would require having a jitsi extension for firefox. sharing fullscreen in chromium is possible using the chrome extension.

Fullscreen screensharing has never been possible using Firefox and is not working in Firefox 57.0.1 (current stable) or nightly from 2017-12-01.

This is a new, clean ticket and follow up to https://github.com/jitsi/jitsi-meet/issues/1910 which digressed.

**Comment by bgrozev** [comment]
To clarify: there is NO need for an extension. What we need is a UI to select between the "screens" and "applications" modes of the Firefox picker.

**Comment by bgrozev** [comment]
There is ongoing work in firefox for supporting the latest gUM spec for screen capture, which includes the change that we need: https://bugzilla.mozilla.org/show_bug.cgi?id=1321221

Thanks to @nils-ohlmeier for pointing this out.

**Comment by martinszy** [comment]
Sorry I'm not sure this is the best place to ask, but do we have a FF58 compatible extension working already? In which version of jitsi? Can I install it even if my host has not updated yet?

**Comment by saghul** [comment]
@martinszy There is no need for an extension on Firefox >= 52.

**Comment by martinszy** [comment]
Hmm... so why is this?
![imagen](https://user-images.githubusercontent.com/997732/36047431-d89d84c6-0dba-11e8-9c65-bba984619caf.png)

**Comment by bgrozev** [comment]
Probably because the jitsi-meet installation is misconfigured. Where do you see this?

**Comment by martinszy** [comment]
It's a custom installation... which configuration parameters would fix that?

**Comment by saghul** [comment]
Look at these: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L153-L168

**Comment by ksast** [comment]
I can confirm this behavior.
Firefox 63.0.3, Windows 7

**Comment by foss-** [comment]
see https://github.com/jitsi/jitsi-meet/issues/1910#issuecomment-453131925 and https://github.com/jitsi/jitsi-meet/issues/1910#issuecomment-453073396

Works as expected in Firefox 66 (nightly as of today). Closing this bug, re-open if you disagree.

**Comment by saghul** [comment]
@foss- Thanks for the heads up! I teste it and it's there! It's so good to finally have this!
