### ISSUE TITLE
I have issue with react packager has encountered an internal error 

### ISSUE THREAD

**Issue by abisanth** [jitsi/jitsi-meet#2241]
I have installed react native dependencies instead of jitsi sdk ios, but it showing react packager has encountered an internal error,  Please check below screen shot and let me know  how can i fix the issue.

![Uploading Screen Shot 2017-12-02 at 1.13.30 PM.png…]()

Thanks,

**Comment by lyubomir** [comment]
@abisanth, unfortunately, 'Uploading Screen Shot 2017-12-02 at 1.13.30 PM.png…' doesn't lead to a screenshot (but rather to this PR). Please provide the output associated with the error you're reporting so that we have a chance to assist you.

**Comment by lyubomir** [comment]
Additional information was requested more than eight months ago. Anyway, the initial report didn't give us anything to work with. So we're better off closing this issue I presume.
