### ISSUE TITLE
I am getting issue on top of the home page while loading

### ISSUE THREAD

**Issue by sraja415** [jitsi/jitsi-meet#2247]
Whenever I am running jitsi app front screen its coming like this
   "Downloading javascript bundle 100%".

Can you explain me pls.

Thanks,

**Comment by lyubomir** [comment]
I presume you're talking about Jitsi Meet for Android or iOS? Which OS exactly? Are you building the app yourself and deploying it to your device or did you download it from the AppStore or Google Play Store? Which version is the app you're reporting? If you're building it from source code, then which commit hash is jitsi-meet at?

**Comment by lyubomir** [comment]
Additional information was requested more than eight months ago. On top of that, the report just states "standard" behavior for a Debug build of Jitsi Meet app and SDK for Android and iOS so we're unlikely to do anything about it.
