### ISSUE TITLE
quick install not working

### ISSUE THREAD

**Issue by tanvir23** [jitsi/jitsi-meet#2248]
i am using fresh ubuntu 14.04, when i use the quick install guide i get the following message,

$ apt-get install jitsi-meet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-videobridge (= 1011-1) but it is not going to be installed
              Depends: jicofo (= 1.0-388-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

how can i fix it?

**Comment by damencho** [comment]
Install java8 packages as they are a requirement now. And then install jitsi-meet.

**Comment by tanvir23** [comment]
ok i will try...thanks...

**Comment by neodev2** [comment]
@tanvir23 I had your exact problem, I solved doing:

```
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo nano /etc/environment
added this line at the end of the file -> JAVA_HOME="/usr/lib/jvm/java-8-oracle"
source /etc/environment
apt-get install jitsi-meet
... etc
```

**Comment by roeycohen** [comment]
hi, this source helped me with debian 14 (jessie) as recommended in the guide:
https://xmoexdev.com/wordpress/installing-openjdk-8-debian-jessie/
