### ISSUE TITLE
No video and audio when 3 or more participants

### ISSUE THREAD

**Issue by ksrichard** [jitsi/jitsi-meet#2254]
So I have a setup on kubernetes with prosody, jicofo, jitsi-meet-web and jitsi-videobridge. The communication between service works fine and with 2 participants it works fine.
BUT when a third participant is connecting to the meeting all the video and audio streams stops.
When someone leaves the meeting (so we have 2 participants again), everything gets back to work again.
Couuld you please help me to sort this out?

**Comment by damencho** [comment]
Can you attach the logs from the javascript console of one of the clients after the third joined, logs from jicofo and jvb.

**Comment by ksrichard** [comment]
here they are: 
[jicofo_log.txt](https://github.com/jitsi/jitsi-meet/files/1532172/jicofo_log.txt)
[jvb_log.txt](https://github.com/jitsi/jitsi-meet/files/1532173/jvb_log.txt)
[jitsi.default.srv.lango.today-1512493961312.log](https://github.com/jitsi/jitsi-meet/files/1532174/jitsi.default.srv.lango.today-1512493961312.log)

**Comment by damencho** [comment]
Are your running your jvb behind nat? If this is the case have you checked and setup this: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration ?

**Comment by ksrichard** [comment]
I am running it in kubernetes, on a pod

**Comment by damencho** [comment]
I have no experience with kubernetes. But does the jvb machine has its own public address?
I see jvb is sending candidates using only the 10.244.4.151, which is a private address and is not publicly available, you need some ports forwarding (tcp 4443 and udp 10000) and set up in jvb its public and private address as said in the link I sent you.

**Comment by ksrichard** [comment]
and videobridge is listening on port 4443 tcp?

**Comment by damencho** [comment]
Yep, this is the default tcp port. It is better to use port 443 to be able to use one some restricted networks. But if you already have a web server running on the same machine as jvb and it is using port 443, then jvb uses port 4443.
There are three options, install jitsi-meet without a web server (no nginx or apache2 installed on the machine), this way jitsi-meet will configure using internal jetty in jvb and will use port 443 for both content serving and media. The other option is moving jvb on another machine and install and configure with authbind bind allowing it to use privileged port 443. And the last one is to have two public ip-addresses there and configure jvb to use one interface and webserver to use the other one.
There is some documentation here: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md

**Comment by ksrichard** [comment]
and if I have a separated public IP for UDP 10000 and another for having TCP 4443, what should I configure then?

**Comment by damencho** [comment]
You should use the same public ip address for all the traffic to jvb.

**Comment by ksrichard** [comment]
So I've been setup the box with input port TCP 4443 and UDP 10000, configured with these properties:
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.prosody.default.srv.lango.today/.*
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=52.166.90.227
org.jitsi.videobridge.TCP_HARVESTER_PORT=4443
org.jitsi.videobridge.TCP_HARVESTER_MAPPED_PORT=4443

BUT got these error messages constantly:
JVB 2017-12-05 20:30:19.682 INFO: [52] org.ice4j.ice.harvest.AbstractTcpListener.readFromChannel() Failed to handle TCP socket Socket[addr=/10.240.0.4,port=60586,localport=4443]: End of stream!
JVB 2017-12-05 20:30:19.727 INFO: [52] org.ice4j.ice.harvest.AbstractTcpListener.readFromChannel() Failed to handle TCP socket Socket[addr=/10.240.0.6,port=51905,localport=4443]: End of stream!

**Comment by bgrozev** [comment]
This is most likely due to something else (not a browser doing ICE/TCP) connecting to the bridge at port 4443.

**Comment by bgrozev** [comment]
To clarify: with the setup described above you should still access the web application on port 443. Port 4443 will be used by videobridge for media traffic (and only as a fallback if UDP/10000 doesn't work).

**Comment by ksrichard** [comment]
btw now I have been setup again jitsi, everything seems works fine, but now on chrome I got a blank grey page and no error logs in js console

**Comment by ksrichard** [comment]
okay, the grey screen error has been sorted out, but still has no capability to have 3 or more participants, but all of the inbouund and outbound UDP/TCP ports are enabled. I'm using azure

**Comment by damencho** [comment]
@kkrisstoff so you have port forward udp/tcp and you have setup private and public address in the jvb config? If you think all this is ok, can you send me again the logs so I can take a look, or maybe a link to your deployment so I can test it...

**Comment by ksrichard** [comment]
it started working, something was wrong I think with port filtering, so thanks a lot for the fast support! :)

**Comment by eloo** [comment]
@ksrichard would you like to share your k8s setup for jitsi?

**Comment by schlomo** [comment]
👍 for sharing the K8S manifests 😄

**Comment by vavadiyahiren** [comment]
@ksrichard  facing the same problem which solution works for you can you please help ?

**Comment by bonduu01** [comment]
Facing same problem on docker, used the docker-compose.yaml file for deployment.
