### ISSUE TITLE
Need to disable debug mode in ios jitsi

### ISSUE THREAD

**Issue by sraja415** [jitsi/jitsi-meet#2255]
![img_0120](https://user-images.githubusercontent.com/17216161/33610828-82202320-d9f2-11e7-9871-d91eb64709b2.PNG)
Hi,

      I need to disable debug mode while running jitsi source code sdk latest version 1.9 ios app.
      Running with MacOS Sierra version 10.12.6 & iphone device also Simulator.
      Please check with this below screenshots, it is coming like this.., 
      Kindly clarify me. how to fix it.

Thanks.,
![img_0117](https://user-images.githubusercontent.com/17216161/33608582-fbfa086c-d9ea-11e7-889a-580d380e3fd0.PNG)
![img_0119](https://user-images.githubusercontent.com/17216161/33608584-fdb329ae-d9ea-11e7-93fd-7ad692a9c7fc.PNG)

**Comment by lyubomir** [comment]
It's really a react-native question and the answer should be easy to google. When you build your app in the Release configuration, the yellow and red screens will not be displayed.

Additionally, you may search our source code for `disableYellowBox` and set this variable to `false` in the source code for the app to make an attempt to reduce the number of yellow and red boxes displayed in the Debug configuration.

**Comment by sraja415** [comment]
Yes, I have changed default debug mode disable settings in xcode (debug configuration) which i have attached screen shot, 
Let will check this functionality once will taken build the app.

Thanks.,
![screen shot 2017-12-06 at 11 23 18 am](https://user-images.githubusercontent.com/17216161/33646877-014a7d28-da78-11e7-8ab3-ac592a20f212.png)
