### ISSUE TITLE
[iOS] Not able to connect to our server instead of "meet.jit.si"

### ISSUE THREAD

**Issue by asshewale** [jitsi/jitsi-meet#2257]
Hi Devs. We want to implement the video conference, for that we found Jitsi, we tried the JItsi clone from [Jitsee Git](https://github.com/jitsi/jitsi-meet) and we really loved the way it works.. We then decided to integrate the Jitsi in our own application with our server instead of meet.jit.si, for that we followed the steps given under [Jitsi Meet SDK for iOS](https://github.com/jitsi/jitsi-meet/tree/master/ios) 
We have provided our server's URL to the method "objJitsiMeetView.loadURLString" like "objJitsiMeetView.loadURLString("https://cvideo.mvoip.com")" , But somehow we are not able to redirect or connect to our server its steel redirecting or connecting to meet.jit.si not to our server. 
 
**_What steps do we need to follow or at which places do i need to do the changes, if we want to connect to our server instead of Jitsi.._** 
> What we have done is :=> We have created one ViewController named "JitsiViewController.swift" with in that we have one view to which we have assigned the class "JitsiMeetView" as per the guide, and the psuedo code is as below... 

`import UIKit
import JitsiMeet

class JitsiViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let objJitsiMeetView: JitsiMeetView  = (self.view as? JitsiMeetView)!
        objJitsiMeetView.delegate = self as? JitsiMeetViewDelegate
        objJitsiMeetView.welcomePageEnabled = true
        objJitsiMeetView.loadURLString("https://cvideo.mvoip.com")
        objJitsiMeetView.accessibilityActivate()
 }
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}`

> Your any help will be highly appreciated, Please we are struggling on same issue from more than a week of time..

**Comment by saghul** [comment]
Does your deployment work when using it from a browser? I tried it but it doesn't seem to work.

> objJitsiMeetView.welcomePageEnabled = true

If you are using the SDK embedded in your app, you probably want to leave this as false.

**Comment by asshewale** [comment]
Hi @saghul Thank you for your valuable time, 
Yes our deployment works hen using it from a browser, And the URL i have provided in question is not the real URL, Our server's real URL is : https://ctsivideo.mvoipctsi.com.

And yes as we are using the SDK embedded in our app, i tried objJitsiMeetView.welcomePageEnabled = false , but its displays the black screen, not shows anything after landing to JitsiViewController.

My question is if we want to use our server instead of meet.jit.si then whether we only need to provide our url to the method objJitsiMeetView.loadURLString ...? is this the only place where i need to change the thing (URL) or is there are any other places or steps i have to follow to use our server. ?? Will yoiu please correct me. i am really struggling hard to get it done..

**Comment by saghul** [comment]
> Our server's real URL is : https://ctsivideo.mvoipctsi.com.

Got it.

> And yes as we are using the SDK embedded in our app, i tried objJitsiMeetView.welcomePageEnabled = false
> but its displays the black screen, not shows anything after landing to JitsiViewController.

That is expected, to a degree. When no welcome page is used, we show a "blank" page when not in a conference. You then need to use the delegate methods for deciding when to hide the view, usually when the conference fails or ends.

> My question is if we want to use our server instead of meet.jit.si then whether we only need to provide our url to the method "objJitsiMeetView.loadURLString" ? is this the only place where i need to change the thing (URL) or is there are any other places or steps i have to follow to use our server. ??

That should be enough. You can, however, set the default URL and then just use the room name in loadURLString`: https://github.com/jitsi/jitsi-meet/tree/master/ios#defaulturl

Does Safari load you deployment correctly? Sometimes there might be issues related to TLS certificates. Since we don't provide any cert store iOS itself needs to be able to access it directly.

**Comment by asshewale** [comment]
>That is expected, to a degree. When no welcome page is used, we show a "blank" page when not in a conference. You then need to use the delegate methods for deciding when to hide the view, usually when the conference fails or ends.

Means what exactly should i do/implement, whether i should implement the delegate methods in JitsiViewController..? 
My problem is i am integrating the Jitsi in Rocket chat, where Rocket chat is in swift and Jitsi is in Objective c, so the Jitsi's methods conversion has became a challange for me in Rocket chat...

**Comment by saghul** [comment]
You should implement the following methods from the delegate: https://github.com/jitsi/jitsi-meet/tree/master/ios#jitsimeetviewdelegate

- conferenceFailed
- conferenceLeft
- loadConfigError

What you want to do in those cases is hide the controller, since the JitsiMeetView will be displaying a black / empty view.

**Comment by asshewale** [comment]
Hi @saghul  can we have that delegate methods in swift. if possible please.

**Comment by lyubomir** [comment]
Hey, @asshewale, here's the Objective-C header file which you may consume in your Swift source code: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/JitsiMeetViewDelegate.h

**Comment by asshewale** [comment]
Thanks @lyubomir i will integrate the file in my code. thanks again

**Comment by asshewale** [comment]
@saghul  @lyubomir  Hi , i succeeded to connect to our server. 

Scenario is we have integrated Jitsi in Rocket chat. 
So on the chat screen of Rocket chat we added one video call button on top, so if two users are chatting with each other and they want to have a video call between them one user can initiate a video call on tapping of video button while chatting with other user, and at that event i am sending a chat message to other user programatically that he has received a video call please tap on video icon to connect , 

Now,  our server url is https://ctsivideo.mvoipctsi.com and i open a conference as https://ctsivideo.mvoipctsi.com/1010 as the conference id is static so two users or any users who will tap on video button will land in a same conference...

But when we want different sessions / conference we will have to create a random conference numbers and append to server url, in that case how could we let other user know about to joine the same conference,  

Please i am not able to get the way to connect the diffrent different people from different different rooms to have seperate conferences. 

Your help will be highly appreciated..

**Comment by saghul** [comment]
Excellend @asshewale, thanks for letting us know! I'm going to go ahead and close this then!

**Comment by johncaozh** [comment]
How to solve this problem?
