### ISSUE TITLE
Go to Welcome Page instead of directly into a conference room

### ISSUE THREAD

**Issue by danielnazareth89** [jitsi/jitsi-meet#2261]
This is a very stupid question, but I am very new to this so please bear with me:

When I navigate to the URL of my jitsi meet install, I am directly put into a conference room with a random room name. By contrast when I go to meet.jit.si, I get a welcome page where I can choose my own conference room name, click Go when I am ready and then enter the room. How do I ensure the Welcome page loads first? Below is my nginx config:

server {
    listen 80;
    server_name $DOMAIN;
    # set the root
    location / {
        return 301 https://$server_name$request_uri;
    }
}
server {
    listen 443 ssl default_server;
    server_name $DOMAIN;
    root /usr/share/jitsi-meet;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    add_header X-Content-Type-Options nosniff;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_prefer_server_ciphers on;

   location / {
        ssi on;
    }
    location ~ ^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }

}

**Comment by damencho** [comment]
There is config option for welcome page:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L213
If you disable it it will generate a room and will put you there.

There is also an option on the welcome page and if you click it it will save it and from now on will behave as you describe. To test if this is the case open your deployment in incognito mode.
There is no easy way to delete this option, other than opening the js console, navigate to Application -> Local storage and delete that entry, it is called welcomePageDisabled.
