### ISSUE TITLE
[Android]  "./gradlew :react-native-webrtc:publish"  this command is not executing

### ISSUE THREAD

**Issue by sachinrkeche** [jitsi/jitsi-meet#2264]
Hello Devs,
We want to integrate Jitsi with our own server in our native android app, so for that i followed the steps given under [Jitsi Meet SDK for Android](https://github.com/jitsi/jitsi-meet/tree/master/android) to extract and integrate the Jitsi SDK in our app, But some how when i am trying to execute the command "react-native-webrtc:publish" it fails to execute. And i am not able to proceed for further steps.

Will any one please help me what could be the reason that the command "react-native-webrtc:publish" failing to execute.. 

Your any help will be highly appreciated.

**Comment by lyubomir** [comment]
Hey, man! Could you please paste the error output of the command `./gradlew :react-native-webrtc:publish`?

**Comment by sachinrkeche** [comment]
Hi, @lyubomir thanks for your valuable time, 
 I am using this one , i clone [](https://github.com/jitsi/jitsi-meet.git) jitsi meet repository and following the steps from [https://github.com/jitsi/jitsi-meet/tree/master/android](url) , Jitsi Meet SDK for Android i paste completely step what i did step 5 and 6 when i fired ./gradlew :react-native-webrtc:publish

Rahils-MacBook-Pro:JitsiIntegration arpitmakhija$ cd jitsi-meet/

1 ] First Step 

Rahils-MacBook-Pro:jitsi-meet arpitmakhija$ cd android/

2 ] Then I fired ./gradlew :sdk:assembleRelease

Rahils-MacBook-Pro:android arpitmakhija$ ./gradlew :sdk:assembleRelease
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Configure project :react-native-background-timer
Configuration 'compile' in project ':react-native-background-timer' is deprecated. Use 'implementation' instead.

> Configure project :react-native-fetch-blob
Configuration 'compile' in project ':react-native-fetch-blob' is deprecated. Use 'implementation' instead.

> Configure project :react-native-immersive
Configuration 'compile' in project ':react-native-immersive' is deprecated. Use 'implementation' instead.

> Configure project :react-native-keep-awake
Configuration 'compile' in project ':react-native-keep-awake' is deprecated. Use 'implementation' instead.

> Configure project :react-native-vector-icons
Configuration 'compile' in project ':react-native-vector-icons' is deprecated. Use 'implementation' instead.

> Configure project :react-native-webrtc
Configuration 'compile' in project ':react-native-webrtc' is deprecated. Use 'implementation' instead.

> Configure project :sdk
Configuration 'compile' in project ':sdk' is deprecated. Use 'implementation' instead.

> Task :sdk:bundleReleaseJsAndAssets
Scanning folders for symlinks in /Users/arpitmakhija/Downloads/SachinWorkspace/JitsiIntegration/jitsi-meet/node_modules (23ms)
Scanning folders for symlinks in /Users/arpitmakhija/Downloads/SachinWorkspace/JitsiIntegration/jitsi-meet/node_modules (16ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: start
bundle: finish
bundle: Writing bundle output to: /Users/arpitmakhija/Downloads/SachinWorkspace/JitsiIntegration/jitsi-meet/android/sdk/build/intermediates/bundles/release/assets/index.android.bundle
bundle: Copying 1 asset files
bundle: Done writing bundle output
bundle: Done copying assets


BUILD SUCCESSFUL in 7m 9s
106 actionable tasks: 19 executed, 87 up-to-date


3 ] after that i fired ./gradlew :sdk:publish

Rahils-MacBook-Pro:android arpitmakhija$ ./gradlew :sdk:publish

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Configure project :react-native-background-timer
Configuration 'compile' in project ':react-native-background-timer' is deprecated. Use 'implementation' instead.

> Configure project :react-native-fetch-blob
Configuration 'compile' in project ':react-native-fetch-blob' is deprecated. Use 'implementation' instead.

> Configure project :react-native-immersive
Configuration 'compile' in project ':react-native-immersive' is deprecated. Use 'implementation' instead.

> Configure project :react-native-keep-awake
Configuration 'compile' in project ':react-native-keep-awake' is deprecated. Use 'implementation' instead.

> Configure project :react-native-vector-icons
Configuration 'compile' in project ':react-native-vector-icons' is deprecated. Use 'implementation' instead.

> Configure project :react-native-webrtc
Configuration 'compile' in project ':react-native-webrtc' is deprecated. Use 'implementation' instead.

> Configure project :sdk
Configuration 'compile' in project ':sdk' is deprecated. Use 'implementation' instead.


BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed

4 ] then I change the directory as mentionin the doc (https://github.com/jitsi/jitsi-meet/tree/master/android) by cd ../

Rahils-MacBook-Pro:android arpitmakhija$ cd ../
Rahils-MacBook-Pro:jitsi-meet arpitmakhija$ ls
CONTRIBUTING.md		android			connection_optimization	fonts			interface_config.js	package-lock.json	sounds
ConferenceEvents.js	app.js			css			gen			ios			package.json		static
LICENSE			base.html		debian			images			lang			plugin.head.html	title.html
Makefile		conference.js		doc			index.android.js	logging_config.js	react			webpack.config.js
README.md		config.js		favicon.ico		index.html		modules			resources
analytics.js		connection.js		flow-typed		index.ios.js		node_modules		service

5 ] Here is fired ./gradlew :react-native-webrtc:publish as documented but here I am out of the directory so I got following o/p


Rahils-MacBook-Pro:jitsi-meet arpitmakhija$ ./gradlew :react-native-webrtc:publish
-bash: ./gradlew: No such file or directory


6 ] Again I goes to the android directory and fire this the command ./gradlew :react-native-webrtc:publish my output is like this  

Rahils-MacBook-Pro:jitsi-meet arpitmakhija$ cd android/
Rahils-MacBook-Pro:android arpitmakhija$ ./gradlew :react-native-webrtc:publish

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Configure project :react-native-background-timer
Configuration 'compile' in project ':react-native-background-timer' is deprecated. Use 'implementation' instead.

> Configure project :react-native-fetch-blob
Configuration 'compile' in project ':react-native-fetch-blob' is deprecated. Use 'implementation' instead.

> Configure project :react-native-immersive
Configuration 'compile' in project ':react-native-immersive' is deprecated. Use 'implementation' instead.

> Configure project :react-native-keep-awake
Configuration 'compile' in project ':react-native-keep-awake' is deprecated. Use 'implementation' instead.

> Configure project :react-native-vector-icons
Configuration 'compile' in project ':react-native-vector-icons' is deprecated. Use 'implementation' instead.

> Configure project :react-native-webrtc
Configuration 'compile' in project ':react-native-webrtc' is deprecated. Use 'implementation' instead.

> Configure project :sdk
Configuration 'compile' in project ':sdk' is deprecated. Use 'implementation' instead.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webrtc:publishAarArchivePublicationToMaven2Repository'.
> Failed to publish publication 'aarArchive' to repository 'maven2'
   > Invalid publication 'aarArchive': artifact file does not exist: '/Users/arpitmakhija/Downloads/SachinWorkspace/JitsiIntegration/jitsi-meet/node_modules/react-native-webrtc/android/build/outputs/aar/react-native-webrtc-release.aar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
5 actionable tasks: 2 executed, 3 up-to-date
Rahils-MacBook-Pro:android arpitmakhija$

**Comment by lyubomir** [comment]
Did you successfully complete `./gradlew :react-native-webrtc:assembleRelease` first? Or `./gradlew :sdk:assembleRelease` which assembles Jitsi Meet SDK for Android and all its dependencies including react-native-webrtc?

**Comment by sachinrkeche** [comment]
Thanks @lyubomir, it's working now , i success in after executing the _./gradlew :react-native-webrtc:assembleRelease_ , I am following this doc for [https://github.com/jitsi/jitsi-meet/tree/master/android](url) to use Jitsi SDK in my project , what i have to do now ?
I simply import "Android" folder into my project and added the Maven repository https://github.com/jitsi/jitsi-maven-repository/raw/master/releases and the dependency org.jitsi.react:jitsi-meet-sdk:1.9.0 into your build.gradle, but i am getting the error in Android/sdk/build.gradle , 

> file

 cannot get property compileSdkVersion on extra property extensionas it does not exist.

**Comment by lyubomir** [comment]
@sachinrkeche,

1. When you do `./gradlew :<project name here>:assembleRelease` and `./gradlew :<project name here>:publish`, I presume you've modified the respective project's source code and you want to build your own binary.

2. Then you cannot make your binary available via https://github.com/jitsi/jitsi-maven-repository/raw/master/releases because it's our/Jitsi's Maven repository and you don't have write access to it.

3. Which means that you need to (3.1) either copy the .aar files of the project you modified into your project, or (3.2) create your own Maven repository (by forking ours on GitHub, for example) in which you publish your binary artifact. As soon as you've got binaries, you no longer want to import Jitsi Meet for Android's source code into your project's source code.

Does the above make sense to you?

**Comment by sachinrkeche** [comment]
Dear ### @lyubomir,   
This one clearly make sense to me , i followed the 
1. ./gradlew :<project name here>:assembleRelease

2.  ./gradlew :<project name here>:

 respectively for the below project , 
 react-native-background-timer
 react-native-fetch-blob
 react-native-immersive
 react-native-keep-awake
 react-native-vector-icons
 react-native-webrtc 
 so as you mention in above comment point 3 - (3.1) I am following,  modified project  contains / android folder where i assemble/published above 6  project , so i have to create the .aar file of /android folder from modified project and that should i need to include as .aar file in to my project , is the way i am going is right way?

**Comment by lyubomir** [comment]
The `:publish` copies your binary artifacts into a Maven repository. If you followed our documentation and didn't modify the defaults, that Maven repository is probably a directory with a clone of jitsi/jitsi-maven-repository. Since you said you're following 3.1, then copy the .aar files from the clone of jitsi/jitsi-maven-repository to your project and work with them. Anyway, I'd certainly recommend going with 3.2 but then you need to utilize some Maven knowledge like incrementing versions so that your modified binaries are picked up from your Maven repository instead of ours, etc.

**Comment by saghul** [comment]
@sachinrkeche slightly tangential, but why do you need to build the SDK yourself? Do you have changes you cannot upstream? Ideally you should be to use it as-is, and that should not take more than adding our maven repo and a dependency in your project.

**Comment by sachinrkeche** [comment]
Hello @saghul, I am building the SDK for Android Native application so i can use this SDK in the Native Android project .  Is it possible for Native to use maven repository and dependancy in my project ?

**Comment by saghul** [comment]
Sure. You can use our maven repo: https://github.com/jitsi/jitsi-maven-repository and add a dependency to your project.

**Comment by sachinrkeche** [comment]
@saghul , How to add this maven repository ? and give me the dependency. will be thankful.

**Comment by saghul** [comment]
Here is the link to the maven repo and the name of the package you need to depend on: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#install It's standard gradle stuff:

In your app build.gradle file, add:

~~~
repositories {
  maven {
    url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
  }
}
~~~

And in the dependencies section, add:

~~~
implementation('org.jitsi.react:jitsi-meet-sdk:1.9.0@aar')
~~~

**Comment by sachinrkeche** [comment]
Hello @saghul , I already try this solution as per your suggestion i added  app build.gradle file  
repositories {
  maven {
    url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
  }
}
And in the dependencies section, add:

implementation('org.jitsi.react:jitsi-meet-sdk:1.9.0@aar')

but i am getting this error , 

FATAL EXCEPTION: main
                                                                               Process: com.example.sachink.jitsisaghul, PID: 7351
                                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/ReactInstanceManager;
                                                                                   at org.jitsi.meet.sdk.JitsiMeetView.initReactInstanceManager(JitsiMeetView.java:92)
                                                                                   at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:252)
                                                                                   at com.example.sachink.jitsisaghul.MainActivity.onCreate(MainActivity.java:26)
                                                                                   at android.app.Activity.performCreate(Activity.java:6684)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2764)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                   at android.os.Looper.loop(Looper.java:203)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6338)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1066)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)

this error is regarding the react,  any solution?

**Comment by saghul** [comment]
Re you doing a debug build or a release build?

**Comment by sachinrkeche** [comment]
@saghul , I am making Debug build.

**Comment by lyubomir** [comment]
Because of the failed resolution of `com/facebook/react/ReactInstanceManager` which is a react-native class and react-native is a dependency of Jitsi Meet SDK for Android, did you try to bring the transitive dependencies?

````gradle
implementation('org.jitsi.react:jitsi-meet-sdk:1.9.0@aar') {
    transitive = true;
}
````
