### ISSUE TITLE
[ios] I try to integrate it to a demo. but i get the error about .jsbundle

### ISSUE THREAD

**Issue by yuhuazhexian** [jitsi/jitsi-meet#2267]
there is the log 

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2017-12-08 10:59:33.192116+0800 jitsi_meet_demo[79066:3601525] No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2017-12-08 10:59:33.208728+0800 jitsi_meet_demo[79066:3601525] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001074921cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000106dfcf41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001074d1e8c _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00000001073a6da1 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x00000001073a6c2b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   JitsiMeet                           0x00000001056fd51b -[AppInfo constantsToExport] + 379
	6   JitsiMeet                           0x00000001057b0762 __32-[RCTModuleData gatherConstants]_block_invoke + 50
	7   JitsiMeet                           0x000000010585a8e3 RCTUnsafeExecuteOnMainQueueSync + 67
	8   JitsiMeet                           0x00000001057b04b7 -[RCTModuleData gatherConstants] + 631
	9   JitsiMeet                           0x000000010571af83 __52-[RCTBatchedBridge prepareModulesWithDispatchGroup:]_block_invoke + 163
	10  libdispatch.dylib                   0x000000010def53f7 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010def643c _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010df0185d _dispatch_main_queue_callback_4CF + 993
	13  CoreFoundation                      0x0000000107454ef9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x0000000107419662 __CFRunLoopRun + 2402
	15  CoreFoundation                      0x0000000107418a89 CFRunLoopRunSpecific + 409
	16  GraphicsServices                    0x000000010d4609c6 GSEventRunModal + 62
	17  UIKit                               0x000000010790cd30 UIApplicationMain + 159
	18  jitsi_meet_demo                     0x000000010540b5bf main + 111
	19  libdyld.dylib                       0x000000010df72d81 start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

I only import 2 frameworks  (JitsiMeet.framework & WebRTC.framework)   . Do I do it right?
Wish you give me some suggestions?  And I'm extremely grateful to you very much.

**Comment by kiempq** [comment]
I have same error. Did you fix it?

**Comment by saghul** [comment]
Fixed in 2572d583.
