### ISSUE TITLE
jitsi meet broken after upgrade to jitsi-* 1.0.2635-1 on Debian GNU/Linux 9.2 (stretch)

### ISSUE THREAD

**Issue by spellauge** [jitsi/jitsi-meet#2268]
hi,

after i upgraded to jitsi-* 1.0.2635-1 we are unable to create new
meetings (creating a new meeting requires user's authentication by means
of authdomain: .. at out site)

this used to work fine before the upgrade but now the login box is
displayed over and over again.

/var/log/jitsi/jicofo.log states:

Jicofo 2017-12-08 09:10:01.441 WARNING: [368]
org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener()
Connection XMPPTCPConnection[not-authenticated] (0) closed with error
javax.net.ssl.SSLHandshakeException:
sun.security.validator.ValidatorException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to
find valid certification path to requested target

so i assume that at least one ca-cert is missing now. searching the
internet i found some hints which were not really helpful.

i would greatly appreciate any hint on how to fix this issue in order to
overcome the less of service.

thanks in advance, gustav

**Comment by damencho** [comment]
I've already sent you an email to the mailinglist. No need to post everywhere. Here is my email:
Hi,
Did jitsi-meet-prosody package got updated? This is the one responsible for doing the migration and fixing this problem.

You can also check the manual installation doc and check/execute everything about auth.jitsi.example.com, the prosody config, make sure you restart prosody if you make a change. https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

But first make sure you have updated version of jitsi-meet-prosody.

Regards 
damencho
