### ISSUE TITLE
[iOS] Simply how do i notify other user to connect to the conference i created And how should we connect to same conference initiated by first user please...

### ISSUE THREAD

**Issue by asshewale** [jitsi/jitsi-meet#2269]
Hi Devs,

**Actually i want to initiate a video call from chat and want that other user should get notify to accept that call, here we are using the Rocketchat with our server and our own users and with in that we have integrated the video using Jitsi SDK with our server.** 

Scenario is we have integrated Jitsi in Rocket chat.
So on the chat screen of Rocket chat we added one video call button on top, so if two users are chatting with each other and they want to have a video call between them one user can initiate a video call on tapping of video button while chatting with other user, and at that event i am sending a chat message to other user programatically that he has received a video call please tap on video icon to connect ,

Now, our server url is https://ctsivideo.mvoipctsi.com and i open a conference as https://ctsivideo.mvoipctsi.com/1010 as the conference id is static so two users or any users who will tap on video button will land in a same conference...

But when we want different sessions / conference we will have to create a random conference numbers and append to server url, in that case how could we let other user know about to joine the same conference,

Please i am not able to get the way to connect the diffrent different people from different different rooms to have seperate conferences.

Your help will be highly appreciated..

**Comment by asshewale** [comment]
Hi @saghul how can i make jitsi work in rocket chat please i am not getting the way to make it work from anywhere.. 

you will be life saver for me.

**Comment by luismachado** [comment]
I would say that this is more of a rocketchat issue than jitsi's.
You probably want to post the URL of the newly created conference on the chat so that the other user can connect.

**Comment by asshewale** [comment]
Hi @luismachado yes i have confirmed that Rocket chat dont have a support for Jitsi as of now for native iOS, But we have to implement the methods under webSocket to communicate with Rocket chat is what the solution i got from Rocket chat ios forum, 

So what will be the initial way or steps from jitsi SDK to make it work, means from where should we start to implement those methods to communicate with Rocket chat.. first.

**Comment by saghul** [comment]
Sorry I missed the notification.

Jitsi Meet does not provide a rendezvous mechanism, that's up to your application. In a nutshel, and as you have found out, all you need is for both users to load a conference with the same URL. There are many ways to do this, but the simplest one is with some UI, for example cards. Riot, the Matrix client kinda does this. A user can add a widget to a chatroom and the URL is autogenerated at that moment. Then when another user taps on the widget, they join the room.

You can complicate it a lot more, but as a starter, the above should do.

**Comment by asshewale** [comment]
@saghul thanks for your time, 
Yes i have implemented the same logic for two users means for peer to peer, when first user is initiating a video call i am sending one message with Hyperlink of random room number appending to our url, then when other user got that message in his chat and he taps on the video button i grabs that URL from chat message and both lands in a same room number but 

I want to develop it like the way Jitsi work from Web app of Rocket chat... 
For that i had a discussion in RC forum, But came to know that the RC native iOS dont have a support for Jitsi, For that we will have to implement the methods under webSocket to connect to RC from Jitsi and to Jitsi from RC. ... Dont know how it would be get done.. But just shared whatever i came to know. :(

Ps. @saghul @luismachado : Will you guys also help me for the issue https://github.com/jitsi/jitsi-meet/issues/2285 please

**Comment by saghul** [comment]
> However thsi logic fails for group chat and for the call from web to iOS..

Why does this logic fail?

> For that i had a discussion in RC forum, But came to know that the RC native iOS dont have a support for Jitsi, For that we will have to implement the methods under webSocket to connect to RC from Jitsi and to Jitsi from RC. ... Dont know how it would be get done.. But just shared whatever i came to know. :(

I don't understand. You say you got it working for 1:1 chats but now say that RC needs some WebSocket connection to Jitsi?! That can't be right. There is no reason for an RC server to "talk" to a Jitsi server. All RC has to do is come up with a URL, a random one, and share it with the people in the room. The RC client may need some work (widgets / cards or something like that) but that's out of the scope of the Jitsi integration, you'd have the same problem if you integrate with any other WebRTC compatible conferencing system which used the same URL-based routing scheme.

**Comment by luismachado** [comment]
^ Exactly.

I've also been working on rocketchat and I would say that the implementation for 1:1 or group should be exactly the same, right @saghul 

It should only be a question of where you post the URL (private or group chat).
Either that or I'm missing the problem here :P

**Comment by saghul** [comment]
Correct.
