### ISSUE TITLE
Facing error while installing jitsi bridge on ubantu 14.04 Lts

### ISSUE THREAD

**Issue by jason9335** [jitsi/jitsi-meet#2273]
Hello Team,

We have installed jitsi bridge on ubantu 14.04 Lts and it's installed properly also displaying properly but when we try to join room it's not connecting Our Ip URL https://35.189.163.240/  as the services  which needed are working fine which are :- 

service jitsi-videobridge status

* jvb is running

service jigasi status

* jigasi is running

service jicofo status

* jicofo is running

prosodyctl status (XmPP server )

Prosody is running with PID 7395

Config file for cond.d/videodil.cfg.lua is wriiten below : 

-- Plugins path gets uncommented during jitsi-meet-tokens package install - that's where token plugin is located
--plugin_paths = { "/usr/share/jitsi-meet/prosody-plugins/" }

VirtualHost "videodil"
        -- enabled = false -- Remove this line to enable this host
        authentication = "anonymous"
        -- Properties below are modified by jitsi-meet-tokens package config
        -- and authentication above is switched to "token"
        --app_id="example_app_id"
        --app_secret="example_app_secret"
        -- Assign this host a certificate for TLS, otherwise it would use the one
        -- set in the global section (if any).
        -- Note that old-style SSL on port 5223 only supports one certificate, and will always
        -- use the global one.
        ssl = {
                key = "/etc/prosody/certs/videodil.key";
                certificate = "/etc/prosody/certs/videodil.crt";
        }
        -- we need bosh
        modules_enabled = {
            "bosh";
            "pubsub";
            "ping"; -- Enable mod_ping
        }

        c2s_require_encryption = false

Component "conference.videodil" "muc"
    storage = "/"
    --modules_enabled = { "token_verification" }
admins = { "focus@auth.videodil" }

Component "jitsi-videobridge.videodil"
    component_secret = "ZKwOYS6M"

VirtualHost "auth.videodil"
    ssl = {
        key = "";
        certificate = "";
    }
    authentication = "internal_plain"

Component "focus.videodil"
    component_secret = "M66Xii4p"

All logs are fine expect prosody logs which are showing like this :- 

Dec 09 13:18:05 jcp240f440      info    component disconnected: nil (false)
Dec 09 13:18:10 jcp211d240      info    Incoming Jabber component connection
Dec 09 13:18:10 mod_component   info    Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>callcontrol.videodil does not match any configured external components</text></stream:error>
Dec 09 13:18:10 jcp211d240      info    component disconnected: nil (false)
Dec 09 13:18:15 jcp20d5e80      info    Incoming Jabber component connection
Dec 09 13:18:15 mod_component   info    Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>callcontrol.videodil does not match any configured external components</text></stream:error>
Dec 09 13:18:15 jcp20d5e80      info    component disconnected: nil (false)
Dec 09 13:18:20 jcp22a6b80      info    Incoming Jabber component connection
Dec 09 13:18:20 mod_component   info    Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>callcontrol.videodil does not match any configured external components</text></stream:error>
Dec 09 13:18:20 jcp22a6b80      info    component disconnected: nil (false)

So can you please help on this as we tried a lot but we didn't find the resolution for this .

**Comment by damencho** [comment]
First thing I see is that in your config.js you have configured bosh: '//videodil/http-bind'. Most probably you had entered as domain for the deployment videodil. This is not resolvable for me and I cannot connect to your deployment.
Normally, you need to enter there domain which is resolvable, so remote participants can join.
Now, changing it is tricky, you need to reconfigure all packages, to enter it again or you will have problems later when updating.
You can also purge all the packages and start on clean.
Some commands hints: http://lists.jitsi.org/pipermail/dev/2017-May/033040.html

**Comment by jason9335** [comment]
Hello,

But as you can see our Ip is live so is it not worth wile though Ip or if I
do entry on my windows PC local host then atleast it is resolvable for
localhost if do entry of localhost on 2 laptops with the live ip then
atleast it is resolvable on those two laptops locally. Is it necessary to
live the domain DNS worldwide.

**Comment by damencho** [comment]
That's fine. Is jvb running on a machine with public address or is on a machine behind nat?

**Comment by jason9335** [comment]
Hello,

I have configured this on google cloud server which private ip is 10.140.0.3
and which is natted with this public Ip 35.189.163.240 i think. Can you
please help out as you can yourself tested by doing entry in your localhost
.

**Comment by damencho** [comment]
Have you checked this? And have you configured it?
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by jason9335** [comment]
Yes i have already configured this wait let me show you, but it's log is
showing error which is given below

2017-12-12 05:14:46.858 SEVERE: [40]
org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException:
Connection refused (Connection refused), host:videodil, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException:
Connection refused (Connection refused)
        at
org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
        at
org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at
org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
        at
org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection
refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at
java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at
java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at
org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)
        ... 12 more

**Comment by damencho** [comment]
You are trying to connect jvb or jicofo to host:videodil, port:5347, but prosody is not listening there. By default, both jicofo and jvb try to connect to localhost 5347. Make sure prosody is listening there.

**Comment by jason9335** [comment]
Hello Team,

Can you please tell me how to do that have tried everything but the log is
same . here are my prosody log :-

Dec 12 05:12:50 jcp28ecac0      info    component disconnected: nil (false)
Dec 12 05:12:55 jcp2b154f0      info    Incoming Jabber component connection
Dec 12 05:12:55 mod_component   info    Disconnecting component,
<stream:error> is: <stream:error><host-unknown
xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text
xmlns='urn:ietf:params:xml:ns:xmpp-streams'>callcontrol.videodil does not
match any configured external components</text></stream:error>
Dec 12 05:12:55 jcp2b154f0      info    component disconnected: nil (false)
Dec 12 05:13:00 jcp2a42060      info    Incoming Jabber component connection
Dec 12 05:13:00 mod_component   info    Disconnecting component,
<stream:error> is: <stream:error><host-unknown
xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text
xmlns='urn:ietf:params:xml:ns:xmpp-streams'>callcontrol.videodil does not
match any configured external components</text></stream:error>
Dec 12 05:13:00 jcp2a42060      info    component disconnected: nil (false)
Dec 12 05:13:05 jcp2a04de0      info    Incoming Jabber component connection
Dec 12 05:13:05 mod_component   info    Disconnecting component,
<stream:error> is: <stream:error><host-unknown
xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text
xmlns='urn:ietf:params:xml:ns:xmpp-streams'>callcontrol.videodil does not
match any configured external components</text></stream:error>
Dec 12 05:13:05 jcp2a04de0      info    component disconnected: nil (false)

**Comment by damencho** [comment]
# netstat -anp | grep 5347
Do you see it listening to localhost?
In /etc/jitsi/videobridge/config what is the value of JVB_HOST, by default it should be "JVB_HOST=".

Ignore the errors in prosody log about callcontrol, this is for jigasi and you are not interested in it.

**Comment by jason9335** [comment]
hello,

it's listning fine :-

tcp        0      0 127.0.0.1:5347          0.0.0.0:*               LISTEN
    26727/lua5.1
tcp        0      0 127.0.0.1:5347          127.0.0.1:60068
 ESTABLISHED 26727/lua5.1
tcp        0      0 127.0.0.1:5347          127.0.0.1:60078
 ESTABLISHED 26727/lua5.1
tcp6       0      0 ::1:5347                :::*                    LISTEN
    26727/lua5.1
tcp6       0      0 127.0.0.1:60078         127.0.0.1:5347
ESTABLISHED 13252/java
tcp6       0      0 127.0.0.1:60068         127.0.0.1:5347
ESTABLISHED 13387/java


below is the entry for config file :-

# Jitsi Videobridge settings

# sets the XMPP domain (default: none)
JVB_HOSTNAME=videodil

# sets the hostname of the XMPP server (default: domain if set, localhost
otherwise)
JVB_HOST=

# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347

# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=ZKwOYS6M

# extra options to pass to the JVB daemon
JVB_OPTS=--apis=rest,xmpp


# adds java system props that are passed to jvb (default are for home and
logging config file)
JAVA_SYS_PROPS="$JVB_EXTRA_JVM_PARAMS
-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi
-Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge
-Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi
-Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
AUTHBIND=yes

**Comment by damencho** [comment]
It seems to me that when you are starting jvb, it doesn't use /etc/jitsi/videobridge/config, as in your log you have: 'ConnectException:
Connection refused (Connection refused), host:videodil, port:5347', which means that 'JVB_HOST=videodil', but it is 'JVB_HOST='.

ps ax | grep videobridge
What is the value of --host parameter? Should be '--host=localhost'.

**Comment by jason9335** [comment]
Hello ,

It is exactly showing like that

jar:/usr/share/jitsi-videobridge/lib/weupnp-0.1.4.jar:/usr/share/jitsi-videobridge/lib/xml-apis-1.0.b2.jar:/usr/share/jitsi-videobridge/lib/xmlpull-1.1.3.4a.jar:/usr/share/jitsi-videobridge/lib/xpp3-1.1.4c.jar:/usr/share/jitsi-videobridge/lib/zrtp4j-light-3.2.0-jitsi-1-20150723.002345-1.jar
org.jitsi.videobridge.Main --host=localhost --domain=videodil --port=5347
--secret=ZKwOYS6M --apis=rest,xmpp

**Comment by jason9335** [comment]
Hi,

i have installed successfully but not able to conferencing on video as you
can check the link yourself https://jitsi.dil.in/jason kindly suggest what
i am missing .

**Comment by saghul** [comment]
I see ICE failures in the console. Does the server have port 10000 (UDP) open?

**Comment by jason9335** [comment]
Hello ,

Its listning

root@videomail:/home/dilmail# netstat -tulpn | grep :10000
udp6       0      0 10.140.0.2:10000        :::*
    7990/java

**Comment by saghul** [comment]
That doesn't mean the port is open for traffic coming from outside of the server's network. A firewall might be blocking it.

**Comment by jason9335** [comment]
Actually i am using google cloud for this on private network its listening
and for outer network i have allowed the same port . Can you please guide
us for the same.

**Comment by saghul** [comment]
I have no experience with Google Cloud, sorry :-(
