### ISSUE TITLE
Maybe useful, simple JS redirect from home page

### ISSUE THREAD

**Issue by AdamMiltonBarker** [jitsi/jitsi-meet#2274]
Here is a very simple hack to redirect the home page to any url you like, this stops people being able to land on your homepage and open a room (Which I believe is a very bad feature), also allows you to make a custom homepage without the hassle of entirely rebuilding everything just to change the homepage.

Edit /usr/share/jitsi-meet/index.html and add the code to the top of the JS script.

 ```
var fileName = location.href.split("/").slice(-1);
if(fileName == ""){
                window.location.href = "YOURURL";
}
```

**Comment by ZuzooVn** [comment]
@AdamMiltonBarker  People can open a new room by accessing to `yourdomain.com/room_name`
