### ISSUE TITLE
Video Adjustment

### ISSUE THREAD

**Issue by cynthiabaker91** [jitsi/jitsi-meet#2277]
How does JITSI determine what resolution, frame rate,compress and bit rate to use for video call??
Are these fixed parameters? If not how can I change them?

**Comment by bbaldino** [comment]
there are some configurable parameters in config.js that control the maximums (https://github.com/jitsi/jitsi-meet/blob/master/config.js#L93 for older browsers and https://github.com/jitsi/jitsi-meet/blob/master/config.js#L100 for the more modern browsers we've moved over to use spec-style constraints).  Once the call is started, other factors (like the network and cpu) can vary the resolution at runtime.  Btw, in the future the mailing list would be better for this sort of question (dev@jitsi.org).
