### ISSUE TITLE
https client certificate for mobile clients

### ISSUE THREAD

**Issue by wildc4t** [jitsi/jitsi-meet#2278]
First of all thank you for this software! It's really cool.

I was trying to setup client ssl authorization with own ca in web server config.
Browser clients works fine. But mobile clients lacks feature of apropriate client certificate selection like in mobile browsers. 

Example config on server side (apache2 example):

`SSLProxyCACertificateFile` `/path/to/ssl/ca.crt`

 `<Proxy` `*>`
 `SSLVerifyClient` `require`
 `</Proxy>`

  `ProxyPreserveHost` `on`
  `ProxyPass` `/http-bind` `http://localhost:5280/http-bind/`
  `ProxyPassReverse` `/http-bind` http://localhost:5280/http-bind/

This feature would make jitsi-meet much safer.

**Comment by saghul** [comment]
We currently use the system facilities, so you'll have to trust the CA at the OS level and then Jitsi Meet should work too.

> This feature would make jitsi-meet much safer.

Out of curiosity: why? Having letsEncrypt makes this a lot easier these days.

**Comment by wildc4t** [comment]
I probably did not explain very clearly. You mean trust to jitsi-meet server. LetsEncrypt working perfectly there.
But I mean mobile client auth with client cert imported in mobile device cert storage. Allow or not allow a particular mobile client to connect to the server jitsi-meet.
For desktop clients it works fine. Mobile browsers asks which cert to use for auth to this server and works fine. Jitsi mobile client does not ask for cert. On apache2 server log we can see:
`[Mon` `Dec` `11` `13:04:06.458067` `2017]` `[ssl:error]` `[pid` `2496:tid` `140013473343232]` `SSL` `Library` `Error:` `error:140890C7:SSL` `routines:ssl3_get_client_certificate:peer` `did` `not` `return` `a` `certificate` `--` `No` `CAs` `known` `to` `server` `for` `verification?`

Web server asks jitsi-meet mobile client for certificate to authenticate yourself. Mobile browser in that case opens dialog to select cert from phone storage.

**Comment by saghul** [comment]
Ah, I see now, you seem to require client certificates. Do you know if storing those client certs on the device's trust store fixes the problem? I don't see us implementing support for this any time soon, I'm afraid.

**Comment by wildc4t** [comment]
Cert is on the store. But client has to select which cert to use like browser does. I think it is system dialog.
Thanks anyway.
