### ISSUE TITLE
Video getting disappeared after few seconds and the emojis appears instead

### ISSUE THREAD

**Issue by asshewale** [jitsi/jitsi-meet#2285]
I have integrated Jitsi in RC and succeeded in connecting two people in same room, The problem is, The video of one person which is visible to other person in whole screen of mobile is getting dissappeared after either in 1o seconds or in 20 sec. or in 30 sec. This is happening for both the users on both ends after few secs we fails to see the other user we only able to see our self in small square box at bottom right . 

I am trying to search for the issue but not able to find any reliable solution. 

Your any help will be highly appreciated. 

@saghul  can you please help me on this.

**Comment by saghul** [comment]
Are you using your own Jitsi installation or meet.jit.si?

**Comment by asshewale** [comment]
@saghul  Hi bro , i am using our won Jitsi installation

**Comment by saghul** [comment]
There is no magic knob. But just to make sure, can you switch to using our servers instead? Just for checking if there is a difference.

**Comment by asshewale** [comment]
means should i replace our server URL (Base URL) with Jitsi, and then append the random room id to it..? Please correct me.

**Comment by saghul** [comment]
That's correct.

**Comment by asshewale** [comment]
ok let me give a try , thanks :) :)

**Comment by asshewale** [comment]
Hi @saghul i tried it, its working idealy with jitsi url, video is not getting dissapeared, So what might be the issue that the video getting invisible with our URL after couple of seconds.. please...

**Comment by saghul** [comment]
Any chance of packet loss towards your server? Connect a mobile and a browser and on the browser side, check the connection information by hovering on the signal bars. Do you see "p2p" in the transport on both cases? Any packet loss?

**Comment by asshewale** [comment]
Hi @saghul Sorry for communicating after long time, it was a long holiday actually..

We tried the steps you asked, we were/are bit confused about the 'singnal bars' on which you asked to hover, but whichever we found on web and we hover on i am sharing the images of same please give a look and please correct us whether we checked the right signal bars or not. 

Below are the singals we found on web of two users in conferencing. 
![screen shot 2017-12-27 at 3 23 23 pm](https://user-images.githubusercontent.com/4498273/34378246-e74190d4-eb1a-11e7-800d-bbd9b902adeb.png)

below are the screen shot of hovering on the signals of both users

![screen shot 2017-12-27 at 3 25 31 pm](https://user-images.githubusercontent.com/4498273/34378288-1bb083ca-eb1b-11e7-89e4-c15a58707741.png)

![screen shot 2017-12-27 at 3 25 47 pm](https://user-images.githubusercontent.com/4498273/34378297-24d1a56a-eb1b-11e7-9fb3-d825831f70a8.png)

as above by hovering of above signals we got only the white view nothing else. If this are not the intended signals then please correct us that which signals to check. 

Thanks.

**Comment by saghul** [comment]
@asshewale that looks like some styling is broken! are you running the latest release? do you see any errors in the console? or maybe you've made some customizations?

**Comment by lyubomir** [comment]
Further information was requested roughly eight months ago. Additionally, the conversation seems to be about a custom deployment with bugs that we're not (presently at least if ever) seeing. So I suppose it's safe to close this issue.
