### ISSUE TITLE
Screencast menu option

### ISSUE THREAD

**Issue by bprinsloo** [jitsi/jitsi-meet#2287]
I just managed to get it installed on Ubuntu 14 LTS. Everything seems to work fine, except I don't have the desktop screen cast menu option. Is there a setting I might be missing? Apologies if this was answered before.

**Comment by damencho** [comment]
For firefox 52 and above, nothing. For chrome you need an extension. You can create extension for your deployment, by changing the domain name in the manifest file and uploading it to chrome webstore, taking the id for that extension and configure it in config.js.
The extension and more info you can find at: https://github.com/jitsi/jidesha

**Comment by bprinsloo** [comment]
Thank you for the quick response. Will the same extension also make the option available for Opera? On your test site the menu option shows within Opera.

**Comment by damencho** [comment]
Yes, but you need another extension that install chrome extensions in opera.

**Comment by damencho** [comment]
You can try on meet.jit.si
