### ISSUE TITLE
"Unfortunately, something went wrong" appear when two or more than two user connected issue

### ISSUE THREAD

**Issue by ahsanshaokat** [jitsi/jitsi-meet#2298]
Hi, I got that issue, when two or more than two people connected to conference call, I installed jitsi-meet on my own server, but am getting this issue. Please guide me, how i can handle this issue. and why it's occurring.  here is the console logs

[modules/xmpp/xmpp.js] <t.value>:  (TIME) Strophe connected:	 30538.750000000004
Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  My Jabber ID: 0d92f939-fe94-484e-b454-fd893cc5eb53@devcall.softwarefunnels.com/98f43633-c9d3-434a-b386-2dae0b2484a8
Logger.js:125 [conference.js] <>:  initialized with %s local tracks 2
Logger.js:125 [modules/xmpp/ChatRoom.js] <new t>:  Joined MUC as testing@conference.devcall.softwarefunnels.com/0d92f939
Logger.js:125 [modules/connectivity/ParticipantConnectionStatus.js] <new e>:  RtcMuteTimeout set to: 2000
Logger.js:125 [modules/statistics/AvgRTPStatsReporter.js] <new e>:  Avg RTP stats will be calculated every 15 samples
Logger.js:125 [JitsiConference.js] <new r>:  backToP2PDelay: 5
Logger.js:125 [JitsiConference.js] <r._doReplaceTrack>:  _doReplaceTrack - no JVB JingleSession
Logger.js:125 [JitsiConference.js] <r._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
Logger.js:125 [JitsiConference.js] <r._doReplaceTrack>:  _doReplaceTrack - no JVB JingleSession
Logger.js:125 [JitsiConference.js] <r._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
Logger.js:125 [modules/xmpp/moderator.js] <i.setFocusUserJid>:  Focus jid set to:  undefined
Logger.js:125 [modules/xmpp/moderator.js] <i.createConferenceIq>:  Session ID: null machine UID: 257a226c673cf828dd3202f5619511e4
Logger.js:125 [modules/xmpp/strophe.ping.js] <o.value>:  XMPP pings will be sent every 10000 ms
Logger.js:125 [modules/xmpp/moderator.js] <i.setFocusUserJid>:  Focus jid set to:  focus@auth.devcall.softwarefunnels.com
Logger.js:125 [modules/xmpp/moderator.js] <i.parseConfigOptions>:  Authentication enabled: false
Logger.js:125 [modules/xmpp/moderator.js] <i.parseConfigOptions>:  External authentication enabled: false
Logger.js:125 [modules/xmpp/moderator.js] <i.parseConfigOptions>:  Sip gateway enabled:  false
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  entered testing@conference.devcall.softwarefunnels.com/f84b3548 {show: "", affiliation: "owner", role: "moderator", jid: "f84b3548-90a0-4ae2-8059-ebdaa9b12259@devcall.softw…efunnels.com/61582cda-4e14-4505-847f-08e1d81c1901", isFocus: false, …}
Logger.js:125 [conference.js] <n.<anonymous>>:  USER %s connnected f84b3548 e {_jid: "testing@conference.devcall.softwarefunnels.com/f84b3548", _id: "f84b3548", _conference: r, _displayName: undefined, _supportsDTMF: false, …}
Logger.js:125 [JitsiConference.js] <r._maybeStartOrStopP2P>:  Auto P2P disabled
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  entered testing@conference.devcall.softwarefunnels.com/focus {show: "", affiliation: "owner", role: "moderator", jid: "focus@auth.devcall.softwarefunnels.com/focus1552583483124", isFocus: true, …}
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  Ignore focus: testing@conference.devcall.softwarefunnels.com/focus, real JID: focus@auth.devcall.softwarefunnels.com/focus1552583483124
Logger.js:125 [modules/version/ComponentsVersions.js] <>:  Got xmpp version: Prosody(0.9.10,Linux)
Logger.js:125 [modules/version/ComponentsVersions.js] <>:  Got focus version: JiCoFo(1.0.1.0-371,Linux)
Logger.js:125 [conference.js] <n.<anonymous>>:  My role changed, new role: none
Logger.js:125 [JitsiConference.js] <r._maybeStartOrStopP2P>:  Auto P2P disabled
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  (TIME) MUC joined:	 33713.43
Logger.js:125 [modules/UI/videolayout/LargeVideoManager.js] <>:  hover in %s 0d92f939
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  Ignore focus: testing@conference.devcall.softwarefunnels.com/focus, real JID: focus@auth.devcall.softwarefunnels.com/focus1552583483124
Logger.js:125 [react/features/overlay/components/AbstractPageReloadOverlay.js] <t.value>:  The conference will be reloaded after 20 seconds.
Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.videobridgeNotAvailable
i @ Logger.js:125
value @ conference.js:286
n.emit @ events.js:81
n.emit @ events.js:96
value @ ChatRoom.js:539
value @ strophe.emuc.js:105
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
setTimeout (async)
_send @ strophe.js:4972
send @ strophe.js:2653
sendIQ @ strophe.js:2757
info @ strophe.disco.js:162
(anonymous) @ Caps.js:121
value @ Caps.js:120
r.onMemberJoined @ JitsiConference.js:1152
n.emit @ events.js:89
value @ ChatRoom.js:474
value @ strophe.emuc.js:105
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
flush @ strophe.js:2669
value @ ChatRoom.js:277
(anonymous) @ ChatRoom.js:239
i._allocateConferenceFocusSuccess @ moderator.js:451
(anonymous) @ moderator.js:338
(anonymous) @ strophe.js:2731
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
flush @ strophe.js:2669
i.allocateConferenceFocus @ moderator.js:345
value @ ChatRoom.js:239
r.join @ JitsiConference.js:303
value @ conference.js:397
(anonymous) @ conference.js:734
(anonymous) @ conference.js:733
Promise resolved (async)
init @ conference.js:681
(anonymous) @ actions.web.js:38
(anonymous) @ index.js:11
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:31
(anonymous) @ middleware.js:127
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:34
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:36
(anonymous) @ middleware.js:54
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:28
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:47
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:78
value @ Conference.web.js:46
e.notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
E @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
u @ ReactUpdates.js:200
i @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
i.setState @ ReactBaseClasses.js:64
(anonymous) @ AbstractApp.js:400
value @ AbstractApp.js:398
value @ App.web.js:96
I @ middleware.js:78
M @ middleware.js:118
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:36
(anonymous) @ middleware.js:54
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:28
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:47
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:78
dispatch @ applyMiddleware.js:35
(anonymous) @ actions.js:49
Promise resolved (async)
r @ actions.js:49
o @ actions.js:123
(anonymous) @ actions.js:22
(anonymous) @ index.js:11
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:31
(anonymous) @ middleware.js:127
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:34
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:36
(anonymous) @ middleware.js:54
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:28
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:47
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:78
value @ AbstractApp.js:430
value @ AbstractApp.js:119
performInitialMount @ ReactCompositeComponent.js:350
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
a @ ReactMount.js:104
perform @ Transaction.js:143
s @ ReactMount.js:126
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
o @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:319
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ index.web.js:22
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  do leave testing@conference.devcall.softwarefunnels.com/0d92f939
Logger.js:125 [conference.js] <n.<anonymous>>:  USER %s LEFT f84b3548 e {_jid: "testing@conference.devcall.softwarefunnels.com/f84b3548", _id: "f84b3548", _conference: r, _displayName: undefined, _supportsDTMF: false, …}
Logger.js:125 [modules/UI/videolayout/VideoLayout.js] <Object.removeParticipantContainer>:  Removing remote video: f84b3548
Logger.js:125 [modules/UI/videolayout/RemoteVideo.js] <i.remove>:  Remove thumbnail f84b3548
Logger.js:125 [JitsiConference.js] <r._maybeStartOrStopP2P>:  Auto P2P disabled
Logger.js:125 [modules/xmpp/moderator.js] <i.onMucMemberLeft>:  Someone left is it focus ? testing@conference.devcall.softwarefunnels.com/f84b3548
Logger.js:125 [conference.js] <n.<anonymous>>:  My role changed, new role: moderator
Logger.js:125 [JitsiConference.js] <r._maybeStartOrStopP2P>:  Auto P2P disabled
Logger.js:125 [modules/UI/videolayout/VideoLayout.js] <Object.changeUserAvatar>:  Missed avatar update - no small video yet for 0d92f939
i @ Logger.js:125
changeUserAvatar @ VideoLayout.js:918
i @ UI.js:728
O.setUserAvatarID @ UI.js:758
(anonymous) @ conference.js:1922
(anonymous) @ ChatRoom.js:640
value @ ChatRoom.js:639
value @ ChatRoom.js:577
value @ strophe.emuc.js:105
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5013
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
setTimeout (async)
_send @ strophe.js:4972
send @ strophe.js:2653
_onDiscoInfo @ strophe.disco.js:225
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
flush @ strophe.js:2669
value @ ChatRoom.js:304
(anonymous) @ ChatRoom.js:1349
value @ ChatRoom.js:1329
r.leave @ JitsiConference.js:395
value @ conference.js:354
n.emit @ events.js:81
n.emit @ events.js:96
value @ ChatRoom.js:539
value @ strophe.emuc.js:105
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
setTimeout (async)
_send @ strophe.js:4972
send @ strophe.js:2653
sendIQ @ strophe.js:2757
info @ strophe.disco.js:162
(anonymous) @ Caps.js:121
value @ Caps.js:120
r.onMemberJoined @ JitsiConference.js:1152
n.emit @ events.js:89
value @ ChatRoom.js:474
value @ strophe.emuc.js:105
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
flush @ strophe.js:2669
value @ ChatRoom.js:277
(anonymous) @ ChatRoom.js:239
i._allocateConferenceFocusSuccess @ moderator.js:451
(anonymous) @ moderator.js:338
(anonymous) @ strophe.js:2731
run @ strophe.js:2013
(anonymous) @ strophe.js:3110
forEachChild @ strophe.js:993
_dataRecv @ strophe.js:3098
_onRequestStateChange @ strophe.js:4729
XMLHttpRequest.send (async)
l @ strophe.js:4843
_processRequest @ strophe.js:4855
_throttledRequestHandler @ strophe.js:5007
_onIdle @ strophe.js:4633
_onIdle @ strophe.js:3718
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
setTimeout (async)
_onIdle @ strophe.js:3722
flush @ strophe.js:2669
i.allocateConferenceFocus @ moderator.js:345
value @ ChatRoom.js:239
r.join @ JitsiConference.js:303
value @ conference.js:397
(anonymous) @ conference.js:734
(anonymous) @ conference.js:733
Promise resolved (async)
init @ conference.js:681
(anonymous) @ actions.web.js:38
(anonymous) @ index.js:11
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:31
(anonymous) @ middleware.js:127
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:34
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:36
(anonymous) @ middleware.js:54
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:28
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:47
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:78
value @ Conference.web.js:46
e.notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
E @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
u @ ReactUpdates.js:200
i @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
i.setState @ ReactBaseClasses.js:64
(anonymous) @ AbstractApp.js:400
value @ AbstractApp.js:398
value @ App.web.js:96
I @ middleware.js:78
M @ middleware.js:118
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:36
(anonymous) @ middleware.js:54
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:28
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:47
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:78
dispatch @ applyMiddleware.js:35
(anonymous) @ actions.js:49
Promise resolved (async)
r @ actions.js:49
o @ actions.js:123
(anonymous) @ actions.js:22
(anonymous) @ index.js:11
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:31
(anonymous) @ middleware.js:127
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:34
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:36
(anonymous) @ middleware.js:54
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:28
(anonymous) @ middleware.js:18
(anonymous) @ middleware.js:47
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:78
value @ AbstractApp.js:430
value @ AbstractApp.js:119
performInitialMount @ ReactCompositeComponent.js:350
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
a @ ReactMount.js:104
perform @ Transaction.js:143
s @ ReactMount.js:126
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
o @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:319
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ index.web.js:22

**Comment by ahsanshaokat** [comment]
https://screenshots.firefox.com/aMtI4AjKnmhKet0U/devcall.softwarefunnels.com

**Comment by saghul** [comment]
> Logger.js:125 [conference.js] <e.value>: CONFERENCE FAILED: conference.videobridgeNotAvailable

Here is your error. There seem to be no video bridges available. Check if the jvb is running and restart it just in case.

**Comment by ahsanshaokat** [comment]
how to restart jvb? please let me know if any command

**Comment by saghul** [comment]
What distro are you using? If it's a recent enough Ubuntu, `sudo systemctl restart jitsi-videobridge` will do.

**Comment by spellauge** [comment]
i get the same error string "Unfortunately, something went wrong" when the meet-server has been running for more than n (n >=2 - unsure) days and the first participant joins a meeting after it was created by it's initiator. restarting jicofo seems to be suitable to fix this issue.

**Comment by ahsanshaokat** [comment]
Please have a look on this, console. now i am getting this error,
https://drive.google.com/file/d/1WFs7uFKxsfP0-rTHStPNp9CyMMXo3_te/view?usp=sharing

**Comment by ahsanshaokat** [comment]
Conference call is working good in chrome, but in mozila i cannot see video of other person, why???? plz help

**Comment by saghul** [comment]
ICE seems to have failed, I don't know why that could be different on Firefox. What version are you using?

**Comment by ahsanshaokat** [comment]
57.0.1 (64-bit) Firefox

**Comment by saghul** [comment]
Can you reproduce this with meet.jit.si?

**Comment by ahsanshaokat** [comment]
Now everything is working fine, actually problem was that, i did not open ports, 4443 and 10000 UDP
Thank you so much for your help and kindness.
