### ISSUE TITLE
Video and audio stop working when moderator leaves room and rejoins

### ISSUE THREAD

**Issue by SeveHo** [jitsi/jitsi-meet#2299]
Hello,
since the new release of the stable packages we have the problem that the audio and video is gone for all participants after the moderator leaves the video conference and rejoins it.

You can reproduce this issue by joining a room with two people. After the moderator (the one who entered the room first) reloads the page both participants wont't be able to see or hear each other.

There are no errors in the Chrome dev console and on the server. Also the videobridge is still running after this happens.

Jitsi Meet Version:  jitsi-meet-web_1.0.2441-1_all
JVB Version: jitsi-videobridge_1011-1_amd64
Jicofo Version:  jicofo_1.0-388-1_amd64 
Java Version: 1.8.0_151 from oracle jdk

**Comment by kevin-og** [comment]
Also have observed this behavior as well.  We're running Jibri, and the live stream shows the participants camera, but in the actual meeting, nothing.

**Comment by damencho** [comment]
Do you reproduce this on https://beta.meet.jit.si ?

**Comment by SeveHo** [comment]
Sorry for the late response. Totally forgot to answer after we found the solution.

The issue was caused by the prosody setup. Somehow prosdy wasn't registered at our service. 
This fixed it: 
`sudo prosodyctl register focus auth.jitsi.example.com focuspassword`
