### ISSUE TITLE
When installing chrome screen sharing plugin for the first time via the screen share button in jitsi-meet, an error message displays and the screen share modal does not come up

### ISSUE THREAD

**Issue by spditner** [jitsi/jitsi-meet#2300]
This issue is regarding the Screen Sharing plugin for Google Chrome. There appears to be an order of operation issue between plugin installation and the code's request for the start of a screen share, where the first attempt to click on the screen share results in failure despite successful plugin installation.

Expected behaviour:
* Clicking on screen sharing for the first time should install the plugin
* Upon confirming plugin installation, a modal should appear allowing the user to select what is to be shared

Faulty behaviour:
* Ensure that you do not have the Jitsi screen sharing plugin installed in chrome
* Visit https://beta.meet.jit.si and click on the 'share screen' option, you will be prompted to do so.
* You will then get a red bar across the bottom of the screen informing you that the operation was **not** successful, however the plugin **does** install.
* Clicking on the screen share a second time correctly displays the screen sharing modal

**Comment by damencho** [comment]
Hum, that is strange I just tried it several times and it seems to work fine on my side. Not sure what can be the problem.

**Comment by spditner** [comment]
Are you visiting https://beta.meet.jit.si? I went back and re-tested with with a new user profile in Google Chrome, and in Incognito mode. I now see that it's also failing to prompt for the microphone and camera.

**Comment by damencho** [comment]
Yep, this is known issue for beta, but it is a testing environment and we need the http thing for some reason (cannot remember why, but there is something).
