### ISSUE TITLE
[Android] Failed to discover features of 333@conference.meet.jit.si/8a28fe16

### ISSUE THREAD

**Issue by anhlh011190** [jitsi/jitsi-meet#2301]
When new users enter the room. The users present in the room are appearing error "console.error:"JitsiConference.js","<n>:","Failed to discover features of 333@conference.meet.jit.si/8a28fe16",null".
Can you help me, how to fix it?

**Comment by saghul** [comment]
There is nothing for you to fix there. Sometimes that request will timeout, but it's not important. I'm going to lower the severity to a warning because it seems to give too many false positives.
