### ISSUE TITLE
[Android] android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by sachinrkeche** [jitsi/jitsi-meet#2302]
Hello Developers, 
    I configure the Jitsi meet from the source [https://github.com/jitsi/jitsi-meet](url) .aar file of this for my native Android application and added the react framework [https://github.com/facebook/react-native/tree/master/](url) as a module (simply import ReactAndroid folder) in my project. Which need webrtc i used the dependencies  "org.webrtc:google-webrtc:1.0.+" for my Native Android project while building this project I get the following error.

Error:11:55:37.520 [ERROR] [system.err] Android.mk:44: *** Android NDK: Aborting.    .  Stop.
11:55:37.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:55:37.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:55:37.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:55:37.526 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:55:37.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':ReactAndroid:cleanReactNdkLib'.
11:55:37.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command 'D:\soft\android-ndk-r10e-windows-x86_64\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2
11:55:37.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:55:37.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
11:55:37.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ReactAndroid:cleanReactNdkLib'.
11:55:37.527 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)

[error.txt](https://github.com/jitsi/jitsi-meet/files/1562706/error.txt)

what i tried , 
1 ] I tried on Windows 7, Ubuntu 14.04 and Mac.
2 ] changes NDK use ndk-r10e.
 please help me out.

**Comment by saghul** [comment]
Please **read** the instructions here: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md

Note that you don't *need* to build the SDK yourself, you can use the releases we publish on the Maven repo specified in the documentation.
