### ISSUE TITLE
Cannot establish Video or Audio with Docker

### ISSUE THREAD

**Issue by tiredofit** [jitsi/jitsi-meet#2304]
I've put together a [docker image](https://github.com/tiredofit/docker-jitsi-meet) that combines Nginx, Jicofo, Jitsi-meet and Video Bridge and no matter what I try I still cannot get media to share.

I have tried stable, unstable, nightly, working with Docker "Host" mode (ie not forwarding ports) and via NAT and updating sip-communicator.properties and still nothing.

When I visit the host via my browser I join the room, and can see my full screen video in the browser, however in the small Filmstrip, it is just a black box. If I login using my other system I get the same results, only seeing my own video from that device. I can see another Jitsi'er join the room, but all Filmstrips are blank. In the signal section of the remote user I can see that there is data being transmitted back and forth. I am behind a NAT on the original browser, and have tried behind the same NAT with the other device, or routing through a cellular network.

I believe I have recreated the steps from the Manual Install within my scripts, and notice the same issue when running behind a nginx proxy (in front of the nginx-proxy detailed in the manual), or directly.

I've spent a good 20 hours trying to put this all together, is there any advice that one could give to me?

**Comment by bbaldino** [comment]
Things to check:

See any interesting logs in the js console?
What does chrome://webrtc-internals show? Any errors when setting remote or
local descriptions? Does ICE succeed or is it failing?
Do the jicofo logs show any indication of clients joining?  What about JVB
logs?

**Comment by saghul** [comment]
Typically, when running the jvb inside docker you'd run into a problem because ICE would fail due to incorrect candidates being advertised. You can configure the harvester manually (see the readme in ice4j), but the easiest it to use host mode networking. Also make sure you don't have a local firewall in your machine, and that you are accessing the web interface via HTTPS.

**Comment by huiminsi** [comment]
I encounter the same situation

**Comment by tiredofit** [comment]
I've managed to get everything working now. I encountered quite a few problems, but also learned more about the internals of the systems and their dependencies. I've put together a series of Docker images that work with just editing a few lines in the docker-compose.yml file for proper hostnames.With the exception of JVB they are all running under Alpine Linux.

You can find it [here](https://github.com/tiredofit/docker-jitsi-meet), I wanted to thank you all for being patient and willing to assist in what seemingly are quite a few repeat questions about similar topics.

**Comment by saghul** [comment]
Great work @tiredofit! I'm closing this then :-)
