### ISSUE TITLE
How do you turn on Audio participant.

### ISSUE THREAD

**Issue by thuanbx** [jitsi/jitsi-meet#2311]
Excuse me. I want moderator can turn on/off microphone participant and role participant doesn't turn on/off audio yourself. I had config default turn off audio / video .But I don't nkow How do turn on audio participant in "filmstrip"
Thanks alot

**Comment by saghul** [comment]
You cannot turn a participant's audio on, that's not implemented. Also, even if you turn their mic off, they can turn it back on.
