### ISSUE TITLE
Works only in LAN

### ISSUE THREAD

**Issue by seek1338** [jitsi/jitsi-meet#2313]
Hello,

i installed like your description for Ubuntu and set alle Forwards (443/TCP, 4443/TCP, 10000-20000/UDP) but it only works in the LAN not over the internet. 

If i connect over LAN is see the connect informations IP, Ports but via Internet is see the Client but no Information an only chat works.

I try also some other Ports iv found in the internet and use the internal and external settings from the docs, but nothing works.

can anybody tell me whats the problem, seems to be the ports but there are open?

thanks

best regards,
Seek

**Comment by damencho** [comment]
Have you also setup the settings for jvb as described, the private and public address there?

**Comment by seek1338** [comment]
yes everthink was set up...

big sorry from my side...it was a firewall issue ... i found it after 4h off trying out.. now i was able to connect from 3 different clients and saw the video... everytime i change somethng on the clients (from video to desktop window sharing) the webrtc drops and alle clients are dark...

from one issue in the other :)

i will check the internet if i found a solution for this...

best regards,
Seek

**Comment by damencho** [comment]
Are you testing with chrome or Firefox, we have identified recently a Firefox issue and will be further investigating it these days.

**Comment by seek1338** [comment]
ohh my comment yesterday was not send... i testing via Firefox (newest Version), i will try chrome, would be fine if you have an Update on Firefox to write here because in Chrome the desktopsharing dont works.

thanks for your work and help 🥇

**Comment by damencho** [comment]
Will update when there is something. For chrome you need to publish an extension in chrome webstore and configure it and it will work: https://github.com/jitsi/jidesha

**Comment by classfiy** [comment]
@seek1338 I now meet three people in the room; but I can't work properly; only two people can work properly; three people can't see the picture of each other; should it be jvb not connected? Ask for your help; thank you.

**Comment by classfiy** [comment]
@seek1338 This is a mistake:Not adding remote JVB tracks - no session yet

**Comment by seek1338** [comment]
the problems are solved, sometime with firefox we had the problem that is one participiant join the others dont see the video from the new one, a refresh helps sometimes, but chrome works great with the plugin also screensharing.

the problems was that we had to increase some SYSCTL Values for buffering and UDP optimazion... i think it would be nice if you wrote some info for the SYSCTL Values, becaus you know it at best what Values are the best :)

Now the connections are stable and everythink works with 3-4 participients... dont had the possibility to test more

the firefox problems dont produce an error in the browser console or jvb.log, so its hard to describe without a log output. sometimes it works, sometimes dont!

**Comment by classfiy** [comment]
@seek1338 I installed it quickly; but three people could not work properly; it was found that jvb had not been opened.

**Comment by classfiy** [comment]
@seek1338 I follow this:https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

**Comment by seek1338** [comment]
qucik install works for me on debian (... be sure you open or nat port 80/443 and 10000 UDP... also that you set up:
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>

if your server are behind nat

and i recomend after every change in the configs to reboot the server, just restarting the services not works for me !

**Comment by classfiy** [comment]
@seek1338 You are installing quickly; are there any other configurations? I now use the public network IP configuration; three people can't see the picture.

**Comment by classfiy** [comment]
@seek1338 I use private IP to quickly build three people to see the picture, but use the public network IP to build; three people can not work properly; jvb does not seem to open.

**Comment by damencho** [comment]
@classfiy You need to forward these ports and configure the properties as @seek1338 already mentioned and as this is described here: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
