### ISSUE TITLE
Question: Require OAuth2 login before creating room

### ISSUE THREAD

**Issue by KerryRitter** [jitsi/jitsi-meet#2315]
Is it possible (either through supported extension or reasonable customization) to enable jitsi-meet to require OAuth2 authentication (i.e. Google) before the user can start a new room? So say someone in a company can start a call, but guests may only join. Does the `jitsi/jap` tool supply this functionality?

**Comment by NotSqrt** [comment]
:+1: 

I see some work from @paweldomas at https://github.com/jitsi/jicofo/compare/oauth2_server_side_flow last year.
