### ISSUE TITLE
guest user cant join room when using jwt token

### ISSUE THREAD

**Issue by tanvir23** [jitsi/jitsi-meet#2317]
walkthrough:
OS ubuntu 14.04
installed jitsi-meet using quick install (everything went smoothly)
installed jitsi-meet-tokens  using this ( https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#installing-token-plugin )

now when user login with https://example.com/test?jwt=idgeneratedby.jwt.io room is created successfully and user is granted moderator permission. when the guest user joins the room using https://example.com/test an authentication dialog prompted asking user to key-in username and password but when guest user also uses https://example.com/test?jwt=idgeneratedby.jwt.io then user can join as guest user with no error. 

Question: 
how do I fix this issue? shouldn't it allow any user to join as guest when without a token while if with token it should identify user as moderator?

**Comment by damencho** [comment]
I think you are mixing two approaches which were not designed to work together. 
JWT itself can carry information to which room it has access, and this approach verifies access to certain resources.
While the other approach with authentication and guest domain gives secure access to those creating the rooms and the guests to enter already created rooms.
Maybe you can make it work together, but I'm not sure about that it needs more debugging and checking the code.
What is your usecase?

**Comment by tanvir23** [comment]
thanks @damencho for the clarification. i was just exploring. anyway, i have a very simple external auth service that allows user to login to a dashboard. once they logged in, they can create a room. other registered user can join the room once it is created. if non-registered user wants to join, they can also do so by using url example.com/testroom (once the room is created).
any suggestion which one is more appropriate for my case?

**Comment by tanvir23** [comment]
could anyone give me direction on how to add the second anonymous domain mentioned here ( https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#jitsi-meet-options )

**Comment by damencho** [comment]
I'm not sure what is 'second anonymous domain'?
With tokens, there is no way at the moment to restrict guests waiting for the authenticated user to join. The easiest way is to check whether there is a prosody module or any option to authenticate using your source and use secure domains as described in jicofo doc: https://github.com/jitsi/jicofo#secure-domain
