### ISSUE TITLE
possibility to add HEVC or H265 video codec?

### ISSUE THREAD

**Issue by aditya6992** [jitsi/jitsi-meet#2320]
Hi, will it be possible to somehow add HEVC to jitsi-meet? I know that the current browsers do not support it, but I have found a javascript library that can decode/encode hevc, will it be possible to add it to videobridge/jicofo? If so, how do I proceed?

**Comment by Manouchehri** [comment]
Safari is going to be supporting this, would be nice if Jitsi could use HEVC.

**Comment by saghul** [comment]
I don't think the effort is justified for a single platform.
