### ISSUE TITLE
middleware.js:131 Uncaught (in promise) ReferenceError: a19420 is not defined

### ISSUE THREAD

**Issue by dreaminglwj** [jitsi/jitsi-meet#2326]
Installation succeed， bug when I visit the web error occured:

middleware.js:131 Uncaught (in promise) ReferenceError: a19420 is not defined

is this because of configuration?

**Comment by damencho** [comment]
This doesn't give a lot of information about the problem. Please, send all your console logs.

**Comment by dreaminglwj** [comment]
http://47.95.215.151/index 
This is my ip address, thank you very much!

**Comment by dreaminglwj** [comment]
when runing npm install I got the error info : 
> git-validate@2.2.2 install /srv/47.95.215.151/node_modules/git-validate
> node bin/install


> node-sass@3.13.1 install /srv/47.95.215.151/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> precommit-hook@3.0.0 install /srv/47.95.215.151/node_modules/precommit-hook
> node bin/install


and I visit the website https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-59_binding.node with browser and it really not exist

dos it matters?

**Comment by damencho** [comment]
First your deployment seems to not have https for some reason, this is the first thing you want to fix as webrtc is not working using http. You can see it in the errors: "....Only secure origins are allowed..."
About the error, try deleting node_modules and run npm install again, does this change anything?

**Comment by dreaminglwj** [comment]
I tried three times, now the website works but jicofo went wrong: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by damencho** [comment]
More info about this error:
https://github.com/jitsi/jicofo#certificates
also check the info about auth.jitsi.example.com and 
```
prosodyctl cert generate auth.jitsi.example.com
ln -sf /var/lib/prosody/auth.jitsi.example.com.crt /usr/local/share/ca-certificates/auth.jitsi.example.com.crt
update-ca-certificates
```
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

**Comment by dreaminglwj** [comment]
try rm /etc/ssl/certs/auth.xxxx.pem and then update-ca-certificates  can fix it

**Comment by dreaminglwj** [comment]
middleware.js:131 Uncaught (in promise) ReferenceError: a19420 is not defined

it occurs again after a reinstall ( this time all errors were resovled during installation  )
my ip address https://47.95.215.151/

**Comment by damencho** [comment]
Can you check which versions of node/npm you have installed? 
Try using latest LTS from nodejs.org:
$ node --version
v8.9.3
$ npm --version
5.5.1

**Comment by dreaminglwj** [comment]
all done with newest version of node and npm
thank you so much
