### ISSUE TITLE
Desktop sharing not working

### ISSUE THREAD

**Issue by amrdarweesh** [jitsi/jitsi-meet#2327]
Dear team,

Kindly desktop sharing is not allowed. We got the following error message:
"Screen sharing extension failed to install
Oops! Your screen sharing extension failed to install.
Dismiss                Contact Support "

Please advise.

**Comment by damencho** [comment]
Did you follow the jidesha instructions changing the manifest, uploading the extension in chrome webstore and verifying the site when uploading to chrome webstore developer dashboard, setting the id in config.js?

**Comment by memetb** [comment]
I'm seeing the same behaviour. Sharing screen (and nothing else) from Firefox 58.0 on windows 10, other participant is same version 58.0 on OSX. 

config file has `desktopSharingFirefoxMaxVersionExtRequired: 51`

Client participant still gets "Screen sharing extension failed to install".

(also, I've set all the config file paramters to the sensible values for non extension mode, i.e. nulls and falses)

**Comment by damencho** [comment]
There was a bug, which should already be fixed in unstable packages.
You can try desktopSharingFirefoxMaxVersionExtRequired: '51'
Does this change anything?

**Comment by damencho** [comment]
Put a string not int.

**Comment by memetb** [comment]
Thanks @damencho: this does get rid of the extension failed to install.

However, I should still let you know that a clean spin-up of a digital ocean debian 9 image + the instructions followed for nightly unstable builds (i.e. apt-get installation) gets me the system up and running, but screen sharing simply does not work.

The meeting is established, but as soon as one party initiates screen sharing, the other party sees "username is having connectivity issues...". 

Let me know what you'd need from me in terms of clarifications.

**Comment by alexis619** [comment]
@damencho @bbaldino 
Desktop sharing in conference is not working in jitsi.
For 2 users desktop sharing is working fine, But the 3rd users joins the same conference, desktop sharing doesn't work for any of the users (screen sharing becomes whitish gray and hangs).

Please help me to resolve the issue.

**Comment by damencho** [comment]
@alexis619 https://github.com/jitsi/jitsi-meet/issues/3878 we are looking into it, there is a temp workaround at least for the steps we repro the problem

**Comment by alexis619** [comment]
@damencho , I am having my own jitsi server in Sydney region in aws. But person1 from australia and person2 from india tries to have desktop sharing and its works fine for 5 mins and person1 in australia gets a bandwidth connectivity issue, please help me to rectify and solve the issue.

**Comment by alexis619** [comment]
@damencho, I am having my own jitsi server in Sydney region in aws. But person1 from australia and person2 from india tries to have desktop sharing and its works fine for 5 mins. And person1 in australia gets a bandwidth connectivity issue , please help me to rectify and solve the issue.

**Comment by alexis619** [comment]
@damencho , how to add the secondary videobridge to the main main jitsi-meet server. Please help me to resolve this case to resolve the issue.
