### ISSUE TITLE
Have problem on Jicofo Secure Domain. "guest.example.com" seems not recognized by jitsi-meet

### ISSUE THREAD

**Issue by noorshazmil** [jitsi/jitsi-meet#2329]
Dear All,

I had setup all jitsi components using CentOS 7.
Successfully setup the Jitsi-Meet without authentication.

When I tried to config the prosody with authentication="internal_plain" and change config.js in Jitsi-Meet "anonymousdomain: 'guest.example.com' " , the video conference cant be start.
I already check all the log and there is no error. It is really weird. The log I check are prosody, jvb, jicofo, nginx.

After that, I try to change the config.js in Jitsi-Meet. Comment the "anonymousdomain". The jitsi-meet can be loaded , but anyone need to put the username and password to start the video conference.

It seems there is some misconfiguration in prosody or jitsi-meet.
Anyone have the same problem?

**Comment by noorshazmil** [comment]
It seems, the "guest.example.com" cannot be recognized by jitsi-meet. I don't know where to debug. Because all log does not have error or weird status

**Comment by damencho** [comment]
You have added 
```
VirtualHost guest.jitsi-meet.example.com
    authentication = "anonymous"
```
to the prosody config and you have restarted prosody?

Also your config.js has both:
```          
domain: 'jitsi-meet.example.com',
anonymousdomain: 'guest.jitsi-meet.example.com',
```
?

Did you add `org.jitsi.jicofo.auth.URL=XMPP:jitsi-meet.example.com` to jicofo and restarted it?

**Comment by noorshazmil** [comment]
I'm sure I had added all necessary configuration.

If I change these on config.js
Also your config.js has both:

> domain: 'jitsi-meet.example.com',
> //anonymousdomain: 'guest.jitsi-meet.example.com',

the video conference page with load with popup prompt username and password.

I know if there is no anonymousdomain, anyone need to enter username and password to start video conference. No anonymous allow.

But its really weird. Whenever I try to put 'guest.jitsi-meet.example.com' , the video conference page only load the interface but no local video at all.

**Comment by noorshazmil** [comment]
Is there any method to test the 'guest.jitsi-meet.example.com' is working correctly?

**Comment by damencho** [comment]
Can you share the errors from the js console when you enable guest?

**Comment by noorshazmil** [comment]
Do you means chrome?

Below are the log from Chrome console:

> (TIME) index.html loaded:	 511.61
> Logger.js:125 [modules/RTC/RTCBrowserType.js] <Array.r>:  This appears to be Chrome, ver: 63
> Logger.js:125 [react/index.web.js] <HTMLDocument.<anonymous>>:  (TIME) document ready:	 1092.345
> Logger.js:125 [react/features/base/media/middleware.js] <>:  Start muted: 
> Logger.js:125 [react/features/base/media/middleware.js] <>:  Start audio only set to false
> Logger.js:125 [modules/URL/ConferenceUrl.js] <new e>:  Stored original conference URL: https://www.example.com/test
> Logger.js:125 [modules/URL/ConferenceUrl.js] <new e>:  Conference URL for invites: https://www.example.com/test
> Logger.js:125 [modules/RTC/ScreenObtainer.js] <Object.init>:  Desktop sharing disabled
> Logger.js:125 [modules/RTC/RTCUtils.js] <t.value>:  Using the new gUM flow
> Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  P2P STUN servers:  (3) [{…}, {…}, {…}]
> Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  Lip-sync enabled !
> Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  (TIME) Strophe connecting:	 1254.75
> Logger.js:125 [modules/RTC/RTCUtils.js] <t.<anonymous>>:  Got media constraints:  {video: {…}, audio: {…}}
> app.bundle.min.js?v=139:2 [Violation] 'setTimeout' handler took 91ms
> Logger.js:125 [modules/RTC/RTCUtils.js] <>:  Available devices:  (7) [MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo]
> Logger.js:125 [modules/RTC/RTCUtils.js] <>:  onUserMediaSuccess
> Logger.js:125 [modules/RTC/JitsiLocalTrack.js] <t.value>:  Setting new MSID: a6e20e72-8a5b-4c1d-af5d-b147d31d2f86 01d8a0d7-52c0-4f72-9705-3679a63ea8b0 on LocalTrack[undefined,audio]
> Logger.js:125 [modules/RTC/JitsiLocalTrack.js] <t.value>:  Setting new MSID: 0946e100-5d12-4c0e-95df-16dfb75ec693 75350c1b-5af0-4ce2-8aea-9b5d751ec474 on LocalTrack[undefined,video]
> strophe.js:5594 XHR finished loading: POST "https://www.example.com/http-bind?room=test".
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _connect @ strophe.js:5083
> connect @ strophe.js:3028
> value @ xmpp.js:269
> value @ xmpp.js:329
> r.connect @ JitsiConnection.js:54
> r @ connection.js:38
> (anonymous) @ connection.js:141
> o @ connection.js:86
> t.a @ connection.js:171
> (anonymous) @ conference.js:127
> createInitialLocalTracksAndConnect @ conference.js:137
> (anonymous) @ conference.js:716
> Promise resolved (async)
> init @ conference.js:713
> (anonymous) @ actions.web.js:36
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ Conference.web.js:77
> commitLifeCycles @ react-dom.production.min.js:149
> t @ react-dom.production.min.js:158
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> enqueueSetState @ react-dom.production.min.js:108
> o.setState @ react.production.min.js:12
> (anonymous) @ AbstractApp.js:398
> value @ AbstractApp.js:396
> value @ App.web.js:113
> (anonymous) @ middleware.js:82
> l @ middleware.js:82
> (anonymous) @ middleware.js:22
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> dispatch @ applyMiddleware.js:35
> (anonymous) @ actions.js:52
> Promise resolved (async)
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:126
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ AbstractApp.js:428
> value @ AbstractApp.js:119
> mountClassInstance @ react-dom.production.min.js:110
> beginWork @ react-dom.production.min.js:133
> o @ react-dom.production.min.js:161
> a @ react-dom.production.min.js:161
> s @ react-dom.production.min.js:162
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> updateContainer @ react-dom.production.min.js:175
> (anonymous) @ react-dom.production.min.js:225
> unbatchedUpdates @ react-dom.production.min.js:171
> Qt @ react-dom.production.min.js:225
> render @ react-dom.production.min.js:227
> (anonymous) @ index.web.js:22
> strophe.js:5594 XHR finished loading: POST "https://www.example.com/http-bind?room=test".
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _no_auth_received @ strophe.js:5319
> _connect_cb @ strophe.js:3889
> _onRequestStateChange @ strophe.js:5491
> XMLHttpRequest.send (async)
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _connect @ strophe.js:5083
> connect @ strophe.js:3028
> value @ xmpp.js:269
> value @ xmpp.js:329
> r.connect @ JitsiConnection.js:54
> r @ connection.js:38
> (anonymous) @ connection.js:141
> o @ connection.js:86
> t.a @ connection.js:171
> (anonymous) @ conference.js:127
> createInitialLocalTracksAndConnect @ conference.js:137
> (anonymous) @ conference.js:716
> Promise resolved (async)
> init @ conference.js:713
> (anonymous) @ actions.web.js:36
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ Conference.web.js:77
> commitLifeCycles @ react-dom.production.min.js:149
> t @ react-dom.production.min.js:158
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> enqueueSetState @ react-dom.production.min.js:108
> o.setState @ react.production.min.js:12
> (anonymous) @ AbstractApp.js:398
> value @ AbstractApp.js:396
> value @ App.web.js:113
> (anonymous) @ middleware.js:82
> l @ middleware.js:82
> (anonymous) @ middleware.js:22
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> dispatch @ applyMiddleware.js:35
> (anonymous) @ actions.js:52
> Promise resolved (async)
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:126
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ AbstractApp.js:428
> value @ AbstractApp.js:119
> mountClassInstance @ react-dom.production.min.js:110
> beginWork @ react-dom.production.min.js:133
> o @ react-dom.production.min.js:161
> a @ react-dom.production.min.js:161
> s @ react-dom.production.min.js:162
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> updateContainer @ react-dom.production.min.js:175
> (anonymous) @ react-dom.production.min.js:225
> unbatchedUpdates @ react-dom.production.min.js:171
> Qt @ react-dom.production.min.js:225
> render @ react-dom.production.min.js:227
> (anonymous) @ index.web.js:22
> strophe.js:5594 XHR finished loading: POST "https://www.example.com/http-bind?room=test".
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _no_auth_received @ strophe.js:5319
> _connect_cb @ strophe.js:3873
> _onRequestStateChange @ strophe.js:5491
> XMLHttpRequest.send (async)
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _no_auth_received @ strophe.js:5319
> _connect_cb @ strophe.js:3889
> _onRequestStateChange @ strophe.js:5491
> XMLHttpRequest.send (async)
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _connect @ strophe.js:5083
> connect @ strophe.js:3028
> value @ xmpp.js:269
> value @ xmpp.js:329
> r.connect @ JitsiConnection.js:54
> r @ connection.js:38
> (anonymous) @ connection.js:141
> o @ connection.js:86
> t.a @ connection.js:171
> (anonymous) @ conference.js:127
> createInitialLocalTracksAndConnect @ conference.js:137
> (anonymous) @ conference.js:716
> Promise resolved (async)
> init @ conference.js:713
> (anonymous) @ actions.web.js:36
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ Conference.web.js:77
> commitLifeCycles @ react-dom.production.min.js:149
> t @ react-dom.production.min.js:158
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> enqueueSetState @ react-dom.production.min.js:108
> o.setState @ react.production.min.js:12
> (anonymous) @ AbstractApp.js:398
> value @ AbstractApp.js:396
> value @ App.web.js:113
> (anonymous) @ middleware.js:82
> l @ middleware.js:82
> (anonymous) @ middleware.js:22
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> dispatch @ applyMiddleware.js:35
> (anonymous) @ actions.js:52
> Promise resolved (async)
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:126
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ AbstractApp.js:428
> value @ AbstractApp.js:119
> mountClassInstance @ react-dom.production.min.js:110
> beginWork @ react-dom.production.min.js:133
> o @ react-dom.production.min.js:161
> a @ react-dom.production.min.js:161
> s @ react-dom.production.min.js:162
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> updateContainer @ react-dom.production.min.js:175
> (anonymous) @ react-dom.production.min.js:225
> unbatchedUpdates @ react-dom.production.min.js:171
> Qt @ react-dom.production.min.js:225
> render @ react-dom.production.min.js:227
> (anonymous) @ index.web.js:22
> strophe.js:5594 XHR finished loading: POST "https://www.example.com/http-bind?room=test".
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _no_auth_received @ strophe.js:5319
> _connect_cb @ strophe.js:3873
> _onRequestStateChange @ strophe.js:5491
> XMLHttpRequest.send (async)
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _no_auth_received @ strophe.js:5319
> _connect_cb @ strophe.js:3873
> _onRequestStateChange @ strophe.js:5491
> XMLHttpRequest.send (async)
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _no_auth_received @ strophe.js:5319
> _connect_cb @ strophe.js:3889
> _onRequestStateChange @ strophe.js:5491
> XMLHttpRequest.send (async)
> l @ strophe.js:5594
> _processRequest @ strophe.js:5609
> _throttledRequestHandler @ strophe.js:5755
> _connect @ strophe.js:5083
> connect @ strophe.js:3028
> value @ xmpp.js:269
> value @ xmpp.js:329
> r.connect @ JitsiConnection.js:54
> r @ connection.js:38
> (anonymous) @ connection.js:141
> o @ connection.js:86
> t.a @ connection.js:171
> (anonymous) @ conference.js:127
> createInitialLocalTracksAndConnect @ conference.js:137
> (anonymous) @ conference.js:716
> Promise resolved (async)
> init @ conference.js:713
> (anonymous) @ actions.web.js:36
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ Conference.web.js:77
> commitLifeCycles @ react-dom.production.min.js:149
> t @ react-dom.production.min.js:158
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> enqueueSetState @ react-dom.production.min.js:108
> o.setState @ react.production.min.js:12
> (anonymous) @ AbstractApp.js:398
> value @ AbstractApp.js:396
> value @ App.web.js:113
> (anonymous) @ middleware.js:82
> l @ middleware.js:82
> (anonymous) @ middleware.js:22
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> dispatch @ applyMiddleware.js:35
> (anonymous) @ actions.js:52
> Promise resolved (async)
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:52
> (anonymous) @ actions.js:126
> (anonymous) @ index.js:11
> (anonymous) @ middleware.js:58
> (anonymous) @ middleware.js:35
> (anonymous) @ middleware.js:127
> (anonymous) @ middleware.js:21
> (anonymous) @ middleware.js:39
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:25
> (anonymous) @ middleware.js:36
> (anonymous) @ middleware.js:17
> (anonymous) @ middleware.js:54
> (anonymous) @ middleware.js:12
> (anonymous) @ middleware.js:33
> (anonymous) @ middleware.js:27
> (anonymous) @ middleware.js:34
> (anonymous) @ middleware.js:20
> (anonymous) @ middleware.js:57
> (anonymous) @ middleware.js:80
> (anonymous) @ middleware.js:64
> (anonymous) @ middleware.js:21
> value @ AbstractApp.js:428
> value @ AbstractApp.js:119
> mountClassInstance @ react-dom.production.min.js:110
> beginWork @ react-dom.production.min.js:133
> o @ react-dom.production.min.js:161
> a @ react-dom.production.min.js:161
> s @ react-dom.production.min.js:162
> _ @ react-dom.production.min.js:169
> w @ react-dom.production.min.js:168
> h @ react-dom.production.min.js:167
> p @ react-dom.production.min.js:165
> updateContainer @ react-dom.production.min.js:175
> (anonymous) @ react-dom.production.min.js:225
> unbatchedUpdates @ react-dom.production.min.js:171
> Qt @ react-dom.production.min.js:225
> render @ react-dom.production.min.js:227
> (anonymous) @ index.web.js:22
>
>
> **Logger.js:125 [modules/UI/videolayout/SmallVideo.js] <r.updateView>:  Unable to init avatar - no id r {videoSpanId: "localVideoContainer", container: span#localVideoContainer.videocontainer, $container: Z.fn.init(1), localVideoId: null, isLocal: true, …}
> n @ Logger.js:125
> r.updateView @ SmallVideo.js:595
> (anonymous) @ SmallVideo.js:266
> handle @ jquery.min.js:3
> dispatch @ jquery.min.js:3
> m.handle @ jquery.min.js:3
> Logger.js:125 [modules/UI/videolayout/SmallVideo.js] <r.updateView>:  Unable to init avatar - no id r {videoSpanId: "localVideoContainer", container: span#localVideoContainer.videocontainer, $container: Z.fn.init(1), localVideoId: null, isLocal: true, …}
> n @ Logger.js:125
> r.updateView @ SmallVideo.js:595
> (anonymous) @ SmallVideo.js:271
> handle @ jquery.min.js:3
> dispatch @ jquery.min.js:3
> m.handle @ jquery.min.js:3
> Logger.js:125 [modules/UI/videolayout/SmallVideo.js] <r.updateView>:  Unable to init avatar - no id r {videoSpanId: "localVideoContainer", container: span#localVideoContainer.videocontainer, $container: Z.fn.init(1), localVideoId: null, isLocal: true, …}
> n @ Logger.js:125
> r.updateView @ SmallVideo.js:595
> (anonymous) @ SmallVideo.js:266
> handle @ jquery.min.js:3
> dispatch @ jquery.min.js:3
> m.handle @ jquery.min.js:3
> Logger.js:125 [modules/UI/videolayout/SmallVideo.js] <r.updateView>:  Unable to init avatar - no id r {videoSpanId: "localVideoContainer", container: span#localVideoContainer.videocontainer, $container: Z.fn.init(1), localVideoId: null, isLocal: true, …}
> n @ Logger.js:125
> r.updateView @ SmallVideo.js:595
> (anonymous) @ SmallVideo.js:271
> handle @ jquery.min.js:3
> dispatch @ jquery.min.js:3
> m.handle @ jquery.min.js:3**

The errors only occur after a minute.

**Comment by damencho** [comment]
I don't see something that can point me the error. But I have tested this configuration yesterday with latest unstable and with latest stable and I do not see a problem, which seems like a configuration issue, that's why I was asking for different configs are they there and were the services restarted.
This needs more debugging ... do you see anything in jicofo logs, what about prosody logs.

**Comment by noorshazmil** [comment]
will share you jicofo and prosody logs.
btw, I already check that log. no error at all. 
for prosody logs, it have NEW BOSH created. but, jicofo logs no changes.

may I know which jicofo and jvb you used?
and how to know which version is stable and unstable? "sorry for silly question"

let me try to create new server and manual install jitsi-meet.

btw... forgot to mention. I'm done this on CentOS 7.

**Comment by damencho** [comment]
Stable are those at https://download.jitsi.org/stable/
And if you are using source code you can checkout tag jitsi-meet_2635 everywhere: https://github.com/jitsi/jitsi-meet/releases/tag/jitsi-meet_2635

**Comment by noorshazmil** [comment]
ok thanks.

you are using the latest jicofo and jitsi-videobridge too?

**Comment by damencho** [comment]
I tested latest in unstable, and latest from stable.

**Comment by noorshazmil** [comment]
@damencho may I know which prosody you used?

**Comment by damencho** [comment]
The version running on meet.jit.si - prosody-trunk                         1nightly747-1~xenial

**Comment by noorshazmil** [comment]
@damencho I just solved the problem with guest.example.com.

I'm setup on CentOS 7 and using prosody 0.10 .

I remove the prosody 0.10 and install prosody 0.9 .

The prosody 0.9 can be found at http://mirrors.isu.net.sa/pub/fedora/fedora-epel/7/x86_64/p/
Full link: http://mirrors.isu.net.sa/pub/fedora/fedora-epel/7/x86_64/p/prosody-0.9.12-1.el7.x86_64.rpm

After install prosody 0.9, the secure domain works fine. I'm not sure what cause the problem when using prosody 0.10

**Comment by damencho** [comment]
That is strange, we currently deploy with trunk. With 0.9 or 0.10 is only a problem for jwt. I will test 0.10 to see do I see the same.
