### ISSUE TITLE
Audio Call Only

### ISSUE THREAD

**Issue by webcluesdev** [jitsi/jitsi-meet#2330]
I am able to make the video call using Jitsi-Meet properly.

I want to implement audio call in it. it's work nice with speaker.

when I join the audio conference, In Android it will go on the speaker by default and I don't have any option for speaker off.(there is the only option for audio mute).

Is there any option to make speaker off when audio call start.

Thanks in advance :).

**Comment by webcluesdev** [comment]
I found the solution. We can change it from the setMode function in AudioModeModule.

**Comment by ranggamp** [comment]
hi, @webcluesdev. Anywhere you can show it to me?
Thanks
