### ISSUE TITLE
no sound without p2p mode

### ISSUE THREAD

**Issue by dreaminglwj** [jitsi/jitsi-meet#2331]
p2p: {
        // Enables peer to peer mode. When enabled the system will try to
        // establish a direct connection when there are exactly 2 participants
        // in the room. If that succeeds the conference will stop sending data
        // through the JVB and use the peer to peer connection instead. When a
        // 3rd participant joins the conference will be moved back to the JVB
        // connection.
        enabled: true,

        // Use XEP-0215 to fetch STUN and TURN servers.
        // useStunTurn: true,

        // The STUN servers that will be used in the peer to peer connections
        stunServers: [
            { urls: 'stun:stun.l.google.com:19302' },
            { urls: 'stun:stun1.l.google.com:19302' },
            { urls: 'stun:stun2.l.google.com:19302' }
        ],

if change    enabled: true   to enabled: false  no sound and video transfered

**Comment by damencho** [comment]
With p2p disabled with two participants in the call the media moves through the bridge. 
Is your bridge behind nat (no public address on its interfaces), if yes than did you do all opening/forwarding of ports and configure in jvb its public and private address? 
More info here: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by dreaminglwj** [comment]
I install jitsi follow manual-install.md  

my server is behind a nat Ip is 192.168.11.12 and the public ip is public_ip
questtion:
1.org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=192.168.11.12 or 127.0.0.1?
2.I have tried apt-get install jigasi in another server, and it generated a sip-communicator.properties file like this:
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.139.196.94.152/.*
org.jitsi.videobridge.rest.jetty.host=::
org.jitsi.videobridge.rest.jetty.port=443
org.jitsi.videobridge.rest.jetty.ProxyServlet.hostHeader=139.196.94.152
org.jitsi.videobridge.rest.jetty.ProxyServlet.pathSpec=/http-bind
org.jitsi.videobridge.rest.jetty.ProxyServlet.proxyTo=http://localhost:5280/http-bind
org.jitsi.videobridge.rest.jetty.ResourceHandler.resourceBase=/usr/share/jitsi-meet
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./config.js=/etc/jitsi/meet/139.196.94.152-config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./interface_config.js=/usr/share/jitsi-meet/interface_config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./logging_config.js=/usr/share/jitsi-meet/logging_config.js
org.jitsi.videobridge.rest.jetty.RewriteHandler.regex=^/([a-zA-Z0-9]+)$
org.jitsi.videobridge.rest.jetty.RewriteHandler.replacement=/
org.jitsi.videobridge.rest.jetty.SSIResourceHandler.paths=/
org.jitsi.videobridge.rest.jetty.tls.port=443
org.jitsi.videobridge.TCP_HARVESTER_PORT=443
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePath=/etc/jitsi/videobridge/139.196.94.152.jks
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePassword=changeit

so, what would my sip-communicator.properties file contain?

**Comment by dreaminglwj** [comment]
now throw the log and the data from wireshark I think the ice works, but I get the error log from jvb:
VB 2017-12-28 17:04:50.534 SEVERE: [1781] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[IceUdpTransportManager connect thread,5,main] and message was: null
java.lang.NullPointerException
	at net.sf.fmj.media.rtp.RTPSessionMgr.getAllParticipants(RTPSessionMgr.java:1144)
	at net.sf.fmj.media.rtp.RTPSessionMgr.getReceiveStreams(RTPSessionMgr.java:1323)
	at org.jitsi.impl.neomedia.rtp.translator.RTPTranslatorImpl.getReceiveStreams(RTPTranslatorImpl.java:761)
	at org.jitsi.impl.neomedia.rtp.StreamRTPManager.getReceiveStreams(StreamRTPManager.java:209)
	at org.jitsi.impl.neomedia.MediaStreamImpl.getReceiveStreams(MediaStreamImpl.java:1844)
	at org.jitsi.impl.neomedia.MediaStreamImpl.startReceiveStreams(MediaStreamImpl.java:3075)
	at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:3037)
	at org.jitsi.impl.neomedia.MediaStreamImpl.start(MediaStreamImpl.java:2964)
	at org.jitsi.videobridge.RtpChannel.maybeStartStream(RtpChannel.java:1053)
	at org.jitsi.videobridge.Channel.transportConnected(Channel.java:926)
	at org.jitsi.videobridge.IceUdpTransportManager.onIceConnected(IceUdpTransportManager.java:1726)
	at org.jitsi.videobridge.IceUdpTransportManager.access$700(IceUdpTransportManager.java:51)
	at org.jitsi.videobridge.IceUdpTransportManager$3.run(IceUdpTransportManager.java:1936)

**Comment by damencho** [comment]
You need to set private and public address using the props:
Private should be:
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=192.168.11.12
And for public: org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>

The manual install is using nginx and you have installed jitsi-meet (jitsi-videobridge) on a machine which has java8 which configures the jetty webserver which is embeded in the bridge to serve meet. So the machine with the default quick install and the machine with the manual install need different jvb configurations. But if both are behind nat, both need the properties above.

**Comment by dreaminglwj** [comment]
thank you so much
