### ISSUE TITLE
Can't install package in jitsi app 

### ISSUE THREAD

**Issue by tungns4-topica** [jitsi/jitsi-meet#2336]
i can' link package react-native-pdf in project. 
There is no MainApplication.java file in \android\app\src\main\java\org\jitsi\meet
i am try create this file, but after link package, i can't use it
ERROR: "Invariant Violation: Native component for "RCTPdf" does not exist"

**Comment by saghul** [comment]
What are you trying to do? Adding a new dependency to the project? Can you build it with no changes?

**Comment by tungns4-topica** [comment]
i try create file MainApplication.java and link package "react-native-pdf"
i build success but when i run app 
 ERROR: "Invariant Violation: Native component for "RCTPdf" does not exist"

**Comment by saghul** [comment]
How is that related to the Jitsi Meet project? We already have our own MainActitivity: https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/java/org/jitsi/meet/MainActivity.java.

If you are modifying our project, note that it does not follow the standard React Native project layout.

**Comment by lilei-1** [comment]
I face the same issue. I use another app as entry by a url such as `jitsi-meet://a.com/abc`. I rewrite the hardware back button and end call button to exit app from conference activity. But when I follow the url again. The app stay in welcome activity sometimes. As a resolution, I found that totally exit app is worked. So I need a new module `react-native-exit-app` to exit the app totally not hung up in background. When I add this module, run `react-native link react-native-exit-app`, failed with same error.

**Comment by lilei-1** [comment]
Add config information to `settings.gradle`
Add `compile` directive to `dependencies` section in `sdk/build.gradle`
Add `.addPackage(new RNExitAppPackage())` to `initReactInstanceManager` method in `sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java`

**Comment by tungns4-topica** [comment]
Thank lilei-1, I found it 5 month ago :D

**Comment by lilei-1** [comment]
@tungns4-topica Yeah if you found that, maybe you could post the resolution out.

**Comment by tungns4-topica** [comment]
@lilei-1  Yeah, with tags jitsi-meet-3135 newest, _initReactInstanceManager_ method in _sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java_

**Comment by idrive-pankaj** [comment]
@tungns4-topica can you please share the full solution here?
I am trying to add one package but as there is no mainApplication.java file, I am stuck.

**Comment by duchuy312** [comment]
> @lilei-1 Yeah, with tags jitsi-meet-3135 newest, _initReactInstanceManager_ method in _sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java_

can you share full solution, please
