### ISSUE TITLE
why so difficult to install jitsi meet?

### ISSUE THREAD

**Issue by zhanganl** [jitsi/jitsi-meet#2340]
as an app deplorer, i have no idea to install jitsi, i do not understand what means every step. fuck!fuck jitsi!

**Comment by zhangkehu** [comment]
少侠，要冷静

**Comment by zhanganl** [comment]
@zhangkehu 帮帮我，完全看不明白，快速安装在阿里云上搞不定。留个QQ吧，少侠。

**Comment by zhangkehu** [comment]
@zhanganl 其实我也不懂，不过我不着急弄，我是做Android的，服务器那边我也不清楚，我之前弄过一次，结果是失败了，也是各种原因。我当时是在虚拟机里瞎搞的，关于这个我还真帮不上你，抱歉了。被大佬踩了(┬＿┬)

**Comment by zhangkehu** [comment]
大佬看了一下是中文的讨论，立马关闭了，哈哈，这里不适合中文
