### ISSUE TITLE
Supported browsers and platforms for video conferencing

### ISSUE THREAD

**Issue by arikusu** [jitsi/jitsi-meet#2342]
Is there any official documentation for supported browsers and platforms?

https://meet.jit.si/ seems only to work on Chrome and this seems weird.

**Comment by saghul** [comment]
Any platform with a supported browser should work.  As for supported browsers:

- Chrome (and derivatives, like Opera, etc)
- Firefox (latest release brought in some bugs, I'm not sure if we caught them all)
- Safari (audio only, as it doesn't support H.264)
- Edge (beta)
- IE (via a plugin, so the experience is not great)

I believe we were in the process of putting this more explicitly on our website, bit I've been AFK for a week so I can't confirm.

At any rate, if you see problems with any of the above, please file it as a bug!

**Comment by shiftee** [comment]
> Firefox (latest release brought in some bugs, I'm not sure if we caught them all)

Screensharing fails using firefox 57.0.3 on Ubuntu. It works fine using Chromium.

Would it be the same as this issue https://github.com/jitsi/jitsi-meet/issues/2233 or should I create a new one?

**Comment by saghul** [comment]
> Screensharing fails using firefox 57.0.3 on Ubuntu.

I just tested it on Debian and it's working fine here.  What problem are you running into, exactly?

**Comment by shiftee** [comment]
Maybe try using firefox to firefox.
The issue disappears if one of the browsers is Chromium.

To reproduce:
Open a test room on each machine.
On either machine click the button to start screen-sharing, select a window and click allow.
There is no visible change on the other machine

I am also unable to see the camera of the other side

**Comment by saghul** [comment]
> Maybe try using firefox to firefox.
> The issue disappears if one of the browsers is Chromium.

I tried it alone in the room.



> On either machine click the button to start screen-sharing, select a window and click allow.
> There is no visible change on the other machine
> 
> I am also unable to see the camera of the other side

Well, then that might be something else! Screen-sharing is just a slightly different video stream, but a video stream none the less. So if you get no video from the webcam at all, chances of getting screen-sharing are close to none.

Please open an issue about this and be as detailed as you possibly can.

**Comment by shiftee** [comment]
Issue created here: https://github.com/jitsi/jitsi-meet/issues/2350

**Comment by gniezen** [comment]
On Opera (v56 on Ubuntu 18.04) it's not finding my webcam. It works fine on Chrome and Brave (another Chromium-based browser).

**Comment by tinygvillage** [comment]
> On Opera (v56 on Ubuntu 18.04) it's not finding my webcam. It works fine on Chrome and Brave (another Chromium-based browser).

I tried to install using Brave but hit an error. Any tips you could offer?

**Comment by saghul** [comment]
This issue is really old, please open a new one if you are running into problems @tinygvillage
