### ISSUE TITLE
A problem about prosody

### ISSUE THREAD

**Issue by huiminsi** [jitsi/jitsi-meet#2343]
My software environment:
Vmware 14 pro .  debian-9.3.0 strech, prosody version (0.10.0-1~stretch4).
bind version 9.10.3. 
I installed prosody ,  in order to check the result ,  I run 
**prosodyctl  check** ,the result are shown as follows .

**root@debian:/etc/bind# prosodyctl  check**
Checking config...
Done.

   Failed to determine the external addresses of this server. Checks may be inaccurate.
Checking DNS for host auth.jitsi.example.com...
    No _xmpp-client SRV record found for auth.jitsi.example.com, but it looks like you need one.
    No _xmpp-server SRV record found for auth.jitsi.example.com, but it looks like you need one.
    auth.jitsi.example.com A record points to internal address, external connections might fail
    Host auth.jitsi.example.com does not seem to resolve to this server (IPv6)
    Only some targets for auth.jitsi.example.com appear to resolve to this server.

Checking DNS for host jitsi.example.com...
    No _xmpp-client SRV record found for jitsi.example.com, but it looks like you need one.
    No _xmpp-server SRV record found for jitsi.example.com, but it looks like you need one.
    jitsi.example.com A record points to internal address, external connections might fail
    Host jitsi.example.com does not seem to resolve to this server (IPv6)
    Only some targets for jitsi.example.com appear to resolve to this server.

Checking DNS for component conference.jitsi.example.com...
    No _xmpp-server SRV record found for conference.jitsi.example.com, but it looks like you need one.
    conference.jitsi.example.com A record points to internal address, external connections might fail
    Host conference.jitsi.example.com does not seem to resolve to this server (IPv6)
    Only some targets for conference.jitsi.example.com appear to resolve to this server.
    DNS records are necessary if you want users on other servers to access this component.

Checking DNS for component jitsi-videobridge.jitsi.example.com...
    No _xmpp-server SRV record found for jitsi-videobridge.jitsi.example.com, but it looks like you need one.
    jitsi-videobridge.jitsi.example.com A record points to internal address, external connections might fail
    Host jitsi-videobridge.jitsi.example.com does not seem to resolve to this server (IPv6)
    Only some targets for jitsi-videobridge.jitsi.example.com appear to resolve to this server.
    DNS records are necessary if you want users on other servers to access this component.

For more information about DNS configuration please see http://prosody.im/doc/dns

 ### Why always appear   "No _xmpp-client SRV record" "No _xmpp-client SRV record "

**Comment by huiminsi** [comment]
I have checked this : https://prosody.im/doc/dns#srv_records
Here says:

Following the previous example of a server 'example.com' wanting to delegate its XMPP services to the server at 'xmpp.example.com', here are some example records: 
_xmpp-client._tcp.example.com. 18000 IN SRV 0 5 5222 xmpp.example.com.
 _xmpp-server._tcp.example.com. 18000 IN SRV 0 5 5269 xmpp.example.com. 

My question is  where shoud I add the  "example records" ?  I have deploy the bind dns server ,but I don't know where to add the record.

**Comment by bgrozev** [comment]
You don't need any of these records for Jitsi-Meet.
