### ISSUE TITLE
There is an error ,when I Start the videobridge 

### ISSUE THREAD

**Issue by huiminsi** [jitsi/jitsi-meet#2344]
There is an error ,when I Start the videobridge with the following
./jvb.sh --host=localhost --domain=jitsi.example.com --port=5347 --secret=YOURSECRET1 &

JVB 2018-01-01 23:22:04.066 FINE: [45] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: **<**iq id="T7R2s-21" type="result" to="jitsi-videobridge.jitsi.example.com" from="jitsi.example.com"**/>**

This tip is always recurring , and the number after FINE in the square brackets increase 1 each time.  
There must be something wrong , I guess.

**Comment by bgrozev** [comment]
This is normal, it just indicates that the bridge received an XMPP message (probably a reply to a ping that it sent).
