### ISSUE TITLE
how to debug connection?

### ISSUE THREAD

**Issue by kosmosby** [jitsi/jitsi-meet#235]
i see a new user if somebody joined but i don't have video-audio channel. Please suggest how to debug it. My link is http://dev.cloudinterpreter.com:8901/1

Thanks.

**Comment by kosmosby** [comment]
after deeply reading setup documentation i have audio signal, but still no video, heeelp

**Comment by kosmosby** [comment]
it works now, but how to automatically turn on video camera?

**Comment by kosmosby** [comment]
it worded, thanks

**Comment by gpolitis** [comment]
@kosmosby have you solved the issue? Is it OK to close it?
