### ISSUE TITLE
Etherpad do not display on latest source code.

### ISSUE THREAD

**Issue by ZuzooVn** [jitsi/jitsi-meet#2351]
Hi,

Currently, I run Jitsi-meet on my localhost.

I add the following to `/etc/jitsi/meet/MY_DOMAIN-config.js`

`etherpad_base: 'https://whiteboard.buddhikajay.pro/whiteboard/'
`

And here 's my interface_config.js

```
 TOOLBAR_BUTTONS: [

        // main toolbar
        'microphone', 'camera', 'desktop', 'invite', 'fullscreen', 'fodeviceselection', 'hangup',

        // extended toolbar
        'profile', 'contacts', 'info', 'chat', 'recording', 'etherpad', 'sharedvideo', 'settings', 'raisehand', 'videoquality', 'filmstrip' ],
```

But I can not see the etherpad button on the toolbar. What's wrong with me?

Thanks,
Nam Vu

**Comment by damencho** [comment]
That is strange, this is enough for enabling it. 
If you open the html source you should see the interface config inside it, do you see the etherpad in there? 
Can it be caching, what about refreshing, does it fix it?

**Comment by ZuzooVn** [comment]
@damencho 

> If you open the html source you should see the interface config inside it, do you see the etherpad in there?

Yes, there is etherpad_base: 'MY_DOMAIN'

>Can it be caching, what about refreshing, does it fix it?

Hard refresh did not fix it, I used another web browsers, but nothing change.

**Comment by damencho** [comment]
No, I was asking about etherpad in TOOLBAR_BUTTONS, this should be inside:
var interfaceConfig = {.....

**Comment by damencho** [comment]
Just to make sure that the interface config that is used is the correct one, the values loaded in the browser.

**Comment by ZuzooVn** [comment]
@damencho 
Here is HTML Source code
```
var interfaceConfig = {
  
  TOOLBAR_BUTTONS: [
  
  // main toolbar
   'microphone', 'camera', 'desktop', 'invite', 'fullscreen', 'fodeviceselection', 'hangup',
   
  // extended toolbar
  'profile', 'contacts', 'info', 'chat', 'recording', 'etherpad', 'sharedvideo', 'settings', 'raisehand', 'videoquality', 'filmstrip' ],
```

Currently, I am using https://github.com/jitsi/jitsi-meet/commit/fb6f1bdba0da95c0f770a9438709710540998fba version

**Comment by ZuzooVn** [comment]
@damencho WDYT of my issue?

**Comment by damencho** [comment]
This is strange and should work with the settings you describe. Is your deployment publicly accessible? Can you send me, privately, a link so I can test, send it to damencho at jitsi.org.

**Comment by ZuzooVn** [comment]
That is strange, It worked like a champ after updating to https://github.com/jitsi/jitsi-meet/commit/64c5ae1c485916d982cf97bb414186c5625a1d59

Thanks for your help.
