### ISSUE TITLE
Jitsi-Meet on Caddy

### ISSUE THREAD

**Issue by Abdulla-B** [jitsi/jitsi-meet#2358]
Hi All,

Checking the manual installation I noticed that Jitsi uses Nginx in the documentation, but I was wondering if anyone had any luck setting it up with Caddy? Caddy does not support Server side include (SSI) but has templates that should be better but I lack the knowledge of using them. This isn't much of an issue, but I'm not sure where to post in order to get assistance in getting it to run with Caddy.

Thanks!

**Comment by derhagen** [comment]
I'm also trying to get it run behind a Caddy proxy. With docker, it's pretty easy, to set up the HTTP only mode and let Caddy take care of the rest. Here, it seems to be more complicated.

**Comment by ruizdiazever** [comment]
Support to Caddy guys please.

**Comment by damencho** [comment]
Is there an official debian package?

**Comment by aaronkvanmeerten** [comment]
Caddy can be used as an ingress if you like, but you still want to forward to our nginx as it's configured not just for the SSI, but also includes rate limiting configuration to avoid prosody overload, as well as the logic for sorting requests to the various components.  Re-implementing all this in one go in Caddy was non-trivial.  I gave it a go a few months ago but came to the conclusion that the benefits of Caddy weren't enough to switch to it entirely, and that it can still be used in front of the nginx without much additional processor cost if folks need Caddy-like behavior for SSL, etc.
