### ISSUE TITLE
How to change the video interface UI on ios or android

### ISSUE THREAD

**Issue by xioamins** [jitsi/jitsi-meet#2359]
I want to modify the UI layout of the meeting interface on ios or android, but I did not find a way

**Comment by tushar-patil-android** [comment]
@xioamins Did you find an appropriate solution. Because I also looking for the same change.

**Comment by saghul** [comment]
You can start by looking into Conference.native.js, that's the conference view on mobile.

**Comment by tajoumal** [comment]
Hey, not sure if this is of help, but you can configure the visibility of UI elements from the OpenFire plugin view. In the Interface section.

**Comment by saghul** [comment]
The OpenFire plugin provides a different UI, though it's not built on top Jitsi Meet, but on top of the underlying components.

I'm closing this, please holler if you need it reopened.
