### ISSUE TITLE
Quick Install Options

### ISSUE THREAD

**Issue by atb00ker** [jitsi/jitsi-meet#2360]
During quick-install of jitsi-meet; it asks for a hostname and certificate option.
I wish to by-pass that, so that i can automate the process without any human intervention.
Can i pass arguments somehow as in `apt-get install jisti-meet --hostname=www.abcd.com --certficate=option1`
If that isn't possible; is passing arguments planned for future?

**Comment by damencho** [comment]
This is not possible using arguments. But these are debconf values and there is a standard way to pre-set debconf values. 

echo "jitsi-videobridge jitsi-videobridge/jvb-hostname string my-domain" | debconf-set-selections
echo "jitsi-meet jitsi-meet/cert-choice select Self-signed certificate will be generated" | debconf-set-selections
Or
echo "jitsi-meet jitsi-meet/cert-path-crt string /etc/ssl/my-domain.crt" | debconf-set-selections
echo "jitsi-meet jitsi-meet/cert-choice select A certificate is available and the files are uploaded on the server" | debconf-set-selections
echo "jitsi-meet jitsi-meet/cert-path-key string /etc/ssl/my-domain.key" | debconf-set-selections
