### ISSUE TITLE
get participants count not working

### ISSUE THREAD

**Issue by quickstreamingmedia** [jitsi/jitsi-meet#2369]
participant count is not working can some one quickly help setting up. that

**Comment by quickstreamingmedia** [comment]
var domain = "https://portal.gopandoratv.com";
var room = "roomq";
var width = 700;
var height = 180;
var htmlElement = undefined;
var configOverwrite = {};
var interfaceConfigOverwrite = {
filmStripOnly: true
};
var api = new window.JitsiMeetExternalAPI(domain, room, width, height,
htmlElement, configOverwrite, interfaceConfigOverwrite);
api.addEventListener("videoConferenceJoined", function(object){
console.log(object);
});
console.log(api.getNumberOfParticipants());

giving 0 all the time

**Comment by saghul** [comment]
That is too early to check for the participant count. Listen to the 'participantJoined' event, which you'll get for every participant in the room, so you'll see that number climb.

**Comment by quickstreamingmedia** [comment]
I didn’t check too early I did count after there is 2 participants in room and call Is initiated as well.

**Comment by quickstreamingmedia** [comment]
It is also helpful is you could share a little code just one line

**Comment by quickstreamingmedia** [comment]
And this is we need for mobile application to check how many participants in the room

**Comment by quickstreamingmedia** [comment]
@saghul please give a line code where we could  get solution

**Comment by saghul** [comment]
Try this:

```
var domain = "https://portal.gopandoratv.com";
var room = "roomq";
var width = 700;
var height = 180;
var htmlElement = undefined;
var configOverwrite = {};
var interfaceConfigOverwrite = {
    filmStripOnly: true
};
var api = new window.JitsiMeetExternalAPI(domain, room, width, height,
    htmlElement, configOverwrite, interfaceConfigOverwrite);
api.addEventListener("participantJoined", function(object){
    console.log(object);
    console.log(api.getNumberOfParticipants());
});
```

**Comment by quickstreamingmedia** [comment]
i have done it thanks
