### ISSUE TITLE
Error building iOS app

### ISSUE THREAD

**Issue by sunilkumarmohanty** [jitsi/jitsi-meet#2370]
Hi,

I am getting the below error message when I am building the iOS app from XCode in debug mode. It works fine when I use the release mode or if I run using the command
`react-native run-ios --device
`
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTLinkingManager", referenced from:
      objc-class-ref in JitsiMeetView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Showing Recent Messages
  "_OBJC_CLASS_$_RCTLinkingManager", referenced from:
      objc-class-ref in JitsiMeetView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by saghul** [comment]
Did you install all the pods?

**Comment by sunilkumarmohanty** [comment]
I did install the pod. I am able to build the app using react-native command. I face issue only when I build it using Debug mode and from XCode.

**Comment by saghul** [comment]
Hum, did you change any settings in the project? The react-native CLI also does a Debug build, so I'd ex[ect tp get the same results.

**Comment by sunilkumarmohanty** [comment]
No, I did not make any changes to the project settings except for adding my signing certificates

**Comment by saghul** [comment]
What steps did you follow to make the build? Please be as detailed as you possibly can.
