### ISSUE TITLE
add Jitsi Meet SDK for iOS have error nil object from objects[0]

### ISSUE THREAD

**Issue by kiempq** [jitsi/jitsi-meet#2377]
i did step follow https://github.com/jitsi/jitsi-meet/tree/master/ios

but have error:
018-01-10 16:23:56.237527+0700 TestJitsi[13325:346396] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f08712b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000108886f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f0c70cc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010ef9b951 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010ef9b7db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   JitsiMeet                           0x00000001073d6d42 -[AppInfo constantsToExport] + 289
	6   JitsiMeet                           0x0000000107423675 __32-[RCTModuleData gatherConstants]_block_invoke + 46
	7   JitsiMeet                           0x0000000107472da7 RCTUnsafeExecuteOnMainQueueSync + 35
	8   JitsiMeet                           0x0000000107423594 -[RCTModuleData gatherConstants] + 229
	9   JitsiMeet                           0x00000001073e722c __52-[RCTBatchedBridge prepareModulesWithDispatchGroup:]_block_invoke + 116
	10  libdispatch.dylib                   0x0000000110c972f7 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x0000000110c9833d _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000110ca3766 _dispatch_main_queue_callback_4CF + 993
	13  CoreFoundation                      0x000000010f049e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x000000010f00e462 __CFRunLoopRun + 2402
	15  CoreFoundation                      0x000000010f00d889 CFRunLoopRunSpecific + 409
	16  GraphicsServices                    0x0000000111f3c9c6 GSEventRunModal + 62
	17  UIKit                               0x00000001091235d6 UIApplicationMain + 159
	18  TestJitsi                           0x00000001070e5b47 main + 55
	19  libdyld.dylib                       0x0000000110d14d81 start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by kurniadi92** [comment]
any ideas for this ? i got same error.

**Comment by reimertz** [comment]
Same issues. I've tried copy-paste the environment of jitsi-meet down to each individual build settings but still get the same issues.

**Comment by saghul** [comment]
Sorry folks, I'm afraid I haven't seen this one :-( Can you provide some details on when it happens? MAybe upload a compressed simple test app?
