### ISSUE TITLE
WHy I use firefox start a video call, but can not see the man in the other side

### ISSUE THREAD

**Issue by kyle-kai** [jitsi/jitsi-meet#2378]
I started video call with firefox, and another one on the other side use chrom or firefox, we just can not see each other.
Only if I use chrome, it is OK.
Does somebody know what is wrong?

**Comment by saghul** [comment]
What Firefox version are you using?

**Comment by damencho** [comment]
Maybe you are hitting https://github.com/jitsi/jitsi-videobridge/pull/590, which still hasn't made its way to meet.jit.si.
