### ISSUE TITLE
when i try enter recording token in a popup window have an error

### ISSUE THREAD

**Issue by kosmosby** [jitsi/jitsi-meet#238]
when i try enter recording token in a popup window have an error

Uncaught TypeError: undefined is not a functionapp.bundle.js?v=11:14702 Recording.toggleRecordingapp.bundle.js?v=11:14695 (anonymous function)app.bundle.js?v=11:4727 (anonymous function)jquery-2.1.1.min.js:3 n.event.dispatchjquery-2.1.1.min.js:3 n.event.add.r.handlejquery-2.1.1.min.js:3 n.event.triggerjquery-2.1.1.min.js:3 (anonymous function)jquery-2.1.1.min.js:2 n.extend.eachjquery-2.1.1.min.js:2 n.fn.n.eachjquery-2.1.1.min.js:3 n.fn.extend.triggerjquery-impromptu.js:114 (anonymous function)jquery-2.1.1.min.js:3 n.event.dispatchjquery-2.1.1.min.js:3 n.event.add.r.handle

you can see it here: http://dev.cloudinterpreter.com:8901/ImpoliteGoatsEatWeakly

**Comment by hristoterezov** [comment]
Fixed in fdada53
