### ISSUE TITLE
Jitsi-meet capturing hover event on screen

### ISSUE THREAD

**Issue by mlelyakan** [jitsi/jitsi-meet#2385]
How can I edit hover event on screen? I need to make some changes related with the primary and secondary toolbars' hide and show animations. I've reviewed the documentation of jitsi. But I couldn't find anything. Is it possible to do ?
![jitsi](https://user-images.githubusercontent.com/25706791/34906019-65697514-f875-11e7-9b37-2c7382d14373.jpg)

**Comment by enlicayomer** [comment]
Hello Lemi,
I found this for you: if you disable the showToolbox method in your ./react/features/conference/components/Conference.web.js file, the toolbox will not open.

**Comment by mlelyakan** [comment]
Hello @enlicayomer, thanks for your help. I'll try it. :)
