### ISSUE TITLE
don't see recorded files in jitsi-meet

### ISSUE THREAD

**Issue by kosmosby** [jitsi/jitsi-meet#239]
When i click the recording button in jitsi-meet and enter token recording button flash-up and nothing going on.

the link for conference is http://dev.cloudinterpreter.com:8901/AncientCreaturesAskEverywhere

i use google chrome Version 40.0.2214.115 (64-bit) on OS X Yosemite Version 10.10.2 
and for the server:

Description:	Ubuntu 14.04.1 LTS
Release:	14.04
x86_64

the folder i selected for records is empty.
my sip-communicator file is:

org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
org.jitsi.videobridge.ENABLE_MEDIA_RECORDING=true
org.jitsi.videobridge.MEDIA_RECORDING_PATH=/home/kosmos/jitsi/recs/
org.jitsi.videobridge.MEDIA_RECORDING_TOKEN=111

**Comment by bgrozev** [comment]
Please use the dev@jitsi.org mailing list for questions.
