### ISSUE TITLE
Stereo audio instead of mono

### ISSUE THREAD

**Issue by itf** [jitsi/jitsi-meet#2395]
Is it possible to deactivate echoCancellation in the webrtc connection and then set the audio to stereo instead of mono?

**Comment by saghul** [comment]
Can you try this?

https://meet.jit.si/test123#config.disableAP=true&config.disableAEC=true

This will disable echo cancellation, which should be enough to get stereo support.

**Comment by itf** [comment]
This disables echo cancellation and makes the output stereo. Thanks!

**Comment by saghul** [comment]
Excellent, thanks for confirming!

**Comment by spatialaudiolabs** [comment]
Where is stereo supported tho? Chrome only? Firefox? and what about the mobile apps?

**Comment by Cdddo** [comment]
Is there a simple way to enable stereo in the web interface without url parameters?

**Comment by derEremit** [comment]
well
did a lot of research and the culprit is
it only works with firefox
at least if you stream stereo with firefox the mono sound in chrome is better quality
https://endless.ersoft.org/pulseaudio-loopback/
