### ISSUE TITLE
Connection reconect when start conference

### ISSUE THREAD

**Issue by fuentes277** [jitsi/jitsi-meet#2398]
Hello
when start conference , the service jitsi reconect 5 or 6 seg..
what the problem?
![seleccion_007](https://user-images.githubusercontent.com/35070708/35141726-40352b54-fcfc-11e7-8896-bdf02af0a389.png)

**Comment by saghul** [comment]
Can you please show us the console logs? Is this meet.jit.si or your own infrastructure?
