### ISSUE TITLE
Android app mishandles whitespaces in room names.

### ISSUE THREAD

**Issue by eggpi** [jitsi/jitsi-meet#2403]
Hi, I've seen problems with the Jitsi Meet Android app on two different devices when trying to join rooms with whitespaces in their names.

On my Nexus 5X running Android 8.1.0 and app version 1.13.71, when attempting to join a room named, for instance, "a b", I initially get a red screen with an error message ("Unfortunately, something went wrong").

I do seem to join the room after a retry and I see "a%20b" on my room history later, though I suppose an unescaped "a b" would have been much more user-friendly. Interestingly, for a trailing whitespace, it seems to get stripped eventually: if I try "a ", I get the same error, but after the retry and successful connection, "a" shows up in the history.

I've observed the same behavior on a Samsung Galaxy Tab 4 running Android 5.0.2 and same app version. The tablet is a bit more concerning because its autocorrect happens to add a trailing whitespace to the room name if the user accepts its suggestion as the room name is being typed, so this error condition may be more likely to happen.

I don't have easy access to the tablet, but let me know if you need any logs from the phone.

Thanks!

**Comment by saghul** [comment]
This was fixed on https://github.com/jitsi/jitsi-meet/pull/2388 and will be part of the next release. Cheers!

**Comment by eggpi** [comment]
Nice, thank you! Would that also fix the URL-encoding showing up in the chat history? That is, I think it would make more sense to see "my chat room" than "my%20chat%20room" in the history.

**Comment by saghul** [comment]
It will show the room name without spaces.
