### ISSUE TITLE
Quick install doesn't ask for hostname?

### ISSUE THREAD

**Issue by onetonfoot** [jitsi/jitsi-meet#2405]
The first time I installed jitsi-meet using `apt-get install`  ,the videobridge would ask for a hostname, which made the set up smooth. However having removed it using `apt-get purge`, on subsequent reinstalls it does not ask for a hostname?

**Comment by saghul** [comment]
Have you removed all components? Or just the bridge?

You can query the debconf database with debconf-show <package name>:

```
# debconf-show jicofo
  jicofo/jicofo-authpassword: (password omitted)
  jicofo/jicofosecret: (password omitted)
  jicofo/jicofo-authuser: focus
* jitsi-videobridge/jvb-hostname: saghul.jitsi.net
```

**Comment by saghul** [comment]
Yes.
