### ISSUE TITLE
is it possible to make a nginx load balancing to different servers for  jitsi-meet 

### ISSUE THREAD

**Issue by edisonchen1985** [jitsi/jitsi-meet#2406]
hi guys, we have been using jitsi-meet for quite a while, everything is great but the connection qualities go down from time to time, even we need to rejoin the room to get the connection again.  Especially when there are more than 8 people joining the same video conference room, the situation is more obviously. 

Our jitsi-meet runs on a Ubuntu server of 16 GB memory, 4 core processors. I am not quite sure for the internet width, but it should not be a issue. When we do the monitoring on the server, ever since there are more than 8 or 10 people connecting the jitsi-meet at the same time, the CPU will reach 100% to 120%, and the video qualities become very bad. 

So we are wondering if there is a nginx proxy way to load balance to different servers with jitsi-meet, then each server will not be given too much workload, is it possible for that?

Thanks  in advance for any help!

**Comment by damencho** [comment]
So the cpu 100-120 out of 4 processors, this means the load is around 25% on the machine... 
So you say that quality degrades over time and after reconnecting it works again? Which version of jvb are you using?
The http requests are only used for signaling and very lightweight, normally the load that is significant and you want to distribute it is jvb and it is not the cpu that is hit, but the network constraints. And you can always add few jvbs to the same jicofo instances and jicofo will load balance them. But mind that for a single conference it uses one jvb, so if you want to distribute a big conference to several jvb instances, this is currently not possible.
