### ISSUE TITLE
Implement OMEMO beside OTR

### ISSUE THREAD

**Issue by dampfklon** [jitsi/jitsi-meet#2409]
It would be great if you could support [OMEMO](https://en.wikipedia.org/wiki/OMEMO) E2E-Encryption besides OTR as the OMEMO protocol it provides "multi-end to multi-end encryption, allowing messages to be synchronized securely across multiple clients, even if some of them are offline"

**Comment by damencho** [comment]
I suppose you are using the wrong issue tracker. For jitsi-desktop client there is already open issue about OMEMO
https://github.com/jitsi/jitsi/issues/199
