### ISSUE TITLE
Quick install guide: how to start/ stop jitsi meet ?

### ISSUE THREAD

**Issue by kinnla** [jitsi/jitsi-meet#241]
I am really impressed how easy it is to install jitsi meet on debian. Excellent quick install guide. Also good that you explain how to uninstall it.

However, the guide doesn't explain how to start/ stop the server. Is there any documentation about it? 

Suggestion: add this information to the install guide or link to it.

**Comment by bgrozev** [comment]
There are a few different server applications -- nginx, prosody, jicofo, jitsi-videobridge
They can all be controlled through the /etc/init.d scripts, e.g.
/etc/init.d/XXX {stop,start, restart}

I agree about adding it to the guide.

**Comment by kneeki** [comment]
I'm unable to get my Jitsi-Meet server back online after it has apparently crashed. I'm looking through the log files now to see why, but I'm unable to restart Jitsi Meet because I'm ashamed to say I don't know the command, nor can I find it within any of the documentation. So far I've tried:

```shell
sudo /etc/init.d/prosody start
sudo /etc/init.d/jicofo start
sudo /etc/init.d/jitsi-videobridge start
```

**Comment by saghul** [comment]
Try with `restart` instead of `start`. Also check the logs in `/var/log/jitsi/`.

**Comment by kneeki** [comment]
Ah, thank you!

**Comment by jidanni** [comment]
Now that is started, what to do next?!?!
There is no instructions anywhere!

**Comment by rasos** [comment]
@jidanni you may want to run your own, customized instance of jitsi-meet

**Comment by bbrout** [comment]
I found you couldn't stop the server even though I ran these commands:

sudo /etc/init.d/prosody start
sudo /etc/init.d/jicofo start
sudo /etc/init.d/jitsi-videobridge start

I could still sign onto my jitsi server. I added a 

sudo service nginx stop

and a 

sudo service nginx start

to the beginning of a couple of scripts to turn off and turn on the jitsi server and all seems to work well.

**Comment by bittin** [comment]
This thread helped me today years later :)

**Comment by heidemn** [comment]
This worked for me:

```
sudo /etc/init.d/prosody start
sudo /etc/init.d/jicofo start
sudo /etc/init.d/jitsi-videobridge2 start    ## needed to add the "2"
sudo /etc/init.d/nginx restart
```
