### ISSUE TITLE
super.onCreate error.. No virtual method setJSMainModuleName?

### ISSUE THREAD

**Issue by HelloEgg** [jitsi/jitsi-meet#2411]
Okay so I successfully added dependencies: 
(implementation('org.jitsi.react:jitsi-meet-sdk:1.9.0') and 
 maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
)
Also, I skipped cd /android ./gradlew :sdk:assembleReleases because it did not work at all.. but I successfully installed react-native and added dependencies as above.
However, as I was following along with example in https://github.com/jitsi/jitsi-meet/tree/master/android, I constantly get the following error:

java.lang.NoSuchMethodError: No virtual method setJSMainModuleName(Ljava/lang/String;)Lcom/facebook/react/ReactInstanceManagerBuilder; in class Lcom/facebook/react/ReactInstanceManagerBuilder; or its super classes (declaration of 'com.facebook.react.ReactInstanceManagerBuilder' appears in /data/app/com.awesomeproj-1/split_lib_dependencies_apk.apk)

This occured at : super.onCreate(savedInstanceState);
What do you think would have cause problem?? Please help...

**Comment by saghul** [comment]
What are you trying to do? Adding the SDK to an existing project or building the project itself?

**Comment by HelloEgg** [comment]
I am trying to add SDK.. So I built the example react-native program provided by react native organization.. It did build on my Galaxy S6, obviously. But when I added SDK like the way stated above and typed the demo code from 
https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/java/org/jitsi/meet/MainActivity.java
The app crashes.. Do you have any ideas?? thank you very much in advance!

**Comment by HelloEgg** [comment]
I also tried extending activity with AppCompatActivity and invoke JitsiMeetView, however it showed same error. My best guess is maybe compile "com.facebook.react:react-native:+" in build.gradle:app is somehow deprecated or is not synced properly??

**Comment by saghul** [comment]
The SDK is "native" as in, it uses react-native internally, but it doesn't expose it to consumers. If you start a React Native app and then add the SDK, you need to make sure the React Native version matches, otherwise you are going to run into this. IIRC 1.9 used RN 0.49.

**Comment by HelloEgg** [comment]
Hmm.. I downgraded RN version to 0.49.5 but the same error occurs.. perhaps not adding compileOptions could be a problem? I did not know how to add it so I just skipped it..

**Comment by HelloEgg** [comment]
Here is an interesting turn of event...
Since 0.49.5 version of react-native, the "index.android.js" and "index.ios.js" are merged to app.js.
I looked at the source code of JitsiMeetView and setJSMainModuleName("index.android") could be one of the causes of error because it looks for index.android while it is moved since 0.49.5
The problem is, however, even though I ran "npm install react-native@0.49.0" and react-native --version showed 0.49.0, the same error shows up... Am I missing a step while downgrading react-native?

**Comment by kamran1** [comment]
same problem  here 
@HelloEgg  did you find the solution ?

**Comment by lizi0588** [comment]
@HelloEgg  did you find the solution ?
please share the solution
