### ISSUE TITLE
react-native run-android

### ISSUE THREAD

**Issue by cirelramos** [jitsi/jitsi-meet#2412]
how i can make an apk for android?

**Comment by cirelramos** [comment]
https://drive.google.com/file/d/1t2iqqyrO7XXJOfG5TNdj1jK5BH_JIh8u/view?usp=sharing

**Comment by HelloEgg** [comment]
I ran in to similar problem few minutes ago(if not all)

Please refer to answer from stackoverflow: 
https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

**Comment by saghul** [comment]
After you have installed all dependencies, you'll need to make sure you can sign the package (see here: https://facebook.github.io/react-native/docs/signed-apk-android.html) and then build it with `./gradlew assembleRelease`.

@HelloEgg Yours is another problem, please don't mix issues.

**Comment by HelloEgg** [comment]
@saghul  I ran in to @cirelramos 's exact problem before I got current problem I queried on github...
