### ISSUE TITLE
armv7i package for video bridge/meet

### ISSUE THREAD

**Issue by WCat13** [jitsi/jitsi-meet#2413]
I was wondering if there has been any thought into making a package for arm. I have a stretch lxc container I am itching to set this up on.

Can it be built with arm maven? Is there any resource for doing this that anyone knows of? Has anyone done this successfully? 

I would like to run this on my Turris Omnia router. Kind of a fringe deployment I know.

Apologize if this is wrong place for feature requests.
regards

**Comment by damencho** [comment]
I doubt it will work. Jicofo and videobridge and prosody will need a lot of RAM...

**Comment by wcataldo** [comment]
I got 2 gigs on the Omnia.
https://omnia.turris.cz/en/

Already running Prosody in the container, I guess I will try and build it with Maven. I have no experience with Maven though. Easy enough to try.
