### ISSUE TITLE
Jitsi meet in local network 

### ISSUE THREAD

**Issue by heyapple1** [jitsi/jitsi-meet#2415]
Hello!

1)Should there be any difficulties to set up a jitsi meet for usage only in local network (no domains, only internal ip  addresses)?
2) Is it possible to use jitsi-meet in environment without internet connection?

**Comment by damencho** [comment]
Yep it should work. Install and enter the ip address of the machine as hostname, then access the deployment using https://ip-address.
Make sure in your config.js under /etc/jitsi/meet you set disableThirdPartyRequests: true
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L264
If you see any problems attach console.log from the browser and from jvb, while opening new issue.

**Comment by phamduythai92mta** [comment]
Hi all!
i have the same question. how to install jitsi meet in a LAN network without internet. 
now i already installed jitsi on a server with internet with an IP address (i have no domain). now i want put this server into another LAN network without internet. 
How i can do that? and what i have to change to make it work with the LAN network without internet!
Thanks in advance!

**Comment by lishuai199502** [comment]
Hi guys~
Is there a step by step guide to install Jitsi meet offline,I'm too green to do this myself.
Thank you very very much.

**Comment by Memphizzz** [comment]
Is there a guide to install jitsi on a local network by now?
