### ISSUE TITLE
why this?

### ISSUE THREAD

**Issue by cirelramos** [jitsi/jitsi-meet#2418]
i run android first time

[first](https://drive.google.com/file/d/1KI4cpt7hMK-Snuo_YkMmBW0ZRt7hJuaR/view?usp=sharingl)

stop and run again

[two](https://drive.google.com/file/d/1HSdqA6iWeTz06sllHKA5f36gQ8aph5yK/view?usp=sharingl)

**Comment by saghul** [comment]
How are you loading the URL?
