### ISSUE TITLE
 Failed to load font

### ISSUE THREAD

**Issue by reimertz** [jitsi/jitsi-meet#2421]
I have spent a couple of hours to get the SDK working properly.

I'm about to give up till further feedback from any of the core developers. It seems the `JitsiMeet.framework` can't resolve all the fonts that is bundled together with the framework.

Any suggestions how this can be solved?

I've tried getting the iOS SDK to load on a clean iOS Project but I get the same issues that others are seeing. (#2377, #2158)

error below

```
2018-01-26 01:45:50.667039+0100 mavencook[1698:885812] Failed to load font: The operation couldn’t be completed. 
(com.apple.CoreText.CTFontManagerErrorDomain error 105 - Could not register the CGFont '<CGFont (0x1c02efd80): FontAwesome>')
```

**Comment by saghul** [comment]
I assume you built the framework yourself. What commit from master did you build and what CocoaPods version did you use?

**Comment by reimertz** [comment]
commit f5f341ca9eabd118bbd5d72bb524ea1e44fd96ed
```
$ pod --version
1.3.1

```

**Comment by saghul** [comment]
CocoaPods 1.4.0 has changed the syntax a bit, and we updated our podfile to it. You must have gotten a warning when running pod install. 1.4.0 already made it into homebrew, can you please update and try again?

**Comment by reimertz** [comment]
Think I got it to work now. Thanks!
