### ISSUE TITLE
Jitsi-meet subdomain or subdirectory

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#2422]
Hi,

I was able to have a successful jitsi-meet install on a test server I have on Digital Ocean. I have it all working like a brand new Ferrrari. Its perfect.

However now I would like to have it where I intend to use it and before I start setting that up on a new domain, server and doing a fresh install, I have the following situation:

My intended machine is Linux Ubuntu 16.04 /Apache and ideally I would like to have jisti run in a subdirectory eg, www.mydomain.com/meet but I haven't seen anyone using it like that so I'm wondering if its possible to install it in the "meet" directory (re my example). What would I need to change keeping in my my specs?

Or is it that a subdomain pointing to the server jitsi is running on that would be better?

**Comment by dasboeh** [comment]
Nobody got an answer? This would be my question, too. :-)

**Comment by StreamTitan** [comment]
Actually this would be the perfect way to install Jitsi-Meet as you can set the main directory as the site which explains the service etc (a how-to for example) 

I wasn't able to figure this out either. It may come down to the conf files, telling Jitsi where to look for the app in order to get that working with a sub directory

**Comment by turint** [comment]
Look for the "getroomnode" option in the config.js:
// Custom function which given the URL path should return a room name.
// getroomnode: function (path) { return 'someprefixpossiblybasedonpath'; },

Change it to something like:
getroomnode: function (path) { return location.pathname.replace('/subfolder/',''); },
It gets the current web path and returns just the room name, without the subfolder part.

Change the "bosh" variable to include the subfolder, "//jitsi-meet.example.com/subfolder/http-bind".

Then, of course, re-configure your webserver to serve Meet for the subfolder instead of web root.

**Comment by StreamTitan** [comment]
This looks good. Thanks

**Comment by mckaygerhard** [comment]
any how to for do this in subpath? i changed the configuration files but http webserver redirection are gone!

**Comment by kllp** [comment]
> Then, of course, re-configure your webserver to serve Meet for the subfolder instead of web root.
@turint I tried these (untested) nginx config changes https://github.com/jitsi/jitsi-meet/issues/381#issuecomment-150679902 but failed

In addition I can't find "location /xmpp-websocket" in my config. 
It would be very nice if you can provide a working subdirectory example for nginx.

**Comment by kllp** [comment]
> Just configure your webserver to server the content off a subdirectory 
Great news, but this ain't easy.

**Comment by mckaygerhard** [comment]
yeah! seems configuring that are more complicated now! all are very confused! could provide exact documentation for do that or minimal steps!?

**Comment by saghul** [comment]
I really don't understand where the trouble is. The subdirectory setup? I recommend you use a subdomain, not because there are problems but because there is nothing to configure, since our setup does it automatically.

**Comment by kllp** [comment]
Yes subdomains are easier to setup but I'd like to use a subdirectory. There are plenty of resources for nginx online but that doesn't help much. I *just* want nginx to serve the webroot at a subdirectory like 'example.com/jitsi'. Nginx should not touch 'example.com'.

**Comment by mckaygerhard** [comment]
yeah me too, i cannot use subdomains!

**Comment by turint** [comment]
You can just use "location" to configure all the web paths to point to the subfolder, for example something like this:

    root /usr/share/jitsi-meet;
    index index.html index.htm;
    location /subfolder {
        ssi on;
		location /subfolder/config.js {
			alias /etc/jitsi/meet/jitsi-meet.example.com-config.js;
		}
		location ~ ^/subfolder/([a-zA-Z0-9=\?]+)$ {
			rewrite ^/subfolder/(.*)$ /subfolder/ break;
		}
		location /subfolder/http-bind {
			proxy_pass      http://localhost:5280/http-bind;
			proxy_set_header X-Forwarded-For $remote_addr;
			proxy_set_header Host $http_host;
		}
	}

YMMV, so please check the Nginx documentation too.

**Comment by mckaygerhard** [comment]
umm that looks like a "workaround" ony, there's no jitsi-meet related configuration for? we need someting more close to!

**Comment by saghul** [comment]
@mckaygerhard I think you are going to need to be more specific. That's **NOT** a workaround. You need to update config.js so URLs have the subdirectory there.

**Comment by saghul** [comment]
Now that @turint provided an example here: https://github.com/jitsi/jitsi-meet/issues/2422#issuecomment-444499707 I'm closing this. Please reopen (with details) if the problem persists.

**Comment by kllp** [comment]
@turint Thank you very much for this example. 

I understand that you prefer the subdomain setup but I hope we can build a working example together.

You can find my config.js here: http://dpaste.com/2NTV9V6
And my (nginx) meet.conf, which uses the default docker-jitsi paths here: http://dpaste.com/1NX5R2J

> "/usr/share/jitsi-meet/subfolder/index.html" is not found (2: No such file or directory)

Symlinking "/usr/share/jitsi-meet/subfolder" to "/usr/share/jitsi-meet" does help for index.html, but the screen stays grey.

**Comment by mckaygerhard** [comment]
seems more resources of jitsi-meet are taken from assumed hijacked webserver root path!

**Comment by mckaygerhard** [comment]
seems more resources of jitsi-meet are taken from assumed hijacked webserver root path!

please @kllp can yo enable with F12 the console debug a see if all the request are correct or there 's some 404 not found?

**Comment by saghul** [comment]
@kllp If you are using the Docker setup you are looking at the problem all wrong. Please post in the community: https://community.jitsi.org/ and I'll help ypu out.

**Comment by mckaygerhard** [comment]
thanks @saghul for your support, please post here @kllp the linked post to property see the responses!

**Comment by ddoussot** [comment]
I managed to make it work following those guidelines and also :
/usr/share/jitsi-meet/base.html
<base href="/<your_subdirectory>/" />

**Comment by Berti85** [comment]
> /usr/share/jitsi-meet/base.html

Ddoussot, could you share with me the details of the setting in addition to the path you mentioned?
Which files do I need to modify to make Jitsi Meet work from a specified subdirectory, and what are those changes?

**Comment by kyronjoves** [comment]
Is it still not possible to have jitsi on a subfolder path? Like FQDN/meet? @saghul
