### ISSUE TITLE
Screen Sharing stopped working in Firefox (meet.jit.si)

### ISSUE THREAD

**Issue by yurkobb** [jitsi/jitsi-meet#2424]
I've used screen sharing in FF just yesterday, but today it stopped working. No FF or OS updates occurred to my knowledge. When I click the screen sharing button, I get an error saying the extension failed to install. However, previously it was working in FF without any extensions. Here's the [full JS console log](https://framabin.org/?c2a07ebfaef3c083#YTqxz/x3x+yR6Ae3N4eUs1oQtxRxDr0dmHwiPHoVBVk=). The XML parsing error caught my attention in particular.

As a side note, in Chromium it asks to install the extension - doesn't Chrome(ium) support screen sharing natively yet?

----
Firefox version: 57.0.4 (64-bit)
OS: Fedora 27

**Comment by saghul** [comment]
@yurkobb Thanks for the report! I can confirm that the issue occurs to me too, running Firefox Nightly (60 at the moment). Looks like our last deploy botched it, sorry about that.

> As a side note, in Chromium it asks to install the extension - doesn't Chrome(ium) support screen sharing natively yet?

The extension is only needed for whitelisting the domain doing it, not to implement the feature itself, that is supported natively. But yeah, it's still needed in Chrome.

**Comment by bgrozev** [comment]
Thanks for the report! @virtuacoplenny  @hristoterezov  and @aaronkvanmeerten  worked on hot-fixing this in meet.jit.si. A solution for the underlying problem is also being worked on

**Comment by yurkobb** [comment]
Thank you for reacting so quickly. I'll be doing a couple of webinars soon, it's great to be able to do it using free & open technology.
