### ISSUE TITLE
Not working on Chromium 63?

### ISSUE THREAD

**Issue by faelsoto** [jitsi/jitsi-meet#2428]
First of all, thanks for such a great product! We use jitsi meet a lot and we're loving it.

Recently I have installed Ubuntu 17.10, as well as Firefox and Chromium. I like jitsi better in Chromium since I can share full screen. In the previous installation (I was on Ubuntu 15.10, and Chromium was stuck, outdated at ~53), it was working just fine.

However, on Chromium 63 I'm getting this message:

![image](https://user-images.githubusercontent.com/1304449/35464324-e2bc407e-02ba-11e8-8498-7cc3ecdf4a45.png)

Console shows the following errors:

```
[react/features/base/connection/actions.web.js] <>:  TypeError: Cannot read property 'isPluginInstalled' of undefined
Uncaught (in promise) TypeError: H.webRTCReady is not a function
```

(Also the [fully supported browsers](https://cdn.jitsi.net/static/recommendedBrowsers.html) link is not working)

**Comment by CodeMouse92** [comment]
I can dodge this by faking the user agent string, but this is highly annoying, and VERY badly timed! I've got an important meeting on Jitsi with a lot of people this evening.

**Comment by bgrozev** [comment]
There is already a PR open for this specific problem, and we're working to improve the testing process before releasing to meet.jit.si.

**Comment by saghul** [comment]
Was this already released @bgrozev ?

**Comment by bgrozev** [comment]
Yes, meet.jit.si is now running jitsi-meet 2569 which includes [the fix]https://github.com/jitsi/lib-jitsi-meet/pull/698)

**Comment by CodeMouse92** [comment]
Thanks, all y'all! Fix confirmed on my end.
