### ISSUE TITLE
Update button in settings menu does not work

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#243]
When "Update" button is pressed in the Settings menu the application crashes at:
xmpp.addToPresence - Unknown tag for presence.

**Comment by gpolitis** [comment]
@paweldomas you mean when you update Chrome?

**Comment by paweldomas** [comment]
No, I mean this one in Jitsi-meet "settings" view opened from top toolbar. You can edit your display name there, but when you press "Update" button it is not updated. Other participants do not see the change, because presence is not sent correctly.

**Comment by paweldomas** [comment]
Seems to be working now.
