### ISSUE TITLE
Hang up can not quit

### ISSUE THREAD

**Issue by xioamins** [jitsi/jitsi-meet#2438]
When I hang up, it will always be in a black screen, can not carry out other operations, where is the problem

**Comment by saghul** [comment]
Based on your comment on https://github.com/jitsi/jitsi-meet/issues/2195 I guess you mean this happens on Android? Does it crash or is it just showing a black screen? Are you using the Jitsi Meet app or is it your own app using the SDK?

We need more details in order to be able to help you.

**Comment by ArtiMane** [comment]
Hi sir, I am also getting same issue as after hang up the jitsi call It shows me blank screen and user unable to go back on previous screen

**Comment by afueo** [comment]
I have same issue which I use the SDK and give me just black screen after i click call finish but not app crached.

**Comment by saghul** [comment]
Are you finishing your Activity on the conference ended / failed event?

**Comment by afueo** [comment]
i just start the call and then clicked close the call by the default sdk,
I use the SDK in Cordova plugin
Should I close the activity in below code and how?
https://github.com/afueo/cordova-plugin-jitsi-meet/blob/master/src/android/JitsiPlugin.java

**Comment by saghul** [comment]
When you get the "conference left" or "conference failed" it's time to hide that view. I don't know how to do this in the Cordova plugin, since I (nor anyone on the Jitsi team) wrote it.

**Comment by FWDimitrios** [comment]
I am having the same issue on Android. 

**Setup:** `implementation ("org.jitsi.react:jitsi-meet-sdk:1.21.0") { transitive = true }`

**Code:**
```
class CallActivity : JitsiMeetActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)     
        loadURL("https://myUrlLoadsJustFine.com")
    }

}
```
My activity just hangs in a black screen after terminating a call. It doesn't finish. Also, the `JitsiMeetActivity` doesn't expose any callbacks or listeners to manually `finish()` the activity when the conference ends.

 In the [sample activity](https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/java/org/jitsi/meet/MainActivity.java) provided, there seems to be loads of methods to override but I have access to none of them.

**Comment by saghul** [comment]
master containes an updated SDK which will become version 2.0 really soon. I'd suggest you build the SDK by hand as the docs describe since the API has changed. The Activity now finishes by itself when a conference ends, for example.
