### ISSUE TITLE
Can I customize the video chat interface?

### ISSUE THREAD

**Issue by lizi0588** [jitsi/jitsi-meet#2442]
When using Android SDK, I would like to customize the video chat interface, such as adding buttons. What should I do?

**Comment by saghul** [comment]
The Android SDK is implemented internally as a React Native application. You will need to make changes to it and then rebuild it. Here are some pointers:

https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/Toolbox.native.js
https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build

Cheers!

**Comment by lizi0588** [comment]
I want to use only Android code to make calls instead of using react native. I want to use the native layout of Android, so that it will be better to maintain the project. Can this be achieved? Do you have the SDK developed using Android?

**Comment by saghul** [comment]
No, the SDK is developed using React Native and that's what you have to modify if you want to make any layout changes.

**Comment by lizi0588** [comment]
Hello, I'm sorry, there's another problem. Android uses webrtc's SDK, the server side uses your jitsi server. Is there any information about calling API? This is because we require the use of native code.
