### ISSUE TITLE
video stream appears after a long delay

### ISSUE THREAD

**Issue by roeycohen** [jitsi/jitsi-meet#2448]
for some reason, some times when i turn the camera off and on, the video reappears on the other side only after a minute or so.
![screenshot_2](https://user-images.githubusercontent.com/2613845/35694780-12958e66-078b-11e8-98a3-d1d458603aa7.png)
the webrtc internals screenshot above shows that the data actually arrived at about 6:54, but the first frame is decoded only at 6:55.
another weird thing is that once the video appears, i get 30fps but then it drops to 10fps which is the typical fps for me.

- 150kb is the usual bit-rate i get from the server when the delay doesn't occur.
- this problem doesn't occur on meet.jit.si
- i've installed jitsi on top of an aws instance using the quick install guide (v1.0.2635-1).
- no one else is using my instance.
- both clients are chrome 64 on top of the same windows 10 machine.

what am i missing?

**Comment by bbaldino** [comment]
PLIs start right away, so it looks like they're probably not getting received properly by the far side.  I'd start by looking at those and seeing if they're getting forwarded/received by the sender correctly.

**Comment by roeycohen** [comment]
@bbaldino not sure what you need me to do...

**Comment by damencho** [comment]
v1.0.2635 is the current stable. The version currently running on meet.jit.si is pretty new and will be pushed to stable, probably early next week.

**Comment by roeycohen** [comment]
@damencho the question is will it fix the problem?... maybe i was doing something wrong? are you familiar with this problem?

**Comment by damencho** [comment]
As you are saying that you don't see the problem on meet.jit.si, I suppose it will be fixed with the update...

**Comment by roeycohen** [comment]
ok, i'll wait for early next week :)

**Comment by TheReal1604** [comment]
@roeycohen did the stable update fix your issues?
