### ISSUE TITLE
My meeting room share link missing one column option to dian in, use one of the flollowing numbers and meeting id

### ISSUE THREAD

**Issue by xiaoqge** [jitsi/jitsi-meet#2449]
My meeting room share link missing one column option to dian in, use one of the flollowing numbers and meeting id ？ Please help me, thank you

**Comment by xiaoqge** [comment]
Who knows how to solve this problem? Thanks

**Comment by damencho** [comment]
You need to configure [jigasi](https://github.com/jitsi/jigasi) for your deployment with a sip provider of your choice that will provide you the numbers you can use. 
Then you can configure in your config.js dialInNumbersUrl that will return a json with those numbers, and dialInConfCodeUrl which is the conference mapper (not sure at the moment whether you can reuse the one used for meet.jit.si).

**Comment by xiaoqge** [comment]
Thank you very much for your answer, is there any configuration reference example?

**Comment by damencho** [comment]
Nope. Sorry. You can ask, when you have some questions or problems doing that.

**Comment by xiaoqge** [comment]
Thanks a lot, I'll try

**Comment by xiaoqge** [comment]
PhoneNumberList and conferenceMapper I wrote these two documents, and then configure URl it? Is not jigasi written? I configured config.js two wrote their own document Jin, but no effect, if the copy configuration meet.jit.si no problem

`root@v:/etc/jitsi/meet# more conferenceMapper.js 
{"message":"No conference or id provided","conference":false,"id":false}
root@v:/etc/jitsi/meet# more phoneNumberList.js 
{"message":"Phone numbers available.","numbers":{"Australia":["+61.8.7150.1136"],"Brazil":["+55.21.3500.0112"],"France":["+33.1.84.88.6478"],"Germany":["+49.89.38
0.38719"],"Japan":["+81.3.4510.2372"],"Spain":["+34.932.205.409"],"UK":["+44.121.468.3154"],"US":["+1.512.402.2718"]},"numbersEnabled":true}`

`server {
    listen 443 ssl;
    server_name xxx.com;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM
:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";

    add_header Strict-Transport-Security "max-age=31536000";

    ssl_certificate /etc/jitsi/meet/xxx.com.crt;
    ssl_certificate_key /etc/jitsi/meet/xxx.com.key.unsecure;

    root /usr/share/jitsi-meet;
    index index.html index.htm;
    error_page 404 /static/404.html;

    location /config.js {
        alias /etc/jitsi/meet/xxx.com-config.js;
    }

    location /phoneNumberList {
        alias /etc/jitsi/meet/phoneNumberList;
    }
    location /conferenceMapper {
        alias /etc/jitsi/meet/conferenceMapper;
    }

    location ~ ^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }

    location / {
        ssi on;
    }

    # Backward compatibility
    location ~ /external_api.* {
        root /usr/share/jitsi-meet/libs;
    }

    # BOSH
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }
}`

**Comment by xiaoqge** [comment]
https://github.com/jitsi/jigasi/issues/81 
It seems that you need to implement IVR yourself

**Comment by VectorformIT** [comment]
This is how I got it working in detail.
This is assuming you're going to use a FreePBX Asterisk server and Active Directory for LDAP
https://evilcreamsicle.com/index.php/2018/03/28/jitsi-meet-w-call-in-and-active-directory/
