### ISSUE TITLE
Which dependencies is needed while using the Mobile SDK

### ISSUE THREAD

**Issue by TangXT** [jitsi/jitsi-meet#2454]
Which dependencies is needed to use the SDK? Is it possible to provide only android/sdk and ios/sdk without the to deploy jitsi-meet on native development machines?

**Comment by saghul** [comment]
Are you asking for SDK binaries so you don't have to build it yourself? If so, we do have them for Android, see: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#install, but alas not yet for iOS.

**Comment by TangXT** [comment]
@saghul I want to build the SDK myself and provided it to other developers to write app without deploy jitsi-meet on their development machines.
By the way, It seems that for iOS only need to build the JitsiMeet.framework and provided the JitsiMeet.framework and WebRTC.framework(which in the path:/node_modules/react-native-webrtc/ios/) to other developers to add the two .framework files  into their project. Am I right??

**Comment by saghul** [comment]
> I want to build the SDK myself and provided it to other developers to write app without deploy jitsi-meet on their development machines.

I see. Then all you have to do is provide them with the SDK, which uses meet.jit.si as the deployment by default, so they don't need to have the server installed themselves.

> By the way, It seems that for iOS only need to build the JitsiMeet.framework and provided the JitsiMeet.framework and WebRTC.framework(which in the path:/node_modules/react-native-webrtc/ios/) to other developers to add the two .framework files into their project. Am I right??

Correct.

**Comment by TangXT** [comment]
@saghul I had done some modify with the mobile project. It means that I only need to provided the JitsiMeet.framework and WebRTC.framework(which in the path:/node_modules/react-native-webrtc/ios/) to other developers to add the two .framework files into their project without jitsi-meet. Am I right?
But in android project need to  provided above to other developers :
sdk
react-native-background-timer
react-native-fetch-blob
react-native-immersive
react-native-keep-awake
react-native-locale-detector
react-native-vector-icons
react-native-webrtc
by doing above:
cd android/
./gradlew :sdk:assembleRelease
./gradlew :sdk:publish
./gradlew :react-native-background-timer:publish
./gradlew :react-native-fetch-blob:publish
./gradlew :react-native-immersive:publish
            .......................
./gradlew :react-native-webrtc:publish
So that other developers (both iOS and Android) don't need to deploy jitsi-meet on their development machines. Is that right?

**Comment by saghul** [comment]
Yes, that's correct!

**Comment by deva-gopalani** [comment]
Hey @saghul ! I am not sure where to ask this hence i am posting my query under this issue. I have made a custom android SDK for jitsi-meet. Now in one of my projects the apk which is being generated does not consist of the lib folder whereas in another project the lib folder is being generated which is actually taking up a lot of space. I wanted to know how could i remove the native binaries which are being added in the lib folder of the apk. 

Note: In both the APK's jitsi is working fine, it's just that when the lib folder is getting included in the apk, it is taking up about 40MB of memory and i would like to remove that!

**Comment by saghul** [comment]
That is the expected size, since it includes 4 architectures. You could remove some ABIs if you want to, but you cannot remove the native libraries or the app won't work.

**Comment by deva-gopalani** [comment]
> That is the expected size, since it includes 4 architectures. You could remove some ABIs if you want to, but you cannot remove the native libraries or the app won't work.

Okay got it. Thanks @saghul !
