### ISSUE TITLE
we only see "welcome to nginx"

### ISSUE THREAD

**Issue by tansaku** [jitsi/jitsi-meet#2458]
![](https://dl.dropbox.com/s/9jmltwvhyu9278r/Screenshot%202018-02-06%2014.05.53.png?dl=0)

we only see "welcome to nginx" when we go to the box URL - we completed the quick install - letsencrypt certs all set up - is there something else we need to do?

**Comment by saghul** [comment]
Did you already have nginx installed before you did the quick install, or did you install it afterwards?

**Comment by tansaku** [comment]
@saghul I don't think we had it installed - we started with a clean box - I'm working on this with my colleague @sigumagwa and he thinks he might have installed nginx after in an attempt to get things working, but we are not sure

**Comment by saghul** [comment]
Just to make sure, uninstall all jitsi things, install nginx first and then jitsi meet afterwards. This way the install process will place the appropriate nginx config files automagically.

**Comment by tansaku** [comment]
thanks @saghul - does that mean that the quick install docs should recommend an initial install of nginx?

@sigu - sounds like we have a next step ...

**Comment by tansaku** [comment]
@saghul we have certainly done at least two complete purges and re-installs since nginx was last installed.   Is there something else we can do to debug?  what is supposed to happen when we go to the URL mentioned?

**Comment by saghul** [comment]
If you specified that domain when installing Jitsi Meet, you should see something akin to meet.jit.si. What files do you have in /etc/nginx/sites-available/ ?

**Comment by sigu** [comment]
we have two files @saghul  :

- `<ip>.conf` 
- `default`

where `<ip>` is the ip address of our box, (not sure how safe it is to share that 😛 )

**Comment by saghul** [comment]
That's the problem right there. During the installation you were asked for the hostname, and you added the IP and not the hostname, right? The easiest is to reinstall all packages and when prompted add "jitsi.agileventures.org" as the hostname. Otherwise nginx won't know how to match the incoming traffic.

**Comment by sigu** [comment]
Thanks, we tried reinstalling it never prompted for the hostname 😄

**Comment by tansaku** [comment]
perhaps we could manually rename <ip>.conf (and contents of file) and/or delete that conf? @sigu @saghul

**Comment by damencho** [comment]
Probably you just did apt-get remove ... which just removes packages and keeps its configurations. You need purge all packages:
apt-get --purge remove jitsi-meet jitsi-meet-web jitsi-meet-prosody jitsi-meet-web-config jicofo jitsi-videobridge

**Comment by tansaku** [comment]
@damencho yes, that's what we did - we purged and reinstalled twice, but it still didn't ask us for the hostname - is there some way to force it to ask us for the hostname, or explicitly set it?

**Comment by damencho** [comment]
You used this command that purges all the related packages? https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#uninstall

**Comment by sigu** [comment]
Managed to set it up on the Azure box, thank you :tada: :tada:

**Comment by DarkTrick** [comment]
Purge and Reinstall can't be the answer here, right? There must be a (simple) way of reconfiguring it. I mean,  this is just 1 string during the setup process. It's not possible to simple change it?

**Comment by DerfOh** [comment]
Having a similar issue on the docker-compose build, 2 different docker hosts just show the nginx welcome page instead of the app.

**Comment by AbuShawarib** [comment]
FWIW, I resolved this by deleting the default website and reloading.
