### ISSUE TITLE
The local view is mirrored when screen sharing

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#246]
When you share your screen the local video shown is mirrored. I am not sure if it happens every time, observed with a single window share.

**Comment by ibeardslee** [comment]
There is a pull request for this waiting to be merged .. https://github.com/jitsi/jitsi-meet/pull/233

**Comment by bgrozev** [comment]
@ibeardslee thanks!

**Comment by hristoterezov** [comment]
Fixed with db2296953ddfbc4a5ae5f144d11655eb4ebb8579
