### ISSUE TITLE
[Android] Jitsi Meet SDK for Android Problem

### ISSUE THREAD

**Issue by samk17cmutpm** [jitsi/jitsi-meet#2464]
Hi, 
I followed the link below to publish file aar 
https://github.com/jitsi/jitsi-meet/tree/master/android

When I published successfully the arr file
![maven_publish](https://user-images.githubusercontent.com/7029528/35960111-05e49c2a-0cdb-11e8-9262-5931b7464e24.png)
Then I added into my project by adding new module with arr file 
![errro2](https://user-images.githubusercontent.com/7029528/35960147-280695ce-0cdb-11e8-82cb-9e9206a7a0d6.png)
Finally I run the project but I faced the error like this below 
![errorr](https://user-images.githubusercontent.com/7029528/35960174-3f693a78-0cdb-11e8-8d03-fe796f29aae8.png)
Did I do something wrong ? Please help me !!

**Comment by saghul** [comment]
Did you also publish all other dependencies to your own local maven repo?

**Comment by samk17cmutpm** [comment]
@saghul Yes I published all local maven before I published jismit sdk 
![localmaven](https://user-images.githubusercontent.com/7029528/35962202-23fa0a94-0ce3-11e8-9868-ac78a2143a71.png)

**Comment by saghul** [comment]
Hum, how about the proguard rules file?

**Comment by samk17cmutpm** [comment]
Yes I Tried, but the same error !!!
![proguard-rules](https://user-images.githubusercontent.com/7029528/35964867-968daa54-0ceb-11e8-9912-dc4f60f2fc9b.png)

**Comment by sesangsokuro** [comment]
how to make jitsi-meet-sdk-{version}.arr ?

**Comment by saghul** [comment]
The new SDK (1.21) is up and the build process was overhauled in the meantime, so I'm closing this.

@sesangsokuro `cd android; ./gradlew assembleRelease`.
