### ISSUE TITLE
Integrate jitsi meet in to native iOS code....! Help needed...!!!!!

### ISSUE THREAD

**Issue by smbteam1** [jitsi/jitsi-meet#2471]
I have a development ongoing native iOS project and I would like to integrate jitsi meet in to it, with out using any react native dependency files. I need a pure native iOS project after the implementation.
Is it possible?

**Comment by saghul** [comment]
This is already the case. When you build the SDK the result is a pure iOS framework you can embed in your app. It still uses React Native internally, but that's an internal implementation detail.
