### ISSUE TITLE
[React native] How to turn off audio from all participants

### ISSUE THREAD

**Issue by hvlong** [jitsi/jitsi-meet#2473]
I spend on a lot time to investigate source code about turn off audio from all participants, but I can't found it. Please share me this class or source code.
Appreciate anyone help me.

Thank you.

**Comment by saghul** [comment]
There is no nuch feature implemented. You can only mute them one by one. What you can do though, is configure the room so everyone starts muted. 

![screenshot_20180210_114057](https://user-images.githubusercontent.com/317464/36061204-55e506ba-0e57-11e8-98fa-866ca8271192.png)

**Comment by hvlong** [comment]
Please share me source code.

**Comment by hvlong** [comment]
When will you impement feature disable audio of all participants in only local?
I need this feature to next release project. 
Thanks

**Comment by damencho** [comment]
There is no such feature planned on the roadmap. 
But any contributions are welcome.

**Comment by hvlong** [comment]
@damencho I got it, thank you!

**Comment by damencho** [comment]
@ajaydata 
You can use:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L84
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L119

Or:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L88
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L123

**Comment by ajaydata** [comment]
Thanks. 

We are using thay. But in this case user can enable his audio or video.. which we want to restrict..

Thanks.

On April 4, 2018 9:33:44 AM GMT+05:30, "Дамян Минков" <notifications@github.com> Wrote:
>@ajaydata 
>You can use:
>https://github.com/jitsi/jitsi-meet/blob/master/config.js#L84
>https://github.com/jitsi/jitsi-meet/blob/master/config.js#L119
>
>Or:
>https://github.com/jitsi/jitsi-meet/blob/master/config.js#L88
>https://github.com/jitsi/jitsi-meet/blob/master/config.js#L123
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jitsi/jitsi-meet/issues/2473#issuecomment-378473656

राजमेल - राजस्थान सरकार की फ्री ईमेल सेवा

**Comment by saghul** [comment]
That is not possible at present time, nor it's in our roadmap.
