### ISSUE TITLE
 iOS SDK -Getting NSInvalidArgumentException Error and App going to Crash

### ISSUE THREAD

**Issue by ParvendraSingh** [jitsi/jitsi-meet#2475]
Dear Team,

Will you please check my step. and suggest me
I am following these all steps to use JitsiMeet in my own application.

First i am doing this in your repository clone (To get JitsiMeet.framework and WebRTC.framework)

1- I installed React dependency in my project with following commands.
a- brew install node
b- brew install watchman
c- npm install -g react-native-cli

Then

2- npm install -g ios-deploy --unsafe-perm=true (As my OS Version is greater then 10.11)
3- npm install
4- brew install cocoapods
5- pod install

After this when i run your code it is working fine..

Then i just create my own project and doing these steps

1- Copy JitsiMeet.framework from the location "ios/sdk/JitsiMeet.framework"
2- Copy WebRTC.framework from the location "node_modules/react-native-webrtc/ios/WebRTC.framework"
3- Added a JitsiMeetView to my app using a Storyboard .
4- Adding this slice of code in my project under ViewDidLoad Function

JitsiMeetView *jitsiMeetView = (JitsiMeetView *) self.view;
jitsiMeetView.delegate = self;
[jitsiMeetView loadURLObject:@{
@"config": @{
@"startWithAudioMuted": @no,
@"startWithVideoMuted": @no
},
@"url": @"https://meet.jit.si/parvendra9090"
}];

5- Run the app in my iPhone
6- Getting this responce

2018-02-10 18:16:35.766254+0530 JitsiMeetDemo[3752:1881792] Running application App ({
initialProps = {
url = {
config = {
startWithAudioMuted = 0;
startWithVideoMuted = 0;
};
url = "https://meet.jit.si/parvendra9090";
};
welcomePageEnabled = 0;
};
rootTag = 1;
})

NSInvalidArgumentException

2018-02-10 18:16:38.430230+0530 JitsiMeetDemo[3752:1881792] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x18515b164 0x1843a4528 0x1850f3c9c 0x18502bfd0 0x18502be4c 0x1059b4024 0x105a5beac 0x105b051a0 0x105a5bc20 0x1059d0388 0x1069512cc 0x10695128c 0x106955c20 0x185103344 0x185100f20 0x185020c58 0x186eccf84 0x18e7795c4 0x10459b3d4 0x184b4056c)
libc++abi.dylib: terminating with uncaught exception of type NSException

And My app going to crash
Please suggest me the best solution

**Comment by saghul** [comment]
Can you please upload this demo app to github somewhere? I have one of my own and haven't run into this.

**Comment by ParvendraSingh** [comment]
@saghul 
I have uploaded my sample code on my Public git repository [https://github.com/ParvendraSingh/JitsiMeetDemo](url)
Please find the sample code and have a look.
It is going to crash with same reason and error.

**Comment by ParvendraSingh** [comment]
@saghul 
I solved this issue 
now my app is working fine.
you no need to check my code.
Thanks

**Comment by NipunBilala** [comment]
@ParvendraSingh Hello i am facing the same issue, you faced. can you pls tell me hw did u manage to solve it.

**Comment by TTTTTTTK** [comment]
my app going to crash too.
Can you produce a app demo @ParvendraSingh  , i want to sovle the problem by taking it as a reference
