### ISSUE TITLE
Error printed when sharing the screen

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#248]
When screen is shared this error is printed in other participants console:

modified setLocalDescription failed Failed to set local answer sdp: Called in wrong state: STATE_SENTACCEPT(or some other state name)

Most of the time seems it seems to work in spite of that error. Do we wait for stable state when doing addsource/removesource ?

**Comment by dwilson6** [comment]
I've seen this as well.  Usually when turning screen sharing off and it fails to switch back to the video feed.

**Comment by paweldomas** [comment]
Fixed by 29f0682
