### ISSUE TITLE
Black screen after configuring Jicofo Secure Domain

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#2482]
Hi,
I installated the latest version of Jitsi-Meet with quick-install on a public server over internet (Debian 8).
The fqdn is meet.mydomain.com (mydomain is in place of the actual name of the domain).
The system is working fine with anonymous authentication.

I tried to setup "Jicofo Secure Domain", as indicated in https://github.com/jitsi/jicofo

in Prosody, I added a new virtual host
VirtualHost guest.meet.mydomain.com
    authentication = "anonymous"
and modified the authentication of the main domain:
VirtualHost "meet.mydomain.com"
    -- authentication = "anonymous"
   authentication = "internal_plain"

in Meet I enabled anonymousdomain
var config = {
    hosts: {
            domain: 'meet.mydomain.com',
            anonymousdomain: 'guest.meet.mydomain.com',
            ...
        },
        ...
}

and finally I added the row
org.jitsi.jicofo.auth.URL=XMPP:meet.mydomain.com
in /etc/jitsi/jicofo/sip-communicator.properties 

When  I open the url https://meet.mydomain.com with Chrome, I get a black screen.
No errors in  prosody.log , jvb.log , jicofo.log.
If I comment anonymousdomain in Prosody, the conference works, after putting user and password.
Every time I modified the configuration files I restarted the system.
I tried a fully update of the system with apt-get upgrade, but nothing changed.
Stefano

**Comment by damencho** [comment]
Which version of prosody are you running?

**Comment by calamatitech** [comment]
This is output of "prosodyctl about":

Prosody 0.9.7

# Prosody directories
Data directory:         /var/lib/prosody
Plugin directory:       /usr/lib/prosody/modules/
Config directory:       /etc/prosody
Source directory:       /usr/lib/prosody

# Lua environment
Lua version:                    Lua 5.1

Lua module search paths:
  /usr/lib/prosody/?.lua
  /usr/local/share/lua/5.1/?.lua
  /usr/local/share/lua/5.1/?/init.lua
  /usr/local/lib/lua/5.1/?.lua
  /usr/local/lib/lua/5.1/?/init.lua
  /usr/share/lua/5.1/?.lua
  /usr/share/lua/5.1/?/init.lua

Lua C module search paths:
  /usr/lib/prosody/?.so
  /usr/local/lib/lua/5.1/?.so
  /usr/lib/x86_64-linux-gnu/lua/5.1/?.so
  /usr/lib/lua/5.1/?.so
  /usr/local/lib/lua/5.1/loadall.so

LuaRocks:               Not installed

# Lua module versions
lfs:            LuaFileSystem 1.6.2
lxp:            LuaExpat 1.3.0
pposix:         0.3.6
socket:         LuaSocket 3.0-rc1
ssl:            0.5.PR

**Comment by calamatitech** [comment]
I forgot to say that I executed the following commands after the quick install to get a working jitsi meet server (without authentication, that is authentication = "anonymous"), after the script /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

cd /etc/prosody/certs/
mv localhost.cert localhost.crt

keytool -import -noprompt -trustcacerts -alias auth.meet.mydomain.com -file /etc/prosody/certs/auth.meet.mydomain.crt -keystore /etc/ssl/certs/java/cacerts -storepass changeit

**Comment by calamatitech** [comment]
I’m running prosody 0.9.7.
I made two new comments on issue 2482

**Comment by calamatitech** [comment]
I tried the lastest unstable version, but nothing changed.
I started Chrome with --enable-logging and I got this chrome_debug.log:

[11200:11784:0216/173906.689:WARNING:PushPullFIFO.cpp(182)] PushPullFIFO: underflow while pulling (underflowCount=1, availableFrames=0, requestedFrames=480, fifoLength=8192)
[11852:2136:0216/173915.098:INFO:CONSOLE(7)] "SW registered", source: https://www.google.it/_/chrome/newtab?ie=UTF-8 (7)
[11852:2136:0216/173936.021:INFO:CONSOLE(12)] "(TIME) index.html loaded:	", source: https://meet.mydomain.com/ (12)
[11852:2136:0216/173936.022:INFO:CONSOLE(157)] "Uncaught SyntaxError: Unexpected identifier", source: https://meet.mydomain.com/ (157)
[11852:2136:0216/173936.347:INFO:CONSOLE(2)] "[modules/browser/BrowserDetection.js]", source: https://meet.mydomain.com/libs/lib-jitsi-meet.min.js?v=2590 (2)
[11852:2136:0216/173936.749:INFO:CONSOLE(2)] "Uncaught ReferenceError: config is not defined", source: https://meet.mydomain.com/libs/app.bundle.min.js?v=2590 (2)
[11852:2136:0216/173936.754:INFO:CONSOLE(2)] "Uncaught ReferenceError: config is not defined", source: https://meet.mydomain.com/libs/app.bundle.min.js?v=2590 (2)

where, as usual, mydomain replaces the actual domain name

**Comment by damencho** [comment]
Well, it seems that meet is not loading at all, this should be fixed. No idea what can be wrong seems config is not loaded.  You should check that. By default config is serverside included, can it be your web server doesn't have access to it or something (not sure what you use in your deployment apache2, nginx or jetty). 
Check why config is not loading.

**Comment by damencho** [comment]
[11852:2136:0216/173936.022:INFO:CONSOLE(157)] "Uncaught SyntaxError: Unexpected identifier", source: https://meet.mydomain.com/ (157)
[11852:2136:0216/173936.749:INFO:CONSOLE(2)] "Uncaught ReferenceError: config is not defined", source: https://meet.mydomain.com/libs/app.bundle.min.js?v=2590 (2)

There is an error in some javascript file, it can be in the config when you are enabling auth, check that.

**Comment by calamatitech** [comment]
Everything looks like right. Tomorrow I will reinitialize my vps, and do a new fresh installation of Jitsi Meet.
On the same machine, before trying Jicofo Secure Domain, I tried Openfire with plugin Meeting.
I removed it, but it could have left some dirty.
Thank you for you assistance.

**Comment by calamatitech** [comment]
Damencho, you are right. It was missing a comma in the config.js .... I inserted a new row,
anonymousdomain: 'guest.meet.mydomain.com' , and I forgot to insert a comma at the end of the previous row.

**Comment by allquixotic** [comment]
This bit me too! Just uncommenting the anonymousdomain breaks the syntax of the file (missing a comma, etc.)  Glad this issue is here...
