### ISSUE TITLE
ios App crashing after adding JitsiMeet.framework and WebRTC.framework

### ISSUE THREAD

**Issue by NipunBilala** [jitsi/jitsi-meet#2484]
i am trying to integrate jitimeet in my app. i did all the steps as mentioned.
But after successful build, the app crashes with the following log.

 Unknown class JitsiMeetView in Interface Builder file.
 -[UIView setDelegate:]: unrecognized selector sent to instance 0x10130a490
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setDelegate:]: unrecognized selector sent to instance 0x10130a490'
*** First throw call stack:
(0x184a1bd38 0x183f30528 0x184a291f8 0x18e1e3cc4 0x184a216e4 0x1849070dc 0x1000f61e4 0x18de2bbfc 0x18de2b7d4 0x18de3239c 0x18de2f608 0x18de9f068 0x18e08e954 0x18e0936e4 0x18e321454 0x18e5f11f0 0x18e3210b8 0x18e321928 0x18ea8a6e8 0x18ea8a58c 0x18e8069c0 0x18e99bfc8 0x18e806870 0x18e5f0850 0x18e091e28 0x18e4956ec 0x1870bd768 0x1870c6070 0x10018945c 0x100195b74 0x1870f1a04 0x1870f16a8 0x1870f1c44 0x1849c4358 0x1849c42d8 0x1849c3b60 0x1849c1738 0x1848e22d8 0x186773f84 0x18de8f880 0x1000f6670 0x18440656c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by zy885137** [comment]
we have same problem,
Please help me to solve this error.

**Comment by saghul** [comment]
Looks like you'll need to set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to YES in your app's build configuration (via Xcode).

**Comment by agusvazquez** [comment]
Hello Saghul, I also have the same issue. Did everything you are saying but It doesn't work.

2018-10-08 18:05:00.806281-0300 Medvice[61483:328184] Unknown class JitsiMeetView in Interface Builder file.
2018-10-08 18:05:00.807622-0300 Medvice[61483:328184] -[UIView setDelegate:]: unrecognized selector sent to instance 0x7ffae7438110


![captura de pantalla 2018-10-08 a la s 18 11 33](https://user-images.githubusercontent.com/1704434/46634038-06517e80-cb26-11e8-8fda-39691b73a5a2.png)
![captura de pantalla 2018-10-08 a la s 18 11 39](https://user-images.githubusercontent.com/1704434/46634039-06517e80-cb26-11e8-85e9-348ee3fb84ba.png)
![captura de pantalla 2018-10-08 a la s 18 12 08](https://user-images.githubusercontent.com/1704434/46634040-06517e80-cb26-11e8-9127-9125190570d1.png)

**Comment by agusvazquez** [comment]
No. Latest version xCode 12

**Comment by saghul** [comment]
There is no Xcode 12. 10 is the latest.

**Comment by agusvazquez** [comment]
Oh yes, you are right, sorry about that.

Yes I'm using xCode 10

**Comment by zjklyl931081** [comment]
I also encountered this problem on xcode10. Setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to YES is useless. How should I solve this problem?

**Comment by zhanghuiDev** [comment]
Can't the problem of integration on Xcode 10 be solved?

**Comment by saghul** [comment]
All Xcode 10 issues are solved AFICT. Please open a new issue if you are running into problems.

**Comment by zhanghuiDev** [comment]
Is there any documentation that tells me how to solve it?

**Comment by sujiewen** [comment]
xcode 10.2.1  the same problem！

**Comment by saghul** [comment]
How are you integrating the project? Are you using CocoaPods?
