### ISSUE TITLE
Chrome 64 breaks jitsi meet external api iframe.

### ISSUE THREAD

**Issue by JoseAntonioIdener** [jitsi/jitsi-meet#2486]
Hi there!

As you have might read, Chromium(Chrome) 64 has deprecated permissions in cross-origin iframes, here's the link 
 for the full information [https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes](url).

We made a quick fix modifying the external_api.js file to include the new required attributes.

We changed this code:
`  var n = "jitsiConferenceFrame" + w;
                        this._frame = document.createElement("iframe"),
                        this._frame.src = this._url,
                        this._frame.name = n,
                        this._frame.id = n,
                        this._setSize(e, t),
                        this._frame.setAttribute("allowFullScreen", "true"),
                        this._frame.style.border = 0,
                        this._frame = this._parentNode.appendChild(this._frame)`

into this one:

`  var n = "jitsiConferenceFrame" + w;
                        this._frame = document.createElement("iframe"),
                        this._frame.src = this._url,
                        this._frame.name = n,
                        this._frame.id = n,
                        this._setSize(e, t),
                        this._frame.setAttribute("allowFullScreen", "true"),
                        this._frame.setAttribute("allow", "microphone; camera"),
                        this._frame.style.border = 0,
                        this._frame = this._parentNode.appendChild(this._frame)`

That's all! Keep up the good work guys.

**Comment by damencho** [comment]
Thanks for the report. 
This was fixed in jitsi-meet a few months ago 
https://github.com/jitsi/jitsi-meet/commit/46ccefdfe9046b2e2cfa88698480cc962b53c588
