### ISSUE TITLE
I'd done everything, but screen sharing button still doesn't present at Chrome

### ISSUE THREAD

**Issue by smalltomi3** [jitsi/jitsi-meet#2493]
Here is what I did:

1. Revised the manifest.json, with 
```
 "update_url": "https://meeting.jototech.cn/updates.xml",
  "externally_connectable": {
      "matches": [
          "*://meeting.jototech.cn/*"
```

2. Get the Exension ID: edhfhepkbohecicbjcgnceljemjhiglm

3. Revise the update.xml and upload, please check: https://meeting.jototech.cn/update.xml

```
<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
<app appid="edhfhepkbohecicbjcgnceljemjhiglm">
<updatecheck codebase="https://meeting.jototech.cn/chrome.crx" version="2.0"/>
</app>
</gupdate>
```

4. Successfully drag and drop the extension:
<img width="749" alt="screen shot 2018-02-17 at 12 07 05 am" src="https://user-images.githubusercontent.com/36542855/36316882-81a0c766-1376-11e8-8de6-7998501b9081.png">

5. Revise the configuration of /etc/jitsi/meet/joto-config.js, as following:
```
    desktopSharingChromeExtId: 'edhfhepkbohecicbjcgnceljemjhiglm',
   desktopSharingChromeDisabled: false,
```

6. Open link: https://meeting.jototech.cn/joto, but no screen sharing button

Any thing I did wrong???

**Comment by bgrozev** [comment]
Any messages in the js console?

**Comment by smalltomi3** [comment]
@bgrozev thanks for the reply, please have the console information.
![screen shot 2018-02-17 at 10 11 57 pm](https://user-images.githubusercontent.com/36542855/36341861-b3734430-142f-11e8-967a-d321ccc83366.png)
[meeting.jototech.cn-1518876712888.log](https://github.com/jitsi/jitsi-meet/files/1733737/meeting.jototech.cn-1518876712888.log)

**Comment by damencho** [comment]
Your bosh connection config is wrong. 
And the browser reports the extension to be installed...so the button should be visible.

**Comment by smalltomi3** [comment]
It works after I changed the hostname.. Thanks @damencho
