### ISSUE TITLE
Ngnix doesn't found

### ISSUE THREAD

**Issue by smalltomi3** [jitsi/jitsi-meet#2494]
I followed the quick installation tutorial and Jitsi is working. However I want to change the Ngnix configuration (to auto redirect http to https), but there is no /etc/ngnix folder..

**Comment by smalltomi3** [comment]
Anyone know the path of Ngnix?

**Comment by damencho** [comment]
If you are on system with java8 that comes by default, the preffered webserver is the jetty which is inside jvb. Check your processes probably you don't have nginx running. Normally the nginx config is in/etc/nginx.

**Comment by smalltomi3** [comment]
@damencho Thanks!
Seems my instance is using Jetty not Nginx, wondering how can I force redirect http to https in Jetty? sorry I'm not familiar with Jetty.

**Comment by damencho** [comment]
I'm not sure that this can be currently done with the jetty that is inside jvb, without modifying the code. What you can do is install nginx that only listens on 80 and do the redirection there.
