### ISSUE TITLE
Build release jitsi problem IOS native

### ISSUE THREAD

**Issue by fiirrman** [jitsi/jitsi-meet#2496]
Hai guys,

Can you provide information how to build release jitsi meet in xcode / from react CLI properly?

1. After integrate jitsi meet to my project, im able to running video call from my native apps, but when im trying to build release, which is set build scheme on xcode to release, then i got an error : 

**File /Users/Username/Library/Developer/Xcode/DerivedData/jitsi-meet-encyfefbnjanhjetwxnxljpdzncd/Build/Intermediates.noindex/ArchiveIntermediates/jitsi-meet/BuildProductsPath/Release-iphoneos/JitsiMeet.framework/main.jsbundle does not exist. This must be a bug with echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'**

2. Then i think, maybe Jitsi SDK App can running release mod smoothly. After installing jitsi sdk for ios, i can running the app, and access the conference meet, and then im trying to build release to, but got the same error :

**File /Users/Username/Library/Developer/Xcode/DerivedData/jitsi-meet-encyfefbnjanhjetwxnxljpdzncd/Build/Intermediates.noindex/ArchiveIntermediates/jitsi-meet/BuildProductsPath/Release-iphoneos/JitsiMeet.framework/main.jsbundle does not exist. This must be a bug with echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'**

3. Can you provide some information, how to build release jitsi meet properly? im thinking this from last month, and stressed out :(

**Comment by riobijanero** [comment]
Hi fiirman, I am also trying to integrate jitsi meet to my project. But I#m not as far. Do you have a tip on how to get started on that?

**Comment by ankurkloud** [comment]
[JitsiMeet.framework.zip](https://github.com/jitsi/jitsi-meet/files/2022766/JitsiMeet.framework.zip)
Use this Jitsimeet framework and integrate as given on URL  https://github.com/jitsi/jitsi-meet/tree/master/ios from "API" section onwards.

**Comment by lyubomir** [comment]
To build a release version of JItsi Meet SDK for iOS:
````
git clean -dfx
npm install
cd ios/
pod install
cd ../
xcodebuild -workspace ios/jitsi-meet-react.xcworkspace -scheme JitsiMeet -destination generic/platform=iOS -configuration Release archive
````

You're going to get a link `ios/sdk/JitsiMeet.framework`. Follow the link to get the built JitsiMeet.framework. In your project consuming the JitsiMeet.framework, you'll also need to add WebRTC.framework from `node_modules/react-native-webrtc/ios/`.

**Comment by nasircsms** [comment]
> To build a release version of JItsi Meet SDK for iOS:
> 
> ```
> git clean -dfx
> npm install
> cd ios/
> pod install
> cd ../
> xcodebuild -workspace ios/jitsi-meet-react.xcworkspace -scheme JitsiMeet -destination generic/platform=iOS -configuration Release archive
> ```
> You're going to get a link `ios/sdk/JitsiMeet.framework`. Follow the link to get the built JitsiMeet.framework. In your project consuming the JitsiMeet.framework, you'll also need to add WebRTC.framework from `node_modules/react-native-webrtc/ios/`.

I tried the above steps to build the release version, but facing the same issue
The following build commands failed:
	PhaseScriptExecution Package\ React\ bundle /Users/csms/Library/Developer/Xcode/DerivedData/jitsi-meet-ddnneucdoujxxeattgwbbqzradfg/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-0BCA49651EC4B77500B793EE.sh
(1 failure)

building with Release Scheme in Xcode results in 
error: File /Users/Username/Library/Developer/Xcode/DerivedData/jitsi-meet-ddnneucdoujxxeattgwbbqzradfg/Build/Products/Release-iphoneos/JitsiMeet.framework/main.jsbundle does not exist

Any help here would be appreciated..

**Comment by nasircsms** [comment]
> To build a release version of JItsi Meet SDK for iOS:
> 
> ```
> git clean -dfx
> npm install
> cd ios/
> pod install
> cd ../
> xcodebuild -workspace ios/jitsi-meet-react.xcworkspace -scheme JitsiMeet -destination generic/platform=iOS -configuration Release archive
> ```
> You're going to get a link `ios/sdk/JitsiMeet.framework`. Follow the link to get the built JitsiMeet.framework. In your project consuming the JitsiMeet.framework, you'll also need to add WebRTC.framework from `node_modules/react-native-webrtc/ios/`.

I tried the above steps to build the release version, but facing the same issue
The following build commands failed:
PhaseScriptExecution Package\ React\ bundle /Users/Username/Library/Developer/Xcode/DerivedData/jitsi-meet-ddnneucdoujxxeattgwbbqzradfg/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-0BCA49651EC4B77500B793EE.sh
(1 failure)

building with Release Scheme in Xcode results in
error: File /Users/Username/Library/Developer/Xcode/DerivedData/jitsi-meet-ddnneucdoujxxeattgwbbqzradfg/Build/Products/Release-iphoneos/JitsiMeet.framework/main.jsbundle does not exist

Any help here would be appreciated..

**Comment by Insfgg99x** [comment]
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Package\ React\ bundle /Users/fengge/Library/Developer/Xcode/DerivedData/jitsi-meet-dwwznoxjmugakkabqvajirdiewwp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-0BCA49651EC4B77500B793EE.sh
(1 failure)

**Comment by gmOctal** [comment]
Please provide solution anyone for repo ios build faild 

 JitsiMeet.framework/main.jsbundle does not exist.

The following build commands failed:
PhaseScriptExecution Package\ React\ bundle /Users/fengge/Library/Developer/Xcode/DerivedData/jitsi-meet-dwwznoxjmugakkabqvajirdiewwp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-0BCA49651EC4B77500B793EE.sh
