### ISSUE TITLE
Locking room by moderator [new feature]

### ISSUE THREAD

**Issue by Sp3r4z** [jitsi/jitsi-meet#2499]
Hello,

I'm new on using Jitsi-meet (on the Framatalk.org instance) and before using Jitsi I've used appear.in, and this site gives an option for "locking the room", and new comers have to knock to come in room. I know Jitsi have an option for setting a password, but I find that a bit "heavy" and painful. I find the knocking option easier to "set", and can lead to "I lock my room, because all members are here".

I don't know if you share my opinion about that. If not, no problem, you can close my issue/new feature question.

Have a nice day.

**Comment by bahiamartins** [comment]
I'd love this feature and also mute participants if I am moderator

**Comment by Sp3r4z** [comment]
@bahiamartins as a moderator you can already mute someone, but you can't demute it when you've mute it. Maybe being really the "master" on a room can be cool too.

**Comment by bgrozev** [comment]
I would definitely not want any master unmuting me without my consent :)

**Comment by Sp3r4z** [comment]
@bgrozev That's not my point, and of course it's not a good idea (muting someone can be interesting, but definitely not unmuted ;) )

**Comment by fdcds** [comment]
This seems like a really important feature to me when you are trying to conduct a more formal meeting and as moderator want some control over who can join and listen in. Can it please be reopened?

**Comment by damencho** [comment]
@fdcds what is the request here? Every moderator can lock the room already.

**Comment by fdcds** [comment]
Can you please point me to the button that does this?

I do see the (i) info icon and the "Add password" button on the card that pops up when clicking it. But that is not the feature requested here.

This request is about a feature to lock the room *without setting a password*, where everyone who wants to join the room has to knock (in https://whereby.com/ that means you take a picture of yourself) and the moderator can then let them in (or reject their request to enter).

**Comment by saghul** [comment]
I don't think that's a feature we want to add. We'll check with the team and reopen if appropriate.

**Comment by raphaelh** [comment]
That would be a nice feature, because it enables to use nice room names, and once the meeting starts lock it so other people don't drop in by mistake

It also allows private conversations

**Comment by leupoki** [comment]
As I learned from our data protection manager today, the knocking function ist crucial if you want to use Jitsi "safely" under European GDPR rules. Due to this our (German) company does not allow the use of Jitsi. For companies with fear of data protection issues, a "strong" moderator role and a locking/knocking function would help to spread Jitsi ...

**Comment by EliasSeccom** [comment]
We have customers who want to have a solution who they can safely use for psychotherapy. To guarantee the confidentiality of very private meetings this function absolutely essential. Otherwise  Jitsi-Meet is not a option for them. Please reopen.
