### ISSUE TITLE
Can we Customise JitsiMeetView for iOS ?

### ISSUE THREAD

**Issue by ParvendraSingh** [jitsi/jitsi-meet#2501]
Dear Team.

I have one quick query and one issue ..
Query
Can we customise JitsiMeetView  for iOS Application same as whatsapp calling UI?
If we can so suggest me how can we do it.

And issue is 

when i disconnect the call by taping on red button, Video view take time to remove, it is taking approx half of minut to remove from superview.

**Comment by Shipra08** [comment]
I also want to use jitsi in my app. so please suggest how could we customise jitsi view to be use in IOS app

**Comment by Insfgg99x** [comment]
I also want to use jitsi in my app. so please suggest how could we customise jitsi view to be use in IOS app

**Comment by NaveenDelegate** [comment]
I also wish to customise Jitsi view to be use in IOS app. Please help.
