### ISSUE TITLE
Screensharing infinitely loops

### ISSUE THREAD

**Issue by tmcgee123** [jitsi/jitsi-meet#2506]
Currently, if you choose Your Entire Screen, the sharing goes Inception mode and infinitely pulls in the screen sharer's window
<img width="1402" alt="screen shot 2018-02-21 at 4 28 47 pm" src="https://user-images.githubusercontent.com/6415216/36509373-1ef772e2-1725-11e8-8f56-a045c93c16f4.png">

Also, not sure if it's important, but we are using the atlassian.video room for the meet

**Comment by damencho** [comment]
This is a known effect, it is like if you put two mirrors next to each other there is nothing we can do about the image that loops in the mirrors :)
Normally the presenter that is sharing its screen shows a page, presentation or its desktop and does not show the meeting that the other participants already are looking at. A workaround is to click on someone else's video to avoid the mirror effect.

**Comment by L4mPi2** [comment]
Hi @damencho ! Sorry to bother you, is there any way to do something like this? 
Let's say i click screen sharing, would it be possible to not show my own window until i pick what exactly i want to share? So, nothing displays until i've chosen tab or window or app ?
Thanks in advance

**Comment by damencho** [comment]
@L4mPi2 I suppose it is possible, but you need to modify either chrome, either Firefox, submit to them a patch and wait for it to be released accepted and pushed to their stable release.
Another option is to implement this in jitsi-meet-eletron-utils and use it with jitsi-meet-electron.

**Comment by L4mPi2** [comment]
Thanks @damencho I think i could explore your latter suggestion. I'm not very familiar with electron. i'm trying to have a built-in chat within my app but i wanted to prevent this infinite window self-mirroring because clients think it's a bug, and i'm tired of saying that's not a bug, so i'm desperate to find a workaround to ease my client's UX.

**Comment by mikehenken** [comment]
+1: Other screenshare and conference tools do not have this issue. It is a bug that looks unprofessional in client meetings.

**Comment by ChristineBoersen** [comment]
Here's what I'm testing locally to work around it. Add this to your css (or into your build for the css).
**This only fixes when in tile mode.** 
If viewing in full screen mode, AND viewing the browser window, you will still get the mirror effect (and doubt there is a way around that)

// HACK to prevent mirror effect when sharing whole screen
#localVideoTileViewContainer {
    display: none !important; 
}

**Comment by JeromeDeGresy** [comment]
I confirm two things : 
- Jitsi is pretty awesome
- The only disturbing issue is this infinite mirror loop effect

**Comment by logicalin** [comment]
Hi, would it be possible for the presenters tile to always only show their camera feed?  We do split 75/25 presenting and a camera-only feed in the tile would work for us.  We do the split to allow the presenter to remain in video.

**Comment by nagkumar** [comment]
How to handle this.. that way it is so pathetic, basic screen share messes it all..not usable at all..

**Comment by utrotzek** [comment]
In my opinion, the own shared screen should simply not be visible in the own frontend at all. Maybe a placeholder icon "Sharing screen" should be displayed. This would avoid the mirroring effect when acciddentally opening the jetsi session while sharing the screen.

**Comment by shaileshjadav** [comment]
I am facing same issue with dolby conference tool. any one can help me?

**Comment by hex-m** [comment]
Our friends over at BBB implemented a [workaround](https://github.com/bigbluebutton/bigbluebutton/pull/12522).

It seems this is not unsolvable and therefore this issue should be kept open imo.

**Comment by kingdom553** [comment]
I am also facing the mirro screen sharing issues on myside.
How do I resolve this problem?

**Comment by akalana** [comment]
Hey @kingdom553 
I think this issue has been fixed now
