### ISSUE TITLE
SSL change from Letsencrpyt to custom SSL

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#2507]
Hi,

I have not been able to find any forum for Jitsi other than this "issues" on github. I don't need anyone to solve my issue but please just point me in the right direction.

I have a successful install using Apache 2 and Letsencrypt.
Everything works perfectly.

My issue is that I have an SSL for my domain that I would like to use so that we don't have this "trusted site" issue on browsers. How do I change from using the LetsEncrypt SSL to my own custom SSL from SSLs.com for my domain?

Things like this never get responses but this issue, I'm sure will have many who want to know the same. Can someone please guide me to or state what needs to be done. Thanks

My current working apache2 / jitsi config using letsencrypt
`
<VirtualHost *:80>
    ServerName my_domain.com
    Redirect permanent / https://my_domain.com/
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>

  ServerName my_domain.com

  SSLProtocol TLSv1 TLSv1.1 TLSv1.2
  SSLEngine on
  SSLProxyEngine on
  SSLCertificateFile /etc/letsencrypt/live/my_domain.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/my_domain.com/privkey.pem
  SSLCipherSuite "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED"
  SSLHonorCipherOrder on
  Header set Strict-Transport-Security "max-age=31536000"

  DocumentRoot "/usr/share/jitsi-meet"
  <Directory "/usr/share/jitsi-meet">
    Options Indexes MultiViews Includes FollowSymLinks
    AddOutputFilter Includes html
    AllowOverride All
    Order allow,deny
    Allow from all
  </Directory>

  ErrorDocument 404 /static/404.html

  Alias "/config.js" "/etc/jitsi/meet/my_domain.com-config.js"
  <Location /config.js>
    Require all granted
  </Location>

  ProxyPreserveHost on
  ProxyPass /http-bind http://localhost:5280/http-bind/
  ProxyPassReverse /http-bind http://localhost:5280/http-bind/

  RewriteEngine on
  RewriteRule ^/([a-zA-Z0-9]+)$ /index.html
</VirtualHost>
`

and a custom SSL from SSLs.com Apache2 config I have for another site

<VirtualHost *:80>
   ServerName my_domain.com
   Redirect permanent / https://my_domain.com/
   DocumentRoot /var/www/html
</VirtualHost>
<VirtualHost *:443>
SSLEngine on
SSLCACertificateFile  /etc/apache2/ssl/my_domain.com.ca-bundle
SSLCertificateFile /etc/apache2/ssl/my_domain.com.crt
SSLCertificateKeyFile /etc/apache2/ssl/my_domain.com.key

	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName my_domain.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
	
	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by ibeardslee** [comment]
updates these lines with the path to the files from your other SSL provider
```
SSLCertificateFile /etc/letsencrypt/live/my_domain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/my_domain.com/privkey.pem
```

**Comment by StreamTitan** [comment]
Awesome!

Thank you! That worked great.
I'm sure this will help others because changing from LetsEncrypt to a custom SSL is an uncovered topic in Jitsi.

Note to others: After editing the above to make the changes, don't forget to restart the server. Changes to virtualhosts files require a server restart before they can take effect.

**Comment by MichaelGrigoryan25** [comment]
Hello, where can I find the SSL key and cert directory cause i don't have a "live" dir.
