### ISSUE TITLE
Jicofo only listen 127.0.0.1.

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#2514]
I tested load balancing but could not connect to the jicofo server because it only listened to connections from address 127.0.0.1. Please tell me how to fix it. Thank you.

![image](https://user-images.githubusercontent.com/26251116/36585893-3b67cdda-18b2-11e8-998d-b13dd808fcbb.png)

**Comment by damencho** [comment]
If you are talking about 127.0.0.1:5347, this is not jicofo this is prosody. 
To change that open:
/etc/prosody/prosody.cfg.lua
And add/edit the following line:
component_interface = "0.0.0.0"
This way prosody will listen on all interfaces. You can specify specific address to listen to: component_interface = "some.ip.v4.address".
And of course restart prosody after modifying the commit (you need to wait a bit about jicofo and jvb to reconnect or you can just restart jvb and jicofo in this order after restarting prosody).
