### ISSUE TITLE
Can't access camera

### ISSUE THREAD

**Issue by Maddie1233** [jitsi/jitsi-meet#2516]
Help! conference call starts in five! m

**Comment by aaronkvanmeerten** [comment]
Have you tried turning it off and on?

**Comment by StreamTitan** [comment]
New version has issues with Firefox v58 try another browser.

**Comment by danboid** [comment]
My laptop webcam is off by default (under Ubuntu) so I have to turn it on first by pushing Fn+F10 although it could be any key combo depending on your laptop model.

**Comment by divyamiot** [comment]
unable to access camera
