### ISSUE TITLE
Jitsi load balancing show error org.xmpp.component.ComponentException: host-unknown

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#2517]
I do load balancing as the model below (follow the tutorial https://github.com/jitsi/jicofo/blob/master/doc/load_balancing.md). I'm not sure if the configuration is correct, please help me to check again.
I get the error message at videobridge server
`SEVERE: [21] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:jcofo.example.com, port:5347
org.xmpp.component.ComponentException: host-unknown`

![image](https://user-images.githubusercontent.com/26251116/36626759-fe2c41ee-196a-11e8-9b04-983d62539a2d.png)

Please help me fix this problem. Thank you so much everyone.

**Comment by damencho** [comment]
Does jcofo.example.com resolve to prosody's machine IP address? If not fill in JVB_HOST with the IP-address of the prosody server in both jvb configurations.

**Comment by pekubu** [comment]
@damencho 
So how does it work?
My prosody config 
`VirtualHost "jcofo.example.com"
        authentication = "anonymous"
        ssl = {
                key = "/etc/prosody/certs/jcofo.example.com.key";
                certificate = "/etc/prosody/certs/jcofo.example.com.crt";
        }
        modules_enabled = {
            "bosh";
            "pubsub";
            "ping"; -- Enable mod_ping
        }
        c2s_require_encryption = false
Component "conference.jcofo.example.com" "muc"
    storage = "null"
    --modules_enabled = { "token_verification" }
admins = { "focus@auth.jcofo.example.com" }

Component "jcofo.example.com"
    component_secret = "osMMoHUX"

VirtualHost "auth.jcofo.example.com"
    ssl = {
        key = "";
        certificate = "";
    }
    authentication = "internal_plain"

Component "focus.jcofo.example.com"
    component_secret = "fqvfG@xF"
`

**Comment by damencho** [comment]
And what was the error when you tried that?

**Comment by pekubu** [comment]
`SEVERE: [21] org.jitsi.meet.ComponentMain.call().278 host-unknown, host: (ip of jicofo server), port:5347 org.xmpp.component.ComponentException: host-unknown`

**Comment by pekubu** [comment]
And error log of prosody 
```
 Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>jvb1.example.com$
Feb 24 10:23:29 jcp1100870      info    component disconnected: nil (false)
```

**Comment by damencho** [comment]
You need to fix your prosody config.
You cave Component "jvb1.example.com", but if you add JVB_HOSTNAME=jvb1.example.com the component name used is jitsi-videobridge.jvb1.example.com.

There is another option, if you want to run with the current config of prosody you need to change videobridges config:
JVB_HOSTNAME=example.com
JVB_OPTS="--subdomain=jvb1"
This way jvb will use as a component name jvb1.example.com and it will match your prosody config.

**Comment by pekubu** [comment]
thank you, I'll try it

**Comment by bgrozev** [comment]
> SEVERE: [21] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:jcofo.example.com

Your prosody configuration does not include a component for "jcofo.example.com" (it has one for focus.jcofo.example.com)

**Comment by pekubu** [comment]
@damencho  
```
JVB_HOSTNAME=example.com
JVB_OPTS="--subdomain=jvb1"
```

If I make such a configuration, I get a "time-out" error.
How to fix it :(

**Comment by varma-nexge** [comment]
JVB 2020-03-12 10:53:40.987 SEVERE: [56] org.jitsi.meet.ComponentMain.log() not-authorized, host:video-conf.nexge.com, port:5347
org.xmpp.component.ComponentException: not-authorized

**Comment by varma-nexge** [comment]
can you pls anyone help

**Comment by damencho** [comment]
Wrong secret used for authenticating the component. Match the value from prosody config and the one configured in `/etc/jitsi/videobridge/config`.

**Comment by varma-nexge** [comment]
#Main server
vi /etc/prosody/conf.d/video-conf.nexge.com.cfg.lua

Component "jitsi-videobridge.video-conf.nexge.com"
    component_secret = "oYu2LxSl"
Component "videobridge2.video-conf.nexge.com"
    component_secret = "zedfP4Gu"

#Main Server
#/etc/jitsi/videobridge/config

# sets the XMPP domain (default: none)
JVB_HOSTNAME=video-conf.nexge.com

# sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
JVB_HOST=video-conf.nexge.com

# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347

# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=oYu2LxSl

# extra options to pass to the JVB daemon
JVB_OPTS=--apis=rest,xmpp --subdomain=videobridge2

#Second server

/etc/prosody/conf.d/video-conf.nexge.com.cfg.lua

# sets the XMPP domain (default: none)
JVB_HOSTNAME=video-conf.nexge.com

# sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
JVB_HOST=video-conf.nexge.com

# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347

# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=zedfP4Gu

# extra options to pass to the JVB daemon
JVB_OPTS="--apis=rest,xmpp --subdomain=videobridge2"

Note : i configured like this

**Comment by damencho** [comment]
You have in both bridges this `JVB_OPTS="--apis=rest,xmpp --subdomain=videobridge2"` same subdomain, which is wrong.

**Comment by damencho** [comment]
And by the way, we are moving away from the components used for jvb, so you better use this method for multiple jvbs:
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/muc.md

**Comment by varma-nexge** [comment]
ok bro now i didnt find any error but if i down main server jvb, unable to create room it gets down, but im able to see if i down n up second jvb i am able to see intimation in first jvb

I just down both jvb n started one by one and checked in jicofo.log

Jicofo 2020-03-12 14:15:07.383 SEVERE: [30] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverVersion().200 Failed to discover version, req: <iq to='jitsi-videobridge.video-conf.nexge.com' id='WTWlq-2196' type='get'><query xmlns='jabber:iq:version'></query></iq>, response: <iq to='focus@auth.video-conf.nexge.com/focus10394294011428' from='jitsi-videobridge.video-conf.nexge.com' id='WTWlq-2196' type='error'><error type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
Jicofo 2020-03-12 14:15:07.384 INFO: [30] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: jitsi-videobridge.video-conf.nexge.com, null
Jicofo 2020-03-12 14:15:07.384 INFO: [30] org.jitsi.jicofo.BridgeSelector.log() Added videobridge: jitsi-videobridge.video-conf.nexge.com v: null
Jicofo 2020-03-12 14:15:07.384 WARNING: [30] org.jitsi.jicofo.BridgeSelector.log() No pub-sub node mapped for jitsi-videobridge.video-conf.nexge.com
Jicofo 2020-03-12 14:15:07.385 INFO: [52] org.jitsi.jicofo.JvbDoctor.log() Scheduled health-check task for: jitsi-videobridge.video-conf.nexge.com


Jicofo 2020-03-12 14:15:37.367 SEVERE: [30] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverVersion().200 Failed to discover version, req: <iq to='videobridge2.video-conf.nexge.com' id='WTWlq-2222' type='get'><query xmlns='jabber:iq:version'></query></iq>, response: <iq to='focus@auth.video-conf.nexge.com/focus10394294011428' from='videobridge2.video-conf.nexge.com' id='WTWlq-2222' type='error'><error type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
Jicofo 2020-03-12 14:15:37.368 INFO: [30] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: videobridge2.video-conf.nexge.com, null
Jicofo 2020-03-12 14:15:37.368 INFO: [30] org.jitsi.jicofo.BridgeSelector.log() Added videobridge: videobridge2.video-conf.nexge.com v: null
Jicofo 2020-03-12 14:15:37.368 WARNING: [30] org.jitsi.jicofo.BridgeSelector.log() No pub-sub node mapped for videobridge2.video-conf.nexge.com
Jicofo 2020-03-12 14:15:37.369 INFO: [52] org.jitsi.jicofo.JvbDoctor.log() Scheduled health-check task for: videobridge2.video-conf.nexge.com
