### ISSUE TITLE
IE 11 does not have sharing icon

### ISSUE THREAD

**Issue by f987002856** [jitsi/jitsi-meet#2519]
Hi,I met a problem.
 when i use IE 11 open my own jitsi-meet application,there has no screen sharing icon.But when i use https://meet.jit.si/,it can see the screen sharing icon.
 I also look other issue,it says need to install Temasys plugin. But In the IE management add-in，i saw the
plugin which name is "Plugin allowing browser without native handling of WebRTC to actually use it".
Before i met this problem,i used my own jitsi-meet appcication in Chrome,It also can not see the screen sharing icon.But i set the chrome plugin id in config.js and resloved it.
I want to know,how can i to set then let the IE can see the screen sharing icon.
Please help me,thanks.

**Comment by daimoc** [comment]
Hi,

If you're using your how jitsi-meet server you need to provide your own
chrome plugin extention to enable screen sharing to respect google screen
capture secure policy.
You can found all informations on this page
https://github.com/jitsi/jidesha/blob/master/chrome/README.md .

For IE11 and screensharing option, according to Temasys plugin infromation (
https://confluence.temasys.com.sg/display/TWPP), you need a commercial
version of the plugin.
I don't know if it's still true, and why IE11 screensharing is enable in
meet.jit.si server. May be there have a commercial licence for this?

Reagards,
Damien.


2018-02-26 9:09 GMT+01:00 bfther <notifications@github.com>:

**Comment by damencho** [comment]
Yes, that is correct. You need commercial version and yes meet.jit.si has one. But temasys support can go away soon.
