### ISSUE TITLE
Gravatars must remain the same even when random

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#252]
Currently, unless users input their own gravatar id, a random one is chosen for them.

If the gravatar service allows this we should make sure we show the same one every time.

**Comment by bgrozev** [comment]
AFAIK this is supposed to be already implemented, with the random string being saved in local storage.

**Comment by gpolitis** [comment]
f48633fa1d39d4802a135205925fa6b58a7cc14e broke this and it also broke the active video thumbnail blacking out. @paweldomas is it OK if we revert the commit?

**Comment by gpolitis** [comment]
OK, broke is a harsh word :-) but I don't know what else I could have used instead!

**Comment by hristoterezov** [comment]
I think we shouldn't revert the whole commit. Maybe we should keep the code for sending userId, email and displayName and maybe some of the other fields but not all.

**Comment by paweldomas** [comment]
No don't revert that. I will fix it. There is unused stuff mixed with used
stuff.

**Comment by paweldomas** [comment]
Fixed in f986211.
