### ISSUE TITLE
How to disable p2p

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#2522]
I want to use JVB for two people in the room, How to implement it.
Please help me, thank you.

**Comment by damencho** [comment]
By default, p2p is enabled. You need to disable it in your config.js (/etc/jitsi/meet/.....-config.js)
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L283

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/60808453-e89b6d80-a1ba-11e9-9359-3d17178e0a5e.png)

When I disabled P2P, there was no screen

**Comment by zsinba** [comment]
// Suspend sending video if bandwidth estimation is too low. This may cause
    // problems with audio playback. Disabled until these are fixed.
    disableSuspendVideo: false,

I think it's the effect of this parameter.Set it to false and you can see the screen.
