### ISSUE TITLE
Firewall configuration

### ISSUE THREAD

**Issue by tenchooo** [jitsi/jitsi-meet#2527]
Hi all, 

Maybe it's just me but i can't find any configuration guide for firewalls on jitsi servers, so since i installed jitsi meet using ubuntu repository and i use ufw, are the following the only ports i need to allow in my firewall? and is it secure with the default config?

- 443/tcp - frontend
- 4443/tcp - videobridge
- 10000/udp - videobridge

**Comment by damencho** [comment]
Yep, those ports are correct. What you mean by is it secure? Yes it is, traffic is encrypted if this is what you are asking.

**Comment by visualecho1** [comment]
Is port 8888/tcp from jicofo on this list? (or should it be?)

**Comment by damencho** [comment]
Nope, this port is for health checks which are supposed to be done from localhost. So this port should not be exposed publicly.
