### ISSUE TITLE
No sound with phone call (in France).

### ISSUE THREAD

**Issue by pparent76** [jitsi/jitsi-meet#2529]
On meet.jit.si whenever someone joins with a phone call, we can hear him, but he cannot hear us.

The problem does not happen with webrtc client, only with phone call clients that call the french number, cannot hear the other ones.

It was tested with many phones, the result is the same.

**Comment by pparent76** [comment]
Just tested again it seems to work, but last week it did not work and we did many tests.

**Comment by damencho** [comment]
Yep, there was a problem with the provider, which we fixed at some point last week (Feb 19). 
Thanks for reporting, if you experience such issues again, please report them. Thanks!
