### ISSUE TITLE
Allow guest people to view confrence, without being involved in.

### ISSUE THREAD

**Issue by dev-mraj** [jitsi/jitsi-meet#253]
at start i need to share my cam. so please make a function so people can participate whenever they want.
so it will be also usefull for people who are looking for prensation like use cases or broadcasting cam etc.

if its not right issue then please help to how to achieve this whenever 5-6 people will discuss and 1000s of others will watch.

**Comment by gpolitis** [comment]
Sounds like you want to check out the LastN feature of the JVB. This is an integer, which can be set on a specific video channel. If set to N for a channel, only the video from the first N other endpoints in the conference will be sent to the channel. The endpoints are ordered by the last time they were the "dominant speaker". In meet you can control this by setting the channelLastN configuration param.

**Comment by dev-mraj** [comment]
i think i've tried that too, but that still call getUserMedia and ask for
webcam. any solution for that?

**Comment by gpolitis** [comment]
We don't have that right now but it seems like an interesting idea.

**Comment by dev-mraj** [comment]
I am on deadlines to make this work..

Can you please give me hints to achive this..i have even tried putting some
blank media stream (new webkitMediaStream) instead of real webcam stream
but didnt work either...

**Comment by fippo** [comment]
this isn't trivial. Participants without streams are something which needs careful considerations, both in the client as well as the focus.

**Comment by dev-mraj** [comment]
this is important, like use cased of class room. where teacher is on webcam and other all are listener. and for this case we have tried janus, kurento and finally we are moving to jitis due to its high perforamance and less CPU and scalable architecture (till yet i didn't understand its architecture completly ).

**Comment by dev-mraj** [comment]
is that possible?

**Comment by nwittstruck** [comment]
You could record the conference, stich it together/synchronize it using ffmpeg and immediately start streaming the conference via ffserver or a different streaming tool. But this is definitely not the best approach.

**Comment by magatz** [comment]
Hi, i'm trying to achieve exactly the same feature.
At this time, i've simply muted both video and audio, when joining the room. 
Clearly it is still requesting access to the webcam, but it works (I've monitored the network i/o, and looks like, that only the "broadcaster" is sending data to videobridge, while the "watcher" are only receiving data.
Anyway i'm thinking about create "fake" stream and send them to the videobridge, in order to avoid webcam detection.

**Comment by hristoterezov** [comment]
dbcfc92dc4744e3540fd90be5f98700c442df49c changes the implementation to allow users with no camera and microphone to join the conference. Also if deny chrome to access your camera and microphone when you are prompted you can also join the conference without camera and microphone.

**Comment by dev-mraj** [comment]
i tried this commit..
on my local network these kind of errors

```
Jingle error Object {source: "answer"}
 Jingle error Object {source: "answer"}
Jingle error Object {source: "transportinfo"}
Jingle error Object {source: "transportinfo"}
Jingle error Object {source: "transportinfo"}
```

**Comment by gpolitis** [comment]
@dev-mraj those messages are usually harmless. Does it work if you ignore these?

**Comment by dev-mraj** [comment]
its not working thats why i am getting worried?

i just modified your code a little, because i can't ask for webcam at startup..

so i placed this.rtcUtils.successCallback(null) instead of obtainAudioAndVideoPermissions at RTC.js:136

and when user want to share cam i called  obtainAudioAndVideoPermissions()

**Comment by gpolitis** [comment]
Without modifying the code, do you get any other errors (other than the four you mentioned before)?

**Comment by hristoterezov** [comment]
@dev-mraj what do you mean by not working. It asks for permissions but if you deny chrome to use your camera and microphone the user should join the conference. Also if you don't have camera and microphone you will be also able to join the conference and watch/hear the other participants.

**Comment by dev-mraj** [comment]
yes i test again without modiification it worked.

but i am in situation where use will share cam in middle of conference. user wil have button to start sharing his cam..

i am working on this and i think APP.xmpp.switchStreams sholud work for this, whatever i'll let you know further soon.

any hints for to do this.

**Comment by dev-mraj** [comment]
using switch stream its almost done, 
but when first time page loads and user share fake streams..then other peer's streams comes and statics shows but video don't come in until we do share our cam..

i am using switchStreams function here to replace our fake local streams with new webcam's streams.
http://37.187.137.134:8001/test3

**Comment by dev-mraj** [comment]
now i've done, and its working for me user can start stop cam anytime, and everthing works fine, maximum 6 user can share their cam. then all will viewer.

but when i did testing after 30+ users its getting bit slow and chrome's cpu is also gettng increased even (no issue with server's cpu)

any suggestions for best optimum configurations in jitisi for such use cased. (config.js)

**Comment by bgrozev** [comment]
@dev-mraj, Is this with LastN=6? Is everyone sending audio?

Closing since the original issue seems resolved.

**Comment by dev-mraj** [comment]
Yes thanks issue has be solved, no doubt.

i was just looking for suggestions that might help me and others too.

**Comment by bgrozev** [comment]
I see you are indeed using LastN=6. I don't think we have thoroughly tested the client performance yet. If it uses too much CPU with 30 endpoints (compared to say 6) there might be a bug in the client. Maybe you can run chrome's profiler and try to pinpoint it.

**Comment by Zalmoxisus** [comment]
AFAIK, LastN restricts only video streams. So, if we have 30 endpoints, each user will receive 29 audio streams though. This may cause increasing cpu.

**Comment by dev-mraj** [comment]
i didn't knew about this... i was planing to make it working at least 1000 user..
and if its still making audio streams then it will big trouble for me...

anybody who knows core of jitis can suggest solution to make it work to publish few videos to almost 1000 users.

**Comment by dev-mraj** [comment]
Hi, @Zalmoxisus sorry i just forget to mentions that according to main issue (above which has been solved), audio video streams has been replaced with fake media streams. so connections can established without sharing webcam or audio.

what will be optimum configuration in config.js in this use case.
like here are few things (currently what i am using) that i didn't get properly.

```
        openSctp: false, // Toggle to enable/disable SCTP channels
        disableStats: true,
        resolution:"180",
        channelLastN: -1, // i can control this so thats why i am not using this
        adaptiveLastN: false,
        adaptiveSimulcast: false,
        useRtcpMux: true,
        useBundle: true,
        enableSimulcast: false,
```

**Comment by Zalmoxisus** [comment]
Hi, @dev-mraj. Could you please share how you faked audiostream? Have you tested wether you have cpu sparks when you just pass a null value for the stream? I'm not a big expert, but I'm also interested in such a feature.

**Comment by dev-mraj** [comment]
Hi, 
here is url where i am doing testing, i modified a bit UI code, and these same code is being used in my main big application where UI Module is completely removed but both's working is identical.
http://37.187.137.134:8001/test3
see above there 6 users, and it will start but after a little while videos will be freezed and work very slowly, even i've tested same on high speed servers..

**Comment by eroy4u** [comment]
Hi dev-mraj, 
Did you solve the slowness issue and manage to make it work with 1000 clients? I'm having a similar scenario and is evaluating whether jitsi or janus could do the job. Any comments would be appreciated, thanks.
