### ISSUE TITLE
Tutorial for Building Out an install from scratch: Ubuntu 16.04/Apache2

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#2531]
Hi Fellow Jitsters!
The following is a tutorial for installing and building out Jitsi-Meet.
I, like many, have had some difficulty to install and I was helped by "damencho" and "aaronkvanmeerten". In the end everything worked perfectly and the best thank you I can give is to help others with their installs and do a tutorial.

Now there is the Quick Install & the Build Out install.
The difference is that the Quick Install will give you a working Jitsi-Meet but you won't be able to edit the homepage and other files because they need to be Built Out.

This Tutorial covers the "Build Out install" which allows you to edit the files and have those changes show on your Jitsi-Meet site.

# Lets get started

Our machine: Ubuntu 16.04 / Apache2
Our tools: Putty / Filezilla / Notepad++ 
- Lets update before we begin. Its always a good practice to do this so you're up-to-date
apt-get update

- Now we need to install Apache2
apt-get install apache2

You would need to restart Apache2 after the install but since the following modules also need a
restart, lets wait a bit to do the restart.

- Now we need to install the modules that would be needed later. Might as well do them all now.
a2enmod ssl
a2enmod headers
a2enmod proxy
a2enmod rewrite

- Now we can do our server restart
sudo service apache2 restart

- We have some content to grab later and for that we'll need Curl so lets install it
sudo apt-get install php-curl

Both Nodejs and NPM are needed to install Jitsi-Meet so lets get that done too. 
- Each line below is a command to enter.
sudo apt-get install build-essential libssl-dev
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.7/install.sh -o install_nvm.sh
bash install_nvm.sh
rm install_nvm.sh

Now CLOSE PUTTY and RE-OPEN it again. Login again then continue
- To see all the versions of nodejs enter
nvm ls-remote

- We want to install the latest version (9.2.1) so lets do that. Its will also install NPM
nvm install 9.2.1

- Lets check our version of Nodejs to confirm we are using what we wanted.
node -v

- And the same check for NPM
npm -v

Your read outs should have 9.2.1 and 5.5.1

# DOING GREAT!!

- Python 2.7 is needed for Jitsi-Meet so now we install that as well
 sudo apt install python2.7 python-pip

- Lets check that we have Python 2.7 installed
python --version

You should have a read out as Python 2.7.12

# Part 1 DONE! 
That was cool and we're ready to go again with the Jitsi-Meet install

- Now we need to get the Jitsi-Meet Repository
echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list

- Then
wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -

- Now let's install Jitsi-Meet
apt-get -y install jitsi-meet

- Now we get the directory set
cd /opt

- And we Git Clone Jitsi-Meet in
git clone https://github.com/jitsi/jitsi-meet.git

- Lets change directory again so this time we are in the Jitsi-Meet directory
cd jitsi-meet

- Now we do the install using NPM (this is going to take about 320 seconds)
npm install

- We're now ready to Build Out our Jitsi-Meet (this will take a while but its doing its thing)
make

The 'make' process takes some time (about 5 mins)

- Now we have to do a chown (change the owner and group assigned to files, directories and links)
chown -R www-data:www-data jitsi-meet

Awesome job so far! If you've done all of the above you'll have zero issues to this point.
Lets configure our conf files so that apache will be able to show Jitsi-Meet
Its BEST TO USE NOTEPAD++ for this part

NOTE!! There are only 2 files that we need to edit. 
Don't go editing other config files!!

# File 1
Edit the file /etc/apache2/sites-available/YOURDOMAIN.conf

When you go to the sites-available directory you'll see the conf file with your domain on it
Open that file with Notepad++ and lets make some changes

- There are 2 places which show: /usr/share/jitsi-meet
- Just replace those two places of "/usr/share/jitsi-meet" with "/opt/jitsi-meet".

# File 2
Edit the apache2.conf file
- Now we need to edit the apache2.conf file. It is at /etc/apache2/apache2.conf
Again, open the file with Notepad++ and add to it (where the other directories info are)

        <Directory /opt/jitsi-meet/>
    	    Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
        </Directory>

Hopefully you have saved these 2 conf files and re-uploaded them back to the server.
As always, every time you edit an apache configuration, you MUST restart the server for changes to
take pace.

sudo service apache2 restart

# THAT'S IT!!
If you've done all of the above you will 100% have a working "Built Out" Jitsi-Meet

Some future editing notes:
If you edit the contents of the static folder no 'make' is needed.
If you edit the index.html page (for example the text) you must do the 'make' command

- Example, if you do special edits to the files, you need to run commands to have them show:
cd /opt/jitsi-meet
make

Thanks for reading through and hopefully all went well.
Regards,
StreamTitan

**Comment by damencho** [comment]
For installing nodejs I would say use LTS version and there are instructions on nodejs.org about that:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
Just I'm not familiar with this nvm and what are its advantages, instead of using upstream debian repo.

**Comment by hemantasapkota** [comment]
Excellent tutorial. I'll just add that after this step in Part 1,

```wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -```

Don't forget to call ```apt-get update```

Thanks

**Comment by PhuCuong14ctt** [comment]
I did follow strictly this tutorial. But nothing happens. When i access to my dns, it's still apache default page.
I edited config files already.

**Comment by rhwu** [comment]
Great tutorial!

A newbie question: the "make" process takes very long to finish. How do people usually work on this, i.e. do you need to run make in order to test any of your modification? Is there a way to run the site without webpack?

Thanks!

**Comment by asawin11** [comment]
Hello @StreamTitan 
When I put command "npm install" my Ubuntu16.04 print out this error "npm ERR! cb() never called!" and that's why I can't "make"it. For your information, my node -v is 10.8.0 and my npm -v is 6.2.0.

Thank you in advance for you answer.

**Comment by saghul** [comment]
Closing this, since there is nothing actionable.

@asawin11 Please open a new issue and make sure you include all relevant information such as a full backtrace.

**Comment by antch57** [comment]
This tutorial has saved my life....Thanks for posting!

**Comment by thecodecafe** [comment]
Hey @StreamTitan thanks for this awesome tutorial, but I'm facing a bit of a problem here and don't know if you can help, when I run `make` the command uses Webpack to bundle the project, only thing is I don't see how I can host this, in the index.html I see comments for things that are to be replaced after compilation, they're still there even after I run `make` on my terminal, what should I do next if I want to host this myself on my server? It's quite confusing what I'm supposed to do, please help.

**Comment by ky3297** [comment]
Hey all, this tutorial is really helpful thanks, I was wondering is there any updated version for ubuntu 18.04 or will this tutorial still work?
