### ISSUE TITLE
CSS & Main.json

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#2532]
1. I've been editing the all.css file in /opt/jitsi-meet/css but the css changes are not showing after the build out (make). Page is still the same. 

The last lines of my 'make' reads:
./node_modules/.bin/node-sass css/main.scss css/all.bundle.css && \
./node_modules/.bin/cleancss css/all.bundle.css > css/all.css ; \
rm css/all.bundle.css
Rendering Complete, saving .css file...
Wrote CSS to /opt/jitsi-meet/css/all.bundle.css
([ ! -x deploy-local.sh ] || ./deploy-local.sh)
rm -fr build

2. The main.json edits does change text after build but I've haven't been able to do "new lines" (line breaks) in the text using \n and \r.

**Comment by damencho** [comment]
Did you try hard refresh on the page?

**Comment by StreamTitan** [comment]
yes, the text from main.json updated, which means that the build is making and display the edits.
The css is not because I updated the css to 12px and its still showing at 20px on the site when viewed from a hard refresh or browser which had not yet cached the site.:

      .welcome .header .header-text-description {
          color: #fff;
          font-size: 12px;
          line-height: 28px;
          opacity: .8
      }

The "new line" in main.json is also proving challenging.

**Comment by StreamTitan** [comment]
There are some things I haven't been able to do with the 'make' build out of the homepage.

1. Not able to create a new line. I have tried:
      '\n', \n, '\r', \r, \\n, \r\n, <br> etc
Just about everything I can think of for a new line and no luck. There is no example of a new line in any of the jitsi files either that I could have used.

2. Not able to create a link to a static page on the homepage. It comes out as a text string on the page.

3. Not able to have any changes to the all.css file shown on the homepage.

**Comment by damencho** [comment]
1. I have no Idea what is your goal, but search for a resolution in Internet, there are plenty of html tutorials.
2. No idea either, but it also seems like html problem.
3. all.css is a generated file. You need to modify the files under css folder and then do make which will generate new all.css file, if you modify it directly make will clean your changes.

**Comment by StreamTitan** [comment]
1 & 2. These are not html issues they are json issues and its meant to bring it to the jitsi team's attention as future jitsi-meet users will want to edit the homepage to reflect their use of Jitsi.

3. Thanks

**Comment by damencho** [comment]
Main.json is suppose to keep only language and translations, formatting is in the css.

**Comment by StreamTitan** [comment]
That explains things. Thank you
