### ISSUE TITLE
Is it possible to skip password required after creating a room?

### ISSUE THREAD

**Issue by HackerUnicorn** [jitsi/jitsi-meet#2533]
Hello,

I'm installing jitsi-meet for a camera feed from one office to another. We only need the video to see each other nothing else. I was configuring prosody for jitsi-meet and my question is do you really need auth.domain.com, conference.domain.com,jitsi-videobridge.domain,com and focus.jitsi.domain.com? Is there anyway to only use domain.com and ignore focus.domain.com etc.? 

My jitsi-meet works until I try to go to a new room and I get the window where it asks me user@domain.net and user password. After that my login fails and I can see when I inspect the page that it tries to use focus.domain.com even if I haven't defined it in prosody. Is it installed with some module? Or is there anyway to skip the password required and go straight to room? 

With inspect it shows after login failed: `[conference.js] <e.value>: CONFERENCE FAILED: conference.focusDisconnected focus.domain.com`

I'm still new on installing jisti-meet and using prosody and I tried to google this one but couldn't find any answer to my question.

**Comment by damencho** [comment]
So what you are trying to achieve is having jitsi meet deployment protected by password, is this correct?  

All those domain as internal and are needed by the different components.

**Comment by HackerUnicorn** [comment]
Thank you, I was trying to find out whether I needed those subdomains or not. Just made subdomains for the site so hopefully it works this time.
