### ISSUE TITLE
Password required to create room

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#2536]
Can someone point me in the right direction?

Looking for documentation on, or example of, a password required to create a room.
As is, anyone can create a room which can crash our server if it gets overloaded.

We'd like to have a password required to create a room.

**Comment by damencho** [comment]
https://github.com/jitsi/jicofo#secure-domain

**Comment by StreamTitan** [comment]
Thanks!

**Comment by alorson** [comment]
> https://github.com/jitsi/jicofo#secure-domain

Can you explain please 1. In Prosody B) ? 
Shall i dubplicate that file and rename it to new name? Or what exactly does ") Add new virtual host with anonymous login method for guests:" mean?
