### ISSUE TITLE
screensharing installation broken

### ISSUE THREAD

**Issue by fippo** [jitsi/jitsi-meet#254]
Got a report about screensharing extension install broken, pasting from a chat with @yanas:
17:12 < fippo> looks like the screensharing extension installation process is broken on meet.jit.si
17:12 < fippo> something is getting in the way of the click action
17:13 < fippo> "Chrome Web Store installations can only be initated by a user gesture"

The problem is that meet is using an event dispatcher which break the "user gesture" (aka: click on a button) chain somehow. Not sure if that is due to chrome being more strict in recent versions or simply lack of testing after making changes here.

@bgrozev @hristoterezov?

**Comment by paweldomas** [comment]
I believe that this has been fixed in cd19c0e. https://meet.jit.si is running version for 406, so update should fix the issue.

**Comment by paweldomas** [comment]
https://meet.jit.si is now updated. Please let me know if it works for you now.

**Comment by fippo** [comment]
WFM again. Thanks.
