### ISSUE TITLE
No Mute While Playing Youtube Video Share

### ISSUE THREAD

**Issue by kirkjaa** [jitsi/jitsi-meet#2540]
Hello,

Could you please point me to the right direction as far as the codes for no mute when we share youtube video please ? Since our requirement is in musical training and we need to have the voice over when youtube video is playing. Thank you.

**Comment by damencho** [comment]
All the code about sharing youtube video is here:
https://github.com/jitsi/jitsi-meet/blob/master/modules/UI/shared_video/SharedVideo.js

The problem is when the video starts playing on all participant in the conference, and there are some unmuted the audio from the video clip can be heard 3-4-5 times from all participants (as many times as the number of unmuted participants) and this is very annoying and unusable.

**Comment by kirkjaa** [comment]
Hello,

Gotcha and I understand the feed back loops of video will distort audio in
the overall conference. Well noted on the possible issue and thank you so
much,

Regards,

Kirk

**Comment by Sidem** [comment]
Is this issue ever going to be resolved? there is demand for being able to speak while a video is playing.

**Comment by n3rdcoach** [comment]
I have the same question, or better said: i need the option for "no one is muted during youtube-video" too. Any workarounds known?  

Thank you in advance

**Comment by damencho** [comment]
This is intentional as this can lead to unbearable multiplied echo, we had been experimenting with that in the past, and the only usable option is the current one.

**Comment by rodri042** [comment]
Could you add it as a configurable setting? I've used other apps to share videos and it should work OK if all are using headphones

**Comment by gadjodilo83** [comment]
> This is intentional as this can lead to unbearable multiplied echo, we had been experimenting with that in the past, and the only usable option is the current one.

> Could you add it as a configurable setting? I've used other apps to share videos and it should work OK if all are using headphones

i would like that too. we only have meetings with headphones. is there a way to change the mute in the code afterwards? it runs under ubuntu.

unfortunately i can't find any entries in the config files.

thanks
marc

**Comment by eggpi** [comment]
There's one workaround, which may itself be a bug.

0. Make sure you are wearing headphones :)
1. Set a shared video, which mutes all participants.
2. Start talking to make the "Trying to speak? You're muted" popup appear.
3. Click "Unmute" on the popup which, unlike the regular mute/unmute button, unmutes you without muting the video.
4. Avoid any interaction with the video, as that mutes me again.

It is confusing that (say) lowering the volume of a video [causes participants to be muted as a side effect](https://github.com/jitsi/jitsi-meet/blob/06fa175a6ce37bf8aeda2489c52abd91d9357e79/modules/UI/shared_video/SharedVideo.js#L258), or that my intent as a user is second-guessed when I get auto-muted after I've unmuted.

Maybe it would make sense to mute participants when a video is first shared, with a notice for why that happened in a popup, and then not auto-mute if they un-mute themselves?

**Comment by gabriellucius** [comment]
> There's one workaround, which may itself be a bug.
> 
> 1. Make sure you are wearing headphones :)
> 2. Set a shared video, which mutes all participants.
> 3. Start talking to make the "Trying to speak? You're muted" popup appear.
> 4. Click "Unmute" on the popup which, unlike the regular mute/unmute button, unmutes you without muting the video.
> 5. Avoid any interaction with the video, as that mutes people again.
> 
> It is confusing that (say) lowering the volume of a video [causes participants to be muted as a side effect](https://github.com/jitsi/jitsi-meet/blob/06fa175a6ce37bf8aeda2489c52abd91d9357e79/modules/UI/shared_video/SharedVideo.js#L258), or that my intent as a user is second-guessed when I get auto-muted after I've unmuted.
> 
> Maybe it would make sense to mute participants when a video is first shared, with a notice for why that happened in a popup, and then not auto-mute if they un-mute themselves?

Wow, thanks! I need that function too. This "bug" is helping me a lot.

I will really apprecciate this as a feature possible to be enabled

**Comment by kommhoerauf** [comment]
The workaround is ok, but I liked to have a proper solution.

You may checkout the jitsi-meet code and change the code. I have prepared a quick patch for you https://pastebin.com/Gr1Zh3m7 . If you just follow the deploy part of the installation guide https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#deploy-jitsi-meet you should be able to build the necessary libs.

In my case (ubuntu 18.04 - Jitsi-Meet quick-installation) the related libs generated from code where the following

```
/usr/share/jitsi-meet/libs/app.bundle.min.js
/usr/share/jitsi-meet/libs/app.bundle.min.map
```
 
Just be aware when updating you may loose your changes. The patch files for these 2 files where a bit too big to put them here ;)

Now works fine for me!

**Comment by cddf** [comment]
I think it would be nice to have an option to disable the automatic muting.

And I really don't get the problem with it. Of course, the feedback can be an issue with speakers, but there's no physical difference between played Youtube sound and sound of somebody who is speaking.

The point is, the (really nice) feature gets a bit useless without the possibility to speak spontaneously.

And by the way, thank you all for your really nice work. It's rather convenient in Corona times :)

**Comment by rugk** [comment]
I agree that users should at least **be able to disable it**. When they have proper headphones, no audio loop will appear.

**Comment by jvschiavo** [comment]
+1 for that, please. I like to watch videos with my friends and talking over them like we used to do with Rabbit and now this simply is not possible.

**Comment by rugk** [comment]
BTW if anyone is looking for an alternative solution for now, you can also use a service like https://getmetastream.com/ to watch any video together with your friends. It is actually also better, because it e.g. supports any website – not only YouTube.

**Comment by jvschiavo** [comment]
> There's one workaround, which may itself be a bug.
> 
> 1. Make sure you are wearing headphones :)
> 2. Set a shared video, which mutes all participants.
> 3. Start talking to make the "Trying to speak? You're muted" popup appear.
> 4. Click "Unmute" on the popup which, unlike the regular mute/unmute button, unmutes you without muting the video.
> 5. Avoid any interaction with the video, as that mutes people again.
> 
> It is confusing that (say) lowering the volume of a video [causes participants to be muted as a side effect](https://github.com/jitsi/jitsi-meet/blob/06fa175a6ce37bf8aeda2489c52abd91d9357e79/modules/UI/shared_video/SharedVideo.js#L258), or that my intent as a user is second-guessed when I get auto-muted after I've unmuted.
> 
> Maybe it would make sense to mute participants when a video is first shared, with a notice for why that happened in a popup, and then not auto-mute if they un-mute themselves?

I was using this "bug" to workaround this stupid behavior and watch videos and comment with my friends but now this simply isn't working anymore DDDD:

Are you guys able to still use it? @eggpi @gabriellucius 

Also, one more time, please change this behavior so at least we can unmute and stay unmuted! There are already options to mute everyone in the room!! >.<'

**Comment by RenegadeButcher** [comment]
At least provide an option in the config to not mute by default.  It's a bit ridiculous that a 5 year old issue has been closed twice with no resolution when this is clearly a tweak that people want.

**Comment by saghul** [comment]
If it's clearly something people want someone would have sent a patch.

It's a good indicator for how many and how badly people want things.

**Comment by hannescam** [comment]
I would like a config option for this too where I can disable muting on playback

**Comment by rugk** [comment]
Here, apparently a workaround has been posted:
https://github.com/jitsi/jitsi-meet/issues/8720#issuecomment-1533378210
