### ISSUE TITLE
File sharing feature in Jitsi

### ISSUE THREAD

**Issue by emnkhin** [jitsi/jitsi-meet#2541]
We are a group of digital security trainers working with activists, lawyers, investigative journalists and civil society organisations. We love to teach and encourage them to use Jitsi.

One common issue we have with Jitsi when we use it is when we clicked Open/Close shared document and we were expecting to share the documents directly but instead, we were directed to etherpad and had to click another Import/Export button in order to share a document.
We know that it is available to do in the etherpad, but it takes longer time to open etherpad and it is good to have options. 

While we really like the idea of having Etherpad as a collaborative space and want it to be kept, we think that the issue is that the icon and title are misleading. So our suggestion is to have a feature for sharing the files that is visible on the left-hand bar of jitsi meet screen.

<img width="1440" alt="jitsi" src="https://user-images.githubusercontent.com/19723093/36838338-0637109e-1d67-11e8-8987-188d42ba35a5.png">

**Comment by damencho** [comment]
Such feature is not on our roadmap. 
What you can do is find a service or something you can deploy and meets your expectations and configure the etherpad link to use your file service, its just a iframe loading inside jitsi-meet.
I don't see an issue with the etherpad button text. It is for sharing documents, you click and a document is open and collaborative editing is enabled.

**Comment by kirkjaa** [comment]
@damencho could you point me to the documentation for the iframe configuring the etherpad to use others service to be embed instead of the standard etherpad ? Thank you in advance

**Comment by damencho** [comment]
There is no such document and we haven't explored any other service embedding.

**Comment by dipu19** [comment]
Hi,

In my case that open shared document is not showing, i have installed etherpad_lite and also changed in nginx server
and in config.js file also, still i am not getting that option. Can any one guide me to resolve that problem?
