### ISSUE TITLE
User Orientation feature needed

### ISSUE THREAD

**Issue by Yatanar** [jitsi/jitsi-meet#2542]
We are a group of trainers working with activists who need to use messaging tools to communicate among each other safely. We have recommended Jitsi Meet to them; however, we have seen that many of them found the interface confusing as there are no guides or orientation of the tool at the beginning. We suggest to put pop-up guides to orient beginners around the tool and we have included an idea of what can be of use for the users.  

![jitsi-meet](https://user-images.githubusercontent.com/22883085/36839106-3f2c0446-1d6b-11e8-983c-6a6b18fa8938.gif)

**Comment by damencho** [comment]
Hi, thanks for the suggestion, but this feature is not on our roadmap. 
But we will be working on the toolbars design in the following weeks, so we hope to improve the experience there.
