### ISSUE TITLE
install-letsencrypt-cert.sh failed

### ISSUE THREAD

**Issue by mxins** [jitsi/jitsi-meet#2548]
run /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh failed：
Failed authorization procedure. jit.followeye.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://jit.followeye.com/.well-known/acme-challenge/f9oA15ZjloLT69zoi1Wp4MV_8knk7TD_-pFHy3QSiA4: "<html>

why?

**Comment by turret24** [comment]
I got this error too.
Failed authorization procedure. jitsi.pothos.me (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://jitsi.pothos.me/.well-known/acme-challenge/gIKHCVXkzO5kGJWJSBl2awIJ0oq9X5S2AvAJLuGGSYQ

Did you ever solve it? Anyone know what's causing this? I verified that my DNS settings were valid, and the error response doesn't provide any solution recommendations other than that.

Notably, I got this after installing Jitsi on a server where Apache was installed, but I didn't get this error when I installed Jitsi on a server without Apache or Nginx. However, my installations without them (i.e. built-in Jetty) didn't work either. When I visited the domain after installation, I just got a 404.

**Comment by damencho** [comment]
Not sure about the let's encrypt error, maybe let's encrypt cannot open the .well-known file, do you open that successfully? 

But I'm interested why jetty is not working for you? 
What is the URL you visit? Is it http or https, as jetty listens to port 443 only.

**Comment by turret24** [comment]
I tried to go to the ./well-known directory in my shell and was told no such directory exists, so now I'm trying to figure out why that dir and file weren't created.

As for jetty installation, I'm not sure. I followed the quick-install instructions on github, also tried the instructions on the website, and some instructions i found on youtube. None of them worked. And I tried visiting the domain both over http and https each time and got 404 either way.

**Comment by turret24** [comment]
Well now I am finally able to see the working jitsi application on my domain over https. But it's still saying "not secure" because the attempt to create a security cert failed. I'll keep batting away at it and let you know if I solve it.

**Comment by damencho** [comment]
No, not your shell, let's encrypt server will try accessing: http://jitsi.pothos.me/.well-known/acme-challenge/gIKHCVXkzO5kGJWJSBl2awIJ0oq9X5S2AvAJLuGGSYQ, the link from the error.
If you cannot open that in your browser, this means and let's encrypt will not work. 

If you cannot open it, something went wrong with the installation and with the install-letsencrypt-cert.sh script. 
Both the installation and the script try to detect what you have installed on the system and act differently. 
But basically, as jitsi-meet is already configured the install-letsencrypt-cert.sh will use /usr/share/jitsi-meet for the let's encrypt scripts to store the needed files:
```
./certbot-auto certonly --noninteractive \
    --webroot --webroot-path /usr/share/jitsi-meet \
    -d $DOMAIN \
    --agree-tos --email $EMAIL
```
From: https://github.com/jitsi/jitsi-meet/blob/master/resources/install-letsencrypt-cert.sh#L62

**Comment by damencho** [comment]
In the future please use the community forum for posting questions, problems or suggestions: https://community.jitsi.org

**Comment by inpos** [comment]
Add to /etc/nginx/sites-enabled/<domain>.conf in section of ssl following:
```
location /.well-known {
    root /usr/share/jitsi-meet;
}
```
and reload nginx.
Then start letsencrypt script again.
