### ISSUE TITLE
[Android] Integrate jitsi-meet into android application

### ISSUE THREAD

**Issue by vinhntdev** [jitsi/jitsi-meet#2549]
Hello,
I try to integrate jitsi-meet into android application, but it has error like below.

> 03-02 16:39:45.748 4299-4299/com.testj E/AndroidRuntime: FATAL EXCEPTION: main
>                                                          Process: com.testj, PID: 4299
>                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/ReactInstanceManager;
>                                                              at org.jitsi.meet.sdk.JitsiMeetView.initReactInstanceManager(JitsiMeetView.java:106)
>                                                              at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:325)
>                                                              at com.testj.MainActivity.onCreate(MainActivity.java:25)
>                                                              at android.app.Activity.performCreate(Activity.java:6285)
>                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
>                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
>                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
>                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154)
>                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
>                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                              at android.os.Looper.loop(Looper.java:234)
>                                                              at android.app.ActivityThread.main(ActivityThread.java:5526)
>                                                              at java.lang.reflect.Method.invoke(Native Method)
>                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.ReactInstanceManager" on path: DexPathList[[zip file "/data/app/com.testj-2/base.apk"],nativeLibraryDirectories=[/data/app/com.testj-2/lib/arm, /vendor/lib, /system/lib]]
>                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>                                                              at org.jitsi.meet.sdk.JitsiMeetView.initReactInstanceManager(JitsiMeetView.java:106) 
>                                                              at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:325) 
>                                                              at com.testj.MainActivity.onCreate(MainActivity.java:25) 
>                                                              at android.app.Activity.performCreate(Activity.java:6285) 
>                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
>                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
>                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
>                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
>                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
>                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                              at android.os.Looper.loop(Looper.java:234) 
>                                                              at android.app.ActivityThread.main(ActivityThread.java:5526) 
>                                                              at java.lang.reflect.Method.invoke(Native Method) 
>                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
>                                                          	Suppressed: java.lang.ClassNotFoundException: com.facebook.react.ReactInstanceManager
>                                                              at java.lang.Class.classForName(Native Method)
>                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
>                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
>                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
>                                                              		... 16 more
>                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

I will describe what steps I do.
1. I pull code from https://github.com/jitsi/jitsi-meet
2. I setup in Build part, step 1 in https://github.com/jitsi/jitsi-meet/tree/master/android
3. I run ./gradlew :sdk:assembleRelease command and it's ok.
4. I pick sdk-release.aar from jitsi-meet/android/sdk/build/outputs/aar and import it into my new android project, use compile files('libs/sdk-debug.aar')
5. Then I use "JitsiMeetView" in MainActivity and it happen error above.
--- BUT
6. I use implementation "org.jitsi.react:jitsi-meet-sdk:1.9.0" and 
> repositories {
>     maven {
>         url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
>     }
> }

It works.
I want to manual build aar file and import into my project, I don't know what steps I wrong.
I use Analyze APK of Android Studio to compare 2 APK.
One APK by import sdk-release.aar (apk-debug-manual.apk, step 1 to 5) and one from implementation "org.jitsi.react:jitsi-meet-sdk:1.9.0" (apk-debug-maven.apk, step 6)
It seem to missing very library and class. I capture image below.
<img width="1276" alt="screen shot 2018-03-02 at 16 38 53" src="https://user-images.githubusercontent.com/10249799/36893593-3603c8b0-1e3b-11e8-8fa4-3d8a1fe56fe7.png">
All advice is appreciated. Thanks all.

**Comment by nightstryke** [comment]
Jitsi already has an android app you know.

**Comment by vinhntdev** [comment]
@nightstryke 
Yes, but I want to build by myself and integrate into my app. Can I do that?

**Comment by lyubomir** [comment]
You need `transitive` (google the right syntax please) on the `jitsi-meet-sdk` dependencies in order to full all of Jitsi Meet SDK for Android's transitive dependencies including react-native.

**Comment by vinhntdev** [comment]
I build index.bundle file into assets and build success. I close issue. Thanks.

**Comment by niteshanand90** [comment]
@vinhntdev i am getting error in 3rd step

**Comment by hasnainali3** [comment]
@vinhntdev how did you do "build index.bundle file into assets and build success." ? Because i am doing the same thing you did. got the same error. but stuck. If you can Help Please!

**Comment by BlackChy** [comment]
@hasnainali3  How to " build index.bundle file into assets and build success."? I also want to kown.
