### ISSUE TITLE
There is a typo in: lang/main.json

### ISSUE THREAD

**Issue by driesken** [jitsi/jitsi-meet#255]
Seems like there is a type in lang/main/json, but I can't seem to find it.

Here is some chrome console output:

app.bundle.js?v=44:18001 
f.errorapp.bundle.js?v=44:12065 defaultOptions.customLoad.i18n.functions.ajax.errorjquery-2.1.1.min.js:2 n.Callbacks.jjquery-2.1.1.min.js:2 n.Callbacks.k.fireWithjquery-2.1.1.min.js:4 xjquery-2.1.1.min.js:4 n.ajaxTransport.k.cors.a.crossDomain.send.bjquery-2.1.1.min.js:4 n.ajaxTransport.k.cors.a.crossDomain.sendjquery-2.1.1.min.js:4 n.extend.ajaxapp.bundle.js?v=44:12055 defaultOptions.customLoadapp.bundle.js?v=44:17403 (anonymous function)jquery-2.1.1.min.js:2 n.extend.eachapp.bundle.js?v=44:17386 (anonymous function)jquery-2.1.1.min.js:2 n.extend.eachapp.bundle.js?v=44:17385 sync._fetchapp.bundle.js?v=44:17335 sync.loadapp.bundle.js?v=44:18167 initapp.bundle.js?v=44:12124 module.exports.initapp.bundle.js?v=44:40 (anonymous function)jquery-2.1.1.min.js:2 n.Callbacks.jjquery-2.1.1.min.js:2 n.Callbacks.k.fireWithjquery-2.1.1.min.js:2 n.extend.readyjquery-2.1.1.min.js:2 I

**Comment by hristoterezov** [comment]
Fixed in c1c5a305c6c421bb2497f3c1144ad5d56dc8d644
