### ISSUE TITLE
new version, dont working extension

### ISSUE THREAD

**Issue by cirelramos** [jitsi/jitsi-meet#2550]
I had version 1.0.2098-1 0 but when updating to 1.0.2794-1 0 the extension to share desktop stopped working, try installing again the version 1.0.2467-1 0 and the extension works again, check the repository of the chrome extension and there are no changes. What can I do to solve this problem? Thanks for the help you can give me

my changes
 desktopSharingChromeExtId: 'hjcgfecgldpgebeeflnjldogphkilfdo',                                     desktopSharingChromeDisabled: false,

error: 
[modules/RTC/ScreenObtainer.js] <Object.handleExtensionInstallationError>:  Failed to install the extension from https://chrome.google.com/webstore/detail/hjcgfecgldpgebeeflnjldogphkilfdo Could not fetch data from the Chrome Web Store

**Comment by virtuacoplenny** [comment]
What version of chrome are you using?

**Comment by hristoterezov** [comment]
Hi @cirelramos ,

Could you please give us some more details? Are you using the extension for your own deployment or for meet.jit.si? Have you uploaded the extension to the chrome webstore or you are loading it into chrome from source? 

I checked  https://chrome.google.com/webstore/detail/hjcgfecgldpgebeeflnjldogphkilfdo and it appears that this extension doesn't exist.

**Comment by cirelramos** [comment]
hello @hristoterezov, thanks for your answer, I'm using an extension of your own from here download (https://github.com/jitsi/jidesha), loading it in chrome from the source, try extensions are already in the chrome store and neither It works, I'll give you an example of how I do it

`desktopSharingChromeExtId: 'kglhbbefdnlheedjiejgomgmfplipfeb',`

  this is the link
https://chrome.google.com/webstore/detail/jitsi-meetings/kglhbbefdnlheedjiejgomgmfplipfeb


or this way

https://chrome.google.com/webstore/detail/jitsi-desktop-streamer/baoobmjlebjbimmmoaokcicanlelmhan?hl=en

other

https://chrome.google.com/webstore/detail/jitsi-desktop-streamer/gcaffdoemjejpiibinkkfjblmjnpfkoh?hl=en



If you can guide me a bit on how I should write, please

**Comment by damencho** [comment]
Extensions that are already in store are for deployments with different URL than the one you deployed, so it will not work with reusing existing extensions. 
You need to create an extension specific for you deployment by putting your URL of deployment in the manifest file of jidesha (as it is described in jidesha's README). 
Then you need either install it locally (you will be the only one able to use it) or publish it in chrome webstore, so others can install it. When publishing in webstore you need to make sure you enable inline install and verify your site.
