### ISSUE TITLE
Collaborative work while screen sharing

### ISSUE THREAD

**Issue by ElucGeek** [jitsi/jitsi-meet#2551]
Hello, I hope it's OK to add a feature request here. I try to militate to quite proprietary solution for video calls, screen sharing and collaborative work in general. Jitsi meet is the closer of all solution from what we would like but one last feature is missing: possibility to interact during screen sharing, idealy we would like to:
1. Possibility for all people in the conference to click on a shared screen and a marker with the position clicked and the name will appear to everyone.
2. Possibility for all people in the conference to draw on the screen while screen sharing (a very simple draw tool would be enough with a dozen color and maybe pen size).

Is is something already discussed ? Is there interest for such feature from other users ? How are would it be to implement such feature ?

**Comment by damencho** [comment]
This is very easy to add on a jitsi-meet deployment, we had experimented with it but we didn't have time to add a separate button and setting for it.
So basically you go and deploy etherdraw and change the etherpad link config in config.js to point to the etherdraw deployment and you are done.

**Comment by ElucGeek** [comment]
Interesting, I didn't know Etherdraw, it's not even mentioned on Etherpad homepage. Would it work in transparency on top of the screen sharing image ?

**Comment by damencho** [comment]
Nope, it will act as the etherpad, it just switches to that screen. But you can upload an image and draw over it.

**Comment by Thatoo** [comment]
I guess it continues there https://github.com/jitsi/jitsi-meet/issues/8128
