### ISSUE TITLE
IE and Safari plug-ns

### ISSUE THREAD

**Issue by TabeebOsama** [jitsi/jitsi-meet#256]
Hi Emil and everyone,

Thank you for responding to my public comments.  I want to ask about your recommendation for an IE and Safari WEBRTC plug-ns?  I looked at WEBRTC4ALL, WEBRTC-EVERYWHERE and Temasys.  They all need a change to adapter.js.  They all do NOT support screen sharing.  I am not sure they support multi stream that JITSI needs to support.

**Comment by gpolitis** [comment]
I don't think we officially support any of the plugins that you mention.

**Comment by paweldomas** [comment]
Just an update that Temasys plugin does support screen sharing.

**Comment by TabeebOsama** [comment]
Thanks.  Does it work with jitsi meet!  I could not make it work,

Thanks

**Comment by paweldomas** [comment]
We have just added experimental support for Temasys WebRTC plugin. Currently I know that it works with IE11. Should work also with Safari, but that hasn't been well tested yet. You can give it a try at beta.meet.jit.si.

**Comment by paweldomas** [comment]
IE and Safari is now supported through Temasys plugin.

**Comment by thedracle** [comment]
It appears that  screen sharing will only be enabled for your domain by Temasys when you sign up for a monthly service contract.

My organization is small and using Jitsi internally for now, and upon learning this Temasys just outright closed my ticket and ignored me.

Is anyone aware of any IE options that support screen sharing that aren't behind a huge paywall?

**Comment by akuckartz** [comment]
@thedracle Firefox ?

**Comment by neufeind** [comment]
Safari 11 will add WebRTC-support. Might that help solve Safari-issues then once and for all, at least for up-to-date browsers?
