### ISSUE TITLE
[iOS]RNBackgroundTimer.setTimeout error issue when start app

### ISSUE THREAD

**Issue by wong1234566** [jitsi/jitsi-meet#2569]
I found a error when i start jitsi-meet sample app

Please help, 

Argument 1 (<null>) of RNBackgroundTimer.setTimeout could not be processed. Aborting method call.

[https://ibb.co/jeFVF7]https://ibb.co/jeFVF7
[https://ibb.co/nKAxv7]https://ibb.co/nKAxv7

**Comment by reimertz** [comment]
It seems you only have to update your repo so you get this change: https://github.com/jitsi/jitsi-meet/commit/8dc866fab39aaf7cd320d4fd3fcd03454fe344d1.
