### ISSUE TITLE
No JitsiMeetExternalAPI(domain, options) constructor?

### ISSUE THREAD

**Issue by adam-law** [jitsi/jitsi-meet#2577]
I may have been cross-eyed, or blind, but the only constructor available was:
`function JitsiMeetExternalAPI(domain, room_name, width, height, parentNode, configOverwrite, interfaceConfigOverwrite, noSsl) `

Also, it doesn't seem to accept whatever i pass for configOverwrite and interfaceConfigOverwrite.

The main JSON I was using was:
`{"roomName":"XnWSNrR0C4NLUxO2gseYPeaoLO","width":1920,"height":1040,"configOverwrite":{},"interfaceConfigOverwrite":{"TOOLBAR_BUTTONS":["microphone","camera","desktop","chat","filmstrip","sharedvideo","settings","desktop","recording"],"MAIN_TOOLBAR_BUTTONS":["microphone","camera","desktop"]}}`

and my constructor call was:

`var api = new JitsiMeetExternalAPI(domain, options.roomName, options.width, options.height, null, options.configOverwrite, options.interfaceConfigOverwrite, true);`

It turned out this way since I wanted to be sure I wasn't passing malformed JSON

**Comment by virtuacoplenny** [comment]
Are you loading the API from the same url that's in doc/api.md? https://meet.jit.si/external_api.js. I tried using the example in doc/examples/api.html and it worked for me, with the constructor JitsiMeetExternalAPI(domain, options) being supported.

**Comment by adam-law** [comment]
That's a great point-out @virtuacoplenny. No, I used [https://meet.jit.si//libs/external_api.js](url), which I was under the impression was the correct one, as per my issue detailed on a recent merged PR (sorry, I was going to reference it, but I can't find it at the moment XD)

Let me use the "old" one, and see how it goes.

Thanks.

**Comment by adam-law** [comment]
That did the trick, though Idk what to do about the recent PR.
