### ISSUE TITLE
Problem installing Certbot on Jitsi-meet on Ubuntu 17.10

### ISSUE THREAD

**Issue by leehclark3** [jitsi/jitsi-meet#2578]
Please stop closing my issues before the problem is solved. This is the second time it was done. My DNS is set up correctly and I tried your script.

Update: I installed Ubuntu 16.04 then Apache then Jitsi-Meet according to the tutorial posted recently.

Then when I try to install Certbot it won't verify domain. I just use A records with the static IP for my DNS configuration. Can someone tell me how to serve secure Jitsi-meet video from my little home setup? 

Obtaining a new certificate
Performing the following challenges:
http-01 challenge for recoverylive.webcam
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. recoverylive.webcam (http-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No valid IP addresses found for recoverylive.webcam

IMPORTANT NOTES:

The following errors were reported by the server:

Domain: recoverylive.webcam
Type: unknownHost
Detail: No valid IP addresses found for recoverylive.webcam

To fix these errors, please make sure that your domain name was
entered correctly and the DNS A/AAAA record(s) for that domain
contain(s) the right IP address.

Your account credentials have been saved in your Certbot
configuration directory at /etc/letsencrypt. You should make a
secure backup of this folder now. This configuration directory will
also contain certificates and private keys obtained by Certbot so
making regular backups of this folder is ideal.16.04/Apache2 #2531, same problem.

--

**Comment by damencho** [comment]
Your problem is clearly written in the error. It is up to you to fix it. 

> recoverylive.webcam (http-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No valid IP addresses found for recoverylive.webcam

If I'm wrong, find a better opinion.

**Comment by leehclark3** [comment]
Well, can you help me solve the problem? What do I need to do to fix it?

**Comment by damencho** [comment]
You need to learn what is your network topology. What is your public address and who is managing it. If you are trying to do that at home, is there a router provided by your internet provider that is having the public address, if this is the case you can see your public address by visiting the site http://whatismyip.com/. Then you need to use that address for your A record and configure your router to forward port tcp 443 and udp port 10000 to your internal address.
For more info you can read: 
https://en.wikipedia.org/wiki/Private_network
https://en.wikipedia.org/wiki/IP_address
https://en.wikipedia.org/wiki/Network_address_translation

**Comment by leehclark3** [comment]
Ran:

sudo certbot --apache

Same error:

   Domain: recoverylive.webcam
   Type:   unknownHost
   Detail: No valid IP addresses found for recoverylive.webcam

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

**Comment by leehclark3** [comment]
OK, I forwarded udp port 10000 to my server. I did not know I had to do
that, Public IP has been set in router. It's a static IP.

**Comment by damencho** [comment]
It is not only udp 10000, you also need to forward and tcp 443. And dns changes can take up to 24 hours to update, you may have your dns cached on the letsencrypt serverside, as your DNS now looks good ...

**Comment by leehclark3** [comment]
i had port 443 forwardwarded already

**Comment by leehclark3** [comment]
I can't get into one of my Ubuntu machines. Suddenly the automatic login is
gone and the password has changed.

**Comment by leehclark3** [comment]
I got a public IP (duh) and did a successful install. Ubuntu 17.10 with
Jitsi-meet and ran the ssl script successfully. However, when people come
into the room the connection is very poor and slow, even when they have
massive bandwidth on their end. Should I try an install with a web server
like apache? Any idea what my problem might be now?

https://recoverymeetings.online/

**Comment by damencho** [comment]
Does your server has enough bandwidth? The web server just serves the web and there is not much traffic going to it, so changing web servers will not make any difference. 
The media goes from the client to jvb and from jvb to the client. You need to check your server bandwidth.
For 3 people conference, you need something like 15-20 Mbit download on the server and upload 20-25 and this is with simulcast(chrome) and depends on resolution. Without simulcast(firefox) upload will be 30-40. These are very rough estimates, but just to know approximately for what bandwidth we talk.
https://jitsi.org/jitsi-videobridge-performance-evaluation/

**Comment by leehclark3** [comment]
OK. I'm doing it out of my home and we have 50 Mbps down and 5 Mbps up. So
obviously this is the limitation. Thank you for your answer. That was
helpful.
