### ISSUE TITLE
Delegate Method when receiver disconnects the call

### ISSUE THREAD

**Issue by ArtiMane** [jitsi/jitsi-meet#2584]
Hi ,

I have question as when receiver disconnects the jitsi meet video call , which delegate method is called ? And how we will get the event about user is busy with another video call ?

**Comment by damencho** [comment]
On your first question, the iframeAPI has a listener and you can listen for videoConferenceLeft. https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

About the second one, this is out of the scope of jitsi-meet app, but you can implement those.

To implement busy you will need few things:
1. Passing jwt tokens with some user identity in it, so you can identify users.
2. Create a prosody module that can handle events inside prosody to report to some service you need to implement. 
-- left
module:hook("muc-occupant-left", handleOccupantLeft, 10);
-- joined
module:hook("muc-occupant-joined", handleOccupantJoined, 10);
-- update in the presence
module:hook("muc-broadcast-presence", handleBroadcastPresence, 10);
This module will report to your service join and leave events for a particular user, those users inside prosody have a session and holding token data, so you can identify your users.
3. Implement a service you will be hitting for storing the state and querying the state (busy or not). 
If you are using just a single prosody instance you can easily use the prosody http module and implement that service inside prosody. There are few examples for stuff like that in https://github.com/jitsi/jitsi-meet/tree/master/resources/prosody-plugins

This is one way you can address the busy feature.

**Comment by ArtiMane** [comment]
OK..thanks..But how to implement this api's in ios and android ?

**Comment by ArtiMane** [comment]
Another issue I found after intergrating jitsi meet video call is I got dialing screen of iPhone after call disconnects and I found the Jitsi meet call record in call log in my iPhone .

**Comment by damencho** [comment]
I haven't understood from your description that this is for mobile. But the things I had pointed above are still valid. 
There is no call flow implementation on the server side. So it is up to the app that embeds the mobile SDK to implement it.
About the callkit integration and the thing you describe, someone from @jitsi/mobile can give you more details.

**Comment by ArtiMane** [comment]
This page is not working  jitsi/mobile..

**Comment by ArtiMane** [comment]
If receiver left the conference then which delegate method is called?
