### ISSUE TITLE
Do not have option to screen share on current deployment

### ISSUE THREAD

**Issue by speedy739** [jitsi/jitsi-meet#2588]
Do not have option to screen share on current deployment of jitsi-meet

**Comment by bgrozev** [comment]
Please provide more details

**Comment by speedy739** [comment]
when i create a meeting i do not have option to share my screen please see screen shot attached. 
![no opt to share screen](https://user-images.githubusercontent.com/36172368/37209937-e612cace-2374-11e8-8a6f-fe463ab1f930.PNG)

**Comment by damencho** [comment]
I suppose this is chrome? Did you configure it? You need to create and upload an a extension in chrome webstore. Take a look at github.com/jitsi/jidesha.

**Comment by speedy739** [comment]
Yes its chrome. i will take a look at that and lets you know the results.
