### ISSUE TITLE
Disable re-direct to download app page when viewed on mobile device

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#2595]
Currently when Jitsi-Meet is viewed on a mobile device it re-directs to the download app page.

If you do not have the apps done, this is pointless.

What do we need to change in order to disable this re-direct and have the default index page show instead of the re-direct?

**Comment by StreamTitan** [comment]
Can someone please respond to this?

Currently the "download app"goes to the Jitsi app, which has no connection to our site. This means there is no use for this unless it points to your site's app.

Since we do not have an app for the site as yet, this mobile view re-direct page is not needed.

This is a common issue anyone setting up Jitsi-Meet would face IF they do not have an app.

**Comment by saghul** [comment]
FWIW, the app works with any Jitsi Meet deployment, not just with meet.jit.si, you don't need a separate app.
