### ISSUE TITLE
[RN] How to set status default for turn on/off audio/video

### ISSUE THREAD

**Issue by hvlong** [jitsi/jitsi-meet#2599]
I followed source when press button turn on/off video.
I use function:
dispatch(
                setVideoMuted(
                    true,
                    VIDEO_MUTISM_AUTHORITY.USER,
                    /* ensureTrack */ true
                )
            );
call action to set default video is mute.
But I get error message:
'Local track for video already exists'.

![image](https://user-images.githubusercontent.com/12244203/37320207-3318ce58-26a5-11e8-92f3-3b5c1a0ab3f2.png)

I need set default status mute video/audio for synchronize with my server.

Please help me

**Comment by paweldomas** [comment]
Hi !

Try using these 2 config options and let me know how it works for you:

https://github.com/jitsi/jitsi-meet/blob/master/config.js#L88
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L123

You need to modify your deployment's config.js file to include those 2 properties and adjust to false/true accordingly.

**Comment by paweldomas** [comment]
If you want to adjust that on per user basis then you can append this to the room URL like this:
https://server.com/conference1#config.startWithAudioMuted=true&config.startWithVideoMuted=false

Let me know if you need to do that from the code, but the URL should suffice.

**Comment by hvlong** [comment]
Thank you so much, 
Because follow logic of my app, I need pass default status to turn on/off from source native(android and iOS), value is dynamic,
So I found where is easy to set default status for mute audio/video.
In features/base/media/middleware.js 
and inside method: function _setRoom({ dispatch, getState }, next, action),
I set default for variable 'audioMuted' with value default that get from state.

**Comment by hvlong** [comment]
@paweldomas I found the way to fix it,
Thank for your support,
I will close the issue.
