### ISSUE TITLE
Error when setup Jibri on EC2 modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.4.0-1052-aws

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#2600]
I implemented Jibri install on EC2 server, however I encountered this error when installing.
```
~# modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.4.0-1052-aws

```
Previously I installed linux-image-extra-virtual. Please tell me how to solve it. Thank you very much.

**Comment by aaronkvanmeerten** [comment]
The AWS default kernel doesn't come with the snd-aloop module, nor does it come with extras.  You will need to switch back to one of the linux kernel flavors which DOES come with aloop support.  I suggest the "linux-image-virtual" package.
