### ISSUE TITLE
Can't change Page Titile

### ISSUE THREAD

**Issue by leehclark3** [jitsi/jitsi-meet#2614]
I thoroughly edited /usr/share/jitsi-meet/title.html but the page title of my rooms is still "Jitsi Meet"

Am I missing something? Good news is I got my server up and running.

**Comment by gurumark** [comment]
I have the same issue.

**Comment by minkyul** [comment]
Change the following two variables in /usr/share/jitsi-meet/interface_config.js: DEFAULT_REMOTE_DISPLAY_NAME and APP_NAME variables.

**Comment by saghul** [comment]
APP_NAME is the only one which is required indeed.

**Comment by rasos** [comment]
Changing APP_NAME variable does not work for me, the tab name in browser and title is still "Jitsi Meet", also after restart of services.

**Comment by Chakib-Temal** [comment]
you should clean you cash browser after your configuration

**Comment by radityateddy** [comment]
> None of the solution in here work for me. I successfully changed the title in the google chrome tab, but I can't change the main headline in the middle of the jitsi meet welcome page.
> 
> It still says
> 
> **JITSI MEET** Secure and high quality meetings
> 
> I can't change these two lines, I edited every file in langs folder and cleared cache but still nothing changes.

there is any update about this issue ? i still facing this matters to in my environment

**Comment by rasos** [comment]
The English version of all text is not taken from the langs folder, but are in the jitsi-web app static, for performance reasons. You would build your own image.  Other languages are loaded dynamically.
