### ISSUE TITLE
No video and audio

### ISSUE THREAD

**Issue by nguyenvannon** [jitsi/jitsi-meet#2615]
Dear sir / madam.

I installed Jitsi Meet on my own VPS. I am wondering why this is not working on my server.
URL: https://vps.nguyenvannon.info/

Extra Informations about VPS:
- OS: Ubuntu 16.04
- Java version: 1.8.0_161. Java(TM) SE Runtime Environment (build 1.8.0_161-b12). Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- Javac version: 1.8.0_161

I use these following command to install Jitsi:

- wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
- sudo sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"
- sudo apt-get -y update
- sudo apt-get install apt-transport-https
- sudo apt-get -y update
- sudo apt-get -y install jitsi-meet

Installing Cerbot: https://certbot.eff.org/#ubuntutrusty-apache
Thank you.
![issue](https://user-images.githubusercontent.com/37391219/37442397-b4f13976-2838-11e8-9d67-afab2626a02b.png)

**Comment by nguyenvannon** [comment]
Solved

**Comment by triawan90** [comment]
Hi, could you share how to solved? thanks

**Comment by nguyenvannon** [comment]
Hi @triawan90 
Thank your for reading my issue.

First, during the installation of Jitsi, you will see a request to enter the hostname. Do not leave it blank, enter your IP address or domain and continue.

Eventually due to VPS resource limitations, upgrading the same VPS package is a solution.

Good luck!
