### ISSUE TITLE
Errors while integrating the jitsi meet android sdk 

### ISSUE THREAD

**Issue by jean-ben-guigui** [jitsi/jitsi-meet#2616]
Hello,

I am currently building a React-native application and I want to integrate Jitsi as a new activity.
So I decided to use the jitsi meet sdk. I started by integrating the the android sdk (I used the iOS sdk in another app without problem before).

I have tried the following steps:

 - I bind a native module on my app to create an intent that will navigate to a `JitsiActivity`. Here are my .java files.
[Archive.zip](https://github.com/jitsi/jitsi-meet/files/1816141/Archive.zip)
and my Component that contains the button
[LoginScreen.js.zip](https://github.com/jitsi/jitsi-meet/files/1816180/LoginScreen.js.zip)

 - Add the **Maven repository** https://github.com/jitsi/jitsi-maven-repository/raw/master/releases and the dependency org.jitsi.react:jitsi-meet-sdk:1.9.0 into my build.gradle.
==> When I run react-native run-android, my app launch correctly. Then when I try to open the JitsiActivity, I get an error in logCat that method `setJSMainModuleName` does not exist 
[error1.txt](https://github.com/jitsi/jitsi-meet/files/1816128/error1.txt)
Seems to be the same problem as https://github.com/jitsi/jitsi-meet/issues/2411 and https://github.com/jitsi/jitsi-meet/issues/2314

- I realised that the **maven repo is not up to date** (last commit was 6 months ago)
![screen shot 2018-03-15 at 17 42 39](https://user-images.githubusercontent.com/15104156/37477591-56fae002-2878-11e8-9cc1-266a962c48b1.png)
 and that the problem is solved with the new jitsi app. So I decided to build the sdk with the last version of JitsiMeet.
Then I forked your repo and I added my brand new `jitsi-meet-sdk-1.9.0.aar` to my repo https://github.com/jean-ben-guigui/jitsi-maven-repository.

- I changed the dependency in my build.gradle and ran `react-native run-android`.
==> I then have the following error
[error2.txt](https://github.com/jitsi/jitsi-meet/files/1816165/error2.txt)
![screen shot 2018-03-16 at 15 42 01](https://user-images.githubusercontent.com/15104156/37526970-211bb5d8-2931-11e8-9422-366a667e647c.png)

I feel like I have not built the sdk correctly. Any help with that last error would be highly appreciated. If not, an update of the [maven repo](https://github.com/jitsi/jitsi-maven-repository/raw/master/releases) with latest source of Jitsi Meet SDK for Android would be amazing.

- **First Update:**
I have built a basic native android app with two activities : One main activity and one that extends JitsiMeetActivity. It works.
So there is no problem with the jitsi-meet-sdk I built. The problem seems to came from the fact that AppRegistry.registerComponent is called two times: One in my app and one in the Jitsi sdk. Is there an easy way out of this?

**Comment by fretman92** [comment]
https://github.com/jitsi/jitsi-meet/issues/1703 seems to have the same goal but some details are missing

**Comment by pranav-pandey** [comment]
Any luck in integrating the sdk with an empty react native project?  

Tried to follow this for android: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md

Fails at step 2, `Project 'sdk' not found in root project 'JitsiClone'`

This looks like the way to go forward as it gives complete control - https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md#installation

Still not sure, any help would be welcome.

**Comment by themakerman** [comment]
Why is this not yet solved? We really need some docs for integrating jitsi in our react native project....

**Comment by amirasaran** [comment]
@themakerman do you find any way ?

**Comment by antch57** [comment]
having the same problem here....any updates?
