### ISSUE TITLE
JItsi-Meet : Can't implement text chatting with react-native

### ISSUE THREAD

**Issue by vink1987** [jitsi/jitsi-meet#2620]
I have been trying to enable the text chat functionality in my react-native source code but I am not seeing this option anywhere. Can you please find me out on this?

**Comment by paweldomas** [comment]
This feature is not there yet, so there's no option available.

**Comment by vink1987** [comment]
@paweldomas Ahh my bad. Let's close this ticket. Thanks for the help

**Comment by vink1987** [comment]
@paweldomas Just want to know if the dev team is planning to implement this feature in future

**Comment by paweldomas** [comment]
I haven't seen that to have any priority. There are many other more important things to fix/implement as of now.

**Comment by vink1987** [comment]
@paweldomas actually I am going to implement an app which will provide Audio/Video/Text chat. Was expecting the text chat as this is a very common thing to have. Anyways thanks a lot for your support :)

**Comment by viveka3logics** [comment]
@paweldomas I understand that this feature is not in your priority list .. but is there any way that we can implement text chat simmilar like web ? ... it will be great if you can give any idea ? thanks.
