### ISSUE TITLE
how to change the hostname configured with a first installation ?

### ISSUE THREAD

**Issue by DigitalCoder** [jitsi/jitsi-meet#2625]
Good evening,

how to change the hostname configured with a first installation?

I tried a complete uninstall with the command:
apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-web jicofo jitsi-videobridge

however during the new installation I am not asked which hostname to choose.

The goal is to run Jitsi-meet on a subdomain with a reverse-proxy.

Knowing that my main site (symfony 3) is configured under Apache and Jiti-Meet under nginx

I am on a VPS OVH Ubuntu 16.04 Server.

In addition to each uninstallation I am obliged to delete the lines concerning "jitsi-meet-web-config" which returns the following error:
« Errors were encountered while processing:
jitsi-meet-web-config
E: Sub-process /usr/bin/dpkg returned an error code (1) »

I delete the lines with the command:
sudo nano /var/lib/dpkg/status

I looked in all forums and tickets https://github.com/jitsi/jitsi-meet/issues/
I can not find solutions.

**Comment by turint** [comment]
You can use 'debconf-get-selections' (it's not there by default, you need the debconf-utils package) to check what values are there left and 'debconf-set-selections' to set them to null strings.
You can also use 'debconf-communicate' to clear them all, for example 'echo PURGE | debconf-communicate jitsi-videobridge'.
I wouldn't advise to mess with the status file, though, unless you really know what you are doing.
