### ISSUE TITLE
Minimize app.bundle.js

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#263]
app.bundle.js has now grown to 900KB and should probably be minimized.

**Comment by gpolitis** [comment]
[Grunt](http://gruntjs.com/) could solve this problem easily (and do much more, it's like ant for Java, only better).

**Comment by gpolitis** [comment]
Just to clarify my previous comment, when I say it can do much more I mean that it can handle minification, browserify, jshint/csslint/jscs/... and friends.

It's pretty straightforward to setup too. We add it as a devDependency in the package.json and then we describe in GruntFile.js what we want it to do. We can get "inspired" by a nice and clean example [here](https://github.com/webrtc/samples).

**Comment by fippo** [comment]
you can achieve the same with npm. A side-note about travis: precommit-hook is way better at catching linter errors. Which was the reason I required it more than a year ago.

**Comment by bgrozev** [comment]
Currently app.bundle.js is 1.24MB and 0.46MB minified with http://javascript-minifier.com/
