### ISSUE TITLE
Do I need to install my own Jitsi Meet server to use Jitsi Meet API ?

### ISSUE THREAD

**Issue by DigitalCoder** [jitsi/jitsi-meet#2630]
HI All !
Do I need to install my own Jitsi Meet server to use Jitsi Meet API ?
I've implemented in my website a page using the API.
In local it works but in production the interface integrated in the generated iframe do not ask the user To allow webcam, any prompt :(
So to prevent this I'm wondering or I install my own Jitsi Meet serveur
So I will have the API installed in my server and configured with my server's info settings
Or will it works just by installing only the lib Jitsi  Meet ? And my users will be prompt to allow webcam ?
Thanks for advance !

**Comment by damencho** [comment]
You can use meet.jit.si deployment and use the iframe API from there or of course, you can deploy your own jitsi-meet and use it, it is a personal preference. 
Not sure why it doesn't asks for permissions, it should.

**Comment by DigitalCoder** [comment]
I'ave already done it but 
when I load it in my website, I do not have the prompt message to allow webcam use

if I cut and past the url loaded in the iframe generated in a new window the prompt message appears

I think it's a licensing problem. the API does not allow access from an external site.
which is good my problem i thought this API will avoid me to install my own server.
Jisti-meet server for which I still have problems installing on my server Ubuntu 16.04 Server

the goal is to load dynamic video-conference area from an existing site.

Thx

**Comment by damencho** [comment]
There is no licensing. Are you using http or https when accessing the API? webrtc does not work when using http.

**Comment by DigitalCoder** [comment]
all right !
I'm going to check !

Thx a lot !

**Comment by boystruss** [comment]
I'm having this same issue
