### ISSUE TITLE
getting 502 bad gateway.

### ISSUE THREAD

**Issue by orbstick** [jitsi/jitsi-meet#2635]
hello every one,
i am working on jitsi api for custom gui, after passing token rs256 jwt i am getting error. for your reference i attached screen shot.

your quick response highly appriciated.
Have a good day,
![jitsi err](https://user-images.githubusercontent.com/35483897/37707355-ac239e1a-2d24-11e8-9f37-1543d0e63fa5.PNG)

**Comment by damencho** [comment]
Can you try openning the bosh address(https://meeting.o....com/http-bind), you should see result same as when you open https://meet.jit.si/http-bind
Is the result on your deployment, the same as on meet.jit.si?
