### ISSUE TITLE
interfaceConfig is not defined

### ISSUE THREAD

**Issue by chandrantwins** [jitsi/jitsi-meet#2639]
Hi Friends,

I have installed jitsi-meet in my AWS server. But i got following javascript error message while loading index page. Have you come accross such issue

Please check javascript error too

Uncaught ReferenceError: interfaceConfig is not defined
    at Object.<anonymous> (languageDetector.web.js:23)
    at t (bootstrap 757d94b864647e2a7da7:19)

**Comment by damencho** [comment]
Are you using nginx, apache or just jvb's jetty is serving jitsi-meet. Apparently, server-side includes are not turned on or not working and your configurations are not loaded, you can see this in the source of your wabpage when you open it in the browser.
You can see for example `<script><!--#include virtual="/interface_config.js" --></script>`

**Comment by chandrantwins** [comment]
Hi damencho thanks for your comment. i am using nginx.  what i have to replace this code to make it work

**Comment by damencho** [comment]
You need to enable ssi.
http://nginx.org/en/docs/http/ngx_http_ssi_module.html
Using default nginx that comes in ubuntu/debian repos have everything that we need and ssi is turned on as said in the documentation link, so it should work. 
What version of nginx are you using and did you install it from the official ubuntu/debian repos?
Mine is `nginx                                 1.10.3-0ubuntu0.16.04.2`

**Comment by chandrantwins** [comment]
Hi damecho thanks i have changed url now its loading index page.. after when i click go button its not loading next page.. is that related to this ssi configuration

mine nginx version and ubuntu version are same

**Comment by damencho** [comment]
I don't think ssi is fixed. I still see the virtual includes and there is no config, so it will not work.

**Comment by cmeng-git** [comment]
I too face the same problem. Installing jitsi-meet via source build based on jitsi-meet-jitsi-meet_3389.zip
I am running jitsi-meet on Ubuntu 18.04 with apache2 v2.4.29.
Per the apache2 document on: https://httpd.apache.org/docs/2.4/howto/ssi.html

I have the following setting for jitsi-meet.conf
<Directory /usr/share/jitsi-meet>
    Options FollowSymLinks
    Options +Includes
    XBitHack on
    DirectoryIndex index.html
</Directory>

Beside enable the ssi module, you also need to perform
chmod +x index.html

**Comment by cantoute** [comment]
I had a similar issue and it had to do with missing ssi as mentioned in previous messages but I had a other twist.  I had done quick install but seemed that was missing a symlink from webroot to /etc/jistsi

`ln -s /etc/jitsi/meet/chat.example.com-config.js /usr/share/jitsi-meet/` (of course adapting example.com to your case)

**Comment by kyronjoves** [comment]
> I too face the same problem. Installing jitsi-meet via source build based on jitsi-meet-jitsi-meet_3389.zip
> I am running jitsi-meet on Ubuntu 18.04 with apache2 v2.4.29.
> Per the apache2 document on: https://httpd.apache.org/docs/2.4/howto/ssi.html
> 
> I have the following setting for jitsi-meet.conf
> <Directory /usr/share/jitsi-meet>
> Options FollowSymLinks
> Options +Includes
> XBitHack on
> DirectoryIndex index.html
> </Directory>
> 
> Beside enable the ssi module, you also need to perform
> chmod +x index.html
> 
> With the above changes, I am able to start jitsi-meet on chrome v 70.
> On Mozilla v63, it fixed the include problem. However it throws other errors i.e.
> 
> ```
> (TIME) index.html loaded:	 80 jitsimeet:12:9
> [modules/browser/BrowserCapabilities.js] <t>:  This appears to be firefox, ver: 63.0 Logger.js:124:12
> Request to access cookie or storage on “https://atalk.sytes.net/jitsimeet/” was blocked because we are blocking all storage access requests. Settings.js:124:8
> [modules/settings/Settings.js] <r>:  DOMException: "The operation is insecure." Logger.js:124:12
> [modules/settings/Settings.js] <get callStatsUserName>:  generated callstats uid Magali-g6b Logger.js:124:12
> Request to access cookie or storage on “https://atalk.sytes.net/jitsimeet/” was blocked because we are blocking all storage access requests. localStorage.js:8
> ReferenceError: interfaceConfig is not defined[Learn More] languageDetector.web.js:23
> ```
> 
> Note: I have to relaunch mozilla browser, then it works.

Not sure where to look for the jitsi-meet.conf. Can you help me with this one so I can change the settings?

**Comment by athenadever** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/3e0bf8ad-ae98-4729-87e8-cdbf14a76733)
@damencho Hi, How are you?
I uploaded image for my index.html file. 
Should I remove virtual like this?

`<script src="/config.js" ></script>
    
    <script src="/interface_config.js" ></script>`
    
    Please reply me.
    Thanks

**Comment by damencho** [comment]
Why? You should turn on server side includes in your webserver.

**Comment by athenadever** [comment]
I don't understand what I have to do. I'm beginner for jitsi.
Could you please explain in details?

**Comment by athenadever** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/76e3b316-4608-4b63-9e67-088a802660e1)
I can see black page and this error

**Comment by damencho** [comment]
What is the webserver that you use?

Also, avoid writing in closed tickets in the future. And before opening new issues use the community forum for questions.

**Comment by athenadever** [comment]
Ok, got it.
I just fixed above issue, and got another issue. I posted on jitsi community.
https://community.jitsi.org/t/how-to-make-calling-feature-on-my-another-site/132380

**Comment by mik658** [comment]
> Hi Friends,
> 
> I have installed jitsi-meet in my AWS server. But i got following javascript error message while loading index page. Have you come accross such issue
> 
> Please check javascript error too
> 
> Uncaught ReferenceError: interfaceConfig is not defined at Object. (languageDetector.web.js:23) at t (bootstrap 757d94b864647e2a7da7:19)

I had similar issue.
