### ISSUE TITLE
No-camera icon dissapears

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#264]
The icon on the thumbnail video indicating video is turned off disappears after a confrence is re-created. To reproduce: open with two tabs, stop video on tab1, refresh tab2. Tab2 now does not see the icon.

**Comment by hristoterezov** [comment]
Have you tried 520e6551003b50ea65ae3d23bd93c019ce628067. I think this commit fixes the issue.

**Comment by bgrozev** [comment]
Indeed it works on beta (I only tried on meet.jit.si before). Thanks, Hristo!
