### ISSUE TITLE
Network Nat problem

### ISSUE THREAD

**Issue by michaelchen001** [jitsi/jitsi-meet#2645]
Hi, I follow quick install instructions , except add local/public ip address to etc/jitsi/videobridge/sip-communicator.properties , But the clients working fine in LAN , and people in internet has no audio/video .

Then  I add below to etc/jitsi/videobridge/sip-communicator.properties ,
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address> 
Then first people can open the meetingroom ,but when the 2nd people join the meeting , both clients will "Unfortunately, something went wrong ........"

if I change config with 
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Local.IP.Address>
Then the clients in LAN working  fine , and people in internet has no audio/video.
I also tried to change org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS to other address, all of them will "Unfortunately, something went wrong ........"

So can you help me to solve it .

**Comment by michaelchen001** [comment]
From chrome console , I can see
[conference.js] <e.value>:  CONFERENCE FAILED: conference.videobridgeNotAvailable
But  I run  /etc/init.d/jitsi-videobridge status  ,  I can see it's active(running).

**Comment by damencho** [comment]
Video bridge not available means that video bridge is not successfully registered to the xmpp server. Can you check jvb logs for errors on startup?

And the property:
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Local.IP.Address>
should set the public address of the videobridge not the local. You also need to forward tcp 443(or 4443 depends whether you have webserver or jvb is serving meet) and udp 10000 to the jvb machine.

**Comment by michaelchen001** [comment]
@damencho  I have checked the ports evan reinstall OS&software, and I still can't solve it. can you try the address ,Thank you .
http://vctest.saedgn.com.cn

**Comment by keantoken** [comment]
I'm having this same problem. What exactly needs to be entered into these two configuration lines? Does it need to be the public IP and router IP? Both the public IP? Both the localhost? This is really confusing.

I get video as long as there are only 2 people. If a 3rd person joins, everyone loses video. If the 3rd person leaves, video suddenly starts again!

**Comment by bgrozev** [comment]
> I'm having this same problem. What exactly needs to be entered into these two configuration lines? Does it need to be the public IP and router IP? Both the public IP? Both the localhost? This is really confusing.

The "public" property should contain the public IP (the IP that users on the internet can use to access the machine). The "local" property should contain the IP address of a local interface. Sorry if this is confusing, I don't know how to phrase it clearer.

Note that your router will need to be configured to forward the necessary ports.

> 
> I get video as long as there are only 2 people. If a 3rd person joins, everyone loses video. If the 3rd person leaves, video suddenly starts again!

Sounds like the connection to jitsi-videobridge fails (when there are two participants, they bypass jitsi-videobridge and connect directly), which might be because of missing or wrong values for the properties mentioned above.

**Comment by keantoken** [comment]
By local interface do you mean the router's IP address on the local network or the IP address of the computer running the videobridge?

**Comment by bgrozev** [comment]
> By local interface do you mean the router/NAT's IP address on the local network or the IP address of the computer running the videobridge?

The IP address on the computer running jitsi-videobridge.

> Should either of these include the port used if local port 443 is forwarded to a different public port number?

No, but in this case you probably need this property:
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md#orgjitsivideobridgetcp_harvester_mapped_port

**Comment by keantoken** [comment]
I was using it without that option and it worked for 2 people, after I added it and restarted videobridge/jicofo nothing has changed. The same problem occurs whether the users are within the LAN or on the outside.

Previously I added the port number to the bosh line in /etc/jitsi/meet/<public.IP.address>-config.js

Do I need to revert this now that I have the mapped port property set?

**Comment by keantoken** [comment]
I have tried reverting the bosh line but then the client keeps trying to access https://<public.IP>/http-bind?room=test3 when it needs to be accessing https://<public.IP>:9965/http-bind?room=test3

**Comment by keantoken** [comment]
Does turnserver need to be installed in order for these config lines to be useful?

**Comment by Annihil8ted** [comment]
For what it's worth, I didn't add anything to the sip-communicator.properties. I only modified the nginx to change 443 to 5000 and the same changes to config.js for BOSH. Everything seems to be working fine and I can host multiple people without error. The issue I'm having is further integration with etherpad.

**Comment by Annihil8ted** [comment]
You could try refreshing all the services a couple of times. nginx, jitsi-videobridge, jicofo, and prosody.

**Comment by michaelchen001** [comment]
It''s my fault , The IP address should not be contain in "<>";  just 4 number and 3 point behind "=" , and the problem solved . 
And at last , the quick install guide is right.
