### ISSUE TITLE
Client side recording? [Looking for advice]

### ISSUE THREAD

**Issue by ztl8702** [jitsi/jitsi-meet#2648]
## Background & motivation

I have a use case that is driving me to implement client-side recording on Jitsi Meet (both Web and Mobile clients). The scenario is like this:

- I am working on a podcast with someone remotely. The way we currently do it is to call on Skype (or Jitsi). 
- Each one of us will have recording software (Audacity and Voicemeter) on our computer to record just the microphone audio on each side.
- After the audio call, we collect the recorded files from both sides and merge them into a single audio track.

The reason we do this instead of recording both participants on the same computer is to ensure audio quality so that in the final product we can have high-fidelity audio, and without any jitter. In other words, we want every sound bit recorded to come directly from the microphones, rather than transmitted over the Internet.

Now this works to some extent, but it is cumbersome. Especially when we want to invite guests to our show, we cannot require them to have the same local-recording setup as we do.

## Solution: a rough idea

The idea is to have this distributed recording mechanism __built into__ the audio conference software itself.  I initially thought about implementing this from grounds up using WebRTC, but it was too difficult. Jitsi Meet, being opensource and builds on top of WebRTC, seems an ideal platform to implement this feature on top of.

So to put the requirements into context:

1. Jitsi Meet clients (or my modified version) need to be able to record the audio stream from the audio device **simultaneously** as the audio is streaming over the network.
1. There needs to be some signalling & synchronisation mechanism that can endure network partition. 
    - One of the participant (owner of the call) will signal the start of the recording, and every participant's device will start recording individually. Same with stopping the recording.
    - The audio call might be interrupted or reconnecting but the local recording should carry on normally. (Timestamp-based signalling might be most easy to implement.)

How to collect the audio recording from each participant's device and merge them would be out of the scope of this issue. (Let's assume that offline processing part is already implemented.)

After some initial research, I have found that:
- For Jitsi Meet web client: I was able to call `getUserMedia()` and created a `MediaRecorder` in the browser console simultaneously as a Jisit Meet conference was going on. The `MediaRecorder` worked as expected and did manage to record and save high-quality audio from the microphone. It did not seem to affect the Jisit call.

- For Android / iOS, it depends. For example, it appears that multiple native Android `MediaRecorder` instances will have [unexpected behaviour](https://stackoverflow.com/questions/32929936/android-crash-when-using-2-mediarecorder-instances). But I am suspect it is possible to reuse the same native `MediaRecorder` for both WebRTC streaming and recording at the same time. I might need to look into https://github.com/oney/react-native-webrtc to figure this out.

------

I currently plan to implement this as a separate application based on Jitsi Meet. I am not aware of any existing feature like this in Jitsi or similar applications. Do you think this use case is common enough that should be incorporated into Jitsi Meet?

I would like to hear any thoughts or suggestions from you guys. 

Thanks!

**Comment by bgrozev** [comment]
I love the idea! 

I don't know whether it is something that should be incorporated in Jitsi Meet. If it is a simple and separate module and doesn't require much maintenance, it might be viable. Otherwise, perhaps not.

What do you mean by a separate application based on Jitsi Meet? If it is a clone with additional changes it will be easier to evaluate the effort needed to merge it into master and maintain it.

**Comment by bbaldino** [comment]
there are some tools already for doing recording of local media that might be interesting here.  check out https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API

**Comment by ztl8702** [comment]
@bgrozev 
> What do you mean by a separate application based on Jitsi Meet?
I am currently thinking about creating a fork. I am not sure if this can be implemented as a module / plugin to Jisit Meet (perhaps not, if this requires modification on the `react-native-webrtc` level, but correct me if I am wrong).

@bbaldino  Thanks!

**Comment by ztl8702** [comment]
@stale Not stale. I will fire a follow-up PR to #3223 soon.

**Comment by saghul** [comment]
Is there anything actionable here though? When you send the follow-up PR we'll look at it for sure.

**Comment by ztl8702** [comment]
All right.

**Comment by anil1712** [comment]
@ztl8702 Can you please share you local recording code using the MediaRecorder. 
I have implemented the same but I am facing 2 issues:

1. There is no Audio in recoding, somehow only video is getting recorded
2. The video size is too high, 30 seconds video has 10 MB of size, I need to send the recorded video to the server but may be due to large size browser is getting heaviour. 

So please help me or suggest something.

**Comment by ztl8702** [comment]
@anil1712 
You can find the local recording code I wrote in:
https://github.com/jitsi/jitsi-meet/tree/master/react/features/local-recording/recording 

I tried the lossless flac codec (https://github.com/jitsi/jitsi-meet/blob/master/react/features/local-recording/recording/flac/flacEncodeWorker.js) and the browser's default Opus codec (https://github.com/jitsi/jitsi-meet/blob/master/react/features/local-recording/recording/OggAdapter.js) both seemed to produce decent file size (100MB~ish per hour in flac IIRC).

**Comment by trymeouteh** [comment]
I would like a client side recording feature to be able to record the audio or video on any device. Will be harder to do in the browser, but maybe this could be integrated into the chrome/firefox extensions.

**Comment by RainerBielefeld** [comment]
I use client side recording, and it's easy.
* I run **Jitsi** in a WINDOWS Chromium TAB with headset mic and headset earphones
* I additional run the **Jitsi** conference in an additional incognito (private) window   
   * for This window Microphone =  Stereo-Mix"   and  Speaker = "Via High definition Speaker" – Stereo (my normal Speaker, switched off at the speaker device)
* **Audacity** with "WASAF", Mic =Via High definition Speaker" – Stereo and Speaker = something unused

The "private" Jitsi sound output collects the sound from other participants and from my normal jitsi window. So I can record the audio result form all participants without problems.

**Comment by anil1712** [comment]
@RainerBielefeld Can you share sample code of your implementation along with the steps to run to achieve recording

**Comment by abnerh69** [comment]
HI, Any news on Local Recording using Android SDK from Jitsi/Flutter?

**Comment by RainerBielefeld** [comment]
> @RainerBielefeld Can you share sample code

Hi anil1712, it's not code, it's a trick. If you still are interested we can fix a jitsi call and I can demonstrate my way how I do. I think that is more instructive that 2 pages of how to instructions. Contact via rainerbielefeldng@bielefeldundbuss.de
