### ISSUE TITLE
"Jingle error" messages

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#265]
"Jingle error" messages are often logged (as errors), without apparent ill effects.

**Comment by luistduarte** [comment]
localhost environment?

**Comment by luistduarte** [comment]
I have the same messages in the browser, but i cant get audio/video from other participants because,
on jitsi-videobridge i get messages like ice failed

**Comment by paweldomas** [comment]
This is caused by strophe.js bug which no longer exists in the latest version. First 'on result' callback was called for 'session-accept' IQ and then after timeout limit expired Strophe trigerred error callback again.

**Comment by paweldomas** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/commit/b5135c455efa9a46c7403dc1a8984d0df0f6eb80
