### ISSUE TITLE
Automatic live streaming - Question?

### ISSUE THREAD

**Issue by Keqi** [jitsi/jitsi-meet#2651]
Hi,

I've been digging in the documentation trying to find a way to automatically enable video recording when room is created. Here's my user scenario:

Every day two students meet in the conference room and learn together. We want to automatically record all their sessions and save it in our YT channel. We don't want to share our YT streaming key.

I see there are some config options to automatically enable recording https://github.com/jitsi/jitsi-meet/blob/master/config.js#L326,L327 but they did not work for me. I suppose its because I have to install Jibri locally and setup all library dependencies.

Is there any easy way to overcome that problem without spending week on development?

Thanks,
Maciej

**Comment by bgrozev** [comment]
> I see there are some config options to automatically enable recording https://github.com/jitsi/jitsi-meet/blob/master/config.js#L326,L327 but they did not work for me.

I'm pretty sure those only supported the now deprecated recording through the bridge, and not jibri.
