### ISSUE TITLE
Jitsi Video Bridge on Ubuntu 16.04

### ISSUE THREAD

**Issue by nam1665** [jitsi/jitsi-meet#2656]
I download jitsi-video-bridge on Ubuntu 16.04, when I run the command, it's said: "not-authorized, host:localhost, port:5347 org.xmpp.component.ComponentException: not-authorized". 
Do I have to run jitsi-video-bridge on Ubuntu 14. Thank you guys.

**Comment by damencho** [comment]
Are you installing jvb only? Not the whole jitsi-meet? 
Seems your prosody is expecting another secret for the jitsi-videobridge component.

**Comment by nam1665** [comment]
Thank you so much, It's my mistake. I set wrong Secret in prosody
