### ISSUE TITLE
set up the jitsi-meet environment in China

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2659]
Has anyone set up the jitsi-meet environment in China?
I have a lot of error reporting here, asking for guidance.

**Comment by saghul** [comment]
What problems are you experiencing? If UDP traffic is blocked and you are not running the JVB listening for ICE-TCP on port 443 is highly unlikely it will work. Can you give some more details?

**Comment by c526537207** [comment]
I have installed the installation in accordance with the fast installation. After running nginx, I can't request the page in the browser. How can I solve it?

**Comment by saghul** [comment]
What problem do you see? Anything in the browser console? How about the nginx logs?

**Comment by c526537207** [comment]
What services are started when the jitsi starts, and what are the commands?

**Comment by saghul** [comment]
Several services: possibly a web server, prosody, jicofo, and the jitsi-videobridge. They all start automatically with the init stripts included in the Debian packages. How did you install Jitsi Meet onto your server?

**Comment by c526537207** [comment]
I am just following the fast installation, all the processes in ubuntu, how to start?

**Comment by michaelchen001** [comment]
@c526537207 what's your email address or QQ

**Comment by c526537207** [comment]
@michaelchen001 qq526537207

**Comment by saghul** [comment]
I'm going to close this since there is no specific information no actionable items for us here. You opened a myriad of issues all going back to the same problem: initial setup, which, for some unknown reason hasn't worked for you. Please follow up in a single place and provide as much information as possible.
