### ISSUE TITLE
Please give detailed instructions on how to set Avatar and  display name from the iOS SDK

### ISSUE THREAD

**Issue by real19** [jitsi/jitsi-meet#2661]
I have added the iOS framework for JITSI to my Swift iOS project which uses iOS implementation of Rocket.chat . 

I can only set the url of the room and connect to it but the SDK does not document how I can properly set the avatar URL and the display name. 

How can I display the avatar and display name from the iOS SDK?

**Comment by jean-ben-guigui** [comment]
I don't know if there are new ways of doing that but i was able to set the display name using jwt as described here https://github.com/jitsi/jitsi-meet/issues/1880

**Comment by elliscwc** [comment]
@jean-ben-guigui 
may I know how did you get it to work? below is Android code:
```
String value = extras.getString("url");
String jwt = extras.getString("jwt");

Bundle config = new Bundle();
config.putString("startWithAudioMuted", false);
Bundle urlObject = new Bundle();
urlObject.putBundle("config", config);
urlObject.putString("jwt", jwt); // doesn't work 
urlObject.putString("url", value);
this.view.loadURLObject(urlObject);
```
how did you put the jwt object into the bundle?

**Comment by jean-ben-guigui** [comment]
Hi, sorry to respond that late. I was only interested to make it work with iOS, I have no idea how to do it with android.
Hope you've found out!

**Comment by erandakarachchi** [comment]
In android you can use
`JitsiMeetUserInfo userInfo = new JitsiMeetUserInfo();`
  `userInfo.setDisplayName("Jitsi user");`
` userInfo.setAvatar('...some image ...');`
