### ISSUE TITLE
How to really clean previous install of jitsi meet ?

### ISSUE THREAD

**Issue by DigitalCoder** [jitsi/jitsi-meet#2663]
HI All!
I've installed Jitsi meet a first time with a domain name but after I had to change by using a subdomain.
I've purge the first install and clean some files.
I tried to install to the new subdomain.
The welcome page works but after creating the room it restarts because somethings je front.
I have javascript errors in the console log but I don't see where is the  problem.
Installation not completed ?
Problem with SSL certificat?
One service is missing ?

So I think I need to reinstall with clean sources and configuration.
I've read lots of solutions but I would like an official and sure guide to reinstall.
I'm in production with a server Ubuntu 16.04
Is it possible to use apache vhost than nginx ?
Thx

**Comment by saghul** [comment]
> HI All!
> I've installed Jitsi meet a first time with a domain name but after I had to change by using a subdomain.
> I've purge the first install and clean some files.

Have you purged app packages? You can get a list with `dpkg -l | grep -i jitsi`



> The welcome page works but after creating the room it restarts because somethings je front.
> I have javascript errors in the console log but I don't see where is the problem.

Can you please paste those errors?



> Installation not completed ?
> Problem with SSL certificat?
> One service is missing ?

Impossible to tell without any logs. Did the installation give you any errors?



> Is it possible to use apache vhost than nginx ?

Yes, but we prefer nginx.

**Comment by DigitalCoder** [comment]
the console log errors are (to show you I've replace my real sub-domain name "sub.domain.fr") :

> /!\Logger.js:125 [modules/UI/videolayout/VideoLayout.js] <Object.changeUserAvatar>:  Missed avatar update - no small video yet for undefined
> (x)Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 1000
>     at i._allocateConferenceFocusError (moderator.js:413)
>     at moderator.js:341
>     at s.Handler.handler (strophe.js:3385)
>     at s.Handler.run (strophe.js:2554)
>     at strophe.js:3819
>     at Object.forEachChild (strophe.js:1522)
>     at s.Connection._dataRecv (strophe.js:3807)
>     at e.Bosh._onRequestStateChange (strophe.js:5550)
> 	
> (x)Logger.js:125 [modules/xmpp/moderator.js] <i._allocateConferenceFocusError>:  Focus error, retry after 1000 
> (x)Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.focusDisconnected focus.sub.domain.fr 1
> (x)Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 2000
>     at i._allocateConferenceFocusError (moderator.js:413)
>     at moderator.js:341
>     at s.Handler.handler (strophe.js:3385)
>     at s.Handler.run (strophe.js:2554)
>     at strophe.js:3819
>     at Object.forEachChild (strophe.js:1522)
>     at s.Connection._dataRecv (strophe.js:3807)
>     at e.Bosh._onRequestStateChange (strophe.js:5550)
> 	
> (x)Logger.js:125 [modules/xmpp/moderator.js] <i._allocateConferenceFocusError>:  Focus error, retry after 2000 
> (x)Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.focusDisconnected focus.sub.domain.fr 2
> (x)Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 4000
>     at i._allocateConferenceFocusError (moderator.js:413)
>     at moderator.js:341
>     at s.Handler.handler (strophe.js:3385)
>     at s.Handler.run (strophe.js:2554)
>     at strophe.js:3819
>     at Object.forEachChild (strophe.js:1522)
>     at s.Connection._dataRecv (strophe.js:3807)
>     at e.Bosh._onRequestStateChange (strophe.js:5550)
> 	
> (x)Logger.js:125 [modules/xmpp/moderator.js] <i._allocateConferenceFocusError>:  Focus error, retry after 4000 
> (x)Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.focusDisconnected focus.sub.domain.fr 4
> (x)Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 8000
>     at i._allocateConferenceFocusError (moderator.js:413)
>     at moderator.js:341
>     at s.Handler.handler (strophe.js:3385)
>     at s.Handler.run (strophe.js:2554)
>     at strophe.js:3819
>     at Object.forEachChild (strophe.js:1522)
>     at s.Connection._dataRecv (strophe.js:3807)
>     at e.Bosh._onRequestStateChange (strophe.js:5550)
> (x)Logger.js:125 [modules/xmpp/moderator.js] <i._allocateConferenceFocusError>:  Focus error, retry after 8000 
> (x)Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.focusDisconnected focus.sub.domain.fr 8
>

**Comment by chandrantwins** [comment]
Step 1
apt-get --purge remove jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jicofo jitsi-videobridge

step 2
apt-get autoclean

step 3
apt-get --force-yes remove

step 4
apt-get install --reinstall dpkg

step 5
cd /var/lib/dpkg/info

step 6
sudo rm jitsi-meet-web-config.postinst

Above command will clearly uninstall jitsi

**Comment by saghul** [comment]
> (x)Logger.js:125 [conference.js] <e.value>: CONFERENCE FAILED: conference.focusDisconnected focus.sub.domain.fr 2

Looks like a problem with jicofo. Can you check if it's running, and the logs?

**Comment by DigitalCoder** [comment]
I take a look

**Comment by DigitalCoder** [comment]
I've restarted and when I try a new room in jicofo.log I have this :

> 

> Jicofo 2018-03-27 14:45:08.465 SEVERE: [30] org.jitsi.xmpp.component.ComponentBase.run().589 Failed to send ping
> java.lang.NullPointerException
> 	at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
> 	at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:36)
> 	at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:577)
> 	at java.util.TimerThread.mainLoop(Timer.java:555)
> 	at java.util.TimerThread.run(Timer.java:505)
> Jicofo 2018-03-27 14:45:08.670 SEVERE: [31] org.jitsi.meet.ComponentMain.call().278 not-authorized, host:localhost, port:5347
> org.xmpp.component.ComponentException: not-authorized
> 	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
> 	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
> 	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
> 	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
> 	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
> 	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Jicofo 2018-03-27 14:45:09.043 SEVERE: [51] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
> org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
> 	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:291)
> 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1084)
> 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
> 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
> 	at java.lang.Thread.run(Thread.java:748)
> Jicofo 2018-03-27 14:45:09.046 SEVERE: [70] org.jivesoftware.smack.AbstractXMPPConnection.run() Exception in async packet listener
> java.lang.NullPointerException
> 	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
> 	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
> 	at net.java.sip.communicator.impl.protocol.jabber.extensions.caps.EntityCapsManager.removeUserCapsNode(EntityCapsManager.java:362)
> 	at net.java.sip.communicator.impl.protocol.jabber.extensions.caps.EntityCapsManager$CapsPacketListener.processStanza(EntityCapsManager.java:941)
> 	at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1199)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by saghul** [comment]
Can you run `update-ca-certificates -f`, restart jicofo and try again?

**Comment by DigitalCoder** [comment]
before that I can tel you this :

> ~# debconf-show jicofo
>   jicofo/jicofosecret: (password omitted)
>   jicofo/jicofo-authpassword: (password omitted)
> * jitsi-videobridge/jvb-hostname:  visio.cercle-confiance.fr
>   jicofo/jicofo-authuser: focus
>

**Comment by chandrantwins** [comment]
Below command are used to check status about installation. Please check

/etc/init.d/jicofo status 
/etc/init.d/jitsi-videobridge status
service nginx status
prosodyctl status
netstat -anltp | grep "LISTEN"

**Comment by DigitalCoder** [comment]
```
# /etc/init.d/jicofo status
● jicofo.service - LSB: Jitsi conference Focus
   Loaded: loaded (/etc/init.d/jicofo; bad; vendor preset: enabled)
   Active: active (running) since Tue 2018-03-27 16:17:29 CEST; 11min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 31139 ExecStop=/etc/init.d/jicofo stop (code=exited, status=0/SUCCESS)
  Process: 31150 ExecStart=/etc/init.d/jicofo start (code=exited, status=0/SUCCESS)
    Tasks: 31
   Memory: 156.4M
      CPU: 4.142s
   CGroup: /system.slice/jicofo.service
           └─31158 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=/usr/share/jicofo/lib/native/linux-64 -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator....

Mar 27 16:17:29 vps433266 systemd[1]: Stopped LSB: Jitsi conference Focus.
Mar 27 16:17:29 vps433266 systemd[1]: Starting LSB: Jitsi conference Focus...
Mar 27 16:17:29 vps433266 jicofo[31150]: Starting jicofo: jicofo started.
Mar 27 16:17:29 vps433266 systemd[1]: Started LSB: Jitsi conference Focus.
```
```
# /etc/init.d/jitsi-videobridge status
● jitsi-videobridge.service - LSB: Jitsi Videobridge
   Loaded: loaded (/etc/init.d/jitsi-videobridge; bad; vendor preset: enabled)
   Active: active (running) since Tue 2018-03-27 16:17:46 CEST; 11min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 31282 ExecStop=/etc/init.d/jitsi-videobridge stop (code=exited, status=0/SUCCESS)
  Process: 31292 ExecStart=/etc/init.d/jitsi-videobridge start (code=exited, status=0/SUCCESS)
    Tasks: 16
   Memory: 81.2M
      CPU: 3.647s
   CGroup: /system.slice/jitsi-videobridge.service
           └─31301 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=/usr/share/jitsi-videobridge/lib/native/linux-64 -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.co...

Mar 27 16:17:46 vps433266 systemd[1]: Stopped LSB: Jitsi Videobridge.
Mar 27 16:17:46 vps433266 systemd[1]: Starting LSB: Jitsi Videobridge...
Mar 27 16:17:46 vps433266 jitsi-videobridge[31292]: Starting jitsi-videobridge: jvb started.
Mar 27 16:17:46 vps433266 systemd[1]: Started LSB: Jitsi Videobridge.
```

I'm using apache2 configuration

```
# prosodyctl status
Prosody is running with PID 31256
```

```
# netstat -anltp | grep "LISTEN"
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      31256/lua5.1
tcp        0      0 0.0.0.0:5281            0.0.0.0:*               LISTEN      31256/lua5.1
tcp        0      0 127.0.0.1:5347          0.0.0.0:*               LISTEN      31256/lua5.1
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      31256/lua5.1
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      32286/mysqld
tcp        0      0 0.0.0.0:2226            0.0.0.0:*               LISTEN      32436/sshd
tcp        0      0 0.0.0.0:5269            0.0.0.0:*               LISTEN      31256/lua5.1
tcp6       0      0 :::443                  :::*                    LISTEN      31396/apache2
tcp6       0      0 :::443                  :::*                    LISTEN      31396/apache2
tcp6       0      0 :::443                  :::*                    LISTEN      31396/apache2
tcp6       0      0 :::5280                 :::*                    LISTEN      31256/lua5.1
tcp6       0      0 :::5281                 :::*                    LISTEN      31256/lua5.1
tcp6       0      0 ::1:5347                :::*                    LISTEN      31256/lua5.1
tcp6       0      0 :::5222                 :::*                    LISTEN      31256/lua5.1
tcp6       0      0 :::80                   :::*                    LISTEN      31396/apache2
tcp6       0      0 :::80                   :::*                    LISTEN      31396/apache2
tcp6       0      0 :::80                   :::*                    LISTEN      31396/apache2
tcp6       0      0 :::2226                 :::*                    LISTEN      32436/sshd
tcp6       0      0 :::5269                 :::*                    LISTEN      31256/lua5.1
tcp6       0      0 :::8888                 :::*                    LISTEN      31158/java

```

**Comment by chandrantwins** [comment]
it seems you have configuration problem, because everything is running properly.
Please check your config.js and interfaceconfig.js in jitsi-meet

**Comment by chandrantwins** [comment]
Please check once you have done all this steps in jicofo
https://github.com/jitsi/jicofo/blob/master/README.md

**Comment by chandrantwins** [comment]
have you restared your jicofo service. if not please can you try once by restarting

**Comment by DigitalCoder** [comment]
```
sudo /etc/init.d/prosody restart
sudo /etc/init.d/jicofo restart
sudo /etc/init.d/jitsi-videobridge restart
sudo /etc/init.d/apache2 restart
```
done and still have the same problem

in fact, I could see here (https://github.com/jitsi/jitsi-meet/issues/2384) that someone had a similar problem, a password problem

I'm going to check passwords

**Comment by chandrantwins** [comment]
it seems you have not enabled this ports UDP 10000-20000.. please check once

**Comment by DigitalCoder** [comment]
ok I'll check ports UDP 10000-20000

**Comment by chandrantwins** [comment]
is that fixed ..what was the problem?

**Comment by DigitalCoder** [comment]
```
~# iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports s                                                                                                                                                             sh
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2226
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:smtp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:urd
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     udp  --  anywhere             anywhere             udp spt:ntp
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTA                                                                                                                                                             BLISHED
LOG        all  --  anywhere             anywhere             limit: avg 15/min                                                                                                                                                              burst 5 LOG level debug prefix "Dropped by firewall: "
DROP       all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTA                                                                                                                                                             BLISHED
ACCEPT     udp  --  anywhere             anywhere             udp dpts:10000:200                                                                                                                                                             00

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp

Chain f2b-sshd (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

```

**Comment by bgrozev** [comment]
The DROP rule in the INPUT chain will catch udp/10000 packets

**Comment by DigitalCoder** [comment]
and ? what do I have to do  please? @bgrozev

**Comment by DigitalCoder** [comment]
before reinstallation (and purge) if there is a solution to resolve It would be great.

to be sure where are registered and referenced YOURSECRET1 YOURSECRET2 YOURSECRET3 ? in which files?
Which port do I have to open and with which command line ?

Thanks

**Comment by CostanzoPablo** [comment]
The solution is this:

sudo apt purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2

apt remove prosody
apt remove jitsi-meet
apt install dpkg --reinstall
rm /etc/prosody -rf
rm /etc/jitsi -rf

apt autoclean
apt autoremove
