### ISSUE TITLE
Need to implement whatsapp like video calling

### ISSUE THREAD

**Issue by vink1987** [jitsi/jitsi-meet#2665]
Hello there,

I am trying to implement the video calling feature exactly like Whatsapp or Phone call. The interface is supposed to be implement in a way that it lets a user call a remote user and the remote user should get the call options like receive/reject and he can proceed with those options only.

Please provide me a reference or already built code for such functionality.

**Comment by saghul** [comment]
Sorry, that's not how it works. This software is provided to you **for free** so you can use it as-is or build your own application atop, but don't expect someone to build a full application for you.

The mobile apps in this repository are a good starting point, but incoming calls are not implemented.
