### ISSUE TITLE
When I asked for a page, why was it a black screen, not a success value index.html?

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2668]
When I asked for a page, why was it a black screen, not a success value index.html?

**Comment by c526537207** [comment]
console 'ReferenceError: interfaceConfig is not defined',how to solve?

**Comment by damencho** [comment]
What is the webserver that you are using? It doesn't support ssi.

**Comment by c526537207** [comment]
nginx

**Comment by damencho** [comment]
It seems ssi is not turned on. That is strange, as it is enabled in the default config https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L34

**Comment by c526537207** [comment]
No open, HTTP request.Do I have to open it?

**Comment by damencho** [comment]
What do you mean? You need to make sure jitsi-meet is accessible using https.

**Comment by c526537207** [comment]
Yes, I have changed to HTTPS and still cannot load index.html successfully.
chrome console'Uncaught ReferenceError: config is not defined',help !

**Comment by damencho** [comment]
What version of nginx are you using, the default one that comes with debian/ubuntu?
ssi is not working: https://github.com/jitsi/jitsi-meet/blob/master/index.html#L132

**Comment by c526537207** [comment]
yes,nginx version: nginx/1.10.3 (Ubuntu)

**Comment by c526537207** [comment]
error is here ,<script></script>

**Comment by saghul** [comment]
You need the nginx-extras package, since the regular nginx package does not provide ssi support.

**Comment by damencho** [comment]
@saghul Version 1.10.3 is in 16.04 Ubuntu (1.10.3-0ubuntu0.16.04.2). I just installed on DO ubuntu 16.04 vm and this the following:
```
apt-get update
apt-get install nginx
echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
apt-get update
apt-get install jitsi-meet
```
The following installed when doing nginx install:
`The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0 libjpeg-turbo8 libjpeg8 libtiff5 libvpx3 libxpm4 libxslt1.1 nginx nginx-common nginx-core`
So no nginx-extras and everything is working as expected with ssi turned on and working.

**Comment by saghul** [comment]
Hum, so you don't need nginx-extras after all? I may remember incorrectly, sorry!

**Comment by damencho** [comment]
Yep. Works just fine without it.

**Comment by chandrantwins** [comment]
Inside index.html just replace script tag to point interface_config.js location-

**Comment by anvarjezeem** [comment]
**i'm using nginx version: nginx/1.14.0 (Ubuntu)
while calling index.html from jitsi-meet, it shows a blank screen.can u tell how it can be avoided?
