### ISSUE TITLE
Feature request: Create Slack app that allows you to use meet as a calling app in Slack

### ISSUE THREAD

**Issue by BrianGilbert** [jitsi/jitsi-meet#2669]
Meet is currently missing from this list:
https://get.slack.help/hc/en-us/articles/208492868-Voice-video-screen-sharing-apps

It would be super awesome if it could be added to the above list!

About ceating apps:
https://api.slack.com/slack-apps#creating_apps

Submitting to Slack App directory
https://api.slack.com/slack-apps#directory

**Comment by saghul** [comment]
You are more than welcome to work on that on your own, but Jitsi being owned by Atlassian, which has a competing product to Slack, you can understand why we won't ;-)

**Comment by BrianGilbert** [comment]
oh.. I did not realise that it was owned by atlassian, understasndable then I guess :)

**Comment by hlehmann** [comment]
Now that atlassian is pertenaring with slack, stopping stride. So now this feature should be possible ?

**Comment by saghul** [comment]
Probably ;-)

**Comment by BrianGilbert** [comment]
Should the issue be re-opened then? :)

**Comment by emcho** [comment]
For completeness: https://jitsihq.slack.com/apps/A3LN30B7T-jitsi-meet
