### ISSUE TITLE
Failed to get access to local media

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2672]
Unable to access local audio and video, how to solve?

**Comment by saghul** [comment]
Please, paste console logs, we cannot help you without seeing hat's happening.

**Comment by c526537207** [comment]
![_20180329085458](https://user-images.githubusercontent.com/31339057/38064206-5de0dfea-332f-11e8-8faa-930428110d91.png)

**Comment by calamatitech** [comment]
The error is related to the absense of a front camera.
The error shows itself when the device has only a back camera; no error when the device has only a front camera, or when it has front and back camera. I did these tests with Android emulator.
I went back to release jitsi-meet-2528.zip (first day of January 2018), going throught other intermediate releases, but the error persists.
The UI of release 2528 looks like UI of Jitsi Meet version 1.13.71, updated on: 2017-12-23 on Play Store.

**Comment by saghul** [comment]
@calamatitech That's unrelated, this issue is about the web, not mobile devices.

That said, I'm closing this one, due to no following up.

**Comment by calamatitech** [comment]
Can you explain, please? Why web? I did'nt get the message.

**Comment by calamatitech** [comment]
Reading the log above, it can be a web issue.
But I builded the app without any change, and I used it for connecting to the default server: https://meet.jit.si
**GetUserMedia fails when there is only back camera**; my log looks like this:
04-01 09:57:24.602  2846  2886 I ReactNativeJS: '[__filename]', '<s>: ', 'Start muted: '
04-01 09:57:24.664  2846  2886 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Get media constraints', { audio: false,
04-01 09:57:24.664  2846  2886 I ReactNativeJS:   video:
04-01 09:57:24.664  2846  2886 I ReactNativeJS:    { mandatory: {},
04-01 09:57:24.664  2846  2886 I ReactNativeJS:      optional: [ { facingMode: 'user' } ],
04-01 09:57:24.664  2846  2886 I ReactNativeJS:      facingMode: 'user' } }
04-01 09:57:24.950  2846  2886 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Available devices: ', [ { facing: 'back',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     label: 'Camera 0, Facing back, Orientation 0',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     kind: 'videoinput',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     deviceId: '0',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     groupId: null },
04-01 09:57:24.950  2846  2886 I ReactNativeJS:   { facing: null,
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     label: 'Audio',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     kind: 'audioinput',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     deviceId: 'audio-1',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     groupId: null } ]
04-01 09:57:24.952  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:57:24.952  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:57:24.958  2846  2886 W ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', '**Failed to get access to local media. Error** ', { name: null,

In attachment two log, smart glass (only back camera) and smartphone (back and front camera)

[smart_glass_log.txt](https://github.com/jitsi/jitsi-meet/files/1872809/smart_glass_log.txt)
[smartphone_log.txt](https://github.com/jitsi/jitsi-meet/files/1872810/smartphone_log.txt)

**Comment by saghul** [comment]
> Can you explain, please? Why web? I did'nt get the message.

His report was about the web, that was the output of the web console. The mobile apps use react-native-webrtc, which is were the problem may lay for you, so it's a different issue.
