### ISSUE TITLE
502 Bad Gateway,help

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2680]
![_20180329111938](https://user-images.githubusercontent.com/31339057/38068321-285f078e-3343-11e8-81df-d9088753d4f7.png)
![_20180329085458](https://user-images.githubusercontent.com/31339057/38068323-2afe248e-3343-11e8-83e8-71d9b5222e11.png)

**Comment by saghul** [comment]
How is your web server configured to proxy requests to /http-bind?

**Comment by c526537207** [comment]
`# BOSH
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    } `
in nginx

**Comment by saghul** [comment]
Is prosody listening on port 5280 ok? Check with `netstat -tunapl`

**Comment by c526537207** [comment]
root@DESKTOP-MH40E2N:~# netstat -tunapl
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name

how to open?

**Comment by saghul** [comment]
Please paste the actual output. If empty, you have no services listening, which can't be happening.

**Comment by c526537207** [comment]
@saghul It's empty, but it's not possible to have all the service listening. It's weird.

**Comment by c526537207** [comment]
root@DESKTOP-MH40E2N:~# prosodyctl restart
Prosody is not running
**************************
Prosody was unable to find the configuration file.
We looked for: /etc/prosody/prosody.cfg.lua
A sample config file is included in the Prosody download called prosody.cfg.lua.dist
Copy or rename it to prosody.cfg.lua and edit as necessary.
More help on configuring Prosody can be found at http://prosody.im/doc/configure
Good luck!
**************************
Still waiting...
Prosody is still not running. Please give it some time or check your log files for errors.

What happened?why?how?

**Comment by saghul** [comment]
I really don't know what's going on with your system, but things don't seem to be installed correctly. A default prosody config file is installed automatically, if you don't have it it means the installation process didn't complete successfully or it was manually removed.

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by milkperson** [comment]
Thank you @Haravikk! I just upgraded prosody to 0.11.5 and was having this same issue. Adding that Include statement solved it!
