### ISSUE TITLE
No media from Firefox 59

### ISSUE THREAD

**Issue by webintoit** [jitsi/jitsi-meet#2682]
When firefox 59 comes to meeting which already has some participants, it can see media from them, but other participant never will see/hear firefox streams.
When firefox is meeting initiator then^ other browsers can see media from ff.  But after page refresh  firefox media will be lost. 😢 
With FF 57 it works as expected. 

UPD:
When firefox comes to conference with audio/video enabled (default meet.jit.si config) it works as expected.

But when firefox joins the conference with disabled camera/mic, other browsers cannot see firefox.
Also chrome can see incoming traffic on stats but it does not recognizes ff media.

**Comment by rotenbergwitalik** [comment]
yeeeaap. Fucking firefox.

**Comment by webintoit** [comment]
![image](https://user-images.githubusercontent.com/5518513/38098836-ae0f6e58-3381-11e8-9e07-da71662fb0bc.png)

**Comment by v-basanko** [comment]
I think so too...

**Comment by shargorodskyq** [comment]
Also faced same issue, I'm hopeful might resolve

**Comment by saghul** [comment]
@gpolitis Is that BUNDLE line correct? I think audio should be there, right?

**Comment by saghul** [comment]
Yeah, that BUNDLE line is definitely incorrect. However, I tested Firefox 59.0.2 on macOS and could not reproduce this. Can you reproduce it reliably? What steps do you follow? Please be as detailed as you can.

**Comment by webintoit** [comment]
--> Bad story <--
1) Chrome participant1 joins https://meet.jit.si/demo
2) Chrome participant2  joins https://meet.jit.si/demo
Both streams video + audio
------
3) Firefox 59.02 participant3 joins https://meet.jit.si/demo
Firefox enables camera && mic
In this case firefox can see both of chrome users, but any of them can not see firefox media. 
![image](https://user-images.githubusercontent.com/5518513/38135471-f43cb3b4-3420-11e8-92a1-28b44a24cf4f.png)
4) Firefox reloads page.  result the same, sometimes chrome users will se firefox (1 success of 5 tries in my case). 
When chrome users reloads page, result the same. 

--> Success story <--

1) ff 59.02 joins https://meet.jit.si/demo2
It streams video && audio 
2) Chrome joins https://meet.jit.si/demo2
3) Chrome2 joins https://meet.jit.si/demo2
It also streams media
Both of chrome-users can see firefox in this case, firefox can see chrome users.

4) Firefox reloads page. 
Result: 
 firefox can see both of chrome users, but any of them can not see firefox media.

**Comment by webintoit** [comment]
I think it related to this
https://github.com/jitsi/jitsi-meet/issues/2646

**Comment by saghul** [comment]
Thanks for the details @webintoit. I tried reproducing it following your steps but couldn't :-/

**Comment by webintoit** [comment]
Test it again. When firefox comes before other participants, anybody can see it, but after page reload firefox can see anybody, nobody can see firefox. 
ff.room.jvbJingleSession.peerconnection.localDescription
```javascript
RTCSessionDescription { type: "answer", sdp: "v=0\r\no=mozilla...THIS_IS_SDPARTA-59.0.2 6309161766612003509 2 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 BD:7F:04:E1:66:36:DF:E4:84:63:77:7D:AF:3E:6D:C5:C6:88:89:CE:6D:AD:D9:9A:66:21:38:49:C1:6E:30:D4\r\na=ice-options:trickle\r\na=msid-semantic: WMS *\r\na=group:BUNDLE audio video data\r\nm=audio 64760 RTP/SAVPF 111 126\r\nc=IN IP4 46.37.194.219\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:126 0-15\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:60882410\r\na=ice-pwd:0015f6d00a9bff2e51cfcba32719630f\r\na=candidate:0 1 UDP 2122252543 192.168.1.251 64760 typ host\r\na=candidate:1 1 TCP 2105524479 192.168.1.251 9 typ host tcptype active\r\na=end-of-candidates\r\na=ssrc:948127774 cname:{a4735d98-30a1-e24c-b830-bbb6823e9d4a}-1\r\na=ssrc:2306607665 cname:{a4735d98-30a1-e24c-b830-bbb6823e9d4a}-1\r\na=ssrc:2306607665 msid:{47619428-9b67-8444-bb00-acf8082f3321}-1 {c9e6f36d-e8a5-1948-9b4e-70c6267affc4}-1\r\na=rtcp-mux\r\nm=video 64760 RTP/SAVPF 100\r\nc=IN IP4 46.37.194.219\r\na=rtpmap:100 VP8/90000\r\na=fmtp:100 max-fs=12288;max-fr=60\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 goog-remb\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=setup:active\r\na=mid:video\r\na=sendrecv\r\na=ice-ufrag:60882410\r\na=ice-pwd:0015f6d00a9bff2e51cfcba32719630f\r\na=ssrc:2646533856 cname:{a4735d98-30a1-e24c-b830-bbb6823e9d4a}-1\r\na=ssrc:2646533856 msid:{67ccdb3a-9da5-5e4b-a153-f34ae58b4cc3}-1 {a152e8cf-1fd2-5642-9374-d0d6409cc5a5}-1\r\na=ssrc:3745785728 cname:{a4735d98-30a1-e24c-b830-bbb6823e9d4a}-1\r\na=rtcp-mux\r\nm=application 64760 DTLS/SCTP 5000\r\nc=IN IP4 46.37.194.219\r\na=setup:active\r\na=mid:data\r\na=sendrecv\r\na=ice-ufrag:60882410\r\na=ice-pwd:0015f6d00a9bff2e51cfcba32719630f\r\na=rtcp-mux\r\na=sctpmap:5000 webrtc-datachannel 256\r\na=max-message-size:1073741823\r\n" }

```
ff.room.jvbJingleSession.peerconnection.remoteDescription
```javascript
RTCSessionDescription
​
sdp: "v=0\r\no=- 1923518516 2 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=msid-semantic: WMS *\r\na=group:BUNDLE audio video data\r\nm=audio 1 RTP/SAVPF 111 103 104 126\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:103 ISAC/16000/1\r\na=rtpmap:104 ISAC/32000/1\r\na=rtpmap:126 telephone-event/8000\r\na=rtcp:1 IN IP4 0.0.0.0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=setup:actpass\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:98s3f1ca2l2oq2\r\na=ice-pwd:2jvgmq0g557tfeal35m5pevblm\r\na=fingerprint:sha-1 5C:39:F8:DE:71:E2:77:65:A0:46:4A:CD:3D:2F:B2:38:FB:12:AD:DD\r\na=candidate:1 1 tcp 2130706431 172.18.0.1 4443 typ host tcptype passive generation 0\r\na=candidate:2 1 tcp 2130706431 10.90.87.73 4443 typ host tcptype passive generation 0\r\na=candidate:3 1 tcp 2113932031 62.210.202.239 4443 typ host tcptype passive generation 0\r\na=candidate:4 1 udp 2113932031 172.18.0.1 10000 typ host generation 0\r\na=candidate:5 1 udp 2113932031 10.90.87.73 10000 typ host generation 0\r\na=candidate:6 1 udp 2113932031 62.210.202.239 10000 typ host generation 0\r\na=ssrc:1153693149 cname:6sbv16U4gpMNmn4p-1\r\na=ssrc:1153693149 msid:e1c3ac3c-25b1-45c3-bdbc-e70776d8e17c-1 7938d8be-7a94-4727-9470-b682956874ac-1\r\na=ssrc:2288417212 cname:mixed\r\na=ssrc:2288417212 label:mixedlabelaudio0\r\na=ssrc:2288417212 mslabel:mixedmslabel\r\na=ssrc:2288417212 msid:mixedmslabel mixedlabelaudio0\r\na=rtcp-mux\r\nm=video 1 RTP/SAVPF 100 107 101\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:100 VP8/90000\r\na=rtpmap:107 H264/90000\r\na=rtpmap:101 VP9/90000\r\na=rtcp:1 IN IP4 0.0.0.0\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:107 ccm fir\r\na=rtcp-fb:107 nack\r\na=rtcp-fb:107 nack pli\r\na=rtcp-fb:107 goog-remb\r\na=rtcp-fb:101 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=setup:actpass\r\na=mid:video\r\na=sendrecv\r\na=ice-ufrag:98s3f1ca2l2oq2\r\na=ice-pwd:2jvgmq0g557tfeal35m5pevblm\r\na=fingerprint:sha-1 5C:39:F8:DE:71:E2:77:65:A0:46:4A:CD:3D:2F:B2:38:FB:12:AD:DD\r\na=candidate:1 1 tcp 2130706431 172.18.0.1 4443 typ host tcptype passive generation 0\r\na=candidate:2 1 tcp 2130706431 10.90.87.73 4443 typ host tcptype passive generation 0\r\na=candidate:3 1 tcp 2113932031 62.210.202.239 4443 typ host tcptype passive generation 0\r\na=candidate:4 1 udp 2113932031 172.18.0.1 10000 typ host generation 0\r\na=candidate:5 1 udp 2113932031 10.90.87.73 10000 typ host generation 0\r\na=candidate:6 1 udp 2113932031 62.210.202.239 10000 typ host generation 0\r\na=ssrc:1610327527 cname:mixed\r\na=ssrc:1610327527 label:mixedlabelvideo0\r\na=ssrc:1610327527 mslabel:mixedmslabel\r\na=ssrc:1610327527 msid:mixedmslabel mixedlabelvideo0\r\na=ssrc:3468431058 cname:6sbv16U4gpMNmn4p-1\r\na=ssrc:3468431058 msid:1c5ca9e8-8062-45ac-b868-c37aed438559-1 7bc67e4c-6f65-4a93-ba9c-fdb06c9c7456-1\r\na=rtcp-mux\r\nm=application 1 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=mid:data\r\na=sendrecv\r\na=ice-ufrag:98s3f1ca2l2oq2\r\na=ice-pwd:2jvgmq0g557tfeal35m5pevblm\r\na=fingerprint:sha-1 5C:39:F8:DE:71:E2:77:65:A0:46:4A:CD:3D:2F:B2:38:FB:12:AD:DD\r\na=candidate:1 1 tcp 2130706431 172.18.0.1 4443 typ host tcptype passive generation 0\r\na=candidate:2 1 tcp 2130706431 10.90.87.73 4443 typ host tcptype passive generation 0\r\na=candidate:3 1 tcp 2113932031 62.210.202.239 4443 typ host tcptype passive generation 0\r\na=candidate:4 1 udp 2113932031 172.18.0.1 10000 typ host generation 0\r\na=candidate:5 1 udp 2113932031 10.90.87.73 10000 typ host generation 0\r\na=candidate:6 1 udp 2113932031 62.210.202.239 10000 typ host generation 0\r\na=rtcp-mux\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"
​
type: "offer"
```

Also there in ff 59 remote stats calculation does not have resolution, remote ip, but has fps, bitrate up/down, packet loss up/down

**Comment by saghul** [comment]
I tried a few times, i'll try again.

Those two SDPs don't seem to have the bundle problem, FWIW.



> Also there in ff 59 remote stats calculation does not have resolution, remote ip, but has fps, bitrate up/down, packet loss up/down

This is known.

**Comment by webintoit** [comment]
![image 1](https://user-images.githubusercontent.com/5518513/38193373-6ed1481e-367a-11e8-9523-795852d3566b.png)
![image 2](https://user-images.githubusercontent.com/5518513/38193374-6eede1ea-367a-11e8-9a32-c5d956bfdd0e.png)
![image](https://user-images.githubusercontent.com/5518513/38193375-6f0b73ae-367a-11e8-8150-8e323bbf05b0.png)

**Comment by webintoit** [comment]
Tested it with `no-jvb` services e.g mediasoup. It seems to be related to firefox 59  on mac.
Case: 
Chrome joined, then ff joined, result the same as on meet.jit.si.

![image](https://user-images.githubusercontent.com/5518513/38194079-0a6979ec-367e-11e8-8e7b-91bb77d34ca6.png)
But chrome on chrome: 
![image](https://user-images.githubusercontent.com/5518513/38194091-1bdb4322-367e-11e8-9d95-82635f0d9b7c.png)

**Comment by webintoit** [comment]
Now i tested with lib-jitsi-meet/master with /example code. 
![image](https://user-images.githubusercontent.com/5518513/38203523-293a0574-36a8-11e8-89e0-7bc60bbbbabf.png)

When firefox is connected, it saw chrome tracks, but on chrome `mediaStream` was created, but track will never been added. 

Maybe it related  to something like here
https://github.com/versatica/mediasoup-client/commit/7c0178066bf4ea7e92e6d142064a2f427dcdadf5

**Comment by webintoit** [comment]
When chrome reloads page, firefox has this
![image](https://user-images.githubusercontent.com/5518513/38203779-04fa02d0-36a9-11e8-92ea-fba4ed4a6cd5.png)

**Comment by webintoit** [comment]
Seems like ff59  ignores offered track ids. https://bugzilla.mozilla.org/show_bug.cgi?id=1437980

**Comment by saghul** [comment]
@paweldomas can you PTAL?

**Comment by webintoit** [comment]
There is `[modules/RTC/TraceablePeerConnection.js] <r._remoteStreamAdded>:  TPC[2,p2p:false] ignored remote 'stream added' event for non-user streamid: default` 
For firefox streams, TPC should be refactored. I will try )

**Comment by webintoit** [comment]
When ff comes to existing conference, mediaStream.id is always `default`, but changing this 
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTC.js#L747 will affect multiple same tracks from firefox. @saghul, i have no idea.  @bgrozev,  is it should be changed on Jicofo or on lib-jitsi-meet side  ?

**Comment by saghul** [comment]
Thanks a lot for the effort @webintoit!

**Comment by hristoterezov** [comment]
I tried to reproduce the issue on FF 60.0.1 but I was not able.
@webintoit Are you still reproducing it? Have you tested with FF 60.0.1?

**Comment by webintoit** [comment]
Tested with latest ljm /doc/example
firefox has 'default' stream id, chrome does not show tracks from it. 
https://github.com/versatica/mediasoup-client/issues/21
// -^ it can be helpful

**Comment by damencho** [comment]
You still not reproduce this on meet.jit.si, but you reproduce it using the example in lib-jitst-meet?

**Comment by webintoit** [comment]
It can be reproduced on meet.jit.si, also with example lib-jitsi-meet. 
It hard to be reproduced with P2P enabled.
```
[modules/xmpp/JingleSessionPC.js] <eval>:  Processing addRemoteStream
[modules/xmpp/JingleSessionPC.js] <eval>:  ICE connection state:  connected
Halt: There are no SSRC groups in the remote description.
[modules/RTC/TraceablePeerConnection.js] <r._remoteStreamAdded>:  TPC[2,p2p:false] ignored remote 'stream added' event for non-user streamid: default
[modules/xmpp/SdpConsistency.js] <e.value>:  TPC[2,p2p:false] no SSRC found for the recvonly videostream!
[modules/RTC/TraceablePeerConnection.js] <r._processLocalSSRCsMap>:  No local track matched with: b478264b-6f41-41a2-9bbc-6b71f816230e 68f66984-8c9e-4e95-8a60-d8849793ae71 in TPC[2,p2p:false]
[modules/RTC/TraceablePeerConnection.js] <r._adjustLocalMediaDirection>:  Adjusted local video direction to sendrecv
```

**Comment by hristoterezov** [comment]
@webintoit can you reproduce it if you are using not the example for lib-jitsi-meet but the whole jitsi-meet app on meet.jit.si or the latest master?
Note: p2p is disabled for FF!

**Comment by webintoit** [comment]
Tested  again. 
- Chrome joined meet.jit.si/ff-test
- FF joined
![image](https://user-images.githubusercontent.com/5518513/41646484-9b0be976-747c-11e8-8012-c9b998648327.png)

Black screen on ff, `ff has connection issues` on chrome. I have same results after page reaload. 

[modules/RTC/TraceablePeerConnection.js] <r._remoteStreamAdded>:  TPC[1,p2p:false] ignored remote 'stream added' event for non-user streamid: default

I will try again with ljm example.

**Comment by hristoterezov** [comment]
OK. Thanks for the report!

**Comment by damencho** [comment]
There is a signaling fix we are adding as part of fixing the start video muted. For the audio part, there may be also a bug in Firefox for versions 61 and above, reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1472321
