### ISSUE TITLE
Screen Sharing Issue

### ISSUE THREAD

**Issue by alagbesola** [jitsi/jitsi-meet#2684]
Please can't share screen. I get an error message saying "Screen Sharing Extension failed to install".

**Comment by bgrozev** [comment]
You need to allow access to the screen (the button to the left of the URL bar):

<img width="493" alt="screen shot 2018-03-29 at 17 29 32" src="https://user-images.githubusercontent.com/3264699/38116688-cb29b2b0-3376-11e8-870c-dcf2b9faafd2.png">
