### ISSUE TITLE
listen to custom event in android using JitsiMeetViewListener

### ISSUE THREAD

**Issue by tanvir23** [jitsi/jitsi-meet#2686]
Hi guys, is it possible to listen to custom event using JitsiMeetViewListener. For example, when a user left meeting an event called USER_LEFT is fired from lib-jitsi-meet. and if we listening to that event we can execute a function that takes 2 arguments (id and user object). 
My question is, is there a way i can notify this event occurred to the sdk via JitsiMeetViewListener?

**Comment by saghul** [comment]
That's not currently implemented. You'd need to capture that action and send an event, here is where to start, if you feel like implementing it: https://github.com/jitsi/jitsi-meet/blob/master/react/features/mobile/external-api/middleware.js

**Comment by tanvir23** [comment]
really appreciate the quick replay thanks 👍

**Comment by atif-afridi** [comment]
@saghul  hello i have the same requirement how to check if all participant left the conference ?
i check all of the git issues and your comments but nothing was helpful yet.
Thanks

**Comment by saghul** [comment]
We do have those events now: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#jitsimeetviewdelegate and https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#listening-for-broadcasted-events

**Comment by atif-afridi** [comment]
thanks for quick response.

it says "Please see JitsiMeetActivity, which registers for all the events and can serve as an example."

i am unable to find the sample code in JitsiMeetActivity i.e 

IntentFilter intentFilter = new IntentFilter();
    intentFilter.addAction(BroadcastEvent.Type.CONFERENCE_JOINED.getAction());
    LocalBroadcastManager.getInstance(this).registerReceiver(broadcastReceiver, intentFilter);
    
i have extended by VideoActivity with JitsiMeetActivity. i guess it should be handled if we are extending but not with me ? am i using old version for jitsi or what reason it could be ?

**Comment by atif-afridi** [comment]
BroadcastEvent and BroadcastAction arnt imported unable to find by android studio

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by atif-afridi** [comment]
implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }

provided in sample

it would be grat if you share the sdk version and a sample

**Comment by saghul** [comment]
That version is ancient, please use the latest, 3.7.0 as of now.

**Comment by atif-afridi** [comment]
@saghul  Thanks a lot. now its working fine.
