### ISSUE TITLE
build ios app problem

### ISSUE THREAD

**Issue by kangzhe0000** [jitsi/jitsi-meet#2687]
when I run "pod install",it occured,
No podspec found for `RNSound` in `../node_modules/react-native-sound

**Comment by saghul** [comment]
Did you run `npm install` first in the root directory?

**Comment by kangzhe0000** [comment]
Yes,I did,but it also had problem.
![jitsi](https://user-images.githubusercontent.com/22000426/38180952-bc796a64-3662-11e8-9247-27894789792d.png)

**Comment by kangzhe0000** [comment]
I use 'sudo npm install'

**Comment by damencho** [comment]
Can you double check what's going on on your file system, as some of your files are used from .Trash, I think that also can be leading to problems.
