### ISSUE TITLE
Jitsi screen sharing error

### ISSUE THREAD

**Issue by surendra1987** [jitsi/jitsi-meet#2688]
I got an error while screen sharing. Jitsi screen sharin
![2018-03-30 17_21_12-surendra prasad_jitsi_](https://user-images.githubusercontent.com/12031892/38136859-d305337e-343e-11e8-85ee-b0e11b3eaa1e.png)
g extension failed to install.
![2018-03-30 17_21_12-surendra prasad_jitsi_](https://user-images.githubusercontent.com/12031892/38136862-dbd6d156-343e-11e8-8cc9-8b52d88b504e.png)

**Comment by damencho** [comment]
Did you create extension for your deployment, upload it to google chrome webstore, verify the site while doing that and configure the extension id in your config.js?
