### ISSUE TITLE
Quick install - "Unfortunately, something went wrong" on loop forever.

### ISSUE THREAD

**Issue by keantoken** [jitsi/jitsi-meet#2695]
I am using Debian Sid. I installed Jitsi-meet with my local IP address as hostname and tried starting a videoconference in my browser. 

The errors seem to be in the Jicofo log.

[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1865355/jicofo.log)

**Comment by keantoken** [comment]
Installing from the unstable repository made no change.

**Comment by keantoken** [comment]
I tried the workaround here:

https://github.com/jitsi/jitsi-meet/issues/2676#issuecomment-377039435

```
dpkg -l | grep jicofo
ii  jicofo                                   1.0-400-1                      amd64        JItsi Meet COnference FOcus
```

There was nothing in sip-communicator.properties before I added this line, but after adding it I still get the same error.

**Comment by damencho** [comment]
I don't see the setting in your jicofo config, if it is there it should be in the log file. Did you restart jicofo after adding the property?

**Comment by keantoken** [comment]
I restarted the computer. I just tried to check the log, but it is 512MB. I deleted it, but it seems that stopped logging.

Apache and nginx are not installed.

**Comment by keantoken** [comment]
I followed these instructions:

https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

**Comment by damencho** [comment]
You don't need to restart the computer. Just /etc/init.d/jicofo restart.
After deleting the log you need to restart jicofo again in order to be able to see something. Is it working now? If not can you send the log again?

**Comment by keantoken** [comment]
Here is the new log file. It does not loop with the error screen but instead it repeatedly asks me to allow access to the camera/mic. 




[jifoco.log](https://github.com/jitsi/jitsi-meet/files/1865575/jifoco.log)

**Comment by keantoken** [comment]
It turns out nginx was installed under a different name (nginx-full), so I removed and purged it, and purged and reinstalled all the jitsi-meet components. However I still have the same problem.

**Comment by keantoken** [comment]
The error appeared to change after reloading Jicofo but that was actually because my sound drivers crashed...

After reinstalling I had to add the configuration line to /etc/jitsi/jicofo/sip-communicator.properties. Even though I am using the latest Jicofo, the line is not there. However the only thing this did is get rid of the PKIX errors.

So I am back to square one with the looping reload problem. Here is another log in case it is any different from the last one. I know it can work because the video conference on the Jitsi website works.

[jicofo.log.txt](https://github.com/jitsi/jitsi-meet/files/1865634/jicofo.log.txt)

**Comment by keantoken** [comment]
Are these any commands I can run to get more diagnostic info?

**Comment by keantoken** [comment]
Here is jvb.log.
[jvb.log](https://github.com/jitsi/jitsi-meet/files/1865694/jvb.log)

**Comment by damencho** [comment]
Some configuration had been left when purging and now jicofo component secret is different than the one configured in prosody.

Jicofo 2018-03-31 09:42:48.301 SEVERE: [30] org.jitsi.meet.ComponentMain.call().278 not-authorized, host:localhost, port:5347
org.xmpp.component.ComponentException: not-authorized

the component secret is in /etc/jitsi/jicofo/config. I suppose and the password for jicofo is different, so there will be a lot of stuff to fix.
How did you purge? If you already took the way of reinstalling my suggestion is doing:
```
apt-get --purge remove jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-web jicofo jitsi-videobridge prosody
rm -rf /etc/jitsi
apt-get install jitsi-meet
```

**Comment by keantoken** [comment]
Thank you! That worked.

apt-get --purge often leaves a lot of stuff. After I purged nginx there was still /etc/nginx/ and /etc/init.d/nginx.
