### ISSUE TITLE
Android Jitsi Meet unable to access to local server

### ISSUE THREAD

**Issue by zzzykf** [jitsi/jitsi-meet#2696]
I've installed Jitsi Meet on both of my laptop and android phone. I am able to start the video call using browser with the url "https://{ip-address}" but when I use the Jitsi Meet app that is downloaded from PlayStore, it always show the message "You have been disconnected".  
May I know what is the problem ?

**Comment by saghul** [comment]
Are you using a self-signed certificate? If so, that's not going to work unless to add it to the system trust store, it's a platform limitation.

**Comment by zzzykf** [comment]
Thank you for the reply. 
Yes, I am using a self-signed certificate. 
May I know how to add it to the system trust store? Or is there any other ways to allow the Jitsi Meet to be used in local server (there is no domain)?

**Comment by c526537207** [comment]
I have the same problem, how can I solve it?

**Comment by zzzykf** [comment]
@c526537207  I didn't solve the problem actually, but what I did was to use a domain instead of an ip address

**Comment by c526537207** [comment]
@zzzykf It is recommended to replace the https:// {IP -address} with a secure domain name.

**Comment by zzzykf** [comment]
yup, that solved my problem.

**Comment by c526537207** [comment]
@zzzykf Are you Chinese?

**Comment by zzzykf** [comment]
@c526537207  yes, I am

**Comment by c526537207** [comment]
@zzzykf 我也是，qq526537207

**Comment by zzzykf** [comment]
可是我没用qq， 我来自马来西亚

**Comment by CPLASF1925** [comment]
@zzzykf How to solve it？
