### ISSUE TITLE
Failed to get access to local media on smartglass

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#2698]
Hi, I builded the app for Android, cloning the branch master.
It runs successfully on my smartphone (android 6.0.1) and other devices, but It fails to get access to the camera on the my smart glass (android 6.0).
On the same smartglass I tried successfully Jitsi Meet version 1.9.1, camera worked very well.
Both Jitsi Meet and the App builded by myself don't ask for permission to use camera on the smart glass; they ask for it on the smartphone, 

Here is the log of the App builded by myself, executing on the smart glass:
04-01 09:57:21.342  2846  2860 D ReactNative: Initializing React Xplat Bridge.
04-01 09:57:21.346  2846  2860 D ReactNative: Initializing React Xplat Bridge before initializeBridge
04-01 09:57:21.358  2846  2860 D ReactNative: Initializing React Xplat Bridge after initializeBridge
04-01 09:57:21.358  2846  2860 D ReactNative: CatalystInstanceImpl.runJSBundle()
04-01 09:57:21.398  2846  2887 D ReactNative: ReactInstanceManager.setupReactContext()
04-01 09:57:21.398  2846  2887 D ReactNative: CatalystInstanceImpl.initialize()
04-01 09:57:21.398  2846  2887 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-01 09:57:23.068  2846  2886 I ReactNativeJS: '[modules\\browser\\BrowserCapabilities.js]', '<n>: ', 'This appears to be react-native, ver: 0.51.0'
04-01 09:57:23.095  2846  2886 I ReactNativeJS: '[modules\\settings\\Settings.js]', '<n>: ', 'generated callstats uid', 'Willy-JXu'
04-01 09:57:24.160  2846  2886 I ReactNativeJS: Running application "App" with appParams: {"initialProps":{"welcomePageEnabled":true,"externalAPIScope":"0464248f-1be1-4631-b4fb-d602ef8dd5a8","pictureInPictureEnabled":false,"timestamp":1522565840904},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
04-01 09:57:24.332  2846  2886 I ReactNativeJS: '[__filename]', '<s>: ', 'redux state rehydrated as', {}
04-01 09:57:24.377  2846  2886 I ReactNativeJS: '[__filename]', '<s>: ', 'redux state persisted. 99914b932bd37a50b983c5e7c90ae93b -> c7c9c4dc24824c39d17f1e29cb8d849c'
04-01 09:57:24.577  2846  2886 W ReactNativeJS: '[JitsiMeetJS.js]', '<n>: ', 'Analytics disabled, disposing.'
04-01 09:57:24.578  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Disposing of analytics adapter.'
04-01 09:57:24.589  2846  2886 I ReactNativeJS: '[modules\\RTC\\ScreenObtainer.js]', '<n>: ', 'Screen sharing not supported by the current browser: ', 'react-native'
04-01 09:57:24.590  2846  2886 I ReactNativeJS: '[modules\\RTC\\ScreenObtainer.js]', '<n>: ', 'Desktop sharing disabled'
04-01 09:57:24.601  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:57:24.602  2846  2886 I ReactNativeJS: '[__filename]', '<s>: ', 'Start muted: '
04-01 09:57:24.664  2846  2886 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Get media constraints', { audio: false,
04-01 09:57:24.664  2846  2886 I ReactNativeJS:   video:
04-01 09:57:24.664  2846  2886 I ReactNativeJS:    { mandatory: {},
04-01 09:57:24.664  2846  2886 I ReactNativeJS:      optional: [ { facingMode: 'user' } ],
04-01 09:57:24.664  2846  2886 I ReactNativeJS:      facingMode: 'user' } }
04-01 09:57:24.950  2846  2886 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Available devices: ', [ { facing: 'back',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     label: 'Camera 0, Facing back, Orientation 0',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     kind: 'videoinput',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     deviceId: '0',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     groupId: null },
04-01 09:57:24.950  2846  2886 I ReactNativeJS:   { facing: null,
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     label: 'Audio',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     kind: 'audioinput',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     deviceId: 'audio-1',
04-01 09:57:24.950  2846  2886 I ReactNativeJS:     groupId: null } ]
04-01 09:57:24.952  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:57:24.952  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:57:24.958  2846  2886 W ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Failed to get access to local media. Error ', { name: null,
04-01 09:57:24.958  2846  2886 W ReactNativeJS:   message: 'Failed to create new track',
04-01 09:57:24.958  2846  2886 W ReactNativeJS:   constraintName: undefined }, { audio: false,
04-01 09:57:24.958  2846  2886 W ReactNativeJS:   video:
04-01 09:57:24.958  2846  2886 W ReactNativeJS:    { mandatory: {},
04-01 09:57:24.958  2846  2886 W ReactNativeJS:      optional: [ { facingMode: 'user' } ],
04-01 09:57:24.958  2846  2886 W ReactNativeJS:      facingMode: 'user' } }
04-01 09:57:24.961  2846  2886 E ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'failed to obtain video stream - stop', [gum.general: Failed to create new track]
04-01 09:57:24.978  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:57:24.981  2846  2886 E ReactNativeJS: '[__filename]', '<s>: ', 'Failed to create local tracks', [ 'video' ], [gum.general: Failed to create new track]
04-01 09:57:44.559  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:58:48.847  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:58:50.895  2846  2886 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'

And here is the log on the smartphone:

04-01 09:08:23.437 31476 31476 D ReactNative: ReactInstanceManager.ctor()
04-01 09:08:23.497 31476 31476 D ReactNative: ReactInstanceManager.createReactContextInBackground()
04-01 09:08:23.497 31476 31476 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
04-01 09:08:23.498 31476 31476 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
04-01 09:08:23.498 31476 31476 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-01 09:08:23.498 31476 31476 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
04-01 09:08:23.560 31476 31490 D ReactNative: ReactInstanceManager.createReactContext()
04-01 09:08:24.112 31476 31490 D ReactNative: Initializing React Xplat Bridge.
04-01 09:08:24.116 31476 31490 D ReactNative: Initializing React Xplat Bridge before initializeBridge
04-01 09:08:24.128 31476 31490 D ReactNative: Initializing React Xplat Bridge after initializeBridge
04-01 09:08:24.128 31476 31490 D ReactNative: CatalystInstanceImpl.runJSBundle()
04-01 09:08:24.169 31476 31517 D ReactNative: ReactInstanceManager.setupReactContext()
04-01 09:08:24.169 31476 31517 D ReactNative: CatalystInstanceImpl.initialize()
04-01 09:08:24.169 31476 31517 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-01 09:08:25.873 31476 31516 I ReactNativeJS: '[modules\\browser\\BrowserCapabilities.js]', '<n>: ', 'This appears to be react-native, ver: 0.51.0'
04-01 09:08:25.900 31476 31516 I ReactNativeJS: '[modules\\settings\\Settings.js]', '<n>: ', 'generated callstats uid', 'Ahmad-hlE'
04-01 09:08:26.992 31476 31516 I ReactNativeJS: Running application "App" with appParams: {"initialProps":{"welcomePageEnabled":true,"externalAPIScope":"231f7daf-61a9-4b7e-88f4-dc01515a4819","pictureInPictureEnabled":false,"timestamp":1522566503494},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
04-01 09:08:27.161 31476 31516 I ReactNativeJS: '[__filename]', '<s>: ', 'redux state rehydrated as', {}
04-01 09:08:27.205 31476 31516 I ReactNativeJS: '[__filename]', '<s>: ', 'redux state persisted. 99914b932bd37a50b983c5e7c90ae93b -> c7c9c4dc24824c39d17f1e29cb8d849c'
04-01 09:08:27.414 31476 31516 W ReactNativeJS: '[JitsiMeetJS.js]', '<n>: ', 'Analytics disabled, disposing.'
04-01 09:08:27.416 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Disposing of analytics adapter.'
04-01 09:08:27.427 31476 31516 I ReactNativeJS: '[modules\\RTC\\ScreenObtainer.js]', '<n>: ', 'Screen sharing not supported by the current browser: ', 'react-native'
04-01 09:08:27.428 31476 31516 I ReactNativeJS: '[modules\\RTC\\ScreenObtainer.js]', '<n>: ', 'Desktop sharing disabled'
04-01 09:08:27.439 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:08:27.440 31476 31516 I ReactNativeJS: '[__filename]', '<s>: ', 'Start muted: '
04-01 09:08:27.508 31476 31516 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Get media constraints', { audio: false,
04-01 09:08:27.508 31476 31516 I ReactNativeJS:   video:
04-01 09:08:27.508 31476 31516 I ReactNativeJS:    { mandatory: {},
04-01 09:08:27.508 31476 31516 I ReactNativeJS:      optional: [ { facingMode: 'user' } ],
04-01 09:08:27.508 31476 31516 I ReactNativeJS:      facingMode: 'user' } }
04-01 09:08:27.815 31476 31516 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Available devices: ', [ { facing: 'back',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     label: 'Camera 0, Facing back, Orientation 90',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     kind: 'videoinput',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     deviceId: '0',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     groupId: null },
04-01 09:08:27.815 31476 31516 I ReactNativeJS:   { facing: 'front',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     label: 'Camera 1, Facing front, Orientation 270',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     kind: 'videoinput',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     deviceId: '1',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     groupId: null },
04-01 09:08:27.815 31476 31516 I ReactNativeJS:   { facing: null,
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     label: 'Audio',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     kind: 'audioinput',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     deviceId: 'audio-1',
04-01 09:08:27.815 31476 31516 I ReactNativeJS:     groupId: null } ]
04-01 09:08:27.817 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:08:27.817 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:08:27.818 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:09:24.077 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 09:09:27.141 31476 31516 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'onUserMediaSuccess'
04-01 09:09:27.155 31476 31516 D ReactNativeJS: '[modules\\RTC\\JitsiLocalTrack.js]', '<n>: ', 'Setting new MSID: b2834e9e-e6b1-44a4-8701-ec82a8a83a7a 6bf150f5-f362-43bb-9a85-e1e4b26d308a on LocalTrack[undefined,video]'
04-01 09:09:27.163 31476 31516 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'

**Comment by saghul** [comment]
This sounds like https://github.com/jitsi/jitsi-meet/issues/2209

**Comment by calamatitech** [comment]
I tried the app on a android emulator, with only a back camera.
I got the same error, afther giving the app the permission to use the camera.
Why does the app Jitsi Meet works well on the smart glass? Can be it related to the signature of the app?
The only difference between the app Jitsi Meet and the app builded by myself is the signature.
I used a self generated private key to sign the apk.

Moreover, I builded the app on Windows, using the following sequence of commands:

npm install
mkdir android\app\src\main\assets
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
react-native run-android
or
react-native run-android --variant=release

Here is the log generated on the Android emulator, with only a back camera
04-01 17:24:42.630  2683  2709 I ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Available devices: ', [ { facing: 'back',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     label: 'Camera 0, Facing back, Orientation 270',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     kind: 'videoinput',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     deviceId: '0',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     groupId: null },
04-01 17:24:42.630  2683  2709 I ReactNativeJS:   { facing: null,
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     label: 'Audio',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     kind: 'audioinput',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     deviceId: 'audio-1',
04-01 17:24:42.630  2683  2709 I ReactNativeJS:     groupId: null } ]
04-01 17:24:42.630  2683  2709 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 17:24:42.630  2683  2709 W ReactNativeJS: '[modules\\statistics\\AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'
04-01 17:24:46.145  2683  2709 W ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Failed to get access to local media. Error ', { name: null,

**Comment by calamatitech** [comment]
I forgot to say that I got the error when the android emulator has only a back camera; if the emulator has only a front camera, the error did not show.
Please notice when I speak about Jitsi Meet app, I mean the Jitsi Meet app downloaded from the Play Store.

**Comment by calamatitech** [comment]
Sorry, the version of Jitsi Meet app available in the Play Store is 1.14.75, 1.9.1 is the version of the app available on github, branch master.
I will look backward in the versions of the app to find the same version as Play Store.

**Comment by saghul** [comment]
Yep, this looks the same as #2209, please let's continue there, I'm closing this as a duplicate.
