### ISSUE TITLE
Changed router, cannot connect locally

### ISSUE THREAD

**Issue by keantoken** [jitsi/jitsi-meet#2699]
Hello. I changed to a different router and now I cannot connect to the videoconference using my own IP address (refused to connect). The router uses DD-WRT and I reset it to factory settings. After that I set my local IP address to static but have not done anything else.

[jvb.log](https://github.com/jitsi/jitsi-meet/files/1866304/jvb.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1866305/jicofo.log)

**Comment by keantoken** [comment]
So I added the NAT harvester lines to the config file. I didn't need to use them for the previous router (Linksys BEFSR41) so I thought they didn't apply to local use.

So I can reach the videoconference locally now.

Now I am trying to get port forwarding to work. Going to my public IP address brings me to my router page and I can't seem to change this. Going to public-IP:443 or public-IP:4443 results in ERR_NO_RESPONSE.

**Comment by keantoken** [comment]
I believe the problem was that my router is using port 443 for it's web config interface. So I forwarded a different port.

I then found by rabid experimentation that the new port number needs to be added to the bosh line in /etc/jitsi/meet/<public.IP.address>-config.js

So now I can access the video conference from the internet using the new port. You must use the https:// prefix however to tell your browser that it needs to treat the new port like the HTTPS port.

Anyways, I guess this is a closed issue now, but I would appreciate any tips on better ways to do this or potential security issues.

**Comment by Annihil8ted** [comment]
@keantoken, how did you forward your jitsi instance to another port? I'm in the exact same situation. So far, I've redirected nginx port to receive on my new port and modified the bosh line in /etc/jitsi/meet/<public.IP.address>-config.js. What else is needed?

**Comment by keantoken** [comment]
I used port forwarding in my router, and used the default Jitsi config without nginx or apache. See the image. The second image is port range forwarding on the next config tab which is needed for ports 10000-20000. Note I have a zombie entry for port 10000 before I realized it needs to be a range, not a single port.

3rd image is the static local IPs I set for my computer so that someday the router doesn't assign me a different one and the server stops working (but for a short test you could just configure Jitsi to use your current local IP address). Jitsi uses 200 and my browser uses 201. I don't think there is any benefit to having 2, unless you have multiple servers running on your computer that are trying to use the same ports.

I don't know how all the config options in the jitsi config files work, it would be nice to have a line by line explanation. Perhaps looking through the .deb config script would explain some things.

![jitsi-port-forwarding](https://user-images.githubusercontent.com/4388640/38246274-dd74f374-3706-11e8-8977-d8d7086fe080.png)
![jitsi-port-range-forwarding](https://user-images.githubusercontent.com/4388640/38246273-dd62adcc-3706-11e8-83ad-d91c5983f524.png)
![jitsi-static-local-ip](https://user-images.githubusercontent.com/4388640/38246522-a4bb316e-3707-11e8-9f74-40503f3fc0ca.png)

**Comment by keantoken** [comment]
Okay, I have consulted with a better man. Those configs might work, but are pretty bad.

A better config is to forward public port say 9980 (can be anything that doesn't conflict with an existing service) to local port 443. Then set up port triggering to forward port range 10000-20000 when port 9980 is used. This way the https port isn't in the middle of the UDP port range.

Don't bother using 2 IP addresses unless you are an expert and know of a way to do that without creating problems. I didn't have problems, but most likely some hardware/software will at some point.

At this point I can connect to one person. If a 3rd person joins, video stops for everyone. As soon as the 3rd person leaves, video starts again. It seems to be related to this:

https://github.com/jitsi/jitsi-meet/issues/2645

**Comment by keantoken** [comment]
The Jitsi server is installed from the unstable repository (linux). When it asks for the hostname I enter my public IP address.

The next thing I do is add the NAT harvester lines to /etc/jitsi/videobridge/sip-communicator.properties:

#org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<local.IP.address>
#org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<public.IP.address>
org.jitsi.videobridge.TCP_HARVESTER_MAPPED_PORT=<public.port>

Because my router is using port 443, I forward another public port to port 443 in the router's config, something outside of the second port range. I also forward port range 10000-20000.

Now I go to /etc/jitsi/meet/<public.IP.address>-config.js and edit the line that starts with 'bosh' to add the forwarded port number:

bosh: '//<public.IP.address>:10403/http-bind',


Oddly enough it seems to be working right today. I don't know what changed. Maybe it was one of the Jitsi updates. I still need to test it more, but I got 3 people to join without losing video.

**Comment by c526537207** [comment]
@keantoken I also encountered ICE fail and more than two people who couldn't see video and asked for help.
