### ISSUE TITLE
How can I allow more than 2 people at a time?

### ISSUE THREAD

**Issue by zzzykf** [jitsi/jitsi-meet#2700]
I've deployed jitsi on AWS EC2 and it only works for p2p. The screen with be black whenever there are more than 2 people in the room. 
I installed the jitsi meet using the quick installation. Is there anything I missed?

**Comment by damencho** [comment]
Provide js console log, jicofo and jvb logs to analyze what can be the problem.

**Comment by zzzykf** [comment]
I'm sorry, but where can I find the jicofo and jvb logs?

**Comment by damencho** [comment]
/var/log/jitsi

**Comment by c526537207** [comment]
This should be due to the low bandwidth.

**Comment by c526537207** [comment]
@saghul If you want to configure the video meeting for 6-8 people, what is the bandwidth?

**Comment by chandrantwins** [comment]
Please go here https://www.testports.com/ and check whether your port is enabled or not

**Comment by c526537207** [comment]
@zzzykf Has the problem been solved?

**Comment by classfiy** [comment]
@zzzykf 你的问题是否已经解决?我也遇到这个问题

**Comment by zzzykf** [comment]
@classfiy I've changed to kurento instead of jitsi
