### ISSUE TITLE
"Current video quality" info dead end

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2702]
We see a circle with "LD".
Mouseover says "Current video quality".
There is no further "(i)" or "(?)" to see a list of what LD corresponds to, or the rest of the qualities' names.

**Comment by saghul** [comment]
You can click on the "eye" icon, which lets you pick the quality, otherwise is automatic. I wonder if we don't show the dialog when clicked though.

**Comment by saghul** [comment]
@virtuacoplenny didn't we have this before? if so, what was the reason for removing it?

**Comment by jidanni** [comment]
@saghul no "eye" icon on  https://meet.jit.si/ . Closest one finds is an "i" icon.

**Comment by virtuacoplenny** [comment]
The "eye" icon is the "Manage call quality" option in the overflow menu. The overflow menu is the popover opened by clicking the far right button on the menu bar, the button with the triple dots.

**Comment by jidanni** [comment]
@virtuacoplenny ah! found it. Why in the world is it not also linked to that circle in the upper right!?
