### ISSUE TITLE
Don't give "Current video quality" if camera is disabled

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2703]
We see a circle with "LD".
Mouseover says "Current video quality".
But my computer doesn't even have a camera.
So that can't be right.

But it does have audio though.

**Comment by virtuacoplenny** [comment]
The "current video quality" label is for the video that's currently displayed on the large screen. So it's not about your send video quality, although it could be if you're on large screen. Would adjusted tooltip text be helpful? The adjustment would be to specify it's video quality being received from the current speaker on large screen. There is also a known bug with the video quality label where a video muted participant (which is practically the same as not having a camera) is displayed on large screen it still displays some value. Maybe that's the issue you're referring to.

**Comment by jidanni** [comment]
All I know is #2702...
So there needs to be two call quality menu items, linked to two circles in the upper right. One for sending, one for receiving. All clearly marked.

**Comment by virtuacoplenny** [comment]
Correct. After implementing the original quality selector, which actually was opened from the quality label itself but got moved into the toolbar for a reason I don't remember, it was quickly noted that there should be some kind of interaction with send quality as well. Right now the quality selector only affects receive quality. There's an internal ticket for further work on the quality selector, which includes work to change receive quality, but the effort has not been staffed or queued for staffing.
