### ISSUE TITLE
Add mouseover to arrow

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2704]
In the lower right there is an arrow.
Add a mouseover so we know what it will do so we don't have to click to find out.

**Comment by virtuacoplenny** [comment]
There's a good amount of technical jank associated with the filmstrip in general. A lot of the UI is still in a spaghetti jquery world (not jquery's fault), which includes some of the filmstrip. I tried moving that arrow to be react, which would make your request easier and be inline with current codebase direction, but I couldn't get a review. https://github.com/jitsi/jitsi-meet/pull/1926. I'll see if I can make time to update that PR some day but for now open tasks exist to get the filmstrip converted to react, and your request could easily slot into there. If you want to make the change yourself, without the refactoring, it'd be here: https://github.com/jitsi/jitsi-meet/blob/9e53d40b9cacf956a529b1b1697c22c0543e2bf0/modules/UI/videolayout/Filmstrip.js#L56.
