### ISSUE TITLE
Port Forwarding Troubles/ sip-communicator.properties necessary?

### ISSUE THREAD

**Issue by Annihil8ted** [jitsi/jitsi-meet#2708]
Having stood up a fully operation jitsi utilizing the quick install method, I now need to move jitsi from 443 or 4443 to a different port like 5000 due to existing applications on those two ports.

I've reconfigured nginx to respond to port 5000 and I've also changed in /etc/jitsi/meet/<ip>-config.js the bosh endpoint. Everything in terms of jitsi is working. Which makes me wonder if adding the extra lines to sip-communicator.properties is necessary? I'm curious what does it affect?

An error that I'm getting is a crossorigin issue when trying to integrate with etherpad. Etherpad will load and perform correctly but it doesn't seem very stable. Sometimes the endpoint won't be hit and error out. 

This is one of the issues I'm seeing:
`Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught SecurityError: Blocked a frame with origin "https://ip:5000" from accessing a cross-origin frame. Script: https://ip:5000/libs/app.bundle.min.js?v=2675 Line: 2 Column: 2801463 StackTrace:  DOMException: Blocked a frame with origin "https://ip:5000" from accessing a cross-origin frame.
    at o (https://IP:5000/libs/app.bundle.min.js?v=2675:2:2801463)
    at HTMLIFrameElement.a.onload (https://IP:5000/libs/app.bundle.min.js?v=2675:2:2802689)`

**Comment by Annihil8ted** [comment]
Going to :5000/etherpad/ I'm getting a lot of Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught SecurityError: Blocked a frame with origin "https://ip:5000" from accessing a cross-origin frame. Script: https://ip:5000/libs/app.bundle.min.js?v=2675 Line: 2 Column: 2801463 StackTrace:  DOMException: Blocked a frame with origin "https://ip:5000" from accessing a cross-origin frame.
    at o (https://ip:5000/libs/app.bundle.min.js?v=2675:2:2801463)
    at HTMLIFrameElement.a.onload (https://ip:5000/libs/app.bundle.min.js?v=2675:2:2802689)

**Comment by bgrozev** [comment]
> Which makes me wonder if adding the extra lines to sip-communicator.properties is necessary? I'm curious what does it affect?

Which extra lines?

> Blocked a frame with origin "https://ip:5000" from accessing a cross-origin frame.

I am guessing you configured the etherpad with an IP address instead of the same domain name that Jitsi Meet uses. You also need to make sure that :5000/etherpad/ is proxied to the correct place (opening it in a browser should show the etherpad interface, not Jitsi Meet. See https://meet.jit.si/etherpad/)

**Comment by Annihil8ted** [comment]
Okay so I just tested a clean jitsi instance without modifying the ports and problem exists even in this instance.

**Comment by Annihil8ted** [comment]
@bgrozev, these are the lines I'm refering to.

Running behind NAT
Jitsi-Videobridge can run behind a NAT, provided that all required ports are routed (forwarded) to the machine that it runs on. By default these ports are (TCP/443 or TCP/4443 and UDP 10000-20000).

The following extra lines need to be added the file ~/.sip-communicator/sip-communicator.properties (in the home directory of the user running the videobridge):

org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>
So the file should look like this at the end:

org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>

Oops, sorry got carried away with abstracting. There is indeed a dns name and not just an ip.
I do indeed get the etherpad interface when I open :5000/etherpad/. It's not very stable though

**Comment by bgrozev** [comment]
> @bgrozev, these are the lines I'm refering to.

Whether you need to use these lines or not is not affected by the port you use for the web server

**Comment by Annihil8ted** [comment]
I'm trying to have Jitsi be accessible on port 5000. The only thing I've changed is to nginx and ip-config.js. So far it seems to be working with the exception of etherpad integration stability. Because everything seems to work, this has me wondering what changing the sip-communicator.properties will do. Do I need to change it for full functionality of jitsi? My understanding from documentation is that it needs to be changed but it seems like everything works without changing it.

**Comment by bgrozev** [comment]
> Do I need to change it for full functionality of jitsi?

If conferences work, then adding the NAT harvester properties is not necessary.

Note that jitsi uses udp/10000 for the ICE connections, so if some of your users can not access this (due to e.g. restrictive firewalls) then will not be able to connect.



> The reason why I mentioned the cross origin error is I'm wondering if that's related to sip-communicator.properties

No, that's not related.

**Comment by Annihil8ted** [comment]
Thank you for the clarification! I'll close this ticket soon then. Just a follow up, what is the purpose of NAT harvester properties? I understand it's for NAT purposes but I figured changing the port to 5000 would fall under that?

**Comment by Annihil8ted** [comment]
Gotcha thanks!
