### ISSUE TITLE
Allow users to enter conference without video and audio.

### ISSUE THREAD

**Issue by hristoterezov** [jitsi/jitsi-meet#271]

**Comment by gpolitis** [comment]
Has this been fixed in Chrome? In FF currently this is not possible. I'm wondering if I should open a separate issue for FF.

**Comment by foss-** [comment]
Works in Chromium 43.0.2357.81 (64-bit), so indeed FF only.

**Comment by Zalmoxisus** [comment]
It doesn't work for video on Chrome too, according to the issue https://github.com/jitsi/jitsi-meet/issues/277

**Comment by foss-** [comment]
Ping! What's the status of this?

#277 has been closed. When visiting https://meet.jit.si/ and creating a new room with Firefox 42.0 I get asked if I want to allow access to the microphone (twice) which seems odd.

@gpolitis you got any status quo on this?

**Comment by gpolitis** [comment]
Hi @foss-, unfortunately this issue is still valid. We have done some work on FF and fixed a few bugs but not this one.

**Comment by akuckartz** [comment]
:+1: for this use case.

**Comment by gpolitis** [comment]
Just to clarify, this should be working on Chrome, @hristoterezov implemented this a while ago. It's only on FF that it doesn't work and that's tracked in #347.
