### ISSUE TITLE
quick install is not working

### ISSUE THREAD

**Issue by chandrantwins** [jitsi/jitsi-meet#2711]
Hi jitsi team,
I am in ubuntu 16.04 and nginx server

I have tried to install jitsi-meet but i am getting following error

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.2579-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by damencho** [comment]
What are your OS and version?

**Comment by PhuCuong14ctt** [comment]
Hello damencho :)

I am following Quick Install guide, and fail at the last step:

> /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh 

I'm not sure about my DNS name. I'm running VM Ubuntu 16.0.4 on Azure
In /etc/hosts
    127.0.0.1      jitsimeet.southeastasia.cloudapp.azure.com        localhost
    127.0.1.1      jitsimeet.southeastasia.cloudapp.azure.com         jitsimeet

My error is:

> An unexpected error occurred:
> The request message was malformed :: Error creating new authz :: DNS name does not have enough labels

Where am I wrong??

**Comment by damencho** [comment]
@PhuCuong14ctt please do not hijack threads with different problems, please create your own issue if you do not find similar problem.
Maybe letsencrypt got confused cause your DNS resolves locally as localhost ip-address.

**Comment by chandrantwins** [comment]
Hi Team,

Problem was apt-get deleted.. so i recoved this using following command

sudo sed -i -re 's/\w+\.archive\.ubuntu\.com/archive.ubuntu.com/g' /etc/apt/sources.list

Now its installing depends too
