### ISSUE TITLE
npm install -> nothing happens

### ISSUE THREAD

**Issue by sefter25** [jitsi/jitsi-meet#2713]
hello

i have clone the jitsi-meet on opensuse leap 42.3 then i start "npm install" in jitsi-meet directory i wait and wait and wait... nothing happens

when i started comando strace npm install > i can see a lot of
epoll_wait(5, {}, 1024, 49)             = 0

what happens here?

thanks for help

**Comment by saghul** [comment]
That's a question for node / npm rather than for us, I'm afraid. What node / npm versions are you using?

**Comment by saghul** [comment]
You probably need to update your npm version. We use package-lock, which is only supported in npm > 5 IIRC.

**Comment by sefter25** [comment]
in opensuse is the latest npm6 ->  node version 6.12.2 and npm version 3.10.10
where i can find npm > 5?

**Comment by sefter25** [comment]
so i have update npm to 5.8.0
now i got permanently this message in strace:
epoll_wait(5, {}, 1024, 49)             = 0
write(11, "[\33[7m \33[27m\33[90m................"..., 132[ .................] \ loadIdealTre) = 132llDepsIntoIdealTree: sill install loadIdealTree
epoll_wait(5, {}, 1024, 0)              = 0

and nothing happens

**Comment by saghul** [comment]
Sorry, I have no idea what could be going wrong. If there is an issue it's on the Node side of things...

**Comment by sefter25** [comment]
ok, i drop the package-lock.json and now it´s running a little bit...
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
[  ................] | fetchMetadata: sill pacote range manifest for copy-descriptor@^0.1.0

**Comment by sefter25** [comment]
after 15min it´s going on, i think the installation takes a lot of time....

**Comment by sefter25** [comment]
i have now installed jitsi-meet
what is the next? how i can start?

**Comment by saghul** [comment]
What are you trying to do? If you want to run your own infrastructure you should follow the quick install instructions (see the README).

**Comment by sefter25** [comment]
yes, i want to run our own infrastructure. what is the difference between this npm installation and quick install? the quick install is for debian, but i have opensuse
