### ISSUE TITLE
Problem with audio/video when I use the api

### ISSUE THREAD

**Issue by SergioComeron** [jitsi/jitsi-meet#2714]
I installed my own jitsi meet server and when I access the page to access sessions eg: myhost / sessionTest everything works correctly (audio ok, video ok, etc ...) but when I use the api I can enter the session but I can not use neither audio nor video. Is this a problem with the certificate? Is it because the certificate is a self-signed certificate? 
I have it auto-signed while I am with the development tests, then when I send it to production it will be a normal certificate.

Thanks!

**Comment by damencho** [comment]
Are you accessing the API using https?

**Comment by SergioComeron** [comment]
Hi damencho!
First thanks for your reply.

Yes, I access the api using https.
I give you a little more information to see if we get to see where the problem is:
I'm creating a plugin for Moodle (LMS) and the problem appears when the Moodle launched a jitsi session, the page that creates the session is of this type:
`
<html itemscope itemtype="http://schema.org/Product" prefix="og: http://ogp.me/ns#" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
    </head>
    <body>
        <script src="https://meet.jit.si/external_api.js"></script>
        <script>
            var domain = "myhost";
            var options = {
                roomName: "sesionName",
            }
            var api = new JitsiMeetExternalAPI(domain, options);
            api.executeCommand('displayName', 'username');
            api.executeCommand('toggleVideo');
            api.executeCommand('avatarUrl', 'avatarImage');
        </script>
    </body>
</html>
`
(The value of the variables I get it from before)

**Comment by damencho** [comment]
Have you tried this, does it work? 
<script src="https://meet.jit.si/external_api.js"></script>
        <script>
            var domain = "meet.jit.si";
This way it will use meet.jit.si to download the API and the meet.jit.si backend deployment.
If you want to provide  domain = "myhost"; then on that machine "myhost" you need to deploy the backend.

**Comment by damencho** [comment]
I just tested your code and doing `var domain = "meet.jit.si";` and commenting the `api.executeCommand('toggleVideo');` and it works fine I see my video.

**Comment by SergioComeron** [comment]
Hi Damencho!
My problem is with my plugin, I recorded a video exposing the problem:
[video](https://youtu.be/S_HGi7JfArQ)

If I execute my code out of my plugin jitsi run ok. 
The code at localhost & the server it's the same. 
What could be the problem?

**Comment by damencho** [comment]
When you have failed to access camera, have you checked the console logs?
I have the impression that the second link is loaded under http which may prevent loading webrtc, but if this is the case you will see in the js console logs.

**Comment by SergioComeron** [comment]
mmmmm it's possible. 
on the server, the development environment is only secured for login to the moodle platform. I'm going to ask the systems department to secure the entire site and test. But that's for sure, in the console I get some error related to this issue and link to [this](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)
I'll tell you what happens.

Thank you!

**Comment by saghul** [comment]
Yep, you need the entire site to be HTTPS.

**Comment by SergioComeron** [comment]
as you said after passing all the moodle to https chrome we no longer have problems with the camera.

Thanks for everything!
