### ISSUE TITLE
letsencrypt: DNS name does not have enough labels

### ISSUE THREAD

**Issue by PhuCuong14ctt** [jitsi/jitsi-meet#2716]
> /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

An unexpected error occurred:
The request message was malformed :: Error creating new authz :: DNS name does not have enough labels

In /etc/hosts
You mean i should change

> 127.0.0.1 jitsimeet.southeastasia.cloudapp.azure.com localhost
> 127.0.1.1 jitsimeet.southeastasia.cloudapp.azure.com jitsimeet

into public IP like this?

> 20.188.96.140 jitsimeet.southeastasia.cloudapp.azure.com localhost
> 20.188.96.140 jitsimeet.southeastasia.cloudapp.azure.com jitsimeet

right?

Sorry for hijacking another post. I will delete it immediately. I think we have the same issue is "quick install is not working" lol 👍

**Comment by damencho** [comment]
Is it working when you changed it from 127.0.0.1 to your public address?

**Comment by PhuCuong14ctt** [comment]
No. It still fails with the same error above.

**Comment by damencho** [comment]
It is some letsencrypt issue, I quickly search for it and found this: https://community.letsencrypt.org/t/error-creating-new-authz-dns-name-does-not-have-enough-labels/49614/14. There are may be more resources to look at, just search for your error.

**Comment by PhuCuong14ctt** [comment]
Surely, i  read it already before i raised a question.
I think my domain name "jitsimeet.southeastasia.cloudapp.azure.com" is valid.
Could you show me in detail how to fix it. I'm a noob :(

**Comment by damencho** [comment]
I have no idea what is the problem, you can ask and open issue on letsencrypt issue tracker. This is not an error with jitsi-meet, it is some letsencrypt related issue.

**Comment by PhuCuong14ctt** [comment]
Anyway, thanks a lot. You're so kind.

When i can run jitsi-meet, i will email u :)

It's time to close this topic!

**Comment by damencho** [comment]
Not having a letsencrypt will not prevent you from using it :) I suspect your deployment maybe in a strange state because of that failure. At least port 443 is not open.
