### ISSUE TITLE
Cross Origins Issue

### ISSUE THREAD

**Issue by Annihil8ted** [jitsi/jitsi-meet#2717]
I'm getting a strange cross origins issue that I can't seem to isolate between jitsi and etherpad. My jitsi was installed via quick install but now sits on port 5000, https://ipname:5000. Etherpad was installed normally at https://ipname:9001. Accessing etherpad on its own at https://ipname:9001 yields no issue however trying to access etherpad at https://ipname:5000/etherpad/ gives me this:

`WebSocket connection to 'wss://ipname:5000/etherpad/socket.io/?EIO=3&transport=websocket&sid=ldwb_AaFe9V9IHwPAAAQ' failed: Error during WebSocket handshake: Unexpected response code: 400`

When I try to access etherpad from within a jitsi conference session, I get this:

`Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught SecurityError: Blocked a frame with origin "https://ipname:5000" from accessing a cross-origin frame. Script: https://ipname:5000/libs/app.bundle.min.js?v=2675 Line: 2 Column: 2801463 StackTrace:  DOMException: Blocked a frame with origin "https://ipname:5000" from accessing a cross-origin frame.
    at o (https://ipname:5000/libs/app.bundle.min.js?v=2675:2:2801463)
    at HTMLIFrameElement.a.onload (https://ipname:5000/libs/app.bundle.min.js?v=2675:2:2802689)`

[conference.js] <e.value>:  CONFERENCE FAILED: conference.setup_failed Error: ICE fail
    at r.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:469)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TraceablePeerConnection.js:262)

[modules/connectivity/ParticipantConnectionStatus.js] <e.value>:  No participant for id: 3a0808b6

This is what I have in /etc/nginx/sites-available/ipname.conf
`    # Etherpad-lite
    location /etherpad/ {
        proxy_pass https://ipname:9001/;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_buffering off;
        proxy_set_header Host $http_host;
    }
}
`

This is what I have in /etc/jitsi/meet/ipname-config.js
`      etherpad_base: 'https://ipname:5000/etherpad/p/',
`

**Comment by Annihil8ted** [comment]
Within /var/log/nginx/error.log, I'm getting this

2018/04/03 16:25:57 [alert] 7639#7639: *164 open socket #12 left in connection 9
2018/04/03 16:25:57 [alert] 7639#7639: *124 open socket #21 left in connection 11
2018/04/03 16:25:57 [alert] 7639#7639: *27 open socket #20 left in connection 12
2018/04/03 16:25:57 [alert] 7639#7639: *154 open socket #15 left in connection 15
2018/04/03 16:25:57 [alert] 7639#7639: aborting
2018/04/03 16:33:21 [alert] 9125#9125: *159 open socket #21 left in connection 5
2018/04/03 16:33:21 [alert] 9125#9125: *218 open socket #13 left in connection 13
2018/04/03 16:33:21 [alert] 9125#9125: aborting
2018/04/03 16:36:25 [alert] 11139#11139: *39 open socket #12 left in connection 8
2018/04/03 16:36:25 [alert] 11139#11139: *9 open socket #3 left in connection 9
2018/04/03 16:36:25 [alert] 11139#11139: aborting

**Comment by keantoken** [comment]
This is something to try:

https://github.com/jitsi/jitsi-meet/issues/2645#issuecomment-378307350

**Comment by Annihil8ted** [comment]
@keantoken I don't think my issue is related to changing ports as the problem I outlined also exists without modifying the ports.
