### ISSUE TITLE
Add dial-in number for Canada

### ISSUE THREAD

**Issue by patcon** [jitsi/jitsi-meet#2723]
Thanks for the great software!

What would need to happen to make this happen? Curious to use this issue to document the general process of getting new numbers in!

I couldn't quite figure out where these numbers are coming from, aside from finding them to be related to the `dialInNumbersUrl` endpoint on config :)

Please help repair the deflated egos of Canada's Jitsi Meet users! :)

**Comment by virtuacoplenny** [comment]
I asked around a bit out of curiosity. Another service is used (right now that's VoxImplant) to make those numbers available and handle some of the call logic and there's some manual configuration involved somewhere. So adding Canada would mean asking emcho (Emil) to pay for Canadian numbers and get whatever manual changes are needed. Or as I put it, "so, it's magic."

**Comment by patcon** [comment]
@emcho please please please help make this a thing

I would love to push for usage of Jitsi Meet within the "Civic Tech Toronto" community that I co-organize within. We are 3000 members, and gather weekly in groups of 60-80 to work on open civic projects. So I promise this is for the benefit of more than one internet-man :)

Also, I will send you a shiny bauble via air-freight in the medium-future 🛫 📫 🎉  (bauble will not actually explode with confetti or any other explodable)
