### ISSUE TITLE
Point contributors towards a more user-friendly web IRC client

### ISSUE THREAD

**Issue by patcon** [jitsi/jitsi-meet#2726]
Re-ticketed from https://github.com/jitsi/jitsi-meet/issues/2721#issuecomment-378400922

Just found the section of the mailing list page that mentions the real-time chat options for IRC:
https://desktop.jitsi.org/Development/MailingLists#irc

I would like to propose that we link to a more user-friendly web-based IRC client:
https://kiwiirc.com/nextclient/irc.freenode.net/#jitsi

This will make this comms channel less intimidating to less-technical users who may arrive in the future.

Thanks for hearing me out! :)

**Comment by saghul** [comment]
IRC doesn't get much use these days, alas... However, the proposed URL at least it uses SSL, which is a plus, so I'm in. @jitsi/developers thoughts?

**Comment by damencho** [comment]
@saghul Yep, seems fine. Even works on mobile.

@patcon The problem with IRC is lack of history. If you open an issue and we discuss something there it will be indexed, searchable and other people can find it. While whatever we say in IRC stays there and no one can benefit of it.

**Comment by patcon** [comment]
Thanks both! @damencho true say. I opened another ticket for that :)
https://github.com/jitsi/jitsi-meet/issues/2721#issuecomment-378520209

Your thoughts there would be totally appreciated.

**Comment by mestaritonttu** [comment]
Message history is coming to Kiwi IRC in the near future. Remember that the next gen client has not been officially launched yet.

**Comment by patcon** [comment]
neato! thanks!
