### ISSUE TITLE
Failed to start LSB: Prosody XMPP Server

### ISSUE THREAD

**Issue by PhuCuong14ctt** [jitsi/jitsi-meet#2727]
Hi damencho,

> ● prosody.service - LSB: Prosody XMPP Server
>    Loaded: loaded (/etc/init.d/prosody; bad; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2018-04-04 05:33:58 UTC; 15ms ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 34468 ExecStart=/etc/init.d/prosody start (code=exited, status=1/FAILURE)
> 
> Apr 04 05:33:58 jitsimeet systemd[1]: Starting LSB: Prosody XMPP Server...
> Apr 04 05:33:58 jitsimeet prosody[34468]:  * Starting Prosody XMPP Server prosody
> Apr 04 05:33:58 jitsimeet prosody[34468]:    ...fail!
> Apr 04 05:33:58 jitsimeet systemd[1]: prosody.service: Control process exited, code=exited status=1
> Apr 04 05:33:58 jitsimeet systemd[1]: **Failed to start LSB: Prosody XMPP Server.**
> Apr 04 05:33:58 jitsimeet systemd[1]: prosody.service: Unit entered failed state.
> Apr 04 05:33:58 jitsimeet systemd[1]: prosody.service: Failed with result 'exit-code'.
> dpkg: error processing package prosody (--configure):
>  subprocess installed post-installation script returned error exit status 1
> dpkg: dependency problems prevent configuration of jitsi-meet-prosody:
>  jitsi-meet-prosody depends on prosody | prosody-trunk; however:
>   Package prosody is not configured yet.
>   Package prosody-trunk is not installed.
> 
> dpkg: error processing package jitsi-meet-prosody (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of jitsi-meet:
>  jitsi-meet depends on jitsi-meet-prosody (= 1.0.2579-1); however:
>   Package jitsi-meet-prosody is not configured yet.
> 
> dpkg: error processing package jitsi-meet (--configure):
>  dependency problems - leaving unconfigured

When I used Nginx, it didn't alert me anything but now i used Apache. 

I see you answered the same problem in the mailing list. I checked my key and it existed in /var/lib/prosody/. However, in the end i don't what i should do to solve this problem.

**Comment by PhuCuong14ctt** [comment]
Hi chandrantwins,

I reinstalled the Prosody but the problem now is when I open the browser and connect to the server all I get is the apache2 default index.html while I want to get to jitsi web interface.

**Comment by chandrantwins** [comment]
you have to change server  root path.. inside /etc/apache2/sites-enabled/yourdomain.conf

**Comment by saghul** [comment]
Please open a new issue for the web server problem, this one started about prosody and is now solved, so I'm going to go ahead and close it.
