### ISSUE TITLE
make command just stalls on ./node_modules/.bin/webpack -p

### ISSUE THREAD

**Issue by Renaud009** [jitsi/jitsi-meet#2732]
'make' command just seems to stall on 'node_modules/.bin/webpack -p', no output
Tried to build project on both CentOS 7/Node 8.5/NPM 5.3 and Ubuntu/Node 9.10.1/NPM 5.6.
What am I doing wrong?

**Comment by saghul** [comment]
It may take a reasonably long time, unfortunately. How long have you waited?

**Comment by Renaud009** [comment]
Waited for a whole night...
I just actually made it work by installing webpack globally (3.9.1) and modifying Makefile accordingly. Weirdly, the build process seem to be a lot faster this way on my CentOS VM than on by Windows Ubuntu subsystem.
