### ISSUE TITLE
Jitsi Install on Nginx 1.13.6

### ISSUE THREAD

**Issue by Annihil8ted** [jitsi/jitsi-meet#2734]
I'm trying to install jitsi on nginx with 1.13.6 however the quick installer breaks. What would be the most viable way of going forward? A manual installation or modification of the installtion packages and how?

**Comment by damencho** [comment]
Is this a default nginx coming with ubuntu/debian? 
What are the errors you see?

**Comment by damencho** [comment]
This needs fixing the debian configuration scripts. But I think you can woraround it by creating sites available and sites enable folders before installing jitsi meet. Or the other option is to install default nginx and then upgrade to the newer one, I will test it later and will report my findings.

**Comment by Annihil8ted** [comment]
Yeah that was my hunch too. Unfortunately, I don't know how to modify the configuration scripts. For now, I've installed the newer version of nginx and created the sites-available and sites-enable folder and then symlinking them to the correct locations in the newer nginx. I'll report back if this works or not.

Following up, will installing default then upgrading not break the folder structures?

**Comment by damencho** [comment]
Yep, it doesn't break anything. I just tested it:
- apt install nginx 
- add the debian repo from nginx.org
- apt update
- apt install nginx
- add to nginx.conf just after `include /etc/nginx/conf.d/*.conf;` I've added `include /etc/nginx/sites-enabled/*;`, `/etc/init.d/nginx restart`
- follow the quick-install procedure and everything is working (I've tested it on 16.04 Ubuntu).

**Comment by Annihil8ted** [comment]
Everything seems to work as before. All that's needed is the sites-available and sites-enable folder and then symlinking the conf file to conf.d.

**Comment by Annihil8ted** [comment]
The confirmation above from me was directly installing the newer version and making the changes.

> add to nginx.conf just after include /etc/nginx/conf.d/*.conf; I've added include /etc/nginx/sites-enabled/*;, /etc/init.d/nginx restart

Where is this located? Is this the preinst script for the packages?
