### ISSUE TITLE
Device Settings > Test sound: telephone ringing misleading

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2741]
On https://meet.jit.si/.... in Device Settings > Test sound,
we hear a phone ringing sound.
This makes us think it is exactly like the Skype Test Call,
where after a few rings a connection will be made.
But in fact it is just one test sound.
So perhaps substitute a cat's meow, etc. instead.

**Comment by saghul** [comment]
Everything is subjective, of course. We are sticking to it. You are free to change in your own installation.
