### ISSUE TITLE
"Everyone starts hidden" not clear

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2742]
Below "Device Settings" one sees "Everyone starts hidden".
But that could mean their cameras are all off,
or their icons do not appear in some tab.
So please use clearer language, or have a mouseover explaining it.

**Comment by WildYorkies** [comment]
https://github.com/jitsi/jitsi-meet/blob/2f23f8e4004b611af8318d32ba61325ec003bf5c/lang/main.json#L134
https://github.com/jitsi/jitsi-meet/blob/2f23f8e4004b611af8318d32ba61325ec003bf5c/lang/main.json#L135

Change these both to 

>Everyone starts with microphone muted
>Everyone starts with camera off

@jidanni Thoughts? Not sure which branch to make these changes on.

**Comment by geckolinux** [comment]
> Change these both to
> 
>> Everyone starts with microphone muted
>> Everyone starts with camera off

I agree, I just had to Google this to figure out what it means.
