### ISSUE TITLE
 "point its location" is bad English

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2743]
Upon installation we read:
> Jitsi Meet is best to be set up with an SSL certificate. Having no certificate, a self-signed one will be generated. By choosing self-signed  you will later have a chance to install Let’s Encrypt certificates. Having a certificate signed by a recognised CA, it can be uploaded on the server and point its location. The default filenames will be /etc/ssl/--domain.name--.key for the key and /etc/ssl/--domain.name--.crt for the certificate.

But "point its location" is bad English. No I can't make a patch because I don't know what it means.

**Comment by saghul** [comment]
Yeah, it doesn't sound right. What it tries to say is that if you already have a valid certificate you can specify its location so that one will be used.
