### ISSUE TITLE
Error creating new authz :: DNS name does not have enough labels

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2747]
We are told to do
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

But this only results in
```
Upgrading certbot-auto 0.22.2 to 0.23.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: DNS name does not have enough labels
Please see the logfiles in /var/log/letsencrypt for more details.

IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

\# perl -pwle 's/\w{33}/\@/g;' /var/log/letsencrypt/letsencrypt.log > /tmp/g.log
[g.log](https://github.com/jitsi/jitsi-meet/files/1882320/g.log)

**Comment by damencho** [comment]
You can search the issue tracker and the forums of letsencrypt, there were multiple reports of this problem. 
There was another user reporting the same recently. It has something to do with dns, or the address it resolves to or server not accessible from letsencrypt servers.

**Comment by jidanni** [comment]
@damencho I am thinking maybe
```
This script will:
- Need a working DNS record pointing to this machine(for domain jidanni)
```
might have something to do with it.

Most users are just connection via their home PC via a modem connected to a ISP via a dynamic IP address.
Quite different than a company who has registered a domain name, and has a fixed IP address.

May those instructions are only for companies.
