### ISSUE TITLE
The repository 'http://download.jitsi.org/deb unstable/ Release' is not signed.

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2748]
https://github.com/jitsi/jitsi-meet/wiki/Debian-installation
says
```
You can resolve the warnings with:
wget -qO - https://download.jitsi.org/nightly/deb/unstable/archive.key | apt-key
```
But then
\# apt-get update
Hit:1 http://free.nchc.org.tw/debian experimental InRelease
Hit:2 http://free.nchc.org.tw/debian unstable InRelease                                              
Ign:3 http://download.jitsi.org/deb unstable/ InRelease                                              
Get:4 http://download.jitsi.org/deb unstable/ Release [1,547 B]
Get:5 http://download.jitsi.org/deb unstable/ Release.gpg [72 B]
Ign:5 http://download.jitsi.org/deb unstable/ Release.gpg
Reading package lists... Done  
W: GPG error: http://download.jitsi.org/deb unstable/ Release: The following signatures were invalid: 040F57608F84BAF1BF844A62C697D823EB0AB654
E: The repository 'http://download.jitsi.org/deb unstable/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by jidanni** [comment]
Same problem for "nigthly".

**Comment by damencho** [comment]
Tha page was outdated (a user had created it in 2015 and since then many things changed). I just fixed it. Thanks.
