### ISSUE TITLE
Improvements to logging

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#275]
These are some events/information which we should consider logging (from the client) in order to help debugging:
*Changes from video to screen share
*Browser version
*Page close/reload
*Speaker changes
*Pinned speakers
*Mute/unmute
*Jingle states
*XMPP connection states

**Comment by gpolitis** [comment]
XMPP connection state changes are interesting to log too. They could help find out more about XMPP connection failures (see #268).

**Comment by bgrozev** [comment]
Thanks, added to the list. That's be tricky, though, since we need an XMPP connection to send logs in the first place

**Comment by gpolitis** [comment]
I was thinking about using a REST logging service, like something built around influxdb or some other db. Not sure if it worths the effort though, but I thought I should mention this here to get it off my head.

**Comment by bgrozev** [comment]
We could do this, but we'd have to handle authentication once more (now jicofo does it for us automatically).

**Comment by gpolitis** [comment]
RTP stats (like raw RTP stats reports in JSON format from Chrome) and SDPs could be useful too. RTP stats could consume a lot of space so that needs to be taken into consideration.

**Comment by bgrozev** [comment]
We do have the RTP stats (on Chrome, not on FF yet).

**Comment by bgrozev** [comment]
I think we now have logs for everything in the list
