### ISSUE TITLE
'React/RCTConvert.h' file not found when app is build in Xcode

### ISSUE THREAD

**Issue by ayhamk94** [jitsi/jitsi-meet#2750]
I did everything that the docs are saying but I am not able to build the app in Xcode
I am running Xcode 9.3 
react-native-cli  2.0.1

**Comment by saghul** [comment]
Did you do `pod install`? What CocoaPods version do you have?

**Comment by ayhamk94** [comment]
I already did pod install in the Ios folder and I am using 1.5.0

**Comment by tomrossberlin** [comment]
I've had the same problem since I updated XCode the other day. The React libraries are installed in the workspace, but when I build, they cannot be found.

**Comment by vuuet** [comment]
I have the same problem

**Comment by lunikit** [comment]
Try installing CocoaPods 1.3.1

**Comment by ayhamk94** [comment]
Sorry for the late answer but I got it to work for me when I used CocoaPods 1.4 even with the new version of Xcode.
for everyone who is trying to install an old version of CocoaPods, this is the command 
`sudo gem install cocoapods -v 1.4.0` on Mac.
