### ISSUE TITLE
Bug: Share Document State Not Accurate

### ISSUE THREAD

**Issue by Annihil8ted** [jitsi/jitsi-meet#2751]
With etherpad integration, normally you open it up with the open shared document button and close it with the close shared document button. If you open shared document, then click on a user to bring to focus, and then click close document, it reopens the document. Only when you click it again does the document close. This behavior seems a little strange.

**Comment by aaronkvanmeerten** [comment]
I have confirmed this behavior exists in the latest release.  Thanks for the report!

**Comment by Annihil8ted** [comment]
No problem! Should I close this?
