### ISSUE TITLE
Camera is on and off

### ISSUE THREAD

**Issue by ITISAG** [jitsi/jitsi-meet#2754]
While using the new jitsi in the chromium browser, the camera is first supported, but after a few seconds, it reports a malfunction.

**Comment by damencho** [comment]
Can you provide the js logs of such session?

**Comment by ITISAG** [comment]
I don't have it since it was with the meet.jit.si server you provide. 
Unless you tell me that I would have a client side log for jitsi on my computer. 

Great software, BTW. We love jitsi. It is just that we very much miss the remote control feature . 


Von: "Дамян Минков" <notifications@github.com> 
An: "jitsi/jitsi-meet" <jitsi-meet@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com> 
Gesendet: Freitag, 6. April 2018 19:57:54 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 



Can you provide the js logs of such session?

**Comment by damencho** [comment]
There are client javascript logs. On chrome on mac you open View -> Developer -> JavaScript Console, right click on the opened Panel/Window and there is an option "Save as...".

There is remote control you can try, but you need to compile a project from source. The side which desktop you want to control need to open the meeting inside an electron app: https://github.com/jitsi/jitsi-meet-electron

**Comment by ITISAG** [comment]
Thanks for answering so quickly. 

I tried to reproduce the error but it was not really Coming this time. 

I noticed a couple of flickering in the session, but not really an outage like during this mornings sessions. 

Might have been a bandwidth or server load issue, too. I am connected over WLAN into a 100 MBps fiber line. 

I saw a couple of errors in the log still, thus I am sending you the log I got here. 

Machine wise: running on a chromium browser on Linux Mint 18.3 

BR, Joerg 



Von: "Дамян Минков" <notifications@github.com> 
An: "jitsi" <jitsi-meet@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com> 
Gesendet: Freitag, 6. April 2018 21:54:08 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 



There are client javascript logs. On chrome on mac you open View -> Developer -> JavaScript Console, right click on the opened Panel/Window and there is an option "Save as...". 

There is remote control you can try, but you need to compile a project from source. The side which desktop you want to control need to open the meeting inside an electron app: [ https://github.com/jitsi/jitsi-meet-electron | https://github.com/jitsi/jitsi-meet-electron ]

**Comment by ITISAG** [comment]
Thanks for asking. In my case, the camera was running and a green light was on for active video all the time. But suddenly, a red error message appeared in Jitsy that said that the camera is inaccessible and the video froze. The light of the camera was still on at that time and the message dropped after a few seconds. The picture stream did not recover, however - until I closed the session and retried. This happened about three times. We then left the video off, as it was not that important at that session. 

----- Ursprüngliche Mail -----

Von: "Дамян Минков" <notifications@github.com> 
An: "jitsi/jitsi-meet" <jitsi-meet@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com> 
Gesendet: Freitag, 6. April 2018 22:21:49 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 


Maybe I didn't understand you correctly by "malfunction" you mean that for example, your camera was running - light is turned on that it is being used, and at some point, you see it turned off? 
Or it is just the other person is not seeing your video, with a message due to connectivity issues or some other message (what is the message is important)?

**Comment by damencho** [comment]
Is the camera USB or integrated?

**Comment by ITISAG** [comment]
Hi, the camera is integrated and works fine with the elder version of the jitsi meet interface 

----- Ursprüngliche Mail -----

Von: "Дамян Минков" <notifications@github.com> 
An: "jitsi/jitsi-meet" <jitsi-meet@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com> 
Gesendet: Samstag, 7. April 2018 17:35:48 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 


Is the camera USB or integrated?

**Comment by damencho** [comment]
If this happens again, please save your browser js console logs and upload it here.

**Comment by ITISAG** [comment]
happened again, see screenshot and log 

----- Ursprüngliche Mail -----

Von: "Дамян Минков" <notifications@github.com> 
An: "jitsi/jitsi-meet" <jitsi-meet@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com> 
Gesendet: Montag, 9. April 2018 15:36:11 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 


If this happens again, please save your browser js console logs and upload it here.

**Comment by damencho** [comment]
I don't see any attachment

**Comment by ITISAG** [comment]
Resending 


two attachments are present, like last time .. 1x png (23,2 kb) , 1x .log (size is 39,2 kb) 

BR, Joerg 
----- Ursprüngliche Mail -----

Von: "Joerg Lorenz" <jlorenz@itis.de> 
An: "jitsi/jitsi-meet" <reply@reply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com>, "jitsi/jitsi-meet" <jitsi-meet@noreply.github.com> 
Gesendet: Mittwoch, 11. April 2018 17:28:42 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 


happened again, see screenshot and log 

----- Ursprüngliche Mail -----

Von: "Дамян Минков" <notifications@github.com> 
An: "jitsi/jitsi-meet" <jitsi-meet@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Author" <author@noreply.github.com> 
Gesendet: Montag, 9. April 2018 15:36:11 
Betreff: Re: [jitsi/jitsi-meet] Camera is on and off (#2754) 


If this happens again, please save your browser js console logs and upload it here.

**Comment by TheReal1604** [comment]
@ITISAG just want to give the hint that it seems that attachments from email-replys are not attached to the github issue. Maybe provide some downloadlink.
