### ISSUE TITLE
Debian: Mention what to do after installation

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2755]
1. User Googles "debian jitsi"
1. User finds e.g.,
    1. https://github.com/jitsi/jitsi-meet/wiki/Debian-installation
    1. https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ (P.S., one says apt, the other apt-get)
2. User completes installation.
3. User realizes neither within the package nor without, there are no instructions on what to do next.

**Comment by chandrantwins** [comment]
So your next step goes here
1) you have to configure nginx or apache2 root folder to jitsi-meet folder
2) you have to enable interface_config.js,config.js inside index.html

**Comment by jidanni** [comment]
Good. Be sure all that is mentioned on the web page.

**Comment by saghul** [comment]
> So your next step goes here
> 
>     you have to configure nginx or apache2 root folder to jitsi-meet folder
>     you have to enable interface_config.js,config.js inside index.html

Neither of those things need to be done.

If nginx or apache are already installed they will be configured to serve Jitsi Meet, otherwise a Jetty server is automatically started by the Jitsi Videobirdge to serve the assets.

The only next step is to open the URL: https://the-hostname-you-chose-during-install/

**Comment by jidanni** [comment]
So all this needs to be made clear on the web page.

**Comment by delpes** [comment]
I installed Jitsi on an Ubuntu machine with nginx/1.10.3 - The installation completes successfully but no config files for nginx are created or modified. 

It would be nice if you could implement a check during installation that looks for those files.
Additionally some hints or a sample nginx/apache config would be very helpful.

**Comment by damencho** [comment]
@delpes Please use the community forum for question or suggestions. https://community.jitsi.org

If you have nginx installed before installing jitsi-meet, the packages should configure it, if it doesn't there may be some bug.
What is the result of executing: `dpkg-query -f '${Status}' -W 'nginx' 2>/dev/null | awk '{print $3}`, this is how we detect that nginx is installed.
Maybe your deployment is configured to use jetty now.
The example files(templates) are in the code: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example, and after installation those are in /usr/share/doc/jitsi-meet-web-config.

**Comment by damencho** [comment]
What to do is already mentioned in the [quick install guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#open-a-conference) which is the recommended doc for installing.
