### ISSUE TITLE
Many "XXXXXXXXXX not enough data" messages logged

### ISSUE THREAD

**Issue by d2chau** [jitsi/jitsi-meet#276]
When users join a meeting, Jitsi-Meet logs many "XXXXXXXXXX not enough data" messages to the console within the browser. 

This is the portion of the code which is displaying the error

```
var before = this.baselineAudioLevelsReport[idx];
if (!before)
{
    console.warn(getStatValue(now, 'ssrc') + ' not enough data');
    continue;
}
```

**Comment by gpolitis** [comment]
This is usually harmless. It's useful for debugging but not otherwise. My thinking is that we should be able to set logging levels and filter what we display at the JS console. This is mildly related to #275 that discusses how to gather logging from the client to the backend.

**Comment by bgrozev** [comment]
Fixed by now
