### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by jmthackett** [jitsi/jitsi-meet#2763]
Is there a guide to monitoring the quality of webRTC calls and other functions of jitsi anywhere? I'd be interested in lag, jitter, anything else involving call quality.

**Comment by damencho** [comment]
Yep, but you need an account and to enable callstats.io. On their dashboard there a lot of stats around media and webrtc.

**Comment by jmthackett** [comment]
Seems to be a minimum pricing of 500eur/month - I'll have a look at writing something 'good enough' I suppose. Will close this in a few days if nobody else comments.
