### ISSUE TITLE
Allow browser's Copy Link Address context menu to copy the Call Info Link

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2765]
On https://meet.jit.si/... the circle i button shows Call Info: Link meet.jit.si...
1. Say http or https
2. Allow browser's Copy Link context menu to copy it.

**Comment by saghul** [comment]
Sounds good to me. /cc @virtuacoplenny maybe?

**Comment by virtuacoplenny** [comment]
The http/https part was removed by design. I'll add the Copy Link...

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/2770
