### ISSUE TITLE
Create 24 hour mock meeting testing channel

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2766]
There very much needs to be a https://meet.jit.si/mock-meeting channel created,
where a simulated meeting running 24 hours a day should be running, with e.g., the presidents of Russia, China, USA, etc. taking turns speaking, or whatever, in one minute loops.

Otherwise there is **no way** for users to test **hardly any** issues until waiting for **certain disaster** at their first **real meeting**.

No, most users don't have a room full of office mates available to help out.

Thank you!

**Comment by jidanni** [comment]
(One would think
> Just use the jitsi-meet app on your cellphone and jitsi-meet on your computer at the same time.

would work. Well with only one ADSL line, we are using double the upstream bandwidth vs. my proposed test channel, so we will see horrible results, making it look like jitsi-meet will not be usable.)

**Comment by damencho** [comment]
> would work. Well with only one ADSL line, we are using double the upstream bandwidth vs. my proposed test channel, so we will see horrible results, making it look like jitsi-meet will not be usable.)

Well, this is not true if you open a meeting from the same network. Those two devices will connect p2p and your line will not be used for media, will be used only for signalling which can be ignored.

If you want to open a 24-hour meeting, you can do it, there are no restrictions.

**Comment by jidanni** [comment]
One would not see the real situation when not everybody is on the same local network.
Anyway to emulate a 10 person meeting one would need to purchase 10 devices.
