### ISSUE TITLE
Android: fullscreen should be optional

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2771]
Android app should allow turning off full screen, so one could still see the notifications bar.

**Comment by saghul** [comment]
We are not doing that. The expectation is that the full screen real-state is used. You can temporarily show it by swiping up from the bottom of the screen, this is standard Android behavior.

**Comment by jidanni** [comment]
I guess I will have to buy a wristwatch and lay it next to my cellphone.
Or constantly have to swing up and back as you say, to check the time.

**Comment by bgrozev** [comment]
@saghul, most of the apps I use on Android keep the bar at the top visible.

**Comment by jidanni** [comment]
Actually when making an app, the default is that, what, 5% of the screen
still visible to the user. So he/she can still keep track of his/her
battery, clock, etc. That the app demands 100%, no matter what, takes
special programming.

OK I ask you, why not do the same on desktop?

**Comment by torugor** [comment]
I am trying to put jitsi in a fragment so that i can still have control of other functions during jitsi conference but the behaviour of jitsi makes it impossible...it takes all screen. 
How can i put jitsi in a fragment so that i can still have another fragment working on my android app in the same activity?

**Comment by IggyBlob** [comment]
@torugor I'm trying to do that, too. Have you found a way to configure Jitsi such that parts of the host app are still visible?

**Comment by alariej** [comment]
@saghul Wouldn't it be sensible to add a _Feature Flag_ (https://jitsi.github.io/handbook/docs/dev-guide/mobile-feature-flags) to disable full screen on mobile platforms? It would certainly complement well the existing list of GUI features.

**Comment by saghul** [comment]
@alariej Yes, that would work. We didn't have feature flags back then. A PR would be most welcome!

**Comment by alariej** [comment]
@saghul https://github.com/jitsi/jitsi-meet/pull/8718
