### ISSUE TITLE
How to automate arguments for installation

### ISSUE THREAD

**Issue by Erwyn** [jitsi/jitsi-meet#278]
Hello,

I'm trying to build a Dockerfile to deploy jitsi-meet but I don't know how to pass arguments during the .deb installation so that it does not ask for hostname and certificates.

Any clue?

Regards

**Comment by gpolitis** [comment]
Closing this question as I think it's outside the scope of the project. That said, I believe that If you want to supply an answer to a configuration question but do not want to be prompted for it, then this can be arranged by preseeding the DebConf database with the required information.
