### ISSUE TITLE
JitsiVideoBrigde get error SCTP connection with f518afa8 not ready yet

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#2780]
I checked the log of jitsi, there are many errors like this. What is the error and how to fix it?
Thank you so much.
![image](https://user-images.githubusercontent.com/26251116/38533215-6c23e7b0-3ca2-11e8-80ca-c37b9847426c.png)

![image](https://user-images.githubusercontent.com/26251116/38534105-8cc24cb0-3ca6-11e8-8384-11decb3eea7c.png)

**Comment by c526537207** [comment]
I also encountered this problem, do not know how to solve?

**Comment by shooding** [comment]
For 2 people conference (P2P is working fine).
When 3rd people comes in, switched to SFU mode, the got the same issue here.

JVB 2018-10-05 10:08:04.420 WARNING: [25] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 78db288c not ready yet.
JVB 2018-10-05 10:08:04.421 WARNING: [25] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message

**Comment by saghul** [comment]
Do you see any errors on the JS console?

**Comment by shooding** [comment]
[modules/RTC/TraceablePeerConnection.js] <r._createRemoteTrack>:  TPC[2,p2p:false] overwriting remote track! RemoteTrack[9ab66a1d, video, p2p: false] 9ab66a1d video
n @ Logger.js:125
r._createRemoteTrack @ TraceablePeerConnection.js:744
r._remoteTrackAdded @ TraceablePeerConnection.js:704
e.onaddtrack @ TraceablePeerConnection.js:586

Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
n @ Logger.js:125

getGlobalOnErrorHandler @ JitsiMeetJS.js:535
window.onunhandledrejection @ middleware.js:111
AbstractAudio.js:82 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Comment by shooding** [comment]
Solved by edit /etc/hosts 
make sure you have something like:

127.0.0.1       localhost Dev-VideoConf-Jitsi

@pekubu Could you confirm the method also fix your problem ?

**Comment by rishabhchd19** [comment]
> Solved

It is confirmed that this is the final solution for SCTP connection problem. Finally I also got my problem resolved by this method.

**Comment by albercuba** [comment]
> 
> 
> Solved by edit /etc/hosts
> make sure you have something like:
> 
> 127.0.0.1 localhost Dev-VideoConf-Jitsi
> 
> @pekubu Could you confirm the method also fix your problem ?

@shooding what is Dev-VideoConf-Jitsi in your case?

**Comment by shooding** [comment]
@albercuba 
It works. For example, if your hostname running the service is myvideo-conf.com

$hostnamectl set-hostname myvideo-conf.com
$/etc/init.d/jitsi-videobridge restart

**Comment by albercuba** [comment]
Ok thanks

**Comment by fgrosse** [comment]
I just installed jitis using the docker-compose way via https://github.com/jitsi/docker-jitsi-meet and see the same issues in the logs. As far as I can tell (as a jitsi newcomer) everything seems to work fine but I'm uncertain why I have these warnings in my log messages.

```
JVB 2020-03-27 13:30:08.255 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with c8354e13764ab732 not ready yet.
JVB 2020-03-27 13:30:08.258 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2020-03-27 13:30:08.259 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with b7d7dfc363122409 not ready yet.
JVB 2020-03-27 13:30:08.263 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2020-03-27 13:33:09.842 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd6a7fbc178681bd not ready yet.
JVB 2020-03-27 13:33:09.845 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
…
```

I thought maybe it was related to https://github.com/jitsi/docker-jitsi-meet/issues/307 but I tried with 3 participants without any problem. Maybe somebody can explain what this error message actually means so I can investigate some more on my own?
