### ISSUE TITLE
Can not see anyone else

### ISSUE THREAD

**Issue by tfraley** [jitsi/jitsi-meet#279]
It seems I am having a few issues 

OS: Ubuntu vivid server 15.0.4 (fresh install)
Followed the quick install directions from https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
Chrome v 42.0.2311.90 (64-bit)
Client machines connecting: Mac's running Yosemite locally and remotely

It seems I can connect via the webpage fine, however no one can see each other. 
I've also tried the option invite others and get the output 'Your conference is currently being created

**Comment by gpolitis** [comment]
Most probably some component isn't configured correctly. Could you please post the log from the browser's JavaScript console?

**Comment by tfraley** [comment]
@gpolitis thanks for looking into this for me. 

My console output in chrome is 

XMLHttpRequest cannot load https://hangout/http-bind. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://hangout.homeip.net' is therefore not allowed access.
app.bundle.js?v=63:17216 Strophe: request id 3.3 error 0 happenedStrophe.log @ app.bundle.js?v=63:17216
app.bundle.js?v=63:17212 Strophe: request errored, status: 0, number of errors: NaN
lifewithtech:1 XMLHttpRequest cannot load https://hangout/http-bind. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://hangout.homeip.net' is therefore not allowed access.
app.bundle.js?v=63:17216 Strophe: request id 4.4 error 0 happenedStrophe.log @ app.bundle.js?v=63:17216Strophe.error @ strophe.min.js?v=1:1Strophe.Bosh._onRequestStateChange @ strophe.min.js?v=1:1
app.bundle.js?v=63:17212 Strophe: request errored, status: 0, number of errors: NaN

**Comment by tfraley** [comment]
FYI https://hangout.homeip.net is an internal address

**Comment by tfraley** [comment]
Ok just did a fresh install, when it asks for host name i was putting "hangout"  this time I put  "hangout.homeip.net" and things seem to be fine.
