### ISSUE TITLE
Latest jitsimeet Javascript error

### ISSUE THREAD

**Issue by chandrantwins** [jitsi/jitsi-meet#2793]
Hi Expert.
My instance is keep on disconnecting and try to connect again and again

Failed to load resource: the server responded with a status of 405 (Not Allowed)
VM45 lib-jitsi-meet.min.js:2 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 1.1 error 405 happened
    at Object.i.Strophe.log (VM45 lib-jitsi-meet.min.js:2)
    at Object.error (VM45 lib-jitsi-meet.min.js:2)
    at e.Bosh._onRequestStateChange (VM45 lib-jitsi-meet.min.js:2)
n @ VM45 lib-jitsi-meet.min.js:2
VM45 lib-jitsi-meet.min.js:2 [modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 1.1 error 405 happened
n @ VM45 lib-jitsi-meet.min.js:2
VM45 lib-jitsi-meet.min.js:2 

VM45 lib-jitsi-meet.min.js:2 [modules/xmpp/xmpp.js] <t.value>:  XMPP connection dropped!
n @ VM45 lib-jitsi-meet.min.js:2
VM45 lib-jitsi-meet.min.js:2 [modules/statistics/statistics.js] <Function.i.sendAnalyticsAndLog>:  {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.droppedError","error_message":"connection-dropped-error"}}
VM46 app.bundle.min.js:2 [connection.js] <n.l>:  CONNECTION FAILED: connection.droppedError
n @ VM46 app.bundle.min.js:2
VM46 app.bundle.min.js:2 [react/features/overlay/components/AbstractPageReloadOverlay.js] <t.value>:  The conference will be reloaded after 27 seconds.
VM46 app.bundle.min.js:2 [react/features/base/connection/actions.web.js] <>:  connection.droppedError

**Comment by damencho** [comment]
Do you open the bosh url?
Should look like https://meet.jit.si/http-bind

**Comment by chandrantwins** [comment]
My jicofo is not running .. Please help me

● jicofo.service - Jicofo
   Loaded: loaded (/etc/systemd/system/jicofo.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-04-12 07:59:22 UTC; 3min 11s ago
 Main PID: 1451 (code=exited, status=143)

Apr 12 07:57:22 ip-172-31-37-193 jicofolog[1451]: Jicofo 2018-04-12 07:57:22.191 INFO: [25] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() XMPP provider Jabber:focus@auth.jitsi.amallu.xyz/focus9692249407@localhost connected (JID
Apr 12 07:57:53 ip-172-31-37-193 jicofolog[1451]: Jicofo 2018-04-12 07:57:53.071 INFO: [41] org.jitsi.jicofo.ComponentsDiscovery.discoverServices().267 New component discovered: jitsi-videobridge.jitsi.amallu.xyz, IQ Stanza (query jabber
Apr 12 07:57:53 ip-172-31-37-193 jicofolog[1451]: Jicofo 2018-04-12 07:57:53.071 INFO: [41] org.jitsi.jicofo.BridgeSelector.addJvbAddress().241 Added videobridge: jitsi-videobridge.jitsi.amallu.xyz v: IQ Stanza (query jabber:iq:version)
Apr 12 07:57:53 ip-172-31-37-193 jicofolog[1451]: Jicofo 2018-04-12 07:57:53.071 WARNING: [41] org.jitsi.jicofo.BridgeSelector.addJvbAddress().253 No pub-sub node mapped for jitsi-videobridge.jitsi.amallu.xyz
Apr 12 07:57:53 ip-172-31-37-193 jicofolog[1451]: Jicofo 2018-04-12 07:57:53.075 INFO: [56] org.jitsi.jicofo.JvbDoctor.log() Scheduled health-check task for: jitsi-videobridge.jitsi.amallu.xyz
Apr 12 07:59:21 ip-172-31-37-193 systemd[1]: Stopping Jicofo...
Apr 12 07:59:22 ip-172-31-37-193 systemd[1]: jicofo.service: Main process exited, code=exited, status=143/n/a
Apr 12 07:59:22 ip-172-31-37-193 systemd[1]: Stopped Jicofo.
Apr 12 07:59:22 ip-172-31-37-193 systemd[1]: jicofo.service: Unit entered failed state.
Apr 12 07:59:22 ip-172-31-37-193 systemd[1]: jicofo.service: Failed with result 'exit-code'.
lines 1-15/15 (END)

**Comment by chandrantwins** [comment]
Its loading same as your link.. what else do i need to check damencho
https://jitsi.amallu.xyz/http-bind

**Comment by damencho** [comment]
Running fine now. The only problem is that tcp 4443 and udp 10000 is not reaching your jvb. You have correctly configured jvb as said in: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
But seems those ports are not forwarded to the jvb machine.
