### ISSUE TITLE
no message on android after kickout

### ISSUE THREAD

**Issue by tanvir8269** [jitsi/jitsi-meet#2797]
Hi guys, 
want to ask how come no message shown, when someone joined mobile (android/ios) gets kicked out?
i want to show a message when user from mobile gets kicked out. Can anyone give me a direction on where to start?

**Comment by saghul** [comment]
We haven't gotten around showing that error yet. I can't really give you guidance since we haven't yet decided how the UI for those errors is going to look like, sorry.

**Comment by Gaurav-CareMonitor** [comment]
hi @saghul , Any updates on this?
