### ISSUE TITLE
console.error:"[_filename]","<_addOrRemoveAudioElement>:"

### ISSUE THREAD

**Issue by CYBoys** [jitsi/jitsi-meet#2804]
When the hold jitsiMeetView controller is destroyed,
screen print: console.error:"[_filename]","<_addOrRemoveAudioElement>:","_REMOVE_AUDIO_ELEMENT:no sound for id:PARTICIPANT_JOINED_SOUND"

**Comment by Base2526** [comment]
Hi friend.
You fix the problem also.
