### ISSUE TITLE
If you want to configure the video meeting for 6-8 people, what is the bandwidth of the service?

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2821]
If you want to configure the video meeting for 6-8 people, what is the bandwidth of the service?

**Comment by damencho** [comment]
Very rough estimates are 5Mbits up/down per participant(1080p). This means a conference with 8 people, all running chrome and simulcast is enabled (this is by default), this conference can use around 40 Mbits upload and 40 Mbits download on the server.
If you add Firefox to the picture, where we do not have simulcast enabled it will add additional 5MBit to upload to the server for every participant(like 35Mbit more for one FF in this 8 person conference) and for download on every other participant 5 Mmbit will be added.
But this is very rough estimates and all depends on client networks, the resolution used ...
