### ISSUE TITLE
CONFERENCE FAILED: conference.setup_failed 

### ISSUE THREAD

**Issue by chandrantwins** [jitsi/jitsi-meet#2822]
Hi Team,
Please help me resolve this issue

react-dom.production.min.js:98 [conference.js] <e.value>:  CONFERENCE FAILED: conference.setup_failed Error: ICE fail
    at r.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:877)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TraceablePeerConnection.js:746)

Thanks
Chandran Nepolean

**Comment by damencho** [comment]
Is this meet.jit.si or your own deployment? Is this in p2p or in a call using jvb (more than two participants)?

**Comment by chandrantwins** [comment]
Hi Jitsi users,

I have solved this problem in following way
I checked firewall status inside server using this command
1) sudo ufw status

Its not listed 10000-20000 udp and 4443 TCP. so i have added here. it started to works and 

2)  in /etc/jitsi/videobridge/sip.communicator file i added Public and private ips of my server.

Thanks damencho for your timing

**Comment by WildDylan** [comment]
@chandrantwins can you give your config file ?
