### ISSUE TITLE
Can't install sharing extension on Chrome

### ISSUE THREAD

**Issue by BEJUIS** [jitsi/jitsi-meet#2840]
Could you tell me why I can't install this extension ? 
Is there a solution to workaround this problem ? Maybe install locally the extension instead of using your web interface to do so ?

![screen_jitsivinci](https://user-images.githubusercontent.com/38525141/38983911-c4b3f01c-43c5-11e8-9e24-f33bc7117f14.PNG)

Thank you in advance

**Comment by saghul** [comment]
What error do you see in the browser console?

**Comment by BEJUIS** [comment]
Got 4 different errors in the browser console :

![screen_jitsivinci2](https://user-images.githubusercontent.com/38525141/38990108-4dee8b22-43d9-11e8-9c06-183239b3e26c.PNG)

**Comment by saghul** [comment]
Can you expand the errors? I can't see the full description.

**Comment by BEJUIS** [comment]
Sure ! 
![screen_jitsivinci3](https://user-images.githubusercontent.com/38525141/38995223-bf82468e-43e8-11e8-8b08-7f97abd97036.PNG)

**Comment by damencho** [comment]
Is this an extension you have uploaded and modified manifest with your domain? While uploading it have you verified the site?

**Comment by BEJUIS** [comment]
Nope, this extension is needed to start the screen sharing.
And when I try to start the screen sharing, I got this error and the download doesn't start.
I tried on a professional domain and on a public domain, both didn't work.

**Comment by saghul** [comment]
@BEJUIS what @damencho asked is if you uploaded **your own** copy of jidesha to the Chrome store or if you are using ours directly. You need to upload your own extension, with your own domain listed in the manifest, otherwise it won't work. This is a limitation in Chrome.

**Comment by BEJUIS** [comment]
Ok, I got my answer then.
Thanks for your help.
Have a nice day

**Comment by saghul** [comment]
Cheers @BEJUIS. I'm going to close this then, holler if you run into any other problems.
