### ISSUE TITLE
API use > is there any event return to tell the user is on mobile device ?

### ISSUE THREAD

**Issue by DigitalCoder** [jitsi/jitsi-meet#2841]
I've got a problem.
I'm loading API Jitsi meet inside an Iframe but when a user is on mobile device, when he click on the link to download the app, the url destination try to load the link in the Iframe.

I'd like to change the target for example to _blank or new window

**Comment by saghul** [comment]
Isn't the respective store opened automatically?

**Comment by saghul** [comment]
How would changing the target help here?

**Comment by DigitalCoder** [comment]
no it try to open the link inside my iframe
and then the loading is blocked :

> Refused to display 'https://play.google.com/store/apps/details?id=org.jitsi.meet' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

I could disable the information pages with MOBILE_APP_PROMO

but It would have been great just to have the link open in blank page

**Comment by DigitalCoder** [comment]
If someone can make a PR It would be great :D
