### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by leonidas-o** [jitsi/jitsi-meet#2842]
Had a running Jitsi meet on:
`Centos 7`
`nginx 1.12.2`
`prosody 0.10.0`
`java version "1.8.0_77"`
using a Let's encrypt certificate

with the jitsi versions:
Jitsi Meet `jitsi-meet_2514`
Jicofo `jitsi-meet_2514`
Videobridge `997`

After updating it to:
Jitsi Meet `jitsi-meet_2971`
Jicofo `jitsi-meet_2971`
Videobridge `1053`

I get this error:
```
jicofo.sh[4072]: Jicofo 2018-04-19 13:39:03.931 SEVERE: [108] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().345 Failed to connect/login: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
jicofo.sh[4072]: org.jivesoftware.smack.SmackException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
jicofo.sh[4072]: at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1060)
jicofo.sh[4072]: at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
jicofo.sh[4072]: at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
jicofo.sh[4072]: at java.lang.Thread.run(Thread.java:745)
jicofo.sh[4072]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
jicofo.sh[4072]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
jicofo.sh[4072]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
jicofo.sh[4072]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
jicofo.sh[4072]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
jicofo.sh[4072]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
jicofo.sh[4072]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
jicofo.sh[4072]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
jicofo.sh[4072]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
jicofo.sh[4072]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
jicofo.sh[4072]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
jicofo.sh[4072]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
jicofo.sh[4072]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
jicofo.sh[4072]: at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:798)
jicofo.sh[4072]: at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:150)
jicofo.sh[4072]: at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1055)

...
```
I've seen that there are already some issues in here with the same error. But as I'm on centos I'm not able to e.g. delete everything and use the automatic Debian installation script. 

1. Was there a change somewhere between these two versions mentioned above, which could cause this issue?
2. How can I manually solve this on centos?

**Comment by leonidas-o** [comment]
I've tried:
```
ln -sf /etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem /etc/pki/ca-trust/source/anchors/jitsi.fullchain.pem
update-ca-trust
```
but after restarting the jitsi components, prosody and nginx, I get the same errors

**Comment by damencho** [comment]
Make sure your auth domain virtual host definition in prosody looks like:
https://github.com/jitsi/jitsi-meet/blob/master/doc/example-config-files/prosody.cfg.lua.example#L184
the ssl part.
Then do `update-ca-certificates -f`

**Comment by leonidas-o** [comment]
@damencho  That is what my prosody.cfg.lua looks like.
As I'm on centos I do not have `update-ca-certificates`, I've executed `update-ca-trust`. But still the same errors.

```
---------- Server-wide settings ----------
admins = { "focus@auth.jitsi.mydomain.com" }

--- global ssl/tls 
ssl = {
    certificate = "/etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem";
    key = "/etc/letsencrypt/live/jitsi.mydomain.com/privkey.pem";
}

-- Enable use of libevent for better performance under high load
-- For more information see: http://prosody.im/doc/libevent
-- use_libevent = true

-- Disable account creation by default, for security
-- For more information see http://prosody.im/doc/creating_accounts
allow_registration = false

c2s_require_encryption = false

consider_bosh_secure = true

s2s_secure_auth = false

-- Section for VirtualHost example.com
VirtualHost "jitsi.mydomain.com"
        -- enabled = false -- Remove this line to enable this host
        authentication = "ldap"
        ldap_base = "cn=internal,ou=users,dc=FOO,dc=com"
        ldap_server = "localhost:MYPORT"
        ldap_rootdn = "uid=jitsiwhatever,cn=functional,ou=users,dc=FOO,dc=com"
        ldap_password = "MYPASSWORD"
        ldap_filter = "(uid=$user)"
        ldap_scope = "subtree"

        -- Assign this host a certificate for TLS, otherwise it would use the one
        -- set in the global section (if any).
        -- Note that old-style SSL on port 5223 only supports one certificate, and will always
        -- use the global one.
        ssl = {
                certificate = "/etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem";
                key = "/etc/letsencrypt/live/jitsi.mydomain.com/privkey.pem";
        }

        modules_enabled = {
          "bosh";
          "pubsub";
          "saslauth";
          "roster";
          "tls";
          "dialback";
          "auth_ldap";
        }



VirtualHost "auth.jitsi.mydomain.com"
    ssl = {
        certificate = "/etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem";
        key = "/etc/letsencrypt/live/jitsi.mydomain.com/privkey.pem";
    }
    authentication = "internal_plain"
    -- authentication = "internal_hashed"

VirtualHost "guest.jitsi.mydomain.com"
    authentication = "anonymous"


------ Components ------
-- You can specify components to add hosts that provide special services,
-- like multi-user conferences, and transports.
-- For more information on components, see http://prosody.im/doc/components

component_ports = { COMPONENTPORTS }

---Set up a MUC (multi-user chat) room server on conference.example.com:
--Component "conference.example.com" "muc"
Component "conference.jitsi.mydomain.com" "muc"
    restrict_room_creation = "local"

-- Set up a SOCKS5 bytestream proxy for server-proxied file transfers:
--Component "proxy.example.com" "proxy65"

---Set up an external component (default component port is 5347)
--
-- External components allow adding various services, such as gateways/
-- transports to other networks like ICQ, MSN and Yahoo. For more info
-- see: http://prosody.im/doc/components#adding_an_external_component
--
--Component "gateway.example.com"
--      component_secret = "password"

Component "jitsi-videobridge.jitsi.mydomain.com"
    component_secret = "MYSECRET"

Component "focus.jitsi.mydomain.com"
    component_secret = "MYSECRET"
```

**Comment by damencho** [comment]
I'm not familiar with update-ca-trust and where it expects the certificates. But in debian/ubuntu when running update-ca-certificates and calls a script to update the java cert stores (/etc/ssl/certs/java/cacerts) which is used by java, and without the -f switch it was not working.
You can use the unstable debian repo for latest jicofo and then enable in its config: org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true to disable this certificate checking.

**Comment by leonidas-o** [comment]
I think there is just one missing piece here.
I don't know which file to use (from letsencrypt I got my `cert.pem`, `chain.pem`, `fullchain.pem` and `privkey.pem`), or a combination of them or maybe even one file from: https://letsencrypt.org/certificates/

Then, as of https://www.mankier.com/8/update-ca-trust#Source_Configuration , it expects it in `/etc/pki/ca-trust/source/anchors/` and the command should be `update-ca-trust extract`.

After running this command, the file from `/etc/pki/java/cacerts -> /etc/pki/ca-trust/extracted/java/cacerts` is getting updated, I see it on the timestamp.
So I guess I'm just missing the first part, which file/file combination to use. As already mentionend tried with:
`ln -sf /etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem /etc/pki/ca-trust/source/anchors/jitsi.fullchain.pem` and with the `cert.pem` file. But maybe I need to somehow incorporate the `privkey.pem`?

**Comment by damencho** [comment]
The error you see is in jicofo trying to connect to auth.your.domain.com, it has nothing to do with lets encrypt. The debian packaging generate a self-signed certificate for auth.your.domain.com and put it there in the folder of trusted certs and updates all the trusted certs, so that self-signed one will be trusted on that machine. 
This is the script doing that: https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L126

**Comment by damencho** [comment]
I don't know what is your config, but I'm explaining you the default setup. 
Jicofo is connecting to xmpp virtual host auth.some.domain and in prosody, it must be configured prosody to return a certificate with such CN for that host and this certificate must be trusted on the machine running jicofo, so it can trust it when connecting. If you have created that(auth.some.domain) with letsencrypt you don't need the step with update-ca-certificates cause it will be globally trusted. But if you haven't, I already posted a link to the script that does that and you can use the commands from there to generate the self-signed cert.

**Comment by leonidas-o** [comment]
I've posted my full prosody config in here, if you scroll a bit up, you will see it. I know that this is the default setup. FYI: I had jitsi running for at least 2 years now with my setup and sometimes If I could spare some time, I updated it. Since the last update it is not working anymore and I get this error. 

But, good news, I was able to solve it with:

1. I've added *.jitsi.mydomain.com to the letsencrypt cert generation process, so auth.jitsi.mydomain.com and the others are covered
2. In my prosody config, I've commented out all ssl entries (scroll up to see my config):
```
--ssl = {
--        certificate = "/etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem";
--        key = "/etc/letsencrypt/live/jitsi.mydomain.com/privkey.pem";
--    }
```
3. From Prosody 0.10 prosodyctl gains the ability to import and activate certificates in one command: 
`prosodyctl --root cert import /etc/letsencrypt/live/jitsi.mydomain.com/fullchain.pem`

Certificates and their keys are copied to /etc/prosody/certs (can be changed with the certificates option) and then it signals Prosody to reload itself. --root lets prosodyctl write to paths that may not be writable by the prosody user, as is common with /etc/prosody. Multiple hostnames and paths can be given, as long as the hostnames are given before the paths.

This command can be put in cron or passed as a callback to automated certificate renewal programs such as certbot or other Let's Encrypt clients.

**Comment by mwild1** [comment]
Just a note for anyone who may stumble upon this previous comment, the correct way to use 'cert import' is actually to pass it a directory. Passing it the path to fullchain.pem will cause it to incorrectly use this as the key also.

So:

```
prosodyctl --root cert import jitsi.mydomain.com /etc/letsencrypt/live
```

Prosody will find the fullchain.pem and privkey.pem itself.
