### ISSUE TITLE
the third when the user entered, can't see the video

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2849]
I've put the project deployment in public on https://sp.weishichuang.cn, but the third when the user entered, can't see the video, the Advanced configuration and configuration, how to solve?There is nothing wrong with the console.

**Comment by c526537207** [comment]
After viewing the console output, I found that my console did not output the following.
![_20180421143831](https://user-images.githubusercontent.com/31339057/39081341-2546abf6-4572-11e8-9995-d6938acc5bb0.png)

**Comment by dest4** [comment]
"but the third when the user entered" check your syntax. I guess you mean "when the third user entered".

When you increase the number of users from 2 to 3, you probably switch from the "P2P" mode to the "SFU" mode, requiring a central server to pipe the streams. Do you have a TURN server configured?

**Comment by c526537207** [comment]
@dest4 The problem is that the schema cannot be converted, and I have configured the turn server.

**Comment by damencho** [comment]
Moved to https://github.com/jitsi/jitsi-meet/issues/2891
