### ISSUE TITLE
As soon as jitsi conference start, Audio is muted and video is also not appearing  

### ISSUE THREAD

**Issue by kunal-pingalkar** [jitsi/jitsi-meet#2851]
Hi,
**Problem with Jitsi-Meet: Others joining meet cannot see or hear originator**
I have the following problem with making Jitsi-Meet work correctly:
    1. I have installed jitsi-meet on my ubuntu system

    2. As soon as I start a Jitsi conference: 
                 a. I can see my video and 
                 b. the audio is working

    3. As soon as someone joins the conference: 
                 a. They cannot see me 
                 b. They cannot hear me
                 c. The audio button is showing muted to them. 
                 d. Note: I checked the logs but there are no warnings or errors.

    4. All I can see is nothing but info messages in log file.

Please let me know if I am missing any configuration or settings? 
Also can you please let me know, if you need any further information regarding the same.
Any help would be really appreciated,

**Comment by chandrantwins** [comment]
It seems port is not enabled. Please enable 10000-20000 UDP port and 4443 TCP port.

**Comment by c526537207** [comment]
I also encountered the same problem, where to start udp and TCP port? @chandrantwins

**Comment by chandrantwins** [comment]
goto your server login via putty.. 
Type this command
sudo ufw status

Then you will know the status whether port are opened or not. or else another way is give your IP address in the following website to check whether port is opened or not.

https://www.testports.com/

**Comment by kunal-pingalkar** [comment]
Hi @chandrantwins 

All ports are open and ufw status is Status: inactive, 
I am now facing following issue.

*PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target*

Please suggest.

**Comment by chandrantwins** [comment]
This is problem with jdk what you have installed.

**Comment by kunal-pingalkar** [comment]
@chandrantwins 
My java version is.
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by damencho** [comment]
@kunal-pingalkar You need check few things:
- prosody config:
VirtualHost "auth.domain.com"
    ssl = {
        key = "/etc/prosody/certs/auth.domain.com.key";
        certificate = "/etc/prosody/certs/auth.domain.com.crt";
    }
    authentication = "internal_plain"
- You have a link to /etc/prosody/certs/auth.domain.com.crt in /usr/local/share/ca-certificates/
If this all is correct run `update-ca-certificates -f` and then restart jicofo. Do you still see the problem?

**Comment by kunal-pingalkar** [comment]
Hi @damencho 
Thanks much for your support , Looks like the certificate issue is resolved now, but the participant is not able to connect to the conference,  The latest log messages are as follow,

Jicofo 2018-04-26 06:26:28.861 INFO: [52] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: tests@conference.mydomainname.com
Jicofo 2018-04-26 06:26:28.861 INFO: [52] org.jitsi.jicofo.FocusManager.log() Created new focus for tests@conference.mydomainname.com@auth.mydomainname.com conferences count: 1 options:
    channelLastN: -1
    enableLipSync: true
    openSctp: true
    disableRtx: false
Jicofo 2018-04-26 06:26:28.861 INFO: [52] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Lip-sync enabled in tests@conference.mydomainname.com
Jicofo 2018-04-26 06:26:28.861 INFO: [52] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: tests@conference.mydomainname.com
Jicofo 2018-04-26 06:26:29.543 INFO: [36] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@18a44af member=ChatMember[tests@conference.mydomainname.com/86d376c8, jid: null]@1500848973]
Jicofo 2018-04-26 06:26:29.545 INFO: [36] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to tests@conference.mydomainname.com/86d376c8
Jicofo 2018-04-26 06:26:29.545 INFO: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member tests@conference.mydomainname.com/86d376c8 joined.
Jicofo 2018-04-26 06:27:56.529 INFO: [36] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@18a44af member=ChatMember[tests@conference.mydomainname.com/86d376c8, jid: 86d376c8-a8cf-477e-8fa7-13677e0a5695@mydomainname.com/8db2c557-7b16-45dd-a14b-6a8c9a5c601a]@1500848973]
Jicofo 2018-04-26 06:27:56.529 INFO: [36] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2018-04-26 06:27:56.529 INFO: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member tests@conference.mydomainname.com/86d376c8 is leaving
Jicofo 2018-04-26 06:27:56.529 WARNING: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Participant not found for tests@conference.mydomainname.com/86d376c8 terminated already or never started ?
Jicofo 2018-04-26 06:27:56.530 INFO: [36] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: tests@conference.mydomainname.com conference count: 0

**Comment by damencho** [comment]
You tried with two participants that are joining the same room right? 
Can you attach the full logs from both sides.

**Comment by kunal-pingalkar** [comment]
Hi @damencho .
yes, the two participants are joining the same room.

[jicofo.log.zip](https://github.com/jitsi/jitsi-meet/files/1966979/jicofo.log.zip)

**Comment by damencho** [comment]
@kunal-pingalkar are you using a machine behind NAT? 
If that is the case are you sure the ports are forwarded to the machine? https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by kunal-pingalkar** [comment]
HI @damencho 

I have launched this on AWS Cloud ( EC2 Instance ) ,
I have also Allowed / Enabled the UDP 10000 and TCP 443 & 4443 as well on the instance.
Please suggest. 
I am also happy to have a short skype call , if you not mind .

**Comment by damencho** [comment]
@kunal-pingalkar Can you check when you establish a connection do you see the private and public address of the bridge inside setRemoteDescription in webrtc-internals as shown here: https://github.com/jitsi/jitsi-meet/issues/2891#issuecomment-386171481 (the screenshot is with a problem remote description where videobridge advertises only its internal address).

"Allowed / Enabled" I suppose means that you do not have them in some firewall rule on the deployment machine, but also you have forwarded the ports in the security group for that instance.

**Comment by c526537207** [comment]
@kunal-pingalkar How to solve this problem?

**Comment by kunal-pingalkar** [comment]
@c526537207  It is not yet solved, i am still working on this.

**Comment by c526537207** [comment]
@kunal-pingalkar Close the p2p in config.js and try it out.

**Comment by Elmahdi1962** [comment]
i have same problem now

**Comment by luckydawas** [comment]
i have same problem . Start Audio and Video muted while they're not.
How to solve this problem.

**Comment by tj0xin** [comment]
I have the same problem too, the Audio and Video are always muted regardless of the setting in config.js any solution?

**Comment by saghul** [comment]
This issue is 4 years old. The likelihood of your problem being the same is very slim.

Please check our community and otherwise open a new issue providing as much information as possible.

**Comment by tj0xin** [comment]
Hi Saghul, 

The problem still persists, i have posted in community 

https://github.com/jitsi/jitsi-meet/issues/8144

https://community.jitsi.org/t/startwithaudiomuted-true-startwithvideomuted-true-not-working-in-2-0-5390-3/91619/11

https://community.jitsi.org/t/start-with-camera-and-mic-muted/108913/3

**Comment by saghul** [comment]
I do t think that problem and this one are the same. If there an open issue then feel free to follow there, or send a patch if you can help.

**Comment by IamDixit** [comment]
Facing the same problem, audio and video are always shown as muted to the other person.
Is there any solution for this?

**Comment by saghul** [comment]
Please read my 2 earlier comments.

**Comment by vinod325** [comment]
I have faced same problem (Third person joining causes loss of audio for first two participants in jitsi).
Now I have resolve this issue, firstly follow the Jitsi document(https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/) for jitsi installation in ubuntu server.
If you setup and configure your firewall in ufw, please also add 10000 port with custom UDP in ec2 security group then Jitsi meet work fine
