### ISSUE TITLE
React native expection java.lang.UnsatisfiedLinkError: dlopen failed: “/data/data/{package}/lib-main/libgnustl_shared.so” is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by smbteam1** [jitsi/jitsi-meet#2854]
I am trying to integrate Jitsi meet with my existing Android App. I am getting the following exception when initializing React Native Screen:

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.snapdeal.main/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit.

The App is only crashing on **64**-bit devices. 

Please advice!!!

**Comment by bharatghimire005** [comment]
I am also facing the same problem. Please provide the solution
