### ISSUE TITLE
Screenshare

### ISSUE THREAD

**Issue by murugan36** [jitsi/jitsi-meet#2859]
screensharing extension failed to install firefox

**Comment by damencho** [comment]
Which version of Firefox are you using? Is this meet.jit.si or own deployment? Have you check the permissions, there is an icon in the address bar showing the different permissions for the page, what does it say?
<img width="346" alt="screen shot 2018-04-24 at 04 27 05" src="https://user-images.githubusercontent.com/3263098/39178623-d32921ac-4777-11e8-9b1d-19c470d14283.png">

**Comment by murugan36** [comment]
Hi,
Its our own deployment
FF 59.02 windows 10, Video freezes in remote location as soon as screen
share icon is clicked.
In chrome screen share icon is  not available
jitsi-meet installed in ubuntu 16.04

**Comment by damencho** [comment]
Well, this is not "screensharing extension failed to install". 
What version of jitsi-meet are you using? Is it the stable one? Have you tried updating to latest from unstable repo, there was an issue which was recently fixed?
Chrome you need to create an extension for your deployment (http://github.com/jitsi/jidesha) and upload it to google chrome webstore and configure its id in the config.js.
