### ISSUE TITLE
Poor connectivity - massive connectivity issues

### ISSUE THREAD

**Issue by gino909** [jitsi/jitsi-meet#2865]
Dear jitsi, dear community
I am really impressed by this project and we are searching a solution for us and our customers and jitsi would really fit our needs... but unfortunately we are not able to get it working properly...
We tried to install from stable repository as well from the unstable one. we tried on virtual server and now we are trying on phisical with multicore xeon and 32 GB of RAM.
But nothing... everytime poor connectivity, video not working properly, screensharing not working properly etc...
Firewall rules are ok, port 443 tcp and 10000 udp are open, we tried different setting customization but nothing....
Can anyone please help us to setup this piece of software properly?
We are also willed to pay for this help... we believe in open source and we want to get this piece of software working. thank you

**Comment by TheReal1604** [comment]
@gino909 can you expose your system URL here? do you checked if this parameters are set? How much bandwith got your clients? How many participants have you tested?

https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf

Maybe @damencho can give some additional hints to check.

**Comment by gino909** [comment]
Dear jitsi Team.
Is it possible that somebody of you could assist us in setting up jitsi to make it working as it should?
As just explained we are searching a solution for us and for our customers. If we can not get it to work we have to search for other solutions.
As also explained we are also willed to pay for this support.... I am sure you are also willed to make some business :)
Please let me know asap! Thank you
PS. does anyone know how to contact jitsi officially? I did not found any contacts, thank you!

**Comment by gino909** [comment]
Is there anyone running a installation with good quality? Can someone assist us in setting up jitsi?
Please help! Thank you

**Comment by damencho** [comment]
If you loose audio/video when there are more than 2 people, this is a configuration problem have you followed https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration ?

**Comment by xsteadfastx** [comment]
On Di, 19. Jun 06:44, Дамян Минков wrote:
> If you loose audio/video when there are more than 2 people, this is a
> configuration problem have you followed https://github.com/jitsi/jitsi-meet/
> blob/master/doc/quick-install.md#advanced-configuration ?

you mean the NAT_HARVESTER part? we run this local and connect with
local network browsers. shouldnt there be a problem with nat? or maybe i
dont understand webrtc enough. does it need a internet connection? even
if everything is local?

**Comment by damencho** [comment]
You need jvb to advertise correct ip address on which you can connect to. You can check by opening chrome://webrtc-internals and check setRemoteDescription and what ip addresses are advertised for jvb. By default jvb will advertise only its internal address if you have connectivity to that one it should connect.

**Comment by gino909** [comment]
HI, following output has setRemoteDescription

type: offer, sdp: v=0
o=- 1923518516 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS mixedmslabel
a=group:BUNDLE audio video data
m=audio 10000 RTP/SAVPF 111 103 104 126
c=IN IP4 172.17.0.1
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:audio
a=sendrecv
a=ice-ufrag:qhoi1cguq715j
a=ice-pwd:3h52kt5copmuo49927hvbspcgm
a=fingerprint:sha-1 D3:8C:11:54:5E:3A:6F:23:A4:F6:E9:61:B9:AE:98:A6:D9:52:85:1F
a=candidate:1 1 ssltcp 2130706431 172.17.0.1 4443 typ host generation 0
a=candidate:2 1 ssltcp 2130706431 2a01:4f8:xxxx:xxxx::2 4443 typ host generation 0
a=candidate:5 1 udp 2113939711 2a01:4f8:xxxx:xxxx::2 10000 typ host generation 0
a=candidate:3 1 ssltcp 2113932031 136.xxx.xxx.xxx 4443 typ host generation 0
a=candidate:4 1 udp 2113932031 172.17.0.1 10000 typ host generation 0
a=candidate:6 1 udp 2113932031 136.xxx.xxx.xxx 10000 typ host generation 0
a=ssrc:576230996 cname:mixed
a=ssrc:576230996 msid:mixedmslabel mixedlabelaudio0
a=ssrc:576230996 mslabel:mixedmslabel
a=ssrc:576230996 label:mixedlabelaudio0
a=ssrc:3427731585 cname:1b342e68-9367-4c5c-bb72-21aa21fa358a-2
a=ssrc:3427731585 msid:36e4be86-4d12-45ec-bd16-142b2368e1ba-2 d0b9ac9f-0abf-4dc5-aeaa-1da2e824ec08-2
a=rtcp-mux
m=video 10000 RTP/SAVPF 100 107 101 96 99 97
c=IN IP4 172.17.0.1
a=rtpmap:100 VP8/90000
a=rtpmap:107 H264/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:99 rtx/90000
a=rtpmap:97 rtx/90000
a=fmtp:100 x-google-start-bitrate=800
a=fmtp:107 x-google-start-bitrate=800
a=fmtp:101 x-google-start-bitrate=800
a=fmtp:96 apt=100
a=fmtp:99 apt=107
a=fmtp:97 apt=101
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 transport-cc
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 transport-cc
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:qhoi1cguq715j
a=ice-pwd:3h52kt5copmuo49927hvbspcgm
a=fingerprint:sha-1 D3:8C:11:54:5E:3A:6F:23:A4:F6:E9:61:B9:AE:98:A6:D9:52:85:1F
a=candidate:1 1 ssltcp 2130706431 172.17.0.1 4443 typ host generation 0
a=candidate:2 1 ssltcp 2130706431 2a01:4f8:xxxx:xxxx::2 4443 typ host generation 0
a=candidate:5 1 udp 2113939711 2a01:4f8:xxxx:xxxx::2 10000 typ host generation 0
a=candidate:3 1 ssltcp 2113932031 136.xxx.xxx.xxx 4443 typ host generation 0
a=candidate:4 1 udp 2113932031 172.17.0.1 10000 typ host generation 0
a=candidate:6 1 udp 2113932031 136.xxx.xxx.xxx 10000 typ host generation 0
a=ssrc:448557280 cname:mixed
a=ssrc:448557280 msid:mixedmslabel mixedlabelvideo0
a=ssrc:448557280 mslabel:mixedmslabel
a=ssrc:448557280 label:mixedlabelvideo0
a=ssrc:1805103637 cname:1b342e68-9367-4c5c-bb72-21aa21fa358a-2
a=ssrc:1805103637 msid:36e4be86-4d12-45ec-bd16-142b2368e1ba-2 6883ac97-1870-4055-85f5-d8040b01bf31-2
a=rtcp-mux
a=x-google-flag:conference
m=application 10000 DTLS/SCTP 5000
type: offer, sdp: v=0
o=- 1923518516 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS mixedmslabel
a=group:BUNDLE audio video data
m=audio 10000 RTP/SAVPF 111 103 104 126
c=IN IP4 172.17.0.1
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:audio
a=sendrecv
a=ice-ufrag:qhoi1cguq715j
a=ice-pwd:3h52kt5copmuo49927hvbspcgm
a=fingerprint:sha-1 D3:8C:11:54:5E:3A:6F:23:A4:F6:E9:61:B9:AE:98:A6:D9:52:85:1F
a=candidate:1 1 ssltcp 2130706431 172.17.0.1 4443 typ host generation 0
a=candidate:2 1 ssltcp 2130706431 2a01:4f8:211:2d18::2 4443 typ host generation 0
a=candidate:5 1 udp 2113939711 2a01:4f8:211:2d18::2 10000 typ host generation 0
a=candidate:3 1 ssltcp 2113932031 136.243.19.153 4443 typ host generation 0
a=candidate:4 1 udp 2113932031 172.17.0.1 10000 typ host generation 0
a=candidate:6 1 udp 2113932031 136.243.19.153 10000 typ host generation 0
a=ssrc:576230996 cname:mixed
a=ssrc:576230996 msid:mixedmslabel mixedlabelaudio0
a=ssrc:576230996 mslabel:mixedmslabel
a=ssrc:576230996 label:mixedlabelaudio0
a=ssrc:3427731585 cname:1b342e68-9367-4c5c-bb72-21aa21fa358a-2
a=ssrc:3427731585 msid:36e4be86-4d12-45ec-bd16-142b2368e1ba-2 d0b9ac9f-0abf-4dc5-aeaa-1da2e824ec08-2
a=rtcp-mux
m=video 10000 RTP/SAVPF 100 107 101 96 99 97
c=IN IP4 172.17.0.1
a=rtpmap:100 VP8/90000
a=rtpmap:107 H264/90000
a=rtpmap:101 VP9/90000
a=rtpmap:96 rtx/90000
a=rtpmap:99 rtx/90000
a=rtpmap:97 rtx/90000
a=fmtp:100 x-google-start-bitrate=800
a=fmtp:107 x-google-start-bitrate=800
a=fmtp:101 x-google-start-bitrate=800
a=fmtp:96 apt=100
a=fmtp:99 apt=107
a=fmtp:97 apt=101
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 transport-cc
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 transport-cc
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:qhoi1cguq715j
a=ice-pwd:3h52kt5copmuo49927hvbspcgm
a=fingerprint:sha-1 D3:8C:11:54:5E:3A:6F:23:A4:F6:E9:61:B9:AE:98:A6:D9:52:85:1F
a=candidate:1 1 ssltcp 2130706431 172.17.0.1 4443 typ host generation 0
a=candidate:2 1 ssltcp 2130706431 2a01:4f8:211:2d18::2 4443 typ host generation 0
a=candidate:5 1 udp 2113939711 2a01:4f8:211:2d18::2 10000 typ host generation 0
a=candidate:3 1 ssltcp 2113932031 136.243.19.153 4443 typ host generation 0
a=candidate:4 1 udp 2113932031 172.17.0.1 10000 typ host generation 0
a=candidate:6 1 udp 2113932031 136.243.19.153 10000 typ host generation 0
a=ssrc:448557280 cname:mixed
a=ssrc:448557280 msid:mixedmslabel mixedlabelvideo0
a=ssrc:448557280 mslabel:mixedmslabel
a=ssrc:448557280 label:mixedlabelvideo0
a=ssrc:1805103637 cname:1b342e68-9367-4c5c-bb72-21aa21fa358a-2
a=ssrc:1805103637 msid:36e4be86-4d12-45ec-bd16-142b2368e1ba-2 6883ac97-1870-4055-85f5-d8040b01bf31-2
a=rtcp-mux
a=x-google-flag:conference
m=application 10000 DTLS/SCTP 5000
c=IN IP4 172.17.0.1
a=setup:actpass
a=mid:data
a=ice-ufrag:qhoi1cguq715j
a=ice-pwd:3h52kt5copmuo49927hvbspcgm
a=fingerprint:sha-1 D3:8C:11:54:5E:3A:6F:23:A4:F6:E9:61:B9:AE:98:A6:D9:52:85:1F
a=candidate:1 1 ssltcp 2130706431 172.17.0.1 4443 typ host generation 0
a=candidate:2 1 ssltcp 2130706431 2a01:4f8:211:2d18::2 4443 typ host generation 0
a=candidate:5 1 udp 2113939711 2a01:4f8:211:2d18::2 10000 typ host generation 0
a=candidate:3 1 ssltcp 2113932031 136.243.19.153 4443 typ host generation 0
a=candidate:4 1 udp 2113932031 172.17.0.1 10000 typ host generation 0
a=candidate:6 1 udp 2113932031 136.243.19.153 10000 typ host generation 0
a=sctpmap:5000 webrtc-datachannel 1024
a=setup:actpass
a=mid:data
a=ice-ufrag:qhoi1cguq715j
a=ice-pwd:3h52kt5copmuo49927hvbspcgm
a=fingerprint:sha-1 D3:8C:11:54:5E:3A:6F:23:A4:F6:E9:61:B9:AE:98:A6:D9:52:85:1F
a=candidate:1 1 ssltcp 2130706431 172.17.0.1 4443 typ host generation 0
a=candidate:2 1 ssltcp 2130706431 2a01:4f8:xxxx:xxxx::2 4443 typ host generation 0
a=candidate:5 1 udp 2113939711 2a01:4f8:xxxx:xxxx::2 10000 typ host generation 0
a=candidate:3 1 ssltcp 2113932031 136.xxx.xxx.xxx 4443 typ host generation 0
a=candidate:4 1 udp 2113932031 172.17.0.1 10000 typ host generation 0
a=candidate:6 1 udp 2113932031 136.xxx.xxx.xxx 10000 typ host generation 0
a=sctpmap:5000 webrtc-datachannel 1024

as I understand is advertising all IPv4 and IPv6 addresses. The only thing may could be wrong is the c=IN IP4 172.17.0.1 which is advertising a docker internal ip address.

The jitsi is not behind a nat and has IPv4 and IPv6 public addresses.

**Comment by mbaudin47** [comment]
I have the same kind of "connectivity issue". This seems to be the same as in #1930 

My guess is that I am behind a proxy server, which prevents from sending the data. Weirdly enough, the screen sharing service provided by join.me works.
