### ISSUE TITLE
cannot see the chat window from the mobile app

### ISSUE THREAD

**Issue by Sesquatch** [jitsi/jitsi-meet#2869]
Don't know if this is a bug, or not-yet-implemented feature. I cannot see the chat of others, when using my android phone (samsung S8, android 8.0.0) and the jitsi meet app.
When joining the same room from a destktop browser, the chat text is visible.

**Comment by randymuhroji** [comment]
+1

**Comment by olastor** [comment]
+1

**Comment by olastor** [comment]
+1

Really appreciate the Jitsi Service on different platforms.

**Comment by binarious** [comment]
This issue still persists. @saghul Is anything planned to support the chat on mobile devices?

**Comment by damencho** [comment]
Yep a new release will bring it in. This is already available in the source code. The new release we hope, to come soon. We are currently fighting with some issues around publishing the app in the stores.

**Comment by binarious** [comment]
@damencho Any news on this one?

**Comment by damencho** [comment]
If you are talking about be able to chat from the mobile app, this is already in the play/app store. So I'm closing the issue.
