### ISSUE TITLE
Jitsi repository certificate errors

### ISSUE THREAD

**Issue by keantoken** [jitsi/jitsi-meet#2874]
Hello. Today I tried to update and got "no release file" errors. I asked for help on the Debian IRC and was told this was due to the Jitsi repos being HTTPS - to use HTTPS repos you need to have apt-transport-https installed.

It was suggested to just use http for the Jitsi repos, since the security is already in the signed release files, and https doesn't add any extra security. 

I think the repo install instructions here should be updated with instructions which will not eventually result in certificate errors and failure to update:

https://jitsi.org/downloads/

**Comment by keantoken** [comment]
I didn't have apt-transport-https, that is why I had errors (I could be wrong about this but it seems to be the case). It would make sense to let users know they should install apt-transport-https. Otherwise they may fail to update one day, and reinstall ca-certificates to fix it without actually solving the problem.

**Comment by saghul** [comment]
This already documented: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#update-the-package-lists
