### ISSUE TITLE
desktop sharing error

### ISSUE THREAD

**Issue by chandrantwins** [jitsi/jitsi-meet#2877]
Hi Jitsi team,

Please guide me to solve this problem

"Failed to install the extension from 
https://chrome.google.com/webstore/detail/aoebealjjefddaafjpaokofchfnpkend"
name
:
"gum.chrome_extension_installation_error"
stack
:
"Error↵    at new r (https://jitsi.amallu.xyz/libs/lib-jitsi-meet.min.js?v=139:2:84745)↵    at Object.handleExtensionInstallationError (https://jitsi.amallu.xyz/libs/lib-jitsi-meet.min.js?v=139:2:816688)↵    at Installer.onInstallResponse (extensions::webstore:72:22)"
__proto__
:
Error

**Comment by damencho** [comment]
Is that extension uploaded? https://chrome.google.com/webstore/detail/aoebealjjefddaafjpaokofchfnpkend gives me 404. You need to make sure the domain in the manifest is correct and when uploading to verify the site.
