### ISSUE TITLE
Option to disable mic AGC

### ISSUE THREAD

**Issue by ralgozino** [jitsi/jitsi-meet#2878]
Hello! We are loving jit.si! but we have a minor issue while having conferences.

Please, add an option to disable the microphone automatic gain control. It makes sense while using a laptop, but in our case we are using videoconference rooms with very good mics and audio in general, and the AGC makes the mic work odd. We can adjust de mic gain in hardware.

Thanks in advance!

**Comment by damencho** [comment]
You can try joining the conference passing the param disableAGC=true, like:
https://meet.jit.si/somemeeeting#config.disableAGC=true

**Comment by ajaydata** [comment]
We have iur own jitsi instance, I s there any way to monitor number of calls made, room, issues, participants, client used, errors etc.

Where so we get the CDR basically.

On 26-Apr-2018 at 19:31:06
Дамян Минков 'notifications@github.com' wrote:

You can try joining the conference passing the param disableAGC=true, like:
https://meet.jit.si/somemeeeting#config.disableAGC=true

**Comment by ralgozino** [comment]
@damencho awesome! will try it ASAP. Thanks!!
