### ISSUE TITLE
Letsencrypt renew certs doesn't work in standalone installation (by quick install guide)

### ISSUE THREAD

**Issue by le0pard** [jitsi/jitsi-meet#2885]
After install by "Jitsi Meet quick install", letsencrypt renew doesn't work.

https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#generate-a-lets-encrypt-certificate

**1. First problem**. Crontab task:

```
#!/bin/bash
/usr/local/sbin/certbot-auto renew >> /var/log/le-renew.log
```

Get this error:

```
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/***.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer None
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for ***
Cleaning up challenges
Attempting to renew cert (***) from /etc/letsencrypt/renewal/***.conf produced an unexpected error: Problem binding to port 443: Could not bind to IPv4 or IPv6.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/***/fullchain.pem (failure)

-------------------------------------------------------------------------------

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/***/fullchain.pem (failure)
-------------------------------------------------------------------------------
1 renew failure(s), 0 parse failure(s)
```

**Reason**: jitsi already busy 443 port.

**2. Second problem**:

After:
```
service jitsi-videobridge stop
```

and update certs jitsu-meet still not using renewal certs.

**Reason** - no phase for converting ssl keys again https://github.com/jitsi/jitsi-meet/blob/master/resources/install-letsencrypt-cert.sh#L89-L98

**Comment by damencho** [comment]
Some time ago I was working on this to update the renew procedure but didn't have time to fix/test it.
https://github.com/jitsi/jitsi-meet/tree/letsencrypt-renew
But now based on your comments I see that my renew script is missing the phase for converting ssl keys. So this needs updating. 
This is still on my TODO list, but not sure when I will get to it. Any help is welcome.

**Comment by tansaku** [comment]
short term fix for this seems to be re-running the certificate install:

```
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```

@damencho any tips on where to look int the repo to help you?  some changes required in https://github.com/jitsi/jitsi-meet/blob/letsencrypt-renew/resources/install-letsencrypt-cert.sh ?  I guess we can see the changes you made so far in:

https://github.com/jitsi/jitsi-meet/compare/letsencrypt-renew

**Comment by ahayes** [comment]
It is a shame this has been marked wontfix by a bot and left untouched. You can't even use jitsi-meet without ssl enabled and an auto-renewing certbot seems pretty important for a turnkey solution like jitsi.

**Comment by kamihacker** [comment]
this can be worked-around in Debian / Ubuntu if you use the built-in certbot packages and scripts

I've tried it and it works

**Comment by LatinSuD** [comment]
As a workaround modify `/etc/cron.weekly/letsencrypt-renew` to look like this:

```
#!/bin/bash
service jitsi-videobridge stop
/usr/local/sbin/certbot-auto renew >> /var/log/le-renew.log
service jitsi-videobridge start
```

It will just stop the service briefly during the renewal.
