### ISSUE TITLE
JVB can't connect

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2891]
There is no problem with p2p connection. When you connect with JVB, you can't see the other video, and the audio is not good. What is the problem?[sp.weishichuang.cn](url)

**Comment by c526537207** [comment]
I use the domain name to build, the log is as follows.
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1957429/jicofo.log)
[Uploading jvb.log…]()

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by damencho** [comment]
I was checking your deployment I still see jvb is not advertising your public IP.
Can you paste your jvb's sip-communicator.properties file?

**Comment by damencho** [comment]
And please stop opening issues without closing the previous one.

**Comment by damencho** [comment]
@c526537207 jicofo seems to be not connected at the moment. Can you do:
rm /var/log/jitsi/jicofo.log
/etc/init.d/jicofo restart
And then attach here /var/log/jitsi/jicofo.log.

I'm sure jicofo was running fine the previous time I tested your deployment, cause I was seeing the remote offers coming from it, where I was seeing only the 172.... address advertised by jvb.

**Comment by c526537207** [comment]
@damencho 
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1965690/jicofo.log)

**Comment by damencho** [comment]
Can you check that in /var/lib/prosody/ and /etc/prosody/certs/ you have auth.sp.weishichuang.cn.crt and auth.sp.weishichuang.cn.key files. 
In /etc/prosody/conf.avail/sp.weishichuang.cn.cfg.lua you have the following virtual host definition:
```
VirtualHost "auth.sp.weishichuang.cn"
    ssl = {
        key = "/etc/prosody/certs/auth.sp.weishichuang.cn.key";
        certificate = "/etc/prosody/certs/auth.sp.weishichuang.cn.crt";
    }
    authentication = "internal_plain"
```
If all of the above is correct execute:
```
update-ca-certificates -f
/etc/init.d/jicofo restart
```
And try again, is it working now?

**Comment by c526537207** [comment]
@damencho We've already configured it, but we can't.Because the certificate displayed in quick installation is not safe, I have given the domain name to my application certificate. Does this have any impact?

[sp.weishichuang.cn.cfg.lua.txt](https://github.com/jitsi/jitsi-meet/files/1965746/sp.weishichuang.cn.cfg.lua.txt)

**Comment by damencho** [comment]
Yes, it does. The certificate for auth domain should have CN=auth.sp.weishichuang.cn. That domain doesn't matter outside of the deployment it is internal and there is no need for a valid certificate for it. During installation a self-signed certificate is created then it is added to the trusted certificates on the machine(https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L138) and the `update-ca-certificates -f` command updates the java store which java and jicofo then used to verify this certificate. So if the certificate is changed and is not the one generated by the installation(https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L131), the instructions above will not work. You can always use the command `prosodyctl cert generate auth.sp.weishichuang.cn` to generate new one, then you can follow the steps from my previous comment.

**Comment by c526537207** [comment]
@damencho I do not understand your meaning, I use self-signed certificate, should configure where can solve my problem?

**Comment by damencho** [comment]
Have you tried, my instructions?
```
update-ca-certificates -f
rm /var/log/jitsi/jicofo.log
/etc/init.d/jicofo restart
```
And then check again jicofo.logs for the errors? Are they still there?

**Comment by c526537207** [comment]
@damencho 
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1965862/jicofo.log)
There is still an error.My self-signed certificate is only configured in nginx. Does it need to be configured elsewhere?

**Comment by damencho** [comment]
Upgrade to latest version. Then edit /etc/jitsi/jicofo/sip-communicator.properties and add the following line:
org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true
again restart jicofo. This should fix it.
The version of jicofo must be 405.

**Comment by damencho** [comment]
This is normal, now as before I see that jvb is advertising only its internal address:
<img width="712" alt="screen shot 2018-05-02 at 20 41 25" src="https://user-images.githubusercontent.com/3263098/39556910-8baeb0c0-4e49-11e8-91f0-2de683a937f6.png">

You have uploaded sip-communicator.properties.txt and it contains correct settings, is this file with the same name in /etc/jitsi/videobridge folder? It should be without .txt at the end and you need to restart jvb after fixing this.

**Comment by c526537207** [comment]
@damencho Still, JVB can't open, the third person can't display audio and video.Is there anything else that needs to be configured?

**Comment by damencho** [comment]
Did you fix the problem with the config?

**Comment by damencho** [comment]
Yeah, I see it now, you have fixed it.

**Comment by damencho** [comment]
Now, I don't know your setup there if the 42..... is some kind of router you need to do port forwarding. You need to forward udp port 10000 and tcp port 4443 to go to the jitsi-meet machine(172.....). This is described here https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration. You have already done that for port 443.

**Comment by c526537207** [comment]
@damencho 42 is the domain name corresponding to the public network IP, 172 is the server's private network IP, this does not need to do port mapping.

**Comment by damencho** [comment]
Well, apparently when I'm testing it, there is no port forwarding and that is why it doesn't work for me. 
Where is this, is this on Amazon AWS? DigitalOcean? OVH? or some other VM provider?
Which machine has the 42... address, it must be something, whether it is your home router, office router, some server before your deployment, provider of the VM, something?

**Comment by c526537207** [comment]
Services deployed on aliyun server (China). @damencho

**Comment by damencho** [comment]
I'm not familiar with aliyun server, but as most providers, you should be able to forward ports. Port 443 is already forwarded, so you need to forward and the other two ports.

**Comment by damencho** [comment]
INTERNET ------ 47.92.73.182 ------- 172.26.204.76
If I open your site a packet travels through the Internet and hits port 443 on 47.X.X.X which then forward the packet to 172.X.X.X. The same should happen with media, the port used for media are 4443 and 10000.
I don't understand what mapping do you mean. The ports can be changed but this will not help, as no packet will reach the machine. 
Here is a documentation how to do that: https://www.alibabacloud.com/help/doc-detail/25471.htm?spm=a2c5q.11423531.0.0.2be9786aQtmxbb
If this cannot help you, call their support to ask to help you forwarding udp 10000 and tcp 4443, without that port forwarding no media will flow between participants.

**Comment by c526537207** [comment]
@damencho Finally found the problem, is I use server network environment problem, it only private network card, all request must be forwarded to the private network card processing, unable to request directly to the private network card.During the installation configuration, only the port of the private network IP was monitored, causing us to use the problem that the public network IP cannot request.Is it possible to modify the installation process so that the ports are monitored on both the private and public networks?
