### ISSUE TITLE
Share one entire screen, but not all screens

### ISSUE THREAD

**Issue by amenk** [jitsi/jitsi-meet#2894]
I have multiple screens. It is currently (using https://meet.jit.si/) only possible to share a window, a chrome tab or the entire desktop (all screens).

What seems to be missing is to share only one screen.

Sharing one application window is not what I want here, because I often switch between two application windows on the same screen.

Is this possible to implement or a limitation by the browser?

(I tried it on Chrome 66, Ubuntu 16.04)

**Comment by amenk** [comment]
Same problem in Ubuntu 18.04

Would a workaround on the side of jitsi-meet be possible, where the use still can select a sub-rectangle of the originally shared full screen / full desktop?

**Comment by bgrozev** [comment]
I don't think we can work around this in jitsi-meet. The chrome API only allows us to specify the types of sources to include [(tabs, separate applications, or screens)](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L151). The detection of the actual screens that are available happens internally in chrome.

**Comment by rmorabia** [comment]
I can attest to this happening in Arch & Firefox, as well. Is there any browser where this would be possible in Linux? I would happily switch.

**Comment by bgrozev** [comment]
> I can attest to this happening in Arch & Firefox, as well. Is there any browser where this would be possible in Linux? I would happily switch.

You can try chromium or chrome

**Comment by saghul** [comment]
Closing since there is nothing we can do on meet.

**Comment by JThoennes** [comment]
Here is a possible workaround from the above Chromium bug list:

> Comment 19 by linuxcom...@gmail.com, Feb 6
As a workaround I use ffmpeg virtual webcam. I have written a script that asks you which individual screen you wish to share.
Chromium will not automatically add virtual webcam to its list (its another bug), so to workaround it, I prorammatically reinsert my internal laptop webcam.
I have shared these scripts in my repo called hliss (Hangouts Linux Individual Screen Share). It is located here: https://github.com/Ashark/hliss

**Comment by george-viaud** [comment]
A very clunky workaround I've used with this and other web-based screen share on Ubuntu 18.04 (and likely works with others) is to install OBS, set it up to view the monitor you wish to share, move it off to another monitor and share that app...  

This is very clunky but essentially achieves the same effect as JThoennes' solution.

**Comment by nitomartinez** [comment]
Another workaround option similar to @JThoennes  and @george-viaud that I use is using Xephyr:

Example:
`
# Get list of monitors via xrandr --listmonitors
Xephyr -output DP1 :1 &
export DISPLAY=:1
firefox &
recordmydesktop -o /tmp/myrecording.ogv
# Any other items you want on screen DP1
`

**Comment by gerazov** [comment]
@george-viaud thanks for the tip! This also helped me with single screen sharing.

How to you set OBS to just show the screen with no interface?

The best I could do is get rid of all the docks and status bar and full screen it. This leaves a menu though:
![image](https://user-images.githubusercontent.com/15214418/76785369-9bde4c80-67b5-11ea-80f9-a04cb5e145f1.png)

If I select Fullscreen Projector (Preview) I get the whole screen but then it stays on top of other applications.

**Comment by nitomartinez** [comment]
I haven't used obs.

With recordmydesktop this works for me:

<pre>
export DISPLAY=:1
recordmydesktop  --on-the-fly-encoding -o /mnt/$(date +%Y%m%d-%H:%M:%S-%Z)-course.ogv
</pre>

**Comment by gerazov** [comment]
Ok finally made it work. Here are the steps required when using OBS:

1. Run OBS Studio, 
2. In `File > Settings` uncheck `Make projectors always on top`
![image](https://user-images.githubusercontent.com/15214418/76837779-68da9e00-6833-11ea-8479-b5aa791c20e4.png)
3. Now right-click on the screen and start `Windowed projector (Preview)`*
4. Screen share the `Windowed projector (Preview)` application

----
* Note OBS keeps the `Fullscreen projector (Preview)` always on top https://github.com/obsproject/obs-studio/issues/2514

**Comment by nitomartinez** [comment]
Nice !!!!

**Comment by MarrekNozka** [comment]
> Another workaround option similar to @JThoennes and @george-viaud that I use is using Xephyr:
> 
> Example:
> 
> ```
> # Get list of monitors via xrandr --listmonitors
> Xephyr -output DP1 :1 &
> export DISPLAY=:1
> firefox &
> recordmydesktop -o /tmp/myrecording.ogv
> # Any other items you want on screen DP1
> ```
> 
> On jitsi, share the app: Xephyr.

I use this:

```bash

Xephyr :1 -screen 1280x980 & 
XPID=$!

export DISPLAY=:1

xfce4-panel &
PANELPID=$!

openbox

kill $PANELPID
kill $XPID

```

**Comment by JoKeyser** [comment]
@gerazov's hack with OBS is nice because you can even compose your webcam view over the shared screen, or more advanced stuff!

**Comment by ulab** [comment]
> you can even compose your webcam view over the shared screen

@JoKeyser Did you know that you can enable your cam during screen sharing for a Picture-in-Picture mode?

**Comment by pas-calc** [comment]
this workaround works for me

`fplay -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+1366,0`

share second screen (create window that captures the contents of second display)
laptop screen width: 1366 (second screen starts on the right of that, see xrandr or display settings)
second screen resolution: 1920x1080

put ffplay window in background, do not minimize
then select the appropriate window from the dropdown list in Firefox browser
