### ISSUE TITLE
make android app more accessible for blind users.

### ISSUE THREAD

**Issue by grishakonzalaev** [jitsi/jitsi-meet#2895]
Make readable buttons. My TB can read only hangup button. all buttons excluding "hangup" Talkback recognize but not read as unmarket button or simply text. Only play swipe sound with novoice.

**Comment by saghul** [comment]
Hi there! Thanks for reaching out! We are currently working on a heavy refactor of the mobile buttons and they will all contain accessibility labels, in alignment with web's aria labels. I don't have an ETA for when this will be available, but it's being actively worked on, as part of other efforts.

**Comment by julie-nguyen-projects** [comment]
Hello, it appears the application isn't easily usable for blind users yet. They can't use their voice assistant to log in a room. Could you see if it's improvable ?

**Comment by nisses** [comment]
It's the year 2022 and there are still no labels for blind people in Android application. You should be ashamed.
