### ISSUE TITLE
audio not working most of the time, webrtc trouble?

### ISSUE THREAD

**Issue by quite** [jitsi/jitsi-meet#290]
Audio recording is working very intermittently on my system. Previously chromium 42, right now 43. I see my own video, and others can see me. But webrtc (?) on my side doesn't seem to be able to record any audio. I've got it working "a few" times, by restarting chromium. And usually it will keep working as long as that chromium session is alive... But I've by no means found a consistent way of getting it to work, other than these random restarts.

I've found the following url, which is a test for webrtc audio. I'd say that when this page gives me feedback of my own voice/noise, audio also works on meet.jit.si

  http://webrtc.github.io/samples/src/content/getusermedia/audio/

I don't know at all where I'd start debugging this. It's not exactly my field of expertise, and unfortunately I don't really have the time :(

This is chromium on a fresh Arch Linux system, x86_64.

**Comment by gpolitis** [comment]
Does your mic work ok for you otherwise? Can you for example record an audio file and play it back correctly?

**Comment by quite** [comment]
Yes, no problem with microphone. When webrtc doesn't record audio, I can indeed do `rec foo.wav` in a terminal and the resulting file has my noise.

**Comment by yanas** [comment]
@quite please send the js console log, so that we could have a look at the details.

**Comment by bgrozev** [comment]
Re-open if needed.
