### ISSUE TITLE
How do I get the participants count in welcomepage 

### ISSUE THREAD

**Issue by landlove** [jitsi/jitsi-meet#2904]
I would like to print a list of each room and get the number of participants in it.
How do I get the list of rooms but implement the number of participants in the room?

For example, the following implementation does not properly fetch the number of participants in the room.
I want help.

welcomepage.web.js

example room name 1234 

const usercount = getParticipantCount ({room: '1234'});

**Comment by damencho** [comment]
There is no such option currently.  There is a prosody module that gives the participant count for a room, but you need to know the room. You can easily extend that module and add an endpoint to return the currently used rooms:
https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_size.lua
Then in the page you need to implement REST client to hit that module.

**Comment by me-heer** [comment]
For anyone who comes across this in the future, a newer prosody module is added  
https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_census.lua that provides the list of all the rooms and the number of participants in each room.
