### ISSUE TITLE
Participants could not see each other's video on EC2

### ISSUE THREAD

**Issue by Infirex** [jitsi/jitsi-meet#291]
Jitsi-meet was installed on `https://vidwaan.org/` host using fast installation method:
`apt-get -y install jitsi-meet`

When I trying to test conference `https://vidwaan.org/whatever` video is not visible.
And I am getting Jingle error:  `{source: "transportinfo"}`,`{source: "answer"}`
However chat is working as expected.

JVB Log can be found at `https://vidwaan.org/jvb.log`

**Comment by olofumark** [comment]
I have the same issue on EC2 but not with fast Installation method.
Video not working but chat is working, participants are registered correctly and presences acknowledged.
I followed detailed setup at https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md
however there are no errors

**Comment by mobentec** [comment]
We're having the same issue too.

**Comment by emcho** [comment]
The most likely explanation for a working chat and no audio/video exchange
is that your JVB is not running.

Emil

On Wednesday, May 27, 2015, olofumark <notifications@github.com> wrote:

> I have the same issue on EC2 but not with fast Installation method.
> Video not working but chat is working, participants are registered
> correctly and presences acknowledged.
> I followed detailed setup at
> https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md
> however there are no errors
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jitsi/jitsi-meet/issues/291#issuecomment-105693592>.
>


-- 
sent from my mobile

**Comment by Avatarerof** [comment]
It's running, or at least at can be see in `htop`. I think the problem is somewhere in NAT. Is it possible?

**Comment by buaasoftware** [comment]
I have the same problem. The jitsi-meet was installed at a public vps with ubuntu14.04 . Every setting is default. However , none of the peers can see the others' video. More of them has webcam. 
Please refer to the beginning section ( date : 2015-05-09 00:48:20.975 ) of jvb.log  for the meeting : 
 https://133.130.52.89/jvb.log ( you can use cmd "  wget -c --no-check-certificate  https://133.130.52.89/jvb.log" to download it )

If more info. is needed , please feel free to contact me at buaasoft@tom.com. Thankyou !

**Comment by bgrozev** [comment]
@buaasoftware Is the hostname of the machine resolvable? It looks like it might be "133-130-52-89" and it fails to resolve:

"133-130-52-89: Name or service not known"

**Comment by buaasoftware** [comment]
@bgrozev :  I had no idea why this name appeared at the log file. During the installation of jitsi-meet, I keyed in  : 133.130.52.89 when  prompted. Do you have any ideas ?

**Comment by buaasoftware** [comment]
@bgrozev  : Thanks for your hint! It makes great difference now :) At least  now my PC can see video from my android mobile ( chrome40 ) while video at the mobile flicks seriously .  I will further test it tomorrow ( now it is mid-night ) with more PCs and update this thread . Thanks again ~~~

**Comment by buaasoftware** [comment]
Thankyou so much for bgrozev's help and Jitsi team's sharing such a great work with us:) The following is a summary on the "not see each other's video" issue and we hope it may be of some help to the other users with similiar problem :
Symptom : Participants could not see each other's video
Error messages : 1. at console.log 
Jingle error Object {source: "transportinfo"}
Jingle error Object {source: "answer"}
Jingle error Object {source: "transportinfo"}
2. at jvb.log
2015-05-08 21:20:48.255 SEVERE: [95] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[IceUdpTransportManager connect thread,5,main] and message was: java.net.UnknownHostException: 133-130-52-89: 133-130-52-89: Name or service not known
java.lang.RuntimeException: java.net.UnknownHostException: 133-130-52-89: 133-130-52-89: Name or service not known

Fix : hostname 133.130.52.89

**Comment by yanas** [comment]
Fixed.
