### ISSUE TITLE
I want to capture the room administrator's play screen

### ISSUE THREAD

**Issue by landlove** [jitsi/jitsi-meet#2910]
hi.
I want to capture the room administrator's video screen and show it in welcomepage.js.
I tried to find the contents but could not find it easily.
Please let me know if you have any helpful documentation or examples.

way to save the screenshot as an image.
I'm sorry to keep asking questions.
Thank you. 

![20180503_162726.png](https://steemitimages.com/DQmW377WZPB2LQDg4b2aSGtdQHi5VH9imaKVBQaSKAGsLFV/20180503_162726.png)

**Comment by damencho** [comment]
No there is no such, documentation. Basically you need to rewrite welcome page to join a conference, as conference page and show only one video. There is no way to get the video without joining the conference, so basically you need to remove welcome page as you want who ever open the page to join conference.
You have an option to start youtube streaming, moderator activates follow me and selects his own video, and embed youtube video on welcome page.

**Comment by daminiMore** [comment]
Hi there...is it possible to take pictures  of the guest users screen  that he shown through his camera...from both side ...means from front camera and rear camera...during video call
