### ISSUE TITLE
Not adding remote JVB tracks - no session yet

### ISSUE THREAD

**Issue by classfiy** [jitsi/jitsi-meet#2923]
Please give me some help

**Comment by damencho** [comment]
Share the console log with the errors.

**Comment by classfiy** [comment]
[jvb.log](https://github.com/jitsi/jitsi-meet/files/1978453/jvb.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1978455/jicofo.log)
@damencho

**Comment by damencho** [comment]
Check my comment https://github.com/jitsi/jitsi-meet/issues/2891#issuecomment-385841102 for a solution to your problem. You need to fix jicofo connecting to the xmpp server.

**Comment by c526537207** [comment]
How to solve this problem?
