### ISSUE TITLE
Jitsi Meet App issue with custom server

### ISSUE THREAD

**Issue by alenpmla** [jitsi/jitsi-meet#2927]
We are trying to connect the Jitsi meet app using our custom server.  When we are using custom server the call is not connecting. Cannot join to the room id provided.

**Comment by saghul** [comment]
Can you provide any logs? Do you see a red error screen?

A known issue is with self-signed SSL certs, they are not supported. Could this be it?

**Comment by alenpmla** [comment]
Sure. Please find the attached log. 

`04-22 05:51:09.471 1637-1637/com.example.sd1080417.myapplication D/ReactNativeJS: *******************-----------------------------Starting Jitsi Activity-------------------------------------------------------------*********************
04-22 05:51:09.481 1637-1637/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.ctor()
04-22 05:51:09.711 1637-1637/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.createReactContextInBackground()
04-22 05:51:09.711 1637-1637/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
04-22 05:51:09.761 1637-1637/com.example.sd1080417.myapplication W/unknown:ReactNative: Packager connection already open, nooping.
04-22 05:51:10.751 1637-1735/com.example.sd1080417.myapplication W/unknown:ReactNative: The packager does not seem to be running as we got an IOException requesting its status: recvfrom failed: ECONNRESET (Connection reset by peer)
04-22 05:51:10.751 1637-1637/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
04-22 05:51:10.751 1637-1637/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-22 05:51:10.751 1637-1637/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
04-22 05:51:10.791 1637-1747/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.createReactContext()
04-22 05:51:11.391 1637-1747/com.example.sd1080417.myapplication D/ReactNative: Initializing React Xplat Bridge.
04-22 05:51:11.391 1637-1747/com.example.sd1080417.myapplication D/ReactNative: Initializing React Xplat Bridge before initializeBridge
04-22 05:51:11.411 1637-1747/com.example.sd1080417.myapplication D/ReactNative: Initializing React Xplat Bridge after initializeBridge
04-22 05:51:11.411 1637-1747/com.example.sd1080417.myapplication D/ReactNative: CatalystInstanceImpl.runJSBundle()
04-22 05:51:11.461 1637-1759/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.setupReactContext()
04-22 05:51:11.461 1637-1759/com.example.sd1080417.myapplication D/ReactNative: CatalystInstanceImpl.initialize()
04-22 05:51:11.461 1637-1759/com.example.sd1080417.myapplication W/unknown:ReactNative: Packager connection already open, nooping.
04-22 05:51:11.471 1637-1759/com.example.sd1080417.myapplication D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-22 05:51:12.771 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\browser\\BrowserDetection.js]', '<n>: ', 'This appears to be react-native, ver: 0.51.0'
04-22 05:51:12.791 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\settings\\Settings.js]', '<n>: ', 'generated callstats uid', 'Easton-dst'
04-22 05:51:13.671 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: Running application "App" with appParams: {"initialProps":{"welcomePageEnabled":false,"externalAPIScope":"2853f4d4-1c90-4a8c-9298-d0bb27e20238","pictureInPictureEnabled":false,"timestamp":1524390669708,"url":{"url":"https://hacx.tkminfotech.com/gfdgdgd"}},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
04-22 05:51:14.631 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\ScreenObtainer.js]', '<n>: ', 'Screen sharing not supported by the current browser: ', 'react-native'
04-22 05:51:14.631 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\ScreenObtainer.js]', '<n>: ', 'Desktop sharing disabled'
04-22 05:51:14.681 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Get media constraints', { audio: false,
                                                                                    video: 
                                                                                     { mandatory: { minWidth: 1280, minHeight: 720, maxWidth: 1280, maxHeight: 720 },
                                                                                       optional: [ { facingMode: 'user' } ],
                                                                                       facingMode: 'user',
                                                                                       width: { ideal: 1280 },
                                                                                       height: { ideal: 720 } } }
04-22 05:51:14.711 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Get media constraints', { audio: true, video: false }
04-22 05:51:14.721 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\xmpp\\xmpp.js]', '<n>: ', 'P2P STUN servers: ', [ { urls: 'stun:stun.l.google.com:19302' },
                                                                                    { urls: 'stun:stun1.l.google.com:19302' },
                                                                                    { urls: 'stun:stun2.l.google.com:19302' } ]
04-22 05:51:14.751 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\xmpp\\xmpp.js]', '<n>: ', '(TIME) Strophe connecting:\t', 1524390674765
04-22 05:51:14.981 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Available devices: ', [ { facing: 'back',
                                                                                      label: 'Camera 0, Facing back, Orientation 90',
                                                                                      kind: 'videoinput',
                                                                                      deviceId: '0',
                                                                                      groupId: null },
                                                                                    { facing: 'front',
                                                                                      label: 'Camera 1, Facing front, Orientation 270',
                                                                                      kind: 'videoinput',
                                                                                      deviceId: '1',
                                                                                      groupId: null },
                                                                                    { facing: null,
                                                                                      label: 'Audio',
                                                                                      kind: 'audioinput',
                                                                                      deviceId: 'audio-1',
                                                                                      groupId: null } ]
04-22 05:51:14.991 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'onUserMediaSuccess'
04-22 05:51:15.001 1637-1758/com.example.sd1080417.myapplication D/ReactNativeJS: '[modules\\RTC\\JitsiLocalTrack.js]', '<n>: ', 'Setting new MSID: 08550b6c-d302-4793-8e09-ce6d1a5af0a1 51add0e5-534d-4d8c-8126-79b7934929d8 on LocalTrack[undefined,video]'
04-22 05:51:15.071 1637-1758/com.example.sd1080417.myapplication I/ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'onUserMediaSuccess'
04-22 05:51:15.071 1637-1758/com.example.sd1080417.myapplication D/ReactNativeJS: '[modules\\RTC\\JitsiLocalTrack.js]', '<n>: ', 'Setting new MSID: 9c347473-8863-4ee1-b21b-26ae114b9864 f5385d45-d729-4133-be61-b1f84e90de84 on LocalTrack[undefined,audio]'
04-22 05:51:15.101 1637-1758/com.example.sd1080417.myapplication D/ReactNativeJS: '[modules\\xmpp\\strophe.util.js]', '<n>: ', 'Strophe', 1, 'Websocket open'
04-22 05:51:15.121 1637-1758/com.example.sd1080417.myapplication W/ReactNativeJS: { [ReferenceError: Can't find variable: DOMParser] line: 444, column: 129152, sourceURL: 'index.android.bundle' }
04-22 05:51:15.131 1637-1758/com.example.sd1080417.myapplication W/ReactNativeJS: { [ReferenceError: Can't find variable: DOMParser] line: 444, column: 129743, sourceURL: 'index.android.bundle' }`

**Comment by alenpmla** [comment]
[Log_Custom_server.txt](https://github.com/jitsi/jitsi-meet/files/1983053/Log_Custom_server.txt)

**Comment by saghul** [comment]
Ah, I see you are using websockets to connect. There was a bug with that, which was fixed in:https://github.com/jitsi/jitsi-meet/commit/627b9d319c2cc7bdf4df80dea7a02db03f233eb4

This is not part of any release yet IIRC. @lyubomir do you know if this made it to the latest internal build?

**Comment by saghul** [comment]
@alenpmla You can workaround this by using BOSH as the XMPP transport in the meantime.

**Comment by CPLASF1925** [comment]
@saghul 



Using the self signed SSL certificate, the red screen prompts the connection to disconnect and cannot join the room.

**Comment by saghul** [comment]
@CPLASF1925 self-signed certificates are not supported, sorry. This is because we (well, React Native really) use the system trust store. Consider getting a proper SSL cert.

I'm closing this since the original issue is now fixed.
