### ISSUE TITLE
avoid adding #jitsi_meet_external_api_id to room URL

### ISSUE THREAD

**Issue by riobijanero** [jitsi/jitsi-meet#2928]
Hello, 

when I access jitsi-meet on an ios client, it opens the app but adds jitsi_meet_external_api_id to the room url.

- what is the purpose of that ?
- how can I prevent it from concatenating the room url with #jitsi_meet_external_api_id ?

**Comment by damencho** [comment]
Why you need that removed, what is the problem you face? 
This is a mechanism we use to signal to jitsi-meet code that it is loaded through the external API using iframe. Without it, there are functionalities that will not work.

**Comment by riobijanero** [comment]
I want to invite to a specific room Url, that is always the same. I want that room to be available to a mobile client as well.
however if #jitsi_meet_external_api_id is added to the room URL, the person joining with an ios client ends up in a different roomURL
