### ISSUE TITLE
Loading spinner shows after entering room with authentication enabled. 

### ISSUE THREAD

**Issue by monstrfolk** [jitsi/jitsi-meet#2934]
A loading spinner appears a few seconds after joining a conference with authentication enabled. I am using ldap authentication. 

Audio and video continue to work after spinner appears. This does not happen with authentication disabled.

**Comment by damencho** [comment]
Can you attach a screenshot of the spinner and the js console logs from the browser?

**Comment by monstrfolk** [comment]
The spinner shows in the android app.

**Comment by monstrfolk** [comment]
Anyone have experience this issue before?

**Comment by lyubomir** [comment]
@paweldomas, does Jitsi Meet for Android and iOS support ldap authentication?

**Comment by paweldomas** [comment]
I will give authentication flow a try. Can you give some more details on how exactly you configure that ? Do you make changes only to prosody config ? Do you change anything in the config.js or Jicofo's config ?

Did it used to work correctly and broke on one of the recent releases or it never worked as expected ?

Does the web work correctly for you ?
