### ISSUE TITLE
Integration with OpenFire

### ISSUE THREAD

**Issue by lfdominguez** [jitsi/jitsi-meet#2935]
Hello, I was installed from jitsi debian repo de jitsi-meet package, then I configure the jicofo and videobridge to connect to my central OpenFire XMPP Server, the components is working great, but when i browse to jitsi-meet internal web, then the autentication works well, but say that is not authorized (in console js using chrome) to create a conference, but the user (not jicofo@domain) i put to test jicofo is an admin of the OpenFire (OpenFire is autenticating with LDAP), this is the error:

![image](https://user-images.githubusercontent.com/5604131/39756542-0c6b5fae-5298-11e8-81f7-167786b86b1a.png)

Every time that i clic "I am the Host" the OpenFire log show me this:

`2018.05.08 12:09:33 org.jivesoftware.openfire.IQRouter - No se pudo rutear el paquete
java.lang.NullPointerException`

and the jicofo log
```
Jicofo 2018-05-08 12:16:54.985 INFO: [46] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: test5@conference.mtz.desoft.cu
Jicofo 2018-05-08 12:17:00.986 INFO: [48] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: test5@conference.mtz.desoft.cu
Jicofo 2018-05-08 12:17:04.307 SEVERE: [101] org.jitsi.jicofo.JvbDoctor.log() Unexpected error returned by the bridge: jitsi-videobridge.mtz.desoft.cu, err: <iq to='luis.dominguez@mtz.desoft.cu/luis.dominguez291617669320999' from='jitsi-videobridge.mtz.desoft.cu' id='4WYVU-27970' type='error'><error type='auth'><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```

**Comment by damencho** [comment]
Have you checked this: https://github.com/jitsi/jicofo/blob/master/README.md#secure-domain
These are the instructions for using authentication, it has some extra settings you need to configure to jicofo.
But your error that is coming from jvb is strange. Does jvb connects correctly on startup?

**Comment by lfdominguez** [comment]
I'm using OpenFire, not using prosody, the jicofo and vb are connecting in components to openfire great (i think)...

![image](https://user-images.githubusercontent.com/5604131/39757492-fec90eb6-529a-11e8-8a73-4d10720ca641.png)

**Comment by damencho** [comment]
Check jvb logs for the error, why it returns not-authorized.
Did you check that readme to the end? Have you add the jicofo config?

**Comment by lfdominguez** [comment]
this is log from jvb
```
JVB 2018-05-08 13:51:38.395 FINE: [33] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId J9wzs-15127): <iq type="result" id="J9wzs-15127" from="mtz.desoft.cu" to="jitsi-videobridge.mtz.desoft.cu"/>
JVB 2018-05-08 13:51:38.395 FINE: [33] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq type="result" id="J9wzs-15127" from="mtz.desoft.cu" to="jitsi-videobridge.mtz.desoft.cu"/>
JVB 2018-05-08 13:51:43.997 FINE: [35] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId OqMor-3807): <iq to="jitsi-videobridge.mtz.desoft.cu" id="OqMor-3807" type="get" from="luis.dominguez@mtz.desoft.cu/luis.dominguez324527277711347"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
JVB 2018-05-08 13:51:43.997 FINE: [35] org.jitsi.videobridge.xmpp.ComponentImpl.processIQRequest() (serving component 'JitsiVideobridge') Processing IQ request (packetId OqMor-3807).
JVB 2018-05-08 13:51:43.997 FINE: [35] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq to="jitsi-videobridge.mtz.desoft.cu" id="OqMor-3807" type="get" from="luis.dominguez@mtz.desoft.cu/luis.dominguez324527277711347"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
JVB 2018-05-08 13:51:43.998 FINE: [35] org.jitsi.videobridge.xmpp.ComponentImpl.log() SENT: <iq to="luis.dominguez@mtz.desoft.cu/luis.dominguez324527277711347" from="jitsi-videobridge.mtz.desoft.cu" id="OqMor-3807" type="error"><error type="auth"><not-authorized xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></not-authorized></error></iq>
JVB 2018-05-08 13:51:43.998 FINE: [35] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Responding to IQ (packetId OqMor-3807) with: <iq to="luis.dominguez@mtz.desoft.cu/luis.dominguez324527277711347" from="jitsi-videobridge.mtz.desoft.cu" id="OqMor-3807" type="error"><error type="auth"><not-authorized xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></not-authorized></error></iq>
JVB 2018-05-08 13:51:48.395 FINE: [37] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId J9wzs-15131): <iq type="result" id="J9wzs-15131" from="mtz.desoft.cu" to="jitsi-videobridge.mtz.desoft.cu"/>
JVB 2018-05-08 13:51:48.395 FINE: [37] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq type="result" id="J9wzs-15131" from="mtz.desoft.cu" to="jitsi-videobridge.mtz.desoft.cu"/>
```

**Comment by damencho** [comment]
Hum, there is something wrong here, where jvb is receiving an iq from your user luis.dominguez and not from the focus user of jicofo. 
Have you configured jicofo to connect to Openfire as user 'focus' or you are using user luis.dominguez for jicofo?

**Comment by lfdominguez** [comment]
ohh now i will changed, the openfire is with ldap, so i create a new focus user and.... work... but now there are another problem

**Comment by damencho** [comment]
Can you try with two chrome tabs, does it work? Firefox still has some issues that we will be working on in the following weeks.

**Comment by lfdominguez** [comment]
with chrome... works... but both of them converts to master of conference

**Comment by lfdominguez** [comment]
and the video dont show with a js error

![image](https://user-images.githubusercontent.com/5604131/39770877-59943820-52be-11e8-9586-a46368a49759.png)

**Comment by damencho** [comment]
By `master of conference` you mean moderators, the star that is shown in their thumbnail, right? This is expected as the participants are authenticated.
There is an option to allow guests: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L25, this way once an authenticated user is in the room you can invite guests which will not need to login.
You need to create a domain with allowed anonymous connecting and add that domain to that setting - anonymousdomain. Not sure that this is possible with Openfire.

**Comment by lfdominguez** [comment]
Yeap i meant that, i dont want anonymous people, that i want is that only I be a moderator...

**Comment by lfdominguez** [comment]
Uff i dont get the webcam into chromium in any way....

**Comment by cnscns** [comment]
@lfdominguez How to integrate jitsi-meet with openfire? Is there any documents?

**Comment by lfdominguez** [comment]
Well the documentation is my own test ggg.. and already all works great!!
