### ISSUE TITLE
 Authentication failed when enable Secure domain (manual install).

### ISSUE THREAD

**Issue by gunsluo** [jitsi/jitsi-meet#2937]
Env: ubuntu18.04

**prosody config:**
```
VirtualHost "meet.demo.com"
    authentication = "internal_plain"
    ssl = {
        key = "/var/lib/prosody/meet.demo.com.key";
        certificate = "/var/lib/prosody/meet.demo.com.crt";
    }
    modules_enabled = {
        "bosh";
        "pubsub";
    }

VirtualHost "guest.meet.demo.com"
    authentication = "anonymous"
    c2s_require_encryption = false

admins = { "focus@meet.demo.com" }

Component "conference.meet.demo.com" "muc"
Component "jitsi-videobridge.meet.demo.com"
    component_secret = "password1"
Component "focus.meet.demo.com"
    component_secret = "password2"
```

**nginx config:**

```
server {
    listen 80;
    server_name meet.demo.com;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name meet.demo.com;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";

    ssl_certificate /var/lib/prosody/meet.demo.com.crt;
    ssl_certificate_key /var/lib/prosody/meet.demo.com.key;

    root /var/www/jitsi-meet;
    index index.html index.htm;
    # error_page 404 /static/404.html;

    location ~ ^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }

    location / {
        ssi on;
    }

    # BOSH
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }
}
```

**videobridge config**
sip-communicator.properties
```
org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
```

./jvb.sh --host=localhost --domain=meet.demo.com --port=5347 --secret=password1

**jicofo config**
sip-communicator.properties
```
org.jitsi.jicofo.auth.URL=XMPP:meet.demo.com
```

> JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=jicofo -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi/jicofo -Djava.util.logging.config.file=/etc/jitsi/jicofo/logging.properties -Dlog4j.configurationFile=/etc/jitsi/jicofo/log4j2.xml -Dorg.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true"

./jicofo.sh --host=localhost --domain=meet.demo.com --secret=password2 --user_domain=meet.demo.com --user_name=focus --user_password=password3

**create account**
prosodyctl register focus meet.demo.com password3
prosodyctl register test meet.demo.com test

input: https://meet.demo.com/room

![image](https://user-images.githubusercontent.com/9067076/39764848-13f48b30-5313-11e8-9793-9efb7d9602e9.png)
click `I am this host`  and user: ` test@meet.demo.com`  password: `test`

![image](https://user-images.githubusercontent.com/9067076/39764924-37c9daba-5313-11e8-8823-2926d3fa8b90.png)

Error:
![image](https://user-images.githubusercontent.com/9067076/39764973-5a7a6840-5313-11e8-9f5d-02a6d5a1bac3.png)

Any ideas?

**Comment by damencho** [comment]
Can you try adding c2s_require_encryption = false and for the VirtualHost "meet.demo.com" and try again, do you have the same experience?

**Comment by gunsluo** [comment]
Prosody Log: 

> ay 08 07:50:47 jcp55a98353c1e0	info	Incoming Jabber component connection
> May 08 07:50:47 c2s55a9832f7d40	info	Client connected
> May 08 07:50:47 focus.meet.demo.com:component	info	External component successfully authenticated
> May 08 07:50:47 c2s55a9832f7d40	info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
> May 08 07:50:47 c2s55a9832f7d40	info	Authenticated as focus@meet.demo.com
> May 08 07:55:18 bosh2cba40db-ce3f-4afa-9ac8-c57ce6bdf359	info	BOSH client disconnected
> May 08 07:55:29 mod_bosh	info	New BOSH session, assigned it sid '02ca0714-a50e-481a-8103-6390120a217a'
> May 08 07:55:29 bosh02ca0714-a50e-481a-8103-6390120a217a	info	Authenticated as 6fbd3473-62b0-4416-a8fe-6a295183357a@guest.meet.demo.com
> May 08 07:55:49 mod_bosh	info	New BOSH session, assigned it sid '097f9440-1bf6-40ec-bc38-0025b7881a73'
> May 08 07:58:30 mod_bosh	info	New BOSH session, assigned it sid '9915280e-246c-40e8-a09d-54d51ae561a0'
> May 08 08:01:41 bosh02ca0714-a50e-481a-8103-6390120a217a	info	BOSH client disconnected
> May 08 08:01:43 mod_bosh	info	New BOSH session, assigned it sid '637eb569-2345-43e6-9694-dd729b42e1e0'
> May 08 08:01:43 bosh637eb569-2345-43e6-9694-dd729b42e1e0	info	Authenticated as dc4ab4fd-ae14-4386-bf7a-8bfd7905bf20@guest.meet.demo.com
> May 08 08:02:06 mod_bosh	info	New BOSH session, assigned it sid '5340c9b2-7bd8-4b2b-9759-1fd3de4de9b8'

JVB Log:

> May 08, 2018 8:02:51 AM org.jitsi.util.LoggerImpl log
> FINE: RECV: <iq id="l3LvT-3119" type="result" to="jitsi-videobridge.meet.demo.com" from="meet.demo.com"/>
> May 08, 2018 8:02:57 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Processing IQ (packetId nuHBQ-964): <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-964"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> May 08, 2018 8:02:57 AM org.xmpp.component.AbstractComponent processIQRequest
> FINE: (serving component 'JitsiVideobridge') Processing IQ request (packetId nuHBQ-964).
> May 08, 2018 8:02:57 AM org.jitsi.util.LoggerImpl log
> FINE: RECV: <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-964"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> May 08, 2018 8:02:57 AM org.jitsi.util.LoggerImpl log
> INFO: CAT=stat create_conf,conf_id=7ee70d3813efd30c conf_name=null,logging=false,conf_count=1,ch_count=0,v_streams=0
> May 08, 2018 8:02:57 AM org.jitsi.util.LoggerImpl log
> FINE: SENT: <iq to="focus@meet.demo.com/focus70318535117915" from="jitsi-videobridge.meet.demo.com" id="nuHBQ-964" type="result"/>
> May 08, 2018 8:02:57 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Responding to IQ (packetId nuHBQ-964) with: <iq to="focus@meet.demo.com/focus70318535117915" from="jitsi-videobridge.meet.demo.com" id="nuHBQ-964" type="result"/>
> May 08, 2018 8:02:59 AM org.jitsi.util.LoggerImpl log
> INFO: Running expire()
> May 08, 2018 8:03:01 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Processing IQ (packetId l3LvT-3123): <iq id="l3LvT-3123" type="result" to="jitsi-videobridge.meet.demo.com" from="meet.demo.com"/>
> May 08, 2018 8:03:01 AM org.jitsi.util.LoggerImpl log
> FINE: RECV: <iq id="l3LvT-3123" type="result" to="jitsi-videobridge.meet.demo.com" from="meet.demo.com"/>
> May 08, 2018 8:03:07 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Processing IQ (packetId nuHBQ-971): <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-971"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> May 08, 2018 8:03:07 AM org.xmpp.component.AbstractComponent processIQRequest
> FINE: (serving component 'JitsiVideobridge') Processing IQ request (packetId nuHBQ-971).
> May 08, 2018 8:03:07 AM org.jitsi.util.LoggerImpl log
> FINE: RECV: <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-971"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> May 08, 2018 8:03:07 AM org.jitsi.util.LoggerImpl log
> INFO: CAT=stat create_conf,conf_id=56b92b90ba508a9d conf_name=null,logging=false,conf_count=1,ch_count=0,v_streams=0
> May 08, 2018 8:03:07 AM org.jitsi.util.LoggerImpl log
> FINE: SENT: <iq to="focus@meet.demo.com/focus70318535117915" from="jitsi-videobridge.meet.demo.com" id="nuHBQ-971" type="result"/>
> May 08, 2018 8:03:07 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Responding to IQ (packetId nuHBQ-971) with: <iq to="focus@meet.demo.com/focus70318535117915" from="jitsi-videobridge.meet.demo.com" id="nuHBQ-971" type="result"/>
> May 08, 2018 8:03:11 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Processing IQ (packetId l3LvT-3127): <iq id="l3LvT-3127" type="result" to="jitsi-videobridge.meet.demo.com" from="meet.demo.com"/>
> May 08, 2018 8:03:11 AM org.jitsi.util.LoggerImpl log
> FINE: RECV: <iq id="l3LvT-3127" type="result" to="jitsi-videobridge.meet.demo.com" from="meet.demo.com"/>
> May 08, 2018 8:03:17 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Processing IQ (packetId nuHBQ-981): <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-981"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> May 08, 2018 8:03:17 AM org.xmpp.component.AbstractComponent processIQRequest
> FINE: (serving component 'JitsiVideobridge') Processing IQ request (packetId nuHBQ-981).
> May 08, 2018 8:03:17 AM org.jitsi.util.LoggerImpl log
> FINE: RECV: <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-981"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> May 08, 2018 8:03:17 AM org.jitsi.util.LoggerImpl log
> INFO: CAT=stat create_conf,conf_id=7f54a64b7a0d4314 conf_name=null,logging=false,conf_count=1,ch_count=0,v_streams=0
> May 08, 2018 8:03:17 AM org.jitsi.util.LoggerImpl log
> FINE: SENT: <iq to="focus@meet.demo.com/focus70318535117915" from="jitsi-videobridge.meet.demo.com" id="nuHBQ-981" type="result"/>
> May 08, 2018 8:03:17 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Responding to IQ (packetId nuHBQ-981) with: <iq to="focus@meet.demo.com/focus70318535117915" from="jitsi-videobridge.meet.demo.com" id="nuHBQ-981" type="result"/>
> May 08, 2018 8:03:17 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Processing IQ (packetId nuHBQ-989): <iq type="get" to="jitsi-videobridge.meet.demo.com" from="focus@meet.demo.com/focus70318535117915" id="nuHBQ-989"><query xmlns="http://jabber.org/protocol/disco#info"/></iq>
> May 08, 2018 8:03:17 AM org.xmpp.component.AbstractComponent processIQRequest
> FINE: (serving component 'JitsiVideobridge') Processing IQ request (packetId nuHBQ-989).
> May 08, 2018 8:03:17 AM org.xmpp.component.AbstractComponent processIQ
> FINE: (serving component 'JitsiVideobridge') Responding to IQ (packetId nuHBQ-989) with: <iq type="result" id="nuHBQ-989" from="jitsi-videobridge.meet.demo.com" to="focus@meet.demo.com/focus70318535117915"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="component" type="conference" name="JitsiVideobridge"/><feature var="http://jabber.org/protocol/disco#info"/><feature var="urn:xmpp:ping"/><feature var="jabber:iq:last"/><feature var="urn:xmpp:time"/><feature var="http://jitsi.org/protocol/colibri"/><feature var="http://jitsi.org/protocol/healthcheck"/><feature var="urn:xmpp:jingle:apps:dtls:0"/><feature var="urn:xmpp:jingle:transports:ice-udp:1"/><feature var="urn:xmpp:jingle:transports:raw-udp:1"/><feature var="jabber:iq:version"/></query></iq>

Jicofo Log:

> INFO: XMPP provider Jabber:focus@meet.demo.com/focus70318535117915@localhost connected (JID: focus@meet.demo.com/focus70318535117915)
> May 08, 2018 7:50:50 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:50:56 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:02 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:08 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:14 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:20 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:26 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:32 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:38 AM net.java.sip.communicator.util.Logger info
> INFO: Focus request for room: luoji@conference.meet.demo.com
> May 08, 2018 7:51:44 AM net.java.sip.communicator.util.Logger info

There is no error message.  

Did you find any solution?

**Comment by gunsluo** [comment]
@damencho Thank you for your quick reply.

You are right.   set `c2s_require_encryption = false` is ok.
