### ISSUE TITLE
Quick Install didn't configure auth ssl info.

### ISSUE THREAD

**Issue by seansackowitz** [jitsi/jitsi-meet#2938]
When following the Quick Install guide on a brand new install of Ubuntu 16.04, p2p connections worked great, and when testing the videobridge on my own(internal network), everything worked fine as well. However, when I got a third member from outside the network to join, everyone's connection would drop unless they were on the same network.
Eventually, after much frustration, I found that the key and certificate as shown below, were instead blank. after setting them to the correct files, and restarting jicofo, everything worked perfectly.

in `/etc/prosody/conf.avail/jitsi.example.com.cfg.lua`
```
VirtualHost "auth.jitsi.example.com"
    ssl = {
        key = "/etc/prosody/certs/auth.jitsi.example.com.key";
        certificate = "/etc/prosody/certs/auth.jitsi.example.com.crt";
    }
    authentication = "internal_plain"
```
followed by running these two commands
```
update-ca-certificates -f
/etc/init.d/jicofo restart
```

I also want to make it clear that there were no errors that specified what was going wrong, outside of a few generic warning logs, and I merely stumbled across this solution after 3 days of debugging.

**Comment by damencho** [comment]
@seansackowitz I'm interested how did you install? You are using the stable packages, right? Did you try something, then remove it and try again, or deleting some file when retrying ...? I'm trying to find the steps to reproduce this, cause I was testing this lately on clean VM and just following the quick install instructions everything works from the initial setup.
Missing the ssl ={ part is expected if at the time of the installing the file "/var/lib/prosody/$JICOFO_AUTH_DOMAIN.crt" is there.

**Comment by seansackowitz** [comment]
Correct, I was using the stable packages. It appears as though I did install, then purge, then install again, but I do not recall why I had to do so. Other than that however, I only followed the exact instructions. exact block was:
```
VirtualHost "auth.jitsi.example.com"
    ssl = {
        key = "";
        certificate = "";
    }
    authentication = "internal_plain"
```
and it had filled out the key and cert for the non-auth VirtualHost block.

I do not remember the exact version I did the install with, as it was about 2 months ago.

**Comment by damencho** [comment]
Ou, those were empty :( Hum. That is so strange: https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L133 it should at least have /etc/prosody/certs/... 
In previous versions purge was not clearing everything, and is fixed now in the stable.
