### ISSUE TITLE
how to activate this

### ISSUE THREAD

**Issue by geraldsamosir** [jitsi/jitsi-meet#2941]
can you  give me information how to allow this in my jitsi meet server

![lolol](https://user-images.githubusercontent.com/7693125/39790117-3ee7c4ce-535e-11e8-9d14-bc1db3cefe2c.png)

i have try to follow the instruction in jibri but i got only like this
![yeyeyey](https://user-images.githubusercontent.com/7693125/39790151-7b3f09aa-535e-11e8-9b4a-8c295f12c40c.png)

**Comment by bbaldino** [comment]
Well it looks like you have it configured correctly in jitsi-meet, but Jicofo isn't seeing any Jibris available.  Can you attach your Jicofo and Jibri logs from when that happens?

**Comment by geraldsamosir** [comment]
this is the first time i use this engine and i have try to re install jitsi meet again ,
can you give me process to allow that features because i really confused with documentation

**Comment by geraldsamosir** [comment]
here is my jcofo and jibri logs
![jibrilog](https://user-images.githubusercontent.com/7693125/39980934-74ef37e6-5778-11e8-8dcc-a27cb87401a3.png)
![jicofolog](https://user-images.githubusercontent.com/7693125/39980935-7530f4d8-5778-11e8-9412-e202a9d0334d.png)
