### ISSUE TITLE
call icon disappear in jitsi meet when install jigasi

### ISSUE THREAD

**Issue by globalcorpp** [jitsi/jitsi-meet#2943]
hello fellow jitster

I install jitsi meet in ubuntu 16.04 both stable and unstable builds, want to active jigasi
after install jigasi package and register a sip extension(when I monitor sip server log(asterisk), my extension register successfully) then reload services
when create a room in jitsi meet, doesnt show any phone icon in main toolbar or extended toolbar
do I need any specific configuration? 

Regards.

**Comment by globalcorpp** [comment]
yes I see plus button("+") in main toolbar
but when i dial a local extension, automatically add +1 to my number. for example if enter 3000 (3000 is a client that install jitsi desktop in my local network) convert to +13000 and show "initializing call" then show "13000 is having connectivity issues..."

when i check sip server log, does not receive any incoming call

**Comment by saghul** [comment]
I’m afraid this is a known issue, now that I see it.

**Comment by globalcorpp** [comment]
how can solve this problem?
is there any config file try it?

**Comment by globalcorpp** [comment]
anybody can help me how to fix this issue?

**Comment by globalcorpp** [comment]
after many days I can solve this issue

first:
in new version of jitsi meet accoroding to this news https://jitsi.org/news/jitsi-meet-simplified/
plus icon in right bottom corner replace phone icon after install jigasi package this new icon appeared

second:
if you suddenly power off your server or VM, jigasi service get in trouble until manually restart this service with this command "service jigasi restart"
if you check server status with this comand "service jigasi status" you will see this log

jigasi.service - LSB: Jitsi Gateway for SIP
   Loaded: loaded (/etc/init.d/jigasi; generated)
   Active: active (running) since Sat 2018-05-12 11:57:31 PDT; 12min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2856 ExecStop=/etc/init.d/jigasi stop (code=exited, status=0/SUCCESS)
  Process: 2862 ExecStart=/etc/init.d/jigasi start (code=exited, status=0/SUCCESS)
    Tasks: 92 (limit: 4999)
   CGroup: /system.slice/jigasi.service
           +-2868 java -Djava.library.path=/usr/share/jigasi/lib/native/linux-64 -Djava.util.logging.config.file=/etc/jitsi/jigasi/logging.properties -

May 12 11:57:31 ubuntu systemd[1]: Stopped LSB: Jitsi Gateway for SIP.
May 12 11:57:31 ubuntu systemd[1]: jigasi.service: Found left-over process 855 (java) in control group while starting unit. Ignoring.
May 12 11:57:31 ubuntu systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
May 12 11:57:31 ubuntu systemd[1]: Starting LSB: Jitsi Gateway for SIP...
May 12 11:57:31 ubuntu jigasi[2862]: Starting jigasi: jigasi started.
May 12 11:57:31 ubuntu systemd[1]: Started LSB: Jitsi Gateway for SIP.

**Comment by saghul** [comment]
I'm leaving this open because we shouldn't really mangle whatever the user enters in this case.
