### ISSUE TITLE
anybody have a successfully experience to install jitsi meet on ubuntu 1804 LTS

### ISSUE THREAD

**Issue by globalcorpp** [jitsi/jitsi-meet#2947]
install jitsi meet on ubuntu 1804 LTS and when I create a room, the screen is freeze(gray) and each person invite to room, get disconnect error

**Comment by saghul** [comment]
Do you get any errors in the JavaScript console?

**Comment by globalcorpp** [comment]
(TIME) index.html loaded:	 224.50500000000002
[modules/browser/BrowserCapabilities.js] <new t>:  This appears to be chrome, ver: 50.0
[react/index.web.js] <HTMLDocument.<anonymous>>:  (TIME) document ready:	 1518.89
[react/features/base/storage/PersistenceRegistry.js] <e.a.value>:  redux state rehydrated as Object
[modules/UI/videolayout/VideoLayout.js] <Object.w.changeUserAvatar>:  Missed avatar update - no small video yet for undefined
[JitsiMeetJS.js] <Object.t.default.i.init>:  Analytics disabled, disposing.
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Disposing of analytics adapter.
[modules/RTC/ScreenObtainer.js] <Object.y.init>:  Desktop sharing disabled
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
[react/features/base/media/middleware.js] <>:  Start muted: 
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
[react/features/base/media/middleware.js] <>:  Start audio only set to false
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
[react/features/base/conference/middleware.js] <>:  Audio-only disabled
[modules/URL/ConferenceUrl.js] <new e>:  Stored original conference URL: https://"MYIP"/test
[modules/URL/ConferenceUrl.js] <new e>:  Conference URL for invites: https://"MYIP"/test
[modules/RTC/RTCUtils.js] <>:  Available devices:  Array[9]
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
[modules/RTC/RTCUtils.js] <t.F.value>:  Get media constraints Object
[modules/xmpp/xmpp.js] <t.b.value>:  P2P STUN servers:  Array[3]
[modules/xmpp/xmpp.js] <t.b.value>:  Lip-sync enabled !
[modules/xmpp/xmpp.js] <t.b.value>:  (TIME) Strophe connecting:	 1821.1450000000002
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
[JitsiMeetJS.js] <Object.t.default.i.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 1.1 error 0 happened(…)
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 1.1 error 0 happened
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request errored, status: 0, number of errors: 1
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
[JitsiMeetJS.js] <Object.t.default.i.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 2.2 error 0 happened(…)
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 2.2 error 0 happened
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request errored, status: 0, number of errors: 2
[modules/RTC/RTCUtils.js] <>:  onUserMediaSuccess
[modules/RTC/JitsiLocalTrack.js] <t.b.value>:  Setting new MSID: 117562a3-8a6a-4200-9fb6-a877e6487498 3eeb725c-214f-4968-b4ab-f20a934f382a on LocalTrack[undefined,audio]
[modules/RTC/JitsiLocalTrack.js] <t.b.value>:  Setting new MSID: 858c4515-6d75-429a-bf92-03ec6ba88b92 2c45a73e-c61b-440e-9db1-1bd8055ed5ef on LocalTrack[undefined,video]
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
[JitsiMeetJS.js] <Object.t.default.i.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 3.3 error 0 happened(…)
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 3.3 error 0 happened
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request errored, status: 0, number of errors: 3
OPTIONS https://vconf.test.uk/http-bind?room=test net::ERR_NAME_NOT_RESOLVED
[JitsiMeetJS.js] <Object.t.default.i.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 4.4 error 0 happened(…)
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 4.4 error 0 happened
[modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request errored, status: 0, number of errors: 4
[modules/xmpp/xmpp.js] <t.b.value>:  (TIME) Strophe connfail[giving-up]:	 36939.87
[modules/statistics/statistics.js] <Function.i.sendAnalyticsAndLog>:  {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.otherError","error_message":"giving-up"}}
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
[connection.js] <n.l>:  CONNECTION FAILED: connection.otherError
[modules/statistics/AnalyticsAdapter.js] <e.c.value>:  Not sending an event, disposed.
[react/features/overlay/components/AbstractPageReloadOverlay.js] <t.f.value>:  The conference will be reloaded after 30 seconds.
[react/features/base/connection/actions.web.js] <>:  connection.otherError

**Comment by damencho** [comment]
Yep, I was testing the quick install when 18.04 was released and it was working just fine. In your console logs I can see that your bosh URL that is configured cannot be resolved:  https://vconf.test.uk/http-bind?room=test net::ERR_NAME_NOT_RESOLVED
You need to make sure the DNS you use for your deployment is resolvable.
