### ISSUE TITLE
Error:(44, 0) C:\Users\Iyayi Kelvin\Documents\My Apps\JITSI\node_modules\react-native-background-timer\package.json (The system cannot find the file specified) 

### ISSUE THREAD

**Issue by kiyayi** [jitsi/jitsi-meet#2950]
I just compiled/built this project on Android Studio, I am currently faced with this error, which has to do with the system not properly locating the location of package.json,  I will appreciate a solution to this error.

![screenshot 125](https://user-images.githubusercontent.com/5180028/39877681-76cba868-546e-11e8-9a86-a83745655859.png)

**Comment by virtuacoplenny** [comment]
Did you run `npm install` within the jitsi-meet directory? The jitsi-meet project is a js project that uses npm/package.json to manage external dependencies.
