### ISSUE TITLE
failed to load config.js from in android >>E/ReactNativeJS: 'Failed to load config from https://example.org/config.js?room=aayush'

### ISSUE THREAD

**Issue by aayushsri17** [jitsi/jitsi-meet#2958]
i can easily connect  **jitsiView.loadURL("https://meet.jit.si/Test123");** from android studio .

 I implemented the android sdk from the dependency "org.jitsi.react:jitsi-meet-sdk:1.9.0" in gradle file.

but i get the above error when i place my url i.e. **jitsiView.loadURL("http://example.org/aayush");**  instead the test url.

the url (domain name) is working fine in web browser but not working in android client.

i also get connection failure request when i try to connect from the jitsi meet app i downloaded from play store using my url(domain). 

 my IP i.e. **http://xxx.xx.xxx.xx/aayush** shows unsecure when i open it in browser but the DNS  for the same is secured via lets encrypt and show a valid SSL/TLS certificate i.e. **http://example.org/aayush**

please check and revert and you can see the attached file for more details.
thanks in advance.

also can please u tell the configuration changes that needs to be done in config.js file for android client.

![bug1](https://user-images.githubusercontent.com/15009214/39954421-c94518e4-55dc-11e8-809b-d90824d4cd5a.png)

**Comment by aayushsri17** [comment]
issue resolved.. needs a valid ssl certificate

**Comment by yoosefi12** [comment]
I have run into the same problem. despite i have a valid certificate installed, the problem still exists.
I don't know what to do next! please help me.

**Comment by saghul** [comment]
@yoosefi12 do you get any warning when you open the website with the system web browser? If you sen me the URL I can take a look.

**Comment by yoosefi12** [comment]
@saghul thank you, i solved the problem by adding valid ssl certificate and valid certificate chain.

**Comment by richanshah** [comment]
@aayushsri17  Hi , in which place have u added certificate , I am working on a native android app so Can  u pls guide

**Comment by aayushsri17** [comment]
add the SSL on the webserver and then add a certificate verification from the native app 
follow the link to do the same in your andorid app : **https://developer.android.com/training/articles/security-ssl**

on the other hand, you can look for other options like kurento media server(webrtc). I didn't proceed with jitsi as it had less documentation when I was try to use it. 
you can check kurento video calling service. it is open source and very well documented.
check these links: **https://github.com/nubomedia-vtt/kurento-room-client-android**
**https://doc-kurento.readthedocs.io/en/stable/user/installation.html**

**Comment by aayushsri17** [comment]
> > issue resolved.. needs a valid ssl certificate
> 
> how to add valid ssl certificate? in server or android app?

server

**Comment by c80617** [comment]
Hello,I follow the link to add a certificaiton verificaiotn,
but I am not sure where to add the SSL context to jitsi SDK?
