### ISSUE TITLE
screen sharing support for FF

### ISSUE THREAD

**Issue by gpolitis** [jitsi/jitsi-meet#296]

**Comment by wolftune** [comment]
FF 40 now functions for meet.jit.si and the built-in Firefox Hello supports screen-sharing with no extra plugins installed. Therefore, meet.jit.si should be able to use the same WebRTC screen-sharing support and enable this feature.

**Comment by marclaporte** [comment]
@wolftune clever idea!

One thing though: 
"If you've initiated a conversation, the screen sharing feature will be available to you."
https://support.mozilla.org/en-US/kb/share-your-screen-firefox-hello

So Jitsi Meet would need to emulate this somehow.

Thanks!

**Comment by bgrozev** [comment]
I should have updated this issue, but it slipped. We added firefox support just recently[1]. But there are still some bugs to resolve before we close this. Notably, once you go to screen sharing, you can't go back to camera.

To use it on your own domain you need an extension which you can build with the template here:
https://github.com/jitsi/jidesha/tree/master/firefox

You can test it out on beta.meet.jit.si. Please report any problems.

**Comment by jmcclelland** [comment]
This is great to hear. I think you didn't paste in the footnote about adding firefox support - I would like to read about it. Also - do you have any more documentation on creating an extension to white list our own domain? I notice on the beta version (beta.meet.jit.si) it prompted me to dowload and install the plugin. Is it possible to enable that on our own installed version of jitsi meet?

**Comment by bgrozev** [comment]
Oops. Here's the link: https://hacks.mozilla.org/2015/06/firefox-multistream-and-renegotiation-for-jitsi-videobridge/

And the documentation for the extension is here (it's not that its missing, there's just really not much to it): https://github.com/jitsi/jidesha/blob/master/firefox/README.md

**Comment by jmcclelland** [comment]
Thanks for the links! 

I just compiled the extension for our domain. Just a few more questions...

 1. Where do I copy the extension so that when a user clicks on the Desktop sharing link they will be prompted to download and install it (i.e. they way it works on beta.meet.jit.si).
 1. What version of jitsi-meet includes these changes? We are running 1.0.701-1 from http://download.jitsi.org/nightly/deb/ unstable.

**Comment by bgrozev** [comment]
> Where do I copy the extension so that when a user clicks on the Desktop sharing link they will be prompted to download and install it (i.e. they way it works on beta.meet.jit.si).

That's up to you, but you then need to configure the link in config.js (desktopSharingFirefoxExtensionURL).

> What version of jitsi-meet includes these changes? We are running 1.0.701-1 from http://download.jitsi.org/nightly/deb/ unstable.

701 definitely includes them. I think the first is somewhere around 669, not sure which exactly.

**Comment by jmcclelland** [comment]
Thanks - this is awesome!! Working (and I even got Mozilla to sign it).

I had to add all of the following to config.js to get the link to work properly.

desktopSharingFirefoxExtId: "jidesha@meet.mayfirst.org",
desktopSharingFirefoxDisabled: false,
desktopSharingFirefoxMaxVersionExtRequired: -1,
 desktopSharingFirefoxExtensionURL: 'https://meet.mayfirst.org/desktop-sharing-firefox.xpi',

**Comment by bgrozev** [comment]
You probably want to set desktopSharingFirefoxMaxVersionExtRequired to 0, otherwise clients without the extension won't be prompted to install it.
