### ISSUE TITLE
passthrough video from sip invite via jigasi

### ISSUE THREAD

**Issue by globalcorpp** [jitsi/jitsi-meet#2961]
if my client(tablet, smart phone, pc) have webcam and invite to video conference via jitsi meet room, just transfer audio and cant see video
is there any config to passthrough video from jigasi  or by default cant transfer video when invite?

**Comment by damencho** [comment]
Jigasi does not support video and will never will. 
There is an option to use video sip devices with your own deployment of jibri (as a sip gateway).
