### ISSUE TITLE
Disable "Automatically switch the main lens"

### ISSUE THREAD

**Issue by havid0707** [jitsi/jitsi-meet#2963]
In a multi-person meeting，When someone speaks(or some logic I don't know), the home screen automatically switches to speaker.
Is there any option to turn off this feature? I just want to fix the picture for someone。

**Comment by damencho** [comment]
You can always "pin" him, just click on the person you want to see all the time, and that thumb will be pinned (you will see a blue border around it). Clicking a second time on a pinned thumbnail will unpin it and it will automatically switch to the talking person.
If you want to control what people are seeing there is the option Follow-Me in the settings(moderator only and for all when the option all moderators is enabled like on meet.jit.si), once enabled the other participants will see what you see, for pinning, hiding filmstrip, etc..
