### ISSUE TITLE
problem with login containing '@' character

### ISSUE THREAD

**Issue by fabjal** [jitsi/jitsi-meet#2964]
Hi,
I'm fairly new with video conferences, and i have a problem with the authentication of my users in jitsi-meet:
I configured authenticating against my Active Directory DC, using `authentication = "ldap2"`, and it works flawlessly if i use sAMAccountName (or even GivenName).

However, i want to use the email of the user as login information (or userPrincipalName), and **here's my problem: if i try to log with an '@' in the login field, i get the message "you have been disconnected", and sent back to the login window after 15 seconds.**

This problem seems to occur only in the presence of an '@' symbol. I couldn't find any error in prosody logs or jvm.log. can anyoàne help me on this

**Comment by damencho** [comment]
To be able to save the logs, you need to open the console before trying to login and enable "Preserve logs" option, so they do not get deleted on the reload of the page and keep it open.

**Comment by fabjal** [comment]
Thanks for your help. In the meantime, i've been setting up the server to use samaccountName for preparation purposes, so i've been changing a lot of parameters.

I tried again to authenticate with an email address kinf of format, and i get a different (but clearer?) error:
When i log in, jitsi says: **"Oops! A problem occured and the connection to the conference is impossible: connection.ortherError"** (akwardly translated from french)

In the Chrome console, i get this error:
`[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: BOSH-Connection failed: host-unknown
at Object.i.Strophe.log (strophe.util.js:89)
at Object.error (strophe.js:2081)
at e.Bosh._connect_cb (strophe.js:5282)
at s.Connection._connect_cb (strophe.js:3907)
at e.Bosh._onRequestStateChange (strophe.js:5550)`

Something seems to be missing, but where?

**Comment by damencho** [comment]
You are hitting the prosody bosh with a host which is not configured inside prosody.
For example in prosody you have configured domain A, but you are accessing the bosh connection using domain B. Depending on the deployment you can fix it by changing the host header in the proxy request in the web server config to domain A.

**Comment by fabjal** [comment]
Thanks you for your response. However, i'm not sure where to change it. Is it `/etc/jitsi/meet/<domain>-config.js`? or another file? Which line/parameter would that be?

**Comment by damencho** [comment]
Are you using nginx, apache or jetty that comes with jvb? This setting, I think, is not possible with jetty at the moment.
So you can also fix it in prosody config /etc/prosody/conf.d/, by fixing the domains you use and make them in sync with what you have in /etc/jitsi/meet/<domain>-config.js, but then you need to also fix and jicofo user and connection information.

**Comment by fabjal** [comment]
i'm using the easy install, via apt-get command. so i'm not sure (sorry). Is it nginx?
The domains i use are as follows:
Everything in jitsi-meet suite is configured on confcall.mydomain.com.
However, my users authenticate with user@mydomain.com

**Comment by damencho** [comment]
If you didn't have nginx or apache before installing jitsi-meet you are probably using jetty.
The authenticate user doesn't matter.
What about the bosh config in config.js is it again confcall.mydomain.com? And you have the same domain configured in prosody?
What have you changed after the standard installation?

**Comment by fabjal** [comment]
The bosh config in config.js is as follows:
`// BOSH URL. FIXME: use XEP-0156 to discover it.`
`bosh: '//confcall.mydomain.com/http-bind',`
Apart from ldap2 authentication, not much was changed:
I uncommented the line for anonymous users (`anonymousdomain: 'guest.mydomain.com'`), and activated desktop sharing support for chrome.
