### ISSUE TITLE
New install without nginx

### ISSUE THREAD

**Issue by havid0707** [jitsi/jitsi-meet#2970]
![image](https://user-images.githubusercontent.com/9440277/40032661-9cddef4a-5827-11e8-941f-38680fa7f912.png)

I installed Jitsi Meet through "quick install" method yesterday, but I found no nginx installed.
Has there been any recent change? If there is a version change statement it is more convenient.

Question 2: 
I only found logs for jicofio and Jvb under the /var/logs/jitsi. "Jitsi Meet" should also have logs, right?
I only found the configuration file at /usr/share/jitsi-meet/logging_config.js. where is the log files?

Thanks very much.

**Comment by damencho** [comment]
By default the webserver used is jetty. If you want to use nginx, you need to install it before installing jitsi-meet.
The server side components log in /var/log/jitsi, these are jicofo and jvb. Jitsi-meet is a web client application and logs are found in the browser executing the app. You can open the js console of the browser and you will see the client logs there, there are no files with client logging.
