### ISSUE TITLE
Question about the possibility of a scenario

### ISSUE THREAD

**Issue by danionescu2007** [jitsi/jitsi-meet#2997]
Hello and thank you for developing this awesome piece of software.
I have the following scenario. I have a teacher and the students. I need the teacher to see everyone (video and audio. I need the students to be able to choose if they want not to be visible to the other students (aka only to the teacher) or to everyone. Is this possible in any way with the Jitsi software?
Thank you in advance!

**Comment by bbaldino** [comment]
Hey Dan, currently this wouldn't be possible with Jitsi.  To get this sort of selective forwarding (the students deciding who can and can't see them, but the teacher always being allowed to) would take some non-trivial work.

**Comment by danionescu2007** [comment]
Thank you for your prompt response. Any suggestion on what to look into, some other software?

**Comment by bbaldino** [comment]
There are other SFUs like Janus but I have no idea if they support this.
