### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by ankurkloud** [jitsi/jitsi-meet#2998]
Integrated Jitsi in iOS custom app. The audio is always muted. Tried to unmute it but it is not happening. Any help is appreciated.

**Comment by ankurkloud** [comment]
Any one? I am stuck with this. The mic icon shows muted always. Nothing is happening even after pressing the icon.

**Comment by saghul** [comment]
What logs do you get? How are you loading the URLs? Any extra config parameters related to starting the call muted / audio-only?

**Comment by ankurkloud** [comment]
Thank you for getting back to me as I am struggling from long. 

The code line is simple as given on https://github.com/jitsi/jitsi-meet/tree/master/ios. 
JitsiMeetView *jitsiMeetView = (JitsiMeetView *) self.view;
    NSString *fullName = @"xxxxxx";
  NSString *url = [NSString stringWithFormat:@"https://meet.jit.si/%@",fullName];
  jitsiMeetView.delegate = self;
  [jitsiMeetView loadURLObject:@{
                                 @"config": @{
                                     @"startWithAudioMuted": @"NO",
                                     @"startWithVideoMuted": @"NO"
                                     },
                                 @"url":url
                                 }];

Video start well but mic icon shows muted. I tap it  but cant unmute it.
![img_0913](https://user-images.githubusercontent.com/11850299/40277157-336280ca-5c38-11e8-8c22-6e68a0e73ccb.png)

I didnt get much of log but below is one
<<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_Presence (client: )

I am including the example project. I tried it in this one and also my original customer app but at both place i am getting same problem. 
https://github.com/ankurkloud/test-jitsi

Let me know if you need more details.

**Comment by saghul** [comment]
> @"startWithAudioMuted": @"NO",
> @"startWithVideoMuted": @"NO"

These are the default values, so you don't need to specify them. But if you do, they are booleans, not strings, so you must use the proper syntax: 

~~~
JitsiMeetView *jitsiMeetView = (JitsiMeetView *) self.view;
NSString *fullName = @"xxxxxx";
NSString *url = [NSString stringWithFormat:@"https://meet.jit.si/%@",fullName];
jitsiMeetView.delegate = self;
[jitsiMeetView loadURLObject:@{
    @"config": @{
        @"startWithAudioMuted": @NO,
        @"startWithVideoMuted": @NO
    },
    @"url":url
}];
~~~

**Comment by ankurkloud** [comment]
Thank you Saghul for solving the problem and it was a silly mistake from my part.
Now when I changed the code in my test project it is working fine but in my customer project audio is not working at call. Mic button can be muted/un-muted. I am getting below logs.

[CallKitCallUIAdaptee] Received provider(_:perform:) CXSetMutedCallAction
2018-05-21 16:51:31:702 [347:20059] [CallKitCallUIAdaptee] Failing CXSetMutedCallAction for unknown call: A93A4FAB-D899-4D4A-9473-EFD064512401
2018-05-21 16:51:31:725 [347:20059] [CallKitCallUIAdaptee] Timed out provider(_:timedOutPerforming:) while performing <CXSetMutedCallAction 0x1c427bf80 UUID=079D3DAC-4E85-4F93-AE6B-2998557A57E4 state=2 commitDate=2018-05-21 11:21:05 +0000 failureReason=2 callUUID=A93A4FAB-D899-4D4A-9473-EFD064512401 muted=0>

Any reason for this? In the custom project we are also using 'Signal' (https://github.com/signalapp/Signal-iOS).

**Comment by saghul** [comment]
@ankurkloud I assume you mean the CallKit UI mute button? We (Jitsi) use CallKit, so does Signal, so I suspect there might be some fight over the CallKit state. I'm not sure what to suggest here. You could try to disable the CallKit integration on either and see if it works...

**Comment by saghul** [comment]
Import and set this to false: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/callkit/JMCallKitProxy.swift#L51

This may not fix it, however. I don't know what Signal does internally, but I do know Jitsi Meet works. It's possible the combination of both together is the problem. iOS contains many singletons such as AVAusioSession, which controls the global audio session, and all components of the app need to be aware of it and cooperate.

**Comment by ankurkloud** [comment]
I tried to do that but it not helping me. Any other pointers you think of?

**Comment by saghul** [comment]
I'm sorry, I don't know anything else which could help you 😢

**Comment by ankurkloud** [comment]
OK. Thank you for all your help and support.

**Comment by ankurkloud** [comment]
Any body,
Could you please help me? The audio is not working in Jitsi only.

**Comment by ankurkloud** [comment]
Guys, I am able to solve the issue. We have to enable the audio variable of RTCAudioSession class

**Comment by ankurkloud** [comment]
We are able to solve the issue. We need to enable the Audio of class RTCAudioSession. 

Thank you @sahul for your help.

**Comment by saghul** [comment]
I'm glad you solved it! I'm going to close this then.

**Comment by aniltaha** [comment]
> Guys, I am able to solve the issue. We have to enable the audio variable of RTCAudioSession class

Thank you :)

**Comment by ccs1428** [comment]
Audio and Video is muted when i am joined from an iOS device. Other platforms its working .
Is there any customisation required on ios.

**Comment by ccs1428** [comment]
@ankurkloud @saghul I am facing same issue , please help.

**Comment by aniltaha** [comment]
Hi @ccs1428,  i added this code.
` do{
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playAndRecord)
            try AVAudioSession.sharedInstance().setMode(.videoChat)
        }catch{
            print("Error")
        }
        audioSession.isRTCAudioEnabled = true
`

**Comment by ccs1428** [comment]
@aniltaha Thank you for response.

Which file i need to change, please confirm.

I am using latest jitsi meet, in sdk found "AudioMode.m" file.

For me both Audio and Video are mute when i joined in a meeting using iPhone. Other two platform its working fine, Android to Web and Web to Android working fine.

**Comment by ccs1428** [comment]
@aniltaha 

Session configuration is already there:

```   videoCallConfig = [[RTCAudioSessionConfiguration alloc] init];
        videoCallConfig.category = AVAudioSessionCategoryPlayAndRecord;
        videoCallConfig.categoryOptions = AVAudioSessionCategoryOptionAllowBluetooth;
        videoCallConfig.mode = AVAudioSessionModeVideoChat;```

Not found this properties : 

audioSession.isRTCAudioEnabled = true

Log data error

[JitsiMeetSDK] [modules/xmpp/strophe.jingle.js] Marking session from kkkk@conference./focus as *not* P2P
2020-06-09 14:26:23.183980+0530 jitsi-meet[4844:1313979] [JitsiMeetSDK] [JitsiConference.js] Failed to send E2E ping request or response. undefined

**Comment by aniltaha** [comment]
Hi, you must add your code from calling jitsimeet :) 9 Haz 2020 12:18 tarihinde ccs1428 <notifications@github.com> yazdı:
@aniltaha
Session configuration is already there:
        videoCallConfig.category = AVAudioSessionCategoryPlayAndRecord;
        videoCallConfig.categoryOptions = AVAudioSessionCategoryOptionAllowBluetooth;
        videoCallConfig.mode = AVAudioSessionModeVideoChat;```

Not found this properties : 

audioSession.isRTCAudioEnabled = true

Log data error

[JitsiMeetSDK] [modules/xmpp/strophe.jingle.js] Marking session from kkkk@conference./focus as *not* P2P
2020-06-09 14:26:23.183980+0530 jitsi-meet[4844:1313979] [JitsiMeetSDK] [JitsiConference.js] Failed to send E2E ping request or response. undefined

**Comment by ccs1428** [comment]
@aniltaha 

Same code i have tried in JitsiMeet / AppDelegate method.

```    AVAudioSession *_session = [AVAudioSession sharedInstance];
    [_session setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
    [_session setMode:AVAudioSessionModeVoiceChat error:nil];
    RTCAudioSession *session = [RTCAudioSession sharedInstance];
    session.isAudioEnabled = true;```

still audio and video are muted for other users.

**Comment by rachits21** [comment]
@ccs1428 @aniltaha Same problem I am facing, did you guys found the solution ?

**Comment by zsinba** [comment]
me too

**Comment by saghul** [comment]
This issue is 4 years old. Please open a new one, the likelihood of it being the same problem is very small. Be sure to provide as many details as possible.
