### ISSUE TITLE
No podspec found for `RNSound`

### ISSUE THREAD

**Issue by MLNomiss** [jitsi/jitsi-meet#2999]
Fetching podspec for `RNSound` from `../node_modules/react-native-sound`
[!] No podspec found for `RNSound` in `../node_modules/react-native-sound`

**Comment by MLNomiss** [comment]
when cd ios and pod install

**Comment by saghul** [comment]
Have you installed all dependencies with `npm install` beforehand?

**Comment by ramanmacchavel** [comment]
run this command

npm i react-native-audio
