### ISSUE TITLE
Alternative video layouts

### ISSUE THREAD

**Issue by yanas** [jitsi/jitsi-meet#30]
Allow the user to choose between other video layouts, e.g. show more than one participants in large resolution or allow the user to show/ hide the remote participants.

**Comment by danboid** [comment]
+1

During one-on-one chats it would be useful to be able to split the display horizontally or vertically between the two callers or just show the other caller.

This is a must for webcasters.

**Comment by thekyriarchy** [comment]
yes! https://talky.io/ does this as do many others. was surprised it is not an option on an otherwise very complete app. It would also be awesome to allow people to join as chatters-only first, without requiring broadcasting audio/video as in #688
