### ISSUE TITLE
Jicofo exception upon conference start - Maximum members limit reached in meet

### ISSUE THREAD

**Issue by max-schoebel** [jitsi/jitsi-meet#3000]
Hi!

I am hitting a wall trying to deploy jitsi meet manually on an arch-linux box. Prosody, jicofo and Jitsi-videobridge are running on the same machine. Upon entering a conference with the first user, jicofo throws an IllegalArgumentException and the confernce seems to disconnect immediately. After an automatic reconnect, the webinterface prints "Maximum members limit reached".

I am running:

jitsi-meet_3053 (tag: 2797). I am only getting the blue background screen without any other response using the latest commit.

Jicofo tag 413

Jitsi-videobrige assembly 1056

jicofog-log: https://pastebin.com/kQh0RnZ5

videobrige-log: https://pastebin.com/CtdUTcHi

prosody-log: https://pastebin.com/Tkt0suLT

config.js: https://pastebin.com/qr33sVKN

prosody.cfg.lua: https://pastebin.com/ynvHtdar

Any help is very much appreciated.

Thanks a lot and keep up the good work!

**Comment by guanzixin** [comment]
Hi , I am facing the same error ...
Does your issue fixed ? @max-schoebel 
Thanks.

**Comment by damencho** [comment]
https://community.jitsi.org/t/jitsi-users-jicofo-exception-upon-conference-start-maximum-members-limit-reached/13884/5?u=damencho

Also check this out: 
https://github.com/jitsi/jitsi-meet/issues/3247#issuecomment-404452732
