### ISSUE TITLE
All icons display failed when I install the app on an android device

### ISSUE THREAD

**Issue by anyanyan07** [jitsi/jitsi-meet#3001]
All icons can't display in the android app by a release apk but can when I debug install. are there some config files that I should do?

**Comment by lyubomir** [comment]
Are you building your own app? Have you modified the source code of jitsi-meet? The icons of jitsi-meet are defined in a font so there are usually problems with them when the font is not correctly bundled in the apk.

**Comment by anyanyan07** [comment]
I resolved the problem by coping  the fonts folder from  sdk/build/..bundle/debug/assets/fonts  to sdk/build/..bundle/release/assets/. But I think this is not a good solution because the build folder should not be edited.

**Comment by CPLASF1925** [comment]
@lyubomir I also encountered this situation, modify the source code, how to bind the font correctly.
