### ISSUE TITLE
Change the page that enters the room name

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3002]
I want to change the style of the page that entered the name of the room. Which file should I modify?

**Comment by saghul** [comment]
See:

- https://github.com/jitsi/jitsi-meet/blob/master/react/features/welcome/components/WelcomePage.web.js
- https://github.com/jitsi/jitsi-meet/blob/master/css/_welcome_page.scss

**Comment by c526537207** [comment]
@saghul I use a quick install, and I can't find the welcome_page file in Linux.

**Comment by saghul** [comment]
You cannot edit the resulting files, you'll need to build the web from source.

**Comment by c526537207** [comment]
@saghul How to modify in source code, how to generate after modification?

**Comment by saghul** [comment]
Please, have a look in the README, it's all written there.
