### ISSUE TITLE
Etherpad icon do not shown in latest jitsi meet 

### ISSUE THREAD

**Issue by cheelibrahmaiah** [jitsi/jitsi-meet#3011]
Hi @damencho,

I run jitsi meet in my loacal 

I have enable **etherpad_base: MY DOMAIN**,  in **MYDOMAIN-config.js**

I have observed it is enough to enable etherpad in older releases, but JITSI latest release build it is not working.

Please help us

Thanks.

**Comment by saghul** [comment]
The etherpad button has been moved to the "three-dots" menu. 

<img width="259" alt="screen shot 2018-05-22 at 10 33 49" src="https://user-images.githubusercontent.com/317464/40351031-b5cbcc46-5dab-11e8-94a6-ed41b0a8cebb.png">

Do you not see it there?

**Comment by cheelibrahmaiah** [comment]
Yes, I'm unable to see open shared document option on three-dot menu.

**Comment by cheelibrahmaiah** [comment]
Hi @saghul,

I am unable to see the **Open shared document** option from Three-dots menu bar,

> I have enable etherpad_base: MY DOMAIN, in MYDOMAIN-config.js

or Please suggest me, How to quick install older JITSI-MEET stable version.

Thanks.

**Comment by damencho** [comment]
Hi, @chadwallacehart are you using default interface_config.js file? 
There, in TOOLBAR_BUTTONS you should have 'etherpad' is that value there?

**Comment by cheelibrahmaiah** [comment]
Hi @damencho, I haven't changed, it is default interface_config.js file, in this file TOOLBAR_BUTTONS also have 'etherpad' value.
Please fix this issue ASAP.
Thanks.

**Comment by damencho** [comment]
@chadwallacehart Can you send me an URL to your deployment so I can test it myself (damencho at jitsi.org). 
There is nothing to fix at the moment as it seems to work fine, check meet.jit.si.

**Comment by damencho** [comment]
@chadwallacehart Check your jicofo logs for errors. 
It seems jicofo is not connecting to the room and not advertising the etherpad document to be used ... 
Your deployment is broken and will be working only in p2p mode and if you add a third participant you will not see any media.

**Comment by damencho** [comment]
Yes, it will be fixed. 
Check your prosody config do you have ssl configuration for your auth domain like:
https://github.com/jitsi/jitsi-meet/blob/master/doc/example-config-files/prosody.cfg.lua.example#L184
And that you have those auth certs available on the system.
You can then try running `update-ca-certficates -f` and restart jicofo and see is it fixed.
And also there is a workaround for it: https://github.com/jitsi/jitsi-meet/issues/2676#issuecomment-377039435

**Comment by cheelibrahmaiah** [comment]
Hi @damencho I have used workaround for testing purpose 

>  I have added to /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true

Etherpad icon now appear and it's working fine :) .


> Check your prosody config do you have ssl configuration for your auth domain like

There is no auth domain configured here.

I was deployed  JITSI MEET in my production server, we had lot of problems regarding video like  **Video has been turned off to save bandwidth ** it appear very often,(version is  **jitsi-meet 1.0.2794**)
so we are planning to upgrade latest version, is this problems may resolved for latest jitsi build??

Thanks for your support.

**Comment by damencho** [comment]
There were fixes in the bridge to improve connectivity. But "Video has been turned off to save bandwidth" can be a real problem, and there were fixes to not turn off video for the onstage participant.
