### ISSUE TITLE
Improve failure messages

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#302]
Currently we fail with a generic message that does not include any detail or hints on how to resolve the problem or gather information. As a result there issues are opened without any details provided. The message should have a link to show more details about the failure if possible, and a link that explains where the log files are located and how to contact us (i.e. write to dev@jitsi.org) with sufficient details.

**Comment by akuckartz** [comment]
:+1: for more informative error messages

**Comment by bgrozev** [comment]
The messages have been improved. We should open new issues for problems with specific existing messages.
