### ISSUE TITLE
Always show profile names on thumnails in meeting?

### ISSUE THREAD

**Issue by ChillarAnand** [jitsi/jitsi-meet#3022]
Right now, on mouse hover on thumbnail, it shows name. Sometimes because of network issues or some other reason, users get disconnected. It will be better if we can always show name on profiles.

In mobile phones, it never shows profile name during a meeting.

**Comment by saghul** [comment]
Hi!



> Right now, on mouse hover on thumbnail, it shows name. Sometimes because of network issues or some other reason, users get disconnected. It will be better if we can always show name on profiles.

That would mean the text is on top of the video / avatar, which is not a good user experience, I'd say.

> In mobile phones, it never shows profile name during a meeting.

This is on our todo list.
