### ISSUE TITLE
invitees api iframe issue

### ISSUE THREAD

**Issue by m-zizzi** [jitsi/jitsi-meet#3024]
Hi, i'm using the JitsiMeetExternalAPI and i'm trying to invite someone in my conference with the function invite.

api.invite([{...}, {...}, {...}]).then(function() {
    // success
}).catch(function() {
    // failure
});

I can't find the format of the js object's array for the invitees, and the log is poor.
Can someone help me with this array format?
Thank you.

**Comment by AlexMart123** [comment]
Any update on this issue?

Thanks.

**Comment by saghul** [comment]
This is some functionality which depends on an abstract service you need to have running yourself. There is no full invitation mechanism baked in.

The API for this service is alas not documented.

**Comment by AlexMart123** [comment]
Thank you for the quick reply but it is still unclear to me 
how I can make an invitation usung JitsiMeetExternalAPI?

Now I'm investigating the feasibility of implementation a webrtc video conference with Jitsi
and everything looks promising to me, but I do not understand how one user can call another.

My Jitsi-meet is installed on Ubuntu 14.04 using apt-get. 

I'm following this guide: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md 

In my script an object of JitsiMeetExternalAPI type is created successfully.
Then a Jitsy local video appears in my browser.  

And what should I do next? 
Should I write something like below?:

```
jitsiApi = new JitsiMeetExternalAPI(domain, options);
jitsiApi.invite([{server:"myserver.com", user: "another_user"}]).then(function() { ...
```


What standards, protocols, etc... should implement this “abstract service”?
How JitsiMeetExternalAPI should interact with a such service? 
Is there any documentation, examples how to make a call with JitsiMeetExternalAPI?

Is it possible to make an invitation on https://meet.jit.si/?

Please correct me if I have any misunderstanding.

Thanks.

**Comment by saghul** [comment]
@DigitalCoder That function relies on you developing a backend service. In its current state I recommend you ignore it and implement an out of band invitation process.

**Comment by DigitalCoder** [comment]
allright but can you tell us how to use this method ?

I'm planning to use an other development to schedule it but if Icould use a native method from jitsi directly it could be great :D
