### ISSUE TITLE
Pb sharing document - not working no error message

### ISSUE THREAD

**Issue by Spartacus2018** [jitsi/jitsi-meet#3025]
Hello, 
so i insalled jisti ee on ubuntu 16.04

i m using it on local network, not on internet, 

so i have an invalide certificat, 
![image](https://user-images.githubusercontent.com/301074/40415791-04c81eb4-5e7c-11e8-8360-8b028977419f.png)

so works, i can create a room people can go on the room.

WIth firefox last version, i can share my screen, but other user can't see my screen.

WIth Ie and CHOME, i don't have the icone sharing screen.

can u please expain me how add the sharing screen function works for all navigateur. and even works firefox to firefox

thanks

**Comment by saghul** [comment]
Hi there!

> WIth firefox last version, i can share my screen, but other user can't see my screen.

What package versions have you installed? Does it work for you on meet.jit.si? I just tried it Firefox to Firefox and it worked.



> WIth Ie and CHOME, i don't have the icone sharing screen.

IE is not supported for screen sharing. For Chrome you need to deploy your own extension, see https://github.com/jitsi/jidesha
