### ISSUE TITLE
Deprecating Permissions in Cross-Origin Iframes

### ISSUE THREAD

**Issue by havid0707** [jitsi/jitsi-meet#3034]
When I embed Jitsi Meet as iframe to another react project.
I encounter the "Deprecating Permissions in Cross-Origin Iframes" problem .
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

I think many people will integrate like me，So I would like to ask if there are other ways besides modifying external_api.js

**Comment by havid0707** [comment]
according to the link, we need to add attribute allow.. to iframe
for example: <iframe src="https://example.com" allow="geolocation; microphone; camera"></iframe>

**Comment by saghul** [comment]
That has already been fixed a while ago: https://github.com/jitsi/jitsi-meet/commit/46ccefdfe9046b2e2cfa88698480cc962b53c588#diff-5b40c189a18f8b2c3896fae0d0f80089

**Comment by havid0707** [comment]
@saghul 

I follow the steps of ``` https://jitsi.org/downloads/ubuntu-debian-installations-instructions/``` to install
However, Only ``` external_api.min.js``` but not ```external_api.js``` file can be found in the ```/usr/share/jitsi-meet/libs``` directory

if I reference external_api.min.js file, I will encounter error ```only one instance of babel-polyfill is allowed```
![image](https://user-images.githubusercontent.com/9440277/40520656-f6156550-5ff9-11e8-99ac-7606402cbedd.png)

![image](https://user-images.githubusercontent.com/9440277/40520688-21625574-5ffa-11e8-8cc7-c41e88a27e11.png)

------------------------------------------------------
I have another previous installation,```external_api.js``` file is found and I can reference it without error.
![image](https://user-images.githubusercontent.com/9440277/40520904-43e55672-5ffb-11e8-9f0c-2b354e3abacf.png)
