### ISSUE TITLE
Webcam active while screen sharing

### ISSUE THREAD

**Issue by kevin-og** [jitsi/jitsi-meet#3038]
A feature request.  Would it be possible to keep the speaker's video visible still while s/he is screen sharing?  This should also translate the same if Jibri live streaming is being leveraged.  Picture in a picture, or in this case, webcam overlay ontop of the screenshare.

**Comment by jondo** [comment]
Can this be reopened, please, even without current development plans in this direction? I'd like to get updates about this, even if it is only years.

**Comment by damencho** [comment]
This is already available on meet.jit.si.
