### ISSUE TITLE
Restrict conference creation to privileged users via a configuration option

### ISSUE THREAD

**Issue by tigre-bleu** [jitsi/jitsi-meet#304]
For small installations of jitsi-meet, it could be too ressource consuming to allow the whole internet to create conferences. Additionnaly, there is a lack of control of who is using the platform.

It would be nice to add a configuration feature that makes it possible to select the users allowed to create a conference. All other users would be allowed to attend.

Ideally, those authorised users could be retrieved from an LDAP request.

**Comment by damencho** [comment]
Please use the mailinglist [1] as requested.
Check the documentation [2] where you can find how to restrict room's
creation only for registered users. You can also configure prosody to use ldap. All these are already present and implemented. 

[1] https://github.com/jitsi/jitsi-meet#discuss
[2] https://github.com/jitsi/jicofo#secure-domain
