### ISSUE TITLE
`clientNode` setting in `jitsi.conf`

### ISSUE THREAD

**Issue by christian-korneck** [jitsi/jitsi-meet#3054]
Hello,

I've installed a `jitsi-meet` instance by following the Quick Setup instructions. Everything seems to work at a very first look (thanks for the good docs!)

However, I wonder: In the `jitsi.conf` there's a setting for which the installer didn't replace the hostname:
```
The name of client node advertised in XEP-0115 'c' stanza
clientNode: 'http://jitsi.org/jitsimeet'
```

What would be the correct `clientNode` setting for a self-hosted server `jitsi.example.com`?

Best,
Chris

**Comment by damencho** [comment]
You don't need to change this, this is a xmlns in the xmpp messages that are beeing sent from the client and I'm not sure, at the moment, but changing it may break some features.

**Comment by christian-korneck** [comment]
thank you
