### ISSUE TITLE
 o.find is not a function

### ISSUE THREAD

**Issue by wilane** [jitsi/jitsi-meet#3056]
Trying to provide https://jitsi-api.jitsi.net/directorySearch to my Jitsi Meet Instance. I'm using token auth and as soon I start typing in the 'Invite people to this meeting dialog' I get the "We stumbled a bit" message and the console reads:

`[react/features/base/react/components/web/MultiSelectAutocomplete.js] <>:  MultiSelectAutocomplete error in query TypeError: o.find is not a function
    at VM64909 app.bundle.min.js:formatted:73066` 
......

            } else
                m = Promise.resolve({});
            return Promise.all([p, m]).then(function(e) {
                var t = a(e, 2)
                  , o = t[0]
                  , i = t[1]
                  , s = [].concat(r(o));
                return o.find(function(e) {
                    return "phone" === e.type
                }) || "boolean" != typeof i.allow || s.push({
                    allowed: i.allow,
                    country: i.country,
                    type: "phone",
                    number: i.phone,
                    originalEntry: n,
                    showCountryCodeReminder: !h
                }),
                s
            })
        }

Any direction?
Thanks in advance

**Comment by damencho** [comment]
You cannot use https://jitsi-api.jitsi.net/directorySearch (as it is meet.jit.si specific and has its own token setting), you need to implement your directory search and feed it with data specific to your deployment.

**Comment by wilane** [comment]
@damencho thanks for the comment, I'm not using https://jitsi-api.jitsi.net/directorySearch, I'm actually trying to implementing my own directory search  when I hit this error. I was wondering if there's any reason I'm getting that message when my directory search returns a result?

**Comment by wilane** [comment]
@damencho the code above seems to be the minified version of react/features/invite/functions.js:



            /**
             * This check for phone results is for the day the call to searching
             * people might return phone results as well. When that day comes
             * this check will make it so the server checks are honored and the
             * local appending of the number is not done. The local appending of
             * the phone number can then be cleaned up when convenient.
             */
            const hasPhoneResult
                = peopleResults.find(result => result.type === 'phone');

            if (!hasPhoneResult && typeof phoneResults.allow === 'boolean') {
                results.push({
                    allowed: phoneResults.allow,
                    country: phoneResults.country,
                    type: 'phone',
                    number: phoneResults.phone,
                    originalEntry: text,
                    showCountryCodeReminder: !hasCountryCode
                });
            }

            return results;
        });
}
Thanks for your time.

**Comment by damencho** [comment]
When you are implementing it, do you return an array of results?
Like: [{"id":"some-id","name":"Damian Minkov","type":"user","avatar":"link-to-avatar"}]

**Comment by wilane** [comment]
Thanks @damencho I didn't and the error disappeared as soon as I did  ... sorry for the noise I should have known better. Thanks for your time, appreciated.

**Comment by damencho** [comment]
Well, we need to better document it, a good place for contribution :) you can document your success story :)

**Comment by wilane** [comment]
@damencho I will for sure, thanks
