### ISSUE TITLE
Etherpad issue after re-join

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#306]
Description:
- An  authenticated user (through shibboleth) creates a room.
- Other participants join the room (authentication is not required)
- They edit an Etherpad document.
- The authenticated user (who seems to be the owner of the Etherpad) leaves the room (e.g technical issue)
- Then he comes back to the room and relaunches the Etherpad.
- Now he has got a new instance of Etherpad which different of other users
- They can't edit the same document anymore.

**Comment by paweldomas** [comment]
Another scenario that breaks etherpad is when authentication is disabled and moderator reloads the page - he and any next participants won't have etherpad button enabled. That's because only moderator includes etherpad instance name in presence and after he leaves we loose it.

In scenario with authentication multiple etherpad names are generated as we have multiple moderators joining the room.

**Comment by paweldomas** [comment]
I'm planning to move etherpad name generation to Jicofo.

**Comment by emcho** [comment]
Which would also be better from a security perspective

**Comment by paweldomas** [comment]
Fixed in:

jitsi-meet: 3f9b220ee9c44e169a1fb11689a9af5cab5283e8
jicofo: da386db7494c44ee0f1be8aa9f200f0b0e42a88c
