### ISSUE TITLE
Self-hosted : video crash after startup

### ISSUE THREAD

**Issue by yagu0** [jitsi/jitsi-meet#308]
I installed jitsi-meet following the quick install for Debian Wheezy, and then tried both openJDK (6 & 7) and Oracle JRE (7).

I use the last version of chromium (but also tried with google chrome) on my client machine. Local video is showing properly, but remote one (in the corner) disappear after initialization (a few seconds).

What could I try to fix this annoying problem ?

EDIT: probably same issue as described here https://github.com/jitsi/jitsi-meet/issues/234

**Comment by Kidav** [comment]
I am also spent some time for this issue and found this errors in log of jvb
```javascript
Sctp send error: : Resource temporarily unavailable
SEVERE: [29] org.jitsi.videobridge.Conference.error() Failed to send message on data channel.
java.io.IOException: Failed to send the data
```

jicofo.log 
```javascript
SEVERE: [52] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.initiateSession().135 Timeout waiting for session-accept from 1122334@conference.meet.jit.si/7217db9a
INFO: [52] org.jitsi.jicofo.JitsiMeetConference.discoverFeaturesAndInvite().588 Expiring 1122334@conference.meet.jit.si/7217db9a channels - participant has left
SEVERE: [55] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.initiateSession().135 Timeout waiting for session-accept from 1122334@conference.meet.jit.si/0936319a
INFO: [55] org.jitsi.jicofo.JitsiMeetConference.discoverFeaturesAndInvite().588 Expiring 1122334@conference.meet.jit.si/0936319a channels - participant has left
```
so I suppose for quick workaround you can downgrade jicofo to 1.0-68-1 (that helped me)

**Comment by yanas** [comment]
Forwarded to the dev mailing list. Please follow up here: http://lists.jitsi.org/pipermail/dev/2015-July/024688.html. We’re trying to keep all questions and discussions on the mailing list and only create issues for well identified problems.
