### ISSUE TITLE
Cannot connect 3+ people to conference, was working fine previously

### ISSUE THREAD

**Issue by Arccosyne** [jitsi/jitsi-meet#3081]
I've had a jitsi-meet server running successfully for about a year until yesterday it suddenly stopped working when there were more than 3 people in the room. Peer2peer seems to work fine still, but breaks when a third client joins. It seems to be something to do with the videobridge not picking it up. I dont see any useful errors in jicofo, jvb or prosody logs. I've seen many others have similar issues that result from faulty NAT configs, but our network does not use NAT.

I had had the Jitsi packages pinned in apt to prevent them from  updating, I recently updated to attempt to fix it, but no luck. 

Our users are presently using skype for their audioconferences. Needless to say this is subpar and I would like to get this back online as soon as possible.

Anyone have any ideas?

-Andrew

**Comment by Arccosyne** [comment]
I should also say, I had this problem while I was building out the server initially, the only way I could resolve it was to rebuild the server from an image, basically start from scratch. Starting over is not really a possibility now as that server also runs a rocket.chat instance. This is unrelated and doesn't affect Jitsi.

I've read @damencho 's help which leads me to think it might be something to do with Prosody's auth certificates.

**Comment by damencho** [comment]
Hum, this is strange with the /tmp folder. Do you see any files written there by jvb user?
