### ISSUE TITLE
Mini video shows instability

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3085]
When multiple video, the small video on the right side shows instability, sometimes not.But there is no problem when I click to switch to video. How does this happen?

![3](https://user-images.githubusercontent.com/31339057/40899970-0fb34c0c-67fc-11e8-9d63-ef6a79bf75aa.jpg)

**Comment by havid0707** [comment]
I also encountered this problem

**Comment by havid0707** [comment]
This problem seems to have only recently
