### ISSUE TITLE
Improper Copyright removal, please add the original Copyright back

### ISSUE THREAD

**Issue by bear** [jitsi/jitsi-meet#309]
Commit 
https://github.com/jitsi/jitsi-meet/commit/8380a7bb9dc1529826f73ac5db7a53c51710baf0 removes the original Copyright notice.

http://opensource.org/faq#preserve-copyright-notices explains why this is not allowed.

**Comment by fippo** [comment]
@emcho I'm "concerned".

**Comment by bear** [comment]
I feel this has been handled/covered by the revert commit here

https://github.com/jitsi/jitsi-meet/commit/5f48e4cf9d5c809c3fea2fee58563bc0eb748718
