### ISSUE TITLE
[Android] Bug in fixed conference

### ISSUE THREAD

**Issue by driesken** [jitsi/jitsi-meet#3090]
When I modify the Server URL in the settings to start with a specific conference (by using a "/" after the domain), the app opens the conference on start but a few bugs are introduced by this:

- It's not possible to hangup the conference within the app.
- It's not possible to modify or show up the sidebar (and thus settings) anymore.

**Comment by driesken** [comment]
Hi,

The URL is [https://meet-new.uzgent.be/bla1234](url)

**Comment by saghul** [comment]
@driesken are you using that URL as the "Server URL". What are you entering there exactly? Also, can you please reply to my other questions?

**Comment by driesken** [comment]
Sorry, answered on my phone and overlooked some of your questions.

That's correct, I've entered "https://meet-new.uzgent.be/bla1234" as the Server URL.

I can see the other participant and the red hangup button is visible. After I hang up (using the button), it appears as the conference is disconnecting and it briefly shows a loading icon on top of the video. Afterwards the screen refreshes once while it stays in the conference.

**Comment by saghul** [comment]
I understand now. What you're trying to do is not supported. The server URL must point to the server, not a conference. I'll make sure this is fixed so a URL like that is rejected.

What is your use case? Maybe we can find a different way to achieve what you want.

**Comment by driesken** [comment]
Ah, I see.

I'm trying to achieve that a user will automatically join a specific conference on the app start (by defining the conference name in a setting).  Or a list of conference(s) that gets populated by some kind of file/http request.

**Comment by saghul** [comment]
Gotcha. I'm not sure if we have that anywhere in our roadmap.

Would having a link which makes the app join a specific conference help? You could have this link anywhere: an email, website, etc.

If you create a link such as `org.jitsi.meet:https://your-server.com/room` the Jitsi Meet app will open and join that room automagically.

**Comment by driesken** [comment]
Thanks!

I've written a simple page that calls the manifest url you described on click and added it to the homescreen afterwards.

**Comment by saghul** [comment]
Cool, I'm going to close this then, cheers!
