### ISSUE TITLE
remove some of the functions shown on android and ios

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3100]
I want to remove some of the functions shown on android and ios, where can I change them?

**Comment by saghul** [comment]
What do you want to remove exactly? Here are the toolbox buttons that get rendered on mobile: https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/native/Toolbox.js#L208-L224

you'd need to remove some from there and rebuild the SDK.
