### ISSUE TITLE
JWT usage on meet.jit.si server

### ISSUE THREAD

**Issue by prawnsalad** [jitsi/jitsi-meet#3101]
Apologies if this is the wrong place to ask but the IRC channel is dead for some time.

Looking at the Meet API i see that it has a JWT token option. Does this do anything if were using the meet.jit.si server? Specifically I'm looking at authorising users to join a room and to gain mod/admin status in the room.

**Comment by saghul** [comment]
> Looking at the Meet API i see that it has a JWT token option. Does this do anything if were using the meet.jit.si server?

You can use it to set the user's display name and avatar.

> pecifically I'm looking at authorising users to join a room and to gain mod/admin status in the room.

That would work if you enable token authentication, but you need to do that on your own server.

**Comment by prawnsalad** [comment]
Thanks @saghul. Are there any docs on what data the token should contain for the display name, room and role?

**Comment by damencho** [comment]
Here is some more information: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

**Comment by prawnsalad** [comment]
Ah it's documented in that repo, I see. I don't see anything about setting the roles though?

**Comment by damencho** [comment]
Yep, when you configure token, you can enable this property:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L244

And some of the features will be available only for those using the token, the rest will be treated as guests.

**Comment by prawnsalad** [comment]
Ok, so to allow access to a room with only a valid token and to set the role from a property in the token, I would need to:
1. Enable the JWT token authentication Prosody plugin
2. Pass the JWT token with an added "role" property
3. Keep the enableUserRolesBasedOnToken config = false
4. Modify this prosody plugin somehow to read the "role" property from the token? https://github.com/jitsi/jitsi-meet/blob/6a3e4bb59ff6bda20d4775c374e6602a2a82edb7/resources/prosody-plugins/mod_muc_allowners.lua#L11

I'm not sure how I should be modifying point 4? Or if that's even the correct place

**Comment by KerryRitterWaa** [comment]
Is there a workflow diagram on how JWTs can work with jitsi/jicofo? I'm very confused by it.

**Comment by damencho** [comment]
No there is no such diagram. Basically, there are some UI changes when you enable enableUserRolesBasedOnToken, like inviting people, dialing out, recording, stuff like that is not available for guests. 

Then prosody has also can give/deny access to certain rooms based on the token data, but this is explained in https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md. Jicofo doesn't understand anything about tokens. Everything stops in prosody. 
There is some data that is pushed in the clients' presence which then can be used in jibri and that is all. 
There are also some modules in prosody for filtering based on token, to not allow dialing out for example, if someone changes his UI to enable it :) https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_filter_iq_rayo.lua
