### ISSUE TITLE
Missing comma on config.js

### ISSUE THREAD

**Issue by andrekutianski** [jitsi/jitsi-meet#3102]
Hello folks!

We have try install the jitsi meeting through the repositorie, but we have a issue with startup of the conference room. Looking into the `config.js` file we found a missing comma on line 22

https://github.com/jitsi/jitsi-meet/blob/master/config.js#L22

After correct this, all works fine!

credits to @cleverzamp

**Comment by damencho** [comment]
You got missing comma cause you uncommented some of the lines after the line you had provided, right?
In default installation this works and nothing is missing. 
We should soon have some work scheduled around configuration and things should be way easier.
