### ISSUE TITLE
Android app disconnecting

### ISSUE THREAD

**Issue by kkar** [jitsi/jitsi-meet#3103]
Hello, we have tried jitsi-meet with two different browsers on PC and it's working as expected. Wonderful quality of video and sound as always!

The problem is that when we try to communicate with the android application, it says "disconnected" and no matter how many times we tap on "rejoin now", nothing happens.

Is this a known issue?
Thank you!

**Comment by damencho** [comment]
Are you using your own deployment? The mobile app will work only with valid certificates.

**Comment by kkar** [comment]
@damencho yes, I am using the self-hosted solution, installed by following "quick install" guidelines, and provided my Let's Encrypt certificate and Key file. I just noticed that if i "CANCEL" the connection retries and type the room name ("test") manually, it enters a room just like it was a different one, although the name is the same. Would it be useful if I share my room link with you?

**Comment by damencho** [comment]
When you just type just a room name it uses by default meet.jit.si. You can share the link.
What you can try is open the link of your deployment in the browser, preferably in private/incognito,  on the mobile and see whether it gives you a warning, if that is the case that's the problem for not connecting.

**Comment by kkar** [comment]
[Here](https://conference.think-free.net/test) is my test room, I am currently logged in too, from Chrome on PC.

**Comment by damencho** [comment]
Yeah I don't see a problem opening it from my mobile browser but the app is not connecting I will ask someone from @jitsi/mobile to chime in for help?

**Comment by kkar** [comment]
@damencho thank you so much. Will this issue be updated or I have to create an issue there?

**Comment by kkar** [comment]
@damencho sorry for "spamming". Perhaps I should try to re-issue certificates from within jitsi-meet before we ask help from jitsi/mobile? Is there a way to force jitsi to re-issue Let's Encrypt certs?

**Comment by damencho** [comment]
I'm not sure what 'there' you mean. But this is enough. Mobile code is here in this repo.
