### ISSUE TITLE
Jitsi-meet keeps disconnecting all of us

### ISSUE THREAD

**Issue by kkar** [jitsi/jitsi-meet#3105]
Hello,
we are facing an issue here. We tried to communicate in a one-to-one chat, and everything went as expected. We added a third person and we could keep communicating normally. After a "kick" for one of the persons, we all are getting a disconnect loop for reasons we can't understand.

[Here is our test-room](https://conference.think-free.net/test), and [here is the screenshot of the disconnect-loop](https://ibb.co/gKjGL8).

No matter how long we let it trying, or manually refreshing the page, we get an immediate disconnect.

Thank you for your help in advance.

**Comment by kkar** [comment]
Just noticed that after about 10 minutes of letting it retry to connect, the connection is made normally and we can use the room again. How can we see the reasons for this strange behavior...?

**Comment by damencho** [comment]
You need to open the js console when you see the reload screen and save the logs, there should be something about it, focus missing, or jvb missing.
You can also check jicofo logs for errors.

**Comment by kkar** [comment]
@damencho could you give me some directions on how to do this, since I am not familiar...?

**Comment by damencho** [comment]
To open javascript console in Chrome you have View -> Developer -> JavaScript Console.

**Comment by kkar** [comment]
I have "tailed" the jicofo.log file and tried the following. I entered the (same) room, alone and got the log output below.

```
Jicofo 2018-06-06 20:58:39.354 INFORMATION: [69] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: test@conference.conference.think-free.net
Jicofo 2018-06-06 20:58:39.354 INFORMATION: [69] org.jitsi.jicofo.FocusManager.log() Created new focus for test@conference.conference.think-free.net@auth.conference.think-free.net conferences count: 1 options:
    channelLastN: -1
    enableLipSync: true
    openSctp: true
    disableRtx: false
Jicofo 2018-06-06 20:58:39.355 INFORMATION: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Lip-sync enabled in test@conference.conference.think-free.net
Jicofo 2018-06-06 20:58:39.355 INFORMATION: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: test@conference.conference.think-free.net
Jicofo 2018-06-06 20:58:39.670 INFORMATION: [45] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@15bb4630 member=ChatMember[test@conference.conference.think-free.net/ed262dd2, jid: null]@1398025111]
Jicofo 2018-06-06 20:58:39.673 INFORMATION: [45] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to test@conference.conference.think-free.net/ed262dd2
Jicofo 2018-06-06 20:58:39.673 INFORMATION: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member test@conference.conference.think-free.net/ed262dd2 joined.
```

Then I asked my partner to join me in the same room, and we both got a disconnect. The following log output was captured.

```
Jicofo 2018-06-06 21:03:45.127 INFORMATION: [81] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: test@conference.conference.think-free.net
Jicofo 2018-06-06 21:03:45.312 INFORMATION: [45] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@15bb4630 member=ChatMember[test@conference.conference.think-free.net/bdd42e06, jid: null]@1517669256]
Jicofo 2018-06-06 21:03:45.313 INFORMATION: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member test@conference.conference.think-free.net/bdd42e06 joined.
Jicofo 2018-06-06 21:03:45.313 SCHWERWIEGEND: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2018-06-06 21:03:45.313 SCHWERWIEGEND: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2018-06-06 21:03:45.942 INFORMATION: [45] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@15bb4630 member=ChatMember[test@conference.conference.think-free.net/bdd42e06, jid: null]@1517669256]
Jicofo 2018-06-06 21:03:45.942 INFORMATION: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member test@conference.conference.think-free.net/bdd42e06 is leaving
Jicofo 2018-06-06 21:03:45.942 INFORMATION: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, test@conference.conference.think-free.net/bdd42e06
Jicofo 2018-06-06 21:03:46.179 INFORMATION: [45] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@15bb4630 member=ChatMember[test@conference.conference.think-free.net/ed262dd2, jid: ed262dd2-e757-4dd6-b4f5-5fb419efea57@conference.think-free.net/5d12b608-d072-4b68-81fe-c67cc15d4e73]@1398025111]
Jicofo 2018-06-06 21:03:46.180 INFORMATION: [45] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2018-06-06 21:03:46.180 INFORMATION: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member test@conference.conference.think-free.net/ed262dd2 is leaving
Jicofo 2018-06-06 21:03:46.180 INFORMATION: [45] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, test@conference.conference.think-free.net/ed262dd2
Jicofo 2018-06-06 21:03:46.181 INFORMATION: [45] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: test@conference.conference.think-free.net conference count: 0
```

I hope it helps. If there is any other information I can provide, I will be happy to do so.

**Comment by damencho** [comment]
Nope it doesn't help, this just proves the thing I already tested and I see there is no jvb. Can you look at my comment:
https://github.com/jitsi/jitsi-meet/issues/3105#issuecomment-395167568
Can you search all your jicofo logs for "Too many open files", it should happen in the past.

**Comment by kkar** [comment]
@damencho I restarted jitsi-videobridge several times, I have also tried to see if there are any "too many open files"-strings in jicofo logs but nope. Nothing like that.

```
root@h2782615:~# cat /var/log/jitsi/jicofo.log | grep "Too many open files"
root@h2782615:~#

```

**Comment by damencho** [comment]
Ok, so if you have restarted jitsi-videobridge and jicofo still do not see it there must be another problem. Check jvb logs for errors, do you see any?
Can you send all jicofo logs(even the old ones) so I can check them and to see why it lost the jvb. It was working in the beginning right?

**Comment by kkar** [comment]
@damencho of course, how may I send you the logs? I can create a pastebin with jicofo logs if it's ok with you.

**Comment by damencho** [comment]
Upload an archive somewhere, I suppose that they are multiple files. If you want to send them to me personally damencho AT jitsi.org.

**Comment by kkar** [comment]
I have only two files in the logs directory, but never deleted any lines so I suppose they are complete. Uploading now. I will post the link here, thank you so much for your help @damencho .. !!!

**Comment by kkar** [comment]
@damencho [here](https://files.fm/u/cjg8w6aj#_) is the logs archive.

**Comment by damencho** [comment]
jitsi-logs.rar is not RAR archive

**Comment by kkar** [comment]
What do you mean? Just created it with WinRAR...

**Comment by damencho** [comment]
No idea, my UnRarX client says so. Maybe use some other more common format.

**Comment by kkar** [comment]
ZIP archive [here](https://files.fm/u/d9pcdbgk)

**Comment by damencho** [comment]
Here is why there is no jvb registered in jicofo, cause jvb failed to respond to a health check:
Health check failed on: jitsi-videobridge.conference.think-free.net error: timeout
Removing JVB: jitsi-videobridge.conference.think-free.net
Looking at the same time in jvb log you can see:

JVB 2018-06-06 19:44:43.845 SCHWERWIEGEND: [285] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[pool-5-thread-9,5,main] and message was: unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread

Apparently, there is not enough memory for jvb and jicofo on that machine, fix that and restart both jvb and jicofo in this order.

**Comment by kkar** [comment]
So, all I have to do, is ask my provider to add more RAM to the server?

**Comment by damencho** [comment]
I don't know your infrastructure, it is your decision what to do ... you may decide to have more machines than you can distribute multiple bridges on multiple machines. 
What is the current memory capacity of that machine?

**Comment by kkar** [comment]
root@h2782615:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           2048         396        1599           9          51        1538
Swap:             0           0           0
root@h2782615:~#

**Comment by damencho** [comment]
So both jicofo and jvb are started with -Xmx3072m which means only for them the memory can go up to 6GB and you should leave some for the OS and the other processes, like prosody and maybe webserver ... So 2GB really too optimistic.

**Comment by kkar** [comment]
Upgraded my plan to an 8GB memory. You were the most helpful person I've ever met on github. Thank you for your support and patience!

**Comment by naveenpatidar** [comment]
# **Hi All,

# I am sucessfully connected by the peer client  but after 20-30 seconds , both get disconnected.**
Following is the error message shown in the JS console.

[modules/xmpp/JingleSessionPC.js] <r.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed P2P? false:	 45369.399999966845
app.bundle.min.js?v=2872:2 [modules/UI/videolayout/VideoLayout.js] <Object.removeParticipantContainer>:  Removing remote video: 52e72c0d
app.bundle.min.js?v=2872:2 [modules/UI/videolayout/RemoteVideo.js] <r.remove>:  Remove thumbnail 52e72c0d
app.bundle.min.js?v=2872:2 [modules/UI/videolayout/VideoLayout.js] <Object.electLastVisibleVideo>:  Last visible video no longer exists
app.bundle.min.js?v=2872:2 [modules/UI/videolayout/VideoLayout.js] <Object.electLastVisibleVideo>:  Fallback to local video...
app.bundle.min.js?v=2872:2 [modules/UI/videolayout/VideoLayout.js] <Object.electLastVisibleVideo>:  electLastVisibleVideo: 2e7591e9
lib-jitsi-meet.min.js?v=2872:2 [modules/RTC/TraceablePeerConnection.js] <r.close>:  Closing TPC[2,p2p:false]...
lib-jitsi-meet.min.js?v=2872:2 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught TypeError: Cannot read property 'updateView' of undefined Script: https://SERVER DOMAIN NAME/libs/lib-jitsi-meet.min.js?v=2872 Line: 2 Column: 1033665 StackTrace:  TypeError: Cannot read property 'updateView' of undefined
    at Object.updateLargeVideo (app.bundle.min.js?v=2872:2)
    at Object._updateLargeVideoIfDisplayed (app.bundle.min.js?v=2872:2)
    at Object.onRemoteStreamRemoved (app.bundle.min.js?v=2872:2)
    at Object.S.removeRemoteStream (app.bundle.min.js?v=2872:2)
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at Object.dispatch (app.bundle.min.js?v=2872:2)
    at n.<anonymous> (app.bundle.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at r.<anonymous> (lib-jitsi-meet.min.js?v=2872:2)
    at Array.forEach (<anonymous>)
    at r.onRemoteTrackRemoved (lib-jitsi-meet.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at r._removeRemoteTrack (lib-jitsi-meet.min.js?v=2872:2)
    at r.close (lib-jitsi-meet.min.js?v=2872:2)
    at t.value (lib-jitsi-meet.min.js?v=2872:2)
    at r.leave (lib-jitsi-meet.min.js?v=2872:2)
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at Object.dispatch (app.bundle.min.js?v=2872:2)
    at e.value (app.bundle.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at n.<anonymous> (lib-jitsi-meet.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at r.peerconnection.oniceconnectionstatechange (lib-jitsi-meet.min.js?v=2872:2)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (lib-jitsi-meet.min.js?v=2872:2)
n @ lib-jitsi-meet.min.js?v=2872:2
getGlobalOnErrorHandler @ lib-jitsi-meet.min.js?v=2872:2
window.onerror @ app.bundle.min.js?v=2872:2
lib-jitsi-meet.min.js?v=2872:2 Uncaught TypeError: Cannot read property 'updateView' of undefined
    at Object.updateLargeVideo (app.bundle.min.js?v=2872:2)
    at Object._updateLargeVideoIfDisplayed (app.bundle.min.js?v=2872:2)
    at Object.onRemoteStreamRemoved (app.bundle.min.js?v=2872:2)
    at Object.S.removeRemoteStream (app.bundle.min.js?v=2872:2)
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at Object.dispatch (app.bundle.min.js?v=2872:2)
    at n.<anonymous> (app.bundle.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at r.<anonymous> (lib-jitsi-meet.min.js?v=2872:2)
    at Array.forEach (<anonymous>)
    at r.onRemoteTrackRemoved (lib-jitsi-meet.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at r._removeRemoteTrack (lib-jitsi-meet.min.js?v=2872:2)
    at r.close (lib-jitsi-meet.min.js?v=2872:2)
    at t.value (lib-jitsi-meet.min.js?v=2872:2)
    at r.leave (lib-jitsi-meet.min.js?v=2872:2)
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at app.bundle.min.js?v=2872:2
    at Object.dispatch (app.bundle.min.js?v=2872:2)
    at e.value (app.bundle.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at n.<anonymous> (lib-jitsi-meet.min.js?v=2872:2)
    at n.emit (lib-jitsi-meet.min.js?v=2872:2)
    at r.peerconnection.oniceconnectionstatechange (lib-jitsi-meet.min.js?v=2872:2)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (lib-jitsi-meet.min.js?v=2872:2)
updateLargeVideo @ app.bundle.min.js?v=2872:2
_updateLargeVideoIfDisplayed @ app.bundle.min.js?v=2872:2
onRemoteStreamRemoved @ app.bundle.min.js?v=2872:2
S.removeRemoteStream @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
n.emit @ lib-jitsi-meet.min.js?v=2872:2
(anonymous) @ lib-jitsi-meet.min.js?v=2872:2
r.onRemoteTrackRemoved @ lib-jitsi-meet.min.js?v=2872:2
n.emit @ lib-jitsi-meet.min.js?v=2872:2
r._removeRemoteTrack @ lib-jitsi-meet.min.js?v=2872:2
r.close @ lib-jitsi-meet.min.js?v=2872:2
value @ lib-jitsi-meet.min.js?v=2872:2
r.leave @ lib-jitsi-meet.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
(anonymous) @ app.bundle.min.js?v=2872:2
value @ app.bundle.min.js?v=2872:2
n.emit @ lib-jitsi-meet.min.js?v=2872:2
(anonymous) @ lib-jitsi-meet.min.js?v=2872:2
n.emit @ lib-jitsi-meet.min.js?v=2872:2
peerconnection.oniceconnectionstatechange @ lib-jitsi-meet.min.js?v=2872:2
peerconnection.oniceconnectionstatechange @ lib-jitsi-meet.min.js?v=2872:2
lib-jitsi-meet.min.js?v=2872:2 [modules/xmpp/JingleSessionPC.js] <r.peerconnection.oniceconnectionstatechange>:  (TIME) ICE closed P2P? false:	 45532.3999999091
lib-jitsi-meet.min.js?v=2872:2 (TIME) Render video:	 45572.799999965355
lib-jitsi-meet.min.js?v=2872:2 (TIME) TTFM video:	 24422.49999998603
app.bundle.min.js?v=2872:2 [modules/UI/videolayout/LargeVideoManager.js] <>:  hover in %s 2e7591e9

**Comment by naveenpatidar** [comment]
after running  free -m I still have 668MB free space. Do I really need to increase the RAM??

              total        used        free      shared  buff/cache   available
Mem:           1906         564         668           6         673        1116
Swap:             0           0           0

**Comment by saghul** [comment]
> [modules/xmpp/JingleSessionPC.js] <r.peerconnection.oniceconnectionstatechange>: (TIME) ICE failed P2P? false: 45369.399999966845

Looks like a connectivity error.

**Comment by naveenpatidar** [comment]
But we both are on the same network and my network speed returned by https://fast.com/ is 9.1 Mbps

**Comment by damencho** [comment]
Check your network, ICE failures are due to the network. Are you also behind this ip address 85.214.103.72 or it is used only for jvb? Sometimes firewalls do not allow coming out of the NAT and connecting to the address of the nat box.
And strangely, not sure if this is still the case, looking at old logs, but your jvb advertises 0:0:0:0:0:0:0:2 as an address, it doesn't seem as a correct ip address, this should be fixed, although it will not cause ICE to fail.

Ooo wait, @naveenpatidar is your problem has something to do with @kkar's one?

**Comment by naveenpatidar** [comment]
Can you tell me what need to be set for getting over this issue, means in which file with what parameter??

 If **Sometimes firewalls do not allow coming out of the NAT and connecting to the address of the nat box.** this is the case the case then what is the possible solution for it.

**Comment by naveenpatidar** [comment]
**Resolved.**

I am using org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<DOMAIN NAME> insted of <IP ADDRESS>

**Comment by LeeChanWu** [comment]
@naveenpatidar 
Where did you change IP ADDRESS?
I am a fresher for jitsi.
Regards

**Comment by LeeChanWu** [comment]
I installed jitsi-meet by following guide video in my own server(ubuntu16.04).
Install were completed successfully.
When 2 users join to room, they connected.
But they are disconnected after 20seconds.
What is mistake?

**Comment by damencho** [comment]
@LeeChanWu Check javascrip console logs.

Please in the future when you have questions or problems, before opening an issue or writing to an already closed one, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
