### ISSUE TITLE
Make _BACKGROUND_BLUR temporary flag permanent and bring it to stable branch

### ISSUE THREAD

**Issue by cmilanf** [jitsi/jitsi-meet#3108]
I have been working in making jitsi-meet working at acceptable speed with a Raspberry Pi 3, something that I successfully accomplished by:

1. [Implementing ffmpeg with h264 hardware acceleration enabled for the Pi](https://www.raspberrypi.org/forums/viewtopic.php?t=199775).
2. In Chromium web browser, go to `chrome://flags` and enable `#enable-webrtc-h264-with-openh264-ffmpeg`
3. Configure jitsi-meet webcam capture restrictions to 480p

With these steps, jitsi-meet can work quite well in a Raspberry Pi 3 **if _BACKGROUND_BLUR is set to off**. It looks like the blur process takes a significant performance hit in a limited device. Hence, I consider it would be important to keep this option permanent or make `off` the default setting.

**Comment by saghul** [comment]
What do you mean by permanent exactly? If you modify interface_config.js to set it to 'off' it will remain that way.

**Comment by cmilanf** [comment]
I am referring to the comment of the configuration option:
```/**
     * Temporary feature flag to debug performance with the large video
     * background blur. On initial implementation, blur was always enabled so a
     * falsy value here will be used to keep blur enabled, as will the value
     * "video", and will render the blur over a video element. The value
     * "canvas" will display the blur over a canvas element, while the value
     * "off" will prevent the background from rendering.
     */
    _BACKGROUND_BLUR: 'canvas'
```
I am requesting that this feature flag should be permanent.

**Comment by virtuacoplenny** [comment]
I ran it by Emil and others and the sentiment is to keep the flag. I might have to change the name though, maybe rename it to DISABLE_BACKGROUND_BLUR but at least remove the underscore prefix.

This was good timing because I already made a PR to clean up this flag.

**Comment by cmilanf** [comment]
I'm glad this request made in time before that PR :)

**Comment by virtuacoplenny** [comment]
interfaceConfig. DISABLE_VIDEO_BACKGROUND is in master now.

**Comment by cmilanf** [comment]
I will test it as soon as I can :)

**Comment by saghul** [comment]
I'm going to close this since we have the new setting inplace now. Thanks for binging this up @cmilanf and thanks for actually fixing it @virtuacoplenny !

**Comment by ThiesDuke** [comment]
Dear cmilanf,
you mention that you get jitsi running on chromium on raspberry with acceptible performance. I have followed the instructions but to no avail- Jitsi on my device is a blurry, delayed mess. The chrome flag for h264 I cannot change since it is under the category "unavailable for your device" and I am unable to configure anything in jitsi, since I only call the URL and not install anything. Would you mind pointing me in the right direction? I have been searching quite a while.

**Comment by cmilanf** [comment]
It looks like you are not following completely the instructions:

  1. You must follow every single step in [the tutorial](https://www.raspberrypi.org/forums/viewtopic.php?t=199775). No exceptions, it takes time. Ensure you have Raspbian Strecth and a Pi 3. 
  2. You must be able to configure Jitsi, so it implies you must setup your own server instance, so you can lower the resolution, force h264 codec and bring up the background flag. You can't modify these on the hosted version.

**Comment by ThiesDuke** [comment]
Thank you for the reply! The stunning tutorial of Mike I have followed to the Ietter. I stumbled over the issue that I cannot install the jitsi-meet server, since it complains about unmet dependencies for the videobridge and Jicofo. I followed all advises to solve that like install java8 etc. (like so: https://github.com/jitsi/jitsi-meet/issues/2248). But I can't resolve that issue. Trying to install videobridge and jicofo seperately I get the remark that no installation candidate is available. (also nginx is installed and running smoothly). Have you encountered the same issue?

**Comment by cmilanf** [comment]
The quick install worked for me, but anyway I just learned you are able to turn on the DISABLE_VIDEO_BACKGROUND in the hosted version as reference in #3232

**Comment by damencho** [comment]
@ThiesDuke do you have java8 installed?

**Comment by ThiesDuke** [comment]
To make sure I have not messed up my system beforehand here is what I did:
Blank SD card- put on Raspbian stretch latest image from RPI website (put on ssh and wifi)
Installing nginx: https://www.raspberrypi.org/documentation/remote-access/web-server/nginx.md
checked java -version:
java -version
pi@raspberrypi:~ $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
Then I follow the instruction on quick install https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md and get:
The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-videobridge (= 1077-1) but it is not installable
              Depends: jicofo (= 1.0-425-1) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by cmilanf** [comment]
The Jitsi server is NOT to be installed in the Pi, but in another powerfull x86 or x64 machine. The Pi is already short of power just in the client side, so bettee not even think installing the server there. The Pi just need the Chromium web browser and the setup in the tutorial I pointed.

**Comment by ThiesDuke** [comment]
Hi- thank you for the support, it's really highly appreciated! I followed the tutorial and mpv play's all the 1080p content etc perfectly. However in Chromium browser visiting chrome://flags the mentioned flag (#enable-webrtc-h264-with-openh264-ffmpeg) does not exist. I checked however the browser versions for chromium and while in my version 65.0.... does not have the flag in an earlier version 56.0... it appears. (also the general appearance of the chrome://flags page was redesigned apparently). Have you also tried with chromium 65 or newer? Have you added a certain "open with.." behavior to use ffmpeg within the browser?

**Comment by cmilanf** [comment]
I don't recall the Chromium version I used, but it was definitely the one in Raspbian Stretch. You have [several versions](http://archive.raspbian.org/raspbian/pool/main/c/chromium-browser/) to select in the same distro. If latest one, 68, do not have the flag, maybe you can use 57.
