### ISSUE TITLE
Just A Query

### ISSUE THREAD

**Issue by 91Abdullah** [jitsi/jitsi-meet#3109]
Hi,

Thanks for developing such an amazing and robust application. I've just started to use it and it been so excited.

I'm trying to use it in production. But I want to ask if application can support upto 500 users simultaneously? Is it possible?

Regards

**Comment by saghul** [comment]
Hi!

Thanks or the kind words!

You mean a single room with 500 connected users? Or 500 users total, spread across multiple rooms?

**Comment by tanvir23** [comment]
ya @saghul i also have the same question.
1. can I have a conference with 500 users total?
2. can i have my server 500 users having conference in multiple room?

**Comment by 91Abdullah** [comment]
Yes a single room with 500 connected users

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 91Abdullah** [comment]
Hi,

Any update on this?

**Comment by saghul** [comment]
Please use our [community forum](https://community.jitsi.org/) for such questions, we are trying to keep GitHub only for issues and feature requests. Thanks for understanding.
