### ISSUE TITLE
jitsi meet api [object%20Object] 404 failure

### ISSUE THREAD

**Issue by tansaku** [jitsi/jitsi-meet#3112]
We've set up our own jitsi server at http://www.jitsi.agileventures.org/ and were trying to embed it in https://www.paironauts.org/mob however we get a 404 error when the iframe attempts to load stuff from http://www.jitsi.agileventures.org/

![](https://dl.dropbox.com/s/5lfu3208b7484q3/Screenshot%202018-06-08%2012.21.36.png?dl=0)

we think it's trying to load the external_api.js, but this weird bit of js is getting inserted:

![](https://dl.dropbox.com/s/mrwmtv3k7e9hqz7/Screenshot%202018-06-08%2012.22.18.png?dl=0)

I assume this is a problem created from configuration of our jitsi server - has anyone ever seen anything like this or know a good way to debug it?

**Comment by saghul** [comment]
How are you trying to embed it? Please paste a snippet of what you are currently doing.

**Comment by tansaku** [comment]
We have a [template](https://github.com/AgileVentures/Paironauts/blob/26_test_av_jitsi/lib/paironauts_web/templates/page/mob.html.eex)

```html
<div id="meet">

</div>
<script src="https://www.jitsi.agileventures.org/external_api.js"></script>
```

Our embedding works just fine for meet.jit.si btw, and then the [javascript](https://github.com/AgileVentures/Paironauts/blob/26_test_av_jitsi/assets/js/pairing.js) we are using is

```js
if(typeof JitsiMeetExternalAPI != "undefined") {
  var domain = "www.jitsi.agileventures.org";
  var options = {
      roomName: window.location.pathname.substr(1),
      width: 700,
      height: 700,
      parentNode: document.querySelector('#meet')
  }
  var api = new JitsiMeetExternalAPI(domain, options);
}
```

So embedding all works completely fine with meet.jit.si and we just tried with our own jitsi installation at https://www.jitsi.agileventures.org and we get the failure above, so we are assuming it's the configuration of our jitsi server that's at fault.  I was just looking there for all the places that might affect requests for the external_api:

```
sam@AVJitsyServer:~$ sudo grep -l -r "external_api" /
/usr/share/jitsi-meet/libs/external_api.js.map
/usr/share/jitsi-meet/libs/external_api.min.map
/usr/share/jitsi-meet/libs/app.bundle.min.map
/usr/share/jitsi-meet/libs/app.bundle.js.map
/usr/share/jitsi-meet/libs/app.bundle.min.js
/usr/share/jitsi-meet/libs/external_api.js
/usr/share/jitsi-meet/libs/app.bundle.js
/usr/share/jitsi-meet/libs/device_selection_popup_bundle.min.js
/usr/share/jitsi-meet/libs/external_api.min.js
/usr/share/jitsi-meet/libs/device_selection_popup_bundle.min.map
/usr/share/doc/jitsi-meet-web-config/jitsi-meet.example
```

The main config file for that server is at https://gist.github.com/tansaku/af48764d1d10097033e453d34277557b

I wonder if there is something in there that's the problem, or maybe just the version of jitsi we have on our server, but not even sure how to check which version we are running ...
