### ISSUE TITLE
Verify room name format

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#312]
We should add room name format validation at least at the welcome page.

**Comment by subtildreams** [comment]
yes it will be nice if in the welcome page, we could not allow special caractere or space in the room box

no more 404

**Comment by spellauge** [comment]
yes, this would be nice an would increase usability and acceptance. once, a user sees a 404 caused by an illegal room name the risk is high that he will refrain from using jitsi meet.

**Comment by kolAflash** [comment]
+1
This would be really useful!
Just spend 10 Minutes, trying to find out which characters I could use for a certain room name.

By the way: Why are no underscores and hyphens possible?
And if underscores where possible, you could also enable spaces and automatically transform them into underscores.

**Comment by roeycohen** [comment]
it would be really nice to know how to add support for an underscore or an hyphen...

**Comment by spellauge** [comment]
it should not bevery  hard to do this (less than 20 lines of code), but i feel there are discussions in the background (for at least 18 months -> low priority) on how to deal with this.

**Comment by saghul** [comment]
Sometimes things fall through the cracks, sorry about that. If you are up for it, a PR would be most welcome.

**Comment by ZuzooVn** [comment]
@saghul 
We have some user demand on special characters use for room names in JItsi-meet.

1. Open /etc/nginx/sites-available/chat.example.net.conf

2. Change 

```
    location ~ ^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }

    location / {
        ssi on;
    }
```

to

```
    # location ~ ^/([a-zA-Z0-9=\?]+)$ {
    #    rewrite ^/(.*)$ / break;
    # }

    location / {
        ssi on;
        try_files $uri /index.html;
    }
```

3. Restart Nginx:

```
service nginx restart
```

**Comment by c526537207** [comment]
I changed it as you suggested, but it is currently only available on the web, and Android and ios are still not supported.

**Comment by TheLastProject** [comment]
Can this be reopened? This is still an issue.

**Comment by Deltachaos** [comment]
We also have this issue

**Comment by damencho** [comment]
@Deltachaos I'm about the revert this change. Can you tell me the use case that it was fixing? We do not want to limit the input, for example currently you can create rooms with cyrilic letters and there is no problem of having those rooms.

**Comment by damencho** [comment]
I will modify the pattern to be something like only excluding some chars like & :, will check what is allowed currently in the nginx on meet.jit.si and will also update the default ngxin rules when installing the packages.

**Comment by bluikko** [comment]
Jitsi docker container seems to have this issue.

**Comment by Deltachaos** [comment]
@damencho there is a problem with slashes in the conference name
