### ISSUE TITLE
Trying to disable Calendar, got a TypeError after connection to a room

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#3128]
I builded my Jitsi Meet App for Android, cloning the latest stable release (2740) from github (commit 784d94b30f403707b9812ff02998f791f5ea094e), released on the first of May.
I tried to disable the Calendar modifying in this way the function  _isCalendarEnabled():
function _isCalendarEnabled() {
    // PATCH 
    **return false;**
    //
    const { calendarEnabled } = NativeModules.AppInfo;
    return typeof calendarEnabled === 'undefined' ? true : calendarEnabled;
}
contained in the file react\features\calendar-sync\constants.js

The toolbar with the two buttons, History and Calendar, disappears from the WelcomePage, but after trying a connection to a room I get this error:

TypeError: undefined is not an object (evaluating 'state['features/calendar-sync'].events')

This error is located at:
    in Connect(ConferenceNotification) (created by Translate(Connect(ConferenceNotification)))
    in Translate(Connect(ConferenceNotification)) (at Conference.native.js:237)
    in RCTView (at View.js:112)
    in View (created by Container)
    in Container (at Conference.native.js:191)
    in Conference (created by Connect(Conference))
    in Connect(Conference) (created by AbstractApp)
    in RCTView (at View.js:112)
    in View (at DimensionsDetector.native.js:65)
    in DimensionsDetector (at ReducedUIDetector.js:38)
    in ReducedUIDetector (created by Connect(ReducedUIDetector))
    in Connect(ReducedUIDetector) (at App.native.js:115)
    in RCTView (at View.js:112)
    in View (at DimensionsDetector.native.js:65)
    in DimensionsDetector (at AspectRatioDetector.js:37)
    in AspectRatioDetector (created by Connect(AspectRatioDetector))
    in Connect(AspectRatioDetector) (at App.native.js:114)
    in Fragment (at AbstractApp.js:311)
    in Provider (at AbstractApp.js:310)
    in I18nextProvider (at AbstractApp.js:309)
    in AbstractApp (at index.native.js:153)
    in Root (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
_mapStateToProps
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\react\features\calendar-sync\components\ConferenceNotification.native.js:277:52
mapToPropsProxy
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\connect\wrapMapToProps.js:54:102
detectFactoryAndVerify
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\connect\wrapMapToProps.js:63:24
mapToPropsProxy
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\connect\wrapMapToProps.js:54:56
handleFirstCall
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\connect\selectorFactory.js:37:33
pureFinalPropsSelector
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\connect\selectorFactory.js:85:96
runComponentSelector
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\components\connectAdvanced.js:43:39
initSelector
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\components\connectAdvanced.js:195:26
Connect(ConferenceNotification)
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-redux\lib\components\connectAdvanced.js:136:8
constructClassInstance
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1572:264
updateClassComponent
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1657:143
beginWork
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1786:44
performUnitOfWork
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2528:33
workLoop
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2554:141
_invokeGuardedCallback
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:73:23
invokeGuardedCallback
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:47:40
performWork
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2593:41
scheduleUpdateImpl
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2728:101
scheduleUpdate
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2711:38
enqueueSetState
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1514:90
setState
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react\cjs\react.development.js:237:31
<unknown>
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\react\features\app\components\AbstractApp.js:517:30
tryCallTwo
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\promise\setimmediate\core.js:45:7
doResolve
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\promise\setimmediate\core.js:200:23
Promise
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\promise\setimmediate\core.js:66:12
_navigate
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\react\features\app\components\AbstractApp.js:515:27
proxiedMethod
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-proxy\modules\createPrototypeProxy.js:44:35
tryCallOne
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\promise\setimmediate\core.js:37:14
<unknown>
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\promise\setimmediate\core.js:123:25
<unknown>
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:301:23
_callTimer
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:154:6
_callImmediatesPass
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:202:17
callImmediates
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:470:11
__callImmediates
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:275:4
<unknown>
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:140:6
__guard
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:262:6
flushedQueue
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:139:17
callFunctionReturnFlushedQueue
    C:\Users\stefano\AndroidStudioProjects\jitsi-meet-stable-2018-04-25\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:114:11

**Comment by calamatitech** [comment]
Commenting a row in the function _mapStateToProps contained in the file react\features\calendar-sync\components\ConferenceNotification.native.js, the app seems to work well

function _mapStateToProps(state: Object) {
    const { locationURL } = state['features/base/connection'];

    return {
        _aspectRatio: state['features/base/responsive-ui'].aspectRatio,
        _currentConferenceURL:
            locationURL ? getURLWithoutParamsNormalized(locationURL) : '',
	/////// PLEASE FIX ME ////////
        //_eventList: state['features/calendar-sync'].events
       /////////////////////////////////
    };
}

**Comment by lyubomir** [comment]
@zbettenbuk, could you please create a PR to fix this?

**Comment by zbettenbuk** [comment]
Hello @calamatitech, this is very similar to an issue that was addressed recently. Can you please go a bit further and check if this revision is also affected? 54b6db02d827129e822003e0e0e46a2e38a8bd40

**Comment by calamatitech** [comment]
Ok, thank you. I checked the sources of the version I'm using (2740), it does'nt contain your patch.
I will try it in a few days, when I will back nome.

**Comment by zbettenbuk** [comment]
Hello @calamatitech

Unfortunately there was a regression bug a bit after the revision I suggested, so if you go a bit later than what I wrote, you'll hit that bug. So you either need my revision, or one after this one: 0d3fac7c0ff4a8475b5fc93be239fd75a929823e

On the other hand, we're constantly focusing on keeping the master stable, so I suggest you using the latest revision, that'll be good for you.

Regarding your question of disabling the feature: yes, that way should be good for you on Android, or you can simply set the CALENDAR_ENABLED const to false, both will work. On iOS we have a native way to do it (hence the _isCalendarEnabled function), but we haven't implemented it on Android.
