### ISSUE TITLE
Android app crashing

### ISSUE THREAD

**Issue by BlackChy** [jitsi/jitsi-meet#3133]
Other user enter my room then display this：
java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3000

Why can only one user exist in my room？

**Comment by saghul** [comment]
What device and Android version are you using? What version of the app?

**Comment by BlackChy** [comment]
app version : 1.0
android version : 4.2.2

**Comment by saghul** [comment]
1.0 is ancient, any chance you can update?

**Comment by BlackChy** [comment]
Maybe it is not important. Now I discover my mobile user close video  that other user can enter the room,but  the app crash immediately with mobile user opened video.The audio is normal.

**Comment by BlackChy** [comment]
There 'oher user' mean web user, I just tried between the mobile and the web.

**Comment by saghul** [comment]
Have you tried with a more recent version of the app? We have fixed tens of issues regarding EGL, specially on old Android versions.

**Comment by saghul** [comment]
@BlackChy That shouldn't result in a crash though. We fixed a bunch of those crashes in the past couple of versions, so please update and re-test.

**Comment by CPLASF1925** [comment]
@saghul 

Android client to access their own servers how to configure, and where to add certificates to their own certificates.

**Comment by saghul** [comment]
No follow-up, closing.

@CPLASF1925 please don't hijack issues. This has nothing to do with your problem.
