### ISSUE TITLE
how to change defaultLanguage

### ISSUE THREAD

**Issue by havid0707** [jitsi/jitsi-meet#3143]
I would like to show the GUI languange as Chinese through API. 
and I have add the overwrite parameter as : configOverwrite['defaultLanguage'] = 'zhCN';

but the gui still show english, any tips? Thanks

**Comment by havid0707** [comment]
LANG_DETECTION: false in interface_config.js

**Comment by virtuacoplenny** [comment]
Seems like you're doing the right thing. I think there's an issue here with order of priority; uf you have a language saved in localstorage then that is taking priority over whatever you pass in through the config. So in localstorage you might have 'en' and so jitsi-meet will show in 'en' even if you pass 'zhCN' as the defaultLanguage.

**Comment by damencho** [comment]
The bug we have is that we always save it in localstorage. We will address it. To test it, you can just open an incognito window and you should see the default language to be zhCN.

**Comment by virtuacoplenny** [comment]
Here is the order set currently: https://github.com/jitsi/jitsi-meet/blob/259066e2c69f74257f85acbda3d05c51d0becc41/react/features/base/i18n/languageDetector.web.js#L15. So any person that visits jitsi-meet for the first time through your iframe app will have the default language set properly to zhCN. If they've ever visited before, which I assume you have, then localstorage will take priority.

**Comment by havid0707** [comment]
Thanks for all your reply. it is ok now.

**Comment by CPLASF1925** [comment]
@havid0707  How to solve it
