### ISSUE TITLE
Configuration for STUN server

### ISSUE THREAD

**Issue by SeveHo** [jitsi/jitsi-meet#3144]
Hello,

I recently run into the problem that Jitsi is not using the specified STUN servers anymore when conferencing across NATs. As a result I looked into the config of the meet.jit.si server just to have a comparison.

The config shows me this:

```p2pStunServers: [
        { urls: "stun:stun.l.google.com:19302" },
        { urls: "stun:stun1.l.google.com:19302" },
        { urls: "stun:stun2.l.google.com:19302" }
    ],
    enableP2P: true, // flag to control P2P connections
    // New P2P options
    p2p: {
        enabled: true,
        preferH264: true,
        disableH264: true,
        useStunTurn: true, // use XEP-0215 to fetch STUN and TURN server for the P2P connection
        stunServers: [
            { urls: "stun:stun.l.google.com:19302" },
            { urls: "stun:stun1.l.google.com:19302" },
            { urls: "stun:stun2.l.google.com:19302" }
        ]
    },
    useStunTurn: true, // use XEP-0215 to fetch STUN and TURN server for the JVB connection
```

I am a bit confused because I don't know which specification for the STUN servers is the one that is applied as configuration (The one inside the `p2p: {} block` or the other one). 

This is my configuration now: 
```p2p: {
        enabled: true,
        useStunTurn: true,
        stunServers: [
            { urls: 'stun:stun.meet1.comjoo.com:3478' },
	    { urls: 'stun:stun.l.google.com:19302' },
            { urls: 'stun:stun1.l.google.com:19302' },
	    { urls: 'stun:stun2.l.google.com:19302' }
        ],
        preferH264: true
        // disableH264: false,
        // backToP2PDelay: 5
    },
```

Does anyone know what is the right way to specify and enable the servers?

Thanks for your help :)

I am not sure where I need to post this question. Please correct me if I have to post this to the mailing list.

**Comment by damencho** [comment]
Under p2p section is the correct one and remove the p2pStunServers.
