### ISSUE TITLE
Enable rtcpMuxPolicy: "require"

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#315]
We should probably enable this. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/4IOADjJLpOo/ksXO7O43-cEJ

**Comment by bgrozev** [comment]
I am not sure if this is still valid or not. With the jitsi-meet client we always use rtcp-mux, and the policy should be "require". I don't know if this is now default, and whether we can just close this issue. If someone can confirm that would be helpful.

**Comment by saumeya** [comment]
"require" is the default now, and also this feature is at risk due to lack of implementation
[https://www.w3.org/TR/webrtc/#rtcrtcpmuxpolicy-enum]
So it should not be enabled now.

**Comment by bgrozev** [comment]
Thank you, @saumeya
