### ISSUE TITLE
This app cannot be approved with CallKit functionality active in China.

### ISSUE THREAD

**Issue by bhooshanpatil** [jitsi/jitsi-meet#3152]
From Apple
5. Legal: Preamble
Guideline 5.0 - Legal

Recently, the Chinese Ministry of Industry and Information Technology (MIIT) requested that CallKit functionality is deactivated in all apps available on the China App Store.

During our review, we found that your app currently includes CallKit functionality and has China listed as an available territory in App Store Connect.

Next Steps

This app cannot be approved with CallKit functionality active in China. Please make the appropriate changes and resubmit this app for review.

If you have already ensured that CallKit functionality is not active in China, you may reply to this message in Resolution Center to confirm. 

Voice over Internet Protocol (VoIP) call functionality continues to be allowed but can no longer take advantage of CallKit’s intuitive look and feel. CallKit can continue to be used in apps outside of China.

**Comment by saghul** [comment]
I assume you are using our SDK, right? If so, you can disable CallKit by setting the enabled property to false in JMCallKitProxy: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/callkit/JMCallKitProxy.swift#L51 in you app.

**Comment by bhooshanpatil** [comment]
About to close this issue but I can't find The "JMCallKitProxy.swift" file in my finder,  whats missing?
[https://www.dropbox.com/s/gilzw19qw8vhs9r/Screen%20Shot%202018-06-19%20at%2011.01.57%20AM.png?dl=0](url)

**Comment by saghul** [comment]
You seem to be running an old version of the SDK, there should be a "callkit" directory there, with this file (amongst others) inside. Please update.
