### ISSUE TITLE
Screen extention from Renater Rendez Vous

### ISSUE THREAD

**Issue by mdeneire** [jitsi/jitsi-meet#3154]
Hell,o, 
I just connected to the new app, Rendez-vous en Renater.  I could not use the sreen extension and they asked to contact you.  Also, could you tell me if we can record sessions on this app?
Thanks, Marc Deneire

**Comment by daimoc** [comment]
Hi Marc,
Rendez-vous is the French NREN jitsi-meet based service.
You should contact RENATER support for any question regarding this service (https://www.renater.fr/support) and not open issue on jitsi-meet Github.
Best Regards,
Damien.
