### ISSUE TITLE
audience GUI Control

### ISSUE THREAD

**Issue by havid0707** [jitsi/jitsi-meet#3156]
I integrate JItsi via API
I want peoples other than the conference creator to be an audience, 'audience' means that: do not show microphone and camera.

How can I achieve the following purpose?
Q1. hide filmstip bar for audience?
Q2. Audience specified to show the creator’s video

**Comment by damencho** [comment]
So this can be achieved in two ways:
1. Use live streaming and share the YouTube link
2. The creator enters the room and sets inbthe settings, the option others to start audio muted and hidden( video muted) and enables follow me, than hides the filmstrip and pins itself on the screen
The last steps from 2 can be used and when live streaming to make sure that is what you see on the stream.
Please when asking questions, do that on community.jitsi.org and do not create issues for that.

**Comment by damencho** [comment]
@havid0707 
<img width="301" alt="screen shot 2018-06-19 at 22 17 24" src="https://user-images.githubusercontent.com/3263098/41635518-cd61a244-740e-11e8-82a4-7dee34f4a634.png">
When you enable this, all other participants in the meeting will see what you see. When you pin a participant video, it will be pinned on other participants meeting interface. If you hide the filmstrip, the same will happen in their UI. Switching between different video, the same.
