### ISSUE TITLE
JITSI shows menu items in Chinese

### ISSUE THREAD

**Issue by SeshagiriSriram** [jitsi/jitsi-meet#3164]
We have implemented a JITSI server using the quick install: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
We do have a valid cert and all works fine. 
From an android client, we try to initiate a call and rarely we come across menu  items in Chinese. please help us in debugging this issue. If you need additional details, please let us know and I will update this issue accordingly. 

BTW, we do not have either Apache/NGINX installed on our server (Ubuntu 16.04) and are just following the quick install step.

**Comment by damencho** [comment]
If you open the url from the android browser, do you see a warning about the certificate?

Please, in the future, before opening issues post your questions on the community forum: https://community.jitsi.org.

**Comment by SeshagiriSriram** [comment]
Thank you Damencho for pointing to the community forum for future use. 
To answer your question, No. There are no issues. The certificate is a fully signed (not self signed certificate). When we open it from either the web browser or Android browser, it comes as fully trusted.

**Comment by damencho** [comment]
Can you send me the URL of the deployment to test it myself? If you want to send it in a private mail to damencho AT jitsi org.
