### ISSUE TITLE
Quick Install Debian 9 - Connection Refused

### ISSUE THREAD

**Issue by delpes** [jitsi/jitsi-meet#3165]
I followed the quick install guide and successfully did:
- Frech Debian 9 minimal install (without nginx/apache)
- Setup jitsi-meet  videochat.example.com as the Domain.
- Generation of the LetsEncrypt Certs also completed successfully.
- /etc/init.d/jicofo|jistsi-videobridge|prosody restart

After this im stuck:
https://videochat.example.com gives me an "Connection Refused" error

Netstat:
tcp        0      0 0.0.0.0:5269            0.0.0.0:*               LISTEN      107        31757      10351/lua5.1
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          11812      906/sshd
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      107        31766      10351/lua5.1
tcp        0      0 0.0.0.0:5281            0.0.0.0:*               LISTEN      107        31768      10351/lua5.1
tcp        0      0 127.0.0.1:5347          0.0.0.0:*               LISTEN      107        31763      10351/lua5.1
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      107        31761      10351/lua5.1

How would i proceed in debugging/fixing this?

**Edit**
Using nginx i end up receiving an SSL Protocol Error which i'm currently trying to pinpoint.
**Edit2**
I further see this error in de prosody.log:
`warn    Component not connected, bouncing error for: <iq id='lf11a-111' type='get' to='jitsi-videobridge.videochat.example.com' from='focus@auth.videochat.example.com/focus8215938711111'>`

Thx.

**Comment by damencho** [comment]
Do you see something running on port 443?

**Comment by delpes** [comment]
Thx for you reply.

Nothing was listening on port 443 until i installed Nginx with the configuration from the manual installation guide. 
With nginx running, i get an SSL Protocol Error which i haven't solved yet :/

The prosody and nginx cert files are setup correctly (imho):
> `$: ls -la /usr/local/share/ca-certificates/auth.videochat.example.com.crt
> /usr/local/share/ca-certificates/auth.videochat.example.com.crt -> /var/lib/prosody/auth.videochat.example.com.crt

> $: ls -la /etc/prosody/certs/
> auth.videochat.example.com.crt -> /var/lib/prosody/auth.videochat.example.com.crt
> auth.videochat.example.com.key -> /var/lib/prosody/auth.videochat.example.com.key
> videochat.example.com.crt -> /var/lib/prosody/videochat.example.com.crt
> videochat.example.com.key -> /var/lib/prosody/videochat.example.com.key


However i solved the `Component not connected` error by manually running the `./jvb.sh` with my configuration.

The logs won't give me any details - so right now im trying a manual installation.

**Comment by damencho** [comment]
So you didn't use the quick-install guide?

**Comment by delpes** [comment]
As stated above: yes, i did. 
But i didn't work.
Neither with nginx installed before doing the quick install nor without it.

**Comment by damencho** [comment]
Just made a quick test on new VM Debian 9 and everything works fine. I tested with nginx as you mentioned you were testing with it.

```
# history
    1  apt install nginx
    2  apt update
    3  apt install nginx
    4  echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
    5  wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
    6  apt-get update
    7  apt install apt-transport-https
    8  apt-get update
    9  apt-get -y install jitsi-meet
```

If you are experimenting on that machine you can try purging everything and start from scratch:
`apt-get --purge remove jitsi-meet jitsi-meet-web jitsi-meet-prosody
jitsi-meet-web-config jicofo jitsi-videobridge`

**Comment by delpes** [comment]
Tried the quick install again with a fresh Deb9 Image:
- No Errors during installation or letsencrypt script
- Netstat shows nothing listening on 443 ( Connection Refused)
- Connecting to example.com:8888 gives me an ssl_protocol error
- Prosody.log again shows: ` warn    Component not connected, bouncing error for [...] jitsi-videobridge` which i guess happens because the secret isn't passed correctly: 

> org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.java.command=org.jitsi.videobridge.Main --host=localhost --domain=videochat.sally-mobile.de --port=5347 --secret=X

(starting ./jvb manually with the correct params solves at least the `Compoent not connected` error
No further hints or infos for why this is happening.

Do you happen to know any other places where i can lock for hints? Shouldn't jetty log sth somewhere / what should start the web service?

**Comment by damencho** [comment]
Can you upload all your jvb log its in /var/log/jitsi? I'm interested to see why jvb doesn't start when you initially install. Or you can send it to me privately if you want (damencho AT jitsi org).

**Comment by delpes** [comment]
Ah - it works! Thank you.

So nginx seems to be mandatory to get it to work? The quick install guide isn't clear on that.

Thank you for your time.

**Comment by damencho** [comment]
No, it is not mandatory. It works without it and this is the default option because then you use 443 for serving web content and for TCP media to the bridge which can help in certain scenarios with restricted(corporate) nats.
