### ISSUE TITLE
diff: /../Podfile.lock: No such file or directory      diff: /Manifest.lock: No such file or directory error: The sandbox is not in sync with the Podfile.lock.    Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by liyongning16** [jitsi/jitsi-meet#3176]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
CLosing as is containes zero details.
