### ISSUE TITLE
diff: /../Podfile.lock: No such file or directory

### ISSUE THREAD

**Issue by liyongning16** [jitsi/jitsi-meet#3177]
here is the detail:
diff: /../Podfile.lock: No such file or directory   
  diff: /Manifest.lock: No such file or directory error: The sandbox is not in sync with the Podfile.lock. 
  Run 'pod install' or update your CocoaPods installation.

when i use Xcode to build on my phone,somthing mistake!!!
i have tried almost every solution in the internet,but it doesn't work!!!!
help!!!!!

**Comment by lyubomir** [comment]
Generally, please follow https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md step by step and you will not get the error.

Anyway, here are a couple of steps to try:
1) Close Xcode and the jitsi-meet workspace or the app project you've opened.
2) Open a Terminal, navigate to your jitsi-meet clone, execute the following in Terminal:
`pod install --project-directory=ios/`
Of course, the above assumes that you've got CocoaPods installed on your system. If the pod command fails, make sure that you have it installed.
3) Reopen the workspace or project that you had open before and retry building.
