### ISSUE TITLE
Bring participants to focus

### ISSUE THREAD

**Issue by danionescu2007** [jitsi/jitsi-meet#3189]
I could swear there was this behavior in previous versions: when the moderator was clicking a participant webcam, thus enlarging it, the other participants had the same webcam focused and enlarged.
Am I mistaken?

**Comment by damencho** [comment]
You first need to click "Everyone follows me" in settings.
<img width="273" alt="screen shot 2018-06-24 at 21 17 23" src="https://user-images.githubusercontent.com/3263098/41827258-0eb01d14-77f4-11e8-9b43-2480ee0d9ae9.png">

In the future before opening issues for asking a question or discussing a problem please use the community forum: https://community.jitsi.org as said in the issue template.
