### ISSUE TITLE
Jitsi not working in Edge 42

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#3190]
I get these errors when using meet.jit.si on the Edge (only version 42) browser. How to fix it.
`ORTC18615: ORTC RTCDtlsTransport: DTLS handshake failed. hr=c004e00f.
[modules/RTC/ortc/RTCPeerConnection.js] n.onerror>:  dtlsTransport "error" event, message:undefined`

Thank you so much.

**Comment by soundlake** [comment]
I have the same issue. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14561214/ might be related.
