### ISSUE TITLE
Import any image, not showing in apk release ?

### ISSUE THREAD

**Issue by randymuhroji** [jitsi/jitsi-meet#3194]

**Comment by randymuhroji** [comment]
import logo_text from '../../../../../../images/logo-text.png'; 

<Image source={ logo_text } style={ this.style.logo_text }/>

when in debug, image can showing.
but when release apk image not showing

**Comment by saghul** [comment]
@randymuhroji Where does that code come from? You app? I cannot find it in our SDK.

**Comment by randymuhroji** [comment]
I clone this repo, and add that code

**Comment by saghul** [comment]
Did you really think that we can realize this by reading the 8 words on your initial bug report?

You'll need to have the code which imports the image at the top level of a module, for one. Then, I'm not sure if `import` will work or you need to `require` it. See an example plus the explanation here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/participants/components/Avatar.native.js#L25

**Comment by novakzaballa** [comment]
Hi @saghul , could you please update the link you provided in you last comment on this thread? It seems it is broken.

Thanks in advance!
