### ISSUE TITLE
Linking.getInitialURL() sometimes return null when app startup android.

### ISSUE THREAD

**Issue by lilei-1** [jitsi/jitsi-meet#3199]
## Description
Linking.getInitialURL() sometimes return null when app startup android.

## Current behavior
When Android app start with a external URL(`com.haomo.jitsi.meet://a.laxalex.net:444/abc`). `Linking.getInitialURL()` return null sometimes. If I exit app totally, It works fine. But if I exit app from conference activity directly( I rewrite the hardware back button and end call button on this activity). And follow the url again. It return null sometimes, NOT ALWAYS. On Android.
## Expected Behavior
`Linking.getInitialURL()` always return the correct URL

## Steps to reproduce
Not sure. Open the URL and exit, and open..

# Environment details
Android 8.0.0 RN 0.51.0

**Comment by saghul** [comment]
Does it work correctly in the Jitsi Meet app or, if you are using the SDK, if make no changes to the SDK?

**Comment by lilei-1** [comment]
@saghul That's the Jitsi Meet app in Jitsi-Meet project, and I never make changes of SDK.

**Comment by saghul** [comment]
Got it. I'll test this.

**Comment by lilei-1** [comment]
I this they are same in me recent testing.
https://github.com/facebook/react-native/issues/15961

**Comment by xwartz** [comment]
I have same issue
