### ISSUE TITLE
Remote videos freeze after muting local video

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#320]
When local video is muted remote videos freeze from time to time. chrome://webrtc-internals reports lots of NACKs and PLIs being sent. After unmuting local video remote video is displayed fine and no more PLIs and NACKs in the stats.

This happens on Chrome 43 Windows 7 x64.

Issue https://github.com/jitsi/jitsi-meet/issues/277 is probably related.

**Comment by paweldomas** [comment]
On remote side received NACK and PLI count for frozen video stream is 0.

**Comment by paweldomas** [comment]
If [this bug] exists in Chrome 43 this will probably work fine in Chrome 44.

[this bug]: https://code.google.com/p/webrtc/issues/detail?id=4678

**Comment by paweldomas** [comment]
It does happen with Canary 46, so the bug mentioned above is not related.

**Comment by emcho** [comment]
Is anyone looking into this? We should probably get it sorted sooner rather than later.

**Comment by paweldomas** [comment]
With Chrome 44 issue is also present after switching back from screensharing to camera video. Lots of NACKs and PILs, but remote video stays frozen.

**Comment by paweldomas** [comment]
JVB complains about bad RTCP version and reports bad RTP packets for this stream in summary stats.

**Comment by paweldomas** [comment]
When we're muting local video or switching to desktop stream our old camera video is removed from peerconnection. The SSRC for this stream is also removed from peer config on the JVB by Jicofo. The bridge will no longer forward RTCP packets for this SSRC and because Chrome is using it in PLI requests they never reach the other side.

**Comment by paweldomas** [comment]
Submitted bug report[1] to WebRTC - having behaviour more consistent will help resolving the issue without too many "hacks".

[1]: https://code.google.com/p/webrtc/issues/detail?id=4883

**Comment by paweldomas** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/74e7507a7321334a53153876398dfde7237f23cd for Chrome/Opera/IE/Safari. Still needs to check Firefox once https://github.com/jitsi/jitsi-meet/issues/333 is resolved.

**Comment by paweldomas** [comment]
FF does not support removeStream, so there is no SSRC switching there and issue does not apply, so closing it for now.
