### ISSUE TITLE
Screen sharing extension failed to install

### ISSUE THREAD

**Issue by lynnefaulk** [jitsi/jitsi-meet#3204]
Hi, I use jitsi.org for online meetings. I've downloaded the extension for screen sharing, but it fails to load. Please advise. 
![screen shot 2018-06-28 at 07 59 15](https://user-images.githubusercontent.com/38556613/42018207-41d22644-7aa9-11e8-934f-d4ee2f73c921.png)
![screen shot 2018-06-28 at 07 59 32](https://user-images.githubusercontent.com/38556613/42018208-41f61248-7aa9-11e8-8776-54b5d79b6b89.png)

**Comment by saghul** [comment]
Hi! I see you are using a custom deployment on your own domain. In this case you need to create your own extension by cloning ours: https://github.com/jitsi/jidesha and modifying it for your own domain. You can find the instructions on the project itself.

This is unfortunate, but it's a Chrome limitation.
