### ISSUE TITLE
Jitsi-meet error massage

### ISSUE THREAD

**Issue by thuanbx** [jitsi/jitsi-meet#3205]
Hi all.

I installed into the quick install guide. but the latter only received the last 20 messages. I want people to see all messages afterwards how to do?

Thanks alot

**Comment by saghul** [comment]
What messages?

**Comment by thuanbx** [comment]
Hi saghul.

I will detail the error I encountered.
User 1 and user 2 joined Room A. They talked a lot.
then user 3 joins room A, user 3 sees only the last 20 messages of user 1 and user 2.

img user 1 and user chat from 1 to 30.
![1](https://user-images.githubusercontent.com/31682542/42030244-5728ed72-7afc-11e8-96d5-dded460b987c.PNG)



img user 3 just receive from 11 to 30
![2](https://user-images.githubusercontent.com/31682542/42030411-eb2c18fa-7afc-11e8-80a7-8e2804c9ee35.PNG)

thanks for answer

**Comment by damencho** [comment]
This is a prosody setting, open prosody config and set `max_history_messages` to the value you want after you save the config don't forget to restart prosody.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template.
