### ISSUE TITLE
FF support possibly broken

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#321]
It seems that something in FF functionality has been broken by https://github.com/jitsi/jitsi-meet/commit/ae759fab5b621fb77b196be17f9ff0298b8cd34d

**Comment by paweldomas** [comment]
Video issue is now fixed in https://github.com/jitsi/jitsi-meet/commit/bc935eb5dca739401b4d870f956c4ad67737559f

But even before ae759fa there are following issues:

In FF<-->FF calls:
- audio in one direction
- 3rd FF participant joins the room, but there is no media at all

FF <--> Chrome:
- seems to work fine even with 2+ participants, but there are some UI glitches related to video switching and thumbnails

**Comment by paweldomas** [comment]
FF <--> Chrome:
- UI issues were not FF specific and has been fixed in https://github.com/jitsi/jitsi-meet/commit/9b4ee7c0c5d92be6bd2c51795555299b43fdbca9

**Comment by gpolitis** [comment]
@paweldomas could you please clarify what the problem is in the FF<-->FF case? I just tested with 3 participants and the conference is fully functional, so I'm thinking that maybe we fixed the issue and forgot to close the ticket.

**Comment by paweldomas** [comment]
Hey George, it didn't worked some time ago, but it's possible that it has been fixed. Will give it another try and let you know.

**Comment by damencho** [comment]
Obsolete.
