### ISSUE TITLE
Android app can't join conference in LAN

### ISSUE THREAD

**Issue by lilei-1** [jitsi/jitsi-meet#3210]
## Description
Im using Jitsi-Meet android app in LAN with a DNS server through safe https connection. If I join a room from web side and android app. Web can see app's stream, bug app can't see web's stream. The error on app is `JitsiConference.js, Failed to accept incoming Jingle session. code:'',reason:'item-not-found',msg:'No participant found for 1530240345014@conference.a.laxalex.net/e8e7f36e',session:'JingleSessionPC[p2p=false,initiator=false,sid=3I2garn98jram'`
I also test in WAN, there is no errors reported and connecting speed is much better.
I have setted p2p to false and thirdPartyRequest to false in LAN

## Possible Solution
Jitsi-Meet do not support working in LAN, configure mistakes or network's problems.

# Environment details
In docker, ubuntu

**Comment by lilei-1** [comment]
[This is a screen shot of app](https://imgur.com/OgrnFCq)

**Comment by saghul** [comment]
do 3 web browsers work in this environment?

**Comment by lilei-1** [comment]
I resolved this issue. Android SDK has a request to `nat64.jitsi.net` and which is not reachable in LAN. Change this hostname or change DNS to any LAN server can resolve this issue. CHEERS! I'm working on this issue for two weeks : )

**Comment by lilei-1** [comment]
@saghul If you have time, please to see https://github.com/jitsi/jitsi-meet/issues/3199
