### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#322]
Test and fix bugs in Temasys plugin integration on Safari

**Comment by paweldomas** [comment]
After https://github.com/jitsi/jitsi-meet/commit/0902cbb16495e295507a93a2fc4139ee33889bf9 the plugin seems to be working, but there is an issue with jQuery fadeOut().

**Comment by emcho** [comment]
I also had problems with screen streaming, and relatively rough plugin
installation process.

On Wed, Jul 22, 2015 at 2:47 PM, Paweł Domas <notifications@github.com>
wrote:

> After 0902cbb
> <https://github.com/jitsi/jitsi-meet/commit/0902cbb16495e295507a93a2fc4139ee33889bf9>
> the plugin seems to be working, but there is an issue with jQuery fadeOut().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jitsi/jitsi-meet/issues/322#issuecomment-123709175>.
>



-- 
https://jitsi.org

**Comment by dushoff** [comment]
I have tried twice to meet with Safari users. They both installed plugin, reporting success, but still failed to join meeting.

**Comment by neufeind** [comment]
Safari 11 will add WebRTC-support. Might that help solve Safari-issues then once and for all, at least for up-to-date browsers?

**Comment by dwt** [comment]
Webkit Technology Preview includes WebRTC-Support right now <https://webkit.org/downloads/>. Is there already an effort to support this?
