### ISSUE TITLE
Request: merge Traditional Chinese translations

### ISSUE THREAD

**Issue by ztl8702** [jitsi/jitsi-meet#3224]
I can see that https://translate.jitsi.org/zh_TW/ has had 99% of translations for months and I just finished the remaining strings. 

How can a new translation language be added to Jitsi Meet? Should I create a pull request?

**Comment by bgrozev** [comment]
No, this is done through pootle. I just added zh_TW to the jitsi-meet project.

**Comment by bgrozev** [comment]
The jitsi-meet strings are not translated yet. You'll have to ping us again if you translate any of them so we can get the changes back to jitsi-meet.

**Comment by ztl8702** [comment]
Thanks.
