### ISSUE TITLE
When the room name contains a non-numeric or non-letters, jump to 404

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3227]
In https://meet.jit.si/, when the room is using non-numbers or non-letters, it can enter the room, but the project I built jumps to 404. How can I solve this problem?

**Comment by saghul** [comment]
What web server are you using and how have you configured it?

**Comment by saghul** [comment]
This part must be it:

```
    location ~^/([a-zA-Z0-9=\?]+)$ {
        rewrite ^/(.*)$ / break;
    }
```

That restricts the possibilities. I don't know how to specify support for other characters. Maybe look into the nginx documentation, this is not a problem inherent to Jitsi Meet.

**Comment by c526537207** [comment]
@saghul What should I do to support Chinese?

**Comment by saghul** [comment]
I don't know. Please check the nginx documentation.

**Comment by c526537207** [comment]
@saghul ok,thank you very much!

**Comment by damencho** [comment]
Just to mention, that those names are then used for xmpp room names. There are some restriction about what characters can a jid contain, so not sure is Chinese allowed.

**Comment by c526537207** [comment]
@damencho The room name of x'mpp is allowed in Chinese and can be encoded and decoded.The problem is that nginx will jump access to 404.

**Comment by damencho** [comment]
I'm saying that even if you fix nginx, I'm not sure about the part after nginx, how it will behave, the xmpp server (prosody). Reading this https://xmpp.org/extensions/xep-0029.html I see that the xmpp jid should be utf8, not sure how is Chinese encoded.

**Comment by c526537207** [comment]
@damencho Utf8 supports Chinese decoding, so it's still a matter of nginx regex matching.
