### ISSUE TITLE
DISABLE_VIDEO_BACKGROUND does not work in URL

### ISSUE THREAD

**Issue by linuxprocess** [jitsi/jitsi-meet#3232]
Hello,

I've read this : 
https://github.com/jitsi/jitsi-meet/issues/3108

And I want to use this DISABLE_VIDEO_BACKGROUND parameter in URL like it is mentioned possible there : 
https://github.com/jitsi/jitsi-meet/issues/2596#issuecomment-383915759

So I tested this URL with chromium : 
https://meet.jit.si/FooBar#config.resolution=360&config.constraints.video.height.ideal=360&config.constraints.video.height.max=360&config.preferH264=true&interfaceConfig.DISABLE_VIDEO_BACKGROUND=true

But background blur is still present ...

I expect the background to become black, like in Firefox.

Thanks

**Comment by saghul** [comment]
We have not yet deployed a version which includes that commit into meet.jit.si. You can test it on beta.meet.jit.si, I just did and it works as expected.

IIRC we are planning on upgrading meet.jit.si sometime next week.

**Comment by linuxprocess** [comment]
... and it has been deployed !
Thanks !
