### ISSUE TITLE
What's meaning of this warning?

### ISSUE THREAD

**Issue by lilei-1** [jitsi/jitsi-meet#3233]
`Failed to discover features of abc@conference.a.laxalex.net/3c8f9725 null
`
Is that should be `abc@conference.a.laxalex.net/focus`?

If that warning cause my android app can't set up streams to PC web in a conference?

**Comment by damencho** [comment]
This is service discovery, https://xmpp.org/extensions/xep-0030.html and is ok to fail.
On which deployment you cannot set up a conference? 
If there are two participants a p2p will be attempted and if it fails it will fallback to jvb. 

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
