### ISSUE TITLE
Labeled as Proprietary in Ubuntu Software Center 18.04

### ISSUE THREAD

**Issue by tiotrom** [jitsi/jitsi-meet#3237]
Like the title says. Installed from here https://download.jitsi.org/stable/ 
![qlppiza](https://user-images.githubusercontent.com/34804533/42545188-bc6f8cd6-84b6-11e8-96be-9449d1fdd659.png)

**Comment by damencho** [comment]
The license is Apache 2.0. https://github.com/jitsi/jicofo/blob/master/LICENSE

Please use the community forum https://community.jitsi.org, before opening issues.

**Comment by bgrozev** [comment]
I don't know why whatever application you are using shows the license as proprietary. The (`/usr/share/doc/jicofo/copyright`) was outdated (although it never had a proprietary license), so we're updating it in jicofo#301.

**Comment by tiotrom** [comment]
As stated in the title: The Ubuntu Software Center.
