### ISSUE TITLE
TURN server installation?

### ISSUE THREAD

**Issue by robertoandrade** [jitsi/jitsi-meet#324]
Following both the quick and manual installation README doesn't talk about TURN server installation/configuration at all.

I found an [old fork](https://github.com/mduggan/jitsi-meet/blob/master/INSTALL.md#install-turn-server) that still has those instructions and was wondering why they don't exist on the official repo?

**Comment by robertoandrade** [comment]
Looks like you guys have a TURN server [implementation of your own](https://github.com/jitsi/turnserver)... how does one go about connecting the dots here?

**Comment by damencho** [comment]
As jitsi-videobridge received TCP support, turn server is not needed anymore, as it was used to take the participants who has problems using UDP.
Please use our mailing list for posting question.

**Comment by robertoandrade** [comment]
Just for documentation purposes the use of `jitsi-videobridge` as both TURN and a web server replacement for `jitsi-meet` will be a default option soon (instead of `nginx` as it currently stands) according to feedback I got on the mailing list.

Additionally, as it stands today when you install using either the quick or manual instructions on the repo today, you need to do quite a bit of trickery to change it so that jvb can act as a TURN/web server as described by @damencho: http://lists.jitsi.org/pipermail/dev/2015-July/024713.html

1. Add prosody certificates to java keystore
2. Configure `authbind` to allow `jvb` to use port `443`
3. And configure jvb itself in
`/usr/share/jitsi-videobridge/.sip-communicator/sip-communicator.properties`

```
org.jitsi.videobridge.rest.jetty.host=::
org.jitsi.videobridge.rest.jetty.port=443
org.jitsi.videobridge.rest.jetty.ProxyServlet.hostHeader=example.meet.jit.si
org.jitsi.videobridge.rest.jetty.ProxyServlet.pathSpec=/http-bind
org.jitsi.videobridge.rest.jetty.ProxyServlet.proxyTo=http://localhost:5280/http-bind
org.jitsi.videobridge.rest.jetty.ResourceHandler.resourceBase=/usr/share/jitsi-meet
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./config.js=/etc/jitsi/meet/example.meet.jit.si-config.js
org.jitsi.videobridge.rest.jetty.RewriteHandler.regex=^/([a-zA-Z0-9]+)$
org.jitsi.videobridge.rest.jetty.RewriteHandler.replacement=/
org.jitsi.videobridge.rest.jetty.tls.port=443
org.jitsi.videobridge.TCP_HARVESTER_PORT=443
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePath=/etc/jitsi/videobridge/example.meet.jit.si.jks
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePassword=changeit
```

4. You need to start jvb with rest and xmpp interface running. Add the
following to `jvb` config in `etc`:

```
JVB_OPTS="--apis=rest,xmpp"
AUTHBIND=yes
```

**Comment by matclab** [comment]
As a complement, I had to add the following lines (else, the javascript files were not served):
```
org.jitsi.videobridge.rest.jetty.SSIResourceHandler.paths=/
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./interface_config.js=/usr/share/jitsi-meet/interface_config.js
```

**Comment by damencho** [comment]
Thanks, I have updated the doc file. 
You should use this [doc](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/http.md) as a reference. I'm glad to further update it, if you find anything missing.

**Comment by pciavald** [comment]
Almost all of our jitsi-meet calls receive the `IceConnectionFailure` error, which makes the platform unusable in a professional environment.
Investing on this error, it seems to be the consequence of not having a TURN server set up.
From what I understand, jitsi-videobridge now includes a TURN server. Although i've installed it through the automated `apt-get install jitsi-meet`, i'm still facing this problem.
I would like to investigate more on the procedure in this thread, however i don't know how to proceed.
- How do I configure `jitsi-videobridge` to serve `meet` ?
- How do I add `prosody` certificates to java keystore ?
- How do I configure `authbind` to allow `jvb` to use port `443` ?
- My `/usr/share/jitsi-videobridge/` doesn't have a `.sip-communicator/sip-communicator.properties`, should I create it ?
I've noticed in `/etc/jitsi/videobridge/config` that `JVB_OPTS` is not defined. So I guess if this information is still true, my jitsi setup is not configured to use a TURN server as it should be with automated install.

Thank you for your help, 
yours kindly.

**Comment by emcho** [comment]
This has been discussed many times but it's probably worth reminding:

The role of a TURN server is to provide at least one path with a public IP address. Jitsi Videobridge is a server that runs (unless you have an unusual setup) on a public IP address. Use of a TURN server with Jitsi Videobridge is entirely redundant. It would only add extra hops and hence additional points of doubt and failure for your calls

**Comment by pciavald** [comment]
Okay, thank you. Then how can I troubleshoot the `IceConnectionFailure` error ?

**Comment by emcho** [comment]
You seem to be on the right path: serving meet out of the bridge, using port 443 and having TCP enabled are the right things to do (all of those are enabled by default if you just apt-get install jitsi-meet) on a clean Ubuntu VM. Can you start there and see how it goes? Make sure you have a domain name and a cert ready. You are going to need them for the isntallation

**Comment by pciavald** [comment]
Jitsi has been installed for a month here : conf.cantonconsulting.info
It works from some places (e.g. my home, android phones over 4G, but not at some collaborators homes or offices) which is why i thought it had to do with NAT or TURN, as this is the info getting out of google when i search for this error. It is a clean install with apt-get on a ubuntu 16.04 on a vps, with just some tweaks in the js config files.

**Comment by emcho** [comment]
Yup, it looks like your install is properly advertising 443. You can try if it's actually working by blocking UDP on your computer to that machine (make sure you don't block all of your UDP, because you'll kill DNS too) and see if you still get a conference.
Ultimately there are always going to be cases where things are not going to work. For example: if some of your users only support connecting to the web through an HTTP proxy, or do deep packet inspection and kill anything they don't legitimately recognize as HTTP, then you are not going to be able to connect.
If you are ever in doubt about whether or not Jitsi is doing its job, you can also do a comparison with Hangouts for the faulty users and see if that's passing (although they also do P2P in some cases now ... so you'd have to confirm that's not happening when you do your test).

Hope all of this helps!
