### ISSUE TITLE
not work 'make'

### ISSUE THREAD

**Issue by leka2002** [jitsi/jitsi-meet#3246]
**root@ubuntu:/jitsi-meet# lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**root@ubuntu:/jitsi-meet# node --version**
v10.5.0

**root@ubuntu:/jitsi-meet# npm --version**
6.1.0

**root@ubuntu:/jitsi-meet# make**
./node_modules/.bin/webpack -p
ℹ ｢webpack｣: Starting Build
ℹ ｢webpack｣: Starting Build

**When I try 'make' it stops at that state.
How can I go to the next step?**

**When I did 'npm install' I got a few warnings below, but ignored them.
Is that the cause?**

npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.

**Comment by saghul** [comment]
How long did you wait? The webpack part can take up to minutes.

**Comment by leka2002** [comment]
I waited all day, but it does not go on.

**Comment by leka2002** [comment]
If I wait a long time for 'make', I get this error.

**Comment by saghul** [comment]
Hum. can you downgrade to Node 8 and test again? I did a quick test last week and ran into some problems myself, but my memory is fuzzy and I can't remember what it was exactly!

**Comment by leka2002** [comment]
**I downgraded to node version 8 and tried 'make' again.**
**And I got this error.**


**root@ubuntu:/jitsi-meet# node --version**
v8.11.3
**root@ubuntu:/jitsi-meet# make**
./node_modules/.bin/webpack -p
ℹ ｢webpack｣: Starting Build
ℹ ｢webpack｣: Starting Build
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.fork (child_process.js:103:10)
    at fork (/jitsi-meet/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/jitsi-meet/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/jitsi-meet/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.<anonymous> (/jitsi-meet/node_modules/worker-farm/lib/farm.js:97:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Makefile:17: recipe for target 'compile' failed
make: *** [compile] Error 1
root@ubuntu:/jitsi-meet#

**Comment by leka2002** [comment]
**I deleted 'node_modules' folder and tried 'sudo npm install' 'make' again.**
**And I got the same error as the first one.**

**root@ubuntu:/jitsi-meet# make**
./node_modules/.bin/webpack -p
ℹ ｢webpack｣: Starting Build
ℹ ｢webpack｣: Starting Build
Makefile:17: recipe for target 'compile' failed
make: *** [compile] Killed
**root@ubuntu:/jitsi-meet# node -v**
v8.11.3

**Comment by saghul** [comment]
Is this all? The previous command suggests you ran out of memory.

**Comment by leka2002** [comment]
**I deleted 'jitsi_meet' folder and tried to reinstall.**

**root@ubuntu:/# rm -rf jitsi-meet/**
**root@ubuntu:/# git clone https://github.com/jitsi/jitsi-meet**
Cloning into 'jitsi-meet'...
remote: Counting objects: 48002, done.
remote: Total 48002 (delta 0), reused 0 (delta 0), pack-reused 48001
Receiving objects: 100% (48002/48002), 26.65 MiB | 2.06 MiB/s, done.
Resolving deltas: 100% (30929/30929), done.
Checking connectivity... done.
**root@ubuntu:/# cd jitsi-meet/**
**root@ubuntu:/jitsi-meet# sudo npm install**

> git-validate@2.2.2 install /jitsi-meet/node_modules/git-validate
> node bin/install


> node-sass@4.8.3 install /jitsi-meet/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /jitsi-meet/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/parallels/.npm/node-sass/4.8.3/linux-x64-57_binding.node

> precommit-hook@3.0.0 install /jitsi-meet/node_modules/precommit-hook
> node bin/install


> uglifyjs-webpack-plugin@0.4.6 postinstall /jitsi-meet/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> lib-jitsi-meet@0.0.0 postinstall /jitsi-meet/node_modules/lib-jitsi-meet
> webpack -p

[BABEL] Note: The code generator has deoptimised the styling of "/jitsi-meet/node_modules/react-native-callstats/callstats.js" as it exceeds the max of "500KB".
Hash: 2ed01a9a41bf86ffe6ec
Version: webpack 3.9.1
Child
    Hash: 2ed01a9a41bf86ffe6ec
    Time: 99716ms
                            Asset       Size  Chunks                    Chunk Names
            lib-jitsi-meet.min.js    1.02 MB       0  [emitted]  [big]  lib-jitsi-meet
    lib-jitsi-meet.min.js.LICENSE  483 bytes          [emitted]         
           lib-jitsi-meet.min.map    3.69 MB       0  [emitted]         lib-jitsi-meet
       [0] ../jitsi-meet-logger/lib/index.js 3.67 kB {0} [built]
       [2] ./modules/browser/index.js 99 bytes {0} [built]
       [3] ./service/RTC/MediaType.js 110 bytes {0} [built]
       [4] ./modules/util/GlobalOnErrorHandler.js 2.54 kB {0} [built]
       [5] ./modules/statistics/statistics.js 30.5 kB {0} [built]
       [6] ./service/statistics/AnalyticsEvents.js 13.8 kB {0} [built]
       [7] ./JitsiConferenceEvents.js 8.18 kB {0} [built]
      [13] ./JitsiTrackError.js 6.64 kB {0} [built]
      [53] ./JitsiMediaDevicesEvents.js 884 bytes {0} [built]
      [54] ./index.js 160 bytes {0} [built]
      [55] ./JitsiMeetJS.js 20.9 kB {0} [built]
      [56] ./modules/util/AuthUtil.js 1.42 kB {0} [built]
      [57] ./JitsiConnection.js 5.45 kB {0} [built]
     [146] ./JitsiMediaDevices.js 6 kB {0} [built]
     [147] ./modules/recording/recordingConstants.js 339 bytes {0} [built]
        + 133 hidden modules

> node-sass@4.8.3 postinstall /jitsi-meet/node_modules/node-sass
> node scripts/build.js

Binary found at /jitsi-meet/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1742 packages in 168.185s
**root@ubuntu:/jitsi-meet# make**
./node_modules/.bin/webpack -p
Makefile:17: recipe for target 'compile' failed
make: *** [compile] Killed
**root@ubuntu:/jitsi-meet# **


**How should I install jitsi server?**

**Comment by damencho** [comment]
Did you increase the server memory after deleting and before retrying to compile?

You are trying to compile jitsi-meet, which is just the frontend/UI of the conferencing solution, this will not install anything. 

If you want to install a deployment like meet.jit.si, you need to follow https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md and install the Debian packages, this is the quickest and easiest way to do it.

**Comment by leka2002** [comment]
If I install 'quick install', Can I modify the UI or the part that communicates?
First, increase the server memory and try installing again.
Thank you.

**Comment by damencho** [comment]
If you want to use it with a modified interface you will also need a deployment. After following the quick-install, you will end up with a deployment using default binary(compiled) jitsi-meet, which will be in /usr/share/jitsi-meet. 
You can clone and make jitsi-meet. Then just change the root directory pointing to your clone/modified version in the web server configuration, that was installed during quick-install.
Or you can replace /usr/share/jitsi-meet with your modified clone, and make sure the webserver process can read from this folder.

**Comment by leka2002** [comment]
thank you I will try.

**Comment by leka2002** [comment]
**I increased server memory.**
**And I have successfully installed and run the server.**
