### ISSUE TITLE
Maximum number of users reached

### ISSUE THREAD

**Issue by Falgn0n** [jitsi/jitsi-meet#3247]
self-hosted install

I cannot see where/how to test or adjust the max number of allowed users. I am alone in the meet room. 1 is the default maximum?

**Comment by saghul** [comment]
I don't think we have a explicit config option to limit the maximum number of participants in a conference. Generally the client (browser) will run out of resources before your server does.

> I am alone in the meet room. 1 is the default maximum?

I don't understand. If you are alone you are alone, there is no maximum to consider.

**Comment by Falgn0n** [comment]
![jitsi_error](https://user-images.githubusercontent.com/15193343/42620398-60140940-85aa-11e8-8d8e-84dbc785af9f.png)

and no one else can join.

Where are the logs?

**Comment by Falgn0n** [comment]
oops - didn't mean to close it

**Comment by Falgn0n** [comment]
seems to be a prosody configuration problem (certs and storage), investigating it now

**Comment by saghul** [comment]
Oh, I see now. Hum. Did you use our packages or did you install every component by hand?

**Comment by Falgn0n** [comment]
`apt install jitsi-meet` ... it installed all the other stuff, including prosody

Prosody error log:

```
portmanager	error	Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281   
portmanager	error	Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281   
conference.meet.librenet.co.za:muc	error	Error loading list of persistent rooms from storage. Reload mod_muc or restart to recover.   
modulemanager	error	Error initializing module 'muc' on 'conference.meet.librenet.co.za': /usr/lib/prosody/modules/muc/mod_muc.lua:44: Storage error: no data storage active   
```
So I need to manually (re)configure prosody? not sure what exactly is required / don't want to mess up the previous configuration

**Comment by saghul** [comment]
What prosody version do you have?

**Comment by saghul** [comment]
I believe the last error is the culprit here, if we fix that your installation should be good to go.

**Comment by damencho** [comment]
I have seen, I think it was 0.10. That the setting we use does not work for some reason: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L29
`storage = "null"`, even though the documentation says it has null: https://prosody.im/doc/storage
Replacing it with `storage = "none"` will fix the problem, I think.

**Comment by Falgn0n** [comment]
`storage = none` did seem to stop the errors
but it is still problematic, there is no audio and then it seems to drop the connection/s after a few seconds

I'm not trying to be a nag ... but I mean, it's not as if there was any stuff in the configs that I had to do myself, apart from specify the domain. So I just don't know where to look for what's going wrong.

One thing I did come across was in the nginx log:
```
[warn] 14252#14252: *15090 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000042, client: x.x.x.x, server: meet.librenet.co.za, request: "POST /http-bind?room=conf HTTP/2.0", host: "meet.librenet.co.za"
```

**Comment by saghul** [comment]
I just tested your deployment. 2 participants works, but 3 breaks. This usually means the JVB can't be reached. Did you open or forward port 10000 UDP to the machine running the installation?

**Comment by damencho** [comment]
<img width="749" alt="screen shot 2018-07-12 at 05 06 11" src="https://user-images.githubusercontent.com/3263098/42627062-90019ece-8591-11e8-97a5-a278510428fc.png">
You need to also configure your public and private addresses as stated here: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration, and of course do and the port forwarding as @saghul mentioned.

**Comment by Falgn0n** [comment]
I did not port forward .. this is a hosted VPS with a public IP. there is no NAT. I can open 10000 in the firewall, but there are no ports to forward

**Comment by damencho** [comment]
Ups, my mistake. I saw 173.x.x.x as 172.x.x.x sorry. Yeah just opening the ports will fix it.

**Comment by Falgn0n** [comment]
sorry, no ... when a 3rd person connects they kick someone else out - then everyone gets disconnected ...

**Comment by damencho** [comment]
Yep, I see ice failed. Ports are still not open. I tried for example:
```
$ telnet 173.212.214.191 4443
Trying 173.212.214.191...
```
And port 4443 is not open, I suppose port 10000 udp is also not open and that's why ice fails and there is no media.

**Comment by andyhu** [comment]
@damencho changing it to "none" works, thanks! However, could you fix the default config so anyone else won't meet this problem again? Thanks

**Comment by damencho** [comment]
I will check it, cause it should work on 0.9.x and -trunk version at the same time or some more complex logic is needed.

**Comment by damencho** [comment]
I tested this and for some reason it doesn't work for trunk, at least the trunk we use for meet.jit.si which is pretty old one 747... So I need to think about it, how to best handle it.
