### ISSUE TITLE
Customisation 

### ISSUE THREAD

**Issue by tanvir23** [jitsi/jitsi-meet#3250]
Hi guys, I wanted to ask you about a use case asked by my client. He is a lecturer. When he host conference, always guests will have bandwidth issue. He want to host conference where by he can see all other guests. But guest can only see the host to reduce bandwidth consumption. Is it possible? I can’t seem to remember the forum address so I am asking here. :D

**Comment by webintoit** [comment]
Hi. Firstly, you can configure `last-N` feature described here https://jitsi.org/wp-content/uploads/2016/12/nossdav2015lastn.pdf
AfterAll you can play with `startmuted` and ability to enable usermedia.

**Comment by tanvir23** [comment]
thanks for the idea will do some testing...

**Comment by tanvir23** [comment]
it works!! the power of lastn!! thanks @webintoit for the direction and paper...really appreciate it. alright closing this issue
