### ISSUE TITLE
Hey, How to restart jitsi-meet

### ISSUE THREAD

**Issue by WildDylan** [jitsi/jitsi-meet#3261]
Hey, How to restart jitsi-meet???
after config changed, how to restart ?

**Comment by damencho** [comment]
You can restart jicofo /etc/init.d/jicofo restart, you can restart jitsi-videobridge /etc/init.d/jitsi-videobridge restart, you can restart prosody /etc/init.d/prosody restart, these are the components that need a restart on config change.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by WildDylan** [comment]
Thanks !

**Comment by Sx3** [comment]
/etc/init.d/jitsi-videobridge**2** restart

**Comment by fritzfr** [comment]
`/etc/init.d/jicofo restart && /etc/init.d/jitsi-videobridge2 restart && /etc/init.d/prosody restart`

Copy paste oneliner.

**Comment by BlueOwlet** [comment]
what about with a containers :((((

**Comment by saghul** [comment]
`docker compose restart container_name` There is nothing Jitsi specific.
