### ISSUE TITLE
[BUG] Waiting for the Host message doesnt disappear after successfull login

### ISSUE THREAD

**Issue by TheReal1604** [jitsi/jitsi-meet#3262]
## Description
The authentication screen in a new conference room should disappear after a successfull login.

## Current behavior
The login mask is shown until a successfull login AND a page refresh.

![image](https://user-images.githubusercontent.com/5877910/42762158-cf8652ac-890f-11e8-86c9-1cba0ed53f43.png)

(This is shown after a successfull login)

## Expected Behavior
The "waiting for the host" message should disappear and unlock the new conference room.

## Steps to reproduce
1. Use latest stable (stable/jitsi-meet_3135)
2. Enable authentication
3. Open a new webconference channel
4. authenticate
5. -> login mask is shown after a successfull login. (until refresh)

# Environment details
OS: Ubuntu Server 16.04 LTS
Installation: Quick Install / apt-get

**Comment by damencho** [comment]
This had been fixed in unstable. 

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
