### ISSUE TITLE
About share file

### ISSUE THREAD

**Issue by WildDylan** [jitsi/jitsi-meet#3267]
I dont't see my private service have the `Open shared document` function. 

How to enable this ? 

And  another question, iOS and Android app can't chat ?

**Comment by saghul** [comment]
> I dont't see my private service have the Open shared document function.
> 
> How to enable this ?

You need to the the "etherpad_base" option in config.js to point to your etherpad installation.



> And another question, iOS and Android app can't chat ?

No they can't, that is not supported yet.
