### ISSUE TITLE
How to switch the project to Chinese

### ISSUE THREAD

**Issue by CPLASF1925** [jitsi/jitsi-meet#3279]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
From settings.

**Comment by CPLASF1925** [comment]
I want to apply the default is how to set up Chinese

**Comment by CPLASF1925** [comment]
@damencho   I want to apply the default is how to set up Chinese

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L241

**Comment by CPLASF1925** [comment]
@damencho defaultLanguage: 'zhCN' ???  Do not work

**Comment by damencho** [comment]
Try opening it in an incognito window, does it work there? More information here: https://github.com/jitsi/jitsi-meet/issues/3143
The thing is that once loaded with on value, for example, English, this is stored in local storage and if you change the default language on the server it will not affect old clients, but will affect only new-comers. 
I was looking at this, but this storing is buried somewhere in i18n-next and I didn't found an easy fix for it, and as it is not a priority I dropped it, cause this is a rear case which will almost never happen.
Normally the default language will be changed when it is deployed and not in the middle of the life of a service. Any contributions are welcome.
