### ISSUE TITLE
ICE Failed

### ISSUE THREAD

**Issue by WildDylan** [jitsi/jitsi-meet#3284]
```
[modules/UI/videolayout/LargeVideoManager.js] <>:  hover in %s 9710e346
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackRemoved>:  TPC[2,p2p:false] - remote track removed: 39eec6a6-afde-1b40-95a2-ce81afb461c7-1, 06d0cb38-38ac-8548-b1e5-479a7f051356-1
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackRemoved>:  TPC[2,p2p:false] Removed track not found for msid: 39eec6a6-afde-1b40-95a2-ce81afb461c7-1,
             track id: 06d0cb38-38ac-8548-b1e5-479a7f051356-1
n @ Logger.js:125
r._remoteTrackRemoved @ TraceablePeerConnection.js:840
e.onremovetrack @ TraceablePeerConnection.js:600
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackRemoved>:  TPC[2,p2p:false] - remote track removed: 77e5c1e4-e02b-2149-96f4-402434afb394-1, 8c41c9cd-ab9b-cc42-a902-fa0262c98555-1
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackRemoved>:  TPC[2,p2p:false] Removed track not found for msid: 77e5c1e4-e02b-2149-96f4-402434afb394-1,
             track id: 8c41c9cd-ab9b-cc42-a902-fa0262c98555-1
n @ Logger.js:125
r._remoteTrackRemoved @ TraceablePeerConnection.js:840
e.onremovetrack @ TraceablePeerConnection.js:600
Logger.js:125 [modules/xmpp/SdpConsistency.js] <e.value>:  TPC[2,p2p:false] sdp-consistency replacing new ssrc2252569461 with cached 2252569461
JitsiRemoteTrack.js:215 (TIME) Render video:	 75462.51500000001
JitsiRemoteTrack.js:234 (TIME) TTFM video:	 23560.195000000007
Logger.js:125 [modules/xmpp/JingleSessionPC.js] <>:  removeRemoteStream - OK, SDPs:  r {media: Array(3), raw: "v=0
↵o=- 6750109673232007113 3 IN IP4 127.0.0.1
↵s…trickle
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", session: "v=0
↵o=- 6750109673232007113 3 IN IP4 127.0.0.1
↵s…1-a14a6fab072d
↵a=group:BUNDLE audio video data
↵"} r {media: Array(3), raw: "v=0
↵o=- 6750109673232007113 4 IN IP4 127.0.0.1
↵s…trickle
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", session: "v=0
↵o=- 6750109673232007113 4 IN IP4 127.0.0.1
↵s…1-a14a6fab072d
↵a=group:BUNDLE audio video data
↵"}
Logger.js:125 [modules/xmpp/JingleSessionPC.js] <t.value>:  removal not necessary
Logger.js:125 [modules/xmpp/JingleSessionPC.js] <t.value>:  addition not necessary
Logger.js:125 [modules/xmpp/JingleSessionPC.js] <r.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed P2P? false:	 85202.61
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r.close>:  Closing TPC[2,p2p:false]...
Logger.js:125 [modules/xmpp/ChatRoom.js] <t.value>:  do leave r1@conference.jitsi.devdylan.cn/9710e346
Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.setup_failed Error: ICE fail
    at r.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:470)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TraceablePeerConnection.js:262)
n @ Logger.js:125
value @ conference.js:306
n.emit @ events.js:84
(anonymous) @ JitsiConferenceEventManager.js:227
n.emit @ events.js:84
peerconnection.oniceconnectionstatechange @ JingleSessionPC.js:467
peerconnection.oniceconnectionstatechange @ TraceablePeerConnection.js:262
Logger.js:125 [modules/xmpp/JingleSessionPC.js] <r.peerconnection.oniceconnectionstatechange>:  (TIME) ICE closed P2P? false:	 85221.51500000001
```

here is some log.

My port TCP: 443 4443 UDP: 10000-20000 was open.
my stun server and p2p config was: 

<img width="510" alt="default" src="https://user-images.githubusercontent.com/2519544/43038798-f74d89b2-8d52-11e8-9e9a-b3740ed6be4d.png">

and my server address was: `https://jitsi.devdylan.cn `

can you help me ?  or how to find and fix this issue. thanks.

**Comment by WildDylan** [comment]
Now, for example: 

A Client and B Client. 

When B Client join the room, A Client was know, but without camera and voice. After seconds, show a notice bar: disconnected. 

And the log: ICE Failed. 

Please help me, solve this question. it was take me few days.

**Comment by damencho** [comment]
P2P works for me, but your jvb need some configuration: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
You need to set your public and private address, cause jvb advertises only your internal one.
<img width="748" alt="screen shot 2018-07-21 at 18 05 27" src="https://user-images.githubusercontent.com/3263098/43040733-1319e6a0-8d11-11e8-962a-4e9f1539711b.png">

**Comment by WildDylan** [comment]
@damencho very thanks for your answer. config this make me happy. but my browser show this error:

<img width="633" alt="default" src="https://user-images.githubusercontent.com/2519544/43044137-6e782490-8dd3-11e8-8aa4-62696a27cefb.png">

**Comment by damencho** [comment]
I tested your deployment, and I see you had fixed public/private address for jvb, now I see the ip address in webrtc-internals, but when I join with 3 participants there is no media. This means either the ip address is wrong or there is no port forwarding from the public address to the internal one for the media ports tcp 4443 in your case and udp port 10000 or there is firewall on the machine ruuning jvb and is blocking the those ports.

**Comment by WildDylan** [comment]
@damencho thanks again.

ufw for ubuntu

```
root@jitsi:~# sudo ufw status
Status: inactive
```

<img width="1278" alt="default" src="https://user-images.githubusercontent.com/2519544/43052915-4b50e8f6-8e5c-11e8-957a-5d0ac8c35c12.png">

and test by `nc`:

```shell
➜  jitsi-meet-electron git:(master) ✗ nc -v -z -w 2 47.95.13.23 80
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 192.168.0.103 port 58227
	dst 47.95.13.23 port 80
	rank info not available
	TCP aux info available

Connection to 47.95.13.23 port 80 [tcp/http] succeeded!

➜  jitsi-meet-electron git:(master) ✗ nc -v -z -w 2 47.95.13.23 443
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 192.168.0.103 port 58229
	dst 47.95.13.23 port 443
	rank info not available
	TCP aux info available

Connection to 47.95.13.23 port 443 [tcp/https] succeeded!


➜  jitsi-meet-electron git:(master) ✗ nc -v -z -w 2 47.95.13.23 4443
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 192.168.0.103 port 58230
	dst 47.95.13.23 port 4443
	rank info not available
	TCP aux info available

Connection to 47.95.13.23 port 4443 [tcp/pharos] succeeded!

➜  jitsi-meet-electron git:(master) ✗ nc -vuz 47.95.13.23 10000
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif (null)
	src 192.168.0.103 port 54821
	dst 47.95.13.23 port 10000
	rank info not available

Connection to 47.95.13.23 port 10000 [udp/ndmp] succeeded!
```

port was normally ..... 

and then .... what should i do

**Comment by damencho** [comment]
Well, now it seems to work for me, at least for audio. It is sent and received when I open 3 tabs in chrome. I cannot see the video but I have too big packet loss from my location to your IP address, maybe that is the reason at my end. 
Does it work for you if you open 3 tabs in chrome?

**Comment by WildDylan** [comment]
haha, looks like worked for me.

very thanks for your quickly anwser and useful help.

**Comment by WildDylan** [comment]
@damencho Hey, sorry for reopen this issue.

browser and browser was fine, but browser and iOS or android client not work.

could not see video and without voice.

**Comment by scrolls-mckenzie** [comment]
I'm still having issues with this. I have a brand new EC2 in a VPC and have forwarded the ports in the security group as follows

<img width="932" alt="security-group" src="https://user-images.githubusercontent.com/14047475/44294196-c369ec00-a2d6-11e8-9ac1-3159a62670d6.png">

I have also added the private an public IP's of my instance into the sip.communicator-properties
`org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.0.0.xxx
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=13.xxx.xxx.xxx`

I can have 2 participants using P2P without issue but when a third joins I get no connections for audio or video. In the config file, if I turn P2P off I cannot get 2 participants to work which leads me to believe it is the JVB. I have tried browser to browser as well as using an electron package as a client. 

The issue that i see when i connect the third participant in the Chrome Console is 

`[modules/xmpp/strophe.jingle.js] <a.value>:  invalid session id ​`

I have read dozens of similar posts that lead to people getting it to work due to ports but I think i have the covered. Any comments would be really appreciated

**Comment by WildDylan** [comment]
no ideas ...

**Comment by mateuszrusiecki** [comment]
Hi, have the same problem - I can have 2 participants using P2P without issue but when a third joins I get no connections for audio or video. Is there any solution fot it?

**Comment by damencho** [comment]
@mateuszrusiecki check the advanced section im https://jitsi.org/qi

**Comment by dongsweet** [comment]
Finally I got the solution.
Edit /etc/jitsi/videobridge/jvb.conf
Add a health section in videobridge {}:
health {
        require-valid-address = false
    }
And the ice4j is:
ice4j {
    harvest {
        mapping {
            static-mappings = [
                {
                    local-address = "10.0.1.6"
                    public-address = "172.20.38.129"
                }
            ]
        }
    }
}
