### ISSUE TITLE
I can't login setting up SECURE DOMAIN

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#3286]
I builded, using the latest release, my own server on Debian 8 using quick install and generating ssl certificates with Let's encrypt.
The system is working fine, without making any changes.
If I try to setup SECURE DOMAIN I can't login with a user created with prosodyctl (prosodyctl adduser stefano@mydomain). After pressing OK I go back to the window "Waiting for the host".
I type a incorrect password I get the error "Incorrect user or password", that it's right.
The only changes I did are the following:

in config.js:
hosts: {
domain: 'mydomain',
anonymousdomain: 'guest.mydomain',

in /etc/jitsi/jicofo/sip-communicator.properties:
org.jitsi.jicofo.auth.URL=XMPP:mydomain

in prosody config /etc/prosody/conf.d/mydomain.cfg.lua:
VirtualHost "guest.mydomain"
authentication = "anonymous"
.....
VirtualHost "mydomain"
authentication = "internal_plain"

In attach videobridge, prosody and jicofo logs
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2217036/jvb.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2217037/jicofo.log)
[prosody.log](https://github.com/jitsi/jitsi-meet/files/2217038/prosody.log)

but I think the only relevant rows are the following:

Jul 22 15:09:03 mod_bosh	info	New BOSH session, assigned it sid '321acff7-5d1d-403b-b21a-e7e6af0a92f3'
Jul 22 15:09:04 bosh321acff7-5d1d-403b-b21a-e7e6af0a92f3	info	Authenticated as e3c8e101-3c80-4c33-bd9a-fc941c673f8e@guest.mydomain
Jul 22 15:09:06 bosh321acff7-5d1d-403b-b21a-e7e6af0a92f3	warn	rid too large (means a request was lost). Last rid: 2337038182 New rid: 2337038184
Jul 22 15:09:15 mod_bosh	info	New BOSH session, assigned it sid '5379a08a-da00-4b38-9cb9-8e0be948b9f8'
Jul 22 15:09:15 bosh5379a08a-da00-4b38-9cb9-8e0be948b9f8	info	Authenticated as 9861d903-8a00-48e6-aad8-6bab4794e46d@guest.mydomain
Jul 22 15:09:37 mod_bosh	info	New BOSH session, assigned it sid '87b02030-18e7-40d1-ba30-9d74a4d99297'
Jul 22 15:09:37 bosh87b02030-18e7-40d1-ba30-9d74a4d99297	info	Authenticated as stefano@mydomain
Jul 22 15:09:38 bosh87b02030-18e7-40d1-ba30-9d74a4d99297	info	BOSH client disconnected

**Comment by damencho** [comment]
Have you tried using latest version from unstable? A bug was fixed which haven't reached stable yet. 

Please use the community forum, before opening new issues. https://community.jitsi.org

**Comment by calamatitech** [comment]
Sorry, you are right.
Updating Jitsi Meet to the latest unstable version, the authentication works.
Many thanks,
