### ISSUE TITLE
can't connect server on iOS

### ISSUE THREAD

**Issue by leka2002** [jitsi/jitsi-meet#3287]
iOS model : iPad Mini 4
iOS version : 11.4
app version : 1.9

**When I try to connect to my server from iOS, the following error occurs.**
**How to connect my server on iOS ?**

![err1](https://user-images.githubusercontent.com/38308563/43052052-80f5e93e-8e5c-11e8-847d-1d84d038acaf.png)

** Extra Info**
![err2](https://user-images.githubusercontent.com/38308563/43052058-8d8396f6-8e5c-11e8-96f9-34f516838905.png)

**Comment by saghul** [comment]
You can't connect to an IP address because certificate validation will fail and so will all HTTP requests. Use a FQDN with a valid certificate (self-signed ones won't work either).

**Comment by CPLASF1925** [comment]
@saghul 
How to add your own certificate

**Comment by saghul** [comment]
See https://letsencrypt.org/ and configure nginx to use it.
