### ISSUE TITLE
how to install jibri?

### ISSUE THREAD

**Issue by sesangsokuro** [jitsi/jitsi-meet#3297]
I am installing jibri for recording after a successful jitsi-meet.

apt-get install jibri

After entering the command

Enter /etc/jitsi/jibri/config.json

"control_login": {
  "domain": "auth.jitsi.webzook.net"
  "username": "username ??"
  "password": "password ??"
},
"control_muc": {
  "domain": "auth.jitsi.webzook.net"
  "room_name": "JibriBrewery ??"
  "jibri-nickname": "jibri-nickname ??"
},
 "call_login": {
  "domain": "recorder.jitsi.webzook.net"
  "username": "username ??"
  "password": "password ??"
}

There is a setting section that does not make sense

The place where the question mark is not understood all.

I think control_login is the part of prosody authentication.
So I typed it like auth.mydomain
Suddenly I was asked to enter the user / password.

apt-get jitsi-meet did not prompt me to enter an ID when installing.

How can I make an ID?

And call_login
recorder.jitsi.webzook.net
How do I create an id to log in here?

I do not know the room_name and jibri-nickname of the control_muc entry.
I do not know if it's a meaningful value or an arbitrary example value.

Compared to the documented jitsi-meet installation process
jibri does not seem to have the installation documentation itself, how can I do it?

I installed it through apt-get install jibri.

However, modprobe snd-aloop did not work. And wherever I look, there is no answer to that issue.

I am using ubuntu 16.04.

Any way is good. Links and keywords are okay. Please escape me from this no documentation hell

In the overall jitsi documentation
The settings related to prosody seem to be omitted. Is this the error?

**Comment by buddhikajay** [comment]
I believe the issue is directly related to snd-aloop. Without that, jibri will not work.
