### ISSUE TITLE
Cannot read property 'scrollIntoView' of undefined when use react-devtools

### ISSUE THREAD

**Issue by tianjyan** [jitsi/jitsi-meet#3298]
## Description
I clone the project and want to use [React Native Developer Tools](https://github.com/facebook/react-devtools/tree/547916f3ad9b9c1a610f89a51a5a3bcc1923d188/packages/react-devtools) to inspect it.

## Current behavior
I see a red screen shows `Cannot read property 'scrollIntoView' of undefined`.

## Expected Behavior
I should can use this project with React Native Developer Tools.

## Possible Solution
n/a

## Steps to reproduce
* Run `react-devtools` to start the tools
* Run `adb reverse tcp:8097 tcp:8097`
* Run `react-native run-android` to deploy the apk to my phone

# Environment details
* OS: macOS 10.13.6
* React Native Cli: 2.0.1
* React Native Developer Tools: 3.2.3
* Jitsi-Meet Commit Id: 5d4a2e87f82d9ba7cdc2e6404e87c841262ae765

**Comment by CyberCyclone** [comment]
Was a solution ever found for this?
