### ISSUE TITLE
Is Custom Navigation Possible in Jitsi ?

### ISSUE THREAD

**Issue by FaizalMalik** [jitsi/jitsi-meet#3309]
## Description

Can anyone help me to get an Insight, how to implement the custom navigation in Jitsi application?
 
I would like to build an Application, where Video conference is the core functionality, so I decided to select Jitsi as a Boilerplate and Integrate my modules to that, so is it possible to have the custom navigation in Jitsi application? 

Or can anyone help me, how I can use Jitsi library in a new React Native Application?

Thanks in Advance 

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Also, it's Jits**i**.

**Comment by FaizalMalik** [comment]
@saghul  - My requirement is like, I need to create a new Hello world React Native Application and place a button inside the view when I click the button, I need to join 'https:jitse/.../room123' ... that's it..!
I have done the same in Android and iOS (Standalone apps), but how can I achieve the same in React Native? 

I am expecting a URL / Docs or steps to achieve my requirement ---! 

I am a newbie in React Native :|

**Comment by FaizalMalik** [comment]
@saghul  -  Could you please help me, thanks in Advance 👍

**Comment by saghul** [comment]
Unfortunately that's not as easy at it is to integrate Jitsi Meet into a native application. I cannot give you a guide because there is no guide. You'll need to modify the build to do the needful.

I know this is not great, I'm sorry. With time, we can hopefully improve on this, but that's how things are today.

**Comment by FaizalMalik** [comment]
yeah, I am trying that, but as a beginner in React Native, for me, it's really hard to understand and modify the code....!!  

But I tried to customize the code like --

I have added a login page and when the user clicks the Login button - the app will land on Welcome Page...!! but after typing room name and click join - it's not working :( -- @saghul 

![img_0010](https://user-images.githubusercontent.com/32692684/43265369-2a9fbeb4-9106-11e8-9575-d2fca6914c2d.PNG)

**Comment by FaizalMalik** [comment]
or Could you please help me how can I navigate to a custom page using the routing used by Jitsi? 
Maybe that helps me better...!

@saghul

**Comment by vinay72** [comment]
Yes we can add custom Navigation in Jitsi Application.

**Comment by AbhijeetThakur** [comment]
Can anybody please guide me to adding custom navigation in Jitsi Application.

**Comment by khateeb0** [comment]
> Yes we can add custom Navigation in Jitsi Application.

How??
