### ISSUE TITLE
Is there a 'quick-install' for 'centos'?

### ISSUE THREAD

**Issue by leka2002** [jitsi/jitsi-meet#3310]
**Is there a 'quick-install' for 'centos'?**

**Comment by saghul** [comment]
No, sorry.

**Comment by CRCinAU** [comment]
Is there *any* type of documentation for installation on anything that isn't Ubuntu / Debian?

**Comment by saghul** [comment]
Yes, the manual installation instructions: https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

**Comment by CRCinAU** [comment]
Is there any information about required versions of various libraries? It seems the manual install just says:

Install prosody
apt-get install prosody

I'm trying to get my head around how this would apply in CentOS - and hopefully, if there is any kind of interest in trying to fix the RPM builds for it.

Trying to gauge the current situation, are the RPMs listed in the downloads section still considered current? Is there a .spec file available? I'd really like to try and get the RPM packages updated and supported properly (and happy to contribute where I can)

**Comment by saghul** [comment]
You should just install prosody.

> Trying to gauge the current situation, are the RPMs listed in the downloads section still considered current?

What are you trying to do here, use Jitsi dekstop or Jitsi Meet? They are different projects and you have created similar issues on both.

**Comment by CRCinAU** [comment]
I'm looking at Jitsi Meet - while I'd be happy to try help package both or help with issues in packaging, my personal aim is to get the conferencing going via web interface that I can use internally within my org.

**Comment by saghul** [comment]
Gotcha. So, here are my thoughts, which need not represent those of the Jitsi project as a whole:

There are a number of moving parts in a basic installation: prosody, jicofo, jvb, the meet web to start with. All these components need to be configured to work together. This is non-trivial and we currently provide an automated way of dealing with this in our Debian packages. You'd have to replicate that on CentOS.

Doing all this will not be a quick and simple task. And once done, comes the maintenance cost. Someone has to take ownership of maintaining those packages helthy and making sure releases are made (we use an "umbrella tag" across all repos) and things don't break. Currently we make releases with our Jenkins agents, but if we add RPMs into the mix and people start relying on them we'd have to take ownership.

This means more work for us. I'm not sure we want to / can add that work on our shoulders, I hope this is understandable.

So here is a counter-proposal: how about keeping your CentOS installation and running Jitsi Meet on Docker containers? Yes, they would be running Debian, but you don't have to worry about that. You can give it a go by following the instructions here: https://github.com/jitsi/docker-jitsi-meet

**Comment by CRCinAU** [comment]
Yeah - I appreciate the difficulty - as coming from outside, its hard to grasp how the bits of the jigsaw fit together. Then to make things worse, having things unmaintained is even more frustrating :)

We currently run VMs based on Xen, which would give us a VM running CentOS running docker + debian. I'm not sure how that would affect performance (if at all) - but it seems like more levels of redirection that would make me comfortable. I think given the choice, I'd probably try to get a Debian install running on our existing VM solution. Annoying to break SOE, but may be less pain.

On a future thinking basis, is it within the realm of possibility to package a tarball with a 'mostly configured' binary distribution of the required parts?

While I'll admit I'm not familiar with the internal workings of this entire project, other enterprise projects such as keycloak etc adopt a 'extract, configure & run' type approach - meaning no root installation is required.

I guess that would mean instructions such as:
1) Install dep packages: speexdsp openjdk-blah libexample
2) Extract archive
3) Edit config in $HOME/path/to/config
4) Run program ./runme

This could also then be easily wrapped via systemd to run as an unpriv user etc etc etc

Of course, this may be over simplifying and I might be speaking out my butt with respect to complexity - but would appreciate the input.

**Comment by saghul** [comment]
> We currently run VMs based on Xen, which would give us a VM running CentOS running docker + debian. I'm not sure how that would affect performance (if at all)

Shouldn't be much.



> but it seems like more levels of redirection that would make me comfortable. I think given the choice, I'd probably try to get a Debian install running on our existing VM solution.

Totally understandable, makes sense.



> On a future thinking basis, is it within the realm of possibility to package a tarball with a 'mostly configured' binary distribution of the required parts?

IMHO, not really. As I mentioned there are several moving parts, so we'd have to package them all. Then either provide a launcher for them all or have the user do it. And then there is the configuration part, which we'd have to do from scratch just for this scenario. We currently have 2 ways to connect all components in an integrated manner: the Docker setup or the Debian / Ubuntu packages setup. Otherwise it's all manual. Adding a 3rd is not something I'd be personally looking forward to maintain.

> While I'll admit I'm not familiar with the internal workings of this entire project, other enterprise projects such as keycloak etc adopt a 'extract, configure & run' type approach - meaning no root installation is required.
> 
> I guess that would mean instructions such as:
> 
>     1. Install dep packages: speexdsp openjdk-blah libexample
> 
>     2. Extract archive
> 
>     3. Edit config in $HOME/path/to/config
> 
>     4. Run program ./runme
> 
> 
> This could also then be easily wrapped via systemd to run as an unpriv user etc etc etc
> 
> Of course, this may be over simplifying and I might be speaking out my butt with respect to complexity - but would appreciate the input.

Keyclock is a single application AFAICT, our setup involves multiple parts so the complexity grows by quite a bit.

Thanks for the chat, this is good. Note, however, that other members of the community might have other thoughts in the matter, these are just my 2 cents.

**Comment by CRCinAU** [comment]
Yeah - this is all understandable. I did get things running via Debian Stretch - however I found myself breaking the install - and the uninstall kept failing - so I re-installed and started again - then its weekend time :)

I've been trying to find information on how to set up guests to join existing rooms, but only authed users to be able to create new rooms. The docs seem to say to set up a new domain - which I didn't manage to get functioning as I'd expect.

Ideally, I'd like to hook up to an LDAP server for auth - however I can't seem to find anything that isn't 2+ years old on how to do this.

Are there any hints on integration for these sorts of things?

**Comment by saghul** [comment]
> Yeah - this is all understandable. I did get things running via Debian Stretch - however I found myself breaking the install - and the uninstall kept failing - so I re-installed and started again - then its weekend time :)

:-)

> I've been trying to find information on how to set up guests to join existing rooms, but only authed users to be able to create new rooms. The docs seem to say to set up a new domain - which I didn't manage to get functioning as I'd expect.

These are the instructions to follow: https://github.com/jitsi/jicofo/#secure-domain What didn't work as expected?

> Ideally, I'd like to hook up to an LDAP server for auth - however I can't seem to find anything that isn't 2+ years old on how to do this.

Once you get the above working, adding LDAP becomes a Prosody configuration detail. In the example above we use `internal_plain`, which is a builtin auth method in Prosody, but you can configure it for PAM, LDAP or others: https://prosody.im/doc/authentication I have no experience doing that myself, so it might be easier said than done, but hopefully not :-)

**Comment by CRCinAU** [comment]
I might have done it wrong - but I'd like to use the same domain, then ONLY allow guests to join rooms that have already been created.

I noticed that through whatever config I managed to get going that I got a message in the web browser that said "It looks like conference TEST hasn't started yet" and a button for "I am the host" - however I couldn't get all the pieces to work and I didn't make notes of what config changes I had made and where.

Good news on the prosody auth part - as it means I was going somewhat in the right direction with the 'prosody-modules' package from debian.

I think my main confusion was how I got that message to display, using the same domain name, and how to get auth happening after that. I couldn't find any documentation that seemed to reflect the "I am the host" option.

**Comment by saghul** [comment]
I see.

There are 2 things at play here:

1) Do you want authentication for the main domain?
2) Do you want to enable guests (ie, unauthenticated users) to join rooms, if an authenticated user is already in?

The configuration is pretty similar but the behavior will vary depending on what you decide for option 2.

If you want to allow guests you need to create the new domain in Prosody and configure `anonymousdomain` in config.js. This will show the dialog with the "I am the host" option. If you omit this part, you'll just see a login form with user and password because all users will need to be authenticated.

**Comment by CRCinAU** [comment]
I'm after Option 2 - so an authed user can create any room they like, and once created, a guest can join without requiring auth.

A guest user should not be able to create a room.

**Comment by saghul** [comment]
> EDIT: As such, it should be able to happen on the one domain.

No, I don't think it can, because how we implement it. That subdomain doesn't even need to exist, is just something so authentication can be configured differently in Prosody.

**Comment by CRCinAU** [comment]
Wait, so the domains don't have to exist in DNS and apache's config?

**Comment by saghul** [comment]
The guest domain no, the main one yeah.

**Comment by CRCinAU** [comment]
Good news is that I got it going. I talked to the prosody guys - removed the debian prosody-modules package, then installed mod_auth_ldap manually as a prosody plugin.

The only other change I needed to do was to add `consider_bosh_secure = true` to the main prosody.cfg.lua file and away it all went.

Thanks for your help.

**Comment by saghul** [comment]
Glad to hear!
