### ISSUE TITLE
Eherpad connot work

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3313]
When you opened etherpad, you went to the main domain address, not the etherpad document. What happened?

**Comment by c526537207** [comment]
etherpad_base:'MY DOMAIN',connection timeout

**Comment by damencho** [comment]
Check how it is configured on meet.jit.si, https://meet.jit.si/config.js.

**Comment by c526537207** [comment]
@damencho Thank you for your reply. The problem has been solved!
