### ISSUE TITLE
This error occurred during installation, on debian-arm64.

### ISSUE THREAD

**Issue by liuzhangkui** [jitsi/jitsi-meet#3314]
The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-videobridge (= 1077-1) but it is not installable
              Depends: jicofo (= 1.0-425-1) but it is not installable
E: Unable to correct problems, you have held broken packages

**Comment by damencho** [comment]
Arm is not a supported platform for the moment.

**Comment by liuzhangkui** [comment]
I saw someone successful on the raspberry pi .
