### ISSUE TITLE
Cannot set password

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3315]
The room lock function cannot set the password.

**Comment by saghul** [comment]
Can you **please** fill the issue template? Where does this happen: web? mobile?

**Comment by c526537207** [comment]
@saghul web,When the password is set, it is cancelled automatically

**Comment by saghul** [comment]
I cannot reproduce it. Does it work on meet.jit.si for you?

**Comment by c526537207** [comment]
@saghul It cannot work on meet.jit.si for you,It's also auto cancel.And you?Can work?

**Comment by saghul** [comment]
Yes, it works just fine for me on meet. Hum, I think I may now your problem: do you press enter? Looks like we don't save the password on blur. Maybe we should @virtuacoplenny ?

**Comment by c526537207** [comment]
@saghul Thank you for your reply. The problem has been solved!
