### ISSUE TITLE
Automatically switch between phone and speaker outputs on mobile

### ISSUE THREAD

**Issue by hferreiro** [jitsi/jitsi-meet#3318]
Raising the phone to an ear should automatically switch to audio only mode and to phone output.

**Comment by saghul** [comment]
There is more work to be done other than just changing the audio device. It would make sense to mute local and remote video, thus turning on audio-only mode.

I’m open to trying this out, but I worry it’s too easy to cover the proximity sensor by accident (specially when holding the phone in landscape mode) so this would cause an undesired flicker.

**Comment by hferreiro** [comment]
Alternatively, this could be done only when in audio-only mode.

**Comment by saghul** [comment]
In audio-only mode the earpiece is the default, and the user has to manually change the output to the speaker. I'm still not sure what the best idea is here. Thanks for the feedback!

**Comment by hferreiro** [comment]
Then I believe the default in audio-only mode should be changed to speaker and support the raise the phone behaviour. It is a bit surprising that changing the audio-video mode would also change the audio route, making the sound much more quiet and forcing the user to raise the phone.

**Comment by hferreiro** [comment]
ping

**Comment by saghul** [comment]
@naveensaini4u please either ask in our community (https://community.jitsi.org) or open a new issue if it's code related. Don't hijack issues please.
