### ISSUE TITLE
My Jitsi Meet Server Working from Same network and Same Wifi, but it's not work from network

### ISSUE THREAD

**Issue by shopno111** [jitsi/jitsi-meet#3319]
Hi,
My Jitsi Meet Server Working from Same network and Same Wifi, but it's not work from network
Here is my domain: http://zoomcall.zoombangla.com
It is perfectly working from same network.

Please check and suggest me, what i can do.

Thank

**Comment by damencho** [comment]
Have you checked this? https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by shopno111** [comment]
Hi,
Thanks for your update, I already did it, and here my I set my server in Local IP and Remote IP. but it's didn't work.

Thanks

**Comment by Ahmad-Mustafaa** [comment]
> si Meet Server Working from Same network and Same Wifi, but it's not work from ne

I am facing same issue. Can you please Post about solution what you did ?
