### ISSUE TITLE
How to enforce the moderator by nickname?

### ISSUE THREAD

**Issue by danionescu2007** [jitsi/jitsi-meet#3321]
What happens is that if I am the moderator and I get reconnected for various reasons, another user gets the moderator rights, with no possibility for me to gain it back on.
I need to tweak the code to force the moderator from a list of nicknames.
Can someone point me in the right direction, right file were to change the code?
Thank you in advance!

**Comment by damencho** [comment]
It is jicofo assigning that role: https://github.com/jitsi/jicofo/blob/1d16c78f90d078e762266dc9df04950e780b7982/src/main/java/org/jitsi/jicofo/ChatRoomRoleAndPresence.java#L197
What you can do is just enable all-moderators, like on meet.jit.si: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_allowners.lua

Please the community forum for questions: https://community.jitsi.org

**Comment by danionescu2007** [comment]
Thank you, Damian! You saved my day.
Regards++,
Dan

**Comment by danionescu2007** [comment]
I created this forum post: https://community.jitsi.org/t/trying-to-install-and-activate-mod-muc-allowners-lua/14405
It seems I am not worthy enough to make the mod_muc_allowners.lua module to work :)
