### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by CPLASF1925** [jitsi/jitsi-meet#3322]
@saghul 
Try APK to wrap the signature, but the'react-native-vector-icons'loaded icon is exactly the same and abnormal.

**Comment by CPLASF1925** [comment]
@saghul     

As this is the same problem  #1688

**Comment by saghul** [comment]
Then why don't you give us more complete details? I't impossible to help you otherwise.

Please reply to my previous questions and tell us what steps you have followed to arrive at this problem.
