### ISSUE TITLE
How can I activate the 'etherpad' function?

### ISSUE THREAD

**Issue by leka2002** [jitsi/jitsi-meet#3331]
How can I activate the 'etherpad' function?

I installed the server according to the guide in the link below.

https://github.com/jitsi/jitsi-meet/wiki/Tutorial-for-Building-Out-an-install-from-scratch:-Ubuntu-16.04-Apache2

![2018-08-01 3 12 47](https://user-images.githubusercontent.com/38308563/43504190-67dfac12-959d-11e8-99cd-e89dd57dcf58.png)

**Comment by leka2002** [comment]
I have installed 'etherpad' and can use it as http: // localhost: 9001.

What additional settings should I set in Jitsi?


In my 'interface_config.js' I have written:

TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection', 'hangup', 'profile', 'info', 'chat', 'recording',
        'livestreaming', **'etherpad'**, 'sharedvideo', 'settings', 'raisehand',
        'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts'
    ],

**Comment by damencho** [comment]
Enable it in config.js https://github.com/jitsi/jitsi-meet/blob/master/config.js#L365

**Comment by leka2002** [comment]
In my 'config.js' I have written:

etherpad_base: 'https://mydomain/etherpad/p/',

But it was not activated.

**Comment by leka2002** [comment]
I set it in '/etc/apache2/site-available/mydomain.conf' as follows, and I succeeded in activating the EtherPad.

<Location /etherpad/>
ProxyAddHeaders On
ProxyPass http://HOSTNAME/
RequestHeader set X-Forwarded-For REMOTE_ADDR
RequestHeader set X-Forwarded-Host HOST
</Location>

Thanks.
