### ISSUE TITLE
Video/audio streams not sent to the server

### ISSUE THREAD

**Issue by prawnsalad** [jitsi/jitsi-meet#3334]
We have managed to get jitsi setup on our own test servers successfully using JWT tokens, along with a test page to make sure the conference streaming between users is working correctly.

Using the same install on a production box however fails. Clients can connect, all participants see each other, but no stream is passed on to anybody. There are no obvious errors in the browser console. The jvb log outputs are similar between the test and production servers.

We are currently testing without any firewalls in place, and I can see traffic heading to UDP 10000 when streaming should be happening - but nowhere near as much as there should be. Very little traffic in comparison to a working videobridge instance.

Here is our test page that we're seeing the issue with: https://conference.kiwiirc.com/kiwi/

I'm really not sure how on how to debug this any further, any pointers would be great!

**Comment by saghul** [comment]
I see a JS error in the console, which I wonder if it's related. Can you compare the config.js and interface_config.js from both installations?

**Comment by prawnsalad** [comment]
The was actually a difference between them both but only for the channelLastN config. I've matched them both up just in case and nothing has changed.

~~~bash
$ diff config.prod.js config.test.js
181c181
<     channelLastN: 10,
---
>     channelLastN: -1,
~~~

**Comment by prawnsalad** [comment]
All instances installed via these docs: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

We changed up some of the Lua scripts which are now working fine, and users get joined to the room so that's fine.

**Comment by prawnsalad** [comment]
Would any other info help debug this? I'm at a complete loss here of where to even look anymore.

**Comment by saghul** [comment]
I'll try to reproduce this tomorrow.

**Comment by damencho** [comment]
I reproduce your problem. But currently, have no idea why is that, it is a very strange problem. But I see an error in the API someting about invitees and I will ask @hristoterezov for help, cause I think he was the last one changing that code.

**Comment by saghul** [comment]
Do you have a meaningful traceback @damencho ?

**Comment by saghul** [comment]
Really? I don't see how that code path could get executed :-O I'll do some testing tomorrow and try to find out!

**Comment by damencho** [comment]
Hey @prawnsalad we had fixed the error, can you update to latest unstable and test again. 
This should be jitsi-meet version 3268 (jitsi-meet-web version 2977). 

Sorry for the inconvenience.

If you still have a problem, we can continue debugging with the new version.

**Comment by prawnsalad** [comment]
thanks for looking into that @damencho, the javascript does seem to have disappeared which is great :)

However the issue of the video+audio not being sent is still there. To replicate: open the link in your normal browser then open another. You can see the other participants in the conference but not their audio/video.

**Comment by damencho** [comment]
Something came to my mind but I'm away from the computer to check it. Double check the documentation how to pass token, cause token= and jwt= are different things.

**Comment by prawnsalad** [comment]
hey @damencho, we are passing it as follows:
`JitsiMeetExternalAPI(jitsiDomain({jwt: 'the jwt token', othervalues:'here'});`

People can join the room successfully so we know the JWT is working fine. It's just that the video/audio stream is not being propagated to other users.

**Comment by damencho** [comment]
That seems to be correct, I was suspecting something around the iframe API, but I also tested it without the API and the behavior is the same. And it behaves very strangely ... so there are no exceptions in jicofo logs?

**Comment by prawnsalad** [comment]
@damencho I've uploaded a full log here: https://conference.kiwiirc.com/jicofo.txt

I can't see any exceptions though maybe something else stands out to you?

**Comment by damencho** [comment]
Those logs have some suspicious lines like:
```
org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Focus role unknown
Jicofo 2018-08-04 16:46:59.190 SEVERE: [120] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.wasInviteAccepted().253 Failed to send 'session-initiate' to 6972632e667265656e6f64652e6e65742f2373646673646661@conference.conference.kiwiirc.com/8444e9f1, error: XMPPError: service-unavailable - cancel
Jicofo 2018-08-04 16:46:59.190 INFO: [120] org.jitsi.jicofo.ParticipantChannelAllocator.log() Expiring 6972632e667265656e6f64652e6e65742f2373646673646661@conference.conference.kiwiirc.com/8444e9f1 channels - no RESULT for session-initiate
Jicofo 2018-08-04 16:46:59.191 INFO: [120] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Region info, conference=ff8596: [[null, null]]
Jicofo 2018-08-04 16:46:59.191 INFO: [120] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Expiring channels for: 6972632e667265656e6f64652e6e65742f2373646673646661@conference.conference.kiwiirc.com/8444e9f1
Jicofo 2018-08-04 16:46:59.192 INFO: [77] org.jitsi.jicofo.Bridge.log() Removing 3 video streams on jitsi-videobridge.conference.kiwiirc.com video streams: 0 diff: 1 (estimated: 1)
Jicofo 2018-08-04 16:46:59.193 WARNING: [120] org.jitsi.jicofo.AbstractParticipant.log() Canceling a ChannelAllocator.
Jicofo 2018-08-04 16:46:59.193 INFO: [78] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.initiateSession().130 INVITE PEER: 6972632e667265656e6f64652e6e65742f2373646673646661@conference.conference.kiwiirc.com/1eea0014
Jicofo 2018-08-04 16:46:59.193 INFO: [120] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, 6972632e667265656e6f64652e6e65742f2373646673646661@conference.conference.kiwiirc.com/8444e9f1
```

Can you double check your config, do you have the correct line: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L31
Should be something like:
```
admins = { "focus@auth.conference.kiwiirc.com" }
```
Or just paste the prosody config you are using (removing the passwords/secrets).

**Comment by damencho** [comment]
@prawnsalad can you also paste your jvb config.

**Comment by prawnsalad** [comment]
~~~
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.conference.kiwiirc.com/.*
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=stun.l.google.com:19302
~~~

**Comment by prawnsalad** [comment]
Just as a quick update, after almost a month of testing on different server providers, configurations, package versions, the issue was resolved by forcing our server host to use a standard Ubuntu .iso instead of their own provided iso. We nor the server hosts are sure what the differences are but that solved the issue.

Thanks for all the help given on here and IRC!
