### ISSUE TITLE
i want to change the hostname,which was inputed when i install jitsi-meet, how can i chang it?

### ISSUE THREAD

**Issue by vinson-zhang** [jitsi/jitsi-meet#3336]
i want to change the hostname,which was inputed when i install jitsi-meet, how can i chang it?

**Comment by vinson-zhang** [comment]
one: with the command:apt-get remove --purge jitsi-meet jitsi-meet-prosody jitsi-meet-web-config jitsi-meet-web jicofo jitsi-videobridge to remove the jistsi
two:sudo apt-get install -y jitsi-meet
you can config the hostname again!

**Comment by jscaux** [comment]
For me, if I do this and rerun the install, it doesn't ask me the hostname anymore so I can't change it. It stays on the originally-set one. Any tips?

**Comment by erdoukki** [comment]
Not working on fresh debian buster installation !

**Comment by jlegen** [comment]
the list of packages to be removed needs to be extended by "jitsi-videobridge2". or remove the hostname manually: "echo PURGE | debconf-communicate jitsi-videobridge2"

**Comment by damencho** [comment]
This had been fixed in latest stable https://github.com/jitsi/jitsi-videobridge/commit/63d2f9da8208cf1fb65ee6fe20b850c93be924c2

**Comment by exyfeplin** [comment]
I had this same problem with the latest "quick install" instructions from here:
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

I uninstalled, but when reinstalling I was not asked to provide the hostname.

But, the uninstall instruction above seemed to do it.
i.e.
apt-get remove --purge jitsi-meet jitsi-meet-prosody jitsi-meet-web-config jitsi-meet-web jicofo jitsi-videobridge

After this, reinstalling would ask for the hostname.

Instructions need updating.  Or, a way to reconfigure hostname for an existing installation.

**Comment by zugzwang** [comment]
FWIW, @jlegen suggestion worked for me. Full uninstall command is
```

**Comment by zugzwang** [comment]
FWIW, @jlegen suggestion worked for me. Full uninstall command is
```
apt-get remove --purge jitsi-meet jitsi-meet-prosody jitsi-meet-web-config jitsi-meet-web jicofo jitsi-videobridge jitsi-videobridge2 
```
On next install, it asks for the hostname

**Comment by zugzwang** [comment]
(and also, it seems to repair the broken packages issue).

**Comment by K-KOTAN** [comment]
use dpkg-reconfigure jitsi-videobridge2

**Comment by apmuthu** [comment]
Doing this will update the **jitsi-meet** to the latest version and it will break in some instances. Here is an example:
````
Jitsi was installed on 2024-07-27, using self-signed certificate in Debian Buster.
prosody from bullseye was used, and everything worked.

The following were the versions:
# dpkg-query -l | grep jitsi
ii  jitsi-meet                      2.0.9584-1                    all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.8043-1                    all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.8043-1                    all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.8043-1                    all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.8043-1                    all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.3-149-g793df5a9-1           all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                      0.4.1-jitsi1                  all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                 2.1.0.10-jitsi1               amd64        JSON parser/encoder for Lua

After an apt update && apt dist-upgrade the jitsi-meet got upgraded as:

ii  jitsi-meet                      2.0.9646-1                    all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.8091-1                    all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.8091-1                    all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.8091-1                    all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.8091-1                    all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.3-160-g97a1f15b-1           all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                      0.4.1-jitsi1                  all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                 2.1.0.10-jitsi1               amd64        JSON parser/encoder for Lua

Now we keep getting disconnected when the second user logs in.
````

**Comment by apmuthu** [comment]
Are there a list of files in a Jitsi install where the **hostname** and **domain** name needs to be changed or is there a domain/hostname change script?

**Comment by damencho** [comment]
The files are in 
/etc/nginx
/etc/prosody
/etc/jitsi
/etc/turnserver.conf

**Comment by apmuthu** [comment]
Tnx

**Comment by c2n14-go-brr** [comment]
In case anyone hits this via a search later, the issue with the quick install (on debian 12.8) is the missing VitualHost entry in /etc/prosody/prosody.cfg.lua

**Comment by damencho** [comment]
jitsi-meet does not add  VitualHost in /etc/prosody/prosody.cfg.lua. There is a jitsi-meet prosody config with that.

**Comment by c2n14-go-brr** [comment]
Right, the quck install sets up /etc/prosody/conf.avail/your.host.name.cfg.lua (which has the correct VirtualHost) and links that into /etc/prosody/conf.d/
Still, there's _something_ going wrong with the install procedure, at least initially.
After a  purge/install cycle, I hit the issue mentioned by apmuthu (second user entering a room disconnects both).
Adding the VirtualHost entry in /etc/prosody/prosody.cfg.lua and restarting prosody got rooms usable again - but I guess that is an effect of the restart, not the added VirtualHost.
After removing the added VirtualHost and another restart of prosody, the rooms stay usable.
For the initial setup, this could be explained by an ordering issue (prosody loads it's config before the dpkg script linked the config file into conf.d), but that wouldn't explain issues during an uupgrade (where the link is already in place).

**Comment by damencho** [comment]
> After a purge/install cycle, I hit the issue mentioned by apmuthu (second user entering a room disconnects both).

Check what is the error in the web js console, is it no videobridge available? Then check jvb logs. Is jvb correctly connected to prosody? If not just restarting jvb will fix it ... I think we fixed that at some point [with](https://github.com/jitsi/jitsi-meet/blob/e151be48b90289ef630577326abb60263d6ad9f1/debian/jitsi-meet-prosody.postinst#L257)

**Comment by c2n14-go-brr** [comment]
I am kinda getting confused here. I've tried 5 reinstalls, and keep getting one of two outcomes - none of them matching yesterday's scenario. As at least one of the variants is trust related: Im using the "I want to use my own certificate" option during installation.

First variant: The debconf output looks good, but rooms don't work at all (joining leads to immediate disconnect).
The js console shows:
`[modules/xmpp/moderator.js] <_handleError>:  Failed to get a successful response, giving up.`
Both jvb.log and jicofo.log report TLS trust issues, i.e.:
`JVB 2024-11-21 21:35:50.592 WARNING: [515] [hostname=localhost id=shard] MucClient$2.connectionClosedOnError#341: Closed on error:
javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed`
prosody.log reports kinda the same:
`Nov 21 21:35:50 c2s563af38bbfd0 info    Client connected
Nov 21 21:35:50 c2s563af3835870 info    Client disconnected: sslv3 alert certificate unknown`

Restarting jitsi-videobridge2 and jicofo helps in this case.

Second variant (happened once): Package configuration fails.
`Setting up jitsi-meet-prosody (1.0.8242-1) ...
grep: /etc/prosody/conf.avail/my.domain.com.cfg.lua: No such file or directory
grep: /etc/prosody/conf.avail/my.domain.com.cfg.lua: No such file or directory
grep: /etc/prosody/conf.avail/my.domain.com.cfg.lua: No such file or directory
sed: can't read /etc/prosody/conf.avail/my.domain.com.cfg.lua: No such file or directory`

Haven't tried to salvage that one.

**Comment by damencho** [comment]
> Both jvb.log and jicofo.log report TLS trust issues, i.e.:
> `JVB 2024-11-21 21:35:50.592 WARNING: [515] [hostname=localhost id=shard] MucClient$2.connectionClosedOnError#341: Closed on error: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed`

This is normal during installation, at the end of the installation both are restarted and should connect correctly without errors.

How are you reinstalling using this [command](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/#uninstall)?

**Comment by damencho** [comment]
> Yes, for the purge part - i don't use sudo, but that shouldn't make a difference. After that `apt install jitsi-meet`.
> 
> >

But you purge all the packages?

**Comment by damencho** [comment]
Yeah maybe when purging this file is not deleted: `/var/lib/prosody/$JICOFO_AUTH_DOMAIN.crt` if that is the case, PRs are welcome.

**Comment by c2n14-go-brr** [comment]
The .crt file in /var/lib/prosody/ is consistently deleted after purging, at least for me, but I've noticed an ordering issue during install. Apt sets up the packages in this order:

- jitsi-videobridge2
- jitsi-meet-prosody
- jitsi-meet-web-config
- jicofo
- jitsi-meet-web
- jitsi-meet

The jitsi-meet-prosody.postinst script triggers a conditional restart for jicofo, which fails (`Failed to restart jicofo.service: Unit jicofo.service not found.`). This itself would not be an issue, as jicofo is set up later - but (for reasons beyond my understanding) this leaves jvb in a broken state.

**Comment by damencho** [comment]
> This itself would not be an issue, as jicofo is set up later - but (for reasons beyond my understanding) this leaves jvb in a broken state.

jitsi-meet-prosody, sets up the locally trusted certificates. JVB at that time is giving the certificate error, but at the end of the jitsi-meet-prosody postinst jvb should be restarted and the certs are all in place and locally trusted and jvb should connect without errors this time.
