### ISSUE TITLE
jitsi-meet-prosody debian postinst fails when changing hostname back

### ISSUE THREAD

**Issue by ariep** [jitsi/jitsi-meet#3337]
The [debian postinst script](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst) doesn't work when the hostname (as set by debconf) has been changed back to a value that it had earlier.

Steps to reproduce:
1. install via apt, using hostname `localhost` (I get version 1.0.2942-1)
1. `echo jicofo jitsi-videobridge/jvb-hostname string temp | debconf-set-selections`
1. `/var/lib/dpkg/info/jitsi-meet-prosody.postinst configure`
1. `echo jicofo jitsi-videobridge/jvb-hostname string localhost | debconf-set-selections`
1. `/var/lib/dpkg/info/jitsi-meet-prosody.postinst configure`

Expected outcome: the package is configured correctly for hostname `localhost`, with a config file in `/etc/prosody/conf.d/localhost.cfg.lua`.

Actual outcome: `/etc/prosody/conf.d` is empty.

I think this is because the postinst script doesn't remove the config file from `conf.avail` on lines 74–78, while on line 92 it checks for the existence of the config file in `conf.avail`, not `conf.d`.

**Comment by ariep** [comment]
Additionally, there is a similar problem with the certificates: the same lines 74–78 remove `localhost.{key,crt}` from `/etc/prosody/certs/`, but not from `/var/lib/prosody/`, so the check on line 119 will fail, and the old certificate will be available in `/var/lib/prosody` but is not symlinked in `/etc/prosody/certs`. Result: prosody cannot find `/etc/prosody/certs/localhost.key` as referenced in the configuration generated by postinst itself, and fails to start.

**Comment by vlad88sv** [comment]
>     4\. echo jicofo jitsi-videobridge/jvb-hostname string localhost | debconf-set-selections

Many thanks for this command, I was stuck in dpkg/apt because I entered an empty string for domain when installing Jitsi as per the website instructions for Ubuntu
