### ISSUE TITLE
Quick install not working

### ISSUE THREAD

**Issue by hohi2007** [jitsi/jitsi-meet#3341]
Hi Admin,
I'm try Quick install but it not working,
My errors message:
_root@xxx:/# apt-get -y install jitsi-meet
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.2975-1) but it is not going to                                                                                                                                                              be installed
E: Unable to correct problems, you have held broken packages._

My info version:
Ubuntu: 18
Java: 1.8.0_181
Apache2: Apache/2.4.29 (Ubuntu)
node : 9.2.1
npm : 5.5.1
Python: 2.7.12

My step install Jitsi Meet:
https://github.com/jitsi/jitsi-meet/wiki/Tutorial-for-Building-Out-an-install-from-scratch:-Ubuntu-16.04-Apache2

Please help me

**Comment by saghul** [comment]
That page was bogus, I just deleted it. Please follow this guide: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

**Comment by hohi2007** [comment]
Thank you,
I will try again
