### ISSUE TITLE
Installing a custom jitsi-meet on a windows server?

### ISSUE THREAD

**Issue by BlakeEram** [jitsi/jitsi-meet#3343]
Is there a tutorial I can follow? or a document that has some place to start? 
Thanks

**Comment by saghul** [comment]
Windows is not a supported platform, I'm afraid. You can, however, try our [Docker based setup](https://github.com/jitsi/docker-jitsi-meet).

**Comment by BlakeEram** [comment]
do you think this would work, https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by saghul** [comment]
I honestly don't know. It should be relatively easy to give it a try though, but I've never done it myself so I can't help you, in case you run into problems.
