### ISSUE TITLE
SHaring screen

### ISSUE THREAD

**Issue by nationsorg** [jitsi/jitsi-meet#3346]
Hi, is it possible in Chrome? thanks

**Comment by damencho** [comment]
Yes, it is, you can check it on meet.jit.si. 
To enable it on your deployment an extension is needed for now https://github.com/jitsi/jidesha

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by nationsorg** [comment]
Bonjour,

  I'm not a programmer and I'm not making the deployement.
  I was needed just a simple plugin to enable the screen sharing.

  Thank you.

Saturday, August 4, 2018, 6:28:54 AM, you wrote:

> Yes, it is, you can check it on meet.jit.si.
> To enable it on your deployment an extension is needed for now https://github.com/jitsi/jidesha
> Please in the future when you have questions or problems, before
> opening an issue, discuss them first on the community forum:
> https://community.jitsi.orgas stated in the issues template, thank you.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jitsi/jitsi-meet","title":"jitsi/jitsi-meet","subtitle":"GitHub
> repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open
> in
> GitHub","url":"https://github.com/jitsi/jitsi-meet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@damencho
> in #3346: Yes, it is, you can check it on meet.jit.si. \r\nTo enable
> it on your deployment an extension is needed for now
> https://github.com/jitsi/jidesha\r\n\r\nPlease in the future when
> you have questions or problems, before opening an issue, discuss
> them first on the community forum: https://community.jitsi.org as
> stated in the issues template, thank you."}],"action":{"name":"View
> Issue","url":"https://github.com/jitsi/jitsi-meet/issues/3346#issuecomment-410422595"}}}[
> { "@context": "http://schema.org", "@type": "EmailMessage",
> "potentialAction": { "@type": "ViewAction", "target":
> "https://github.com/jitsi/jitsi-meet/issues/3346#issuecomment-410422595",
> "url":
> "https://github.com/jitsi/jitsi-meet/issues/3346#issuecomment-410422595",
> "name": "View Issue" }, "description": "View this Issue on GitHub",
> "publisher": { "@type": "Organization", "name": "GitHub", "url":
> "https://github.com" } }, { "@type": "MessageCard", "@context":
> "http://schema.org/extensions", "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re:
> [jitsi/jitsi-meet] SHaring screen (#3346)", "sections": [ { "text":
> "", "activityTitle": "**Дамян Минков**", "activityImage":
> "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
> "activitySubtitle": "@damencho", "facts": [  ] } ],
> "potentialAction": [ { "name": "Add a comment", "@type":
> "ActionCard", "inputs": [ { "isMultiLine": true, "@type":
> "TextInput", "id": "IssueComment", "isRequired": false } ],
> "actions": [ { "name": "Comment", "@type": "HttpPOST", "target":
> "https://api.github.com", "body": "{\n\"commandName\":
> \"IssueComment\",\n\"repositoryFullName\":
> \"jitsi/jitsi-meet\",\n\"issueId\": 3346,\n\"IssueComment\":
> \"{{IssueComment.value}}\"\n}" } ] }, { "targets": [ { "os":
> "default", "uri":
> "https://github.com/jitsi/jitsi-meet/issues/3346#issuecomment-410422595"
> } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name":
> "Unsubscribe", "@type": "HttpPOST", "target":
> "https://api.github.com", "body": "{\n\"commandName\":
> \"MuteNotification\",\n\"threadId\": 364581473\n}" } ], "themeColor": "26292E" } ]



-- 
Best regards,

NATIONSORG Association
Intérêt général

Organisme de formation enregistré sous le numéro 84691452869.
Cet enregistrement ne vaut pas agrément de l’État

www.Nationsorg.com                      mailto:info@nationsorg.com

Language courses:
http://abc.nationsorg.com

International Facebook group Nationsorg:
https://www.facebook.com/groups/nationsorgcom/



If you do not wish to receive future e-mail updates, please reply with the Subject: UNSUBSCRIBE
Si vous ne souhaitez plus recevoir de messages de notre part, envoyez le mot DESINSCRIRE dans l'objet de la lettre.

Please consider the environment before printing this email.

**Comment by damencho** [comment]
Yep, jidesha is a simple plugin which enables screen sharing. There are instructions on how to prepare the extension and then you need to upload it to chrome webstore. For now this is the only option to use screen sharing with chrome. 
There will be changes and in 6 months or 1 year this will be possible without an extension, but everything is in the hands of Google when they will release it in chrome.
You can use screen sharing with Firefox without extension. Or you can simply use meet.jit.si, where the extension is already published.
