### ISSUE TITLE
Can I make mobile access to a 'self-signed' server?

### ISSUE THREAD

**Issue by leka2002** [jitsi/jitsi-meet#3348]
Can I make mobile access to a 'self-signed' server?

Can I customize it for mobile access to a 'self-signed' server?

**Comment by damencho** [comment]
No, mobile devices need a trusted certificate.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
