### ISSUE TITLE
enable recording ,but tip "Guests can't start recording",How to repair it

### ISSUE THREAD

**Issue by martinyulin** [jitsi/jitsi-meet#3355]
![image](https://user-images.githubusercontent.com/6227438/43829686-2167c5f4-9b32-11e8-87af-b750bde5e017.png)

**Comment by virtuacoplenny** [comment]
The button being enabled is based on several flags:
https://github.com/jitsi/jitsi-meet/blob/1d99abc4a42575905392d9b2a5d73fad9e85626a/react/features/recording/components/Recording/AbstractRecordButton.js#L127
https://github.com/jitsi/jitsi-meet/blob/1d99abc4a42575905392d9b2a5d73fad9e85626a/react/features/recording/components/Recording/RecordButton.web.js#L95

From what I see, to have it enabled you'll need:
1. Be a moderator
2. config.fileRecordingsEnabled set to a truthy value
3. config.enableFeaturesBasedOnToken be falsy or if it is truthy somehow have the localparticipant have the property features.recording to be true. I think enableFeaturesBasedOnToken should be falsy for you but maybe it's the issue? Try executing `APP.store.getState()['features/base/participants'][0]` in the web console to see what your values are for the local participant.

**Comment by Ark74** [comment]
Hello!
I'm reviewing this issue, the output for 
`APP.store.getState()['features/base/participants']`

`Object { avatarID: "fd9d167a28422f40c6ed0836ed4da45a", avatarURL: undefined, botType: undefined, conference: undefined, connectionStatus: undefined, dominantSpeaker: false, email: "", id: "6c39c12f", isFakeParticipant: undefined, local: true, 7 more… }`

As the first person to arrive to the room, 
I was moderator, but here it doesn't look like it.

**Comment by virtuacoplenny** [comment]
What environment are you testing on? What is the value of `APP.store.getState()['features/base/participants'][0].role`?

**Comment by Ark74** [comment]
Hehehe :nerd_face: 
Sorry 
Here the right command,
```
APP.store.getState()['features/base/participants'][0].role
"moderator"
```

![jibri](https://user-images.githubusercontent.com/7444518/45309266-f758bb80-b4e8-11e8-8685-5c7188268d98.png)

**Comment by Ark74** [comment]
Any clue?

**Comment by virtuacoplenny** [comment]
@damencho, sorry, but I have to defer to you. I think I'm not reading the code correctly. What is necessary to get local recording working?

**Comment by Ark74** [comment]
I've test so many times that I've come out with a [script](https://gist.github.com/Ark74/01b1c87527169cc490488b2dcd5726c3) to _simplify_ the installation process.
@damencho @virtuacoplenny 
Do you mind give an opinion or two?

**Comment by damencho** [comment]
@Ark74 There are two things here, first there is a bug that I'm fixing. 
But also to enable it, you need to enable the dropbox integration: 
https://github.com/jitsi/jitsi-meet/blob/df0e107ea60fa34daab0a5d080a4024c6f335d10/react/features/recording/components/Recording/AbstractRecordButton.js#L132

**Comment by Ark74** [comment]
>  you need to enable the dropbox integration

Ohh wow!, that's new, sounds great.

**Comment by Ark74** [comment]
@damencho couldn't find AbstractRecordButton.js on the custom installation of meet/jibri
Also, are we talking about a ClientID key/secret or an Access token?
Just in case I have tested,

- drobox
- dropbox.clientId
- dropboxClientId

 on config.js with no changes :laughing: 

Is it necessary to set and build that _string_ into meet?

**Comment by Ark74** [comment]
@damencho Yeah indeed, upgraded to meet #3355, then tried different variable names for Dropbox (access token) on config.js.

**Comment by damencho** [comment]
And you have in the config
```
fileRecordingsEnabled: true,
enableUserRolesBasedOnToken: false, // or not existing
enableFeaturesBasedOnToken: false, // or not existing,
dropbox: {
   clientId: 'something'
}
```
Also, check that in interface_config.js in TOOLBAR_BUTTONS you have a listed item 'recording'.

**Comment by Ark74** [comment]
> dropbox: {
>    clientId: 'something'
> }

Hmmm, that makes sense.

Yeah sure, `recording` is by default on TOOLBAR_BUTTONS, so by default shouldn't be a issue :wink:

**Comment by Ark74** [comment]
Never mind, it does parses correctly clientid (not access token), also make sure to set in your DB app the redirect uri.

Well I can confirm, that enabling dropbox (among other things) does enable the start recording button.
![db-jb](https://user-images.githubusercontent.com/7444518/45403931-13a84580-b61a-11e8-9463-a565e97b9935.png)

Thank you for the follow up details.

I'm still having issues, but I'm pretty sure is related to the several changes I made before I realize these new features, have a look tomorrow.
Good night!

**Comment by vincentwlau** [comment]
The current implementation is tightly coupled with Dropbox.  If we would like to upload the file to somewhere other than Dropbox, how can it be done through configuration?

**Comment by bbaldino** [comment]
The dropbox requirement will be reverted soon.
