### ISSUE TITLE
Welcome page no longer working when not running in context root.

### ISSUE THREAD

**Issue by guusdk** [jitsi/jitsi-meet#3356]
We're running an instance of meet, but not in the context root of the web server (we're running it on https://example.org/meet/ instead of https://example.org/ ). 

After updating from 1.0.2862 to 1.0.2942 (which corresponds to stable/jitsi-meet_3229), the welcome page is misbehaving. When pressing the 'go' button, the user is redirected to https://example.org/roomname, instead of https://example.org/meet/roomname (and sees a 404).

**Comment by guusdk** [comment]
The issue persists in jitsi-meet-1.0.2985.tar.bz2, which is the latest release at the time of writing.

**Comment by virtuacoplenny** [comment]
I looked into this yesterday.There was refactoring done with the frontend routing. App.web.js used to have an instance variable called `getLocationContextRoot`. That variable held the full context was used to navigate to the meeting page. With refactoring, that logic changed and the instance variable removed. I couldn't understand how the routing logic works so I couldn't find a fix. I'll try again soon and maybe Saul will too as he's now (probably and unfortunately for him) the most knowledgeable about the routing.

**Comment by saghul** [comment]
@guusdk Can you please test this? https://github.com/jitsi/jitsi-meet/pull/3375

**Comment by saghul** [comment]
The fix landed, closing.
