### ISSUE TITLE
How can I disable 'Lock Room'

### ISSUE THREAD

**Issue by ryuheimat** [jitsi/jitsi-meet#3359]
Jitsi sdk provides 'Lock Room' feature or is it extra feature what 'jitsi-meet' react native app have?
I want to disable 'Lock Room' from SDK if sdk belongs it.

**Comment by saghul** [comment]
Yes, it’s part of the SDK, but you can’t disable it (unless you edit the code yourself). It also depends on a server component, so a different user could lock the room, even if you hide the option.
