### ISSUE TITLE
Need docs to Intergrate jitsi meet in existing react native project 

### ISSUE THREAD

**Issue by themakerman** [jitsi/jitsi-meet#3363]
Why there are no docs on this yet? Would really appreciate if someone from jitsi team looks into this....

**Comment by saghul** [comment]
HI there! Alas it's not a simple process due to how our app / SDK is structured. We had to diverge from standard conventions because we are not really building an app in React Native, but an SDK which uses React Native and then exposes a native interface (if that makes any sense).

Sorry, but I don't see being solved anytime soon since it would require nontrivial effort to consider all usage scenarios.

**Comment by themakerman** [comment]
@saghul completely understand. However will someone from atlasiasn team would be keen to help someone like me who wants to document the integration part?..... Once I understand the pieces of code and how they work together... I can document everything and mayb PR for the community?

**Comment by saghul** [comment]
@themakerman Sure, I can be that person. Feel free to get started and send questions my way. We can use this issue for that.

**Comment by markmadlangbayan** [comment]
Hi @saghul , we're on the boat.  We have an existing app written in RN and native (swift).  I'm trying to use the SDK, and running into an issue.  

![image](https://user-images.githubusercontent.com/5464773/44362522-dcb19a80-a486-11e8-86ec-0fa75414304a.png)

The thing is, I just added the webrtc and jitsimeet frameworks, and make sure the app loads properly.  I haven't made any code changes that calls any jitsi code.

So my question is, does the jitsimeet framework do anything even if it hasn't been called yet?

FYI, I cannot recreate the issue with a blank react-native app or blank swift project.  I don't have an issue, but I do notice on blank react-native that it display warning messages that some module couldn't be loaded.

Unfortunately, on our app, it just fails.

**Comment by themakerman** [comment]
Closing the issue. Feel free to reopen in future.
