### ISSUE TITLE
Can't change interface language via API

### ISSUE THREAD

**Issue by dalton-e** [jitsi/jitsi-meet#3367]
I can change the language in the settings menu but the code below doesn't seem to work:

```
var domain = "meet.jit.si";
var options = {configOverwrite: {defaultLanguage: 'fr'}} 
var api = new JitsiMeetExternalAPI(domain, options);
```
Is it possible to do it this way?
Thanks!

**Comment by virtuacoplenny** [comment]
Maybe the same as https://github.com/jitsi/jitsi-meet/issues/3143? The language is getting set and stored as preferred on the first load of the application. So if the app was visited without a config overwrite, then it will default to english and store that as preferred.

**Comment by dalton-e** [comment]
Thanks, I will double check but I already tried cleaning the cache/localstorage and opening the url in other browsers/computers, still in english.

Is this code supposed to be commented?
```
    // Default language for the user interface.
    // defaultLanguage: 'en',
```

**Comment by virtuacoplenny** [comment]
Yeah. If a config is commented there should be a default being set somewhere else already; that way the config becomes more for overrides instead of setting a value. Someone else on the jitsi team looked into the issue some time ago and said the library i18next was setting the default to english.

**Comment by dalton-e** [comment]
Okay, thanks for your help!
