### ISSUE TITLE
Jitsi mobile app show you are disconnected

### ISSUE THREAD

**Issue by MSaadatt** [jitsi/jitsi-meet#3368]
Hi,
I have run jitsi on docker with this documentation:

https://github.com/jitsi/docker-jitsi-meet

I have been added a Nginx proxy to handle SSL certificate and my SSL certificate is not self-assigned.

Jitsi works fine when I use it from any browser in my desktop but not working from a mobile app and show you are disconnected and check your internet connection.

What is the problem?

Jitsi app URL:  http://test1.yomobit.de

**Comment by saghul** [comment]
There is a bug in handling the relative BOSH URL, please see: https://github.com/jitsi/docker-jitsi-meet/issues/2#issuecomment-409202397

I hope to fix that soon.

**Comment by saghul** [comment]
This got fixed and a new version was released in the Play Store. Please give it a try!
