### ISSUE TITLE
Jitsi Meet API not working in Firefox 61.0

### ISSUE THREAD

**Issue by Debilera** [jitsi/jitsi-meet#3371]
Working fine in Chrome and other browsers, super fustrating. Error shows:

TypeError: "e is null"
ehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2699176reliableMarginLefthttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2699788gethttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2650105csshttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2700965csshttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2702304Dehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2684883csshttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2702140calculateAvailableSizehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:861173calculateThumbnailSizehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:860327resizeThumbnailshttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:852280inithttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:847967starthttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2845562valuehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2625294valuehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:2624283commitLifeCycleshttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1154840whttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1142646_https://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1141456ghttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1140987vhttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1140824hhttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1140203chttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1139665enqueueSetStatehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1128965setStatehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:1080894valuehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:333969valuehttps://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:333945<anonymous>https://cdn.jitsi.net/2942/libs/app.bundle.min.js?v=2942:2:539427 react-dom.production.min.js:150:111

**Comment by virtuacoplenny** [comment]
I'm unable to repro the issue on Firefox 61.0.2 (mac). Could you tell me how you're initializing the api or provide me a repro case?
