### ISSUE TITLE
Jitsi-meet-prosody not installing

### ISSUE THREAD

**Issue by BlakeEram** [jitsi/jitsi-meet#3380]
After trying: sudo apt-get install jitsi-meet
 jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.2942-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I was able to install jitsi-meet before on a different ubuntu

Thanks for the help!

**Comment by saghul** [comment]
What ubuntu version and architecture is this? Without any details it's impossible for us to help you.
