### ISSUE TITLE
Much more lag and glitches vs other WebRTC options

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#339]
So, https://talky.io/ or https://opentokrtc.com/ and other sorts of direct WebRTC functions have *much* higher quality connections with much better frame rates, less lag, less glitches, less freezes etc. They support multi-party…

Unfortunately, both of those options are lacking in other ways. One has a nice recording function, but otherwise, the feature set and design of meet.jit.si is superior, if only the connection were on par.

I tried with the latest Firefox 40, glad to see meet.jit.si working now, but still these connection issues.

Is there any way to have meet.jit.si use the better connections of the technology those other tools use while keeping the better interface and feature set?

From my outside impression, it seems meet.jit.si is still using non-standard WebRTC functions that should probably be replaced with the more standard operations. But I don't know enough to actually say. I'm just reporting the quality issues and hoping they are fixed soon (or that other sites get more of the meet.jit.si features or that a fork could be made that mixes the best aspects of all these).

**Comment by emcho** [comment]
Hey @wolftune 

This one sounds like an interesting discussion but it is much too broad of subject to qualify as a ticket. 

You are welcome to post and start the discussion on our mailing list!

Cheers,
Emil

**Comment by wolftune** [comment]
@emcho Fair enough, but I'm not active enough as a user / dev to get involved at the moment. Would you potentially pass on my note to the mailing list, perhaps with a more pointed request: add an FAQ somewhere for people to read about why meet.jit.si has these problems (if you know they do, maybe the privacy-protection / encryption isn't possible the way the other sites work?)

**Comment by emcho** [comment]
The main concern here is that X works better for me than Y does not generally tell us a whole lot. It could very well be that your route to our single box running meet.jit.si is not so good. We do have a bunch of things in mind to improve this but they are all deployment specific problems and not issues of the videobridge/meet applications.

I didn't get the part about the non-standard webrtc features but I'd say it's pretty safe to assume they have little to do with the quality problems that you experienced.

**Comment by wolftune** [comment]
I've tried meet.jit.si from several different locations in different states, and the contrast is stark. Indeed, it seems likely related to the route to the single meet.jit.si box. Are there any other alternatives to testing this / using it otherwise without doing the work of setting up our own host?

**Comment by emcho** [comment]
We are working on this. Hopefully we would have something to talk about next week.

**Comment by wolftune** [comment]
Great, I look forward to the announcement
