### ISSUE TITLE
Jitsi homepage disappearing after enabling call_control

### ISSUE THREAD

**Issue by abhijitnathwani** [jitsi/jitsi-meet#3391]
Hi, 
I have installed jitsi through the package manager, along with jigasi. I see from the various other issues and readme, that in order to place a SIP call from the conference through Jigasi, we need to enable ```call_control``` in the ```config.js``` for jitsi meet. When I do that change and restart the services, the Jitsi homepage on my local disappears. Nothing but a black screen is visible. Also, commenting the ```call_control``` and restarting the services makes Jitsi meet work fine, but the Jigasi feature to add a SIP call does not work.

Thanks, 
Abhijit Nathwani

**Comment by saghul** [comment]
Can you show us your JS console logs? Also the config.js might shed some light.

**Comment by abhijitnathwani** [comment]
Hi, 
Please find the attached ```config.js``` and console logs.
[config.txt](https://github.com/jitsi/jitsi-meet/files/2310354/config.txt)
![consolejs](https://user-images.githubusercontent.com/5513984/44464403-4c1abc00-a638-11e8-99de-72b699b21c24.png)

**Comment by saghul** [comment]
You are missing a comma in the `muc` line.
