### ISSUE TITLE
[iOS] Enable bitcode

### ISSUE THREAD

**Issue by lxcid** [jitsi/jitsi-meet#3394]
I try to search around but realise that no one really mentioned (either in GitHub issue or Community)…

In 17 Oct 2016, This commit 2f11e85304ca6dad02a303f89a1da26ac38d353d disable bitcode. Its been 2 years, I was wondering if turning on bitcode is safe?

**Comment by saghul** [comment]
I  have no indication about anything being different. 

We have no plans to turn it on, but of course you are free to compile the WebRTC framework yourself and also turn it on for the SDK.
