### ISSUE TITLE
Video on the Jitsi-Meet web app frozen after the JVB failover

### ISSUE THREAD

**Issue by vincentwlau** [jitsi/jitsi-meet#3397]
Re-post the prior discussions in the correct group.

In the prior discussions in Jicofo 
[Re-invite failed when Jicofo select another JVB after one crash #282](https://github.com/jitsi/jicofo/issues/282#issuecomment-411526795)
the problem was confirmed by @bgrozev. He believed that the Jitsi Meet web client didn't reinitialize correctly and caused the video frozen.  Here is the short recap:

We had two JVB's and one Jicofo, and we disabled P2P in config.js forcing the media streams via JVB.  During a call conference, we shutdown the active JVB.  After Jicofo performed the failover on the 2nd JVB, the video/audio were streamed via the new JVB correctly.  But the video was frozen on both web clients; however, audio was played correctly.

Does anyone have a chance look into this issue?  Any hints which files we should look into?

**Comment by paweldomas** [comment]
Is it the latest version that you're using ? Do you see active speaker updates after the conference migration ?

**Comment by vincentwlau** [comment]
@paweldomas We have been using the 2018-05-01 stable build (jitsi-meet_1.0.2988-1.)  Yes, I can see the active speaker updates in the PIP window.

**Comment by damencho** [comment]
There was a fix for migrating conferences two months ago https://github.com/jitsi/jitsi-meet/commit/e06ad6cea9656a249039e77289c2131ed6bdfb5e, but maybe there are more problems as Boris suggested in https://github.com/jitsi/jicofo/issues/282#issuecomment-411526795

**Comment by paweldomas** [comment]
I think this issue might be fixed by https://github.com/jitsi/lib-jitsi-meet/commit/2080e812a9e565a7151df367b31b12429ce5b50e

The next release after https://github.com/jitsi/jitsi-meet/pull/3775 is merged should have the fix.
