### ISSUE TITLE
Unhandled JS Exception: undefined is not an object (evaluating 'e.callUUID')

### ISSUE THREAD

**Issue by markmadlangbayan** [jitsi/jitsi-meet#3401]
I'm getting the errors below on my app using `example-pip-app` code.  It seems it's working, but I don't see this error message when running the `app` code.  The issue is `reproducable` if I run the `example-pip-app`.

Any clue how to resolve this issue?

`... [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'e.callUUID')
... [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'e.callUUID')`

**Comment by Lucas15andrade** [comment]
Did you manage to solve it? I am experiencing the same problem.

**Comment by TBG-FR** [comment]
@Lucas15andrade Got the same issue too, maybe it's related to https://github.com/jitsi/jitsi-meet/issues/4770 ? If I manage to fix it I'll tell you

**Comment by saghul** [comment]
You need to enable the voip background mode.

**Comment by Aydogdyshka** [comment]
@saghul with voip background mode enabled, issue persists what now sir ?
