### ISSUE TITLE
view screen sharing failed when peer without cam & mic

### ISSUE THREAD

**Issue by havid0707** [jitsi/jitsi-meet#3402]
![image](https://user-images.githubusercontent.com/9440277/44579628-90899180-a7c9-11e8-99bb-9c92374cb9b1.png)

A user (without microphone and camera) sharing his screen to B user , B user can not show the largevideo.
how to fix this ? Thanks

**Comment by virtuacoplenny** [comment]
Are you running on latest jitsi-meet? I can't repro the issue. Is there a place where I can test this out? Here are the steps I took:
1. User A creates a conference and denies mic/camera permissions (also tried with a computer with no mic/camera).
2. User B joins the conference.
3. User A starts screensharing.

**Comment by havid0707** [comment]
Sorry, My code is not up to date and your steps is correct.
I have test https://meet.jit.si and it works well.

My code is probably around June 20th. I don't want to upgrade to the latest code for now.
If you know what changes are related to this, I am very grateful.

**Comment by havid0707** [comment]
I have found the reason. Thanks
![image](https://user-images.githubusercontent.com/9440277/44638593-4af7df00-a9ea-11e8-990d-fd680be21394.png)
