### ISSUE TITLE
Option disableRemoteControl works?

### ISSUE THREAD

**Issue by markinfurkin** [jitsi/jitsi-meet#3407]
i'm trying remove the kick and mute button , i found this config **disableRemoteControl**
`var options = {
			roomName: roomNameId,
			width: '100%',
			height: 400,
			parentNode: document.querySelector('#container-chamada'),
			configOverwrite: {
				defaultLanguage: 'ptBR',
				disableRemoteControl:true,
				debug:true
			},
			interfaceConfigOverwrite: {
				TOOLBAR_BUTTONS: ['microphone', 'camera', 'settings', 'videoquality', 'filmstrip'], 
				SETTINGS_SECTIONS: ['devices', 'language'],
				SHOW_JITSI_WATERMARK: false,
				SHOW_WATERMARK_FOR_GUESTS: false
			},
`

But, not working for me, he still there:
![image](https://user-images.githubusercontent.com/8128485/44795154-67c61b00-ab80-11e8-8a62-9b51291fecc5.png)
anyone knows solve this?

**Comment by damencho** [comment]
The config disableRemoteControl is for disabling remote control, which is available when the remote participant is using jitsi-meet-electron app. 
Currently, there is no option to remove kick and mute buttons.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
