### ISSUE TITLE
jitsi meet not installing

### ISSUE THREAD

**Issue by avi-panchal** [jitsi/jitsi-meet#3427]
After trying: sudo apt-get install jitsi-meet -y
jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.2942-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I am installing it on Ubuntu 18.04 server

Thanks for the help!

**Comment by damencho** [comment]
I just tried it on fresh VM Ubuntu 18.04 and it works just fine following the instructions.
Do you have any other error before that? What is the output of `dpkg -l | grep jitsi`?

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by mdre77** [comment]
Got the same issue. Installed ubuntu-server-18.04. Added the repo as described in the quick install document. Tried to install jitsi-meet and got the following output:

> root@jitsi:~# LANG=posix apt-get install jitsi-meet
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:

> The following packages have unmet dependencies:
> jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.2942-1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by damencho** [comment]
@mdre77 was it clean install? I mean jitsi-meet was not installed prior that?

**Comment by mdre77** [comment]
Yes. It was a clean installation. Installed from the latest iso:
[](http://releases.ubuntu.com/18.04/ubuntu-18.04.1-live-server-amd64.iso)

**Comment by damencho** [comment]
Thanks, i will try it out and will share my results

**Comment by damencho** [comment]
@mdre77 @avi-panchal 
The problem is that when you install ubuntu by default it comes with only `main` repository enabled. 

You need to enable and `universe`. Prosody is in universe. Edit file `/etc/apt/sources.list` and add 
```
deb http://archive.ubuntu.com/ubuntu bionic universe
``` 
or similar depending on the mirror you use. Make sure you do `apt update` after that.

More info at https://help.ubuntu.com/community/Repositories/Ubuntu

**Comment by grandchild** [comment]
This should be mentioned then in the quick install documentation.
