### ISSUE TITLE
Cannot unmute video on Firefox 40.0

### ISSUE THREAD

**Issue by seanmheff** [jitsi/jitsi-meet#343]
When I mute my local video on Firefox, I cannot unmute myself.

When I click the unmute icon in the toolbar, nothing seems to happen. I need to refresh the page to get back into the meeting.

Happening on Firefox 40.0 using OSX

**Comment by bgrozev** [comment]
@seanmheff does that happen with a conference with 1 firefox and one (or more) chromes?

**Comment by bgrozev** [comment]
@seanmheff Can you currently reproduce this on beta.meet.jit.si (or another up-to-date installation)? I suspect/hope that it was fixed in https://github.com/jitsi/jitsi-meet/commit/711d4ab63428269cc91aea7e548ec61418070725

**Comment by seanmheff** [comment]
Yes I can confirm that this is now fixed.

Thanks.
