### ISSUE TITLE
Can use bare IP address not domain?

### ISSUE THREAD

**Issue by cnscns** [jitsi/jitsi-meet#3432]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Yes, but you will not be able to use Let's encrypt certificates or any certificates other than self-signed.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by cnscns** [comment]
OK.Is there any reference?

**Comment by haofanning** [comment]
Did it solved?

**Comment by saghul** [comment]
No, this is never going to work. Use a domain name.

**Comment by haofanning** [comment]
OK then, thanks for reply
