### ISSUE TITLE
How to setup jitsi-meet, jicofo and jitsi-video bridge from source code

### ISSUE THREAD

**Issue by kraghupathi** [jitsi/jitsi-meet#3433]
How to setup/run jitsi-meet, jicofo and jitsi-video bridge from source code on Ubuntu-16.04.

**Comment by kraghupathi** [comment]
Please solve the above issue as quickly possible

**Comment by bgrozev** [comment]
One way is to install the debian packages, then replace the contents of `/usr/share/{jitsi-videobridge,jicofo}` with your own build. You can create a package with `mvn install -Dassembly.skipAssembly=false` (you'll see .zip files in the `target` directory).

**Comment by kraghupathi** [comment]
@bgrozev 

Thanks

but I need to run jitsi-meet, jitsi-videobridge and jicofo from source code.

Can you send me the steps how to do

**Comment by damencho** [comment]
https://community.jitsi.org/t/how-to-install-jitsi-meet-jicofo-and-jitsi-videobridge-through-source-code/14891
