### ISSUE TITLE
If do I need to file app.bundle.min.js I can find app.bundle.js file?

### ISSUE THREAD

**Issue by Base2526** [jitsi/jitsi-meet#3434]
If do I need to file app.bundle.min.js I can find app.bundle.js file ?

Thx

**Comment by virtuacoplenny** [comment]
If you're deploying your own instance you don't necessarily need .min.js  but the `index.html` file by default looks for app.bundle.min.js so you'll need to change that. Are you building the js bundles using the `make` command? By default that should be executing the `Makefile` and building the javascript through webpack (`webpack.config.js`) with the minified version.
