### ISSUE TITLE
meeting subtitle  button not showing 

### ISSUE THREAD

**Issue by peererror** [jitsi/jitsi-meet#3441]
## Description
I was using meeting subtitle few days ago but today I was not able to see the cc button to start subtitle 

## Current behavior
subtitle button not showing 

## Expected Behavior
show subtitle button 
## Possible Solution
I think it is related to #3424

## Steps to reproduce
open https://meet.jit.si/  start meeting you will be see there is no cc button now 

# Environment details
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by damencho** [comment]
Stay tuned for announcement this is coming in the following weeks. It was enabled just for a day on meet, but we still need to tune some params on the backend.

Please in th future use the community forum before opening issues.
