### ISSUE TITLE
Room name "room" returns 404

### ISSUE THREAD

**Issue by akshitkrnagpal** [jitsi/jitsi-meet#3450]
Visit the following link.
https://meet.jit.si/room

**Comment by paweldomas** [comment]
Yup, it's a known issues caused by the nginx rule regexpr checking for a "room" phrase

**Comment by akshitkrnagpal** [comment]
@paweldomas 
But this isn't the case in [jitsi/docker-jitsi-meet](https://github.com/jitsi/docker-jitsi-meet).

Can you point me towards the nginx file? There must be a fix for this.

**Comment by paweldomas** [comment]
it could be that it's specific to the meet.jit.si deployment

**Comment by paweldomas** [comment]
Yes, it's specific to AWS shard deployments. A URL starting with 'room' has special meaning there.

**Comment by bgrozev** [comment]
> A URL starting with 'room' has special meaning there.

I think we fixed this, and now it only matches '/room' not '/room*'
