### ISSUE TITLE
Jitsi Desktop Sharing problem

### ISSUE THREAD

**Issue by praveen-kumar-dei** [jitsi/jitsi-meet#3452]
i have enable chrome extension for jitsi as per the URL 
https://www.adamhyde.net/setting-up-jitsi-letsencrypt-cert-and-desktop-sharing/
I am able to see the desktop sharing icon but i am not able to share my desktop

Plesae help me in configuring Desktop sharing on jitsi

**Comment by damencho** [comment]
Have you verified the site when uploading the extension to the store?

In few chrome releases, the extension will no longer be a requirement as it is not when using Firefox.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
