### ISSUE TITLE
Permission denied on android device with front camera only

### ISSUE THREAD

**Issue by leoagle** [jitsi/jitsi-meet#3458]
I build lastest code in jitsi-meet/android of master branch in Android Studio,  and run on Android Device with front camera only. It shows  console error [modules/RTC/RTCUtils.js], failed to obtain video stream - stop. SecurityError, Permission denied.  gum.permission_denied. 
     I try to run react-native run-android in console, still come up this error. 
    
![wechatimg72](https://user-images.githubusercontent.com/7445806/45674688-2eba0e80-bb60-11e8-9d67-6eb8d0a6a8c2.jpeg)

 build platform : Mac 10.13.5
 target: Android 5.1.1, cpu Rx3288

**Comment by leoagle** [comment]
But everything is ok if run the apk downloaded from https://apkpure.com/jitsi-meet/org.jitsi.meet

**Comment by saghul** [comment]
@leoagle Hi there! Are you building the SDK or the Jitsi Meet app itself?

**Comment by leoagle** [comment]
I build the SDK. I just run the android project in jitsi-meet/android, create index.android.bundle and index.android.bundle.meta into android/app/src/main/assets, and then build the SDK and sample app. it runs well on android phone, but show up "Permission denied" on android device with single camera

**Comment by saghul** [comment]
@leoagle It's still not clear to me if you are building the SDK and using your own app or building Jitsi Meet itself.

If you are building your own app, are you using `JitsiMeetActivity` or using your own activity with `JitsiMeetView` ?

**Comment by leoagle** [comment]
@saghul I building Jitsi Meet itself

**Comment by saghul** [comment]
Thanks, I'll try to reproduce this with the emulator.

**Comment by leoagle** [comment]
@saghul Hi, do u reproduce this bug?
