### ISSUE TITLE
Use bower or npm to manage external dependencies

### ISSUE THREAD

**Issue by dwilson6** [jitsi/jitsi-meet#346]
What do you think about using bower or npm to manage strophe, jquery, and jquery-ui instead of having them checked into the repo? Is there any customization in any of those dependencies?

**Comment by gpolitis** [comment]
+1 We already have npm so this should be fairly easy.

**Comment by bgrozev** [comment]
+1

**Comment by dwilson6** [comment]
Ok, so maybe add npm deps and then create a vendor browserify bundle then? Or would you rather copy the individual files into the libs dir from node_modules in build task?

**Comment by dwilson6** [comment]
So it looks like the npm module for strophe doesn't include the minified version of strophe (I've submitted a PR to add it) and the strophe-plugins module is really old and doesn't have the disco and caps plugins.  The bower dependencies are good enough to use.

Also, is it still preferred to have the dependencies checked into the repo? If so, it might make sense to create a vendor bundle and just check that in.

**Comment by hristoterezov** [comment]
Personally I think it would be better to just add the dependancies in the package.json file. NPM will resolve that dependancies and browserify will include them in the app.bundle.js.

**Comment by dwilson6** [comment]
I started this a while ago and finally got around to finishing it up.  The PR is here: https://github.com/jitsi/jitsi-meet/pull/366

**Comment by gpolitis** [comment]
I merged your awesome PR, thank you @dwilson6 !
