### ISSUE TITLE
Android app disconnects when screen turns off

### ISSUE THREAD

**Issue by leoluk** [jitsi/jitsi-meet#3477]
## Description

Jitsi Meet Android app not keeping device awake, even when charging.

## Current behavior

Call drops shortly after screen turns off, showing reconnection screen when turning back on.

## Expected Behavior

App keeps device awake (I've seen other apps do it, so the API exists).

# Environment details

Nexus 5x, Android 8.1.0, latest Play Store release of the React Native app

**Comment by paweldomas** [comment]
Are you using the app with video or in audio only mode ? Currently the app when in the audio only mode is not kept awake by design.

**Comment by leoluk** [comment]
Audio only mode.

**Comment by leoluk** [comment]
This makes it impossible to use the app for audio conferences without manually keeping the device awake, so I can't see how this is intended behavior.

**Comment by paweldomas** [comment]
It's intended to turn off the screen, but it's not intended for the app to be disconnected, so we'll treat that as bug and probably someone will be looking into it.

**Comment by cnscns** [comment]
@leoluk  where is the Jitsi Meet Android app source code and the compile commands?
