### ISSUE TITLE
Is there any way to make the videobridge honor  the standard sdp 'sendonly' direction?

### ISSUE THREAD

**Issue by Paultok** [jitsi/jitsi-meet#348]
Hi guys,

one question before the "real" question: is the videobridge designed around jitsi meet? or is it supposed to be a standard webrtc tool?

Real question: is there any way to make the videobridge honor  the standard sdp 'sendonly' direction? I am interested in sending video /audio only and don't want to receive any media stream from the videobridge.

**Comment by bgrozev** [comment]
Videobridge is not designed specifically around jitsi-meet. However, it does not take part in regular WebRTC offer/answer based on SDP, and therefore cannot honor an "sdp" direction. It can be configured via the control protocol ([COLIBRI](http://xmpp.org/extensions/xep-0340.html)) to not send media on a certain channel by setting said channel's "direction" attribute to recvonly.
