### ISSUE TITLE
Crash on Firefox

### ISSUE THREAD

**Issue by KarimFikani** [jitsi/jitsi-meet#3480]
## Description
Firefox crashes when doing web to web video call. Firefox generated 3 crash reports related to that crash.
https://crash-stats.mozilla.com/report/index/ff29aed5-6d77-4ffa-96db-5b6fc0180925
https://crash-stats.mozilla.com/report/index/6e23cd71-15a6-49e0-8e58-9948a0180925
https://crash-stats.mozilla.com/report/index/1cbdd8a5-5d99-4cd6-a905-db6a30180925

## Steps to reproduce
1. Join a meet room on firefox https://meet.jit.si/atheer and open 'New Incognito Window' on firefox with the same room name.
2. Hang up and join multiple times. At some point firefox crashes.

# Environment details
Firefox 62.0.2 running on MacOS High Sierra (10.13.2)

I was able to repro the crash on prior versions of firefox.

**Comment by damencho** [comment]
There are known Firefox crashes with webrtc which are still not fixed, I suspect it is some of these:
https://bugzilla.mozilla.org/show_bug.cgi?id=1409167
https://bugzilla.mozilla.org/show_bug.cgi?id=1490462

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
