### ISSUE TITLE
P2P connectivity issues on Chrome  69.0.3497.81

### ISSUE THREAD

**Issue by alexlee85** [jitsi/jitsi-meet#3481]
## Description

Jitsi meet web application show "Fellow Jister is having connectivity issues ..." when 2 paticipaints use p2p communication. this is only happen on Chrome 69, no problem on Chrome 68

## Current behavior

Jitsi meet web application show "Fellow Jister is having connectivity issues ..." when 2 paticipaints use p2p communication, but there is no problem with connection, everything is working, except the alert message is shown.

## Expected Behavior

do not show "Fellow Jister is having connectivity issues ..." when 2 paticipaints use p2p communication.

# Environment details

Jitsi meet web application, master branch,  Chrome 69.0.3497.81

**Comment by paweldomas** [comment]
I just gave it a try with that exact Chrome version with two Chrome tabs on https://beta.meet.jit.si and was unable to reproduce the issue...

Is it both Chromes with this version in your case ? Can you check on the beta website if it works for you ?

**Comment by kuklinistvan** [comment]
Same here with two Chromium 69 instances - if one of the clients uses Firefox then the alert does not appear.

**Comment by kuklinistvan** [comment]
As a workaround disabling p2p in meet/config.js prevents this alert

**Comment by ispryt** [comment]
I have the same problem
