### ISSUE TITLE
Chrome and Firefox don't work in the same room

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3482]
When you set up a room in chrome and Firefox users join, chrome users can't get the native video, but Firefox's.Chrome console error reporting,[modules/statistics/RTPStatsCollector.js] <o._processAndEmitReport>:  JitsiTrack not found for SSRC 3009520584 in TPC[1,p2p:true]

**Comment by damencho** [comment]
Can you reproduce this on meet.jit.si? What versions are chrome and firefox?

Please use the community forum before opening new issues

**Comment by c526537207** [comment]
@damencho yes, same problem on meet.jit.si. chrome  68.0.3440.84 and firefox 62.0.2

**Comment by saghul** [comment]
Can't repro, works here: Chrome 70.0.3538.35, Firefox 62.0.2
