### ISSUE TITLE
Jitsi Meet SDK for Android :- Stabel SDK Missing JitsiMeetView functions 'onBackPressed' , 'onHostDestroy'

### ISSUE THREAD

**Issue by smbteam1** [jitsi/jitsi-meet#3487]
We tried to use Jitsi Meet video & audio calling feature in one of our Native Android & IOS App. We followed the GitHub repo  https://github.com/jitsi/jitsi-meet . 

In the app, we have one to one and group calling feature. 

We tried to make this working for android , as mention in the below git url
https://github.com/jitsi/jitsi-meet/tree/master/android.

In your project, first we tried with the pre-build SDK and added the Maven repository https://github.com/jitsi/jitsi-maven-repository/raw/master/releases and the dependency org.jitsi.react:jitsi-meet-sdk into your build.gradle files.

This is working fine.

But our actual requirement was to make use of Jitsi in same way as hangout or whats-app works. ie, when click on the call button , end user should be able to see the calling screen immediately, and should be able to click accept or reject.  For this purpose we had to do some customization in Jisti Meet. 

For that ,

**Below is what we tried to do in Android:**
   
    1. Downloaded the latest release from the Git  repo and unzip it.(stable/jitsi-meet 3344)

    2. Done some customization in Jitsi Meet view.

    3. After the customization we assemble the release and published to a GitHub repo.

    4. In our app’s build.gradle we added the link as dependency.

But it DID NOT worked, showing some errors saying like below **functions in JitsiMeetView are missing** in the downloaded stable version of SDK (stable/jitsi-meet 3344)

**jitsi-meet/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java**

**onBackPressed
onHostDestroy(activity)
onHostResume(activity)** 

**But pre-build SDK is working fine.** https://github.com/jitsi/jitsi-maven-repository/raw/master/releases

Any help is appreciated.!!!

**Comment by ranggamp** [comment]
have you import org.jitsi.meet.sdk.JitsiMeetActivity in your code?
