### ISSUE TITLE
In windows using AndroidStudio open jitsi-meet/android projects build failed

### ISSUE THREAD

**Issue by cnscns** [jitsi/jitsi-meet#3492]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Could not find method android() for arguments [build_2nz1vi7vuuldi3dhn8s4cbbna$_run_closure1$_closure7$_closure16@35fd1adf] on project ':react-native-fast-image' of type org.gradle.api.Project.
Open File

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by cnscns** [comment]
My steps:
1.git clone https://github.com/jitsi/jitsi-meet.git
2.cd jitsi-meet
3.npm install
4.reference to https://github.com/jitsi/jitsi-meet/tree/master/android
5.errors :Could not find method android() for arguments [build_2nz1vi7vuuldi3dhn8s4cbbna$_run_closure1$_closure7$_closure16@35fd1adf] on project ':react-native-fast-image' of type org.gradle.api.Project.

**Comment by saghul** [comment]
Sorry we don't develop on Windows, it's not a platform we support for development. It may work, but if there are problems, we won't be able to help you.

**Comment by cnscns** [comment]
On Ubuntu or MAC？ and using AndroidStudio？

**Comment by saghul** [comment]
@cnscns Yes. But it's easier to use `react-native run-android` instead of launching with Android Studio, because otherwise the bundler process won't be spawned.
