### ISSUE TITLE
 problem on setting up the AudioOnly mode

### ISSUE THREAD

**Issue by adimulyo29** [jitsi/jitsi-meet#3493]
hey, im using jitsi and having a problem on setting up the AudioOnly mode,
this is my code snippet here :

this is my code snippet here :

```
jitsiView = JitsiMeetView(this)
        
val jitsiUrl = "https://mychat.com/"
jitsiView.defaultURL = URL(jitsiUrl)
jitsiView.loadURLString(intent.getStringExtra(keyRoomId) + "#config.startAudioOnly=true")
```

in the call activity if i click the three dot button, the option for AudioOnly is in "Disable AudioOnlyMode"
but the audio is still redirected to the audio speaker. If i deactivate the AudioOnly and reactivated it, the Audio get redirected to the ear speaker. And in the select audio channel there'a an option showing "Phone" channel, that wasn't there in the initialization of the activity.

![jitsi-3](https://user-images.githubusercontent.com/30622219/46267295-4df06d00-c55e-11e8-9535-dfd8d5badb3d.jpg)
![jitsi-1](https://user-images.githubusercontent.com/30622219/46267296-4df06d00-c55e-11e8-97fc-378040a9e6fc.jpg)
![jitsi-2](https://user-images.githubusercontent.com/30622219/46267297-4df06d00-c55e-11e8-93cc-2b6f764acc2d.jpg)

_Originally posted by @RheineAdithia in https://github.com/jitsi/jitsi-meet/issues/1908#issuecomment-425775518_

**Comment by RheineAdithia** [comment]
can someone from the community help us on this issue, we're offering reward for the team who would resolve this problem in the form of donation or anykind. Thank you

**Comment by sandeepjangir** [comment]
Hi @RheineAdithia 

Please email / skype me at sandeep@techsbiz.com

**Comment by Aizaz-Abbasi** [comment]
> can someone from the community help us on this issue, we're offering reward for the team who would resolve this problem in the form of donation or anykind. Thank you

I did you got any solution?
