### ISSUE TITLE
no recording button

### ISSUE THREAD

**Issue by atyenoria** [jitsi/jitsi-meet#3495]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

https://github.com/jitsi/jitsi-meet/blob/a214be0dfee30e13e8c9dd6f2d564ec912688d7b/react/features/recording/components/Recording/AbstractRecordButton.js#L132
There is no recording button when I don't turn dropbox on in config.js

## Current behavior
---
no recording button setting fileRecordingsEnabled: true

## Expected Behavior
---
show recording button setting fileRecordingsEnabled: true

## Possible Solution
---
I don't know. 

## Steps to reproduce
---
above

# Environment details
---
above

**Comment by damencho** [comment]
Currently dropbox is a requirement, we will be working on adding more like google drive.
