### ISSUE TITLE
add configuration field ios

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-meet#3496]
Hi,
I want to modify jitsi meet on ios.
I need to add configuration field in the configuration page.
I need to start a thread with a particular parameter.
I don't undestand in which files I have to touch the code.
Thank you very much
Angelo

**Comment by damencho** [comment]
This is the main panel of the configuration of the mobile app https://github.com/jitsi/jitsi-meet/blob/55794649510768095ae60b61afb0ee8dc67de627/react/features/settings/components/native/SettingsView.js

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
