### ISSUE TITLE
Screen sharing not work in Chrome

### ISSUE THREAD

**Issue by ispryt** [jitsi/jitsi-meet#3500]
Hello!
Chrome 69.0.3497.100
Latest jitsi-meet
Screen sharing not work in Chrome: https://imgur.com/a/9PSFmMP
but in Firefox all is well.

Jitsi install on debian(self signed cert)

**Comment by damencho** [comment]
Is this your deployment or meet.jit.si? If it is yours, had you created and uploaded a chrome extension to web store and enable the extension in the config? https://github.com/jitsi/jidesha

Please use the community forum for questions and problems, before opening new issues.

**Comment by damencho** [comment]
Ups, just saw your last sentence, but yeah did you do the extension config?
