### ISSUE TITLE
jitsi meet framework file is not working with Xcode 10

### ISSUE THREAD

**Issue by manav26** [jitsi/jitsi-meet#3502]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Can you please detail **what** it is that doesn't work? Some build logs, something?

**Comment by manav26** [comment]
when I try to make jitsi meet framework ,completed all the steps but in last framework is not there......

**Comment by manav26** [comment]
![screen shot 2018-10-03 at 5 59 52 pm](https://user-images.githubusercontent.com/43812967/46410350-366bdc80-c736-11e8-9fe3-69f7be4691be.png)

**Comment by saghul** [comment]
That's not where it will be created. See the screenshot below. Choose "Show in Finder".

<img width="378" alt="screen shot 2018-10-03 at 14 41 05" src="https://user-images.githubusercontent.com/317464/46410841-6c9b6300-c71a-11e8-943d-902149aafb5e.png">

**Comment by manav26** [comment]
![screen shot 2018-10-03 at 6 39 14 pm](https://user-images.githubusercontent.com/43812967/46412275-a892f000-c73b-11e8-855e-9f9c4f9425b4.png)

**Comment by saghul** [comment]
You can see it above in "Frameworks".

**Comment by manav26** [comment]
thanks but I can't find where it is ??????

**Comment by saghul** [comment]
I don't know what's wrong in your setup, but I can find it just fine by right clicking and selecting "Show in finder". Did you build and run the app successfully?
