### ISSUE TITLE
jitsi-meet and jigasi cannot make calls

### ISSUE THREAD

**Issue by rzmc10** [jitsi/jitsi-meet#3503]
Hi all,

I have a problem with jitsi-meet and jigasi.
After jigasi installation ( _apt install jigasi_) in jitsi-meet appears the "plus" icon to invite other people.
When I press to the "Invite" button nothing happens.

My configurations are in this txt:
[conf.txt](https://github.com/jitsi/jitsi-meet/files/2442656/conf.txt)

**The prosody logs:**

portmanager     error   Error binding encrypted port for https: No key present in SSL/TLS configuration for https port 5281

c2s558708a7e410 info    Client connected
c2s558708a7e410 info    Client disconnected: ssl handshake error: sslv3 alert certificate unknown

Can you help me?

**Comment by damencho** [comment]
Can you upload js console logs, and jigasi logs?

**Comment by damencho** [comment]
Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by damencho** [comment]
Enable this and restart jigasi and it should be fine: https://github.com/jitsi/jigasi/blob/master/jigasi-home/sip-communicator.properties#L97
