### ISSUE TITLE
Installation of jitsi on ios

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-meet#3505]
Hi,
I'm trying to run jitsi meet built on my ipad.
I set a new id and my team information.
when I launch the application I have the following error:
no bundle url present.
make sure you're running a packeger server or have included a .js bundle file in your application bundle.

thank you very much

**Comment by saghul** [comment]
If you in debug mode, you need to keep the terminal window that opens when you hit run, since that's the process that serves the JavaScript bundle.

If you run in release mode, the bundle will be included with the application.

**Comment by manang** [comment]
in debug mode the terminal window is open.
do you know which command I have to launch to build in release mode using the command line?
Thank you very much

**Comment by saghul** [comment]
I don't know the command by heart, but all you need to do is build the `Release` configuration for the `jitsi-meet` target and the build process will take care of the rest.

**Comment by manang** [comment]
thank you very much.
I'm new with xcode.
thanks again
