### ISSUE TITLE
Jitsi-Meet NOT working on AWS LightSail Ubuntu 14.x

### ISSUE THREAD

**Issue by inglesuniversal** [jitsi/jitsi-meet#3510]
Hi, I had installed Jitsi before on an AWS LightSail plain Ubuntu image and it worked wonderfully.

I tried it today with a fresh new server and got no error during installation.

However when entering the https://mydomain.com to jump into the welcome screen I got a REFUSE CONNECTION ERROR.

I even added the NAT configuration and nothing... :( 

These are the ports that I have opened under networking setup:

TCP
80 / 443 / 4443
UDP
10000 - 20000

Hope you can help me!

Regards

VM profile:

1 G RAM / 1 CORE

**Comment by inglesuniversal** [comment]
ate_conf,conf_id=368a9f5397f1ca36 conf_name=null,logging=false,conf_count=1,ch_count=0,v_st
reams=0
JVB 2018-10-05 16:36:40.763 INFO: [14] org.jitsi.videobridge.health.Health.log() Performed 
a successful health check in 13ms. Sticky failure: false
JVB 2018-10-05 16:36:40.830 FINE: [333] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ(
) (serving component 'JitsiVideobridge') Processing IQ (packetId WJBw4-37897): <iq type="ge
t" to="jitsi-videobridge.mydomain.net" from="focus@auth.mydomain.net/focus12759191154" 
id="WJBw4-37897"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
JVB 2018-10-05 16:36:40.830 FINE: [333] org.jitsi.videobridge.xmpp.ComponentImpl.processIQR
equest() (serving component 'JitsiVideobridge') Processing IQ request (packetId WJBw4-37897
).
JVB 2018-10-05 16:36:40.830 FINE: [333] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV
: <iq type="get" to="jitsi-videobridge.mydomain.net" from="focus@auth.mydomain.net/focu
s12759191154" id="WJBw4-37897"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/>
</iq>
JVB 2018-10-05 16:36:40.830 FINE: [333] org.jitsi.videobridge.xmpp.ComponentImpl.log() SENT
: <iq to="focus@auth.mydomain.net/focus12759191154" from="jitsi-videobridge.mydomain.ne
t" id="WJBw4-37897" type="result"/>
JVB 2018-10-05 16:36:40.830 FINE: [333] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ(
) (serving component 'JitsiVideobridge') Responding to IQ (packetId WJBw4-37897) with: <iq 
to="focus@auth.mydomain.net/focus12759191154" from="jitsi-videobridge.mydomain.net" id=
"WJBw4-37897" type="result"/>
JVB 2018-10-05 16:36:42.504 FINE: [335] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ(
) (serving component 'JitsiVideobridge') Processing IQ (packetId T0EC1-20656): <iq id="T0EC
1-20656" type="result" to="jitsi-videobridge.mydomain.net" from="mydomain.net"/>
JVB 2018-10-05 16:36:42.504 FINE: [335] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV
: <iq id="T0EC1-20656" type="result" to="jitsi-videobridge.mydomain.net" from="mydomain
.net"/>

**Comment by inglesuniversal** [comment]
ast login: Fri Oct  5 16:34:35 2018 from 72.21.217.142
ubuntu@ip-172-26-13-211:~$ sudo tail -f /var/log/jitsi/jicofo.log
Jicofo 2018-10-05 02:16:00.723 INFO: [25] org.jitsi.jicofo.JitsiMeetServices.newNodeDiscove
red().208 Detected XMPP server version: IQ Stanza (query jabber:iq:version) [to=focus@auth.
mydomain.net/focus12759191154,from=auth.mydomain.net,id=WJBw4-23,type=result,]
Jicofo 2018-10-05 02:16:00.724 INFO: [25] org.jitsi.jicofo.ComponentsDiscovery.discoverServ
ices().267 New component discovered: conference.mydomain.net, null
Jicofo 2018-10-05 02:16:00.725 INFO: [25] org.jitsi.jicofo.JitsiMeetServices.newNodeDiscove
red().200 MUC component discovered: conference.mydomain.net
Jicofo 2018-10-05 02:16:00.762 INFO: [25] org.jitsi.jicofo.ComponentsDiscovery.scheduleRedi
scovery().189 Services re-discovery interval: 30000
Jicofo 2018-10-05 02:16:00.763 INFO: [25] org.jitsi.jicofo.FocusManager.log() XMPP provider
 reg state: RegistrationState=Registered
Jicofo 2018-10-05 02:16:00.794 INFO: [25] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider
.doConnect().309 XMPP provider Jabber:focus@auth.mydomain.net/focus12759191154@localhost 
connected (JID: focus@auth.mydomain.net/focus12759191154)
Jicofo 2018-10-05 02:16:30.826 INFO: [41] org.jitsi.jicofo.ComponentsDiscovery.discoverServ
ices().267 New component discovered: jitsi-videobridge.mydomain.net, IQ Stanza (query jab
ber:iq:version) [to=focus@auth.mydomain.net/focus12759191154,from=jitsi-videobridge.myclo
udvip.net,id=WJBw4-50,type=result,]
Jicofo 2018-10-05 02:16:30.826 INFO: [41] org.jitsi.jicofo.BridgeSelector.addJvbAddress().2
15 Added videobridge: jitsi-videobridge.mydomain.net v: IQ Stanza (query jabber:iq:versio
n) [to=focus@auth.mydomain.net/focus12759191154,from=jitsi-videobridge.mydomain.net,id=
WJBw4-50,type=result,]
Jicofo 2018-10-05 02:16:30.826 WARNING: [41] org.jitsi.jicofo.BridgeSelector.addJvbAddress(
).227 No pub-sub node mapped for jitsi-videobridge.mydomain.net
Jicofo 2018-10-05 02:16:30.829 INFO: [58] org.jitsi.jicofo.JvbDoctor.log() Scheduled health
-check task for: jitsi-videobridge.mydomain.net

**Comment by inglesuniversal** [comment]
the above logs is what I have available... I hope it helps you.

**Comment by damencho** [comment]
Did you install any webserver before that? Or it is using jetty from jvb?
If the later is the case delete jvb log, restart jvb and check for exception like 443 already taken or something like that?
