### ISSUE TITLE
New installation on ubuntu 16.04 and selfsigned certification but can't login the welcome page

### ISSUE THREAD

**Issue by cnscns** [jitsi/jitsi-meet#3513]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
When login to the web using https://192.168.x.x

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
You need toaddan exception in your browser, there is usually an “advanced” button to do so.
