### ISSUE TITLE
Building Framework with Xcode 10 doesnot work

### ISSUE THREAD

**Issue by Frindecent** [jitsi/jitsi-meet#3514]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

**## Description**
 I have been following the tutorial
https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md
To build jitsi meet.

Installed all dependencies and pods etc.

When i run this command 
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

It says archive succeeded but the framework is not present in ios/sdk folder

The only framework i was able to find was from derived folders but it was empty with no header file in framework

Please note that i have been building this earlier with no issues. I have faced this issue since xcode update to 10.0 while adding support for ios12

**## Current behavior**

Does not generate jitsimeet.framework 
cannot get the framework target to generate a proper archive. Therefore, IOS12 remains unsupported.

## Steps to reproduce
Mentioned Under Description.

**##Extra** 

Seems to be bug in Xcode10 , however , i have tried Xcode 10.1 beta and issue is still there. Which means we will not be able to support ios12.

----------------
tried to do it from xcode9 , however ios12 architecture remains supported. after adding arm64e as arm64 is allready there , still there is error

 The generated framework gave error in Xcode.
"Missing Required architecture file arm64 in jitsimeet.framework/jitsimeet
clang : error : linker command failed with exit code 1

----------------
Didnot changed anything in jitsi react and then tried with original code , was able to find one generated framework in dervied folder which again gave the same error  :  
"Missing Required architecture file arm64 in jitsimeet.framework/jitsimeet
clang : error : linker command failed with exit code 1

**##Suggestion**

When i was checking Xcodebuild generated logs , at the end it was
cd ios/sdk
Touch -c /path/to/dervied/folder/containing/jitsi/framework 

However while checking locally this /path/to/dervied/folder/containing/jitsi/framework folder was never present. Rechecked , while XcodeBuild was working , this folder was there initially however halfway during build it was deleted , There i think jitsiframework requires some edits and modifications to be made in order to support ios12 and xcode 10+

**Comment by Frindecent** [comment]
Hi there,

Writing my current workaround to this solution for Xcode 10.
Make sure you have emptied your derived data folder in order to avoid confusion.

After following the documentation and running command 

xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

When it says archive succeeded. 
Go to derived data folder, then open jitsi-meet-xyz folder
follow the path
Build/intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphonesimulator/JitsiMeet.Framework 

Copy this framework to your app.

The current binary should work with simulator. However it would give 
architecture error for device.

if on device i replaced it with this binary. 
[https://github.com/jitsi/jitsi-meet/files/2440426/JitsiMeet_For_Device.zip](url)

And i was able to build it for ios12 on xcode10

**Comment by saghul** [comment]
Here is what worked for me, using Xcode:

1) Select the JitsiMeet target
2) Select Generic iOS device
3) Click in the target, edit the scheme and choose the Release build configuration
4) Hit build
5) Goto sdk -> Products -> JitsiMeet.framework, right click: show in Finder

The resulting binary has both arm architectures.

**Comment by Frindecent** [comment]
Yup thank you ,
Building framework with jitsi-meet scheme also resolved the issue which had proper binaries.
and the method you have mentioned also does work.

**Comment by saghul** [comment]
I'm closing this since there is nothing we can act on other than providing workarounds.

**Comment by theomobile** [comment]
> Here is what worked for me, using Xcode:
> 
> 1. Select the JitsiMeet target
> 2. Select Generic iOS device
> 3. Click in the target, edit the scheme and choose the Release build configuration
> 4. Hit build
> 5. Goto sdk -> Products -> JitsiMeet.framework, right click: show in Finder
> 
> The resulting binary has both arm architectures.

Unfortunately not working for me, still "Undefined symbols for architecture x86_64" running on the simulator, xcode 10.1
