### ISSUE TITLE
ios Picture-in-Picture

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-meet#3515]
Hi,
I've built jitsi for ios and I don't see the picture in picture mode.
do I have to enable anything?
Thank you very much
Angelo

**Comment by saghul** [comment]
There is no picture in picture mode *per se* on iOS. There is something, but it's not as flexible as Android's. You can't just turn a regular view into pip mode.

So, we have a solution for it, check the example-pip application in the Xcode project. It requires some extra setup by the host application, but it can work.

**Comment by saghul** [comment]
I should clarify that it will only work for your app. That is, you won't have PiP over any application. This is a limitation of what we can currently do on iOS.

**Comment by manang** [comment]
thank you very much!

**Comment by Aizaz-Abbasi** [comment]
@saghul  Hi when I dismiss the view picture in picture hides and its also not opening call view when click on notification.
