### ISSUE TITLE
Error Build App on React-Native Android

### ISSUE THREAD

**Issue by PaijoRX** [jitsi/jitsi-meet#3516]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I'm trying to create jitsi meet on react-native. when compile the code using this comment `cd android && ./gradlew clean && cd .. && react-native run-android`, I got red error like below.

## Current behavior
Got red error

![screenshot_1538868681](https://user-images.githubusercontent.com/5009491/46576730-a6f74f80-c9fb-11e8-87fa-c4e7e0fb2a74.png)

<img width="699" alt="screen shot 2018-10-07 at 6 37 39 am" src="https://user-images.githubusercontent.com/5009491/46576780-8e3b6980-c9fc-11e8-8af7-f813032d01de.png">

## Expected Behavior
Application running properly

## Possible Solution
---

## Steps to reproduce
---

# Environment details
```
package.json

{
  "name": "DigitalCustomerService",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.2",
    "react-native-jitsi-meet": "^1.0.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by saghul** [comment]
We are not the authors of `"eact-native-jitsi-meet`. I don't know how they package Jitsi Meet, but there might be some problem there. Please ask the authors for support.

**Comment by netstairs** [comment]
we had the same experience.  Is there a more stable version?  How can we edit and compile revised codes?

**Comment by saghul** [comment]
@netstairs That's an unofficial plugin which you got from https://github.com/skrafft/react-native-jitsi-meet

You should ask them.
