### ISSUE TITLE
web server in jitsi meet

### ISSUE THREAD

**Issue by nanu1995** [jitsi/jitsi-meet#3517]
guys i am new to jitsi 
i am intregating the chat page of jitsi meet with a blank webpage of our company website but is unable to do anything 
are there any coding required for the wb page to integrate jitsi meet 
or there must be any specific name of web page please help

**Comment by saghul** [comment]
Please post such questions on our community forum: https://community.jitsi.org/ - We keep this issue tracker for specific bugs.
