### ISSUE TITLE
使用npm install 编译出现如下问题

### ISSUE THREAD

**Issue by 365323507** [jitsi/jitsi-meet#3524]
Unhandled rejection Error: Command failed: C:\Program Files\Git\cmd\git.EXE subm
odule update -q --init --recursive
warning: templates not found in C:\Users\ADMINI~1\AppData\Local\Temp\pacote-git-
template-tmp\git-clone-ee044b0e
fatal: cannot create directory at 'Examples/SDWebImage TV Demo/Assets.xcassets/A
pp Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Back.imagestac
klayer/Content.imageset': Filename too long
Unable to checkout 'ad9f1a24360b2c7581f136e3bd987ff700862ce7' in submodule path
'ios/Vendor/SDWebImage'

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by saghul** [comment]
We don't support building on Windows, please use GNU/Linux or macOS.
