### ISSUE TITLE
How to install an earlier version of Jitsi-Meet?

### ISSUE THREAD

**Issue by schub91** [jitsi/jitsi-meet#3526]
Friends!

Hello, 
I need help to do the full installation of Jitsi-Meet but of the 2866 version, I need to know if there is any tutorial on how to install a specific version of Jitsi or if you could provide one to perform this action.

**Comment by damencho** [comment]
Yep, as Saul said we are interested why? But here is a possible solution:
https://community.jitsi.org/t/jitsi-meet-not-work-on-aws-anymore/15251/2?u=damencho

And please use the community forum before opening new issues.
