### ISSUE TITLE
muc-occupant-left not trigger 

### ISSUE THREAD

**Issue by pekubu** [jitsi/jitsi-meet#3527]
I created a module to receive events as shown below, but only muc-room-destroyed is displayed.
How to fix it, 
```
module:hook("muc-occupant-joined", function(event)
    module:log("info", "muc-occupant-joined");
end, 10)

module:hook("muc-occupant-left", function(event)
    module:log("info", "muc-occupant-left");
end, 10)

module:hook("muc-room-destroyed", function(event)
    module:log("info", "muc-room-destroyed");
end)
```

My config 
```
Component "conference.example.com" "muc"
    storage = "null"
    modules_enabled = { "test" }
    muc_room_default_persistent = true

```

**Comment by damencho** [comment]
I think some of these are only available when using prosody trunk.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
