### ISSUE TITLE
User is having connectivity issues - Grey video

### ISSUE THREAD

**Issue by SeveHo** [jitsi/jitsi-meet#3528]
## Description
We have recently faced the issue that the video turns grey with the error message *User is having connectivity issues* after some time and does not turn back to color mode even though the network seems to be fine and the video quality is perfect (but grey). This occurs in every p2p session but also sometimes in multi user mode.

We have also recognized that when the video stays grey in a p2p session and a third user joins the colored mode is back for all of the users. After the third users left the guy video is back immediately.

I've seen some discussions about this now but there are no ideas from the community on how to fix this yet (see: https://community.jitsi.org/t/user-is-having-connectivity-issues/15278).

Does someone of the devs have an idea on how to fix this?

## Expected Behavior
Normal colored video when network is fine.

## Possible Solution
Remove grey colored video on low bandwidth (preferred solution) or fix connectivity check so that the video turns back to colored mode when bandwidth is good enough.

## Steps to reproduce
Open a conference on an environment with the latest stable packages. You will see the issue after a bit.

# Environment details
- jitsi-videobridge: 1087-1
- jicofo: 1.0-437-1
- jitsi-meet-web: 1.0.3036-1

**Comment by saghul** [comment]
Do you get anything in the JS logs when this starts to happen?

**Comment by SeveHo** [comment]
The JS log looks like this when it happens: 
![bildschirmfoto 2018-10-11 um 11 57 43](https://user-images.githubusercontent.com/20375523/46796575-4fcfe280-cd4d-11e8-9086-a4d394501974.png)

**Comment by saghul** [comment]
Those logs are not useful, alas. Do you experience the same problem on meet.jit.si ? Any chance your server can be underdimensioned?

**Comment by SeveHo** [comment]
No the server is fine. CPU load at 20% max. RAM and Storage are fine as well. Same on meet.jit.si

**Comment by pdarcos** [comment]
I can confirm I also see this behavior quite often lately

**Comment by paweldomas** [comment]
I suspect that there can be a bug where in p2p mode we have two media stream for each video: one p2p and one jvb. When the jvb video is suspended it gets "frozen" and by mistake the app looks at this status instead of unfrozen video's (the p2p one would be unfrozen I guess). It would not explain why this could happen in non-p2p conference. Does it happen only in a p2p conference ?

**Comment by havid0707** [comment]
I also encountered this problem, basically reproduce every time in the case of P2p

**Comment by havid0707** [comment]
@saghul NO js error/warning log on console and backend.
meet.jit.si seems work well, my install component is:
Got xmpp version: Prosody(0.9.10,Linux)
Got focus version: JiCoFo(1.0.1.0-438,Linux)
Got videobridge version: JVB(0.1.1089,Linux)

The version of Jitsi meet is older

**Comment by havid0707** [comment]
Console Log for Caller / Callee
[callee.log](https://github.com/jitsi/jitsi-meet/files/2472209/callee.log)
[caller.log](https://github.com/jitsi/jitsi-meet/files/2472210/caller.log)

**Comment by AdilHoumadi** [comment]
We are experiencing the same issue here!

**Comment by pdarcos** [comment]
The bug I've observed may be related to this issue since I get a lot of connectivity issues messages even when both clients are on same LAN. I also get the grey screen most of the time too.
Logs attached

[Chrome_69.0.3497.100_high_sierra.log](https://github.com/jitsi/jitsi-meet/files/2474066/Chrome_69.0.3497.100_high_sierra.log)
[Chrome_69.0.3497.100_ubuntu_18.04.1.log](https://github.com/jitsi/jitsi-meet/files/2474067/Chrome_69.0.3497.100_ubuntu_18.04.1.log)

**Comment by pdarcos** [comment]
It happens pretty much every time.

[chrome_high_sierra.log](https://github.com/jitsi/jitsi-meet/files/2475653/chrome_high_sierra.log)

**Comment by paweldomas** [comment]
I suspect that when .play() exception happens parts of the app are not initialised correctly

**Comment by paweldomas** [comment]
but there's also this:
`Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackAdded>:  TPC[1,p2p:false] remote track added: 3844631a-735e-4aa8-89b6-e778f2e38cb8-6 video
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackAdded>:  TPC[1,p2p:false] associated ssrc 92ec9eb4 2557751743
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackAdded>:  TPC[1,p2p:false] remote track added: 3844631a-735e-4aa8-89b6-e778f2e38cb8-6 video
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._remoteTrackAdded>:  TPC[1,p2p:false] associated ssrc 92ec9eb4 2557751743
Logger.js:125 [modules/RTC/TraceablePeerConnection.js] <r._createRemoteTrack>:  TPC[1,p2p:false] overwriting remote track! RemoteTrack[92ec9eb4, video, p2p: false] 92ec9eb4 video`

**Comment by paweldomas** [comment]
I think it's the remote track overwrite error. For some reason the peerconnection started firing "remote stream added" event twice and this confuses the app.

**Comment by pdarcos** [comment]
I agree @paweldomas 

That remote track overwrite error shows up a lot and confuses everything

**Comment by paweldomas** [comment]
https://github.com/jitsi/lib-jitsi-meet/pull/827

**Comment by paweldomas** [comment]
https://github.com/jitsi/jitsi-meet/pull/3540

**Comment by damencho** [comment]
@SeveHo @pdarcos @havid0707 can you update to jitsi-meet from unstable build 3378 it should contain the fix.

**Comment by SeveHo** [comment]
I'll try it out. Thank you @paweldomas @damencho!
