### ISSUE TITLE
Hot to join an existing-  invitation VC? 

### ISSUE THREAD

**Issue by Saeidk0** [jitsi/jitsi-meet#3530]
Hello,
How to join an existing VC with Jitsi? I have an invitation to a call (with a password) I can't join the call with "START A CALL" option.

**Comment by damencho** [comment]
What happens when you click the link to join the call? 

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by Saeidk0** [comment]
Sure- will do. 
I click on START A CALL, it start my camera but it does not connect to the VC organizer (the invitation is something like this:  12345678@xxx.xxx.xxx.xxx -IP address, and it does not prompt to enter the password (which is provide by the organizer)

**Comment by damencho** [comment]
Can you show the invitation? 
It should have a link like https://meet.jit.si/someroomname or a phone number to call. This invitation something@ip-address doesn't seem right.

**Comment by Saeidk0** [comment]
it is like: 1234567891@video.canada.ca

**Comment by Saeidk0** [comment]
I tried with FQDN and IP address..
