### ISSUE TITLE
latest unstable drops clients off around 30 seconds

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3535]
Latest unstable debian packages on debian 9.

Both sides are running latest chrome. One is on win 10, the other on ubuntu.

The videoconf starts normally enough but after 30 seconds (approx) the win 10 client gets kicked off.
I've experimented with many other clients and they all seem to get kicked off automatically.

Logs attached

Cheers

[Chrome_69.0.3497.100_windows10pro.log](https://github.com/jitsi/jitsi-meet/files/2474060/Chrome_69.0.3497.100_windows10pro.log)
[Chrome_69.0.3497.100_ubuntu_18.04.1.log](https://github.com/jitsi/jitsi-meet/files/2474061/Chrome_69.0.3497.100_ubuntu_18.04.1.log)

**Comment by pdarcos** [comment]
And here are trimmed down jicofo and jvb logs
Hope this helps

[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2474091/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2474092/jvb.log)

**Comment by damencho** [comment]
When you were deploying did you follow:https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration ?
Seems like no connection is possible to the bridge.

**Comment by pdarcos** [comment]
Thanks @damencho 

Yeah it seems some of the config items were lost on the upgrade.
After adding local and public address again the connection no longer drops :)

But I'm still getting the constant "connectivity issues" and grey screen even when both clients are on same LAN.

JS console logs attached.

[chrome_high_sierra.log](https://github.com/jitsi/jitsi-meet/files/2475652/chrome_high_sierra.log)
