### ISSUE TITLE
Recording voice problems

### ISSUE THREAD

**Issue by zhanghuiDev** [jitsi/jitsi-meet#3537]
After the meeting, the iOS client could not record the voice.

**Comment by saghul** [comment]
How are you recording the voice? Can you please be more specific?

**Comment by zhanghuiDev** [comment]
As long as the conference is opened, you cannot record it. You must restart APP.

NSDictionary *settings=[NSDictionary dictionaryWithObjectsAndKeys:
                            [NSNumber numberWithFloat:8000],AVSampleRateKey,
                            [NSNumber numberWithInt:kAudioFormatLinearPCM],AVFormatIDKey,
                            [NSNumber numberWithInt:1],AVNumberOfChannelsKey,
                            [NSNumber numberWithInt:16],AVLinearPCMBitDepthKey,
                            [NSNumber numberWithBool:NO],AVLinearPCMIsBigEndianKey,
                            [NSNumber numberWithBool:NO],AVLinearPCMIsFloatKey,
                            nil];
    
    [[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryPlayAndRecord error: nil];
    [[AVAudioSession sharedInstance] setActive:YES error:nil];

    NSURL *url = [NSURL fileURLWithPath:[FileInfo getUUIDFileName:@"wav"]];
    pathURL = url;
    
    NSError *error;
    audioRecorder = [[AVAudioRecorder alloc] initWithURL:pathURL settings:settings error:&error];
    audioRecorder.delegate = self;
    
    peakTimer = [NSTimer scheduledTimerWithTimeInterval:0.01 target:self selector:@selector(updatePeak:) userInfo:nil repeats:YES];
    [peakTimer fire];
    
    [audioRecorder prepareToRecord];
    [audioRecorder setMeteringEnabled:YES];
    [audioRecorder peakPowerForChannel:0];
    [audioRecorder record];

**Comment by saghul** [comment]
Why can't you? You get an error? What error? At any rate, this is not an issue we can solve since you are modifying the code in ways unknown to us.

Throughout the conference the AVAudioSession may change mode and category, you can't just do your thing and assume the rest of the code will remain unaffected.

**Comment by echooooooo** [comment]
> Why can't you? You get an error? What error? At any rate, this is not an issue we can solve since you are modifying the code in ways unknown to us.
> 
> Throughout the conference the AVAudioSession may change mode and category, you can't just do your thing and assume the rest of the code will remain unaffected.

I have the same problem, when I end the video conference, set [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord
                                            Error:nil], try recording, but AVAudioSession will automatically switch to AVAudioSessionCategorySoloAmbient mode.

**Comment by echooooooo** [comment]
The problem is that when conference ends , I set AVAudioSessionCategoryPlayAndRecord again, my app will be changed to AVAudioSessionCategorySoloAmbient again. The conference is not modifying my app again？
[[NSNotificationCenter defaultCenter]
             addObserver:self
                Selector:@selector(routeChanged:)
                    Name:AVAudioSessionRouteChangeNotification
                  Object:nil] 
it seems to have not been released

**Comment by echooooooo** [comment]
> We set the mode to `AVAudioSessionCategorySoloAmbient` when the conference ends: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/AudioMode.m#L125
> 
> The mic is released otherwise you'd see the red bar showing "recording" as this is drawn by iOS itself.

The problem is that when conference ends , I set AVAudioSessionCategoryPlayAndRecord again, my app will be changed to AVAudioSessionCategorySoloAmbient again. The conference is not modifying my app again？
[[NSNotificationCenter defaultCenter]
             addObserver:self
                Selector:@selector(routeChanged:)
                    Name:AVAudioSessionRouteChangeNotification
                  Object:nil]
it seems to have not been released

**Comment by saghul** [comment]
It's your app, so I don't really know what you are doing. What I do know for sure is that we release the mic.

> The problem is that when conference ends , I set AVAudioSessionCategoryPlayAndRecord again, my app will be changed to AVAudioSessionCategorySoloAmbient again. The conference is not modifying my app again？

Of course we will change the mode again, with the next conference. The mode is changes after the conference ends, but it may take a bit to kick in, I think you are calling it too early, maybe wait a couple of seconds.

> [[NSNotificationCenter defaultCenter]
> addObserver:self
> Selector:@selector(routeChanged:)
> Name:AVAudioSessionRouteChangeNotification
> Object:nil]
> it seems to have not been released

I don't know what this code has to do with anything.

**Comment by zhanghuiDev** [comment]
@echooooooo Hello, can you solve this problem?

**Comment by WSX1994** [comment]
@echooooooo @zhanghuiDev  I have the same problem, can you solve this problem?

**Comment by zhanghuiDev** [comment]
@saghul Hello, have you tested this situation?

**Comment by saghul** [comment]
No I haven’t. I don’t really know what you are trying to do. Unless I can see the full code I have no idea.

**Comment by WSX1994** [comment]
@saghul  When we close the page of jitsi-meet-View, the recording of jitsi-meet-View doesn't seem to be closed. We can't reproduce the recording on other pages. Are you sure that when we close the page of jitsi-meet-View, the recording of jitsi-meet-View is stopped?

**Comment by WSX1994** [comment]
@saghul Was this method [player stop] called when the page of jitsi-meet-View was closed?

**Comment by zhanghuiDev** [comment]
@saghul  
Thank you for your reply. the situation is like this, After the iOS client integrates JitsiMeet.framework, first open the conference, and then click the hang up button to end the conference, the APP uses AVAudioRecorder to try to record the voice, but can not receive the audio data, you must restart the APP to record the voice. The initial suspicion was because the conference was hung up and the microphone was not completely released.

**Comment by saghul** [comment]
@WSX1994 Well, of course it won't. You need to stop the conference. Call loadURL with a NULL URL and this will cause the conference to stop. We don't use AVPlayer, so there no player to stop, it all happens at a much lower level.

**Comment by saghul** [comment]
@zhanghuiDev I can tell you that suspicion is wrong. iOS draws the red bar when the mic is recording. If you don't see it, it's not recording.

The problem I see is that our SDK enforces the AVAudioSession mode: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/AudioMode.m#L73 so when you change it the SDK will see this change and will want to revert back. You may need to modify that part of the code I think. You probably want to ignore the changes when the mode is the default.

**Comment by WSX1994** [comment]
@saghul OK, thank you,i will try it

**Comment by Aizaz-Abbasi** [comment]
Hi, I have the same issue after call hangup when I record voice its not recording. Then I go to back screen A and Combe back to B then recording works fine.
