### ISSUE TITLE
Couldn't see anybody on Firefox but it worked in Chrome

### ISSUE THREAD

**Issue by simivar** [jitsi/jitsi-meet#3547]
## Description
I've created a new room where 4 people joined. When I joined from Firefox I could see* only myself on the call. After I switched to Chrome or to Jitsi iOS App I could see that people are already there and they are speaking.

* by "see" I don't mean their video. I didn't saw that anyone joined the room at all. It was like I was only person in the room.

## Current behavior
Couldn't see/hear people in the room on Firefox and by "see" I don't mean their video. I didn't saw that anyone joined the room at all. It was like I was only person in the room.

## Expected Behavior
See that other people are in the room with you

## Possible Solution
---

## Steps to reproduce
1. Turn on Firefox 62.0.3 (64-bit)
2. Go to https://meet.jit.si/YamsCallOrganizacyjnyDrugiWtorek1610|2115 
3. Join from other device.
4. You still see that you are alone in the room.

# Environment details
Windows 10
Firefox 62.0.3 (64 bit)
Chrome 69.0.3497.100 (64 bit)

**Comment by damencho** [comment]
Thanks for the report, the problem comes from '|' char and maybe some bug in the code we will investigate it.
So chrome uses this to send bosh messages: https://meet.jit.si/http-bind?room=yamscallorganizacyjnydrugiwtorek1610%7c2115
While Firefox uses this: https://meet.jit.si/http-bind?room=yamscallorganizacyjnydrugiwtorek1610|2115
Which are different rooms at the end.

**Comment by miwojc** [comment]
we just had a video conference, 6 people, we could hear audio fine but with video it was funny, some of us could see some of us, but not everyone. so for example person 1 could see person 2 and person 3, but person 3 could only see person 5, and person 6 didn't see anyone. really strange. but cannot use it reliably so will be switching to something else. which is shame...

**Comment by simivar** [comment]
@damencho will you investigate it? I see that @stale has marked it as "wontfix".

**Comment by damencho** [comment]
Yep, that is a bug and we should look at it at some point when priorities allow it.

**Comment by damencho** [comment]
Any help is welcome.

**Comment by naslave** [comment]
I have the same problem but on Chrome (Mac OS), when I join a meeting I can see that other users are online, but I cant hear them and cant see them or their screenshare. I have also tried with Safari, but same problem here. The other users can talk and hear each other.
