### ISSUE TITLE
Users get kicked off the meeting when someone joins

### ISSUE THREAD

**Issue by DoFuckOff** [jitsi/jitsi-meet#3548]
Hi everyone,

this is my very first time linux and open source, so let me apologize in advance for my lack of knowledge.

I have installed jitsi meet on an Ubuntu server and I'm able to reach the web interface and start a meeting, but whenever another user connects, we both get kicked out of the meeting and get into a log in/log off loop.

Is there something I'm missing? I followed the quick-install guide...

Thanks in advance!

**Comment by saghul** [comment]
Interesting choice for a username. Please use our community forum for such questions: https://community.jitsi.org/
