### ISSUE TITLE
Screen sharing javascript interference

### ISSUE THREAD

**Issue by IppyD** [jitsi/jitsi-meet#3558]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Hi maintainers

Thank you for an awesome open-source communication tool!

This week, whilst delivering user training for a Drupal 8 website, I encountered some interesting behaviour whereby certain JS-based functions appeared to erratically fail or be interfered with. Killing the screen sharing returned the site to normal/expected behaviour.

I've searched the issue queue and not found anything similar, so it may be such an edge-case that its not worth time investigating, on the other hand I thought you might like to know and also in case anyone else experiences similar behaviour as its always nice to know you are not alone!

## Current behavior
---
Examples of interference observed - elements vanish (drag handles), elements fail to function as expected (entity browser cannot include selected images/files). This seems erratic/inconsistent. 

## Expected Behavior
---
Not to interfere with other JS

## Possible Solution
---
??

## Steps to reproduce
---
Share screen, choose to share application window (of Firefox as I needed to be logged in with different roles in different browsers) try using drag handles (they might vanish) or Drupal entity browser to upload or reference files.  

NB I tried to reproduce this error once myself today - I thought I may capture some useful data from the console -  and couldn't. Hmm.. 

# Environment details
---
Using meet.jit.si with Chrome Version 68.0.3440.84 (Official Build) (64-bit), with the Jitsi Meeting extension (0.2.8.14) on Ubuntu 16.04.5 LTS (Mate desktop environment)

**Comment by damencho** [comment]
Once screensharing had been started there is nothing we can do, I mean that everything is browser implemented, so if you find some problem/bug scenario, you rather report it to chromium issues or bugzilla for Firefox.
