### ISSUE TITLE
Can't compile iOS app

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3563]
Hi guys,

Running HighSierra with Node 10.12.0 and npm 6.4.1

I used to be able to compile the iOS app in the past.

But now when I run pod install I get the following error:

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FUsers%2Fchewie%2FDocuments%2FDev%2Fjitsi-meet%2Fnode_modules%2Freact-native%2Fthird-party-podspecs%2FDoubleConversion.podspec&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new


Anyone else having this issue? Do I have to downgrade node or npm?

Cheers

**Comment by saghul** [comment]
GitHub has been semi down today, I wonder if that is the problem. I have never seen this before.

**Comment by pdarcos** [comment]
Could be.
I've tried fixing the pod install error by following advice from here https://stackoverflow.com/questions/44396215/cocoapods-not-working-in-macos-high-sierra and here https://github.com/CocoaPods/CocoaPods/issues/7294 but nothing resolves it.

Not sure what else I could do to help debug this

**Comment by pdarcos** [comment]
I've actually opened a new ticket about this on cocoapods repo https://github.com/CocoaPods/CocoaPods/issues/8217

**Comment by privum** [comment]
Nevermind. It was a corrupt npm install that was causing this.
I had to remove the nodes folder and run npm install again.
Now the pods install OK.

Go ahead and close please

Thanks
