### ISSUE TITLE
recording failed to start

### ISSUE THREAD

**Issue by rahultyagi12** [jitsi/jitsi-meet#3566]
we have integrated dropbox with jitsimeet and jicofo. But after clicking on start record a pop up comes and show recording failded. please try again. no error is showing on console.

**Comment by aaronkvanmeerten** [comment]
For this kind of things please first post to our community forums (https://community.jitsi.org).  In this case you are probably missing the Jibri recorder component required for recordings.  This is run often on a separate server from the rest of the jitsi meet stack.
