### ISSUE TITLE
Red screen when i'm trying to run my demo iOS app 

### ISSUE THREAD

**Issue by hemantkadam** [jitsi/jitsi-meet#3567]
Hello guys, 
I'm trying to run my demo iOS app using JitsiMeet framework. I've followed all the instruction mentioned [here](https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md) for iOS and was able to build JitsiMeet.framework for simulator and device successfully without React Native CLI and only using Xcode 10 with few mentioned terminal commands. 
However, i was not able to build WebRTC.framework for device and the one present is mentioned path is for simulator.

**Need help in:**
**1. Get WebRTC.framework for device**

**2. As it is working for simulator i tried running on simulator but I see red screen with errors. How to fix it? Please help.**
![simulator screen shot - iphone 6 - 2018-10-24 at 16 23 56](https://user-images.githubusercontent.com/85816/47426486-f9ca5880-d7aa-11e8-8bc7-403dec99a8ea.png)

**Comment by hemantkadam** [comment]
> @hemantkadam Any updates about this issue? I am also facing the same issue

Nope :(

**Comment by saghul** [comment]
WebRTC.framework is built for all architectures, including simulators. It's in node_modules/react-native-webrtc/ios

As for the red screen, if you did a Dubug build, the bundle is not included. Make a release build and you should be good to go.

**Comment by tj0xin** [comment]
Hi @saghul 

I am having the same problem with Xcode 12, all the requirements are latest (npm, Node) it used to work earlier, i think i messed up something. 

On the physical iphone, it shows no bundle URL present. same as what the OP has mentioned. 

Could you please guide? i've spent days trying all the mentioned fixes on github and Jitsi Meet forums.

Any help will be very much appreciated. 

Thanks

**Comment by tj0xin** [comment]
> Hi @saghul
> 
> I am having the same problem with Xcode 12, all the requirements are latest (npm, Node) it used to work earlier, i think i messed up something.
> 
> On the physical iphone, it shows no bundle URL present. same as what the OP has mentioned.
> 
> Could you please guide? i've spent days trying all the mentioned fixes on github and Jitsi Meet forums.
> 
> Any help will be very much appreciated.
> 
> Thanks

Solved! terminal into root project folder and: 

node node_modules/react-native/local-cli/cli.js start --reset-cache

keep the terminal running and click the play button
