### ISSUE TITLE
black screen for more than two people at a time Jitsi Meet quick install

### ISSUE THREAD

**Issue by bharatbhamare** [jitsi/jitsi-meet#3568]
via jetty
here is the file
/etc/jitsi/videobrige/sip-commuicator.properties

org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.otcstaging.triarqclouds.com/.*
org.jitsi.videobridge.rest.jetty.host=::
org.jitsi.videobridge.rest.jetty.port=443
org.jitsi.videobridge.rest.jetty.ProxyServlet.hostHeader=otcstaging.triarqclouds.com
org.jitsi.videobridge.rest.jetty.ProxyServlet.pathSpec=/http-bind
org.jitsi.videobridge.rest.jetty.ProxyServlet.proxyTo=http://localhost:5280/http-bind
org.jitsi.videobridge.rest.jetty.ResourceHandler.resourceBase=/usr/share/jitsi-meet
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./config.js=/etc/jitsi/meet/otcstaging.triarqclouds.com-config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./interface_config.js=/usr/share/jitsi-meet/interface_config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./logging_config.js=/usr/share/jitsi-meet/logging_config.js
org.jitsi.videobridge.rest.jetty.RewriteHandler.regex=^/([a-zA-Z0-9]+)$
org.jitsi.videobridge.rest.jetty.RewriteHandler.replacement=/
org.jitsi.videobridge.rest.jetty.SSIResourceHandler.paths=/
org.jitsi.videobridge.rest.jetty.tls.port=443
org.jitsi.videobridge.TCP_HARVESTER_PORT=443
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePath=/etc/jitsi/videobridge/otcstaging.triarqclouds.com.jks
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePassword=changeit
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=10.91.182.140
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=160.109.235.148

**Comment by damencho** [comment]
Testing your deployment seems like jicofo is having issues connecting to the xmpp server. Check jicofo logs, do you see errors?
How did you install? What os and version?

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by bharatbhamare** [comment]
hello ,
os and version is ubuntu-18-04-1-lts

[jicofoLog.txt](https://github.com/jitsi/jitsi-meet/files/2513793/jicofoLog.txt)
[JvbLog.txt](https://github.com/jitsi/jitsi-meet/files/2513794/JvbLog.txt)
[Certificate-config.js.txt](https://github.com/jitsi/jitsi-meet/files/2513796/Certificate-config.js.txt)
[sip-communicatorProperties(videobridge).txt](https://github.com/jitsi/jitsi-meet/files/2513797/sip-communicatorProperties.videobridge.txt)

**Comment by damencho** [comment]
You have problems with the locally trusted certificates and the certs from prosody. How did you install jitsi-meet? What is the java version you use?
Quick fix is to add `org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true` in /etc/jitsi/jicofo/sipc-ommunicator.properties and restart jicofo.

**Comment by bharatbhamare** [comment]
hii,
thanks for reply.
it is working now ,
I have changed java version oraclejdk to openjdk8
thanks,
Bharat
