### ISSUE TITLE
Custom URL for iOS app?

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3569]
Hi,

In the past the meet.jit.si URL was hardcoded in react/features/app/components/AbstractApp.js and all I had to do to get it to work with our self deployed server was change the URL.

I've noticed that now you just have string there https://github.com/jitsi/jitsi-meet/blob/master/react/features/app/components/AbstractApp.js#L21

Is that where I set my own URL or has the location changed to some resource or config file?

Thanks

**Comment by damencho** [comment]
Is this what you are looking for: https://github.com/jitsi/jitsi-meet/blob/3bfab7718f9dbdd48aa5b67c37bfa11eccfc0086/react/features/base/settings/constants.js#L6

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by pdarcos** [comment]
So that's where it went to. Thanks guys!
BTW, I know this isn't a bug but I couldn't find this info in the community forum which is why I had to open a ticket. Perhaps this info could be centralised and updated in one doc?

Cheers
