### ISSUE TITLE
URL Params are not taken into account

### ISSUE THREAD

**Issue by edi9999** [jitsi/jitsi-meet#3571]
## Description
---

When I go to : 

https://meet.jit.si/testResolution123#config.resolution=360&config.constraints.video.height.ideal=360&config.constraints.video.height.max=360

in 3 different browsers simultanously,

I would expect that the resolution of the video is 360px 

However, when I click on "Call Quality", I still see "high definition".

I have found this "feature of url params" in the following comment : https://github.com/jitsi/jitsi-meet/issues/2596#issuecomment-383915759

## Current behavior
---

The urlparams are not taken into acconut

## Expected Behavior
---

The urlparams are taken into acconut

## Possible Solution
---

## Steps to reproduce
---

Described above

# Environment details
---

Linux, Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by saghul** [comment]
At the moment, those 2 things trigger different behavior: the URL parameters will define how your video is sent, whereas the call quality screen defines how the remote video will be received.

**Comment by paweldomas** [comment]
I think there might be some problem with the config.resolution parameter. It doesn't seem to be taken into account anymore (at least not on Chrome).

**Comment by saghul** [comment]
That’s the expected behavior. The resolution setting only affects devices not using the “new GUM flow”.

**Comment by edi9999** [comment]
Isn't there any option to send and receive only lower quality video ?

My CPUs are burning like hell when I open jitsi with 3 other persons, I would like to open jitsi with minimum overhead (without having to configure it each time, I open jitsi at least 10 times a day). What are my options ?

**Comment by paweldomas** [comment]
> That’s the expected behavior. The resolution setting only affects devices not using the “new GUM flow”.

Maybe need to update the docs in the config.js then

**Comment by edi9999** [comment]
This story should be kept open.

**Comment by edi9999** [comment]
This story should be kept open.

Having a stale bot is a very bad idea by the way.

This is the equivalent of having a person waiting for a lung be removed from a list of potential receivers just because they have waited for more than X months without complaining.

**Comment by saghul** [comment]
Hyperbole won't help getting this issue fixed.

As the one who suggested and added the stale bot, it's a great idea. You can disagree, but the people working on this project like it.

We get notifications too, so if something needs reopening, it will be reopened, don't worry.
