### ISSUE TITLE
Jitsi server configuration

### ISSUE THREAD

**Issue by naushrambo** [jitsi/jitsi-meet#3573]
This is not an issue. Need help or advice to configure jitsi server. I have a requirement of live streaming ( Not YouTube) . 1 live streaming consists of 80 participants . And there will be atleast 15 to 30 live streaming will run concurrently 6 times per month any day.
And also record the streams for later play.
Help me to configure my servers or create how many servers to achieve this scenario. 
I have Digital Ocean Account.

**Comment by damencho** [comment]
Do you want it to stream it to somewhere, like we stream to youtube? Or you use streaming like there will be one conference with 80 participants?

Why didn't you use the community forum, before opening an issue for your question?

**Comment by naushrambo** [comment]
Stream like there will be one conference with 80 participants. Like 1 trainer and 80 students. With recording.

Didn't aware about to post in which community forum.

**Comment by damencho** [comment]
When you try to create an issue there is a template that starts as:
```
Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
```

So, 80 participants are kind of too much if you don't configure lastN, where just the last number N of participants which were talking will have their video streamed to the other participants. 

If all videos are enabled with simulcast, in an ideal situation you will have 320 Mbit input/output to the server for the 80 people conference.  If there is no simulcast enabled (all participants with Firefox), the server ouput will be 25280 Mbit, basically not possible for one machine. 
We are working on adding big conferences, but this requires more infrastructure and a lot of jvb machines.

Will the participants will be participating in the conference? Like talking or video?

**Comment by naushrambo** [comment]
Scenario is,


There is 1 Trainer who will start conference and 80 participants all 80 participants will receive the audio and video of trainer, but the audio and video of all 80 participants will be disabled/muted.

Like happens in live streaming, but i cant use youtube.

________________________________
