### ISSUE TITLE
Jitsi Meet application crashes on Samsung devices with Exynos CPU after unmuting/switching the camera

### ISSUE THREAD

**Issue by MaksimHalavenchyk** [jitsi/jitsi-meet#3576]
## Current behavior
Jitsi Meet application crashes after unmuting/switching the camera

## Expected Behavior
The application doesn't crash

## Steps to reproduce
1. Open https://meet.jit.si/ in your browser
2. Start a new meeting by setting its name (e.g. crashtest) and clicking "Go" button
3. Install Jitsi Meet application (https://play.google.com/store/apps/details?id=org.jitsi.meet) on your Samsung device
4. Launch the application and join the meeting created in step 2 (crashtest) via "Enter room name" field
5. After joining, mute and unmute your camera or just switch it from frontal to main

## Video
https://screencast-o-matic.com/watch/cF60QvYAzl

## Logs
[Samsung S7 edge logs.txt](https://github.com/jitsi/jitsi-meet/files/2519839/Samsung.S7.edge.logs.txt)

## Environment details
Jitsi Meet application 1.20.111
Samsung Galaxy S7 edge (6.0.1), Samsung Galaxy J7 2017 (8.1.0), Samsung Galaxy S8 (8.0)
Not reproducible on LG Nexus 5X (8.1.0) and Xiaomi Redmi 5A (7.1.2)

**Comment by patidars** [comment]
is there any update on this issue. Getting crash on most of the Samsung devices.
Jitsi-Meet crashes when two or more participant join the conference and we toggle camera from Samsung device.
Thanks

**Comment by saghul** [comment]
I see this was reported to WebRTC, as the problem occurs in libwebrtc: https://bugs.chromium.org/p/webrtc/issues/detail?id=9797

Please follow-up there.
