### ISSUE TITLE
Enable compression on the CDN

### ISSUE THREAD

**Issue by prawnsalad** [jitsi/jitsi-meet#3579]
https://cdn.jitsi.net/meetjitsi_3083.1437/libs/app.bundle.min.js?v=3083.1437

This file for example is *huge*, almost 3mb and has obvious performance issues with it being so slow to load. With compression it would be ~720k.

**Comment by saghul** [comment]
Ping @aaronkvanmeerten

**Comment by saghul** [comment]
Ping @aaronkvanmeerten

**Comment by damencho** [comment]
I'm closing this as this is already enabled:

What I have in chrome - ~700KB: 
![image](https://user-images.githubusercontent.com/3263098/56912285-e1fbc600-6aa6-11e9-8003-8923bbabe2c4.png)

And here is the file saved on local disk, saved from the same location - ~2.7MB:
![image](https://user-images.githubusercontent.com/3263098/56912334-f63fc300-6aa6-11e9-8494-c1900a37c417.png)
