### ISSUE TITLE
Many p2p

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3581]
In order to reduce the server pressure, I consider room 3-6 people are also adopted p2p mode, how to configure?

**Comment by paweldomas** [comment]
Do you want a p2p between 3 people ? Like a full mesh ? That's not implemented yet, but doable. I'm not sure if we'd want that in master though.

**Comment by c526537207** [comment]
Yes, I'm thinking about that @paweldomas

**Comment by saghul** [comment]
I don't think the complexity is worth it here. The server load for a 3-6 person conference is not high, whereas the client load will be. Bandwidth estimation will also be poor since each peer connection will do its own.

While I don't have the final say, I don't see this happening.

**Comment by danielgimeno** [comment]
So, you saying is not possible to make an 3 people videoconference,  in P2P? I mean, my intention is to move the server to AWS, in Docker containers. You are saying that is not so big load in the server side. Can you tell me the cost KB/s for a single video stream?. Imagine you have  100 groups with three members, at the same time. I imagine the bill would be big. What do you think?

**Comment by danielgimeno** [comment]
Understood. Is not really so expensive. The thing is that you get that figure of 0.09 €/GB when you are having a consume above of 100TB, and that's a lot. Although I would like to have that problem, that means that my platform is completely successful. ;^)
If someone is interested in, 
https://aws.amazon.com/es/blogs/aws/aws-data-transfer-prices-reduced/

**Comment by pdarcos** [comment]
I'm also interested in this feature.
While I think 6 people in p2p is too much load client side, I think we should have the option to allow p2p for 3 participants and only move to the bridge when the 4th participant enters.

Is this possible at the moment?

Thanks

**Comment by damencho** [comment]
This is not possible. And I doubt we will consider adding it. The goal is to minimize the traffic and the load on participants PC and improve experience. Increasing the load and traffic will for sure make experience bad.
I agree with Pawel, that this will even not make to master if somebody creates a PR for it.

**Comment by pdarcos** [comment]
OK, I understand your reasoning.

Can you however point which part of the code we need to change for those of us that believe 3 people p2p conferences are desirable?

Thanks

**Comment by damencho** [comment]
Everything is in https://github.com/jitsi/lib-jitsi-meet. Check modules/xmpp/JingleSessionPC.js and JitsiConferenceEventManager.js. and JitsiConference.js. search isP2P.

**Comment by pdarcos** [comment]
Hi guys,

I wanted to start poking around at this now that I have some time.
Has anything changed in the last 1.5 years since this ticket was opened?
ie to increase the threshold from p2p to jvb from 2 to 3 participants is the logic still present in the 3 files you mentioned above or is there somewhere else I should look at?

Thanks

**Comment by platomedical** [comment]
@pdarcos - just wanted to check if you found any solution to this? Thanks.

**Comment by saghul** [comment]
No work has been done here that I'm aware of.
