### ISSUE TITLE
Network traffic problem ： 

### ISSUE THREAD

**Issue by pzqtinger** [jitsi/jitsi-meet#3582]
Hi  developer

Now the test, two PCs for audio and video communication, the server's data reception is twice as much as the sending, what is the problem here? Or is it a normal phenomenon? Please help analyze.

Thank you

![1540619965 1](https://user-images.githubusercontent.com/34857924/47633171-e7c02f80-db87-11e8-8cae-879c6dd0ca7f.jpg)

**Comment by pzqtinger** [comment]
Sorry , icon upload error, below is traffic data.。

![1540794928 1](https://user-images.githubusercontent.com/34857924/47633213-0a524880-db88-11e8-8a1e-4ec43f341e67.jpg)

**Comment by saghul** [comment]
It can be normal, yes. How many participants were there at the conference?

**Comment by pzqtinger** [comment]
Two people attended the conference.

For one question, the jitsi-meet configuration file allows you to modify the resolution. Where are the bit rates and frame rates configured?

**Comment by saghul** [comment]
There are many factors affecting the bitrate, including CPU load. So what you see it's certainly possible.

As for configuring the framerate, you can add it as a constraint here: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L103

**Comment by pzqtinger** [comment]
But config did not see the frame rate constraint of the video.

**Comment by pzqtinger** [comment]
But config did not see the frame rate constraint of the video.。Including maximum bitstream restriction
