### ISSUE TITLE
JVB service configuration

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3591]
When using private network server, only internal network card, when setting up jitsi, JVB service cannot be set up directly because there is no external network card, how should this situation be configured?

**Comment by damencho** [comment]
As described here: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
You must have an external address on which you will forward the ports to the jvb machine and in jvb config you need to describe the private and the public address.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
