### ISSUE TITLE
Can i use it in ionic ?

### ISSUE THREAD

**Issue by LuniChang** [jitsi/jitsi-meet#3592]
Both android and ios, i want to use js only in ionic .Can I just use the "lib-jitsi-meet.min.js"?

**Comment by saghul** [comment]
Not out of the box. AFAIK ionic runs on a UIWebVView on iOS, which doesn't support WebRTC. Even if you switch to WKWebView, which does have WebRTC, it only has H.264 support and no VP8.

You'll need to patch the environment so support for all WebRTC features is properly detected.
