### ISSUE TITLE
leaving conference manually with jitsi meet sdk for react native 

### ISSUE THREAD

**Issue by riobijanero** [jitsi/jitsi-meet#3595]
I noticed that the app crashes when I press the home button of the phone while I am in a meet conference and then open the app again.

## Current behavior

I get this Error: `'NSInvalidArgumentException', reason: 'Pushing the same view controller instance more than once is not supported`
I assume, this is because the conference was not left properly and the view controller was not popped.

Does anyone know about a way to leave the conference that I can manually invoke when the app goes to background?

---

## Possible Solution

I have added this code to the JitsiMeetNavigator.m and I call leaveConference() when the App goes to the background, but that doesn't fix it.

```
{
  dispatch_sync(dispatch_get_main_queue(), ^{
    RCTLogInfo(@"Conference left");
    UIViewController* rootViewController = [[[[UIApplication sharedApplication]delegate] window] rootViewController];
    UINavigationController *navigationController = (UINavigationController *) rootViewController;
    [navigationController popViewControllerAnimated:NO];
  });
}
```
---

## Steps to reproduce
1) start a meet conference with the sdk in react native.
2) press the home button while in the conference
3) open the app again
---

## Environment details 
iOS12
RN 0.57
node: 9.11.2

---

**Comment by saghul** [comment]
You can hangup / leave a conference by loading a `NULL` URL.

> I have added this code to the JitsiMeetNavigator.m and I call leaveConference() when the App goes to the background, but that doesn't fix it.

I assume that file and function relate to your code, since we have nothing of the sort.

The app will happily continue running in the background. Do you explicitly want to kill it? If so, load a `NULL` URL as I mentioned earlier.

**Comment by riobijanero** [comment]
Thank you saghul,
that worked :-)

**Comment by guusdk** [comment]
(Please, let me).
