### ISSUE TITLE
Join conversation to Docker Jitsi Server

### ISSUE THREAD

**Issue by danielgimeno** [jitsi/jitsi-meet#3596]
I have started the Docker environment successfully. I can join a video conference from web clients without problem. The thing is that mobile clientes, Android or Iphone can not join the conference. Funny thing is that the same clients can join a meeting in the server when I started all Jitsi components from apt-get installation. So the question is, what are differences between Docker and package installed. 

# Expected Behavior
Expected Behavior should be like when the server has the same packages installed through aptget. 

# Steps to reproduce
Launch a mobile client app, create a room and try to join it. 

The .env file is almost the same as OOTB. I created my own certs, to have it as good as posible. Any help would be very appreciated. 

This is the log in the moment of a try for one of the mobiles.

web_1      | 80.28.141.89 - - [06/Nov/2018:16:41:29 +0100] "GET /config.js?room=sfd HTTP/1.1" 200 13812 "-" "okhttp/3.6.0"
web_1      | 80.28.141.89 - - [06/Nov/2018:16:41:29 +0100] "POST /http-bind?room=qwe HTTP/1.1" 200 346 "https://jitsi.medsbla.com:8443/qwe" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
jvb_1      | JVB 2018-11-06 16:41:29.855 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriStatsExtension@64cc5158
jvb_1      | JVB 2018-11-06 16:41:34.856 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriStatsExtension@822e6d
jvb_1      | JVB 2018-11-06 16:41:36.498 INFO: [19] org.jitsi.videobridge.Videobridge.log() CAT=stat create_conf,conf_id=316e06c2498a78aa conf_name=null,logging=false,conf_count=1,ch_count=0,v_streams=0
jvb_1      | JVB 2018-11-06 16:41:36.533 INFO: [19] org.jitsi.videobridge.health.Health.log() Performed a successful health check in 36ms. Sticky failure: false
web_1      | 80.28.141.89 - - [06/Nov/2018:16:41:39 +0100] "POST /http-bind?room=qwe HTTP/1.1" 200 346 "https://jitsi.medsbla.com:8443/qwe" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
jvb_1      | JVB 2018-11-06 16:41:39.866 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriStatsExtension@51d81fcd
jvb_1      | JVB 2018-11-06 16:41:44.867 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriStatsExtension@498fc097
jvb_1      | JVB 2018-11-06 16:41:46.540 INFO: [19] org.jitsi.videobridge.Videobridge.log() CAT=stat create_conf,conf_id=936005e20b4962f8 conf_name=null,logging=false,conf_count=1,ch_count=0,v_streams=0
jvb_1      | JVB 2018-11-06 16:41:46.573 INFO: [19] org.jitsi.videobridge.health.Health.log() Performed a successful health check in 33ms. Sticky failure: false

Thank you in advance, Daniel.

**Comment by saghul** [comment]
> I created my own certs,

What certs are these? Does the mobile web browser give a warning when you visit the site? Mobile applications don't support self-signed certificates, and the Docker setup doesn't yet support Let's Encrypt.

**Comment by saghul** [comment]
Correct.

**Comment by saghul** [comment]
Closing this then. Also, the Docker setup now contains builtin Let's Encrypt :-) ✨

**Comment by saghul** [comment]
@danielgimeno As long as you enable Let's Encrypt, it will.

**Comment by danielgimeno** [comment]
New release seems to work right, the letsencrypt certificates era correctly generated, and web clients can connect as usually, but mobiles are still spinning , the loading ball. And I usually see the red screen error modules/xmpp/strophe.util.js request id error 0  happened.

**Comment by saghul** [comment]
Your own build or the one from the store?
