### ISSUE TITLE
[RN] How to disable remote audio track.

### ISSUE THREAD

**Issue by vtrungbk87** [jitsi/jitsi-meet#3598]
On mobile device, we can not mute audio when joining a meeting room. 
Sometime I need mute all audio of remote participant but can not found any method for that. 
Thank for your support

**Comment by vtrungbk87** [comment]
> There is currently no way to do this.

Thank for your reply. 
If have any plan to update it, please share with us. Thank you!

**Comment by inspifinity** [comment]
@vtrungbk87 @saghul 
Any update on this? I have the same problem
