### ISSUE TITLE
Last application shared in desktopShare is still seen from users who don't have a camera or have camera disabled

### ISSUE THREAD

**Issue by d2chau** [jitsi/jitsi-meet#360]
When userA, a user who doesn't have a camera or has their camera disabled, desktopShares and stops desktopSharing, the other participants in the meeting can still see userA's last shared application. 

For userA, it seems as though he/she thinks that they are still sharing.

We can detect this by looking at `APP.RTC.localStreams[ ]`. If we look at the `LocalStream` that is not audio, it has a `videoType` of "screen" although desktopShare has been stopped. It is supposed to be "camera". I believe desktopShare also disables Active Speaker which contributes to userA's last image of desktopShare being displayed and not transitioning to others participants who are talking.

This may be due to how desktopShare is detecting that it has stopped. Within `desktopsharing.js`, while disabling desktopShare it tries to get a new video stream and if that fails, a method is called and defaults to a null stream. `newStreamCreated(null);`. 

The portion of code which handles disabling desktopShare is below. 

```
APP.RTC.getUserMediaWithConstraints(
    ['video'],
    function (stream) {
        // We are now using camera stream
        isUsingScreenStream = false;
        newStreamCreated(stream);
    },
    getVideoStreamFailed, config.resolution || '360'
);
```

**Comment by bgrozev** [comment]
Probably fixed by now. Please re-open if this happens.
