### ISSUE TITLE
Cannot setup letsencrypt

### ISSUE THREAD

**Issue by tuncK** [jitsi/jitsi-meet#3601]
I am using Ubuntu 18.04 and tried to install the stable version using the repositories. I then wanted to change the self-signed security certificates to the ones generated by certbot. For that, I used the shell script provided by the jitsi-meet package: 
`/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`

However, this script in its default configuration generates an error message:
`pkcs12: Cannot open input file /etc/letsencrypt/live/-emy.domain.com/fullchain.pem, No such file or directory
pkcs12: Use -help for summary.`

Noting the extra '-e' in the domain name, I think line 8 is the culprit, but I could not fix it, because I actually could not understand why this line is necessary.
`DOMAIN="$(echo -e "${DOMAIN}" | tr -d '[:space:]')"`

**Comment by tuncK** [comment]
No, the domain is of the form `my.domain.com` -e part comes from line 8, and this is what breaks the script.

**Comment by damencho** [comment]
Which OS version are you using?

**Comment by tuncK** [comment]
Ubuntu Server 18.04

**Comment by damencho** [comment]
That is so strange. I just tested it on an Ubuntu 18.04 with domain of same type and I have no problem, that passes without an error.
Is it possible by any chance that you have added some non ASCII char in the hostname while configuring jitsi-meet?

What is your output when executing `debconf-show jitsi-meet-web-config | grep jvb-hostname`, I have:
```
* jitsi-videobridge/jvb-hostname: testmeet.example.com
  jitsi-meet/jvb-hostname: testmeet.example.com
```

**Comment by damencho** [comment]
No, I was just testing till line 8 and was seeing the right output. I don't have a correct DNS setup for that machine and cannot actually test let's encrypt. Strange, how it is possible `echo` to behave differently ... wondering what can be the difference between both machines.

**Comment by tuncK** [comment]
I see, no idea either. Before I removed line 8, the system freaks out at lines 94-98, because 
`echo $DOMAIN` gives `-emy.domain.com`
