### ISSUE TITLE
Screen sharing Firefox 61.0.1 on ubuntu 7.2.0

### ISSUE THREAD

**Issue by Audevalade** [jitsi/jitsi-meet#3603]
When trying to share my screen on jitsi with firefox 61.0.1, only windox sharing is offered and not all applications are available from the list. In particular I do not have access to my libreoffice windows.
On chrome the full screen sharing is offered as an option but what is shared is a black screen.
Any idea on how to fix this?
Thanks,
Aude

**Comment by saghul** [comment]
> When trying to share my screen on jitsi with firefox 61.0.1, only windox sharing is offered and not all applications are available from the list. In particular I do not have access to my libreoffice windows.

This must be a Firefox bug, we have no control over what windows Firefox offers you.

> On chrome the full screen sharing is offered as an option but what is shared is a black screen.
> Any idea on how to fix this?

Does window sharing work on Chrome for you? We've seen reports of black screens on Windows lately and they seem to be related to GPU acceleration.

**Comment by Audevalade** [comment]
Hi,

thank you for your answer.

On chrome the windo situation is the same as in firefox, only a few 
applications are offered as sharing options and libreoffice is not one 
of them..

Best,

Aude

**Comment by saghul** [comment]
That's really interesting. Alas, we have no control over what Chrome / Firefox display there :-/

**Comment by daimoc** [comment]
Hi Aude,

Are you really using an Unbuntu 7 version (from 2007) or is it an Unbuntu 17 version ?
As Ubuntu 17 switch from default display server from x11 to Wayland,  the screen capture process could be impacted. 

Could you run  echo $XDG_SESSION_TYPE to see if you'are using  X11 or Wayland  ?

Best Regards,
Damien

**Comment by fippo** [comment]
This is related to wayland. https://chromium.googlesource.com/external/webrtc/+/318da51f99f91e3de1192f29d7f1824958f9f13e just (re)landed support in webrtc.org. 

@nils-ohlmeier FYI

**Comment by nils-ohlmeier** [comment]
Yes there is even wayland patch for Firefox https://src.fedoraproject.org/rpms/firefox/blob/master/f/firefox-pipewire.patch which now after we upgraded to libwebrtc 64 needs to be rebased and landed in Firefox.

**Comment by saghul** [comment]
This is awesome! Thanks @daimoc @fippo and @nils-ohlmeier 

I'm going to go ahead and close this then!
