### ISSUE TITLE
Add DTMF UI controls 

### ISSUE THREAD

**Issue by wtip** [jitsi/jitsi-meet#3606]
When adding a SIP caller through jigasi it would be nice to have the option to send DTMF tones.
For example I would like to be able to dial into a third party PSTN conference bridge and currently can't do that because I can't send the required PIN.

It looks like this functionality did exist at some point but then was removed #2731

**Comment by wtip** [comment]
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/DTMF/JitsiDTMFManager.js
DTMF code appears to still be in `lib-jitsi-meet`

**Comment by jbguerraz** [comment]
Exactly the same need here. What happened / is happening with the dtmf support ?
