### ISSUE TITLE
Screen sharing not working on CEF(chromium embedded framework)

### ISSUE THREAD

**Issue by lamposu** [jitsi/jitsi-meet#3608]
I want to embed the jitsi meet in our desktop project via the CEF(chromium embedded framework) browser, everything works fine except the screen sharing "failed to install desktop extension".  
The CEF did not support the google chrome extension, is there some one can help me to achieve this? thanks a lot!

**Comment by zsinba** [comment]
The question remains.I guess he's CEF's problem.Because other than the Jitsi, other applications can't turn desktop sharing on in CEF.
