### ISSUE TITLE
Can not run ios app

### ISSUE THREAD

**Issue by fengzhonglingluandeduanfa** [jitsi/jitsi-meet#3609]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by fengzhonglingluandeduanfa** [comment]
Hi guys,

The code you just downloaded is not running yet

But now when I run pod install I get the following error:

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by pohsiu** [comment]
you could try update cocoapods to 1.5.3

**Comment by fengzhonglingluandeduanfa** [comment]
I've done it, but it doesn't work

**Comment by fengzhonglingluandeduanfa** [comment]
I've done it but it's no help
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by pohsiu** [comment]
Have you tried update your xcode version?

**Comment by fengzhonglingluandeduanfa** [comment]
xcode9.4.1
