### ISSUE TITLE
font awesome missing iOS

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3614]
Just compiled after a fresh git clone and I noticed that jitsi-meet complains about missing font awesome (see attached screenshot).

And indeed one can see question marks where the speaker and moderator star would normally be when in a conference on iOS

![awesome_bug](https://user-images.githubusercontent.com/32959420/48854240-4eacbf00-eda9-11e8-8ad1-95469ca26756.PNG)

**Comment by pdarcos** [comment]
Ok, looking through past commits it seems you removed FontAwesome https://github.com/jitsi/jitsi-meet/pull/3550/commits/f3d0d1ca7eda95c7350b3475502e86fa56bb31d6

But why did you remove it when it's still being used (in iOS at least)?

**Comment by pdarcos** [comment]
OK, I see now that commit actually reverted a previous one that had removed FontAwesome.

So the question remains why jitsi-meet throws the error above when FontAwesome is there (I checked and it is present)?

Could there be a version mismatch or a new naming convention like other RN projects have encountered? https://github.com/entria/react-native-fontawesome/issues/29

**Comment by pdarcos** [comment]
Am I the only one experiencing this issue?
Can someone else please confirm this is a bug/misconfiguration?

**Comment by pdarcos** [comment]
Is it just me having this issue?

**Comment by sfratini** [comment]
@pdarcos I am having the same issue, only in iOS. In my case it cannot find the fa_solid_900 font which is the one the library uses. Probably because the fontFamily is different. In my opinion FontAwesome broke everything with their v5 update

**Comment by saghul** [comment]
Hi there. Sorry, this is my fault. I plan on removing FontAwesome entirely, and I'll re-create the PR that had to be reverted, plus the needed fixes. In the meantime, you can revert the patch which removed them from iOS yourself.

**Comment by pdarcos** [comment]
No worries @saghul 
Thanks for confirming!

Go ahead and close if you want to

**Comment by saghul** [comment]
This is fixed in master now.

**Comment by pdarcos** [comment]
Confirmed working OK now.
Thanks @saghul!
