### ISSUE TITLE
Is it possible to access the all recording videos via Dropbox

### ISSUE THREAD

**Issue by andaralex** [jitsi/jitsi-meet#3617]
Hi There,

I am using Jitsi Meeting External API for connecting Video Call. Is it possible to access all recording via Dropbox API?

All the recording have saved through our appKey, is it possible to access the saved files through Dropbox API.?

I have config the dropbox appKey in configOverwrite.

The idea is end user can connect multiple video call based on timings and the call should be recorded by the user. Later the user has the option to replay that recorded call. 

So I want to know, where the recorded files saved in end user own Dropbox account or based on config it saved through the registered app in Dropbox which I have the config in the configOverwrite option.

Also, make sure the above scenario is possible to achieve using Jitsi External API and any idea to record the call automatically like autoRecord or something else?

**Comment by damencho** [comment]
Please use the community forum for questions.

> I am using Jitsi Meeting External API for connecting Video Call. Is it possible to access all recording via Dropbox API?

No.

> All the recording have saved through our appKey, is it possible to access the saved files through Dropbox API.?
No, the recordings are saved using the Dropbox account of the user who started the recording. 

The recordings are saved in the personal Dropbox account and there is no auto-record feature.
