### ISSUE TITLE
jitsi-meet basic pull and make broken dependencies on 18.04

### ISSUE THREAD

**Issue by idistech** [jitsi/jitsi-meet#3618]
Apologises for any repeats, if this has been covered elsewhere. Im trying to follow the basic
'# git clone ...
# npm install
'
to enable a make..
I have a number of broken dependencies at the end of this process :+1: 

_npm WARN @atlaskit/flag@6.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/icon@7.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react-dom@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/layer@2.9.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.57.5 requires a peer of react@16.6.1 but none is installed. You must install peer dependencies yourself._

I can see a few others with the same issue, but from reding , its not clear what the resolution was ( or is ? ) .. Cant see anything on the community forum...

Did we get to a simple set of steps to resolve  ?
I know node dependencies can be really tough - is the answer to use the "npm audit fix --force" ?
Thank you for all your help ;-)

**Comment by virtuacoplenny** [comment]
They're warnings and should cause no errors while running or building. Do you see errors? Does make not succeed? A use for peerDependencies is making sure that the consumer of a package has installed dependencies the package needs for execution. In jitsi-meet's case, react and react-dom are installed but are not the exact versions listed in the peer dependencies of those packages.

**Comment by idistech** [comment]
Thanks for the help, 
I did 'just ignore' and all seemed to progress so far ...
Thank you again for the help !
