### ISSUE TITLE
NAT Issues

### ISSUE THREAD

**Issue by FShieldheart** [jitsi/jitsi-meet#3621]
Hello All,

First of all, thank you for the people who contributed and are still contributing to this great work.
I have a problem, probably related to a NAT issue. I did a quick install to a Debian standalone machine. I've used the DNS name and certificate files which my organization has provided me and it is working properly in LAN. This Debian server is behind a Load Balancer and NAT. So, I added the following lines to sip-communication.properties file which exists both in "videobridge" and "jicofo" folders:

org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=XXX.XXX.XXX.XXX
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=YYY.YYY.YYY.YYY

XXX.XXX.XXX.XXX is the local address of the machine and YYY.YYY.YYY.YYY is the address of the global address. UDP 10000, TCP 443 and 4443 are all opened in the firewall (both machine and the corporation) and all port forwarding are done (checked by the system administration).

My problem starts here: It seems working when users in LAN (or through VPN) but when they are not in LAN, it is not working _everytime_. Sometimes, two people connected and everything seems fine. Sometimes, only audio is working, sometimes only the video is working, sometimes one person can see and hear the other one but the other one can not. And sometimes, it just kicks out one of the participants. I can not find a correlation or pattern when or under which circumstances this occurs. These are my "webrtc" logs:

![image](https://user-images.githubusercontent.com/34981623/48978977-59c36000-f0c5-11e8-8f54-cd06feb9e69f.png)

Bytes are received and send successfully according to the logs and system administration trace results. I do not know why this problem occurs. I need some help with this issue.

UPDATE 1:
--
When one participant failed as I have explained above, I noticed a different log on the console of the client with a loop frequency of ten seconds approximately. It writes:

"[JitsiConference.js] <e.sendMessage>: Failed to send a ping request or response."

If a participant successfully connects, then this log does not appear.

UPDATE 2:
--
After the first four of the log appearance discussed in Update 1, an error has occurred:

"[conference.js] <e.value>: CONFERENCE FAILED: conference.setup_failed Error: ICE fail at i.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:479) at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TracablePeerConnection.js:252)"

UPDATE 3:
--
When a participant has a problem or disconnected, after a couple of refreshes, it is starting to work normally. I can find no pattern of the refresh count needed to succeed. 

Thanks in advance.

FS

**Comment by JustinTQ** [comment]
Hello, I have a similar problem. Browser Warns: '[JitsiConference.js] <e.sendMessage>: Failed to send a ping request or response. ' Can you tell me how you solved it in the end? Thank you.
