### ISSUE TITLE
Shared Hosting Deployment and Developing Locally On Non-Ubuntu Systems

### ISSUE THREAD

**Issue by thecodecafe** [jitsi/jitsi-meet#3623]
Is there a guide on how to install and develop with jitsi locally and also deployment for shared hosting?

**Comment by saghul** [comment]
You can follow this quick install guide: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md for Ubuntu systems or do a manual install: https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

Alternatively, you can use our Docker images: https://github.com/jitsi/docker-jitsi-meet
