### ISSUE TITLE
react-native error

### ISSUE THREAD

**Issue by a3101380** [jitsi/jitsi-meet#3624]
This error occurred when the video chat page was closed  error(console.error:"[__filename]","<|>:","_REMOVE_AUDIO_ELEMENT:no sound for id: PARTICIPANT_JOINED_SOUND
![img_1579](https://user-images.githubusercontent.com/16264659/49064600-5b705d80-f256-11e8-92df-e9bec9e9c19f.PNG)
")

**Comment by monkey1992** [comment]
I have the same issue and don't know why, any one can offer us a hand, thanks a lot!

**Comment by saghul** [comment]
Are you building the app or using the SDK?

**Comment by a3101380** [comment]
building the app

**Comment by saghul** [comment]
Are you running latest master? I made some heavy changes to the build system in the past few days, can you please try again?

**Comment by a3101380** [comment]
ok Thank you

**Comment by meetinglink** [comment]
I'm not sure if this helps your particular case, and I also haven't managed to solve this issue yet...

I've commented out some lines in _OverflowMenu.js_ related to subtitles, live streaming, and the lock room button.  When these lines are commented out, I get this same "no sound for id" error.  

I'll report back when I identify what's causing the issue.

**Comment by visheshtungare-hiteshi** [comment]
i am also facing the same issue i am using the latest master in my project

**Comment by saghul** [comment]
It's not an error, you can dismiss it. We will get rid of that screen though.
