### ISSUE TITLE
Prosody error in binding encrypted port

### ISSUE THREAD

**Issue by andaralex** [jitsi/jitsi-meet#3639]
We saw the error in Prosody 

Error binding encrypted port for https: No key present in SSL/TLS configuration for https port 5281 

Could anyone help on this? How we can resolve this issue?

**Comment by saghul** [comment]
That error is harmless and you can ignore it. Or better yet, disable encrypted BOSH altogether by putting this in the main config file: `https_ports = { }`

You are going to be proxying the BOSH connection anyway, so there is no need to be listening for BOSH over HTTPS.

**Comment by sivasaiganesh08** [comment]
main config file??

**Comment by hex-m** [comment]
`/etc/prosody/prosody.cfg.lua`
