### ISSUE TITLE
"I am the host" button not working on Chrome 45.0.2454.101

### ISSUE THREAD

**Issue by wrouesnel** [jitsi/jitsi-meet#364]
When configuring authentication for conference creators, the "I am the host" button will never invoke the callback because `submitValue` is undefined.

It's not clear why it's undefined, but I got perfectly normal behavior by removing the dependency and just making the function always call `callback()`.

``` javascript
            function (onSubmitEvent, submitValue) {

                // Do not close the dialog yet
                onSubmitEvent.preventDefault();

                // Open login popup
                //if (submitValue === 'authNow') {
                callback();
                //}
            }
```

**Comment by damencho** [comment]
Obsolete.
