### ISSUE TITLE
Manual installation ： Unable to carry out normal audio and video communication

### ISSUE THREAD

**Issue by pzqtinger** [jitsi/jitsi-meet#3645]
All code is manual installation,  run log , can see what the problem is?

![1543549531 1](https://user-images.githubusercontent.com/34857924/49267430-7a106780-f495-11e8-9f26-e2312fe775d7.jpg)

Jicofo 2018-11-30 11:29:04.108 INFO: [12] org.jitsi.service.libjitsi.LibJitsi.log() Successfully started LibJitsi using as implementation: org.jitsi.impl.libjitsi.LibJitsiOSGiImpl
Jicofo 2018-11-30 11:29:04.116 INFO: [12] impl.configuration.ConfigurationActivator.log() Using properties file configuration store.
Jicofo 2018-11-30 11:29:04.118 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.HOSTNAME=jitsi.example.com
Jicofo 2018-11-30 11:29:04.118 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.runtime.name=OpenJDK Runtime Environment
Jicofo 2018-11-30 11:29:04.118 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
Jicofo 2018-11-30 11:29:04.118 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.version=25.191-b12
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.vendor=Oracle Corporation
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vendor.url=http://java.oracle.com/
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() path.separator=:
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.util.logging.config.file=/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/logging.properties
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.name=OpenJDK 64-Bit Server VM
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() file.encoding.pkg=sun.io
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.country=US
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.java.launcher=SUN_STANDARD
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.os.patch.level=unknown
Jicofo 2018-11-30 11:29:04.119 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.service.media.DISABLE_AUDIO_SUPPORT=true
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.specification.name=Java Virtual Machine Specification
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.dir=/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.FOCUS_USER_PASSWORD=**********
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.runtime.version=1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() os.arch=amd64
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.io.tmpdir=/tmp
Jicofo 2018-11-30 11:29:04.120 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() line.separator=

Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.specification.vendor=Oracle Corporation
Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() os.name=Linux
Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.jnu.encoding=UTF-8
Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.CONFIGURATION_FILE_IS_READ_ONLY=true
Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.FOCUS_USER_DOMAIN=auth.jitsi.example.com
Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.library.path=/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/native/linux-64
Jicofo 2018-11-30 11:29:04.121 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.specification.name=Java Platform API Specification
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.class.version=52.0
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.service.audionotifier.AudioNotifierService=org.jitsi.impl.neomedia.notify.AudioNotifierServiceImpl
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.management.compiler=HotSpot 64-Bit Tiered Compilers
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() os.version=4.15.0-39-generic
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.home=/root
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.timezone=Asia/Shanghai
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.awt.printerjob=sun.print.PSPrinterJob
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.FOCUS_USER_NAME=focus
Jicofo 2018-11-30 11:29:04.122 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() file.encoding=UTF-8
Jicofo 2018-11-30 11:29:04.123 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.specification.version=1.8
Jicofo 2018-11-30 11:29:04.123 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.service.media.DISABLE_VIDEO_SUPPORT=true
Jicofo 2018-11-30 11:29:04.123 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.XMPP_DOMAIN=jitsi.example.com
Jicofo 2018-11-30 11:29:04.123 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.class.path=/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/jicofo-1.1-SNAPSHOT.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/agafua-syslog-0.4.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/annotations-15.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/bccontrib-1.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/bcpkix-jdk15on-1.54.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/bcprov-jdk15on-1.54.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/cglib-nodep-2.2.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/commons-codec-1.6.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/commons-lang3-3.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/commons-logging-1.2.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/concurrentlinkedhashmap-lru-1.0_jdk5.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/core-2.0.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/dnsjava-2.1.7.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/dom4j-1.6.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/fmj-1.0-20160121.172939-10.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/guava-15.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/httpclient-4.4.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/httpcore-4.4.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/ice4j-2.0.0-20181005.221549-11.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jain-sip-ri-ossonly-1.2.98c7f8c-jitsi-oss1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/java-dogstatsd-client-2.5.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/java-sdp-nist-bridge-1.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/javax.servlet-3.0.0.v201112011016.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/javax.servlet-api-3.1.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jbosh-0.9.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jcip-annotations-1.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jcl-core-2.8.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-ajp-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-client-9.2.10.v20150310.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-continuation-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-http-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-io-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-proxy-9.2.10.v20150310.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-security-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-server-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-servlet-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-util-8.1.16.v20140903.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-webapp-7.0.1.v20091125.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jetty-xml-7.0.1.v20091125.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jicoco-1.1-20180710.162527-5.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-android-osgi-1.0-20180322.162617-2.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-configuration-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-credentialsstorage-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-dnsservice-2.9-20150723.181644-1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-netaddr-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-protocol-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-protocol-jabber-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-protocol-media-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-ui-service-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jitsi-util-2.13.f6042d3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jna-4.1.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jnsapi-0.0.3-jitsi-smack4.2-3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/json-simple-1.1.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jxmpp-core-0.6.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jxmpp-jid-0.6.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/jxmpp-util-cache-0.6.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/libidn-1.15.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/libjitsi-1.0-20180829.231707-362.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/object-cloner-0.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/objenesis-2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/orange-extensions-1.3.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/org.apache.felix.framework-4.4.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/org.apache.felix.main-4.4.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/org.osgi.core-4.3.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/sdes4j-1.1.3.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/sdp-api-1.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/slf4j-api-1.7.7.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/slf4j-jdk14-1.7.7.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-bosh-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-core-4.2.2-b1c107f.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-debug-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-experimental-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-extensions-4.2.2-b1c107f.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-im-4.2.2-b1c107f.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-java7-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-legacy-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-resolver-javax-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-sasl-javax-4.2.1.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/smack-tcp-4.2.2-b1c107f.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/tinder-1.3.0.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/weupnp-0.1.4.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/xml-apis-1.0.b2.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/xmlpull-1.1.3.4a.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/xpp3-1.1.4c.jar:/work/src/jitsi-meet/jicofo/jicofo-linux-x64-1.1-SNAPSHOT/lib/zrtp4j-light-3.2.0-jitsi-1-20150723.002345-1.jar
Jicofo 2018-11-30 11:29:04.123 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.name=root
Jicofo 2018-11-30 11:29:04.123 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.specification.version=1.8
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.java.command=org.jitsi.jicofo.Main --domain=jitsi.example.com --secret=X --user_domain=auth.jitsi.example.com --user_name=focus --user_password=X
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.arch.data.model=64
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.language=en
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.specification.vendor=Oracle Corporation
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() awt.toolkit=sun.awt.X11.XToolkit
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.info=mixed mode
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.version=1.8.0_191
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
Jicofo 2018-11-30 11:29:04.124 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.boot.class.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vendor=Oracle Corporation
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() file.separator=/
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.impl.configuration.USE_PROPFILE_CONFIG=true
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vendor.url.bug=http://bugreport.sun.com/bugreport/
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.io.unicode.encoding=UnicodeLittle
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.cpu.endian=little
Jicofo 2018-11-30 11:29:04.125 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.cpu.isalist=
Jicofo 2018-11-30 11:29:04.126 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() Normal classloader
Jicofo 2018-11-30 11:29:04.126 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() failed to find jitsi-defaults.properties with class loader, will continue without it.
Jicofo 2018-11-30 11:29:04.126 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() Normal classloader
Jicofo 2018-11-30 11:29:04.126 INFO: [12] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() failed to find jitsi-default-overrides.properties with class loader, will continue without it.
Jicofo 2018-11-30 11:29:04.140 INFO: [12] util.NetworkUtils.<clinit>().117 java.net.preferIPv6Addresses=null
Jicofo 2018-11-30 11:29:04.140 INFO: [12] util.NetworkUtils.<clinit>().118 java.net.preferIPv4Stack=null
Jicofo 2018-11-30 11:29:04.143 INFO: [12] impl.netaddr.NetworkAddressManagerServiceImpl.start().92 Network Address Manager         ...[  STARTED ]
Jicofo 2018-11-30 11:29:04.144 INFO: [12] impl.netaddr.NetworkAddressManagerServiceImpl.start().98 Network Address Manager Service ...[REGISTERED]
Jicofo 2018-11-30 11:29:04.147 INFO: [12] org.jitsi.version.AbstractVersionActivator.start().119 JiCoFo Version: JiCoFo 1.0.build.SVN
Jicofo 2018-11-30 11:29:04.275 INFO: [12] org.jitsi.jicofo.JitsiMeetGlobalConfig.init().170 Automatically grant 'owner' role: true
Jicofo 2018-11-30 11:29:04.275 INFO: [12] org.jitsi.jicofo.JitsiMeetGlobalConfig.init().183 Jibri requests in PENDING state will be timed out after: 90 seconds
Jicofo 2018-11-30 11:29:04.275 INFO: [12] org.jitsi.jicofo.JitsiMeetGlobalConfig.init().197 Lonely participants will be "terminated" after 20000 milliseconds
Jicofo 2018-11-30 11:29:04.289 INFO: [12] org.jitsi.jicofo.BridgeSelector.createBridgeSelectionStrategy().176 Using SingleBridgeSelectionStrategy
Jicofo 2018-11-30 11:29:04.289 INFO: [12] org.jitsi.jicofo.BridgeSelector.<init>().146 Using org.jitsi.jicofo.BridgeSelector$SingleBridgeSelectionStrategy
Jicofo 2018-11-30 11:29:04.289 INFO: [12] org.jitsi.jicofo.BridgeSelector.init().610 Bridge failure reset threshold: 300000
Jicofo 2018-11-30 11:29:04.337 INFO: [12] org.eclipse.jetty.server.Server.doStart() jetty-8.1.16.v20140903
Jicofo 2018-11-30 11:29:04.359 INFO: [12] org.eclipse.jetty.server.AbstractConnector.doStart() Started SelectChannelConnector@0.0.0.0:8888
Jicofo 2018-11-30 11:29:04.360 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.SC_HOME_DIR_NAME=.sip-communicator
Jicofo 2018-11-30 11:29:04.360 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.SC_HOME_DIR_LOCATION=/root
Jicofo 2018-11-30 11:29:04.363 INFO: [1] org.jitsi.xmpp.component.ComponentBase.loadConfig().202 Component org.jitsi.jicofo. config: 
Jicofo 2018-11-30 11:29:04.363 INFO: [1] org.jitsi.xmpp.component.ComponentBase.loadConfig().203   ping interval: 10000 ms
Jicofo 2018-11-30 11:29:04.363 INFO: [1] org.jitsi.xmpp.component.ComponentBase.loadConfig().204   ping timeout: 5000 ms
Jicofo 2018-11-30 11:29:04.363 INFO: [1] org.jitsi.xmpp.component.ComponentBase.loadConfig().205   ping threshold: 3
Jicofo 2018-11-30 11:29:04.536 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.discoverServices().267 New component discovered: jitsi-videobridge.jitsi.example.com, IQ Stanza (query jabber:iq:version) [to=focus@auth.jitsi.example.com/focus77858826892660,from=jitsi-videobridge.jitsi.example.com,id=h8CG4-21,type=result,]
Jicofo 2018-11-30 11:29:04.536 INFO: [19] org.jitsi.jicofo.BridgeSelector.addJvbAddress().215 Added videobridge: jitsi-videobridge.jitsi.example.com v: IQ Stanza (query jabber:iq:version) [to=focus@auth.jitsi.example.com/focus77858826892660,from=jitsi-videobridge.jitsi.example.com,id=h8CG4-21,type=result,]
Jicofo 2018-11-30 11:29:04.536 WARNING: [19] org.jitsi.jicofo.BridgeSelector.addJvbAddress().227 No pub-sub node mapped for jitsi-videobridge.jitsi.example.com
Jicofo 2018-11-30 11:29:04.538 INFO: [41] org.jitsi.jicofo.JvbDoctor.log() Scheduled health-check task for: jitsi-videobridge.jitsi.example.com
Jicofo 2018-11-30 11:29:04.542 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.discoverServices().267 New component discovered: focus.jitsi.example.com, null
Jicofo 2018-11-30 11:29:04.543 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.discoverServices().267 New component discovered: conference.jitsi.example.com, null
Jicofo 2018-11-30 11:29:04.543 INFO: [19] org.jitsi.jicofo.JitsiMeetServices.newNodeDiscovered().200 MUC component discovered: conference.jitsi.example.com
Jicofo 2018-11-30 11:29:04.545 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.discoverServices().267 New component discovered: auth.jitsi.example.com, IQ Stanza (query jabber:iq:version) [to=focus@auth.jitsi.example.com/focus77858826892660,from=auth.jitsi.example.com,id=h8CG4-30,type=result,]
Jicofo 2018-11-30 11:29:04.545 INFO: [19] org.jitsi.jicofo.JitsiMeetServices.newNodeDiscovered().208 Detected XMPP server version: IQ Stanza (query jabber:iq:version) [to=focus@auth.jitsi.example.com/focus77858826892660,from=auth.jitsi.example.com,id=h8CG4-30,type=result,]
Jicofo 2018-11-30 11:29:04.545 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.scheduleRediscovery().189 Services re-discovery interval: 30000
Jicofo 2018-11-30 11:29:04.545 INFO: [19] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered
Jicofo 2018-11-30 11:29:04.549 INFO: [19] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().309 XMPP provider Jabber:focus@auth.jitsi.example.com/focus77858826892660@jitsi.example.com connected (JID: focus@auth.jitsi.example.com/focus77858826892660)

**Comment by pzqtinger** [comment]
jvb run log

[jvb.log](https://github.com/jitsi/jitsi-meet/files/2631921/jvb.log)

**Comment by damencho** [comment]
Please in the future use the community forum, before opening an issue.

First check your browser javascript console log, what error do you see?

**Comment by pzqtinger** [comment]
![1543564360 1](https://user-images.githubusercontent.com/34857924/49275986-09c70d80-f4b8-11e8-8406-23c4e657a754.jpg)

**Comment by pzqtinger** [comment]
The community used it, but the posts were hidden.

**Comment by pzqtinger** [comment]
Can you see that there is a problem with my configuration?

**Comment by damencho** [comment]
https://community.jitsi.org/t/manual-installation-unable-to-carry-out-normal-audio-and-video-communication/15959
