### ISSUE TITLE
video recording failing

### ISSUE THREAD

**Issue by awsompankaj** [jitsi/jitsi-meet#3651]
I have setup jibri as per the steps in https://github.com/jitsi/jibri.
Standalone conferencing is  is working fine but recording is not working.
jibri server is configured on other than jitsi-meet server.

when clicking the recording butting it is showing preparing to recording and then fails.

**Comment by awsompankaj** [comment]
Attached are the files


[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2636311/jicofo.log)
[prosody.log](https://github.com/jitsi/jitsi-meet/files/2636312/prosody.log)
[jibri.log](https://github.com/jitsi/jitsi-meet/files/2636313/jibri.log)
[jicofo sip.txt](https://github.com/jitsi/jitsi-meet/files/2636317/jicofo.sip.txt)
[jibri config.txt](https://github.com/jitsi/jitsi-meet/files/2636314/jibri.config.txt)
[prosody.txt](https://github.com/jitsi/jitsi-meet/files/2636315/prosody.txt)
[jitsi.domain-prosody.txt](https://github.com/jitsi/jitsi-meet/files/2636316/jitsi.domain-prosody.txt)

**Comment by bbaldino** [comment]
Jibri is unable to connect to your xmpp server it seems:

```
2018-11-30 18:54:57.961 INFO: [247] class org.jitsi.xmpp.mucclient.MucClient.reconnectionFailed() [prod environment: auth.jitsi.liquidclouds.in@jitsi.liquidclouds.in] Xmpp connection status: reconnection failed: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
```

@damencho I think has seen this before?

**Comment by damencho** [comment]
Isn't this just a wrong password?

**Comment by awsompankaj** [comment]
> 
> 
> Isn't this just a wrong password?

@damencho I have verified the user password using profanity xmpp clinet from jibri server.

password is correct for both users i.e jibri and recorder.
below are the prosody logs for reference.

Dec 03 17:16:13 c2s561eaaf22030 info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Dec 03 17:16:13 c2s561eaaf22030 info    Authenticated as recorder@recorder.jitsi.liquidclouds.in
Dec 03 17:17:09 c2s561eaae98d80 info    Client connected
Dec 03 17:17:09 c2s561eaae98d80 info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Dec 03 17:17:09 c2s561eaae98d80 info    Authenticated as jibri@auth.jitsi.liquidclouds.in
