### ISSUE TITLE
unable to access camera

### ISSUE THREAD

**Issue by nuria2015** [jitsi/jitsi-meet#3652]

**Comment by nuria2015** [comment]
I 'm using the program but the program is unable to access my camera, I can talk and listen. The camera is working with other programs: skype, zoom.

When using jitsimeet any other program is open.
Camera and microphone are "allowed"

How more I have to do?

Thanks!

**Comment by danieleds** [comment]
Same issue here, on firefox+macos. It doesn't even ask to allow access to the camera, it just shows a yellow toast saying "Failed to access your camera".
With chrome it works fine.

**Comment by saghul** [comment]
I just tried macOS + Firefox and it worked fine. What Firefox version are you using?

**Comment by danieleds** [comment]
Firefox 64.0, macos 10.14.1.

**Comment by danieleds** [comment]
Actually, it works if I open the URL directly. It doesn't if I get there through a hyperlink.
So a workaround is: just reload the page.

**Comment by mibzman** [comment]
I've been seeing this in jitsi in chrome on mac Mojave, but this issue occurs intermittently, and also occurs with other applications.  That leads me to think that this is a mac issue and not a jitsi issue.

**Comment by rbhun** [comment]
wondering if this has been solved? I have the same issue still. MacOS 10.15.3, Safari 13.0.5. Safari says the camera is allowed, Jutsi preferences says camera is not allowed. There is a popup asking for microphone access (which works), no popup for camera. Chrome  on same machine works as advertised.

**Comment by peterdk** [comment]
We are getting no camera popup as well, and can't use it in Safari, but need Chrome.

**Comment by dur3x** [comment]
I have the same problem; safari looks not supported.

**Comment by JustinKenpisi** [comment]
Same problem here with a colleague trying to join a meeting with Safari - could only use audio. Real shame as otherwise jitsi has been fantastic.

**Comment by 1024kilobyte** [comment]
Same Here. Not really surprising as it is marked as not supported, but would be great to see any progress here .....

**Comment by fmthant** [comment]
The problem is still happened?
Safari latest version on Catalina version of Macos.

**Comment by luixxiul** [comment]
@ferdibayrak please see https://github.com/jitsi/jitsi-meet/issues/6872 for Safari on macOS.
