### ISSUE TITLE
Issue in DropBox integration in Jitsi Config.json file

### ISSUE THREAD

**Issue by andaralex** [jitsi/jitsi-meet#3654]
I have configured my DropBox app id in the Jitsi meet config.json like

dropbox: {
          appKey: "XXXXXXXxxxxx"
        }

While enabling the start recording option, it asking for Dropbox authorization and start recording the call. So the recording happened successfully and the file created in the server machine under the config folder "/tmp/recordings"

But the files did not push to Dropbox.

Could anyone help on this?

**Comment by virtuacoplenny** [comment]
You're more likely to get a response for this question on community.jitsi.org. The people that worked on dropbox/uploading integration check often on there. jitsi-meet is specifically the web and native frontend for jitsi.

**Comment by damencho** [comment]
You need to install jitsi-upload-integrations and use dropbox_uploader.sh(should be in /usr/bin) inside finalize_recording.sh. 

https://github.com/jitsi/jitsi-upload-integrations/blob/master/dropbox/dropbox_uploader.sh
https://github.com/jitsi/jibri/blob/master/resources/finalize_recording.sh

**Comment by frankodoom** [comment]
How do I install this package? apt install jitsi-upload-integrations not working for me at this current time.
