### ISSUE TITLE
Build Jitsi framework (iOS) for both arm and x86_64

### ISSUE THREAD

**Issue by luismachado** [jitsi/jitsi-meet#3659]
Hi,

I'm trying to integrate jitsi on my iOS app and so far I've managed to do it but I'm experiencing some issues.

The main one is that I'm only able to run my app either in a device or in the simulator depending on how I've build the Jitsi framework: when building Jitsi, if I select 'Generic iOS Device' it looks like it builds only for arm. On the other end, if I select any simulator, it will build for x86_64.

So my question is: is there any way to build the framework to support  both platforms at the same time?

Thanks!

**Comment by luismachado** [comment]
Thanks for the quick reply @saghul !
In the meanwhile I also found an alternative, by following this [guide](https://medium.com/@hassanahmedkhan/a-noobs-guide-to-creating-a-fat-library-for-ios-bafe8452b84b), by manually creating the fat library.

**Comment by felix-voicehub** [comment]
@saghul This does not seem to be valid anymore:

```
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination generic/platform=iOS -configuration Release archive
```

This leads to only x86_64 and arm64 in the framework:
```
lipo -info ios/sdk/JitsiMeet.framework/JitsiMeet
Architectures in the fat file: ios/sdk/JitsiMeet.framework/JitsiMeet are: x86_64 arm64
```

**Comment by umairgillani94** [comment]
I am just getting arm64 by running this command 

lipo -info ios/sdk/JitsiMeet.framework/JitsiMeet
Non-fat file: /Users/umairgillani/Library/Developer/Xcode/DerivedData/jitsi-meet-byuitotfesbuupfgntpadgftdfhq/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/JitsiMeet.framework/JitsiMeet is architecture: arm64

How can I also get x86_64?

**Comment by AmalJose-01** [comment]
/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Running on Xcode 12.4 with m1 mac
