### ISSUE TITLE
Build Jitsi library (Android) failed since this morning

### ISSUE THREAD

**Issue by omralcrt** [jitsi/jitsi-meet#3661]
Hi,

I'm trying to build my project but it is failed for Jitsi. It was working until today. I didn't change anything in the project. Just I want to build working project.

The error is:
![ekran resmi 2018-12-04 14 22 33](https://user-images.githubusercontent.com/12418327/49438683-28871600-f7d0-11e8-8313-9b92f462302e.png)

Do you have an idea?

Thanks!

**Comment by saghul** [comment]
Are you using `JitsiMeetView` or `JitsiMeetActivity` ? If it's the former, please paste some code on how how you are calling those methods.

**Comment by omralcrt** [comment]
I am using JitsiMeetView in the Fragment actually. This is my view setup:

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        appointmentResponse = ((VideoChatActivity)getActivity()).appointmentResponse;
        return setupCall();
    }

    View setupCall() {
        view = new JitsiMeetView(getActivity());
        view.setPictureInPictureEnabled(false);
        view.loadURL(null);

        view.setListener(new JitsiMeetViewAdapter() {
            @Override
            public void onConferenceFailed(Map<String, Object> data) {
                super.onConferenceFailed(data);
            }

            @Override
            public void onConferenceJoined(Map<String, Object> data) {
                super.onConferenceJoined(data);
                ((VideoChatActivity)getActivity()).hideWelcomePage();
                setupVideoChatPage();
            }

            @Override
            public void onConferenceLeft(Map<String, Object> data) {
                super.onConferenceLeft(data);
                getActivity().onBackPressed();
            }

            @Override
            public void onConferenceWillJoin(Map<String, Object> data) {
                super.onConferenceWillJoin(data);
            }

            @Override
            public void onConferenceWillLeave(Map<String, Object> data) {
                super.onConferenceWillLeave(data);
            }

            @Override
            public void onLoadConfigError(Map<String, Object> data) {
                super.onLoadConfigError(data);
            }
        });

        Bundle urlObject = new Bundle();
        Bundle config = new Bundle();
        config.putBoolean("startWithAudioMuted", false);
        config.putBoolean("startWithVideoMuted", false);

        urlObject.putBundle("config", config);
        String url = "https://"+appointmentResponse.getDomain()+"/"+appointmentResponse.getRoom();
        urlObject.putString("url", url);
        view.loadURLObject(urlObject);
        return view;
    }


And I call method which failed in parent activity like this:

    @Override
    protected void onDestroy() {
        super.onDestroy();
        JitsiMeetView.onHostDestroy(this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        JitsiMeetView.onNewIntent(intent);
    }

    @Override
    protected void onResume() {
        super.onResume();
        JitsiMeetView.onHostResume(this);
    }

**Comment by saghul** [comment]
Ah, I see. You need to call those mthods in the `ReactActivityLifecycleCallbacks` class now. Also note that your Activity / Fragment should now implement the `JitsiMeetActivityInterface` interface.

**Comment by omralcrt** [comment]
Thank you so much. That's worked!!

**Comment by saghul** [comment]
Cool! I created https://github.com/jitsi/jitsi-meet/pull/3662 just to warn people.
