### ISSUE TITLE
Jetty not serving application/json MIME type for apple app site association file

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3666]
Apple (and Google's) app site association file used to work fine on a self install, but I noticed lately that it stopped working.

Checking server side I noticed that jetty isn't using application/json MIME type when serving the apple-app-site-association file.

I assume this is a configuration issue that was changed recently in jetty?

Where/how can I set the correct parameters?

Thanks

**Comment by pdarcos** [comment]
Also having a related issue with Google's digital asset links https://developers.google.com/digital-asset-links/v1/getting-started. We need to put the file in the .well-known folder for Google to check if everyhting's OK but not sure how to configure that with Jetty. With nginx and apache it's a no brainer, but with jetty I don't know where we can configure this.

The weird part is that I'm having a deja vu feeling with this issue. I've had deep links for Google and Apple working before on my self-installed server, and I'm almost 100% certain it was using jetty, so I assume something changed in jetty's config?

Any help pointing me in the right direction is much appreciated.

**Comment by pdarcos** [comment]
Answering my own question regarding Google's verification policy, creating the folder manually and inserting the assetlinks.json file there solves that problem.

But I'm still stuck with Apple's verification of deeplinks. Anyone know how can I make sure that jetty serves the app site association file as json and not text? I assume we need to enter some jetty configuration to tell it to serve the file as json but not sure where and what config parameters to enter,
I believe we need to add something to the sip-communicator.properties file in /etc/jitsi/videobridge.

Any help is much appreciated!

**Comment by damencho** [comment]
I'm afraid that such configs need code changes ... The jetty inside jvb is embedded and configured from code.

**Comment by pdarcos** [comment]
Thanks @damencho 

I assume you're using nginx or apache on your jitsi meet production servers, so that's not a problem for you.
But if you're using jetty it becomes a big problem. Can you point to where in the code I can look at to build it from scratch?
By the way, has this ever worked with jetty before without having to change the code? Maybe I'm just confused but I could swear that I had it working before with jetty since last year.

Thanks!

**Comment by damencho** [comment]
I don't think we had changed anything about it. So the shared code is in https://github.com/jitsi/jicoco/tree/master/src/main/java/org/jitsi/rest and the jvb code is https://github.com/jitsi/jitsi-videobridge/blob/d9f5eefeaee9d7f520cf8616f42534c868013335/src/main/java/org/jitsi/videobridge/rest/PublicRESTBundleActivator.java
