### ISSUE TITLE
all streamers are currently busy We're working on freeing streaming resources. Please try again in a few minutes

### ISSUE THREAD

**Issue by ece106** [jitsi/jitsi-meet#3667]
This has been going on for a week on every youtube account we've tried.

**Comment by aaronkvanmeerten** [comment]
Thanks for the heads up.  This service is undergoing some changes and so the monitoring on the jibri instances has been limited.  This should be resolved temporarily now, and more permanently over the weekend.  Again, thanks for the report and please continue to let us know if you experience issues.

**Comment by dsaibene** [comment]
Hello, I am still facing this problem. What to do?

**Comment by aaronkvanmeerten** [comment]
What region are you in? We have recently made a fix in the last few hours that we hope to help resolve the problem. If you have tested recently please help us by sending your conference name and specific times you saw this error.

**Comment by dsaibene** [comment]
I am in Italy. Conference name is meet.jit.si/WikimediaItaliap2p. I saw it just on Monday and today, just now

**Comment by dsaibene** [comment]
Thank you. It seems to work now

**Comment by ece106** [comment]
We're suddenly getting the "all streamers are currently busy We're working on freeing streaming resources. Please try again in a few minutes" message again, starting a few minutes ago. Also, we just recorded something to youtube, but it's just a jitsi person icon with no audio.

**Comment by aaronkvanmeerten** [comment]
we have identified the underlying issue and are working to improve it.  We will continue to try to recover the older live jibris on meet.jit.si as they fail in this way as well.  Thanks for the notification.

**Comment by ece106** [comment]
We're no longer getting the orange  "all streamers are currently busy" notice. However we are unable to record audio on Mac, Linux; Firefox, Chrome. Only the video is sent to youtube.

**Comment by ece106** [comment]
It works! Thank you for all this important work you're doing.
