### ISSUE TITLE
Self-hosted service crashes often

### ISSUE THREAD

**Issue by CicoZhang** [jitsi/jitsi-meet#3668]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
It is a self-hosted service, with the latest version installed.
---

## Current behavior
---
The service crashed often when I am using or even not using it. 
I have to **Restarting jitsi-videobridge** to get it fall into the place.

## Expected Behavior
---
It should be working smoothly.

## Possible Solution
---
I don't know.

## Steps to reproduce
---
It appears automatically, rather often.

# Environment details
---
Ubuntu 16.04
512MB of memory
10GB of NVMe space
1 Shared Cores

**Comment by damencho** [comment]
Please use the community forum for questions or problems, before opening new issues.

I suspect your 512MB of memory is too low for running jicofo and jvb on the same machine, 4 or 8 GB of RAM will be reasonable to handle a normal load. 
If this happens again, check the jvb logs to see the actual errors.
