### ISSUE TITLE
Unable to outcall from Jitsi

### ISSUE THREAD

**Issue by keshav0129** [jitsi/jitsi-meet#3670]
Jitsi: jvb, jicofo and jigasi installed on ubuntu 16.4 following quick install and without any errors. I could also see that jigasi is seen in jicofo logs and registered as sip client to my proxy. I could also see the '+' icon in jitsi page.

the problem occurs when I try to make out calls. Here's what I see in jigasi.log

jigasi.log
----
https://pastebin.com/LiMHsMJL

**Comment by saghul** [comment]
Try to set this option in /etc/jigasi/sip-communicatior.properties:

`net.java.sip.communicator.service.gui.ALWAYS_TRUST_MODE_ENABLED=true`
