### ISSUE TITLE
No remote video if auth domain activated when the moderator joins after a waiting participant

### ISSUE THREAD

**Issue by Toumassa** [jitsi/jitsi-meet#3671]
## Description

When creating a jitsi conference requires authentication, the participant who waits a host will not have remote video and audio (thumbnails) once a moderator joins. 

## Steps to reproduce

1) Activate authenticated domain for the MUC
2) Create a room (auth promt should pop, do not type credentials yet)
3) Join the conference with an other user (auth promp should pop for him too)
4) Use valid credentials for the first participant to start the conference
5) The other participant will join in max 5 sec but will not have remote thumbnails (video and audio)

## Environment details

Jitsi-meet_3344

## Possible Solution

See the commit 8cfc83f18cf5a22de283377a42117f9d97d40619
File: /react/features/base/participants/actions.js in the function participantJoined

This condition is too restrictive. The state value *conference* or *joining* do not exist in the case described above.

```javascript
if (conference === stateFeaturesBaseConference.conference
   || conference === stateFeaturesBaseConference.joining) {
         return dispatch({
                type: PARTICIPANT_JOINED,
                participant
    });
}
```

One way to correct this is to check if `stateFeaturesBaseConference.authRequired` exists in the state.
If the variable exists this means the authenticationRequired error already poped.

```javascript

if (conference === stateFeaturesBaseConference.conference
        || conference === stateFeaturesBaseConference.joining 
        || stateFeaturesBaseConference.authRequired !== undefined) {
    return dispatch({
        type: PARTICIPANT_JOINED,
        participant
    });
}

```

**Comment by virtuacoplenny** [comment]
I have a very vague recollection of this issue. Another side of the problem comes from lib-jitsi-meet's authenticateAndUpgradeRole function somehow making it so the wrong room is being listened in to for a/v updates from remote participants, like it has listeners set on the room before the password and so none of those updates are received. Admittedly, I didn't get anywhere with the issue other than that.

**Comment by daimoc** [comment]
Hello, we're experimenting exactly the same issue.
The fix proposed by @Toumassa  seems to work well on our test platform.
Does someone see any drawback to add the authRequired check in this if condition ?

**Comment by damencho** [comment]
I still haven't looked at the code, it is in my todo list, but I think what is happening is that when joining with authentication in that case you experience, then conference_will_join (the joining state) is omitted and this is the right way to be fixed.
