### ISSUE TITLE
How to capture ParticipantLeft action and send event in Jitsi Mobile SDK.

### ISSUE THREAD

**Issue by sabir-ali** [jitsi/jitsi-meet#3678]
I understood from this [link](https://github.com/jitsi/jitsi-meet/issues/2686) that I need to capture that action and send an event in this file : https://github.com/jitsi/jitsi-meet/blob/master/react/features/mobile/external-api/middleware.js

If anyone has done something similar, please help how to achieve it.

**Comment by saghul** [comment]
Duplicate of https://github.com/jitsi/jitsi-meet/issues/3673
