### ISSUE TITLE
When someone Kicks Out another user, the person kicked out can still re-enter the chat room

### ISSUE THREAD

**Issue by ece106** [jitsi/jitsi-meet#3679]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
This is how xmpp kick works. https://xmpp.org/extensions/xep-0045.html#kick
