### ISSUE TITLE
Jitsi reconnection problem

### ISSUE THREAD

**Issue by exagon** [jitsi/jitsi-meet#3680]
I've installed the last version of jitsi-meet on Ubuntu 16.04, with nginx as a reverse proxy.

From internal LAN all work fine but from internet i've some disconnection problem.So when someone join to mett all work fine but afte 50 sec disconnect and reconnect in loop.

Here the log :
JVB 2018-12-11 09:46:37.469 INFO: [593] org.jitsi.videobridge.SctpConnection.log() SCTP socket accepted for endpoint ab28789d
JVB 2018-12-11 09:46:37.491 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:37.492 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:37.680 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:37.681 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:38.675 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:38.675 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:40.678 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:40.679 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:40.974 FINE: [349] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId weLrj-183): <iq type="get" to="jitsi-videobridge.bpvideo.xxxx.it" from="focus@auth.bpvideo.xxxx.it/focus977626740802" id="weLrj-183"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
JVB 2018-12-11 09:46:40.975 FINE: [349] org.jitsi.videobridge.xmpp.ComponentImpl.processIQRequest() (serving component 'JitsiVideobridge') Processing IQ request (packetId weLrj-183).
JVB 2018-12-11 09:46:40.975 FINE: [349] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq type="get" to="jitsi-videobridge.bpvideo.xxxx.it" from="focus@auth.bpvideo.xxxx.it/focus977626740802" id="weLrj-183"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
JVB 2018-12-11 09:46:40.978 FINE: [349] org.jitsi.videobridge.xmpp.ComponentImpl.log() SENT: <iq to="focus@auth.bpvideo.xxxx.it/focus977626740802" from="jitsi-videobridge.bpvideo.xxxx.it" id="weLrj-183" type="result"/>
JVB 2018-12-11 09:46:40.978 FINE: [349] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Responding to IQ (packetId weLrj-183) with: <iq to="focus@auth.bpvideo.xxxx.it/focus977626740802" from="jitsi-videobridge.bpvideo.xxxx.it" id="weLrj-183" type="result"/>
JVB 2018-12-11 09:46:42.558 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:42.558 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:42.673 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:42.673 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:44.657 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:44.657 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:45.730 FINE: [394] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId iJESe-60): <iq id="iJESe-60" type="result" to="jitsi-videobridge.bpvideo.xxxx.it" from="bpvideo.xxxx.it"/>
JVB 2018-12-11 09:46:45.730 FINE: [394] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq id="iJESe-60" type="result" to="jitsi-videobridge.bpvideo.xxxx.it" from="bpvideo.xxxx.it"/>
JVB 2018-12-11 09:46:46.587 INFO: [46] org.jitsi.videobridge.Videobridge.log() CAT=stat create_conf,conf_id=1f9d4b612ce0b5a9 conf_name=null,logging=false,conf_count=2,ch_count=6,v_streams=4
JVB 2018-12-11 09:46:46.644 INFO: [46] org.jitsi.videobridge.health.Health.log() Performed a successful health check in 57ms. Sticky failure: false
JVB 2018-12-11 09:46:46.664 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:46.664 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:48.554 WARNING: [43] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:48.554 WARNING: [43] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:48.656 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with bd7957d5 not ready yet.
JVB 2018-12-11 09:46:48.656 WARNING: [592] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2018-12-11 09:46:49.053 FINE: [396] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId weLrj-223): <iq type="set" to="jitsi-videobridge.bpvideo.xxxx.it" from="focus@auth.bpvideo.xxxx.it/focus977626740802" id="weLrj-223"><conference xmlns="http://jitsi.org/protocol/colibri" id="3f682944ae567eb4" name="a" gid="fffbfa"><content name="audio"><channel id="724f9fb3617007fb" expire="0"/></content><content name="video"><channel id="e51185cb9b068e20" expire="0"/></content><content name="data"><sctpconnection endpoint="bd7957d5" port="5000" id="2d8a57f3ba068771" expire="0"/></content></conference></iq>

and the configuration : 

org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.bpvideo.xxxxx.it/.*
org.jitsi.videobridge.rest.jetty.host=::
org.jitsi.videobridge.rest.jetty.port=443
org.jitsi.videobridge.rest.jetty.ProxyServlet.hostHeader=bpvideo.xxxxx.it
org.jitsi.videobridge.rest.jetty.ProxyServlet.pathSpec=/http-bind
org.jitsi.videobridge.rest.jetty.ProxyServlet.proxyTo=http://localhost:5280/http-bind
org.jitsi.videobridge.rest.jetty.ResourceHandler.resourceBase=/usr/share/jitsi-meet
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./config.js=/etc/jitsi/meet/bpvideo.xxxxx.it-config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./interface_config.js=/usr/share/jitsi-meet/interface_config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./logging_config.js=/usr/share/jitsi-meet/logging_config.js
org.jitsi.videobridge.rest.jetty.RewriteHandler.regex=^/([a-zA-Z0-9]+)$
org.jitsi.videobridge.rest.jetty.RewriteHandler.replacement=/
org.jitsi.videobridge.rest.jetty.SSIResourceHandler.paths=/
org.jitsi.videobridge.rest.jetty.tls.port=443
org.jitsi.videobridge.TCP_HARVESTER_PORT=4443
org.jitsi.videobridge.TCP_HARVESTER_MAPPED_PORT=443
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePath=/etc/jitsi/videobridge/bpvideo.xxxxx.it.jks
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePassword=changeit
org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS="local address"
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS="public address"

Someone can point me ?

**Comment by saghul** [comment]
Can you show the logs on the JavaScript console when the disconnect occurs?
