### ISSUE TITLE
Android JitsiMeetActivity Integration showing a blank screen 

### ISSUE THREAD

**Issue by FaizalMalik** [jitsi/jitsi-meet#3683]
## Description

I have used the 'https://github.com/jitsi/jitsi-meet/tree/master/android' for Integrating the Jitsi meet sdk. I have used the 'JitsiMeetActivity' (recommended approach in that doc )
---

## Current behavior

I created a sample app and after integrating the sdk , project build successfully and installed on phone successfully. but showing a blank screen.

*Used code *
import org.jitsi.meet.sdk.JitsiMeetActivity;

public class MainActivity extends JitsiMeetActivity {
}

---

**Comment by FaizalMalik** [comment]
@saghul  -When i use the JitsiMeet View implementation , I am getting an error - "Enclosing Activity must implement JitsiMeetActivityInterface".

**Comment by saghul** [comment]
We are making some changes to the Activity at the moment, so things are a hit in flux, sorry about that.

Use the view for now, I replied on the other issue.

**Comment by FaizalMalik** [comment]
@saghul  - thank you so much.

I also tried with the view and its throwing an error ' Enclosing Activity must implement JitsiMeetActivityInterface ' . Could. you please leave a comment here once you fix ? :)
