### ISSUE TITLE
Unable to build android using react-native

### ISSUE THREAD

**Issue by IdrishKha** [jitsi/jitsi-meet#3687]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Training\React-Native\jitsi-meet-master\android\build.gradle' line: 100

* What went wrong:
A problem occurred configuring project ':react-native-fast-image'.
> Could not find method android() for arguments [build_debn8t64tnrmxt1p04o0zmluc$_run_closure1$_closure9$_closure18@1a398e9e] on project ':react-native-fast-image' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by saghul** [comment]
Bohío ding on Windows is not supported, sorry.
