### ISSUE TITLE
Quick install (i.e., debian package) with existing certificates

### ISSUE THREAD

**Issue by joudinet** [jitsi/jitsi-meet#369]
Hi,
During the deb package configuration, I selected "Use existing certificates" and installed my certificate and private key into /etc/ssl/host.{crt,key} as recommended.
Still, at the end of the installation, I notice jitsi-meet generates an RSA private key in /var/lib/prosody:

```
Setting up jitsi-meet-prosody (1.0.701-1) ...
Generating a 4096 bit RSA private key
```

Is this option broken?

**Comment by bgrozev** [comment]
I don't think prosody's certificates are used anywhere. The ones you provided should be used by nginx (you can verify in /etc/nginx/sites-enables/your-domain.conf).

**Comment by joudinet** [comment]
Indeed, nginx configuration uses the correct certificates and I verified it from within jitmeet.
Still, I believe prosody's certificate should not be generated in this scenario. I let the issue open if you decide to fix it later, but it's fine to me if you decide to not fix it and close this issue anyway.
