### ISSUE TITLE
"session-initiate" error null

### ISSUE THREAD

**Issue by roy2651** [jitsi/jitsi-meet#3691]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---when I run my react-native app with lib-jitsi-meet，run 'react-native run-android’ in debug, console is '"session-initiate" error null', and ' Failed to accept incoming Jingle session '
js console:
E:\AwesomeProject\li…ills-browser.js:336 [JitsiConference.js] <>:  Failed to discover features of 0834@conference.meet.roy2651.cn/cb88e3f5 null
E:\AwesomeProject\no…ptionsManager.js:84 [modules/xmpp/JingleSessionPC.js] <>:  "session-initiate" error null
E:\AwesomeProject\no…ptionsManager.js:84 [JitsiConference.js] <>:  Failed to accept incoming Jingle session 
{reason: "timeout", session: "JingleSessionPC[p2p=false,initiator=false,sid=fqdecss27fnll]"}
2
E:\AwesomeProject\li…ills-browser.js:336 [modules/connectivity/ParticipantConnectionStatus.js] <e.value>:  figure out conn status - no participant for: cb88e3f5
E:\AwesomeProject\li…ills-browser.js:336 [modules/connectivity/ParticipantConnectionStatus.js] <e.value>:  figure out conn status - no participant for: cb88e3f5
E:\AwesomeProject\li…ills-browser.js:336 [modules/RTC/TraceablePeerConnection.js] <i._remoteTrackRemoved>:  TPC[2,p2p:false] Removed track not found for msid: 7Yx6SXYL8HXHCE9JxWHERaPuHucbhAgJK9pz-1,
             track id: e536e441-6a26-4e90-953e-262ddd33794d-1
E:\AwesomeProject\li…ills-browser.js:336 [JitsiConference.js] <e.sendMessage>:  Failed to send a ping request or response.
E:\AwesomeProject\li…ills-browser.js:336 [JitsiConference.js] <>:  Failed to discover features of 0834@conference.meet.roy2651.cn/cd1a4b8e null

jicofo log:
Jicofo 2018-12-17 07:40:38.355 INFO: [64] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: 0834@conference.meet.roy2651.cn
Jicofo 2018-12-17 07:40:38.381 INFO: [37] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@79298b63 member=ChatMember[0834@conference.meet.roy2651.cn/cd1a4b8e, jid: null]@1131234566]
Jicofo 2018-12-17 07:40:38.382 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member 0834@conference.meet.roy2651.cn/cd1a4b8e joined.
Jicofo 2018-12-17 07:40:38.383 INFO: [37] org.jitsi.impl.protocol.xmpp.colibri.OperationSetColibriConferenceImpl.createNewConference().81 Conference created: org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl@4c088747
Jicofo 2018-12-17 07:40:38.384 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Added participant jid= 0834@conference.meet.roy2651.cn/cd1a4b8e, bridge=jitsi-videobridge.meet.roy2651.cn
Jicofo 2018-12-17 07:40:38.384 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Region info, conference=ff913e octo_enabled= false: [[null, null]]
Jicofo 2018-12-17 07:40:38.384 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Added participant jid= 0834@conference.meet.roy2651.cn/4d19ccc1, bridge=jitsi-videobridge.meet.roy2651.cn
Jicofo 2018-12-17 07:40:38.385 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Region info, conference=ff913e octo_enabled= false: [[null, null, null]]
Jicofo 2018-12-17 07:40:38.386 INFO: [57] org.jitsi.jicofo.AbstractChannelAllocator.log() Using jitsi-videobridge.meet.roy2651.cn to allocate channels for: [Participant endpointId=4d19ccc1
Jicofo 2018-12-17 07:40:38.386 INFO: [99] org.jitsi.jicofo.AbstractChannelAllocator.log() Using jitsi-videobridge.meet.roy2651.cn to allocate channels for: [Participant endpointId=cd1a4b8e
Jicofo 2018-12-17 07:40:38.388 INFO: [40] org.jitsi.jicofo.Bridge.log() Adding 1 video streams on jitsi-videobridge.meet.roy2651.cn video streams: 0 diff: 1 (estimated: 1)
Jicofo 2018-12-17 07:40:38.391 INFO: [40] org.jitsi.jicofo.Bridge.log() Adding 3 video streams on jitsi-videobridge.meet.roy2651.cn video streams: 0 diff: 4 (estimated: 4)
Jicofo 2018-12-17 07:40:38.789 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Received session-accept from cd1a4b8e with accepted sources:Sources{ video: [ssrc=2041085238 ssrc=2831792026 ssrc=2017882030 ssrc=3563789222 ssrc=3146485952 ssrc=4043343877 ] }@594190300
Jicofo 2018-12-17 07:40:38.791 WARNING: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() No jingle session yet for 4d19ccc1
Jicofo 2018-12-17 07:40:48.941 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Received session-accept from 4d19ccc1 with accepted sources:Sources{ }@320486088
Jicofo 2018-12-17 07:40:48.943 INFO: [37] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.sendAddSourceIQ().476 Notify add SSRC 0834@conference.meet.roy2651.cn/cd1a4b8e SID: e3jd21np7qr9f Sources{ video: [] }@989202648 source_Groups{ }@852267646
Jicofo 2018-12-17 07:40:48.943 WARNING: [37] org.jitsi.jicofo.LipSyncHack.log() No corresponding audio found for: 0834@conference.meet.roy2651.cn/cd1a4b8e 'source-add' to: 0834@conference.meet.roy2651.cn/4d19ccc1
Jicofo 2018-12-17 07:40:48.943 WARNING: [37] org.jitsi.jicofo.LipSyncHack.log() No corresponding audio found for: 0834@conference.meet.roy2651.cn/cd1a4b8e 'source-add' to: 0834@conference.meet.roy2651.cn/4d19ccc1
Jicofo 2018-12-17 07:40:48.944 WARNING: [37] org.jitsi.jicofo.LipSyncHack.log() No corresponding audio found for: 0834@conference.meet.roy2651.cn/cd1a4b8e 'source-add' to: 0834@conference.meet.roy2651.cn/4d19ccc1
Jicofo 2018-12-17 07:40:48.945 WARNING: [37] org.jitsi.jicofo.LipSyncHack.log() No corresponding audio found for: 0834@conference.meet.roy2651.cn/cd1a4b8e 'source-add' to: 0834@conference.meet.roy2651.cn/4d19ccc1
Jicofo 2018-12-17 07:40:48.945 WARNING: [37] org.jitsi.jicofo.LipSyncHack.log() No corresponding audio found for: 0834@conference.meet.roy2651.cn/cd1a4b8e 'source-add' to: 0834@conference.meet.roy2651.cn/4d19ccc1
Jicofo 2018-12-17 07:40:48.945 WARNING: [37] org.jitsi.jicofo.LipSyncHack.log() No corresponding audio found for: 0834@conference.meet.roy2651.cn/cd1a4b8e 'source-add' to: 0834@conference.meet.roy2651.cn/4d19ccc1
Jicofo 2018-12-17 07:40:48.947 INFO: [37] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.sendAddSourceIQ().476 Notify add SSRC 0834@conference.meet.roy2651.cn/4d19ccc1 SID: 6ngugppsqredu Sources{ audio: [] video: [ssrc=2041085238 ssrc=2831792026 ssrc=2017882030 ssrc=3563789222 ssrc=3146485952 ssrc=4043343877 ] }@1160736644 source_Groups{ video:[ SourceGroup(FID)[ ssrc=2041085238 ssrc=2831792026 ]SourceGroup(FID)[ ssrc=2017882030 ssrc=3146485952 ]SourceGroup(FID)[ ssrc=3563789222 ssrc=4043343877 ]SourceGroup(SIM)[ ssrc=2041085238 ssrc=2017882030 ssrc=3563789222 ] ] }@119652755
Jicofo 2018-12-17 07:42:16.054 INFO: [37] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@79298b63 member=ChatMember[0834@conference.meet.roy2651.cn/cd1a4b8e, jid: null]@1131234566]
Jicofo 2018-12-17 07:42:16.054 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member 0834@conference.meet.roy2651.cn/cd1a4b8e is leaving
Jicofo 2018-12-17 07:42:16.054 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Terminating: 0834@conference.meet.roy2651.cn/cd1a4b8e
Jicofo 2018-12-17 07:42:16.055 INFO: [37] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.terminateSession().618 Terminate session: 0834@conference.meet.roy2651.cn/cd1a4b8e
Jicofo 2018-12-17 07:42:16.055 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removing 0834@conference.meet.roy2651.cn/cd1a4b8e sources Sources{ video: [ssrc=2041085238 ssrc=2831792026 ssrc=2017882030 ssrc=3563789222 ssrc=3146485952 ssrc=4043343877 ] }@228309351
Jicofo 2018-12-17 07:42:16.056 INFO: [37] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.sendRemoveSourceIQ().579 Notify remove SSRC 0834@conference.meet.roy2651.cn/4d19ccc1 SID: 6ngugppsqredu Sources{ video: [ssrc=2041085238 ssrc=2831792026 ssrc=2017882030 ssrc=3563789222 ssrc=3146485952 ssrc=4043343877 ] }@228309351 source_Groups{ video:[ SourceGroup(FID)[ ssrc=2041085238 ssrc=2831792026 ]SourceGroup(FID)[ ssrc=2017882030 ssrc=3146485952 ]SourceGroup(FID)[ ssrc=3563789222 ssrc=4043343877 ]SourceGroup(SIM)[ ssrc=2041085238 ssrc=2017882030 ssrc=3563789222 ] ] }@1527940552
Jicofo 2018-12-17 07:42:16.056 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Region info, conference=ff913e octo_enabled= false: [[null, null]]
Jicofo 2018-12-17 07:42:16.057 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Expiring channels for: 0834@conference.meet.roy2651.cn/cd1a4b8e
Jicofo 2018-12-17 07:42:16.059 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, 0834@conference.meet.roy2651.cn/cd1a4b8e
Jicofo 2018-12-17 07:42:16.060 INFO: [40] org.jitsi.jicofo.Bridge.log() Removing 3 video streams on jitsi-videobridge.meet.roy2651.cn video streams: 0 diff: 1 (estimated: 1)

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---android box
my git repo https://github.com/roy2651/react-native-lib-jitsi-meet

**Comment by saghul** [comment]
From the trimmed log it's not clear to me if joining the conference worked or not. We are not great at logging sometimes, so it may be inocuous. What behavior are you seeing?

**Comment by roy2651** [comment]
@saghul  when I run in debug model it will show this error, but when I run in relase it work ok.
I think it will be the xmpp's problem.
 Failed to accept incoming Jingle session timeout.
I will pay attention to this problem
