### ISSUE TITLE
[startmuted] Nobody can see video from Firefox 60 - 64 after unmute. 

### ISSUE THREAD

**Issue by webintoit** [jitsi/jitsi-meet#3700]
## Description
---
When firefox is starting muted and then activates device, nobody can see / hear media from it. 
Debug shows us that other browser can receive something from , but can not recognize that received track is belongs to ff. Sometimes 
## Current behavior
---
Not able to use current signaling with firefox 60+. Firefox user does not know about nobody view him. 
## Expected Behavior
Meet (ljm + jicofo + jvb ) works well with Firefox as like with  Chrome. 

## Possible Solution
Do not ignore `default` msid ?
Rethink ms ownership  signaling ? Do something.
## Steps to reproduce
---
1) join conference from Chrome and start media
2) open meet with ff with startmuted
https://meet.jit.si/fftests#config.startWithVideoMuted=true&config.startWithAudioMuted=true
Get luck, it is a lottery. 

# Environment details
---
FF 60  - 64 - is reproducible. 
Chrome - any
# related
https://github.com/jitsi/jitsi-meet/issues/2682
https://github.com/jitsi/jitsi-meet/issues/2646

**Comment by webintoit** [comment]
> Maybe related? [jitsi/lib-jitsi-meet#845](https://github.com/jitsi/lib-jitsi-meet/pull/845)

Tested this,  fix is work fine for Chrome 71 -><- Chrome 69. 
There was a very similar case, but firefox still unchanged.

**Comment by damencho** [comment]
Is the issue about Audio or Video? Audio should work with start audio muted, but video is a known thing and we are waiting for some fixes from @gpolitis

**Comment by webintoit** [comment]
Damian, you are right. There is normal audio from firefox. 
Tested with deployment: jicofo 444, jvb 1095, ljm 697. 
Chrome 71:
![image](https://user-images.githubusercontent.com/5518513/50176196-6f642800-0307-11e9-9e43-fd77ae8f5746.png)

Firefox 64:
![image](https://user-images.githubusercontent.com/5518513/50176388-e8fc1600-0307-11e9-9e1a-f5ebb57814ea.png)

**Comment by webintoit** [comment]
https://github.com/jitsi/lib-jitsi-meet/pull/845
Fixes Chrome 71, but partially. After page reload chrome 71 have same behavior as with Firefox.

**Comment by webintoit** [comment]
Is there any updates on it ?

**Comment by gpolitis** [comment]
@webintoit I'm sorry but I haven't been able to work on it, there was a bigger task that consumed all of my time. I was hoping I could find some time to address this as part of the bigger task but, unfortunately, I wasn't able to. So the fix for this will have to either wait more or somebody from the community will have to do the necessary work.

**Comment by webintoit** [comment]
Chrome 72 is reproducible now.

**Comment by saghul** [comment]
@webintoit I just joined https://meet.jit.si/saghul#config.startWithVideoMuted=true&config.startWithAudioMuted=true on Chrome 72 and my media is muted correctly. What steps are you following to validate this?

**Comment by webintoit** [comment]
@saghul, this is . issue with video signaling, make this to reproduce:
- join with Chrome, enable your camera. 
- join with startmuted chrome | enable camera. 
-- Chrome 1 will not recognize video from Chrome 2. 
P2P should be off. 
Other browsers can see Chrome 72  video only when Chrome is initiator and was enabled camera before any user joined. The same as with Firefox 60 - 64.

**Comment by damencho** [comment]
@webintoit I just tested this and it works for me. I open two tabs on meet.jit.si and add a third one using a similar link as the one Saul pasted above and enabling video on that browser and it worked, I can see the video on the other 2 participants. I was using chrome 72 for all participants and when joining third it will not use p2p.

**Comment by webintoit** [comment]
@damencho, yep, you are right , we are unable to reproduce it on jitsi-meet deployment, but able on local one. will find the reason. thanks.

**Comment by webintoit** [comment]
The issue is partially fixed with 
https://github.com/jitsi/jitsi-videobridge/pull/755
--
Sometimes `overwrite remote track`  error occurs after switching between camera and  screensharing.

**Comment by saghul** [comment]
@webintoit I don't understand. Was screen-sharing part of the equation on previous tests?

**Comment by webintoit** [comment]
Screensharing is just a `track replacement` here, it does not relate to this issue.  We have working FF, that can produce `remote track overwrite` behavior sometimes. Just my observation.
