### ISSUE TITLE
CPU usage high on audio only calls

### ISSUE THREAD

**Issue by edi9999** [jitsi/jitsi-meet#3705]
I just called with 6 participants (5 other participants + me), and after setting the call quality to audio only, jitsi was still using 300% of CPU.

I've recorded a Chrome Profile so that you can possibly investigate further.

[profile.zip](https://github.com/jitsi/jitsi-meet/files/2694201/profile.zip)

**Comment by saghul** [comment]
Just to clarify: your computer was running a single Jitsi Meet call, with no video at all. Correct?

**Comment by edi9999** [comment]
Yes, 1 minute before starting the CPU profile, I checked the option "Audio Only".

I had only a single Jitsi meet call at the same time.

**Comment by damencho** [comment]
Hey @edi9999 are you still experiencing the issue? If yes, can I ask you to create a profile for the cpu usage from the "JavaScript Profiler" tab in the developer tools? The profile you had provided can be loaded in the "Performance" tab which is a memory profiler.
