### ISSUE TITLE
ICE state is FAILED

### ISSUE THREAD

**Issue by joudinet** [jitsi/jitsi-meet#371]
Hi,
I have a running VM behind a NAT with jitmeet debian package installed.
I've added the following lines in /etc/jitsi/videobridge/sip-communicator.properties:
```
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<Public.IP.Address>
```

Still, jvb.log reports an error with ICE and audio/video is not working on jitmeet.
Any idea how to solve this?

**Comment by bgrozev** [comment]
Have you made sure that traffic to the public IP on the ports used by videobridge (TCP/443, TCP/4443, UDP 10000-20000) is routed to the machine with the bridge?

**Comment by joudinet** [comment]
Nope, I missed that information. I did the bridge for port 443 only. Thanks.
It could be a good idea to add this information there:
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#running-behind-nat

**Comment by bgrozev** [comment]
Added, thanks for the suggestion.
