### ISSUE TITLE
Enable support for Iceweasel (The Debian version of Firefox)

### ISSUE THREAD

**Issue by nickmdowson** [jitsi/jitsi-meet#372]
Hi,
I just went to meet.jit.si and it came up with: 

This application is currently only supported by
Chrome
DOWNLOAD
Chromium
DOWNLOAD
Opera
DOWNLOAD
Firefox
DOWNLOAD

However: I am currently using 'Iceweasel' which *is* Firefox: it's the rebranded version used in Debian Linux, which is kept identical, but rebranded so that Debian can apply it's own security updates.

I was wondering if you could add something into the software so it recognises Iceweasel as basically Firefox and works with that? (Actually, I think my browser might not be sufficiently up to date for this to work - does firefox support come in with version 40? - but I hope to use Jitsi Meet when it does).

Thanks for all the good work!
Nick

**Comment by gpolitis** [comment]
You're absolutely right Nick, it makes sense enabling Jitsi Meet for Iceweasel, thanks for bringing this up! Iceweasel >= 40 should work fine.

**Comment by nickmdowson** [comment]
Hi, This isn't entirely the same issue but i did notice that meet.jitsi.org tells anyone going to it that jitsi meet doesn't support firefox...don't know if this is in your area but might give some people the wrong idea!
Cheers

**Comment by damencho** [comment]
This instance is old and not updated, we will redirect it these days to the
correct one. Sorry.

**Comment by gpolitis** [comment]
I just installed Debian Jessie and it has Iceweasel 38 (usr) which is too old to work meet. Debian Sid and Stretch also have Iceweasel 38. Can somebody with "Debian experimental" please test if Iceweasel works with https://meet.jit.si/?

**Comment by nickmdowson** [comment]
I think I heard from someone who had iceweasel 40 and for whom it
worked. But I'm going to try and update my system in the next week or
two and test this myself. Thanks!
Nick

**Comment by gpolitis** [comment]
Nice, looking forward for your feedback! I'm suspecting that it would work, because in theory we're handling Iceweasel the same as Firefox, but in practice some things might be broken.

**Comment by nickmdowson** [comment]
Hi George,
I've just updated and tried it and it looks to me like it all works fine -
including the share screen option.
I was trying it on me own though so can't confirm 100% - if I get a chance
soon to use it with someone else I'll let you know if I have any problems!
Looks like a pretty sweet piece of software - nice work.
Nick

**Comment by gpolitis** [comment]
Hi Nick, this is great news, thanks very much for your testing and for your feedback. I will close this issue now and, if you find any new problems, you can either re-open it or create another issue for the specific problem that you're experiencing. Thank you.

**Comment by akuckartz** [comment]
:+1: Thanks!

**Comment by gpolitis** [comment]
I'm re-opening this issue because we should have version numbers in the supported browsers list, as per @ibauersachs suggestion.
