### ISSUE TITLE
ios : delegates not getting called

### ISSUE THREAD

**Issue by bhooshanpatil** [jitsi/jitsi-meet#3722]
Hello Everyone , 
i'm in the middle of creating SDK (ios framework ), i successfully addded  `JITSIMEET SDK` , but im not receiving jitsimeet `delegates` methods  like `conferenceLeft()` and all others like `conferenceJoined()` .. What im missing ? 

Thanx in advance 
CODE 👍 :
      `

           let jitsiMeetView = JitsiMeetView();

            jitsiMeetView.pictureInPictureEnabled = true;
            
            jitsiMeetView.delegate = self;

            jitsiMeetView.loadURLObject(["config": ["startWithAudioMuted": true, "startWithVideoMuted": false], "url": "*****"]);

            self.jitsiMeetView = jitsiMeetView;
            
            self.pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView);
            
            self.pipViewCoordinator?.configureAsStickyView(withParentView: UIViewController.view);
            
            jitsiMeetView.alpha = 0;
            
            self.pipViewCoordinator?.show();`

**Comment by bhooshanpatil** [comment]
Hey All , Solved it by making singleton of class

**Comment by calvinckho** [comment]
> Hey All , Solved it by making singleton of class

@bhooshanpatil I face the same issue of delegate not getting called. I wonder how you solved it using singleton of class? Can you share some code snippet?

**Comment by calvinckho** [comment]
For those looking for an answer, I am able to get it to work in swift using extension:

```
import Foundation
import UIKit
import JitsiMeet

public class JitsiMeetViewController: UIViewController {
    
    var jitsiMeetView: JitsiMeetView!
    var url: String = ""
    
    public override func viewDidLoad() {
        super.viewDidLoad()
    }

    public override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated);
        
        jitsiMeetView = view as? JitsiMeetView;
        jitsiMeetView?.delegate = self
        
        jitsiMeetView?.loadURLObject([
            "config": [
                "startWithAudioMuted": NSNumber(value: false),
                "startWithVideoMuted": NSNumber(value: false)
            ],
            "url": self.url
            ]);
    }
}

extension JitsiMeetViewController: JitsiMeetViewDelegate {
    @objc func conferenceJoined(_ data: [AnyHashable : Any]!) {
        print("[Jitsi Plugin Native iOS]: JitsiMeetViewController::conference joined");
    }
}
```

**Comment by bhooshanpatil** [comment]
Have you checked this [Link](https://github.com/jitsi/jitsi-meet/blob/master/ios/example-pip-app/src/ViewController.swift)

**Comment by venkatmacapp** [comment]
@bhooshanpatil  please give a code for conference users left delegate method and check the user is a modulator.
