### ISSUE TITLE
Unable to access camera on Chrome

### ISSUE THREAD

**Issue by brittkl** [jitsi/jitsi-meet#3732]
On my PC and using the latest Chrome, the video does not activate. Yet setting is set to allow. When I use FireFox using the same PC, the camera starts. When I use Jitsi meet via my Mac, using the latest Chrome, the camera works.

**Comment by damencho** [comment]
Are you testing meet.jit.si? Does it work on https://appr.tc?

For problems and questions use the community forum before opening issues.

**Comment by damencho** [comment]
I'm afraid this is a chrome issue and there is nothing we can do about it. You can try reporting it on the chromium bug tracker.

**Comment by brittkl** [comment]
Thanks - will do.

Any chance this is related to Chrome's recent autoplay policy? In that Jitsi Meet automatically starts with the video streaming?

**Comment by brittkl** [comment]
PS - The Chrome problem appears to be restricted to Chrome + **Windows 8**. When using Jitsi Meet on Chrome + Windows 7 or 10 it works fine, as well as Chrome via Mac (with no Windows).
