### ISSUE TITLE
Participant disconnected from room after stream error caused by unrelated participant

### ISSUE THREAD

**Issue by jayaddison** [jitsi/jitsi-meet#3734]
## Description
---
I'm using functionality from [webrtc-streamer](https://github.com/mpromonet/webrtc-streamer) to attempt to send an RTSP stream to an instance of `jitsi-meet` as a meeting participant; this is currently configured via one server which runs the conferencing, and another host which acts as a streaming bridge.

Appropriate CORS access is granted by the conference server to the streaming server so that it can connect via the Strophe XMPP library / BOSH.  Although I've configured all of this on dedicated hosts, it's reproducible using the [public jitsi-meet](https://meet.jit.si) and [xmppvideoroom demo](https://webrtc-streamer.herokuapp.com/xmppvideoroom.html)

## Current behavior
---
* Human participant creates a meeting room on `jitsi-meet.example.com` named `test`
* Operator initiates named stream `Example` from `streamer.example.com/xmppvideoroom.html` to server `jitsi-meet.example.com`, room `test`
* Human participant observes a participant named `Example` joining
* Human participant is disconnected from `streamer.example.com/test` room and shown attached disconnection message (see screenshot)

![disconnected](https://user-images.githubusercontent.com/406005/50407194-36083e00-0787-11e9-8a46-f6159d23e60f.png)

## Expected Behavior
---
* Human participant is not disconnected from meeting

## Possible Solution
---
This might be due to some kind of unhandled exception relating to badly formatted XML input - in particular the following warnings/errors/exceptions seem to appear in `jicofo.log` (attached; IPs and server names anonymized) around the time of the problem:

```
Jicofo 2018-12-24 18:13:47.218 WARNING: [28] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[focus@auth.subdomain.example.com/focus141966713991820] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: not-well-formed You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1060)
    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:994)
    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1010)
    at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-12-24 18:13:47.220 SEVERE: [28] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.connectionClosedOnError().651 XMPP connection closed on error: not-well-formed You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
```

[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2707788/jicofo.log)

Even if this is an unhandled exception, it seems like it's bad for the human client to be getting kicked out of a room as an error which seems to be the consequence of the streamer/machine client joining.

## Steps to reproduce
---
* Install jitsi-meet on a host
* Install webrtc-streamer on a host
* Create and join jitsi-meet channel via browser (reproduced in Firefox and Chromium)
* Begin stream from webrtc-streamer via xmppvideoroom.html

# Environment details
---
* [os](http://releases.ubuntu.com/18.04/): `18.04.1 LTS (Bionic Beaver)`
* [jitsi-meet](https://download.jitsi.org/unstable/jitsi-meet_1.0.3444-1_all.deb): `1.0.3444-1 (nightly)`
* [webrtc-streamer](https://github.com/mpromonet/webrtc-streamer/commit/b344d83a48a1b23f9e155f50334bc16849c93230): `b344d83`
* [mozilla-firefox](https://www.mozilla.org/en-US/firefox/61.0.1/releasenotes/): `61.0.1`
* [chromium-browser](https://chromium.googlesource.com/chromium/src/+/67.0.3396.99): `67.0.3396.99`

**Comment by damencho** [comment]
Your logs show that focus connection drops and this is considered a fatal error in a conference, there is no one to control the conference, so a reload is triggered to all participants. Normally in such case the shard with faulty signaling node will be marked unhealthy and with reload all participants will land on a healthy shard.

If you can get the xmpp traffic that makes jicofo fail, that will be interesting.

**Comment by jayaddison** [comment]
@damencho @paweldomas Thanks for the recommendations and analysis; I've verified this locally and confirmed that adjusting the way that `webrtc-streamer` encodes the `/api/call` parameters allows the client to join the room without booting out other web-based participants.  I've notified the author of that and opened a temporary workaround ( https://github.com/mpromonet/webrtc-streamer-html/pull/1 )

For future reference, the XML fragments from the logs can be validated using `xmllint`, like so:

```
$ xmllint packet.xml 
packet.xml:45: parser error : EntityRef: expecting ';'
value='VirginiaTech||rtptransport=tcp&timeout=60 VirginiaTech_video' name='msid'
```

@damencho @paweldomas should I leave this issue open to track more resilient XML-validation handling?  (I can rename the issue title if that's useful)

**Comment by jayaddison** [comment]
Thanks @damencho; done.  I've linked to here for most of the environment/reproduction issues and background, but can copy those across if needed.
