### ISSUE TITLE
Can't see each other, but can see oneself

### ISSUE THREAD

**Issue by JustinTQ** [jitsi/jitsi-meet#3735]
![image](https://user-images.githubusercontent.com/20768697/50409392-39ee9b80-082d-11e9-8e56-a03d6e523bd8.png)
![image](https://user-images.githubusercontent.com/20768697/50409395-4246d680-082d-11e9-8dac-d4f680df8216.png)
![image](https://user-images.githubusercontent.com/20768697/50409400-4f63c580-082d-11e9-8d2a-74ae798e1ae8.png)

**Comment by nhutcorp** [comment]
I your problem is same with this issue
https://github.com/jitsi/jitsi-meet/issues/267

Solution is:
> open ports incoming ports
> https and 10000-20000

**Comment by JustinTQ** [comment]
I've closed the firewall.

**Comment by saghul** [comment]
Looks like your videobridge cannot connect to your XMPP server because the cert is not installed. You can disable this validation by adding this to your sip-communicator.properties file:

`org.jitsi.videobridge.xmpp.user.shard.DISABLE_CERTIFICATE_VERIFICATION=true`

**Comment by shisg1002** [comment]
> Looks like your videobridge cannot connect to your XMPP server because the cert is not installed. You can disable this validation by adding this to your sip-communicator.properties file:
> 
> `org.jitsi.videobridge.xmpp.user.shard.DISABLE_CERTIFICATE_VERIFICATION=true`

Finally，I fix it,  even though I didn't understand the principle  ! Thans  a lot ! :p
**keytool –importcert -alias jitsi.test.com -keystore ../cacerts -storepass changeit -file jitsi.test.com.crt**
