### ISSUE TITLE
Client Change Language

### ISSUE THREAD

**Issue by zhanghuiDev** [jitsi/jitsi-meet#3736]
![1a679929ca0b0111eb812bb12bc26f21](https://user-images.githubusercontent.com/20181773/50440837-e5cddf00-0932-11e9-910a-0b1cc923e1f1.jpg)

Hello, how can I change the default language of the client?

**Comment by virtuacoplenny** [comment]
I believe the mobile client uses the device language, so if your device is set to English then it displays English by default. I'm assuming your device is already set to the language you want displayed in the app but it's not displaying. It might be related to an existing issue: https://github.com/jitsi/jitsi-meet/pull/3627/files.

**Comment by zhanghuiDev** [comment]
![image](https://user-images.githubusercontent.com/20181773/50462047-b44e2580-09bd-11e9-9411-a5e4afbdd1b4.png)

How can there be only one change?

**Comment by zhanghuiDev** [comment]
How can I change the text above?

**Comment by zhanghuiDev** [comment]
Where to modify? Thank you

**Comment by virtuacoplenny** [comment]
Translations can be added from https://translate.jitsi.org/. After translations have been added there, updating translation files within jitsi-meet is a manual process someone on the team will have to do. The last time an update happened is on November 13. https://github.com/jitsi/jitsi-meet/commit/216782d60690359a380db91cafdd49d96932a0f4. Once the translations are in jitsi-meet, and a new version has been made available, you’d have to update your jitsi-meet app.

**Comment by savagejet** [comment]
> 
> 
> How can I change the text above?

解决了吗？
