### ISSUE TITLE
JWT: password required problem

### ISSUE THREAD

**Issue by vortecsone** [jitsi/jitsi-meet#3741]
I'm working in an Android app with Jitsi Meet SDK and when I add the token in URL, the app shows a dialog titled "Password required" asking for user and password to enter the room. I don't understand what kind of authentication I need. 
I'm using these parameters:

{
  "context": {
    "user": {
      "avatar": "https:/gravatar.com/avatar/abc123",
      "name": "John Doe",
      "email": "jdoe@example.com",
      "id": "abcd:a1b2c3-d4e5f6-0abc1-23de-abcdef01fedcba"
    },
    "group": "a123-123-456-789"
  },
  "iss": "com.example.root.jitsialinali",
  "sub": "meet.jit.si",
  "room": "*"
}

The signature is verified when I test it in https://jwt.io/#libraries-io

I only had modified the gradle configurations of the project for import the JitsiSDK and then I wrote the code for start a call in the onCreate Method. What I need for authenticate the token and enter the room ?

**Comment by rananajam1** [comment]
Facing the same issue can you help me out @vortecsone 
![Screenshot_1596740719](https://user-images.githubusercontent.com/51153575/89699088-30507380-d93e-11ea-81da-d371b1534f04.png)

**Comment by askarimov** [comment]
Hi @vortecsone, were you able to fix this issue?
