### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by shisg1002** [jitsi/jitsi-meet#3742]
Hello, I clone the source, and install many dependence, but "npm install" return err. How to do with this err?

**env:
Centos 7, Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost test.jitsi]# node -v
v8.10.0
[root@localhost test.jitsi]# npm -v
6.5.0
[root@localhost test.jitsi]# git log --oneline -1
f1ca2cac (HEAD -> master, tag: jitsi-meet_3444, tag: 3137, origin/master, origin/HEAD) build: fix setting webpack mode**

[root@localhost test.jitsi]# npm install 

> git-validate@2.2.2 install /home/software/test.jitsi/node_modules/git-validate
> node bin/install

> precommit-hook@3.0.0 install /home/software/test.jitsi/node_modules/precommit-hook
> node bin/install

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/software/test.jitsi/.jshintrc'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.internals.copyFile (/home/software/test.jitsi/node_modules/git-validate/lib/utils.js:117:8)
    at Object.internals.copy (/home/software/test.jitsi/node_modules/git-validate/lib/utils.js:77:26)
    at Object.exports.copy (/home/software/test.jitsi/node_modules/git-validate/lib/utils.js:66:22)
    at Object.<anonymous> (/home/software/test.jitsi/node_modules/precommit-hook/bin/install:5:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm WARN @atlaskit/flag@6.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/icon@7.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react-dom@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/layer@2.9.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expose-loader@0.7.4 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN string-replace-loader@1.3.0 requires a peer of webpack@1 || 2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! precommit-hook@3.0.0 install: `node bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the precommit-hook@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-28T07_19_25_069Z-debug.log

**Comment by saghul** [comment]
Why are you installing in a user directory as root?

**Comment by shisg1002** [comment]
> Why are you installing in a user directory as root?

emmmm, is that the prob ? I always use root to do anything

**Comment by shisg1002** [comment]
> Why are you installing in a user directory as root?

I find a way from other questions, 
first :npm install lib-jitsi-meet --force && make deploy-lib-jitsi-meet, than npm install.

[root@localhost test.jitsi]# npm install 
npm WARN @atlaskit/flag@6.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/icon@7.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react-dom@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/layer@2.9.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expose-loader@0.7.4 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN string-replace-loader@1.3.0 requires a peer of webpack@1 || 2 || 3 but none is installed. You must install peer dependencies yourself.

added 1 package and audited 31411 packages in 40.669s
found 2 vulnerabilities (1 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[root@localhost test.jitsi]# npm audit fix
npm WARN @atlaskit/flag@6.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/icon@7.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react-dom@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/layer@2.9.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expose-loader@0.7.4 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN string-replace-loader@1.3.0 requires a peer of webpack@1 || 2 || 3 but none is installed. You must install peer dependencies yourself.

removed 1 package and updated 4 packages in 20.916s
fixed 2 of 2 vulnerabilities in 31411 scanned packages

**Now, I'm running make. but it sames that the node thread has status D! I really don't know how to do.**
[root@localhost test.jitsi]# make
./node_modules/.bin/webpack -p
                                                                                                                                                            
 13653 root      20   0 2192976 597816    256 D   9.1 60.0   1:50.18 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 618852    304 D  11.8 62.1   1:50.54 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 656852    288 R  12.8 66.0   1:50.93 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 678964    284 D   8.3 68.2   1:51.18 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 671776    284 R  10.3 67.5   1:51.49 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 626204    432 D   8.3 62.9   1:51.74 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 650216    204 D  10.4 65.3   1:52.06 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 638052    236 D   8.2 64.1   1:52.31 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 661808    244 D   9.9 66.5   1:52.61 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 663836    244 D  10.3 66.7   1:52.92 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 661092    108 D   8.6 66.4   1:53.18 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 667148    108 D   9.8 67.0   1:53.48 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 658912    236 D  12.1 66.2   1:53.86 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 657408    256 D   8.4 66.0   1:54.12 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 655976    272 D   8.9 65.9   1:54.39 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 649084    272 D  13.9 65.2   1:54.81 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 667024    272 D  10.0 67.0   1:55.11 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 630804     52 D   9.0 63.3   1:55.43 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 662512    276 D   9.2 66.5   1:55.72 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 672124    128 D  12.2 67.5   1:56.09 node                                                                                                                                                                                                    
 13653 root      20   0 2192976 640356      0 D   9.8 64.3   1:56.40 node                                                                                                                                                                                                    
 13653 root      20   0 2106916 654428    576 D  11.8 65.7   1:56.77 node                                                                                                                                                                                                    
 13653 root      20   0 2118180 678976    940 D  24.0 68.2   1:57.51 node                                                                                                                                                                                                    
 13653 root      20   0 2118180 673760    100 D  20.0 67.7   1:58.15 node

**Comment by shisg1002** [comment]
It just stall on "./node_modules/.bin/webpack -p", Should I waiting for it?

[root@localhost test.jitsi]# make
./node_modules/.bin/webpack -p

**Comment by saghul** [comment]
Ok. Let's do this. Delete that directory. Entirely. Let's start fresh.

Do not use root. There is no need for it and it will just create problems. Case in point (from your first post):

> Error: EACCES: permission denied, open '/home/software/test.jitsi/.jshintrc'

As a user, run (on a fresh repo clone):

```
npm install
```

After it finishes, run:

```
make
```

That will build the frontend code. Note that you need the rest of the intrastructure components, and a webserver to put the frontent on. Alternatively you can use the builtin development web server to test it out, run this instead of the above step:

```
make dev
```

**Comment by shisg1002** [comment]
It really works!  I'm running make now,  hope I can succeed at one time!
Thanks a lot !!!!!

[shisg@localhost jitsi-meet-master]$ npm install

> git-validate@2.2.2 install /home/software/jitsi-meet-master/node_modules/git-validate
> node bin/install

WARNING: Unable to find a .git directory for this project, installation aborted.

> node-sass@4.10.0 install /home/software/jitsi-meet-master/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /home/software/jitsi-meet-master/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/shisg/.npm/node-sass/4.10.0/linux-x64-57_binding.node

> precommit-hook@3.0.0 install /home/software/jitsi-meet-master/node_modules/precommit-hook
> node bin/install


> styled-components@3.4.9 postinstall /home/software/jitsi-meet-master/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components

> lib-jitsi-meet@github:jitsi/lib-jitsi-meet#7ecead1ac01d07c300675789f66c47a07b0fb187 postinstall /home/software/jitsi-meet-master/node_modules/lib-jitsi-meet
> webpack -p

[BABEL] Note: The code generator has deoptimised the styling of /home/software/jitsi-meet-master/node_modules/react-native-callstats/callstats.js as it exceeds the max of 500KB.
Hash: 2d9f6897c7303bbedac3
Version: webpack 4.26.1
Child
    Hash: 2d9f6897c7303bbedac3
    Time: 53590ms
    Built at: 2018-12-28 17:14:19
                     Asset      Size  Chunks                    Chunk Names
     lib-jitsi-meet.min.js  1.01 MiB       0  [emitted]  [big]  lib-jitsi-meet
    lib-jitsi-meet.min.map  3.66 MiB       0  [emitted]         lib-jitsi-meet
    Entrypoint lib-jitsi-meet [big] = lib-jitsi-meet.min.js lib-jitsi-meet.min.map
      [2] ./JitsiConferenceEvents.js 8.21 KiB {0} [built]
      [3] ./modules/browser/index.js 98 bytes {0} [built]
      [4] ../jitsi-meet-logger/lib/index.js 3.6 KiB {0} [built]
      [6] ./modules/statistics/statistics.js 27.9 KiB {0} [built]
      [7] ./service/statistics/AnalyticsEvents.js 15 KiB {0} [built]
      [9] ./service/RTC/MediaType.js 110 bytes {0} [built]
     [10] ./modules/util/GlobalOnErrorHandler.js 2.37 KiB {0} [built]
     [12] ./JitsiTrackErrors.js 2.68 KiB {0} [built]
     [13] ./modules/RTC/RTC.js 34 KiB {0} [built]
     [15] ./JitsiTrackError.js 6.07 KiB {0} [built]
     [17] ./JitsiTrackEvents.js 1.31 KiB {0} [built]
     [20] ./modules/videosipgw/VideoSIPGWConstants.js 1.44 KiB {0} [built]
     [21] ./JitsiConferenceErrors.js 2.12 KiB {0} [built]
    [117] ./index.js 160 bytes {0} [built]
    [118] ./JitsiMeetJS.js 18.9 KiB {0} [built]
        + 138 hidden modules
    
    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      lib-jitsi-meet.min.js (1.01 MiB)
    
    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      lib-jitsi-meet (1.01 MiB)
          lib-jitsi-meet.min.js
    
    
    WARNING in webpack performance recommendations: 
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/

> node-sass@4.10.0 postinstall /home/software/jitsi-meet-master/node_modules/node-sass
> node scripts/build.js

Binary found at /home/software/jitsi-meet-master/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1778 packages from 959 contributors and audited 31413 packages in 260.954s
found 2 vulnerabilities (1 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[shisg@localhost jitsi-meet-master]$ npm audit fix
npm WARN @atlaskit/flag@6.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/icon@7.1.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react-dom@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/layer@2.9.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@1.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expose-loader@0.7.4 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN string-replace-loader@1.3.0 requires a peer of webpack@1 || 2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 1 package and updated 4 packages in 21.735s
fixed 2 of 2 vulnerabilities in 31413 scanned packages
[shisg@localhost jitsi-meet-master]$ make
./node_modules/.bin/webpack -p
