### ISSUE TITLE
Jitsi Meet problem with realm

### ISSUE THREAD

**Issue by saadqbal** [jitsi/jitsi-meet#3748]
when I apply all the steps mentioned in the readme, I start getting the below realm error. Realm works fine otherwise.

2018-12-28 16:22:34.504 [error][tid:main][RCTModuleData.mm:179] Realm has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method.

"react-native": "0.57.8",
"realm": "^2.19.1"

realm works fine if I remove the library.

And the library works fine without realm. I have checked myself but a colleague told me it does the same with firebase as well.

**Comment by saghul** [comment]
Honestly, I have no idea. 

> when I apply all the steps mentioned in the readme

What steps exactly?



> realm works fine if I remove the library.
> 
> And the library works fine without realm. I have checked myself but a colleague told me it does the same with firebase as well.

What library?

You'll need to add more details here. I have no idea about what you are trying to do.

**Comment by saadqbal** [comment]
Hey @saghul Thank you for looking into this.

I integrated Jitsi-meet following [these instructions](https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md). 
I also set the "**Always Embed Swift Standard Libraries**" to **YES** as without it Jisti-meet does not work.

After this when I run the app, it shows the following realm error:
`2018-12-28 16:22:34.504 [error][tid:main][RCTModuleData.mm:179] Realm has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method.`

Realm works fine if I remove Jisti-meet with or without setting the  "**Always Embed Swift Standard Libraries**" to **YES**.

**Comment by saadqbal** [comment]
I have posted a detailed explanation of the issue on realm repo  [https://github.com/realm/realm-js/issues/2193](#2193).

**Comment by saghul** [comment]
You haven't mentioned that you are using react-native-jitsi-meet. Despite it's name, we are not maintaining that package, so you may want to reach out to the developer of that package instead.

**Comment by saadqbal** [comment]
I Metioned that library for instructions on setting up JitsiMeet as there are steps that are not mentioned in JitsiMeet offical repo and they are required. e.g  setting the "**Always Embed Swift Standard Libraries**" to **YES**. . The error starts to show up the moment I add the JitsiMeet.framework.

@saghul Just try to add JitsiMeet into the app with realm configured. You will get the error.

**Comment by djorkaeffalexandre** [comment]
@saghul I followed this steps: https://github.com/jitsi/jitsi-meet-ios-sdk-releases/blob/master/README.md
and have same error with Realm.

**Comment by saghul** [comment]
Do you have a small repository that can reproduce the issue?
