### ISSUE TITLE
jitsi recording not available

### ISSUE THREAD

**Issue by tkoller1** [jitsi/jitsi-meet#3749]
Hello,
after installation of jitsi-meet as per video instruction (Ubuntu 18.04 desktop, Intel NUC Intel® Core™ i5-4250U CPU @ 1.30GHz × 4, 8GB Ram 0,5 TB SSD) jitsi-meet runs smooth. Installation of JIBRI causes some effort on another INTEL NUC ( Intel® Core™ i5-5250U Prozessor 8GB Ram 2x 1TB SSD) and after several unsuccessful installation attemps finally jibri startet as per the youtube video. However, after the button to confirm recording is clicked, the error message "Aufnahme nicht verfügbar" recording not available appears. On the jibri machine the /var/log/jitsi remains empty. Find the truncated logs from the jitsi-meetings machine enclosed. 

Enabling "local recording = true"  causes a blank grey screen 
Please note, that I only today was able to successful install the jibri server, so the unnecessary parts of the log files are not included. 
Thank you in advance for your kind support.
Best regards Toni Koller

[jitsilogs.txt](https://github.com/jitsi/jitsi-meet/files/2717381/jitsilogs.txt)

**Comment by damencho** [comment]
There are no jibris available as you can see on the last line of your jicofo logs. On the jibri machine, you can check the logs under /var/log/jitsi/jibri and see what is the problem.

When you have questions and problem use the community forum before opening issues here.
