### ISSUE TITLE
Automatic video change

### ISSUE THREAD

**Issue by subtildreams** [jitsi/jitsi-meet#375]
Hi
when we click on a participant nickname (in the participant list) we can see his webcam.

It will be nice to have a button to come back to an automatic video change (when dominant speacker change)

And not stay on a particular webcam

Thank you

**Comment by bgrozev** [comment]
> when we click on a participant nickname (in the participant list) we can see his webcam.
> 
> It will be nice to have a button to come back to an automatic video change (when dominant speacker change)

This is supposed to happen when you click on the small video again (you will notice the "pinned" video has a blue aura, which disappears when you click it again). Does it not work for you?

**Comment by subtildreams** [comment]
Hi thank you, yes it workes i did not know. It's nice

Maybe it can be nice to add automatic mode button at the bottom of the participants list or an information that said you are currently watching "nickname" camera click here for automatic mode?
