### ISSUE TITLE
Random Call Disconnection

### ISSUE THREAD

**Issue by rptwsthi** [jitsi/jitsi-meet#3750]
## Description
While on video/audio call is active (on android mobile device using jitsi framework) system get these errors randomly, or may be I could not figure the patterns. 

**Error1:**
> Failed to accept incoming P2P Jingle session', { reason: 'timeout',
                   session: 'JingleSessionPC[p2p=true,initiator=false,sid

**Error2:**
> 'Failed to accept incoming Jingle session', { code: '',
                                                                     reason: 'item-not-found',
                                                                     msg: 'No participant found for: gosessionroom1545982702032@conference.hello.***.in/0fc38bfe',
                                                                     session: 'JingleSessionPC[p2p=false,initiator=false,sid=6d89i1jcm3g23]' }

## Current behavior
These issues occurs during first couple of minutes, if that time frame is passed it will call will remain steady rest of the time.
After above error get raised, withing 10 to 15 seconds call get disconnected.

## Expected Behavior
System sholdn't be getting these error randomly there must be some pattern (which may be I am missing), so I can debug and rectify.

## Possible Solution
I am not sure.

## Steps to reproduce
* Connect the call (let me know if you need my server system information)
* Withing 1-2 minute above error will trigger
* After 10-15 sec after error have raised call will automatically get disconnected

# Environment details
Mobile: Samsung J2 Pro
OS: Android 6.0.1
Jitsi Meet SDK

Mobile: Moto G 1st Gen
OS: Android 5.0.1
Jitsi Meet SDK

**Comment by Rman-m** [comment]
i have same problem

**Comment by vivekwegile** [comment]
[features/base/dialog] No reload reason defined!
[modules/xmpp/xmpp.js] XMPP connection dropped!
[features/base/conference] JWT error: connection-dropped-error
[modules/xmpp/strophe.ping.js] Ping timeout null
[modules/xmpp/strophe.util.js] Strophe: request id 110.1 error 0 happened

Some time getting this . and call disconnect automatically

Any Idea/suggestions to solve it?
