### ISSUE TITLE
jigasi broken on clean install?

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3751]
Just did a clean install on Debian Stretch using your latest unstable packages.

Everything seems to work fine except now I can no longer call out through jigasi (used to work before I updated everything). I'm able to ring the SIP number and answer, but there's no audio going through.

It seems there's maybe some problem with java (I'm using jdk 1.8 as recommended) and sockets?

 Failed to send a packet to target /2a01:4f8:c0c:21f:0:0:0:2:11682:java.io.IOException: No active socket.

Here are the server side logs
[jigasi.txt](https://github.com/jitsi/jitsi-meet/files/2718869/jigasi.txt)
[jvb.txt](https://github.com/jitsi/jitsi-meet/files/2718870/jvb.txt)
[jicofo.txt](https://github.com/jitsi/jitsi-meet/files/2718871/jicofo.txt)

Any help much appreciated.

P.S. Happy New Year everyone!

**Comment by pdarcos** [comment]
I believe the problem may have something to do with rtcpmux.

Where can I disable it to test out my theory?

Thanks

**Comment by saghul** [comment]
ping @damencho

**Comment by pdarcos** [comment]
@damencho can you help? I don't remember in which sip communicator properties file I turn off rtcpmux

**Comment by damencho** [comment]
Jigasi needs ports udp 10000-20000, cannot use the single-port udp 10000, nothing to disable/enable.

**Comment by damencho** [comment]
It is not supported by jigasi.

**Comment by pdarcos** [comment]
Yes, I know jigasi doesn't support it which is why I suspect there's a compatibility problem since jvb is using it.
Isn't there some property in the jvb sip.com.properties file I can use to disable it in jvb too to see if jigasi calls start working again?

**Comment by pdarcos** [comment]
I'm going to go ahead and close this ticket now since jigasi started working again all of a sudden.

Not sure what the exact problem was but it seems OK now.

Thanks for your help guys!
