### ISSUE TITLE
Android App Permissions Prompt / Home Buttons Glitching & Flashing

### ISSUE THREAD

**Issue by meetinglink** [jitsi/jitsi-meet#3752]
## Description
I was building the jitsi-meet app as a test, and it works fine in a Pixel 2 virtual device.  However, when I copy it to my Galaxy S8 Plus, I experience some weirdness when starting a call.

To be clear, this happens with the Jitsi Meet app as currently published on the Play Store as well.

When I enter a room name and hit join, it loads the conference screen and the "Allow to use camera" "Allow to use microphone" prompts appear.  Before I have the chance to click "Allow" or "Deny", the the home screen bar on the bottom of the phone starts appearing disappearing quickly, sliding up from the bottom.  The permissions prompt starts moving up and down, as if it's getting pushed by the home screen bar at the bottom of the phone.  

https://www.youtube.com/watch?v=kXUU8BBedQs

Here's a 13 second recording of what it's doing.  The permission prompt isn't moving up and down as much as it usually does, I suspect because of the recording app.  You can see it at the beginning and after the 6 second mark as well.

## Current behavior
Permissions prompt and menu bar slide up and down repeatedly on the screen until you "Allow" or "Deny"

## Expected Behavior
I'd expect the permissions prompt and "home screen menu" bar to remain static.

## Steps to reproduce
For me it happens on a fresh install of jitsi-meet with no permissions granted to the app.

**Note**
This only happens if the "home button menu bar" is static, rather auto hiding.  I'm unclear if this is a Samsung feature or an Android 8 feature.  What I'm referring to is, the menu bar has a "dot" at the far left.  You can double click it to toggle between auto hide and always showing.  This issue only happens when the bar is auto hiding (the dot is just an outline with no fill).

![Image of the button](http://i.imgur.com/daC6hN5.jpg)

# Environment details
Galaxy s8 Plus
Android Version: 8.0.0
Samsung Experience Version: 9.0

**Comment by meetinglink** [comment]
I've confirmed that this is happening within Samsung Test Lab as well with these settings: Galaxy S8+ / SM-G955F-KR2 in Korea

**Comment by saghul** [comment]
Just to confirm: this only happens once, after you accept the permissions it goes away, right?

This is kind-of a known issue which we haven't figured out how to fix yet, IIRC.

**Comment by meetinglink** [comment]
Correct, @saghul. No worries! I couldn't find an issue for it or any mention of anything similar so I thought I'd create an issue.

I think Samsung calls these "Full Screen Apps" or maybe "Immersive Mode" and it's part of their "Full Screen Experience".

Maybe this will help narrow down a fix:

I just noticed that there is a page in my Android Settings called "Full Screen Apps". It lists everything installed on my phone with a toggle switch next to it allowing you to enable or disable full screen mode.

There are a few apps like Google Authenticator and Chase Banking that say "This app may not work correctly in full screen mode" and the toggle switch is off.

https://i.imgur.com/B243sNg.jpg

If I disable full screen on the Jitsi app it behaves properly.  However, it has an extra portion that says "tap here to fill entire screen". When you click it, the app "refreshes" and loads in full screen mode. The toggle switch in Full Screen Apps turns to the On position as well.

In Google Authenticator, when you click the "Tap here to fill entire screen" box it attempts to reload the app full screen but displays this message:  https://i.imgur.com/q9j4KS3.jpg

Once you hit OK, it reloads in full screen mode and changes the toggle switch in full screen apps.

Unclear for the time being if you can force an app to run in non-immersive mode and suppress the "tap here to fill entire screen" message.

**Comment by saghul** [comment]
The problem is that we try to go full-screen when in a conference, but at the same time, get out of it when the permissions dialog is shown, so they "fight".

This is a bug on our side and one we will eventually fix. Thanks for your thorough analysis!

**Comment by saghul** [comment]
Keep open.

**Comment by saghul** [comment]
We actually fixed this one! Version 19.2 is now rolling out.
