### ISSUE TITLE
iOS Problems after Successful Reduction of Picture in picture

### ISSUE THREAD

**Issue by WSX1994** [jitsi/jitsi-meet#3756]
Hello, I would like to ask a question about iOS. When I enter the picture-in-picture, the screen will shrink, but the picture-in-picture will have a black background that does not belong to itself.I slide on the black background, but it will not affect the picture-in-picture, but will affect my superior page.

**Comment by saghul** [comment]
Can you share a screenshot?

**Comment by saghul** [comment]
Or a video.

**Comment by WSX1994** [comment]
@saghul ，hello，The yellow background of this picture is a normal picture-in-picture, and the black one doesn't know why it exists.  [wechatimg33](https://user-images.githubusercontent.com/33861158/50584585-651b5f80-0eab-11e9-9a05-7ea94e883aa2.jpeg)

**Comment by saghul** [comment]
I have no idea 😮  Maybe use Xcode's view inspector to see what view it is.

**Comment by WSX1994** [comment]
@saghul   hi， I added views to kewindow, so I couldn't see hierarchical drawings, and I don't understand why there are more areas that don't belong to painted areas when they are reduced to painted areas.

**Comment by WSX1994** [comment]
@saghul  hello，This hierarchy is an extra one. Why is it automatically higher in rctview when I shrink? The place where I draw the red line is the part that is higher when I enter the painting?
<img width="921" alt="wechatimg9" src="https://user-images.githubusercontent.com/33861158/50626419-116f4b80-0f69-11e9-9c88-6987baf68af5.png">

**Comment by saghul** [comment]
> Excuse me, it's useful to draw in this picture that I run in the demo of the source code, and the hierarchy diagram is right.

Ok, that's good to know.



> But when I drag the framework into the project after integration, I see the hierarchy diagram and find that it's the problem of rctview. Is it true that after the integration of the framework, there is no treatment there? How do I deal with the problem here?

Hum. We don't do anything special there. I can only suggest trying to replicate what the demo does as much as possible, but otherwise I'm afraid I have nothing else I can suggest, sorry.

**Comment by WSX1994** [comment]
@saghul ，thank you，Can you tell me which way to change the height of the video in rctview?

**Comment by saghul** [comment]
The RCTView takes the entirety of the encosing JitsiMeetView. There is no way to change it other than manually taking the subview off the JitsiMeetView.

**Comment by WSX1994** [comment]
@saghul The three high views I see in the hierarchy diagram are rctview - > rctview - > rtcvideoview, which you have ideas about how to change from rctview, because the only difference between demo and demo is that demo is written directly from source code, and the project is written by integrated framework.

**Comment by WSX1994** [comment]
@saghul The three higher views I see in the hierarchy diagram are rctview - > rctview - > rtcvideoview, which you have ideas about how to change from rctview, because the only difference between project and demo is that demo is written directly from source code and in project is written by integrated framework.

**Comment by saghul** [comment]
There is no way to change that, since the RTCVideoView is created in JavaScript, by React Native.

The project also uses the framework, the only difference is that they are built together, but other than that, they should be the same.

Have you build the framework yourself? From current master?

**Comment by saghul** [comment]
Where did you get the framework from, CocoaPods?

**Comment by WSX1994** [comment]
@saghul Framework integration through terminals

**Comment by saghul** [comment]
I don't know what you mean. Did you build it or not?

**Comment by WSX1994** [comment]
@saghul I downloaded it from GitHub

**Comment by saghul** [comment]
From here? https://github.com/jitsi/jitsi-meet-ios-sdk-releases

**Comment by WSX1994** [comment]
@saghul I downloaded https://github.com/jitsi/jitsi-meet from here, then downloaded and installed the react-native environment, then proceeded to cocopods, and then proceeded to operate according to the instructions of the api.

**Comment by saghul** [comment]
Ok, so you built it yourself then. In that case, you are running the same code as the demo app, so I don't know why it's not working properly :-/

**Comment by WSX1994** [comment]
@saghul thank you，I know，I try other methods
