### ISSUE TITLE
Unable to install on Debian server

### ISSUE THREAD

**Issue by SanalkumarQuiits** [jitsi/jitsi-meet#3757]
I am trying to install Jitsi-meet in Debian server.
I am getting the following errors while running 'apt-get -y install jitsi-meet'

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-videobridge (= 1096-1) but it is not going to be installed
              Depends: jicofo (= 1.0-444-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by damencho** [comment]
Please post questions and problems on the community forum before opening issues, thank you.

Which debian version is that, do you have openjdk-8 installed? The jitsi-videobridge package depends on java8 (openjdk-8-jre-headless) and will not be installed if that is not available.

**Comment by SanalkumarQuiits** [comment]
Thanks for the quick reply. I am using Debian 8(Jessie). Let me check if openjdk-8 is installed or not. Further discussion will be on the community forum. Thank you.
