### ISSUE TITLE
conferenceJoined get called just after conferenceWillJoin even after receiver is not available

### ISSUE THREAD

**Issue by VinodComlink** [jitsi/jitsi-meet#3758]
Hi,

While implementing Delegates **JitsiMeetViewDelegate** I observe that **conferenceJoined** get called just after **conferenceWillJoin** irrespective to the any user join conference. I just want to capture the moment when a user joined the conference to perform some action. 

I have checked the documents and it says **Called when a conference was joined.** . can someone assist me on this?

Thanks

**Comment by saghul** [comment]
`conferenceJoined` is called for the local participant, not for other participants.
