### ISSUE TITLE
No delegate get called if initiator disconnect conference just after initiate 

### ISSUE THREAD

**Issue by VinodComlink** [jitsi/jitsi-meet#3759]
Hi,

**iOS Implementation**

I have get into this issue while working with Jitsi Video conference implementation. the scenario is like this -

I initiated a video conference and arrived over JitsiMeetView, As soon as I reached to the video screen I disconnect the conference by pressing hangup button. In this case I didn't get any delegate callback and user stuck on the same view. 

Whereas if I wait for 2-3 seconds and then disconnect(hangup) conference I get all delegate call backs.
  
Thanks

**Comment by saghul** [comment]
Do you get any delegate methods called at all?

**Comment by VinodComlink** [comment]
Yes, Delegates get called if I wait for 2-3 seconds and then disconnect the call.

**Comment by saghul** [comment]
But does no delegate method get called at all? Not even `conferenceWillJoin`?

**Comment by VinodComlink** [comment]
Not even single method get called in that case.

**Comment by saghul** [comment]
Thanks for the report, I'll take a look as soon as I can.

**Comment by VinodComlink** [comment]
Thanks, Please let me know as soon as you fixed
