### ISSUE TITLE
jitsi source code for ios cocoa framework 

### ISSUE THREAD

**Issue by bhooshanpatil** [jitsi/jitsi-meet#3771]
Hey All,
I'm in the middle of creating a **chat cocoa framework**, cant use jitsi.framework in my cocoa framework as Apple doesn't support it, Any alternate way to add jitsi in my cocoa framework??
thanx in advance..!

**Comment by damencho** [comment]
Posting your question to the community forum is enough, no need to create issues for questions. Thank you.
