### ISSUE TITLE
Image Flipped Horizontally When Pointing Camera at Monitor

### ISSUE THREAD

**Issue by earth3300** [jitsi/jitsi-meet#3774]
The image is flipped horizontally when the camera is pointed at the screen. Pointing the camera at the screen rather than using the screen sharing option is preferable for security reasons. Also, this allows the entire screen to be shown rather than a single window. The setting can be changed in the camera software to view the monitor correctly, but this setting does not carry over to the camera when used via the Firefox browser. Since the image is flipped horizontally, the words appear backwards as a mirror image, and so cannot be read.

Here is a link to an article that explains why pointing a camera at a screen is much better than sharing that screen internally:

https://blog.mozilla.org/webrtc/share-browser-windows-entire-screen-sites-trust/

**Comment by earth3300** [comment]
I have edited the text. Please let me know if this helps to clarify the issue.

**Comment by saghul** [comment]
@earth3300 Sorry, I missed the notification.

We do have a hidden way to toggle local video flipping. Set the `enableLocalVideoFlip` URL parameter when joining a room, for example: https://meet.jit.si/foo#config.enableLocalVideoFlip=true

Then right click on the local video and click on "Flip". This setting is stored in the browser's localStorage, so you only need to set it once for a given domain.
