### ISSUE TITLE
vieobridge startup error

### ISSUE THREAD

**Issue by JustinTQ** [jitsi/jitsi-meet#3784]
when I ran jvb.sh, prosody.log notes: 'component warn Component not connected, bouncing error for...' and jvb.log notes: 'INFO:[25] org.jitsi.videobridge.VideobridgeExpireThread.log() Running expire()'.
![image](https://user-images.githubusercontent.com/20768697/51024846-8b38b200-15c5-11e9-9354-a197b5d8349d.png)
![image](https://user-images.githubusercontent.com/20768697/51024896-a60b2680-15c5-11e9-8989-2eff0203c350.png)
![image](https://user-images.githubusercontent.com/20768697/51025183-4f521c80-15c6-11e9-9639-754146457ed1.png)
I can enter the room, but I will disconnect when someone else comes in.

**Comment by damencho** [comment]
Check your jicofo logs. The bounce error is fo jicofo. VideobridgeExpire thread is checking for channels which are no longer used to expire them, nothing to do with the problem you have.
When there is a problem like:
> I can enter the room, but I will disconnect when someone else comes in.

is to open the js console log and to confirm the problem, it maybe the bridge is missing or focus (jicofo) is missing.

Please use the community forum for asking questions and discussing problems before opening issues.
