### ISSUE TITLE
Support Iceweasel

### ISSUE THREAD

**Issue by Chris00** [jitsi/jitsi-meet#379]
Iceweasel is just Firefox rebranded for Debian.  It should be supported by https://meet.jit.si/
Thanks.

**Comment by gpolitis** [comment]
Hello Chris, thank you very much for your interest in jitsi-meet and for your suggestion. Iceweasel support is being discussed here here https://github.com/jitsi/jitsi-meet/issues/372 so I'm closing this as duplicate.
