### ISSUE TITLE
JitsiMeet Video interface change iOS SDK 

### ISSUE THREAD

**Issue by VinodComlink** [jitsi/jitsi-meet#3791]
Hello,

Want to understand how can video call interface of JitsiMeet can be customised, I am using JitsiMeet iOS SDK. I have explored so many things before posting this question because didn't find appropriate answers.

I have checked [https://github.com/jitsi/jitsi-meet/issues/2359](https://github.com/jitsi/jitsi-meet/issues/2359) but no clue how it can be achieved. I appreciate any help.

Thanks

**Comment by saghul** [comment]
At the moment the interface is not configurable, indeed. You'd need to make the changes to the Jitsi Meet project and rebuild the SDK.

We are, however adding the ability to change the color scheme and later on we'll add the ability to change the icon font.

What changes do you have in mind?

**Comment by Gk19011994** [comment]
@saghul Here i want to remove the add people option from video interface and want to add some another option.
 so please do a comment regarding this.
it can be possible if yes however i can.

**Comment by saghul** [comment]
**This** repo contains the app and SDK. Look on the ios/ subdirectory. As for changing the UI, you need to change the JS files since it's written in JavaScript for React Native.

**Comment by Gk19011994** [comment]
![1](https://user-images.githubusercontent.com/31057387/55158554-3dbff000-5185-11e9-81bf-990e48a2b77d.png)
![issue1](https://user-images.githubusercontent.com/31057387/55158555-3e588680-5185-11e9-8187-e7e3f6a0a7a7.png)
![issue2](https://user-images.githubusercontent.com/31057387/55158557-3e588680-5185-11e9-93fa-377127a8ea4c.png)

Here i have these 2 issue(screenshot attached) how can i resolve them?

![issuesall](https://user-images.githubusercontent.com/31057387/55158729-95f6f200-5185-11e9-97d1-1477f4f06480.png)

**Comment by saghul** [comment]
Have you install the dependencies with `npm install`?

**Comment by Gk19011994** [comment]
@saghul  Yes .

**Comment by saghul** [comment]
I suspect some build component is not liking your space in the path. Can you rename the directory from `ios sdk` to something without a space and try again?

**Comment by Gk19011994** [comment]
@saghul its working here i just remove the space. thanks for fast replying.

**Comment by Gk19011994** [comment]
![Buildios](https://user-images.githubusercontent.com/31057387/55235997-e9844100-5254-11e9-9e73-22907489c3ba.png)

@saghul  now i have this one issue.
jitsi server is working on 192.168.1.5 locally, can you please suggest where i should change on this.
or i have to add this so i can connect through app.

**Comment by saghul** [comment]
Didn't a terminal pop up with the development server? Alternatively make a release build of the SDK, so all assets are bundled.

**Comment by Gk19011994** [comment]
@saghul 
i want to ask one thing after making the desire changes. and build customise sdk now from this sdk
if i reference jitsimeetview and now the showing view of video interface, that will be as per my customisation?

**Comment by Gk19011994** [comment]
> Didn't a terminal pop up with the development server? 
No pop up
>Alternatively make a release build of the SDK, so all assets are bundled.
How??

![img22](https://user-images.githubusercontent.com/31057387/55275508-375c8000-530d-11e9-8168-abd4dcbe7384.png)
which js file i have to study to make changes as per this attached image.

thanks

**Comment by saghul** [comment]
> How??

Make a Release build of the "JitsiMeet" target on Xcode.

> which js file i have to study to make changes as per this attached image.

Chaging the icon will be tricky because we use an icon font, so you'd need to rebuild it. 

You can edit the toolbox buttons here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/native/Toolbox.js#L238

**Comment by Gk19011994** [comment]
@saghul 
Copy <code>selection.json</code> and <code>fonts/jitsi.*</code> from the zip file to <code>fonts/</code> in Jitsi Meet

what i have to do according to this step? this is step no 8. before this step i did not get a zip from click of download at the https://icomoon.io/app/ only get selection.json file.

**Comment by saghul** [comment]
There should be a link to download the entire font set. I can't look into it now but I know it's there.

**Comment by Gk19011994** [comment]
![font](https://user-images.githubusercontent.com/31057387/55393484-fa85c880-555a-11e9-8f0f-419e232ea6c9.png)

@saghul 
i download the jitsi.zip
please explain here in this step what i have to do.
Copy the class for the new icon from <code>style.css</code> in the zip file to <code>css/_font.scss</code> in Jitsi Meet (do *not* copy the whole file)

**Comment by saghul** [comment]
Exactly what it says. Copy the class for the new icon defined in the style.css file inside the zip file into the css/_font.css file of the jitsi-meet repo.

**Comment by Gk19011994** [comment]
@saghul 
Now my changes on icons are reflecting and showing inside ios build.
Now i want to make jitsi framework as with my changes what should i do?

**Comment by saghul** [comment]
Build the JitsiMeet target, which is a Framework already.

**Comment by Gk19011994** [comment]
![rebuild sdk](https://user-images.githubusercontent.com/31057387/55398156-738a1d80-5565-11e9-82d1-8b88c492af89.png)
@saghul

**Comment by Gk19011994** [comment]
@saghul 
i got the sdk but this sdk have less function comparing with jitsi original ios sdk, why?
also this is not having welcome page function and loadurl function.so its crashing.
Help me here.
![originalviewjitsi](https://user-images.githubusercontent.com/31057387/55400434-80117480-556b-11e9-8bb3-ddb458ec39cc.png)
![viewcustomJitsi](https://user-images.githubusercontent.com/31057387/55400435-80aa0b00-556b-11e9-9f19-e9272079bebf.png)

**Comment by saghul** [comment]
Please read the documentation: https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md#joinjitsimeetconferenceoptions

**Comment by Gk19011994** [comment]
![issuecustomsdk](https://user-images.githubusercontent.com/31057387/55404055-c28b7f00-5574-11e9-88b7-a1388df8a0f5.png)
@saghul   Please Help what is the its crashing and ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES this is set to YES

**Comment by saghul** [comment]
Sorry, I cannot help you any firther in this thread. Please post in our community: https://community.jitsi.org/

**Comment by Gk19011994** [comment]
@saghul  created
https://community.jitsi.org/t/having-a-crash-in-ios/17473

**Comment by Gk19011994** [comment]
@saghul 
i Successfully rebuild customise jitsi framework with my own changes.
Thanks for the Help.

Close it.

**Comment by ngoctan95** [comment]
@Gk19011994 , Could you help me pointing out the way to customize framework with my own changes,?

**Comment by Gk19011994** [comment]
@ngoctan95 what changes you want?Related to UI?

**Comment by Insfgg99x** [comment]
@Gk19011994 
Could you help me pointing out how to rebuild

**Comment by Gk19011994** [comment]
carefully read above comments you will get your solution @Insfgg99x

**Comment by mohdsafadsaal** [comment]
@Gk19011994 @saghul 

Hi , i have made changes in ToolBox.js. But if i want to rebuild the framework and add the framework in my own native project, what are the steps to follow?

your help would be appreciated.

**Comment by anirudha-music** [comment]
> **This** repo contains the app and SDK. Look on the ios/ subdirectory. As for changing the UI, you need to change the JS files since it's written in JavaScript for React Native.

Thanks for the information but where exactly these files are located and which are those?
