### ISSUE TITLE
JitsiMeet error and unable to find pod

### ISSUE THREAD

**Issue by gabcas267** [jitsi/jitsi-meet#3792]
Hello,
When I want to use the library in my native iOS project, I get the error "No bundle url present" and all the screen turn red.
Another query, because when I want to install the pod from cocoapods it appears "Can not find a specification for` JitsiMeetSDK` "

**Comment by marcoadasilvaa** [comment]
hello @saghul 

Could you please mention a developer that integrates Jitsi about a native development in IOS?

Thx

**Comment by saghul** [comment]
The pod is fairly recent, but it should Just Work (TM). What error are you seeing @gabcas267 ?

@marcoadasilvaa here you go: https://github.com/vector-im/riot-ios

**Comment by saghul** [comment]
Can do a "pod update" and try again?

**Comment by marcoadasilvaa** [comment]
thank you very much everything went well in the integration @saghul

**Comment by saghul** [comment]
Thanks for confirming @marcoadasilvaa !

**Comment by robertogomezslashmobility** [comment]
I'm getting the same issue, when I try to do a pod install. Unable to find a specification for `JitsiMeetSDK`. Can you help me?
