### ISSUE TITLE
jitsi-meet disconnect after running 2 hour

### ISSUE THREAD

**Issue by shisg1002** [jitsi/jitsi-meet#3805]
Five users use the jitsi-meet in one room, but for a maximum of two hours the page disconnects and is no longer linked. Restart jicofo, jitsi-videobridge has no help. 

Rerun jicofo with many errors that didn't have before.

[7E04B80E-DAF2-4325-AB94-93F33FF2AAC7.txt](https://github.com/jitsi/jitsi-meet/files/2768024/7E04B80E-DAF2-4325-AB94-93F33FF2AAC7.txt)

Who can give me some help ? Thanks a lot~!

**Comment by damencho** [comment]
Seems like your prosody is not running. 

Please use the community form for asking questions or when having problems, before opening new issues. Thank you.
