### ISSUE TITLE
How To Play Live Stream from other than webcam

### ISSUE THREAD

**Issue by nodejscss** [jitsi/jitsi-meet#3806]
I read Jitsi Meet features and know it is WebRTC javascript application and it can play YouTube video. 

And Jitsi Videobridge is WebRTC compatible.

How can I play live stream(live video) captured from VCR other than webcam?

Please help me. Thank you.

**Comment by saghul** [comment]
This question is better suited for our [community](https://community.jitsi.org/). We keep GitHub for bugs.
