### ISSUE TITLE
Task: sdk: bundleReleaseJsAndAssets FAILED when compiling apk release

### ISSUE THREAD

**Issue by thisEdgarMarquez** [jitsi/jitsi-meet#3807]
Hello community, I open the following thread to ask for help in finding a solution to the following error that occurs when I want to generate my apk release of jitsi meet for android, it seems that the sdk can not be compiled.

NOTE: This only happens when you want to generate a release apk in development compiles correctly.

`> Task :sdk:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':sdk:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Could not list contents of '/home/edgarmarquez/jitsi-meet/node_modules/.bin/json5'. Couldn't follow symbolic link.`

**Comment by saghul** [comment]
Looks like your node_modules directory might be botched. Can you remove it, run `npm i` and try again?

**Comment by thisEdgarMarquez** [comment]
I already managed to make it work, thanks for your help.

Steps I followed:

delete the node_modules folder
remove the lib-jitsi-meet package indicated in the package.json
run yarn add https://github.com/jitsi/lib-jitsi-meet or npm install https://github.com/jitsi/lib-jitsi-meet
run yarn install or npm install
run yarn install or npm install on lib-jitsi-meet
run make on jitsi-meet
