### ISSUE TITLE
404 Not Found when meeting name contains non-ascii characters such as äöüÄÖÜß

### ISSUE THREAD

**Issue by elsbiet** [jitsi/jitsi-meet#3811]
## Description
entering a meeting name containing äöüÄÖÜß and possibly other non-ascii characters results in '404 Not Found' displayed user's browser

## Current behavior
'404 Not Found' is presented to the user

## Expected Behavior
display a warning possibly accompanied by a hint if meeting name contains an illegal character

## Possible Solution
check meeting name using a positiv list such as /[a-zA-Z0-9]+/

## Steps to reproduce
try to create a meeting containing any of the above characters

# Environment details
none

# additional comment
the current behavior is annoying especially for a new user who might think, jitsi-meet is broken and will refrain from using it in the future.

**Comment by aaronkvanmeerten** [comment]
This is entirely in the nginx rules.  These rules are adjustable if the administrator wants to allow more permissive room names.  The request here as I see it is actually to make a prettier 404 page which describes what the user may have done wrong.  We're happy to take contributions of this variety, simply sign the NDA and make a PR against jitsi-meet with your suggested changes, and we'll review as with any other proposed change.

**Comment by saghul** [comment]
NDA -> CLA :-)
