### ISSUE TITLE
jibri never starts after 6 attempts to reinstall ubuntu16.04 using the install video for both, jitsi-meet and jibri

### ISSUE THREAD

**Issue by tkoller1** [jitsi/jitsi-meet#3819]

**Comment by tkoller1** [comment]
[jibri.log](https://github.com/jitsi/jitsi-meet/files/2783151/jibri.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2783152/jicofo.log)
[JVB.log.txt](https://github.com/jitsi/jitsi-meet/files/2783153/JVB.log.txt)

As a "non programmer" I made several attempts to install jibri exactly the way as shown in the instruction youtube videos. However jitsi-meet works but recording ist still not available. It seems that a Jibri cannot be found:
Jicofo 2019-01-22 14:56:43.547 SCHWERWIEGEND: [102] org.jitsi.jicofo.recording.jibri.JibriSession.log() 
Jicofo 2019-01-22 14:56:43.548 INFORMATION: [102] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Failed to start a Jibri session, no Jibris available

The jvb.log for the relevant period reports a healthy videobridge.
Finally the jbri log for the relevant period shows:
2019-01-22 14:44:57.588 INFORMATION: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will$
2019-01-22 14:45:27.615 WARNUNG: [22] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary() XMPPConnection was not authenticated
2019-01-22 14:45:30.809 SCHWERWIEGEND: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.SmackException$ConnectionException: $
2019-01-22 14:45:30.867 WARNUNG: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime d$

To my best knowledge I filled in the files with the relevant DNS entries and finally exhausted would be happy for a problemsolving advice and would also be willing to pay for.

**Comment by bbaldino** [comment]
Did you figure out the problem?

**Comment by tkoller1** [comment]
No, I still am struggling ;((

**Comment by tkoller1** [comment]
It is by the way a failure I have had with my very first instllation using Ubuntu 18.04....

**Comment by bbaldino** [comment]
Which versions of Jicofo and Jibri are you using?

**Comment by bbaldino** [comment]
Actually, can you open a discussion thread on [the community](https://community.jitsi.org/latest) for this?  Better than a bug.

**Comment by tkoller1** [comment]
The jibri version is:

||/ Name                    Version          Architektur      Beschreibung

+++-=======================-================-================-====================================================

ii  jibri                   7.1.70-1         all              Jibri



Thank you!

Regards

toni



*Von:* bbaldino <notifications@github.com>
*Gesendet:* Dienstag, 22. Januar 2019 21:43
*An:* jitsi/jitsi-meet <jitsi-meet@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Betreff:* Re: [jitsi/jitsi-meet] jibri never starts after 6 attempts to
reinstall ubuntu16.04 using the install video for both, jitsi-meet and
jibri (#3819)



Which versions of Jicofo and Jibri are you using?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jitsi/jitsi-meet/issues/3819#issuecomment-456555613>,
or mute the thread

**Comment by tkoller1** [comment]
Sorry, I forgot the Jicofo version:

||/ Name           Version      Architektur  Beschreibung

+++-==============-============-============-=================================

ii  jicofo         1.0-440-1    amd64        JItsi Meet COnference FOcus



*Von:* bbaldino <notifications@github.com>
*Gesendet:* Dienstag, 22. Januar 2019 21:43
*An:* jitsi/jitsi-meet <jitsi-meet@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Betreff:* Re: [jitsi/jitsi-meet] jibri never starts after 6 attempts to
reinstall ubuntu16.04 using the install video for both, jitsi-meet and
jibri (#3819)



Which versions of Jicofo and Jibri are you using?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jitsi/jitsi-meet/issues/3819#issuecomment-456555613>,
or mute the thread

**Comment by damencho** [comment]
Those versions are not compatible jicofo 440 and jibri 70. You need to update everything from unstable.

**Comment by tkoller1** [comment]
Thank you, I will have a try this afternoon.

T.



*Von:* Дамян Минков <notifications@github.com>
*Gesendet:* Mittwoch, 23. Januar 2019 12:42
*An:* jitsi/jitsi-meet <jitsi-meet@noreply.github.com>
*Cc:* tkoller1 <tkoller@contactlinse.net>; Comment <
comment@noreply.github.com>
*Betreff:* Re: [jitsi/jitsi-meet] jibri never starts after 6 attempts to
reinstall ubuntu16.04 using the install video for both, jitsi-meet and
jibri (#3819)



Those versions are not compatible jicofo 440 and jibri 70. You need to
update everything from unstable.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jitsi/jitsi-meet/issues/3819#issuecomment-456771104>,
or mute the thread
