### ISSUE TITLE
Jitsi conference disconnects automatically after 30 secs

### ISSUE THREAD

**Issue by kamal1978** [jitsi/jitsi-meet#3823]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.

**Comment by kamal1978** [comment]
I did a clean fresh quick install on Ubuntu 18.04 LTS

After installation, when i started the conference, it is disconnecting the conference after every 20 secs

**Comment by damencho** [comment]
Please use the community forum before opening issues.

First, check your javascript console log to understand why is that. I suspect you had missed this step: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by kamal1978** [comment]
Hi Damencho,

I have done all the mentioned configurations mentioned in the advanced-configuration settings
Still facing the issue
Firewall
root@whpvc:~# ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
10000:20000/udp            ALLOW       Anywhere
5437/tcp                   ALLOW       Anywhere
5437/udp                   ALLOW       Anywhere
5347/tcp                   ALLOW       Anywhere
5347/udp                   ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
10000:20000/udp (v6)       ALLOW       Anywhere (v6)
5437/tcp (v6)              ALLOW       Anywhere (v6)
5437/udp (v6)              ALLOW       Anywhere (v6)
5347/tcp (v6)              ALLOW       Anywhere (v6)
5347/udp (v6)              ALLOW       Anywhere (v6)

SIP-configuration

org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=127.0.0.1
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=103.225.41.7




Ice4j configs
root@whpvc:~# cat /proc/`cat /var/run/jitsi-videobridge.pid`/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             65000                65000                processes
Max open files            65000                65000                files
Max locked memory         16777216             16777216             bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       14656                14656                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

**Comment by damencho** [comment]
This is not a correct one: NAT_HARVESTER_LOCAL_ADDRESS=127.0.0.1
What is the output of ifconfig? Do you see there '103.225.41.7'?

**Comment by kamal1978** [comment]
Thanks its done, i was not putting the correct local IP.

Its working now
