### ISSUE TITLE
How to Cancel the Interface Display of Callkit Call Failure on iOS

### ISSUE THREAD

**Issue by WSX1994** [jitsi/jitsi-meet#3841]
![wechatimg61](https://user-images.githubusercontent.com/33861158/51902913-0f789b00-23f6-11e9-80b3-b1272cd4841b.jpeg)

hello，On the iOS side, the interface in the picture, how can he not display it?

**Comment by saghul** [comment]
It's not possible, you'd need to disable CallKit entirely.

**Comment by WSX1994** [comment]
But if I disable callkit, can I still cut back to the background when I use App videos?

**Comment by saghul** [comment]
Yes, you can.

**Comment by kiran4991** [comment]
Hello I am still acing the same issue. I have entirely disable the callkit

**Comment by saghul** [comment]
If you see that screen you haven't properly disabled CallKit, please double-check.
