### ISSUE TITLE
Device supported orientation not repected, even if specified on landscape, when device is rotated to protrait, video feed is rotated on both device and web

### ISSUE THREAD

**Issue by pierrewehbe** [jitsi/jitsi-meet#3844]
## Description
Device supported orientation not repected, even if specified on landscape, when device is rotated to protrait, video feed is rotated on both device and web

## Current behavior
Device supported orientation not respected, even if specified on landscape, when device is rotated to portrait, video feed is rotated on both device and web

## Expected Behavior
Feed should remain in Landscape Right and not rotate and resize frame on both web and device

## Possible Solution
I think it is reading it from image orientation because even after I disable notification on the sdk side, image was still rotating

## Steps to reproduce
Specify allowed orientation to Landscape Right ONLY
while on a call rotate to portrait

# Environment details
---
iOS: 12.0+
Xcode: 10.1

**Comment by saghul** [comment]
> Specify allowed orientation to Landscape Right ONLY
> while on a call rotate to portrait

I assume you are doing this by building the app / SDK yourself, right?

**Comment by pierrewehbe** [comment]
Yes

**Comment by saghul** [comment]
Right. This is a limitation of react-native-webrtc, the library we use for audio / video handling. It does not respect orientation locking. This is a known issue.
