### ISSUE TITLE
InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by mkenyon2** [jitsi/jitsi-meet#3847]
Getting this error:
Oops! Something went wrong. The following error occurred: InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.

**Comment by saghul** [comment]
Are you running Chrome 72? In that case you need to update your Jitsi Meet deployment: https://community.jitsi.org/t/urgent-update-jitsi-meet-now/16616/2

**Comment by nathando** [comment]
hi @saghul after updating library on both server and client. I still got a warning
```
[Deprecation] "Complex" Plan B SDP detected! Chrome will switch the default sdpSemantics in M72, around January 2019 from 'plan-b' to the standardized 'unified-plan' format and this peer connection is relying on the default sdpSemantics. This SDP is not compatible with Unified Plan and will be rejected by clients expecting Unified Plan. For more information about how to prepare for the switch
```

**Comment by saghul** [comment]
That comes from Chrome but it’s ok, we are currently still using plan B but will be migrating to unified plan.

**Comment by nathando** [comment]
Sorry have to reopen but I still have the same error after updating both server and client 

> [modules/xmpp/JingleSessionPC.js] <>:  addRemoteStream failed: setRemoteDescription failed: InvalidAccessError: Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan

Is there a setting or anything I need to reconfigure after the update ?

**Comment by saghul** [comment]
No, it should work out of the box. Are you sure you are using the latest version?

**Comment by billmorgan123** [comment]
anyone can post the link of the new version of jitsi meet

**Comment by mhbackpacker** [comment]
Hmm I seem to being having this error on the unified plan even now

[modules/xmpp/JingleSessionPC.js] addRemoteStream failed: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.

**Comment by saghul** [comment]
Please open a new issue as this one is really old and likely unrelated even though the error message might look similar.
