### ISSUE TITLE
Feature: Minimal Jitsi client JS API

### ISSUE THREAD

**Issue by matthias-w** [jitsi/jitsi-meet#385]
Jitsi Meet is a pretty cool stand alone video conferencing tool. However, from my experience so far it is quite difficult to integrate into an existing web application. There are many third party libraries (e.g. jquery, font awesome) that are related to user interface handling. All that is pretty much mixed up with the networking and video conferencing code.
A version leaving out all this UI stuff providing only a minimal JS API (e.g. subscribe for events such as stream-added or room-joined) for handling only the networking stuff would be great. This way it would be much easier to adapt it to other use cases and to use it in a more productive environment.

**Comment by nkokkos** [comment]
From what I understand jitsi-meet uses jitsi-videobridge to handle conferencing, which may be controlled through a rest api: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest-videobridge.md

**Comment by paweldomas** [comment]
Hi,

There is ongoing work on JS API for Jitsi-meet. You can find it on this branch here:

https://github.com/jitsi/jitsi-meet/tree/lib-jitsi-meet <https://github.com/jitsi/jitsi-meet/tree/lib-jitsi-meet>

Regards,
Pawel

**Comment by matthias-w** [comment]
Hello Pawel,
thanks for that. I did not know that you are already working on such an API. I guess that is exactly what I was looking for. Great :)

**Comment by nkokkos** [comment]
@matthias-w 
Have you seen this? -> https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

**Comment by matthias-w** [comment]
Hi,
thank you for mentioning external API. Unfortunately, it is not flexible enough for me. As far as I understand, it is pretty much the same (apart from a few available functions and events) as if I would embed Jitsi Meet with an iframe in my web page. The UI and all related libraries I do not need are still loaded. It would be too time-consuming overwriting JS behavior and CSS styling everytime a new Jitsi Meet version is published. The API, Pawel pointed to would be more suitable for my use case. 

Thanks and best regards
Matthias

**Comment by nadeem1234** [comment]
Any luck on implementing Jitsi Meet API?

can anyone put examples that they have been working with..

**Comment by hristoterezov** [comment]
Hi,

We have this example in the doc directory:

https://github.com/jitsi/jitsi-meet/tree/lib-jitsi-meet/doc/example

**Comment by nkokkos** [comment]
@hristoterezov 
May I ask a question? Does using lib-jitsi-meet require prior installation of jitsi-meet (the node.js application). Or can someone use lib-jitsi-meet to create something similar to jitsi-meet? 
Thank you in advance for the clarification.

**Comment by owen2345** [comment]
Hi friends,
does anyone know how to solve the iframe problem?
Load denied by X-Frame-Options: https://meet.jit.si/#external=true does not permit framing.
I am using this demo:
https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

**Comment by matthias-w** [comment]
@nkokkos 
I don't know if your issue is still relevant, but lib-jitsi-meet does not require jitsi-meet. What you do need is jitsi videobridge and jitsi conference focus together with an XMPP signaling server (I am using Openfire). With lib-jitsi-meet js file integrated in your web page (see example) you could build a jitsi-meet like application.

**Comment by nkokkos** [comment]
@matthias-w 
Thank you so much. Your answer helps me creatly.
