### ISSUE TITLE
Change Jitsi default URL or port

### ISSUE THREAD

**Issue by IvanMorozoff** [jitsi/jitsi-meet#3852]
I've installed Jitsi on my Ubuntu 14.04+Apache.
After installation, I can only access the Jitsi video conference from the URL of my site.
(for example https://mysite.com), 
and cannot access my old web pages in /var/www/html.

Please, advise me how I can config Jitsi to access via https://mysite.com/jitsi-meet?

Can I configure Jitsi to use non-443 port like this https://mysite.com:SOME_ANOTHER_PORT?

Is there a clear guide to solve this problem?

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening issues.

Sorry, currently there is no guide for doing that.

**Comment by IvanMorozoff** [comment]
Is it possible?

**Comment by IvanMorozoff** [comment]
Could you advise me how I can change 443 port?
There are a lot of topics about this issue on the internet like this:
https://github.com/jitsi/jitsi-videobridge/issues/578 
But this is not clear to me yet and I spend so much time on it (

What config files and what default settings should I change 
for typical installation Ubuntu 14.04+Apache?

**Comment by IvanMorozoff** [comment]
I've modified my config files like  below:

Apache2
/etc/apache2/sites-available/qqq.com.conf 

```
<VirtualHost *:5555>
  ServerName qqq.com
```
Jitsi

/etc/jitsi/meet/qqq.com-config.js
```
bosh: '//qqq.com:5555/http-bind'``
```

Now video conference works OK for 2 participants in the local network
But when the 3rd user is connected video and audio stops

I feel like this is typical situation and typical questions
But the answers that I found on the Internet are quite confusing and incomprehensible (

**Comment by damencho** [comment]
> Now video conference works OK for 2 participants in the local network
But when the 3rd user is connected video and audio stops

Was it working before your change? Usually, the problem is that people skip reading the advanced configuration: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by IvanMorozoff** [comment]
Before deploying jitsi on my external server, I'm trying to configure jitsi on the local network,
because default installation breaks an existing site.

Yes, I read this document and try to get help using the community forum, 
as you advised earlier: https://community.jitsi.org/t/setup-jitsi-url-and-port/16675
