### ISSUE TITLE
Internal Error in Chrome 72

### ISSUE THREAD

**Issue by sreenivaska** [jitsi/jitsi-meet#3854]
I am unable to have the video call with Chrome browser V72.
Here is the error prompted the bowser

Oops! Something went wrong. The following error occurred: InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.

**Comment by damencho** [comment]
Please for questions and problems use the community forum before opening an issue.

https://community.jitsi.org/t/urgent-update-jitsi-meet-now/16616
Are you using latest?
