### ISSUE TITLE
App android uses high band network

### ISSUE THREAD

**Issue by eunafinta** [jitsi/jitsi-meet#3856]
I made one test with jitsi-meet own server and i do one-to-one connection test with android app and google-chrome web client, worked very well. However, when i am  put  more one google-chrome web client on room, the app use more upload rate in 720p (Show in image). My question is how can i set in app to reduce the bandwith? 

![jisti-app-hight-band](https://user-images.githubusercontent.com/29760344/52129865-cdcb3880-261f-11e9-83f7-3205f8997fd3.png)

**Comment by saghul** [comment]
On mobile (android and ios) you can switch to audio-only mode. Adjusting the video quality is currently not supproted.

**Comment by eunafinta** [comment]
When a use the browser in "Desktop mode", the connection is better. And the bandwidth is adaptable better than app... 

My cellphone is Moto Z3 and android 8.1.0.
