### ISSUE TITLE
Add news shortcuts to improve quality video

### ISSUE THREAD

**Issue by anas0dev** [jitsi/jitsi-meet#3867]
There is a problem during the video call, a bug causes the screen to freeze. A solve to resolve this problem is to change the quality video.

The addition of shortcuts to change the qualitfy video makes things easier.

Moreover the shortcuts is important and useful for the software.

**Comment by anas0dev** [comment]
Hi,
I wish to work on this issue, can you assign it to me please?

**Comment by saghul** [comment]
We already have this feature on the web, do you intend to work on it for mobile?

**Comment by anas0dev** [comment]
Yes, I think there is some confusion, i was just thinking about adding a shortcut to use this feature ( manage quality video), it would make the user's task easier and would quickly stop the bug I was referring to.

**Comment by saghul** [comment]
Ah, sure, feel free to send a PR!

**Comment by iLevelUp** [comment]
Hello ! I am currently working with Anasdev on the modification regarding the addition of the ManageCallQuality shortcuts, we thought about adding other improvements that we will share with you later.

Concerning the addition of the shortcuts, there are several files to modify but for the moment I think I'm starting to open the Call Quality dialog box using a keyboard key, so I'm thinking about working on the keyboardshortcut.js and VideoQualityDialogWeb files, am i on the right track? or not?
Thank you !

**Comment by saghul** [comment]
Sounds like on the right track!

**Comment by iLevelUp** [comment]
Hi, we had some concerns causing some delay in our progress, but we got back on track, for the moment we can trigger other shortcuts from unused keyboard keys, however we want to change the values of the dialog box ( switch from low to high) and at the same time open this box, if you have any advice for us, they are welcome :)

**Comment by saghul** [comment]
@virtuacoplenny can you provide some guidance here?

**Comment by virtuacoplenny** [comment]
registering a shortcut: https://github.com/jitsi/jitsi-meet/blob/b886f8d72d7da6bd4cac80399c57f5f78fb877d3/react/features/toolbox/components/web/Toolbox.js#L286
opening the dialog: https://github.com/jitsi/jitsi-meet/blob/b886f8d72d7da6bd4cac80399c57f5f78fb877d3/react/features/toolbox/components/web/Toolbox.js#L393
changing the quality: https://github.com/jitsi/jitsi-meet/blob/b886f8d72d7da6bd4cac80399c57f5f78fb877d3/react/features/video-quality/components/VideoQualitySlider.web.js#L388

**Comment by saghul** [comment]
wait

**Comment by saghul** [comment]
@virtuacoplenny any chance you can take another look at this?

**Comment by virtuacoplenny** [comment]
https://github.com/jitsi/jitsi-meet/pull/4205. I've been waiting for the reporter to follow up.
