### ISSUE TITLE
Android Studio upgrade to 3.3.1 breaks groovy.json.JsonSlurper

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3872]
Compiling Android app from latest git was working fine until I got prompted to update Android Studio and I foolishly accepted. (From 3.3. to 3.3.1 on OSX).

Now I get an error when trying to import groovy.json.JsonSlurper
"Cannot resolve symbol JsonSlurper"

I think the Android Studio update broke something, which seems to have happened before with other projects and JsonSlurper  https://github.com/react-native-community/react-native-image-picker/issues/293

I could delete Android Studio and reinstall an older version but that maybe a pain I'd rather avoid if there's a simple fix for this.

Cheers

**Comment by pdarcos** [comment]
I deleted Android Studio 3.3.1 and went back to 3.3 and it's working again now

**Comment by saghul** [comment]
FWIW, I just updated to AS 3.3.1 and made a build with no issues.

**Comment by pdarcos** [comment]
Thanks @saghul 

I cleaned my environment and indeed works fine with 3.3.1

**Comment by matkev** [comment]
@pdarcos I'm having the exact same problem on AS 3.5
Could you let me know what you did to fix it, or how to clean my environment?

**Comment by thorito** [comment]
Same problem with Android Studio 3.5 stable

**Comment by saghul** [comment]
Cannor reproduce with AS 3.5. Did you make any change to the project?

**Comment by thorito** [comment]
Nothing, 
I first, import proyect from git.
Second, npm install from console.

I use Windows 10 and installed node, python
Android Studio 3.5

**Comment by saghul** [comment]
We don't support building on Windows, sorry about that.

**Comment by AbhisekhD** [comment]
I am also facing the same issue with AS 4.0.

**Comment by Ginzry** [comment]
I am also facing the same issue with AS 4.0, the system is macos

**Comment by Yarkhan** [comment]
Facing the same issue today on android 4.1.2, linux.
removing the import for JsonSlurper and adding  "new groovy.json.JsonSlurper()"  instead where JsonSlurper is used fixed it for me, after clearing gradle caches in the home directory.
