### ISSUE TITLE
Allow sharing of youtube video in Tile View

### ISSUE THREAD

**Issue by patcon** [jitsi/jitsi-meet#3874]
Hi! First off, thanks again for all the effort y'all put into this rad tool!

**Is your feature request related to a problem you are facing?**
I am trying to host a video-watching hangout on Jitsi that we currently host on appear.in. Since the watch-party is about fostering interactions between viewers, not just consuming the information in the video, it's important to the social dynamics that people can see one another. It is conceptually like the video is just another person on the call that is sharing space with us, and not taking all the attention and hiding us from one another.

Jitsi Meet's frozen screenshot of video thumbnail in tile view:

![screen shot 2019-02-07 at 11 16 06 am](https://user-images.githubusercontent.com/305339/52426064-46704000-2acb-11e9-8206-e281e3a238a3.png)

**Describe the solution you'd like**
I personally prefer the opinionated appear.in solution that defaults to a big view of the video, with faces of watchers along the side (auto-muted when playback starts). But it could work equally well if I could request people move into Tile View. I can do that, but Tile View just shows a screenshot of the video, while the full video plays in the background.

Appear.in's default view for video watch feature

![screen shot 2019-02-07 at 11 23 17 am](https://user-images.githubusercontent.com/305339/52426035-37898d80-2acb-11e9-89cd-1dff1115da27.png)

**Describe alternatives you've considered**
We could watch the video without seeing one another, but this will not support the human-centered ethos of the call. We've been using appear.in for now :)

Thanks for hearing me out!

**Comment by damencho** [comment]
What about not using tile view, but the default one. You can just enable 'Follow me' mode, and pin the video you are watching. This way the video will be on large, and all participants small thumbs and everybody should see the state you see as you had enabled 'Follow me'. Does that work for you?

Please use the community forum for problems or questions before opening new issues.

**Comment by patcon** [comment]
Thanks @damencho! That's an alternative I hadn't considered, so thank you!

Downsides of this would be

1. the facilitator (25% of the 4-person group) wouldn't be visible, and
2. having to stream the video through a user feed rather than watching locally (through "watch youtube video" feature) would likely affect the experience quite significantly, depending quite crucially on bandwidth of facilitator, and not letting participants' benefit from youtube widget's bandwidth auto-selection (and closed captioning, to a lesser degree).

Am I understanding that you don't see this as a meaningful feature request, and wish to close it? (I do understand wanting to keep issue queue in check :) )

**Comment by damencho** [comment]
1. I don't get it.
2. If you use the share YouTube video feature, the video will be played locally downloaded from YouTube on every client machine.

Yes, as described in the issue template we prefer discussing stuff in the forum before opening an issue.
And here I don't see a feature request, as everything is already available.

**Comment by patcon** [comment]
1. Seeing faces is important to the community organizing these calls. Your solution is thoughtful, but means one of the 4 total faces on the call is replaced with the video :)

Really appreciate your time @damencho. This feature is not available in the requested form (appear.in demonstrates the desired behaviour for now), but if I'm not pushing it forward myself, I'll let this rest. Cheers!

**Comment by damencho** [comment]
@patcon 
> 1. Seeing faces is important to the community organizing these calls. Your solution is thoughtful, but means one of the 4 total faces on the call is replaced with the video :)

No, that is not true. If you share youtube video it is seen as a separate participant. 
<img width="300" alt="screenshot 2019-02-07 at 21 44 38" src="https://user-images.githubusercontent.com/3263098/52445025-d9d46000-2b21-11e9-84e0-1adb48f852d2.png">
Did you try that, and it replaces your participant?

**Comment by mavenik** [comment]
@damencho How does this work with paid subscriptions. For example, if I rent a movie on YouTube and then bring it to Jitsi to co-watch with my friends, would that work for others in the chat room as well (given that the video is streamed locally and they may not have purchased subscription)?

I'm yet to test this myself, thought I'd ask on this thread. I could initiate a topic on community forum, if it hasn't been initiated already.

**Comment by saghul** [comment]
That won’t work. This feature basically tells everyone to open that same video, you are not streaming it to them.

**Comment by rishabhmalik759** [comment]
> What about not using tile view, but the default one. You can just enable 'Follow me' mode, and pin the video you are watching. This way the video will be on large, and all participants small thumbs and everybody should see the state you see as you had enabled 'Follow me'. Does that work for you?
> 
> Please use the community forum for problems or questions before opening new issues.

Hello, 
I am using Jitsi to teach people Yoga online, and when the shared youtube video stops in the tile view I can't see where I am at.
If I don't go to tile view, I can't really correct the participants if they are doing some wrong move.

This feature of playing youtube video in tile view is must needed. Please tell me how can I implement it, if it's not so complicated?

**Comment by gigabyteservice** [comment]
@saghul This issue is still there on web as well as on mobile app

**Comment by saghul** [comment]
Not in the short term, but a PR would be welcome.
