### ISSUE TITLE
Jitsi Conference not loading with Public IP 

### ISSUE THREAD

**Issue by rishabhchd19** [jitsi/jitsi-meet#3879]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---I installed the Jitsi on Ubuntu 18 LTS on Vbox 6.0. Using bridge network I got IP assigned within the domain and Installed Jitsi Package with Apache2 . Jitsi meet conference room loading all the necessary stuff reqd for jitsi but on Local Domain only. Now when I Port Forwarded on Public IP 
![2019-02-10_22-55-43](https://user-images.githubusercontent.com/30948461/52537134-16ee5b80-2d89-11e9-9e0c-66e0b90a8a0a.jpg) with port 443, it's loading perfectly the Welcome Page. Now when I entered a room, Room doesn't load with all the stuff.
 

## Current behavior
---When looking into Console from Browser, it displaying -:

OPTIONS https://192.168.0.13/http-bind?room=abcd 
net::ERR_CERT_AUTHORITY_INVALID
l @ strophe.js:5662
_processRequest @ strophe.js:5677
_throttledRequestHandler @ strophe.js:5823
_connect @ strophe.js:5170
connect @ strophe.js:3051
value @ xmpp.js:309
value @ xmpp.js:369
c.connect @ JitsiConnection.js:61
e @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
s @ app.bundle.min.js?v=3186:230
c @ app.bundle.min.js?v=3186:230
H @ app.bundle.min.js?v=3186:248
createInitialLocalTracksAndConnect @ app.bundle.min.js?v=3186:248
init @ app.bundle.min.js?v=3186:248
(anonymous) @ app.bundle.min.js?v=3186:187
(anonymous) @ app.bundle.min.js?v=3186:187
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:16
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:116
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:116
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:241
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:241
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
value @ app.bundle.min.js?v=3186:187
value @ app.bundle.min.js?v=3186:187
Na @ app.bundle.min.js?v=3186:100
ja @ app.bundle.min.js?v=3186:100
Pa @ app.bundle.min.js?v=3186:100
Oa @ app.bundle.min.js?v=3186:100
Zi @ app.bundle.min.js?v=3186:100
enqueueSetState @ app.bundle.min.js?v=3186:100
w.setState @ app.bundle.min.js?v=3186:92
n @ app.bundle.min.js?v=3186:24
t @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:1
e.emit @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
t.load @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
t.load @ app.bundle.min.js?v=3186:1
t.loadResources @ app.bundle.min.js?v=3186:1
r @ app.bundle.min.js?v=3186:1
t.changeLanguage @ app.bundle.min.js?v=3186:1
s @ app.bundle.min.js?v=3186:1
setTimeout (async)
t.init @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:65
(anonymous) @ app.bundle.min.js?v=3186:65
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:60
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:65
(anonymous) @ app.bundle.min.js?v=3186:65
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:24
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:35
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:24
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:230
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:158
(anonymous) @ app.bundle.min.js?v=3186:158
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:248
(anonymous) @ app.bundle.min.js?v=3186:248
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:248
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
Logger.js:125 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: request id 1.1 error 0 happened
    at Object.i.Strophe.log (strophe.util.js:89)
    at Object.error (strophe.js:2083)
    at e.Bosh._onRequestStateChange (strophe.js:5565)
i @ Logger.js:125
getGlobalOnErrorHandler @ JitsiMeetJS.js:535
window.onerror @ app.bundle.min.js?v=3186:1
callErrorHandler @ GlobalOnErrorHandler.js:61
i.Strophe.log @ strophe.util.js:89
error @ strophe.js:2083
_onRequestStateChange @ strophe.js:5565
XMLHttpRequest.send (async)
l @ strophe.js:5662
_processRequest @ strophe.js:5677
_throttledRequestHandler @ strophe.js:5823
_connect @ strophe.js:5170
connect @ strophe.js:3051
value @ xmpp.js:309
value @ xmpp.js:369
c.connect @ JitsiConnection.js:61
e @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
s @ app.bundle.min.js?v=3186:230
c @ app.bundle.min.js?v=3186:230
H @ app.bundle.min.js?v=3186:248
createInitialLocalTracksAndConnect @ app.bundle.min.js?v=3186:248
init @ app.bundle.min.js?v=3186:248
(anonymous) @ app.bundle.min.js?v=3186:187
(anonymous) @ app.bundle.min.js?v=3186:187
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:16
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:116
(anonymous) @ app.bundle.min.js?v=3186:35
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:116
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:241
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:241
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
value @ app.bundle.min.js?v=3186:187
value @ app.bundle.min.js?v=3186:187
Na @ app.bundle.min.js?v=3186:100
ja @ app.bundle.min.js?v=3186:100
Pa @ app.bundle.min.js?v=3186:100
Oa @ app.bundle.min.js?v=3186:100
Zi @ app.bundle.min.js?v=3186:100
enqueueSetState @ app.bundle.min.js?v=3186:100
w.setState @ app.bundle.min.js?v=3186:92
n @ app.bundle.min.js?v=3186:24
t @ app.bundle.min.js?v=3186:24
(anonymous) @ app.bundle.min.js?v=3186:1
e.emit @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
t.load @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
t.load @ app.bundle.min.js?v=3186:1
t.loadResources @ app.bundle.min.js?v=3186:1
r @ app.bundle.min.js?v=3186:1
t.changeLanguage @ app.bundle.min.js?v=3186:1
s @ app.bundle.min.js?v=3186:1
setTimeout (async)
t.init @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:65
(anonymous) @ app.bundle.min.js?v=3186:65
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:60
(anonymous) @ app.bundle.min.js?v=3186:60
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:65
(anonymous) @ app.bundle.min.js?v=3186:65
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:24
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:35
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:24
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:230
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:158
(anonymous) @ app.bundle.min.js?v=3186:158
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:230
(anonymous) @ app.bundle.min.js?v=3186:230
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:248
(anonymous) @ app.bundle.min.js?v=3186:248
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:248
n @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
(anonymous) @ app.bundle.min.js?v=3186:1
Logger.js:125 [modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 1.1 error 0 happened

## Expected Behavior
---I allowed cross origin in global config, enabled websocket and http static files permissions too. But all works fine in LOCAL Domain even outside the VBOX but not on Public IP.

## Possible Solution
---

## Steps to reproduce
--- I put the FQDN as LOCAL IP, Generated Self Signed Cert. When the Conference Room is called, the LOCAL Domain shows no error...PUBLIC network does!

# Environment details
---
How to Start Conferencing on Public Network as smooth as going with Local Network?

**Comment by damencho** [comment]
When installing you had entered as a domain the internal IP address, where you needed to enter the public dns.

Use the community forum for problems or questions before opening new issues.
