### ISSUE TITLE
Shared Link is not getting opened  after changing the bundle identifier in the ios 

### ISSUE THREAD

**Issue by visheshtungare-hiteshi** [jitsi/jitsi-meet#3881]
after successfully  running the jitsi meet for ios and android 
and connecting it with my server now when i share a link and when we click on the link the app 
![skype_picture](https://user-images.githubusercontent.com/44169233/52561810-7b112e00-2e22-11e9-9b68-7aad80233a5c.jpeg)

while the application is already present in the device its not opening the app 

kindly help

**Comment by pdarcos** [comment]
When did you compile your app (what git version)?

It maybe related to this bug https://github.com/jitsi/jitsi-meet/issues/3833

**Comment by visheshtungare-hiteshi** [comment]
Thanks for the replay i complied it with the latest version of the jitsimeet 
from the masters

**Comment by pdarcos** [comment]
Then it's probably related to the bug I identified.
Not much we can do except wait to see if @saghul or someone else has any ideas

**Comment by saghul** [comment]
Let's continue in #3833 though I'm out of ideas :-/

**Comment by visheshtungare-hiteshi** [comment]
@pdarcos @saghul 

Let me clear the scenario with an example 

suppose  i have created a room on my application FOOMEET  and sent an invitation to @pdarcos  on whats app 
when @pdarcos  click on the link that he got on whats  then  it fails to recognise my application  instead ut ask you to download jitsi meet even you have FOOMEET installed on the device

hope this clarifies me situation

**Comment by saghul** [comment]
You need to enable Universal linking for that: https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links?language=objc

The Jitsi Meet app has this enabled by default for meet.jit.si, but if you run your own domain, you can still use it by clicking on the "continue to app" message on that website.

**Comment by visheshtungare-hiteshi** [comment]
> 

> You need to enable Universal linking for that: https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links?language=objc
> 
> The Jitsi Meet app has this enabled by default for meet.jit.si, but if you run your own domain, you can still use it by clicking on the "continue to app" message on that website.

 continue to app does not work

**Comment by saghul** [comment]
What error do you get? I wonder if you need to change the schema...

**Comment by visheshtungare-hiteshi** [comment]
> What error do you get? I wonder if you need to change the schema...

nothing no response

**Comment by visheshtungare-hiteshi** [comment]
can you please tell me from where this page is getting generated 
so i can also  find a work around 
 and if  i want to see the shareing URL from where i can see that in the Code

**Comment by visheshtungare-hiteshi** [comment]
hello I have resolved this issue  in the 
interface_config.js 
one can configure the redirect URLs for android and ios

**Comment by visheshtungare-hiteshi** [comment]
now  when i click on continue with application it open chooser on the android but shows only google play store 

and on ios it is showing the following error this is very  urgent kindly provide the feedback 
thanks 
"safari can not open the page as the address is invalid " this is coming on IOS 

![skype_picture_2019_02_14t06_02_52_241z](https://user-images.githubusercontent.com/44169233/52766160-497bab00-304c-11e9-9f07-7a5902bf49a4.jpeg)

**Comment by visheshtungare-hiteshi** [comment]
now when i click on continue with application it open chooser on the android but shows only google play store

and on ios it is showing the following error this is very urgent kindly provide the feedback
thanks
"safari can not open the page as the address is invalid " this is coming on IOS
![skype_picture_2019_02_14t06_02_52_241z](https://user-images.githubusercontent.com/44169233/52767040-2e5e6a80-304f-11e9-8010-eee5852b4ba1.jpeg)

**Comment by saghul** [comment]
Well, what address did you put in there?

**Comment by visheshtungare-hiteshi** [comment]
> Well, what address did you put in there?

i have added my bundle identifier name in the APP_SCHEME in the interface_config.js

**Comment by saghul** [comment]
That's not enough. You need to also edit the Xcode file and match it in associaled links.

**Comment by visheshtungare-hiteshi** [comment]
i am asuming that you are saying  in the ios folder ,
apple-app-site-association
i will have to add the appid

**Comment by visheshtungare-hiteshi** [comment]
1. i have add the association site in the xcode 
2. in the ios folder >>> appl-app-site-association  i have added the new appid  and the same format 
3. on my apple account  Associated Domains are enable for the id 


current response  on clicking on the continue with app no response is coming    he above error has been resolved but still its not opening the application 


i have tested this for android if there are certain steps for that also please let me know 
thanks

**Comment by visheshtungare-hiteshi** [comment]
Finally, I was able to achieve deep-linking successfully on both android and ios 


on ios, we will need to add the URL TYPE and the same URL type need to mention in the app scheme 
for Android, we need to add the host domain in the manifest  and need to mention the package name  on the server

**Comment by pdarcos** [comment]
Thanks for the update!
So you are able to compile the iOS app with your own URL in the constants.js file instead of meet.jit.si and you’re able to trigger the invite someone function on the iPhone?
Is that correct?

Cheers

**Comment by saghul** [comment]
@pdarcos I think he was struggling with deep-linking.

**Comment by pdarcos** [comment]
@saghul  That's what I suspected but I was hoping he had somehow gotten it to work since it doesn't make sense to have deep linking unless he's using his own custom URL. If he is he'll run into the same problem as soon as he tries to invite someone via the iOS app.

Is there another way to change the default URL? Maybe by using some other method it won't trigger the strange behavior we're seeing.

**Comment by visheshtungare-hiteshi** [comment]
> @saghul That's what I suspected but I was hoping he had somehow gotten it to work since it doesn't make sense to have deep linking unless he's using his own custom URL. If he is he'll run into the same problem as soon as he tries to invite someone via the iOS app.
> 
> Is there another way to change the default URL? Maybe by using some other method it won't trigger the strange behavior we're seeing.

i was able to make the deep linking invite button still not work 
i am also facing issues in the deep linking in the chrome  due to the DSP parsing

**Comment by saghul** [comment]
What is DSP?

**Comment by visheshtungare-hiteshi** [comment]
> What is DSP?

recently chrome has changed its parsing method and updated the rules due to which when you will paste the room url on the chrome browser and then when you will click on the continue to the application it will just open a blank window in the browser and won't open the application this happens only for Android ! 
cheers 

![screen shot 2019-02-18 at 2 26 39 pm](https://user-images.githubusercontent.com/44169233/52947117-d3ed4300-339b-11e9-8b90-4bce2643bc52.png)

**Comment by saghul** [comment]
@visheshtungare-hiteshi Please open new issues for, well, new issues. This thread was about iOS, let's not mix things.

At any rate, that was fixed a couple of weeks ago. I updated the Maven artifacts a couple of days agio, so if you fetch them again it shoiuld just work because we now generate Intent URLs on Android.

**Comment by visheshtungare-hiteshi** [comment]
> @visheshtungare-hiteshi Please open new issues for, well, new issues. This thread was about iOS, let's not mix things.
> 
> At any rate, that was fixed a couple of weeks ago. I updated the Maven artifacts a couple of days agio, so if you fetch them again it shoiuld just work because we now generate Intent URLs on Android.

That was just for information  as it can't not be considered as issue as it is wontFix  on chrome

**Comment by gaurishsharma** [comment]
> after successfully running the jitsi meet for ios and android
> and connecting it with my server now when i share a link and when we click on the link the app


Hi @visheshtungare-hiteshi , was just going through your message. I am facing tough time in integrating iOS and Android apps to my custom url. 
I have set up Jitsi on my own server on a domain like https://mydomain.com

In my Android code, I have set jitsi_url as https://mydomain.com,

 ```
val serverURL: URL
        try {
            serverURL = URL(getString(R.string.jitsi_url))
        } catch (e: MalformedURLException) {
            e.printStackTrace()
            throw RuntimeException("Invalid server URL!")
        }

        var userInfo = JitsiMeetUserInfo()
        val options = JitsiMeetConferenceOptions.Builder()
            .setServerURL(serverURL)
            .setWelcomePageEnabled(false)
            .setUserInfo(userInfo)
            .setRoom("1")
            .build()

        JitsiMeetActivity.launch(activity, options)
```
But, instead of going to the url defined in jiitsi_url above, it is going to http://meet.jit.si/1

Is there anything else that is required to point to my own Jitsi domain?

Would really appreciate if you can help.

Thanks,
Gaurish
