### ISSUE TITLE
Youtube video support 

### ISSUE THREAD

**Issue by visheshtungare-hiteshi** [jitsi/jitsi-meet#3882]
How can i see the youtube on jitsi mobile 
which is shared by other user in the room as shared youtube video 
i am not able to see the youtube video on the device 

kindly help

**Comment by virtuacoplenny** [comment]
It's not supported right now on mobile; it would need implementing.

**Comment by netstairs** [comment]
Does it work on stable version?

**Comment by saghul** [comment]
No

**Comment by rykel** [comment]
Hi, I would like to view the Shared Youtube video on Jitsi Meet for Android and iOS too. How may I help to contribute the code so that this can be made possible? I am not a programmer, but since I am on lockdown, I can take the time to learn how to do it.

**Comment by netstairs** [comment]
When u have a time, I can show it to you.  It is located under … (More Options) located at right bottom corner.  Option says share You Tube.  Copy and paste URL and you’re all set.

**Comment by CCStefanini** [comment]
This thread has particular interest to me and to others (https://community.jitsi.org/t/sharing-youtube-video-for-mobile-devices/27301).  I along with others would like to see this functional developed for the jitsi product.  I am trying to figure out how we get developers to prioritize this?  I can contribute by testing but not coding.
