### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#3887]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by 532910** [comment]
not stale

**Comment by saghul** [comment]
Damn right. ihad missed this report, thanks for the heads up! We'll be fixing this shortly.

**Comment by 532910** [comment]
not stale

**Comment by saghul** [comment]
Fixed it last week! https://github.com/jitsi/jitsi-meet/commit/0f77cf9e0cd3d942d10c4b7434156d1fc9ebf5d4 Sorry I forgot to update this one. It will be part of the next release.

**Comment by 532910** [comment]
Nice, thank you!
