### ISSUE TITLE
Trouble accessing mic/cam or entering room (logs included)

### ISSUE THREAD

**Issue by Bugsbane** [jitsi/jitsi-meet#389]
Hey there,
I tried beta.meet.jit.si last night (EST) between my (Manjaro) Linux laptop with Chrome and my Android (5.1) phone using Firefox and it worked fine.

When I tried calling a friend who was using Firefox on their Samsung Galaxy Note 2 phone just an hour later though, they weren't able to see their camera or audio. They were just seeing the icon of the camera with the cross through it for their thumbnail.

![screengrab](https://cloud.githubusercontent.com/assets/401733/10761130/69957726-7c96-11e5-9035-5c08a8105411.jpg)

They assure me that they did allow access to the mic and phone, and when we tried Hangouts just after there were no problems.

Most of the time I wasn't even seeing anyone enter the room. I'm wondering if this may be related to https://github.com/jitsi/jitsi-meet/issues/388 although as I said before, when I tested between Linux Chrome and Android Firefox, I had no problem.

We tried a couple of different URL's, and the logs are at:
https://paste.kde.org/phxucvncg/gjydjv
https://paste.kde.org/ps1rr8spd/cf2fut

**Comment by akuckartz** [comment]
I also tried to use Jitsi Meet with Firefox on Android and no camera was recognized.

**Comment by Bugsbane** [comment]
Well it wors on my Android phone with Firefox (Moto E gen 2, FF from Fdroid), so it's not universal to FF Android. just not sure if it's a hardware or FF version triggered bug.

**Comment by bgrozev** [comment]
This is outdated by now. Please open a new issue if a problem persists
