### ISSUE TITLE
iOS : Conference is terminated if the user locks the screen by pressing the device hardware button

### ISSUE THREAD

**Issue by MehediHasanTanim** [jitsi/jitsi-meet#3906]
## Description
--- in iOS, if the user "Enable audio-only mode" and lock the screen by pressing device hardware button, then the conference is terminated and a message "Jitsi Meet Audio Ended" is shown in callkit display. The same issue even found in Jitsi Meet appstore app.

## Current behavior
--- Conference is terminated if the user locks the screen by pressing the device hardware button.

## Expected Behavior
--- Conference should not be terminated if the user locks the screen by pressing the device hardware button

## Steps to reproduce
--- 1. Enable Audio only mode from options
      2. Lock the screen by pressing the device hardware button

# Environment details
--- Device : iPhone x, iPhone xs, iPhone 8 Plus
--- iOS : 12, 11

**Comment by saghul** [comment]
This behavior is expected, as it's imposed by iOS itself. Check FaceTime, it does the same. CallKit sends the call termination signal when the device is locked while in audio only mode. This doesn't happen when video is enabled.
