### ISSUE TITLE
"Start Recording" end conference

### ISSUE THREAD

**Issue by farhan9876** [jitsi/jitsi-meet#3911]
Start Recording was working perfectly fine and saving files to dropbox but suddenly it stopped working.
![step1](https://user-images.githubusercontent.com/46020087/53070312-85a58480-3500-11e9-88b3-dff87855da54.PNG)

Now when ever I click on "Start Recording", it ends conference and send me to below screen.
![step2](https://user-images.githubusercontent.com/46020087/53070313-85a58480-3500-11e9-9e63-52da5c7a41b4.PNG)

I am using Windows 10 and Firefox/ chrome.

**Comment by virtuacoplenny** [comment]
It's a know and fixed regression that slipped onto master. A version with the fix hasn't been deployed yet. The PR with the fix is: https://github.com/jitsi/jitsi-meet/pull/3896.

**Comment by farhan9876** [comment]
thank you for response.
any expected date for fix deployment?

**Comment by virtuacoplenny** [comment]
Sorry, not that I know of. Wish I could tell you but it's not on a set schedule.

**Comment by farhan9876** [comment]
Thank you
