### ISSUE TITLE
Jitsi Meet in small window (in Rocket.Chat)

### ISSUE THREAD

**Issue by mmmaks2004** [jitsi/jitsi-meet#3916]
## Description
When the Jitsi Meet is launched in a small window, I cannot press any button due to pop-up messages
I can not close these messages

## Current behavior
 I cannot press any button due to pop-up messages
 I can not close these messages

## Expected Behavior
Messages should not interfere
Give the ability to close messages

## Possible Solution
reduce messages to window size

# Environment details
Windows 10
Browser Firefox 52.9 ser
Rocket Chat 0.74.2
![yyy](https://user-images.githubusercontent.com/45267864/53229297-8834e500-368c-11e9-8dc9-ffb1a507f3b3.png)

**Comment by ChristineBoersen** [comment]
Until there is a solution, a work around is to tell Rocket.Chat to "Always Open in New Window" in the Video Conference -> Jitsi settings.
