### ISSUE TITLE
Asked twice to allow access to microphone

### ISSUE THREAD

**Issue by akuckartz** [jitsi/jitsi-meet#392]
When I load such a page https://beta.meet.jit.si/myprivatechannel (I am using a different channel) the browser (Iceweasel 41.0.2) asks twice if I allow access to a microphone. The system does not have a webcam.

**Comment by gpolitis** [comment]
I'm sorry that you have troubles running FF without a webcam. This is a known issue: #347. Closing as duplicate.

**Comment by foss-** [comment]
Why is this closed? @akuckartz correctly referenced this bug and mentioned, this is not resolved. I can confirm this is still a problem in Firefox 41.0.2.

**Comment by gpolitis** [comment]
If a user has both a mic and a video camera, then it's a technical limitation in our specific case to have two prompts. If one of the two devices is missing the user is unable to join the conference: #347. Not being prompted two times when one of the two devices is missing is part of #347.

**Comment by foss-** [comment]
Thanks for elaborating. All good.

**Comment by akuckartz** [comment]
I now have plugged in an old cheap webcam (which is recognized by the Debian system) and the result is a bit stranger:

1. Request to allow access to microphone 
2. Request to allow access to camera ("VGA Single Chip")
3. Request to allow access to microphone

But there is no picture. I will investigate further...
