### ISSUE TITLE
xcode10 integrates framework

### ISSUE THREAD

**Issue by WSX1994** [jitsi/jitsi-meet#3925]
Hi，In this case, xcode10 integrates framework with method of “xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive”. There are no files in the framework path. What is the reason?
<img width="639" alt="wechatimg1" src="https://user-images.githubusercontent.com/33861158/53397941-5e105980-39e3-11e9-89d8-74079b74df65.png">

**Comment by rutmb** [comment]
You should open original file, see in attachment
<img width="633" alt="screen shot 2019-02-26 at 13 50 53" src="https://user-images.githubusercontent.com/8993487/53407613-9efd7380-39cd-11e9-820d-14179fc905ab.png">

**Comment by WSX1994** [comment]
I tried that operation and it showed that I couldn't find the original file.

**Comment by WSX1994** [comment]
I put the framework into the project and run it under Xcode 10, and he prompted me for such a mistake.

dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/DAE05F87-A264-4A52-BBD2-3BFBA4CE6384/Frameworks/JitsiMeet.framework/JitsiMeet
  Expected in: /private/var/containers/Bundle/Application/DAE05F87-A264-4A52-BBD2-3BFBA4CE6384/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/DAE05F87-A264-4A52-BBD2-3BFBA4CE6384/Frameworks/JitsiMeet.framework/JitsiMeet

**Comment by rutmb** [comment]
Embed Jitsi framework in your project

**Comment by WSX1994** [comment]
I'm embedded in the project, it works well in Xcode 9, and it reports errors in Xcode 10. I wonder what they need to pay attention to when integrating with “xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive” in this way.

**Comment by saghul** [comment]
The command is correct. Have you modified the Jitsi Meet project files in any way?

**Comment by WSX1994** [comment]
I haven't made any changes. Integration under Xcode 9/swift 4.1.2 is good, but integration under Xcode 10/swift 4.2 is not good. Is the project not in line with swift 4.2 version?

**Comment by WSX1994** [comment]
Or do I need to do something else to integrate under Xcode 10/swift 4.2?

**Comment by rutmb** [comment]
Did you try legacy build system for Xcode 10? https://github.com/jitsi/jitsi-meet/pull/3660

**Comment by WSX1994** [comment]
I'll make these changes here first, and then reintegrate, right?
<img width="987" alt="pasted graphic 3" src="https://user-images.githubusercontent.com/33861158/53479815-d85cde80-3ab4-11e9-9b62-64cae06ccd91.png">

**Comment by rutmb** [comment]
Xcode -> File -> Workspace Settings -> Build system

**Comment by WSX1994** [comment]
Should both be chosen “legacy build system”？
<img width="531" alt="pasted graphic" src="https://user-images.githubusercontent.com/33861158/53480391-1575a080-3ab6-11e9-90ff-9835777c2f03.png">

**Comment by rutmb** [comment]
Only first one

**Comment by WSX1994** [comment]
Thank you very much for helping me solve this problem. I have run it successfully as you said.
