### ISSUE TITLE
How to build jitsi-meet and jitsi-meet-prosody debian package

### ISSUE THREAD

**Issue by reixd** [jitsi/jitsi-meet#393]
Hello,

how can I build the  jitsi-meet and jitsi-meet-prosody debian package?
Like the videobridge and jicofo this repo does not contain an ant build.xml file.
And "dh_make" does not work on the sources.

Warm Regards

**Comment by damencho** [comment]
As stated in the README of the project:
Please use the Jitsi dev mailing list to discuss before opening an issue on Github.

dpkg-buildpackage -A -rfakeroot -us -uc
