### ISSUE TITLE
MacOS camera access - works via focusmate but not on my own

### ISSUE THREAD

**Issue by neuropet** [jitsi/jitsi-meet#3930]
Have wanted to access the jitsi FMGroupRoom (https://meet.jit.si/FMGroupRoom
) but even though I have had no problem with focusmate test sessions and real sessions, this room (and also when I try to access jitsi indenepent of focusmate) yields an error message that jitsi is unable to access camea and I should either try again (restart browser, application etc) or contact the support group.
Which is what I am doing now after multiple efforts to restart and reload.

MacOS 10.13.6
Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by damencho** [comment]
Please use the community forum for question or problems.

What do you mean, on my own? That you have the error if you open two tabs in your browser? That is strange cause I can do that on macOS. Does https://appr.tc works for you if you use it that way?
