### ISSUE TITLE
DPKG configuration on Ubuntu fails

### ISSUE THREAD

**Issue by steinymity** [jitsi/jitsi-meet#3936]
## Description
---
I followed the installation procedure as described for ubuntu (https://jitsi.org/downloads/#stableline) by adding the apt-key and repository and installing `jitsi-meet` using apt-get.

## Current behavior
---
The installation didn't finish but stopped with an error in `jitsi-meet-prospody`'s postinst script:

> The given hostname does not exist in the config

Trying to fix the package with `apt install --fix-broken` yielded the same error.

Even worse, when I try to uninstall the package, dpkg throws the same error, so I cannot even uninstall the package.

## Expected Behavior
---
Installation and uninstallation should work.

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---
Ubuntu 18.04 LTS, amd64.

**Comment by steinymity** [comment]
Apparently, the command `prosodyctl cert generate $JICOFO_AUTH_DOMAIN` in the postinst script fails.

**Comment by damencho** [comment]
By any chance are you using minimal install images? There is a known issue there with packages not able to write in /usr/share/doc.

I had been testing ubuntu LTS few days ago without any problem.

**Comment by steinymity** [comment]
Well, I guess it's not a minimal system. However, I upgraded it from 16.04. `/usr/share/doc/` is definitely writeable for root. Btw, during installation I left the hostname field empty.

**Comment by damencho** [comment]
Well its not supposed to be empty.
