### ISSUE TITLE
interface_config.js has no effect on Jitsi-meet for iOS

### ISSUE THREAD

**Issue by marco-palumbo** [jitsi/jitsi-meet#3937]
I’ve integrated the Jitsi-meet framework in an iOS app that I’m developing. I need to disable the chat feature, so I’ve edited interface_config.js and removed the ‘chat’ item in the TOOLBAR_BUTTONS array, but this has no effect on the subsequent builds of Jitsi-meet framework: the Jitsi view will always show the chat button.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

Currently, interface_config.js is used only for the web part of jitsi-meet. To disable buttons for the mobile sdk, you need to modify the code.

**Comment by Test1923** [comment]
hello how to modify the code and which file please help me.

**Comment by Test1923** [comment]
![Screenshot 2020-10-02 at 5 07 50 PM](https://user-images.githubusercontent.com/72243754/94919240-d1d4eb00-04d1-11eb-9e61-77a95a813529.png)
