### ISSUE TITLE
Conversation 'admin' should not be able to UN-mute users

### ISSUE THREAD

**Issue by mammuth** [jitsi/jitsi-meet#394]
Expected:
- conversation admin is able to mute noisy users
- admin is able to unmute users that the admin muted before

However admin is able to toggle the mute setting of any user. So the admin is able to unmute a user, even with this user decided to mute himself. 

This is a heavy privacy issue, because when I press the mute button, I expect to stay muted, until I unmute myself.

**Comment by akuckartz** [comment]
:+1:

**Comment by paweldomas** [comment]
It used to work this way, but maybe something has been broken recently.

**Comment by paweldomas** [comment]
Or maybe not exactly this way, but admin was not able to unmute any users.

**Comment by damencho** [comment]
Fixed with 374763c. Disabled in jicofo the option users to unmute somebody except themselves.
