### ISSUE TITLE
Andorid app url broken on chrome (mobile) by target

### ISSUE THREAD

**Issue by Ark74** [jitsi/jitsi-meet#3941]
## Description
---
New installations have the url for the android app still broken on chrome mobile users.
I've found that with the commit: https://github.com/jitsi/jitsi-meet/commit/e729f0948cc57102bd8406b40cc1f92125c1603f there was an attempt to fix this, but seems that adding target attribute breaks the redirection.

Being the url structure:
```
<a class="deep-linking-mobile__href" href="intent://meet.instance.com/test#Intent;scheme=org.jitsi.meet;package=org.jitsi.meet;end" rel="noopener noreferrer" target="_blank">Continue to the app</a>
```

## Current behavior
---
Intent URL link is broken for android app through Google Chrome, thus users can't join the chat.
As a side note, Firefox can parse the current url state.

## Expected Behavior
---
Click on _"Continue to the app"_ and open room on the Jitsi meet android app.

## Possible Solution
---
Removing **target="_blank"** from url fixes de issue.
Testing on firefox seems fine, as it won't affect the action.
@saghul 
https://github.com/jitsi/jitsi-meet/blob/master/react/features/deep-linking/components/DeepLinkingMobilePage.web.js#L133

## Steps to reproduce
---
1. Create a new instance using apt repository.
2. Create a chat room.
3. Try to join from Google Chrome mobile browser using the _"Continue to the app"_ link.
4. Broken link with empty window

# Environment details
---
* Google Chrome Mobile - 72.0.3626.105
* Android Nougat - 7.0

**Comment by Ark74** [comment]
Any comments on this?

**Comment by saghul** [comment]
It was fixed. It took me 4-5 commits because it wasn't my best day, but it should be fixed now. I tested it yesterday on both Chrome and Firefox mobile.

**Comment by Ark74** [comment]
Hi @saghul !
Did you build the package yourself or are these part of the unstable repository already?

Cheers!

**Comment by saghul** [comment]
It’s part of unstable already.

**Comment by Ark74** [comment]
Great!!
Sorry the delay I noticed that is necessary **make sure you are using also the latest updates on all your mobile apps**.

Thanks @saghul I'll be closing this issue.
Best regards.
