### ISSUE TITLE
Quick Install not working on Debian 9.8

### ISSUE THREAD

**Issue by michaelschefczyk** [jitsi/jitsi-meet#3942]
## Description

My aim is to create a small jitsi-meet server based on a Debian 9.8 virtual machine with 4 GB of RAM and 4 processor cores. The target VM is behind NAT and I was not able to set it up based on quick install. Therefore, I tried simplified versions purely within the LAN, with fully permissive firewall settings and with jetty only as well as with Nginx. All led to the same error.

## Current behavior

Each user can set up conferences and see the own picture reflected via the browser. Just connecting two or more users does not work. Even before any user activty (and again immediately after each reboot), the logs contain:

/var/log/jitsi/jvb.log:

JVB 2019-03-04 21:34:32.852 SEVERE: [48] org.jitsi.videobridge.health.Health.log() Health check failed in 0ms:
java.lang.Exception: Failed to bind single-port
	at org.jitsi.videobridge.health.Health.doCheck(Health.java:222)
	at org.jitsi.videobridge.health.Health.doRun(Health.java:495)
	at org.jitsi.util.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

/var/log/jitsi/jicofo.log:

Jicofo 2019-03-04 21:33:58.934 WARNING: [26] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.192.168.1.38 error: <error type='cancel'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>java.lang.Exception: Failed to bind single-port</text></error>
Jicofo 2019-03-04 21:33:58.935 INFO: [50] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().261 Removing JVB: jitsi-videobridge.192.168.1.38
Jicofo 2019-03-04 21:33:58.936 INFO: [50] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.192.168.1.38

## Expected Behavior

Multiple users can be bridged into the conference. Logs without "Failed to bind single-port" and other errors.

If a general reason for this inability to bind ports can be detected, please consider explaining it in the quick install documentation.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

Most probably you have some other software that is using UDP port 10000 (maybe webmin), you either change that or set jvb to use another port https://github.com/jitsi/jitsi-videobridge/blob/master/doc/single-port.md#orgjitsivideobridgesingle_port_harvester_port1234

**Comment by michaelschefczyk** [comment]
Thank you very much! Two suggestions for the documentation do remain:
- Mention to change Webmin ports (in addition to the obvious 10000/tcp it uses (less obvious, but critical here) 10000/udp to listen to broadcasts, unless changed.
- Quick install only mentions port 10000/udp, while manual install mentions 10000:20000/udp

**Comment by manu-p** [comment]
Faced the same problem... Thanks guies.
