### ISSUE TITLE
Suggestion to improve quick install documentation

### ISSUE THREAD

**Issue by michaelschefczyk** [jitsi/jitsi-meet#3948]
Please consider two modifications to the quick install documentation:
- Mention to change Webmin ports (in addition to the obvious 10000/tcp it uses (less obvious, but critical here) 10000/udp to listen to broadcasts, unless changed).
- Quick install only mentions port 10000/udp, while manual install mentions 10000:20000/udp

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

> Mention to change Webmin ports ....

Webmin has nothing to do with jitsi-meet. We will not be able to collect and note all the software that uses that port, so I don't think that belongs to it. If you read the quick-install guide in the section for advanced config all the ports that are used are mentioned.

> Quick install only mentions port 10000/udp, while manual install mentions 10000:20000/udp
Manual install has a warning in the beginning saying it is not up-to-date. Single-port 10000 is the default for a few years now, so it is definitely not up to date, but it is there to show the basic steps that the debian scripts do while installing the whole deployment.
