### ISSUE TITLE
New installation of Jitsi-Meet with error  "ERR_TOO_MANY_REDIRECTS" 

### ISSUE THREAD

**Issue by emresaracoglu** [jitsi/jitsi-meet#3949]
Jitsi Meet Great software, thank you for this!

I've installed [Jitsi Meet](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) on Ubuntu 16.04 with quick setup. I get this error `ERR_TOO_MANY_REDIRECTS` with domain name but I can access with Local IP.

 I'm managemebt my domain names with HAproxy

The diagram is:

Cloudflare -> My server -> HAproxy -> Jitsi Meet _(on VM)_

Why do I get this error?

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

Apparently, something with redirects is looping but this is something in front of jitsi-meet. We only have one redirect in case of accessing http to redirect to https.

**Comment by emresaracoglu** [comment]
Where's the convention file?
I want to check the domain name in the file.

**Comment by damencho** [comment]
What do you mean by "convention file"?

Here are all the redirects:
nginx - https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L6
apache2 - https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example-apache#L7
jetty - https://github.com/jitsi/jitsi-videobridge/blob/master/src/main/java/org/jitsi/videobridge/rest/PublicClearPortRedirectBundleActivator.java#L168

**Comment by emresaracoglu** [comment]
Thank you. I can't find the Apache/Nginx configuration file on the server. Can you give me a path for this files.

**Comment by damencho** [comment]
/etc/nginx/sites-available/youdomain
And apache was something similar /etc/apache/sites-available/youdomain

**Comment by emresaracoglu** [comment]
Unfortunately there is no Nginx and Apache folder on the Jitsi server. I guess it needs to be installed Nginx before install Jitsi service(?)

**Comment by damencho** [comment]
By default it uses jetty. Are you sure your problem is there?

**Comment by emresaracoglu** [comment]
I found the solution with Docker on CentOS 7 VM

It works fine with this uncomment:  `ENABLE_HTTP_REDIRECT=0` and access: `http://192.168.1.20:8000` for HAproxy

But I can't use other features like this one at this time.
<hr>

**Installation steps are as follows:**


```
apt-get update -y
echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
apt-get update -y 
apt-get install apache2
apt-get -y install jitsi-meet
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```

Result:
[Apache Default page (Image)](https://d2hzlohlg26lpl.cloudfront.net/uploads/default/original/3X/b/5/b551e0ff1245234fd311629560c520677557dd9a.jpg)

If I don't install Apache;
_Result:_
`ERR_TOO_MANY_REDIRECTS`

Please show me the a way

Versions I tried:

Ubuntu 16.04 and 18 on VM and LXC

cc @damencho

**Comment by damencho** [comment]
How are you going to use the let's encrypt certificates which are installed on apache, when you are serving https with haproxy?

My proposal was to remove the redirect and make sure apache2 serves meet using http (you need all rules from the apache https part of the config) and this way you need to install certificates on haproxy and from there it serves it using http.

**Comment by varma-nexge** [comment]
hi, i have a issue in happroxy  configuration
Haproxy domain(video-conf.nexge.com)
videoconf-primary.nexge.com(jitsi-meet-server1)
videoconf-backup.nexge.com(jitsi-meet-server2)
able to open two severs individually but haproxy domain not able to open.
actually i have installed jitsi meet in 2 servers, now i want to keep these two domains in haproxy server,
my haproxy configuration

   log 127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block

defaults
        log     global
        mode    tcp
        option  tcplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000


frontend video
mode tcp
option httpclose
option forwardfor
reqadd X-Forwarded-Proto:\ https
bind video-conf.nexge.com:443
default_backend jitsi_meet

backend jitsi_meet
mode tcp
balance roundrobin
server meet1 videoconf-primary.nexge.com:443 check
server meet2 videoconf-backup.nexge.com:443 check
