### ISSUE TITLE
Please consider option for imprint and GDPR notice on welcome page

### ISSUE THREAD

**Issue by michaelschefczyk** [jitsi/jitsi-meet#3950]
Without an imprint and a GDPR notice, it is problematic to operate a self hosted jitsi meet instance in Europe without facing legal issues.

There should be a straightforward (i.e. without compiling, by just configuring configuration options in the Debian package verison & with adequate documentation) way to persistently (i.e. survive package updates) add short texts or links to provide a customized imprint and a GDPR notice. Other open source projects such as nextcloud or searx might serve as examples.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

The fact is that we do not store anything, the default deployment you have doesn't store any personal information, everything stays on the client browsers.
There are few hooks where anybody can add their content for example on the welcomepage:
https://github.com/jitsi/jitsi-meet/blob/master/static/welcomePageAdditionalContent.html
This is for example used on meet.jit.si to provide "Jitsi On Mobile" and "Jitsi For Slack" part.
