### ISSUE TITLE
Translation Issues [Turkish]

### ISSUE THREAD

**Issue by emresaracoglu** [jitsi/jitsi-meet#3964]
You can see "_Uzak Adres: Uzak Adresler: XXX_" string on the image. There are mistakes in the plural suffix.

> Uzak Adres: Remote Address
> Uzak Adresler: Remote Addresses 

``ler``: ``s`` (_plural suffix_)

![untssitled](https://user-images.githubusercontent.com/297968/53983518-0929bd00-4120-11e9-9fd5-b7a05c1db2fd.png)

Also;

![unti1tled](https://user-images.githubusercontent.com/297968/53983782-adabff00-4120-11e9-9f1e-e14ca41910ba.png)

on Docker version

**Comment by damencho** [comment]
You can use translate.jitsi.org to make changes to the translation and ping us when ready so we can push it.

Please for questions and problems use the community forum before opening new issues.

**Comment by damencho** [comment]
Thanks for the feedback and the PR, but use the online translation we have using pootle.

**Comment by emresaracoglu** [comment]
Okey 👍
