### ISSUE TITLE
Feature request: Share a single screen

### ISSUE THREAD

**Issue by brkeh** [jitsi/jitsi-meet#3969]
When multiple displays are in use, you can choose a single screen display and share just it. I think this would be useful.

Currently in Chromium and derivatives, you can choose to share all screens, a window or a browser tab. Currently in the [Jitsi Meet Electron](https://github.com/jitsi/jitsi-meet-electron) client you can choose to share all screens, or a window. Firefox seems to have interoperability issues with Chromium and also only allows a window to be shared.

**Comment by damencho** [comment]
This is something we do not control and needs implementation in the browser. You can send feature requests to chromium bug tracker and mozilla one.

Please for queries like this, question and problems use the community forum before opening new issues.

**Comment by brkeh** [comment]
Ok, I thought Jitsi Meet had control of it, my mistake, sorry. Thanks for the information
