### ISSUE TITLE
Problem with older version dependencies (3088)

### ISSUE THREAD

**Issue by issadorado** [jitsi/jitsi-meet#3973]
## Description
Runing npm install in version jitsi-meet_3088 there are a lot of dependencies that aren't available anymore. We are trying to compile jitsi 1.16.

## Current behavior
---
<img width="988" alt="Captura de pantalla 2019-03-08 a la(s) 8 26 55" src="https://user-images.githubusercontent.com/9956236/54054372-9b2cd680-41af-11e9-92af-4a4b4a625dd6.png">

## Expected Behavior
--- Getting all the dependecies and running ios version 

## Steps to reproduce
1.Download  jitsi-meet_3088
2. run npm install

**Comment by saghul** [comment]
I'm afraid that's not possible anymore.
