### ISSUE TITLE
Jitsi does not work on Brave Browser

### ISSUE THREAD

**Issue by krrisis** [jitsi/jitsi-meet#3978]
## Description

Jitsi doesn't launch the camera when you use brave browser

## Current behavior

Ask for microphone & camera access, light to indicate camera usage even goes on, but no stream is passed through. 

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details

- latest version of brave
- windows 10, latest version

**Comment by saghul** [comment]
What do you see in the JavaScript console?

**Comment by krrisis** [comment]
Okay, this time when accessing the page to get that info I briefly saw the message 'autoplay is not allowed'. 
Can't reproduce bcs I fixed it by clicking it & allowing it.

So I see that in Brave when you hit the 'lock' button to see if the site is secure (left in nav bar) you have microphone, camera & autoplay access. 
For Camera & Microphone the default setting is **ask**
For autoplay the default setting is **block** (!)

Chrome does *not* show this third point ( the autoplay setting) when I go to a jitsi video page, so I guess it just does not take it into account, it definitely does not block it. 

Below a screenshot of the settings & proof of the default setting in Brave, hope this helps:

![image](https://user-images.githubusercontent.com/6533925/54152693-202d1f80-443e-11e9-9922-8e5af42c0626.png)

**Comment by saghul** [comment]
Nice find! That must be new, it certainly wasn't there when I last fixed Brave support.

@virtuacoplenny IIRC you did something about autoplay, any thoughts on this?

**Comment by virtuacoplenny** [comment]
I haven't done any changes around autoplay; I actually think I've never done changes around auto-play for jitsi-meet ever. I downloaded brave though and do see the issue. If I go into the js console and manually run .play() on the video element then it does start to play the video properly.

**Comment by saghul** [comment]
Sorry Lenny, my wife’s must have crossed. Never mind. Well it looks like we have a problem :-/

**Comment by krrisis** [comment]
You should have left in that typo I see in my mail notifications, you should indeed never cross your wife(s) ;-) Well happy that I could flag something that could be an issue that needs looking at. Thx for building yr great product, big fan.

**Comment by johnxie** [comment]
Can confirm this!

**Comment by saghul** [comment]
If anyone knows how this should be handled a PR or a pointer would be most welcome.

**Comment by bendschs** [comment]
Can confirm this as well!

**Comment by matibak** [comment]
Confirmed on 
Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)

**Comment by allilengyi** [comment]
As mentioned [above](https://github.com/jitsi/jitsi-meet/issues/3978#issuecomment-471693374) you have to allow in brave browser autoplay for the site. This solved this issue for me.

**Comment by dud1337** [comment]
Worked for me in brave Version 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit) on Debian and Windows allowing camera and microphone from the usual prompts.

**Comment by medic17** [comment]
Can confirm this issue as well. brave 1.4.98

**Comment by rickgoud** [comment]
Any updates on this issue? The fix works, but confuses people a lot.
Awesome!

**Comment by bwheeler96** [comment]
I am having this issue in Brave 1.7.92, and allowing autoplay does not fix the issue for me.

**Comment by saghul** [comment]
I just tested it on Brave Beta (Version 1.8.75 Chromium: 81.0.4044.92 (Official Build) beta (64-bit)) and I no longer get the auto-play block, even if the domain is removed from the whitelist. Maybe they fixed it by allowing auto-play for WebRTC streams? I don't know. Give beta a try.

As for the problem itself, Brave caused it by introducing this "feature" for which no permission can be asked with Web APIs and it must have broken every single video conferencing site out there. You should be asking *them* to fix their browser.

**Comment by bwheeler96** [comment]
@saghul you are correct. Brave is aware of the issue and has said that 1.8 will fix the problem

https://github.com/brave/brave-browser/issues/9066

**Comment by saghul** [comment]
This is great to hear, thanks for the pointter @bwheeler96 !
