### ISSUE TITLE
Will there be mobile (Android, iOS) editions soon?

### ISSUE THREAD

**Issue by MRYingLEE** [jitsi/jitsi-meet#398]
Jitsi meet is great, but not available on mobiles.

I noticed there is a project on iOS. Do you have plan on Android also?

If you don't have plan, is there any technical obstacle to stop you to do so?

Thanks,
Ying

**Comment by emcho** [comment]
We do plan to do that but have no timeline.

Both Android and iOS would represent considerable efforts, which is the
main reason this hasn't happened yet.

Emil

On Thursday, 5 November 2015, MRYingLEE <notifications@github.com> wrote:

> Jitsi meet is great, but not available on mobiles.
>
> I noticed there is a project on iOS. Do you have plan on Android also?
>
> If you don't have plan, is there any technical obstacle to stop you to do
> so?
>
> Thanks,
> Ying
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jitsi/jitsi-meet/issues/398>.
>


-- 
sent from my mobile

**Comment by akuckartz** [comment]
There is no need to provide native apps. Jitsi Meet "only" needs to be usable with mobile browsers. See #335

**Comment by emcho** [comment]
Other than Bowser, which currently has very limited adoption, I am not
aware of any iOS browsers that have WebRTC support.

There's also a separate case to be made that even in the presence of
supporting browsers, native apps provide user experience that is closer to
what users expect.

Emil

On Friday, 6 November 2015, Andreas Kuckartz <notifications@github.com>
wrote:

> There is no need to provide native apps. Jitsi Meet "only" needs to be
> usable with mobile browsers. See #335
> <https://github.com/jitsi/jitsi-meet/issues/335>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jitsi/jitsi-meet/issues/398#issuecomment-154472369>.
>


-- 
sent from my mobile

**Comment by akuckartz** [comment]
Ah, the limitations of Safari... Maybe http://www.openwebrtc.org/bowser/ can be used. http://www.ericsson.com/research-blog/context-aware-communication/webrtc-in-webkit-with-openwebrtc/ also might become  relevant.

**Comment by MRYingLEE** [comment]
1. I confirm that Jitsi meet works on Android Chrome smoothly even on Android 2.2, although the UI is not as good as that on desktop.

2. The Browser by ericsson on iOS is not stable. I found a lot of complaints on Internet. So far there is no stable iOS browser to support WebRTC. An interesting project https://crosswalk-project.org/ claims they can have WebRTC support in their WebView. But it seems they focus on Android. And I have no idea on their real usage.

3. If Jitsi Meet is following WebRTC standard, maybe it is easy to adapt some Android/iOS WebRTC open source Apps to communicate with Jitsi Meet. In other way, a minimized mobile client instead of a full function one. Is this feasible?

Thank you all,
Ying

**Comment by bhatvv** [comment]
check this out .. http://lists.jitsi.org/pipermail/dev/2016-January/026486.html

**Comment by rwh23** [comment]
Hello, everyone.
I notice that MeetRTC_iOS demo app is not running with web browser. Can anyone advice me about that? (I already checked demo app and ...)
 http://lists.jitsi.org/pipermail/dev/2016-January/026486.html
Thanks

**Comment by hlevring** [comment]
I see that this issue is still open, but as I understand the project now includes both a client for iOS and Android based on react-native.

So perhaps this issue can be closed now, but perhaps with a little more information on how to get the mobile clients running and perhaps some prebuilt clients for iOS and Android so it is more simple for non-coders to try it out

**Comment by AndyNormore** [comment]
Yep still need an answer on this. Works on Chrome Mobile, but not when I'm running in a native app view.

Please help us out here with a Cordova / Phonegap plugin

**Comment by saghul** [comment]
> Please help us out here with a Cordova / Phonegap plugin

I don't think we will be making one.

**Comment by damencho** [comment]
Apps are in Apple store and Google Play.
