### ISSUE TITLE
HOW  to link new packages of reactnative  in the jitsi meet 

### ISSUE THREAD

**Issue by visheshtungare-hiteshi** [jitsi/jitsi-meet#3984]
i am working on the jitsi meet project 
now i want to link a new npm package in the jitsi meet   project 
how can i link them manually for the android 
as i didn't found 
`public class MainActivity extends ReactActivity ` where as i found
`public class MainActivity extends JitsiMeetActivity`

more over i didnt found the  getpackages() and even the mainApplication is not implements ReactApplication 

can someone guild me  how can i add new packages which require manual linking

**Comment by saghul** [comment]
You can add them here: https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java#L45

**Comment by rcidt** [comment]
@saghul is there any special process to link iOS dependency?

**Comment by saghul** [comment]
Nope
