### ISSUE TITLE
Jitsi has stopped recognizing my external USB camera

### ISSUE THREAD

**Issue by mcarballea** [jitsi/jitsi-meet#3988]
Have used Jitsi many times before and as of 1-1.5 weeks ago Jitsi will not recognize my external USB camera anymore. The camera works just fine for other applications on the same laptop. I use Chrome as my browser and the Logitech C905 webcam (https://support.logitech.com/en_us/product/webcam-c905)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues.

Can you check does it work here: https://appr.tc/?
