### ISSUE TITLE
Error after installing app on device

### ISSUE THREAD

**Issue by sampatparas13** [jitsi/jitsi-meet#3992]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.

![1552901425284](https://user-images.githubusercontent.com/7456495/54520634-274cb400-498f-11e9-8c28-7468aac7960f.JPEG)

After running app on android, I am getting error as shown in above image.
What am I doing wrong?
Is there any available tutorial to setup and build sample app on ubuntu for android?

**Comment by harishnv** [comment]
I assume you have executed command react-native run-android.
can you please post the output of this command?
meanwhile you can also try this  adb reverse tcp:8081 tcp:8081 and run above command again

**Comment by sampatparas13** [comment]
@harishnv 
I have only 1 device connected to the system
Below is the output I am getting : 

Task :app:installDebug
04:45:00 V/ddms: execute: running am get-config
04:45:00 V/ddms: execute 'am get-config' on '192.168.1.14:5555' : EOF hit. Read: -1
04:45:00 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'TITAN - 7.1.1' for app:debug
04:45:00 D/app-debug.apk: Uploading app-debug.apk onto device '192.168.1.14:5555'
04:45:00 D/Device: Uploading file onto device '192.168.1.14:5555'
04:45:00 D/ddms: Reading file permision of /home/nirav/Downloads/jitsi-meet-master/android/app/build/outputs/apk/debug/app-debug.apk as: rw-rw-r--
04:45:10 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
04:45:13 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on '192.168.1.14:5555' : EOF hit. Read: -1
04:45:13 V/ddms: execute: returning
04:45:13 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
04:45:13 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on '192.168.1.14:5555' : EOF hit. Read: -1
04:45:13 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 47s
225 actionable tasks: 6 executed, 219 up-to-date
Running adb -s 192.168.1.14:5555 reverse tcp:8081 tcp:8081
error: more than one device/emulator
Could not run adb reverse: Command failed: adb -s 192.168.1.14:5555 reverse tcp:8081 tcp:8081
Starting the app on 192.168.1.14:5555 (adb -s 192.168.1.14:5555 shell am start -n org.jitsi.meet/org.jitsi.meet.MainActivity)...
Starting: Intent { cmp=org.jitsi.meet/.MainActivity }

**Comment by harishnv** [comment]
@sampatparas13  your log shows 
error: more than one device/emulator
Could not run adb reverse: Command failed: adb -s 192.168.1.14:5555 reverse tcp:8081 tcp:8081
are you running emulator. 
check output of 
adb devices

**Comment by sampatparas13** [comment]
@harishnv 
On reading error, I did check adb devices
It shows only 1 device

**Comment by harishnv** [comment]
Have tried starting react-native (react-native start) server and realod application.

**Comment by saghul** [comment]
What version of Android Studio are you running?

**Comment by sampatparas13** [comment]
@harishnv below link worked for me 
[https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff](url)

**Comment by sampatparas13** [comment]
@saghul Android Studio 3.3.2

**Comment by sampatparas13** [comment]
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

This command saved my day.
Closing issue

**Comment by zhenghow93** [comment]
For me, it seems like it's caused by Android's security policy which blocks out clear text communication. Check this out: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
