### ISSUE TITLE
Recording Failed to start

### ISSUE THREAD

**Issue by farhan9876** [jitsi/jitsi-meet#3993]
I am using Jitsi Meet external API and getting message "Recording failed to start" when clicking on "Start Recording" button. Not getting any specific error or any error on console.
Tried in Chrome and Firefox. Also tried changing room name.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

Which deployment are you using? Is it meet.jit.si?

**Comment by farhan9876** [comment]
Yes

**Comment by damencho** [comment]
I just tried and there are recorders, maybe it was a temporary issue.

**Comment by farhan9876** [comment]
I am still getting same error

**Comment by damencho** [comment]
Can you send a link so I can test?

**Comment by farhan9876** [comment]
http://72.52.162.14:5001/Presentation/AES/

**Comment by damencho** [comment]
That will never work, you need first to make sure your link is available under https.

**Comment by farhan9876** [comment]
I also tried by uploading on an https link but still not working.
https://clinicalpearl.com/AES/

**Comment by damencho** [comment]
Hey I will move the conversation in the community forum.
