### ISSUE TITLE
The button "More actions" rest while there is nothing to see

### ISSUE THREAD

**Issue by PapyrusAdmin** [jitsi/jitsi-meet#3994]
![Sans titre](https://user-images.githubusercontent.com/46884196/54602080-e9a86380-4a40-11e9-91c4-73d86455e898.png)

**Comment by damencho** [comment]
Please when reporting problems or have questions use our community forum before opening new issues.

Can you give more details? Where do you see this? Is it meet.jit.si? Is it on a self-hosted deployment? If yes, then what is installed, just default deployment, no additional services configured? What is the browser and its version? Screen resolution? Any javascript console errors that you see?

**Comment by PapyrusAdmin** [comment]
Hello,

I see this on the docker jitsi meet in local on my computer. It(s a  self-hosted deployment.

I juste configure this : 
` interfaceConfigOverwrite: {
                    DEFAULT_REMOTE_DISPLAY_NAME: 'Papyrus Guest',
                    DEFAULT_LOCAL_DISPLAY_NAME: 'Papyrus Guest',
                    SHOW_JITSI_WATERMARK: false,
                    SHOW_WATERMARK_FOR_GUESTS: false,
                    SHOW_BRAND_WATERMARK: false,
                    BRAND_WATERMARK_LINK: '',
                    SHOW_POWERED_BY: false,
                    SHOW_DEEP_LINKING_IMAGE: false,
                    GENERATE_ROOMNAMES_ON_WELCOME_PAGE: false,
                    DISPLAY_WELCOME_PAGE_CONTENT: false,
                    APP_NAME: 'Papyrus',
                    NATIVE_APP_NAME: 'Papyrus',
                    PROVIDER_NAME: 'Papyrus',
                    LANG_DETECTION: true,
                    INVITATION_POWERED_BY: false,
                    TOOLBAR_BUTTONS: [
                        'microphone', 'camera', 'hangup', 'chat', 'desktop'
                    ],
                },`

It's on all browser and a screen resolution >768px
There aren't any console error

**Comment by hristoterezov** [comment]
Thanks for the report! 

I guess we are not handling correctly the use case when you don't have buttons in the overflow menu. Maybe I broke it with my recent changes about the toolbar resize...

I will have a deeper look in the code and return back with more information soon!
