### ISSUE TITLE
JitsiMeetConferenceOptions class not found with the last android SDK

### ISSUE THREAD

**Issue by oscarito9410** [jitsi/jitsi-meet#4000]
Hi, I'm using the last SDK version in my app, this is how my build.gradle looks like:

![Captura de pantalla 2019-03-20 a la(s) 20 46 30](https://user-images.githubusercontent.com/13366923/54730976-50b53d80-4b51-11e9-9bda-9925cb3bae03.png)

apparently the sdk implementation is added correctly to my proyect, however when i try to use  **sdk.JitsiMeet and  
sdk.JitsiMeetConferenceOptions**
classes are not found. The only clases available by the SDK are _JitsiView, JitsiMeetActivity, JitsiMeetActivityInterface, JitsiMeetViewAdapter and JitsiMeetViewListener_

Please could you tell me where is the error with my implementation?

Thanks in advance

**Comment by saghul** [comment]
master has been updated with a new SDK API which is unreleased yet. We plan to release it shortly, but in the meantime, please read the old documantion here: https://github.com/jitsi/jitsi-meet/blob/4b99caa1a9b96390783037c905167352b77d6523/android/README.md

**Comment by oscarito9410** [comment]
Thanks 👍
