### ISSUE TITLE
Xcode9 build error

### ISSUE THREAD

**Issue by lipengda** [jitsi/jitsi-meet#4001]
by using CocoaPods

iOS model : iPhone6 Plus
iOS version : 10.2
Xcode version : 9.4.1

crash:
dyld: Symbol not found: _$SBOWV
  Referenced from: /private/var/containers/Bundle/Application/FB4EDB3A-DC1F-46A6-9F2C-08A18A025410/jitsi-meet-iOS.app/Frameworks/JitsiMeet.framework/JitsiMeet
  Expected in: /private/var/containers/Bundle/Application/FB4EDB3A-DC1F-46A6-9F2C-08A18A025410/jitsi-meet-iOS.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/FB4EDB3A-DC1F-46A6-9F2C-08A18A025410/jitsi-meet-iOS.app/Frameworks/JitsiMeet.framework/JitsiMeet

**Comment by lipengda** [comment]
podfile:

platform :ios, '10.0'

workspace 'jitsi-meet-iOS.xcworkspace'

target 'jitsi-meet-iOS' do
    project 'jitsi-meet-iOS.xcodeproj'
    
    pod 'JitsiMeetSDK'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

**Comment by saghul** [comment]
You need Xcode 10.

**Comment by lipengda** [comment]
Thank you very much.
