### ISSUE TITLE
Jitsi Install review November 2015

### ISSUE THREAD

**Issue by StreamTitan** [jitsi/jitsi-meet#401]
There are so many things wrong with Jitsi that it begs belief that they market this as a "quick install". I really wonder what are they thinking when in the past year and more, there is still yet to be a detailed install demo. If even the bash history of a successful install.

Packages are deprecated, files to modify have no info on where the files are found which I thought was really funny. "Yeah, modify these files...but we're not saying where they are".

If you fall for it, and take the quick install, you're 100% running into an Ningx index page. Yes, if you follow their instructions word for word, that's the page you end up on, NOT the video conference page.

So until Jitsi decides to give a more detailed process for the manual install OR a Quick Install which solves the Nginx issue (Even Hak5 had problems with that in their demo), stay FAR away or wear a helmet because you'll be banging your head in just trying to install it.

Try doing a YouTube search for a demo install that isn't over a year old from Jitsi.
I mean its a Quick Install right? Should be a snap for them to do. 
They don't even have to speak, just capture the screen on an "quick install" from scratch and guess what? There will be tons more users and publicity of the product instead of headaches and lots of lost hours.

**Comment by damencho** [comment]
Please use the mailinglist before creating issues, so we can discuss the problems you have. 

Describe which packets you found deprecated and the problems you found with the "quick install". Which OS and its version are you using. What is your nginx issue?
Which versions of prosody and nginx are you using, versions coming with the official Ubuntu/Debian repositories or using other repos?

Manual install had been deprecated, we try to update from time to time, for those who needs information how the different components are configured. But we always recommend using the quick install, we try keeping the debian package configuration updated keeping compatibility with older versions when adding new stuff.

**Comment by StreamTitan** [comment]
Hi,

I've been trying to the the "quick install" since 11.00 this morning.
Its now 21.31 yep that's how long I've been trying to get something that went further than the default nginx page.

I've googled and youtubed for any info which would resolve what can only be an configuration issue with nginx and passing the info to / from jitsi meet.

Each time I scrubbed the server and started again from scratch but no luck so far.

I have previous changed as much of what was advised eg. hostname, conf files after struggling to get an install from the quick install but these didn't help either.

How I scrubbed the server again and have just done the quick install again.
I don't have the mental energy to try again but its there. I am sure that it must be something really simple but without proper docs for these things how can we go further?

Shell access if needed is:
server ip: 188.166.88.186
login: root
password: gfdsa54s

I have a domain I intend to use - konferensee.com and I have entered this when asked for 
the Jitsi-videobridge package that needs the DNS hostname of the instance.

hostname -f shows the domain as well as it should be - konferensee.com

I really cannot think of how different to do this again. If you have a better doc or would like to take a look feel free to login and change whatever see, that would be great, but after 10hrs on this, the frustration is wearing me down.

**Comment by damencho** [comment]
I'm not sure how you are testing, but this works for me. I just pointed my
browser to your domain (opened two tabs) and everything is fine, video also.

If you are trying with your ip-address, you need to further configure nginx
that the jitsi-meet virtual host to be your default server, but this is
beyond quick install or jitsi-meet configuration.

**Comment by StreamTitan** [comment]
How did you get to see it? konferensee.com gives me the ngix page on all the browsers I try

**Comment by damencho** [comment]
Yeah I've just opened the address konferensee.com. Maybe you have some
wrong entry in /etc/hosts ... It is strange.

**Comment by zerohalo** [comment]
I also had no problems testing against your domain. I highly suggest, however, that you destroy this box and start again as at _least_ 100 people are watching this project and now have your root password.

**Comment by StreamTitan** [comment]
Thank you. It was my intention to destroy after any success.
The main thing was to learn and start over again.

**Comment by StreamTitan** [comment]
what browser did you try. After you notified you saw the site I was able to load it in IE. However the nginx default page is the only thing chrome is showing

**Comment by zerohalo** [comment]
Chrome Version 46.0.2490.80 (64-bit) here

**Comment by damencho** [comment]
Chrome.

**Comment by zalmoxisus** [comment]
Use Control + Shift + R or Control + F5.

**Comment by StreamTitan** [comment]
I downloaded FF to try it there and it worked. Will have to go deeper in this computer to see what the problem is because the cache is cleared etc.

I have to hold my hands up and say that I was wrong.
The quick install does work as intended. Apologies.

**Comment by gpolitis** [comment]
@StreamTitan I can understand your frustration if you've been fighting to get something working for hours and it's still not working. But please keep in mind that jitsi meet is a relatively complex system that's composed of several components in order to work properly. In case something goes wrong you might have to get your hands dirty. Also, if you think documentation is lacking in some places (which I'm sure it is, and we're sorry for this but we're trying our best), please keep in mind that this is an open source project and any contributions would be highly appreciated. Or, if you have any recommendations on how to improve documentation, again we would love to hear them and try to do so.
