### ISSUE TITLE
iOS recording is not available.

### ISSUE THREAD

**Issue by mewkill** [jitsi/jitsi-meet#4012]
Hi,
I would like you to support me, I am integrating the iOS SDK, but in the options I don't see the option to **START RECORDING**. I share a screenshot of how the current menu is displayed.

![Screenshot](https://user-images.githubusercontent.com/13002043/54796494-0ea1ff80-4c16-11e9-8d77-04eda88a7efb.jpeg)

**Comment by damencho** [comment]
Please, when you have questions and problems use the community forum before opening new issues.

At some point, we disabled recording option for ios as the app was rejected from the store because of that. Apple allows only local recordings which with jibri cannot happen at the moment.

**Comment by mewkill** [comment]
Lo siento, la próxima vez pondré la pregunta en la comunidad. 
¿Tendrán documentación acerca de la integración de Jitsi y Jibri con Swift (iOS)?

**Comment by Bellusterra** [comment]
Is it that you can’t have the option to self host and record? Just a little confused the 8x8 app has it enabled on iOS?
![37E51B1D-E519-44A0-B15F-45728096C348](https://user-images.githubusercontent.com/25701774/69898275-8e35c000-139a-11ea-90fc-f9868f008f47.png)

**Comment by Bellusterra** [comment]
I’ll try to submit to the forum as well.

**Comment by saghul** [comment]
The 8x8 app uses a slightly different mechanism for recordings on the backend and thus we are able to enable it.

On Jitsi we can only support Dropbox and Apple rejected the app because of this.

Why not use the same thing as we do for 8x8 then? We don’t want to store the recordings, hence the Dropbox integration.

**Comment by Bellusterra** [comment]
Didn’t know we could?

**Comment by saghul** [comment]
If you use the SDK on your own app you can enable it with the “ios.recording.enabled” feature flag.

**Comment by Bellusterra** [comment]
But as @damencho mentioned it would not pass getting approved by Apple correct? so it would need to be reconfigured as was done in the 8x8 app.

**Comment by saghul** [comment]
Not necessarily. If your app already requires an account of some sort you may get lucky. It’s anybody’s guess really, since we don’t make the rules. Just try it out.

**Comment by Bellusterra** [comment]
Okay that makes sense now thank you @saghul for clarifying. It must be related to having an account before the recording feature is allowed in the app. Where jitsi doesn’t require an account to use/record the 8x8 and other apps that have in app recording do... but agree they make the rules and have their own discretion on what goes and what doesn’t.

**Comment by Seesi** [comment]
> If you use the SDK on your own app you can enable it with the “ios.recording.enabled” feature flag.

@saghul Ermm where to i find this you talk about "ios-recording.enable" feature flag

**Comment by akalana** [comment]
> If you use the SDK on your own app you can enable it with the “ios.recording.enabled” feature flag.
HI @saghul 
Can you please explain more?

**Comment by Test1923** [comment]
hello every one 

I am using Jitsi iOS SDK
I want to hide more setting button how can hide help me.

Thank you all for advance
