### ISSUE TITLE
Can I connect to a Scheduled Live Stream on YouTube?

### ISSUE THREAD

**Issue by nagybarnabas** [jitsi/jitsi-meet#4013]
I understand that by adding my live stream key from YouTube will let me stream on Jitsi Meet. But what about scheduled streams? How do I go about connecting that with Jitsi Meet?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum.

Have you tried enabling the google API. It will query youtube servers for configured events for your account and will show them in a drop down list. https://github.com/jitsi/jitsi-meet/blob/master/doc/integrations.md

**Comment by nagybarnabas** [comment]
Where is the forum? I don't understand the instructions on the link? Is this so complicated?

**Comment by damencho** [comment]
Instructions for using the forum are even added in the template of the issues: 
```
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.
```

The instructions are how to enable it on your deployment.

Have you tried https://meet.jit.si, do you see the scheduled stream there?
