### ISSUE TITLE
uninstall error

### ISSUE THREAD

**Issue by asd51731** [jitsi/jitsi-meet#4015]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

My system is ubuntu18.04, I install jitsi-meet following https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md. Install jitsi-meet first time it suggest to write FQDN hostname, but after first time it skip this step and never suggest to write the FQDN hostname which confused me a lot. When I uninstall jitsi-meet by using "apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-web jicofo jitsi-videobridge" each time it will give me an error  
 '''
Errors were encountered while processing:
   jitsi-meet-web-config
W: Can not find PkgVer for 'jicofo'
W: Can not find PkgVer for 'jigasi'
W: Can not find PkgVer for 'jitsi-meet'
W: Can not find PkgVer for 'jitsi-meet-prosody'
W: Can not find PkgVer for 'jitsi-videobridge'
E: Sub-process /usr/bin/dpkg returned an error code (1)
'''
and I have more action to uninstall jitsi-meet-web-config
---

## Current behavior

install jitsi-meet more than one time it will not prompt the FQDN hostname.  
uninstall jitsi-meet it will not uninstall jitsi-meet-web-config successfully.

---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Please when you have problems or questions first use the community forum before opening new issues.

I just tested it on 18.04 and all worked fine.

```
# history
    1  echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
    2  wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
    3  apt-get update
    4  apt-get install jitsi-meet
    5  apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-web jicofo jitsi-videobridge
    6  history
```

Did you have any web server apache2, nginx installed before installing jitsi-meet?

**Comment by asd51731** [comment]
Ok, I will check it again. Thanks

**Comment by Fuseteam** [comment]
i have this issue :V
```
sudo apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-web jicofo jitsi-videobridge
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'jigasi' is not installed, so not removed
Package 'jitsi-meet-web' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  libappindicator1 libdbusmenu-gtk4 libindicator7 libqt4-designer libqt4-help
  libqt4-scripttools libqt4-svg libqt4-test libqtassistantclient4 lua-bitop lua-event
  lua-expat lua-filesystem lua-sec lua-socket lua5.1 prosody python-qt4 python-sip sdparm
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  jicofo* jitsi-meet* jitsi-meet-prosody* jitsi-meet-web-config jitsi-videobridge*
0 upgraded, 0 newly installed, 5 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 36.7 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 219834 files and directories currently installed.)
Removing jitsi-meet-web-config (1.0.3729-1) ...
apache2.service is not active, cannot reload.
invoke-rc.d: initscript apache2, action "reload" failed.
dpkg: error processing package jitsi-meet-web-config (--remove):
 installed jitsi-meet-web-config package post-removal script subprocess returned error exit status 1
Removing jicofo (1.0-508-1) ...
dpkg: warning: ignoring request to remove jitsi-meet, only the config
 files of which are on the system; use --purge to remove them too
dpkg: warning: ignoring request to remove jitsi-meet-prosody, only the config
 files of which are on the system; use --purge to remove them too
dpkg: warning: ignoring request to remove jitsi-videobridge, only the config
 files of which are on the system; use --purge to remove them too
Errors were encountered while processing:
 jitsi-meet-web-config
W: Can not find PkgVer for 'jitsi-meet'
W: Can not find PkgVer for 'jitsi-meet-prosody'
W: Can not find PkgVer for 'jitsi-videobridge'
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by damencho** [comment]
If you fix `invoke-rc.d: initscript apache2, action "reload" failed.` the purge will pass. This is fixed in the latest versions.

**Comment by Fuseteam** [comment]
I just installed this week tho....
how do i fix that?

**Comment by Fuseteam** [comment]
Just logging that i had to uninstall apache to get it to purge
but that it left a systemd job behind
