### ISSUE TITLE
televisit 

### ISSUE THREAD

**Issue by ntice1842** [jitsi/jitsi-meet#4017]
didn't work  i could not see or hear the person but i could see myself and he had the same issue.

**Comment by damencho** [comment]
Please, when you have problems or questions use the community forum before opening an issue.

Is this on meet.jit.si or on your own deployment?
If it is your own deployment, check the advanced section of the quick-install guide: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
