### ISSUE TITLE
Documentation: How to deactivate callstats.io ?

### ISSUE THREAD

**Issue by akuckartz** [jitsi/jitsi-meet#402]
Maybe I have overlooked something, but how can one deactive callstats.io ?

**Comment by emcho** [comment]
I am not sure I understand. Right now it has to be explicitly activated with account specific fields.

**Comment by gpolitis** [comment]
@akuckartz if you mean to not load the JS file when callstats.io is not configured/activated, then the answer is no as we currently don't support that. Incidentally, there's been a discussion about that today in the jitsi-dev mailing list [here](http://lists.jitsi.org/pipermail/dev/2015-November/025676.html).

**Comment by akuckartz** [comment]
@gpolitis Yes, that is what I mean. I agree with the suggestion by https://theintercept.com/staff/micah-lee/

**Comment by bickelj** [comment]
Simply comment out or delete line ~14 here: https://github.com/jitsi/jitsi-meet/blob/master/index.html

**Comment by damencho** [comment]
This is how it works nowadays. Disable callstats and its lib loading by just not configuring it.
