### ISSUE TITLE
Android release build crash

### ISSUE THREAD

**Issue by ms747** [jitsi/jitsi-meet#4020]
The released app crash when startup.

I cloned the git repo jitsi/jitsi-meet.
Run npm install. 
Run make.
Install appropriate certificates for signed app.
Run ./gradlew assembleRelease in android/.
Run ./gradlew installRelease.

Android SDK 28
Build Tool 28.0.3

I was able to gather some info from logcat when I launch the app.

`E/unknown:ViewManager(10715): Error while updating prop autoComplete
E/unknown:ViewManager(10715): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.as$j.a(ViewManagersPropertyCache.java:83)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.aq$b.a(ViewManagerPropertyUpdater.java:132)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.aq.a(ViewManagerPropertyUpdater.java:51)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.j.a(NativeViewHierarchyManager.java:265)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.an$e.a(UIViewOperationQueue.java:200)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.an$h.c(UIViewOperationQueue.java:1109)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.an$h.a(UIViewOperationQueue.java:1080)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.e.b(GuardedFrameCallback.java:29)
E/unknown:ViewManager(10715): 	at com.facebook.react.modules.core.e$b.b(ReactChoreographer.java:166)
E/unknown:ViewManager(10715): 	at com.facebook.react.modules.core.a$a$1.doFrame(ChoreographerCompat.java:84)
E/unknown:ViewManager(10715): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/unknown:ViewManager(10715): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/unknown:ViewManager(10715): 	at android.view.Choreographer.doFrame(Choreographer.java:549)
E/unknown:ViewManager(10715): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/unknown:ViewManager(10715): 	at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:ViewManager(10715): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:ViewManager(10715): 	at android.os.Looper.loop(Looper.java:135)
E/unknown:ViewManager(10715): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:ViewManager(10715): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/unknown:ViewManager(10715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/unknown:ViewManager(10715): Caused by: java.lang.NoSuchMethodError: No virtual method setImportantForAutofill(I)V in class Lcom/facebook/react/views/textinput/c; or its super classes (declaration of 'com.facebook.react.views.textinput.c' appears in /data/app/org.jitsi.meet-1/base.apk)
E/unknown:ViewManager(10715): 	at com.facebook.react.views.textinput.ReactTextInputManager.setTextContentType(ReactTextInputManager.java:589)
E/unknown:ViewManager(10715): 	... 25 more
E/AndroidRuntime(10715): FATAL EXCEPTION: main
E/AndroidRuntime(10715): Process: org.jitsi.meet, PID: 10715
E/AndroidRuntime(10715): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'autoComplete' of a view managed by: AndroidTextInput
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.as$j.a(ViewManagersPropertyCache.java:95)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.aq$b.a(ViewManagerPropertyUpdater.java:132)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.aq.a(ViewManagerPropertyUpdater.java:51)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.j.a(NativeViewHierarchyManager.java:265)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.an$e.a(UIViewOperationQueue.java:200)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.an$h.c(UIViewOperationQueue.java:1109)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.an$h.a(UIViewOperationQueue.java:1080)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.e.b(GuardedFrameCallback.java:29)
E/AndroidRuntime(10715): 	at com.facebook.react.modules.core.e$b.b(ReactChoreographer.java:166)
E/AndroidRuntime(10715): 	at com.facebook.react.modules.core.a$a$1.doFrame(ChoreographerCompat.java:84)
E/AndroidRuntime(10715): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/AndroidRuntime(10715): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(10715): 	at android.view.Choreographer.doFrame(Choreographer.java:549)
E/AndroidRuntime(10715): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(10715): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(10715): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10715): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10715): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10715): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(10715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(10715): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.as$j.a(ViewManagersPropertyCache.java:83)
E/AndroidRuntime(10715): 	... 22 more
E/AndroidRuntime(10715): Caused by: java.lang.NoSuchMethodError: No virtual method setImportantForAutofill(I)V in class Lcom/facebook/react/views/textinput/c; or its super classes (declaration of 'com.facebook.react.views.textinput.c' appears in /data/app/org.jitsi.meet-1/base.apk)
E/AndroidRuntime(10715): 	at com.facebook.react.views.textinput.ReactTextInputManager.setTextContentType(ReactTextInputManager.java:589)`

**Comment by ms747** [comment]
I was able to get release build working on android emulator. But doesn't work on any real devices.

**Comment by saghul** [comment]
What Android devices did you test it on? What Android versions were they running?

**Comment by ms747** [comment]
Hello. 
I'm using Motorola moto g (5.1), Motorola moto g turbo (6.0.1), and a redmi note 3 (7.0).
Also I am using an Android Pie (ver 9) emulator where everthing works fine.

**Comment by ms747** [comment]
after downgrading to react-native version 0.58.6. I'm getting different error.

`E/ReactNativeJS( 6532): Can't find variable: Symbol
E/AndroidRuntime( 6532): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 6532): Process: org.jitsi.meet, PID: 6532
E/AndroidRuntime( 6532): com.facebook.react.common.JavascriptException: Can't find variable: Symbol, stack:
E/AndroidRuntime( 6532): <unknown>@952:294
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:967
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): <unknown>@371:3360
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:967
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): <unknown>@370:85
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:967
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): <unknown>@369:552
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:967
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): <unknown>@368:85
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:967
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): <unknown>@12:156
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:967
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): <unknown>@11:30
E/AndroidRuntime( 6532): _@2:1514
E/AndroidRuntime( 6532): d@2:897
E/AndroidRuntime( 6532): o@2:435
E/AndroidRuntime( 6532): global code@1482:4
E/AndroidRuntime( 6532): 
E/AndroidRuntime( 6532): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
E/AndroidRuntime( 6532): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
E/AndroidRuntime( 6532): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6532): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6532): 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
E/AndroidRuntime( 6532): 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
E/AndroidRuntime( 6532): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime( 6532): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 6532): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6532): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E/AndroidRuntime( 6532): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6532): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
E/AndroidRuntime( 6532): 	at java.lang.Thread.run(Thread.java:818)
E/ReactNativeJS( 6532): Module AppRegistry is not a registered callable module (calling runApplication)
E/ReactNativeJS( 6532): Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)`

**Comment by saghul** [comment]
You cannot use 0.58. 0.59 is a requirement since it updates the JS runtime.

**Comment by saghul** [comment]
Looks like you are running into this: https://github.com/facebook/react-native/issues/23934

Seems fixed in 0.59.2, I'll update as soon as it's available and drop a line here.

**Comment by ms747** [comment]
I am following this issue.

https://github.com/facebook/react-native/issues/23934#issue-421171795

**Comment by ms747** [comment]
@saghul Yeah thanks a lot. So its a react-native issue more than a jitsi issue.

**Comment by ms747** [comment]
Updating react-native to 0.59.2 solves the issue. Please update package.json accordingly.
