### ISSUE TITLE
Cannot compile Jitsi-Meet on Ubuntu 14.04

### ISSUE THREAD

**Issue by luciash** [jitsi/jitsi-meet#403]
I used the recommended way on https://github.com/jitsi/jitsi-meet to build from source in my jitsi-meet-bootstrap fork (I guess I need to run the `npm install` and `make` commands with sudo too, or should not that be necessary?):

    sudo apt-get install npm nodejs-legacy
    cd jitsi-meet-bootstrap
    sudo npm install

then

    sudo make

there are some errors:
http://pastebin.com/ReMvgYnu

Any ideas?

**Comment by luciash** [comment]
OK, seems I forgot that command:
```
sudo npm install -g browserify
```

But even when I run it and browserify seems to install without errors I still get this error after running make again:
```
...
npm http 304 https://registry.npmjs.org/utf8/2.0.0
npm http 304 https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http 304 https://registry.npmjs.org/blob/0.0.2
/bin/sh: 1: ./node_modules/.bin/browserify: not found
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.
./node_modules/.bin/uglifyjs -p relative ./app.bundle.js -o ./app.bundle.min.js --source-map ./app.bundle.min.map --in-source-map ./app.bundle.js.map
make: ./node_modules/.bin/uglifyjs: Command not found
make: *** [uglify] Error 127
```

**Comment by gpolitis** [comment]
The instructions where unclear but @damencho fixed them today with [this](https://github.com/jitsi/jitsi-meet/commit/b6f9cf93d501427086a462e3b13fa7e52f96cfac). You shouldn't have to run any command with `sudo`. Normally, on a clean clone, you just have to run `npm install && make`? Can you please try again on a clean clone?

**Comment by luciash** [comment]
Yeah, man! It worked now! :+1: Thanks! Turns out I've got an unwritable tmp/ in my home dir for some reason (owner was root:root) so that is why I assumed I need to run it as sudo/root. When I removed it, it works perfectly now.

**Comment by gpolitis** [comment]
Cool, I'm glad it worked :+1: I would have never guessed that :-)
