### ISSUE TITLE
Xcode 10.2 build error

### ISSUE THREAD

**Issue by lipengda** [jitsi/jitsi-meet#4035]
error: The following binaries use incompatible versions of Swift:
/Users/lipengda/Library/Developer/Xcode/DerivedData/jissi-iOS-5-dmqgmijmuyjvvzcuvqkcwnjblhid/Build/Products/Debug-iphoneos/jissi-iOS-5.app/Frameworks/JitsiMeet.framework/JitsiMeet
/Users/lipengda/Library/Developer/Xcode/DerivedData/jissi-iOS-5-dmqgmijmuyjvvzcuvqkcwnjblhid/Build/Products/Debug-iphoneos/jissi-iOS-5.app/jissi-iOS-5

iOS model : iPhone6s
iOS version : 10.2
Xcode version : 10.2

**Comment by saghul** [comment]
The SDK hasn't been built with Xcode 10.2 yet. This will happen in the next couple of weeks. Until then you can build it yourself.

**Comment by lipengda** [comment]
Thanks a lot.

**Comment by andremvb** [comment]
@saghul there is some guide? I cant figure out how to build the project without Xcode :(. And when do you think we will have Xcode 10.2 compatibility?

**Comment by saghul** [comment]
@andremvb a guyide for what? If you need Xcode 10.2 you will need to compile the SDK yourself. The instructions are here: https://github.com/jitsi/jitsi-meet/tree/master/ios#builduing-it-yourself

**Comment by saghul** [comment]
FYI, SDK 2.1.0 is out, it was built with Xcode 10.2.

**Comment by MansoorB** [comment]
@saghul path to sdk?

**Comment by saghul** [comment]
https://cocoapods.org/pods/JitsiMeetSDK
