### ISSUE TITLE
How do I disable error handling feature for android app? (Red screen on crash)

### ISSUE THREAD

**Issue by sampatparas13** [jitsi/jitsi-meet#4042]
Whenever there's some crash in app, at shows up as below, How do I disable such error? 

![29999807-5094ea0a-901b-11e7-86ab-63b7674324ef](https://user-images.githubusercontent.com/7456495/55160740-00aa2c80-518a-11e9-8a74-07d67582b1be.png)

**Comment by saghul** [comment]
That is a develoment mode feature, it's automatically disabled on release builds.
