### ISSUE TITLE
Cannot complile - missing js-utils

### ISSUE THREAD

**Issue by ealbers** [jitsi/jitsi-meet#4046]
## Description
Brand new clone, when I issue the make command I get the following:
Module not found: Error: Can't resolve 'js-utils/random' in '/home/sysadmin/jitsi-meet/react/features/app'

I downloaded the js-utils from github, just not sure where they are supposed to reside.

Thanks

**Comment by damencho** [comment]
Please, when you have questions and problems use the community forum before opening new issues.

Have you executed `npm install` prior doing `make`, as described in the README?
