### ISSUE TITLE
Dominant speaker recognition in API

### ISSUE THREAD

**Issue by haiowin** [jitsi/jitsi-meet#4049]
I am trying to print to screen the dominant speaker whenever it changes to improve accesibility for disabled people.

It would be very interesting to have an event like DOMINANT_SPEAKER_CHANGED in the lib, but for the jitsi-meet API.

I tried to get it working with the lib but when I implement the lib it's broken.

Thank you all for your work.

**Comment by saghul** [comment]
Where are you trying to do this? At the lib-jitsi-meet level? The iframe API? The native SDK? We do have an event for the dominant speaker change event at the lib-jitsi-meet level, there are different things that need to be don in order to tap into it depending on how you want to use it.

**Comment by haiowin** [comment]
I tried to do it in the lib-jitsi-meet level. 

However, using that level is overkill for my case, because I need to redo all the UI for just one feature.

That's why I was suggesting if it was possible to implement a similar event at the iframe API (https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md), something like a dominantSpeakerChanged event.

**Comment by saghul** [comment]
Makes sense. @hristoterezov is the expert in that area, maybe he can guide you. What have you tried so far?

**Comment by haiowin** [comment]
First, as I said before, I tried to use the lib-jitsi-meet level, but I can't get it to work well enough (I'm kind of new to conference software), plus I had to design all the UI from scratch.

I also tried downloading the API file (ttps://meet.jit.si/external_api.js) and see if I could modify something there to accomplish what I wanted (an event for dominant speaker changes). I saw the logs in the browser, and it definitely fires an event, in some module I cannot access. However I had no success.

**Comment by saghul** [comment]
The external API sorce is built from https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js

Now, we'd need to feed it docminant speaker events when they occurr. You can try to find your way around by following other events, hopefully @hristoterezov can guide you a bit there.

**Comment by haiowin** [comment]
Can the API on the link you posted be modified to accomplish this? That'd be awesome!

**Comment by saghul** [comment]
Yes, it can.

**Comment by virtuacoplenny** [comment]
Here is a sample commit for adding an event: https://github.com/jitsi/jitsi-meet/pull/2434.
Here is one place where you could modify to emit the event: https://github.com/jitsi/jitsi-meet/blob/b791fc32fd72aae53cdc1551902421b9abf5cb5e/react/features/base/participants/middleware.js#L73. Search for DOMINANT_SPEAKER_CHANGED to get the event of the dominant speaker changing.

**Comment by haiowin** [comment]
@saghul @virtuacoplenny 
Does this mean that I have to run it on local Debian server?

**Comment by saghul** [comment]
If you make the change yourself, yes. If you make it, submit a PR, it gets acepted (I don't see why it wouldn't) then you would be able to use meet.jit.si, once that change makes it into a release. We release quite often.

**Comment by karthikmuralidharan** [comment]
@saghul I can take a crack at this. Would you still be open to accepting the PR ?

**Comment by saghul** [comment]
Sure thing!
