### ISSUE TITLE
Prepare for unprefixed APIs for firefox

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#405]
The moz-prefixed APIs (e.g. mozRTCPeerConnection) [will eventually be removed from firefox](https://wiki.mozilla.org/Media/WebRTC/ReleaseNotes/44).

**Comment by gpolitis** [comment]
Mildly related, we should think about using adapter.js https://github.com/webrtc/adapter that presumably will handle this and other cross platform incompatibilities.
