### ISSUE TITLE
[Android] JitsiMeetView displays a weird title

### ISSUE THREAD

**Issue by bmarty** [jitsi/jitsi-meet#4050]
Hi, I'm upgrading the Jitsi library of the project Riot (https://github.com/vector-im/riot-android), and I'm using a JitsiMeetView.

Is there a way to configure the title displayed by the JitsiMeetView?

Currently it's not relevant ("X Nch..."):

![JitsiTitle](https://user-images.githubusercontent.com/3940906/55342073-3875e480-54a8-11e9-92df-027e0551a27a.png)

**Comment by saghul** [comment]
That's the meeting ID. Currently it's set from a number of sources:;

- the room name, beautified
- the config.callDisplayName URL parameter
- the callee name, if specified in the JWT token

For Riot, I'd say the best option is to use the URL parameter. If you want to disabkle it you can set it to the empty string.

We are going to add another source for that title: the meeting subject, but that work hasn't been completed yet.

**Comment by bmarty** [comment]
Ok thanks for your answer.
Is there a resource where i can find all the possible options for the bundle parameter of method loadUrl?

Also the arrow on the left of the title has no effect, is it supposed to do something when i click on it?

**Comment by saghul** [comment]
> Is there a resource where i can find all the possible options for the bundle parameter of method loadUrl?

I suggest you wait for version 2.0.0 to land, which should happen this week or the next. The API was refactored and there is no longer a loadURL which has a better interface. You can already test this by building the SDK yourself off master.

> Also the arrow on the left of the title has no effect, is it supposed to do something when i click on it?

That's the picture in picture indicator. A property needs to be set in the Activity enclosing the view in order for it to work. This is no longer needed if you use the 2.0.0 API.

**Comment by bmarty** [comment]
Ok, I can set the title with property "callDisplayName" (see https://github.com/vector-im/riot-android/pull/3091/commits/4674640f68ed52b75e39e1ffeb58bd3950768509).

Also is there a way to configure user name, to avoid the popup to enter it when user wants to start chat?

It will be nice to have. Again if you can lead me to the list of available bundle parameter, we could improve the user experience at its maximum level :-).

I do not want to wait for 2.0.0 because we have crash on the current version. It's not new, but I want to fix it quickly (https://github.com/vector-im/riot-android/issues/2412)

Thanks!

**Comment by saghul** [comment]
> Ok, I can set the title with property "callDisplayName" (see [vector-im/riot-android@4674640](https://github.com/vector-im/riot-android/commit/4674640f68ed52b75e39e1ffeb58bd3950768509)).

👍 

> Also is there a way to configure user name, to avoid the popup to enter it when user wants to start chat? Also RiotWeb provide the user avatar.

Using JWT tokens.

> It will be nice to have. Again if you can lead me to the list of available bundle parameter, we could improve the user experience at its maximum level :-).

The bundle parameters are basically any config.js parameter: https://github.com/jitsi/jitsi-meet/blob/master/config.js or interface_config.js parameter: https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js under the "config" and "interfaceConfig" bundles, respectively.

The 2.0 SDK uses this: https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java

> I do not want to wait for 2.0.0 because we have crash on the current version. It's not new, but I want to fix it quickly ([vector-im/riot-android#2412](https://github.com/vector-im/riot-android/issues/2412))

I urge you to reconsider. Riot is currently running a really old version (based on the UI, we changed it over a year ago). We learned quite a bit in the process and applied all that in SDK 2.0. This doesn't mean it will be perfect from the get go, but it should make your life much easier and allow for more flexibility. Your call.

**Comment by bmarty** [comment]
Ok, thank you.
I will update to 2.0.0 when it will be available!

One last question, required min API level by the library is 21, and min API level of Riot is 16 (I know its old, but users still have such old devices and for developers it's sometime a pain). So I have disable access to Jitsi conf to device under 21. Is it the same in version 2.0.0?

**Comment by saghul** [comment]
Yes, that hasn't changed, the min API level; is still 21.

**Comment by Bubu** [comment]
For publishing riot-android in F-Droid we can't use the prebuilt binaries from https://github.com/jitsi/jitsi-maven-repository so we'll have to rebuild the same sdk-release that's then used (1.21.0).

As we have been building the sdk as part of the riot-android build before that should be relatively straight-forward, but I really can't figure out to what commit in this repo version`1.21.0` maps.

@saghul Could you give me a pointer here?

**Comment by saghul** [comment]
@Bubu as I told @bmarty , I urge you to wait for 2.0, which we'll be releasing in the next days. It will be tagged and we will follow semver from 2.0 on. 1.21 was a messy one, apologies for that.

**Comment by saghul** [comment]
The new SDK is now releaaed: https://community.jitsi.org/t/jitsi-meet-sdk-2-0-0-for-android-and-ios-released/17485

I'm closing this now, feel free to open new issues if you run into problems when integrating it. All feedback is welcome!

**Comment by bmarty** [comment]
@saghul I've opened #4068 :)
