### ISSUE TITLE
Latest SDK 1.22 for JitsiMeetView is not synced.

### ISSUE THREAD

**Issue by naveensaini4u** [jitsi/jitsi-meet#4052]
Hello,
I am developing a Native android application Using jitsiMeetSdk but _i am facing some audio or microphones related issues in samsung devices._ JitsiMeet Community has recently updated their **SDK 1.21.0 to 1.22** but when i am trying to sync it in my project is always **sync 1.21.**
Can you please help me to resolve this error.

Thanks
Naveen Saini

**Comment by saghul** [comment]
There is no 1.22 release. We are about to release 2.0 this week, stay tuned!

**Comment by naveensaini4u** [comment]
Thanks, Saghul for your quick response.
I'm waiting for it.

**Comment by saghul** [comment]
It's out now: https://community.jitsi.org/t/jitsi-meet-sdk-2-0-0-for-android-and-ios-released/17485
