### ISSUE TITLE
How to Integrate jitsi-meet in new react-app(Web) how can i use its component

### ISSUE THREAD

**Issue by manojPebibits** [jitsi/jitsi-meet#4053]
I'm creating a new React-app and want to use jitsi-meet but there is no component, any doc I found to integerate JITSI-MEET in my React Application there is only simple js stuff they have provided i.e. 

```
var domain = "meet.jit.si";
    var options = {
        roomName: "JitsiMeetAPIExample",
        width: 700,
        height: 180,
        parentNode: undefined,
        configOverwrite: {},
        interfaceConfigOverwrite: {
            filmStripOnly: true
        }
    }
    var api = new JitsiMeetExternalAPI(domain, options);
  }
```

but I need to know what are the industry standards to create a react-app(Web) with Jitsi-meet and what are the components I need to use and how can I integrate

I want to stream a single video in a div and customize it according to my own UI design

**Comment by dmigo** [comment]
@manojPebibits have you found a solution?

**Comment by tfaieta** [comment]
I've been trying to hack this together for a couple of days, the root is here: 
https://github.com/jitsi/jitsi-meet/blob/master/react/index.web.js#L24

It loads in `<App/>`, but it's very specific to Jitsi-Meet in the way it loads up so much. I think it would be great to have a "Guide to creating your own Jitsi Meet with custom react UI", but I'm sure the contributors have put thought into something like this already. 

Also if this helps give some direction with the structure. 

``` 
|-- /react
	|-- /features
	        |-- /app                  # defines window.APP
        	|-- /base                 # core functionality & business logic
            		|-- /media            # audio & video mounting
            		|-- /connection       # connnection functionality
            		|-- /conference       # conference functionality
        	|-- /**                   # other features
|-- /modules
    |-- /UI                       # Non React UI functionality
```

**Comment by mayur-bhandari** [comment]
@manojPebibits : You can use lib-jitsi-meet to do it. I have been able to do so using lib-jitsi-meet.js in ReactJS.

**Comment by saghul** [comment]
@manojPebibits You can wrap the iframe API in a component. Here is how we did it for the Electron app: https://github.com/jitsi/jitsi-meet-electron/blob/master/app/features/conference/components/Conference.js

@mayur-bhandari Using lib-jitsi-meet means redoing the entire UI, that is a very wise advice here.

**Comment by shamoons** [comment]
Can you create a custom UI with `lib-jitsi-meet`?
