### ISSUE TITLE
show every Participant Video Stream in a new div

### ISSUE THREAD

**Issue by manojPebibits** [jitsi/jitsi-meet#4056]
Hello All,
I am not good with Jitsi, but I want to show every Participant Video Stream in a new div Element(HtmlDivElement), also with its seprate Controllers to access

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues.

The only option to achieve that at the moment is directly to use lib-jitsi-meet, but you will need to implement a lot of UI logic yourself, logic that is already implemented in jitsi-meet.
https://github.com/jitsi/lib-jitsi-meet
There is a great example of using that library and this is: https://github.com/jitsi/jitsi-meet, and a simple one: https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example
