### ISSUE TITLE
Meeting Join Fails on Ubuntu 18.10

### ISSUE THREAD

**Issue by ahmedsaifreza** [jitsi/jitsi-meet#4058]
I have just installed jitsi meet on a new ubuntu box. Installation was success without any warning or error. When I go to the url and type a meeting to join, camera permission pops up and after I accept, I can see the camera for a split sec and then gives "Unfortunately something went wrong. We are trying to fix this"

I am running on a linode with 4GB RAM and 2 CPU

**Comment by saghul** [comment]
Where did you install it from?

**Comment by ahmedsaifreza** [comment]
I added this repo as per quick install guide: echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list

**Comment by saghul** [comment]
I see. What logs do you see in the javaScript console?

**Comment by ahmedsaifreza** [comment]
`[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: "Strophe: request id 19.1 error 0 happened"
    log strophe.util.js:89
    error strophe.js:2083
    _onRequestStateChange strophe.js:5565
Logger.js:124:12`

**Comment by saghul** [comment]
Please paste the full log in a Gist.
