### ISSUE TITLE
Missing changelog 

### ISSUE THREAD

**Issue by filipedelimabrito** [jitsi/jitsi-meet#4062]
After the last released here (2.0.0) the `onConferenceWillLeave(...)`, `onConferenceLeft(...)`, `onLoadConfigError(...)` and  `onConferenceFailed(...)` methods from the `JitsiMeetViewListener ` don't exist anymore. Also, the `loadURLObject(...)` from `JitsiMeetView` doesn't work anymore. Is there a way to include a changelog on this repository to let us know about all the changes after from a release here? 

Thank you.

**Comment by saghul** [comment]
First and foremost, apologies, I know exactly what you are going to go through now, but there was simply no other way.

As I mentioned in the announcement: https://community.jitsi.org/t/jitsi-meet-sdk-2-0-0-for-android-and-ios-released/17485 we are going to adhere to semantic versioning from now on.

Unfortunatelky, we didn't keep good track of the changes throughout the 1.X series, and even if we did, you can consider 2.0.0 as a full-rewrite of the native facing API.

We did this so we now have a good foundation on top of which we can build a better experience for developers such as yourself. You shouldn't go through a breakage of this magnitude ever again, not at least without a detailed plan.

Again, sorry. Thanks for understanding.

**Comment by filipedelimabrito** [comment]
Thanks for the explanation @saghul but I couldn't see no changelog link from your post.

> We are also correcting that: starting with 2.0.0 we are adhering to semantic versioning, each release will also come with a comprehensive changelog so SDK consumers can use the new features easily and adapt to changes.

So, starting from 2.0.0, where I can find that?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/releases/tag/android-sdk-2.0.0

As I said, there is no actual changelog other than "it's new!". Future releases will have the changelog as part of the tag message.

**Comment by filipedelimabrito** [comment]
Better to remove the "`[...] each release will also come with a comprehensive changelog so SDK consumers can use the new features easily and adapt to changes.`" from the post then - since there is no actual changelog (from your words) - which makes the issue status to be open and not closed here.

Thanks for the great work btw.

**Comment by saghul** [comment]
Note the future tense "will come", we don't have a _real_ changelog for 2.0 because it's impossible to write one.

**Comment by filipedelimabrito** [comment]
I don't want to discuss with you about grammatical questions here but since you started your sentence with `[...]starting with 2.0.0 [...]` anyone who have read it will think on that way.

Putting a dot here instead of adding a comma like would be better: `[...] starting with 2.0.0 we are adhering to semantic versioning. After this release each new release will come...`

If you think that there is no reason to include a changelog after deploying a 2.0.0 version while most of your users is on 1.something version with probably lot's of breaks, that's bad! Unless you think no one is using the older version and will start using the newer one.

**Comment by saghul** [comment]
I updated the text a bit.

**Comment by filipedelimabrito** [comment]
I could see there. It is more clear now. Thank you for improving that!

**Comment by olcayertas** [comment]
@saghul I was also looking for `loadURLObject` method. What should I use in new Version?

**Comment by saghul** [comment]
The API is documented here: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md

You can see a sample project here: https://github.com/jitsi/jitsi-meet-sdk-samples

The direct translation is to use join(...), but using JitsiMeetActivity is much simpler.
