### ISSUE TITLE
Jitsi Meet rejects user agent string of recent version of Firefox derivative.

### ISSUE THREAD

**Issue by sudoman** [jitsi/jitsi-meet#4063]
## Description

Visiting meet.jit.si with Abrowser (rebranded Firefox) version 66 leads to a browser unsupported message. A co-worker tested with an older version of Abrowser, and only had the issue on the newest version.

## Current behavior

""it looks like you're using a browser we don't support. please try again with the latest version of firefox, chrome or"

## Expected Behavior

The page should load for Abrowser 66.

## Possible Solution
---

## Workaround

Use a user agent switcher and select "Firefox".

## Steps to reproduce

Install Abrowser in Trisquel 8. Visit meet.jit.si

# Environment details

Trisquel 8, 64 bit

**Comment by saghul** [comment]
Can you please past the full UA string that browser uses? We use the `bowser` library to detect the bworser, plus some extra checks, we might need to add some more.

**Comment by sudoman** [comment]
According to Apache logs, this is the browser string when I visit one of our sites:

````
"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
````

The user agent switcher creates this UA that is accepted by Jitsi Meet:

````
"Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0"
````

Thanks! : )

**Comment by saghul** [comment]
Is that what "Abrowser" sets? Hum... it should definitely be interpreted as Firefox, unless bowser is broken.

**Comment by sudoman** [comment]
Yeah, that's what it sets. It seems rather strange.

I think that 66 isn't an ESR release either, so that's probably not the issue.

**Comment by saghul** [comment]
FTR this is my UA (FF beta on macOS): `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0"`

**Comment by damencho** [comment]
We support Firefox 52.4+. So Firefox 31 will not work and the page we show is correct.

**Comment by sudoman** [comment]
@damencho It's the other way around the "66" UA doesn't work, but the "31" one did.

**Comment by sudoman** [comment]
What if this has to do with the JavaScript API? That doesn't exactly explain why changing the UA would cause the page to load, unless less tests are performed when there is an older UA.

**Comment by damencho** [comment]
> @damencho It's the other way around the "66" UA doesn't work, but the "31" one did.

So maybe there is a bug in user-agent parsing.

**Comment by damencho** [comment]
Hum, there ,must be something else a quick test I did works with that user-agent string:
```
navigator.userAgent
"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"

[modules/browser/BrowserCapabilities.js] <t>:  This appears to be firefox, ver: 66.0
```
And by the way the other one also works:
```
modules/browser/BrowserCapabilities.js] <t>:  This appears to be firefox, ver: 31.0
```
Which makes my statement above invalid.
