### ISSUE TITLE
iPhone Xr's screen aspect ratio distortion bug

### ISSUE THREAD

**Issue by patkhai** [jitsi/jitsi-meet#4065]
iPhone Xr's screen aspect ratio distortion problem
Version 1.21.1 JitsiMeet SDK for iOS
iOS version: 12.1.4
## Description
iOS: Whenever you switch from portrait mode to a landscape mode on the video call, the camera display became stretched out. This is only happening on the iPhone XR but not on iPhone 7/8. 

Note: However, if you take a screen shot while in a landscape mode, the result of the screen shot doesn't seem to be stretched or distorted. 

## Steps to reproduce
If you have iPhone XR, try video calling and using a landscape mode to see the stretch image

**Comment by saghul** [comment]
Since you are using the SDK, I assume you are building an app yourself. Does this also happen with the Jitsi Meet app? Can you reproduce it on the simulator?

**Comment by patkhai** [comment]
Yeah it does happen with the Jitsi Meet app it self too. 
Note: This only happens on the iPhone XR camera when in landscape mode.

**Comment by saghul** [comment]
That's unfortunate. I don't have access to such device (and I don't think anyone on the team has either) so I'm not sure how to reproduce this. I'll ping this issue when we update WebRTC, that may have an effect. No ETA for when that may happen though.

**Comment by nukeador** [comment]
I can confirm this bug on an iPad 5, iOS 12.3.1

Is there a way we can debug something for you on the device?

Cheers.

**Comment by nukeador** [comment]
Btw, back camera is not experiencing this issue, just the front one.

When you change from one to the other, there is a couple of frames where you see the front one image with the right orientation.

**Comment by saghul** [comment]
Are you seeing the stretch too? Can you take a screenshot? If the screenshot shows correctly, can you take a photo with another device?

**Comment by patkhai** [comment]
I don't know about the iPad bug but what I did found out is that if I screenshot it, the video image comes out fine with no stretch. User only sees it while chatting live.

This is still with iPhone XR, IOS 12.3.1
