### ISSUE TITLE
Android Jitsi-meet sdk stops working suddenly , showing 'dialogCornerRadius not found.' and 'failed linking references.'

### ISSUE THREAD

**Issue by FaizalMalik** [jitsi/jitsi-meet#4067]
## Description

One. of my project is using andorid prebuild sdk, all of a sudden its stops working , Project showing errors like 'dialogCornerRadius not found.' and 'failed linking references.' 

I was using 

implementation('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true } in build.gradle

I have changed it to 

implementation('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true } 

But the error remains same....!! When we comment the Jitsi Implementations, App building successfully...
---

## Error Log

Android resource linking failed

Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.

Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.

Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1555: error: resource android:attr/fontVariationSettings not found.

Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1556: error: resource android:attr/ttcIndex not found.
error: failed linking references.

**Comment by FaizalMalik** [comment]
@saghul  Could you please help me ?

**Comment by saghul** [comment]
Run `./gradlew clean --refresh-dependencies` You may need to update your code since there have been API changes.
