### ISSUE TITLE
Does not work in Edge

### ISSUE THREAD

**Issue by Vitoza** [jitsi/jitsi-meet#4074]
Meet.jit.si opens meeting in MS Edge, ask permissions for using my mic and camera, then successfully shows a video from my camera with myself. It seems all works good - camera's and mic's icons in meetjitsi's web app are switched on. The only issue that I am geting a yellow "Browser warning" notification ("Eer...we are afraid..." etc). But when I join to this  meeting from iphone - I see on iphone that Edge's user has disabled camera and microphone. And respectively no any video and audio comes from edge client to iphone's one.
In Edge meetjitsi client I set all devices settings (in a Settings menu/Devices tab) - video preview in Settings dialog shows video from my camera good, microphone's indicator under it also works fine. 
Also I have tested meetjitsi client on this PC from Chrome browser - all works fine, such a problem does not reproduce on this PC from Chrome.

So why Edge client (Windows 10 + Microsoft Edge 42.17134.1.0) does not transmitt video and audio to other meetjitsi clients (for instance Chrome+IOS, Ubuntu + FireFox)? Working with meet.jit.si server. Please help.

**Comment by saghul** [comment]
Our current Edge support is not great. With Edge transitioning to being based on the Chromium engine it's not very practical for us to spend time fixing issues on a browser which is being phased out. I suggest you switch to a different browser for the time being.

Sorry for the trouble.

**Comment by Vitoza** [comment]
Thank you

**Comment by dermeister0** [comment]
It stopped working on Chromium-based Edge.

Edge Version 81.0.381.0 (Official build) dev (64-bit)

**Comment by saghul** [comment]
We have fixed that earlier this week. This should be available soon on meet.jit.si. Sorry for the trouble.

**Comment by damencho** [comment]
The fix is available now on meet.jit.si.

**Comment by Vitoza** [comment]
Good, thanks
