### ISSUE TITLE
Is Lower Third possible to be supported?

### ISSUE THREAD

**Issue by MRYingLEE** [jitsi/jitsi-meet#408]
The Lower Third in Google Hangouts is as that in the image:

![image](https://cloud.githubusercontent.com/assets/11193534/11168997/e310b0c0-8be1-11e5-8030-d8129db93e3e.png)

I noticed the project of Jipopro (https://github.com/jitsi/jipopro/blob/master/src/org/jitsi/recording/postprocessing/overlay/manager/LowerThirdOverlaysManager.java)  contains lower third support for post processing.

Just wonder whether it is possible to do it in Jitsi Meet on LIVE video stream.

Thank you in advance,

YIng

**Comment by Bugsbane** [comment]
I'm sure (being the technical novice I am, heh) that it's likely doable. I'd even appreciate having this available if it didn't divert resources. Personally though, given the choice between dev's spending time on getting the connections more reliable and lower thirds, I know I'd choose the former. It's a nice idea though, especially if the lower thirds were somewhat customizable (ie font, colors etc).

**Comment by emcho** [comment]
Getting a patch for something like this would be most welcome!

**Comment by danionescu2007** [comment]
+1 for the lower thirds
