### ISSUE TITLE
[Android SDK][2.0.0] Tracker Amplitude in Jitsi SDK

### ISSUE THREAD

**Issue by bmarty** [jitsi/jitsi-meet#4080]
The report https://reports.exodus-privacy.eu.org/en/reports/69374/ reveals that tracker Amplitude is added in the Jitsi SDK.

Grade dependencies tree:
```
+--- org.jitsi.react:jitsi-meet-sdk:2.0.0
|    +--- com.facebook.react:react-native:0.59.2 (*)
|    +--- com.android.support:support-v4:28.0.0 (*)
|    +--- com.android.support:appcompat-v7:28.0.0 (*)
|    +--- com.amplitude:android-sdk:2.14.1                         <-- HERE
|    |    \--- com.squareup.okhttp3:okhttp:3.0.1 -> 3.12.1 (*)
|    +--- com.dropbox.core:dropbox-core-sdk:3.0.8
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    +--- com.facebook.react:react-native-background-timer:2.1.1-jitsi-799011
|    |    \--- com.facebook.react:react-native:0.59 -> 0.59.2 (*)
|    +--- com.facebook.react:react-native-calendar-events:1.6.4-jitsi-799011
|    |    \--- com.facebook.react:react-native:0.59 -> 0.59.2 (*)
|    +--- com.facebook.react:react-native-fast-image:5.1.1-jitsi-799011
|    |    +--- com.facebook.react:react-native:0.59 -> 0.59.2 (*)
|    |    +--- com.android.support:support-v4:28.0.0 (*)
|    |    +--- com.github.bumptech.glide:glide:4.7.1 -> 4.8.0 (*)
|    |    +--- com.github.bumptech.glide:annotations:4.7.1 -> 4.8.0
```

What are you tracking with this tracker?
Is it possible to have a library without embedded tracker?

Also is it possible to disable any tracking in the current SDK?

Thanks!

**Comment by saghul** [comment]
@bmarty We are currently experimenting with amplitude for event tracking, in a similar way to Google Analytics: we track events such as button presses which help us know if certain features are used or not.

This library is only enabled if an API key is configured in the Jitsi Meet depoloyment's config.js file. You can see an example here: https://beta.meet.jit.si/config.js

If you want to completely rip it out of the build, that should be possible to do with minor changes. I don't think I have the time available right now, but here is an outline in case you want to send a PR:

- read an env variable at build time `DISABLE_ANALYTICS`
- don't include the SDK in that case
- modify the Amplitude - React Native java glue we have to not be enabled in that case
- profit!

**Comment by bmarty** [comment]
Ok, thanks.

It looks like removing the dependencies this way:

```
    implementation('org.jitsi.react:jitsi-meet-sdk:2.0.0') {
        transitive = true
        exclude group: 'com.amplitude', module: 'android-sdk'
    }
```

does not lead to any issue.

**Comment by saghul** [comment]
@bmarty Please take a look at https://github.com/jitsi/jitsi-meet/pull/4155

**Comment by saghul** [comment]
Oops, forgot to close this one. All the bits required to make a "libre build" are now in and are documented in the README. Closing!
