### ISSUE TITLE
Error running App en Android Studio - CreateProcess error = 193,% 1 is not a valid Win32 application

### ISSUE THREAD

**Issue by djlolito** [jitsi/jitsi-meet#4085]
## Description

Good morning, I am trying to run the app, but I get the following error:
CreateProcess error = 193,% 1 is not a valid Win32 application

I have tried even with the JDK outside the Studio but it gives the same error.

**Comment by pengbs** [comment]
same issue

**Comment by saghul** [comment]
Building on Windows is not currently supported.

**Comment by e4basil** [comment]
Is there any update?

**Comment by luixxiul** [comment]
See https://github.com/jitsi/jitsi-meet/issues/6290#issuecomment-617609483
