### ISSUE TITLE
[Android] Samsung device: JitsiConference.leave() rejected with...

### ISSUE THREAD

**Issue by ngoctan95** [jitsi/jitsi-meet#4086]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- It is only occurs in Samsung devices. 

## Current behavior
---While I joining into the room for video calling, it kick me out and got nothing after that

## Expected Behavior
---Still join into room

## Possible Solution
---

## Steps to reproduce
---

# Environment details
--- Here I got some logs: 
1. E/JitsiConnectionService: onCreateOutgoingConnectionFailed 2597E231-521A-4CEE-BC07-E00DECB7B855
2. W/ReactNativeJS: '[__filename]', '<l>: ', 'Failed to initialize Amplitude handler, no APP key'
3. W/ReactNativeJS: Tried to show an alert while not attached to an Activity
4. W/ReactNativeJS: '[__filename]', '<l>: ', 'Calendar access not granted.'
    E/JitsiConnectionService: onCreateOutgoingConnectionFailed 4576CD36-E8BE-4C0A-878D-ABB50E5377E8
5. After some kinds of log above appeared, terminated video call and I got: 
W/ReactNativeJS: '[__filename]', '<l>: ', 'JitsiConference.leave() rejected with:', { [Error: The timeout for the confirmation about leaving the room expired.] line: 910, column: 428252, sourceURL: 'index.android.bundle' }

**Comment by ngoctan95** [comment]
@saghul , @anyone_else, 
I have granted camera, audio_record and read_calendar too. But only one thing I got only without success. 
Im very appreciated if any solution for this issue.

**Comment by saghul** [comment]
Are you using the app or the SDK?

**Comment by ngoctan95** [comment]
@saghul , Just SDK. But anw, after update system, the app work perfectly in Samsung. 
Thanks for the lib. I gonna close this issue. 👍
