### ISSUE TITLE
[Lastest SDK] interface for listenning change of joining, leaving,...

### ISSUE THREAD

**Issue by ngoctan95** [jitsi/jitsi-meet#4088]
@saghul  Thank you and your team for building this incredible lib. 
After migrate successfully this lib into my project, I think it should get better if more interface to tracking the change of actions, such as the recipient out the room, joined the room or terminated the room,. ... 
Currently only 3 events like this: 
```
public interface JitsiMeetViewListener {
    void onConferenceJoined(Map<String, Object> var1);

    void onConferenceTerminated(Map<String, Object> var1);

    void onConferenceWillJoin(Map<String, Object> var1);
}

```
I logged that and see in JitsiConference.js but could you consider add more that events? 
Thanks

**Comment by saghul** [comment]
Thanks for the kind words!

We plan on adding more events at some point, yes. What specific events would you be interested in and what use would you give them?
