### ISSUE TITLE
Procedure for Installing Jitsi-meet in PHP laravel project ?

### ISSUE THREAD

**Issue by syedMSohaib** [jitsi/jitsi-meet#4092]
Hey Guys,  I have a website with whole backend built on top of laravel PHP, i need to integrate video conferencing feature of jitsi meet in my existing project but can't find a way to do it.  PS. Is there any repo or tutorial to integrate jitsi-meet in non-reactjs project

**Comment by damencho** [comment]
Please for questions and problems use the community forum at https://community.jitsi.org before opening new issues.

You can use the iframeAPI https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md
