### ISSUE TITLE
Slack support ?

### ISSUE THREAD

**Issue by adriens** [jitsi/jitsi-meet#410]
Hi guys,

i use your software everyday... and i wonder if you intend to support SLACK ?... (without passing by xmpp)
Thank you in advance for your answer.

**Comment by romaintb** [comment]
+1

**Comment by warden** [comment]
+1

**Comment by emcho** [comment]
jitsi-meet is standalone and in that sense has no "support" for any external systems, so I am really not sure what this request is about, and even less about the "without passing by xmpp" part

**Comment by rasos** [comment]
Rocket.Chat is an open source variant of Slack and got Jiitsi meet integrated in today's release [0.34](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.34.0/).

**Comment by brianmcbride** [comment]
+1

**Comment by seccubus** [comment]
It would be great if, like /HangOut you could open a jitsi chat with /jitsi

**Comment by saghul** [comment]
I guess we can close this now :-) https://jitsi.org/Main/Slack

**Comment by jbbr** [comment]
@saghul the link is dead
> The page “Main/Slack” doesn’t exist.

Are there any news regarding some sort of "integration" or webhook support to allow quick start of a jitsi chat from slack?

**Comment by seccubus** [comment]
Please reopen this ticket.

**Comment by wiggitamoo** [comment]
I agree this would be a valuable addition to our team too.

**Comment by jmacelroy** [comment]
There is now a slack integration available, https://jitsi.org/slack/.
