### ISSUE TITLE
Possibility to mute/unmute audio without reconnection to the conference?

### ISSUE THREAD

**Issue by dlernatovich** [jitsi/jitsi-meet#4101]
It is possible to mute/unmute audio from the iOS SDK through the code without using the standard (react native) mute/unmute button UI?

**Comment by saghul** [comment]
Not currently.

**Comment by phngoctam** [comment]
I’m facing two issues that are both on CallKit system UI.
Issue 1 : I want to mute/unmute voice when user tapped “mute” button in CallKit system UI
Issue 2 : I want to switch video/audio mode when user tapped “video” button in CallKit system UI
@saghul please help me handle it by native code (swift).
Many thanks!

**Comment by phngoctam** [comment]
@saghul  Can you give me a workaround or any solution to fix it , please?

**Comment by saghul** [comment]
> Issue 1 : I want to mute/unmute voice when user tapped “mute” button in CallKit system UI

This is already the default behavior, are you seeing any probleems with it?



> Issue 2 : I want to switch video/audio mode when user tapped “video” button in CallKit system UI

This is not possible, CallKit triggeers a new call, alas.

**Comment by phngoctam** [comment]
Thanks for your response @saghul ,
“This is already the default behavior, are you seeing any probleems with it?”
My problem is every time user click on “mute” button in CallKit SystemUI => it’s does not work
when user click "mute" button => Callkit System UI display correctly but another peer still hear the voice from this device that is muted.
Method “provider(_ provider: CXProvider, perform action: CXSetMutedCallAction)“in CXProviderDelegate delegate that is invoked for each click “mute” button in CallKit System UI.
I need it every time the user clicks on mute it is muted, every time user unmute it  is unmuted, that’s all!

**Comment by asim1mehta** [comment]
Hi @phngoctam
I am facing the same problem, Did you find any solution to this?

**Comment by bariseray030** [comment]
any solution?
