### ISSUE TITLE
xcode 10.2 and swift 5

### ISSUE THREAD

**Issue by MansoorB** [jitsi/jitsi-meet#4128]
Hi,

I tried follow the guides that is provided. The issue I am facing is "JitsiMeetView has no member load", in other words function load doesnt exist for the JitsiMeetView.

I built the framework through terminal and xcode. Both are success, but terminal framework gives me architecture problem and xcode one is the first paragraph.

How do resolve this?

**Comment by saghul** [comment]
See the API here: https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md#api there is no longer a `load` method.

Also, FYI, you don't need to build the SDK yourself, we publish it on CocoaPods. All details are on the README.
