### ISSUE TITLE
offer audio-only option

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#413]
to save bandwidth, offer a way not only to turn off one's own outgoing feed but also turn off video from everyone else so that a particular user can choose to have only audio streams for all directions.

**Comment by pastk** [comment]
I second that; a nice feature to make jitsi more usable for data-capped mobile plans

**Comment by saghul** [comment]
This is planned, though we have no actual ETA yet. Stay tuned! :-)

**Comment by bgrozev** [comment]
Audio-only is now in :)
