### ISSUE TITLE
Mac store app version with own server setup, blocks some connection.

### ISSUE THREAD

**Issue by AleshaOleg** [jitsi/jitsi-meet#4132]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Jitsi inside our electron-based app from [app store](https://itunes.apple.com/at/app/grape-business-kommunikation/id971791845) doesn't work, but working fine with [releases outside](https://github.com/ubergrape/grape-electron/releases) of mac store. Basically, I need an answer if somebody stuck with that before and a possible way to resolve this. From what I googled I didn't find any related issues.

From what I found, that problem related to different network usage. For example, I found if I'll use my phone (we also have an app for iOS/Android) connected to LTE and will try to contact the user who uses this app on the desktop, the connection will be broken. But, if I'll join the same network from mobile (Wi-Fi) as the desktop user, everything will work fine!

## Current behavior
---
Seems like the problem is mac store version blocking some connection, and it causes connection issues with Jitsi. I tried to check network status with Wireshark but didn't find any UDP packages where traffic should go. Basically, when somebody joining with mac store app, other users see a message "_username_ is having connection problems"

What's working:
1) I can see users who joined/left the call;

What's not working:
1) Audio/video;
2) User connection status. N/A or 0 for most of the values;
3) Window with conversation time in seconds. It always shows 0 for everybody;

## Expected Behavior
---
Connection working fine.

## Possible Solution
---
Don't have any idea, what's a possible solution. I googled around and didn't find any information according to if mac store apps blocking some ports for example.

## Steps to reproduce
---
I think I can invite somebody to our product, to test with me in our environment if you're interested.

# Environment details
---
We're using our own server for Jitsi, and sorry I'm front-end developer and can't say any real details. But if you would need some details, just ask me I'll ask our system engineers about details.

Thanks!

**Comment by saghul** [comment]
What deployment are you using, meet.jit.si or your own?

**Comment by AleshaOleg** [comment]
@saghul we're using our own.

**Comment by saghul** [comment]
Can you reproduce the issue when you use a desktop browser instead of the store app?

**Comment by AleshaOleg** [comment]
@saghul no, only related to store app.

**Comment by AleshaOleg** [comment]
If somebody will be stuck with the same issue you need to allow your app to use UDP connection. Here is [some](https://stackoverflow.com/questions/41396350/not-receiving-any-udp-data-on-a-socket-when-app-sandbox-is-on-in-cocoa-app) more info. For some reason, the Mac Store version blocking UPD/TCP connections. Fixed with the help of [com.apple.security.network.server](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_network_server).

Here is an example: https://github.com/ubergrape/grape-electron/commit/92d230e13bc407c6773e7cb8428575ba78c46fa5

![photo_2019-04-29_05-36-30 (1)](https://user-images.githubusercontent.com/1459899/57691599-edbdbf80-7644-11e9-8862-db4dbe4d0a7c.jpg)

**Comment by saghul** [comment]
Thanks for sharing!
