### ISSUE TITLE
Add features to enable easy troubleshooting

### ISSUE THREAD

**Issue by cannycartographer** [jitsi/jitsi-meet#414]
Hi,
I've used Jitsi Meet several times and it looks like a great application - thanks. This is just a suggestion as to how I think it could be made better and to encourage more people to use it.

A couple of times I've used it and audio and video has worked fine in both directions. However I've also used it a couple of times where the connection has not worked or audio and video have only worked in one direction - e.g. I haven't been able to see or hear the other, but they've been able to hear and see me.

When this happened it wasn't very easy to troubleshoot what was going wrong and we soon gave up, which is a shame.

I'm wondering whether it would be possible to implement something which clearly shows:
- whether your own microphone and webcam are/ aren't working (and why -e.g. if it's a permission problem)
- whether audio input, output and video connections are working - in both directions
- easy steps to take to troubleshoot and sort this out
- perhaps something similiar to the 'skype call testing service' - a remote bot that you can somehow ring or invite that will echo back your own audio and video to you to test the hardware and connections.

I don't really understand the architecture or technical side of jitsi meet that much so sorry if some of this isn't applicable or possible!
Cheers,
Nick

**Comment by Bugsbane** [comment]
I agree with the overall sentiment. Often when I've tried to bring less technical users over to Jitsi Mett we've run into problems with not getting video or sound, and it can be tricky to know why. My specific suggestions would be:

1. An echo bot - as suggested, that lets you call and have your audio (and unlike SKype, video!) echo'd back to you.

2. Something that gives you visual feedback of the volume level being captured, both by your mic, and the other parties streams. That way, if their volume meter is showing at their end, but not at yours, then you know their mic is successfully capturing sound, but that there's no successful audio sream etc. Hangouts / Skype don't quite do it this way, but both provide a screen where you can get visual feedback based on whether your microphone is receiving sound.

**Comment by jantman** [comment]
I have to strongly agree on this as well. I'm quite technical, as is everyone I work with. Perhaps it's because we're all Linux users and not used to in-browser A/V actually working right, but it seems that every time we use meet.jit.si, every call starts with everyone testing audio, and then trying to figure out if the problem is Jitsi, or other parties, or their audio setup. Both of @Bugsbane 's suggestions would help a lot.

**Comment by paweldomas** [comment]
have you seen chrome://webrtc-internals in Chrome and about://webrtc in
Firefox ? It provides lots of information and is useful for debugging such
issues, but you need to be "quite technical". It will show you for example
results of "getUserMedia" and input/output volume for audio stream etc.

**Comment by nickmdowson** [comment]
Thanks Pawel, I hadn't seen those (I just checked and it's actually about:webrtc in firefox, i.e. without the double slash).

Perhaps in the first instance jitsi meet could have a help button that points users in that direction with a brief guide to understanding it? Mind you, I just had a look at that debug log from firefox's about:webrtc and I couldn't make much sense of it, and I am probably more technically inclined than most users..

**Comment by kwill** [comment]
External solution mentioned in #1823:

> There's an external echo test hosted at https://janus.conf.meetecho.com/echotest.html

Also mentioned:

> ...we don't have plans to implement a pre-call device testing screen. While in a call though, you can open the device selection dialog and it will preview audio and video devices.
