### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by TheLastProject** [jitsi/jitsi-meet#4141]
There is some inconsistency between the documentation of the quick install and the manual install.

https://github.com/jitsi/jitsi-meet/blob/d7eea8abbcd76e956128bfa137a943031928029d/doc/quick-install.md#advanced-configuration says:
- org.ice4j.ice.harvest variable names
- ports TCP/443 or TCP/4443 and UDP 10000

While https://github.com/jitsi/jitsi-meet/blob/16f47e5e0aaa9d53fe8ec49b18fe379cc38abe60/doc/manual-install.md#running-behind-nat says:
- org.jitsi.videobridge variable names
- ports TCP/443 or TCP/4443 and UDP 10000-20000

From testing, the quick-install seems to be correct. Is this correct? Shall I submit a merge request to update the manual install there to match the quick install?

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues. 

Yes, the manual install document is outdated and has a warning saying that and is not recommended to be used. If you feel like updating it, feel free to open a PR.
