### ISSUE TITLE
Mic & video goes off on a running conference if participant count is more than 2

### ISSUE THREAD

**Issue by wahid4sap** [jitsi/jitsi-meet#4149]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

We installed Jitsi successfully using local ip e.g: 192.168.. and p2p & jingle/conference session both are working fine. 
Suddenly, our network configuration changed by system admin and later we want to use our existing established Jitsi server to communicate each other. But we failed to do P2P and conference session.
After lots of R&D we changed some config file with the new IP. Changed files are- 
- /etc/jitsi/meet/ip-config.js,
- /etc/jitsi/jicofo/config,
- /etc/jitsi/videobridge/config
- nginx
- /etc/prosody/conf.d/ip.lua

And then we can do P2P session but when another participant join to that running conference then the mic & video goes off of all the participants but 3 thumbnails available are on the screen.
Again, we did some R&D on that and seen the jicofo log and there we got xmpp host verifier() cannot match the cert with new IP.

Please do some help to relieve from the issue.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

The problems you describe can be easily avoided if you are using a DNS, the way everything is designed.
Add to jicofo configuration (/etc/jitsi/jicofo/sip-communicator.properties)
org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true 
and restart jicofo (maybe give some time for jicofo to discover the bridge).
