### ISSUE TITLE
External API - Execute Command does not work

### ISSUE THREAD

**Issue by ami2009** [jitsi/jitsi-meet#415]
I try to use the external API for Jitsi meet. But the ExecuteCommand function is not working. The reason for this is that you are concatenating this.url = "// + domain +" / and expect the domain to be a string without http or https for the JitsiMeetExternalAPI call. I changed it in my code to this.url = domain+"/" and provide a proper domain string like "https://meet.jit.si" and it works.

**Comment by bgrozev** [comment]
This has probably been fixed by now. Please re-open if needed
