### ISSUE TITLE
Jitsi-meet unable to access my camera after several attempts.

### ISSUE THREAD

**Issue by abddayan** [jitsi/jitsi-meet#4154]

**Comment by abddayan** [comment]
It reports that I check to be sure no any other app is using the camera.  After some checks and closing any other suspected app, it's still unable to access.

**Comment by damencho** [comment]
Please use the community forum for reports and questions before opening new issues.

More info is needed, like OS and version, browser and versions, camera model, is it external/internal. I would also ask you to test does it works with the same browser when you try https://appr.tc/.

**Comment by abddayan** [comment]
Thanks for your concern. The problem is the same when I tried the link you
sent: https://appr.tc/.
The following are the details you requested:
OS: Windows 8 Enterprise, 64 bit,
Browser: Google Chrome, 73.0.3683
Camera: internal.
Thank you.
<https://about.me/abddayan?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Abd Dayan
about.me/abddayan
<https://about.me/abddayan?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/05/19,
14:32:16

**Comment by damencho** [comment]
If you experience same there, this can be browser bug and you nees to report it there ...

**Comment by abddayan** [comment]
OK. Thanks.
<https://about.me/abddayan?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Abd Dayan
about.me/abddayan
<https://about.me/abddayan?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/05/19,
20:16:42
