### ISSUE TITLE
Remember audio level of participants

### ISSUE THREAD

**Issue by DiThi** [jitsi/jitsi-meet#4159]
Currently you can change the volume level of each participant in a meeting, by default it's set to maximum. If you or anyone exits and enters the meeting, it's reset to default.

I'd really like that to persist across sessions.

**Comment by damencho** [comment]
It maybe possible to be implemented only when using authentication.

**Comment by DiThi** [comment]
Wouldn't it be enough to use localStorage and the name of participants?

**Comment by saghul** [comment]
The names can change at any time. It would need to be attached to something that does not change, like the authentication account.

**Comment by DiThi** [comment]
How about this? Have a global default volume option that is assigned to other participants.

**Comment by KaKi87** [comment]
Bump
