### ISSUE TITLE
Jitsi Meet reconnecting / no other user seen

### ISSUE THREAD

**Issue by MaFreiberger** [jitsi/jitsi-meet#4164]
Hello,

like hundreds other posts, i have the "normal" problems with Jitsi Meet.
When connecting as first users to https://jitsi.mydom.de:4443 everything seems fine first.
When another user from another PC/network connects, everything seem fine first but the users don't see each other at all.
Then, after some seconds the reconnection occurs. "You have been disconnected"

If followed (4 times now) the Quick install manual, sometimes with nginx installed first, this time without (just the basic quick install)
Host OS is debian 9 running in a Proxmox VM.
Java is
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

When installing, i used the FQDN as hostname "jitsi.mydom.de"
The hostname of the OS is also jitsi.mydom.de. Those FQDN is a public accessible A-record and name resolving is working.
Those host is in a DMZ with NAT & portforwarding TCP Port 4443 (public) to local IP of Host Port  443. Same with UDP 10000-20000.
Even NAT reflection is enabled in the Firewall/Router.
On the host the firewall is default debian = Allow All from Anywhere to Anywhere

And of course, i have set the NAT settings in  sip-communicator.properties
```
root@jitsi:/home/user# cat /etc/jitsi/videobridge/sip-communicator.properties
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.jitsi.mydom.de/.*
org.jitsi.videobridge.rest.jetty.host=::
org.jitsi.videobridge.rest.jetty.port=443
org.jitsi.videobridge.rest.jetty.ProxyServlet.hostHeader=jitsi.mydom.de
org.jitsi.videobridge.rest.jetty.ProxyServlet.pathSpec=/http-bind
org.jitsi.videobridge.rest.jetty.ProxyServlet.proxyTo=http://localhost:5280/http-bind
org.jitsi.videobridge.rest.jetty.ResourceHandler.resourceBase=/usr/share/jitsi-meet
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./config.js=/etc/jitsi/meet/jitsi.iteanova.com-config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./interface_config.js=/usr/share/jitsi-meet/interface_config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./logging_config.js=/usr/share/jitsi-meet/logging_config.js
org.jitsi.videobridge.rest.jetty.RewriteHandler.regex=^/([a-zA-Z0-9]+)$
org.jitsi.videobridge.rest.jetty.RewriteHandler.replacement=/
org.jitsi.videobridge.rest.jetty.SSIResourceHandler.paths=/
org.jitsi.videobridge.rest.jetty.tls.port=443
org.jitsi.videobridge.TCP_HARVESTER_PORT=443
org.jitsi.videobridge.TCP_HARVESTER_MAPPED_PORT=4443
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=XXX.XXX.XXX.XXX
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=YYY.YYY.YYY.YYY
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePath=/etc/jitsi/videobridge/jitsi.mydom.de.jks
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePassword=changeit
```

/etc/hosts
```
oot@jitsi:/home/iteanova# cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       jitsi.mydom.de      jitsi

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
I don't know how to proceed any more. After i have lost now two days for thos problems i#m near to give up and try another solution, as long as no "jitsi" is included in it.

Could somebody pls. give me a hint where else to search for the problem?

Thank you.

**Comment by damencho** [comment]
Please use the community forum for reports and problems before opening new issues.

The first step is to check the client error, open the js console in the browser and check the error there. 
Normally the first one is about missing jicofo or jvb, and then you need to check those logs to see the error why it doesn't connect. 
If you have installed it several times I suspect jicofo is not able to connect due to cert problems.
