### ISSUE TITLE
Contact list from ldap

### ISSUE THREAD

**Issue by jamesarems** [jitsi/jitsi-meet#417]
Hi team,

First of all its an amazing webrtc platform. We are using this in our small company . 

Is there any option for integrating ldap contacts to jitsi meet contact list . ?

or 

Option for each users to create contact in there on user space? Is it possible?

we are using plain auth mechanism.

Keep going....Cheers

**Comment by nkokkos** [comment]
Hi,

If I am not mistaken, please someone correct me if I am wrong, jitsi-meet uses prosody for authentication. Prosody may be configured to authenticate against an ldap server through cyrus provider? 

I have found these links:

http://prosody.im/doc/authentication
http://prosody.im/doc/modules/mod_auth_cyrus
http://prosody.im/doc/cyrus_sasl

Setting Up Prosody to Authenticate Against LDAP:
http://blog.marc-seeger.de/2009/12/30/setting-up-prosody-to-authenticate-against-ldap/

**Comment by jamesarems** [comment]
Hi,
Authentication against ldap is possible with prosody . But my actual suggestion is , How to list all contacts ( ldap , internal_plain ...etc whatever it is) in 'contacts list'?  . Example scenario is , contact user is not online for meeting  so we can call him via SIP if contact list exist.
