### ISSUE TITLE
Would it be possible to drop Google-Analytics?

### ISSUE THREAD

**Issue by jfml** [jitsi/jitsi-meet#4170]
**Is your feature request related to a problem you are facing?**
Not really a problem but as a privacy conscious individual I don't really want to use services that give data to Google.

**Describe the solution you'd like**
So it would be amazing if you would not use analytics at all or

**Describe alternatives you've considered**
if that is not possible it would be really appreciated if you could use a more privacy-friendly analytics tool like [Matomo](http://matomo.org/). Thanks so much und keep up the good work!

**Comment by damencho** [comment]
Please for questions and problems use our community forum before opening new issues, thank you.

If you are talking about meet.jit.si, this is our choice to use it. If you do not want to trust or use it, you can always deploy your own deployment and enable your own analytics handler there. This is fully configurable:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L351
You can also use the option to disable ThirdPartyRequests option:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L305

**Comment by saghul** [comment]
Jitsi Meet supports pluggable analytics handlers. It currently ships with 2: Google Analytics and Amplitude. 

They only work if there is an API key configured for them, of course: https://github.com/jitsi/jitsi-meet/blob/5cc01b074e5a9a91b8706a81b9166c41c2b4f0f4/config.js#L351

You might have noticed the `scriptURLs` setting: https://github.com/jitsi/jitsi-meet/blob/5cc01b074e5a9a91b8706a81b9166c41c2b4f0f4/config.js#L359 you can add any analytics backend you like without having to modify the Jitsi Meet source code. It has to expose this API: https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/AbstractHandler.js you can look at the Google Analytics implementation for inspiration: https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/GoogleAnalyticsHandler.js

So, back to your initial message. No, there is no reason for us not to allow users to use whatever analytics they want. If you install Jitsi Meet on your own server no alaytics are sent anywhere so it's private by default.

**Comment by jfml** [comment]
Ok, thanks for the info.

**Comment by NicoHood** [comment]
I recently found out about jitsi-meet and found it a nice tool. However I also noticed the google analytic dependency, which gave me a very bad second impression. I fully understand, that the analytics setting is optional for custom servers, I am also aware that those servers exists, and I understand that it was your choice to use google analytics.

I just want to point out, that to me as a **potential customer**, looking for a secure communication tool, this makes a really **bad impression**. Especially when sharing this tool with friends, I always have to tell them to use another server, which makes it more complicated, than it should be. If you ask me, I'd definitely **remove this dependency** from the website and **use the site statistics of your webhoster** without any google scripts.

**Comment by jfml** [comment]
If I'm not mistaken they switched to https://amplitude.com/ now? Not sure if that's any better but it probably *looks* better because less people will know it's analytics … Not sure how I feel about this.

**Comment by saghul** [comment]
We have removed GA completely from meet.jit.si: https://github.com/jitsi/jitsi-meet/issues/4590#issuecomment-608510905 We were using both, so we haven't just enabled Amplitude now.

Here is our updated privacy policy: https://jitsi.org/meet-jit-si-privacy/
and terms of service: http://jitsi.org/meet-jit-si-terms-of-service/
