### ISSUE TITLE
[Android] Cannot copy chat message or open links in chat

### ISSUE THREAD

**Issue by olastor** [jitsi/jitsi-meet#4177]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

Don't know if this is an upcoming feature, but with the current chat window on android it's not possible to click on links or copy and paste chat messages.

---

## Current behavior
---

## Expected Behavior

- Links should be highlighted, clickable and redirect to the browser when clicking
- Long pressing on chat messages should copy chat messages or open a menu where you can select "copy" 
 
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details

- Phone: BQ Aquaris V
- Android: 7.1.2
- App Versoin: Jitsi Meet 19.1.0

---

**Comment by root0902** [comment]
> _This Issue tracker is only for reporting bugs and tracking code related issues._
> 
> Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.
> 
> ## Description
> Don't know if this is an upcoming feature, but with the current chat window on android it's not possible to click on links or copy and paste chat messages.
> 
> ## Current behavior
> ## Expected Behavior
> * Links should be highlighted, clickable and redirect to the browser when clicking
> * Long pressing on chat messages should copy chat messages or open a menu where you can select "copy"
> 
> ## Possible Solution
> ## Steps to reproduce
> # Environment details
> * Phone: BQ Aquaris V
> * Android: 7.1.2
> * App Versoin: Jitsi Meet 19.1.0

Have you find any solution to it??

**Comment by olastor** [comment]
> Have you found any solution to it, as I am facing the same issue.

Sorry, it's been a while but I think I did not find any way.
