### ISSUE TITLE
How to use different auth user with jigasi config

### ISSUE THREAD

**Issue by heutger** [jitsi/jitsi-meet#418]
I have a different auth user for my sip account at getonsip.com, but meanwhile I can provide it with the sipcommunicator.properties I can't provide it with the config file, as I don't know the parameter name, so dialing seems not to work.

**Comment by damencho** [comment]
Please use our dev mailinglist for questions. 
You can install jitsi desktop client, configure it the way so you can use it with your sip account and then use the relevant account properties from the sip-communicator.properties file and paste them in the jigasi config.
