### ISSUE TITLE
Any instructions on activation of Prezi in Jitsi

### ISSUE THREAD

**Issue by heutger** [jitsi/jitsi-meet#419]
Meanwhile I found instructions for desktop sharing (however currently not working with app installation) and for etherpad (working well), I didn't found any instructions on how to enable Prezi? Any help welcome!

**Comment by turint** [comment]
There is not much to enable -- if you see the button, you just use it and paste the url to the prezi presentation (Prezi is a presentation SaaS, hosted on prezi.com, so it's a third-party service). If you don't see the button, check that you have "prezi" in the list of toolbar buttons in the file interface_config.js

**Comment by heutger** [comment]
As discussed in the mailing list, there was an issue with the code, why it was commented out in the nightly repository, but it got reenabled recently and is now working for me. Thanks!

**Comment by dbareiro** [comment]
Hi!

I tried adding "prezi" in "TOOLBAR_BUTTONS:", but I do not see the button appear. Is the sharing of documents with Prezi no longer available?

Investigating I've seen the issue #531

Kind regards,
Daniel
