### ISSUE TITLE
How to Convert Video Quality Control on Web to Native

### ISSUE THREAD

**Issue by XDhughie** [jitsi/jitsi-meet#4200]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.
jitsi-meet only support Video Quality control on web, but I want to control Video Quality on Native,
I know it is not a easy work, so i need your help! thank u!

**Comment by saghul** [comment]
This is on our TODO list, but we haven't gotten around to it yet. It's not yet clear how we'll want this to look like UI/ UX wise, so I can't really provide any guidance in terms of implementing it yourself, sorry.
