### ISSUE TITLE
Integrate Jitsi to Humhub

### ISSUE THREAD

**Issue by snap15** [jitsi/jitsi-meet#4201]
Hi Team,
we are using Humhub and would like to integrate Jitsi for Video Conference. Does a module exist, does anybody help us with code or a full description on "How to do?"
Love to hear from you soon...
Best regards

**Comment by damencho** [comment]
Please for question and problems use the community forum before opening new issues.

You can use the iframeAPI https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md
