### ISSUE TITLE
[iOS] iOS Upload issue

### ISSUE THREAD

**Issue by civilordergone** [jitsi/jitsi-meet#4203]
I am running into an issue with trying to upload my iOS build:
Due to your recommendation of having bitcode off, this is what apple throws:

**Too many symbol files - These symbols have no corresponding slice in any binary.**

What do you recommend?

**Comment by saghul** [comment]
I haven’t seen this one before. Is you app using frameworks other than Jitsi itself?

Is it open source, so I can eventually take a look?

**Comment by civilordergone** [comment]
I had to set bitcode off for the main target.
