### ISSUE TITLE
Echo cancellation breaks when speaking simultaneously.

### ISSUE THREAD

**Issue by DiThi** [jitsi/jitsi-meet#4208]
## Steps to reproduce
---
Using Chrome on Windows.
Person A has headphones (Bluetooth with 200ms latency, I don't know if it's relevant).
Person B uses speakers on a small room.

A speaks and echo cancellation works well after the first sentence.
A and B speak simultaneously for a moment (probably caused because of BT latency).
A speaks and hears himself. There's no more echo cancellation and it doesn't fix itself.
B mutes for a second, unmutes. Echo cancellation works again.

Echo cancellation should probably stop auto adjusting after the first couple of sentences.

**Comment by damencho** [comment]
Please use the community forum for questions or problems before opening new issues.

Echo cancelation is something the browser is offering as part of its webrtc implementation. So you can report this to the bug tracker of the browser you use.
