### ISSUE TITLE
Bitcode enable issue with latest code

### ISSUE THREAD

**Issue by uranashel** [jitsi/jitsi-meet#4209]
Hi @saghul , I got issue while trying compile lastest code. 
```
jitsi-meet/node_modules/react-native-webrtc/ios/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
```

I have enabled Bitcode to true, but still no luck. Please help me out. Thanks so much

**Comment by saghul** [comment]
Run this script: https://github.com/jitsi/react-native-webrtc/blob/master/tools/downloadBitcode.sh It's part of the package, so you'll havee it in `node_modules/react-native-webrtc/tools/downloadBitcode.sh`

I need to re-think how to handle bitcode a bit better, maybe by integrating this script or something. I'll keep this open.

**Comment by uranashel** [comment]
Oh thanks, I will give a shot try.

**Comment by uranashel** [comment]
Hi @saghul ,
It works. 
But anytime I press on Hangup button (Leave room) in debug mode, it always show this log. 
```
console.error:"[__filename]", "<_addOrRemoveAudioElement>:", "REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_JOINED_SOUND"
```
Is it a bug?

**Comment by saghul** [comment]
You can ignore it.

**Comment by uranashel** [comment]
Hi @saghul , 
Thank for that. But I have another question that Im trying to build sdk my own. It done. That what I do: 
- Build, file would be located in tmp/repo
- I replace 
```
allprojects {
    repositories {
        maven { url "file:/tmp/repo" }
        google()
        jcenter()
    }
}
```
And I put this line to app buildgradle: 
```implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }```

But it got crash while I start jitsi view
Here is the log: 
```
beginning of crash
2019-05-14 17:37:03.230 14448-15103/com.sns E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.sns, PID: 14448
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by saghul** [comment]
Please keep issues on topic. Open a new issue for this one.

**Comment by Sharcoux** [comment]
I have the same issue, but `node_modules/react-native-webrtc/tools/` contains only `build-webrtc.py / ios_arch.js / release.sh`. There is no `downloadBitcode.sh`

**Comment by saghul** [comment]
What version of the module are you using? That got added in 1.75.

**Comment by Sharcoux** [comment]
My bad. I forgot that I'm relying on a fork. I needed to fork to make it work with mediasoup and I failed to make it work with the last version. Thanks for your answer. I'll try to find a solution.

**Comment by ngoctan95** [comment]
I did make it work properly hehe. 
Let me know what issue is.

**Comment by saghul** [comment]
@Sharcoux No worries. The 1.75 release contains a very important piece to make it work with mediasoup, AFAICT it should just work.

**Comment by Sharcoux** [comment]
I know, but in practice, it didn't for me. But I'll get back into it as soon as I successfully upgrade my app to RN 60... I fixed the issue by running your script for the build M69.1.

**Comment by PrimulaX** [comment]
Shell script doesn't work, I guess file doesn't even exit on bintray server anymore.

**Comment by saghul** [comment]
Update to 1.89, the build artifacts are now stored in GH releases.

**Comment by PrimulaX** [comment]
@saghul I can't, there is some breaking changes for me, Is there any other way?

**Comment by saghul** [comment]
What breaking change? I have see no such reports.

You can make bitcode enabled builds with the Python script in the tools folder, the process is documented.

**Comment by PrimulaX** [comment]
> What breaking change? I have see no such reports.
My app builds fail

**Comment by saghul** [comment]
> My app builds fail

How? Unless you provide logs or any other information nobody can help you.

**Comment by PrimulaX** [comment]
![image](https://user-images.githubusercontent.com/16132259/117263470-5a9a7780-ae63-11eb-8ebe-6c79ca1579a0.png)
and its require ios version 11

**Comment by saghul** [comment]
That errors shows up when you have an outdated CocoaPods. Make sure you are on >= 1.10. As for iOS 11, yeah, it's a requirement now.

If you can't work within those requirements you are on your own. You can build the bitcode framework with the Python script.

**Comment by PrimulaX** [comment]
Okay, Thanks I'll try.

**Comment by molnartimi** [comment]
I have the same problem since yesterday! I updated my cocoapods from 1.9 to 1.10.0, deleted node_modules and Pods, after new npm i and pod install ios/scripts/release-sdk.sh stopped working. The file that node_modules/react-native-webrtc/tools/downloadBitcode.sh tries to download doesn't exist, so it can't fix the problem. I use react-native-webrtc 1.84.0. I tried also with 1.89.1 and there are still errors, WebRTC sources are not found, eg.
```
/jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/VideoCaptureController.h:3:9: fatal error: 
      'WebRTC/RTCCameraVideoCapturer.h' file not found
#import <WebRTC/RTCCameraVideoCapturer.h>
```

**Comment by PrimulaX** [comment]
@saghul Is there any chance to retrieve these old files from bintray, its quite an issue for me.

**Comment by saghul** [comment]
> Is there any chance to retrieve these old files from bintray, its quite an issue for me.

I'm afraid not, I can no longer signin to bintray.

**Comment by saghul** [comment]
> I have the same problem since yesterday! I updated my cocoapods from 1.9 to 1.10.0, deleted node_modules and Pods, after new npm i and pod install `ios/scripts/release-sdk.sh` stopped working. The file that `node_modules/react-native-webrtc/tools/downloadBitcode.sh` tries to download doesn't exist, so it can't fix the problem. I use react-native-webrtc 1.84.0. I tried also with 1.89.1 and there are still errors, WebRTC sources are not found, eg.
> 
> ```
> /jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/VideoCaptureController.h:3:9: fatal error: 
>       'WebRTC/RTCCameraVideoCapturer.h' file not found
> #import <WebRTC/RTCCameraVideoCapturer.h>
> ```

Are you using Xcode 12.4 ?

**Comment by molnartimi** [comment]
> > I have the same problem since yesterday! I updated my cocoapods from 1.9 to 1.10.0, deleted node_modules and Pods, after new npm i and pod install `ios/scripts/release-sdk.sh` stopped working. The file that `node_modules/react-native-webrtc/tools/downloadBitcode.sh` tries to download doesn't exist, so it can't fix the problem. I use react-native-webrtc 1.84.0. I tried also with 1.89.1 and there are still errors, WebRTC sources are not found, eg.
> > ```
> > /jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/VideoCaptureController.h:3:9: fatal error: 
> >       'WebRTC/RTCCameraVideoCapturer.h' file not found
> > #import <WebRTC/RTCCameraVideoCapturer.h>
> > ```
> 
> Are you using Xcode 12.4 ?

No, just updated to Xcode 12.5

**Comment by saghul** [comment]
Can you build Jitsi Meet master? We use that combination of versions (well CocoaPods 1.10.1 I think) and it's working fine.

**Comment by molnartimi** [comment]
> Can you build Jitsi Meet master? We use that combination of versions (well CocoaPods 1.10.1 I think) and it's working fine.

Yes I can, build works fine on your master branch. I will look into our changes to find the problem. Thanks for the help!

**Comment by syedmudaseer** [comment]
> > I have the same problem since yesterday! I updated my cocoapods from 1.9 to 1.10.0, deleted node_modules and Pods, after new npm i and pod install `ios/scripts/release-sdk.sh` stopped working. The file that `node_modules/react-native-webrtc/tools/downloadBitcode.sh` tries to download doesn't exist, so it can't fix the problem. I use react-native-webrtc 1.84.0. I tried also with 1.89.1 and there are still errors, WebRTC sources are not found, eg.
> > ```
> > /jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/VideoCaptureController.h:3:9: fatal error: 
> >       'WebRTC/RTCCameraVideoCapturer.h' file not found
> > #import <WebRTC/RTCCameraVideoCapturer.h>
> > ```
> 
> Are you using Xcode 12.4 ?

yes i am using xcode 12.4 any issue ?

**Comment by syedmudaseer** [comment]
@saghul 

After node_modules/react-native-webrtc/tools/downloadBitcode.sh, i did pod install then i am getting new error
![image](https://user-images.githubusercontent.com/25653053/120147145-d938c980-c203-11eb-8908-b8934711b529.png)

my pod file

platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'foodapp' do
  # Pods for foodapp
  use_frameworks!
  pod 'Kommunicate'
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  target 'foodappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end
# target.build_configurations.each do |config|
#   if config.name != 'Debug'
#     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#     if target.name == "react-native-webrtc"
#       config.build_settings["EXCLUDED_ARCHS"] = "armv7"
#       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#     end
#   end
# end
# end
target 'foodapp-tvOS' do
  # Pods for foodapp-tvOS

  target 'foodapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by iim-norse** [comment]
`
.../Library/Developer/Xcode/DerivedData/jitsi-meet-bzfgcpkzszajhfduxetkthysfctq/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/username/Library/Developer/Xcode/DerivedData/jitsi-meet-bzfgcpkzszajhfduxetkthysfctq/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/WebRTC.framework/WebRTC' for architecture arm64

`
how to fix this ?

**Comment by saghul** [comment]
Do you need bitcode? If not, disable it in your project.

**Comment by iim-norse** [comment]
> Do you need bitcode? If not, disable it in your project.

sorry, here or where ?
<img width="1118" alt="Снимок экрана 2022-04-08 в 15 37 57" src="https://user-images.githubusercontent.com/99746223/162437051-7da3649c-bb5a-4cdf-9aa1-905ffc1123a4.png">

**Comment by PrimulaX** [comment]
@iim-norse better to download bitcode for webrtc with shell script under `node_modules/react-native-webrtc/tools/downloadBitcode.sh`

**Comment by saghul** [comment]
If you are building Jitsi Meet then you need it. See https://github.com/jitsi/jitsi-meet/issues/4209#issuecomment-492128520

**Comment by iim-norse** [comment]
Aha! Thanks very much guys! run this script helped

**Comment by iim-norse** [comment]
@saghul https://dl.bintray.com/webrtc-builds/webrtc-builds/M75-1/WebRTC.framework.tar.xz no file here anymore ))

**Comment by saghul** [comment]
Good. That version is so old nobody should be using it.

**Comment by iim-norse** [comment]
I stiil get error 
```
Developer/Xcode/DerivedData/jitsi-meet-eelicumonhclghdauisfwnpxklay/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '..../Library/Developer/Xcode/DerivedData/jitsi-meet-eelicumonhclghdauisfwnpxklay/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/WebRTC.framework/WebRTC' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by iim-norse** [comment]
turn off bitcode in project helped
