### ISSUE TITLE
Crash app in building Android SDK my own

### ISSUE THREAD

**Issue by uranashel** [jitsi/jitsi-meet#4212]
Hi @saghul , 
I have another question that Im trying to build sdk my own. It done. That what I do: 
- Build, file would be located in tmp/repo
- I replace 
```
allprojects {
    repositories {
        maven { url "file:/tmp/repo" }
        google()
        jcenter()
    }
}
```
And I put this line to app buildgradle: 
```implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }```

But it got crash while I start jitsi view
Here is the log: 
```
beginning of crash
2019-05-14 17:37:03.230 14448-15103/com.sns E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.sns, PID: 14448
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
```
```Failed to resolve: org.webkit:android-jsc:r224109```

Many thanks 💯

**Comment by saghul** [comment]
What git commit are you building exactly?

**Comment by uranashel** [comment]
I use the lastest commit in master branch

**Comment by saghul** [comment]
Have you *just* built the SDK? The lineNumber bug was fixed with RN 0.59.5 ( we are now at .8) and the dependency on android-jsc is no longer needed. What specific commit hash did you build?

**Comment by uranashel** [comment]
I have pulled from lastest changes. 
Hash commit: 02955ab5
But, what I did in those steps are correctly?

**Comment by saghul** [comment]
What steps did you follow? Looks like you are not using the latest RN version.

**Comment by ngoctan95** [comment]
same issue

**Comment by saghul** [comment]
You haven't pushed the new react-native version to your maven repo. This doesn't happen automatically. Please use the release script as described here: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build-and-use-your-own-sdk-artifactsbinaries it will take care of that too.

> How should I replace my new sdk by the correct way?

If you have changes in the code you'll need to make then every time you update the source code from git.

**Comment by nitish1227** [comment]
@saghul @ngoctan95 @uranashel @jcfischer @tomdee 
Please help me. Only Android signed build crash. But debug build is working perfectly.
I am using this.

allprojects {
repositories {
google()
jcenter()
mavenCentral()
maven { url “https://jitpack.io” }
maven { url ‘https://maven.google.com/’ }
maven { url ‘https://oss.sonatype.org/content/repositories/snapshots/’ }
maven { url ‘https://raw.github.com/rockerhieu/mvn-repo/master/’ }
maven {
url “file:/tmp/repo”

    }
   
}
}

app gradle file:

dependencies {
implementation fileTree(dir: ‘libs’, include: [’*.jar’])
implementation “org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version”
implementation project(’:voiplib’)
implementation project(’:emojicons’)
implementation project(’:emojiconizes’)
// implementation(project(path: ‘:backend’, configuration: ‘android-endpoints’)) {
// exclude group: ‘com.google.guava’, module: ‘guava-jdk5’
// }
endpointsServer project(path: “:backend”, configuration: “endpoints”)

implementation('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
    transitive = true;
}
// implementation ‘com.onesignal:OneSignal:3.10.7@aar’
implementation ‘com.google.android.material:material:1.0.0’
implementation ‘androidx.multidex:multidex:2.0.0’
implementation ‘androidx.legacy:legacy-support-v4:1.0.0’
implementation ‘androidx.cardview:cardview:1.0.0’
implementation ‘androidx.appcompat:appcompat:1.0.0’
implementation ‘androidx.recyclerview:recyclerview:1.0.0’
implementation ‘androidx.constraintlayout:constraintlayout:1.1.3’

implementation 'com.google.firebase:firebase-core:16.0.8'
implementation "com.google.firebase:firebase-messaging:17.3.4"
implementation "com.google.firebase:firebase-messaging:17.5.0"
// implementation ‘com.google.android.gms:play-services-gcm:9.0.1’

implementation 'com.google.android.gms:play-services-location:9.0.1'
implementation 'com.google.android.gms:play-services-analytics:9.0.1'
implementation 'com.google.android.gms:play-services-appindexing:9.0.1'

implementation 'me.relex:circleindicator:1.2.2@aar'
implementation 'com.anjlab.android.iab.v3:library:1.0.36'
implementation 'com.firebase:firebase-client-android:2.5.2'
implementation 'com.google.code.gson:gson:2.8.2'
/*implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'io.reactivex.rxjava2:rxjava:2.1.6'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'*/
implementation 'com.github.bumptech.glide:glide:3.7.0'
implementation 'net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:2.0.1'

implementation('com.google.api-client:google-api-client:1.23.0')
        {
            exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        }
implementation('com.google.http-client:google-http-client-android:1.23.0')
        {
            exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        }


//****************** Web Api **************************/
implementation("com.squareup.retrofit2:retrofit:$rootProject.retrofitVersion") {
    exclude module: 'okhttp'
}
implementation "com.squareup.retrofit2:converter-gson:$rootProject.coverterGson"

implementation "com.squareup.okhttp3:logging-interceptor:$rootProject.logginInterceptorVersion"
implementation "com.squareup.okhttp3:okhttp:$rootProject.okkhttpVersion"
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'io.reactivex.rxjava2:rxjava:2.1.6'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'


/*View model*/
implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
implementation 'androidx.lifecycle:lifecycle-viewmodel:2.0.0'
implementation 'androidx.lifecycle:lifecycle-livedata:2.0.0'
annotationProcessor 'androidx.lifecycle:lifecycle-compiler:2.0.0'

/*Socket Chat */
compile('com.github.nkzawa:socket.io-client:0.6.0') {
    exclude group: 'org.json', module: 'json'
}


/* AWS */
implementation 'com.amazonaws:aws-android-sdk-s3:2.7.+'
implementation 'com.amazonaws:aws-android-sdk-cognito:2.7.+'

/*crpto js*/
implementation group: 'com.sun.jersey', name: 'jersey-client', version: '1.19.4'
implementation group: 'org.bouncycastle', name: 'bcprov-jdk16', version: '1.46'

/*Glide*/

//  implementation 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
//******************* Image Loader ********************/
implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'

/*Exo Player*/
// add exo player dependency here
implementation 'com.google.android.exoplayer:exoplayer:2.11.1'
implementation 'com.danikula:videocache:2.7.1'
// implementation 'org.jsoup:jsoup:1.10.3'

/* Loader indicater*/
implementation 'com.wang.avi:library:2.1.3'

/* Uploading dialog */
implementation 'com.kaopiz:kprogresshud:1.2.0'


//implementation project(':sdk')
implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }
}
