### ISSUE TITLE
jitsi-meet show user login if authentication required

### ISSUE THREAD

**Issue by vieridipaola** [jitsi/jitsi-meet#4213]
Hi,

As reported on the Jitsi Forum (https://community.jitsi.org/t/jitsi-meet-ldap-active-directory-authentication-how-to-get-log-info/18037) I can't seem to get Jitsi-Meet Web UI to show the user login form when Prosody is configured with modules such as "ldap2" or "external". The only way Jitsi-Meet shows a form is when using "internal_plain".

Is this a known issue?

**Comment by saghul** [comment]
Please don't open new issues if the matter is already being discussed in the forum.
