### ISSUE TITLE
Issue while building my own SDK

### ISSUE THREAD

**Issue by ngoctan95** [jitsi/jitsi-meet#4215]
Thanks @saghul  for this library. 
While I tried to build my own SDK, I follow document but my custom UI not work. 

```
My build.gradle project level: 
repositories {
        maven { url "file:/tmp/repo/" }
        google()
        jcenter()
    }
.......
```
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "file:/tmp/repo/" }
    }
}
```
My build.gradle app level: 
implementation('org.jitsi.react:jitsi-meet-sdk:+') {        transitive = true }
```

But the user interface not change. Which step I miss? Have a nice day @all

**Comment by saghul** [comment]
> Thanks @saghul for this library.

Thanks, but I can't take all the credit, I'm just part of an awesome team of very talented individuals :-)



> While I tried to build my own SDK, I follow document but my custom UI not work.

What steps did you follow exactly and what changes did you make and where?

**Comment by ngoctan95** [comment]
@saghul , 👍 
I built my SDK and it released jitsi-meet-sdk-2.1.0.aar.
But when I added below line: 
```
implementation('org.jitsi.react:jitsi-meet-sdk:2.0.0') { transitive = true }
```
And I press Run, it always show standard UI. 
I could not gradle ```org.jitsi.react:jitsi-meet-sdk:2.1.0'``` , Idk why it not, error pointed out: 
``` Error: fail to resolve com.facebook```

**Comment by ngoctan95** [comment]
Should I add or clean something? I guess that the ```file:/tmp/repo``` not directly pointed there. And it still take the original sdk.

**Comment by saghul** [comment]
Yes, you need to add your own maven repo to the project's build.gradle file. Please see the README: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#use-pre-build-sdk-artifactsbinaries (you'd put your own URL there, of course)
