### ISSUE TITLE
Make all third-party requests configurable

### ISSUE THREAD

**Issue by micahflee** [jitsi/jitsi-meet#422]
Right now a default installation of Jitsi Meet automatically makes a handful of requests to third-party servers. Some of these might be useful (like Gravatar for avatars, or CallStats for analytics), but not everyone wants this.

It would be great if third-party requests could be configurable just by changing variables in `config.js`. Individual sites could make minor patches on their own to disable the third-party requests, but if they're using the official debian repository, updates will blow away their patches, so it would be great if these could be implemented in the main project.

The current version of Jitsi Meet makes requests to these domains:

* **gravatar.com**: Avatars all get loaded from Gravatar. This should be optional, and if Gravatar is disabled then everyone's avatars can just be the same generic image, or a random image from a set of generic images.
* **callstats.io**: A script tag in `index.html` loads a javascript file from api.callstats.io always, even if the service itself is disabled in config.js. The script tag shouldn't get loaded unless the server is using it.
* **google-analytics.com**: A script tag in `index.html` loads `analytics.js`, which adds Google Analytics code to the page, using Jitsi's account. This should be optional, and if disabled in `config.js` it shouldn't make any requests to an analytics server.

As far as I can tell, these are the only third-party requests that get made by Jitsi Meet. I'm all for adding new functionality in the future that makes third-party requests, but it would be excellent if that functionality could always be optional so that servers where privacy is a big priority can choose to not use them.

**Comment by bickelj** [comment]
See https://github.com/jitsi/jitsi-meet/pull/427 for a possible approach addressing 2/3 third parties.

**Comment by micahflee** [comment]
@bickelj nice!

Yes, Gravatar is more complicated. I wrote my own patch that basically rips out all the gravatar code and replaces it with local images: https://github.com/micahflee/jitsi-meet/commit/b96dd151998506178f9bdb80ea0b7993bb3a6f2d but the Jitsi Meet project probably wants something more elegant, that gives people the option to still use Gravatar if they want.

**Comment by bgrozev** [comment]
@micahflee I think we could accept your solution, if you just make it optional (i.e. can be configured through config/interfaceConfig).

**Comment by bickelj** [comment]
https://github.com/jitsi/jitsi-meet/pull/427 now takes care of 3/3 third party requests.

**Comment by bickelj** [comment]
Because https://github.com/jitsi/jitsi-meet/pull/427 was just merged (thanks @bgrozev), this can probably be closed. Thanks @micahflee for bringing up the issue.

**Comment by micahflee** [comment]
Awesome thank you so much @bickelj for making the PR. Now that it's merged and a new release has been made I just updated the debian package on my server, set `disableThirdPartyRequests` to true, and it works great!
