### ISSUE TITLE
Access to Office 365 calendar (business account)

### ISSUE THREAD

**Issue by kazssym** [jitsi/jitsi-meet#4221]
Trying to access my Office 365 calendar (business account) in Jitsi Meet caused the following error. Could you configure Jitsi Meet so that a business account user could allow access to their calendar?

![image](https://user-images.githubusercontent.com/4685621/57753835-1a96d300-7728-11e9-8878-a715ab16cf88.png)

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

Do you know how to do that? Whatever was possible was already enabled in the Microsoft console. The error sounds to me that your administrator needs to allow using this app.

**Comment by kazssym** [comment]
I'm the administrator of the tenant and have no information on how to install Jitsi Meet to our tenant.

Ok, I will use the community forum.

**Comment by sgoll** [comment]
@kazssym I am having the exact same issue and so far was unable to find a solution in the community forum. Did you ever find out a solution to this problem?
