### ISSUE TITLE
Not able to git commit -  error  Line 178 exceeds the maximum line length of 80  max-len

### ISSUE THREAD

**Issue by palmtown** [jitsi/jitsi-meet#4224]
Hello,

When I pulled the latest changes from the repo, and tried to commit to my local repo, I got an error:  166 problems (166 errors, 0 warnings).

All of the errors are the same, exceeds the maximum line length of 80  max-len.  It seems it is running lint which produces these errors and prevents me from committing the changes.  Note that all of these errors are generated from the master code i pulled from the jitsi repo and I did not introduce any of them.

Is there a way to force it to commit and bypass these errors, or what is the fix available?

**Comment by damencho** [comment]
Have you done npm install before committing? Line length had been increased recently to 120 maybe you are using not updated lib with those settings ...

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

**Comment by saghul** [comment]
> Is there a way to force it to commit and bypass these errors, or what is the fix available?

`git commit --no-verify`

**Comment by palmtown** [comment]
Hello All,

Thank you for your help.  It was that I needed to run npm install.
