### ISSUE TITLE
video confrencing is working fine from desktop to desktop but not working in case of mobile app to web app

### ISSUE THREAD

**Issue by sankus2212** [jitsi/jitsi-meet#4226]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by sankus2212** [comment]
[conference.js] <e.value>:  CONFERENCE FAILED: conference.videobridgeNotAvailable

this is the error in the console. The web application crashes when another person join the confrence from mobile.

**Comment by saghul** [comment]
Please ask these kind of questions in our community. Your deployment is misconfigured, there is no videobridge available as the error states.
