### ISSUE TITLE
compiling iOS app throws watchkit codesigning errors

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#4227]
Hi guys,

I just tried compiling a fresh version of the iOS app and I noticed you now have watchkit enabled too.

Can I compile the app without watchkit considering I don't have an Apple watch?
How would I go about doing that?

Thanks

Code Signing Error: No profiles for 'org.jitsi.meet.watchkit.extension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'org.jitsi.meet.watchkit.extension'.
Code Signing Error: Code signing is required for product type 'WatchKit Extension' in SDK 'watchOS 5.2'

**Comment by paweldomas** [comment]
Hi, maybe try excluding JitsiMeetCompanion from the jitsi-meet target ?

**Comment by pdarcos** [comment]
Thanks @paweldomas
