### ISSUE TITLE
Video mute fails with 'stopMediaStream is not a function'

### ISSUE THREAD

**Issue by matthias-w** [jitsi/jitsi-meet#423]
I am using lib-jitsi-meet and when I try to mute the video there is an error:
'stopMediaStream is not a function'
The error occurs in 'JitsiLocalTrack.prototype._setMute' method
at line (~ 1050 in lib-jitsi-meet.js):
this.rtc.stopMediaStream(this.stream);

**Comment by bgrozev** [comment]
This has probably been fixed by now. Re-open if necessary
