### ISSUE TITLE
[iOS] the app freezes on iPad

### ISSUE THREAD

**Issue by rutmb** [jitsi/jitsi-meet#4239]
## Description
The iOS app periodically freezes when in video conference with 3 or more participants or when I leave the conference.
There is log message:
[error][tid:com.facebook.react.JavaScript] '[__filename]', '<l>: ', '_REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_JOINED_SOUND'

## Current behavior
The app freezes

## Expected Behavior
The app is running without freezes

## Steps to reproduce
Go to the video conference on iPad, the camera should be on for all participants.

# Environment details
iOS 12.2, iPad (tested on iPad 2018, iPad mini 2)
Jitsi Meet SDK was built from commit jitsi-meet_3734.

**Comment by saghul** [comment]
> [error][tid:com.facebook.react.JavaScript] '[__filename]', ': ', '_REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_JOINED_SOUND'

Anything else? This log is basically harmless.

**Comment by rutmb** [comment]
Yes. It seems to me that app in conference with a lot of participants uses a lot of memory / cpu and it freezes. 
Did you test iOS app in video conference mode? How many participants with video were there?

**Comment by saghul** [comment]
Ho many participants are you testing? Generally, video can be very demanding, as it uses the VP8 codec which is not hardware acelerated.

**Comment by rutmb** [comment]
About 5-6 participants and app freezes. In audio conference everything is fine.
