### ISSUE TITLE
Certificate for download.jitsi.org is expired

### ISSUE THREAD

**Issue by jbfriedrich** [jitsi/jitsi-meet#4245]
I tried to access download.jitsi.org via HTTPS, but the certificate seems to be expired.

![Screen Shot 2019-05-21 at 17 34 35](https://user-images.githubusercontent.com/1968991/58110867-a1e4ba80-7bf0-11e9-8497-4c18b27d45d9.png)

**Comment by damencho** [comment]
Known issue and we are working on fixing it. Will let you know once it is fixed.

**Comment by damencho** [comment]
All issues had been fixed and download.jitsi.org is back.
