### ISSUE TITLE
Cannot building Android SDK my own

### ISSUE THREAD

**Issue by california257** [jitsi/jitsi-meet#4248]
I don't run command line (./android/scripts/release-sdk.sh /tmp/repo)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/18181704/58146796-e8362a00-7c81-11e9-9c48-9498a531776f.png">
Please help me! thank you

**Comment by saghul** [comment]
The answer is right there. You are missing the `jq` utility. On macOS you can install it with Homebrew: `brew install jq`

**Comment by riyas145** [comment]
for windows?
