### ISSUE TITLE
Possibility to add video quality filter like on the meet.jit.si website UI within the API.

### ISSUE THREAD

**Issue by loulou2852** [jitsi/jitsi-meet#4249]
Hi,

Sometimes I encounter some connecting issues, even with a "good" network.

Do you know if there is something like encoding or compression, video size and/or video fps that allow to reduce video quality.

For exemple with my computer, I try to reduce to low quality, but it still responding with the HD instead of the LD.

And finally my initial question, related to this one:

This setting (Manage video quality) is only available on the website meet.jit.si, but not available on the API.

Is it possible to integrate it afterward?

Thanks 

Regards.

Louis

**Comment by virtuacoplenny** [comment]
Right now there isn't an implemented way to dynamically modify the send side of video quality. The way to change it would be using different constraints for obtaining your local video. https://github.com/jitsi/jitsi-meet/blob/5101f69e4ed3d128cb6b2b85d830dd24ea34e0d2/config.js#L103, https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints. The video quality dialog affects only receive side and only when the call is not peer-to-peer (not a 1-on-1 call in Chrome).

As for the video quality dialog, you are correct that its functionality is accessible only through the UI itself and not through the iFrame api. There are currently no plans to make it accessible through the API so someone would have to proactively make the change. Here is an example of updating the API https://github.com/jitsi/jitsi-meet/pull/4237.
