### ISSUE TITLE
how to change language in android?

### ISSUE THREAD

**Issue by zhaozhilong001** [jitsi/jitsi-meet#4256]

**Comment by zhaozhilong001** [comment]
why close it？

**Comment by saghul** [comment]
We have not 1 or 2, but 3 issue templates which you chose to ignore. Please use them. Also use search, this has been answered before.

**Comment by wQueen** [comment]
> We have not 1 or 2, but 3 issue templates which you chose to ignore. Please use them. Also use search, this has been answered before.

Hi saghul, I have searched nearly all the similar issue templates, but it still doesn't work for me. My phone local language is Simplified Chinese. I think maybe it's better to add language selecting in Settings menu on App, just like the backend server did?
