### ISSUE TITLE
[iOS] ReferenceError: Can't find variable: APP

### ISSUE THREAD

**Issue by civilordergone** [jitsi/jitsi-meet#4272]
```
Strophe: User connection callback caused an exception: ReferenceError: Can\'t find variable: APP
'[modules/xmpp/strophe.util.js]', '<i>: ', 'Strophe: User connection callback caused an exception: ReferenceError: Can\'t find variable: APP'

 [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
```

I have the framework building, the view loads but it has a spinner in the middle and throws the above error.  :|

**Comment by saghul** [comment]
Do you have a longer trackeback? Have you modified the code in any way? What steps did you follow to reproduce?

**Comment by civilordergone** [comment]
Hmm.. I have modified the code, do you know how to use the live js debugging w/ react-native?

**Comment by saghul** [comment]
Shake the device and you'll see the dev menu.

**Comment by civilordergone** [comment]
It turned out to be custom code, your framework is all good.  Thanks so much for the help!
