### ISSUE TITLE
App_Name variable has no effect

### ISSUE THREAD

**Issue by RcTomcat1** [jitsi/jitsi-meet#4273]
Changing the App_Name Setting to something other than Jitsi meet seems to have no effect.
The Browser Tab is still called Jitsi Meet.
A server reboot does not solve it.
I cleared my browser cache of course and tried several different computers.

**Comment by virtuacoplenny** [comment]
Are you seeing this behavior in-meeting or on the welcome page? I see the JS to change the title is run when in a conference (and a little late) but not on the welcome page. https://github.com/jitsi/jitsi-meet/blob/72a1def571b5b1039ebcb9d2be2a3a1c775a2276/modules/UI/UI.js#L207

**Comment by RcTomcat1** [comment]
The welcome page.
I can see the change in title in a conference.

**Comment by virtuacoplenny** [comment]
Yeah, so that's likely an oversight on the jitsi-meet side; I don't see why it would be intentional. If you have access to the static html files you could get away with setting the title in there. https://github.com/jitsi/jitsi-meet/blob/master/title.html#L1

**Comment by RcTomcat1** [comment]
Changing it directly in the title html works of course.
I just assumed that the variable would also change the welcome page title. As you said, likely to be an oversight :)
