### ISSUE TITLE
Image Problems After Connection

### ISSUE THREAD

**Issue by echooooooo** [jitsi/jitsi-meet#4274]
## Description
On some Huawei Mat20 devices, jitsi meet has a problem with the display connection after it is connected, but voice can be heard and image can not be seen. This is true every time, and all kinds of network environments have tried.

## Current behavior
---Can be connected, after the connection will show that there is a connection problem ("USER_CONNECTION_INTERRUPTED"), even if the network environment is good, can not see the image, can only hear the voice.

## Expected Behavior
---Normal display of image and sound after connection

## Possible Solution
---Is Huawei's mobile phone support bad?Or we didn't fully release jitsi meet when the meeting ended？

**Comment by saghul** [comment]
Aare you using the Jitsi Meet app or your own? meet.jit.si or your own? Can you perhaps record a small video showing the issue?

**Comment by echooooooo** [comment]
https://www.bilibili.com/video/av53963180/   
I found that when I finished the video conference, the system management on my mobile phone showed that the camera was being used by jitsi meet. And I can't unlock my phone with face recognition. It's supposed that the camera hasn't been released. Can you give me some suggestions on how to solve this problem?

**Comment by echooooooo** [comment]
> Aare you using the Jitsi Meet app or your own? meet.jit.si or your own? Can you perhaps record a small video showing the issue?

https://www.bilibili.com/video/av53963180/
I found that when I finished the video conference, the system management on my mobile phone showed that the camera was being used by jitsi meet. And I can't unlock my phone with face recognition. It's supposed that the camera hasn't been released. Can you give me some suggestions on how to solve this problem?

**Comment by echooooooo** [comment]
> Aare you using the Jitsi Meet app or your own? meet.jit.si or your own? Can you perhaps record a small video showing the issue?

![屏幕快照 2019-05-31 下午3 09 27](https://user-images.githubusercontent.com/10336892/58688125-246e3680-83b6-11e9-96cf-a95f64510380.png)

Memory is increasing.

**Comment by saghul** [comment]
Have you enabled the welcome page in the SDK? Whjat SDK version are you using? How are you leaving the meeting? Those active threads suggest the video track has not yet been disposed.
