### ISSUE TITLE
ice

### ISSUE THREAD

**Issue by WJdenghuo** [jitsi/jitsi-meet#4275]
in /etc/jitsi/meet/*-config.js  p2p  only stun
need ice like this
[
  {urls: 'stun:stun1.example.net'},
  {urls: ['turns:turn.example.org', 'turn:turn.example.net'],
    username: 'user',
    credential: 'myPassword',
    credentialType: 'password'},
  {urls: 'turns:turn2.example.net',
    username: '22BIjxU93h/IgwEb',
    credential: {
      macKey: 'WmtzanB3ZW9peFhtdm42NzUzNG0=',
      accessToken: 'AAwg3kPHWPfvk9bDFL936wYvkoctMADzQ5VhNDgeMR3+ZlZ35byg972fW8QjpEl7bx91YLBPFsIhsxloWcXPhA=='
    },
    credentialType: 'oauth'}
];

How to configure

**Comment by saghul** [comment]
It says stun, but it really means "iceServers". This setting is applied to RTCPeerConnection's iceServer property: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L331
