### ISSUE TITLE
Jitsi meet works in browser, not through RocketChat

### ISSUE THREAD

**Issue by stevenmcastano** [jitsi/jitsi-meet#4278]
## Description

If I have multiple clients connect through the normal web interface by just going to "meet.mydomain.com" everything seems to work fine. I get two way audio, video everything. However, if I use the button in the RocketChat client to create a video call, it starts the call, everyone can connect, but all of a sudden now I don't seem to get audio or video working anymore.

Has anyone experienced this before? I think there must be a configuration problem... if I leave the RocketChat server set to use the publit jitsi meet instance it seems to work fine, but when I switch it to my own, I don't get any audio or video passing through anymore.

**Comment by saghul** [comment]
Do you observe any errors in the JS console when joining via Rocket.Chat?

**Comment by stevenmcastano** [comment]
No errors anywhere... everything seems to join fine, but there is no audio or video... I also notice in the jitsi meet window the "stats" screen just shows N/A for everything... no bandwidth stats or anything.

**Comment by saghul** [comment]
Can you paste the output of the JS console in a gist?

**Comment by stevenmcastano** [comment]
@saghul what output exactly are you looking for??

(Sorry for the delay here, I got side-tracked with about 12 other projects... but I am still having the same issue)

**Comment by saghul** [comment]
I don't know the exact output, but we do log how we create streams so the JS console logs should shed some light here.

**Comment by stevenmcastano** [comment]
The problem is I don't know how to get the JS console logs from the RocketChat desktop client... it's not running in a browser so I have no developer tools. Are there server-side logs I can capture instead?

**Comment by saghul** [comment]
Ah, I see. I think Rocket.Chat uses electron, so I assume there must be a way to open the developer tools console.

**Comment by rasos** [comment]
You may need to check your proxy to allow cross site CORS or try to open the video conference in a separate tab (which is a setting in RocketChat and is more convenient for users as you still can navigate in chat channels while staying connected in the conference).
