### ISSUE TITLE
Xcode error using cocoapod 

### ISSUE THREAD

**Issue by machonam** [jitsi/jitsi-meet#4281]
Here's the error code..

error: The following binaries use incompatible versions of Swift:
/Users/<UserName>/Library/Developer/Xcode/DerivedData/"ProjectName"-ekwouwxuaxxafcgvcqkowizkdpyl/Build/Products/Debug-iphoneos/"ProjectName".app/Frameworks/JitsiMeet.framework/JitsiMeet

i've already disable bitcode....still can't handle this error...

Is there some steps i missed?

Here's my Podfile

platform :ios, '9.0'

def import_pods
  "other pods.."
  pod 'JitsiMeetSDK'
end

target "ProjectName"do

  use_frameworks!
  import_pods

  target "Extension" do
    inherit! :search_paths
  end

  target "Extension" do
    inherit! :search_paths
  end

end

**Comment by machonam** [comment]
And tried at blank project, this error occured.

ld: /Users/emotionwave/Documents/JitsiTest/Pods/JitsiMeetSDK/jitsi-meet-ios-sdk-releases-1.21.1/Frameworks/JitsiMeet.framework/JitsiMeet compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/Users/emotionwave/Documents/JitsiTest/Pods/JitsiMeetSDK/jitsi-meet-ios-sdk-releases-1.21.1/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

should i downgrade swift version??

**Comment by machonam** [comment]
And tried at blank project, this error occured.

ld: /Users/"UserName"/Documents/JitsiTest/Pods/JitsiMeetSDK/jitsi-meet-ios-sdk-releases-1.21.1/Frameworks/JitsiMeet.framework/JitsiMeet compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/Users/"UserName"/Documents/JitsiTest/Pods/JitsiMeetSDK/jitsi-meet-ios-sdk-releases-1.21.1/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

should i downgrade swift version??

**Comment by saghul** [comment]
What Xcode version are you using? What swift version on your project? Also, note the SDK doesn't support iOS 9.

**Comment by machonam** [comment]
Xcode version 10.2.1, Swift5, iOS version 12.2. All brand new..

idk why "# platform :ios, '9.0'" is specified at my Podfile..im just create podfile with "$pod init"at terminal. 

And also in Xcode, Deployment Target is 12.2

**Comment by saghul** [comment]
You can check our sample projects here: https://github.com/jitsi/jitsi-meet-sdk-samples maybe there is something you didn't set.

**Comment by machonam** [comment]
thx!

In fact.. i solved this with just replaced my pods-header with the frameworks header in sample
Still don't know why... but solved anyway.
