### ISSUE TITLE
only android 8.0，when i join the meeting，the sdk must be calling tell，why?

### ISSUE THREAD

**Issue by zhaozhilong001** [jitsi/jitsi-meet#4290]
only android 8.0，when i join the meeting，the sdk must be calling tell，why?

**Comment by zhaozhilong001** [comment]
i test the sdk,find that android 8.0 operate system,when i join the meeting,it making a call,how to fix the bug?

**Comment by zhaozhilong001** [comment]
When entering a meeting, it dials a strange number, and how to prevent it from dialing is only seen on android8.0.

**Comment by crazypaving** [comment]
same problem.how to fix?
