### ISSUE TITLE
[iOS] Conferences work on all devices except iPhone XS, XS Max, XR

### ISSUE THREAD

**Issue by svtagt** [jitsi/jitsi-meet#4295]
The problem is only on these three devices - iPhone XS, XS Max, XR. 
On all other physical devices (iPhone 5s, some devices on Android) on which I test - video conferences work fine.

After I go to the video conference screen, I immediately see that the conference terminated and see a black screen and this error:

Optional([AnyHashable("url"): https://media.doctorsmart.ru/2383#config.startWithVideoMuted=false, AnyHashable("error"): ])

And the most important - if I replace my Jitsi instance https://jitsi-prod.doctorsmart.ru with https://meet.jit.si, everything starts working normally on these iPhones (XS, XS Max, XR).

I understand that the problem is most likely on the my Jitsi server instance.
Please tell me what could be the problem.

**Comment by underthegui** [comment]
Having a similar issue. Not sure where to begin looking.

**Comment by underthegui** [comment]
Having a similar issue. Not sure where to begin looking.. did you end up figuring it out?
