### ISSUE TITLE
[iOS]xcodebuild failed!

### ISSUE THREAD

**Issue by Insfgg99x** [jitsi/jitsi-meet#4296]
error `fsevents` unavailable (this watcher can only be used on Darwin). Run CLI with --verbose flag for more details.
+ [[ false != true ]]
+ [[ ! -f /Users/fengge/Library/Developer/Xcode/DerivedData/jitsi-meet-dwwznoxjmugakkabqvajirdiewwp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/JitsiMeet.framework/main.jsbundle ]]
+ echo 'error: File /Users/fengge/Library/Developer/Xcode/DerivedData/jitsi-meet-dwwznoxjmugakkabqvajirdiewwp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/JitsiMeet.framework/main.jsbundle does not exist. This must be a bug with'
error: File /Users/fengge/Library/Developer/Xcode/DerivedData/jitsi-meet-dwwznoxjmugakkabqvajirdiewwp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/JitsiMeet.framework/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Package\ React\ bundle /Users/fengge/Library/Developer/Xcode/DerivedData/jitsi-meet-dwwznoxjmugakkabqvajirdiewwp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-0BCA49651EC4B77500B793EE.sh
(1 failure)

**Comment by Insfgg99x** [comment]
I fixed this issue with:
```
brew install watchman
cd /usr/local/var/run
sudo mkdir watchman
sudo chmod 042777 watchman

react-native bundle --entry-file ./index.ios.js --platform ios --bundle-output ios/main.jsbundle
```

and add the main.jsbundle to the Xcode project works for me.

**Comment by Shamsiddin** [comment]
what was the solution of this problem?

**Comment by Vantam1601** [comment]
what was the solution of this problem?
