### ISSUE TITLE
How to build rebuild my own SDK on iOS?

### ISSUE THREAD

**Issue by Insfgg99x** [jitsi/jitsi-meet#4297]
I change something in `Toolbox.js` for the purpose test rebuilding on iOS as follow:
![image](https://user-images.githubusercontent.com/12442442/58768622-c5383e00-85d0-11e9-8dfc-f4d90968c276.png)

`xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive`

I get the `JitsiMeet.framework` under ios/sdk:

![image](https://user-images.githubusercontent.com/12442442/58768672-848cf480-85d1-11e9-9878-0578f8a2605d.png)

I copy it into my project and run success, but it doesn't work! The button surposed to be heere In the conference UI.

![image](https://user-images.githubusercontent.com/12442442/58768844-8bb50200-85d3-11e9-8168-7dd871159bdc.png)

Would you point out the way to do it?

**Comment by Insfgg99x** [comment]
make and use xcbuild

**Comment by saghul** [comment]
Note that what you are ciopying is a symlink, you must copy the target of it. Also, how are you doing the integration? If you are using cocoapods, the od framework would override your own.

**Comment by Insfgg99x** [comment]
make and build

**Comment by mohdsafadsaal** [comment]
@Insfgg99x  @saghul  I made the changes in Toolbox.js and i rebuild the target and copied to framworks in my own xcode project. But changes are not reflection. Could you please guide me?

**Comment by albert0m** [comment]
did you manage to rebuild the sdk?
