### ISSUE TITLE
Make meeting scheduling clearer/easier

### ISSUE THREAD

**Issue by EricRoche** [jitsi/jitsi-meet#4317]
**Is your feature request related to a problem you are facing?**
I'm new to jitsi, and am finding it hard to understand how to set up a meeting ahead of time. The documentation isn't as clear as it could be, and I would like to know more before I connect my work account (Office 365) to the service. 

**Describe the solution you'd like**
I wish there was an option to create a link that would persist for some time (say two or three months) and then just copy-paste that link into my own meeting invites. A button that says "generate future meeting link" or something would be great.f Alternatively, better documentatioin on how to do this (if it's already possible) would suffice. 

**Describe alternatives you've considered**
I don't feel comfortable giving calendar access to jitsi and would like a manual way to schedule meetings in advance.

**Comment by damencho** [comment]
Please use the community forum for questions before opening new issues.

There is no such thing as creating a meeting in advance. The conference exists in the moment the first participant joins and is destroyed the moment the last one leaves. 
The calendar access is needed just to add an URL to an event, a thing you can do by yourself, by hand.

The only thing is that if you take your dial-in information it will be valid for a month after the last use of that URL, if you use it regularly, there is no problem. But if you enter today and after 40 days the dial in pin will be different.
