### ISSUE TITLE
iOS I try to run the application,but crash to JitsiMeet.framework

### ISSUE THREAD

**Issue by Johnny5826** [jitsi/jitsi-meet#4319]
![image](https://user-images.githubusercontent.com/17289530/59336900-0992af00-8d32-11e9-984f-dd81737cfb79.png)
please help me!

**Comment by Johnny5826** [comment]
I user Xcode10.2.1.
when i use 10.1 to run the application ,worked;then i use 10.2.1 to run the application is worked;
But I use derectly Xcode10.2.1 and the application is not worked,crash to JitsiMeet.framework

**Comment by saghul** [comment]
Did you build the SDK yourself or are you using our prebuilt artifacts? Are you using cocoapods?

**Comment by Johnny5826** [comment]
> Did you build the SDK yourself or are you using our prebuilt artifacts? Are you using cocoapods?

I am running our own project, but the JitsiMeet.framework is downloaded from GitHub.
I have not use cocoapods.

**Comment by saghul** [comment]
Where did you download it from?

**Comment by Johnny5826** [comment]
> Where did you download it from?

I downloaded from https://github.com/jitsi/jitsi-meet-ios-sdk-releases

**Comment by saghul** [comment]
If you downloaded the latest, it's built with Xcode 10.2 + Swift 5 enabled. Make sure you are using those too and that the framework is properly embedded in the project.

**Comment by Johnny5826** [comment]
> If you downloaded the latest, it's built with Xcode 10.2 + Swift 5 enabled. Make sure you are using those too and that the framework is properly embedded in the project.

Thank you for your help, I just learned that this library is packaged by others after modification. I am asking the person how to deal with it, thank you！
