### ISSUE TITLE
Android App no remote video stream, with LAN setup,  Let's Encrypt cert set properly.

### ISSUE THREAD

**Issue by ltzMaxwell** [jitsi/jitsi-meet#4325]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Deployment in LAN, using let's encrypt cert, modify hosts on my android device using an app called virtual hosts(don't have DNS server in LAN this moment) for test. Loading config using FQDN(not ip) works well on android browser。

But video not streaming in and out.

## Current behavior
Only local video visible, no remote stream on either android app or chrome.

What is wired that, when using two browser as clients(replace android app with browser) , It's working good, so does it mean the server side is all OK? and the problem must be with android app?

## Expected Behavior
Streaming works.

## Possible Solution
I found someone said that nat.64.jit.si should be modified in LAN, is it true?
#3210 (comment)

## Steps to reproduce
---

# Environment details
1、LAN
2、Let's encrypt ssl cert
3、modify hosts on android device for test, using an app: virtual host.
4、p2p disabled in config.js .

**Comment by saghul** [comment]
How do the URLs you are testing look like?

**Comment by ltzMaxwell** [comment]
like this : https://abc.def.myhost.com.cn

**Comment by ltzMaxwell** [comment]
Trace logs , found connection is interrupted.

Reproduce:
1. Start Android app first;
2. then enter conference in chrome.   

ps :  p2p is disabled in config.js, using jvb to relay.

![not working](https://user-images.githubusercontent.com/6007578/59420219-13ceaf00-8dff-11e9-9757-4a845247115b.png)

**Comment by saghul** [comment]
I have never tested in such environment, it's very hard to tell what could go wrong. How does your config.js file look like?

**Comment by ltzMaxwell** [comment]
Well , I just modify p2p and bosh configuration, it works good with chrome: 
![WX20190613-173305](https://user-images.githubusercontent.com/6007578/59421585-6b6e1a00-8e01-11e9-867c-5c45b56434b5.png)
![WX20190613-173235](https://user-images.githubusercontent.com/6007578/59421587-6b6e1a00-8e01-11e9-9eda-3d4fcdae31c4.png)

By the way ,what does  the log "interrupted " mean?
@saghul

**Comment by saghul** [comment]
> By the way ,what does the log "interrupted " mean?

It means the connection with a participant is not working.

Please send the entire config.js file.

**Comment by ltzMaxwell** [comment]
[config.txt](https://github.com/jitsi/jitsi-meet/files/3285266/config.txt)
This is the entire config file.

**Comment by saghul** [comment]
Can you try to use a full URL when joining? like `https://abc.def.myhost.com.cn/test123` ? I think the problem is that on mobile we'll take the `domain` of the `host` section and craft the URL like that, which would be incorrect.

**Comment by ltzMaxwell** [comment]
Still not working. I'm wondering  what caused  the connection interruption.

**Comment by ltzMaxwell** [comment]
Fixed after remove "virtual hosts" app , and use a DNS server instead.
