### ISSUE TITLE
Toolbar always shown when youtube video sharing is on.

### ISSUE THREAD

**Issue by netaskd** [jitsi/jitsi-meet#4326]
## Description
---
Toolbar is not hide when youtube video sharing is on.

## Current behavior
---
Toolbar is not hide

## Expected Behavior
---
Hide as when shows participant

## Possible Solution
---

## Steps to reproduce
---
1. Enter to a conference
2 Press share a Youtube video

# Environment details
---
jitsi-meet_3796

**Comment by virtuacoplenny** [comment]
The toolbar is always shown when a video is pinned. When the YouTube video is first displayed it's pinned by default. That at least explains the current behavior.

**Comment by netaskd** [comment]
> The toolbar is always shown when a video is pinned.

Which the reason this behavior? I mean, why we need toolbar while video is playing?

**Comment by virtuacoplenny** [comment]
Because I remembered incorrectly and was completely wrong about what I wrote. But making the toolbar display with YouTube video is intentional. I don't know why: https://github.com/jitsi/jitsi-meet/blob/master/modules/UI/shared_video/SharedVideo.js#L619.

**Comment by netaskd** [comment]
@virtuacoplenny 
I've commented out this line and tested. So, I guess, it is made for hide black line on the buttom when youtube video is played. But right black line is still remain. Please look at the screenshot:

![youtube_toolbar_hidden](https://user-images.githubusercontent.com/1027361/59777642-b387b380-92bd-11e9-98ef-63d6fb567880.png)

I don't have another guessing about why toolbar always is on.
But maybe the best solution will be to stretch video picture for filling all the workspace. In this case the black lines will go away and toolbar can be auto hidden, as this in normal mode when a participant is shown.

**Comment by netaskd** [comment]
It would be grate to have youtube sharing without toolbar.
