### ISSUE TITLE
MS calendar integration is broken since commit 97e0303

### ISSUE THREAD

**Issue by netaskd** [jitsi/jitsi-meet#4329]
## Description
---
Seems like ms calendar cannot be loaded since commit 97e0303

## Current behavior
---
Commit 35ffbe1 and earler works good.
Started from 97e0303 calendar is not loaded.

## Expected Behavior
---
Successfull authentication in ms calendar and showing calendar events

## Possible Solution
---

## Steps to reproduce
---
1. Build jitsi-meet from commit 97e0303
2. Press "Connect your calendar" -> "Sign in with Microsoft" -> auth in MS
3. Nothing happen. "Sign in with Microsoft" shown again, no events in calendar.

# Environment details
---
Win10, Chrome 74,75

**Comment by saghul** [comment]
Damn, that was me. I can repro with Google Calendaar too. Thanks for the report, I'll be working on a fix stat.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/4332 thanks again for the heads up @netaskd!
