### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [jitsi/jitsi-meet#4331]
**Objective**: Implement and Support i2p in Jitsi
**Description**: Explore the possibility of using Jitsi over i2p.
**Why?**: Many reasons, mainly for privacy and security but also to support decentralized communications. 

________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75486496-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75486496)](https://www.bountysource.com/issues/75486496-feature-support-i2p)

**Comment by saghul** [comment]
Interesting, I had never heard of i2p before. How do you envision Jitsi using i2p?

**Comment by scottprovost** [comment]
We are planning on using i2p so any help is appreciated.

**Comment by saghul** [comment]
Please drop by our community at https://community.jitsi.org to get the conversation started!
