### ISSUE TITLE
Start a new meeting only works when pressing enter to submit form

### ISSUE THREAD

**Issue by tmcgee123** [jitsi/jitsi-meet#4343]
## Description

When selecting a previously used room, the video chat does not render

---
![Screen Shot 2019-06-18 at 2 31 02 PM](https://user-images.githubusercontent.com/6415216/59713986-333a5300-91d6-11e9-9d83-2ea89a008cda.png)

## Current behavior

Upon selecting a previously used room, the screen flashes and starts to compile the video chat but errors out.

---

## Expected Behavior

Upon selecting a previously used room, the video chat should render successfully and start the conference.

---

## Possible Solution

Use the same function _onFormSubmit

---

## Steps to reproduce

1. Go to meet.jit.si
2. Select Recent
3. Select a recent video room
4. Observe console for errors and video chat finishes rendering

---

# Environment details

Meet.jit.si site

---

**Comment by saghul** [comment]
I could reproduce this. Thanks for the report!

**Comment by saghul** [comment]
We have fixed it in beta: https://beta.meet.jit.si a deployment to meet.jit.si should happen soon.

**Comment by tmcgee123** [comment]
Thanks!
