### ISSUE TITLE
docker-jitsi-meet JWT room restriction is not working 

### ISSUE THREAD

**Issue by omesta** [jitsi/jitsi-meet#4349]
https://community.jitsi.org/t/docker-jitsi-meet-jwt-support/18340/4

This mudule must be enabled: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_token_verification.lua when using JWT auth

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/f809afe7ed65332922f414bd1de9212e8aaa9039
