### ISSUE TITLE
[SECURITY] XSS in jitsi meet

### ISSUE THREAD

**Issue by qchn** [jitsi/jitsi-meet#4368]
## Description
XSS in jitsi meet

## Current behavior
On the main jitsi page when one of the criticalFiles (index.html Line 22) does not load an onerror handler inserts the current url into the page (index.html Line 96).

## Threat
An attacker in a man-in-the-middle position could send a manipulated link to a user and make one of the requests fail.
This way arbitrary code can be injected into jitsi.
The attacker could ask for a password (for example, when a single sign-on service is used) or yield other attacks.

## Possible Solution
The href should be properly escaped (note the html attribute context, the following characters need to be escaped '  " & < > ).

## Environment details
Latest jitsi version, we were using the "Manual Install" Documentation[1] to deploy it. 

[1] https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

**Comment by saghul** [comment]
Thanks a lot for the detailed report!

**Comment by virtuacoplenny** [comment]
A potential fix is in master. Based on my testing latest big browsers do a decent job of automatically escaping but older browsers are a problem.

**Comment by saghul** [comment]
How old?

**Comment by virtuacoplenny** [comment]
I didn't bother finding that out.

**Comment by saghul** [comment]
@qchn Hey Robert, do you think our solution is enough to close this?

**Comment by qchn** [comment]
@saghul Hi Saúl, yup, ok with me 👍

**Comment by saghul** [comment]
Thank you!
