### ISSUE TITLE
Error on iOS 13 Beta

### ISSUE THREAD

**Issue by Insfgg99x** [jitsi/jitsi-meet#4386]
it's black, and it doesn't show the video call interface on iOS 13 Beta.
![1111](https://user-images.githubusercontent.com/12442442/60315868-f838dc00-999a-11e9-9012-912c9be23544.PNG)

**Comment by saghul** [comment]
Based on the UI you have made changes to Jitsi Meet. Does the Jitsi Meet app in the store work properly?

**Comment by Insfgg99x** [comment]
Thanks for your reply. It works properly in the store.

**Comment by saghul** [comment]
Then it must be related to the changes you made, that's my only guess.

**Comment by Insfgg99x** [comment]
Hello, I may have made a mistake, It  does not work properly  on the Jitsi Meet app in the store. 
![image](https://user-images.githubusercontent.com/12442442/60409054-61fff280-9bf4-11e9-9aa9-d262bcb314c2.png)
![image](https://user-images.githubusercontent.com/12442442/60409060-66c4a680-9bf4-11e9-9b7c-f6603024abb7.png)
![image](https://user-images.githubusercontent.com/12442442/60409063-69270080-9bf4-11e9-9ee6-c2444bf1045f.png)

**Comment by melvin-huss** [comment]
I can confirm that my custom implementation using the SDK is not working on iOS13 same build works fine on iOS 12.

**Comment by saghul** [comment]
Thanks for the report! We'll take a look.

**Comment by jiawenbin2013** [comment]
@Insfgg99x how do you download the ios app?  I have the same porblem that can not download the app from app store

**Comment by Insfgg99x** [comment]
> @Insfgg99x how do you download the ios app? I have the same porblem that can not download the app from app store

You need a foreign Apple Store account

**Comment by ydawei** [comment]
Can confirm. I am using my own server with a valid certificate chain (can be validated here: https://whatsmychaincert.com/). Web browsers, the android app, and the iOS app on iOS stable are working properly, but not on iOS 13 beta 4.

My guess is it's related to iOS 13 certificate issue. The signal app on iOS 13 beta is also having such issues (see [reddit post](https://www.reddit.com/r/signal/comments/c2q6c6/anyone_using_signal_in_ios_13_beta_iphone/)) and can be solved by adding the root CA. I am currently trying to do the same thing but there is no luck.

**Comment by saghul** [comment]
@jiawenbin2013 @ydawei Please don't derail the issue.

**Comment by saghul** [comment]
@Insfgg99x I'm on beta 6 and do see video. I had a case of black video on WhatsApp too, just once though. I tested Jitsi Meet straight from the store.

**Comment by masterhaowu** [comment]
Same issue, the ios store version shows black screen on iOS 13

**Comment by saghul** [comment]
@masterhaowu What beta version are you running? Does mute / unmute "fix" it for you? Do you see it happening with other apps?

**Comment by pcarlsym** [comment]
I also see black screen on local and remote video on Jitsi Meet App Store version. iOS Beta 13.1. Restart or mute/unmute does not help.

**Comment by saghul** [comment]
Thanks for the update. Come to think of it, I’ve been checking with our latest beta, not the store version, my mistake.

I’ll see if I can share it.

**Comment by mikeelston** [comment]
I am experiencing the same issue.  iOS 13.1 Beta 2.
Jitsi Version 19.2.0 build 23

**Comment by saghul** [comment]
An update is now available on the App Store fixing this problem.
