### ISSUE TITLE
How to use my own jitsi server for both web and mobile app?

### ISSUE THREAD

**Issue by geniussoft2019** [jitsi/jitsi-meet#4387]
Hi,
I follow the steps in this link to run the jitsi-meet web application :

https://github.com/jitsi/jitsi-meet

and it works succussfully
also i follow this link to run the jitsi-meet mobile app:

https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md

and it works succussfully on device .
Now i want to change the default server domain in order to use my own jitsi server for both web and mobile app ,
I try changing the domain in the projects file config.js but it doesn’t work?

So how can i change to my own server ?any idea please ? thanks

**Comment by damencho** [comment]
Please do not open issues for just questions.

**Comment by KindYAK** [comment]
@geniussoft2019 I am facing the same problem. Did you come up with any solution? Thank you
