### ISSUE TITLE
npm install -> extract:ua-parser-js

### ISSUE THREAD

**Issue by jiawenbin2013** [jitsi/jitsi-meet#4400]
node version 12.40
npm version 6.9.0
yarn version 1.16.0

when i enter  jitsi-meet and npm install，always show 'extract:ua-parser-js: sill extract github:amplitude/ua-'；I have waiting for hours, how resolve the problem?

**Comment by saghul** [comment]
Likely a network issue. Nothing we can do on the project side I'm afraid.

**Comment by jiawenbin2013** [comment]
how can i download the ios app?
from app store? No，i can not find the app from app store;
any other ways?
@saghul

**Comment by saghul** [comment]
We use CallKit, and alas that means we cannot make it available in the AppStore on China. You can get it with an account from another region. Alternatively, you can build it yourself, but AFAIS you are running into issues too, not sure there is anything I can do to help though.

**Comment by jiawenbin2013** [comment]
@saghul thanks a lot

**Comment by liuzy1993** [comment]
How did you solve it?always show 'extract:ua-parser-js: sill extract github:amplitude/ua-'
