### ISSUE TITLE
pod install -> ERROR | attributes: Missing required attribute `summary`

### ISSUE THREAD

**Issue by jiawenbin2013** [jitsi/jitsi-meet#4405]
pod --version:1.7.3

When i do pod install,the follow error happen：
Fetching podspec for `RNWatch` from `../node_modules/react-native-watch-connectivity`
[!] The `RNWatch` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `summary`.

Tips：I use yarn, is not npm install;

**Comment by jiawenbin2013** [comment]
I have resloved myself;

**Comment by saghul** [comment]
I cannot reproduce this.

**Comment by jiawenbin2013** [comment]
@saghul I have build iOS app successful，but how change local ip to my service domain，becase i have run the service successful。

**Comment by saghul** [comment]
You can click the "hamburger menu" button and change the default server to yours.

**Comment by jiawenbin2013** [comment]
![image](https://user-images.githubusercontent.com/5269568/60647107-861b3800-9e6f-11e9-961b-8f4b40ee4451.png)

@saghul

**Comment by jiawenbin2013** [comment]
![image](https://user-images.githubusercontent.com/5269568/60647380-2c673d80-9e70-11e9-90cd-512a3a69ed65.png)
@saghul

**Comment by jookovjook** [comment]
Solved the original error by upgrading `react-native-watch-connectivity` to `0.3.1`:
```
yarn upgrade react-native-watch-connectivity@0.3.1
```
then renamed `RNWatch` to `react-native-watch-connectivity` in `Podfile`:
```
...
pod 'react-native-watch-connectivity', :path => '../node_modules/react-native-watch-connectivity
...
```
The error has gone, but I didn't test features related to this package
