### ISSUE TITLE
jitsi video is not working when auth mode is token

### ISSUE THREAD

**Issue by jits009** [jitsi/jitsi-meet#4406]
Hi 

When enable token auth mode then video call stops working. Can you please help me out. 

I get this error in console

![image](https://user-images.githubusercontent.com/25115041/60645724-20bb4d00-9e57-11e9-9a43-6d0e14469d30.png)

**Comment by saghul** [comment]
Looks like your XMPP server is giving an error. The BOSH endpoint is returning a 504. Check your prosody logs.

**Comment by jits009** [comment]
Hi @saghul 

Here are the logs I am getting in prosody 

![image](https://user-images.githubusercontent.com/25115041/60646866-02a31c00-9e5a-11e9-8935-9050b2dff4ff.png)

**Comment by saghul** [comment]
There you have it, the configured authentication mode (token, I suppose) is not found. Have you installed the token auth modules?

**Comment by jits009** [comment]
Yes I did I have I followed this documentation for installing

https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

**Comment by saghul** [comment]
Veruify that the plugin path is set correctly and that the right files are there. Prosody is not detecting them.

**Comment by jits009** [comment]
Here is the path I have in domain.confi.lua file 

![image](https://user-images.githubusercontent.com/25115041/60651063-07b89900-9e63-11e9-93b2-5f9228b7af56.png)

**Comment by saghul** [comment]
what files do you have in there?

**Comment by jits009** [comment]
Here are the files

![image](https://user-images.githubusercontent.com/25115041/60652595-2ec49a00-9e66-11e9-8ba7-78ea36676b82.png)

**Comment by jits009** [comment]
In browser I am getting this error 

http://domain.com/http-bind?room="xyx"  504 Gateway timeout when auth mode is token. Its working when auth mode is anonymous

**Comment by saghul** [comment]
@damencho any ideas?

**Comment by damencho** [comment]
yep, error on startup, when starting prosody ...

**Comment by jits009** [comment]
@saghul @damencho 

Can you please help me resolving this

**Comment by saghul** [comment]
paste full prosody logs

**Comment by jits009** [comment]
Jul 04 10:39:39 general info    Hello and welcome to Prosody version trunk nightly build 747 (2017-02-19, 428d4abee723)
Jul 04 10:39:39 general info    Prosody is using the select backend for connection handling
Jul 04 10:39:39 portmanager     info    Activated service 's2s' on [::]:5269, [*]:5269
Jul 04 10:39:39 portmanager     info    Activated service 'c2s' on [::]:5222, [*]:5222
Jul 04 10:39:39 portmanager     info    Activated service 'legacy_ssl' on no ports
Jul 04 10:39:39 mod_posix       info    Prosody is about to detach from the console, disabling further console output
Jul 04 10:39:39 mod_posix       info    Successfully daemonized to PID 16415
Jul 04 10:39:39 portmanager     info    Activated service 'component' on [127.0.0.1]:5347, [::1]:5347
Jul 04 10:39:39 modulemanager   error   Error initializing module 'auth_token' on '13.232.213.195': /usr/lib/prosody/../../bin/prosody:185: module 'luajwtjitsi' not found:No LuaRocks module found for luajwtjitsi
        no field package.preload['luajwtjitsi']
        no file '/usr/lib/prosody/luajwtjitsi.lua'
        no file '/usr/local/share/lua/5.1/luajwtjitsi.lua'
        no file '/usr/local/share/lua/5.1/luajwtjitsi/init.lua'
        no file '/usr/local/lib/lua/5.1/luajwtjitsi.lua'
        no file '/usr/local/lib/lua/5.1/luajwtjitsi/init.lua'
        no file '/usr/share/lua/5.1/luajwtjitsi.lua'
        no file '/usr/share/lua/5.1/luajwtjitsi/init.lua'
        no file '/var/lib/prosody/.luarocks/share/lua/5.1/luajwtjitsi.lua'
        no file '/var/lib/prosody/.luarocks/share/lua/5.1/luajwtjitsi/init.lua'
        no file '/usr/lib/prosody/luajwtjitsi.so'
        no file '/usr/local/lib/lua/5.1/luajwtjitsi.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/luajwtjitsi.so'
        no file '/usr/lib/lua/5.1/luajwtjitsi.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/var/lib/prosody/.luarocks/lib/lua/5.1/luajwtjitsi.so'
stack traceback:
        /usr/lib/prosody/core/modulemanager.lua:31: in function </usr/lib/prosody/core/modulemanager.lua:31>
        [C]: in function '_real_require'
        /usr/lib/prosody/../../bin/prosody:185: in function 'require'
        .../share/jitsi-meet/prosody-plugins/token/util.lib.lua:7: in main chunk
        (tail call): ?
        .../share/jitsi-meet/prosody-plugins/mod_auth_token.lua:8: in main chunk
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/prosody/core/modulemanager.lua:31: in function 'pcall'
        /usr/lib/prosody/core/modulemanager.lua:176: in function 'do_load_module'
        /usr/lib/prosody/core/modulemanager.lua:254: in function 'load'
        /usr/lib/prosody/core/usermanager.lua:66: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/core/hostmanager.lua:104: in function 'activate'
        /usr/lib/prosody/core/hostmanager.lua:57: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/../../bin/prosody:354: in function 'prepare_to_start'
        /usr/lib/prosody/../../bin/prosody:423: in main chunk
        [C]: ?
Jul 04 10:39:39 portmanager     info    Activated service 'http' on [::]:5280, [*]:5280
Jul 04 10:39:39 certmanager     error   SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Check that the permissions allow Prosody to read this file. (for https port 5281)
Jul 04 10:39:39 portmanager     error   Error binding encrypted port for https: error loading private key (Permission denied)
Jul 04 10:39:39 certmanager     error   SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Previous error (see logs), or other system error. (for https port 5281)
Jul 04 10:39:39 portmanager     error   Error binding encrypted port for https: error loading private key (system lib)
Jul 04 10:39:39 portmanager     info    Activated service 'https' on no ports
Jul 04 10:39:39 certmanager     error   SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Check that the permissions allow Prosody to read this file. (for localhost)
Jul 04 10:39:39 localhost:tls   error   Error creating context for c2s: error loading private key (Permission denied)
Jul 04 10:39:39 certmanager     error   SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Previous error (see logs), or other system error. (for localhost)
Jul 04 10:39:39 localhost:tls   error   Error creating contexts for s2sout: error loading private key (system lib)
Jul 04 10:39:39 certmanager     error   SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key': Previous error (see logs), or other system error. (for localhost)
Jul 04 10:39:39 localhost:tls   error   Error creating contexts for s2sin: error loading private key (system lib)
Jul 04 10:39:39 modulemanager   error   Error initializing module 'token_verification' on 'conference.13.232.213.195': /usr/lib/prosody/../../bin/prosody:185: module 'luajwtjitsi' not found:No LuaRocks module found for luajwtjitsi
        no field package.preload['luajwtjitsi']
        no file '/usr/lib/prosody/luajwtjitsi.lua'
        no file '/usr/local/share/lua/5.1/luajwtjitsi.lua'
        no file '/usr/local/share/lua/5.1/luajwtjitsi/init.lua'
        no file '/usr/local/lib/lua/5.1/luajwtjitsi.lua'
        no file '/usr/local/lib/lua/5.1/luajwtjitsi/init.lua'
        no file '/usr/share/lua/5.1/luajwtjitsi.lua'
        no file '/usr/share/lua/5.1/luajwtjitsi/init.lua'
        no file '/var/lib/prosody/.luarocks/share/lua/5.1/luajwtjitsi.lua'
        no file '/var/lib/prosody/.luarocks/share/lua/5.1/luajwtjitsi/init.lua'
        no file '/usr/lib/prosody/luajwtjitsi.so'
        no file '/usr/local/lib/lua/5.1/luajwtjitsi.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/luajwtjitsi.so'
        no file '/usr/lib/lua/5.1/luajwtjitsi.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/var/lib/prosody/.luarocks/lib/lua/5.1/luajwtjitsi.so'
stack traceback:
        /usr/lib/prosody/core/modulemanager.lua:31: in function </usr/lib/prosody/core/modulemanager.lua:31>
        [C]: in function '_real_require'
        /usr/lib/prosody/../../bin/prosody:185: in function 'require'
        .../share/jitsi-meet/prosody-plugins/token/util.lib.lua:7: in main chunk
        (tail call): ?
        ...itsi-meet/prosody-plugins/mod_token_verification.lua:24: in main chunk
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/prosody/core/modulemanager.lua:31: in function 'pcall'
        /usr/lib/prosody/core/modulemanager.lua:176: in function 'do_load_module'
        /usr/lib/prosody/core/modulemanager.lua:254: in function 'load'
        /usr/lib/prosody/core/modulemanager.lua:76: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/core/hostmanager.lua:104: in function 'activate'
        /usr/lib/prosody/core/hostmanager.lua:57: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/../../bin/prosody:354: in function 'prepare_to_start'
        /usr/lib/prosody/../../bin/prosody:423: in main chunk
        [C]: ?
Jul 04 10:39:44 c2s56414d41efe0 info    Client connected
Jul 04 10:39:44 c2s56414d41efe0 info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Jul 04 10:39:44 c2s56414d41efe0 info    Authenticated as focus@auth.13.232.213.195
Jul 04 10:39:44 jitsi-videobridge.13.232.213.195:component      warn    Component not connected, bouncing error for: <iq id='7Xhw1-3472' type='get' to='jitsi-videobridge.13.232.213.195' from='focus@auth.13.232.213.195/focus11427316918415'>
Jul 04 10:39:44 focus.13.232.213.195:component  warn    Component not connected, bouncing error for: <iq id='7Xhw1-3476' type='get' to='focus.13.232.213.195' from='focus@auth.13.232.213.195/focus11427316918415'>
Jul 04 10:39:46 jcp56414d404910 info    Incoming Jabber component connection
Jul 04 10:39:46 focus.13.232.213.195:component  info    External component successfully authenticated
Jul 04 10:39:57 jcp56414d4b25d0 info    Incoming Jabber component connection
Jul 04 10:39:57 jitsi-videobridge.13.232.213.195:component      info    External component successfully authenticated

**Comment by damencho** [comment]
What is the output if you execute: `luarocks install luajwtjitsi` ? 
Which prosody version do you have?

**Comment by jits009** [comment]
After Executing luarocks install luajwtjitsi command getting this error 

`root@ip-172-31-11-15:~# luarocks install luajwtjitsi
Installing https://luarocks.org/luajwtjitsi-1.3-7.rockspec
Missing dependencies for luajwtjitsi 1.3-7:
   luacrypto >= 0.3.2-1 (not installed)
   lua-cjson >= 2.1.0 (not installed)
   lbase64 >= 20120807-3 (not installed)

luajwtjitsi 1.3-7 depends on luacrypto >= 0.3.2-1 (not installed)
Installing https://luarocks.org/luacrypto-0.3.2-2.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/lcrypto.c -o src/lcrypto.o -I/usr/inc                                                                                                             lude
src/lcrypto.c: In function ‘digest_pnew’:
src/lcrypto.c:81:61: error: invalid application of ‘sizeof’ to incomplete type                                                                                                               EVP_MD_CTX {aka struct evp_md_ctx_st}’
     EVP_MD_CTX *c = (EVP_MD_CTX *)lua_newuserdata(L, sizeof(EVP_MD_CTX));
                                                             ^~~~~~~~~~
src/lcrypto.c: In function ‘digest_reset’:
src/lcrypto.c:120:10: warning: implicit declaration of function ‘EVP_MD_CTX_clea                                                                                                             nup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
     if (!EVP_MD_CTX_cleanup(c))
          ^~~~~~~~~~~~~~~~~~
          EVP_MD_CTX_create
src/lcrypto.c: In function ‘encrypt_pnew’:
src/lcrypto.c:331:69: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
     EVP_CIPHER_CTX *c = (EVP_CIPHER_CTX *)lua_newuserdata(L, sizeof(EVP_CIPHER_                                                                                                             CTX));
                                                                     ^~~~~~~~~~~                                                                                                             ~~~
src/lcrypto.c: In function ‘encrypt_fencrypt’:
src/lcrypto.c:425:20: error: storage size of ‘c’ isn’t known
     EVP_CIPHER_CTX c;
                    ^
src/lcrypto.c: In function ‘decrypt_pnew’:
src/lcrypto.c:470:69: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
     EVP_CIPHER_CTX *c = (EVP_CIPHER_CTX *)lua_newuserdata(L, sizeof(EVP_CIPHER_                                                                                                             CTX));
                                                                     ^~~~~~~~~~~                                                                                                             ~~~
src/lcrypto.c: In function ‘decrypt_fdecrypt’:
src/lcrypto.c:561:20: error: storage size of ‘c’ isn’t known
     EVP_CIPHER_CTX c;
                    ^
src/lcrypto.c: In function ‘hmac_pnew’:
src/lcrypto.c:604:57: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘HMAC_CTX {aka struct hmac_ctx_st}’
     HMAC_CTX *c = (HMAC_CTX *)lua_newuserdata(L, sizeof(HMAC_CTX));
                                                         ^~~~~~~~
src/lcrypto.c: In function ‘hmac_fnew’:
src/lcrypto.c:621:5: warning: implicit declaration of function ‘HMAC_CTX_init’;                                                                                                              did you mean ‘HMAC_CTX_new’? [-Wimplicit-function-declaration]
     HMAC_CTX_init(c);
     ^~~~~~~~~~~~~
     HMAC_CTX_new
src/lcrypto.c: In function ‘hmac_clone’:
src/lcrypto.c:631:5: error: dereferencing pointer to incomplete type ‘HMAC_CTX {                                                                                                             aka struct hmac_ctx_st}’
     *d = *c;
     ^~
src/lcrypto.c: In function ‘hmac_gc’:
src/lcrypto.c:697:5: warning: implicit declaration of function ‘HMAC_CTX_cleanu                                                                                                              ’; did you mean ‘HMAC_CTX_get_md’? [-Wimplicit-function-declaration]
     HMAC_CTX_cleanup(c);
     ^~~~~~~~~~~~~~~~
     HMAC_CTX_get_md
src/lcrypto.c: In function ‘hmac_fdigest’:
src/lcrypto.c:711:14: error: storage size of ‘c’ isn’t known
     HMAC_CTX c;
              ^
src/lcrypto.c: In function ‘sign_pnew’:
src/lcrypto.c:747:61: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
     EVP_MD_CTX *c = (EVP_MD_CTX *)lua_newuserdata(L, sizeof(EVP_MD_CTX));
                                                             ^~~~~~~~~~
src/lcrypto.c: In function ‘sign_fsign’:
src/lcrypto.c:828:20: error: storage size of ‘c’ isn’t known
         EVP_MD_CTX c;
                    ^
src/lcrypto.c: In function ‘verify_pnew’:
src/lcrypto.c:857:61: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
     EVP_MD_CTX *c = (EVP_MD_CTX *)lua_newuserdata(L, sizeof(EVP_MD_CTX));
                                                             ^~~~~~~~~~
src/lcrypto.c: In function ‘verify_fverify’:
src/lcrypto.c:940:20: error: storage size of ‘c’ isn’t known
         EVP_MD_CTX c;
                    ^
src/lcrypto.c: In function ‘rand_pseudo_bytes’:
src/lcrypto.c:992:5: warning: ‘RAND_pseudo_bytes’ is deprecated [-Wdeprecated-de                                                                                                             clarations]
     return rand_do_bytes(L, RAND_pseudo_bytes);
     ^~~~~~
In file included from /usr/include/openssl/e_os2.h:13:0,
                 from /usr/include/openssl/err.h:13,
                 from src/lcrypto.c:7:
/usr/include/openssl/rand.h:44:1: note: declared here
 DEPRECATEDIN_1_1_0(int RAND_pseudo_bytes(unsigned char *buf, int num))
 ^
src/lcrypto.c: In function ‘pkey_generate’:
src/lcrypto.c:1064:9: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-de                                                                                                             clarations]
         RSA *rsa = RSA_generate_key(key_len, RSA_F4, NULL, NULL);
         ^~~
In file included from /usr/include/openssl/e_os2.h:13:0,
                 from /usr/include/openssl/err.h:13,
                 from src/lcrypto.c:7:
/usr/include/openssl/rsa.h:234:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
src/lcrypto.c:1074:9: warning: ‘DSA_generate_parameters’ is deprecated [-Wdeprec                                                                                                             ated-declarations]
         DSA *dsa = DSA_generate_parameters(key_len, NULL, 0, NULL, NULL, NULL,                                                                                                              NULL);
         ^~~
In file included from /usr/include/openssl/e_os2.h:13:0,
                 from /usr/include/openssl/err.h:13,
                 from src/lcrypto.c:7:
/usr/include/openssl/dsa.h:117:1: note: declared here
 DEPRECATEDIN_0_9_8(DSA *DSA_generate_parameters(int bits,
 ^
src/lcrypto.c: In function ‘pkey_to_pem’:
src/lcrypto.c:1164:27: error: dereferencing pointer to incomplete type ‘struct e                                                                                                             vp_pkey_st’
     if (private && pkey_st->type == EVP_PKEY_DSA)
                           ^~
src/lcrypto.c: In function ‘pkey_tostring’:
src/lcrypto.c:1277:60: error: dereferencing pointer to incomplete type ‘EVP_PKEY                                                                                                              {aka struct evp_pkey_st}’
     sprintf(buf, "%s %s %d %p", LUACRYPTO_PKEYNAME, (*pkey)->type == EVP_PKEY_D                                                                                                             SA ? "DSA" : "RSA", EVP_PKEY_bits(*pkey), pkey);
                                                            ^~
src/lcrypto.c: In function ‘seal_pnew’:
src/lcrypto.c:1299:46: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
     c->ctx = (EVP_CIPHER_CTX *)malloc(sizeof(EVP_CIPHER_CTX));
                                              ^~~~~~~~~~~~~~
In file included from src/lcrypto.c:8:0:
src/lcrypto.c: In function ‘seal_tostring’:
src/lcrypto.c:1320:81: error: dereferencing pointer to incomplete type ‘EVP_CIPH                                                                                                             ER_CTX {aka struct evp_cipher_ctx_st}’
 s, "%s %p %s", LUACRYPTO_SEALNAME, (void *)c, EVP_CIPHER_name(c->ctx->cipher));
                                                                     ^
src/lcrypto.c: In function ‘seal_fseal’:
src/lcrypto.c:1400:20: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX ctx;
                    ^~~
src/lcrypto.c: In function ‘open_pnew’:
src/lcrypto.c:1483:46: error: invalid application of ‘sizeof’ to incomplete type                                                                                                              ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
     c->ctx = (EVP_CIPHER_CTX *)malloc(sizeof(EVP_CIPHER_CTX));
                                              ^~~~~~~~~~~~~~
src/lcrypto.c: In function ‘open_fopen’:
src/lcrypto.c:1602:20: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX ctx;
                    ^~~

Error: Failed installing dependency: https://luarocks.org/luacrypto-0.3.2-2.src.                                                                                                             rock - Build error: Failed compiling object src/lcrypto.o
`

**Comment by jits009** [comment]
I am using prosody Prosody trunk nightly build 747

**Comment by damencho** [comment]
What is the OS and version you use? Not sure why that fails maybe because of the newer openssl and laucrypto does not support it ... just guessing

**Comment by jits009** [comment]
I am using 

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by damencho** [comment]
I suggest to try 18.04 there it is tested to work fine, anyway 16.04 is 5 years old ...

**Comment by jits009** [comment]
Finally it worked I have installed on ubuntu 18.04 

Thank you for help

**Comment by jits009** [comment]
Even after passing jwt token its giving throwing this error

![image](https://user-images.githubusercontent.com/25115041/60666751-6727a080-9e85-11e9-8c76-904b7d603a00.png)

**Comment by saghul** [comment]
Looks like to toke is not valid. Any chance it's expired? Also check the prosody logs.

**Comment by jits009** [comment]
I token I am using is this 
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiYXZhdGFyIjoiaHR0cHM6L2dyYXZhdGFyLmNvbS9hdmF0YXIvaml0ZW5kcmFAZ21haWwuY29tIiwibmFtZSI6IkppdGVuZHJhIiwiZW1haWwiOiJqaXRlbmRyYUBnbWFpbC5jb20iLCJpZCI6ImFiY2Q6YTFiMmMzLWQ0ZTVmNi0wYWJjMS0yM2RlLWFiY2RlZjAxZmVkY2JhIn0sImdyb3VwIjoiYTEyMy0xMjMtNDU2LTc4OSJ9LCJhdWQiOiJmYiIsImlzcyI6ImZiIiwic3ViIjoiaml0c2kiLCJyb29tIjoiKiIsImlhdCI6MTU2MjI0MzAzNCwiZXhwIjoxNTYyMzI5NDM0fQ.Z7SjVThRGgBTkMO6yk4jeWwfxtbwMpvPcBRqghzBMCI`

In prosody logs I am getting this 

![image](https://user-images.githubusercontent.com/25115041/60668931-bcb27c00-9e8a-11e9-8144-1869c63ffce3.png)

**Comment by saghul** [comment]
Looks like the token is not being recognized as such. What kind of URL are you using?

**Comment by jits009** [comment]
Here is the URL 

`https://jitsi-staging.funnelbake.com/UnseenKidsComputeAppallingly?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiYXZhdGFyIjoiaHR0cHM6L2dyYXZhdGFyLmNvbS9hdmF0YXIvaml0ZW5kcmFAZ21haWwuY29tIiwibmFtZSI6IkppdGVuZHJhIiwiZW1haWwiOiJqaXRlbmRyYUBnbWFpbC5jb20iLCJpZCI6ImFiY2Q6YTFiMmMzLWQ0ZTVmNi0wYWJjMS0yM2RlLWFiY2RlZjAxZmVkY2JhIn0sImdyb3VwIjoiYTEyMy0xMjMtNDU2LTc4OSJ9LCJhdWQiOiJmYiIsImlzcyI6ImZiIiwic3ViIjoiaml0c2ktc3RhZ2luZy5mdW5uZWxiYWtlLmNvbSIsInJvb20iOiIqIiwiaWF0IjoxNTYyMjQzMDM0LCJleHAiOjE1NjIzMjk0MzR9.ZikibSL9oTjOjy9wNVaRG6Jy1YIV-sBkTakq61wb5BY`

**Comment by saghul** [comment]
Isn't it expired already?

**Comment by jits009** [comment]
I am using this payload in jwt is right ?

`{
  "context": {
    "user": {
      "avatar": "https:/gravatar.com/avatar/abc123",
      "name": "John Doe",
      "email": "jdoe@example.com",
      "id": "abcd:a1b2c3-d4e5f6-0abc1-23de-abcdef01fedcba"
    },
    "group": "a123-123-456-789"
  },
  "aud": "jitsi",
  "iss": "my_client",
  "sub": "meet.jit.si",
  "room": "*"
}`

**Comment by damencho** [comment]
This token I think is for url https://domain/a123-123-456-789/roomname
Just remove the group part. The error why token is not valid, should be printed in prosody logs

**Comment by jits009** [comment]
In logs I am getting this error  /var/log/prosody/prosody.log

` Error verifying token err:not-allowed, reason:token required`

**Comment by jits009** [comment]
I changed jwt payload to this 

`
    {
        "context": {
            "user": {
                "avatar": "https:/gravatar.com/avatar/jitendra@gmail.com",
                "name": "Jitendra",
                "email": "jitendra@gmail.com"
            }
        },
        "sub": "jitsi-staging.domain.com",
        "iss": "fb",
        "aud": "jitsi",
        "room": "*"
    }
`

**Comment by webintoit** [comment]
Prosody need to be patched to respect the token. Default `BOSH` do not allows us to get query params during authentication. Please modify mod.bosh.lua and emits `bosh-session` event required by  https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_auth_token.lua#L21

**Comment by damencho** [comment]
@webintoit bosh-session is already fired in prosody-trunk 747.

**Comment by damencho** [comment]
@jits009 is your prosody config like, based on the token you use: 
app_id = "fb"
asap_accepted_audiences = { "jitsi" }

**Comment by webintoit** [comment]
> @webintoit bosh-session is already fired in prosody-trunk 747.
It is for BOSH. Not for web socket yet. 
We are facing issue with token absence here, it should be related to this.

**Comment by jits009** [comment]
> @jits009 is your prosody config like, based on the token you use:
> app_id = "fb"
> asap_accepted_audiences = { "jitsi" }

prosody config have this 2 lines

**Comment by damencho** [comment]
@webintoit https://github.com/jitsi/lib-jitsi-meet/pull/907 still not merged, will do soon

**Comment by jits009** [comment]
Still Its not working @damencho

**Comment by damencho** [comment]
How are you passing the token adding a parameter jwt=... in the browser?
https://mydmain.com/someroomname?jwt=<token_string>

**Comment by jits009** [comment]
Here is example 

`https://jitsi-staging.funnelbake.com/UnseenKidsComputeAppallingly?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiYXZhdGFyIjoiaHR0cHM6L2dyYXZhdGFyLmNvbS9hdmF0YXIvaml0ZW5kcmFAZ21haWwuY29tIiwibmFtZSI6IkppdGVuZHJhIiwiZW1haWwiOiJqaXRlbmRyYUBnbWFpbC5jb20ifX0sInN1YiI6ImppdHNpLXN0YWdpbmcuZnVubmVsYmFrZS5jb20iLCJpc3MiOiJmYiIsImF1ZCI6ImppdHNpIiwicm9vbSI6IioiLCJpYXQiOjE1NjIzMTkxNzcsImV4cCI6MTU2MjQwNTU3N30.8SGaj80ObcWG5fvjo5tJ8qho2eq7nZp3JNZxiQu4VKU`

**Comment by webintoit** [comment]
Looks like your proxy server  (Nginx ? ) does not forward query string parameters. Can you check this ?

**Comment by jits009** [comment]
Hi @webintoit 

I am have installed jitsi quick installation method. Where can i find nginx setting ? Normally it's available in `/etc/nginx` but it's not there

**Comment by jits009** [comment]
I tried this method and it worked 

`https://github.com/jitsi/jitsi-meet/pull/3907/commits/471674b127a247db17ead210bd28cb41d761268e`

But its breaking giving this error 

![image](https://user-images.githubusercontent.com/25115041/60788913-6cce0080-a17b-11e9-82a1-eae80e6832e8.png)

**Comment by damencho** [comment]
What is the error you see in js console?

**Comment by jits009** [comment]
Here are the errors

`Jul 08 08:52:32 c2s5592682b23c0 error   Traceback[c2s]: /usr/lib/prosody/util/cache.lua:66: table index is nil
stack traceback:
        /usr/lib/prosody/util/cache.lua:66: in function 'set'
        /usr/lib/prosody/modules/muc/mod_muc.lua:176: in function 'track_room'
        /usr/lib/prosody/modules/muc/mod_muc.lua:204: in function </usr/lib/prosody/modules/muc/mod_muc.lua:191>
        (tail call): ?
        /usr/lib/prosody/modules/muc/mod_muc.lua:433: in function '?'
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (tail call): ?
        /usr/lib/prosody/core/stanza_router.lua:180: in function 'core_post_stanza'
        /usr/lib/prosody/core/stanza_router.lua:127: in function 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:282: in function 'func'
        /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
Jul 08 08:52:34 c2s5592682b23c0 error   Traceback[c2s]: /usr/lib/prosody/util/cache.lua:66: table index is nil
`

**Comment by damencho** [comment]
These errors are from prosody.
You need to change a prosody config based on the prosody version you use:
# if the version is 0.10.X (>0.10 and <0.11)
storage = "none"
# for >0.11
storage = "memory"

This is normally detected on install time, detects prosody version and fixes that.
https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-prosody.postinst#L128

**Comment by jits009** [comment]
Thank you so much @damencho  

It worked !!  :)
