### ISSUE TITLE
A computer has multiple cameras displaying simultaneously

### ISSUE THREAD

**Issue by zsinba** [jitsi/jitsi-meet#4412]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
My computer has two cameras, one that talks to me and the other that demonstrates my work.I wanted to use two cameras at once, not just one.
**Describe the solution you'd like**
Please describe the desired behavior.
Used as a scene when multiple cameras are used simultaneously.
**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Opening a TAB page on the web can open multiple cameras, but that's not what I wanted or was convenient to use.

**Comment by damencho** [comment]
Not sure about multiple cameras, but we are looking forward to adding probably simultanouusly camera and desktop sharing.
The desired behavior you can easily achieve by joining the same meeting twice, the second time you join you need to use the following url format in order to avoid hearing twice:
https://meet.jit.si/mymeeting#config.startSilent=true

**Comment by zsinba** [comment]
First of all, Thank you for your reply.
Yes, I have found that it is possible to join the meeting twice so that multiple cameras can be used simultaneously. You're talking about using both cameras and desktop sharing, which is part of the same desired. 
Is there any specific development plan for using desktop sharing and camera at the same time?
Which version can be released, or is it feasible?

Thank you again. 
It's a great project.

**Comment by zsinba** [comment]
I made some attempts to use both the camera and desktop sharing, and it worked. I tried using BBB's system for desktop sharing and camera use at the same time. This is a screenshot
![image](https://user-images.githubusercontent.com/890157/60803210-4cb73500-a1ad-11e9-9502-271be0eb4775.png)

**Comment by damencho** [comment]
> Is there any specific development plan for using desktop sharing and camera at the same time?
> Which version can be released, or is it feasible?

No ETA at the moment, but probably later this year or the beginning of next. But nothing, in particular, we had just mentioned it a few times.

**Comment by PanderMusubi** [comment]
With the current global work from home situation, can this issue please get reopened?

Not only for camera + desktop bit also for camera1 + camera2. Preferably the middle of both video streams side by side in landscape view client side and on top of each other in portrait view client side.

**Comment by martinseip** [comment]
This can be done using OBS (Open Broadcast Software) and its addon Virtual cam. I use 3 webcams as sources, arrange their location and size on the screen. This layout is combined by OBS to one single output "camera" which is available in jitsi meet as any usual camera.

**Comment by jhonatanpiffer** [comment]
Hi, @damencho I really need this feature for my project and my intention now is to develop this feature of using 3 webcams simultaneously.
Can you help me with some directions? 
Can I use only lib-jitsi-meet to achieve this or I need to customize JVB too?

**Comment by damencho** [comment]
Probably you can achieve this by using the lib, like entering multiple times in the conference with different local settings ... Otherwise the whole arch, around jicofo, jvb and lib-jitsi-meet are one video and one audio stream per participant.

**Comment by samopus1io** [comment]
Hi jhonatanpiffer we implemented multi camera support with picture in picture / and custom layout for a commercial project. We will contribute it eventually but we cant at the moment. 

We can talk about it If you are interested, or at the very least we can give you some pointers.

https://www.reddit.com/r/jitsi/comments/i371gm/multi_camera_support_in_jitsi_meetings/

**Comment by jhonatanpiffer** [comment]
> Hi jhonatanpiffer we implemented multi camera support with picture in picture / and custom layout for a commercial project. We will contribute it eventually but we cant at the moment.
> 
> We can talk about it If you are interested, or at the very least we can give you some pointers.
> 
> https://www.reddit.com/r/jitsi/comments/i371gm/multi_camera_support_in_jitsi_meetings/

Amazing to know this. Thanks in advance.

**Comment by jhonatanpiffer** [comment]
> Probably you can achieve this by using the lib, like entering multiple times in the conference with different local settings ... Otherwise the whole arch, around jicofo, jvb and lib-jitsi-meet are one video and one audio stream per participant.

Thanks @damencho for your answer. Entering some times in a room does not supply my needs for this project. I will need the whole arch.

**Comment by jpelkonen** [comment]
> Hi jhonatanpiffer we implemented multi camera support with picture in picture / and custom layout for a commercial project. We will contribute it eventually but we cant at the moment.
> 
> We can talk about it If you are interested, or at the very least we can give you some pointers.
> 
> https://www.reddit.com/r/jitsi/comments/i371gm/multi_camera_support_in_jitsi_meetings/

Hi @samopus1io, this looks very nice. Can you give even a rough timeline when will you contribute this feature?

**Comment by eglipeter** [comment]
Another usecase for two-camera support would be that we would like to use an HDMI video grabber. By that, Jitsi can serve as an easy-to-use room system where the presenter simply connects his computer via HDMI for sharing the display content to the "local audience" and the remote audience. So it would be great if the second camera can also be set as the source for the "screen sharing content".

**Comment by minhhd-works** [comment]
> > Probably you can achieve this by using the lib, like entering multiple times in the conference with different local settings ... Otherwise the whole arch, around jicofo, jvb and lib-jitsi-meet are one video and one audio stream per participant.
> 
> Thanks @damencho for your answer. Entering some times in a room does not supply my needs for this project. I will need the whole arch.

Have you implemented this feature successfully yet?
