### ISSUE TITLE
[iOS] Application not found

### ISSUE THREAD

**Issue by pstrive** [jitsi/jitsi-meet#4414]
Hi, I have installed a jitsi-meet server and it is running normally on the web. But i couldidn't find an IOS Application works on IPhone. The link, http://jitsi.org/ios, on the https://jitsi.org/downloads/ returned 404, where can i get the package work on IPhone, thanks a lot.

**Comment by damencho** [comment]
Use the community forum for questions and oroblem before opening new issues.

Try the app store on your phone.
