### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by joelihn** [jitsi/jitsi-meet#4415]
I want  access the camera trough Applciation A but at the same time record the stream as well with Applciation B.

So i split the video from /dev/video0 to two virtual webcam devices. I used the v4l2loopback and ffmpeg to archieve this. 

But when i refresh the web page, hints "Failed to access your camera"...

In the Setting Tab Camera display "Permission not granded".

If a do not split the video, everything is fine.

I want to know is there something i should to do to make that work.

Thanks in advanced.

**Comment by damencho** [comment]
Please, use the community forum when you have questions and problems before opening new issues.

Have you tried does it work with other apps, check for example https://appr.tc.
