### ISSUE TITLE
jitsi videobridge package missing

### ISSUE THREAD

**Issue by MidnightTanny** [jitsi/jitsi-meet#4424]
pi@raspberrypi:~ $ sudo apt-get -y install jitsi-meet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-videobridge (= 1116-1) but it is not installable
              Depends: jicofo (= 1.0-468-1) but it is not installable
E: Unable to correct problems, you have held broken packages.

pi@raspberrypi:~ $ sudo apt-get -y install jitsi-videobridge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package jitsi-videobridge is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'jitsi-videobridge' has no installation candidate

**Comment by MidnightTanny** [comment]
Please fix your repository!

**Comment by damencho** [comment]
We support only i386 and amd64 packages, arm is not supported.
For the system to operate normally we recommend 8GB of RAM, probably you don't have this available on a raspberry pi.

**Comment by damencho** [comment]
Please, use the community forum for questions and problems before opening new issues, thanks.
