### ISSUE TITLE
[Android] Switch Camera Bug on Phone with Multiple Rear Cameras

### ISSUE THREAD

**Issue by zhenghow93** [jitsi/jitsi-meet#4436]
## Description
Toggling camera does not work as intended, instead of showing front and back camera in an alternating manner, multiple rear views are shown upon toggling the camera. This happened in Huawei Mate 20 Pro and Huawei P30 Pro. The app is built from this repo (git cloned the repo when sdk version is 2.1.0) with minor customisation to the UI, that's why some of the menu are hidden. But the exact same behaviour can be observed by using the latest Jitsi Meet app downloaded from Google Playstore as well. Hence, this problem exists in the latest version as well.

## Current behavior
Please refer to this video: https://youtu.be/0vjKFrSSiwI
The camera view is toggled in such manner: front, back, back, back, back, front, back...
It started with the front view, then 4 times of back view.

## Expected Behavior
Local camera view should toggle between front and back, in the front, back, front, back... sequence.

## Possible Solution
Not sure though. Helpppp...

## Hypothesis/Findings
I believe the main cause is in the jitsiTrack._switchCamera(); called upon toggling the camera. (react/features/base/tracks/middleware.js)
Huawei Mate 20 Pro and P30 Pro have 3 rear cameras and 1 front camera.
Hence, we deduced that by toggling the camera, _switchCamera() actually goes through all 3 rear cameras and probably one combined-rear-camera-mode. That's why you see 4 rears views when you toggle the camera.
However, we tested on Nokia 7 Plus (Android Pie) and some other phones with only 2 rear cameras, they are working well.

## Steps to reproduce
1. Run Jitsi Meet app
2. Enter any room name, and join
3. Tap on the overlay menu button on the bottom right, choose "Toggle camera"
4. Repeat step 3 for four times at least

# Environment details
OS version: Android Pie (9.0)
EMUI: 9.0
Phone Model: Huawei P30 Pro, Huawei Mate 20 Pro
react-native-webrtc version: jitsi/react-native-webrtc#659d2fe417b52356b1b706636de97e23bae3e9f5

**Comment by zhenghow93** [comment]
[UPDATE] Huawei P20 Pro which has 3 rear cameras does not have similar behaviour.
EMUI version: 9.0.0
Android version: Pie (9.0)

**Comment by saghul** [comment]
Thanks for the report! This is indeed a knwon issue. FTR, it has to do with how WebRTC implements this method in the Android side of things (ie, it cycles through them, doesn't switch).

**Comment by zhenghow93** [comment]
@saghul Thanks for the speedy reply! Any workaround that we can try for the moment?

**Comment by saghul** [comment]
Nope, sorry.

**Comment by zhenghow93** [comment]
Alright, thanks for the speedy reply.

Anyway, we just tested with a few more phones.
Vivo V5 (1819) has 3 rear cams and 1 front cam, it's working well.
However, Samsung Galaxy Note 9 (1 front cam, 2 rear cams) has a rather weird behaviour, it toggles in front, back, front, front, back, front, front, back.. manner.

Just leave it here for your record. Hope this helps the webrtc sdk team. Thank you.

**Comment by saghul** [comment]
Thanks a lot @zhenghow93, this really helps!

**Comment by saghul** [comment]
@zhenghow93 this is now fixed in master. Any chance you can build it yourself and give it a try?

**Comment by zhenghow93** [comment]
@saghul thank you very much for your help. Although it's a bit slow upon changing to the rear camera, but it's working great now!
Million thanks! =]

**Comment by saghul** [comment]
> Although it's a bit slow upon changing to the rear camera

Yeah, that's due to the need to internally switch multiple times. I've reported this upstream to hopefully get a better API which would avoid this, so it may improve over time.

Thanks for testing it out!

**Comment by zhenghow93** [comment]
Understood that. Thank you very much!

**Comment by monet-hs** [comment]
@saghul Hello,

I wonder if this fix is committed in react-native-webrtc git. 
I'm using the latest react-native-webrtc version (1.75.3), the same issue happened.
When I switch a camera 2 times more during webrtc call on Android Note 10 Plus, the app crashed.

Please give some advice.

BR,
monet
