### ISSUE TITLE
El stream cayo de la nada

### ISSUE THREAD

**Issue by lucaspazmundial** [jitsi/jitsi-meet#4442]
Estaba estrimeando en directo y a las 2 horas se cayo de la nada.

**Comment by saghul** [comment]
Cual era el nombre de la conferencia?

@bbaldino Do we have a limit on jibri sessions?

**Comment by bbaldino** [comment]
so there is a limit on session time on meet.jit.si, but there's currently a bug in how it's done (Jibri expects the number to be in minutes, but it's provided in seconds) so the limit is quite large right now.  we'll be fixing it soon, and when it's fixed i expect the limit to be 2 hours (which is what was intended).  it's eerie that this is stopping at 2 hours,  but it may be something else causing it to stop. if we had a call name we could investigate more.

**Comment by lucaspazmundial** [comment]
Si el directo se cayo a las 2 hrs aprox

**Comment by saghul** [comment]
@lucaspazmundial Cual era el nombre de la sala? (para que intentemos averiguar porque, mirando los logs).

**Comment by lucaspazmundial** [comment]
fue por el limite de timpo que deberian ampliar y dejarlo liberado sin
limite como hace obs.

**Comment by saghul** [comment]
No. Lo que Brian ha dicho es que hay un limite de 2h pero estaba mal configurado, por lo que deberias de haber podido usar mas de 2h.

En cualquier caso, no vamos a ofrecer mas de 2h continuas de streaming en meet.jit.si.

**Comment by lucaspazmundial** [comment]
Ahora que se cayo hangout seria bueno que intentaran hacerlo.
