### ISSUE TITLE
www: Missing closing parenthesis on website

### ISSUE THREAD

**Issue by Zarthus** [jitsi/jitsi-meet#4444]
I couldn't find the web repo to PR it, so I guess I'll just file it here:

In the header "Jitsi Meet is packed with premium features." there is a text
"Keeps conversations private
with encryption by default (and advanced security settings"

It opens the (, but never closes it.

![img](https://liefland.net/~zarthus/image/chrome_ProtestantsLosers.png)

Thanks!

**Comment by damencho** [comment]
Fixed, thanks.
