### ISSUE TITLE
Jitsi Meet and WebRTC M69 / React-Native-WebRTC-1.69.2

### ISSUE THREAD

**Issue by sparmar-atheer** [jitsi/jitsi-meet#4447]
Which is the release / tag in Jitsi-meet repository that matches WebRTC M69 version?

**Comment by saghul** [comment]
Hi there! I assume by matches you mean it includes it. The 19.2 version does indeed use M69, here you can find links to the tags: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-APPS.md

The master branch (what will become 19.3) has been updated to M75 already.

Hope that helps, cheers!
