### ISSUE TITLE
TRACK_MUTE_CHANGED event not getting triggered for remote video tracks on lib-jitsi-meet

### ISSUE THREAD

**Issue by seanmheff** [jitsi/jitsi-meet#445]
It looks like the "videomuted" handler in RTC.js is expecting a full jid, but is receiving a resource instead. This is causing the TRACK_MUTE_CHANGED event not to fire for remote tracks.

![screen shot 2016-01-04 at 11 12 53 am](https://cloud.githubusercontent.com/assets/2361700/12089003/23ddfdf2-b2d8-11e5-8a18-4a18e92fbf22.png)

**Comment by hristoterezov** [comment]
Fixed in the latest version. Thank you for the report!
