### ISSUE TITLE
The name of the participant to the small box in the video interface!

### ISSUE THREAD

**Issue by Johnny5826** [jitsi/jitsi-meet#4459]
I want to add the name of the participant to the small box in the video interface. What should I do?Please help me,Thx!

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

If you set your name locally by going to settings profile or by just clicking in the middle of your local video and setting it, the rest of the participants in the meeting will see it.

**Comment by Johnny5826** [comment]
> Please use the community forum for questions and problems before opening new issues.
> 
> If you set your name locally by going to settings profile or by just clicking in the middle of your local video and setting it, the rest of the participants in the meeting will see it.

Please give me an accurate location, allowing me to display the username in the preview video box! thx!
