### ISSUE TITLE
Create my own SDK

### ISSUE THREAD

**Issue by phucnd0604** [jitsi/jitsi-meet#4463]
Im trying to create my own SDK but when i build a framework the Terminal hangs at "info Done copying assets"
![Screen Shot 2019-07-19 at 2 16 56 PM](https://user-images.githubusercontent.com/6973483/61516968-543dd000-aa30-11e9-8cd7-c980342f0031.png)

**Comment by saghul** [comment]
Hi there! What steps are you following (exactly) and what versions of Node and Xcode are you using?

**Comment by phucnd0604** [comment]
First, i follow this guide and get the project run successfully,
https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md
Then i use this command to build my own framework
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive
i use node v12.6.0, Xcode 10.2.1

**Comment by saghul** [comment]
That sounds about right. I have vague memories of someone running into problems with Node 12 but not with Node 10, can you give that a try? (we build the SDKs with Node 10 ourselves).

**Comment by saghul** [comment]
Is there a reason why you are building it yourself? Using CocoaPods is much easier. You must have not added the framework properly on Xcode.

**Comment by phucnd0604** [comment]
i need to custom UI of conference screen, Please help

**Comment by saghul** [comment]
How exactly are you adding the framework?

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by maneesh12345** [comment]
No such module 'JitsiMeet'
using xcode 11.4

**Comment by sunilkumarjena21** [comment]
Hi @saghul ,
Thanks you for the awesome SDK.
I followed the guide to create my own SDK.
[https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk](http://)

Just one small query.
Can I rename the below dependency as my own library name.

implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }

Wanted to update it like this:- 
implementation ('org.example.react:example-meet-sdk:+') { transitive = true }

Would be great if you can let us know the steps for the same.
Thanks in advance!

**Comment by ytam** [comment]
> No such module 'JitsiMeet'
> using xcode 11.3

import JitsiMeetSDK instead of JitsiMeet

**Comment by BadriBarmaja** [comment]
> JitsiMeetSDK

<module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/JitsiMeetSDK.h"
