### ISSUE TITLE
jvb uses 100% CPU after a while

### ISSUE THREAD

**Issue by commander0815** [jitsi/jitsi-meet#4464]
Hello,
we are facing a wired problem, the jvb service on our jitsi server starts to use 100% CPU after a while. We suspect it is happening after one of our teams is using it for a meeting. Hope the logfiles are enough to help. The problem startet around 12 o'clock

[jvb.log](https://github.com/jitsi/jitsi-meet/files/3410706/jvb.log)

**Comment by damencho** [comment]
@commander0815 Are you able to reproduce it every time? I have one suspicion, can you try adding this `org.jitsi.videobridge.DISABLE_TCP_HARVESTER=true` to videobridge settings and see whether that fixes it.

Please use the community forum for questions and problems before opening new issues. Thanks.

**Comment by saschaludwig** [comment]
We almost have the same problem on our fresh install. Aproximately 20 minutes after a conference has been made two java processes go wild and use 100% CPU. Any solution that helped @commander0815 would be appreciated if posted here too. Thank you :)

**Comment by damencho** [comment]
@saschaludwig have you tested my proposal, does it change anything?

**Comment by crystech** [comment]
I am having same issue on fresh installed on ubuntu 18.04. I will try the proposed settings as well

**Comment by crystech** [comment]
@damencho 
I followed your suggestion and it seem now jitsi meet no longer freeze and jvb no longer 100%
What’s the impact by disabling harvesting?

**Comment by damencho** [comment]
This is tcp harvester. In some restricted corporate networks udp is not allowed and a tcp connection is attempted. But some times even this is not enough in those networks, as it needs to be on port 443 and to looks like real https connection, which is not the case when using the bridge for that. That is the reason we are using coturn for the tcp connections for meet.jit.si, anyway coturn is used for the p2p connections to offload the bridge.

**Comment by umataro** [comment]
what is this crazy style of 'wontfix' ticket closing when issues are not fixed or even addressed?
