### ISSUE TITLE
Cannot run android error:

### ISSUE THREAD

**Issue by kunsubin96** [jitsi/jitsi-meet#4467]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runDebugReactPackager'.
> A problem occurred starting process 'command 'scripts/run-packager.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 41s
201 actionable tasks: 178 executed, 23 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

**Comment by saghul** [comment]
Have you installed all npm dependencies? Do you have adb in your path?

**Comment by kunsubin96** [comment]
I'm installed, but error: A problem occurred starting process 'command 'scripts/run-packager.sh', use windows 10 OS

**Comment by saghul** [comment]
Ah, that. Sorry, we don't support Windows for building the Jitsi Meet app.

**Comment by niutech** [comment]
@saghul That's very disappointing. You didn't state it in the README that the Jitsi Meet Android app cannot be built in Windows 10. I wasted hours trying to build it under Windows and I stuck on this error. Could you please make building process cross-platform?

**Comment by saghul** [comment]
Sorry about that, I'll get that added to the README.



> Could you please make building process cross-platform?

Not really, sorry. We don't develop on Windows, so we can't provide support for a platform we don't use. It would just keep breaking and we'd be giving our users the false message that we support it.

**Comment by ArsalImam** [comment]
@niutech I am doing development on windows 10 by using `WSL` from the past 8 months. you can give it a try till now, I didn't found any limitation on it

**Comment by chagai95** [comment]
> @niutech I am doing development on windows 10 by using `WSL` from the past 8 months. you can give it a try till now, I didn't found any limitation on it

how did you set it up without using GUI? Could you get in touch with me? I would deeply appreciate that, have spent two days trying to get that to work and I could not figure it out! here are my contact details: www.chagaifriedlander.cf

**Comment by chagai95** [comment]
> @niutech I am doing development on windows 10 by using `WSL` from the past 8 months. you can give it a try till now, I didn't found any limitation on it

I tried that and it didn't work for me, what distribution are you using? I would really appreciate you helping me getting this to work, spent two days already trying things...

**Comment by deva-gopalani** [comment]
> > @niutech I am doing development on windows 10 by using `WSL` from the past 8 months. you can give it a try till now, I didn't found any limitation on it
> 
> how did you set it up without using GUI? Could you get in touch with me? I would deeply appreciate that, have spent two days trying to get that to work and I could not figure it out! here are my contact details: [www.chagaifriedlander.cf](http://www.chagaifriedlander.cf)

Hey did you get the solution? If yes then please post it here! Thanks in advance!

**Comment by gongweiqiang** [comment]
> > > @niutech I am doing development on windows 10 by using `WSL` from the past 8 months. you can give it a try till now, I didn't found any limitation on it
> > 
> > 
> > how did you set it up without using GUI? Could you get in touch with me? I would deeply appreciate that, have spent two days trying to get that to work and I could not figure it out! here are my contact details: [www.chagaifriedlander.cf](http://www.chagaifriedlander.cf)
> 
> Hey did you get the solution? If yes then please post it here! Thanks in advance!

1.Create a file named "run-packager.bat" in current floder with the following content:
set RCT_METRO_PORT=8081
adb reverse tcp:%RCT_METRO_PORT% tcp:%RCT_METRO_PORT%
2.Replace commandLine("scripts/run-packager.sh") with commandLine("scripts/run-packager.bat") in build.gradle(/android/app/build.gradle，line 160);
3.try react-native run-android command again;

**Comment by dochathuc** [comment]
> > > > @niutech I am doing development on windows 10 by using `WSL` from the past 8 months. you can give it a try till now, I didn't found any limitation on it
> > > 
> > > 
> > > how did you set it up without using GUI? Could you get in touch with me? I would deeply appreciate that, have spent two days trying to get that to work and I could not figure it out! here are my contact details: [www.chagaifriedlander.cf](http://www.chagaifriedlander.cf)
> > 
> > 
> > Hey did you get the solution? If yes then please post it here! Thanks in advance!
> 
> 1.Create a file named "run-packager.bat" in current floder with the following content:
> set RCT_METRO_PORT=8081
> adb reverse tcp:%RCT_METRO_PORT% tcp:%RCT_METRO_PORT%
> 2.Replace commandLine("scripts/run-packager.sh") with commandLine("scripts/run-packager.bat") in build.gradle(/android/app/build.gradle，line 160);
> 3.try react-native run-android command again;

Thanks. This solution works perfectly. Just wanted to echo on it.
Replace commandLine("scripts/run-packager.sh") in build.gradle(/android/app/build.gradle)
To:
`
                if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                    commandLine("scripts/run-packager.bat")
                } else {
                    commandLine("scripts/run-packager.sh")
                }
`

**Comment by Nallamala-Satish** [comment]
your system problem

**Comment by harsha-ziroh** [comment]
i am developing for react-native mobile android from my win11, I am not able to run in my android emulator or device, if you can throw some light regarding this that would be very helpful.

**Comment by saghul** [comment]
We don't develop on Windows, sorry. Looks like someone found a solution here: https://github.com/jitsi/jitsi-meet/issues/4467#issuecomment-699599656

**Comment by harsha-ziroh** [comment]
after changing the configuration as  @niutech mentioned above still i am not able to run, is this version match might be blocking to build??


  ext {
    buildToolsVersion = "31.0.0"
    compileSdkVersion = 32
    minSdkVersion    = 23
    targetSdkVersion = 32
    supportLibVersion = "28.0.0"



coz m getting error for this line

**Comment by tu-nv** [comment]
For someone who use WSL2, there are additional steps need to be done. Since the WSL2 network is considered public to the window, you need to establish traffic route 127.0.0.1:8081 (for metro) to WSL2 by running this in powershell:
```
iex "netsh interface portproxy add v4tov4 listenport=8081 listenaddress=127.0.0.1 connectport=8081 connectaddress=<WSL_IP>"
```
where WSL_IP can get from inside WSL2 with "ip a" or "ifconfig".

and inside WSL2, serve bundle for public IPs:
```
npx react-native start --host 0.0.0.0
```

Then you can deploy app from android studio. If you also want to deploy app with `npx react-native run-android` then it requires more steps. [Reference](https://gist.github.com/bergmannjg/461958db03c6ae41a66d264ae6504ade).

**Comment by SanjaySargam** [comment]
@saghul Does it supports on Linux?

**Comment by saghul** [comment]
Yes.

**Comment by gayatriii0803** [comment]
Still getting same issue in Linux also
