### ISSUE TITLE
Debian Repository

### ISSUE THREAD

**Issue by heutger** [jitsi/jitsi-meet#447]
The quick installation instructions state to use the nightly repository. Is there also a stable repository with less updates (how is the update policy to this repository then)?

**Comment by damencho** [comment]
Please forward your questions to the dev mailing list. 
There is a stable repository which wasn't updated recently and we should update it at some point. Still no strict policy for that.

**Comment by heutger** [comment]
I already wrote the question to the mailing list some time ago but without response.
