### ISSUE TITLE
JitsiMeetConferenceOptionsBuilder setting local user info

### ISSUE THREAD

**Issue by civilordergone** [jitsi/jitsi-meet#4474]
Hi, I am trying to set the local user info while using the JWT token for authentication.  In the file it says if I set userInfo then it'll be used in absence of a token:

/**
 * Information about the local user. It will be used in absence of a token.
 */
@property (nonatomic, nullable) JitsiMeetUserInfo *userInfo;

I have initialized a `JitsiMeetUserInfo` with the `JitsiMeetConferenceOptions` builder but it doesn't get reflected when I take a look at the store w/ the all the participants.  The name/email aren't updated.

**Comment by saghul** [comment]
What do you mean by “the store”? Can you paste the snippet of how you’re actually using it?

**Comment by civilordergone** [comment]
```
        let token = jwtToken?.token
        let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.welcomePageEnabled = false
            builder.serverURL = URL.init(string: "https://jitsi-meet.stag.vowel.ai")
            builder.room = self.room
            builder.token = token!
            builder.audioOnly = true
        }
        
        jitsiMeetView.join(options)
```
I'm just initializing the room like the above.  How do I set the username/email?

**Comment by saghul** [comment]
```
        let info = JitsiMeetUserInfo()
        info.displayName = "Alice"
        info.email = "alice@atlanta.com"
        let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.welcomePageEnabled = true
            builder.userInfo = info
        }
        jitsiMeetView.join(options)
```

**Comment by civilordergone** [comment]
Passing **JitsiMeetUserInfo** to **userInfo** doesn't work.  The user still pops up as "Fellow Jitser", what do you advise?

**Comment by saghul** [comment]
Aare you passing a token?

**Comment by civilordergone** [comment]
Yeah

**Comment by saghul** [comment]
As the documentation clearly states: "Information about the local user. It will be used in absence of a token." aka, if you pass a token then userInfo is not taken into account.

**Comment by Maheshhastree123kashyap** [comment]
without token also not working
