### ISSUE TITLE
set displayname on smallvideo

### ISSUE THREAD

**Issue by Johnny5826** [jitsi/jitsi-meet#4478]
![image](https://user-images.githubusercontent.com/17289530/61853200-e3922a00-aeed-11e9-96ad-997f728188db.png)
![image](https://user-images.githubusercontent.com/17289530/61853358-4e436580-aeee-11e9-98c1-a38c422874c2.png)

I want to set the name of the person who shows the meeting. Please tell me how to set it up? Which file is it specific? Thank you！

**Comment by saghul** [comment]
You were already told in https://github.com/jitsi/jitsi-meet/issues/4459 to post in the community forum, we use the tracker for issues and feature requests.
