### ISSUE TITLE
ICE (Video/Audio) failed over NAT

### ISSUE THREAD

**Issue by tlionheart** [jitsi/jitsi-meet#4485]
Hi guys,

i installed an own jitsi meet server (stable version 2.10.5550 / ubuntu 18.04.2 LTS) in my private environment. My network is separated into three subnets for LAN, WLAN and DMZ by a firewall. I put the jitsi server into my DMZ and configured the required port forwarding (TCP 443 / UDP 10000). The jitsi meet server is addressed via a nginx reverse-proxy. Nginx forwards the https request to jitsi. The UDP forwarding goes straight to the jitsi meet server.

As recommended in the FAQ i put the two lines for NAT in the /etc/jitsi/videobridge/sip-communicator.properties. 

`org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=192.168.5.249
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=24.129.63.25`

[https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration](url)

P2P mode is disabled in config.

Inside this network everything works fine. I can do jitsi meetings between two or more participations in my LAN and WLAN without any problems. In wireshark and firewall logs i see the traffic flows correctly over TCP443 and UDP10000. 

As soon as anyone from the internet join a meeting, i only see a black screen. There is no video or audio available. In the chrome console is see some warnings like this:
`Logger.js:125 [modules/xmpp/JingleSessionPC.js] <A.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed P2P? false:	 26383.319999999912
Logger.js:125 [modules/connectivity/IceFailedNotification.js] <>:  ICE connection restored - not sending ICE failed`
In my logs i only see the https-traffic but no UDP packets. 

I tested my UDP port-forwarding from another ubuntu server in the cloud via netcat. All tests are fine. This shoud not be the reason. 

So why do an external Browser use no UDP? Do you have any suggestions why no udp connection could be established?  

Plese help me to solve it .

**Comment by geniussoft2019** [comment]
Hi @tlionheart  try adding these lines to /etc/jitsi/videobridge/sip-communicator.properties : 

org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=192.168.5.249 

org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=24.129.63.25

org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=stun.l.google.com:19302 ,stun1.l.google.com:19302 ,stun2.l.google.com:19302

then do : 
 /etc/init.d/jitsi-videobridge restart
and make . then test again 

it works for me .
