### ISSUE TITLE
Jitsi Meet Installed on 3rd party UBUNTU invite audio participant failed to add participant

### ISSUE THREAD

**Issue by mattstolarczyk12** [jitsi/jitsi-meet#4487]
ON Jitsi Meeting URL page - start a meeting - click on "+" to invite people, enter valid phone number, click on Invite, then pop-up error message window is display - Failed to add participants - I am running Jitsi on 3rd party UBUNTU server.

**Comment by damencho** [comment]
For questions and problems use the community forum.

Have you installed and configured jigasi. Check jicofo and jigasi logs when this happens.
