### ISSUE TITLE
Проблема с отключением записи!!!!!!!!!

### ISSUE THREAD

**Issue by Natali-K1527** [jitsi/jitsi-meet#4501]
Добрый день!
Почему, когда в вашем сервисе я нажимаю "Завершить запись", она не отключается на Ютубе?
Там написано: Запись приостановлена. 
Как мне ее отключить?!

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues and please write in English as this is an English speaking community. Thanks.
