### ISSUE TITLE
APP_NAME in permission page

### ISSUE THREAD

**Issue by rajapulau** [jitsi/jitsi-meet#4512]
I think this is a bug. I was set my interfaceConfigOverwrite

## Description
```
interfaceConfigOverwrite: {
      TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'hangup'
       ],
      APP_NAME: 'My Application',
      NATIVE_APP_NAME: 'My Application',
      PROVIDER_NAME: 'My Application'
 }
```
Sorry if I wrong to create this ticket

## Current behavior
My permission paget still **Jitsi Meet needs to use your microphone and camera**

## Expected Behavior
**My Application needs to use your microphone and camera**

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Have you tried it on meet.jit.si, it was fixed recently?
https://community.jitsi.org/t/jitsi-meet-needs-to-use-your-microphone-and-camera/19136/6
https://github.com/jitsi/jitsi-meet/commit/6ddd17c76976a00d40832cba7158d95067af6e36

**Comment by rajapulau** [comment]
has it been updated https://meet.jit.si/external_api.js ?

**Comment by damencho** [comment]
Packages in unstable are updated, we will soon update and those in stable.
