### ISSUE TITLE
[Web] The code in the chat is not displayed correctly

### ISSUE THREAD

**Issue by lyabs243** [jitsi/jitsi-meet#4515]
Description
---
In the chat when you send the code as text, it is not displayed correctly.
The code should be displayed correctly without being encoded, this can be useful in a discussion between programmers.

## Current behavior
---
&lt;?php<br/>$menu = $menubar-&gt;getHomeMenu();

## Expected Behavior
---
```
<?php
$menu = $menubar->getHomeMenu();
```

## Steps to reproduce
---
Sends a message containing tags in the chat 
Ex: `<?php echo'Hello'; ?>`
# Environment details
---
Jitsi Meet on web.

**Comment by saghul** [comment]
We'll revisit this in https://github.com/jitsi/jitsi-meet/pull/8741
