### ISSUE TITLE
[Web] language detector does not work properly

### ISSUE THREAD

**Issue by poying** [jitsi/jitsi-meet#4516]
## Description

jitsi-meet use some invalid language codes (`zhCN`, `zhTW`, `frCA`) which can't be recognized by language detector.

## Current behavior

When `LANG_DETECTION` flag is set to `true`, jitsi-meet displayed language is not user preferred language.

## Expected Behavior

jitsi-meet should use user preferred language.

## Possible Solution

This is my workaround.

```javascript
/* eslint-disable require-jsdoc */
import I18nextBrowserLanguageDetector from 'i18next-browser-languagedetector';

export default class BrowserLanguageDetector extends I18nextBrowserLanguageDetector {
    addDetector(detector) {
        const lookup = detector.lookup.bind(detector);

        detector.lookup = options => {
            let found = lookup(options);

            if (typeof found === 'string') {
                found = found.replace(/-/, '');
            } else if (found) {
                found = found.map(lang => lang.replace(/-/, ''));
            }

            return found;
        };
        super.addDetector(detector);
    }
}
```

## Steps to reproduce

1. change your browser language settings to Traditional Chinese
2. clear localStorage
3. reload the page

# Environment details
---

**Comment by saghul** [comment]
ping @damencho

**Comment by poying** [comment]
@saghul Is there any update on this issue?

**Comment by saghul** [comment]
Not yet sorry, I’ll try to look into it the upcoming week.
