### ISSUE TITLE
Video streams freezing or not going through in Firefox

### ISSUE THREAD

**Issue by bekand** [jitsi/jitsi-meet#4520]
## Description
Possibly related to #4461 . When using latest Firefox, the video stream of the participants sometimes freezes or fails to load. I'm able to reproduce this issue both locally, and on meet.jit.si, bot not consistently.

## Steps to reproduce
Connect to a meet.jit.si room using latest Firefox browsers. At the initial connection, or after refreshing one of the browser windows, the video stream sometimes freeze, or fail to load (Participant Nr.1 detects Participant Nr.2's camera as disabled, or vice versa).

# Environment details
Windows 10, Firefox 68.0.1

**Comment by l0b0** [comment]
I can reproduce on Firefox 70.0.1 on Linux. Not reproducible on Chromium 77.0.3865.75 (also on Linux).

**Comment by prongzz** [comment]
Do we have update on this? Does Jitsi Meet new release have Firefox related fixes ?

**Comment by saghul** [comment]
Please open a new issue. This one is too old to be relevant.
