### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by kunsubin96** [jitsi/jitsi-meet#4527]
E/ReactNativeJS: '[__filename]', '<l>: ', 'Failed to load config from https://room.surelrn.vn/config.js?room=d', { [TypeError: Network request failed] line: 142, column: 2655, sourceURL: 'index.android.bundle' }
E/unknown:ReactNative: console.error: "[__filename]", "<l>: ", "Failed to load config from https://room.surelrn.vn/config.js?room=d", {"line":142,"column":2655,"sourceURL":"index.android.bundle"}, stack:
                       <unknown>@379:2405
                       <unknown>@-1
                       l@614:840
                       l@-1
                       <unknown>@973:1093
                       f@116:155
                       <unknown>@116:882
                       y@121:657
                       C@121:1021
                       callImmediates@121:3216
                       callImmediates@-1
                       value@42:2873
                       <unknown>@42:1264
                       value@42:2565
                       value@42:1234
                       value@-1
                       value@-1
![Uploading df.PNG…]()

**Comment by saghul** [comment]
The app is trying to download config.js from your server but it's failing to do so. I just tested it from the desktop and it worked fine. I also test your server from my mobile and it worked ok, so it must be a problem with your device / network.

**Comment by kunsubin96** [comment]
connect to server and run ios devide, but cannot connect to server and run android devide

**Comment by saghul** [comment]
Your certificate chain is misconfigured. This is a typical source of problems on Android. You can check it here, and also see how to solve it: https://whatsmychaincert.com/?room.surelrn.vn
