### ISSUE TITLE
[iOS] Issues trying to create jitsi framework

### ISSUE THREAD

**Issue by xiefangzhenz** [jitsi/jitsi-meet#4531]
I am trying to create the jitsi-meet framework for iOS.

When I execute in the root jitsi-meet directory:
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

It throws:

<code>
 export XPCSERVICES_FOLDER_PATH=JitsiMeet.framework/XPCServices
    export YACC=yacc
    export arch=arm64
    export diagnostic_message_length=246
    export variant=normal
    /bin/sh -c /Users/xiefangzhen/Library/Developer/Xcode/DerivedData/jitsi-meet-ciygatkliwhwiegftiafpravervk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh
WebRTC framework has NO bitcode
~/Documents/develop/html/jitsi-meet/node_modules/react-native-webrtc/ios ~/Documents/develop/html/jitsi-meet/ios/sdk
Downloading files...
Command /bin/sh failed with exit code 6

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Bitcode /Users/xiefangzhen/Library/Developer/Xcode/DerivedData/jitsi-meet-ciygatkliwhwiegftiafpravervk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh
(1 failure)
</code>

**Comment by saghul** [comment]
Did you install all dependencies? What Xcode and Node versions are you using?

**Comment by xiefangzhenz** [comment]
Thanks! @saghul All dependencies have been Installed.I can debug it in webstorm,but can't create framework. WEBRTC.framwork disappeared when I create framework failed.
Xcode:10.3
Node:10.15.3

**Comment by saghul** [comment]
> WEBRTC.framwork disappeared when I create framework failed.

Can you clarify this? WebRTC.framework is not built, it's part of the dependencies installed with npm.

**Comment by xiefangzhenz** [comment]
Thanks,I change node version to 10.16.3, solved it.
