### ISSUE TITLE
Jitsi-meet installation breaks on ubuntu minimal

### ISSUE THREAD

**Issue by setpill** [jitsi/jitsi-meet#4537]
Specifically, installation of the `jitsi-meet-web-config` dependency breaks with the following error:

> `cp: cannot stat '/usr/share/doc/jitsi-meet-web-config/config.js': No such file or directory`

I understand this is because ubuntu minimal has an apt rule to prevent installation of docs. Failing to install docs should not break installation of the package.

I do not know if this is the correct repo to report this bug; feel free to move it elsewhere if there is a more appropriate location.

**Comment by setpill** [comment]
The "culprit" in ubuntu minimal is the file `/etc/dpkg/dpkg.cfg.d/excludes`; adding `path-include=/usr/share/doc/jitsi*` to this file is a viable workaround.

**Comment by saghul** [comment]
I don't think Jitsi it's at fault here. Minimal images are known to be troublesome because of this. You can't possibly know what packages put in the files they ignore.

**Comment by setpill** [comment]
It is up to the packager to follow the rules of the system they package for; are you saying minimal images are unsupported? If so it might help to clarify that in the documentation.

**Comment by saghul** [comment]
Can you point me at where in the Debian packaging guidelines this "minimal" packaging is mentioned, and how packagers are supposed to act? We do follow the guidelines to the best of our knowledge.

**Comment by setpill** [comment]
https://jitsi.org/downloads/ lists "Ubuntu packages" and an "Ubuntu repository" - I am not talking about the Debian packages/repository.

**Comment by saghul** [comment]
They are the same thing and follow the same guidelines. So the question remais: does Ubuntu have guidelines for packagers for this case?

**Comment by setpill** [comment]
https://www.debian.org/doc/debian-policy/ch-docs.html#additional-documentation

> Packages must not require the existence of any files in /usr/share/doc/ in order to function.

**Comment by saghul** [comment]
Thanks for the pointer! @damencho looks like we might need to move some files around here...

**Comment by damencho** [comment]
This was fixed in the latest unstable packages.
