### ISSUE TITLE
 multi party video conference failing 

### ISSUE THREAD

**Issue by drpsrk** [jitsi/jitsi-meet#4545]
I have installed and set up jitsi meet on AWS with 4 core and 16Gb RAM and upto 10gbps bandwidth infrastructure. I have used a self signed ssl certificate as given in the documentation. The site says its insecure and does not load the video conferencing streams. Even if the connections establish, the video of the participants are not enabled. The site breaks down once we scale to four participants. The issue is same across devices (laptop/desktop/mobile). We have followed the steps given in
https://jitsi.org/news/new-tutorial-installing-jitsi-meet-on-your-own-linux-server/
please suggest if we have missed anything or is there any assumptions we need check.

**Comment by saghul** [comment]
You can use Let's Encrypt which is free and that will get rid of the "insecure" warning. Now, as for why the conference fails: are you entering with HTTP or HTTPS? Can you please share the JS console logs when it fails?

**Comment by drpsrk** [comment]
![IMG-20190816-WA0004](https://user-images.githubusercontent.com/54139347/63212314-12cc3d80-c120-11e9-9abc-c2ec458420e9.jpg)

Thanks very much to your suggestion after we did the suggested steps, we could link upto 16 participants on different pcs. As can be seen in the attached image (see link above), the following behavious is observed:
1. Some participants screens were blank, although there was no physical or electrical problem. Need to understand why this happens. 
2.  Some participants kept dropping and rejoining automatically.
3. When some participants leave the conference, there image is help still for more than a minute instead of their video window closing immediately for other viewers.
trying to understand why it does not clear immediately, why it keeps dropping, because each participant is having ample bandwidth.
