### ISSUE TITLE
[i18n] Unreadable translations

### ISSUE THREAD

**Issue by Quenty31** [jitsi/jitsi-meet#4556]
Hello,
I'd like to finish my translations but the newest strings are hard to understand.
Some examples:
"Add meeting $t(lockRoomPasswordUppercase)"
"$t(lockRoomPasswordUppercase)"
"Setting a meeting $t(lockRoomPassword) is not supported."
"$t(lockRoomPasswordUppercase) not supported"

I do not understand what's with all these $t strings.
How are we supposed to translate them?

**Comment by damencho** [comment]
Please use the community forum when having questions or problems before opening new issues.

These are variables, so you just need to translate lockRoomPasswordUppercase and then use this in these strings as $t(lockRoomPasswordUppercase). By default lockRoomPasswordUppercase is 'Password' and lockRoomPassword is 'password', you can check those in the template used for all languages https://github.com/jitsi/jitsi-meet/blob/master/lang/main.json#L407.
We use this to be able brand some deployments and to avoid duplication of strings.
