### ISSUE TITLE
Problem with break lines in chat

### ISSUE THREAD

**Issue by juliemar** [jitsi/jitsi-meet#4557]
## Description
In the current chat when I sent a message with break lines this message is rendered wrong.

## Current behavior
my message with tree lines
![image](https://user-images.githubusercontent.com/643779/63395704-f425ab00-c39a-11e9-86f9-85425f406d97.png)

The wrong result
![image](https://user-images.githubusercontent.com/643779/63395763-26370d00-c39b-11e9-94df-b0a1482d320e.png)

## Expected Behavior
the message needs to be rendered like this:
![image](https://user-images.githubusercontent.com/643779/63396095-5206c280-c39c-11e9-90af-13605a89e1c7.png)

## Possible Solution
I believe we have to change on line 36,37,38,39 in this file: https://github.com/jitsi/jitsi-meet/blob/master/react/features/chat/components/web/ChatMessage.js

`const escMessage = messageToDisplay.replace(/</g, '&lt;')
.replace(/>/g, '&gt;')
.replace(/\n/g, '<br/>');
const processedMessage = [];
`
when I inspect the HTML shows like this
![image](https://user-images.githubusercontent.com/643779/63396044-27b50500-c39c-11e9-9301-0d182766a8c1.png)

## Steps to reproduce
start a chat and send a message with multiple lines executing CTRL+SHIFT+ENTER to put a new line

# Environment details
I'm using Chrome in Ubunto 18.01

**Comment by saghul** [comment]
The proposed solution looks good, care to send a PR?

**Comment by saghul** [comment]
@zbettenbuk @virtuacoplenny do you guys know if this got fixed?

**Comment by virtuacoplenny** [comment]
I tested just now on beta by sending a chat with line breaks. The tags are gone but the line breaks are not being displayed; it may need some `white-space: pre`.
