### ISSUE TITLE
Hight CPU utilization

### ISSUE THREAD

**Issue by juliemar** [jitsi/jitsi-meet#4558]
## Description
We are using the jitsi with a videoconferencing provider in our[ open source project](https://github.com/ResultadosDigitais/matrix).

I'm using the embeded mode [here](https://github.com/ResultadosDigitais/matrix/blob/e02d547858b4fd543499ca21b2ad7b77df49625a/frontend/office.js#L117) is possible to see my current configurations.

## Current behavior
In my computer when I enter in a meeting my CPU hit between 80% and 100% 

## Expected Behavior
Don't eat my CPU  

## Steps to reproduce
Enter in [my project with anything google account](https://matrix-juli.herokuapp.com/) using a computer with a nondedicated videobridge and folow de CPU utilization. 

# Environment details
I'm chrome on Windows 10 to reproduce hight CPU utilization.

**Comment by Beeez** [comment]
I think Resolution, number of users and some of the encoding like H264 can contribute. I've always just dealt with it though unfortunately. My laptops fans ramp up shortly after joining a call.
