### ISSUE TITLE
RTCCVPixelBuffer、RTCWrappedNativeVideoDecoder、RTCVideoDecoderVP8 implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib

### ISSUE THREAD

**Issue by nchkdxlq** [jitsi/jitsi-meet#4559]
objc[19527]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1d3234018) and /private/var/containers/Bundle/Application/7DAC2F64-9DBD-494A-A17A-623423FE0F32/jitsi-meet.app/Frameworks/WebRTC.framework/WebRTC (0x105992cb0). One of the two will be used. Which one is undefined.
objc[19527]: Class RTCWrappedNativeVideoDecoder is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1d104b428) and /private/var/containers/Bundle/Application/7DAC2F64-9DBD-494A-A17A-623423FE0F32/jitsi-meet.app/Frameworks/WebRTC.framework/WebRTC (0x105992da0). One of the two will be used. Which one is undefined.
objc[19527]: Class RTCWrappedNativeVideoEncoder is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1d104b478) and /private/var/containers/Bundle/Application/7DAC2F64-9DBD-494A-A17A-623423FE0F32/jitsi-meet.app/Frameworks/WebRTC.framework/WebRTC (0x105992df0). One of the two will be used. Which one is undefined.
objc[19527]: Class RTCVideoDecoderVP8 is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1d104b180) and /private/var/containers/Bundle/Application/7DAC2F64-9DBD-494A-A17A-623423FE0F32/jitsi-meet.app/Frameworks/WebRTC.framework/WebRTC (0x105992eb8). One of the two will be used. Which one is undefined.

**Comment by saghul** [comment]
You can ignore those. That's a bug on Apple's WebCore framework, they shouldn't be exposing those symbols.

PS: Please use our issue template next time, it's there for a reason.

**Comment by nchkdxlq** [comment]
@saghul  ok, thank you very much.

**Comment by fukemy** [comment]
that so bad when i got this error , it CRASH my app

**Comment by saghul** [comment]
@fukemy That's just a warning, so it must be something else. Can you please an issue and paste the full backtrace?

**Comment by fukemy** [comment]
> @fukemy That's just a warning, so it must be something else. Can you please an issue and paste the full backtrace?

oki thanks, i found that crash my app because other reason. kiki
