### ISSUE TITLE
detect poor connection and disconnect

### ISSUE THREAD

**Issue by mohammaddvi** [jitsi/jitsi-meet#4576]
How can I detect black screen when poor connection and disconnect?in both situation just a onConferenceFailed will be call and nothing else.(Android)

**Comment by saghul** [comment]
Can you please elaborate? What problem are you observing exactly?

**Comment by mohammaddvi** [comment]
In Android SDK, I can just 5 listener to handle call situation(onLeft, will leave, fail , will join and join) and I can`t know user has poor connection or failed connection to show a proper Toast or snackbar and accompany user to right way.

**Comment by saghul** [comment]
Right. This is not something we support, nor we plan to. We do have plans to show this inside the Jitsi Meet view. We already do it for the remote participants and will be extending it to the local participant too. Keep an eye on the repo!
