### ISSUE TITLE
Compressed (shortened) audio heard

### ISSUE THREAD

**Issue by dangrayorg** [jitsi/jitsi-meet#4580]
## Description

Audio from guest was available but was 'compressed'. Delivered in short bursts at very high speed - chipmunk style! Both users on Jitsi Web.

## Current behavior

 See description

## Expected Behavior

Audio should be delivered at normal speed.

## Possible Solution
Could this be a codec problem somewhere in the server, maybe an issue with detection of sample rates?

## Steps to reproduce

Happened on every call. Tried 3 times.

# Environment details

4.15.0-1045-aws
Ubuntu 18.04.2 LTS 
ca-certificates-java:amd64 (20180516ubuntu1~18.04.1, automatic), libcups2:amd64 (2.2.7-1ubuntu2.7, automatic), libpcsclite1:amd64 (1.8.23-1, automatic), liblcms2-2:amd64 (2.9-1ubuntu0.1, automatic), lua5.1:amd64 (5.1.5-8.1build2, automatic), lua-filesystem:amd64 (1.6.3-1, automatic), lua-bitop:amd64 (1.0.2-5, automatic), libxrender1:amd64 (1:0.9.10-1, automatic), lua-expat:amd64 (1.3.0-4, automatic), jicofo:amd64 (1.0-481-1, automatic), libavahi-common-data:amd64 (0.7-3.1ubuntu1.2, automatic), libavahi-common3:amd64 (0.7-3.1ubuntu1.2, automatic), jitsi-meet-web:amd64 (1.0.3577-1, automatic), prosody:amd64 (0.10.0-1build1, automatic), jitsi-meet:amd64 (1.0.3936-1), jitsi-videobridge:amd64 (1124-1, automatic), jitsi-meet-web-config:amd64 (1.0.3577-1, automatic), libxtst6:amd64 (2:1.2.3-1, automatic), libxi6:amd64 (2:1.7.9-1, automatic), lua-event:amd64 (0.4.3-2build1, automatic), lua-socket:amd64 (3.0~rc1+git+ac3201d-4, automatic), openjdk-8-jre-headless:amd64 (8u222-b10-1ubuntu1~18.04.1, automatic), libnss3:amd64 (2:3.35-2ubuntu2.3, automatic), x11-common:amd64 (1:7.7+19ubuntu7.1, automatic), libavahi-client3:amd64 (0.7-3.1ubuntu1.2, automatic), java-common:amd64 (0.68ubuntu1~18.04.1, automatic), libnspr4:amd64 (2:4.18-1ubuntu1, automatic), jitsi-meet-prosody:amd64 (1.0.3577-1, automatic), lua-sec:amd64 (0.6-4, automatic)

**Comment by saghul** [comment]
Thanks for the report! Any chance you can get an audio recording? What endpoints were you using? Browsers or the mobile apps? What versions?

**Comment by saghul** [comment]
No follow-up, closing.
