### ISSUE TITLE
Swift : JitsiMeetView buttons gets untouchable after one touch

### ISSUE THREAD

**Issue by mostafa-v** [jitsi/jitsi-meet#4587]
## Description
I'm adding Jitsi-Meet to my Xcode project (like the demo app). The view is shown and if the peers connect, the pictures are properly shown... The problem is I can touch buttons only one time.

## Current behavior
First touch anywhere on jitseemeetview behaves as expected (whether it is a button, or anywhere else on the view), but then buttons does not respond to touch. jitsimeetview became untouchable except for user thumbnails at bottom that can get scrolled (but not clickable in order to change between different users)

## Expected Behavior
Buttons could be touchable multiple times, ...

## Possible Solution
---

## Steps to reproduce
The base project I'm working on is a big project and I'm not fully aware of its architecture. I have tried different ways to add JitsiMeetView (Using pip coordinator, adding Jitsi Meet as subview, presenting view controller, pushing to navigation controller) , but this problem exists nonetheless. I don't have any clue what may cause this issue.

# Environment details
Xcode, swift, also the project uses [AsyncDisplayKit](https://github.com/facebookarchive/AsyncDisplayKit)

**Comment by saghul** [comment]
Can you provide a small example project which exhibits the issue? Otherwise I'm afraid there is not much we can do to help.

**Comment by mostafa-v** [comment]
I emailed you the details of the project. I'd be thankful if you check that.
