### ISSUE TITLE
Meet.jit.si live streaming does not works

### ISSUE THREAD

**Issue by Vitoza** [jitsi/jitsi-meet#4592]
Jitsi feature (on meet.jit.si server) "start live stream" does not works during 3 days already, saying:
Live Streaming unavailable
Oops! The Live Streaming service is currently unavailable. We're working on resolving the issue. Please try again later.

Can we hope for a fix to this problem during nearest days?

**Comment by Viktoriya012** [comment]
не знаете аналог мита, что использовать, пока он не работает?

**Comment by Vitoza** [comment]
Hello? Is there anybody out there? (c)

**Comment by saghul** [comment]
Sorry for the lack of replies 😢  This should be working now. Note that we can't offer unlimited resources for free so it's possible all our recorders are busy at times.

**Comment by Vitoza** [comment]
Thanks for the explanation. It works now. But quality of video dramatically low occasionally, worse than  the same video session quality in a real time. Is it possible to configure recording quality in the Jitsy Meet?

**Comment by saghul** [comment]
No, it's not possible to configure it. It should be maximum quality, same as live. If you expereience issues, please do open a new issue and provide us with a short clip of the recording and call information so we can take a look.

**Comment by Vitoza** [comment]
ok. Thank you

**Comment by servetbozkurtt** [comment]
Oops! The Recording service is currently unavailable. We're working on resolving the issue. Please try again later.

Could you explain the solve about this error :(
![WhatsApp Image 2020-04-16 at 18 39 24](https://user-images.githubusercontent.com/18358643/79476968-4d210e00-8012-11ea-8e50-f7a4376e554b.jpeg)

**Comment by rescue1155** [comment]
> Oops! The Recording service is currently unavailable. We're working on resolving the issue. Please try again later.
> 
> Could you explain the solve about this error :(
> ![WhatsApp Image 2020-04-16 at 18 39 24](https://user-images.githubusercontent.com/18358643/79476968-4d210e00-8012-11ea-8e50-f7a4376e554b.jpeg)

Getting same error.
