### ISSUE TITLE
kamera

### ISSUE THREAD

**Issue by Steffo64** [jitsi/jitsi-meet#4594]
När jag skall ha en videokonferens, så står det att kameran inte stöds, förstår inte vad det kan vara för fel. kameran visas en kort sekund , sen blir det svart

**Comment by saghul** [comment]
Please use the issue template and formulate your questions in English.

**Comment by Steffo64** [comment]
My camera does not work when I am having a video conference, it says that access to the camera is missing. How to set it. When I start the program it finds the camera, but then they turn black and the sound is only heard. What could be the problem. Have never heard of this program before, is new to me

**Comment by saghul** [comment]
Please give us some details: are you using the mobile apps or the browser? What version?

**Comment by Steffo64** [comment]
Hey!

I use browser and windows ten

**Comment by saghul** [comment]
What browser? Also, does it work here? https://test.webrtc.org/

**Comment by Steffo64** [comment]
I have Google Chrome and its not working

**Comment by saghul** [comment]
If the test site doesn't work either then there is some problem in your system, unfortunately. Jitsi Meet uses the browser provided multimedia capabilities, so if those don't work, there is not much we can do.

Try the following: reboot the machine. Check that any software which might use the camera is closed. Try again.

**Comment by Steffo64** [comment]
shit program that doesn't work
