### ISSUE TITLE
Multipath routing for conference broadcast reliability

### ISSUE THREAD

**Issue by cmrd-senya** [jitsi/jitsi-meet#461]
Hi!

Consider I have two mobile 3G internet connections. Both are pretty stable but can lose connection occasionally.

Is there any practices I could apply, so that my Jitsi Meet conference is routed via two different connection (like tcp multipath), so that if one fails, another could be used glitch-free and without conference reload?

**Comment by PolynomialDivision** [comment]
I would love to see that. :)
