### ISSUE TITLE
[Bug/Android] Crash by RNConnectionService.java

### ISSUE THREAD

**Issue by vtnhondk** [jitsi/jitsi-meet#4610]
## Description
--- 
jitsi-meet/android/sdk/src/main/java/org/jitsi/meet/sdk/RNConnectionService.java
Crash in startCall() function

## Current behavior
---

```private static final String TAG = ConnectionService.TAG;```

- Tag is String but in log using **%d** in 1st parameter

<img width="638" alt="image" src="https://user-images.githubusercontent.com/11543501/64502019-10f43500-d2ee-11e9-8ed5-36c354cee33b.png">

## Expected Behavior
---

```
JitsiMeetLogger.d("%s startCall UUID=%s, h=%s, v=%s",
                           TAG,
                             callUUID,
                             handle,
                             hasVideo)
```

## Possible Solution
---

```
JitsiMeetLogger.d("%s startCall UUID=%s, h=%s, v=%s",
                           TAG,
                             callUUID,
                             handle,
                             hasVideo)
```

## Steps to reproduce
---
# Environment details
---

**Comment by saghul** [comment]
Please check https://github.com/jitsi/jitsi-meet/pull/4609
