### ISSUE TITLE
I cant 2 days to use Live Jitsi

### ISSUE THREAD

**Issue by Polinaschool** [jitsi/jitsi-meet#4611]
Already 2 days I have problem
![IMG_5588](https://user-images.githubusercontent.com/55086522/64523981-3b51ec80-d306-11e9-982a-1c3dd21d7b06.JPG)

, I can"t open live on Jitsi. What happend? 
I try to use my keys from Youtube, friends key, not.
Computer friend, its ok, Im not

**Comment by saghul** [comment]
We have fixed a number of problems in this area, so this should be fixed now. Note, however, that we don’t provide unlimited live streaming resources, so it’s still possible to get failures, if all our resources are busy.
