### ISSUE TITLE
Два дня я не могу запустить трансляцию в Jitsi

### ISSUE THREAD

**Issue by Polinaschool** [jitsi/jitsi-meet#4612]
Перепробовали все!!! Заходила с разных браузеров, открывала через инкогнито, пишут трансляция не возможна!!!!! Что делать?? Это большие проблемы для меня и бизнеса моего.
Пробовали использовать ключи не с моего Youtube трансляции, нет ничего не запускается, у друга на компьютере работает у меня нет.
Месяц назад я вела трансляции на Jitsi все было хорошо, что случилось???

Помогите, мне очень нужна помощь. У меня на 11 сентября назначена трансляция, запущена реклама, а Jitsi не работает((((((
![IMG_5588](https://user-images.githubusercontent.com/55086522/64524400-18740800-d307-11e9-86d5-a12031c0a20c.JPG)

**Comment by damencho** [comment]
Please use the community forum before opening new issues. And use English, please.
