### ISSUE TITLE
Low webcam resolutions selected by default on Google Chrome and Firefox

### ISSUE THREAD

**Issue by gradinaruvasile** [jitsi/jitsi-meet#462]
It seems that on Jitsi Meet Google Chrome always selects 640x360 resolution for desktop webcams even if they support higher resolutions. I tried this with webcams supporting 1280x720, 1920x1080, 1024x768 resolutions. Google Chrome always selected 640x360.

In Firefox 43 with default settings the resolution was 640x480, although i could force other supported resolutions through setting explicit width and height in the (about:config) settings "media.navigator.video.default_width" and "media.navigator.video.default_height".

OS: Debian Stable and Testing, Google Chrome 47.0.2526.111, Firefox 43.04

**Comment by bgrozev** [comment]
Try setting "resolution: '720'" in config.js

**Comment by gradinaruvasile** [comment]
Which config.js?
I tried setting it in /etc/jitsi/meet/domainname.js, /etc/jitsi/meet/interface_config.js but Chrome always selects 640x360.

**Comment by hydrandt** [comment]
Try reloading with ctrl+F5 (with flushing browser cache), when I was doing some changes, the cached kept being displayed.

**Comment by gradinaruvasile** [comment]
I tried. On 4 different computers, 3 running Linux (debian Testing, Stable) and one Windows 10. All with Chrome stable and Firefox and same results. 640x480 Firefox, 640x360 Chrome.

**Comment by gradinaruvasile** [comment]
I did more tests (hacking into app.bundle.min.js, replacing all occurences of ||"360" with other resolutions) and it seems that

- Firefox just ignores this setting and uses 640x480 and for alternate resolutions honors only the forced "media.navigator.video.default_height" and "media.navigator.video.default_width" (set through the about:config page)
- Chrome uses ONLY this setting whatever it is set to. In case of not having this resolution (720 set and 1024x768 webcam available) available it falls back to 320x240, regardless if it has in-between resolutions available lower on the list (640x480, 640x360, 1024x768).

Right now if both sides use Chrome, they must use the lowest common resolution set in app.bundle.min.js which seems to be 640x360. If this resolution is set to one that is not available on one side, it seems that one side will fall back to a really low resolution.
On Firefox it seems that no matter what is set here, only 640x480 will be used (except cases where the user is able to set his own preferred resolution locally).
What is the designed behavior for resolution selection?

**Comment by gradinaruvasile** [comment]
Actually setting "resolution: '720'" in config.js worked in Chrome after browser restart (Firefox ignores this setting too). And it does fall back to the next available resolution too if '720' is not available. Now, i have a 1024x768 capable webcam and the next resolution is 960x720. 1024x768 is not on the list.

I modified app.bundle.min.js and added "1024:{width:1024,height:768,order:6}" and shifted the orders of the higher resolutions. This way if i set 720 in config.js with the 1024x768 webcam it uses 1024x768 resolution in Chrome.
Can you add the 1024x768 resolution to the resolution list?

**Comment by gradinaruvasile** [comment]
After installing jitsi-meet 1.0.803-1, Chrome uses only 640x360 or 320x180 sometimes. I use the same config.js as before. I see that some js files were changed and i see no config.resolution in the .min.js files

**Comment by hydrandt** [comment]
Is this a bug? Is this a feature? What is the intended behaviour? For me, Chrome seems to always select lower resolution than Firefox.

**Comment by gradinaruvasile** [comment]
Well, at least for Chrome the actual behavior it seems to be that if no "resolution" is specified in config.js (/etc/jitsi/meet/domainname-config.js) it will select "360" which is 640x360 by default.
If you add "resolution: '720'" for example it will try to use 1280x720 and if not available, fall back to the next resolution.
Firefox is oblivious to this setting - its internal "media.navigator.video.default_height" and "media.navigator.video.default_width" variables can be used to select anything different from the default 640x480.

Right now at least the current Debian build 1.0.803-1 however seems to have a problem since using it ignores the resolution value from config.js (it IS working in the previous version 791) and Chrome selects 640x360 or even 320x180 in the same conditions randomly.
Its maybe caused by commit https://github.com/jitsi/jitsi-meet/commit/ffbaaa26224c1af1d3e39c1a2b3a8c6e83df3c71 ?
Since the .js files were modified and the config.resolution variable cannot be found in the new /usr/share/jitsi-meet/libs/lib-jitsi-meet.min.js file anymore.

**Comment by danboid** [comment]
It would be great if this could be auto-detected or otherwise set in the JM UI rather than having to hack the source or browser config.

**Comment by gradinaruvasile** [comment]
It seems that in more recent versions Chrome uses some bandwidth auto detection and sometimes reaches the 1280x720 resolution. But it's random (it seems) and doesnt scale with bandwidth correctly (it changes seemingly randomly even when bandwidth is available).
It would be nice to have a resolution change option under settings.

**Comment by gradinaruvasile** [comment]
Tested again and it seems it is still broken in Chrome. We had Firefox on one end and Chrome on the other. Bandwidth was no issue. Firefox was working ok (1024x768, max for its webcam), but Chrome that had a 1920x1080 webcam was using 320x180 for 10 minutes until we started using Firefox on that end too which was using 1280x720(set from about:config)  with no issues.

**Comment by PocoCraft** [comment]
I am testing with Windows 10 and Debian 8(Jessie) both with the latest Google Chrome as of posting and I am having the same issue.
I am streaming with FFMPeg on Debian 8 at 1080P(native) and 720P(downscaled) and I am only able to stream at 640x360.

**Comment by anatomism** [comment]
Same as above in Chrome 52. Rather irritating

**Comment by daradib** [comment]
Is there a functioning workaround? On Firefox 48, the media.navigator.video settings seem to only apply initially. When new clients join or existing ones refresh the page, they switch to lower resolutions. And config.resolution did not work for me in Chrome 52.

**Comment by gradinaruvasile** [comment]
On recent nightlies it sems to work better. Using Chrome on both sides the resolution set in config are resdpected mostly. There are resolution changes from time to time and sometimes, but mostly is ok.

**Comment by abeverley** [comment]
I've been having the opposite problem (too high a resolution for the available bandwidth). I found that by setting ```resolution``` in ```config.js``` I could force a lower resolution, but only Chromium paid any attention to it. I was unable to change the resolution in Firefox (49) either with that setting or by setting ```media.navigator.video.default_height``` in ```about:config```. So for me, the solution is use Chromium and set the resolution in ```config.js```.
