### ISSUE TITLE
ScreenShot on Android device.

### ISSUE THREAD

**Issue by Rana-Mohit** [jitsi/jitsi-meet#4623]
Hi, 
When i try to take screenshot of conference screen with my  android device it give me black screen in screenshot.
Using this library for screenshot "react-native-view-shot": "^3.0.2".
Any help will be appreciated.

**Comment by saghul** [comment]
That won't work. Video is drawn on an OpenGL surface. Many have tried in the past, but with little success. Feel free to browse issues at https://github.com/react-native-webrtc/react-native-webrtc
