### ISSUE TITLE
«Something went wrong» when more than 1 user join the room

### ISSUE THREAD

**Issue by stemy2** [jitsi/jitsi-meet#4626]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
It works only if i stay alone in the room.

## Current behavior
Session is terminated with the message « something went wrong».

## Expected Behavior
I can speak with someone through the app.

## Possible Solution
---

## Steps to reproduce
1. Create a room.
2. Make another user join the room.

# Environment details
Jitsi meet 1.0.3387 on yunohost 3.6.4.6

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

You need to provide more details for your problem, like your js console logs.
