### ISSUE TITLE
jitsi не могу запустить трансляцию бета

### ISSUE THREAD

**Issue by oksanchik121** [jitsi/jitsi-meet#4638]
Здравствуйте, нажимаю начать трансляцию Бета, ввожу код трансляции, нажимаю начать трансляцию, но вместо начала трансляции выходит ошибка: Все ресурсы для трансляции уже задействованы. Как мне запустить трансляцию и в чем может быть ошибка

**Comment by damencho** [comment]
Please use the community forum before opening new issues. And use English, please.
