### ISSUE TITLE
make dev doesn't work

### ISSUE THREAD

**Issue by billkim84** [jitsi/jitsi-meet#4639]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I've been worked on jitsi-meet client the last few weeks and suddenly it doesn't work. 
I downloaded the code again and ran but still doesn't work.
![image](https://user-images.githubusercontent.com/2604192/64907697-e75b5500-d6c3-11e9-9658-ef137de5947f.png)

Browser logs. 
![image](https://user-images.githubusercontent.com/2604192/64907768-de1eb800-d6c4-11e9-80b4-00f3f552a07a.png)

I believe it's both url problem but I don't know how I get this url. 
![image](https://user-images.githubusercontent.com/2604192/64907806-48375d00-d6c5-11e9-8a10-69b027e6682c.png)

## Current behavior
I can join the conference room but I can't see the video.

# Environment details
---
OS: macOS Mojave 10.14.6

**Comment by virtuacoplenny** [comment]
You probably need to be on latest master which has this change 40a1af53029316448e92d23403abfd881cf32ede.
