### ISSUE TITLE
Трансляция не начинается

### ISSUE THREAD

**Issue by Mariya-Kalmykova** [jitsi/jitsi-meet#4640]
Здравствуйте. Трансляция не воспроизводится. Пишет сообщение "Все ресурсы для трансляции уже задействованы. Освобождаем новые ресурсы" И так уже второй день. У нас сегодня трансляция в 13:00. помогите исправить проблему.

**Comment by damencho** [comment]
Please use the community forum before opening new issues. And use English, please.
