### ISSUE TITLE
Не запускается трансляция

### ISSUE THREAD

**Issue by Quzzzka** [jitsi/jitsi-meet#4641]
Здравствуйте. Делаю все по этой схеме: https://vk.com/@bizon365-proschaemsya-s-google-hangouts-a-chto-vzamen 
Вставляю ключ с ютуба, включаю трансляцию, мне пишут что все ресурсы для трансляции уже задействованы, освобождаем новые ресурсы для трансляции. Пожалуйста, попробуйте снова через несколько минут. Но и через несколько минут ничего не происходит. Что можно сделать?

**Comment by damencho** [comment]
Please use the community forum before opening new issues. And use English, please.
