### ISSUE TITLE
Video Quality and Camera Zoom.

### ISSUE THREAD

**Issue by Rana-Mohit** [jitsi/jitsi-meet#4642]
Hi,
1- I want to Know how can i change video quality like web in mobile apps. Is it possible or not. Or we can change it from webrtc.
 2- Can we zoom our device camera while in video conference. Or we can zoom video in conference.

If  any from above is possible please help me.
Thanks.

**Comment by saghul** [comment]
> 1- I want to Know how can i change video quality like web in mobile apps. Is it possible or not. Or we can change it from webrtc.

It's not possible to change it at the moment. You can change to "low bandwidth mode", which disables video entirely.



> 2- Can we zoom our device camera while in video conference. Or we can zoom video in conference.

No.

PS: Please use the community forum for such questions: https://community.jitsi.org/

**Comment by Rana-Mohit** [comment]
PS: Please use the community forum for such questions: https://community.jitsi.org/.
Ok thanks.
