### ISSUE TITLE
Mute / Unmute disappear after modification

### ISSUE THREAD

**Issue by matrixtempnew** [jitsi/jitsi-meet#4644]
![Screenshot from 2019-09-17 14-29-05](https://user-images.githubusercontent.com/46959277/65028028-fa3a8780-d958-11e9-8a46-c564842ee927.png)

As you can see in the image on remote participant controls triple dot menu hover I can't see anything.

**Comment by damencho** [comment]
Please use the community forum before opening new issues. 

I suspect there is no media path established between clients, is audio/video communication working on this deployment? I had seen this when there is no audio/video working between clients, there is no audio track to be able to mute.

**Comment by matrixtempnew** [comment]
> Please use the community forum before opening new issues.
> 
> I suspect there is no media path established between clients, is audio/video communication working on this deployment? I had seen this when there is no audio/video working between clients, there is no audio track to be able to mute.

@damencho audio is working between clients they can hear audio and also see a video, I think there is another problem.
