### ISSUE TITLE
Selective loss of audio from participants

### ISSUE THREAD

**Issue by yarikoptic** [jitsi/jitsi-meet#4648]
We had been using jitsi very successfully for awhile with similar number of participants (up to 5) in the https://meet.jit.si/DataLad room. But recently we have started to experience issues where we all or just some of us cannot hear some other participant.  Typically it was "resolved" by reconnecting of the one who could not be heard. In the recent attempt to meet (today) where we had 5 participants, we simply could not achieve the same (and ended up resorting to another video cast). It felt like it was working ok while we had 4 participants, but with the 5th joining we were loosing audio.  We didn't establish the full "logic" for this.  Altogether in this session we had 4 Linux (Debian/Ubuntus) and 1 Windows laptops connecting.
I am not sure what other information I could provide, but may be someone keeps the logs for the meetups on meet.jit.si to discover more?

**Comment by yarikoptic** [comment]
participants (besides me) were @jbpoline, @kyleam, @bpoldrack, and @tedstrauss happen they could provide additional information

**Comment by damencho** [comment]
I see in the stats that some of the participants had been using Firefox. Have you noticed whether when someone is not hearing, was it using Firefox?
There is a known issue about Firefox, which is still not addressed.

**Comment by yarikoptic** [comment]
I was using chromium, and I couldn't hear some of the participants too I believe. But next time we will try to stay Firefox free and see if that helps anyhow

**Comment by damencho** [comment]
And please report again with the meeting URL, thanks.

**Comment by RevoluPowered** [comment]
We had this issue on our own self hosted setup.

We had approximately 10 people in the call, and the call seems to drop on firefox when someone either:
1. kicks someone from the call
2. someone new joins

I personally have not experienced this on chrome, but I mainly use firefox.
