### ISSUE TITLE
iOS 13 GM: Black screen

### ISSUE THREAD

**Issue by markmadlangbayan** [jitsi/jitsi-meet#4653]
## Description
I have iOS 13 GM, most probably the version that will be released in two days.  On our app, and the Jitsi Meet app, I'm getting audio but a black screen on the app.  On the receiving end, another version of the iOS OS (12.x) or web, I can receive both video and audio for the session.  This might be related to #4386 .

## Current behavior
Black screen with audio

## Expected Behavior
Video should show up

## Steps to reproduce
Download Jitsi Meet app and join a conference.

# Environment details
Any version of Jitsi Meet (including on App Store) as long as the version of iOS OS is 13.

**Comment by saghul** [comment]
We are aware of this. A new version is on the way with a fix, hold on tight!

**Comment by saghul** [comment]
An update is now available on the App Store fixing this problem.

**Comment by saghul** [comment]
We released SDK version 2.3.0 which fixes this problem. Updating your app to use it should fix the problem for you. Please let us know if it doesn't.

**Comment by osdchris** [comment]
Noted with thanks , let me try to build with sdk 2.3.0.

**Comment by sparmar-atheer** [comment]
Hi @saghul 
Can you please point us to fix you did to resolve this issue?

**Comment by saghul** [comment]
It’s the update to M75 that fixed it AFAICT.

**Comment by sparmar-atheer** [comment]
Great. Thanks @saghul
