### ISSUE TITLE
external_api.js - Error when trying to set password

### ISSUE THREAD

**Issue by alenbasic** [jitsi/jitsi-meet#4655]
Apologies, not sure whether this is the right place to post this but I am looking at how to use the API based on this document: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

In there it states to set the password to use: 

    api.executeCommand('password', 'The Password');

However it doesn't seem to work. I am not really a web developer, but I found this in the console logs and I'm thinking it's probably relevant:

    Uncaught TypeError: Cannot read property 'lock' of undefined at Object.password (API.js:89)

Essentially all I did was use the example html file and add that command directly below the setting of the api var, so if it's me not doing something right, apologies.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

https://community.jitsi.org/t/setting-the-room-password-on-creation-using-the-jitsi-meet-api/19426/2?u=damencho

Depends what you want to do with the command, you either execute it after you had joined a conference or after a password required event is received.
