### ISSUE TITLE
When clicked on meeting history it redirects to the same meeting i had started

### ISSUE THREAD

**Issue by Apoorvadimpu** [jitsi/jitsi-meet#4656]
Hello team,

I have an issue with the meeting history: I can see the meeting history . when clicked on history it redirects me to the meeting i had started with the same meeting name i had given.
i dont want to redirect to the same meeting again that i had started but instead i want to get the recorded meeting.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

> i dont want to redirect to the same meeting again that i had started but instead i want to get the recorded meeting.

This functionality is not available, and it requires additional development on your side based on what authentication you had chosen for your system.

First you need to add a custom recording service, jibri should push recording to some storage you own. You need information for the user, for now jwt token is available to recognize users. 
Then you need a service which users can query about recent meetings and recordings passing their jwt token so the service can recognize them. And then you need to modify the UI adding the functionality to query the service and show the meetings with their recordings.

**Comment by vanduc9a2** [comment]
I am a new user of jitsi-meet, and I find it very interesting. I am currently the owner of my Jitsi-meet server, but I cannot know how? who has access and who created the meeting on my jitsi-meet server. please show me. (my english is not good)! thanks so much.
