### ISSUE TITLE
Create a meeting history and upcoming history

### ISSUE THREAD

**Issue by Apoorvadimpu** [jitsi/jitsi-meet#4657]
How can we get the server side recorded details not the video on the client side (details of number of participants, participant name and the meeting name).

Where are meeting details stored in the server code so that i can access them using an API.

I want to create a meeting history as well as the upcoming meeting history . All suggestions are welcome

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

I think I had answered most of the questions here: https://github.com/jitsi/jitsi-meet/issues/4656
What you need is implement custom https://github.com/jitsi/jibri/blob/master/resources/finalize_recording.sh for your jibri instances, so you can upload the recordings on your system, the script has access to a metadata json file which contain jwt token of the user that created the recording.

**Comment by mdell-seradex** [comment]
This sounds to me like the request was completely misunderstood as he said "not the video".
