### ISSUE TITLE
Problem with recording Jitsi

### ISSUE THREAD

**Issue by msowa92** [jitsi/jitsi-meet#4659]
Im installed Jitsi-Meet and Jibri and I can't recording. I have comunicate : 

Recording unavailable. Oops! The recording service is currently unavailable. We're working on resolving tji issue. Please try again later.

**Comment by damencho** [comment]
When having a question or problems, please use the community forum before opening new issues.

Check your jibri logs, this means your jibri is not connected to the xmpp server and jicofo is not seeing any available jibri.
