### ISSUE TITLE
JS errors when the "lock/unlock" button is clicked

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#466]
In jitsi-meet some buttons, such as "Record" and "Lock/unlock room", 
depending on impromptu library, cause an error:

Uncaught TypeError: t.jqib.on(...).on(...).on is not a function jquery-impromptu.js:356

Originally reported on dev@jitsi.org: http://lists.jitsi.org/pipermail/dev/2016-January/026498.html

**Comment by vnc-rainer-schuth** [comment]
This error also happens when trying to use Jigasi ("Call Sip Number").

See http://lists.jitsi.org/pipermail/users/2016-January/010726.html

**Comment by dwilson6** [comment]
As I posted on the mailing list, this is a bug in jquery 2.2.0. http://lists.jitsi.org/pipermail/dev/2016-January/026501.html

**Comment by damencho** [comment]
Fixed for now in build 791.
