### ISSUE TITLE
Jibri — "Recording unavailable" — What to do? Which/where the logs to check?

### ISSUE THREAD

**Issue by vedavrat** [jitsi/jitsi-meet#4660]
In my case, Jitsi and Jibri work on own VDS sever (domain: meet1.ved.bz). 
The server has 4 GB RAM and 4 CPUs.

When i press "Start recording", the recording does not begin, 
and there is an error message on orange backgroung:
«««
Recording unavailable
The Recording service is currently unavailable. We're working on resolving the issue. Please try again later.
»»».

The same problem, if i try to "Start a live stream"...

What to do? How to find the reason?

**Comment by damencho** [comment]
When having a problem or a question use the community forum before opening a new issue.

Have you checked jibri logs for errors?
