### ISSUE TITLE
ios SDK 2.3.0 audio always routed to the speaker

### ISSUE THREAD

**Issue by Denismih** [jitsi/jitsi-meet#4662]
## Description
ios SDK 2.2.0 route audio to the earpiece when call is "AudioOnly". Now  in SDK 2.3.0 audio always routed to the speaker, then I can change audio device.

## Current behavior
audio always routed to the speaker if  "AudioOnly" true/false

## Expected Behavior
route audio to the earpiece when call is "AudioOnly"

## Possible Solution
add in JitsiMeetConferenceOptions.fromBuilder default audio device variable

## Steps to reproduce
make call with and without  "AudioOnly"

# Environment details
XCode 10.3
IOS 12.4

**Comment by saghul** [comment]
This is the new expected behavior, the change is intentional.

**Comment by Frindecent** [comment]
@saghul is it possible for you to point towards the location of the file for this behaviour. So i may be able to modify it

**Comment by saghul** [comment]
Take a look at AudioMode.m Note that the logic got complex as part of making it more flexible for us to select the preferred device so the change is not a one liner.

**Comment by luismachado** [comment]
@Frindecent I was also looking for a solution for this myself and I think I found one.

Here https://github.com/jitsi/jitsi-meet/blob/5429b8568e0ddb2d352206d219e37111b831e312/ios/sdk/src/AudioMode.m#L97 if I remove the `AVAudioSessionCategoryOptionDefaultToSpeaker ` option the audio calls start with the earpiece. Not only that but if you change between a video call and a AUD call mid-call the audio is also routed accordingly. 

Having said that, I don't know if this leads to any unexpected behaviours further along the line. Maybe @saghul can weigh in on this.

**Comment by saghul** [comment]
Off the top of my head: if you connect or disconnect headphones the code may fallback to using the speaker, I'm not sure. It's possible it ends up being such a simple change, but it also may not.

**Comment by AndaBucsa** [comment]
Is there a way to use the earpiece by default without any code changes to to the SDK (set it via the Public API)?

**Comment by saghul** [comment]
Nope, sorry.
