### ISSUE TITLE
Stopped working online in browsers on Windows XP

### ISSUE THREAD

**Issue by Problema123** [jitsi/jitsi-meet#4665]
Until recently, worked without problems in Firefox 52 esr. Now that this browser is that any other (49 Chrome, Opera 36, Mypal 28.6.1, otter-browser, Firefox esr 52) everywhere just a grey screen and a message that the page fully loaded. I attach screenshots was and became.
![been](https://user-images.githubusercontent.com/55667981/65393122-8e578500-dd85-11e9-8c43-6c81b1920e35.jpg)
![becames](https://user-images.githubusercontent.com/55667981/65393125-944d6600-dd85-11e9-824b-dea322b26e05.jpg)

**Comment by damencho** [comment]
When having problems and questions use the community forum before opening new issues, please.

Generally using Windows XP is not recommended. Also about Firefox support we aim to support the latest ESR which is not 52.
In case of such problems, uploading the js console log is very helpful. What are the errors you see there?

**Comment by Problema123** [comment]
This version of Firefox latest for XP, perhaps I wasn't clear enough, I don't have version 52, my version 52.9.0 (And i have other browsers that listed above, in this Firefox 52.9.0 everything worked fine). I use jitsi meet because I need to communicate with people both with XP and with Win 7-10, and with various Linux

Write what you need from the logs and consoles, just Java and browsers are not my element, but I am a technical specialist but more computer hardware than software.
[js.docx](https://github.com/jitsi/jitsi-meet/files/3640223/js.docx)

![Буфер обмена-154654654654656](https://user-images.githubusercontent.com/55667981/65394993-68d67580-dd9d-11e9-9015-7a49f8feca8e.jpg)

![345435435435345435](https://user-images.githubusercontent.com/55667981/65394970-ef3e8780-dd9c-11e9-86cd-e19e0299ce66.jpg)

**Comment by Problema123** [comment]
> 
> 
> When having problems and questions use the community forum before opening new issues, please.
> 
> Generally using Windows XP is not recommended. Also about Firefox support we aim to support the latest ESR which is not 52.
> In case of such problems, uploading the js console log is very helpful. What are the errors you see there?

i send error log

**Comment by saghul** [comment]
Can you test with ESR 60? According to the Mozilla website it has been out for a while already: https://wiki.mozilla.org/Release_Management/Calendar

Firefox 52, on which your ESR version is based, it's really really old, we can't really support it.

**Comment by Problema123** [comment]
> 
> 
> Can you test with ESR 60? According to the Mozilla website it has been out for a while already: https://wiki.mozilla.org/Release_Management/Calendar
> 
> Firefox 52, on which your ESR version is based, it's really really old, we can't really support it.

More recently, everything worked fine in 52 Firefox. And I pointed out above, 52.9.0 version latest version for Windows XP. So the same meet jitsu does not work in Chrome 49, Opera 36, Mypal 28.6.1 which at the moment is the same latest version for Windows XP, otter-browser is the same thing but there I version not tested. Today I downloaded the update Mypal 28.7.1 as I know he uses the basis of Firefox 60 version, but the online version gives the same error. I asked to check the friend the same with WIndows XP what-to exclude any problems with Java or Internet provider, at the friend precisely the same.

[firefox 60.docx](https://github.com/jitsi/jitsi-meet/files/3642662/firefox.60.docx)

![firefox 60](https://user-images.githubusercontent.com/55667981/65435777-b993b000-de29-11e9-8801-5cd636290ccd.jpg)

**Comment by saghul** [comment]
I'll be blunt: unless it's a simple fix I doubt we can justify spending resources on a platform that is essentially dead. And even if whatever current bug is fixed, it's likely to break soon for other reasons.

**Comment by Problema123** [comment]
> 
> 
> I'll be blunt: unless it's a simple fix I doubt we can justify spending resources on a platform that is essentially dead. And even if whatever current bug is fixed, it's likely to break soon for other reasons.

I partially solved the problem, of all the variety of browsers under XP in the only thing now works, as your project and discord which simply referred to the fact that the browser is not supported (in the entire list of browsers above). It turned out to be Yandex Browser, that's it from him, I did not expect it, it is based on chromium and a little added by programmers Yandex.

![111111111111111](https://user-images.githubusercontent.com/55667981/65443952-b8697f80-de37-11e9-8ba3-40f59596c9bd.jpg)
![234223423423432432434](https://user-images.githubusercontent.com/55667981/65443977-c0292400-de37-11e9-951d-231a1d21ffe4.jpg)

**Comment by saghul** [comment]
Interesting. Glad you got it working!

**Comment by nekr0z** [comment]
FWIW, Jitsi Meet still works in [Maxthon](https://maxthon.com/) under Windows XP. Not that anyone should be still using XP in 2020.

(Originally published at: https://evgenykuznetsov.org/en/reactions/2020/26/)
