### ISSUE TITLE
Audio lost when call multiple time with 2 or more users

### ISSUE THREAD

**Issue by phucnd0604** [jitsi/jitsi-meet#4670]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
We make a call with 2 people by 2 IOS device, after end call then call again in a short time, the conference room open but no audio, event the video is work

## Current behavior
 Audio lost when call multiple time with 2 users

## Expected Behavior
Audio work as normally

## Possible Solution
---

## Steps to reproduce
---

# Environment details
IOS 12.4
Jitsi Meet framework 2.2.0 and 2.3.0

**Comment by saghul** [comment]
Please provide device logs.

**Comment by saghul** [comment]
No follow-up, closing.
