### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by sophiez91** [jitsi/jitsi-meet#4672]
![image](https://user-images.githubusercontent.com/55789411/65592236-7d2d9480-df8e-11e9-9c0b-3b9429f975b9.png)

The other browser I tried to use (edge) won't work either, for some reason it could not access the camera even though I allowed it.

**Comment by damencho** [comment]
Please, when having a question or problem use the community forum before opening new issues.

Which browser and version did you try?

**Comment by damencho** [comment]
Where did you test meet.jit.si?

**Comment by sophiez91** [comment]
sorry, I am new to this type of support and I'm quite inexperienced when it comes to solving this kind of issue. Where could I find this community forum you're talking about? Is it on github or somewhere else?

I used Chrome and Edge, calling in from Amsterdam.

**Comment by damencho** [comment]
The community forum can be found at: https://community.jitsi.org/

When reporting such issues, mention the OS, the browser and its version that was used and the deployment you use, is it meet.jit.si, if not the jitsi-meet version running there.

When creating the issue there is a template which starts with:
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.
