### ISSUE TITLE
I'm getting an internal error when trying to video call in to my coaching circle at ULAB

### ISSUE THREAD

**Issue by dcmatthias** [jitsi/jitsi-meet#4673]
It says InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Media Section has more than one track specified with A=ssrc lines which is not supported...

**Comment by damencho** [comment]
Please, when having a question or problem use the community forum before opening new issues.

Which browser and version did you try?

**Comment by damencho** [comment]
Where did you test meet.jit.si?
