### ISSUE TITLE
Sharing screen takes over 80% of CPU 

### ISSUE THREAD

**Issue by ThomasKientz** [jitsi/jitsi-meet#4679]
## Description
When sharing my screen (all screen or just a window), my computer becomes very very slow. In the activity monitor I can see CPU usage of "WindowServer" process taking over 80%.

## Environment details
MAC OS 10.14.6
2,9 GHz Intel Core i5
Rocket Chat 2.15.5 (don't know which Jitsi version it uses)

Any ideas why it slows down my computer so much ?

**Comment by damencho** [comment]
Please, when having problems or questions use the community forum before opening new issues.

There is nothing we can do about screen sharing, other than setting the frame rate. It is set to something reasonable for screensharing, currently is something like 5 frames per second.
The screen sharing is totally a browser thing and different browsers have different implementations, so this another thing you can try, change the browser. Chrome in its latest few versions have some optimizations about the screensharing video, while Firefox's implementation is rather simple, I think, just encodes and sends it as regular capture ... the difference is that camera feed is in small resolution up to 720p or 1080p where desktop can go a lot above 1080p and this takes a lot of cpu to encode and send ...
