### ISSUE TITLE
 On the line break of chat displays the tag <br>

### ISSUE THREAD

**Issue by stephenstephen** [jitsi/jitsi-meet#4681]

**Comment by saghul** [comment]
Where do you see this, web or mobile? Can you provide a screenshot?

**Comment by stephenstephen** [comment]
I type * Beginning * and after I make Shift + Enter 4 times and finish with * End *

![Capture d’écran de 2019-10-04 13-57-49](https://user-images.githubusercontent.com/34239158/66206079-4b63ae80-e6af-11e9-85a1-f0cf8145f24f.png)

![Capture d’écran de 2019-10-04 13-57-53](https://user-images.githubusercontent.com/34239158/66206085-53235300-e6af-11e9-803b-ce8f67177caf.png)

**Comment by stephenstephen** [comment]
it's on the web

**Comment by saghul** [comment]
@zbettenbuk @damencho maybe either of you can take a look when you have some sapare cycles?

**Comment by stephenstephen** [comment]
Is there any news for this problem?

**Comment by saghul** [comment]
Not that I'm aware of.

**Comment by saghul** [comment]
@zbettenbuk can you PTAL?
