### ISSUE TITLE
Jitsi calling  is not working with mobile data network. 

### ISSUE THREAD

**Issue by pushpsenairekar2911** [jitsi/jitsi-meet#4686]
The new version of Jitsi mobile is not working with the mobile data network.  We have tested it on Android and iOS. 

## Description
The new version of Jitsi mobile is not working with the mobile data network.  We have tested it on Android and iOS. 

## Current behavior
Calling not working

## Expected Behavior
Calling should work.

## Possible Solution
---

## Steps to reproduce
Turn off. the Wifi. 
Switch on the Mobile data. 
Call another user.

# Environment details
Xcode 11. iOS 13.

**Comment by saghul** [comment]
Are you using the version in the store? Or did you build your own?

**Comment by pushpsenairekar2911** [comment]
I've built my own.  We have tested with the sample on the AppStore and there it is working properly.

**Comment by saghul** [comment]
Have you made any changes? The current store build is built off the `mobile-19.3` branch with no changes.

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by BlueOwlet** [comment]
still happening though

**Comment by saghul** [comment]
The original issue was about the mobila app, not the mobile web browser. Please open a new issue if you are experiencing problems with the mobile web version.
