### ISSUE TITLE
JitsiMeetSDK 2.3.2 Android has an error with netinfo

### ISSUE THREAD

**Issue by djorkaeffalexandre** [jitsi/jitsi-meet#4689]
We tried to use JitsiMeetSDK 2.3.2 on Android and when we start a call has the follow error:
```
java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/chat.rocket.reactnative-Cfn4SGkBvJro4AVjjDc1YA==/base.apk!classes2.dex)
```
This error is from react-native-community/netinfo.

JitsiMeetSDK 2.4 Android works fine!! <3 thanks!

Waiting your update on gradle.

**Comment by jc-delvalle** [comment]
same issue

**Comment by saghul** [comment]
Do you know what version of netinfo includes the fix? I don't recall updating that dependency.

**Comment by jc-delvalle** [comment]
It seems to be version 61 of react native. Version 61 has different interface for WritableMap, which expects String,ReadableMap instead of String,WritableMap. Downgrading to RN 60 worked for me.

**Comment by saghul** [comment]
master (2.4) does indeed have RN 0.61. @djorkaeffalexandre what RN version does RocketChat use?

**Comment by djorkaeffalexandre** [comment]
We use RN 0.61 and 2.4 worked nice!!

**Comment by saghul** [comment]
Yeah, so due to the RN breakage you need to use master for the time being. Until we release a 2.4 SDK that is. I'll see if we can speed things up though.

**Comment by saghul** [comment]
Android SDK 2.4.0 is now out, with uses RN 0.61 so this should be fixed!
