### ISSUE TITLE
Current session breaks when user on other computer joins (runing locally docker-jitsi-meet)

### ISSUE THREAD

**Issue by paulvi** [jitsi/jitsi-meet#4692]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

Current session breaks when user on other computer joins.

I am trying out Jitsi meet using
https://github.com/jitsi/docker-jitsi-meet

It starts OK, but when opening the room on other computer (regardless Chrome or Firefox), 
UI breaks,
there is non descriptive error and restart in 15 seconds

---

## Current behavior
---

![image](https://user-images.githubusercontent.com/1614482/65829228-8ba0e680-e2d5-11e9-9310-a5fc036c017c.png)

## Expected Behavior
---

No errors, can see conference of 2 people.

## Possible Solution
---

## Steps to reproduce
---

Running docker on Mac,  
starting new room with short name `abc` from Chrome or Firefox.  
Then open /abc on other PC

# Environment details
---

The same LAN network, two laptops Mac 10.14.6 and Windows 10 using WiFi

**Comment by saghul** [comment]
What does the JS console show?

**Comment by TechnicLab** [comment]
CONFERENCE FAILED: conference.videobridgeNotAvailable on quick install on Debian 10. It works for some time after server restart.

**Comment by saghul** [comment]
@TechnicLab The OP is using the Docker setup, not the quick install. If the server doesn't stay up, please open a new issue so we can help troubleshoot it.

**Comment by paulvi** [comment]
@saghul
Should be separate issue to make UI message more exact, instead of "something",
and give option to stop timer.

**Comment by saghul** [comment]
Yes, please create a new issue for the UI improvements and let's close this one.

**Comment by paulvi** [comment]
Why close this one? It is not solved in any ways ?!

UI improvement for error situation is #4743

**Comment by paulvi** [comment]
@saghul It seems like you have not raise separate issue for 
quick install on Debian 10 case.

The reason may be different.

Please reference this issues.

**Comment by saghul** [comment]
Oops, I mixed up the 2 users. Can you paste your JS console output then?

**Comment by Entretoize** [comment]
Can you reopen, I have the same issue on debian 10 ?

**Comment by saghul** [comment]
Please open a new issue, but first check the closed ones, check for DOCKER_HOST_ADRESS and JVB_STUN_SERVERS usage.

**Comment by Entretoize** [comment]
Where ? I don't find documentation

**Comment by Entretoize** [comment]
Sorry it's not the same issue I'm not using docker
