### ISSUE TITLE
Jitsi leaves call without google services

### ISSUE THREAD

**Issue by cvoges12** [jitsi/jitsi-meet#4693]
### Description

Jitsi fails a call when no google services are installed. Call works properly until app switcher or home screen is used on android. The application is fine while on the app or when screen goes to sleep. Also, the notification menu does not close / leave the call. However, the application never crashes. It simply does not stay on call when the application should be sent to background.

### Replication

To replicate, remove all google services or use android open project (or any other fork) without google services installed. Join a Jitsi call. Then switch to a new app or hit the home button. The call with fail but the application will not crash.

### Possibly Related / Fixes

#4106 #4155 #1290

**Comment by saghul** [comment]
I have no way to test this, I'm afraid. Can you please take the logcat output when this happens and paste it in a gist?

Are you running a custom build with the LIBRE_BUILD compile time var set?

**Comment by saghul** [comment]
No follow-up, closing.
