### ISSUE TITLE
https://meet.jit.si/ not working on Waterfox 56 (based on FX 56)

### ISSUE THREAD

**Issue by rorya** [jitsi/jitsi-meet#4696]
I'll just make a reference to the bug report about this on the Waterfox project bug tracker: https://github.com/MrAlex94/Waterfox/issues/1176

**Comment by rorya** [comment]
Worth noting, the site and its features worked fine with v56, within the last 2 months. So it sounds like something has changed on the jitsi-meet codebase which is making it not load properly on WF 56. Thanks.

**Comment by rorya** [comment]
I'll go ahead and add the error I'm seeing in the Waterfox 56 console here, for quick reference:

TypeError: r.map is not a function[Learn More]  functions.js:27:28
	<anonymous> functions.js:27:28
	<anonymous> functions.js:20
	n bootstrap:19
	<anonymous> reducer.js:27:15
	n bootstrap:19
	<anonymous> actions.js:20:66
	n bootstrap:19
	<anonymous> index.js:67:12
	n bootstrap:19
	<anonymous> actions.js:17:8
	n bootstrap:19
	<anonymous> AuthHandler.js:1
	<anonymous> AuthHandler.js:1
	n bootstrap:19
	<anonymous> connection.js:1
	<anonymous> connection.js:1
	n bootstrap:19
	<anonymous> conference.js:1
	<anonymous> conference.js:1
	n bootstrap:19
	<anonymous> index.js:109
	n bootstrap:19
	<anonymous> bootstrap:83
	<anonymous> https://web-cdn.jitsi.net/meetjitsi_3613.341/libs/app.bundle.min.js:1:2

**Comment by saghul** [comment]
We only support Firefox > ESR, which is at version 60 now.
