### ISSUE TITLE
Call aborted

### ISSUE THREAD

**Issue by mt131** [jitsi/jitsi-meet#4700]
I have dialog show that:
http://prntscr.com/pd9ldh
Call aborted
There's already another call in progress. Please end it first and try again.

2019-10-01 16:02:16.002 25521-25541/net.jitsi.sdktest E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-10-01 16:02:16.004 25521-25521/net.jitsi.sdktest E/Minikin: Could not get cmap table size!
2019-10-01 16:02:34.444 25521-25676/net.jitsi.sdktest E/BufferQueueProducer: [] Can not get hwsched service
2019-10-01 16:02:36.059 25521-25521/net.jitsi.sdktest E/JitsiMeetSDK: JitsiConnectionService onCreateOutgoingConnectionFailed DCB5DD8D-A7E5-437A-9FF1-D840262A4B1A
2019-10-01 16:02:36.663 25521-25684/net.jitsi.sdktest E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
2019-10-01 16:02:36.815 25521-25614/net.jitsi.sdktest E/JitsiMeetSDK: [modules/statistics/AnalyticsAdapter.js] Required field missing (containerId, containerType, objectId or objectType)
2019-10-01 16:02:36.815 25521-25614/net.jitsi.sdktest E/JitsiMeetSDK: [modules/statistics/AnalyticsAdapter.js] Dropping a mis-formatted event: {"type":"track","action":"unpinned","actionSubject":"participant","objectType":"participant","attributes":{"participant_count":1},"source":"unpinned","containerType":"conference"}
2019-10-01 16:02:41.925 25521-25614/net.jitsi.sdktest E/com.amplitude.api.AmplitudeClient: Argument context cannot be null in initialize()

**Comment by saghul** [comment]
This happens when there is another call in progress when you try to start a Jitsi Meet call.

**Comment by mt131** [comment]
How to avoid this? It happen many time

**Comment by saghul** [comment]
I see you are using the SDK. When starting the second call, are you certain you properly closed the first one?

**Comment by mt131** [comment]
public class MainActivity extends FragmentActivity implements JitsiMeetActivityInterface {
    private JitsiMeetView view;

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data) {
        JitsiMeetActivityDelegate.onActivityResult(
                this, requestCode, resultCode, data);
    }

    @Override
    public void onBackPressed() {
        JitsiMeetActivityDelegate.onBackPressed();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        view = new JitsiMeetView(this);
        JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
            .setRoom("https://meet.jit.si/test123")
            .build();
        view.join(options);

        setContentView(view);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        view.dispose();
        view = null;

        JitsiMeetActivityDelegate.onHostDestroy(this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

    @Override
    public void onRequestPermissionsResult(
            final int requestCode,
            final String[] permissions,
            final int[] grantResults) {
        JitsiMeetActivityDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onResume() {
        super.onResume();

        JitsiMeetActivityDelegate.onHostResume(this);
    }

    @Override
    protected void onStop() {
        super.onStop();

        JitsiMeetActivityDelegate.onHostPause(this);
    }
}

is this sample ok, i call view.leave(); to end call

**Comment by mt131** [comment]
in the library who work well i see it difference:
public class JitsiMeetActivity extends FragmentActivity implements JitsiMeetActivityInterface, JitsiMeetViewListener {
    protected static final String TAG = JitsiMeetActivity.class.getSimpleName();
    private static final String ACTION_JITSI_MEET_CONFERENCE = "org.jitsi.meet.CONFERENCE";
    private static final String JITSI_MEET_CONFERENCE_OPTIONS = "JitsiMeetConferenceOptions";

    public JitsiMeetActivity() {
    }

    public static void launch(Context context, JitsiMeetConferenceOptions options) {
        Intent intent = new Intent(context, JitsiMeetActivity.class);
        intent.setAction("org.jitsi.meet.CONFERENCE");
        intent.putExtra("JitsiMeetConferenceOptions", options);
        context.startActivity(intent);
    }

    public static void launch(Context context, String url) {
        JitsiMeetConferenceOptions options = (new Builder()).setRoom(url).build();
        launch(context, options);
    }

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.setContentView(layout.activity_jitsi_meet);
        if (!this.extraInitialize()) {
            this.initialize();
        }

    }

    public void onDestroy() {
        this.leave();
        if (AudioModeModule.useConnectionService()) {
            ConnectionService.abortConnections();
        }

        JitsiMeetOngoingConferenceService.abort(this);
        super.onDestroy();
    }

    public void finish() {
        this.leave();
        super.finish();
    }

    protected JitsiMeetView getJitsiView() {
        JitsiMeetFragment fragment = (JitsiMeetFragment)this.getSupportFragmentManager().findFragmentById(id.jitsiFragment);
        return fragment.getJitsiView();
    }

    public void join(@Nullable String url) {
        JitsiMeetConferenceOptions options = (new Builder()).setRoom(url).build();
        this.join(options);
    }

    public void join(JitsiMeetConferenceOptions options) {
        this.getJitsiView().join(options);
    }

    public void leave() {
        this.getJitsiView().leave();
    }

    @Nullable
    private JitsiMeetConferenceOptions getConferenceOptions(Intent intent) {
        String action = intent.getAction();
        if ("android.intent.action.VIEW".equals(action)) {
            Uri uri = intent.getData();
            if (uri != null) {
                return (new Builder()).setRoom(uri.toString()).build();
            }
        } else if ("org.jitsi.meet.CONFERENCE".equals(action)) {
            return (JitsiMeetConferenceOptions)intent.getParcelableExtra("JitsiMeetConferenceOptions");
        }

        return null;
    }

    protected boolean extraInitialize() {
        return false;
    }

    protected void initialize() {
        this.getJitsiView().setListener(this);
        this.join(this.getConferenceOptions(this.getIntent()));
    }

    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        JitsiMeetActivityDelegate.onActivityResult(this, requestCode, resultCode, data);
    }

    public void onBackPressed() {
        JitsiMeetActivityDelegate.onBackPressed();
    }

    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        JitsiMeetConferenceOptions options;
        if ((options = this.getConferenceOptions(intent)) != null) {
            this.join(options);
        } else {
            JitsiMeetActivityDelegate.onNewIntent(intent);
        }
    }

    protected void onUserLeaveHint() {
        this.getJitsiView().enterPictureInPicture();
    }

    public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {
        JitsiMeetActivityDelegate.requestPermissions(this, permissions, requestCode, listener);
    }

    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        JitsiMeetActivityDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    public void onConferenceJoined(Map<String, Object> data) {
        JitsiMeetLogger.i("Conference joined: " + data, new Object[0]);
        JitsiMeetOngoingConferenceService.launch(this);
    }

    public void onConferenceTerminated(Map<String, Object> data) {
        JitsiMeetLogger.i("Conference terminated: " + data, new Object[0]);
        this.finish();
    }

    public void onConferenceWillJoin(Map<String, Object> data) {
        JitsiMeetLogger.i("Conference will join: " + data, new Object[0]);
    }
}

**Comment by mt131** [comment]
because i want to custom layout and add some view

**Comment by saghul** [comment]
Then you need to Mae sure you do the things the activity does: add a view listener and finish your activity in the onConferenceTerminated event.
