### ISSUE TITLE
Getting issue Could not find module 'JitsiMeet' for target 'x86_64-apple-ios-simulator'; found: arm64 when build using Xcode 11 

### ISSUE THREAD

**Issue by jeetkapadia** [jitsi/jitsi-meet#4701]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
The issue when I am trying to build the framework by using Xcode 11 then after adding it in my project I am getting the above error which is 
> Could not find module 'JitsiMeet' for target 'x86_64-apple-ios-simulator'; found: arm64
Please let me know how can I fix this.

## Current behavior
---Not able to work with simulators in XCode but when build using a generic or real device.

## Expected Behavior
---The framework should work when ran m project in simulator

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Closing in favor of https://github.com/jitsi/jitsi-meet/issues/4666 as the main "Xcode 11 issues" task.

**Comment by ratnesh-ahead** [comment]
<img width="272" alt="Screenshot 2019-12-08 at 12 00 19 PM" src="https://user-images.githubusercontent.com/54057685/70385950-c2236d80-19b8-11ea-92f7-6a32054f187d.png">
The issue when I am trying to build the framework by using Xcode 11 then after adding it in my project I am getting the above error Please help me
