### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by ankathiriya** [jitsi/jitsi-meet#4706]
![Screenshot 2019-10-03 at 3 48 30 PM](https://user-images.githubusercontent.com/22503223/66119010-6376f780-e5f5-11e9-9a63-c29e471d33d8.png)

Could you please check above issue I'm facing issue in Xcode 11.

**Comment by saghul** [comment]
Please look into the open issues before opening a new one. See https://github.com/jitsi/jitsi-meet/issues/4666
