### ISSUE TITLE
Enable Hungarian language

### ISSUE THREAD

**Issue by gyuris** [jitsi/jitsi-meet#4710]
I translated Jitsi Meet to Hungarian (hu) with Pootle server: https://translate.jitsi.org/hu/jitsi-meet/ It is 100% ready. I ask fot enabling it in https://meet.jit.si

**Comment by damencho** [comment]
Please use community forum for queries like this before opening new issues.

Will update it soon. Thank you m

**Comment by damencho** [comment]
@gyuris I had updated the templates and there are few left to translate ... you can beat me before committing it.

**Comment by gyuris** [comment]
Thanks. Done.
