### ISSUE TITLE
Crash when another user joins

### ISSUE THREAD

**Issue by TechnicLab** [jitsi/jitsi-meet#4725]
## Description
---
Jitsi meet crashes when there are 2 or more users in a conference.
## Current behavior
---
Crashes and tries to reconnect.

## Expected Behavior
---
No crashes
## Possible Solution
---
Restart Jitsi meet
## Steps to reproduce
---
Install Jitsi meet using Quick install method.
Wait approximately 5-6 hours.
2 users should join 1 conference.
# Environment details
---
Jitsi meet installed with quick install on Debian 10
https://paste.ubuntu.com/p/hXh74y8dJm/
https://paste.ubuntu.com/p/GKyxzSpqCz/

**Comment by damencho** [comment]
Please, when having questions or problems use the community forum before opening new issues.

> CONFERENCE FAILED: conference.videobridgeNotAvailable

Seems your bridge is not running or has a problem, attach its logs for further analysis.

**Comment by TechnicLab** [comment]
https://transfer.sh/15Ttya/jvb.log

**Comment by damencho** [comment]
I don't see a problem with jvb. Can you upload and the jicofo logs.

**Comment by TechnicLab** [comment]
https://transfer.sh/ZxnYc/jicofo.log

**Comment by damencho** [comment]
The jicofo log for `Health check failed on` is from Jicofo 2019-10-08 13:48:57.986, where the jvb log ends at JVB 2019-10-08 13:48:50.219, it either crashed or you haven't sent the complete log including the moment it failed healthcheck. 

What is the machine you are running jvb and jicofo, does it have at least 8GB of RAM?

**Comment by TechnicLab** [comment]
Monitored logs on the host side. Videobridge was killed by OOM due to the lack of RAM in container. Fixed, thank you for help.
