### ISSUE TITLE
Jitsi Meet Unmute of Remote Participants No longer working

### ISSUE THREAD

**Issue by kcooi** [jitsi/jitsi-meet#473]
In newer Jitsi Meet, I noticed that a moderator not able to unmute back participant.
The 'muted' option of that particular participant become grey-out/disabled, once it has muted.

But the older jitsi Meet version is working fine. A moderator can mute/unmute a participant.
Is it expected?

**Comment by bgrozev** [comment]
If it was possible in older versions, it was a bug. It constitutes a privacy issue (if someone is able to unmute your mike without your knowledge/approval).
