### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by ankathiriya** [jitsi/jitsi-meet#4731]
![Screenshot 2019-10-10 at 6 47 02 PM](https://user-images.githubusercontent.com/22503223/66572451-9fc6cc80-eb8e-11e9-9be7-abdecab8c64e.png)

**Comment by ankathiriya** [comment]
![Screenshot 2019-10-10 at 6 49 40 PM](https://user-images.githubusercontent.com/22503223/66572522-bcfb9b00-eb8e-11e9-84ac-896148979d85.png)

**Comment by saghul** [comment]
You are using Xcode 11, right? The current SDK is compiled with Xcode 10, so if you need Swift 5.1 you must compile the SDK yourself until we release a new version.

**Comment by ankathiriya** [comment]
@saghul any idea when we will have latest version supported with Xcode 11?

**Comment by saghul** [comment]
Soon :-) Xcode 11 is already supported on master, we just need to release a new SDK with it.

**Comment by ankathiriya** [comment]
okay @saghul thanks for your help.

**Comment by NeenaMishra12** [comment]
Hi @saghul ,
When can we expect the release of a new SDK?
Is there any update on this?

**Comment by saghul** [comment]
I’m expecting to release an updated SDK as soon as next week.

**Comment by saghul** [comment]
iOS SDK 2.4.0 is now out.
