### ISSUE TITLE
Jitsi Video calling view is green

### ISSUE THREAD

**Issue by SkyProjects007** [jitsi/jitsi-meet#4737]
## Description

Hello Guys
       I have developed Jitsi audio and video calling and audio calling is implement..but i am facing issue in jitsi video calling time..calling time display color green why? i have try another example and check but same issue faceing please solve my issue ASAP and my sdk using in jitsi ..

SDK:-
implementation('org.jitsi.react:jitsi-meet-sdk:2.2.2') { transitive = true }

Thanks in advance

**Comment by saghul** [comment]
Can you please update to 2.3.2? Also, does the sample app exhibit the problem for you? https://github.com/jitsi/jitsi-meet-sdk-samples

**Comment by SkyProjects007** [comment]
Hello @saghul 

         Thanks for your feedback..and finally its working now..Great

**Comment by saghul** [comment]
Glad I could help!
