### ISSUE TITLE
Local Recording not work

### ISSUE THREAD

**Issue by stephenstephen** [jitsi/jitsi-meet#4744]

**Comment by stephenstephen** [comment]
![Capture d’écran de 2019-10-14 15-02-02](https://user-images.githubusercontent.com/34239158/66753239-a48fc700-ee93-11e9-80d2-ee541444e875.png)
No response for *Start Recording*

**Comment by damencho** [comment]
any error in the console?

**Comment by damencho** [comment]
And please use the community forum before opening new issues.

**Comment by stephenstephen** [comment]
![Capture d’écran de 2019-10-14 15-28-35](https://user-images.githubusercontent.com/34239158/66754967-64324800-ee97-11e9-8e7e-088e38d59e30.png)

**Comment by damencho** [comment]
My french is not so good :) but isn't that a notification that there is no access to your microphone?

**Comment by stephenstephen** [comment]
Yes, I do not have a microphone and webcam, but recording with dropbox works well even without microphone and webcam

**Comment by stephenstephen** [comment]
Does the local recording need microphone and webcam to work?

**Comment by damencho** [comment]
The recording to dropbox is done on another machine, I think for this one you need as this is a local recording from your microphone, if there is no mic where will it get the input from. 
This feature records locally and the other participants do the same and then send the initiator the files which he then can combine.

**Comment by stephenstephen** [comment]
OK thanks a lot

**Comment by stephenstephen** [comment]
Even with a microphone, there is no answer :(

**Comment by stephenstephen** [comment]
VM32:37 [features/local-recording] <e.start.then.catch.e>:  Failed to start local recording. undefined

**Comment by damencho** [comment]
These needs more debugging, cannot give you any advice at the moment.
Are you trying to start it when there is more than one participant in the room?

**Comment by stephenstephen** [comment]
I tested on two participants

**Comment by rjimmya777** [comment]
Hi, I also have the same problem, I can not record the video locally in my laptop,

**Comment by damencho** [comment]
Local recording is audio-only.

**Comment by stephenstephen** [comment]
Is that so.
But in my case, even the audio does not work, there is no response on click the link Start recording.

**Comment by rjimmya777** [comment]
Same for me, voice recording does not work :(

**Comment by damencho** [comment]
Hey, @ztl8702 can you take a look?

**Comment by ztl8702** [comment]
@damencho  
I think the code for local recording might have eroded over time -- because I didn't write tests for it. But I will take a look within this week.

**Comment by damencho** [comment]
Thanks

**Comment by stephenstephen** [comment]
Thanks

**Comment by ztl8702** [comment]
So I just tested locally (built from master) with macOS 10.15 and Chrome 77.0.3865.120, and local recording works for me.

@stephenstephen  Can you provide more details: your browser version, OS version, and which version of jitsi-meet you were running (was it self-deployed or using the public server?)

**Comment by stephenstephen** [comment]
I'm using Chrome Version 71.0.3578.98 on Ubuntu 18.04.1 LTS with https://meet.jit.si/

**Comment by ztl8702** [comment]
And how did you override config.js to enable local recording? Was it by embedding meet.jit.si in an iframe and setting `configOverwrite`?

**Comment by stephenstephen** [comment]
**Here is my source code**

```

const domain = 'meet.jit.si';
const options = {
    roomName: 'Meeting25',
    parentNode: document.querySelector('#meet'),
    onload : function(e){
        //
    },
    interfaceConfigOverwrite: {
        SETTINGS_SECTIONS: [ 'devices', 'language', 'calendar'],
        TOOLBAR_BUTTONS: [
            'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
            'fodeviceselection', 'profile', 'chat',
            'etherpad', 'settings', 'raisehand',
            'videoquality', 'filmstrip', 'feedback',
            'tileview', 'localrecording',  'recording'
        ]
    },
    configOverwrite: {
         localRecording: {
             enabled: true,
         },
         fileRecordingsServiceEnabled: true,
         fileRecordingsEnabled: true,
     },
    
};
```

**Comment by rasos** [comment]
Localrecording works here. As mentioned above, it records only your own audio track. This should be probably explained in the recording dialog box before starting it.

**Comment by SushantGautam** [comment]
Same problem here even you use public Jitsi server.
