### ISSUE TITLE
toolbar camera button is blocked by more options

### ISSUE THREAD

**Issue by sntk** [jitsi/jitsi-meet#4749]
## Description

Embedding Jitsi below 540px width makes it impossible to enable/disable the camera as the 'More Actions' container overlaps it.

## Current behavior

When you mouse over the camera toggle button, I'm unable to click on it. button-group-right is overlapping button-group-center.

![Oct-14-2019 18-09-45](https://user-images.githubusercontent.com/951859/66786741-7c15c600-eeaf-11e9-8524-c263de7fb32f.gif)

---

## Expected Behavior

I should be able to turn on/off camera regardless of the width I'm using.

---

## Possible Solution

For `.button-group-left` `.button-group-center` and `.button-group-right` replace `width: 33%;` with `max-width: 33%;`

---

## Steps to reproduce

Follow instructions here: https://www.taskade.com/v/KdCnUQUJkfeWaUTp

---

# Environment details
Any supporting browser.

**Comment by saghul** [comment]
Ping @hristoterezov

**Comment by hristoterezov** [comment]
@sntk would you be able to open a PR with the fix?

**Comment by virtuacoplenny** [comment]
Haven't tested thoroughly but removing this line might fix it: https://github.com/jitsi/jitsi-meet/blob/8a3ddd8596e6ffabf9882275f7edd457c49437a8/css/_toolbars.scss#L71. Not sure why the width was ever set; hopefully it was an oversight.

**Comment by saghul** [comment]
@hristoterezov can you PTAL at this again?
