### ISSUE TITLE
Can we disable more option in calling view

### ISSUE THREAD

**Issue by ankathiriya** [jitsi/jitsi-meet#4755]
![Screenshot 2019-10-16 at 2 14 50 PM](https://user-images.githubusercontent.com/22503223/66903393-0846fb00-f020-11e9-9d1e-f84e50d5746a.png)

Wants to disable this option.let me know if we have any solution for this.

**Comment by saghul** [comment]
That's the "overflow menu" Without it you can't switch to low bandwidth mode, or change your devices, FYI. There is no setting to disable it, you'll need to compile the code yourself and remove: https://github.com/jitsi/jitsi-meet/blob/a35099f949f80b35befc1f7b366e6e464becec93/react/features/toolbox/components/native/Toolbox.js#L179
