### ISSUE TITLE
jitsi-meet make error!!!   cp: cannot stat ‘node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js’: No such file or directory

### ISSUE THREAD

**Issue by java-programmer** [jitsi/jitsi-meet#4760]
I copied the 4040 release from github jitsi-meet, then used NPM install and finally use  make   an error.
cp: 无法获取"node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map" 的文件状态(stat): 没有那个文件或目录
make: *** [deploy-lib-jitsi-meet] 错误 1
please help me!

**Comment by damencho** [comment]
Please, when having problems or questions use the community forum before creating new issues.

Seems lib-jitsi-meet did not install. Did you get any error on npm install step, maybe share npm install output?
What is your OS, and npm version you use?

**Comment by java-programmer** [comment]
centos7.6   npm version: 6.4.1
lib-jitsi-meet  already install! but is no lib-jitsi-meet.min.js!

**this is npm install output:**
[root@localhost qlndvc-meet]# npm install
npm WARN lifecycle jitsi-meet@0.0.0~postinstall: cannot run in wd jitsi-meet@0.0.0 jetify (wd=/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet)
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/inline-dialog@5.3.0 requires a peer of react-dom@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/layer@2.9.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@2.4.1 requires a peer of react@15.6.0 - 16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.61.1 requires a peer of react@16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-native-community/cli@3.0.0-alpha.2 requires a peer of react-native@^0.60.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 83510 packages in 53.954s
found 2391 vulnerabilities (3 low, 2 moderate, 2384 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

if i use make,  the error:
[root@localhost qlndvc-meet]# make dev
rm -fr libs
mkdir -p libs
./node_modules/.bin/node-sass css/main.scss css/all.bundle.css && \
./node_modules/.bin/cleancss css/all.bundle.css > css/all.css ; \
rm css/all.bundle.css
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:786:3)
    at Object.getInstalledBinaries (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/extensions.js:130:13)
    at foundBinariesList (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
rm: 无法删除"css/all.bundle.css": 没有那个文件或目录
make: *** [deploy-css] 错误 1

**and if i use make dev, the error:**

./node_modules/.bin/webpack -p
Hash: 518d77356418e370d61528098305ed429701bc0d7aacbde3c128e3d24c119392aa1417c0b8aa3287783626dc07234fea7f440e88298b3b78c38cf5909c70cd61a95392c77a584910b6b9b320196c4c24939739a047bb3af95a82eb1f6cf5a5df780a7447
Version: webpack 4.26.1
Child
    Hash: 518d77356418e370d615
    Time: 114760ms
    Built at: 2019-10-17 18:48:12
                 Asset      Size  Chunks             Chunk Names
     app.bundle.min.js  2.66 MiB       0  [emitted]  app.bundle
    app.bundle.min.map  9.71 MiB       0  [emitted]  app.bundle
    Entrypoint app.bundle = app.bundle.min.js app.bundle.min.map
     [10] ./react/features/analytics/index.js + 20 modules 44.2 KiB {0} [built]
          | ./react/features/analytics/index.js 106 bytes [built]
          | ./react/features/analytics/AnalyticsEvents.js 21.9 KiB [built]
cp \
	node_modules/rnnoise-wasm/dist//rnnoise.wasm \
	libs
cp \
	node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js \
	node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map \
	node_modules/lib-jitsi-meet//connection_optimization/external_connect.js \
	node_modules/lib-jitsi-meet//modules/browser/capabilities.json \
	libs
cp: 无法获取"node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map" 的文件状态(stat): 没有那个文件或目录
make: *** [deploy-lib-jitsi-meet] 错误 1

**Comment by java-programmer** [comment]
the centos7.6  use root user!!!

**Comment by damencho** [comment]
Try first make and then make dev.

**Comment by java-programmer** [comment]
**I first make, but  error!**
root@localhost qlndvc-meet]# make dev
rm -fr libs
mkdir -p libs
./node_modules/.bin/node-sass css/main.scss css/all.bundle.css &&
./node_modules/.bin/cleancss css/all.bundle.css > css/all.css ;
rm css/all.bundle.css
fs.js:115
throw err;
^

Error: ENOENT: no such file or directory, scandir '/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/vendor'
at Object.readdirSync (fs.js:786:3)
at Object.getInstalledBinaries (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/extensions.js:130:13)
at foundBinariesList (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/errors.js:45:5)
at module.exports (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/binding.js:15:30)
at Object. (/usr/local/src/qlndvc/qlndvc-front/qlndvc-meet/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
rm: 无法删除"css/all.bundle.css": 没有那个文件或目录
make: *** [deploy-css] 错误 1

**Comment by java-programmer** [comment]
**I first make, but error  output:**
/node_modules/.bin/webpack -p
Hash: 518d77356418e370d61528098305ed429701bc0d7aacbde3c128e3d24c119392aa1417c0b8aa3287783626dc07234fea7f440e88298b3b78c38cf5909c70cd61a95392c77a584910b6b9b320196c4c24939739a047bb3af95a82eb1f6cf5a5df780a7447
Version: webpack 4.26.1
Child
Hash: 518d77356418e370d615
Time: 114760ms
Built at: 2019-10-17 18:48:12
Asset Size Chunks Chunk Names
app.bundle.min.js 2.66 MiB 0 [emitted] app.bundle
app.bundle.min.map 9.71 MiB 0 [emitted] app.bundle
Entrypoint app.bundle = app.bundle.min.js app.bundle.min.map
[10] ./react/features/analytics/index.js + 20 modules 44.2 KiB {0} [built]
| ./react/features/analytics/index.js 106 bytes [built]
| ./react/features/analytics/AnalyticsEvents.js 21.9 KiB [built]
cp
node_modules/rnnoise-wasm/dist//rnnoise.wasm
libs
cp
node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js
node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map
node_modules/lib-jitsi-meet//connection_optimization/external_connect.js
node_modules/lib-jitsi-meet//modules/browser/capabilities.json
libs
cp: 无法获取"node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map" 的文件状态(stat): 没有那个文件或目录
make: *** [deploy-lib-jitsi-meet] 错误 1

**I dont't find lib-jitsi-meet.min.js  in  node_modules/lib-jitsi-meet !!!!    How is lib-jitsi-meet-min.js generated?**

**Comment by warmachine7733** [comment]
i am also facing the same issue ,have someone resloved it???

**Comment by warmachine7733** [comment]
my os is win10

**Comment by saghul** [comment]
We don't support building on Windows.

**Comment by warmachine7733** [comment]
okay

**Comment by abhishek7737** [comment]
I am having the same issue

**Comment by zhoumh1988** [comment]
I am having the same issue
