### ISSUE TITLE
I need help removing few buttons from video screen in android

### ISSUE THREAD

**Issue by maheshgelani** [jitsi/jitsi-meet#4763]
TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection', 'hangup', 'profile', 'recording',
        'livestreaming', 'etherpad', 'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
        'tileview', 'videobackgroundblur'
    ]

our server guy removed few options from interface_config.js , in the above toolbar buttons but did not get any change at the android side.

Do we miss anything after changing it

**Comment by damencho** [comment]
Please use the community forum for questions like this before opening new issues, thank you.

Mobile does not use interface config, you need code changes to remove buttons.

**Comment by maheshgelani** [comment]
ok sure
