### ISSUE TITLE
Not able to compile with XCode 11.2 Beta 

### ISSUE THREAD

**Issue by jeetkapadia** [jitsi/jitsi-meet#4765]
Hi,

I am trying to build the Jitsi framework with XCode 11.2 beta2 version and I am getting this error:

`Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.1 compiler: /Users/JEET/Desktop/CometChatProSDKRepo/cometchat-pro-ios-sdk/CometChatSDK/CometChatPro/Vendors/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64.swiftmodule`

Can you please let me know how can I fix the above issue. 

Also, I am thankful for all your help.

**Comment by saghul** [comment]
Looks like Apple has once again updated the Swift version. You'll have to compile the SDK yourself with thet same Xcode version.
