### ISSUE TITLE
how to auto close mobile app after the call end in android applciation 

### ISSUE THREAD

**Issue by SkyCoders007** [jitsi/jitsi-meet#4772]
how to auto close mobile app after the call end in android applciation 

I'm integrating the app to my messaging system and I would like the jitsi mobile to close itself after the call end in stead of going back to the welcome page.

Any idea where I should look/change?

**Comment by saghul** [comment]
Sorry, this fell through the cracks. You can add your code in the `conferenceTerminated` listener on the activity.
