### ISSUE TITLE
JitsiMeetView not open while internet is slow in ios app

### ISSUE THREAD

**Issue by kharpodiya** [jitsi/jitsi-meet#4779]
I am working on an ios application with jitsimeet SDK 2.4.0.  Everything is fine, but JitsiMeetView is taking 3-5 minutes to appear on the screen when the internet is very slow and I am trying to make audio or video calls.  And for the time the application is hanging.

**Comment by kharpodiya** [comment]
Not solved

**Comment by saghul** [comment]
I guess you solved it?

**Comment by kharpodiya** [comment]
yes

**Comment by Aizaz-Abbasi** [comment]
how did you solve it can you please let me know
