### ISSUE TITLE
Audio call start with main speaker instead of ear speaker.

### ISSUE THREAD

**Issue by kharpodiya** [jitsi/jitsi-meet#4780]
Every time when I'm joining the conference that is audio only, the default audio speaker is main speaker. But I want to start the audio only call  with ear speaker as default audio.
Is there any way to do this..?

**Comment by richardhrace** [comment]
yes, you can do it.

**Comment by saghul** [comment]
@kharpodiya YOu need to explicitly select the arpiece device on every call. We default to the speaker and this is done on purpose.
