### ISSUE TITLE
Breakout rooms

### ISSUE THREAD

**Issue by balejos** [jitsi/jitsi-meet#4787]
**Is your feature request related to a problem you are facing?**
I would like to facilitate sessions which include seamless administration of breakout rooms 

**Describe the solution you'd like**
I would like to choose the number of participants per room and the time of the breakout will last. Then, the participants are randomly distributed to the new rooms for the time chosen. When the time is up, the participants are automatically redirected to the initial room.

**Comment by ece106** [comment]
I would like this too.

**Comment by saghul** [comment]
This sounds like something that an application using our iframe API would implement. We don't provide any room administration capabilities (except for setting up password, but I wouldn't say that qualifies) and this is intentional. Since we can't cover all use-cases, we try to provide the tools for developer to do so.

In this case, you could build an admin portal that generates random room names and privdes that facility by using the iframe API to direct users to the room of your choice: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

**Comment by balejos** [comment]
Thanks Saúl for the clear explanation of jitsi's scope and kudos that well-documented API

**Comment by rasos** [comment]
@balejos did you start any activities building an admin tool for breakout rooms?

**Comment by balejos** [comment]
No, @rasos, I'm sorry but I don't currently have the bandwidth

**Comment by ildr3him** [comment]
Yes Please. This is the last and only reason I am still using Zoom :)

**Comment by diamondin** [comment]
Same with me! I would strongly prefer jitsi over Zoom, but we need breakout sessions (as many other in these times).

**Comment by jtakalai** [comment]
> @balejos did you start any activities building an admin tool for breakout rooms?

I think it would be better to direct these requests to all of https://jitsi.org/built-on-jitsi/ which are commercial products(?) built on top of jitsi. Since non-basic features are not in scope for the FOSS solution, there might be interest in the products to develop those. They all want to beat Zoom.

**Comment by sbargon** [comment]
Hey, great news. Someone has done this now and build break out rooms on top of Jitsi. Check out https://www.videofacilitator.com/

**Comment by alexanderadam** [comment]
> Someone has done this now and built break out rooms on top of Jitsi.

This doesn't seem to help any of the self hosting users here as [this seems to be a proprietary service](https://www.videofacilitator.com/pricing). Or did I misunderstand this?

**Comment by sbargon** [comment]
> > Someone has done this now and built break out rooms on top of Jitsi.
> 
> This doesn't seem to help any of the self hosting users here as [this seems to be a proprietary service](https://www.videofacilitator.com/pricing). Or did I misunderstand this?

I'd contact them, and ask, they might be open to licensing it or something. https://www.videofacilitator.com/contact-us

**Comment by happyhenry99** [comment]
But Video Facilitator is twice the price of Zoom. What features does it have that are missing from Zoom?

**Comment by jtakalai** [comment]
> But Video Facilitator is twice the price of Zoom. What features does it have that are missing from Zoom?

I guess relevantly it's built on top of Jitsi? They don't give credit (BOO!) but clearly it is. They have [a "tour" feature](https://meet.videofacilitator.com/join/futour/) where you can check it out.

This is hardly the place for discussing the relative merits of two proprietary services, though, is it? If there are FOSS products with breakout rooms that you know of (that build on top of Jitsi preferably), please link them here.

**Comment by rasos** [comment]
@jtakalai BigBlueButton has breakout rooms. Requires installation on Ubuntu 16.04 (18.04 and Docker are WIP).

**Comment by Grietje143** [comment]
> Hey, great news. Someone has done this now and built break out rooms on top of Jitsi. Check out https://www.videofacilitator.com/

I tried to use it, but for several reasons it didn't work. Staff of videofacilitator is friendly, and offered to figure it out. But well, at this moment I am still stuck with zoom😖

**Comment by joaoaguiam** [comment]
you can also check-out https://app.veertly.com we have deployed yesterday the breakout feature rooms on top of jitsi :)

**Comment by alexanderadam** [comment]
Oh nice! You even made [the source free](https://github.com/veertly/app#introduction). :tada: 

Are you planning to add a Docker image on docker hub ([like Jitsi](https://hub.docker.com/u/jitsi/)) and a documentation how to get it running fast and easy?

**Comment by JayHoltslander** [comment]
Just arrived here while researching to see if Jitsi had breakout room capability.

**Comment by etuardu** [comment]
@joaoaguiam I see that your implementation does not cover the use case of Zoom, where the host can send the participants to breakout rooms, broadcast messages to every breackout rooms, move them back to the main conversation and so on (check the Zoom's video tutorial here: https://www.youtube.com/watch?v=jbPpdyn16sY ). Or did I miss something?

**Comment by joaoaguiam** [comment]
@alexanderadam We are not using docket so that is not possible. We are hosting on firebase and using their services.

@etuardu Yes you are right, we don't have an automatic distribution of the participants to the different rooms, but more leave this decision to the participant on which room or with which person do they want to talk to. Regarding broadcast messages and moving them back to the main room, this is in our roadmap but not yet implemented.

**Comment by alexanderadam** [comment]
> We are not using docket so that is not possible.

Well, you wouldn't have to use it by yourself. You just have to have a `Dockerfile` and a CI/GitHub action that bundles all dependencies.
However, nobody can self-host this anyway if it is relying on Firebase. :disappointed:

**Comment by puthli** [comment]
We are working on breakout rooms and other tools on top of Jitsi meet. Our use case is group facilitators and trainers. We were in the EuVsVirus hackathon last week and have since fleshed out the prototype we made.

Last week we had our first trial users and they were quite satisfied.
At some point we will need to make this a paid service to fund the server hosting, but for now its open for everyone here to use: www.wurk.app

Comments and suggestions are welcome!

**Comment by alexanderadam** [comment]
> We are working on breakout rooms and other tools on top of Jitsi meet.

Will you open the source as well? [The current "source code" link points to jitsi.org](https://www.wurk.app/en/#beveiliging).

**Comment by puthli** [comment]
Yes that is my intention, but we first need to clean up the source code made in the hackathon. Right now i think no-one would be able to read the source or get it running. Deployment is further complicated by requiring a self hosted server, for which we need to bundle the deployment scripts; in docker for example. And i need to work out how to make the web server configuration with Jitsi meet easy to set up; maybe with docker compose. Right now it's too hard and requires many manual steps.

**Comment by alexanderadam** [comment]
> Yes that is my intention

This is _great_ news!

> […] we need to bundle the deployment scripts; in docker for example

You are thinking of a Docker image? This is even better! :+1: 

> i need to work out how to make the web server configuration with Jitsi meet easy to set up; maybe with docker compose

You probably know about the official `docker-compose.yml` of Jitsi already, right?

Thank you for those news! Please highlight me, when this project is available on GitHub/GitLab so that I can give a star and follow it.

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5550

**Comment by scheepers** [comment]
> Yes that is my intention, but we first need to clean up the source code made in the hackathon. Right now i think no-one would be able to read the source or get it running. Deployment is further complicated by requiring a self hosted server, for which we need to bundle the deployment scripts; in docker for example. And i need to work out how to make the web server configuration with Jitsi meet easy to set up; maybe with docker compose. Right now it's too hard and requires many manual steps.

THAT'S AMAZING!
Please, this looks awesome. If you make it available already, maybe people can help you with that!

**Comment by aspiers** [comment]
I have attempted to summarise all known Jitsi-based solutions for breakout rooms in this new wiki page:

https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms

Please help me make it accurate and comprehensive - thanks!

**Comment by putt1ck** [comment]
@puthli if there's anything we can do to help, just say.

**Comment by heikar** [comment]
Hi @puthli ,

there are news about the deployment of the solution?
If you need support (e.g. for testing), so let me know.

Many greetings
heikar

**Comment by gtilflm** [comment]
> 
> 
> Yes that is my intention, but we first need to clean up the source code made in the hackathon. Right now i think no-one would be able to read the source or get it running. Deployment is further complicated by requiring a self hosted server, for which we need to bundle the deployment scripts; in docker for example. And i need to work out how to make the web server configuration with Jitsi meet easy to set up; maybe with docker compose. Right now it's too hard and requires many manual steps.

Hi @puthli.  How close are you to making your work on this open source?  Could use it in a project that is starting in a few weeks.  Thanks!!

**Comment by pierreozoux** [comment]
@puthli we can help on the docker side.

For the code, it is up to you of course.
But if you need a bit of money to help cleaning the code, we can discuss, and I'm sure here some people would love to come and chip in! How much would you need to put this on the priority list?

If we can help you clean the code, then you just publish as it is, and sure some people will help on the docker (us) and on the instructions to run it!

We need this! :)

Thanks for your feedback!

**Comment by gtilflm** [comment]
@puthli: Would be happy to contrib. assuming it will end up doing what I need it to do.

@pierreozoux: Are you doing development for this feature, or just hoping it happens?  I have a project in the works that will need breakout rooms and would be down for a collaborative effort assuming we're of the same mind on what needs to be done.

**Comment by aspiers** [comment]
The wiki page for breakout rooms solutions has now [been moved](https://community.jitsi.org/t/edit-access-for-jitsi-jitsi-meet-wiki-was-removed/71402/5) into the [official handbook](https://jitsi.github.io/handbook/docs/community/breakout-rooms), so anyone can submit PRs to [the `breakout-rooms.md` file](https://github.com/jitsi/handbook/blob/master/docs/community/breakout-rooms.md).

**Comment by puthli** [comment]
Just started a public repo on https://github.com/puthli/breakout-rooms
I moved the installation scripts away from our AWS specific installations scripts and did not have time to test yet, so mileage may vary. But all the ingredients are there.

Any help on setting up the open source process is welcome.

**Comment by aspiers** [comment]
Thanks @puthli.  Please consider submitting a PR as per my previous comment.
