### ISSUE TITLE
[iOS] Issues trying to build jitsiMeet.framework

### ISSUE THREAD

**Issue by chenBingGuo** [jitsi/jitsi-meet#4789]
I am trying to build the jitsi-meet framework for iOS. use Xcode:10.1

When I execute in the root jitsi-meet directory:
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

It throws:

    export WATCHKIT_SUPPORT_FOLDER_PATH=/Users/bingo/Library/Developer/Xcode/DerivedData/jitsi-meet-ebaidvspurcwncbetbnogzlmvuio/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/WatchKitSupport
    export WRAPPER_EXTENSION=framework
    export WRAPPER_NAME=JitsiMeet.framework
    export WRAPPER_SUFFIX=.framework
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=10B61
    export XCODE_VERSION_ACTUAL=1010
    export XCODE_VERSION_MAJOR=1000
    export XCODE_VERSION_MINOR=1010
    export XPCSERVICES_FOLDER_PATH=JitsiMeet.framework/XPCServices
    export YACC=yacc
    export arch=arm64
    export diagnostic_message_length=80
    export variant=normal
    /bin/sh -c /Users/bingo/Library/Developer/Xcode/DerivedData/jitsi-meet-ebaidvspurcwncbetbnogzlmvuio/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/bingo/Desktop/jitsi-meet': Is a directory
WebRTC framework has NO bitcode
../scripts/bitcode.sh: line 12: /Users/bingo/Desktop/jitsi-meet: is a directory

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Bitcode /Users/bingo/Library/Developer/Xcode/DerivedData/jitsi-meet-ebaidvspurcwncbetbnogzlmvuio/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh
(1 failure)

**Comment by saghul** [comment]
Oops, this fell through the cracks. You can use this script to get a build with bitcode: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/downloadBitcode.sh
