### ISSUE TITLE
Xcode 11.0 - Issue running SDK into iOS Project (Symbol not found)

### ISSUE THREAD

**Issue by luismachado** [jitsi/jitsi-meet#4790]
I'm having some issues running the SDK into my iOS Project.

I managed to build it and import it correctly and it does run on a device. However, when I try to build the project for the simulator I get the following error:

`dyld: Symbol not found: __ZdaPv
  Referenced from: /Users/luismachado/Library/Developer/CoreSimulator/Devices/5CF3CDA6-179F-4861-8017-809435123593/data/Containers/Bundle/Application/490EDCC8-FC09-4995-8765-8E035FEB0516/Rocket.Chat.app/Frameworks/JitsiMeet.framework/JitsiMeet
  Expected in: /Users/luismachado/Library/Developer/CoreSimulator/Devices/5CF3CDA6-179F-4861-8017-809435123593/data/Containers/Bundle/Application/490EDCC8-FC09-4995-8765-8E035FEB0516/Rocket.Chat.app/Frameworks/WebRTC.framework/WebRTC
 in /Users/luismachado/Library/Developer/CoreSimulator/Devices/5CF3CDA6-179F-4861-8017-809435123593/data/Containers/Bundle/Application/490EDCC8-FC09-4995-8765-8E035FEB0516/Rocket.Chat.app/Frameworks/JitsiMeet.framework/JitsiMeet`

I was running my own version of Jitsi's SDK but I already tried a version straight from your repo and got the same error.

PS: I'm using the fat library (created by running the xcodebuild command that you suggest).

Any ideas? Thanks!

**Comment by luismachado** [comment]
Two additional notes:

1) The issue happens on both Xcode 10 and 11
2) I went through the commits and found out that the issue started happening after https://github.com/jitsi/jitsi-meet/commit/598b6f05984eff9122aeb6290f9ecb81efde2cd1

**Comment by saghul** [comment]
That's really strange. How are you integrating the SDK? Are you using the WebRTC framework provided by our Pod or a different one?

**Comment by renji-xx** [comment]
Same error for me as well. I pulled your latest release code from branch and build using ./scripts/release-sdk.sh.

Used generated JitsiMeet.framework(fat) and webrtc framework from your side.

**Comment by saghul** [comment]
> It's strange that the issue only occurred when deploying to a simulator and not on a real device though.

Not really, different symbols are used because they use different architectures. Glad we figured it out!

**Comment by kanchan2mj** [comment]
I am facing same error.
Downloaded WebRTC from jitsi released SDK and generated jitsi framework using xcode 11.  When I try to run app on simulator I get this error

dyld: Symbol not found: __ZdaPv
  Referenced from: /Users/me/Library/Developer/CoreSimulator/Devices/DA70F87E-1E98-4413-A68A-B6470D706E96/data/Containers/Bundle/Application/DE92E68C-493A-48D9-BDCD-594C41997909/myapp.app/Frameworks/JitsiMeet.framework/JitsiMeet

Can someone please help me on this

**Comment by HariNarayanan777** [comment]
Getting this same while running in simulator with Xcode 11.5. I tried so many ways to solve this 
clear the derived data and run again, and regenerate the sdk once again.

can someone find the issue and solve that please inform the proper steps to follow to short it out please...

**Comment by raghadsoliman** [comment]
Any help Please ?

**Comment by Brumor** [comment]
+1
