### ISSUE TITLE
怎么运行Jitsi Meet源码，我不想直接安装我需要二次开发，请问你们连个运行源码的文档都没有吗？

### ISSUE THREAD

**Issue by liuhuan543539666** [jitsi/jitsi-meet#4793]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.
怎么运行Jitsi Meet源码，我不想直接安装我需要二次开发，请问你们连个运行源码的文档都没有吗？

**Comment by JustGogoing** [comment]
朋友最后你咋跑起来的
