### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by liuhuan543539666** [jitsi/jitsi-meet#4795]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master> npm install
npm WARN tarball tarball data for react-native@0.61.1 (sha512-FjOhAgzjrPr2BjBITmCY+SHzWxfP/bv5ve3oN6ItoIPsVPjJG2QZE8yeByVdI4TzaZrGHU4Ag7/7hX4j39cj2Q==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTAnimationDriver.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTDecayAnimation.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTDecayAnimation.m'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTEventAnimation.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTEventAnimation.m'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTFrameAnimation.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTFrameAnimation.m'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTSpringAnimation.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\react-native-b5dfff11\Libraries\NativeAnimation\Drivers\RCTSpringAnimation.m'
npm WARN tarball tarball data for flow-bin@0.104.0 (sha512-EZXRRmf7m7ET5Lcnwm/I/T8G3d427Bq34vmO3qIlRcPIYloGuVoqRCwjaeezLRDntHkdciagAKbhJ+NTbDjnkw==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\source-map-601e4dfb\dist\source-map.debug.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\terser-d7c580a4\tools\props.html'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\terser-d7c580a4\dist\bundle.min.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\core.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\es2015.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\experimental.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\flow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\jsx.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\misc.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\placeholders.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\typescript.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-498987b7\lib\definitions\utils.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib\modifications\appendToMemberExpression.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib\modifications\inherits.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib\modifications\prependToMemberExpression.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib\modifications\removeProperties.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib\modifications\removePropertiesDeep.js'
npm WARN tarball tarball data for bc-css-flags@3.0.0 (sha1-OJWiPppx+VgE6u8V8WXVG5rV4hM=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-98bada1e\lib\validators\react\isCompatTag.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-98bada1e\lib\validators\react\isReactComponent.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-98bada1e\lib\validators\validate.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-141bb934\lib\validators\react'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-79a204a8\scripts\utils\formatBuilderName.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-79a204a8\scripts\utils\lowerFirst.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-79a204a8\scripts\utils\stringifyValidator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-79a204a8\scripts\utils\toFunctionName.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-a768455d\lib\validators\generated\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-141bb934\lib\validators\react\isCompatTag.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-141bb934\lib\validators\react\isReactComponent.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Liuhuan\Downloads\jitsi-meet-master\jitsi-meet-master\node_modules\.staging\@babel\types-141bb934\lib\validators\validate.js'
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/react-native-webrtc/react-native-webrtc.git C:\Users\Liuhuan\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-f5ef78d4\.git --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\Liuhuan\AppData\Local\Temp\pacote-git-template-tmp\git-clone-eb638da3
npm ERR! fatal: read error: Invalid argument

**Comment by saghul** [comment]
Building on Windows is not supported, sorry.

**Comment by wuriyanto48** [comment]
same problem here, when build inside docker container
