### ISSUE TITLE
Follow redirects in android app when providing room URL

### ISSUE THREAD

**Issue by patcon** [jitsi/jitsi-meet#4801]
Hi there! Thanks for all the work that you do on this app :)

This is the tiniest feature request is terms of priority, but thought I'd log it anyhow.

**Is your feature request related to a problem you are facing?**
Very tiny inconvenience of app trying to process a redirected link as a `https://<server url>/<room>`

**Describe the solution you'd like**
When offering a link like https://link.hypha.coop/calls, would be nice if the app recognized the redirect and instead parsed info from final URL.

**Describe alternatives you've considered**
Being more explicit with instructions, so people know to only use mobile app via the "resolved" url. (We use a redirect so that our docs don't need updating if we switch underlying room or servers.)

**Comment by saghul** [comment]
Hi there, thanks for the kind words!

The only thing that comes to mind would be to add an extra "room resolution" step wich performs a HEAD request to resolve the URL.

This shouldn't be too hard to do. Are you up for writing a PR? I can provide some guidance.

**Comment by saghul** [comment]
Hey, thanks for willing to help out!

The fix needs to happen in JS, which is where the URL is actually handled. Specifically around here: https://github.com/jitsi/jitsi-meet/blob/5429b8568e0ddb2d352206d219e37111b831e312/react/features/app/actions.js#L43

Basicallt, before we process the URL, we'd do the HEAD request thing and update it.

**Comment by patcon** [comment]
Ok cool, and do you use any special http client libs, or just XMLHttp​Request?

**Comment by saghul** [comment]
You should be able to use `fetch` which is available since we polyfill it, when it's not.
