### ISSUE TITLE
iOS video call screen not switch nicely to landscape mode after rotate phone

### ISSUE THREAD

**Issue by xsoul** [jitsi/jitsi-meet#4802]
## Description
iOS: During a video call, whenever you switch from portrait mode to a landscape mode, the screen will not rotate nicely accordingly.

## Steps to reproduce
Open a video call, flip your iphone from portrait to landscape, the screen become as the attached image.

![cordova-jitsi-plugin-screen-rotate-issue](https://user-images.githubusercontent.com/5644701/67842301-dad87200-fb34-11e9-8b65-ae1a09599f9f.jpeg)
## Expected Behavior
Screen should rotate according to phone ratio.

# Environment details
iOS: v13.1.2

 iOS SDK: 2.4

**Comment by saghul** [comment]
I see you are using the SDK. The JitsiMeetView is just like another view, on which the SDK draws on, so you need to take care of setting the layout constraints you want. Looks like you are splitting the screen to displahy 2 views?

**Comment by xsoul** [comment]
Hi Saghul. Thanks for quick reply. Yes, I'm using jitsi-meet-ios-sdk with cordova plugin  (https://github.com/jitsi/jitsi-meet-ios-sdk-releases), FYI, I'm not splitting the screen to display 2 views. What i did is just calling the cordova plugin which calling the SDK with the code as below:

`- (void)loadURL:(CDVInvokedUrlCommand *)command {
    NSString* url = [command.arguments objectAtIndex:0];
    NSString* key = [command.arguments objectAtIndex:1];
    NSString* jwt = [command.arguments objectAtIndex:2];
    commandBack = command;
    
    jitsiMeetView = [[JitsiMeetView alloc] initWithFrame:self.viewController.view.frame];
    jitsiMeetView.delegate = self;
    
    // Join the room.
    JitsiMeetConferenceOptions *options
    = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
        builder.room = key;
        builder.serverURL = [NSURL URLWithString:url];
        builder.token = jwt;
        builder.subject = @" ";
        builder.welcomePageEnabled = NO;
        [builder setFeatureFlag:@"chat.enabled" withBoolean:NO];
        
    }];
    [jitsiMeetView join:options];
    [self.viewController.view addSubview:jitsiMeetView];
}`

The Android working fine with the landscape screen mode.

**Comment by saghul** [comment]
I'd venture it's a bug on the Cordova plugin, which doesn't set the view bounds / layout correctly.

**Comment by xsoul** [comment]
May I know which part i should set the view bounds/layout at the iOS native code which i share above? Thanks!

**Comment by saghul** [comment]
I don't know, that's part of what the Cordova plugin does, and depends if it's using a controller or not. I suggest you open an issue on their repo.

**Comment by xsoul** [comment]
Hi saghul, I managed to solve this issue by modifying the cordova plugin iOS native code, so i will close this issue for now.

Thanks!
