### ISSUE TITLE
Android app disconnects immediately

### ISSUE THREAD

**Issue by AndriiZ** [jitsi/jitsi-meet#4805]
## Description
I have own self-hosted installation with Letsencrypt cert

Certificate is valid

I can connect to Jitsi meeting from different browsers. 

I am triing to connect to Jitsi meeting from Android app and immediately received

You have been disconnected....

# Environment details
Ubuntu 19.10
Android 8.0

**Comment by damencho** [comment]
Please, when having problems or questions post them in the community forum before opening new issues.

Have you tried using it with the browser? What is your experience there? Do you see any js console errors?

**Comment by AndriiZ** [comment]
Have you tried using it with the browser? What is your experience there? Do you see any js console errors?
====

As I mentioned in description, 

I can connect to Jitsi meeting from different browsers.

**Comment by AndriiZ** [comment]
@damencho Please dont close issue immediately without even looking into 

Have you tried using it with the browser? What is your experience there? Do you see any js console errors?
====
Yes, I tested in different browsers without any issues and have issue only with Android app

**Comment by saghul** [comment]
Do you get any certificate warnings in your Android phone if you open the site with the mobile browser? You can check if the cert chain is configured correctly in your server with this: https://whatsmychaincert.com

**Comment by AndriiZ** [comment]
I have a valid letsencrypt certificate 
https://i.postimg.cc/XvmYtYFn/photo-2019-10-31-15-46-39.jpg

**Comment by saghul** [comment]
Can you paste your config file? Also, any chance you could capture the adb logcat when you try to connect?

**Comment by AndriiZ** [comment]
Which one?

**Comment by saghul** [comment]
config.js, sorry.

**Comment by AndriiZ** [comment]
did not touch it, but may attach if you want

One thought - Jitsi uses 443 port (was free), but port 80 is occupied by nginx. Can it be root cause?

**Comment by saghul** [comment]
It would help to see it.

You are using the https:// URL when you try to join, right?

**Comment by kondratuka7** [comment]
[up.zhuk.xyz-config.js.zip](https://github.com/jitsi/jitsi-meet/files/3794188/up.zhuk.xyz-config.js.zip)

**Comment by AndriiZ** [comment]
[up.zhuk.xyz-config.js.zip](https://github.com/jitsi/jitsi-meet/files/3794195/up.zhuk.xyz-config.js.zip)

**Comment by AndriiZ** [comment]
I have a wildcard certificate for *.zhuk.xyz, so I can create any local domains

**Comment by saghul** [comment]
Yes, but the DNS name cannot be resolved. How long ago have you set that up? Maybe it hasn't propagated yet.

Here is my output:

```
dig up.zhuk.xyz @8.8.8.8

; <<>> DiG 9.10.6 <<>> up.zhuk.xyz @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 1440
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;up.zhuk.xyz.			IN	A

;; AUTHORITY SECTION:
zhuk.xyz.		1799	IN	SOA	amy.ns.cloudflare.com. dns.cloudflare.com. 2032325432 10000 2400 604800 3600

;; Query time: 66 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Oct 31 15:32:09 CET 2019
;; MSG SIZE  rcvd: 101
```

**Comment by AndriiZ** [comment]
I have a local dns server, so propagation is not an issue 

![screenshot_82](https://user-images.githubusercontent.com/820269/67956245-6d901400-fbfc-11e9-8462-536fc81f65b3.png)

**Comment by saghul** [comment]
Does the Android device use the same resolver?

At this stage I'd need to see the `adb logcat` output from Android, since I cannot test it myself.

**Comment by AndriiZ** [comment]
ok, probably Jitsi uses some other nameserver

I am connected to my internal network using OpenVPN, and name resolving in browsers (on Android) working fine, but probably Jitsi resolves names from wifi dns but not from OpenVPN dns

**Comment by saghul** [comment]
That would explain, yeah. We use the standard HTTP libraries provided by React Native, which is `okhttp` on Android. I don't think there is much we can do here, sorry.

**Comment by AndriiZ** [comment]
@saghul Temporarily exposed up.zhuk.xyz into Internet  - but error is the same (browser works fine). You can connect and confirm
