### ISSUE TITLE
module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/xgf/Desktop/cw/Third/JitsiMeet/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule

### ISSUE THREAD

**Issue by Insfgg99x** [jitsi/jitsi-meet#4807]
module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/xgf/Desktop/cw/Third/JitsiMeet/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule

Env : Xcode 11.2

**Comment by kharpodiya** [comment]
> module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/xgf/Desktop/cw/Third/JitsiMeet/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule
> 
> Env : Xcode 11.2

Manually compile the SDK with code 11.2

**Comment by saghul** [comment]
SDK 2.4.0 has been compiled with Xcode 11.1. If you need to use a higher Xcode version you must compile the SDK yourself, or wait until we update it in a future SDK release.

**Comment by Rylaa** [comment]
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.0 compiler: /Users/XXX/Desktop/xxx/swift-pip/JitsiSDKTest/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64.swiftmodule
