### ISSUE TITLE
How Can I Change Default Language On Android SDK?

### ISSUE THREAD

**Issue by arrow-zh** [jitsi/jitsi-meet#4816]
I have integrated jitsi meet into my android project. Everything works correctly, now I want the Chinese language by default. Please help me how to do it? my phone language also Chinese.

**Comment by saghul** [comment]
The default language (if available) is selected to match that of the system. If we don't support said language, Engligh is used instead.

There is currently no way to force a language in the SDK.

What version of the SDK are you using? We have supported Chinese for a while IIRC.

**Comment by mt131** [comment]
i want to force to japan too

**Comment by saghul** [comment]
Do we support Japanese on the web?
