### ISSUE TITLE
Jitsi meet not connecting

### ISSUE THREAD

**Issue by sandeeppatilhg** [jitsi/jitsi-meet#4817]
Hi, 
We have installed jitsi meet at our data center. The application was working fine and in the last couple of days when we try to connect it keeps hopping to the page "trying to connect" which comes with progress bar. We tried the jitsi meet demo - meet.jitsi.org, we see the same issue there. Kindly advise on the issue.

Regards
Sandeep

**Comment by saghul** [comment]
Do you see any errors on the JavaScript console?

**Comment by sandeeppatilhg** [comment]
No we do not see any error logs. When we try to connect, it connects and disconnects and keeps trying to reconnect.

**Comment by saghul** [comment]
There must be something. Please put the full log in a gist for inspection.

**Comment by sandeeppatilhg** [comment]
Hi 
I saw an error about the conference video bride now, so I tried to restart all the service and it worked. thank you.
Do we need to restart the service every few days.?

But I didn't understand why this error occurred. the error looked something like this on the site.

![error](https://user-images.githubusercontent.com/54399220/68202722-3baaf300-ffea-11e9-8a30-f70063b0caba.png)

**Comment by damencho** [comment]
Restart is not normal. Most probably the error in the js console was showing that there is no bridge, coming from jicofo. There should be a message in jicofo logs when the bridge was removed from the pool, and you need to check and jvb logs at that time to see what was the error and why it happen.
Do you have at least 8 GB of RAM for the machine running jicofo and jvb?

**Comment by sandeeppatilhg** [comment]
Ho ok. I understood the situation now, we currently have only 4 GB RAM. then, in this case, we need to scale to at least 8GB.

Thank you so much for the solution.

**Comment by damencho** [comment]
Anyway check your logs for out of memory errors, to make sure that is the case.
