### ISSUE TITLE
audioManager not work in huawei

### ISSUE THREAD

**Issue by mt131** [jitsi/jitsi-meet#4826]
audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);                
         audioManager.setSpeakerphoneOn(true);

these code work on other device but not in huawei P10 lite android 8.0.0

and how to select the sound device programmablly

**Comment by saghul** [comment]
What are you trying to do? Jitsi Meet takes care of this automatically. We don't use those APIs on Android >= Oreo (8) because we use ConnectionService by default.

**Comment by mt131** [comment]
http://prntscr.com/ptlwli
my screen is look like above. 
the jitsi voice call view is invisible.
so i tap in the red frame button to switch the sound device.
do you know how to do it in java

**Comment by saghul** [comment]
Our audio device handling on Android is here: https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java and here (for ConnectionService): https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerConnectionService.java

If you are mixing the Jitsi Meet SDK and other audio management things are not going to go well.

Please use the forum for these questions though: https://community.jitsi.org/
