### ISSUE TITLE
(iOS) Building with xcode 10.3 fails with "Invalid bitcode version" error 

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#4834]
Hi guys,

Just did a fresh git clone and am able to build the app to test directly on an iPhone XR running 12.4. without issues.

But when I try to then archive the app it fails to build with this error:

ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1100.0.33.8.0_0' Reader: '1001.0.46.4_0')', using libLTO version 'LLVM version 10.0.1, (clang-1001.0.46.4)' for architecture armv7

I'm running 10.14.5 Mojave, xcode 10.3, npm 6.9.0 and node 12.1.0

Anyone else experiencing this problem?

Cheers

**Comment by saghul** [comment]
We have updated to Xcode 11 and Xcode 10 is no longer being tested. Chances are something broke along the way... can you try updating?

**Comment by pdarcos** [comment]
Thanks @saghul 

I was hoping to avoid updating to 11 as long as possible.
I'm going to setup a dual xcode 10 and 11 environment and will report back results.

Cheers

**Comment by saghul** [comment]
11.2.1 seems to work fine, FWIW. In case it helps, we use https://github.com/xcpretty/xcode-install to keep multiple versions side by side on our CI.

**Comment by pdarcos** [comment]
Yup. Confirmed it builds fine on 11.2.1

Thanks

**Comment by CodeBunny786** [comment]
Hey HI @pdarcos @saghul   i am facing the same issue or Archive on xcode 10.3 any quik solution please Thanks

**Comment by saghul** [comment]
I'll be looking at this today, but no promises.

**Comment by CodeBunny786** [comment]
Hey @saghul can i have to upgrade my xcode to  11.2.1 ?? stucked  here for 3 days Please let me know the solution Thanks mate

**Comment by pdarcos** [comment]
Hi @CodeBunny786 
Yes update to 11.2.1 and all should work again.

**Comment by saghul** [comment]
I have found the issue. It's bitcode related 😢 Turns out we also need to be able to compile with Xcode 10 in addition to 11. I hope to have a fix ready today.

**Comment by saghul** [comment]
Ok, found the problem. You must disable bitcode because the google SDK is compiled with Xcode 11 and contains incompatible bitcode.

In https://github.com/jitsi/jitsi-meet/pull/4850 I fixed compiling the SDK.

If you want to compile the app you'd have to disable bitcode yourself and remove the watchOS app since bitcode is mandatory in that case.
