### ISSUE TITLE
[macOS] productivity: add jitis-meet URL to calendar event

### ISSUE THREAD

**Issue by c-alpha** [jitsi/jitsi-meet#4835]
**Is your feature request related to a problem you are facing?**
I was looking for a way to generate sufficiently unique jitsi-meet URLs so I can store them in appointments in macOS's calendar app. This is inspired by how the jitsi mobile app can add links to iOS calendar appointments.

**Describe the solution you'd like**
As there is no need for a dedicated jitsi-meet app on macOS, I wanted to add the functionality to Apple's calendar app. That does not have a plugin interface, however. What I hence ended up with, is the attached automator workflow [Add Jitsi Meet.workflow.zip](https://github.com/jitsi/jitsi-meet/files/3827389/Add.Jitsi.Meet.workflow.zip). When editing an new appointment, right click the "Add URL" field, and select "Add Jitsi Meet" from the pop-up (see screen shot). This will insert a meet.jit.si link with a 32-bit random number as the meeting id. I wanted to make this work with a vanilla OS install, so restricted myself to tools that are shipped with the OS. Generating a diceware id (like the website does) would have required installing extras.

<img width="343" alt="Screenshot 2019-11-09 at 15 41 59 " src="https://user-images.githubusercontent.com/2213269/68530323-8937a080-0307-11ea-8c4c-05b63d306656.png">

Please feel free to flame me for this out-of-scope contribution. But if you do, please be sure to also point me to where I should have contributed this instead. 

**Describe alternatives you've considered**
This doesn't really fit here, since it's about an integration outside the scope of this repo. But I didn't really know where else to put it.

**Comment by c-alpha** [comment]
No views anyone?

**Comment by saghul** [comment]
Hey Alexander, sorry this fell through the cracks. TBH I'm not sure where we could put this. We have worked on integrations with Google Calendar and Office 365, which we can integrate on the web, but this requires the user to download and install this "plugin". I really appreciate the effort, I'm just not sure how we could show users it exists.

**Comment by c-alpha** [comment]
> [...] I'm just not sure how we could show users it exists.

I guess that's the core of the issue. I could make it available here as a repo, and point to it from my website. But that's probably not a location Jitsi Meet users will typically be looking at.

If I made it a GitHub repo, would you perhaps consider an "honourable mention" at the end of `jitsi-meet/doc/integrations.md`? Or perhaps new `jitsi-meet/doc/third-paty-integrations.md`?

**Comment by laudaksg** [comment]
Thanks, @c-alpha for this script and idea. Works like charm. Although changing it to a static, unique Jitsi link makes it easier to use with the Jitsi desktop app.

**Comment by c-alpha** [comment]
laudaksg ***@***.***> writes:

> Thanks, @c-alpha for this script and idea. Works like charm. Although
> changing it to a static, unique Jitsi link makes it easier to use with
> the Jitsi desktop app.

@laudaksg, many thanks for the warm words; glad you found it useful!

I designed it for a different use-case, though. I wanted a unique
different link for each call, since I share the link up front with other
participants, and wanted to avoid unwanted participants popping into my
confidential conversations. ;-)

Changing the code to generate a constant URL should be trivial, I think.
I have however changed my email setup [1], and thus am now using elisp
inside Emacs to generate the links.

[1] https://www.condition-alpha.com/blog/?p=1792

**Comment by MaximGretsev** [comment]
> As there is no need for a dedicated jitsi-meet app on macOS, I wanted to add the functionality to Apple's calendar app. That does not have a plugin interface, however. What I hence ended up with, is the attached automator workflow [Add Jitsi Meet.workflow.zip](https://github.com/jitsi/jitsi-meet/files/3827389/Add.Jitsi.Meet.workflow.zip).

Thank you so much, @c-alpha for this realization 
I love it

**Comment by devilmark84** [comment]
Is it possible to add into the "add meeting link" context menu, inside the event creation popup? Next to the "Facetime" icon...

**Comment by saghul** [comment]
No, you need a plugin like the one linked earlier in this thread.

**Comment by devilmark84** [comment]
Ok but I can't find any plugin linked earlier...

**Comment by saghul** [comment]
Isn't that what this plugin did? https://github.com/jitsi/jitsi-meet/files/3827389/Add.Jitsi.Meet.workflow.zip

**Comment by saghul** [comment]
Then I don't know, sorry.

**Comment by c-alpha** [comment]
> No, I'm talking about this menu.
> 
> <img alt="Image" width="453" src="https://private-user-images.githubusercontent.com/1248444/426134618-c8e64bd4-a9c0-4172-bae9-131b32005d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI4NTQ5MjUsIm5iZiI6MTc0Mjg1NDYyNSwicGF0aCI6Ii8xMjQ4NDQ0LzQyNjEzNDYxOC1jOGU2NGJkNC1hOWMwLTQxNzItYmFlOS0xMzFiMzIwMDVkMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjRUMjIxNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY5OWEwYWNmMzI2MzI3YjkwYjY4M2E1MGZhODNjZmJkYjNiODU5NzBiOWIxNTAwNzQ3YjE2YTc5OTA0MmJjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1yPRCTi3038yquYGf9yOLjTkGjnAMR8sWQfvR03PKK0">

Not even installed videoconf apps (like for example Zoom) appear in this drop-down menu. I would thus assume that Apple have not yet opened up any inroads to appear in that drop-down.

**Comment by devilmark84** [comment]
> > No, I'm talking about this menu.
> > <img alt="Image" width="453" src="https://private-user-images.githubusercontent.com/1248444/426134618-c8e64bd4-a9c0-4172-bae9-131b32005d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI4NTQ5MjUsIm5iZiI6MTc0Mjg1NDYyNSwicGF0aCI6Ii8xMjQ4NDQ0LzQyNjEzNDYxOC1jOGU2NGJkNC1hOWMwLTQxNzItYmFlOS0xMzFiMzIwMDVkMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjRUMjIxNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY5OWEwYWNmMzI2MzI3YjkwYjY4M2E1MGZhODNjZmJkYjNiODU5NzBiOWIxNTAwNzQ3YjE2YTc5OTA0MmJjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1yPRCTi3038yquYGf9yOLjTkGjnAMR8sWQfvR03PKK0">
> 
> Not even installed videoconf apps (like for example Zoom) appear in this drop-down menu. I would thus assume that Apple have not yet opened up any inroads to appear in that drop-down.

I'm sure that Skype appeared on that menu because I saw it!

**Comment by mechko** [comment]
btw, I built an Open Source app that does this for Jitsi and is available on the Mac App Store (free & Open Source). 

<img width="1286" height="804" alt="Image" src="https://github.com/user-attachments/assets/8b96f4a9-7db9-4682-bea1-0d5778bdb10a" />

Find it here: 

https://apps.apple.com/de/app/calendar-freedom/id6759659484?mt=12

Dear Jitsi team: Maybe someone wants to link this somewhere on the Jitsi documentation for better visibility?

**Comment by saghul** [comment]
That's great! You can send a PR adding a link to the app here: https://jitsi.github.io/handbook/docs/community/third-party-software
