### ISSUE TITLE
Jitsi Meet "not working" with Icecat

### ISSUE THREAD

**Issue by Perflyst** [jitsi/jitsi-meet#4836]
## Description
Icecat is the GNU version of firefox. Looks like Jitsi Meet doesnt like it.

## Current behavior
For example https://meet.jit.si/ displays that the browser is not supported

## Expected Behavior
Jitsi meet should just work, Icecat is normal Firefox with some things removed for better privacy.

## Possible Solution
Add Icecat useragent (?) to supported list

## Steps to reproduce
1. Install Icecat
2. Open https://meet.jit.si/

**Comment by bgrozev** [comment]
Can you please post the UserAgent string and the logs from the javascript console? You can filter for just "BrowserCapabilities" in the console.

**Comment by Perflyst** [comment]
Old LTS `Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0` or new LTS `Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0` (it is using privacy.resistFingerprinting: true)

From console
`2019-11-16T15:50:19.200Z [modules/browser/BrowserCapabilities.js] This appears to be unknown, ver: undefined`

**Comment by Ambrevar** [comment]
Can we reopen this issue?  More generally, Jitsi should test for capabilities, not User Agents.  I suspect that any browser that has WebRTC support but not the known user agent won't work on Jitsi, while it should.

Workaround for IceCat users: Install the https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/ extension and switch to the Firefox user agent.

**Comment by saghul** [comment]
Unfortunately that doesn't quite work in practice. Some things can't be checked at runtime.

**Comment by Ambrevar** [comment]
That's OK! :)

Preventing access to select user agents is not a good option: it's
better to just display a warning and let the user proceed at their own risk.

**Comment by saghul** [comment]
> Preventing access to select user agents is not a good option: it's better to just display a warning and let the user proceed at their own risk.

I beg to differ: they may have a bad experience because the software is not tested on their browser, and they'll think it's the software which doesn't work. There are some Chromium builds our there which remove WebRTC altogether, for example. I have no idea what changes IceCat has.

**Comment by Ambrevar** [comment]
Isn't displaying a warning banner enough?

Also consider that restricting Jitsi to Firefox and Chrome may be
further entrenching the dominance of an already rather monopolized
market :/

**Comment by saghul** [comment]
> Isn't displaying a warning banner enough?

It has proven to not be the case.



> Also consider that restricting Jitsi to Firefox and Chrome may be further entrenching the dominance of an already rather monopolized market :/

It's not explicitly restricted. WebRTC support in browsers has a painful history. If you / we know it works, feel free to open a PR so we treat IceCat as Firefox, that should do it.

**Comment by Ambrevar** [comment]
IceCat has the exact same WebRTC support as Firefox.
Accepting IceCat user agent would fix it.

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
```

**Comment by Ambrevar** [comment]
Thanks in advance :)
