### ISSUE TITLE
(Android) Build fails with "Cannot get property 'mavenRepo'"

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#4837]
Sorry, but now I'm having trouble building on Android.

I'm getting this error when gradle is syncing:

"Cannot get property 'mavenRepo' on extra properties extension as it does not exist"

Any clues?

Thanks

**Comment by pdarcos** [comment]
Forgot to add:

Mojave 10.14.5  
Android Studio 3.5.2 
Android gradle plugin version 3.4.2 
Gradle version 5.1.1

**Comment by pdarcos** [comment]
I had to downgrade gradle to 3.3.2 and now it builds without the maven error.

In my testing it seems to work ok on a Samsung S8 running Android 9, but on a Pixel 2 running Android 10 I didn't get it to work yet.

I'll close this ticket and open a new one for Android 10 when I have some debug logs.

Cheers

**Comment by sy3adel** [comment]
I had the same problem in Gradle version 5.0.
And when I downgraded Gradle version to 3.3 I had another problem
`Could not determine java version from '12.0.1'.`

And The recommendations point to updating the Gradle to version 5.0 to solve this problem.

**Comment by shishir1979** [comment]
Any solution for this ?

**Comment by saghul** [comment]
Last I tried I couldn’t get Jitsi Meet to build properly on Gradle 5 and plugin 3.4 (or 3.5 I can’t remember).

I’ll give it a try again in the future, but in the meantime, any patches are welcome.
