### ISSUE TITLE
Dial in number provided by the Android app is for the wrong country

### ISSUE THREAD

**Issue by life777eternal** [jitsi/jitsi-meet#4840]
## Description
--- Sharing the Meeting Info from the Android app provided the US dial in number, not the number for the country I'm in. 

## Current behavior
--- Tapping on the 3 vertical dots at the bottom right, and then Meeting Info, after selecting where to send the meeting info, the US dial in number is included. 

## Expected Behavior
--- Same as current, except that the dial in number for the country I'm in should be included, if I happen to be in one of the 10 countries that Jitsi Meet has dial in numbers for, if I happen to not be in the US. 

## Possible Solution
--- Add a selection of the 10 countries with dial in numbers available, and from that selection make the app include the dial in number for that country. 

## Steps to reproduce
--- If you are not in the US, start/join a Jitsi Meet link on Android. Once connected tap on the 3 vertical dots at the bottom right & hit "Meeting Info" then select where you want to send it. (probably to yourself in some way other than Insecure SMS) and notice that the dial in phone provided is the US number. Many carriers are offering free long distance within the country, but international calls usually have an extra charge. 

# Environment details
--- Android 9

**Comment by damencho** [comment]
If you create your service that provides the numbers to return default or as first number the desired one(the one that matches your geolocation) you will get it in meeting info .

**Comment by life777eternal** [comment]
> If you create your service that provides the numbers to return default or as first number the desired one(the one that matches your geolocation) you will get it in meeting info .

How do you mean by that? How is that a fix?

**Comment by damencho** [comment]
Are you using your own service to provide the numbers?

**Comment by damencho** [comment]
We are already using this solution in a jitsi-meet deployment. In the returned list of numbers you can specify the default one https://github.com/jitsi/jitsi-meet/blob/master/doc/cloud-api.swagger#L139 according location the request was made

**Comment by life777eternal** [comment]
> Are you using your own service to provide the numbers?

No, it's just the share feature in the Android app that I was referring to.

Although I know that I copy the preferred number from the mobile website on https://Meet.jitsi.si/_______ but that's not the point. It shouldn't provide the US Dial-in number if the person is not in the states.

**Comment by damencho** [comment]
So in order to see a number according geolocation the dial in service needs to provide that information as default number as shown in the swagger above. This way it works for web and for mobile and in all places where we show just one number. It is just that meet.jit.si's service does use this feature yet, I will bring it up to the team to migrate it to another geolocated service.
