### ISSUE TITLE
Difficulté de connexion caméra

### ISSUE THREAD

**Issue by REMY-BECARD-30** [jitsi/jitsi-meet#4849]
Bonjour,
Je débute sur cet outil libre Visio et je rencontre une difficulté avec la caméra.
J'ai cette caméra :
![image](https://user-images.githubusercontent.com/57708371/68754497-1e3be180-0607-11ea-8a4f-717f900ebb44.png)

et j'ai ce message :
![image](https://user-images.githubusercontent.com/57708371/68754563-3ad81980-0607-11ea-91b0-464ac18571fd.png)

Pourriez-vous m'éclairer ?
Merci
Cordialement.
Rémy

**Comment by damencho** [comment]
When having questions please use the community forum before opening new issues. And make sure you post your questions in English.

You can also test your camera with https://test.webrtc.org/ and https://appr.tc/ and also report the results.
