### ISSUE TITLE
Feature-Request: Jitsi-meet support LAN networks

### ISSUE THREAD

**Issue by compuguy** [jitsi/jitsi-meet#485]
I work in a protected network that is heavily restricted. I was considering using jitsi-meet for our video conferencing solution, but it seems dependent on several external internet features.

**Comment by bgrozev** [comment]
Setting [this option](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L72) to true should make it work without internet connectivity.

**Comment by cr7xiaoyu** [comment]
the L72 option is  'During that time service will not be available. ' +
is it?

**Comment by damencho** [comment]
Apparently the file has changed, the option is disableThirdPartyRequests.
