### ISSUE TITLE
Provide flag for hiding the new participants count UI element

### ISSUE THREAD

**Issue by MarkErik** [jitsi/jitsi-meet#4871]
**Is your feature request related to a problem you are facing?**
Recently there was a new participants count number and icon that appears at the top centre of the video chat window when using web browser for the conference.
https://github.com/jitsi/jitsi-meet/commit/c3a6a8fb173add9d114757cb053d9a995a049474

The issue is that it draws a lot of attention away from the speaker during the conference and for 1-1 (or small) conferences in my opinion it is not necessary to see how many people are connected front-and-center (as we can see the video window of each participant).

I also appreciate that everyone has slightly different use-cases for how they use Jitsi, so I don't want to assume that this new UI element is an issue for everyone (maybe large conferences nice to know how many are connected).

**Describe the solution you'd like**
It would be great if there was a _variable to turn it On or Off in the interface_config.js file_ (that seems like the most logical place).

Also, may want to consider moving the UI element to the bottom right near the Chat / Raise Hand area? I feel like you may want to keep the view around the speaker as clean as possible.

Thank you!

**Comment by saghul** [comment]
Hiding it for the 1-1 case has come up, and I'm there with you, it makes sense. As for moving the UI element, I'll bring it up with our UI/UX people (or they weill see it here).

Thanks for the feedback!

**Comment by MarkErik** [comment]
Thank you for looking into this.

Is there a case for also having it as a flag in the interface_config?
(Default could be On to satisfy your use-cases)

**Comment by saghul** [comment]
I removed it for 1-1 calls here: https://github.com/jitsi/jitsi-meet/pull/4872 as for the rest of cases, yeah a flag is probably ok. Are you for writing a PR?

**Comment by MarkErik** [comment]
I'd love to contribute, however my skill level is such that I can just read the code and through trial and error make modifications (comment stuff out).

Thank you again for responding to this.

**Comment by saghul** [comment]
No worries, we'll keep this open and get to it as time allows.

**Comment by saghul** [comment]
THis has already been implemented.
