### ISSUE TITLE
Loop connection time out issue

### ISSUE THREAD

**Issue by Arunakjv** [jitsi/jitsi-meet#4873]
Hi,
can you please tell me about Session timeout .
how can i give inactive session  timeout to 10 seconds.in a conference.
i am using jitsi Meet quick setup in my server. and it is running smoothly.
can i take control of any conference by any way either by API or some third party tool.

Thanks Arun Kumar

**Comment by damencho** [comment]
Please when having questions or problems use the community forum before opening new issues.



> how can i give inactive session timeout to 10 seconds.in a conference.

What do you mean? Currently, when the last participant is alone in the room for 20 seconds jicofo terminates the session and that participant is no longer sending media as it had just joined an empty room.
