### ISSUE TITLE
Regarding build issue with xcode 11.2.1

### ISSUE THREAD

**Issue by NishantTiwarins** [jitsi/jitsi-meet#4876]
Hi 

I am unable to build the jitsi framework with command terminal as it gives an issue with the simulator and arm7 build files. Can you please help me with this

**Comment by saghul** [comment]
What exact steps are you following and what exact commit are you building? (I've made fixes in this area very recently).

**Comment by NishantTiwarins** [comment]
Hi 

The steps I performed for building the jitsi framework manually i.e (xcode build command) is the same as i used to build earlier the only change here is that i am using xcode 11.2.1 terminal as i want this to be build for Xcode 11.2.1

**Comment by NishantTiwarins** [comment]
Please help me i am stuck with this step from last two days and tried everything.

**Comment by saghul** [comment]
Please paste the exact build command you used and the exact error you got.

**Comment by NishantTiwarins** [comment]
Hi 
give me 10 to 15 minutes as i deleted the framework so need to create again with xcode 11.2.1  to produce the error. Steps and command are as follows 
1. git clone <your repo url>
2. then npm install 
3. cd ios
4. pod install
5. xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

Have run this command with xcode terminal 11.2.1 will share the screenshot in 5 to 10 minutes
Thankyou for your help and replies
