### ISSUE TITLE
xcode 11.2.1 issue with real devices.

### ISSUE THREAD

**Issue by PinkeshGjr** [jitsi/jitsi-meet#4881]
I have updated my Xcode to the latest version 11.2.1. I am using jitsi-meet SDK manually. When I try to run my project it works fine in the simulator but when I try to run in the real device it's not working.

```
Details

Unable to install "XXXXXX"
Domain: com.apple.dtdevicekit
Code: -402620388
--
App installation failed
Domain: com.apple.dtdevicekit
Code: -402620388
Failure Reason: No code signature found.
User Info: {
    DVTRadarComponentKey = 487927;
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012391e6e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x000000012391ede9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x000000012395e56a __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 164
	3   DVTFoundation                       0x000000010b3ba156 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x000000012395e301 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1589
	5   IDEiOSSupportCore                   0x00000001237e6a25 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4523
	6   DVTFoundation                       0x000000010b4eb3ba __DVT_CALLING_CLIENT_BLOCK__ + 7
	7   DVTFoundation                       0x000000010b4eca92 __DVTDispatchAsync_block_invoke + 809
	8   libdispatch.dylib                   0x00007fff66f01583 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00007fff66f0250e _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00007fff66f07ace _dispatch_lane_serial_drain + 597
	11  libdispatch.dylib                   0x00007fff66f08452 _dispatch_lane_invoke + 363
	12  libdispatch.dylib                   0x00007fff66f11a9e _dispatch_workloop_worker_thread + 598
	13  libsystem_pthread.dylib             0x00007fff6715b71b _pthread_wqthread + 290
	14  libsystem_pthread.dylib             0x00007fff6715b57b start_wqthread + 15
);
}
--
```

**Comment by saghul** [comment]
What do you mean by "manually"? Are you using CocoaPods or just vendoring the framework? Did you make sure it's also signed?

**Comment by saghul** [comment]
When embedding it in your project, did you mark is as "Embed and sign" ? Did you add the WebRTC framework too?

![Screen Shot 2019-11-22 at 07 36 32](https://user-images.githubusercontent.com/317464/69403429-dbf75c00-0cfa-11ea-850c-4986a19ba736.png)

**Comment by PinkeshGjr** [comment]
Yes, both frameworks are there with "Embed and sign". When I run my project to simulator it works fine. I got that error when I run in real devices.

**Comment by saghul** [comment]
Can you reproduce it with this example? https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/ios/objc/NoPodsSample

**Comment by PinkeshGjr** [comment]
It's working fine with this example. I have replaced my framework in this example and still, it's working fine.

**Comment by saghul** [comment]
I don't know, you built it 🤷‍♂ 

I strongly suggest you use CocoaPods though, this way you'll be able to update easily and you don't need to build the SDK yoursself.

**Comment by PinkeshGjr** [comment]
I have made some UI changes that's why I need to use the framework manually. Would you please help me with that why I keep getting this error?

**Comment by saghul** [comment]
I don't know why it's failing for you. I've never seen this error myself, sorry. Since it menstions signing, I'd start by double checking every signing related options.

**Comment by PinkeshGjr** [comment]
Ok, thanks for the support. For now, I am closing this issue, in future if you have anything please me know here.

**Comment by hongcha919** [comment]
@PinkeshGjr   I had the same problem. Have you solved it ？

**Comment by PinkeshGjr** [comment]
@hongcha919 No i am not able to fix this so for now i am using real device for testing to avoid that.

**Comment by hongcha919** [comment]
@PinkeshGjr Thanks. I still have this error with xcode 11.3.1 . which jitsi tag you used ?  

I use the lastest tag 4255. My steps to reproduce
npm i
cd ./ios
pod install
cd ..
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive
