### ISSUE TITLE
(ANDROİD)Could not find method debugImplementation() for arguments [com.squareup.leakcanary:leakcanary-android:1.6.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by gokhanakcam** [jitsi/jitsi-meet#4886]
Hi, i have a MacOs. When I wanted to compile the application, I got the error as follows. I am using the most current version of the application. Can you help me ? Thanks. 

<img width="1679" alt="Ekran Resmi 2019-11-23 15 19 56" src="https://user-images.githubusercontent.com/39699114/69481464-ab124680-0e22-11ea-9d1d-973325236df9.png">

**Comment by saghul** [comment]
If you into the android directory and do `./gradlew assembleRelease` does it fail the same way?

**Comment by gokhanakcam** [comment]
Dear Saghul,
Unfortunately, I get exactly the same error. What we did was we just downloaded the last version of the project and we didn't touch even a single line of the source code. Could you possibly clone the project and test it on your own system so that also you can generate the error 

A piece of information: if I commented out codes related to leakcanary I can get the application running. But this is so risky that we don't go along with these lines are commented. FYI.

**Comment by saghul** [comment]
I cannot reproduce it. It's not risky to disable that at all, since it's just a thing to catch leaks in debug mode. That said, they released a major update, so I'll give that a try. In the meantime, just comment those out, it's ok.

**Comment by saghul** [comment]
Try to apply this PR, it should fix your problem.

**Comment by skabali** [comment]
Hello @saghul , i recently imported the Jitsi meet Android SDK and i also installed all the react native files using npm install, 2 errors cleared and now i am stuck with the one below, please advise on how i can resolve it;

> Caused by: groovy.lang.MissingPropertyException: Cannot get property ‘mavenRepo’ on extra properties extension as it does not exist
<img width="960" alt="jitsi-meet" src="https://user-images.githubusercontent.com/1632185/81428772-70e4f900-9165-11ea-9074-e2c7eafc2431.PNG">
