### ISSUE TITLE
Unable to force kick/ban or force mute users even if i am a jitsi room moderator.

### ISSUE THREAD

**Issue by FaizanZahid** [jitsi/jitsi-meet#4887]
As a moderator i can mute people, but they can unmute themselves. This moderation feature is useless, because spammers who want to spam can keep unmuting themselve. This is happening with us.

Same thing with kicking, if i kick them, they can come back again, so its useless too.

Is there any way to force mute the participant or permanently ban/kick a user from joining a meeting? If i am a moderator ?

How to do this? and how can we make other users moderators?

Alternatively, if you guys enable below feature:

If a mod has muted a user, then 
then they should be able to unmute themselve only after a mod has allowed them to unmute,

 if mod has muted them, they should not be able to unmute, unless the mod has unmute them (which will not unmute them but will give them an option/permission to unmute themselve in real) but if mod has muted them, they should remain force muted, unless they have the permission by a mod to unmute themselve.

currently a mod cannot force mute users, because they can simply come back and unmute themselve, they should not be permitted to unmute unless mod has allowed them to unmute,. How can we do this?

**Comment by damencho** [comment]
There is no such option for muting and it will need modifications in several places to be able to implement this. 
To be able to force a user out of a conference, you need to implement authentication and to delete the user from your authentication backend. With anonymous participants there will always be able to join.

Please use the community forum for questions before opening new issues.

**Comment by tdkuehnel** [comment]
You could kick a user and change to a new room with the remaining participants where the slammer does not know the roomname as a workaround.

**Comment by saghul** [comment]
The lobby is the right way to handle this.
