### ISSUE TITLE
Allow jitsi room moderator to force mute participants in a room and they should be able to unmute only if permitted by the mod.

### ISSUE THREAD

**Issue by FaizanZahid** [jitsi/jitsi-meet#4888]
As a moderator i can mute people, but they can unmute themselves. This moderation feature is useless, because spammers who want to spam can keep unmuting themselve. This is happening with us.

Same thing with kicking, if i kick them, they can come back again, so its useless too.

Is there any way to force mute the participant or permanently ban/kick a user from joining a meeting? If i am a moderator ?

How to do this? and how can we make other users moderators?

Alternatively, if you guys enable below feature:

If a mod has muted a user, then
then they should be able to unmute themselve only after a mod has allowed them to unmute,

if mod has muted them, they should not be able to unmute, unless the mod has unmute them (which will not unmute them but will give them an option/permission to unmute themselve in real) but if mod has muted them, they should remain force muted, unless they have the permission by a mod to unmute themselve.

currently a mod cannot force mute users, because they can simply come back and unmute themselve, they should not be permitted to unmute unless mod has allowed them to unmute,. How can we do this?

**Comment by damencho** [comment]
Please do not spam, one question in the forum is enough.
