### ISSUE TITLE
CAMERA WON'T WORK

### ISSUE THREAD

**Issue by yahokanapia** [jitsi/jitsi-meet#4889]
Hi, I am supposed to have an online interview with WeblioPh but the website cannot access my camera. I have made sure to turn off any other apps using my camera, restared my pc, refreshed my page  and updated my pc but still won't work. Please help me. I 'm using windows 10 by the way.

**Comment by saghul** [comment]
I don’t know what WeblioPh is. Do they use Jitsi Meet?

**Comment by yahokanapia** [comment]
yes they are, its an online tutor ESL company.
this is the link they have provided me https://meet.jit.si/ along with my
log ins.
I can log in tru Jitsi Meet but my camera will not work, it's on and off.

**Comment by saghul** [comment]
What browser are you using? Can you open the JavaScript console and paste the output here?

PS: We are the authors of the Jitsi Meet open source project, but are in no way related to WeblioPh.
