### ISSUE TITLE
Add app store badges to README and website

### ISSUE THREAD

**Issue by PanderMusubi** [jitsi/jitsi-meet#4891]
Please, add badges of app stores to:
- [README](https://github.com/jitsi/jitsi-meet/blob/master/README.md) 
- [website](https://jitsi.org/downloads/)

This would concern:
- Google Play badge
- F-Droid badge
- iOS badge

I'm willing to make a PR for this if it is welcomed.

**Comment by saghul** [comment]
You’re welcome to send a PR for the readme! I’ll take care of the website. Cheers!

**Comment by saghul** [comment]
Added flair to the README: https://github.com/jitsi/jitsi-meet/pull/4897

**Comment by saghul** [comment]
Done, also the website.

**Comment by PanderMusubi** [comment]
Thanks very much! Looks great. Perhaps also add the F-Droid badge at https://meet.jit.si/ ?

Related question: why are https://meet.jit.si/ and https://meet.jitsi.net/ looking differently?

**Comment by damencho** [comment]
> Related question: why are https://meet.jit.si/ and https://meet.jitsi.net/ looking differently?

The second one is not a thing, where did you get it from?

**Comment by PanderMusubi** [comment]
Fourth result on Duck Duck Go for Jitsi Meet.

**Comment by licaon-kter** [comment]
Any news here? Still missing from https://meet.jit.si/

**Comment by licaon-kter** [comment]
So this is not wanted? Only the apps with tracking are advertised there?

**Comment by licaon-kter** [comment]
https://github.com/jitsi/jitsi-meet/commit/f8a41aea9c32796646c0fea11064775a4e5c3523
Great :)
