### ISSUE TITLE
List of devices has no text when embedding Jitsi Meet on file:// or chrome-extension://

### ISSUE THREAD

**Issue by Jip-Hop** [jitsi/jitsi-meet#4892]
The list of devices has no text, but you can select the empty items to change devices. This happens when embedding Jitsi Meet with the external iframe api, on a page served over the file:// or chrome-extension:// protocol. So this happens by default in a NW.js app.

![Screenshot 2019-11-25 at 11 15 11](https://user-images.githubusercontent.com/2871973/69533173-a4491800-0f77-11ea-975a-78422c285607.jpg)

The list has no text, describing the options you can choose from. But there should be text, like there is when embedding Jitsi Meet on e.g. a page served via https.

Save this snippet of code as html file, and open it in Google Chrome directly using the file:// protocol. Go to settings -> devices and click one of the dropdowns.

```
<!DOCTYPE html>
<html>

<head>
    <title>External API</title>
    <script src='https://meet.jit.si/external_api.js'></script>
    <style>
        * {
            margin: 0;
            padding: 0;
            border: 0;
        }

        #meet {
            width: 100vw;
            height: 100vh;
        }
    </style>
</head>

<body>
    <div id="meet"></div>
    <script>
        const domain = 'meet.jit.si';
        const options = {
            roomName: 'test',
            parentNode: document.querySelector('#meet'),
            configOverwrite: {
                desktopSharingFrameRate: {
                    min: 30,
                    max: 30
                },
            }
        };
        const api = new JitsiMeetExternalAPI(domain, options);
    </script>
</body>

</html>
```

This happens using the latest Google Chrome on MacOS 10.14.6, or NW.js 0.42.5.

**Comment by saghul** [comment]
I wonder if this is a secirity policy thing? Do you see the Jitsi logs in the JS console? We do log device information.

**Comment by Jip-Hop** [comment]
Maybe it's a timing issue?

This is the log output:

```
2019-11-26T11:41:09.394Z [modules/RTC/RTCUtils.js] <t.value>:  Using the new gUM flow
Logger.js:154 2019-11-26T11:41:09.394Z [modules/RTC/RTCUtils.js] <t.value>:  Using the new gUM flow
Logger.js:154 2019-11-26T11:41:09.395Z [modules/RTC/RTCUtils.js] <t.<anonymous>>:  Got media constraints:  {video: false, audio: {…}}audio: optional: Array(9)0: {sourceId: "default"}1: {echoCancellation: true}2: {googEchoCancellation: true}3: {googAutoGainControl: true}4: {googNoiseSuppression: true}5: {googHighpassFilter: true}6: {googNoiseSuppression2: true}7: {googEchoCancellation2: true}8: {googAutoGainControl2: true}length: 9__proto__: Array(0)__proto__: Objectvideo: false__proto__: Object
Logger.js:154 2019-11-26T11:41:09.396Z [modules/RTC/RTCUtils.js] <t.<anonymous>>:  Got media constraints:  {video: {…}, audio: false}audio: falsevideo: aspectRatio: 1.7777777777777777deviceId: "f4c51c1bbbfea7f0bacc00e1c42440e27f324f20fcbb066e434160e10c0c05ee"height: {ideal: 720, max: 720, min: 240}__proto__: Object__proto__: Object
Logger.js:154 2019-11-26T11:41:10.499Z [modules/RTC/RTCUtils.js] onUserMediaSuccess
Logger.js:154 2019-11-26T11:41:11.747Z [modules/RTC/RTCUtils.js] onUserMediaSuccess
```

When I run Chrome with the flag `--use-fake-ui-for-media-stream` and open the example html file, it works fine.

**Comment by saghul** [comment]
That flag causes permission prompts not being displayed. What does NW.js do about permissions? Doesn't it popup for permission?

**Comment by Jip-Hop** [comment]
I meant the easiest way to reproduce is just open the html file in Google Chrome.

With the --use-fake-ui-for-media-stream flag the permission is granted immediately without a permission prompt, and then the entries show correctly in the list. So that's why I thought maybe it has something to do with timing/race condition.

NW.js shows a prompt but I think if it's solved in the case of loading the html example via file:// protocol in Google Chrome, it will be fixed for NW.js too.

**Comment by saghul** [comment]
I wonder if this is related to WebRTC only working on “secure” origins.

Electron does work, but it’s a different beast...

**Comment by Integrion** [comment]
Hi all, i'm getting the same thing.  Running latest Google Chrome Version 80.0.3987.163 (Official Build) (64-bit) on Windows 10 64-bit machine. Our jitsi meet api instance is hosted in the cloud.

**Comment by christianvw** [comment]
Same here.
