### ISSUE TITLE
Problem share screen in ubuntu

### ISSUE THREAD

**Issue by mirohe** [jitsi/jitsi-meet#490]
Hello,

Mi system is:

Ubuntu 14.04
Graphical Environement is Unity
Firefox 44.0
jidesha 0.1.1

I reproduced this problem with two computer over my desktop, facing each other, with the same software, plugins (jidesha) and SO as I described above.

When I share screen with any program, not scale correctly and the other users see it wrong.
For example, if I share screen with libreoffice calc, the column "A" and part of "B" is not seen for the rest of users that is connected.
The problem also persists if I change the window size of that program or any other shared program. The scale is not correct.
This problem existed in previous versions of firefox, and this is tested from firefox user to firefox user.

Best regards

**Comment by gpolitis** [comment]
Thank you @mirohe. Are you able to test with Chromium? Does it work correctly there?

**Comment by mirohe** [comment]
Hello gpolitis,

I tried in chrome version 48 and works ok.

**Comment by bgrozev** [comment]
Outdated
