### ISSUE TITLE
NAT64AddrInfo.java 中 InetAddress.getAllByName(host) 阻塞 jsc 线程.

### ISSUE THREAD

**Issue by zyCwind** [jitsi/jitsi-meet#4901]
'gethostbyname' function may cause block.

when i deployed the jitsi-meet sys on an local area network with no access to the internet, i found that the app will block for a while (almost 1 minute). it was caused by getIPv6Address function which blocks the 'jsc' thread. discovering ipv6 address should be async by using threads. i just commeted these codes.

**Comment by zyCwind** [comment]
when 'jsc' thread was blocked, the jingle session-initiate got timeout and we can see 'xxx has connectivity problems on the other side.

**Comment by saghul** [comment]
Thanks for the report, we’ll take a look. Was this on iOS or Android?

**Comment by saghul** [comment]
Ah, i see the file name in the title. Never mind.

**Comment by saghul** [comment]
Why do you close this? Is the report incorrect?

**Comment by zyCwind** [comment]
nope，resolving ip address do block the jsc thread if there is no dns server. or just like desceibed before. i closed this because i got you awared.
