### ISSUE TITLE
Regarding WebRTC Size

### ISSUE THREAD

**Issue by NishantTiwarins** [jitsi/jitsi-meet#4902]
Hi 

Can you please check the size of WebRTC in project its showing me 937.7 MB ? is this correct ?

**Comment by saghul** [comment]
Yes, it's correct as it includes bitcode. If you don't need it you can strip it. Use the ios/sccripts/release-sdk.sh script to build the SDK and it will strip the bitcode.

PS: **Please** follow the issue templates before opening new issues. This should have been a question in our community: https://community.jitsi.org/

**Comment by NishantTiwarins** [comment]
okay. Will go through it and try to strip the WebRTC framework. Thanks for the update and help.
