### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.0.1 compiler: /Users/Develop/Projects/Eureka/SANNA/SANNA-app-ios-paciente/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule

### ISSUE THREAD

**Issue by andremvb** [jitsi/jitsi-meet#4905]
## Description
I need to work with Xcode 10.3. I have jitsimeet 2.4.2 installed, but I can't compile it. Jisti-meet was installed via Cocoapods.
Thanks for your work guys! :D 

## Error
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.0.1 compiler: /Users/Develop/Projects/Eureka/SANNA/SANNA-app-ios-paciente/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule

**Comment by saghul** [comment]
You can pin your version to 2.4.1, since it was compiled with Xcode 10.

**Comment by andremvb** [comment]
Hi @saghul, me here again. I installed 2.4.1, and I get this error:
Module compiled with Swift 5.1 cannot be imported by the Swift 5.0.1 compiler: /Users/Develop/Projects/Eureka/SANNA/SANNA-app-ios-paciente/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule

**Comment by saghul** [comment]
Hum. Maybe that was 2.4.0? Or 2.3.2 for sure.

**Comment by andremvb** [comment]
The last version supporting Xcode 10.3 is 2.3.1 (P.D., 2.3.2 doesn't exist).
Thanks @saghul!
