### ISSUE TITLE
Jitsi Meet in Docker

### ISSUE THREAD

**Issue by grinono** [jitsi/jitsi-meet#491]
When i'm running Jitsi Meet in Docker, somehow video and audio are not working. I'm running docker at AWS so it's NAT in NAT. May this cause the issue? It their any solution to fix this?

i start testing it with the following [Docker files](https://github.com/robertoandrade/docker-jitsi-meet) 

i though it could have caused by the lack of exposed ports.  So i added
Dockerfile >
`EXPOSE 443 5347 4443 10000-10020/udp`
Docker run >
`docker run -it --name name -p 443:443 -p 4443:4443 -p 5347:5347 -p 10000-10020:10000-10020/udp test/test1`

but no luck.

**Comment by damencho** [comment]
Please send your questions to the mailing list. You need to configure jitsi-videobridge to work behind nat which had been mentioned several times in the mailing list. 
Check org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS and org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS. 
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md

**Comment by sliard** [comment]
It's work after a lot of try for me :/

NAT_HARVESTER_LOCAL_ADDRESS must be the local ip of docker container and NAT_HARVESTER_PUBLIC_ADDRESS the docker host ip (the vm ip in case of macos use)

For example, for me it's :

> org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=172.17.0.3
> org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=192.168.99.100
