### ISSUE TITLE
make "start audio/video muted" web setting configurable in user's browser side preferences (like name and email)

### ISSUE THREAD

**Issue by alexkuklin** [jitsi/jitsi-meet#4913]
**Is your feature request related to a problem you are facing?**
Muted state is reset after reconnect, which sometimes is not very convenient.

**Describe the solution you'd like**
Checkboxes added to local settings, "start audio muted" and "start video muted".

**Comment by saghul** [comment]
FTR this is going to be part of the “hair check” screen I believe.

**Comment by Wurzelmann** [comment]
Something like this has been added [here](https://github.com/jitsi/jitsi-meet/commit/a45cbf41ef5e2ec66eeaedcf2fa94fd0c30cd54d)
