### ISSUE TITLE
Please add support for Libravatar.org and self-hosted instances (alternative to Gravatar)

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jitsi-meet#4927]
"Libravatar (from "libre" and "avatar") is a piece of free software to do federated avatar hosting."

It would be useful to support this service (and any self-hosted services using the same software) as an alternative to Gravatar. This would be more coherent with Free software values and a self-hosting approach, without requiring a proprietary third party service. A configuration option should be available to integrate such a self-hosted service.

* https://wiki.libravatar.org/
* https://wiki.libravatar.org/features/ - a list of features compared to Gravatar

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

This is already available as a setting https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L77

**Comment by MagicFab** [comment]
Thanks, [I've posted in a new thread on the forum](https://community.jitsi.org/t/how-can-i-use-avatars-from-libreavatar-org-or-my-self-hosted-instance-of-it-instead-of-gravatar/21012).

**Comment by MaxNoe** [comment]
In the Forum it turned out that this feature is currently *not* supported. Could you reopen this issue?

We were also now looking for an alternative to gravatar, especially since they require a wordpress account nowadays

**Comment by MaxNoe** [comment]
Gibt's schon einen User mit der und 4037?

**Comment by ofalk** [comment]
Let me know if there are any reasons why you would not switch to Libravatar. It can also proxy requests to Gravatar and therefore enhance your privacy!

**Comment by MagicFab** [comment]
For the ability to choose a local image as opposed to an image served by a third-party service, see : 
https://github.com/jitsi/jitsi-meet/issues/5254

**Comment by davidak** [comment]
This is still needed.

**Comment by MagicFab** [comment]
Still relevant.

**Comment by saghul** [comment]
Done in https://github.com/jitsi/js-utils/pull/44

**Comment by MagicFab** [comment]
Thank you ! Looking forward to testing and using this.

**Comment by saghul** [comment]
I'm afraid all the glitter wasn't gold 😢  See: https://github.com/jitsi/jitsi-meet/pull/8149 - You can still turn it on on your own deployment.
