### ISSUE TITLE
Please add support to save calls to WebDAV / Nextcloud

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jitsi-meet#4928]
It would be useful to be able to save calls to a non-proprietary, Free open source software, self-hosted service such as WebDAV. Nextcloud integration could be a possible interesting integration.
This would be more coherent with Free software values and a self-hosting approach, without requiring a proprietary third party service.

**Comment by MagicFab** [comment]
Tere is [a forum thread about saving to another location than Dropbox](https://community.jitsi.org/t/save-recording-to-location-other-than-drop-box/20971).

**Comment by saghul** [comment]
Ultimately it will probably be a matter of time. Are you willing to help?

**Comment by MagicFab** [comment]
How ? I can translate, document, test. Not available to code much at the moment.

**Comment by saghul** [comment]
Since this feature doesn't yet exist, coding is the first task at hand. Now, I may have some good news: we are planning to apply for GSoC 2020 and this would be a good project candidate!

**Comment by MagicFab** [comment]
In the current context with many new users coming to meet.jit.si there is increased interest and demand in self-hosting and this becomes even more relevant. I am still keen on helping with QA, docs and translation.

**Comment by MagicFab** [comment]
It looks like this script implements this feature : 

https://github.com/switnet-ltd/quick-jibri-installer

**Comment by ompiepy** [comment]
@saghul I am very much interested in working this issue. I will be preparing my proposal for GSoC 2022. I will be discussing any doubts. Thank You.

**Comment by saghul** [comment]
Excellent!
