### ISSUE TITLE
Voice Activation

### ISSUE THREAD

**Issue by Turakar** [jitsi/jitsi-meet#4933]
**Is your feature request related to a problem you are facing?**
Background noise (e.g. mechanical keyboards) can be heard.

**Describe the solution you'd like**
Background noise could be muted if somebody is not talking. For this, a voice activation level has to be defined (e.g. default value + settings or some dynamic method). If the volume is greater than the defined level the user starts to send. If he stops, there is a short delay until he becomes muted.

**Describe alternatives you've considered**
Push-to-Talk. This is not intuitive and error-prone.

**Comment by loleg** [comment]
I think that #899 adds quite useful and interesting technology to Jitsi, and would really encourage the project to consider improving on background noise (blocking as suggested by Turakar, noise filtering, or the worst enemy of multi-way calls: echos and feedback) as an area of development. Or if it is already underway, pointing out here some ways of supporting the effort.

**Comment by subversion23** [comment]
Also, this is an is essential feature for gamers. Discord and Teamspeak have it.  
Would be nice to have it in jitsi too.

**Comment by christianvw** [comment]
We have also had the same experience. In addition to the keyboard noise you can hear the noise of all microphones at all time, which is suppressed by voice activation in other applications (Teamspeak, Discord, Skype, ...).

Voice activation would be a very needed extension!

**Comment by jarno83** [comment]
Also interested in this. Thanks

**Comment by maul0r** [comment]
Hi, 
people agreed that this would be a useful feature, both would be voice activation & push to talk. The user could choose which one suites the user best - I would really like to see this reopened and actioned. 

+1

**Comment by DashieTM** [comment]
This would be the one "killer feature" that something like discord has over jtsi.
I assume it could be implemented with VADTalkMutedDetection. I can try to implement it, but my web dev skills are not as extensive yet.
