### ISSUE TITLE
Recording failed to start

### ISSUE THREAD

**Issue by aamdevan** [jitsi/jitsi-meet#4934]
I installed jitsi in a server and jibri in another server, everything is working, when i click start recording i got error like **Recording failed to start**

[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:

**Comment by saghul** [comment]
Please post in our community here: https://community.jitsi.org/ it's best for these kind of discussions.
