### ISSUE TITLE
Add support for external UVC webcams in Android client

### ISSUE THREAD

**Issue by vakrolme** [jitsi/jitsi-meet#4937]
**Is your feature request related to a problem you are facing?**

I'm prototyping a product for real-time remote assistance. I need the person on one side of the Jitsi Meet video call to use a specialized external camera to stream video to the other person. There are many other people facing the exact same problem. Various NGOs working with third-world countries, especially telemedicine projects, but others as well.

Endoscopes, microscopes, action cameras — there are many devices that support UVC protocol which, were they supported by WebRTC applications on consumer-level mobile devices, would enable many innovative apps and services in various industries.

**Describe the solution you'd like**

Jitsi Meet on Android needs to recognize an external USB-OTG UVC-camera, add it to the list of media sources and allow to switch to it just as you can switch between front & back cameras.

I believe this can be achieved easily with [UVCCamera library](https://github.com/saki4510t/UVCCamera), for which there is a [React-Native component wrapper](https://github.com/flyskywhy/react-native-uvc-camera). I'd do it myself if I knew anything about Java, React Native and Jitsi Meet codebase.

**Describe alternatives you've considered**

Patching the Android kernel to support external cams on OS level. Doesn't actually solve the problem, because I need other (non-technical) people to use this feature on their own personal devices.

**Comment by saghul** [comment]
I have succesfully used a UVC camera on devices which have support for it on the Kernel, like the Nvidia Shield. I understand these other more specific devices need some extra help.

Just as a note, the work should happen in https://github.com/react-native-webrtc/react-native-webrtc, which is where Jitsi Meet gets its multimedia capabilities from.

> I believe this can be achieved easily with [UVCCamera library](https://github.com/saki4510t/UVCCamera), for which there is a [React-Native component wrapper](https://github.com/flyskywhy/react-native-uvc-camera). I'd do it myself if I knew anything about Java, React Native and Jitsi Meet codebase.

Not quite, alas. This will need to be integrated at the low level, so the WebRTC engine works with the UVC based capturer.

**Comment by vakrolme** [comment]
> I have succesfully used a UVC camera on devices which have support for it on the Kernel, like the Nvidia Shield. I understand these other more specific devices need some extra help.

Correct, I'm talking about mobile devices that can be used wirelessly and outside. Some people say that manufacturers don't bother enabling `android.hardware.camera.external` even on those smartphones and tablets that ship with Android 9 pre-installed. And that, indeed, only Android TVs seem to support this feature.

> Just as a note, the work should happen in https://github.com/react-native-webrtc/react-native-webrtc, which is where Jitsi Meet gets its multimedia capabilities from.

Should I reopen the issue there?

> Not quite, alas. This will need to be integrated at the low level, so the WebRTC engine works with the UVC based capturer.

Ok, but the Java-library [UCVCamera](https://github.com/saki4510t/UVCCamera) can still be used, correct? 

I was also told [this piece of code](https://github.com/sutogan4ik/android-webrtc-usb-camera/blob/master/UsbCapturer.java) might be helpful. Is it?

**Comment by saghul** [comment]
> Should I reopen the issue there?

It's ok, since it's also us who maintain that library.



> Ok, but the Java-library [UCVCamera](https://github.com/saki4510t/UVCCamera) can still be used, correct?
> 
> I was also told [this piece of code](https://github.com/sutogan4ik/android-webrtc-usb-camera/blob/master/UsbCapturer.java) might be helpful. Is it?

Yes and yes. That capturer looks a lot like what we need, at least an important piece of it. It lacka a license, alas, so we cannot use it, I opened https://github.com/sutogan4ik/android-webrtc-usb-camera/issues/2

**Comment by vakrolme** [comment]
Sent the author an email as well, but it doesn't look promising.

I searched the issue tracker of [AndroidUSBCamera](https://github.com/jiangdongguo/AndroidUSBCamera) (a UVCCamera-derived library), 
and found another implementation of WebRTC+UVC integration: https://github.com/konovalov-k/USBCameraToWebRTC, this one is GPL-licensed, please check it out as well, @saghul.

**Comment by saghul** [comment]
We can’t use GPL code. MIT or Apache are fine.

**Comment by tamasberesoebb** [comment]
@vakrolme I am also interested in this feature. Did you find a solution for this issue? Are there any existing solutions to usb webcam based video chat on Android at all? I couldn't find one. 

I'm also trying to find an existing platform, which could work with a little bit of modification.

**Comment by vakrolme** [comment]
> Did you find a solution for this issue? 

No, I found a way to use internal cameras instead, which ended up being better for me atm.
> Are there any existing solutions to usb webcam based video chat on Android at all? 

I don't believe so.

**Comment by Tech4Life-salman** [comment]
I want to add USB camera in my android native sdk How can i achieve this task ?

**Comment by Niko-La** [comment]
Hey guys any way to get this otg-usb uvc working on mobile.

Is it possible to do it through only webrtc yet ?

If not is there way to do it on browser only.

This would be a huge feature for webrtc if it can do natively.

**Comment by saghul** [comment]
No progress has been made here, sorry.

**Comment by sohel-khan** [comment]
@Niko-La @Tech4Life-salman I have publish a npm  if you still looking for solution then here it is : https://www.npmjs.com/package/react-native-webrtc-usb-lib

**Comment by KanwalKhan-20** [comment]
@sohel-khan  how can we achieve this functionality if we are using SDK which is in java language ?

**Comment by sohel-khan** [comment]
@KanwalKhan-20 You can refer to this library's Android codebase

**Comment by danionescu2007** [comment]
> I have succesfully used a UVC camera on devices which have support for it on the Kernel, like the Nvidia Shield. I understand these other more specific devices need some extra help.
> 
> Just as a note, the work should happen in https://github.com/react-native-webrtc/react-native-webrtc, which is where Jitsi Meet gets its multimedia capabilities from.
> 
> > I believe this can be achieved easily with [UVCCamera library](https://github.com/saki4510t/UVCCamera), for which there is a [React-Native component wrapper](https://github.com/flyskywhy/react-native-uvc-camera). I'd do it myself if I knew anything about Java, React Native and Jitsi Meet codebase.
> 
> Not quite, alas. This will need to be integrated at the low level, so the WebRTC engine works with the UVC based capturer.

Hi @saghul,

Is there any new development on this?

Is there a "custom work service" which we can employ for having this feature added?

Thanks you.

**Comment by saghul** [comment]
No work has been done on this.

**Comment by kactusotp** [comment]
> Yes and yes. That capturer looks a lot like what we need, at least an important piece of it.

It is currently listed under Apache 2.0 License.

**Comment by danionescu2007** [comment]
I can't believe that years later this has been put aside.

**Comment by saghul** [comment]
Nobody seems to want it bad enough to write the code. 🤷‍♀️

**Comment by Kreshnik** [comment]
Is there any update on this issue?

**Comment by zsinba** [comment]
Will it continue?

**Comment by zsinba** [comment]
> **Is your feature request related to a problem you are facing?**
> 
> I'm prototyping a product for real-time remote assistance. I need the person on one side of the Jitsi Meet video call to use a specialized external camera to stream video to the other person. There are many other people facing the exact same problem. Various NGOs working with third-world countries, especially telemedicine projects, but others as well.
> 
> Endoscopes, microscopes, action cameras — there are many devices that support UVC protocol which, were they supported by WebRTC applications on consumer-level mobile devices, would enable many innovative apps and services in various industries.
> 
> **Describe the solution you'd like**
> 
> Jitsi Meet on Android needs to recognize an external USB-OTG UVC-camera, add it to the list of media sources and allow to switch to it just as you can switch between front & back cameras.
> 
> I believe this can be achieved easily with [UVCCamera library](https://github.com/saki4510t/UVCCamera), for which there is a [React-Native component wrapper](https://github.com/flyskywhy/react-native-uvc-camera). I'd do it myself if I knew anything about Java, React Native and Jitsi Meet codebase.
> 
> **Describe alternatives you've considered**
> 
> Patching the Android kernel to support external cams on OS level. Doesn't actually solve the problem, because I need other (non-technical) people to use this feature on their own personal devices.
I normally use this method on medical imaging. Mainly for medical education. I implemented a different solution. The UVC-Camera was sent to the server through another protocol and then added to the meeting room so that all participants could see the picture.
Did you go on?

**Comment by saghul** [comment]
Nobody seems to be willing to do the work here.

I'm going to close this since this issue already documents what needs to happen and where.

PRs are welcome.

**Comment by zsinba** [comment]
got

**Comment by sohel-khan** [comment]
@zsinba you can reach out to me at khan.sohel005@gmail.com, I have built the same solution which is you looking for.

**Comment by Leepian** [comment]
@sohel-khan can you share the link please?

**Comment by saghul** [comment]
We should be close to having this builtin: https://github.com/react-native-webrtc/react-native-webrtc/pull/1459

**Comment by sohel-khan** [comment]
> @sohel-khan can you share the link for latest working solution please?
please go through the following package 
https://www.npmjs.com/package/react-native-webrtc-usb-lib

**Comment by saqibkafeel** [comment]
whats te solution for [jitsi-meet](https://github.com/jitsi/jitsi-meet) this repo , i need to enable ucv camera in this code using react native please explain how can i do that

**Comment by tanzil114** [comment]
> No, I found a way to use internal cameras instead, which ended up being better for me atm.
> 
> >

@vakrolme can you please share how did you manage to use internal camera? I mean I want to enable video for android tv, but they don't have camera built-in, so would really helpful to know what you did?

Is there any way to use an external camera by making android os recognize it on os level, like a patch like you mentioned in a previous comment? If so, please give me pointers on how to do that, I really want to make these cams work, because we have heavy reliance on jitsi sdk now, and video is not working. Thanks!

**Comment by vakrolme** [comment]
> @vakrolme can you please share how did you manage to use internal camera?
@tanzil114 I switched from Jitsi to Agora SDK

**Comment by tanzil114** [comment]
> > @vakrolme can you please share how did you manage to use internal camera?
> 
> @tanzil114 I switched from Jitsi to Agora SDK

oh i see! :(
