### ISSUE TITLE
Prevent the screen from going off during a call when using a browser

### ISSUE THREAD

**Issue by raphj** [jitsi/jitsi-meet#4941]
Hello,

I just had a video call. At the other end, people did not touch their computer during the call and their screen went off at some point. They were using Jitsi Meet from Firefox on Windows 10.

Jitsi Meet should tell the computer not to put the screen on stand by. I don't have any idea whether there is an API for that, or whether using full screen would fix this. If full screen works to prevent going stand by, maybe Jitsi Meet should invite users to use full screen?

**Comment by saghul** [comment]
I don't think there is much we can do from the Jitsi side of things. This is something the browser has to do really.

Jitsi Meet already provides the option to go full-screen, it's up to the user to  do it or not.
