### ISSUE TITLE
Lags, delays and chopped sound on weak connection

### ISSUE THREAD

**Issue by raphj** [jitsi/jitsi-meet#4942]
Hello,

I just had a call using Jitsi Meet with people located at a place in the contryside in which the connection is weak (around 80 KiB/s up, 400 KiB/s down).

There were huge lags, delays and video and audio where intermittent. It was overall difficult to understand each other.

I was using the Jitsi Meet application on Android (F-Droid :-)). They were using Jitsi Meet from Firefox on Windows 10

It seems to me that Jitsi Meet should (more aggressively?) degrade the video quality automatically,  and maybe the sound without making it intermittent. They don't really need to see me in full HD :-)

Thanks for this awesome video conference system by the way

**Comment by saghul** [comment]
Other than low bandwidth, do you know if there was any packet-loss?

Note that righ now our Firefox support is far from ideal (aka, pretty broken). We have just started an effort to Make It Great Again. In the meantime, you'd have better results with Chromium.

**Comment by raphj** [comment]
Must probably, though I did not check. On this connection, when the upload link is maxed out, which I guess happened, incoming packets have a hard time to reach their destination.

This is good information. I can't see myself advise Chrome / Chromium, though I will use Jitsi Meet (the tool, not the public instance) on Wednesday for something quite important and will make sure to use Chromium then I guess.

Thanks for making Jitsi Meet great again on Firefox, I am looking forward for this.

**Comment by raphj** [comment]
I should note that I regularly use Jitsi Meet with someone using Firefox on Windows 10 from a better connection and the video calls are pretty good.

**Comment by saghul** [comment]
Thanks for the feedback Ralph, much appreciated. I don’t think having the call details would help at this point since we are in the process of fixing Firefox and we do know what’s wrong. Once these issues have been resolved we’ll make an announcement and feedback would be most welcome at that point.

Thank you!

**Comment by gudge25** [comment]
same problem
jitsi meet  hs been installed  in VPS in local data  center
i cant see any real  load  on  server
but  starting from 3  persons it is Lags, delays and chopped sound

**Comment by raphj** [comment]
I can confirm this was caused by using Firefox with Jitsi Meet. I had a video call in the same situation as described in this bug report but Chrome was used at the other end and it was flawless.

But Firefox and Jitsi Meet are making up! This situation is going to be solved soon! :-)

So check what browser is used, the CPU and bandwidth used on any computer involved. Jitsi Mee misbehaves if I am doing something else intensive on my computer.
