### ISSUE TITLE
createLocalTrack({maxFps:20}),  not work on mobile app

### ISSUE THREAD

**Issue by jakajacky** [jitsi/jitsi-meet#4946]
## Description
createLocalTrack({maxFps:20}),  the options not work on mobile app, the framerate still stay at  30

like this:
![屏幕快照 2019-12-17 下午5 27 32](https://user-images.githubusercontent.com/16397721/70982818-9d36a500-20f2-11ea-8002-8a5cba5cc8ab.png)

---

**Comment by saghul** [comment]
We’re you using iOS or Android?

**Comment by jakajacky** [comment]
> We’re you using iOS or Android?

hi,  i using Android 9,  by the way, the source code not the latest code,  i forked  from mobile-19.4

**Comment by saghul** [comment]
We haven’t done any changes recently so 19.4 should be fine. Can you please capture and attach the logcat output?

**Comment by jakajacky** [comment]
logcat output is here. Please see if it's helpful, I'm not familiar with Android

[logcat.txt](https://github.com/jitsi/jitsi-meet/files/3977215/logcat.txt)

**Comment by jakajacky** [comment]
@saghul  is there a conclusion?

**Comment by saghul** [comment]
I haven’t had the time to look into it, sorry. I’m on vacation now, with limited access to things.

**Comment by jakajacky** [comment]
> I haven’t had the time to look into it, sorry. I’m on vacation now, with limited access to things.

Sorry to bother you, you can ignore this problem for now. Enjoy your vacation ^_^

**Comment by vakrolme** [comment]
@jakajacky were you able to resolve this?
