### ISSUE TITLE
CLAMAV detected virus on app.bundle.min.map

### ISSUE THREAD

**Issue by vanhoveAlexis** [jitsi/jitsi-meet#4950]
After clamav scan, he detects this virus : Win.Trojan.LOLBins-7360500-2 on "app.bundle.min.map".
Published by clamav on December 14: https://lists.gt.net/clamav/virusdb/78045.

Can you clarify us on this issue?

Thank you.

VANHOVE Alexis

**Comment by saghul** [comment]
Can you please share a full-report of the scan? I don't really know what "Win.Trojan.LOLBins-7360500-2" is and the link doesn't really clarify much.

**Comment by vanhoveAlexis** [comment]
I will try to contact Clamav, we don't have more informations about this Virus reported by Clamav.
I will come back to you as soon as I have more information.

Best regards,

Alexis

**Comment by saghul** [comment]
Thank you!

**Comment by vanhoveAlexis** [comment]
After analysis of this virus name on Clamav, i had this report : 

![image](https://user-images.githubusercontent.com/36508252/71011970-9dcd3c80-20ee-11ea-959f-c9b7f4356e29.png).

Decoded by `sigtool`.

**Comment by saghul** [comment]
I don't  know what any of that means. What alleged malicious behavior is  detected?

**Comment by jlemangarin** [comment]
Hello !

I confirm your map file is now considered as a trojan. Here is an online scan : https://www.garyshood.com/virus/results.php?r=598246c39fe8a375310d5360457a2303

Thank you for your feedback on this.

**Comment by saghul** [comment]
Sorry, but I still don't understand what we can do here. That scan offers no details whatsoever, so I don't know how to proceed. For all I know, Clamav is likely wrong.

**Comment by jlemangarin** [comment]
Yeah it seems Clamav is wrong for sure ! But unfortunatly, leaving this issue as it is could lead to a more global rejection of this file. And you wouldn't have files of your library rejected by antivirus ! :)

Will you do something about this ?

Thanks in advance !

**Comment by jlemangarin** [comment]
FYI, I just sent a false positive report to Clamav

**Comment by saghul** [comment]
I’d do anything, but what can we do? I really don’t know. Also, what steps did you follow to run the scan? Do you run a scan in the browser or in the generated files after building Jitsi Meet locally?

**Comment by jlemangarin** [comment]
We have multiple installations of jitsi with a Clamav scanner on our installations that triggered this alert on this file.

I reported the false positive to the Clamav team so I guess we just have to wait and see

**Comment by saghul** [comment]
Please keep us posted, thanks!

**Comment by vanhoveAlexis** [comment]
Hi @saghul,
I did a test today, and clamav deleted this signature from the database. This file is not infected.

Best regards,

**Comment by saghul** [comment]
Thanks a lot for helping us with this! 🙏
