### ISSUE TITLE
Screen Sharing Broken in Chrome

### ISSUE THREAD

**Issue by cyberfarer** [jitsi/jitsi-meet#4955]
## Description
Desktop sharing with Chrome and Rocket.Chat is broken on the latest Ubuntu stable release: 1.0.4101-1

## Current behavior
Attempting to use desktop sharing presents no options in Chrome and presents a blank window that will consume all CPU in Rocket.Chat.

## Expected Behavior
Choose between screen and applications.

## Possible Solution
Roll back to version 1.0.3734-1

## Steps to reproduce
apt upgrade

# Environment details
Ubuntu 16.04.6

**Comment by saghul** [comment]
Do you have any Rocket.Chat logs? Is it works in. Chrome but not in Rocket.Chat, then I suspect something is wrong with the latter.

**Comment by cyberfarer** [comment]
It works in neither.

**Comment by saghul** [comment]
Oh. What Chrome version are you running? From the official Ubuntu repos?

**Comment by cyberfarer** [comment]
I download from Google and install. The version is: 78.0.3904.87 (Official Build) (64-bit)

**Comment by saghul** [comment]
Hum. I don't have a environment where I can test it, sorry. Does this test work for you? https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

**Comment by cyberfarer** [comment]
I enabled the experimental web platform and I was able to start a screen recording, select an open window and record. However, nothing displayed the dark window. I'm not sure if anything should have.

**Comment by saghul** [comment]
I don’t know what’s wrong in your setup, but screen sharing should work without plugins or flags since version 72 (IIRC).

**Comment by cyberfarer** [comment]
We have not changed our setup other than to install the update. Reverting back to the pre-update version solved the problem.

**Comment by saghul** [comment]
What where the exact package versions?

**Comment by zyphlar** [comment]
I just tried using screen sharing at meet.jit.si and nobody on the call got anything but a gray screen to send out to the rest of the attendees. The preview showed in the presenter's window, but nobody else got anything. I am using Chromium Version 80.0.3987.163 (Official Build) snap (64-bit), on Ubuntu.

Not sure if this is related but felt it was worth mentioning because everyone else joked that maybe we shouldn't have used Jitsi for this meeting and that was unfortunate.

**Comment by singletS** [comment]
I'm having the same screen sharing issue with the same conditions: using meet.jit.si; others see blank screen or sometimes an icon of monitor, but not the screen share preview showing on presenter's window.

Chromium 80.0.3987.163 Built on Ubuntu , running on Ubuntu 18.04

Video and audio working ok.

**Comment by badesemowo** [comment]
@singletS , I answered on something like this on #5884  -  
Perhaps this comment may be useful for you:  https://github.com/jitsi/jitsi-meet/issues/5884#issuecomment-612284539

**Comment by matthiasg** [comment]
Screen sharing is not very stable anyway sadly. It works on Windows/Chrome quite well in general at first, but often makes the entire session unusable when stopping it. 

The resolution and fps is also very inconsistent and sometimes drops to very low values (non readable text).

**Comment by Chersos** [comment]
we have similar issues:
- can't see shared screen of other clients (only gray background)
- on reload it shows up for a second
- shared screen thumbnail works !
- only some of our chromium-users have this issue
- switching to firefox seems to work
- version: Chromium 80.0.3987.163 Built on Ubuntu
- screen-sharing is going well until the last update (jitsi/jvb:4101-2 --> jitsi/jvb:4384)
