### ISSUE TITLE
Not able to build iOS SDK for latest release with deployment target 10.1

### ISSUE THREAD

**Issue by preema22** [jitsi/jitsi-meet#4957]
I have followed the steps to build release configuration build for iOS deployment target 10.1. I cannot update the deployment target currently due to other dependencies. 
Tried to build SDK using the command:
 xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release ENABLE_BITCODE=NO clean archive

Build failed with the following error :

ld: library not found for -lAmplitude-iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

Trying with Xcode 10.2.1
macOS Mojave Version 10.14.5

**Comment by saghul** [comment]
This is correct and noted in the changelog. SDK 2.5 dropped iOS 10 support.
