### ISSUE TITLE
Codepush and Jitsi not compatible in release mode.

### ISSUE THREAD

**Issue by jerinjohnk** [jitsi/jitsi-meet#4960]
## Description
In release version of android app crashes with error as soon as its opened
```
null is not an object (evaluating 'n.IsAndroid')

Module AppRegistry is not a registered callable module (calling runApplication)

null is not an object (evaluating 't.NativeModules.LocaleDetector.locale')
```

## Current behavior
Currently in app Codepush is added `android/app/src/main/java/com/docprime/MainApplication.java`
```
 @Override
        protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
        }
```

## Possible Solution
Commenting above snippet in android successfully builds android release

## Steps to reproduce
Add  `react-native-code-push`, complete its android installation and create a build.

# Environment details
 "react-native-code-push": "^5.5.1",
"react": "16.6.1",
"react-native": "^0.59.5",
"react-native-jitsi-meet": "^1.2.0",

Referencing similar error log issue #4574

**Comment by saghul** [comment]
Note that `react-native-jitsi-meet` is not maintained by us. It uses our native SDK which coincidentally also uses RN. That may lead to some issues. The problem here is that there are 2 bundles really. 1 provided by your app and nother one which the Jitsi SDK uses.

**Comment by jerinjohnk** [comment]
Closing this issue here have opened issue at respective repo [issue 94](https://github.com/skrafft/react-native-jitsi-meet/issues/94)
