### ISSUE TITLE
Could not use latest pod 2.5.1

### ISSUE THREAD

**Issue by ankathiriya** [jitsi/jitsi-meet#4962]
![Screenshot 2019-12-25 at 2 54 37 PM](https://user-images.githubusercontent.com/22503223/71441219-96c5b000-2726-11ea-9c22-0d21c87388b3.png)

**Comment by saghul** [comment]
Hum, we haven’t seen this issue. Can you try to reproduce with the Swift PiP example? https://github.com/jitsi/jitsi-meet-sdk-samples

Also, 2.5.1 was a botched release, please try 2.5.2.
