### ISSUE TITLE
Video doesn't work for iPhone with software version 13.2.3 for Jitsi-meet iOS SDK(framework) build version 2.1.0

### ISSUE THREAD

**Issue by preema22** [jitsi/jitsi-meet#4964]
I’ve integrated iOS SDK(framework) build version 2.1.0 with my app. It works fine for iPhone with software version 12.2. Video doesn’t work (it’s blank, audio works fine) for iPhone with software version 13.2.3.

Xcode Version : 10.2.1
Jitsi-Meet Version : 2.1.0
iPhone Version: 13.2.3

Is there any higher version of the framework I can use for Xcode 10?

![Screenshot 2019-12-19 at 15 00 28](https://user-images.githubusercontent.com/38324036/71507686-9e4f9b00-2885-11ea-946c-f74a78f8a677.png)

**Comment by saghul** [comment]
You need to update to the latest SDK 2.5.X.
