### ISSUE TITLE
I have changed DEFAULT_SERVER_URL in constants file (react/features/base/settings/constants.js) and now Dominant speaker for iOS is not working.

### ISSUE THREAD

**Issue by khateeb0** [jitsi/jitsi-meet#4965]
![Screen Shot 2019-12-27 at 4 38 45 PM](https://user-images.githubusercontent.com/45829536/71515062-68330b00-28c7-11ea-9040-fef181aeb99c.png)

**Comment by saghul** [comment]
Those 2 things are not related. If it works with one server and doesn't with another, there might be a bug in your deployment.

**Comment by saghul** [comment]
Sorry about that, you were right. The problem is that meet.jit.si uses WebSockets instead of datachannels, so we didn't catch the bug. A new release will be made shortly. You can check: https://github.com/jitsi/jitsi-meet/issues/4961
