### ISSUE TITLE
App crashes on joining a meeting when native call integration is enabled

### ISSUE THREAD

**Issue by sicherist** [jitsi/jitsi-meet#4966]
I installed jitsi meet (19.4.0) on my Sony Xperia Tablet Z running LineageOS (lineage-15.1-20191219-nightly-pollux_windy).

As soon as I join a meeting the app crashes and has to be restarted.

Reproducable: always

When I disable "native call integration" in the advanced settings, the app does not crash, I can join the conference and can see the other person. But the other participants can not hear me - it seems that Jitsi doesn't use the tablets microphone. But I assume this might be a different problem than the one that causes the app to crash - or is "native call integration" needed for the microphone?

**Comment by saghul** [comment]
Can you please share the logcat logs?

**Comment by sicherist** [comment]
adb logcat -v long > jitsi.txt
[jitsi.txt](https://github.com/jitsi/jitsi-meet/files/4032046/jitsi.txt)

**Comment by saghul** [comment]
Thanks, this really helps!

**Comment by saghul** [comment]
This should be fixed by https://github.com/jitsi/jitsi-meet/pull/4978
