### ISSUE TITLE
stable builds

### ISSUE THREAD

**Issue by kinnla** [jitsi/jitsi-meet#497]
Hi,
we (NGO with ~100 activists) set up our own jitsi meet server that we plan to use for internal communication. It runs on a debian virtual server and our hoster takes care for the install.

Do you have recommendations, how often we should update the setup? In your install guide you reference the nightly builds at http://download.jitsi.org/nightly/deb. Do you also have stable builds? 

Thx for the great software!

**Comment by kinnla** [comment]
Found your stable builds now at https://download.jitsi.org/jitsi/debian/ Maybe you want to add that to your install guide at https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md, where you only mention the nightly builds.

**Comment by kinnla** [comment]
Hi, I am changing now to stable builds on our server. Would be good, if you include instructions in your install guide (in the moment I only can see instructions for nightly builds). Thx!

**Comment by kinnla** [comment]
Update: our server stayed with a nightly build. apt-get displayed conflicts when I tried to switch to stable, and I felt not experienced enough to handle them. If you add instructions, we would switch to stable in the future.

**Comment by bonanza123** [comment]
Can you tell me how you added the stable branch to the apt-sources?

**Comment by kinnla** [comment]
hi Bonanza, we are still on nightly.
@jitsi-meet: are there any instructions how to migrate to stable?

**Comment by damencho** [comment]
We've updated the quick-install doc to use the stable repo we recently updated. Upgrading should be straight, just updating packages. If there are any conflicts or errors please report them to the dev list.
