### ISSUE TITLE
This app cannot be approved with CallKit functionality active in China. Please make the appropriate changes and resubmit this app for review.

### ISSUE THREAD

**Issue by 826888099** [jitsi/jitsi-meet#4970]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.

**Comment by 826888099** [comment]
how to get source code,i want to disable callkit

**Comment by saghul** [comment]
The source code is in this very repo. You can use the `enabled` property in `JMCallKitProxy` to disable CallKit in your app: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/callkit/JMCallKitProxy.swift#L53

**Comment by jakajacky** [comment]
i use the enabled property in JMCallKitProxy.swift to disable CallKit in my app, like this:
`@objc public static var enabled: Bool = false {`
but Apple still told me this app cannot be approved with CallKit functionality active in China.
we need to rebuild the SDK after change the enabled property to` false`?

**Comment by saghul** [comment]
If you changed it that way, yes, you need to rebuild the SDK.

That property can be changed at runtime though, so you can change it when your app starts. Not sure if that’s an option or Apple will reject your app though.

**Comment by mh18701873076** [comment]
Hello, I am using version 2.4.1 installed by cocopods. The release in China was rejected by Apple. How do I disable callkit? Can you open an interface to disable callkit?

**Comment by saghul** [comment]
You can call JMCallKitProxy.enabled = false in your app initialization code.

**Comment by l819183457** [comment]
![image](https://user-images.githubusercontent.com/16470589/76379998-91265080-638c-11ea-87ee-00080a6ca089.png)
这是这样禁用么？ 在项目启动的时候，但是苹果还是把项目拒绝了，有什么好的经验能提供一下么

**Comment by jakajacky** [comment]
@l819183457 确实，你最近有新进展吗？我准备重新编译SDK试试，直接将enable默认值改为false

**Comment by jakajacky** [comment]
- My app is finally approved, and released in App Store.  @saghul This method `JMCallKitProxy.enabled = false` is indeed correct, **however, some additional instructions need to be made when submitting.** 

- I think the reason why Apple reject is because CallKit is still integrated in my project, although i don’t use this feature

- So you can reply to Apple in Resolution Center your app have disabled CallKit functionality in China, but the CallKit is still integrated in my project....try to make some reasonable explanations

- It should be approved without accident

**Comment by AliKarpuzoglu** [comment]
@jakajacky  does the app work fine when you disable CallKit integration?

**Comment by saghul** [comment]
It should, yes.

**Comment by jakajacky** [comment]
@AliKarpuzoglu Up to now the APP work fine. In addition, we are not using the latest source code.

**Comment by AliKarpuzoglu** [comment]
Thanks guys.
