### ISSUE TITLE
Is it possible to Use jitsi Meet with non React Platforms

### ISSUE THREAD

**Issue by cmungun** [jitsi/jitsi-meet#4974]
I have a web-app in AngularJs which is implemented in IOS with a wkwebview. I'm using an Iframe to display  a URL using apprtc which works on web, android. Unfortunately, the getUserMedia function in Webrtc is not too compatible with the wkwebview. So i'm  currently trying to switch to jitsi.  It be greatl if i could have some further clarification of  the following(since it is mentioned i can integrate jitsi-ios in third party apps )

1) If i utilize just the IOS part (jitsi and webrtc framwork) only and integrate it to my swift code using the jitsiMeetView, will that work or do i have to have to  bridge something.

2) Any help would be greatly appreciated: whether if  its a workaround for the getUser Function or your thoughts on this.

**Comment by saghul** [comment]
>     1. If i utilize just the IOS part (jitsi and webrtc framwork) only and integrate it to my swift code using the jitsiMeetView, will that work or do i have to have to  bridge something.

Yes, it will work. Our native iOS SDK doesn't use a webview.



>     2\. Any help would be greatly appreciated: whether if  its a workaround for the getUser Function or your thoughts on this.

If you already have a native app then integrating our native SDK should provide a better user expecience since it's not a webview and doesn't suffer from webview limitations: running in the background, callkit integration, etc.
