### ISSUE TITLE
Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min

### ISSUE THREAD

**Issue by xiefangzhenz** [jitsi/jitsi-meet#4976]
Working with the library sources (lib-jitsi-meet)
By default the library is build from its git repository sources. The default dependency path in package.json is :

"lib-jitsi-meet": "jitsi/lib-jitsi-meet",
To work with local copy you must change the path to:

"lib-jitsi-meet": "file:///Users/name/local-lib-jitsi-meet-copy",
To make the project you must force it to take the sources as 'npm update':

npm install lib-jitsi-meet --force && make
Or if you are making only changes to the library:

npm install lib-jitsi-meet --force && make deploy-lib-jitsi-meet

After,I run jitsi-meet iOS project in xcode.

2020-01-08 11:39:02.544995+0800 jitsi-meet[29478:302684] [JitsiMeetSDK] Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `react/features/base/lib-jitsi-meet/_.native.js`: lib-jitsi-meet/lib-jitsi-meet.min could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
2020-01-08 11:41:08.642084+0800 jitsi-meet[29478:302701] Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
2020-01-08 11:41:08.642470+0800 jitsi-meet[29478:302701] Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery

After,I run yarn install in terminal.

yarn add v1.21.1
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning @atlaskit/button > @atlaskit/analytics-next-types@3.2.0: Typescript type definition files are now hosted directly from @atlaskit/analytics-next
warning @atlaskit/button > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @atlaskit/dropdown-menu > @atlaskit/button > @atlaskit/analytics-next-types@3.2.0: Typescript type definition files are now hosted directly from @atlaskit/analytics-next
warning @atlaskit/dropdown-menu > @atlaskit/droplist > @atlaskit/tooltip > @atlaskit/popper > react-popper > create-react-context > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
error Couldn't find match for "ed538f1" in "refs/heads/develop,refs/heads/firefox-mozilla,refs/heads/fix_ie_mobile,refs/heads/fix_ipad,refs/heads/gh-pages,refs/heads/master,refs/pull/1/head,refs/tags/0.7.1,refs/tags/0.7.2,refs/tags/0.7.3,refs/tags/v0.1,refs/tags/v0.1.2,refs/tags/v0.2.0,refs/tags/v0.2.1,refs/tags/v0.3.0,refs/tags/v0.3.2,refs/tags/v0.3.4,refs/tags/v0.4.0,refs/tags/v0.4.15,refs/tags/v0.4.3,refs/tags/v0.4.6,refs/tags/v0.4.8,refs/tags/v0.5.1,refs/tags/v0.5.11,refs/tags/v0.5.15,refs/tags/v0.5.25,refs/tags/v0.5.27,refs/tags/v0.6.0,refs/tags/v0.6.2,refs/tags/v0.7.0,refs/tags/v0.7.1" for "https://github.com/amplitude/ua-parser-js.git".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

how can i solve it?Thanks!

**Comment by saghul** [comment]
Don't use yarn.

You can use `install-local` (`npm i -g install-local`) to install your modified version of lib-jitsi-meet as follows: cd jitsi-meet; install-local ../lib-jitsi-meet

**Comment by xiefangzhenz** [comment]
Thanks!worked for me!

**Comment by asad175** [comment]
The solution is very simple. I have shared it here in my article. [Solution: Unable to resolve module lib-jitsi-meet/lib-jitsi-meet.min ](https://handyopinion.com/unable-to-resolve-module-lib-jitsi-meet-lib-jitsi-meet-min/).
We just need to go inside "lib-jitsi-meet" directory and need to run yarn command.

**Comment by gouravrc** [comment]
@saghul 
Previously, I ran the application with Xcode 11.01. It was working fine. But afterwards, when I tried ```npm install``` the following error came. Is there any way to get it run on Xcode 11+

> bundling failed: Error: Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `react/features/base/lib-jitsi-meet/_.native.js`: lib-jitsi-meet/lib-jitsi-meet.min could not be found within the project.

**Comment by saghul** [comment]
We no longer support Xcode 11.

**Comment by TivanDev** [comment]
> Don't use yarn.
> 
> You can use `install-local` (`npm i -g install-local`) to install your modified version of lib-jitsi-meet as follows: cd jitsi-meet; install-local ../lib-jitsi-meet

thank bro, worked for me
