### ISSUE TITLE
DOMException: Permission Denied!

### ISSUE THREAD

**Issue by shahzaibcb** [jitsi/jitsi-meet#4982]
Hi,

We've setup jitsi meet and integrated with rocketchat on port :8443 which is proxied by Nginx on HTTPS over port :8444 . In rocketchat, video call works fine but when we put the rocketchat in iframe on one of our livechat website and click on video conference button within the chat window (that suppose to connect to jitsi). The following error occurs in chrom inspect element:

https://pastebin.com/2kf9ernG

But the same works on firefox and camera gets detected but other person can't see the video.

What could that be related to ?

**Comment by saghul** [comment]
Does the site which embeds Jitsi on the iframe use HTTPS?

**Comment by shahzaibcb** [comment]
Yeah. We just came to know that rocketchat in iframe has some issue with video conference. So maybe that is the bottleneck here.

**Comment by saghul** [comment]
When creating the iframe, you have to set `allow="camera;microphone"` or use our external API which does that for you: https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js#L303

**Comment by shahzaibcb** [comment]
Okay but whats happening is that, rocketchat only has option for video recording in iframe and video conference looks not available which is creating this issue. We've used this fix which helped showing camera in chrome but it records and send video to user instead of live video conference.

**Comment by saghul** [comment]
I don't really know what you mean. I'm not familiar with how RocketChat is embedding Jitsi Meet. How is video recording invoved here?

**Comment by shahzaibcb** [comment]
Well what we come to believe that rocketchat in iframe is not giving any option for video conference. Its just giving option for video recording which is now working fine with jitsi even on chrome after your proposed fix.

So i think we need to check with rocketchat about this option.
