### ISSUE TITLE
While Compiling with Bitcode enabled

### ISSUE THREAD

**Issue by NishantTiwarins** [jitsi/jitsi-meet#4989]
Hi 

I am getting an error while compiling with bitcode. It shows that WebRTC does not conatin bitcode enabled. I have provided the screenshot below. 
![Screen Shot 2020-01-15 at 8 49 56 PM](https://user-images.githubusercontent.com/56542484/72446219-25cf6080-37d9-11ea-8aea-517371e762fc.png)

**Comment by saghul** [comment]
I assume you mean you are compiling the SDK yourself. You can use this script to download a bitcode-enabled WebRTC build: https://github.com/jitsi/jitsi-meet/blob/master/ios/scripts/bitcode.sh

**Comment by NishantTiwarins** [comment]
Hi 
Yes we are compiling the SDK by ourself. I have performed this following steps 
1. I went to the ios Folder after npm install and pod install
2. Opened jitsi.xcworkspace and in build phases of sdk workspace i have added the following script in bitcode section 
3. And from terminal i have run this following command 
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

Can you please confirm if these steps are correct.

**Comment by jeetkapadia** [comment]
@saghul it only creates the jitsimeet.framework and not the webrtc.framework. Can you tell me where can I find the resulting framework?

Also, as you can see in the image shared above it is giving error for arm7. Can you help us with that?
