### ISSUE TITLE
Make (error) notifications expanded by default

### ISSUE THREAD

**Issue by nosmicek** [jitsi/jitsi-meet#4993]
**Is your feature request related to a problem you are facing?**
If there is no audio or camera present on the client computer, two notifications messages appear. The problem is, that i have to expand those notifications first to have acces to buttons that dismiss those notices (either "dismiss" or "ok"). I think this problem is related to almost any notification. It is really a **bad design pattern to not show notification dismiss buttons** and to force users to do unnecessary actions (which are not obvious that uses should do them) just to get access to something that should be made available by default. Don't really get the idea why are notifications not expanded by default.
![jitsi](https://user-images.githubusercontent.com/20813001/72616221-b96a7380-3936-11ea-9c56-14f944b33f8b.jpg)

**Describe the solution you'd like**
I would like all notifications to be expanded by default, so i can just click on the "dismiss" or "ok" button.

**Describe alternatives you've considered**
No other alternatives for me.

**Comment by saghul** [comment]
We are going to replace those notifications (which are indeed not great) really soon. Stay tuned!

**Comment by wd77** [comment]
I second this, and I would like to note that it would be wise to place notifications where they do not interfere with the GUI. We had issues with these notifications as well, and they clearly obstruct the Chat and Raise Hand controls. This came up when users joined some session without camera or microphone as they were only joining a presenter, and they did not grasp how to get to Chat as the notification was in the way.

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/4993#issuecomment-575673772
