### ISSUE TITLE
No sound or video

### ISSUE THREAD

**Issue by contrapunctus-1** [jitsi/jitsi-meet#4994]
Device 1 - Nokia 6.1 (TA-1089), Android 9
Device 2 - OnePlus 3T

Jitsi Meet v19.4.0 from F-Droid

Both were connected via (different) WiFi connections. Neither side received voice or video, not even in low bandwidth mode. 

Both definitely were online, as we communicated over XMPP the whole time.

**Comment by NotSqrt** [comment]
Here, we've noticed that a transition from wifi to mobile data **during a call** made the sound/video work.

**Comment by graphixillusion** [comment]
I confirm that there is something not working right now: just tried with several devices and i can't hear/see any audio/video from other users in the room. Tried desktop/desktop, desktop/mobile. If i try to enable mobile data instead of wifi, the website crash everytime, try to reconnect, crash again.

**Comment by Besto-B** [comment]
We also did a test: Some of the users had to connect several times until audio worked. For some it never worked. There were different systems involved. Mainly firefox was the browser, mainly Ubuntu the operating system. Video froze after a while. The version was the latest stable one from yesterday March 17th 2020)

**Comment by contrapunctus-1** [comment]
@Besto-B there are known issues with Firefox - see https://github.com/jitsi/jitsi-meet/issues/4758#issuecomment-548795402

(I've had good experiences with Falkon, available in Debian repositories.)

**Comment by saghul** [comment]
F-Droid is also getting a new release with the latest fixes. It should be available tomorrow.

**Comment by cleitonflima** [comment]
I had the same issue with the Android app. I was connected with a VPN on my smartphone. After disable the VPN, I have sound and video working.

**Comment by NotSqrt** [comment]
Oh ! I'll test without blokada, then.

**Comment by contrapunctus-1** [comment]
Still an issue on v20.2.1 from F-Droid. Can rule out network issues, both were on the same WiFi.

**Comment by contrapunctus-1** [comment]
v20.2.3 from F-Droid has fixed it partially - the Nokia 6.1 can join and sends video, but causes a loud, constant screeching noise in the meeting.

**Comment by sebastienaubry** [comment]
Same for me: v20.2.3 from F-Droid seems to have fixed it. Thanks!
