### ISSUE TITLE
Build number

### ISSUE THREAD

**Issue by kinnla** [jitsi/jitsi-meet#500]
Is there a way to find out the build number (software version) of a jitsi meet server instance? E.g. through a key board shortcut. It would be helpful for debugging and error reporting.

**Comment by bgrozev** [comment]
For jitsi-meet itself, load the page, view the source and look for something like this:
"  <script src="libs/app.bundle.min.js?v=825"></script>"

The value of the "v" param is the jitsi-meet version.

**Comment by kinnla** [comment]
<img width="765" alt="captura de pantalla 2016-02-17 a las 0 29 22" src="https://cloud.githubusercontent.com/assets/3518808/13094829/983f2b4c-d50d-11e5-936e-f7366aedfdab.png">
So in this case it will be 730? That's odd, because the latest stable build at https://download.jitsi.org/jitsi/debian/ is 699, and according to our host we should run the latest stable build.
