### ISSUE TITLE
jitsi-meet cannot handle more than 2 on the same room 

### ISSUE THREAD

**Issue by nawafHinai** [jitsi/jitsi-meet#5010]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.
**
jitsi-meet that I have deployed, cannot handle more than 2 on the same room.
when third one enter the room stops steaming

**Comment by damencho** [comment]
Check the advanced section in the quick install network https://jitsi.org/qi, its either firewall, port forwarding or you missed to define private and public addresses in jvb config.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.
