### ISSUE TITLE
Audio is muted after a few seconds in TVBox

### ISSUE THREAD

**Issue by thorito** [jitsi/jitsi-meet#5015]
## Description
---
VideoConference from a mobile phone with integrated camera and a TVBox with external camera connected by USB 
The video conference starts correctly but you can see that the audio coming from the TVBox is very low and after about 10 seconds it is muted
The audio in the TVBox is heard very low and after some time it is muted. The video works correctly.

## Current behavior
---
The audio in the TVBox is heard very low and after some time it is muted.

## Expected Behavior
---
To work properly on USB-connected webcams

## Possible Solution
---

## Steps to reproduce
---

# Environment details
* Android Studio 3.5.3
* Windows 10 Enterprise
* Kotlin: 1.61
* Gradle: 3.4.1
* distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
* jitsi-meet-sdk: 2.5.1
* compileSdkVersion 29
* minSdkVersion 21
* buildToolsVersion "29.0.2"

---
* Webcams: Creative Labs VF0700, Creative Labs VF0790, Logitech HD720p Autofocus and AUSDOM AW625
* Mobile: OnePlus 5T, Google Pixel 3, Xioami Mi Mix2
* TVBox: Minix Neo U9-H (Marshmallow), AZW Beelink GT1 (Nougat), Mecool KM3 (Android TV Pie) and Nvidia Shield (Android TV Pie)

---
**Note**: Using gradle: '3.2.1' and Jitsi: 2.2.2, the audio works correctly but the device fails: Xioami MiMix2.
[TestJitsi.zip](https://github.com/jitsi/jitsi-meet/files/4118718/TestJitsi.zip)

**Comment by saghul** [comment]
>     * TVBox: Minix Neo U9-H (Marshmallow), AZW Beelink GT1 (Nougat), Mecool KM3 (Android TV Pie) and Nvidia Shield (Android TV Pie)

What TV box gives you trouble? All of them? What audio device are you using the external camera's USB mic?

**Comment by thorito** [comment]
There are two incidents: 

1) With the Creative VF0790 webcam, you hear distorted on all devices, with all other cameras the audio is correct.

2) If you use the Mecool KM3 and any other camera other than the VF0790; you hear the volume very low and after about 10-20 seconds it is muted.

NOTE: The Creative Labs VF0700 (older) does not distort the audio. 

Thank you

**Comment by saghul** [comment]
Do you observe anything relevant in adb? Without having the hardware it's hard for me to say what could be the cause, specially since it does work with other devices, so the problem may be in your Android device and the drivers it provides. But that' just a guess...

**Comment by thorito** [comment]
**Mecool KM3 & Creative Labs VF0700**
The video call is established between the PC to https://meet.jit.si/testAudio and the Mecool KM3 device.
The device uses the android application.
The first 15-20 seconds the audio is heard correctly but then it is muted.

The Mecool KM3 device has a remote control with a microphone.
You are listening to the audio from the control microphone and the webcam. 
Is it possible to deactivate the control microphone?

Log: _https://pastebin.com/wX1RPB9E_

Gradle: 3.5.3, Jitsi: 2.5.1

**Comment by thorito** [comment]
**NVidia Shield & Creative Labs VF0790**
The video call is established between the PC to https://meet.jit.si/testAudio and the NVidia Shield device.

The audio from the camera is heard distorted on the PC at all times.
It is never muted. 
Note: The NVidia remote control does not have a microphone

Log: https://pastebin.com/Q0ssYHKU

**Comment by thorito** [comment]
**NVidia Shield & Logitech HD 720p Autofocus
The video call is established between the PC to https://meet.jit.si/testAudio and the NVidia Shield device.

Everything has worked out well.
Note: The NVidia remote control does not have a microphone

Log: https://pastebin.com/8mWUBfTU

**Comment by saghul** [comment]
> **Mecool KM3 & Creative Labs VF0700**
> The video call is established between the PC to https://meet.jit.si/testAudio and the Mecool KM3 device.
> The device uses the android application.
> The first 15-20 seconds the audio is heard correctly but then it is muted.
> 
> The Mecool KM3 device has a remote control with a microphone.
> You are listening to the audio from the control microphone and the webcam.
> Is it possible to deactivate the control microphone?
> 
> Log: _https://pastebin.com/wX1RPB9E_
> 
> Gradle: 3.5.3, Jitsi: 2.5.1

I see this in the logs:

```
2020-01-29 18:36:23.760 12171-12236/com.sivsa.testjitsi D/JitsiMeetSDK: [modules/RTC/JitsiRemoteTrack.js] "onmute" event(1580319383755): RemoteTrack[userID: 1733c72f, type: video, ssrc: 2447819552, p2p: false, status: readyState: live, muted: true, enabled: true]
```

That means no video data was being received from the remote endpoint. This may explain why you experience a cut.

As for disabling the remote microphone, we don't select the microphone to use but let the system pick it. Maybe there is a setting to disable it in the system?

**Comment by saghul** [comment]
> **NVidia Shield & Creative Labs VF0790**
> The video call is established between the PC to https://meet.jit.si/testAudio and the NVidia Shield device.
> 
> The audio from the camera is heard distorted on the PC at all times.
> It is never muted.
> Note: The NVidia remote control does not have a microphone

I can only attribute this to bad driver support on the Shield, specially since it works well with Logitech cameras (I have tested it myself and you also mentioned it works well with the c920).

I honestly don't know if there is anything at all we can do to improve this, sorry.

**Comment by thorito** [comment]
Scenario: 

- With Jitsi: 2.2.2 and gradle: 3.5.3 the audio works correctly, but fails on the 4th connection attempt.

- With Jitsi; 2.5.1 and gradle: 3.5.3 does not fail on the following connections but mutes after 15-20 seconds.

Note: Device: Meecool KM3 and webcam: Logitech 720p.

With version 2.2.2 the microphone of the remote control does not work (ok) but with version 2.5.1 (yes, can it be that?)

https://pastebin.com/0wFu3mF9

Any idea?

Thanks

**Comment by saghul** [comment]
Yes! We made spedific audio device handing impeovements in 2.5, you should use that.

**Comment by thorito** [comment]
I think the problem is that it enrolls the remote control audio and not the webcam audio. Is it possible to change that behavior ?

Thank you

**Comment by saghul** [comment]
I honestly don’t know how. We only set the microphone to “on” and let the system decide.

**Comment by bademux** [comment]
Hi,
sorry if missed with issue:
Logitech c920pro webcam microphone doesn't work (no sound at all) on Xiaomi Mibox S Android TV (latest Android 9).
Latest Jitsi tested
Trueconf work well.
Let me know how I can help
