### ISSUE TITLE
Display Name is not used

### ISSUE THREAD

**Issue by Tobi696** [jitsi/jitsi-meet#5018]
Here's how I created the instance: 
```javascript
  new window.JitsiMeetExternalAPI("meet.jit.si", {
    roomName: `{this.chat_id}`,
    parentNode: document.getElementById("call-canvas"),
    userInfo: {
      displayName: "Tobi"
    }
  })
```

But Jitsi still calls me "Fellow Jitsier". I also tried the keys username and name. The E-Mail feature also doesn't work.
If I pass `userInfo: {
  email: "tobiwimma04@gmail.com"
}` , no profile picture is shown, although I have set a gravatar picture for this E-Mail.

**Comment by saghul** [comment]
@damencho when you added that in https://github.com/jitsi/jitsi-meet/commit/50f47961440c5784e3891b79fa010c77a3cfc5cd it was meant only for analytics, right? @Tobi696 You can send the command to change the display name, it's documented on the same README.

**Comment by damencho** [comment]
That was as we needed the email early in the execution to be able to pass it to callstats. Not sure why it would not work if you pass it ... I think that is a valid use case ...

**Comment by Jip-Hop** [comment]
I have this issue too.

```
  userInfo: {
    displayName: "JipTest", // Setting displayName here is not working...
    email: "email@jitsiexamplemail.com" // But email does work!
  },
```

Although I can confirm setting email via userInfo does work for me.

**Comment by fabrodz** [comment]
Same here, I don't know if it works for you guys, but the workaround I found was using:

`api.executeCommand ('displayName', 'New Nickname'); `

right after 

`var api = new JitsiMeetExternalAPI(domain, options);`

Hope it helps.

**Comment by ZedLove** [comment]
The documentation seems to suggest that passing `userInfo` would set the user's `displayName` for the call. Indeed, it says:

> You can set the userInfo(email, display name) for the call

If this option is not meant to set the name displayed to everyone in a call, that should be made clearer in the documentation. If the behaviour is meant to be as the documentation describes, this is a bug.
