### ISSUE TITLE
joining jisti-meet conference from jitsi client

### ISSUE THREAD

**Issue by abbas-aghamirzaei** [jitsi/jitsi-meet#502]
hello. 
i want to know if there is a way to join to a conference that is created by jitsi-meet from jitsi-clients such as client from windows or android.
thanks alot.

**Comment by abbas-aghamirzaei** [comment]
i mean video conference..

**Comment by bgrozev** [comment]
No: https://github.com/jitsi/jitsi-meet/issues/96
