### ISSUE TITLE
Surface Book screen sharing

### ISSUE THREAD

**Issue by csae7255** [jitsi/jitsi-meet#5024]
I'm using a Surface Book and when trying to share the screen with meet.jit.si I'm only allowed to share the web browser, or the full screen. The option to share another program is not available.
I tried with Firefox and Chrome.

On other Laptops everything works fine.

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

Screensharing is something we do not control and especially the UI for choosing screen/windows/tabs. You'd rather report it to the browsers issue tracker.
