### ISSUE TITLE
Repo for Fedora

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [jitsi/jitsi-meet#5029]
Hi,

any chance to get a Fedora repo?
or at least a tutorial to install jitsi-meet server on any linux distrib.

Thanks

**Comment by saghul** [comment]
We currently provide 3 ways to install Jitsi Meet:

- The quick install using our Debian packages (see the link in the README)
- Docker (see our docker-jitsi-meet repo)
- Manual install (also linked on the README though I wouldn’t recommend it)

Maintaining more systems / methods is not something we can commit to do. We don’t use Fedora so we wouldn’t know if something breaks and the effort to keep those packages working is not justifiable, sorry about that.

My recommendation if you use Fedora is to use the Docker setup.

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks, so maybe I can contribute a package for fedora.

**Comment by saghul** [comment]
Even if you do, we cannot commit to maintaining it or fixing any bugs in the packaging. If that’s ok with you, feel free to submit it!

**Comment by ROBERT-MCDOWELL** [comment]
I will do my best...

**Comment by zladuric** [comment]
@ROBERT-MCDOWELL hey, have you ever managed to do something about this?

**Comment by darkBuddha** [comment]
> I will do my best...

how's it going?

**Comment by ROBERT-MCDOWELL** [comment]
lack of time to achieve it, but I not give up

**Comment by ROBERT-MCDOWELL** [comment]
do you guys would be ready to help? so I can create a repo

**Comment by darkBuddha** [comment]
https://ask.fedoraproject.org/t/howto-jitsi-videoconference-server-on-fedora/10800

there are RPMs in a COPR repo now, got it working on Fedora 33.

**Comment by ROBERT-MCDOWELL** [comment]
great!
