### ISSUE TITLE
Caching users in the room and it isn't deleting them automatically.

### ISSUE THREAD

**Issue by contentadore** [jitsi/jitsi-meet#5030]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

## Description

We find caching users in the room and it isn't deleting them automatically.
Restarting of all processes isn't helping.
Please check it and help if possible.

## Current behavior

Eric settled here forever :)
https://i.imgur.com/zR7tniD.jpg

## Expected Behavior

We want to see this room without Eric.

## Possible Solution

I don't know. Seems it isn't cache in browsers.

## Environment details

- Ubuntu Server 18.04.4 LTS
- nginx version: nginx/1.14.0 (Ubuntu)
- jitsi-meet                         1.0.4101-1 
- jitsi-meet-prosody                 1.0.3729-1   
- jitsi-meet-web                     1.0.3729-1     
- jitsi-meet-web-config              1.0.3729-1   
- itsi-videobridge                  1126-1

**Comment by saghul** [comment]
If the user disconnected abruptly it may take up to a minute to vanish. This is to accommodate flaky connections in a graceful manner.

**Comment by contentadore** [comment]
> If the user disconnected abruptly it may take up to a minute to vanish. This is to accommodate flaky connections in a graceful manner.

Thanks. I know but this user settled there about 5 days ago.

**Comment by saghul** [comment]
Is the connection still active?

**Comment by damencho** [comment]
What is your prosody setting? Can you share it? It should have storage null/memory/none which will destroy the room data on restart and will prevent this from happening.

**Comment by contentadore** [comment]
> Is the connection still active?

No, the connection isn't already really active. But I see 2 duplicated users in our other room as active.
https://i.imgur.com/lQonPxh.jpg
They settled there about 3 days ago. And we decided to change room.



> What is your prosody setting? Can you share it? It should have storage null/memory/none which will destroy the room data on restart and will prevent this from happening.

Sure
Here are: 
- domain.com.cfg.lua
https://pastebin.com/PcaG8dnd
- prosody.cfg.lua
https://pastebin.com/ZTy64HE1
- migrator.cfg.lua
https://pastebin.com/tfLia93Y

@damencho Did you mean these sitting?
Thank you.

**Comment by contentadore** [comment]
> It should have storage null/memory/none

There is `storage = "none"`

**Comment by contentadore** [comment]
Oh, I restarted a prosody service and all the cached users were deleted.
I didn't know about "prosody". Thanks for the help! Hope it will work again.
