### ISSUE TITLE
ICE (TURN) default installation not working

### ISSUE THREAD

**Issue by grinono** [jitsi/jitsi-meet#504]
When i create a default easy installation in Ubuntu. The ICE negotiation is not working correct. As when testing behind a firewall no RTP is coming trough.
The firewall blocks everything except 80 and 443. so not UDP 10.000 20.000 is accepted.

The machine is running on a public IP (no NAT).
Any ideas how to fix this?

**Comment by damencho** [comment]
Please use the mailinglists for questions. 
By default jvb listens and on TCP port 4443, you need that port forwarded also and configure private and public addresses for jvb as described: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md#orgjitsivideobridgenat_harvester_local_address
And use chrome, as Firefox TCP support is currently not working with FF stable releases.

**Comment by grinono** [comment]
unfortunate port 4443 is not available behind this network. The machine is not in NAT so no need to configure the private addresses.
