### ISSUE TITLE
[FR] Screen sharing and camera at the same time

### ISSUE THREAD

**Issue by raphj** [jitsi/jitsi-meet#5040]
(Related: https://github.com/jitsi/jitsi-meet/issues/1491)

Hello,

So I defended my P.h.D thesis on December and I used Jitsi Meet (using the rendez-vous renater instance) so the jury members who could not be physically present could attend the presentation anyway. Thanks a lot for your work! It worked perfectly well!

I missed being able to stream myself and my presentation through screen sharing at the same time. I used two computers to achieve this, so the remote jury members could use the mosaic view to see both myself and the presentation at the same time (nice feature by the way! I think they chose to display only the presentation and see me through the small vignette but knowing they could use the mosaic view if they wished was great). The setup ended up working well but I had to borrow a computer for that and extensively test this more complicated than necessary setup. I could have used one computer but did not want one machine to handle the incoming streams twice (including itselves). It would probably have been laggy (with everything by WiFi, with one laptop CPU, it would have been a bit scary actually).

Being able to share the screen and the camera at the same time would require two streams but would be useful anyway. Remote presentations are common and Jitsi Meet is very close to be a perfect fit for this - and is already deployed at places where it is likely to be used for this :-)

**Comment by damencho** [comment]
My five cents here. There is not big value of watching a presentation in tile view mode.

**Comment by saghul** [comment]
We have a mode in which you can share your screen and your camera at the same time. We call it "presenter mode". Basically, once you start sharing your screen, unmute your video and you'll get this:

![Screen Shot 2020-02-05 at 09 06 13](https://user-images.githubusercontent.com/317464/73822711-fff51480-47f6-11ea-8754-57483fde93e2.png)

**Comment by raphj** [comment]
Nice :-)
I guess I did not figure out the user interface here.

**Comment by saghul** [comment]
We have not made this very obvious to be honest :-) Congratulations on your PhD!

**Comment by raphj** [comment]
Thanks!
