### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by jahanzebit** [jitsi/jitsi-meet#5043]
I have setup two servers for - Jitsi and Jibri .Ubuntu 18.04 LTS
After few secs of clicking the Rec button, it’s showing Rec failed
what I am looking for. Why does it fails and what is the solution?
Can anything be derived from the log? firewall also disabled 

meet.yourcloudcampus.com is the url 

/etc/prosody/prosody.cfg.lua
consider_bosh_secure = true;. this line also added

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

Check your jibri logs for errors.
