### ISSUE TITLE
room names in recent list are encodeded once the room name in UTF8 ( in Chinese in this case)

### ISSUE THREAD

**Issue by qivhou** [jitsi/jitsi-meet#5048]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
room names in recent list are encodeded once the room name in UTF8 ( in Chinese in this case)

## Current behavior
---
when I created 1 room with Chinese name, the meet was working well . But the room name was in encoded in the recent list.

## Expected Behavior
---
the room name should be decoded, once the room name in UTF8 (in Chinese in this case).

## Possible Solution
---
After I looked around the source code, in order to limit the affects to the other feature, the simple way to fixed it is to update line 180 in `react/features/base/react/components/web/MeetingsList.js` https://github.com/jitsi/jitsi-meet/blob/b30008e3a5895b3e78a76abab13c84ae024ee0e2/react/features/base/react/components/web/MeetingsList.js#L180 as following

```javascript

{ decodeURIComponent(title) }
```
Since I didn't check the mobile version, so I'm not sure if this issue in React-Native, but it's 99.99% sure.

## Steps to reproduce
---
1. start a meet with room name in UTF8.
2. exit the meet & check the recent list.

# Environment details
current stable version by following quick install.
---

**Comment by saghul** [comment]
Thanks for the report and the analysis! Sounds reasonable, care to make a PR?

**Comment by qivhou** [comment]
sure，I'll do it tomorrow

**Comment by qivhou** [comment]
Hi @saghul, pull request https://github.com/jitsi/jitsi-meet/pull/5054 created. please take your time to review & merge.

**Comment by Echolon** [comment]
@qivhou As I see, this has been merged. Thus I will close this. If there is anything else, we can reopen of course.

Thank you for your help!

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
