### ISSUE TITLE
Moderator/host authentication broken

### ISSUE THREAD

**Issue by paulvt** [jitsi/jitsi-meet#505]
We are running a setup with moderator/host authentication and a guest domain so that people can join freely once the conference is started (see http://lists.jitsi.org/pipermail/dev/2014-November/022609.html for the setup).  In recent weeks this feature broke down and hosts can no longer authenticate. Pressing the "I am the host" button that is popped up when starting a new conference, doesn't do anything anymore.
This issue might be related to #484, or at least the lib-jitsi-meet split-off?

Errors in de JS console:

    I: [/modules/xmpp/moderator.js] <Moderator.setFocusUserJid>:  Focus jid set to:  undefined
    I: [/modules/xmpp/moderator.js] <Moderator.createConferenceIq>:  Session ID: null machine UID: d29ce05006f211ac2d1ae575fcb565e5
    W: AuthHandler.js:105 Uncaught TypeError: Cannot read property 'isExternalAuthEnabled' of undefined
        authenticate @ AuthHandler.js:105
        (anonymous function) @ LoginDialog.js:231
        jQuery.event.dispatch @ jquery.js:4436
        elemData.handle @ jquery.js:4122
        jQuery.event.trigger @ jquery.js:4351
        (anonymous function) @ jquery.js:4902
        jQuery.extend.each @ jquery.js:375
        jQuery.fn.jQuery.each @ jquery.js:140
        jQuery.fn.extend.trigger @ jquery.js:4901
        (anonymous function) @ jquery-impromptu.js:271
        jQuery.event.dispatch @ jquery.js:4436
        elemData.handle @ jquery.js:4122
    W: [/modules/xmpp/moderator.js] <>:  Unauthorized to start the conference
        <iq xmlns=​"jabber:​client" type=​"error" to=​"cbbbf27e-6ab3-47b5-b720-a44e134042e8@guest.meet.domain.tld/​a600d3ef-3e37-4293-bf12-908bc1930b7b" from=​"focus.meet.domain.tld" id=​"2eff77b4-b52b-4aca-99cf-d86c58689251:​sendIQ">​…​</iq>​
    E: conference.js:167 CONFERENCE FAILED: conference.authenticationRequired

I am currently using 1.0.842, and I recall 1.0.760 working fine.

**Comment by isymchych** [comment]
Hi @paulvt ,
This issue should be fixed by https://github.com/jitsi/jitsi-meet/pull/499
Maybe it still happens because of caching?

**Comment by paulvt** [comment]
Hey @isymchych,
Indeed, going via the development tools window and purging cache and hard reloading worked.
Is there any way to bump anything so that non-technical users don't have to go through that?

**Comment by isymchych** [comment]
The easiest way is to manually edit https://github.com/jitsi/jitsi-meet/blob/master/index.html#L17 and specify current jitsi-meet version there, so browser will know that it should load file from the server.
More tricky way is to [configure caching](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching) on your http server.

**Comment by paulvt** [comment]
Alright, yes I thought so, but I'm using the nightly build deps and it seems that the version was actually bumped from v=833 to v=842 and that seems to have been ignored also. Weird.

**Comment by paulvt** [comment]
Something is still not right. I can go to a room, become moderator and thus start/open it. That's ok.
But, if I then leave the room and join another, I get "Conference focus - ... not available, retrying...".
However, I can still go back to the URL of the room I left before and become moderator there (repeatedly).

Restarting Jicofo seems to resolves the problem, but I don't plan to restart Jicofo every time I leave a room ;).

The JS console reports when joining the new/other room:

    E: [/modules/xmpp/moderator.js] <>:  Focus error, retry after 4000
        <iq xmlns=​"jabber:​client" type=​"error" to=​"e1b981ed-2426-4788-81d7-50524ddbbac9@guest.meet.domain.tld/​3170369b-b2d3-4cc1-9c49-1ab5232ff72c" from=​"focus.meet.domain.tld" id=​"5b62449a-a7f3-4b5a-9127-5db4625433e1:​sendIQ">
          ​<conference xmlns=​"http:​/​/​jitsi.org/​protocol/​focus" room=​"casualbirdsreckonslowly@conference.meet.domain.tld" machine-uid=​"d0a392d401e2b51fcbb4a5dc6be182f8" session-id=​"43313fbf-4776-4c6a-ac3c-c3e49a6b4c30">​…​</conference>
          ​<error code=​"406" type=​"MODIFY">​<not-acceptable xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-stanzas">​  </not-acceptable>​
            <text xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-stanzas" xml:lang=​"en">​machine UID mismatch or empty​</text>​
          </error>
        ​</iq>​
        (anonymous function) @ lib-jitsi-meet.min.js:9
        (anonymous function) @ app.bundle.min.js:29
        Strophe.Handler.run @ app.bundle.min.js:29
        (anonymous function) @ app.bundle.min.js:29
        Strophe.forEachChild @ app.bundle.min.js:28
        Strophe.Connection._dataRecv @ app.bundle.min.js:29
        Strophe.Bosh._onRequestStateChange @ app.bundle.min.js:30
    E: CONFERENCE FAILED: conference.focusDisconnected focus.meet.domain.tld 4

**Comment by paulvt** [comment]
Nevermind, I forgot to check the lib-jitsi-meet issues.  This is jitsi/lib-jitsi-meet#18.
Sorry for the noise.
