### ISSUE TITLE
Ubuntu installation 7 feb 2020

### ISSUE THREAD

**Issue by mathben** [jitsi/jitsi-meet#5053]
## Description
I had installation bug when following this guide : https://jitsi.org/downloads/ubuntu-debian-installations-instructions/

The error : 

> Config written to /var/lib/prosody/localhost.cnf
> Certificate written to /var/lib/prosody/localhost.crt
> 
> The given hostname does not exist in the config
> dpkg: error processing package jitsi-meet-prosody (--configure):
>  installed jitsi-meet-prosody package post-installation script subprocess returned error exit status 1

And the installation finish by :

> dpkg: dependency problems prevent configuration of jitsi-meet:
>  jitsi-meet depends on jitsi-meet-prosody (= 1.0.3729-1); however:
>   Package jitsi-meet-prosody is not configured yet.
> 
> dpkg: error processing package jitsi-meet (--configure):
>  dependency problems - leaving unconfigured
> Setting up jitsi-meet-web (1.0.3729-1) ...
> No apport report written because the error message indicates its a followup error from a previous failure.
>                                                                                                           Processing triggers for systemd (240-6ubuntu5.8) ...
> Errors were encountered while processing:
>  jitsi-meet-prosody
>  jitsi-meet
> E: Sub-process /usr/bin/dpkg returned an error code (1)

## Steps to reproduce
sudo apt-get -y install jitsi-meet

# Environment details
Ubuntu 19.04 up to date.

**Comment by damencho** [comment]
Try purging and installing with dns not localhost.

**Comment by mathben** [comment]
What do you mean by dns not localhost?
I keep localhost empty when the configuration ask it.

**Comment by damencho** [comment]
Yes, there you should enter the dns that you will use to access your deployment like meet.jit.si. I suspect that prosody has already configured a host named localhost and as you try to configure a second one and it fails.

**Comment by mathben** [comment]
When I apt purge jitsi* and install again, the prompt to enter the hostname doesn't show anymore.
The installation fail again with the same error.

New test, I copy the file /var/lib/prosody/localhost.cnf, change DNS.0 to meet.jit.si, purge all, move it in /var/lib/prosody, reinstall.

Now got a new error in LUA :
```
lua5.2: /usr/bin/prosodyctl:1286: /usr/lib/prosody/util/prosodyctl.lua:51: attempt to index local 'char' (a nil value)
stack traceback:
	/usr/lib/prosody/util/prosodyctl.lua:51: in function 'getchar'
	/usr/lib/prosody/util/prosodyctl.lua:88: in function 'show_yesno'
	/usr/bin/prosodyctl:499: in function 'use_existing'
	/usr/bin/prosodyctl:521: in function 'config'
	/usr/bin/prosodyctl:626: in function </usr/bin/prosodyctl:619>
	(...tail calls...)
	/usr/bin/prosodyctl:1368: in function 'func'
	/usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
stack traceback:
	[C]: in function 'error'
	/usr/bin/prosodyctl:1286: in function 'handler'
	/usr/lib/prosody/util/async.lua:211: in function 'run'
	/usr/bin/prosodyctl:1371: in main chunk
	[C]: in ?
/var/lib/prosody/localhost.cnf exists, do you want to replace it? [y/n] dpkg: error processing package jitsi-meet-prosody (--configure):
```

Do you know how to set hostname during installation instead using a command prompt who doesn't show? Why the purge doesn't fix the configuration of the hostname?

Thanks!

**Comment by damencho** [comment]
Are you purging using this command: https://jitsi.org/qi#uninstall ?

**Comment by mathben** [comment]
Succeed, I forgot to uninstall jigasi.
Thanks!

**Comment by deepdad** [comment]
I got a similar error. I do use a domain name.

<img width="617" alt="Screenshot 2020-02-14 at 16 00 53" src="https://user-images.githubusercontent.com/22483621/74542703-5e7f6880-4f44-11ea-8ebc-fb5455454ca6.png">

But it was solved by (re-)commenting server_names_hash_bucket_size 64; in nginx.conf and restarting the nginx service.
