### ISSUE TITLE
Hide or show UI

### ISSUE THREAD

**Issue by danboid** [jitsi/jitsi-meet#506]
I would like to use JM for webcasting but one of the features its currently missing is the ability to hide or show its UI with a context menu or keyboard shortcut.

Hiding the UI would hide the window that shows your webcam (or the webcams of other secondary callers) output on top of the other caller(s) so that only the video stream from the currently active speaker is displayed in the JM tab/window.

**Comment by damencho** [comment]
There is hide filmstrip button and shortcut.
