### ISSUE TITLE
currenlty Jitsi-meet ios mobile appliaction is not able to buy in Applestore China region

### ISSUE THREAD

**Issue by p31415926** [jitsi/jitsi-meet#5062]
Could you please help launch your ios application for China applestore？

**Comment by saghul** [comment]
You need to disable CallKit. All you have to do is set enabled to false in JMCallKitProxy. You can do this as soon as your app starts.

**Comment by p31415926** [comment]
@saghul 
What do you mean ?  Do you mean i can build Iphone client by my self with disable CAllkit?

**Comment by saghul** [comment]
Yes. We don’t offer it in China due to the CallKit restriction. You are welcome to build it yourself though.
