### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by foxis1986** [jitsi/jitsi-meet#5063]
Hi.
You very cool!!!
When stream on youtube will be work?

**Comment by damencho** [comment]
If you have questions use the forum. It works, we streamed The Call today.

**Comment by foxis1986** [comment]
I'm sorry to disturb You. I checked the forum but didn't find a solution to my problem. I go to the site http://meet.jit.si/ but when I try to start "start live sream" I get the error "live streamng unavailable". For several days now. Please Help me figure out what the problem is!

**Comment by damencho** [comment]
@foxis1986 I just tested it and it works. Do you experience the same at the moment, can you try again?
