### ISSUE TITLE
Fail to connect to jitsi meet by chrome browser(when more than one user)

### ISSUE THREAD

**Issue by petjiang** [jitsi/jitsi-meet#5064]
1st user connects to jitsi meet by chrome and create a meeting is ok , and video and audio is fine.

when the 2nd user connected to the meeting created by the 1st user, both session quit and chrome webpage shows :

" Unfortunately, something went wrong. "
"we're trying to fix this. Reconnecting in xx sec..."

And fail once and once again ...

-----------------
Enviroments:
my jitsi meet server is running on docker with the scripts provided by github project :"jitsi/docker-jitsi-meet". following the project instructions to configurate.

what I missed ?

**Comment by saghul** [comment]
Please post in our community (https://community.jitsi.org/) as this is an issue with your deployment rather than with the software itself.
