### ISSUE TITLE
Livestream dont work

### ISSUE THREAD

**Issue by GeraldHangweyrer** [jitsi/jitsi-meet#5067]
From Yesterday 7 pm i cant start a Jitsi Lifestream
please help
Thanks, Gerald

**Comment by damencho** [comment]
Please use the community forum when having problems or questions before opening new issues.
What is the experience, what happens? We successfully streamed yesterday TheCall I was testing the same and this morning and everything seems to work just fine.

**Comment by GeraldHangweyrer** [comment]
I read: Live-Streaming is for unternehmerbund@gmail.com not activatet - please activate. i dont know, where i can do that. Till now i already startet a lot of Livestreams - now i cant animore -

**Comment by damencho** [comment]
@GeraldHangweyrer have you tried this: https://support.google.com/youtube/answer/9227509
