### ISSUE TITLE
Multiple call admins

### ISSUE THREAD

**Issue by danboid** [jitsi/jitsi-meet#507]
Currently, the way JM works is the person who started the call gets admin rights and can kick others from the call. However, if the original admin's (the call starter's) connection drops they lose admin rights and they get passed onto another user. 

The person who starts the call should be able to assign additional admins so that the right person (or people) gain control and they can then re-assign the dropped admin their rights when they re-join the call in a similar way to how IRC channels and Mumble rooms work.

**Comment by agsupport** [comment]
What if they could create an “admin” code.  Just like in Join.me or gotomeeting when you call in you have to put in the “admin” code to have all the features such as recording the meeting and kicking people out.  That way you don’t have to reassign the admin.  They could select a button as “admin role” and reenter the code.

What do you think about that?

**Comment by danboid** [comment]
Yes, I like the idea of an admin code that the call starter sends to those they want to be admins that they can enter themselves to regain admin rights.

Good suggestion agsupport, thanks!

**Comment by ecafe9901** [comment]
Yes, I like the idea either.
