### ISSUE TITLE
Coop with react-native-keyboard-tracking-view

### ISSUE THREAD

**Issue by djorkaeffalexandre** [jitsi/jitsi-meet#5070]
Hi. 👋 
I'm using `JitsiMeetSDK` on an app that have `react-native-keyboard-tracking-view`, but when I add pod for `JitsiMeetSDK` this causes a weird behaviour on `react-native-keyboard-tracking-view`.
I'm trying to find the cause of the error, but how you have more knowledge about the `JitsiMeetSDK` code, maybe you can know what's happening.

## Current behavior
![](https://media.giphy.com/media/QWLfaurlXRCaDuPyTO/giphy.gif)

## Expected Behavior
![](https://media.giphy.com/media/XbJTpZQQ8nHRCNnw2S/giphy.gif)

## Steps to reproduce
[Reproducible demo](https://github.com/djorkaeffalexandre/jitsi-keyboard-tracking).
Run `yarn` and `react-native run-ios`.
Try to hide the keyboard slowly scrolling the list.

# Environment details
JitsiMeetSDK -> 2.5.1

**Comment by saghul** [comment]
Is the Jitsi view inside that other view or just by having it as a dependency things go weird?

**Comment by djorkaeffalexandre** [comment]
Just add pod to `JitsiMeetSDK` and things go weird :(

**Comment by saghul** [comment]
can you try 2.6.0 ?

**Comment by djorkaeffalexandre** [comment]
Yes. Same problem with `2.6.0`.
I found that this [delegate method](https://github.com/wix/react-native-keyboard-tracking-view/blob/master/lib/ObservingInputAccessoryView.m#L62) is not called when `JitsiMeetSDK` is in the project .

**Comment by saghul** [comment]
I'll see if I ccan find something related, but this is really weird!

**Comment by djorkaeffalexandre** [comment]
Hey @saghul! Thanks for all quickly responses!
I'm doing a patch on `react-native-keyboard-tracking-view` now to fix this error, but it looks a behavior provided by add `JitsiMeetSDK` on any project React Native.
Look that when we add `JitsiMeetSDK` on a React Native project, all comparisons about classes return wrong value in Objective-C, a while ago I tried to coop between `realm-js` and `JitsiMeetSDK` and I found this [error](https://github.com/realm/realm-js/pull/2456/files#diff-5a43c4ca08305e203ab6bac4051e5f8cR309), and now, the error is same, when you try to use `isKindOfClass` in any module with a project with `JitsiMeetSDK` included it always evaluates to `false`.
I would like to know if it's an expected behavior?

**Comment by saghul** [comment]
> I would like to know if it's an expected behavior?

Of course not 😢 The SDK itself uses React Native but none of its symbols are exported, so I honestly don't know how / why it can cause this problem. I wonder if the symbols are not really hidden as I think they are...

**Comment by djorkaeffalexandre** [comment]
I'll close it for now.
I'll try to do one most basic reproducible demo for we investigate it.
Your help is very wonderful.
Thanks again!

**Comment by saghul** [comment]
Thanks @djorkaeffalexandre . If you have a small test project which can repro the issue that would be immensely helpful. Cheers!

**Comment by djorkaeffalexandre** [comment]
Hey man, sorry about spent your time, but [here](https://github.com/djorkaeffalexandre/jitsi-tracking-view) you can see a small test project. I only started a new react-native project and added [pod](https://github.com/djorkaeffalexandre/jitsi-tracking-view/blob/master/ios/Podfile#L37) to `JitsiMeetSDK` and [this line](https://github.com/djorkaeffalexandre/jitsi-tracking-view/blob/master/ios/jitsitest/AppDelegate.m#L24) of log.
When you add the pod `JitsiMeetSDK` the log shows `no` and when you remove it shows `yes`.
It's really weird. I really thanks if you have some time to test this.
Thanks.

**Comment by saghul** [comment]
I think I know what the problem is, but I don't know how to fix it: JitsiMeetSDK also uses react native, so the ObjC runtime has those classes (RTCRootView and so on) already registered at runtime. So, your app is compiled with *your* RN version and our SDK with *our* version, and even if they match, it's 2 sets of symbols in tthe ObjC runtime. Somehow tthe SDK gets loaded later so it overrides the symbols I think, that's why you get something else.

Can you test this? Get the NSBundle for RCTRootView with https://developer.apple.com/documentation/foundation/nsbundle/1417717-bundleforclass and then print its `resourceURL` I bet it's inside JitsiMeetSDK.

**Comment by djorkaeffalexandre** [comment]
@saghul yep, you're right, JitsiMeetSDK override some classes, sorry for the delay.
Do you know if there is something that we can do to prevent things like this?
We're facing some errors like this https://github.com/facebook/react-native/issues/18563#issue-308539176
I think they are also related to JitsiMeetSDK, looks like we have two bundles running and one is changing things on the other.
WDYT?

**Comment by saghul** [comment]
I'm not sure how to solve this, I'm afraid.

**Comment by djorkaeffalexandre** [comment]
Thanks man! If we find some way I'll let you know. :)

**Comment by saghul** [comment]
Thanks and good luck!
