### ISSUE TITLE
Access issues

### ISSUE THREAD

**Issue by skyhuihui** [jitsi/jitsi-meet#5071]
https://github.com/jitsi/jitsi-meet/blob/master/doc/development.md

Hello, I use make dev to launch the web test.Only viewable at localhost:8080, which I need to access via IP +port, the expected netstat -netl effect after boot should be 0.0.0.0:8080 instead of 127.0.0.1:8080.Where do I need to change the configuration

**Comment by damencho** [comment]
Please when having questions and problems use the community forum before opening new issues.

`make dev` runs a localhost proxy, which is for developers to easily change the UI and see the changes immediately, to speed development. It is meant to be localhost. If you want to access your modifications from the internet you need to deploy them on a machine.

**Comment by skyhuihui** [comment]
I deployed it on ubuntu18.04 and ran it with make dev, I don't know what I need to change to access it via Ip+port

**Comment by damencho** [comment]
To deploy it use https://jitsi.org/qi

**Comment by skyhuihui** [comment]
I used the remote development plug-in of vscode with ubuntu18.04 to make the project run on ubuntu18.04. The problem I encountered was that the machine was not accessible and the running effect could not be seen.Please tell me what configuration file I should modify, thank you very much

**Comment by damencho** [comment]
`make dev` is supposed to be run on your dev machine.
You can install and configure the packages on your ubuntu machine and then compile and deploy it from source code. This had been mentioned many times in the forum
https://community.jitsi.org/t/jitsi-users-jitsi-meet-manual-install/12745/3?u=damencho

**Comment by skyhuihui** [comment]
ok, thank you
