### ISSUE TITLE
Better variable naming

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/jitsi-meet#5082]
First off, I want to say that I came to install jitsi some years ago, and the forum you developped in the community and the documentation improved a lot. It is beautiful to see, and I found a lot of valuable information there. So I'd like to first send you a big thank you for this effort, it is nice to see and really helpful for users like me.

Then, my feature request is a small one.

When you name things in the code or configuration, please use positive variables.

Here some context about it, http://davej.io/2018/05/negative-naming.html better than I could explain.

Here is an example:
https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/config.js#L421-L423

It would be a lot easier to read and understand if it was this form:
```
    // If false, any checks to handoff to another application will be prevented
    // and instead the app will continue to display in the current browser.
    // default to true
    // deepLinking: true
```

I know you'll not rewrite all the variables, but this is something to consider for the future variables :)

Hope it helps, and feel free to close it once you read it. Thanks again for the really nice project and community you are building around it!

**Comment by saghul** [comment]
> First off, I want to say that I came to install jitsi some years ago, and the forum you developped in the community and the documentation improved a lot. It is beautiful to see, and I found a lot of valuable information there. So I'd like to first send you a big thank you for this effort, it is nice to see and really helpful for users like me.

Thank you for saying that!



> When you name things in the code or configuration, please use positive variables.
> 
> Here some context about it, http://davej.io/2018/05/negative-naming.html better than I could explain.
> 
> Here is an example:
> https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/config.js#L421-L423
> 
> It would be a lot easier to read and understand if it was this form:
> 
> ```
>     // If false, any checks to handoff to another application will be prevented
>     // and instead the app will continue to display in the current browser.
>     // default to true
>     // deepLinking: true
> ```
> 
> I know you'll not rewrite all the variables, but this is something to consider for the future variables :)

I couldn't agree more. We've been talking about re-doing our config for quite a while now. Yes, the plan involves renaming everything to stuff that makes sense and grouping options instead of using things like desktopSharingFoo desktopSharingBar desktopSharingBaz. Obviously this is not a simple change and we need to retain backwards compatibility for a while, but I'm hoping we can get to it sooner rather than later.

Thanks a lot for your feedback!

**Comment by pierreozoux** [comment]
Really nice to hear :) As there is nothing actionable on your side, I'll just close it :)

Have a wonderful weekend ;)
