### ISSUE TITLE
Video recording problem

### ISSUE THREAD

**Issue by newCharlie** [jitsi/jitsi-meet#5088]
Hello!The manager!
I deployed the jitsi-meet server and the jibri server, but there were problems while I was recording
![image](https://user-images.githubusercontent.com/19547452/75084867-50da6c00-555e-11ea-81f6-104ea55e7965.png)
Please help me out！
blessing

**Comment by saghul** [comment]
Please post in our community forum. Include logs from jibri, jicofo and the JS console please.
