### ISSUE TITLE
Bundle policy with the value max bundle

### ISSUE THREAD

**Issue by piyushl85730** [jitsi/jitsi-meet#5089]
i am using latest framework release 
https://github.com/jitsi/jitsi-meet/releases/tag/3850

when i tried to run project it works fine but once i connect any call it crashed with this details. Would you please help me with this @saghul 

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-22 at 11 37 45](https://user-images.githubusercontent.com/59352194/75087603-7ff5db00-5568-11ea-89d1-b49a8f9a0703.png)

Testing details
iOS 13.3 
xcode 11.3.1

**Comment by PinkeshGjr** [comment]
i am also facing same issue @saghul Would you please help us. That would be really helpful.

**Comment by saghul** [comment]
Can you reproduce this reliably every time? Only in debug mode or does it also show up in release mode? Only on iOS or also android?

**Comment by PinkeshGjr** [comment]
Facing this issue every-time when someone join or may be "Not sure because this happen only while call is connected" leave call.

Haven't tried in release mode i tried using it in debug only in iOS.

**Comment by saghul** [comment]
I’ll try to repro.

**Comment by saghul** [comment]
I haven't been able to reproduce it on the simulator. Did you reproduce it on a phisical device or a simulator? What iOS version?

**Comment by PinkeshGjr** [comment]
i used simulator with iOS 13.3 and xcode Version 11.3.1 (11C504)

**Comment by saghul** [comment]
I haven't been able to reproduce this netiher with the simulator or a real device.

**Comment by naveenprakash74** [comment]
anyone get the solution I also facing the same error when I join call after 5-10 second I got this error

**Comment by luixxiul** [comment]
@naveenprakash74 do you get the exact same screen on the first post?

**Comment by naveenprakash74** [comment]
> @naveenprakash74 do you get the exact same screen on the first post?

Yes

**Comment by pstmamao** [comment]
Any update on this?

**Comment by AjayShivanagol** [comment]
Any update on this?

**Comment by saghul** [comment]
I never managed to reproduce this. Can you?

**Comment by AjayShivanagol** [comment]
@saghul I can reproduce this on the emulator debugger mode.

Name: Pixel_2_API_28
CPU/ABI: Google Play Intel Atom (x86_64)
Path: /home/ajay/.android/avd/Pixel_2_API_28.avd
Target: google_apis_playstore [Google Play] (API level 28)

I was switching between WiFi and Mobile Internet. it was not constant through 10 out of 3 times I can reproduce.
