### ISSUE TITLE
Avatars in the middle of the screen do not disappear when enabling the pad

### ISSUE THREAD

**Issue by jaragunde** [jitsi/jitsi-meet#510]
When I'm in a conference with some people who's not sharing their webcam, it may happen that their avatars remain in the middle of the screen if I open the etherpad while they are speaking, like in the attached screenshot.

I have been able to reproduce this issue in Chrome 48.0.2564.109 (64-bit) and Firefox 44.0, on a Fedora 22 Linux distro.

![captura de pantalla de 2016-02-19 16-24-42](https://cloud.githubusercontent.com/assets/2900877/13179717/6f8a153a-d725-11e5-8a67-6d525d30f51e.png)

**Comment by gpolitis** [comment]
This must be a CSS related regression with the new meet.

**Comment by jaragunde** [comment]
This hasn't happened for a while :) Thanks!
