### ISSUE TITLE
Cannot run React Native app: "Attempting to change the getter of an unconfigurable property."

### ISSUE THREAD

**Issue by rcidt** [jitsi/jitsi-meet#5102]
## Description
I am not able to run the React Native app. 

When running I receive the following error:

```
TypeError: Attempting to change the getter of an unconfigurable property.

defineProperty
    [native code]:0
<global>
    index.js:4
forEach
    [native code]:0
<global>
    index.js:4
loadModuleImplementation
    require.js:322:6
<global>
    actions.js:5
loadModuleImplementation
    require.js:322:6
<global>
    index.js:3
loadModuleImplementation
    require.js:322:6
<global>
    index.native.js:16
loadModuleImplementation
    require.js:322:6
<global>
    index.ios.js:1
loadModuleImplementation
    require.js:322:6
guardedLoadModule
    require.js:201:45
global code
    index.bundle?platform=ios&dev=true&minify=false:279996:4
```

![image](https://user-images.githubusercontent.com/37703740/75810354-6e76b500-5d58-11ea-88f0-b1fcbebf0d9c.png)

---

## Current behavior

Cannot run React Native app

---

## Expected Behavior

Should be able to run React Native app

---

## Possible Solution

I have tried cleaning caches, re-cloning repo, different node/npm version, etc.
Nothing seems to work.

---

## Steps to reproduce

```
npm install
react-native run-ios
```

---

# Environment details

```
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.50 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9 => 16.9.0
    react-native: github:jitsi/react-native#efd2aff5661d75a230e36406b698cfe0ee545be2 => 0.61.5-jitsi.1
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

---

**Comment by saghul** [comment]
Have you made any changes to the code?

**Comment by rcidt** [comment]
@saghul no

**Comment by saravanakumargn** [comment]
try clear the cache
```
npx react-native start --reset-cache
```

**Comment by saghul** [comment]
This should've been fixed already.

**Comment by azeezat** [comment]
Check to see if you are not directly rendering something inside SafeAreaView

Ensure you are following this format

`<SafeAreaView>
      <View>
          {children}
        </View>
      </View>
    </SafeAreaView>`

**Comment by jeremyfrancis** [comment]
To resolve this I started by trying to get just a blank View to display on the simulator screen. This then helped me find the real issue which was in my index.js

For expo web bear you have to use the registerComponent() function as is already in there. However, for mobile you need to use the regular React Native form:

`AppRegistry.registerComponent("AppName", () => App)`

This did it for me then I just had to work through some other issues in our codebase.
