### ISSUE TITLE
Privacy when entering a meeting room. (webcam and the micrófono)

### ISSUE THREAD

**Issue by EdZava** [jitsi/jitsi-meet#5110]
**Is your feature request related to a problem you are facing?**
Privacy when entering a meeting room.

**Describe the solution you'd like**
Before connecting to a room via a web browser, I should be able to indicate if I want the webcam and the micrófono to be activated by default or not.

**Describe alternatives you've considered**
It would be best to have 2 buttons as in the iOS app where you could indicate before connecting if you want the webcam and microphone activated or not.

**Comment by saghul** [comment]
We are currently working on this already, it should be available in a few weeks time!

**Comment by l3d00m** [comment]
Hi, I'm going to close this in favour of #2737, which proposed something very similar. Either way, your request should be implemented shortly!
