### ISSUE TITLE
Integrate React Navigation v4

### ISSUE THREAD

**Issue by tushargoyalofficial** [jitsi/jitsi-meet#5115]
First of all, thanks for such a great platform, really appreciate your work into it. Really inspirational.

I want to use your source code and want to create some pages over it. We are using RN v0.61 and trying to integrate **react native router flux**, in though it uses **react navigation v4** as it's base. Now, I want to use router flux so as to navigate among pages which I am creating over jitsi, but I am unable to do so.

Also we though of to go with **React navigation v5** only, discard router flux, but still unable to integrate the same. Issue persist whenever we try to use **react native gesture handler**, which in turn required for react navigation to work.

I will be sharing the screenshot of the issue as well. It would be really great if you guys can help me out int this.

![Screenshot 2020-03-06 at 7 55 45 PM](https://user-images.githubusercontent.com/24288879/76091942-65156480-5f73-11ea-83e4-0622cf1a34c5.png)

Thanks in advance, cheers!

**Comment by saghul** [comment]
Looks like the gesture handler module wasn't properly linked: https://github.com/software-mansion/react-native-gesture-handler/blob/master/Directions.js#L3

Note that this is not your standard RN app. You'll need to link manually. Add the packages here: https://github.com/jitsi/jitsi-meet/blob/fd8fb58eaf3d42d0952d6bc99be46d05adce4a89/android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java#L206

**Comment by tushargoyalofficial** [comment]
@saghul : Thanks for the reply. I have searched about it, yes it not properly linked. The main problem is I am a JS developer and not having any idea about the Andoird Java/XML native things.

I have also found about this file too, I.e. ReactInstanceManagerHolder.java, but again I don't know how to integrate the code.

If you follow the link, [https://reactnavigation.org/docs/4.x/getting-started](url)

I stuck here, how to write this code into that file

=================================================================
package com.reactnavigation.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }
+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+        return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}
=================================================================

Also, I have to manually link the gesture handler as it start giving error I.e. Unable to find **com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView** package.

I know I am asking it like a fool but sorry as having no knowledge of Android things, also apologies for my bad English.

Thanks for the help

**Comment by jonnysu** [comment]
hi,i don't even know how to run it in react-native.stucked from very beginning. thanks~~

**Comment by harleyxx1** [comment]
@tushargoyalofficial have you fixed it? If so, can you tell me how you did it?

**Comment by tushargoyalofficial** [comment]
> @tushargoyalofficial have you fixed it? If so, can you tell me how you did it?

Yes, go to this file

https://github.com/jitsi/jitsi-meet/issues/5115#issuecomment-595799215

and for react-navigation, gesture needs to work, so for that, you have to write this
new com.swmansion.gesturehandler.react.RNGestureHandlerPackage()

that's it. Rest navigation will start working. Also, go with RN Navigation v5.

**Comment by lironsher** [comment]
Do we have a pr on this?

**Comment by goappycodes** [comment]
> > @tushargoyalofficial have you fixed it? If so, can you tell me how you did it?
> 
> Yes, go to this file
> 
> [#5115 (comment)](https://github.com/jitsi/jitsi-meet/issues/5115#issuecomment-595799215)
> 
> and for react-navigation, gesture needs to work, so for that, you have to write this
> new com.swmansion.gesturehandler.react.RNGestureHandlerPackage()
> 
> that's it. Rest navigation will start working. Also, go with RN Navigation v5.

added this but now getting this error

jitsi/meet/sdk/ReactInstanceManagerHolder.java:200: error: package com.swmansion.gesturehandler.react does not exist
                new com.swmansion.gesturehandler.react.RNGestureHandlerPackage(),

**Comment by sheywesk** [comment]
> > > @tushargoyalofficial have you fixed it? If so, can you tell me how you did it?
> > 
> > 
> > Yes, go to this file
> > [#5115 (comment)](https://github.com/jitsi/jitsi-meet/issues/5115#issuecomment-595799215)
> > and for react-navigation, gesture needs to work, so for that, you have to write this
> > new com.swmansion.gesturehandler.react.RNGestureHandlerPackage()
> > that's it. Rest navigation will start working. Also, go with RN Navigation v5.
> 
> added this but now getting this error
> 
> jitsi/meet/sdk/ReactInstanceManagerHolder.java:200: error: package com.swmansion.gesturehandler.react does not exist
> new com.swmansion.gesturehandler.react.RNGestureHandlerPackage(),

I also have this error,any solution ?

**Comment by fajarism** [comment]
There are two more steps after adding RNGestureHandlerPackage in jitsi/meet/sdk/ReactInstanceManagetHolder.java.
1. In android/sdk/build.gradle, add this code in dependencies block
```
dependencies {
 ...
 ...

 implementation project(':react-native-gesture-handler') //add this code
}
```

2. Now, go to top level settings.gradle (android/settings.gradle) and add this code
```
include ':react-native-gesture-handler' 
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android') 
```

Hope this helps

**Comment by FinSlate** [comment]
Hi @tushargoyalofficial I'm trying to integrate React Navigation 5 in to a jitsi-meet project of my own, adding my own screens etc.. Where do you put the <NavigationContainer>. Do you place it in 'index.native.js' or in 'WelcomePage.native.js'? 
Somewhere else? 

I have done all the steps mentioned by you and @fajarism  above and the errors that I get say that RNSafeAreaProvider is not in the UIManager. I have safe-area-context linked as well as the correct configuration for react-native-gesture-handler. 

Thanks and Regards

**Comment by FinSlate** [comment]
For anyone else that runs in to the issue. I have solved it. I had to follow the steps for safe-area-context but instead of MainActivity.java I had to link the package to ReactInstanceManagerHolder.java

Which is interesting because I should have know this because I went through the entire process for react-native-gesture-handler...

It wasn't an issue with react-navigation or where to place the NavigationContainer at all.[](url)

**Comment by saghul** [comment]
Thanks for sharing!
