### ISSUE TITLE
hello i am very new to this jitsi-meet. want to develop react-native with it

### ISSUE THREAD

**Issue by jonnysu** [jitsi/jitsi-meet#5117]
hello guys , i am newbie for develop videocall in mobile, and dont know how to build this demo, please tell me how start a demo in this jitsi-meet.

i have downloaded jitsi-meet.and try to run react-native run-android to build and play in mobile.but it didn't work. i think i use the wrong command or wrong way to build this demo when i following the article [mobile.md](https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md)

**Comment by saghul** [comment]
Please use our community (https://community.jitsi.org) for these questions.
