### ISSUE TITLE
external webcam problem with chrome

### ISSUE THREAD

**Issue by pasquale979** [jitsi/jitsi-meet#5120]
if i use chrome, the external webcam does not work. if I use firefox it works instead. do I have to enable something?

**Comment by saghul** [comment]
What webcam is it? Can you try https://test.webrtc.org/ and let us know if it works there?

**Comment by alexanderadam** [comment]
Isn't this a duplicate of #5155?

**Comment by saghul** [comment]
No follow-up, I'm closing this one.
