### ISSUE TITLE
feature request: support multiple audio streams

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#5121]
For events with live translation service, remote participants would like to choose a certain language track. Either live or one of the translated audio tracks. 

Some thoughts: 

- Two languages would be possible using stereo #2395  
- Does Jitsi also support surround (with up to 7.1 audio tracks)?

Stereo works only when switching off P2P and diabling echo cancellation by adding `#config.p2p.enabled=false&config.disableAP=true&config.disableAEC=true` to the URL.

**Comment by rasos** [comment]
I successfully tested playing a Dolby surround video from one Jitsi Meet client and enjoying surround at a 7.1 amplifier via a web browser and optical Aureon 5.1 output, using above parameters.

**Comment by lvoogdt** [comment]
Sadly this is not working for me with none of the parameters. Using the latest self hosted stable and jitsu-meet on chrome/brave/firefox on osx. Seems @rasos had this working. The sounds stays mono/low bitrate no matter what i try (changing parameters in url and config.js)

**Comment by omertoledano** [comment]
@rasos @lvoogdt I'm interested in this feature as well, did you make any progress?

**Comment by metasj** [comment]
@cpunkzzz @rasos same here, it's a nice idea for a simple hack for two languages -- which covers the easy 80% of live translations.

**Comment by rasos** [comment]
Be careful, activating stereo is also switching off noise cancellation.

Meanwhile we have developed a feature complete solution for live translation for multiple languages including bridge translations for BigBlueButton https://git.fairkom.net/chat/fairblue/-/wikis/home
