### ISSUE TITLE
Working version of jitsi meet with Cordova

### ISSUE THREAD

**Issue by slothstronaut** [jitsi/jitsi-meet#5122]
Hi there Jitsi team!

After doing a considerable amount of leg work trying to get my cordova app to play nicely with Jitsi, I ended up creating my own repo which merged in changes from two different repos:

https://github.com/findmate/cordova-plugin-jitsi-meet/

This version of the cordova plugin is able to build and submit to both Apple and Play store, and is being used in production in my app. 

I tried several different plugins and none of them worked, so perhaps you could suggest in some official capacity for cordova users to use this repo as all of the others will lead to issues.

The plugins were merged from:

https://github.com/gaganinvic/cordova-plugin-jitsi-meet (this version worked in iOS but not Android; did not satisfy 64-bit requirement)

https://www.npmjs.com/package/cordova-plugin-jitsi-meet (This version works in Android, but does not include anything at all for iOS)

Thanks for your consideration

**Comment by saghul** [comment]
Hi there! Thanks for sharing this!

We currently don’t have a god place to share third party Jitsi integrations duchas this one. How about editing a page on the wiki here? You should be able to do that directly.

**Comment by slothstronaut** [comment]
Sure, I created this: https://github.com/jitsi/jitsi-meet/wiki/Using-Jitsi-Meet-React-Native-SDK-with-Cordova

Let me know if that works. Cheers!

**Comment by saghul** [comment]
Loooks great! I'm closing this then.

**Comment by rsalvignac** [comment]
Hi,

It doesn't work on my project.
When I build I have this error :

> D8: Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$StubApi21


Can you help me ?

**Comment by slothstronaut** [comment]
Seems you have some conflict with another plugin possibly, what plugins are
you using, can you provide output of `cordova plugin list`

**Comment by rsalvignac** [comment]
Ok it's possible

My plugin list below

cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-autostart 2.3.0 "Autostart"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-calendar 5.1.2 "Calendar"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fingerprint-aio 1.3.8 "FingerprintAllInOne"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
in.lucasdup.bringtofront 0.0.1 "Bring to Front"

Thx for your help

**Comment by flean** [comment]
@slothstronaut , I added your package but I'm having some issues with it and I'm wondering if you have them too or know how to resolve them.

By the way I'm in Vegas too. Hope you are keeping safe. Thanks

 #5561
