### ISSUE TITLE
about CallKit

### ISSUE THREAD

**Issue by l819183457** [jitsi/jitsi-meet#5126]
I wrote this sentence when you started it and submitted it to Apple as they said. They still said that we still have this situation, any good suggestions, how to explain to Apple, or I need to do other operating? I do n’t think we ’ve ever shown the callkit function. It ’s a push message.
![image](https://user-images.githubusercontent.com/16470589/76380490-dd25c500-638d-11ea-8823-1535fe8ed1de.png)

**Comment by saghul** [comment]
I don’t know. AFAIK other have submitted apps to the store in China by disabling it like this, but I have no experience with it as we have not released it in China.

**Comment by l819183457** [comment]
thanks,
