### ISSUE TITLE
Android getDisplayMedia

### ISSUE THREAD

**Issue by zyCwind** [jitsi/jitsi-meet#5127]
i implemented 'getDisplayMedia' in react-native-webrtc to share android screen with other participants in the meet.

the screen can be correctly cast to the other side when 2 participants in the room. but when another comes into the room, the connection is lost and the webpage says that my android phone has connectivity problem. but on my phone, everything goes well.

i turned off screen sharing and switched to the front camera of that phone. all 3 participants can see the camera video.

is there any difference between screen stream and the camera video stream?

when jitsi-meet app gose to background. lastN was set to 0 to avoid receiving data with jingle-session sender='none', but i still want to send my screen data. i dont know whether lastN has effect on sending data. i just set lastN=1 and saw jingle-session sender='both' and it works.

its not a problem of configuration of jvb. i enabled and tested the 'octo' mode whith 2 jvbs on my server. there is a quirk that android MediaProjectionManager may not produce more frame data when the picture of screen have no changes. this may cause connectivity problems, too.
hope some suggestions :-). 

![QQ图片20200311153930](https://user-images.githubusercontent.com/16893158/76393505-a44a1800-63ae-11ea-9ae9-0e6a2e9d1dcf.jpg)

**Comment by saghul** [comment]
HI there!

Right now we do indeed set lastN to 0 when we go into the background. I also did a preliminary getDisplayMedia implementation and hacked around to set it to 1 when the video stream was a screen-share.

I never finalized it so what you discovered it's how we behave today and changes would be necessary to make it work properly.

**Comment by zyCwind** [comment]
im totally confused :-| there's nothing wrong of signalling with peers. logs from 'chrome://webrtc-internals/' seems all right. i created a android screen track and chrome added a receiver with the new track. android screen shown. toggled off android screen sharing, chrome removed that receiver, then turn it on, a screen track added again with no data only in jvb mode, (i have disabled the p2p mode). p2p mode works properly.

**Comment by zyCwind** [comment]
@saghul  when creating screen source using peerConnection.createVideoSource(isScreencast), param 'isScreencast' should be false. otherwise, data from screen recording service may be dropped as so far.(not in p2p mode), i used another thread for feeding the capturerObserver at a fixed speed which delivers the video frame.  so that participants come afterwards can see the screen even screen source dose not produce a frame when there were no changes.

i have not tested the screen source problems on other than my android phone.  :-)

**Comment by saghul** [comment]
Cool! Would you be willing to contribute some of your work?

**Comment by zyCwind** [comment]
@saghul I am glad to share some of my work. i have modified two projects related, react-native-webrtc, lib-jitsi-meet

today, i reorganized the code, and found a way that only make some hacks in jitsi-meet project, 
can make it work without modifing the dependency projects.

i will make a pull request later.by the way how can i join in the project. :-)
its better to enable that feature without hacks, so at lest project  lib-jitsi-meet should be updated.

**Comment by alfinurhakim** [comment]
Hello @zyCwind  ... I want to ask about the error react native ...

I have followed the steps of this link to make screen sharing in the application mobile 
(https://github.com/jitsi/jitsi-meet/commit/f11b94a0a5ee9f085b152f496627d6243079e6f4#diff-0475ad5b1318463a38eac1e39d79)

and ....

the issue is where when I install the react-native-webrtc library in your github, then conflicts arise ... conflicts with existing libraries (ie conflicts with lib react-native-google-signin) ... so when I open my application and try to log in to Google as usual this error immediately appears ...? can you help me to solve this error ..? please help because I have been stuck in 2 days 😄🙏...

![1589517219921](https://user-images.githubusercontent.com/48195224/82167330-a0260380-98e5-11ea-9157-92b9af5a839e.JPEG)
