### ISSUE TITLE
Come risolvere il problema della Videocamera

### ISSUE THREAD

**Issue by Stefanodevil148** [jitsi/jitsi-meet#5128]
Buongiorno,

quando sono connesso non riesco a mantenere attiva la webcam. Dopo pochi secondi si disconnette e non si riesce a vedermi.

Saluti
Stefano

**Comment by saghul** [comment]
Hi there,

We are under heavy load and the entire team has been working tirelessly on stabilizing the infrastructure. You may still face drops, but reconnecting should fix that.

Sorry about the trouble.
