### ISSUE TITLE
jitsi-meet-web-config does not uninstall, due to not installed apache2

### ISSUE THREAD

**Issue by anobit** [jitsi/jitsi-meet#5133]
## Description

After installing jitsi according to your instructions (`sudo apt-get -y install jitsi-meet`), i chose to uninstall it. But my packet manager isn't able to, because the uninstall-script seems to invoke a apache2 reload. Problem on my server is, that there is no apache2 service running. I only use nginx.

`apt-get purge jigasi jitsi-meet jitsi-meet-web-config`
returns
`Entfernen von jitsi-meet-web-config (1.0.3729-1) ...
apache2.service is not active, cannot reload.
invoke-rc.d: initscript apache2, action "reload" failed.
dpkg: Fehler beim Bearbeiten des Paketes jitsi-meet-web-config (--remove):
`

**Comment by anobit** [comment]
I hot-fixed this for me, by commenting out the corresponding
`
#        if [ -x "/etc/init.d/apache2" ]; then
#            invoke-rc.d apache2 reload
#        fi
`
in /var/lib/dpkg/info/jitsi-meet-web-config.postrm

**Comment by damencho** [comment]
This is already fixed: https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postrm#L31
