### ISSUE TITLE
No pop-up and no event participantKickedOut when kicking out a participant

### ISSUE THREAD

**Issue by Arzar** [jitsi/jitsi-meet#5136]
From https://community.jitsi.org/t/external-api-cant-receive-any-participantkickedout-event/22565

## Description
 Custom server jitsi-meet 3863
iframe embedded in browser thanks to external api for client (chrome/firefox)
Prosody(0.10.0,Linux)
JiCoFo(1.0.524,Linux)
Ubuntu 18

When a moderator kick out a participant, the participant forcibly leave the meeting as expected, but there is no red pop-up "ouch! moderator kicked you out of the meeting" and also there is no event participantKickedOut sent through the external api to let this user know it has been kicked out.

## Expected Behavior
Kicked up pop up appear. participantKickedOut event is sent through the external api

# Log

I could find log of Prosody and Jicofo proving that they were both aware of the kicking. Couldn't find log at higher level like jitsi-meet.

Prosody

Mar 12 14:36:00 bosheed056e8-5cc8-4d8f-a0d2-6449537a5702        debug   SEND: <presence xmlns='jabber:client' type='unavailable' to='2a59e3c5-f14d-43de-8505-34ae915de4ea@jitsi.service.trk.___.com/63dcccfc-c349-468c-8bc3-fdd7
e4042a3a' from='tele0011wkzogncxli@conference.jitsi.service.trk.___.com/2a59e3c5'><stats-id>Judson-uKb</stats-id><videomuted xmlns='http://jitsi.org/jitmeet/video'>false</videomuted><c ver='12a0JlElgsvtkqcjvfNtayNtIdw=' hash
='sha-1' node='http://jitsi.org/jitsimeet' xmlns='http://jabber.org/protocol/caps'/><avatar-id>84cd0bb87416c2bc6350c05a38bd3775</avatar-id><audiomuted xmlns='http://jitsi.org/jitmeet/audio'>false</audiomuted><nick xmlns='http://jabber.or
g/protocol/nick'>b</nick><jitsi_participant_raisedHand/><x xmlns='http://jabber.org/protocol/muc#user'><item affiliation='none' role='none' nick='2a59e3c5'><reason>You have been kicked.</reason></item><status code='307'/><status code='11
0'/></x></presence>

Jicofo 

Jicofo 2020-03-12 15:20:12.104 INFO: [27] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member tele0011wkzogncxli@conference.jitsi.service.trk.___.com/3bfd93bb kicked !!!
Jicofo 2020-03-12 15:20:12.104 INFO: [27] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member tele0011wkzogncxli@conference.jitsi.service.trk.___.com/3bfd93bb is leaving

**Comment by frankaloisio** [comment]
Hi Arzar, I am running inti this exact same issue - did you ever find a resolution to it? Any pointers would be greatly appreciated.
