### ISSUE TITLE
jibri is not starting

### ISSUE THREAD

**Issue by khushbukotwal** [jitsi/jitsi-meet#5138]
Hello I have received this error in jibri staus 

jibri.service: Failed with result 'exit-code'.
Mar 12 11:19:33 jibri systemd[1]: Started Jibri Process.
Mar 12 11:19:35 jibri launch.sh[14794]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

And also when I click on start recording it gives me an error that recording is unavailable .

Help

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

These are warning and are not a problem. Check jibri logs. Also check for errors `journalctl -xe`
