### ISSUE TITLE
Android App (current version from Market) frequently crashes when connected to server from docker-jitsi-meet

### ISSUE THREAD

**Issue by vorburger** [jitsi/jitsi-meet#5152]
The Android App (version 20.0.2 build 3764390, currently on Play Store) crashes after a few seconds in a first simple test when I connect it to a new server I just set up using https://github.com/jitsi/docker-jitsi-meet to a room with 1 other participant connected from Chrome on a Linux desktop (I've not really tested it against https://meet.jit.si).

It's been a while since [I've last done Android development](https://www.youtube.com/watch?v=ajNbrfL5cSU), and I forgot how / am not yet up to provide crash logs, but still wanted to let you guys know about it. (I did the Submit Report thing, may be you can find it on some Play Store console?)

**Comment by vorburger** [comment]
BTW I'm curious for an answer on https://community.jitsi.org/t/app-vs-mobile-web-browser/22857

**Comment by damencho** [comment]
Please use the community forum when you have questions and problems before opening new issues.

Have you tried testing with chrome with two tabs? Is it working?

**Comment by vorburger** [comment]
> Please use the community forum when you have questions and problems before opening new issues.

@damencho sure, [copy/pasted it here](https://community.jitsi.org/t/android-app-current-version-from-market-frequently-crashes-when-connected-to-server-from-docker-jitsi-meet/22884)

> Have you tried testing with chrome with two tabs? Is it working?

Yeah, web-to-web (from two Linux desktop computers) it's working fine and seems stable.

The App of course shouldn't just crash even if the server was not stable (which I don't think it is).
