### ISSUE TITLE
Impossibile accedere alla videocamera

### ISSUE THREAD

**Issue by scuolarobybongio** [jitsi/jitsi-meet#5157]
Buongiorno, ho un problema con la videocamera ma solo con il vostro software, per il resto funziona benissimo. Grazie

**Comment by saghul** [comment]
Please post your details (browser and webcam model) on this issue: https://github.com/jitsi/jitsi-meet/issues/5155#issuecomment-599030660

**Comment by scuolarobybongio** [comment]
Google Chrome
Lenovo easy camera Realtek

Il giorno sab 14 mar 2020 alle ore 13:28 Saúl Ibarra Corretgé <
notifications@github.com> ha scritto:

**Comment by scuolarobybongio** [comment]
Cerco di avviare Live da Weschool ma non riconosce la telecamera. Inoltre
appare il messaggio  "select allows when your bouser asks for permission"
ma dove appare questo comando?

Il giorno sab 14 mar 2020 alle ore 16:03 Roberta Bongiovanni <
scuolarobybongio@gmail.com> ha scritto:

**Comment by simevo** [comment]
"_select allow when your browser asks for permission_" si riferisce alla finestra di consenso per l'accesso a microfono e videocamera che il browser mostra quando apri il link alla videoconferenza per la prima volta, e che puoi riaprire anche in seguito cliccando sull'icona della videocamera qui:

![Screenshot_20200314_193933](https://user-images.githubusercontent.com/8254819/76688342-24c97c80-662c-11ea-9a48-87f7a9038496.png)

**Comment by rosycataldo** [comment]
Anch'io ho lo stesso problema ma nonostante le indicazioni non riesco a risolvere

**Comment by simevo** [comment]
i browser supportati sono Chrome e Firefox (ma devono essere aggiornati)

prova questo sito di test: https://test.webrtc.org/:
- dai il consenso all'accesso a microfono e videocamera
- clicca su start
- attendi la fine dei test e poi copiaincolla uno screenshot qui sotto

**Comment by karl74na** [comment]
Anch'io ho lo stesso problema.

**Comment by Ndrindro** [comment]
![Schermata 2020-04-17 alle 12 14 22](https://user-images.githubusercontent.com/63849624/79559038-61621b00-80a5-11ea-97a6-be12bb3f5251.png)

**Comment by amatrixx** [comment]
Risolto!
Io avevo Kaspersky come antivirus, andando nelle impostazioni (ingranaggio in basso a sx) poi protezione e cliccando su protezione webcam, ho trovato che chrome era tra le applicazioni a cui non era consentito utilizzare la webcam. Adesso tutto ok.
