### ISSUE TITLE
Extend quick install instructions

### ISSUE THREAD

**Issue by radiospiel** [jitsi/jitsi-meet#5160]
I don't know if this is the right repo to suggest an improvement on jitsi.org; but given the really exceptional experience provided by the installer I suggest the following additions to the "Ubuntu / Debian Installation Instructions" at https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ 

- add instruction on how to generate a lets encrypt certificate
        /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
- add a pointer to the quick install document in this repo: meet/blob/master/doc/quick-install.md)

One of the best installers for an Open Source product I have seen so far. Thank you!

**Comment by l3d00m** [comment]
I assume this site could also now be replaced with the new handbook. https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
