### ISSUE TITLE
All recorders are currently busy

### ISSUE THREAD

**Issue by pablorodriguezgonzalez** [jitsi/jitsi-meet#5161]
Hello!

I'm getting this message and asking to wait a few minutes but isn't working after waiting.

Any idea how to solve it? It's a problem with my micro?

Thanks in advance!

**Comment by saghul** [comment]
We have a maximum number of recorders available and all of them seem to be busy, since our service has seen a signifiacnt spike in usage.

There is nothing you can do other than wait, sorry about that.

**Comment by pablorodriguezgonzalez** [comment]
Thanks anyway!
