### ISSUE TITLE
tutti i registratori sono occupati

### ISSUE THREAD

**Issue by Pamela84** [jitsi/jitsi-meet#5162]
Salve
sono alle prima armi, e dopo aver fatto tutto, devo iniziare a registrare un video.
però quando clicco in basso a destra "INIZIA A REGISTRARE", mi esce una finestra arancione a sinistra che dice testualmente "TUTTI I REGISTRATORI SONO OCCUPATI. STIAMO CERCANDO DI LIBERARE RISORSE PER LE REGISTRAZIONE. RIPROVA TRA QUALCHE MINUTO".
Ho provato diverse volte, ma purtroppo no va.
Come mai? come mi comporto?
resto in attesa.
saluti

**Comment by simevo** [comment]
Ciao ! questa è la piattaforma dove gli sviluppatori incontrano gli amministratori di sistema o gli altri sviluppatori, e qui si comunica in lingua inglese. Per un problema di supporto agli utenti ti consiglio  https://community.jitsi.org (anche questo in inglese). Cmq se ti dice di aspettare prova domani ;-)
