### ISSUE TITLE
webcam non riconosciuta

### ISSUE THREAD

**Issue by scuolarobybongio** [jitsi/jitsi-meet#5164]
Buonasera,
cerco di far partire la videoconferenza utilizzando LIVE direttamente da Weschool ma il programma non si connette con la mia webcam. Utilizzo Google Chrome e la mia webcam è Lenovo Easy camera della Realtek.
Grazie

**Comment by simevo** [comment]
Ciao ! questa è la piattaforma dove gli sviluppatori incontrano gli amministratori di sistema o gli altri sviluppatori, e qui si comunica in lingua Inglese. Per un problema di supporto agli utenti ti consiglio  https://community.jitsi.org (anche questo in inglese). Cmq per il tuo problema ho cercato con google "_lenovo easy camera not working_" e questo è il primo risultato: https://www.techjunkie.com/lenovo-webcam-not-working-issue/

**Comment by saghul** [comment]
Thanks for helping out @simevo !
