### ISSUE TITLE
All recorder are currently busy

### ISSUE THREAD

**Issue by ritategon** [jitsi/jitsi-meet#5165]
Good Eevening
I would like to record a work session in Jitsi for the ones who can not partecipate. How can I be sure that a recorder is not busy?
Thank You so much
Rita Tegon

**Comment by saghul** [comment]
We have a maximum number of recorders available and all of them seem to be busy, since our service has seen a signifiacnt spike in usage.

There is nothing you can do other than wait, sorry about that.

**Comment by ritategon** [comment]
> 
> 
> We have a maximum number of recorders available and all of them seem to be busy, since our service has seen a signifiacnt spike in usage.
> 
> There is nothing you can do other than wait, sorry about that.

Thank you for the answer.
RT

**Comment by lambda121** [comment]
Hello Saghul, 
Are you guys planning to expand the recorders count? We are facing this issue as well and wanted to check if its better to deploy our own jitsi instance or wait for jitsi meet to resolve this issue.

Thanks,
Abhishek
