### ISSUE TITLE
On android it's missing the share button

### ISSUE THREAD

**Issue by Yajo** [jitsi/jitsi-meet#5166]
**Is your feature request related to a problem you are facing?**
Yes, I'm trying to add more people to my meeting.

**Describe the solution you'd like**
A share button.

**Describe alternatives you've considered**
Copying and pasting the room name before opening it. Not much intuitive...

**Comment by saghul** [comment]
You're right, our meeting sharing option wasn't very easily accessible. We pushed an Android update yesterday (iOS is still in review) making it easier to acess. Here is how you can do it:

First press on the "More" button at the bottom of the menu:

![Screenshot_20200315-100339_Jitsi Meet](https://user-images.githubusercontent.com/317464/76698552-a9f07800-66a4-11ea-8095-1d1bf88a0a12.jpg)

On the new menu, pick "Meeting Info"

![Screenshot_20200315-100345_Jitsi Meet](https://user-images.githubusercontent.com/317464/76698560-c2609280-66a4-11ea-9292-28b659468846.jpg)

Thanks for the feedback, we will be revisiting this going forward.

**Comment by saghul** [comment]
I forgot to say that if you ddon't see the More button you can swipe up and the new options will show up, it means you haven't received the latest update yet.

**Comment by Yajo** [comment]
Oh I see! The option is there, but it's not intuitive.

I'd expect something like "Share meeting info" or "Invite somebody", with an icon like one of these:
- https://fontawesome.com/icons/share-alt?style=solid
- https://fontawesome.com/icons/share-alt?style=solid

Also I'd expect it to be more prominent, as I think one of the main usages of a meeting is to invite other people.

**Comment by saghul** [comment]
Our typical use case has been to use a calendar to disseminate the meeting information, but the recent spike in traffic has shown us that indeed you're right and we should make the sharing part more prominent.

We'll be working to improve this when time allows.

**Comment by Yajo** [comment]
> recent spike in traffic

Must be due to COVID-19.

**Comment by bluikko** [comment]
Now the "Meeting info" seems to be truly gone?

**Comment by saghul** [comment]
Yep, see our announcement here: https://twitter.com/jitsinews/status/1243485453325664256

**Comment by saghul** [comment]
Thanks for the feedback here. The changes we made in the last release originated in this discussion.

**Comment by Yajo** [comment]
Thank you, it's great now!
