### ISSUE TITLE
A realsense integrated camera (HP OMEN) doesn't works in Ubuntu derivated distro 

### ISSUE THREAD

**Issue by maxezek** [jitsi/jitsi-meet#5168]
In my case, I have a realsense SR300 which works with realsense-viewer in my linux distro but it doesn't work in any browser.

The camera is integrated in my HP Omen laptop 

The device is located in /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.2/video4linux/video1

Thanks for any help

**Comment by saghul** [comment]
If it doesn't work in any browser there is hardly anything we can do from the Jitsi side in order to help.

I suggest you post in our community: https://community.jitsi.org/ since maybe someone has run into this and knows the answer.

Cheers!
