### ISSUE TITLE
possibility to easily distinguish the rooms in the list/history (of the android-app)

### ISSUE THREAD

**Issue by DJCrashdummy** [jitsi/jitsi-meet#5169]
**Is your feature request related to a problem you are facing?**
i started using the jitsi meet android-app because i'm going to have more than one different video conference repeatedly...
now after the first use i see them in the handy list/history and can join them again, but my problem is that i have no clue which entry is which room (because of "endless" alphanumerical URLs)!

**Describe the solution you'd like**
well... i'm thankful for any solution, but a function to (locally) label the existing rooms would be nice.

**Describe alternatives you've considered**
- using a different room with a meaningful name in the URL is not an option because i got this URL as one simple participant of ~20.
- i also saw some applications using jitsi meet to provide video conferencing which create alphanumerical strings without the possibility to override it with a meaningful name.

**Comment by saghul** [comment]
We do have the concept of a meeiting "subject" but there is currently no way to set it from the app... I think this could achieve what you describe.

**Comment by michaelschefczyk** [comment]
In addition, it might be worthwhile to add the possibility to delete entries from the history list to the android app. So far, deleting the app and installing it again seems to be the only way.

**Comment by DJCrashdummy** [comment]
@saghul that seems to be interesting and may solve the problem... is there any way to set it for normal users (or admins resp. mods) via a GUI or is it for now just a "hidden feature"?

**Comment by saghul** [comment]
> In addition, it might be worthwhile to add the possibility to delete entries from the history list to the android app. So far, deleting the app and installing it again seems to be the only way.

Not at all! Swipe left on an entry and it will reveal an option to delete it.

**Comment by saghul** [comment]
> that seems to be interesting and may solve the problem... is there any way to set it for normal users (or admins resp. mods) via a GUI or is it for now just a "hidden feature"?

Not at the moment. The usual way to set the subject is when crearting the event in a calendar with the calendar addon, or ina  JWT token.

**Comment by michaelschefczyk** [comment]
Sorry - to delete an entry, I did try tap, double tap, tap & move around, long press, two finger gestures, swipe right, swipe up, swipe down - just not ... :)

**Comment by DJCrashdummy** [comment]
> Swipe left on an entry and it will reveal an option to delete it.

indeed! that works at least at the android-app... but that's hardly intuitive. :slightly_frowning_face: 
how about a log tap to get to additional functions (like usual) or even better a simple settings-icon on the right side. - that would even be possible to have 1:1 in the web-GUI (because i think there still isn't an option to delete entries).

**Comment by vkruoso** [comment]
> > that seems to be interesting and may solve the problem... is there any way to set it for normal users (or admins resp. mods) via a GUI or is it for now just a "hidden feature"?
> 
> Not at the moment. The usual way to set the subject is when crearting the event in a calendar with the calendar addon, or ina JWT token.

@saghul I was trying to figure this out in the web interface as well. Turns out that the JWT value used is the ```callee.name```, but it is only used for the user that authenticated using the token. Setting the ```subject``` of the room with the iframe API seems to work for all participants as it sends the information to the server, and it has preference of display over the JWT value in the interface.

My issue now is that after setting the room ```subject``` the web interface shows correctly, but the page title still shows the original formatted version of the room name (that might not be really readable). 

My take is that the page title should be equal to the value displayed in the interface at all times. Does that make sense? Please let me know if I should open this as a separate issue.

**Comment by saghul** [comment]
Makes sense. A PR addressing that would be welcome!
