### ISSUE TITLE
Not able to connect video & audio in Jitsi meet conferencing

### ISSUE THREAD

**Issue by a3c** [jitsi/jitsi-meet#5174]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
https://meet.jit.si/testtest1 or similar rooms allow users to connect but not able to see or hear each other. 

Chat works fine.
## Current behavior
---
conferencing is not working

## Expected Behavior
---
all participants should be able to see and hear each other.

## Possible Solution
---

## Steps to reproduce
---
Just start a conference and try having a call with any participant

# Environment details
---
https://meet.jit.si/

**Comment by a3c** [comment]
update : when two people connect, it works.. however, as soon as the third person connects to the bridge, all three get muted (camera & mic both show as muted).

**Comment by zhengzheli** [comment]
Yes, we show as muted to others, but not to ourselves. Is this intentional to save bandwidth on the free servers?

**Comment by niko** [comment]
Similiar: 4 persons, A, B, C, D.

* A and B can talk. Even each with laptop and cell phone.
* As soon as either C or D joins, all mics are muted, all cameras off.
* C and D can't talk 1:1.

**Comment by saghul** [comment]
We had some load problems which are likely solved now, sorry for the trouble.

**Comment by onlyyjc** [comment]
More than 3 people video conference have no sound and picture, 2 people are all right, why？

**Comment by davidoppen** [comment]
One hour ago I had the issue that all other parties (more then two people) were shown as muted with no sound coming through. 
All participants unmuted themselves multiple times but still were shown as such.

**Comment by saghul** [comment]
This was a result of a partial outage we had.

**Comment by a3c** [comment]
How many conferences the current setup can support?  curious, as we had two outages in two days.

**Comment by saghul** [comment]
There is no imposed limit, "as many as we possibly can" is the most accurate number I can provide.

Yes we have had issuess, and probably still will, we aare trying oour best to keep up with this unprecedented load.

**Comment by saghul** [comment]
I'm going to close this since handling the increading load in these tumultuous times is our number 1 priority and we are constantly making adjustments and improvements in our infrastructure to make sure we are able to handle it.
