### ISSUE TITLE
Link to supported browsers does not load on Firefox

### ISSUE THREAD

**Issue by janvlug** [jitsi/jitsi-meet#5177]
## Description
I'm using the latest, up to date version of Firefox on a fully up to date Fedora Linux. I get a Browser Warning notification. There is a link in this notification that does not load a page in Firefox.

## Current behavior
When clicking the fully supported browsers link, a new tab is opened, but it stays blank. Firefox indicates that it is waiting/loading.

## Expected Behavior
When clicking the fully supported browsers link, a new tab to be opened with details of supported browsers.

## Possible Solution
None

## Steps to reproduce
1. Use Firefox to go to a Jitsi room.
2. In the bottom left a notification with the text: "Browser warning" appears.
3. Expand the notification.
4. In the appearing text is a link: [fully supported browsers](https://web-cdn.jitsi.net/meetjitsi_3883.555/static/recommendedBrowsers.html)
5. Click on the link.

# Environment details
Linux 5.5.7-200.fc31.x86_64 SMP Fri Feb 28 17:18:37 UTC 2020 x86_64 x86_64x86_64 GNU/Linux

**Comment by damencho** [comment]
Could you please add your console logs with the errors?

**Comment by janvlug** [comment]
I tried to get the web console errors, but now it works (again). This morning there were some Jitsi service disruption, maybe the issue was related to that. Closing this bug now.

**Comment by stephenjudge** [comment]
I'm using Firefox 74 on Xubuntu 18.04.

Only Chrome and Chromium are listed as supported browsers. Is there a reason Firefox is not supported? Is there documentation anywhere explaining supported browsers status (I can't find any)?

I find it incredible the Firefox would not be supported.
