### ISSUE TITLE
Firefox - user is shown as muted

### ISSUE THREAD

**Issue by kuba-orlik** [jitsi/jitsi-meet#5181]
# Description

When connecting to a room on https://meet.jit.si/ via Firefox, the user connecting from Firefox appears as muted, even though the browser has been granted access to the mic. 

# Environment details
GNU/Linux (Manjaro), Firefox 74

**Comment by damencho** [comment]
Please use the community forum for problems or questions before opening new issues.

This is a known issue happening from time to time with Firefox. We are working on fixing it.

**Comment by LAfricain** [comment]
>We are working on fixing it.

Ok thank you but why refusing the bug report? I have the same issue with all my Linux computer, we must use chrome for the meeting what's not the best way...

**Comment by damencho** [comment]
Cause there are more issues like that. Cannot find it right now. Opening new issues for the same problem will not help solving it. What is the point of keeping it open?

**Comment by LAfricain** [comment]
>What is the point of keeping it open?

Only because it is a real issue isn't it? Or maybe you have other issue similar we can follow?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5230
https://github.com/jitsi/jitsi-meet/issues/4758

**Comment by LAfricain** [comment]
OK thank you!
