### ISSUE TITLE
Chrome - could not get access to microphone for unknown reason

### ISSUE THREAD

**Issue by kuba-orlik** [jitsi/jitsi-meet#5182]
## Description

When connecting to Jitsi Meet via Chrome, the video is transmitted, but the microphone audio does not. There is a popup saying that the app could not get access to the microphone for an unknown reason. The js console says

> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

# Environment details
GNU/Linux (Manjaro), Chrome 80

**Comment by saghul** [comment]
Can you try test.webrtc.org ? Does it work there?

**Comment by kuba-orlik** [comment]
Seems ok:

![image](https://user-images.githubusercontent.com/2697916/76939353-21661780-68f0-11ea-865c-4b2ed4fcfcda.png)

**Comment by saghul** [comment]
If you go the settings dialog, then devices, do you have multiple mics to choose from?

**Comment by kuba-orlik** [comment]
That's correct. Although now the "could not get access to microphone for unknown reason" does not pop up. Will report back if it appears again

**Comment by saghul** [comment]
👍 tentatively closing then.
