### ISSUE TITLE
Add a donate button

### ISSUE THREAD

**Issue by forteller** [jitsi/jitsi-meet#5183]
Thank you for creating this amazing service!

I am worried about its long term financial sustainability, especially now with the onslaught of new users I'm sure you're having.

I really feel like you should add a way to donate to the project on meet.jit.si, to get some income from all this new use, not just expenses. 

Thanks again.

**Comment by saghul** [comment]
Thanks for the kind words! We (the Jitsi team) are employed by 8x8, Inc. which graciously runs the service. Thus, we are not taking donations.

If you ever need telephony services at your company consider 8x8 ;-)

**Comment by viktorsmari** [comment]
Came here planning to donate for this amazing service.
I guess this is the company running it:
https://www.8x8.com/

**Comment by f-9t9it** [comment]
> Thanks for the kind words! We (the Jitsi team) are employed by 8x8, Inc. which graciously runs the service. Thus, we are not taking donations.
> 
> If you ever need telephony services at your company consider 8x8 ;-)

We want to donate too as we have deployed a self hosted server, I agree that 8x8 is sponsoring it but It is better to have a community based finance which can be used to help the community contributors with something like test devices etc.

I will consider 8x8 when needing any of their service but I still insist to taking donation for community benefit as we're also maintaining opensource projects and donations are always helpful.

Thanks for such a great work on jitsi meet
