### ISSUE TITLE
iOS/Android: Share meeting link improvement: rename "Meeting info" to "Share meeting"

### ISSUE THREAD

**Issue by mauritslamers** [jitsi/jitsi-meet#5187]
In the current iOS and Android applications, the only way that I have been able to find to share a meeting link is through the context menu of the meeting itself, through a label called "Meeting information". This is not very intuitive.

UX-wise, I would expect the information to display a pane with the meeting info. The action linked to this option however is to open the sharing screen for the meeting information.

I see a possible solution in renaming the label (and its translations) to "Share meeting".
This makes immediately clear what the action is behind that option.

**Comment by saghul** [comment]
Note to self: we should probably call it "Invite participants" and foldd it with the option which works when there is a backend...

**Comment by bluikko** [comment]
After updating to the recent new version now the "Meeting info" is gone from the menu. Users are wondering how to share a link now...

**Comment by saghul** [comment]
We reworded the menu and called the option "Invite someone", which should be clearer. See: https://twitter.com/jitsinews/status/1243485453325664256 there is also a new invite button displayed when a user is alone in the meeting.

**Comment by bluikko** [comment]
Yes, I see that. But the functionality of "Meeting info" (showing a link to the meeting, button to copy it, plus sharing functionality) is now gone and all that is left is inviting someone by entering a number?

Basically the whole "Meeting info" functionalities are gone and only the old "Invite" functionality is left?

**Comment by saghul** [comment]
What server are you connecting to?

**Comment by bluikko** [comment]
This is a local instance done with the docker image. Let me update it then also!

**Comment by saghul** [comment]
Did you deploy Jigasi?

**Comment by bluikko** [comment]
This is a very simple installation of `docker-jitsi-meet` and nothing else. I did remove the "blur background" option from menu but no other menu items were touched in configuration.

**Comment by saghul** [comment]
I can reproduce it, thanks for the report! This is a bug in the Docker setup, that shouldn't happen.

**Comment by bluikko** [comment]
No - thank you for Jitsi!! With everything going on right now it's been very useful for remote workers.
I can open a new bug for tracking it if you want.

**Comment by saghul** [comment]
Can you please try this: remove the line starting with `org.jitsi.jicofo.jigasi.BREWERY=` from jicofo's ssip-communicator.properties file. Then restart the jicofo container.

**Comment by bluikko** [comment]
It works after updating `sip-communicator.properties`. Took a while since the double-s confused me (I'm not very familiar with this yet).

**Comment by saghul** [comment]
Thanks a lot for testing! I'll make a fix in the Docker files stat. Apologies for the typo, this mac keyboard is the worst thing!

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/7c0c795fa7d29d04248ec6201ef7b879f4dc537f

It will be part of the next images release, but your change is ok already.
