### ISSUE TITLE
Fail when connecting in a room from 2 different countries!! 😭

### ISSUE THREAD

**Issue by EdZava** [jitsi/jitsi-meet#5189]
## Description
When connecting to an open room. With people in different countries the call does not work, you do not see the other people connected.

This BUG happens, when trying to connect me from Brazil and other users from Spain, Those who are granted in Spain see those who are in Brazil, we are not able to see those in Spain.

If before entering the room if we enter via, Proxy los de Brazil as we would be in Spain, then everything works correctly.

I think it may be something from CORS or location blocking.

Note: until Friday 03/13/2020 everything worked correctly.

How to simulate the error, connect 2 people from different countries to an example room:
  https://meet.jit.si/test-bug1

**This is an urgent and critical error that does not make it impossible to use the application.**

**Comment by EdZava** [comment]
@saghul do you know anything about this error? was something updated?

**Comment by Yajo** [comment]
It just happened today the same for me, people from Portugal and Cuba landed in one room, and people from Spain in another one.

**Comment by saghul** [comment]
This was likely due to the high load we are receiving. We are working to fix all these issues as they arise folks, don't stop believing! :-)

**Comment by rathnakaraita** [comment]
Any Updates on this we are also facing same issue.
India To USA video Conferences we are trying in Self-Hosting Server.

**Comment by BhargavMsh** [comment]
India To USA video Conferences Not working we are trying in Self-Hosting Server.
Person Joined from USA not able See video or Hear Audio inputs from our end via versa.

**Comment by saghul** [comment]
Please don't post on 2 year old issues, it's unlikely to be related.
