### ISSUE TITLE
Все ресурсы для трансляции уже задействованы

### ISSUE THREAD

**Issue by luchinina1503** [jitsi/jitsi-meet#5194]
Добрый день! Подскажите по какой причине не получается начать прансляцию, высвечивается оранжевое окошко "Все ресурсы для трансляции уже задействованы"... Как исправить эту проблему? Спасибо

**Comment by damencho** [comment]
Use the community forum when having questions and problems before creating new issues.

Try again later, there is a big demand for resources the last few weeks...
