### ISSUE TITLE
[feature request] save server-specific profiles (with credentials)

### ISSUE THREAD

**Issue by Wurzelmann** [jitsi/jitsi-meet#5196]
**Is your feature request related to a problem you are facing?**
I want to save a profile specific to my jitsi server in order to not having to sign in every time I enter a room

**Describe the solution you'd like**
Add option to create server specific profiles (server url+user name+password) and use these credentials to automatically log into rooms on the corresponding server(s)

**Describe alternatives you've considered**
None come to mind

**Comment by saghul** [comment]
If you are using authentiaction I assume you have your own deployment. You can set this configuration option in Jicofo to cache the authenticcation for a period of time (defaults to 24h if enabled): https://github.com/jitsi/jicofo/blob/9cfa2361c7841b7621f1882deaeeeeaea54c9196/src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java#L73

**Comment by Wurzelmann** [comment]
Thank you for this! In my original post, I was talking about the Android app, but did not specify this, my mistake, I am sorry about this.
