### ISSUE TITLE
Allow Jitsi Android app to open links from self-hosted Jitsi Meet instances

### ISSUE THREAD

**Issue by tssk** [jitsi/jitsi-meet#5199]
I would like the Jitsi Android app to be shown as an option to open link from Jitsi Meet running on our server not only predefinefined servers meet.jit.si, alpha.jitsi.net and beta.meet.jit.si.

When opening links from other applications like Email or Mattermost have an option to oen link in Jitsi app.

Alternative solution is to copy the link, open Jitsi app, paste the link in the room name input and delete https://hostname/ from the link which is not user friendly.

**Comment by C0rn3j** [comment]
If you open said link on the android app you however get the page with a button to open the app.

Wanting to bind to every single domain seems like a nuisance to users

![image](https://user-images.githubusercontent.com/1641362/76844364-74cb5d80-683d-11ea-8e76-4bd1838cdbc6.png)

**Comment by saghul** [comment]
> I would like the Jitsi Android app to be shown as an option to open link from Jitsi Meet running on our server not only predefinefined servers meet.jit.si, alpha.jitsi.net and beta.meet.jit.si.

This is not posssible, we cannot list all instancces in the app. As @C0rn3j said, the app will open with the Continue to app button.

**Comment by tssk** [comment]
@C0rn3j I did not know about this, but I think this just solves my issue. Thanks

@saghul btw> I got impression that it is possible to register every address with * like VLC. But I am not sure how this exactly works in Android.

**Comment by saghul** [comment]
@tssk I don't think so. VLC might be using deep links, which would work, we use them too, that's what the "Continue to app" button does, open a URL of the form "org.jitsi.meet://foo".

If you manage to find a way around it, I'd be happy to take it!

**Comment by md-work** [comment]
Alternatively a conference could have a "share for app" button, which outputs an URL starting with a registred string.

The string could be a registered scheme like `jitsi-meet:myserver.org/room-name`.

Alternatively, the app could simply register to a "forward URL". E.g. `https://fw.jit.si`.
The Jitsi-Meet wouldn't even need to register `fw.jit.si` in the DNS. Instead the app simply detects if it's being called with something like `https://fw.jit.si/myserver.org/room-name` and instead of `fw.jit.si` the app then opens `https://myserver.org/room-name`.

**Comment by hasandiwan** [comment]
Seems to me that we would just need a preference key to modify the 'android:host' in app/src/main/AndroidManifest.xml. I think we'll need it to modify line 35 only, but I'm not familiar enough with the code to be sure. If there is interest, reopen this issue and I can try a build with my modifications for my self-hosted instance.

**Comment by hasandiwan** [comment]
> Why does the deep-link not work for you?

Was this in response to my comment or the one before?

**Comment by saghul** [comment]
The previous comment was years ago, so yours.

**Comment by hasandiwan** [comment]
> Why does the deep-link not work for you?

It does now... thank you very much.
