### ISSUE TITLE
[Web] Chat should not be overlaying on video

### ISSUE THREAD

**Issue by connectedSoul** [jitsi/jitsi-meet#5201]
First, I thought about making this a bug report, but since it doesn't look buggy, but intended, I should now state my feature request:

Please make the chat window equally in hierarchy as the video streaming tiles. The overlaying part is annoying and cuts of parts of the video streams.

**Comment by saghul** [comment]
THiss is being worked on right now, see https://github.com/jitsi/jitsi-meet/pull/5148

**Comment by connectedSoul** [comment]
Thanks, I did not find it.
