### ISSUE TITLE
When building my own SDK error

### ISSUE THREAD

**Issue by batuhansahan** [jitsi/jitsi-meet#5202]
## Description
---
When i use release-sdk.sh

## Error

> Task :react-native-background-timer:checkReleaseManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to create parent directory '/home/user/jitsi-meet/node_modules/react-native-background-timer/android/build' when creating directory '/home/user/jitsi-meet/node_modules/react-native-background-timer/android/build/intermediates/check_manifest_result/release/checkReleaseManifest/out'

# Environment details
---
Ubuntu 18.04

**Comment by saghul** [comment]
can you chek the permissions of those directories? Did you git clone as root?

**Comment by batuhansahan** [comment]
Permission not permitted, i didn't git clone as root should i ? how to overcome this problem i can use root prefix i own the server currently on amazon azure vm.

**Comment by saghul** [comment]
No, no, you shouldn't use root. Is there enough space available on the hard drive? Did you run  npm install?

**Comment by batuhansahan** [comment]
Yes there is 15gb space available, I ran npm uninstall but there is some error at the end
```
code ELIFECYCLE
npm ERR! errno 1
npm ERR! lib-jitsi-meet@github:jitsi/lib-jitsi-meet#c6323d1ddb26bce5e50436685ec892d1f164590c postinstall: `webpack -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lib-jitsi-meet@github:jitsi/lib-jitsi-meet#c6323d1ddb26bce5e50436685ec892d1f164590c postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by batuhansahan** [comment]
I downgrade npm to @5.3 it is okay now
i'll try again building process

**Comment by saghul** [comment]
That's strange. It looks like an npm failure, not sure what to do about it.

**Comment by batuhansahan** [comment]
I handle the npm error with downgrade npm@5.3 and

removed ~/.gradle and clean project with ./gradlew clean

and run script with fresh start.

the error occures
```
> Task :sdk:bundleReleaseJsAndAssets
warn Failed to chmod xsel: EPERM: operation not permitted, chmod '/home/user/jitsi-meet/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/server/external/xsel'
warning: the transform cache was reset.
fs.js:1384
    throw error;
    ^

Error: watch /home/user/jitsi-meet/node_modules/@atlaskit/dropdown-menu/node_modules/@atlaskit/item/dist/cjs/util ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (/home/user/jitsi-meet/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/batuhansahan/jitsi-meet/node_modules/sane/src/common.js:109:31)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at /home/batuhansahan/jitsi-meet/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:135:15)

> Task :sdk:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

```

**Comment by saghul** [comment]
Have you installed watchman?

**Comment by batuhansahan** [comment]
yeah i manually installed watcman

 [facebook/create-react-app/issues/346](https://github.com/facebook/create-react-app/issues/346) found solution just need to Create an empty .watchmanconfig file in my project's root folder. 
`touch .watchmanconfig`

**Comment by saghul** [comment]
I'm confused. We already have such file: https://github.com/jitsi/jitsi-meet/blob/master/.watchmanconfig You could have mentioned you had made changes to the project and we'd have pinpointed the issue easier...
