### ISSUE TITLE
Custom SDK publishing to Github

### ISSUE THREAD

**Issue by batuhansahan** [jitsi/jitsi-meet#5213]
I built sdk and at the end of message says "Don't forget to push the tag and the Maven repo artifacts." what should i do.

i have tmp folder and in inside 2 folder com, org, 

- com 
   - facebook

- org 
   - jitsi
      - react
          - jitsi-meet-sdk
             - 2.6.0 > jitsi-meet-sdk-2.6.0.aar, .pom files
             - maven-metadata.xml
             - maven-metadata.md5,sha1 files

i want to use the sdk as a github package like 
[https://github.com/jitsi/jitsi-maven-repository/tree/master/releases](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases)

i have repository but i just did git push not maven deploy or anything else. 
https://github.com/batuhansahan/Jitsi-custom-sdk

it is not working when i implement my project
```
maven {
     url "https://github.com/batuhansahan/Jitsi-custom-sdk"
}
```

This is my first maven issue i don't know anything about pom file or anything about maven, can you please help about this issue.

**Comment by saghul** [comment]
Lots of dependencies are missing there. How did you make the release, with the release-sdk.sh script? Did you see any errors in the output?

**Comment by fritzfr** [comment]
@batuhansahan How did you resolve this? I also miss the dependencies, e.g. `hermes`. See https://github.com/jitsi/jitsi-meet/issues/6688.

**Comment by batuhansahan** [comment]
i cloned official maven repo and copy the custom repo in com, org folders
```bash
cd jitsi-maven-repository

cp -r $home/jitsi-meet/tmp/repo/org $home/jitsi-maven-repository/releases
cp -r $home/jitsi-meet/tmp/repo/com $home/jitsi-maven-repository/releases
```
 and then

```bash
git add -A .
git commit -m "Jitsi Meet SDK + dependencies: <SDK_VERSION>"
git tag android-sdk-<SDK_VERSION>

// push
git push --tags
```

now you can use your custom sdk with your tag

**Comment by fritzfr** [comment]
@batuhansahan Okay thanks. That doesn't solve my problem though, as with my setup, I'd like maven to push `hermes` too.

**Comment by batuhansahan** [comment]
i push hermes too hermes is in com/facebook/hermes folder

**Comment by deva-gopalani** [comment]
@batuhansahan hey i tried doing your steps and then i pasted my repo link in the gradle file but when i tried syncing the gradle i got the following error:

`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.jitsi.react:jitsi-meet-sdk:2.8.2.`

Could you help with this?

**Comment by 1433498251** [comment]
> Lots of dependencies are missing there. How did you make the release, with the release-sdk.sh script? Did you see any errors in the output?

Please implement/ After the android/scripts/release sdk. sh/tmp/repo command is packaged, why is there only one webkit directory in the org directory.
