### ISSUE TITLE
Emoji reactions

### ISSUE THREAD

**Issue by dbrgn** [jitsi/jitsi-meet#5217]
**Is your feature request related to a problem you are facing?**

In a meeting with many people, sometimes you want to indicate your approval or dismissal (or another emotion) for an idea without speaking up and disrupting the conversation flow.

**Describe the solution you'd like**

For this, it would be useful if a user could pick from a list of emoji and that this emoji would be briefly shown on top of the user video (with fade-in and fade-out). It could cover maybe 50% of the area, potentially with some transparency.

**Describe alternatives you've considered**

The chat could be used as well, but it's persistent, while an approval of an idea is specific to something that was just said and is thus only relevant temporarily.

**Comment by AndCotOli** [comment]
I could start working on this, obviously if maintainers/admins agree this is a good feature 🙃.

**Comment by jeromelebleu** [comment]
I - and almost everybody I talk to with Jitsi - think that it could be really useful - especially at this time. Many thanks in advance to those who can add this feature!

**Comment by maxired** [comment]
I made a chrome extension which adds a single reaction and allows to share happiness https://chrome.google.com/webstore/detail/jitsi-meet-party-button/pbdkaccnkglbocobgnkcggipeeakfppg

I also think that more global reactions would be great

**Comment by dbrgn** [comment]
I would still find this useful. Especially in meetings with many people.

**Comment by Pretuer** [comment]
> I made a chrome extension which adds a single reaction and allows to share happiness https://chrome.google.com/webstore/detail/jitsi-meet-party-button/pbdkaccnkglbocobgnkcggipeeakfppg
> 
> I also think that more global reactions would be great

Doesn't work anymore. needs to be updated

**Comment by maxired** [comment]
@Pretuer thanks for letting me know. Version 1.0.3 of the extensions should fix the issue.

**Comment by tonibony** [comment]
See also #8054

**Comment by saghul** [comment]
This has already been implemented in master. It will be rolled out soon.
