### ISSUE TITLE
Room Name: Umlauts are not possible

### ISSUE THREAD

**Issue by thalunil** [jitsi/jitsi-meet#5223]
## Description
Room name does not correctly display "Umlauts"

## Current behavior
When opening up a room named "äöü" (https://meet.jit.si/öüä) the display of the room name on the top is strippend/sanitized and not correctly shown

## Expected Behavior
The room name should display the "Umlauts" during conference session on top of screen.

Maybe similar to https://github.com/jitsi/jitsi-meet/issues/5048

**Comment by saghul** [comment]
We have some logic to try to “prettify” names, it does not seem to do the right thing in this case, thanks for the report!

**Comment by manu-p** [comment]
Hi, it seems the same for any accented character : éèêëàâùç... many languages are impacted.

**Comment by saghul** [comment]
I think this would be the case for any non-ascii character.

**Comment by manu-p** [comment]
Sure, so what's the solution since any user will type something in his own language as a room name?

Alternatively, what is the way to display a warning message to inform that the room name must not contain any "non-ascii" char?

**Comment by saghul** [comment]
Any character is allowed in a room name, we are failing to render it correctly though.

**Comment by saghul** [comment]
Here is a fix: https://github.com/jitsi/jitsi-meet/pull/5333

**Comment by manu-p** [comment]
Not sure what you mean by "is allowed", but if you type something like été for the room name, you get a 404 error, as you cant see on this image https://ibb.co/zRyT1jX

**Comment by saghul** [comment]
Works jusst fine on meet.jit.si. If you are using the Docker setup, we jave a bug in the nginx rules, but it'ss separate from this one. This is strictly a display issue. I see, however, how one can be confused for the other now...

**Comment by manu-p** [comment]
Yep, that's what I can see for meet.jit.si. No, it's not a docker image, and apache2 is used, not nginx.

**Comment by manu-p** [comment]
jitsi-meet                            1.0.4299-1                                                all          WebRTC JavaScript video conferences
jitsi-meet-prosody                    1.0.3900-1                                                all          Prosody configuration for Jitsi Meet
jitsi-meet-turnserver                 1.0.3900-1                                                all          Configures coturn to be used with Jitsi Meet
jitsi-meet-web                        1.0.3900-1                                                all          WebRTC JavaScript video conferences
jitsi-meet-web-config                 1.0.3900-1                                                all          Configuration for web serving of Jitsi Meet
jitsi-videobridge                     1132-1                                                    amd64        WebRTC compatible Selective Forwarding Unit (SFU)

jicofo                                1.0-534-1                                                 all          JItsi Meet COnference FOcus

**Comment by saghul** [comment]
Then it looks like we have the same bug in both the nginx and apache2 configs. Can you please open a new issue about Apache 2? We are already tracking our Nginx default. Thanks!

**Comment by manu-p** [comment]
Will it be a copy of #5333? Or which issue regarding nginx?

**Comment by saghul** [comment]
No, the fix is needed in the apache 2 config. The fix in #5333 is about displaying the room name.. If you now enter in https://meet.jit.si/saúl123 the room name will be displayed as "Saul 123" (note the lack of the accent).

**Comment by manu-p** [comment]
OK, @saghul : issue  #5334

**Comment by obfusk** [comment]
This seems to be fixed now (by a46fd60).

**Comment by saghul** [comment]
Oops, yeah, forgot to close this one!
