### ISSUE TITLE
download.jitsi.org down

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#5224]
Dear Jitsi folks, just a heads-up, that the server `donwload.jitsi.org` is not reachable from several networks, so seems to be down.

    $ ping download.jitsi.org
    PING download.jitsi.org(download.jitsi.org (2001:660:2402::22)) 56 data bytes

**Comment by mboogert** [comment]
and up again...

**Comment by paulmenzel** [comment]
Thanks.
