### ISSUE TITLE
problems with recording

### ISSUE THREAD

**Issue by SaraC74** [jitsi/jitsi-meet#5225]
I try to record ..but always to busy..it say...

**Comment by saghul** [comment]
We don’t have unlimited recorders. If they are busy there is nothing you can do other than wait, sorry about that!

**Comment by SaraC74** [comment]
Thank you. Have a good evening.

Il giorno mer 18 mar 2020 alle ore 13:16 Saúl Ibarra Corretgé <
notifications@github.com> ha scritto:
