### ISSUE TITLE
Problem with livestreaming

### ISSUE THREAD

**Issue by Serg-93** [jitsi/jitsi-meet#5229]
Good evening! We can't start livestreaming. It says all streamers are corrently busy. What does it mean?

**Comment by saghul** [comment]
Hi there! We don't have infinite recorders, so it's possible reccording is temporarily unavailable. There is nothing you can do other than waiting.

**Comment by nidian2020** [comment]
I too have the same problem. Can you tell me how long it takes to fix the problem?

**Comment by rasos** [comment]
So does livestreaming with Google/YOutube require a recorder? It failed here as well in our setup, which would stream to rtmp://a.rtmp.youtube.com/live2
