### ISSUE TITLE
Unable to edit contact with numbers

### ISSUE THREAD

**Issue by ludoja** [jitsi/jitsi-meet#523]
By draging contact onto contact I unintentionally assigned 3 numbers to a contact. 

The contact then became uneditable - the right click of the mouse does not show the dropdown menu.

When I dragged another contact on it - so there were 4 numbers assigned to the contact, I was able to remove one number, but then the contact became uneditable again.

Is there another way, how to remove the contact?

**Comment by damencho** [comment]
Wrong issue tracker. 

You can shutdown jitsi and edit contactlist.xml.
