### ISSUE TITLE
Laptop Camera Non-Functional

### ISSUE THREAD

**Issue by impactpthillsboro** [jitsi/jitsi-meet#5236]
I am unable to view my clients through VSee's telehealth system. I have tried accessing my client through the web and through the Vsee app which have both failed. I am able to hear my clients but not see them. I am using Google Chrome web browser and a Lenovo laptop.

**Comment by saghul** [comment]
I don't know what VSee is or how it relates to Jitsi. Can you please clarify?

**Comment by alexanderadam** [comment]
Isn't this a duplicate of #5155?

**Comment by saghul** [comment]
Seems at least related...

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
