### ISSUE TITLE
No puedo grabar la sesión del webinar que estoy haciendo

### ISSUE THREAD

**Issue by diana8valeria** [jitsi/jitsi-meet#5237]
Estoy impartiendo un seminario en directo que debería quedar grabado y no graba, me sale un aviso que indica lo siguiente:

All recordings are currently bussy
We're working on freeing recording resources. Please try again in a few minutes.

^Pero lo intento, y lo intento, y lo intento
y sigue dando el mismo error.

¿Qué tengo que hacer?

Muchas gracias por su atención.

Un saludo.
Diana Valeria

**Comment by saghul** [comment]
Hola Diana,

Por favor busca en las incidencias abiertas antes de abrir una nueva. Es posible que no haya grabadores disponibles, no son ilimitados. No hay nada que puedas hacer salvo esperar. Lo siento.

**Comment by Juanjogual** [comment]
Cuando ejecuto una sala en mi ordenador utilizando la aplicación Droidcam como Webcam la pantalla se muestra de color naranja en lugar de mostrar mi imagen.
