### ISSUE TITLE
startWithAudioMuted causes problems with permissions in Chrome

### ISSUE THREAD

**Issue by rkralovic** [jitsi/jitsi-meet#5241]
## Description
Using startWithAudioMuted: true config value does not work correctly.

## Current behavior
Participants are muted when they join, but they also do not hear other participants. After they unmute themselves, they do hear others, but after they mute again, incoming audio stops as well.

## Expected Behavior
Participants are muted when they join and they always do hear others.

## Steps to reproduce
1. Set startWithAudioMuted: true
2. Create a room, unmute mic.
3. Connect other participant to the room. The participant is muted and also does not hear the first participant.

Browser javascript console log is attached:
[2.log](https://github.com/jitsi/jitsi-meet/files/4351544/2.log)

In particular, it contains the following error that does not happen when startWithAudioMuted is disabled:

```
Logger.js:154 2020-03-18T21:17:55.456Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
o @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:568
window.onunhandledrejection @ middleware.js:111
AbstractAudio.js:84 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
play @ AbstractAudio.js:84
(anonymous) @ middleware.js:41
```

# Environment details
Manual installation from source, all components are synced to stable/jitsi-meet_4101. Clients are using Google Chrome 80.0.3987.132.

**Comment by saghul** [comment]
Can you reproduce this on meet.jit.si ?

**Comment by rkralovic** [comment]
meet.jit.si does not have startWithAudioMuted set in the config (see https://meet.jit.si/config.js ) and, obviously, I have no write rights to files at meet.jit.si.

Is there an easy way to override config from client side?

**Comment by saghul** [comment]
Sure thing! meet.jit.si/teat123#config.startWithAudioMuted=true

**Comment by rkralovic** [comment]
Thanks!

I cannot reproduce it on meet.jit.si. What version is running there? (As I mentioned, I synced my deployment to stable/jitsi-meet_4101, which is from November 2019.)

Also, I noticed that the functionality I need can be also achieved by startAudioMuted=1, and that one is working with my deployment as well. Thus, this bug has rather low priority.

**Comment by saghul** [comment]
We may have botched something in a past release. If you cannot repro on meet.jit.si it means it's solved :-)

We'll be making a new stable release soon.
