### ISSUE TITLE
all streamers are currently busy

### ISSUE THREAD

**Issue by aybbr** [jitsi/jitsi-meet#5243]
Hi,

We were unable to start a live stream using Youtube stream key.
Jitsi shows the following error message: 
![image](https://user-images.githubusercontent.com/3009041/77016108-0be80080-6977-11ea-9add-02409e0e7cc4.png)
Trying again after waiting for few minutes like suggested, didn't solve the problem. Any idea if this will be quickly addressed or we need to look for another solution? 
Thanks

**Comment by saghul** [comment]
We will be increasing the pool of live streaming machines, but there will always be a limit.

**Comment by molinapj** [comment]
we have news? we're still having trouble with streamers.
