### ISSUE TITLE
Letsencrypt "Connection refused" because of nginx https redirect

### ISSUE THREAD

**Issue by vbraun** [jitsi/jitsi-meet#5246]
I did a fresh default install of Debian 10 with nginx and followed the quickstart instructions. The `install-letsencrypt-cert.sh` fails with
~~~~
root@01:~# /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
[...]
Performing the following challenges:
http-01 challenge for 01.my-domain.com
Using the webroot path /usr/share/jitsi-meet for all unmatched domains.
Waiting for verification...
Challenge failed for domain 01.my-domain.com
http-01 challenge for 01.my-domain.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: 01.meet.talque.com
   Type:   connection
   Detail: Fetching
   http://01.my-domain.com/.well-known/acme-challenge/3IhxF42Tw_gjbkzc-pvawnesDHehnqmR4ozwerZItj0:
   Connection refused
~~~~
This is because nginx unconditionally redirects http -> https but apparently letsencrypt either doesn't follow or doesn't trust the self-signed cert.

I had to change the nginx configuration file to
~~~~
server {
    listen 80;
    server_name 01.my-domain.com;

    # I had to add this: allow insecure http for the letsencrypt challenge
    location /.well-known/acme-challenge/ {
        root /usr/share/jitsi-meet;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name 01.my-domain.com;
[...]
~~~~
This is Debian 10 in a VM on OVH cloud, I think thats a vanilla Debian install but haven't verified. I looked at the jitsi-meet-web-config.postinst script and its doesn't change the http section of the config file.

**Comment by saghul** [comment]
Did you first install your system with a self-signed cert or did you choose letsencrypt at installation time?

**Comment by vbraun** [comment]
I only installed nginx (`apt-get install nginx`), that didn't ask me anything about certs. But must have silently created a self-signed cert since I got the chrome cert warning screen when I tried to debug the error from `install-letsencrypt-cert.sh`.

**Comment by damencho** [comment]
I think, there is a fix for this on unstable these two locations for http: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L7

**Comment by damencho** [comment]
Once we update packages this will be fixed.
