### ISSUE TITLE
Keystore : Use P12 instead of JKS

### ISSUE THREAD

**Issue by bugeaud** [jitsi/jitsi-meet#5253]
At this time, the setup is using the legacy JKS keystore format.

I suggest we could switch to PKCS#12 (.p12 files) format instead because it is a more standard and interroperable format to work with other part of an infratructure.

A bit of configuration is anticipated at Java level, but P12 is fully supported and even used by default on Java 9 :
https://openjdk.java.net/jeps/229

A handy JKS to P12 script can be brought for migration purposes if required.

**Comment by saghul** [comment]
You mean the debug.keystore store? That’s just for testing, it’s not used in production so I see no real benefit in changing it.

Or is it something else?

**Comment by bugeaud** [comment]
Actually in every situation where it applies. For instance when using Jetty as frontend, a JKS is used as a keystore AFAIK.

Here is an extract of the install-letsencrypt-cert.sh that give a hint :

` # create jks from  certs
    openssl pkcs12 -export \
        -in $CERT_CRT -inkey $CERT_KEY -passout pass:changeit > $CERT_P12
    keytool -importkeystore -destkeystore $CERT_JKS \
        -srckeystore $CERT_P12 -srcstoretype pkcs12 \
        -noprompt -storepass changeit -srcstorepass changeit`

Switching this to P12 on the Java side would result in removing such boiler plate config that was required for Java's legacy purpose (Java used to only support JKS as keystore already built-in format).

**Comment by damencho** [comment]
We had moved away from jetty in the latest packages, which soon will hit stable.

**Comment by bugeaud** [comment]
Which frontend will be used instead ?

**Comment by damencho** [comment]
nginx is used by default if none of apache or nginx is already installed.

**Comment by bugeaud** [comment]
Will there still be anywhere in Jitsi a use of JSSE or JCE to handle either some crypto or TLS socket for any use ? No = #5253 to be closed. Yes = #5253 still applicable.

**Comment by damencho** [comment]
These were certificates used only for jetty and the webserver, anything else does not need that.
