### ISSUE TITLE
Infinity share effect for screen sharer if participant leaves mid-meeting.

### ISSUE THREAD

**Issue by shrihari1999** [jitsi/jitsi-meet#5255]
## Description
If a participant (sharer) needs to share their browser window, they are likely to share entire screen or browser window. In either case, if another participant leaves mid-meeting and the sharer returns to their jitsi page, they are greeted with an ever-growing infinity effect as shown. However, if the sharer does not share the browser that jitsi is running on, everything seems fine.

![2020-03-19-195734_1440x900_scrot](https://user-images.githubusercontent.com/13913674/77078790-1230b800-6a1d-11ea-9af6-dcbe9f917249.png)

## Current behavior
Infinity effect is observed by screen sharer if they are sharing their browser and a participant leaves.

## Expected Behavior
Nothing weird should occur and the meeting should carry on normally.

## Steps to reproduce
Connect two people
Start screen sharing browser which has jitsi open.
Disconnect the non-sharer.
Observe infinity effect for sharer.

# Environment details
Jitsi's tested: meet.jit.si, my own deployment (v1.0.4101-1).
Browsers tested: Chrome, Firefox on macOS Catalina 10.15.3 and Ubuntu 16.04

**Comment by damencho** [comment]
Please use the community forum for problems and questions before opening new issues.

This is normal effect, same as if you put a mirror against another mirror.
Why would you share your video screen? People already have it and see it.

**Comment by shrihari1999** [comment]
I'm afraid you have mistaken. If I want to share other tabs of the same browser what else would you do?
