### ISSUE TITLE
F-Droid Android client 19.4.0 echo cancellation not working

### ISSUE THREAD

**Issue by vandys** [jitsi/jitsi-meet#5259]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
On the newest build on F-Droid (19.4.0) for Android, the client starts well, connections to conferences, displays roster.

## Current behavior
---
In an audio-only conference, turning on the mic and speaking results in a feedback howl.
Your audio comes back out through the speaker, reaching the mic.

## Expected Behavior
---
I expect echo cancellation to keep this from happening.  Your own audio should
not come out your own speaker.

## Possible Solution
---
Echo cancellation is complex, but Android has a decent toolbox of ways to mitigate it.

## Steps to reproduce
---
Install latest from F-droid to two phones.  Connect both to a room (mic & camera off).
Now turn on mics and try to speak to each other.

# Environment details
---
Various Android phones, pretty much Pie from LineageOS.

**Comment by saghul** [comment]
Please update to version 20.0.3 which we released yesterday on F-Droid.

**Comment by vandys** [comment]
Still happening between phones running 20.0.3?

**Comment by saghul** [comment]
Echo cancellation is a dark art, we use the HW echo canceller via the WebRTC library. If there is still echo, there is nothing we can really do, sorry.
