### ISSUE TITLE
can't hear or be heard on 32bit Ubuntu

### ISSUE THREAD

**Issue by jeetsee** [jitsi/jitsi-meet#526]
Running - Ubuntu 12.04.05 32bit (Kernel: Linux Ubuntu 3.13.0-32-generic)
Browser - Chromium 37.0.2062

When I join a chat room I can see everyone else as well as hear the join notification noise but I can not hear them talking and they can not hear me talk.

I have tried a number of Ubuntu 12.04 32bit computers with Chromium and they all have the same problem.  Tests have also included a freshly installed OS

Below is the output from console in Chromium during  a test:

    (TIME) index.html loaded:	 142.74999999977834 ThisIsATest:13
    This appears to be Chrome, ver: 37 RTCBrowserType.js:81
    (TIME) document ready:	 584.2159999997782 app.js:127
    [/modules/RTC/ScreenObtainer.js] <Object.ScreenObtainer.init>:    Using Chrome extension for desktop sharing Logger.js:89
    [/modules/RTC/ScreenObtainer.js] <>:    Chrome extension installed: false updateRequired: false Logger.js:89
    [/modules/RTC/RTCUtils.js] <Object.RTCUtils.getUserMediaWithConstraints>:    Get media constraints Object {audio: Object, video: Object, [object Object]: (...)} Logger.js:89
    [/modules/xmpp/xmpp.js] <Object.connect_callback>:    (TIME) Strophe CONNECTING	:774.0809999997782 Logger.js:89
    [/modules/RTC/RTCUtils.js] <>:    onUserMediaSuccess Logger.js:89
    [/modules/xmpp/xmpp.js] <Object.connect_callback>:    (TIME) Strophe CONNECTED	:1797.7909999997783 Logger.js:89
    [/modules/xmpp/xmpp.js] <Object.connect_callback>:    My Jabber ID: 525d1f21-707f-48d3-ac55-57ada34e9d01@meet.jit.si/6d41eb35-c80e-4d0e-a773-a7dc00608798 Logger.js:89
    initialized with 2 local tracks conference.js:295
    [/modules/settings/Settings.js] <new Settings>:    generated id e5b32311e1b60de24001e57ac650c6de Logger.js:89
    [/modules/settings/Settings.js] <new Settings>:    generated callstats uid Grayce-1Gf Logger.js:89
    [/modules/xmpp/ChatRoom.js] <new ChatRoom>:    Joined MUC as ThisIsATest@conference.meet.jit.si/525d1f21 Logger.js:89
    2[/modules/xmpp/ChatRoom.js] <ChatRoom.addStream>:    No conference handler or conference not started yet Logger.js:89
    Peer video type changed:    525d1f21 camera VideoLayout.js:801
    [/modules/xmpp/moderator.js] <Moderator.setFocusUserJid>:    Focus jid set to:    undefined Logger.js:89
    [/modules/xmpp/moderator.js] <Moderator.createConferenceIq>:    Session ID: null machine UID: e5b32311e1b60de24001e57ac650c6de Logger.js:89
    [/modules/xmpp/strophe.ping.js] <Object.Strophe.addConnectionPlugin.startInterval>:    XMPP pings will be sent every 10000 ms Logger.js:89
    [/modules/xmpp/moderator.js] <Moderator.setFocusUserJid>:    Focus jid set to:    focus@auth.meet.jit.si Logger.js:89
    [/modules/xmpp/moderator.js] <Moderator.parseConfigOptions>:    Authentication enabled: false Logger.js:89
    External authentication enabled: false moderator.js:225
    [/modules/xmpp/moderator.js] <Moderator.parseConfigOptions>:    Sip gateway enabled:    false Logger.js:89
    [/modules/xmpp/ChatRoom.js] <ChatRoom.onPresence>:    entered ThisIsATest@conference.meet.jit.si/focus Object {show: "", status: "", affiliation: "owner", role: "moderator",    jid: "focus@auth.meet.jit.si/focus19623899763"…} Logger.js:89
    [/modules/xmpp/ChatRoom.js] <ChatRoom.onPresence>:    Ignore focus: ThisIsATest@conference.meet.jit.si/focus, real JID: focus@auth.meet.jit.si/focus19623899763 Logger.js:89
    Etherpad is enabled UI.js:466
    (TIME) MUC joined:	 2507.200999999778 ChatRoom.js:260
    No avatar stored yet for 525d1f21 - using ID as avatar ID Avatar.js:45
    No avatar stored yet for 525d1f21 - using ID as avatar ID Avatar.js:45
    hover in 525d1f21 LargeVideo.js:414
    No avatar stored yet for 525d1f21 - using ID as avatar ID Avatar.js:45
    My role changed, new role: moderator conference.js:594
    [/modules/xmpp/ChatRoom.js] <ChatRoom.onPresence>:    entered ThisIsATest@conference.meet.jit.si/8797728d Object {show: "", status: "", affiliation: "none", role:     "participant", jid: "8797728d-9a8c-496f-b81e-37776b35fd25@meet.jit.si/b5ce1b34-28a6-42af-9e43-a7e74e970ffb"…} Logger.js:89
    USER 8797728d connnected JitsiParticipant {_jid: "ThisIsATest@conference.meet.jit.si/8797728d", _id: "8797728d", _conference: JitsiConference, _displayName: undefined,     _supportsDTMF: false…} conference.js:576
    No avatar stored yet for 8797728d - using ID as avatar ID Avatar.js:45
    No avatar stored yet for 8797728d - using ID as avatar ID Avatar.js:45
    Missed avatar update - no small video yet for 8797728d VideoLayout.js:902
    [/modules/xmpp/strophe.jingle.js] <Object.Strophe.addConnectionPlugin.onJingle>:    on jingle session-initiate from ThisIsATest@conference.meet.jit.si/focus <iq xmlns=​"jabber:​client" type=​"set" to=​"525d1f21-707f-48d3-ac55-57ada34e9d01@meet.jit.si/​6d41eb35-c80e-4d0e-a773-a7dc00608798" from=​"ThisIsATest@conference.meet.jit.si/​focus" id=​    "NTI1ZDFmMjEtNzA3Zi00OGQzLWFjNTUtNTdhZGEzNGU5ZDAxQG1lZXQuaml0LnNpLzZkNDFlYjM1LWM4MGUtNGQwZS1hNzczLWE3ZGMwMDYwODc5OABjVzdvTS05NDU5MDY0APeG2V0Gl4CBjACpKksGazE=">​…​</iq>​     Logger.js:89
    (TIME) received session-initiate:	 74651.89699999978 strophe.jingle.js:97
    Halt: There are no SSRC groups in the remote description. index.js:133
    [/modules/statistics/CallStats.js] <null.<anonymous>>:    TypeError {stack: (...), message: "undefined is not a function", [object Object]: (...)} Logger.js:89
    [/modules/xmpp/JingleSessionPC.js] <TraceablePeerConnection.peerconnection.onaddstream>:    REMOTE STREAM ADDED:    MediaStream {onremovetrack: null, onaddtrack: null, onended: null, ended: false, id: "mixedmslabel"…} mixedmslabel Logger.js:89
    [/modules/xmpp/JingleSessionPC.js] <>:    setLocalDescription failed Failed to set local answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to add send stream ssrc: 3753778175. Logger.js:89
    CONFERENCE FAILED: conference.setup_failed conference.js:165
    [/modules/xmpp/JingleSessionPC.js] <JingleSessionPC.sendIceCandidates>:    sendIceCandidates [RTCIceCandidate, RTCIceCandidate, RTCIceCandidate, [object Object]: (...)] Logger.js:89
    [/modules/xmpp/JingleSessionPC.js] <JingleSessionPC.sendIceCandidates>:    sendIceCandidates [RTCIceCandidate, RTCIceCandidate, RTCIceCandidate, [object Object]: (...)] Logger.js:89
    [/modules/xmpp/JingleSessionPC.js] <JingleSessionPC.sendIceCandidate>:    Have we encountered any srflx candidates? false Logger.js:89
    [/modules/xmpp/JingleSessionPC.js] <JingleSessionPC.sendIceCandidate>:    Have we encountered any relay candidates? false Logger.js:89
    [/modules/xmpp/ChatRoom.js] <ChatRoom.onPresence>:    entered ThisIsATest@conference.meet.jit.si/227362ac Object {show: "", status: "", affiliation: "none", role:    "participant", jid: "227362ac-4b04-4f59-bf53-a038c57e26a5@meet.jit.si/d7f0009e-e248-4d63-a84d-d17a7e50f861"…} Logger.js:89
    USER 227362ac connnected JitsiParticipant {_jid: "ThisIsATest@conference.meet.jit.si/227362ac", _id: "227362ac", _conference: JitsiConference, _displayName: undefined,    _supportsDTMF: false…} conference.js:576
    No avatar stored yet for 227362ac - using ID as avatar ID Avatar.js:45
    No avatar stored yet for 227362ac - using ID as avatar ID Avatar.js:45
    Missed avatar update - no small video yet for 227362ac VideoLayout.js:902
    USER 227362ac LEFT JitsiParticipant {_jid: "ThisIsATest@conference.meet.jit.si/227362ac", _id: "227362ac", _conference: JitsiConference, _displayName: undefined,     _supportsDTMF: false…} conference.js:585
    Removing remote video: 227362ac VideoLayout.js:786
    Remove thumbnail 227362ac RemoteVideo.js:171
    [/modules/xmpp/moderator.js] <Moderator.onMucMemberLeft>:    Someone left is it focus ? ThisIsATest@conference.meet.jit.si/227362ac Logger.js:89
    USER 8797728d LEFT JitsiParticipant {_jid: "ThisIsATest@conference.meet.jit.si/8797728d", _id: "8797728d", _conference: JitsiConference, _displayName: undefined,     _supportsDTMF: false…} conference.js:585
    Removing remote video: 8797728d VideoLayout.js:786
    Remove thumbnail 8797728d RemoteVideo.js:171
    [/modules/xmpp/moderator.js] <Moderator.onMucMemberLeft>:    Someone left is it focus ? ThisIsATest@conference.meet.jit.si/8797728d

**Comment by damencho** [comment]
Can you please forward your questions to the mailinglist.
The chromium version is pretty old, can you test with it whether meet.jit.si is working for you.
