### ISSUE TITLE
doc improvement: make clear that /etc/hostname must match /etc/hosts

### ISSUE THREAD

**Issue by simevo** [jitsi/jitsi-meet#5260]
Admins of self-hosted instances may encounter trouble if `/etc/hostname` does not match `/etc/hosts`, see for example: https://community.jitsi.org/t/default-jitsi-installation-gives-error-bridge-channel-send-no-opened-channel/23740

The ["Jitsi Meet quick install" guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) tells you what to put in `/etc/hosts` but does not elaborate about `/etc/hostname`. Also in the "Install Jitsi Meet" section it states that Jitsi Meet can be installed without a resolvable FQDN, but this is not consistent with what appears in the "Basic Jitsi Meet install".

I suggest to change this section thus:

```
Set up the Fully Qualified Doman Name (FQDN) (optional)

If the machine used to host the Jitsi Meet instance has a FQDN hostname already set up in DNS, `/etc/hostname` must contain this FQDN; if this is not case yet, [change the hostname](https://wiki.debian.org/it/HowTo/ChangeHostname).
Then add the the same FQDN in the `/etc/hosts` file , associating it with the loopback address:
127.0.0.1 localhost meet.example.org
Finally test that you can ping the FQDN with: ping "$(hostname)"
```

**Comment by saghul** [comment]
👍  are you up for ssending a PR?

**Comment by simevo** [comment]
OK will do

**Comment by seanm** [comment]
I followed the quick-install doc pretty closely but in the end the web page worked but video and audio didn't. Various searching got me here. I wiped my VM and started over, following the hostname suggestions in this patch, and now things work.  There were some other differences too, so I can't be sure this was my only problem, but using this setup definitely works.

**Comment by saghul** [comment]
The docs commit landed, right? Closing here then.

**Comment by simevo** [comment]
https://github.com/jitsi/jitsi-meet/pull/5279 is still open, probably I canceled your approval by amending my 1st commit to fix a typo ...

**Comment by saghul** [comment]
Oops, landed!
