### ISSUE TITLE
Notifications toasts block ui elements

### ISSUE THREAD

**Issue by svelle** [jitsi/jitsi-meet#5263]
## Description

Info toast pop ups are covering controls

## Current behavior

When multiple users join a meeting or the user wants to start a youtube video while another one is playing notifications toasts/popups show up which cover up ui elements.

## Expected Behavior

Popups are spawned at a different location of the interface so they don't cover up ui elements.

## Possible Solution

Move popups to a different position (upper left for example)

## Steps to reproduce

Start a meeeting, have multiple people connect and disconnect again, also try to start another yt video while one is already playing.

![Annotation 2020-03-19 195532](https://user-images.githubusercontent.com/7526550/77104607-8d459e80-6a1c-11ea-8984-ee056553c741.png)

## Environment Details

Jitsi Meet latest version in latest stable Chrome

**Comment by saghul** [comment]
Yeah, they are not great. We are currenly already working on a new design for them.

**Comment by svelle** [comment]
> Yeah, they are not great. We are currenly already working on a new design for them.

thanks for the update. I couldn't find a ticket (partially because I didn't know what to look for) so I just opened one.

Thanks for your great work folks, keep it up!

**Comment by robsdedude** [comment]
I'd also be interested in following the progress. So @saghul, is there an Issue or PR I could subscribe to?

**Comment by Weptun** [comment]
This still happens with the newest version. If more than one notification is displayed they overlap the toolbox with the mute/unmute buttons etc.
