### ISSUE TITLE
Jitsi Meet says all streamers are currently busy

### ISSUE THREAD

**Issue by CL-Flyer** [jitsi/jitsi-meet#5266]
Jitsi Meet says "All streamers are currently busy." It's been several days now. Is there a tech problem?Or has the Jitsi staff bugged out because of the COVID fright?... I hope not. Any help would be greatly appreciated, as we need to broadcast our twice-weekly show Friday night.
Thanks,
Rusty K

**Comment by damencho** [comment]
We are working on fixing it.

**Comment by CL-Flyer** [comment]
Thanks for your reply, Damencho.
