### ISSUE TITLE
Installation error: webpack: Command not found

### ISSUE THREAD

**Issue by flberger** [jitsi/jitsi-meet#5267]
## Description
I am following the installation procedure at https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md At "Deploy Jitsi Meet", it says:

> cd /srv
> git clone https://github.com/jitsi/jitsi-meet.git
> cd jitsi-meet
> npm install
> make

## Current behavior
`make` fails with:

> ./node_modules/.bin/webpack -p
> make: ./node_modules/.bin/webpack: Command not found
> make: *** [Makefile:19: compile] Error 127

## Expected Behavior
webpack should apparently be found at ./node_modules/.bin/webpack , and the installation should complete.

# Environment details
OS is Gentoo linux, npm 6.12.0

Maybe related to #2732

**Comment by saghul** [comment]
Did npm install succeed?

**Comment by flberger** [comment]
Apparently not. It keeps segfaulting.

> npm install
> Segmentation fault extract:react-native-callstats: sill extract react-native-callstats@3.61.0 extracted to /home/prosody/jitsi-meet/node_modules/.staging/react-na

I'll try with a global installation of webpack.

**Comment by flberger** [comment]
Got it working with a global installation. Will report further issues in a different bug.
