### ISSUE TITLE
How to get files after recording? 

### ISSUE THREAD

**Issue by maxdonetsk** [jitsi/jitsi-meet#527]
Here is my configuration settings for video recording:
org.jitsi.videobridge.ENABLE_MEDIA_RECORDING=true
org.jitsi.videobridge.MEDIA_RECORDING_PATH=/rec
org.jitsi.videobridge.MEDIA_RECORDING_TOKEN=12345678

How can I downloaded these files as a user (without admin rights)?

**Comment by geckolinux** [comment]
I supposed you could just use Nginx or something to allow browsing the recording directory with a username and password. But I would also like an integrated solution for achieving this.
