### ISSUE TITLE
[feature request] Add keyboard shortcut and icon for "Everybody follows me"

### ISSUE THREAD

**Issue by fd0** [jitsi/jitsi-meet#5272]
**Is your feature request related to a problem you are facing?**

I'm holding workshops using jitsi-meet together with a second person. The usual setup is us on one side, and a group of people in a room on the other side.

For discussions, we enable the "Everybody follows me" (EFM) and switch to the tile view. After the discussion is over, we switch back to our video (for all), then disable EFM, and switch only our view this time to the video of the other participant (usually a group in a room).

This way, we can control their projector image without anybody on the remote side having to take care of it and see the group video in large on our screen.

The problem is that toggling EFM takes us five mouse clicks each time.

**Describe the solution you'd like**

I'd like to be able to toggle EFM with a keyboard shortcut (or a single mouse click), ideally including a highlighted button which shows the state. This could be similar to the tile view button.

**Describe alternatives you've considered**

I've tried adding the keyboard shortcut myself and [asked about it](https://community.jitsi.org/t/how-to-add-key-bindings/24023/2?u=fd0), there's no easy way to add keyboard shortcuts right now.

**Closing remarks**

I'm willing to work on a PR which adds this feature (given a bit of guidance). Please let me know if such a PR would be merged :)

Thank you very much for all the work! Jitsi is awesome!

**Comment by saghul** [comment]
I think we would be ok with this contribution, thanks! Note we may not be able to provide a lot of guidance right now since we're quite  busy, sorry!

**Comment by fd0** [comment]
> Note we may not be able to provide a lot of guidance right now since we're quite busy, sorry!

Understood, no problem :)

**Comment by fd0** [comment]
FYI, I'm working on something

**Comment by fd0** [comment]
The PR was closed so I'm also closing this issue. Thanks!
