### ISSUE TITLE
No Sound on iOS-App when conferencing with people from other subnets

### ISSUE THREAD

**Issue by Shaddowpain** [jitsi/jitsi-meet#5274]
## Description
When joining a conferece with iOS or Android App using our own hosted jitsi-server all sound, webcam and screen-sharing crashes. Sound, webcam and screen-sharing is availible after a few seconds, when App-User leaves the conference.

## Current behavior
We're hosting our own jitsi server. Its behind a stateful NAT. Firewall allows incomming traffic from tcp:80/443 and udp:10000. We configured our server like this:
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
Furthermore we've configured secure domains - exactly like the tutorial for internal authentication.

Everything is working fine when having conferences with WebClients(Chrome or Firefox). It does kill all sound or screen-sharing when a iOS or Android Client is joining the conference wich is not on the same subnet lika all other conference participiants(the web-client user).
WebClient Users can be in different subnets or locations.

## Expected Behavior
No denys on firewall are logged
Stateful NAT - all Ports are translated
Local and public IP is set in "/etc/jitsi/videobridge/sip-communicator.properties"

# Environment details
Jitsi is running on our VMWare Cluster on Ubuntu 18.04.04 LTS VM. Enough CPU/RAM/Storage is available. 1Gbit/s Up/Down-Bandwith available.
Public IP is translated to private IP with stateful NAT.

Any Ideas what is going wrong?
Thanks in advance!

**Comment by saghul** [comment]
What's in your `/etc/jitsi/videobridge/sip-communicator.properties` file? Do the mobile endpoints have a route to the public IP you put there?

**Comment by Shaddowpain** [comment]
`rg.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.jitsi.company.tld/.*
org.jitsi.videobridge.rest.jetty.host=::
org.jitsi.videobridge.rest.jetty.port=443
org.jitsi.videobridge.rest.jetty.ProxyServlet.hostHeader=jitsi.company.tld
org.jitsi.videobridge.rest.jetty.ProxyServlet.pathSpec=/http-bind
org.jitsi.videobridge.rest.jetty.ProxyServlet.proxyTo=http://localhost:5280/http-bind
org.jitsi.videobridge.rest.jetty.ResourceHandler.resourceBase=/usr/share/jitsi-meet
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./config.js=/etc/jitsi/meet/jitsi.company.tld-config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./interface_config.js=/usr/share/jitsi-meet/interface_config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./logging_config.js=/usr/share/jitsi-meet/logging_config.js
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./external_api.js=/usr/share/jitsi-meet/libs/external_api.min.js
org.jitsi.videobridge.rest.jetty.RewriteHandler.regex=^/([a-zA-Z0-9]+)$
org.jitsi.videobridge.rest.jetty.RewriteHandler.replacement=/
org.jitsi.videobridge.rest.jetty.SSIResourceHandler.paths=/
org.jitsi.videobridge.rest.jetty.tls.port=443
org.jitsi.videobridge.TCP_HARVESTER_PORT=443
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePath=/etc/jitsi/videobridge/jitsi.company.tld.jks
org.jitsi.videobridge.rest.jetty.sslContextFactory.keyStorePassword=PASSWD
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=PRIV-IPv4-Addr
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=PUBL-IPv4-Addr
`

Is this defined in the last two lines?
Or did i missed a line?

Thank you in advance!

**Comment by saghul** [comment]
> org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=PUBL-IPv4-Addr

Is the IP you put here reachable by the mobile clients from their subnet?

**Comment by Shaddowpain** [comment]
Yes it is. It's a public IP wich can be reached worldwide. From the internal company network or from home-office e.g..

**Comment by saghul** [comment]
What do you see in the JS console logs on a browser client when the mobile client joins?

**Comment by Shaddowpain** [comment]
`Logger.js:154 2020-03-20T11:43:01.184Z [modules/xmpp/ChatRoom.js] <t.value>:  entered test2@conference.jitsi.company.tld/1cd98b2c {affiliation: "none", role: "participant", jid: "1cd98b2c-c443-4180-9d79-ce76339d7ec5@guest.jitsi.h…company.tld/ba75c5bc-7f43-46a5-baf2-0a6d28595a0b", isFocus: false, isHiddenDomain: false, …}
Logger.js:154 2020-03-20T11:43:01.235Z [conference.js] <c.<anonymous>>:  USER 1cd98b2c connnected: e {_jid: "test2@conference.jitsi.company.tld/1cd98b2c", _id: "1cd98b2c", _conference: ee, _displayName: "Dennis", _supportsDTMF: false, …}
Logger.js:154 2020-03-20T11:43:01.373Z [modules/xmpp/ChatRoom.js] <t.value>:  Ignore focus: test2@conference.jitsi.company.tld/focus, real JID: focus@auth.jitsi.company.tld/focus19728320335
Logger.js:154 2020-03-20T11:43:01.542Z [modules/UI/videolayout/LargeVideoManager.js] hover in %s 1cd98b2c
Logger.js:154 2020-03-20T11:43:01.698Z [modules/xmpp/ChatRoom.js] <t.value>:  Ignore focus: test2@conference.jitsi.company.tld/focus, real JID: focus@auth.jitsi.company.tld/focus19728320335
Logger.js:154 2020-03-20T11:43:01.701Z [modules/xmpp/ChatRoom.js] <t.value>:  Ignore focus: test2@conference.jitsi.company.tld/focus, real JID: focus@auth.jitsi.company.tld/focus19728320335
Logger.js:154 2020-03-20T11:43:01.703Z [modules/xmpp/strophe.jingle.js] <s.value>:  on jingle session-initiate from test2@conference.jitsi.company.tld/focus <iq xmlns=​"jabber:​client" type=​"set" to=​"ea7e0d96-7fad-4278-8546-52b352d63b33@guest.jitsi.company.tld/​d13f47d1-62e2-4e81-9f8c-2d2d74739d40" from=​"test2@conference.jitsi.company.tld/​focus" id=​"ZWE3ZTBkOTYtN2ZhZC00Mjc4LTg1NDYtNTJiMzUyZDYzYjMzQGd1ZXN0LmppdHNpLmhmZy1vZmZlbmJhY2guZGUvZDEzZjQ3ZDEtNjJlMi00ZTgxLTlmOGMtMmQyZDc0NzM5ZDQwAFZGTGZzLTU2MDkAVFMwBnJCXH5fluB506lQdg==">​…​</iq>​
Logger.js:154 2020-03-20T11:43:01.704Z [modules/xmpp/strophe.jingle.js] <s.value>:  (TIME) received session-initiate:	 33046.97500000111
Logger.js:154 2020-03-20T11:43:01.704Z [modules/xmpp/strophe.jingle.js] <s.value>:  Marking session from test2@conference.jitsi.company.tld/focus as *not* P2P
index.js:44 SdpSimulcast: using 3 layers
Logger.js:154 2020-03-20T11:43:01.713Z [modules/RTC/TraceablePeerConnection.js] <new w>:  Create new TPC[1,p2p:false]
Logger.js:154 2020-03-20T11:43:01.716Z [JitsiConference.js] <ee._acceptJvbIncomingCall>:  Starting CallStats for JVB connection...
Logger.js:154 2020-03-20T11:43:01.720Z [modules/RTC/TraceablePeerConnection.js] <w.addTrack>:  add LocalTrack[1,audio] to: TPC[1,p2p:false]
index.js:146 Halt: There are no SSRC groups in the remote description.
Logger.js:154 2020-03-20T11:43:01.890Z [modules/RTC/TraceablePeerConnection.js] <w._remoteStreamAdded>:  TPC[1,p2p:false] ignored remote 'stream added' event for non-user streamid: mixedmslabel
Logger.js:154 2020-03-20T11:43:01.893Z [modules/RTC/TraceablePeerConnection.js] <w.generateRecvonlySsrc>:  TPC[1,p2p:false] generated new recvonly SSRC: 3001190743
Logger.js:154 2020-03-20T11:43:01.894Z [modules/xmpp/SdpConsistency.js] <e.value>:  TPC[1,p2p:false] no SSRC found for the recvonly videostream!
Logger.js:154 2020-03-20T11:43:01.900Z [modules/RTC/TraceablePeerConnection.js] <w._processLocalSSRCsMap>:  Storing new local SSRC for LocalTrack[1,audio] in TPC[1,p2p:false] {ssrcs: Array(1), groups: Array(0), msid: "fda988e2-079f-4c2b-aae0-6bf0e6181b6d 9ebff4e5-0f3c-41d8-94c8-52d78439bc52"}
Logger.js:154 2020-03-20T11:43:01.937Z [modules/xmpp/JingleSessionPC.js] <t.value>:  Sending session-accept <iq to=​"test2@conference.jitsi.company.tld/​focus" type=​"set" xmlns=​"jabber:​client" id=​"26d26f6a-eaf3-4900-8278-2309dc931cb6:​sendIQ">​…​</iq>​
Logger.js:154 2020-03-20T11:43:01.939Z [modules/xmpp/JingleSessionPC.js] <w.peerconnection.oniceconnectionstatechange>:  (TIME) ICE checking P2P? false:	 33281.57999999894
Logger.js:154 2020-03-20T11:43:01.943Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.944Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "4"
Logger.js:154 2020-03-20T11:43:01.944Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "50"
Logger.js:154 2020-03-20T11:43:01.946Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.946Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "2"
Logger.js:154 2020-03-20T11:43:01.947Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "10"
Logger.js:154 2020-03-20T11:43:01.951Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.951Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "3"
Logger.js:154 2020-03-20T11:43:01.951Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "10"
Logger.js:154 2020-03-20T11:43:01.953Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.953Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "1"
Logger.js:154 2020-03-20T11:43:01.954Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "10"
Logger.js:154 2020-03-20T11:43:01.966Z [modules/xmpp/JingleSessionPC.js] <t.value>:  sendIceCandidates (4) [RTCIceCandidate, RTCIceCandidate, RTCIceCandidate, RTCIceCandidate]
Logger.js:154 2020-03-20T11:43:01.969Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.969Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "4"
Logger.js:154 2020-03-20T11:43:01.969Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "50"
Logger.js:154 2020-03-20T11:43:01.970Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.970Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "2"
Logger.js:154 2020-03-20T11:43:01.970Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "10"
Logger.js:154 2020-03-20T11:43:01.970Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.971Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "3"
Logger.js:154 2020-03-20T11:43:01.971Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "10"
Logger.js:154 2020-03-20T11:43:01.971Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "ufrag" = "pcsP"
Logger.js:154 2020-03-20T11:43:01.971Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-id" = "1"
Logger.js:154 2020-03-20T11:43:01.971Z [modules/xmpp/SDPUtil.js] <Object.candidateToJingle>:  not translating "network-cost" = "10"
Logger.js:154 2020-03-20T11:43:02.026Z [modules/xmpp/JingleSessionPC.js] <w.peerconnection.oniceconnectionstatechange>:  (TIME) ICE connected P2P? false:	 33368.89499999961
Logger.js:154 2020-03-20T11:43:02.032Z [modules/xmpp/JingleSessionPC.js] <t.value>:  sendIceCandidate: last candidate.
Logger.js:154 2020-03-20T11:43:02.131Z [modules/statistics/RTPStatsCollector.js] <f.processAudioLevelReport>:  1900744016 not enough data
o @ Logger.js:154
f.processAudioLevelReport @ RTPStatsCollector.js:918
(anonymous) @ RTPStatsCollector.js:329
Logger.js:154 2020-03-20T11:43:02.254Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onopen>:  datachannel channel opened
Logger.js:154 2020-03-20T11:43:02.254Z [JitsiConferenceEventManager.js] <c.<anonymous>>:  (TIME) data.channel.opened 33597.49000000011
Logger.js:154 2020-03-20T11:43:02.255Z [modules/RTC/BridgeChannel.js] <e.value>:  sending pinned changed notification to the bridge for endpoint  null
Logger.js:154 2020-03-20T11:43:02.256Z [modules/RTC/BridgeChannel.js] <e.value>:  sending selected changed notification to the bridge for endpoints ["1cd98b2c"]
Logger.js:154 2020-03-20T11:43:02.256Z [modules/RTC/BridgeChannel.js] <e.value>:  sending a ReceiverVideoConstraint message with a maxFrameHeight of 1080 pixels
Logger.js:154 2020-03-20T11:43:02.327Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onmessage>:  Channel new dominant speaker event:  ea7e0d96
Logger.js:154 2020-03-20T11:43:02.346Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onmessage>:  Channel new last-n event:  [] {colibriClass: "LastNEndpointsChangeEvent", lastNEndpoints: Array(0), endpointsEnteringLastN: Array(0), conferenceEndpoints: Array(0)}
Logger.js:154 2020-03-20T11:43:02.366Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onmessage>:  Channel new last-n event:  ["1cd98b2c"] {colibriClass: "LastNEndpointsChangeEvent", lastNEndpoints: Array(1), endpointsEnteringLastN: Array(1), conferenceEndpoints: Array(1)}
Logger.js:154 2020-03-20T11:43:02.375Z [modules/xmpp/strophe.jingle.js] <s.value>:  on jingle source-add from test2@conference.jitsi.company.tld/focus <iq xmlns=​"jabber:​client" type=​"set" to=​"ea7e0d96-7fad-4278-8546-52b352d63b33@guest.jitsi.company.tld/​d13f47d1-62e2-4e81-9f8c-2d2d74739d40" from=​"test2@conference.jitsi.company.tld/​focus" id=​"ZWE3ZTBkOTYtN2ZhZC00Mjc4LTg1NDYtNTJiMzUyZDYzYjMzQGd1ZXN0LmppdHNpLmhmZy1vZmZlbmJhY2guZGUvZDEzZjQ3ZDEtNjJlMi00ZTgxLTlmOGMtMmQyZDc0NzM5ZDQwAFZGTGZzLTU2MzEAVFMwBnJCXH5fluB506lQdg==">​…​</iq>​
Logger.js:154 2020-03-20T11:43:02.383Z [modules/xmpp/JingleSessionPC.js] Processing addRemoteStream
Logger.js:154 2020-03-20T11:43:02.383Z [modules/xmpp/JingleSessionPC.js] ICE connection state:  connected
index.js:159 Imploding SIM group: 1673426517 811342999 2456002507
Logger.js:154 2020-03-20T11:43:02.406Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackAdded>:  TPC[1,p2p:false] remote track added: f61ba737-5134-44ba-bf11-2d772a1819a6-2 audio
Logger.js:154 2020-03-20T11:43:02.406Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackAdded>:  TPC[1,p2p:false] associated ssrc 1cd98b2c 289590294
Logger.js:154 2020-03-20T11:43:02.422Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackAdded>:  TPC[1,p2p:false] remote track added: f61ba737-5134-44ba-bf11-2d772a1819a6-2 video
Logger.js:154 2020-03-20T11:43:02.423Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackAdded>:  TPC[1,p2p:false] associated ssrc 1cd98b2c 1673426517
Logger.js:154 2020-03-20T11:43:02.438Z [modules/UI/videolayout/LargeVideoManager.js] hover in %s 1cd98b2c
Logger.js:154 2020-03-20T11:43:02.443Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackAdded>:  TPC[1,p2p:false] remote track added: f61ba737-5134-44ba-bf11-2d772a1819a6-2 video
Logger.js:154 2020-03-20T11:43:02.443Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackAdded>:  TPC[1,p2p:false] associated ssrc 1cd98b2c 1673426517
Logger.js:154 2020-03-20T11:43:02.443Z [modules/RTC/TraceablePeerConnection.js] <w._createRemoteTrack>:  TPC[1,p2p:false] ignored duplicated remote track added event for: 1cd98b2c, video
Logger.js:154 2020-03-20T11:43:02.782Z [modules/xmpp/SdpConsistency.js] <e.value>:  TPC[1,p2p:false] no SSRC found for the recvonly videostream!
JitsiRemoteTrack.js:212 (TIME) Render audio:	 34131.32500000211
JitsiRemoteTrack.js:231 (TIME) TTFM audio:	 1982.5149999996938
Logger.js:154 2020-03-20T11:43:02.805Z [modules/xmpp/JingleSessionPC.js] addRemoteStream - OK, SDPs:  o {media: Array(3), raw: "v=0
↵o=- 976298645913287911 2 IN IP4 127.0.0.1
↵s=…trickle
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", session: "v=0
↵o=- 976298645913287911 2 IN IP4 127.0.0.1
↵s=…0-6bf0e6181b6d
↵a=group:BUNDLE audio video data
↵"} o {media: Array(3), raw: "v=0
↵o=- 976298645913287911 3 IN IP4 127.0.0.1
↵s=…trickle
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", session: "v=0
↵o=- 976298645913287911 3 IN IP4 127.0.0.1
↵s=…0-6bf0e6181b6d
↵a=group:BUNDLE audio video data
↵"}
Logger.js:154 2020-03-20T11:43:02.807Z [modules/xmpp/JingleSessionPC.js] <t.value>:  removal not necessary
Logger.js:154 2020-03-20T11:43:02.808Z [modules/xmpp/JingleSessionPC.js] <t.value>:  addition not necessary
Logger.js:154 2020-03-20T11:43:02.810Z [modules/statistics/RTPStatsCollector.js] <f.processAudioLevelReport>:  289590294 not enough data
o @ Logger.js:154
f.processAudioLevelReport @ RTPStatsCollector.js:918
(anonymous) @ RTPStatsCollector.js:329
Logger.js:154 2020-03-20T11:43:02.810Z [modules/statistics/RTPStatsCollector.js] <f.processAudioLevelReport>:  1673426517 not enough data
o @ Logger.js:154
f.processAudioLevelReport @ RTPStatsCollector.js:918
(anonymous) @ RTPStatsCollector.js:329
Logger.js:154 2020-03-20T11:43:10.874Z [modules/UI/videolayout/RemoteVideo.js] <_.removeRemoteStreamElement>:  Audio removed 1cd98b2c k.fn.init [audio#remoteAudio_f61ba737-5134-44ba-bf11-2d772a1819a6-2]
Logger.js:154 2020-03-20T11:43:10.886Z [modules/UI/videolayout/RemoteVideo.js] <_.removeRemoteStreamElement>:  Video removed 1cd98b2c k.fn.init [video#remoteVideo_f61ba737-5134-44ba-bf11-2d772a1819a6-2]
Logger.js:154 2020-03-20T11:43:10.904Z [modules/UI/videolayout/VideoLayout.js] <Object.removeParticipantContainer>:  Removing remote video: 1cd98b2c
Logger.js:154 2020-03-20T11:43:10.905Z [modules/UI/videolayout/SmallVideo.js] <_.w.remove>:  Remove thumbnail 1cd98b2c
Logger.js:154 2020-03-20T11:43:10.928Z [modules/RTC/BridgeChannel.js] <e.value>:  sending selected changed notification to the bridge for endpoints ["ea7e0d96"]
Logger.js:154 2020-03-20T11:43:10.929Z [conference.js] <c.<anonymous>>:  USER 1cd98b2c LEFT: e {_jid: "test2@conference.jitsi.company.tld/1cd98b2c", _id: "1cd98b2c", _conference: ee, _displayName: "Dennis", _supportsDTMF: false, …}
Logger.js:154 2020-03-20T11:43:10.931Z [modules/xmpp/moderator.js] <d.onMucMemberLeft>:  Someone left is it focus ? test2@conference.jitsi.company.tld/1cd98b2c
Logger.js:154 2020-03-20T11:43:10.937Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onmessage>:  Channel new last-n event:  [] {colibriClass: "LastNEndpointsChangeEvent", lastNEndpoints: Array(0), endpointsEnteringLastN: Array(0), conferenceEndpoints: Array(0)}
Logger.js:154 2020-03-20T11:43:10.958Z [modules/RTC/BridgeChannel.js] <RTCDataChannel.e.onmessage>:  SelectedUpdateEvent isSelected? true
Logger.js:154 2020-03-20T11:43:10.969Z [modules/xmpp/strophe.jingle.js] <s.value>:  on jingle source-remove from test2@conference.jitsi.company.tld/focus <iq xmlns=​"jabber:​client" type=​"set" to=​"ea7e0d96-7fad-4278-8546-52b352d63b33@guest.jitsi.company.tld/​d13f47d1-62e2-4e81-9f8c-2d2d74739d40" from=​"test2@conference.jitsi.company.tld/​focus" id=​"ZWE3ZTBkOTYtN2ZhZC00Mjc4LTg1NDYtNTJiMzUyZDYzYjMzQGd1ZXN0LmppdHNpLmhmZy1vZmZlbmJhY2guZGUvZDEzZjQ3ZDEtNjJlMi00ZTgxLTlmOGMtMmQyZDc0NzM5ZDQwAFZGTGZzLTU2NTEAVFMwBnJCXH5fluB506lQdg==">​…​</iq>​
Logger.js:154 2020-03-20T11:43:10.974Z [modules/xmpp/JingleSessionPC.js] Processing removeRemoteStream
Logger.js:154 2020-03-20T11:43:10.974Z [modules/xmpp/JingleSessionPC.js] ICE connection state:  connected
index.js:146 Halt: There are no SSRC groups in the remote description.
Logger.js:154 2020-03-20T11:43:10.985Z [modules/connectivity/ParticipantConnectionStatus.js] <e.value>:  No participant for id: 1cd98b2c
o @ Logger.js:154
value @ ParticipantConnectionStatus.js:802
c.emit @ events.js:146
value @ JitsiRemoteTrack.js:117
(anonymous) @ JitsiRemoteTrack.js:100
Logger.js:154 2020-03-20T11:43:10.989Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackRemoved>:  TPC[1,p2p:false] - remote track removed: f61ba737-5134-44ba-bf11-2d772a1819a6-2, FD72A542-FD84-4891-AABA-6ADBB685E420-2
Logger.js:154 2020-03-20T11:43:10.989Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackRemoved>:  TPC[1,p2p:false] Removed track not found for msid: f61ba737-5134-44ba-bf11-2d772a1819a6-2,
             track id: FD72A542-FD84-4891-AABA-6ADBB685E420-2
o @ Logger.js:154
w._remoteTrackRemoved @ TraceablePeerConnection.js:874
e.onremovetrack @ TraceablePeerConnection.js:621
Logger.js:154 2020-03-20T11:43:10.989Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackRemoved>:  TPC[1,p2p:false] - remote track removed: f61ba737-5134-44ba-bf11-2d772a1819a6-2, E198ED0B-BB80-4B92-A430-68E42BF4520E-2
Logger.js:154 2020-03-20T11:43:10.990Z [modules/RTC/TraceablePeerConnection.js] <w._remoteTrackRemoved>:  TPC[1,p2p:false] Removed track not found for msid: f61ba737-5134-44ba-bf11-2d772a1819a6-2,
             track id: E198ED0B-BB80-4B92-A430-68E42BF4520E-2
o @ Logger.js:154
w._remoteTrackRemoved @ TraceablePeerConnection.js:874
e.onremovetrack @ TraceablePeerConnection.js:621
JitsiRemoteTrack.js:212 (TIME) Render video:	 42337.96000000075
JitsiRemoteTrack.js:231 (TIME) TTFM video:	 10189.149999998335
Logger.js:154 2020-03-20T11:43:11.010Z [modules/xmpp/SdpConsistency.js] <e.value>:  TPC[1,p2p:false] no SSRC found for the recvonly videostream!
Logger.js:154 2020-03-20T11:43:11.020Z [modules/xmpp/JingleSessionPC.js] removeRemoteStream - OK, SDPs:  o {media: Array(3), raw: "v=0
↵o=- 976298645913287911 3 IN IP4 127.0.0.1
↵s=…trickle
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", session: "v=0
↵o=- 976298645913287911 3 IN IP4 127.0.0.1
↵s=…0-6bf0e6181b6d
↵a=group:BUNDLE audio video data
↵"} o {media: Array(3), raw: "v=0
↵o=- 976298645913287911 4 IN IP4 127.0.0.1
↵s=…trickle
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", session: "v=0
↵o=- 976298645913287911 4 IN IP4 127.0.0.1
↵s=…0-6bf0e6181b6d
↵a=group:BUNDLE audio video data
↵"}
Logger.js:154 2020-03-20T11:43:11.021Z [modules/xmpp/JingleSessionPC.js] <t.value>:  removal not necessary
Logger.js:154 2020-03-20T11:43:11.022Z [modules/xmpp/JingleSessionPC.js] <t.value>:  addition not necessary
Logger.js:154 2020-03-20T11:43:11.232Z [modules/UI/videolayout/LargeVideoManager.js] hover in %s ea7e0d96
`

This is joining and leving the conference room with a mobile device via iOS App.

**Comment by Shaddowpain** [comment]
Any idea whats wrong?
I cant find a problem wich makes a cloue to me.

**Comment by saghul** [comment]
Sorry, I'm out of ideas. I suspect a network related problem, but it's hard to tell...

**Comment by Shaddowpain** [comment]
No worries. I think youre right. Ive changed my network setup without stateful NAT and it's working like a charm.

Thank you for your assist!
