### ISSUE TITLE
Allow Jitsi to be installed as a PWA

### ISSUE THREAD

**Issue by MrEbbinghaus** [jitsi/jitsi-meet#5275]
**feature request:**
Let me install Jitsi as a PWA:
There are numerous reason for this. 
For myself I just want to have Jitsi run "seperate" from Chrome itself, so I can Alt+Tab to it faster. 

A web manifest should be enough, without any other code changes. 
https://web.dev/add-manifest/

These PWAs would have to be installed for each server you are using, but I think that most of the users don't use more than one anyway

Thank you

**Comment by tyler71** [comment]
> For myself I just want to have Jitsi run "seperate" from Chrome itself, so I can Alt+Tab to it faster.

As a workaround, you can run it like this  
`chromium-browser --app=https://meet.jit.si/`

Should be the same for chrome

**Comment by MrEbbinghaus** [comment]
Or in Chromium
More tools -> Create Shortcut -> in new window
