### ISSUE TITLE
problème enregistrement

### ISSUE THREAD

**Issue by benoued** [jitsi/jitsi-meet#5278]
bonjour,
lorsque je veux enregistrer ma session video avec mes élèves j'ai le message suivant :
"tous les enregistreurs sont occupés"

**Comment by benoued** [comment]
bonjour,
quand je veux enregistrer ma session vidéo avec mes élèves j'ai le message suivant:
"tous les enregistreurs sont occupés"

**Comment by saghul** [comment]
We are working to fix this.
