### ISSUE TITLE
placeholder="user@domain.net" is confusing

### ISSUE THREAD

**Issue by ulab** [jitsi/jitsi-meet#5280]
## Description

After enabling LDAP authentication we had multiple people who tried to enter their full email address as username since the login popup asks them for `user@domain.net` while they need to just enter their username.

## Current behavior

`placeholder="user@domain.net"`

## Expected Behavior

`placeholder="username"` - probably internationalized as "Benutzername" in German, since you also ask for "Benutzerpasswort"

## Possible Solution

Fix the placeholder to a more generic value

## Steps to reproduce

Enable authentication and create a room.

# Environment details

Debian 10, Jitsi debian package 1.0.4101-1, Firefox 74.0 on MacOS.

**Comment by saghul** [comment]
When using XMPP authentication with more than one host, however, the domain must be specifiedd. I don't think there is a one-size-fits-all placeholder. The UI does not know  what auth type is used either.

**Comment by ulab** [comment]
I feel that just "Username" or "User identity" is more generic, since it could be either? 

But if you suggest something that looks like an email address, people will always try to enter that.

I don't know the code much, but searching the repository for `"user@domain.net"` I get two results. [One of them](https://github.com/jitsi/jitsi-meet/blob/f6d3ca23a54b600421dbae66277a32a1975d23be/modules/UI/authentication/LoginDialog.js#L13)  seems to make a difference by switching between `user identity` and `user@domain.net` depending on wether `config.hosts.authdomain` is set?

```
    const placeholder = config.hosts.authdomain
        ? 'user identity'
        : 'user@domain.net';
```
Since `authdomain` defaults to `config.hosts.domain`, the first choice will never hit, will it?

**Comment by SignoreMic** [comment]
Same problem here!

**Comment by RyanColp** [comment]
Same issue here.  I set up LDAP authentication on my server, and the current placeholder confuses my users too.

It would be useful if the placeholder could be customised, perhaps with the addition of a new setting in interface_config.js.

**Comment by slackluis** [comment]
Same problem here! 
It would be useful if the placeholder could be customized.

**Comment by ovailleau** [comment]
Hi !
Same problem for me. I'm using ldap with ActiveDiectory and "sAMAccountname".
Users have to enter their short login (not login@domain). The placeholder text is a little bit confusing !
Until I can't customize thi stext, I cannot deploy Jitsi-meet into my organisation.

It would be useful if the placeholder could be customized.
Thanks a lot

**Comment by SignoreMic** [comment]
Dear all,
I had found user@ddoamin.net in the file app.bundle.min.js and customized it with "Username".
Works for me, but I'm not sure it is the best way to do it. 
Saluti

**Comment by RyanColp** [comment]
Thanks SignoreMic.

Editing app.bundle.min.js worked for me as well, and seems to be a good temporary workaround.  Be prepared to redo the customization though, as app.bundle.min.js will probably be overwritten by upgrades.

**Comment by webslider** [comment]
Hi there !
For those who don't want to edit app.bundle.min.js, here is a workaround using MutationObserver that I've put in my /usr/share/jitsi-meet/plugin.head.html :
```
<script>
var observer = new MutationObserver(function (mutations, me) {
  if(!window.APP.conference.isJoined()){
    var canvas = $('input[name ="username"]').length;
        if (canvas) {
          $('input[name ="username"]').attr('placeholder', 'login');
          return;
        }
  }
  else {
    me.disconnect(); // we joined a conference, stop observing
  }
});

$(document).ready(function() {
  // start observing
  observer.observe(document, {
    childList: true,
    subtree: true
  });
});
</script>
```

**Comment by ovailleau** [comment]
It works like a charm.
I just replaced the text by "Compte Windows" (that's sound better in french) instead of 'login' at line 6.
Thanks a lot !

**Comment by freaky-m0** [comment]
Same problem here... our staff try to login with e-mail daily and then get stuck at "connecting..." is there a "better" way instead of customizing my html? That will get lost every time we update.

**Comment by ulab** [comment]
This seems to have been fixed. Placeholder is just "user" now?

**Comment by jfwiebe** [comment]
Hi. As @ulab correctly figured out, the code checks, if the authdomain variable is set and displays "user identity" instead of "user@domain.net".
https://github.com/jitsi/jitsi-meet/blob/f6d3ca23a54b600421dbae66277a32a1975d23be/modules/UI/authentication/LoginDialog.js#L13
`config.hosts.authdomain` points to your jitsi-meet config, which is typically located at `/etc/jitsi/meet/exampledomain.com-config.js`. Comment in the "authdomain" attribute on Line 15 and set it to the same value as "domain".

After commenting in that value, "user@domain.net" not not shown anymore, instead it only shows "user".
![grafik](https://user-images.githubusercontent.com/6865786/108606928-7e4e3580-73bd-11eb-8550-4117e1f8918a.png)
I assume, that this is a bug and needs to be fixed. If anyone can reproduce it, I'll open another issue with this bug.

**Comment by core66** [comment]
how is it possible to prefill the Username and set the cursor to the Password field?

Can anyone help me?
