### ISSUE TITLE
Video conference Recorded

### ISSUE THREAD

**Issue by Renato1963** [jitsi/jitsi-meet#5281]
When I try to start a recording I receive the following alert:
"All recorders are currently busy. We're working on freeing recording resources. Please try again in few minutes. Contact Support".
I have tried some times in the last hour but the alert persist.
I'm trying to record a video lesson to send it to my students that cannot connect online.
Thank you in advance for your support.
Kind Regards
Renato Picarazzi

**Comment by saghul** [comment]
We are working to fix this.
