### ISSUE TITLE
startWithVideoMuted = no video on webclient tile-view anymore

### ISSUE THREAD

**Issue by demlak** [jitsi/jitsi-meet#5283]
Hey.. we want audio and video be muted on start. and because we don't want to do so on every channel-setting seperated, we tried to use the settings in config.js

we tried `startWithVideoMuted: true,` and it has a strange behaviour on webclient tile-view:
all participants join muted as aspected. But when the moderator enables his cam, all others can see this cam only in "focus-view", but not in tile-view.
tested on chromium and firefox

and btw. the setting has no effect at all (no muting) for dedicated clients like jitsi-meet-bin on archlinux

btw.. posting this issue in the docker repo is correct?

**Comment by saghul** [comment]
Moved the issue over to Jitsi Meet. @jallamsetty1 can you PTAL?



> and btw. the setting has no effect at all (no muting) for dedicated clients like jitsi-meet-bin on archlinux

I don't know what that client is. If it's a repacckage of our Electron client, it may have bugs in those specific settings, as there are local toggles to override them.

**Comment by jallamsetty1** [comment]
Hi there ! I am not able to reproduce the issue with the latest Jitsi Meet web client. Can you please confirm if you using the latest as well ?

**Comment by demlak** [comment]
after several new installations i think it was/is caching-problem. sometimes it happens.. sometimes not.
i think, this can be closed until i will write a reproducable scenario. sorry.
