### ISSUE TITLE
Problem with live stream on youtube

### ISSUE THREAD

**Issue by BixBitIT** [jitsi/jitsi-meet#5285]
Hi,
I have two problems with live stream on YouTube:
1 - I can't do Sign Up with Google Account, it tried to connect but then get me an error.
2 - I can't start the live stream with the youtube stream key, it said me:
All streamers are currently busy
We're working on freeing streaming resources. Please try again in a few minutes.

What can we do it?

Thanks a lot!
Carlo

**Comment by damencho** [comment]
We are working on fixing this.

**Comment by adicatur** [comment]
Hi @damencho 

Thanks for working on this, can we know when it will be fixed?
