### ISSUE TITLE
Installed with quick install instructions - can only get black screen when connected

### ISSUE THREAD

**Issue by techjunkie64** [jitsi/jitsi-meet#529]
when i connect to our server running jitsi meet i can get to main page then type in a meet and i go to a black page with some controls but nothing works - i also have apache installed and had to switch ports in nginx to use 8084 and 4443 - i see it is up and so is jicofo but i did not see a jvb -jitsi videobridge in the listing ports - i did a  ./jicofo.sh --domain=jitsi.example.com --secret=YOURSECRET2 --user_domain=auth.jitsi.example.com --user_name=focus --user_password=YOURSECRET3
and it looks like it started.

**Comment by Armin-Smailzade** [comment]
I have the same problem. Did you find any solution ?

**Comment by techjunkie64** [comment]
i wiped my server and made sure its 14.04 LTS then quick install worked flawless

 
Robert Yeakley
Prince Law Offices P.C.
646 Lenape Road
Bechtelsville, PA. 19505-9135
(610)-845-3803 x 81109
ryeakley@princelaw.com

**Comment by Armin-Smailzade** [comment]
I am using Ubuntu also. But still not working. I am getting this error on server log : JVB 2016-03-30 20:50:51.697 SEVERE: [20] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347

I have followed the instruction as it is. But not sure how to resolve this error.

**Comment by techjunkie64** [comment]
ok first what version are you running  of ubuntu 14.04 - 15.04 15.10 or desktop or server  it makes a difference and what else do you have installed makes a difference - 



Robert Yeakley
Prince Law Offices, PC
646 Lenape Road
Bechtelsville, PA. 19505-9135
610-845-3803 x 81109
ryeakley@princelaw.com

**Comment by Armin-Smailzade** [comment]
I wiped the Debian server and installed a 64 bit Ubuntu 14.04 LTS desktop. Then followed the quick install. I haven't installed anything else.

**Comment by techjunkie64** [comment]
ok great  now when you installed the jitsi what did you use for host name  if you try anything else but hostname you used you will get only black screen - we used a pingable external address and had open ports 10000 - 20000 and 80 and 443  now to check if nginx is running ok go to browser and type in ip address of server and you should get a welcome to nginx  screen if not wipe and try again it took me 3 times before i found out all the little issues while installing 



Robert Yeakley
Prince Law Offices P.C.
646 Lenape Road
Bechtelsville, PA. 19505-9135
(610)-845-3803 x 81109
ryeakley@princelaw.com

**Comment by techjunkie64** [comment]
here are some pointers for you 
1.the name you use is important  you need to be able to ping both ip and dns address- whether you use internally or externally 

ex: when installing i use my.jitsi-server.com <http://my.jitsi-server.com/>  and the ip address in internal like 192.168.0.250  i must be able to ping both ip and name  and when accessing jitsi -  i need to use https://my.jitsi-server.com <https://my.jitsi-server.com/>  not ip - ip should take me to nginx  http://192.168.0.250 <http://192.168.0.250/> - now to reach externally i need to use a external ip address on server or set up external dns pointing to my-jitsi-server.com <http://my-jitsi-server.com/>  and remember to open ports 10000 - at least 20000 and 80 and 443  and look at manual install there is some lines you need to add to .sip-communicator.properties files if behind a NAT  — hope that helps 






  
Robert Yeakley
Prince Law Offices P.C.
646 Lenape Road
Bechtelsville, PA. 19505-9135
(610)-845-3803 x 81109
ryeakley@princelaw.com

**Comment by Armin-Smailzade** [comment]
Thank you so much for you suggestions.
I used my local host as the hostname. I was able to get to the nginx page. then I went to https://localhost and it went to the jitsi page to enter a room name. after entering the room name it went to the conference room but it was only black screen with some control buttons and anyone else who joins the room gets the same black screen with some control buttons. 

I have not setup a DNS yet so I guess that might be the problem. But even without DNS shouldn't it get local user's camera and display it since the javascript is using getUserMedia() ?

**Comment by phoenixsampras** [comment]
Same problem here, in LAN (local network), I'm getting a BLACK screen... no video, all ports open.

**Comment by nhtdata** [comment]
same problem. any solution team, black screen, is fake ?

**Comment by nhtdata** [comment]
dear team, any feedback 
  36  apt-get -y install jitsi-meet
   37  apt-get -y install jigasi

Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phoenixsampras** [comment]
Jitsi unstable, unusable, as far as we know, in Ubuntu 15 LTS

**Comment by isazayed** [comment]
i am using ubuntu 16.04 its with fresh installation internet is working fine local network is working fine 
after quick installing jisti-meet server
nginx web server is working fine......https://192.168.3.133 jisti-meet server working fine....
when i enter the room name..........no camera just black screen.........plz urgent help....

**Comment by phlegx** [comment]
For me it happens the same with ubuntu 16.04 and also ubuntu 14.04 when testing it locally

An error that I get is also the following

```
JVB 2016-09-30 09:16:50.919 SEVERE: [17] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347 org.xmpp.component.ComponentException: host-unknown
``` 
However all ports are open.

**Comment by williammahecha** [comment]
Greetings. I have installed Jitsi Meet following the instructions in https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md, in Debian 8 Jessie - default jre 7  and in Ubuntu 14.04 - jre8 oracle. Ubuntu 14.04 has firewall disabled by default.

When I create a room using Chrome or Firefox, I get a black screen, the camera, microphone, hangout buttons don´t work. I can't even watch my own video. 
When I click the invite button, it always says creating room. There could be something missing in the guide or in the package.

**Comment by s1341** [comment]
I was also getting a black screen. I checked the js console and saw that I was getting 404s from `https://myserver/http-bind?room=test`. I added the following to my `/etc/prosody/conf.d/myserver.cfg.lua` under the myserver VirtualHost:
```
http_host = myserver
```
And now I no longer get the http-bind 404.

Now when I try to go to a room (e.g. `https://myserver/test`) I get an error: "Oops! Something went wrong and we couldn't connect to the conference: connection.otherError".

In the js console I see the following:
```
[modules/xmpp/xmpp.js] <e.value>:  Lip-sync enabled !
Logger.js:89 [modules/xmpp/xmpp.js] <e.value>:  (TIME) Strophe connecting:	 675.845
Logger.js:89 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}message: "Could not establish connection. Receiving end does not exist."__proto__: Objectr @ Logger.js:89(anonymous function) @ ScreenObtainer.js:385sendResponseAndClearCallback @ extensions::messaging:359disconnectListener @ extensions::messaging:377target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:388target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:149EventImpl.dispatch_ @ extensions::event_bindings:372EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:149dispatchOnDisconnect @ extensions::messaging:320
Logger.js:89 [modules/RTC/ScreenObtainer.js] <>:  Chrome extension installed: false updateRequired: false
Logger.js:89 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: BOSH-Connection failed: host-unknown(…)r @ Logger.js:89getGlobalOnErrorHandler @ JitsiMeetJS.js:332window.onerror @ conference.js:549callErrorHandler @ GlobalOnErrorHandler.js:65Strophe.log @ strophe.util.js:29error @ strophe.js:1560_connect_cb @ strophe.js:4462_connect_cb @ strophe.js:3177_onRequestStateChange @ strophe.js:4729
Logger.js:89 [modules/xmpp/strophe.util.js] <Object.Strophe.log>:  Strophe: BOSH-Connection failed: host-unknownr @ Logger.js:89Strophe.log @ strophe.util.js:30error @ strophe.js:1560_connect_cb @ strophe.js:4462_connect_cb @ strophe.js:3177_onRequestStateChange @ strophe.js:4729
Logger.js:89 [modules/xmpp/xmpp.js] <e.value>:  (TIME) Strophe connfail[host-unknown]:	 758.4250000000001
Logger.js:89 [modules/xmpp/xmpp.js] <e.value>:  (TIME) Strophe disconnected[host-unknown]:	 760.5600000000001
connection.js:86 CONNECTION FAILED: connection.otherErroru @ connection.js:86n.emit @ events.js:96value @ xmpp.js:155_changeConnectStatus @ strophe.js:2973_doDisconnect @ strophe.js:3015_connect_cb @ strophe.js:4472_connect_cb @ strophe.js:3177_onRequestStateChange @ strophe.js:4729
app.js:124 connection.otherError(anonymous function) @ app.js:124
Logger.js:89 [modules/RTC/RTCUtils.js] <>:  onUserMediaSuccess
```
I looked in the prosody logs (`/var/log/prosody/prosody.log`) and I see the following output every few seconds:
```
Nov 17 11:50:30 jcp1e93970	info	Incoming Jabber component connection
Nov 17 11:50:30 mod_component	info	Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>jitsi-videobridge.myserver does not match any configured external components</text></stream:error>
Nov 17 11:50:30 jcp1e93970	info	component disconnected: nil (false)
Nov 17 11:50:35 jcp237da60	info	Incoming Jabber component connection
Nov 17 11:50:35 mod_component	info	Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>jitsi-videobridge.myserver does not match any configured external components</text></stream:error>
Nov 17 11:50:35 jcp237da60	info	component disconnected: nil (false)
```
Also, the jvb log (`/var/log/jitsi/jvb.log`) has the following every few seconds:
```
JVB 2016-11-17 11:42:00.543 SEVERE: [16] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Can anyone help me get jitsi meet working?

**Comment by damencho** [comment]
So I don't think this setting is needed: "http_host = myserver". In your deployment you have several problems not sure how you got those, did you edit the files or you came to this with just doing apt-get install ...?
1. Your bosh is not properly configured. The configuration is in nginx, to pass it to prosody. Check that you have this exact config in your nginx:
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L43
And you have bosh enabled for your virtual host:
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L21
2. Check that you have configured jitsi-videobridge component in your prosody config:
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L30
If you have this maybe your config is not included from the main prosody config? Does the main prosody config /etc/prosody/prosody.cfg.lua has Include "conf.d/*.cfg.lua".

**Comment by s1341** [comment]
@damencho I tried with the quick install. I verified that everything looks like the config files you mentioned, but I'm still seeing the 'oops' message, and am getting this in the `/var/log/prosody/prosody.log`:
```
Nov 20 08:56:57 jcp2637460	info	Incoming Jabber component connection
Nov 20 08:56:57 mod_component	info	Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>focus.GNU-1207-SHMARYAR does not match any configured external components</text></stream:error>
Nov 20 08:56:57 jcp2637460	info	component disconnected: nil (false)
```
And the following in `/var/log/jitsi/jvb.log`:
```
JVB 2016-11-20 08:57:26.012 SEVERE: [16] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
And this in `/var/log/jitsi/jicofo.log`:
```
Jicofo 2016-11-20 08:58:02.087 SEVERE: [30] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Jicofo 2016-11-20 08:58:02.230 WARNING: [17] org.jivesoftware.smack.filter.IQReplyFilter.accept() Rejected potentially spoofed reply to IQ-packet. Filter settings: packetId=mo69I-21, to=myserver, local=focus@auth.myserver/focus571102389740986, server=auth.gnu-1207-shmaryar. Received packet with from=myserver
````
Any ideas how I can fix this?

**Comment by damencho** [comment]
For some reason when trying to connect the components, prosody doesn't know about them. Did you saw the "conf.d/*.cfg.lua" in your prosody config? Did you try restarting prosody?
The component domain for jvb is "JVB_HOSTNAME=jitmeet.example.com" from /etc/jitsi/videobridge/config and in /etc/prosody/conf.d/jitmeet.example.com.cfg.lua you should have Component "jitsi-videobridge.jitmeet.example.com".
Check prosody logs for some errors on restarting it.

**Comment by s1341** [comment]
My prosody.cfg.lua has the "Include conf.d/*.cfg.lua" line.

This is the output from start of prosody, with logging set to 'debug' level:
```
Nov 22 11:06:15 general	info	Hello and welcome to Prosody version 0.9.8
Nov 22 11:06:15 general	info	Prosody is using the select backend for connection handling
Nov 22 11:06:15 hostmanager	debug	Activated host: focus.gnu-1207-shmaryar
Nov 22 11:06:15 portmanager	debug	No active service for component, activating...
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[127.0.0.1]:5347'
Nov 22 11:06:15 portmanager	debug	Added listening service component to [127.0.0.1]:5347
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[::1]:5347'
Nov 22 11:06:15 portmanager	debug	Added listening service component to [::1]:5347
Nov 22 11:06:15 portmanager	info	Activated service 'component' on [127.0.0.1]:5347, [::1]:5347
Nov 22 11:06:15 portmanager	debug	No active service for s2s, activating...
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[::]:5269'
Nov 22 11:06:15 portmanager	debug	Added listening service s2s to [::]:5269
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[*]:5269'
Nov 22 11:06:15 portmanager	debug	Added listening service s2s to [*]:5269
Nov 22 11:06:15 portmanager	info	Activated service 's2s' on [::]:5269, [*]:5269
Nov 22 11:06:15 hostmanager	debug	Activated host: jitsi-videobridge.gnu-1207-shmaryar
Nov 22 11:06:15 hostmanager	debug	Activated host: localhost
Nov 22 11:06:15 localhost:auth_internal_plain	debug	initializing internal_plain authentication provider for host 'localhost'
Nov 22 11:06:15 usermanager	debug	host 'localhost' now set to use user provider 'internal_plain'
Nov 22 11:06:15 portmanager	debug	No active service for c2s, activating...
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[::]:5222'
Nov 22 11:06:15 portmanager	debug	Added listening service c2s to [::]:5222
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[*]:5222'
Nov 22 11:06:15 portmanager	debug	Added listening service c2s to [*]:5222
Nov 22 11:06:15 portmanager	info	Activated service 'c2s' on [::]:5222, [*]:5222
Nov 22 11:06:15 portmanager	debug	No active service for legacy_ssl, activating...
Nov 22 11:06:15 portmanager	info	Activated service 'legacy_ssl' on no ports
Nov 22 11:06:15 mod_posix	info	Prosody is about to detach from the console, disabling further console output
Nov 22 11:06:15 mod_posix	info	Successfully daemonized to PID 9026
Nov 22 11:06:15 hostmanager	debug	Activated host: conference.gnu-1207-shmaryar
Nov 22 11:06:15 datamanager	debug	Assuming empty persistent storage ('cannot open /var/lib/prosody/conference%2egnu%2d1207%2dshmaryar/persistent.dat: No such file or directory') for user: nil@conference.gnu-1207-shmaryar
Nov 22 11:06:15 hostmanager	debug	Activated host: gnu-1207-shmaryar
Nov 22 11:06:15 usermanager	debug	host 'gnu-1207-shmaryar' now set to use user provider 'anonymous'
Nov 22 11:06:15 portmanager	debug	No active service for http, activating...
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[::]:5280'
Nov 22 11:06:15 portmanager	debug	Added listening service http to [::]:5280
Nov 22 11:06:15 socket	debug	server.lua: new server listener on '[*]:5280'
Nov 22 11:06:15 portmanager	debug	Added listening service http to [*]:5280
Nov 22 11:06:15 portmanager	info	Activated service 'http' on [::]:5280, [*]:5280
Nov 22 11:06:15 portmanager	debug	No active service for https, activating...
Nov 22 11:06:15 socket	debug	server.lua: new ssl server listener on '[::]:5281'
Nov 22 11:06:15 portmanager	debug	Added listening service https to [::]:5281
Nov 22 11:06:15 socket	debug	server.lua: new ssl server listener on '[*]:5281'
Nov 22 11:06:15 portmanager	debug	Added listening service https to [*]:5281
Nov 22 11:06:15 portmanager	info	Activated service 'https' on [::]:5281, [*]:5281
Nov 22 11:06:15 gnu-1207-shmaryar:http	debug	Serving 'bosh' at https://gnu-1207-shmaryar:5281/http-bind
Nov 22 11:06:15 hostmanager	debug	Activated host: auth.gnu-1207-shmaryar
Nov 22 11:06:15 auth.gnu-1207-shmaryar:auth_internal_plain	debug	initializing internal_plain authentication provider for host 'auth.gnu-1207-shmaryar'
Nov 22 11:06:15 usermanager	debug	host 'auth.gnu-1207-shmaryar' now set to use user provider 'internal_plain'
Nov 22 11:06:18 socket	debug	server.lua: accepted new client connection from 127.0.0.1:56476 to 5347
Nov 22 11:06:18 jcp18b7c00	info	Incoming Jabber component connection
Nov 22 11:06:18 mod_component	info	Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>jitsi-videobridge.GNU-1207-SHMARYAR does not match any configured external components</text></stream:error>
Nov 22 11:06:18 jcp18b7c00	info	component disconnected: nil (false)
Nov 22 11:06:18 socket	debug	server.lua: closed client handler and removed socket from list
Nov 22 11:06:18 socket	debug	server.lua: accepted new client connection from 127.0.0.1:56478 to 5347
Nov 22 11:06:18 jcp18c1310	info	Incoming Jabber component connection
Nov 22 11:06:18 mod_component	info	Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>focus.GNU-1207-SHMARYAR does not match any configured external components</text></stream:error>
Nov 22 11:06:18 jcp18c1310	info	component disconnected: nil (false)
Nov 22 11:06:18 socket	debug	server.lua: closed client handler and removed socket from list
```
Component for jitsi-videobridge and focus are set in my GNU-1207-SHMARYAR.cfg.lua

JVB_HOSTNAME is set correctly.

**Comment by damencho** [comment]
The problem here is your capital case. jitsi-videobridge.gnu-1207-shmaryar is not equals jitsi-videobridge.GNU-1207-SHMARYAR. You should fix that.
Use small caps, as you would normally do for dns names. When configuring the packages they as for service name, as the dns name you will add as meet.jit.si.
You need to edit all jicofo and jvb files by hand or purge all the packages and install on clean.

**Comment by damencho** [comment]
I will close this issue as it contains several different problems from different people. Black screen is normally a configuration issue where the webapp is not able to join the room or the deployment is missing the focus (jicofo is not connected for some reason). 
If you have such a problem and seek for help, as always write to the mailinglist before opening an issue.

**Comment by s1341** [comment]
@damencho fixing the case solved the issue.

**Comment by damencho** [comment]
Glad it worked. :)
