### ISSUE TITLE
`install-letsencrypt-cert.sh` ignores Prosody certificates

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#5292]
Using the DebianBuster/stable  package jitsi-Meet-web 1.0.3895-1, it looks like when installing the Let’s Encrypt certificates with https://github.com/jitsi/jitsi-meet/blob/master/resources/install-letsencrypt-cert.sh, the Prosody certificates are not updated.

`/etc/prosody/conf.avail/jitsi.molgen.mpg.de.cfg.lua` still contains the settings below.

        ssl = {
                key = "/etc/prosody/certs/jitsi.molgen.mpg.de.key";
                certificate = "/etc/prosody/certs/jitsi.molgen.mpg.de.crt";
        }

The 

```
$ sudo ls -l /etc/prosody/certs/
total 0
lrwxrwxrwx 1 root root 45 Mar 18 14:38 auth.jitsi.molgen.mpg.de.crt -> /var/lib/prosody/auth.jitsi.molgen.mpg.de.crt
lrwxrwxrwx 1 root root 45 Mar 18 14:38 auth.jitsi.molgen.mpg.de.key -> /var/lib/prosody/auth.jitsi.molgen.mpg.de.key
lrwxrwxrwx 1 root root 40 Mar 18 14:38 jitsi.molgen.mpg.de.crt -> /var/lib/prosody/jitsi.molgen.mpg.de.crt
lrwxrwxrwx 1 root root 40 Mar 18 14:38 jitsi.molgen.mpg.de.key -> /var/lib/prosody/jitsi.molgen.mpg.de.key
lrwxrwxrwx 1 root root 37 Jan  9  2019 localhost.crt -> ../../ssl/certs/ssl-cert-snakeoil.pem
lrwxrwxrwx 1 root root 39 Jan  9  2019 localhost.key -> ../../ssl/private/ssl-cert-snakeoil.key
$ sudo ls -l /var/lib/prosody/
total 28
drwxr-x--- 4 prosody prosody 4096 Mar 18 14:38 auth%2ejitsi%2emolgen%2empg%2ede
-rw-r----- 1 prosody prosody  895 Mar 18 14:38 auth.jitsi.molgen.mpg.de.cnf
-rw-r----- 1 prosody prosody 1688 Mar 18 14:38 auth.jitsi.molgen.mpg.de.crt
-r-------- 1 prosody prosody 1675 Mar 18 14:38 auth.jitsi.molgen.mpg.de.key
-rw-r----- 1 prosody prosody 1679 Mar 18 14:38 jitsi.molgen.mpg.de.cnf
-rw-r----- 1 prosody prosody 2374 Mar 18 14:38 jitsi.molgen.mpg.de.crt
-r-------- 1 prosody prosody 1679 Mar 18 14:38 jitsi.molgen.mpg.de.key
```

I would expect that no self-signed certificates would be used here.

**Comment by house97** [comment]
Thank you for bringing this up.  I think that the order of operations should be updated so that the letsencrypt cert is created first, and then used by all installed components.  perhaps the reason it's not done this way is due to all the SAN entries in the prosody cert?  If you use openssl to decode the cert to text, you'll see what I mean:
openssl x509 -noout -text -in /var/lib/prosody/<your domain>.crt

However, whatever the requirements for the prosody cert are, wouldn't it be better to spell them out from the jump and have a cert created that includes them all?

**Comment by damencho** [comment]
The internal to the system certificates do not need to be valid certificates. So this is intentionally skipped. Anything other than webserver is not exposed to the Internet.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

**Comment by paulmenzel** [comment]
> The internal to the system certificates do not need to be valid certificates. So this is intentionally skipped.

Ah, I remember something like that. Thank you for clearing that up.

> Anything other than webserver is not exposed to the Internet.

The TURN server is exposed too on UDP:443, isn’t it?

**Comment by saghul** [comment]
No, Nginx fonts it.

**Comment by paulmenzel** [comment]
@saghul, what does “fonts it” mean?

Using the self-signed certificates with coturn caused certificate verification errors, when testing the connection with `openssl s_client -connect meet.example.net:443` for example.

**Comment by paulmenzel** [comment]
(The browser didn’t mind though.)

**Comment by saghul** [comment]
Sorry, bad keyboard. I meant "fronts". The next stable release uses Nginx to front HTTP and TURN traffic, so there is no extra cert.
