### ISSUE TITLE
Debian package configures coturn for port 443 and Nginx on 4444

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#5293]
Using Debian 10 Buster/stable with the packages *jitsi-meet* 1.0.4290-1, and *jitsi-meet-web* 1.0.3895-1, the package *[coturn](https://packages.debian.org/buster/coturn)* is configured to listen on port 443, and the Nginx Jitsi site configuration listens on port 4444.

This contradicts the diagram in https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md, where Nginx listens on port 443 for SSL traffic.

**Comment by damencho** [comment]
That page has a big warning on the top saying, it is most probably outdated.
