### ISSUE TITLE
Default coturn configuration shows error

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#5296]
The generated coturn configuration by the Debian package configuration script

    $ head -4 /etc/turnserver.conf
    # jitsi-meet coturn config. Do not modify this line
    lt-cred-mech
    use-auth-secret
    keep-address-family

gives the error below.

    CONFIGURATION ALERT: You specified --lt-cred-mech and --use-auth-secret in the same time.
    Be aware that you could not mix the username/password and the shared secret based auth methohds. 
    Shared secret overrides username/password based auth method. Check your configuration!

**Comment by damencho** [comment]
Interesting, thanks for the report. Which coturn version is this?

**Comment by paulmenzel** [comment]
Package coturn 4.5.1.1-1.1 from Debian Sid/unstable.

**Comment by Commifreak** [comment]
Is it possible to use Jitsi with only lt-cred-mech enabled? The manual states, that lt-cred-mech is needed for WebRTC to work properly. Firefox does not authenticate with current Jitsi config (static-auth) (see https://community.jitsi.org/t/turn-server-firefox-not-working-chome-is-ok/28826 and https://community.jitsi.org/t/firefox-coturn-ice-error-401-but-working-in-chrome/55420). Someone statet, that after enabling lt-cred-mech, Firefox started to work with coturn as well.
