### ISSUE TITLE
Ingreso y restricción.

### ISSUE THREAD

**Issue by tarjetasprof** [jitsi/jitsi-meet#5297]
Buenas tardes, 

   Recién he ingresado a Jitsi Meeting con una llamada de prueba a la que le puse Prueba 2. Me conectó con otras dos personas que no conocía y que también estaban haciendo una prueba con el nombre PRUEBA 2. Me dijeron que habían puesto una contraseña, pero a mí no me la pidió y pude entrar en diálogo con ellos. Por otro lado tampoco me veían. 
   Tampoco veo que el que inicia una conferencia pueda administrar al resto, silenciándolos para moderar una conversación. 
   Finalmente, al intentar transmitir en vivo me apareció un mensaje que decía: " todos los transmisores están actualmente ocupados."

    Espero que les sea de utilidad para mejorarlo.

**Comment by saghul** [comment]
> Recién he ingresado a Jitsi Meeting con una llamada de prueba a la que le puse Prueba 2. Me conectó con otras dos personas que no conocía y que también estaban haciendo una prueba con el nombre PRUEBA 2.

Esto es asi por disseño. Cualquier persona puede elegir un nombre para su sala, y cualquier otra persona se puede unir con saber el nombre, siempre y cuando no haya una contraseña.



> Me dijeron que habían puesto una contraseña, pero a mí no me la pidió y pude entrar en diálogo con ellos.

Puede que no lo hubieran hecho a tiempo.



> Tampoco veo que el que inicia una conferencia pueda administrar al resto, silenciándolos para moderar una conversación.

Es posible, haz click en los 3 puntos del cuadrado de un participante. Ess una moderacion "suave", ellos se puedden desmutear en cualquier momento.



> Finalmente, al intentar transmitir en vivo me apareció un mensaje que decía: " todos los transmisores están actualmente ocupados."

Estamoss trabajando para solucionar esto.
