### ISSUE TITLE
Option to show participants names and sort their videos in alphabetical order

### ISSUE THREAD

**Issue by misha-franz** [jitsi/jitsi-meet#5298]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

We are trying to use Jitsi for a game called Mafia.
There are 11 participants: 1 moderator and 10 players.
When players get numbers from 1 to 10 and take their seats around the table in that order.
More info: http://englishmafiaclub.com/how-to-play-mafia-by-classic-rules.html

**Describe the solution you'd like**
Please describe the desired behavior.

We believe the following would help:

Players change their names to include the number they received from the moderator, for example: 0  - Mike - Moderator, 1 - John, 2 - Bob, 3 - Amy... Jitsi does not have to manage names - participants will assign names themselves.

Jitsi always shows name on top of participants' video (in the corner).

Jitsi shows participants' videos in alphabetical order. Once participant changes the name Jitsi sorts videos again to maintain the order.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

Nothing else, just 2 options, show participants names, and sort alphabetically. These options do not have to be default. Each of the options can have a separate setting in the Jitsi UI to allow additional flexibility.

**Comment by gabrielmcf** [comment]
This is a feature tha would be very useful for our case. We do daily meetings using a on-premise install of jitsi and we speak in alphabetical order. It is a feature that exists em Google Hangout and is very helpful!

**Comment by jobe2015** [comment]
This would be very helpfull for us too. We are having daily meetings where the teacher needs to see the videos and names of all participants at the same time.

**Comment by crsepulv** [comment]
I think that see the names on each video is a must when there are more than 3-4 webcams

**Comment by marknovem** [comment]
This would be a very much helpful for us too. I agree with the above comments.

**Comment by alex-T-awesome** [comment]
Very useful for first-time meeting calls and live streams/recordings as well.

**Comment by mdell-seradex** [comment]
That is sad that this useful request was closed because it took too long to get to.

**Comment by slesru** [comment]
We use https://github.com/kaiyazeera/jitsi-bookmarklets  and works.
Unfortunately it does not longer work with 2.0.9364.
May be somebody knows java script and can update it?
Thank you!
