### ISSUE TITLE
Jitsi Meet - Android app from https://f-droid.org/de/packages/org.jitsi.meet/

### ISSUE THREAD

**Issue by cdr8H** [jitsi/jitsi-meet#5299]
<img width="401" alt="JitsiAndroid" src="https://user-images.githubusercontent.com/6630333/77221782-2bd11d00-6b4d-11ea-8046-e8d4420d90eb.png">

## Description
there is a translation failure in the german language strings: the menu displays "Kamera ein-/ausschalten" what means "Camera on/off" - but instead it toogles between front and back cam. This is behavior is very useful and should not be changed .... but the correct string would be for german "Front-/Rückkamera" or in englisch something like "front/rear camera" ....

# Environment details
Android Version 20.0.3 (200300)

**Comment by saghul** [comment]
Thanks, this should be fixed with the next update.

**Comment by lf-novelt** [comment]
Hello there is actually the same problem in French, the translation should be updated to `Changer de caméra`.

**Comment by fretman92** [comment]
Hello there is actually the same problem in French, the translation should be updated to `Changer de caméra`.
