### ISSUE TITLE
Webcam overlay while screen sharing

### ISSUE THREAD

**Issue by jondo** [jitsi/jitsi-meet#5302]
While sharing a window or the whole screen, the video of the speaker should be (optionally, but as default) visible as overlay.
(Zoom also does this.)

The clumsy workaround is to have the speaker's mobile phone as additional participant in the meeting.

This duplicates https://github.com/jitsi/jitsi-meet/issues/3038, which was closed as stale by a bot.

**Comment by damencho** [comment]
This is already available. Try sharing on meet.jit.si and turn on your camera.

**Comment by jondo** [comment]
Ah, great! I didn't discover it, because I didn't expect the camera to be turned off when sharing. So this is really only about a missing setting to let the camera stay turned on. I have filed https://github.com/jitsi/jitsi-meet/issues/5303 for this.
