### ISSUE TITLE
(Setting to) keep the camera turned on when sharing

### ISSUE THREAD

**Issue by jondo** [jitsi/jitsi-meet#5303]
While sharing a window or the whole screen, I would like my camera to stay switched on s.t. people continue seeing me.

Please change the default or add a setting for this behavior.

**Comment by w-vi** [comment]
I think you'd like to have this, correct? https://jitsi.org/news/introducing-presenter-mode/
If so all you need is to install from unstable branch.

**Comment by jondo** [comment]
Thank you, @w-vi , but I already know about presenter mode, I have discovered it on https://meet.jit.si/ . Here, I want to suggest that presenter mode should be active by default.
