### ISSUE TITLE
teacher or webinar mode

### ISSUE THREAD

**Issue by treble2019** [jitsi/jitsi-meet#5304]
**Is your feature request related to a problem you are facing?**

Would it be possible to some way implement a webinar/classroom mode? World is moving towards online-classroom. 

**Describe the solution you'd like**

It would great to have the first user or moderator have the video/audio controls. 

in the current situation, would be of great help instead of schools switching to closed source platforms.

**Describe alternatives you've considered**

The problem in editing  `/usr/share/jitsi-meet/interface_config.js ` to remove video/audio buttons does not solve this. If the  student (non moderator) uses android/iOS app, it shows 'audio, video' buttons. Causes lots of teaching disruptions: any help appreciated.

https://github.com/jitsi/jitsi-meet/issues/1675
https://github.com/jitsi/jitsi-meet/issues/1887

**Comment by saghul** [comment]
Sorry that is not a use-case we directly cover. Our moderation controls are "soft", you can mute a user, but they can unmute back and so on.
