### ISSUE TITLE
Mute a participant locally

### ISSUE THREAD

**Issue by horazont** [jitsi/jitsi-meet#5309]
**Is your feature request related to a problem you are facing?**
We use Jitsi Meet to deal with social distancing. In some cases, two people (let’s call them Alice and Bob) in a conference want to share the same room, but can’t share the same client device (I don’t want to bore you with the details).

In that case, if the microphone of Alice picks up Bobs voice too, and vice versa, both will hear each other via air and via Jitsi. The echo from jitsi is delayed and that’s annoying/confusing/distracting.

**Describe the solution you'd like**
There is already a volume slider per participant, but moving it all the way to the left does not completely mute the participant. There should exist a way to completely mute a participant either with a button or by moving the slider to zero.

**Describe alternatives you've considered**
- Splitting the rooms of Alice and Bob. That’s a workaround, but let’s for now assume that’s not possible.
- One of the two (Bob) could turn off his microphone and rely on his voice being picked up by Alice’. This has two downsides: His voice will be much quieter, and Jitsi will not attribute the audio to him, making the automatic speaker magnification quite useless.
- Having Bob and Alice mute themselves as needed.
- Use Push-to-Talk. Push-to-talk is all nice for meeting-type conferences, but for social gettogethers, having to push a button to have your spontaneous laugh be transmitted is suboptimal.

**Comment by saghul** [comment]
I thought the slider went all the way to 0, doesn't it @hristoterezov  ?

**Comment by robopossum** [comment]
I've found that the slider doesn't appear to work at all. It appears to make no effect on the participant's volume

**Comment by saghul** [comment]
@robopossum That's unexpected! What browser and version are you running?

**Comment by horazont** [comment]
@saghul I’ve seen the slider not doing anything or only having a small effect on

* Chromium Version 80.0.3987.132 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)
* Firefox Versoin 74.0 (64-bit) also on Debian bullseye/sid

with a very recent jitsi-meet:

```
root@jitsi:~# apt policy jitsi-meet
jitsi-meet:
  Installed: 1.0.4101-1
  Candidate: 1.0.4101-1
```

With a casual report supporting this with some browser on Windows, though I don’t know the exact versions. I can probably get those if that’s relevant.

**Comment by saghul** [comment]
Thankss for the report!

**Comment by horazont** [comment]
@saghul Shall I edit the description and should we maybe add a bug classification label to this then?

**Comment by saghul** [comment]
No need, I'd say it's ok. It may take us a bit to get to it since it's weird times now...

**Comment by robopossum** [comment]
I observed the following on Chrome 80.0.3987.149 (Official Build) (64-bit) on Windows 10.

The sliders worked in a one-to-one meeting when I tested. But in all the meetings with more than two participants it had no effect on the volume.

Oddly, when sliding it I could see that it was updating the volume property on the respective audio element.

**Comment by horazont** [comment]
I’m unable to reproduce this with recent jitsi meet and chromium. Seems that it fixed itself.
