### ISSUE TITLE
complete config-file is exposed on web client

### ISSUE THREAD

**Issue by demlak** [jitsi/jitsi-meet#5310]
In Browser take a look at the sourcecode of jitsi meet webclient.
You will see the complete config file incl. comments, keys, server credentials, maybe notes, etc.. etc..

**Comment by damencho** [comment]
What do you think is a problem?

Please if you have questions or problems use the community forum before opening new issues.

**Comment by demlak** [comment]
Exposure a complete config-file to the web, without warning to people, is not a problem for you?

**Comment by damencho** [comment]
Nope. There is no sensitive data in it. There is nothing you can get and use it ... or abuse it.

**Comment by demlak** [comment]
well.. i thought, providing for example callstats.io ID + Secret could be sensitive. But i never used callstats.io.. so: i'm sorry

Beside this i think it is not that rarely out there, that people write personal comments into config files, which will be exposed, without knowledge about exposure.

IMHO i think it makes much more sense to parse a config file for given options and not publish it completely.

all in all, for me, this is/could be security related.. what is the reason for posting an issue

**Comment by damencho** [comment]
> well.. i thought, providing for example callstats.io ID + Secret could be sensitive. But i never used callstats.io.. so: i'm sorry

There are other protections there running.




> IMHO i think it makes much more sense to parse a config file for given options and not publish it completely.

How would you do that without exposing? 

There are no security concerns about exposing config.js.
