### ISSUE TITLE
nginx not recognized on debian

### ISSUE THREAD

**Issue by jotwewe** [jitsi/jitsi-meet#5312]
## Description
No configuration for nginx is created on installation.

## Current behavior
On 
apt-get install jitsi-meet
no nginx configuration is being created when only nginx-light or nginx-full is installed, but not nginx.

## Expected Behavior
Create configuration in those cases, too.

## Possible Solution
Check for nginx-light or nginx-full or nginx in postinst of jitsi-meet-web-config

# Environment details
debian 9.12

**Comment by damencho** [comment]
Have you tried latest unstable? I think nginx-light is not detected. But the rest should be fine. We even default to nginx in latest unstable.

If you have questions and problems use the community forum before opening new issues.
