### ISSUE TITLE
Unable to build mobile on Windows due to hard dependency on bash

### ISSUE THREAD

**Issue by mastacheata** [jitsi/jitsi-meet#5313]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
It's currently not possible to build the mobile app on Windows due to the react-native packaging running in .sh scripts, which are not executable on Windows cmd/PowerShell.

## Current behavior
---
The gradle config for both iOS and Android will try to run the packaging scripts on the native shell.
This fails on Windows as there 1) is no bash installed by default and 2) even if there were, Windows is unaware of the shebang and POSIX paths and would therefore not neccessarily execute the .sh file in bash even if it were installed.

## Expected Behavior
---
The gradle config / scripts for iOS and Android should be cross-platform and not rely on *nix features by default.

## Possible Solution
---
Preferrably the gradle build file would be self-contained and not rely on external scripts.
Most of the thing you do in the .sh files could be described by a Gradle Build task as well.
Notable exception: `nc` and `curl` are not available by default, even on Linux (no idea about OSX, have never owned a Mac)

Another option would be to migrating the .sh files to .js files as node must be installed anyway in order to run React Native.

## Steps to reproduce
---
Execute `npx react-native run-android`
Or if you already successfully built the application and only want to reproduce the error, run `.\gradlew.bat app:installDebug -PreactNativeDevServerPort=8081` inside the android folder.

# Environment details
---
**Windows**

**Comment by damencho** [comment]
Sorry, we do not support building on windows.

**Comment by parazitenew** [comment]
> Sorry, we do not support building on windows.

What does this mean? We have to be on macos or linux to build?

**Comment by damencho** [comment]
Yes.
