### ISSUE TITLE
ios10 support

### ISSUE THREAD

**Issue by vascotenner** [jitsi/jitsi-meet#5318]
My grandparents are using ios10 and i like to meet them via jitsi. However, there is no ios10 app in the appstore. Is there a away to use jitsi meet from a browser on a tablet?

**Comment by saghul** [comment]
No, sorry. Shouldn't the app store show you the last version we releasedd with ios 10 support? Alas, we no longer do, so there is nothing we can do to help. :-/

**Comment by vascotenner** [comment]
No, the appstore does not show a version for ios10.

**Comment by saghul** [comment]
Sorry, I have no idea then, this is, alas, not in our hands.
