### ISSUE TITLE
Jitsi tutti i registratori sono occupati!  all recorders are busy!

### ISSUE THREAD

**Issue by Deroandrea80** [jitsi/jitsi-meet#5319]
Buongiorno,

non riesco mai a fare una registrazione poiché ho sempre queste tipologie di errore.
Come si fa a registrare le proprie lezioni ad uno specifico orario se le registrazioni non funzionano mai?

Grazie.

Good morning,

I can never make a recording because I always have these types of errors.
How do you record your lessons at a specific time if the recordings never work?

**Comment by sd0minick** [comment]
I'm having the same issue here

**Comment by saghul** [comment]
Please search the tracker before opening new issues. This has been asked already. We are working on fixing this.
