### ISSUE TITLE
How to enable VP9

### ISSUE THREAD

**Issue by zzdczhang** [jitsi/jitsi-meet#5327]
How to enable VP9 in jitsi-meeting with tag 3936.

Thanks

**Comment by saghul** [comment]
It's not currently posssible to do so. Please follow the open isssue about it in the jitsi-videobriddge repo.

**Comment by zzdczhang** [comment]
> It's not currently posssible to do so. Please follow the open isssue about it in the jitsi-videobriddge repo.

Thank you for your answer, is there any version of jitsi-meeting that supports vp9?

**Comment by saghul** [comment]
Not at the moment.
