### ISSUE TITLE
NO access to the video

### ISSUE THREAD

**Issue by AebyI** [jitsi/jitsi-meet#5329]
We try to make a video conference. But 3 of us do not have access to the video.
Please check the problem.
Best regards.
I. Aeby
Université de Fribourg

**Comment by saghul** [comment]
Were. you able to have a call with video afterwards? It'ss posssible you got a timeout due to the increased load in our service.

**Comment by Echolon** [comment]
@AebyI is this still an issue?

**Comment by Echolon** [comment]
I will close this, due to lag of information.

@AebyI
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
