### ISSUE TITLE
Chrome 49 Update Causing Problems

### ISSUE THREAD

**Issue by chollander** [jitsi/jitsi-meet#533]
I see that my VZ and Samsung Android Tablets running Jitis Meet that auto upgraded to chrome 49.0.2623.91 are experiencing issues. This update occurred I believe on March 9th. We are running stable meet build 860 and stable video bridge build 677 that were also posted on March 9th. My dell running chrome 48 is not experiencing same issues such as one way video , freezing , non proper sizing of meet screen etc, The counter party to the tablet on windows seems to see and hear tablet participant well but not vice versa. Did a mac to windows test both on 49 desktop chrome and that seems to work. It seems problem is with chrome 49 mobile only. Also tried meet.jit.si same problems when on 49 and that is older bridge and meet client and tried beta.jit.si and which I believe is latest build and still same problem when using chrome 49 mobile on both tablets. Can anyone confirm problem with jitsi/chrome 49 mobile?

**Comment by damencho** [comment]
Obsolete.
