### ISSUE TITLE
[i18n] Translation from main-XX.json ignored

### ISSUE THREAD

**Issue by pitchum** [jitsi/jitsi-meet#5331]
## Description

I know that my instance is not standard but still it's an issue worth fixing, and probably an easy one.

My instance is customized with *defaultLanguage: 'fr'* and I've modified *interface_config.js* in order to not recommend Firefox (that makes me sad, but we're waiting for #4758 ). So I removed "firefox" from *OPTIMAL_BROWSERS*

## Current behavior

Firefox users see a warning upon joining a room. The title of this warning is en French, the body is still in English.

## Expected Behavior

The warning should be fully translated.

## Possible Solution

No idea of a clean solution :( 
In the meantime I've customized a local copy of *app.bundle.min.js*.
Yes I know it's a real bad idea because it may break everything on next upgrade of jitsi-meet.

The l10n key for the message is *notify.suboptimalBrowserWarning*.
That key has a good translation in *main-fr.json* but it is unused.

# Environment details

Installed on Debian Buster with the packages.

**Comment by xolf** [comment]
Same here, try to use `defaultLanguage: 'de'` however the interface is still in english.

**Comment by damencho** [comment]
Try clearing localstorage or in incognito.

**Comment by damencho** [comment]
This is a limitation or bug in i18next and we had not worked on that as changing default language of site is not everyday thing.

**Comment by Wikinaut** [comment]
@xolf see https://twitter.com/Wikinaut/status/1242434947551543296

**Comment by xolf** [comment]
Thanks guys for your helped.

@Wikinaut solutions solved our problems.
