### ISSUE TITLE
switch off stale bot

### ISSUE THREAD

**Issue by WolfgangFahl** [jitsi/jitsi-meet#5332]
## Description
#1964  is closed  - problem not solved.

## Current behavior
#1964  is closed

## Expected Behavior
#1964  should be open - problems don't go away by simply waiting. No answer does not mean the problem is gone. A reopen should at least automatically happen.

## Possible Solution
switch off stalebot - reopen automatically on new comments.

## Steps to reproduce
create an important bug report - wait until stale report closes it without issue being fixed

# Environment details
github/stalebot

**Comment by saghul** [comment]
We are not going to turn it off.

Browsers are updated freequently and issues are fixed just with updates. A > 2 year old issue has a high chance of not capturating the right context for today because many things have changed.

Please open a new issue if the problem reappeared.

**Comment by WolfgangFahl** [comment]
see #5335
