### ISSUE TITLE
Screen Sharing of Android Screen (optional Give Control for support)

### ISSUE THREAD

**Issue by dbareis** [jitsi/jitsi-meet#5348]
**Is your feature request related to a problem you are facing?**
A: I'm trying to teach and help people with Android. I will need to see and preferably also control their screen to do so.  These people are generally over 60 and 70 or 80 is not uncommon.

**Describe the solution you'd like**
A: On Windows (Chrome Browser) I can share the screen or Window or Tab.  I'd like to be able to share the complete Android screen with others.

I'm not sure if Windows sharing is read/see only, but ideally, there would be an option to allow someone to give/take control, mainly for support/help purposes.

**Describe alternatives you've considered**
A: Zoom, Skype, Facebook Messenger and other products, I like the simplicity of your solution while still retaining a lot of features.

**Comment by saghul** [comment]
We have an open issue about this already: https://github.com/jitsi/jitsi-meet/pull/5244

**Comment by dbareis** [comment]
I just tried "ScreenStream (https://play.google.com/store/apps/details?id=info.dvkr.screenstream) but as I now see you said, you have to be on the local network which is no good to me.  I'll try AirDroid remotely.
