### ISSUE TITLE
HedgeDoc (formerly CodiMD) integration, as an alternative to etherpad

### ISSUE THREAD

**Issue by sunjam** [jitsi/jitsi-meet#5349]
[CodiMD](https://github.com/hackmdio/codimd) is a very active project, [which can import from Etherpad](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-migration-etherpad).  The platform is very similar to Etherpad in design.  [See this live demo to try it out](https://demo.codimd.org/#)

**Comment by Wurzelmann** [comment]
+1 would be also very interested in seeing this happening

**Comment by sunjam** [comment]
Please leave open

**Comment by tbussmann** [comment]
just to bring this request up to date: The CodiMD community version has renamed to [HedgeDoc](https://github.com/hedgedoc/hedgedoc) in the meantime to differentiate from the open-core version of HackMD. Demo is available [here](https://demo.hedgedoc.org/). The before mentioned import of notes from Etherpad via it's TXT export [should still be possible](https://github.com/hedgedoc/hedgedoc/blob/master/docs/guides/migrate-etherpad.md) via the [hedgedoc cli](https://github.com/hedgedoc/cli)

**Comment by sunjam** [comment]
open please
