### ISSUE TITLE
Andoid app is unable to connect when http basic auth is used 

### ISSUE THREAD

**Issue by kbsingh** [jitsi/jitsi-meet#5350]
## Description

When the jitsi meeting service is hosted wrapped by http basic auth, as the only AuthN and AuthZ layer, the andoid app is unable to connect to the remote service.  Stuck in a loop saying 
```
You have been disconnected, You may want to check your network connection.  
Reconnecting in x sec..
```
---

## Current behavior

Using the android app, its not possible to join the service or any meetings hosted on it; whereas people using browsers on Linux, OSX and Chromebooks are able to connect fine with no errors log'd on either client or service side.

---

## Expected Behavior

Joining a meeting via the android app should bring up a basic auth user/pass dialog, should it be presented with the http/401 

---

# Environment details

- Host VM is running CentOS Linux 7
- Jitsi Meet is running as implemented via the docker-quick-start flow
- nginx is configured to run the basic auth 
```
        auth_basic "Login";
        auth_basic_user_file /config/nginx/htpass;
```
- http is redirected to https
- https certs are deployed using the bundled certbot
- past the http basic auth, the system is run as an open system, with no auth requirements in the app itself
---

**Comment by saghul** [comment]
The mobile apps are not browsers, you cannot expect them to work with browser authentiation schemes. If you want authentication you can use the application level auth, which is also supported on mobile: https://github.com/jitsi/jicofo/#secure-domain
