### ISSUE TITLE
Delete Meeting Room URL

### ISSUE THREAD

**Issue by yonzfloss** [jitsi/jitsi-meet#5351]
Is there a way to delete the meeting room URL ? because when all participants have left, when the URL is accessed again the meeting room is still open.

I'm really appreciate for any response.

**Comment by damencho** [comment]
When you have questions or problems, please use the community forum before opening new issues.

When the last person leaves the room it is destroyed, and when the first one joins a new room is created. Every time you access the URL if you are the first one, you are creating new room.
