### ISSUE TITLE
Error obtaining microphone permission and Unable toaccess camera

### ISSUE THREAD

**Issue by sowelyk** [jitsi/jitsi-meet#5353]
Device 1 - redmi note7, Android 9
Device 2 - iphone 6s, IOS 13.3.1

When I use a mobile device in the browser (Chrome) login my own build jitsi meet server, can't make video calls and Error obtaining microphone permission, Unable to access the prompt of the camera (I already allows the browser to access a camera and microphone), test using the url https://meet.jit.si/ is still the problem.
When I use the 'Jitsi Meet' app on my mobile device, I don't have this problem, either logging into the server I built myself or https://meet.jit.si/.
The elder brothers and I have similar problems, https://github.com/jitsi/jitsi-meet/issues/5155, the difference is he using personal computers, and I use a mobile device.
I want to be able to make video calls using a browser on my mobile device. How can I fix this?
Thanks! :)

**Comment by saghul** [comment]
We don't support using Jitsi Meet on a mobile browser.
