### ISSUE TITLE
Poll users during exclusion process ?

### ISSUE THREAD

**Issue by LilianCr** [jitsi/jitsi-meet#5355]
**Is your feature request related to a problem you are facing?**
We had just finished the development of lets-share.io which is a website that integrate crisis' tools for people (and by the people).
We're using Jitsi for audiovisual conference and we will receive a lot of people in the next days. There is a big problem for us "Everyone can exclude everyone" of a discussion.

**Describe the solution you'd like**
Maybe to solve it we could implement a poll system which query all members of the room if they agree with the exclusion request ?

**Describe alternatives you've considered**
No alternatives ATM

Thanks in advance,
Lilian :)

**Comment by saghul** [comment]
Hey Lilian! If you have your own deployment you can enable authentication and then only the autheenticcated users would have moderation controls. Does that work in your scenario?

**Comment by LilianCruanes** [comment]
Hey @saghul ! Thanks for your answer ! No that not work, the goal is to offer a 'fast and simple' tool to users, so authentication will be an heavy step which will make the tool less simple to user...

**Comment by saghul** [comment]
I see. We are on the same boat, that's why we have the "everyone is a moderator" scheme. Alas we have no feature which matches your use-case.

**Comment by LilianCruanes** [comment]
@saghul A poll system for an exclusion consented by the group, wouldn't it be better?

**Comment by LilianCruanes** [comment]
With a little popup that appears on screen of each participant with for example "Adrian's asking for John to be excluded, would you agree?" : "Yes", "No"

**Comment by saghul** [comment]
This is a very insteresting feature indeed. I guess there are many small but important details like how much consensus is needed and so on.

This is not something we can jump into right now though. If you are interested in contributing this, I'll be happy to provide guidance / review, however.

First we'd need to know if there is consensus in the community to have this implemented. Maybe open a discussion over at https://community.jitsi.org/

**Comment by LilianCruanes** [comment]
Thanks @saghul, I'll share this to the community :) See you !

**Comment by Echolon** [comment]
I think duplicate:

#5676 **Implement Poll bot for Chat**
