### ISSUE TITLE
Feature request: Share audio together with screen

### ISSUE THREAD

**Issue by jluttine** [jitsi/jitsi-meet#5356]
**Is your feature request related to a problem you are facing?**

I have a large video file on my laptop. I'm trying to figure out how to show it to about 10 participants together online. I can play the video on my laptop and share my screen on Jitsi Meet, but I would also need to share audio (not my mic but directly the audio that the video is playing). It would be cool to have such an option in screensharing in Jitsi Meet.

Other requirements I had that were already fulfilled by Jitsi Meet:
- Video streaming is end-to-end encrypted: WebRTC video calls are end-to-end encrypted.
- Only the participants I want can access the stream: I can password protect the room.

**Describe the solution you'd like**

When sharing the screen, there could be a checkbox to share audio too.

**Describe alternatives you've considered**

I'm interested to hear about alternatives.

**Comment by saghul** [comment]
Good news, we are almost ready with this! Please follow the progress here: https://github.com/jitsi/jitsi-meet/pull/5139
