### ISSUE TITLE
Debian installation : [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel.

### ISSUE THREAD

**Issue by Bschalck** [jitsi/jitsi-meet#5357]
## Description
We can notbe more than one in a meeting :D 

## Steps to reproduce
Connect to https://meet.devloprog.org

# Environment details

Fresh install
Server on LXC Proxmox debian 10.
BEhind an router, in DMZ

I don't know where are the mistakes ....

The JS logs are here 
`2020-03-24T11:36:02.855Z [modules/RTC/TraceablePeerConnection.js] <w.prototype._processLocalSSRCsMap>:  No SSRCs found in the local SDP for LocalTrack[1,audio] MSID: {cfd27143-5434-470b-a453-586449b01a07} {450bbf2b-cf1c-4ae4-8d54-4798e4eb9e3d} in TPC[1,p2p:false] Logger.js:154:22
2020-03-24T11:36:02.855Z [modules/xmpp/JingleSessionPC.js] <value/</<>:  Renegotiate: setting local description Logger.js:154:22
2020-03-24T11:36:02.869Z [modules/xmpp/JingleSessionPC.js] <value/</<>:  removeRemoteStream - OK, SDPs:  
Object { media: (3) […], raw: "v=0\r\no=mozilla...THIS_IS_SDPARTA-74.0 3130652172820248345 1 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 37:69:81:66:60:8A:B5:6B:BD:88:B4:18:F1:2E:59:BB:BD:56:74:AA:F8:B6:D5:EB:4C:E9:29:51:33:58:34:7A\r\na=ice-options:trickle\r\na=msid-semantic: WMS *\r\na=group:BUNDLE audio video data\r\nm=audio 54067 RTP/SAVPF 111 126\r\nc=IN IP4 192.168.0.62\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:126 0-15\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:e7f936b5\r\na=ice-pwd:fe28f6c6b913119a866123ec9702d7a4\r\na=candidate:0 1 UDP 2122187007 10.244.237.73 54066 typ host\r\na=candidate:1 1 UDP 2122252543 192.168.0.62 54067 typ host\r\na=candidate:2 1 TCP 2105458943 10.244.237.73 9 typ host tcptype active\r\na=candidate:3 1 TCP 2105524479 192.168.0.62 9 typ host tcptype active\r\na=end-of-candidates\r\na=ssrc:3681119708 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=ssrc:3681119708 msid:{cfd27143-5434-470b-a453-586449b01a07}-1 {72746334-32ca-4c00-ba26-2d5aa35cc04e}-1\r\na=ssrc:3684255986 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=rtcp-mux\r\nm=video 9 RTP/SAVPF 100 107 101\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:100 VP8/90000\r\na=rtpmap:107 H264/90000\r\na=rtpmap:101 VP9/90000\r\na=fmtp:107 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=fmtp:100 max-fs=12288;max-fr=60\r\na=fmtp:101 max-fs=12288;max-fr=60\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:107 nack\r\na=rtcp-fb:107 nack pli\r\na=rtcp-fb:107 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 ccm fir\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=setup:active\r\na=mid:video\r\na=sendrecv\r\na=ice-ufrag:e7f936b5\r\na=ice-pwd:fe28f6c6b913119a866123ec9702d7a4\r\na=ssrc:1019367635 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=ssrc:1019367635 msid:{e597377a-d5b2-4b5f-8212-0015ff6b516f}-1 {70e032d0-41c8-4ad3-9052-507bc2634d97}-1\r\na=ssrc:4163679535 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=rtcp-mux\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=mid:data\r\na=sendrecv\r\na=ice-ufrag:e7f936b5\r\na=ice-pwd:fe28f6c6b913119a866123ec9702d7a4\r\na=rtcp-mux\r\na=sctpmap:5000 webrtc-datachannel 256\r\na=max-message-size:1073741823\r\n", session: "v=0\r\no=mozilla...THIS_IS_SDPARTA-74.0 3130652172820248345 1 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 37:69:81:66:60:8A:B5:6B:BD:88:B4:18:F1:2E:59:BB:BD:56:74:AA:F8:B6:D5:EB:4C:E9:29:51:33:58:34:7A\r\na=ice-options:trickle\r\na=msid-semantic: WMS *\r\na=group:BUNDLE audio video data\r\n" }
 
Object { media: (3) […], raw: "v=0\r\no=mozilla...THIS_IS_SDPARTA-74.0 3130652172820248345 2 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 37:69:81:66:60:8A:B5:6B:BD:88:B4:18:F1:2E:59:BB:BD:56:74:AA:F8:B6:D5:EB:4C:E9:29:51:33:58:34:7A\r\na=ice-options:trickle\r\na=msid-semantic: WMS *\r\na=group:BUNDLE audio video data\r\nm=audio 54067 RTP/SAVPF 111 126\r\nc=IN IP4 192.168.0.62\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:126 0-15\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:e7f936b5\r\na=ice-pwd:fe28f6c6b913119a866123ec9702d7a4\r\na=candidate:0 1 UDP 2122187007 10.244.237.73 54066 typ host\r\na=candidate:1 1 UDP 2122252543 192.168.0.62 54067 typ host\r\na=candidate:2 1 TCP 2105458943 10.244.237.73 9 typ host tcptype active\r\na=candidate:3 1 TCP 2105524479 192.168.0.62 9 typ host tcptype active\r\na=end-of-candidates\r\na=ssrc:3681119708 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=ssrc:3681119708 msid:{cfd27143-5434-470b-a453-586449b01a07}-1 {72746334-32ca-4c00-ba26-2d5aa35cc04e}-1\r\na=ssrc:3684255986 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=rtcp-mux\r\nm=video 9 RTP/SAVPF 100 107 101\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:100 VP8/90000\r\na=rtpmap:107 H264/90000\r\na=rtpmap:101 VP9/90000\r\na=fmtp:107 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=fmtp:100 max-fs=12288;max-fr=60\r\na=fmtp:101 max-fs=12288;max-fr=60\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:107 nack\r\na=rtcp-fb:107 nack pli\r\na=rtcp-fb:107 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 ccm fir\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=setup:active\r\na=mid:video\r\na=sendrecv\r\na=ice-ufrag:e7f936b5\r\na=ice-pwd:fe28f6c6b913119a866123ec9702d7a4\r\na=ssrc:1019367635 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=ssrc:1019367635 msid:{e597377a-d5b2-4b5f-8212-0015ff6b516f}-1 {70e032d0-41c8-4ad3-9052-507bc2634d97}-1\r\na=ssrc:4163679535 cname:{42d2cf3c-66d3-4574-96fb-61f66d446715}-1\r\na=rtcp-mux\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=mid:data\r\na=sendrecv\r\na=ice-ufrag:e7f936b5\r\na=ice-pwd:fe28f6c6b913119a866123ec9702d7a4\r\na=rtcp-mux\r\na=sctpmap:5000 webrtc-datachannel 256\r\na=max-message-size:1073741823\r\n", session: "v=0\r\no=mozilla...THIS_IS_SDPARTA-74.0 3130652172820248345 2 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 37:69:81:66:60:8A:B5:6B:BD:88:B4:18:F1:2E:59:BB:BD:56:74:AA:F8:B6:D5:EB:4C:E9:29:51:33:58:34:7A\r\na=ice-options:trickle\r\na=msid-semantic: WMS *\r\na=group:BUNDLE audio video data\r\n" }
Logger.js:154:22
2020-03-24T11:36:02.872Z [modules/xmpp/JingleSessionPC.js] <value>:  removal not necessary Logger.js:154:22
2020-03-24T11:36:02.874Z [modules/xmpp/JingleSessionPC.js] <value>:  addition not necessary Logger.js:154:22
2020-03-24T11:36:02.878Z [modules/xmpp/JingleSessionPC.js] <value>:  sendIceCandidate: last candidate. Logger.js:154:22
2020-03-24T11:36:02.943Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:02.964Z [modules/connectivity/IceFailedNotification.js] <value/<>:  ICE connection restored - not sending ICE failed Logger.js:154:22
2020-03-24T11:36:04.946Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:06.950Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:08.948Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:10.946Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:12.949Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:14.948Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:16.950Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:18.951Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. Logger.js:154:22
2020-03-24T11:36:20.951Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel.`

**Comment by saghul** [comment]
How does the sip-communicator.properties file for the jvb look like in your install?

**Comment by Bschalck** [comment]
the sip-communicator.properties file is empty ...

What should be in there ?

**Comment by damencho** [comment]
Seems you had fixed it, I just tested.

Please in the future use the community forum before opening new issues.

**Comment by Bschalck** [comment]
Sorry , you test , but .... Doest it work ?  I mean, with 2 people ?

**Comment by damencho** [comment]
Yes, it works with 3 people is what I tested to be sure I tested the case where it goes through the jvb.

**Comment by Bschalck** [comment]
wow !! Can you tell which browser did you use ?

**Comment by damencho** [comment]
Chrome 80. Are you testing with FF?

**Comment by damencho** [comment]
We know there are issues with Firefox and we are working on fixing them. There will be very soon something to be tested.

**Comment by Bschalck** [comment]
yes FF is our browser. Ok thanks a lot, I will try with chrome ... It it worked for you, that should work for me :D
