### ISSUE TITLE
Non ho accesso alla videocamera

### ISSUE THREAD

**Issue by IolandaCostantini** [jitsi/jitsi-meet#5358]
Mi dice che non riesce ad avere accesso alla videocamera, come mai? Solo con questo sito mi dà problemi

**Comment by saghul** [comment]
Please provide us with as many details as possible: what camera is that? Does it work on https://test.webrtc.org ?

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
