### ISSUE TITLE
Application dialogs not visible when sharing application window

### ISSUE THREAD

**Issue by jgrocha** [jitsi/jitsi-meet#5359]
## Description

When I need to share an application, only the main window is shared. Dialogues, popups and so on are not visible to participants.

## Current behavior

Only the main window is shared.

## Expected Behavior

It would be nice to share all descendent dialogues and panels.
 
## Possible Solution

I don't know if it is a limitation on Chrome's API. Maybe it does not depend on Jitsi, but I'm new to Jitsi.

Possible related to #1013 and #2894

## Steps to reproduce

Create a meeting; share an application with dialogues (like a QT application)

# Environment details

I'm using https://meet.jit.si/ on Ubuntu 19.01, Chrome Version 73.0.3683.103 (Official Build) (64-bit), Gnome 3.34.2, Jitsi Meetings extension 0.2.8.14

**Comment by saghul** [comment]
This is a Chrome limitation. You can share the entire sccreen as an alternative.

**Comment by jgrocha** [comment]
Thank you for the feedback @saghul
