### ISSUE TITLE
Video is muted in Chrome

### ISSUE THREAD

**Issue by Sladoeg** [jitsi/jitsi-meet#536]
Hello, there,
I am getting no audio from remote client in Chrome 49.0.2623.87m.
The remote client is on Raspberry Pi 2 and USB Camera with Microphone with UV4L WebRTC extension installed.
In Chrome Dev Tools --> Console I have found the following:
`pi video is now active
<video muted=?"true" autoplay id=?"remoteVideo_stream_label" src=?"blob:?https%3A/?/?meet.jit.si/?73ec218e-3384-43bc-a904-ce2cf9a2bd8f" style=?"display:? block;? visibility:? hidden;?">?</video>?
DataChannels.js:187selected endpoint changed:  pi
https://meet.jit.si/libs/modules/UI/videolayout/VideoLayout.js:360`
How can I fix Video muted issue? Thank you.

**Comment by damencho** [comment]
Please use the mailinglist before posting issues. 
When you open the same location with two chrome instances is it working?

**Comment by paweldomas** [comment]
The <video> is muted by design, because audio is rendered in separate <audio> tag

**Comment by Sladoeg** [comment]
> When you open the same location with two chrome instances is it working?

Yes, working via two Chrome browsers installed on PCs.
But with using the Firefox 45.0 I can get the audio from remote client (Raspberry Pi 2), but I cannot transmit audio to Raspberry if selecting analog microphone input of the PC, there is no sound captured. 
When I am selecting the USB microphone of the PC the sound is captured and transmitted correctly.
I am sorry, but I really cannot figure out where the problem is as two browsers have different behavior.
