### ISSUE TITLE
Audio crackes on Mac OS

### ISSUE THREAD

**Issue by Badsheep** [jitsi/jitsi-meet#5362]
Hello,

I use meet.jit.si with friends, with an 2016's MacBook Pro.

When I use Mac OS 10.13.6, I have audio crackles about every minute.
When I use Windows 10 on the same computer (using bootcamp), the sound is perfect.

I use Chrome in both cases.

Thanks !

**Comment by saghul** [comment]
If the same machine behaves differently depending on the operating system it's unlikely we can do anything to solve it...

**Comment by Badsheep** [comment]
Hello,

I don't really understand your answer...
I'd rather say it that way : If this machine works well with an given OS, and bad with another OS, I'd say : 
- this machine is capable of a good behavior
- so if there is a problem with the other OS, this a to be a bug in the software.

Am I wrong ?
Thanks !

**Comment by Badsheep** [comment]
In other words : many other users may have problems on OSX.

**Comment by saghul** [comment]
I don't disagree, but Jitsi Meet runs in your browser. We have no control over that. Anecdotally, we use it on macOS extensively and haven't seen this behavior.

**Comment by Badsheep** [comment]
Hello, 

Thanks for your answer.
I’ll search on my side what may be going on.
