### ISSUE TITLE
screensharing doesn't work reliable

### ISSUE THREAD

**Issue by stahnirockt** [jitsi/jitsi-meet#5365]
During my conferences, screen sharing stops working.The shared screen area is no longer visible to the participants, only for me. Problem occurs with both Chrome (version 80.0.3987.149) and Firefox 74.0 under MacOS 10.15.3. Only one program window was shared and not the entire screen.

**Comment by rasos** [comment]
Works here (on our own instance).

**Comment by Echolon** [comment]
related

Screen Sharing Broken in Chrome #4955
100% support for Firefox (and other non-Chrome browsers)
#4758

**Comment by Echolon** [comment]
@stahnirockt can you provide steps to reproduce please?

**Comment by pgenderson** [comment]
I'm having a similar issue but it only affects one member of the meeting. Chrome and Safari.
