### ISSUE TITLE
Feature request: Share audio only

### ISSUE THREAD

**Issue by jluttine** [jitsi/jitsi-meet#5366]
**Is your feature request related to a problem you are facing?**

#5139 is adding support for sharing audio when sharing screen. That's awesome! It would also be nice to be able to share audio only without sharing the screen. For instance, an online exercise/yoga session could use some background music. Or people could listen to an ebook together.

**Describe the solution you'd like**

Be able to share audio only without sharing the screen.

**Describe alternatives you've considered**

Share audio with screen but that's a bit overkill because it wastes bandwidth for video. When sharing audio only, the audio quality could be much better.

**Comment by Echolon** [comment]
@jluttine can this be closed now?

**Comment by jluttine** [comment]
@Echolon Has this been implemented? At least #5139 didn't add this support if I understood correctly.

**Comment by ccapndave** [comment]
Also vital for music rounds in family quiz night :)

**Comment by jhermsen** [comment]
Any updates on this feature request?
Maybe some timeframe in which this might be implemented?

**Comment by saghul** [comment]
It's not possible to implement this in the browser. Audio sharing is done via `getDisplayMedia`, which is about sharing (parts of) the screen.

For example, on macOS and Linux Chrome is only able to share the audio of the tab you are sharing.

**Comment by rananajam1** [comment]
@saghul are you guys planning to develop this feature? If not what are the work arounds?

**Comment by damencho** [comment]
As Saul said this needs to be done in the browser code and there is nothing we can do. The workaround is using a virtual audio device to put whatever audio is needed and use that as mic in the browser.

**Comment by rananajam1** [comment]
@damencho thanks for replying so quick

**Comment by pzystorm** [comment]
@damencho or @saghul, please allow one more question on this:
Image I have a browser tab in Google Chrome which is playing audio, like a youtube tab or nextcloud audio player.
If I could now click on share the screen, allow Google browser to access that tab, in Jitsi you would use that getDisplayMedia method to access that tab but would only broadcast the audio to the audience and discard the video information, then we would already everything what we need here and @jluttine and I would be very happy :)
Would this be possible?

**Comment by saghul** [comment]
This feature has alreqady been implemented. Check the "Share Audio" button.

<img width="298" alt="Screen Shot 2024-01-22 at 09 18 23" src="https://github.com/jitsi/jitsi-meet/assets/317464/49b23e7f-f43b-4697-965f-463cd945ce76">
