### ISSUE TITLE
Feature request: YouTube sharing on Android

### ISSUE THREAD

**Issue by jluttine** [jitsi/jitsi-meet#5367]
**Is your feature request related to a problem you are facing?**

On desktop browser, I can "Share a YouTube video". However, on Jitsi Meet Android app I don't have such possibility. Also, if I do share a youtube video on desktop, I cannot see that video on Android. I can see it on other desktop browsers that are participating in the call.

**Describe the solution you'd like**

I would like to see the shared YouTube videos on Android as well and also be able to share YouTube videos myself on Android.

**Describe alternatives you've considered**

At least seeing the videos that others share even if I cannot share YouTube videos myself on Android.

**Comment by spacehobo** [comment]
I am working with a music teacher who uses the youtube feature to play synchronised tutorial clips to students.

This works fine for everyone connected via Chrome, but it was a shock when someone with the official android app connected.  They saw no video, heard no audio, and weren't even muted while the video played!

**Comment by Echolon** [comment]
Hi,
I will close this with refrerence to Live streaming #5146

---
I'm a community contributor and not directly affiliated with the Jitsi team.

**Comment by spacehobo** [comment]
@Echolon I believe this issue has been closed in error.  It is about sharing youtube videos via the meet, not about sharing the meet via youtube livestreaming.

The "share youtube video" feature only appears to work within the Chrome browser, but is not available in the android app.  

Please re-open this issue.

**Comment by individual-it** [comment]
Is this done?
The changelog claims it is https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-APPS.md#2030-2020-07-14
And I can see the sharing function in the app

**Comment by damencho** [comment]
Yep.
