### ISSUE TITLE
Make browser warning permanently removable (via settings)

### ISSUE THREAD

**Issue by jondo** [jitsi/jitsi-meet#5368]
I am a happy Firefox user, and Jitsi Meet works well enough for me there.
So I would like to have the browser warning permanently removed on my computer, e.g. by changing an appropriate setting.

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

I suppose you are talking about meet.jit.si, we will remove that once we have updates over the Firefox experience, hopefully very soon.

**Comment by jondo** [comment]
"Hopefully very soon" sounds great! Sorry for spamming here.
For the record, @damencho [speaks of the missing simulcast feature](https://community.jitsi.org/t/jitsi-meet-browser-warning-with-supported-browser/21379/8).
