### ISSUE TITLE
Mobile web UI for Jitsi Meet?

### ISSUE THREAD

**Issue by singpolyma-shopify** [jitsi/jitsi-meet#5374]
More and more users have no meaningful computer besides a smartphone.  It would be great if I could use Jitsi Meet with them without making them install an app.

**Comment by saghul** [comment]
This is not something in our roadmap, sorry.

**Comment by singpolyma-shopify** [comment]
Could I ask why not?  It's a pretty surprising omission at this point from an otherwise great product...
