### ISSUE TITLE
Correct italian translation on main-it.json

### ISSUE THREAD

**Issue by alesarrett** [jitsi/jitsi-meet#5375]
## Description
The default English text for "videoStatus" > "callQuality" is "Video Quality" (file lang/main.json)

The correspondent text for Italian (file main-it.json) is "Qualità audio", while it should be "**Qualità video**"

I'm not able to prepare a pull request by myself: could anyone do it?
Thanks,
Ale

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/pull/5376

**Comment by Echolon** [comment]
The correction has been merged, therefore I will close this.

Thank you for reporting!

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
