### ISSUE TITLE
Question: Enabling recording programatically

### ISSUE THREAD

**Issue by Swellenator** [jitsi/jitsi-meet#5377]
I know that auto recording is not available due to privacy reasons. We have a unique situation where is it a legal requirement for our installation of Jitsi to record all client interactions.

Can you please advise how feasible it would be to create our own fork of the code and enable programmatic starting and stopping of recording. There is already an undocumented config item 'autoRecord', can you point me in the direction of where I could change the code to use that setting to start recording?

I can see some components for the record button, and I can see some adapters like

jitsi-meet/react/features/local-recording/recording/OggAdapter.js 

That have a start method. Are they the right methods to call? But how do we know which adapter it is using?

Thanks

**Comment by Echolon** [comment]
rel. #5403

**Comment by cesarcorzo** [comment]
I am trying to do the same thing. Company policy requires this.

**Comment by Hammad-Ishaque** [comment]
Did any body got the solution?
Please share.
