### ISSUE TITLE
E: Unable to locate package jitsi-meet-turnserver

### ISSUE THREAD

**Issue by Commifreak** [jitsi/jitsi-meet#5378]
Your Quick-Setup says, I can uninstall Jitsi via:

`apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge`

but jitsi-meet-turnserver is not an valid package name. Can you check/correct that?

Your repo is active and enabled in sources.list.

I use Ubuntu 18.04.4

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

This package is new and is available in latest packages, which soon will be stable.
