### ISSUE TITLE
Can we share file in the video meeting?

### ISSUE THREAD

**Issue by JacobGbGuan** [jitsi/jitsi-meet#5388]
**Is your feature request related to a problem you are facing?**
We Need to add the file sharing in the meeting, Is there any sloution  or suggestion?
**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by damencho** [comment]
Please use the community forum when you have questions.

Not here is such an option, you can use any other sharing file service and just paste the link in the chat.
