### ISSUE TITLE
Can't build JitsiMeet after upgrading to iOS 13.4 and XCode 11.4

### ISSUE THREAD

**Issue by SlavcoPetkovski** [jitsi/jitsi-meet#5389]
After upgrading JitsiMeetSDK for iOS to the latest one and upgrading XCode to 11.4 i'm receiving this build error.
'PiPViewCoordinator' is not a member type of 'JitsiMeet'
'AnimationCompletion' is not a member type of 'JitsiMeet'
'JMCallKitListener' is not a member type of 'JitsiMeet'

placed in **arm64-apple-ios.swiftinterface** file

**Comment by SlavcoPetkovski** [comment]
Any update on this?

**Comment by saghul** [comment]
No, sorry, we are very busy these days. 11.4 requires Catalina, which means I'd need to update my operating system to test it.

**Comment by saghul** [comment]
More importantly, what is it you needd from 11.4?

**Comment by SlavcoPetkovski** [comment]
Well nothing, I just update XCode more often, no special need.
https://user-images.githubusercontent.com/852767/77588490-dea0d280-6ee1-11ea-84c2-f546d82caa84.png
Here is a screenshot. Maybe I can do something locally to fix it?

**Comment by hzorr** [comment]
> More importantly, what is it you needd from 11.4?

Support for 13.4 ios

Any help would be much appreciated

**Comment by saghul** [comment]
You can support 13.4 without Xcode 11.4. All you need it to copy the DeviceSupport files over tto Xcodee 11.3...

**Comment by codal-hardik** [comment]
@SlavcoPetkovski Did you found the solution for the above error?
If not follow the below steps to generate the framework again with XCode 11.4.
I have the same error for XCode 11.0
Step 1: Download the repository from [here](https://github.com/jitsi/jitsi-meet) 
Step 2: Follow the steps for the readme file for ios [here](https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md).
> Once you completed the pod installation process mentioned on the above step & successfully run the application. Either by XCode or CLI.
> Step 3: Navigate to the ios directory and run the following command on terminal
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS, generic/platform=iOS Simulator' -configuration Release archive
Get the framework from the derived data and put it into your project it will work. I managed this error in this way.

**Comment by SlavcoPetkovski** [comment]
@codal-hardik I still haven't resolved them, so I need your help here. Currently I'm using CocoaPods and my app is native iOS. When I try to install "npm install -g ios-deploy" the npm command is not found... Any help here?

**Comment by codal-hardik** [comment]
@SlavcoPetkovski Pod will not work as we don't know through which XCode version the pod Jitsi framwork was created. The only way I can able to succeed here by doing manually creating the JitsiMeet.framework.

**Comment by saghul** [comment]
> Pod will not work as we don't know through which XCode version the pod Jitsi framwork was created

It was built with Xcode 11.2.1

**Comment by SlavcoPetkovski** [comment]
@codal-hardik Can we connect somehow on another place, because I'm running in a bunch of errors here... Can you help me out?

**Comment by SlavcoPetkovski** [comment]
@codal-hardik Can we connect somehow on another place, because I'm running in a bunch of errors here... Can you help me out?

**Comment by SlavcoPetkovski** [comment]
Nice!! That worked :) Thanks.
I'm just concerned about the WebRTC size (it is around 950MB).

**Comment by codal-hardik** [comment]
@SlavcoPetkovski Can you please let us know how did you solve the problem so if anyone else face this problem they don't need to find the solution by themself.

**Comment by SlavcoPetkovski** [comment]
Step 1: Download the repo

Step 2: Follow the steps for the readme file for ios [here](https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md).

Step 3: Run "xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive"

Step 4: You will get 2 frameworks (JitsiMeet and WebRTC). Their size is very big, so in order to decrease it, you have to strip bitcode using this command. "xcrun bitcode_strip -r JitsiMeet.framework/JitsiMeet -o JitsiMeet.framework/JitsiMeet" (for example on your Desktop)

Step 5: Drag & drop them in your project and in General tab for both of them select "Embed and Sign" option.

Step 6: If you want to publish your app, you have to add [this](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/) script in "Run script" phases with "Run script only when installing" option set to ON.

**Comment by codal-hardik** [comment]
@SlavcoPetkovski Don't you think this is the same as what I have posted except the drag & drop step. Step 5 & 6. That is quite understandable after creating the framework what we need to do for adding them to the project.

**Comment by SlavcoPetkovski** [comment]
I followed your steps but it was like 70-80% of what have I done. I just added the extra steps. No need to thumbdown, just wanted to help.

**Comment by SmartAkashNara** [comment]
Hello anyone has solved compilation error of Xcode I am using Xcode 11.3.1
showing error  " Failed to load module ‘JitsiMeet’

![Screenshot 2020-05-11 at 12 36 42 PM](https://user-images.githubusercontent.com/61772249/81533135-44a6c380-9383-11ea-95ec-66dafb14aebe.png)

**Comment by saghul** [comment]
That seems to be an Xcode bug. If you use 11.4 it should just work. You can make it work by deleting "JitsiMeet" from those lines, as a stopgap. It will compile.

**Comment by rrlevy** [comment]
Any news on making the build work out-of-the-box on Xcode 11.4?

**Comment by immortalsantee** [comment]
> Any news on making the build work out-of-the-box on Xcode 11.4?

I am waiting too.

**Comment by saghul** [comment]
@rrlevy @immortalsantee It already does. Do you get any problems?

**Comment by immortalsantee** [comment]
Cannot run in xCode 11.4

![image](https://user-images.githubusercontent.com/6284566/82121791-605d0000-97af-11ea-8cb4-7631d075a153.jpeg)

**Comment by Boby** [comment]
#5645 

this will solve the issues :)

**Comment by Denismih** [comment]
New Xcode 11.5 - same problems. Waiting for updates. Thanks for your work.

**Comment by hacnguyen1412** [comment]
> New Xcode 11.5 - same problems. Waiting for updates. Thanks for your work.

hey, you just add "platform :ios, '11.0'" in the head of podfile :)))

**Comment by dashvlas** [comment]
> That seems to be an Xcode bug. If you use 11.4 it should just work. You can make it work by deleting "JitsiMeet" from those lines, as a stopgap. It will compile.

works for me, thank you

**Comment by naeemAkee** [comment]
> > That seems to be an Xcode bug. If you use 11.4 it should just work. You can make it work by deleting "JitsiMeet" from those lines, as a stopgap. It will compile.
> 
> works for me, thank you

Can you please help me on it. I'm facing same problem 

<img width="812" alt="Screenshot 2020-12-09 at 8 22 36 PM" src="https://user-images.githubusercontent.com/43524143/101649068-4b520200-3a5c-11eb-8a1e-6ffe5387d9ef.png">

how you fixed that ? @dashvlas

**Comment by saghul** [comment]
Please update to Xcode 12.2, that's the version the latest SDK was built with.

**Comment by rajorange** [comment]
(https://user-images.githubusercontent.com/29770199/102177843-57a9e500-3eca-11eb-9b79-7a279435404f.png)

it is also not working on Version 12.1 (12A7403). Thanks for Help.

**Comment by saghul** [comment]
As I said, you need 12.2

**Comment by afsaredrisy** [comment]
Facing same issue with Version 12.3 (12C33).

**Comment by rdonik** [comment]
![image](https://user-images.githubusercontent.com/13782976/109297860-7cb8bd80-7854-11eb-9d2c-51d35f0b1565.png)
i have same issue, xcode 12.2

**Comment by rdonik** [comment]
@saghul

**Comment by rohmat97** [comment]
i found same problem xcode 12.4

**Comment by saghul** [comment]
In SDK 3 we renamed the main package to JitsiMeetSDK, have you imported the right module?

**Comment by rohmat97** [comment]
> In SDK 3 we renamed the main package to JitsiMeetSDK, have you imported the right module?

yes, indeed
i've been imported right module , for temporary solution i installed xcode 11.2.1 
but i need to know how to handle for xcode 12.4

**Comment by saghul** [comment]
There is nothing special needed for 12.4. If you use SDK 3 just use the new name.

**Comment by ahmed-classtra** [comment]
This worked for me. Removing the `JitsiMeet.` on Xcode 12.4.

https://github.com/jitsi/jitsi-meet/issues/5389#issuecomment-626518321

**Comment by mfa01** [comment]
Try just to remove "JitsiMeet." on all errors, I think it should fix the error
