### ISSUE TITLE
 integrated webcam

### ISSUE THREAD

**Issue by Doriana12** [jitsi/jitsi-meet#5390]
the integrated webcam does not work, it turns on and after a few seconds it freezes and no longer works. the message comes out: unable to access camera

**Comment by alexanderadam** [comment]
Can you try whether your camera works at https://test.webrtc.org/?

**Comment by Echolon** [comment]
unable to access camera #5155

Camera switch not working #4163

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
