### ISSUE TITLE
Screen sharing not working with Firefox on macOS

### ISSUE THREAD

**Issue by alexruf** [jitsi/jitsi-meet#5393]
I am using Firefox 74 on macOS Catalina. When I try to share my screen with Jitsi, Firefox shows the dialogue to select a screen I want to share, but the nothing happens. Screen Recording permission are granted to Firefox via the system preferences.

I haven’t tested it with Chrome on macOS, but it seems to work on Windows with both Chrome and Firefox.

**Comment by saghul** [comment]
Are you using meet.jit.si or your own deployment?

**Comment by alexruf** [comment]
> Are you using meet.jit.si or your own deployment?

I tried both, but it doesn’t make a difference if I use meet.jit.si or my own deployment

**Comment by freechelmi** [comment]
I'm not a macOS catalina user but did you authorise the browser in : 

System Preferences > Security & Privacy > Privacy > Camera
System Preferences > Security & Privacy > Privacy > Micorphone
System Preferences > Security & Privacy > Privacy > Screen Recording. 

Also , can you test Screensharing here and report the error ? 

https://mozilla.github.io/webrtc-landing/gum_test.html

**Comment by alexruf** [comment]
I correct myself: seems to be an issue specific to my Mac. I had the chance to test it on another machine, and screen sharing worked with Firefox without any issues.

Sorry

**Comment by freechelmi** [comment]
Can you guide users on how they can enable SC in MacOS ?

**Comment by alexruf** [comment]
> System Preferences > Security & Privacy > Privacy > Camera
> System Preferences > Security & Privacy > Privacy > Micorphone
> System Preferences > Security & Privacy > Privacy > Screen Recording

Those are the correct permissions you need to grant on macOS. As I figgured out, at least the 'Screen Recording' permissions only works for me if I keep the system dialog unlocked in the background while starting screen sharing in Jitsi.
