### ISSUE TITLE
On a fresh quick install server,  the server fails to answer SSL handshake exactly 1 on 3

### ISSUE THREAD

**Issue by fbouynot** [jitsi/jitsi-meet#5395]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
On a fresh quick install server,  the server fails to answer SSL handshake exactly 1 on 3.
The first, whatever the device, is successful. The second, with the same or another, is successful. The third, with one of the previous or another, is timeouting at * TLSv1.3 (OUT), TLS handshake, Client hello (1):
Fourth and fifth suceed, sixth fails, and so on.

When the fourth / Seventh / ... handshake is attempted, it does suceed, but also the third
 / sixth one finally succed if it hasn't timeout yet.

[successthenfail.txt](https://github.com/jitsi/jitsi-meet/files/4382495/successthenfail.txt)

## Current behavior
---
On a fresh quick install server,  the server fails to answer SSL handshake exactly 1 on 3.

## Expected Behavior
---
It does answer all handshakes.

## Possible Solution
---

## Steps to reproduce
---
- Install Ubuntu 19.10 server on HyperV

    echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
    wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
    apt-get update
    apt-get -y install jitsi-meet
    /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

# Environment details
---
OpenSSL 1.1.1c  28 May 2019
Linux *** 5.3.0-1016-azure #17-Ubuntu SMP Wed Mar 18 18:24:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by damencho** [comment]
If you did not have webserver installed before installing jitsi-meet it defaults to jetty and there were already reports it behaves bad in some cases. New packages default to Nginx and no longer use jetty. Those packages soon will hit stable.
Easy workaround is purge all (as explained in the https://jitsi.org/qi), install Nginx and then install jitsi-meet again.
