### ISSUE TITLE
Portuguese translation on mobile app

### ISSUE THREAD

**Issue by kokbira** [jitsi/jitsi-meet#5398]
I recommended my team to use that app for web conferencing, but some of team members would prefer to use that on native language, Portuguese, to allow more intuitive use of the app tools. The app is on English only.

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

Currently, we have Portuguese (Brazil) https://github.com/jitsi/jitsi-meet/blob/08f55ccb948e49ef6b0162235998e0b423e35fea/lang/languages.json#L26
And this is included in the mobile app which runs the same language as device https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/BuiltinLanguages.native.js#L119
If you want to see a new language you can translate it (create a PR) and the translation will at some point reach the mobile.
