### ISSUE TITLE
YouTube Live Streaming - 1. Sign in With Google always fails & 2. Forgets Stream Key 

### ISSUE THREAD

**Issue by dbareis** [jitsi/jitsi-meet#5399]
I successfully streamed to Youtube with my Youtube Stream Key.  The next day I tried it again and I had to go back and find it again.  It should be a remembered setting like all the rest, and probably with all the rest (or at least duplicated in the UI).

I'm not sure what "Sign in with Google" does (is it an alternative to needing the key?) but it never works.  If it works for anyone then perhaps Jitsi doesn't support 2FA?  It works everywhere else I use it.

Things that probably should be in a Jitsi about box (for copy/paste) or a report bug shortcut:
             Windows 10 64 bit + Chrome 64 bit - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by damencho** [comment]
Please use the community forum for questions before opening new issues.

> I'm not sure what "Sign in with Google" does (is it an alternative to needing the key?) but it never works. If it works for anyone then perhaps Jitsi doesn't support 2FA? It works everywhere else I use it.

We are hitting some quotas and we are waiting on google for that to be resolved, sorry for the inconvenience.
