### ISSUE TITLE
Test Microphone Function

### ISSUE THREAD

**Issue by dbareis** [jitsi/jitsi-meet#5400]
In the settings->Devices (https://meet.jit.si/RandomMeeting), you can see the camera working, you can test the speakers, but you can't test your microphone!

You should probably also be able to do the same tests on Android.

**Windows 10 64 bit + Chrome 64 bit - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by saghul** [comment]
You can test the mic by just speaking and there is a volume meter at the bottom of the video preview.

**Comment by MurzNN** [comment]
Yes, but will be good to hear real voice, so test must record sound from microphone, and playback it later.

**Comment by dbareis** [comment]
On Android it is definitely not there, there is no indication of any type.

On Windows, I sometimes saw something, but I was having issues with a browser extension (it stopped the mic and video working).  I couldn't tell (I didn't know what to expect, I almost gave this product up for Zoom).

The things you talk about aren't documented in a manual and NOT SEEING them is meaningless to most people, particularly a first time user with issues (what other time are they going to have them?).

**Comment by saghul** [comment]
> On Android it is definitely not there, there is no indication of any type.

That's right. Audio device management works different. We cannot preview sound really, so you need to just switch to the device in question.



> On Windows, I sometimes saw something, but I was having issues with a browser extension (it stopped the mic and video working). I couldn't tell (I didn't know what to expect, I almost gave this product up for Zoom).

I don't know what you expet me to say here. It's virtually impossible to detect why a microphone doesn't work. We try to, by seeing if we reeive data frrom it, and the vumeter shows it, plus we show an alert if your mic doesn't work.



> The things you talk about aren't documented in a manual and NOT SEEING them is meaningless to most people, particularly a first time user with issues (what other time are they going to have them?).

Yesh, we don't have a user manual, alas... 



> Seems to me on windows video not playing when it's not muted should be detected and reported, not ignored. This is for the leaders session and all incoming members.

Sorry I don't understand. We were talking about mic testing, I don't know what video not playing has to do with it. Can you please elaborate a bit more?

**Comment by dbareis** [comment]
>> On Android it is definitely not there, there is no indication of any type.

> That's right. Audio device management works different. We cannot preview sound really, so you need to just switch to the device in question.

OK, I don't understand, the Android app doesn't see the microphone's output?  If its unmuted and it "hears" nothing I'd expect that to be unusual.

 
>> On Windows, I sometimes saw something, but I was having issues with a browser extension (**it stopped the mic and video working**). I couldn't tell (I didn't know what to expect, I almost gave this product up for Zoom).
> 
> I don't know what you expect me to say here. It's virtually impossible to detect why a microphone doesn't work. We try to, by seeing if we receive data from it, and the vumeter shows it, plus we show an alert if your mic doesn't work.

I'm not saying that it should work out why it doesn't work, I'm saying:

1. If its unmuted and it "hears" nothing I'd expect that to be unusual
2. There should be a mic test option as you have confirmed you see the "received data".
3. The Vu meter doesn't show "no data received" which is what I believe the starting position should be, maybe red dots, as soon as mic input is received the vumeter starts and the red indicator disappears.


>> Seems to me on windows video not playing when it's not muted should be detected and reported, not ignored. This is for the leaders session and all incoming members.
> 
> Sorry I don't understand. We were talking about mic testing, I don't know what video not playing has to do with it. Can you please elaborate a bit more?

As above Jitsi wasn't working due to a browser extension that caused video and mic issues.  Just like my new comment above for audio, a red, orange or other color (and/or text message) should fill the video panels until some video is received (similar to the "browser permissions message", while they are being checked).

**Comment by dbareis** [comment]
**One the subject of a manual**.

I've written one (draft) for a group that may use it ( I'm also looking at "WebEx" free), I could update it to remove groups specific information for Jitsi users...

It's quite detailed (at least as much as I know). If interested I am sharing the latest version here:
https://drive.google.com/drive/folders/1Qp-qpjKdWoaGaH73nj0N_HNXul6HbM66?usp=sharing

**Comment by saghul** [comment]
> OK, I don't understand, the Android app doesn't see the microphone's output? If its unmuted and it "hears" nothing I'd expect that to be unusual.

Yes, we currently don't do anything in that case. We shoul indeed, but haven't gotten to it.

>     1. If its unmuted and it "hears" nothing I'd expect that to be unusual

This is already handled, we show an error. I think you mean in the preview window? We don't show anything there indeed.

>     2\. There should be a mic test option as you have confirmed you see the "received data".

That's not up to me to decide, but I agree it could be useful.



>     3\. The Vu meter doesn't show "no data received" which is what I believe the starting position should be, maybe red dots, as soon as mic input is received the vumeter starts and the red indicator disappears.

I see. I'll pass along this feedback, since we are in the process of redesigning the device swtiching, thank you!



> If interested I am sharing the latest version here:
> https://drive.google.com/drive/folders/1Qp-qpjKdWoaGaH73nj0N_HNXul6HbM66?usp=sharing

Thank you!

**Comment by dbareis** [comment]
Just one more comment about my "red" idea for vumeter, that should "come
back" when muted (or at least when they UN-MUTE) as a better visual cue
that no input has been received.

Anyway, in the manual I have now made it generic (removed the U3A stuff),
not sure which version you may have seen.

---
Thanks
Dennis

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
31/03/20,
07:51:55 am

**Comment by claell** [comment]
I just had this problem of not knowing whether my mic was working correctly. I noticed the volume meter now after reading this, but you might want to offer some more sophisticated test options, for example where audio is recorded and then played back, so one can also assess the quality of the audio.

**Comment by nekohayo** [comment]
Hi folks, I'll share a little "real world usage scenario" here: yesterday night I had over 20 family members use a room in meet.jit.si to be able to see each other for xmas. It worked very well but there was one technical & usability issue that became clear to me: some participants had their microphones set way too loud (so their voices were peaking) while some participants had their microphone input levels set so low that we couldn't hear them even when they were unmuted. The wide variance in loudness levels was a bit problematic.

I think what would help here is to have a mandatory/in-your-face "microphone check" on the welcome screen; with some tips/instructions, and a horizontal vumeter with color (especially red if it goes above 95% loudness). Something that tells people that their microphone is not properly calibrated and lets them adjust it in their operating system's settings (if you can't do that from the browser) until the vumeter gives them the "green light" (so to speak), and _before_ entering the room with other participants.

**Comment by claell** [comment]
@nekohayo This looks like a nice addition. I know that Big Blue Button has some kind of test whenever entering a room where you have to confirm that you can hear yourself. Combining such thing with more sophisticated controls will probably be great.

Additionally I think that it might be possible to offer some automatic volume adjustments to be able to mitigate volume problems? Not sure whether there is already an issue for that, but you might want to create one.

**Comment by MurzNN** [comment]
Knock knock, bump!

**Comment by MurzNN** [comment]
Bump!

**Comment by secam** [comment]
That is really needed, I have problems with my mic I can't diagnose in jitsi. It works well in other browser tabs for mic test pages, works well in other communication apps outside the browser. But on a meeting other participants are saying they can hardly hear me... and there is no options to record and listen. I have some settings in the OS and sound card itself to tune, but it is very hard to check if you can't hear how it sounds from third party perspective.
