### ISSUE TITLE
Aws S3 Record meetings

### ISSUE THREAD

**Issue by EliveltonRepolho** [jitsi/jitsi-meet#5402]
I am working on a project now, that is all hosted on AWS environment.

Checked jitsi has the ability to record meeting to drop box, would be nice the option to save record's to aws S3 to, is it possible/interesting to be implemented ?

**Comment by saghul** [comment]
Yes, multiple recording backends is something we want to work on. Our plan to do it as a GSoC project but alas we didn’t get accepted, so I don’t know when we’ll get to doing it.

**Comment by damencho** [comment]
We already support a custom recording service, other than dropbox where you can upload to s3 and decide how to distribute your recordings based on the jwt token passed from your system.

**Comment by saghul** [comment]
@damencho I think the point here would be to have something preconfigured perhaps, and choosable by the user.

**Comment by damencho** [comment]
I see, if this is the case then, yeah Dropbox for now, we would love to add more, but we are out of resources of adding those at the moment ...

**Comment by reysy** [comment]
Hi @damencho, you wrote about custom recording service support, is it documented somewhere? Or can you please share it.

**Comment by damencho** [comment]
No, there is no documentation. You install jibri and enable this config.js https://github.com/jitsi/jitsi-meet/blob/master/config.js#L195
And then there is a type that is passed to jibri which you can use to recognize dropbox to the other recording and you can take it from there. 
Here are all the hooks: https://github.com/jitsi/jitsi-upload-integrations/blob/master/jitsi_uploader.sh#L42

**Comment by reysy** [comment]
@damencho thank you!

**Comment by Echolon** [comment]
rel. 
meet.jit.si recording - no audio recorded #5403

**Comment by yodaphone** [comment]
> I am working on a project now, that is all hosted on AWS environment.
> 
> Checked jitsi has the ability to record meeting to drop box, would be nice the option to save record's to aws S3 to, is it possible/interesting to be implemented ?

if you have it hosted on aws, why dont you create a datastore and mount it as NFS store and map to your recording folder?

thats whay i've done

**Comment by luixxiul** [comment]
Closing as the first question has been answered.

**Comment by eonbhuwan** [comment]
> No, there is no documentation. You install jibri and enable this config.js https://github.com/jitsi/jitsi-meet/blob/master/config.js#L195 And then there is a type that is passed to jibri which you can use to recognize dropbox to the other recording and you can take it from there. Here are all the hooks: https://github.com/jitsi/jitsi-upload-integrations/blob/master/jitsi_uploader.sh#L42

Hi is the line number changed? Please update this reply, it will be helpful. Thanks.
