### ISSUE TITLE
Meta - recording problems

### ISSUE THREAD

**Issue by Julia-Glenday** [jitsi/jitsi-meet#5403]
Hi! I'm trying to record meetings hosted online (meet.jit.si). I connected to my dropbox and a file was saved, but appears to have saved with no audio. 
The meeting progressed fine and participants could hear one another, but it appears the audio was not recorded. Any advice on what to try? Thanks!

**Comment by Echolon** [comment]
@saghul @damencho 

evtl. this one should be pinned as well with a bit more proper title

**Comment by sunjam** [comment]
This has zero relation to issue 5800.  Please delete your comment there.  Thanks.

**Comment by Echolon** [comment]
Yes, mistook something

**Comment by slstss** [comment]
Hi, Any ideas when recording resources will be freed up? TIA

**Comment by MagicFab** [comment]
I see at least 2 reports of people not finding their recording "in Dropbox" really meaning "on my PC Dropbox folder".

However when looking at the web directory on the server itself (at dropbox.com), the recording is there.

The ":" in the file name prevents sync to the desktop giving the impression the recording was never saved.

See : 

* https://community.jitsi.org/t/windows-possible-bug-solution-change-filenames-to-allow-dropbox-local-syncing/56451
* https://community.jitsi.org/t/windows-suggestion-of-solution-for-filenames-to-allow-dropbox-local-syncing/56444

**Comment by Liuchunqi3240** [comment]
I want record two people video & audio. how I should do?
now:
person A join meet , person B join meet.
then:
I get a video . the video start with A , but switch to B in a while?

what happen?  what I do  for record only one person video?

**Comment by freechelmi** [comment]
> I want record two people video & audio. how I should do?
Well the forum is more appropriate for this but : 

Just switch to tile view 

Record your screen and audio with your computer using kazam

**Comment by Liuchunqi3240** [comment]
> > I want record two people video & audio. how I should do?
> > Well the forum is more appropriate for this but :
> 
> Just switch to tile view
> 
> Record your screen and audio with your computer using kazam

this not work for me , I try click other filmstrip for switch main screen video , but record video is (click record button person) always.

**Comment by saghul** [comment]
I think this issue has served it's purpose, recording is much more stable now. Time to put it to rest.
