### ISSUE TITLE
All our streamers are busy

### ISSUE THREAD

**Issue by asarriegi** [jitsi/jitsi-meet#5404]
Hi

We are trying to prepare a live streaming session linking our jitsi-meet room to a youtube live channel but almost all our tryings end with the message "All our streamers are busy". Is it a technical problem or just because of the covid-19 virus and its consequences?

Do you think we can trust this way tomorrow at 18:30 (Spain) or should we try another type of streaming like OBS studio?

Thank you very much

**Comment by freechelmi** [comment]
Dup #5294

**Comment by asarriegi** [comment]
Sorry & thanks
