### ISSUE TITLE
WebDAV Integration for images and other files shared in Jitsi conversations

### ISSUE THREAD

**Issue by sunjam** [jitsi/jitsi-meet#5412]
**Is your feature request related to a problem you are facing?**
I'm hoping for WebDAV integration as it is supported on every operating system and all mobile device, plus is used by a number of file sharing systems: Nextcloud, Owncloud, Pydio, Filerun, FileStash, SeaFile, web hosting services, etc.

**Describe the solution you'd like**
Please consider adding support for WebDAV as you have with S3/Minio.

**Describe alternatives you've considered**
Adding Jitsi storage through Minio/S3 integration, but it is a roundabout way to add this functionality.  Thanks for your consideration. :)

Different request, but [here is a request for CalDAV calendar support](https://github.com/jitsi/jitsi-meet/issues/4719), which is another open standard.

**Comment by sunjam** [comment]
Please leave open.

**Comment by didierm** [comment]
Go away, bot.

**Comment by sunjam** [comment]
open please

**Comment by didierm** [comment]
ping

**Comment by saghul** [comment]
We have no plans to add native WebDAV support at this time. Jibri can record to arbitrary storage using the finalizer script.

**Comment by WhyNotHugo** [comment]
Jibri seems to require setting up one's own infrastructure.

There will be no way to record meetings without maintaining our own infrastructure

**Comment by saghul** [comment]
See https://github.com/jitsi/jitsi-meet/issues/5800

**Comment by WhyNotHugo** [comment]
That issue seems to be in the same state: closed / WONTFIX, right?

**Comment by saghul** [comment]
Correct.
