### ISSUE TITLE
Kebab menu top items not accessible in Jitsi widget frames with low height

### ISSUE THREAD

**Issue by MurzNN** [jitsi/jitsi-meet#5415]
## Description
When Jitsi widget integrates in other apps, usually it displayed in iframe with not so large height. For example, in Riot.im there are height 273px, and with this height users don't have access to "View full screen" menuitem!

## Current behavior
With height = 273px Jitsi widget kebab top menu items are not available for user - there are no scroll:
![menu-problem](https://user-images.githubusercontent.com/336662/77577055-35f57180-6ee7-11ea-9c07-43d000d5b56f.png)

Here is same menu in full size:
![menu-full](https://user-images.githubusercontent.com/336662/77577251-7e149400-6ee7-11ea-9374-69b9195f629a.png)

## Expected Behavior
All menu items must be available with low height

## Possible Solution
Add vertical scroll to menu items, when they can't be displayed all in widget

**Comment by MurzNN** [comment]
Related https://github.com/jitsi/jitsi-meet/issues/6687

**Comment by MurzNN** [comment]
Bump!

**Comment by saghul** [comment]
A drawer is now displayed in such cases.

**Comment by MurzNN** [comment]
Thanks, now it have scroll and works, but not in all cases, eg in 400x400 window when I click here:
![image](https://user-images.githubusercontent.com/336662/144252682-2507d4a3-3319-4db2-bb98-5fbe0fa48f23.png)
I see smiles menu together with kebab menu:
![image](https://user-images.githubusercontent.com/336662/144252769-fb645029-0d28-4679-b42e-4b7fedbfd658.png)
