### ISSUE TITLE
No sound or Video when using a password.

### ISSUE THREAD

**Issue by chubs25991** [jitsi/jitsi-meet#5418]
After creating a chat and setting a password. None of the participants can see or hear each other. Setting up a chat with no password with the same people and with the same name for the chat does not do this. All participants have allowed access to cameras and mics and no one muted themselfs.

Sorry if this has already been rasied.

**Comment by saghul** [comment]
Was this on meet.jit.si ? What do you ee on the browser console?

**Comment by chubs25991** [comment]
We think we worked out what the issue was. When we turned adblocker off, it stopped doing it. It was odd that adblocker only stopped it when we had a password set, but anyway we have a solution now.
