### ISSUE TITLE
No puedo conectarme a una video llamada porque dice que mi equipo se detuvo

### ISSUE THREAD

**Issue by jerans16** [jitsi/jitsi-meet#5427]
Tengo el problema de que trato de conectarme a una sala y me dice "la video llamada se interrumpio porque se detuvo este equipo"

**Comment by saghul** [comment]
Puedes mostrar una imagen de tu pantalla?

**Comment by Echolon** [comment]
> I have the problem that I try to connect to a room and it tells me "the video call was interrupted because this equipment stopped"

Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
