### ISSUE TITLE
Logitech Orbit camera not recognized

### ISSUE THREAD

**Issue by jbrooksmartin** [jitsi/jitsi-meet#5430]
USB camera not recognized by Jitsi to mic or video capture.  Any suggestions?

**Comment by saghul** [comment]
Does it work on test.webrtc.org ?

**Comment by alexanderadam** [comment]
Duplicate of #5425

**Comment by jbrooksmartin** [comment]
It works in some of the tests, but not all.  I tried the VDC fix at that #5425 issue, and I didn't find it.  Should I just post my test results there?  is this a new pop-up issue?

**Comment by saghul** [comment]
We think we have found the problem and an update will be rolling out shortly.

**Comment by jbrooksmartin** [comment]
Awesome. Thank you.
