### ISSUE TITLE
apache2 / install-letsencrypt-cert.sh not working

### ISSUE THREAD

**Issue by DoinStuff35** [jitsi/jitsi-meet#5434]
Got yome issues with install-letsencrypt-cert.sh-Script on a server runnig apache2 (most issues here aim on ngnix):

```
Challenge failed for domain my.domain.com
http-01 challenge for my.domain.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: my.domain.com
   Type:   unauthorized
   Detail: Invalid response from
   http://my.domain.com/.well-known/acme-challenge/DBjQ6Z_XrDAr8a0YK3AeBETzVwxz6HYMaU6rd0Hs7pE
   [123.456.789.012]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">\n<html><head>\n<title>404 Not
   Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"
```

Followed Quick-Install Guide, everything seems to work pretty well (Domain ist reachable, working DNS A record). Except LE.

Any ideas? Thank for your effort!

Doinstuff

PS: Debian Buster.

**Comment by saghul** [comment]
IIRC we don't support Let's Encrypt when using Apache, is that right @damencho ?

**Comment by DoinStuff35** [comment]
> 
> 
> IIRC we don't support Let's Encrypt when using Apache, is that right @damencho ?

Uh...does that mean your **script** does not support Apache2 or does it mean, LE & Apache2 for jitsi isn´t supported **at all**? Please clearify, thanks!

**Comment by damencho** [comment]
Nope, LE is supported when using apache. https://github.com/jitsi/jitsi-meet/blob/master/resources/install-letsencrypt-cert.sh#L69

**Comment by ulab** [comment]
When you call your server using `http://`, do you still get the Debian default page for apache?

In that case it might be the same issue I reported here #5239

**Comment by DoinStuff35** [comment]
> 
> 
> When you call your server using `http://`, do you still get the Debian default page for apache?
> 
> In that case it might be the same issue I reported here #5239

Not sure, if it is the same issue. but http->https isn´t working for me too.

Any more ideas on this?

**Comment by ulab** [comment]
So did you try `a2dissite 000-default; systemctl reload apache2` as I suggested in the other issue?

**Comment by DoinStuff35** [comment]
> 
> 
> So did you try `a2dissite 000-default; systemctl reload apache2` as I suggested in the other issue?

Yepp. Neither LE-Script nor https-redirection is working. My best bet is, that the script isn´t able to place the challenge/make it acessible. No clue why redirection isn´t working.

Additional Info: I followed the quick installation guide and added athentication like here https://github.com/jitsi/jicofo#secure-domain

**Comment by MDKAOD** [comment]
This is also not working for nginx using the quick-install.md commands 

Same challenge issue. http>https redirect isn't working, and secondarily, the .well-known/acme-challenge/<CHALLENGE> doesn't seem to be created at all.

**Comment by MDKAOD** [comment]
Looks like this might be a Cloudflare thing?

**Comment by DoinStuff35** [comment]
So, i guess we still have a problem here. Any ideas?

**Comment by BlueWheels75** [comment]
if useful, I’ve got a similar report on  >> Ubuntu 18.04 <<  (right now)
[Why AMAZONAWS is “involved” in the LE process ?]

I’m using a DynDNS domain,
the DNS A record correctly points to my IP server address.
@ http://my.domain.com — > I can get the nginx  “Welcome page”

But, after a Jitsi-meet re-install (prepared w/ purge & autoremove)
an issue arrived  activating the "install-letsencrypt-cert.sh-Script” reporting:

WARNING:certbot,_internal.auth_handler:Challeng failed for domain my.domain.com
INFO:certbot,:internal,auth_handler:http-01 challenge for my.domain.com

Domain: my.domain.com
   Type:   unauthorized
   Detail: Invalid response from
   http://fast.ns0.it/.well-known/acme-challenge/ZoiFXfeaFbEL9K1iRyafWQjyPDBYVAg2BVZxM4x3Nj0
   [aaa.bbb.ccc.ddd.]: &quot;&lt;html&gt;\r\n&lt;head&gt;&lt;title&gt;404 Not
   Found&lt;/title&gt;&lt;/head&gt;\r\n&lt;body&gt;\r\n&lt;center&gt;&lt;h1&gt;404 Not
   Found&lt;/h1&gt;&lt;/center&gt;\r\n&lt;hr&gt;&lt;center&gt;nginx/1.17.10&lt;/c&quot;
This answer means: “404 not found” page by nginx.

**** !! ****
In /var/log/nginx/error.log four lines explain “No such file or directory” …
but this error is replicated … in the middle of the process …
to four clients (52.28.236.88, 34.222.229.130, 3.14.255.131, 66.133.109.36) …. 
NOT the original one initiating and ending the validation process (172.65.32.248) !

Looking at tcpdump … I see
    ec2-52-28-236-88.eu-central-1.compute.amazonaws.10772
    ec2-32-222-229-130.us-west-2.compute.amazonaws.54148
    ec2-3-14-255-131.us-east-2.compute.amazonaws.20716


@MDKAOD , @DoinStuff35  maybe you are on the right way ...

How may I be of some help ?
(and having a working server)

**Comment by jindovu** [comment]
Remove the TLSv1.3 option from nginx solved the problem
