### ISSUE TITLE
unable to access a camera by  mencacci.liliana@gmail.com

### ISSUE THREAD

**Issue by Lillac73** [jitsi/jitsi-meet#5438]
this is the message . can you help me?

**Comment by saghul** [comment]
Please check https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by Lillac73** [comment]
Good morning, we have a problem to access and after 10 minutes we look this message no avaible to camera. Can you hel me? My account is mencacci.liliana@gmail.comThanks Il 30 mar 2020 15:35, Saúl Ibarra Corretgé <notifications@github.com> ha scritto:
Please check #5425
