### ISSUE TITLE
Path to jquery-ui must be updated in package.json

### ISSUE THREAD

**Issue by billux** [jitsi/jitsi-meet#544]
Hi,

I tried to build jitsi-meet but `npm update` fails to import jquery-ui.js file defined in package.json, the path has changed:

    -    "jquery-ui": "./node_modules/jquery-ui/jquery-ui.js",
    +    "jquery-ui": "./node_modules/jquery-ui/ui/jquery-1-7.js",

**Comment by damencho** [comment]
There was indeed a problem with the version of jquery-ui, where ^1.10.5 is resolved as latest 1.12.0 which is not compatible with jitsi-meet. 
This is now fixed.
