### ISSUE TITLE
28-3-20 The video conference could not be recorded

### ISSUE THREAD

**Issue by Kantzara** [jitsi/jitsi-meet#5440]
Hello everyone,
I am very happy to join this open source community, and thank you for all the work you' ve doing!.
Here is the issue I encountered:
Today March 28, 2020, while on video conference tried the "recording video" possibility, but it did not work. The message I got was saying, "unable to record, all recording resources are busy, try later". 
I tried later, but I received the same message, again and again. Yesterday, mind you, I could record the video conferencing. 
Note that the recording archive is sent to dropbox. Today I started a free trial on dropbox business, because the free version was full. 
Is the problem of recording of an open source software related to that it is connected to a not open source account? If yes, how to resolve it?
If not, did anyone has had a similar problem and what did they do to resolve it?
Thank you in advance for the answer,
and take care of yourself!
Yours,
Vasiliki Kantzara
Athens, Greece

**Comment by saghul** [comment]
Hi Vasiliki, we didd have a problem this morning, which got resolved!

**Comment by Kantzara** [comment]
Thank you for your answer!
