### ISSUE TITLE
Google Analystics: Disable Third Party Requests

### ISSUE THREAD

**Issue by Echolon** [jitsi/jitsi-meet#5446]
With reference to this post https://github.com/jitsi/jitsi-meet/issues/4590#issuecomment-605097813 by @Jip-Hop, I am creating a bug informational report. I cannot provide high technical information, but @saghul does know already.

## Description
`https://meet.jit.si/foo#config.disableThirdPartyRequests=true` doesn't disable anything. Not even Google Analytics.

rel. #422, #3010

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/5450
