### ISSUE TITLE
Unable to access my camera

### ISSUE THREAD

**Issue by Marce2020** [jitsi/jitsi-meet#5448]
Unable to access my camera when I start a video conference

**Comment by neilzone** [comment]
I doubt there's much anyone can do with this as it stands — if you were to list:

 - browser and version
 - operating system
 - any errors showing in your browser's console

that might help.

**Comment by alexanderadam** [comment]
Most probably a duplicate of #5425.
Please test it on https://test.webrtc.org and report your at #5425.
