### ISSUE TITLE
API: TOOLBAR_ALWAYS_VISIBLE is ignored on desktop browser

### ISSUE THREAD

**Issue by VirginieGarcin** [jitsi/jitsi-meet#5455]
## Description
The option `TOOLBAR_ALWAYS_VISIBLE: true` in `interfaceConfigOverwrite` seems to be ignored on desktop browser.

## Current behavior
Toolbar is dismissed after the number of milliseconds specified with TOOLBAR_TIMEOUT, even when TOOLBAR_ALWAYS_VISIBLE is true.

## Expected Behavior
Toolbar should never be dismissed when TOOLBAR_ALWAYS_VISIBLE is true.

# Environment details
Tested with Firefox 74 and Chome 80 on Fedora.

**Comment by mikrobestie** [comment]
We have the same problem - I tried a workaround setting INITIAL_TOOLBAR_TIMEOUT to high value but It seems that this setting is also ignored and toolbar is hidden after default 20s. 
However, setting the TOOLBAR_TIMEOUT seems to work, but that unfortunately does not affect the initial state

**Comment by jperera** [comment]
Same here using Chrome in Ubuntu

**Comment by tsiegleauq** [comment]
Can confirm on 83.0.4103.97. It's a mayor problem for us since "moving the mouse in the iFrame to see the controls" is not instinctive understandable for some user

**Comment by VirginieGarcin** [comment]
This issue is still present, should be reopen.

**Comment by ptandler** [comment]
please reopen, would be helpful

**Comment by danzfairs** [comment]
I noticed this too.  Even if I set TOOLBAR_ALWAYS_VISIBLE=true, the toolbar still gets hidden.
