### ISSUE TITLE
[Android App] I don't hear or see anyone in the room

### ISSUE THREAD

**Issue by giupardeb** [jitsi/jitsi-meet#5457]
## Description
I have a Lineage OS without gapps and I installed Jitsi 20.0.3 from fdroid. Unfortunately, I can't use jitsi because I don't see and hear the members in room.

## Current behavior
---
I can't talk in the room because nobody hears me and sees me and vice-versa
## Expected Behavior
---
What I expect is that the members of room see me and hear me and vice-versa

## Possible Solution
---
I don't know
## Steps to reproduce
---
Join to the room
# Environment details
---
Androdid: Lineage OS 16 without GAPPS installed

**Comment by jcbevns** [comment]
Have you tried setting your permissions to the app within Android?
Settings>Apps>Permissions (Microphone and Camera - ON) 

You've tried multiple rooms? What other troubleshooting steps have you attempted so far?

**Comment by giupardeb** [comment]
@jcbevns Yes, I already setted Microphone and Camera permission, and I tried multiple rooms, with the same behaviour

**Comment by saghul** [comment]
Are you using your own server or meet.jit.si ? Can you provide `adb logcat` logs?

**Comment by giupardeb** [comment]
This is the log after I tried to join to the room. 
[logcat_jitsi.txt](https://github.com/jitsi/jitsi-meet/files/4402901/logcat_jitsi.txt)

I hope that is correct

**Comment by saghul** [comment]
I need some more. Can you filer all the logs for the jitsi app and then join a meeting? you can do so with `pidcat org.jitsi.meet` (you need to have pidcat installed).

**Comment by giupardeb** [comment]
@saghul Please, Can you tell me step by step What I to do? I never used pidcat or logcat

**Comment by saghul** [comment]
Use either of them to start capturing the output, while you are in the "welcomee page". The join a meeting. Have another participant join. Hangup. Stop the cature.

**Comment by giupardeb** [comment]
Thank you so much @saghul I used the following command to get error from jitsi:
`adb logcat *:E | grep org.jitsi.meet`

and this is the output:

> 04-02 14:13:13.307 22366 22366 E org.jitsi.meet: No package ID ff found for ID 0xffffffff.
> 04-02 14:13:24.024 22366 22366 E org.jitsi.meet: No package ID ff found for ID 0xffffffff.
> 04-02 14:13:24.274   515   515 E SurfaceFlinger: [SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity#0] rejecting buffer: bufWidth=1074, bufHeight=1172, front.active.{w=1074, h=1244}
> 04-02 14:13:24.307   515   515 E SurfaceFlinger: [SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity#0] rejecting buffer: bufWidth=1074, bufHeight=1172, front.active.{w=1074, h=1914}
> 04-02 14:13:25.480 22366 22366 E org.jitsi.meet: No package ID ff found for ID 0xffffffff.
> 04-02 14:13:34.390 22366 22366 E org.jitsi.meet: No package ID ff found for ID 0xffffffff.
> 04-02 14:13:34.407 22366 22366 E org.jitsi.meet: No package ID ff found for ID 0xffffffff.
> 04-02 14:13:45.840 22366 22366 E org.jitsi.meet: No package ID ff found for ID 0xffffffff.
> 04-02 14:13:46.090   515   515 E SurfaceFlinger: [SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity#0] rejecting buffer: bufWidth=1080, bufHeight=1920, front.active.{w=1080, h=1848}
> 04-02 14:13:46.106   515   515 E SurfaceFlinger: [SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity#0] rejecting buffer: bufWidth=1080, bufHeight=1920, front.active.{w=1080, h=1848}

**Comment by saghul** [comment]
Don't filter just the erros, give me everythin, ass I'm not even sure what I'm looking for.

**Comment by giupardeb** [comment]
[logJITSI.txt](https://github.com/jitsi/jitsi-meet/files/4421048/logJITSI.txt)

**Comment by giupardeb** [comment]
please help me! I can't use the application from my smartphone :-(

**Comment by pandyin** [comment]
I also have experienced this where new joiners couldn't hear and see anyone. it looked like he/she was the only one in the call but there were 60-70 people already on the call.

**Comment by pandyin** [comment]
> I also have experienced this where new joiners couldn't hear and see anyone. it looked like he/she was the only one in the call but there were 60-70 people already on the call.

and I also got reports from users where they experienced the same behaviour on 1-1 call.

**Comment by damencho** [comment]
@pandyin What is your setup? Do you have multiple shards or you are talking about meet.jit.si?

**Comment by pandyin** [comment]
@damencho we were on different devices and platforms. ios and android are using **jitsi meet sdk** and web is calling **jitsi meet external** api.

**Comment by damencho** [comment]
> @damencho we were on different devices and platforms. ios and android are using **jitsi meet sdk** and web is calling **jitsi meet external api**.

Using meet.jit.si or your own deployment?

**Comment by giupardeb** [comment]
I upgraded to jitsi 20.2 and I still have the same problem.

**Comment by pandyin** [comment]
> meet.jit.si

we are using meet.jit.si

**Comment by giupardeb** [comment]
@saghul do you have news? I already installed 20.2.1, but I still have same error

**Comment by mubbelsberger** [comment]
I've got the same error with the same APP Version. 
LOS 16, gApps.

**Comment by giupardeb** [comment]
> I've got the same error with the same APP Version.
> LOS 16, microG

Upgrade to 20.2.3, they finally fixed the bug!
