### ISSUE TITLE
Installation Jitsi Meet in Digital Ocean Ubuntu 18.04 droplet

### ISSUE THREAD

**Issue by alaksandarjesus** [jitsi/jitsi-meet#5458]
First of all, thank you to every selfless souls, contributed to this opensource project. Still i dont believe this is opensource.

I created a droplet and installed nginx

https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04

![image](https://user-images.githubusercontent.com/4712552/77848806-0abf9a80-71e5-11ea-9c46-8ee98c3ff17a.png)

Following this link

https://jitsi.org/downloads/ubuntu-debian-installations-instructions/

For the 8th attempt, i got the jitsi page. i had no idea, why it works now, but not on previous 7 attempts.

Now i am getting this message as insecure url...

![image](https://user-images.githubusercontent.com/4712552/77848976-fa5bef80-71e5-11ea-8e40-562775936a56.png)

Because of this, browsers are displaying this message

![image](https://user-images.githubusercontent.com/4712552/77849064-781ffb00-71e6-11ea-8f98-adcb3078bfe4.png)

Going through the documentation again, i ran

/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

And i got this message

![image](https://user-images.githubusercontent.com/4712552/77849165-32affd80-71e7-11ea-95ca-322ac0bb55d9.png)

What should i do now to get the updated lets encrypt certificate

**Comment by alaksandarjesus** [comment]
I understood the mistake. 

I was enabling the ufw that blocks the site from access.

After i ran sudo ufw enable --- site is not connected

After i ran sudo ufw disable ---  site works fine

The secure certificate also enabled

**Comment by damencho** [comment]
Please use the community forum before opening new issues.
Glad it worked 👍
