### ISSUE TITLE
No screen sharing button on Firefox 74

### ISSUE THREAD

**Issue by joekerna** [jitsi/jitsi-meet#5459]
## Description
I don't see the screen sharing button anymore in Firefox 74.
Not in my own server instance or on meet.jit.si

Screen Sharing test by Mozilla as suggested in #5393 is working fine.
https://mozilla.github.io/webrtc-landing/gum_test.html

## Current behavior
No screen sharing button in Firefox 74
![grafik](https://user-images.githubusercontent.com/23077594/77849179-f4f0ac00-71c9-11ea-8681-3a204eda397c.png)

## Expected Behavior
The button is shown in Firefox 73 on the same server.
![grafik](https://user-images.githubusercontent.com/23077594/77849202-279aa480-71ca-11ea-93a6-5ce7d63d181c.png)

## Possible Solution
??

## Steps to reproduce
Use Jitsi on Firefox 74

# Environment details
Ubuntu 18.04 (Server)
Mac OS High Sierra
Jitsi Meet 4341
Firefox 74

**Comment by dschwoerer** [comment]
Cannot reproduce this in Firefox 74.0-3.fc31 on Fedora.

**Comment by joekerna** [comment]
I realized that if I create a new Firefox Profile it works. Is there a setting in Firefox that could disable this feature?

**Comment by saghul** [comment]
I suppose. See if there is anything related to disabling "getDisplayMedia".

**Comment by joekerna** [comment]
I couldn't find anything. I've simply created a new Firefox profile and it's working now.
I'll close the issue for now.

Please reopen, in case the happens to someone else.

Thanks!
