### ISSUE TITLE
[Feature request] adding a list of servers link

### ISSUE THREAD

**Issue by giupardeb** [jitsi/jitsi-meet#5460]
Hi guys, due to Covid-19 we are forced to use multiples servers of Jitsi. At this moment if I want to change the server link I edited a field server on the settings, but if I want to choose another link I forced to delete the old link server and adding a new. Can you add a field in the settings of the application that allow us to add a list of Jitsi server to switch quickly among it?

**Comment by freechelmi** [comment]
Are you talking about the mobile application ? 

You can use this landing page on the browser

https://framatalk.org/accueil/en/

They use a Big pool of jitsi server , and the mobile app will be used automatically.

**Comment by giupardeb** [comment]
Yes, I talk about the mobile application.  I don't understand How can framatalk resolve the problem. I think that a list view instead of a textbox is more useful

**Comment by freechelmi** [comment]
When you click on the mobile web browser it will launch the application on the right server , simple as that.

**Comment by giupardeb** [comment]
ah okay...I don't know it. thank you
