### ISSUE TITLE
meet.jit.si conference failed with chrome 80 Win10 and safari 13.1 in Mac

### ISSUE THREAD

**Issue by techcouncilbox** [jitsi/jitsi-meet#5461]
## Description

User A joins meet.jit.si/roomY (Chrome 80 on Windows 10 accepting micro and camera permissions).
User B joins meet.jit.si/roomY (Safari 13.1 on Mac OS Catalina accepting micro permissions due camera are not requested).

## Current behavior

Safari user joins conference but after a 3-4 seconds Safari shows the Jitsi reconnection page with text "Unfortunately, something went wrong". Reconnection process fails again and again after 3-4 seconds.

Logs in Safari browser:

![image](https://user-images.githubusercontent.com/17164419/77852150-55d5af80-71dd-11ea-8191-2ad1d6bf7808.png)

## Expected Behavior

Succesful conference between two browsers.

## Possible Solution

Not provided but looks like negotiation using simulcast between browsers fails.

## Steps to reproduce

It occurs always.

# Environment details

Chrome 80 updated accepting micro and camera permissions. Browser updated.
Safari 13.1 on updated Mac OS Catalina accepting micro permissions due camera are not requested. Browser updated.

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

What about two chromes, does it work for you? Safari is known to have problems, there should already be warning about it. An update about Safari and Firefox is coming in the following weeks.

**Comment by techcouncilbox** [comment]
Thx @damencho , I reported here due to I though it was a bug. Sorry for the inconvenience.

**Comment by damencho** [comment]
Safari not behaving very well is known. Once we add the update it should be better and reports will be most welcome. But use the forum first reporting problem ... it may turn out issue is in jicofo or in lib-jitsi-meet ...
