### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by Papasseit** [jitsi/jitsi-meet#5463]
the app doesn't have access to caera

**Comment by Papasseit** [comment]
to camera

**Comment by saghul** [comment]
Please see https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by Papasseit** [comment]
Thanks. I checked that link, which gave correct function of the camera, but the camera doesn't work. It says it is for an unknown reason.

**Comment by saghul** [comment]
Please leave feedback on that issue, we're trying to find the root cause.
