### ISSUE TITLE
No audio and video from/on Android app

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5465]
Both when initiating or joining vide or audio call audio and video is not accessible on Android app and on the another side, only text.

## Steps to reproduce
1. Start session or join session
2. Observe no audio and video.

# Environment details
Android 8.1
Jitsi meet version 20.1.0

**Comment by saghul** [comment]
Can you reproduce this consistently? What is the other endpoint? Does the problem persist if you add a 3rd participant?

**Comment by ostasevych** [comment]
Yes, it doesn't matter. I am not heard and seen and I cannot hear and see anyone. At the start I see that my phone tries to initialise some video, however later it falls.

**Comment by saghul** [comment]
Are you able to provide an `adb logcat` ?

**Comment by ostasevych** [comment]
It seems I found who is guilty here https://github.com/blokadaorg/blokada/issues/669...
