### ISSUE TITLE
Jitsi-Meet stops working after long periods of server IDLE time

### ISSUE THREAD

**Issue by inglesuniversal** [jitsi/jitsi-meet#5467]
I am running an ubuntu 18.x.x server (amazon bitnami) 500 mb shared memory... the script works excellent with the previous version available of your script... but after leaving a conference, if I try to login again... the server will NOT be available for access... I just get a "can't connect to server" browser error.

I have to reboot the server and the problem is SOLVED.

Do I need to add a script or library for that or does the script require a minimum memory amount for it to run smoothly?

How many users can connect to it in various rooms?   Thanks

**Comment by saghul** [comment]
> of your script.

What script?

> a "can't connect to server" browser error.

How did you install Jitsi Meet? What web server are you using?

**Comment by l3d00m** [comment]
Closing as no further feedback was given, feel free to reopen with more details if it still persists.

**Comment by Mozurok** [comment]
Hello guys, Good night, how are you? The same is happening to me, I have the selfdeployed jitsi on an Ubuntu 18 server at Digital Ocean, after a while without anyone using Jitsi, when trying to start a new room, as soon as someone else connects, it gives an error and falls into a reconnection screen. The only way I found to solve this so far was by rebooting the machine through the terminal, then everything works normally again.

**Comment by damencho** [comment]
Have you chexk the logs of jicofo and jvb, is the available RAM enough? Recommended for all on one machine is 8GB of RAM, if you have less you need to adjust jicofo and jvb to use less memory.

**Comment by Mozurok** [comment]
I checked the logs and everything normal, I believe the problem was memory, which forced the service to stop. I am making the changes as you recommended and I will follow up. But to guarantee the best functioning I will also increase the machine's memory.
Thank you very much for your attention.
