### ISSUE TITLE
Registradores ocupados

### ISSUE THREAD

**Issue by LucianaElenaFinardi** [jitsi/jitsi-meet#5472]
Me dice que las herramientas para grabar están ocupadas ... ¿qué puedo hacer?

**Comment by saghul** [comment]
Estamos investigando esto.

**Comment by LucianaElenaFinardi** [comment]
Gracias, estoy preocupada!

**Comment by saghul** [comment]
Prueba de nuevo, deberia de funcionar ahora.

**Comment by LucianaElenaFinardi** [comment]
Perfecto!!!! Gracias, sois un equipo increíble!!!!!!!!!!!!
