### ISSUE TITLE
[Prosody] Jitsi stable Debian repo bug in version  "1.0.3928-1"

### ISSUE THREAD

**Issue by PhilippeRaven** [jitsi/jitsi-meet#5473]
## Description
---
Debian Stretch.
APT history : 

Install: jitsi-videobridge2:amd64 (2.1-157-g389b69ff-1, automatic)

Upgrade: jicofo:amd64 (1.0-508-1, 1.0-539-1), jitsi-meet-web:amd64 (1.0.3729-1, 1.0.3928-1), jitsi-meet:amd64 (1.0.4101-1, 1.0.4335-1), jitsi-meet-web-config:amd64 (1.0.3729-1, 1.0.3928-1), jitsi-meet-prosody:amd64 (1.0.3729-1, 1.0.3928-1)

Remove: jitsi-videobridge:amd64 (1126-1)

## Current behavior
---
When somebody enters a channel, everything is OK, then when a 2nd person enters it, it crashes with "Unfortunately, something went wrong".

## Expected Behavior
---
Expected to upgrade and have nothing to fix.

## Possible Solution
---
I found the solution.
When installing the new version of /etc/prosody/conf.avail/meet.mydomain.tld.cfg.lua, it adds those new lines : 
```
Component "internal.auth.meet.mydomaine.tld" "muc"
    storage = "null"
    modules_enabled = { "ping"; }
    admins = { "focusUser@auth.jitmeet.example.com", "jvb@auth.jitmeet.example.com" }
```
As you can see it forgets to replace "focusUser@auth.jitmeet.example.com" and "jvb@auth.jitmeet.example.com" with the actual domain running.
So you have to manually replace by this line : 

`    admins = { "focusUser@auth.meet.mydomain.tld", "jvb@auth.meet.mydomain.tld" }
`

Restart prosody and it works.

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Thanks for the heads up!

**Comment by saghul** [comment]
Should be fixed by https://github.com/jitsi/jitsi-meet/pull/5475
