### ISSUE TITLE
Impossible record

### ISSUE THREAD

**Issue by josemanuelases** [jitsi/jitsi-meet#5474]
Please take note that I was making a record test in a jitsi session. I connect with my dropbox but when I tried to begin the record the following messaje appear - see the following screen shot.
 
![Captura realizada el 2020-03-30 10 50 44](https://user-images.githubusercontent.com/23087584/77896482-acdc9280-7278-11ea-8c0f-f440e77c8cc5.png)

I wait for your instructions because I will need this option.

Thanks and regards.
José Manuel Ases

**Comment by saghul** [comment]
We are looking into this, thanks for the report.

**Comment by Echolon** [comment]
duplicate of:

meet.jit.si recording - no audio recorded #5403 

@saghul
