### ISSUE TITLE
Unable to connect with the camera

### ISSUE THREAD

**Issue by David1968-thuis** [jitsi/jitsi-meet#5479]
Dear,
We tried allot today to get the camera working on the jitsi meet platform.
Although the cookies show alll is right, camara is permitted to accessed by Jitsi
we get the message from your site: unable to access the camera.
No other programm is using it.

**Comment by saghul** [comment]
does it work on https://test.webrtc.org ?

**Comment by saghul** [comment]
Please continue on https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by David1968-thuis** [comment]
that works. execept for:

Througput 
Video bandwidth

Connectivity
[ INFO ] Gathered candidate of Type: srflx Protocol: udp Address: 83.81.175.153
[ WARN ] Could not connect using reflexive candidates, likely due to the network environment/configuration.
