### ISSUE TITLE
[Feature] room name in browser tab title

### ISSUE THREAD

**Issue by rubenk** [jitsi/jitsi-meet#5480]
**Is your feature request related to a problem you are facing?**
We've run our first CoderDojo over Jitsi this weekend, and so far it has worked great, thank you for all your hard work on Jitsi!.

The CoderDojo mentors have a few rooms open simultaneously, but all rooms have the same page title. Finding the right room between your tabs becomes difficult.

**Describe the solution you'd like**
Have the room name in the page title

**Comment by saghul** [comment]
Makes sense to me! It would need to be changed here: https://github.com/jitsi/jitsi-meet/blob/e1a4478a0689c8d717b4ce57bc58a63e5ed8bcce/react/features/conference/components/web/Conference.js#L123

Any chance you can send a PR wso we can discusss it with the team?

**Comment by rubenk** [comment]
Thanks! I know next to nothing of modern frontend development but I'll give it a try.
Printing interfaceConfig.APP_NAME in Chrome Devtools console gives "Jitsi Meet", not the name of the room though.

**Comment by saghul** [comment]
`APP.conference.roomName`

**Comment by saghul** [comment]
We should probably try to so something like `room naame | Jitsi Meet`

**Comment by rubenk** [comment]
Like this?
```
diff --git react/features/conference/components/web/Conference.js react/features/conference/components/web/Conference.js
index 93c888ec6..82f150793 100644
--- react/features/conference/components/web/Conference.js
+++ react/features/conference/components/web/Conference.js
@@ -120,7 +120,7 @@ class Conference extends AbstractConference<Props, *> {
      * @inheritdoc
      */
     componentDidMount() {
-        document.title = interfaceConfig.APP_NAME;
+        document.title = APP.conference.roomName || interfaceConfig.APP_NAME;
         this._start();
     }
```

**Comment by saghul** [comment]
Sorry, I mean more like a literal `|`: 

```
document.title = `${APP.conference.roomName} | ${interfaceConfig.APP_NAME}`;
```

**Comment by rubenk** [comment]
Ah got it, I just opened #5510 for this

**Comment by mykolarudenko** [comment]
And now it shows "Undefined | <Your app name>" in the title
