### ISSUE TITLE
Nginx won't start after server restart

### ISSUE THREAD

**Issue by ctrager** [jitsi/jitsi-meet#5487]
I originally posted in the community and that generated discussion and info that seems important, so I'm posting an "official" bug here to track progress of the fix.

Here's the community discussion:
https://community.jitsi.org/t/jitsi-meet-nightly-mar-29-on-ubuntu-18-04-worked-but-not-after-reboot-nginx-wont-start/27308

**Comment by gs4711** [comment]
This behaviour originates in two definitions for serving port 443 by nginx:

/etc/nginx/sites-enabled/FQDN.conf:

    server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name FQDN;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eN

    ULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";

/etc/nginx/modules-enabled/60-jitsi-meet.conf

```
server {
    listen 443;

    # since 1.11.5
    ssl_preread on;
    proxy_pass $upstream;

    # Increase buffer to serve video
    proxy_buffer_size 10m;
}
```

**Comment by damencho** [comment]
@gs4711 Can you describe your process, you had a previous installation with Nginx and you did upgrade? 
`60-jitsi-meet.conf` comes from the turnserver that is configured, but that code changes FQDN.conf ... so I'm still not sure how to repro this problem.

**Comment by ctrager** [comment]
My process. I had a fresh installation per the github per the quick install guide, https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md,  that wasn't working well in the sense that my Chrome client would go into a loop of disconnect, reconnect, and I could see from one of the server logs that there was a crash. (Somebody posted excerpts from their log in the community discussion, that looked like the entry I saw). 

So then I saw info that maybe the "nighty" was better so I uninstalled per the guide and followed the instructions here: https://jitsi.org/downloads/ubuntu-debian-installations-instructions-nightly/ and I then WAS able to make a connection with Chrome, just me, that seemed to work.

Then I shut off my server. When I restarted, nginx wouldn't come up.

**Comment by ctrager** [comment]
I should add, this was on a brand new Digital Ocean 1gb droplet, Ubuntu 18.04, and the only thing I did on it was jitsi. Its entire purpose was for jitsi.

**Comment by damencho** [comment]
Thanks, now I know for sure one of the issues I was suspecting, purge does not clean 60-jitsi-meet.conf

**Comment by ctrager** [comment]
@damencho  - Thanks! Based on your comment I rebuilt my droplet and followed a combination of the install guide (for the FQDN stuff) and the nightly instructions and it seems to be working fine even after a restart.

**Comment by ctrager** [comment]
@gs4711  - I thought so too and played with that, but I was able to restart with that config. I think it's what @damencho wrote.

**Comment by damencho** [comment]
> Thanks, now I know for sure one of the issues I was suspecting, purge does not clean 60-jitsi-meet.conf

I just tested it and purge indeed deletes the link, so no problem with removing  60-jitsi-meet.conf. So not sure how it stays behind, maybe you were using apt-get remove?

**Comment by ctrager** [comment]
@damencho -  I'm sure I didn't use a "remove" command, but my actions involved more thrashing around than my simplified explanation.  Note that your own install guide says the following below. I didn't pay close attention to the output of the "purge" commands I copy pasted, so I dunno. 

> Sometimes the following packages will fail to uninstall properly:
> jigasi
> jitsi-videobridge
> When this happens, just run the uninstall command a second time and it should be ok.

**Comment by damencho** [comment]
Well, that file had been removed on my side... and that is when jitsi-meet-turnserver is removed so it is before jitsi-videobridge2 ... still not sure how that can be left behind ...

**Comment by Open-wan** [comment]
Similar problem on a fresh install with Debian 10.3, nginx didn't start : 
nginx[538]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)

Port 443 used both in /etc/nginx/sites-enabled/FQDN.conf and /etc/nginx/modules-enabled/60-jitsi-meet.conf

If I change port in 60-jitsi-meet.conf, it works but I did not have any video and sound.

**Comment by linarnan** [comment]
Try to replace in /etc/nginx/modules-enabled/60-jitsi-meet.conf the port 443 with 4443 that works for me 


see https://community.jitsi.org/t/jitsi-meet-nightly-mar-29-on-ubuntu-18-04-worked-but-not-after-reboot-nginx-wont-start/27308/9

**Comment by Open-wan** [comment]
I tryed this, but I have no sound and video...

**Comment by saghul** [comment]
What do you see in the JS console logs?

**Comment by Open-wan** [comment]
Witch log ?

**Comment by saghul** [comment]
Browser console!

**Comment by Open-wan** [comment]
Maybe NAT Problem...

Warning log:
2020-03-31T11:32:37.298Z [modules/UI/videolayout/VideoLayout.js] <changeUserAvatar>:  Missed avatar update - no small video yet for undefined
2020-03-31T11:32:37.343Z [modules/statistics/AnalyticsAdapter.js] <value>:  Disposing of analytics adapter.
2020-03-31T11:32:37.468Z [features/base/devices] <A/</</<>:  Failed to set audio output device.
                        Default audio output device will be used instead Error: Audio output device change is not supported
2020-03-31T11:32:38.671Z [modules/xmpp/XmppConnection.js] <value>:  Stream resume enabled, but WebSockets are not enabled
wasm streaming compile failed: TypeError: Response has unsupported MIME type react_devtools_backend.js:6:5119
falling back to ArrayBuffer instantiation
La connexion d’AudioNodes à partir d’AudioContexts avec une fréquence d’échantillonnage différente n’est actuellement pas prise en charge.
2020-03-31T11:41:27.784Z [modules/xmpp/strophe.jingle.js] <value>:  invalid session id 
onaddstream is deprecated! Use peerConnection.ontrack instead.
2020-03-31T11:41:28.299Z [modules/RTC/TraceablePeerConnection.js] <k.prototype._processLocalSSRCsMap>:  No SSRCs found in the local SDP for LocalTrack[1,audio] MSID: {26d70cdb-1ca2-4a0c-8e2b-82b4e215def4} {2b848e62-a8bd-42ab-9aef-47e12641f82a} in TPC[1,p2p:false]
2020-03-31T11:41:37.241Z [JitsiConference.js] <oe.prototype._init/this.e2eping<>:  Failed to send E2E ping request or response. undefined

**Comment by Open-wan** [comment]
Error log:

2020-03-31T11:40:32.562Z [features/analytics] <te/<>:  Error: "No analytics handlers created!"
    te functions.js:100
react_devtools_backend.js:6:5119
2020-03-31T11:40:37.544Z [features/analytics] <te/<>:  Error: "No analytics handlers created!"
    te functions.js:100
Logger.js:154:22
2020-03-31T11:40:40.359Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  DOMException: "Operation is not supported" react_devtools_backend.js:6:5119
NotSupportedError: Operation is not supported lib-jitsi-meet.min.js:1
2020-03-31T11:41:27.775Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: "This client does not support P2P connections"
    _rejectIncomingCall JitsiConference.js:1966
    _onIncomingCallP2P JitsiConference.js:1799
    onIncomingCall JitsiConference.js:1814
    emit events.js:146
    value strophe.jingle.js:165
    run strophe.umd.js:1875
    _dataRecv strophe.umd.js:3157
    forEachChild strophe.umd.js:830
    _dataRecv strophe.umd.js:3146
    _onRequestStateChange strophe.umd.js:5012
react_devtools_backend.js:6:5119
2020-03-31T11:41:28.444Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: TypeError: t[2] is undefined Script: https://xxxxxxxxxx.com/libs/lib-jitsi-meet.min.js?v=3928 Line: 10 Column: 33833 StackTrace:  TypeError: "t[2] is undefined"
    parseCandidate sdp.js:65
    RTCIceCandidate common_shim.js:85
    shimRTCIceCandidate common_shim.js:106
    o common_shim.js:27
react_devtools_backend.js:6:5119
TypeError: t[2] is undefined
sdp.js:65:4
2020-03-31T11:41:37.240Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. react_devtools_backend.js:6:5119
ICE failed, add a STUN server and see about:webrtc for more details
2020-03-31T11:41:47.239Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel. react_devtools_backend.js:6:5119
2020-03-31T11:41:48.158Z [modules/RTC/BridgeChannel.js] <value>:  Bridge Channel send: no opened channel.

**Comment by saghul** [comment]
Are you using Firefox 74? Can you please try if you get the same results with Chromium?

**Comment by Open-wan** [comment]
Yes, Firefox74, Working with Chromium !

**Comment by saghul** [comment]
Thanks for confirming. There seems to be some problem with FF74, we are looking into it.

**Comment by olmari** [comment]
I stumbled to this issue, or rootcause for it, on our Jitsi-instances, both Debian Buster... Happened on both apt update, and brand new install of Jitsi-meet on virgin VM. Also neither instance really work, yet (still reading and figuring out all this)..

**Comment by tomiboy78** [comment]
For me the following modification did the trick on a fresh Debian 10.3 Server. Noticeable is, this is only necessary on a fast Debian 10.3 System (i7 32GB). On a slow Debian 10.3 vServer (2vC 4GB) the install scripts works fine without any modification.

change in /etc/nginx/sites-available/meet.my-server.de.conf
Server from 443 to 4444

server {
listen 4444 ssl;
listen [::]:4444 ssl;
server_name meet.my-server.de;

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;

add in a delay /lib/systemd/system/jitsi-videobridge2.service
ExecStartPre=/bin/sleep 30

**Comment by olmari** [comment]
Referring to @tomiboy78 post, I do wonder what would be the proper way to do this..  But I assume it will become a thing "automatically" when devs figure out best way :)

**Comment by damencho** [comment]
> add in a delay /lib/systemd/system/jitsi-videobridge2.service
> ExecStartPre=/bin/sleep 30

Why do you need this?

**Comment by tomiboy78** [comment]
@damencho  I noticed that restarting nginx after reboot helps some people with the latest Debian packages. Now I didn't want to restart the service after each restart. So I delayed the service and that helps. This is only necessary on the fast machine (i7,32GB, nvme).

**Comment by damencho** [comment]
Then why a restart is needed on reboot? What problem does that solves?

**Comment by l3d00m** [comment]
Closing this in favour of #5567 as it has newer information and seems to be about the same problem.
