### ISSUE TITLE
Cannot get property 'mavenRepo' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by sergey-prosvirnin** [jitsi/jitsi-meet#5491]
Hi, I want to put together an apk for Android. I clone the repository, run root `npm i` and in **/jitsi-meet/android/** run `gradle assemble` and I get an error `> Cannot get property 'mavenRepo' on extra properties extension as it does not exist`.
 
I'd appreciate any help in this matter.

**My environment:**
Windows 10
java version "1.8.0_181"
Gradle 6.3
Node.js v12.7.0
Android SDK 9.0 (Pie) 28 API level

```
$ gradle assemble
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\StudioProjects\jitsi-meet\android\build.gradle' line: 58

* What went wrong:
A problem occurred evaluating root project 'jitsi-meet'.
> Cannot get property 'mavenRepo' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by sergey-prosvirnin** [comment]
I have managed to build apk from Gradle version 4.10.1 and the team `gradle assembleRelease`. But why can't I install apk on my smartphone.

**Comment by saghul** [comment]
We don't support buillding on Windows. Chances are your apk is botched because of this.

**Comment by chandanbhanopa** [comment]
Hi , 
I have newly downloaded your react native source code. 
After running the npm install , I tried to run

react-native run-android

It could not have started in my emulator. I am gettng following error:

*** What went wrong:
A problem occurred evaluating root project 'jitsi-meet'.
> Cannot get property 'mavenRepo' on extra properties extension as it does not exist**

![jitsi_error](https://user-images.githubusercontent.com/8103882/86904581-8dce8600-c12e-11ea-9fd3-387d9e5820d2.png)

Can you please let me know what am I missing in setup?
