### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [jitsi/jitsi-meet#5494]
The application is not fully translated.
The site https://translate.jitsi.org is down.
How can I participate in the translation?

**Comment by damencho** [comment]
You can create PRs to this repo changing translations for the time being.

**Comment by damencho** [comment]
Please use the community forum when you have questions, before opening new issues.

**Comment by KovalevArtem** [comment]
> You can create PRs to this repo changing translations for the time being.

![image](https://user-images.githubusercontent.com/36500228/78056644-26b27000-738e-11ea-83c4-2921cc862765.png)
https://github.com/jitsi/jitsi-meet/tree/3c36eece5e4abad9c8ade5c964b1237a08d8d19f/lang
But it’s written not to do so ...

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5056
