### ISSUE TITLE
Simulcast and h.264 codec

### ISSUE THREAD

**Issue by acsfer** [jitsi/jitsi-meet#5496]
About https://github.com/jitsi/jitsi-meet/blob/ca5605620aa05d3cb4e64cea13847b65ec15af9a/config.js#L142-L146
Is this still true as the support (at least on Chrome) is nowadays more wide?

**Comment by saghul** [comment]
I believe we'd need some more adjustments. Can you configm @jallamsetty1 ? Also, is there any bridge work neccessary? @JonathanLennox

**Comment by JonathanLennox** [comment]
The bridge does not currently support simulcast for H.264, no.

**Comment by jallamsetty1** [comment]
This would only work for the p2p case like Jonathan mentioned.

**Comment by no-identd** [comment]
Could someone please share the issue under which adding support for this gets tracked from the bridge side?

**Comment by heylix** [comment]
@no-identd https://github.com/jitsi/jitsi-videobridge/issues/1173

**Comment by no-identd** [comment]
Bad @stalebot no cookie
