### ISSUE TITLE
Option to lock screen on one participant

### ISSUE THREAD

**Issue by TomJSmith** [jitsi/jitsi-meet#5500]
When someone is screen-sharing, it is annoying for the focus to change to other users when they talk. It would be nice to be able to lock the focus to a single user. This could either be set by users on an individual basis, or the focus could be locked for the whole room.

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

Are you talking about meet.jit.si or your own deployment?
There are few options about this, there is already automatic detection and pinning for this: https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L192
You can also use follow me feature from settings and force users to see whatever you see.
