### ISSUE TITLE
Improve audio quality by controlling the microphone sensitivity/mixer ...

### ISSUE THREAD

**Issue by ctheune** [jitsi/jitsi-meet#5502]
**Is your feature request related to a problem you are facing?**

We experience atrocious audio quality every now and then and a friend noticed that this might be related due to microphone mixer settings:
https://twitter.com/wamdamdam/status/1244886674116575234

**Describe the solution you'd like**

I guess it would be nice to control the microphone mixer settings automatically to avoid distortion/clipping/cutoffs. Apparently there is no browser API for it yet, but maybe with all the energy around this topic at the moment we could lobby for an API?

**Describe alternatives you've considered**

An alternative would be to warn the user if their microphone level is too high and causing bad effects. We could then instruct them were to look for the microphone UI depending on their platform/system.

**Comment by saghul** [comment]
@ctheune Does the "you are being too noisy" notification show up for those participants with a noisy microphone? Note that it would be them who see it.

@andrei-gavrilescu Since you worked with mic things, do you think there is anything we could do here?

**Comment by ctheune** [comment]
Hmm. Good question. I wasn't the noisy one, I think. It's also not necessarily noise but when they speak the clip. We're going to experiment with this in the near future and I'll keep an eye open. Maybe @zagy knows as he was affected a number of times.

**Comment by zagy** [comment]
Noise wasn't the issue but the sound clipped. I don't know if macOS automatically adjust the mic level, but I almost never needed to adjust it before. I think the quality was better when we used hangout years ago.

**Comment by ctheune** [comment]
Right, so hangout did use a plugin back then I think. I did Google around a bit and found various items that WebRTC should be auto-levelling the gain. I guess this is not working properly here.

**Comment by saghul** [comment]
The WebRTC AEC, NS and AGC are all enabled by default.

**Comment by andrei-gavrilescu** [comment]
Hello everyone,
I can confirm what @saghul said. Just tested on mac os and AGC is enabled in the Jitsi implementation and works.
However there are several posts that other applications such as Skype and the likes do AGC behind the scenes and might be interfering. 
As for the 'You are noisy' notification, it's quite sensitive to human voice even if it's somewhat distorted it usually won't pick that up as noise.

**Comment by andrei-gavrilescu** [comment]
We could probably do more heuristics around audio gain and adjust it as we see fit, but I don't think we should go against the already implemented AGC in WebRTC.

**Comment by ctheune** [comment]
Right, so a question: what would be a useful report for you guys about the experience from our users and whether it improves when you make changes?
