### ISSUE TITLE
Android SDK serverURL field is being ignored

### ISSUE THREAD

**Issue by tuantvu** [jitsi/jitsi-meet#5504]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- In the Android SDK, the setServerURL option is being ignored. The meeting's serverURL always defaults to https://meet.jit.si

## Current behavior
--- Clients are unable to set their own server using this setServerURL.

## Expected Behavior
--- Clients should be able to set their custom URL using setServerURL.

## Possible Solution
--- I believe, but have not verified the solution, that in the JitsiMeetConferenceOptions.[writeToParcel](https://github.com/jitsi/jitsi-meet/blob/4a218823450cde276f6f2ce1453808eeee968604/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java#L378), the serverURL is never written to the dest.

Also, in the private [constructor](https://github.com/jitsi/jitsi-meet/blob/4a218823450cde276f6f2ce1453808eeee968604/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java#L290) doesn't read it.

On JitsiMeetActivity.[launch](https://github.com/jitsi/jitsi-meet/blob/4a218823450cde276f6f2ce1453808eeee968604/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java#L48), the intent.putExtra would not be sending the serverURL to the JitsiMeetView, causing it to be ignored and default used.

Fix would be write and read the serverURL. Workaround right now is to put the full url in the room field.

## Steps to reproduce
---
      `URL serverURL;
        try {
            serverURL = new URL("https://anotherdomain.com");
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions options
            = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setWelcomePageEnabled(false)
                .build();

       JitsiMeetActivity.launch(activity, options)`

# Environment details
---
Testing via jitsi_meet Flutter plugin using Android pixel 3a API 29 emulator.

**Comment by saghul** [comment]
Great find! There is indeed a bug there. Any chance you can send a PR?

**Comment by tuantvu** [comment]
I am probably not able to sign your contributors agreement due to my job unfortunately. So will not be able to make a PR.

**Comment by vbraun** [comment]
Another workaround is setting the default options 
```java 
        JitsiMeetConferenceOptions defaultOptions = new JitsiMeetConferenceOptions.Builder()
            .setServerURL(serverUrl)
            .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);
```
before building the actual options object.

**Comment by vbraun** [comment]
Parceling the serverURL did the trick, PR is at #5820

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/5820
