### ISSUE TITLE
Start with lower default volume for other participants

### ISSUE THREAD

**Issue by stefandesu** [jitsi/jitsi-meet#5506]
**Is your feature request related to a problem you are facing?**
Consider the following scenario: The sound volume for everyone in the call is roughly equal, i.e. it is not necessary to change their volumes. But there is a single person whose volume is too low. In order to increase their volume, you'd have to:

- decrease the volume of ALL other participants
- increase your system volume

This seems to be more complicated than it needs to be.

**Describe the solution you'd like**
My suggestion is to set the default volume for all participants to the middle of the slider so that it's possible to either decrease or increase the volume for each participants. To solve the scenario described above, it would only be necessary to move that one participant's slider to the right.

**Describe alternatives you've considered**
The alternative is what I described above, but especially in larger calls it would take much less time if this small change was made.

Thanks!

**Comment by mrengy** [comment]
+1  I encountered this issue on the past 2 meetings I was on - only one participant was too quiet, even with my system volume all the way up. It was a pain to go in to lower everyone else’s volume rather than just being able to increase the volume of the one who was too quiet.

**Comment by lordmauve** [comment]
I have this issue; one person on our regular call has very quiet audio and I have to adjust everyone else down and turn system volume up.

It's not a good solution because if someone who I've turned down drops and reconnects they are booming again.

**Comment by stefandesu** [comment]
@lordmauve I totally agree! I still think that this should be implemented since it's easy, doesn't have ANY consequences as far as I can see, and really helps some people.
