### ISSUE TITLE
You have been disconnected. Custom setServerURL() value.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [jitsi/jitsi-meet#5507]
Good afternoon! I changed the value of setServerURL() to the URL of my own server. In the end, the application successfully displays the URL of my server, but when I try to connect I get an error - “You have been disconnected”. However, I don’t see such a problem on the official application from PlayMarket if there is a default server URL to my own server. It may also be important that I use the default Jitsi Meet authorization - https://stackoverflow.com/questions/48588421/adding-authentication-to-jitsi-meet.

I would be glad to get any help!

![Screenshot_20200331-125135_Jitsi Meet](https://user-images.githubusercontent.com/24830345/78013773-a705b080-734f-11ea-9c9e-78660530ee99.jpg)
![Screenshot_20200331-125202_Jitsi Meet](https://user-images.githubusercontent.com/24830345/78013791-abca6480-734f-11ea-8bbd-f6b80799d6a8.jpg)

**Comment by saghul** [comment]
I cannot seem to connect to that URL. Is it correct and publicly available? What TLS certificate does it have?

**Comment by sergey-prosvirnin** [comment]
Hell, I really typed in the URL with a mistake, excuse me. But now I can't rebuild the application with the correct URL, I keep getting the old URL in apk.  I use to build the apk `Build - Generate Signed Bundle / APK ... `in Android Studio. I can't figure out how to remove the cache.

**Comment by saghul** [comment]
That's in the device storage. Go to system settings and wipe.

**Comment by sergey-prosvirnin** [comment]
Do you mean the app cache or the full Android wipe?

**Comment by saghul** [comment]
The app cache.

**Comment by sergey-prosvirnin** [comment]
I've tried a few times before, it's not helping.

**Comment by sergey-prosvirnin** [comment]
![Uploading Screenshot_20200331-145236_Settings.jpg…]()

**Comment by saghul** [comment]
There should be 2 things you can clean: the app cache and the app storage. Clear both.

**Comment by sergey-prosvirnin** [comment]
I've tried this path more than once before.

![image](https://user-images.githubusercontent.com/24830345/78024816-b1c94100-7361-11ea-92ec-c6fa78be6713.png)

**Comment by saghul** [comment]
Then your apk must not be the one you think...

**Comment by sergey-prosvirnin** [comment]
I just installed apk on another smartphone and got the old URL again. The problem is obviously with apk. Do I build a signed apk correctly, should I pick it up from `/jitsi-meet/android/app/release` ? Maybe I need to clear the Gradle cache somehow?

**Comment by sergey-prosvirnin** [comment]
I tried to remove the cache from ~/.gradle/cache and the commands gradle clean cleanBuildCache, but it didn't help. The application in apk still produces a default URL of https://meet.jit.si, not mine. This could be related to the problem - https://github.com/jitsi/jitsi-meet/issues/5504# ?

**Comment by anshad** [comment]
@sergey-prosvirnin you got any fix for this?

For me I have removed the app sidebar links from component and tested it on emulator. But it is getting displayed on release apk.

**Comment by l3d00m** [comment]
So the issue now is that setServerUrl() has no working behaviour for you / it gets overridden by the default jitsi url. Is that correct?

**Comment by sergey-prosvirnin** [comment]
> So the issue now is that setServerUrl() has no working behaviour for you / it gets overridden by the default jitsi url. Is that correct?

Hello. Yes.

**Comment by daxiondi** [comment]
I think you need to uninstall your app and` PersistenceRegistry.js `Add the following code to work
![image](https://user-images.githubusercontent.com/26639571/90355008-94311580-e07d-11ea-8352-e843372e22bc.png)

**Comment by namangt68** [comment]
@sergey-prosvirnin did you get any solution for this? Facing same issue
