### ISSUE TITLE
can not change to large-video

### ISSUE THREAD

**Issue by tzezlcy** [jitsi/jitsi-meet#5508]
When i click the small-video , the large-video doesn't change.
But when i open the F12 devTools, the large video can be seen.

The conference lasts for 1 hours ,and then see the question.
my browser is Chrome 80

thanks for help!

**Comment by saghul** [comment]
Looks like a datachannel connection problem. Can you paste your console logs?

**Comment by tzezlcy** [comment]
> Looks like a datachannel connection problem. Can you paste your console logs?

I see the log, but there's nothing.  When i press F12, the large video  appears, and everything looks like ok

**Comment by saghul** [comment]
That is very strange! Do you have any addons that are somewhat related to video / WebRTC ?

**Comment by tzezlcy** [comment]
> That is very strange! Do you have any addons that are somewhat related to video / WebRTC ?

my chrome is installed recently,  just for jitsi, and have no addons.
It's really very strange
