### ISSUE TITLE
meet.jit.si should . . actually tell the user what the typed text is for

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [jitsi/jitsi-meet#5515]
I find it bizarre that https://meet.jit.si/ shows various bits of near-incomprehensible text being typed, without telling the user the use to which any typed text will be put. The likely result, at least initially, will be - as it was on my part - bafflement. Indeed you don't even tell the user that she or he must type some text, though I suppose one can work that out.

**Comment by LoveIsGrief** [comment]
You might want to provide screenshots. I don't know if the dev team knows what you mean, but as a fellow user, I have no idea what you're referencing.

**Comment by Syonyk** [comment]
It fills out random meeting names in the "Start a New Meeting" box, with a "Go" link to the right, and then when you start the meeting, you see a box about sharing the meeting link.

As there is no persistence of meetings after everyone has left, there's no harm in users experimenting with it a bit - I think it's quite cute, and implies one ought not choose insanely simple meeting names.
