### ISSUE TITLE
Mensaje "All streamers are currently busy"

### ISSUE THREAD

**Issue by molinapj** [jitsi/jitsi-meet#5520]
Good afternoon, sometimes when we try to do a live broadcast from JITSI it shows us the message "All streamers are currently busy".

What can we do to solve this problem?

We await news.
Cheers

Buenas tardes, en algunas ocasiones cuando intentamos hacer una emisión en directo desde JITSI nos muestra el mensaje "All streamers are currently busy".

¿que podemos hacer para solucionar este problema?

Esperamos notícias.
Saludos

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5809

**Comment by Echolon** [comment]
Hi,
Please review: Live streaming #5146

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
