### ISSUE TITLE
Feature Request: Auto-join default meeting

### ISSUE THREAD

**Issue by sicherist** [jitsi/jitsi-meet#5522]
**Is your feature request related to a problem you are facing?**
I would like to give my 90 year old quarantined grandmother an android tablet for video chats. As she has no experience with computer or touch screens I would prefer if she had to do as few steps as possible to start the meeting. Right now she has to touch the JitsiMeet icon, wait a bit, and then touch the name of the meeting to join. I would be nice if the last step could be removed as she will always join the same meeting.

**Describe the solution you'd like**
I would like a setting, where you could define a default meeting that is automatically joined when Jitsi Meet is started.

**Describe alternatives you've considered**
Maybe a widget for the desktop, where one could define the name of the meeting

**Comment by julienDhilly** [comment]
Same feature requested but for the web client. Should be amazing 👍

**Comment by saghul** [comment]
For the web a bookmark should do, right?

**Comment by saghul** [comment]
@sicherist We now have enabled the possibility to open Jitsi Meet in the mobile web browser. For this use case that might preferred. Maybe you can try the “add to home screen” functionality to have a shortcut to the specific meeting that would run in the browser.

**Comment by julienDhilly** [comment]
Oh right, this not the same feature, sry. I've readed to fast.. In fact, when my grandmother turn on the TV, a raspberry open the browser with the URL `https://meet.jit.si/${roomName}`, but she still have to click on "Join meeting" button. This is this last step I want to abstract. Actually I've accomplish this feature by running a custom Javascript code on the page.

My request is maybe to add a query param `https://meet.jit.si/${roomName}?autojoin=1`. I'lle do a new issue if you think this feature nice.

**Comment by saghul** [comment]
@julienDhilly You can accomplish that with a config override: `https://meet.jit.si/${roomName}#config.prejoinPageEnabled=false`

**Comment by julienDhilly** [comment]
I obviously haven't looked enough. Thanks a lot @saghul

**Comment by inovramadani** [comment]
> @julienDhilly You can accomplish that with a config override: `https://meet.jit.si/${roomName}#config.prejoinPageEnabled=false`

Is there IFrame API to do this?

**Comment by damencho** [comment]
Yes, add the prejoinPageEnabled in configOverwrite that is passed to the iframeAPI.
