### ISSUE TITLE
Can't see video flux on android app

### ISSUE THREAD

**Issue by ymeskini** [jitsi/jitsi-meet#5534]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
During a meeting,I join from a laptop (ubuntu 18.04 => chrome Version 80.0.3987.149 (Official Build) (64-bit). 

On Android (Huawei P20 Lite Android 9, with latest app installed) I also joined the same meeting, but I was unable to see the video from the laptop side (camera and screen sharing). 

## Current behavior
Screenshots when the video is enabled from my laptop : 
![Screenshot_20200401_144325_org jitsi meet](https://user-images.githubusercontent.com/30120944/78138807-d0920b00-7427-11ea-80ef-7025b9816475.jpg)
![Screenshot_20200401_144334_org jitsi meet](https://user-images.githubusercontent.com/30120944/78138820-d5ef5580-7427-11ea-8bce-4b3d2cd02682.jpg)

Screenshot after few seconds later : 
![Screenshot_20200401_144405_org jitsi meet](https://user-images.githubusercontent.com/30120944/78138848-ddaefa00-7427-11ea-81de-5e85a87f0aad.jpg)
![Screenshot_20200401_144412_org jitsi meet](https://user-images.githubusercontent.com/30120944/78138853-e0115400-7427-11ea-9496-6bb7b46c8d2f.jpg)
 

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Did you have good connectivity on the phone? Looks like there might have been a bandwidth problem.

**Comment by li-youssefmeskini** [comment]
I tried with the same config but with an iphone 5s and it's working. So I don't think it's about connectivity

**Comment by li-youssefmeskini** [comment]
#5465
