### ISSUE TITLE
Hide logo when someone shares screen

### ISSUE THREAD

**Issue by rickgoud** [jitsi/jitsi-meet#5540]
When someone shares his/her screen, the logo stays visible. This hampers readability of the content shown on the screen.
Isn't it a good idea to hide the logo if someone is sharing his/her screen?

**Comment by c-stubbe** [comment]
This should really be fixed. With this logo, Jitsi cannot reasonable be used for screen sharing (so we have to use TeamViewer for this, with all its drawbacks compared to Jitsi).
Please fix this!
