### ISSUE TITLE
Side menu is not opened when tapped on some of the Android machines

### ISSUE THREAD

**Issue by liormorad** [jitsi/jitsi-meet#5543]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Pressing the hamnurger button should open a menu with options.
This doesn't work on some random Android devices.
## Current behavior
---
menu has no text/images on it when opened - just the transparent rectangle
## Expected Behavior
---
Shown menu with Settings / Terms / Privacy / Send feedback options
## Possible Solution
---

## Steps to reproduce
---

# Environment details
---
Tested on 6 Android machines.
3 introduced this issue. Seems that it's not related to Android OS version
(e.g. it worked OK on Android 8.0 on  one device but not on the other one)

**Comment by saghul** [comment]
We have never seen this. Can you reproduce this consistently? Any chance you could get a logcat of the failing devices? What version of the app were you testing?

**Comment by liormorad** [comment]
- I found out that root cause is when using a language system that is right-to-left , i.e. Hebrew , Arabic
- It happens 100% of the time
- It is reproducible using the latest Android app that is in store.

**Comment by Fahad-Alsaidi** [comment]
I face the same problem.

**Comment by Echolon** [comment]
May someone post a screenshot as well?

**Comment by Echolon** [comment]
@liormorad please provide steps to reproduce. For the meantime I will close this.
