### ISSUE TITLE
instructions for installing jibri on ubuntu server

### ISSUE THREAD

**Issue by brunoamaral** [jitsi/jitsi-meet#5546]
I'm running ubuntu server and the instructions for setting up Alsa don't include this use case.

https://github.com/jitsi/docker-jitsi-meet#jitsi-broadcasting-infrastructure-configuration

```echo "snd-aloop" >> /etc/modules```

returns permission denied.

**Comment by saghul** [comment]
You need to be root, or run the command with sudo.

**Comment by brunoamaral** [comment]
@saghul I think it's more than that, running `sudo echo "snd-aloop" >> /etc/modules` returns the same error. But if I edit the file with a text editor running with sudo it works. I think the echo command is running with admin privileges but still doesn't allow writting to the file.

**Comment by l3d00m** [comment]
See this @brunoamaral https://stackoverflow.com/questions/82256/how-do-i-use-sudo-to-redirect-output-to-a-location-i-dont-have-permission-to-wr 

Going to close this as this is not really related to Jitsi.
