### ISSUE TITLE
Please add Subject Alternative Name to the openssl self-signed cert script

### ISSUE THREAD

**Issue by egerardus** [jitsi/jitsi-meet#5547]
**Is your feature request related to a problem you are facing?**

During the quick install, when a self-signed SSL cert is created it has no [Subject Alternative Name](https://www.entrustdatacard.com/blog/2019/march/what-is-a-san-and-how-is-it-used). This results in chrome giving a "misconfigured cert" error and rejecting HTTPS entirely. This makes the self-signed cert useless for the majority of my users that are on Chrome.

**Describe the solution you'd like**

The simplest solution would be to use the %JITSI_HOSTNAME% variable provided by the user during the quick install and just plug that into the openssl script as a SAN DNS or SAN IP (depending on what it is).

**Describe alternatives you've considered**

I recreated the certificate using a different script that allowed for SAN.

**Comment by saghul** [comment]
Here is where we create it: https://github.com/jitsi/jitsi-meet/blob/6e4c1f64d8ccb385826f2ecd184dc0b01894acbd/debian/jitsi-meet-web-config.postinst#L94 any chance you could open a PR with your propoed improvement? Cheers!

**Comment by egerardus** [comment]
Thanks @saghul PR [created here](https://github.com/jitsi/jitsi-meet/pull/5964).

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/pull/7216
