### ISSUE TITLE
All recorders are busy

### ISSUE THREAD

**Issue by PabloMarCer** [jitsi/jitsi-meet#5548]
I'm having some trouble when it comes to recording my lessons on Jitsi. An error message pops out, "all recorders are busy"... Anything I can do about it? 

Thanks in advance

Pablo

**Comment by saghul** [comment]
Hey Pablo. Nothing you can do on your side. Sometime all our recorders are busy. We'll look into this.

**Comment by jeisoncp** [comment]
Is there someway to help, maybe with donations to improve the infrastructure?
