### ISSUE TITLE
Feature Request: Breakout Rooms

### ISSUE THREAD

**Issue by JpTiger** [jitsi/jitsi-meet#5550]
Thanks for making this, this is amazing! I would love to use this for the volunteer-led classes that a nonprofit I work for teaches and has had to transition to doing over video conferencing. 

The one feature that would really make this functionally stand out for us among the closed-source competition would be the ability to have breakout rooms. So if a teacher is hosting a call of ten students, the teacher could group the students into smaller calls of 2-3 students to do smaller discussions or activities together, drop in on different smaller calls to see how they're doing, then bring them back in to the larger call. 

Thanks again!

**Comment by evolve2k** [comment]
Incase you haven’t bee paying attention Zoom are approaching a moment of reckoning.
https://hn.algolia.com/?q=zoom

And the moment is ripe for another group video service to arise.
Jitsi is attracting a lot of interest from technical folks, but to crack the mainstream there’s one key killer feature that professionally facilitators and large group meeting hosts absolutely require and that is breakout rooms.

Without it, sessions with 50+ people loose much of the possible interactivity that’s critical for engagement.

This is a key moment for Jitsi. 

My suggestion would be to announce publically you’ll begin working on breakout rooms and take the right to Zoom now while everyone is talking about this. Good luck!

Ps. I started question on Hacker News; 
If not Zoom. What to use for large group video with breakout rooms?
https://news.ycombinator.com/item?id=22754935

Provides a lay of the land of competing options. If it wasn’t for breakout rooms I think you otherwise are a strong contender for the best option.

**Comment by berwynhoyt** [comment]
I agree. Every church in the world is also using Zoom for the breakout rooms functionality. But the one feature Zoom itself is missing is breakout sub-rooms. You can't split your breakout rooms into even smaller rooms for one-on-one time or praying together.

This could be done easily by simply allowing co-hosts (a host in each room) to also manage breakout rooms into smaller rooms. But Zoom don't allow that. This is a feature which would put Jitsi ahead of the pack.

**Comment by crabmusket** [comment]
Related: #4787

**Comment by sbargon** [comment]
This has been done, check out https://www.videofacilitator.com/ (built on top of Jitsi)

**Comment by JpTiger** [comment]
> This has been done, check out https://www.videofacilitator.com/ (built on top of Jitsi)

Great, though to be up front, that's a paid product.

**Comment by AndreasAZiegler** [comment]
Due to the corona pandemic I have many more online meetings. As I'm a strong FOSS promoter, I always try to convince people to use jitsi. In my experience, the two main reasons people choose zoom instead of jitsi is that it also works with more browsers (I'm told so) and the breakout rooms. Therefore, I would highly appreciate this feature in order to bring more people to use FOSS.

**Comment by Echolon** [comment]
@JpTiger  May you be so kind and give the issue a clear title summarizing what you are talking about

**Comment by JpTiger** [comment]
> @JpTiger May you be so kind and give the issue a clear title summarizing what you are talking about

Sorry about that! Thought I had but clearly didn't finish it. Fixed.

**Comment by bryceschober** [comment]
@sbargon I'll take this opportunity to note that [videofacilitator.com uses only the Jitsi mobile app](https://www.videofacilitator.com/systemrequirements), which "is not designed for navigating rooms".

**Comment by marclaporte** [comment]
Here is a good explanation of the feature:
https://support.blindsidenetworks.com/hc/en-us/articles/360024516512-Create-and-manage-breakout-rooms

**Comment by Grietje143** [comment]
I would like to use Jitsi instead of Zoom, but this is the feature I really need.

**Comment by jacobgonzales20** [comment]
Breakout rooms would be nice

**Comment by dantosXD** [comment]
This is so necessary, I would be absolutely at full blown software nirvana

**Comment by RoyBkker** [comment]
Totally needed!

**Comment by deleolajide** [comment]
I have made an attempt at this. For now it is only available in Openfire Meetings
https://github.com/igniterealtime/openfire-pade-plugin/wiki/Breakout-Meeting-Rooms

![image](https://user-images.githubusercontent.com/110731/79966048-c1c9d180-8484-11ea-9b28-21bb5f9cae21.png)

It uses a [kanban](https://www.riccardotartaglia.it/jkanban/)  for the UI. It can auto-allocate, re-direct participants to their breakout rooms and reassemble them back to the main conference automatically after a specified duration or manually with the reassemble button. It is only available to moderators, allowing them to dip in and out of any of the breakout rooms during the breakout session. 

![image](https://user-images.githubusercontent.com/110731/79966146-e4f48100-8484-11ea-86d9-397cb823bd99.png)

I have keep to XMPP standards and used [XEP-0335: JSON Containers](https://xmpp.org/extensions/xep-0335.html) to send the redirect commands from the moderator to the participants.

I have no plans to upstream this back to Jitsi as I am too busy to learn React, but the vanilla JavaScript is there for anyone else to port it to React.

**Comment by deleolajide** [comment]
For those interested in testing the breakout rooms feature with meet.jit.si, I have a demo running on GitPages at https://inspired-futures.github.io/ipade/

Please post any issues or questions at https://github.com/inspired-futures/ipade/issues

You are welcome to clone/fork [my github repo](https://github.com/inspired-futures/ipade) and make your own custom version. Edit the config.js and interface_config.js  files. You can even do this all directly from GitHub. No need to download/upload code to/from a PC.

Also note that this is a static web pages version of Jitsi-Meet. Meeting URLs are slightly different because there is no web server code running on GitHub. Just XMPP signalling and WebRTC media connections to meet.ji.si from the client browser.

**Comment by bryceschober** [comment]
I'll also note that my particular use-case of the Zoom breakout rooms does also to pre-assign known users to known rooms... and it's probably a pretty common use-case for church study groups that have stable assignments to "tables" for more private discussions in smaller groups.

**Comment by MethylBromide** [comment]
I also need this, and in particular I have a use case that even Zoom doesn't support. I'm trying to do conference-style rooms where there's a general session followed by breakouts where the attendees can choose for themselves which one to enter (and can switch when they like). Obviously the breakout rooms would need to have names, not just numbers, and it would be great if the meeting owner could select whether to let people see who is already in each room (default yes).

**Comment by deleolajide** [comment]
> I'm trying to do conference-style rooms where there's a general session followed by breakouts where the attendees can choose for themselves which one to enter (and can switch when they like).

My advice would be for you to design and implement your own web page with your required user experience. Put jitsi-meet in an iframe and control it using the external API or encode the meeting URLs directly to enter your breakout rooms.

**Comment by jorsn** [comment]
> Obviously the breakout rooms would need to have names, not just numbers, and it would be great if the meeting owner could select whether to let people see who is already in each room (default yes).

The quick&dirty™ solution without any control but readily available would be to announce rooms `<basename>-<roomname>` in the chat of room `<basename>`. Then, people can join where they want.

@bryceschober I would also suggest this solution to stable church study groups. It's like in real life: In a group which meets regularly, people know the room and enter it autonomously. Problems arise when you want to group people spontaneously or control the size or duration of a public meeting. Then, in an online meeting, the easiest way would be that the moderator distributes people into breakout rooms.

**Comment by MethylBromide** [comment]
I did try to use jitsi in an iframe as deleolajide suggested, but I ran into the issue that the browser (I use Firefox) needs to ask permission of the user to use the camera and mic, and it can't do that if the content is in an iframe.

**Comment by MacBlui** [comment]
> > Obviously the breakout rooms would need to have names, not just numbers, and it would be great if the meeting owner could select whether to let people see who is already in each room (default yes).
> 
> The quick&dirty™ solution without any control but readily available would be to announce rooms `<basename>-<roomname>` in the chat of room `<basename>`. Then, people can join where they want.
> 
> @bryceschober I would also suggest this solution to stable church study groups. It's like in real life: In a group which meets regularly, people know the room and enter it autonomously. Problems arise when you want to group people spontaneously or control the size or duration of a public meeting. Then, in an online meeting, the easiest way would be that the moderator distributes people into breakout rooms.



> > Obviously the breakout rooms would need to have names, not just numbers, and it would be great if the meeting owner could select whether to let people see who is already in each room (default yes).
> 
> The quick&dirty™ solution without any control but readily available would be to announce rooms `<basename>-<roomname>` in the chat of room `<basename>`. Then, people can join where they want.
> 
> @bryceschober I would also suggest this solution to stable church study groups. It's like in real life: In a group which meets regularly, people know the room and enter it autonomously. Problems arise when you want to group people spontaneously or control the size or duration of a public meeting. Then, in an online meeting, the easiest way would be that the moderator distributes people into breakout rooms.

What about this workaround? Attending breakout meetings can be done very easily with Jitsi even in one browser (two or more different TABs) - just attend different meeting rooms :-)

But to work as a workaround for breakout-rooms (yes, we really need real breakout-rooms! :-) one needs to easily switch the audio while changing the TABs. So muting one room (MIC + loudspeaker) and unmuting the other room. Or putting loudspeaker to 20% for the "old" room" - for all curious people who _can_ do multitasking. Hence women :-)

Does anybody know a browser-based solution for this for Chrome, Chromium, Firefox  etc.? It _can_ be done with tools on OS-basis - but this is not feasible for "normal" users.

Thanks for your ideas & discussion...

PS: I tried two Chrome-extension doing a sort of mute - but this is not working very well...

**Comment by MacBlui** [comment]
> > > Obviously the breakout rooms would need to have names, not just numbers, and it would be great if the meeting owner could select whether to let people see who is already in each room (default yes).
> > 
> > 
> > The quick&dirty™ solution without any control but readily available would be to announce rooms `<basename>-<roomname>` in the chat of room `<basename>`. Then, people can join where they want.
> > @bryceschober I would also suggest this solution to stable church study groups. It's like in real life: In a group which meets regularly, people know the room and enter it autonomously. Problems arise when you want to group people spontaneously or control the size or duration of a public meeting. Then, in an online meeting, the easiest way would be that the moderator distributes people into breakout rooms.
> 
> > > Obviously the breakout rooms would need to have names, not just numbers, and it would be great if the meeting owner could select whether to let people see who is already in each room (default yes).
> > 
> > 
> > The quick&dirty™ solution without any control but readily available would be to announce rooms `<basename>-<roomname>` in the chat of room `<basename>`. Then, people can join where they want.
> > @bryceschober I would also suggest this solution to stable church study groups. It's like in real life: In a group which meets regularly, people know the room and enter it autonomously. Problems arise when you want to group people spontaneously or control the size or duration of a public meeting. Then, in an online meeting, the easiest way would be that the moderator distributes people into breakout rooms.
> 
> What about this workaround? Attending breakout meetings can be done very easily with Jitsi even in one browser (two or more different TABs) - just attend different meeting rooms :-)
> 
> But to work as a workaround for breakout-rooms (yes, we really need real breakout-rooms! :-) one needs to easily switch the audio while changing the TABs. So muting one room (MIC + loudspeaker) and unmuting the other room. Or putting loudspeaker to 20% for the "old" room" - for all curious people who _can_ do multitasking. Hence women :-)
> 
> Does anybody know a browser-based solution for this for Chrome, Chromium, Firefox etc.? It _can_ be done with tools on OS-basis - but this is not feasible for "normal" users.
> 
> Thanks for your ideas & discussion...
> 
> PS: I tried two Chrome-extension doing a sort of mute - but this is not working very well...

Hm, hate commenting my own comments :-) 

I just tried to use the Jitsi-integrated selection of output device(s), available in the latest version of Jitsi. This can be found in the control-set at the bottom of a Jitsi Videoconference screen (small arrow right on the mute-button).

I selected two different output-devices for two different tabs / two different rooms (one headset, one loudspeaker). Seems to work - but not quite user-friendly.

Any experiences using this set-up in real conferences?

Thanks & best regards
cb

**Comment by JayHoltslander** [comment]
Just arrived here via Google after searching for an alternative to Zoom's breakout meetings functionality. Was already aware of Jitsi and hoping the feature already existed.

**Comment by puthli** [comment]
We are working on breakout rooms and other tools on top of Jitsi meet. Our use case is group facilitators and trainers. We were in the EuVsVirus hackathon last week and have since fleshed out the prototype we made. 

Last week we had our first trial users and they were quite satisfied. 
At some point we will need to make this a paid service to fund the server hosting, but for now its open for everyone here to use: www.wurk.app 

Comments and suggestions are welcome!

**Comment by dantosXD** [comment]
I need this, if anyone has any solutions and need testers.

**Comment by xae7Jeze** [comment]
Hi all,
this feature would by very nice to have.

**Comment by luixxiul** [comment]
Hi guys, would you please add "+1" to the first post instead of adding comments? thanks!

**Comment by aspiers** [comment]
I have attempted to summarise all known Jitsi-based solutions for breakout rooms in this new wiki page:

https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms

**Comment by yodaphone** [comment]
> We are working on breakout rooms and other tools on top of Jitsi meet. Our use case is group facilitators and trainers. We were in the EuVsVirus hackathon last week and have since fleshed out the prototype we made.
> 
> Last week we had our first trial users and they were quite satisfied.
> At some point we will need to make this a paid service to fund the server hosting, but for now its open for everyone here to use: [www.wurk.app](http://www.wurk.app)
> 
> Comments and suggestions are welcome!

Hi 

Any plans on making this opensource?

**Comment by aspiers** [comment]
[**@yodaphone**](https://github.com/yodaphone) commented on [May 26, 2020 3:28 AM](https://github.com/jitsi/jitsi-meet/issues/5550#issuecomment-633775453 "2020-05-26T02:28:04Z - Replied by Github Reply Comments"):
> Any plans on making [wurk.app] opensource?

Yes - see https://github.com/jitsi/jitsi-meet/issues/4787#issuecomment-626213513

**Comment by puthli** [comment]
Hello, we made a poll to see which use cases breakout rooms will help with. Please help us by answering two questions: https://docs.google.com/forms/d/e/1FAIpQLSd0zLFO0PJHUzQAn9JXMnAd-zlnvCJlVOls8f6QrEahnvQPuA/viewform 
Thanks in advance!

**Comment by rvdv01** [comment]
> Hello, we made a poll to see which use cases breakout rooms will help with. Please help us by answering two questions: https://docs.google.com/forms/d/e/1FAIpQLSd0zLFO0PJHUzQAn9JXMnAd-zlnvCJlVOls8f6QrEahnvQPuA/viewform
> Thanks in advance!

Thanks for creating this feature for Jitsi!
I just gave it a try and what's there, is already working quite nicely!
Of course, it's easy to see it's still under development since 'basic' features are still missing (eg. naming a room, moving multiple people at once to a room, allowing attendees to see which room are there and possible let them switch between rooms themselves), but the basis is working quite nicely!
I hope you can get all this code back to Jitsi somehow or perhaps make it a one-time-purchase add-on or something.

**Comment by drewellenrw** [comment]
Please, please. I'm ready to leave zoom and use your product, but without break out rooms, it doesn't meet my organizations need.  Please add this feature asap.

**Comment by JVillella** [comment]
We have been working on a solution to the more general problem of networking within an online event/meetup. We experimented _heavily_ with breakout rooms of varying sizes with zoom - as well as some of the limited available options on top of Jitsi. We had this idea of spatial/proximity-based "rooms" that felt more natural to us. Here's a gif from an earlier prototype of it,

![meetfromhome-meet](https://user-images.githubusercontent.com/6306986/87465519-cf55aa00-c5e2-11ea-9883-ad883eea50fa.gif)

You can try it out for yourself (it's a lot better than that gif these days). It's free, no sign-in required: https://meetfromhome.io

We'd like to add this option for others to use on the [Jitsi wiki](https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms) but seems there's no option to edit anymore.

**Comment by yodaphone** [comment]
> We have been working on a solution to the more general problem of networking within an online event/meetup. We experimented _heavily_ with breakout rooms of varying sizes with zoom - as well as some of the limited available options on top of Jitsi. We had this idea of spatial/proximity-based "rooms" that felt more natural to us. Here's a gif from an earlier prototype of it,
> 
> ![meetfromhome-meet](https://user-images.githubusercontent.com/6306986/87465519-cf55aa00-c5e2-11ea-9883-ad883eea50fa.gif)
> 
> You can try it out for yourself (it's a lot better than that gif these days). It's free, no sign-in required: https://meetfromhome.io
> 
> We'd like to add this option for others to use on the [Jitsi wiki](https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms) but seems there's no option to edit anymore.

looks very interesting.. will definitely try it out

**Comment by yodaphone** [comment]
> Hello, we made a poll to see which use cases breakout rooms will help with. Please help us by answering two questions: https://docs.google.com/forms/d/e/1FAIpQLSd0zLFO0PJHUzQAn9JXMnAd-zlnvCJlVOls8f6QrEahnvQPuA/viewform
> Thanks in advance!

Hi there... any more progress to your project?

**Comment by JpTiger** [comment]
> 
> 
> We have been working on a solution to the more general problem of networking within an online event/meetup. We experimented _heavily_ with breakout rooms of varying sizes with zoom - as well as some of the limited available options on top of Jitsi. We had this idea of spatial/proximity-based "rooms" that felt more natural to us. Here's a gif from an earlier prototype of it,
> 
> ![meetfromhome-meet](https://user-images.githubusercontent.com/6306986/87465519-cf55aa00-c5e2-11ea-9883-ad883eea50fa.gif)
> 
> You can try it out for yourself (it's a lot better than that gif these days). It's free, no sign-in required: https://meetfromhome.io
> 
> We'd like to add this option for others to use on the [Jitsi wiki](https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms) but seems there's no option to edit anymore.

I've always liked this concept. Have you talked to the folks at [gather.town](gather.town)? They're doing a similar thing but are still working out the kinks as well.

**Comment by JVillella** [comment]
Thanks @yodaphone and @JpTiger - I came across their project last month. I love where they are going with it. I think there's something that feels right w/ the concept, just needs more exploring. :)

**Comment by kno10** [comment]
I'd love to see meetfromhome.io/gather.town like capabilities. There also appears to be a similar open-source project: https://github.com/capnmidnight/Calla

For me, it **must** be self-hosted open-source. It won't pass the privacy requirements otherwise.

**Comment by JVillella** [comment]
@kno10 That's certainly an option. What use cases do you have in mind for it?

**Comment by kno10** [comment]
Virtual hangout for students to socialize. They'd certainly prefer to run it on their own servers.

**Comment by aspiers** [comment]
> We'd like to add this option for others to use on the [Jitsi wiki](https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms) but seems there's no option to edit anymore.

I wrote most of that wiki page, and I've lost my edit access too :-(  This is a pretty unfriendly thing to do to contributors without any warning/explanation.  I hope it can be reversed.

**Comment by aspiers** [comment]
I've posted about the wiki issue here: https://community.jitsi.org/t/edit-access-for-jitsi-jitsi-meet-wiki-was-removed/71402

**Comment by nimaam** [comment]
I can add breakout to your jitsi meet instance with local recording and etherpad to full funtionality, and you can have control to all of them in your API, I can handle a webinar mode that guest can not sea each other too, I made a change to jitsi alot and now is ready to others but not for free and not expensive.
- Break out
- Local Record no jibri needed
- Local Snapshopt
- Etherpad
- HIde guests from guests and moderator sea all 
- stream to youtube/instagram/facebook and all rtpm server.

**Comment by saghul** [comment]
@nimaam First and last warning. This issue tracker is not an advertising platform.

**Comment by kno10** [comment]
@JVillella any updates on whether your approach could become available as open-source for self-hosted non-profit use?

**Comment by gtilflm** [comment]
Looking to have breakout rooms as part of a project I'm having built.  Would be interested in connecting with other people who want to develop similar functionality.  No point in everyone developing the same thing if we can pool our resources/knowledge.

If interested please email me at jbovey@liveonlinemath.com.

**Comment by wcerfgba** [comment]
I was looking for a similar but not identical feature to Zoom breakout rooms, which I have since found implemented in Hubbub [1] and Toucan [2].

Whereas breakout rooms let the facilitator/host split people off in to random groups/subvideoconferences within a main call, I want something similar but with more control by the participants, oriented around recovering the social dynamics of a real world group conversation instead of being a facilitation tool. My idea is 'bubbles': a user can pull others 'to the side' to create a separate conversation (splits AV into multiple groups). All users can see all bubbles and move between bubbles at will. Option to 'overhear' a bubble and preview the conversation before joining/moving bubble. So instead of randomised breakouts, any participant could invite someone to create a breakout.

The implementation of 'bubbles' and breakout rooms are very similar, except that breakout rooms have a stricter set of permissions (only the facilitator can create the rooms and either manually or randomly assign participants to the rooms), and 'bubbles' requires some additional UI for participants (to allow them to see all rooms/bubbles and move between them, and possibly support an optional 'overhear' feature). I would love if a solution could be implemented which supports both of these features. 

[1] https://hubbub.live/
[2] https://toucan.events/

**Comment by JVillella** [comment]
> @JVillella any updates on whether your approach could become available as open-source for self-hosted non-profit use?

Hey @kno10, I don't mind sharing the source. Want to send me an email about how you were thinking about using it? (jvillella.jv@gmail.com)

**Comment by kno10** [comment]
@Jvillella I will not have time to explore this myself.

**Comment by awlx** [comment]
As we get more and more requests regarding this feature. Is there any timeline for this?

**Comment by saghul** [comment]
There isn't. We have no plans to work on it in the short term.

**Comment by awlx** [comment]
But would you be open to take a PR in general? Or is this out of scope for Jitsi anyway?

**Comment by waja** [comment]
Jitsi is widely used by schools these days. As far I can report from teachers and parents of childs, breakout rooms are the most missed feature in context of (home)schooling actually.

**Comment by saghul** [comment]
> But would you be open to take a PR in general? Or is this out of scope for Jitsi anyway?

It's hard to answer without having a design for the feature to look at. I don't mean the UI, that is important as well, but how it would work and integrate in the codebase.

**Comment by aspiers** [comment]
A reminder to everyone new to this thread that I was previously maintaining [this list of all available ways to get breakout rooms in Jitsi](https://github.com/jitsi/jitsi-meet/wiki/Jitsi-based-solutions-for-breakout-rooms).  Unfortunately however at a later point [the wiki was locked](https://community.jitsi.org/t/edit-access-for-jitsi-jitsi-meet-wiki-was-removed/71402/4) and so the information there is becoming out of date.

It would be great if someone could volunteer to migrate this page to the official documentation, where the community could help maintain it and keep it up to date!

**Comment by saghul** [comment]
@aspiers I dropped the ball on moving all content to the handbook, sorry about that. If this is something you're keen on doing, feel free to open a PR in the handbook repo and @ me.

**Comment by gtilflm** [comment]
I 2nd the comment from @waja that this is a massively helpful feature in online learning.  As an online teacher, this is a gotta have and would be happy to talk with any developers who are or want to pursue this.  Perhaps a small group that has the same goal could collaborate on this?  I would happily run lead on this to organize the effort.

Personally, I'd like the ability to "pipe" audio and video (and many screensharing?).  Like somehow say, "user 42 'pipes' his audio to room 17".  And then everyone in room 17 can hear/see user 42.

**Comment by puthli** [comment]
The second half of 2020 went differently than we expected: There was some interest in wurk.app but not enough to provide a business model.  Our other business was crazy busy so we did not have time to follow up until now. 
wurk.app provides 
- a UI layer on top of the Jitsi API that facilitates breakout rooms
- a server for inter-room communication and moderator functions
- a statistics interface for prometheus
- a prometheus installation
- the above is on top op a standard jitsi meet installation with docker

All of the above runs in docker containers. We have scripts to populate an AWS server.
We will move our private git repo's to a github soon, allowing people to host the software themselves. We will use Apache 2 or MIT licences.

Any help with the open source process and / or testing would be appreciated.

**Comment by awlx** [comment]
That sounds great! Thank you very much in advance.

**Comment by aspiers** [comment]
Thanks to @saghul, the wiki page for breakout rooms solutions has now [been moved](https://community.jitsi.org/t/edit-access-for-jitsi-jitsi-meet-wiki-was-removed/71402/5) into the [official handbook](https://jitsi.github.io/handbook/docs/community/breakout-rooms), so anyone can submit PRs to [the `breakout-rooms.md` file](https://github.com/jitsi/handbook/blob/master/docs/community/breakout-rooms.md).  Please help maintain this page for the benefit of the whole Jitsi community!

**Comment by heikar** [comment]
Perhaps it would be possible to check and implement the [pade-plugin](https://github.com/jitsi/jitsi-meet/issues/5550#issuecomment-618461856).

Breakout rooms is a really important feature and it is a pity that Jitsi it does not have yet.
But maybe soon ;)

**Comment by saghul** [comment]
@puthli Hey Robin, that sounds very interesting! Sorry the business didn't work, kudos for your willingness to give this away to the community.

Feel free to reach out to me (saghul @ jitsi . org) - Happy to help with the open source process.

**Comment by saghul** [comment]
https://github.com/puthli/breakout-rooms

**Comment by heikar** [comment]
Hi,

at first @puthli  many thanks for share this valuable solution :)

But, i, and i think many others, do not use docker and run jitsi meet directly.
So @saghul are there plans to implement/merge the solution into jitsi meet?

**Comment by saghul** [comment]
No plans at the moment.

**Comment by saghul** [comment]
FYI: https://jitsi.org/blog/winning-over-the-classroom-with-jitsi/

**Comment by manouchk38** [comment]
This feature is very important for online teaching. As waja said "breakout rooms are the most missed feature in context of (home)schooling actually". Without that, lessons are liveless. It is really a must have but it may not be sufficient. Breakout room without whiteboard are though quite useless for teaching. ANd all whiteboard should be watchable at least by the teacher and the teacher should be able to share whiteboard after closing breakout rooms to allow for presentations and discussions.

**Comment by saghul** [comment]
Projects are not limited to the proposed challenges. Participants are welcome to work on any project so long as it's education related.

**Comment by awlx** [comment]
> FYI: https://jitsi.org/blog/winning-over-the-classroom-with-jitsi/

Very nice! Thanks for keeping up the great work.

**Comment by aspiers** [comment]
Yeah this is awesome, exactly what the project needs!  Congrats on securing the sponsorship!

**Comment by manouchk38** [comment]
Perfect! They are really many things needed for teaching like broadcasting
audio in all breakout rooms for the teacher. For the white some interesting
ideas are implemented in whiteboard.fi. The teacher can monitor all
whiteboard and save them... An interface to monitor whiteboard could be an
important possibility that mimics conventional lesson using portable small
whiteboard. Well, I don't know if it's the correct discussion to develop
this discussion. I hope I did not extrapolate the scope of this discussion.

**Comment by tremby** [comment]
> broadcasting audio in all breakout rooms for the teacher

Broadcasting text would also be valuable.

**Comment by manouchk38** [comment]
Le ven. 9 avr. 2021 à 00:17, Bart Nagel ***@***.***> a écrit :

> broadcasting audio in all breakout rooms for the teacher
>
> Broadcasting text would also be valuable.
>
For, sure!

There is a very interesting extension of google meet which have many
interesting features and solutions that may be interesting.
https://chrome.google.com/webstore/detail/google-meet-breakout-room/kogfdlbehkaeoafmgaecphlnhohpabig

Some of the features of this extension are:

1) View all breakout rooms together in Tile or Tab format
2) Single click to move slide between rooms (for teacher)
3) Assign breakouts in either ad hoc or preassigned mode
4) Broadcast audio and video into all of the breakout rooms
5) Customize colors for Meet bottom toolbar
7) Basic reports for attendance, breakout groups, participant group
assignments, etc

Many teachers seems to have used this successfully.

**Comment by wardnath** [comment]
For anyone arriving at this issue, here is a work in progress PR for breakout rooms:
https://github.com/jitsi/jitsi-meet/pull/9131

**Comment by briancleland** [comment]
Great work on this PR. Do we know when it is likely to be merged into the master branch?

**Comment by jbg** [comment]
The successor PR [has been merged](https://github.com/jitsi/jitsi-meet/pull/10170)!

**Comment by saghul** [comment]
Oops, forgot to close this one indeed!
