### ISSUE TITLE
New Debian 10 / Virtualmin / Nginx install - unable to locate package jitsi-meet with --no-install-recommends 

### ISSUE THREAD

**Issue by oneearth27** [jitsi/jitsi-meet#5551]
## Description
Hi,
I have a fresh install of Debian 10 / Virtualmin / Nginx on a server and noticed the instructions are to skip turnserver configuration (whatever that is) if Nginx is listening on port 443. So I used that command but got:

<div>root@love:~# apt install --no-install-recommends jitsi-meet<br/>
Reading package lists... Done<br/>
Building dependency tree  <br/>     
Reading state information... Done<br/>
E: Unable to locate package jitsi-meet<br/>
root@love:~#
</div>

---
## Current behavior
<p style="font-weight:normal;">Unable to install jitsi-meet</p>
---

## Expected Behavior
<p style="font-weight:normal;">Install jitsi-meet on Nginx Debian Virtualmin</p>
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details

Here's some other info on the system:

<div>root@love:~# cat /etc/apt/sources.list.d/jitsi-stable.list<br/>
deb https://download.jitsi.org stable/
</div>
<p/>
<div>root@love:~# netstat -tunlp<br/>
Active Internet connections (only servers)<br/>
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name <br/>   
tcp        0      0 my.debian10.virtualmin.ip:443      0.0.0.0:*               LISTEN      3404/nginx: master  
</div>
---

**Comment by oneearth27** [comment]
I tried the install command with apt-get and that did the trick:

 apt-get install --no-install-recommends jitsi-meet

**Comment by saghul** [comment]
That is unexpected!
