### ISSUE TITLE
Phone-in support for Austria and Italy

### ISSUE THREAD

**Issue by lanzanasto** [jitsi/jitsi-meet#5552]
Do you plan a phone-in support for Austria and Italy? We are a team in Austria, Italy and Switzerland and would love to use jitsi.

**Comment by marius-bardan** [comment]
@lanzanasto are you referring to mobile apps or opening a Jitsi meeting from a mobile browser? If the latter, the this might help: https://github.com/jitsi/jitsi-meet/pull/3518

**Comment by lanzanasto** [comment]
I meant the possibility to dial in with an ordinary phone.
![Screenshot_20200401_225507_com android chrome](https://user-images.githubusercontent.com/1436982/78185841-ff31d500-746b-11ea-9c9c-26e721e7c4a6.jpg)

**Comment by eknoes** [comment]
This is already possible if you self-host it, but I think for your issue you must ask 8x8 directly, they are hosting https://meet.jit.si as far as I know! In this repository it is about the software they use to provide the service, but anybody can just install it on their own server!

**Comment by eknoes** [comment]
The component providing SIP connect is called jigasi, you can find it in https://github.com/jitsi/jigasi. In jitsi meets quick install guide the SIP setup is included: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#adding-sip-gateway-to-jitsi-meet
