### ISSUE TITLE
Cant connect any other

### ISSUE THREAD

**Issue by mirecta** [jitsi/jitsi-meet#5557]
i started Quick install (from the start)
but after create room and try conenct another client (mobile phone) everything wall down and in logs is 
jvb.log
`2020-04-01 23:08:11.815 INFO: [27] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-04-01 23:08:11.815 SEVERE: [27] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
`
jicofo.log
`Jicofo 2020-04-01 23:18:35.321 INFO: [207] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().401 Focus request for room: miro@conference.meet.talasek.sk
Jicofo 2020-04-01 23:18:35.499 INFO: [192] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@5855031a member=ChatMember[miro@conference.meet.talasek.sk/012a8fec, jid: null]@1079296565]
Jicofo 2020-04-01 23:18:35.499 INFO: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member miro@conference.meet.talasek.sk/012a8fec joined.
Jicofo 2020-04-01 23:18:35.500 WARNING: [192] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-04-01 23:18:35.500 SEVERE: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-04-01 23:18:35.500 WARNING: [192] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-04-01 23:18:35.501 SEVERE: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-04-01 23:18:35.867 INFO: [192] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@5855031a member=ChatMember[miro@conference.meet.talasek.sk/c6fafa47, jid: t1jkkbikofyorai9@meet.talasek.sk/N0ZEPL8z]@448329796]
Jicofo 2020-04-01 23:18:35.867 INFO: [192] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2020-04-01 23:18:35.872 INFO: [192] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to miro@conference.meet.talasek.sk/012a8fec
Jicofo 2020-04-01 23:18:35.873 INFO: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member miro@conference.meet.talasek.sk/c6fafa47 is leaving
Jicofo 2020-04-01 23:18:35.873 INFO: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, miro@conference.meet.talasek.sk/c6fafa47
Jicofo 2020-04-01 23:18:36.547 INFO: [192] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@5855031a member=ChatMember[miro@conference.meet.talasek.sk/012a8fec, jid: a0s-2xeezm0ys2wb@meet.talasek.sk/e-h2oQg0]@1079296565]
Jicofo 2020-04-01 23:18:36.547 INFO: [192] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2020-04-01 23:18:36.547 INFO: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member miro@conference.meet.talasek.sk/012a8fec is leaving
Jicofo 2020-04-01 23:18:36.547 INFO: [192] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, miro@conference.meet.talasek.sk/012a8fec
Jicofo 2020-04-01 23:18:36.555 INFO: [192] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: miro@conference.meet.talasek.sk conference count: 0
`

and yes my password in config /etc/jitsi/jicofo/config
JICOFO_AUTH_PASSWORD and in /var/lib/prosody/<domain>/accounts/focus.dat perfectly match 
so where is the problem

**Comment by ljo** [comment]
@mirecta Did you also check the password for jvb? The jvb.dat file is in the same directory as focus.dat.

**Comment by saghul** [comment]
Looks like the JVB password might be wrong. We've had some problems with the latest stable packages, can you please reinstall ?

**Comment by cweiske** [comment]
I had to fix the xmpp password in `/etc/jitsi/videobridge/sip-communicator.properties` to the one stored in the prosody user SQL database. With that it worked again.

**Comment by alorson** [comment]
> I had to fix the xmpp password in `/etc/jitsi/videobridge/sip-communicator.properties` to the one stored in the prosody user SQL database. With that it worked again.

Hi, can you kindly share exact steps? which you did please? I don't understand the Solution yet. 
Thank you in advance

**Comment by mirecta** [comment]
> @mirecta Did you also check the password for jvb? The jvb.dat file is in the same directory as focus.dat.
in dat file i see 
`accounts/jvb.dat 
return {
        ["password"] = "ok";
};
`
and in jvb config is /etc/jitsi/videobridge/config 
`JVB_SECRET=0ya1rJN2
`
it must be same too ?

**Comment by mirecta** [comment]
Solved if i write ok to jvb config as JVB_SECRET it doesnt work but if i wrote 0ya1rJN2 into jvb.dat config it works perfectly

**Comment by mirecta** [comment]
it is work

**Comment by dandrzejewski** [comment]
I think I experienced this issue because the first character of the password was a "#" which is not good in .properties files.  I changed that character to something else and it started working.
