### ISSUE TITLE
Request for documentation: Connecting to Jitsi from a node.js application.

### ISSUE THREAD

**Issue by JamesNewton** [jitsi/jitsi-meet#5559]
**Is your feature request related to a problem you are facing?**

We are attempting to add support for Jitsi to a FOSS (Free Open Source Software) robot control IDE so that robots can be controlled in Jitsi calls for remote access and collaboration. This will enable [remote medical treatment](https://twitter.com/HDRobotic/status/1241808643072262144) or other similar applications over the internet with our [FOSS robot arm](https://github.com/HaddingtonDynamics) and may well save lives.

So far, after reading the (massive) xmpp spec and the (massive) documentation available for Stroph.js, (we can't find any documentation on how to connect to Jitsi, but we've spent hours searching and reading through the repo) and trying what seems like hundreds of different things, this is as far as we have been able to get. When we run the code below, we get 

1 CONNECTING
3 AUTHENTICATING
2 CONNFAIL
6 DISCONNECTED

```
var conn = new Strophe.Connection("https://meet.jit.si/http-bind")
conn.connect('massmind@meet.jit.si/cfry', //fake jid, that's ok right?
             "", //don't need password?
             function(status_code) { //status_code is a small non-neg integer
                   console.log("connected with status: " + status_code + " " + strophe_status_code_to_name(status_code))
             }) 

```

**Describe the solution you'd like**

We are requesting additional documentation / example code (especially in node.js) for how to connect to Jitsi from an external application. Any help would be deeply appreciated. We think the issue has to do with how Jitsi avoids authentication? Uses do NOT need to sign up, but somehow the meet.jit.si server is requiring us to authenticate.

**Describe alternatives you've considered**

We have posted a request on the community and have recieved a few responses, but our progress there appears to have stopped. 
https://community.jitsi.org/t/inserting-locally-connected-device-data-into-chat/24118

We have posted again today, but don't hold out much hope of resolving this issue there:
https://community.jitsi.org/t/authentication-fail-on-connect-but-jitsi-doesnt-require-authorization/28566

**Comment by jandrieu** [comment]
Try lib-jitsi-meet https://github.com/jitsi/lib-jitsi-meet

Looks solid, but I haven't tried it yet. I found it in the same search that led to your initial post here.

**Comment by JamesNewton** [comment]
Sadly, the system expects chat messages to come through a browser interface only. Even in their app, they use a browser object inside electron. There may be some way to send chat messages (containing non-video / audio data) but we couldn't find it after hours and hours of looking. We rolled our own system using BOSH on a free google server:
https://github.com/HaddingtonDynamics/Dexter/issues/31#issuecomment-633180367

**Comment by satendrasingh51** [comment]
How to manage jitsi in node js
