### ISSUE TITLE
Allow full automation for apt installer via environment variable for hostname

### ISSUE THREAD

**Issue by sventropy** [jitsi/jitsi-meet#5563]
**Is your feature request related to a problem you are facing?**
When installing jitsi on a fresh ubuntu server via apt-get, there is no possibility to feed the hostname in a way that would allow automation, i.e. the user running the apt command has to enter the host name (described [here](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md)).

**Describe the solution you'd like**
I would love to have a way to automate the entire process as I tried to achieve [here](https://github.com/sventropy/digitalocean-jitsi), to give non-tech-savy people a simple 1-click installer without a command line interface to setup infrastructure and run digital ocean on it. IMHO an environment variable for the hostname, checked during installation would be the ideal solution. 

**Describe alternatives you've considered**
A config file entry might also be one of the obvious choices, however this would be less flexible compared to an environment variable, because the config file has to be copied to the correct location after being modified with the correct host name value (two steps) compared to a simple environment variable (one step).

**Offtopic**
Thanks for the effort everyone put into this project 💜

**Comment by Syonyk** [comment]
The hostname needs to be properly configured on the host to start with for Jitsi - perhaps one could chain off that and warn if it's not a FQDN.

**Comment by obfusk** [comment]
`apt`/`dpkg` allows you to set `debconf` configuration values before installing.

You can use `debconf-get-selections` (from the `debconf-utils` package) to look at the configuration of an existing installation:

```sh
$ debconf-get-selections | grep example.com
jitsi-meet-turnserver   jitsi-meet-turnserver/jvb-hostname      string  jitsi.example.com
jitsi-meet-prosody      jitsi-meet-prosody/jvb-hostname string  jitsi.example.com
jicofo  jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-prosody      jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-turnserver   jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-web-config   jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-videobridge2      jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-web-config   jitsi-meet/jvb-hostname string  jitsi.example.com
```

And use `debconf-set-selections` to provide those values before doing a noninteractive installation:

```sh
$ cat << EOF | debconf-set-selections
jitsi-meet-turnserver   jitsi-meet-turnserver/jvb-hostname      string  jitsi.example.com
jitsi-meet-prosody      jitsi-meet-prosody/jvb-hostname string  jitsi.example.com
jicofo  jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-prosody      jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-turnserver   jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-web-config   jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-videobridge2      jitsi-videobridge/jvb-hostname  string  jitsi.example.com
jitsi-meet-web-config   jitsi-meet/jvb-hostname string  jitsi.example.com
EOF
$ export DEBIAN_FRONTEND="noninteractive"
$ apt install jitsi-meet
```

NB: I haven't tested which specific values you'd need to set for jitsi, this is just an example.
