### ISSUE TITLE
usb 2.0 fhd uvc webcam no picture

### ISSUE THREAD

**Issue by geschke-eu** [jitsi/jitsi-meet#5569]
camera is only not recognized in jitsi
The camera light is on but there is no picture.
Camera is in a Phillips Brilliance499p
OS Mac 10.14.6
Chrome
Version 80.0.3987.149 (official build) (64-bit)

Kind regards
Tim

**Comment by geschke-eu** [comment]
camera works only in sd format

**Comment by awlx** [comment]
Works fine for me on MacOS 10.15.3 and latest Chrome. But there were some issues with 10.14.6 and Webcam Access with all Chrome Apps.

**Comment by freechelmi** [comment]
Please test your camera https://test.webrtc.org/ first

**Comment by Echolon** [comment]
@geschke-eu could you manage to test you camera?

**Comment by Echolon** [comment]
@geschke-eu please provide steps to reproduce. For the moment I will close this.
