### ISSUE TITLE
Documentation: add Firewall ports to be open for Firefox to work

### ISSUE THREAD

**Issue by rosa2** [jitsi/jitsi-meet#5571]
**Is your feature request related to a problem you are facing?**
I do face to face classes and with the Coronavirus I am trying open source video-conference programs. I have many problems with Firefox browsers and Jitsi, so I have been searching. I found 2 main reasons for Firefox no to work:

- Implementation of WebRTC that Firefox developers are fixing https://bugzilla.mozilla.org/buglist.cgi?status_whiteboard_type=substring&status_whiteboard=jitsi-meet&list_id=15179616

- Ports that are not open in the server (as in this article explained)
_Firewall: If her outgoing network connections with a desktop or Netzwerk-Firewall filter, you should release the ports TCP-443 (HTTPS) and UDP-10000 (video Stream)._
https://www.kuketz-blog.de/jitsi-meet-erste-hilfe-bei-problemen/

**Describe the solution you'd like**
For the second problem, please, add in your installation instructions to open those ports.
As for example in 
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

Also, find a way to tell people when they update their installation.

Thanks a lot for this great tool :)

**Comment by dbuenzli** [comment]
> For the second problem, please, add in your installation instructions to open those ports.

There's a patch [here](https://github.com/jitsi/jitsi-meet/pull/5469) for this which can be integrated by anyone who has signed the cla (I relinquish any rights on the content).

**Comment by rosa2** [comment]
Thanks a lot @dbuenzli and I understand why you don't sign a CLA. I too much prefer a CDO :)

**Comment by Syonyk** [comment]
I've created a new pull request using dbuenzli's changes, as I don't like the CLA but have signed it.
