### ISSUE TITLE
How to stop service when exit Picture in Picture mode 

### ISSUE THREAD

**Issue by react1ve** [jitsi/jitsi-meet#5573]
Hi!
When I Enter to PIP mode, according to sdk starts service to hold current video conference.
But when I hold pip layout and pull down to exit the service not stop and I have to stop it manually.

Is is possible to stop service after holding and pull down to exit pip layout>

**Comment by benaltair** [comment]
That is the case for me too. It feels unintuitive, and I've had calls persist after they were meant to be ended by dragging PIP down.

**Comment by TBG-FR** [comment]
Encountered the same issue, using the mobile SDK (versions 2.5.1 to 2.8.2).
This is a real issue, as the user stays connected (in call) while he thinks he left the call, by making the PIP disappear...

**Comment by saghul** [comment]
This is kinda by design. I don't know if there is a way to handle the X button press. If there is, terminating the call at that point should be fine indeed.
