### ISSUE TITLE
Impossibile attivare webcam

### ISSUE THREAD

**Issue by karl74na** [jitsi/jitsi-meet#5587]
Salve nonostante abbia dato i permessi alla webcam e al microfono non funziona.
Si accende il led della cam ma non parte.
Capita solo con jitsi.
Uso Chrome.

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
