### ISSUE TITLE
How to import Jitsi Meet Library to existing React App

### ISSUE THREAD

**Issue by codetestmg** [jitsi/jitsi-meet#5592]
Thanks   for this library.
I have used this library in Android Native Java and it works pretty well.
But now i am looking to integrate this library with my existing react native project which is latest version.
I have searched ,many topic in forum(https://community.jitsi.org/) but not found sollution.
Also i have tried another wrapper for this library(https://github.com/skrafft/react-native-jitsi-meet) but its not have few latest features which this library has.

Is there any sample example ,how to integrate this library with existing react native library ?
Also is it possible to link android java native library to react native ? If so any sample example .
After two days of research i am posting this question here.Hope someone will help me to fix this.
Thank you

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet, as you already did, I would like to advise to discuss your topic here first: https://community.jitsi.org

I will close this for the moment, okay?

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
