### ISSUE TITLE
Meeting clock starting at one hour

### ISSUE THREAD

**Issue by gaael** [jitsi/jitsi-meet#5595]
## Bug discussion in the community
Community discussion in [this post](https://community.jitsi.org/t/elapsed-time-starts-at-one-hour-at-the-beginning-of-the-meeting/28337/7)

## Description
When creating a new meeting by entering it, the elasped time clock starts at one hour and goes on.

## Current behavior
When a new meeting is created by entering it, the elapsed time clock starts at one hour and goes on.

## Expected Behavior
The elapsed time clock should start at 00:00:00.

## Possible Solution
I have no idea.

## Steps to reproduce
On a Debian fresh install (without any web server), follow the [quick-install](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) instructions. When the Jitsi server is up and running, create a new room and look at the timer at the top of the page.

# Environment details
VPS (at OVH) - KVM OpenStack - Debian 10 (bare) - 1vCore - 2GB RAM - SSD20Go

**Comment by red-hood** [comment]
Same issue here, on Debian 10 at hetzner cloud server. Browser and server time zone are set to the same value.

**Comment by yodatak** [comment]
With application of this patch from the forum it's works now 
```
--- mod_conference_duration_component.lua.broken	2020-04-09 05:37:51.399803696 +0200
+++ mod_conference_duration_component.lua	2020-04-09 05:34:54.620984358 +0200
@@ -28,7 +28,7 @@
     if participant_count > 1 then
 
         if room.created_timestamp == nil then
-            room.created_timestamp = os.time(os.date("!*t")) * 1000; -- Lua provides UTC time in seconds, so convert to milliseconds
+            room.created_timestamp = os.time(os.date("*t")) * 1000; -- Lua provides UTC time in seconds, so convert to milliseconds
         end
 
         local body_json = {};
```

**Comment by CaptPicardFR** [comment]
Hi, 
I tried vim /usr/share/jitsi-meet/prosody-plugins/mod_conference_duration_component.lua  

edit : 

```
if` participant_count > 1 then

        if room.created_timestamp == nil then
            room.created_timestamp = os.time(os.date("!*t")) * 1000; -- Lua provides UTC time in seconds, so convert to milliseconds
        end
```
		
en 

 ```
if participant_count > 1 then

        if room.created_timestamp == nil then
            room.created_timestamp = os.time(os.date("!*t")) * 1000; -- Lua provides UTC time in seconds, so convert to milliseconds
            room.created_timestamp = os.time(os.date("*t")) * 1000; -- Lua provides UTC time in seconds, so convert to milliseconds
        end
```


```
systemctl restart jitsi-videobridge2.service
systemctl restart jicofo.service
```

but time start again at 1:00:00

Debian10

**Comment by damencho** [comment]
When you are doing changes to those modules you need to restart prosody.

**Comment by CaptPicardFR** [comment]
systemctl restart prosody.service = chain crash after connexion

```
systemctl restart prosody.service
systemctl restart jitsi-videobridge2.service
systemctl restart nginx.service
systemctl restart jicofo.service
```
= pb resolved !!! count ok !!! MANY THANKS

**Comment by 532910** [comment]
Same issue here, but "Meeting clock starting at timezone GMT offset hours".
Please update the title.

debian buster
jitsi-meet 2.0.4468-1
```
% date
Sat 18 Apr 19:16:07 MSK 2020
```
MSK is UTC+3 and jitsi meet shows +3 hours

**Comment by onlyyjc** [comment]
How to use mod_conference_duration_component.lua? Can I see your jitsi-meet.cfg.lua？

**Comment by 532910** [comment]
Mine? I've not modified it, just get it from the default deb package.

**Comment by pedro-nonfree** [comment]
Is this applied to stable jitsi version for debian? my debian still has `/usr/share/jitsi-meet/prosody-plugins/mod_conference_duration_component.lua` without this modification

```
# apt show jitsi-meet
Package: jitsi-meet
Version: 2.0.4468-1
```

**Comment by damencho** [comment]
You need to update to unstable to get this.

**Comment by pedro-nonfree** [comment]
@damencho aha, and when is going to be in the stable version? Thanks! (another way is to patch from our own, which in this case is simple)

**Comment by pedro-nonfree** [comment]
finally it's fixed in last stable version. Worked for me. cc @tmakarios @johnVels

**Comment by 532910** [comment]
I confirm it works fine now. Thank you, Ruben!
