### ISSUE TITLE
Jitsi Meet quick install instructions don't work any more

### ISSUE THREAD

**Issue by anvaruk** [jitsi/jitsi-meet#5596]
I have successfully deployed Jitsi Meet several times a week ago,  following  https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

but something is broken now,  nginx doesnt start (complaining about port, but its not used)
I use blank Ubuntu 18.04, without anything on it

![image](https://user-images.githubusercontent.com/2795267/78294574-82adfd80-7522-11ea-97c1-71054e1664ed.png)

**Comment by fwolfst** [comment]
We have seen the same, still debugging. /etc/hosts /etc/hostname might be cursed.

**Comment by sjjh** [comment]
> We have seen the same, still debugging. /etc/hosts /etc/hostname might be cursed.

unfortunately doesn't seem to be the culprit.
Vanilla Debian 10 here.

**Comment by damencho** [comment]
Have you tried with latest release(from today)? Should not have this problem. 
Otherwise, try deleting /etc/nginx/modules-enabled/60-jitsi-meet.conf and restart nginx.

**Comment by sjjh** [comment]
> Have you tried with latest release(from today)? Should not have this problem.

Used latest stable release, which does not work.
> Otherwise, try deleting /etc/nginx/modules-enabled/60-jitsi-meet.conf and restart nginx.

That works. thx. Will the (correct) file be re-enabled with the next update?

**Comment by anvaruk** [comment]
> Have you tried with latest release(from today)? Should not have this problem.

I was just following quick install instructions an hour ago

> Otherwise, try deleting /etc/nginx/modules-enabled/60-jitsi-meet.conf and restart nginx.
it helped, thanks!

**Comment by damencho** [comment]
The latest stable will scan enabled virtual hosts and if there is one with 443 enabled will skip configuring turnserver.

**Comment by damencho** [comment]
> > Have you tried with latest release(from today)? Should not have this problem.
> 
> I was just following quick install instructions an hour ago
> 
> > Otherwise, try deleting /etc/nginx/modules-enabled/60-jitsi-meet.conf and restart nginx.
> 
> it helped, thanks!

Hum, maybe it is not fully fixed in latest as the link will still be created 🤦‍♂

**Comment by realmrealm** [comment]
> Have you tried with latest release(from today)? Should not have this problem.
> Otherwise, try deleting /etc/nginx/modules-enabled/60-jitsi-meet.conf and restart nginx.

Can confirm this works (removing that file), also fixed letsencrypt cert issues. Tried setting up 3 seperate times before checking issues section. Thank you @damencho
