### ISSUE TITLE
Dial In Option Unusable Outside US, Also Can't use Standard Meeting Room Name

### ISSUE THREAD

**Issue by dbareis** [jitsi/jitsi-meet#5597]
**Is your feature request related to a problem you are facing?**
I currently can't schedule meetings without using the Chrome Extension, which means

    1. It can't have a standard name like "dbareis-class-android" which everyone knows.
    2. It can't use my meeting Text (no template support).
    3. It gives people a USA number (correct # not configurable, or detected), I'm in Australia, 
        and setting up a meeting using the otherwise each to use Jitsi is beyond my audience.
    4. Even the "+61" would confuse these guys, Ideally the whole number text is configurable 
        (all of them are local to Australia).

**Describe the solution you'd like**
    1. The dial-in PIN and its lifespan should be documented
    2. The PIN for the Meeting Room should be PREDICTABLE.  The easiest way of doing this 
        is to hash the meeting room name.  This may be too predictable for too short a meeting 
        room name, so would probably require a documented minimum length with shorter ones 
        unpredictable and padded with random characters.
    3. The phone text (or at least the phone number) needs to be configurable in the Chome 
        extension
    4. The text of the meeting invite needs to be configurable with perhaps "{Phone#.AU.LOCAL}" 
        used where I want a local AU number to be placed.
    5. Ideally it would support multiple templates with the correct one being asked for by the 
        extension.  The meeting room name should be associated with the template or if blank also 
        asked for.

**Describe alternatives you've considered**
Zoom, WebEx, not supporting dial-in in my meetings.

**Comment by Echolon** [comment]
rel. Phone-in support for Austria and Italy
#5552

**Comment by dbareis** [comment]
> rel. Phone-in support for Austria and Italy
> #5552

Just to clarify in case required my issues have nothing to do with adding phone support to new countries.  It's how "usefully" they are handled when they exist.

**Comment by dbareis** [comment]
Anyone? Not a hard fix...

**Comment by dbareis** [comment]
So it won't be fixed, that's great 👎
