### ISSUE TITLE
Documentation: how to update ssl certificate on jetty

### ISSUE THREAD

**Issue by triangle-stream** [jitsi/jitsi-meet#5599]
When installing jitsi-meet from apt install without a previous installation of nginx or apache, it would be nice to have some documentation (if it is not too difficult) on how to change a certificate inside jetty.

I ran in this issue because the first used certificate during meet installation was not correctly chained and the results are that is not possible to use the jitsi-meet android application (but you can use meet by using android chrome and forcing desktop view).
Now i have the right certificate but i'm not able to change jetty configuration, so i need to purge and reinstall meet (but, like me, a user could have spended so much time in changing prosody, videobridge and other configurations that this may lead to a really "hurting" procedure).

Thank you.

**Comment by swipswaps** [comment]
//this ^

**Comment by damencho** [comment]
Jetty is no longer used when installing or after upgrading.
