### ISSUE TITLE
Todas as transmissões estão atualmente ocupadas

### ISSUE THREAD

**Issue by tjunik** [jitsi/jitsi-meet#5600]
Estava tentando iniciar uma transmissão ao vivo pelo Youtube. Mas, infelizmente, deu esse erro:
"Todas as transmissões estão atualmente ocupadas"

**Comment by Echolon** [comment]
> All transmissions are currently busy
I was trying to initiate a live Youtube transmission. But, unfortunately, you made that mistake:
"All transmissions are currently busy."

@tjunik  No support forum, please review: https://community.jitsi.org/

@damencho  can be closed
