### ISSUE TITLE
SEM CONSEGUIR GRAVAR

### ISSUE THREAD

**Issue by PrLuizFernando** [jitsi/jitsi-meet#5602]
DIZ QUE TODAS AS GRAVAÇÕES ESTÃO OCUPADAS

**Comment by Echolon** [comment]
> UNABLE TO RECORD
SAYS ALL THE RECORDINGS ARE OCCUPIED

@PrLuizFernando  No support forum, please review: https://community.jitsi.org/

@damencho  can be closed
