### ISSUE TITLE
Cannot run locally (Chrome Privacy error)

### ISSUE THREAD

**Issue by mosesoak** [jitsi/jitsi-meet#5604]
## Description

Hello, I'm excited to be trying out Jitsi! Thanks for this amazing product.

My first task involves running this repo locally. After installing and doing `make dev` I see the following in Chrome – note that there's no bypass link given.

<img width="796" alt="Screen Shot 2020-04-02 at 2 45 20 PM" src="https://user-images.githubusercontent.com/24345/78305569-16b5a000-74f6-11ea-9fcb-cdbeecc38d19.png">

I don't know what the cert it's referring to might be, it has an expiration date of May 2020 and is not something in my keychain. When I click on the `NET::ERR_CERT_INVALID` it shows the key preceded by:

```
Subject: localhost
Issuer: localhost
Expires on: May 2, 2020
Current date: Apr 2, 2020
PEM encoded chain:
...
```
I tried generating a self-signed cert for `localhost` (I'm on macos), and setting it to always trust but it always shows this screen.

Note that I have other dev projects that run locally using https without any issue – this is a new one for me!

---

## Current behavior
Cannot view https://localhost:8080 despite Webpack working without any problems

```
./node_modules/.bin/webpack-dev-server
ℹ ｢wds｣: Project is running at https://localhost:8080/
ℹ ｢wds｣: webpack output is served from /libs/
ℹ ｢wds｣: Content not from webpack is served from /Users/moses/Documents/cloudengage/chord-video
```

---

## Expected Behavior
Can view https://localhost:8080

---

## Steps to reproduce
- clone repo
- `npm install`
- `make dev`
(I also tried running `make`)

---

## Environment details

Mac Catalina 10.15.2

**Comment by damencho** [comment]
@hristoterezov what was the workaround? 
@mosesoak this is a common thing and you can search for a resolution on Internet. We need to update the docs with that, it appeared with one of the latest versions of Chrome.

**Comment by mosesoak** [comment]
@damencho Thanks, I've been searching around – can you give me a little more info? Most of the posts I've found suggest making a self-signed cert, which didn't fix it.

**Comment by damencho** [comment]
In the Chrome address bar, type “chrome://flags/#allow-insecure-localhost“
Select the “Enable” link.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

**Comment by mosesoak** [comment]
Thanks for the info, @damencho, I will! And yes, a docs update on this would be fantastic, if it works out I'll provide a PR to make this issue worth your time. Thanks again
