### ISSUE TITLE
Can't install jitsi-meet-prosody 

### ISSUE THREAD

**Issue by TeoColuccio** [jitsi/jitsi-meet#5605]
I'm trying to install jitsi-meet on debian testing, but there's a strange error with jitsi-meet-prosody required by meet. I'm trying to install them through the official jitsi repo, but through .deb file it's exactly the same. I tried also to do a remove and purge all packages, for then reinstall it..
This is the output:

> sudo apt install jitsi-meet-prosody
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  jitsi-meet-prosody
0 upgraded, 1 newly installed, 0 to remove and 43 not upgraded.
Need to get 0 B/34.7 kB of archives.
After this operation, 177 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package jitsi-meet-prosody.
(Reading database ... 195549 files and directories currently installed.)
Preparing to unpack .../jitsi-meet-prosody_1.0.3962-1_all.deb ...
Unpacking jitsi-meet-prosody (1.0.3962-1) ...
Setting up jitsi-meet-prosody (1.0.3962-1) ...
The given hostname does not exist in the config
dpkg: error processing package jitsi-meet-prosody (--configure):
 installed jitsi-meet-prosody package post-installation script subprocess return
ed error exit status 1
Errors were encountered while processing:
 jitsi-meet-prosody
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

What can I do?

**Comment by damencho** [comment]
It must be some error with prosody. Can you check does prosody starts/stop/restart correctly?

**Comment by StephanEggermont** [comment]
It is a well known longer existing issue, pointed out by multiple people. There are lots of closed/wontfix issues here pointing out that the apt install and deinstall are broken.

**Comment by damencho** [comment]
@StephanEggermont please, we are trying to fix all issues we found. Believe me we had tested million times, but we cannot test all possible OS versions and combinations off packages. So when  we ask, this means we want to see what is the exact issue and as we are currently fixing other issues ... we can fix this or help user if its already use. 
And all this while trying to keep service running, and juggling million of issues, so be patient, please, we try as hard as possible.

**Comment by TeoColuccio** [comment]
> It must be some error with prosody. Can you check does prosody starts/stop/restart correctly?

Yes, if i do "sudo prosodyctl start/stop/restart" it works correctly

**Comment by TeoColuccio** [comment]
Any suggestion?

**Comment by TeoColuccio** [comment]
Update: I just tried on debian 10 stable and all works fine

**Comment by TeoColuccio** [comment]
Why closed? I just pointed out that on stable it works, but on testing it still doesn't work
