### ISSUE TITLE
jitsi

### ISSUE THREAD

**Issue by rpwulandr** [jitsi/jitsi-meet#5606]
why i cann't use my caamera when im login in my laptop

**Comment by xilentura** [comment]
Please give us some information about which browser and which operating system you use. Under Windows, you may need to adjust the security settings and allow your browser to access the camera. It works fine on Linux and on Windows with Firefox and Chrome.

**Comment by saghul** [comment]
Please see: https://github.com/jitsi/jitsi-meet/issues/5425
