### ISSUE TITLE
Current Jitsi Update overwrites NGNIX configuration

### ISSUE THREAD

**Issue by xilentura** [jitsi/jitsi-meet#5611]
## Description
After today's update the server was no longer able to output the page via HTTPS and threw the error that the page is not accessible. I have tested it on a recent Debian GNU/Linux 10 (buster) system with Kernel: 4.19.0-8-amd64 x86_64. I have previously made a change to the file /etc/nginx/conf.d/meet.mydomain.com.conf to make SSL under IPv4 and IPv6 work. 

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2; 
```

## Current behavior
Firefox 74.0 has been complaining that he can't find the site. A login via app was also not possible and was answered with a timeout. The file /etc/nginx/conf.d/meet.mydomain.com.conf changed after the update to:

```
server {
    listen 4444 ssl http2;
    listen [::]:4444 ssl http2; 
```

## Expected Behavior
Everything runs more smoothly or even more smoothly after the update.

## Possible Solution
Change file /etc/nginx/conf.d/meet.mydomain.com.conf to 

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2; 
```

back again and restart everything.

## Steps to reproduce
Update the same environment with the update from today.

# Environment details
Current  Debian GNU/Linux 10 (buster) 
Kernel: 4.19.0-8-amd64 x86_64
Jitsi-Meet full installation with stable [Jitsi repository](https://desktop.jitsi.org/Main/DebianRepository)
Tested with Android Jitsi Meet App from F-Droid and Firefox under Ubuntu 19.10

**Comment by saghul** [comment]
Did the update install a jitsi-meet-turnserver package?

**Comment by herrwusel** [comment]
It did for me. It overwrote my current turnserver.conf. Because of this I ran into quite some troubles but I could revert the changes.

**Comment by saghul** [comment]
What version of the packages do you have?

**Comment by damencho** [comment]
Latest packages will keep the original turnserver file as .bak one.

**Comment by herrwusel** [comment]
@saghul 
```bash
apt policy jitsi-meet
jitsi-meet:
  Installed: 1.0.4335-1
  Candidate: 1.0.4335-1
```

@damencho good to know. If I remember correctly it was configured to listen on port 443 as well which might be causing troubles for users installing it on a system with nginx, apache etvc.

**Comment by xilentura** [comment]
@saghul After some updates, configuration changes and so on, I found out that there was actually a turnserver installed which overwrote my configurations with port 443 to 4443 or 4444. After changing some configurations everything is working as expected now. It was just a bit difficult to understand this change, because the videobridge has also been changed to version two and caused some troubles.
