### ISSUE TITLE
Cannot gain access to microphone

### ISSUE THREAD

**Issue by kuba-orlik** [jitsi/jitsi-meet#5613]
## Description

When connecting to my self-hosted jitsi Meet via Firefox, the app can't get access to the microphone.

A popup is shown saying:

```
AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
```
I don't have this issue when connecting through the same browser to a different instance (I've tested jitsi.riot.im on Firefox and it doesn't show this error)

# Environment details

Firefox 75.0b10
Not sure how to check my version of jitsi, but I'm running `docker-jitsi-meet` on ebfa142d384466fefc7cd224cdca50df9cfe40c7, a commit from 2 days ago

**Comment by saghul** [comment]
@andrei-gavrilescu Does this ring any bell?

**Comment by andrei-gavrilescu** [comment]
Hello everyone. This doesn't reproduce on the release version of Firefox which is 74. However I did manage to reproduce on the beta version 75.|
It has to do with the audio processing we do for detecting speech using Web Audio, it looks like Firefox changed an API there, namely the expected PCM frequency when creating a media stream source `AudioContext.createMediaStreamSource()`. 
At this point idk if it's an easy fix, or something more complicated. Will investigate it.

**Comment by rosa2** [comment]
> Hello everyone. This doesn't reproduce on the release version of Firefox which is 74. However I did manage to reproduce on the beta version 75.|
> It has to do with the audio processing we do for detecting speech using Web Audio, it looks like Firefox changed an API there, namely the expected PCM frequency when creating a media stream source `AudioContext.createMediaStreamSource()`.
> At this point idk if it's an easy fix, or something more complicated. Will investigate it.

@andrei-gavrilescu any news about this? Thanks

**Comment by rosa2** [comment]
Related https://github.com/jitsi/jitsi-meet/issues/2835

**Comment by Ganonmaster** [comment]
Tested in Firefox 76.0b4 and can confirm that my microphone does not work at all. (sample-rate error as reported above) For now, I'm using Firefox ESR 68.7.0esr as a fallback and the microphone works fine there, although I can imagine that's not an option for everyone.

**Comment by rosa2** [comment]
> Tested in Firefox 76.0b4 and can confirm that my microphone does not work at all. (sample-rate error as reported above) For now, I'm using Firefox ESR 68.7.0esr as a fallback and the microphone works fine there, although I can imagine that's not an option for everyone.

Did you report in Firefox issue list? I saw several reports there. I have not idea if it is a bug from Jitsi or Firefox, but I think it is good that both check, don't you think it?

**Comment by andrei-gavrilescu** [comment]
Hello, after the investigation it turns out that a resampler is required to make this work in firefox, which is not trivial. It will be added after more urgent issues are taken care of.
From what I tested so far the error doesn't seem to affect the conference flow i.e. audio/video still work, however the talk while muted, and noise detection notification won't work.
Don't think it's related to https://github.com/jitsi/jitsi-meet/issues/2835 as the microphone not working might be something else.

**Comment by bwindels** [comment]
Fwiw, getting this error on Fedora 32 with Gnome 3.36.2 on Wayland, and Firefox 76.0.1 (64-bit)
