### ISSUE TITLE
http-bind responses with 404 (unknown host)

### ISSUE THREAD

**Issue by xentity** [jitsi/jitsi-meet#5616]
Hi there.

I installed Jitsi-Meet on a server behind a NAT firewall. The publicIP:443 is translated to an nginx reverse proxy, who directs everything with the public jitsi hostname to the local jitsi nginx. I double checked the http routing. UDP10000 is translated directly to Jitsi.

I can access the URL in the app or in the webinterface and I am prompted for a conference name. If I enter a conference, the message "connection interrupted" appears. The logs show me that there are requests to http-bind:
`"POST /http-bind?room=conftest HTTP/2.0" 404 393 "-" "okhttp/3.12.1"`

If I access the http-bind page, I get the message:
`404 Not Found

Whatever you were looking for is not here. It's behind you.

Unknown host: 192.168.5.70`

This IP is the local IP of the jitsi server. How can I fix it? Whom asks http-bind to get an answer? And what should be the desired output? AFAIK is this a reponse of the prosody service, but cannot find any hints for this issue in its log.

**Comment by saghul** [comment]
Looks like something is wrong in your proxying. This is how the http-bind should look like: https://meet.jit.si/http-bind

**Comment by xentity** [comment]
@saghul Thanks for your reply.

I guess, the proxying is working. This is from the nginx of the jitsi server:
`sysadmin@comm01:~$ sudo tail -f /var/log/nginx/access.log
192.168.5.61 - - [03/Apr/2020:12:22:34 +0200] "POST /http-bind?room=testconf HTTP/1.0" 404 401 "-" "okhttp/3.12.1"
192.168.5.61 - - [03/Apr/2020:12:32:06 +0200] "POST /http-bind?room=testconf HTTP/1.0" 404 396 "-" "okhttp/3.12.1"
192.168.5.61 - - [03/Apr/2020:12:32:37 +0200] "GET /config.js?room=testconf HTTP/1.0" 200 18376 "-" "okhttp/3.12.1"
192.168.5.61 - - [03/Apr/2020:12:32:37 +0200] "POST /http-bind?room=testconf HTTP/1.0" 404 401 "-" "okhttp/3.12.1"
192.168.5.61 - - [03/Apr/2020:13:02:29 +0200] "GET /http-bind HTTP/1.0" 404 401 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:02:30 +0200] "GET /sw.js HTTP/1.0" 200 35881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:02:33 +0200] "GET /http-bind HTTP/1.0" 404 393 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:02:34 +0200] "GET /sw.js HTTP/1.0" 200 35881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:02:34 +0200] "GET /http-bind HTTP/1.0" 404 401 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:02:35 +0200] "GET /sw.js HTTP/1.0" 200 35881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:55 +0200] "GET /ConfTest HTTP/1.0" 200 35881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:55 +0200] "GET /libs/do_external_connect.min.js?v=1 HTTP/1.0" 200 2406 "https://ctx.du-consult.de/ConfTest" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:55 +0200] "GET /libs/lib-jitsi-meet.min.js?v=3969 HTTP/1.0" 200 747804 "https://ctx.du-consult.de/ConfTest" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:55 +0200] "GET /libs/app.bundle.min.js?v=3969 HTTP/1.0" 200 2910076 "https://ctx.du-consult.de/ConfTest" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:56 +0200] "GET /sw.js HTTP/1.0" 200 35881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:57 +0200] "GET /images/favicon.ico?v=1 HTTP/1.0" 200 4286 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:57 +0200] "POST /http-bind?room=conftest HTTP/1.0" 404 396 "https://ctx.du-consult.de/ConfTest" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
192.168.5.61 - - [03/Apr/2020:13:03:58 +0200] "GET /sw.js HTTP/1.0" 200 35881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"`

You can see that the requests coming from the reverse proxy to the jitsi server. The http-bind requests are reponsed with 404. I know, how the page should look like, but what is my mistake to bring the page to that state?

**Comment by saghul** [comment]
Can you share your proxy config?

**Comment by xentity** [comment]
Of course:
```
server {
        listen 443 ssl http2;
        server_name ctx.domain.de;
        server_tokens off;

        proxy_headers_hash_max_size 1024;

        #resolver                  192.168.5.1 valid=300s;
        #resolver_timeout          10s;

        ssl    on;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;

        ssl_certificate /etc/letsencrypt/live/ctx.domain.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ctx.domain.de/privkey.pem;

        client_max_body_size 100M;

        location /_matrix {
                proxy_pass http://192.168.5.70:8008;
                proxy_set_header X-Forwarded-For \$remote_addr;
        }

        location /riot {
                index index.php index.html;
                root /var/www/riot/;
        }

        location / {
                proxy_pass https://192.168.5.70/;
                proxy_set_header X-Forwarded-For \$remote_addr;
        }
}
```

**Comment by xentity** [comment]
@saghul Damn it... the scales fell from my eyes. Solved it.

Jitsi expects to be called with the public/known host header:

```
        location / {
                proxy_pass https://192.168.5.70/;
                proxy_set_header X-Forwarded-For \$remote_addr;
                proxy_set_header Host $host;
        }
```
Now, nginx is copying the ctx.domain.de host header into the request to the upstream/jitsi server. Nice.
