### ISSUE TITLE
Quick Install doc is not working

### ISSUE THREAD

**Issue by sachin10101998** [jitsi/jitsi-meet#5617]
## Description
The quick install doc for meet is not working

## Current behavior
Entering sudo apt-get -y install jitsi-meet
returns E: Unable to locate package jitsi-meet

## Expected Behavior
It should continue with installation and ask fqdn details

## Possible Solution
---

## Screenshots

![Screenshot from 2020-04-03 16-49-32](https://user-images.githubusercontent.com/34926285/78355330-2357f800-75cb-11ea-9e09-398b6ca4316f.png)

# Environment details
Ubuntu 18.04

**Comment by deluxe2** [comment]
Did you enable the `universe` repositories like mentioned in the doc?

>On Ubuntu systems, Jitsi requires dependencies from Ubuntu's `universe` package repository. To ensure this is enabled, run `apt-add-repository universe` at the command-line.

**Comment by vincentjanv** [comment]
Did you add the package repository and performend an `apt-get update`?

**Comment by sachin10101998** [comment]
@vincentjanv yes I did. Still the error persists.

**Comment by saghul** [comment]
an you show us your jitsi-meet sources list file?

**Comment by sachin10101998** [comment]
@saghul am not sure what exactly you mean by sources list. I just followed the steps in quick install doc and got the error in very starting.

**Comment by saghul** [comment]
This file: /etc/apt/sources.list.d/jitsi-stable.list

**Comment by sachin10101998** [comment]
@saghul there is no list like jitsi-stable.list in the sources.list folder

**Comment by saghul** [comment]
Then you didn't run all the steps in the quick install. You are missing the Jitsi repository, hence your problem.

**Comment by sachin10101998** [comment]
@saghul solved. thanks for help. closing the issue.
