### ISSUE TITLE
Start in Audio-only

### ISSUE THREAD

**Issue by jorgedlcruz** [jitsi/jitsi-meet#562]
Hi, I can't find a way to start just an audio-only call, I know we can start with video, and then disable the camera, but for Audio Conferences where we start early on the morning, it will be much better to offer a way to do just an auto-only call.

**Comment by neo-inuit** [comment]
+1

**Comment by gpolitis** [comment]
As the moderator of the call you can configure the conference to start with audio only. Have you checked that out?
