### ISSUE TITLE
Freeing recording recourses

### ISSUE THREAD

**Issue by iEnrique** [jitsi/jitsi-meet#5622]
Hello, 

I am planning on using Jitsi Meet for my classes and recording them in order for students to be able to watch them later (especially those who are absent). Nevertheless, last time I tried it appeared a message saying that "All recorders were busy". Will that happen often? Are you working on a solution to avoid that from happening any time soon? 

I need to be able to rely on the platform to record my classes or otherwise I would have problems with students if I encounter that message whenever I am set to give an online class.

Thank you in advance.

![Captura de pantalla 2020-04-03 a las 14 59 52](https://user-images.githubusercontent.com/4863665/78363456-1089f700-75bc-11ea-8137-78bceaa85da8.png)

**Comment by saghul** [comment]
I just tested it andd it seems to be working fine here. We keep on improving the service, but we cannot guarantee that problems will never happen.

**Comment by iEnrique** [comment]
Alright, thank you. One question, the recordings are stored using the space in my DropBox, right? What happens if I run out of space while i am recording something, will it not get stored and desappear?

**Comment by saghul** [comment]
We estimate how much recoridng we can store, so you'll just not get it all. Alternatively you can use the live streaming feature with a YouTube private stream, this way you can download it from youtube later.
