### ISSUE TITLE
Remove Trackers from Android/iOS Apps

### ISSUE THREAD

**Issue by awlx** [jitsi/jitsi-meet#5623]
## Description
Google Analytics and various other trackers are included in the Android and iOS Version of the app. But not in the F-Droid version.

There is also no hint on the app that tracking is the case

See trackers here:
https://twitter.com/sayho/status/1244642096780324864?s=20

## Current behavior
Tracking is enabled and no feature to opt out

## Expected Behavior
Remove trackers completely or turn off by default.

Suspected iOS code:
https://github.com/jitsi/jitsi-meet/blob/master/ios/app/src/AppDelegate.m

**Comment by saghul** [comment]
Please see here: https://community.jitsi.org/t/ios-client-leaking-data-to-third-parties-without-user-consent/28767/2?u=saghul
