### ISSUE TITLE
List user accounts?

### ISSUE THREAD

**Issue by truelai** [jitsi/jitsi-meet#5625]
It seems that user management features are lacking or missing. In the documentation, I only find how to add a user:
`sudo prosodyctl register <my-username> <my-domain> <my-password>`

Looking from bash at the available commands, I see:
```
root@jitsi:~# sudo prosodyctl 
prosodyctl - Manage a Prosody server

Usage: /usr/bin/prosodyctl COMMAND [OPTIONS]

Where COMMAND may be one of:

 adduser JID
    Create the specified user account in Prosody

 passwd JID
    Set the password for the specified user account in Prosody

 deluser JID
    Permanently remove the specified user account from Prosody

 start
    Start Prosody

 stop
    Stop a running Prosody server

 restart
    Restart a running Prosody server

 reload
    Reload Prosody's configuration and re-open log files

 about
    Show information about this Prosody installation

 cert config|request|generate|key
    Helpers for generating X.509 certificates and keys.

 status
    Reports the running status of Prosody
```

Is there a way to list users? If not, this should be a feature for obvious reasons.

**Comment by damencho** [comment]
Please when having questions or problems use the community forum before opening new issues.

You can go to the prosody site and send the request there, it is out of our control.
As a workaround all users are stored in /var/lib/prosody
