### ISSUE TITLE
quick install - error message : videobridge unavailable

### ISSUE THREAD

**Issue by Miroslav36** [jitsi/jitsi-meet#563]
Hello,

I have followed the quick install procedure, but I always get the error message about the videobridge not being available.
I have tried a conference with an other particpant, we can only see our own video, not each other.
I am running a freshly installed server with : debian 8, nginx.
Did an apt-get update and upgrade.
Other functions seem to work : chat works, I can see other participants.

Should I start a service or check something before using jitsi-meet ?

Thank you for your help.

**Comment by wweich** [comment]
I had this problem all the time after a jitsi-meet update a while back.. My workaround was to revert back to versions `jisti-meet 1.0.722-1`, `jitsi-videobridge 557-1` and stay there. But after the last kernel update of my Ubuntu 14.04 server `3.16.0.67.58 => 3.16.0.69.60` I get this error even with those versions.
Reverting the VM back to before the kernel update "fixed" the problem for me for now.

**Comment by aamoyg** [comment]
I'm having the same issue-- quick installed on Ubuntu 16.04 LTS, and I'm just getting a gray screen. It seems like the videobridge is not starting.
