### ISSUE TITLE
Unable to contact camera

### ISSUE THREAD

**Issue by pcchynoweth** [jitsi/jitsi-meet#5633]
Running Chromium
peter@peter-Inspiron-545:~$ uname -a
Linux peter-Inspiron-545 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

peter@peter-Inspiron-545:~$ inxi
CPU: Quad Core Intel Core2 Quad Q9400 (-MCP-) 
speed/min/max: 1995/1998/2664 MHz Kernel: 5.3.0-45-generic x86_64 
Up: 2d 2h 09m Mem: 2209.7/5935.4 MiB (37.2%) Storage: 2.96 TiB (28.1% used) 
Procs: 246 Shell: bash 4.4.20 inxi: 3.0.32 
peter@peter-Inspiron-545:~$ 

peter@peter-Inspiron-545:~$ chromium-browser --version
Using PPAPI flash.
Chromium 80.0.3987.149 Built on Ubuntu , running on LinuxMint 19.3
peter@peter-Inspiron-545:~$ 

When I use Firefox I get a Browser warning, but the camera works - but Meet in general is extremely laggy.

When I use Chromium it can't find my camera. See attached screenshots. It recognizes the camera but I can't switch to it. It defaults to the Hauppauge TV card that is installed. 

![Screenshot from 2020-04-03 13-27-44](https://user-images.githubusercontent.com/97002/78397987-82a80f00-75af-11ea-8194-5d4983d720cc.png)
![Screenshot from 2020-04-03 13-28-12](https://user-images.githubusercontent.com/97002/78397989-8340a580-75af-11ea-893e-d7e15aaf80a6.png)
![Screenshot from 2020-04-03 13-28-28](https://user-images.githubusercontent.com/97002/78397990-83d93c00-75af-11ea-8911-1e5b11524ba3.png)
![Screenshot from 2020-04-03 13-28-59](https://user-images.githubusercontent.com/97002/78397992-8471d280-75af-11ea-9f52-c81f68bc49f7.png)

I would really like to get away from using proprietary Zoom, but right now, even though this looks promising, it is not good enough for me to recommend.

Peter Chynoweth

**Comment by Echolon** [comment]
Non-working camera meta-issue #5425
@damencho
