### ISSUE TITLE
prosodyctl register undocumented?

### ISSUE THREAD

**Issue by solick** [jitsi/jitsi-meet#5635]
Hi i am wondering why prosodyctl register is an undocumented option. 
prosodyctl --help does not show up with any hint.

I came up with this because i was searching how to edit the user which will be registered as organisator. 

Has anyone a hint why this is used but undocumented?

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

Maybe that one is not available in the prosody version you use?
