### ISSUE TITLE
iOS Safari cannot open Jitsi Meet welcome page

### ISSUE THREAD

**Issue by dpoon** [jitsi/jitsi-meet#5649]
## Description

When trying to open the Jitsi Meet welcome page (the page that presents random words as meeting names) in Safari (on iOS 12.4.1), an error occurs:

> Safari cannot open the page because the network connection was lost.

However, Safari 13.1 on macOS 12.15.4 is able to load the page.

---

## Analysis

The problem is that nginx proxies the browser's HTTPS to the TURN server at `127.0.0.1:4445`, which balks and responds with a TCP RST.

The problem is in `/etc/nginx/modules-enabled/60-jitsi-meet.conf`, which incorrectly maps the browser's HTTP/2 request to port 4445, rather than 4444:

https://github.com/jitsi/jitsi-meet/blob/c73ba372022db0bb967d628b136934219d8c4fec/doc/debian/jitsi-meet/jitsi-meet.conf#L6-L18

Safari on iOS sends the following ALPN within the TLS Client Hello:

```
Extension: application_layer_protocol_negotiation (len=48)
  Type: application_layer_protocol_negotiation (16)
  Length: 48
  ALPN Extension Length: 46
  ALPN Protocol:
    ALPN string length: 2
    ALPN Next Protocol: h2
    ALPN string length: 5
    ALPN Next Protocol: h2-16
    ALPN string length: 5
    ALPN Next Protocol: h2-15
    ALPN string length: 5
    ALPN Next Protocol: h2-14
    ALPN string length: 8
    ALPN Next Protocol: spdy/3.1
    ALPN string length: 6
    ALPN Next Protocol: spdy/3
    ALPN string length: 8
    ALPN Next Protocol: http/1.1
```

The [nginx documentation](https://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html) says:

> **`$ssl_preread_alpn_protocols`**  
> list of protocols advertised by the client through ALPN (1.13.10). The values are separated by commas.

… so `$ssl_preread_alpn_protocols` has the string value `h2,h2-16,h2-15,h-14,spdy/3.1,spdy/3,http/1.1`, which is not an exact string match for any of the three values that would map the request to port 4444.  Therefore, it maps to port 4445.

The correct configuration is to use regex matching:

> ```
>     map $ssl_preread_alpn_protocols $upstream {
>         ~\bh2\b         web;
>         ~\bhttp/1.1\b   web;
>         default         turn;
>     }
> ```

---

# Environment details

Server: Ubuntu 18.04.4 with [jitsi-meet-2.0.4384-1](https://download.jitsi.org/stable/jitsi-meet_2.0.4384-1_all.deb), [jitsi-meet-turnserver-1.0.3969-1](https://download.jitsi.org/stable/jitsi-meet-turnserver_1.0.3969-1_all.deb), [jitsi-meet-web-config-1.0.3969-1](https://download.jitsi.org/stable/jitsi-meet-web-config_1.0.3969-1_all.deb)

Client: Safari on iOS 12.4.1

---

**Comment by mwarnaar** [comment]
Using the exact same setup, Server: Ubuntu 18.04.4 with jitsi-meet-2.0.4384-1, jitsi-meet-turnserver-1.0.3969-1, jitsi-meet-web-config-1.0.3969-1, nginx version: nginx/1.14.0 (Ubuntu)

All requests are forwarded to the `turn` upstream, regardless of browser, with `/etc/nginx/modules-enabled/60-jitsi-meet.conf` containing the following:
```
# this is jitsi-meet nginx module configuration
# this forward all http traffic to the nginx virtual host port
# and the rest to the turn server

stream {
    upstream web {
        server 127.0.0.1:4444;
    }
    upstream turn {
        server 127.0.0.1:4445;
    }
    # since 1.13.10
    map $ssl_preread_alpn_protocols $upstream {
        ~\bh2\b         web;
        ~\bhttp/1\.     web;
        default         turn;
    }

    server {
        listen 443;
        listen [::]:443;

        # since 1.11.5
        ssl_preread on;
        proxy_pass $upstream;

        # Increase buffer to serve video
        proxy_buffer_size 10m;
    }
}
```

**Comment by damencho** [comment]
@mwarnaar Wasn't there a PR for that?

**Comment by damencho** [comment]
O there is and is merged and will be available on next stable release. Which will be by the end of the week. https://github.com/jitsi/jitsi-meet/pull/5651

**Comment by mwarnaar** [comment]
Indeed, that's the configuration with the `map $ssl_preread_alpn_protocols $upstream` block from that merge request. The problem still occurs while using it.

**Comment by damencho** [comment]
Hum, this means that Safari is not setting ALPN for web traffic, I wild guess.

**Comment by dpoon** [comment]
What version of Safari are you using that is has that behaviour, @mwarnaar?

**Comment by mwarnaar** [comment]
It happened in any browser. In the end the removing `coturn` and `jitsi-meet-turnserver` packages resolved this issue.

Since the syntax/changes of https://github.com/jitsi/jitsi-meet/pull/5651 is much like the examples mentioned in http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html,  the configuration is probably correct.

**Comment by sneakyx** [comment]
Same here, it happens also in every browser, it doesn't work with
```
       ~\bh2\b         web;
        ~\bhttp/1.1\b   web;
        default         turn;
```

 I can get it only to get running by 
`default web;`

**Comment by istvan-berenyi** [comment]
Hi,

I’m on the latest Jitsi and still having the same issue.
jitsi-meet/stable,now 2.0.4416-1 all [installed]
jitsi-meet-prosody/stable,now 1.0.3992-1 all [installed,automatic]
jitsi-meet-turnserver/stable,now 1.0.3992-1 all [installed,automatic]
jitsi-meet-web/stable,now 1.0.3992-1 all [installed,automatic]
jitsi-meet-web-config/stable,now 1.0.3992-1 all [installed,automatic]
jitsi-videobridge2/stable,now 2.1-169-ga28eb88e-1 all [installed,automatic]
libnginx-mod-http-geoip/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 amd64 [installed,automatic]
libnginx-mod-http-image-filter/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 amd64 [installed,automatic]
libnginx-mod-http-xslt-filter/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 amd64 [installed,automatic]
libnginx-mod-mail/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 amd64 [installed,automatic]
libnginx-mod-stream/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 amd64 [installed,automatic]
nginx/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 all [installed]
nginx-common/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 all [installed,automatic]
nginx-core/bionic-updates,bionic-security,now 1.14.0-0ubuntu1.7 amd64 [installed,automatic]

/etc/nginx/modules-enabled/60-jitsi-meet.conf
map $ssl_preread_alpn_protocols $upstream {
~\bh2\b web;
~\bhttp/1. web;
default turn;
}
nginx error: 2020/04/16 18:21:34 [error] 917#917: *14462 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: {redacted_ip} , server: 0.0.0.0:443, upstream: “127.0.0.1:4445”, bytes from/to client:723/3632, bytes from/to upstream:3632/124

for good measure i’ve tried with these setting too:
map $ssl_preread_alpn_protocols $upstream {
~\bh2\b web;
~\bh2c\b web;
~\bhttp/1.1\b web;
~\bh2,http/1.1\b web;
~\bh2c,http/1.1\b web;
default turn;
}

But exactly the same results.

Safari Google chrome on some mac does not work, everywhere else does.

Any help please???

Thanks,

Istvan

**Comment by fritzfr** [comment]
>The correct configuration is to use regex matching:

    map $ssl_preread_alpn_protocols $upstream {
        ~\bh2\b         web;
        ~\bhttp/1.1\b   web;
        default         turn;
    }

This blocks things like Postman or a simple http request using fetch from accessing the web stuff too. Noticed this while trying to expose a prosody plugin through nginx proxy_pass (https://community.jitsi.org/t/nginx-proxy-pass-for-muc-size-working-in-browser-but-not-postman/57805/2).
