### ISSUE TITLE
Change default text about "full encryption"

### ISSUE THREAD

**Issue by infosec-handbook** [jitsi/jitsi-meet#5659]
**Is your feature request related to a problem you are facing?**
The default landing pages of Jitsi instances currently state "In fact, invite everyone you know. {{app}} is **a fully encrypted**, 100% open source video conferencing solution that you can use all day, every day, for free — with no account needed." [Example](https://github.com/jitsi/jitsi-meet/blob/7321f706bb3dc48996b8f305cee8ba9603d532e7/lang/main-enGB.json#L689)

According to [your own GitHub repo](https://github.com/jitsi/jitsi-meet#security) and [this post](https://jitsi.org/news/security/), this isn't actually the case. 

- P2P calls are end-to-end encrypted after comparing and verifying fingerprints (and as long as the Jitsi Videobridge of the server isn't used). 
- Group calls via the Jitsi Videobridge aren't end-to-end encrypted. They are protected by transport encryption and decrypted on the Jitsi server. So the default text is misleading since there is no "full encryption" in this case.

**Describe the solution you'd like**
Change the default text to something like:

"In fact, invite everyone you know. {{app}} is a 100% open source video conferencing solution that you can use all day, every day, for free — with no account needed. **P2P calls are end-to-end encrypted, group calls are protected by transport encryption.**"

In addition, P2P calls are only E2E encrypted if they aren't use the Jitsi Videobridge. Only a suggestion, the final text could be much shorter. 

---
Besides, the same applies to https://jitsi.org/jitsi-meet/. Here it is stated: "Jitsi Meet is **a fully encrypted**, 100% open source video conferencing solution that you can use all day, every day, for free — with no account needed."

**Comment by ulab** [comment]
Technically one could discuss that "fully encrypted" does not pretend to mean "end to end encrypted". Everything that goes over the network still is "fully encrypted"?

But yeah, I can understand why people might say it is misleading.

**Comment by saghul** [comment]
Exactly. No unencrypted data is ever transported. So it’s fully encrypted in transit, and since nothing is stored at rest, that’s all there is to it. We are not saying it’s E2EE, because it’s not, yet.

**Comment by saghul** [comment]
Please see: https://jitsi.org/news/security/

**Comment by infosec-handbook** [comment]
@saghul 
Thanks for your quick reply.

>Exactly. No unencrypted data is ever transported. So it’s fully encrypted in transit, and since nothing is stored at rest, that’s all there is to it. We are not saying it’s E2EE, because it’s not, yet.

And this is the actual problem. The term "fully encrypted" suggests that nobody except the meeting participants can access audio and video.

According to your post on GitHub and the linked blog post, this isn't the case since everything is decrypted on the server. Even if the streams aren't written to permanent storage by default, it isn't fully secure. A server-side attacker can record streams due to missing encryption.

So you should at least clarify in the "fully encrypted" statements that this only applies to data in transit.

**Comment by kek-coin** [comment]
> Technically one could discuss that "fully encrypted" does not pretend to mean "end to end encrypted". Everything that goes over the network still is "fully encrypted"?

> No unencrypted data is ever transported. So it’s fully encrypted in transit, and since nothing is stored at rest, that’s all there is to it.

Fully encrypted != Fully encrypted *in transit*. That qualifier is non-trivial. You cannot omit it and argue that it still technically means the same, because it simply does not.

**Comment by infosec-handbook** [comment]
We started a [poll in the Fediverse](https://chaos.social/@infosechandbook/103944970662799856) (results will be automatically shown on April 8).

The preliminary results after the first 50 votes:

>If you read "fully encrypted solution," what is your understanding of "fully encrypted"? 
>For me, "fully encrypted" means …
>* … **end-to-end encryption. 76%**
>* … transport encryption. 6%
>* … full-disk encryption. 4 %
>* … (answer is a comment; most comments also assume that it means E2EE, or say it is marketing lingo).

The first results clearly show that "fully encrypted" is actually a misleading term.

**Comment by kek-coin** [comment]
As for why "fully encrypted in transit" is misleading, imagine a physical package containing some server hardware being sent from a manufacturer to a customer. Customers might care about security and request that the manufacturer sends servers in a locked box only for the customer to unlock and open it. One might call that "fully locked in transit".

Then imagine these boxes were opened, and re-locked in transport hubs. Would that still qualify as "fully locked in transit"? Technically when the boxes are opened they are temporarily not "in transit" as they are sitting in a transport hub waiting to be put onto the next leg of their trip to the customer.

**Comment by infosec-handbook** [comment]
@saghul 
It would be nice if you reconsider the request after [only 8% of 220 people](https://github.com/jitsi/jitsi-meet/issues/5659#issuecomment-609381827) understood "fully encrypted" as "means transport encryption." 

Contrary to this, 74% think that it means "end-to-end encryption" which is clearly not the case.

**Comment by sunjam** [comment]
I want to voice my support for clarifying exactly what you mean by "fully encrypted" as OP suggested.  Having to dig up this information on Github from community suggestions is not ideal, but the suggested solution is both reasonable and concise.  Thanks for considering!

**Comment by dpoon** [comment]
"P2P calls are end-to-end encrypted, group calls are protected by transport encryption" may intimidate casual users because it contains too much jargon. Furthermore, even that could be considered misleading, because two-party calls may fail to negotiate a direct peer-to-peer connection and fall back to being relayed through the bridge.

I'd suggest simply dropping the word "fully" from "fully encrypted".  No meaning would be lost, and it would no longer imply anything about the strength of the encryption system.  Anyone who wants to research the details can do so — but the front page is not the place for such details.

**Comment by sunjam** [comment]
> I'd suggest simply dropping the word "fully" from "fully encrypted". No meaning would be lost, and it would no longer imply anything about the strength of the encryption system. Anyone who wants to research the details can do so — but the front page is not the place for such details.

Good idea!  You could simply embed the security url directly into the word [encryption](https://jitsi.org/news/security/), because taking the time to read this blurb likely means you _do_ want to know: I count myself amongst this crowd. :). 

example:

Jitsi is an [encrypted](https://jitsi.org/news/security/), 100% open source video conferencing solution that you can use all day, every day, for free — with no account needed.
