### ISSUE TITLE
Can't share Okular presentation in meet.jit.si

### ISSUE THREAD

**Issue by raspatan** [jitsi/jitsi-meet#5660]
This is probably not related with you but let me try.

I use Okular to open pdfs (in Ubuntu 16.04). When I choose Presentation mode (an a new window is created with full screen), such new window is not available to share in meet.jit.si. Only the original one. Do you know how I can fix this?

**Comment by Echolon** [comment]
@raspatan have you tried this with another software, too?

**Comment by l3d00m** [comment]
Closing as no further feedback was given, feel free to reopen with more details if it still persists.
