### ISSUE TITLE
Jitsi is unable to access my camera and microphone

### ISSUE THREAD

**Issue by Angels-Santigosa** [jitsi/jitsi-meet#5663]
Hello,
I am trying to use Jitsi, and it is  is unable to access my camera and microphone, so I cannot talk/be seen during the meetings. I would like to ask for your support to find a solution. Thank you!

**Comment by ulab** [comment]
Please [go to the community](https://community.jitsi.org/c/users/7) for these kinds of questions. This is not a user support forum, but for reporting issues with the code.

That said: Check your operating systems app privacy settings (I heard about Win10 users with that issue) and/or check the small "lock" icon in your browsers address bar.

**Comment by dpoon** [comment]
Have you looked at #5425?

If that doesn't solve the problem, you'll need to provide details about your web browser and OS, because this sketchy bug report is not actionable.

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
