### ISSUE TITLE
original Apple iSight camera doesn't work with jit.si

### ISSUE THREAD

**Issue by czyz** [jitsi/jitsi-meet#5665]
I know it's 17-years-old, but I just tried plugging my old [Apple iSight camera](https://www.macworld.com/article/3018431/in-praise-of-the-glorious-wildly-over-engineered-isight-webcam.html) into a 2013 Mac Pro via a thunderbolt 2-to-firewire800 adapter, and it works in the Photo Booth app and FaceTime. Jit.si allows one to select the iSight camera and mic, but displays the input as black. No image.

But in the Jit.si settings panel, one can select the iSight camera and see a small preview image. So some part of jit.si is able to use the image from the camera, just not the video conferencing part.

This is probably not a high-priority issue, but it would be nice to be able to use this camera with jit.si rather than consign it to the dust heap. Since it's ancient, I wonder if it's just outputting a resolution or frame rate that jit.si doesn't support?

![image](https://user-images.githubusercontent.com/345036/78457391-a8402180-765e-11ea-85a8-e15c3b0934d9.png)

Tested in both Chrome "Version 84.0.4104.0 (Official Build) canary (64-bit)" and "Version 80.0.3987.149 (Official Build) (64-bit)" on macOS 10.14.6.

Thanks for developing jit.si, by the way.

**Comment by saghul** [comment]
@czyz Thanks for the report!

@jallamsetty1 This is what were talking about the other day. That camera cannot be opened with our constraints, but works without...

**Comment by saghul** [comment]
@czyz I found an old webcam and could reproduce the problem! Any chance you can test the following? (SomeRandomRoomNameToTest is a room name i just made up)

https://meet.jit.si/SomeRandomRoomNameToTest#config.constraints.video.aspectRatio=1.33

Then try to select your camera.

**Comment by czyz** [comment]
That worked!

Zach Fine
323.470.6969

**Comment by czyz** [comment]
It appears that in order for this to work, everyone in the chat has to also join with "#config.constraints.video.aspectRatio=1.33" added to their URL. So maybe a variety of cameras with different aspect ratios can't join a chat together?

**Comment by emninger** [comment]
Is it allowed to attach a similar (may be identical?) issue? If not, my excuses in addvance and feel free to cancel my posting.

Description: On an old Macbook (3,1, late 2007) which runs arch linux, i succeeded in getting to work the built-in iSight camera. It works with cheese and skypeforlinux flawlessly. But jitsi does not get access to the camera, neither in Chromium nor with the desktop client.

hwinfo tells this about the camera:
39: USB 00.0: 0000 Unclassified device
  [Created at usb.122]
  Unique ID: Zj8l.DGFUEkBH9kD
  Parent ID: pBe4.9T1GDCLyFd9
  SysFS ID: /devices/pci0000:00/0000:00:1d.7/usb2/2-4/2-4:1.0
  SysFS BusID: 2-4:1.0
  Hardware Class: unknown
  Model: "Apple Built-in iSight [Micron]"
  Hotplug: USB
  Vendor: usb 0x05ac "Apple, Inc."
  Device: usb 0x8501 "Built-in iSight [Micron]"
  Revision: "1.84"
  Driver: "uvcvideo"
  Driver Modules: "uvcvideo"
  Speed: 480 Mbps
  Module Alias: "usb:v05ACp8501d0184dcEFdsc02dp01ic0Eisc01ip00in00"
  Driver Info #0:
    Driver Status: uvcvideo is active
    Driver Activation Cmd: "modprobe uvcvideo"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #56 (Hub)

**Comment by saghul** [comment]
Does it work in https://test.webrtc.org ?

**Comment by emninger** [comment]
No, it does not. The error msg for Any resolution is:
[ FAILED ] getUserMedia failed with error: NotFoundError

**Comment by es20490446e** [comment]
Does it work on the "V4L test utility"?

**Comment by es20490446e** [comment]
Also if you enter in the Terminal:
`groups ${USER}`

"video" must be in the list.

**Comment by emninger** [comment]
It is. But curiously, on another Mac (iMac running manjaro i3 as well) it is not, the facetime webcam works, nevertheless ...

**Comment by saghul** [comment]
> No, it does not. The error msg for Any resolution is:
> [ FAILED ] getUserMedia failed with error: NotFoundError

Then you're out of luck I'm afriaid.

**Comment by es20490446e** [comment]
@saghul If it is working somewhere, and elsewhere it isn't, the error is fixable by somebody. The question is who, whose software is the cause.

**Comment by es20490446e** [comment]
Let me guess: fitsi uses Electron, Electron is based onChromium, and Chromium has a dedicated back-end for video management which doesn't use "Video For Linux" (V4L). While all the apps based on the latest are working.

If you confirm that's the case, then you should report to Chromium.

**Comment by emninger** [comment]
@saghul: Why, then, on this macbook i can use jitsi in firefox but not in chromium? The dedicated jitsi client (for linux: jitsi-desktop-bin) does not work as well (gives the same error as in Chromium).

**Comment by es20490446e** [comment]
Cause the dedicated Jitsi client is using Electron, which is a rebranded Chromium.

**Comment by saghul** [comment]
Exactly. If it doesn't work with test.webrtc.org then you should report it to Chromium since it's a bug in the browser, which sadly we cannot deal with since Jitsi just runs on top of it.

**Comment by emninger** [comment]
In any case thanks a lot for your help. I tried to tell it to the chromium people ...

**Comment by es20490446e** [comment]
@emninger Have a nice day 👍

**Comment by emninger** [comment]
For me and the mine, 08/05 will be a nice day forever :)
