### ISSUE TITLE
Allow jitsi-meet to run behind Cloudflare CDN

### ISSUE THREAD

**Issue by dane-stevens** [jitsi/jitsi-meet#5667]
Trying to use Cloudflare Access (https://teams.cloudflare.com/access) to limit access to my self-hosted Jitsi Meet server.

I want to run Cloudflare Access in front of Jitsi so that I can limit access to users from a specific email domain.

I have considered putting it behind a VPN. Since bandwidth is a big consideration, a VPN would create a bottleneck on our internet bandwidth. (Jitsi server is cloud hosted).

**Comment by dane-stevens** [comment]
I have successfully setup Jitsi using Cloudflare as my DNS provider (DNS only, Cloudflare proxy turned off).

As soon as I proxy through Cloudflare, I can no longer access the Jitsi server. 

nginx error log shows: 

2020/04/04 17:57:14 [error] 11262#11262: *1119 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 108.162.241.14, server: 0.0.0.0:443, upstream: "127.0.0.1:4445", bytes from/to client:2826/3608, bytes from/to upstream:3608/3080

**Comment by saghul** [comment]
This topic is better suited for our community forum, please open a discussion topic here: https://community.jitsi.org/

**Comment by ijt** [comment]
Thank you @dane-stevens for posting this. I was having the exact same problem for days.

**Comment by WissamAntoun** [comment]
I was able to make everything work for like 1 minute, and then all participants are kicked out of the room. with the same error as above.  I extended all timeouts on cloudflared and nginx and still i get the same issue

**Comment by damencho** [comment]
Are you using websockets? Have you configured websocketKeepAliveUrl?

**Comment by aaronkvanmeerten** [comment]
Just FYI the proxy through cloudflare doesn't support the UDP to port 10000 required to have media flow.  Cloudflare proxying only support http-based protocols, which our WebRTC media isn't appropriate for.  If you wish to use Cloudflare for this, then you should have a separate IP/port open to the public advertised by the videobridge, and only run the http components of jitsi through cloudflare.  This is indeed how we have cloudflare configured for our own domains.

**Comment by WissamAntoun** [comment]
@aaronkvanmeerten I did what you suggested and now it works. Thanks!

**Comment by tmb45** [comment]
@aaronkvanmeerten is there any way to overcome this? while I don't have a public IP

**Comment by aaronkvanmeerten** [comment]
No, unfortunately there's no UDP support in cloudflare presently, so I don't see a way around this without a public IP/port to advertise for the media path.
