### ISSUE TITLE
Gravatars are loaded with disableThirdPartyRequests set to true

### ISSUE THREAD

**Issue by ulab** [jitsi/jitsi-meet#5670]
## Description
I set `disableThirdPartyRequests` to `true`, but I am still seeing my Gravatar image being displayed when I switch off the camera. Also according to network inspector there are still calls being made to gravatar.com.

This is unexpected since the comment states:

    // If third party requests are disabled, no other server will be contacted.
    // This means avatars will be locally generated and callstats integration
    // will not function.
    disableThirdPartyRequests: true,

## Current behavior

gravatar.com is still being called.

## Expected Behavior

gravatar.com should not be called.

## Steps to reproduce

Set `disableThirdPartyRequests: true,` and check the network inspector during a page reload.

# Environment details

jitsi-meet 2.0.4384-1 on Debian 10.3

**Comment by saghul** [comment]
I wonder if the change I made in this that’s a few days ago was included in the latest stable. Can you test using the URL override on meet.jit.si?

**Comment by ulab** [comment]
I have not yet worked with URL overrides, but `https://meet.jit.si/WholeGrinsDescribeOriginally#config.disableThirdPartyRequests=true` refreshes to the same URL without the parameter. Is that how it's supposed to work?

Gravatars are loaded with or without either way.

I was quite sure this worked before, but on my latest installation I noticed the avatars being loaded again.

**Comment by saghul** [comment]
The hash disappearing is ok, that doesn’t mean it wasn’t applied.

I fixed this recently, maybe I left some case unhandled. Thanks for the report, I’ll take a look!

**Comment by saghul** [comment]
Looks like the local user is being proesssed before the config was upated from the URL parameters... thus being bypassed. Sigh. This one might be tricky to fix.

**Comment by ulab** [comment]
Hm. I created this issue with `disableThirdPartyRequests: true` in the config file, not because of an URL parameter?

**Comment by kheiken** [comment]
Is there any news on this issue?

This leak of email addresses to an external service like Gravatar is exactly the kind of thing that I expected not to happen with disabledThirdPartyRequests set to true.

**Comment by Commifreak** [comment]
Same here. In addition, a request to callstats.io is made to load the Main JS! Both should be disabled with `disableThirdPartyRequests: true,`

```

GET | https://api.callstats.io/static/callstats-ws.min.js
-- | --



GET /static/callstats-ws.min.js HTTP/1.1
Host: api.callstats.io
```

**Comment by echristiaans** [comment]
we are blocking both callstats and gravatar by no including it in the Content Security Header, but that leads to errors in the web console which is a bit of a dirty solution but it works for now.

**Comment by saghul** [comment]
Does the problem manifest with the URL override or with the value set in config.js ?

**Comment by ulab** [comment]
Either.

**Comment by saghul** [comment]
Thanks for confirming, I'll test it again.

**Comment by amsnek** [comment]
same here, one browser request to: Request URL: https://api.callstats.io/static/callstats-ws.min.js

this only happens if i enable websockets (openBridgeChannel: websocket,) though (?) on latest/current 
if i disable websockets / use sctp -> disableThirdPartyRequests:true works as expected again

**Comment by rasos** [comment]
Avatars should be loaded if `gravatarBaseURL: ` is being set, as this is a strong indicator that you run your own avatar server or have carefully chosen one that fits your privacy needs.

**Comment by csett86** [comment]
I debugged into this first of all, the behaviour is still present in current stable (2.0.5870) and master (f84f7332b9205652a7e9cd8772d05c6fd98e0329) and I found out the following:

When handling the PARTICIPANT_JOINED action, the 'features/base/config' state is empty, thus disableThirdPartyRequests is undefined, ie falsy, which means that the preloading of the avatar is triggered. I debugged this by showing the full redux state in the middleware of participants (https://github.com/jitsi/jitsi-meet/blob/f84f7332b9205652a7e9cd8772d05c6fd98e0329/react/features/base/participants/middleware.js#L410):

![state-participant-joined](https://user-images.githubusercontent.com/1392875/120238579-c2729100-c25c-11eb-83f3-16641397cac4.png)

Unfortunately my react / redux skills are not good enough to propose a fix for this, but maybe this debugging helps someone to fix it.
