### ISSUE TITLE
Implement Poll bot for Chat

### ISSUE THREAD

**Issue by David100mark** [jitsi/jitsi-meet#5676]
**Is your feature request related to a problem you are facing?**
We are using Jitsi for audio-/video-conferences for discussions. Therefore we often do need polls. 
Unfortunately Jitsi doesn't offer a poll-tool, so we rely on external tools.

**Describe the solution you'd like**
Integration of a poll bot in the menue or the Chat.
Examples are Skype-Poll or the Matrix-poll-bot.

**Comment by Echolon** [comment]
I will close this with reference to this:


Poll users during exclusion process
#5355
