### ISSUE TITLE
JitsiMeetExternalAPI: getEmail() always returns undefined

### ISSUE THREAD

**Issue by VirginieGarcin** [jitsi/jitsi-meet#5677]
When trying to retrieve email of a user, calling `api.getEmail(participantId);` (like specified in the documentation ) it always returns `undefined`, even if email was set with `api.executeCommand('email', 'example@example.com');` and with 
```
var options = {
    ...
    userInfo: {
        email: 'example@example.com'
    }
}
```

Other user noticed same issue:

https://community.jitsi.org/t/externalapi-getemail-and-emailchange-dont-work-for-other-participant/29212

**Comment by Arzar** [comment]
Thanks VirginieGarcin. As stated in the forum, I have the same issue.

**Comment by UpTheDesign** [comment]
Same issue here.

**Comment by lapprand** [comment]
Can confirm same issue here, the usage is similar to avatarChanged, which works, but emailChange does not. Tried setting the email as above with userInfo option and executing 'email' command, both did not work.

**Comment by beyondlevi** [comment]
Same issue here. Without this we can't trust on participant information. We use email is user primary key.

**Comment by maulikshah88** [comment]
Same issue.

**Comment by iris-chant** [comment]
Same issue. I had to workaround with it passing mail address as parameter of the avatar URL.

Something like that:

api.on('participantJoined', (event) => {
    var participantId= event.id;
    setTimeout(function(){
        var email = api.getAvatarURL(participantId);
        var url = new URL(email);
        email = url.searchParams.get("mail");
        var index = mails.indexOf(email);
if ($.inArray( email, mails ) !== -1) {mails.splice(index, 1);}
}, 1000); 
});

**Comment by thite-amol** [comment]
same issue. Do we have news for it?

**Comment by itskhurram** [comment]
do we have any update and any fix for this ?

**Comment by vl404-not-found** [comment]
Same issue here. 
Do we have news?
Without this we can't identify users.

**Comment by cfficaurzua** [comment]
same issue

**Comment by nclong87** [comment]
Please fix this issue, thanks

**Comment by anthony-zhou** [comment]
I'm experiencing the same problem, where the email isn't getting saved in the `participants` array. I decided to do some reading to see if I could find out why. 

## Tracing the function calls
It looks like adding an email might require a whole lot of changes. I think what happens is the `JitsiMeetExternalAPI` instance passes the initial `userInfo` object in the `src` attribute of the `iframe` element, and then `lib-jitsi-meet` (in a separate repo) parses the `src` element to find the user info:

https://github.com/jitsi/lib-jitsi-meet/blob/30c87957701eb9fc6a6b69a5cc6dc273f7955b05/modules/xmpp/ChatRoom.js#L476-L486

But notice how `lib-jitsi-meet` only reads the `id`, `name`, and `avatar` tags. Maybe if we also read the `email` tag we could pass it back down the chain of events to get it to the user?

If we can get the `email` into the Participant object, then we can eventually read it in here on the client side when we destructure the `localParticipant` object:
https://github.com/jitsi/jitsi-meet/blob/e69529867e67d98f652457c616a96a4ed1504af0/react/features/external-api/middleware.js#L86-L95

Tracing through further, it looks like we could just pass the `email` down the chain right next to the `avatar` parameter, which (I think) would involve one of the following event listeners.

https://github.com/jitsi/jitsi-meet/blob/e69529867e67d98f652457c616a96a4ed1504af0/modules/API/external/external_api.js#L476-L484

https://github.com/jitsi/jitsi-meet/blob/e69529867e67d98f652457c616a96a4ed1504af0/modules/API/external/external_api.js#L464-L474

My main point, though, is that nowhere along this module is there any mention of the user's `email`.

## Conclusion
This is my first time digging through this codebase, so I'm sure there are some parts I missed. 

To be honest, I don't think I've discovered the exact solution, and I won't have time for a PR. Just thought I'd take some notes here in case it's helpful for anyone who wants to fix this. Either way, it looks like the External API doesn't seem to keep track of the participant's emails at all, across the stack. Would really appreciate a fix!

**Comment by SamarthaKV29** [comment]
This is ridiculous! this issue has not been fixed since Apr ! Why provide a email in the UI and everywhere if there is no support for it! 
Either you guys have committed code to remove the email by mistake or it was never implemented, but this is no way to release software. As much as I appreciate all the efforts the community puts in to make this happen, I'm a little frustrated because we are developing our applications in record time using your SDK, and bugs/issues like these set us back by a lot. Whoever is doing the code review or task management needs to prioritize the development properly. You guys are spending too much time on unnecessary features and UI. Nobody cares. The core functionality needs to work first. I think you have strayed too far from the goal.

**Comment by SamarthaKV29** [comment]
> I'm experiencing the same problem, where the email isn't getting saved in the `participants` array. I decided to do some reading to see if I could find out why.
> 
> ## Tracing the function calls
> It looks like adding an email might require a whole lot of changes. I think what happens is the `JitsiMeetExternalAPI` instance passes the initial `userInfo` object in the `src` attribute of the `iframe` element, and then `lib-jitsi-meet` (in a separate repo) parses the `src` element to find the user info:
> 
> https://github.com/jitsi/lib-jitsi-meet/blob/30c87957701eb9fc6a6b69a5cc6dc273f7955b05/modules/xmpp/ChatRoom.js#L476-L486
> 
> But notice how `lib-jitsi-meet` only reads the `id`, `name`, and `avatar` tags. Maybe if we also read the `email` tag we could pass it back down the chain of events to get it to the user?
> 
> If we can get the `email` into the Participant object, then we can eventually read it in here on the client side when we destructure the `localParticipant` object:
> https://github.com/jitsi/jitsi-meet/blob/e69529867e67d98f652457c616a96a4ed1504af0/react/features/external-api/middleware.js#L86-L95
> 
> Tracing through further, it looks like we could just pass the `email` down the chain right next to the `avatar` parameter, which (I think) would involve one of the following event listeners.
> 
> https://github.com/jitsi/jitsi-meet/blob/e69529867e67d98f652457c616a96a4ed1504af0/modules/API/external/external_api.js#L476-L484
> 
> https://github.com/jitsi/jitsi-meet/blob/e69529867e67d98f652457c616a96a4ed1504af0/modules/API/external/external_api.js#L464-L474
> 
> My main point, though, is that nowhere along this module is there any mention of the user's `email`.
> 
> ## Conclusion
> This is my first time digging through this codebase, so I'm sure there are some parts I missed.
> 
> To be honest, I don't think I've discovered the exact solution, and I won't have time for a PR. Just thought I'd take some notes here in case it's helpful for anyone who wants to fix this. Either way, it looks like the External API doesn't seem to keep track of the participant's emails at all, across the stack. Would really appreciate a fix!

@anthony-zhou I really appreciate your support on this, and I am severely disappointed to know that this is coming from the lib-jitsi-meet. Now we need to maintain our own copy of the fixed version for this one also in our codebase. This is super annoying and crappy implementation. Parsing a JistiMeetUserInfo object should not be done in lib-jitsi-meet. If what you're saying is true, it makes no sense why one would do it that way. I have been working on Jitsi for over 2 months now, and I have implemented much of the functionality myself. Forwarding those events which are available on Iframe API and not available on native, etc. I have no interest in React/React Native or any background in it. I frankly hate React and Facebook. The only reason I entered into this is for developing our SDK. Even without any help or looking at the code and tracing deep into it, I am able to implement the changes we need, like adding buttons and other crap. 
How long does it take Jisti community to fix this damn bug. Ridiculous !
I am going to figure out a way to fix this, and 100s of other things to customize it for our SDK. I will even fork these projects but will not share my solutions coz you guys are not worth it. This simple ticket hasn't been solved yet, but from tracing all your commits and changelogs, I see 100s  of unnecessary crap you guys are working on. Stop wasting my time. 
God knows when you will fix this. Such a simple thing

**Comment by damencho** [comment]
The email can be set through the API for the local participant and the same way can be retrieved through the API. getEmail returns the email of the local participant.

**Comment by anthony-zhou** [comment]
@damencho Sorry, I misspoke in saying that the email's not kept track of across the stack. It's stored locally, but it doesn't seem to be stored in the backend. That is, `getParticipantsInfo()` never returns the other users' emails. 

Is it intentional that we can only access each user's email address locally? I can understand the privacy motivations, but it'd be nice to have some consistent source of identity, to know which users are on a call at a given time (would love to know if there are workarounds here). 

I think the source of confusion is that `getEmail`, as documented, is supposed to take in a participant id and return their email, but it only works for the local participant's id--I (and probably the others on this thread) expected it to fetch emails for any participant on the call.

**Comment by damencho** [comment]
> @damencho Sorry, I misspoke in saying that the email's not kept track of across the stack. It's stored locally, but it doesn't seem to be stored in the backend. That is, `getParticipantsInfo()` never returns the other users' emails.

That has never been the case, and was not intended to be used that way looking at the contributor's PR.



> I think the source of confusion is that `getEmail`, as documented, is supposed to take in a participant id and return their email, but it only works for the local participant's id--I (and probably the others on this thread) expected it to fetch emails for any participant on the call.

Yep, I agree ... we missed that detail when we were reviewing the PR.

**Comment by SamarthaKV29** [comment]
@damencho can some one provide way to get it working or do we need to do it ourselves now? Does this require changing the database in video bridge or is or all local to the client?

**Comment by damencho** [comment]
There are is no planned work around it ... so any PRs are welcome, no these are just client side changes ...
