### ISSUE TITLE
Current version not availalbe in F-Droid

### ISSUE THREAD

**Issue by Krawei** [jitsi/jitsi-meet#5679]
Dear team,

when I take a look on google play store the current version is 2.1.0.201000 in the F-Droid store the current version is 2.1.0.3883698

What's the reason for this gap? Are both the same version, but in different stores? Or is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by saghul** [comment]
Hi there!

The F-Droid build is special. It uses a built time flag which makes it a “libre build”: there is no Crashlytics, Google SignIn, Dropbox or any Google services dependency.

In addition, the build versionCode is choose NAT random, so unless we force it they wouldn’t match.

For all intents and purposes, the MAJOR.MINOR.PATCH are all that needs RN match so you know the same features are supported.

Hope that clarifies it.
