### ISSUE TITLE
Adding API Key To Jitsi Room Creation

### ISSUE THREAD

**Issue by ankitarora12** [jitsi/jitsi-meet#568]
I would like to add an application API key to the room creation on Jitsi-Meet, so as to restrict access to different clients that I provide my services to. Since I would be hosting Jitsi on a dedicated server, I would like only the authenticated clients to create rooms on my installation. Skylink.io provides a similar mechanism.

Can anyone tell me if I can add in some API the API key parameter? Or if it can be added as a new feature in Jitsi??

**Comment by damencho** [comment]
There is already token authentication. You can install
jitsi-meet-tokens and play with it, then you can provide token to the
clients. Hope this helps.

**Comment by damencho** [comment]
Mailinglist is preferred way to communicate. Do not open issues. (Mailinglist is moderated so when you are not subscribed the moderator needs to approve your mail, as I see you already sent an email to the list)
