### ISSUE TITLE
Support MP3 for localRecording

### ISSUE THREAD

**Issue by PanderMusubi** [jitsi/jitsi-meet#5686]
**Is your feature request related to a problem you are facing?**
Local recording of audio can be configured to ogg, flac and wav. The latter two do not have a lot of compression. Ogg does have that, but many users have no idea what an ogg file is or how to play it. Hence, many users ignore the local recording .ogg download and get confused by it.

**Describe the solution you'd like**
Allow mp3 as one of the options for localRecording in the config file. This is a well-know audio file format which users recognize and feel comfortable with.

**Describe alternatives you've considered**
Educating people what ogg files are but for many non-technical users this is something they do not want to be bothered with.

**Comment by ostasevych** [comment]
> **Is your feature request related to a problem you are facing?**
> Local recording of audio can be configured to ogg, flac and wav. The latter two do not have a lot of compression. Ogg does have that, but many users have no idea what an ogg file is or how to play it. Hence, many users ignore the local recording .ogg download and get confused by it.
> 
> **Describe the solution you'd like**
> Allow mp3 as one of the options for localRecording in the config file. This is a well-know audio file format which users recognize and feel comfortable with.
> 
> **Describe alternatives you've considered**
> Educating people what ogg files are but for many non-technical users this is something they do not want to be bothered with.

As far as I know mp3 is closed format subjected to licensing (https://en.wikipedia.org/wiki/MP3#Licensing.2C_ownership_and_legislation). All modern music players, including online, support open OGG format. So, this is the matter of tips to be provided to users.

**Comment by saghul** [comment]
We would need to ship an mp3 encoder, and whatever legal / patent uncertain shenanigans apply are not something we really want to get legal involved with.

**Comment by PanderMusubi** [comment]
Okay, thanks for the info.
