### ISSUE TITLE
Bowser Browser on iOS 9.3 not recognised as a WebRTC capable browser.

### ISSUE THREAD

**Issue by bcnx** [jitsi/jitsi-meet#569]
Hi,

while connecting to the latest version of Jitsi-Meet with a recently updates iPad I get the message that Bowser is not WebRTC capable. The people of Ericsson assured me it is. Could there be an issue with the detection routine?

thank you,

BC

**Comment by bgrozev** [comment]
AFAIK Jitsi-Meet hasn't been tested with Bowser, and Bowser is not in the list of supported browsers. You if you see (this page)[https://meet.jit.si/unsupported_browser.html], that's normal.

**Comment by bcnx** [comment]
Well, I have tested with Chrome on iPad and that didn't work as well. I did not check the version though (already removed it) but I would expect it to be the latest and greatest? 
What has been verified as working on an iOS device?

thanks!

BC
