### ISSUE TITLE
Cannot edit Ukrainian localisation

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5692]
Hi! Today I added Ukrainian language to Jitsi meet and locally translate strings. In a certain time I have found that I may not more edit the strings: the translation of the main file is locked.
![image](https://user-images.githubusercontent.com/5199030/78508366-feac7d80-778e-11ea-8ff3-53808e3d8c79.png)

Moreover, I cannot add the localisation of the languages file in Ukrainian.

Are any restrictions applied now?

**Comment by damencho** [comment]
Yes the weblate guys were still working on the project there. Should be fine now.

**Comment by ostasevych** [comment]
> Yes the weblate guys were still working on the project there. Should be fine now.

Hi! Thanks for responding. Still no possibility to edit strings...

**Comment by damencho** [comment]
Yep, it seems there is still some problem ... 🤷‍♂

**Comment by ostasevych** [comment]
> Yep, it seems there is still some problem ... 🤷‍♂

These issues periodically appearing... I am still not able add UA language to the list of laguages :(

**Comment by damencho** [comment]
You can follow this link for news about the translations. https://github.com/jitsi/jitsi-meet/issues/5056
We as a team had still not decided on a tool to use for translations. Once the tool is chosen and it is configured according to our needs we will inform everybody in that ticket and will close it.
Sorry for the inconvenience.
