### ISSUE TITLE
Country code "translation" to country name does not work

### ISSUE THREAD

**Issue by real-or-random** [jitsi/jitsi-meet#5697]
## Description

Using dialInNumbers json like:
```
 [{"countryCode":"de", "tollFree":false, "formattedNumber":"12345"}]
```
look at the one table entry in `static/dialInInfo.html`:

## Current behavior
:de:   "countries.de" 

## Expected Behavior
:de:  "Germany"

## Possible Solution

I suspect this line should be have `countries:${number.countryCode}` instead:
https://github.com/jitsi/jitsi-meet/blob/86d0d4fc2201bf4bbe50681001d7d64a220bf5b2/react/features/invite/components/dial-in-summary/web/NumbersList.js#L67
 
# Environment details
v4384

**Comment by damencho** [comment]
What about {"countryCode":"DE","tollFree":true,"formattedNumber":"+49 ....."}
Use DE not de? Does that make a change?

**Comment by real-or-random** [comment]
Oh this works. Yes, country codes are typically written in upper case, and indeed https://www.npmjs.com/package/i18n-iso-countries insists on upper case. But it was confusing since the flag was displayed properly. I'll open a PR to always convert the code to upper case. This seems sensible here because there's no danger of confusion with a language code here.
