### ISSUE TITLE
Inconsistent connection scenarios

### ISSUE THREAD

**Issue by inpharmaticist** [jitsi/jitsi-meet#5699]
I followed the quick install instructions (https://jitsi.org/downloads/). I looked at other threads that couldn't get audio/video on all devices but couldn't find my specific situation or a fix for it.

I have 4 devices: a laptop running the server, two androids, and an iphone. When the laptop is part of the connection, the phones not connected to the wifi will be "in the room" but no audio/video.  I can use all 3 phones while 2 are on the network and 1 is not with no issues. I can use all devices if they are all on the internal network. I can use one phone on the network and one phone outside the network. I can use the laptop and one phone off the network.

It seems like any combination that includes the laptop (server) and one device outside the network, the outside device cannot get audio/video. I also tried the advanced configuration (https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) but that made is so the laptop couldn't connect to any device on or off the network.

Need more info? I have attached the following logs.

[jicofo.log](https://github.com/jitsi/jitsi-meet/files/4435309/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/4435310/jvb.log)

**Comment by damencho** [comment]
Please use the community forum when you have problems or questions before opening new issue.

Have you forwarded port 10000 udp to your laptop?

**Comment by inpharmaticist** [comment]
Yes, as well as 443 and 80 based on this tutorial https://youtu.be/8KR0AhDZF2A
