### ISSUE TITLE
Allow to prevent displayName change in config

### ISSUE THREAD

**Issue by gleibfried** [jitsi/jitsi-meet#5707]
**Is your feature request related to a problem you are facing?**
I currently cannot prevent an user to update his dsplay name. I'm setting it automatically and don't want him to be able to change it.

**Describe the solution you'd like**
Have a boolean parameter I can set in `configOverwrite`, which could be something like `enableDisplayNameChange` as true by default.

**Describe alternatives you've considered**
To prevent users doing it I made an event listener on displayNameChange to set it back, but it will seem strange in an UX point of view.

**Comment by abhi0476** [comment]
Try this: 
setInterval(function(){
            api.executeCommand('displayName', userFullName);
        },1000);

**Comment by gleibfried** [comment]
@abhi0476 I know how to overwrite a display name, but allowing the user to update his name and set it back to previous feels strange in UX perspective.

I manage to unallow the editing by setting `pointer-events: none` to `#localDisplayName` on the jitsi server, but that would be better to be able to do it in the options of JitsiMeetExternalAPI

**Comment by abhi0476** [comment]
Agreed, developers should definitely look into it for future release...

**Comment by JeDy1111** [comment]
If you use jwt token, you can set enableUserRolesBasedOnToken to true
This removes the profile editing from the user interface for token authenticated users.

However users can still change his displayName from the browser console with api.executeCommand('displayName', 'newname');
I am looking for a solution to prevent this. Maybe an option to disable the displayName command from the API ? Could it be the same option as enableUserRolesBasedOnToken ?

**Comment by cubico** [comment]
It works for me with JitsiMeetExternalAPI:

```
<script src='https://meet.jit.si/external_api.js'></script>
<script>
  // check conference state (join page or videochat)
  let videoConferenceJoined = false;

  // set with an string to default value, "John Doe" by example
  let localDisplayName = null;

  const domain = 'meet.jit.si';
  const options = {...}; // put your own options here
  const api = new JitsiMeetExternalAPI(domain, options);

  // Force default value (You can comment this line if localDisplayName is null)
  api.executeCommand('displayName', localDisplayName);

  api.addEventListeners({
      displayNameChange: function(params){
        // if is Videochat, set the Join Page displayName
        if (videoConferenceJoined){
          return this.executeCommand('displayName', localDisplayName);
        }

        // if is Join Page, update global variable (localDisplayName) with input value
        localDisplayName = params.displayname;
      },
      videoConferenceJoined: function() {
       // flag the conference starts
        videoConferenceJoined = true;
      }
  });
</script>
```

**Comment by nilsreichardt** [comment]
> If you use jwt token, you can set enableUserRolesBasedOnToken to true
> This removes the profile editing from the user interface for token authenticated users.
> 
> However savvy users can still change their displayName from the browser console with api.executeCommand('displayName', 'newname');
> I am looking for a solution to prevent this. Maybe an option to disable the displayName command from the API? Could it be the same option as enableUserRolesBasedOnToken?

`enableUserRolesBasedOnToken` doesn't exists anymore. It is separated into `disableProfile` and `enableFeaturesBasedOnToken`:

```js
// Disables profile and the edit of all fields from the profile settings (display name and email)
disableProfile: true,

// Whether or not some features are checked based on token.
// enableFeaturesBasedOnToken: false,
```

**Comment by JMSevilla** [comment]
Is there any solution for this today?

**Comment by anazcodesap** [comment]
if you don't want a user to update his display name. or want to setting it automatically and don't want him to be able to change it. use  'prejoinpage.hideDisplayName': true, in flag...
Here is my example

const user = {
    firstName: 'Joe',
    lastName: 'Doe',
    email: 'joe@gmail.com',
  };

  const userInfo = {
    displayName: `${user.firstName} ${user.lastName}`,
    email: user.email,
  };

<JitsiMeeting
      eventListeners={eventListeners}
      flags={{
        'invite.enabled': false,
        'kick-out.enabled': false,
        'prejoinpage.hideDisplayName': true,
      }}
      ref={jitsiMeeting}
      style={{flex: 1}}
      room={room}
      userInfo={userInfo}
      serverURL={'your url'}
    />

**Comment by anazcodesap** [comment]
> Is there any solution for this today?

yes
