### ISSUE TITLE
Share a single screen/monitor in a multi-monitor setup

### ISSUE THREAD

**Issue by maxguru** [jitsi/jitsi-meet#5709]
Platform: Linux
Distribution: Gentoo
Desktop Environment: KDE
Package: AppImage at https://appimage.github.io/jitsi-meet/ (jitsi-meet-electron)

**Is your feature request related to a problem you are facing?**
I have too many monitors. I only get the option to share the entire workspace which has all monitors included or individual windows. People can't see very well what I am showing if they have a small screen.

**Describe the solution you'd like**
It would be really nice to be able to share a single monitor.

**Describe alternatives you've considered**
I tried sharing individual windows but it is not practical to keep having to switch between them.

This issue is similar to #3969. Would I need to post this at https://github.com/jitsi/jitsi-meet-electron ?

**Comment by samperd** [comment]
+1 to this idea.

Platform: Linux
Distribution: Ubuntu
Desktop Environment: GNOME
Package: running straight from http://meet.jit.si
Browser: Firefox

**Is your feature request related to a problem you are facing?**
As a dual monitor user I deliver many online presentations. I use one monitor to deliver the presentation and use the second monitor to manage the presentation (eg using google slide sof MS Powerpoint), speaker notes, other apps or views to pull into the presentation.

Currently I am limited to a specific application or all dual screen contents. It would be nice to constrain to a single monitor including all apps on that monitor.

It would also be nice to be able to share the actual jitsi application so I can take new users on a tour.

**Describe the solution you'd like**
When being asked for screen sharing permissions I would like to select screen#1 and Screen#2 as my left and right monitors.

**Describe alternatives you've considered**
I tried sharing individual windows but it is not practical to keep having to switch between them. One example is when I run demos I use google slides to start off and then might move to another browser window. I then need to unshare and re-share. During this process my users must experience a dizzying mass of cascading windows on their screen. 

Implementation Details:
* according to #3969 this might also be related to browser functionality.
* About the screen capture API in Firefox: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture
* About Web RTC API for firefox: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API
* Good comparison chart for media capture and streams API for various browsers: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API

**Comment by maxguru** [comment]
I think this should be closed. The new version of jitsi-meet-electron seems to have this bug fixed. It worked for me for a while already.
