### ISSUE TITLE
avoid gendered elements in avatars

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#571]
for example, the thing that looks like a mustache etc. on the robots

EDIT: Surprised people cared enough to downvote. In a world where the default assumptions are too often male already, I am not (as a man myself) comfortable with things that ram home the assumption that most people are likely male (especially seeing situations in which some others have assumed that a no-video female participant in a meeting was male). I don't think it would have occurred to the designers to have most of the robots be either neutral or have clearly feminine markers. I don't want to spend tons of time unpacking this, but it would be preferable that unless things go crazy and build a complete customizable avatar system, the appropriate and easiest thing to do is to just avoid things that aren't neutral.

**Comment by FliegendeWurst** [comment]
But why?

**Comment by jart** [comment]
You're such a knight in shining armor @wolftune. Fighting to protect us from moustaches.

**Comment by wolftune** [comment]
@jart yeah whatever. I don't give a shit about my personal place in this, and I'm not interested in fighting about this little thing.

It just irked me because the unfortunate gender imbalance in the Open Source tech world leads to all sorts of cases where white-male is the assumed default. I dislike this overall situation for a range of good reasons and the mustache thing just reminded me of this trend overall. I thought it'd be easy enough to just bring to people's attention and they'd think "oh yeah, hmm, didn't think about that". Why would people bother being defensive about this? Yes, it's a minor insignificant detail in a world with a lot of real issues.

**Comment by jart** [comment]
I find it remarkable how the opinions of radical feminists in the 60's, are remarkably similar to the opinions of male software engineers today.

<img width="677" alt="screen shot 2016-07-04 at 2 13 41 am" src="https://cloud.githubusercontent.com/assets/49262/16590481/c26200d8-42a5-11e6-9c04-7e4cb67013b9.png">

http://www.newyorker.com/magazine/2013/04/15/death-of-a-revolutionary

**Comment by wolftune** [comment]
@jart Non-sequitur. I am not a software engineer, and I don't hold that opinion you quoted. I'm not denying anything you said, it just doesn't apply to me at all. It may be true that many male software engineers feel that way though.

**Comment by joncamfield** [comment]
Bring back the bots! The switch this week to randomly-assigned, gendered people is... odd?

**Comment by damencho** [comment]
We are aware of the problem with random avatars, we will be working on this
now.
