### ISSUE TITLE
Wrong order of languages in Settings

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5712]
When changing a language in Settings I see wrong order of languages in drop-down menu. Should be from A to Z.
![image](https://user-images.githubusercontent.com/5199030/78561586-a9b94780-7820-11ea-9eb0-c600402e2827.png)

Additionally, there are no added Ukrainian language there.

**Comment by Echolon** [comment]
@ostasevych we would be very happy for volunteers to translate to additional languages: https://desktop.jitsi.org/Documentation/HowToTranslateSIPCommunicator

**Comment by ostasevych** [comment]
> @ostasevych we would be very happy for volunteers to translate to additional languages: https://desktop.jitsi.org/Documentation/HowToTranslateSIPCommunicator

I am a bit confused with the suggestion to help with the translation of SIP Communicator... Is that another product? Meanwhile, how to improve existing translation of Jitsi Meet?...

**Comment by Echolon** [comment]
Ah, sorry my fault I'm only a voluntary community support.

Yes that's misleading. @saghul is there an official translation service for Jitsi?

**Comment by damencho** [comment]
@Echolon not at the moment https://github.com/jitsi/jitsi-meet/issues/5056
We are working on bringing something but we are constantly being slowdown from more urgent issues. But it is moving, slowly, but moving.

**Comment by Echolon** [comment]
ok
