### ISSUE TITLE
Live streaming with Facebook live

### ISSUE THREAD

**Issue by LAfricain** [jitsi/jitsi-meet#5718]
**Is your feature request related to a problem you are facing?**
Currently live streaming is only possible with Youtube, please add the possibility to use Facebook live

**Describe the solution you'd like**
Add en entry for the facebook live live streaming key.

**Describe alternatives you've considered**
OBS, works well.

**Comment by PGPereira** [comment]
It would be interesting to livestream also in twitter and instagram

**Comment by funkyfuture** [comment]
as you're interested in self-hosting, you may find this resource interesting as well: https://staltz.com/the-web-began-dying-in-2014-heres-how.html

**Comment by grahamPegNetwork** [comment]
I second this request. Trying to leverage Jitsi as a Zoom replacement however the lack of Facebook integration is a deal breaker for the intended use.

**Comment by Echolon** [comment]
duplicate of
Live streaming #5146
@damencho
