### ISSUE TITLE
provide a non-video way to "raise your hand"

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#572]
i.e. click a "wanting to speak" or something icon that would highlight my avatar for owner (or myself perhaps) to acknowledge and then turn off that highlight once I speak.

**Comment by Ham-Radio** [comment]
I second this, this would be awesome!

**Comment by bgrozev** [comment]
+1

**Comment by emcho** [comment]
How wold that be better than just saying "I'd like to say/ask something" in chat?

**Comment by wolftune** [comment]
If there's lots of chat going on, people would have to monitor it and check for this. Plus, the chat is flat. A chat half-full of people discussing some side issues or links but half-full of "I'd like to speak" messages would be crappy. The chat also has an audio sound and is distracting that way.

The idea is to keep the same signal: visual indication in the video area, whether or not you're on camera. Otherwise, someone might just keep calling on those people on camera with hands up and not notice those not on camera.

**Comment by bgrozev** [comment]
> How wold that be better than just saying "I'd like to say/ask something" in chat?

1. It doesn't require typing
2. It doesn't require people reading the chat
3. It can be disabled once the person is done speaking (while a chat message cannot be deleted)

**Comment by emcho** [comment]
What concerns me here is that the risk of burdening the interface with something that is only going to be needed in a very, very small percentage of conferences.

Now, if we could find a smart way of doing it ... for example by somehow using the mute button, then I'd be happier

**Comment by ibeardslee** [comment]
The mute button should be used for muting, let's not give things multiple vaguely related tasks to do.

If it could somehow be worked in with the 'talking stick' idea that I have seen mentioned a couple of other issues that could work.  Raise your hand to speak, the talking stick gets handed to you.

**Comment by wolftune** [comment]
sure, this basically is the same as "request the talking stick"

**Comment by emcho** [comment]
How common do you guys think is the idea of a talking stick? How many people do you think would see it and immediately know how it works? 

The point of using the mute button is that people will naturally go and select it when they want to speak. If their conference is configured the right way that action can translate to turning their mic icon some specific colour (same for their thumbnail on others' desktops) as well as a message informing them about how this is going to go. 

No education necessary for users. It all just works for them. Only added complexity will be for moderators who have to configure their rooms as moderator controlled ... or something of the sort

**Comment by ibeardslee** [comment]
I thought the point of a mute button was to stop me being heard.

A bit of retraining about what a mute button is for will be needed .. is this turning off my mic? or turning it on? or putting my hand up to talk? or putting my hand back down again because someone else covered my point?

**Comment by emcho** [comment]
> I thought the point of a mute button was to stop me being heard.

And it will still do that part reliably

> A bit of retraining about what a mute button is for will be needed ..

I don't see it. Muting still works. Unmuting is delayed and accompanied with a message along the lines of: you can't actually unmute now. We will let you know (and unmute you) when it's your turn to speak.

**Comment by wolftune** [comment]
> We will let you know (and unmute you) when it's your turn to speak.

Right, but that would only be if the owner muted you, not if you muted yourself (right?), that's why this confused people. It would be no good to make the owner the only person who can ever unmute anyone.

**Comment by emcho** [comment]
That's a separate thing. If we want we can always add an extra button that says "I need to speak NOW!"

or something

**Comment by bgrozev** [comment]
#687 implements what I believe is the original suggestion.

**Comment by wolftune** [comment]
surprised no else closed this, but it's obviously done, thanks

**Comment by real1900** [comment]
How can this be triggered from the mobile SDK ?

**Comment by saghul** [comment]
@real1900 that action is not currently exposed in the SDK, the only way to trigger it is by using the UI button. This may change in the future though.

**Comment by sebo313** [comment]
Hi, I would like to have a Sound like a bell ringing when clicking the "raise the hand" button. Can you help me with implementing it?
