### ISSUE TITLE
Beats headphones produce an echo effect during a jitsi-meet call

### ISSUE THREAD

**Issue by Luni-4** [jitsi/jitsi-meet#5722]
## Description
---

During a `jitsi-meet` call, two of the fifteen participants have produced an echo effect while they were talking. Both of them were using `Beats` headphones. The first one was using the `jitsi-meet` app for `Ios` while the other one was using the last version of ` Google Chrome` on `Windows 10` 

## Current behavior
---

`Beats` headphones produced an echo effect during a `jitsi-meet` call

## Expected Behavior
---

No echo effect produced by `Beats` headphones

## Possible Solution
---

## Steps to reproduce
---

Verify if `Beats` headphones produce an echo effect during a `jitsi-meet` call

# Environment details
---

- `jitsi-meet` app for `IoS`
- `Google Chrome` on `Windows 10`

**Comment by hardlycode** [comment]
Our of curiousity can you confirm if they were using bluetooth or wired?

**Comment by Luni-4** [comment]
Hi @hardlycode! Thanks for your reply! :)

One was using the bluetooth, while the other one wired.

**Comment by saghul** [comment]
I don’t think there is anything we can do here. Seems like a device specific issue.

**Comment by hardlycode** [comment]
I would agree. I have a number of people using different devices on Jitsi. I don't recommend anything bluetooth at all, but if wired headphones are producing echo, it must be a microphone in the headphones for phonecalls...
