### ISSUE TITLE
Chat Break Lines are caught but not formatted

### ISSUE THREAD

**Issue by alucard0134** [jitsi/jitsi-meet#5723]
## Description
---
When attempting to post a chat message with line breaks, the chat message does not include the line breaks.
## Current behavior
---
Chat renders a line break as a space instead
![image](https://user-images.githubusercontent.com/12538482/78586772-8af78880-7801-11ea-804d-da0803bdf1f5.png)

## Expected Behavior
---
The chat message should render the line breaks.
![image](https://user-images.githubusercontent.com/12538482/78586859-b67a7300-7801-11ea-95f2-0e54b1744302.png)

## Possible Solution
---
I tried adding `white-space: pre` to the .chatmessage class but then text overflow isnt handled correctly as seen in the pictures above.
## Steps to reproduce
---
Attempt to post a message with line breaks
# Environment details
---
Jitsi-meet k8s

**Comment by Syonyk** [comment]
How are you putting line breaks in?

Using shift-enter in the text input area appears to render properly in the current public version of Jitsi.  Copying and pasting multi-line text appears to work properly.

Chrome 81 on Linux against my own private Jitsi instance, iOS app works properly too.
