### ISSUE TITLE
Dropbox Oauth Login issue on Electron client for Recording Jitsi Video Conferences

### ISSUE THREAD

**Issue by jimDKE** [jitsi/jitsi-meet#5724]
## Description

Hi Jitis Team!  We've run into a problem when entering a Jitsi Meet video conference room through the desktop Electron client and then attempting to record the session via Dropbox.  We seem to be running into a possible issue with OAuth into Dropbox.  When we enter the same Jitsi Meet video conference room via URL in Firefox or Chrome, the Dropbox OAuth and session recording work without any issues.

---

## Current behavior

When accessing the Jitsi video conference in the Electron client, Dropbox OAuth window turns completely white and empty of all text/buttons after we submit the Dropbox account credentials.

![dropbox_oauth_prompt](https://user-images.githubusercontent.com/45210650/78590577-e8d2a300-77f6-11ea-8f1f-07f403da77ba.png)

![dropbox_oauth_blank_oauth_window](https://user-images.githubusercontent.com/45210650/78590598-ecfec080-77f6-11ea-95e7-02562aef0ed0.png)

Note: the Dropbox OAuth process and recording seems to work just fine when accessing the Jitsi video conference room in Firefox and Chrome.  We were able to use OAuth, record the video to Dropbox and view the recording later.

---

## Expected Behavior

We are hoping there will be fix to allow Dropbox OAuth in the Electron app to succeed and then present the user with the option to start recording the video session.

---

## Possible Solution

It looks like the last change related to this may have been a from early last year (2019), https://github.com/jitsi/jitsi-meet/commit/55149670da4d56a6242e16c09977d40f44c54674

Would it be possible to update the Dropbox OAuth support in Jitsi?

---

## Steps to reproduce
-Deploy a rocketchat server snap (following the [documentation](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/), it's pretty quick and easy) for testing with their [app](https://rocket.chat/install) on the Electron client.
-Enable Jitsi video conferencing ([documentation](https://rocket.chat/docs/administrator-guides/setting-up-video-conferencing/)).
-Enter one of the chat channels (like the "general" channel), then click the triple-dot icon in the upper right corner and select "Video Chat".

Alternatively, feel free to test this out with any app that runs in Electron and provides access to Jitsi video conferencing with recording options through Dropbox OAuth.

---

# Environment details

Server
- Version of Rocket.Chat Server: 2.4.11
- Operating System: Linux x64 5.3.0-42-generic
- Deployment Method: snap

Client
-Operating System: Windows 10 Enterprise 2016 LTSB x64 Build 14393
-Electron Desktop app (Chrome update 78)
(Electron app supplied by [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron) on GitHub)
-Firefox x64 v74.0 (testing accessing Jitsi Meet on Win 10)
-Chrome v80.0.3987.149 (testing accessing Jitsi Meet on Win 10)

Our server directs clients to a public web URL that begins with meet.jit.si when we launch a Jitsi video conference.

---

**Comment by damencho** [comment]
@hristoterezov Have you seen this as you had recently was working with new windows in electron?

**Comment by Echolon** [comment]
rel.

meet.jit.si recording - no audio recorded #5403
