### ISSUE TITLE
issue to record

### ISSUE THREAD

**Issue by florenciadurante** [jitsi/jitsi-meet#5727]
hi, i can not record my meeting in jitsi-meet, why is it?
should i pay for this?

**Comment by jfowlie** [comment]
There's a completely separate module that lets you add recording features, called Jibri -- I haven't tried to use it, however. [https://github.com/jitsi/jibri](https://github.com/jitsi/jibri)

**Comment by Echolon** [comment]
I think its spam.

@damencho
