### ISSUE TITLE
Unable to access camera

### ISSUE THREAD

**Issue by caminarva** [jitsi/jitsi-meet#5730]
I can't use the camera in mi meetings, it says "for unknown reason" ¿How can i resolve this issue?
![2020-04-06-18-04-36](https://user-images.githubusercontent.com/63263979/78609679-323fe400-7831-11ea-9600-d68b1a889b7b.png)

**Comment by Echolon** [comment]
**Non-working camera meta-issue** #5425 
@damencho can be closed
