### ISSUE TITLE
Не подключается запись

### ISSUE THREAD

**Issue by vehemense** [jitsi/jitsi-meet#5737]
Добрый день!
Почему-то идет сбой по записи. Пишется - все записывающие устройства - заняты. Как быть? Запись нужна, аккунт в дропбоксе создан

**Comment by Echolon** [comment]
> No recording connected.
> Good afternoon!
> Somehow there's a malfunction in the recording. It's being written - all the recording devices are busy. What's it gonna be? You need the recording, the shotbox is tidy.

This is not a support forum.

**Comment by damencho** [comment]
Use the community forum.

@Echolon thanks for the work you are doing!
