### ISSUE TITLE
Add label to room name 

### ISSUE THREAD

**Issue by guerda** [jitsi/jitsi-meet#5739]
**Is your feature request related to a problem you are facing?**
Based on the discussion at https://community.jitsi.org/t/accessibility-ranking-of-jitsi/27796, I would like to see a label for the room name, in order to help users to identify what the input field is

**Describe the solution you'd like**
Add a <label> before the input field.
https://github.com/jitsi/jitsi-meet/blob/9fdc18d1ec41707be3fc1f1de06b81c7f1394fb9/react/features/welcome/components/WelcomePage.web.js#L195

I will add a pull request for this.

**Comment by Echolon** [comment]
@guerda can you connect the related issue with this PR?

**Comment by guerda** [comment]
@Echolon I'm not sure how to do that, but I'm happy to learn. Should I just mention the PR in this issue here?

**Comment by Echolon** [comment]
@guerda its not complicated. Just go to the referenced PR, and on the right side you can "Link to relevant issue" or something like this.

**Comment by luixxiul** [comment]
Maybe it means: By adding `Close #5739` inside the first post of the PR / inside the commit message, this issue will be closed automatically when the PR is merged.

**Comment by guerda** [comment]
Thanks @luixxiul ! I was able to add it as a linked issue via your hint. @Echolon : done :)

**Comment by DJCrashdummy** [comment]
this is at least related to #5169...

**Comment by guerda** [comment]
As soon as #5740 is approved, this can be merged. Still waiting for the review.
