### ISSUE TITLE
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'JitsiMeet')

### ISSUE THREAD

**Issue by sergey-prosvirnin** [jitsi/jitsi-meet#5744]
This is the first time I've tried to build a mobile app for iOS.  First I run `npm i` and then `pod install` and after that I start building `xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive`. In the end I get an error about the wrong version, but I don't find a place to change it.

```
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive
User defaults from command line:
    destination = generic/platform=iOS

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'JitsiMeet')

** ARCHIVE FAILED **
```

![2020-04-07_10-57-53](https://user-images.githubusercontent.com/24830345/78661809-13e0f380-78d8-11ea-9de6-2b8e104fdbe4.png)

**Comment by fagerbua** [comment]
@sergey-prosvirnin Which version of Xcode are you using? It could be that you need to upgrade your macOS and/or Xcode versions to get Swift 5 supported.

**Comment by sergey-prosvirnin** [comment]
> @sergey-prosvirnin Which version of Xcode are you using? It could be that you need to upgrade your macOS and/or Xcode versions to get Swift 5 supported.

Unfortunately, my version of Xcode turned out to be a bit too old, just like my laptop to install a new version of Xcode.
