### ISSUE TITLE
ldap.cfg.lua doesn't works with `%u`

### ISSUE THREAD

**Issue by aboettger-tuhh** [jitsi/jitsi-meet#5747]
@damencho 

The placeholder `%u` is not replaced by the login name at runtime.
Why do I say that?

If I replace `%u` with my login name (MY_UID), then the login via LDAP works.

In the two blocks you can see the configuration and the corresponding result when working with `%u`.

```
authentication = 'ldap2' -- Indicate that we want to use LDAP for authentication

ldap = {
    hostname      = 'ldap.rz.tu-harburg.de', -- LDAP server location
    use_tls       = true,
    --bind_dn       = 'uid=jabberd,ou=people,dc=example,dc=com', -- Bind DN for LDAP authentication (optional if anonymous bind is supported)
    --bind_password = 'xxxxxxxxxxxxxxxxxxxx', -- Bind password (optional if anonymous bind is supported)

    user = {
        basedn        = 'ou=People,dc=tu-harburg,dc=de',               -- The base DN where user records can be found
        filter        = '(uid=%u)',                                 -- Filter expression to find user records under basedn
        usernamefield = 'uid',                                         -- The field that contains the user's ID (this will be the username portion of the JID)
        namefield     = 'cn',                                          -- The field that contains the user's full name (this will be the alias found in the roster)
    },
}
```

```
Apr 07 13:54:18 bosh123-foobar-321        debug   Received[c2s_unauthed]: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Apr 07 13:54:18 passat.rz.tuhh.de:auth_ldap2    debug   _M.bind - no DN found for username = MY_UID                                                               
Apr 07 13:54:18 passat.rz.tuhh.de:saslauth      debug   sasl reply: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text>Unable to authorize you with
the authentication credentials you&apos;ve sent.</text></failure>
```

**Comment by MaadixNet** [comment]
Why do you need the placeholder?  Through the usernamefield you are already saying that the uid needs to match the username. Then in filter use something like (objectClass=organizationalPerson) or whatever objectClass you have. 
Try something like this.

```
    user = {
        basedn        = 'ou=People,dc=tu-harburg,dc=de',               -- The base DN where user records can be found
        filter        = '(objectClass=organizationalPerson)',                                 -- Filter expression to find user records under basedn
        usernamefield = 'uid',                                         -- The field that contains the user's ID (this will be the username portion of the JID)
        namefield     = 'cn',                                          -- The field that contains the user's full name (this will be the alias found in the roster)
    },

```

**Comment by aboettger-tuhh** [comment]
The filter limits the amount of results of the request to the LDAP server. Depending on the server settings, not all results may be returned.

Running a LDAP search without any filters is likely to be a waste of time and resource.

What **works** is a filter that does not exceed the limit of the server's records.

What does **not work** is a filter that exceeds the limit of the server's records.

**Comment by MaadixNet** [comment]
I am not saying that you should run a search without a filter. My point is that the placeholder is not working in this case.
You can add any additional filter to limit your search, such as 

`(&(objectClass=organizationalPerson)(authorizedService=jitsi))`

or any other filter you can think of, but not a placeholder.
The 'usernamefield'  is working as your input filed...your placeholder.
This is working for us. You could give it a try.
Up to you

**Comment by aboettger-tuhh** [comment]
Unfortunately this does not work for us because there are more than 500 accounts.

**Comment by ignlazaro** [comment]
Good afternoon,

I am having the same problem, I can authenticate with sAMAccountName but not with name@domain.com

Any ideas?

Thank you very much.

**Comment by ignlazaro** [comment]
Good afternoon,

I am having the same problem, I can authenticate with sAMAccountName but not with name@domain.com

Any ideas?

Thank you very much.

**Comment by MaadixNet** [comment]
Check the  code in /usr/lib/prosody/modules/ldap.lib.lua 

maybe it gives you tips.
These are the important part for the search query and the bind
```
function _M.singlematch(query)
    local ld = _M.getconnection();

    query.sizelimit = 1;
    query.scope     = 'subtree';

    for dn, attribs in ld:search(query) do
        attribs.dn = dn; 
        return attribs;
    end 
end
```
The  _M.singlematch function is a search query, which accepts an input param (query) in which you can use a filter, a base dn and a username.
It is returning one single match. the dn provided which in your case is uid=THEINPUTUSERNAME,ou=People,dc=tu-harburg,dc=de
which should be unique. 

So the 'usernamefield'  string seems to be  used to build the dn, not the filter.

Here you can find accepted param for the search command:
http://math2.org/luasearch/lualdap.html#conn_search

```
    local who = _M.singlematch {
        attrs     = params.user.usernamefield,
        base      = params.user.basedn,
        filter    = filter,
    };
  .......  

    local conn, err = ldap.open_simple(params.hostname, who, password, params.use_tls);
```

The bind is finally performed using 'who' which is the singlematch result. The distinguished name.
In 'filter' you can put any additional filter you need.

**Comment by ignlazaro** [comment]
Thank you very much for the advice.

Similarly, the value params.user.usernamefield is a string.
If I replace this value with that of the mail xxxx@xxx.xx.xx it should work, but no.

I show you my cfg:

authentication = 'ldap2'

ldap = {
    hostname = 'xxx.xxx.xx.xx',
    bind_dn = 'CN=xxxx,CN=xxxx,DC=xxxx,DC=xxx,DC=xxx',
    bind_password = 'xxxxxxxx',
    use_tls = false,
    user = {
        basedn = 'dc=xxxx,dc=xxx,dc=xxx',
        filter = '(&(objectClass=organizationalPerson) memberof=CN=xxxx,CN=xxxx,DC=xxxx,DC=xxx,DC=xxx))',
        usernamefield = 'userPrincipalName', -- value with xxxx@xxxx.xx.xx
        -- usernamefield = 'sAMAccountName', -- works
        namefield = 'cn',
    },
}
----------

Regards

**Comment by aboettger-tuhh** [comment]
I have a problem with %u in the filter

> Good afternoon,
> 
> I am having the same problem, I can authenticate with sAMAccountName but not with [name@domain.com](mailto:name@domain.com)
> 
> Any ideas?
> 
> Thank you very much.

Isn't the same problem.

**Comment by saghul** [comment]
I'm closing this since it's a Prosody related question, you'll get better answers asking in their community.
