### ISSUE TITLE
Display jitsi version(s) somewhere in the Web GUI

### ISSUE THREAD

**Issue by richb-hanover** [jitsi/jitsi-meet#5748]
**Is your feature request related to a problem you are facing?**
When troubleshooting, it's difficult (impossible?) to find the version(s) of jitsi that are currently in operation. (I know I can go to my server and use `dpkg -l | grep jitsi` but I don't think anything like this is available through the GUI.)

**Describe the solution you'd like**
A simple, unobtrusive place for this information would be a new "tab" in the Settings, ie: 

> Devices | Profile | **Version** | More

**Describe alternatives you've considered**
The Version text could even be the output shown below:
```
deploy@atl3:~$ dpkg -l | grep jitsi
ii  jitsi-meet                      2.0.4384-1                                  all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.3969-1                                  all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.3969-1                                  all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.3969-1                                  all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.3969-1                                  all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.1-164-gfdce823f-1                         all          WebRTC compatible Selective Forwarding Unit (SFU)
```

**Comment by saghul** [comment]
We are logging the versions in the console too, in case that helps. I don't think adding them to the Settings tab is aa good idea because it's not something the user can do anything with. You'll likely ask for the browsser console logs anyway, and verssionss will be logged therein.

**Comment by richb-hanover** [comment]
> We are logging the versions in the console too, ...

Do you mean in the browser Console? That would be a good enough workaround to my question - I know how to "Inspect Element" in the browser. (However, I don't see a clear indication in the Console window today...)

But it won't be a long-term solution as Jitsi has more and more success. There'll be lots of Jitsi servers deployed with varying releases, and having easily-reviewed version numbers will help with bug reporting.

**Comment by damencho** [comment]
Open page source and you can see the web version in some of the links as v=... And if you open the console log and filter by string version and open two tabs you will see prosody, jicofo and jvb version. This is what we use for debugging don't think anything more is needed. Anyway if you debug something you open dev console in the browser and everything is there.

**Comment by mykhal** [comment]
I do not confirm there are any console messages containing "version" substring, and do not think that e.g. `GET https://meeting.myserver.example/css/all.css?v=6447` is usable as sw version info.

**Comment by saghul** [comment]
<img width="562" alt="Screenshot 2022-12-02 at 12 41 52" src="https://user-images.githubusercontent.com/317464/205285184-d722d9ac-4636-4b60-b892-217c205a5e0d.png">

**Comment by janvlug** [comment]
As an end user, I sometimes use Jitsi hosted by others. Sometimes I experience issues. When reporting them, I would like to be able to report the Jitsi server version. It would be convenient if this information was accessible just via the web interface. Maybe in: Settings > Version

**Comment by farvardin** [comment]
it's not very clear. On the official meet.jit.si in the source code I can see ``[v=8077.4968](view-source:https://web-cdn.jitsi.net/meetjitsi_8077.4968/css/all.css?v=8077.4968)``  but on github I can see the latest version is 2.0.9584 that doesn't make sense.

**Comment by richb-hanover** [comment]
The original report was more than four years ago. This should remain closed, and people should open a new issue if this remains a problem.
