### ISSUE TITLE
Default setup for localhost can't work: 'Cannot issue for "localhost"'

### ISSUE THREAD

**Issue by Synchro** [jitsi/jitsi-meet#5752]
## Description

I'm installing on Ubuntu alongside apache running existing sites. `apt install jitsi-meet` works, but when I run `install-letsencrypt-cert.sh`, it's clear that it's trying to install for `localhost`, which can't work. Since I'm never asked for the domain that Jitsi should run on (which is not the same as the server's own hostname), I don't see how this could *ever* work, and I can't see anything in the docs about this. By inspecting what the scripts look for, I gather that it expects domain-specific config files in `/etc/jitsi/meet/<domain>-config.js`, so I made one to match my domain, but it still tries to issue a cert for `localhost`.
---

## Current behavior
---
```
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
-------------------------------------------------------------------------
This script will:
- Need a working DNS record pointing to this machine(for domain localhost)
- Download certbot-auto from https://dl.eff.org to /usr/local/sbin
- Install additional dependencies in order to request Let’s Encrypt certificate
- If running with jetty serving web content, will stop Jitsi Videobridge
- Configure and reload nginx or apache2, whichever is used

You need to agree to the ACME server's Subscriber Agreement (https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf)
by providing an email address for important account notifications
Enter your email and press [ENTER]: webmaster@example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
An unexpected error occurred:
The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "localhost": Domain name needs at least one dot
Please see the logfiles in /var/log/letsencrypt for more details.
```
## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---
```sh
apt install jitsi-meet
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```

# Environment details
---
Ubuntu 16.04

**Comment by saghul** [comment]
> Since I'm never asked for the domain that Jitsi should run on (which is not the same as the server's own hostname)

That is what we ask for. We may want to clarify, come to think of it.

**Comment by Arthur-Kamau** [comment]
@saghul how did you solve the issue?
