### ISSUE TITLE
Installer .deb and automation

### ISSUE THREAD

**Issue by awienecke** [jitsi/jitsi-meet#5759]
**Is your feature request related to a problem you are facing?**
When attempting to automate the install from the .deb (amazing job, btw, it installs coturn, configures it, and everything!) the ncurses interface kind of... makes this a manual task

**Describe the solution you'd like**
The option to pre-define the answers to all the questions either with environment variables or with an expected config file somewhere. Or; if this is already possible, provide some documentation for it?

**Describe alternatives you've considered**
I've attempted to run an expect script, but it fails with the ncurses prompts.

**Comment by damencho** [comment]
Please use the community forum when having questions before opening new issues.

These are standard Debian packages and this can be done with pure debian commands. Here is an example I use:
```
echo "jitsi-videobridge jitsi-videobridge/jvb-hostname string your.domain.com" | debconf-set-selections
echo "jitsi-meet-web-config jitsi-meet/cert-choice select 'Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)'" | debconf-set-selections
apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install jitsi-meet
```
