### ISSUE TITLE
Increase P2P participants from 2 to 3

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#5760]
Hi everyone,

I hope everyone is safe.
I remember seeing a similar thread about this a couple of years ago but it is now closed https://github.com/jitsi/jitsi-meet/issues/3581

In that thread @damencho mentioned the files I should look at to enable P2P with 3 participants.
https://github.com/jitsi/jitsi-meet/issues/3581#issuecomment-439631595

Since then I believe jitsi's code has changed quite a bit so I don't think those files are still relevant.

So the question I ask is where in the code do I have to poke around to change the threshold to 4 so that jvb doesn't automatically get involved as a soon as the 3rd participant enters.

Thanks!

**Comment by damencho** [comment]
There is no such feature as p2p for more than two participants. Always the 3rd one and everyone uses jvb.

Please use the community forum before opening new issues.

**Comment by pdarcos** [comment]
Hi @damencho 

I'm aware it is not available which is why I filed it here using the Feature requests template and not Bugs.

Do you prefer I open another ticket in the community forum instead?

Cheers

**Comment by damencho** [comment]
Sorry, I quickly responded without looking thoroughly. But the answer will be, that this feature will not be implemented in the official repos. If you want you are free to fork and work it on your own. p2p does not scale well with people's internet connection, where even one video upload sometimes is hard, but multiplying it, it will not work well.

**Comment by pdarcos** [comment]
No worries.

I'm aware it won't scale well, but for my particular use case 3 is the magic number and I'm sure it can handle 3 people in P2P mode.

I know I'll need to fork it and change the code, but I was hoping someone could point me in the right direction ;)

Thanks

**Comment by damencho** [comment]
Everything you need it in lib-jitsi-meet p2p session, jvb session.
