### ISSUE TITLE
Wrong size of UI elements in portrait mode 

### ISSUE THREAD

**Issue by sebastiantoro** [jitsi/jitsi-meet#5763]
## Description

I discovered a problem with the UI of jitsi-meet when entering with rotated screens (portrait mode) as opposed to when entering on regular horizontal screens (landscape mode). All the Ui elements have a wrong size when the screen is in portrait mode.

## Current behavior
![bug](https://aws1.discourse-cdn.com/business4/uploads/jitsi/original/2X/4/4fa1eeda60c526411b4f827ece3ac853128949c5.png)  

## Expected Behavior
Button should have the right sizes.

## Steps to reproduce
Enter meet.jit.si with a cellphone using Chrome's desktop mode and with the screen in portrait mode.

**Comment by l3d00m** [comment]
Does this also happen when entering meet.jit.si in Chrome without desktop mode enabled? I think the desktop mode on mobile isn't really supported by any application.
