### ISSUE TITLE
Defining tile view as default

### ISSUE THREAD

**Issue by jans23** [jitsi/jitsi-meet#5764]
**Is your feature request related to a problem you are facing?**

I would like Jitsi Meet to start in tile view by default. Currently this is not the case and users have to click the tile view button (at the bottom right) instead.

**Describe the solution you'd like**

Add a configuration parameter to specify Jitsi's default view.

**Describe alternatives you've considered**

Inform (novel)  attendees about the option to change their view manually. (Inexperienced users may not notice the option on their own.)

**Comment by kinafu** [comment]
Would be really nice to have, especially since many other similar apps start with the same layout.

So the on-boarding experience would become more convenient.

**Comment by munsifhayat** [comment]
We need to have the same functionality. @jans23  any leads on this ?

**Comment by AdriaandeJongh** [comment]
I'm hearing this complaint in my Jitsi meetings a lot, too!

**Comment by StephenDonnelly** [comment]
Likewise, the ability to configure the default view is being requested by our customers too. It would be great to be able to do this.

**Comment by wietsewarendorff** [comment]
It is possible using [the api](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe):

`api.executeCommand('toggleTileView');`

For example when using the iframe:

```
const domain = 'meet.jit.si';
const options = {
    roomName: 'JitsiMeetAPIExample',
    width: 700,
    height: 700,
    parentNode: document.querySelector('#meet')
};
const api = new JitsiMeetExternalAPI(domain, options);
api.executeCommand('subject', 'My Awesome room with tile view!');
api.executeCommand('toggleTileView');
const iframe = api.getIFrame();
```

**Comment by saghul** [comment]
This is something we have discussed and will happen. If anyone wants to take a crack at it I’ll help review.

**Comment by NodeGuy** [comment]
@wietsewarendorff It's actually not that straightforward to do with the API because the tile view setting is persisted between reloads.  I had to do this:

```JavaScript
  api.addEventListener(`videoConferenceJoined`, () => {
    const listener = ({ enabled }) => {
      api.removeEventListener(`tileViewChanged`, listener);

      if (!enabled) {
        api.executeCommand(`toggleTileView`);
      }
    };

    api.addEventListener(`tileViewChanged`, listener);
    api.executeCommand(`toggleTileView`);
  });
```

**Comment by wietsewarendorff** [comment]
> @wietsewarendorff It's actually not that straightforward to do with the API because the tile view setting is persisted between reloads.
You're right, I noticed after posting this. Looks like there is a PR open for the functionality you're looking for though: #6764

**Comment by pandel** [comment]
@NodeGuy 
Is it possible to add this API functionality to toggle the tile view to an existing installation, i.e. by modifiying some of the web components delivered to the client, too? Sadly, I am totally unfamiliar with JS so generally, I understand what you are doing here but am unsure how to integrate it...

**Comment by NodeGuy** [comment]
Hi @pandel, I understand your question but I don't know the answer.  My code is on a client I created that uses the [IFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe).

**Comment by ptandler** [comment]
Any chance to open this issue again?
I'm currently also looking for a way to have tile view as default for all meetings

**Comment by ptandler** [comment]
@NodeGuy your code above works perfectly, tanks for sharing!!

However, a somehow more straightforward way to do this would be nice. There's a PR around, which was not merged, but is closed, that would make this feature much more easy to implement: https://github.com/jitsi/jitsi-meet/pull/6764

I'd like to know why it wasn't merged. Anyway ...

**Comment by pratik9722** [comment]
@ptandler I have seen you PR & thanks for that but is it possible that we can also define pin participants by display name.
That way I can show which participan's video should are shown when title view is not enabled ( & also follow me options is not enabled by moderator )

**Comment by dbrgn** [comment]
I'm also looking for an option to configure the tile view as default view. It would be great if this could be configured through a variable in `web/interface_config.js`.

**Comment by Nemra1** [comment]
> ```js
>   api.addEventListener(`videoConferenceJoined`, () => {
>     const listener = ({ enabled }) => {
>       api.removeEventListener(`tileViewChanged`, listener);
> 
>       if (!enabled) {
>         api.executeCommand(`toggleTileView`);
>       }
>     };
> 
>     api.addEventListener(`tileViewChanged`, listener);
>     api.executeCommand(`toggleTileView`);
>   });
> ```

best answer here

**Comment by ammarsalman94** [comment]
@NodeGuy How do you add this on the server side so it applies to all connecting clients?

**Comment by roihershberg** [comment]
The option @ammarsalman94 described only works for me sometimes. It mostly enables it before I even joined the meeting and then it has no effect.
It would be so great to have a builtin solution to that like developed in #14504 .
