### ISSUE TITLE
Something wrong with https://hosted.weblate.org/projects/jitsi/

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5765]
I found that periodically the translation functionality is locked from adding/updating, moreover I didn't manage to add Ukrainian locale to the list of languages.

I added the list of translated manually locales to the newly created file languages-uk and in some time I found that all the strings are not translated.

Something strange is going with this functionality of translating the strings...

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5056
