### ISSUE TITLE
Cómo grabar una reunión?

### ISSUE THREAD

**Issue by danielpax1** [jitsi/jitsi-meet#5770]
Cómo puedo grabar las reuniones que tengo con mi estudiantes? Intenté hacer click en el botón de grabar y guardar el vídeo en mi dropbox, pero me dicen que disponen de grabadoras. Por favor, me pueden indicar el procedimiento para grabar estas reuniones.

**Comment by Kreijstal** [comment]
Esto no es un foro de soporte.

**Comment by Echolon** [comment]
@damencho here too
