### ISSUE TITLE
Prevent multiple sessions at once

### ISSUE THREAD

**Issue by damianpeterson** [jitsi/jitsi-meet#5777]
**Is your feature request related to a problem you are facing?**
We're using the web version of meet to chat with elderly parents and they often double-click the link we email to them which opens two or more feedback-ridden sessions in browser tabs. 

**Describe the solution you'd like**
It would be great if there was some way to detect that there is a second connection from the same browser/computer and disconnect it automatically so that there is only one running.

**Comment by engesin** [comment]
> It would be great if there was some way to detect that there is a second connection from the same browser/computer and disconnect it automatically so that there is only one running.

This sound greats. is there any plan to prevent multiple joins with multiple taps :)
