### ISSUE TITLE
Mobile link welcome page reverse buttons

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jitsi-meet#5779]
When you share a link the other person currently get this view:

![XoNlVMdUSlybb2lKiyd2og](https://user-images.githubusercontent.com/2282799/78764657-62dd6600-7976-11ea-8a12-d074a549faad.jpg)

...which looks more like a dark-pattern to always force the user to press download instead of join.

Yes the user might not have the app but, at least on Android, pressing the intent link when you don't have the app will pop-up the Store selector _(F-Droid, Aurora or I guess even Play)_, making the Download button useless somewhat.

Can this be reduced to JOIN or at least reorder and emphasis JOIN as a big blue button and Download as a link?

**Comment by ageekhere** [comment]
or check if you have the app and auto open that

**Comment by licaon-kter** [comment]
Not sure the website can do that.

**Comment by Echolon** [comment]
Friends of mine told me the same and were hasseling to open the link with the app.

**Comment by licaon-kter** [comment]
Fixed already bot, get smart :)
