### ISSUE TITLE
Option to turn off audio and camera before starting a meeting

### ISSUE THREAD

**Issue by blackshady** [jitsi/jitsi-meet#5781]
**Is your feature request related to a problem you are facing?**
Yes, it is. Before starting a meeting, I manually try to cover my camera with my hands and once the meeting starts I officially turn off my camera.

**Describe the solution you'd like**
 It would be nice if we can see an option to turn on or off our camera or audio before joining a meeting.
 it can simply be a dialog that prompts the user with this option.

**Describe alternatives you've considered**
None.

**Comment by Syonyk** [comment]
What platform?

In the mobile apps, under settings, there are toggles to start with audio and video muted.

There don't appear to be such settings in the browser client.

In the server, if you run your own instance, you can set the startWithVideoMuted and startWithAudioMuted options in the config.js file to control this.

**Comment by jwsp1** [comment]
This would definitely be nice for meet.jit.si in browser.

**Comment by licaon-kter** [comment]
@blackshady Did you select "always allow" in the browser permission pop-up for camera/mic? Maybe remove those permissions and allow them when you feel like been seen/heard instead.

**Comment by l3d00m** [comment]
Please see #2737
