### ISSUE TITLE
Support for revision 0.7 of XEP-0215

### ISSUE THREAD

**Issue by weiss** [jitsi/jitsi-meet#5786]
Jitsi Meet (optionally) uses [XEP-0215][1] to discover STUN/TURN services.  Version 0.7 of the XEP [bumped the namespace][2] to `urn:xmpp:extdisco:2` in 2015, it would be nice if Jitsi Meet could use that instead of `extdisco:1`.  Presumably, you could just use `extdisco:2` in place of `extdisco:1` and ignore the new attributes returned by the server.

Prosody's [`mod_turncredentials`][3] [supports][4] the new namespace for some months now; and I'm currently adding XEP-0215 support to ejabberd and would be happy not having to support the old one :smile:

[1]: https://xmpp.org/extensions/xep-0215.html
[2]: https://xmpp.org/extensions/xep-0215.html#appendix-revs
[3]: https://modules.prosody.im/mod_turncredentials.html
[4]: https://hg.prosody.im/prosody-modules/rev/2bbf655431be

**Comment by damencho** [comment]
Actually we use a slightly modified version of the module that supports multiple turn hosts as response.
But we can port the changes.

**Comment by Neustradamus** [comment]
@damencho: Yes it is important to have the up-to-date module with your changes.
Maybe your changes can be integrated in the original module...

**Comment by licaon-kter** [comment]
Any news on this?

ejabberd 20.04 with support was released already: https://www.process-one.net/blog/ejabberd-20-04/

And more servers are getting STUN/TURN support day by day: https://compliance.conversations.im/test/turn/

But at least 42% of them (https://nitter.net/iNPUTmice/status/1257543944486785030) can't enable the use of TURN for Jitsi Meet since this is a Prosody (custom module) only thing :(

**Comment by Neustradamus** [comment]
Always here.

**Comment by licaon-kter** [comment]
@damencho So according to https://jitsi.github.io/handbook/docs/devops-guide/turn it should use the updated XEP temp credentials mechanism as defined by the IETF draft? But only in 1:1?

**Comment by weiss** [comment]
Seems this [has been implemented][1], many thanks!

[1]: https://github.com/jitsi/lib-jitsi-meet/pull/1472
