### ISSUE TITLE
Wrong Microphone Selected When Joining Meeting

### ISSUE THREAD

**Issue by PolynomialDivision** [jitsi/jitsi-meet#5787]
When I join the meeting the "Default"-Microphone is selected.
![defaultmicrophone](https://user-images.githubusercontent.com/10708466/78779893-13ab2b80-799e-11ea-88b0-e24c0c7a69b8.png)
You have to manually select "Built-in Audio Analog Stero". You don't get a warning or other useful information. User could think that the Jitsi-Session has an error.

- **OS:** Manjaro (Linux)
- **Jitsi min.js version:** 3969

**Comment by l3d00m** [comment]
Tbh it seems like an error with your setup / OS, usually the default microphone is the correct one. Especially when you have only one microphone, your OS should select that as the default.

I also think that Jitsi is outputting a warning when no microphone input is detected.

Should you have any further ideas on how to improve this or should this not happen in other applications, feel free to reopen.
