### ISSUE TITLE
camera selection does not persist after opening screenshare

### ISSUE THREAD

**Issue by Sloth-on-meth** [jitsi/jitsi-meet#5790]
Hi!

i have two webcams. An integrated webcam, and a C920. i manually pick the c920 at the start of the call. when i start screensharing, and then go back to camera, it will pick the default camera again, the integrated webcam. Can we make this choice persist?

**Comment by jallamsetty1** [comment]
Hey there,
The camera settings are expected to persist when toggling between camera and screenshare. I am not able to reproduce this issue on meet.jit.si with chrome. Can you please give me more details about your setup and what browser you are using ?

**Comment by Echolon** [comment]
@Sloth-on-meth have you had time to review the issue and may provide some more detailed information? That would help addressing your issue.

Have you also tested this: https://test.webrtc.org/


---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
