### ISSUE TITLE
I built the Jitsi-meeting system manually,But the conference system is wrong

### ISSUE THREAD

**Issue by zzdczhang** [jitsi/jitsi-meet#5791]
The error log:

Logger.js:125 [modules/xmpp/moderator.js] <d._allocateConferenceFocusError>:  Focus error, retry after 1000 
 xmlns="jabber:client" type="error" to="t0br8tetdzcvafv1@10.206.132.113/5KOlbl77" from="focus.10.206.132.113" id="e541654c-3c3c-4875-9ff2-70c1cb81fbb2:sendIQ"><error code="500" type="wait"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>

May I ask which service has the problem?

**Comment by damencho** [comment]
Jicofo is the focus.

Please use the community forum when you have questions before opening new issues.
