### ISSUE TITLE
Annoying breath sound "incomingMessage.wav"

### ISSUE THREAD

**Issue by RedCore161** [jitsi/jitsi-meet#5794]
I am hearing a lot of jitsi-streams right now and all of them have this breath sound, when a message was send. Can you disable this in the admin gui? If not please make this a point where people trying to fix this, can find an anwser! thanks

> export const INCOMING_MSG_SOUND_FILE = 'incomingMessage.wav';

from react/features/chat/sounds.js

**Comment by luixxiul** [comment]
unless you compile by yourself, how about seeking that file and just rename it?

**Comment by RedCore161** [comment]
Better replace the file with an empty incomingMessage.wav - there might be a crash otherwise. But as a hot-fix: yes

**Comment by luixxiul** [comment]
yeah I also would prefer to replace it with an empty file with the same filename.

**Comment by cyroxx** [comment]
I ended up using a customization in the nginx configuration:

```
    # custom message sound
    location = /sounds/incomingMessage.wav {
        add_header 'Access-Control-Allow-Origin' '*';
        alias /var/www/<custom_path>/<custom_sound>.mp3;
    }

    #ensure all static content can always be found first
    location ~ ^/(libs|css|static|images|fonts|lang|sounds|connection_optimization|.well-known)/(.*)$
    {
        add_header 'Access-Control-Allow-Origin' '*';
        alias /usr/share/jitsi-meet/$1/$2;
    }
```

This way, I do not need to interfere with the jitsi files and the customization is clearly documented.
