### ISSUE TITLE
Chrome Browser Debian Stretch Camera Glitches on Entry to Meet

### ISSUE THREAD

**Issue by motrengaw** [jitsi/jitsi-meet#5795]
While the camera will eventually work if the user knows to persevere, a flurry of equivocal behavior on start up may lead many unfamiliar with this excellent platform to dismiss it as unreliable.
It is rare that the camera "just works".  The user allows the use of camera and audio, but all too frequently enters to a blank screen.  Toggling the "tile view" will usually bring the camera into play, but the user has to know to try that.  Even then, when first started the camera is frozen or appears to be running at an extremely low frame rate: 1-2 fps.  Toggling the video on and off usually fixes this, but again...the user must know to do this from experience.  Lastly, at some point during this thrashing about, the "Unable to Access Camera" splash is thrown up...even though the  camera has in fact come online behind the splash. (I'm reporting from that splash instead of dismissing in this post).
Most of my experience with Jistsi has been on Linux, but I have tried on serval occaisions to  use the meet.jit.si resource for our non-profit meetings among users on OSx, MS, and Android platforms., and have also tried to deploy our own server on a linode (Debian Stretch).  But these apparent browser-side issues have frustrated our users and been institutionally embarrassing enough to cause us, reluctantly, to look elsewhere.  I'll keep returning to Jitsi to check your progress in maturing your brower-based access for professional use, and continue to use it in private among my friends via my shared knowledge of the futtering about required to get a session started.
Thanks for what is clearly a great deal of hard work and what may yet become a stellar, and otherwise very well implemented resource.

**Comment by MagicFab** [comment]
The Chromium (not Chrome) browser version in Stretch is very old... The current stable Debian version is 10 (Buster), Perhaps using the current version of Debian for both the server and clients will help. I am using both without any issues.

**Comment by Echolon** [comment]
@motrengaw have you tried to upgrade to a new version and retried?

I don't use Chrome, but have a look at this: https://www.google.com/linuxrepositories/

**Comment by Echolon** [comment]
@motrengaw are you still having this issue?
