### ISSUE TITLE
access to camera denied

### ISSUE THREAD

**Issue by chupalo11** [jitsi/jitsi-meet#5797]
fix this now please, jitsi doesnt allow me to access my camera and i have granted all the permissions. what is happening?

**Comment by jallamsetty1** [comment]
Hey there, can you please provide more details about the issue you are facing ? Please include all the relevant information like the platform, browser and version information. What error do you see on the UI ?

**Comment by Echolon** [comment]
**Non-working camera meta-issue** #5425
@damencho can be closed
