### ISSUE TITLE
Set up Github Sponsor in Jitsi account

### ISSUE THREAD

**Issue by nmercado1986** [jitsi/jitsi-meet#5802]
**Is your feature request related to a problem you are facing?**
I would like to sponsor the project.

**Describe the solution you'd like**
Implement Github sponsoring on the repos.

**Describe alternatives you've considered**
Contributing via Patreon or any other link?

**Comment by dhrp** [comment]
I think this is a great idea. Nowadays a lot of people are looking for alternatives to physical meetings (and Zoom etc), and I'm sure the core maintainers already felt the urgency, but some $-support would could also them free up time for this.

**Comment by saghul** [comment]
We are not going to pursue this for the time being, since there are implications as we are part of a larger company.

We may revisit it in the future.

Thanks for the suggestion though!
