### ISSUE TITLE
dificultades para transmisión en vivo

### ISSUE THREAD

**Issue by NILDANOEMI** [jitsi/jitsi-meet#5805]
Buenas tardes! Quiero realizar una transmisión en vivo desde JITSI pero sale un cartel que dice TODOS LOS STREAMINGS ESTÁN OCUPADOS ACTUALMENTE.

**Comment by Echolon** [comment]
> Difficulties for live broadcast 
Good afternoon! I want to make a live broadcast from JITSI but there is a sign that says ALL THE STREAMINGS ARE BUSY CURRENTLY.

I think you can close this.
