### ISSUE TITLE
Can't get a streamer

### ISSUE THREAD

**Issue by Dale1112** [jitsi/jitsi-meet#5809]
Receiving error "All streamers are currently busy"

**Comment by Echolon** [comment]
@damencho can be closed

**Comment by gwolf** [comment]
I opened an issue yesterday (#6019). It got redirected to this one. I think mine at least explains the situation — What does this mean? What should we do?

**Comment by luixxiul** [comment]
@gwolf sorry if it hurt your feeling. I just related that with this one. I am pretty sure that the issue was recognized by the team and they are working on the fix.
