### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by FiorellaCampanella** [jitsi/jitsi-meet#5810]
i can't conect my camera and it works in others plataforms. 
Also when i oppen jitsi appperars a banner that says " allow jitsi to use your camera" after i allow jitsi it banner can´t be close

**Comment by GNUDimarik** [comment]
@FiorellaCampanella please let me know what plaftorm do you use and what version?

**Comment by Echolon** [comment]
**Non-working camera meta-issue** #5425
@damencho can be closed
