### ISSUE TITLE
Apache - Harden/Complete SSL/TLS

### ISSUE THREAD

**Issue by C0RD** [jitsi/jitsi-meet#5821]
## Description
Current Jitsi-Packages contain an example and autoconfiguration for Apache Webserver.
These contains Configuration for HTTPS.

## Current behavior
The package provides weak SSL and Cipher configuration. It also misses a CertificateChain.

## Expected BehaviorSSLProtocol
Provide security by default, by refreshing the examples. (Users are free to weaken configuration again)

## Possible Solution
Follow Best Practices https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices

  SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1  # disable deprecated Protocols and enable TLSv1.3 (and newer ones as they become available.
  SSLCipherSuite HIGH:!aNULL:!MD5  #  that can be hardened even further.

Also there should be a SSLCertificateChainFile-Configuration as soon as it is available (Letsencrypt!)  (I encountered problems connection with Android-Jitsi-Meet when it isn't set, until the device has learned the Chain (not extensivly tested))

## Steps to reproduce
https://www.ssllabs.com/ssltest/analyze.html?d=meet.jit.si&s=76.223.28.75&latest

# Environment details
Apache-Config

**Comment by saghul** [comment]
@JonathanLennox did you fix this already the other day, or was it just for nginx?

**Comment by JonathanLennox** [comment]
Yes, my change in https://github.com/jitsi/jitsi-meet/pull/6806/files should fix this.
