### ISSUE TITLE
Camera flip iOS/Android 

### ISSUE THREAD

**Issue by silentshotghost** [jitsi/jitsi-meet#5822]
Make a shortcut on the video home screen of a group call to easily flip the camera, so you don’t have to go through multiple prompts. The icon for the camera flip could look similar to the iPhones default camera app.

**Comment by saghul** [comment]
We cannot put all the button on the main screen. Thus we keep evaluating adjusting as we move along. For now, the button will remain on the secondary menu.

**Comment by patelmohit829** [comment]
@saghul Where can I find the secondary menu in Android??

**Comment by DiamondJewelryLive** [comment]
Any body figure this out??
