### ISSUE TITLE
Inconsistentcy between new source picker and settings

### ISSUE THREAD

**Issue by timboxyz** [jitsi/jitsi-meet#5823]
On Firefox 75 on OSX 10.14.6 (Mojave) using jitsi-meet 2.0.4420-1.  Clicking on the new source picker icon down arrow next to the Mic enable/disable icon shows a number of selectable sources (mic, Bluetooth etc). However using the original settings method there is no choice, only the current selection (which is the system default) is shown.

The new selector, despite showing the actually connected devices, does not allow any re-selection though.

**Comment by Echolon** [comment]
@timboxyz may you provide a screenshot too?

**Comment by timboxyz** [comment]
<img width="269" alt="Audio-settings" src="https://user-images.githubusercontent.com/58913363/82899998-bf5f0980-9f53-11ea-8cad-fe3a1861a247.png">
The above is all I get in the settings menu for audio, there is no pull down selector

<img width="335" alt="Mic-pulldown" src="https://user-images.githubusercontent.com/58913363/82900012-c4bc5400-9f53-11ea-8db1-14499d798199.png">

The above is the list I get  When using the Mic icon pulldown from the main screen.

By contrast the below is the video settings pulldown, I cannot show the equivalent from the main screen icon as it causes to Firefox to exit.
<img width="269" alt="Video-settings" src="https://user-images.githubusercontent.com/58913363/82900268-2a104500-9f54-11ea-8ba6-ba284ef781d0.png">

**Comment by saghul** [comment]
This is due to a Firefox limitation. There can only be one microphone open at a time. In the settings window you can open another microphone and test if before applying it live (you can verify this in Chromium) but we cannot do that on Firefox... yet.

**Comment by jallamsetty1** [comment]
I think we should disable audio settings popup for Firefox since it is confusing.

**Comment by jallamsetty1** [comment]
Audio settings popup has been disabled for Firefox.
