### ISSUE TITLE
Cannot edit any language on weblate though not locked

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5826]
Hi! I cannot edit any language in weblate, though the state of the file is unlocked (no lock icon). The Save button is not active, only Suggestion is available.

Moreover, I tried to add Ukrainian locale numerous times, using pull requests or through weblate, and it doesn't appear in templates of languages.

Please, help me/us to fix this issue.....

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by Mejans** [comment]
Hello @damencho will you merge the work done there?
I took the chance to use weblate checkers to improve my translations, I wouldn't like to lose them :(
