### ISSUE TITLE
Add shared whiteboard

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5830]
Please, add the shared whiteboard, which may be used for placing text, images, drawing during a conference by all participants with further downloading it in the form of document and/or image file.

**Comment by davidak** [comment]
@ostasevych does it make sense to add this to jitsi while BigBlueButton is a more complex software that support such features? why don't you use the software that provides the features you like?

**Comment by ostasevych** [comment]
> @ostasevych does it make sense to add this to jitsi while BigBlueButton is a more complex software that support such features? why don't you use the software that provides the features you like?

Well, I see Jitsi as a good competitive in-house solution, and this functionality is not something outstanding... Meanwhile, as I've got the Shared document functionality is no more maintained?...

**Comment by davidak** [comment]
maybe it's out of scope

i like jitsi-meet to focus on beeing simple and easy to use while BigBlueButton is a big more complex software with advanced features (i actually never used it, but jitsi for years and i don't miss anything. it's just perfect and works (in Chromium, lol))

that ways, we have two good solutions to choose from for our use-case

the readme says "Secure, Simple and Scalable Video Conferences", so my question is, will it still be simple with more features like whiteboard or does it overwhelm some users when there are more buttons and features

**Comment by ostasevych** [comment]
> maybe it's out of scope
> 
> i like jitsi-meet to focus on beeing simple and easy to use while BigBlueButton is a big more complex software with advanced features (i actually never used it, but jitsi for years and i don't miss anything. it's just perfect and works (in Chromium, lol))
> 
> that ways, we have two good solutions to choose from for our use-case
> 
> the readme says "Secure, Simple and Scalable Video Conferences", so my question is, will it still be simple with more features like whiteboard or does it overwhelm some users when there are more buttons and features

Thank you for your thoughts. I also share clean approach to solutions. What I know is that there have been Etherpad shared document extension, which is now deprecated (?). I suggest to have options, which may be enabled or disabled by admins if needed. At the same time, please, look at high waves of new solutions on the market due to lockdown. I believe, Jitsi may provide reliable services staying FOSS.

**Comment by davidak** [comment]
>I suggest to have options, which may be enabled or disabled by admins if needed.

I support that :+1: 

>At the same time, please, look at high waves of new solutions on the market due to lockdown. I believe, Jitsi may provide reliable services staying FOSS.

i often read that jitsi is not very reliable and had minor hicups myself while BBB works very reliably and also scales well. so please don't use development resources for new features that can be used to make the product more reliable!

If there is a PR from the community which adds optional whiteboard, i see no problem to merge it.

**Comment by heylix** [comment]
Since there is already an integration for etherpad, one could possibly try to integrate [Cryptpad](https://cryptpad.fr/), which features a whiteboard mode. Many teachers would appreciate that :)

**Comment by ostasevych** [comment]
> Since there is already an integration for etherpad, one could possibly try to integrate [Cryptpad](https://cryptpad.fr/), which features a whiteboard mode. Many teachers would appreciate that :)

Is Ethetpad still supported by Jitsi? Is Cryptpad opensource solution?

**Comment by ericschdt** [comment]
Duplicate: https://github.com/jitsi/jitsi-meet/issues/5295

**Comment by Echolon** [comment]
Thanks @ericschdt
