### ISSUE TITLE
No response received within reply timeout - While waiting for establishing TLS

### ISSUE THREAD

**Issue by shellshocker** [jitsi/jitsi-meet#5832]
I'm using the quick-install version on my Debian Buster server.

When I change something in the config file:
`/etc/jitsi/meet/www.mydomain.de-config.js`
and initiate a restart of services to take effect:
```
service jicofo restart
service jitsi-videobridge2 restart
service prosody restart
service nginx restart
```
I get this error message in jvb.log:

> 2020-04-09 15:04:51.539 WARNUNG: [34] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#643: [MucClient id=shard hostname=localhost] error connecting
> org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS
> 	at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:93)
> 	at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:272)
> 	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:157)
> 	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:128)
> 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:908)
> 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
> 	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:638)
> 	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 2020-04-09 15:04:56.490 WARNUNG: [36] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary: XMPPConnection was not authenticated

JVB stops working. Even after a restart. What helps:
`update-ca-certificates -f`

Everything starts working as expected. Any ideas?

**Comment by damencho** [comment]
You may have another error before that which is the source of the problem `XMPPConnection was not authenticated`. There is a known installation problem with Debian 10, which is now fixed in debian unstable packages (which will soon go into stable). The problem was with re-order of the install sequence (asking for jvb password where it shouldn't) and having wrong jvb password in sip-communicator.properties and in prosody.

**Comment by damencho** [comment]
To fix it you can go to /etc/jitsi/videobridge/sip-communicator.properties, find the password from the value of this key: `org.jitsi.videobridge.xmpp.user.shard.PASSWORD` and do
`prosodyctl register jvb auth.yourdomain correctSecret` (change yourdomain and correctSecret) and restart jvb `service jitsi-videobridge2 restart`. Does that make a change?

**Comment by shellshocker** [comment]
Hmm no.
But I saw something strange. Maybe this is related. I'm using a domain with www. So for example:
www.test.de

When I check **/etc/prosody/conf.avail/www.kuketz-meet.de.cfg.lua**
```
muc_mapper_domain_base = "www.test.de";
[...]
VirtualHost "auth.www.test.de"
    ssl = {
        key = "/etc/prosody/certs/auth.www.test.de.key";
        certificate = "/etc/prosody/certs/auth.test.de.crt";
    }
    authentication = "internal_plain"
[...]
```
This **auth.www.test.de** seems wierd.

**Comment by damencho** [comment]
Those are internal to the system and not exposed outside. You just need to use it like that:
`prosodyctl register jvb auth.www.test.de.key secret`

**Comment by shellshocker** [comment]
Thanks @damencho I have done that. Nothing changes.
`update-ca-certificates -f `
is still necessary.

**Comment by Mebus** [comment]
> You may have another error before that which is the source of the problem `XMPPConnection was not authenticated`. There is a known installation problem with Debian 10, which is now fixed in debian unstable packages (which will soon go into stable). The problem was with re-order of the install sequence (asking for jvb password where it shouldn't) and having wrong jvb password in sip-communicator.properties and in prosody.

The current unstable update (2.0.4456-1) fixed this stange issue for me. Thanks! :blush:
