### ISSUE TITLE
Blurring causes freezing

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5836]
Blurring beta functionality doesn't work with Google Chrome causing freezing the tab totally.

**Comment by Syonyk** [comment]
Beta functionality is beta?

A console log or crash log would be useful.

**Comment by jbis9051** [comment]
Just implemented the blur feature in a much more optimized way for a separate project. Gonna open source that part and push to Jitsi.

**Comment by saghul** [comment]
Thanks @jbis9051 !

**Comment by jbis9051** [comment]
So, I've been doing some more testing and was able to get it to near zoom like speed when doing background replacement, however the blur effect really slows it down. Its still much more performant than the current Jitsi implementation but very slow. I don't really want to take the time to build a Jitsi image upload for replacement interface so I am just going to fix the current script to implement my changes and someone else can make the interface for image replacement.

**Comment by jbis9051** [comment]
Alrighty. Virtual Background working without noticeable performance impact even with bodypix on high. Blur has performance impacts but its very usable.

I'm going to clone jitsi this weekend and add it. Someone will prob need to test it.

**Comment by jbis9051** [comment]
So...good news and bad news.

The bad news is I wasn't able integrate it into Jitsi yet as I didn't realize jitsi used flow (why?)  so I need to figure out how to implement it.

The (really) good news is I finally got blur to be near virtual background speed. It works really fast and with virtually no performance impact.

**Comment by jbis9051** [comment]
TimerWorker seems to break chrome so i'm removing, someone can add it back one they fix it

**Comment by jbis9051** [comment]
Any update on the PR?

**Comment by mdannehl** [comment]
I also can't wait to hear something about the PR.

I think improving the performance of the blurring feature is very important - especially in context of the still ongoing discussion about different video conference tools and their features. Blurring is currently barely usable.
