### ISSUE TITLE
Impossibilità di registrare video-lezioni

### ISSUE THREAD

**Issue by Cammisa61** [jitsi/jitsi-meet#5839]
Sono una docente che utilizza weschool. Ho necessità di registrare le mie video - lezioni ma quando richiedo questa funzione compare la scritta registratori occupati

**Comment by bhack** [comment]
Please use English or translate it with some service like https://www.deepl.com/translator

**Comment by Cammisa61** [comment]
impossible to record video lectures
When you activate the rec function it says that the recorders are busy

Il giorno gio 9 apr 2020 alle ore 17:43 bhack <notifications@github.com> ha
scritto:

**Comment by Echolon** [comment]
Non-working camera meta-issue #5425
@damencho can be closed
