### ISSUE TITLE
Redirect to "unsupported browser" page

### ISSUE THREAD

**Issue by ulab** [jitsi/jitsi-meet#5846]
**Is your feature request related to a problem you are facing?**
I'd really like to be able to modify the "It looks like you're using a browser we don't support." page without having to fiddle with the code and having to rebuild the app.

The idea is to be able to explain to users what's wrong and give more options than just "Chrome".

**Describe the solution you'd like**
There already is a static `recommendedBrowsers.html` page that can be modified a lot easier. It'd be nice if you can redirect to that page instead.

**Comment by Echolon** [comment]
related

100% support for Firefox (and other non-Chrome browsers)
#4758
