### ISSUE TITLE
Stop Record and Stop Live Doesn't Work at First Click

### ISSUE THREAD

**Issue by gabriele86** [jitsi/jitsi-meet#5847]
Hi to all

I have some problem with live stream and local call recording on a self hosted jitsi installation. 

I can start record or start a live stream ( using custom external servers ) when I click to stopRecording or stopLive buttons modal windows appears as expected but when I click to "continue" for the first time recording or live doesn't stop as expected I had to open the modal a second time.

Seems like missing some meetings session on first time modal loading. 

Some one can help me? 

No error on browser console

**Comment by Echolon** [comment]
rel. 

meet.jit.si recording - no audio recorded #5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
