### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by ghost** [jitsi/jitsi-meet#5849]
Dark mode for iOS would be nice and it would be nice if it can read the systems toggle if it is set to light or dark

**Comment by Echolon** [comment]
@silentshotghost 

Do you mean dark mode or a mode to AMOLED screen? If so should be renamed

**Comment by silentshotghost** [comment]
Both there can be a dark mode option and a dark mode option for OLED screens

**Comment by moshpirit** [comment]
Please, also for Android!
