### ISSUE TITLE
Would you like to rate our app prompt

### ISSUE THREAD

**Issue by silentshotghost** [jitsi/jitsi-meet#5850]
I think if you guys added a “would you like to rate our app” or Are you loving Jitsi give us a rate” or something like that how all other apps give, it could bring in a lot of users

**Comment by Syonyk** [comment]
I disagree strongly.  That the Jitsi Meet app is limited in functionality and quite well behaved is a feature, not something that needs to be "fixed."  The less an app "pesters the user," the happier I generally am with it.

**Comment by saghul** [comment]
We have no plans to do that right now. We may in the future, but no specifics.
