### ISSUE TITLE
List of jitsi servers depending load to collaborate on distribution

### ISSUE THREAD

**Issue by rosa2** [jitsi/jitsi-meet#5851]
Hello and again thanks :)

**Is your feature request related to a problem you are facing?**
I know people that has jitsi on their servers and they don't make it public because they are afraid of overload.

**Describe the solution you'd like**
To have system to be federated and distribute the load.
A better system than your wiki page to add a server and easy also to unsubscribe.

**Describe alternatives you've considered**
There is a page that helps to you to choose a server depending what load they have
https://ladatano.partidopirata.com.ar/jitsimeter/
so you can get the one that it is better at the moment.
Could you put a link to it or some thing similar in the home where you write the channel name before creating it, so people will be less afraid to be public?

Thanks a lot for the tool ;)

**Comment by arthurlogilab** [comment]
Something similar : 

* https://entraide.chatons.org/ randonmly redirects users to jitsi services (and other stuff) code here : https://framagit.org/chatons/entraide
* https://ensemble.scaleway.com/ links to instances according to their load (closed source or not linked)

**Comment by arthurlogilab** [comment]
shame if this is closed, I've talked to so many users and potential users that say "oh jitsi didn't work well when X", and when you dig into it, you find out that they're using a too small instance hosted on a raspberrypi over a DSL link... that hurts jitsi's image... shame.
