### ISSUE TITLE
Vous avez  été déconnecté

### ISSUE THREAD

**Issue by derf81** [jitsi/jitsi-meet#5854]
bonjour,

J'ai installé Jitsi Meet hier sur un Raspberry et raspbian 10
Tout fonctionne sauf une fois sur le salon après 30sec un message apparait qui indique : Vous avez été déconnecté.
Veuillez vérifié votre connexion.
avec un décompte pour une reconnexion automatique après  quelques secondes.

Ma configuration 👍 
Raspberry B+
Carte SD 32Go
Raspbian 10
Connexion : Wifi
Freebox Delta
Le raspberry je l'ai mis dans la DMZ de ma freebox pour y accéder depuis l’extérieur sans problème.
(Pour faire du teletravail avec les collègues)

Est-ce un problème d'ouverture de ports, de configuration ou du faite que le raspberry soit en wifi ou problème de puissance du raspberry ?

Merci pour votre futur aide.

**Comment by peckeltw** [comment]
@derf81 I had the same problem which I solved by checking the CORS settings. Open the developer tools of your browser and check if you see CORS related issues. I had them because the domain name was not properly setup.

**Comment by derf81** [comment]
> 
> 
> @derf81 I had the same problem which I solved by checking the CORS settings. Open the developer tools of your browser and check if you see CORS related issues. I had them because the domain name was not properly setup.

Hello, thanks for the return.
I have an error: Blocking of a multi-origin request (Cross-Origin Request)
How did you solve the problem?
Thank you.

**Comment by Echolon** [comment]
> **You've been disconnected**
> Hello,
I installed Jitsi Meet yesterday on a Raspberry and raspbian 10
Everything works except once on the living room after 30 seconds a message appears that says: You have been disconnected.
Please check your connection.
with a countdown for an automatic reconnection after a few seconds.
My configuration +1
Raspberry B+
32GB SD Card
Raspbian 10
Connection : Wifi
Delta Freebox
The raspberry I put it in the DMZ of my freebox to access it from the outside without any problem.
(For teleworking with colleagues)
Is it a problem with port opening, configuration or the fact that the raspberry is wifi or a problem with the power of the raspberry?
Thank you for your future help.

**Comment by Echolon** [comment]
@derf81 please first review: https://community.jitsi.org

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
