### ISSUE TITLE
Unable to access camera

### ISSUE THREAD

**Issue by goddess-bh** [jitsi/jitsi-meet#5856]
I cant see or hear myself or anyone in jitsi meeting. I didnt have this problem last time using jisti. 
This happened while I was using Opera, I opened a meeting and myb accidentally changed something on my touchscreen (i was cleaning my laptop screen) ... It worked normally on Chrome later.

**Comment by Echolon** [comment]
Non-working camera meta-issue #5425
@damencho can be closed
