### ISSUE TITLE
Control local volume of each stream in a Jitsi Meet call

### ISSUE THREAD

**Issue by theronic** [jitsi/jitsi-meet#5858]
I want to control the relative local volume of each participant.

I'd like to be able to do:

    api.executeCommand('setLocalVolume', "user123", 70); // set that user's local volume to 70%

And also retrieve a user's local volume:

    let volume = api.executeCommand('setLocalVolume', "user123"); // or perhaps with a callback

**Describe alternatives you've considered**

I've looked in the [Jitsi Meet API docs](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) and don't see any volume control events.

**Comment by nulele** [comment]
Yes! And could be useful for hiding/showing the video streaming too.

**Comment by maxmijn** [comment]
This would be very useful!

**Comment by nulele** [comment]
Correct me if I'm wrong but isn't this already possibile with this (https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md) set of API? If yes, is it possibile to use this set of API toghether with the external API (https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md)?

**Comment by albeethekid** [comment]
It is possible from the web, by clicking the vertically oriented tripled dots on a given participants tile (see screenshot) However, the IOS SDK does not seem to expose this, which is quite disappointing. Can anyone offer any advice on how to expose this feature to the SDK for iOS?

<img width="260" alt="Screen Shot 2020-04-23 at 1 05 55 PM" src="https://user-images.githubusercontent.com/23175308/80144455-5c98dd80-8563-11ea-9a89-f71dd220e7db.png">

**Comment by FaizanZahid** [comment]
@nulele  i see this option also on https://meet.jit.si/mymeeting

however, i m using jitsi using the external iframe API, how do i turn on this option so that all participants can lower or raise volumes for other participants?

My code looks something like this,,

```<script src="https://meet.jit.si/external_api.js"></script>


<script>

if ((typeof(JitsiMeetExternalAPI) !== "undefined") && (JitsiMeetExternalAPI === JitsiMeetExternalAPI)){

            var domain = "mydomain.com";
            var options = {
                roomName: "community3",
                configOverwrite: {
                     startWithVideoMuted:true
               },
                interfaceConfigOverwrite: {
                    filmStripOnly: true,
                    VERTICAL_FILMSTRIP: false,
                    MOBILE_APP_PROMO:false,
   TOOLBAR_BUTTONS: [
        'microphone', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection',  'profile', 'chat', 'recording',
        'livestreaming', 'etherpad', 'sharedvideo',  'raisehand',
       'filmstrip', 'invite', 'feedback', 'stats',  'shortcuts',
        'tileview'
    ],
                }
            }
            var api = new JitsiMeetExternalAPI(domain, options);
api.executeCommand('displayName',this.app.user.username);
if (this.app.user.username == "Guest") {
        api.executeCommand('avatarUrl', "https://i.pravatar.cc/300"+"?v="+Math.random());
    } else {
        api.executeCommand('avatarUrl', this.app.user.picture);
    }

} else {
location.reload();
}
```

My iframe looks like this, but i dont see the 3 dots to lower or raise volume of each participant, what am i doing wrong?

![image](https://user-images.githubusercontent.com/9073066/82044741-5790ff00-96c7-11ea-8003-33264fa4ea3c.png)

**Comment by Fuji1405116** [comment]
I checked and that “remote video menu” option (3 dots) is already available by default without any “configOverwrite” and “interfaceConfigOverwrite” in the iframe api.
@FaizanZahid  I even just tried your above code by simply removing “filmStripOnly: true” and “3 dots” option was there… I don’t know why “filmStripOnly: true” make that option vanish but by simply removing it you can achieve that. May be there are be other options too.
If you want fully customized control over every component you have to use lib-jitsi-meet https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md and have to manually do everything.
Thanx

**Comment by laijinmei** [comment]
i could not do the same thing in lib-jitsi-meet API (low level),i want to  control local volume of each stream too

**Comment by saghul** [comment]
You need to do that in the `<audio>` element that is playing the stream.

**Comment by mimiyue282193** [comment]
let participantID = api.getParticipantsInfo()[0].participantId;
console.log(participantID);
api.executeCommand('setParticipantVolume', participantID, 0.5);

I coded like this and it worked fine.
