### ISSUE TITLE
All streamers are busy

### ISSUE THREAD

**Issue by CCEFinland1** [jitsi/jitsi-meet#5859]
Hi, 
On Jitsi Meeting, we can not stream to Youtube. Getting error: All streamers are busy
May I know any workaround for the same?

**Comment by Echolon** [comment]
Non-working camera meta-issue #5425
@damencho can be closed

**Comment by CCEFinland1** [comment]
This is not the Camera issue.  The issue is still not closed.

**Comment by Echolon** [comment]
@CCEFinland1 anyway the issue is know to the developers as I understand.
