### ISSUE TITLE
"Failed to access your microphone" Linux Debian testing

### ISSUE THREAD

**Issue by olberger** [jitsi/jitsi-meet#5863]
I managed to launch the jitsi-meet-x86_64.AppImage with jitsi-meet-x86_64.AppImage --no-sandbox

Video is OK and the rest seems functional, but sound doesn't seem to be working : displays a "Failed to access your microphone" warning message.

Hope this helps,

**Comment by saghul** [comment]
Moved it here to jitsi-meet, since the Electron app just embeds it on an iframe.

**Comment by PolynomialDivision** [comment]
> Actually, the microphone works, once one selects the proper microphone in the list, and activates it.
> 
> Maybe the dialog should indicate that it couldn't auto-detect it, and ask for manual selection.

This does not work for me. I can not select anything. In Chrome/Chromium it works.

**Comment by PolynomialDivision** [comment]
I started from source (npm start) and get this Warning:

```
Logger.js:154 2020-04-20T10:44:53.936Z [modules/RTC/RTCUtils.js] Failed to get access to local media.  NotReadableError: Could not start audio source [object Object] 
```
And this error:
```
Logger.js:154 2020-04-20T10:44:53.937Z [features/base/tracks] Failed to create local tracks
```

**Comment by Baldomo** [comment]
I have this very same error on `5.4.39-1-MANJARO`, on the latest jitsi-meet-electron AppImage (screenshot taken with Electron remote debugging)
[![https://imgur.com/T7ctyct.png](https://imgur.com/T7ctyct.png)](https://imgur.com/T7ctyct.png)

**Comment by PolynomialDivision** [comment]
@Baldomo 
Please look into Pulse-Audio Settings -> Recording.
Start meet app and see if the correct microphone is used. This was my mistake.

**Comment by Baldomo** [comment]
@PolynomialDivision I already tried messing with PA but it shows no recording devices when Jitsi is open, but the microphone works with any other app just fine

**Comment by Mahdi-Forghani** [comment]
i have the same problem but on windows
