### ISSUE TITLE
[UX] Language setting very hidden

### ISSUE THREAD

**Issue by mMuck** [jitsi/jitsi-meet#5865]
Hi!
First of all: Thanks for that great stand-alone app. Perfect to handle the very limited browser support.

I tried the app for win (on win10). I am evaluating Jitsi for the use with people who probably want to change the language setting. From the UX POV this setting should be part of the profile settings at main page or more prominent at the top right of the start screen.
So this implies there needs to be a translation for the main page and settings sidebar.

Greetings

**Comment by d-g** [comment]
> From the UX POV [language] setting should be part of the profile settings at main page or more prominent at the top right of the start screen.

No, itʼs fine: changing language on per-app basis against general user preference is indeed a rarely useful thing.

The major UX issue with Jitsi Meet is that it does _not_ respect userʼs locale (LANG for desktop app [0], Accept-Language for in-browser app [1]) at all, always presenting him an English interface instead.

It might be nice to ask user to choose language prominently if the localization is missing, though.

[0] https://github.com/jitsi/jitsi-meet-electron/issues/281
[1] https://github.com/jitsi/jitsi-meet/issues/3888

**Comment by mMuck** [comment]
@d-g Thanks for clarifying this. Would solve the UX problem, if the user locale is respected.
@saghul OK, sorry. Thought the main page and menu sidebar is part of the wrapper/electron app.
So this could be closed, correct?

**Comment by d-g** [comment]
Markus <notifications@github.com> wrote:
> So this could be closed, correct?

Once [0] is reopened (it was marked WONTFIX by bot for inactivity), imho, yes.

[0] https://github.com/jitsi/jitsi-meet/issues/3888
