### ISSUE TITLE
Impossible to record live to dropbox

### ISSUE THREAD

**Issue by osteopro** [jitsi/jitsi-meet#5868]

**Comment by Echolon** [comment]
duplicate of:

meet.jit.si recording - no audio recorded #5403 

@damencho

**Comment by ridagold** [comment]
I have the same issue. Want to record to Dropbox and there's a message saying "Error recording" and no other explanation.
Thank you

**Comment by Echolon** [comment]
@ridagold okay, I think the issue is known to the developers. One issue is basically enough. Please comment to #5403

**Comment by paoloartasensi** [comment]
Thanks @Echolon for the heads-up! I'll follow #5403 for updates on this.
