### ISSUE TITLE
Where have all the translations gone?

### ISSUE THREAD

**Issue by Mejans** [jitsi/jitsi-meet#5869]
Hello,
like many other people I made some improvements thanks to Weblate.
Now the project Jitsi is no longer there, what happens to our contribution?
I mean, it's time spend to contribute, I cannot imagine it's been erased and lost.
When will our work be merged?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by Mejans** [comment]
@damencho Hello, thanks for the link but it doesn't answer =/

**Comment by damencho** [comment]
Nothing is erased or lost. We are trying to integrate Crowdin and see how it goes. We will try migrate everything from weblate without the Norwegian.
We advised people to do PRs for translations for the time being till we finish the process of setting up a new translation service and we were not expecting something to end up in weblate, but we will try to move everything that got there ... will see how it goes.

**Comment by ostasevych** [comment]
> Nothing is erased or lost. We are trying to integrate Crowdin and see how it goes. We will try migrate everything from weblate without the Norwegian.
> We advised people to do PRs for translations for the time being till we finish the process of setting up a new translation service and we were not expecting something to end up in weblate, but we will try to move everything that got there ... will see how it goes.

Actually, I may not change language files obtaining response that the fork will be created...
