### ISSUE TITLE
jitsi-meet unmet package dependencies Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by wehmoen** [jitsi/jitsi-meet#5872]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

apt on fresh ubuntu 18.04 cant install jitsi

---

## Current behavior

When trying to install jitsi following the steps at https://jitsi.org/downloads/ using the repositories apt fails with this message:

```
root@ip-172-31-35-171:/home/ubuntu# sudo apt-get -y install jitsi-meet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : PreDepends: jitsi-videobridge2 (= 2.1-169-ga28eb88e-1) but it is not going to be installed
              Recommends: jitsi-meet-turnserver (= 1.0.3992-1) but it is not going to be installed or
                          apache2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

---

## Expected Behavior

The same instructions worked a few days ago when I setup a test server. Same OS. 

---

## Possible Solution

Provide the required version of jitsi-videobridge2 over the package repository

---

## Steps to reproduce

1 ) Setup a EC2 t2.small instance with Ubuntu 18.04 (Marketplace Version) 
2) `wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -`
3) `sudo sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"`
4) `sudo apt-get -y update`
5) `sudo apt-get -y install jitsi-meet`

---

# Environment details

OS: Ubuntu 18.04.3 LTS
universe distribution component was activated
---

**Comment by brimur** [comment]
Just tried to do an install on the same version of Ubuntu server and got the same result. I can also confirm it did work a few days ago when I installed on another server.

**Comment by iakashpaul** [comment]
Just ran into the same issue AWS Ubuntu 18.04.3, seems to be an issue with latest stable release.

**Comment by damencho** [comment]
I just pushed new stable and something went wrong. Looking at it fixing it ASAP. Will let you know

**Comment by brimur** [comment]
I had to add sudo sh -c "echo 'deb https://download.jitsi.org unstable/' > /etc/apt/sources.list.d/jitsi-unstable.list" to get it to install

**Comment by thomas31415** [comment]
Same here on a fresh install on debian 10:

apt-get install jitsi-meet

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 jitsi-meet : Hängt ab von (vorher): jitsi-videobridge2 (= 2.1-169-ga28eb88e-1) soll aber nicht installiert werden

**Comment by damencho** [comment]
Yes, there is a problem with the release, not sure where it got wrong. Trying first to fix it and then will try to figure out.

**Comment by wehmoen** [comment]
wow. glad to hear its not just me making a stupid mistake. thanks for looking into this guys!

**Comment by SeeUnsharp** [comment]
Oh boy, I thought I am crazy :D

**Comment by damencho** [comment]
Sorry all, seems the jvb somehow is not getting picked. Still struggling, stay tight.

**Comment by damencho** [comment]
It is something with the download server ... Mirror of the repo works.

**Comment by damencho** [comment]
Can someone do 
```
apt-get update 
apt-get install jitsi-meet
```
Does it work now?

**Comment by damencho** [comment]
It must be some cache or anything ... not obvious at the moment ...

**Comment by thomas31415** [comment]
yes seems to work - thanks a lot!

**Comment by damencho** [comment]
Pfew, sorry for the trouble. I'm double-checking on a fresh VM now.

**Comment by iakashpaul** [comment]
Yep worked now! Thanks a ton!

**Comment by damencho** [comment]
Thank you all for the report and patience!

**Comment by SeeUnsharp** [comment]
That was fast, thanks!

**Comment by damencho** [comment]
This release should fix all the Debian 10, problems people were facing with wrong jvb password and turnserver credentials are the most problematic ones.
But as we are moving fast these days, new releases will be following. Including new stuff.

**Comment by kushagraagent47** [comment]
Same problem is coming again

**Comment by TheNomad11** [comment]
same issue happened again with the most recent release on Ubuntu 18.04 LTS

```
The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.5307-1) but 1.0.5211-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by damencho** [comment]
Check out this: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#for-ubuntu-1804-add-prosody-package-repository
