### ISSUE TITLE
jitsi embed API example doesnt work 

### ISSUE THREAD

**Issue by kchecker** [jitsi/jitsi-meet#5878]
The example given on this page when setup gives a https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html opens up a window with no video or audio. 

Am I missing something?

![image](https://user-images.githubusercontent.com/2305977/79016082-bd034480-7b8b-11ea-87f5-89843e4dbe1e.png)

**Comment by NiallTracey** [comment]
If you're on a page that is not using https, your browser won't grant access to the webcam or microphone.

**Comment by vibhor-j** [comment]
It is working fine.
Try this -> https://codepen.io/prasanthlalapeta-the-styleful/pen/NOOBEX
