### ISSUE TITLE
Record a Class in Jitsi Meet

### ISSUE THREAD

**Issue by Maria01-n** [jitsi/jitsi-meet#5879]
Hello! My name is Mary, and I've having some issues with Jitsi Meet. I wanted to record a Class, but a message appears: "All recorders are currently busy. We're working on freeing recording resources. Please try again in a few minutes".

Is it normal? Or is there anything I can do to solve this problem?
I have been trying more than 6 times, and it doesn't work..

Please, can you give me a hand? Thanks

**Comment by Maria01-n** [comment]
I checked the answer for this issue. Thanks

**Comment by Echolon** [comment]
Hello, @Maria01-n this is not a support forum, please review: https://community.jitsi.org

@damencho can be closed
