### ISSUE TITLE
android app doesn't support HTTP basic auth

### ISSUE THREAD

**Issue by taleden** [jitsi/jitsi-meet#5881]
**Is your feature request related to a problem you are facing?**
I am hosting my own jitsi-meet server on my home network, and would like to make it available to friends and family over the internet while minimizing the security risks to my network. I have therefore enabled HTTP basic auth in my docker-jitsi-meet's nginx configuration, which works great for web-based clients, but does not work for mobile app clients. The mobile app does not appear to support prompting the user for credentials, nor does it accept credentials encoded into the meeting server URL (i.e. "https://user:pass@my.jitsi.server").

**Describe the solution you'd like**
The jitsi-meet mobile apps should detect meeting servers that employ HTTP basic auth and prompt the user for credentials to connect. It could also check for and use credentials provided by the user encoded into the meeting server URL.

**Describe alternatives you've considered**
I am aware that jitsi-meet has some internal authentication capabilities, and I had originally configured it using the internal/plain auth. That worked insofar as clients being prompted for credentials when joining rooms, but there seems to be a bug currently that blocks audio and video when using internal auth, so room participants could chat with eachother in text but could not see or hear eachother.

Regardless, even if and when the internal auth bug is fixed, I think it would still be valuable to support HTTP auth as a defense-in-depth option. In some use cases, even revealing the presence of a jitsi video bridge server at a given host and port could be seen as an undesirable security risk; with HTTP basic auth, unauthorized visitors could only learn that a web server of some sort was present, but not the nature of that server.

**Comment by saghul** [comment]
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5419

**Comment by taleden** [comment]
Apologies, I did search for 'http auth' but did not find that issue.
