### ISSUE TITLE
Recorders is busy

### ISSUE THREAD

**Issue by marciocbrinck** [jitsi/jitsi-meet#5883]
I was able to record a meeting previously but I am not getting it now.

**Comment by edmundlaugasson** [comment]
Same here...

**Comment by Echolon** [comment]
@damencho 

I think can be closed due to: **Non-working camera meta-issue** #5425

**Comment by bcoufal** [comment]
me too...

**Comment by luixxiul** [comment]
@bcoufal follow #5403 / #5425 for the latest info.
