### ISSUE TITLE
text parsing issue in chat feature in android app: emoji appears in url

### ISSUE THREAD

**Issue by ForestJohnson** [jitsi/jitsi-meet#5885]
## Description

I installed Jitsi Meet on my LineageOS (Open source Android) device via F-Droid.

They sent a URL via text chat feature of Jitsi, they sent it via the web interface from chromium. Other users who were on the web interface saw the link show up correctly.

## Current behavior

![image](https://user-images.githubusercontent.com/7119703/79030738-32592000-7b60-11ea-889f-74d080101cc9.png)

I blanked out domains from the URL in the screen shot but you can see how the client parsed one of the domains in the URL parameters as a link, but it didn't parse the whole thing as a link. 

The URL was something like `https://prometheus.foo.info/graph?g0.range-input=2w&g0.expr=rate(node_network_receive_bytes_total%7Binstance%3D%22waabba.babba.info%3A9100%22%2Cdevice%3D%22vnet4%22%7D%5B5m%5D)&g0.tab=0`

## Expected Behavior

It should show a click-able URL, not an emoji.

## Possible Solution

parse URL correctly 

## Steps to reproduce

Send the example  URL  `https://prometheus.foo.info/graph?g0.range-input=2w&g0.expr=rate(node_network_receive_bytes_total%7Binstance%3D%22waabba.babba.info%3A9100%22%2Cdevice%3D%22vnet4%22%7D%5B5m%5D)&g0.tab=0` from Jitsi web interface to an android jitsi meet user in the chat, hopefully it will be re-producible. 

it should show `22waabba.babba.info` as a clickable link and show `https://prometheus.foo.info` as  https😕/prometheus.foo.info

# Environment details

I was using a Jitsi server hosted by a friend. They sent me these version numbers for the jitsi server version:
```
apt list --installed | grep jitsi

jitsi-meet-prosody/stable,now 1.0.3969-1 all [installed,upgradable to: 1.0.3992-1]
jitsi-meet-turnserver/stable,now 1.0.3969-1 all [installed,upgradable to: 1.0.3992-1]
jitsi-meet-web-config/stable,now 1.0.3969-1 all [installed,upgradable to: 1.0.3992-1]
jitsi-meet-web/stable,now 1.0.3969-1 all [installed,upgradable to: 1.0.3992-1]
jitsi-meet/stable,now 2.0.4384-1 all [installed,upgradable to: 2.0.4416-1]
jitsi-videobridge2/stable,now 2.1-164-gfdce823f-1 all [installed,upgradable to: 2.1-169-ga28eb88e-1]
```

the android app was `org.jitsi.meet` `19.4.0`

**Comment by Echolon** [comment]
related

**Emoji reactions** #5217

**Comment by ForestJohnson** [comment]
How is that related?  One is a feature request for slack-style emoji reactions.  The other is a bug related to URL parsing
