### ISSUE TITLE
Where is Live Stream ?

### ISSUE THREAD

**Issue by liberodark** [jitsi/jitsi-meet#5888]
Hi,

Where is live stream i dont see the fonctionality on my Jitsi Meet.

![image](https://user-images.githubusercontent.com/4238928/79037404-e0041780-7bd0-11ea-8e01-b725c0aef431.png)

Best Regards

**Comment by liberodark** [comment]
Have  see this is correct : https://github.com/jitsi/jibri ?

**Comment by Echolon** [comment]
duplicate of

Live streaming #5146

@damencho

**Comment by badesemowo** [comment]
@liberodark - 
If you are using meet.jit.si -  I think the Livestream feature is not supported by every browser . 

If you are using a self-hosted version - in addition to checking the above, note that you also have to configure https://github.com/jitsi/jibri in your environment as @liberodark  mentioned.

**Comment by liberodark** [comment]
Yeah ok.
