### ISSUE TITLE
mobile Safari on iPadOS doesn't request for video permission

### ISSUE THREAD

**Issue by marcelloceschia** [jitsi/jitsi-meet#5891]
on the older version i was able to have video conference with iPads by patching the usesPlanB and an other function. Is there an easier way to allow video on iPadOS?

**Comment by normen** [comment]
Afaict full Safari support has been committed already and should be pushed to the release channels soon. Then theres always the app.

**Comment by tisayama** [comment]
When I access the conference room page in Safari on my iPad, I get the same regular video call screen as on my PC.

If this web app is not working in Safari on iPad, I think it should display the same Deep-link page as if I open link on my iPhone.

It happen on my iPad Pro 11inch with iOS 13.4.

**Comment by normen** [comment]
Thing is Apple lately made the iPad think it's a desktop by default. The current iPadOS is _supposed_ to ditch "mobile versions" of a web page. For me the web app is "working" on iPad in that I can take part in a conference, video just doesn't work (yet).

**Comment by saghul** [comment]
I sshould be working now, after the latest fixed we deployed for Safari mobile.
