### ISSUE TITLE
All streamers are currently busy

### ISSUE THREAD

**Issue by config-v2** [jitsi/jitsi-meet#5894]
All streamers are currently busy
[https://take.ms/JnMtj](url) (screen)
This message has been popping up for more than a day!
Is it really impossible to fix anything?

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5809

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
