### ISSUE TITLE
Jitsi hijacks requests intended for other domains on same server

### ISSUE THREAD

**Issue by matbender** [jitsi/jitsi-meet#5897]
The Jitsi nginx config takes over requests intended for other domains on same server.

Example:
a request for the (not Jitsi related) url  https://foo.mydomain.com/yam12345 is redirected to Jitsi 

nginx error log says:
`2020/04/11 16:54:59 [warn] 17911#17911: *2 using uninitialized "subdomain" variable while sending response to client, client: ***IPv6adress***, server: ***jitsy_server_domain***, request: "GET /yam12345 HTTP/1.1", subrequest: "/config.js", host: "***hijacked_domain***"`

***IPv6adress*** = Client IP
***jitsy_server_domain*** = jitsi.mydomain.com 
***hijacked_domain***     = foo.mydomain.com

**Comment by saghul** [comment]
What is your server_name configured to?

**Comment by Echolon** [comment]
@matbender may you have an answer to the question? That would help a lot!

**Comment by matbender** [comment]
It's set to the jitsi domain. Currently it works, I did not know to what ist was set initially. I can provide the jitsi ngnx.conf if needed/helpful.
