### ISSUE TITLE
How to close jitsi on android 

### ISSUE THREAD

**Issue by torugor** [jitsi/jitsi-meet#5898]
I created an android all that manages rooms for jitsi with a set of rules.

Thing is my usar may enter a jitsi activity then leave the jitsiactivity with back button and choose another room returning to jitsiactivity.

Sometimes when the user leaves jitsiactivity and resumes it...jitsi wont return connecting. Furthermore when this bug happens i noticed that by closing the app and trying to make a  video call with whatsapp, their app complains i am already on a videocall.

So i would like to know what methods force the video call to end so that i can use it on the onclose activity and solve this issue.

**Comment by saghul** [comment]
You should use a different activity for each meeting. It's the simplest, and it avoid a number of problems.

As for the calling, I recommend you disable the native call integration, as it doesn't work quite well with ssome vendors, alas: `.setFeatureFlag("call-integration.enabled", false)`
