### ISSUE TITLE
droid cam 

### ISSUE THREAD

**Issue by gleizzo93** [jitsi/jitsi-meet#5899]
hallo ich habe heute morgen noch über droidcam spielen können 
nun ist es immer so das wenn ich mit droidcam verbinden möchte das gesagt wird uneable to connect to camera

**Comment by Echolon** [comment]
@damencho 

I think can be closed due to: **Non-working camera meta-issue** #5425

**Comment by l3d00m** [comment]
Hi @gleizzo93,

das scheint mir eher ein Problem mit Droidcam zu sein. Sollte Droidcam in anderen Anwendungen funktionieren, lies dir bitte #5425 durch. Dort ist beschrieben, wie du dein Fehler besser reporten kannst.
