### ISSUE TITLE
Specifications for instalation / removing

### ISSUE THREAD

**Issue by rlinares89** [jitsi/jitsi-meet#590]
Hi there...

How many specifications from my hardware i need to run in this server (jitsi meet videobridge), i have a debian 8 with 2.5Gb RAM, 8Gb HDD, Intel I3 first family,, is that suficient???... otherwise, i apply "apt-get remove jitsi-meet", delete all directorys and install again, but it doesn't runs again the localhost configuration, do you have any idea for that issue?...

I apply the quick install intructions from:

https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

Any help will be gracefully recieved.

Thanks you all!

**Comment by damencho** [comment]
When we last checked the localhost approach is not working well, there were a lot of modifications in the configs in order to make it work. Using a resolvable dns name is working fine.
Please use the mailinglist before opening issues.

**Comment by rlinares89** [comment]
Thank you DAMENCO, so now... doy you have any sugest for the system specifications, i mean hardware sugestions?... ram, cpu, network bandwith on my ethernet interface?
