### ISSUE TITLE
Room password could be send as a URL parameter

### ISSUE THREAD

**Issue by sidan5** [jitsi/jitsi-meet#5902]
**Is your feature request related to a problem you are facing?**
I'm trying to secure rooms using a "random"/complex password. on the other hand it must be simple enough for anyone to join the meeting (without the need to type the complex password). This kind of solution is implemented on Zoom as far as I know.
This on one hand might not be too complex to implement but would increase security dramatically. Moreover, user experience would not negatively be affected as users doesn't need to know anything for it to work. 
_Real life example_: I want to connect between 2 (or more) users for a video call using a mobile app but without both (or all) need to set the room password manually (should have same UX as a FaceTime call).

**Describe the solution you'd like**
Add a new parameter to the URL that could contain the room password. When joining a room this parameter would automatically set room password from the URL instead of user need to insert that manually.
Also, when sharing from room UI it would be nice if this parameter and password that has been set would be added to the shared URL (the link would include password).

Example:
    https://meet.jit.si/ROOMNAME#config.roomPassword="ROOM_PASSWORD"

_Expected Result_: Anyone who have access to the full URL could join the room. Clicking the URL would enter the room even if it is password protected.

**Describe alternatives you've considered**
_JWT_: Using JWT doesn't help as we would need to manage list of users that allow to enter a specific room (this could not be done at scale as this shall be dynamic).
_Using complex room name_: This is kind of nice but does not prevent anyone from entering a room if somehow this name is being exposed.

**Comment by ostasevych** [comment]
You may try to think to encrypt the password.

**Comment by sidan5** [comment]
@ostasevych how encryption would help?
If I want the password hidden from all users but the ones need to join the room I would need to share a key with all of the relevant somehow. This doesn’t add any security as I would need to send it somehow for all of them. So encryption by itself for the password doesn’t add anything to a “strong” password.
I see the password as the credentials to join a conversation (something only those who are creditable to join would know). For me everyone who knows it or get access to it could definitely join the room. 
If I misunderstood your suggestion please let me know.

**Comment by ostasevych** [comment]
> @ostasevych how encryption would help?
> If I want the password hidden from all users but the ones need to join the room I would need to share a key with all of the relevant somehow. This doesn’t add any security as I would need to send it somehow for all of them. So encryption by itself for the password doesn’t add anything to a “strong” password.
> I see the password as the credentials to join a conversation (something only those who are creditable to join would know). For me everyone who knows it or get access to it could definitely join the room.
> If I misunderstood your suggestion please let me know.

Well, I mean, the plain password may be intercepted, while encrypted or hashed not.

**Comment by sidan5** [comment]
> Well, I mean, the plain password may be intercepted, while encrypted or hashed not.

Let's think about those options for a second:
1. If the password is encrypted then the room participants would need to have a key distributed to them to encrypt it. Then we just make the issue more complex as I'm not sure we want this kind of feature. Also all those participants would eventually have access to the plain password and they could forward that to anyone. So I'm not sure it gives any value then just to have the password as plaintext.
2. If the password is hashed then how we would get the plain password we need to access the room? If we would use a hash function to create the password it would just "help" to make it complex enough from a simple phrase, still this need to be created with some kind of random as we won't want a guessable password (even if we used hash and it looks complex after hash function). This is definitely different from hashing a password for saving in the DB (there the hash help not to disclose the original text used to create it).

To my conclusion, as I see it, in the scenario we are talking about I do not see any value whatsoever to encrypt the password being sent in the URL or hash it. Let me know if I miss anything as I might... :)

**Comment by PacoBell** [comment]
"This is definitely different from hashing a password for saving in the DB (there the hash help not to disclose the original text used to create it)."

To me, this is exactly what is desired. The meeting organizer wants to choose a password familiar to them, but doesn't necessarily want to disclose the semantic meaning to the participants. This provides easy access to the room for anyone with the URL, yet some measure of security against anyone opportunistically scanning for public rooms with no password security (i.e. Zoombombing).

**Comment by sidan5** [comment]
> To me, this is exactly what is desired. The meeting organizer wants to choose a password familiar to them, but doesn't necessarily want to disclose the semantic meaning to the participants. This provides easy access to the room for anyone with the URL, yet some measure of security against anyone opportunistically scanning for public rooms with no password security (i.e. Zoombombing).

@PacoBell I get this. However, my feature request was to have the password option available to be fetched from the URL. The exact way of creating it is a different topic to my understanding.

Anyway, If we do discuss that (hashed password), Need to understand that using a same password with hash would result with same hashed-password. That means that to prevent that we would need to create also a random salt for this hash so the host would create the hashed-password using the password he likes, some random salt would be generated then the hashed password would be created and be available for sharing. This would keep the (hashed) password being shared a "random" string in any case (it does not affect this feature request in any way but on the way password is being created). 

If I would suggest a way to create the shared password I would definitely add an option of a random one created in the client by host request (or the host could just set any if he would like in any way he finds appropriate as it is today).

**Comment by Syonyk** [comment]
I'm struggling to see how adding a room password to the URL is functionally different from just using a very long and random room name in the first place.  If the goal is to have people able to join "with a link," and not have other people discover the room, then a long and unique name accomplishes both goals.

If Jitsi _is_ leaking room names, then that's a separate issue that should be addressed.  The problem with Zoom is that they're using nothing more than a 9 or 10 digit room ID, which can be easily brute forced.  Jitsi allows long names, so the search space is massive.  Don't use names like "Meeting" or "Test" or such, and the chances of someone finding it drop quite low.

If you want to generate good random room names, you can always use a hash function (sha256 or so) to generate a meeting name.

On Linux, at least, one might consider extracting some entropy from /dev/random and hashing it to make a room name.

```
$ head -c 64 /dev/random | sha256sum
3a97553e0dc4aac41f9457f431aa7910fdf9373baa2a628a450e29077710c820  -
```

That's just as good as any password, and if the URL is being shared for access, there's no difference.

**Comment by sidan5** [comment]
@Syonyk that’s a good point. I’m new to Jitsi and not sure how room name is being stored, compared and used (could check if you can refer me to the relevant point). However, as I see it, room name (on contrary to password) is a parameter I guess does not need to be handle carefully (as most passwords are). I would be very surprised if room name is handled same as required from password and in that case you are right.
On other hand, if room name is “exposed” to the world and not handled carefully as password should, I don’t think it’s a security issue by itself (same as sharing your email address with everyone is not a security breach).

**Comment by MagicFab** [comment]
Keep in mind anything used in the URL will be visible and kept in users browsing histories and server logs.

**Comment by joydeb28** [comment]
Any config params required to work this 
**https://meet.jit.si/ROOMNAME#config.roomPassword="ROOM_PASSWORD"**

**Comment by Iwandel** [comment]
the need to create a pw for a room that way still persists, I have been looking around to find a solution but did not find one.

**Comment by magazinebrute** [comment]
> Is there any news if such feature will ever be implemented?
> 
> We have similar need for setting room password on creation.
> Currently our rooms are only created by jwt authenticated users, also, we don't request authentication for guest.
> Moderators can set room password after they join their room, but that also means that room is created and everyone "waiting for host to join" are already joined when moderator is setting room password.
> 
> Regarding this topic I have already opened ticket at: https://community.jitsi.org/t/jitsi-jwt-which-also-sets-room-password/66660
> 
> For us It would be good enough solution if room password could be set with URL parameter when moderator is entering room.
> I don't mind if guest are forced to "manually" enter room password and can't pass room password with URL - if this is security concern.

Maybe if a moderator/host enters an already populated room, and creates a password, an event could trigger that silences/mutes and kills all participant videos in progress, clears chats and disables chat entry and private messages until the password is entered, then the expected features are re-enabled, excluding all the uninvited guests.

**Comment by apiraino** [comment]
Upvoting this feature request, having the password in the URL would remove some friction for people using other conferencing softwares (at least in my experience, Jitsi is a bit of a tough sell in these cases).

**Comment by luminous706** [comment]
Quick question, what would be the difference between the room password added to the room URL vs a very complicated room name? Asking because atm, I don't really see a need for passwords in rooms as we can have MD5-based room names.

**Comment by Iwandel** [comment]
unwanted participants can re-enter a complicated room name but can not come back when you change the pw. Its just one of many reasons why we still need this feature.

**Comment by sidan5** [comment]
> Quick question, what would be the difference between the room password added to the room URL vs a very complicated room name? Asking because atm, I don't really see a need for passwords in rooms as we can have MD5-based room names.

Room names are not passwords and probably don’t managed in same way. For example it might be easy to scan for rooms available (depend how it is stored) whereas with passwords it won’t be possible. On top of that as others mentioned password could be changed keeping same room name.

**Comment by saghul** [comment]
Folks, we are close to 3 years into this issue and nobody has wanted it badly enough to send us a patch. Maybe it's not meant to be.

**Comment by AlexandreBonneau** [comment]
Adding to the conversation, when trying to push for Jitsi to my clients, any bit of friction might be seen as huge.
Ideally for some of the users a single click to a link should be the only action on their part.

In order to do so, we need a way to add *all* the information that are currently asked to the user:
- The room name
- The password
- Their nickname

It would be great if you could create links like:
`https://meet.jit.si/roomName/password/username` for users that are not tech-savvy
`https://meet.jit.si/roomName/password` for users knowing how to enter their username and click 'join'

Or if url rewriting is too complex, something along those lines:
`https://meet.jit.si/roomName?p=password&u=username` for users that are not tech-savvy
`https://meet.jit.si/roomName?p=password` for users knowing how to enter their username and click 'join'

**Comment by damencho** [comment]
What is the difference between having a long unpredictable roomname and having a password set to the room?
If using meet.jit.si someone needs to enter on advance and set the password.

**Comment by saghul** [comment]
An equivalent (if not better) level of protection can be accomplished with the lobby.

There are ways to enable it automatically.

Please remember meet.jit.si is just a special deployment with no auth where everyone is a moderator. If you need different options you can self-host Jitsi or use JaaS.

**Comment by augusto-herrmann** [comment]
When your're live streaming the meeting (e.g. using OBS Studio) the room name, and probably the URL too, can be easily seen by anyone watching the stream. Enabling the lobby with moderator approval is not enough to prevent "zoom bombing", as someone can just use a user name the moderator expects to come (e.g. by looking at the public event schedule containing the speaker names). The only way to prevent this is by setting a password.

To make it more convenient for participants, we could send them a link with prejoinConfig including the password, so they do not have to enter it manually.

As has been said before, requiring the meeting participants to manually enter the password, even if it is just cut/paste from the email you've sent them, is friction enough for them to complain and want to go back to the Big Tech video conferencing solutions they're used to. +1 to "it makes the tough sell of using Jitsi Meet even tougher". Don't underestimate how much people in general are addicted to Big Tech these days.

**Comment by AlexandreBonneau** [comment]
Lastly, to complete my [previous message](https://github.com/jitsi/jitsi-meet/issues/5902#issuecomment-1572985618), I think you need to have the room name separated from the password, for the simple reason that you can create multiple rooms for multiple teams (with always the same password), and then rely on your browser cache to find the correct url, looking for your team name instead of having to remember a long hexadecimal hash.

That way when typing your room name in your browser, the urls are more recognizable.
