### ISSUE TITLE
invoke start/stop live streaming and start/stop recording from external_api methods

### ISSUE THREAD

**Issue by techcouncilbox** [jitsi/jitsi-meet#5904]
**Is your feature request related to a problem you are facing?**

It is only a suggestion but I wish I could invoke start/stop live streaming and start/stop recording from external_api methods.

**Describe the solution you'd like**

Additional command options like 'livestreaming' and 'recording'. 

**Describe alternatives you've considered**
N/A

**Comment by nulele** [comment]
Yeah me too!

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/jitsi/jitsi-meet/issues/1807.
