### ISSUE TITLE
Jitsi meet client for KaiOS?

### ISSUE THREAD

**Issue by farooqkz** [jitsi/jitsi-meet#5906]
Are you going to implement a client for KaiOS?
Or would you instruct how to code a client for KaiOS?
e.g. Protocol, Libraries, etc.

**Comment by normen** [comment]
Jitsi is based on Javascript and WebRTC. Actually if KaiOS has a modern browser it might even work in the browser as is, right from the web page. Try requesting a "desktop version" of the site if possible in the KaiOS browser.

**Comment by farooqkz** [comment]
@normen I tried. It does not work, now.

**Comment by saghul** [comment]
What is KaiOS? From a quick glance it looks like a continuation of FirefoxOS?

**Comment by farooqkz** [comment]
> What is KaiOS? From a quick glance it looks like a continuation of FirefoxOS?

Yeah for non touch devices.

**Comment by saghul** [comment]
I see. Our app is built with React Native, so if that works, I guess you could make it to work. Alternatively if there is a WebView available, that could be another avenue to get it working.

Now, we don't have resources to take on more platforms ourselves, so don't expect a first-party client. That said, if you or anyone wants do this we'll be happy to try and help out o the best of our ability.

I hope you understand.
