### ISSUE TITLE
Disable sharing of Youtube links as meeting moderator.

### ISSUE THREAD

**Issue by zaggynl** [jitsi/jitsi-meet#5910]
As per title, anyone can interrupt by sharing a Youtube video.

**Comment by kkaefer** [comment]
You can remove this feature from the UI by removing `'sharedvideo`' from `TOOLBAR_BUTTONS` array in `/usr/share/jitsi-meet/interface_config.js`. This probably won't disable the actual functionality, but it'll vanish from the web UI.

**Comment by zaggynl** [comment]
Thanks, this will do as a server wide workaround, any way to do this per meeting?
