### ISSUE TITLE
(video cropping/quality problem) Unable to Use Virtual Camera with OBS

### ISSUE THREAD

**Issue by EliterScripts** [jitsi/jitsi-meet#5918]
I am currently using a fake camera solution, as a workaround to using OBS as the video input for a Jitsi meeting.

I am currently running Ubuntu Desktop 18.04, and I am finding that I am unable to use an OBS (Open Broadcast Software) virtual video device, since Jitsi seriously cuts the video quality, and crops the video, I am finding that I am unable to do this.

I am using OBS with the v4l2sink plugin https://github.com/CatxFish/obs-v4l2sink/ which basically creates a fake camera, with the OBS output. The resolution I have it at is 1848x1009 --I might be wrong, since it is hard to figure out how to use OBS properly.

The problem is, when I open /dev/video0 with VLC, it shows the full screen. Granted, it's not the video quality I want, but it is the full screen. You can see that with the images I have attached. When I open the video with Jitsi on another browser (outside the virtual machine--I am using virtualbox for the OBS/camera hack), it has even worse video quality, and it cuts the video--you can't see the power button on the top right of the Unity desktop on the computer that is using OBS.

Now, I was reading that could be fixed by a configuration here https://github.com/jitsi/jitsi-meet/issues/969 , but I feel like that won't completely fix the problem. I am also going through, and eventually figuring out how to get Jitsi Docker to work, because it is broken at this moment.

Now, I do like how Jitsi handles screensharing, and for the browsers that automatically enable "low bandwidth mode", it will still stream. Is there a way for me to get OBS to output to a screenshare? It appears that the screen share shows the full screen, and has high quality video on the other side.

Any suggestions on the best way to take OBS output, and stream it to a Jitsi meeting? I'm also still trying to figure out how to take OBS audio and put it in Jitsi.

![image](https://user-images.githubusercontent.com/17048113/79064321-c3adbc80-7c5c-11ea-8771-724ccb4ee01d.png)
![image](https://user-images.githubusercontent.com/17048113/79064332-e3dd7b80-7c5c-11ea-8140-f41b310d616e.png)
![image](https://user-images.githubusercontent.com/17048113/79064351-040d3a80-7c5d-11ea-8657-ab799897cfa1.png)
![image](https://user-images.githubusercontent.com/17048113/79064367-1f784580-7c5d-11ea-93c2-2524b49f1b95.png)
![image](https://user-images.githubusercontent.com/17048113/79064458-176cd580-7c5e-11ea-8377-da78ff2d3799.png)
![image](https://user-images.githubusercontent.com/17048113/79064523-5d299e00-7c5e-11ea-9394-88e06a95965a.png)
![image](https://user-images.githubusercontent.com/17048113/79064547-9a8e2b80-7c5e-11ea-9b39-aa54cba1d534.png)
![image](https://user-images.githubusercontent.com/17048113/79064569-d88b4f80-7c5e-11ea-8ebb-ceddde681eba.png)

**Comment by Echolon** [comment]
ref. #6010
