### ISSUE TITLE
Etherpad icon not showing

### ISSUE THREAD

**Issue by jamesarems** [jitsi/jitsi-meet#592]
Hi,

Recently i have installed jitsi meet and its very usefull. But i cant able to use etherpad in jitsi meet. I have installed etherpad lite on my ubuntu 14.04 and its working fine. Also pointed on nginx as per the jitsi meet documentation. But i cant able to see "share document" icon in the management tab. I can see "SIP" "Youtube share"..etc. I have double checked interface_config.js and "etherpad" is there. 

Please help me guys.

**Comment by damencho** [comment]
Please write to the mailinglist before creating new issues!

Do you have the setting etherpad_base:... in config.js?

**Comment by jamesarems** [comment]
Closed? !! Seriously. Give me atleast couple of hours to explain my problems. 

Its configured exactly the same which you guys are done in the documentation. 

I have added etherpad_base: <nginx url> in jitsi imeet under /etc , but no hope. Etherpad is working fine with localhost. But i cant able to see "share document" icon. 

Im using latest jitsi update.

**Comment by damencho** [comment]
Hi, again. I'm trying to answer your question, but as I asked we prefer discussions on the mailinglist, and open an issue after we have identified that there is one.
You can open https://github.com/jitsi/jitsi-meet and check that part:
"Discuss
Please use the Jitsi dev mailing list to discuss feature requests before opening an issue on Github."
Thanks

**Comment by jamesarems** [comment]
Okey, got your point. Thanks.
