### ISSUE TITLE
OTG camera support on Android

### ISSUE THREAD

**Issue by nosferatu12** [jitsi/jitsi-meet#5921]
**Is your feature request related to a problem you are facing?**
The display in the conference is limited to the features of the build in camera of the smartphone. The view angle is small. And in times of corona we are with two or three people in front. An attached external cam would provide better options. E.g. a streaming of jitsi by chromecast to my TV, which has no build in cam.

**Describe the solution you'd like**
I attached a simple webcam , logitech c270. Lineage 16 recognizes it with OTG view app. 
But jitsi app can switch only between front and back cam.
Please add support for OTG connected cams or enable addition of OTG view screen in jitsi app.

**Describe alternatives you've considered**
Running jitsi in firefox browser by checkmarking desktop screen

I would appreciate a benevolent testing of my request
regards Achim

**Comment by esteban1983** [comment]
Hi Achim,
did you find a solution regarding your topic? I have the same issue and i would be very interested if you find the solution.
Thanks!!

**Comment by nosferatu12** [comment]
Hi,

No, we didn't find a solution.
We no make our meetings with pc and attached cams.

11.01.2021 10:29:14 esteban1983 <notifications@github.com>:
