### ISSUE TITLE
Phone-in Fails When Password Set

### ISSUE THREAD

**Issue by drewpc** [jitsi/jitsi-meet#5925]
## Description ##
Dialing in to a meeting by phone fails when a password is set. 
Mentioned [here](https://community.jitsi.org/t/error-connecting-to-conference-by-phone/29748) and [here](https://community.jitsi.org/t/i-need-help-to-be-able-to-place-a-phone-call-to-a-meeting-room/24339/10)

---

## Current behavior
 A user can dial the number, enter the PIN, and then the user is disconnected.

---

## Expected Behavior
A user dials the number, enters the PIN, and is connected without needing to enter a password because the PIN serves the purpose of the password.

---

## Possible Solution
Remove password checking for dial in users when the PIN is entered.

---

## Steps to reproduce
Establish a Jitsi Meet room and set a password.  Dial the US phone number listed and enter the PIN.  After the call disconnects, clear the password and perform the same steps.  The call will succeed.

---

# Environment details
United States phone numbers.  macOS 10.14.6, Chrome 81.0.4044.92 on the browser side.

---

**Comment by kekzoz** [comment]
This happened to me using the UK phone number too.  Came here to add the issue, had already been added!

**Comment by LinuxOnTheDesktop** [comment]
I have just run afoul of this. I really could have done without yet another problem.

There are also the following impediments.

1. The phone service asks for 'meeting id' while the informational window within Jitsi Meet speaks of a 'PIN'.
2. I am unsure it is helpful that the icon for the telephone caller is the country code for their country.
3. The recorded message speaks of the 'pound' button, which will confuse British people - and this was the message played when dialling a UK number. We call that button 'hash'. Changing the recorded message might be impractical, but you could add the information to the aforementioned informational window.

**Comment by DaveOoff** [comment]
Hello, this issue is still present today with the behavior described in the first post, in France. Any news regarding a future fix/update ?

**Comment by saghul** [comment]
I believe using a numeric PIN works now, but if you set it to something a phone cannot dial you're out of luck.

**Comment by DaveOoff** [comment]
> I believe using a numeric PIN works now, but if you set it to something a phone cannot dial you're out of luck.

I've tried a numeric password phone dialable, but still have the same issue : phone hang up after trying to join the conference room. Works fine without room password.

**Comment by saghul** [comment]
@damencho Didn't this work?

**Comment by damencho** [comment]
You need to pass the password with sip headers, the same way you pass the room to join.

**Comment by DaveOoff** [comment]
> This is not supported on meet.jit.si at the moment.

Can this issue be re-open to be fixed later ?
