### ISSUE TITLE
Lets Encrypt setup error about missing file

### ISSUE THREAD

**Issue by TopheC** [jitsi/jitsi-meet#5929]
## Description
I have installed Jitsi Meet for the first time and now I can’t get any further at the point of Lets Encrypt certificate.

---

## Current behavior
I get the following error message:

```
# Unable to find deploy-hook command /etc/letsencrypt/renewal-hooks/deploy/0000-coturn-certbot-deploy.sh in the PATH.
# (PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

---

## Expected Behavior
Setup with no errors at the point of Lets Encrypt certificate.

---

## Possible Solution
From this official quick install guide : https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
**BEFORE** chapter Generate a Let’s Encrypt certificate (optional, recommended) i’ll do that under root account :

```
# mkdir -p /etc/letsencrypt/renewal-hooks/deploy/ 
# touch 0000-coturn-certbot-deploy.sh
# chmod +x 0000-coturn-certbot-deploy.sh

```
the file is empty, but then you can setup Lets Encrypt without errors :

`# /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`

2 other fellows have tested this workaround with success.

---

## Steps to reproduce

Strictly follow the quick install guide https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

---

## Environment details
**_Fellow1_**: Debian 9.4 with Nginx
**_Me_** : Scaleway (French Cloud Provider) DEV1-M instances with Debian Stretch 9.12 (GNU/Linux 4.9.0-11-amd64 x86_64) up to date. With only Jitsi installed. 

---

**Comment by damencho** [comment]
https://community.jitsi.org/t/lets-encrypt-problem/32857

**Comment by lebovic** [comment]
Looks like this was resolved by https://github.com/jitsi/jitsi-meet/commit/be565212677ef9f410cba8c37a48a85e7f9be6f0#diff-4c5b794585e04357b12aaf526757db9f?

**Comment by damencho** [comment]
Yes. Thanks.
