### ISSUE TITLE
I cannot use web camera.

### ISSUE THREAD

**Issue by furu0819** [jitsi/jitsi-meet#5933]
Suddenly, the webcam is no longer available.
Please tell me how to deal with it.

**Comment by silentshotghost** [comment]
Try unplugging and replugging in and if not go to the settings in meet.jit.si and check connected devices

**Comment by furu0819** [comment]
Thank you for quick response.
I will try it.


2020年4月13日(月) 18:51 Rickie Noel <notifications@github.com>:

**Comment by Echolon** [comment]
@damencho 

I think can be closed due to: **Non-working camera meta-issue** #5425

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
