### ISSUE TITLE
Ошибка: все записывающие устройства заняты

### ISSUE THREAD

**Issue by Anna-Me** [jitsi/jitsi-meet#5934]
Добрый день! При попытке начать видео запись конференции, выдает ошибку: Все записывающие устройства заняты. В чем проблема? Как я могу ее решить?

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
