### ISSUE TITLE
i can't connect my own server

### ISSUE THREAD

**Issue by zhaoleigithub** [jitsi/jitsi-meet#5935]
[/Users/zhaolei/Desktop/WerewolfJPiOS/MegaWerewolf/Feature/CreateRoom/MGCreateRoomViewController.m:118] JitsiMeetViewDelegate CONFERENCE_TERMINATED {
    error = "AbortError: Aborted";
    url = "https://jitsi.53site.com/test999";
} 
How can I fix this error?

**Comment by luixxiul** [comment]
> If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org
>
> Questions posted to this repository will be closed.

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
