### ISSUE TITLE
How to use Rear camera? or if i want to switch camera in mobile browser then how can i do that?

### ISSUE THREAD

**Issue by jeetvirani** [jitsi/jitsi-meet#5936]

**Comment by silentshotghost** [comment]
Theirs a settings In mobile browser and on the app you has to press the three dots then more options and press toggle camera

**Comment by jeetvirani** [comment]
its not working. when we changed camera then its giving error : Failed to access your camera.

**Comment by jeetvirani** [comment]
@silentshotghost can you check this problem. when i am pressing toggle camera still not working. i have to reload my page.

**Comment by mirh** [comment]
> its not working. when we changed camera then its giving error : Failed to access your camera.

Then perhaps the problem is with the camera itself, rather than the "switching"?

**Comment by jeetvirani** [comment]
@mirh  Both camera is working fine. After switching if i reload page then its working means i have to disconnect and connect again for meeting.
Without reload its giving Failed to access Your Camera.

**Comment by jeetvirani** [comment]
any update on this ?

**Comment by saghul** [comment]
Sorry, no updates. Mobile browsers are not officially supported. As we've mentioned, there are some things to fixup before we can make that option directly available, and it looks like you found one more.

**Comment by Echolon** [comment]
ref. #6004

**Comment by DiamondJewelryLive** [comment]
Anybody figure out how to do this yet??

**Comment by saghul** [comment]
The mobile web has a camera switch button now.

**Comment by root0902** [comment]
> The mobile web has a camera switch button now.

Where can i find that?? I can't see any options in jitsi meet web config files.

**Comment by saghul** [comment]
It's on the 3 dots menu.

![image](https://user-images.githubusercontent.com/317464/157732319-66d2263a-ebfa-4cad-a795-c7be32c77bc3.jpeg)

**Comment by foolishgrunt** [comment]
Has this option moved?

<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/d2c02f88-ca27-4055-80b0-23dd11c39d3e" />

**Comment by foolishgrunt** [comment]
Nevermind, it appears to be there in Chromium-based browsers.

I'm seeing varying levels of issues when using Gecko-based browsers: Firefox and Fennec F-droid show the button but claim they lack permission to access the rear camera. IronFox doesn't show the button at all (see screenshot above).
