### ISSUE TITLE
TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by JewelKolpolok** [jitsi/jitsi-meet#5937]
I couldn't build the project for android because it's giving me below errors. can you please tell me what is the issue here.
![device-2020-04-13-142046](https://user-images.githubusercontent.com/45818144/79105277-2ce31c00-7d92-11ea-824a-5fb8d56f5ba3.png)

**Comment by saghul** [comment]
Cannot reproduce this with latest master.
