### ISSUE TITLE
Challenge failed for domain "my_domainName"

### ISSUE THREAD

**Issue by ajayartificialchat** [jitsi/jitsi-meet#5938]
Hello there,
I've tried to set-up jitsi-meet in my AWS Ec2 instance using the following link:
Deploying Jitsi on Amazon EC2
https://aws.amazon.com/blogs/opensource/getting-started-with-jitsi-an-open-source-web-conferencing-solution/

But I've got the following error:

> Challenge failed for domain "my_domainname"
> http-01 challenge for "my_domainname"
> Cleaning up challenges
> Some challenges have failed.
> 
> IMPORTANT NOTES:
>  - The following errors were reported by the server:
> 
>    Domain: "my_domainname"
>    Type:   dns
>    Detail: No valid IP addresses found for "my_domainname"
>  - Your account credentials have been saved in your Certbot
>    configuration directory at /etc/letsencrypt. You should make a
>    secure backup of this folder now. This configuration directory will
>    also contain certificates and private keys obtained by Certbot so
>    making regular backups of this folder is ideal.

Also I've check the same error in your open:issue
https://community.jitsi.org/t/lets-encrypt/26413

So, would you inform here you have fix the bug in your stable version or not?
And please acknowledge me, it will very helpful to me
Thanks

**Comment by saghul** [comment]
You seem to not have a valid DNS entry for the domain you are configuring.
