### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by EverlynAsiko** [jitsi/jitsi-meet#5939]
I have this issue that all recorders are busy. What can i do to stop it?

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
