### ISSUE TITLE
no puedo grabar reunión

### ISSUE THREAD

**Issue by cesardavidrodas** [jitsi/jitsi-meet#5943]
Estimados
Cómo podría solucionar que no puedo grabar reuniones en jitsi.
Gracias

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
