### ISSUE TITLE
kameraya ulaşılamıyor.

### ISSUE THREAD

**Issue by vildanayd** [jitsi/jitsi-meet#5944]
kamera bazen açılıyor bazen açılmıyor.

**Comment by Echolon** [comment]
@damencho 

I think can be closed due to: **Non-working camera meta-issue** #5425

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
