### ISSUE TITLE
Official Jitsi-Meet Plugin for ConverseJS

### ISSUE THREAD

**Issue by ericschdt** [jitsi/jitsi-meet#5946]
Jitsi-Meet is great for A/V conferences but its chat capabilities are rather limited. 

There's however [ConverseJS](https://github.com/conversejs/converse.js/) a feature rich web-based XMPP/Jabber chat client written in JavaScript, which however only supports A/V by a weakly integrated [community plugin](https://github.com/conversejs/community-plugins/tree/master/jitsimeet).

Therefore I would like to suggest a marriage of ConverseJS and Jitsi-Meet or respectively an official plugin, which integrates better with ConverseJS. 

Combined it would become something like Skype for web. :)

**Comment by deleolajide** [comment]
> but its chat capabilities are rather limited

Would you care to elaborate a bit more about that?

>weakly integrated community plugin.

Exactly what features are you missing?

>which integrates better with ConverseJS

Could you provide a more detailed description of what this means? What business function are you implementing and what communication problems are you solving?

>a marriage of ConverseJS and Jitsi-Meet

Already been done. See https://archive.fosdem.org/2019/schedule/event/pade/

**Comment by saghul** [comment]
We cannot really spread ourselves thinner here, and as @deleolajide pointed out there is already existing work.

**Comment by kimcosmos** [comment]
Omemo xmpp e2e is in converse and not in Jitsi meet
