### ISSUE TITLE
Camera rarely recognized

### ISSUE THREAD

**Issue by izengrino** [jitsi/jitsi-meet#5947]
Hello,
first let me thank you for this project I really appreciate. That's a good job and this Covid19 era demonstarte this every day :-).

Now my issue.
I have been able to get both camera and microphone recognized together in a jitsi meet session.
However this doesn't reproduce often. Most of the time I get a meesage stating the camera couldn't be accessed.

**Comment by izengrino** [comment]
Please find below some info I grab that may help you.
Let me know if I can provide any other info.

Chrome version is:  Version 81.0.4044.92 (Build officiel) Arch Linux (64 bits)
Camera (via lsusb): Bus 002 Device 003: ID 046d:0990 Logitech, Inc. QuickCam Pro 9000

![jitsi-console1](https://user-images.githubusercontent.com/63585576/79112508-023b9800-7d7f-11ea-99ef-7357e6dfc6de.png)

![jitsi-console2](https://user-images.githubusercontent.com/63585576/79112428-d5878080-7d7e-11ea-872a-9552ad8e9a05.png)

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue. As your log seems really relevantl, I assume it'd be really helpful if you'd leave it there as a comment as well.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
