### ISSUE TITLE
Disable Moderator rights granted to notifications

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#5948]
**Is your feature request related to a problem you are facing?**
Every user in our on-premise Jitsi deployment get moderator rights and users are comply about that notification.
![image](https://user-images.githubusercontent.com/4023037/79117646-58ff9c80-7d94-11ea-8801-6c9c553029fc.png)

**Describe the solution you'd like**
Please make that notifications configurable like it done with Join\Leave notifications in that PR https://github.com/jitsi/jitsi-meet/pull/4985

**Comment by ankar84** [comment]
@mynameisbrendan hi!
Yes! We have the same setup with jwt authorization and every non guest user gets moderator rights. 
It's not good.

**Comment by anpel** [comment]
I would like a way to disable this notification as well.

**Comment by damencho** [comment]
You can do this by setting this https://github.com/jitsi/jitsi-meet/blob/a18fd1cdb39ee05696e262ef8a1f17c99f62b861/interface_config.js#L85

**Comment by mynameisbrendan** [comment]
> You can do this by setting this
> 
> https://github.com/jitsi/jitsi-meet/blob/a18fd1cdb39ee05696e262ef8a1f17c99f62b861/interface_config.js#L85

Thanks as always.  A quick and correct response, I can confirm this is working for me

**Comment by ankar84** [comment]
Actually 

> DISABLE_FOCUS_INDICATOR: true

,
fixed that annoying notification
Thanks. @damencho

**Comment by Digital-Nerd** [comment]
can someone tell me how to make only one person a moderator and the rest all as a regular participant? Also, any proper documentation or video link explaining how to configure all the options in jitsi
