### ISSUE TITLE
Error de cámara

### ISSUE THREAD

**Issue by brunella787213373** [jitsi/jitsi-meet#5951]
No me anda la cámara, me aparece un cartel que dice: "No podemos acceder a su cámara. Verifique si otra aplicación esta usando este dispositivo, seleccione otro dispositivo en el menú de configuración o intente volver a cargar la aplicación. "
Pero no estoy usando otra aplicación y ya intente en volver a cargar la pagina pero sigue apareciendo lo mismo. 
Necesito una solución ya que uso esto para estudiar online debido a el momento que estamos atravesando con el coronavirus.

**Comment by Echolon** [comment]
@damencho 

I think can be closed due to: **Non-working camera meta-issue** #5425
