### ISSUE TITLE
Unable to access camera in Chromium / Firefox / AppImage

### ISSUE THREAD

**Issue by hklaufus** [jitsi/jitsi-meet#5952]
Starting Jitsi Meet with `./jitsi-meet-x86_64.AppImage --no-sandbox` on Fedora 31 gives a messsage **Unable to access camera** .

There is no other application accessing the camera, and I have no other camera device in the settings menu, no other then the built in camra, that apparently is identified as a USB Webcam.

I am trying to run _jitsi-meet-x86_64.AppImage_

EDIT: I do see myself in the main window, however the image is _mostly_ frozen, somtimes / irregularly the screen is updated.
Random horizontal bars appear through the screen.

![Screenshot from 2020-04-13 15-31-31](https://user-images.githubusercontent.com/17512132/79125740-ee079300-7d9e-11ea-9e65-3ec88b138e89.png)

![Screenshot from 2020-04-13 15-48-41](https://user-images.githubusercontent.com/17512132/79125745-f19b1a00-7d9e-11ea-8d1a-e5e9e46139a3.png)

**Comment by hklaufus** [comment]
From `https://test.webrtc.org/`:
 Microphone
Camera
Check resolution 320x240
[ INFO ] cameraName: USB Webcam: USB Webcam
[ INFO ] actualVideoWidth: 0
[ INFO ] actualVideoHeight: 0
[ INFO ] mandatoryWidth: 320
[ INFO ] mandatoryHeight: 240
[ INFO ] isMuted: false
[ INFO ] testedFrames: 0
[ INFO ] blackFrames: 0
[ INFO ] frozenFrames: 0
[ INFO ] Not available: encodeSetupTimeMs, avgEncodeTimeMs, minEncodeTimeMs, maxEncodeTimeMs, avgInputFps, minInputFps, maxInputFps, avgSentFps, minSentFps, maxSentFps
[ INFO ] Cannot verify sent FPS.
[ FAILED ] Incorrect captured resolution.
[ FAILED ] Could not analyze any video frame.
Check resolution 640x480
[ INFO ] cameraName: USB Webcam: USB Webcam
[ INFO ] actualVideoWidth: 640
[ INFO ] actualVideoHeight: 480
[ INFO ] mandatoryWidth: 640
[ INFO ] mandatoryHeight: 480
[ INFO ] isMuted: false
[ INFO ] testedFrames: 137
[ INFO ] blackFrames: 0
[ INFO ] frozenFrames: 0
[ INFO ] Not available: encodeSetupTimeMs, avgEncodeTimeMs, minEncodeTimeMs, maxEncodeTimeMs, avgInputFps, minInputFps, maxInputFps, avgSentFps, minSentFps, maxSentFps
[ INFO ] Cannot verify sent FPS.
[ OK ] Captured video using expected resolution.
Check resolution 1280x720
[ INFO ] cameraName: USB Webcam: USB Webcam
[ INFO ] actualVideoWidth: 0
[ INFO ] actualVideoHeight: 0
[ INFO ] mandatoryWidth: 1280
[ INFO ] mandatoryHeight: 720
[ INFO ] isMuted: false
[ INFO ] testedFrames: 0
[ INFO ] blackFrames: 0
[ INFO ] frozenFrames: 0
[ INFO ] Not available: encodeSetupTimeMs, avgEncodeTimeMs, minEncodeTimeMs, maxEncodeTimeMs, avgInputFps, minInputFps, maxInputFps, avgSentFps, minSentFps, maxSentFps
[ INFO ] Cannot verify sent FPS.
[ FAILED ] Incorrect captured resolution.
[ FAILED ] Could not analyze any video frame.
Check supported resolutions
[ OK ] Supported: 160x120
[ OK ] Supported: 160x120
[ INFO ] 320x180 not supported
[ OK ] Supported: 320x240
[ INFO ] 640x360 not supported
[ OK ] Supported: 640x480
[ INFO ] 768x576 not supported
[ INFO ] 1024x576 not supported
[ OK ] Supported: 1280x720
[ INFO ] 1280x768 not supported
[ INFO ] 1280x800 not supported
[ INFO ] 1920x1080 not supported
[ INFO ] 1920x1200 not supported
[ INFO ] 3840x2160 not supported
[ INFO ] 4096x2160 not supported
Network
Udp enabled
Tcp enabled
Ipv6 enabled
[ WARN ] Failed to gather IPv6 candidates, it might not be setup/supported on the network.
Connectivity
Relay connectivity
Reflexive connectivity
[ INFO ] Gathered candidate of Type: srflx Protocol: UDP Address: 87.213.250.165
[ WARN ] Could not connect using reflexive candidates, likely due to the network environment/configuration.
Host connectivity
Throughput
Data throughput
Video bandwidth
[ FAILED ] Frame rate mean is 0, cannot test bandwidth without a working camera.
[ INFO ] Send bitrate mean: NaN kbps
[ INFO ] Send bitrate standard deviation: NaN kbps
[ INFO ] RTT average: 0 ms
[ INFO ] RTT max: 0 ms
[ INFO ] Packets lost: -1

**Comment by hklaufus** [comment]
Ref #5425
Close this issue.

**Comment by hklaufus** [comment]
Not working with update 3 in #5425
Reopened

**Comment by saghul** [comment]
Do you get the same behavior in the Chrome browser or iss it just the Electron app?

**Comment by hklaufus** [comment]
Yes, same behaviour, but in _Chromium_ browser

**Comment by saghul** [comment]
Does this example work, if you select "HD" ? https://webrtc.github.io/samples/src/content/getusermedia/resolution/

If not, does this one do it? https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by hklaufus** [comment]
Hi Saghul

First one does not work, but the second (https://webrtc.github.io/samples/src/content/getusermedia/gum/) **does** work in Chromium, and it also works in Firefox!
Great!

**Comment by hklaufus** [comment]
Hi @saghul , any news?

**Comment by Echolon** [comment]
@hklaufus would you be so kind and precise you issue title so it's easier to differential from other related. We experience lots of duplicates at the moment.

Still, thank you for your efforts and report!

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by hklaufus** [comment]
Still not functioning with Firefox 81.0.1, nor Chromium 85.0.4183.121 under Fedora 33.

**Comment by nikiwaibel** [comment]
same here
