### ISSUE TITLE
no puedo grabar la conferencia

### ISSUE THREAD

**Issue by CAPV03** [jitsi/jitsi-meet#5953]
hola la conferencia no la puedo grabar como puedo hacer o como me pueden ayudar?

**Comment by edwin-aguilar** [comment]
Tampoco puedo grabar, mensaje todas las grabadoras están ocupadas, significa se saturó repositorio web de jitsi?

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
