### ISSUE TITLE
I WANT TO RECORDING MY MEET 

### ISSUE THREAD

**Issue by GustavoMenin** [jitsi/jitsi-meet#5957]

**Comment by GustavoMenin** [comment]
I can´t do it because "all recorder are busy"

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
