### ISSUE TITLE
Jitsi Recording...

### ISSUE THREAD

**Issue by word2u** [jitsi/jitsi-meet#5961]
I have been trying to record a video through Jitsi...and it keeps telling me that all recorders are currently busy...   Is this normal?  Is there a time that is better to record videos?  Need a little help here...

Thanks!

Drew
word2u@writeme.com

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
