### ISSUE TITLE
Wrongly generated config file on fresh install

### ISSUE THREAD

**Issue by malumoe** [jitsi/jitsi-meet#5962]
## Description
---
I just installed jitsi-meet on a Debian Buster server and encountered a wrongly generated config file, located in `/etc/jitsi/meet/`. For privacy reasons, let's assume the domain for the jitsi instance was `myjitsyinstance.mydomain.tld`. The mistake is in `/etc/jisti/meet/myjitsiinstance.mydomain.tld-config.js`.

Nevertheless, the server works flawlessly anyway with or without the error in the config file.

## Current behavior
---
The installer creates the mentioned file and in my case, I find the following lines (comments excluded):

```
var config = {
    hosts: {
        domain: 'myjitsiinstance.mydomain.tld',
        muc: 'conference.<!--# echo var="subdomain" default="" -->myjitsiinstance.mydomain.tld'
    },
   [...]
```

## Expected Behavior
---

I expect the `muc` line to be generated as follows:

```
var config = {
    hosts: {
        domain: 'myjitsiinstance.mydomain.tld',
        muc: 'conference.myjitsiinstance.mydomain.tld'
    },
   [...]
```

## Possible Solution
---
unknown

## Steps to reproduce
---

- Set up a fresh Debian buster instance.
- Followed the Jitsi Meet quick install guide (installed it by `apt-get install jitsi-meet`
- Encountered the problem above

# Environment details
---
`Linux myjitsiinstance.mydomain.tld 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`

`apt list | egrep '(jitsi|jicofo|jvb|prosody)'` (hope that's helpful)

```
jicofo/stable,now 1.0-544-1 all  [Installiert,automatisch]
jicofo/stable 1.0-508-1 i386
jitsi-archive-keyring/stable 1.0.1 all
jitsi-meet-prosody/stable,now 1.0.3992-1 all  [Installiert,automatisch]
jitsi-meet-tokens/stable 1.0.3992-1 all
jitsi-meet-turnserver/stable,now 1.0.3992-1 all  [Installiert,automatisch]
jitsi-meet-web-config/stable,now 1.0.3992-1 all  [Installiert,automatisch]
jitsi-meet-web/stable,now 1.0.3992-1 all  [Installiert,automatisch]
jitsi-meet/stable,now 2.0.4416-1 all  [installiert]
jitsi-videobridge2/stable,now 2.1-169-ga28eb88e-1 all  [Installiert,automatisch]
jitsi-videobridge/stable 1126-1 amd64
jitsi-videobridge/stable 1126-1 i386
jitsi/stable 2.10.5550-1 amd64
jitsi/stable 2.10.5550-1 i386
prosody-modules/stable,stable 0.0~hg20190203.b54e98d5c4a1+dfsg-1+deb10u1 all
prosody/stable,now 0.11.2-1 amd64  [Installiert,automatisch]
ruby-diaspora-prosody-config/stable 0.0.7-1 all
```

**Comment by damencho** [comment]
Please when having problems or questions use the community forum before opening new issues. 

The file is correct this is a server-side include which is replaced when file is being served. If it is not, maybe ssi is not turned on, or it is not turned on for js files for some reason.
https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-web-config.postinst#L107
