### ISSUE TITLE
CANT RECORD

### ISSUE THREAD

**Issue by lilyorge** [jitsi/jitsi-meet#5966]
It says that there are no recorders available, what do I do?

**Comment by edmundlaugasson** [comment]
that is problematic for mee, too

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
