### ISSUE TITLE
Jitsi canta accede to my Integrated - Webcam

### ISSUE THREAD

**Issue by claudiodevigili** [jitsi/jitsi-meet#5969]
When start to use Jitsi, i can used it very well. But, then, when I try to make another chat room, appear a message saying "Can access to camera", but turns  it on de Camm Light.
When I use other programs, seems all to be allright.

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
