### ISSUE TITLE
No puedo poner mi camara

### ISSUE THREAD

**Issue by Yogaentigre** [jitsi/jitsi-meet#5971]
Hola, buenas tardes.

No puedo poner la cámara ya que me detecta una cámara que no tengo, necesito borrar la opción de epoccam que no tengo y usar la determinada por el sistema.

Por otro lado hoy hice una prueba de llamada y una persona entró a la conversación, la podía ver. Quiero saber si hay alguna manera que pueda limitar esto para que no vuelva a ocurrir y si los codigos son tan abiertos que cualquier entra a las llamadas

**Comment by Echolon** [comment]
@damencho 

I think can be closed due to: **Non-working camera meta-issue** #5425

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
