### ISSUE TITLE
Start recording didn't start

### ISSUE THREAD

**Issue by csrspinozzi** [jitsi/jitsi-meet#5972]
Already connected with Dropbox start recording (a voice say something) and a red banner appears and say that it's not possible to record the screen.

**Comment by csrspinozzi** [comment]
![image](https://user-images.githubusercontent.com/61951705/79169187-253b6b80-7dc2-11ea-8f29-0e5f63dbf0bc.png)

**Comment by silentshotghost** [comment]
try it again

**Comment by edmundlaugasson** [comment]
same here...

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
