### ISSUE TITLE
sending endpoint text message Error: Channel support is disabled

### ISSUE THREAD

**Issue by cfry** [jitsi/jitsi-meet#5975]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

I am attempting to send a message via Jitsi

## Description
`var domain = 'beta.meet.jit.si' //'meet.jit.si'
var options = {
roomName: 'fry_room',
width: 490,
height: 470,
parentNode: jitsi_id // document.querySelector('#meet')
}
var api = new JitsiMeetExternalAPI(domain, options)
function text_listener(data){
console.log("got text data: " + JSON.stringify(data))
}
api.addEventListener('endpointTextMessageReceived', text_listener); 
api.executeCommand('sendEndpointTextMessage', api._myUserID, 'programmatic text');

## Current behavior
Text does not show up in the local or remote gui but rather errors with:
Logger.js:154 2020-04-11T17:53:23.026Z [modules/API/API.js] <Object.send-endpoint-text-message>: Failed sending endpoint text message Error: Channel support is disabled!
at t.value (VM1479 lib-jitsi-meet.min.js:1)
at oe.sendEndpointMessage (VM1479 lib-jitsi-meet.min.js:10)
at Object.sendEndpointMessage (VM1480 app.bundle.min.js:126)
at Object.send-endpoint-text-message (VM1480 app.bundle.min.js:126)
at b.on (VM1480 app.bundle.min.js:126)
at n.size.n.forEach.e (VM1480 app.bundle.min.js:29)
at Set.forEach ()
at p.emit (VM1480 app.bundle.min.js:29)
at p._onMessageReceived (VM1480 app.bundle.min.js:29)
at postis.listen.e (VM1480 app.bundle.min.js:29)
at u (VM1480 app.bundle.min.js:152)

## Expected Behavior
Seeing the text in the GUI on both the sender and the reciever.
Seeing my text_listener function called.

## Possible Solution
See description, but I don't really care if that's the approach.
Any way I can send a text message via Jitsi from one
jitsi client to another, both "broadcase" to all participants,
and to target it to one participant would be great.

## Steps to reproduce
See description

# Environment details
Mac OS, code in description evaled in Electron V4

**Comment by dlbdvd96** [comment]
I have the same issue.

**Comment by jminor** [comment]
I had the same "Channel support is disabled" problem, so I experimented with the openBridgeChannel options to see if that would help. Every once in a while a message goes through, but 99% do not.

`configOverwrite: { openBridgeChannel: 'datachannel' }`

From another thread, I found a suggestion to try connecting via the domain `beta.meet.jit.si` instead. That did the trick, and now sendEndpointTextMessage is working great. 
```
const domain = 'beta.meet.jit.si';
const options = { ... };
const api = new JitsiMeetExternalAPI(domain, options);
```

Also, @cfry, two things to note: 1) Your sample code is sending an endpoint message to yourself - you might want to try sending to a different participantId. 2) These endpoint text messages are not the same as the chat text messages that you see in the UI. I don't see any exposed API for chat messages.

**Comment by cfry** [comment]
thanks Joshua, this sounds like "the missing manual"!

**Comment by horymury** [comment]
hi @cfry ,

Is this still an issue for you? Just tested on both `beta.meet.jit.si` and `meet.jit.si` and it seems to work fine now.

**Comment by wuttke** [comment]
Doesn't work for me - same exception.
I tried configOverwrite: { openBridgeChannel: 'datachannel' } and beta.meet.jit.si.

**Comment by MANNAISALIM** [comment]
i try with both beta.meet.jit.si and meet.jit.si but i got this error 
 [modules/statistics/AvgRTPStatsReporter.js] <m.addNext>:  bandwidth_upload - invalid value for idx: 0 undefined

**Comment by MANNAISALIM** [comment]
i have th same issue help please !!

**Comment by rulucay** [comment]
I have the same issue

**Comment by zsinba** [comment]
I have the same issue

**Comment by codebeginer** [comment]
When testing on mac this error appears and on ubuntu os this errors does not appear.
