### ISSUE TITLE
Contraseñas de reuniones

### ISSUE THREAD

**Issue by Yogaentigre** [jitsi/jitsi-meet#5976]
No puedo ponerle contraseñas a las reuniones. Se las pongo y se borran.

**Comment by Yogaentigre** [comment]
no puedo unir desde la compu el streaming en youtube.

**Comment by Echolon** [comment]
> I can't put passwords on meetings. I put them on and they get deleted.

**Comment by Echolon** [comment]
Please refer to #5701, #5720, #6403, #6530 in terms of the passwords.

If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
