### ISSUE TITLE
30/60fps desktopsharingframerate for smoother screen sharing

### ISSUE THREAD

**Issue by silentshotghost** [jitsi/jitsi-meet#5977]
https://github.com/jitsi/jitsi-meet/blob/edb8ecd54217da6bfdb61da3806c5710313add16/config.js#L169-L173

change 
Optional desktop sharing frame rate options. Default value: min:5, max:5.
    // desktopSharingFrameRate: {
    //     min: 30,
    //     max: 30
    // },

**Comment by silentshotghost** [comment]
over even to 
Optional desktop sharing frame rate options. Default value: min:5, max:5.
// desktopSharingFrameRate: {
// min: 60,
// max: 60
// },

**Comment by silentshotghost** [comment]
i try to do yoga videos but it's to laggy at least 30fps would be nice

**Comment by ndastur** [comment]
Is this now available. Can't find the config in the main documentation. Thanks

**Comment by l3d00m** [comment]
I'm not exactly sure what the issue here is. If you want more FPS, you can change those variables on your own deployment. If that doesn't work, please refer to #5382.

**Comment by feulix** [comment]
I've got this issue on my own deployment, DigitalOcean droplet running Ubuntu 18.04.3 LTS, with jitsi-meet stable installed.
Config:
```
    desktopSharingFrameRate: {
         min: 30,
         max: 30
    }
```
Happy to help if you need any more information.
