### ISSUE TITLE
Wrong file permissions for certificates and turnserver.conf

### ISSUE THREAD

**Issue by perryflynn** [jitsi/jitsi-meet#5978]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

Turnserver not opens TLS Ports.

## Current behavior

Certificate files issued by certbot (setup with your letencrypt bash script) have the following access permissions: `-rw------- 1 root root`. Because coturn runs as user `turnserver`, the certificates are not accessible for coturn.

## Expected Behavior

coturn should open the TLS Port.

## Possible Solution

- `chmod a+r /etc/jitsi/meet/meet.example.eu*`
- or: copy the cert one more tune with the correct permissions for coturn in the deploy hook

## Steps to reproduce

- Install jitsi-meet
- Install jitsi-meet-turnserver
- Install Lets Encrypt with your script

# Environment details

- Debian 10
- Everything installed with apt and your Lets Encrypt script

**Comment by damencho** [comment]
Hum the let's encrypt scripts already create a folder and use a copy of the LE certs and does not use those for the web.
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-turn/coturn-certbot-deploy.sh#L26
Which version have you installed?
Do you have this file https://github.com/jitsi/jitsi-meet/blob/master/resources/install-letsencrypt-cert.sh#L46 ?

**Comment by perryflynn** [comment]
The setup is 16 days old.

```
root@jitsi:~# curl -s http://127.0.0.1:8080/about/version
{"name":"JVB","version":"2.1.169-ga28eb88e","os":"Linux"}
```

```
root@jitsi:~# cat /etc/turnserver.conf
# jitsi-meet coturn config. Do not modify this line
use-auth-secret
keep-address-family
static-auth-secret=XXXXXXX
realm=meet.XXXXX.eu
cert=/etc/jitsi/meet/meet.XXXXX.eu.crt
pkey=/etc/jitsi/meet/meet.XXXXX.eu.key

# no-tcp
listening-port=4446
tls-listening-port=4445
external-ip=116.203.XXXX.XXXX

syslog
```

First time I've issued a cert there was no turnserver. I've installed it afterwards. Maybe the hook was not executed because of it.

But why the turnserver config contains the cert which is used by jitsi-meet?

**Comment by damencho** [comment]
Cause it is behind the same domain. But we had changed the behavior and now the certs are copied in a special folder used only for coturn. And this copy is done on every renew.

**Comment by perryflynn** [comment]
Yes I've installed a new server right now and it worked without issues.
Thanks!

```
# jitsi-meet coturn config. Do not modify this line
use-auth-secret
keep-address-family
static-auth-secret=XXXXXXXXXXXX
realm=static.XXXXXXXXXXX.clients.your-server.de
cert=/etc/coturn/certs/static.XXXXXXXXX.clients.your-server.de.fullchain.pem
pkey=/etc/coturn/certs/static.XXXXXXXX.clients.your-server.de.privkey.pem

# no-tcp
listening-port=4446
tls-listening-port=4445
external-ip=XXXXXXXXXX

syslog
```
