### ISSUE TITLE
P2P not always used in 1 to 1 communication

### ISSUE THREAD

**Issue by mikelpzm** [jitsi/jitsi-meet#5979]
I see that when there are only 2 persons, it doesn't always use P2P connection in my hosted jitsi.

Sometimes I see that P2P is used, but not always. Any guess on what could it be? Same test, same 2 devices.

What could I test?

I have the following:

```
 p2p: {
        // Enables peer to peer mode. When enabled the system will try to
        // establish a direct connection when there are exactly 2 participants
        // in the room. If that succeeds the conference will stop sending data
        // through the JVB and use the peer to peer connection instead. When a
        // 3rd participant joins the conference will be moved back to the JVB
        // connection.
        enabled: true,

        // Use XEP-0215 to fetch STUN and TURN servers.
        useStunTurn: true,

        // The STUN servers that will be used in the peer to peer connections
        stunServers: [

            { urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443' }
        ],
```

**Comment by damencho** [comment]
Do you have turn configured and running?
When p2p is not being able to be established the media can be relayed through turn and if that fails the jvb connection is used.

Please use the community forum for questions before opening new issues.
