### ISSUE TITLE
Tous les enregitreurs sont occupés 

### ISSUE THREAD

**Issue by FarrahVirus** [jitsi/jitsi-meet#5983]
Bonjour, 

A chaque fois que je veux lancer l'enregistrement sur dropbox, un message me dit que les rnregistreurs sont occupés. Comment puis-je résoudre ce problème svp ?

**Comment by Echolon** [comment]
> Every time I want to start recording on dropbox, a message tells me that the recorders are busy. How can I solve this problem?

@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403
