### ISSUE TITLE
El programa no graba

### ISSUE THREAD

**Issue by Charlsdelgado** [jitsi/jitsi-meet#5985]
Porqué no puedo grabar una video llamada?

gracias

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403

**Comment by Charlsdelgado** [comment]
Pues no entiendo su respuesta. Le digo q el programa no siempre graba.
Porque es eso?

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
