### ISSUE TITLE
How to work with localisation now

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#5989]
Hi! Are any news with working on the localisation? I put certain efforts with the Ukrainian language, however, there is still no language locale in the language.json file, while languages-uk.json file is not editable... How to proceed, please, help me.

**Comment by damencho** [comment]
Nope, we haven't advanced on enabling Crowdin. We will try to finish it this week and announce it in the thread about translate.jitsi.org where everyone is watching.

**Comment by damencho** [comment]
Please when you have questions post them in the relevant thread if already exist or use the community forum before opening new issues.

**Comment by ostasevych** [comment]
> Please when you have questions post them in the relevant thread if already exist or use the community forum before opening new issues.

Please, help me to find, where to place my questions? Where is the forum?..

**Comment by damencho** [comment]
It is stated in the template of issues which is shown when you create issues, saying to put your questions there. https://community.jitsi.org/
I think I had already answered you follow https://github.com/jitsi/jitsi-meet/issues/4758 for updates, there is still no update. We will announce it there once it is done and we have a new translation service.
