### ISSUE TITLE
Grabación de videollamadas

### ISSUE THREAD

**Issue by RainCami** [jitsi/jitsi-meet#5995]

**Comment by RainCami** [comment]
Buenos días, estoy teniendo problemas con Jitsi meet en estos momentos, ya que no me permite grabar las videollamadas, dice que las grabaciones estan ocupadas o no funciona, agradezco su ayuda.

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **meet.jit.si recording - no audio recorded** #5403
