### ISSUE TITLE
Start muted

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#6]
@yanas will add a GUI option that allows organisers to specify whether participants in a conference are supposed to start with their microphone muted and/or webcam turned off. 

Once this is ready, we would need the focus to indicate it in its invitations.

**Comment by bgrozev** [comment]
Implemented.

**Comment by perguth** [comment]
How to enable the default muting? It doesn't work for me using https://meet.jit.si

**Comment by paweldomas** [comment]
Currently it works with this URL syntax:
`https://meet.jit.si/something123#config.startWithAudioMuted=true`

In the settings -> more tab there's option to make everyone start muted which can be useful for bigger conferences.

**Comment by paweldomas** [comment]
Also please use our community page https://community.jitsi.org for asking questions next time

**Comment by perguth** [comment]
For completeness for all Googlers: 🎆 

**Append the following to your invite URL** to start out muted: `#config.startWithAudioMuted=true&config.startWithVideoMuted=true`

**Comment by perguth** [comment]
After the computer comes back from sleep, Jitsi just starts with video/audio recording enabled--regardless of what it has been configured to do.
