### ISSUE TITLE
Move "toggle camera" button out from the Menu

### ISSUE THREAD

**Issue by tanty** [jitsi/jitsi-meet#6004]
During my conferences using the mobile app (Android), I tend to change frequently from the front to the rear camera. Having to open the menu and search for the proper button in order to do so is quite annoying.

Move the "Toggle camera" button out from the menu and place it straight away into the main view. Most of the other conferencing applications (Skype, WhatsApp, Hangouts, etc.) have it also this way.

Alternatively, if not wanting to add a new button, it would be great to add a "press-and-hold" context bubble menu in the existing camera button which will pop also the option of toggling the camera.

**Comment by tanty** [comment]
Let's make some activity, then.

**Comment by tanty** [comment]
... and some more activity ...

**Comment by tanty** [comment]
... and some more activity ...

**Comment by DiamondJewelryLive** [comment]
Any action on this??

**Comment by saghul** [comment]
No, we have no plans to change the current button placement.

**Comment by mirh** [comment]
I cannot think to a single videocall program that hasn't the button readily available in the call view.
