### ISSUE TITLE
Move "Select the sound device" button out from the Menu

### ISSUE THREAD

**Issue by tanty** [jitsi/jitsi-meet#6005]
During my conferences using the mobile app (Android), it is handy to change from the speaker to the phone "sound device" frequently. Having to open two menus and search for the proper buttons in order to do so is quite annoying.

Move the "Select the sound device" button out from the menu and place it straight away into the main view. Also, change the inner Menu so it is not so invasive. Many of the other conferencing applications have it also this way.

The menu can be a toggle which will rotate among the possible options. Also, it would be great to have a "press-and-hold" context bubble menu in this new button or, directly, in the mute button, which will pop also the option of selecting the sound device.

**Comment by ostasevych** [comment]
I fully support!

**Comment by tanty** [comment]
@saghul any specific reason to close this straight away?

I've tried to find some other previous issue or community discussion addressing the same concern but I've failed so any explanation or link would be welcome.

**Comment by saghul** [comment]
Sorry for the close with no explanation, I thought I had written something, but it just have skipped.

We are working on a redesign of the menus. We have some constraints to work with (buttons on the main menu on small devices for instance) and what you may find the most useful option others may never use, so hopefully the new design improves things for many, but it’s virtually impossible to create something nobody can’t complain about.

**Comment by tanty** [comment]
There you go, recent activity to prevent this mindless bot from closing this issue, which is still relevant.

**Comment by damencho** [comment]
This is already done. Device changes can be done through the mute audio and video buttons.
