### ISSUE TITLE
web cam no se activa

### ISSUE THREAD

**Issue by JMVB1001** [jitsi/jitsi-meet#6006]
Hola espero se encuentren bien de salud junto a sus seres queridos.
Tengo el problema que en la laptop no me deja usar la webcam, en el movil si.
Necesito la laptop para realizar la presentación de la charla.
Agradezco de antemano su apoyo.
![image](https://user-images.githubusercontent.com/63106928/79256490-bb68a380-7e4d-11ea-8b16-cc7f33249b98.png)

**Comment by Echolon** [comment]
@damencho 

I think it can be closed due to: **Non-working camera meta-issue** #5425

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
