### ISSUE TITLE
Move "Raise your hand" out from the Menu

### ISSUE THREAD

**Issue by tanty** [jitsi/jitsi-meet#6007]
During my conferences using the mobile app (Android), it is handy to be able to "Raise your hand" without having to open the menu and search for the proper button.

Move the "Raise your hand" button out from the menu and place it straight away into the main view.

**Comment by saghul** [comment]
THere is not enough pace to put all buttons on the main view.

**Comment by ostasevych** [comment]
> THere is not enough pace to put all buttons on the main view.

This is one of the most significant functions in online facilitation. Please, place this icon close to the big buttons.
