### ISSUE TITLE
Top "v" Menu is shown but does nothing

### ISSUE THREAD

**Issue by tanty** [jitsi/jitsi-meet#6008]
## Description

Using the mobile app (Android), when entering into a meeting room and, while showing the on screen buttons, I can see at the top of the view the name of the room, the duration of my stay in the room and a "v" arrow in the left corner, suggesting that there is a hidden menu. When pressing, nothing happens.

## Current behavior

I see a UI hint at the top left corner which suggests a menu. But nothing shows on pressing.
## Expected Behavior

I DO NOT see a UI hint at the top left corner or, if I see it some menu appears upon pressing it.

## Possible Solution

Remove the visual hint.

## Steps to reproduce

Enter a meeting and make the on screen controls visible.

# Environment details

Android

**Comment by saghul** [comment]
That should make the app enter picture-in-picture mode. What Android version do you have?

**Comment by tanty** [comment]
LineageOS 14.1 (Android 7.1.2) and EMUI 4.0.3 (Android 6.0)

**Comment by tanty** [comment]
Jitsi Meet 20.2.1 and 20.0.3 installed from F-Droid

**Comment by saghul** [comment]
Ah, PiP is only supported in Android >= 8. We'll get that hidden in unsupported versions, thanks for the report.
