### ISSUE TITLE
Remove the black shade gradients in the top and bottom of the on screen controls

### ISSUE THREAD

**Issue by tanty** [jitsi/jitsi-meet#6009]
When in a meeting in the mobile app (Android), if I press the display to make the on screen controls appear, a black gradient also appears at the top and the bottom. This gradients do not help but, actually, shade the background video stream, which is quite annoying.

Just remove the black gradients at the top and bottom.

**Comment by saghul** [comment]
That gradieent is there to help display the items in case the backgrounds are too light.

**Comment by tanty** [comment]
I guess this has already been discussed a number of times and that's why you are closing it straight away.

I'd say that there are better ways of helping to display the items in light background, like making the items to have contrast on their own. For example, a black border around them.

Using gradients is not how other apps out there are doing it and it is quite annoying to have quite a big chunk of the video feed shaded.
