### ISSUE TITLE
Add mode to use jitsi-meet for games via webcam.

### ISSUE THREAD

**Issue by silvio** [jitsi/jitsi-meet#6012]
**Is your feature request related to a problem you are facing?**
I am a big fan of the game Werewolfes, which is played with 5 players or more, usually in a social group. During the game, the eyes are often closed, but the players still hear all the sounds.

The rules of the game can be read here <https://www.playwerewolf.co/rules>.

**Describe the solution you'd like**
It would be good if jitsi could be switched into a kind of game mode where a certain host, groups of participants can disable and enable their camera.

**Comment by Echolon** [comment]
@silvio I am not sure if that is a real scope of Jitsi. I recommend to just play honestly for the moment. I will close this therefore.
