### ISSUE TITLE
Camera is not working

### ISSUE THREAD

**Issue by juliangomez12** [jitsi/jitsi-meet#6013]
Hi,
    I have a problem with my camera. The program is unable to access to it. How could I fix it?

**Comment by jallamsetty1** [comment]
Hi, can you share some more details about this issue ? Do you get a browser prompt for granting permissions to access camera. Please include all the relevant information like platform, browser, version and browser console logs.

**Comment by Echolon** [comment]
@jallamsetty1 

I think it can be closed due to: **Non-working camera meta-issue** #5425
