### ISSUE TITLE
Speaker countdown timer : show a remaining-time display to speakers

### ISSUE THREAD

**Issue by cron0mat** [jitsi/jitsi-meet#6015]
We are holding weekly meetings with ~20 people.
Everyone has max. 3 minutes to speak and to tell something about his work that may be interesting for others. Time is limited just to give everyone opportunity to tell something and to prevent exceeding meeting time.

Currently is one of us sharing our firefox/application showing [website](https://webuhr.de/timer-auf-3-minuten/) with a countdown timer.

It would be nice to have this feature built in jitsi-meet instead of working with external websites,
where meeting master can set/start/reset a countdown timer visible for everyone.

**Comment by dbrgn** [comment]
That would be a fantastic addition.

Another implementation option would be to show the "time since unmute" for every speaker. That might be easier to implement than an organizer controlled timer, but an organizer controlled timer might be more useful / flexible.

**Comment by bhack** [comment]
Please keep this open

**Comment by bhack** [comment]
Please keep this open

**Comment by theRAGEhero** [comment]
Is it done or just closed?

**Comment by saghul** [comment]
Closed. This is not a feature we are considering on adding to Jitsi Meet.
