### ISSUE TITLE
Can't record

### ISSUE THREAD

**Issue by camibarberclas** [jitsi/jitsi-meet#6017]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by luixxiul** [comment]
See here https://github.com/jitsi/jitsi-meet/issues/5403 and close this issue if you find a duplicate there. 

Since any post which ignores the template will be highly ignored for a legitimate reason, I'd recommend you to close this issue anyway.
