### ISSUE TITLE
Start live stream → All streamers are currently busy

### ISSUE THREAD

**Issue by gwolf** [jitsi/jitsi-meet#6019]
Hello,
I have been using Jitsi for my classroom work during the pandemic. I understand your resources will be quite strained... But would nevertheless like to know if there's anything I can do for this.
I try to record my classes via the bridge to YouTube live streaming, but some days (like today) I have had problems connecting them; I get the "All streamers are currently busy" message. I connect early, so there is better chance of me finding a spot among streamers - But today I have been unlucky so far ☹. 
What can you suggest me? If I set up and run my own Jitsi server, can I also set up such a bridge?

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5809

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
