### ISSUE TITLE
Todas las grabadoras están actualmente ocupadas

### ISSUE THREAD

**Issue by yucatancomercio** [jitsi/jitsi-meet#6020]
Quisiera grabar una sesión y casi siempre me da esa respuesta

**Comment by luixxiul** [comment]
Consulte aquí https://github.com/jitsi/jitsi-meet/issues/5403 y cierre este problema si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

**Comment by yucatancomercio** [comment]
Siempre me da ese mensaje:
Todas las grabadoras están actualmente ocupadas

Lo que me gustaría saber es la solución a este problema
yucatan.comercio@gmail.com

**Comment by luixxiul** [comment]
Lo siento, no tengo ninguna solución a tu problema. Pregúntele a un miembro del equipo por eso.

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
