### ISSUE TITLE
All Streamers Completely Busy

### ISSUE THREAD

**Issue by Pyrocracker** [jitsi/jitsi-meet#6026]
Please DELETE the Stream Feature! Please! You are frauding yourself by doing this. This is because it ruins your self image. You are simply unreliable. If you cannot let us stream whenever we NEED to, please don't give us false hope. Conversely, GIVE us the option to connect ATEM Blackmagic Switcher or Wirecast, ROSS, Grassvalley, OBS, etc. If not, please stay away from the streaming world. It's a wild wild world that you obvisouly cannot handle.

Yours Truly,

A REAL video producer.
PS: Why am I on Github? Shouldn't there be a customer support page?

**Comment by silentshotghost** [comment]
https://community.jitsi.org/

**Comment by luixxiul** [comment]
What the hell is this?
