### ISSUE TITLE
Acer laptop camera no working (access blocked|)

### ISSUE THREAD

**Issue by BigJohnSam** [jitsi/jitsi-meet#6028]

**Comment by saghul** [comment]
Please see: https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by BigJohnSam** [comment]
Thank you I spent about an hour looking at and trying what I could on 5425 but could not get any results.

**Comment by BiNeurale** [comment]
If your camera light blinks on and off while the picture stays black, and stops blinking when the window loses focus, this may be it — and it is not a driver or a privacy setting.
Acer installs a Device MFT (AcerMediaService.dll) that sits inside the Windows Media Foundation camera pipeline and processes every frame. After a recent Windows 11 update it loads but stops delivering frames, so every app gets black while Device Manager still reports the camera as healthy. The blinking is the app opening the stream, getting nothing, timing out and retrying.
The reason the registry fixes in this thread stop working after a reboot: the service AcerARTAIMMXDriverService re-registers the plug-in at every startup through DetectCameraDMFT.exe. You have to stop that service too.
The neat part is that Acer already ships the uninstaller for it — UninstallAcerCameraDMFT.exe, inside its own driver package.
I wrote it up with a script that runs read-only by default and tells you whether this is actually your problem before touching anything: https://github.com/BiNeurale/acer-camera-black-screen-fix
If the read-only run does not print CameraDeviceMftClsidChain, this is not your fault — stop there, the same symptom has several other causes.
