### ISSUE TITLE
accessibility issues.

### ISSUE THREAD

**Issue by davidacm** [jitsi/jitsi-meet#6029]
## Description
  The accessibility with screen readers need to be improved. I like this project and I'd like to use it but we need more compatibility with screen readers like NVDA, Voice Over, Orca, ETC. Others platforms like this have similar issues, but since this is an open source project, I see an oportunity to improve it while with others, they aren't interested in accessibility.

## Current behavior
  The system can be used by blind people, but with some issues.

* Is not possible to know the current toggle status, e.g. audio or video toggle.
* is not possible to navigate between controls, because the majority of them don't have the right role.
* The chat view is tedious to use with screen readers.

## Expected Behavior

All the controls and views can be accessed easily.

## Possible Solution
  As a developer with accessibility experience, I can help to improve the accessibility of the web client and android client app. I can't do tests on iOs but since you're using react-native, the fixes should work on iOs too.

## Steps to reproduce
---

1. Enable the screen reader of your device. Or use a free screen reader like [NVDA](https://www.nvaccess.org/)
2. Access the website.
3. Read the page with the screen reader and listen the elements and controls being spoken.

# Environment details
---

Computer: windows 10, chrome and firefox, NVDA 2019.3.1.
Mobile phone: android 9, Talkback the latest version.

**Comment by t3chguy** [comment]
Toggles/buttons were fixed by https://github.com/jitsi/jitsi-meet/pull/5432 but it was reverted because Space for Accessibility conflicts with Space for Push-To-Talk.

**Comment by davidacm** [comment]
Thanks, I searched for accessibility and I didn't see the mentioned issue, I'm closing this issue now.
