### ISSUE TITLE
Microsoft Azure - Ubuntu Server 15.10 - Quick Install

### ISSUE THREAD

**Issue by LukeStephen** [jitsi/jitsi-meet#603]
#Has anyone gotten the quick install to work on Microsoft Azure using Ubuntu Server 15.10 VM (also tried with 14.04 LTS, same results)?

I opened all ports in and out of the VM through Azure web portal

For the hostname I used the VMs public IP address and the self signed cert

When I go to Jitsi Meet I can see myself, I see the other Chrome device is connected, we can chat back and forth, but I can't see there video (it's just a black screen) and they can't see mine.

In Chrome developer tools I get "conference.js:185 CONFERENCE FAILED: conference.setup_failed"

**Comment by cheenwe** [comment]
same question

**Comment by herbat73** [comment]
I did it with Azure servers, all you need to

modify sip-communicator.properties file located at /etc/jitsi/videobridge
and add 2 lines

org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=Here you private adress (it is displayed in azure portal)
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=Here you public adress (it is displayed in azure portal)
open ports incoming ports https and 10000-20000
