### ISSUE TITLE
Las grabadoras están siempre ocupadas

### ISSUE THREAD

**Issue by LucianaElenaFinardi** [jitsi/jitsi-meet#6030]
Eso pasa muy a menudo

**Comment by luixxiul** [comment]
Duplicado de https://github.com/jitsi/jitsi-meet/issues/6020?

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
