### ISSUE TITLE
non va la camera

### ISSUE THREAD

**Issue by lorenzooropallo** [jitsi/jitsi-meet#6035]
salve,ho un problema sono entrato nella live e la camera non funziona potete risolvere questo problema

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5403

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
