### ISSUE TITLE
No puedo grabar videollamadas

### ISSUE THREAD

**Issue by Charlsdelgado** [jitsi/jitsi-meet#6036]
Siempre que intento grabar me pone este mensaje:

Todas la grabadoras están actualmente ocupadas.

Y nunca puedo grabar, no entiendo porqué tenéis esa función si nunca funciona.

Agradecería su ayuda.

Saludos cordiales.
Carlos

**Comment by luixxiul** [comment]
Duplicado de https://github.com/jitsi/jitsi-meet/issues/5995

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
