### ISSUE TITLE
streaming youtube

### ISSUE THREAD

**Issue by luciaugge** [jitsi/jitsi-meet#6038]
compare la scritta: tutti gli stramer sono impegnati al momento
riprova ma continuo a riprovare e non si avvia la diretta

**Comment by luixxiul** [comment]
See here https://github.com/jitsi/jitsi-meet/issues/5403 and close this issue if you find a duplicate there. If you cannot find, please provide additional information.

Vedi qui https://github.com/jitsi/jitsi-meet/issues/5403 e chiudi questo problema se ne trovi un duplicato. Se non riesci a trovare, ti preghiamo di fornire ulteriori informazioni.
