### ISSUE TITLE
Shortcut for switching "Share Audio" during sharing

### ISSUE THREAD

**Issue by rogerknop** [jitsi/jitsi-meet#6043]
**Is your feature request related to a problem you are facing?**
If PC micro and speakers are used and PC audio is shared in parallel, the user hears his voice doubled. This is not really nice. And therefore the shortcut would be helpful.

**Describe the solution you'd like**
During the sharing session it would be nice to toggle the "Share Audio" functionality with a shortcut to simple change the feature without ending the sharing.

**Describe alternatives you've considered**
A button in the controlled PCs toolbar would also be fine.

**Comment by rananajam1** [comment]
@rogerknop did you find anything on this?

**Comment by rogerknop** [comment]
> @rogerknop did you find anything on this?

No...

**Comment by saghul** [comment]
Sorry, looks like this one fell through the cracks. You mean toggling the share system audio in the screen sharing tab? That is not possible to change without stopping and restarting the share process I'm afraid.
