### ISSUE TITLE
[Suggestion] Entering/starting conference improvements

### ISSUE THREAD

**Issue by blu-IT** [jitsi/jitsi-meet#6046]
Hello,

I have some suggestions - that from my point of view - would **ease the use and raise acceptance** of jitsi-meet _(not only)_ for non techies ;-)

When clicking on the link to a conference, there should be

**1.** some kind of **"entry page"** where a user _can_ set his **name** and
**2.** **check devices** - microphone and/or webcam  - settings

This would be very nice, because now using jitsi-meet means "stumble" into the conference nearly without any pre-check for many non experienced users with jitsi.
Others see that there is a new member in the conference, but maybe the user ist still experiencing problems with access rights of browser settings for webcam and/or microphone.
Then the user **still has to find the settings menu** and **set there his name, choose a language, select the audio/video device...** This is anoying for the rest of the group....

And from a point of view regarding the **security** for a initiator/moderator of a videoconference it 

**3.** should be **mandatory to set a PIN** for the conference.

Thanks!

Regards

**Comment by l3d00m** [comment]
I like the idea of prompting to set a username, it happened for me that i had a lot of "Fellow Jitsers". It's hard to guess who's who when not using webcams, so I had to manually explain how to set the names there.

A mandatory PIN might be making it more complicated, but requiring it at least when setting custom room names makes sense to me, as those are usually easy to guess and to "zoom-bomb" 😛

**Comment by ndastur** [comment]
Please don't do this. I'm sorry @blu-IT but there is a really good API and it's really easy to build a UI that collects user information and populates the Jitsi instance with that information. Same goes for mandating a password. There is an exposed API and forcing such options would remove flexibilty and the SDK is not the place for it.

**Comment by blu-IT** [comment]
@ndastur Well, I can understand your concerns. Unfortunately I am not a coder to integrate such things myself and I am looking at that, as a lot of people who try jitsi for the first time now, as I am considering this tool to many people.
Maybe a "plugin"-option to easily activate/deactivate this feature would not break everything?

**Comment by cweiske** [comment]
Point 1 can be solved by enabling "requireDisplayName" in the config file, see https://github.com/jitsi/jitsi-meet/issues/4552

**Comment by blu-IT** [comment]
@cweiske Thanks for that hint, good to know!

**Comment by Echolon** [comment]
@blu-IT would you be so kind and rename the issue with a clear and proper issue so its much easier for us the keep track

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by l3d00m** [comment]
Your first suggestion is tracked in #2737 and will be implemented soon.

**Comment by pioneer** [comment]
Leaving this comment also here: the first suggestion I think could be also implemented on per-meeting base, not only on per-server base.
