### ISSUE TITLE
jitsi-meet stream to server

### ISSUE THREAD

**Issue by liu1083947028** [jitsi/jitsi-meet#605]
Scenario:
User A and User B is WEB RTC communication (audio + video) based. After the session is established, A will switch to the main screen to display the video itself A, B will be displayed as a thumbnail.
Before handover, the uplink & downlink data A and B are nearly 1Mbps, and after the handover, the uplink & downlink data B remains unchanged, the uplink data and downlink data A unchanged down to about 300Kbps.

problem:
1, either A or B, upload data, for uploading the video stream is how to deal with? Upload video streams simultaneously in two different resolutions, displayed by the other clients on demand? Or upload a complete resolution video, by the server side Resize handle?
2, after the session is established, audio and video streaming between servers and clients whether at the different ports transmission? By Tcpdump data captured throughout the session, between a client (browser) and server only one connection port is enabled.

**Comment by bgrozev** [comment]
> Scenario:
> User A and User B is WEB RTC communication (audio + video) based. After the session is established, A will switch to the main screen to display the video itself A, B will be displayed as a thumbnail.
> Before handover, the uplink & downlink data A and B are nearly 1Mbps, and after the handover, the uplink & downlink data B remains unchanged, the uplink data and downlink data A unchanged down to about 300Kbps.

This is a feature. :)
It should go back up if you click on B agaig.

> problem:
> 1, either A or B, upload data, for uploading the video stream is how to deal with? Upload video streams simultaneously in two different resolutions, displayed by the other clients on demand? Or upload a complete resolution video, by the server side Resize handle?

Clients send their video encoded with different settings (simulcast). Receivers signal to the videobridge which endpoint they have on their main screen, and receive the high quality stream for this endpoint, and lower quality for the ones seen in thumbnails.

> 2, after the session is established, audio and video streaming between servers and clients whether at the different ports transmission? By Tcpdump data captured throughout the session, between a client (browser) and server only one connection port is enabled.

A single UDP/TCP stream is used.

None of these is a problem, as far as I can see.

**Comment by liu1083947028** [comment]
I always see high quality stream in thumbnails and main screen.
Where I set up wrong?
Thanks.

![image](https://cloud.githubusercontent.com/assets/7359403/16439241/fde5e3b6-3de8-11e6-84f6-8a3942ea1f7d.png)
![image](https://cloud.githubusercontent.com/assets/7359403/16439287/78754ab8-3de9-11e6-92a0-4c5e77fab26d.png)

**Comment by liu1083947028** [comment]
How can i get the specified resolution stream?
Theanks

**Comment by tarlesurendra** [comment]
hello

video stream button now showing on my jits-meet please may i know what is the issue and how can i set video streaming on my server ubuntu 14?

Thank you

**Comment by bubomancer** [comment]
@liu1083947028 Did you solve how to get the specified resolution stream?  I would like to know--thanks!

**Comment by liu1083947028** [comment]
@bubomancer Sorry, I have no idea.
