### ISSUE TITLE
Mobile apps locked to sending 720p?

### ISSUE THREAD

**Issue by thieman** [jitsi/jitsi-meet#6055]
**Is your feature request related to a problem you are facing?**

We're using self-hosted Jitsi for an online board game group. We have an iPad set up on a tripod pointing down on the game board. Unfortunately, we can only get 720p output from the iPad, which makes some smaller text on the board too blurry to read.

As a workaround, we're currently streaming the iPad camera output to a Mac through QuickTime and then streaming the Mac's screen output through Jitsi. The Mac can output at around 1080p, so this gets us a much better picture on the stream. It's kludgy and a pain to set up, though.

**Describe the solution you'd like**

It'd be great if the iPad could emit higher quality video without having to do the QuickTime kludge. Its camera is certainly capable of more than 720p. And in our case at least, the bandwidth requirements should not be very high as the picture is static most of the time.

**Other questions**

I've seen a few places where Jitsi contributors have confirmed that the mobile apps are locked to 720p, but I couldn't find a rationale for it. Does anyone happen to know it? Is this something we could actually fix, or are there issues I'm not aware of?

**Comment by licaon-kter** [comment]
You did setup this: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L106 right?

**Comment by thieman** [comment]
I attempted to do the following:

1. Changed `resolution` to `1080`
2. Changed `constraints.video.height.max` to `1080`
3. Changed `constraints.video.height.ideal` to `1080`

I did all that, restarted my server, and I was still not seeing any iOS device go above 720p.

**Comment by sagz** [comment]
Wait why is this a wontfix now?

**Comment by licaon-kter** [comment]
Now I'm seeing this too I guess, i can't get more than 640x480 or 640x360. ;(

**Comment by Bergruebe** [comment]
Is there any update on this topic?

**Comment by saghul** [comment]
No, the apps still use 360 / 480p. The SDK does not have this limit though.

**Comment by Bergruebe** [comment]
Thank you for your fast answer! Then I need to use the mobil browser instead of the app...
