### ISSUE TITLE
record live meetings

### ISSUE THREAD

**Issue by oldchant** [jitsi/jitsi-meet#6057]
I need to record my live meeting with Jitsi,but it doesn't work. What should I do?

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5403

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
