### ISSUE TITLE
Grabacion de la sesion en Jitsi

### ISSUE THREAD

**Issue by inetcity** [jitsi/jitsi-meet#6059]
Es posible configurar la aplicación para que se realice una grabación local, en lugar de subirse a Dropbox ? 
Esto para evitar los continuos reportes que la grabación no esta disponible ya que todas las grabadoras están ocupadas

**Comment by luixxiul** [comment]
See here https://github.com/jitsi/jitsi-meet/issues/5403 and close this issue if you find a duplicate there. If you cannot find, please provide additional information.

Consulte aquí https://github.com/jitsi/jitsi-meet/issues/5403 y cierre este problema si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional.
