### ISSUE TITLE
jitsi-videobridge call out no voice

### ISSUE THREAD

**Issue by liu1083947028** [jitsi/jitsi-meet#607]
jitsi-videobridge call out no voice。

The versions are
jicofo_1.0-235-1_amd64
jigasi_1.0-99_amd64
jitsi-meet_1.0.909-1_all
jitsi-meet-prosody_1.0.909-1_all
jitsi-videobridge_704-1_amd64
prosody_0.9.1-1ubuntu0.1_amd64

need anyother config ?

**Comment by liu1083947028** [comment]
- 

- 

-

**Comment by liu1083947028** [comment]
This is jigasi log.
![image](https://cloud.githubusercontent.com/assets/7359403/14553071/254ede8e-0316-11e6-8c50-668528f7b360.png)

SIP is connected.
![image](https://cloud.githubusercontent.com/assets/7359403/14553108/7317b37a-0316-11e6-88cf-2f9b045d7893.png)

**Comment by damencho** [comment]
Check https://github.com/jitsi/jigasi/issues/29

**Comment by damencho** [comment]
And please use the mailinglist before opening issues.
