### ISSUE TITLE
Conference error

### ISSUE THREAD

**Issue by RomaDomor** [jitsi/jitsi-meet#6074]
## Description
When I'm joining conference, I get JS error from JitsiMeetJS.js (attached screenshot from console)
![error](https://user-images.githubusercontent.com/59030601/79430401-8e44fe00-7fd1-11ea-9537-1a4eabfef19b.png)

## Current behavior
Getting error from JS after joining/creating conference. GUI buttons (enable webcam/microphone) aren't working(I'm getting same error each time I click them)

## Expected Behavior
No error when joining/creating conference

## Steps to reproduce
Just create new conference and check your browser console.

# Environment details
Ubuntu 18.04.3 (LTS) x64
Digital Ocean Droplet(2 Cores/4 GB MEM)
Google Chrome(Mac OS)

**Comment by l3d00m** [comment]
Hello @RomaDomor, is this issue still occuring for you with the newest version?
