### ISSUE TITLE
jitsi-meet call recording

### ISSUE THREAD

**Issue by jhorstmann-oroverde** [jitsi/jitsi-meet#6075]
Hello,
I need some support regarding jitsi-meet conference recording:

I'd like to record jitsi-conference-calls and safe the file in my dropbox-account which is already connected, but trying it out a couple of times, sometimes I get the error message that all recording resources are occupied and recording is not possible. But in a following trial just a few seconds or minutes later recording seems to work well. 

What is this problem due to? my computer? or dropbox / jitsi / gitHub resources exceeded by too many recording going on at the same time? 

We need a reliable recording option for our conference calls, as more than 15 persons meet for the conference, but the recording will be needed to spread the conversation among even more collegues in several countries and locations. What support can you offer, or what solution do you suggest?

Thanks in Advance for your kind collaboration!

best regards,

Johannes

**Comment by lhpitn** [comment]
It would be nice to support nextcloud and all other webdav systems to ;)

**Comment by jhorstmann-oroverde** [comment]
> It would be nice to support nextcloud and all other webdav systems to ;)

sure! good idea! we are also using nextCloud, not Dropbox. it would be great to save recordings directly in our nextcloud

**Comment by blu-IT** [comment]
I'd like to see that feature too for **Nextcloud**!

Quite unusual for an open-source product to support closed-sourced products (like DropBox or Google Calendar), instead of something like **Nextcloud** and **CalDAV** that is open-source ;-)

**Comment by luixxiul** [comment]
Here are tickets related with Nextcloud, CalDAV and owncloud integration:

- https://github.com/jitsi/jitsi-meet/issues/5800 - Nextcloud + jitsi
- https://github.com/jitsi/jitsi-meet/issues/4719 - [FEATURE REQUEST] Integration with CalDav for Jitsi meetings
- https://github.com/jitsi/jitsi-meet/issues/5412 WebDAV Integration for images and other files shared in Jitsi conversations

**Comment by rosa2** [comment]
Yes, please, support open standards

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
