### ISSUE TITLE
jitsi-meet recording with dropbox

### ISSUE THREAD

**Issue by jhorstmann-oroverde** [jitsi/jitsi-meet#6076]
Hello,
I need some support regarding jitsi-meet conference recording:

I'd like to record jitsi-conference-calls and safe the file in my dropbox-account which is already connected, but trying it out a couple of times, sometimes I get the error message that all recording resources are occupied and recording is not possible. But in a following trial just a few seconds or minutes later recording seems to work well. 

What is this problem due to? my computer? or dropbox / jitsi / gitHub resources exceeded by too many recording going on at the same time? 

We need a reliable recording option for our conference calls, as more than 15 persons meet for the conference, but the recording will be needed to spread the conversation among even more collegues in several countries and locations. What support can you offer, or what solution do you suggest?

Thanks in Advance for your kind collaboration!

best regards,

**Comment by luixxiul** [comment]
You have created the same ticket already here: https://github.com/jitsi/jitsi-meet/issues/6075

Also I would recommend you to check the pinned issues on https://github.com/jitsi/jitsi-meet/issues/5403, which tracks tickets related with recording.
