### ISSUE TITLE
All recorders are currently busy ...

### ISSUE THREAD

**Issue by slstss** [jitsi/jitsi-meet#6078]
Hi, Any ideas when recording resources will be freed up? TIA

**Comment by luixxiul** [comment]
I think you would want to follow this ticket https://github.com/jitsi/jitsi-meet/issues/5403 and close this one in favor of that. The issue has been well recognized by the team. See: https://github.com/jitsi/jitsi-meet/issues/5403#event-3234249785 and the list of tickets linked to that.

**Comment by slstss** [comment]
Thanks … will do.

Tim Fransen
Technical Tutor – Web Publishing and Design | Technical Support Services | London South Bank University | 103 Borough Road, London, SE1 0AA
t: +44 (0)20 7815 6775 | e: timfransen@lsbu.ac.uk<mailto:timfransen@lsbu.ac.uk>

[signature_613414467]<http://www.lsbu.ac.uk/>

Become what you want to be
lsbu.ac.uk<http://www.lsbu.ac.uk> | Twitter<https://twitter.com/lsbu> | Facebook<https://www.facebook.com/londonsouthbankuni/> | Instagram<https://www.instagram.com/lsbu/>

**Comment by slstss** [comment]
Thanks … will do.
