### ISSUE TITLE
iOS, the quit button does not work

### ISSUE THREAD

**Issue by micha06de** [jitsi/jitsi-meet#6079]
On iOS (last version on the old iPhone SE) the red quit button does not work.

When you press the button nothing happens, to leave the session you have to finish the task of the app.  

Addendum: The issue seems to be related to this
https://github.com/jitsi/jitsi-meet/issues/5210

**Comment by saghul** [comment]
Were you using meeting with such name? aaa/bbb

**Comment by saghul** [comment]
No follow-up, closing.
