### ISSUE TITLE
quick install - black screen

### ISSUE THREAD

**Issue by potapovdima** [jitsi/jitsi-meet#608]
I try jitsi-meeting on digitalocean. 
After quick install I have black screen.
screen: http://prntscr.com/askssy
help please!

**Comment by LukeStephen** [comment]
Are you using your own digital cert or the self signed cert option?

I have found using your own cert allows it to Just work right from the quick install behind NAT

**Comment by bhatvv** [comment]
Need to set this if JVB is behind the NAT ..https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md#orgjitsivideobridgenat_harvester_local_address

**Comment by potapovdima** [comment]
htx for answers,
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#running-behind-nat

I'm noob in JVB,))

 I have added /etc/jitsi/videobridge/sip-communicator.properties
3 lines
org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=127.0.0.1
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=139.XXX.XXX.249
Result  black screen (((

**Comment by LukeStephen** [comment]
@bhatvv @potapovdima what is the exact folder path to this file: sip-communicator.properties?

**Comment by bgrozev** [comment]
> I'm noob in JVB,))
> 
> I have added /etc/jitsi/videobridge/sip-communicator.properties
> 3 lines
> org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
> org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=127.0.0.1
> org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=139.XXX.XXX.249

Are you sure 127.0.0.1 is the address your NAT translates to? 

> @bhatvv @potapovdima what is the exact folder path to this file: sip-communicator.properties?

It is "/etc/jitsi/videobridge/sip-communicator.properties"

**Comment by potapovdima** [comment]
where I can see NAT_HARVESTER_LOCAL_ADDRESS and  NAT_HARVESTER_PUBLIC_ADDRESS addresses ?

**Comment by potapovdima** [comment]
help please!

**Comment by kas70** [comment]
I'm also getting a black screen. Logs tell me:
```
JVB 2016-04-27 18:29:37.027 SCHWERWIEGEND: [27] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Verbindungsaufbau abgelehnt, host:localhost, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Verbindungsaufbau abgelehnt
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)
	... 12 more
```

**Comment by derNarr** [comment]
Using Firefox I got a black screen as well. With Chromium it works fine. Safari is not working as well -- as far as I can say.

I am only mentioning that in order to rule out this possibility.

**Comment by scrolls-mckenzie** [comment]
I am having similar issues since an update 1 week ago. The system was working fine before. I am using the nightly updates and have read everything i can about the "Black Screen" fault. It appears that the JVB connection is failing to connect the 2 parties. 

I have tried firefox and chrome with no success. If i add the lines to the sip-communicator.properties i instantly get a JVB failure message in the rooms. Without any lines in the properties file, i get no warnings but no connection either. 

Only thing that the jvb.log shows is an INFO:failed to connect the clients. 

Has anyone had any success without having to do a clean install cause that it a pretty bad solution

**Comment by nessor** [comment]
I've also trouble with this error. It's strange that the connection work fine when I connect 2 clients which are in the same network. At the moment when these two clients, logged in in different networks, connect, the "mysterious-black-error" appears.

**Comment by Liferow** [comment]
Tried installing Jitsi Meet on Debian Jessie yesterday. Installation went without errors (fresh Debian install + fresh Jitsi Meet install using quick guide), but I'm having the same problem other people mentioned. 

After creating conference room and allowing browser to access mic/cam I get black screen and most of interface is not functioning (can't set nickname, cam/mic or any other option).

**Comment by williammahecha** [comment]
Greetings. I have installed Jitsi Meet following the instructions in https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md, in Debian 8 Jessie - default jre 7  and in Ubuntu 14.04 - jre8 oracle. Ubuntu 14.04 has firewall disabled by default.

When I create a room using Chrome or Firefox, I get a black screen, the camera, microphone, hangout buttons don´t work. I can't even watch my own video. 
When I click the invite button, it always says creating room. There could be something missing in the guide or in the package.

**Comment by damencho** [comment]
I just created two vms on digitalocean one with ubuntu 14.04 and one with debian8 installing there using the quick install instructions produced a working deployment (Just selected self-signed certs and filled a dummy domain, which later I filled in my /etc/hosts, in real world you will add an A and AAAA dns records for that dns).
It must be some misconfiguration, if you do not see your own video start checking browser logs for errors, then check the jicofo logs for errors.

**Comment by williammahecha** [comment]
Thanks for your help. I configured a dummy domain and updated hosts file, but I still get this errors.
![jitsi browser errors](https://cloud.githubusercontent.com/assets/7416133/20360003/23927310-ac00-11e6-843a-6453af6107a4.PNG)
![jicofolog](https://cloud.githubusercontent.com/assets/7416133/20360042/49ae7a08-ac00-11e6-884d-214dd22402cd.png)

**Comment by damencho** [comment]
Did you set hangout in /etc/hosts on the machine where chrome is running?
Chrome is not resolving hangout domain.

**Comment by williammahecha** [comment]
Thank you very much, Damencho. I really appreciate your quick response, and your goodwill to help me and everybody to implement this project.
I was using the FQDN "jitsiserver.com", but I don't have a domain server. So I changed it for the unqualified domain name "hangout" and it worked from the vm and the host OS.
![hostname](https://cloud.githubusercontent.com/assets/7416133/20393093/914ba95a-aca8-11e6-9209-44df12fd8f0a.PNG)

These are my hosts and hostname files
![hostname 2](https://cloud.githubusercontent.com/assets/7416133/20393128/b367968e-aca8-11e6-9d02-547bf9161f91.PNG)

**Comment by damencho** [comment]
Sorry I didn't quite get it. So when you install jitsi-meet and it asks for domain you entered hangout. There is nothing more you need to do on the linux machine, the domain there is just virtual and do not need to be resolved.
On the other hand on the client machine where chrome is running, that domain needs to be resolved and pointed to the linux machine. The link https://hangouot/http-bind should be working. If you had setup /etc/hosts on your machine and chrome is not resolving it, maybe you din't set it correctly, you need to restart chrome or not sure how to debug this situation. That is the problem from the chrome screenshots, you need to make sure chrome resolves that.

**Comment by williammahecha** [comment]
It is already working, but now I understand the concepts. In the installation i set "hangout" as the domain, and it is virtual. In the hosts file of the computer where i was connecting, I had to resolve that virtual domain name, matching it with the IP of the jitsi videobridge server. 
Thank you, again.

**Comment by damencho** [comment]
I will close this issue, as different people were posting here different configuration problems. 
We prefer discussions and questions to be sent to dev/users mailinglist instead of opening new issues.
