### ISSUE TITLE
error en la grabacion 

### ISSUE THREAD

**Issue by martin-0509** [jitsi/jitsi-meet#6091]
quisiera saber el porque aun no me deja usar la grabacion

**Comment by luixxiul** [comment]
Consulte aquí https://github.com/jitsi/jitsi-meet/issues/5403 y cierre este problema si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabacion
