### ISSUE TITLE
How to record a meet in hard disk? 

### ISSUE THREAD

**Issue by midebort** [jitsi/jitsi-meet#6092]
how to record a meet in hard disk?  
In dropbox it is not possible
Pueden responder en español por favor?
Como grabar una meet en el disco duro de la PC? por que varias veces intenté grabar en dropbox y las grabadoras están todas ocupadas...

**Comment by saghul** [comment]
No es posible actualmente.

**Comment by midebort** [comment]
Muchas gracias saghul.
Intenté iniciar transmisión en youtube y da error reiteradamente.
Se puede solucionar esto?

**Comment by midebort** [comment]
I tried to begin transmission in youtube and gives error repeatedly.  
can this be solved?
