### ISSUE TITLE
[Firefox] _addOrRemoveRemoteStream Error when camera is on

### ISSUE THREAD

**Issue by HelloWorldUser123** [jitsi/jitsi-meet#6093]
## Description

When I use Firefox ESR 68.5 I get following Error when I turn on the camera if one or more persons are within the room

Edit: when I completely turn off simulcast it seems to work

[modules/xmpp/JingleSessionPC.js] <_addOrRemoveRemoteStream/</<>:  addRemoteStream failed: DOMException: "Failed to parse SDP: SDP Parse Error on line 14:  Warning: Invalid maxplaybackrate: 0 specified for fmtp attribute
SDP Parse Error on line 111:  Warning: Unrecognized attribute (ssrc-group) 
SDP Parse Error on line 80: simulcast attribute has a direction that is inconsistent with the direction of this media section.

## Steps to reproduce
---
Two participants in the room. The second one turns on the video

# Environment details
---
https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%20ESR%2C%20Portable%20Edition%2068.5.0/

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
Thanks for the report, I am looking into it.

**Comment by jallamsetty1** [comment]
This should be fixed in the next release of meet.jit.si

**Comment by jallamsetty1** [comment]
@HelloWorldUser123 Can you please check if this issue is resolved now ? We made a new release with the fix last night, thanks !

**Comment by HelloWorldUser123** [comment]
@jallamsetty1 Thanks for the fix. It seems to work on Firefox.

I see the same behavior on iOS Safari, but currently I don't have error logs for it. Could this be that case?

**Comment by jallamsetty1** [comment]
Thank you for verifying the fix. 
iOS Safari will be a different issue. I tried to reproduce the iOS Safari issue when you first mentioned it on the other thread but I didn't see any issues with my iPhone 8 running iOS 13.4 in a 3 way call. 
Please open a new bug with logs, I will be closing this one.

**Comment by HelloWorldUser123** [comment]
@jallamsetty1 Thanks, I have created a new issue with the logs from safari:

https://github.com/jitsi/jitsi-meet/issues/6176
