### ISSUE TITLE
Problema con Drogbox 

### ISSUE THREAD

**Issue by felifonse** [jitsi/jitsi-meet#6096]
Hola, buen día
 Me gustaría saber por favor por que no puedo grabar mi video conferencia en jitsi meet no me permite guardarla en drogbox me sale un error

![Captura de pantalla 2020-04-16 a la(s) 8 58 18 a  m](https://user-images.githubusercontent.com/63797259/79465093-8892ec80-7fc0-11ea-8ea7-4ba832fe1772.png)

**Comment by luixxiul** [comment]
Consulte aquí https://github.com/jitsi/jitsi-meet/issues/5403 y cierre este problema si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabacion

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
