### ISSUE TITLE
broadcast live Jitsi meetings on youtube

### ISSUE THREAD

**Issue by lucianodraetta** [jitsi/jitsi-meet#6097]
Good Morning
Can you help me?
Why am I not able to broadcast live Jitsi meetings on youtube? The message is: "all broadcasts are currently busy"
Is it possible to 
Thank you very much

**Comment by luixxiul** [comment]
The issue is being investigated

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
