### ISSUE TITLE
Integration of e2ee

### ISSUE THREAD

**Issue by beatstick** [jitsi/jitsi-meet#6099]
I could not get the new e2ee encryption to work using the electron app. 
Is this already integrated into the electron client? Or do I need to use the development version of chromium to test it? (I could not get it to work with electron + chromium (regular version).
I am also not sure how to enable e2ee in the first place.
Is e2ee enabled by attaching a line to the url like this(?): jitsi.meet/yourroomname#e2eekey=yourpassword
I know this is all still in the early stages of development but I really would like to test it.

**Comment by saghul** [comment]
E2EE is now available on meet.jit.si with a button the 3 dots menu.

This option will only show up when your browser supports the capability.

The URL parameter is still supported, but you can use the new adíalos for extra convenience.

**Comment by beatstick** [comment]
> 
> 
> You need to be running Chrome Canary with the experimental web platform flag enabled, so no chance it works on Electron.

Thanks for the feedback. I've got e2ee working on my server + chromium nightly build. Yeah! But most users (including me) are running jitsi-meet on an app because it just performs a lot better compared to using a browser. 
Will it never work on electron? I thought this was based on google chrome? Is there no nightly build for electron? 
Also aren't the smartphone apps based on electron as well? Does this mean there will be no e2ee for those too in the forseeable future?
