### ISSUE TITLE
Todas las grabadoras ocupadas

### ISSUE THREAD

**Issue by danielgarofano** [jitsi/jitsi-meet#6103]
No puedo grabar, casi siempre me sale que las grabadoras están ocupadas, no puedo empezar una video conferencia y quedarme sin poder grabarla

**Comment by luixxiul** [comment]
Vea aquí #5403 y cierre este ticket si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabar
