### ISSUE TITLE
Documentation: Installing JDK and JRE is Duplicative

### ISSUE THREAD

**Issue by jlpoolen** [jitsi/jitsi-meet#6104]
[The Server Installation for Jitsi Meet](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#user-content-server-installation-for-jitsi-meet) has several steps.  

Step [Install Jitsi Videobridge](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#user-content-install-jitsi-videobridge) recommends installing a Java runtime environment ("JRE").

Then a following step[ Install Jitsi Conference Focus (jicofo) ](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#user-content-install-jitsi-conference-focus-jicofo)recommend installing the Java Development Kit ("JDK").

The Open JDK has a run time environment, so installing a JRE and then the JDK make the step of installing the JRE unnecessary and duplicative.  The instructions presumably are for one server instance and therefore the earliest step ought to simply specify that the JDK be installed.  Or, if the instructions are to be for several servers, then they should so indicate and distinguish that a JRE is only needed for the Videobridge whereas the JDK is required for the jicofo.

**Comment by Echolon** [comment]
@jlpoolen can you imagine create a pull request for this?

**Comment by damencho** [comment]
The quick install guide is about installing binary debian packages that require jre. Manual install is compiling from sources so you need jdk.

**Comment by damencho** [comment]
Well yeah the manual install is something we do not update as said in the Notice in the beginning... You are right on one place its jdk the other is jre in the same doc, I saw it the second time I took a look. PRs are welcome.
