### ISSUE TITLE
no puedo grabar la sesion y guardarla en dropbox

### ISSUE THREAD

**Issue by MARISAEPL** [jitsi/jitsi-meet#6105]

**Comment by luixxiul** [comment]
Vea aquí #5403 y cierre este ticket si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabar
