### ISSUE TITLE
duvida sobre gravacao

### ISSUE THREAD

**Issue by KarinaSandolin** [jitsi/jitsi-meet#6106]
POr favor, gostaria de gravar a aula, mas aparece uma mensagem que não é possivel por falta de espaço. Tem como eu saber, antes de iniciar a reunião, se vou conseguir gravar ou nao?
obrigada

**Comment by luixxiul** [comment]
Vea aquí #5403 y cierre este ticket si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabar
