### ISSUE TITLE
Jitsi Meet: Pressing Ctrl-T mutes me

### ISSUE THREAD

**Issue by RalfJung** [jitsi/jitsi-meet#611]
When I am in a conversation and use other applications besides the browser, and other tabs in the browser besides Jitsi, it frequently happens that I get muted. I was unable to reproduce this so far. This is rather disturbing, since I do not even notice that I got muted -- and if I was not in the middle of a sentence, the other people in the conversation do not notice, either.

My impression is that there is some kind of auto-mute mechanism in Jitsi, that somehow tries to detect... well, I don't know, really. But I had no such trouble when using other WebRTC conversation sites, I don't see any benefit from this auto-muting, and having to frequently manually un-mute myself is very disrupting.

I am using Firefox 45.0.2.

**Comment by damencho** [comment]
Could you please discuss problem on the mailinglist before opening new issues. 
There is no such auto-mute, there is some stuff we are working on, but it only concerns shared-video. 
Can it be that you are pressing m button while in the conference, which mutes you? Or the moderator of the conference mutes you for some reason?

**Comment by RalfJung** [comment]
> Could you please discuss problem on the mailinglist before opening new issues. 

I wasn't aware there is a list, sorry. There was no CONTRIBUTING.md with any kind of instructions, so I figured the bugtracker is the obvious way to go :)

> Can it be that you are pressing m button while in the conference, which mutes you?

I don't think so -- I was in different tabs in my browser.

> Or the moderator of the conference mutes you for some reason?

I did not know there is anything like a moderator. There were was two people (me and a friend) both browsing to the same meet.jit.si URL, and talking, and be being randomly muted. I'm sorry this is rather vague, I just don't know how to reproduce this.

**Comment by bickelj** [comment]
Try reproducing with the T key.

Any time I open a new tab in Firefox, I get muted as well, it is due to pressing T.

It is a push-to-talk feature, allowing you to hold T when talking and be muted afterwards. In Chromium-based browsers, the issue doesn't seem to be there for Ctrl-T, but in Firefox it seems to be there.

**Comment by RalfJung** [comment]
It's definitely the Push-to-talk thing. I could now reproduce the muting by pressing Ctrl-T while in the Jitsi tab, which I do a lot when I want to look up something else.
