### ISSUE TITLE
Record meeting

### ISSUE THREAD

**Issue by tomisilveira** [jitsi/jitsi-meet#6112]
Can't record meeting

**Comment by lucialvarez** [comment]
no se puede grabar la reunion

**Comment by luixxiul** [comment]
Vea aquí #5403 y cierre este ticket si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.

https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabar

Search before creating a new issue, please.
