### ISSUE TITLE
hola. el problema que se me presenta es el acceso a mi camara

### ISSUE THREAD

**Issue by crdiaz41** [jitsi/jitsi-meet#6114]
Hola como esta? la verdad aparece un cartel naranja en el angulo inferior advirtiendo que no accede a la camara. que me asegure que no lo esta utilizando otro aplicativo,

Puede indicarme como solucionarlo?
Gracias

**Comment by luixxiul** [comment]
Vea aquí #5425 y cierre este ticket si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.
