### ISSUE TITLE
Specs required on Ubuntu server per 10 / 100 / 1000 simultaneous connections? 

### ISSUE THREAD

**Issue by inglesuniversal** [jitsi/jitsi-meet#6115]
How can I figure out, how to set up my server, depending on the number of possible and sustainable connections?

How many users can be connected at the same time?

What is the RECORD or TOP number of online users ever tested with jitsi-meet ?

Thanks

**Comment by luixxiul** [comment]
````
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.
````

I think you should ask those questions at https://community.jitsi.org
