### ISSUE TITLE
Arbitrary data transfer over API

### ISSUE THREAD

**Issue by repomaa** [jitsi/jitsi-meet#6117]
I‘m looking into embedding a Jitsi conference into an online card game.

I’d love to be able to use the api to send and receive arbitrary messages (that won’t show up in the chat) to connected peers so that I can synchronize game state directly over the webrtc connection established by Jitsi.

It seems redundant to add a websocket Server for this given that Jitsi already maintains a connection between the peers.

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
