### ISSUE TITLE
enregistrement ?

### ISSUE THREAD

**Issue by ArmandFlorea** [jitsi/jitsi-meet#6124]
Bonjour,

Je souhaite enregistrer nos visioconférences ( trois par jour). 
C'est possible ? Comment faire sil vous plait ? 

merci d'avance 

Armand Florea

**Comment by freechelmi** [comment]
English please

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
