### ISSUE TITLE
Installing jitsi-meet via ansible not possible

### ISSUE THREAD

**Issue by paulkitt** [jitsi/jitsi-meet#6130]
## Description
---
I am writing a ansible script automating the jitsi installation procedure and can only enter the hostname and cert selection after the successful install with `deb_conf`.

## Current behavior
---
Currently when installing jitsi with apt you have to configure the pkt while installing. When not entering the hostname and cert selection during the deb_conf procedure the installation is falling.

## Expected Behavior
---
A check if this values are needed would be great because because before installing jitsi-meet the FQDN is already set in `/etc/hostname` and certs are already generated in `/etc/letsencrypt` in my installation procedure.

## Possible Solution
---
* Allow the installation to be configured after a successful install with `dpkg-reconfigure` 
* check if the needed selections already set in `/etc/hostname` or use default values

## Steps to reproduce
`DEBIAN_FRONTEND=noninteractive apt-get -y install jitsi-meet` will produce:
```
....
   The given hostname does not exist in the config
dpkg: error processing package jitsi-meet-prosody (--configure):
 installed jitsi-meet-prosody package post-installation script subprocess returned error exit status 1
Setting up coturn (4.5.0.7-1ubuntu2.18.04.1) ...
Adding group `turnserver' (GID 117) ...
Done.
Adding system user `turnserver' (UID 112) ...
Adding new user `turnserver' (UID 112) with group `turnserver' ...
Not creating home directory `/'.
dpkg: dependency problems prevent configuration of jitsi-meet:
 jitsi-meet depends on jitsi-meet-prosody (= 1.0.3992-1); however:
  Package jitsi-meet-prosody is not configured yet.

dpkg: error processing package jitsi-meet (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of jitsi-meet-turnserver:
 jitsi-meet-turnserver depends on jitsi-meet-prosody; however:
  Package jitsi-meet-prosody is not configured yet.

dpkg: error processing package jitsi-meet-turnserver (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
 Processing triggers for systemd (237-3ubuntu10.39) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ca-certificates (20180409) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Processing triggers for ufw (0.36-0ubuntu0.18.04.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 jitsi-meet-prosody
 jitsi-meet
 jitsi-meet-turnserver
E: Sub-process /usr/bin/dpkg returned an error code (1)                                                         
                            
```
---

# Environment details
---
* Ubuntu 18.04

**Comment by derekmarcotte** [comment]
FWIW, I wasn't using ansible, but was able to script the configuration using something like:

```shell
sudo debconf-set-selections <<EOF
jitsi-meet-web-config   jitsi-meet/jvb-hostname string  JITSIHOSTNAME
jitsi-meet-prosody      jitsi-meet-prosody/jvb-hostname string  JITSIHOSTNAME
jicofo  jitsi-videobridge/jvb-hostname  string  JITSIHOSTNAME
jitsi-meet-prosody      jitsi-videobridge/jvb-hostname  string  JITSIHOSTNAME
jitsi-meet-web-config   jitsi-videobridge/jvb-hostname  string  JITSIHOSTNAME
jitsi-videobridge2      jitsi-videobridge/jvb-hostname  string  JITSIHOSTNAME
jitsi-meet-web-config   jitsi-meet/cert-choice  select  Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)
EOF
#jitsi-meet-web-config  jitsi-meet/cert-path-key        string  /etc/ssl/JITSIHOSTNAME.key
#jitsi-meet-web-config  jitsi-meet/cert-path-crt        string  /etc/ssl/JITSIHOSTNAME.crt
#jitsi-meet-web-config  jitsi-meet/cert-choice  select  I want to use my own certificate
```
before the `apt-get -y install jitsi-meet`.

**Comment by paulkitt** [comment]
Great thank you for that work around. This is working also great in Ansible.

When installing with debconf-set-selections preconfig in my installation no config files are generated.
Currently I am missing the nginx config and `/etc/jitsi/meet/fqdn-config.js`. Do you deploy this config files by your self?

**Comment by derekmarcotte** [comment]
I didn't get `/etc/jitsi/meet/fqdn-config.js`, but it seems like my nginx config was installed as part of running the letsencrypt script, as far as I can tell.

This is my first foray into jisti, so I'm definitely not a config expert.  I have a second "configure jitsi" step beyond "install jitsi", fwiw.

**Comment by derekmarcotte** [comment]
PS - things were weirdly broken on the installation when the debconf-set-selections input was space separated.  It really does need tabs for the fields.

**Comment by tderflinger** [comment]
I created an Ansible installation script that worked on my Ubuntu 18 machine: https://github.com/tderflinger/jitsi-deployment
