### ISSUE TITLE
necesito grabar la videoconferencia de Meet jitsi y me dicen que la grabadora está ocupada 

### ISSUE THREAD

**Issue by Burnetin** [jitsi/jitsi-meet#6133]
please pueden habilitar la grabación de esta videoconferencia?
https://meet.jit.si/grupodecapacidades
muchas gracias

**Comment by luixxiul** [comment]
#5403 https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+grabar
