### ISSUE TITLE
Enable REST api for stats make conference crash

### ISSUE THREAD

**Issue by solick** [jitsi/jitsi-meet#6134]
## Description
Have a running Jitsi Meet hosted on own root server. jisti-meet version 2.0.4416-1
When enabling rest api for stats, conferences are not working. First person can enter room but when entering second person, both are kicked from the server with error message and option to reconnect.

## Steps to reproduce
* have a running Jitsi-meet
* enable rest in Videobridge config: 
    #JVB_OPTS="--apis=rest"
* enable rest in sip-communicator.properties
   org.jitsi.videobridge.rest.private.jetty.port=8080
   org.jitsi.videobridge.ENABLE_STATISTICS=true
   org.jitsi.videobridge.STATISTICS_TRANSPORT=colibri
* restart jitsi-videobridge and try to have a conference.

# Environment details
---
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

nothing else is running on this server.

**Comment by frittentheke** [comment]
@solick  I can config this - just wanted to enable the stats for the prometheus-jitsi-meet-exporter (https://github.com/systemli/prometheus-jitsi-meet-exporter/) to scrape and it just keeps crashing.

**Comment by solick** [comment]
@frittentheke did you find any solution yet? Really strange that there is no feedback on this bug.

**Comment by frittentheke** [comment]
> @frittentheke did you find any solution yet? Really strange that there is no feedback on this bug.

No. I just observed the same issue as the OP.
