### ISSUE TITLE
UX - Preselect monitor in screen sharing dialog when only one is available

### ISSUE THREAD

**Issue by l3d00m** [jitsi/jitsi-meet#6136]
**Is your feature request related to a problem you are facing?**
I explained Jitsi in Chrome to some non-technical users and this is one thing that confused them: If you have only one monitor and open the screen sharing dialog, it is required to click once on the single monitor, then again on the "Share" button.  Most tried to just click on "share" directly, but it's greyed out unless you select the only choice (besides single window sharing ofc).

**Describe the solution you'd like**
If only one monitor is available to select, preselect it so the share button isn't greyed out. I see no obvious disadvantages to that.

**Describe alternatives you've considered**
I don't see any good alternatives.

Btw: I'm astonished how good the UX feels otherwise, most of them were able to use Jitsi without any real struggles, which does not happen in many applications.

**Comment by jallamsetty1** [comment]
Hey there, thank you for the kind words about our UX. 
We do not have any control over the screen sharing dialog, this is how chrome has designed it and the application gets the callback once the selection has been made.

**Comment by l3d00m** [comment]
That explains why it looks so different in firefox... Thanks for the quick reply and the good product :)
