### ISSUE TITLE
Need to update the Kickout term and Kickout message

### ISSUE THREAD

**Issue by benzntech** [jitsi/jitsi-meet#6139]
When I removed someone from the meeting, it showed him a notification saying: you have been Kicked Out of the meeting!  (Not a professional approach)

Can we remove this message and update with professional approach.

**Comment by damencho** [comment]
What is your suggestion?

**Comment by l3d00m** [comment]
I had to smile when I saw the message for the first time, but I agree that it may sound aggressive in a more professional environment, where you not used to such messages. I would propose something like: "You were removed from the meeting" or "\<Name> removed you from the meeting". Both sound more neutral (but more boring too)

**Comment by bensonkb** [comment]
> What is your suggestion? @damencho 

I would like to go with @l3d00m Suggestion.  

> I would propose something like: "You were removed from the meeting" or "<Name> removed you from the meeting".

**Comment by saghul** [comment]
No plans to change this.

**Comment by Gaurav-CareMonitor** [comment]
Any updates on this?
