### ISSUE TITLE
Screen Sharing, it creates "mirroring"

### ISSUE THREAD

**Issue by bensonkb** [jitsi/jitsi-meet#6140]
As host, when I share the entire screen, it creates "mirroring", which is annoying

**Comment by damencho** [comment]
Yep, you are not supposed to share your current conference as people are already seeing the conference.
And this is the effect of putting in front of a mirror, there is nothing you can do for a mirror showing the mirror, showing the mirror ...

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

**Comment by bensonkb** [comment]
Is there any possibility of avoiding the conference screen. Which is available in zoom and other conference application @damencho
