### ISSUE TITLE
gravação 

### ISSUE THREAD

**Issue by CMPR646** [jitsi/jitsi-meet#6142]
Esta exibindo mensagem que os gravadores estão ocupados.

Não posso iniciar uma reunião sem a gravação

**Comment by luixxiul** [comment]
Por favor, tente o Firefox e deixe-me saber se funciona ou não. obrigado

**Comment by CMPR646** [comment]
Testei no firefox mas tbém exibe a mensagem que os servidores estao ocupados

**Comment by CMPR646** [comment]
Bom Dia!!! 

                    Testei  o firefox e também esta exibindo que os
gravadores estão ocupados. 

Sem Mais

---
      JANIO DIONISIO CORRADI 

DIRETOR DE INFORMATICA E RECURSOS HUMANOS 

CÂMARA MUNICIPAL DE PORTO REAL 

TEL: (24) 3353-2600 RAMAL 210       

INFORMATICA@CMPORTOREAL.RJ.GOV.BR 

Em 17/04/2020 11:57, Suguru Hirahara escreveu:

> Por favor, tente o Firefox e deixe-me saber se funciona ou não. obrigado 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/jitsi/jitsi-meet/issues/6142#issuecomment-615292029
[2]

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5403
