### ISSUE TITLE
Conferencia 2

### ISSUE THREAD

**Issue by Carlos-Conferencias** [jitsi/jitsi-meet#6143]

**Comment by luixxiul** [comment]
@saghul

**Comment by Carlos-Conferencias** [comment]
Psicólogo
Mtr. Sistemas Integrados de Gestión
Especialista en Higiene y Seguridad Industrial
Teléfono 301 3704063


*FELICIDAD DEJANDO HUELLA*

**Comment by l3d00m** [comment]
Hi,
Please detail your issues so it's clearer what the problem is. If you still have problems, feel free to reopen this.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
