### ISSUE TITLE
Add jitsi-meet to the official debian repo instead of using an external repo

### ISSUE THREAD

**Issue by herbsmn** [jitsi/jitsi-meet#6145]
Adding jitsi to the official debian repositories, instead of using an external repo, would increase end user's ability to trust the software. Debian is widely trusted by the free software community and jitsi-meet would benefit from the robust testing that they do before adding packages into their official repos.

This would also ease the installation process of jitsi-meet for novice users.

An ITP (Intent To Package) was sent in 2014 but it doesn't seem like it was ever followed up. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760485

**Comment by damencho** [comment]
In the past we had tried pushing Jitsi Desktop and it was a huge project, it took almost 6 months of work. And that was for one project, now we need that for 3 projects so I don't see that would happen with even more dependencies. We do not have the resources to do any of that work for the moment. If someone wants to dedicate so much time for doing that we may help with some guidance.

Please when you have questions or problems use the community forum before opening new issues.
