### ISSUE TITLE
JITSI

### ISSUE THREAD

**Issue by Scharafeddin** [jitsi/jitsi-meet#6146]
I WANT TO RECORD A CONFERENCE, WHY IT DOESNT WORK??

**Comment by luixxiul** [comment]
JUST FOLLOW #5403

**Comment by l3d00m** [comment]
Did you even try to search for existing issues @Scharafeddin? At least try to detail the issues you're having.You didn't even pay anything for this, so get some manners. (I'm not affliated with Jitsi in any form, I just don't understand how ppl can be so rude)

**Comment by l3d00m** [comment]
Hi,
If you have an issue with recording, please report it in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
