### ISSUE TITLE
Tools for language facilitation during conferences

### ISSUE THREAD

**Issue by ostasevych** [jitsi/jitsi-meet#6151]
**Is your feature request related to a problem you are facing?**
In case of multilanguage video/audio conference some participants need synchronous interpretation, which may be provided by a language facilitator(s)/appointed person(s), which will interpret the conversation in different language(s), as well as provide text translation (captions).

**Describe the solution you'd like**
Let participants choose the language of the conversation in case of such an option, either audio channel or subtitles.

**Describe alternatives you've considered**
Let create separate room within the whole conversation between language facilitator and speaker. In this case the voice of speaker will be replaced by the voice of language facilitator. This will work in case if audience doesn't understand completely the speaker, but all of them understand the interpreter. 

Automatised solution: to create a bot who will help with automatic audio/text conversion using some AI (Google, MS etc), eg like in Skype or Youtube.

**Comment by aral** [comment]
The lack of this feature is one of the reasons I am having trouble getting the European Commission to use Jitsi for an upcoming event. The other is the lack of support for including a sign language interpreter.
