### ISSUE TITLE
Record a session

### ISSUE THREAD

**Issue by edjav2001** [jitsi/jitsi-meet#6155]
I have a dropbox account, but I cannot record any sessions, because gives me a message: "all the recorders are busy".
Thanks a lot.
Edgardo

**Comment by Pimmetje** [comment]
Are u talking about the https://meet.jit.si or do you have your private instance?

If u have a private instance please share some logfiles.

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
