### ISSUE TITLE
Grabación de videoconferencias

### ISSUE THREAD

**Issue by leandrotogithub** [jitsi/jitsi-meet#6159]
Al iniciar la grabación se conecta con mi perfil de dropbox, me avisa cuanto espacio disponible tiene, y me dice
"TODAS LAS GRABADORAS ESTAN ACTUALMENTE OCUPADAS
Estamos trabajando en liberar recursos de grabación. Vuelve a intentarlo en unos minutos"

En todos los intentos repite el mensaje. 
Estoy haciendo algo mal?

Saludos

Leandro

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
