### ISSUE TITLE
Only two participants, cannot more than 3 participants

### ISSUE THREAD

**Issue by sgnd** [jitsi/jitsi-meet#6161]
##  Description
I install Jitsi on ubuntu 18.04 on NAT, the private IP `10.20.31.63` and public IP `123.123.xxx`. Installation using quick-install in this repository. But if I test p2p only two participants work normally. And another participant access the jitsi, the video and audio are blank.

## Current behavior
- Only two participants with the same network
- Cannot more than two participants in same network
- If using another network not working

```
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
# org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=localhost
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.parisada.id
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=g2YliNlP
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.parisada.id
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=00294aee-4a1c-4475-b60a-232c9c0681d1
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=10.20.31.63
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=103.31.xxx.xxx
```

Port is opened
```
80/tcp
443/tcp
4443/tcp
10000/udp
```

## Expected Behavior
can conference call normally, with more than 2 participants

# Environment details
Ubuntu 18.04 - NAT

**Comment by damencho** [comment]
Make sure your port forwarding works and there is no firewall. 

Please use the community forum when you have problems or questions before opening new issue.

**Comment by ana-jd** [comment]
I consider all the efforts done in this project but a simple install on a new ubuntu or debian server should work, but it's not the case.
