### ISSUE TITLE
nginx1.16.1 tlsv1.3

### ISSUE THREAD

**Issue by sjnhnp** [jitsi/jitsi-meet#6163]
ubuntu18.04，Default nginx 1.14 

i use quick install

i want to update my nginx1.16 for tlsv1.3

but when i install 1.16.1, website will display:

welcome to nginx, not jitsi-meet

**Comment by luixxiul** [comment]
> use quick start

what do you mean "quick start"?

**Comment by sjnhnp** [comment]
sorry quick install

**Comment by saghul** [comment]
Is the jitsi site still enabled? Check the nginx logs, they probably contain a clue.

**Comment by l3d00m** [comment]
Closing as no further feedback was given, feel free to reopen with more details if it still persists.
