### ISSUE TITLE
Improving issue management

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6164]
Recently I've commented to issues here related with Jitsi camera / microphone / recording / integration with Dropbox, anything with the error message such as "all recorders are busy",  "grabación", "ocupados", everything that should be redirected to https://community.jitsi.org, not here.

Basically almost all of them is like one liner without useful information from a user, whose account was only created to leave a meaningless post like those. Dozens of duplicate are pilling up per day without a comment from a team member.

Though I am not related with the team in any way and just trying to help them as far as I could, I think a team member should engage with the stuff here in order to moderate this repository. Otherwise there would be no order and **even a spam** like https://github.com/jitsi/jitsi-meet/issues/6154 keep happening. It's no good not only for the team (in terms of public image, public relations) but also for users here who submit legit bug reports.

I see 8x8 is not a large company but as long as you keep this place open, you are expected to engage with issues here. Who are in charge of that job at 8x8?

I would like to recommend you to consider how to manage this place. Here is just my proposal: **a)** keep this place open and moderate to maintain the order, **b)** make it only open to `contributors` from the repo's setting menu and guide other users to https://community.jitsi.org (this should also have a category for foreign users who don't speak English), etc. If the team would engage with users, I would happily like to keep helping. However, if the team is going to let the thing including spam happen as it does currently and let the bot close the issues after six month of inactivity, please let me know. Otherwise what I am doing is nothing more than a waste of time and energy.

Thank you very much for your consideration.

**Comment by l3d00m** [comment]
I think adding some interested users like you to help with moderating duplicates, adding labels etc. should already help a lot. 

Not letting people report seems like a last resort option to me. That the devs don't answer in a day or so doesn't mean they couldn't trace the issues at a later date. Especially considering how good Jitsi works despite the huge influx says a lot of how much work they do.

Having presorted issues from the community should a) help to get more responses as they don't have to read through all the low effort and b) help to get higher quality issue reporting if done right.

**Comment by luixxiul** [comment]
Thank you for your response.

> That the devs don't answer in a day or so doesn't mean they couldn't trace the issues at a later date. 

The point is the forum where spamming can be seen is likely to have been already in deep trouble in terms of moderation... I have worked at a startup as a forum moderator and I think I know the stuff about that.

**Comment by ClausAndersen** [comment]
Option b) could be a little less strict by setting "Limit to existing users" which will help cool down fresh accounts.

But apart from that I agree. Having a meta for "camera/support" which directs people to the forums and the liberally mark all the one-line issues as "duplicate".

I would be happy to help out with this as well. Access right could be limited and the scope well-defined: Remove the cruft.

**Comment by ClausAndersen** [comment]
I see that  @damencho recently has closed some issues. Around 50 has been added just over the weekend.

A pinned "meta" for feature requests might make sense as well. Take the gist of an idea to a list in the meta with a link to the issue. And then close the issue. The project is drowning in ideas.

**Comment by S74HK9hV** [comment]
it's discouraging when you take the time to file a proper bug report and you don't get an answer. 

meanwhile, there are dozens of new issues opened every day that are just "RECORDING???? WHY NO WORK????" 

i really do feel sorry for the official team when they have to respond to all these low-effort issues. i've never seen a team so patient like @damencho answering stupid questions on github. keep up the good work. i just wish they would respond to the good issues and not waste time on the issues that have obvious solutions in the documentation.

**Comment by saghul** [comment]
Hey there,

Thanks for raising this @luixxiul. First and foremost, we really appreciate the effort that community members such as yourself have put into helping others, it's commendable.

As you might imagine we are kindda flooed on all fronts: GH issues, email, Discourse, etc. It's just impossible to answer everything. However it is important to be able to capture everything, so we can at leasst search if problem X has been reportedd before.

We are learning to deal with this new world order, so please bear with us as we update our approach to handling things.

I jusst updated the issue templates on this repo to try to make spam / low effort reports harder.

There are alreaddy 3 meta issues, with the current top 3 reports, but people seem to ignore them too.

IIRC there is a way to give people a "bug marshal" power, so they can help triage issues. We might want to also look into that.

**Comment by l3d00m** [comment]
Hi @saghul, happy to see you reply! And yes, it's possible to add the "triage" role for people on a repository basis, see here https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

Thanks for the insights and keep up the good work :)

**Comment by luixxiul** [comment]
I am going to keep this open to track the issue until eventually update to fix the problem will be published.

**Comment by toby63** [comment]
@l3d00m @saghul : 
Not intended to be offensive, but I think my topic title is better than this. Could you consider changing the title? (this was also the reason I haven't found this issue before I opened mine)

Nonetheless some of my points should be considered:
* apply more labels and milestones for better seperation between issues
* use an automatic issue labeler, like: https://github.com/github/issue-labeler
* delete empty or nonsense issues
* close duplicates (or even delete them)
* Respond to issues, when they are solved or if you work on them (can also be marked with labels)

I understand that things take some time, but you should consider working on structure first (means more labels, milestones, projects etc.), as this should make work also easier for you.

**Comment by saghul** [comment]
No offense taken @toby63 ! Updated the issue title. I'll try to start taking steps to improve the situation next week.

**Comment by luixxiul** [comment]
> Not intended to be offensive, but I think my topic title is better than this. Could you consider changing the title? (this was also the reason I haven't found this issue before I opened mine)

I don't want to be ironic but still I honestly cannot help but feeling a bit like I was told my English was too poor to contribute here.

**Comment by luixxiul** [comment]
I'd like to add:
- Create FAQ
- Lead retail users to the forum
- Limit the official language to English

**Comment by toby63** [comment]
luixxiul
> I don't want to be ironic but still I honestly cannot help but feeling a bit like I was told my English was too poor to contribute here.

It had nothing to do with english skills, it was simply a too long title that was also not really good for summarizing and finding this topic :wink: .

> Lead retail users to the forum

Is already implemented in the issue templates, somehow people ignore that.
Even though the templates could maybe be improved:
* Tell people that they should search in the issues and forum first (partly already implemented, but should maybe be included directly on this [page](https://github.com/jitsi/jitsi-meet/issues/new/choose) ) (because people maybe ignore what stands in a textfield))
* Decribe what bugs are, so that people who are not sure if they have bugs, go the forum instead
* add details to the environment info (such as system details)

@luixxiul @saghul 
> Create FAQ
also very good idea.
* you could especially mention the webcam problem and link directly to the issue report and solutions
* also add links to the FAQ in the issue templates and in the README.md

**Comment by l3d00m** [comment]
This was discussed in the last community call and according to them they'll soon open a new issue where volunteers can comment to help out on GitHub using the triage role as discussed here. See https://youtu.be/kmBYc7xV-vE?t=356

**Comment by saghul** [comment]
Alright, we now have a bug-marshall "progrmme": https://github.com/jitsi/jitsi-meet/issues/6656

@luixxiul you have been invited to the team.

I like the idea of the FAQ, feel free to kickstart a document in docs/ which we can improve with subsequent PRs.

I'm closing this issue now, since it has served it's purpose very well :-)

**Comment by luixxiul** [comment]
I confirmed the request just now :-)
