### ISSUE TITLE
turn server can't configure IP automatically

### ISSUE THREAD

**Issue by tanvir23** [jitsi/jitsi-meet#6165]
https://github.com/jitsi/jitsi-meet/blob/4fda428be16f7a41335ef35ce600aa0820754fb5/debian/jitsi-meet-turnserver.postinst#L109

In IPv6 enabled network turnserver can't configure IP automatically when installing the debian package. Because the command `dig +short myip.opendns.com @resolver1.opendns.com` doesn't produce any IP address. User has to manually configure it. Requesting to change the command `dig +short -4 myip.opendns.com @resolver1.opendns.com` which does produce IP address regardless of IPv6 enabled or not

**Comment by saghul** [comment]
Continues on https://github.com/jitsi/jitsi-meet/pull/6167
