### ISSUE TITLE
apt-key add should not be used

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#6169]
https://manpages.debian.org/buster/apt/apt-key.8.en.html says:

> **add**
> ...
> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

Please update https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md and
https://jitsi.org/downloads/ubuntu-debian-installations-instructions/

**Comment by luixxiul** [comment]
Addressed on [the install manual](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#add-the-jitsi-package-repository-and-update-the-list-of-available-packages) with this commit: https://github.com/jitsi/handbook/commit/a8092779b8171400d110ea45b69e877a6f1e2de2 by @pajeon.

That commit did not only replace `apt-key add` but also even limit trust of the signing key.

> avoids adding the Jitsi signing key to the global SecureApt trust anchor in /etc/apt/trusted.gpg.d, which would cause the system to accept signatures from Jitsi's key on all other repositories configured on the system that don't have a signed-by option

https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ needs to be taken care of outside of this repository.

**Comment by damencho** [comment]
Fixed https://jitsi.org/downloads/ubuntu-debian-installations-instructions/
