### ISSUE TITLE
Restrict access to jitsi-meet (additional feature requests)

### ISSUE THREAD

**Issue by toby63** [jitsi/jitsi-meet#6171]
As #304 is closed and locked for conversation, I need to open a new issue to add three related requests:
1. Make it more clear on your website, readmes etc. that the default setup is open for everyone (Server-URL can be accessed by everyone and rooms can be created by everyone).

* The Website (https://jitsi.org/jitsi-meet/) does not mention anything about the ability for access for everyone, instead it says `Invite users `
which gives the impression to users, that also room creation is restricted (to themselves only (thats what i would think) or at least by "custom" url).
* Quick Install Howto: The following should not just be in section "Advanced configuration", it should be mentioned on top of the howto or somewhere more visible: 
qoute from [quick install howto](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md):
`By default, anyone who has access to your jitsi instance will be able to start a conference: if your server is open to the world, anyone can have a chat with anyone else. If you want to limit the ability to start a conference to registered users, set up a "secure domain". Follow the instructions at https://github.com/jitsi/jicofo#secure-domain.`
* This also seems to be missing in the [manual install howto](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md)
* Docker-Jitsi-Meet : The [section for authentication](https://github.com/jitsi/docker-jitsi-meet#authentication) should be mentioned above in the Table of content and should be explained more.

2. Consider including the restricted option by default into your pre-configured server packages and docker setups etc. (in case of docker setups, it could also be a seperate one, for those who want to use a version that is restricted by default)

3. Add an option or a howto for restricting access to the website (jitsi-meet startpage) itself (not just rooms or room creation).
This could be achieved by three options:
    * password-protected by default (or at least option for setting password, also during install/configuration)
    * seperate start page for quests (no room creation available; not recommended option and also not necessary, because the users will be invited by custom url)
    * startpage is also in a custom url (also not recommended, except when combined with password-protection, but would at least be better than now)

Note:
I want to clarify that this is not a request for advanced users in the first place, I know that many advanced users should be able to read everything properly, set advanced options up by looking into additional documentation etc.
Keep in mind that in these times, your software will be used by far more inexperienced users.

**Comment by toby63** [comment]
More or less related: #5407 #5579

**Comment by saghul** [comment]
>     1. Make it more clear on your website, readmes etc. that the default setup is open for everyone (Server-URL can be accessed by everyone and rooms can be created by everyone).

Sure, let's have it! Want to take a crack at it? We now have a handbook: https://github.com/jitsi/handbook



>     * The Website (https://jitsi.org/jitsi-meet/) does not mention anything about the ability for access for everyone, instead it says `Invite users `
>       which gives the impression to users, that also room creation is restricted (to themselves only (thats what i would think) or at least by "custom" url).

We are already making strides to solve this. There is now a warning for rooms with easy to guess names without a password, and a "lobby" feature is incoming, which would mean users wait and a moderator must let them in.

>     * Quick Install Howto: The following should not just be in section "Advanced configuration", it should be mentioned on top of the howto or somewhere more visible:
>       qoute from [quick install howto](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md):
>       `By default, anyone who has access to your jitsi instance will be able to start a conference: if your server is open to the world, anyone can have a chat with anyone else. If you want to limit the ability to start a conference to registered users, set up a "secure domain". Follow the instructions at https://github.com/jitsi/jicofo#secure-domain.`

Please feel free to make a PR to the handbook! We moved those docs over there.



> * This also seems to be missing in the [manual install howto](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md)
> 
> * Docker-Jitsi-Meet : The [section for authentication](https://github.com/jitsi/docker-jitsi-meet#authentication) should be mentioned above in the Table of content and should be explained more.

Ditto.



>     1. Consider including the restricted option by default into your pre-configured server packages and docker setups etc. (in case of docker setups, it could also be a seperate one, for those who want to use a version that is restricted by default)

What do you mean by restricted here? Authentication? We can't possibly know what people want.



>     2\. Add an option or a howto for restricting access to the website (jitsi-meet startpage) itself (not just rooms or room creation).

Not sure what benefit this has.

Thanks for your feedback!

**Comment by toby63** [comment]
> > ```
> > 1. Make it more clear on your website, readmes etc. that the default setup is open for everyone (Server-URL can be accessed by everyone and rooms can be created by everyone).
> > ```
> 
> Sure, let's have it! Want to take a crack at it? We now have a handbook: https://github.com/jitsi/handbook

No offence, but:
While a handbook might be useful (though it's exaggerated imo, because jitsi is not such a mega-complex software to use), this is not the point.
I asked for clarification in the description of your software and service, this does not happen in a handbook, it happens on the website and in the readme's.

> > ```
> > * The Website (https://jitsi.org/jitsi-meet/) does not mention anything about the ability for access for everyone, instead it says `Invite users `
> >   which gives the impression to users, that also room creation is restricted (to themselves only (thats what i would think) or at least by "custom" url).
> > ```
> 
> We are already making strides to solve this. There is now a warning for rooms with easy to guess names without a password, and a "lobby" feature is incoming, which would mean users wait and a moderator must let them in.

Again: that is good, but that was not my point.
My point is to prevent strangers from creating rooms by default in the first place.

> > ```
> > * Quick Install Howto: The following should not just be in section "Advanced configuration", it should be mentioned on top of the howto or somewhere more visible:
> >   qoute from [quick install howto](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md):
> >   `By default, anyone who has access to your jitsi instance will be able to start a conference: if your server is open to the world, anyone can have a chat with anyone else. If you want to limit the ability to start a conference to registered users, set up a "secure domain". Follow the instructions at https://github.com/jitsi/jicofo#secure-domain.`
> > ```
> 
> Please feel free to make a PR to the handbook! We moved those docs over there.

I will consider that.

> > ```
> > 1. Consider including the restricted option by default into your pre-configured server packages and docker setups etc. (in case of docker setups, it could also be a seperate one, for those who want to use a version that is restricted by default)
> > ```
> 
> What do you mean by restricted here? Authentication? We can't possibly know what people want.

I guess we can assume that most people don't want a server, that can be accessed by every stranger to use.
So yes, the above mentioned option (restricting who can create rooms) should be applied by default imo.

> > ```
> > 2\. Add an option or a howto for restricting access to the website (jitsi-meet startpage) itself (not just rooms or room creation).
> > ```
> 
> Not sure what benefit this has.

Imo it's a strange design choice, to let strangers look at a page that suggests to create a voip-chatroom and then (after they tried to do that) telling them that it is forbidden (if you applied an option to restrict room creation).
A better design would be to not let them access the website by default.

**Comment by luixxiul** [comment]
> this does not happen in a handbook, it happens on the website and in the readme's.

I think you are suggesting something like `Tip: by default Jitsi Meet instance is public. To restrict room creation you need to set up authentication. Click [here](https://jitsi.github.io/handbook/docs/devops-guide/secure-domain) for more information."` on README.md, maybe under https://github.com/jitsi/jitsi-meet#installation.

If so, I think it sounds fair, since it is exactly those who would never read the handbook that would need this kind of information.

> A better design would be to not let them access the website by default.

I am not against that, yet since this is fundamental, you would have to overhaul the design from the scratch. I think it would take a lot time and effort, I guess.

**Comment by toby63** [comment]
> > this does not happen in a handbook, it happens on the website and in the readme's.
> 
> I think you are suggesting something like `Tip: by default Jitsi Meet instance is public. To restrict room creation you need to set up authentication. Click [here](https://jitsi.github.io/handbook/docs/devops-guide/secure-domain) for more information."` on README.md, maybe under https://github.com/jitsi/jitsi-meet#installation.
> 
> If so, I think it sounds fair, since it is exactly those who would never read the handbook that would need this kind of information.

Yes, something like that would be good :+1: .
I would make it like:
`By default the Jitsi Meet instance is public, so everyone (even strangers) can create rooms [...]` 

> > A better design would be to not let them access the website by default.
> 
> I am not against that, yet since this is fundamental, you would have to overhaul the design from the scratch. I think it would take a lot time and effort, I guess.

I don't think thats the case, because jitsi is using a webserver (nginx) and the access restriction can be configured in nginx.
That said it is of course a bit more convenient (and it looks better) if it's directly implemented into the website (the above method will likely create a pop-up-window in the browser).
But that should also not be a big problem.
It might even be more convenient, to login on the main site and not during room creation.

**Comment by luixxiul** [comment]
@saghul What would you think? On README.md: `Tip: By default the Jitsi Meet instance is public, so everyone (even strangers) can create rooms.To restrict room creation you need to set up authentication. Click [here](https://jitsi.github.io/handbook/docs/devops-guide/secure-domain) for more information.`

re: @toby63 I'm not quire sure about authentication design / intention of this project so maybe I should stop talking about that stuff here. A dev team member would answer.

**Comment by toby63** [comment]
bump

**Comment by toby63** [comment]
bump

**Comment by aseempatni** [comment]
Is this actually implemented? How do I restrict access to homepage for unauthenticated users?
