### ISSUE TITLE
No SD/HD video on Firefox

### ISSUE THREAD

**Issue by bluppfisk** [jitsi/jitsi-meet#6173]
## Description
The Firefox client seems to be unable to upgrade to HD video.

## Current behavior
When connecting to my own Jitsi server using Google Chrome, the video will start at SD and eventually upgrade to HD.
On Firefox, it stays at LD (for the receiver). 

## Expected Behavior
When enough bandwidth is available (there is!) it should upgrade to HD video as soon as possible.

## Possible Solution
Not quite sure. I already set the config to force 1080p

## Steps to reproduce
- Set up a Jitsi server
- Start a room
- Connect two clients using Firefox

# Environment details
Using Firefox 77 (Nightly) on Ubuntu 19.10
Server on Ubuntu 16.04

**Comment by jallamsetty1** [comment]
Hey there, what version of the JVB are you using ? Recently we made improvements to our bandwidth probing mechanism on our bridge that would ramp up the available b/w faster on FF 75 and later versions. We had identified a bug on FF75 which would cause the bridge to not send SD/HD to Firefox clients, we also added a workaround for that on our latest JVB. Can you give our JVB nightly a try and see if it gets resolved ?

**Comment by bluppfisk** [comment]
Hi! Sorry for the late reply; didn't have time to play with it. I've now updated to the latest version and can confirm that I will now get a HD stream from all clients (3x myself... TIL) after a while. It starts at SD/LD and upgrades briefly after. Thanks!

However, it seems I had to do a hard refresh on all Firefox clients to achieve this result. Was there client-side code involved in this fix?
