### ISSUE TITLE
Jitsi-meet not starting recording properly, asking for Dropbox signin

### ISSUE THREAD

**Issue by garrigatorres** [jitsi/jitsi-meet#6174]
My Jitsi Meet was recording (with audio issues) to a Jibri Server, and after adding a second Jibri when I start recording it launches Dropbox authentication instead of start recording.
Jicofo logs show two instances of Jibri, apparently ready: server-IC10 and aws_jibri1:

Jicofo 2020-04-18 15:26:31.091 INFO: [19] org.jitsi.jicofo.xmpp.BaseBrewery.start().186 Joined brewery room: JibriBrewery@internal.auth.jitsi.escolaarrels.com
Jicofo 2020-04-18 15:26:31.092 INFO: [30] org.jitsi.jicofo.xmpp.BaseBrewery.processInstanceStatusChanged().329 Added brewery instance: jibribrewery@internal.auth.jitsi.escolaarrels.com/aws_jibri1
Jicofo 2020-04-18 15:26:31.103 INFO: [19] org.jitsi.jicofo.xmpp.BaseBrewery.start().186 Joined brewery room: JvbBrewery@internal.auth.jitsi.escolaarrels.com
Jicofo 2020-04-18 15:26:31.115 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().137 Received Jibri jibribrewery@internal.auth.jitsi.escolaarrels.com/aws_jibri1 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='idle'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
Jicofo 2020-04-18 15:26:31.125 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().175 Jibri: jibribrewery@internal.auth.jitsi.escolaarrels.com/aws_jibri1 available: true
Jicofo 2020-04-18 15:26:31.129 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().137 Received Jibri jibribrewery@internal.auth.jitsi.escolaarrels.com/aws_jibri1 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='idle'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
Jicofo 2020-04-18 15:26:31.130 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().175 Jibri: jibribrewery@internal.auth.jitsi.escolaarrels.com/aws_jibri1 available: true
Jicofo 2020-04-18 15:26:31.131 INFO: [30] org.jitsi.jicofo.xmpp.BaseBrewery.processInstanceStatusChanged().329 Added brewery instance: jibribrewery@internal.auth.jitsi.escolaarrels.com/server-IC10
Jicofo 2020-04-18 15:26:31.131 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().137 Received Jibri jibribrewery@internal.auth.jitsi.escolaarrels.com/server-IC10 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='idle'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
Jicofo 2020-04-18 15:26:31.135 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().175 Jibri: jibribrewery@internal.auth.jitsi.escolaarrels.com/server-IC10 available: true
Jicofo 2020-04-18 15:26:31.149 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: recorder.jitsi.escolaarrels.com, Prosody(0.10.0,Linux)
Jicofo 2020-04-18 15:26:31.155 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().137 Received Jibri jibribrewery@internal.auth.jitsi.escolaarrels.com/server-IC10 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='idle'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
Jicofo 2020-04-18 15:26:31.155 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().175 Jibri: jibribrewery@internal.auth.jitsi.escolaarrels.com/server-IC10 available: true
Jicofo 2020-04-18 15:26:31.156 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: conference.jitsi.escolaarrels.com, null
Jicofo 2020-04-18 15:26:31.156 INFO: [19] org.jitsi.jicofo.JitsiMeetServices.log() MUC component discovered: conference.jitsi.escolaarrels.com
Jicofo 2020-04-18 15:26:31.170 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: auth.jitsi.escolaarrels.com, Prosody(0.10.0,Linux)
Jicofo 2020-04-18 15:26:31.170 INFO: [19] org.jitsi.jicofo.JitsiMeetServices.log() Detected XMPP server version: Prosody(0.10.0,Linux)
Jicofo 2020-04-18 15:26:31.172 INFO: [19] org.jitsi.jicofo.ComponentsDiscovery.log() Services re-discovery interval: 30000
Jicofo 2020-04-18 15:26:31.175 INFO: [19] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
