### ISSUE TITLE
Percent-encoded title

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#6175]
![image](https://user-images.githubusercontent.com/14617699/79643423-8e005a80-81ab-11ea-883e-a55169b0b507.png)

Steps to reproduce:
https://meet.jit.si/фыва

**Comment by l3d00m** [comment]
Hi, see #5223. It was fixed recently and worked for me with your link.

**Comment by 532910** [comment]
I confirm it's fixed, thank you!
