### ISSUE TITLE
Safari leads to restarts when any other user joins room

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#6178]
Latest Debian jitsi-meet unstable installed on debian 9 server.

Testing with Safari 13.1 on Catalina it works as expected at first.
However, as soon as anyone else connects it seems the jvb kicks out Safari and tries to endlessly reconnect.

Hope this bug report helps.

Thanks for your awesome work. Excited to see Jitsi progress so much over the years.

Likely related to https://github.com/jitsi/jitsi-meet/issues/6176

**Comment by damencho** [comment]
Can you check the errors and those are the same as #6176 close this issue as a duplicate.

**Comment by pdarcos** [comment]
I don't think it's the same error. This is what I see in the Safari console as soon as another user joins:

[Error] 2020-04-18T18:39:51.636Z – "[JitsiMeetJS.js]" – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: "
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
play
play — AbstractAudio.js:84
(anonymous function) — middleware.js:71
(anonymous function) — reducer.js:52
(anonymous function) — app.bundle.min.js:210:64500
(anonymous function) — middleware.js:23
W — middleware.js:303
(anonymous function) — middleware.js:120
(anonymous function) — middleware.js:18
(anonymous function) — actions.web.js:26
(anonymous function) — middleware.js:52
(anonymous function) — middleware.js:37
(anonymous function) — middleware.js:23
(anonymous function) — middleware.js:31
(anonymous function) — middleware.js:61
asyncFunctionResume
(anonymous function) — middleware.js:95
(anonymous function) — middleware.web.js:34
(anonymous function) — middleware.js:41
(anonymous function) — middleware.web.js:39
(anonymous function) — actions.js:29
(anonymous function) — middleware.js:20
(anonymous function) — actions.any.js:250
(anonymous function) — middleware.js:74
(anonymous function) — middleware.js:149
(anonymous function) — middleware.js:21
(anonymous function) — middleware.js:106
(anonymous function) — middleware.js:21
(anonymous function) — app.bundle.min.js:210:64500
(anonymous function) — middleware.js:23
f — functions.js:134
(anonymous function) — conference.js:1976
(anonymous function) — events.js:151
(anonymous function) — JitsiConference.js:1490
[native code]
(anonymous function) — events.js:146
onPresence — ChatRoom.js:568
onPresence — strophe.emuc.js:130
onPresence
run — strophe.umd.js:1875
(anonymous function) — strophe.umd.js:3157
forEachChild — strophe.umd.js:830
_dataRecv — strophe.umd.js:3146
_dataRecv
_onRequestStateChange — strophe.umd.js:5012
_onRequestStateChange
bound _onRequestStateChange
	error
	s (lib-jitsi-meet.min.js:10:26346)
	s
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:17:77942)
	(anonymous function) (app.bundle.min.js:1:53462)


[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (app.bundle.min.js:54:173031)
	(anonymous function) (app.bundle.min.js:24:72877)
	(anonymous function) (app.bundle.min.js:24:72986)
	(anonymous function) (app.bundle.min.js:210:64500)
	(anonymous function) (app.bundle.min.js:16:75659)
	W (app.bundle.min.js:1:99415)
	(anonymous function) (app.bundle.min.js:1:101897)
	(anonymous function) (app.bundle.min.js:29:191272)
	(anonymous function) (app.bundle.min.js:24:227775)
	(anonymous function) (app.bundle.min.js:24:216598)
	(anonymous function) (app.bundle.min.js:24:212405)
	(anonymous function) (app.bundle.min.js:70:49721)
	(anonymous function) (app.bundle.min.js:24:211503)
	(anonymous function) (app.bundle.min.js:24:210164)
	asyncFunctionResume
	(anonymous function) (app.bundle.min.js:24:207679)
	(anonymous function) (app.bundle.min.js:16:31706)
	(anonymous function) (app.bundle.min.js:29:182462)
	(anonymous function) (app.bundle.min.js:24:181001)
	(anonymous function) (app.bundle.min.js:63:29179)
	(anonymous function) (app.bundle.min.js:54:123063)
	(anonymous function) (app.bundle.min.js:24:287214)
	(anonymous function) (app.bundle.min.js:54:48348)
	(anonymous function) (app.bundle.min.js:24:253659)
	(anonymous function) (app.bundle.min.js:29:246128)
	(anonymous function) (app.bundle.min.js:1:42747)
	(anonymous function) (app.bundle.min.js:1:39866)
	(anonymous function) (app.bundle.min.js:210:64500)
	(anonymous function) (app.bundle.min.js:16:75659)
	f (app.bundle.min.js:24:250503)
	(anonymous function) (app.bundle.min.js:126:311079)
	(anonymous function) (lib-jitsi-meet.min.js:1:126916)
	(anonymous function) (lib-jitsi-meet.min.js:10:170222)
	(anonymous function)
	(anonymous function) (lib-jitsi-meet.min.js:1:126859)
	onPresence (lib-jitsi-meet.min.js:10:214430)
	onPresence (lib-jitsi-meet.min.js:10:207443)
	onPresence
	run (lib-jitsi-meet.min.js:1:21365)
	(anonymous function) (lib-jitsi-meet.min.js:1:29816)
	forEachChild (lib-jitsi-meet.min.js:1:13021)
	_dataRecv (lib-jitsi-meet.min.js:1:29657)
	_dataRecv
	_onRequestStateChange (lib-jitsi-meet.min.js:1:49647)
	_onRequestStateChange
	bound _onRequestStateChange

**Comment by pdarcos** [comment]
Has anyone else seen this behaviour with Safari?

Do you need logs from jvb or jicofo side?

Let me know how I can help. It's great to almost have Safari working well with jitsi-meet.

Thanks

**Comment by jallamsetty1** [comment]
@pdarcos, can you please provide the full console log from the browser ? Can you also check if you see the same behavior on meet.jit.si ?

**Comment by pdarcos** [comment]
Sure @jallamsetty1 

I checked on meet.jit.si as well as beta.meet.jit.si and I can't reproduce (I also get the browser warnings on both servers using Safari which I don't get on my latest unstable debian package updated a few hours ago).

As for the full console logs, here they are https://pastebin.com/cJBbDhGP

Safari is able to open a room and everything seems ok (no yellow browser warning on my server).
But as soon as another client joins (I've tested with Chromium and Firefox) the bug happens. As long as there's another client in the room Safari will keep restarting the connection. As soon as Safari is the only one left in the room it stops restarting the connection.

It seems we're not using the same code as you are using on meet.jit.si

Hope this helps and thanks for your awesome work!

**Comment by pdarcos** [comment]
In these 3 minutes Safari is all by itself in the room and everything seems OK.
At 18:47 Chromium enters the room and the problems begin immediately.

o — Logger.js:1732020-04-20T18:44:06.457Z – "[modules/UI/videolayout/SmallVideo.js]" – "Displaying video for 33c20f58, data: [{\"isCurrentlyOnLargeVideo\":true,\"isHovered\":false,\"isAudioOnly\":false,\"tileViewEnabled\":true,\"isVideoP…"

All is fine until Chromium enters here

s — Logger.js:1822020-04-20T18:47:12.397Z – "[modules/xmpp/ChatRoom.js]" – "entered" – "123@conference.jitsi.domain.com/6edc6fa1" – {affiliation: "none", role: "participant", jid: "6edc6fa1-c749-431c-abe2-1bfc6658f5aa@jitsi.domain.com/a05bfd5a-12d3-40ab-9786-a23c908bdd0a", …}

**Comment by jallamsetty1** [comment]
This seems to be duplicate of #6176, can you please close this issue as

**Comment by jallamsetty1** [comment]
We have identified the issue, will be releasing the fix soon. Meanwhile, can you please verify if the issue goes away when you change the bridge channel to `websockets`. The default value with debian package is '`datachannel`'.
This is a config.js setting on your depolyment
    openBridgeChannel: 'datachannel', // One of true, 'datachannel', or 'websocket'

**Comment by pdarcos** [comment]
I can confirm that changing to websockets makes the issue go away.
Thanks
