### ISSUE TITLE
instagram live

### ISSUE THREAD

**Issue by asedali** [jitsi/jitsi-meet#6188]
How to stream one user and others can only comment.
Something like Instagram live.

**Comment by Pimmetje** [comment]
Currently there is only youtube. 
As for a new feature would #6156 be enough for instagram?

**Comment by asedali** [comment]
Sorry for my inappropriate issue title.
Can it be made similar to a webinar system?
That is, the coach video is played and users leave a comment.

**Comment by Pimmetje** [comment]
Currently this is not possible afaik

**Comment by Pimmetje** [comment]
Here is a good explanation https://www.youtube.com/watch?v=S43-A1N_COE

**Comment by Echolon** [comment]
ref. Live streaming #5146

**Comment by Echolon** [comment]
unstale
