### ISSUE TITLE
Settings page does not allow input

### ISSUE THREAD

**Issue by mir07** [jitsi/jitsi-meet#6190]
## Description
---
When tapping any text field in the settings window the keyboard pops up very quickly and then disappears again making any changes in the settings page impossible. This bug was introduced with the last released version of jitsi meet on Google Play: 20.2.1 build 4016143

# Environment details
---
I have seen this behavior on Android 9 and Android 10 using latest security patch

**Comment by saghul** [comment]
This should have been fixed in version 20.2.3. Can you please update and check again?

**Comment by mir07** [comment]
> This should have been fixed in version 20.2.3. Can you please update and check again?
I can confirm that the above version fixed the issue.
