### ISSUE TITLE
Instructions on how to add/update Jitsi translations on README.md

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#6192]
Could you please add a section to the `README.md` at https://github.com/jitsi/jitsi-meet explaining how to add/update Jitsi translations?

What do you think?

Thank you

**Comment by Pimmetje** [comment]
There is a readme in the lang folder https://github.com/jitsi/jitsi-meet/tree/master/lang

**Comment by Pimmetje** [comment]
http://translate.jitsi.org does not work so i guess it needs a update.

**Comment by damencho** [comment]
We are working on it https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by MagicFab** [comment]
Can someone indicate here how to manually submit translation corrections / copntributions for now ? It should be possible to do so.

I won't be contributing via Crowdin if that's a final decision. Thanks in advance.
