### ISSUE TITLE
All recorders are busy

### ISSUE THREAD

**Issue by shusterboris** [jitsi/jitsi-meet#6193]
My problem is that all recorders are busy durring 5 hours all time. Is it problem related to havy loading on jitsi? Or there are another reasons?

**Comment by Pimmetje** [comment]
If i watch this https://www.youtube.com/watch?v=S43-A1N_COE i get the feeling it uses a lot of resources. So it's safe to assume that's the cause of it. OSB screencapture is better choice if possible

**Comment by campelo** [comment]
Duplicate of #6257

**Comment by shusterboris** [comment]
Thanks!
The problem disappeared! It's work fine
Many thanks, Boris

ср, 22 апр. 2020 г. в 04:26, Flavio Campelo <notifications@github.com>:

**Comment by toby63** [comment]
@shusterboris :
> The problem disappeared! It's work fine
Then how about closing this?

**Comment by shusterboris** [comment]
Sure!
Thanks!
Boris

ср, 22 апр. 2020 г. в 17:52, toby63 <notifications@github.com>:
