### ISSUE TITLE
mi cam doesn´t work

### ISSUE THREAD

**Issue by Manuotravez** [jitsi/jitsi-meet#6196]
Hello, i don´t talk a good english, so, excuse me since now.
The camera of my laptop isn´t working for de hangouts. How can i fix it?
Im using chrome because firefox don't recognize even the microphone.
I think is a common problem, because some friends had the same problem... so, maybe you can help me and i help them...
Thanksss
Manu

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
