### ISSUE TITLE
coturn listens on UDP only

### ISSUE THREAD

**Issue by perryflynn** [jitsi/jitsi-meet#6201]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

After a default Debian installation the coturn server only listens on UDP, but not on TCP. 

But TCP is used in NGINX and Prosody.

## Current behavior

TCP is disabled in `/etc/turnserver.conf`

## Expected Behavior

TCP is enabled in `/etc/turnserver.conf` by removing the `no-tcp` Option.

## Steps to reproduce

- Add jitsi debian repo
- Install `jitsi-meet`
- Install `jitsi-meet-turnserver`

# Environment details

- Fresh installed server (2020-04-19 20:45:00 CET)
- Debian 10
- jitsi-meet 2.0.4468-1
- jitsi-meet-turnserver 1.0.4025-1

**Comment by damencho** [comment]
The turnserver uses tls by default, which is TCP and there is no point of having both as the TLS one covers more use-cases. 

https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-turn/turnserver.conf#L11
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L11
There is no default setting to use turn tcp.

**Comment by uzsito** [comment]
Sorry for resurrecting this thread, but I would like to ask some clarification about it.

I installed Jitsi server using the Self-Hosting Guide "quick Jitsi-Meet installation" method on a Ubuntu 20.04 host, behind NAT, and forwarded ports on my firewall to the host including TCP 5349 for TURN.

After the installation my `/etc/turnserver.conf` also contains `no-tcp` option.

If coTURN listens only on UDP ports, why should I forward TCP 5349?
On multiple points of the documentation TCP port 5349 is mentioned about TURN server.

Sorry, I am a bit confused about this.

**Comment by damencho** [comment]
But it listens for TLS connections on port 5349 which are TCP. 
If you remove no-tcp option the turnserver will be responding to TCP connection attempts on 3478 without the TLS.

**Comment by Iruwen** [comment]
I ended up here because I faced the same issue, then figured that the directory containing the cert and key initially wasn't readable by coturn (user turnserver). For whatever reason this wasn't shown in the logs, coturn (4.5.1.1-1.1ubuntu0.20.04.2) just silently started without TLS on TCP Port 5349.
