### ISSUE TITLE
real-time whiteboard

### ISSUE THREAD

**Issue by 5V715** [jitsi/jitsi-meet#6202]
Would be really nice to see a real-time whiteboard for everybody to draw and see in real-time.

**Comment by ovari** [comment]
Perhaps [Etherpad](https://etherpad.org/) could also be added? Not a whiteboard but `a highly customizable Open Source online editor providing collaborative editing in really real-time.`

**Comment by ovari** [comment]
Could [OpenBoard](https://www.openboard.ch/index.en.html) be added to Jitsi Meet?

**Comment by ostasevych** [comment]
Cryptpad.fr may be also considered.

**Comment by ostasevych** [comment]
> Could [OpenBoard](https://www.openboard.ch/index.en.html) be added to Jitsi Meet?

Is it web app? What I see it is good for desktops only...

**Comment by Echolon** [comment]
As long as there is no attempt to implement this, please use for example: https://drawpile.net/

**Comment by Echolon** [comment]
Closing this as duplicate with reference to:

**Shared drawing canvas / whiteboard** #5295
