### ISSUE TITLE
Translation strings for footer at https://meet.jit.si/

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#6204]
Please enable the footer at https://meet.jit.si/ to be translated as shown in the image below.

![kép](https://user-images.githubusercontent.com/17465872/79700357-61962c80-82d8-11ea-86aa-ef03f82fa9d9.png)

What do you think?

Thank you

**Comment by luixxiul** [comment]
See https://github.com/jitsi/jitsi-meet/issues/6209#issuecomment-633171245

> that page is static and I assume localization needs to be done outside of the repository.

**Comment by saghul** [comment]
Correct.

**Comment by ovari** [comment]
Can a link to where they need to be translated be added to this issue? Thank you
