### ISSUE TITLE
Please enable "Mute everyone" to be translated

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#6206]
Please enable "Mute everyone" string in the "More actions" button to be translated.

![kép](https://user-images.githubusercontent.com/17465872/79700448-f436cb80-82d8-11ea-80cb-5c073ad8bd43.png)

Thank you

**Comment by damencho** [comment]
That is already the case https://github.com/jitsi/jitsi-meet/blob/master/lang/main.json#L660
