### ISSUE TITLE
Please enable "Microphones" and "Speakers" headings to be translated in the "Mute / Unmute" button

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#6207]
Please enable "Microphones" and "Speakers" headings to be translated in the "Mute / Unmute" button as shown in the image below.

![kép](https://user-images.githubusercontent.com/17465872/79700549-d74ec800-82d9-11ea-81d8-4fbb8cf30e24.png)

Thank you

**Comment by damencho** [comment]
All strings are already translatable.
