### ISSUE TITLE
No speaker shown in the "Mute / Unmute" button

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#6208]
Should the speaker be listed in the `Mute / Unmute` button?

![kép](https://user-images.githubusercontent.com/17465872/79700596-1f6dea80-82da-11ea-9fd5-723e04792176.png)

Thank you

**Comment by jallamsetty1** [comment]
Hey there, what browser are you seeing this on ? Please note that the speakers will only be enumerated one chrome. Firefox and Safari, do not support changing of the speaker devices and therefore do not enumerate those devices.

**Comment by ovari** [comment]
Thanks for your reply. Seems to be a Firefox bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1631672

**Comment by ovari** [comment]
> We gonna release the output device enumeration ([bug 1630289](https://bugzilla.mozilla.org/show_bug.cgi?id=1630289)) before the support for changing the output device. However, we are working actively on the latter, it is more involved and it takes more time, it's coming rapidly though.
https://bugzilla.mozilla.org/show_bug.cgi?id=1164187#c64

Once Firefox has "support for changing the output device" will Jitsi work like Chrome without any modification?

Thank you
