### ISSUE TITLE
Translation of https://meet.jit.si/static/close3.html

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#6209]
Please enable translation of the message once the `Leave` button is pressed. The URL is https://meet.jit.si/static/close3.html and the image is

![kép](https://user-images.githubusercontent.com/17465872/79700637-87bccc00-82da-11ea-8961-6284754154cd.png)

What do you think?

Thank you

**Comment by luixxiul** [comment]
that page is static and I assume localization needs to be done outside of the repository.

**Comment by ovari** [comment]
Can a link to where they need to be translated be added to this issue? Thank you
