### ISSUE TITLE
Enregistrement 

### ISSUE THREAD

**Issue by Amandinecdl** [jitsi/jitsi-meet#6215]
Bonjour, 
Depuis le début du confinement nous utilisons régulièrement votre site et les enregistrement, hors il est actuellement saturé. 
Pourriez vous m'indiquer si une solution sera rapidement apportée ? Existe il une autre possibilité d'enregistrement ? 
Merci de votre aide 

Hello,
Since the beginning of the containment we regularly use your site and the recordings, except it is currently saturated.
Could you tell me if a solution will be found quickly? Is there another possibility of registration?
Thank you for your help

**Comment by campelo** [comment]
Duplicate of #6257

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

I'm a community contributor and not directly affiliated with the Jitsi team.
