### ISSUE TITLE
jitsi-meet-tokens cannot be installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by radiospiel** [jitsi/jitsi-meet#6217]
## Description
---

I cannot install jitsi-meet-tokens , since it depends on prosody >= 0.11. Ubuntu 18.04 does not provide that version - it is on 0.10 - and, given the LTS status, probably never will.

for some more background on how I stumbled on this see https://community.jitsi.org/t/conference-backend-possible-without-awt-tokens-installation-guides/39297, but I think the scenario is unrelated

**Comment by radiospiel** [comment]
Note that I just stumbled across this remark: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#patching-prosody Given the wording in that file it looks as if "apt install jitsi-meet-tokens" should succeed before patching prosody, but I guess now that it is the other way around .)

**Comment by wsnipex** [comment]
in prosody 11, which you can install from the prosody repo https://packages.prosody.im/debian, jitsi-meet-tokens was replaced by jitsi-meet-prosody

**Comment by radiospiel** [comment]
Thank you, I will give it a try!
