### ISSUE TITLE
DNSFilter problems

### ISSUE THREAD

**Issue by em230418** [jitsi/jitsi-meet#6218]
Hi, all!

## Description
---
Working with Jitsi Meet on Android with https://f-droid.org/ru/packages/dnsfilter.android/index.html installed. Using official meet.jit.si

## Current behavior
---
I see chat, micro and video statuses (turned off/on) of peers, who is sharing screen. But I don't hear anything, noone hears me and don't see the shared screen itself. If I exit DNSFilter - everything is ok. When I start again DNSFilter while running Jitsi Meet - again I can't hear anything and so on. Checked longs of DNSFilter - it does not block/reject jitsi's DNS queriers.

## Expected Behavior
---
Working fine with DNSFilter.

## Possible Solution
---
No idea.

## Steps to reproduce
---
Join any conference, make sure you can hear everyone and everyone hears you. Start DNSFilter. You won't hear anyone and vice-versa. You will be able to chat.

# Environment details
---
Android 8.1.0
Jitsi Meet 20.2.0
DNSFilter 1.50.39.1

**Comment by saghul** [comment]
It's clear DNSFilter is doing *something*, you should probably ask them, sincec they know better what their software does.

The fact that chat works but audio / video doesn't suggests UDP might have gotten blocked somehow.
