### ISSUE TITLE
Grabar una Reunion

### ISSUE THREAD

**Issue by alvaroedisonmd** [jitsi/jitsi-meet#6227]
Estoy tratando de hacer una grabación de la reunión de clase y me informa que todas las grabadoras están actualmente ocupadas, que debo hacer? gracias

**Comment by rosa2** [comment]
Buscar otro servidor?
Piensa que los servidores gratuitos tienen recursos limitados y si necesitas algo que requiere profesionalmente esos servicios, tendrias que pagar en otro lado, no?

También decirte, que reportes en inglés que si no es más difícil contestarte :)
Y que des más detalles, como por ejemplo, donde te ha pasado porque cada servidor tiene su configuración personalizada.
Aquí tienes un recurso muy bueno para ver servidores menos cargados

https://ladatano.partidopirata.com.ar/jitsimeter/

**Comment by campelo** [comment]
Duplicate of #6257
