### ISSUE TITLE
recording trouble

### ISSUE THREAD

**Issue by enricaardissino** [jitsi/jitsi-meet#6228]
when i try to start the recording, I read this message " tutti i registratori sono occuapati"
how can i do the solve the problem?
tnanks

**Comment by rosa2** [comment]
_tutti i registratori sono occuapati_ means in Italian that all recordings are busy. It looks like that server has a limited number of rooms recording, I would say.
Could you give more details, please?

**Comment by enricaardissino** [comment]
is there too much traffic, maybe? Should I try later?
thanks

**Comment by campelo** [comment]
Duplicate of #6257

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
