### ISSUE TITLE
Timeouts for apt-key

### ISSUE THREAD

**Issue by bredereck** [jitsi/jitsi-meet#6232]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- wget https://download.jitsi.org/jitsi-key.gpg.key produces timeouts

## Current behavior
--- timeouts

## Expected Behavior
--- no timeouts

## Possible Solution
--- Fix the file.

## Steps to reproduce
--- wget https://download.jitsi.org/jitsi-key.gpg.key produces timeouts

# Environment details
--- Any.

**Comment by bakie** [comment]
I also faced this issue very frequent during the day. When I test it now (in the evening) I don't seem to get anymore timeouts. So they either fixed the problem or the load on the servers was to high to cope with all the traffic generating timeouts at random times.
