### ISSUE TITLE
GRABACION EN JITSI MEET

### ISSUE THREAD

**Issue by NUEVODIA** [jitsi/jitsi-meet#6234]
No funciona la grabación en Jitsi Meet

**Comment by JuanVqz** [comment]
@NUEVODIA said the record is not working on jitsi meet, I asked for more information.

@NUEVODIA Estaria bueno que dieras mas detalles, donde esta instalado? que versiones tienes? en el navegador, en el celular, etc. todo lo que creas importante y que ayude a encontrar una solución.

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
