### ISSUE TITLE
Add ability to invite people by JID

### ISSUE THREAD

**Issue by wiktor-k** [jitsi/jitsi-meet#6235]
**Is your feature request related to a problem you are facing?**
As there are [more](https://github.com/siacs/Conversations/tree/jingle) and [more](https://siskin.im/) XMPP clients that do have native Jingle audio/video calling I'd like to invite a participant knowing their JID to avoid the need to install separate Jitsi app.

**Describe the solution you'd like**
I'd like to have additional option: `Invite by JID` where I'd put the JID in question and have that person invited. (This could also check in contact book for contacts that do have Jabber field filled in).

**Describe alternatives you've considered**
The only alternative is to ask them to install Jitsi Meet or to use phone calling.

Allowing other XMPP clients to dial-in to Meet would help interoperability between clients!

Thank you for you work and time!

**Comment by damencho** [comment]
This is currently not possible as no of the clients supports the custom IQs we have, like inviting jicofo in a meeting, adding custom extensions for mute/unmute status, custom IQs requesting muting and so on.

**Comment by wiktor-k** [comment]
Thanks for commenting @damencho! Is there a documentation somewhere that lists the custom XMPP extensions used by Meet? (I did have a quick look at the [doc](https://github.com/jitsi/jitsi-meet/tree/master/doc) directory but nothing seems matching).

From what you've described some of these could be useful to implement by others and maybe there is still a way for a better compatibility here...

**Comment by damencho** [comment]
There is no docs about that other than running jitsi-meet. You can open a conference with 2 participants and then add a third one and do mute/unmute and you can dump all the XMPP traffic by executing js in the console `APP.conference.saveLogs()`

**Comment by damencho** [comment]
And there are many other cases like announcing that there is a recording which also comes from presence ...

**Comment by wiktor-k** [comment]
> you can dump all the XMPP traffic by executing js in the console APP.conference.saveLogs()

Sounds like a good place to start, thanks @damencho :+1:

**Comment by Neustradamus** [comment]
Hope more XMPP in @Jitsi...

People wait since several years ago...

**Comment by iNPUTmice** [comment]
[Conversations](https://github.com/siacs/Conversations) developer here. I’d be interested in adding support for custom Jitsi extensions (within reason) if there is some genuine interest on your side in allowing actual XMPP clients to join a Jitsi Meet call. I’m not interested in a one sided reverse engineering fest but if we can make this somehow a collaborative effort I think that could be a pretty cool feature.

**Comment by damencho** [comment]
@iNPUTmice I will bring that question to the team and will come back to you.

**Comment by damencho** [comment]
The official statement is that you should use the provided APIs, the mobile or iframe one to create meetings.

Using directly the xmpp and muc is not encouraged for a few reasons: we had seen in the past buggy implementation causing a lot of trouble and we needed to block them at some point. We may change the protocol breaking your work totally, that's why everything is encapsulated in those APIs. You are free to experiment with it on your deployments.

So I'm closing this issue now.
