### ISSUE TITLE
Weird behaviour with Jitsi Meets Library when button is in form.

### ISSUE THREAD

**Issue by nedimf** [jitsi/jitsi-meet#6236]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

## Description
---
Problem with calling jitsi instance from browser on click of button . Normal calling on function works. 

## Current behavior
---
Jitsi does nothing, not even initialise. Weird thing is that, function is working fine.

## Expected Behavior
---
Showing meeting room with all configuration code.
Weird thing is, this is worked 2 days ago. I don't know if you guys changed anything in external api js file.

## Possible Solution
---
No idea, I have debugged as much as I could.

## Steps to reproduce
---
Create function 
```javascript
document.getElementById("button").addEventListener("click", meeting);
var api;
function meeting(){
  const domain = 'meet.jit.si';
  const options = {
      roomName: 'name',
      width: "100%",
      height: "70%",
      parentNode: document.querySelector('#meet-one'),
      interfaceConfigOverwrite: { DEFAULT_BACKGROUND: "#212529",    DEFAULT_REMOTE_DISPLAY_NAME: 'remotename',
      DEFAULT_LOCAL_DISPLAY_NAME: 'ja' ,TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'desktop', 'fullscreen',
        'fodeviceselection', , 'profile', 'chat',
        'settings', 'raisehand',
        'videoquality', 'filmstrip', 'stats',
        'tileview'
    ]}
  };
  api = new JitsiMeetExternalAPI(domain, options);
}

```
[Fiddle](https://jsfiddle.net/nedimf/vLzumq71/5/embedded/html,result/)
# Environment details
---
localhost:3000
Express
Node v13.5.0
MacOS 10.15.13

**Comment by nedimf** [comment]
My last post, did not show HTML code.  I had been struggling  with this for few hours.
I have discovered error is in receiving calling function from ``` <form>```.

I have created [Fiddle](https://jsfiddle.net/nedimf/3wajoe7n/3/embed/html,result/dark)

### Fix:
Get button out of form.

**Comment by saghul** [comment]
https://stackoverflow.com/questions/2825856/html-button-to-not-submit-form
