### ISSUE TITLE
Jicofo Secure Domain and user authentication lifetime ??

### ISSUE THREAD

**Issue by Toky77** [jitsi/jitsi-meet#6238]
Hi Jitsi Staff,

We have a fresh install of jitsi meet  server under Debian 10. We configured the jicofo secure domain to authenticate users. User can create a conference with anonymous guest. Everything works fine.
But there is a curious problem about the user authentication lifetime and I'll try to describe the issue below all steps : 
1 - User create a conference and Jitsi asks for an authentication as a Host
2 - Once authenticated, Conference has created
3 - Once the conference  finished, the host ends the conference and closes his browser
4- If the host decides to create a new conference, Jitsi meet doesn't longer ask an authentication .

Sorry for my english.

Toky

**Comment by damencho** [comment]
Please when having questions or problems use the community forum before opening new issues.

You can disable auto-login in jicofo or lower the timing of expiring those.
https://community.jitsi.org/t/easiest-way-to-secure-jitsi-meet/21330/43?u=damencho

**Comment by Toky77** [comment]
Thanks a lot for your quick help.
Regards
