### ISSUE TITLE
I can't record

### ISSUE THREAD

**Issue by ZellinhaMariah** [jitsi/jitsi-meet#6240]
Hello, my name is Roselle,
I started ti use this plataform today, but I just can't record my classes. What I have to do, how can we fix this?

**Comment by jacobgonzales20** [comment]
#5403

**Comment by l3d00m** [comment]
Hi,
If you have an issue with recording, please report it in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
