### ISSUE TITLE
la mia  telecamera non funziona

### ISSUE THREAD

**Issue by mariateresaborra** [jitsi/jitsi-meet#6243]
la mia  telecamera HPTRUEVISIONHD(064e:c345) non funziona e non posso fare riunioni con la mia classe qualcuno mi aiuta?
Grazie
Maria Teresa Borra

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
