### ISSUE TITLE
Camera only provides 4:3 video after upgrade from 1.0.3992 to 1.0.4025

### ISSUE THREAD

**Issue by ElectronicWar** [jitsi/jitsi-meet#6244]
## Description
---
I am running jitsi-meet on Debian 10 behind Nginx using the official Jitsi deb packages on the stable channel.

After upgrading from my previous stable version 1.0.3992 to the latest release 1.0.4025, most cameras of my regular users are now only showing a 4:3 image instead of the usual 16:9. This includes my own camera (Logitech C920).

Downgrading to previous stable 1.0.3992 fixes the issue.
Using meet.jit.si also works, it seems to run 1.0.4020 instead of 1.0.4025.

I am happy to test unstable or test builds any time as it's not a vital system.
Latest nightly from today (unstable deb repo) still shows the issue.

https://test.webrtc.org/ returns a green checkmark for all tested resolutions, including 1280x720.

## Current behavior
---
Camera only shows 4:3 aspect ratio video

## Expected Behavior
---
Camera shows proper 16:9 aspect ratio video

## Possible Solution
---
Downgrading to 1.0.4020 or older

## Steps to reproduce
---
Join a meeting, enable camera. It will only show a 4:3 image.

# Environment details
---
* Server:
  * Root Server with Debian 10
  * Jitsi debian packages from "stable" channel
  * Nginx 1.16.1
* Client:
  * Windows 10
  * MS Edge (Chromium) - also tested with Google Chrome and Firefox Developer Edition
  * Logitech C920

**Comment by yodaphone** [comment]
edit the /etc/jitsi/meet/meet.mydomain.com-config.js (OR something like that) file, & go to the "Video" section & paste this. please be sure to use spaces properly

```
    startBitrate: 500,
    resolution: 720,
    constraints: {
         video: {
            aspectRatio: 16 / 9,
            height: {
                ideal: 720,
                max: 720,
                min: 240
            }
         }
    },

```

**Comment by ElectronicWar** [comment]
Thanks, updating the config file did the trick. Although I am not sure why Jitsi would switch to 4:3 on the default config now as it's whole interface is made for 16:9 video 🤷‍♀️
