### ISSUE TITLE
phoneNumberList documented json format not accepted

### ISSUE THREAD

**Issue by jbf920** [jitsi/jitsi-meet#6246]
phoneNumberList json formatted is documented here:
https://github.com/jitsi/jitsi-meet/blob/master/doc/cloud-api.swagger

https://community.jitsi.org/t/solved-phonenumberlist-format-for-non-us-numbers/18040/3
Per discussion this is supposed to be valid json:
`[
    {
        "countryCode": "US",
        "tollFree": true,
        "formattedNumber": "+1 555-000-6425"
    },
    {
        "countryCode": "US",
        "tollFree": false,
        "formattedNumber": "+1 555-000-6427"
    }
]`

When providing json of this format, a JS error produces like so:
`2020-04-20T22:13:01.302Z [features/invite] Error encountered while fetching dial-in numbers: undefined`

A demonstrating example can be found at meet dot ops dot one jitsi instance.

A demonstrating example of correctly formatted json can be found at
https://meet-api.ops.one/phone_numbers.php

**Comment by jbf920** [comment]
As further clarification I suggest the issue is located here:  the !id and !conference calls are breaking the parsing, when phoneNumberList json does not require them.

https://github.com/jitsi/jitsi-meet/blob/b706972acb222dea24894cd5d7f052995217f33c/react/features/invite/actions.any.js#L182

@damencho I would humbly request your help as the guru

**Comment by damencho** [comment]
> [ { "countryCode": "US", "tollFree": true, "formattedNumber": "+1 555-000-6425" }, { "countryCode": "US", "tollFree": false, "formattedNumber": "+1 555-000-6427" } ]

I just pasted the snippet above on my test instance and it works fine

**Comment by jbf920** [comment]
What do you mean by pasted? Are you running latest jitsi-meet from debian apt packages, and can you look at the JS error above? I've spent more than 12 straight hours trying to debug this problem, I'm fairly sure it's a bug. Happy to be wrong but I need more detail.

**Comment by jbf920** [comment]
https://meet-api.ops.one/phone_numbers.php

I updated that endpoint to have the exact JSON as per above, still seeing the issue  

`2020-04-20T22:54:56.922Z [features/invite] Error encountered while fetching dial-in numbers: undefined`

**Comment by damencho** [comment]
I saw, I use latest and I have used the same json and it works fine. Same format is used on 8x8.vc you can test it your self there.

**Comment by damencho** [comment]
Maybe your problem is in the config js ...

**Comment by jbf920** [comment]
You are right, the issue was in config.js. Specifically, where the two lines that follow were in the file; they had to go after the p2p block. 

`        // How long we're going to wait, before going back to P2P after the 3rd
        // participant has left the conference (to filter out page reload).
        // backToP2PDelay: 5
    },
	
	// customize/config.js
    dialInNumbersUrl: 'your_url',
    dialInConfCodeUrl:  'your_url',
	
    analytics: {`
