### ISSUE TITLE
youtube livestreaming error: connect streaming software to start preview 

### ISSUE THREAD

**Issue by cad0p** [jitsi/jitsi-meet#6248]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Hi, this is my first time trying Jitsi for livestreaming (I used to use hangouts on air, since discontinued of course).

I only managed to make it work using the legacy version of the youtube stream now, not the new "live dashboard"

---

## Current behavior
When using the new design of the live dashboard, the stream connected successfully but failed to show a preview (so it refused to start streaming).

The error was:
```
    connect streaming software to start preview 
```
---

## Expected Behavior
That the livestreaming would work on both ways (I understand it may be YouTube's problem but it's worth investigating IMHO

---

## Possible Solution
For now, just use the old interface

---

## Steps to reproduce
Go to the new live dashboard, paste the stream key from Jitsi.

---

# Environment details
Chrome on Mac OS 10.14

---

**Comment by Echolon** [comment]
I will close this with reference to this: #5146
See also: #5403

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
