### ISSUE TITLE
Own video in Firefox upside down

### ISSUE THREAD

**Issue by spacemanspiff2007** [jitsi/jitsi-meet#6256]
When I join a conference the video from my built in webcam of my laptop is upside down.
I tried the video settings but I can't seem to find an option how to rotate it by 180°.
This makes the webcam pretty much unusable for me.

When I start a webcam control program the video shows fine and in upright position.

**Comment by rcsarv** [comment]
is it only Firefox or try another browser like chrome and o=post your responce
