### ISSUE TITLE
All recorders currently busy

### ISSUE THREAD

**Issue by rolllo** [jitsi/jitsi-meet#6257]
![Jitsi-Jibri-busy](https://user-images.githubusercontent.com/9165865/79844867-911e6500-83bc-11ea-8cde-626e7a3cdf44.png)

2020-04-21T08:35:00Z

**Comment by rcsarv** [comment]
These days jit.si facing huge traffic, and recording only possible one recording per instance so all servers are busy.
Try self-hosted server.
More for information visit https://github.com/jitsi/jitsi-meet/issues/6265#issuecomment-617109651

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
