### ISSUE TITLE
Recorder are not available

### ISSUE THREAD

**Issue by cedric2606** [jitsi/jitsi-meet#6258]
Hello, bonjour
I have a problem with Jitsi, no recorder available....
What can I do?

Thnks

**Comment by rcsarv** [comment]
These days jit.si facing huge traffic, and recording only possible one recording per instance so all servers are busy.
Try self-hosted server.
More for information visit https://github.com/jitsi/jitsi-meet/issues/6265#issuecomment-617109651

**Comment by campelo** [comment]
Duplicate issue #6257

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
