### ISSUE TITLE
youtube livestreaming error: all streamers are currently busy

### ISSUE THREAD

**Issue by mrclean06** [jitsi/jitsi-meet#6265]
hi 

When i try to stream on my youtube channel.. an error message will be appered : 
all streamers are currently busy

do you know how to stream my visionferency on my tv channel .. please

**Comment by AliKarpuzoglu** [comment]
look at this issue: #5403

**Comment by rcsarv** [comment]
These days jit.si facing huge traffic, and recording only possible one recording per instance so all servers are busy.
Try self-hosted server.

**Comment by campelo** [comment]
duplicate of #6249

**Comment by luixxiul** [comment]
Do you experience the issue yet?
