### ISSUE TITLE
conference timer always begins with 1 hour 

### ISSUE THREAD

**Issue by GiorgioBart** [jitsi/jitsi-meet#6269]
## Description
conference timer always begins with 1 hour 

## Current behavior
conference timer always begins with 1 hour 
![photo_2020-04-21_13-10-50](https://user-images.githubusercontent.com/23031295/79867006-f20a6500-83dd-11ea-846e-2a1714347404.jpg)
It was 10:24 minutes
## Expected Behavior
conference timer always begins with 0 hour 

## Possible Solution
---

## Steps to reproduce
---

# Environment details
jitsi-meet/stable,now 2.0.4468-1 all [installed]
on 
Ubuntu 18.04.4 LTS

**Comment by damencho** [comment]
Duplicate https://github.com/jitsi/jitsi-meet/issues/5595
