### ISSUE TITLE
All Recorders are currently busy

### ISSUE THREAD

**Issue by holadiego** [jitsi/jitsi-meet#6272]
Hi, 
Im looking forward to record some meetings and I have continually the same problem 

"All recorders are currently busy", does anyone knows what can I do?
Im using the on line version meet.jit.si

**Comment by rcsarv** [comment]
These days jit.si facing huge traffic, and recording only possiable one recodring per instance so all servers are busy.
Try self hosted server.

**Comment by campelo** [comment]
duplicated #6257

**Comment by l3d00m** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
