### ISSUE TITLE
Create server status page

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6274]
**Describe the solution you'd like**

Please create a server status page. it will help users to troubleshoot or at least understand what is going on. It will also reduce a bunch of duplicates related with "all recorders are busy", "grabación", etc.

It does not need to be elegant as all of the team members seems so busy. Just a list of busy servers, how many of the total servers are full is enough.

**Describe alternatives you've considered**

Use Twitter to tell people what is going on. Any official announcement will help.

**Comment by malix0** [comment]
I deduce that at the moment there is no way of knowing if the server is working properly?
