### ISSUE TITLE
no option to grant access to microphone and camera in firefox

### ISSUE THREAD

**Issue by TheGoldmasterCorporation** [jitsi/jitsi-meet#6275]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
i create a meeting name then click go and get presented with some kind of call screen. which is fine but cant unmute the microphone or camera.

## Current behaviour
no option in firefox to grant access to microphone and camera

## Expected Behavior
firefox should how do want to allow this website access to camera and microphone.

## Possible Solution
a grant access button and an option to invite people. via a link, like how zoom works.

## Steps to reproduce
using the latest version of firefox stable and go to start a new meeting and then don't get an option to grant the firefox option to use a microphone and camera. I have tried turning on and off tracking protection and ublock origin with no difference.

# Environment details
windows 10 pro and firefox 64 bit

**Comment by l3d00m** [comment]
Is this still happening?

**Comment by TheGoldmasterCorporation** [comment]
Hi there it seems to be working ok now. Great that we don't need a
desktop version. But do keep an eye incase someone else gets the same
issue. I will recommend jitsi over zoom.

**Comment by l3d00m** [comment]
Happy to hear that! I'll close the issue then, but feel free to reopen in case it happens again
