### ISSUE TITLE
Unable to use share your screen in chrome

### ISSUE THREAD

**Issue by jgrocha** [jitsi/jitsi-meet#6276]
## Description

I'm not able to use "share your screen" in Chrome. It works in Firefox, but not in Chrome.

Possible related to #4955, but I don't use Rocket.Chat (don't know what it is).

## Current behavior

When I try to share the screen in Chrome, nothing happens in the interface. No popup panel is displayed.

On the console, I get the following errors:
```
2020-04-21T17:28:58.918Z [modules/RTC/RTCUtils.js] <z.newObtainAudioAndVideoPermissions>:  Using the new gUM flow
Logger.js:154 2020-04-21T17:28:58.919Z [modules/RTC/ScreenObtainer.js] <Object.obtainScreenFromGetDisplayMedia>:  Using getDisplayMedia for screen sharing
Logger.js:154 2020-04-21T17:28:58.920Z [features/base/tracks] Failed to create local tracks ["desktop"] s {name: "gum.chrome_extension_user_canceled", message: "User canceled Chrome's screen sharing prompt", stack: "Error↵    at new s (https://web-cdn.jitsi.net/meet…77/libs/lib-jitsi-meet.min.js?v=4020.672:1:165460"}
o @ Logger.js:154
(anonymous) @ functions.js:123
...
Logger.js:154 2020-04-21T17:28:58.921Z [conference.js] <Object.toggleScreenSharing>:  Failed to switch to screensharing s {name: "gum.chrome_extension_user_canceled", message: "User canceled Chrome's screen sharing prompt", stack: "Error↵    at new s (https://web-cdn.jitsi.net/meet…77/libs/lib-jitsi-meet.min.js?v=4020.672:1:165460"}
o @ Logger.js:154
toggleScreenSharing @ conference.js:1566
...
```

Audio and video sharing works perfectly. It is my meeting favorite software.

## Expected Behavior

It should display a panel to choose the window/display to share.

## Possible Solution

It might be related to permissions, but I don't know what to do. I've tried many options in Chrome settings, but not able to make it work.

From the error message, it seems like my fault:
```
User canceled Chrome's screen sharing prompt
```
I didn't cancelled anything (I think!).

## Steps to reproduce

Open https://meet.jit.si/anymeeting and try to share the screen. Nothing happens. Just the error in the console.

# Environment details

Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Ubuntu 19.10, using X11 (not wayland)

I'm using https://meet.jit.si, not a self deployed service.

I've also installed Jitsi Meetings 0.2.8.14 Chrome extension, but I didn't notice any difference.

With Firefox 75.0 (64-bit) it works, but sometimes hangs/freezes at start.

**Comment by jgrocha** [comment]
Maybe related to this: https://lists.w3.org/Archives/Public/public-webrtc/2019Mar/0058.html

**Comment by jgrocha** [comment]
Upgrading from Chrome Version 73.0.3683.103 (Official Build) (64-bit) to Version 81.0.4044.129 (Official Build) (64-bit) solved the issue.

**Comment by raghav-khunger** [comment]
If you are in MAC you need to go to 

Security & Privacy >> Screen Recording

Check the checkbox against Chrome to allow Chrome to share your screen.

![image](https://user-images.githubusercontent.com/904902/81284695-10c65800-907c-11ea-87ce-db738493e1a6.png)
