### ISSUE TITLE
interface customizations are lost on jitsi update

### ISSUE THREAD

**Issue by mehdyhaghy** [jitsi/jitsi-meet#6279]
Jitsi update replaces 
/usr/share/jitsi-meet/interface_config.js 
and watermark.png so we lose all the customizations after each update.
interface_config.js  should be treated like other config files and shouldn't be overwritten on update/upgrade

**Comment by Syonyk** [comment]
Agree, was actually about to file a similar issue.

It would be sane to put the interface_config.js file in /etc, or to allow an override in /etc.  The same is true for the watermark - it should either be not overwritten if changed, or there should be a way to point to another one (from a config file that's not overwritten).

**Comment by damencho** [comment]
We have a plan of re-organizing configurations of the web, but we could not get to doing it. And one of the tasks is to make sure everything is in /etc/.

There is an easy workaround you can do by yourself, putting the interface_config and the image you want in /etc and create a location in the web config as the one that already exists for config.js and your changes will not be lost as those will be in /etc/

**Comment by Syonyk** [comment]
@damencho Poking through the config files, I'd come to roughly the same conclusion - interface_config.js and watermark.png should be in /etc/jitsi/meet, with the proper aliases configured and the install scripts updated to point to these new locations.  It's not very many changes in the overall installer setup.

I'll put a PR together for those changes and push it up, you can take a look.

**Comment by damencho** [comment]
Yep, I agree for interface_config, but I would not touch the images

**Comment by Syonyk** [comment]
I'm only thinking of moving watermark.png over.  I'm also tired of copying our custom logo into /usr/share/jitsi-meet when someone asks why it's back to the default.

What about something like this in the nginx config?

```
    location = /images/watermark.png {
        try_files /images/local_watermark.png /images/watermark.png =404;
    }
```
I'm afraid I don't know how to do this for Apache, but if you put a local_watermark.png file in /usr/share/jitsi-meet/images, it shouldn't overwrite it on updates.  If that file is present, it will be returned as the watermark.  If not, the default watermark will be returned.

**Comment by Syonyk** [comment]
PR created, please take a look and see if that's along the lines of what you were thinking.

**Comment by laryllian** [comment]
> I'm only thinking of moving watermark.png over. I'm also tired of copying our custom logo into /usr/share/jitsi-meet when someone asks why it's back to the default.

Sure, but also the custom url will be reset, so I would prefer a "real" solution. ;)

**Comment by MagicFab** [comment]
I'd like to suggest a new bug tag "dataloss" to be able to increase the priority/importance of these issues. I'll be tagging forum posts about this issue with "dataloss" (similar to "lost recording when using Dropbox")

Until there is a fix in the current packaging / implementation, someone had published a configuration backup / recovery script for this precise situation : 

https://github.com/AndreStemmann/Jitsi-Meet-Scripts

**Comment by johnxie** [comment]
Any updates on this?

**Comment by maulanayusupp** [comment]
I wanna upgrade the jitsi but im afraid if my configration gone or reset to default after upgrade
any suggestion how to safe upgrade without losing my configuration?

**Comment by brrrrrrrt** [comment]
i am not very familiar with the possibilities of dealing with javascript config files, but i work alot with different "config files systems". to me the most convenient way is to have something like ".local" files which override the default config files which come from the vendor/distribution. the local files include only those settings you want to change, so if the vendor or distribution adds new settings or changes defaults you will not have to revise your "localized" version of the config file which can be a real PITA on every update.

**Comment by dasani08** [comment]
I hosted jitsi on my owner private server then can I remove jitsi watermark logo? Is it legal or not?
Thanks guys.

**Comment by joho1968** [comment]
I realize there's some work involved in this, but it would be nice if Jitsi updates/upgrades did not overwrite *any* files at all.

IMHO, it'd be better to have ".dist" or ".conf.default" handling of configuration files and directories, for everything.

**Comment by coccochanel** [comment]
what i understand is we have this file https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js with all options, but the only editabled are the options in this file: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config
/interfaceConfigWhitelist.js

where i can find the last file in my server? i need the link (for ex: /etc/...).

thanks in advice

**Comment by approached** [comment]
Just bind the new config with *${CONFIG}/web/custom_interface_config.js:/defaults/interface_config.js*.

Docker-compose example:
```
version: '3'

services:
    # Frontend
    web:
        image: jitsi/web:latest
        restart: ${RESTART_POLICY}
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
            - ${CONFIG}/web/custom_interface_config.js:/defaults/interface_config.js:Z
```

Reference: https://github.com/jitsi/docker-jitsi-meet/blob/e5746ae0f42cca0aacfda24ecfffb65f08787ae6/web/rootfs/etc/cont-init.d/10-config#L77

**Comment by erikvanoosten** [comment]
I described workaround on my blog for the case you deploy with Docker: https://day-to-day-stuff.blogspot.com/2021/12/customizing-jitsi-meet-ui-in-docker.html

**Comment by akk796** [comment]
Not sure if it is a real fix, but it worked pretty well for me. I made a folder in my /etc directory called "custom-jitsu-files". I then copied any of my custom Jitsi config files to this folder. I updated Jitsi after, then copied the files from the new directory (which will remain untouched by updates) to the Jitsi directories in /usr/share/jitsi-meet. After clearing my browser cache everything was correct again and it really took maybe 10-minutes. That is the quickest solution I came up with.

1. Make a folder in your /etc directory (mkdir *custom folder name*)

2. Copy Customized Jitsi Files in /usr/share/jitsi-meet (cd /usr/share/jitsi-meet; cp interface_config.js; cp css/all.css; cp images/watermark.png; cp images/welcome-background.png /etc/*custom folder name*)

3. Update Jitsi (I personally use cockpit but "sudo apt-get update -y" should work for you).

4. Replace the updated config files that you previously saved back to the /usr/share/jitsi-meet directories (cd /etc/*custom folder name*; cp interface_config.js /usr/share/jitsi-meet; cp all.css /usr/share/jitsi-meet/css; cp watermark.png /usr/share/jitsi-meet/images; cp welcome-background.png /usr/share/jitsi-meet/images)

5. Reboot your server (reboot)

6. If you launched your server in the web browser after updating and the changes don't look like they worked close the webpage, clear your browsing data and relaunch the webpage. It should have your custom layout back in action.

**Comment by damencho** [comment]
> 2\. cp interface_config.js; cp css/all.css; cp images/watermark.png; cp images/welcome-background.png

For everything there you can have a custom location in your nginx config to serve those files from other folder like the config.js 
https://github.com/jitsi/jitsi-meet/blob/43f554295e36403c66e0ca45e7422b0db335d887/doc/debian/jitsi-meet/jitsi-meet.example#L59

The all.css one you should not do that, you are basically reverting the CSS to an older version which in most cases will result in a broken UI.

**Comment by akk796** [comment]
> jitsi-meet/doc/debian/jitsi-meet/jitsi-meet.example

This is a perfect way to get around the issue. Thanks for sharing. In regards to the all.css is there any way possible to preserve changes without overriding it? For example I removed the footer pointing to app downloads, so it the update re-enables that and other things that have been adjusted (such as custom text) it'd be a bit inconvenient. 

Thanks for all your help btw I've read tones of discussions on Jitsi where you provided the answer that put me on the right path.

**Comment by damencho** [comment]
You can use fonts.html to add your custom CSS that will override the original one.
https://github.com/jitsi/jitsi-meet/blob/43f554295e36403c66e0ca45e7422b0db335d887/index.html#L12
You can also do the location thingy and for that file so you serve the content from a file that is not in /usr/share/jitsi-meet. You need to avoid touching /usr/share/jitsi-meet and leave the upstream update without wiping your modifications.

**Comment by akk796** [comment]
> You can use fonts.html to add your custom CSS that will override the original one.
> 
> https://github.com/jitsi/jitsi-meet/blob/43f554295e36403c66e0ca45e7422b0db335d887/index.html#L12
> 
> 
> You can also do the location thingy and for that file so you serve the content from a file that is not in /usr/share/jitsi-meet. You need to avoid touching /usr/share/jitsi-meet and leave the upstream update without wiping your modifications.

Awesome! Thank you so much again. Appreciate you.
