### ISSUE TITLE
The app can't open the camera in chrome

### ISSUE THREAD

**Issue by MachinEmmus** [jitsi/jitsi-meet#6280]
hi developers i need help to the problem to use the camera in a virtual session why my Pc can't open the camera but this is ready to use mi SO is windows 8.1 a try restarting the camera but dont function

**Comment by yodaphone** [comment]
what virtualization platform are you using? if virtualbox read this

https://scribles.net/using-webcam-in-virtualbox-guest-os-on-windows-host/

**Comment by MachinEmmus** [comment]
Thanks @yodaphone
