### ISSUE TITLE
iOS app not disconnecting(objc-version)

### ISSUE THREAD

**Issue by ciufab** [jitsi/jitsi-meet#6282]
I've succesfully imported and used Pods for the objective c project.
Everything works fine(I just had to set the identifier of the storyboard segue to "joinConference" - otherwise I would always get "the room is nul" error).
Once i hit the hangup button the app remains stuck at a waiting screen indefinitely...any suggestions on what to watch for?

**Comment by saghul** [comment]
Please try the SDK samples. I reviewed all of them this morning and haven't found such issue.
