### ISSUE TITLE
SIN ACCESO A CÁMARA JITSI

### ISSUE THREAD

**Issue by KAROLINALEAL** [jitsi/jitsi-meet#6287]
Buenas noches 
Realizó videoconferencia por otras plataformas como Zoom y Google Meet y funciona sin problemas audio y video, sin embargo en JITSI no es asi, me funciona siempre audio pero video no, estan activos los permisos desde la configuración de Google Chrome y aun desde la configuración del pc a la aplicación Jitsi pero no me es posible activar el video.
Que puedo hacer en este caso?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/5425
