### ISSUE TITLE
Jitsi meet on an already running web server?

### ISSUE THREAD

**Issue by egoipse** [jitsi/jitsi-meet#6289]
Hi,

I have a running web server (Ubuntu 18.04) for a couple of webpages and I've tried to install a jitsi meet instance there. Everything was fine until tried to load the FQDN hostname url on my browser. When doing that, the webpage of my main domain was loaded. In other words, the same webpage hosted on example.com was loaded on server.example.com (the hostname) request. It wasn't loaded the jitsi meet page, which it supposed to load as it is explained in [this video](https://jitsi.org/blog/new-tutorial-installing-jitsi-meet-on-your-own-linux-server/) and [these instructions](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md).

Is it possible to do what I'm trying to do? Or do I need a server exclusively dedicated to jitsi meet? In case it is posible to do what I'm trying, how to solve this issue? Some dns record? Some hack? Some conf file to update? Some line on virtualhost?

Thanks in advance for any help.

**Comment by Snowman-25** [comment]
Hello egoipse,
I had the same problem when using ISPConfig 3. You first have to teach your server to NOT serve its standard webpage.
Should you also be using ISPConfig3, go to ``Sites --> Websites --> <your domain> --> Domain``.
From there you set ``IPv4-Address`` (and ``IPv6-Address``, should you have one) to ``*``
and ``Auto-Subdomain`` to ``None``.

**Comment by egoipse** [comment]
Thanks for your answer @Snowman-25.

I work with virtualmin. I'll check how to replicate there what you did in ISPConfig3. Meanwhile, your answer is very useful to know that it is possible to get this issue solved. Otherwise, I'd have to search for another solution.

Thanks again.

Kind regards!

**Comment by celocore** [comment]
@egoipse 

You can also create an own web for server.example.com and access your jitsi installation via ProxyPass requests.

**Comment by dab0u** [comment]
I'm sooo interested on this subject too !
Here, I have a debian 10, ispconfig 3, on a dedicaded server from OVH (with some websites installed as well) and I can't install jitsi-server ... :( .
I'm sure it is about the FQDN question that I really don't understand.

I tried to add it to /etc/hostname and /etc/hosts but it didn't work... (but I'm sure I'm beginning to destroy my server configuration too ! :S ) 
Do we have to create a website in ispconfig before installing jitsi-meet ? (As I see 2 files in /etc/apache2/sites-available/ now... One from ispconfig, one from jitsi-meet installation...)
Do we have to modify /etc/hostname or /etc/hosts ?
The "FQDN" should be the url we want to use, like video.mydomain.org ? or it is the name of the server, like ns-server1234.ovh.net (That I can see in hostname) ?

**Comment by Snowman-25** [comment]
Hey @dab0u,
Running ISPConfig3 on Debian 9, here's what I did:

As I said above, set your domain to listen on ANY IP-Address (Asterisk, not sure if necessary) and Auto-Subdomain to `None`. Also activate SSI on the same page (`Sites --> <your domain> --> Domain`).
Doing that should give you the "Apache 2 Debian Default Page" when going to a subdomain that you don't have registered.

Create a subdomain for your jitsi-instance but don't set it to active. This is just for parking purposes so you don't try to use the subdomain later on.

I've edited the following line of my /etc/hosts like this:
`127.0.0.1        localhost <video.mydomain.com>`
You don't have to touch your `/etc/hostname`

Now install jitsi from the repo, providing the FQDN for the domain (video.mydomain.com). Basically follow the quick-install guide.

Make sure that there's a config-file at `/etc/jitsi/meet/<domainname>-config.js`

You'll get a grey page if you open the subdomain now. In the console you'll see a warning that `interface_config` wasn't defined.
Navigate to `/usr/share/jitsi-meet/` create a `.htaccess` and put `XBitHack on` in it.
Now execute `find . -name \*.html | xargs chmod o+x` to mark all HTML-files as Executable, which will allow SSI to work with them (thanks to `XBitHack on`).

Your Jitsi-instance should now work.

I had some additional problems where the server couldn't find the config.js so I created a new one directly in /usr/share/jitsi-meet and tweaked that until it worked. I later found it to not be necessary anymore, as the appropiate `/etc/jitsi/meet/<domainname>-config.js` was in place.

Best of Luck!
Andreas

**Comment by dab0u** [comment]
Really thanks you... but it doesn't work for me :( .
Let's see : domain.org is already used on this server. I want to use video.domain.org for jitsi. (I added my IP in my DNS area, on OVH, that seems to be fine.)
Did you mean I need to create a subdomain in Ispconfig ? And not a "normal" domain for video.domain.org ? (which I usually do, for my others subdomains...) But then, why do you create this main domain ? And with SSI ?

Moreover, I modified my /etc/hosts, but I'm not sure about it :+1: 
`127.0.0.1       localhost       video.mydomain.org 
127.0.1.1       nsxxxxxxx.ip-xx-xx-xx.eu        nsxxxxxxx       video.mydomain.org 
::1     localhost       ip6-localhost ip6-loopback 
ff02::1 ip6-allnodes 
ff02::2 ip6-allrouters 
xx.IP-SERVER.xx    nsxxxxxx.ip-xx-xx-xx.eu        nsxxxxxx`
And I used  `invoke-rc.d networking force-reload` and `invoke-rc.d hostname.sh start` to reload it.
But `ping "$(hostname)"` still show me : 
`PING nsxxxxxx.ip-xx-xx-xx.eu (127.0.1.1) 56(84) bytes of data.
64 bytes from nsxxxxxx.ip-xx-xx-xx.eu (127.0.1.1): icmp_seq=1 ttl=64 time=0.037 ms`

When I try to see video.mydomain.org, I'm still on the webserver default page.

**Comment by dab0u** [comment]
Ho it works !!! 

A new day, a new view. I read again your message.
As I said, The domain.org was already configured a long time ago and I didn't think about changing it. Then, as you said, I set "Auto-subdomain" to none (It was on "any") and tick on SSI and all works perfectly ! 

I don't really understand why all of this, but it works, so great thank to you ! :) @Snowman-25

**Comment by egoipse** [comment]
That's a great @dab0u !!!

I finally took drasticall measures: to make a fresh resinstallation of my web server, with a new and receantly bougth domain name to avoid fqdn conflicts. So, the jitsi-meet server is finally running, nicely running here: servidor.sirviendo.me

Thanks for all the help @Snowman-25 ... Your patience and generosity was the key for me and for @dab0u to solve our issues.

**Comment by dab0u** [comment]
Except that it doesn't work well for now :D .
It works if I'm alone... a friend can connect from a computer and we see we are connected each other, the chat work aswell, but we can't see the video of the other one (only our's). 
Moreover, it doesn't work from the android app. We are disconnected just at the start... 

Well, I haven't take time to search about it. I'll tell you if I find the solution to my problem :+1:

**Comment by Snowman-25** [comment]
> Except that it doesn't work well for now :D .
> It works if I'm alone... a friend can connect from a computer and we see we are connected each other, the chat work aswell, but we can't see the video of the other one (only our's).
> Moreover, it doesn't work from the android app. We are disconnected just at the start...
> 
> Well, I haven't take time to search about it. I'll tell you if I find the solution to my problem +1

Sounds like a firewall problem. Video not working with others might also be a STUN/TURN-Server Problem. Try restarting the jitsi-services

**Comment by dab0u** [comment]
You're right, again ! :)
I checked the firewall (80,443 and 10000 ... is the 4443 needed ?) and restarted the services and it works great for desktop (we tried with 5 users perfectly !) ! I think it was because of the port 10000.

But.... Not with android app... I read that it could be a certificate problem if it is self-signed, but i'm using let's encrypt... I can't access the room from the android app. 
Can you see a solution here too ?

**Comment by dab0u** [comment]
Now it works. Everything works. I'm really happy ;)
The certificate could have been the problem. I executed the command an another time, and now, apps can connect to the jitsi conf.

Thanks for all. This project is awesome and I'll try to help a little for the translation if needed. Thx !

**Comment by l3d00m** [comment]
Happy to hear it now works for you. If you need further support please use the community forum https://community.jitsi.org/ for anything that's not a bug or a feature request.

**Comment by filipposfilippides** [comment]
Andreas THANKS SO MUCH!

**Comment by Xzave** [comment]
I don't understand because I'm under ispconfig and that's not working for me
