### ISSUE TITLE
Unable to Build on Windows 10

### ISSUE THREAD

**Issue by ajaysingh452** [jitsi/jitsi-meet#6290]
While trying to build the Jitsi-meet getting below errors,

+ lib-jitsi-meet@0.0.0
added 67 packages from 26 contributors, updated 1 package and audited 83162 packages in 74.788s
found 5211 vulnerabilities (2825 low, 6 moderate, 2378 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
'make' is not recognized as an internal or external command,
operable program or batch file.

If Anyone can help me to get the solution to be build on Windows platform.

Thank You in advance.

**Comment by 98lenvi** [comment]
@ajaysingh452 , I think you need to run the command either on a Unix based OS or WSL. make sure you have the following installed (in Unix based OS or WSL).

- [ ]  gcc
- [ ]  make

**Comment by campelo** [comment]
> While trying to build the Jitsi-meet getting below errors,
> 
> * lib-jitsi-meet@0.0.0
>   added 67 packages from 26 contributors, updated 1 package and audited 83162 packages in 74.788s
>   found 5211 vulnerabilities (2825 low, 6 moderate, 2378 high, 2 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details
>   'make' is not recognized as an internal or external command,
>   operable program or batch file.
> 
> If Anyone can help me to get the solution to be build on Windows platform.
> 
> Thank You in advance.

I have used WSL on win 10 and works fine! 

![image](https://user-images.githubusercontent.com/4963840/80013528-07929400-849d-11ea-9c4a-8362d172733f.png)

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
