### ISSUE TITLE
Feature request: room url obfuscation

### ISSUE THREAD

**Issue by TxHawks** [jitsi/jitsi-meet#6291]
**Is your feature request related to a problem you are facing?**
When Alice wants to talk to Bob and Carol, they all connect point their browser to https://meet.jit.si/our-secret-hush-hush-call.
An adversary with a rather wide view of a network, such as governments, for instance, or even ISPs in certain cases, can determine who is talking to who, simply by examining the urls they connect to.

**Describe the solution you'd like**
A solution to that could be that instead of relying on a url as the identifier, a user could enter the room id in a form, which then opens the room in the same window context, without performing navigation to a new URL.

This will allow an adversary to know who is using Jitsi, but not who is talking to who

**Describe alternatives you've considered**
Using Tor, or to a lesser degree DOH, but that's technically more complicated for the average user and has some drawbacks:
  * In many places Tor is simply too slow for live video
  * In DOH, You have to trust the DNS relay

**Comment by saghul** [comment]
You are welcome to implement that using lib-jitsi-meet, but I don't think we'll go in that direction for Jitsi Meet. URLs are shared in calendars, the app follows them, etc.

**Comment by TxHawks** [comment]
This is fair enough and thank you for the quick reply. 

From a network analysis point of view, running my own server with this implementation would not be productive, since it will inherently be used by very few people at any given time, and therefore it would be easy to surmise who is speaking to who (anyone connected to the server at a given moment).
