### ISSUE TITLE
Is it possible to redirect jitsi chat conversation to my server?

### ISSUE THREAD

**Issue by shareef-dweikat** [jitsi/jitsi-meet#6292]
Is it possible to redirect Jitsi chat conversations to my server?

**Comment by toby63** [comment]
@shareef-dweikat Could you explain what you intend exactly?

**Comment by shareef-dweikat** [comment]
@toby63 
I am developing an app using Jitsi. You know, users can do Audi. Video, and Text conversation using it. I need to monitor their text conversations. To do that, i need to redirect their conversation to my server rather than Jisti server, so i can analyze them. 

Do you get the idea?

**Comment by toby63** [comment]
> Do you get the idea?

Not really, but I only asked for others to understand your issue better.
With your server you mean what?
Your own jitsi server, or your own xmpp-server or a different server for text logs?
Otherwise it's a bit strange that you want to "monitor and analyze their text conversations".

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
