### ISSUE TITLE
Package repository error when trying to install

### ISSUE THREAD

**Issue by jeffchown** [jitsi/jitsi-meet#6300]
Hello,

When following the Jitsi Meet quick install instructions, I am receiving a `The repository 'https://download.jitsi.org stable/ Release' no longer has a Release file.` error when executing the `apt-get update` step.

This worked fine last night but is not working this morning (on a new server).

Can anyone shed some light on this?  Thanks in advance for any help.

Jeff

**Comment by saghul** [comment]
Looks like our repo is down... ping @damencho

**Comment by jeffchown** [comment]
Thanks for the quick response @saghul !  

Hi @damencho - per @saghul 's response and my original issue post, is the `https://download.jitsi.org stable` repo down?

**Comment by damencho** [comment]
Works now.

**Comment by jeffchown** [comment]
Perfect.  Thanks @damencho

**Comment by davidrd108** [comment]
I need help, please
I make:

curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'

echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null

I Got thi error:
**E: The repository 'https://download.jitsi.org stable/ Release' does not have a Release file.**
