### ISSUE TITLE
Release notes missing for 20.2.0, 20.2.1 in CHANGELOG-MOBILE-APPS.md

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jitsi-meet#6301]
It's really good to see frequent updates published via F-Droid.org for the Android Jitsi Meet app, thank you!

However, the changelog is missing details about the last two updates (20.2.0, 20.2.1). I am referring to this document:

https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-APPS.md

**Comment by MagicFab** [comment]
CC @saghul

**Comment by saghul** [comment]
Oops, dropped the ball there. Updated now, thanks for the report!

**Comment by MagicFab** [comment]
Thank you!
