### ISSUE TITLE
VirtualHost OR .htaccess that blocks root domain from non private IP Addresses

### ISSUE THREAD

**Issue by stondino00** [jitsi/jitsi-meet#6304]
As an alternative to the secure login option (which I'm not able to get working with active directory on port 3269) I'd like the ability to do the following.

Either a VirtualHost OR .htaccess file that performs the following.

ONLY allows private internal IP networks to access the main meet.example.com domain.  When someone on the internet attempts to access this meet.banktr.com root url, they receive a forbidden message.

This would only allow INTERNAL network hosts to create meetings since it's not accessible from the internet.

This would also need to allow anything after meet.example.com/ to be accessible from the Internet so anybody can JOIN an already created meeting.

This sounds like a very simple security alternative to the secure option that so many are struggling with.

Just not able to figure out how to create a virtualhost or .htaccess file that solves this issue AND keeps the rest of the system operating normally.

**Comment by saghul** [comment]
Closing as this is specific to the web server you use and not Jitsi related.
