### ISSUE TITLE
"Native module cannot be null" when trying to run react native app

### ISSUE THREAD

**Issue by felix-voicehub** [jitsi/jitsi-meet#6305]
## Description
I want to run the react-native app on iOS (not the framework). I am getting "Native module cannot be null" when trying to run the iOS react-native app.

![image](https://user-images.githubusercontent.com/49151885/79995997-38cc8d80-84b8-11ea-9d0f-d5d1f2356796.png)

## Steps to reproduce
Here is what I did:
- `git clone`
- `npm i`
- `cd ios`
- `pod install`

Here I am getting at the end:
```
[!] The Podfile contains framework or static library targets (JitsiMeet), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).
```

Then I did:
- `cd ..`
- `npx react-native run-ios` (also tried running it from Xcode)

I am getting the following errors from that last command:

```sh
error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?
error Could not find the following native modules: RNCAsyncStorage, RNGoogleSignin, react-native-netinfo, react-native-background-timer, react-native-calendar-events, react-native-keep-awake, BVLinearGradient, RNSound, RNSVG, RNWatch, react-native-webrtc, react-native-webview. Did you forget to run "pod install" ?
```

Obviously, I did run `pod install`. The app does build despite the errors, it shows the splash screen for a bit,  and then shows the screen in the picture above.

I am aware of https://github.com/jitsi/jitsi-meet/issues/2423, but this seems like something else.

# Environment details
macOS 10.14.6
node 12.6.1
npm 6.13.4
Xcode 11.3.1 (Build version 11C504)
Cocoapods 1.9.1

**Comment by saghul** [comment]
That is so weird, never seen it before... I geneerally reccommeendd everyone to use Xcode. Make sure you open the workspace file, not the project file. Does the problemn still occur that way?

**Comment by felix-voicehub** [comment]
@saghul Yes, I opened it from the workspace file. It still persists.

**Comment by saghul** [comment]
> Seriously weird.

That's Xcode being Xcode :-P

**Comment by fritzfr** [comment]
Just to complete the info: This is likely caused by having the metro bundler already opened from another project. Terminate it, then it works.
