### ISSUE TITLE
Sharing link in Iframe should show URL of main page

### ISSUE THREAD

**Issue by VogtAI** [jitsi/jitsi-meet#6308]
When using jitsi meet in an IFrame, the sharing link should be the URL of the main page instead of the IFrame URL.

**Comment by VogtAI** [comment]
Alternatively an option in the config file for disabling the sharing button and dialog would be great.

**Comment by voicemailtel** [comment]
There is option to hide button "info" from toolbar on interface_config, it works on iframe by using config overwrite. For the share link I have the same problem. I agree that a config option whould help to setup a diferent url.

**Comment by dpanic** [comment]
Config for setting third party url share. For example some of us have shortened URLs.
