### ISSUE TITLE
error con la camara

### ISSUE THREAD

**Issue by juanpablo2006** [jitsi/jitsi-meet#6309]
hola no me deja utilizar la camara

**Comment by KennosiS** [comment]
Hay un problema entre el teclado y la silla.

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
