### ISSUE TITLE
Black screen while 3 or more users join

### ISSUE THREAD

**Issue by TheProgramSrc** [jitsi/jitsi-meet#6311]
(I checked older issues and anything works)

## Description
When there is 2 users everything is ok but when another one enter to the room the screen is black and there is no sound

## Information
OS: Ubuntu 18.04
Jitsi Meet: latest

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

This is normally problems with firewall, or not working port forwarding or jvb not correctly discovering its public IP address. Check https://jitsi.org/qi#advanced-configuration
