### ISSUE TITLE
camara no funciona

### ISSUE THREAD

**Issue by pamela1234** [jitsi/jitsi-meet#6312]
no puedo abrir la camara

**Comment by toby63** [comment]
@pamela1234 Please search for issues first.
See here: https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
