### ISSUE TITLE
Solicitud

### ISSUE THREAD

**Issue by UnidadTI** [jitsi/jitsi-meet#6320]
Buenos tardes señores Jitsi, por medio del presente correo nos dirigimos  a ustedes con el fin de solicitar de su ayuda en realizar una transmisión en vivo desde su plataforma, ya que cuando intentamos hacer la transmisión en vivo nos sale este mensaje o pantallazos, en la actualidad nos encontramos haciendo pruebas para realizar una transmisión el día lunes 27 de abril a las 10:30 am hora Colombia.   

" Estamos trabajando para liberar recursos de transmisión 

Adjunto imagen 

Atentamente,

Julio Díaz 
Correo:  uat@parlamentoandino.org

![image](https://user-images.githubusercontent.com/64169054/80033137-d3759e00-84b1-11ea-8573-fc07f3c0f062.png)

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

@UnidadTI please also remove your private email from this post.
@saghul may you just remote it from the message?

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
