### ISSUE TITLE
Problemas con NAT

### ISSUE THREAD

**Issue by bootablearg** [jitsi/jitsi-meet#6322]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Primer scenario
DMZ Jitsi appliance on VMWare <—> pfSense <—> Internet
LAN <—> Same pfSense of Jitsi <—> Internet

pfSense manaja mas de una red en su LAN interface

Jitsi server esta en un Debian 9, detras de un pfSense router con HA Proxy

El firewall en Jitsi appliance esta apagado

Ports 80 y 443 son administrados por el HAProxy del pfSense

Tambien HAProxy maneja otros ports como smtp, pop3 etc_ etc_, inclusive RTMP en 1935, todos funcionas de maravillas

Bien, Jitsi server reciveel port 80 y 443 por el HAProxy mas el 4443 y 10000, el 1000 en UDP es por NAT, todo detra del pfSense

Esto usando un FQDN que se resuelve en internet con la IP publica del firewall, y en la LAN accedo via el HAProxy, ergo no tengo la necesidad de generar doble zona y en la LAN apuntarla a la IP interna de Jitsi.
En el hosts del Jitsi si hice que el fqdn que se resuelve en internet apunte al 127.0.0.1 como indica el paper de instalacion.

The sip-communicator_properties file on /etc/jitsi/videobridge has the next config

###############################
org_ice4j_ice_harvest_DISABLE_AWS_HARVESTER=true
org_ice4j_ice_harvest_NAT_HARVESTER_LOCAL_ADDRESS=A_B_C_D (internal IP of Jitsi)
org_ice4j_ice_harvest_NAT_HARVESTER_PUBLIC_ADDRESS=1_2_3_4 (external Public IP of pfSense WAN, it’s not behind a private, the pfSense box catch the public ip)
#org_ice4j_ice_harvest_STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay_jitsi_net:443 (comment as indicate the instructions)
org_jitsi_videobridge_ENABLE_STATISTICS=true
org_jitsi_videobridge_STATISTICS_TRANSPORT=muc
org_jitsi_videobridge_xmpp_user_shard_HOSTNAME=localhost
org_jitsi_videobridge_xmpp_user_shard_DOMAIN=auth_meet_mydomain_com
org_jitsi_videobridge_xmpp_user_shard_USERNAME=jvb
org_jitsi_videobridge_xmpp_user_shard_PASSWORD=ydGeYRm1
org_jitsi_videobridge_xmpp_user_shard_MUC_JIDS=BvbVrewery@internal_auth_meet_mydomain_com
org_jitsi_videobridge_xmpp_user_shard_MUC_NICKNAME=9ce1a67a-8c5d-4a1e-b529-583448e5aaaa
###############################

La configuracion de arriba es la que se tiene y se encuentra como recomendada para el caso en el que esta el appliance (detras de un NAT)

Sintomas

Primer caso de uso
Una PC detras del pfSense en la LAN
Un Celular detras del pfSense en la misma lan LAN que la PC

Las conecciones a la url van OK
El ingreso a la salas van OK
Los chat van OK
El Audio va OK
El Video va OK

Estimo por que esta usando el P2P

Segundo casto de testeo
Una PC detras del pfSense en la LAN
Un Celular via paquete de datos (sin usar el WiFi, ingresa por la WAN del pfSense)

Las conecciones a la url van OK
El ingreso a la salas van OK
Los chat van OK
El Audio NO va OK
El Video NO va OK

Tercer casi de uso
Una PC detras del pfSense en la LAN
Un Celular via paquete de datos (sin usar el WiFi, ingresa por la WAN del pfSense)
Segundo Celular via paquete de datos (sin usar el WiFi, ingresa por la WAN del pfSense)

Las conecciones a la url van OK
El ingreso a la salas van OK
Los chat van OK
El Audio NO va OK
El Video NO va OK

Cuarto caso de uso
Una PC detras del pfSense en la LAN
Un Celular detras del pfSense en la misma lan LAN que la PC
Segundo Celular detras del pfSense en la misma lan LAN que la PC

Las conecciones a la url van OK
El ingreso a la salas van OK
Los chat van OK
El Audio NO va OK
El Video NO va OK

Segundo scenario
Es exactamente como el anterio salvo la configuracion en un par de cosas y las casos de usos son los mismos pasando exactamente lo mismo

The sip-communicator_properties file on /etc/jitsi/videobridge has the next config

###############################
org_ice4j_ice_harvest_DISABLE_AWS_HARVESTER=true
#org_ice4j_ice_harvest_NAT_HARVESTER_LOCAL_ADDRESS=A_B_C_D (internal IP of Jitsi)
#org_ice4j_ice_harvest_NAT_HARVESTER_PUBLIC_ADDRESS=1_2_3_4 (external Public IP of pfSense WAN, it’s not behind a private, the pfSense box catch the public ip)
org_ice4j_ice_harvest_STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay_jitsi_net:443 (comment as indicate the instructions)
org_jitsi_videobridge_ENABLE_STATISTICS=true
org_jitsi_videobridge_STATISTICS_TRANSPORT=muc
org_jitsi_videobridge_xmpp_user_shard_HOSTNAME=localhost
org_jitsi_videobridge_xmpp_user_shard_DOMAIN = auth_meet_mydomain_com
org_jitsi_videobridge_xmpp_user_shard_USERNAME=jvb
org_jitsi_videobridge_xmpp_user_shard_PASSWORD=ydGeYRm1
org_jitsi_videobridge_xmpp_user_shard_MUC_JIDS = BvbVrewery@internal_auth_meet_mydomain_com
org_jitsi_videobridge_xmpp_user_shard_MUC_NICKNAME=9ce1a67a-8c5d-4a1e-b529-583448e5aaaa
###############################

Que estoy haciendo mal?
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by Echolon** [comment]
@bootablearg **please translate your issue to English**. 

As long as this is not the case we cannot manage the efforts to translate it ourselves.
You can use free services like www.deepl.com. Once you have translated (as well as the title of the issue) we can reopen the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
