### ISSUE TITLE
Videobridge TCP harvester behind NAT: Chrome uses wrong candidate

### ISSUE THREAD

**Issue by joushx** [jitsi/jitsi-meet#6327]
## Description
When using the video bridge behind a port translation, (in our case 444 -> 4443), the candidate elements arriving at the web interface contain:

1. the public IP
2. the private IP
3. the port 444 (port)
4. the port 4443 (rport)

## Current behavior
```
<candidate network="0" priority="2130706431" protocol="ssltcp" port="4443" ip="10.32.0.25" generation="0" tcptype="passive" id="79aab4904c5a58e507f007a82" type="host" foundation="1" component="1" />
<candidate network="0" priority="2130706431" protocol="udp" port="10000" ip="10.32.0.25" generation="0" id="bd30e3d4c5a58e507f009037" type="host" foundation="3" component="1" />
<candidate foundation="2" rel-port="4443" priority="1694498815" protocol="ssltcp" port="4443" ip="XXX" network="0" rel-addr="10.32.0.25" id="2a4560744c5a58e5079e98642" tcptype="passive" type="srflx" generation="0" component="1" />
<candidate foundation="2" rel-port="4443" priority="1694498815" protocol="ssltcp" port="444" ip="10.32.0.25" network="0" rel-addr="10.32.0.25" id="6675f984c5a58e507f006ae3" tcptype="passive" type="srflx" generation="0" component="1" />
<candidate foundation="2" rel-port="4443" priority="1694498815" protocol="ssltcp" port="444" ip="XXX" network="0" rel-addr="10.32.0.25" id="1864b2c14c5a58e5079e976a3" tcptype="passive" type="srflx" generation="0" component="1" />
<candidate foundation="4" rel-port="10000" priority="1677724415" protocol="udp" port="10000" ip="XXX" network="0" rel-addr="10.32.0.25" id="bd5e5164c5a58e5079e99bf7" type="srflx" generation="0" component="1" />
```

Chrome tries to connect to the correct bridge host, but on port 4443. It uses the candidate with port 4443, but not the one with 444.

## Expected Behavior
Firefox tries to connect to the correct bridge host, on port 444. 

## Steps to reproduce
1. Configure videobridge:

```
org.jitsi.videobridge.DISABLE_TCP_HARVESTER=false
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=192.168.XX
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=1.2.3.4
org.jitsi.videobridge.TCP_HARVESTER_PORT=4443
org.jitsi.videobridge.TCP_HARVESTER_MAPPED_PORT=444
```
2. Map port 444 to 4443 and enter room with >= 3 participants
3. Use e.g. Wireshark to view traffic to wrong port

# Environment details
Docker containers (Kubernetes)

Port 10000 is blocked for testing

**Comment by mawasource** [comment]
Good question - it seems to be the wrong candidate is used. I was able to reproduce the issue and saw that firefox is trying both candidates while Chrome only tries 4443

**Comment by saghul** [comment]
@bgrozev Maybe you have an idea here?

**Comment by joushx** [comment]
We solved it for us by not using port translation any more. We now use 444 everywhere and use authbind to allow jitsi to listen on this port.

**Comment by Rouji** [comment]
I'm getting this kind of problem even without the `MAPPED_PORT`. Chrome/Chromium only tries udp 10000 and doesn't fallback to anything else (in my case, tcp harvester directly on 443). 
Firefox does it correctly.

Not 100% sure this is exactly the same issue, but it does seem like Chrome always just uses one single candidate, no matter what the setup.
