### ISSUE TITLE
No puedo grabar la videoconferencia

### ISSUE THREAD

**Issue by Markosbel** [jitsi/jitsi-meet#6329]
Comencé a usar jitsi hace poco y grabé una primera conferencia sin problemas se subió a Dropbox bien, pero al ir a grabar una segunda conferencia el otro dia no pude y a partir de ahí me dice que:
"Todas las grabadoras están actualmente ocupadas" y no salgo de ahí. Da igual que use el portátil o la tablet.  ¿Alguien me puede ayudar? Y ya aprovecho para preguntar si se puede grabar la videoconferencia sin usar dropbox. Muchisimas gracias.

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
