### ISSUE TITLE
Add DTMF UI controls

### ISSUE THREAD

**Issue by jbguerraz** [jitsi/jitsi-meet#6332]
Exactly the same as #3606 

> When adding a SIP caller through jigasi it would be nice to have the option to send DTMF tones.
For example I would like to be able to dial into a third party PSTN conference bridge and currently can't do that because I can't send the required PIN.
It looks like this functionality did exist at some point but then was removed #2731

What's the status with DTMF ? Is there a chance to get it somehow ? Is there a need for contribution ?

Thank you!

**Comment by jbguerraz** [comment]
not stale ;) I'd be happy to know!

**Comment by damencho** [comment]
Yes this was removed and is not used through the UI

**Comment by jbguerraz** [comment]
Hello @damencho 
Would you accept some contribution that bring it back ? We'd love to bridge another conference using PSTN.

**Comment by damencho** [comment]
Yep, that sounds ok. Just need to be behind flag disabled by default. 
Thank you.

**Comment by jbguerraz** [comment]
This is still something we want to tackle at some point (probably S2 2021)

**Comment by mwllgr** [comment]
+1 for this. I'd need the DTMF controls too.

**Comment by cbeckr** [comment]
See PR above: https://github.com/jitsi/jitsi-meet/pull/8890

**Comment by mwllgr** [comment]
Any ETA on how long it takes to be in a release version?

**Comment by cbeckr** [comment]
I'll try to follow up here over the next week or so.

**Comment by mwllgr** [comment]
Any news on the PR @cbeckr?

**Comment by cbeckr** [comment]
Sorry @mwllgr, unfortunately I won't have time to work on this in the foreseeable future due to other commitments. If anyone else could finish the PR I'd appreciate it.

**Comment by saghul** [comment]
I'm going to close this since we have no plans to add such a feature at this time, sorry.
