### ISSUE TITLE
Used Ram Increased after a call

### ISSUE THREAD

**Issue by iamoku** [jitsi/jitsi-meet#6333]
Hi everybody,
I have a small dedicated cloud server based on Ubuntu 18.04 with only Jitsi installed that I use for internal calls with 5 to 10 people max.
I have noticed that the RAM used increased at the end of calls with different participant number during the same call.
For example in this call we were 2 on the first hour, after 7 with 5 cameras and at then end 3 with 3 cameras.
Almost at the end of the call the used RAM continued to increase 2 hours after the call end.
What do you think is this issue related to?

Here is the Prometheus data
![photo_2020-04-23 09 17 32](https://user-images.githubusercontent.com/49643727/80105723-f56d3000-8546-11ea-80e2-dfd7f0b146f7.jpeg)

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

Even with no conference there are healthchecks and stuff going on. Jicofo and JVB use up to 3GB each it grows to those limits.
Take a look at https://community.jitsi.org/t/solved-looks-like-a-memory-leak/35876/8
