### ISSUE TITLE
mobile client: dark theme support

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#6334]
Please add a dark theme support with selection it from the system theme setting by default

![image](https://user-images.githubusercontent.com/14617699/80108315-d2fa0780-8584-11ea-9bed-0292960f61dd.png)

**Comment by 532910** [comment]
Is it stale?

**Comment by 532910** [comment]
Dear bot, please stop trying to close this issue.

**Comment by moshpirit** [comment]
I use the dark mode and everytime I open the chat I get blind. So frustrating

**Comment by 532910** [comment]
fixed, not actual more
