### ISSUE TITLE
Android low contrast ratio for inactive button

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#6335]
https://contrastchecker.com/?c=1081b2&b=17a0db

`Calendar` is extremely hard to see and read:

![image](https://user-images.githubusercontent.com/14617699/80107837-47807680-8584-11ea-9746-f4a276e65b19.png)

**Comment by 532910** [comment]
Is any update there?

**Comment by 532910** [comment]
must be fixed

**Comment by 532910** [comment]
I believe that the bot shouldn't decide whether to fix it or not!I believe that the bot shouldn't decide whether to fix it or not!

**Comment by 532910** [comment]
Still actual

**Comment by 532910** [comment]
Still actual

**Comment by s21sd** [comment]
I can solve this issue , can you assign this issue to me.
