### ISSUE TITLE
iOS Jitsi app disturbing conference in random ways

### ISSUE THREAD

**Issue by pandel** [jitsi/jitsi-meet#6337]
Hi!

Today, I
- freshly installed jitsi-meet on Debian 10 via quick start
- added Letsencrypt certificates
- configured NAT according to the advanced part of the installation manual.
So far, so good.

I am able to start meetings between conference partners regardless if they connect to the internet directly or via a relatively restrictive corporate proxy - using Google Chrome exclusively. Tested it with 4 different partners, two on the corporate net, two via direct net connection. Everything works as expected. Changes between two or more participants are handled correctly.

BUT, as soon as I try to establish a connection to the established conference with my iPhone or iPad (latest os 13.4, latest app) with the Jitsy app via LTE (did not try Wifi, useless in my configuration), different variants happen and I cannot say why:

a) iPhone has only black screens of everyone else while the rest sees only a new participant without video/audio
b) random connection between iPhone and one other participant is being established (but not one of the corporate network connection) and everything else is blackened out
c) every participant including iPhone is immediately disconnected and gets a message like  "Something bad happened, trying again in x seconds"... (I am German, so I don't know the exact message in English) over and over again, eventually reconnects everyone else when I leave with the iPhone

I have absolutely no idea, why this happens. I file this as a bug, because everything else seems to work just fine.

BTW, the machine is real hardware, no VM. Ports forwarded: 80, 443, 10000

Regards,
Holger

**Comment by leonfrom** [comment]
Hey,

I have the same problems with fresh install on Ubuntu Server 18.04.

Regards,
Leon

**Comment by saghul** [comment]
What log sdo you see in the browser console when everything fails after the iOS participant joins?

**Comment by pandel** [comment]
Hi!

As this error was annoying and I needed a solution now, I went the complex way a few days ago and built up a separate TURN server in Amazon EC2 besides the Debian 10 installation. I removed jitsi-meet-turnserver, corrected some left over in the nginx configuration (mainly port setting back to 443) and everything is fine now, as our test phase up to now is working flawless.

So, sorry, but I am unable to test. I wanted to close this issue after our test phase ended, but if you wish, you can close it now. 

Regards,
Holger

**Comment by saghul** [comment]
If it works now with changes to the infrastructure I assume it had something to do with configuration.

Please holler if it happens again and we’ll reopen.

**Comment by pandel** [comment]
Yes, thanks! I think, it has something to do with the fact how ssl_preread stream splitting is handled via nginx when you install the all-in-one solution via "apt install jitsi-meet".

I'd also like to propose an additional feature in this regard:
As "jitsi-meet" Debian package is a meta package for installing the whole environment INCLUDING the TURN server, it would be great to have a second meta package "jitsi-meet-without-turn". Then one could decide how a fresh installation should look like right from the start and no one would have to clean up things after removing jitsi-meet-turnserver manually.

**Comment by damencho** [comment]
We will be removing the multiplexing in favor of running turn on default ports and configured everytime. With just instructions how to do turn server with an extra dns ... We just need to find time adding that ... But it will come in the following month ...

**Comment by pandel** [comment]
Seems to be a good idea! Besides, many many thanks for your hard work! Jitsi is absolutely amazing :-)
