### ISSUE TITLE
Loss of connection creates 'ghost user'

### ISSUE THREAD

**Issue by lcts** [jitsi/jitsi-meet#6338]
Hi,
I have Jitsi running on my own server and have noticed the following issue:

- When the person who created the session drops out due to network issues or similar (i.e. NOT when disconnecting normally), they stay in the session as a 'ghost user' (present but no video/audio).
- When they then reconnect, they connect as a new user, with the 'ghost user' still present
- the ghost user remains the room mod and so cannot be kicked
- further deliberate disconnects/reconnects will always join as a new user
- further involuntary dropouts will create additional 'ghost users'

So far, I have only observed this with people who are the room creator, though it is possibly this can also happen to normal users or users who became moderators later on.

This is on a fresh install on Ubuntu 18.04 LTS, no secure domain, no special configuration or modules enabled.

**Comment by damencho** [comment]
An interesting observation that it happens only for guests. We have seen such reports when using prosody 0.10 and that upgrading to prosody 0.11 fixes the problem.

**Comment by lcts** [comment]
Sorry for the late reply, very busy times.
I upgraded to prosody 0.11, but unfortunately 0.11 doesn't work at all on my machine, so I can't really test your suggestion.
Jicofo & jvb logs claim that prosody doesn't server auth.<myserver>, prosody logs show that login attempts are met with

`Apr 28 09:51:14 c2s55e4cba6a360	error	Traceback[c2s]: /usr/lib/prosody/util/cache.lua:66: table index is nil
stack traceback:
	/usr/lib/prosody/util/cache.lua:66: in function 'set'
	/usr/lib/prosody/modules/muc/mod_muc.lua:176: in function 'track_room'
	/usr/lib/prosody/modules/muc/mod_muc.lua:204: in function </usr/lib/prosody/modules/muc/mod_muc.lua:191>
	(...tail calls...)
	/usr/lib/prosody/modules/muc/mod_muc.lua:433: in function '?'
	/usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
	(...tail calls...)
	/usr/lib/prosody/core/stanza_router.lua:180: in function 'core_post_stanza'
	/usr/lib/prosody/modules/mod_presence.lua:109: in function 'handle_normal_presence'
	/usr/lib/prosody/modules/mod_presence.lua:304: in function '?'
	/usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
	(...tail calls...)
	/usr/lib/prosody/core/stanza_router.lua:180: in function 'core_post_stanza'
	/usr/lib/prosody/core/stanza_router.lua:127: in function 'core_process_stanza'
	/usr/lib/prosody/modules/mod_c2s.lua:275: in function 'func'
	/usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>`

This seems like purely a prosody issue, but still, have you had any reports on this?

**Comment by damencho** [comment]
This is wrong value for storage setting in prosody config. Change it to 'memory'.

**Comment by lcts** [comment]
Hey, thanks for the answer.
I changed the storage backend to `memory` in the main `prosody.cfg.lua`
Same error, but now triggered a bit later by bosh instead of c2s:

```
conference.<myserver>:muc: Restoring room <roomname>@conference.<myserver> from storage
Apr 28 16:45:55 <myserver> prosody[12930]: runnerjh3B_SDI: changed state from ready to error (ready)
Apr 28 16:45:55 <myserver> prosody[12930]: mod_bosh: Traceback[bosh]: /usr/lib/prosody/util/cache.lua:66: table index is nil
```

Do I need to set different storage backends for the different components (beyond those that already have storage=none in the site prosody config)?
Why would things work in 0.10 with the default `internal` backend, but not in 0.11?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L46
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L58
This is how it should look like. ^
The reason for this change is that this was changed in prosody.

**Comment by lcts** [comment]
Hey, again, sorry for the delay.
So I just misunderstood you initially, none -> memory makes much more sense then internal -> memory. The server is running now with prosody 0.11 (& the latest jitsi packages, see below).

The issue persists, however I have to reverse my initial claim that this only happens with the user who started the meeting - that apparently was coincidental. When the 'ghost' is not the moderator, the 'ghost' can be kicked, while the new 'real' user remains, so it is less of a problem.

I figured out a way to reproduce the issue:
  
1.  create a meeting
2.  join the meeting from a second device (phone is easiest)
3. cut internet connection from 2nd device (e.g. switch to airplane mode)
4. wait for Jitsi to notice the connection issue (by notification on 2nd device)
5. switch internet back on & rejoin meeting on 2nd device
6. the timed-out initial user remains as 'ghost', user from 2nd device appears as new user

This can be repeated to create ghosts ad infinitum. Cutting the connection WHILE reconnecting appears to cause multiple ghost in one go, but I have been unable to reproduce this reliably. Reconnecting before the timeout does NOT create a ghost user, the original user simply becomes active again.

Maybe some mismatch in timeout values?

jitsi-meet 2.0.4548-1
jitsi-videobridge2 2.1-197-g38256192-1
jicofo 1.0-567-1
prosody 0.11.5-1~bionic6

**Comment by saghul** [comment]
This is expected behavior. Ghosts should disappear is 60 seconds, do they disappear for you?

The reason for ghosts to exist is that a user may have a flaky connection and it’s possible to resume a broken XMPP session, thus avoiding the ghost. But in order for this to work we need to keep a window of time in which the user can come back, and if they don’t, you’ll see the ghost.

**Comment by lcts** [comment]
Ha, I'm an idiot. They didn't disappear originally, so I didn't check that when testing with prosody 0.11.

It works now. Thanks to both of you for your help.

**Comment by geekgonecrazy** [comment]
@saghul did the fix for this one happen to get back ported or any plans to release it?  I notice latest in the jitsi meet debian repo is 1.10.0.  I tried to pull int 1.11.5 from upstream from prosody directly and things kinda blew up so I had to roll back.

We get this issue a lot. I have to restart prosody every few days to shake loose all of the ghost users.

We tried putting the allowners prosody script in as another temporary fix, but doesn't seem to pick it up for some reason.

**Comment by saghul** [comment]
There is no fix for the ghost users, they are going to happen. The fix is for Prosody 0.10 vs 0.11.

You can install 0.11 from the official Prosody repos to get the latest fixes.

**Comment by geekgonecrazy** [comment]
> There is no fix for the ghost users, they are going to happen. The fix is for Prosody 0.10 vs 0.11.

Right 100% understand that jitsi hasn’t made a fix for this specifically.  Was more wondering if there is a plan to ship prosody 0.11.x in the jitsi meet deb repo.  Since as is its only got 0.10.0 which has this issue. 

> You can install 0.11 from the official Prosody repos to get the latest fixes

Tried from the official prosody repo, everything started up but seems something between the two versions weren’t  compatible.  Because everyone regardless seemed to be alone when connecting to a room.  Logs didn’t return much of any use so had to roll back to keep from effecting calls happening

**Comment by saghul** [comment]
>  Was more wondering if there is a plan to ship prosody 0.11.x in the jitsi meet deb repo.

No plans for that.



> Tried from the official prosody repo, everything started up but seems something between the two versions weren’t compatible. Because everyone regardless seemed to be alone when connecting to a room. Logs didn’t return much of any use so had to roll back to keep from effecting calls happening

Our Docker setup runs off that repo with no problems. Must be something else. Feel free to open a new issue so we can try to troubleshoot.

**Comment by dhruvsgit121** [comment]
Hi, 

Upgarding the prosody version to 0.11 didn't worked for me. Can you please help me with this issue. As not able to get any other help.
