### ISSUE TITLE
Ubuntu 20.04 fails to install jitsi via install-letsencrypt-cert.sh

### ISSUE THREAD

**Issue by Porthorian** [jitsi/jitsi-meet#6341]
I understand Ubuntu 20.04 had just come out today 4/23/2020. This is mainly an issue to track when you guys decide to move your support up from 18.04.

## Description
install-letsencrypt-cert.sh fails on Ubuntu 20.04 due to 
```
python-virtualenv has "no-installation candidate"
```

Even when we specify in our sources.list and download the older repository from ubuntu bionic, when it comes to the script to run certbot-auto it will than output. Which is not an issue you guys will be able to fix as it is not your project. Just outputting for reference.
![image](https://user-images.githubusercontent.com/34264214/80137369-24989700-8571-11ea-94c5-b5ba7dd45160.png)

## Current behavior
Attempts to install certbot-auto packages and fails to due 
```
python-virtualenv has "no-installation candidate"
```

## Expected Behavior
A fully installed jitsi instance configured with letsencrypt

## Possible Solution
Use native certbot rather than certbot-auto.

## Steps to reproduce
If you need a quick and fast installation of Ubuntu 20.04 vultr has some images up.
https://www.vultr.com

# Environment details
Ubuntu 20.04

**Comment by yodaphone** [comment]
certbot-auto has to be replaced with certbot

**Comment by l3d00m** [comment]
Interestingly enough, one user reported the same problem with 18.04, see #6558.

**Comment by vineetStartele** [comment]
steps to install jitsi
sudo apt update
sudo apt install apt-transport-https
sudo apt-add-repository universe
sudo apt update
sudo apt install curl
sudo curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg
sudo echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
sudo apt update
sudo ufw enable
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 4443/tcp
sudo ufw allow 10000/udp
sudo ufw allow 22/tcp
sudo ufw enable
sudo ufw status verbose
sudo apt install jitsi-meet
enter ip address 127.0.0.1 and select a option to generate a self signed certificate
 above steps does bot give any error but as soon as i run the below  command i get the following error in ubuntu 20.04
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
i the the below error 
**Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate**

**Comment by paisuchen** [comment]
> steps to install jitsi
> sudo apt update
> sudo apt install apt-transport-https
> sudo apt-add-repository universe
> sudo apt update
> sudo apt install curl
> sudo curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg
> sudo echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
> sudo apt update
> sudo ufw enable
> sudo ufw allow 80/tcp
> sudo ufw allow 443/tcp
> sudo ufw allow 4443/tcp
> sudo ufw allow 10000/udp
> sudo ufw allow 22/tcp
> sudo ufw enable
> sudo ufw status verbose
> sudo apt install jitsi-meet
> enter ip address 127.0.0.1 and select a option to generate a self signed certificate
> above steps does bot give any error but as soon as i run the below command i get the following error in ubuntu 20.04
> sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
> i the the below error
> **Note, selecting 'python-is-python2' instead of 'python'
> Note, selecting 'python-dev-is-python2' instead of 'python-dev'
> Package python-virtualenv is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'python-virtualenv' has no installation candidate**
> Note = I run tthe above command on newly installed ubuntu 20.04

Hi, is there any update for this error?

**Comment by l3d00m** [comment]
You might check the linked issue in my comment above, if that helps.

**Comment by paisuchen** [comment]
> You might check the linked issue in my comment above, if that helps.

Thanks @l3d00m for your response.

I think the issue is jitsi not support Ubuntu 20.4 yet. Jitsi using the previous version of python an Ubuntu 20.4 using python 3.
For this issue I work around with generating let's encrypt in my domain service then copy certificate and key (.crt & .key) manually to jitsi server. It works for me.

**Comment by saghul** [comment]
The latest stable version should have this fixed, since we now use the `certbot` package provided by Ubuntu. Can you please give the latest stable a try?

**Comment by paisuchen** [comment]
> The latest stable version should have this fixed, since we now use the `certbot` package provided by Ubuntu. Can you please give the latest stable a try?

Hi saghul, I try withi this step:
sudo apt-get upgrate certbot <--- nothing updated, still on vertion 0.40.0

and I try also to run :
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

same error occurred. 

cmiiw if the steps was wrong

**Comment by saghul** [comment]
Have you updated jitsi-meet to the latest stable version? What package versions do you have?

**Comment by safnz** [comment]
Same issue here on fresh new install, running Ubuntu 20.04 and jitsi-meet 2.0.4857-1

```
/usr/local/sbin/certbot-auto renew
Requesting to rerun /usr/local/sbin/certbot-auto with root privileges...
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://nz.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://nz.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://nz.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://nz.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://download.jitsi.org stable/ InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

**Comment by dantman** [comment]
😩 What version of Ubuntu is fully supported by Jitsi Meet with tokens? I tried 18.04 LTS and the tokens package didn't work due to version conflicts (necessary versions was not available on that old version) and trying to manually set it up royally broke what I had already setup.

So I tried 20.04 LTS to try and get a recent enough version of everything for things to work. And got this same error instead.

```bash
nano /etc/hosts
sudo hostnamectl set-hostname meet
apt update && apt install apt-transport-https && apt-add-repository universe && apt update
curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'
echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
apt update
apt install jitsi-meet
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```

```
-------------------------------------------------------------------------
This script will:
- Need a working DNS record pointing to this machine(for domain meet.jitsi-test2.{...})
- Download certbot-auto from https://dl.eff.org to /usr/local/sbin
- Install additional dependencies in order to request Let’s Encrypt certificate
- If running with jetty serving web content, will stop Jitsi Videobridge
- Configure and reload nginx or apache2, whichever is used
- Configure the coturn server to use Let's Encrypt certificate and add required deploy hooks
- Add command in weekly cron job to renew certificates regularly

You need to agree to the ACME server's Subscriber Agreement (https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf) 
by providing an email address for important account notifications
Enter your email and press [ENTER]: daniel@redwerks.org
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease                            
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease                          
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease                                
Hit:5 https://download.jitsi.org stable/ InRelease                        
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

Server is an Azure VPS with the official `Ubuntu Server 20.04 LTS Gen1` image.

**Comment by SSpecken** [comment]
@dantman Pls have a look at [Jitsi Meet Installation Ubuntu 20.04](https://scheible.it/jitsi-meet-installation-ubuntu-20-04/). You'll have to:

Install certbot:
`sudo apt install certbot`

and replace `./certbot-auto` with `certbot` in the script **/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh**

`sudo sed -i 's/\.\/certbot-auto/certbot/g' /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`

**Comment by safnz** [comment]
Nice work @SSpecken - I can confirm this solution works. 

> @dantman Pls have a look at [Jitsi Meet Installation Ubuntu 20.04](https://scheible.it/jitsi-meet-installation-ubuntu-20-04/). You'll have to:
> 
> Install certbot:
> `sudo apt install certbot`
> 
> and replace `./certbot-auto` with `certbot` in the script **/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh**
> 
> `sudo sed -i 's/\.\/certbot-auto/certbot/g' /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`

**Comment by gpatel-fr** [comment]
current stable (jitsi-meet 2.0.4966,  jitsi-meet-web 1.0.4370) has the fix. This should be closed.

**Comment by getachew015** [comment]
this instruction should be working for Ubuntu 20.4
https://certbot.eff.org/lets-encrypt/ubuntufocal-other

**Comment by vineetStartele** [comment]
> steps to install jitsi
> sudo apt update
> sudo apt install apt-transport-https
> sudo apt-add-repository universe
> sudo apt update
> sudo apt install curl
> sudo curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg
> sudo echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
> sudo apt update
> sudo ufw enable
> sudo ufw allow 80/tcp
> sudo ufw allow 443/tcp
> sudo ufw allow 4443/tcp
> sudo ufw allow 10000/udp
> sudo ufw allow 22/tcp
> sudo ufw enable
> sudo ufw status verbose
> sudo apt install jitsi-meet
> enter ip address 127.0.0.1 and select a option to generate a self signed certificate
> above steps does bot give any error but as soon as i run the below command i get the following error in ubuntu 20.04
> sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
> i the the below error
> **Note, selecting 'python-is-python2' instead of 'python'
> Note, selecting 'python-dev-is-python2' instead of 'python-dev'
> Package python-virtualenv is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'python-virtualenv' has no installation candidate**
> Note = I run tthe above command on newly installed ubuntu 20.04
It's working more better than on ubuntu 18.04 by following this link https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
