### ISSUE TITLE
Custom FPS Slider

### ISSUE THREAD

**Issue by jacobgonzales20** [jitsi/jitsi-meet#6343]
I think a custom fps slider in the settings would be nice cause when screensharing 5 fps is to little for movies like you gotta be playing chess to use 5fps. So a slider to switch to a higher fps would be nice and i'm sure it won't affect bandwidth on servers that much or at all if you make this feature for 1v1 calls only. I know you can use a command to do this `#config.desktopSharingFrameRate.min=30&config.desktopSharingFrameRate.max=30` but having both participants due this especially not a tech savvy one is a lot of work. So having a dedicated setting in the settings tab were you can slide a bar to higher fps or enter in a custom fps would be nice.

**Comment by Echolon** [comment]
You do stream movies via a video conference? :confused:

**Comment by Echolon** [comment]
@saghul is this within the scope?

**Comment by mirh** [comment]
> You do stream movies via a video conference? 😕

Movies not... Some brief youtube video during a conference/lecture can happen instead. 

On the other hand I feel like there should be some adaptive automatic mechanism handling that. 
But letting the user also force whatever setting they want still seems important.
