### ISSUE TITLE
Ansible script for autmatic installation

### ISSUE THREAD

**Issue by tderflinger** [jitsi/jitsi-meet#6344]
**Is your feature request related to a problem you are facing?**
I would like to automatically install Jitsi on my Linux Ubuntu machine

**Describe the solution you'd like**
I would like to have an Ansible script for automatic installation that can be easily found in the Jitsi repository.

**Describe alternatives you've considered**
Manual installation via tutorial

**My solution**
I have already created an Ansible installation script that worked on my Ubuntu 18 machine on a Digital Ocean server.
https://github.com/tderflinger/jitsi-deployment
Maybe you could use that as a basis and include the script with Jitsi. Would be great.

**Comment by saghul** [comment]
How about you link it here? https://github.com/jitsi/jitsi-meet/blob/master/doc/README.md#devops-guide

**Comment by tderflinger** [comment]
Ok, I added a pull request #6572
