### ISSUE TITLE
self hosted server users from other browsers (not chrome or firefox) or apps cannot see or hear 

### ISSUE THREAD

**Issue by eliavs** [jitsi/jitsi-meet#6347]
---
I am using a self hosted jitsi installed on a digitalocean droplet i have had conversations with 3 particapants that worked

---
there are users that when they connect i cannot see them or hear them they cannot see or hear me but i see that they are connected and we can chat

I understend that the users that could not be seen or heard connected through an app or browsers such as opera

**Comment by MarcelB1988** [comment]
Hi all,

i have the same issues. 
I also noted, that the iOS user / participant will be shown as "Connection: Lost" after a minute. 
I don´t know, if that is normal behavior, if any errors accur. 

My setup:

Ubuntu 18.04. LTS
actual Jitsi Version
Nginx 1.18

**Comment by jimmymarbles** [comment]
Same issue!

I assumed this issue was an RTP port issue, but I did not configure/enable the UFW firewall so my ports are wide open.

I installed it via the Jitsi package repository.  

Digital Ocean: 
Ubuntu 18.04 w/ 1gb ram

**Comment by MarcelB1988** [comment]
Hey @jimmymarbles 

I already got that settings you mentioned in your Update 2. 
The strange thing for me was, while i using ssl, the certificate path (for FQDN) was not the correct one, so i changed it. 
This was not helping at all. I also tried some settings like forwarding any service from my firewall to the server. Nothing helped. Its really annoying and iam running out of options. 

Nobody got any solution or tips I could use? 
Thanks in advance

**Comment by l3d00m** [comment]
@MarcelB1988 Is this still happening? And is it only occuring on iOS for you?

@eliavs I'm a bit unsure what you meant by your issue description, is it happening only in unsupported browsers like Opera for you? Have you tried @jimmymarbles workaround?
