### ISSUE TITLE
Local development broken against alpha.jitsi.net

### ISSUE THREAD

**Issue by maxired** [jitsi/jitsi-meet#6348]
## Description
Hi, I have been working on some local development for the last few weeks.
Until now, I have never been able to use my own remote Jitsi instance while working locally.
I did follow the install instruction, the one without launching an Nginx server. I believe the issue is that the bosh connection can be established because of CORS.
Nevermind, until now I did develop against alpha.jitsi.net, which most of the time works fine.

But since some recent change on the alpha server, the index.html page did change, and so the import of scripts.

Are you aware of that change? I am not using master or jitsi-meet_4506 locally.
Is that the source of the issue?

## Current behavior

Local webpage does not load, because trying to load because of a 404 error on lib-jitsi-meet.js
My local page used until now lib-jitsi-meet.min.js

## Possible Solution
As a workaround, I did save the index.html page from my server in an html page,
and inside the incline config, change the bosh URL to use localhost:8080.
With that configuration, the webpack server handles correctly the forwarding to my own server.

**Comment by anrice** [comment]
@maxired I am running into the same issue. Could you please provide some detailed information on your workaround?

**Comment by maxired** [comment]
- save the index.html for your remote server : `curl https://<yourServer>/ > local.html`
- edit local.html page, and edit the line starting with `bosh:`. instead of your server domain name, insert localhost:8080
- when starting your webpack with `make dev` use the env WEBPACK_DEV_SERVER_PROXY_TARGET to replace the `https://alpha.jitsi.net` server by yours

**Comment by blalop** [comment]
I run into the same issue.

As a workaroud that works with the steps provided in the development guide, I just needed to copy libs/lib-jitsi-meet.min.js to libs/lib-jitsi-meet.js.

Include that in the Makefile deploy-lib-jitsi-meet recipe to avoid make ruining the workaroud everytime you run make.

**Comment by dyros26** [comment]
i experience the same issue.
@blalop i follow your instruction and it works.

**Comment by rob-grio** [comment]
I ran into the same issue, and the solution propsed by @blalop worked for me too. Here's the diff on my Makefile in case it helps anyone else:

```
% git diff Makefile
diff --git a/Makefile b/Makefile
index 0cb668e53..998224687 100644
--- a/Makefile
+++ b/Makefile
@@ -59,6 +59,9 @@ deploy-lib-jitsi-meet:
                $(LIBJITSIMEET_DIR)/connection_optimization/external_connect.js \
                $(LIBJITSIMEET_DIR)/modules/browser/capabilities.json \
                $(DEPLOY_DIR)
+       cp \
+               $(LIBJITSIMEET_DIR)/lib-jitsi-meet.min.js \
+               $(DEPLOY_DIR)/lib-jitsi-meet.js
 
 deploy-libflac:
        cp \
```

**Comment by blalop** [comment]
It is working right for me without workarounds.

**Comment by maxired** [comment]
> It is working right for me without workarounds.

I thinks the issue is that we were working locally with a previous version than the one published on alpha.jitsi.net

And since the webpack dev server forwared the HTML page from the remote server, things got broken.
But yes, I confirme that after I updated my local branch, this now works.
