### ISSUE TITLE
regarding Video recording

### ISSUE THREAD

**Issue by Gopigg** [jitsi/jitsi-meet#6349]
hi iam trying to store the recorded video in dropbox, but its not happening

can any help me to store the video in dropbox account, and also is there any way store in our own file server

**Comment by MagicFab** [comment]
Are you sure the recording is not on Dropbox, via the web Interface ? Perhaps it just didn't sync but it's on their servers.

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
