### ISSUE TITLE
Not possible to copy error messages with mouse in Chrome on Windows

### ISSUE THREAD

**Issue by hginzel** [jitsi/jitsi-meet#6350]
It is not possible to copy error messages to the clipboard in Chrome on Windows with mouse.
![jitsi-meet_error_message](https://user-images.githubusercontent.com/5886916/80202366-c7125200-8625-11ea-963b-e41e039a9ad9.png)

**Comment by Echolon** [comment]
rel. Let me copy text from the website #4814

Actually, I think this is a duplicate then.

**Comment by luixxiul** [comment]
I'd rather handle them as different ones as these issues happen on different pages. I've pushed a PR for #4814.
