### ISSUE TITLE
Firefox addRemoteStream error

### ISSUE THREAD

**Issue by HelloWorldUser123** [jitsi/jitsi-meet#6351]
## Description
---

When two or more participants are within the room I got following error. Somehow I'm not always able to reproduce it all the time.

m=audio 52420 RTP/SAVPF 111 126\r\nc=IN IP4 x.x.x.x\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:126 0-15\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:094054ad\r\na=ice-pwd:0287ab63f4ccb3eed9ecdc30337c6938\r\na=candidate:0 1 UDP 2122187007 10.0.75.1 52417 typ host\r\na=candidate:1 1 UDP 2122121471 xxxx 52418 typ host\r\na=candidate:2 1 UDP 2122055935 192.168.0.15 52419 typ host\r\na=candidate:3 1 UDP 2122252543 xxxx 52420 typ host\r\na=candidate:4 1 TCP 2105458943 xxxx 9 typ host tcptype active\r\na=candidate:5 1 TCP 2105393407 xxxx 9 typ host tcptype active\r\na=candidate:6 1 TCP 2105327871 192.168.0.15 9 typ host tcptype active\r\na=candidate:7 1 TCP 2105524479 xxxx 9 typ host tcptype active\r\na=end-of-candidates\r\na=ssrc:292692253 cname:{5a18bb91-0ff6-4d97-ac39-db52fcd50714}-1\r\na=ssrc:292692253 msid:{09ca08de-168e-42ac-b57e-ad4fded572ed}-1 {a80554e0-3b58-42c6-bdac-a3793e6f56d7}-1\r\na=rtcp-mux\r\n

**Comment by HelloWorldUser123** [comment]
@jallamsetty1

**Comment by jallamsetty1** [comment]
Can you please include all relevant information ? like versions of the FF clients involved and the exact error. Can you also pls check if you have resistFingerPrinting enabled on any of the FF clients ?

**Comment by HelloWorldUser123** [comment]
I'm simply using the latest version of firefox and jitsi. This also happens on meet.ji.si

**Comment by kinafu** [comment]
The same occurs for me. A second after granting the camera access permissions
- Windows 10 Firefox 76.0.1
- meet.jit.si instance
- Firefox privacy protection level "Standard", no PrivacyBadger, UBlockOrigin

When I use Chromium on the same machine it works fine.

![Screenshot video of opening the jitsi call in firefox](https://i.imgur.com/d6Hs4U2.gif)

**Comment by saghul** [comment]
FWIW I cannot reprroduce thi with FF 77 beta on macOS.

**Comment by Sim59121** [comment]
Hello,

I have the same problem on Ubuntu 20.04 and with the latest version of Firefox
When i test on the same device with Chromium or Opera, it's work fine !

**Comment by luixxiul** [comment]
@kinafu would you please try with a fresh profile?

**Comment by jallamsetty1** [comment]
I haven’t been able to reproduce this either without add-ons, I suspect the user has a add-on installed which blocks fingerprinting. If the UA string is spoofed to be an older version but the underlying API is newer then we will have this issue.

**Comment by Sim59121** [comment]
Hello,

I have the same problem.
I have try to disabled all my addons and all the protections of firefox and the problem is already here.

**Comment by luixxiul** [comment]
@Sim59121 have you tried with Firefox safe mode?

**Comment by Sim59121** [comment]
Yes, I just tried safe mode. The problem is still there

**Comment by saghul** [comment]
Just tested on FF 76 on the Ubuntu 20.04 based PopOS. No issue. What UA does yours report? What exact steps ddo you follow to get the problem?

**Comment by Sim59121** [comment]
- I launch Firefox
- I'm connecting to https://meet.jit.si/test
- And i crash
![jitsi](https://user-images.githubusercontent.com/51054004/82121356-de9faf00-977b-11ea-8c3f-5331f9b4075c.png)

**Comment by saghul** [comment]
> What is UA ?

User Agent. Open the JS console and type `navigator.userAgent`

**Comment by Sim59121** [comment]
ok ! I found the JS console but i can't found the User Agent :(

**Comment by kinafu** [comment]
I found my user agent to be set to "firefox 68" on my daily profile, altough I am using firefox 76. 
(The former screenshot / experience I created with my daily profile.)

On a new profile with the same firefox installation it works fine.
Now I used the add-on "User agent switcher and manager" to switch the agent version to 76 on my daily profile. And in that state jitsi works fine just like in the fresh profile.

**Comment by jallamsetty1** [comment]
> ok ! I found the JS console but i can't found the User Agent :(
> I can't see where I can type : "navigator.userAgent" except in "filter".
> When, i type this in filter, i don't found anything

You can type it at the very bottom of the console, you should see a `>` prompt there.

**Comment by jallamsetty1** [comment]
> I found my user agent to be set to "firefox 68" on my daily profile, altough I am using firefox 76.
> (The former screenshot / experience I created with my daily profile.)
> 
> On a new profile with the same firefox installation it works fine.
> Now I used the add-on "User agent switcher and manager" to switch the agent version to 76 on my daily profile. And in that state jitsi works fine just like in the fresh profile.

Glad you were able to figure it out !

**Comment by saghul** [comment]
Looks like this one is solved then. Please holler is we need to reopen.

**Comment by Sim59121** [comment]
Hello,

I have found my user agent, thank you Jallamsetty :)   It's "Firefox 68".
I have change it to "firefox 76.0.1" with the addons "Random User Agent" and i re test.

I always crash :(
![user agent](https://user-images.githubusercontent.com/51054004/82137447-a5ad1c00-9807-11ea-8e4c-9a0b6db43118.png)

**Comment by kinafu** [comment]
After setting `privacy.resistFingerprinting` to false in the firefox settings, it works, too.

To me it seems the anti fingerprint feature changes the user agent to firefox 68!
(Turning off `resistFingerprinting` resets your user agent to the real version of firefox.)

Steps to reproduce:


1. [Check your user agent for the firefox version](https://duckduckgo.com/?q=user+agent) 
2. Go to the URL `about:config`
3. Type in `privacy.resistFingerprinting`
4. Set it to `false`
5. [Check your user agent again](https://duckduckgo.com/?q=user+agent)

**Comment by Sim59121** [comment]
After disabled the "privacy.resistFingerprinting", it's alright !
Thank you @kinafu

**Comment by l3d00m** [comment]
Should this be reopened or is it a wontfix with resistFingerprinting on?

**Comment by Sim59121** [comment]
I don't know because the problem is solved when "resistFingerPrinting" is turned off manually in Firerox.

This is awkward but i think, it's a problem of Firefox. 

I don't know if the Jitsi Team fix this bug on its own or if it's up to Firefox to do it.

**Comment by saghul** [comment]
There are unfortunately things we cannot feature detect so we rely on version checks.

If your Ua strong lies about it, there is nothing we can do.
