### ISSUE TITLE
Unable to access the camera

### ISSUE THREAD

**Issue by GabrielSoaresBonfim** [jitsi/jitsi-meet#6355]
Hello, I am testing Jitisi but he is not accessing my camera, which is strange because I am allowing him to access the camera and I can also make calls on Skype or Teams normally.

![image](https://user-images.githubusercontent.com/64272525/80230286-22454400-8628-11ea-8f82-529c2cf1cbab.png)

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
