### ISSUE TITLE
Can't generate SSL certificate with Let's Encrypt on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by theoricher** [jitsi/jitsi-meet#6356]
## Description
On Ubuntu 20.04 LTS i can't generate SSL certificate Let's Encrypt with ` /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`

## Current behavior

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

## Steps to reproduce
Try to install jitsi meet on Ubuntu 20.04 LTS

# Environment details
OS : Ubuntu 20.04 LTS

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening new issues.

https://community.jitsi.org/t/script-for-ssl-certificate-creation-broken-on-20-04-focal-fossa/43555/2?u=damencho

**Comment by tigusigalpa** [comment]
since Ubuntu 20 you have to use `python3-` prefix instead of `python-`
