### ISSUE TITLE
Etherpad is not working / Working configuration missing

### ISSUE THREAD

**Issue by andreas-bulling** [jitsi/jitsi-meet#6359]
Hi,

I've been trying for days to get Etherpad working, have been raking through tons of forums posts, and asked in multiple places. But I couldn't find a single fully working configuration that reliably solves the Access-Control-Allow-Origin, Content-Security-Policy, XFRAME, whatever combination of settings is causing this problem. And I don't seem to be alone judging from the tons of people having asked similar questions in the past.

I therefore consider this a documentation bug that needs fixing. I envision a working configuration for NGINX and Apache would help 99% of people out there.

**Comment by hex-m** [comment]
> whatever combination of settings is causing this problem

Please explain what problem you are referring to. Did you use the instructions mentioned in the [wiki](https://github.com/jitsi/jitsi-meet/wiki/Etherpad-addition-example)?

**Comment by hex-m** [comment]
I just configured the Etherpad integration.

The wiki-article is confusing because the `proxy_pass` parameter assumes Etherpad is running on the same server as Jitsi Meet (on port 9001) while step 3 assumes Etherpad is running on a different server. My config values:

`proxy_pass https://etherpad-server.examle.com/;`

and 

`etherpad_base: 'https://etherpad-server.examle.com/p/',`

**Comment by andreas-bulling** [comment]
I tried but Access-Control-Allow-Origin, Content-Security-Policy etc always prevent the pad from being shown in the iframe

**Comment by andreas-bulling** [comment]
I managed to make one further step towards a working setup it seems. But now I am stuck with a new `Error during WebSocket handshake: Unexpected response code: 400`

**Comment by hex-m** [comment]
There is [an issue](https://github.com/ether/etherpad-lite/issues/3094) about CSP headers on the Etherpad side.

I would suggest to have this discussion in the [forum](https://community.jitsi.org/t/etherpad-error/48022) as others seem to have the same problem.

**Comment by andreas-bulling** [comment]
Thanks. Do you happen to know how to resolve this icon problem I am having? The NGINX configuration for jitsi includes a directive for /static and so does the one for etherpad. I can only assume that the two clash.

Do you have a working setup for jits+etherpad+nginx and, if yes, would you mind posting your complete config?

Thanks!

**Comment by psymin** [comment]
A symbolic link can resolve this issue.  Not the best fix, but it seems to do the trick.

https://github.com/jitsi/docker-jitsi-meet/issues/540#issuecomment-626085222

**Comment by andreas-bulling** [comment]
Great, thanks, will give it a try!

**Comment by l3d00m** [comment]
Closing this as this is now fixed / not an issue with Jitsi Meet per se.

**Comment by Ark74** [comment]
Has anyone tried this con Secure rooms?
Does it changes?
