### ISSUE TITLE
tel: URLs don't work in Firefox on Android

### ISSUE THREAD

**Issue by mavit** [jitsi/jitsi-meet#6360]
If you visit https://meet.jit.si/ExampleMeeting using Firefox on Android, towards the bottom of the page there is a list of telephone numbers that can be dialled to join the meeting.  These numbers are marked up as links using the `tel:` URI scheme, but clicking them does nothing.

It turns out that tel URI's containing the `#` character are [deliberately blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=797034) in Firefox for what I understand to be security reasons.

Does the backend support, or could be made to support, marking the end of the PIN with some other character?

**Comment by yhutoo** [comment]
Same with DDG (Browser), FF Focus, Orfox/Orbot, Onion Browser/Orbot, Web Media Share, (ASUS) Browser; some can't even get the link.
Can share with many apps, but not with any telephone one; how to use the #s?
No info is provided abt cockies, etc.; so which browser is supposed to work, and which privacy settings, please?
Even the PIN cannot be copied (but with a 3P app such Universal Copy).
ASUS ZenFone 3, Android 6.0.1
Tks, best

**Comment by mavit** [comment]
The issue is still present.

**Comment by mavit** [comment]
I can no-longer reproduce this with Firefox for Android 82.1.3, although, given the lack of activity at https://bugzilla.mozilla.org/show_bug.cgi?id=797034, it's not obvious whether that's deliberate or a regression.
