### ISSUE TITLE
ios App - 20.2.1 b68 - initiating private Chat from Mobile App not possible [bug]

### ISSUE THREAD

**Issue by ibrainventures** [jitsi/jitsi-meet#6361]
Thanks for all your work and this great video-chat eco-system.

We are actually evaluating the Jitsi System and have a issue on our iPhones XR and also
Ipads
## Description
Start a 2 or more Person Chat inside the origin jitsi.net

Longpress on a other conference partner opens a small dialog for starting a private chat.

## Current behavior

Click / touch didnt´t start any more process. only closes dialog.

## Expected Behavior

Should open a Modal for starting a Dialog / entry a private Message

## Possible Solution

Not inject desinfection fluid .. :-) .. No .. i didnt know .. code analysis, event handling check .. etc.

## Steps to reproduce
see upper details.

# Environment details

Iphone XR with Ios 13,x
Ipad with IpadOs 13.x

ios App - 20.2.1 b68

**Comment by ibrainventures** [comment]
Great! 

Installed version 20.2.3 and tested the private messeage initiation on the iphone.

Works fine .. there is a other issue with the "new message" inditication during a conversation
-> i would open there a other issue.

Many thanks for your work!

**Comment by hasgar** [comment]
"new message" indication for private message during a conversation still not fixed in sdk

**Comment by saghul** [comment]
Did you open an issue about that? If not, please do.

**Comment by saiprasad1996** [comment]
Facing the same problem. Two things that aren't working as described by @ibrainventures .
1 - Private message button does not do anything 
2 - New message indication not working on android or ios.

@ibrainventures how did you get the first point working? Can you please help.

**Comment by hasgar** [comment]
@saiprasad1996 update your SDK to latest will fix the issue or [https://github.com/jitsi/jitsi-meet/commit/cd1862a2d332f8eb3a21ffa6f4ecad937436017f](https://github.com/jitsi/jitsi-meet/commit/cd1862a2d332f8eb3a21ffa6f4ecad937436017f) check this commit

**Comment by saiprasad1996** [comment]
@hasgar thank you for the pointer. looking for exactly that.
