### ISSUE TITLE
fallo de cámara

### ISSUE THREAD

**Issue by MARIAMJCRUZ** [jitsi/jitsi-meet#6363]
En la aplicación de Jitsi, no puedo usar la cámara, la activa, pero no se ve ninguna imagen y  me sale un aviso donde dice que no se puede acceder a la cámara, sin embargo prende el foco que avisa que la cámara está encendida.

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
