### ISSUE TITLE
Unable to acess camera

### ISSUE THREAD

**Issue by Meryalbert12** [jitsi/jitsi-meet#6364]
No me funciona la cámara, pero no es problema de mi ordenador

**Comment by dpoon** [comment]
https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
