### ISSUE TITLE
Offer different video tile layouts

### ISSUE THREAD

**Issue by swiesmann** [jitsi/jitsi-meet#6366]
**Is your feature request related to a problem you are facing?**
short answer: I can't do this with Jitsi: ![image](https://user-images.githubusercontent.com/5763858/80279112-b207f280-86fb-11ea-8475-6413468f6cfa.png)
(via https://masilotti.com/play-board-games-online/)

long: Jitsi is super painfree and awesome to get going. However, **there are many ways to collaborate online** (i.e. Kanban Boards, IT Infrastructure status boards, YourCorporateApp™) and **seeing your collaborators talk and react reduces the cognitive load on your brain a lot**. It would be great if there was an option to have different layouts for the video tiles so that one can arrange the browser windows on the computer screen to see the collaborators AND another website at the same time.

**Describe the solution you'd like**
A new button for changing the how the video tiles are being laid out on the screen. I.e. the current layout as "standard", and two more for plain horizontal and vertical alignment.

**Describe alternatives you've considered**
I do not see an easy way to achieve this for all Jitsi users at the moment. There are only options like browser addons for custom user CSS or JS.

**Comment by johntyree** [comment]
I thought about this as well and I think it can be summarized as basically, "Jitsi's layout logic is too inflexible."

For example, it assumes that all people in the meeting are equally important and should be equally sized and equally prominently displayed. It also assumes that the best layout is "as square as possible" no matter what. You can't do what swiesmann shows above because you can't get jitsi to reflow the video windows into a column like that.


1. jitsi should be smarter about the "shape" it tries to fit into. I think "fill as much of the browser window as possible" is a reasonable heuristic here and locations should be shuffled around to make that happen.

2. jitsi needs a way to "pin" _without_ basically hiding everyone else. If I'm in a meeting and everyone is discussing e.g. a slideshow, or a board game or whatever really, I should be able to tell jitsi to emphasize that window (or de-emphasize it) as needed.

**Comment by rusosnith** [comment]
Rearrange windows, change scale, or even change ratio (portrait callers will show in panoramic view nevertheless most of their screen space will be just black bars)

**Comment by neobrain** [comment]
"further activity"

**Comment by WimLeflere** [comment]
Not stale, still a nice feature to have

**Comment by mdingemanse** [comment]
Not stale at all, and also necessray for accessibility (on which see #6906). Deaf people who need access to selected streams (e.g. current speaker + selected interpreter) need to be able to rearrange and pin multiple tiles.

**Comment by dingodoppelt** [comment]
Definately a feature I'd love to see since the use of space has lots of room for improvement since there is still lots of unused space because the tiles don't expand to the whole screen. Rearranging and resizing the tiles would be a killer feature to make use of empty space.

**Comment by amsnek** [comment]
The ability to reorder tiles, set a layout, pin a tile, resize or filter out (inactive streams) would be extremly nice to have, for larger conferences even a possible "must have". 
This would also be a significant step towards WAI as well as mentioned above (for deaf people + interpreter).

**Comment by jmandel** [comment]
There are a couple of improvements to layout that would offer a great "effort to impact" ratio:

* Avoid dead space in gutters between tiles, in tiled view (I work around the the super-wide gutters by using "ctrl-minus" to zoom way out in the browser, which shrinks the gutters -- at the cost of making the buttons, chat, and other UI elements really hard to see.)

* If tiled view is providing an "MxN" grid of tiles, there should be some effort to optimize the choices of M and N, based on the window dimensions. The goal should be to optimize "packing" of tiles in the available space.

**Comment by mavit** [comment]
Duplicate of #5142?

**Comment by swiesmann** [comment]
> Duplicate of #5142?

@mavit yes, seems like it. Both issues are dealing with the same problem. The difference is that here the issue started with a proposal for switching layouts, while #5142 wants to fix the existing one.

IMHO my proposal for switching layouts is not the best solution. A "MxN" grid view like @jmandel suggested would solve all the problems and there would not be a need for multiple layouts as far as I can see. And that's basically the same solution that #5142 aspires towards. So let's join forces there.
