### ISSUE TITLE
Adjust install-letsencrypt-cert.sh for new distros

### ISSUE THREAD

**Issue by Franky1** [jitsi/jitsi-meet#6371]
## Description
---
`certbot-auto` is **deprecated**, therefore the script `install-letsencrypt-cert.sh` needs to be adjusted for new distros. Currently the letsencrypt script fails on **Ubuntu 20.04 Focal Fossa**.

certbot GitHub issue for reference:

<https://github.com/certbot/certbot/issues/7941#>

> We’re planning on deprecating certbot-auto later this year though so we’re not going to add support for Ubuntu 20.04 to it. 
Our recommended instructions for installing Certbot on Ubuntu 20.04 can be found at https://certbot.eff.org/lets-encrypt/ubuntuother-other 

Jitsi Community Forum Thread for reference:

<https://community.jitsi.org/t/script-for-ssl-certificate-creation-broken-on-20-04-focal-fossa/43555>

## Current behavior
---
fails with:
```
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

## Expected Behavior
---

## Possible Solution
---
Maybe replace `certbot-auto` with `certbot` in the script?

## Steps to reproduce
---
```
wget https://dl.eff.org/certbot-auto
sudo chmod a+x ./certbot-auto

sudo ./certbot-auto --install-only --verbose
```

# Environment details
---

**Ubuntu 20.04 Focal Fossa**

**Comment by Porthorian** [comment]
https://github.com/jitsi/jitsi-meet/issues/6341

**Comment by khoschi** [comment]
I had the same issue, resulting from a version conflict python2 vs. python3.
On ubuntu focal remove certbot package, cron and config files in
/usr/local/share/ca-certificates/,  /usr/local/sbin/certbot-auto and /etc/cron.weekly
then install certbot from offical sources. Test in shell with
certbot renew --dry-run
and add new cron job. Certificates can be reused.
