### ISSUE TITLE
Add a warning or a certbot workaround for Ubuntu 20.04 in the documentation

### ISSUE THREAD

**Issue by Franky1** [jitsi/jitsi-meet#6372]
**Is your feature request related to a problem you are facing?**

Script for SSL certificate creation is broken on 20.04 Focal Fossa.
Details see #6371 

**Describe the solution you'd like**

People start to use Ubuntu 20.04
The certbot installation script for jitsi has to be adjusted.
Either add a warning or a workaround for Ubuntu 20.04 in the documentation.
Otherwise the community forum will be flooded with even more avoidable threads…

**Comment by vjleo** [comment]
Hi I had the same error, installed on a ubuntu 18

**Comment by Franky1** [comment]
@vjleo 
I assume, this had another reason.

I cannot confirm your error.
Just started a fresh Ubuntu 18.04. in Virtualbox and installation of `certbot-auto` worked.

**Comment by ranrinc** [comment]
@Franky1 yes 20.04 main certbot package did not install the right nginx packages.

to install certbot correctly you can do
1. Install via snaps `sudo snap install certbot --beta --classic` but not for ARM64
2. 
```
sudo add-apt-repository ppa:ahasenack/certbot-tlssni01-1875471
sudo apt-get update
```
which fixed the nginx problems.

Thanks to Andreas for his ppa.

Enjoy

**Comment by chout0000** [comment]
[good](https://pomeranian4homepups.com/pomeranian-puppies-for-sale/) [ideal](https://pomeranian4homepups.com/pomeranian-puppies-for-sale/)

**Comment by chout0000** [comment]
[nice](https://healthycavalierkingcharlesspanielpuppies.com/cavalier-king-charles-spaniel-puppies-for-sale/) [ideal](https://healthycavalierkingcharlesspanielpuppies.com/cavalier-king-charles-spaniel-puppies-for-sale/)
