### ISSUE TITLE
Nextcloud Record Meetings

### ISSUE THREAD

**Issue by sunjam** [jitsi/jitsi-meet#6375]
Related to https://github.com/jitsi/jitsi-meet/issues/5402

I'd be great to add proper handling of meeting recordings to Nextcloud and it seems most all the basic pieces are in place.  [See this discussion on the forum](https://help.nextcloud.com/t/save-jitsi-meeting-recordings-to-nextcloud/79275)

**Comment by Echolon** [comment]
Duplicate of #5800
