### ISSUE TITLE
Jitsi user statistics

### ISSUE THREAD

**Issue by GianlucaPoliTo** [jitsi/jitsi-meet#6376]
Hi,
I would like to know if there is a simple way to collect user statistics.
To be clearer, I mean the statistics that are shown in the HTML page if you pass the mouse on a little video.
How can I obtain those statistics?
I have analyzed the window.JitsiMeetJS object but I was unable to obtain them.

The final purpose is to send that information to my server.

Thank you!

**Comment by chris246** [comment]
Does this work for you?
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md

**Comment by GianlucaPoliTo** [comment]
Hi @chris246 , thank you for the answer.
The file that you have mentioned could be a good start, but, I'm really interested to obtain also something like this:
stats = {"audio_caller" : [ SSRC,  PT, ..], 
             "video_caller" : [SSRC, PT, RESOLUTION, ...]
              }
In particular, some of those information are just reported in Jitsi-meet if you visit "little-video".
The problem is that I don't be able to capture the statistics, or better, I don't understand where they are generated.
Do you know anything about them?

Thanks!

**Comment by chris246** [comment]
Sorry, no. I'm just a user and used these statistics for server monitoring.

If the traffic is running via the videobridge (and not peer2peer), you can maybe add them to the API.
I suppose the stats in the web ui are sent via WebRTC/websockets as I don't remember seeing them in the Developer Console. If you find out where/ho they are transmitted, you can maybe hook in there.
