### ISSUE TITLE
[modules/xmpp/ChatRoom.js] <discoRoomInfo/<>:  No meeting ID from backend

### ISSUE THREAD

**Issue by anshad** [jitsi/jitsi-meet#6377]
## Description
The second person not getting the chat message sent by other person on a conference

## Current behavior
User is able to sent chat but the other person not getting it

## Expected Behavior
Users on the conference should be able to send and receive chat messages 

## Possible Solution
Provide configuration details on the documentation to enable or setup chat functionality

# Environment details
I have installed latest version of jitsi on Ubuntu using package installer, then replaced jitsi-meet with GitHub copy for custom functionalities.

**Comment by saghul** [comment]
@damencho any idea?

**Comment by damencho** [comment]
Which prosody version are you using? The module responsible for setting this is: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_meeting_id.lua
You should have it enabled like this: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L55

**Comment by saghul** [comment]
Hum, I don't think we are enabling that module on the Docker setup. Should we?

**Comment by damencho** [comment]
Yep, good to be enabled, it is by default with debian install.
We do not widely use it at the moment in the open-source repo ... but working with stats this meeting it will be identifying meetings across components.
