### ISSUE TITLE
Leaving screen sharing doesn’t restore tile view

### ISSUE THREAD

**Issue by chris-morgan** [jitsi/jitsi-meet#6379]
## Description
When screen sharing concludes, participants are not returned the view they were in previously.

## Steps to reproduce
1. Alice and Bob join a meeting.
2. Alice switches to tile view.
3. Bob starts screen sharing.
4. Bob stops screen sharing.

## Current behavior
Alice is returned to the speaker view.

## Expected behavior
Alice should be returned to tile view.

## Possible solution
When receiving a shared screen, store the view you were in before hand, and restore it afterwards.

## Environment details
meet.jit.si, today.

**Comment by smatt989** [comment]
would also like to understand how to resolve this issue!
