### ISSUE TITLE
How can interfaceconfig.js and config.js be used directly without reference in other modules? Modifying these two files in the local environment will not take effect. If docker is used, it will take effect

### ISSUE THREAD

**Issue by Lydon2** [jitsi/jitsi-meet#6381]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by Echolon** [comment]
@Lydon2 please refer to the Jitsi Meet Community Forum first with you problem.
