### ISSUE TITLE
When the meeting is on, the camera and microphone are on by default. How to make them turn off by default when entering the meeting

### ISSUE THREAD

**Issue by Lydon2** [jitsi/jitsi-meet#6382]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by chris246** [comment]
You can either set them on the server-side in /etc/jitsi/meet/[your domain]-config.js
Set & uncomment
```javascript
startWithAudioMuted: true,
startWithVideoMuted: true,
```

or on the client side (per Channel):
* In the bottom-left corner click on the three dots
* Then Settings
* Open tab More
* Check Everyone starts muted or Everyone starts hidden (no video)

**Comment by saghul** [comment]
We now have a "pre-join" page which when enabled allows the user to select devices before the actual join happens. It's in master but not released yet.

**Comment by Echolon** [comment]
@Lydon2 would you be so kind and for all of your issues create short but clear titles? That would help a lot!

**Comment by Echolon** [comment]
@saghul I will close this. Hope you agree!
