### ISSUE TITLE
Screen Sharing on Wayland not Possible

### ISSUE THREAD

**Issue by philschenker** [jitsi/jitsi-meet#6389]
## Description
I can't share any windows running with Wayland or the whole screen when I started a session on meet.jit.si. I'm running on sway (i3 alternative running Wayland only). I can select XWayland windows and sharing of those works.

## Current behavior
I can only share XWayland windows.

## Expected Behavior
I would like to share all windows also those running on Wayland

## Possible Solution
---

## Steps to reproduce
---

# Environment details
Running latest Manjaro with 5.5.8 kernel on Sway

**Comment by ibauersachs** [comment]
> @ibauersachs I think it would be better to move the issue to the correct repo instead of closing it.

Done. I didn't notice this is possible now...

**Comment by snaggen** [comment]
I have shared my screen successfully using meet.jet.si and latest firefox on Fedora 32. It uses xda-desktop-portal (which uses pipewire) for sceencapturing, and I'm not sure sway supports that yet (even though I have seen some activity around that lately). 
So my guess is that this is more of an issue with sway, than with jitsi.

**Comment by saghul** [comment]
Closing since there is nothing we can do from the Jitsi Meet side. The browser must have support for this.
