### ISSUE TITLE
muc_max_occupants error

### ISSUE THREAD

**Issue by petrohiv** [jitsi/jitsi-meet#6392]
## Description
Couldn't use muc_max_occupants module until I fixed it's code.

## Current behavior
With the line (/usr/share/jitsi-meet/prosody-plugins/mod_muc_max_occupants.lua: line 11) going as
```local whitelist = module:get_option_set("muc_access_whitelist");```
I get the following error:
```
2020-04-26 14:08:42 c2s555b6a155ef0     error   Traceback[c2s]: ...jitsi-meet/prosody-plugins/mod_muc_max_occupants.lua:30: attempt to index upvalue 'whitelist' (a nil value)
stack traceback:
        ...jitsi-meet/prosody-plugins/mod_muc_max_occupants.lua:30: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        (tail call): ?
        /usr/lib/prosody/modules/muc/muc.lib.lua:406: in function </usr/lib/prosody/modules/muc/muc.lib.lua:388>
        (tail call): ?
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/core/stanza_router.lua:187: in function 'core_post_stanza'
        /usr/lib/prosody/core/stanza_router.lua:135: in function 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:254: in function 'func'
        /usr/lib/prosody/util/async.lua:90: in function </usr/lib/prosody/util/async.lua:88>
```

## Expected Behavior
Limiting the number of conference participants

## Possible Solution
With the line going as 
```local whitelist = module:get_option_set("muc_access_whitelist",{});```
it works just fine. I suggest you to fix the module code. I can't give you a PR since I don't have an acces to printer and scaner currently so can't submit this consent paper of yours.

# Environment details
```
:~$ sudo prosodyctl about
Prosody trunk nightly build 747 (2017-02-19, 428d4abee723)

# Prosody directories
Data directory:     /var/lib/prosody
Config directory:   /etc/prosody
Source directory:   /usr/lib/prosody
Plugin directories:
  /usr/share/jitsi-meet/prosody-plugins/
  /usr/lib/prosody/modules/


# Lua environment
Lua version:                    Lua 5.1

Lua module search paths:
  /usr/lib/prosody/?.lua
  /usr/local/share/lua/5.1/?.lua
  /usr/local/share/lua/5.1/?/init.lua
  /usr/local/lib/lua/5.1/?.lua
  /usr/local/lib/lua/5.1/?/init.lua
  /usr/share/lua/5.1/?.lua
  /usr/share/lua/5.1/?/init.lua

Lua C module search paths:
  /usr/lib/prosody/?.so
  /usr/local/lib/lua/5.1/?.so
  /usr/lib/x86_64-linux-gnu/lua/5.1/?.so
  /usr/lib/lua/5.1/?.so
  /usr/local/lib/lua/5.1/loadall.so

LuaRocks:               Not installed

# Lua module versions
lfs:            LuaFileSystem 1.6.3
libevent:       2.1.8-stable
luaevent:       0.4.4
lxp:            LuaExpat 1.3.0
socket:         LuaSocket 3.0-rc1
ssl:            0.6
```

**Comment by bastischubert** [comment]
Have you tried setting muc_access_whitelist in the config, instead of monkeypatching?

**Comment by petrohiv** [comment]
@bastischubert Tone of your comment isn't nice at all. Are you compensating something with that kind of behavior? 
Now I found out that there was a typo in my config. Therefore I'm closing this issue.

**Comment by lebreRafael** [comment]
@petrohiv Hey! Where was the typo? I'm trying to fix this same error.

**Comment by petrohiv** [comment]
@lebreRafael Hi! My mistake was "muc_accesss_whitelist" instead if "muc_access_whitelist" (extra "s" in "access"). But also I'd like you to pay attention on Prosody version you use - I wasn't able to use this module until I installed Prosody 0.11. I didn't have any errors in logs with Prosody 0.10 but module just didn't work.

**Comment by lebreRafael** [comment]
@petrohiv Thank you so much. My prosody version was ok. I fixed this by adding ```muc_access_whitelist = {}```
