### ISSUE TITLE
/doc/README.md has a circular link

### ISSUE THREAD

**Issue by kjcole** [jitsi/jitsi-meet#6401]
## Description

https://github.com/jitsi/jitsi-meet/blob/master/doc/README.md

/doc/README.md has a link to video tutorials (https://jitsi.org/tutorials/) that redirects back to /doc/README.md. Specifically:

* [Video tutorials on deployment and scalability](https://jitsi.org/tutorials/)

---

## Current behavior

Following the link goes nowhere.

---

## Expected Behavior

Following the link should take me to video tutorials.

---

## Possible Solution

Fixing the URL.

---

## Steps to reproduce

Click the link.

---

# Environment details

80% nitrogen, 20% oxygen.  100% GitHub web interface. 😉

---

**Comment by DipanshiB** [comment]
Should the link go to the installation for linux server video tutorial available on the YouTube channel? Specifically this link? 
[https://www.youtube.com/watch?v=8KR0AhDZF2A]
Or should a new tutorials page be developed providing the video tutorials there?

**Comment by saghul** [comment]
Fixed the links on the jitsi.org site, it now redirects to the handbook. Thanks for the heads up!
