### ISSUE TITLE
no se puede acceder a la cámara

### ISSUE THREAD

**Issue by makudan** [jitsi/jitsi-meet#6402]
Hola! en el programa Jitsi Meet no puedo acceder a la cámara de la computadora. Tiene instalada Webcam Companion

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
