### ISSUE TITLE
Copying the invitation to clipboard doesn't include the password

### ISSUE THREAD

**Issue by b90g** [jitsi/jitsi-meet#6403]
#Description
---
Copying the invitation credentials on a password secured session doesn't include the password.

## Current behavior 
---
When copying the invitation credentials with a session where there is a passsword set, the password does not get copied to the clipboard, when pressing the `copy`-text:
```
You are invited to join a meeting.
Join the meeting:
https://meet.jit.si/iueso8i-930ur-f082yr-9

To join by phone instead, tap this: +1.512.402.2718,,3188929399#

Looking for a different dial-in number?
See meeting dial-in numbers: https://meet.jit.si/static/dialInInfo.html?room=iueso8i-930ur-f082yr-9


If also dialing-in through a room phone, join without connecting to audio: https://meet.jit.si/iueso8i-930ur-f082yr-9#config.startSilent=true
```
## Expected Behavior
---
Clicking on the copy "button" should result in:

```
You are invited to join a meeting.
Join the meeting:
https://meet.jit.si/iueso8i-930ur-f082yr-9
Password: oieqpfeege

To join by phone instead, tap this: +1.512.402.2718,,3188929399#

Looking for a different dial-in number?
See meeting dial-in numbers: https://meet.jit.si/static/dialInInfo.html?room=iueso8i-930ur-f082yr-9


If also dialing-in through a room phone, join without connecting to audio: https://meet.jit.si/iueso8i-930ur-f082yr-9#config.startSilent=true
```
*note: there is an extra line that includes the password

## Possible Solution
---
include the password the user set.

## Steps to reproduce
---

1. open a session
2. set a password on the session
3. click the copy button

Result: credentials without password.

# Environment details
---

meet.jit.si & other servers which use the current latest release.

**Comment by MagicFab** [comment]
Someone asked about this in the forums : 

https://community.jitsi.org/t/copy-share-password/51813/2

**Comment by foxpalace** [comment]
haha - you linked this to a thread which is linked to this thread here :)
I am missing this feature to - tell users to paste the password manually after pasting invitation ;)

**Comment by b90g** [comment]
> haha - you linked this to a thread which is linked to this thread here - loops back to myself :)
> I am missing this feature too - tell users to paste the password manually after pasting invitation ;)

Thanks, I do that alread, this issue was opened because i don't want to teach users how to invite people although there is a function that should copy the credentials. ;(

**Comment by MagicFab** [comment]
Another mention here : 

https://community.jitsi.org/t/password-setting/40801/19

**Comment by slytomcat** [comment]
I also vote for this feature. It's very inconvenient to copy password line in additional to invitation.

**Comment by luixxiul** [comment]
@slytomcat this *might* be intended for security concern and I don't think it's gonna happen by default. Implementing as an option could, though.

**Comment by slytomcat** [comment]
I don't think that this might be intended for security concern. 
If I want to share the conference details to someone, it is obviously that I have to pass the password also.

**Comment by luixxiul** [comment]
> If I want to share the conference details to someone, it is obviously that I have to pass the password also.

You could send the message someone unintended by mistake or the receiver could forward it to someone untended by mistake too. Unless the message would be encrypted with PGP or something, anyone could spoof the message. It's like sending username and password at the same time. I am not sure the thought behind the implementation as I haven't touched the code, still enabling this function would lead to the security concern as I mentioned.

**Comment by foxpalace** [comment]
hahaha - this mistake could even happen, when i copied the password manual in my mail - what arguments in 2020 :)

**Comment by foxpalace** [comment]
so, it's better not using a passwordprotection, because I can send it via email ;)
in this case passwordprotection is absolutly dangerous and can removed ;)

**Comment by luixxiul** [comment]
@foxpalace you will be banned if you keep posting unrelated comments.

**Comment by b90g** [comment]
> > If I want to share the conference details to someone, it is obviously that I have to pass the password also.
> 
> You could send the message someone unintended by mistake or the receiver could forward it to someone untended by mistake too. Unless the message would be encrypted with PGP or something, anyone could spoof the message. It's like sending plain username and password at the same time. I am not sure the thought behind the implementation as I haven't touched the code, still enabling this function would lead to the security concern as I mentioned.

What the user does with the copied credentials is absolutely in the power of the user....
Fact is i am getting support requests why peple cant join a session, only to find out that there is a password set that wasnt sent by the copied text. 
If you keep going to have this disscussion i am going to close the issue and you cant find someone else to report issies/enhancements...

**Comment by luixxiul** [comment]
Why don't you join https://github.com/jitsi/jitsi-meet/issues/5653? Especially on: `Fix the password-setting UX.`

**Comment by saghul** [comment]
The password can change any time, so I’m not sure it’s a good idea to put it there.

We are very close to launching the “lobby” which is another mechanism for letting users in and preventing others from joining which doesn’t require a password.
