### ISSUE TITLE
Android - Display toolbar from Activity

### ISSUE THREAD

**Issue by clement-petitcunot** [jitsi/jitsi-meet#6405]
I currently implement the Jitsi SDK in my Android application with the latest version (2.8.0).
The purpose of the application is to be able to use Jitsi's functionalities on a hands-free solution (so only through voice commands). 
Everything works at 99% but there is just one problem I can't solve.

On a classic Android device, if I want the toolbar to appear ("Stop a call", "Hide/Show camera"... ), we need to click on the view. 
Not having this possibility to perform this action, is there a function that can be called from my Activity to display this bar?

**Comment by saghul** [comment]
This is not currently possible, sorry. One thing I can think of is a feature flag which toggles the "always sshow toolbox" behavior. Would that help?

**Comment by clement-petitcunot** [comment]
Hi @saghul,

Thank you for your response. 

Upon closer analysis of your source code, I suspected that this was not possible. 
With a colleague, we looked into this problem and submitted a PR ( https://github.com/jitsi/jitsi-meet/pull/6436 ) that fixes our problem and fits perfectly with the idea you mentioned. 

I invite you to take a look at it 😉

**Comment by saghul** [comment]
Ah, nice! I just reviewed and approved it! I'll merge it once tests pass, but you can count on it being part of the next release.

**Comment by clement-petitcunot** [comment]
That's great!! We're looking forward to the next release then :) 
Thanks you very much.
