### ISSUE TITLE
Mux video stream on the server to reduce client bandwith

### ISSUE THREAD

**Issue by MartinDelille** [jitsi/jitsi-meet#6408]
## Description

I write this bug that could also be a feature request because after using *Jitsi* for several week, I notice that when doing conference with a large amount of people, the ones with the lowest connection where unable to see other people face.

I deduced that *Jitsi* is not computing a unified video stream but sending each participant stream to everyone (which doesn't seems to be the behavior of other solution like Z...m.

## Current behavior

The server to client stream increase with the amount of participant.

## Expected Behavior

The server to client stream is constant whatever the amount of participant.

## Possible Solution

Mux the stream on the server.

## Steps to reproduce

Create a conference with several people with a low connection and ask the people to open their webcam one after the other.

# Environment details

*Jitsi* is installed on a virtual server on [Google Cloud Plateform](https://cloud.google.com).

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

This is how [SFU](https://webrtcglossary.com/sfu/) works, this is jitsi-videobridge. If you need serverside mixing of streams you need MCU, which is not what we do.

**Comment by MartinDelille** [comment]
Ok thank for the answer and sorry for the noise!
