### ISSUE TITLE
Screen share quality is rather bad

### ISSUE THREAD

**Issue by Razzeee** [jitsi/jitsi-meet#6409]
**Is your feature request related to a problem you are facing?**
Screens sharing, especially in code editors is not ideal. It's readable, but most fonts get pixelated. Another thing that happens is that the complete quality degrades after scrolling and quality improves over time after that.

**Describe the solution you'd like**
Screen share quality should be improved. It might be possible to use a different codec that's optimized for screen sharing? Or is the problem just caused by low resolution and slow recovery after scrolling.

**Describe alternatives you've considered**
My alternative solution is to use different tools to screen share, other then jitsi. VSCode for e.g. has extensions for this.

**Comment by Razzeee** [comment]
I don't think this should be closed

**Comment by davidak** [comment]
We had this issue also in the last weeks. Here is a recording of a meeting: https://www.youtube.com/watch?v=6J368HqsJQE

We used a different instance of jitsi meet today and the picture was perfectly sharp and readable. So i guess https://meet.jit.si/ is just overloaded at times.

**Comment by Razzeee** [comment]
My case was actually with a selfhosted instance, but I haven't retested recently.

**Comment by pgenderson** [comment]
@Razzeee have you tested it since?

**Comment by Razzeee** [comment]
No, feel free to close this, my company settled for something closed source
unfortunately.

**Comment by deepbluev7** [comment]
I have this issue too and I think it is related to the network bandwith adaption. Basically it seems like the image quality gets reduced, when bandwidth is low. While that makes sense for normal video, screensharing should instead drop frames or reduce FPS. Most screen share content is somewhat static, so dropping frames is not as bad as having a blurry video feed.

**Comment by saghul** [comment]
We are actively looking into this. Alas it's not a simple fix.

**Comment by deepbluev7** [comment]
That's awesome, thank you so much!

**Comment by gcommit** [comment]
Same issue here - is there anything we can do ?!

**Comment by paweldomas** [comment]
one thing to be on the lookout when it comes to screensharing is to not send too big window, when you're sending 4k monitor screen (or even 2k or something close to that), then viewers may not be displaying it large it enough so it gets scaled down and blurred even if it goes in large resolution on the wire (and would look fine after stretching the window on the receiver side).

**Comment by gcommit** [comment]
in the config.js of jitsi i changed the following, which resolved my issue completly, increased stability and increased quality. Enabling Simulcast and it gets as bad as it could get. with this settings now, a screensharing looks like it is my own screen and participants have the same resolution as my own videoscreen: 

```
resolution: 480,
 
constraints: {
video: {
aspectRatio: 4 / 3,
height: {
ideal: 480,
max: 480,
min: 180
}
}
},
 
disableSimulcast: true,
 
enableLayerSuspension: false,
 
preferH264: true,
 
disableH264: false,
 
disableRtx: true,
 
enableTcc: true,
 
desktopSharingFrameRate: {
min: 25,
max: 25
},
```

**Comment by umerf52** [comment]
@saghul any updates on the fix and are there any test builds to try?
I'm asking regarding docker deployment.

**Comment by adamcrisp** [comment]
Hi.

I think the wobble is because of the scaling between the desktop source video and the frame it's drawn in on the browser.
Screen share video does not fit the full screen - you get a black border under where the participants are shown
Normal video does fit the full screen.

To fix click on the ">" chevron on the bottom right to hide the participants and then press F11 for full screen.

Hope this helps.

Adam

**Comment by jsrobinson3** [comment]
Using the latest beta build and setting preferredCodec to VP9 seems to have resolved the issue for us but VP9 is still being tested. H264 also seems to work but then there seems to be bandwidth issues since you cannot use Simulcast.
```    // Specify the settings for video quality optimizations on the client.
     videoQuality: {
        preferredCodec: 'VP9',
        maxBitratesVideo: {
            low: 200000,
            standard: 500000,
            high: 1500000
        },
        minHeightForQualityLvl: {
            360: 'standard',
            720: 'high'
        },

**Comment by BlueOwlet** [comment]
I'm still having this issue 2024.

Some of my users have wide gaming monitors and they DEFINITELY experience this issue. They all mention that SHARING A SMALLER SIZED WINDOWS DOES HELP.

**Comment by raishid** [comment]
same
