### ISSUE TITLE
Audio lost for some recipients

### ISSUE THREAD

**Issue by jaragunde** [jitsi/jitsi-meet#641]
In rare occasions, audio seems to be lost only for some recipients. For example, in a call among three people named A, B and C, A can hear both B and C, C can hear both A and B, but B cannot hear C.

**Comment by tdokta** [comment]
Having a similar issue. Five connections into the meetup, every time there is a sound issue where one can hear audio transmission from the host and no one else can. 

Although tonight there was the opposite, I joined the group and couldn't get sound everyone else could. 

Have resolved the audio issue at times with reboot by the meetup host.

**Comment by philip-n** [comment]
Just want to add another case to this issue. We had a call with 10 people, and most of us could hear each other just fine. However, two people A & B could not hear one specific person C and (I guess) vice versa. 

I was person A and I saw the indicator that person C was speaking (small icon in his avatar box), but just heard nothing. We tried different things (having person C disconnect and reconnect multiple times, muting everybody else, ...) that did not solve the problem.

In the end, we had everybody disconnect and join the room again, which mostly solved the problem.

**Comment by psaavedra** [comment]
This bug still eventually happends. In some observed situation the affected peer can not reconnect safely to the conference, even with other browser or incognito mode. For those case, only the creation of a new room with different name and moving all the participants to this one is the unique possible workaround.

**Comment by cathalgarvey** [comment]
Can confirm

**Comment by psaavedra** [comment]
The problem is still in the latest stable version.

**Comment by johnxie** [comment]
Can confirm this still happens.

**Comment by tdokta** [comment]
Hi, this problem was about three or four years ago. I no longer use jitsi.
Thanks

**Comment by smbteam1** [comment]
@johnxie : Yes we are facing this issue. Audio gets disconnected on some occasions. We are using latest jitsi SDK 2.0 version.

**Comment by johnxie** [comment]
This is still happening occasionally when connecting with multiple parties across different timezones. Parties in the same timezone can communicate no problem, but the conference is split. Any solutions anyone found?

**Comment by damencho** [comment]
@johnxie when this happens it is worth reporting it in the community forum with a link to the meeting so we can investigate. And make sure that the person that you don't hear or cannot hear is not using Firefox, there are some known issues there that we will be working on improving.

**Comment by tanguy-opendsi** [comment]
Hi,
Same troubles here, our users need to refresh browser. 
I disable P2P
Debian : 10 
jitsi-meet  *** 1.0.4101-1 
jicofo
 *** 1.0-508-1 

jitsi-videobridge:
 *** 1126-1
