### ISSUE TITLE
Need disable options for some JitsiMeetConferenceOptions in iOS app

### ISSUE THREAD

**Issue by V1992** [jitsi/jitsi-meet#6412]
Please add option to disable JitsiMeetConferenceOptions like  add meeting password and start live stream options for mobile apps.
For now only few are available.
We need to disable other options too.

**Comment by nedimf** [comment]
I second this, this really should be done.

**Comment by nedimf** [comment]
@saghul is it possible to add PR on this option?

**Comment by saghul** [comment]
We have a bunch of flag now: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js feel free to create PRs for new flags.

**Comment by V1992** [comment]
> We have a bunch of flag now: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js feel free to create PRs for new flags.

Thanks for adding flags.
I tried the same, by setting few flags as false it's working fine.
But I can't able to hide these three options by set as false.

            builder.setFeatureFlag("meeting-password.enabled", withValue: false)
            builder.setFeatureFlag("live-streaming.enabled", withBoolean: false)
            builder.setFeatureFlag("raise-hand.enabled", withBoolean: false)
pls chck.
And please add a flag to hide meeting info option also.

![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/12439866/81944603-a0d74500-961a-11ea-9c6e-f33abcb7c96e.jpeg)

**Comment by thesiliconvalley** [comment]
Hi, I've a quick question here 
Do we have a way to hide toolbar (shown in screenshot)? 
![image](https://user-images.githubusercontent.com/52095823/82052903-076f6800-96da-11ea-9706-0ff904acf399.png)

Android SDK

**Comment by luixxiul** [comment]
@thesiliconvalley would you mind elaborating the difference between your question and a feature request above that?

**Comment by thesiliconvalley** [comment]
Hi, the above request is mentioned for IOS while I was trying to figure out
the same for android. I've seen that these options are actually working for
integration over web  ( according to this doc
https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) but I want to
implement similar one for Android. I hope this description made my question
more clear to you. Thanks

**Comment by nishantt12** [comment]
RNJitsiMeetConferenceOptions options = new RNJitsiMeetConferenceOptions.Builder()
   .setRoom(url)
   .setWelcomePageEnabled(false)
   .setAudioOnly(false)
   .setFeatureFlag("pip.enabled",false) // <- this line you have to add
   .setFeatureFlag("calendar.enabled",false)  // optional
   .setFeatureFlag("call-integration.enabled",false)  // optional
  .setFeatureFlag("pip.enabled",false)
    .setFeatureFlag("calendar.enabled",false)
   .setFeatureFlag("call-integration.enabled",false)
  .setFeatureFlag("close-captions.enabled",false)
   .setFeatureFlag("chat.enabled",false)
   .setFeatureFlag("invite.enabled",false)
   .setFeatureFlag("live-streaming.enabled",false)
   .setFeatureFlag("meeting-name.enabled",false)
   .setFeatureFlag("meeting-password.enabled",false)
   .setFeatureFlag("raise-hand.enabled",false)
   .setFeatureFlag("video-share.enabled",false)
   .setUserInfo(_userInfo)
   .build();
this line what you need add this.
.setFeatureFlag("pip.enabled",false)

here is all flags you can set
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js

I tried these changes but they are not working except .setFeatureFlag("chat.enabled",false).

I can still see all these options when I click on 3 dots on the right side of the screen.

**Comment by kaustavhazra** [comment]
@nishantt12  Yes, I also face this issue, Till now can't solve the problem . Have you got any solution?

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by saghul** [comment]
All of those and more are implemented in the latest SDK (3.7.0 at the time of this writing).

**Comment by amjidkhanmohmand** [comment]
Hello, I am using sdk 5.0.2 but I am still facing this issue. I am using the following flags, 
`.setFeatureFlag("security-options.enabled", false)
 .setFeatureFlag("raise-hand.enabled", false)`

but I am still seeing them in the layout, don't know why

**Comment by amjidkhanmohmand** [comment]
Kindly let me know as soon as possible
