### ISSUE TITLE
Password entry field disappears if mouse is below browser window

### ISSUE THREAD

**Issue by xerces8** [jitsi/jitsi-meet#6413]
## Description

The password entry box disappears after a few seconds, while the user is typing the password.

---

## Current behavior

Password (info tile) entry field disappears.

---
## Expected Behavior

Do not disappears igf the user is using it.

---
## Possible Solution
---

## Steps to reproduce

open https://meet.jit.si/
click Go
dismiss any message boxes
click the (i) icon in the lower right corner
in the tile click Add Password
move the pointer pointer slightly below the browser window
start typing a password
after a few seconds the entire tile disappears, breaking the password entry procedure

---

# Environment details

Firefox 75.0 64 bit on Windows 10

---

**Comment by saghul** [comment]
Closing since the password prompt got refactored into a new dialog and this should no longer happen.
