### ISSUE TITLE
[BUG] Mobile app promo links broken on latest unstable

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#6415]
Updated today to latest debian unstable packages and noticed that I can no longer set my mobile app's URL in interface_config.js as before.

If I try to change the URL from jitsi-meet to my app the conference never starts.

Chrome dev console shows the following error:
Uncaught SyntaxError: Unexpected identifier  pointing to the mobile download links (tried with iOS and Android - same issue)
    MOBILE_DOWNLOAD_LINK_ANDROID: 'https://play.google.com/store/apps/details?id=my.app.package',

Did something change recently regarding URL's for our own mobile apps? I've tested on another server also running unstable and the exact same bug happens.

Thanks

**Comment by blalop** [comment]
I've found the same issue. For some reason, user defined URLs for mobile download apps are ignored and a Firebase dynamic link is always generated. I know that this dynamic link can be configured through interfaceConfig.MOBILE_DYNAMIC_LINK, but I thougth this is not mandatory as MOBILE_DOWNLOAD_LINK_ANDROID and MOBILE_DOWNLOAD_LINK_IOS are present.

**Comment by pdarcos** [comment]
Thanks  @blalop 

@saghul the bug has been confirmed

**Comment by saghul** [comment]
I donm't think we've changed anything there and a quick inspecction of the code doesn't shed any light, it looks ok here. Do you have a deployment where I could test this?

**Comment by pdarcos** [comment]
@saghul I'll email you privately to give you access to my deployment

**Comment by pdarcos** [comment]
@saghul did you get my email?

**Comment by saghul** [comment]
Just checked, yep.

**Comment by pdarcos** [comment]
You've got mail.

By the way, maybe the problem is that these values are hardcoded?
https://github.com/jitsi/jitsi-meet/blob/17c1f50fc3b993e4da5acdebf920cc6328f020a8/react/features/deep-linking/components/DeepLinkingMobilePage.web.js#L181

**Comment by blalop** [comment]
That should not be a problem, as that value is only used as fallback.


What I found is that some lines before that:

https://github.com/jitsi/jitsi-meet/blob/17c1f50fc3b993e4da5acdebf920cc6328f020a8/react/features/deep-linking/components/DeepLinkingMobilePage.web.js#L168

The URL is returned inmediatly if it exists. So, whenever the link is configured for the platform you're in, that URL shall be returned. But somehow, that condition is never satisfied and instead the default link that is generated at line 183 includes both variables in its URL as part of the interfaceConfig parameter.

**Comment by pdarcos** [comment]
In my case I had forgotten to put the , after SHOW_CHROME_EXTENSION_BANNER: false

Now it points to my mobile apps OK.

I'm going to close this issue since it's fixed for me. Feel free to re-open if you're still having problems.

Much thanks to @saghul

**Comment by blalop** [comment]
I'd like to reopen this issue.

When using the external API, the provided mobile download links are not properly binded.

I've found that inside the _generateDownloadURL function, the links are defined inside the interfaceConfig object, but undefined inside the _URLS object. Thus, the firebase fallback URL is always generated.

This can be fixed using the interfaceConfig directly and ignoring the _URLS object.

**Comment by blalop** [comment]
We are at #6489

**Comment by DevAgrawal** [comment]
Can someone please tell me how to alter the jitsi-meet after integrate in android i.e. remove icon and functionality of recording while ongoing call?
