### ISSUE TITLE
[BUG][Mobile App]: Cannot join existing room on android with JWT enabled

### ISSUE THREAD

**Issue by hmharshit** [jitsi/jitsi-meet#6416]
## Description
I have a custom deployment of the jitsi-meet instance. I’ve enabled the JWT authentication also. Everything is working fine when we join using Web Client.

But if I use any android or ios app to join the existing room, It doesn’t join the room and shows forever loading.

## Current behavior
It tries to join the existing room but it's not able to join and doesn't transmit any audio or video.

![image](https://user-images.githubusercontent.com/21979074/80399750-55612f00-88d7-11ea-913a-735f95db549f.png)

## Expected Behavior
It should join the room without any issues.

## Possible Solution
I'm not sure about the possible solution.

## Steps to reproduce
Enable JWT authentication on the server-side. Then try to join any existing room with the mobile application.
# Environment details

**Comment by felix-voicehub** [comment]
I'm not familiar with the integration, but do you pass the JWT token with the room url on android? Like `yourjitsi.example.com/room?jwt=TOKEN_HERE`.

**Comment by hmharshit** [comment]
@felix-voicehub You don't need to pass the token explicitly to the URL. You just need to dispatch a Redux action to set JWT token on the mobile app side.

Correct me if I'm wrong.

**Comment by nedimf** [comment]
You have to pass token somewhere. Passing it in url as parameter as @felix-voicehub  said or anyother way token must be sent to server to confirm authentication.

**Comment by fritzfr** [comment]
@hmharshit Again, I'm not familiar with your implementation and what the redux action might do (I expect something local/client-side). In any case, the token needs to be sent to the server, so try appending it to the url.

**Comment by saghul** [comment]
> @felix-voicehub You don't need to pass the token explicitly to the URL. You just need to dispatch a Redux action to set JWT token on the mobile app side.
> 
> Correct me if I'm wrong.

You should use the URL parameter. This way things will happen in the right order. You can modify the code to dispatch the action as you wish, but then nodoby can help you because nobody knows what your code does.

**Comment by rananajam1** [comment]
@hmharshit did you fix this?
