### ISSUE TITLE
Where is android-20.2.3 tag ?

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jitsi-meet#6418]

**Comment by licaon-kter** [comment]
I'd like for Android users to be able to setup meetings with passwords, any reason to publish only on Play and not tag here?

**Comment by saghul** [comment]
It’s here: https://github.com/jitsi/jitsi-meet/releases/tag/android-20.2.3

**Comment by saghul** [comment]
I don’t know what you mean about passwords, that has nothing to do with the tag, which was already published days ago.

**Comment by licaon-kter** [comment]
I've looked for the tag for days, not sure **where** was it published exactly, because trying to acces it directly was 404-ing.

Regarding passwords, that was fixed in lib-jitsi-meet weeks ago and new version of the app with the updated pom.xml was not **yet** published.

**Comment by licaon-kter** [comment]
I see 20.4.1 in Play store but no such tag, only the _older_ https://github.com/jitsi/jitsi-meet/releases/tag/android-20.4.0

Which commit is the Play version build at?

**Comment by licaon-kter** [comment]
Thanks

**Comment by licaon-kter** [comment]
Is there a problem with pushing tags to Github? 20 days later and android-20.4.2 is still not here, but the app is on Play.

**Comment by saghul** [comment]
There is no problem, it's a manual process, since we may do several builds until the release happens. I had just forgotten.

**Comment by licaon-kter** [comment]
@saghul Right, so https://github.com/jitsi/jitsi-meet/releases/tag/android-20.4.2 published on Sep 24 is the base for the published Play version that was released one month later on Oct 21?

**Comment by licaon-kter** [comment]
Bump @saghul

**Comment by saghul** [comment]
Pushed. For reference, we create a release branch for every version, mobile-20.5 in this case: https://github.com/jitsi/jitsi-meet/tree/mobile-20.5 latest build is always tip of the release branch. All .X subsequent versions are fixups which we apply on top of the release branch.

**Comment by licaon-kter** [comment]
Latest tag https://github.com/jitsi/jitsi-meet/commits/android-20.6.0 last commit Dec 08

Latest branch https://github.com/jitsi/jitsi-meet/commits/mobile-20.6 last commit Jan 14

But latest app https://play.google.com/store/apps/details?id=org.jitsi.meet was published on February 3, 2021, which commit is this?

**Comment by saghul** [comment]
Pushed the missing tags.

**Comment by saghul** [comment]
The last release on the store was the same APK as the previous release plus a TWA for ChromeOS.

**Comment by licaon-kter** [comment]
I see updates in `mobile-21.2` but a Tag for `android-21.2.0` would be nicer to match the Play store release, can we have that @saghul ? :)

**Comment by saghul** [comment]
@tmoldovan8x8 Can you please push the tag?

**Comment by tmoldovan8x8** [comment]
Pushed the proper tags

**Comment by licaon-kter** [comment]
@tmoldovan8x8 thanks

**Comment by licaon-kter** [comment]
@saghul Latest Play from May 16 is based on https://github.com/jitsi/jitsi-meet/commits/mobile-22.2 ? I see no `android-22.2` tag in the public repo.

**Comment by saghul** [comment]
We haven't finished the rollout.

**Comment by licaon-kter** [comment]
So I can build for F-Droid or not?

**Comment by saghul** [comment]
Please don't.

**Comment by licaon-kter** [comment]
@saghul Do ping me when it's ready :+1:

**Comment by licaon-kter** [comment]
Of note, maybe it will be fixed by the time you ping back

It fails to build for me from 44319b377d465a986f90c9a1e7d9fab5cc37b35d
```
> Task :sdk:extractReleaseAnnotations FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:extractReleaseAnnotations'.
> Could not resolve all files for configuration ':sdk:lintClassPath'.
   > Could not download junit-platform-launcher-1.7.0.jar (org.junit.platform:junit-platform-launcher:1.7.0)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-launcher/1.7.0/junit-platform-launcher-1.7.0.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-launcher/1.7.0/junit-platform-launcher-1.7.0.jar'.
            > Read timed out
   > Could not download junit-platform-engine-1.7.0.jar (org.junit.platform:junit-platform-engine:1.7.0)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-engine/1.7.0/junit-platform-engine-1.7.0.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-engine/1.7.0/junit-platform-engine-1.7.0.jar'.
            > Read timed out
```

I retried 2-3 times to exclude some network glitch

**Comment by saghul** [comment]
Oh, I was about to ping you indeed. Hum, I haven't seen that one before. Do you have a WIP PR on f-droid so I can take a look?

**Comment by saghul** [comment]
Excellent, thanks!

**Comment by licaon-kter** [comment]
Building in the VM after a fail just works, so really odd.

I've pushed https://gitlab.com/fdroid/fdroiddata/-/commit/80f6627656a1b92b53d09cf74c16ffbaab952419 and I'll retest on yet another VM in the meantime

**Comment by licaon-kter** [comment]
pls reopen

**Comment by licaon-kter** [comment]
@saghul any reason 24.0.1 is not tagged?

**Comment by saghul** [comment]
We had a bit of an oopsie with that one. I pushed it now. I would, however encourage you to wait until 24.2.0 is out later this week.

**Comment by licaon-kter** [comment]
Will wait if needed, feel free to ping me when ready

**Comment by licaon-kter** [comment]
will test locally this tag: https://github.com/jitsi/jitsi-meet/blob/android-24.0.1/android/gradle.properties#L29 so I'm ready when 24.0.2 or 24.2.0 or (whatever that will be named :smile:) is tagged

**Comment by ildar** [comment]
> We had a bit of an oopsie with that one. I pushed it now. I would, however encourage you to wait until 24.2.0 is out later this week.

Did "later this week" happen already?

**Comment by saghul** [comment]
Yep, 24.2.2 is out already.

**Comment by ildar** [comment]
found it, thanks.
