### ISSUE TITLE
How to enable the user get back to the app in android sdk?

### ISSUE THREAD

**Issue by gungorhafize** [jitsi/jitsi-meet#6429]
I've try to make ongoing call notification and the user tap this notification get back to the app as in orjinal app appearence.

![WhatsApp Image 2020-04-28 at 11 05 21](https://user-images.githubusercontent.com/33956266/80465043-58920480-8943-11ea-9fee-e4f65b71d490.jpeg)

As a result that some research, I found there are some classes for it on -> https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java

and https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java

and this https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingConferenceTracker.java

How to enable the user get back to the app with ongoing call notification and how to make it on this main activity class?

**Comment by saghul** [comment]
How are you integrating with the SDK? Using JitsiMeetView? JitsiMeetActivity? This should work out of the box, as long aas you have an `ic_notification` icon present. Yeah, if you don't have one Android refuses to display the notification 🤷

**Comment by gungorhafize** [comment]
Notification box is appear but the notification message is this -> "Jitsi is running, touch for more information or stop the app " then click this notification uninstal or force stop options appear. I'm using this sdk sample https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/android/java/JitsiSDKTest/app/src/main/java/net/jitsi/sdktest/MainActivity.java here is my main activity class.

**Comment by saghul** [comment]
Do you see any errors in adb logcat?

**Comment by gungorhafize** [comment]
oh okay, i see your point, I've add own ic_notification icon then it becomes appear. I just read your commit message:
"Without it(ic_notification) the ongoing notification while in a call silently fails. Oh
well." ^^ thanks for your attention

**Comment by TBG-FR** [comment]
It would be useful to document this, in the README for example, I struggled a while with that issue, searching tons of tweaks and code before finding that github issue ahah

Thanks for the solution anyway !
