### ISSUE TITLE
coturn integration for stun/turn

### ISSUE THREAD

**Issue by localguru** [jitsi/jitsi-meet#6431]
Hi,

some questions to configure an own coturn server for stun/turn:

1. coturn recommends two public IPs. How to do that? Do I have to run multiple coturn stun/turn servers with different IPs and DNS names like coturn1.domain.tld, coturn2.domain.tld etc.?

2. Do I need to set SRV records for stun/turn in DNS? If yes, how would those records look like?

3. If I run coturn on port 443 is that tcp only or tcp and udp and is port 443 the only open incoming port for coturn on firewall or do ports 10000-20000/udp have to be open too?

```
server-name={{ inventory_hostname }}
cert=/etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem
pkey=/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
realm={{ inventory_hostname }}
fingerprint
listening-ip=0.0.0.0
external-ip={{ ipify_public_ip }}
listening-port=443
min-port=10000
max-port=20000
log-file=/var/log/turnserver.log
verbose
static-auth-secret={{ prosody_turncredentials_secret }}
```

Ciao!

**Comment by saghul** [comment]
>     1. coturn recommends two public IPs. How to do that? Do I have to run multiple coturn stun/turn servers with different IPs and DNS names like coturn1.domain.tld, coturn2.domain.tld etc.?

You don't need that if you only need TURN.



>     2\. Do I need to set SRV records for stun/turn in DNS? If yes, how would those records look like?

Not really, an A record will do.



>     3\. If I run coturn on port 443 is that tcp only or tcp and udp

Both.



>     3\. s port 443 the only open incoming port for coturn on firewall or do ports 10000-20000/udp have to be open too?

Only 10000, that's for the bridge.
