### ISSUE TITLE
Serveroption to display currently open rooms and connected users

### ISSUE THREAD

**Issue by Jasper-Ben** [jitsi/jitsi-meet#6435]
We are using our own private Jitsi Instance for Communication in our company to great success. Thanks for that! However, one feature we dearly miss is a way for users to see which rooms are already open on the instance as well as the names of the users in this room. This is a bit annoying, as this means a user cannot quickly hop into another room to discuss an issue with a particular colleague, but instead has to contact him first on other means and arrange a rendezvous room. As far as I am aware there currently is no solution to this problem available in jitsi.

Therefore I suggest the option to enable a listing of all open rooms as well as their participants beneath the "start a new meeting" portion of the landing page. This behavior could be configured in the servers config file.

**Comment by c-schmitz** [comment]
I agree this is a missing feature.

**Comment by damencho** [comment]
This is a deployment specific, what is needed is already there and can be used to add that customization to your deployment.
https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_census.lua
