### ISSUE TITLE
bosh Setting Cannot Be Overwritten in config.js

### ISSUE THREAD

**Issue by gchallen** [jitsi/jitsi-meet#6438]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
The `bosh` setting in `config.js` cannot be overwritten on the client through `configOverwrite`.

## Current behavior
---
Jitsi will always use the `bosh` setting specified in the server-side `config.js`.

## Expected Behavior
---
Jitsi uses the `bosh` setting specified in the `configOverwrite` option passed to `JitsiMeetExternalAPI`.

## Possible Solution
---
Either fix this or improve the documentation. It seems like the connection is set up before the room is created, so this may be a mess to fix.

## Steps to reproduce
---
Pass a different `bosh` value in the `configOverwrite` value passed to `JitsiMeetExternalAPI`. It will not be used.

In my case this was causing JWT authentication to fail until I set it on the server. However, I'd like to avoid server-side overwrites since I'm using the Docker setup and that requires patching each time a new set of containers is released.

**Comment by saghul** [comment]
I don't think it's a good idea to override bosh. It would mean signalling traffic is potentially sent to another server. You should use a different config.js for that domain IMHO.

**Comment by gchallen** [comment]
Again, overwriting bosh may not be smart, but then please adjust the documentation so that it's clear that it can't be done.

And, again, not allowing this setting to be overwritten makes it much harder to customize your Jitsi configuration when using the Docker containers. Essentially each time you update your Docker images you have to do the following:

* Remove the configuration directory
* Restart the Jitsi docker images so that they regenerate their configuration from the .env file
* Patch the resulting configuration to fix any changes
* Restart the Jitsi docker images again

This is both fiddly and leads to unnecessary downtime. (FYI: having the images regenerate their configuration from scratch is required because new configuration settings and defaults get added.)

**Comment by saghul** [comment]
> Again, overwriting bosh may not be smart, but then please adjust the documentation so that it's clear that it can't be done.

Not sure what is a goodd place to document this, TBH.



> And, again, not allowing this setting to be overwritten makes it much harder to customize your Jitsi configuration when using the Docker containers. Essentially each time you update your Docker images you have to do the following:
> 
>     * Remove the configuration directory
> 
>     * Restart the Jitsi docker images so that they regenerate their configuration from the .env file
> 
>     * Patch the resulting configuration to preserve any local changes—for example, modify the bosh setting to use a websocket connection
> 
>     * Restart the Jitsi docker images again
> 
> 
> This is both fiddly and leads to unnecessary downtime. (FYI: having the images regenerate their configuration from scratch is required because new configuration settings and defaults get added.)

I know. We are working to make this easier, but things take time. As for WebSocket support, there is an open PR for it, once ready it will be one env var change away.

**Comment by jeremythastings** [comment]
I precisely need this functionality in a deployed web app utilizing the Jitsi IFrame API. I intentionally need to overwrite the bosh settings so that requests are forwarded to the web app, and THEN the web app forwards the request to a cloud based Jitsi server.

**Comment by damencho** [comment]
Being able to overwrite that is a security problem. You can always add it to the whitelist on your deployment and use it that way, but we do not recommend it.

**Comment by jeremythastings** [comment]
Apologies for the ignorance but can you elaborate further on why this would be a vulnerability? I’m trying to rewrite it to another domain I control. Then, using a proxy on another server, would forward requests to JITSI

**Comment by jeremythastings** [comment]
Also, how might I “whitelist” this if I wanted to perform this? Thanks!

**Comment by damencho** [comment]
Someone can send you a link to that meeting with URL where signaling will go to a malicious server without you knowing. 

You can whitelist it here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/configWhitelist.js

**Comment by jeremythastings** [comment]
I'm having trouble finding the configWhitelist.js file on an existing Jitsi Server. Will I need to rebuilt from scratch in order to modify this file?

**Comment by damencho** [comment]
You need to checkout source from github, modify the source, rebuild and deploy those changes.

**Comment by jeremythastings** [comment]
Thanks for the assistance!
