### ISSUE TITLE
Sample iOS Swift-PIP app is crashing

### ISSUE THREAD

**Issue by umairgillani94** [jitsi/jitsi-meet#6439]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
The sample app is crashing on iOS 13 and Xcode 11, whereas it's working fine for iOS 12 and Xcode 11
---

## Current behavior
The sample app is crashing when I build on iOS 13 using Xcode 11, whereas it's working fine for iOS 12
---

## Expected Behavior
It should work on iOS 13 as well
---

## Possible Solution
---

## Steps to reproduce
Just run the sample iOS swift PIP app on iOS 13 
---

# Environment details
Xcode 11.3
iOS 13
Jitsi 2.5.2
---

**Comment by saghul** [comment]
Can you post the crash?

**Comment by umairgillani94** [comment]
> Can you post the crash?

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/31413820/80508536-9cabf600-8991-11ea-95b3-771d1e52423e.png">

this is what i see when app get started

**Comment by nedimf** [comment]
Can you post code you are using?

**Comment by jefaokpta** [comment]
the same happens with me.
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/10830832/80539405-d6730180-897d-11ea-9ac3-023847de229c.png">

Xcode 11.4
Project NoPodsSample
iOS 13.3

I'm compiling the sdk 2.7.0
jitsi-meet-ios-sdk-2.7.0# lipo -info ios/sdk/JitsiMeet.framework/JitsiMeet
Architectures in the fat file: ios/sdk/JitsiMeet.framework/JitsiMeet are: x86_64 arm64

On simulators runs ok.
sorry my pour English

**Comment by saghul** [comment]
Did you enable signing of embedded frameworks?

**Comment by umairgillani94** [comment]
> Did you enable signing of embedded frameworks?

<img width="662" alt="image" src="https://user-images.githubusercontent.com/31413820/80564215-aae82980-8a06-11ea-9f2d-c19a3b04207c.png">

i am using pods and they are embedded

**Comment by umairgillani94** [comment]
> Can you post code you are using?

i am using this sample code 
https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/ios/swift-pip/JitsiSDKTest

**Comment by umairgillani94** [comment]
> the same happens with me.
> <img alt="image" width="1670" src="https://user-images.githubusercontent.com/10830832/80539405-d6730180-897d-11ea-9ac3-023847de229c.png">
> 
> Xcode 11.4
> Project NoPodsSample
> iOS 13.3
> 
> I'm compiling the sdk 2.7.0
> jitsi-meet-ios-sdk-2.7.0# lipo -info ios/sdk/JitsiMeet.framework/JitsiMeet
> Architectures in the fat file: ios/sdk/JitsiMeet.framework/JitsiMeet are: x86_64 arm64
> 
> On simulators runs ok.
> sorry my pour English

this the the same error i am facing @saghul can you please help

**Comment by jefaokpta** [comment]
> Did you enable signing of embedded frameworks?

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/10830832/80610327-99574f80-8a0f-11ea-8fc8-349256b324a8.png">
yes, they are signing enable.

please take a look, I inverted the order of the frameworks and the library not loaded changed to WebRTC.

<img width="1672" alt="Screen Shot 2020-04-29 at 11 47 16" src="https://user-images.githubusercontent.com/10830832/80610753-197db500-8a10-11ea-9fad-75aa6c9089ab.png">

I'm newbie in iOS development and don't know if the order of the frameworks matters.

**Comment by nedimf** [comment]
Guys found a fix for this, at least I think. For me problem was with every Cocoa Pods, running it on real device resulted in crash.
**Solution**
Update your iOS to latest version and you have to update your Xcode to latest version.
I think there is know issue and they have introduced fix for it.
Try it out and i hope it works for you all.

**Comment by jefaokpta** [comment]
> Guys found a fix for this, at least I think. For me problem was with every Cocoa Pods, running it on real device resulted in crash.
> **Solution**
> Update your iOS to latest version and you have to update your Xcode to latest version.
> I think there is know issue and they have introduced fix for it.
> Try it out and i hope it works for you all.
> 
> @jefaokpta @saghul @umairgillani94

Awesome ! Thats works for me! Xcode was already on latest version, I just needed update my Iphone. Thanks so much!

**Comment by nedimf** [comment]
No problem man, glad I could help 😄

**Comment by saghul** [comment]
I updated all SDK sample apps this morning and all are working fine AFAICT.
