### ISSUE TITLE
Microphone Activity Indicators on mobile SDK (See who is speaking)

### ISSUE THREAD

**Issue by fritzfr** [jitsi/jitsi-meet#6440]
**Is your feature request related to a problem you are facing?**
I am trying to implement the mobile SDK into my app and noticed, that it doesn't seem to feature an activity indicator like the webview has (the dots next to the users pictures). Does it have to be enabled or is it simply not there in the mobile sdk?

**Comment by fritzfr** [comment]
@saghul Any ideas?

**Comment by BigSaimo** [comment]
> I tried around with listening to 'track.audioLevelsChanged' events on the audioTracks, but they don't seem to be triggered at all.
> 
> -- Update:
> Ahh, I see (/jitsi-meet/react/features/base/config/reducer.js):
> 
> ```
>     // FIXME The support for audio levels in lib-jitsi-meet polls the statistics
>     // of WebRTC at a short interval multiple times a second. Unfortunately,
>     // React Native is slow to fetch these statistics from the native WebRTC
>     // API, through the React Native bridge and eventually to JavaScript.
>     // Because the audio levels are of no interest to the mobile app, it is
>     // fastest to merely disable them.
>     disableAudioLevels: true,
> ```
> 
> Maybe there is a way around this.

hello, how does you resolve this problem? my app also need listen who is speaking.

**Comment by samelm** [comment]
@BigSaimo hello, have you tried using this lib https://github.com/punarinta/react-native-sound-level?
