### ISSUE TITLE
Kamera/Webcam 

### ISSUE THREAD

**Issue by doga12** [jitsi/jitsi-meet#6441]
my camera does not work

**Comment by nedimf** [comment]
On Android or iOS you have to add permissions

**Comment by toby63** [comment]
See #5425

**Comment by luixxiul** [comment]
Do you experience the issue yet?

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
