### ISSUE TITLE
Will audio mixing be implemented? It is needed here for a teaching lesson

### ISSUE THREAD

**Issue by Wikinaut** [jitsi/jitsi-meet#6444]
From https://community.jitsi.org/t/jitsi-users-enabling-audio-mixing-in-jitsi-videobridge/12565 I learn that 
> In the context of the bridge -- sure. In the context of jitsi-meet -- no. Jitsi-meet doesn't support mixed audio right now.

It this the latest status, or can I configure Jitsi on my server to mix all active (unmuted) audio signals?

**Comment by damencho** [comment]
Nope, mixing audio streams is not un option, the bridge is just a smart network router which forwards packets, decoding, encoding and mixing is not supported.

Please use the community forum for questions before opening new issues.
