### ISSUE TITLE
Error recording in dropbox 

### ISSUE THREAD

**Issue by ataveira** [jitsi/jitsi-meet#6447]
Is any additional configuration necessary?

**Comment by MagicFab** [comment]
What error message or what problem did you have ?

**Comment by ataveira** [comment]
the application reports that it is not available for recording.

Em ter, 5 de mai de 2020 19:08, Fabian Rodriguez <notifications@github.com>
escreveu:

**Comment by MagicFab** [comment]
When you click on "Start Recording" during a meeting on meet.jit.si, there a **Sign In** button, once you have accepted access to Dropbox and try to record I believe you see this exact message : 

![Screenshot from 2020-05-06 11-41-42](https://user-images.githubusercontent.com/317514/81197818-bdc2a700-8f8e-11ea-8f4e-19ef26095174.png)

This seems to mean Jitsi Meet servers have a limit on # of streams that can send recordings to Dropbox and that limit has been reached. Perhaps try using another server that has this feature or you may want to setup your own.

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
