### ISSUE TITLE
Running jitsi-meet on ARM devices Amazon, Ampere, Odroid, Marvell ThunderX, Raspberry Pi 4, Tinkerboard running Raspbian, Armbian, Debian or Ubuntu

### ISSUE THREAD

**Issue by crouchingtigerhiddenadam** [jitsi/jitsi-meet#6449]
I would like an ARM version of jitsi-meet particularly for mainstream ARM servers. It would also be useful to run a memory limited version of jitsi-meet on devices such as a Raspberry Pi 4 for home and educational use.

I have a set of instructions that work, that I originally used to help derive docker images with help from @dubit0. Other container technologies like nspawn64 (suggested by @Rooby69) worked really well.

I added a few lines to the prosody configuration because only version 10 and above was available. I also had to recompile jniwrapper-native-1.0-SNAPSHOT. For lower memory SBCs I needed to tweak the `Xmx` flag. I found jitsi-meet would work with varying levels of performance on every device I tested.

- Odroid C2
- NanoPi 2
- Raspberry Pi 4
- Tinkerboard S
- Marvell / ThunderX

The biggest limiting factor during my testing was the network speed, even for SBCs. On a slow broadband connection the phone app could lag anywhere up to 14 seconds. With a fast connection this lag disappeared.

As the jni signatures are `linux-aarch64` and `linux-arm`, would it cause too much scope creep to add them to the `jitsi-sctp` build? Possibly an environment variable for the `Xmx` flag in `jicofo.sh` as exists in jitsi-videobridge2.

### Important Notes for raspbian-nspawn-64

If you are using `raspbian-nspawn-64` then open the 64 bit shell using:
```
sudo ds64-shell
```
Then follow the **Debian 10 (arm64)** instructions and ignore the _Raspbian (armhf)_ instructions.

#### For Raspbian Only (armhf)
```
sudo apt install openjdk-8-jdk
```

#### For Armbian Buster and Debian 10 (armhf)
```
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre_8u242-b08-1~deb9u1_armhf.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre-headless_8u242-b08-1~deb9u1_armhf.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jdk_8u242-b08-1~deb9u1_armhf.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jdk-headless_8u242-b08-1~deb9u1_armhf.deb

sudo apt install \
 ./openjdk-8-jre_8u242-b08-1~deb9u1_armhf.deb \
 ./openjdk-8-jre-headless_8u242-b08-1~deb9u1_armhf.deb \
 ./openjdk-8-jdk_8u242-b08-1~deb9u1_armhf.deb \
 ./openjdk-8-jdk-headless_8u242-b08-1~deb9u1_armhf.deb
```

#### For Armbian Buster and Debian 10 (arm64)
```
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre_8u242-b08-1~deb9u1_arm64.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre-headless_8u242-b08-1~deb9u1_arm64.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jdk_8u242-b08-1~deb9u1_arm64.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jdk-headless_8u242-b08-1~deb9u1_arm64.deb

sudo apt install \
 ./openjdk-8-jre_8u242-b08-1~deb9u1_arm64.deb \
 ./openjdk-8-jre-headless_8u242-b08-1~deb9u1_arm64.deb \
 ./openjdk-8-jdk_8u242-b08-1~deb9u1_arm64.deb \
 ./openjdk-8-jdk-headless_8u242-b08-1~deb9u1_arm64.deb
```

### Configure OpenJDK 8
Set the java version to use:
```
sudo update-alternatives --config java
```
Select `/usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java` from the menu.  

### Other Dependencies
```
sudo apt update
sudo apt install automake autoconf build-essential libtool git maven m4
```

### Install Jitsi Meet
Using this method you will have to keep Jitsi Meet up-to-date yourself.
```
wget https://download.jitsi.org/stable/jicofo_1.0-544-1_all.deb
wget https://download.jitsi.org/stable/jitsi-meet-prosody_1.0.3992-1_all.deb
wget https://download.jitsi.org/stable/jitsi-meet-web_1.0.3992-1_all.deb
wget https://download.jitsi.org/stable/jitsi-meet-web-config_1.0.3992-1_all.deb
wget https://download.jitsi.org/stable/jitsi-videobridge2_2.1-169-ga28eb88e-1_all.deb

sudo apt -y install \
  ./jicofo_1.0-544-1_all.deb \
  ./jitsi-meet-prosody_1.0.3992-1_all.deb \
  ./jitsi-meet-web_1.0.3992-1_all.deb \
  ./jitsi-meet-web-config_1.0.3992-1_all.deb \
  ./jitsi-videobridge2_2.1-169-ga28eb88e-1_all.deb
```

### Stop Services
```
sudo systemctl stop prosody jitsi-videobridge2 jicofo
```

### Modify Prosody Configuration for Versions 10 and Above
These steps will assume you are setting up jitsi-meet with the fully qualified host name `jitsi.example.com`. Please substitute this with own host name.  
  
Edit the prosody configuration:
```
sudo nano /etc/prosody/conf.d/jitsi.example.com.cfg.lua
```
Add the two lines starting `https_certificate` and `https_key`:
```
turncredentials = {
  { type = "stun", host = "jitsi.example.com", port = "443" },
  { type = "turn", host = "jitsi.example.com", port = "443", transport = "udp" },
  { type = "turns", host = "jitsi.example.com", port = "443", transport = "tcp" }
};

-- Add these two lines
https_certificate = "/etc/prosody/certs/jitsi.example.com.crt";
https_key =  "/etc/prosody/certs/jitsi.example.com.key";

cross_domain_bosh = false;
consider_bosh_secure = true;
```
Save by pressing `ctrl+x`, `ctrl+y` and `enter` when prompted.   

#### For Raspbian, Armbian Buster and Debian 10 (armhf)
```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-armhf
```
#### For Armbian Buster and Debian 10 (arm64)
```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
```

### Recompile jniwrapper-native-1.0-SNAPSHOT
```
git clone https://github.com/sctplab/usrsctp.git
git clone https://github.com/jitsi/jitsi-sctp
mv ./usrsctp ./jitsi-sctp/usrsctp/
cd ./jitsi-sctp
mvn package -DbuildSctp -DbuildNativeWrapper -DdeployNewJnilib -DskipTests
```
#### For Raspbian, Armbian Buster and Debian 10 (armhf)
```
cp ./jniwrapper/native/target/libjnisctp-linux-arm.so \
 ./jniwrapper/native/src/main/resources/lib/linux/libjnisctp.so
```
#### For Armbian Buster and Debian 10 (arm64)
```
cp ./jniwrapper/native/target/libjnisctp-linux-aarch64.so \
 ./jniwrapper/native/src/main/resources/lib/linux/libjnisctp.so
```
### Re-package and Copy jniwrapper-native-1.0-SNAPSHOT.jar into Jitsi VideoBridge2
When running `mvn package` ensure all unit tests are successful.
```
mvn package
sudo cp ./jniwrapper/native/target/jniwrapper-native-1.0-SNAPSHOT.jar \
 /usr/share/jitsi-videobridge/lib/jniwrapper-native-1.0-SNAPSHOT.jar
```
### Change the memory limits on Jitsi VideoBridge2 for Raspbian, Armbian Buster and Debian 10 (armhf only)
Open `jvb.sh`:
```
sudo nano /usr/share/jitsi-videobridge/jvb.sh
```
and change:
```
if [ -z "$VIDEOBRIDGE_MAX_MEMORY" ]; then VIDEOBRIDGE_MAX_MEMORY=3072m; fi
```
to:
```
if [ -z "$VIDEOBRIDGE_MAX_MEMORY" ]; then VIDEOBRIDGE_MAX_MEMORY=1024m; fi
```
Save by pressing `ctrl+x`, `ctrl+y` and `enter` when prompted.   
### Change the Memory Limits on Jicofo for Raspbian, Armbian Buster and Debian 10 (armhf only)
Open `jicofo.sh`:
```
sudo nano /usr/share/jicofo/jicofo.sh
```
and change:
```
exec java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp $LOGGING_CONFIG_PARAM $JAVA_SYS_PROPS -cp $cp $mainClass $@
```
to:
```
exec java -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp $LOGGING_CONFIG_PARAM $JAVA_SYS_PROPS -cp $cp $mainClass $@
```
Save by pressing `ctrl+x`, `ctrl+y` and `enter` when prompted.   

### Clear the Log Files and Restart Services
Clear the log files:
```
sudo rm /etc/prosody/prosody.log
sudo rm /etc/jitsi/jicofo.log
sudo rm /etc/jitsi/jvb.log
```

Restart the services:
```
sudo systemctl start prosody jitsi-videobridge2 jicofo
```

### Check the Service Statuses
Check the status of prosody, jitsi-videobridge2 and jicofo:
```
sudo systemctl status prosody
sudo systemctl status jitsi-videobridge2
sudo systemctl status jicofo
```
Using `ctrl+c` where needed to exit the status screen.

### Check the Log Files
If the services are running, check the log files for errors:
```
sudo cat /var/log/prosody/prosody.log
sudo cat /var/log/jitsi/jicofo.log
sudo cat /var/log/jitsi/jvb.log
```
## Additional: Installing Behind a NAT Router
You will need to forward ports 80/TCP, 443/TCP and 10000/UDP. Creating a Let's Encrypt certificate and setting up Jitsi VideoBridge2 is covered in the [Quick Guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#generate-a-lets-encrypt-certificate-optional-recommended).

## Known Issue: Let's Encrypt Workaround
When running the Let`s Encrypt certificate script on both platforms (ARM and X86/X64) if you get:
```
Unable to find deploy-hook command /etc/letsencrypt/renewal-hooks/deploy/0000-coturn-certbot-deploy.sh in the PATH.
```

Create directory and empty file:
```
sudo mkdir /etc/letsencrypt/renewal-hooks/deploy
sudo touch /etc/letsencrypt/renewal-hooks/deploy/0000-coturn-certbot-deploy.sh
sudo chmod +x /etc/letsencrypt/renewal-hooks/deploy/0000-coturn-certbot-deploy.sh
```

Then re-run:
```
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```

**Comment by crouchingtigerhiddenadam** [comment]
_Moving to the community._

**Comment by hbasora** [comment]
I can't change hostname, it's just asking for secret when installing prosody, any help?

**Comment by hbasora** [comment]
sudo cat /var/log/prosody/prosody.log
Apr 29 22:06:58 mod_component	info	Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>focus.localhost does not match any configured external components</text></stream:error>


sudo cat /var/log/jitsi/jicofo.log

<text>This server does not serve auth.localhost</text>

sudo cat /var/log/jitsi/jvb.log
2020-04-29 22:06:22.788 INFORMACIÓN: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.



localhost should be conferencias.mensuravirtual.com

**Comment by crouchingtigerhiddenadam** [comment]
@hbasora have you tried https://community.jitsi.org and posting your question there? If you post here I probably wont see it, I'm spending more time in the community pages. Support questions are better placed there.

**Comment by krithin** [comment]
For what it's worth I adapted these instructions for Ubuntu Server 20.04 here: https://gist.github.com/krithin/e50a6001c8435e46cb85f5c6c78e2d66

**Comment by hbasora** [comment]
> For what it's worth I adapted these instructions for Ubuntu Server 20.04 here: https://gist.github.com/krithin/e50a6001c8435e46cb85f5c6c78e2d66

Thank you, that worked, I was using Debian Buster...., now I'll try to implement Jwt hehe

**Comment by tgeimer** [comment]
> For what it's worth I adapted these instructions for Ubuntu Server 20.04 here: https://gist.github.com/krithin/e50a6001c8435e46cb85f5c6c78e2d66

Hi, following krithin's instructions I was able to successfully install jitsi-meet on my pi 4 (4GB RAM). Thank you for your efforts, guys and keep up the good work! :-)

**Comment by mrjohnson22** [comment]
Did the videobridge recently change how it loads the SCTP library? Ever since `jitsi-videobridge2 2.1-273-g072dd44b-1`, it complains about a mismatched architecture even after I follow all of the provided steps, which worked great for me before:

```
java.lang.UnsatisfiedLinkError: /tmp/nativeutils71750745336281/libjnisctp.so: /tmp/nativeutils71750745336281/libjnisctp.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
```

Stranger still, I tried removing `/usr/share/jitsi-videobridge/lib/jniwrapper-native-1.0-SNAPSHOT.jar` to see what would happen, and the same error occurred, instead of something like a "file not found" error.

Thankfully, [using websockets](https://github.com/jitsi/jitsi-videobridge/issues/1177#issuecomment-610976514) instead of SCTP is a viable alternative. But I'd still like to figure out what's going on.

Also, has the post on [community.jitsi.org](https://community.jitsi.org/t/running-jitsi-meet-on-arm-devices-amazon-ampere-odroid-marvell-thunderx-raspberry-pi-4-tinkerboard-running-raspbian-armbian-debian-or-ubuntu/47842) been moved/removed? Trying to view it gives me an error of "Oops! That page doesn’t exist or is private."

Thanks for this great guide!

**Comment by mrjohnson22** [comment]
Ah, the difference is that the latest version of the Debian 10 `jitsi-videobridge2` package installs `jniwrapper-native-1.0-2-ga3ad2e6.jar` instead of `jniwrapper-native-1.0-SNAPSHOT.jar`. When copying the generated JAR file in Step 2.5 / 3.5, giving the copied file a name of `jniwrapper-native-1.0-2-ga3ad2e6.jar` will work.

**Comment by cristianapas** [comment]
Hi

Based on this guide, I did an installation on a Renegade SBC using armbian 20.08 and I commented that I use the official adoptopenjdk and jitsi repositories to simplify the installation. Regarding the jniwrapper modify the step in this way to replace the current version:
`sudo cp ./jniwrapper/native/target/jniwrapper-native-1.0-SNAPSHOT.jar \`
 `$(ls /usr/share/jitsi-videobridge/lib/jniwrapper-native-*)`

**Comment by cristianapas** [comment]
Hello, here is a guide that I created, based mostly on the information in this post, using repositories and apt to install the packages: 
https://github.com/cristianapas/jitsi-on-arm64

**Comment by licaon-kter** [comment]
Did you have issues with OpenJDK11 and that's the reason to go back to 8? I've always used 11 and didn't see any issues on Debian Buster arm64.

**Comment by jpr5** [comment]
FWIW, here's [instructions for building/running JITSI on AWS ARM64 instances](https://gist.github.com/jpr5/b2554277d76c7ede8d913f5cd0c211e3) (Graviton2).  

Simpler than all the others referenced here.  

Cheers.

**Comment by licaon-kter** [comment]
@jpr5 running on Pi RAM is an issue for building jitsi-meet (the front) as node ooms on 1Gb. Running, memory is fine, but CPU will get loaded a lot more.

**Comment by Staynex** [comment]
Generally Docker Images for ARM64 would be nice!
