### ISSUE TITLE
Restart of the server : keep the state of the camera and micro on client

### ISSUE THREAD

**Issue by dominiquefournier** [jitsi/jitsi-meet#6452]
Hello 
I am connected every time to our server on our but I don't send the video neither the micro. If the Nginx on the server restart, the client reconnects correctely, but the previous state of the camera and the microphone are reset. So the camera and the micro are sent again.
Could you keep the user state in cache and re-use it after the re-connection ?

It can be a privacy concern for the end user.

Thanks !

**Comment by saghul** [comment]
Is this on web, mobile or both?

**Comment by dominiquefournier** [comment]
At least on Web clients, I don't know for mobile : I don't use it and I don't have a recent mobile to test, sorry.

**Comment by saghul** [comment]
No worries, thanks for the report.
