### ISSUE TITLE
SImple way to enable certain people to be moderators without lua/token based auth?

### ISSUE THREAD

**Issue by ktechmidas** [jitsi/jitsi-meet#6458]
Ideally I'm after a simple way to make people mods, without needing to use the jitsi-meet-tokens and authentication - mostly because jitsi-meet-tokens seems to be broken without forcing prosody to be updated and authentication has already been done externally when users receive the link. Also we'd still need to use something [like this](https://github.com/nvonahsen/jitsi-token-moderation-plugin/) I suspect. Ideally it'd be good to marry the two systems, the one that does the auth and Jitsi, but that requires way more time/money than my client has....

So here's what I'm thinking, we have nginx in front so we can add ?ismod=1 to the url for anyone coming from the mod side... yes it's not really secure and can be broken by the user using ismod=1 but it will do the job for us.

So how can I get jitsi to just read that parameter? Is there a way to ship a user into Jitsi from nginx with mod perms without too many changes to jitsi?

**Comment by ktechmidas** [comment]
I was thinking I could just disallow anyone into the room until the mod has come in, but the default behavior gives mod control to another user when the mod leaves right?

**Comment by fritzfr** [comment]
> mostly because jitsi-meet-tokens seems to be broken without forcing prosody to be updated

That is accurate, it is possible to get it to work though. I followed these instructions and while it's complicated, it does work: https://github.com/jitsi/lib-jitsi-meet/issues/1082#issuecomment-616948457

> So how can I get jitsi to just read that parameter? Is there a way to ship a user into Jitsi from nginx with mod perms without too many changes to jitsi?

I don't think there is a way without a lua plugin. But luckily there is one which works in combination with the above mentioned: https://github.com/nvonahsen/jitsi-token-moderation-plugin

**Comment by ktechmidas** [comment]
Hm, so I can have say meet.example.com/login go to a custom PHP script, set the JWT then forward them where they were going?

**Comment by fritzfr** [comment]
@ktechmidas You could, but you would still need to implement said plugins. In fact, you **need** to create tokens somewhere and then forward to a jitsi url with the token appended.

**Comment by josuah** [comment]
You can use the "secure domain" setup documented here: https://github.com/jitsi/jicofo/#secure-domain

This would give a password to the presenter (added with prosodyctl, let's say "the teacher") and have all other users have the guest status: (let's say "students waiting in the corridor that the teacher opens the class door).

As soon as the moderator (authenticated) enters the room, the guests can join.  It takes significantly less time than token setup which is still somehow in development (working well, but packaging workarounds needed and polishing phase).

**Comment by luixxiul** [comment]
Closing as this is a question. Questions should be forwarded to community.jitsi.org/
