### ISSUE TITLE
Android app crashing when using latest org.jitsi.react:jitsi-meet-sdk:2.8.1

### ISSUE THREAD

**Issue by atulgoswami21** [jitsi/jitsi-meet#6460]
I was trying to build android app 
using org.jitsi.react:jitsi-meet-sdk:2.8.1 as implementation.

but during debugging it is crashing but it was working fine with org.jitsi.react:jitsi-meet-sdk:2.5.1

`E/ReactNativeJS: Error: Cannot create URL for blob!
2020-04-29 18:20:21.196 19571-19957/com.meettly.live E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
2020-04-29 18:20:21.509 19571-19958/org.meet.jitsi E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: org.meet.jitsi, PID: 19571
    com.facebook.react.common.JavascriptException: Error: Cannot create URL for blob!, js engine: hermes, stack:`

*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---
Application is crashing.

## Expected Behavior
---
Application should run.

## Possible Solution
---

## Steps to reproduce
---
try debugging this code with latest sdk
https://github.com/jitsi/jitsi-meet-sdk-samples

# Environment details
---
Android SDK on Windows 64 bit

**Comment by saghul** [comment]
Do you have a longer backtrace?

**Comment by saghul** [comment]
Found it. Update coming up.

**Comment by saghul** [comment]
2.8.2 is out and should fix the problem.
