### ISSUE TITLE
About camera.

### ISSUE THREAD

**Issue by Elizabethcaripan** [jitsi/jitsi-meet#6469]
Hi. I have some problems with the camera. it doesn't work with this application but with others, this works well. I would like to know how to allow the camera function.
Please. Can you help me?

**Comment by toby63** [comment]
See #5425

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
