### ISSUE TITLE
can't open the camera

### ISSUE THREAD

**Issue by NicolasBorquez** [jitsi/jitsi-meet#6472]
no me reconoce la camara del notebook
![jitsi](https://user-images.githubusercontent.com/64479791/80640868-08de3680-8a32-11ea-951e-3fd29cb05a85.jpg)
![jitsi2](https://user-images.githubusercontent.com/64479791/80641073-5195ef80-8a32-11ea-9d1b-49b60158159e.jpg)

**Comment by toby63** [comment]
See #5425

**Comment by l3d00m** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*
