### ISSUE TITLE
Camera is still active on Android after terminated jitsi session

### ISSUE THREAD

**Issue by trustratch** [jitsi/jitsi-meet#6482]
## Description
I found out that jitsi is still using the device camera even after i ended the call. 
This happens randomly across different devices and i have no idea how to reproduce this issue.

## Current behavior
1. Create a Jitsi call
2. Enable camera
3. End the call
4. Camera is still in use when i tried to open the other camera app
## Expected Behavior
1. Create a Jitsi call
2. Enable camera
3. End the call
4. Camera should also be inactive

## Steps to reproduce
This case happens randomly
# Environment details
jitsi-meet-sdk:2.6.1 on Android
Android target SDK 29

**Comment by saghul** [comment]
I don't think this iss possible. Please provide adb logs when this happens and make sure to be running the latest SDK version: 2.8.2 right now (just in case, though I've never seen this with any SDK verion).

**Comment by Echolon** [comment]
@trustratch can you provide more details as requested?
