### ISSUE TITLE
"My role changed, new role: none" on stable and unstable

### ISSUE THREAD

**Issue by triangle-stream** [jitsi/jitsi-meet#6487]
## Description
I ran into this issue while trying to lock a room via the jitsi API embed. 
I have 3 test servers with Jitsi-meet (default install) for test purposes and a different Jitsi-meet release on each one (also two with stable and one with unstable).
It seems that this issue is also present for other users but not on the meet.jit.si public website.

This bug is present on a fresh-new Jitsi-meet install, without editing the config files.
Certificates are ok.

Also tried to use different versions of Prosodi (0.10.0 and 0.11.5) and Lua (5.1 and 5.2) on different browsers (Chrome and Firefox).

## Current behavior
In Jitsi everyone that create a room and join is a moderator. Within the console, you can see that the user role switches two times: after the focus, we have "new role: moderator", then "new role: none", then "new role: moderator". This is the same on any other jitsi-meet installation we have.

## Expected Behavior
The role might change only for the first time, setting the user as a moderator.

## Possible Solution
---

## Steps to reproduce
It's quite simple: install a new Jitsi-meet installation with `apt install jitsi-meet` (stable or unstable) and you will experience this issue.

There is a community thread in which we were reporting this bug but unfortunately no one seems to be able to answer. Just read [here](https://community.jitsi.org/t/lock-failed-on-jitsimeetexternalapi/32060/24)

**Comment by damencho** [comment]
I just tried stable with prosody 0.11 we get the initial presence:
```
<status code=\"110\"/>
<item affiliation=\"none\" jid=\"osas-8qgitrt24gx@meet....../XJ-7f0D2\" role=\"participant\"/
```
And then the role changes:
```
<status code=\"110\"/>
<item affiliation=\"owner\" jid=\"osas-8qgitrt24gx@meet....../XJ-7f0D2\" role=\"moderator\">
```

Similar for default prosody 0.10.0-1build1 on 18.04. I don't think this is abnormal.

**Comment by triangle-stream** [comment]
Than you for the answer.

I've just tried on a new server with same OS, intalled jitsi from scratch with apt, made no change (certificate by letsencrypt on nginx previously installed with apt and no config edit), created a room and I have the same logs in console (Chrome and Firefox): 

```
2020-05-01T09:47:27.556Z [modules/xmpp/ChatRoom.js] <onPresence>:  entered dasd@conference.X.Y.Z/focus 
Object { affiliation: "owner", role: "moderator", jid: "focus@auth.X.Y.Z/focus1265457053420838", isFocus: true, isHiddenDomain: false }
Logger.js:154:22
2020-05-01T09:47:27.570Z [conference.js] <_setupListeners/<>:  My role changed, new role: none Logger.js:154:22
2020-05-01T09:47:29.201Z [conference.js] <_setupListeners/<>:  My role changed, new role: moderator Logger.js:154:22
```
Have you done any modification on any config file? Have you tried after installing new jitsi-meet with apt install? 

This issue is also present for other users, so I think there's something that is not working well.

The role changes from moderator to none after confirming the webcam and audio access (moderator to none), than it changes after displaying video (from none to moderator).
​

**Comment by triangle-stream** [comment]
I'm now able to set a password via API with the latest release. Thank you.

**Comment by ngodanghuuha** [comment]
how to keep the role is moderator, I have same problem the role changes two times and auto set role to none!
