### ISSUE TITLE
External API: mobile download links are not properly binded

### ISSUE THREAD

**Issue by blalop** [jitsi/jitsi-meet#6489]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
When using the external API, mobile download links are not properly returned when defined. (MOBILE_DOWNLOAD_LINK_ANDROID, MOBILE_DOWNLOAD_LINK_IOS)

## Current behavior
Although mobile download links are defined for both Android and iOS, they are never returned in the generated link. Instead, the default firebase link is returned.

## Expected Behavior
Return the defined link for each platform.

## Possible Solution
Use the interfaceConfig directly inside react/features/deep-linking/components/DeepLinkingMobilePage.web.js:_generateDownloadURL. The problem is that inside _URLS object the links are always undefined.

## Steps to reproduce
Using the API, define download links and try to use them.

# Environment details
It happens with both localhost and meet.jit.si domains.

**Comment by saghul** [comment]
meet.jit.si does not have those defined, on purpose (check here: https://meet.jit.si/interface_config.js). The default is indeed the firebase dynamic link.

After https://github.com/jitsi/jitsi-meet/commit/5fdb7c176c47c1861adb4871c5d875e834ec0b5f it will prefer the specified linkss to dynami links.

Not sure how external API is related here.

**Comment by blalop** [comment]
Sorry, I didn't make myself clear.

I expected that defining the mobile download links when using the external API via interfaceConfigOverwrite would make jitsi to return my download links, both in meet.jit.si or a self-deployed instance.

**Comment by saghul** [comment]
AFAIS they are whitelisted, so that should work. Can you paste an snippet of code where you override them?

**Comment by blalop** [comment]
Sure:
```html


<div style="margin: 5rem" id="meet"></div>

<script src='https://meet.jit.si/external_api.js'></script>
<script>
    const domain = 'meet.jit.si';
    const options = {
        roomName: 'jisti-test-35203475209347592037139418237',
        width: 1600,
        height: 800,
        parentNode: document.querySelector('#meet'),
        interfaceConfigOverwrite: {
            DEFAULT_REMOTE_DISPLAY_NAME: 'User',
            DEFAULT_LOCAL_DISPLAY_NAME: 'me',
            MOBILE_DOWNLOAD_LINK_ANDROID: 'https://play.google.com/store/apps/details?id=com.idealista.android',
            MOBILE_DOWNLOAD_LINK_IOS: 'https://itunes.apple.com/us/app/idealista/id465958311'
        }
    };
    const api = new JitsiMeetExternalAPI(domain, options);
</script>
```
