### ISSUE TITLE
own video doesn't rotate when device rotates

### ISSUE THREAD

**Issue by DerDings** [jitsi/jitsi-meet#6491]
## Description
Video is not rotatable

## Current behavior
When using a 2-in-1 Laptop in tent mode my video is upside down. When in tablet mode in portait format, it is twisted by 90°

## Expected Behavior
User video always has the correct orientation, users are able to easily fix the orientation.

## Possible Solution
A button to rotate the video. 
This also serves users using an external webcam which can't be correctly positioned.
Should also be a solution / workaround for #6256 

Auto-detecting the device orientation may also be possible, but more error prone.

## Steps to reproduce

1. use a tablet or 2-in-1 device
2. enable auto-rotation
3. start a jitsi meeting
4. rotate the device

# Environment details
Dell XPS 15 2-in-1 (XPS 15 9575)
Windows 10 Home 1909
Firefox 76.0.1

**Comment by DerDings** [comment]
This problem doesn't occur in chromium on the same device, so this may be a browser issue.
However, an ability to manually change the video orientation would be a good workaround in this case, as well as in other environments where the cameras orientation cannot be auto-detected.

E. g. external webcams without orientation sensor.

**Comment by saghul** [comment]
Sorry, but I don't see this happening. It's such a corner case. This is a browser issue, please do report it to Firefox. External cameras can be adjusted externally.

**Comment by DerDings** [comment]
> 
> 
> Sorry, but I don't see this happening. It's such a corner case. This is a browser issue, please do report it to Firefox. External cameras can be adjusted externally.

It's a feature I know from various other video conferencing tools, so this probably not that much a corner case. But I agree that it is not a bug in jitsi-meet, so I filed a feature request #6708 instead.
