### ISSUE TITLE
Replace camera output with shared screen/window

### ISSUE THREAD

**Issue by RalphCorderoy** [jitsi/jitsi-meet#6496]
**Describe the solution you'd like**
Sharing my screen, or a window within it, is separate from the video feed uploaded from my camera. It would be nice if the shared screen/window could replace the video feed and appear as 'me' in everyone else's eyes. It may be I think it's more interesting than me, or I wish to cloak my camera, or I have no camera-just audio.

If multiple users did this then we could be doing a task at the same time, say painting, and the grid view of everyone would show all of them in parallel. Shelfies get old quickly, there's lots more interesting stuff which could be shared.

Given my lack of camera, I might just share an image-viewer window where I change the picture from time to time; it's very open ended how it could be used. Especially in a group setting.

**Comment by Echolon** [comment]
@RalphCorderoy What system/browser are you using?

**Comment by RalphCorderoy** [comment]
I'm using the Electron jitsi-meet on Arch Linux. (My browser is Firefox which had problems when I started using Jitsi a little while ago and could impact non-Firefox users so I switched to jitsi-meet.)

**Comment by saghul** [comment]
Not sure I understand, our current implementation of screen sharing does exactly that. It replaces your video with the shared content.

You can the unmute your camera to create a composite image where your camera is overplayed on the bottom right corner, but that’s up to you.

**Comment by RalphCorderoy** [comment]
So I've just been having a play. I agree the large image from my camera is replaced by the shared window. I think what's thrown me is how another person's newly shared window jumps front and centre, replacing whatever I was looking at, e.g. a tiled view of everyone. Is there a way to start sharing a window quietly, not in this 'Look at me!' fashion? That's what I'd be doing when I want to make up for my lack of video, or when lots of us all want to share an artwork window.

Secondly, the video is still visible in the bottom-right corner of the shared window, though the sharer could obviously cloak his video to stop this. I didn't find I could click on the video to see just that instead of the shared window. Nor could I find a way to get rid of it so I could see all the shared window.

Clarifications on whether I'm still misunderstanding the UI would help me determine if there's anything remaining to keep this issue open. :-)

**Comment by mangmang2006** [comment]
If my understanding is correct from the above comments, @RalphCorderoy would like her shared contents would not be pushed out when another participant started to share his/her contents. I tested this scenario: as a host I started a meeting and make everyone follow. When I shared my contents, and other participants could see what I was doing. However, when someone else started a share, his screen would pushed in as the main view, which should be always minimised in the filmstrip, like his video before, because we were in 'everyone follows me' mode.

**Comment by RalphCorderoy** [comment]
Hi @mangmang2006, yes, that sounds right. I would like to be in a meeting where everyone is just displaying their camera feed and I am seeing them all in the tiled layout. One or more of us could then choose over time to switch the video feed we're uploading from the camera to the capture of a window and nothing in the layout of everyone else would change. All they would notice is the video of me, however it was displayed before, is now of a window's contents but otherwise displayed the same way. And with no superimposed camera feed on top to obscure it.

It's as if I have two cameras: one pointing at me which Jitsi was using, and a second pointing at a window on the screen, and I ask Jitsi to switch from one camera to the other.

(Ralph's a he, BTW.  ;-)

**Comment by Echolon** [comment]
@saghul

**Comment by RalphCorderoy** [comment]
Echoing Echolon above, @saghul.

**Comment by RalphCorderoy** [comment]
Why did stale-bot close this? There was further activity.
