### ISSUE TITLE
Allow to share screen on Android

### ISSUE THREAD

**Issue by Yajo** [jitsi/jitsi-meet#6497]
**Is your feature request related to a problem you are facing?**
Well the problem is that I need to share my screen but I cannot.

**Describe the solution you'd like**
Screen share on android app, just like zoom.

**Describe alternatives you've considered**
Zoom allows this.

**Comment by MagicFab** [comment]
These are two relevant forum posts :

* [Allow screen sharing FROM Android App](https://community.jitsi.org/t/allow-screen-sharing-from-android-app/24839) - 2020-03-23
* [#screen sharing on jitsi meet on android](https://community.jitsi.org/t/screen-sharing-on-jitsi-meet-on-android/36329) - 2020-04-16

**Comment by monnier** [comment]
Even a limited version of the feature which allows to share only
particular kinds of documents (for me, PDF or Markdown would cover the
majority of use cases) would be very welcome.

**Comment by rayhaanq** [comment]
Hi, is there any update on this feature?

**Comment by MagicFab** [comment]
> Hi, is there any update on this feature?

If you don't see any here, no. Please subscribe to this issue and you'll get notifications when there is activity. Please don't post comments here unless directly relevant to contributing or helping with this issue, it only increases developers email volume.

**Comment by devidasm** [comment]
Hi Jitsi team,
From my quick research. Here I'm sharing some useful references that very helpful for making android screen share into a reality. 

Please consider this as a request.

1. https://github.com/Jeffiano/ScreenShareRTC
2. https://www.programcreek.com/java-api-examples/?code=Piasy%2FVideoCRE%2FVideoCRE-master%2FVideoCRE%2Fsrc%2Fmain%2Fjava%2Forg%2Fwebrtc%2FScreenCapturerAndroid.java

**Comment by ravishekharco** [comment]
`+1`

**Comment by voipworld** [comment]
+1

**Comment by vijaykholiya** [comment]
+1 for introducing screen sharing feature.

**Comment by saghul** [comment]
Please stop posting "+1", there is a 👍  button for that.

**Comment by Echolon** [comment]
@saghul I close this with reference to this previous issue, ok? Otherwise please reopen!

**Screen sharing on mobile app does not exist** #5252

**Comment by saghul** [comment]
Sounds good, thanks!

**Comment by monnier** [comment]
> @saghul I close this with reference to this previous issue, ok? Otherwise please reopen!
> **Screen sharing on mobile app does not exist** #5252

AFAICT, #5252 only discusses the iOS app, whereas this issue is about the Android app.  AFAIU the two are separate implementations, so I think it makes sense to keep both issues open and separate.

**Comment by Echolon** [comment]
@monnier I am preparing a general overview of the issues at the moment. both will be mentioned. I cannot imagine this will be only implemented for one platform

**Comment by monnier** [comment]
> @monnier I am preparing a general overview of the issues at the moment. both will be mentioned. I cannot imagine this will be only implemented for one platform

I'm not familiar enough with the codebase to be sure, but I find it hard to believe that implementing it for iOS will inevitably lead to it being implemented for Android (especially since the chunks of code that appear in the other issue seem to be written in Objective C which is very Apple-centric).

**Comment by parveensachdeva** [comment]
![image](https://user-images.githubusercontent.com/45853238/90621266-1ada2400-e231-11ea-94f2-eed7424aa495.png)
We getting same issue

**Comment by KanwalKhan-20** [comment]
@saghul after turning on the screen sharing option I am unable to click on any button even the back button.
And once I stopped screen sharing then still I am unable to click on any button.
