### ISSUE TITLE
JitsiMeet chat too eager to convert to emoji

### ISSUE THREAD

**Issue by popindavibe** [jitsi/jitsi-meet#6501]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I stumbled on this while trying to share a URL on the JitsiMeet chat.

## Current behavior
Anything that could be assimilated to an emoji is converted.

## Expected Behavior
I wouldn't expect a subset of a word to be converted. For example, the following should not get any conversion:

https://wiki.example.com/doku.php?id=appliweb:pleroma

Yet on JitsiMeet current result is:

https://wiki.example.uk/doku.php?id=appliweb
😛leroma

## Possible Solution
I think a simple fix would be to ensure that only emoji either at the beginning of the line or after a white space should be evaluated. 

## Steps to reproduce

Sharing anything that contain a sequence that could be assimilated to an emoji. Example:
```
https://wiki.example.com/doku.php?id=appliweb:pleroma
```
# Environment details
Latest Debian repo stock install.

**Comment by missmatsuko** [comment]
I think the test should also check for space after emoji at the beginning of the line, if the message isn't only an emoji. Otherwise might convert something like `://www.example.com` to `😕/www.example.com`.

**Comment by enzoferey** [comment]
Hi there ! I'm the main maintainer of https://github.com/tommoor/react-emoji-render, the library that is currently being used for emoji parsing in this repo apparently. 

We already had a URL parsing [bug](https://github.com/tommoor/react-emoji-render/issues/20) that we fixed and has a test case that is currently passing.

I will investigate further the issues pointed at https://github.com/tommoor/react-emoji-render/issues/54 and come back to you 👍

**Comment by obfusk** [comment]
The behaviour should be fixed in the `react-emoji-render` library now.
As soon as a new version is released, it can be used by jitsi meet.

**Comment by enzoferey** [comment]
[`1.2.3`](https://www.npmjs.com/package/react-emoji-render/v/1.2.3) has been released.

Thank you @obfusk for the help 🙌
