### ISSUE TITLE
Make "Jitsi Meet" available as flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet#6503]
Hellow.

I would like to suggest on you to make "Jitsi Meet" officially available by you as official flatpak package on FlatHub.

Nore: there is other repository for you called "jitsi-meet-electron". I select this repository "jitsi-meet" to request flatpak on FlatHub & did not select "jitsi-meet-electron" for this correct. If I'm wrong & request for flatpak should be in "jitsi-meet-electron" then kindly inform me, so as to close this issue & open new one in "jitsi-meet-electron" repository.

Best.

**Comment by Nokia808** [comment]
Flatpak is a universal Linux package that compatible with almost all Linux distros ...... By making Jitsi Meet available as flatpak on FlatHub, it will be available for almost all Linux distros & users.

Flatpak is secure package system with default sandbox. It offer users automatic updates, & being independent from system version.

FlatHub home page is:
https://www.flathub.org/home
FlatHub repositories are here:
https://github.com/flathub
To post your flatpak on FlatHub, you have to make PR on:
https://github.com/flathub/flathub/pulls

Flatpak documentation here:
https://docs.flatpak.org/en/latest/

Unfortunately, I'm not programmer & not experienced with packaging ........

**Comment by saghul** [comment]
I don’t think we can spend resources on this. We are already maintaining a large amount of packages and we can’t spread ourselves thinner at the moment, sorry.

**Comment by Nokia808** [comment]
@saghul 
Never mind. My point was exactly this: why you tired yourselves with such large number of packages, so it is better to replace them by single package that working on almost all Linux distros ......

It is up to you. 

Last questions: I'm currently installed your AppImage file:
1) does it will show me message when new version releases & I can update to it automatically after that? I did not see "Update" or "Search for new version" option .....
2) does the AppImage also using WebRTC as web version ?
3) which is more secure: web application or AppImage version ? In my mind the AppImage version, is this correct or they are equally secure ?

No further questions.

Thank you.

**Comment by Nokia808** [comment]
@saghul 
Dear since you did not close this issue, I conclude that the shortage in your resource is the cause of negative response. This is okay because you did not refuse the principle ...... For that, I will close this request from this repository & repost it in the correct repository "jitsi-meet-electron".

Best.
