### ISSUE TITLE
Allow mobile users to join with the browser

### ISSUE THREAD

**Issue by tristanlins** [jitsi/jitsi-meet#6506]
**Is your feature request related to a problem you are facing?**

Yes, it beongs to #5799

**Describe the solution you'd like**

After playing around, I find out that a mobile browser IS able to handle a jitsi video call.
I enabled "show desktop site" in my mobile browser and then I was able to join!
The meetings works "well", not so comfortable then the app and it drains my battery. :worried: 
But this would be a nice option for fast joining a meeting without installing the app or for users who have privacy concerns (see #5799).

Personally I would see this as a secondary option next to "Continue to the app".

**Comment by saghul** [comment]
Please see: https://github.com/jitsi/jitsi-meet/pull/3518#issuecomment-611396665

**Comment by tristanlins** [comment]
Whoops, sorry for the noice, I have overseen this PR :see_no_evil:

**Comment by saghul** [comment]
No worries, it got very long, and there is no way to pin a comment...
