### ISSUE TITLE
Problemas con la grabación en Jitsi-meet

### ISSUE THREAD

**Issue by luisvarelacerda** [jitsi/jitsi-meet#6507]
Hola!! estuve con problemas para realizar una grabación en jitsi-meet el mensaje decía que las grabadoras no estaban disponibles. 
¿Es un problema frecuente? ¿Cómo se puede solucionar?

**Comment by kaffarell** [comment]
English is the standard language here, please remove the issue and create a new one in English.

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
