### ISSUE TITLE
All participants are moderator

### ISSUE THREAD

**Issue by rcampion** [jitsi/jitsi-meet#6511]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
All participants are moderators

## Current behavior
All participants are moderators

## Expected Behavior
Only first participant in room is moderator

## Possible Solution
---

## Steps to reproduce
Login with first user/password on one machine
Login with second user/password on another machine

# Environment details
CentOS7
Openfire 4.5.1
Ofmeet  0.9.9
Jitsi Meet / master branch 04/30/2020

**Comment by luixxiul** [comment]
Did you try setting "secure domain"?

**Comment by saghul** [comment]
Since you are using open fire and ofmeet, you need to ask them for the server configuration they provide.
