### ISSUE TITLE
All recorder are currently busy

### ISSUE THREAD

**Issue by lambda121** [jitsi/jitsi-meet#6518]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check com
![jitsi-meet-issue](https://user-images.githubusercontent.com/58508754/80798793-d0ba2d80-8bc2-11ea-93d8-9e0c9f7e029c.jpeg)
munity.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Jitsi meet recording not working.

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
Doesn't always happen but started happening very frequently.

# Environment details
---

**Comment by luixxiul** [comment]
See: https://github.com/jitsi/jitsi-meet/issues/5403
