### ISSUE TITLE
Network request failed: Android SDK

### ISSUE THREAD

**Issue by khyatiChitroda** [jitsi/jitsi-meet#6519]
*Network request failed.*

 I installed SDK for android and try to run this app, when I use default serverUrl ="**https://meet.jit.si**" it works perfect, but when I try to add my server url it gives me below error, hence my URL is working properly on web it gives error in mobile sdk only.

[features/base/lib-jitsi-meet] Failed to load config from https://ai2.xxxx.com/config.js?room=Hello Error(TypeError){"message":"Network request failed"}

followed this :

https://github.com/jitsi/jitsi-meet/blob/master/android/README.md

**Comment by khyatiChitroda** [comment]
@saghul 
can you help me on this

**Comment by saghul** [comment]
Does your server have a valid TLS certificate? Also make sure the cert chain is correct, see: https://whatsmychaincert.com/

**Comment by khyatiChitroda** [comment]
yes we have, it is working proper on desktop only getting problem into mobile app

**Comment by saghul** [comment]
Have you tested the cert chain? Desktop browsers are more forgiving.

**Comment by khyatiChitroda** [comment]
yes it shows misconfigured, I downloaded chain.crt,
now where I have to put this ?

Actually I am new to React-native so...

**Comment by saghul** [comment]
This has nothjing to do with React Native. It's a web server configuration, which varies depending on what wevserver you are using.

There is a section on that site titled "Configure Your Server" please follow those instructions.

**Comment by erengms** [comment]
Same issue. 
[features/base/lib-jitsi-meet] Failed to load config from https://ai2.xxxx.com/config.js?room=Hello Error(TypeError){"message":"Network request failed"}

use the same server but development device is working, production device not work.

**Comment by athenadever** [comment]
@khyatiChitroda  Hi, How are you?
Did you solve above issue? I got error and couldn't solve it.

**Comment by athenadever** [comment]
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/13590b95-56fd-463f-bd9a-1c8ee8a799cf)
As you can see, my server is self-signed. But Network request failed still.
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/36d83128-e861-40a4-82b6-23eebf245723)
@saghul  Please reply me.
Thanks

**Comment by saghul** [comment]
We don't support self-signed certificates, you need to use a real one.

**Comment by athenadever** [comment]
Thank you for replay
Good luck

**Comment by athenadever** [comment]
Hi @saghul 
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/18439b39-aacf-41bf-8b71-f93bddb5ffe8)
After installed jitsi server on ubuntu 22.04, I tried to access to server.
But I can see only black page and this error.
And I'm not sure this is correct. 
![image](https://github.com/jitsi/jitsi-meet/assets/94537778/a4a5b250-c480-4dfe-a7b2-d1612723dfbe)
Please guide me.
Thanks

**Comment by damencho** [comment]
Please avoid posting for the same issue in multiple places. Once is enough, and you better do it in the community forum.
