### ISSUE TITLE
Mobile application doesn't works with OnPremise servers

### ISSUE THREAD

**Issue by jlemangarin** [jitsi/jitsi-meet#6520]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
The "You have been disconnected. You may want to check your network connection." classic issue triggers when I try to connect to my Jitsi staging server on {DM me for URL} on iOS and Android. i've already checked my certificates and my configurations.

Also on my production server {DM me for URL} it works only on iOS, the only difference is the version of Jitsi meet that is updated in my staging server.

But what I don't understand is that in my staging server the iOS app downloads the config.js file and then crash when in my production server it does the same request and continues to http-bind. The config.js are nearly the same except the domain names.

On iPad it seems to connect to staging but without video (which may be another issue)

Staging : 
![staging](https://user-images.githubusercontent.com/22454938/80802879-f8a09580-8bb0-11ea-9b63-45cb7b5bd6fd.JPG)

Prod : 

![prod](https://user-images.githubusercontent.com/22454938/80802884-fe967680-8bb0-11ea-8a3e-d622ed0d646b.JPG)

With the android app nothing works.

## Current behavior
See description

## Expected Behavior
Applications works

## Possible Solution
?

## Steps to reproduce
Sens me a DM for the URLs

# Environment details
Jitsi-meet / Prosody / Nginx / Java 8
iOS 13.x / Android 9

**Comment by cpot** [comment]
+1 highly important

**Comment by jlemangarin** [comment]
After updating our production it seems that the focus works (not the video but certainly another issue) so it seems to be related to our staging environment but I don't undersand why.. I've checked all certificates.

**Comment by saghul** [comment]
I have seen this often times because the chain cert is wrong. You can check it here: https://whatsmychaincert.com/

**Comment by gpatel-fr** [comment]
same thing here, my server (Debian packages Jitsi-meet 2.0.4548-1) works with Chrome and Firefox, but on Android exactly the same behaviour than for @jlemangarin. My site checks fine with whatmychaincert.com

**Comment by jlemangarin** [comment]
@saghul Thank you for your answer, as I said I already read all the topics (nearly) talking about this and I've already checked my chain certificate : 

![image](https://user-images.githubusercontent.com/22454938/81041689-baf08500-8eae-11ea-9df3-2ff5ebcf53ff.png)

@gpatel-fr What was the mistake ?

**Comment by saghul** [comment]
Can you share your deployment URL?

**Comment by gpatel-fr** [comment]
@jlemangarin 
oh it was so silly :-) . I add added what I believed was a [clever trick](https://community.jitsi.org/t/overriding-features-without-change-in-sources/42409/2?u=gpatel-fr) to avoid changing my interface_config.js. I don't check my site usually on mobile but after the last upgrade I decided to give it a go and I believed for some hours that the upgrade was the culprit. Well the trick works in a browser but not in Android app.

**Comment by jlemangarin** [comment]
@saghul Sure, I just sent you an email

**Comment by jlemangarin** [comment]
Hello @saghul, did you received my email ?

I'm running out of ideas on this issue.. This is really important to use because we plan to deploy your solution in french ministries, regions & town halls (actually we already had but it was unstable before switching from Ejabberd to Prosody).

**Comment by saghul** [comment]
Yes I have, but ran out of time today, I'll try to get to it tomorrow, sorry.

**Comment by cpot** [comment]
Some additional informations 

- on android and iOS : immediate de-connections
- on iPAD12 (same build than iOS) :

**Works only if :** 
- p2p mode
- server config : https://myjitsiserver/
- room name : jitsi-meet/mytestroom

**Comment by saghul** [comment]
Does accessing `https://myjitsiserver/jitsi-meet/config.js` work?

**Comment by cpot** [comment]
if i do tha

> 
> 
> Does accessing `https://myjitsiserver/jitsi-meet/config.js` work?

if i do that in a browser yes it works

**Comment by saghul** [comment]
Hum, we might have a bug in mobile when handling eployments from a subdirectory then :-(

**Comment by cpot** [comment]
> 
> 
> Hum, we might have a bug in mobile when handling eployments from a subdirectory then :-(

Do you need some part of our config.js to help ?

**Comment by saghul** [comment]
I don't have the time to look at it this week, I'll take a look the next one. Ping me here if I forget!

**Comment by cpot** [comment]
> 
> 
> I don't have the time to look at it this week, I'll take a look the next one. Ping me here if I forget!

Well we will ping you because it is highly important for our customers. Do you know if there is a way as a workaround to avoid mobile browser redirect to the app version ? thanks a lot

**Comment by jlemangarin** [comment]
Hello !

Just to say, I tried to change our server configuration and switch from /jitsi-meet to / but it also didn't worked.

I'm not sure that it's related, also it seems to work partially (no audio / video) on certain devices (iPad).

**Comment by haydininfo** [comment]
We have exactly the same behavior. We tested with several servers (ubuntu, apache, nginx etc.) After we disable p2p mode, mobile app does not work anymore. 

If p2p is enabled, it works only for two participants, also the mobile app works fine in this case. After a third person joins to the meeting, mobile app loses the connection, audio and video of other participants are deactivated.

We are using the following workaround right now, in order that participants can join via mobile phone or tablet:
- Open meeting link in chrome 
- Screen with redirection to app appears. Go to the settings of chrome and activate desktop website.

After these steps, joining via mobile phone works without any problem except the screen is not  responsive and users must zoom in/out.

![image](https://user-images.githubusercontent.com/64259116/82142854-c09b8280-983f-11ea-91a8-c6c48a3d0eab.png)

**Comment by jlemangarin** [comment]
On our side, we still get the "You have been disconnected" error message except if we use an iPad where we have the exact same behavior that you described.

@saghul we really need further investigations on this blocking issue since Jitsi Meet is on it's way to be the essential N° 1 open source application against Zoom, GoToMeeting etc..

Tell us if we can help on something

**Comment by bluikko** [comment]
Interesting thread. Back in 4101 and likely in 4384 (docker-jitsi-meet) everything was working - desktop browser, iOS, Android - now in 4548-1 only desktop browser is working for me too. Did not get far in troubleshooting yet so I can't say that there's no problem with my configuration.

But it is interesting to see many have problems with the mobile apps now. For my Android - I get the "You have been disconnected." dialog when trying to join a room; one user who was using Jitsi Android previously had everything working until they re-typed the Server URL in configuration and after that get "You have been disconnected." as well...

I do not see anyone listing the versions and how you are running the server and the client version. That should be the first thing to do @jlemangarin @haydininfo and others.

I'm on 4548-1 docker-jitsi-meet (modified for Traefik v1 use); 20.2.3 build 4129209 Android.

**Comment by bluikko** [comment]
Well, in the end my problem was indeed wrong configuration. There was a hint in #5864 - the SSL certificate chain. For some reason previously the Android client worked without server sending the SSL certificate chain (CA certificates). On the later versions of Android and/or Jitsi mobile that does not work.

Added the CA certificates (root + intermediate) to the certificate file and now Android client works for me. Interesting that all production Docker servers were configured without certificate chain and there has been no other complaints - these are busy servers with much more than just Jitsi being served.

When just the mobile app doesn't work it could be good idea to test with https://whatsmychaincert.com/

**Comment by saghul** [comment]
Thanks for elaborating folks. I’ll allocate some time o dog into this on Monday.

**Comment by cpot** [comment]
From what i recall, any Jitsi mobile app never worked with Onpremise servers (with any jitsi version), and our certificate have no issues. 

Here is our last app versions :
IPAD 12.4.1 JITSI 20.2.3 build 71
ANDROID 6.0.1 JITSI 20.2.3 build 4129209

**Comment by luixxiul** [comment]
@cpot you should consult https://community.jitsi.org/ asking for help to set up your instance correctly.

**Comment by cpot** [comment]
@luixxiul my team (@jlemangarin) spend hours to try help and we lack now of any additional ideas, our instance is working correctly (no problem with the webapp)

We are already contributors here : 
https://community.jitsi.org/t/no-video-or-audio-on-ios-app/35479/2

**Comment by bluikko** [comment]
@cpot Demonstrably Jitsi does work on-prem since many people have it working.

Did you actually check your configuration with https://whatsmychaincert.com/ ? How is your server installed?

**Comment by cpot** [comment]
@bluikko https://github.com/jitsi/jitsi-meet/issues/6520#issuecomment-623887434

Yes the chain is correct

**Comment by saghul** [comment]
> From what i recall, any Jitsi mobile app never worked with Onpremise servers (with any jitsi version)

This is 100% incorrect. They always have, from day 1.

I tested both the iOS and Android apps against a freshly installed Docker setup with a Let's Encrypt certificate and everything is ok, so we'll need to dig deeper.

**Comment by saghul** [comment]
So, I found the problem. Your config.js (I checked on the URL @jlemangarin sent me) contains executable code. On mobile that is not supported. We download and evaluate the config file in a sandbox for security reasons, so things like window.location are not available. In fact we serialize the object to JSON and pass it back out of the sanddbox.

I understand this limitation is not very obvious.

**Comment by jlemangarin** [comment]
Hello @saghul,

I fixed all the issues on the "gofast-preprod"... server (chain and JS code) but it still shows the same error message and doesn't works..

Thanks in advance for your help !

**Comment by haydininfo** [comment]
> We have exactly the same behavior. We tested with several servers (ubuntu, apache, nginx etc.) After we disable p2p mode, mobile app does not work anymore.
> 
> If p2p is enabled, it works only for two participants, also the mobile app works fine in this case. After a third person joins the meeting, mobile app loses the connection, audio and video of other participants are deactivated.
> 
> We are using the following workaround right now, in order that participants can join via mobile phone or tablet:
> 
> * Open meeting link in chrome
> * Screen with redirection to app appears. Go to the settings of chrome and activate desktop website.
> 
> After these steps, joining via mobile phone works without any problem except the screen is not responsive and users must zoom in/out.
> 
> ![image](https://user-images.githubusercontent.com/64259116/82142854-c09b8280-983f-11ea-91a8-c6c48a3d0eab.png)
> 
> Edit on 03.06.2020:
> After I did a fresh installation behind NAT and with Ubuntu Server 20.04, it works well with android and ios app, even tough p2p is disabled. The only differences are as follows:
> 
> * Ubuntu 20.04 instead of 18.04 (please also check issue [#6878](https://github.com/jitsi/jitsi-meet/issues/6878) reg. using certbot instead of using certbot-auto
> * Server behind NAT & Server with public IP. The server behind NAT is available via SSH Tunnel (Reverse Proxy). Earlier, I did the installation on a server, which was directly available via Public IP.

see my reply from today. with the new configuration, jitsi meet seems to work very well know.

**Comment by saghul** [comment]
> I fixed all the issues on the "gofast-preprod"... server (chain and JS code) but it still shows the same error message and doesn't works..

I just tested the preprod server again and it works just fine with an iOS client.

**Comment by jlemangarin** [comment]
Thank you for your feedback, could you please send me your configuration (what you filled and where) ?

Thanks in advance !

**Comment by saghul** [comment]
I didn't fill anything, just used the full URL in the room field and joined the room.

**Comment by jlemangarin** [comment]
Like this ? 

![B4C60435-D1DA-4CEC-BBD2-D0472CEC4BDD](https://user-images.githubusercontent.com/22454938/83613298-dc16c500-a583-11ea-9d81-847a2786ff1d.png)

Here is the result for me :

![DF9B02C5-90C3-4013-97E9-5A896FC5588F](https://user-images.githubusercontent.com/22454938/83613338-e9cc4a80-a583-11ea-8747-eeee3c50d28c.png)

We will try on other devices ASAP..

**Comment by saghul** [comment]
Yes, the preprod server worked for me that way. Note that you need to specify https:// too.

**Comment by jlemangarin** [comment]
After further investigations, it seems that it was a caching issue as reinstalling the application on my phone resolved the issue. It's working now and I'll deploy the fix on all our instances ASAP !

Thank you for your time !
