### ISSUE TITLE
Hold a selected user when other user connects or shares a screen

### ISSUE THREAD

**Issue by DarkR** [jitsi/jitsi-meet#6526]
Hi!

I'm trying to fix all my selections of users to record them separately in different browser tabs, but when someone new connects or shares their screen all my selections change.

Could you please make it possible to fix all selected users nomatter what happens next.

I'll make a donation for that feature. Thanks a lot.

**Comment by saghul** [comment]
I’d you pin a user, that is, if you click on it on the filmstrip, their video is going to be displayed on the large view and won’t change... except if someone starts to share their screen. This is intentional and there are no plans to change that, sorry.

**Comment by DarkR** [comment]
Ok, thanks for the reply. Then we'll find another separate way to share screen.
