### ISSUE TITLE
Firefox unstable during meetings

### ISSUE THREAD

**Issue by nikosbo** [jitsi/jitsi-meet#6527]
## Description
During today call on https://meet.jit.si I had with 3 other participants, 2 with Jitsi meet app and 1 with Chrome, I had one Firefox unexpected closure and a couple of freezes, fixed reloading the tab with the meeting.
3 days ago with 6 participants, I didn't have these issues.

## Steps to reproduce
Maybe to be more than 2 people with microphone unmuted, camera active and video quality HD.

# Environment details
I use Firefox 75.0 on Ubuntu 18.04LTS, connected by cable to my modem.

**Comment by luixxiul** [comment]
it might be related with https://community.jitsi.org/t/loss-of-participants-video-and-sounds-crashs-when-12-attendees/50260/5

**Comment by saghul** [comment]
When you say Firefox closed, you mean the browser itself crashed?

**Comment by nikosbo** [comment]
Yes, I suppose it crashed, even if when I opened it again, it reopened all tabs without the message which asks to send data for troubleshooting.

Yesterday I participated to another meeting with 5 participants without issues.

How could I collect info in case of similar issues?
Nikos

Il 5 maggio 2020 08:06:36 CEST, "Saúl Ibarra Corretgé" <notifications@github.com> ha scritto:

**Comment by saghul** [comment]
If the browser crashes, then it’s a browser bug, JS code shouldn’t cause the browser to crash.

I suggest you fill in the dialog that shows up after a crash so you can report it to Mozilla.

**Comment by nikosbo** [comment]
I hadn't the issues when a new participant joined the meeting.
For sure other participants streaming abd audio on my side freezed without changements.
From the post, it looks that changements are applied week by week, so it's difficult to troubleshoot.
Maybe this evening I'll have another meeting, I'll share my feedback.
Nikos

Il 5 maggio 2020 06:48:59 CEST, Suguru Hirahara <notifications@github.com> ha scritto:

**Comment by nikosbo** [comment]
This evening, in 1 hour more or less, I had 1 freezing of other participants on my side, I reloaded tab and I fixed.

**Comment by ndgnuh** [comment]
I got crashed tab + no audio on Firefox. Audio on other applications works.

**Comment by nikosbo** [comment]
Hi all, this evening I had a call of 1hour and a half with other 8 participants and I didn't have any issue with Firefox 75. :-)))

**Comment by luixxiul** [comment]
See: https://community.jitsi.org/t/today-issue-on-meet-jit-si-with-audio-and-video/52403/17

> We believe the issue is now addressed everywhere. We have made Jicofo and JVB changes to address this.

Closing the issue as fixed.
