### ISSUE TITLE
jitsi chrome and edge failed to access your camera

### ISSUE THREAD

**Issue by dmoibm** [jitsi/jitsi-meet#6528]
## Description
On Chrome and Edge Browser I get the Error "Failed to access your camera". In Firefox it works perfectly. 

## Current behavior
This error prevents selection of a working cam

## Expected Behavior
Let the user select a working cam before showing the error.
 
## Possible Solution
Show at  https://webcamtest.com . They let you select the cam even the default cam doesn't work.

## Steps to reproduce
Install something like EpocCam and don’t connect it to the phone. On most system, EpocCam is the first cam in the list and is called a “master” cam. Than you can start your Jitsi session and get the Error. After that, you can deactivate the device EpocCam in the device manager of windows and now it works like a charm.

# Environment details
Windows 10, Chrom 81.0.4044.129 64-Bit, Microsoft Edge 84.0.495.2

**Comment by saghul** [comment]
Please check pinned issue about webcam problems.
