### ISSUE TITLE
Error 520 on Cloudflare with nginx as webserver

### ISSUE THREAD

**Issue by ExtraHash** [jitsi/jitsi-meet#6535]
## Description
---

Enabling cloudflare on a jitsi-meet server results in an error 520 when using cloudflare, but only when using nginx as the webserver. According to cloudflare, these common issues can cause this error:

- Origin web server application crashes
- Cloudflare IPs not whitelisted at your origin.
- Origin web server TCP idle timeouts shorter than 300 seconds
- Headers exceeding 8 KB (typically due to too many cookies)
- An empty response from the origin web server that lacks an HTTP status code or response body
- Missing response headers or origin web server not returning proper HTTP error responses

## Current behavior
---

The server gives some invalid response to cloudflare which causes it to throw an error 520 when DNS tunneling is enabled. 

## Expected Behavior
---

The server connects as usual through cloudflare.

## Possible Solution
---

I was able to get this working by setting apache2 as the webserver instead of nginx. Additionally, this was working just fine a couple weeks ago, so something must have changed with a recent update. Here's a jitsi community forum link of other people experiencing the same issue:

https://community.jitsi.org/t/jitsi-latest-version-cloudflare-error-520/31586

## Steps to reproduce
---
1. Fresh install ubuntu 18.04
2. Install jitsi meet with nginx
3. enable cloudflare on domain
4. access domain

# Environment details
---

```
ender@jitsi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
ender@jitsi:~$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
ender@jitsi:~$ neofetch
            .-/+oossssoo+/-.               ender@jitsi 
        `:+ssssssssssssssssss+:`           ----------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.4 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-4.1) 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-88-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 42 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 611 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel (Skylake, IBRS) (1) @ 3.792GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: Cirrus Logic GD 5446 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 427MiB / 1993MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss. 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+ 
   /ssssssssssshdmNNNNmyNMMMMhssssss/ 
    .ossssssssssssssssssdMMMNysssso. 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-. 


```

**Comment by obfusk** [comment]
Could be an ALPN issue? The default jitsi-meet nginx config defaults to sending traffic to the turn server when the client doesn't explicitly ask for `h2` or `http/1.1` via ALPN.

`openssl s_client -connect jitsi.example.com:443` does not connect to the http server;
`openssl s_client -connect jitsi.example.com:443 -alpn http/1.1` does.
