### ISSUE TITLE
Old, but still existing issue: underscore and hyphen in meeting name

### ISSUE THREAD

**Issue by testerik** [jitsi/jitsi-meet#6536]
Hi,

I see that this recurring issue is solved for example in the Docker Version (https://github.com/jitsi/docker-jitsi-meet/issues/290) and there are instructions how to fix it with Nginx. But nevertheless the problem still existis with Apache as a Webserver:

The Jitsi Meet room names don't accept "special characters" like Underscore or hyphen. Even worse, you get a 404 instead of a helpful error message.

I use the provided stable .deb-Package Version 2.0.4548-1 from download.jitsi.org together with Ubuntu 18.04. Could you please fix this or point me to a source how can I do this by myself?

**Comment by damencho** [comment]
Here is the apache config template https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example-apache

**Comment by testerik** [comment]
This is the template which is installed from the the install script and which I used already. After tracing the rewrite condition I guess that the request _/http-bind_ prevented a RewriteRule which matched fopr a hyphen.

So I changed the Rewrite sequence to:
```
RewriteEngine on
RewriteCond %{REQUEST_URI} !^/http-bind$
RewriteRule ^/([a-zA-Z0-9_\-]+)$ /index.html
```

Is this OK with you? Or are there more request like _/http-bind_, which should not be rewritten? If not, you should change the Rewrite rules in the template, because this is a very common question from users of Jitsi.

**Comment by damencho** [comment]
The nginx one is more updated https://github.com/jitsi/jitsi-meet/blob/1a40672427a281fb2c5d560e199c9e19b0ebbdd8/doc/debian/jitsi-meet/jitsi-meet.example#L78 maybe if you match that, and it works for you, create a PR so we can update and apache2 one. Thank you.

**Comment by Aaryan-kapur** [comment]
Is there any such solution for periods(" . ") too?

**Comment by rjmaris** [comment]
> ```
> RewriteEngine on
> RewriteCond %{REQUEST_URI} !^/http-bind$
> RewriteCond %{REQUEST_URI} !external_api\.
> RewriteCond %{REQUEST_URI} !xmpp-websocket
> RewriteRule ^/([a-zA-Z0-9_\-]+)$ /index.html
> ```
> 
> The problem is solved for me, but you should do similar modifications on your site.

The proposed changes as quoted here are tested as okay. The three RewriteCond lines however are essential because otherwise the connection is terminated immediately after entering a room when _ or - is in the name.
@damencho's suggested regexp update from the `nginx` example however results in steady output of `an error occured while processing this directive` in the browser window, The same applies to the latest committed nginx regexp `^/([^/?&:'"]+)/(.*)$`.

I think that it would make sense to modify the `RewriteRule` into a next commit. However, doing so would also disallow to test whether a jitsi server is running on `nginx` or `apache2`. ;-)

**Comment by damencho** [comment]
> **Sidenote** (added as edit): Since 2021, the `nginx` example is modified & committed a couple of times until recently. This does not apply to the `apache` example. Hence, it seems that Apache based installs are no longer supported.

We are not actively using Apache, so the configuration we have is based on contributions from the community.
