### ISSUE TITLE
Screen Sharing Problem

### ISSUE THREAD

**Issue by frederiklawson** [jitsi/jitsi-meet#6538]
Previously (several days ago), everything is working fine with MEET.JIT.SI
I can share my presentation to my other colleagues and clients in a way where I can see the meeting participants while I am presenting the presentation.
Now the JITSI even can not recognise the window of the program / application that I use for the presentation, even using the ENTIRE SCREEN sharing way.
Have tried with Chrome and Opera browsers.
No luck until now
Please advice... thank you

**Comment by luixxiul** [comment]
Basically meet.jit.si is an *alpha* service and many experiments are being done simultaneously there.

If you are looking for a stable solution, you should set up your own Jitsi instance, which is not so difficult. See https://www.digitalocean.com/community/tutorials/how-to-install-jitsi-meet-on-ubuntu-18-04 for the tutorial.

**Comment by saghul** [comment]
@luixxiul That is not correct. meet.jit.si is not alpha quality software.

@frederiklawson do you see any problems in the JS console?

**Comment by luixxiul** [comment]
@saghul Apologies- I misread here: https://jitsi.org/blog/e2ee/

> we allowed for e2ee keys to be passed to Jitsi Meet via a URL parameter. This is already enabled on our alpha deployments as well as on meet.jit.si

**Comment by frederiklawson** [comment]
Hi everyone

The previous disco display has gone after I installed the JITSI Chrome
extension (as I use Chrome browser)
I do not know with other browsers, but I believe there should be other
browsers' extension as well.

But, I have another question regarding SCREEN SHARING
I am using PowerPoint or WPS Office to do the presentation
As I do the screen share, the presentation screen does not in the same
window as the conference screen
So, during my presentation, I can not see the participants or if there is
new participant who attend the presentation
I have to minimize the presentation screen and put it on top of the
conference screen
Is there a way or settings that I should do to integrate both windows in
one screen ?

Thank you, be safe and healthy

**Comment by Nezzal** [comment]
I have a problem with screen share, it multiply my screen?
![Capture d’écran 2020-06-01 à 10 36 05](https://user-images.githubusercontent.com/48630318/83396404-d68a7500-a3f3-11ea-8dd5-ee6442722f7b.jpg)

**Comment by saghul** [comment]
@Nezzal That has nothing to do with this. It’s what happens when you share the entire screen and look at the result at the same time. It’s normal.

**Comment by saghul** [comment]
@frederiklawson I don’t know how the extension can be related, since it hasn’t been needed for a long time now.

At any rate, Jitsi will help you share your screen or a window, but it won’t embed the presentation in the meeting. If you want to see your presentation and the conference you’ll need to have both windows visible.

**Comment by Nezzal** [comment]
Thank you.
