### ISSUE TITLE
Mobile app: remove "more options" and just show all options

### ISSUE THREAD

**Issue by monkeydom** [jitsi/jitsi-meet#6552]
## Description
Currently on the native app the overflow menu hides vital options behind a user unfriendly ("more options") area. Let us just remove this and give access to all options immediately

## Current behavior
Many vital options (e.g toggle camera and toggle tile view) are behind a "more options" button in the main overflow menu

## Expected Behavior
Toggle camera and toggle tile view should be more accessible. Additionally the interface idea of show more is a bad one.

## Possible Solution
Expose all options directly, there is enough space and this is more user friendly

additionally arguably the order of the items should be changed as well. E.g. the more common options should be listed earlier. Proposed order:
* Raise your hand
* Toggle Camera
* Toggle Tile View
* Add Meeting Password
* Invite someone
* Enable low bandwidth mode
* Start Live Stream
* Start showing subtitles

## Steps to reproduce
just use the app on an iPhone/iPad

# Environment details
Affected version iOS 20.2.3 build 71

**Comment by saghul** [comment]
We grouped in 2 levels because it's unwieldy to use otherwise. We are now working on a new redesign, which hopefully gets us rid of the second level of options.

I'll keep this open for reference.

**Comment by monkeydom** [comment]
How much of a redesign are you doing? E.g. hand raising and camera switch should be accessible differently imho.

I'm asking to see if it is worth putting time in to come up with better suggestions. This pull request was just a quick remedy for the most problematic one in the use around our peer group in these times.

**Comment by monkeydom** [comment]
Also I could offer to just regroup the entries in a way that seems more logical to me. E.g. do the reordering but make the more options cut off after toggle tile view.

**Comment by saghul** [comment]
Please don't spend time on this as work is unerway.

**Comment by luixxiul** [comment]
Do you mean the essential fix is on its way?

**Comment by saghul** [comment]
Yes, a new bottom sheet design is being worked on.

**Comment by luixxiul** [comment]
Which commit closed this issue?

**Comment by saghul** [comment]
None, I'm closing it because it has nothing actionable at the moment.

**Comment by monkeydom** [comment]
Hmm. Would be nice to have at least a tracking issue for this. My private environment still suffers from this in a sense that a lot of time on first time users need to be guided to these ui positions.

**Comment by manojverma-net** [comment]
Hi @saghul, Could you please progress update like where can we updated sdk? Thanks !!

**Comment by manojverma-net** [comment]
@saghul  - any update here please.

**Comment by aguilalibre** [comment]
I am also very interested in this. Expecting the update. 👍
