### ISSUE TITLE
After importing .aar package of jitsi meet sdk in a project. Do i need to implement the org.jitsi.react:jitsi-meet-sdk:+ in my build.gradle

### ISSUE THREAD

**Issue by GauravAndroidIS** [jitsi/jitsi-meet#6556]
Hey i have imported the .aar package in my code after building it using command 
./android/scripts/release-sdk.sh /tmp/repo

But now do i need to implement the org.jitsi.react:jitsi-meet-sdk:+ in my app build.gradle file?
and which path do i need to add in the maven url?

This is a bit confuse. Please guide me on the same
I want to know the deatils of this following steps:-

1. **I have build the sdk by this command by this command 
./android/scripts/release-sdk.sh /tmp/repo
in this command /tmp/repo is a path of what?**

2. **i have imported the .aar file as a module from the build folder of the jitsi sdk to my project do i need to implement the 
org.jitsi.react:jitsi-meet-sdk:+ dependency also in app build.gradle file**

3. **In maven what path should i use if i have imported the .aar file in my project?**

**Comment by saghul** [comment]
Check these examples: https://github.com/jitsi/jitsi-meet-sdk-samples

**Comment by GauravAndroidIS** [comment]
I have checked this project this is useful if I don't want to customize the sdk. But I want to customize the sdk. So if you please answer the above query that will be very helpful for me?
