### ISSUE TITLE
Audio lag (desynchronized from video)

### ISSUE THREAD

**Issue by ncote** [jitsi/jitsi-meet#6557]
## Current behavior
Using meet.jit.si, the audio often lags far behind the video; I've experienced up to 10 seconds, but usually about 5 seconds.  

I've experienced this in conferences with just two participants and also with five participants.  With five participants, only one user's audio lags.  All other participants in the 5-person conferences had the same experience (i.e. all witnessed that one of the participants had audio lag).  Disconnecting and re-connecting does not solve the issue.  Switching to Low Definition does not solve the issue.

I'm using Chrome 81 on Windows 10, and the lagging users were using either the Android app (just installed on May 1), or Chrome on an ASUS Chromebook.  

I have noticed these lags in about one third of video conferences since I started using Jitsi, approximately 4 weeks ago.

## Expected Behavior
Quality would be expected to degrade with network conditions, but audio and video should stay roughly synchronized.

# Environment details
https://meet.jit.si
Chrome and Android app

**Comment by quazgar** [comment]
I also experience lag from time to time in conferences, also often experienced by only one participant. Logging out and in again usually "fixes" this.

## Idea ##

Maybe just add a small "re-synchronize button"? (At the cost of losing a few seconds.)

**Comment by sixfeetaway** [comment]
I’m experiencing this on public Jitsi meet using the external api to the point that it’s unusable. Has anyone else had this issue?

**Comment by ncote** [comment]
I am also now experiencing this with my own installation on a Digital Ocean droplet (VM), with a single conference with 3 to 5 users.   CPU and RAM are never overloaded (roughly 1GB allocated of 2GB total, CPU hardly exceeds 30%.).  One participant will have their audio lag behind by several seconds, in roughly half the video conferences I've run.

**Comment by nicolasbadia** [comment]
This is still an issue for us too.

**Comment by arnowelzel** [comment]
Here as well, even in 2024
