### ISSUE TITLE
LE certificate generation script fails

### ISSUE THREAD

**Issue by ktechmidas** [jitsi/jitsi-meet#6558]
#6212 
Description
---
It looks like Jitsi is expecting Python 3, on Ubuntu/Debian this is explicity under python3 and it defaults to Python 2.

## Current behavior
Creating virtual environment...
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython2-posix}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list]
                  [--clear] [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
                  [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: --no-site-packages
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 2

## Expected Behavior
A certificate is generated

## Possible Solution
I'm guessing Jitsi is expecting Python 3?

## Steps to reproduce
---
Run /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

# Environment details
---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Comment by l3d00m** [comment]
Hi @ktechmidas, can you verify again that you are on 18.04.? So far the issue was only known for ubuntu installations with 20.04.

**Comment by Sviundt** [comment]
Get the same behavior on Debian 10, running latest stable updates.

It seems that the Letsencrypt script at https://dl.eff.org/certbot-auto that get fetched when running `sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`, automatically installs python2.7 requirements, even with python3 installed.

Tried removing python2.7 before running the script, but 2.7 is back after a quick run that fails.

**Comment by saghul** [comment]
There is an env variable that makes it use Python 3. Can you try this: `export USE_PYTHON_3=1` before running the script.

**Comment by aliadnan1984pk** [comment]
Hi I got same error today on Ubuntu 18.04.4 LTS . 
i tried above suggestion of `export USE_PYTHON_3=1`
but didn't work . 
below is error i got at the end of running `sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`
```

Creating virtual environment...
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 23, in create_venv
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', '/opt/eff.org/certbot/venv']' returned non-zero exit status 1.

```

**Comment by l3d00m** [comment]
Closing as no further feedback was given, feel free to reopen with more details if it still persists. Also seems fixed as far as I understood this.
