### ISSUE TITLE
Android app settings do not work on Android devices.

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet#6559]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
I installed Jitsi Meet on my Android mobile, launched it, created a room, made conference & all this worked okay. But when I tried to click on gear located on upper right corner of application that take shape of 3 horizontal lines one above other, then no setting appeared to me ! 
## Current behavior
---
By clicking icon located in upper right corner of UI, thing happened apart from screen become more darker but no setting appear to me so that I can change user nake, email, or server URL !
## Expected Behavior
---
There should be a setting UI appearing so that user can edit user name, email, server URL ......
## Possible Solution
---

## Steps to reproduce
---

# Environment details
---
My mobile device is Honor 8X, model JSN-L22, number of version 10.0.0.183(C185E2R1P1), EMUI version 10.0.0, Android version 10, kernel 4.14.116

**Comment by Nokia808** [comment]
@saghul 
Hi. This issue is still existing. Moreover, it is not limited to Honor 8X ! I bought new mobile (Nokia 7.2 with Android one - Android 10) & suffer from same issue.

Kindly, remove automatic label "wontfix"

**Comment by Nokia808** [comment]
I changed title to be more accurate for the case.

**Comment by Nokia808** [comment]
Hi. This issue (bug) is still existing without any fix inspite the huge improvement of Android application in it's lest version !

Kindly, give attention to it.

**Comment by Nokia808** [comment]
@saghul 
Please re-open this issue again.

**Comment by saghul** [comment]
I cannot reproduce the issue with any of my devices so unless someone contributes a patch I don't see this getting fixed, sorry.

**Comment by saghul** [comment]
We have reworked the menu, it should work fine now.
