### ISSUE TITLE
Fix recording

### ISSUE THREAD

**Issue by apixs** [jitsi/jitsi-meet#656]
After [recording setup](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#enabling-recording), click on the recording button gives: "The live streaming service is currently unavailable. Please try again later.".

**Comment by eduardo606** [comment]
I have the same problem.
¿Possible Solution?

**Comment by yanas** [comment]
The recording documentation is outdated and only indicates how to do a "colibri" type of recording using the jitsi-videobridge. This project has been discontinued and we'll update the documentation for our newly supported method of recording using Jibri.

**Comment by ankitarora12** [comment]
Any updates on this??

**Comment by FreeScholar** [comment]
would love an update!

**Comment by yanas** [comment]
The JVB recording isn't currently working and the project is on pause. Use jibri recording instead: https://github.com/jitsi/jibri

**Comment by filhocf** [comment]
@yanas , thanks by your reply. 

So, could be better close this ticket now, because you are pointing to jibri as solution. Can we understand that is a official position from Jitsi project?

**Comment by yanas** [comment]
@filhocf Yes, Jibri is our official actively developed recording solution.
