### ISSUE TITLE
Android Error: Could not find method debugImplementation() for arguments

### ISSUE THREAD

**Issue by ugurrdemirel** [jitsi/jitsi-meet#6561]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I clone this repo to rebrand app with our company logos etc. I'm also react native developer but when I try open project with android studio (or npx react-native start) it gives me this error:

Build file '/Users/ugurdemirel/Desktop/jitsi-meet/android/sdk/build.gradle' line: 54
A problem occurred evaluating project ':sdk'.
> Could not find method debugImplementation() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

iOS versiyon working fine

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by ugurrdemirel** [comment]
Developers who got this issue change testImplementation, debugImplementation, ...Implementation etc. to testİmplementation. You just need to replace "I" to "İ"

My computer's language is set to turkish. After a little bit search I found this is a gradle bug. After replace I char to İ my problem solved

**Comment by ycdaskin** [comment]
> Developers who got this issue change testImplementation, debugImplementation, ...Implementation etc. to testİmplementation. You just need to replace "I" to "İ"
> 
> My computer's language is set to turkish. After a little bit search I found this is a gradle bug. After replace I char to İ my problem solved

Thank you very much. You saved my day.
