### ISSUE TITLE
PIP Mode UI issue

### ISSUE THREAD

**Issue by mukulm13** [jitsi/jitsi-meet#6562]
![Simulator Screen Shot - iPhone 11 - 2020-05-04 at 17 15 17](https://user-images.githubusercontent.com/64678623/80962771-4cb6ae80-8e2b-11ea-8ff9-f475c4d9cccf.png)

## Current behaviour
When iOS app switches to PIP mode, the controls UI get disturbed

## Expected Behaviour
When PIP mode is open the controls should be hidden or displayed in correct frame.

## Possible Solution
---

## Steps to reproduce
Step 1: Open the application
Step 2: Start the chat 
Step 3: Move to PIP mode 
Step 4: Observe the PIP UI

# Environment details
Using Pod version 2.6.1

**Comment by saghul** [comment]
What device ddid you test that on?

**Comment by mukulm13** [comment]
iPhone XS / iPhone 11 and even simulator

**Comment by saghul** [comment]
Thanks for the heads up!

**Comment by mukulm13** [comment]
@saghul  Is there a way to hide PIP button without customising the SDK?

**Comment by TBG-FR** [comment]
Disabling PIP using the feature flag `pip.enabled` does the work, but if you want to keep PIP and hide the button as the same time, I don't know.

**Comment by saghul** [comment]
>  Is there a way to hide PIP button without customising the SDK?

Yes, with the feature flag. It's disabled by default on iOS and auto-detected on Android.

**Comment by aartiaparekh** [comment]
@saghul You got any solution ?  When iOS app switches to PIP mode, back UI is black. I am stuck same flow and I want some help.

**Comment by saghul** [comment]
The back is your app, PiP won't show you the dashboard like on Android.

**Comment by aartiaparekh** [comment]
In ios when I open pip mode background is black. Please help for this. I am
stuck

**Comment by TBG-FR** [comment]
As said, this behaviour is normal, it's your responsability to display an app screen here. I think I managed to do so a while ago, that shouldn't be a big issue

**Comment by aartiaparekh** [comment]
@TBG-FR **Can you please help me?**
In ios when I open pip mode background is black, I already set my screen but still its black.
I can't solve and its urgent.

**Comment by amolgit** [comment]
I have solved this issues, refer my two classes and changes made by me. This is 100% working solution in iOS

1. First thing add it to window not to view
2. make the frame of the controller to width = 1 and height = 1
3. add the jitsi controller as child on the topmost controller
4. 


======== File: JitsiViewController=============
import UIKit
import JitsiMeetSDK

class JitsiViewController: UIViewController {
    
    @IBOutlet weak var videoButton: UIButton?
    
    //CHEAT
    fileprivate var pipViewCoordinator: PiPViewCoordinator?
    fileprivate var jitsiMeetView: JitsiMeetView?
    
    var eventSink:FlutterEventSink? = nil
    var roomName:String? = nil
    var serverUrl:URL? = nil
    var subject:String? = nil
    var audioOnly:Bool? = false
    var audioMuted: Bool? = false
    var videoMuted: Bool? = false
    var token:String? = nil
    var featureFlags: Dictionary<String, Any>? = Dictionary();
    var zoomButton: UIButton?
    
    
    var jistiMeetUserInfo = JitsiMeetUserInfo()
    
    override func loadView() {
        
        super.loadView()
    }
    
    @objc func openButtonClicked(sender : UIButton){
        
        //openJitsiMeetWithOptions();
    }
    
    @objc func closeButtonClicked(sender : UIButton){
        cleanUp();
        self.dismiss(animated: true, completion: nil)
    }
    
    override func viewDidLoad() {
        
        //print("VIEW DID LOAD")
        self.view.backgroundColor = .black
        
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        openJitsiMeet();
    }
    
    override func viewWillTransition(to size: CGSize,
                                     with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        let rect = CGRect(origin: CGPoint.zero, size: size)
        pipViewCoordinator?.resetBounds(bounds: rect)
        
        
    }
    
    func openJitsiMeet() {
        cleanUp()
        // create and configure jitsimeet view
        let jitsiMeetView = JitsiMeetView()
        
        
        jitsiMeetView.delegate = self
        self.jitsiMeetView = jitsiMeetView
        let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.welcomePageEnabled = true
            builder.room = self.roomName
            builder.serverURL = self.serverUrl
            builder.subject = self.subject
            builder.userInfo = self.jistiMeetUserInfo
            builder.audioOnly = self.audioOnly ?? false
            builder.audioMuted = self.audioMuted ?? false
            builder.videoMuted = self.videoMuted ?? false
            builder.token = self.token
            
            self.featureFlags?.forEach{ key,value in
                builder.setFeatureFlag(key, withValue: value);
            }
            
        }
        
        jitsiMeetView.join(options)
        
        // Enable jitsimeet view to be a view that can be displayed
        // on top of all the things, and let the coordinator to manage
        // the view state and interactions
        
        //Original
//        pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
//        pipViewCoordinator?.configureAsStickyView(withParentView: view)
        
        //New code by Amol
        pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
        pipViewCoordinator?.configureAsStickyView(withParentView: view.window)
        
        // animate in
        //jitsiMeetView.alpha = 0
        pipViewCoordinator?.show()
//as soon as start meet open in pip mode
        enterPicture(inPicture: [:])
    }
    
    func closeJitsiMeeting(){
        jitsiMeetView?.leave()
    }
    
    fileprivate func cleanUp() {
        jitsiMeetView?.removeFromSuperview()
        jitsiMeetView = nil
        pipViewCoordinator = nil
        //self.dismiss(animated: true, completion: nil)
    }
}

extension JitsiViewController: JitsiMeetViewDelegate {
    
    func conferenceWillJoin(_ data: [AnyHashable : Any]!) {
        //        print("CONFERENCE WILL JOIN")
        var mutatedData = data
        mutatedData?.updateValue("onConferenceWillJoin", forKey: "event")
        self.eventSink?(mutatedData)
    }
    
    func conferenceJoined(_ data: [AnyHashable : Any]!) {
        //        print("CONFERENCE JOINED")
        var mutatedData = data
        mutatedData?.updateValue("onConferenceJoined", forKey: "event")
        self.eventSink?(mutatedData)
    }
    
    func conferenceTerminated(_ data: [AnyHashable : Any]!) {
        //        print("CONFERENCE TERMINATED")
        var mutatedData = data
        mutatedData?.updateValue("onConferenceTerminated", forKey: "event")
        self.eventSink?(mutatedData)
        
        DispatchQueue.main.async {
            self.pipViewCoordinator?.hide() { _ in
                self.cleanUp()
                self.dismiss(animated: true, completion: nil)
                self.view.removeFromSuperview()
            }
        }
        
    }
    
    func enterPicture(inPicture data: [AnyHashable : Any]!) {
        self.view.frame = CGRect(x: 0, y: 0, width: 1, height: 1)

        var mutatedData = data
        mutatedData?.updateValue("onPictureInPictureWillEnter", forKey: "event")
        self.eventSink?(mutatedData)
        DispatchQueue.main.async {
            self.pipViewCoordinator?.enterPictureInPicture()
        }
        
                print("CONFERENCE PIP IN \(mutatedData)")

    }
    
    func exitPictureInPicture() {
        var mutatedData : [AnyHashable : Any]
        mutatedData = ["event":"onPictureInPictureTerminated"]
        self.eventSink?(mutatedData)
                print("CONFERENCE PIP OUT \(mutatedData)")

    }
}


============ File: SwiftJitsiMeetPlugin =========

import Flutter
import UIKit
import JitsiMeetSDK

extension UIApplication {

    class func getTopViewController(base: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {

        if let nav = base as? UINavigationController {
            return getTopViewController(base: nav.visibleViewController)

        } else if let tab = base as? UITabBarController, let selected = tab.selectedViewController {
            return getTopViewController(base: selected)

        } else if let presented = base?.presentedViewController {
            return getTopViewController(base: presented)
        }
        return base
    }
}

public class SwiftJitsiMeetPlugin: NSObject, FlutterPlugin, FlutterStreamHandler {
    var window: UIWindow?

    var uiVC : UIViewController

    var eventSink : FlutterEventSink?

    var jitsiViewController: JitsiViewController?

    init(uiViewController: UIViewController) {
        self.uiVC = uiViewController
    }

    public static func register(with registrar: FlutterPluginRegistrar) {
        let channel = FlutterMethodChannel(name: "jitsi_meet", binaryMessenger: registrar.messenger())

        let viewController: UIViewController =
            (UIApplication.shared.delegate?.window??.rootViewController)!

        let instance = SwiftJitsiMeetPlugin(uiViewController: viewController)

        registrar.addMethodCallDelegate(instance, channel: channel)

        // Set up event channel for conference events
        let eventChannelName = "jitsi_meet_events"

        let eventChannel = FlutterEventChannel(name: eventChannelName, binaryMessenger: registrar.messenger())
        eventChannel.setStreamHandler(instance)
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {

        if (call.method == "joinMeeting") {

            self.jitsiViewController = JitsiViewController.init()
            self.jitsiViewController?.eventSink = eventSink;
            // text = call.argument("text");

            guard let args = call.arguments else {
                return
            }

            if let myArgs = args as? [String: Any]
            {
                if let roomName = myArgs["room"] as? String {
                    if let serverURL = myArgs["serverURL"] as? String {
                        //                        print("serverUrl: ", serverURL);
                        self.jitsiViewController?.serverUrl = URL(string: serverURL);
                    }
                    let subject = myArgs["subject"] as? String
                    let displayName = myArgs["userDisplayName"] as? String
                    let email = myArgs["userEmail"] as? String
                    let token = myArgs["token"] as? String


                    self.jitsiViewController?.roomName = roomName;
                    self.jitsiViewController?.subject = subject;
                    self.jitsiViewController?.jistiMeetUserInfo.displayName = displayName;
                    self.jitsiViewController?.jistiMeetUserInfo.email = email;
                    self.jitsiViewController?.token = token;


                    if let avatarURL = myArgs["userAvatarURL"] as? String {
                        self.jitsiViewController?.jistiMeetUserInfo.avatar = URL(string: avatarURL);
                    }
                    //                    let avatar = myArgs["userAvatarURL"] as? String,
                    //                    let avatarURL  = URL(string: avatar)
                    //                    jitsiViewController?.jistiMeetUserInfo.avatar = avatarURL;

                    if let audioOnly = myArgs["audioOnly"] as? Int {
                        let audioOnlyBool = audioOnly > 0 ? true : false
                        self.jitsiViewController?.audioOnly = audioOnlyBool;
                    }

                    if let audioMuted = myArgs["audioMuted"] as? Int {
                        let audioMutedBool = audioMuted > 0 ? true : false
                        self.jitsiViewController?.audioMuted = audioMutedBool;
                    }

                    if let videoMuted = myArgs["videoMuted"] as? Int {
                        let videoMutedBool = videoMuted > 0 ? true : false
                        self.jitsiViewController?.videoMuted = videoMutedBool;
                    }

                    if let featureFlags = myArgs["featureFlags"] as? Dictionary<String, Any>
                    {
                        self.jitsiViewController?.featureFlags = featureFlags;
                    }

                } else {
                    result(FlutterError.init(code: "400", message: "room is null in arguments for method: (joinMeeting)", details: "room is null in arguments for method: (joinMeeting)"))
                }
            } else {
                result(FlutterError.init(code: "400", message: "arguments are null for method: (joinMeeting)", details: "arguments are null for method: (joinMeeting)"))
            }

            let navigationController = UINavigationController(rootViewController: (self.jitsiViewController)!)
            navigationController.setNavigationBarHidden(true, animated: false)
            navigationController.modalPresentationStyle = .fullScreen
            navigationController.navigationBar.barTintColor = UIColor.black
          //  self.uiVC.present(navigationController, animated: true) // amol comment this line
            
            
            //AMOL new code
            if let topVC = UIApplication.getTopViewController() {

                navigationController.modalPresentationStyle = .fullScreen

               topVC.addChild(navigationController)
                navigationController.view.frame = CGRect(x: 0, y: 0, width: topVC.view.frame.width, height: topVC.view.frame.height)
                topVC.view.addSubview(navigationController.view)
                navigationController.didMove(toParent: topVC)
            }
            
            result(nil)

        }else if (call.method == "closeMeeting") {


            var dictClosingServerInfo : Dictionary = Dictionary<AnyHashable,Any>()
            let serverURL : String = self.jitsiViewController?.serverUrl?.absoluteString ?? ""
            let roomName : String = self.jitsiViewController?.roomName ?? ""

            dictClosingServerInfo["url"] = "\(serverURL)/\(roomName)";

            self.jitsiViewController?.closeJitsiMeeting();
            self.jitsiViewController?.conferenceTerminated(dictClosingServerInfo);



        }

    }

    /**
     # FlutterStreamHandler methods
     */

    public func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
        eventSink = events
        return nil
    }

    public func onCancel(withArguments arguments: Any?) -> FlutterError? {
        eventSink = nil
        return nil
    }
}

**Comment by Telenutrition** [comment]
PIP is on window so it will be still visible on top.
Its up to you if you want to hide the PIP on back or on other controller. If you dont want when user press back you can simply remove it. But it will not automatically get removed.
