### ISSUE TITLE
[F/R] Allow for tables talk: multiple conversations where users can switch

### ISSUE THREAD

**Issue by 6ffm70** [jitsi/jitsi-meet#6564]
**Is your feature request related to a problem you are facing?**
Online meetings in the current style only allow for one topic to be discussed. I.e. it's a stage where only one person at a time presents, and one topic is discussed by participants.

To translate this into non-digital: online _video conference_ is a _panel session_
This feature request is for a **_dining table_**: people start talking in one open round, and then are able to sit together in smaller groups to have multiple conversations in the frame of one video conference. Everybody is able to leave and join between the groups that have found themselves in the _room_.

**Describe the solution you'd like**
- provisions to split a larger meeting "conference" into multiple smaller ones "groups" without losing sight of other groups that developed simultaneously
- provisions to give groups a topic/title or leave empty to allow for dynamic development of conversations
- provisions to peek into groups silently, but visible

**Describe alternatives you've considered**
Start new video conferences from an existing _panel session_ - disadvantage is losing sight of what happens with the rest of the original conference.

**Comment by 6ffm70** [comment]
related/overlapping issues
#4787 
#5550 
#5829

**Comment by joaoaguiam** [comment]
Hey @6ffm70, you could have a look on veertly: github.com/veertly/app
We are doing exactly that on top of jitsi. Anyone can create their event and the participants can create their own rooms, join and switch between rooms. Also, you can enter into a video-chat with anyone else in the event.
