### ISSUE TITLE
Android Default Camera

### ISSUE THREAD

**Issue by JoeyAndroidDev** [jitsi/jitsi-meet#6566]
Hi,

I'm using the jitsi-sdk in my Android App and I'm trying to use the back camera as default starting camera when the conference is launched.

I know the switchCamera methods in the library, but once the conference is launched, I can't change the Settings programmatically.

Maybe there is already a solution and I can't find it.

Thanks in Advance.

**Comment by saghul** [comment]
We don't currently have a settting for this, sorry.

**Comment by JoeyAndroidDev** [comment]
So there is no way to develop this setting by myself?

**Comment by saghul** [comment]
Sure there is, feel free to start tinkering! Alas I cannot help you at this time.

**Comment by JoeyAndroidDev** [comment]
Ok, just wanted to understand your answer correctly, thank you for the quick response.

**Comment by rananajam1** [comment]
@JoeyAndroidDev hey! did you find a solution for this?

**Comment by JoeyAndroidDev** [comment]
Hi,
yeah, but not in my Android Code. You have to checkout the whole project and customize the layout there.

**Comment by rananajam1** [comment]
@JoeyAndroidDev yeah I saw the Camera reducer and action. Need to know if im looking at the right direction?

**Comment by sdejonckheere** [comment]
@JoeyAndroidDev Did you go the build-it-yourself route? Do you happen to have the built library with alteration? I saw your post on StackOverflow aswell, im in the exact same situation, unfortunately I have no mac or knowledge on how to build Jitsi yourself.

**Comment by JoeyAndroidDev** [comment]
It was for a company feature so unfortunaly, I don't have the library to share. But I'm sure, you don't need mac. But the instructions from the answer in Stackoverflow are correct. Clone the jitsi-meet-sdk and change the code in CameraCaptureController.java
