### ISSUE TITLE
Add option to prevent system microphone volume change

### ISSUE THREAD

**Issue by fcorallini** [jitsi/jitsi-meet#6570]
Jiitsi Meet keep changing my system microphone volume and i can't set it manually
tested on chrome/chromium on ubuntu 18.04.

**Comment by btsimonh** [comment]
using the API, i THINK I did this....
maybe you can also do it from the URL?
maybe config,.disableAudioLevels=true

**Comment by Echolon** [comment]
@fcorallini have you tried the suggested steps?

**Comment by saghul** [comment]
That is just for measuring the remote audio levels, not the system volume.

In fact, we don’t change the volume because there is no API for it.

I think what you’re experiencing is the AGC. You can disable it by appending #config.disableAGC=true to the URL.
