### ISSUE TITLE
Deleting old Rooms in DesktopApp (Windows 10)

### ISSUE THREAD

**Issue by diemytree** [jitsi/jitsi-meet#6575]
**Is your feature request related to a problem you are facing?**
I want a way to delete wrong/old rooms i created

**Describe the solution you'd like**
A button or a way to right click and delete would be enough.

**Describe alternatives you've considered**
I heard reinstalling would work, but that's not really what I need and want.

**Comment by saghul** [comment]
Please open an issue on the electron app repo.
