### ISSUE TITLE
Not able to open app with deep-linking(Universal Links).

### ISSUE THREAD

**Issue by Rana-Mohit** [jitsi/jitsi-meet#6576]
Hi,
I am using "jitsi-meet-stable-jitsi-meet_4416" stable version with my server setup. Everything is working fine but deep-linking(Universal Linking) is not working for ios.

1- I have added my teamid and bundler in "apple-app-site-association" file.
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "teamid.org.jitsi.JitsiMeet.ios",
                "paths": [ "*" ]
            },
            {
                "appID": "teamid.com.atlassian.JitsiMeet.ios",
                "paths": [ "*" ]
            },
           {
                "appID": "my_teamid.com.my_projectbundler",
                "paths": [ "*" ]
            }
        ]
    }
}

2- Then added this file at the end of base url 
like - https://my.domain/apple-app-site-association

3- Enable association domain for my app from apple id.

4- Added domain in app.
like- applinks:my.domain

5 Added this in Appdelegate.m
jitsiMeet.customUrlScheme = @"org.jitsi.meet";
 jitsiMeet.customUrlScheme = @"https";
 jitsiMeet.universalLinkDomains = @[@"meet.jit.si", @"alpha.jitsi.net", @"beta.meet.jit.si", @"my.domain"];

6- I have also removed urlscheme- "org.jitsi.meet" from info.plist.

After all the above process when i want to open my ios app with my link it does not open.

Note -> link starts with https://    like - https://my.domain/invite=0123

Note -> For android deep-linking is working.

Don't know why it is not working, does I am missing something please help.

**Comment by saghul** [comment]
Have you checked the AASA file is properly accessible? I think it was also good to put it inside .well-known.

Also note that you may need to uninstall and reinstall the app for Apple to refresh that. It’s a bit of a mystery how that thing works.

**Comment by Rana-Mohit** [comment]
Yes it is accessible and i have also tested on aasa-validator.

[Screenshot 2020-05-05 at 1.16.50 PM.zip](https://github.com/jitsi/jitsi-meet/files/4579505/Screenshot.2020-05-05.at.1.16.50.PM.zip)
 please check this file.

**Comment by saghul** [comment]
Not in principle... I’ll take a look.

**Comment by luixxiul** [comment]
I think this should have been fixed with https://github.com/jitsi/jitsi-meet/pull/6795.
