### ISSUE TITLE
Adding option to log out of xmpp session

### ISSUE THREAD

**Issue by AliKarpuzoglu** [jitsi/jitsi-meet#6580]
**Is your feature request related to a problem you are facing?**
Yes, sometimes when opening, the app asks for a password. Sometimes it doesn't 
**Describe the solution you'd like**
I was thinking of an option in the settings menu that removes a password - but if I understand the code correctly, the password is not saved, but instead the session is stored? I couldn't really find a way to delete this session though. Could anyone give me a pointer, where I need to look? 

Do you think it's bad practice to just call
`window.localStorage.sessionId="" 
`
?

**Comment by nedimf** [comment]
I think, session ends when you hangup.

**Comment by AliKarpuzoglu** [comment]
the session does, but the sessionId (which if I understand right is used to authenticate on a server with password protection)  stays. So I tried to remove it. But when I do, the value still gets reset when I start the app again. Which is weird, because I don't think the value gets filled by the PersistenceRegistry

**Comment by AliKarpuzoglu** [comment]
ok, so my mistake was assuming sessionId was read into localstorage, but it's actually handled by /base/storage/native/Storage.js - I have disabled the getItem() for the key "sessionId" - now a password is required every time you join a session

**Comment by damencho** [comment]
https://community.jitsi.org/t/how-to-request-authentication-before-the-meeting-room-is-initialized/15625/19?u=damencho
There is jicofo setting to disable auto login.

**Comment by AliKarpuzoglu** [comment]
Great, thank you

**Comment by AliKarpuzoglu** [comment]
just in case anyone else sees this and wonders about the sessionId. When you remove the sessionId moderator features won't work. For example the option to mute all participants
