### ISSUE TITLE
RAM usage never goes down (in 4 GB VM)

### ISSUE THREAD

**Issue by pedro-nonfree** [jitsi/jitsi-meet#6589]
## Description
---

RAM usage is never freed in a VM with 4 GB of RAM and 2 cores

## Current behavior
---

RAM usage grows until OOM is reached (after that I have to manually do `service jitsi-videobridge2 restart`)

in this last one, the jvb has `Xmx` of `2048m`, but continues growing

![image](https://user-images.githubusercontent.com/39959198/81177172-87912180-8fa6-11ea-872c-081a4d7b777d.png)

process 423 is jicofo and 23862 is jvb

```
# pgrep java
423
23862
# cat /proc/423/oom_score
56
# cat /proc/23862/oom_score
602
```

## Expected Behavior
---

In this [discussion](https://community.jitsi.org/t/solved-looks-like-a-memory-leak/35876/2) @damencho  said to adjust RAM usage in jvb process

in `/usr/share/jitsi-videobridge/lib/videobridge.rc` I added `VIDEOBRIDGE_MAX_MEMORY=2048m`

I know from other people that a service with greater RAM resources, the RAM is freed

## Possible Solution
---

bad solution would be something like rebooting the machine everyday at 4:00 AM (when nobody uses the service)

## Steps to reproduce
---

- VM with 4 GB of RAM, 2 cores,
- jitsi-meet stable
- debian10
- coturn service in same machine but different IP
- put users to use it, in 3-4 days the RAM will be filled, and OOM happens

**Comment by damencho** [comment]
This is expected. Both jicofo and jvb are instructed to use up to 3GB of RAM, so 4 for both is not enough. There were discussions on the subject in the forum. Check it out.
There is a way to control the max used by jvb by using config file, but for jicofo you beed to edit the jicofo.sh file to change it, and make sure you update it on upgrade.

**Comment by pedro-nonfree** [comment]
Hi @damencho I suspect that you read it very fast

![image](https://user-images.githubusercontent.com/39959198/81179178-988f6200-8fa9-11ea-82a4-43f232937d64.png)

I already adjusted it to 2048, only videobridge, should I adjust it to 1024, jitsivideobridge **and jicofo** ??

thanks

**Comment by damencho** [comment]
Probably yeah. Make both 1024 https://github.com/jitsi/jicofo/blob/master/resources/jicofo.sh#L29

**Comment by pedro-nonfree** [comment]
with both 1024 looks very stable, thanks @damencho 

(it is difficult to see, but it frees some MB of RAM)

![image](https://user-images.githubusercontent.com/39959198/81499817-7a3da500-92ce-11ea-928c-03e0232cb3a6.png)
