### ISSUE TITLE
Don't enable camera and microphone at startup

### ISSUE THREAD

**Issue by piegamesde** [jitsi/jitsi-meet#6593]
**Is your feature request related to a problem you are facing?**
When joining a new meeting, microhpone and camera are enabled and active by default (if available). This has several issues:

- Devices with no camera always get an annoying "could not access camera" pop up on every meeting they join (takes two clicks to hide)
- Using the camera when not strictly needed is a waste of bandwidth. Users should activate it when they need, not the other way around.
- Privacy implications. I've had numerous conferences where I saw a user's web cam cover. They hadn't noticed their camera was active. Many people don't have a web cam cover though.

**Describe the solution you'd like**

Don't enable webcam and microphone by default when joining a new meeting.

**Describe alternatives you've considered**

Only applying this for the camera would already be a big improvement.

**Comment by damencho** [comment]
These configs are already available: 
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L97
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L136

**Comment by piegamesde** [comment]
Way too few instances use this configuration. The default option should be the other way around.

**Comment by saghul** [comment]
We have added a pre-join screen (it's on master, but not yet deployed to meet.jit.si) which allows you to select what devices you'd like to use (or mute them) before joining.

**Comment by piegamesde** [comment]
The pre-join screen does not solve the issue in all cases, please reopen. The pre-join screen is great, however it is only shown if someone manually enables that feature for the room. This is rarely the case and (by definition) never for the first one entering any room.

**Comment by pixelbrackets** [comment]
> These configs are already available:
> https://github.com/jitsi/jitsi-meet/blob/master/config.js#L97
> https://github.com/jitsi/jitsi-meet/blob/master/config.js#L136

Just a quick note since these links don't work anymore and the issue is a top search result:

https://github.com/jitsi/jitsi-meet/blob/4c635a2a634ede02b1d40c9b03cb15f2b2ed709f/config.js#L97 → `startWithAudioMuted` to `true`
https://github.com/jitsi/jitsi-meet/blob/4c635a2a634ede02b1d40c9b03cb15f2b2ed709f/config.js#L136 → `startWithVideoMuted` to `true`

**Comment by nekym** [comment]
There is a new problem. I set these variables to true, but the mic and camera are on by default. Seems that somebody ignore these properties. 

stable/jitsi-meet-5390

**Comment by 0xnor0** [comment]
> There is a new problem. I set these variables to true, but the mic and camera are on by default. Seems that somebody ignore these properties.
> 
> stable/jitsi-meet-5390

really?

**Comment by nekym** [comment]
> > There is a new problem. I set these variables to true, but the mic and camera are on by default. Seems that somebody ignore these properties.
> > stable/jitsi-meet-5390
> 
> really?

I have found the reason two days ago. 
It was the following code that stored some variables in the localStorage
```
/**
 * The default/initial redux state of the feature {@code base/settings}.
 *
 * @type Object
 */
const DEFAULT_STATE = {
    audioOutputDeviceId: undefined,
    avatarID: undefined,
    avatarURL: undefined,
    cameraDeviceId: undefined,
    disableCallIntegration: undefined,
    disableCrashReporting: undefined,
    disableP2P: undefined,
    displayName: undefined,
    email: undefined,
    localFlipX: true,
    micDeviceId: undefined,
    serverURL: undefined,
    startAudioOnly: false,
    startWithAudioMuted: true,
    startWithVideoMuted: true,
    userSelectedAudioOutputDeviceId: undefined,
    userSelectedCameraDeviceId: undefined,
    userSelectedMicDeviceId: undefined,
    userSelectedAudioOutputDeviceLabel: undefined,
    userSelectedCameraDeviceLabel: undefined,
    userSelectedMicDeviceLabel: undefined,
    userSelectedSkipPrejoin: undefined
};

const STORE_NAME = 'features/base/settings';

/**
 * Sets up the persistence of the feature {@code base/settings}.
 */
const filterSubtree = {};

// start with the default state
Object.keys(DEFAULT_STATE).forEach(key => {
    filterSubtree[key] = true;
});

// we want to filter these props, to not be stored as they represent
// what is currently opened/used as devices
filterSubtree.audioOutputDeviceId = false;
filterSubtree.cameraDeviceId = false;
filterSubtree.micDeviceId = false;

PersistenceRegistry.register(STORE_NAME, filterSubtree);
```
Some of participants had `startWithAudioMuted: false` and `startWithVideoMuted: false` in their local storage from an unknown time and it applies with more privileges than properties from config.js.

I removed lines with `startWithAudioMuted` and `startWithVideoMuted` from the `DEFAULT_STATE` and it started to work normally.
