### ISSUE TITLE
Room names with '/' on secured jitsi meet server

### ISSUE THREAD

**Issue by rolnas** [jitsi/jitsi-meet#6597]
## Description
---
A user tried to create a root with slash '/' symbol in the name. He is asked for a authentication, but after saying 'Connecting' he is asked again for a authentication.

## Current behavior
---
In log (jicofo.log) I found that user correctly authenticated. I found also some strange conference names created on server (as aaa@conference.bbb.$fqdn for aaa/bbb room). If I'm using aaabbb it works correctly. Also I found that URL contains '/' in it, but the conference name in dialogs is only the last member after '/'.
Strange in meet.jit.si it works, but it is not secured. Also it shows a conference name after last '/', but URL is containing full initial path name.

## Expected Behavior
---
I should be able create room with names like aaa/bbb.

## Possible Solution
---
Probably '/' should be filtered as '@' and ' ' (space) or behavior for secured installation corrected.

## Steps to reproduce
---
Try to create room with '/' in name for e.g. aaa/bbb on secured jitsi meet server.

# Environment details
---
Our local jitsi meet server installation on Debian 10 is from latest release version installed from official jitsi repository. The only important changes are for securing room creation and moving TURN UDP port to 443 (from 4446).

**Comment by rolnas** [comment]
I tested and it looks now it works. What commit was to solve this problem ?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/pull/4923/commits/e418ccf3b057ef8e7985e83039f5991a6cfd0046
