### ISSUE TITLE
[ios] Prevent an ios phone from going to sleep, while videoconferencing

### ISSUE THREAD

**Issue by Strykeros** [jitsi/jitsi-meet#6600]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

When I am watching a presentation on my ios, the device goes "half-sleep", when I am not tapping on my phone.

**Describe the solution you'd like**
Please describe the desired behavior.

I want it, so that the phone does not go into "half-sleep" mode.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
This sshould already be the case. How long does it take for the phone to go half-asleep? Do you happen to be in low bandwidth mode?

**Comment by Strykeros** [comment]
> This sshould already be the case. How long does it take for the phone to go half-asleep? Do you happen to be in low bandwidth mode?

It takes about 40 seconds. Also, It behaves the same whether I have turned on the low power mode or not. Also, how can I check if I am on low bandwith mode or not?

**Comment by Echolon** [comment]
no stale
