### ISSUE TITLE
Room password could be send as URL parameter

### ISSUE THREAD

**Issue by mzaman-19** [jitsi/jitsi-meet#6601]
I'm trying to create rooms using a set password could be send as URL parameter.
Please see bellow example for more details.
https://meet.sangoma.com/room1234#45678
How can I do this anyone help please.

Regards

**Comment by jespino** [comment]
I would like to give this a try.

**Comment by luixxiul** [comment]
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5902
