### ISSUE TITLE
Jitsi API: setTileView

### ISSUE THREAD

**Issue by guillaumepotier** [jitsi/jitsi-meet#6609]
Hi there,

Thanks for the great work on Jitsi. I'm curious to know why there is only a `toggleTileView` command in the API, and, AFAIK, no way to "force" an user to a specific mode. I mean, my Jitsi integration could be displayed in large (where the user could have the choice between TileView or FullView) but I also have a setup where it's in a kid of PIP (Picture in Picture) mode, where I'd really like to "force" the TileView for `false`.

It seems that currently I cannot do so, because either a) I'm unable to get the current view config in order to toggle it if needed b) have a `setTileView` command to force it or not.

Could you please indicate me on how to proceed to add a command to the API, and would you be interested to have me make a PR for that.

Thanks for your help

Best

**Comment by sretika** [comment]
I have a PR for a)

https://github.com/jitsi/jitsi-meet/pull/6764
