### ISSUE TITLE
How to limit number of user in Android

### ISSUE THREAD

**Issue by kksingla** [jitsi/jitsi-meet#6610]
implementation ('org.jitsi.react:jitsi-meet-sdk:2.5.1') { transitive = true }
Android version: 10

I'm using android SDK.

1. I want to limit the number of users can join the call and want to add auth, so the user needs to enter the password
2. Want to remove chat, share options
3. Can I change starting message connection you to your -> this message is incomplete
4. After call ended: music player app is not working...

```
class VideoCallActivity : BaseActivity() {
    override fun initVM() {

    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Initialize default options for Jitsi Meet conferences.
        val serverURL: URL
        serverURL = try {
            URL("https://meet.jit.si")
        } catch (e: MalformedURLException) {
            e.printStackTrace()
            throw RuntimeException("Invalid server URL!")
        }
        val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setServerURL(serverURL)
            .setWelcomePageEnabled(false)
            .setSubject("Subject")
            .setToken("123")
            .build()
        JitsiMeet.setDefaultConferenceOptions(defaultOptions)
        onButtonClick(null)
    }

    private fun onButtonClick(v: View?) {
        val text = "KK"
        if (text.isNotEmpty()) {
            // Build options object for joining the conference. The SDK will merge the default
            // one we set earlier and this one when joining.
            val options = JitsiMeetConferenceOptions.Builder()
                .setRoom(text)
                .build()

            // Launch the new activity with the given options. The launch() method takes care
            // of creating the required Intent and passing the options.
            JitsiMeetActivity.launch(this, options)
        }
    }
}
```

**Comment by kksingla** [comment]
@saghul please help me

**Comment by l3d00m** [comment]
Hi @kksingla,
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

---
*I'm not affliated with the Jitsi team, I'm a community contributor.*

**Comment by kksingla** [comment]
@l3d00m no one replying,  https://community.jitsi.org/t/i-want-to-create-a-video-call-app-for-medical-clinics/52894?u=kksingla

**Comment by luixxiul** [comment]
I would recommend you to rewrite your post there more clear way. It actually does not tell the community what you want to know, in order to achieve your object.

There is always a reason why nobody responds to a post. Try to communicate better way. Write in sentences, avoid items, etc.

**Comment by l3d00m** [comment]
@kksingla Also stop pinging people and commenting under unrelated issues, it'll just drive away people wanting to help. This is also not a support forum, as detailed already. Github is only for bugs and feature requests.
