### ISSUE TITLE
Why Jitsi Meet is bare bones?

### ISSUE THREAD

**Issue by Lostname777** [jitsi/jitsi-meet#6611]
When I use Jitsi Meet with my friends, anybody can kick other person, anybody can apply password and anybody can remove password and these is much more. I appreciate this but I guess you add an option for asking permission from the creator of the room or you should give this option only for the moderator. I know it can be possible on Matrix or 8x8 etc but I was just putting my point. If you like it or not I have no issue :)

**Comment by gtsop** [comment]
This is a delibarate choise on the public server (meet.jit.si). You can host your own instance of Jitsi Meet and change the configuration to allow only for the modarator to kick people (actually I think that's by default on a fresh installation)
