### ISSUE TITLE
Can't connect via API to a password protected meeting

### ISSUE THREAD

**Issue by AndyGHenderson** [jitsi/jitsi-meet#6614]
In order to programmatically have all users share the same password, I use the following:

meetAPI = new JitsiMeetExternalAPI("meet.jit.si", options);
meetAPI.executeCommand('displayName', userName);
meetAPI.addEventListener('videoConferenceJoined', SetPassword);
meetAPI.addEventListener('passwordRequired', SetPassword);
meetAPI.addEventListener('videoConferenceLeft', AllDone);

and

function SetPassword() {
  meetAPI.executeCommand('password', 'something');  
}

This worked fine earlier in the week. The first person in, set the password for the room via the videoConferenceJoined event. Subsequent joiners entered the room automatically without having to enter the password because it was supplied via the passwordRequired.

Today, the first person in sets the password OK. Subsequent joiners see the meeting room flash up then disappear.

In the console log for the failing session, I see:

app.bundle.min.js:126 2020-05-07T17:43:58.283Z [conference.js] <ee._onConferenceFailed>:  CONFERENCE FAILED: conference.passwordRequired
app.bundle.min.js:126 2020-05-07T17:43:58.294Z [features/base/connection] conference.passwordRequired

I read that as saying that the password I supplied is blank, but it definitely isn't. I can see by debugging it's setting it correctly. I don't use any fancy characters.

I thought it might be a timing issue, but delaying the addEventListeners by a second. Removing them altogether allowed both parties to join.

I've seen this behaviour in Windows 10 (Chrome and Edge-Chrome), Android Chrome and IOS.

I hope you can help,

Andy

**Comment by AndyGHenderson** [comment]
I've done some more testing and it turns out that I can no longer connect to any meeting via the API once a password has been set. It doesn't matter whether the password is set via executeCommand 'password' or manually through the UI. As soon as there's a password on the meeting, any attempt to connect to the meeting using the API fails without the joining person being asked for a password.

If I start the meeting via the API and then set a password manually or via the videoConferenceJoined event, I can join the meeting via a meet.jit.si URL and I get challenged to enter the meeting's password. After I enter the password, the meeting goes OK.

If I do it the other way around, set up the meeting via a meet.jit.si URL and enter a password, I can never connect to that meeting via an API.

If I use the API to set up a meeting without a password, I can join it via the API. If I then add a password, I see the notification in the other window, but the meeting continues. If I then try to join a third person to the meeting via the API it fails like before. 

Andy

**Comment by pierrealixt** [comment]
I experience the same issue. Unable to enter the password through the Jitsi API.
Using the meet.jit.si URL, I can enter a password.

**Comment by fernandolimati** [comment]
```
api = new JitsiMeetExternalAPI(domain, options);
var pass = "pass";

setTimeout(() => {
// why timeout: I got some trouble calling event listeners without setting a timeout :)

    // when local user is trying to enter in a locked room 
    api.addEventListener('passwordRequired', () => {
        api.executeCommand('password', yourRoomPass);
    });

    // when local user has joined the video conference 
    api.addEventListener('videoConferenceJoined', (response) => {
        api.executeCommand('password', yourRoomPass);
    });

}, 10);
```

**Comment by AndyGHenderson** [comment]
As mentioned above, I tried adding a timeout, but that didn't help. Note that the issue occurs even if there aren't any event listeners - instead of showing a password challenge, the connection fails.

Andy

**Comment by AndyGHenderson** [comment]
I've managed to solve my own problem - sort of.

I had set a handler for the videoConferenceLeft event which did some cleanup including a dispose().

Turns out this event fires during the joining process. Presumably the API joins the conference, sees there's a password set, leaves the conference (firing the event), then asks for a password. In my case, dispose() got called and that was the end of that.

To solve the problem I added a 15 second delay to adding the handler for the videoConferenceLeft event (5 seconds wasn't enough using a decent laptop and fibre internet connection). But that's obviously arbitrary and someone quickly clicking the 'Leave' button won't execute the cleanup code. Someone with a slower device/connection might take longer than 15 seconds.

Anyone any better suggestions?

Long term, it would obviously be better if the API didn't join a password-protected conference until a password is provided via the UI or passwordRequired event. I'm hoping that's a simple fix.

Andy

**Comment by N3zTho** [comment]
You can use this
api.addEventListener(“passwordRequired”, () => {
api.executeCommand(“password”, password);
});

**Comment by AndyGHenderson** [comment]
Sure, but that doesn't solve the issue. I pinned the problem down to the videoConferenceLeft event firing while **connecting** to a conference (it seems the API joins the conference, sees a password is needed, leaves the conference, fires videoConferenceLeft, fires passwordRequired).

I called dispose on the videoConferenceLeft event that stopped everything dead. I now delay for several seconds after joining before setting a handler for videoConferenceLeft but that's a kludge.

**Comment by LeoLP1** [comment]
Sorry if I reopen, but someone has found another solution for the problem that "passwordRequired" that trigger "videoConferenceJoined" ?

**Comment by kennylee2008** [comment]
To some extent, I solved this problem. But I don't think it's the best solution. My solution is here, If anyone is experiencing the same problem, you can refer to it.

1.  On _passwordRequired_ event, set a flag variable:
`
api.addEventListener("passwordRequired", function (event) {
       window.passwordRequired = true;
});
`
2. On _videoConferenceLeft_ event, ignore the event when passwordRequired:
`
api.addListener("videoConferenceLeft", function (event) {
    //if passwordRequired, ignore videoConferenceLeft event
    if (window.passwordRequired) {
      window.passwordRequired = false;
      return;
    }

    //otherwise, do normal dispose job
    api.dispose();
    api = undefined;
});
`
