### ISSUE TITLE
"Blur my Background" kills the video

### ISSUE THREAD

**Issue by randolfjorberg** [jitsi/jitsi-meet#6620]
Once I activated "Blur my Background" the camera acted up and I was only able to get this picture, but no sound even on reload of Chrome (on Windows 10). Only when I deactivated the blur option and reloaded again did picture and sound return.

![image](https://user-images.githubusercontent.com/64866719/81346432-8e10bd80-90ba-11ea-9eb6-035b90223fd3.png)

**Comment by mwarnaar** [comment]
Do you have hardware acceleration enabled in chrome://settings?

**Comment by amalgjose** [comment]
I have also faced similar issue.

**Comment by Echolon** [comment]
I will close this as duplicate with reference to #5836.
Anyway, thanks for reporting!
