### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by t104360088** [jitsi/jitsi-meet#6622]
## Description
I got this error
No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)

## Current behavior
When I use android phone to enter room, I crash and got error, but iphone do not crash

**Comment by saghul** [comment]
Try adding this to your gradle.properties file: `android.enableDexingArtifactTransform.desugaring=false`

**Comment by khyatiChitroda** [comment]
still getting same problem after adding that into Gradle.properties

**Comment by saghul** [comment]
What gradle plugin version are you using?

**Comment by khyatiChitroda** [comment]
implementation ('org.jitsi.react:jitsi-meet-sdk:2.5.1') { transitive = true }

**Comment by saghul** [comment]
That'ss the SDK version, which I urge you to update to 2.8.X, I mean the gradle plugin version.

**Comment by khyatiChitroda** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip


 implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.+') { transitive = true }

**Comment by KCNS-2** [comment]
Hello,

The same issue for me as well.
**Working as expected 👍** 
I am used implementation ('org.jitsi.react:jitsi-meet-sdk:2.5.1') { transitive = true }

**Not working as expected :**
I can able to build the sdk from local source code successfully and in my local system it was generated 2.8.0 jitsi meet sdk . 

Used the generated SDK, at that time , I am getting error as like this

No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)

Please help me to solve this.

**Comment by saghul** [comment]
@KCNS-2 have you tried this? https://github.com/jitsi/jitsi-meet/issues/6622#issuecomment-626537457

**Comment by KCNS-2** [comment]
@saghul  thanks for your reply.

Ya I tried that
**My gradle.properties:**

android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
android.useAndroidX=true

android.enableDexingArtifactTransform.desugaring=false

**Comment by saghul** [comment]
What gradle plugin version are you using?

**Comment by KCNS-2** [comment]
**My gradle-wrapper.properties**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

**build.gradle (project)**

```

buildscript {
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}


allprojects {
    repositories {
        maven {
            url "E:\\a2020\\tmp\\newtmp"
        }
        google()
        jcenter()
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
**build.gradle(Module)**

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    // Jitsi Meet
    implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.+') { transitive = true }
//    implementation ('org.jitsi.react:jitsi-meet-sdk:2.5.1') { transitive = true }
}

```

**Comment by KCNS-2** [comment]
Solved by changing maven url path 

```
maven {
            url "E:/a2020/tmp/newtmp"
        }
```

**Comment by saghul** [comment]
Ah, you are using windows! That's an important detail.

**Comment by t104360088** [comment]
Hi @saghul 
I don’t know why jitsi is normal sometimes, sometimes not 
I already add this line **android.enableDexingArtifactTransform.desugaring=false**

This is my build.gradle(Project)

```
buildscript {
    ext.kotlin_version = '1.3.31'
    repositories {
        mavenCentral()
        google()
        jcenter()

        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.28.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()

        maven {
            url 'https://maven.google.com/'
        }

        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Module
`implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }`

gradle.properties
```
# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
# Jitsi WebRTC need it
android.enableDexingArtifactTransform.desugaring=false
```

**Comment by saghul** [comment]
Yes, that option is needed when using the Gradle plugin > 3.5 or 3.6.

**Comment by t104360088** [comment]
@saghul Ok, But I have the same issue about this line sometime

No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals()

**Comment by saghul** [comment]
Downgrading the Gradle plugin is the only solution I know.
