### ISSUE TITLE
Does JWT token authentication works with websocket connections?

### ISSUE THREAD

**Issue by onlyyjc** [jitsi/jitsi-meet#6623]
Does JWT token authentication works with websocket connections?

**Comment by damencho** [comment]
Yes it does. You just make sure you have this event in your prosody:
https://hg.prosody.im/trunk/file/default/plugins/mod_websocket.lua#l299
It will be part of prosody 0.11.6 I think ... 

Please use the community forum when you have questions before opening new issues.
