### ISSUE TITLE
Bad utilisation of viewport in tile view

### ISSUE THREAD

**Issue by phu9Suop** [jitsi/jitsi-meet#6626]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
Large borders inside conference window in tile view are showing only background and logo instead of using surface for tiled channel displays.

**Describe the solution you'd like**
Please describe the desired behavior.
I would like Jitsi to aquire the actual view port dimensions of the window and utilise them to min 90% instead of 50% sizes for the tiles

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Is this a server or a client side non-feature , shall surely be on the client side.
Alternative have client drag borders of tile viewport to his liking and capacity with mouse or pointer
BR

**Comment by phu9Suop** [comment]
![5 -dig -Stammtisch_pixd](https://user-images.githubusercontent.com/37701817/81474623-0be1df80-9207-11ea-8915-f930028ad636.jpg)
![Bildschirmfoto zu 2020-05-05 21-39-09](https://user-images.githubusercontent.com/37701817/81474629-156b4780-9207-11ea-8448-00019f49a0d9.png)
attached are 2 different views in the same conference

**Comment by phu9Suop** [comment]
this was an error to close

**Comment by l3d00m** [comment]
See #5141
