### ISSUE TITLE
Host password requires page refresh to allow entry. latest src build

### ISSUE THREAD

**Issue by Mista-P** [jitsi/jitsi-meet#6629]
When entering a new room, the room prompts for host password. The correct password is entered but the room still prompts for the host password until you hit browser refresh then room allows entry.

**Comment by Mista-P** [comment]
If you stumble across this issue check your prosody certs +  password for user focus.

**Comment by shubhamalive** [comment]
@Mista-P Can you explain that? I am facing the same issue after setting a password for meetings more to it, meetings can't be joined after the password is setup.
