### ISSUE TITLE
Share conference link with join intent

### ISSUE THREAD

**Issue by allo-** [jitsi/jitsi-meet#6631]
**Is your feature request related to a problem you are facing?**
When sharing a conference link to android users, they have to visit a website and then click a button to open their app again. When I know that they have the app, I would like to be able to send a "join" link that opens the app.

**Describe the solution you'd like**
Implement a new share message:

"You're invited to a jitsi meet conference XY. If you have the android app click here intent://open-in-jitsi-meet/myserver/myconference. If you do not using android or do not have the app installed yet, click here: https://myserver/myconference"

**Describe alternatives you've considered**
The alternative is the current flow, that can be improved by adding the android intent link.

**Comment by saghul** [comment]
Then we'd need another link with the iOS depp linking link. I think that's too much for the sake of saving one click.

I'm keeeping this open so others can chime in though.

**Comment by allo-** [comment]
This would be a feature of the Android app, it does not have to be included in the iOS app or mobile web itself, when it is not possible there.

But when iOS allows for similar links, there would be an even better option: Create a redirect in the web interface that redirects users from "https://my.jitsi/direct-to-app" to "intent://android-app" or "iOS-intent://iOS-app" using user-agent sniffing.

Then the resulting message would be: "You are invited to conference X, if you already have the Jitsi Meet app click here https://my.jitsi/direct-to-app/room if you need the app or want to join with your browser click here: https://my.jitsi/room"

**Comment by saghul** [comment]
I like the redirect idea!

**Comment by allo-** [comment]
bump
