### ISSUE TITLE
Project hygiene (js tests, node version, package vulnerabilities)

### ISSUE THREAD

**Issue by gtsop** [jitsi/jitsi-meet#6641]
Coming into this with great respect and gratitude towards everyone who has contributed to this project.

In the interest of the longevity and security of this project, I'd like to ask what is the plan for keeping this codebase in good hygiene. The reason I am concerned about it is because of the following three:
- The recommended node version is >= 10, however we are currently at the final year or support for this version, so the project needs to move to node 12 during that period
- Installing the project shows quite a lot of vulnerabilities:
`found 5216 vulnerabilities (2832 low, 6 moderate, 2376 high, 2 critical)`
- I can't locate any tests for the front-end, which would provide some level of confedence when upgrading node, packages and for generally making sure bugs are cought early. (I saw this directory https://github.com/jitsi/jitsi-meet/tree/6121e9fc65340470b6c412a1e4dc6386ed3ba186/react/features/base/testing/components but I'm not entierly sure what it's about. Also it hasn't been updated recently).

**Is your feature request related to a problem you are facing?**
No, not yet.

**Describe the solution you'd like**
There can be a graduall increase in project hygiene by gothering metrics and making sure these are visible. Visibility is always the first step. Then, we could have a strategy for automated tests and allow the contributors to test their features. Then, there could be a CI task to run the tests and provide feedback on Pull Requests to make sure existing funtionallity isn't broken.

This isn't something that can be done in a short amount of time, but the direction needs to be there, and people will follow.

Please let me know what the Jitsi team thinks of this. Also, I am glad to contribute myself.

**Comment by damencho** [comment]
You can take a look at the integration tests https://github.com/jitsi/jitsi-meet-torture

**Comment by gtsop** [comment]
> You can take a look at the integration tests https://github.com/jitsi/jitsi-meet-torture

Sorry, I should have made it clear. I meant just front end tests, as in javascript unit/component/integration/e2e tests, with mocha, enzyme, cypress and things like that. Tests you run as you modify the front-end code, to make sure you didn't brake anything

**Comment by damencho** [comment]
We are trying (not that we are succeeding lately) to have integration tests for the new features that test the UI, which cover those, and that is the purpose of the torture project and we run those tests one the PR is created. We have unit test on some critical pieces like some parsing in the lib-jitsi-meet.

**Comment by saghul** [comment]
>     * The recommended node version is >= 10, however we are currently at the final year or support for this version, so the project needs to move to node 12 during that period

Node 12 works just fine, there is no moveing necessary, all we need is to update the docs, so thanks for the reminder!

**Comment by luixxiul** [comment]
````
sudo npm install npm-check-updates -g
cd ~/jitsi-meet
ncu -u -m
npm install
npm audit
````

(the flag `-m` means: `do not upgrade newer versions that are already satisfied by the version range according to semver`)

This fixes all high severity vulnerabilities and leaves "only" 1290 low severity ones, still it breaks a lot of stuff, obviously:

![Clipboard01](https://user-images.githubusercontent.com/3362943/82436666-b965b600-9a85-11ea-93fa-41356457692b.png)

![Clipboard02](https://user-images.githubusercontent.com/3362943/82437167-84a62e80-9a86-11ea-98fc-6e25aa1470ee.png)

**Comment by saghul** [comment]
I have a more conservative open PR which just fixes the depss witrh npm audit, but some torture tests are failing, and for the life of me I can't figure out why.

**Comment by luixxiul** [comment]
> I have a more conservative open PR which just fixes the depss witrh npm audit

I totally agree with you; I should have mentioned that my intention above was to show how difficult, risky, and dangerous it would be to update so many packages all together 😉

**Comment by saghul** [comment]
Ah, no worries, I was just trying to point out that we are on it :-)

**Comment by gtsop** [comment]
> I have a more conservative open PR which just fixes the depss witrh npm audit, but some torture tests are failing, and for the life of me I can't figure out why.

Can you link to that PR? If it's a front-end issue I could help.

**Comment by luixxiul** [comment]
Here is the link I think you would be looking for: https://github.com/jitsi/jitsi-meet/pulls?q=is%3Aopen+label%3Adependencies+is%3Apr
