### ISSUE TITLE
Shared link does not join the meeting directly

### ISSUE THREAD

**Issue by gungorhafize** [jitsi/jitsi-meet#6646]
I'm using jitsi sdk, when I shared link for invite someone to my ongoing meeting, the user that invited does not join meeting directly. It redirects to login menu ( conference name entering)

Here is my intent filters configurations: 

`   
   <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:host="meet.mymeet.com.tr:5741" android:scheme="https" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:scheme="net.jitsi.mymeet" />
            </intent-filter>`

**Comment by saghul** [comment]
How does the intent link look like?

**Comment by gungorhafize** [comment]
> Jitsi Meet Join a WebRTC video conference powered by the Jitsi Videobridge 
> meet.mymeet.com.tr

https://meet.mymeet.com.tr:5741/.testmeeting

**Comment by saghul** [comment]
Did you set the default server URL in JitsiMeetConferenceOptions?

**Comment by gungorhafize** [comment]
here is my main activity URL section
        URL serverURL;
        try {
          serverURL = new URL("https://meet.mymeet.com.tr:5741");


        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions defaultOptions
            = new JitsiMeetConferenceOptions.Builder()
                .setWelcomePageEnabled(false)
                .setServerURL(serverURL)
                .setFeatureFlag("call-integration.enabled", false)
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);



        
    }



    public void onButoonClick(View v) {
        EditText editText = findViewById(R.id.conferenceName);
        String text = editText.getText().toString();

        if (text.length() > 0) {

            JitsiMeetConferenceOptions options
                = new JitsiMeetConferenceOptions.Builder()
                    .setRoom(text)
                    .build();
            JitsiMeetActivity.launch(this, options);
            finishAffinity();
        }
    }

**Comment by saghul** [comment]
Ah I see. You need to handle onNewIntent yourself on the main activity and then do a JitsiMeetActivity.launch with the URL.

**Comment by gungorhafize** [comment]
so how can i do that? adding this to my main activity?

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        JitsiMeetConferenceOptions options;

        if ((options = getConferenceOptions(intent)) != null) {
            join(options);
            return;
        }

        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

**Comment by gungorhafize** [comment]
@Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        JitsiMeetActivity.launch((android.content.Context) Context,"https://meet.mymeet.com.tr:5741");
    }

Is that correct usage? @saghul

**Comment by gungorhafize** [comment]
Can you please add these (onNewIntent usege and JitsiMeetActivity.launch usage) to Main Activity sdk ? I couldn't reach the result @saghul

**Comment by gungorhafize** [comment]
```
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        Uri uri = intent.getData();
        if (uri != null) {
            JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                    .setRoom(uri.toString()).build();
            JitsiMeetActivity.launch(this, options);
            finishAffinity();
        }
    }
```

Hi my friend @saghul , can you please tell me what's wrong here ?

**Comment by saghul** [comment]
You don’t see the Jitsi Meet activity launching?

**Comment by gungorhafize** [comment]
onNewIntent method not working although launch mode of activity is singleTop

**Comment by saghul** [comment]
Can you please the full code for your MainActivity?

**Comment by gungorhafize** [comment]
`package net.jitsi.mymeet;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import androidx.appcompat.app.AppCompatActivity;
import androidx.viewpager.widget.ViewPager;

import com.tbuonomo.viewpagerdotsindicator.SpringDotsIndicator;

import org.jitsi.meet.sdk.JitsiMeet;
import org.jitsi.meet.sdk.JitsiMeetActivity;
import org.jitsi.meet.sdk.JitsiMeetConferenceOptions;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    ViewPager viewPager;
    SpringDotsIndicator dot;
    Adapter adapter;
    List<Model> models;
    

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        getSupportActionBar().hide();

        models = new ArrayList<>();
        models.add(new Model(R.drawable.ic_n1, getResources().getString(R.string.startmeet), getResources().getString(R.string.startdesc)));
        models.add(new Model(R.drawable.ic_n2, getResources().getString(R.string.sharecontent), getResources().getString(R.string.sharedesc)));


        adapter = new Adapter(models ,this);
        viewPager = findViewById(R.id.viewPager);
        viewPager.setAdapter(adapter);
        dot = findViewById(R.id.dot);
        dot.setViewPager(viewPager);



        URL serverURL;
        try {
          serverURL = new URL("https://meet.mymeet.com.tr:5741");


        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions defaultOptions
            = new JitsiMeetConferenceOptions.Builder()
                .setWelcomePageEnabled(false)
                .setServerURL(serverURL)
                .setFeatureFlag("call-integration.enabled", false)
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);

        
    }


    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        String action = intent.getAction();

        finishAffinity();

        if (Intent.ACTION_VIEW.equals(action)) {
        Uri uri = intent.getData();
        if (uri != null) {
            JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                    .setRoom(uri.toString()).build();
            JitsiMeetActivity.launch(this, options);
            finishAffinity();
        }
        }

    }


    public void onButoonClick(View v) {
        EditText editText = findViewById(R.id.conferenceName);
        String text = editText.getText().toString();

        if (text.length() > 0) {

            JitsiMeetConferenceOptions options
                = new JitsiMeetConferenceOptions.Builder()
                    .setRoom(text)
                    .build();
            JitsiMeetActivity.launch(this, options);
            finishAffinity();
        }
    }

}

`

**Comment by gungorhafize** [comment]
it remains only on the login screen but i want to join ongoing meeting directly with shared link here is also my Manifest.xml file
` 
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.jitsi.mymeet">

    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_meet"
        android:label="@string/app_name"
        android:roundIcon="@drawable/ic_meet"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name="net.jitsi.mymeet.MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize"
            android:label="@string/app_name"
            android:launchMode="singleTop"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"  android:host="meet.mymeet.com.tr:5741" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="net.jitsi.mymeet" />
            </intent-filter>

        </activity>

    </application>

</manifest>
`

**Comment by saghul** [comment]
I wonder if the port in here `<data android:scheme="https"  android:host="meet.mymeet.com.tr:5741" />` confuses the thing.

Otherwise it looks ok to me...

**Comment by gungorhafize** [comment]
onNewIntent method is not working... is it looks ok as well?

btw port 8443 :/

**Comment by saghul** [comment]
Can you try using singleTask instead of singleTop ?

**Comment by gungorhafize** [comment]
I've try but nothing changed, it still on login screen not join the meeting :/

**Comment by gungorhafize** [comment]
This issue is about communicating between running activities! Thanks for your replies best regards!
