### ISSUE TITLE
Makefile race condition

### ISSUE THREAD

**Issue by Rouji** [jitsi/jitsi-meet#6647]
## Description
The Makefile assumes that prerequisites are run in the order they're listed. Specifically that `deploy-init` is run before everything else. This only happens to be the case with `make -j1` and even then isn't actually guaranteed.

If you try to `make -j` or `-jX` with X>1 (I've got MAKEFLAGS="j\`nproc\`" in my .profile), it'll try to copy things into the `BUILD_DIR`, before it has been (re)created and funky stuff like that.

```
make -j
./node_modules/.bin/webpack -p
rm -fr libs
cp \
        build/app.bundle.min.js \
        build/app.bundle.min.map \
        build/do_external_connect.min.js \
        build/do_external_connect.min.map \
        build/external_api.min.js \
        build/external_api.min.map \
        build/flacEncodeWorker.min.js \
        build/flacEncodeWorker.min.map \
        build/device_selection_popup_bundle.min.js \
        build/device_selection_popup_bundle.min.map \
        build/dial_in_info_bundle.min.js \
        build/dial_in_info_bundle.min.map \
        build/alwaysontop.min.js \
        build/alwaysontop.min.map \
        ./analytics-ga.js \
        build/analytics-ga.min.js \
        build/analytics-ga.min.map \
        build/video-blur-effect.min.js \
        build/video-blur-effect.min.map \
        build/rnnoise-processor.min.js \
        build/rnnoise-processor.min.map \
        libs
mkdir -p libs
cp: target 'libs' is not a directory
make: *** [Makefile:33: deploy-appbundle] Error 1
make: *** Waiting for unfinished jobs....
^Cmake: *** [Makefile:19: compile] Interrupt
```

## Current behavior
You can only `make` using `-j1`, otherwise it fails.

## Expected Behavior
`make -j` also working.

## Possible Solution
Fix the targets' prerequisites.

## Steps to reproduce
Run `make -j`

# Environment details
GNU Make 4.3

**Comment by saghul** [comment]
Can you try this patch?

```
diff --git a/Makefile b/Makefile
index 0cb668e53..cf671886c 100644
--- a/Makefile
+++ b/Makefile
@@ -13,6 +13,7 @@ STYLES_MAIN = css/main.scss
 WEBPACK = ./node_modules/.bin/webpack
 WEBPACK_DEV_SERVER = ./node_modules/.bin/webpack-dev-server
 
+.NOTPARALLEL:
 all: compile deploy clean
 
 compile:

```

**Comment by Rouji** [comment]
Yes that does "fix" it. But you'd want to stick that to the `deploy` and `dev` targets, not `all`. Otherwise those still fail if run seperately.  
Pretty much a bodge-fix though, tbh.

Side note/rant: This really is more of a glorified shell script than a Makefile and doesn't make use of what makes Makefiles useful. i.e. only (re)doing stuff if something's actually changed, if you define your dependencies properly. This issue is also a symptom of that. Could do with a make-over (ha ha), imo.

**Comment by saghul** [comment]
Yeah, we use it as a glorified bash script, oh well. Fix is in https://github.com/jitsi/jitsi-meet/pull/6701
