### ISSUE TITLE
Jitsi bridge is unavailable using random port 

### ISSUE THREAD

**Issue by breebee** [jitsi/jitsi-meet#665]
I put the nginx configuration to listen to port 444, and i added the port to the bosh http bind in the *.com-config.js leaving the nginx bosh to the default 5237 or whatever. Any help on the issue is greatly appreciated.

**Comment by bgrozev** [comment]
Please describe what the problem is and what your modifications are in more detail, and preferably on the mailing list.

**Comment by breebee** [comment]
Ok so i install the package in the terminal, used my own ssl and just altered the listening port on the nginx file from the regular 443 to 444 so that not all subdomains get binded to a conference on the site. The only other modification i made was add :444 in the bosh in .com-config.js from domain.com/http-bind to domain:444/http-bind which makes the conference connect the users without errors for the focus and they can share youtube videos but the video bridge says its unavailable. Inside the nginx configuration the bosh is different however so i left it alone, it is localhost:5237/http-bind i think. Is there anything else i need to configure to resolve this or should it work like this, because i am almost certain it was working at first and the video bridge started failing after a couple days.

**Comment by bgrozev** [comment]
> Is there anything else i need to configure to resolve this or should it work like this

It should work like this, unless I am missing something. Check the logs in the client, jicofo and bridge.

**Comment by breebee** [comment]
it seems the jvb.log is constantly sending this error

JVB 2016-06-01 16:11:31.283 INFO: [275] org.jitsi.videobridge.xmpp.ComponentImpl.info() RECV: <iq id="BugyM-69343" type="result" to="jitsi-videobridge.domain.com" from="domain.com"/>

**Comment by breebee** [comment]
The video bridge log is just getting bigger and bigger without anyone using a conference room spamming that error "BugyM-69343". Any suggestions?

**Comment by breebee** [comment]
Problem resolved. I tried rebooting the server but nothing, then i tried "/etc/init.d/jitsi-videobridge
restart" and it worked perfect if anyone is stuck here in the future.
