### ISSUE TITLE
Problem with FeatureFlag

### ISSUE THREAD

**Issue by nicolas-bofi** [jitsi/jitsi-meet#6650]
Hello, 

I'm trying to use the function "setFeatureFlag" on Android SDK but it not work. All functionalities are always available for the user.

Here is a part of my code : 

JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(VISIO_SERVER)
                .setAudioOnly(true)
                .setRoom(VISIO_URL_KEY)
                .setUserInfo(connectUser)
                .setFeatureFlag("add-people.enabled",false)
                .setFeatureFlag("calendar.enabled",false)
                .setFeatureFlag("close-captions.enabled",false)
                .setFeatureFlag("chat.enabled",false)
                .setFeatureFlag("invite.enabled",false)
                .setFeatureFlag("live-streaming.enabled",false)
                .setFeatureFlag("meeting-name.enabled", false)
                .setFeatureFlag("meeting-password.enabled",false)
                .setFeatureFlag("recording.enabled",false)
                .build();

        view.join(options);
        setContentView(view);

**Comment by saghul** [comment]
What SSDK version are you using?

**Comment by nicolas-bofi** [comment]
2.8.0

**Comment by saghul** [comment]
Most of those flags were released in 2.8.2.

**Comment by nicolas-bofi** [comment]
Ok, thanks !

**Comment by dev-Arif** [comment]
> Most of those flags were released in 2.8.2.

2.8.2 is not yet available for iOS. FeatureFlags are not working in 2.8.1. I need to enable/disable the tiles view based on the requirements. 
How soon do we expect the new release for iOS?

**Comment by nicolas-bofi** [comment]
I do it on iOS and it work.

**Comment by dev-Arif** [comment]
> I do it on iOS and it work.

can you share the code how you do it?
Here is how I am doing:
`JitsiMeetConferenceOptions *options
        = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
            builder.room = self.room;
            builder.audioMuted = true;
            [builder setFeatureFlag:@"tile-view.enabled" withBoolean:true];
        }];
    [jitsiView join:options];`

**Comment by saghul** [comment]
tile-view.enabled is not yet released.

**Comment by dev-Arif** [comment]
> tile-view.enabled is not yet released.
How soon do we expect this to be released? I desperately need this feature please.

**Comment by Akshay8750** [comment]
I'm using SDK version 2.8.2. but it still not working

URL serverURL = new URL("https://meet.jit.si");
                        JitsiMeetConferenceOptions.Builder builder = new JitsiMeetConferenceOptions.Builder();
                        builder.setServerURL(serverURL);
                        builder.setFeatureFlag("invite.enabled", false);
                        builder.setWelcomePageEnabled(false);
                        builder.setRoom(meetingRoom);

**Comment by saghul** [comment]
Please update to version 2.11
