### ISSUE TITLE
Android App says "connection lost" when Javascript is used in config

### ISSUE THREAD

**Issue by inducer** [jitsi/jitsi-meet#6658]
I teach at a university, and I use a self-hosted Jitsi meet instance to do so. (So thanks for your project, first of all!) My students (IMO rightfully) did not like the "whoop" (?) sounds when someone was entering/leaving the room.

I hacked together the following patch that I used on my instance on top of revision 37fb081e6:
```diff
diff --git a/config.js b/config.js
index 9a297bcd1..b0ea9ccf8 100644
--- a/config.js
+++ b/config.js
@@ -475,6 +475,8 @@ var config = {
     // If set to true all muting operations of remote participants will be disabled.
     // disableRemoteMute: true,
 
+    disableJoinLeaveSounds: true;
+
     // List of undocumented settings used in jitsi-meet
     /**
      _immediateReloadThreshold
diff --git a/interface_config.js b/interface_config.js
index 7db8ba271..b7a8176b0 100644
--- a/interface_config.js
+++ b/interface_config.js
@@ -200,7 +200,7 @@ var interfaceConfig = {
     /**
      * If true, notifications regarding joining/leaving are no longer displayed.
      */
-    DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
+    DISABLE_JOIN_LEAVE_NOTIFICATIONS: window.location.href.includes("UIUCAndreasTeaches"),
 
     /**
     * Decides whether the chrome extension banner should be rendered on the landing page and during the meeting.
diff --git a/react/features/base/participants/middleware.js b/react/features/base/participants/middleware.js
index 9886b6219..87fdaf030 100644
--- a/react/features/base/participants/middleware.js
+++ b/react/features/base/participants/middleware.js
@@ -316,7 +316,7 @@ function _localParticipantLeft({ dispatch }, next, action) {
  */
 function _maybePlaySounds({ getState, dispatch }, action) {
     const state = getState();
-    const { startAudioMuted } = state['features/base/config'];
+    const { startAudioMuted, disableJoinLeaveSounds } = state['features/base/config'];
 
     // We're not playing sounds for local participant
     // nor when the user is joining past the "startAudioMuted" limit.
@@ -330,10 +330,12 @@ function _maybePlaySounds({ getState, dispatch }, action) {
 
             // The sounds for the poltergeist are handled by features/invite.
             if (presence !== INVITED && presence !== CALLING) {
-                dispatch(playSound(PARTICIPANT_JOINED_SOUND_ID));
+               if (!disableJoinLeaveSounds)
+                    dispatch(playSound(PARTICIPANT_JOINED_SOUND_ID));
             }
         } else if (action.type === PARTICIPANT_LEFT) {
-            dispatch(playSound(PARTICIPANT_LEFT_SOUND_ID));
+            if (!disableJoinLeaveSounds)
+                dispatch(playSound(PARTICIPANT_LEFT_SOUND_ID));
         }
     }
 }
```
This gave me the desired behavior on the web: no enter/leave sounds for a configurable room, by using the following snippet in the config:
```js
disableJoinLeaveSounds: window.location.href.includes("UIUCAndreasTeaches"),
```
However, the Android app (version 20.2.3 from F-Droid) only says "Connection lost" (I only have German: "Verbindung getrennt") when attempting to connect to such a Jitsi instance.

Is actual JS as part of the config intended as a supported feature? If nothing else, I think it would be useful to achieve consistency across the web and app clients in that respect.

**Comment by saghul** [comment]
> Is actual JS as part of the config intended as a supported feature? If nothing else, I think it would be useful to achieve consistency across the web and app clients in that respect.

It's not supported. On web it is because JS is included with SSI so there is no risk of eval-ing untrusted code, but mobile needs to download the JS file and eval it. This poses a security rist, so we evaluate it in a sandbox which has no acccess to the host environment. It even lacks the window object.

We have plans to move away from JS in config also for web, but haven't been able to execute them yet.
