### ISSUE TITLE
firefox 43 not supported

### ISSUE THREAD

**Issue by h-cloud** [jitsi/jitsi-meet#6660]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
We don’t support such old versions. Generally speaking we support the latest ESR release an onwards (on Firefox).
