### ISSUE TITLE
ERROR: Failed to resolve: org.jitsi.react:jitsi-meet-sdk:+

### ISSUE THREAD

**Issue by Rana-Mohit** [jitsi/jitsi-meet#6661]
Hi jitsi team,
 I am making my own SDK artifacts/binaries.By following these steps:-
1 - Navigate to the newly added jitsi-meet folder and execute npm install after that remove video mute button from toolbox.js.
 2- Create a new folder( /tmp/repo ) inside root folder 
3- Copy the react native and JavaScriptCore dependency via cp -r node_modules/react-native/android/com tmp/repo/ and cp -r node_modules/jsc-android/dist/org tmp/repo/ 
4- Run this command ./android/scripts/release-sdk.sh /tmp/repo 
5- Create a new android Project
 6- Copy the /tmp/repo folder into this project
 7- Add maven { url “file:/tmp/repo” } in the build.gradle (Project:MyProject) 
8- Add implementation (‘org.jitsi.react:jitsi-meet-sdk:+’) { transitive = true } to the build.gradle

When i implement point 7 and 8 in android studio for first time my project works fine.

But when we restart android studio and open same project again, it give me the error -
ERROR: Failed to resolve: org.jitsi.react:jitsi-meet-sdk:+ Show in Project Structure dialog Affected Modules: app

And if we use tmp/repo folder in other mac system in android studio(new project) we get the same error - 
ERROR: Failed to resolve: org.jitsi.react:jitsi-meet-sdk:+ Show in Project Structure dialog Affected Modules: app

Note- Using stable/jitsi-meet-4468
Note - Also used jitsi-meet-mobile - 19.5

Note - when using maven { url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" } it works perfectly.

I don't Know why it is not working on second time or on another system.
I am missing something or did something wrong? Please help.

**Comment by saghul** [comment]
> 3- Copy the react native and JavaScriptCore dependency via cp -r node_modules/react-native/android/com tmp/repo/ and cp -r node_modules/jsc-android/dist/org tmp/repo/

You can sskip this step, the script takes care of it.

>  6- Copy the /tmp/repo folder into this project

No need.

**Comment by Rana-Mohit** [comment]
> You can sskip this step, the script takes care of it.

Skip the step 3 and directly use script "./android/scripts/release-sdk.sh /tmp/repo".But got empty repo folder as below you can check.
![Screenshot 2020-05-12 at 2 48 01 PM](https://user-images.githubusercontent.com/64829661/81666746-11863200-9460-11ea-99b4-fef5278f15f9.png)


> > 6- Copy the /tmp/repo folder into this project
> 
> No need.

If i will not put my custom local sdk folder in android project and give path to that folder than how can i see my changes.

**Comment by saghul** [comment]
> But got empty repo folder as below you can check.

That's not where the result will go. It'ss /tmp/repo, it's an absolute path.

**Comment by Rana-Mohit** [comment]
> > But got empty repo folder as below you can check.
> 
> That's not where the result will go. It'ss /tmp/repo, it's an absolute path.

Ok found it.
It is in file:/private/tmp/repo/com/facebook/react/react-native/
![Screenshot 2020-05-12 at 4 06 02 PM](https://user-images.githubusercontent.com/64829661/81674266-85c5d300-946a-11ea-924c-4bce23f3d6d1.png)

this is inside hidden "private" folder.


Now i have to put path in android project like this -
maven { url "file:/private/tmp/repo" }

**Comment by Rana-Mohit** [comment]
> /tmp is the same as /private/tmp

@saghul  thanks it works.

**Comment by saghul** [comment]
Publish where?

**Comment by Rana-Mohit** [comment]
Actually i want to remove this line from build.gradle -
implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }

Or
replace it with something like -
implementation ('com.github.mohit:sdkrepo:+') { transitive = true }

**Comment by Rana-Mohit** [comment]
Actually i want to remove this line from build.gradle -
implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }

Or
replace it with something like -
implementation ('com.github.mohit:jitsisdkrepo:+') { transitive = true }

**Comment by saghul** [comment]
That's not how it works. Even if you publish it elsewhere the package name will remain the same.
