### ISSUE TITLE
jitsi-meet-ios-sdk-releases-master swift: conferenceTerminated delegate not called after hangup

### ISSUE THREAD

**Issue by datacosmos** [jitsi/jitsi-meet#6662]
I have searched through the issues - but only find unclear and not answered issues which could be similar.

## Description

I imported the prebuilt ios-sdk-releases from github last week. I adapted the example application in the way that I start the video conference from a WKWebview, my code is near the examples:

`        cleanUp()

        // create and configure jitsimeet view
        let jitsiMeetView = JitsiMeetView()
        jitsiMeetView.delegate = self
        self.jitsiMeetView = jitsiMeetView
        let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.welcomePageEnabled = false
            builder.serverURL = serverURL
            builder.room = room
            //builder.token = token
        }
        jitsiMeetView.join(options)

        // Enable jitsimeet view to be a view that can be displayed
        // on top of all the things, and let the coordinator to manage
        // the view state and interactions
        pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
        //pipViewCoordinator?.configureAsStickyView(withParentView: self.owView)
        pipViewCoordinator?.configureAsStickyView()
        
        // animate in
        jitsiMeetView.alpha = 0
        pipViewCoordinator?.show()
        //owView.addSubview(jitsiMeetView)
        
    }
    fileprivate func cleanUp() {
        jitsiMeetView?.removeFromSuperview()
        jitsiMeetView = nil
        pipViewCoordinator?.exitPictureInPicture()
        pipViewCoordinator = nil
        // reload Webview after hangup.
        self.vc.reloadWebView()
        
    }
    public func conferenceTerminated(_ data: [AnyHashable : Any]!) {
        DispatchQueue.main.async {
            self.pipViewCoordinator?.hide() { _ in
                self.cleanUp()
            }
        }
    }
    public func enterPicture(inPicture data: [AnyHashable : Any]!) {
        DispatchQueue.main.async {
            self.pipViewCoordinator?.enterPictureInPicture()
        }
    }`
---

## Current behavior

When I start the video call (welcomePage disabled), everything works fine, but when I hang up, the view hides and what I see is a white screen with a spinning wheel (seems from the startup).
Debugging shows me that after a hangup conferenceTerminated seems not to be called.

---

## Expected Behavior

The view with the spinning wheel should als hide/close, conferenceTerminated delegate should be called and the original webview should appear again.

---

## Possible Solution

Call conferenceTerminated delegate? Or are there other delegates I should implement for getting the hangup?

---

## Steps to reproduce

see description

---

# Environment details

Xcode 11 Version 11.4.1 (11E503a), jitsi-meet-ios-sdk-releases-master swift, Simulator (iPhone) and Hardware Device (iPad), Swift 5
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-12 at 10 02 51](https://user-images.githubusercontent.com/30296295/81656973-cbb57380-9437-11ea-8f06-67d44eec8b03.png)

---

**Comment by saghul** [comment]
re you able to reproduce this with our PiP sample?

**Comment by datacosmos** [comment]
No, with the PiP Sample the delegate is called. 
I am not using the code not directly inside the viewcontroller but in a separte class:
open class JitsiHandler: NSObject, JitsiMeetViewDelegate {

Could that be a problem?

**Comment by datacosmos** [comment]
Ah! I solved it - the the delegate needs to be an extension of a viewcontroller - not of an NSObject class.
