### ISSUE TITLE
INITIAL_TOOLBAR_TIMEOUT override is not working

### ISSUE THREAD

**Issue by harish-aka-shivi** [jitsi/jitsi-meet#6667]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.
- Looked around found nothing like this.

## Description
I am using `Jitsi Meet API` iframe APIs and trying to override the `INITIAL_TOOLBAR_TIMEOUT` using the following options. It is correctly been applied to JITSI player configurations as I can see from console. But, this is not making toolbar to hide. It still hides after `20s` which is the original config.

```
 const options = {
        roomName: 'some room name',
        parentNode: document.querySelector(containerId),
        interfaceConfigOverwrite: {
          SHOW_CHROME_EXTENSION_BANNER: false,
          INITIAL_TOOLBAR_TIMEOUT: 4000,
          TOOLBAR_TIMEOUT: 4000,
          TOOLBAR_ALWAYS_VISIBLE: false,
        },
      };
```
---

## Current behavior
The toolbar is hiding after 20 seconds.

---

## Expected Behavior

The toolbar should hide after 4 seconds

---

## Possible Solution

There was a recent problem with Toolbar where the button configs override was not working. IT could be related to that.

---

## Steps to reproduce
- Initialize Jitsi Player API
`const api = new JitsiMeetExternalAPI(domain, options);`
with the above options object
---

# Environment details
---
OS: macOS 10.15.2
Browser: Google chrome (81.0.4044.138)

**Comment by justyn** [comment]
I'm also seeing this bug - we need to stop the toolbar from hiding for use on a touchscreen where there is no mouse.

**Comment by piloos** [comment]
I am also seeing this issue...

**Comment by math3006** [comment]
Issue confirmed here too

**Comment by justyn** [comment]
Has this been fixed?

**Comment by saghul** [comment]
Fixed by https://github.com/jitsi/jitsi-meet/pull/9897
