### ISSUE TITLE
feature request: live closed captioning

### ISSUE THREAD

**Issue by teslasmoustache** [jitsi/jitsi-meet#6668]
Live closed captioning is a feature that is available on Twitch, but as far as I'm aware, not on any videoconferencing software - at least not readily available.

I don't know if it would have to use a third party service or what, but I think this would greatly increase the accessibility of Jitsi.

**Comment by saghul** [comment]
This is suppored on Jitsi already, but there is a cost associated to it (Google Cloud translation service) so you have to deploy your own infrastructure to enable it.

THis is part of the Pro offering of 8x8.vc, you can also give it a try there.

**Comment by teslasmoustache** [comment]
Interesting. Thank you for pointing that out. I hadn't seen it before.

But since there is a cost associated with it, and you have to depend on a major software company to use it, what do you think of the prospect of something like Mozilla's Common Voice for other implementations of Jitsi? Or any other STTs if any FOSS ones are effective. 

With closed captioning being a necessary accessibility tool, it would be nice if it didn't *have* to cost more money. Trading money for accessibility rubs me the wrong way. Seems almost like a penalty for deaf people, ya know?

**Comment by unfa** [comment]
I wonder if there's any option to self-host an open-source service that could replace the Google one used here.

**Comment by damencho** [comment]
https://github.com/jitsi/jigasi#vosk-configuration-for-transcription
