### ISSUE TITLE
Is coturn bundled as the turnserver?  Updated coturn version fixes security issues and numerous bugs.

### ISSUE THREAD

**Issue by stondino00** [jitsi/jitsi-meet#6669]
Not sure if coturn is bundled in the jitsi meet packages somewhere.  Doesn't appear to be in the turnserver package.  Coturn released a new update on April 30th fixing many bugs and security updates.

https://github.com/coturn/coturn/blob/master/ChangeLog

**Comment by saghul** [comment]
We don't bundle it. We use packages provided in the Debian / Ubuntu repositories.
