### ISSUE TITLE
Error: Cannot create URL for blob!, js engine: hermes

### ISSUE THREAD

**Issue by shekharDongare** [jitsi/jitsi-meet#6676]
I just cloned the repo and tried to run-android application with "react-native run-android" command. Android studio is not showing any error, when after bundle gets loaded getting error message "Error: Cannot create URL for blob!, js engine: hermes".
<img width="355" alt="issue" src="https://user-images.githubusercontent.com/42262429/81734841-c7c63780-94b1-11ea-85b7-43af0eab33d5.png">

**Comment by saghul** [comment]
That’s weird, I fixed that recently. What exact commit do you have?

**Comment by shekharDongare** [comment]
I have cloned it 10-12 days before.

**Comment by shekharDongare** [comment]
@saghul I have cloned the new repo, the issue is resolved, but can you tell me the fix or commit number so that I can do that in my project, as I have made a lot of changes in last week in the application for iOS version.

**Comment by saghul** [comment]
This is the commit that fixed it: https://github.com/jitsi/jitsi-meet/commit/6939939a0f7157822a60ef8a85503560368b406c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
