### ISSUE TITLE
Language Detection not working after change

### ISSUE THREAD

**Issue by cremfert** [jitsi/jitsi-meet#6678]
Hi there,

since this change: https://github.com/jitsi/jitsi-meet/pull/5956, the whole interface is in English, although my device is set to German. This worked before in older versions. 

What can I do?

Best regards
Chris

**Comment by saghul** [comment]
What app version are you running? That should’ve been fixed shortly after: https://github.com/jitsi/jitsi-meet/pull/6565

**Comment by cremfert** [comment]
The one from the maven repository - is the master version not in there?

Thanks and best regards, Chris

**Comment by saghul** [comment]
No, that commit is not on a release yet. I'll make one later today most likely.

**Comment by cremfert** [comment]
Thanks! @saghul

**Comment by willwach** [comment]
Language detection is already not working with Release 2.8.2 on Android.
2.8 ist working correctly, but it's without the feature flags.

**Comment by saghul** [comment]
We haven't released 2.9 yet, which should include the fix.
