### ISSUE TITLE
Android/ Call in process remain after leaving the meeting 

### ISSUE THREAD

**Issue by carlos2712** [jitsi/jitsi-meet#6680]
## Description

On Android R after leaving a Jitsi meeting the app remains the call open. Which it's  causing problems in others apps or even opening a new meeting. 

Is asking the following: 

![image](https://user-images.githubusercontent.com/37664806/81746540-ac890700-9474-11ea-9bda-1478ae18a9cd.png)
 
![Android_Emulator_-_Pixel_2_API_R_5554](https://user-images.githubusercontent.com/37664806/81746723-f70a8380-9474-11ea-8ff6-193faaabeb05.png)

## Current behavior
---

Calling  view.dispose() it's leaving the call open. 

## Expected Behavior
---
After on JitsiMeetActivity and  calling view.dispose()  the call should be also be terminated.  

## Possible Solution
---

## Steps to reproduce
---

I'm using JitsiMeetView and JitsiMeetViewListener

This  how I build the meeting conference : 

`        JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setSubject(" ")
                .setRoom(roomName)
                .setAudioMuted(startWithAudioMuted)
                .setVideoMuted(startWithVideoMuted)
                .setWelcomePageEnabled(false)
                .build();
        view.join(options);
        setContentView(view);`

This is trigger after I left the meeting : 

` @Override
            public void onConferenceTerminated(Map<String, Object> data) {
                view.dispose();
                view = null;
                finish();
                on("onConferenceLeft", data)
            }`

1) Try to join into a JITSI meeting
2) Left the meeting and you will see the call icon at the top menu. 
3) This is only happening on Android R. 

** Just in case I'm using Ionic React and capacitor 

# Environment details
---

 implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }
Android Version : R

**Comment by carlos2712** [comment]
> Share steps to reproduce, include parts of your code, and don't forget to format your answer

@nedimf  updated. let me know if it clear enough.

**Comment by nedimf** [comment]
@carlos2712 so you are using React?

**Comment by carlos2712** [comment]
@nedimf  Yes

**Comment by nedimf** [comment]
@carlos2712  I will tag @saghul who might have an idea for possible fix .

**Comment by saghul** [comment]
I suggest you disable the native call integration on Android. self-managed ConnectionService is a shit show, it breaks in all sorts of wayss depending on the manufacturer :-(

Set this: `.setFeatureFlag("call-integration.enabled", false)`

**Comment by carlos2712** [comment]
@saghul   I set flag like this but is still happening : 

`   JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setRoom(roomName)
                .setFeatureFlag("call-integration.enabled", false)
                .setToken(token)
                .setSubject(" ")
                .setAudioMuted(startWithAudioMuted)
                .setVideoMuted(startWithVideoMuted)
                //.setAudioOnly(false)
                .setWelcomePageEnabled(false)
                .build();
        view.join(options);
        setContentView(view);`

I am missing something ?
