### ISSUE TITLE
User account for new meetings, but no account for guests that receive the link.

### ISSUE THREAD

**Issue by openaspace** [jitsi/jitsi-meet#6682]
Hello.
I'm using jitsi in our company and it works very well.

The big problem is that setting up it to access only to the users with an account, create a lot of privacy problems.

An internal company account need to communicate with external users, and the account is needed also for the external non company accounts.

There is no way to set jitsi internal account for meeting creations, but no account for guests that receive the invitation link.

Please solve this bad account management.

**Comment by damencho** [comment]
Following this guide https://github.com/jitsi/jicofo#secure-domain you can enable username/passwords for those creating the rooms and the guest can connect in already created room without an account.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.
