### ISSUE TITLE
Jitsi doesnt use Proxy.pac in Firefox correct

### ISSUE THREAD

**Issue by Gurkenmus** [jitsi/jitsi-meet#6685]
Chrome benutzt den Proxy ordentlich.
Firefox:
Hier sieht es anders aus. Firefox scheint bei Verwendung einer Proxy.pac diese für die Verbindung zum Turn-Server nicht zu beachten und geht für diese Verbindung wieder direkt. Das scheint ein Fehler in der Meetingsoftware zu sein. Stellt man den Firefox auf manuelle Proxy Konfiguration um und hinterlegt testweise den Proxy manuell, so wird der Proxy auch für den Turn-Server genutzt. Allerdings ruft Firefox den Turnserver nicht über dessen DNS-Namen auf, sondern direkt über die IP-Adresse (xx.xx.xxx.xxx). Da der Turnserver jedoch vom SSL-Scanning ausgenommen werden muss, muss die IP also ebenso als SSL-Ausnahme hinterlegt werden. Hier genügt rxxxx.X.ssl.inspectionwhitelist.urlhost nicht, da dann die Zertifikatsprüfung fehlschlagen würden. Das Zertifikat ist auf den DNS-Namen, nicht auf die IP ausgestellt. D.h. hier müsste man die IP in die Liste rxxxx.X.ssl.tunneledhosts.urlhost aufnehmen, um zusätzlich auch den Zertifikatscheck zu deaktivieren.
Den Proxy manuell zu hinterlegen ist keine Dauerlösung, da hierdurch einige interne Webseiten nicht mehr erreichbar werden. Hier empfehlen wir beim Anbieter der Meetinglösung bezüglich des Problems mit der Proxy.pac-Nutzung im Firefox nachzufragen.

**Comment by Gurkenmus** [comment]
Translation:
Chrome uses Proxy in the right way.
Firefox:
It looks different here. Firefox seems to ignore this when using a Proxy.pac for the connection to the turn server and goes directly for this connection again. That seems to be a bug in the meeting software. If you switch the Firefox to manual proxy configuration and manually test the proxy, the proxy is also used for the turn server. However, Firefox does not call the turn server via its DNS name, but directly via the IP address (xx.xx.xxx.xxx). However, since the turn server must be exempted from SSL scanning, the IP must also be stored as an SSL exception. Here rxxxx.X.ssl.inspectionwhitelist.urlhost is not sufficient, as the certificate check would then fail. The certificate is issued on the DNS name, not on the IP. I.e. here you would have to add the IP to the rxxxx.X.ssl.tunneledhosts.urlhost list to additionally deactivate the certificate check.
Storing the proxy manually is not a permanent solution, as this means that some internal websites can no longer be reached. Here we recommend asking the provider of the meeting solution about the problem with using Proxy.pac in Firefox.

**Comment by saghul** [comment]
Hi there,

I don't know what Proxy.pac is. The meetings software, Jitsi Meet here, is "just" a JavaScript application running in the browser. We cannot decide to connect to a proxy, the browser does that.

If there is a bug in how Firefox does TURN connections when using some kind of ssystem wide proxy, you need to report that to Firefox, as there is nothing we can do about it.

**Comment by luixxiul** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file

@Gurkenmus Erfahren Sie das Problem nur auf Jitsi Seite?

**Comment by Gurkenmus** [comment]
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file
> 
> @Gurkenmus Erfahren Sie das Problem nur auf Jitsi Seite?

Ja, es funktionieren alle besuchten Websites ganz normal, alles läuft via Proxy. Nur unsere Jitsi Applikation bekommt es nicht hin bei Firefox über Proxy zu gehen (bei Chrome funktioniert es..)
