### ISSUE TITLE
Make all interaction functions available for call-in as well (raise hand, mute, ..)

### ISSUE THREAD

**Issue by tgoeg** [jitsi/jitsi-meet#6686]
In larger conferences, it's very important for most participants to just listen and to have a moderator steer the meeting so only explicitly allowed participants can talk.
That's not an issue for web or app users, as they can be muted (or mute themselves) and raise their hand if they want to speak.
However, call-in users cannot raise their hand (or use other functionality than talking/listening). They can mute their telephone but that's also not visible to others.
This is also valid more generally - all additional functionalities should be considered for call-in users as well. (Maybe even disable camera and chat are possible for more feature rich SIP phones? I don't know.)

A simple solution would be to make interaction functions be switchable (toggle) by sending keypad numbers (DTMF for POTS users), e.g. 1 or *1 for "raise hand" (1 even looks like an up-arrow, so this would be pretty intuitive)

If I understand this correctly, this would be something a VoIP service would have to intercept (and also possibly add an introductory text that explains those functions). But I guess what is missing is the API that provides this. I am not sure whether this is actually a jigasi issue.

The only other alternative is for moderators to regularly poll all call-in users if there are any questions, which is time-consuming and inefficient.

Thanks!

**Comment by paf61** [comment]
I agree. Mute-all, show if muted, and "raise hand" must work for dial-in users as well.

Some years ago I was an Asterisk project where we implemented it this way:
Press 1 for "raise hand", 0 for "lower hand".

Asterisk DTMF event:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_DTMFBegin

Asterisk mute event:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+17+ManagerEvent_ConfbridgeList

**Comment by tbart** [comment]
I don't think this should be closed as there is no answer from a dev yet. Asterisk implementation might help for intercepting, but are the APIs there?

**Comment by damencho** [comment]
The muting functionality is available through some SIP INFO messages, but it needs to be implemented on the PBX/asterisk side. We are currently adding lobby support and force mute support while it is being worked on and for jitsi-meet.
https://github.com/jitsi/jigasi/pull/236
There are no plans for now to implement risehand, but it can be done like the startmuted and mute unmute support, but this had nothing to do with jitsi-meet project, this needs to be in jigasi.

**Comment by Echolon** [comment]
@damencho @saghul the stale-bot is going crazy at the moment. Is that of interest?
