### ISSUE TITLE
Make Jitsi widget interface looks better and usable with low height

### ISSUE THREAD

**Issue by MurzNN** [jitsi/jitsi-meet#6687]
Often, when Jitsi widget integrated into other interface (eg Riot.im messenger) with low height, his usability is very bad, here is some screenshots from Riot.im with height=273px:
- tile view with 3 users:
![image](https://user-images.githubusercontent.com/336662/81789305-71d2ad80-950c-11ea-99af-d4e0e89eea64.png)
- tile view with 3 users hovered:
![image](https://user-images.githubusercontent.com/336662/81790604-4b157680-950e-11ea-9f33-9f7f7532e332.png)
- list of users in conference can't show even one user:
![image](https://user-images.githubusercontent.com/336662/81790777-8adc5e00-950e-11ea-81f7-96e705730aeb.png)

Will be good to fix this issues for make Jitsi widget more usable with low height.

**Comment by luixxiul** [comment]
I would reorder the tiles horizontally with `display: grid` with media queries.

**Comment by l3d00m** [comment]
Hi @MurzNN, thanks for providing the good example images. I'm going to close this is in favour of #5142 to keep the discussion in one place.
