### ISSUE TITLE
Android release-sdk.sh not pushing hermes to maven repo

### ISSUE THREAD

**Issue by fritzfr** [jitsi/jitsi-meet#6688]
## Description

I am trying to publish my own compiled Android SDK to my own maven repo. I modified the maven URLs in both `android/build.gradle` and `android/sdk/build.gradle`. The script runs successfully, but the repo ends up missing `com/facebook/hermes`, the rest is there.

The hermes folder does get created in the temporary location (`DEFAULT_MVN_REPO="${THIS_DIR}/../../../jitsi-maven-repository/releases"`) when the script is running, but it does not get pushed to the maven repo specified in the build.gradle files.

My builds implementing Jitsi Android SDK are therefore crashing with:

> E/SoLoader: couldn't find DSO to load: libhermes.so
>  java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so

The script produces the following contents in the `DEFAULT_MVN_REPO` folder locally:
- com
  - facebook
    - hermes
        - 0.2.1/
        - maven files ...
    - react
        - react modules ...
- org
  - jitsi
    - react
      - jitsi-meet-sdk
        - 2.8.2/
        - maven files ...

But in the maven repo, the contents are only:

- com
  - facebook
    - react
        - react modules ...
- org
  - jitsi
    - react
      - jitsi-meet-sdk
        - 2.8.2/
        - maven files ...

## Expected Behavior

The hermes folder should get pushed too.

## Possible Solution

A very similar issue is https://github.com/jitsi/jitsi-meet/issues/5213, however the author didn't mention his solution yet.

## Steps to reproduce
1. Replace mavenRepo, username and password in the `build.gradle` files with your own.
2. Run `./android/scripts/release-sdk.sh`
3. Check the contents of the repo after the script is done, it is missing `hermes` under `com/facebook/`. It is however in the local maven repo.

# Environment details
Current master.

**Comment by saghul** [comment]
Hermes needds to be manually pushed to the maven repo, that's what the script does. If you have a Maven repo accessible via HTTP then `export MVN_REPO=https:...` before running the script. The same problem happens with React Native itself, but the script publishes both.

**Comment by fritzfr** [comment]
@saghul I don't think I'm following. I do include my HTTP accessible Maven repo.

> The same problem happens with React Native itself, but the script publishes both.

Only react native is included as mentioned, hermes isn't. I don't see a difference in the script between them, and why one wouldn't get pushed.

**Comment by mduisenov** [comment]
I've deployed into maven repository with `./android/scripts/release-sdk.sh`  `hermes` and `react native`

But cannot access to jitsi sdk:
