### ISSUE TITLE
Secure Domain: Jitsi Meet Android App cannot authenticate 

### ISSUE THREAD

**Issue by dschmidtke** [jitsi/jitsi-meet#6693]
## Description
---
Installed jitsi-meet on Debian 10 from the official repository download.jitsy.org on my vserver (PHP-FPM 7.3, Apache 2.4). Tried several Jitsi Meet clients (IOS, Android, Browser). Everything worked as expected.

Next I configured authentification according to the docs at https://github.com/jitsi/jicofo#secure-domain. The result was that it was impossible to join a conference on Android -- while IOS app and browser worked as expected.

(Already opened a bug on the Jicofo issue tracker, but seems to be a jitsy meet Android App issue, since IOS app and Jitsi Meet in the web browser do work.) 

## Current behavior
Installed Jitsi Meet on my Android device. Configured my server url in settings.

Entered the name of a non-existing conference and tapped "join". A message appeared: disconnected and retry in x seconds. And so on.

Started a conference with a new name in another client. Back on Android I entered the same new name and tapped join. Same message appeared as before. Disconnected. Retry. And so on.

## Expected Behavior
Android App flow should be the same like in IOS app or in the browser: 
- When entering the name of a non-existing conference, prompt the participant to wait for the organiser or enter credentials.
- When entering the name of an existing conference, let the participant join.

# Environment details
Tried the following versions of Jitsi Meet from f-Droid: 20.2.0, 20.2.1, 20.2.3.
On a second Android device I tried version 20.2.3.4129209 from Google Play - same problems.

**Comment by luixxiul** [comment]
Did you set up your SSL certificate as a full-chain one?

**Comment by dschmidtke** [comment]
I am using a letsencrypt certificate (generated with a self-installed certbot, not with the jitsi meet installer script). So, in my Apache's virtual host conf I have:
```
SSLCertificateFile /etc/letsencrypt/live/[...]/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/[...]/privkey.pem
```

**Comment by dschmidtke** [comment]
So I changed the virtualhost config to use fullchain.pem instead of cert.pem, and that fixes the issue. Apparently Android is picky with certificates. My bad. Thanks for pointing me into the right direction. Issue closed.

**Comment by luixxiul** [comment]
No problem. I understand your situation because I have stuck with the same issue once ;-)

**Comment by luixxiul** [comment]
Also PR for this issue is on its way :-)

https://github.com/jitsi/jitsi-meet/pull/5960/files#diff-2e69fdb5c4abb5fedfcbdb7acbc2c915R56-R62
