### ISSUE TITLE
FR: Debian packages - 1) place interface_config.js in /etc/jitsi / 2) optional custom language file

### ISSUE THREAD

**Issue by pandel** [jitsi/jitsi-meet#6697]
Hi!

Two feature requests regarding the Debian packages:

1) as interface_config.js is clearly expected to be customizable, please place it as conffile under /etc/jitsi, so it won't be overriden

2) if one wants to make changes to the different displayed texts the only way to go is to modify the language files today - it would be great if one could define a custom language file that won't be overriden via apt update

Regards,
Holger

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/pull/6345

**Comment by damencho** [comment]
The problem with language files is that if you copy and modify the file that will be quickly go out of sync and that will work for everything without english, the default one which is embedded in the app bundle.

**Comment by pandel** [comment]
Many thanks for the link! I totally understand the problem with the language file.

As our installation is working perfectly now, I tend to simply set all Jitsi packages on apt hold, so nothing gets changed when I update the rest of the system. Seems the only solution for now.

But never mind! Keep up the good work :-)! It is really really amazing!

**Comment by pandel** [comment]
> 
> 
> The problem with language files is that if you copy and modify the file that will be quickly go out of sync and that will work for everything without english, the default one which is embedded in the app bundle.

I thought about this a little further. Why don't you introduce some kind of language-override.json, which could contain user chosen language overrides? This file could be read in after the main language file and would then replace single entries leaving the rest untouched. And this file could be placed into /etc/jitsi without touching the default files.

**Comment by pandel** [comment]
Anything happening in this regard?
