### ISSUE TITLE
Call aborted

### ISSUE THREAD

**Issue by t104360088** [jitsi/jitsi-meet#6699]
## Description
When using the Jitsi meet, I hang up the phone and try to call again, I got this issue
I use the socket to listen other's hang up action and close the Jitsi (after listening the action, I do the leave(), when I get the onConferenceTerminated() callback, I finish the activity )

## Possible Solution
I think this problem happened recently, because I test the jitsi in 2.8.0 version
and I do not have this issue

## Environment details
OS: android 8.0
SDK: org.jitsi.react:jitsi-meet-sdk:2.+

**Comment by saghul** [comment]
We’ve seen a number of problems when using ConnectionService. I suggest you use the feature flag to disable it.

**Comment by t104360088** [comment]
Thank you for your response,
Do you mean use setFeatureFlag("call-integration.enabled", false)?
What does this code do?

**Comment by saghul** [comment]
Yes, that's what I mean. That disables ConnectionService integration, which is resposible for that call aborted dialog. We have tried to fix it, but it dependds on vendor speecific implementation deetails, and we haven't been able to overcome all the bugs.

**Comment by t104360088** [comment]
Ok, I know, Thank you for your help
