### ISSUE TITLE
Screen artifacts after screen sharing ends

### ISSUE THREAD

**Issue by nothingbutnetcode** [jitsi/jitsi-meet#6702]
We are experience the same issues as described in this post:  https://community.jitsi.org/t/strange-artifacts-after-screen-share-ending/35319

Namely, that after screen sharing there is a large black triangle on screen over the video feed of the user.  As well as other smaller visual artifacts.

I couldn't find any open issues related to this so thought I'd create one. 
We are self-hosting the latest version available on Ubuntu 18.04, installed via APT.

Thanks

**Comment by ForestRolf** [comment]
In addition to the above mentioned issue:
I have an strange artifact **as soon as** I activate Screen saving. A grey square right in the middle of my screen. It stays (or, it is on top of everything) I use meet.jit.ci in Chrome with W10  
![Jitsi grey square](https://user-images.githubusercontent.com/65650366/82423353-f16bf980-9a83-11ea-809a-e2c429baf1a4.jpg)

Only way to get rid of it is by reboot.

**Comment by banksio** [comment]
We are also experiencing the same issues, although only seems to happen on NVIDIA GPUs. The AMD GPU has never reproduced this issue. It seems that possibly the older the GPU, the more likely it is to happen? Occurs on both the electron app and the web client.
![image](https://user-images.githubusercontent.com/30214760/83137820-b308b700-a0e1-11ea-9aba-7a329b1ee0b9.png)

**Comment by saghul** [comment]
This sounds like a either a Chrome or device driver issue.

As an application running in the browser we really have no control over this.
