### ISSUE TITLE
Dependencies update automation

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6703]
Dependencies update should integrate automation, in order to patch security vulnerabilities etc. as soon as possible.

Integrating https://dependabot.com/ with github-action should work nicely.

See:
- https://github.com/nextcloud/forms/pulls?q=is%3Apr+author%3Aapp%2Fdependabot-preview
- https://github.com/nextcloud/forms/blob/master/.github/workflows/dependabot-approve.yml

It depends on your take whether merging a PR also should be automated as it may lead to a regression bug.

**Describe the solution you'd like**

See above.

**Describe alternatives you've considered**

I am not quite sure about other alternatives to automate this type of procedure.

**Comment by saghul** [comment]
We do have dependabot enabled IIRC.

**Comment by luixxiul** [comment]
Still, I haven't seen it working here...  🤔

**Comment by luixxiul** [comment]
Now I did: https://github.com/jitsi/jitsi-meet/pull/6476

:-)
