### ISSUE TITLE
Rest Reservation API return Code not being handled properly

### ISSUE THREAD

**Issue by spisipa** [jitsi/jitsi-meet#6709]
## Description
When the rest reservation API returns a 403 , my error message that I return in the json string is not being displayed.

## Current behavior

I use a REST API for reservation. When I return a Http status code of 200, a conference room is created and all is well.

But when I return a 403 (user is not authorized to create a room), I get the following error message:

 oops, something went wrong and we couldn’t connect to the conference: connection.GET_SESSION_ID_ERROR.

## Expected Behavior

I expect that the message I send in the JSON be presented to the user.

## Possible Solution
---

## Steps to reproduce
Return 403 with message in the JSON returned from the REST reservation API.

# Environment details
Ubuntu 16.04, AMDx64.

**Comment by JFMALBI** [comment]
Same behavior ... not very friendly for the end user
It will be great if the message sent in JSON could be displayed

**Comment by topelrapha** [comment]
Is there any workaround or fix for this issue?

We have the same behaviour in our environment.

Thanks in advance!
