### ISSUE TITLE
Need option to set participant as moderator in JitsiMeetConferenceOptions while joining call in iOS

### ISSUE THREAD

**Issue by V1992** [jitsi/jitsi-meet#6719]
We are using two different iOS apps.
One is for teachers and other for the students.
So for that teachers should be the moderators.

But as per now, if student gets join the call as first, then he/she is now considering as the moderator.
It would be good if an option is available to set moderators/participants.
Please add option to change this.

**Comment by luixxiul** [comment]
> if student gets join the call as first, then he/she is now considering as the moderator.

Have you tried setting secure domain?

See: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by V1992** [comment]
yes, we are using secure domain. Handled by our back end team.
we are getting those details such as domain url, room name etc through API call which is set by back end team.

Now we need to set the user as moderator who are using one particular app ie, teacher app while starting the call.
And those who are joining the call using student app, they should be considered as participants only.

Please add option to change this.

**Comment by glasier001** [comment]
we are still facing the same issue can you provide us the feature ?

**Comment by saghul** [comment]
This cannot be implemented with an option, it needs to be part of the token auth process.

**Comment by saumitraebits** [comment]
I am still facing the same issue kindly help
