### ISSUE TITLE
Unable to join a meeting on ubuntu 20.04 when have 2 participants or more

### ISSUE THREAD

**Issue by Sim59121** [jitsi/jitsi-meet#6720]
## Description
When I want to join or create a meeting on jitsi meet in Firefox on Unbuntu 20.04 where there are 2 or more people, I can't because i crash

I always have the same error  message : "Unfortunately, something went wrong. We're trying to fix this. Reconnecting in ... sec..."

Even if it is me who creates the meeting, as soon as a second participant joins the meeting, I crash and I get this error message.

I have try in other browser and it's ok. I just have this bug in Firefox.

## Current behavior
I can't join or create the meeting if there a 2 or more people, i crash

## Expected Behavior
I should be able to participate or stay in the meeting regardless of the number of participants.

## Possible Solution
I don't know

## Steps to reproduce
1. Create a conference with jitsi meet with Firefox on Ubuntu 20.04
2. Invite a participant

or :

1. Join a meeting who are 2 or more participants. (with Firefox on Ubuntu 20.04)

# Environment details
 Firefox 76.0.1 (64 bits) with Ubuntu 20.04

I attach a screenshot of the error message I get.
![bug jitsi meet](https://user-images.githubusercontent.com/51054004/82050273-5f40ab80-96a7-11ea-8fa5-29952b311b4c.png)

**Comment by l3d00m** [comment]
Could you check whether the browser logs contain anything useful? You can check them by opening the web developer tools by pressing F12 and then opening the console tab.

I'm currently in the process of updating to ubuntu 20.04 as well, so I'll soon be able to test this.

**Comment by Sim59121** [comment]
Hello,

There are many logs ! How do I know what to send you or what will be useful ? 

Here are some errors that appear in red in the console :

- The connection with wss://meet-jit-si-eu-central-1b-s7-jvb-40-111-247.jitsi.net/colibri-ws/default-id/53129dadee7b0b92/4c53d80f?pwd=767fuuqaqsj30ht7f97l81tt79 was interrupted while the page was loading.

- Blocking a Cross-Origin Request: The "Same Origin" policy does not allow to consult the remote resource located on https://api.amplitude.com/. Reason: CORS request failure

- TypeError: t is null

- Firefox cannot establish a connection with the server at wss://meet-jit-si-eu-west-2b-s105-jvb-42-75-19.jitsi.net/colibri-ws/default-id/29ea5f42f0efdfb4/ca7f4a84?pwd=1v4ug0p1ubdtpo61bn18s1oq9m.

- 2020-05-16T09:13:40.200Z [JitsiConference.js] <se.prototype._acceptJvbIncomingCall/<>:  Failed to accept incoming Jingle session DOMException: "SIPCC Failed to parse SDP: SDP Parse Error on line 81:  Warning: Invalid named events specified for fmtp attribute.
SDP Parse Error on line 111:  Warning: Invalid named events specified for fmtp attribute.
SDP Parse Error on line 133:  Warning: Unrecognized attribute (ssrc-group) 
SDP Parse Error on line 138:  Warning: Invalid named events specified for fmtp attribute.
SDP Parse Error on line 160:  Warning: Unrecognized attribute (ssrc-group) 
SDP Parse Error on line 78: No rid attribute for 'rid=1'
SDP Parse Error on line 78: No rid attribute for 'rid=1'

**Comment by saghul** [comment]
Please upload all of it on a gist or something alike. Having the context in between the errors is important.

**Comment by l3d00m** [comment]
Similar issue I found is #6351

**Comment by Sim59121** [comment]
Hello,

Here, there are the logs : https://fromsmash.com/Jjaw43X--5-ct
The password is : jitsi

**Comment by Sim59121** [comment]
The issue #6351 solved my problem.
It's alright !
