### ISSUE TITLE
IOS Archive build error - No such file or directory: objdump

### ISSUE THREAD

**Issue by mihaistiuca** [jitsi/jitsi-meet#6730]
I am trying to make a production build for IOS using XCode on MacOS. I cloned the repo, made a few changes to the application, and then tried to Archive the solution.

I get the error:
No such file or directory: **objdump**

Running the application in dev mode on device works perfectly. 

![Screenshot 2020-05-16 at 16 30 05 (2)](https://user-images.githubusercontent.com/23173094/82121085-30076880-9793-11ea-93fb-f766f68b0f59.png)

Any ideas how could I get rid of the error and make the production build? Thanks!

**Comment by saghul** [comment]
What Xcode version are you using?

**Comment by mihaistiuca** [comment]
@saghul 
Xcode 11.2.1
Build version 11B500

I also tried to run this in the root of the project:
**sh ios/scripts/release-sdk.sh**

The script worked.

However, I am not able to publish the archive to AppStoreConnect like I usually do.
After the run of the script I can see the new build in Xcode->Window->Organizer, where I can see all my archives for all my project.
The problem is the fact that my new archives appears under **Other Items**, instead of **IOS Apps**. Please check the image bellow for a better understanding.
Because my archive is under Other Items, I don't have the **Distribute App** button that uploads the app to AppStoreConnect. Instead, I have **Distribute Content**, which only exports it locally. 

<img width="1004" alt="Screenshot 2020-05-17 at 14 57 56" src="https://user-images.githubusercontent.com/23173094/82145018-7bcc1780-9850-11ea-97a8-2a529199ec7a.png">

What should I do in order to publish the archive to AppStore?

**Comment by SrinivasAttili84** [comment]
iam also got the same issue, did u fing any solution

**Comment by saghul** [comment]
You need to be using Xcode 11.4

**Comment by arihant08** [comment]
I am also getting same issue please resolve asap.
I am using xcode 11.4 and i checked also using  xcode 11.5

**Comment by faisal-fls** [comment]
@SrinivasAttili84 @saghul - do we have any hint / solution for this issue ?

**Comment by SrinivasAttili84** [comment]
Yes i resolved that issue. i removed i386 and x86_64 architectures in Jitsi and Webrtc frameworks.

https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive

**Comment by SrinivasAttili84** [comment]
> @SrinivasAttili84 @saghul - do we have any hint / solution for this issue ?

Yes i resolved that issue. i removed i386 and x86_64 architectures in Jitsi and Webrtc frameworks.

https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive

**Comment by KadambariN** [comment]
Facing same error.. I am using Xcode 11.3.1 . Trying to create distribution build for this. Also found that in this project fixup-frameworks.sh is already present  which removes unwanted architecture i.e.  i386 and x86_64. run script name in project is : Adjust embedded framework architectures. 

![Screenshot 2020-08-06 at 5 38 35 PM](https://user-images.githubusercontent.com/30400473/89530205-c0da6700-d80b-11ea-9352-82df2274017a.png)

Please guide me to solve this issue..
