### ISSUE TITLE
Footer on jitsi.org/jitsi-meet is broken on mobile 

### ISSUE THREAD

**Issue by Keij0** [jitsi/jitsi-meet#6735]
If it's not the proper place to discuss such issue, please close this issue. 

## Description
Footer broken on jitsi-meet webpage

## Current behavior
The footer on mentioned web page doesn't scale properly on mobile, it protrudes out of the viewport

## Expected Behavior
The footer shouldn't protrude out of the viewport 

## Possible Solution
Editing the web page styles, CSS I suppose? 

## Steps to reproduce
Visit the web page on Firefox 68.8.0 on Android

# Environment details
Firefox 68.8.0 on Android (codenamed Fennec) 

# Screenshot
![Screenshot_2020-05-16-22-02-35-108_org mozilla firefox](https://user-images.githubusercontent.com/20029608/82129340-2ba67400-97c2-11ea-8d72-7a9ffe6e0cb7.jpg)

**Comment by saghul** [comment]
Thanks for the report!
