### ISSUE TITLE
Problem with microphone on iOS

### ISSUE THREAD

**Issue by nicolaswww** [jitsi/jitsi-meet#6738]
When i'm using iOS the microphone works after re-activating permissions. 

## Steps to reproduce
1. Start meet iframe (using js external API / meet.jit.si)
2. Allow camera/microphone permissions
3. Active camera and microphone from the UI
4. The microphone does not work the first time. I tap on browser permissions to disable camera permissions and when reactivating them it works.

# Environment details
Device: iPhone 7, iOS 13.4.1, Safari browser

**Comment by saghul** [comment]
@jallamsetty1 any ideas?

**Comment by jallamsetty1** [comment]
This seems to be the happening on Safari mobile w/o iframe as well. I was able to reproduce the issue, working on fixing it. Hopefully will have an update soon.

**Comment by jallamsetty1** [comment]
This should be fixed now, can you pls try against https://alpha.jitsi.net/ and confirm if the audio is working fine ?

**Comment by nicolaswww** [comment]
> This should be fixed now, can you pls try against https://alpha.jitsi.net/ and confirm if the audio is working fine ?

Hi, i tried it and it works perfect! Thank you for your response and congratulations to the team for this project :)
