### ISSUE TITLE
Links to the documentation on README.md are not found

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6742]
**Description**: The links on https://github.com/jitsi/jitsi-meet#development are 404. This is due to the documentation has been moved to https://github.com/jitsi/handbook. Hinted by https://github.com/jitsi/jitsi-meet/issues/1844#issuecomment-629788758.

**Steps to reproduce**:

1. Open https://github.com/jitsi/jitsi-meet#development
2. Click two links

**Expected behavior**: The links should be opened

**Actual behavior**: Both are not found

I'm going to do quick fix.

**Comment by saghul** [comment]
Good catch!
