### ISSUE TITLE
Errror when install share screen in mobile

### ISSUE THREAD

**Issue by alfinurhakim** [jitsi/jitsi-meet#6743]
### **Hello** everyone ... I want to ask about the error react native ... 

I have followed the steps of this link to make screen sharing in the application  mobile (https://github.com/jitsi/jitsi-meet/pull/5244/commits/f11b94a0a5ee9f085b152f496627d6243079e6f4#diff-0475ad5b1318463a38eac1e39d79 )

and ....

the issue is where when I install the react-native-webrtc library, then conflicts arise ... conflicts with existing libraries (ie conflicts with lib react-native-google-signin) ... so when I open my application and try to log in to Google as usual this error immediately appears ...? can you help me to solve this error ..? please help because I have been stuck in 3 days 😄🙏

![1589517219921](https://user-images.githubusercontent.com/48195224/82158078-aa2d0f80-98af-11ea-8d8e-172cbbed28bc.JPEG)

# Environment details
Device: Xiaomi Redmi 4x, Android 7.0

**Comment by saghul** [comment]
That is not a patch we have applied yet. You’ll need to ask the author.
