### ISSUE TITLE
The delegate function ConferenceTerminated was called many times

### ISSUE THREAD

**Issue by fatenumber25** [jitsi/jitsi-meet#6746]
## Description
---
I am developing the application on the IOS platform. When I or the person invited to join the room, the delegate function conferenceTerminated was called many times (without error) before we can talk to each other. And when I tapped the hangup button the delegate function  conferenceTerminated was also called (without error), so I didn't know when the hangup button was actually tapped.

My question is how do I know when the hangup button has actually been tapped. And why when someone joins the room the delegate function conferenceTerminated was called many times. Please help me please!!

# Environment details
---
XCode11.3
iOS 13.4.1

**Comment by saghul** [comment]
Can you reproduce this on the sample apps? https://github.com/jitsi/jitsi-meet-sdk-samples

**Comment by fatenumber25** [comment]
Sorry, I discovered it was an application bug. The delegate function conferenceTerminated did its job right.

**Comment by kirti301290** [comment]
@fatenumber25 can you please help how you  fix problem ?
