### ISSUE TITLE
The link to http://translate.jitsi.org is transferred to https://jitsi.org

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6751]
**Description**: The link to `http://translate.jitsi.org` on https://github.com/jitsi/jitsi-meet/tree/master/lang#translating-jitsi-meet is transferred to the home page.

**Steps to reproduce**: 

1. Open https://github.com/jitsi/jitsi-meet/tree/master/lang#translating-jitsi-meet
2. Click `http://translate.jitsi.org`

**Expected behavior**: a translation service is expected to be opened

**Actual behavior**: Transferred to https://jitsi.org/

**Comment by luixxiul** [comment]
I am not quite sure of the current status on how localization work is handled. It is expected to update https://github.com/jitsi/jitsi-meet/blob/master/lang/readme.md, which is 4 years old, to provide contributors information about that.

**Comment by luixxiul** [comment]
Related: https://github.com/jitsi/jitsi-meet/issues/5056

This should be kept open until the documentation will eventually updated.

**Comment by MagicFab** [comment]
I think the following applies now : 

> Language files for Jitsi Meet localization are located in the` /lang` directory. Modifying such files requires a good understanding of git source management. If you want to contribute by improving or adding support to a specific language, edit the appropriate file and submit a pull request for it.

I realize the existing documentation needs a complete rewrite but for now I think it can at least link to this issue report.

**Comment by Echolon** [comment]
@saghul do translations work again?

**Comment by afranke** [comment]
Woooooo, activity.

**Comment by MagicFab** [comment]
Why bother, just close this already. Pull requests with useful information are rejected anyways.

**Comment by afranke** [comment]
:cartwheeling:

**Comment by afranke** [comment]
:man_dancing:

**Comment by aditi5926** [comment]
Is this issue open yet? Can I work on this?

**Comment by saghul** [comment]
The work to restore this cannot be done externally I'm afraid.
