### ISSUE TITLE
(native) icon doesn't change when new messages arrive

### ISSUE THREAD

**Issue by tombrown86** [jitsi/jitsi-meet#6752]
It seems hasRead is incorrectly set true when new messages arrive

see _handleReceivedMessage in middleware.js

it seems to be because isOpen (from state['features/chat']) comes back as true when chat window is closed

To reproduce: open chat window, close chat window, send message from another device... icon does not change

thanks

**Comment by saghul** [comment]
@zbettenbuk can you please check?

**Comment by kaymyst** [comment]
Hi we noticed the same issue which means some participants on mobile are not seeing messages.

**Comment by SplendornetTech** [comment]
For me none of the participants are seeing any chat message, using react-native SDK

**Comment by saghul** [comment]
Should be fixed by this PR: https://github.com/jitsi/jitsi-meet/pull/7387
