### ISSUE TITLE
ios/android SDK advanced capabilities

### ISSUE THREAD

**Issue by ericavijay** [jitsi/jitsi-meet#6759]
The JitsiMeetView api seems pretty solid but has very sparse documentation of features.  I would like both documentation and help in finding the right API methods and keywords for integration into our native support app.

Here are some of the things that are unclear to me
1. How to enable/disable "Invite Others" as part of the JitsiMeetView api in options? after loading using an event listener, is it possible to do this?
2. How to enable/disable "Add a Meeting Password" similar to above
3. The setup of the options object userInfo with say builder.userInfo?.displayName seems to have no effect in iOS.  If there is someother way to set object properties - can you put that in your documentation?
4. How to get current meeting information on an active JitsiMeetView API? like - current room id, current participants etc.

Thank you for this great project.

**Comment by ericavijay** [comment]
I would add to this list something for Android as well. The simple example provided in JitsiSDKTest with Kotlin or Java is very simple to start off with. It will be great to add an example to this Kotlin and Java class of accessing the View from the JitsiMeetActivity.  For example I am trying to extend  the onConferenceTerminated  for a JitsMeetActivity launched view. Not finding this quite straightforward.

I would be happy to submit the updated JDKTest if you can help me figure this out.

Again thanks for this great community work.

Vijay

**Comment by luismachado** [comment]
@saghul how are you? I was going to create a new issue but I kinda think my question fits here: I'm trying to understand if I can, through JitsiMeetView (or any other exposed API for the iOS SDK) change stuff like mute, enable video, etc.

Basically my aim is to disable the callkit functionality inside Jitsi and have all that logic on my own app. However for that to work (i.e. to react to the callkit screen actions) I would need to be able to mute and enable/disable video from outside the SDK.

**Comment by ericavijay** [comment]
Jitsi Developers,

I have done a bit of playing around with JitsiMeet SKD for both iOS and Android.  Looks like iOS is pretty straightforward using jitsiMeetView.join and you still have plenty of control of the View either in pip or not pip mode. 

However using Android's very convenient JitsiMeetActivity.launch method you loose the ability to do custom listeners and the ability to programmatically close the "activity" or do any type of status checks. You have to use JitsiMeetView which is less recommended by the handbook https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk 

Unless I am missing something obvious, I think the SDK needs a bit of rewrite to give more capability and ability to be adopted into mainstream third party products. 

Thanks
Vijay

BTW : I have also solicited the community for help in ways they currently us the SDK and the API.

**Comment by mehul4795** [comment]
> The JitsiMeetView api seems pretty solid but has very sparse documentation of features. I would like both documentation and help in finding the right API methods and keywords for integration into our native support app.
> 
> Here are some of the things that are unclear to me
> 
> 1. How to enable/disable "Invite Others" as part of the JitsiMeetView api in options? after loading using an event listener, is it possible to do this?
> 2. How to enable/disable "Add a Meeting Password" similar to above
> 3. The setup of the options object userInfo with say builder.userInfo?.displayName seems to have no effect in iOS.  If there is someother way to set object properties - can you put that in your documentation?
> 4. How to get current meeting information on an active JitsiMeetView API? like - current room id, current participants etc.
> 
> Thank you for this great project.

You can use the `setFeatureFlag()` function of the `JitsiMeetConferenceOptions.Builder()` for enabling/disabling some features. For example, the below code disables the "Invite Others" & "Add a Meeting Password" options.
```kotlin
val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setServerURL(serverUrl)
            .setWelcomePageEnabled(false)
            .setFeatureFlag("invite.enabled", false)
            .setFeatureFlag("meeting-password.enabled", false)
            .build()
        JitsiMeet.setDefaultConferenceOptions(defaultOptions)
```
You can find all the feature flags that you can set in [this file](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js).

**Comment by ericavijay** [comment]
Hi Mehul,

Very helpful. I stumbled on this last night from https://community.jitsi.org/t/jitsi-meet-ios-sdk-inviate-enable-flag-does-nothing/26353 and have been able to use it successfully in both Android and iOS. Looks like in iOS and Android the JitsiMeetUserInfo needs to be initialized before settings parameter - had to look at the code to figure out a Class in Android and initiliazable NSObject 
 or Interface in iOS. This should go like you pointed out in defaultOptions and not the view's  "join" options or "launch" options - simple but can throw you off as both of these are are basically same types of object JitsiMeetConferenceOptions.

So instead of 

`           builder.userInfo?.email = reply_email
            builder.userInfo?.displayName = p_name
            builder.userInfo?.avatar = URL(string: avatar_url)`

One should actually create an instance

`            builder.userInfo = JitsiMeetUserInfo(displayName:p_name,
                                                 andEmail: reply_email,
                                                 andAvatar: URL(string: avatar_url))
`

and attach it to builder like

`
let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
builder.userInfo = JitsiMeetUserInfo(displayName:p_name,
                                                 andEmail: reply_email,
                                                 andAvatar: URL(string: avatar_url))} 
`

For Android the code below seems to work

`
var userInfo = JitsiMeetUserInfo()
        userInfo.email = memail
        userInfo.displayName = mdisplayName
        userInfo.avatar = URL(avatar_url.toString())
`

  In Android the JitsiMeetActivity is still mysterious to me as it does not follow the normal method overrides.  This maybe just the way Kotlin and Java work with the mixture of private methods and public, it does not seem to implement overrides when a subclass is created.

Vijay

**Comment by ericavijay** [comment]
This issue is resolved. The Android API has a sort of different approach for accessing and customizing the class.

Thanks
Vijay
