### ISSUE TITLE
New Digital Ocean instance stops working after prosody repo upgrade

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [jitsi/jitsi-meet#6761]
I started a new digital ocean droplet (https://marketplace.digitalocean.com/apps/jitsi-server) - worked fine.
Then I wanted to install the JWT plugin for jitsi: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

APT told me, that I cannot install the JWT package, due to an old version of prosody.
I then added the prosody debian repository: https://prosody.im/download/package_repository and upgraded to 0.11.

After this, jitsi stopped to work, and I get strophe 50* error messages in the browser console?

Should an upgrade to 0.11 work without problems?

**Comment by damencho** [comment]
You need to fix prosody config, storage to be `memory`.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Could you tell me in which file? I changed my ```/etc/prosody/conf.avail/myserver123.com.cfg.lua``` file, but I still get the 502 errors?

**Comment by saghul** [comment]
Plase share your prosody config file.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I found the issue, I had to add ```Include "conf.d/*.cfg.lua"``` to my prosody config file ``` /etc/prosody/prosody.cfg.lua``` (yeah, this is mentioned here:  https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md ).

Thanks!
