### ISSUE TITLE
Can i add my language to jitsi-meent by jitsi's weblate

### ISSUE THREAD

**Issue by pongsawad** [jitsi/jitsi-meet#6766]
Can i add my language(THAI) to jitsi-meent by jitsi's weblate ?

thankyou.
pongsawad.j

**Comment by luixxiul** [comment]
สวัสดี! ภาษาไทยยังไม่พร้อมใช้. หากคุณทำได้โปรดแปลจากภาษาอังกฤษเป็นภาษาไทย.

โปรดตรวจสอบ https://github.com/jitsi/jitsi-meet/tree/master/lang.

**Comment by pongsawad** [comment]
> สวัสดี! ภาษาไทยยังไม่พร้อมใช้. หากคุณทำได้โปรดแปลจากภาษาอังกฤษเป็นภาษาไทย.
> 
> โปรดตรวจสอบ https://github.com/jitsi/jitsi-meet/tree/master/lang.

ขอบคุณ @luixxiul
