### ISSUE TITLE
jibri services not running

### ISSUE THREAD

**Issue by bashokbabu** [jitsi/jitsi-meet#6768]
please check once status of jibri services

 service jibri status
● jibri.service - Jibri Process
   Loaded: loaded (/etc/systemd/system/jibri.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-05-18 20:34:01 IST; 8min ago
  Process: 20904 ExecStop=/opt/jitsi/jibri/graceful_shutdown.sh (code=exited, status=7)
  Process: 20887 ExecStart=/opt/jitsi/jibri/launch.sh (code=exited, status=143)
 Main PID: 20887 (code=exited, status=143)

May 18 20:34:01 recorder graceful_shutdown.sh[20904]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 18 20:34:01 recorder graceful_shutdown.sh[20904]:                                  Dload  Upload   Total   Spent    Left  Speed
May 18 20:34:01 recorder graceful_shutdown.sh[20904]: [149B blob data]
May 18 20:34:01 recorder systemd[1]: jibri.service: Control process exited, code=exited status=7
May 18 20:34:01 recorder systemd[1]: jibri.service: Main process exited, code=exited, status=143/n/a
May 18 20:34:01 recorder systemd[1]: jibri.service: Failed with result 'exit-code'.
May 18 20:34:01 recorder systemd[1]: Stopped Jibri Process.
May 18 20:34:01 recorder systemd[1]: jibri.service: Start request repeated too quickly.
May 18 20:34:01 recorder systemd[1]: jibri.service: Failed with result 'exit-code'.
May 18 20:34:01 recorder systemd[1]: Failed to start Jibri Process.

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
