### ISSUE TITLE
chromium allows disabling audio/camera, no warnings

### ISSUE THREAD

**Issue by fommil** [jitsi/jitsi-meet#677]
(Debian Chromium) I couldn't get jitsi to recognise my camera or audio: I'd completely forgotten that months ago I'd told the security settings to never allow website to access either. Who'd ever want to use that, right? :blush: 

It would be useful if there was some feedback to suggest that this may be the cause of the problem.

**Comment by tsareg** [comment]
@fommil This feature was implemented last week and was already merged in. Now you will get such dialog in jitsi-meet with information what went wrong when trying to access user media devices:

![Error Dialog](https://cloud.githubusercontent.com/assets/1167285/15828759/3a894556-2c19-11e6-8568-dc378435c136.png)

P.S. Please note that it's not yet available at https://meet.jit.si
