### ISSUE TITLE
Jitsi

### ISSUE THREAD

**Issue by VVSZGod** [jitsi/jitsi-meet#6770]
Hello, I have a question about jitsi. How to use jitsi to get the real-time number of people in the room for video conference. I installed it on the server independently. How to modify the source code? Thank you!

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
