### ISSUE TITLE
Powermonitor.js: Uncaught expection

### ISSUE THREAD

**Issue by pat-s** [jitsi/jitsi-meet#6775]
## Description
While running our own self-hosted Jitsi instance, we get the following popup every once in a while when the Jitsi Meet Desktop app is open.

Clicking "ok" does not seem to have any effect (neither positive nor negative) on the Jitsi service.

<img width="210" alt="image" src="https://user-images.githubusercontent.com/8430564/82326297-e1e5a580-99dc-11ea-8643-9c01a8a2f750.png">

# Environment details

Ubuntu 18.04.4

**Comment by saghul** [comment]
Please see the jitsi-meet-electron repository. This has been reported already.
