### ISSUE TITLE
Provide some way to display server load problems to end users 

### ISSUE THREAD

**Issue by arthurlogilab** [jitsi/jitsi-meet#6778]
First of kudos to all to people that made jitsi-meet possible, I use it in personal and professional use cases and it's great ! 

Sorry if this feature request is already somewhere on the tracker of the forums, couldn't find it.. sorry for the noise if it is.

**Is your feature request related to a problem you are facing?**

Yes. On some jitsi instances where the specifications and size of server is not public or where usage may vary, the quality of a conference with the same number of participants (which same network conditions) may vary. Many issues and forum posts talk about the potential limitations of running a jisti server on limited hardware and the impact it has on users when they are in conferences or when number of participants reach more than X people, which is technically fully understandable. 

**Describe the solution you'd like**

It would be really nice to have (maybe an optional) way of displaying to the end users a warning about the state of the server load when it might have an impact on their performance. For example I would imagine a low-end server that one would use for 1-to-1 call or small meetings which works fine and then when 5 people are on it and it is too loaded that it would suggest in the browser for the users to maybe move to a bigger server (which could be indicated by the admin of the instance). 

In a lot of cases varying experience on the same server causes the users to think they are having problems with their client, their ISP, etc. This type of feature would help them identify the problem. 

**Describe alternatives you've considered**

Not sure what this section if for. Maybe there could be a setting to automatically disable some features such as video with a warning such as "server overload disabling some features" ?

**Comment by KevinRoebert** [comment]
+1

**Comment by luixxiul** [comment]
@KevinRoebert you could add "+1" to the first post instead of writing so actually. thanks!

**Comment by saghul** [comment]
This would be really hard to attain, specially on a distributed infrastructure.

Different conferences will happen in different servers, so one server might have higher load but that doesn’t mean anything, since other conferences would happen in other servers due to load balancing.

With OCTO multiple bridges will be used for a single conference.

Last, in case of a DoS attack you wouldn’t want the attackers to know you’re struggling.

I see where you’re coming from with this request, but I don’t think there is a reasonable way to implement this.

**Comment by KevinRoebert** [comment]
> I see where you’re coming from with this request, but I don’t think there is a reasonable way to implement this.

Makes sense. It's not such an important feature that it would be worth a lot of manpower.

**Comment by saghul** [comment]
Thanks for understanding!

**Comment by arthurlogilab** [comment]
Maybe the description of my feature request wasn't clear. All I'm suggesting is a way to send a notification to the sessions. If that's possible then an administrator of an infrastructure could notify the users that the server (or the distributed infrastructure) is having a problem which explains the poor quality.

**Comment by arthurlogilab** [comment]
And I agree that to have a fully automated integrated solution that detects warns etc is a lot of manpower (and should be split into multiple tasks).
