### ISSUE TITLE
App frozen and unresponsive UI on Chrome

### ISSUE THREAD

**Issue by ramrami** [jitsi/jitsi-meet#6781]
## Description
---
App frozen and unresponsive UI upon entering a room on Chrome with one user (usually after 3 to 4 seconds). Can't close the browser tab, CPU is going crazy. Works fine on Firefox.

# Environment details
---
Chrome : Version 81.0.4044.138 (64 bits)
OS: macOS 10.15.3 catalina
Server: Tested on `meet.jit.si` and also with fresh docker install with `stable-4548-1` images

**Comment by paweldomas** [comment]
Is the user alone in the room or is it a conference with 2 participants?
Are both users using Chrome if not then what browser/OS/versions?
Are both audio and video turned on?
Any settings changed in the "Manage video quality" settings?

**Comment by ramrami** [comment]
@paweldomas 
- The is user alone in the room (just me testing)
- Using chrome
- Audio & Video on
- No settings changed

The defaults when you first visit meet.jit.si

**Comment by hugomejia** [comment]
Dear Jitsi team, 

I think this issue should be reopened, I'm having the exact same issue mentioned @ramrami .

Chrome version: Version 94.0.4606.71 (Official Build) (64-bit)

Th iframe just freezes and the page becomes unresponsive, even the reload button on the browser doesn't seem to work. I have to either close the tab or click "back" several times.

Thanks for addressing this.

**Comment by saghul** [comment]
Can you please open a new issue? This one is really too old.
