### ISSUE TITLE
Invite popover breaks with large URLs

### ISSUE THREAD

**Issue by vkruoso** [jitsi/jitsi-meet#6782]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

## Description
When using the invite popover, if the URL is too large, it breaks strangely. If we copy the link, it is fine, so it looks like a display error.

## Current behavior

<img width="500" alt="Screen Shot 2020-05-19 at 16 25 47" src="https://user-images.githubusercontent.com/293572/82369970-2af22580-99ee-11ea-8bae-86bc156cefc6.png">

## Expected Behavior

Show the URL correctly.

## Steps to reproduce

Go to a conference with large url, [like here](https://meet.jit.si/jidosajidosjaioijiosaueioqwueioqwjidqwjiodsdsa)

# Environment details

Any jitsi installation.

**Comment by luixxiul** [comment]
This password dialog has been reworked at #6654 and the issue has been fixed / deprecated.

**Comment by vkruoso** [comment]
Awesome. Thanks for the feedback. The new version really looks great.
