### ISSUE TITLE
Option to hide non-video participants

### ISSUE THREAD

**Issue by gravyboot** [jitsi/jitsi-meet#6789]
**Is your feature request related to a problem you are facing?**
In tile view, screen area is wasted if there are non-video participants. Especially in larger groups when there are many non-video participants.

**Describe the solution you'd like**
Enable option to hide non-video participants.

**Comment by mangmang2006** [comment]
Looks very useful. The muted or no-video device users could be minimised/hidden in the 'Speaker Stats', but apart from stats, they'll have some a similar menu like from the view window, ie, including 'kick out', 'mute audio', 'private message' etc. An icon to show their A/V muted/unmuted would also be very helpful.

**Comment by LADYBEAR7819** [comment]
> Looks very useful. The muted or no-video device users could be minimised/hidden in the 'Speaker Stats', but apart from stats, they'll have some a similar menu like from the view window, ie, including 'kick out', 'mute audio', 'private message' etc. An icon to show their A/V muted/unmuted would also be very helpful.

**Comment by abdultz** [comment]
Jitsi does not have an administrative interface. This feature cannot be implemented without an administrative interface which also requires a database of the conferences, participants and their status to be maintained at the server side.
Nonetheless, you can implement your own administration interface (a separate web application/service) which will set the required parameters on the server side, e.g. mute status of participants. The clients will periodically check the parameters and execute the commands accordingly. The clients just have to call the appropriate API call depending on the parameter. Reference for API [Jitsi Meet API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)

**Comment by gravyboot** [comment]
Thanks for the input. To clarify (though it may not matter in light of your comments) I'm not particularly interested in hiding/uhiding muted/unmuted participants, which I think may result in an overly chaotic experience for end users. 

But if I'm understanding abdultz correctly, it's not currently possible to hide non-video participants as the server can't see who is sharing video. Would it make any difference if, instead of making this the standard behavior instead of an option at the client? As long as you can still view the full participant list, I'm not sure why anyone would want to see full-size black tiles in tile view. But perhaps this goes against the original jitsi ethos, having the server watch the client status. 

Alternatively (and assuming tile view paginates over a certain number of participants, which I haven't been able to confirm) is it possible to sort the list so non-video participants are separately displayed on the last page? This would effectively solve the same problem, but not sure if it can happen without a similar administrative interface.

**Comment by abdultz** [comment]
This arrangement of the participants can be worked out in the filmstrip remote videos. Participants without videos or their camera's disabled/off can be located with associated styling class.

1. videocontainer display-avatar-with-name
2. videocontainer display-name-on-black
3. videocontainer display-avatar-only

You can write a function which can rearrange the elements in the filmstrip. Camera status change events are fired from:

1. RemoteVideo.js
2. SmallVideo.js
3. LargeVideoManager.js

You will have to carefully consider several factors such as arrival of a new participant or a participant leaving a conference. refreshLayout() will be called when the video layout has changed and elements have to be re-arranged and resized. [VideoLayout](https://github.com/jitsi/jitsi-meet/blob/master/modules/UI/videolayout/VideoLayout.js)

**Comment by mangmang2006** [comment]
Many thanks @abdultz

**Comment by ayr-ton** [comment]
This can be an option for the end-user only, there's no need to complicate with administration interface/etc.

Like, as I can choose between block visualization and not, the option to hide non-video participants as well.

**Comment by saghul** [comment]
Look what happens when you hide a participant from the UI: https://securityintelligence.com/posts/ibm-works-with-cisco-exorcise-ghosts-webex-meetings/

The security implications are complex. It's just not as simple as you might think. Thus we have no plans to make changes to our UI in this regard right now. That doesn't mean it will never happen though.

**Comment by ulflunqvist** [comment]
Any updates? Closed?

**Comment by saghul** [comment]
> Any updates? Closed?

See https://github.com/jitsi/jitsi-meet/issues/6789#issuecomment-740479735

**Comment by Uneducated-Engineer** [comment]
https://github.com/Uneducated-Engineer/BetterDiscord_HideStreamANDnon-VideoParticipants
