### ISSUE TITLE
Disable invite popover for jitsi iframe client

### ISSUE THREAD

**Issue by pgulley** [jitsi/jitsi-meet#6790]
Hello! This may be something that's already possible, but I haven't been able to find the option which would enable this behavior.

I would like to disable the popover with the invitation link from appearing at load in my application.
Should be as simple as a flag in the interfaceConfig.

**Comment by damencho** [comment]
What about removing `invite` from `TOOLBAR_BUTTONS`.

Please use the community forum when you have questions or problems before opening new issues.
