### ISSUE TITLE
Security, please?

### ISSUE THREAD

**Issue by Gahamelas** [jitsi/jitsi-meet#6791]
So I for the first time get to create a videoconference with the name I want: "Friends", and first thing, I am watching a lot of naked people I don't even know. What the heck? Are the names ID not unique for each videoconference? Anyone can pop in?

**Comment by luixxiul** [comment]
>  Are the names ID not unique for each videoconference?

No, they are not.

For increasing security, please refer information on the FAQ: https://jitsi.github.io/handbook/docs/faq#how-can-i-protect-my-meetings-with-jitsi

**Comment by Gahamelas** [comment]
https://community.jitsi.org/t/get-the-list-of-rooms/14895/68

And apparently people can trace active chat rooms names?

**Comment by luixxiul** [comment]
> those server instructions.

Actually they are not server instructions.

> 1. Create a "strong" room name.
> 2. Use a different room name for each meeting / conference you have.
> 3. Add a password to the room.
> 4. Enable "secure domain" if you are using your own instance of Jitsi.

The first three of them are written for normal non programmers people.

What am I missing here?

CC @saghul for the response to: https://community.jitsi.org/t/get-the-list-of-rooms/14895/68

**Comment by Gahamelas** [comment]
Thanks. However, creating a strong name of password has nothing to do with encryption of the data being generated during the meeting. Enabling secure domain when using the web address is not possible. As for the response to Saghul, it seems that tools exist that can trace the names of rooms. So it's easy to jump into any with a password cracker.

**Comment by luixxiul** [comment]
Sorry again, on https://community.jitsi.org/t/get-the-list-of-rooms/14895/68 I don't see anything related with tracing the names of the rooms externally.

> Please add the functions to existing mod_muc_size.lua and follow the instructions how to enable it. Maybe you want to copy mod_muc_size.lua and rename it to be save when you update jitsi and mod_muc_size.lua will be overwritten…

Maybe you wanted to refer other posts?

**Comment by saghul** [comment]
We have a more descriptive document written for everyone, even non tech people here: https://jitsi.org/security/

The meeting name is how a meeting is identified. If you choose a poor name people will find it. That’s where the use of a password kicks in.

We have just added a warning note and icon when an “unsafe” meeting name is chosen. It’s not yet deployed on meet.jit.si but will be soon.

Apologies for what happened, with the increase of traffic in our platform we have also seen an increase of individuals trying to do harm and we are putting a number of measures in place to help our users. The aforementioned one is the first of many.
