### ISSUE TITLE
localization error in lang/main-de.json

### ISSUE THREAD

**Issue by paradeiser** [jitsi/jitsi-meet#6797]
line 223
"Das Treffen wurde von einem Teilnehmer geslerrt."
should be
Das Treffen wurde von einem Teilnehmer **gesperrt**."

**Comment by saghul** [comment]
I think this one was fixed just a couple of minutes ago: https://github.com/jitsi/jitsi-meet/commit/7f1f92cdf0dfb072b6fb6aadb58349f0500d3655
