### ISSUE TITLE
Call ended on back pressed in android

### ISSUE THREAD

**Issue by Slake07** [jitsi/jitsi-meet#6803]
## Description
When I was in the call room and I pressed back pressed then my call is ended. Same as in IOS they can continue with call even on the back.

Code:

```
val defaultOptions = JitsiMeetConferenceOptions.Builder()
                        .setAudioMuted(true)
                        .setVideoMuted(true)
                        .setSubject(state.res.class_name)
                        .setToken(state.res.meeting_token)
                        .setServerURL(URL(BuildConfig.CONFERENCE_URL))
                        .setUserInfo(JitsiMeetUserInfo(ss.getJitsiUserInfoBundle()))
                        .setFeatureFlag(Constant.INVITE_ENABLED,false)
                        .setFeatureFlag(Constant.LIVE_STREAMING_ENABLED,false)
                        .setFeatureFlag(Constant.PIP_ENABLED,false)
                        .setRoom(BuildConfig.CONFERENCE_URL.plus(state.name))
                        .setWelcomePageEnabled(false)
                        .build()

                    JitsiMeetActivity.launch(activity,defaultOptions)
```

## Current behavior
Currently ongoing call is ended on navigation back pressed.

## Expected Behavior
Call should not end when user press back button. It should be on going or move to picture in picture mode.

## Possible Solution
---

## Steps to reproduce
---

# Environment details
I am using following version:

implementation('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }

**Comment by saghul** [comment]
What Android version did you test it on?

**Comment by Slake07** [comment]
I tested on android 9 and 10.

**Comment by Slake07** [comment]
> What Android version did you test it on?

I added my code for the launch screen for a call.

**Comment by saghul** [comment]
Wait, are you using the SDK or modified the app? Can you share your changes? This works ok on the app so it must be a small thing.

**Comment by Slake07** [comment]
> Wait, are you using the SDK or modified the app? Can you share your changes? This works ok on the app so it must be a small thing.

I am using SDK.. I didn't modified anything.

**Comment by Slake07** [comment]
> Wait, are you using the SDK or modify the app? Can you share your changes? This works ok on the app so it must be a small thing.

Did I miss anything here?

**Comment by saghul** [comment]
Not really, it should work already. Can you reproduce the problem with the SDK samples?

**Comment by Slake07** [comment]
> Not really, it should work already. Can you reproduce the problem with the SDK samples?

Let me try with the sample. Then I will get back to you.

**Comment by Slake07** [comment]
> > Not really, it should work already. Can you reproduce the problem with the SDK samples?
> 
> Let me try with the sample. Then I will get back to you.

I tested sample. and its working fine in it.

Then I compare with my code. and I removed all the flags and methods. and use just below things:

```
val defaultOptions = JitsiMeetConferenceOptions.Builder()
//                        .setAudioMuted(true)
//                        .setVideoMuted(true)
//                        .setSubject(state.res.class_name)
                        .setToken(state.res.meeting_token)
                        .setServerURL(URL(BuildConfig.CONFERENCE_URL))
//                        .setUserInfo(JitsiMeetUserInfo(ss.getJitsiUserInfoBundle()))
//                        .setFeatureFlag(Constant.INVITE_ENABLED,false)
//                        .setFeatureFlag(Constant.LIVE_STREAMING_ENABLED,false)
//                        .setFeatureFlag(Constant.PIP_ENABLED,false)
                        .setRoom(BuildConfig.CONFERENCE_URL.plus(state.name))
                        .setWelcomePageEnabled(false)
                        .build()

                    JitsiMeetActivity.launch(activity,defaultOptions)

And now it's working fine.

So what should I do if I want to mute the audio, video and also set other flags?
```

**Comment by alpharays05** [comment]
back button is still ending the meet, even after adding setFeatureFlag("pip.enabled", true)
please help
