### ISSUE TITLE
On the latest security option window password cannot be set with mouse 

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6804]
**Description:** Password cancel / add elements overflow from the security options modal window. This ~~will be~~ is an issue for other languages than English. As this makes it impossible to set a password with a mouse (you can set the password by hitting the enter key), this needs a quick fix.

**Steps to reproduce the issue:**

1. `git fetch upstream && git rebase upstream/master`
2. `rm -rf node_modules/ && npm install && make dev`
3. Open `https://localhost:8080/randomRoom`
4. Set the language to `Danish` for example.
5. Try to set your password with mouse (Do not use the enter key on your keyboard)

**Expected result:** A password should be able to set

**Actual result:** A password cannot be set because `Add` element overflows the window.

![Clipboard02](https://user-images.githubusercontent.com/3362943/82470495-f9905d00-9ab4-11ea-919f-1677e70d1eb1.png)

**Environment details:** On the latest master (https://github.com/jitsi/jitsi-meet/commit/0598e7369b2dfac9c11637c3c356cf634466430f)

This is a follow-up to #6654

**Comment by obfusk** [comment]
This seems to have been fixed by #6815.
