### ISSUE TITLE
Call didn't end when the provider end call from their side

### ISSUE THREAD

**Issue by Slake07** [jitsi/jitsi-meet#6809]
## Description
When a call was ongoing with the provider. In which, many others are also joined. Some from the web, some from ios and some from android. During a call, when the provider ends the call, All other joined members call also ended automatically but in android, It's not working.

Code to start the call:

```
val defaultOptions = JitsiMeetConferenceOptions.Builder()
                        .setAudioMuted(true)
                        .setVideoMuted(true)
                        .setSubject(state.res.class_name)
                        .setToken(state.res.meeting_token)
                        .setServerURL(URL(BuildConfig.CONFERENCE_URL))
                        .setUserInfo(JitsiMeetUserInfo(ss.getJitsiUserInfoBundle()))
                        .setFeatureFlag(Constant.INVITE_ENABLED,false)
                        .setFeatureFlag(Constant.LIVE_STREAMING_ENABLED,false)
                        .setFeatureFlag(Constant.PIP_ENABLED,false)
                        .setRoom(BuildConfig.CONFERENCE_URL.plus(state.name))
                        .setWelcomePageEnabled(false)
                        .build()
JitsiMeetActivity.launch(activity,defaultOptions)
```

## Current behavior
When a call was ongoing with the provider. In which, many others are also joined. Some from the web, some from ios and some from android. During a call, when the provider ends the call, All other joined members call also ended automatically but in android, It's not working.

## Expected Behavior
After provider ends call from their side then call should also end from the user side automatically. 

## Possible Solution
---

## Steps to reproduce
---

# Environment details
I mostly tested on android versions: 8, 9, 10.
I am using jitsi SDK without any modification:

implementation('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }

**Comment by saghul** [comment]
What is this provider you mention?

The SDK has no mechanism to leave a meeting on a remote command, every participant needs to leave the meeting by themselves, unless you implement some backend service yourself and trigger a local leave based on some remote action.

**Comment by Slake07** [comment]
> What is this provider you mention?
> 
> The SDK has no mechanism to leave a meeting on a remote command, every participant needs to leave the meeting by themselves, unless you implement some backend service yourself and trigger a local leave based on some remote action.

Provider means who start the conference. 
The main issue is when call ended, I didn't get any callback for that in my screen where I launch
`JitsiMeetActivity.launch(activity,defaultOptions)`

**Comment by Slake07** [comment]
@saghul Can you help me out on this?

**Comment by saghul** [comment]
You will only get the onConferenceTerminated method called when *you* press hangup. Not when the person who created the conference does it.

**Comment by Slake07** [comment]
@saghul Thanks. Can I programmatically end a call from another activity or fragment?

**Comment by Slake07** [comment]
@saghul It will be helpful if you help me out. As I need it on urgent basis.

**Comment by abdultz** [comment]
You will have to implement a service on the provider side. The clients will periodically check the service for commands. A JS file can be sent in Jitsi Meet app which will periodically call the service. If an exit command is sent to the client by the service, the client can be programmed to call:
api.executeCommand('hangup');
Reference: [Jitsi Meet API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)

**Comment by Slake07** [comment]
> You will have to implement a service on the provider side. The clients will periodically check the service for commands. A JS file can be sent in Jitsi Meet app which will periodically call the service. If an exit command is sent to the client by the service, the client can be programmed to call:
> api.executeCommand('hangup');
> Reference: [Jitsi Meet API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)

But this command is compatible on the android side? 
`api.executeCommand('hangup');`

**Comment by saghul** [comment]
That API is for the iframe, won’t work on mobile.

We don’t currently have a an intent to finish a call but you could easily add that, and call leave() in the Jitsi activity.

If you feel like going in this direction we can probably incorporate the work in the SDK so others can also benefit from it.

**Comment by Slake07** [comment]
> That API is for the iframe, won’t work on mobile.
> 
> We don’t currently have a an intent to finish a call but you could easily add that, and call leave() in the Jitsi activity.
> 
> If you feel like going in this direction we can probably incorporate the work in the SDK so others can also benefit from it.

Currenly, I don't have much time due to commitment. So it will be better if you can add this in your SDK.

**Comment by saghul** [comment]
Well, then you’ll have to wait. It’s not like I have all the time in the world either.

**Comment by l3d00m** [comment]
> It will be helpful if you help me out. As I need it on urgent basis.

> So it will be better if you can add this in your SDK.

Requesting support like this on an open-source project is kinda rude tbh. If you need the feature asap, implement it yourself. If you need support, you can use the forums at https://community.jitsi.org

Github isn't a platform to ping individual members for support for your specific problem (I'm not in the Jitsi Team myself, I'm just kinda astonished about the attitude).

**Comment by Slake07** [comment]
> > It will be helpful if you help me out. As I need it on urgent basis.
> 
> > So it will be better if you can add this in your SDK.
> 
> Requesting support like this on an open-source project is kinda rude tbh. If you need the feature asap, implement it yourself. If you need support, you can use the forums at https://community.jitsi.org
> 
> Github isn't a platform to ping individual members for support for your specific problem (I'm not in the Jitsi Team myself, I'm just kinda astonished about the attitude).

I am really sorry for my disrespectful comments. There was nothing about my attitude. I replied without thinking anything as I was in hurry. Sorry again for my such comment. @saghul Sorry to you.

**Comment by JaspreetiOSDev** [comment]
Is any update on this? In iOS side we are not getting invoke conferenceTerminated method while call ended by web client

**Comment by kaswan24** [comment]
Need support for android. No way to programmatically end call yet

**Comment by saghul** [comment]
@kaswan24 There is: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#broadcasting-actions see the HANG_UP action.

**Comment by kaswan24** [comment]
@saghul  thanks for the quick help, just tried everything before your answer and I ended up with extending JitsiMeetActivity and doing some modifications there to leave call, didn't knew about your solution. I had a separate concern related to PiP mode for which I needed to take this step, I have raised a separate issue for PiP yesterday
