### ISSUE TITLE
No response of External API's "executeCommand" in Angular 9

### ISSUE THREAD

**Issue by pongsawad** [jitsi/jitsi-meet#6810]
Hi, ALL
No response of External API's "executeCommand" in Angular 9

Pongsawad.J
Thx.

**Comment by saghul** [comment]
We need many more details here. What command are you running, how? How is angular relevant here? What do you see in the browser console?

**Comment by pongsawad** [comment]
> We need many more details here. What command are you running, how? How is angular relevant here? What do you see in the browser console?

ok, i'm sorry for missing details.

i'm using external api by download it to local and import to angular app at 'scripts' of angular.json
[https://meet.jit.si/external_api.js](https://meet.jit.si/external_api.js)

**then,**
i use embed api from tutorial
[https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#api](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#api)

**but** the 'domain' config, i not use 'meet.jit.si'. use my server instead.
this is my component's code

_.html_
`<div #meet></div>`
`<input [(ngModel)]="nickName" type="text">`
`<button click="executeAnyCommand()">test</button>`

_.ts_
`@ViewChild('meet') meet: ElementRef;`
`public nickName = '';`
`private api: any;`
`ngAfterViewInit(): void {`
    `     const options = {
      roomName: 'loremipsum',
      parentNode: this.meet.nativeElement,
    };`
    `     const domain = 'myjitsimeetserver';`
    `     const api = new JitsiMeetExternalAPI(domain, options);`
 `}`
`public changeNickname() {`
    `console.log(this.api);  //it's work.`
   ` this.api.executeCommand('displayName', this.nick); //it's not work.`
`}`

**i can use all function in iframe**.
it's about voice setting, camera setting, profile setting or everything etc. that i can.

**last,**
i'm trying to controll iframe with 'executeCommand' but it's not work.
..commands 'displayName' , 'toggleAudio' , 'toggleVideo', 'toggleChat' , etc. that not work.

**On the other hand**
Pure Javascript with External API , it's can be work with 'executeCommands'.

Pongsawad.J
sorry about my english.
thank for your response @saghul

**Comment by voidek-work** [comment]
@pongsawad
> `const api = new JitsiMeetExternalAPI(domain, options)`

How can this work? If instead of a class field it is written to a constant

**Comment by Echolon** [comment]
@saghul does the feedback help you?

**Comment by saghul** [comment]
Oops, I had missed the reply.

@pongsawad You need to wait for the joined event (videoConferenceJoined) before you can execute the commands.
