### ISSUE TITLE
From the community: Custom configuration on interface_config.js overwritten

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#6811]
From https://community.jitsi.org/t/how-to-safely-update-the-server/58245

> Our jitsi install is now running smoothly. Last time I tried to update the server (apt-get upgrade) it overwrote a lot of config files and the server went down for our customers!
> 
> What is considered a safe way to update a jitsi server without loosing our configuration?

I myself also have often experienced the same kind of stuff when it comes to running `apt upgrade`.

**Describe the solution you'd like**:

Setting up custom configuration files, in order to overwrite settings applied with default configuration files.

When you would like to apply your own customization, you would just configure `user.config` which should include only necessary changes, instead of applying settings to default configuration files directly.

In this way you could prevent your customization from being overwritten every time when `jitsi-meet` is upgraded.

**Describe alternatives you've considered**: N/A

**Comment by saghul** [comment]
This limitation has been in place for a long time now. It affects interface_config.js but not config.js.

**Comment by MagicFab** [comment]
Marking as duplicate of  #6279, it describes workarounds and has devs involved.

**Comment by luixxiul** [comment]
Thanks for checking! Closing in favor that.
