### ISSUE TITLE
Change Kick out popup message in android

### ISSUE THREAD

**Issue by Slake07** [jitsi/jitsi-meet#6813]
## Description
I want to change message in popup of knockout. Currently Its showing like below:

![IMG_0357](https://user-images.githubusercontent.com/3199539/82552174-3e80c600-9b7f-11ea-9a08-d0419baf79a4.jpg)

You can see in the above image. I want to change that message. I couldn't find any method related to that.

# Environment details
Current SDK version:

implementation('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
