### ISSUE TITLE
User video off options for moderator

### ISSUE THREAD

**Issue by SlalomJohn** [jitsi/jitsi-meet#6814]
Need the option to "Turn off the video" to the user by the moderator.

**Comment by Echolon** [comment]
I will close this by referencing to #6664

**Comment by SlalomJohn** [comment]
This is not dublicate! On 6664 issue "unmute sound", but me issue - "video off"

**Comment by luixxiul** [comment]
Still not quite sure what you mean by below either:

> "Turn off the video" to the user by the moderator.

Is this the option to give the moderator to disable the video displayed from the participants?

Please elaborate more. Use cases, what to establish, on which occasions this function would be useful. Thanks!

**Comment by luixxiul** [comment]
Also, please update the title too- "Video off" does not tell a lot about your suggestion either.

**Comment by SlalomJohn** [comment]
Need option as sound "mute" - but for user video.
Moderator can disable the video to the user.

**Comment by Echolon** [comment]
@luixxiul @SlalomJohn 

Yes, its not an actual duplicate, but the request is hardly close to moderation options. So mentioning in the more general issue should be enough. We need to keep track on tasks and the high amount of issues, so I think there is no real value to keep this open. Its not forgotten, if you close it and mention it in the previous post.

**Comment by SlalomJohn** [comment]
OK

**Comment by Echolon** [comment]
Everyone agrees to close?

There are more than 500 open issues, we need to accumulate.

**Comment by luixxiul** [comment]
I'd let this open and wait to see if some idea on this stuff eventually comes upon.... if not stale bot will take care of that.

IMHO having many open issues are not problem itself, it is keeping them unorganized that is the problem.

**Comment by JWCS** [comment]
I found this looking for something else, perhaps.
FWIW, being able to turn off certain video streams coming to me, if it's a matter of bandwidth, would be useful. When I (or another) is the one on low bandwidth, but I chiefly only want to pay attention to the 2-3 critical people in the meeting, I can focus on them & not the other viewers (while they can still see everyone if they have the bandwidth).
Although I interpret this posting as requesting a global turn/mute off of video, denying all users the video of another person.

**Comment by SlalomJohn** [comment]
I believe that they did not make the option to disable the video by moderators in vain.

**Comment by skolmer** [comment]
This will allow a moderator to disable the camera of other participants. It is similar to mute audio but for video.
https://github.com/jitsi/jitsi-meet/pull/8630

**Comment by damencho** [comment]
Added with 23bb824731034155e0fde409d3878523bdd1fddd thanks @skolmer for the contribution.

**Comment by keunes** [comment]
Guess this can be closed now, given #8630?
