### ISSUE TITLE
End call programmatically in android

### ISSUE THREAD

**Issue by Slake07** [jitsi/jitsi-meet#6817]
## Description
How can I end ongoing call from another activity or fragment or service? I want to end from service.
Currently, there are no way I find which can help to end call programmatically. Below are code which I used for start calling screen:

```
val defaultOptions = JitsiMeetConferenceOptions.Builder()
                        .setAudioMuted(true)
                        .setVideoMuted(true)
                        .setSubject(state.res.class_name)
                        .setToken(state.res.meeting_token)
                        .setServerURL(URL(BuildConfig.CONFERENCE_URL))
                        .setUserInfo(JitsiMeetUserInfo(ss.getJitsiUserInfoBundle()))
                        .setFeatureFlag(Constant.INVITE_ENABLED,false)
                        .setFeatureFlag(Constant.LIVE_STREAMING_ENABLED,false)
                        .setFeatureFlag(Constant.PIP_ENABLED,false)
                        .setRoom(BuildConfig.CONFERENCE_URL.plus(state.name))
                        .setWelcomePageEnabled(false)
                        .build()
JitsiMeetActivity.launch(activity,defaultOptions)
```
# Environment details
I am using jitsi SDK without any modification:

implementation('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }

**Comment by abdultz** [comment]
You can use:
api.executeCommand('hangup');
Reference: [Jitsi API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)

**Comment by Slake07** [comment]
Is 

> You can use:
> api.executeCommand('hangup');
> Reference: [Jitsi API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)

Is this android compatible code?

**Comment by saghul** [comment]
Please edit #6809 instead of opening a new issue.
