### ISSUE TITLE
Android: Both "Cancel" and "Rejoin now" buttons have same effect in "You have been disconnected" dialog

### ISSUE THREAD

**Issue by bluikko** [jitsi/jitsi-meet#6826]
## Description
Note: currently some mobile users have problems with my docker-jitsi-meet as described in https://github.com/jitsi/jitsi-meet/issues/6520#issuecomment-632482984 and it may affect this issue.

When attempting to join a room on on-prem and connection fails the "You have been disconnected. You may want to check your network connection. Reconnecting in x sec..." dialog is displayed.
The dialog has buttons "Cancel" and "Rejoin now" but both of them have same effect: the user is returned to the "Enter room name" screen.

## Current behavior
Pressing "Rejoin now" returns the user to "Enter room name" screen, similarly to "Cancel" button.

## Expected Behavior
Pressing "Rejoin now" should try to reconnect to the server.

## Possible Solution
In one previous problem with the mobile app the problem of unexpected behavior was fixed after docker-jitsi-meet was updated. This leads me to believe that the behavior of the mobile app is highly dependent on the server. Since in this case some mobile users have problem connecting to docker-jitsi-meet I cannot say for sure that the behavior would not be caused by problems at server side.

However it is confusing that both buttons do the same action.

## Steps to reproduce
- Enter room name to join.
- Press "CREATE / JOIN".
- Connection fails, "You have been disconnected" dialog is presented.
- Press "Cancel" - dialog disappears, user is returned to "Enter room name" screen.
- Press "Rejoin now" - dialog disappears, user is returned to "Enter room name" screen.

# Environment details
docker-jitsi-meet 4548-1 modified for Traefik v1

20.2.3 build 4129209 Android

**Comment by saghul** [comment]
Do you have a publicly available server that exhibits this problem?

**Comment by bluikko** [comment]
I believe any server can be made a test case by messing up the SSL certificate, do not send certificate chain. After adding the CA certificates the server works now so no more "You have been disconnected" dialog.

**Comment by ijoshivaibhav** [comment]
Yes i am facing same issue

**Comment by bluikko** [comment]
@ijoshivaibhav Have you checked your website with https://whatsmychaincert.com/ ?
