### ISSUE TITLE
Chrome tab hangs when closing sharing / starting with audio sharing

### ISSUE THREAD

**Issue by paketep** [jitsi/jitsi-meet#6828]
## Description
When I open screen sharing, it works, but when I stop sharing chrome hangs and I have to kill the process.

If I try to open screen sharing with audio sharing, it hangs as well.

Unrelated, I know, but the option should be given to audio share when sharing just one window.

---

## Current behavior
Unusable. I can't use it to teach

---

## Expected Behavior
Well, it should not hang, screen share and audio share.

---

## Possible Solution
Absolutely no idea.

---

## Steps to reproduce
Share complete screen with audio. Boom.

---

# Environment details
Standard Windows 10, Chrome up to latest version (just updated).

---

Thanks.

**Comment by jallamsetty1** [comment]
This is a chrome bug but I can't seem to reproduce it on my Win10.
