### ISSUE TITLE
Choose camera in multi-camera mobile devices

### ISSUE THREAD

**Issue by mjk-gh** [jitsi/jitsi-meet#6829]
Please let people choose from a list of all available cameras on a
multiple-camera mobile device.

Example of an open-source camera app that has this ability: OpenCamera:

  https://opencamera.sourceforge.io/
  (Available on F-Droid)

It can also determine if a camera is a front- or back-camera. As of 1.48.1,
it has 1 flip front/back icon (alas, it doesn't remember which back camera
was selected last) and directly above that icon, it has another icon, which
enables you to cycle through all availble back-cameras (or probably front-
cameras, if you had multiple of those and were in front-camera mode) by
pressing it shortly. One of my back-cameras gets listed under 2 different IDs,
but I can live with such a small bug.

Suggestion:

Add one icon to the main screen, between the camera on/off icon and the
overflow menu (3 vertical dots); I think there should be just enough space
left to press all buttons comfortably, even on devices with a smaller screen.
  Short-pressing this new icon acts as "toggle camera between (last selected)
front-camera and (last selected) back-camera", while long-pressing it opens
a list of cameras for the current mode (front or back), with their name (if
available) and their IDs, e.g.

  3: Back camera, ultra-wide
  4: Back camera, normal
  5: Back camera, tele
  6: Back camera, &lt;unknown&gt;

and if in front-camera mode, the list would look similar:

  1: Front camera, normal
  2: Front camera, eye lash mites analysis mode

Thanks for your consideration!

**Comment by rananajam1** [comment]
Hey @mjk-gh did you find a solution for this?

**Comment by mjk-gh** [comment]
Alas, not yet.

As soon as I find some time, I am going to (re-)visit
- Riot
- Jami
- Wire

and check out their conferencing practicability, including
selection of cameras.

If you don't mind giving away your telephone number, you
could also try "Signal".

**Comment by rananajam1** [comment]
Wonderful. Thanks man @mjk-gh

**Comment by mjk-gh** [comment]
Just tried to narrow down how OpenCamera selects different cameras
and hoped that I could give some hints to the Jitsi developers on how
to copy the appropriate code and/or algorithm from OpenCamera.

Alas, it seems that while OpenCamera uses the official Android
APIs android.hardware.camera and android.hardware.camera2,
Jitsi Meet /claims/ to use android.hardware.camera in their
Manifest file, but instead uses ... I don't know, I could not identify
it, it's all some JavaScript black magic.

I hope one of these days someone takes pity on us "poor" :-} multi-
camera users, because the default non-wide-angle back camera
picked on my phone is really annoying. :-/

Also: Why is toggling between back and front camera not on a
button/icon (be it short-tap or long-tap), but in an extra popup
under "More options ..."? Maybe I should open an extra issue
for that ...
