### ISSUE TITLE
New "lobby" feature breaks live streaming

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#6831]
I updated to latest debian unstable to test out the new features (looking good - way to go) and I noticed that I couldn't live stream any longer.

After digging around some I found the problem only occurs when the prejoinPageEnabled: true, is set.

Hope this helps.

**Comment by saghul** [comment]
That is fixed in https://github.com/jitsi/jibri/commit/73de52da8936130c2ef56f53bef67cbbe5bf2451 are you running the latest jibri?

@damencho are we generating nightlies for jibri too?

**Comment by pdarcos** [comment]
I'm running 8.0-14-g0ccc3f6-1

**Comment by pdarcos** [comment]
I just changed to unstable repo and indeed I have a newer version installed now

jibri 8.0-30-g73de52d-1

I'll test that one out and report back.

Thanks

**Comment by pdarcos** [comment]
I can confirm that updating to 73de52d fixed the problem.

Thanks
