### ISSUE TITLE
Installing package jitsi-meet-prodogy, code doesn't handle hostname correctly

### ISSUE THREAD

**Issue by linuxmagic-mp** [jitsi/jitsi-meet#6833]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

When installing jitsi-meet-prosody_1.0.4074-1_all.deb, you are prompted for a hostname.  There are no dependency issues, and only prosody installed.  Only problem, when attempting to generate files, instead of using the hostname as provided, you instead end up with a return value 'ok' being used where the hostname should be.. eg, it creates.. 

auth.ok.pem instead of auth.<hostname>.pem

Also, by looking at the postinst for this package, it appears to have dependencies on other packages, which aren't listed as dependencies.  Eg, 

        # try to get host from jitsi-videobridge
        db_get jitsi-videobridge/jvb-hostname

       db_get jicofo/jicofo-authuser

## Current behavior
---

Uses the return value of "ok" as the hostname, when creating files

## Expected Behavior
---

Use the value for 'hostname' entered during package installation

## Possible Solution
---

## Steps to reproduce
---

Install package without any other jitsi packages installed

# Environment details
---

**Comment by linuxmagic-mp** [comment]
Possible solution:
Instead of.. 
        db_get jitsi-videobridge/jvb-hostname
        if [ -z "$RET" ] ; then
            # server hostname
            db_set jitsi-videobridge/jvb-hostname "localhost"
            db_input critical jitsi-videobridge/jvb-hostname || true
            db_go
        fi
        JVB_HOSTNAME="$RET"
.. use.. 
        db_get jitsi-videobridge/jvb-hostname
        if [ -z "$RET" ] ; then
            # server hostname
            db_set jitsi-videobridge/jvb-hostname "localhost"
            db_input critical jitsi-videobridge/jvb-hostname || true
            db_get jitsi-videobridge/jvb-hostname
            db_go
        fi
        JVB_HOSTNAME="$RET"

This fixes the issue..

**Comment by linuxmagic-mp** [comment]
Of course, dependencies should be updated..

**Comment by damencho** [comment]
There is no dependencies to add. The idea is to keep packages separate so they can be installed individually on different machines and in the same time be installed on the same machine together without asking the same input for every package.
As first is jvb and it sets the hostname we use it in the rest to obtain the value 
https://github.com/jitsi/jitsi-meet-debian-meta/blob/832572a62090731796dce2c07f4ee2e0beb7bbba/control-tmpl#L12

**Comment by linuxmagic-mp** [comment]
It seems that IF you expect values that are created by the package jicofo and jitsi-videobridge, the package jitsi-meet-prodogy SHOULD have a dependency, other wise you will have to fix the packaging scripts to handle conditions when those packages are NOT installed, but simply put.. that package won't work unless you have the other packages installed.  Of course, you can still handle the case where you don't have to ask the same input for each package.. for the record, you are asking right now for each package, because the packaging scripts are broken as well. 

AS well, if you put the dependency in, this will save a LOT of support questions. 

If they install the videobridge packages first, because the dependencies require it, only that first package will ask for the hostname.

**Comment by damencho** [comment]
Why you thing they are broken. Installation of jitsi meet works without problems on latest 2 LTS Ubuntu and Debian 10, 9 ...

**Comment by linuxmagic-mp** [comment]
This isn't about whether 'jitsi' is broken, it is the package design that is broken. A package cannot reference elements of another debian package, if there is no dependency, unless the package can handle that situation.  If you install JUST this package, it creates files with the WRONG naming convention..

**Comment by damencho** [comment]
I see what you mean. The connection between packages is the debconf jitsi-videobridge/jvb-hostname. 
If you have a proposal on how to do that in a way so packages can be installed separately without dependency between them and install them on the same machine to work as they do today when installing the meta package, feel free to open PRs in the different repositories.
https://github.com/jitsi/jitsi-meet-debian-meta
https://github.com/jitsi/jitsi-videobridge/tree/master/debian
https://github.com/jitsi/jicofo/tree/master/debian
https://github.com/jitsi/jitsi-meet/tree/master/debian
