### ISSUE TITLE
jitsi-videobridge ignoring SIP settings regarding AWS harvestore??

### ISSUE THREAD

**Issue by linuxmagic-mp** [jitsi/jitsi-meet#6835]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
In the jitsi-videobridge sip connection settings, we see.. 

org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true

However, on startup we still see.

2020-05-22 11:21:08.117 INFO: [20] org.ice4j.ice.harvest.StunMappingCandidateHarvester.discover: Discovered public address 104.128.144.12:33683/udp from STUN server 52.60.135.22:443/udp using local address 104.128.144.12:0/udp

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
I've answered you in the other issue.

Both are different things 

Please when you have questions or problems use the community forum before opening new issues.
