### ISSUE TITLE
Not able to handle call abort in android SDK

### ISSUE THREAD

**Issue by aemssid** [jitsi/jitsi-meet#6842]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
When call is disconnected by host of meeting. Call automatically disconnected but it creates two task in recent app stack. 

1. JitsiVideoCall task
2. Parent application task

## Current behavior
1. JitsiVideoCall task didn't cleared after call disconnecting call automatically. If user select this task from recent apps he will join call again while call was ended already

## Expected Behavior
1. The task containing Jitsi video call activity should be cleared out from stack so user can't enter again into conference.

## Possible Solution
1. Activity launching flag issue

## Steps to reproduce
1. Start the conference
2. Enter in PIP mode
3. End Conference.
4. Check recent apps

# Environment details
I mostly tested on android versions: 8, 9, 10.
I am using jitsi SDK without any modification:

implementation('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }

**Comment by BC-M** [comment]
Got the same issue. 

When ending the call via the hang up button, the app is minimized. As soon as you bring it back to the front, the call is started again.

@aemssid Have you been able to solve the problem?
