### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by estiloinfo** [jitsi/jitsi-meet#6847]
HI, i actualize main-es.json and main-esUs.json, i attach the complete files and patch. I you want update de repo.

But main-es.json not change text "You ar the only in the meeting" and "Invite more people" I did not find how to fix it.

Regards

[patch.zip](https://github.com/jitsi/jitsi-meet/files/4671964/patch.zip)
[lang.zip](https://github.com/jitsi/jitsi-meet/files/4671966/lang.zip)

**Comment by saghul** [comment]
Can you please make the changes a proper pull request?

**Comment by luixxiul** [comment]
@estiloinfo if you not sure how to, I could do in favor of you 😄

**Comment by estiloinfo** [comment]
Ok, i dont know that function. Thanks. I make pull request!!!

**Comment by luixxiul** [comment]
> Can you please make the changes a proper pull request?

@saghul actually localization PRs are slowly but surely getting piled up. https://github.com/jitsi/jitsi-meet/pulls?q=is%3Apr+is%3Aopen+label%3Alocalization

If nothing blocks let's just merge them before they gets outdated. New features are coming and they will be outdated sooner or later.

If something blocks such as CLA stuff, then would you please notice PR openers about that? I could not do that task for you as I am not able to access to that information, obviously.

**Comment by estiloinfo** [comment]
I understand 
If you want push the patch, i approved of the action. 
This are the correct files
[lang.zip](https://github.com/jitsi/jitsi-meet/files/4672547/lang.zip)

**Comment by luixxiul** [comment]
https://github.com/jitsi/jitsi-meet/pull/6850 is the correct PR, right?

**Comment by luixxiul** [comment]
CC @damencho as well based on  https://github.com/jitsi/jitsi-meet/issues/5869#issuecomment-612145925

> We advised people to do PRs for translations for the time being till we finish the process of setting up a new translation service.

Would you please have a look at https://github.com/jitsi/jitsi-meet/issues/6847#issuecomment-633109812 ?

**Comment by saghul** [comment]
Thanks for the reminder @luixxiul I’ll go through those PRs.

**Comment by luixxiul** [comment]
@saghul thank you in advance 😄
