### ISSUE TITLE
Android call getting dropped after few sec of joining with self host

### ISSUE THREAD

**Issue by subhendukundu** [jitsi/jitsi-meet#6852]
Description

With the latest update calls are getting dropped around 10-20s of joining with android 2.8.2 SDK. Which used to work with 2.8.0 last time I checked with OnePlus 6. Not sure if device specific issue.
---

## Current behavior
Call is getting dropped after few sec of joining. I have tried with two person call. As soon as the other person join the call, with in few sec call get dropped with popup saying "Unfortunately, something went wrong. We're trying to fix this. Reconnecting in 10 sec...".

## Expected Behavior
The call supposed to continue as before.

## Steps to reproduce
Clone the repo.
mom install
npx react-native run-android

Goto setting add a self hosted url which is working on browsers
Paste the url to join the meeting.
Connects to meeting.
Disconnects in few sec.

# Environment details
Mac 10.15.4
Node v14.1.0
Android v10

**Comment by usamawork61** [comment]
@subhendukundu how did you fix it?
