### ISSUE TITLE
Recording individual AV streams

### ISSUE THREAD

**Issue by contrapunctus-1** [jitsi/jitsi-meet#6853]
I've been trying to make a podcast, and I avoid using non-free software as far as possible. Currently I use Jitsi Meet + vokoscreen (screen recorder), and use a video editor to get a mix of full views (Jitsi Meet) and tile views. (screen recording)

It would help my use a great deal, if Jitsi Meet could record individual streams of each member. It would open up a lot more possibilities for the final video, and I wouldn't have to resort to using hacks like screen recording.

Ideally, this would be stored locally for the person recording, but I can understand if cloud storage is a necessary evil in this situation (for reasons of bandwidth/latency). Cloud storage space may become a limiting factor, however, since I imagine this would consume `(* usual-size number-of-members)` storage. Maybe record each person's stream locally to their own devices?

**Comment by contrapunctus-1** [comment]
😕

**Comment by contrapunctus-1** [comment]
Still desired. 🙁

**Comment by saghul** [comment]
Sorry I think we have missed this. We have no plans to implement this, sorry.
