### ISSUE TITLE
Please update or remove the YouTube Ubuntu 16.04 LTS JitsiMeet tutorial

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jitsi-meet#6855]
It appears many people are still using the tutorial at https://www.youtube.com/watch?v=8KR0AhDZF2A

This tutorial uses Ubuntu 16.04 LTS as the base install and has important differences with the current documentation.

It would be very helpful to add a note in its description about this, remove the tutorial and/or produce another one following the current recommended install instructions.

**Comment by luixxiul** [comment]
This should be taken care of too:
https://github.com/jitsi/handbook/blob/399f90d1481300cb7da350a7b4b02123957d2b93/docs/devops-guide/videotutorials.md#installing-jitsi-meet-on-your-own-linux-server
