### ISSUE TITLE
Toggle Full Screen, Raise Hand, etc. via Jitsi Meet API

### ISSUE THREAD

**Issue by yeah** [jitsi/jitsi-meet#6858]
I've posted about this [in the forums](https://community.jitsi.org/t/toggle-full-screen-raise-hand-etc-via-jitsi-meet-api/32945) because I wasn't sure I was missing something. It seems that this is indeed a missing feature, so I am creating a feature request.

In my app, I’d like to replace all Jitsi toolbar icons with my custom UI outside of the iFrame. Therefore, I am missing `api.executeCommand` calls to toggle full screen, raise a hand, open settings, etc. – basically everything that is available via the native Jitsi Meet UI, so it can be replaced by my custom UI in order to match its style and UX concepts.

I'd like to try and propose a PR, but I am new to the project. Maybe someone can help me out. This is what I have: Extend the commands here:

https://github.com/jitsi/jitsi-meet/blob/2e2d40c1d0c288d37551654a4f84f124d501179b/modules/API/external/external_api.js#L29

Then, the command gets passed to `this._transport.sendEvent()` by `executeCommand()`:

https://github.com/jitsi/jitsi-meet/blob/2e2d40c1d0c288d37551654a4f84f124d501179b/modules/API/external/external_api.js#L637

However, I am not quite sure what  `_transport` is and where the actual handling of `sendEvent()` happens. Any pointers are highly appreciated.

**Comment by yeah** [comment]
This should probably be tagged as *feature request* and *api*, but I can't seem to do that myself.

**Comment by luixxiul** [comment]
thanks for the suggestions 😄

**Comment by luixxiul** [comment]
The one PR is ready:
- https://github.com/jitsi/jitsi-meet/pull/6765 - `Toggle raise hand API`

Also: https://github.com/jitsi/jitsi-meet/pull/6788 - `Adding isSharingScreen() to external API`

I could not find a PR to implement full screen toggle API.

**Comment by yeah** [comment]
Thanks, this is very helpful!

**Comment by boamaod** [comment]
Do you think there should be also an event on hand position change and maybe also a property to detect if the hand is up?

**Comment by sretika** [comment]
It's not documented, but when a hand is raised, there will be a new participant property created. 
i.e. room.participants["<participant_id>"]._properties.raisedHand = true;

**Comment by akiannillo** [comment]
any news on this? It could be very very useful.

**Comment by saghul** [comment]
No specific news. We do take PRs implementing those though!

**Comment by akiannillo** [comment]
I would like to in my spare time, but I don't even know where to start. Any suggestions/indications?
