### ISSUE TITLE
Toggle mirroring of own camera image

### ISSUE THREAD

**Issue by ruedigerkupper** [jitsi/jitsi-meet#6863]
Jitsi meet, like other video conferencing solutions, mirrors the user's own camera image and swaps left and right to make her look like in a mirror. This is very convenient when the camera points toward the user's face.

There are conceivable use cases where the camera will not point toward the user's face, like teachers pointing the camera towards a blackboard. In this case, the teacher will have considerable difficulties setting up the image, as it appears mirrored to her where it should not be.

**Describe the solution you'd like**
Please provide a way of toggling mirroring of the user's own camera image.

**Comment by ruedigerkupper** [comment]
This is very likely related to #6708.

**Comment by DerDings** [comment]
I think it is already possible via right-clicking your video. But I don't know if this only affects what you see or also what your fellow jitsers see.

**Comment by cbm755** [comment]
I checked: it effects only my local view.

I think this can be closed.

**Comment by ruedigerkupper** [comment]
Thanks!

**Comment by pandeyVishakha** [comment]
I didn't get the solution. In my case, the local view is a mirror image. How I can fix this issue?

**Comment by damencho** [comment]
Right-click on your local video and use the menu: 
![image](https://user-images.githubusercontent.com/3263098/101523434-37b87580-394e-11eb-9bff-aa9ab6637cfd.png)

**Comment by pandeyVishakha** [comment]
> Right-click on your local video and use the menu:
> ![image](https://user-images.githubusercontent.com/3263098/101523434-37b87580-394e-11eb-9bff-aa9ab6637cfd.png)

Thank you!!
Is there any way to start video without mirror image?

**Comment by user31415** [comment]
I'm just trying Jitsi Meet and am encountering the same Self Mirror issue. Right clicking the the video does **not** provide a "Flip" option in the menu.

I'm running Fedora 32 and Firefox 86.

Thanks!

**Comment by user31415** [comment]
I **had** this problem as well. The "_Flip_" option required right-clicking the self identifier icon in the top right corner, not just anywhere on the video.

That may be obvious to an experienced user but this is my first time using Jitsi.

Thanks!
