### ISSUE TITLE
Plugin-system

### ISSUE THREAD

**Issue by lggwettmann** [jitsi/jitsi-meet#6864]
**Is your feature request related to a problem you are facing?**
It is very difficult a) to find information on how to adjust Jitsi b) once found, it still is very difficult to make the changes and figuring out how Jitsi works c) everyone seems to have to re-invent the wheel even for very basic or common use cases.

**Describe the solution you'd like**
Some kind of plugin-system or more modular architecture. Think along the lines of plugins for jQuery or packages for Python apps. Jitsi could provide hooks (perhaps based on the API) and the apps all connect/use those hooks and can be installed the same way. Imagine a folder where one has to put the plugin files and a registration file to let Jitsi know about the plugins.

**Describe alternatives you've considered**
Honestly, there are so many moving parts and such bad documentation on this amazing package I don't think there is any alternative besides everyone diving into the code, trying to figure out where to find the information, half of it doesn't work for your use case even though there must be 1000 other people with exactly the same wishes. I think a more modular, developer-friendly approach would really help Jitsi break through the roof.

**Comment by luixxiul** [comment]
Just FYI https://jitsi.github.io/handbook/ is the official guide website.

**Comment by lggwettmann** [comment]
Thanks, I know that this is out there now thankfully. And it's a great first step, but it only covers the very basics and not any other use cases with eg a recorder, docker installation or others. 
I still very much think that a plugin-/modular-system would be very very very helpful to drive adoption and ease of use.

**Comment by luixxiul** [comment]
Nitpick: I don't want to be a jerk but the docker installation guide is available at:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

This was just moved from the official package's README.md, which has been maintained for a long time. The handbook's repository is quite young (or I should say it's been updated inactively) as you could see on its history: https://github.com/jitsi/handbook/commits/master?after=276c315895b6238c533f4f4dcc693842ead06ba9+34

I myself am not sure how plugin system could be implemented to the current codebase. I think @saghul or @damencho would provide some insight on this stuff.

**Comment by lggwettmann** [comment]
Thanks for pointing this out @luixxiul. Please imagine that I used another example. 👍

And as your comment seems quite defensive: I want to make it clear that I'm writing with the best of intentions. I'm not here to trash anyone or all the work you guys have put in this fantastic product - I just think that this has even more potential. We can not talk about the parts where it can be improved, or we can make it better. -- and just to mention: I have added tutorials I found in the community forum to the Github Wiki before there was the new handbook. So I am willing to help out and have done so in the past.

Now, getting to the plugin-idea, I wonder if it's doable at all and if it would make sense. :)

**Comment by saghul** [comment]
I don't understand what you want to accomplish @lggwettmann. We need some more details to understand what's missing or what can be done.

"A plugin system / more modular architecture" doesn't say much. You focused your report on some very abstract "solutions" but it's not clear to me what specific problem you are trying to solve.

Can you please provide some specific examples (plural)?

**Comment by Echolon** [comment]
@lggwettmann Do you have a response to the question?

**Comment by lggwettmann** [comment]
Sorry to not have come back earlier to this. I think I lack the proper information on how all parts of Jitsi work together. I think my thought was intentionally vague and abstract cause I will not be able to come up with a solution. I can merely give feedback and food for thought from an outsider's perspective. 

Imagine a way to add features or customization options to Jitsi in one way for most features. You can call that plugins, add-ons, feature-packs, apps, or whatever. The main goals would be for devs

- developers don't need to reinvent the wheel 
- developers can install and configure common features in ONE way
- developers can install and configure common features with reduced time and money resources
- developers can build new plugins/add-ons based on their customizations and provide it to the community

And for Jitsi
- Jitsi will be customizable easier and faster with the most common features which should lead to even higher adoption
- Jitsi will receive less support/forum posts with the same issues cause there is a standardized way for more things
- Jitsi can provide a small 'plugin store' with easy addable plugins which could help highlight the multiple use-cases for Jitsi
... just to name a few.

Most probably this will be horrible examples and their installation currently all work totally different, but I'll give it a try and hope that you'll be able to get something out of it. Perhaps even if it's just for a future iteration of the code-base or some general modularity. You know best what's possible and what's in your vision for Jitsi.

- Installation and configuration of authentication features like eg via JWT-tokens. So if you have your own website with authentication for users, you can install this plugin and it creates a link with a JTW-token which you can include on your website and brings people to the Jitsi-chat.
- Installation and configuration of different UI options like breakout rooms, music mode options in the UI, themes, or things like that.
- Installation and configuration of the waiting room feature
- Installation and configuration of etherpad
- Installation and configuration of Jibri (after a Jibri server has been already set-up)
- Perhaps even the installation and configuration of other connected video bridges

I understand if this is not applicable, but I hope you can do something with that and the thoughts help.

**Comment by Echolon** [comment]
@saghul @damencho any response to this?

**Comment by edvinkuric** [comment]
@saghul @damencho it would be great to implement a feature like in #3827 without touching the core files, so that future updates   would work "out of the box".

The current state is that "everyone" has to maintain his own base and adapt many files, which can conflict with future updates in later releases. A Plugin-System allows to implement features without touching the core-files.

**Comment by heikar** [comment]
I think also with regard to #4787 or #5550 that this feature would extend the possibilities of jitsi.
So anyone who has a solution for a task can easy provide it to the community.

**Comment by pierreozoux** [comment]
If we take the example of etherpad integration.

It is an iFrame extension. You click a button in the UI, it opens an iframe for everybody.

In an ideal world, lib jitsi meet would offer some kind of API to register a button in the UI (in the 3 dot menu for instance).

Then, the module would be in the form of an NPM package named jitsi-etherpad for instance.
Adding this package would add the button and the iFrame integration to the UI.

If the team agrees with this solution, sound like the best path forward for all the wished of the world (vote, breakout, whiteboard, peertube, you name it :) ).

Ill try to come to a weekly meeting.

Then the ideal would be to find a freelance ready to do the job, and crowdfund the feature (Id love to develop it, but my react is not good enough ;) ).

**Comment by DanielHabenicht** [comment]
In order to implement it it would be useful to have an overview of all functionalities that should or could be implemented in the future of the API, e.g. must haves for version 1 but also things that should be kept in mind for the future. Can somebody with more experience on jitsi provide make a first draft? 
Also what dependencies are there to other frontends, e.g. Android?

**Comment by pierreozoux** [comment]
During the hackathon, this feature was submitted:
It is not necessarily a plugin system per say, but a convenient way to add any url as an iframe (if I understood correctly the code)

https://github.com/jitsi/jitsi-meet/pull/9122

**Comment by DanielHabenicht** [comment]
Mhm, that PR looks like it just for sharing a URL for all during a meeting. I think this Issue is more about adding functionality to Jitsi from a developer perspective for all meetings... e.g. adding an external application link to all meetings or a vote functionality (and creating the plugin system in order to that)
