### ISSUE TITLE
Handle callkit logic outside the SDK on iOS

### ISSUE THREAD

**Issue by luismachado** [jitsi/jitsi-meet#6867]
Hello,

We've been using the SDK for quite some time but I'm now aiming at making some updates to the callkit logic (mainly because since iOS 13.3.1 Apple restricted audio access depending on when, and how, the callkit is initiated).

Basically what I want to do is disable the callkit inside the SDK and handle the complete lifecycle within my own app. Disabling it on jitsi is easy (there's a variable for that) and developing it on the app it's also done. However:

1) As it is right now Jitsi Meet doesn't offer any sort of API so it looks like I'm unable to complete the main functionalities of the callkit screen (such as mute, change audio and video sources, etc). Is this right? Any suggestions?

2) On Jitsi, if a call is started from the background (this happens frequently on the main app, if the app's closed/screen locked and the user receives a call -> on Jitsi I'm just adding a timer before joining the conference and locking the screen, just to simulate that) the audio session is never started:

`2020-05-26 09:25:32.836983+0100 jitsi-meet[5489:1480429] [aurioc] AURemoteIO.cpp:1904:Run: AURemoteIO@0x120876a40: IOThread exiting with error 0x10004006
2020-05-26 09:25:32.839095+0100 jitsi-meet[5489:1480074] [aurioc] AURemoteIO.cpp:1590:Start: AUIOClient_StartIO failed (561145187)`

From what I've gathered (at least since 13.3.1) it looks like iOS only starts the audio session - when the app is backgrounded - with an reportNewIncomingCallWithUUID call. Now, neither Jitsi uses that (to start a call Jitsi uses an outgoing call) nor will it as one of my goals would be to disable callkit completely inside the SDK.

Did you ever experienced this issue? Any clues on what might be attempted?

Thanks in advance :)

**Comment by luismachado** [comment]
Hello, just pinging back in. Any suggestions? Thanks

**Comment by PauMateu** [comment]
Hi! Just a friendly pinging.. Has anyone been able to use/modify the SDK to work with the iOS callkit logic? Thanks!
