### ISSUE TITLE
Feature Request: Dropdown for Jitsi servers

### ISSUE THREAD

**Issue by hackerfactor** [jitsi/jitsi-meet#6871]
**Is your feature request related to a problem you are facing?**
Yes.
I sometimes use the default jitsi server.
I sometimes use my own jitsi server.
I sometimes use my friend’s jitsi server.
It would be nice to have a dropdown of my previous choices so that I don’t have to keep typing them in.

**Describe the solution you'd like**
I would like a dropdown of my previous choices so that I don’t have to keep typing them in.

Also, in the list of recent conferences, have it track which ones used which servers. Right now, it lists “DontEatFuzzyAvocados”, “HeIsComingSoonYouBetterNotSleep”, and “PenguinsTasteLikeChicken”. What I’d like to see:

- “DontEatFuzzyAvocados” (no server listed since it’s the default jitsi.org server)
- “HeIsComingSoonYouBetterNotSleep on server1.example.domain” If I click this, it automatically selects the correct server (server1) and joins the conference.
- “PenguinsTasteLikeChicken on server2.example.domain” Different conference on a different server.

This should be on the mobile apps and any desktop app.
Selecting the server is not needed via web browser since the URL identifies the server.

**Describe alternatives you've considered**
Right now, I have to retype the server each time.

**Comment by sebastienaubry** [comment]
Hi,
I support this feature: several times per day I have to manually type the server (and sometimes meeting) name, when switching between a public and private server. An interesting related idea would be to make it possible to share an URL (a link) to the (for me Android) JitSi app? The link contains both the server address and the meeting room.
Regards
