### ISSUE TITLE
Bug: livestream option is available to guests (should not be)

### ISSUE THREAD

**Issue by hackerfactor** [jitsi/jitsi-meet#6875]
### Description:
Ubuntu 18.04 "jitsi-meet". I enabled the moderator so new rooms require someone who is logged in (see: https://www.digitalocean.com/community/tutorials/how-to-install-jitsi-meet-on-ubuntu-18-04 step 5).

I also installed jibri (have not yet got it working, but that's a whole different issue).

In /usr/share/jitsi-meet/interface_config.js, I enabled "fileRecordingsEnabled: true," and "liveStreamingEnabled: true,".

According to  /etc/jitsi/meet/myserver-config.js, the menu options livestream and recording are special:
    /**
     * The name of the toolbar buttons to display in the toolbar. If present,
     * the button will display. Exceptions are "livestreaming" and "recording"
     * which also require being a moderator and some values in config.js to be
     * enabled. Also, the "profile" button will not display for user's with a
     * jwt.
     */

In reality: 'recording' works as expected. Only the moderator sees the recording option.
However, moderator and guests sees the livestreaming option. The 'livestreaming' option should only be seen by the moderator, not by guests.

### Steps to reproduce:

1. Edit /usr/share/jitsi-meet/interface_config.js
2. Enabled "fileRecordingsEnabled: true," and "liveStreamingEnabled: true,".
3. Restart the jitsi server. (I restart all of the components)
  sudo systemctl restart prosody.service
  sudo systemctl restart jicofo.service
  sudo systemctl restart jitsi-videobridge2.service
  sudo service nginx reload
4. Login as the moderator. There is a menu in the lower right that includes "Start recording" and "Start live stream". (This is expected.)
5. In a different browser, login as a guest. There is a menu in the lower right that does not include "Start recording" but does include "Start live stream". (Livestream should not be there.)

### Expected behavior:
Guests should never see the option to start live stream.
Or if this is desired functionality, then
1. Fix the comment in interface_config.js since the comment does not match the functionality.
2. Change 'liveStreamingEnabled' from a boolean to a string. Allow me to set it to 'none', 'moderator', 'owner', or 'all'. The 'none' would be the same as false. Moderator and owner options specify that access is limited to a specific class of user. The 'all' would enable it for all users, including guests. 

### Actual behavior:
Guests can enable live streaming.

### Server information:

- Jitsi Meet version: stable/jitsi-meet_1.0.1072-1_all.deb
- Operating System: Ubuntu 18.04 server (not desktop)

### Client information:

The issue is browser independent. Tested with both Firefox and Chrome.

**Comment by yodaphone** [comment]
In secure domain setup all moderators can initiate a live stream

Guests see the option but it the live stream will not start even if they try

**Comment by hackerfactor** [comment]
If guests cannot use the option, then the option should not be visible to guests.

**Comment by luixxiul** [comment]
I assume this issue should be fixed with https://github.com/jitsi/jitsi-meet/pull/6263.
