### ISSUE TITLE
participate in a conference without sharing webcam/audio (vieweing, listening, chatting only)

### ISSUE THREAD

**Issue by kolAflash** [jitsi/jitsi-meet#688]
Currently you can't enter a conference without sharing your webcam/audio.

Somebody might want to participate in a conference without sharing his own webcam/audio.

E.g. because he has no webcam and his microphone makes squeaky noises nobody can stand.
So he might want to hear and see the others, but only participate by the chatting feature.

Other example:
You wait for someone else to enter a conference. So you might not want to share your webcam/audio all the time but hear if someone else enters the conference an speaks "Hello, anyone here?" into his microphone.

**Comment by bgrozev** [comment]
> Currently you can't enter a conference without sharing your webcam/audio.

If this occurs for you this is regression. I can't reproduce it here. Can you please share steps to reproduce the problem you see?

**Comment by kolAflash** [comment]
Steps:
1 - Enter a conference on https://meet.jit.si (using Firefox 46)
2 - Close or ignore the question for microphone (there are no choices "no audio" and "no webcam" in the selection dialogs by Firefox)

Result: No second question for webcam appears.
This might be another bug!
Someone might wants to share just the webcam OR audio.

3 - Click on the chat icon in the Jitsi Meet conference.
4 - Type "Hello" and Enter.

Result: Message "Hello" doesn't appears in chat history above.

5 - Connect a second browser tab and allow webcam and audio for the second tab.
6 - look into your camera, speak something into the microphone and send a chat message

Result: The first tab neither receives the message, nor shows the webcam picture of the second tab or plays the audio from the second tab.
Same result if the second connection comes from a completely different device.


If I allow microphone and camera, Jitsi Meet works completely fine on all devices I used for this test.
- openSUSE 13.2 Linux x86_64 Laptop with Firefox 46
- Android 6/Cyanogenmod 13 Smartphone (Samsung Galaxy S4 Mini) with Firefox 47

**Comment by bgrozev** [comment]
Thanks for the detailed explanation. I see similar results if I close or ignore the camera/mic window. It looks like we never attempt to join the MUC (although the XMPP connection succeeds). We should handle this better.
If I specifically decline access to the camera and mic (my firefox 46 running on mac shows a dropdown menu with "don't share" as one of the options), I am able to join the conference and I didn't see any broken functionality. We do show an "error" dialogue, which should probably be something more informative or less scary.

**Comment by akuckartz** [comment]
:+1: for the detailed report.

**Comment by kolAflash** [comment]
I just tested this with Chromium (Google Chrome) and independently from how I handled the question for webcam/audio, I always got into the conference/session.

Maybe you should talk to the Firefox developers. But I guess the behavior of Firefox is intended. Because after clicking "Don't Share" in Firefox, I don't have the possibility to re-decide. Instead on ignoring or closing the Firefox dialog window, there stays an icon (left to the Firefox address bar) giving me the choice to re-dicide and share my camera/microphone.

So Jitsi Meet should probably just let the user enter the conference, and assume no camera/micrphone permission, instead of waiting for a definite "No" (Don't Share).

**Comment by thekyriarchy** [comment]
Yes, combined with adding the ability to view multiple video conference streams at once  #30 , this would be make jitsi meet a complete and fully featured competitor to all the others!

**Comment by heyakyra** [comment]
This would still be a useful feature! any chance of re-opening? @damencho

**Comment by damencho** [comment]
Yes, this should work. I'm reopening, but mind that issues doesn't fix by themselves. Any help is welcome :)

**Comment by damencho** [comment]
@heyakyra I don't see a problem with this. I tested Chrome and Firefox and if you deny the camera requests I see warnings about not able to obtain mic & camera and I see and hear the remote participants.

**Comment by heyakyra** [comment]
Yes, but you consume a rectangle unnecessarily. I think "viewing/listening/chatting-only" means that you participate without being part of the "presentation" which are the rectangles which appear. This would be very useful for panel discussions where some people are on video and the rest participate only through chat, or can be given a temporary slot for their camera to ask a question
