### ISSUE TITLE
"REC" label is no longer visible when VIDEO_QUALITY_LABEL_DISABLED: true

### ISSUE THREAD

**Issue by loyolajavi** [jitsi/jitsi-meet#6880]
In /usr/share/jitsi-meet/interface_config.js if I set VIDEO_QUALITY_LABEL_DISABLED to True, the "REC" label is no longer visible in records.

I've installed:
jitsi-meet 2.0.4468-1
jitsi-videobridge2 2.1-183-gdbddd169-1
jicofo 1.0-549-1
prosody 0.10.0-1build1

**Comment by luixxiul** [comment]
Please follow the template and provide steps to reproduce the bug. It will help developers to detect where the issue exists.

````
### Steps to reproduce:

1. <!-- Open '...' -->
2. <!-- Click on '...' -->
3. <!-- and so on... -->

### Expected behavior:

<!-- Please describe what should happen. -->

### Actual behavior:

<!-- Please describe what actually happens. -->
<!-- Please attach screenshot if possible. -->
````

**Comment by loyolajavi** [comment]
### Steps to reproduce:

1. In a conference click on "start recording"
2. The label REC does not appear in the upper right corner (the "recording is on" audio it reproduce Ok)

### Expected behavior:

The label REC must appear in the upper right corner
