### ISSUE TITLE
Jitsi install/update hijacks coturn config

### ISSUE THREAD

**Issue by mvn23** [jitsi/jitsi-meet#6883]
### Description:
On every update, jitsi-meet-turnserver overwrites /etc/turnserver.conf, overwriting any existing configuration.

### Steps to reproduce:

1.  Have a system with coturn configured to your liking.
2.  Install/update jitsi.
3.  Your existing coturn config is now overwritten.

### Expected behavior:
Don't overwrite existing configuration without confirmation.

### Actual behavior:
Existing config is overwritten without even asking.

### Server information:

- Jitsi Meet version: jitsi-meet 2.0.4627-1, jitsi-meet-turnserver 1.0.4127-1
- Operating System: Debian 10.4

### Client information:

- Browser / app version: 
- Operating System: 

### Additional information:
N/A

**Comment by damencho** [comment]
There is an easy workaround, just make sure you have this line in your config https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-turn/turnserver.conf#L1

**Comment by mvn23** [comment]
Nobody will have that line in their config unless they have already installed jitsi and their config is already overwritten. That line will only make sure that jitsi will not overwrite **its own** config. Existing config is still overwritten upon install without confirmation or consent. Unlike nginx and prosody, coturn does not provide a drop-in config directory, so I can see why there is a need to overwrite the config file, but it's a bit rude to do this without confirmation.

I don't see why this issue was closed. A workaround is not a fix and jitsi is still destroying existing configuration (except its own). If anything, it should only overwrite the config if that line **is** present in the config and otherwise give the user a choice or a reference to some documentation.

**Comment by luixxiul** [comment]
how about trying docker-jitsi-meet instead?

**Comment by mvn23** [comment]
Let me be clear here: I am not looking for help in making my setup work. It works fine as I have configured it now.

I have filed this bug report because I found some behavior in jitsi that I think is undesirable and unintended, i.e. a bug. I report this behavior here so it can be (re)considered and fixed if necessary. If this is actually intended behavior (which I can't imagine) then by all means confirm that jitsi is breaking existing configuration on purpose and we can all go on with our lives. If it is not intended behavior, then let's work out a way forward and see how we want to fix this. From what I have seen so far the bug originates in a postinst bash script, so I may even have a go at a fix after a desired way forward is known.

**Comment by damencho** [comment]
> If this is actually intended behavior (which I can't imagine) then by all means confirm that jitsi is breaking existing configuration on purpose and we can all go on with our lives. If it is not intended behavior, then let's work out a way forward and see how we want to fix this. From what I have seen so far the bug originates in a postinst bash script, so I may even have a go at a fix after a desired way forward is known.

This is how it is intended to work, and we keep a .bak file of the old config. There is no way currently to recognize is this the default turnserver config(after new install) or user-supplied one. If you have an idea how to recognize those we are open on fixing it so it will work for people installing where there is no coturn installed or in situations like yours where coturn was pre-installed and pre-configured.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-turnserver.postinst#L60

**Comment by mvn23** [comment]
I see. It is indeed difficult to distinguish between those situations.
Does it have to be an unattended solution? Or can we ask for user input in the process?

An unattended solution would be to check `/etc/default/coturn` for a `#TURNSERVER_ENABLED` line before changing it in [L142](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-turnserver.postinst#L142). If this is present (with the `#`), then either we have a fresh install or the existing instance is not enabled and likely not configured. In this case we should still make a backup copy and notify the user that we're overwriting the config, but it would be relatively safe to assume we're not breaking a running system.
If that line is not present we can check for the `jitsi-meet coturn config` line in the existing `turnserver.conf`. If that line is present in `turnserver.conf` we can assume that coturn was configured by jitsi on an earlier occasion and we can safely replace it with a possibly updated version.
If that line is not present in `turnserver.conf` we can assume that coturn was previously configured by the user and provide a hint to the relevant documentation and/or desired config file in `/usr/share/jitsi-meet-turnserver/`.

If there is no need to support the unattended option, we can just check if `jitsi-meet coturn config` line is present in `turnserver.conf`. If it is, we can safely replace the config with an updated version. If it is not present, we should ask the user for confirmation before overwriting the config.

**Comment by damencho** [comment]
> An unattended solution would be to check `/etc/default/coturn` for a `#TURNSERVER_ENABLED` line before changing it in [L142](https://github.com/jitsi/jitsi-meet/blob/master/debian/jitsi-meet-turnserver.postinst#L142).

Good point, thanks for the suggestion.

**Comment by mvn23** [comment]
What about the second part? Do we want to overwrite the config when `jitsi-meet coturn config` is present in the file to allow for future updates? Or is a one-shot set and forget approach more desirable?

**Comment by damencho** [comment]
> Or is a one-shot set and forget approach more desirable?

This is how all configs works, and updating the current configuration needs to be spread then, like if we update coturn ports on update prosody config will also need to be updated, it may need and Nginx changes at some point ...

**Comment by Echolon** [comment]
@damencho is this still relevant?

**Comment by damencho** [comment]
Well we keep a backup of the file and do not wipe it ...
