### ISSUE TITLE
Audio-only calls: add option to disable turning video back on

### ISSUE THREAD

**Issue by tdrp** [jitsi/jitsi-meet#6894]
**Is your feature request related to a problem you are facing?**
We want to be able to have forced audio only conference calls. Unfortunately, even when we setAudioOnly(true) and setVideoMuted(true), the users are still shown the little video button which allows them to turn video back on. In our scenario, the conference room has users meeting for the first time and not all the users are yet trusted - we don't want anyone using the video feature to show something inappropriate.

**Describe the solution you'd like**
We'd simply like an option to entirely remove the video button. Something like setVideoAllowed(false)

**Describe alternatives you've considered**
setAudioOnly(true) and setVideoMuted(true) remove the video but still show the video button, so users can simply toggle it back on. It is probably possible to recompile the source code and make the change for our scenario but it seems like others might benefit from this.

**Comment by saghul** [comment]
You can remove the camera button from interface_config.js on your deployment or via the iframe API: https://github.com/jitsi/jitsi-meet/blob/f0c6e934ce8fb4bee75ae2061b920eb703cf688f/interface_config.js#L50

**Comment by tdrp** [comment]
thanks @saghul - is there an equivalent way for the Jitsi Android API (i.e. not using our own deployment)?

**Comment by saghul** [comment]
No, there currently isn't.

**Comment by tdrp** [comment]
@saghul would it be possible to add some of these interface_config params to the Android SDK/API call? Perhaps as a .setFeatureFlag("", false) kind of call. I can make the PR change if you point me in the right direction. 

There's probably a few customizable options available in the iFrame API which we'd eventually like to see in the Android SDK.

BTW can the Android SDK use an iFrame URL as the server? That might make the above moot.

**Comment by saghul** [comment]
> would it be possible to add some of these interface_config params to the Android SDK/API call? Perhaps as a .setFeatureFlag("", false) kind of call. I can make the PR change if you point me in the right direction.

Yes, that would make sense. You can check how other buttons are hidden like the raise hand or tile view ones for example. Feel free to open a PR early and ask questions about the implementation there.

> There's probably a few customizable options available in the iFrame API which we'd eventually like to see in the Android SDK.

Sure thing, let's discuss on a case by case basis, improvements are definitely welcome!



> BTW can the Android SDK use an iFrame URL as the server? That might make the above moot.

Not really, they are completely unrelated.

**Comment by notinactive** [comment]
Thanks a lot @saghul,
You are an angle, 
You solved my problem with your guidance, I was involved in this problem for 2 days.
