### ISSUE TITLE
Android API generated APK/AABs are very large in size if Jitsi is included

### ISSUE THREAD

**Issue by tdrp** [jitsi/jitsi-meet#6895]
### Description:

Our generated Android AAB file went from 6MB for our fully functional app to 35MB simply by including Jitsi (release mode). This makes it more appealing to simply use an embedded WebView than to include the actual API. For reference, adding webRTC alone brought us to 16MB. Some of the files also look like they might not be necessarily needed (both libhermes-executor-debug.so and -release are included). I have attached a screenshot of the analyzed APK
![Capture](https://user-images.githubusercontent.com/66039763/83086312-4808a300-a043-11ea-92fd-5f258337b33a.JPG)

There's also quite a few references to Facebook-owned DLLs (Hermes, react, etc.) - can these not be avoided, and if not, are they sending back any analytics to their own servers?

### Steps to reproduce:

1. Create new Android project
2. Add Jitsi library
3. Include proguard rules given in the tutorial
4. Generate signed APK/Bundle
5. Analyze generated file.

### Expected behavior:

Generated APK/AAB seem to be a bit large in file size. Is it better to just use the embedded WebView now that it is supported with config.disableDeepLinks rather than use the API?

### Actual behavior:

Large file size, not clear if all of them are required.

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: 

### Client information:

- Browser / app version: Android
- Operating System:

**Comment by saghul** [comment]
> Our generated Android AAB file went from 6MB for our fully functional app to 35MB simply by including Jitsi (release mode).

This is the expected size. The SDK is about 28 MB (includes all architectures).



>  This makes it more appealing to simply use an embedded WebView than to include the actual API.

Well, you can do whatever you think best suits your use case. Our mobile support is much better using the app / SDK than a webview.

> For reference, adding webRTC alone brought us to 16MB.

So? There is much more than that. The JS bundle, where all the actual SDK code is, sound files, image assets, etc.



> Some of the files also look like they might not be necessarily needed (both libhermes-executor-debug.so and -release are included).

Yeah I don't know why that is, but at any rate its size is negligible compared to the overall.

 

> There's also quite a few references to Facebook-owned DLLs (Hermes, react, etc.) - can these not be avoided

Of course they can't be avoided. The entire SDK is built with React Native.

> are they sending back any analytics to their own servers?

Of course not.



> ### Expected behavior:
> 
> Generated APK/AAB seem to be a bit large in file size. Is it better to just use the embedded WebView now that it is supported with config.disableDeepLinks rather than use the API?

No. The SDK will always be the native SDK. If you want to embed Jitsi in a WebView you don't need any SDK.

**Comment by guptanarendra** [comment]
yes the apk gets increased to 40MB big when i updated to  lateast version of jitsi plz provide any solutions for this
