### ISSUE TITLE
how to customise UI ?

### ISSUE THREAD

**Issue by fathima-shamsu** [jitsi/jitsi-meet#6896]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by fathima-shamsu** [comment]
how can i add or remove features from "more options " like removing live streaming

**Comment by luixxiul** [comment]
Hi, as explained in the issue template, questions should be put forward at https://community.jitsi.org/ Thanks!
