### ISSUE TITLE
Appointing a host/moderator for the meeting

### ISSUE THREAD

**Issue by ashrayagovindadas** [jitsi/jitsi-meet#6898]
**Is your feature request related to a problem you are facing?**
The problem which we are facing is the attendees sometimes stop the recording feature which causes an interruption in the discussion. In spite of many requests, attendees do that. And if they don't add their name, it simply appears as Fellow Jitster stopped the recording! We are not able to find the mischief monger. :-)

**Describe the solution you'd like**
One solution can be to keep a moderator or host. Anyone in the meeting should be able to appoint anyone as a host. Once he's appointed, only he should be able to further appoint another host/moderator and could control the recording and important functions.

**Describe alternatives you've considered**
I am not able to think of any alternatives to this problem.

**Comment by luixxiul** [comment]
> The problem which we are facing is the attendees sometimes stop the recording feature which causes an interruption in the discussion.

@saghul I thought only a moderator in a meeting could stop the recording. Is it not right?

**Comment by ashrayagovindadas** [comment]
> > The problem which we are facing is the attendees sometimes stop the recording feature which causes an interruption in the discussion.
> 
> @saghul I thought only a moderator in a meeting could stop the recording. Is it not correct?

Unfortunately, there is no moderator in Jitsi Meet.

**Comment by luixxiul** [comment]
> Unfortunately, there is no moderator in Jitsi Meet.

Are you using https://meet.jit.si?

**Comment by luixxiul** [comment]
If so, everyone on your meeting is a moderator. See: https://community.jitsi.org/t/after-the-host-has-started-a-meeting-and-setup-a-password-any-guest-can-change-it/60549/3

If you would like to decide who can be a moderator, you need to deploy your own instance. Please see:

- https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart for instruction
- https://jitsi.github.io/handbook/docs/devops-guide/secure-domain

Thanks!
