### ISSUE TITLE
Non-alphanumeric characters in room names are not allowed when running under Apache

### ISSUE THREAD

**Issue by Mzyxptlk** [jitsi/jitsi-meet#6901]
### Description
Creating rooms containing non-alphanumeric characters results in a 404 error when running under Apache, but work and are allowed under nginx.

### Steps to reproduce:
Run a Jitsi Meet instance with Apache as the web server. Create a room named 'with-dash' or 'with.dot' using the web interface.

### Expected behavior:
Room is created.

### Actual behavior:
"404 not found. You can create a new conversation here", with 'here' linking back to `/`.

### Server information:
- Jitsi Meet version: 2.0.4652-1
- Operating System: Debian testing

### Client information:
Firefox 76

### Additional information:
In /etc/apache2/sites-available/domain.com.conf, the default rewrite rule that redirects room names to index.html is this:
`RewriteRule ^/([-a-zA-Z0-9]+)$ /index.html`

I'm not familiar with nginx configuration, but I think this is the nginx version?

```
location ~ ^/([^/?&:'"]+)$ {
    try_files $uri @root_path;
}
```

As you can see, that regex is much broader than the Apache version. My ~first~ ~second~ third attempt at an equally broad rewrite rule for apache would be this:

```
RewriteCond "%{REQUEST_URI}" "!^/http-bind"
RewriteCond "%{REQUEST_URI}" "!\.(js|png|css|ico|html)(\?v=[0-9]+)?$"
RewriteRule ^/([^/?&:\'\"]+)$ /index.html
```

I have excluded static files and `/http-bind` to be able to use dashes and periods in room names. As far as I can tell this needs to be fixed in doc/debian/jitsi-meet/jitsi-meet.example-apache.

**Comment by Aaryan-kapur** [comment]
I still have this issue!!! please open it!
