### ISSUE TITLE
Port 8081 already in use, packager is either not running or not running correctly

### ISSUE THREAD

**Issue by KunalBhorodiya** [jitsi/jitsi-meet#6904]
> Task :app:runDebugReactPackager FAILED
Starting the React packager...
scripts/run-packager.sh: line 14: curl: command not found
**Port 8081 already in use, packager is either not running or not running correctly**

FAILURE: Build failed with an exception.

* What went wrong:
**Execution failed for task ':app:runDebugReactPackager'.**
> Process 'command 'scripts/run-packager.sh'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
214 actionable tasks: 7 executed, 207 up-to-date

This happens if i start metro server first with react-native start and if i run app with react-native run-android first then the app will install successfully but shows nothing.. 

![Screenshot from 2020-05-29 12-39-03](https://user-images.githubusercontent.com/30719092/83231646-73a59d80-a1a9-11ea-87d1-b9a740ffb163.png)

![Screenshot from 2020-05-29 12-39-57](https://user-images.githubusercontent.com/30719092/83231686-861fd700-a1a9-11ea-85b2-bcf0cbf30ab2.png)

![Screenshot_2020-05-29-12-40-15-002_org jitsi meet](https://user-images.githubusercontent.com/30719092/83231788-b36c8500-a1a9-11ea-846e-bc4d2549ec6f.jpg)
 
![Screenshot from 2020-05-29 12-48-00](https://user-images.githubusercontent.com/30719092/83232359-aa2fe800-a1aa-11ea-9fa8-21231fee7bde.png)

**Comment by KunalBhorodiya** [comment]
I got the solution by changing port in run-packager.sh file in android/scripts folder.
![Screenshot from 2020-05-29 13-19-50](https://user-images.githubusercontent.com/30719092/83235171-190f4000-a1af-11ea-81b4-c6bb010409f3.png)

**Comment by luixxiul** [comment]
@KunalBhorodiya was this issue fixed on your side?

**Comment by KunalBhorodiya** [comment]
@luixxiul Yes i fixed it from my side...
