### ISSUE TITLE
Need the feature to play audio along with video when shared from Application Window

### ISSUE THREAD

**Issue by krishnanvs11** [jitsi/jitsi-meet#6909]
**Is your feature request related to a problem you are facing?**
We conduct online trainings and are planning to use Jitsi for our sessions. However, we face a serious constraint that the audio is not shared along with our training videos. 

**Describe the solution you'd like**
We would love to be able to play the audio along with the video that is shared through Application window. It is essential to make our online session effective.

**Describe alternatives you've considered**
The alternative we have considered is to share the whole screen and play the video but the limitation is that the presenter cannot access any other window till the video is played out.

**Comment by damencho** [comment]
You can do that with latest Chrome on Windows. 
![image](https://user-images.githubusercontent.com/3263098/83364140-8c0de780-a364-11ea-9cad-41dd2a12daf6.png)
Sharing audio from an application is available only on windows, sharing tab audio is available on macosx. This is browser limitation and there is nothing we can do about it.

**Comment by krishnanvs11** [comment]
@damencho
I tried now with latest Chrome version 83.0.4103.61 (Official Build) (64-bit). Not sure if I am missing something but I still don't see the checkbox to share audio when I choose the video to share in "Application window". Please check the attached screenshot.

![jitsi_share_app_window](https://user-images.githubusercontent.com/42645307/83410198-88956180-a433-11ea-8dc7-d60010e5888a.png)
