### ISSUE TITLE
Out-of-the-box Jitsi-meet can not operate when installed to webserver sub-directory

### ISSUE THREAD

**Issue by dvdkhlng** [jitsi/jitsi-meet#6914]
### Description:

I installed jitsi-meet on an existing webserver that has an existing domain-name and SSL certificate.  As such I didn't want to increase my webserver's configuration's complexity by adding another SSL certificate and subdomains with SNI or attempting to get a wildcard-certificate.

I thus attempted installing jitsi-meet into a webserver sub-directory.  Looking at #2422, #4917, #381 there seemed to be no final answer yet whether that is "officially" supported and how to fully configure it.

I found out, that indeed two source-files outside /etc need modification, which points to subdirectory installation either not being supported, or bugs being present WRT it:

/usr/share/jitsi-meet/base.html : content had to be replaced with

```html
    <base href="/jitsi-meet/" />
```

/usr/share/jitsi-meet/index.html : a few absolute-path server-side javascript-references had to be modified

```html
    <script><!--#include virtual="/jitsi-meet/config.js" --></script>
    <script><!--#include virtual="/jitsi-meet/interface_config.js" --></script>
    <script><!--#include virtual="/jitsi-meet/logging_config.js" --></script>
```

Other than that just modifying the configuration was sufficient to make this setup work:
/etc/jitsi/meet/[domain]-config.js :

```JSON
   bosh: '//<domain>/jitsi-meet/http-bind',
```

For reference, this is the (slightly stripped down) copy of the apache2 configuration file  for jitsi-meet installed to subdirectory //jitsi-meet/.  With this configuration, jitsi-meet indeed appears to run flawlessly.

```ApacheConf
## Derived from auto-generated site-config files as follows:
## - Deleted Virtual Server
## - replaced DocumentRoot with Alias
## - prefixed existing Alias and Location commands with /jitsi-meet
## - Moved proxypass into a new <Location> block
## - Moved RewriteEngine into the <Directory> block.
## - change "bosh" in the jitsi -config.js to point to the corret http-bind 

## Other hacks for jitsi-meet in subdir:
## - modify base.html
## - modify index.html to fix all the "include virtual" statements that go
##   directory to the root dir.

Alias "/jitsi-meet/config.js" "/etc/jitsi/meet/<domain>-config.js"
Alias "/jitsi-meet/external_api.js" "/usr/share/jitsi-meet/libs/external_api.min.js"
Alias "/jitsi-meet" "/usr/share/jitsi-meet"

<Directory "/usr/share/jitsi-meet">
    Options Indexes MultiViews Includes FollowSymLinks
    AddOutputFilter Includes html
    AllowOverride All
    Order allow,deny
    Allow from all

    RewriteEngine on
    RewriteBase "/jitsi-meet/"
    RewriteRule "^([a-zA-Z0-9]+)$" "index.html"
</Directory>

<Location /jitsi-meet/config.js>
   Require all granted
</Location>

<Location /jitsi-meet/external_api.js>
  Require all granted
</Location>

<Location /jitsi-meet/http-bind>
    ProxyPreserveHost on
    ProxyPass "http://localhost:5280/http-bind/"
    ProxyPassReverse "http://localhost:5280/http-bind/"
    Require all granted
</Location>
```

Jitsi-meet-web .deb package version: 1.0.4127-1
OS: Debian 9.12 (stretch) amd64
apache2 package version: 2.4.25-3+deb9u

**Comment by JurjenBokma** [comment]
This works. Thx! At first we messed up because our Directory directive mentioned /var/www/jitsi, while that was a symbolic link to /usr/share/jitsi. So it should have mentioned /usr/share/jitsi itself.
Also, the jitsi installation scripts seem to have attempted to edit our Apache config. We had to fix that.

**Comment by saghul** [comment]
Glad you got it working!

This is not the typical setup, so while the stock Debian install will need manual adjustments, this setup is supported in the sense that if there are bugs with it we should fix them.

Adding the steps you followed to the handbook would be nice, if you are up for writing a PR.

**Comment by ilfrick** [comment]
> ### Description:
> I installed jitsi-meet on an existing webserver that has an existing domain-name and SSL certificate. As such I didn't want to increase my webserver's configuration's complexity by adding another SSL certificate and subdomains with SNI or attempting to get a wildcard-certificate.
> 
> I thus attempted installing jitsi-meet into a webserver sub-directory. Looking at #2422, #4917, #381 there seemed to be no final answer yet whether that is "officially" supported and how to fully configure it.
> 
> I found out, that indeed two source-files outside /etc need modification, which points to subdirectory installation either not being supported, or bugs being present WRT it:
> 
> /usr/share/jitsi-meet/base.html : content had to be replaced with
> 
> ```
>     <base href="/jitsi-meet/" />
> ```
> 
> /usr/share/jitsi-meet/index.html : a few absolute-path server-side javascript-references had to be modified
> 
> ```
>     <script></script>
>     <script></script>
>     <script></script>
> ```
> 
> Other than that just modifying the configuration was sufficient to make this setup work:
> /etc/jitsi/meet/[domain]-config.js :
> 
> ```json
>    bosh: '//<domain>/jitsi-meet/http-bind',
> ```
> 
> For reference, this is the (slightly stripped down) copy of the apache2 configuration file for jitsi-meet installed to subdirectory //jitsi-meet/. With this configuration, jitsi-meet indeed appears to run flawlessly.
> 
> ```apache-config
> ## Derived from auto-generated site-config files as follows:
> ## - Deleted Virtual Server
> ## - replaced DocumentRoot with Alias
> ## - prefixed existing Alias and Location commands with /jitsi-meet
> ## - Moved proxypass into a new <Location> block
> ## - Moved RewriteEngine into the <Directory> block.
> ## - change "bosh" in the jitsi -config.js to point to the corret http-bind 
> 
> ## Other hacks for jitsi-meet in subdir:
> ## - modify base.html
> ## - modify index.html to fix all the "include virtual" statements that go
> ##   directory to the root dir.
> 
> Alias "/jitsi-meet/config.js" "/etc/jitsi/meet/<domain>-config.js"
> Alias "/jitsi-meet/external_api.js" "/usr/share/jitsi-meet/libs/external_api.min.js"
> Alias "/jitsi-meet" "/usr/share/jitsi-meet"
> 
> <Directory "/usr/share/jitsi-meet">
>     Options Indexes MultiViews Includes FollowSymLinks
>     AddOutputFilter Includes html
>     AllowOverride All
>     Order allow,deny
>     Allow from all
> 
>     RewriteEngine on
>     RewriteBase "/jitsi-meet/"
>     RewriteRule "^([a-zA-Z0-9]+)$" "index.html"
> </Directory>
> 
> <Location /jitsi-meet/config.js>
>    Require all granted
> </Location>
> 
> <Location /jitsi-meet/external_api.js>
>   Require all granted
> </Location>
> 
> <Location /jitsi-meet/http-bind>
>     ProxyPreserveHost on
>     ProxyPass "http://localhost:5280/http-bind/"
>     ProxyPassReverse "http://localhost:5280/http-bind/"
>     Require all granted
> </Location>
> ```
> 
> Jitsi-meet-web .deb package version: 1.0.4127-1
> OS: Debian 9.12 (stretch) amd64
> apache2 package version: 2.4.25-3+deb9u

@dvdkhlng thanks, I've been trying to achieve this for a long time. One clarification: is the "apache2 configuration file" you pasted is one of the conf files located in /etc/apache2/sites-enabled? Must it be the default one? If not, how does it relate to the default one?
Thanks again.

**Comment by briveira** [comment]
Really?  Cant believe this. NO WEBAPP should be designed forced to be at root path. This is a no brainer :(

**Comment by saghul** [comment]
Sure, are you willing to send patches?

**Comment by juntong20XX** [comment]
Is it still works in 2024? I want try this…

**Comment by giggls** [comment]
Yes, seems to work. I did it with the docker based setup and the following Dockerfile:

```
FROM docker.io/jitsi/web:stable

ARG BASEPATH=/jitsi-meet/

RUN sed -i -e "s;<base href=\"/\" />;<base href=\"${BASEPATH}\" />;g" /usr/share/jitsi-meet/base.html

RUN sed -i -e "s;<\!--#include virtual=\"/;<\!--#include virtual=\"${BASEPATH};g" /usr/share/jitsi-meet/index.html
```
There is only one minor thing:
If you close conferences you end up at base URL nevertheless.

**Comment by v-bulynkin** [comment]
@giggls, is it still working for you? I have a black screen in browser and the following in logs (I use `/jitsi` as URL suffix):
```
jitsi-web  | 2026/04/08 21:46:29 [error] 284#284: *2 open() "/config/config.js" failed (13: Permission denied), client: 172.18.0.2, server: _, request: "GET /jitsi HTTP/1.1", subrequest: "/jitsi/config.js", host: "example.com"
jitsi-web  | 2026/04/08 21:46:29 [error] 284#284: *2 open() "/config/interface_config.js" failed (13: Permission denied), client: 172.18.0.2, server: _, request: "GET /jitsi HTTP/1.1", subrequest: "/interface_config.js", host: "example.com"
jitsi-web  | 172.18.0.2 - - [08/Apr/2026:21:46:29 +0300] "GET /jitsi HTTP/1.1" 200 3563 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:149.0) Gecko/20100101 Firefox/149.0"
```

**Comment by giggls** [comment]
I did not try the latest docker version yet but I would not expect it to fail. I just fixed the Markdown for the dockerfile I am using.
