### ISSUE TITLE
Remove 3 dots on the right side of Video button to access more functionality

### ISSUE THREAD

**Issue by amitmishra0807** [jitsi/jitsi-meet#6917]
iOS version 2.8.1
how to access and Hide 3 dots on the right side of the video button
i use below code to hide chat and invite but no any method for hiding 3 dots
builder.setFeatureFlag(“chat.enabled”, withBoolean: false)
builder.setFeatureFlag(“invite.enabled”, withBoolean: false)

is working but no option to remove 3 Dots to

**Comment by luixxiul** [comment]
Please rewrite the report by following the template below:

````
<!--
Thank you for suggesting an idea to make Jitsi Meet better.

Please fill in as much of the template below as you're able.

Note that the ultimate decision for implementing features lies on the Jitsi team, not all feature requests shall be accepted.
-->

**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
````

For now I am going to close the issue until the request will be more clear. Thanks!

**Comment by amitmishra0807** [comment]
iOS version 2.8.1
how to access and Hide 3 dots on the right side of the video button
i use below code to hide chat and invite but no any method for hiding 3 dots
builder.setFeatureFlag(“chat.enabled”, withBoolean: false)
builder.setFeatureFlag(“invite.enabled”, withBoolean: false)

is working but no option to remove 3 Dots to

**Comment by saghul** [comment]
There is no way to remove it at the moment.

**Comment by baijianghai** [comment]
Android 2.8.2
how to access and Hide 3 dots on the right side of the video button
i use below code to hide chat and invite but no any method for hiding 3 dots
builder.setFeatureFlag(“chat.enabled”, withBoolean: false)
builder.setFeatureFlag(“invite.enabled”, withBoolean: false)

but no option to remove 3 Dots to

is it any way to remove it

**Comment by saghul** [comment]
Same answer as before, sorry. We have no flag for this.
