### ISSUE TITLE
Xcode 11.4 Exported SDK do not include x86_64 (Simulator) architecture

### ISSUE THREAD

**Issue by umairgillani94** [jitsi/jitsi-meet#6924]
### Description:

I export the SDK for iOS using below command using Xcode 11.4 but it doesn't include the simulator support

### Steps to reproduce:

use this command using Xcode11.4
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination=‘generic/platform=iOS’ -configuration Release archive

### Expected behavior:

Sdk should include simulator architecture

### Actual behavior:
Used below command to export SDK

xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination=‘generic/platform=iOS’ -configuration Release archive

When I checklist of architectures in the exported framework it says:

Non-fat file: /Users/umairgillani/Library/Developer/Xcode/DerivedData/jitsi-meet-byuitotfesbuupfgntpadgftdfhq/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/JitsiMeet.framework/JitsiMeet is architecture: arm64

Need help to export it for both arm64 as well as for Simulators

### Server information:

- Jitsi Meet version: Jitsi-meet_4603
- Operating System: macOS Catalina 10.15.3

### Client information:

Xcode 11.4

**Comment by saghul** [comment]
Have you tried using the script we provide to make SDK builds? https://github.com/jitsi/jitsi-meet/blob/master/ios/scripts/release-sdk.sh

**Comment by umairgillani94** [comment]
yes i tried that but still got the same output when running below command 

lipo -info /Users/umairgillani/Personal/jitsi-meet-ios-sdk-releases/Frameworks/JitsiMeet.framework/JitsiMeet 

Non-fat file: /Users/umairgillani/Personal/jitsi-meet-ios-sdk-releases/Frameworks/JitsiMeet.framework/JitsiMeet is architecture: arm64

**Comment by saghul** [comment]
Thanks, I’ll take a look!

**Comment by umairgillani94** [comment]
@saghul do we have any update on this as we are stuck with our deliverables. 
I will be thankful to you for some quick fix for this.

**Comment by wahab054** [comment]
Having same issue in my team as well. It is a major obstacle for us.
@saghul Please help out.

**Comment by Echolon** [comment]
Hi, does this still appear?

**Comment by umairgillani94** [comment]
yes, it does.

**Comment by saghul** [comment]
We no longer support Xcode 11, please update to Xcode 12.
