### ISSUE TITLE
Prejoin button disabled

### ISSUE THREAD

**Issue by c-prompt** [jitsi/jitsi-meet#6926]
Might be related to #6723. I cannot get prejoin to work. The prejoin button is disabled and users cannot enter the room:

![prejoin_disabled](https://user-images.githubusercontent.com/10625352/83358609-61a73480-a33a-11ea-9fa7-7e8b619c9115.png)

You can also see from the HTML that the class shows disabled:
`<div class="prejoin-btn prejoin-btn--disabled">Join meeting<div class="prejoin-btn-options"><div class="jitsi-icon prejoin-btn-icon"><svg fill="none" height="14" width="14" viewBox="0 0 10 6"><path clip-rule="evenodd" d="M8.07.248a.75.75 0 111.115 1.004L5.656 5.193a.75.75 0 01-1.115 0L1.068 1.252A.75.75 0 012.182.248L5.1 3.571 8.07.248z"></path></svg></div></div></div>`

Reviewing the [prejoin code](https://github.com/jitsi/jitsi-meet/search?p=4&q=prejoin&unscoped_q=prejoin) hasn't helped figure out what is disabling the button. When I set `prejoinPageEnabled` to `false` in `\etc\jitsi\meet\config.js`, I go into the room without issue. Of note, I'm using JWT but not sure if that has anything to do with the problem. I don't see anything in the logs that would suggest the problem and I'm not sure how else to troubleshoot.

Any ideas?

---------
Versions:
Debian 9.12
Browsers: tested on Firefox 76.0.1 and Chrome 83.0.4103.61
jicofo 1.0-596-1
jitsi-meet 2.0.4682-1
jitsi-meet-prosody 1.0.4166-1
jitsi-meet-tokens 1.0.4166-1
jitsi-meet-web 1.0.4166-1
jitsi-meet-web-config 1.0.4166-1
jitsi-videobridge2 2.1-214-g5a7a5881-1

**Comment by saghul** [comment]
I think JWT is the problem here. Do your tokens provide a display name?

**Comment by c-prompt** [comment]
Darn - I was afraid of that. Yes, the tokens include a display name and users are unable to change.

**Comment by Echolon** [comment]
Hi, does this still happen?

**Comment by c-prompt** [comment]
@Echolon, I changed `prejoinPageEnabled` to `true` in `\etc\jitsi\meet\config.js`. Then `/etc/init.d/prosody restart && /etc/init.d/jicofo restart && /etc/init.d/jitsi-videobridge2 restart` (I also tried rebooting). The prejoin functionality/screen didn't even show (i.e., it didn't show as disabled - it didn't show at all). Just went straight into the meeting. Tried on both mobile and web. Was this functionality removed?

Versions:
Debian 10
Browsers: tested on Firefox 80.0.1 and Chrome 85.0.4183.102 and Android Chrome
jitsi-meet 2.0.4966-1

**Comment by saghul** [comment]
There is a setting to disable it, any chance you checked that? Go to settings, More.

**Comment by saghul** [comment]
I took a look and this is indeed a but, Prejoin doesn't check the JWT for the display name, nor does the JWT update the display name when processed.

**Comment by saghul** [comment]
Should be fixed by https://github.com/jitsi/jitsi-meet/pull/7699 -- @vp8x8 please reference it in the commit message.

**Comment by c-prompt** [comment]
Looks like it works on desktop but not on mobile app. Mobile app goes right into meeting.

**Comment by saghul** [comment]
Prejoin is not yet implemented on mobile.
