### ISSUE TITLE
Any plan or road map for firebase deeplinking?

### ISSUE THREAD

**Issue by subhendukundu** [jitsi/jitsi-meet#6927]
**Is your feature request related to a problem you are facing?**
The current behavior is on click on the shared URL it takes the user to playstore which I understand due to manual deeplinking. However, if the app is installed it's not taking the user to the app. To join a meeting, we have to copy the link and paste it in the input and join. 

**Describe the solution you'd like**
Ideally, if I have the deeplinking enabled it should join automatically.
For example if I have www.exaample.com/somerandomMeetingId and click on this on my mobile with the app installed, it should open the app and add me to the meeting.

**Describe alternatives you've considered**
So far I have enabled deeplinking with firebase. However as jitsi app is not like any react-native app, it's not working with `react-native-firebase/app`. I can play around with this if I get some idea of how to fix it.

**Comment by saghul** [comment]
We already have Firebase Dynamic Links enabled and working with Jitsi Meet. Are you doing your own build? Do you have your own deployment?

**Comment by subhendukundu** [comment]
Yes, I am doing my own build and own deployment. The server on AWS. Create another subdomain for the firebase dynamic links which is connected to firebase.

**Comment by saghul** [comment]
Then make sure you are running the latest stable and configure the MOBILE_DYNAMIC_LINK property in interface_config.js: https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js

**Comment by l3d00m** [comment]
I'd assume this is resolved as not further comments were provided. If it still persist, you might also use the forums for questions that are not bug reports or feature requests. https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
