### ISSUE TITLE
How I can customize Mobile App UI? 

### ISSUE THREAD

**Issue by blukhi99** [jitsi/jitsi-meet#6928]
i did try to Start from source code but. i am getting lots of error.
it has plugin version are mismatch maven published error, and copy file from sound errors.
from react command can't run because, it's uses as SDK and error at SDK.

Please, Get Back to me
thank you for reading.

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
