### ISSUE TITLE
Android video call cancel after continuously loading is there not cancelling in the call

### ISSUE THREAD

**Issue by iddineshkumar** [jitsi/jitsi-meet#6929]
![jitsi](https://user-images.githubusercontent.com/60511942/83375509-b30ffc00-a3ec-11ea-9ee7-56424f86af4f.jpg)
I'm using this version  implementation('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }

this is my full source code
package com.triton.salveo.activity;

import androidx.fragment.app.FragmentActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;

import com.facebook.react.modules.core.PermissionListener;

import org.jitsi.meet.sdk.JitsiMeetActivity;
import org.jitsi.meet.sdk.JitsiMeetActivityDelegate;
import org.jitsi.meet.sdk.JitsiMeetActivityInterface;
import org.jitsi.meet.sdk.JitsiMeetConferenceOptions;
import org.jitsi.meet.sdk.JitsiMeetView;

import java.net.MalformedURLException;
import java.net.URL;

public class VideoCallActivity extends FragmentActivity implements JitsiMeetActivityInterface {
    private JitsiMeetView view;
    private String setRoom = "";
    String TAG  ="VideoCallActivity";

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        JitsiMeetActivityDelegate.onActivityResult(
                this, requestCode, resultCode, data);
    }

    @Override
    public void onBackPressed() {
        JitsiMeetActivityDelegate.onBackPressed();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        view = new JitsiMeetView(this);
        Bundle extras = getIntent().getExtras();
        if (extras != null) {
            setRoom = extras.getString("id");
            Log.w(TAG,"Setroom :"+" "+setRoom);
        }

        JitsiMeetConferenceOptions options = null;
        try {
            options = new JitsiMeetConferenceOptions.Builder()
                    .setServerURL(new URL("https://meet.jit.si"))
                    .setRoom(setRoom)
                    .setAudioMuted(false)
                    .setVideoMuted(false)
                    .setAudioOnly(false)
                    .setWelcomePageEnabled(false)
                    .build();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        /*JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                .setRoom("https://meet.jit.si/test123")
                .build();*/
        view.join(options);

        setContentView(view);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        view.dispose();
        view = null;

        JitsiMeetActivityDelegate.onHostDestroy(this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

    @Override
    public void onRequestPermissionsResult(
            final int requestCode,
            final String[] permissions,
            final int[] grantResults) {
        JitsiMeetActivityDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onResume() {
        super.onResume();

        JitsiMeetActivityDelegate.onHostResume(this);
    }

    @Override
    protected void onStop() {
        super.onStop();

        JitsiMeetActivityDelegate.onHostPause(this);
    }

    @Override
    public void requestPermissions(String[] strings, int i, PermissionListener permissionListener) {

    }
}

**Comment by saghul** [comment]
You haven’t implemented onConferenceTerminated to finish your activity.

Why have you rolled your own activity instead of using / extending JitsiMeetActivity ? This would’ve been already taken care of.

**Comment by iddineshkumar** [comment]
Hi @saghul, https://github.com/jitsi/jitsi-meet/issues/6930 Can you check this one.
Still not cancel the call. Can you guide me.

**Comment by iddineshkumar** [comment]
@saghul  I have tried all ways but still not resolve my problem, Can you guide me.

**Comment by bahadirerdemm** [comment]
Did you solve the bug ?

**Comment by iddineshkumar** [comment]
> Did you solve the problem ?

Not yet resolve. Any idea for you?

**Comment by iddineshkumar** [comment]
https://github.com/jitsi/jitsi-meet/issues/6930

**Comment by iddineshkumar** [comment]
I have raised two tickets but properly not response

**Comment by bahadirerdemm** [comment]
I solved the problem.
Add this line inside the onCreate function
`jitsiMeetView.setListener(this);`

**Comment by iddineshkumar** [comment]
> I solved the problem.
> Add this line inside the onCreate function
> `jitsiMeetView.setListener(this);`

Thank you so much.

**Comment by thilagrai-aglab** [comment]
> You haven’t implemented onConferenceTerminated to finish your activity.
> 
> Why have you rolled your own activity instead of using / extending JitsiMeetActivity ? This would’ve been already taken care of.

@saghul I am using JitsiMeetActivity.launch. It creates two different application. Is there any way to launch JitsiMeet sdk inside my application. Please help me in this issue

**Comment by fightingmonsters1969** [comment]
Hello is there anyone here that i can pay to add jitsi to my website and server for me, i am sure this is not normal but i have no idea how to do it or where to start
