### ISSUE TITLE
Android Jitsi video call terminated the call  after redirect the page is not working

### ISSUE THREAD

**Issue by iddineshkumar** [jitsi/jitsi-meet#6930]
### Description:
 Video call terminated after redirect the next page is not working for android.

### Steps to reproduce:

1.  Start video call activity
2.  Video call terminated after the same page is there

### Expected behavior:
Video call terminated after will go next page. But call terminated after the log is coming perfectly. But did not go redirect another page.
@Override
public void onConferenceTerminated(Map<String, Object> data) {
    JitsiMeetLogger.i("Conference terminated: " + data);
    startActivity(new Intent(VideoCallExActivity.this,LoginActivity.class));
    finish();
}

### Actual behavior:
Video call terminated after did not go the next page. But call terminated after the log is coming perfectly.
@Override
public void onConferenceTerminated(Map<String, Object> data) {
    JitsiMeetLogger.i("Conference terminated: " + data);
    startActivity(new Intent(VideoCallExActivity.this,LoginActivity.class));
    finish();
}

### Jitsi Meet version:
    implementation('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }

### Source code information:

package com.triton.salveo.activity;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;

import com.facebook.react.modules.core.PermissionListener;
import com.triton.salveo.R;

import org.jitsi.meet.sdk.JitsiMeet;
import org.jitsi.meet.sdk.JitsiMeetActivity;
import org.jitsi.meet.sdk.JitsiMeetActivityInterface;
import org.jitsi.meet.sdk.JitsiMeetConferenceOptions;
import org.jitsi.meet.sdk.JitsiMeetViewListener;
import org.jitsi.meet.sdk.log.JitsiMeetLogger;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

public class VideoCallExActivity extends AppCompatActivity  implements JitsiMeetActivityInterface, JitsiMeetViewListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_call_ex);
        // Initialize default options for Jitsi Meet conferences.
        URL serverURL;
        try {
            serverURL = new URL("https://meet.jit.si");
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions defaultOptions
                = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setWelcomePageEnabled(false)
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);

        JitsiMeetConferenceOptions options
                = new JitsiMeetConferenceOptions.Builder()
                .setRoom("test36r13878")
                .build();
        // Launch the new activity with the given options. The launch() method takes care
        // of creating the required Intent and passing the options.
        JitsiMeetActivity.launch(this, options);
    }

    @Override
    public void requestPermissions(String[] strings, int i, PermissionListener permissionListener) {

    }

    @Override
    public void onConferenceJoined(Map<String, Object> data) {
        JitsiMeetLogger.i("Conference joined: " + data);
        // Launch the service for the ongoing notification.
        // JitsiMeetOngoingConferenceService.launch(this);
    }

    @Override
    public void onConferenceTerminated(Map<String, Object> data) {
        JitsiMeetLogger.i("Conference terminated: " + data);
        startActivity(new Intent(VideoCallExActivity.this,LoginActivity.class));
        finish();
    }

    @Override
    public void onConferenceWillJoin(Map<String, Object> data) {
        JitsiMeetLogger.i("Conference will join: " + data);
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        finish();
    }

}

**Comment by l3d00m** [comment]
Please don't just reopen a new issue (#6929). If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org. 

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
