### ISSUE TITLE
[Feature request] Add "Vote counter"

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet#6934]
Hi. Jitsi has nice feature: "raise/lower hand" option. This feature can be used for voting.

In last video conference with my students there were 70 persons (including me) within room. I need my students to vote for 2 times. I asked them to use the "raise/lower" hand option. I was needing to count the "raised hands" manually & this is some thing not convenient & take time ....

My suggestion is to add "Vote counter" show the total number of "raised hands". It should be located beside the (pointer which showing the total number of current - at the moment - participants in the conference which is already existing in Jitsi). The "Vote counter" should appearing when at least one of participants "raise hand", & should remain till all "raised hands" lowered when it should disappearing.....

Many thanks for your efforts.

**Comment by edvinkuric** [comment]
@Nokia808 maybe this helps you: 
there is a similar feature already PR'd (polls): https://github.com/jitsi/jitsi-meet/pull/3827

**Comment by Nokia808** [comment]
This issue is important specially at this time of COVID19 continue tragedy ! It will add significant functionality to Jitsi. 

Unfortunately, the PR to full this gap is closed & no one working on it at this time !

**Comment by edmundlaugasson** [comment]
Vote counter is good, but I propose to add [poll feature, like in Zoom](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-meetings). Would be much more useful and straightforward to use. Also much more flexible.

**Comment by Nokia808** [comment]
From my side I'm ready to fund for adding this feature to Jitsi. Just say how much the cost to cover the work & time to implement this feature to Jitsi.

**Comment by Nokia808** [comment]
Hello. 

If this feature will see life, I have the following idea about it, & developers have final decision:
1) there should be an option to ask for voting. This option should be ONLY AVAILABLE for moderator (person who create room) not for other participant. Let we say the supposed option will be in the form of an "icon" refer to "ask for voting" (just as icon for option for "raise hand").
2) when person who create the room click on icon of "ask for voting", then 2 options (Yes / No) will appear for every other participant other than creator of room. By these 2 options, each of other participant can vote either "Yes" or "No".
3) there should be a vote counter appear for every participant when "ask to vote" option activated by creator. The "Voting Counter" should show total "Yes" voting number & total "No" voting number.
4) the creator can stop voting, & when she/he do this then "Yes" / "No" / "Voting counter" all should disappear.

Thank you.

**Comment by asfernandes** [comment]
Is this feature done or not? From this issue it's like not, but testing Jitsi in docker I see something like it already implemented.

**Comment by saghul** [comment]
We did implement polls yes.

**Comment by chhaas** [comment]
How is the polling feature to be enabled in Jitsi (self-hosted). Though searching the web, I could not find any information about enabling polls in Jitsi-config.
