### ISSUE TITLE
Pre join page is nor translatet

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#6937]
### Description:

The pre join page is not translatet.

### Expected behavior:

The pre join page should be translatet depending on the language settings.

### Actual behavior:

The pre join page is allways english.

**Comment by luixxiul** [comment]
Is it not because the translation files are simply not ready yet?

**Comment by luixxiul** [comment]
Actually it is so. This depends on localization work and strings are available for localization. cf: https://github.com/jitsi/jitsi-meet/pull/6943/files#diff-3dfc31e15ddcb77dc38a42441d70a32fR501
