### ISSUE TITLE
My jitsi instance does not work for all users

### ISSUE THREAD

**Issue by PH-F** [jitsi/jitsi-meet#6938]
Hello,

Some users get the error "ERR_EMPTY_RESPONSE" in their browser.
When I look in the  nginx accesslog I see these uses come in with HTTP/1.1 instead of HTTP/2

How is this possible?
Thank you in advance

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
