### ISSUE TITLE
Optimize for least bandwidth by default, audio video toggle, country specific routing

### ISSUE THREAD

**Issue by compusolve-rsa** [jitsi/jitsi-meet#6939]
**Is your feature request related to a problem you are facing?**
I am seeking an audio/video conference solution without lock-in to hi-res high-bandwidth defaults with an option to toggle both video and audio before the connection is made, and an option to avoid routing through certain countries.

**Usage cases**
Chatting with family and friends when located on a remote farm in an emerging country with 2G, 3G, edge, Sure cities may have 4G but rural areas are slow on roll out and don't get the upgrades that city folk get. Another issue is rural cell networks are at times very erratic, Would be great to see jitsi as a peoples communication solution and not as a silicon valley autocracy forcing the common people to pay for gigs when money for food is more important. As an example I never chat via video on whatsapp since it would eat my pay-as-you-go 100meg data bundle too quickly.

**Describe the solution you'd like**
Optimize for least bandwidth by default.
Give option to toggle video and/or audio before the connection is made.
Give option to avoid routing through any given country.

**Describe alternatives you've considered**
Whatsapp, Telegram, Signal (All of them are lock-in)

**The assumption that the whole world is on high bandwidth**
The first programmers believed in efficient and optimised code. They had to since they had kilobytes of ram to work with in those days. But they laid down the most important principle of programming at the very start of the computer era. Today is very different. We have programmers who have no consideration for a persons data usage and set about writing apps that are gig-eaters, aka bloatware. What they fail to realise is that it makes the user poorer by spending money on data bundles, which sure makes the cell companies the fat-cats, but also makes programmers poorer, because most folk do not want to pay for subscriptions when they are already paying for the gigs. Why pay twice? Modern programmers need to realise the world is a very unequal place. The northern hemisphere may be well into rolling out 5G, but a remote farm in the southern hemisphere might only be getting sporadic 3G.

If jitsi is truly a peoples app that offers a way out of autocratic software apps who only care about bottom line, then the developers need to understand the massive unequal divide of the haves and have nots in the world. Forcing high bandwidth on poor people who can only afford small data bundles is not fair to them. So optimize your app so everyone can use it. The two requests of least bandwidth and audio video toggle before connection alone will take a huge processing burden off the jitsi network, so processing power can be used for those who want a high-res connection. 

**Country specific routing**
An option screen with names of countries that the user can toggle on and off. Doesn't need an explanation.

**Comment by luixxiul** [comment]
> Forcing high bandwidth on poor people who can only afford small data bundles is not fair to them. So optimize your app so everyone can use it.

Why don't you set video quality to low bandwidth?

![Clipboard01](https://user-images.githubusercontent.com/3362943/83558593-c7461d00-a502-11ea-98de-7d66a95302d2.png)

If you still feel somewhat forced, I'd recommend to check this list to see what suits your needs best: https://directory.fsf.org/wiki/Category/Live-communications/conferencing

**Comment by compusolve-rsa** [comment]
Thank you for the feedback. I have tried this via web browser visiting
meet.jit.si. The web page will not allow a lower resolution. 

On 2020-06-02 20:59, Suguru Hirahara wrote:

>> Forcing high bandwidth on poor people who can only afford small data bundles is not fair to them. So optimize your app so everyone can use it.
> 
> Why don't you set video quality to low bandwidth? 
> 
> [1] 
> 
> If you still feel somewhat forced, I'd recommend to check this list to see what suits your needs best: https://directory.fsf.org/wiki/Category/Live-communications/conferencing 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1]
https://user-images.githubusercontent.com/3362943/83558593-c7461d00-a502-11ea-98de-7d66a95302d2.png
[2]
https://github.com/jitsi/jitsi-meet/issues/6939#issuecomment-637745034
[3]

**Comment by saghul** [comment]
>  The web page will not allow a lower resolution.

How do you mean? Don't you see the option? It's in the "3 dots" menu, then "Manage call quality".

**Comment by compusolve-rsa** [comment]
Thanks for the reply. There is a gear, but no three dots on the webpage.
See screenshot.

On 2020-06-03 09:27, Saúl Ibarra Corretgé wrote:

>> The web page will not allow a lower resolution.
> 
> How do you mean? Don't you see the option? It's in the "3 dots" menu, then "Manage call quality". 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/jitsi/jitsi-meet/issues/6939#issuecomment-638012789
[2]

**Comment by saghul** [comment]
I see no screenshot. Might be because you are using email instead of the GH interface. There should be a 3 dots button on the bottom right, once you are in a meeting.

**Comment by compusolve-rsa** [comment]
Thanks.

On 2020-06-03 11:06, Saúl Ibarra Corretgé wrote:

> I see no screenshot. Might be because you are using email instead of the GH interface. There should be a 3 dots button on the bottom right, once you are in a meeting. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/jitsi/jitsi-meet/issues/6939#issuecomment-638066702
[2]

**Comment by gr01d** [comment]
Hi, I have the same problem too. I use the jitsi meet android app and they don't have the video quality settings. It is always set to max, and it eats up all of my internet bandwidth. This is used for online school/classes so please add an option to lower the bandwidth/video quality on the Android app. Thank You.
