### ISSUE TITLE
reconnect switches on camera and microphone, loses password

### ISSUE THREAD

**Issue by telephon** [jitsi/jitsi-meet#6940]
### Description:

When the browser reconnects after the computer wakes up, jitsi switches on camera and microphone even if it was off before. It also sets the password to nil. This causes a possibly intrusive situation: you may have assumed that the microphone and camera remain off. Also, anyone in possession of the URL may now enter the session, or may have entered it already.

### Steps to reproduce:

1. as a host: switch off microphone and camera in jitsi, set a password
2. put computer to sleep (e.g. close laptop)
3. wake computer up again after 10 min (e.g. open laptop)
4. note how jitsi informs that it is reconnecting, and after this is completed, the camera and microphone switches on.

The same happens if the network is off for a similar period.

### Expected behavior:

All settings, including this one, should survive a temporary network disconnect and/or sleep.

### Actual behavior:

All these settings are lost.

### Client information:

- Browser / app version:  Iron (chromium) and Safari
- Operating System: macOS 10.15.5 Browser

**Comment by telephon** [comment]
The same data loss concerns the settings, in particular the group privacy sensitive settings for "Everybody joins muted" etc.

All in all, this is an important issue, I think, with regard to user trust in jitsi.

Any news on this?

**Comment by saghul** [comment]
Hey there,

This is an interesting case. There are 2 sets of settings at play here:

- Personal settings: audio / video 
- Room settings: password / everyone starts muted

The former should now be solved because we have the prejoin screen, so that one should show up when reconnecting.

The latter is trickier, because if you were the only participant the room is gone and it's re-created, and we don't save those settings because they are applied per room, so I'm not sure how we'd go about fixing this one.

If there was anyone else in the room this wouldn't be a problem, because the room holds on to those settings.

**Comment by telephon** [comment]
> The former should now be solved because we have the prejoin screen, so that one should show up when reconnecting.

I see, that sounds good – will this be in the next stable release?

> The latter is trickier, because if you were the only participant the room is gone and it's re-created, and we don't save those settings because they are applied per room, so I'm not sure how we'd go about fixing this one.
> 
> If there was anyone else in the room this wouldn't be a problem, because the room holds on to those settings.

It is OK that the room doesn't hold onto settings after everyone has left. If it is only the case if I am alone in the room, then the problem is already a bit less pressing (I have to test this with the new version).

Wouldn't normally the browser hold to such settings across re-entry to a room? It does so for the login information.

**Comment by telephon** [comment]
I'll test it asap with the new version.

**Comment by telephon** [comment]
The largest part of the issue is solved (video and audio stay off). Thank you!
The settings still disappear, but that is not such a large issue.

**Comment by saghul** [comment]
I'm going to close this then, cheers.
