### ISSUE TITLE
Allow livestreaming to a "Custom" RTMP endpoint

### ISSUE THREAD

**Issue by chrishobcroft** [jitsi/jitsi-meet#6942]
**Is your feature request related to a problem you are facing?**

I would like to livestream my Jitsi calls via the Jitsi Meet app for Android.

When selecting this option, I am asked for a stream key for streaming on YouTube.

I don't want to livestream via YouTube. I want to livestream to an `rtmp` endpoint on my own streaming platform, using [`simple-streaming-server`](https://github.com/videoDAC/simple-streaming-server).

**Describe the solution you'd like**

I would like to be able to configure to stream to a custom `rtmp` endpoint, with stream key, and to be able to configure some simple streaming settings like "stream resolution" (e.g. `1280x720`), "keyframe interval" (e.g. `2 seconds`), "frames per second" (e.g. `30`), "video bitrate" (e.g. `500 kbps`) and "audio bitrate" (e.g. `64 kbps`).

**Describe alternatives you've considered**

I have considered streaming to YouTube, and I have a lot of experience of doing this in the past. However, this goes against my preference for open-source decentralised systems, instead of closed-source centralised systems.

## Screenshots

Here is the option I have when configuring the livestream... why only YouTube?!

![jitsi screenshot](https://user-images.githubusercontent.com/2212651/83620566-1ba4d780-a5ab-11ea-9864-65ec485fce2a.png)

**Comment by l3d00m** [comment]
Thanks for your detailed request. #2829 is already a similar request with lots of comments and ideas there, so I'd close this in favour of it and ask you to leave your comments there to have them all in one place.
