### ISSUE TITLE
startWithAudioMuted mute all audio instead of disabling microphone.

### ISSUE THREAD

**Issue by BurguerJohn** [jitsi/jitsi-meet#6944]
### Description:
startWithAudioMuted = true does set the "Microphone icon" to display that your microfone is disabled, but still request to access the user microphone and if the permission is denied it will remove all audio from the room, this only occur with the audio, startWithVideoMuted work fine.

### Steps to reproduce:

1. Create a Jitsi server
2. Set startWithAudioMuted = true inside config.js
3. Create a server.
4. Room will ask for microphone permission, it should not since we don't want the user audio.
5. If permission is denied, the user will be unable to listen to the audio of all participants. If permission is allowed, the audio from other participants will work fine and your microfone will be muted.

### Expected behavior:

1. It should not ask for microphone permission
2. It should not remove the audio from other participants if the permission is denied.

### Actual behavior:

1. Ask for microphone permission
2. If denied, user can't listen to the audio from the room

### Server information:

- Jitsi Meet version: package.json show **version": "0.0.0"** ?
- Operating System:ubuntu 18.04

### Client information:

- Browser / app version: Chrome
- Operating System: Windows 10

**Comment by Echolon** [comment]
rel.

#5801
#5417
#6191

**Comment by BurguerJohn** [comment]
> rel.
> 
> #5801
> #5417
> #6191

Not really related to my problem since those are interface problems and improvements.

**Comment by philkaroo** [comment]
Hello, this is still an issue (release 2.0.89.22). Even though the microphone is disabled/deactivated with option startWithAudioMuted, the participant is asked for permission to enable/disable it. One would expect the browser to stay quiet.  Setting the Permissions-Policy to microphone=(), in the header of the request, to overcome the iframe's 'allow' attribute permission won't work with Firefox (partially supported - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/microphone). Config's option 'startSilent' will work but users won't understand why the audio and video buttons don't behave the same way. Any pointer pls ?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/ea4e20f9a7c02a8eba5c32c59dde46b75d949e68/config.js#L611

**Comment by philkaroo** [comment]
Groovy, thanks !
