### ISSUE TITLE
issues with iphone safari

### ISSUE THREAD

**Issue by chancemcox** [jitsi/jitsi-meet#6948]
### Description:

this is via api and connecting to alpha.jitsi.net

https://www.youtube.com/watch?v=BrwAvKwupsE

issue 1: the mic and video buttons require double taps to start.

issue 2: when connected, the self video on the phone is only a image, not a video

### Steps to reproduce:

1.  Go to https://dev.docsink.com/meet/call/test on iPhone

### Expected behavior:

Mic and Video start unmuted and shouldnt take 2 taps to unmute
self video should be a video

### Actual behavior:

video and mic start muted and take two clicks to enable
self video is just an image

### Server information:

- Jitsi Meet version:  whatever is on alpha.jitsi.net
- Operating System: whatever is on alpha.jitsi.net

### Client information:

- Browser / app version: safari
- Operating System: iphone 13.3

**Comment by chancemcox** [comment]
Also if your joining an existing meeting, you cant un mute your camera

**Comment by mangmang2006** [comment]
issue 2 looks to be the same to https://community.jitsi.org/t/the-image-freezes-when-we-start-video-conversation-via-safari-or-chrome-on-ios-phones/53992

**Comment by chancemcox** [comment]
@mangmang2006 it is the same but in that issue a work around was found, but will a fix be added for it?

**Comment by chancemcox** [comment]
Has there been any movement on this?

**Comment by chancemcox** [comment]
the Safari browser on my mac is similar, it doesnt load unmuted you have to click the unmute buttons, so it could be a safari issue

**Comment by jallamsetty1** [comment]
All these issues have been fixed on https://meet.jit.si. Please feel free to reopen this issue if you still see it.

**Comment by pangrr** [comment]
How to test for issue 1 on https://meet.jit.si if we can't use it on mobile browser?
I tested locally with v5390 and still see issue 1.

**Comment by saghul** [comment]
You can use it on the mobile browser just fine, just press the "Launch in web" button.
