### ISSUE TITLE
Mobile: Choose server on joining meeting menu

### ISSUE THREAD

**Issue by trymeouteh** [jitsi/jitsi-meet#6952]
Instead of having the choose server URL buried in the settings on android and ios, I think it will be better there was a input underneath the Jitsi Meet room name. This way all you need to do to join a room on a different server than meet.jit.si is to enter the meeting name and then enter the server URL.

**Comment by trymeouteh** [comment]
This is how I pictured it.

```
**Meeting Name:**
myMeeting

**Server:**
https://meet.jit.si/

Go
```

So you can enter in the name of the meeting and the Server field will by default be https://meet.jit.si/ but can be changed. And after setting those two fields you hit "Go" to join or create the meeting.

**Comment by luixxiul** [comment]
Thanks, I see. Yet I'm a little bit worried that it would be confusing to have the different domain from the host's domain on the welcome page. Also if you would mistype the server domain, you could not start a meeting at all (like `https://meet.jis.ti/`). I'm not sure if this would improve UX.

IMO the request seems to me niche and this kind of UI would be better implemented separately from Jitsi Meet; set up another website with those two input forms. What would you think?

**Comment by trymeouteh** [comment]
I wanted to suggest this for the mobile apps. A suggestion would be to validate the URL is a Jitsi meet server before making the Go button clickable.

**Comment by saghul** [comment]
You can already enter a full URL in the room field and it will connect to that server.
