### ISSUE TITLE
External_api.js command parameter 'startRecording' not supported

### ISSUE THREAD

**Issue by jefaokpta** [jitsi/jitsi-meet#6954]
### Description:

The command 'password' works fine but 'startRecording' isn't recognised 

<img width="1146" alt="Screen Shot 2020-06-03 at 14 15 50" src="https://user-images.githubusercontent.com/10830832/83673814-290f9100-a5ae-11ea-860c-1ffd0e4f29dd.png">

### Steps to reproduce:

1. Running page on a simple file
2. I'm trying to record the meet on dropbox using token

### Client information:

- Browser / app version:
Chrome 83
- Operating System:
MAC

### Additional information:

I'm using CDN
<script src='https://meet.jit.si/external_api.js'></script>

**Comment by saghul** [comment]
It hasn’t been deployed to meet.jit.si yet.

**Comment by jefaokpta** [comment]
Ok, thanks Saúl.

On 3 Jun 2020, at 17:08, Saúl Ibarra Corretgé <notifications@github.com<mailto:notifications@github.com>> wrote:



It hasn’t been deployed to meet.jit.si<http://meet.jit.si> yet.

**Comment by jlrpuma** [comment]
@saghul do you have any idea of when this will be released to meet.jit.si?

**Comment by saghul** [comment]
Probably today :-)

**Comment by jlrpuma** [comment]
@jefaokpta i was testing this new '_startRecording_' option but seems like doesn't work at least on my environment, did you achieve something with this command ?

**Comment by uwaiszaki** [comment]
@saghul Is it working now?
I am trying to start recording by execute command but no event is firing after that.
is there any other way to do this.
Thanks

**Comment by jlrpuma** [comment]
@uwaiszaki Its really weird because once i execute the startRecording command nothing happens, i don't know if i need to update my Docker Jitsi environment too @saghul ? in order to make this function works.

**Comment by Punit-Vajpeyi** [comment]
@saghul Its still not working for me. nothing happens after this.

Here is my code snippet
`api.addEventListener('videoConferenceJoined', (e) => {
      api.executeCommand('startRecording', {
        mode: 'file'
      });
    });`

**Comment by VitaliyDemchuk** [comment]
> @uwaiszaki Это действительно странно, потому что после того, как я выполняю команду startRecording, ничего не происходит, я не знаю, нужно ли мне также обновлять среду Docker Jitsi @saghul ? чтобы эта функция работала.

did you solve this problem?
