### ISSUE TITLE
Changes in external API does not appear immediately on https://localhost:8080/external_api.js

### ISSUE THREAD

**Issue by herpiko** [jitsi/jitsi-meet#6964]
### Description:

Changes in external API does not appear on `https://localhost:8080/external_api.js`

### Steps to reproduce:

1. Edit the `modules/API/external_api/external_api.js`,
```
diff --git a/modules/API/external/external_api.js b/modules/API/external/external_api.js
index 347756964..2c7d0d260 100644
--- a/modules/API/external/external_api.js
+++ b/modules/API/external/external_api.js
@@ -36,7 +36,7 @@ const commands = {
     password: 'password',
     sendEndpointTextMessage: 'send-endpoint-text-message',
     sendTones: 'send-tones',
-    setVideoQuality: 'set-video-quality',
+    setVideoQualityX: 'set-video-quality',
     subject: 'subject',
     submitFeedback: 'submit-feedback',
     toggleAudio: 'toggle-audio',
```
2. Run development server, `make dev`
3. Check if the development server serves the modified `external_api.js`, turn out it does not,
```
➜  jitsi-meet-original git:(750b7171d) ✗ curl -k https://localhost:8080/external_api.js | grep setVideoQualityX
```

However, if I run make all, the change appears on libs directory, `cd libs && grep -r -l setVideoQualityX`, output:
```
./external_api.min.map
./external_api.min.js
```

### Expected behavior:
The `setVideoQualityX` string appears on the output after this command,
```
➜  jitsi-meet-original git:(750b7171d) ✗ curl -k https://localhost:8080/external_api.js | grep setVideoQualityX
```

### Actual behavior:

The changes does not appear on  `https://localhost:8080/external_api.js`.

### Additional information:

Is there any way to get immediate changes of external_api.js in development environment?

**Comment by phanikiranwtc** [comment]
any update on this ?

**Comment by damencho** [comment]
Nope, currently there is no way to do that

**Comment by TKone7** [comment]
Hey
I am having the exact same issue. Can anyone explain why this file is not built and delivered when run with `make dev` and if this is the expected behavior. And if so how can I test the developments in this file without running the full deployment?

**Comment by saghul** [comment]
It is, you can access it at https://localhost:8080/libs/external_api.js

**Comment by vpzomtrrfrt** [comment]
That doesn't really help when using the React SDK since it expects external_api.js to be at the root

But adding this to the webpack config seems to work:
```patch
diff --git a/webpack.config.js b/webpack.config.js
index 07b9715c0..0a2b7e723 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -82,6 +82,10 @@ function devServerProxyBypass({ path }) {

         return path;
     }
+
+    if (path === '/external_api.js') {
+        return '/libs/external_api.js';
+    }
 }

 /**
```
