### ISSUE TITLE
[RN] ReferenceError:Property 'HTMLButtonElement' doesn't exist ,js engine: hermes

### ISSUE THREAD

**Issue by sheywesk** [jitsi/jitsi-meet#6969]
I can't use Button. I get the following error: 
`ReferenceError:Property 'HTMLButtonElement' doesn't exist ,js engine: hermes`
this happens with the onPress event inside the Formik.
any solution ?

**Comment by saghul** [comment]
How does your modified code look like? I assume you’ve made changes because we are not getting it ourselves.

**Comment by sheywesk** [comment]
`export default function SignIn({ navigation }) {
    useEffect(() => {
        Splash.hide();
    });

    return (

        <Formik
            initialValues = {{
                email: '',
                password: ''
            }}
            onSubmit = { value => {} }
            validationSchema = { schemaFormik } >
            {formikProps => (
                <Container>
                    <Title>Login</Title>

                    <SubWrapper>
                        <TextInput
                            placeholder = 'email'
                            onChangeText = { formikProps.handleChange('email') } />
                        <TextError>{ formikProps.errors.email}</TextError>
                        <TextInput
                            placeholder = 'senha'
                            onChangeText = { formikProps.handleChange('password') } />
                        <TextError>{formikProps.errors.password}</TextError>
                    </SubWrapper>
                    <Button
                        size = '300px'
                        name = 'Entrar'
                        onPress = { formikProps.handleSubmit } />
                </Container>
            )}
        </Formik>
    );
}`

other functions work, is it the formik?

**Comment by saghul** [comment]
I don’t know, never used it, the problem seems to be in that Button component, yes

**Comment by sheywesk** [comment]
Resolve. Replace formikProps.handleSubmit with formikProps.submitForm.
