### ISSUE TITLE
Failed to access my microphone

### ISSUE THREAD

**Issue by CarmilleNa** [jitsi/jitsi-meet#6970]
Hi y'all,

I wanted to use Jitsi with my friends to chat, and everything seemed fine, they could join, my camera is working but I can't use the microphone. I keep getting this error message, and can't understand what the problem is. Any idea what is happening?
![jitsi](https://user-images.githubusercontent.com/66492179/83914626-1c7f6a00-a761-11ea-8ec4-9d4a86ae9572.PNG)

**Comment by saghul** [comment]
Please fill in the issue template.
