### ISSUE TITLE
Debian packages not friendly with nginx-light

### ISSUE THREAD

**Issue by sanvila** [jitsi/jitsi-meet#6971]
### Description:

On a Debian system where the `nginx-light` package is already installed, installing `jitsi-meet` does not create any site configuration at `/etc/nginx/sites-enabled` or `/etc/nginx/sites-available`.

### Steps to reproduce:

1. Take a freshly installed Debian 10 system with only the base system
2. Add APT line for the stable packages of jitsi
3. `apt-get install nginx-light`
4. `apt-get install jitsi-meet`

Note: Steps 3 and 4 may be combined into a single `apt-get` call.

### Expected behavior:

I expected `/etc/nginx/sites-available` to contain an automatically created configuration for jitsi-meet (as it happens when I do `apt-get install jitsi-meet` without having `nginx-light` installed beforehand).

### Actual behavior:

No automatic configuration happens.

### Server information:

Debian 10.4 (buster)
jitsi-meet version 2.0.4627-1

### Additional information:

The bug seems to be in the postinst for the jitsi-meet-web-config package,
which reads like this:

```
NGINX_INSTALL_CHECK="$(dpkg-query -f '${Status}' -W 'nginx' ...
NGINX_FULL_INSTALL_CHECK="$(dpkg-query -f '${Status}' -W 'nginx-full'...
NGINX_EXTRAS_INSTALL_CHECK="$(dpkg-query -f '${Status}' -W 'nginx-extras'...
```
Apparently it would suffice to check for `nginx-light` as well and act accordingly.

As a workaround, I could do this:

`apt-get install nginx nginx-light jitsi-meet
`

but installing `nginx`, which is just an empty dependency package without any real functionality by itself, should not be required.

Thanks.

**Comment by saghul** [comment]
Does nginx-light include SSI support? If so, please create a PR with your changes.

**Comment by sanvila** [comment]
> Does nginx-light include SSI support?

Yes, it does. `dpkg -s nginx-light`  shows this:

 ```
OPTIONAL HTTP MODULES: Auth Request, Charset, Gzip, Gzip Precompression,
 Headers, HTTP/2, Index, Log, Real IP, Slice, SSI, SSL, Stub Status, Thread
 Pool, WebDAV, Upstream.
```
> If so, please create a PR with your changes.

Hmm, but that would involve signing a document (which I don't really want to). Can I put the patch in the public domain instead?

**Comment by sanvila** [comment]
Why is this marked as wontfix?
