### ISSUE TITLE
Video and Audio disabled for iOS platform

### ISSUE THREAD

**Issue by ccs1428** [jitsi/jitsi-meet#6977]
### Description:

Customised the jitsi meet application and configured the same in web and mobile. Its working fine both in web and android. But while joining a meeting in iOS vedio and audio seems to be disabled. When checked in safari browser, same issue is there also.

### Steps to reproduce:

1. Start a meeting in web and join ,  user will be able to see all users.
2. When user joined from the android app,  able to see all joined users excluding iOS user
3. When user joined from iOS app, able to see only own video all other videos are disabled

### Server information:

- Jitsi Meet version: 4178 
- Operating System: Ubuntu

### Client information:

- Browser / app version:20.3.0
- Operating System: MAC

### Additional information:

When a user joined meeting from iOS application audio and video muted for all other users.

**Comment by ccs1428** [comment]
Already synced the latest source from https://github.com/jitsi/jitsi-meet/ 
and customise UI the source based on requirement.

When a user create a meeting from web application and joined from iOS app. Video and audios are not sharing in both platforms. They are able to see own video and others only, not iOS users.

Sharing the screen shots, please help.


<img width="1426" alt="meeting" src="https://user-images.githubusercontent.com/585841/84253202-4653da80-ab2d-11ea-9708-a2b92ec90135.png">
![IMG_0389](https://user-images.githubusercontent.com/585841/84253366-78fdd300-ab2d-11ea-8667-7f1f96da1608.PNG)
![IMG_0390](https://user-images.githubusercontent.com/585841/84253381-7c915a00-ab2d-11ea-861e-51c649faeb9a.PNG)


Last 2 weeks i am in this issue, please guide me.

**Comment by ccs1428** [comment]
@Echolon Please help me.

**Comment by ithaqua** [comment]
same issue too, but still cannot find the solution. please help to guide a way to fix, many thanks.

**Comment by ccs1428** [comment]
@ithaqua 
No solution yet.
Better we will use SDK  and customise as per requirement and it's working fine.

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk

**Comment by ithaqua** [comment]
How do you do customize using SDK?
We develop customize app using react native..

**Comment by ccs1428** [comment]
We have to do platform (iOS / Android) based customisation. Not in react native.

**Comment by alantulais** [comment]
@ccs1428 Could you solve this problem?

We are experimenting the exact same issue. We pulled the repository on a stable branch on January and everything was working ok. Then we pulled last changes from master branch 2 weeks ago and do a npm install. Everything was working fine.

Then we removed "node_modules" directory and pod install again, but now web & android apps works fine, while ios users can't turn on their camera or mic and can't see other user's video or audio

**Comment by ccs1428** [comment]
> @ccs1428 Could you solve this problem?
> 
> We are experimenting the exact same issue. We pulled the repository on a stable branch on January and everything was working ok. Then we pulled last changes from master branch 2 weeks ago and do a npm install. Everything was working fine.
> 
> Then we removed "node_modules" directory and pod install again, but now web & android apps works fine, while ios users can't turn on their camera or mic and can't see other user's video or audio

No solution yet.
Better we will use JITSI SDK and customise as per requirement and it's working fine.

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk

**Comment by mindjaydeep** [comment]
I am getting the same issue. video/audio of another user always shows as mute in iPhone 7, iPhone SE (2nd generation), iPhone XR. I tried with default gitsi URL "https://jitsi.mindinventory.net/" as well getting same issue.

**Comment by ccs1428** [comment]
@mindjaydeep  This is an open issue in source code based solution. Better you can go with Jitsi SDK based solution for the same. Please check below link.

[https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk](url)

**Comment by anwar907** [comment]
> @mindjaydeep This is an open issue in source code based solution. Better you can go with Jitsi SDK based solution for the same. Please check below link.
> 
> [https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk](url)

hey I getting same issues but I get on android and iOS, can I see your setup for android first? and if this issues you have solved I can see your setup for iOS also. thank you
