### ISSUE TITLE
Can't get jitsi-meet gpg key

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [jitsi/jitsi-meet#6978]
Hello. I want to install JItsi Meet but I have a problem with gpg key. Please help :(.
Here is my output
```Bash
curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   207    0   207    0     0      6      0 --:--:--  0:00:31 --:--:--    56
gpg: no valid OpenPGP data found.

```

**Comment by Vanshbordia** [comment]
Their main download site and it's mirrors are down as of now. Hope they fix it soon. A lot of new users are stuck

**Comment by MichaelGrigoryan25** [comment]
Thanks for the reply dear @Vanshbordia , I was going to start to panic that something went wrong with my system :)

**Comment by MichaelGrigoryan25** [comment]
And also, can you please update me when it starts running again?

**Comment by IzxxY** [comment]
Same thing here, can't get the key.

Please update me aswell when it runs again

**Comment by MichaelGrigoryan25** [comment]
@IzxxY @Vanshbordia @WonderCRM It's up now, i think
