### ISSUE TITLE
Resume Button for Shared Document Etherpad

### ISSUE THREAD

**Issue by brightson93** [jitsi/jitsi-meet#6979]
**Is your feature request related to a problem you are facing?**
Yes, most of our users complains that the current build button for shared document etherpad navigation is lacking the resume button, everytime the user opens an etherpad, after hiding the etherpad, users are unable to resume to open the etherpad, and are left only with the choice to close the etherpad first then only able to reopen the etherpad.

**Describe the solution you'd like**
adding an additional button for mobile apps(Android/IOS) build for resuming the Shared Docuement etherpad without having the hassle to close etherpad first.  

**Describe alternatives you've considered**
Another alternative for this solution is that the Hide Sliding View button on the etherpad for mobile app is will close the app as well, and the abstract button for shared document button will have function to only Open the Shared Document Button.

**Comment by Echolon** [comment]
related topics:

 Etherpad usernames contain + for spaces ui/ux
#6624
startAudioMuted limits the numer of concurrent etherpad users config quality
#6330

**Comment by AliKarpuzoglu** [comment]
couldn't this be fixed by completely removing the "closed shared document" option in the settings?
