### ISSUE TITLE
Zoom Level of Video on Android Application Doesn't Match Desktop

### ISSUE THREAD

**Issue by eceforge** [jitsi/jitsi-meet#6982]
### Description:

A person joining a video meeting from the Android application will see zoomed and cropped version of the presenter's video. The presenter is unaware that they are cut-off or even completely not in the field of view of the user on the app. 

### Steps to reproduce:

1. Start a meeting between a web-app user (Person A) that has webcam(laptop/desktop) and someone that using the android application (Person B)
2. Person A can see the entire camera field of view from Person B, but....
3. Person B only sees a very small portion of field of view available to person A's camera. 
4. This is made worse when in portrait mode since the android wants to fill the portrait screen with the video from the speaker which is a landscape video .
5. It is quite easy for Person A to see in their preview of their own camera feed that they are easily in the view, meanwhile Person B sees the blank wall to one side or the other of person A. 

### Expected behavior:

Rather than trying to fill the android-app screen with the video of person A (and therefore needing to zoom and crop) just fill horizontal or vertical size of screen and have black-bars everywhere else. 

Alternatively, provide person A on some indication of what is in-frame according to the android application ( I realize this likely quite difficult to do, and not actually a great solution). 

### Actual behavior:

Person A is so heavily zoomed and cropped in Android views (either portrait, or landscape, or tile) that it is possible that person A may not be in frame at all as seen by android users. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: 20.2.3 build 4129209
- Operating System: Android

**Comment by saghul** [comment]
This is expected behavior, web behaves the same, it silla up the viewport with video.

AFAICT this is the industry standard, all video chat apps fill the viewport which means some cropping has to happen.

**Comment by eceforge** [comment]
Filling the viewport makes sense when both parties are on the same platform with approximately the same size viewport, but not on where you might regularly expect parties to be on mixed platforms with massively different viewports. Someone sitting at desk with a 4k monitor and someone with a 5" phone in their hand can't both expect to fill the view-port and have  intelligible amounts of cropping. 

Industry standard or not, do you not agree it makes little sense in this scenario?

**Comment by thomp** [comment]
One might at least make it a configurable option (fill/no-fill) in the web UI.

**Comment by HeuFui** [comment]
I've noticed this for quite some time and it's really confusing. When seeing the call picture in picture, everything is ok, but with the app open, the zoomed version crops so much of the view that sometimes the other party is barely visible (I just can see part of the face, and can't make what they're trying to convey with their facial expressions).
