### ISSUE TITLE
Intermittent Chat Notifications 

### ISSUE THREAD

**Issue by brightson93** [jitsi/jitsi-meet#6983]
### Description:

the Chat notification toggle for unread chat message only work intermittently, but there is a pattern, the chat unread toggle only work again only after the 2nd, 4th chat exchange respectively. the 1st chat will toggle the unread chat, but 2nd chat exchange will not, but the 3rd chat exchange will show the unread chat.  

### Steps to reproduce:

1. Open any Chat from Web App or Mobile App (eg. User A and User B)
2. User A Initiate Chat from either Apps  (Unread Chat will Still Toggle)
3. User B Reply the Chat from the recipient side to User A (Unread Chat will not Toggle)
4. User A Replying the Chat to User B (Unread Chat will not Toggle)
5. User B Replying the Chat to User A (Unread Chat will Toggle)
6. User A Replying the Chat to User B (Unread Chat will not toggle)
7. User B Replying the Chat to User A (Unread Chat will not Toggle)
8.  User A Replying the Chat to User A (Unread Chat will toggle)  

### Expected behavior:
All Unread Chat should be toggle unread for better notification to user

### Actual behavior:

1. Open any Chat from Web App or Mobile App (eg. User A and User B)
2. User A Initiate Chat from either Apps  (Unread Chat will Still Toggle)
3. User B Reply the Chat from the recipient side to User A (Unread Chat will not Toggle)
4. User A Replying the Chat to User B (Unread Chat will not Toggle)
5. User B Replying the Chat to User A (Unread Chat will Toggle)
6. User A Replying the Chat to User B (Unread Chat will not toggle)
7. User B Replying the Chat to User A (Unread Chat will not Toggle)
8.  User A Replying the Chat to User A (Unread Chat will toggle)  

### Server information:

- Jitsi Meet version: 2.0.4468
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: 20.3.0. build 1
- Operating System: Android 10 /IOS 13.5

**Comment by SplendornetTech** [comment]
Any updates on this? Actually I am not receiving any message on mobile application, using react-native SDK
