### ISSUE TITLE
Allow selecting of Camera Resolution

### ISSUE THREAD

**Issue by fionera** [jitsi/jitsi-meet#6988]
### Description:
For one of my Webcams I have to override the resolution over which it gets initialized, else it will only send garbage data. Please allow to add a custom resolution. I tried to override the stream over the JS Console but failed

### Steps to reproduce:
1. Use a Infrared Camera that reports a wrong Resolution
2. Get Garbage Data

### Expected behavior:
1. Allow to set a custom resolution to get a proper image

### Actual behavior:
https://imgur.com/a/Dx3hR2L

### Server information:

- Jitsi Meet version: 
- Operating System:

### Client information:

- Browser / app version: Chrome / Unknown
- Operating System: Linux

**Comment by Echolon** [comment]
related:

**configurable default (start-up) lower video resolution** #5256

**Comment by fionera** [comment]
Thanks stalebot for being useless xD
