### ISSUE TITLE
Cannot disable screen sharing in Audio only mode (Firefox)

### ISSUE THREAD

**Issue by abdultz** [jitsi/jitsi-meet#6991]
Steps to reproduce (using Firefox browser):

1. Manage Video Quality (Select anything apart from Audio only).
2. Start Screen Sharing. Do not select the screen in the Firefox browser notification.
3. Manage Video Quality (Select Audio only).
4. Select the window to share in the Firefox browser notification.

The Screen sharing starts. Clicking the Screen sharing Icon (to stop screen sharing) does not stop screen sharing (Generates an exception in browser console log). The screen sharing thus works in Audio only mode.
This is not possible with Chrome browser as Chrome's notification for screen sharing does not allow interaction with webpage once the notification is open.
![jitsi-screen-sharing](https://user-images.githubusercontent.com/12512518/84141976-a5ecb000-aa71-11ea-9ff6-abe919f64828.png)
![jitsi-screen-sharing2](https://user-images.githubusercontent.com/12512518/84141986-ab49fa80-aa71-11ea-8994-e7f96f683b93.png)

**Comment by saghul** [comment]
I'd say this is a browser issue. Firefox shouldn't allow interaction with the page until choosing the window is done / cancelled. There is not much we can do on our side since we are not in control of the UI for selecting the screen sharing source.
