### ISSUE TITLE
Add ability to share vimeo/vimeo livestream videos

### ISSUE THREAD

**Issue by happychameleon** [jitsi/jitsi-meet#6992]
**Is your feature request related to a problem you are facing?**
I would like to share live streams of nyc city council meetings

**Describe the solution you'd like**
make the same feature that is available for youtube videos available for vimeo videos

**Describe alternatives you've considered**
so far i have not found one that is satisfactory

**Comment by htcheng** [comment]
@happychameleon - this isn't currently possible unless you are hosting your own jitsi-meet servers and jibri servers. If you are, the change isn't very hard and there are two options to do it - one doesn't require modifying any source code but putting an NGINX live streaming proxy in front of the Jibri server. The second way is to recompile Jibri to accept any live streaming RTMP input in the Live Streaming input window and direct the RTMP stream that way.

Method #1 is outlined here: https://community.jitsi.org/t/stream-to-any-or-multiple-rtmp-destinations-record-simultaneously/51943

Mthod #2 is just modifying a few lines of the Jibri source code, recompiling it using Mavena and then replacing the standard jibri.jar file in /opt/jitsi/jibri with the newly compiled version.

I'd say method #1 is certainly easier than method #2 but adds a little latency to the equation, but perfectly acceptable.

**Comment by nimaam** [comment]
I can add breakout to your jitsi meet instance with local recording and etherpad to full funtionality, and you can have control to all of them in your API, I can handle a webinar mode that guest can not sea each other too, I made a change to jitsi alot and now is ready to others but not for free and not expensive.

Break out
Local Record no jibri needed
Local Snapshopt
Etherpad
HIde guests from guests and moderator sea all
stream to youtube/instagram/facebook and all rtpm server.

**Comment by heikar** [comment]
I think, the possibility to share videos from vimeo would be a great functionality.
Maybe it is possible to implement a generic approach, to register multiple video Services in a config file?

**Comment by nimaam** [comment]
I have these modification and no need to do any thing in configuration in my modification for stream to youtube, vimeo, and instagram even facebook, just enter the stream key and select the service you want to stream to it.
So I made some more useful thing like local storage and if you want can talk to me on email, nima.alizadeh.m@gmail.com

**Comment by hex-m** [comment]
related/duplicate: https://github.com/jitsi/jitsi-meet/issues/2829

**Comment by heikar** [comment]
Hi @hex-m ,
the referenced issue is about "stream TO". In this issue the requested function is "stream FROM".
