### ISSUE TITLE
Warning symbol: Hovering with cursor does not show information

### ISSUE THREAD

**Issue by Echolon** [jitsi/jitsi-meet#6995]
### Description:

This is about the red warning symbol which tells the user in case they use a insecure link name.
After the warning is shown to the user, only the red symbol is left. Hovering over this symbol does **not trigger any extra information** or pop-up **in the tile view only**. This should be corrected or implemented.

### Steps to reproduce:

1. Switch to tile view
2. Hover over the warning symbol in the top right

### Expected behavior:

Hovering over the warning symbol shows information (as it normally does).

### Actual behavior:

Hovering over this symbol does not trigger any extra information or pop-up in the tile view only.

![Jitsi](https://user-images.githubusercontent.com/29168011/84189708-f8d85e80-aa95-11ea-8004-8c0c6b18a589.png)

### Server information:

- Jitsi Meet version: https://meet.blabber.im/
- Operating System: ?

### Client information:

- Browser / app version: Firefox 77.0.1 (64-bit)
- Operating System: 
Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8

**Comment by l3d00m** [comment]
I can reproduce this. As you said, it's in the tile view only.

**Comment by saghul** [comment]
The icon does show a tooltip now.
