### ISSUE TITLE
Hide 'Insecure room name' warning on password protected meetings

### ISSUE THREAD

**Issue by fleaz** [jitsi/jitsi-meet#6998]
**Is your feature request related to a problem you are facing?**
When using an insecure room name (e.g. in our case 'HomeOffice') in the new Jitsi version this small red warning icon pops up and tells you that anybody can join because the room name is guessable. But our meeting room is password protected, so the text of the message, stating that everybody can join if they guess the name can join, is wrong.

**Describe the solution you'd like**
My idea would be to hide this message if the meeting has a password configured.

**Describe alternatives you've considered**
Ignoring the warning and telling all participants that is's a bug :D

Best regards,
Felix

**Comment by saghul** [comment]
Please follow https://github.com/jitsi/jitsi-meet/pull/7012
