### ISSUE TITLE
scalable docs: add note about whitespace in debconf-set-selectios data 

### ISSUE THREAD

**Issue by hermanbanken** [jitsi/jitsi-meet#7000]
Maybe add to the scalable installation documentation that the debconf-set-selectios data is space/tab sensitive and you should only use a single whitespace character!
https://www.debian.org/releases/buster/amd64/apbs03.en.html

Previous report / debugging session:

**Errors during "setting up jitsi-meet-prosody (1.0.4127-1)": /etc/prosody/conf.avail/: binary operator expected**
<details>
I searched the issues for "jitsi-meet-prosody postinst binary operator" and found nothing... so here I go.

### Description:
```
Setting up jitsi-meet-prosody (1.0.4127-1) ...
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 104: [: /etc/prosody/conf.avail/: binary operator expected
The given hostname does not exist in the config
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 138: [: /etc/prosody/conf.avail/: binary operator expected
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 145: [: /var/lib/prosody/: binary operator expected
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 180: [: /var/lib/prosody/auth.: binary operator expected
Setting up lua-event:amd64 (0.4.3-2) ...
```

further along:

```
Setting up jitsi-meet-web-config (1.0.4127-1) ...
req: Use -help for summary.
dpkg: error processing package jitsi-meet-web-config (--configure):
 subprocess installed post-installation script returned error exit status 1
```

The latter which provides no additional information to what the error is. Rerunning also does not solve it:

```
# dpkg --configure -a
Setting up jitsi-meet-web-config (1.0.4127-1) ...
req: Use -help for summary.
dpkg: error processing package jitsi-meet-web-config (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 jitsi-meet-web-config
```

**EDIT**: now I know the error is from [`openssl req`](https://github.com/jitsi/jitsi-meet/blob/cb0cea4ebd504e61faa423a6747e0c5192705ad0/debian/jitsi-meet-web-config.postinst#L71-L99)

### Steps to reproduce:
I was following https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-scalable (which mentions a lot of debconf presets).

I saw these errors in the installation logs and felt obliged to notify you:

```
Setting up jitsi-meet-prosody (1.0.4127-1) ...
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 104: [: /etc/prosody/conf.avail/: binary operator expected
The given hostname does not exist in the config
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 138: [: /etc/prosody/conf.avail/: binary operator expected
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 145: [: /var/lib/prosody/: binary operator expected
/var/lib/dpkg/info/jitsi-meet-prosody.postinst: line 180: [: /var/lib/prosody/auth.: binary operator expected
Setting up lua-event:amd64 (0.4.3-2) ...
```

### Expected behavior:
No errors

### Actual behavior:
Errors in the jitsi-meet-prosody.postinst file.

### Server information:
 I don't know how the debian package version 1.0.4127-1 maps to GitHub versions, so I can't diagnose the file itself.

- Jitsi Meet version: debian 1.0.4127-1
- Operating System: Debian 9 (GCP VM image)

### Additional information:
I noticed that 
```
jitsi-meet-prosody  jitsi-videobridge/jvbsecret password some-password
```
still misses from the guide. 
Without it you get a UI popup. Inconvenient in a VM-provisioning-script!

I'm creating a scalable Jitsi GCP Terraform setup here:
https://github.com/hermanbanken/jitsi-terraform-scalable

EDIT:
It seems the postinst files do a lot of `if [ -z $SOMETHING ]` which fails if the $SOMETHING contains spaces:
https://stackoverflow.com/questions/24603037/binary-operator-expected-error-when-checking-if-a-file-with-full-pathname-exists

Same for https://github.com/jitsi/jitsi-meet/blob/cb0cea4ebd504e61faa423a6747e0c5192705ad0/debian/jitsi-meet-web-config.postinst#L102-L103 which fails and does not write a file.

My $JVB_HOSTNAME is `meet.jitsi-hosts.example.tld`. Maybe the `-` between jitsi and hosts is not supported!

</details>

**Comment by hermanbanken** [comment]
Still feels like a reasonable change...

**Comment by samip5** [comment]
I find myself with the same issue.

A lot of errors with the jitsi-meet-prosody.postinst file.
