### ISSUE TITLE
Smartphone App isn't working with my Jitsi Server 

### ISSUE THREAD

**Issue by tux1980** [jitsi/jitsi-meet#7001]
### Description:

Always when I'm connecting with an mobile device, with the app, it's been trying to reconnect all the time. I occurred that that behavior earlier as I was working with a self-signed certificate but in the meantime I'm using a public/commerical cert. 

Site:
https://meet-podium.apps.ocp4.kimmlingen.org/test01

### Steps to reproduce:

Open the web page above with your smartphone

### Expected behavior:

workink like it is the case with an ordinary browser like chrome or firefox

### Actual behavior:

The app on a smart phone doesn't work, as described already above

### Server information:

- Jitsi Meet version:
- Operating System: Openshift 4.4 (Container/Kubernetes environment)

**Comment by tux1980** [comment]
> Which app, version and which platform (Android / iOS) ?

I'm using the Jitsi App on Android. But it doesn't matter if this app is installed, always the same issue.

**Comment by tux1980** [comment]
> Your server is misconfigured: https://whatsmychaincert.com/?meet-podium.apps.ocp4.kimmlingen.org
That's really weird since I did actually install the the Cert Chain with CA including the intermediate cert and the Root CA. Hmmm.....

**Comment by Echolon** [comment]
@tux1980 Could you solve the certificate?
