### ISSUE TITLE
Please remove Dropbox recording from meet.jit.si and self-hosted defaults or clearly indicate it's not reliable - DATA LOSS

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jitsi-meet#7002]
Every few days there is a new post in the forum about someone looking for a lost meeting recording they expected to find in their Dropbox folder.

* The recording may not be lost, [just not sync'ed](https://github.com/jitsi/jibri/issues/294) if you server is running an install with an older version of `jitsi-upload-integrations` . Sometimes the recording may be available by going directly to the Dropbox web interface.
* The Dropbox account may run out of disk space which can't be anticipated or calculated easily by users. Some users have reported after deleting content and making space the recording has appeared a few days later, as if sync from meet.jit.si was retried and successful. 

No error message is shown and no warning indicates this could fail as there are so many factors on which successful recordings depend. Recording full video and audio for the meeting is not documented clearly for self-hosted installs either, which makes it difficult to recommend self-hosting as a viable option for situations when such recordings are essential.

**Ultimately this leads to DATA LOSS**, as most forum posts about this go unanswered, with only a few exceptions. [I've started adding the tag `dataloss` to such posts](https://community.jitsi.org/tag/dataloss).

It's very frustrating to start using Jitsi Meet, have a successful meeting despite the many problems that may surface, to end up looking for a recording that was never implemented in a reliable way because it depends on a third-party service that we  (users and sysadmins) can't control or don't understand fully. 

I'd like to request to completely remove this option from the public https://meet.jit.si instance and by default on self-hosted installs resulting from the [Quick install guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) until it's implemented with proper warnings and alternatives, specifically reliable local / self-hosted recording.

Thanks in advance for considering this.

**Comment by no-username42** [comment]
Thank you for this warning.
I already fail on initial setup and configuration.

**Comment by lucasa** [comment]
UP!
This is very important.

**Comment by MagicFab** [comment]
Still relevant ?

I haven't checked, can any of the core devs please comment on this ?

**Comment by saghul** [comment]
No longer relevant indeed. We have made many improvements to the reliability of Dropbox recordings.

**Comment by ty1279** [comment]
This happened to me as well. I recorded a 1-hour meeting, there was no warning it was going to fail, and I lost my important data. Now I cannot have that meeting again and had to compensate it with my own money for additional loss.

**Comment by saerdnaer** [comment]
We had the same issue yesterday:
After about 30 minutes everybody was dropped from the meeting and the recording stopped, everybody rejoined and we restarted the recording – but the recording of the first part is nowhere to be found...
