### ISSUE TITLE
Mobile Apps break with Lobby

### ISSUE THREAD

**Issue by awlx** [jitsi/jitsi-meet#7005]
### Description:

The mobile apps break when joining a lobby room.

### Steps to reproduce:

Join a room with lobby mode enabled.

### Expected behavior:

Wait in the lobby until it's confirmed to join

### Actual behavior:

App crashes and enters a reload loop.

![20-06-10 18-22-04 5437](https://user-images.githubusercontent.com/6527744/84293323-e880bc00-ab47-11ea-9270-50295c2e7fc7.png)

**Comment by RockOutLoud** [comment]
Has there been any updates on this issue?

**Comment by RockOutLoud** [comment]
> This is known. The app needs to have lobby support as well. The currently released apps don’t.
> 
> The plan is to roll this feature with the next update and turn it on after some time, so users have had the time to update.

Hi Saghul, Any updates regarding the mobile waiting room issue? It's been almost 3 weeks. Are there any updates on this issue?  Thanks so much!!

**Comment by ashirwad007786** [comment]
Hey @saghul. Does the support for mobile has been developed or it's just pending for a release?

If I compile the app from the latest source code(master), will that contain the lobby support for the mobile?

**Comment by saghul** [comment]
Mobile support is already in as of release 20.3.0.

**Comment by saghul** [comment]
Oh, forgot to close this @awlx. Please drop a line if you run into issues. We are waiting to enable it on meet.jit.si until we have a good number of users running the latest version.

**Comment by aninditasadhukhan** [comment]
Hi @saghul  Could you please help me to know what changes are required to support lobby feature in mobile app?

Thanks,
Anindita

**Comment by bjoerrrrn** [comment]
The iOS-App is supporting the Lobby at the moment on my iPad 6. Gen - iOS 14.3 - Jitsi Meet App 20.6.2 build 103

I see the option in the app to activate the lobby in a conference, when I join a new session on _meet.jit.si._

When I do the same on my own Jitsi Meet Instance I do not see the Start Lobby Mode Option in the App.

My Jitsi is based on the official Docker Images, freshly pulled today. 

In the normal Web App in any Browser the Lobby Feature works just fine and without a problem. Only the native Apps for iOS and Android do not offer me the option to toggle the Lobby Feature on.

Am I just blind or is there any switch that I have missed?

**Comment by saghul** [comment]
Can you please open a new issue? This should be working for all deployments.

**Comment by bjoerrrrn** [comment]
sure
