### ISSUE TITLE
Cannot call getUserMedia of undefined

### ISSUE THREAD

**Issue by jhiswin** [jitsi/jitsi-meet#7009]
### Description:

This error now pops up when trying to use Jitsi Meet and voice:

![image](https://user-images.githubusercontent.com/120998/84307007-47cfd380-ab2a-11ea-849c-c9c01f1234e1.png)

Logger.js:154 2020-06-10T18:51:30.139Z [features/base/tracks] Failed to create local tracks Array(1) TypeError: Cannot read property 'getUserMedia' of undefined
    at RTCUtils.js:994
    at new Promise (<anonymous>)
    at z._newGetUserMediaWithConstraints (RTCUtils.js:993)
    at z.<anonymous> (RTCUtils.js:1367)

### Steps to reproduce:

Open an iframe using JitsiMeetExternalAPI or iframe src directly.
Try to use microphone.
Microphone does not work.

### Expected behavior:

Microphone should work.  RTCUtils:994 should check for navigator.getUserMedia as a fallback if navigator.mediaDevices.getUserMedia doesn't exist.

### Actual behavior:

![image](https://user-images.githubusercontent.com/120998/84307007-47cfd380-ab2a-11ea-849c-c9c01f1234e1.png)

Logger.js:154 2020-06-10T18:51:30.139Z [features/base/tracks] Failed to create local tracks Array(1) TypeError: Cannot read property 'getUserMedia' of undefined
    at RTCUtils.js:994
    at new Promise (<anonymous>)
    at z._newGetUserMediaWithConstraints (RTCUtils.js:993)
    at z.<anonymous> (RTCUtils.js:1367)

### Server information:

- Jitsi Meet version: latest CDN JitsiMeet external api
- Operating System: Windows 10 latest updates

### Client information:

 Chrome Version 83.0.4103.97 (Official Build) (64-bit)
Windows 10 latest updates

**Comment by saghul** [comment]
Tentatively closing since it "solved itself". Holler if it reappears and we'll reopen.

**Comment by jhiswin** [comment]
Just wanted to update you guys on what happened.  

So we have other programs that also use the microphone first, and this allows silent blocking.
Chrome does a strange thing where if another requesting page or iframe is not visible when requesting access, it willl just block access to the microphone, and then persist the blocking.  It somehow happens that sometimes the iframe isn't visible or is 0 dimensions when it requests access, and then just gets blocked silently, and it requires manually enabling camera/microphone and completely restarting the browser to get it working again.  I've even had to clear cache in testing a few times.  I don't know yet if this is a bug in Chrome, or a security feature, a combination of the two, or something else like a conflict with the other microphone capture web app.

I'm currently looking at either hooking permissions events and double checking them and adding a banner to ask them to enable the microphone manually, and/or using a separate dedicated window for Jitsi instead of trying to embed it.

**Comment by Vacika** [comment]
Having the same problem here, i get this error only when accessing via iPhone chrome browser.

**Comment by YesThatGy** [comment]
I'm also having this problem. Not that it matters; this issue appears to be closed.
