### ISSUE TITLE
onConferenceTerminated is not invoked

### ISSUE THREAD

**Issue by erandakarachchi** [jitsi/jitsi-meet#7010]
### Description:

I have used Jitsi pre build sdk from maven. and implemented my class as follows.

`implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }`

```
public class JitsiCallActivity extends JitsiMeetActivity{

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_jitsi_call);
        roomId = getIntent().getStringExtra("room_id");

        initConference();
        launchMeeting(roomId);
    }

    @Override
    protected void initialize() {
        Log.d("JITSI","INITIALIZED");
        super.initialize();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        Log.d("DES","ON DESTROY");
    }

    @Override
    public void onConferenceTerminated(Map<String, Object> data) {
         Log.d("JITSI","MEET TERMINATED");
        super.onConferenceTerminated(data);
    }

    private void initConference(){
        URL serverURL;
        boolean isVideoCall = false;
        try {
            serverURL = new URL(KeyValues.JITSI_MEET_HOST);
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }

        JitsiMeetUserInfo userInfo = new JitsiMeetUserInfo();


        JitsiMeetConferenceOptions defaultOptions
                = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setWelcomePageEnabled(false)
                .setFeatureFlag("chat.enabled",false)
                .setFeatureFlag("call-integration.enabled", false)
                .setVideoMuted(false)
                .setUserInfo(userInfo)
                .setSubject("Sample room ")
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);

        Log.d("JITSI","CALL INIT");
    }
    private void launchMeeting(String roomName){
        JitsiMeetConferenceOptions options
                = new JitsiMeetConferenceOptions.Builder()
                .setRoom(roomName)
                .build();
        JitsiMeetActivity.launch(this, options);
        this.finish();
    }
}
```

But the `onConferenceTerminated` method doesn't seems to be calling.

### Expected behavior:

Invoke the `onConferenceTerminated` method after user left the conference.

### Actual behavior:

`onConferenceTerminated` is not invoked.

### Server information:

- Jitsi Meet version:
- Operating System:Ubuntu
-Building Platform : Mac OS Catalina Version 10.15.3 (19D76)

### Client information:

- Browser / app version:Android 10 on google pixel.
- Operating System:Android

### Additional information:

I've tested with the project in [jitsi-meet](https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/java/org/jitsi/meet/MainActivity.java). It seems to work fine.

I couldn't figure out what was missing here.

**Comment by saghul** [comment]
>         JitsiMeetActivity.launch(this, options);
>         this.finish();

Well, you are launching a new `JitsiMeetActivity` and finishing the current one. So it's behaving as expected.

You need to use the join method in your activity which extends from JitsiMeetActiovity if you want to customize the behavior instead of launching a new one.

**Comment by erandakarachchi** [comment]
@saghul Hi, 

I'm getting what you are saying here. but I'm unable to implement it.

`JitsiMeetActivity` doesn't seems to have `join()` method.

```JitsiMeetActivity.join(); //No such method.```

could you please provide a code example?

**Comment by saghul** [comment]
Look at the examples here: https://github.com/jitsi/jitsi-meet-sdk-samples I don't think you need to subclass the activity at all.

**Comment by erandakarachchi** [comment]
@saghul 
as follows,

```public class JitsiCallActivity extends AppCompatActivity```

But the example doesn't seems to implementing ```onConferenceTerminated()``` method.

any help?

**Comment by saghul** [comment]
It's not needed since the activity finishes on its own.

**Comment by erandakarachchi** [comment]
@saghul I need to notify the other users in the conference when a one user leaves. So my current plan is to invoke a method in the `onConferenceTerminated ` and notify other users through a push notification.

So it is important to me to override the `onConferenceTerminated ` method to make a request to my backend.

Thanks

**Comment by erandakarachchi** [comment]
@saghul after few hours of researching I found that following code works.
```
package com.telefon;

import androidx.appcompat.app.AppCompatActivity;
import timber.log.Timber;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.Toast;

import com.facebook.react.modules.core.PermissionListener;
import com.telefon.common.KeyValues;

import org.jitsi.meet.sdk.JitsiMeet;
import org.jitsi.meet.sdk.JitsiMeetActivity;
import org.jitsi.meet.sdk.JitsiMeetActivityDelegate;
import org.jitsi.meet.sdk.JitsiMeetActivityInterface;
import org.jitsi.meet.sdk.JitsiMeetConferenceOptions;
import org.jitsi.meet.sdk.JitsiMeetUserInfo;
import org.jitsi.meet.sdk.JitsiMeetView;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import android.os.Bundle;
import androidx.fragment.app.FragmentActivity;

import org.jitsi.meet.sdk.JitsiMeetView;
import org.jitsi.meet.sdk.JitsiMeetViewListener;

public class JitsiCallActivity extends FragmentActivity implements JitsiMeetActivityInterface, JitsiMeetViewListener {
    private JitsiMeetView view;

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        JitsiMeetActivityDelegate.onActivityResult(
                this, requestCode, resultCode, data);
    }

    @Override
    public void onBackPressed() {
        JitsiMeetActivityDelegate.onBackPressed();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        view = new JitsiMeetView(this);
        JitsiMeetConferenceOptions options = getOptions();
        view.join(options);

        setContentView(view);
        view.setListener(this);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        view.dispose();
        view = null;

        JitsiMeetActivityDelegate.onHostDestroy(this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

    @Override
    public void onRequestPermissionsResult(
            final int requestCode,
            final String[] permissions,
            final int[] grantResults) {
        JitsiMeetActivityDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onResume() {
        super.onResume();

        JitsiMeetActivityDelegate.onHostResume(this);
    }

    @Override
    protected void onStop() {
        super.onStop();

        JitsiMeetActivityDelegate.onHostPause(this);
    }

    @Override
    public void requestPermissions(String[] strings, int i, PermissionListener permissionListener) {

    }

    protected JitsiMeetConferenceOptions getOptions(){
        URL serverURL;
        try {
            serverURL = new URL(KeyValues.JITSI_MEET_HOST);
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetUserInfo userInfo = new JitsiMeetUserInfo();
        userInfo.setDisplayName("user");


        return  new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setWelcomePageEnabled(false)
                .setFeatureFlag("chat.enabled",false)
                .setVideoMuted(false)
                .setUserInfo(userInfo)
                .setSubject("SAMPLE ROOM")//Set call subject here. use to display phone number here.
                .setRoom("helloall")
                .build();

    }

    @Override
    public void onConferenceJoined(Map<String, Object> map) {

    }

    @Override
    public void onConferenceTerminated(Map<String, Object> map) {
        Log.d("SAMPLE","TERMINATED");
        finish();
    }

    @Override
    public void onConferenceWillJoin(Map<String, Object> map) {

    }
}
```

**Comment by sunilkumarjena21** [comment]
Hi @erandakarachchi @saghul ,

After implementing this custom activity 'onConferenceTerminated' & 'onConferenceJoined' working perfectly fine.
Issue:The camera & microphone is not working in this case unlike the '   JitsiMeetActivity.launch(context, options)' case.
Even its not asking for the dynamic permissions when tapping on the microphone & Camera icons.

Any guess on the issue?

Thanks in advance!

**Comment by erandakarachchi** [comment]
hi @sunilkumarjena21 

Not sure what the issue is. but [here](https://github.com/erandakarachchi/jitsi-android-demo) is a sample application that I've created and it's working fine.

**Comment by sunilkumarjena21** [comment]
HI @erandakarachchi ,
Thanks for your swift response.
I clone your code.And run it onSamsung Galaxy S9.
Not able to open/on Microphone & Camera when tapping on the microphone & Camera options on 'VideoChatActivity'.

Can you please try running your above project & let me know,if you can reproduce the same at your end?

Thanks in advance!

**Comment by erandakarachchi** [comment]
@sunilkumarjena21  
Yes. I was able to replicate it on MI Note 10 and Google Pixel. Didn't have much to dive into it. Tried by explicitly allowing camera and microphone permissions. But I was unable to access the camera or microphone.
What is your jitsi SDK version?

**Comment by sunilkumarjena21** [comment]
Hi @erandakarachchi ,

Thank God you're able to replicate it..
My Jitsi version:  'implementation ('org.jitsi.react:jitsi-meet-sdk:2.9.3') { transitive = true }'

Yes you're correct. Explicitly allowing camera and microphone permissions doesn't solve the issue.

Any other way to make it work?

Thanks in advance!

**Comment by baijianghai** [comment]
Hello,I have the same problems，My JitsiMeetSDK version is 3.2.0
Now   JitsiMeetView is not response for setListener method,
How did you solve this problem？

![image](https://user-images.githubusercontent.com/6112837/110409323-0886e100-80c2-11eb-8465-da6fa97b67e9.png)
