### ISSUE TITLE
JitsiMeetView in Relative Layout

### ISSUE THREAD

**Issue by asad175** [jitsi/jitsi-meet#7013]
Hi, I have added Jitsi meetview programatically into my layout in this way, But my picture Jitsi meetview is fluctuating and camera is not able to focus properly it keeps on fluctuatiing. Can anyone help.

My Code
jitsiView = new JitsiMeetView(MainActivity.this);
relativeLayoutJitsi.addView(jitsiView);

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
