### ISSUE TITLE
Will not run on mobile browser (Chrome/Android)

### ISSUE THREAD

**Issue by JakeQZ** [jitsi/jitsi-meet#7014]
### Description:

WebRTC is supported on mobile browsers such as Firefox and Chrome, however Jitsi insists the user downloads and installs an Android app, wasting time (and bandwidth) to access a meeting.  Same is probably true for iOS etc.

### Steps to reproduce:

1. Open https://meet.jit.si/github-issue-7014 with a recent version of Firefox or Chrome on an Android device.

### Expected behavior:

Room should open as on a desktop browser with a small window size.  An option to download an Android app may be provided, but this should be optional and easily dismissable.

### Actual behavior:

Page says "You need the Jitsi Meet mobile app to join this meeting on your phone."  No option is provided to use the browser instead, even if it supports WebRTC.

### Server information:

- Jitsi Meet version: whatever is at https://meet.jit.si/ at time of posting

### Client information:

- Browser / app version: Firefox 68.4.1 / Chrome 74.0.3729.157
- Operating System: Android 9

### Additional information:

Sorry if this has already been reported, but I could not find it.

**Comment by ktechmidas** [comment]
This is the default settings as it really doesn't work fantastically on mobile without the app... you can change this on your own Jitsi server but I guess the official meet.jit.si will keep it as is, in order to change this on your own server you just need to disable deep linking in the config.

**Comment by JakeQZ** [comment]
> it really doesn't work fantastically on mobile without the app...

Any particular reason?  Modern mobile browsers support WebRTC.  Many mobile apps are a just a glorified layer implementing JavaScript and HTML upon another layer which confines them to their specific app and runs on top of another framework for such (which is all a browser does).  So I would have thought native browser support would actually work at least as well as a supposedly device-OS-specific app.  Unless the Jitsi mobile apps are implemented semi-natively in Objective-C (iOS) or Java (Android)?  Are they?

Regardless, I don't think this should matter much, as long the relevant 'hardware accelaration' can be accessed just as well.

So I think users should be given the option.

**Comment by JakeQZ** [comment]
Looks like this has just been resolved.  There is now an option "Launch in web" :)

**Comment by JakeQZ** [comment]
@l3d00m Any chance of a cross-reference to the relevant commit?

**Comment by l3d00m** [comment]
I'm not a Jitsi developer or affiliated with the org, I just have rights to close issues. But nevertheless I think it was this commit 5348fa19c8cba9895217e1336a4915edd5661c3a that at least introduced the browser functionality.

**Comment by JakeQZ** [comment]
> I think it was this commit

Looks about right.  Thanks.

I've had to change my UA to be able to use Skype within a browser, which is crazy because Microsoft were always [banging on](http://cercomonadidae3.rssing.com/chan-3196389/all_p395.html) about using [feature detection](https://stackoverflow.com/a/24376480/2511031) instead of browser sniffing once they [lost](http://blogs.msdn.com/b/ieinternals/archive/2013/09/21/internet-explorer-11-user-agent-string-ua-string-sniffing-compatibility-with-gecko-webkit.aspx) the browser market.

Chrome on Linux seems to work reasonably well as a UA string for Firefox on Windows.  Though I'd rather just be able to use an empty string.  (The world was already mad.)
