### ISSUE TITLE
Cannot update jitsi

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7016]
### Actual behavior:

After `apt update` i get this error:
`An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.jitsi.org stable/ InRelease: The following signatures couldn't be verified because the public key is not available:`

### Server information:

- Jitsi Meet version: 2.0.4627-1
- Operating System: Ubuntu 18.04 LTS

**Comment by MagicFab** [comment]
Please make sure you follow these steps (from [the Quick start guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)) : 

**Add the Jitsi package repository**

This will add the jitsi repository to your package sources to make the Jitsi Meet packages available.

```
curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'
echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null


# update all package sources
sudo apt update
```

**Comment by heikar** [comment]
Hi Fabian,

thank you for your answer :)

If i download the key, then an error message appears:

`curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'`

Error message: `gpg: no valid OpenPGP data found.`

Many greetings
heikar

**Comment by damencho** [comment]
@heikar That should be fixed now. Thanks for the report.

**Comment by heikar** [comment]
Hi,

i have seen, that there is a new stable release.
But if i try to make a new clean install then the error `gpg: no valid OpenPGP data found.` appears again like in my last post.

Please can you check it?

**Comment by l3d00m** [comment]
This does not happen for me, are you sure you followed all of [these steps](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) and especially did an `sudo apt update` before?

**Comment by heikar** [comment]
@l3d00m Thank you. I was too fast. It works perfect :)
