### ISSUE TITLE
videomuted is false by default in LUA script

### ISSUE THREAD

**Issue by alternadom** [jitsi/jitsi-meet#7017]
# Description:

Trying to get the status of video and audio in a room from a script named mod_muc_size.lua
I'm parsing '_occupants' on a room object. All data are correct, except the 'videomuted' which is at 'false' at first, then if the user enable or disable the video, the status of 'videomuted' change and is equal to the real status!
It working for 'audiomuted', without a problem...

### Steps to reproduce:

1. Use this script :
https://github.com/jitsi/jitsi-meet/blob/8758c222c6f4ffa6f2403ff1a4b097d3437b52a5/resources/prosody-plugins/mod_muc_size.lua#L162-L168

2. Change the script with :
```
local nick = pr:get_child_text("nick", "http://jabber.org/protocol/nick") or "";
local email = pr:get_child_text("email") or "";
local videomuted = pr:get_child_text("videomuted", "http://jitsi.org/jitmeet/video") or "";
local audiomuted = pr:get_child_text("audiomuted", "http://jitsi.org/jitmeet/audio") or "";

occupants_json:push({
    sEmail = tostring(email),
    sNick = tostring(nick),
    bVideoMuted = tostring(videomuted),
    bAudioMuted = tostring(audiomuted)
});
```

3. Restart every service and call :
`<URL>/room?room=<ROOM_NAME>
`

### Expected behavior:

I put 'startWithVideoMuted' at 'true' in 'config.js', so the value should not be 'false'..

### Server information:

- Jitsi Meet version: 2.0.4627-1
- Operating System: Debian 9

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org too

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by alternadom** [comment]
Hi,

It is a bug and it is not about the config nor the quality :(

The behavior is not correct just about the status..
The config does what we asked!

**Comment by alternadom** [comment]
Any idea ?
