### ISSUE TITLE
Hide insecure room name warning button and Invite others button on Android SDK 

### ISSUE THREAD

**Issue by gungorhafize** [jitsi/jitsi-meet#7020]
After the update 2.9.0 release, insecure room name warning button and invite others button appeared during ongoing meeting. Is there any implementation/method to hide these buttons on MainActivity?

i.e like (setInviteButton(false) setInsecureRoomWarning(false)) ?

Thanks for your attention

**Comment by l3d00m** [comment]
Related #6801, but as android might be different I'll leave this open for now
