### ISSUE TITLE
Disable Video Adjustment

### ISSUE THREAD

**Issue by marty90** [jitsi/jitsi-meet#7024]
Hello,

we are running a private instance of Jitsi.
We have the need for disabling video adaptation to be sure the resolution is fixed all the call long.

How can we do this?

Thank You

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
