### ISSUE TITLE
Disable notifications on people connecting or disconecting

### ISSUE THREAD

**Issue by py-crash** [jitsi/jitsi-meet#7028]
We used Jitsi as a "hallway track" for South East Linux fest tied up to matrix (room was hosted at https://jitsi.riot.im/).
The main problem is that we had a lot of participants joining and leaving the room all the time. And it gets annoying to hear the connect/disconnect sound every time. And I didn't found a way to mute it.

**Comment by damencho** [comment]
Please when having questions or problem use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L202

**Comment by py-crash** [comment]
The problem is that only the server admin can configure it. There should be a button in the user interface

**Comment by yogeshsolankigithub** [comment]
@damencho  solution provided by you  is not working properly. it just disable only  visual  notification not audion  notification.
please provide another soloution

**Comment by mrego** [comment]
> @damencho solution provided by you is not working properly. it just disable only visual notification not audion notification.
please provide another soloution

I guess you can play with [`startAudioMuted` setting](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L107) to avoid the sounds on that case. At least it looks like that's used to play or not the sounds at [`_maybePlaySounds()`](https://github.com/jitsi/jitsi-meet/blob/c5f6df5210635e5bd5c6fc063bee706f05dc1273/react/features/base/participants/middleware.js#L322). Maybe `DISABLE_JOIN_LEAVE_NOTIFICATIONS` should be included on the check to avoid playing the sounds if it's enabled.

**Comment by johnwry** [comment]
Is there a solution to this yet?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/0ee13b1fd8c99cf189c7f8dee1abe97e2ebdfa5f/interface_config.js#L67

**Comment by PyraPOD** [comment]
> https://github.com/jitsi/jitsi-meet/blob/0ee13b1fd8c99cf189c7f8dee1abe97e2ebdfa5f/interface_config.js#L67

I tried this setting...

/**
     * If true, notifications regarding joining/leaving are no longer displayed.
     */
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: true,

But I still hear the sound of notifications when people join or leave my self-hosted Jitsi. So this means that this setting does not work.
