### ISSUE TITLE
Option to hide "Invite more people" overlay

### ISSUE THREAD

**Issue by capcom-r** [jitsi/jitsi-meet#7029]
One strange thing happened over the last few days, possibly due to an update to the Meet API is that there’s a new button that pops up on hover over the interface (screenshot below) asking the person in the meeting to invite more people. We’d really like for this to be hidden, but can’t find anything in the config parameters list to do so.

So a feature request would be to have an option in the config parameters which allows this to be disabled.

We've tried looking through all the parameters, looking for any changes that may have happened in the API, and considered self-hosting Jitsi (we'd prefer not to for such a simple reason if there's a workaround).

![image](https://user-images.githubusercontent.com/4749354/84573204-0aa75380-ad6d-11ea-9cd6-a08b82086826.png)

**Comment by damencho** [comment]
For questions use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/pull/7021
