### ISSUE TITLE
Set config.deploymentInfo.userRegion in mobile

### ISSUE THREAD

**Issue by hasgardee** [jitsi/jitsi-meet#7030]
I setup octo for my server with region-based switching. Currently, from our website front end we are finding the best region server for the user using latency check then we are passing that region to the config using config.deploymentInfo.userRegion:“region2”. It is working fine on the website
The problem is it is not working on mobile. I tried appending the same config into the URL and added a new config parameter in the mobile SDK. but no luck. I whitelisted deploymentInfo in the js file,
Does anyone have any idea how can I do this?

Thanks

**Comment by hasgardee** [comment]
fixed by adding "deploymentInfo" into /react/feature/base/config/configWhitelist.js

**Comment by ickarakurt** [comment]
Correct path : `react/features/base/config/configWhitelist.js`
