### ISSUE TITLE
Jitsi app on Android doesn't respond to volume control

### ISSUE THREAD

**Issue by qotol** [jitsi/jitsi-meet#7031]
### Description:

Android Jitsi Meet app version 20.3.0 does not respond to volume control during a video call. The volume appears to be fixed at maximum. Subsequent volume control in another app like Whatsapp or Zoom present no issues after terminating Jitsi Meet.

### Steps to reproduce:

Attempt to change call volume using phone hardware buttons or via sound control sliders.

### Expected behavior:

Call volume should change according to user control.

### Actual behavior:

Call volume does not change according to user control.

### Server information:

- Jitsi Meet version: 4127
- Operating System: Debian 10

### Client information:

- Browser / app version: Jitsi Meet app 20.3.0
- Operating System: Android 8

**Comment by pl-gauthier** [comment]
It is still an issue as of version 20.4.2 running on Lineage OS 17.1 with microG.
