### ISSUE TITLE
Disable "Invite more people" button via API

### ISSUE THREAD

**Issue by gpalmas** [jitsi/jitsi-meet#7034]
Actually is impossible to disable the message "You are the only one in the meeting" and the "Invite more people" button when the meeting is launched via API on the meet.jit.si server.
It will be very useful for a lot of people.
I already tried to disable all invite functionalities by adding "disableInviteFunctions: true" to the API request options but it's not working.
It will be useful to add an overridable configuration option.
The message and the button are also not translated in local language.

**Comment by l3d00m** [comment]
Please see #6801

**Comment by gpalmas** [comment]
Sorry... Thanks a lot!

**Comment by l3d00m** [comment]
No worries, harder to find because it was already closed
