### ISSUE TITLE
Android: live stream note doesn't fit the field

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#7035]
![image](https://user-images.githubusercontent.com/14617699/84606741-464b3600-aeb1-11ea-8adb-cd7115b943e8.png)

**Comment by 532910** [comment]
Is any update there?

**Comment by saghul** [comment]
Sorry, no updates as of yet.

**Comment by bhimanshukalra** [comment]
Hi Jitsi team!
If this issue still exists, I'll be happy to work on it. Kindly assign it to me.

Also, I can only think of only two ways at the moment:
First, shorten the string.
Second, enable multiline for text input.

If assigned, should I go ahead with the second approach?

Thanks!

**Comment by saghul** [comment]
This issue no longer applies since the dialog got re-done.
