### ISSUE TITLE
Android: live stream popup bottom corners issue

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#7036]
![image](https://user-images.githubusercontent.com/14617699/84606789-92967600-aeb1-11ea-8857-84b28023f7e1.png)

**Comment by 532910** [comment]
Is any update there?

**Comment by 532910** [comment]
Why time is a reason not to implement this?

**Comment by 532910** [comment]
Dear stale bot, please go away

**Comment by 532910** [comment]
still actual

**Comment by saghul** [comment]
This dialog has been refactored, it no longer looks lien this.
