### ISSUE TITLE
IFrame API: Share a Youtube Video does not work

### ISSUE THREAD

**Issue by informatikTirol** [jitsi/jitsi-meet#7037]
When you share a Youtube video, the clients which uses the IFrame API does freeze. 
In the screenshot below you see on the right the client which shares the youtube video, on the upper left the frozen iframe api client, in the lower left the client without the iframe api. 

https://www.dropbox.com/s/8tuz9mgmksn399h/obNp.jpg?dl=0

The error occurs on the latest nightly build,  https://alpha.jitsi.net and https://meet.jit.si

Here I prepared the same test client as I did for #6865

https://jitsi.informatik.tirol

**Comment by informatikTirol** [comment]
@jallamsetty1

**Comment by pvictorlv** [comment]
I see if we remove "pointer-events: none;" from the style tag of div#sharedVideo and the user press play in the youtube video then it works normally. This should be some cross-reference related problem.

**Comment by ludi81** [comment]
Did you fix this problem? I still have the problem with my installation.

**Comment by otrsk** [comment]
Same here, and removing the 'pointer-events' attr seems to be a workaround. Requires a custom client deployment, obviously...

**Comment by otrsk** [comment]
PS There's an easy fix: Append `&widget_referer=[yourdomain]` to the youtube URL to be shared

**Comment by otrsk** [comment]
This is still an issue I’m afraid

**Comment by shoolpani-dubey** [comment]
We are also facing the same issue.

**Comment by informatikTirol** [comment]
@saghul
it works, thank you!

**Comment by taihoa** [comment]
I have same issue.
Please help me!
