### ISSUE TITLE
"Unfortunately something went wrong" when second user joins 

### ISSUE THREAD

**Issue by vishalkale1** [jitsi/jitsi-meet#7038]
### Description:

When a second user joins, both users see "Unfortunately something went wrong", and the browsers try to re-connect. Same as https://github.com/jitsi/jitsi-meet/issues/5696

But I am getting below error,

![Screenshot 2020-06-12 at 6 39 39 PM](https://user-images.githubusercontent.com/57800843/84625699-728ea300-af01-11ea-946d-93a8a5858446.png)

I tried this,

> sudo apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2
> sudo apt-get purge prosody
> sudo apt autoremove
> sudo apt-get -y install jitsi-meet
> sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

Didn't solve the problem.

Result of 'dpkg -l | grep jitsi'

> ii  jitsi-meet                             2.0.4627-1                                  all          WebRTC JavaScript video conferences
> ii  jitsi-meet-prosody                     1.0.4127-1                                  all          Prosody configuration for Jitsi Meet
> ii  jitsi-meet-turnserver                  1.0.4127-1                                  all          Configures coturn to be used with Jitsi Meet
> ii  jitsi-meet-web                         1.0.4127-1                                  all          WebRTC JavaScript video conferences
> ii  jitsi-meet-web-config                  1.0.4127-1                                  all          Configuration for web serving of Jitsi Meet
> ii  jitsi-videobridge2                     2.1-202-g5f9377b9-1                         all          WebRTC compatible Selective Forwarding Unit (SFU)

Please help to resolve it asap.

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Also: "Please help to resolve it asap." You serious?
---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
