### ISSUE TITLE
Possibility to promote other moderators

### ISSUE THREAD

**Issue by awlx** [jitsi/jitsi-meet#7041]
**Is your feature request related to a problem you are facing?**
Sometimes it's necessary to promote more moderators on the fly or you cannot provide user credentials to everyone. So it would be awesome if moderators can promote other users to moderators too.

**Describe the solution you'd like**
Add a button in the moderator view to promote users to moderators

**Describe alternatives you've considered**

**Comment by validev** [comment]
That'd be really a nice way to avoid messy handling of a concept like "user accounts" while still being "in control" of a meet.

**Comment by awlx** [comment]
Bump

**Comment by saghul** [comment]
This is already implemented and IIRC it should have been part of the last stable release.

<img width="413" alt="Screenshot 2020-09-17 at 10 34 13" src="https://user-images.githubusercontent.com/317464/93445890-6b48ae00-f8d1-11ea-9728-8d1336e0a20c.png">

You can test it on https://alpha.jitsi.net

**Comment by awlx** [comment]
Oh nice!

**Comment by awlx** [comment]
Fixed!
