### ISSUE TITLE
Crash - when joining Jitsi from Chrome on Android

### ISSUE THREAD

**Issue by tdrp** [jitsi/jitsi-meet#7043]
### Description:

This started happening a couple days ago at most. Joining a call from an Android phone using the Chrome browser causes Chrome to crash with the "Aw snap" message. This happens as soon as the video stream from the other user(s) begins getting received. This repros on the regular meet.jit.si as well

### Steps to reproduce:

1. Open meet.jit.si/randomroom2342 on android phones in Chrome.

### Expected behavior:

Conference call goes through

### Actual behavior:

1- Takes some time to load the video from the other users but then crashes before it renders it.
2- If it doesn't repro for you I can get more logs but I am not sure where to look for the relevant ones.

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System:

### Client information:

- Browser / app version: Chrome
- Operating System: Android 6.0

**Comment by saghul** [comment]
If Chrome ceases there is not much we can do, it’s a Chrome bug.

What Chrome version do you have?

**Comment by tdrp** [comment]
Thanks - it is:
83.0.4103.101

FYI it used to work fine about a week ago, this appears to be newish.
