### ISSUE TITLE
Support single sign-on via SAML or OpenID connect

### ISSUE THREAD

**Issue by ngulden** [jitsi/jitsi-meet#7046]
**Is your feature request related to a problem you are facing?**

Jitsi currently supports LDAP authentication and together with guest mode allows several use cases from participants limited to users with accounts to everyone is a guest.

User story: As system administrator I operate an environment with central identity management that supports LDAP and SAML or OpenID Connect. I'd like to offer my users single sign-on. This would allow them to login once at the identity provider and then use other services without another login. 

Support for single sign-on would increase the user experience in scenarios where organizations operate their own jitsi environment and have the requirement that at least the operator of a conference is logged in.

**Describe the solution you'd like**
One needs to distinguish between two status:

1. User is not authenticated via single sign-on: The user clicks on login in jitsi and is then redirected to the login form of the identity provider. There the user provides the credentials, is authenticated and redirected back to jitsi as authenticated user.

2. User is already authenticated via single sign-on: Jitsi recognizes the single sign-on authentication of the user and offers features / settings limited to authenticated users.

**Describe alternatives you've considered**

LDAP already provides central user management which already is a benefit. But, users still have to authenticate in jitsi. IT environments in organizations offer multiple services and it is quite annoying to authenticate to each service with the same credentials. Single sign-on would ease this pain.

**Comment by mraqkhan** [comment]
+1 for this feature. OpenIDConnect provides jwt token which jitsi can consume in order to work with OIDC SSOs.

**Comment by saghul** [comment]
@mraqkhan Usually Jitsi cannot consume the token as is, but a backend service exchanges a SSO token for another just for Jitsi. The Jitsi token allows you to limit the room that a user has access to, for example. This is the model we use at 8x8 for example.

**Comment by Echolon** [comment]
One or the other is a duplicate, but I don't wanna decide:

saml/shiboleth auth #311

**Comment by afranke** [comment]
Still relevant, go away stalebot.

**Comment by afranke** [comment]
ORLY?

**Comment by haslersn** [comment]
This is still relevant.

**Comment by teutat3s** [comment]
I didn't try it out yet but [in this forum thread](https://community.jitsi.org/t/jitsi-meet-oauth-authentication/31374/15) someone states to have gotten OAuth working with this prosody module (looks like it was made with keycloak in mind)

https://github.com/rgrunbla/mod_auth_oauth

I'll try it out and report back

**Comment by saghul** [comment]
Hey folks. We are not planning to implement new authentication mechanisms on Jitsi Meet at this stage. We already have a few and AFAICT all possibilities are covered with reasonable amounts of glue components.

**Comment by Garagoth** [comment]
Could you please document how to glue and what components to glue to have saml working?

**Comment by haslersn** [comment]
Which components do I need in order to have OpenID connect authentication?

**Comment by saghul** [comment]
We don't use SAML, so those who do are the ones who could help document this. You can find some tips in this previous comment: https://github.com/jitsi/jitsi-meet/issues/7046#issuecomment-804274858

**Comment by TBG-FR** [comment]
For those interested :wink: https://community.jitsi.org/t/improving-jitsi-authentication/108753

**Comment by Glowsome** [comment]
In essense as TS has expressed is that LDAP "might" expose more then what one wants to expose to a/the Jitsi server, as the connection potentially can be used for harvesting.
Replacing LDAP with a different type of authentication ( and capable of relaying needed information for/to the application to function) s therefore the way to go.

In this ( from my point of standing with a fully functional IDP which supports both OpenID-Connect aswell as SAML(1/2) i have after trying out alot of setups ( and some own coding) to try and get this setup.

In my case the best/opted for solution was introducing [https://github.com/rgrunbla/mod_auth_oauth](https://github.com/rgrunbla/mod_auth_oauth)

The above did give me atleast some means as to integrating it with Oauth/OIDC, but not quite satisfied.
Due to time restrictions i have not been able to look into this further.

Still i hope this 'poke' might give you a direction as to solving your situation.

- Glowsome

**Comment by IntelligentesTierMaulApollo13** [comment]
For the sake of completeness I just wanted to mention [jitsi-admin / Jitsi Manager](https://github.com/H2-invent/jitsi-admin) - I'd say this tool implements much of what was requested...
