### ISSUE TITLE
Show dominant speaker display name

### ISSUE THREAD

**Issue by shapkarin** [jitsi/jitsi-meet#7057]
I can't see username of the person who speak.
I can implement it as an option in interface config like `active_username` or something. 
And show it in some area.

**Comment by damencho** [comment]
Nope, there is no such feature.

When you have questions or problems use the community forum before opening new issues. Thank you.

**Comment by shapkarin** [comment]
@damencho it a feature request issue. I wonder to see the username and can implement it.

**Comment by damencho** [comment]
I see, sorry. 
Providing some mockups on how it will look will help to sync with design.

**Comment by damencho** [comment]
SHOW_DISPLAY_NAME_ON_STAGE: false seems like a reasonable name with default value for interface config.

**Comment by shapkarin** [comment]
@damencho no worries. Maybe better is `SHOW_DOMINANT_SPEAKER_USERNAME`?

**Comment by damencho** [comment]
That is Display Name, not username. SHOW_DOMINANT_SPEAKER_DISPLAY_NAME

**Comment by shapkarin** [comment]
OK.

**Comment by shapkarin** [comment]
That's a good name. I didn't thought where to place a display name. Hope I will find some or someone will help me.

**Comment by shapkarin** [comment]
Thanks for everyone. I hope that I will back to this task in a two weeks. Implementation is not a big deal, thanks for contributors – It's just a react app.

**Comment by shapkarin** [comment]
I hope that I implement that right with the commit above. Maybe I will figure out with UX, not sure. 
Maybe add it under the room name at conference page.

**Comment by shapkarin** [comment]
Can someone share a link to the UX template? How about to add that template to the `CONTRIBUTING.md`?

**Comment by shapkarin** [comment]
UX template - I mean the latest mockup?

**Comment by shapkarin** [comment]
I will try to add function to the getDominantParticipants or getDominantSpeaker to the `react/features/base/participants/functions.js` also maybe the second function `getDominantSpeakerName` 
Instead of commit above

**Comment by shapkarin** [comment]
I guess it will be more handy
https://github.com/shapkarin/jitsi-meet/blob/dcd6684beb2a74e7670524bfbfd5a70c000ba45b/react/features/base/participants/functions.js#L397-L410
