### ISSUE TITLE
interfaceConfigOverwrite whitelist missing options

### ISSUE THREAD

**Issue by jhiswin** [jitsi/jitsi-meet#7060]
Specifically I am trying to override SHOW_CHROME_EXTENSION_BANNER, but it looks like the MOBILE_APP_PROMO also does not work, along with many other options.  

If it is necessary to include it to encourage use of the extension, I would prefer it to pop up when the feature is requested for use, or allow it to time-out, because for the most part the banners cause confusion with the users who ask why they have to download things to use the chat, and then assume that the chat does not work.

Was working until just recently on meet.jit.si

### Steps to reproduce:
Use interfaceConfigOverwrite option

    interfaceConfigOverwrite: {
          MOBILE_APP_PROMO: true,
          SHOW_CHROME_EXTENSION_BANNER: false,
          TOOLBAR_BUTTONS: [
            'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
            'fodeviceselection', 'hangup', 'profile', '', 'chat', 'recording',
            'livestreaming', 'etherpad', 'sharedvideo', 'settings', 'raisehand',
            'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
            'tileview', 'videobackgroundblur', 'download', 'help', 'mute-everyone',
            'e2ee'
          ],

        }

### Expected behavior:

interfaceConfig MOBILE_APP_PROMO and SHOW_CHROME_EXTENSION_BANNER should propagate to interfaceConfig, and disable the Chrome extension banner or allow to enable/disable the mobile app banner.

### Actual behavior:

![image](https://user-images.githubusercontent.com/120998/84833949-5a507e00-affe-11ea-9659-d4fb0fde4b2f.png)

### Server information:

latest Jitsi External API

### Client information:

Chrome 83 Windows 10

### Additional information:

SHOW_CHROME_EXTENSION_BANNER was added to the whitelist a while back, but the recent refactoring of the config code here appears to have reverted it:
https://github.com/jitsi/jitsi-meet/commit/6aed9bc0c88a704a1f49fae79ebea636ee549c2c#diff-c74306a7d7201be3763231c69c660357

The commit message says "by default", but the changes in the code actually enforce never allowing it to be changed.

**Comment by madhavarshney** [comment]
As @jhiswin said, this seems to be a recently introduced change / regression, as it worked a few days back. The PR for the commit is #7025.

**Comment by stuckinaboot** [comment]
Looks like the PR was shipped but this issue is still showing up when using public Jitsi meet in an iframe even with `SHOW_CHROME_EXTENSION_BANNER: false`. Is it taking a few days to propagate across Jitsi servers? I'm a huge fan of Jitsi btw and really appreciate how much you all are doing to support it.

**Comment by saghul** [comment]
That PR prevents the override of the option, yes, but it hasn’t been deployed yet.

I think this I the same problem as https://github.com/jitsi/jitsi-meet/issues/7061 which a bug in not reading the overridden value early enough.

I am not 100% sure though.

**Comment by jhiswin** [comment]
This is the line and function that filters out the options with _.pick based on the whitelist file.  The overwrite options are getting discarded before being sent to config:
https://github.com/jitsi/jitsi-meet/blob/0598e7369b2dfac9c11637c3c356cf634466430f/react/features/base/config/functions.any.js#L118  
https://github.com/jitsi/jitsi-meet/blob/0598e7369b2dfac9c11637c3c356cf634466430f/react/features/base/config/functions.any.js#L83

**Comment by jhiswin** [comment]
Looks like the issue is affecting all the options right now.  Seems as if none of the config options are being read correctly.

**Comment by capcom-r** [comment]
> Looks like the issue is affecting all the options right now. Seems as if none of the config options are being read correctly.

Yes, it definitely looks like it's affecting more options. `APP_NAME` for example is no longer working either. Some options are still working, but an increasing number are not.

**Comment by johnxie** [comment]
Thanks, bumping this up and hoping the fix gets deployed soon.

**Comment by jhiswin** [comment]
Let me know if these updates are annoying you guys.  Appears meet.jit.si has fixed the problems with all config options not being defined or initialized.
However, the filtering of interfaceOverwrite referenced in this issue appears to still be in effect.

**Comment by johnxie** [comment]
@jhiswin thanks, in particular in our situation we are no longer able to hide/disable the "Install Chrome Extension" warning.

<img width="345" alt="Screen Shot 2020-06-23 at 5 20 34 PM" src="https://user-images.githubusercontent.com/792088/85481045-f0902100-b575-11ea-8d7f-70aaafbc4f2e.png">

**Comment by diegodorado** [comment]
Same here, any workaround to overcome this?

**Comment by RutgerBevers** [comment]
We have the same issue, it's very annoying to our users :(

**Comment by jhiswin** [comment]
https://github.com/jitsi/jitsi-meet/pull/7078  
An update: It looks like it has been merged, but hasn't hit the pub server yet.  Just have to be patient and wait for it to land.

I've done a quick test by intercepting the call to _.pick() locally though the dev console and pushing 'SHOW_CHROME_EXTENSION_BANNER' into the second parameter to _.pick(), and the banner does get disabled, so that patch should definitely allow the banner to be disabled.

**Comment by saghul** [comment]
Yep the next deploy will have the fix.

**Comment by finalhit** [comment]
Will it fix SHOW_JITSI_WATERMARK issue, too?

**Comment by jhiswin** [comment]
@finalhit No: https://github.com/jitsi/jitsi-meet/issues/7162  It's odd that KiwiIRC chose to by default hide the Jitsi logo, given that it was prominently shown (before docs were moved to Handbook): "Please don't remove the Jitsi logo".  I think the only somewhat reasonable thing to request is to not have Jitsi.org pop up on click or have it warn that it will pop up a window so accidental clicks don't cause issues.  Which is a separate issue and one that should be up to their discretion.

**Comment by damencho** [comment]
When using meet.jit.si deployment the term and service ask not to remove logo and branding https://jitsi.org/meet-jit-si-terms-of-service/, when using self-hosted deployment you can change that in your hosted interface config.

**Comment by jhiswin** [comment]
> [...] you shall allow such Branding to be viewed and interacted with by such third-party users for a period of at least 15 seconds from when first presented, and you shall not otherwise remove, obscure, modify, or alter any such Branding.

Does this mean that you guys are actually fine with branding and logos in the style of splash screens, and would be open to having the UI changed in such a way?
I don't personally find it necessary, but there are probably potential users who would want something like that.

**Comment by diegodorado** [comment]
`SHOW_CHROME_EXTENSION_BANNER` seems to be merged to master, but `MOBILE_APP_PROMO` isn't there, and it is also annoying if you intend to use it web only. can the issue be re opened or should it open a nuew issue about this?

**Comment by Shillos** [comment]
> It's odd that KiwiIRC chose to by default hide the Jitsi logo, given that it was prominently written on the Iframe API example (before docs were moved to Handbook): "Please don't remove the Jitsi logo".

@jhiswin actually you can use interfaceConfigOverwrite or configOverwrite on that. Based on this configuration https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js but also could be because of the handbook! On my personal private server, I have done this too. Strangely though we all seem to have the common bug, that fix must be here soon I hope!. Patience! :-)

**Comment by jhiswin** [comment]
Oh, @Shillos I think you've misunderstood.  Not allowing hiding the Jitsi logo on meet.jit.si is intentional.  It just wasn't being enforced before.  It's expressed in the TOS that you are not allowed to hide Jitsi branding (and at the top of Iframe External API docs).
Jitsi Meet has been changed now to not let you use Overwrite to change those settings by default now, by removing them from the whitelist.
.
So it looks like KiwiIRC project people did not realize that the meet.jit.si project wants and requires that their logo (branding) is visible to anyone who uses it.

**Comment by jhiswin** [comment]
> `SHOW_CHROME_EXTENSION_BANNER` seems to be merged to master, but `MOBILE_APP_PROMO` isn't there, and it is also annoying if you intend to use it web only. can the issue be re opened or should it open a nuew issue about this?

@diegodorado 
I don't think it is enabled by default on meet.jit.si right now.  It looks like they changed `MOBILE_APP_PROMO` to default to false in config at the same time that they refactored the whitelist.   (Which is preferable for me, since I'd rather have a separate active walking users through the app install than a banner that blocks UI, if it is the chosen way to use it.)

I've made a [PR](https://github.com/jitsi/jitsi-meet/pull/7186), but I don't feel strongly about it and am satisfied with it the way it is now.  If anyone else wants that config, they should take over the PR and "champion" it (explaining why it's necessary).

**Comment by RutgerBevers** [comment]
> Yep the next deploy will have the fix.

Sorry for being a noob @saghul but where can I see deploy history?

I just tested the bug is still present.

**Comment by vrde** [comment]
I have the same issue. This is the config I pass to the `JitsiMeetExternalAPI` constructor:

```
options = {
    // ...
    interfaceConfigOverwrite: {
        // ...
        SHOW_CHROME_EXTENSION_BANNER: false,
        // ...
    }
}
```

But the banner is still there :disappointed: 

![image](https://user-images.githubusercontent.com/134680/102591442-4bb06400-4112-11eb-80df-1e5936b96c0e.png)

**Comment by damencho** [comment]
That can be controlled server side in interface config. It cannot be overwritten, this is how it is supposed to work.

**Comment by coccochanel** [comment]
> 
> 
> That can be controlled server side in interface config. It cannot be overwritten, this is how it is supposed to work.

Hi dear,

where i can find the file https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/interfaceConfigWhitelist.js in my serveer?
i need the link /ex: /etc/...)

thanks in advice

**Comment by damencho** [comment]
You cannot,  that is compiled in app.bundle. you need to recompile the app to change it.

**Comment by coccochanel** [comment]
> 
> 
> You cannot, that is compiled in app.bundle. you need to recompile the app to change it.

Thanks man!!

How can i recompile the app?

**Comment by damencho** [comment]
I gave you an answer in another comment, please use the community forum before you start writing in random issues and PRs, thank you.
