### ISSUE TITLE
Issue with SHOW_CHROME_EXTENSION_BANNER flag

### ISSUE THREAD

**Issue by capcom-r** [jitsi/jitsi-meet#7061]
In the `interface_config.js` file, the flag `SHOW_CHROME_EXTENSION_BANNER` is no longer having an effect. If it's not there, and is `false` by default, the banner shows. If it is explicitly added as to `interfaceConfigOverwrite` and set to `false`, it's still there. This only started happening today.

To reproduce, integrate the JitsiMeetExternalAPI on any web page, and to confirm the setting does not work, try setting `SHOW_CHROME_EXTENSION_BANNER` to `false` in `interfaceConfigOverwrite` for the meet's options.

This issue is on all browsers we've tested.

We're using the latest version of the Jitsi Meet external API.

**Comment by saghul** [comment]
I think the problem here is that the config override happens a tad later and thus this option is not taken into account early enough.

In addition the fact that this option is on interface_config makes things a bit worse, since it's not loaded the same way as config.js.

**Comment by jhiswin** [comment]
@saghul Same issue as here, should these be merged?  It looks to me more like the options in interfaceConfigOverwite are deliberately filtered using _.pick to disallow overriding.  https://github.com/jitsi/jitsi-meet/issues/7060

**Comment by l3d00m** [comment]
Yeah, I'd close this in favour of #7060 as it was opened earlier and provided a bit more detail. Please continue the discussion there.
