### ISSUE TITLE
Droidcam

### ISSUE THREAD

**Issue by Erik-Per** [jitsi/jitsi-meet#7070]
I set up my phone as a webcam using Droidcam.
https://play.google.com/store/apps/details?id=com.dev47apps.droidcam

Then I went over to Jitsi & selected Droidcam as the webcam.
Since that moment forward, Jitsi shows me this message:  

Jitsi Meet needs to use your microphone and camera.
Select Allow when your browser asks for permission.

I never got the opportunity to allow access for the microphoen & camera.
I am no longer able to access Jitsi settings.
Whenever I close the browser (Chrome) & restart a Jitsi meeting, I again get the same message & again habe no access to settings. Same issue in Firefox, although I was able to get into settings there & was able to select a different webcam. Selecting Droidcam as a webcam in Jitsi using Firefox is no longer possible.

![Droidcam probleem](https://user-images.githubusercontent.com/36383292/84941175-46ca1380-b0e1-11ea-9e05-93f0b6eb253d.jpg)

**Comment by Erik-Per** [comment]
I was able to fix the issue , by removing the Droidcam software.
The question now is, why is Jitsi not playing nice with Droidcam ?

**Comment by tu-nv** [comment]
In my case, I use droidcam with jitsi and they work very well. So problem might be your droidcam setup messed with the system.

**Comment by Erik-Per** [comment]
Maybe the operting systems (Windows 8.1) & phone (LG Nexus 5X) explains why it's not working on my side then ?
