### ISSUE TITLE
Prevent active meeting page closing

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#7071]
Please add support for confirmation to close page with meeting ongoing.

Like OSM for example when you're trying to close the page with unsaved modifications:
![image](https://user-images.githubusercontent.com/14617699/84973770-8f59ef00-b12a-11ea-939b-d2a3c6439dac.png)

**Comment by 532910** [comment]
Is any update there?

**Comment by saghul** [comment]
Sorry, no updates.

**Comment by 532910** [comment]
Why time is a reason not to implement this?

**Comment by ahreurink** [comment]
@saghul is there a reason this is not implemented? @kyliank and I would like to pick it up, but if it is infeasible or not desirable we won't work on it. If it still a desirable feature, which section of the code would be a good place to implement it? Perhaps @muscat1 knows this?

**Comment by 532910** [comment]
Why time is a reason not to implement this?

**Comment by 532910** [comment]
Still actual

**Comment by saghul** [comment]
No plans to implement this, sorry.

**Comment by 532910** [comment]
It's a pity, Saúl, could you say, why so?
If I'd PR this dialog, could it be accepted?

**Comment by saghul** [comment]
It would at least kickstart a conversation.

A 2 year issue clearly signals nobody wanted it bad enough to make a PR ;-)
