### ISSUE TITLE
Safari 13.1.1: No speakers detected

### ISSUE THREAD

**Issue by jkuchar** [jitsi/jitsi-meet#7073]
### Description:

Try to open conference in Safari, first impression is that it works perfectly (awesome work, thanks!). Problem is that web app does not detect output sound device (speakers), so you cannot hear anyone. The same thing works great in Chrome, Edge Beta and Firefox.

### Steps to reproduce:

1. https://meet.jit.si/test in Safari
2. you will hear noone, so you try to select output device and you see something similar to:
3. <img width="398" alt="image" src="https://user-images.githubusercontent.com/133822/84989032-4f533600-b143-11ea-8045-8e38d28a4315.png">

### Expected behavior:

Open conference and hear participants.

### Actual behavior:

Open conference and I does not hear participants.

### Server information:

- Jitsi Meet version: the one running on meet.jitsi.org
- Operating System: unknown

### Client information:

- Browser / app version: Safari 13.1.1
- Operating System: Mac OS Catalina 10.15.5 (19F101)

**Comment by Lominean** [comment]
Yes, the list of speakers is empty, but I can still hear others.

**Comment by jallamsetty1** [comment]
This is a browser limitation, Safari doesn't enumerate audio output devices and therefore do not support changing speaker. Apple guys haven't expressed a desire to change this behavior anytime soon. If you need to change the speaker, you will have to do so using the system settings on the OS.

**Comment by hamletmun** [comment]
https://bugs.webkit.org/show_bug.cgi?id=216641
