### ISSUE TITLE
Android: keyboard overlapping in chat part

### ISSUE THREAD

**Issue by kaushaldeligence** [jitsi/jitsi-meet#7076]
### Description:

The keyboard overlaps message box on the chat ui of jisti meet sdk.
This issue is on android part only. On iOS it is working fine.

### Steps to reproduce:

1. Open the jisti chat feature.
2. Click on the message box to type something.

### Expected behaviour:

No overlapping should have occurred.

### Additional information:

![1592477998541](https://user-images.githubusercontent.com/58382387/85013510-50f01e80-b182-11ea-892f-e3054ab41dac.JPEG)
![1592477998551](https://user-images.githubusercontent.com/58382387/85013521-564d6900-b182-11ea-8bed-bc399eb503b9.JPEG)
![1592477998578](https://user-images.githubusercontent.com/58382387/85013535-5baab380-b182-11ea-91df-da598daeebd2.JPEG)

**Comment by saghul** [comment]
@zbettenbuk Can you PTAL?

**Comment by ijoshivaibhav** [comment]
> 
> ### Description:
> 
> The keyboard overlaps message box on the chat ui of jisti meet sdk.
> This issue is on android part only. On iOS it is working fine.
> ### Steps to reproduce:
> 
>     1. Open the jisti chat feature.
> 
>     2. Click on the message box to type something.
> 
> 
> ### Expected behaviour:
> 
> No overlapping should have occurred.
> ### Additional information:
> 
> ![1592477998541](https://user-images.githubusercontent.com/58382387/85013510-50f01e80-b182-11ea-892f-e3054ab41dac.JPEG)
> ![1592477998551](https://user-images.githubusercontent.com/58382387/85013521-564d6900-b182-11ea-8bed-bc399eb503b9.JPEG)
> ![1592477998578](https://user-images.githubusercontent.com/58382387/85013535-5baab380-b182-11ea-91df-da598daeebd2.JPEG)

did it solved?

**Comment by saghul** [comment]
We solved this a bit ago. Can you test the latest beta? It’s version 20.3.0
