### ISSUE TITLE
Not leaving meeting when user killed android app manually 

### ISSUE THREAD

**Issue by Prashantilluminz** [jitsi/jitsi-meet#7084]
### Steps to reproduce:

1. Initiate meeting between two or more.
2. Wait for user to join
3. Kill app from recent apps section

### Expected behavior:

The user should automatically leave the meeting

### Actual behavior:

The user does not leave the meeting instantly.It took 60sec to leave.

### Server information:

- Jitsi Meet version:
- Operating System: Linux(Ubuntu)

### Client information:

- Browser / app version:2.9.0
- Operating System:Android sdk

**Comment by l3d00m** [comment]
Please fill out the template and at least provide the app version where it's happening and maybe the more precise steps, so it can be reproduced.

**Comment by Prashantilluminz** [comment]
any update on this ?

**Comment by ijoshivaibhav** [comment]
Guys we are having same issues. Please help

**Comment by ijoshivaibhav** [comment]
> 
> 
> any update on this ?



> 
> 
> any update on this ?

Did you found any solution?

**Comment by Prashantilluminz** [comment]
Hi i did not find exact solution for this but in jitsi they have set some timeout time which is 60 seconds and we can minimise that time, if we use jitsi at our backend in my case i set it to 20 sec.
NOTE:It is not the exact solution but it will help you.

**Comment by Harsha18** [comment]
> Hi i did not find exact solution for this but in jitsi they have set some timeout time which is 60 seconds and we can minimise that time, if we use jitsi at our backend in my case i set it to 20 sec.
> NOTE:It is not the exact solution but it will help you.

I am also facing same issue.

Where you set the timeout? In which file?

**Comment by vishalpathak24** [comment]
Facing same issues even when called .leave() / .finish() methods of JitsiActivity
