### ISSUE TITLE
Sometimes smartphone goes to sleep mode during Jitsi call

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#7086]
### Description:

I have problem similar to https://github.com/jitsi/jitsi-meet/issues/6600
I use Jitsi in [Rocket.Chat.ReactNative](https://github.com/RocketChat/Rocket.Chat.ReactNative) mobile application [version 4.7.0](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2008) with [JitsiMeetSDK (2.8.1)](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2008/commits/fa1ccb6aafc9539c59302d56bafdb2bdb70e10e9) on my Android 10 smartphone Xiaomi Mi 9 SE
As backend we use [stable-4627-1 in docker](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4627-1)
Most conferences all good, no problem. 
But sometimes my smartphone goes to **sleep mode** during conference (AudionOnly). Good thing in that case, that call is resumed and not finish at that moment.
I did some experiments and can tell, that with **Enable low bandwidth mode** enabled my smartphone goes in sleep mode every time (100% of cases) after phone sleep mode timeout.
But I'm sure, that I experienced that issue when I didn't do **Enable low bandwidth mode** - I just participate in AudioOnly conference and my smartphone went to sleep mode, and I was forced to periodically tap on smartphone screen to stay it awake.
Maybe in that cases Rocket.Chat somehow went to low bandwidth mode, but didn't want that.

### Expected behavior:

Jitsi call should stay active and don't let smartphone to go to sleep mode like when users watch youtube video or just video.
If user explicitly block his smartphone by pressing power button - Jitsi call should resume and not be finished (it is right now)

### Actual behavior:

Sometimes smartphone goes to sleep mode during Jitsi call
Smartphone always goes to sleep mode during Jitsi call if **Enable low bandwidth mode** was enabled

### Server information:

- Jitsi Meet version: [stable-4627-1 in docker](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4627-1)
- Operating System: CentOS7

### Client information:

- App version: Rocket.Chat 4.7.0
- Operating System: Android 10

**Comment by ankar84** [comment]
It's really annoying issue. 
It's just me experience that rotate problem?
We use Jitsi as part of Rocket chat and lot of my Android users comply about that rotate crash.
Please look at that problem, it's pretty easy reproduced.

**Comment by zioalex** [comment]
Hi @ankar84 m
Was this anyhow solved?
I still have the same problem today.
