### ISSUE TITLE
Voice - Video toggle design issue

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#7087]
The current Voice - Video control:
![image](https://user-images.githubusercontent.com/14617699/85114688-fd81dd00-b222-11ea-91ac-a2f5ac7d02aa.png)

should look so:
![image](https://user-images.githubusercontent.com/14617699/85115010-aa5c5a00-b223-11ea-9470-9149853962d5.png)

1. Common left position is "disabled", common right position is "enabled". If fact it's not selector between Voice or Video, but a Video switch.

2. Moreover the Voice should be completely removed, as you can't disable it here:
![image](https://user-images.githubusercontent.com/14617699/85115428-50a85f80-b224-11ea-98eb-ddbc072b9f32.png)

**Comment by saghul** [comment]
Good points!

We are going to get rid of it (hopefully) soon, since a pre-join screen is coming to mobile too.

**Comment by 532910** [comment]
I believe this issue should be opened until fixed.

**Comment by 532910** [comment]
Why time is a reason not to fix this?

**Comment by 532910** [comment]
Why time is a reason not to fix this?

**Comment by 532910** [comment]
still actual

**Comment by saghul** [comment]
We are not going to change this. It would confuse everyone since it has been like that since the beginning.

That said, we are close to removing the control altogether, once we have the mobile prejoin page in place.
