### ISSUE TITLE
Jitsi Calling Screen Problem

### ISSUE THREAD

**Issue by FarhanAli001** [jitsi/jitsi-meet#7089]
I was able to make audio conference call but the problem is that whenever the call connects the given below screen shows up, but i want to hide it and display my own custom UI, kindly help me, i will be very thankful to you
![IMG-20200619-WA0014 (2)](https://user-images.githubusercontent.com/66011882/85126338-246bef00-b1e2-11ea-84d6-07fc3878136f.jpg)

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
