### ISSUE TITLE
Add a brazilian portuguese (pt-BR) translation at Pootle

### ISSUE THREAD

**Issue by filhocf** [jitsi/jitsi-meet#709]
I want to translate jitsi-meet to brazilian portuguese, but I saw that haven't this language available in Pootle.

Since now, thanks in advanced.

**Comment by filhocf** [comment]
Need i do other thing to get a new language in Pootle? Can someone give me a orientation?

**Comment by gpolitis** [comment]
Hi @filhocf, sorry for the delay. I'll create it for you and update this issue.

**Comment by gpolitis** [comment]
I've added brazilian Portuguese to jitsi-meet. Thanks for your interest in the project!
