### ISSUE TITLE
JitsiMeetActivity not getting destroyed properly

### ISSUE THREAD

**Issue by mehul4795** [jitsi/jitsi-meet#7090]
### Description:

I am launching the JitsiMeetActivity from my app using the `JitsiMeetActivity.launch()` function. Once the meeting is started, the user enters the PiP mode and then again goes full screen by clicking on the full-screen icon in the PiP mode. Now, when the user ends the meeting the activity gets closed but it is still shown in the Recents screen. Clicking on the activity from the Recents screen again starts the meeting.

### Steps to reproduce:

1. Launch JitsiMeetActivity using the `JitsiMeetActivity.launch()` function.
2. Enter PiP once the meeting is started.
3. Go full screen by clicking on the icon in the PiP mode.
4. End meeting
5. Go to the Recents screen and click on the instance of the activity

### Expected behavior:

Once the meeting is ended, the JitsiMeetActivity should be completely destroyed and hence not shown in the Recents screen.

### Actual behavior:

On clicking the instance of the activity from the Recents screen, the meeting is started again.

![Screenshot_20200619_164823](https://user-images.githubusercontent.com/13131390/85127618-6a11d180-b24d-11ea-836e-c49d5154b321.png)

**Comment by TBG-FR** [comment]
I have noticed the same behavior, and it wasn't present in last SDK version (`2.8.2`), so I think we'll need to dig a bit into the commits between this version and the current one, to find the modification responsible for this behavior

**Comment by mehul4795** [comment]
> I have noticed the same behavior, and it wasn't present in last SDK version (`2.8.2`), so I think we'll need to dig a bit into the commits between this version and the current one, to find the modification responsible for this behavior

Thanks for the update. I am not sure but another possible solution can be to provide an option to pass a flag to the `JitsiMeetActivity.launch()` function that hides the JitisMeetActivity from the Recents screen. Check out [this link](https://developer.android.com/guide/components/activities/recents#removing) for more details.

**Comment by TBG-FR** [comment]
Unless it has been fixed (I don't see any related pr), this issue should stay in the list

**Comment by saghul** [comment]
We haven't made any changes around this to the SDK, but this something you can fix outside of it, isn't it?

**Comment by TBG-FR** [comment]
I don't think we can fix it from outside, we need to confirm this by making a test on latest version, but from what I remember, it's always happening, even if the app is in `singleTask` or `singleInstance`

**Comment by nirmalswmnthn** [comment]
Hi the latest version of jitsi 3..0.0 has the same problem, the Jitsi Activity is not destroyed and stays in recents, CONFERENCE_TERMINATED is also not called when PIP is dragged down and dismissed. How to fix it?

**Comment by saghul** [comment]
The conference is not ended when the PiP window is dragged. It continues in the background.
