### ISSUE TITLE
Tooltip UI issue on mobile browser

### ISSUE THREAD

**Issue by patelrr** [jitsi/jitsi-meet#7096]
### Description:

Tooltip for mute/unmute and camera doesn't get hide once shown.

### Steps to reproduce:

1.  Open on 'any mobile web browser'

### Expected behavior:

Tooltip should either get hide or on mobile browser tooltip can be disabled.

### Actual behavior:

Tooltip for mute/unmute and camera doesn't get hide once shown.

### Client information:

- Browser / app version: Any mobile browser
- Operating System: Android (should be same with ios [also)](url)

![Screenshot 2020-06-19 at 7 01 07 PM](https://user-images.githubusercontent.com/17478257/85138195-00e78980-b260-11ea-9fb2-c57bd9aeb85b.png)

**Comment by flunderpero** [comment]
This is a serious problem for us two. We ended up patching the CSS (we don't want to build from source right now) by appending this to `all.css`:
```
/* Disable tooltips on mobile devices.
   I know what you are thinking - what's that monster of a CSS selector?
   Well, it's the only way to hide the correct element so that the bug on iOS/Safari where users
   have to click twice on each button (because the first click triggers tho `hover`-event-listener
   that's bound to this element) ...
 */
.mobile-browser .atlaskit-portal[style*="z-index: 800"] {
    display: none !important;
}
```

Of course this is brute-force, brittle when it comes to updates but it works. It would be great to have tooltips disabled on mobile devices. A fix or a better "workaround" is very much appriciated!
