### ISSUE TITLE
Event Listner

### ISSUE THREAD

**Issue by amalafortunate** [jitsi/jitsi-meet#7102]
**How to Get the Participant name after they Join the meet.**
I am using jitsi external API, I need to get the participant name while it triggers the event listener

`api.on("participantJoined", ()=>{ });`

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org
Unfortunately, therefore I will close this issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by amalafortunate** [comment]
Yeha sorry for posting there.
Ive got answer for the question myself thank you
