### ISSUE TITLE
@saghul

### ISSUE THREAD

**Issue by SrinivasAttili84** [jitsi/jitsi-meet#7103]
@saghul 
Xcode 11.2.1
Build version 11B500

I also tried to run this in the root of the project:
**sh ios/scripts/release-sdk.sh**

The script worked.

However, I am not able to publish the archive to AppStoreConnect like I usually do.
After the run of the script I can see the new build in Xcode->Window->Organizer, where I can see all my archives for all my project.
The problem is the fact that my new archives appears under **Other Items**, instead of **IOS Apps**. Please check the image bellow for a better understanding.
Because my archive is under Other Items, I don't have the **Distribute App** button that uploads the app to AppStoreConnect. Instead, I have **Distribute Content**, which only exports it locally. 

<img width="1004" alt="Screenshot 2020-05-17 at 14 57 56" src="https://user-images.githubusercontent.com/23173094/82145018-7bcc1780-9850-11ea-97a8-2a529199ec7a.png">

What should I do in order to publish the archive to AppStore?

_Originally posted by @mihaistiuca in https://github.com/jitsi/jitsi-meet/issues/6730#issuecomment-629787054_

**Comment by saghul** [comment]
Please follow up on the already existing issue instead of opening a new one.
