### ISSUE TITLE
Lock Users for prevent unmute

### ISSUE THREAD

**Issue by nimaam** [jitsi/jitsi-meet#7106]
Dear All
I want to add feature which add possibility to lock the user and prevent unmute, in this way user raise hand and moderator unlock user otherwise user can not unmute himself/herself.
This is very useful and system like Bigbluebutton has this feature but Jitsi with all these power doesn't have this useful feature.
For this feature should we add a code to Jicofo to add locked participant property and in jitsi-meet to lock and unlock a user.

**Comment by l3d00m** [comment]
Please see #6664, I think it's very similar.
