### ISSUE TITLE
Webinar Mode

### ISSUE THREAD

**Issue by nimaam** [jitsi/jitsi-meet#7110]
Webinar is so simple,
if we have a feature beside all follow me and in this feature we have 2 type of users, who login to system and become presenter and viewers, for presenter there is nothing to do and they use this simple video conference panel but for viewers we rewrite the Toolbar buttons and they just have the disconnect button and the thumbnail videos is hidden for them, so they jut see the presenters and message box, in this mode their video is played to presenters and if the presenter want can start the meeting with audio muted and video muted and in this mode the viewers video and audio if off and if the presenter want to have their video can start follow me and send them the unmute permission and if the viewer give allow then this  click on allow can do the unmute audio and video and after the case is finished moderator can mute and turn the video off.
So this simple solution is so useful and I will be happy if anyone implement it to system for Free.

**Comment by AstraLuma** [comment]
Yes please this.

All I can find is UI hacks that wouldn't actually disallow anything.

**Comment by oussjarrousse** [comment]
Colleagues are requesting it as well as an alternative to popular less secure more costly webinar softwares

**Comment by Yolakalemowa** [comment]
any news on this?

**Comment by saghul** [comment]
No plans to implement a dedicated webinar mode.

We should already be pretty close in features with advanced moderation, visitors and follow me, for example.

**Comment by Yolakalemowa** [comment]
@saghul 

is there any feature that hides participants from being able to see each other? seeing ONLY the presenters?

**Comment by anirbandas18** [comment]
@Yolakalemowa I have found a way to do it to a great extent with some advanced UI configurations that might work for you. Maybe we can discuss this up.

**Comment by damencho** [comment]
@Yolakalemowa visitors

**Comment by saghul** [comment]
> @saghul 
> 
> is there any feature that hides participants from being able to see each other? seeing ONLY the presenters? 

You can use multi-pinning of up to 6 participants. The rest will remain in the filmstrip. Go to Settings - General to adjust.

**Comment by anirbandas18** [comment]
> [@Yolakalemowa](https://github.com/Yolakalemowa) visitors

any good resources to get started on visitors?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/tree/master/resources/extra-large-conference

**Comment by Yolakalemowa** [comment]
> > [@Yolakalemowa](https://github.com/Yolakalemowa) visitors
> 
> any good resources to get started on visitors?

hey @anirbandas18 would love to talk more. You have Signal or SimpleX? we can connect there. (if so, maybe PM me your username)

Also, I've been looking at BigBlueButton and it seems to have this webinar thing already. Still checking it out :)
