### ISSUE TITLE
Echo while loudspeaker is enabled - Android

### ISSUE THREAD

**Issue by devidasm** [jitsi/jitsi-meet#7113]
### Description:
We encountered an echo issue intermittently (sometimes it's happening always) while all participants are using loudspeaker. There is no such echo problems when we uses the earpiece or headphone.

### Steps to reproduce:

1. Join into a conference with more than 3 participant. ( Android devices only)
2. Make sure participants are joined from different remote places.
3. Make sure everyone is turned on the loudspeaker and the mic is not muted.
4. Then someone just start talking.

### Expected behavior:

A participant don't want to hear their own voice through the loud speaker while they talking.

### Actual behavior:

Assume that I'm says "hello" in a conference call   ->  It will blown through their loudspeaker -> At same time their microphone catches the sound from loudspeaker  -> and the same sound is broadcasting to everyone.

The above behavior is sustaining in a cyclic mode.  

At last this will turn into an beep sound.

We cannot say anything until the beep sound stops.

But we can stop this echo by turning on the mic mute option on all phone. 

### Server information:

- Jitsi Meet version: https://meet.jit.si
- Operating System:

### Client information:

- Browser / app version:   SDK 2.8.2
- Operating System: Android

**Comment by ersuman** [comment]
I am also facing this issue - with only 2 participants.
