### ISSUE TITLE
Roles in default JWT implementation

### ISSUE THREAD

**Issue by tsproesser** [jitsi/jitsi-meet#7114]
I'd love to see the ability to pass a moderator role to the default JWT implementation - or does it already exist and I don't know it?

My scenario: I want to connect clients to the conference with their real name (stored in the JWT) but that makes all the participants to moderators. This surely isn't my use-case 😉

Thank you

**Comment by jamesdeacon** [comment]
If I've understood you correctly, I had a similar need and found this plugin: https://github.com/nvonahsen/jitsi-token-moderation-plugin

**Comment by tsproesser** [comment]
I'll give it a try, thank you. But all in all the "Caveats" sound pretty hacky. Guess that could be a nice feature implemented in the default version?

**Comment by jamesdeacon** [comment]
Absolutely - it’d make a fantastic addition to the default version and must meet a lot of use-cases

**Comment by tsproesser** [comment]
For now I'm trying to go with the metioned plugin but the hook `module:hook("muc-room-created") ` is never called. Is there anything I need to setup for this?

**Comment by tsproesser** [comment]
Sorry for bumping - but I'd love to use my Jitsi-server in production and this is the last show-stopper for me. Anyone else experiencing this problem? Am I maybe doing something wrong?
