### ISSUE TITLE
Lobby: Only Show enter password option if a password is set 

### ISSUE THREAD

**Issue by tiiiecherle** [jitsi/jitsi-meet#7115]
Hey,

first of all thanks for all the work and effort that goes into jtisi meet.

When trying the new lobby feature a few of our users got confused about the possibility of entering a password in the lobby screen even if no password for the room is set.

We are using a self hosted auth-only instance of jitsi meet and they were trying to enter their prosody password which is not working.

My suggesting would be to only show the "enter password" button in the lobby if a password for the room is set.

Thanks a lot.

Kind regards

**Comment by alternadom** [comment]
Hi,

I would add that the password don't work simultaneously with the lobby :/ So why make it possible to enter a password ?

Hope there will be a solution ;)
