### ISSUE TITLE
Logo/Watermark is not shown on welcome page

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7117]
### Description:

Logo/Watermark is not shown on welcome page.
On the welcome page is a div container with the class `welcome without-content` with no logo inside.

**Comment by nextgen-networks** [comment]
... jipp - the logo also since 7-9 days ago - there have been made a plenty of parameter changes in the past few days.
But removing the default Logo on welcome page should be an optional at least well documented feature.
Would be glad if a good solution could be found.

**Comment by rasos** [comment]
The logo disappeared both on the welcome page and in the conference after an update of jitsi-meet-web:amd64 (1.0.4127-1, 1.0.4428-1).  

```
Element {
    background-image: url("undefined");
    max-width: 140px;
    max-height: 70px;
}
```
It seems that two variables have been introduced in `interface_config.js` lately: 

      DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.png',
      DEFAULT_LOGO_URL: 'images/watermark.png',

If you add them then the logo again appears.

**Comment by saghul** [comment]
Ping @vp8x8 do you know what happened here?

**Comment by vp8x8** [comment]
@saghul I have not added those variables to `interface_config`. Don't know what happened there...

**Comment by albertoVieiraNeto** [comment]
had this exact problem today, thanks for the comment @rasos, had to update to fix the "muted" error with google chrome.
