### ISSUE TITLE
Dial-in caller can't be heard in web app

### ISSUE THREAD

**Issue by JakeQZ** [jitsi/jitsi-meet#7124]
### Description:

`meet.jit.si` provides option for joining by phone by dialling in (e.g. +44 20 3885 2179).

The dial-in user can hear everyone else, and can be seen by everyone as a "44" icon, but cannot be heard by anyone using the web app.  Users of the mobile phone or tablet app (iOS/Android) can however hear the dial-in caller.

### Steps to reproduce:

1. Open https://meet.jit.si/WeCantHearYouCaller in browser (e.g. Firefox on Windows 10)
2. From a phone, dial +44 20 3885 2179 and enter meeting PIN 1867651731.
3. See if audio received by the phone will be consistently replicated in the web browser.

### Expected behavior:

Audio received through the phone will be consistently replicated in the web browser.

### Actual behavior:

Phone participant appears consistently silent in the web browser.  Occasionally their audio will come through for about 2 seconds after initial connection, but then drop out.

### Server information:

- Jitsi Meet version: As at `meet.jit.si` for the at least the last week or so.

### Client information:

- Browser / app version: Firefox 77.0.1 (64-bit); also same with Chrome
- Operating System: Windows 10 Home (x64) version 1909, OS build 18363.900

**Comment by brownbat** [comment]
Experienced this issue in a conference call while using Firefox. Could hear all participants except for the dial in caller. 

Switching to Chrome resolved the issue.
