### ISSUE TITLE
Safari 11 JS error

### ISSUE THREAD

**Issue by HelloWorldUser123** [jitsi/jitsi-meet#7128]
### Description:

When opening Jitsi in Safari 11 following JS error appears.
![image](https://user-images.githubusercontent.com/63649981/85382958-c02d9000-b53f-11ea-9aad-f18483ad9e51.png)

### Client information:

- Browser / app version: Safari 11

**Comment by HelloWorldUser123** [comment]
@jallamsetty1 might be interesting for  you

**Comment by jallamsetty1** [comment]
We don't support Safari 11, I am surprised you are able to run the client in the browser. Will you be able to provide the console log ?

**Comment by HelloWorldUser123** [comment]
sorry for the late answer - if safari 11 not supported I will close it
