### ISSUE TITLE
Audio track muted status from PARTICIPANT_UPDATED event always one behind

### ISSUE THREAD

**Issue by fritzfr** [jitsi/jitsi-meet#7131]
### Description:

I am trying to intercept the `PARTICIPANT_UPDATED` event and check, whether a participant muted/unmuted himself.

I am logging the tracks from `action.participant.conference.participants[participantId]._tracks`,
which is an array of 1 video and 1 audio track, each with a `muted` boolean property. When I mute/unmute a participant, the boolean seems to be the other way around (true when unmuted, false when muted).

### Steps to reproduce:

Log `participant.conference.participants[participantId]._tracks` in https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/participants/actions.js#L373.

### Expected behavior:

The muted property should be true when muted, false when muted.

### Actual behavior:

The boolean is always the other way around.

Is there a simpler way of fetching the audio muted status from a participant object?

**Comment by saghul** [comment]
Unfortunately it's a bit more complex than that. You'll want to listen to `TRACK_UPDATED`, then there get the `jitsiTrack` that is passed and check is `!isLocal()` and then you can call `getParticipantId()` on it.

**Comment by fritzfr** [comment]
@saghul Thank you so much, I found it. Great help!
