### ISSUE TITLE
Expose mute & raise hand via SDK

### ISSUE THREAD

**Issue by fritzfr** [jitsi/jitsi-meet#7133]
**Is your feature request related to a problem you are facing?**
Yes, I am trying to build my own mobile frontend using the mobile SDKs.

**Describe the solution you'd like**
I would like to programmatically mute and raise/lower hand for the user. The only 2 methods which seem to be exposed from the mobile SDKs are `join` and `leave`. I would like 2 more methods to be exposed, one for toggling mute and one for toggling the raise hand.
I have little to no experience in Objective-C/Java, which is why I need some guidance on how and where this could be implemented.

**Comment by fritzfr** [comment]
I made some progress. The general idea seems to be (iOS for now):

- A new file ("EventManager.m") and a corresponding header file in the SDK.
- A method for each toggling raise-hand and mute there, which sends react native events:
```objective-c
- (void)toggleRaiseHand;
    {
        [self sendEventWithName:@"handRaiseToggled" body:@{@"eventName": @"handRaiseToggled"}];
    }
```
- Listen for this native event in the relevant file, e.g RaiseHandButton.js:
```js
        import { NativeModules, NativeEventEmitter } from 'react-native';
        const EventManagerEmitter = new NativeEventEmitter(NativeModules.EventManager);
        let subscription;
        // ...
	componentDidMount() {
	    subscription = customEventManagerEmitter.addListener(
			'handRaiseToggled',
			this._toggleRaisedHand
	    );
	}

	componentWillUnmount() {
	    subscription.remove();
	}
```

The event does trigger, though I'm getting:
> [JitsiMeetSDK] Sending `handRaiseToggled` with no listeners registered.

**Comment by albert0m** [comment]
Hi @fritzfr , did you manage to send commands like video/audio mute and unmute?
