### ISSUE TITLE
Jitsi Unstable - apt update-error with jitsi-meet-web-config (1.0.4217-1)

### ISSUE THREAD

**Issue by nextgen-networks** [jitsi/jitsi-meet#7136]
## Description: 

latest unstable update could not be finishes because of syntax error:
/var/lib/dpkg/info/jitsi-meet-web-config.postinst: line 231: syntax error near unexpected token `;;'

### Steps to reproduce:

Command:  
apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt autoclean && apt autoremove -y                        
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease
Hit:3 https://packages.grafana.com/oss/deb stable InRelease
Hit:4 https://repos.influxdata.com/debian bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 https://download.jitsi.org unstable/ InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  jitsi-meet-turnserver
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 0 B/6204 B of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
Setting up jitsi-meet-web-config (1.0.4217-1) ...
/var/lib/dpkg/info/jitsi-meet-web-config.postinst: line 231: syntax error near unexpected token `;;'
dpkg: error processing package jitsi-meet-web-config (--configure):
 installed jitsi-meet-web-config package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 jitsi-meet-web-config
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Expected behavior:

update via apt succeeds

### Actual behavior:

update via apt fails with error message mentioned above

### Server information:

- Jitsi Meet version: 2.0.4763-1
- Operating System: latest Ubuntu 18.04. LTS

### Client information:

kitty ;-)

### Additional information:
tried to update from jitsi-meet 2.0.4758-1 to 2.0.4763-1

**Comment by saghul** [comment]
Should be fixed by https://github.com/jitsi/jitsi-meet/pull/7137

**Comment by nextgen-networks** [comment]
check! install succeeded with #7137 
Thanks for the rapid fix and for Jitsi itself!

**Comment by saghul** [comment]
Thanks for the report!
