### ISSUE TITLE
Non-ASCII characters in URL cause poor performance

### ISSUE THREAD

**Issue by evilrhinohater** [jitsi/jitsi-meet#7138]
### Description:

Using a large number of emojis in a room name/URL causes Jitsi Meet to become unusable

### Steps to reproduce:

Choose a room name with many emojis, e.g.
https://meet.jit.si/%F0%9F%94%8C%F0%9F%92%A4%F0%9F%90%AC%F0%9F%92%84%F0%9F%87%B1%F0%9F%87%BA%F0%9F%9A%94%F0%9F%87%B8%F0%9F%87%B2%F0%9F%87%BB%F0%9F%87%AE%F0%9F%87%B0%F0%9F%87%B7%F0%9F%95%B3%F0%9F%96%8D%F0%9F%93%8D%F0%9F%92%87%E2%80%8D%E2%99%82%EF%B8%8F%F0%9F%A5%B0%F0%9F%9A%82%F0%9F%95%89%F0%9F%87%AD%F0%9F%87%B2%F0%9F%8F%9C%F0%9F%A4%AD%F0%9F%92%9F%F0%9F%A4%B9%E2%80%8D%E2%99%80%EF%B8%8F%F0%9F%87%A7%F0%9F%87%AD%F0%9F%87%B5%F0%9F%87%B7%F0%9F%9B%83

Please note that using fewer emojis is no problem, e.g.
https://meet.jit.si/%F0%9F%94%8C%F0%9F%92%A4%F0%9F%90%AC

### Expected behavior:

The meeting should be as responsive as usual.

### Actual behavior:

The meeting loads very slowly and the performance overall is poor.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Jitsi Meet instance hosted on jit.si
- Operating System: Linux

### Additional information:

Occurred for all participants of a scheduled meeting across platforms and browsers.

**Comment by lvarnava** [comment]
The same problem if you give long room names in Cyrillic.
For my users this is a serious problem. On the one hand, you write that simple room names are not safe, and on the other hand, long room names create problems such as monstrous braking, even in Latin.

Examples:

https://meet.jit.si/%D1%81%D1%8A%D0%B5%D1%88%D1%8C%D0%B5%D1%89%D1%91%D1%8D%D1%82%D0%B8%D1%85%D0%BC%D1%8F%D0%B3%D0%BA%D0%B8%D1%85%D1%84%D1%80%D0%B0%D0%BD%D1%86%D1%83%D0%B7%D1%81%D0%BA%D0%B8%D1%85%D0%B1%D1%83%D0%BB%D0%BE%D0%BA%D0%B4%D0%B0%D0%B2%D1%8B%D0%BF%D0%B5%D0%B9%D1%87%D0%B0%D1%8E

https://meet.jit.si/fdasdhfaishdgdhsgiohdsighvisahgdi75t87t897ew8rghjsdfkhgbjkdfcxvkb.re9te87wg9erw8tg9w8retg9-9wregfjkdfcvjkxlcjcjkhvxvh8er8wr98erwkjhgjkvhxcjkvbh

**Comment by RoyalZefa** [comment]
Same problem for us. It is impossible to use jitsi with cyrillic char especially as moodle plugin creates big names(even short works poor)

**Comment by artemws** [comment]
Same problem. No one can fix it?

**Comment by saghul** [comment]
This issue is really old, not sure if the problem still exists.

How does it manifest for you?

**Comment by artemws** [comment]
> This issue is really old, not sure if the problem still exists.
> 
> How does it manifest for you?

Problem still exist. If create room with cyrillic name. and then share this url, i get this

%D1%81%D1%8A%D0%B5%D1%88%D1%8C%D0%B5%D1%89%D1%91%D1%8D%D1%82%D0%B8%D1%85%D0%BC%D1%8F%D0%B3%D0%BA%D0%B8%D1%85%D1%84%D1%80%D0%B0%D0%BD%D1%86%D1%83%D0%B7%D1%81%D0%BA%D0%B8%D1%85%D0%B1%D1%83%D0%BB%D0%BE%D0%BA%D0%B4%D0%B0%D0%B2%D1%8B%D0%BF%D0%B5%D0%B9%D1%87%D0%B0%D1%8E

**Comment by saghul** [comment]
And what's the actual problem of getting that?

**Comment by artemws** [comment]
> And what's the actual problem of getting that?

What do you mean? Problem is - url it's not decoded, when i try to copy this url. Try do decode this text https://meyerweb.com/eric/tools/dencoder/ 

Conference room has get name съешьещёэтихмягкихфранцузскихбулокдавыпейчаю, but i get this %D1%81%D1%8A%D0%B5%D1%88%D1%8C%D0%B5%D1%89%D1%91%D1%8D%D1%82%D0%B8%D1%85%D0%BC%D1%8F%D0%B3%D0%BA%D0%B8%D1%85%D1%84%D1%80%D0%B0%D0%BD%D1%86%D1%83%D0%B7%D1%81%D0%BA%D0%B8%D1%85%D0%B1%D1%83%D0%BB%D0%BE%D0%BA%D0%B4%D0%B0%D0%B2%D1%8B%D0%BF%D0%B5%D0%B9%D1%87%D0%B0%D1%8E

**Comment by artemws** [comment]
> > And what's the actual problem of getting that?
> 
> What do you mean? Problem is - url it's not decoded, when i try to copy this url. Try do decode this text https://meyerweb.com/eric/tools/dencoder/
> 
> Conference room has get name съешьещёэтихмягкихфранцузскихбулокдавыпейчаю, but i get this %D1%81%D1%8A%D0%B5%D1%88%D1%8C%D0%B5%D1%89%D1%91%D1%8D%D1%82%D0%B8%D1%85%D0%BC%D1%8F%D0%B3%D0%BA%D0%B8%D1%85%D1%84%D1%80%D0%B0%D0%BD%D1%86%D1%83%D0%B7%D1%81%D0%BA%D0%B8%D1%85%D0%B1%D1%83%D0%BB%D0%BE%D0%BA%D0%B4%D0%B0%D0%B2%D1%8B%D0%BF%D0%B5%D0%B9%D1%87%D0%B0%D1%8E

In address bar all ok, but when i click copy to clipboard, url not decoded 

![изображение_2024-02-06_143533944](https://github.com/jitsi/jitsi-meet/assets/59208085/dc8f915f-d0b3-4f3b-a7dc-20002ceedc21)
