### ISSUE TITLE
use iceserver

### ISSUE THREAD

**Issue by liu1083947028** [jitsi/jitsi-meet#714]
How can i config iceserver in jitsi-meet?

![image](https://cloud.githubusercontent.com/assets/7359403/16554941/a2a40288-4204-11e6-8cd9-9e6bffc96012.png)

I set {"url": "stun:stun.l.google.com:19302"} in strophe.jingle.js, but it does not work. How can i do it?

thanks

**Comment by damencho** [comment]
Please, could you ask quesitons on the dev list before opening issues?

If you are using jitsi-videobridge you do not need such a config.

**Comment by liu1083947028** [comment]
@damencho  My intention is to point the time without going through the server (videobridge) to communicate. 

How can i set it?

**Comment by damencho** [comment]
I'm not sure what 'time' means in this context. But if you are not going to use the videobridge, there is no point of using jicofo and jitsi-meet at all.

**Comment by liu1083947028** [comment]
@damencho 
I am trying videobridge and perfer to P to P connection. 

How can i set it in videobridge?

Thanks

**Comment by damencho** [comment]
Jitsi-videobridge is always relaying the media, this is the whole idea.
There is no p2p mode. With multiple people in conference in p2p mode you
will end up with up to 3 participants and if you have very good internet
you can make it with 4. But if you are using the videobridge you can have a
conference with 15-20 people.

**Comment by liu1083947028** [comment]
Thank you Damencho, I do like Videobridge to host meeting starting from 3 parties. However, I do many those P2P video chatting's media go straight(without going through server) to save Videobridge server side bandwidth.
