### ISSUE TITLE
Isn't there a security vulnerability with chrome-dependent software?

### ISSUE THREAD

**Issue by gloschtla** [jitsi/jitsi-meet#7140]
I am disappointed that Jitsi Meet doesn't work well in Firefox. This urges its users to install [Chrome browser](https://t.me/NoGoolag/2488), which might leak all your video conferences directly to Maryland.

**Comment by saghul** [comment]
> I am disappointed that Jitsi Meet doesn't work well in Firefox.

What doesn't? We have made tons of improvements to our Firefox support in the last couple of months to the point where they should provide a comparable experience. Anything that doesn't work properly is treated as a bug and fixed. Do you have a specific bug to report? (there are still some Firefox bugs that prevent us from providing some things like multiple input device selection, but there is nothing we can do about that).

> This urges its users to install [Chrome browser](https://t.me/NoGoolag/2488), which might leak all your video conferences directly to Maryland.

Unless you can provide evidence of that (you won't) it's just FUD, which is not welcome here.
