### ISSUE TITLE
Screen sharing frame not removed from Safari

### ISSUE THREAD

**Issue by shool70045** [jitsi/jitsi-meet#7147]
### Steps to reproduce:
1. Start meeting from chrome. 
2. join meeting from safari and turn off video
3. Share screen from chrome.
4. You should see the shared screen in safari now
5. Stop screen share from chrome.
6. Notice the safari still has the last frame of the screen share available.

### Expected behavior:
The last frame of the screen share should be removed automatically.

### Server information:

- Jitsi Meet version: Tried on meet.jit.si
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by jallamsetty1** [comment]
Thanks for the report, will be looking into it.

**Comment by HelloWorldUser123** [comment]
same on our side

**Comment by razor0001** [comment]
Hi,
I created a seperate issue (seems to be duplicated) https://github.com/jitsi/jitsi-meet/issues/7608 . Is there any update on this issue - it seems to be a critical one because it appears on every iphone. In the linked issue I added some additional logs

Thanks
