### ISSUE TITLE
Forbid screen sharing for guests

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7150]
**Is your feature request related to a problem you are facing?**
Shreen sharing should enabled only fors hosts not for guests.
In may meetings the host presents its screen (e.g. PowerPoint) for the guests and the guests should only view and ask questions but not show their own screen.

**Describe the solution you'd like**
Implement an Option for hosts to allow/deny screen sharing for guests.

**Comment by franken300** [comment]
still relevant! Would be a great feature to control a meeting as a moderator

**Comment by saghul** [comment]
We have no plans to make this possible, sorry.
