### ISSUE TITLE
Allow creating persistent MUCs

### ISSUE THREAD

**Issue by mdosch** [jitsi/jitsi-meet#7158]
Friends and me have a recurring event where we meet in jitsi-meet. We always use the same conference name and password. Now we have to create the conference everytime and set the password again. Also this bears the risk to forget to set the password again.

I'd like to have the option to make the conference (MUC) persistent so that this particular conference and it's password won't be deleted after all participants left.

**Comment by damencho** [comment]
This needs to be handled serverside with some custom prosody module suitable for your deployment for setting the password.
A PR with your custom module (if it can be reused by others) is welcome.

Please use the community forum for questions and problems before opening new issues. This had been discussed in the forum and there are people using some custom solutions for that ...

**Comment by weiss** [comment]
> This needs to be handled serverside with some custom prosody module

I would've thought making the room (and thereby the password) persistent would just require setting the [muc#roomconfig_persistentroom][1] flag as per XEP-0045?

But I can imagine it's less trivial to cope with the problem that room ownership is lost if the owner was using anonymous login.

[1]: https://xmpp.org/extensions/xep-0045.html#createroom-reserved
