### ISSUE TITLE
Shared youtube video playing speed is not synchronized properly

### ISSUE THREAD

**Issue by gbirke** [jitsi/jitsi-meet#7159]
### Description:

When sharing a YouTube video, the playback speed is only changed for one of the viewers

### Steps to reproduce:

1. In a Jitsi meeting, go to "Share Youtube video" and add a video
2. In the video controls, set playback speed to 1.5 or 1.25

### Expected behavior:

The video plays back in 1.25 or 1.5 speed for all participants

### Actual behavior:

All participants except the one who set the playback speed see the video in 1.0 speed, skipping every few seconds.

### Server information:

N/A
### Client information:

- Browser / app version: Google Chrome 83.0
- Operating System: Mac OS X 10.14

### Additional information:

Only one presenter had access to teh video controls, the others just saw the video. Playback had to be stopped and re-started for every new participant.

**Comment by damencho** [comment]
Yep, this is not detected from current code and will not work as expected. PRs are welcome.
