### ISSUE TITLE
Cannot dispose of JitsiMeetExternalAPI object

### ISSUE THREAD

**Issue by paulvt** [jitsi/jitsi-meet#716]
I cannot properly hang up a conference, because `dispose()` on `JitsiMeetExternalAPI` calls `this.postis.dispose()` which doesn't seem to exist:

```
Uncaught TypeError: this.postis.dispose is not a function
  JitsiMeetExternalAPI.dispose @ external_api.js:351
  hangup @ call.js:55
  dispatch @ jquery.js:4670
  r.handle @ jquery.js:4338
```

**Comment by damencho** [comment]
Fixed https://github.com/jitsi/jitsi-meet/commit/e46d45adead96ce5af45d5ab5f305f9b39e6c414
