### ISSUE TITLE
Clarify which Chrome extension this setting is referring to

### ISSUE THREAD

**Issue by dandv** [jitsi/jitsi-meet#7163]
I'm new to Jitsi and technical enough to have figured out [the config file](https://github.com/jitsi/handbook/issues/61#issuecomment-649862661) in which I could change some UI settings. Yet this one is unclear:

```
/**
    * Decides whether the chrome extension banner should be rendered on the landing page and during the meeting.
    * If this is set to false, the banner will not be rendered at all. If set to true, the check for extension(s)
    * being already installed is done before rendering.
    */
    SHOW_CHROME_EXTENSION_BANNER: false,
```

What extension is that?

**Comment by jhiswin** [comment]
It's this one: 
![image](https://user-images.githubusercontent.com/120998/85904359-832efb00-b7d6-11ea-86a0-3987bd9f10c7.png)

Doesn't really need clarifying, since it's the only one.

**Comment by dandv** [comment]
> Doesn't really need clarifying, since it's the only one.

Interesting, what made you think I knew there was any extension at all?

**Comment by jhiswin** [comment]
Not to tell you what you should or shouldn't know, but it says "Chrome Extension".  There's only the one Jitsi Chrome Extension.  I (personally) don't really see any reason they need to clarify this.  Maybe if this were a paid product with paid support, where they need to provide you guided support and accountability to your average IT support staff or simple user.

**Comment by dandv** [comment]
I'm not sure you we have the same understanding of how open source works.

Rather than arguing what "they" should do, I've chosen to [contribute](https://github.com/jitsi/jitsi-meet/pull/7172) instead. Feel free to disagree on that PR, or further contribute, such as by,

1. Explaining why the setting is still relevant for self-hosted installs, given that [the extension](https://chrome.google.com/webstore/detail/jitsi-meetings/kglhbbefdnlheedjiejgomgmfplipfeb) clearly states

    > This extension provides calendar integrations to schedule meetings **for meet.jit.si[sic] site**.

2. Explaining why the comment for that setting refers to a plural: "the check for extension<b>(s)</b> being already installed..."

**Comment by jhiswin** [comment]
You are already "arguing" what "they" should do, in the code no less.   For details that aren't necessary to distinguish what it does.
And with a strange amount of indignation, in response to a simple picture pointing out where it is and pointing out that it is not really a problem, because there is only one extension and one UI element it could be in reference to.  

It's great that you are contributing.  All the more power to you.  But I'm still saying I don't see anything to add here.  
Maybe detailed documentation on the configuration wiki that references interfaceConfigOverwrite on the GitHub page.

It's not really normal to see detailed configuration documentation in the code.  So I would say it's still the wrong place to put it.

**Comment by damencho** [comment]
> 2\. Explaining why the comment for that setting refers to a plural: "the check for extension(s) being already installed..."
> 
> >

https://github.com/jitsi/jitsi-meet/blob/master/config.js#L419

There can be multiple extensions to check, there are deployments using several extensions and that checks all listed in the config.

**Comment by jhiswin** [comment]
Handbook Docs are a little bit lacking.  Which is probably where these things should go:  
https://github.com/jitsi/handbook

I think that's the right place for the full Jitsi docs including the self-hosting instructions?  
Someone good at writing docs could (should) make some updates over there.

**Comment by dandv** [comment]
> I think that's the right place for the full Jitsi docs including the self-hosting instructions?

Agree, but on the other hand, https://github.com/jitsi/jitsi-meet/blob/master/config.js is thoroughly commented inline, probably for good reasons. Do those apply to `interface_config.js`?

**Comment by saghul** [comment]
Here is where the config for that banner is taken from: https://github.com/jitsi/jitsi-meet/blob/b4ecef429ada7181c1ac3f530c49ba43da2f6e1c/config.js#L419

I agree that for those who have been around the block for a while this might be confusing, as an extension was needed in the past for screen-sharing. This hasn't been the case for a long time now though.

**Comment by saghul** [comment]
Superseded by https://github.com/jitsi/jitsi-meet/pull/7172
