### ISSUE TITLE
Add an "issue" type "Testimonial"

### ISSUE THREAD

**Issue by yarikoptic** [jitsi/jitsi-meet#7164]
**I just wanted to express my gratitude to every single contributor of Jitsi and http://meet.jit.si deployment: outstanding work and generosity**, but I did not know where/how to do so.  This repository and an issue is the logical entry point for some, but "New Issue" offered only filing complaints, so here is a complaint: I want to praise you all but can't! ;-)

**Comment by Echolon** [comment]
@yarikoptic Thank you for the praises!

Maybe Github is not the right place for this. I suggest to go to the community website!

But the developers really appreciate that!

I will close this issue with reference to the community forum.

@saghul @damencho
