### ISSUE TITLE
Set maximum partcipant for each room dynamically

### ISSUE THREAD

**Issue by nimaam** [jitsi/jitsi-meet#7166]
Dear All
I read the issues and community, and see there is a plugin for prosody which can set maximum participant but globally for all rooms, but what I need is different, I need to set maximum participant for each event or meeting with different value, for this is it possible to change the plugin to get this from prosody rest or from jicofo or from api.
I need to know of there is not a way like I said above, is it possible to have different muc with different maximum_participant setting and each event pass to the one that is ok?

**Comment by Echolon** [comment]
@nimaam can you fill out the issue template please?

**Comment by nimaam** [comment]
Is it possible to use multi tenant and for each tenant set the parameters???

**Comment by Echolon** [comment]
@nimaam I'm afraid but I have to close the issue as long as you havent filled out the issue template. 
If you need support please visit rhe Jitisi Community Forum aswell!

_______
Bugmarshall, not directly affiliated with the Jitsi Meet Team
