### ISSUE TITLE
Full screen button not showing in browser toolbar despite listed in TOOLBAR_BUTTONS

### ISSUE THREAD

**Issue by dandv** [jitsi/jitsi-meet#7170]
### Description:

By default, TOOLBAR_BUTTONS in [`interface_config.js`](https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js) includes `'fullscreen'`. Does this mean that a "Full screen" button should show up in the toolbar at the bottom? It does not:

![image](https://user-images.githubusercontent.com/33569/85900184-363a2d00-b7b4-11ea-9034-fc2d7f858e7b.png)

### Steps to reproduce:

1. Edit `/usr/share/jitsi-meet/interface_config.js`
2. Ensure `'fullscreen'` is included in the TOOLBAR_BUTTONS array
3. Start a meeting

### Server information:

- Jitsi Meet version: 2.0.4627-1
- Operating System: Ubuntu 20.04

### Client information:

Doesn't seem to be browser-specific. Reproduced in Firefox on Mac OS, Chrome on Ubuntu 20.

**Comment by saghul** [comment]
Don't you see it in the overflow menu? The one displayed when you press the 3 dots button.

I know it's not very intuitive from the configuration perspective, but not all buttons go on the toolbar directly, they are put in the overflow menu.

**Comment by dandv** [comment]
I do see it there, so the property name is misleading. It should be "AVAILABLE_BUTTONS" or something. Also,
- what does `sharedvideo` do? I thought it controlled Share your screen, but nope.
- how can buttons be moved out of the way into the <kbd>More actions</kbd> menu? The use case is that I want to make it easy for users to switch to full-screen. The <kbd>S</kbd> shortcut is nice, but not as easily discoverable. I also don't want them to click the Share your screen button, which looks like a "go to full screen" button. So I want to move Full screen to the (real) toolbar, out of More actions, and move the Share your screen into More actions.

In the meantime, see PR #7171.

**Comment by saghul** [comment]
> so the property name is misleading. It should be "AVAILABLE_BUTTONS" or something.

I don't disagree, but the breakage would be substantial, for no big gain IMHO. We can probably clarify the comment above the option to make it clear not everything will be immediately visible in the toolbar.



>     * what does `sharedvideo` do?

It's the "share YouTube video" feature, where all participants will watch a youtube video in a synchronized way



>     * how can buttons be moved out of the way into the More actions menu?

You cannot control it. It's based on the available viewport width.

**Comment by byungjuJin** [comment]
for someone who want to move fullscreen button to the toolbar,

you can do this.
follew custom build from local : https://community.jitsi.org/t/how-to-how-to-build-jitsi-meet-from-source-a-developers-guide/75422

and fix "Toolbox.js" file.  
remove from "_renderOverflowMenuContent()"
add to "_renderToolboxContent()"
and others about  "fullScreen"
