### ISSUE TITLE
Missing map file for the external API on self-hosted package?

### ISSUE THREAD

**Issue by dandv** [jitsi/jitsi-meet#7173]
### Description:

After intsalling `jitst-meet` on Ubuntu, `/external_api.js` is served fine, but the corresponding map file appears to be missing.

### Steps to reproduce:

1. Install Jitsi Meet on Ubuntu 20.04 following the [Quickstart guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) instructions
2. Fetch `/external_api.js` from the host and ensure it's a JavaScript file
3. Fetch `/external_api.min.map`

### Expected behavior:

The map file should download, as it does when accessed from http://meet.jit.si/external_api.min.map

### Actual behavior:

The request for `/external_api.min.map` redirects to `/`.

### Server information:

- Jitsi Meet version: 2.0.4627-1
- Operating System: Ubuntu 20.04

### Additional information

The [IFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe) documentation had always suggested loading the API from meet.jit.si, until I [submitted a PR 4 days ago](https://github.com/jitsi/handbook/pull/55/files#diff-317c2aab5c2ab43ab7de27970ed3c426R12-R14) to suggest loading it from the host itself. Maybe that was not a good idea? CC @saghul

**Comment by mgalalsalem** [comment]
any quick way to fix this problem on the already installed version
