### ISSUE TITLE
Custom domain issue 

### ISSUE THREAD

**Issue by shubhamvishwakarma19** [jitsi/jitsi-meet#7174]
![Screenshot_20200627-145059](https://user-images.githubusercontent.com/50484716/85919064-c5fbdc00-b885-11ea-82d8-62bdc8173f3d.jpg)

<img width="676" alt="Screenshot 2020-06-24 at 5 52 05 PM-1" src="https://user-images.githubusercontent.com/50484716/85919011-5dacfa80-b885-11ea-9a58-164fa9193a96.png">

Here is my code 

var domain = "meet.example.com";
            var options = {
                roomName: "JitsiMeetAPIExample",
                width: 700,
                height: 180,
                parentNode: undefined,
                configOverwrite: {},
                interfaceConfigOverwrite: {
                    filmStripOnly: true
                }
            }
            var api = new JitsiMeetExternalAPI(domain, options);

I'm getting this error in my project when i'm using jitsi domain it's working fine. problem i'm facing when i change the our domain name like meet.example.com .Can you please help how can i implement  in my react project
      

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

This should be a config issue of your server and has nothing to do with Jitsi as far as i understood this. In case it's not, refer to the forums.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
