### ISSUE TITLE
jitsisampleapp/jitsi-meet-sdk-samples-master/ios/swift/JitsiSDKTest/Pods/Target Support Files/Pods-example-pip-app/Pods-example-pip-app.debug.xcconfig: unable to open file (in target "App" in project "JitsiSDKTest")

### ISSUE THREAD

**Issue by maneesh12345** [jitsi/jitsi-meet#7182]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by Echolon** [comment]
@maneesh12345 I'm sorry, but for organisational and quality reasons I will close this issue as long as you don't provide a proper title + decent description of the issue. Once provided, I can reopen the isse.
