### ISSUE TITLE
Provide the flag to disable the Help option

### ISSUE THREAD

**Issue by mehul4795** [jitsi/jitsi-meet#7183]
**Is your feature request related to a problem you are facing?**
I am using the Jitsi Android SDK (Version 2.9.0) and can see that during the meeting an extra **Help** option has appeared which wasn't present previously. 

![Screenshot_20200628-173458](https://user-images.githubusercontent.com/13131390/85947153-9bce1b00-b966-11ea-9a57-583054e1d3be.jpg)

**Describe the solution you'd like**
The SDK already provides feature flags to enable/disable other options. It would be helpful if the feature flag to disable the Help option can be added. 

**Describe alternatives you've considered**
If the feature flag to disable the Help option isn't feasible, an option to change the default Jitsi URL can also work.

**Comment by MaheshPeri19** [comment]
Exactly i need the same feature. Please provide flag to disable/hide help option. Because it is opening jitsi help url.

**Comment by MaheshPeri19** [comment]
Any workaround for this issue as i needed this feature to disable help option in my app.

**Comment by saghul** [comment]
We are quite busy, sorry. A pull request would be most welcome though.

**Comment by e1engineer** [comment]
I'm willing to make a donation (where to?) for this as well.

We are using this for our apps, and it's confusing to users.

**Comment by saghul** [comment]
We don't take donations, sorry.

If you look at almost ahh other button you can see how they are using a feature flag to enable them or not.

**Comment by mehul4795** [comment]
In the latest version of Jitsi, you can now disable the **Help** option that is shown in the bottom sheet using the `help.enabled` feature flag. 

```kotlin
        val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setServerURL("YOUR_SERVER_URL")
            .setFeatureFlag("help.enabled", false)
            .build()

        JitsiMeet.setDefaultConferenceOptions(defaultOptions)
```

**Comment by e1engineer** [comment]
Thank you.

**Comment by saghul** [comment]
I forgot we already have it now lol

**Comment by AmitMamoria** [comment]
Still i can't disable help option from room 
![image](https://user-images.githubusercontent.com/8125539/118517994-59b3f080-b755-11eb-81ce-5139ffb83f43.png)

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by Nipa227** [comment]
Hi I am still facing this problem how to hide help option

**Comment by Nipa227** [comment]
> Thank you.

What SDK you are using

**Comment by faysal-cse** [comment]
I am trying to hide Security option by using this 

builder.setFeatureFlag("security-options.enabled", withBoolean: false)

but its not working. Currently trying with 4.1.0.
On iOS trying this  `pod 'JitsiMeetSDK'`
and on Android 
`    implementation ('org.jitsi.react:jitsi-meet-sdk:4.1.0') { transitive = true }`

What can I do to hide the security option from meet screen?

**Comment by faysal-cse** [comment]
> https://github.com/jitsi/jitsi-meet/blob/8bf42e79a0e58eeea28fcec12fed73502584ae24/react/features/security/components/security-dialog/AbstractSecurityDialogButton.js#L95
> 
> You need to disable the lobby and password sections too. I'd consider that a bug though, we should hide it just with the dedicated flag...

Its working well. Thank you.

**Comment by saghul** [comment]
I have a fix in https://github.com/jitsi/jitsi-meet/pull/11370 FTR.
