### ISSUE TITLE
Turn off audio channel for deaf users

### ISSUE THREAD

**Issue by Ryuno-Ki** [jitsi/jitsi-meet#7187]
**Is your feature request related to a problem you are facing?**

Hey there,
I have friends and families who are part of the deaf / hard-of-hearing community.
For them, it is important to be able to use a service which allows them to communicate via sign language.

So far we tried solutions like Zoom or Skype.
Jitsi beats them but is not as good as ooVoo, which [shut down a few years ago](https://twitter.com/ooVoo/status/934578316966809600).

**Describe the solution you'd like**
Since the deaf community relies on signs and mimic for their language, I'd like to be able to turn off audio channels to increase the throughput for video.

**Describe alternatives you've considered**
We figured out, that meet.jit.si works okay if you sign slowly.

#6425 is related to this issue.

**Comment by saghul** [comment]
There is currently an option to disable all audio but it can only be set using a URL parameter. Add #config.startSilent=true to the end of your meeting URL before joining and give it a try.

**Comment by Ryuno-Ki** [comment]
Hi @saghul,

thanks. We'll try that and report back.
I looked into the code and found some more config options.
Are they documented somewhere?

I mean, https://jitsi.github.io/handbook/docs/user-guide/user-guide-advanced is … sparse.

**Comment by saghul** [comment]
No, alas we don't currently have a proper list of supported configuration options other than: https://github.com/jitsi/jitsi-meet/blob/master/config.js

**Comment by Ryuno-Ki** [comment]
I'm still waiting for feedback with my family.

In the meantime: Would you accept PRs for documentation?

**Comment by saghul** [comment]
Absolutely! Getting the list started in the handbook would be great!

**Comment by Ryuno-Ki** [comment]
Okay, I've cloned the repo, installed the dependencies and got a local handbook running.
Will look into adding some information.
Is an issue (for reference) needed in the handbook repo?

**Comment by Ryuno-Ki** [comment]
Okay, let's try without one.

**Comment by Ryuno-Ki** [comment]
We switched to Threema by now. This issue can be closed.
