### ISSUE TITLE
Failed to load module 'Jitsi-meet' in xcode 11.3

### ISSUE THREAD

**Issue by maneesh12345** [jitsi/jitsi-meet#7188]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by Echolon** [comment]
@maneesh12345 
Due to quality reasons I am going to close this issue until you have provided more specific and detailed information. Please filloit the issue template. Once done, I can reopen, please mention me.
