### ISSUE TITLE
Changing network config on client causes overall disconnect in conference

### ISSUE THREAD

**Issue by dieug** [jitsi/jitsi-meet#7191]
### Description:

Some users had turn vpn (cisco vpn usually) on or off while using jitsi.
It causes total or individual disconnect from conference.
It happens with audio\video on and off with most users. No matter.
It sometimes causes disconnets to another conference on server.
In small confrerence (2-4 users) going off user, which took off vpn.
In bigger conference (12+ users) all users disconnects with audio/video artefacts, if mic or camera was on.
Total disconnect from conference strongly confirmed on MacOs and Cisco VPN.
With Linux and OpenVPN disconnects client, which had changed vpn (usually).
With Windows and Cisco VPN confirmes rarely.
With Android and OpenConnect and OpenVPN couses individual discocnnect.
(statistically)

### Steps to reproduce:

1. Install Jitsi from debian packages with official instruction (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart).
2. Invite 12+ users in one conference.
3. Reconnect some VPN services on clients.

### Expected behavior:

Changing network status on client causes nothing or causes individual disconnect.

### Actual behavior:

Changing status vpn on client causes total or individual disconnet clients from Jitsi.

### Server information:

Server:
VPS
8 cores Intel Xeon Processor (Skylake, IBRS) 2100 MGz
16GB Ram
White (direct) ip address in internet. No NAT.
500Mb/s internet link

OS:
Debian 10.4 64bit

JItsi:
Versions Was/Is installed:
jicofo 1.0-549-1
jitsi-meet 2.0.4468-1
jitsi-meet-prosody 1.0.4025-1
jitsi-meet-web 1.0.4025-1
jitsi-meet-web-config 1.0.4025-1
jitsi-videobridge2 2.1-183-gdbddd169-1

jicofo 1.0-589-1
jitsi-meet 2.0.4627-1
jitsi-meet-prosody 1.0.4127-1
jitsi-meet-web 1.0.4127-1
jitsi-meet-web-config 1.0.4127-1
jitsi-videobridge2 2.1-202-g5f9377b9-1

Confirmed on both.

### Client information:

Browser: Firefox > 76, Chrome > 82
Not depends.

### Additional information:

While clients gets disconnect, i see load 100% irq on one core in monitor.

**Comment by dieug** [comment]
attaching some config and logs from browser and jitsi on last disconnect:
[jitsithings.tar.gz](https://github.com/jitsi/jitsi-meet/files/4845600/jitsithings.tar.gz)

**Comment by saghul** [comment]
Seeing the individual participant which changed their network disconnect is somewhat acceptable, but causing disruption for other participants not really...

**Comment by dieug** [comment]
may be, it'll be helpful someone:
i found, while users gets troubles with audio-video artefacts (and visually bad connection for all participant), jvb jitsi process uses 100% cpu on 1 core, but other cores gets 2-6% load.
in this case, once i did 'systemctl restart jitsi-meet-videobridge2'
and all goes fine.
for users it looks like hotfix without relogin.

**Comment by dieug** [comment]
> may be, it'll be helpful for someone:
> i found, while users gets troubles with audio-video artefacts (and visually bad connection for all participant), jvb jitsi process uses 100% cpu on 1 core, but other cores gets 2-6% load.
> in this case, once i did 'systemctl restart jitsi-meet-videobridge2'
> and all goes fine.
> for users it looks like hotfix without relogin.

it's not clear to users. jitsi writes: something went wrong and user needs to rejoin.

**Comment by dieug** [comment]
after all, i have a question:
is there in jitsi a mechanism to block internal client's ip/subnet?
in example:
i see in jvb.log:
`
2020-11-12 15:22:51.375 INFO: [36] [confId=asda8f7as8f gid=20582 stats_id=Teresa-kNv componentId=1 conf_name=virtualoffice@conference.conf.company.com ufrag=7r9061emu6h49s name=stream-84a17f72 epId=84a17f72 local_ufrag=7r9061emu6h49s] Component.updateRemoteCandidates#481: new Pair added: 89.xxx.xxx.xxx:10000/udp/host -> 10.254.1.161:59686/udp/host (stream-84a17f72.RTP).
`
it's an internal vpn address.
can i block this subnet from jitsi server? '
in jvb config or something else ?

**Comment by Keisial** [comment]
@dieug you can simply block them at webserver or firewall level.
For example, using iptables:
`sudo iptables -I INPUT -s 10.254.1.0/24 -j REJECT --reject-with icmp-host-prohibited`

If you control the vpn, you could also ensure it doesn't allow the clients to reach through it.

**Comment by dieug** [comment]
after some updates and bringing service to another hoster, users doesn't affect by vpn reconnect (in most cases or always).
i think, ticket can be closed.

some latest version:
```
jicofo 1.0-740-1
jitsi-meet 2.0.5765-1
jitsi-meet-prosody 1.0.4900-1
jitsi-meet-web 1.0.4900-1
jitsi-meet-web-config 1.0.4900-1
jitsi-videobridge2 2.1-478-gc6da57bd-1
```
and above does call dissappearing sound with some users (new in conference often).
may be i'll do a new ticket with this question.

i'll try to do multiple videobridges with jitsi.

now one server can't service more then ~75 clients (in my count with established connections to 443 port tcp.)
