### ISSUE TITLE
legacy screen sharing

### ISSUE THREAD

**Issue by omertsur** [jitsi/jitsi-meet#7192]
Good day, 
Because of the Corona Virus pandemic my organization is trying to minimize physical interactions in the work environment as much as possible, so I am trying to implement jitsi in my organization.
I am implementing it in the form of docker images running in Openshift, I managed to patch up a template for compatibility sake and could get jitsi to run and serve meetings (including video and audio sharing).
The only feature I am not able to utilize is the screen sharing capability, I keep running into an error in the chrome console about "gum.chrome_extension_user_canceled". 
We are running in a closed network (not connected to the internet) and using chrome version 70.0 because of legacy support (*sigh*) and upgrading is not an option sadly...
I read online about the "jidesha" extension, and tried to use it (cloned from an older commit of the jidesha repository and run the tutorial) but even after installing it on my browser it didn't work and I still get the same error.
I would like to find a find a way to support screen sharing for my organization, either with an extension or by using a workaround in chrome even just for the near-future until we can upgrade our chrome version.
Thank

**Comment by damencho** [comment]
We recently removed support for desktop sharing using the extension: https://github.com/jitsi/lib-jitsi-meet/commit/a7c49516313b321f22f8c07b0a9cb684c5fdd78a
Even if you backport the change in custom lib-jitsi-meet at your side I'm not sure whether you will be able to submit the extension to the chrome webstore as the use of this API had been deprecated for a long time (more than a year and a half). You will need to configure your extension in config.js and install the extension on all browsers that will use your deployment ...

**Comment by dieug** [comment]
sorry for intrusion, i just did walk near and read it.
for users, who can't upgrade browsers and wouldn't use phone app, i found some time ago an desktop app:
https://github.com/jitsi/jitsi-meet-electron
it has modern chromium inside and work quite well usual. and often hasn't need an installation (for linux, an example).

**Comment by Echolon** [comment]
@damencho shall I keep this issue open?

**Comment by damencho** [comment]
Nope.
