### ISSUE TITLE
Jitsi app on iPhone XS: rear camera constantly shakes

### ISSUE THREAD

**Issue by krithin** [jitsi/jitsi-meet#7194]
### Description:

When toggling to the rear camera during a video call on an iPhone XS the camera shakes constantly and the resulting image is very blurry. A couple other people have reported this on reddit: https://old.reddit.com/r/jitsi/comments/fuxuck/ios_toggle_camera_makes_the_camera_freak_out/ (including a video demonstrating the problem).

### Steps to reproduce:

1. join a video call in the Jitsi app on an iPhone XS
2. Click through the menu to toggle to the rear camera

### Expected behavior: 

A clear image from the rear camera should be visible.

### Actual behavior:

The image shakes a lot constantly, and it seems like the camera might be physically shaking too. A video contributed by /u/Sterling44 on Reddit is here: https://streamable.com/hg42fy

### Server information:

- Jitsi Meet version: 1126-1
- Operating System: Ubuntu

### Client information:

- Browser / app version: not sure, recently installed from the Apple App Store
- Operating System: iOS 13.5.1

**Comment by Echolon** [comment]
May you check for the version again in the setting or the App store? That would be helpful! Thank you for reporting.

**Comment by maxired** [comment]
People on reddit are reporting it with iOS 13.4 Jitsi 20.1.0.

On a custom build based on jitsi-meet_4627 I confirm the bug also happens on iPhone XS
