### ISSUE TITLE
Changing disableH264 kills jitsi web-interface

### ISSUE THREAD

**Issue by dieug** [jitsi/jitsi-meet#7195]
### Description:

Changing option H264 for p2p kills main interface.

### Steps to reproduce:

1. Make in /etc/jitsi/meet/example.com-config.js
 ```
     p2p: {
    .............
          disableH264: true,
    .............
     },
 ```
2. Try https://example.com (main jitsi url) without reload any services
3. See gray screen.

### Expected behavior:

Welcome screen works as usual.

### Actual behavior:

Gray screen against Welcome screen.

### Server information:

- Jitsi Meet version:
jicofo 1.0-589-1
jitsi-meet 2.0.4627-1
jitsi-meet-prosody 1.0.4127-1
jitsi-meet-turnserver 1.0.4127-1
jitsi-meet-web 1.0.4127-1
jitsi-meet-web-config 1.0.4127-1
jitsi-videobridge2 2.1-202-g5f9377b9-1

- Operating System:
Debian 10.4 64bit

### Client information:

- Browser / app version:
Not matter
- Operating System:
Not matter

### Additional information:
It looks strange. I would like to know, what's happening.

Screenshot:

![sshot_001233](https://user-images.githubusercontent.com/57111979/86021472-c89b3480-ba31-11ea-9975-2d96cfa6bb47.jpg)

**Comment by saghul** [comment]
Can you check the JS console logs? It might be a syntax error in config.js or something similar.

**Comment by dieug** [comment]
yeah. i'd check a config.
and really there's syntax error with a colons.

thanks a lot.
