### ISSUE TITLE
Need to trigger onConferenceTerminated

### ISSUE THREAD

**Issue by rishsharma9846** [jitsi/jitsi-meet#7202]
Hi Team,

I implemented jitsi sdk by two ways

//
1). JitsiMeetActivity.launch(this, options)
//
2) jitsiMeetView?.join(options)

In I implement with with 1 way then it ll not let me trigger "onConferenceTerminated" as I need this meethod
And If I go with 2 nd way then it does ask for permission "Camera and audio" and it always show video and audio disable(cross) and even if I tried my self to add permission still video and audio disable(cross).

Please check this and suggest me a way ASAP.

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
