### ISSUE TITLE
Locking screen causes a loss of sound

### ISSUE THREAD

**Issue by sebastienaubry** [jitsi/jitsi-meet#7204]
Hello,

I am using the JitSi app 20.2.3 under Android.

When I lock the smartphone screen by pressing the power button, I lose the conversation sound.
I would like the sound to remain active, in order to be able to listen to the meeting. It seems to me that it used to work in the previous versions.

Thanks

**Comment by saghul** [comment]
Can you try this: go to settings -> toggle advanced -> toggle disable native call integration Then try again.

**Comment by sebastienaubry** [comment]
I don't see this setting in the Android app (20.2.3 build 202030). Thanks
