### ISSUE TITLE
Trailing period (.) is separated from URL when posted in chat

### ISSUE THREAD

**Issue by rai42** [jitsi/jitsi-meet#7214]
### Description:

When posting a URL in the chat that ends with a period, the period is separated from the URL and placed on a new line, thereby making the URL incorrect.

Such URLs occur, for example, with Etherpad services such as https://yopad.eu when the pad title ends with a period.

### Steps to reproduce:

1. Start a conference (single user is enough)
2. Open chat
3. paste the following URL into the chat: `https://www.example.org/abc.`
4. Click on the URL in the chat.

### Expected behavior:

step 3: complete URL appears in chat in one piece

step 4: Browser opens the URL `https://www.example.org/abc.`

### Actual behavior:

step 3: URL appears as follows:
```
https://www.example.org/abc
. 
```
Only the first line is the active link.

step 4: Browser opens the URL `https://www.example.org/abc`
(note the missing period).

### Server information:

Tested on server https://meet.ffmuc.net/

- Jitsi Meet version: unknown (how do I find out?)
- Operating System: unknown

### Client information:

- Browser / app version: Chromium Version 81.0.4044.138 or Firefox 77.0.1
- Operating System: Ubuntu Linux 16.04 (64-bit)

**Comment by Echolon** [comment]
@saghul no, to be honest I have no clue how to tag this sufficiently

**Comment by saghul** [comment]
I think UI makes sense.
