### ISSUE TITLE
Android app not configured to accept user certificate trust store

### ISSUE THREAD

**Issue by motiwardi** [jitsi/jitsi-meet#7220]
### Description:

Jitsi Meet server installed on private network, certificates issued by private CA, and root certificate added to remote device trust stores.

Problem:
All desktop/mobile browsers and Jitsi iOS app have valid chain of trust, and application runs fine.
Android app refuses to connect, going into infinite reconnect loop when trying to connect to meeting room.

Root cause:
Android API Level 24 and above requires in-app declaration of intent to use user-added CAs, which is missing from Jitsi Meet Android configuration.

Patch:
Replace /jitsi/jitsi-meet/blob/master/android/app/src/main/res/xml/network_security_config.xml with:
```xml
<network-security-config> 
   <base-config> 
      <trust-anchors> 
         <certificates src="system" /> 
         <certificates src="user" /> 
      </trust-anchors> 
   </base-config> 
   <domain-config cleartextTrafficPermitted="true"> 
      <domain includeSubdomains="false">localhost</domain> 
      <domain includeSubdomains="false">10.0.2.2</domain> 
   </domain-config> 
</network-security-config>
```
and recompile Android application. 

Android application is now able to connect to server, and functions correctly.

### Server information:

- Jitsi Meet version:  2.0.4627-1
- Operating System: Linux (Debian 10)

### Client information:

- Browser / app version: 20.2.3
- Operating System: Android

### Additional information:

Additional testing may be required for the domain-config bits (I'm not acutally sure what those are for), but the above configuration worked for me in my environment.

**Comment by saghul** [comment]
Thanks! Can you send it in PR form? This LGTM.



> Additional testing may be required for the domain-config bits (I'm not acutally sure what those are for),

Those are for development, to allow the app to make HTTP (non S) connections when connecting to the React Native bundler which runs in localhost via a tunnel.
