### ISSUE TITLE
> Task :sdk:bundleReleaseJsAndAssets FAILED

### ISSUE THREAD

**Issue by vinodlee** [jitsi/jitsi-meet#7228]
[ INFO ] ------------------------------------------------------------------------

[ INFO ] BUILD SUCCESS

[ INFO ] ------------------------------------------------------------------------

[ INFO ] Total time: 0.778 s

[ INFO ] Finished at: 2020-07-03T22:12:53+05:30

[ INFO ] ------------------------------------------------------------------------

~/jitsi-meet

Building and publishing the Jitsi Meet SDK

~/jitsi-meet/android ~/jitsi-meet

> Task :react-native-background-timer:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-calendar-events:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-community-async-storage:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

Note: /Users/vinoth/jitsi-meet/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

3 warnings

> Task :react-native-community_netinfo:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-default-preference:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-google-signin:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

Note: /Users/vinoth/jitsi-meet/node_modules/@react-native-community/google-signin/android/src/main/java/co/apptailor/googlesignin/RNGoogleSigninModule.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

3 warnings

> Task :react-native-immersive:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-keep-awake:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-linear-gradient:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings

> Task :react-native-sound:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

Note: /Users/vinoth/jitsi-meet/node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

3 warnings

> Task :react-native-svg:compileReleaseJavaWithJavac

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

Note: /Users/vinoth/jitsi-meet/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/TSpanView.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

3 warnings

> Task :react-native-webrtc:compileReleaseJavaWithJavac

Note: /Users/vinoth/jitsi-meet/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-webview:compileReleaseJavaWithJavac

Note: /Users/vinoth/jitsi-meet/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /Users/vinoth/jitsi-meet/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

> Task :sdk:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

What went wrong:
Failed to capture fingerprint of input files for task ‘:sdk:bundleReleaseJsAndAssets’ property ‘$1’ during up-to-date check.

Failed to create MD5 hash for file ‘/Users/vinoth/jitsi-meet/node_modules/node-jq/bin/jq’ as it does not exist.

Try:
Run with –stacktrace option to get the stack trace. Run with –info or –debug option to get more log output. Run with –scan to get full insights.

Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

Use ‘–warning-mode all’ to show the individual deprecation warnings.

See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by Echolon** [comment]
@vinodlee can you please fill out the issue template and put you log out put into something like paste-bin.

Until then I will close this issue. Sorry, we need to focus a bit on resources.

Mention me once you have done so and I will reopen.

Anyway, thanks for reporting!
