### ISSUE TITLE
Not able to access camera and Microphone in iOS WKWebView

### ISSUE THREAD

**Issue by ShubhGar** [jitsi/jitsi-meet#7231]
I try to load "https://jitsinew.tinda.app/test" in WKWebview but its unable to access Camera and Microphone Check Screenshot
![IMG_0072](https://user-images.githubusercontent.com/24808854/86513779-8fe0ce00-be2a-11ea-9e7c-3716f53c9b15.png)

Also I try this html string to load in WKWebView. Both gives same error
let html = """
<head>
  <meta charset="utf-8">
  <meta http-equiv="content-type" content="text/html;charset=utf-8">
</head>

<body>

 <script src="https://meet.jit.si/external_api.js"></script>

  <script >
    var domain = "meet.jit.si";
    var options = {
      roomName: "test",
      width: 700,
      height: 1500,
      parentNode: undefined,
      configOverwrite: {
        disableDeepLinking: true
      }
    }
    var api = new JitsiMeetExternalAPI(domain, options);
  </script>
</body>

</html>
"""

**Comment by Echolon** [comment]
can you do this please and paste the results:  https://test.webrtc.org

**Comment by ShubhGar** [comment]
Ok. I also tried your iOS SDK in Xcode 11.4 but unable to build project.

**Comment by ShubhGar** [comment]
@Echolon This url is not working with WKWebview and SFSAfariViewController.

**Comment by ShubhGar** [comment]
@Echolon  I am also not able to use your SDK with Xcode 11.4
![Screenshot 2020-07-03 at 6 16 09 PM](https://user-images.githubusercontent.com/24808854/86551696-72fbe600-bf63-11ea-8d1f-d54fea477767.png)

**Comment by jhiswin** [comment]
This is not something that can be fixed by jitsi-meet: https://bugs.webkit.org/show_bug.cgi?id=208667

**Comment by hasankamrul** [comment]
is there anyone who have the solution, I can't figure out the solution.
