### ISSUE TITLE
App Force Close after navigate to Gallery

### ISSUE THREAD

**Issue by naufalahnaf17** [jitsi/jitsi-meet#7235]
I don't know what happened when I entered the gallery and took pictures, when I returned to Jitsi Meet, the application crashed with a log that the image was obtained.

how to fix this ? 

react-native-image-picker 2.3.0

**Comment by Echolon** [comment]
What are your system settings?

**Comment by naufalahnaf17** [comment]
I start to setting react-native-image-picker for my apps , 
this is my package.json setting : 
react : 0.61
react-native-image-picker : 2.3.0

*P.S all setting package json is default from jitsi-meet-project

currently i work on android 10 for test the application
