### ISSUE TITLE
Feature request: Add meeting cards (extending

### ISSUE THREAD

**Issue by Sebl29** [jitsi/jitsi-meet#7239]
**Problem description**
As a meeting participant, I would like to give signals, without disturbing/speaking.
As a speaker in a call, I would like to receive some feedback and give others the opportunity of a tiny secondary channel, while I am blocking the only audio track.
Like e.g. giving thumbs up/down into the camera or pointing on my ears and making weird faces etc, I would like to show neutral symbols/texts. The idea is the same as the "raise your hand" / "I wanna speak" button, just more of them.
Meeting cards are not direct interrupting: If a person sees the "speak up" / "somebody has background noise" he can just go on and work on that.

**The desired behavior**
As a sender: Instead of having one card for "Raise your hand", I want to quick-choose a card out of ~9 possible cards.
As a receiver: 
- a toaster with the card (picture and small text) is popping up in corner.
- The toaster also shows the name of the sender.
- if more than one person is sending the same card, the names get appended to that toaster. 
- the toaster has an "me too" / "I agree" button, to quick-reply. Also a "I disagree" button (e.g. "No, I can hear the speaker clearly. He is audible for me.").
- One toaster per card, so if multiple cards are send, there are multiple toasters.
- The toaster should disappear automatically after 6 seconds (counting from the last same-card-sending). 
- The sent cards should be added to the chat, so I can read again if I could not read it while on screen.
- which cards?: Plz see links below
- Color code: one color for speaker related cards (e.g. "speak up"), other color for the crowd ("plz mute").
- Could also be used for quick poll: thumb up (10 clicks) vs thumb down (1 click).
Funny cards a charming: Everybody smiles on "Elmo", even if this means a speaker should come to an end / should accept the opinion. Also its not such a "hard punch" than getting interrupted on the audio track.

**Considered alternatives**
https://www.seethinkdo.it/meeting-cards
https://github.com/stephenwalker78/meeting-cards/blob/master/meeting-card-vectors.pdf
Additional cards: 
- Come closer to the mic
- somebody is hammering on the mic
- ... (to be discussed, while on serious selection)

Currently I use printed paper cards or my mobile with the browser (card on fullscreen) to show them to the camera. But this depends, on how the other participants look at the group (gallery view or else): Maybe it is not visible at all (in larger groups) or too small.
But this is only working with the camera:
- camera must be switched on for meeting-card-sender.
- the group must be small, so the video-tile is large enough (if on gallery-view) to be readable.
- if not on gallery-view, it is not visible to everybody.
- other participants must focus on my video (if video tile to small)
- bad video quality, some cards can not be read

IMHO this is a killer feature, underlines the innovative open-source software / community, of jitsi. :-)

**Comment by forteller** [comment]
This sounds like a very clever idea to me! Unfortunately I don't know how to code, but if my vote matters, I'll give it to this :)

**Comment by forteller** [comment]
An idea is not bad just because it hasn't been worked on for a while. I think the idea of the stale bot is illogical and I hope this issue, with 5 thumbs up (a lot compared to what other issues on here gets) will be kept open and ready to be considered whenever there's more resources available for it.

Thanks!

**Comment by saghul** [comment]
Nobody said it's a bad idea. We just have no plans to implement it.
