### ISSUE TITLE
Text encoding issue weird characters for emoji and some labels

### ISSUE THREAD

**Issue by franckadil** [jitsi/jitsi-meet#7240]
Emojis and some text labels show weird characters: ðŸ˜ƒ on latest stable build. We have been able to replicate this easely on 3 new installs.

It is apparent to a text encoding issue, but after looking it up with our dev team we suspect an issue with webpack modules…

I’ve included screenshots of an instance using the latest stable version. The tests were run on Firefox, Safari, Microsoft Edge, Google Chrome, and Chromium.

![image](https://user-images.githubusercontent.com/42721509/86621020-b6833e00-bfbd-11ea-89a7-37629a3597df.png)
![image](https://user-images.githubusercontent.com/42721509/86621088-dadf1a80-bfbd-11ea-90ad-1a9087898934.png)
![image](https://user-images.githubusercontent.com/42721509/86621106-e29ebf00-bfbd-11ea-88da-d542484026f8.png)

Version: Latest Stable repositories
OS: Ubuntu 20.04 /18.04
Browsers: Firefox, Google Chrome, Chromium, Safari, Microsoft Edge

**Comment by saghul** [comment]
Can you please test using the latest nightly? I did a fresh stable install last friday and didn't observe those.

**Comment by franckadil** [comment]
Hi @saghul i tested on nightly but didn't get the error too. But is it safe to work with nightly builds on production?

**Comment by franckadil** [comment]
@saghul Quick update I installed a nightly build for a client and had the same glitch. I am starting to think it's related to Chrome or Webkit...

![image](https://user-images.githubusercontent.com/42721509/87582424-a7497200-c6da-11ea-9238-1676105f5694.png)

**Comment by franckadil** [comment]
@saghul Any update? Thank you.

**Comment by higunjan** [comment]
I'm facing same issue with it. Let me know if you've any solution to solve in existing.

**Comment by GregKezo** [comment]
I, too, am having this issue
