### ISSUE TITLE
Embed does not start camera/microphone on MacOS Safari (latest)

### ISSUE THREAD

**Issue by alexandermaisey** [jitsi/jitsi-meet#7241]
### Description:

Utilizing embed API on a simple HTML page (startAudioMuted and startVideoMuted both set to false in embed config), initiation of conference starts without issue.  Camera and Microphone buttons are in "muted" state;  Does not happen in Chrome (latest) on same MacOS device.  Does not happen on meet.jit.si/same room code on same MacOS device.

### Steps to reproduce:

1. Start call on meet.jit.si/room code via a separate device
2. Start call on embedded version of Jitsi Meet, to same room code via MacOS Safari
3. Microphone and camera buttons need to be clicked to activate

### Expected behavior:

Unless dictated to start muted, camera and microphone should start automatically

### Actual behavior:

Camera and microphone start in "muted" state; Does not occur in Chrome (latest) on same MacOS device

### Server information:

- Jitsi Meet version: N/A (Public meet.jit.si server)
- Operating System: N/A (Public meet.jit.si server)

### Client information:

- Browser / app version: Safari
- Operating System: MacOS Catalina

### Additional information:

Can replicate across a number of MacOS and Safari versions.  As stated above, only encountering this issue when using the embedded version of Jitsi Meet, which otherwise works perfectly (and does not have this problem in Chrome).

**Comment by Echolon** [comment]
I will refer you to this issue first: https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by alexandermaisey** [comment]
@Echolon please justify closing this ticket and referencing a similar sounding, but actually unrelated issue?

My ticket is in reference to the fact that the state does not initiate automatically, but can be manually triggered.  The ticket you reference has examples of total failures that cannot be manually overcome.

**Comment by Echolon** [comment]
Ok, can you still please provide the webrtc steps and try the suggested step for Mac

**Comment by saghul** [comment]
I this the reason for this is that requesting those permissions on mobile Safari requires a user interaction. As in, you cannot get them unless the permission request comes from a button press.

@jallamsetty1 Remember last week when I asked you about the double click needed for permissions on mobile Safari? This is it, the problem manifests when using the iframe API. I suspect the code using this flag https://github.com/jitsi/lib-jitsi-meet/blob/8275c883fcd6eba02386be0fd91fa8b81335414b/modules/browser/BrowserCapabilities.js#L82 is not working right.

**Comment by alexandermaisey** [comment]
@Echolon I will do this shortly and update this ticket.  Thank you.
@saghul I would like to point out that my issue is occurring on the MacOS version of Safari, not the iOS.  Thank you.

**Comment by saghul** [comment]
@alexandermaisey Thanks for clarifying. FWIW, I got a private report of the same problem on iOS. It's very likely both are the same problem.

**Comment by jallamsetty1** [comment]
Thanks for the pointer @saghul, will check it out today.

**Comment by jallamsetty1** [comment]
The fix for this issue is available in the nightly builds and will be available in the next release of meet.jit.si.
