### ISSUE TITLE
Local control of other participants' volume on iOS/Android

### ISSUE THREAD

**Issue by wjbuys** [jitsi/jitsi-meet#7242]
**Is your feature request related to a problem you are facing?**
I would like to adjust the volume of other participants on my mobile device. I can do this on Desktop/Web with the per-participant volume slider. However, this doesn't seem to exist on either the iOS or Android apps.

**Describe the solution you'd like**
Add a volume slider for each participant, possibly in the pop-up menu. This would match the feature as it exists in Desktop/Web.

**Describe alternatives you've considered**
I've tried running the web version on mobile, and while that works, the pop-up menu with the slider doesn't seem to work in mobile browsers (Safari on iOS 13, Firefox on Android); it disappears immediately after clicking the three-dots icon.

**Comment by wjbuys** [comment]
This is still an issue.

**Comment by abdul3Edge** [comment]
Could any one please lead to right way to achieve this. Thank you

**Comment by contrapunctus-1** [comment]
This is one of the biggest issues I face on mobile 😔

(Perhaps the problem can be tackled at a higher level - does Jitsi Meet do anything to ensure that all contacts have the same volume, so that people don't have to constantly fiddle with their volume?)

**Comment by matiaspl** [comment]
It seems there is some workaround for IOS devices, but that would need some developer work: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource
