### ISSUE TITLE
jitsi-meet client side html

### ISSUE THREAD

**Issue by mohamedsabrymohamed** [jitsi/jitsi-meet#7244]
### Steps to reproduce:

1. cloned https://github.com/jitsi/jitsi-meet on my machine
2. After opening it in browser it give me console errors and only display this message:
     Uh oh! We couldn't fully download everything we need :(
    We will try again shortly. In the mean time, check for problems with your internet connection!

3. I've a good internet connection but it can't find these files:
   all.css / lib-jitsi-meet.min.js / app.bundle.min.js / do_external_connect.min.js / lib-jitsi-meet.min.js / app.bundle.min.js

### Expected behavior:

it should run as seen on demo not like so.

### Server information:

- Jitsi Meet version: latest version of cloned client side
- Operating System: windows and mac

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Have you built the project? You can't just take the repo as is and open the page in the browser. You need to serve it with a web server. You can test the local frontend against our alpha backend by using `make dev`
