### ISSUE TITLE
avatar-url from presence not taken into account

### ISSUE THREAD

**Issue by maxired** [jitsi/jitsi-meet#7250]
### Description:

When using the poltergeist module,
we can define an avatar to the new participant.
This avatar is not taken into account on jitsi meet web interface
 
### Steps to reproduce:

1. Setupt poltergeist on your instance
2. Join a conference
3. Create poltergeist user : curl **"http://localhost:5280/poltergeist/create?room=myroom&user=mysyerideee&name=Maxired&status=ringing&avatar=https://avatars2.githubusercontent.com/u/1194083"** -H 'host: conference.jitsi.retrolution.co' -vvv

### Expected behavior:

When the ghost user appear, it should use the avatar provided.

### Actual behavior:

The ghost user does not use the provided avatar url.
The avatar url is not populated here
https://github.com/jitsi/jitsi-meet/blob/0598e7369b2dfac9c11637c3c356cf634466430f/react/features/base/participants/middleware.js#L355

If I trace it deeper in the stack, when we received and deal with the presence message [here](https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/ChatRoom.js#L427) , we are not using the 'avatar-url' attributes 

### Server information:

- Jitsi Meet version: 
- Operating System: debian

### Client information:

- Browser / app version:  chrome 83.0.4103.116 (
- Operating System: macos

**Comment by Echolon** [comment]
@saghul is this module within support? (sorry not involved to that detail)

**Comment by saghul** [comment]
We haven't used it in a while IIRC, so it may have a bug or three...

**Comment by maxired** [comment]
discussion on that PR seems to be related : https://github.com/jitsi/jitsi-meet/pull/2650/files
