### ISSUE TITLE
Set password via Android SDK

### ISSUE THREAD

**Issue by densi97** [jitsi/jitsi-meet#7256]
How to set the password via the Android SDK?

When entering a password protected room we want to programmatically enter the password for this room. With the JS api this is possible, but not with the SDK.

This needs to be implemented asap, as the demand for this feature is huge.

**Comment by saghul** [comment]
This is not currently implemented, sorry.



> This needs to be implemented asap, as the demand for this feature is huge.

Sorry, that's not how we work around here pal.

**Comment by excogitatr** [comment]
Hey @saghul. Please let us know if you are planning to add this feature in the near future. Thanks!

**Comment by AndaBucsa** [comment]
Hi @saghul,

I am interested in this feature as well and would like to fork the repository and try to implement the feature.
Our React know-how is minimal, can you please provide some guidance on how the implementation should look like?

Thanks,
Anda

**Comment by aliraza96** [comment]
Hey @saghul , do you intend to introduce this feature for the Android SDK in future or not? Please reply

**Comment by saghul** [comment]
We have no short term plans to implement this, sorry.
