### ISSUE TITLE
iOS Keyboard is overlapping the view 

### ISSUE THREAD

**Issue by MohamedZiad** [jitsi/jitsi-meet#7258]
When i try to use chat the keyboard overlaps the view 
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-08 at 14 06 26](https://user-images.githubusercontent.com/68012329/86916722-4d6a0a80-c124-11ea-9fb4-43a15ce64002.png)

**Comment by saghul** [comment]
That is not our layout. Are you adding views of your own to the app?

**Comment by MohamedZiad** [comment]
we are integrating the SDK in our own App

**Comment by Echolon** [comment]
@MohamedZiad I think we cannot provide support on this. Please refer to the Jitsi Community Website for help.

@saghul I will close this.
