### ISSUE TITLE
Adding of minimizing the video screen room

### ISSUE THREAD

**Issue by vijaykholiya** [jitsi/jitsi-meet#7260]
I wanted to add a minimize button option which minimizes the video screen and user can use his other applications simultaneously.

This feature has already been present in Android app of Jitsi meet present in play store but isn't available in this repository. Though the code of minimizing the screen is present (not sure) but the functionality or implementation hasn't been done.

1. Jitsi Meet play store app with minimize feature at top left corner

![Screenshot_20200708-192121](https://user-images.githubusercontent.com/56336857/86928016-a43a0900-c151-11ea-806c-31b5be0d5cc6.jpg)

2. Jitsi meet from this repository without minimize feature

![Screenshot_20200708-192211](https://user-images.githubusercontent.com/56336857/86928090-ba47c980-c151-11ea-868c-b6978a63227b.jpeg)

**Comment by saghul** [comment]
The build from the store comes straight from this repository. The feature is there. We might have broken the display of the icon, we'll take a look.
