### ISSUE TITLE
Enable / disable guests per meeting individually

### ISSUE THREAD

**Issue by christianvw** [jitsi/jitsi-meet#7263]
**Is your feature request related to a problem you are facing?**
We have different kinds of meetings. We have internal meetings where we just want to allow internal users to join our meetings but on the same time we have meetings with external persons (guests).

We currently must allow guests gloablly even if we don't want them in every meeting.

**Describe the solution you'd like**
It would be nice to have the ability to change in the meeting if guests are allowed to join or not. You could click on the little (i) where you can set the password and there you can allow guests or not (tickbox).

An environment variable to define the default option would be perfect.

**Describe alternatives you've considered**
We could set up two servers, one with guests disabled and one with guests enabled but that is counter-intuitive for our users. There is a high risk that all users use the guests-enabled server then because it's easier.

**Comment by saghul** [comment]
What authentication mechanism have you configured currently?

**Comment by christianvw** [comment]
Currently we use LDAP, but we plan to switch to JWT.
