### ISSUE TITLE
App crashing due to not getting jitsimeetview

### ISSUE THREAD

**Issue by soorajjaivas** [jitsi/jitsi-meet#7265]
I am using Jitsisdk (org.jitsi.react:jitsi-meet-sdk:2.8.2) in my android app.In my application ,directly launching JitsiMeetActivity by calling like this JitsiMeetActivity.launch(context, options). But app crashing in video session.Below is the issue.Please help me
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView (JitsiMeetActivity.java:106)
org.jitsi.meet.sdk.JitsiMeetActivity.leave (JitsiMeetActivity.java:122)
org.jitsi.meet.sdk.JitsiMeetActivity.finish (JitsiMeetActivity.java:95)
org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated (JitsiMeetActivity.java:220)
java.lang.reflect.Method.invoke (Method.java)
org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread (ListenerUtils.java:135)
org.jitsi.meet.sdk.ListenerUtils.access$000 (ListenerUtils.java:35)
org.jitsi.meet.sdk.ListenerUtils$1.run (ListenerUtils.java:114)
android.os.Handler.handleCallback (Handler.java:790)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

**Comment by saghul** [comment]
Please update to SDK version 2.9.0

**Comment by soorajjaivas** [comment]
After updated to latest version (2.9.0), I could not join to video session.Following error getting
 E/JitsiMeetSDK: [features/analytics] Error(Error){"message":"No analytics handlers created!","stack":"Error: No analytics handlers created!\n    at anonymous (index.android.bundle:448:1252)\n    at f (index.android.bundle:111:155)\n    at anonymous (index.android.bundle:111:882)\n    at apply (native)\n    at anonymous (index.android.bundle:117:1783)\n    at y (index.android.bundle:117:661)\n    at C (index.android.bundle:117:1025)\n    at callImmediates (index.android.bundle:117:3100)\n    at value (native)\n    at anonymous (index.android.bundle:36:1283)\n    at value (index.android.bundle:36:2939)\n    at value (index.android.bundle:36:1253)\n    at value (native)"}

**Comment by saghul** [comment]
That's just a print of an exception, the app doesn't actually crash at that point.

**Comment by pesicivan** [comment]
This crash also happens on 2.9.0 on finishing the video call. The app crashes for the last participant of the conference with the same stacktrace.

**Comment by saghul** [comment]
Can you reproduce it with the beta app, or the SDK samples?

**Comment by soorajjaivas** [comment]
sometimes ths issue happening, saying that app is crashing due to the following issue
Fatal Exception: android.app.RemoteServiceException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7e76698 u0 /org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService}
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1983)

**Comment by soorajjaivas** [comment]
Hi JItsi team,

This is a serious crash issue happening in jitsi sdk to many app users.Crash log getting in firebase services for past 1 month.So please have a look and help me to sort out this issue please.Crash log is provided below

Fatal Exception: java.lang.RuntimeException
java.lang.reflect.InvocationTargetException
org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread (ListenerUtils.java:139)
org.jitsi.meet.sdk.ListenerUtils.access$000 (ListenerUtils.java:35)
org.jitsi.meet.sdk.ListenerUtils$1.run (ListenerUtils.java:114)
android.os.Handler.handleCallback (Handler.java:790)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:198)
android.app.ActivityThread.main (ActivityThread.java:7055)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:523)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:836)

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView (JitsiMeetActivity.java:110)
org.jitsi.meet.sdk.JitsiMeetActivity.leave (JitsiMeetActivity.java:126)
org.jitsi.meet.sdk.JitsiMeetActivity.finish (JitsiMeetActivity.java:99)
org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated (JitsiMeetActivity.java:223)
java.lang.reflect.Method.invoke (Method.java)
org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread (ListenerUtils.java:135)
org.jitsi.meet.sdk.ListenerUtils.access$000 (ListenerUtils.java:35)
org.jitsi.meet.sdk.ListenerUtils$1.run (ListenerUtils.java:114)
android.os.Handler.handleCallback (Handler.java:790)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:836)

**Comment by saghul** [comment]
> sometimes ths issue happening, saying that app is crashing due to the following issue
> Fatal Exception: android.app.RemoteServiceException
> Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7e76698 u0 /org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService}
> android.app.ActivityThread$H.handleMessage (ActivityThread.java:1983)

We've seen this one happen in a small amount of devices. If you look through the code you'll see that we do call startForeground always, so I'm not sure what's going on there.

**Comment by saghul** [comment]
> Hi JItsi team,
> 
> This is a serious crash issue happening in jitsi sdk to many app users.Crash log getting in firebase services for past 1 month.So please have a look and help me to sort out this issue please.Crash log is provided below

I need a way to reproduce this in order to help you.

**Comment by pesicivan** [comment]
@soorajjaivas I believe that, compared to previous versions, you should not count on JitsiView being alive when JistiMeetActivity.onDestroy is called. I did some rearranging of the code and my app is no longer crashing on finishing calls. 

> Can you reproduce it with the beta app, or the SDK samples?

I could not reproduce it with beta app and SDK samples. After updating from 2.8.2 to 2.9.0 I had to change the code in my class that inherits JitsiMeetActivity, as I described above.

**Comment by Echolon** [comment]
@soorajjaivas can you provide steps how to reproduce this?
