### ISSUE TITLE
Disable some menu in settings not working in android

### ISSUE THREAD

**Issue by soorajjaivas** [jitsi/jitsi-meet#7266]
I am using jitsi SDK(org.jitsi.react:jitsi-meet-sdk:2.8.2) in my android app.I need to disable some features in settings menu of video call.Below functions not working.Please help me

   .setFeatureFlag("livestreaming.enabled", false)
                .setFeatureFlag("recording.enabled", false)
                .setFeatureFlag("android.recording.enabled", false)
                .setFeatureFlag("meeting-password.enabled", false)
                .setFeatureFlag("raise-hand.enabled", true)
                .setFeatureFlag("tile-view.enabled", false)

**Comment by saghul** [comment]
Update to 2.9.0, not all of those are available on 2.8.2.

**Comment by soorajjaivas** [comment]
is it possible to hide start showing sub titles and Invite someone menus?
