### ISSUE TITLE
Toggling Tile View changes aspect ratio / crop of other participants video

### ISSUE THREAD

**Issue by mu35li** [jitsi/jitsi-meet#7267]
### Description:

When toggling the tile view, the apsect ratio of other participants video is changed in their view regardless of their setting of tile view or speaker view, resulting in a cropped image.

### Steps to reproduce:

1. Join any jitsi call with at least two participants
2. have one participant toggle tile view on and off while other participant watching their own video aspect ratio
3. user who is doing nothing experiences changes in their video 

### Expected behavior:

Own video stays the same when other participants change their view settings.

### Actual behavior:

Own video gets cropped when other participants toggling tile view.

### Server information:

- Jitsi Meet version: https://jitsi.org/
- Operating System: -

### Client information:

- Browser / app version: Google Chrome 83.0.4103.116
- Operating System: Mac OS Catalina 10.15.3

### Additional information:
```2020-07-09T07:08:21.314Z [modules/xmpp/JingleSessionPC.js]
<R.modifyContents>:  JingleSessionPC[p2p=true,initiator=true, sid=xxx] received remote max frame height: 360
lib-jitsi-meet.min.js?v=4203.857:10

2020-07-09T07:08:21.315Z [modules/xmpp/JingleSessionPC.js]
<R.setSenderVideoConstraint>:  JingleSessionPC[p2p=false,initiator=false,sid=xxx] setSenderVideoConstraint: 360 
lib-jitsi-meet.min.js?v=4203.857:10 

2020-07-09T07:08:21.315Z [modules/xmpp/JingleSessionPC.js] 
<R.setSenderVideoConstraint>:  JingleSessionPC[p2p=true,initiator=true,sid=xxx] setSenderVideoConstraint: 360 
lib-jitsi-meet.min.js?v=4203.857:10 

2020-07-09T07:09:38.978Z [modules/xmpp/strophe.jingle.js] 
<g.onJingle>:  on jingle content-modify from ```

**Comment by saghul** [comment]
@jallamsetty1

**Comment by jallamsetty1** [comment]
Hey there, are you seeing this in the nightly builds ? This is a new feature that we have been working on as part of our cpu optimization efforts on the client. We will be changing the send resolution based on how other participants in the call are viewing this particular participant. If a participant is viewed on stage, 720p will be sent, participant who is on one of the thumbnails on the filmstrip will be sending 180p and those on the tile view will be sending 360p/180p based on how many tiles are in the tile view.
This will save cpu/bandwidth on the client machines. Is there a reason why you don't want the send resolution to not change even when no one else in the call is viewing you at that particular resolution ?

**Comment by mu35li** [comment]
I'm seeing this on any regular meeting on meet.jitsi.org

The problem ist not a change in resolution but a change in aspect ratio of the image I am viewing while someone else is toggling their tile view. So if another participant is switchen to tile view the image I am seeing of my own video is cropped in. I want my picture to be cropped the same way regardless of what anyone is changing in their preferences. Hope this clears things up.

**Comment by jallamsetty1** [comment]
> I'm seeing this on any regular meeting on meet.jit.si
> 
> The problem ist not a change in resolution but a change in aspect ratio of the image I am viewing while someone else is toggling their tile view. So if another participant is switchen to tile view the image I am seeing of my own video is cropped in. I want my picture to be cropped the same way regardless of what anyone is changing in their preferences. Hope this clears things up.

You are right, looks like we updated the web client yesterday on meet.jit.si. Can you please attach screenshots for before/after ? I am not able to reproduce this. It probably has to do with your camera capabilities. Do you see the same when you change your video quality settings to SD ? You can do this by going to `Manage Video Quality ` under `More actions`

**Comment by saghul** [comment]
@jallamsetty1 I could reproduce it as follows: open a meeting on 2 browser windows. Make one of the windows pretty small. On the large window, focus on yourself. On the small one, toggle tile view. You will see the local video on the big window "zoom in" as the resolution dropped to 180p.

I suspect the answer might lay here: https://github.com/jitsi/jitsi-meet/blob/ce812591f9f628f330d74862b0e6d1d73f9508ec/modules/UI/videolayout/VideoContainer.js#L80

**Comment by jallamsetty1** [comment]
> @jallamsetty1 I could reproduce it as follows: open a meeting on 2 browser windows. Make one of the windows pretty small. On the large window, focus on yourself. On the small one, toggle tile view. You will see the local video on the big window "zoom in" as the resolution dropped to 180p.
> 
> I suspect the answer might lay here:
> 
> https://github.com/jitsi/jitsi-meet/blob/ce812591f9f628f330d74862b0e6d1d73f9508ec/modules/UI/videolayout/VideoContainer.js#L80

@saghul, again this behavior is totally dependent on the camera. When we apply constraints on an existing track with the lower resolution, some camera's produce a stream that looks like its "zoomed in" on a large display while others simply blur the existing stream. I see this zoom in effect only my macbook built-in cam but not on Logitech Brio or Win10 built-in.
Are you saying we should trigger a resize of the video layout when the resolution of the stream on stage changes resolution ?

**Comment by saghul** [comment]
I’ve seen that too, but the fact that we have that coefficient means we may compute different levels depending on the video size. I’m not 100% sure though.

**Comment by jallamsetty1** [comment]
Maybe there is a way, right now I see that it is computed when the window is resized. I will keep looking.

**Comment by mu35li** [comment]
Sorry for the late response! 
I attached an image showing the two states I was talking about. The above screenshot shows the cropped image when the other participant toggles tile view on their client. The below screenshot shows the state when the other person has turned speaker view on. I changed nothing on my side between the two images.

I hope this helps.
![jitsi_crop_issue](https://user-images.githubusercontent.com/6570226/87131845-4f071000-c295-11ea-9b03-432af5151bd3.png)

**Comment by jallamsetty1** [comment]
> Sorry for the late response!
> I attached an image showing the two states I was talking about. The above screenshot shows the cropped image when the other participant toggles tile view on their client. The below screenshot shows the state when the other person has turned speaker view on. I changed nothing on my side between the two images.
> 
> I hope this helps.
> ![jitsi_crop_issue](https://user-images.githubusercontent.com/6570226/87131845-4f071000-c295-11ea-9b03-432af5151bd3.png)

No worries, thank you for the screenshots. I will make a change so that we getter a better aspect ratio when we request the camera for lower resolutions.

**Comment by mu35li** [comment]
again, this is happening on my view while **the other person is changing their settings**. I don't really get why the resolution for my view has to change at all as I'm not doing anything.

**Comment by jallamsetty1** [comment]
> again, this is happening on my view while **the other person is changing their settings**. I don't really get why the resolution for my view has to change at all as I'm not doing anything.

Yes, that is the intended behavior of this new feature. We do not want to use resources (cpu/bandwidth) more than they are needed on the client machines. So the participants send resolution will now be determined based on how they are viewed by the other participants in the call. If a remote participant is viewing you in speaker view at a full 720p, only then your client will be sending 720p.

**Comment by thomp** [comment]
The issue of apparent cropping of the image remains unresolved. See mu35li's earlier comment ("The problem ist not a change in resolution but a change in aspect ratio of the image I am viewing while someone else is toggling their tile view.").

**Comment by jallamsetty1** [comment]
> The issue of apparent cropping of the image remains unresolved. See mu35li's earlier comment ("The problem ist not a change in resolution but a change in aspect ratio of the image I am viewing while someone else is toggling their tile view.").

Your aspect ratio shouldn't change when the other person is toggling their view. We are now getting a downscaled stream from the same video capture so the new stream should have the same aspect ratio.
