### ISSUE TITLE
Share screen and not window

### ISSUE THREAD

**Issue by marcosh** [jitsi/jitsi-meet#7269]
**Is your feature request related to a problem you are facing?**
While using meet.jit.si with Firefox 78.0.1 on Linux using two monitors, I'm not able to share the content of a single screen. The options I am given are either to share a single window or to share the whole screen (which is actually the two monitors content)

**Describe the solution you'd like**
I would like to be able to share the content of a single screen, selecting the monitor from the dropdown

**Comment by saghul** [comment]
You need to report this to Firefox. The browser is the one rendering those options, we as an application running in the browser have no control over it.
