### ISSUE TITLE
Jitsi banner misleading (fully encrypted)

### ISSUE THREAD

**Issue by sbocconi** [jitsi/jitsi-meet#7270]
This is a simple request to remove the "fully encrypted" text from meet banner.

`
Go ahead, video chat with the whole team. In fact, invite everyone you know. Jitsi Meet is a fully encrypted, 100% open source video conferencing solution that you can use all day, every day, for free — with no account needed.
`

Full encryption is end-to-end encryption, not transport or hop-to-hop encryption.

Zoom was rightly criticized because they were claiming to be fully encrypted and have changed since. I think it is important for Jitsi to correctly state what it can and cannot do.

**Comment by saghul** [comment]
There is no unencrypted bit in transit, that's what full-encryption is. If it were end-to-end encryption we'd call it by its name, as we do in the dialog that actually enables E2EE.

We have not claimed to have E2EE, until we have added it. And even then, we are not saying your meeting is end to end encrypted unless it is.

For more details, please see: https://jitsi.org/security/

**Comment by sbocconi** [comment]
Hi, we run a Jitsi instance free for the public to use as a service for the community, and we are therefore thankful to Jitsi.

Still "normal" users just see the banner and might think that nothing is left to be done regarding encryption, since it is already fully encrypted. I think it is in the interest of Jitsi as well to be precise with words, and it hopefully does not take much to explain that it is fully encrypted until the server, but not for the Jitsi Videobridge.

**Comment by saghul** [comment]
That is where we are heading. Once our next E2EE improvements are implemented we’ll make it opportunistic: it will be activated by default.
