### ISSUE TITLE
Jitsi + Socket IO Not Working (Android/IOS)

### ISSUE THREAD

**Issue by naufalahnaf17** [jitsi/jitsi-meet#7279]
i just try connect to socket.io-client but it doesnt work .
i try create new project react and it work properly

i still confused how this error can happened , log show not error but socket.on connect not triggered

**Comment by saghul** [comment]
I don't know what you mean, we don't use socket.io at all. Please, use the issue template, it's there for a reason, and be as detailed as possible.
