### ISSUE TITLE
No separation between Cancel/Add and Remove/Copy button

### ISSUE THREAD

**Issue by finn0** [jitsi/jitsi-meet#7283]
### Steps to reproduce:

1. Open https://meet.jit.si and create a meeting
2. Click on `Security Options` then click on `Add password`
3. Now look at `Cancel` and `Add` button
4. Enter a password and click on `Add` button
5. Now look at `Remove` and `Copy` button

![cancel-add](https://user-images.githubusercontent.com/28824347/87137182-0b5bd880-c28c-11ea-8461-d426669b27bd.png)

![remove-copy](https://user-images.githubusercontent.com/28824347/87137186-0bf46f00-c28c-11ea-8c78-795aab49552a.png)

### Expected behavior:

There should be some separation between `Cancel`/`Add` and `Remove`/`Copy`button.

### Actual behavior:

There is no separation present between `Cancel`/`Add` and `Remove`/`Copy` button.

### Server information:

- Jitsi Meet version:  Official Jitsi instance (https://meet.jit.si)
- Operating System: Unknown

### Client information:

- Browser / app version: Any
- Operating System: Any

**Comment by saghul** [comment]
Thanks for the report, fixed in https://github.com/jitsi/jitsi-meet/pull/7284
