### ISSUE TITLE
Conference terminated: Unable to resolve host "ip4only.arpa"

### ISSUE THREAD

**Issue by JoeyAndroidDev** [jitsi/jitsi-meet#7288]
My App with jitsi-meet works with our inhouse server, where several ports are blocked. When I open the conference in my App, everything works fine but when I want to join the conference in a browser, I can't see any video on the screen and a few seconds later, the app crashes with following Exception:

_E/JitsiMeetSDK: NAT64AddrInfo NAT64AddrInfo.discover: ipv4only.arpa
    java.net.UnknownHostException: Unable to resolve host "ipv4only.arpa": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at org.jitsi.meet.sdk.net.NAT64AddrInfo.discover(NAT64AddrInfo.java:62)
        at org.jitsi.meet.sdk.net.NAT64AddrInfoModule.getIPv6Address(NAT64AddrInfoModule.java:98)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103) 
        at java.net.InetAddress.getAllByName(InetAddress.java:1152) 
        at org.jitsi.meet.sdk.net.NAT64AddrInfo.discover(NAT64AddrInfo.java:62) 
        at org.jitsi.meet.sdk.net.NAT64AddrInfoModule.getIPv6Address(NAT64AddrInfoModule.java:98) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
        at android.os.Looper.loop(Looper.java:214) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
        at java.lang.Thread.run(Thread.java:919)_

When I debug my application, the following lines in the discover method where not executed: 
```

        InetAddress[] var3 = InetAddress.getAllByName(host);
        int var4 = var3.length;
```

Some ports are blocked on the server, but when I implement a Webview instead of using the JitsiMeetActivity it works, but that's not user friendly for me.
I have the crashes since I updated the sdk to the newest version.
With the version 2.5.1 of the sdk, the app won't crash, but still no video showing.
So I think it's not a server problem, because I only get the error with the sdk.

**Comment by saghul** [comment]
We log the exception but not crash on the SDK. Are you sure the app crashes or you just don't get any video? Can you paste the rest of `adb logcat` when you do this?

Also, is IPv6 being used in your network?

**Comment by JoeyAndroidDev** [comment]
Thanks for the quick response :)
You are right, it's not really a crash, I think. 
My suggestion is, that there is a connection error and instead of reconnect, the whole app is restarting.

Before the exception, the following line appears:
_I/ReactNativeJS: Halt: There are no SSRC groups in the remote description._

Then the exception comes a few times but when the conference is terminated, the following lines appear:

_I/JitsiMeetSDK: [modules/RTC/TraceablePeerConnection.js] TPC[1,p2p:false] ignored remote 'stream added' event for non-user streamid: default
D/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Renegotiate: creating answer
I/JitsiMeetSDK: [modules/xmpp/SdpConsistency.js] TPC[1,p2p:false] sdp-consistency replacing new ssrc3070390757 with cached 3070390757
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Current ssrc mapping:  {}
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Parsed primary video ssrcs  [ 3070390757, 1870369707, 2308611099 ]  making sure all have rtx streams
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Already have an associated rtx ssrc forvideo ssrc 3070390757: 374040482
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Updating mline to associate 374040482rtx ssrc with primary stream, 3070390757
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] 374040482 was already associated with 3070390757
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Already have an associated rtx ssrc forvideo ssrc 1870369707: 4193696864
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Updating mline to associate 4193696864rtx ssrc with primary stream, 1870369707
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] 4193696864 was already associated with 1870369707
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Already have an associated rtx ssrc forvideo ssrc 2308611099: 2450753272
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] Updating mline to associate 2450753272rtx ssrc with primary stream, 2308611099
D/JitsiMeetSDK: [modules/xmpp/RtxModifier.js] 2450753272 was already associated with 2308611099
D/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Renegotiate: setting local description
D/com.oney.WebRTCModule.WebRTCModule: peerConnectionSetLocalDescription() start
D/com.oney.WebRTCModule.WebRTCModule: peerConnectionSetLocalDescription() end
I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] addRemoteStream - OK, SDPs:  { media: 
       [ 'm=audio 9 RTP/SAVPF 111 103 104 126\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-fb:111 transport-cc\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=setup:passive\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:TU2z\r\na=ice-pwd:VhOWfLLa6c1HEqLxgQuZQucf\r\na=fingerprint:sha-256 89:19:29:26:16:C3:55:0A:77:66:5A:B6:EA:21:DF:21:6C:3F:87:6B:EA:7A:B4:C5:C2:2E:07:65:BB:8B:42:66\r\na=ice-options:trickle\r\na=ssrc:324308538 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:324308538 msid:158ba9d0-21cd-4675-9ceb-558cb4da28f3-1 e6288886-8c9f-4c67-b881-d97bfbcc2973-1\r\na=ssrc:324308538 mslabel:158ba9d0-21cd-4675-9ceb-558cb4da28f3-1\r\na=ssrc:324308538 label:e6288886-8c9f-4c67-b881-d97bfbcc2973-1\r\na=rtcp-mux\r\n',
         'm=video 9 RTP/SAVPF 100 101 96 97\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:100 VP8/90000\r\na=rtpmap:101 VP9/90000\r\na=rtpmap:96 rtx/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:96 apt=100\r\na=fmtp:97 apt=101\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:101 transport-cc\r\na=rtcp-fb:101 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=setup:passive\r\na=mid:video\r\na=sendrecv\r\na=ice-ufrag:TU2z\r\na=ice-pwd:VhOWfLLa6c1HEqLxgQuZQucf\r\na=fingerprint:sha-256 89:19:29:26:16:C3:55:0A:77:66:5A:B6:EA:21:DF:21:6C:3F:87:6B:EA:7A:B4:C5:C2:2E:07:65:BB:8B:42:66\r\na=ice-options:trickle\r\na=ssrc:3070390757 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:3070390757 msid:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1 bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:3070390757 mslabel:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1\r\na=ssrc:3070390757 label:bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:374040482 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:374040482 msid:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1 bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:374040482 mslabel:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1\r\na=ssrc:374040482 label:bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:1870369707 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:1870369707 msid:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1 bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:2308611099 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:2308611099 msid:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1 bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:4193696864 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:4193696864 msid:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1 bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc:2450753272 cname:aKJRdU7ORVQv//bB-1\r\na=ssrc:2450753272 msid:a6fe820a-b4ba-442d-85d2-e8423ded7b94-1 bcb358fc-b3b3-4236-bc84-ba8e3258726a-1\r\na=ssrc-group:FID 3070390757 374040482\r\na=ssrc-group:FID 1870369707 4193696864\r\na=ssrc-group:FID 2308611099 2450753272\r\na=ssrc-group:SIM 3070390757 1870369707 2308611099\r\na=rtcp-mux\r\n',
         'm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=setup:passive\r\na=mid:data\r\na=ice-ufrag:TU2z\r\na=ice-pwd:VhOWfLLa6c1HEqLxgQuZQucf\r\na=fingerprint:sha-256 89:19:29:26:16:C3:55:0A:77:66:5A:B6:EA:21:DF:21:6C:3F:87:6B:EA:7A:B4:C5:C2:2E:07:65:BB:8B:42:66\r\na=ice-options:trickle\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' ],
      raw: 'v=0\r\no=- 8995157041388492043 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS 158ba9d0-21cd-4675-9ceb-558cb4da28f3\r\na=group:BUNDLE audio video data\r\nm=audio 9 RTP/SAVPF 111 103 104 126\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-fb:111 t
I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] removal not necessary
I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] addition not necessary

I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] (TIME) ICE failed P2P? false:	 1594390969950
I/JitsiMeetSDK: [JitsiConference.js] ICE Failed and ICE restarts are disabled
I/org.webrtc.Logging: EglRenderer: Duration: 4005 ms. Frames received: 120. Dropped: 0. Rendered: 120. Render fps: 30,0. Average render time: 3513 us. Average swapBuffer time: 774 us.
I/JitsiMeetSDK: [features/overlay] The conference will be reloaded after 21 seconds.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
W/unknown:WrappingUtils: Don't know how to round that drawable: com.facebook.drawee.drawable.RoundedColorDrawable@8b97cce
D/JitsiMeetSDK: [features/base/lastn] There is no active conference, not updating last N
I/JitsiMeetSDK: JitsiMeetOngoingConferenceServiceService stopped
D/JitsiMeetSDK: ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"url":"https://jitsi-test.company.intern/25165318392275332521594390890125325947303339363430757365722d303133383434","error":"conference.iceFailed"} }
D/JitsiMeetSDK: JitsiConnectionService reportCallFailed D8F30228-2F58-4521-95C6-852B8AAC4BCB
D/JitsiMeetSDK: JitsiConnectionService onStateChanged: DISCONNECTED D8F30228-2F58-4521-95C6-852B8AAC4BCB
I/org.webrtc.Logging: EglRenderer: setMirrorHorizontally: true
I/JitsiMeetSDK: Conference terminated: {error=conference.iceFailed, url=https://jitsi-test.company.intern/25165318392275332521594390890125325947303339363430757365722d303133383434}
I/JitsiMeetSDK: AudioMode Update audio route for mode: 0
I/JitsiMeetSDK: [modules/rttmonitor/rttmonitor.js] Stopping RttMonitor.
I/JitsiMeetSDK: [modules/e2eping/e2eping.js] Stopping e2eping
I/JitsiMeetSDK: AudioMode Updating audio device list
I/JitsiMeetSDK: [modules/xmpp/ChatRoom.js] do leave 25165318392275332521594390890125325947303339363430757365722d303133383434@conference.jitsi-test.company.intern/213e2db1
I/JitsiMeetSDK: [modules/RTC/TraceablePeerConnection.js] Closing TPC[1,p2p:false]...
D/com.oney.WebRTCModule.WebRTCModule: PeerConnection.close() for 0
I/org.webrtc.Logging: SurfaceEglRenderer: : Reporting frame resolution changed to 1280x720 with rotation 270
I/org.webrtc.Logging: GlShader: Deleting shader.
I/org.webrtc.Logging: VolumeLogger: stop@[name=worker_thread - 803, id=1476]
I/org.webrtc.Logging: WebRtcAudioTrackExternal: stopPlayout
I/org.webrtc.Logging: WebRtcAudioTrackExternal: underrun count: 0
I/org.webrtc.Logging: WebRtcAudioTrackExternal: stopThread_


I don't know if you like to see the attributes too. If so I can post them too.

**Comment by paweldomas** [comment]
> CONFERENCE_TERMINATED with data: { NativeMap: {"url":"https://jitsi-url/roomname","error":"conference.iceFailed"}

ICE failed means it's unable to establish connectivity between the client and the bridge.

**Comment by JoeyAndroidDev** [comment]
Yeah, but why only with the usage of the sdk?
With the browser on my phone or a webview in my app I can open the conference and I see the video.

**Comment by paweldomas** [comment]
You'd have to compare ICE candidates from both cases

**Comment by JoeyAndroidDev** [comment]
So, now I have tested the conference with the media-webrtc addon in firefox and in Chrome with webrtc-internals.
I have found 3 candidates, one with the port 4712, which is blocked. But the other ports (443 and 10000) should work.

a=candidate:1 1 tcp 2130706431 172.17.6.2 4712 typ host tcptype passive generation 0
a=candidate:3 1 udp 2130706431 172.17.6.2 10000 typ host generation 0
a=candidate:2 1 tcp 1694498815 172.17.6.2 443 typ srflx raddr 172.17.6.2 rport 4712 tcptype passive generation 0

The events are coming as following:
![events](https://user-images.githubusercontent.com/64791422/87314969-306a7880-c524-11ea-9731-030d6920aac3.PNG)

The blue arrow is the moment, the conference on the phone is terminated. In the tests with the Chrome browser on the phone, I don't get any events after this moment.

In the icecandidateerror is the error 701 written, but only on Chrome, so I think thats not the error I'm searching for, because the problem on Firefox is the same, but I don't get this error.

**Comment by tzezlcy** [comment]
we met the same question ,so how do you solve it?

> So, now I have tested the conference with the media-webrtc addon in firefox and in Chrome with webrtc-internals.
> I have found 3 candidates, one with the port 4712, which is blocked. But the other ports (443 and 10000) should work.
> 
> a=candidate:1 1 tcp 2130706431 ip jitsi-server 4712 typ host tcptype passive generation 0
> a=candidate:3 1 udp 2130706431 ip jitsi-server 10000 typ host generation 0
> a=candidate:2 1 tcp 1694498815 ip jitsi-server 443 typ srflx raddr _ip jitsi-server_ rport 4712 tcptype passive generation 0
> 
> The events are coming as following:
> ![events](https://user-images.githubusercontent.com/64791422/87314969-306a7880-c524-11ea-9731-030d6920aac3.PNG)
> 
> The blue arrow is the moment, the conference on the phone is terminated. In the tests with the Chrome browser on the phone, I don't get any events after this moment.
> 
> In the icecandidateerror is the error 701 written, but only on Chrome, so I think thats not the error I'm searching for, because the problem on Firefox is the same, but I don't get this error.

**Comment by JoeyAndroidDev** [comment]
Are you using the 2.5.1 sdk version?
