### ISSUE TITLE
Add file .env file and process.env support in the whole project and webpack proxy

### ISSUE THREAD

**Issue by shapkarin** [jitsi/jitsi-meet#7290]
Hello. My idea is to use `.env` or `.env.json` file and use it in whole project

and next it can be used in the codebase like
```
process.env.SOME_VAR
```

So at`.env.json` we can define:
```json
{
    "WEBPACK_DEV_SERVER_PROXY_TARGET": "http://league.superhero.com/"
}
```

And webpack config itself will use it and other files too.

Here is the working example https://github.com/aeternity/jitsi-meet/pull/77

**Comment by saghul** [comment]
What would it be used for, other than the webpack proxy?

**Comment by shapkarin** [comment]
Not sure but It can be used also for `turn` or `on` the redux dev tools.

**Comment by shapkarin** [comment]
@saghul it has the check if we have dev tools extension
https://github.com/jitsi/jitsi-meet/blob/3da1b65757502069b4dc8b1420ddfa35dac71156/react/features/base/app/components/BaseApp.js#L195-L198

But maybe also can be defined some check for the env variable that will turn off the redux dev tools as a middleware
