### ISSUE TITLE
iOS 14 beta 2: Safari stops responding

### ISSUE THREAD

**Issue by nathankurtyka** [jitsi/jitsi-meet#7292]
Jitsi Meet doesn't work on iOS 14 beta 2 for more than a few minutes. This is (fortunately?) easy to reproduce.

Steps to reproduce:
- Install iOS 14 beta 2
- Join any room on https://meet.jit.si that has 2+ people in it
- Leave video enabled and wait ~3 minutes

Video should of course continue to work, but after ~3 minutes the local video stream turns to black (both on local device and to other participants). *Other* video/audio streams continue to work. When this happens, Safari then starts to freeze/lock.

**Comment by saghul** [comment]
Given it works on stable safari and iOS 14 is in early beta I don't think we can spend resources taking a look yet. Please let us know how it progresses as more betas are released.

**Comment by mikeluyties** [comment]
We are getting this issue on the newly released stable version: 1.0.4370

It appears to happen 100% of the time if any client is on iOS.

**Comment by gh264367** [comment]
We are getting problems with iOS14 and safari 14 on iPhones and iPads. This is the latest stable release of iSO14 and Safari 14. The video works for a minutes then freezes or goes black. But on the iOs14/Safari 14 still able to hear the other person and the other person can hear the person on the iPhone or iPad.  I know this has to deal with the extra security that apple has added to iOS14. This deals with something of the local network on the mobile device.  Is this being looked into and is there a fix?
