### ISSUE TITLE
lobby: language/locale

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#7295]
1. Please set the default language as the language of the browser.
2. Please enable selecting the language at the lobby.
3. Once `Join meeting` is pressed, please join the meeting with the UI being in the locale selected in the lobby.

![Lobby](https://user-images.githubusercontent.com/17465872/87217429-4b09e980-c38c-11ea-8faf-7de2a035e071.png)

What do you think?

Thank you

**Comment by saghul** [comment]
>     1. Please set the default language as the language of the browser.

This should already be the case, right @damencho ? I thought we had fixed that.



> * Please enable selecting the language at the lobby.
> 
> * Once `Join meeting` is pressed, please join the meeting with the UI being in the locale selected in the lobby.

I don't think we have considered having a way to select the language by hand on the prejoin screen. Something to think about indeed.

**Comment by damencho** [comment]
So `LANG_DETECTION: false` at the moment on meet.jit.si. The current deploy we are doing will have that turned on.

**Comment by saghul** [comment]
Nice, thanks for confirming!
