### ISSUE TITLE
Google Calendar Add-On

### ISSUE THREAD

**Issue by npmccallum** [jitsi/jitsi-meet#7302]
Where do I find the source code for the Google Calendar Add-On? I'd like to add a feature.

**Comment by damencho** [comment]
This is still not available. As mentioned in the Community Call today, I will try to squeeze it in this week. More information https://github.com/jitsi/jidesha/issues/45 the API was recently(like a month ago) made public which allowed us to open source it.

Please when you have questions or problems, use the community forum before opening new issues.

**Comment by damencho** [comment]
https://github.com/jitsi/jidesha/issues/45#issuecomment-658827889
