### ISSUE TITLE
Listen on join button click from pre-meeting room (lobby)

### ISSUE THREAD

**Issue by omazin** [jitsi/jitsi-meet#7309]
**Is your feature request related to a problem you are facing?**
Yes, I want to do some stuff after a user joins from lobby

**Describe the solution you'd like**
`jitsiApi.on ‘joinFromLobby’, function() { … }`

**Describe alternatives you've considered**
Disable interim lobby screen

**Comment by Echolon** [comment]
Hi, thanks for reporting. Would you be so kind and describe you feature request a bit more detailed?

**Comment by omazin** [comment]
Ok, found a solution by listening on "videoConferenceJoined" event.
