### ISSUE TITLE
Video/Sound transmission and screen share only works in p2p mode

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7313]
### Description:

The transmission of video, sound and the screen sharing only works with two participants in p2p mode. If the third participant join the meeting then the complete transmission is deactivated.

### Steps to reproduce:

1. Open a new meeting
2. Join the second particpant (it works)
3. Join the third participant (it doesnt work)

### Server information:

- Jitsi Meet version: actual nightly build
- Operating System: Ubuntu 18.04 LTS
- Tested with activated and deactivated firewall

**Comment by saghul** [comment]
What logs do you see in the browser JS console?

**Comment by heikar** [comment]
Hi @saghul
The JS console says "Failed to send E2E ping request or response.".
It looks like in the background, the e2ee is per default activated (the icon in the ui is green).

**Comment by saghul** [comment]
Please gist or pastebin the full console logs at the most verbose level, there might be more than meets the eye.

**Comment by heikar** [comment]
Hi @saghul 
i hope it helps. JS console log with "verbose" level:
https://gist.github.com/heikar/44423b662d64f60675fc647cd0385d4d

**Comment by heikar** [comment]
Hi @saghul 
i have installed the current stable Version and it works perfect.
Because of this i close the issue.
