### ISSUE TITLE
Setting for video-share.enabled feature flag is not respected on mobile

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7315]
### Description:

I wanted to disable the Youtube video sharing feature on Jitsi Meet mobile devices when building from source. I read that the mobile applications ignore the config.js and interface_config.js settings, however there are [feature flags](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js) in the Jitsi Meet SDK which you can enable/disable by default. 

Unfortunately, both iOS and Android ignore the `video-share.enabled` feature flag.

### Steps to reproduce:

1. Download Jitsi Meet and follow instructions to set up mobile apps
2. On iOS, add the following line inside the `didFinishLaunchingWithOptions` in `AppDelegate.m`
```
jitsiMeet.defaultConferenceOptions = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
        ...
        [builder setFeatureFlag:@"video-share.enabled" withBoolean:NO];        # <--- this line
        ...
```

3. Run and start a call, you will see the Youtube sharing feature still enabled and working.

4. On Android, same situation in `MainActivity.java` add the following line to the function

```
private void setJitsiMeetConferenceDefaultOptions() {
        // Set default options
        JitsiMeetConferenceOptions defaultOptions
            = new JitsiMeetConferenceOptions.Builder()
            ...
            .setFeatureFlag("video-share.enabled", false)      # <--- this line
            ...
            .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);
    }
```

### Expected behavior:

Set the `video-share.enabled` feature flag to **false** and the feature is **not available** inside the mobile applications.

### Actual behavior:

Set the `video-share.enabled` feature flag to **false** and the feature is **still available** inside the mobile applications.

### Server information:

- Jitsi Meet version: iOS 20.3.0 / Android 20.3.0 build 4851575
- Operating System: iOS / Android

### Client information:

- Browser / app version: 
- Operating System: OSX 10.15.4

**Comment by saghul** [comment]
That flag has not yet been released, it was just merged today. You can build the app off master and it will work though.
