### ISSUE TITLE
Support for mac Catalyst 

### ISSUE THREAD

**Issue by jeetkapadia** [jitsi/jitsi-meet#7319]
Hi,

Jitsi works great in our project but with Xcode 11 now we have an option to build the same app which will work on mac as well. I tried to build with mac option ticket under the general tab in my project but it gave me an error by saying

`/Users/jeetkapadia/Documents/TestMac.xcodeproj Building for Mac Catalyst, but the linked and embedded framework 'JitsiMeet.framework' was built for iOS + iOS Simulator. You may need to restrict the platforms for which this framework should be linked and embedded in the target editor, or replace it with an XCFramework that supports both platforms.`

and it shows the same for webrtc:

Showing All Messages
`/Users/jeetkapadia/Documents/TestMac.xcodeproj Building for Mac Catalyst, but the linked and embedded framework 'WebRTC.framework' was built for iOS + iOS Simulator. You may need to restrict the platforms for which this framework should be linked and embedded in the target editor, or replace it with an XCFramework that supports both platforms.`

Can you provide some workaround for this?

Thanks

**Comment by Echolon** [comment]
Are you talking about the desktop client (electron)?

**Comment by jeetkapadia** [comment]
No. I am talking about mac apps

**Comment by saghul** [comment]
We have no plans to support Catalyst at this stage. First, React Native would need to properly support it: https://github.com/react-native-community/discussions-and-proposals/issues/131 then WebRTC, and then our mobile specific modules. I don't see this happening anytime soon.
