### ISSUE TITLE
Audio output not working if local camera not allow Safari and Chrome

### ISSUE THREAD

**Issue by AnthonyGies** [jitsi/jitsi-meet#7322]
### Description:
When a user connect to Jitsi on Chrome or Safari and disallow camera in the navigator popup, it cannot have sound output. On firefox that's work

### Steps to reproduce:

1. Open Jitsi Meet on safari or chrome
2. Disallow webcam authorization
3. No sound output from others users

### Expected behavior:

If you next allow camera and refresh jitsi, the output sound from others users work.

### Server information:

- Jitsi Meet version: Current version

### Client information:

- Browser / app version: Safari or Chrom
- Operating System: Mac OS all versions

**Comment by Echolon** [comment]
@AnthonyGies thanks for reporting. Please specify the Jitsi Meet version

**Comment by mrin** [comment]
I can confirm it. 
If mic permission has not granted - no audio from other participants.
Would be cool if config setting "startWithAudioMuted=true" will not ask mic permission and use "default" deviceId as output.
I also tried to apply pull request https://github.com/jitsi/jitsi-meet/pull/6638 -> yes, no mic permission request, but also no audio output too.
Version 1.0.4289 and also tried latest master branch.
