### ISSUE TITLE
Camera orientation and audio routing

### ISSUE THREAD

**Issue by rohitjagtap12** [jitsi/jitsi-meet#7326]
**Is your feature request related to a problem you are facing?**
I have a Banana Pi W2 board, on which I have my own custom app for audio/video calling which uses the jitsi Android SDK. However I am facing 2 issues.
1. A USB camera is connected to the board and is working fine for the call. But camera feeds rendered on the surface view is not as expected (rotated as -90 degrees). Tried all possible ways to set the activity's screen orientation, setting camera orientation when activity starts but not getting through it. Is there any way I can set the camera orientation? 
2. I want the audio to be routed through a Bluetooth headset. The Bluetooth headset works fine if the app is installed on some Android phone. But for the Banana Pi W2 board, it is not working. Is there any way I can get this working? Any help would be appreciated!

**Describe the solution you'd like**
1. If there's any way I can set the orientation of the camera.
2. If you could help in any way to guide me to get the Bluetooth headset working on Banana Pi W2 board for jitsi app.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
1. For camera orientation, I tried all possible ways, like setting the activity's screen orientation, setting camera orientation

**Comment by Echolon** [comment]
Do I understand correctly that you talk about the mobil android version?

**Comment by rohitjagtap12** [comment]
Yes. I have created an Android App and I am using the Jitsi's Android SDK.
