### ISSUE TITLE
Integrating with existing react-native app

### ISSUE THREAD

**Issue by rananajam1** [jitsi/jitsi-meet#7328]
**Is your feature request related to a problem you are facing?**
I want to add it to an existing app developed on React-Native

**Describe the solution you'd like**
I want to add custom styling to the video options, add more options, change chat interface UI

**Describe alternatives you've considered**
react-native-jitsi-meet

**Comment by Echolon** [comment]
Hello @rananajam1,

I have to close this as this is a support reqiest and you need to reach out to the Jitsi Community Forum please!

Anyway thank you and kind regards!

**Comment by anupamme** [comment]
@rananajam1 were you able to do custom UI development on jitsi? I am in a similar situation and want to explore how it can be done.

**Comment by rananajam1** [comment]
@anupamme i was able to acheive this, but it isnt very straightforward... but I'll still try to make a tutorial for this as soon as I find free time because i see too many people struggling with it

**Comment by anupamme** [comment]
Quick question: did you have to self-host Jitsi for this?

Also, my requirement is a bit urgent so if you could write high-level steps that would be of help as well.

Appreciate you getting back.
