### ISSUE TITLE
Adding splash to the code cloned from repo 

### ISSUE THREAD

**Issue by rananajam1** [jitsi/jitsi-meet#7329]
**Is your feature request related to a problem you are facing?**
How can I add splash screen for react native to this app, how can I change the starting point of the react native app

**Describe the solution you'd like**
Add more screens to this repository

**Describe alternatives you've considered**
React-native-jitsi-meet

**Comment by Echolon** [comment]
Same here, please see the other closed issue!

**Comment by rananajam1** [comment]
@Echolon no response on Jitsi Community Forum brought me here

**Comment by Echolon** [comment]
@rananajam1 okay I understand. However the rule is to post issues and bug reports only here. 😞

But I am only a supporter and not part of the official Jitsi Meet Team.

@saghul @damencho shall I reopen?

**Comment by rananajam1** [comment]
@Echolon that's why i posted it under feature request
