### ISSUE TITLE
Connecting to VPN while in a meeting causes user to switch to a phantom meeting alone

### ISSUE THREAD

**Issue by maxguru** [jitsi/jitsi-meet#7331]
### Description:

When one of the meeting participants connects to a VPN, they are timed out and disconnected from the point of view of other meeting participants. Meanwhile, to the user it appears that everyone else is gone and they are the only ones left in the meeting.

### Steps to reproduce:

1. User A enters meeting A
2. User B enters meeting A
3. User B connects to a VPN
4. Problems...

### Expected behavior:

User A and B should not notice anything changed.

### Actual behavior:

User A and user B both think the other party left the meeting.

### Server information:

- Jitsi Meet version: latest
- Operating System: any

### Client information:

- Browser / app version: any
- Operating System: any

### Additional information:

Zoom appears not to have this issue.

**Comment by maxguru** [comment]
This issue appears to be caused by the same problem as #7191.

**Comment by Echolon** [comment]
@maxguru Thanks for reporting! May you please provide the version number you use?

**Comment by Echolon** [comment]
@saghul I dont know really how to tag this correctly

**Comment by maxguru** [comment]
I am using the AppIamge which auto-updates (https://appimage.github.io/jitsi-meet/). However, it seems like it happens for all users, even the browser users. It is whatever version was live at the time we encountered the issue, which was recently.

**Comment by dieug** [comment]
we had seeing this effect too.
it's not so often as disconnects, but had been present some times.
