### ISSUE TITLE
Chrome autoplay policy - Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by thiennguyen2428** [jitsi/jitsi-meet#7332]
### Description:

Chrome will throw an error when users use no camera PC to join a meeting:

`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD ` . Please check file AbtractAudio.js at line 84.

The large video in conference works normally.

But, all the preview videos in the filmstrip and videos in the tile mode view showed a black view instead of the real videos from other users camera. 

### Steps to reproduce:

1.  Using no camera PCs, joining into a video call room.
2.  Observe the preview video in the filmstrip.
3.  Change into tile mode, observe the video in tile views.

### Expected behaviour:

All the preview videos in the filmstrip and videos in the tile mode view should work normally as the large video

### Server information:

- Jitsi Meet version: deploying using docker-jitsi-meet with the latest tag image 
- Operating System: CentOS Linux, version 7

### Client information:

- Browser / app version: Google Chrome, version 83.0.4103.116
- Operating System: Mac mini late 2014, macOS 10.15.4 (19E287), Darwin 19.4.0

### Additional information:

I also checked on meet.jit.si server but I could not reproduce this issue. I think that in the latest version of this server, you guys had turned on the feature 'Preview before joining meeting' requiring users to press a button 'Join meeting' so that it does not violate Google Chrome policy.

**Comment by saghul** [comment]
@jallamsetty1 We might need to add Chrome to the list of browsers that need an interaction. Can you PTAL?
