### ISSUE TITLE
Option to toggle on/off "join meeting" button

### ISSUE THREAD

**Issue by agichim** [jitsi/jitsi-meet#7334]
I loved the possibility of joining a meeting straight on, without having to click the "Join Meeting" button. Maybe introducing an option where that button can be toggled off, so the other people joining they can simply join as before the "Join Meeting" button was introduced.

**Comment by saghul** [comment]
That possibility landed yesterday so it will be available soon. It's a per-participant option, so they can choose if they want to never see the screen again or not.
