### ISSUE TITLE
Redirect rejected user back to lobby or server start screen

### ISSUE THREAD

**Issue by mhuber84** [jitsi/jitsi-meet#7337]
In a meeting with a lobby, a rejected user should be redirected somewhere. Perhaps back to the server start screen.

Currently the lobby screen is closed and only a small error box is shown to the rejected user. Everything else looks like the user has joined the session successfully. 

This should be the related code: https://github.com/jitsi/jitsi-meet/blob/master/react/features/lobby/middleware.js#L113
But my Javascript skills are too bad to support a patch... 

Tested on https://meet.ffmuc.net/

**Comment by akalana** [comment]
Hi @mhuber84 ,
Could you please let me know the steps to enable the lobby feature in Jitsi?

**Comment by mhuber84** [comment]
Hi @akalana ,
I don't know how to configure the server. But if the feature is enabled on the server (like on meet.ffmuc.net) you get the option in the session's security settings:

![grafik](https://user-images.githubusercontent.com/957178/88681567-00110580-d0f2-11ea-8168-e6b08f3adc80.png)

**Comment by akalana** [comment]
Hi @mhuber84 
I want to know, what did you do to enable that button for you. Because I got and built up the latest Git Hub repo but that feature wasn't enabled for me. That's why.

**Comment by gkdre234** [comment]
> In a meeting with a lobby, a rejected user should be redirected somewhere. Perhaps back to the server start screen.
> 
> Currently the lobby screen is closed and only a small error box is shown to the rejected user. Everything else looks like the user has joined the session successfully.
> 
> This should be the related code: https://github.com/jitsi/jitsi-meet/blob/master/react/features/lobby/middleware.js#L113
> But my Javascript skills are too bad to support a patch...
> 
> Tested on https://meet.ffmuc.net/

Hi @mhuber84 

with the following modification of middleware.js rejected user will be forwarded back to the start screen.

~~~~shell
--- jitsi-orig/jitsi-meet/react/features/lobby/middleware.js 2020-10-08 17:32:18.544057858 +0200
+++ jitsi-local/jitsi-meet/react/features/lobby/middleware.js 2020-10-08 17:38:08.648074552 +0200
@@ -15,6 +15,7 @@
     participantIsKnockingOrUpdated,
     setLobbyModeEnabled,
     startKnocking,
+    cancelKnocking,
     setPasswordJoinFailed
 } from './actions';

@@ -116,7 +117,8 @@
             appearance: NOTIFICATION_TYPE.ERROR,
             hideErrorSupportLink: true,
             titleKey: 'lobby.joinRejectedMessage'
-        }));
+        }, 5000));
+        dispatch(cancelKnocking());
     }

     return next(action);
~~~~
Maybe not completely correct,
but works for me.
