### ISSUE TITLE
Speaker order tracking through the hand-raised feature

### ISSUE THREAD

**Issue by codeofcarson** [jitsi/jitsi-meet#7344]
**Is your feature request related to a problem you are facing?**
Yes, I am unable to reliably determine the order of hands raised.

**Describe the solution you'd like**
I would like to know the order in which hands were raised so that I, as chair/moderator, can properly keep track of speaker order to ensure meetings run smoothly. A small icon beside the hand-raised icon on participant tiles with a number indicating who is next to speak would fix this issue.

**Describe alternatives you've considered**
I have attempted to keep track of it myself but when the meeting reaches 25+ people and multiple hands are raised in a short time span, it is impossible to accurately determine the correct speaker order.
I have also attempted to get other participants to keep track of whose hand was raised but this has also proved unreliable.

**Comment by ngen-brett** [comment]
This would be a great addition.
