### ISSUE TITLE
Warning sign for insecure meeting name has no tooltip on self-hosted instance

### ISSUE THREAD

**Issue by dandv** [jitsi/jitsi-meet#7348]
### Description:

The warning icon for insecure meeting names has no tooltip. On an intranet server, where there was no concern for bombings, I entered a short meeting name and started the meeting. I didn't realize why I was seeing the warning icon in the upper right corner.

### Steps to reproduce:

1. Navigate to your self-hosted Jitsi Meet instance
2. Enter a short meeting name
3. Start the meeting

### Expected behavior:

The warning icon in the upper-right corner should have a tooltip explaining what the warning is about.

### Actual behavior:

No tooltip.

![image](https://user-images.githubusercontent.com/33569/87842999-8e20fc80-c865-11ea-83d0-0bf99cad20ed.png)

### Server information:

- Jitsi Meet version: 2.0.4627-1
- Operating System: Ubuntu Linux 20.

### Client information:

- Browser / app version: Chrome 84

### Additional information:

Bug is not reproducible at https://meet.jit.si/.

**Comment by damencho** [comment]
That is fixed in latest builds. Soon stable will be updated with those.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.
