### ISSUE TITLE
Firefox upload not showing up in HD

### ISSUE THREAD

**Issue by sagz** [jitsi/jitsi-meet#7351]
### Description:
When joining meeting from Jitsi in Firefox it shows up in SD on all recipients, while Chrome works in upto HD

### Steps to reproduce:

1. Open a Jitsi Meet url on Firefox
2. Check resolution on other clients (Android, iOS, Chrome)

### Expected behavior:

HD 720p from Firefox just as it is from Chrome

### Actual behavior:

Firefox client shows up as SD even with a gigabit upload connection

![image](https://user-images.githubusercontent.com/964843/87890143-01537b80-c9ea-11ea-94f0-bb6d72cda266.png)

### Server information:

- Jitsi Meet version: Whatever is deployed on https://meet.jit.si/ as of today
- Operating System: MacOS 10.15.5 (19F101)

### Client information:

- Browser / app version: for the above screenshot, Firefox 80.0a1 (2020-07-14) (64-bit) and Chrome Version 84.0.4147.89 (Official Build) (64-bit)
- Operating System: MacOS 10.15.5 (19F101)

**Comment by jallamsetty1** [comment]
This is a bug in FF 80 where RTX has been enabled by default. Bandwidth probing using RTX has issues and this has been reported to the Mozilla guys. Do you see the same issue with FF 78 ?

**Comment by sagz** [comment]
Didn't try in FF78. Is there a bugzilla bug for this regression in FF80?

Thanks @jallamsetty1
