### ISSUE TITLE
IFrame API Most configOverwrite and interfaceConfigOverwrite don't work

### ISSUE THREAD

**Issue by MrSparklle** [jitsi/jitsi-meet#7354]
### Description:

Most params passed to configOverwrite and interfaceConfigOverwrite don't work.

Ex: 
`defaultLanguage: 'pt'` = Don't works. No matter what value you pass, interface always showed in English.

Some of `interfaceConfigOverwrite` also don't work, check example below.

### Steps to reproduce:

1. Create a index.html locally with this code:
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src='https://meet.jit.si/external_api.js'></script>
</head>

<body>
  <div id="meet"></div>
</body>
<script> const domain = 'meet.jit.si';
  const options = {
    roomName: 'Test12345',
    width: 700,
    height: 700,
    configOverwrite: {
      startWithAudioMuted: true, // ok
      defaultLanguage: 'de' // don't work
    }, 
    interfaceConfigOverwrite: { 
      MOBILE_APP_PROMO: false, // don't works 
      DEFAULT_LOCAL_DISPLAY_NAME: 'Eu', //ok
      DEFAULT_LOGO_URL: 'images/sample.png',   // dont work
      SHOW_CHROME_EXTENSION_BANNER: false, //ok
      TOOLBAR_ALWAYS_VISIBLE: true, // ok
      APP_NAME: 'THe New World', // dont  work
      JITSI_WATERMARK_LINK: 'http://www.google.com', // dont work
      LANG_DETECTION: 'false', // dont work
      SETTINGS_SECTIONS: ['devices', 'language'], //ok,
      SHOW_JITSI_WATERMARK: false, // dont work
      TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'hangup', 'profile', 'settings', 'raisehand',
        'videoquality'
      ] // ok
    },
    // this works fine
    userInfo: {
      email: 'email@jitsiexamplemail.com',
      displayName: 'John Doe',
    },
    parentNode: document.querySelector('#meet'),
  };
  const api = new JitsiMeetExternalAPI(domain, options);</script>

</html>
```
2. start server with this index.hmtl
3. open the url in Google Chrome

### Expected behavior:

All the properties needs to be configured properly 

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: Chrome Version 84.0.4147.89 (Official Build) (64-bit)
- Operating System: MacOS

### Additional information:

```
LocalStatsCollector.js:22 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ LocalStatsCollector.js:22
n @ bootstrap:19
(anonymous) @ statistics.js:1
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:1
n @ bootstrap:19
(anonymous) @ BridgeChannel.js:1
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:10
n @ bootstrap:19
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:1
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:1
n @ bootstrap:19
(anonymous) @ ActiveDeviceDetector.js:1
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:10
n @ bootstrap:19
(anonymous) @ JitsiMeetJS.js:1
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:17
n @ bootstrap:19
(anonymous) @ index.js:3
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ lib-jitsi-meet.min.js?v=4289.935:1
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1
Logger.js:154 2020-07-20T12:49:13.952Z [features/base/config] Extending config with: {"defaultLanguage":"de","startWithAudioMuted":true}
Logger.js:154 2020-07-20T12:49:13.990Z [features/base/media] Start muted: audio, 
Logger.js:154 2020-07-20T12:49:14.001Z [features/base/media] Start audio only set to false
Logger.js:154 2020-07-20T12:49:14.461Z [modules/RTC/RTCUtils.js] Audio output device set to default
Logger.js:154 2020-07-20T12:49:14.529Z [modules/RTC/RTCUtils.js] <z.newObtainAudioAndVideoPermissions>:  Using the new gUM flow
Logger.js:154 2020-07-20T12:49:14.531Z [modules/RTC/RTCUtils.js] <z.<anonymous>>:  Got media constraints:  {video: {…}, audio: {…}}
Logger.js:154 2020-07-20T12:49:15.385Z [features/base/media] Sync audio track muted state to muted
Logger.js:154 2020-07-20T12:49:15.403Z [modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[1,audio]: true
```

**Comment by saghul** [comment]
The interface_config options you kind not working are intentional. If you want those changes you need your own deployment, you cannot do that against meet.jit.si

**Comment by MrSparklle** [comment]
@saghul Ok, but this needs to be more clear in your documentation. There is no mention to any exception those these parameters. 

I clone the repository locally, and I changed some parameters directly in config.js and interface_config.js. Run `make dev`, change the script source to `<script src='https://localhost:8080/external_api.js'></script>` but it doesn't seem to have had any effect either. 

should this work?

**Comment by saghul** [comment]
No, the development server takes the config from the live deployment it points to. If you did make dev thats alpha.jitsi.net.

**Comment by Eluminati** [comment]
Well I am using an own deployment and it's not possible to use this possibility to overwrite the config. It is just ignored especially the watermarks settings.

I don't have any error on console.

**Comment by saghul** [comment]
If you are using your own deployment then edit config.js / interface_config.js directly.

**Comment by rhonz10** [comment]
I'm also using an own deployment. Is there any way to make this work without having to edit core files? Using the config overwrite enables us to dynamical change settings depending on conditions, such as language of the user.

**Comment by akalana** [comment]
Hi @saghul 
Is there any way to change the language using iFrame API?

**Comment by erikvanoosten** [comment]
I described a workaround on my blog which can be used if you deploy Jitsi with Docker: https://day-to-day-stuff.blogspot.com/2021/12/customizing-jitsi-meet-ui-in-docker.html

**Comment by erikvanoosten** [comment]
@saghul Could you please refer us to the issue where this problem is tracked?
