### ISSUE TITLE
Multiple moderators when using password based authentication

### ISSUE THREAD

**Issue by LohithBlaze** [jitsi/jitsi-meet#7355]
### Description:

When using password based authentication, if guest users are waiting for host and when the host enters the password, all the users who were waiting for host become moderators.
 ,,., ,

### Steps to reproduce:

1. I have enabled,  internal_hashed in the main virtual host.
2. Added org.jitsi.jicofo.auth.URL=XMPP:jitsi-meet.example.com to jicofo and restarted the jicofo and prosody service
3.  I enter the room StiffDirectorsEncourageSure
4.   I'm prompted for waiting for host
5.  I open another tab
6.  open the same meeting room again, StiffDirectorsEncourageSure
7.  I'm prompted waiting for host
8. I click on I am the host
9. I enter username and password.
10. Authentication is successfull.
11. Both the users are moderators

### Expected behavior:

Only the user who entered the password and gets authenticated should be moderator

### Actual behavior:

I see presence event to all the users who joined the meeting before the host, with role as moderator, due to this, all the users who were waiting for host to join are moderators

### Server information:

- Jitsi Meet version:
Prosody version 0.11.5
- Operating System:
Ubuntu 18.04.04 LTS

**Comment by 0xnor0** [comment]
This should not be closed.

**Comment by damencho** [comment]
Do you repro? On step 6. `opening new tab`, that needs to be incognito as the current session browser will reuse authentication and moderator role is expected in this case.

**Comment by 0xnor0** [comment]
In our instance we use ldap auth and everyone who was already authentificated before gets moderator role as guest in new conferences.

**Comment by damencho** [comment]
Nope, anyone that is authenticated gets a moderator.

**Comment by 0xnor0** [comment]
In this case this one can bei closed.
