### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by lilong7676** [jitsi/jitsi-meet#7361]
### Description:

I used xcode 11.6 (11E708) to compile the framework from source code, and the operation was successful according to this tutorial. But after integrating into my project, an error was reported:

### Steps to reproduce:

1. pull from last master branch
2. build framework (xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive)
3. integrated to my project and run

### Expected behavior:

Should run normally

### Actual behavior:

 [JitsiMeetSDK] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

 [JitsiMeetSDK] Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[JitsiMeetSDK] FATAL ERROR: RCTFatalException: Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), stack:
value@36:3544
<unknown>@36:841
value@36:2939
value@36:813
value@<null>:<null>

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:iOS 13.5.1

### Additional information:

I have tried to replace the sdk from jitsi-meet-sdk-samples-master with the one I generated, and the same error is reported after running, so the problem must be my packaging problem, but I don't know how to solve this problem.

**Comment by AliKarpuzoglu** [comment]
I experienced the same issue when merging the master branch into my fork

**Comment by saghul** [comment]
Does the same problem occur when using Xcode 11.5 ?

**Comment by lilong7676** [comment]
> Does the same problem occur when using Xcode 11.5 ?

I will try later🤔

**Comment by AliKarpuzoglu** [comment]
> Does the same problem occur when using Xcode 11.5 ?

I use Xcode 11.5 and I had that issue

**Comment by HuskarHuang** [comment]
android has the same problem

**Comment by saghul** [comment]
Ah wait, this is for master! Yes, this is known, it will be fixed shortly. In the interim you can use the "mobile-20.3" branch, which is the one which matches the latest release.

Sorry for the trouble.

**Comment by lilong7676** [comment]
> Ah wait, this is for master! Yes, this is known, it will be fixed shortly. In the interim you can use the "mobile-20.3" branch, which is the one which matches the latest release.
> 
> Sorry for the trouble.

mobile-20.3 branch is working normally, thanks!

**Comment by saghul** [comment]
master is now fixed too.

**Comment by zd13572538541** [comment]
I installed JitsiMeet.framework with cocopods . Run the Device (13.5.1) with Xcode 11.1 and report the following error:
[JitsiMeetSDK] TypeError: undefined is not an object (evaluating 't.replace')
[JitsiMeetSDK] Unhandled JS Exception: TypeError: undefined is not an object (evaluating 't.replace')
[JitsiMeetSDK] FATAL ERROR: RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 't.replace')

How to solve this problem？
