### ISSUE TITLE
Screenshare issue with Firefox when Video is not enabled

### ISSUE THREAD

**Issue by uppuluriaditya** [jitsi/jitsi-meet#7369]
I have been observing a screenshare issue with firefox on the https://meet.jit.si.
Here are the steps to reproduce:

- Create/Join a meeting with firefox and in the landing page disable video
- Start screen share from firefox and other users (chrome browser based users) will be able to see the screenshare without any issues
- Stop screenshare from firefox

**_Expected:_**
Other users will be able to see the screenshare stopped.
**_Actual_**:
Other users in the conference are seeing the firefox user’s screen in a stuck state.

**Comment by uppuluriaditya** [comment]
Hello All,
May i know if there is an update on this issue? Is there any estimated timeline for the fix?
Thanks in advance..

**Comment by uppuluriaditya** [comment]
@jallamsetty1 : May i know if there is an update on this issue? Is this an issue with Firefox browser itself or with jitsi-meet
Thanks in advance.

**Comment by uppuluriaditya** [comment]
@jallamsetty1 : May i know if there is an update on this issue? Is this an issue with Firefox browser?
Thanks in advance

**Comment by saghul** [comment]
I confirm the bug is still there. We'll get to it.

**Comment by prasadkadiyala** [comment]
Same issue able to reproduce with Safari

**Comment by jallamsetty1** [comment]
Fixed in the last stable release.

**Comment by jallamsetty1** [comment]
Sure, this [commit](https://github.com/jitsi/jitsi-meet/commit/870d847f5f46e1277c2d1bcd6d320f9df287142d) should have all the fixes.
