### ISSUE TITLE
not able to set avatar in jitsi sdk ios

### ISSUE THREAD

**Issue by maneesh12345** [jitsi/jitsi-meet#7378]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by Echolon** [comment]
@maneesh12345 Sorry for being a bit strict but please fill out the issue template first. When done I will reopen your issue. If this is a support request please go to the Jitsi Community website. Thank you!
