### ISSUE TITLE
User's statistic in a conference

### ISSUE THREAD

**Issue by filhocf** [jitsi/jitsi-meet#738]
Is possible to measure the number of unique users in a conf? I tried to put a piwik's script to track the number of users in a room (a subfolder) without success.

We have some thing to get this number? I think that not, it can be a good feature, present in other tools like Webex or Gotomeeting.

**Comment by damencho** [comment]
Could you please discuss problems and features on the mailinglist before opening issues. Participants in the current conference are seen in the contactlist, and the button that opens the contact list shows the number of participants that are currently in the conference.
