### ISSUE TITLE
Meta - overview

### ISSUE THREAD

**Issue by Echolon** [jitsi/jitsi-meet#7381]
Dear Community :heart:

hereby an overview for the current important issues for Jitsi Meet is provided. :tada:

:spiral_notepad: Please, consider this as an **orientation** and not a holistic or complete list. It also help you to see if your issue or feature request is already known. As you can see we collected significant issues, where other existing ones are neglected for the moment. Of course the overview will be improved and adjusted by time. Also consider the search via clicking [labels](https://github.com/jitsi/jitsi-meet/labels).

:sos: Please go first to the [Jitsi Community](https://community.jitsi.org/) to ask for general support before opening an issue!

:computer_mouse: Click on the issue number to proceed to the entry of interest.

:exclamation: Please be reminded that this is neither official nor a milestone or working plan.
________

**First of all please review these issues if you have this issue!**

- Meta - camera issues [#5425]
- Meta - recording problems [#5403]

**Top Feature Requests by :+1:** [[Link](https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request+sort%3Areactions-%2B1-desc)]

- Breakout Rooms [#5550]
- Shared drawing canvas / whiteboard [#5295]
- Screen sharing on mobile app [#5252 for iOS, #6497 for Android]
- Virtual backgrounds [#5860]
- Allow streaming to general RTMP endpoint [#2829]
- Define tile view as default [#5764]
- Integration with CalDav [#4719]
- Allow Streaming to WebRTC [#6156]
- Emoji reactions [#5217]
- Promote other moderators [#7041]

**Highly frequented issues** [[Link](https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc)]
- Translations [#5056]
- Insecure Room names [#5407]
- VR mode [#5269]

**Top Community Winners by :+1:** [[Link](https://github.com/jitsi/jitsi-meet/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)]
_Top features excluded_

- Safety concerns exposing users [#5653]
- High Client CPU Load [#5464]
- Do not always mute when a Youtube video is playing [#6390]
- Meeting name is insecure by default [#5407]
- Create a CHANGELOG.md file [#6168]

**Top Problems by :+1:**
- High Client CPU Load [#5464]
- Firefox: Audio input device not selectable [#2835]
- Website is melting CPU! [#5816]
- Configurable default start-up lower video resolution [#5256]
- DEFAULT_BACKGROUND is not getting applied [#6307]

**Top Mobile by :+1:** [[Link](https://github.com/jitsi/jitsi-meet/issues?q=is%3Aopen+is%3Aissue+sort%3Areactions-%2B1-desc+label%3Amobile)]
_Other Top's excluded_

- Password not enforced if someone is already waiting for host [#5720]
- Android App Rejects Let's Encrypt Chain [#5589]
- Raise hand icon missing in iOS and Android [#5197]
- Move "Toggle camera" button out from the Menu [#6004]
- Voice - Video toggle design issue [#7087]
- Auto-join default meeting [#5522]
- Better cropping [#6010, #6011]

**_WIP_** _Suggestions welcome!_

**Comment by Echolon** [comment]
@saghul that is a first start. You can pin it to the top. I will expand and update this by time. Suggestions welcome!

Next I will try to summarize related issues.

**Comment by saghul** [comment]
This is incredibly useful, thank you so much!

**Comment by nimaam** [comment]
I can add breakout to your jitsi meet instance with local recording and etherpad to full funtionality, and you can have control to all of them in your API, I can handle a webinar mode that guest can not sea each other too, I made a change to jitsi alot and now is ready to others but not for free and not expensive.

Break out
Local Record no jibri needed
Local Snapshopt
Etherpad
HIde guests from guests and moderator sea all
stream to youtube/instagram/facebook and all rtpm server

**Comment by rugk** [comment]
BTW (I did not want to open an issue for that 8as it is not a technical thing), so I've use the forum, but [thanks to you all for creating Jitsi](https://community.jitsi.org/t/thanks-to-all-you-creating-jisti-happy-ilovefs-day-2021/93385?u=rugk). This of course includes every contributor or community member! You make this thing rock! The full forum post is available at the link.

So [happy ILoveFs Day 2021](https://fsfe.org/activities/ilovefs/)!

**Comment by pierreozoux** [comment]
@saghul could you give me rights to close and edit issues? I could have cleaned a bit the post on top (virtual backgrounds for instance) :)

**Comment by saghul** [comment]
Thanks for volunteering @pierreozoux ! Will do!

**Comment by saghul** [comment]
I think this issue has run its course. If we ever need a new similar one we shall open a new one.
