### ISSUE TITLE
OPUS max bitrate cannot be overridden due to config key mismatch

### ISSUE THREAD

**Issue by andorardo** [jitsi/jitsi-meet#7384]
According to libjitsi:
https://github.com/jitsi/lib-jitsi-meet/blob/cf584f56e47ed918b196f93b9fff16de70d155ea/modules/xmpp/moderator.js#L271

shouldn't the config key be **`opusMaxAverageBitrate`**, not `opusMaxAvgBitrate`?
https://github.com/jitsi/jitsi-meet/blob/a23dac2ab6191e007efe5c8253ab7e4a7bcffa1b/config.js#L119

Presumably the configWhitelist would also need to be updated
https://github.com/jitsi/jitsi-meet/blob/b0188a71841c966122c3cce8c7023b7de8e32a82/react/features/base/config/configWhitelist.js#L128

**Comment by claysauruswrecks** [comment]
Even when changed, and the changes incorporating modified offers, the `maxaveragebitrate` was not present in the SDP offer in browser console.

**Comment by saghul** [comment]
The option name is bad for sure. Fixed in https://github.com/jitsi/jitsi-meet/pull/7386
