### ISSUE TITLE
Removing (Hide) the option "share a YouTube video" doesn't work on iOS and Android SDK

### ISSUE THREAD

**Issue by asnagni** [jitsi/jitsi-meet#7390]
### Description:

Hello,
   I’m trying to disable (hide) the “Share a Youtube video” option in menu but it doesn’t work. The strange thing is that I can successfully disable (hide) the other options that I don't them to be visible. Please see the code that I have for iOS and Android in the "Additional information" section.

Thank you for helping.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

When I set the Feature Flag "share a YouTube video" to false, the option should not appear in the menu. Please see the code for iOS and Android

### Actual behavior:

When I set the "Share a YouTube video" Feature Flag to false it will always be accessible. 

### Server information:

- Jitsi Meet version:  sdk-releases-2.9.3
- Operating System:  iOS 13.6 and Android

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

This is the code for iOS:

            builder.serverURL = [NSURL URLWithString:@"https://meet.jit.si"];
            builder.room = self.room;
            builder.subject = self.subject;
            builder.audioMuted = NO;
            builder.videoMuted = NO;
            [builder setFeatureFlag:@"toolbox.alwaysVisible" withBoolean:NO];
            [builder setFeatureFlag:@"raise-hand.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"invite.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"video-share.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"live-streaming.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"meeting-password.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"pip.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"video-share.enabled" withBoolean:NO];
            [builder setFeatureFlag:@"recording.enabled" withBoolean:NO];

This is the code for Android:
        URL url = buildURL("https://meet.jit.si");

        Builder builder = new Builder();
        builder.setServerURL(url);
        builder.setRoom(room);
        builder.setSubject(subject);
        builder.setAudioMuted(false);
        builder.setVideoMuted(false);
        builder.setWelcomePageEnabled(false);

        builder.setFeatureFlag("toolbox.alwaysVisible",false);
        builder.setFeatureFlag("invite.enabled",false);
        builder.setFeatureFlag("raise-hand.enabled",false);
        builder.setFeatureFlag("video-share.enabled",false);
        builder.setFeatureFlag("live-streaming.enabled",false);
        builder.setFeatureFlag("recording.enabled",false);
        builder.setFeatureFlag("meeting-password.enabled",false);
        builder.setFeatureFlag("pip.enabled",false);
        builder.setFeatureFlag("video-share.enabled",false);

**Comment by saghul** [comment]
That flag landed after the branch for 2.9.3 was cut, so it's not part of the release.

**Comment by asnagni** [comment]
Ok, thank you for the feedback.
