### ISSUE TITLE
LoadBalancing

### ISSUE THREAD

**Issue by OsamaBadr01** [jitsi/jitsi-meet#7391]
Hello

I have this setup HAProxy and 2 jitsi meet i have problem the partciapant don’t go to the same room while haproxy configured with balance url_param room

This is HAProxy configuration

`frontend haproxynode
bind *:80
bind *:443 ssl crt /etc/haproxy/certs/domainname.pem
http-request redirect scheme https unless { ssl_fc }
mode http
default_backend backendnodes

backend backendnodes
mode http
balance url_param room
option httpchk
hash-type consistent
http-request set-header X-Forwarded-Port %[dst_port]
http-request add-header X-Forwarded-Proto https if { ssl_fc }
option httpchk HEAD / HTTP/1.1\r\nHost:localhost
server node1 x.x.x.x:4444 check ssl verify none
server node2 x.x.x.x:4444 check ssl verify none`

Thanks

**Comment by Echolon** [comment]
@OsamaBadr01 Hi,

would you be so kind an fill out the provided issue template?

**Comment by OsamaBadr01** [comment]
I can't find it can you provide it? Thanks

**Comment by Echolon** [comment]
When you click "New Issue" templates will be provided. However, I think you should actually head for help in the Jitsi Community Portal first. I think your problem is not a bug, right?

**Comment by OsamaBadr01** [comment]
It isn't a bug but i asked many times in jitsi community no one answered the question
