### ISSUE TITLE
setVideoQuality() only changing receiver video not sender video in Mobile

### ISSUE THREAD

**Issue by bhavesh18** [jitsi/jitsi-meet#7393]
Path:- jitsi-meet-stable-jitsi-meet_4857/react/features/video-quality/actions.js

export function setVideoQuality(frameHeight: number) {
    return (dispatch: Dispatch<any>, getState: Function) => {
        const { conference, maxReceiverVideoQuality } = getState()['features/base/conference'];

        if (frameHeight < VIDEO_QUALITY_LEVELS.LOW) {
            logger.error(`Invalid frame height for video quality - ${frameHeight}`);

            return;
        }
        conference.setReceiverVideoConstraint(Math.min(frameHeight, maxReceiverVideoQuality));
        conference.setSenderVideoConstraint(Math.min(frameHeight, VIDEO_QUALITY_LEVELS.HIGH))
            .catch(err => {
                logger.error(`Set video quality command failed - ${err}`);
            });
    };
}

export const VIDEO_QUALITY_LEVELS = {
    HIGH: 720,
    STANDARD: 360,
    LOW: 180
};

Setting different VIDEO_QUALITY_LEVELS changing only receiver video resolutions in mobile not the sender resolution, I only see the same resolution of video on web sending through mobile event after setting different video quality.

How can I change the video quality of mobile in real time like web do?
![Screenshot 2020-07-23 at 8 17 54 PM](https://user-images.githubusercontent.com/22396203/88300896-a1c6da00-cd21-11ea-9f2c-4b5f6c83e544.png)

Is this feature available for mobile ?

**Comment by saghul** [comment]
This feature is not currently available on mobile. You can control the send (and receive) resolution with the "resolution" feature flag.

**Comment by bhavesh18** [comment]
Hi, thank you for the information.

- Can you please give me brief or example on how to use this "resolution" feature flag?
- Is there any action to dispatch to set the resolution?

I can see the flag (Path: jitsi-meet-stable-jitsi-meet_4857/react/features/base/flags/constants.js)
/**
 * Flag indicating the local and (maximum) remote video resolution. Overrides
 * the server configuration.
 * Default: (unset).
 */
export const RESOLUTION = 'resolution';

**Comment by Malik464** [comment]
Hi, I also tried to use this flag to set the resolution in mobile but couldn't find anything.

**Comment by saghul** [comment]
See: https://github.com/jitsi/jitsi-meet/commit/f32140c4b7f4bc9654067cb68882118bbdfae952
