### ISSUE TITLE
React js installation for web

### ISSUE THREAD

**Issue by shubhamvishwakarma19** [jitsi/jitsi-meet#7397]
### Description:

There is no documentation for installation in the react js and also there is no commands available in the package.json file how can i run. Anyone can help please how can i run this project in my local machine i want to run react code for web.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

i want to create react js based jitsi web demo  and customize the UI

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Take a look here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web
