### ISSUE TITLE
when using Android SDK, will call 4887763385474123456??

### ISSUE THREAD

**Issue by BreakerSAMA** [jitsi/jitsi-meet#7407]
when using Android SDK, will call number:4887763385474123456

https://github.com/jitsi/jitsi-meet-sdk-samples/

I just want to use video conferencing. Don't want to use the phone dialing . What should I do?

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by Echolon** [comment]
@saghul
