### ISSUE TITLE
Customize Layout Android SDK with layout xml / java

### ISSUE THREAD

**Issue by amirisback** [jitsi/jitsi-meet#7413]
**Is your feature request related to a problem you are facing?**
I need customize the ui for video conference, replacing audio button with my own button style

**Describe the solution you'd like**
i need function for setup drawable button for ui (ex: setAudioButtonRes(R.drawable.my_own_audio_button))

**Describe alternatives you've considered**
make UI from xml especially for android SDK

Thank you

**Comment by Echolon** [comment]
@saghul is this a suitable feature request?

**Comment by amirisback** [comment]
Used to develop my application with my own design

**Comment by saghul** [comment]
The mobile apps UI is built with React Native. Thus you need to modify the code in this repo (in JavaScript) and then rebuild the SDK.

**Comment by 06065044** [comment]
> The mobile apps UI is built with React Native. Thus you need to modify the code in this repo (in JavaScript) and then rebuild the SDK.


Please tell me where is the function code for inviting others, now we want to call this function on the java side。Thanks

**Comment by Shahzadali062** [comment]
@saghul   i want change color of chat in dark theme in react native android
