### ISSUE TITLE
Can't build JitsiMeet with XCode 12.0 beta 3

### ISSUE THREAD

**Issue by javikr** [jitsi/jitsi-meet#7415]
### Description:

After installing XCode 12.0 (beta 3) and trying to compile a project that includes the cocoapod JitsiMeet SDK, I can not build.

### Steps to reproduce:

1. Install XCode 12.0 beta 3 from iTunes Developer Center.
2. Open a project with a dependency of JitsiMeet SDK as a cocoapod and 'import JitsiMeet'
3. Build in iOS Simulator 14.0 & iOS Simulator 12.4

### Expected behavior:

Build OK.

### Actual behavior:

Following errors appear in XCode:

```
'PiPViewCoordinator' is not a member type of 'JitsiMeet'
'PiPViewCoordinatorDelegate' is not a member type of 'JitsiMeet'
'AnimationCompletion' is not a member type of 'JitsiMeet'
'JMCallKitListener' is not a member type of 'JitsiMeet'
```
In file: x86_64-apple-ios-simulator.swiftinterface

### Client information:

- Jitsi Meet version: 2.9.3
- Operating System: macOS Catalina 10.15.5

**Comment by Echolon** [comment]
@javikr can you please fill out the bug report template when creating a new issue? That would help a lot!

**Comment by javikr** [comment]
> @javikr can you please fill out the bug report template when creating a new issue? That would help a lot!

Sorry. I have updated the original post.

**Comment by saghul** [comment]
The SDK is currently built with Xcode 11.4 and works ok with 11.5. I'd suggest you try to build the SDK yourself with 11/5 and try to use it with 12.

**Comment by Echolon** [comment]
@javikr have you been able to try out the suggestion?

**Comment by javikr** [comment]
> @javikr have you been able to try out the suggestion?

Sorry but I haven't had time to try it yet

**Comment by javikr** [comment]
Finally I could build iOS 14 and XCode 12 beta 3.

I have follow the steps described here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile

I have built Jitsi Meet iOS framework in XCode 12 and then drag and drop JitsiMeet.framework stored in 'sdk/Products' to my project.

The build is OK now, but when I launch the app on a simulator it crashes with the following error:
`dyld: Library not loaded: @rpath/WebRTC.framework/WebRTC
  Referenced from: /Users/javieraznar/Library/Developer/CoreSimulator/Devices/A2952149-88D8-44F1-963F-78285A900B9F/data/Containers/Bundle/Application/8A88206A-FA20-48BB-BF94-E5EB29D8F54E/idealista.app/Frameworks/JitsiMeet.framework/JitsiMeet
  Reason: image not found`

**Comment by javikr** [comment]
Ok! Finally I have the project compiling and running fine! 

I have also added 'WebRTC.framework' folder from the Jitsi Meet project to my project dir.

**Comment by SBiOSoftWhare** [comment]
This error is due to an Apple bug, you can find more information in this [discussion](https://forums.developer.apple.com/thread/123253) on the Apple Developer Forum. Normally with [Module Stability](https://swift.org/blog/abi-stability-and-more/), currently used for the iOS Jitsi binary framework, we should be able to use a binary framework built with Xcode 11 and Swift 5.1 with Xcode 12 and Swift 5.3 without any issue, this is the goal of the feature.

Regarding the Apple issue the current solution (explained in the Apple forum) is to remove `JitsiMeet` module prefix in all `.swiftinterface` files located [here](https://github.com/jitsi/jitsi-meet-ios-sdk-releases/tree/master/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule).

For example I've been able to build the JitsiMeetSDK 2.8.1 (built with Swift 5.2.2) with Xcode 12 (using Swift 5.3) by removing the module prefix `JitsiMeet` everywhere in the `.swiftinterface` files.

Below you can find a concrete example of the content of `x86_64-apple-ios-simulator.swiftinterface` file of JitsiMeetSDK 2.8.1 I manually modified:

```
// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
// swift-module-flags: -target x86_64-apple-ios11.0-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -O -module-name JitsiMeet
import AVKit
import CallKit
import Foundation
@_exported import JitsiMeet
import Swift
public typealias AnimationCompletion = (Swift.Bool) -> Swift.Void
public protocol PiPViewCoordinatorDelegate : AnyObject {
  func exitPictureInPicture()
}
public class PiPViewCoordinator {
  public var dragBoundInsets: UIKit.UIEdgeInsets {
    get
    set
  }
  public enum Position {
    case lowerRightCorner
    case upperRightCorner
    case lowerLeftCorner
    case upperLeftCorner
    public static func == (a: PiPViewCoordinator.Position, b: PiPViewCoordinator.Position) -> Swift.Bool
    public var hashValue: Swift.Int {
      get
    }
    public func hash(into hasher: inout Swift.Hasher)
  }
  public var initialPositionInSuperview: PiPViewCoordinator.Position
  public var pipSizeRatio: CoreGraphics.CGFloat
  weak public var delegate: PiPViewCoordinatorDelegate?
  public init(withView view: UIKit.UIView)
  public func configureAsStickyView(withParentView parentView: UIKit.UIView? = nil)
  public func show(completion: AnimationCompletion? = nil)
  public func hide(completion: AnimationCompletion? = nil)
  public func enterPictureInPicture()
  @objc public func exitPictureInPicture()
  public func resetBounds(bounds: CoreGraphics.CGRect)
  public func stopDragGesture()
  open func configureExitPiPButton(target: Any, action: ObjectiveC.Selector) -> UIKit.UIButton
  @objc deinit
}
@_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class JMCallKitProxy : ObjectiveC.NSObject {
  @objc public static var enabled: Swift.Bool {
    @objc get
    @objc set
  }
  @objc public static func configureProvider(localizedName: Swift.String, ringtoneSound: Swift.String?, iconTemplateImageData: Foundation.Data?)
  @objc public static func isProviderConfigured() -> Swift.Bool
  @objc public static func addListener(_ listener: JMCallKitListener)
  @objc public static func removeListener(_ listener: JMCallKitListener)
  @objc public static func hasActiveCallForUUID(_ callUUID: Swift.String) -> Swift.Bool
  @objc public static func reportNewIncomingCall(UUID: Foundation.UUID, handle: Swift.String?, displayName: Swift.String?, hasVideo: Swift.Bool, completion: @escaping (Swift.Error?) -> Swift.Void)
  @objc public static func reportCallUpdate(with UUID: Foundation.UUID, handle: Swift.String?, displayName: Swift.String?, hasVideo: Swift.Bool)
  @objc public static func reportCall(with UUID: Foundation.UUID, endedAt dateEnded: Foundation.Date?, reason endedReason: CallKit.CXCallEndedReason)
  @objc public static func reportOutgoingCall(with UUID: Foundation.UUID, startedConnectingAt dateStartedConnecting: Foundation.Date?)
  @objc public static func reportOutgoingCall(with UUID: Foundation.UUID, connectedAt dateConnected: Foundation.Date?)
  @objc public static func request(_ transaction: CallKit.CXTransaction, completion: @escaping (Swift.Error?) -> Swift.Void)
  @objc deinit
}
@objc public protocol JMCallKitListener : ObjectiveC.NSObjectProtocol {
  @objc optional func providerDidReset()
  @objc optional func performAnswerCall(UUID: Foundation.UUID)
  @objc optional func performEndCall(UUID: Foundation.UUID)
  @objc optional func performSetMutedCall(UUID: Foundation.UUID, isMuted: Swift.Bool)
  @objc optional func performStartCall(UUID: Foundation.UUID, isVideo: Swift.Bool)
  @objc optional func providerDidActivateAudioSession(session: AVFoundation.AVAudioSession)
  @objc optional func providerDidDeactivateAudioSession(session: AVFoundation.AVAudioSession)
  @objc optional func providerTimedOutPerformingAction(action: CallKit.CXAction)
}
extension PiPViewCoordinator.Position : Swift.Equatable {}
extension PiPViewCoordinator.Position : Swift.Hashable {}
```

A post process with a script after the framework generation can be a solution while waiting for Apple to fix the issue. I don't know if there is another way to solve that. Otherwise I can open a dedicated issue for this annoying bug if you prefer.

**Comment by saghul** [comment]
Sorry, I forgot to close this. The latest SDK (2.10) has been built with Xcode 12, with is the version we'll be using henceforth.

**Comment by Dewsworld** [comment]
I am using XCode 12 beta 3, causing the same issue. Please help

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by Dewsworld** [comment]
> What SDK version are you using?
Xcode 12.2 beta 3

**Comment by saghul** [comment]
I mean Jitsi Meet SDK, not Xcode, sorry I wasn't specific.

**Comment by Dewsworld** [comment]
> I mean Jitsi Meet SDK, not Xcode, sorry I wasn't specific.

2.10

**Comment by saghul** [comment]
I haven't tested Xcode 12.2, you might need to compile it yourself with that version.

**Comment by naeemAkee** [comment]
Hello @saghul hope you are fine. I also have same problem. I'm using Xcode 12.2 and JitsiSDK 2.10.2

But I faced same error.

<img width="1120" alt="Screenshot 2020-12-09 at 11 11 02 PM" src="https://user-images.githubusercontent.com/43524143/101669495-d094e100-3a73-11eb-9c60-35952e8eb728.png">

**Comment by nathansdev** [comment]
@naeemAkee were you able to fix it? I am also facing the same issue. 
Xcode 12.3 and swift 5.3.2
