### ISSUE TITLE
When using screen sharing on the computer, the application does not display the screen correctly.

### ISSUE THREAD

**Issue by Dmxy** [jitsi/jitsi-meet#7419]
Hello:
    When I use screen sharing on my computer, if I select enter tile view, the screen will be lost on the app. 
 _like this_
#
![enterTileViewError](https://user-images.githubusercontent.com/9995805/88765842-b7b51e80-d1a9-11ea-8689-efe1465a3a1d.jpg)

    And when I select exit tile view, the main screen will return to normal, but the small window below will lose the screen.
![exitTileViewError](https://user-images.githubusercontent.com/9995805/88766081-02369b00-d1aa-11ea-8dbe-004ca763da88.PNG)

    If I use a computer camera to capture images, everything is OK.
![exitTileView](https://user-images.githubusercontent.com/9995805/88766005-e7642680-d1a9-11ea-9895-d79b047de0f7.PNG)

    I used this version of jitsi-meet in my android app:
            maven {
                     url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
            }

**Comment by saghul** [comment]
This is the currently intended behavior on mobile (screen-share is only shown in stage view) but we are changing that here: https://github.com/jitsi/jitsi-meet/pull/7339
