### ISSUE TITLE
Publish React [Native] NPM Package

### ISSUE THREAD

**Issue by bennythomps** [jitsi/jitsi-meet#7424]
There is a great amount of functionality in this code base with React & React Native functionality that would be great to take advantage of in custom development.

It would be great if this functionality could be published as a standalone package to use in custom applications.

Currently the only option, at least for React Native, is https://github.com/skrafft/react-native-jitsi-meet which is a very lightweight implementation of existing functionality already available in this codebase.

**Comment by saghul** [comment]
Unfortunately our codebase is not (yet) ready for consumption as an npm package.

We tailored the design for consumption by native apps, and that’s what the module you mention does, which is not ideal for a number of reasons.

We may get there one day, but this is not currently in our roadmap, sorry.
