### ISSUE TITLE
Lobby and password not working simultaniously

### ISSUE THREAD

**Issue by alternadom** [jitsi/jitsi-meet#7428]
### Description:

When we activate Lobby and put a password, the password is not working...

Just a password ✅ 
Just lobby ✅ 
Lobby and password ❌

### Steps to reproduce:

1. Activate lobby
2. Put a password
3. Try to connect with a guest

### Expected behavior:

The guest should join the room...

### Actual behavior:

Return "Password invalid"

### Server information:

- Jitsi Meet version: Master

### Client information:

- Browser / app version: Chrome
- Operating System: MacOSX

**Comment by saghul** [comment]
Can you reproduce this with beta.meet.jit.si? (it has the lobby available)

**Comment by alternadom** [comment]
I was looking for that kind of link after meet.jit.si lost the lobby! Thanks

To answer at your question, no I can't reproduce.. and i don't know why 😕

**Comment by Echolon** [comment]
@alternadom I will close this. If it still appears we will reopen, ok?

**Comment by alternadom** [comment]
Is it possible to see the cfg.lua for beta.meet.jit.si ? 
Because our installation is based on master and the problem persists 😢

**Comment by saghul** [comment]
We don't have any special config / commits nor we are aware of an issue that needs fixing. Can you share your config and live instance so we can take a look?

**Comment by alternadom** [comment]
Sorry, it is not possible, we are in developpement and the live instance is not open to the world 😢

**Comment by mqureshi831** [comment]
Hi All,

I am having the same issue. In addition, when guest joins the room, they are being given moderator rights.

What I am also looking for is to completely remove the option of having to enable the lobby and have the lobby set to true at all times.  Is it possible to achieve this requirement through backend?

Thank you very much and I appreciate all the help!

**Comment by Noext** [comment]
> I am having the same issue. In addition, when guest joins the room, they are being given moderator rights.

same here, even with jwt auth enable, guest without token are moderator when the join a room
