### ISSUE TITLE
UI option to pin specific user to override channelLastN

### ISSUE THREAD

**Issue by SriramScorp** [jitsi/jitsi-meet#7429]
As per [lastn documentation](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/last-n.md#pinning), pinning a specific user/endpoint requires sending an event through the LastN data channel. It would be better if there is an option in the UI to pin an endpoint. Is there already such an option I'm not aware of?

**Comment by Echolon** [comment]
Hey @SriramScorp,
please refer to the communtiy forum first!

I have to close this, sorry!

**Comment by saghul** [comment]
Highlighting a user by clicking on their thumbnail will pin it.

**Comment by SriramScorp** [comment]
FYI, it was a feature request. Infact, I have searched the community but didn't find any mention of a UI option to pin a participant. And I had already tried clicking/selecting a participant's thumbnail to pin them, but that didn't work. When I do that, the participant is highlighted but I'm not receiving their video. I can only see their avatar.
