### ISSUE TITLE
Video will not work

### ISSUE THREAD

**Issue by SamBflint** [jitsi/jitsi-meet#7434]
I use ManyCam virtual webcam to get my unique webcam to work (Ps3 Camera lol) but regardless it works everywhere including facebook,  but I cant use it on videochat,  Not sure what Github has to do with this but whatever, I was directed here.  Anyways, I go to google chrome settings and I set the website to "Allow" my webcam.  Should work, but doesn't still.  Please help Thanks.

**Comment by Echolon** [comment]
I will close this with reference to this https://github.com/jitsi/jitsi-meet/issues/5425

Please fill out the template and provide a detailed report. Also see the Jitsi Meet community website!
