### ISSUE TITLE
Screen Sharing of Application Window & Entire Screen- Problem faced in Linux

### ISSUE THREAD

**Issue by AshiqMehmood** [jitsi/jitsi-meet#7437]
### Description:

Even though i resolved the problem  using an alternate method, i had to report this issue for collective good. When I tried to share my screen through jitsi meet, i could'nt share the entire screen of my computer or could possibly share one of application window other than the browser window. The browser window and its tabs were perfectly alright.
### Steps to reproduce:

1.  Open Jitsi Meet in Browser. 
2.  Click on Screen Sharing button. There you can find 3 options.
3. Select 'Your Entire Screen' option and click on Share button.

### Expected behavior:

Inorder to share any specific application window other than browser window, we can select it from the panel options.

### Actual behavior:
1) When sharing full screen, a black screen with mouse pointer appears.
![rsz_1screenshot_from_2020-08-01_20-24-10](https://user-images.githubusercontent.com/47411302/89105581-de8c8280-d43f-11ea-8d45-2f004fd1a959.jpg)

2) When searching for a particular application window to share, only browser is listed. Not able to share other applications. 
![rsz_screenshot_from_2020-08-01_20-26-36](https://user-images.githubusercontent.com/47411302/89105595-f06e2580-d43f-11ea-8515-41e9b45c7c65.jpg)

### Client information:

- Browser version: Chromium Version 83.0.4103.116  & Firefox 68.10.0esr (64-bit)
- Operating System: Linux- Debian Buster(64 bit) with Gnome Desktop.

### Alternate Solution found ! 
I did some research on this topic and found out that this occurs because of linux desktop environment using 'Wayland' as its xdg-session-type.

- I checked my current desktop environment using this command:
  echo $XDG_SESSION_TYPE

- Then I re-started my Desktop Environment using the option 'Gnome on Xorg' instead of default 'Gnome. 
**([these options were available on user login page on startup, you can find an icon usually a 'gear' near to Sign-In button')
![image135](https://user-images.githubusercontent.com/47411302/89106367-eac80e00-d446-11ea-929b-2046b56bdbef.png)

- Finally i opened the same browser to find the sharing screen to be Perfectly WORKING !

![rsz_screenshot_from_2020-08-01_21-57-35](https://user-images.githubusercontent.com/47411302/89105838-607dab00-d442-11ea-9207-473f6d4bdb7f.png)

Please check out the issue. Hope this document helps to improve software in all aspects. Thanks !

**Comment by atrent** [comment]
![screen-2020-08-25-20-20-57](https://user-images.githubusercontent.com/412584/91216892-f8577780-e716-11ea-9404-f226a6d12710.png)

my case is similar, I can share the entire screen but when I try to share a single application the tab is always empty (see screenshot), on Debian Sid with i3wm, it happens under both Chromium (Version 83.0.4103.116), using Chrome and Firefox, I've tried with --temp-profile, with another user and with another wm

other users in the same confcall can share a single app, so I think it's my config fault, but I'm out of debugging options, can you suggest something I can try?

**Comment by atrent** [comment]
I SOLVED my problem, it was a defective locales package, reinstalled it and everything works now.

I discovered it since I had a similar "window enumeration problem" with OBS showing only "unknown" labels, then (after searching similar problems) I stumbled onto 'rofi' (a dmenu replacement) that gave a "xkbcommon: ERROR: couldn't find a Compose file for locale..." error that suggested the defective locale.

**Comment by ToxicDragon** [comment]
I face the exact same issue: Using Wayland on Ubuntu 20.10 (Gnome 3.38.1) I can only share black screens with the mouse pointer on them. On the other hand I can share browser tabs and some applications, although it seems that GTK 3 applications that make use of Client Side decorations (CSD) and implicitly run under Wayland (so not XWayland) can not even be chosen in the sharing menu.

When using the X11 session sharing works perfectly fine.

So my guess is that there are some problems with Wayland and possible webrtc in general and / or the pipewire application in general. It would be really helpful if jitsi devs could have setup that like mine to also see the problem themselves.

**Comment by drmaniac** [comment]
Share screen with wayland needs some additional work for now. The reason for that is that an additional application is required (xdg-desktop-portal) to allow screen sharing, and it it required to enable 'webrtc-pipewire-capturer' in chrome. 

At first you have to install the correct  xdg-desktop-portal version
- xdg-desktop-portal-gtk (gnome)
- xdg-desktop-portal-kde (KDE)
- xdg-desktop-portal-wlr (wlroots based compositor)

And in chrome you have to enable WebRTC PipeWire support
chrome://flags/#enable-webrtc-pipewire-capturer
or start chrome from command line with 
chrome --enable-features=WebRTCPipeWireCapturer

source: 
https://wiki.archlinux.org/index.php/PipeWire#WebRTC_screen_sharing

**Comment by ToxicDragon** [comment]
I think this issue should be reopened, because not fixed yet (if I interpret the comments correctly).

@drmaniac

**Comment by cldershem** [comment]
I still have this same issue over a year later. I'm more than happy to give debugging info if anyone can point me into the right direction.

**Comment by damencho** [comment]
This is a browser issue. You need to report it to the browser issue tracker.
