### ISSUE TITLE
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.facebook.hermes.BuildConfig found in modules hermes-0.2.1-runtime.jar 

### ISSUE THREAD

**Issue by nishantt12** [jitsi/jitsi-meet#7438]
Jitsi SDK version: 2.9.3

I am using Jitsi in Rocket chat application, I am getting 

`java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.facebook.hermes.BuildConfig found in modules hermes-0.2.1-runtime.jar (com.facebook:hermes:0.2.1) and hermes-debug-runtime.jar (hermes-debug.aar)
`

I have excluded hermes from Jitsi sdk using `exclude group: 'com.facebook',module:'hermes'` but if I do this my app becomes laggy and start crashing.

can let me know how can I resolve this issue?

**Comment by Echolon** [comment]
@nishantt12 can you please fill you the issue template properly?

**Comment by Echolon** [comment]
@nishantt12 and at least provide a better title?

**Comment by Echolon** [comment]
@nishantt12
