### ISSUE TITLE
how to add rtmp to WebRTC conference

### ISSUE THREAD

**Issue by tzezlcy** [jitsi/jitsi-meet#7440]
Now, we want add a rtmp to conference,  but we don't know how to do it.
 
Can you give us any advice?
       
Thanks

**Comment by saghul** [comment]
Please use our community for such questions. We don't currently have RTMP source support, so your best avenue today would be to turn that into a fake webcam device and use a headless Chrome browser (or electron, or puppeteer) to join the meeting.
