### ISSUE TITLE
vct.testsrv.gwdg.de discontinued

### ISSUE THREAD

**Issue by julianladisch** [jitsi/jitsi-meet#7442]
### Description:

GWDG has discontinued their Jirsi Meet Instance vct.testsrv.gwdg.de.

### Steps to reproduce:

1. Open https://github.com/jitsi/jitsi-meet/wiki/Jitsi-Meet-Instances
2. Pick any listed instance
3. Use it

### Expected behavior:

Each listed instance is available.

### Actual behavior:

When picking vct.testsrv.gwdg.de the hostname is not found, the instance has been discontinued:
https://info.gwdg.de/dokuwiki/doku.php?id=en:services:mobile_working:videoconferencing_tools:jitsi:start
https://info.gwdg.de/dokuwiki/doku.php?id=de:services:mobile_working:videoconferencing_tools:jitsi:start

### Suggested fix:

Remove https://vct.testsrv.gwdg.de/ from https://github.com/jitsi/jitsi-meet/wiki/Jitsi-Meet-Instances#special-cases-limited-access-1

**Comment by Echolon** [comment]
@julianladisch can you create a PR for this?

**Comment by saghul** [comment]
Done. I also added a depreciation notice to the wiki. All Gelo migrating the content to the Handbook is welcome.
