### ISSUE TITLE
Cannot enable Google Analytics tracking 

### ISSUE THREAD

**Issue by sashi01** [jitsi/jitsi-meet#7446]
### Description:

Uncommented Google Analytics in `config.js`

```
analytics: {
        // The Google Analytics Tracking ID:
        googleAnalyticsTrackingId: 'UA-xxxxxxx-x',

        // Matomo configuration:
        // matomoEndpoint: 'https://your-matomo-endpoint/',
        // matomoSiteID: '42',

        // The Amplitude APP Key:
        // amplitudeAPPKey: '<APP_KEY>'

        // Configuration for the rtcstats server:
        // In order to enable rtcstats one needs to provide a endpoint url.
        // rtcstatsEndpoint: wss://rtcstats-server-pilot.jitsi.net/,

        // The interval at which rtcstats will poll getStats, defaults to 1000ms.
        // If the value is set to 0 getStats won't be polled and the rtcstats client
        // will only send data related to RTCPeerConnection events.
        // rtcstatsPolIInterval: 1000

        // Array of script URLs to load as lib-jitsi-meet "analytics handlers".
        scriptURLs: [
             "libs/analytics-ga.min.js", // google-analytics
            //  "https://example.com/my-custom-analytics.js"
        ],
    },
```

Made build using the build script 
`xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive`

Cannot observe events under my app in analytics.google.com

**Comment by sashi01** [comment]
On console
`[JitsiMeetSDK] [features/analytics] Loaded 0 analytics handlers`

**Comment by saghul** [comment]
> "libs/analytics-ga.min.js

Does this file exist in your deployment?

**Comment by sashi01** [comment]
> > "libs/analytics-ga.min.js
> 
> Does this file exist in your deployment?

libs/analytics-ga.min.js - No
analytics-ga.js - Yes , but in root

<img width="1677" alt="Screenshot 2020-08-04 at 1 42 47 PM" src="https://user-images.githubusercontent.com/5857539/89270174-9a27ff00-d658-11ea-8fc2-f127a5c2c3bf.png">

**Comment by saghul** [comment]
Ah wait, I had missed this is mobile related. We don't have GA support there.

**Comment by sashi01** [comment]
Ok. GA not supported on mobile then. Thanks !!

**Comment by Echolon** [comment]
I close this then.
