### ISSUE TITLE
network ip camera

### ISSUE THREAD

**Issue by guigeek208** [jitsi/jitsi-meet#745]
Hi,
I want to know if you can use a network ip camera (RTSP protocol) like AXIS or others with jitsi-meet ?
Thanks,
Best regards,

**Comment by nkokkos** [comment]
You need to create a virtual camera driver that accepts the stream of the ip camera. The virtual camera driver would be available to chrome/firefox like another usb connected device. I am talking out of experience with this issue and had it working on windows.
