### ISSUE TITLE
Build is not running

### ISSUE THREAD

**Issue by ips-illuminz** [jitsi/jitsi-meet#7450]
I have cloned the latest repo and installed modules with `npm i`

When i'm running `react-native run-android` i'm getting below error:

`jitsi-meet/react/index.native.js: Unexpected token, expected ";" (14:8)`

Before it was working fine and now it's not working with any previous commit, i had tried with previous month commits as well, but nothing seems to be working. Kindly look into this and let me know what could be the issue.

**Comment by saghul** [comment]
I have experienced the same behavior. We'll look into it.

**Comment by ips-illuminz** [comment]
Hey Guys, thanks for confirming the issue. Meanwhile can you please share a commit that i can use to run build on android, that would be very helpful.

**Comment by saghul** [comment]
You can use the `mobile-20.3` branch, which corresponds with the last release.

**Comment by ips-illuminz** [comment]
Hey @saghul , Thanks for you response. I have tried the above build that is also not working. It's giving me the following error:

`bundling failed: Error: Unable to resolve module `./getDisplayMedia` from `node_modules/react-native-webrtc/MediaDevices.js`:`

I have removed and tried with fresh `npm i` and `npm audit fix` but nothing seems to be working. Could you please provide me previous branch or commit that i can use, as i remembered  that i had used branch 2-3 months ago and that was working fine, but now nothing is working.

**Comment by saghul** [comment]
You must have local changes, there is no such file in react-native-webrtc.

**Comment by ips-illuminz** [comment]
I have fresh cloned the repo and install node modules, but after the `react-native run-build`, it's displaying the following error.

![image](https://user-images.githubusercontent.com/40974105/89517583-84047500-d7f7-11ea-986c-3987eda70bbc.png)

Can anybody please provide me the working commit so that i can use, this is making a lot of trouble to me and i'm not able to edit anything, it was working fine without any issue but yesterday i made mistake by upgrading it

**Comment by saghul** [comment]
Have you tried the mobile-20.3 branch? I tried it from scratch yesterday and it's working.

**Comment by ips-illuminz** [comment]
Yes, i tried with `mobile-20.3`, cloned the repo and then checkout with mobile-20.3 branch with npm install and react-native run-android and i'm getting above error

**Comment by denova** [comment]
@ips-illuminz yesterday I had the same error even for `mobile-20.3` branch. It looks like it's a cache issue but I'm not sure. Steps that helped me (I use android studio for building the app):

1. Remove avd instance
1. Clean build (Build -> Clean Project)
1. Close project in android studio
1. Close android studio
1. Remove node_modules
1. Remove build folder
1. Remove all iml files in the project
1. Remove .idea folders in root and android folders (if you're using android studio)
1. Restart pc (even this sounds wierd, these steps didn't work for me without restarting pc ¯\_(ツ)_/¯)
1. `nmp install`
1. `./node_modules/.bin/react-select start`
1. Wait and import (not open) project in android studio
1. Create new avd instance
1. Run the project

Hope these steps can help you.

**Comment by ips-illuminz** [comment]
Hi @denova , thanks for your reply, but i'm cloning repo from scratch and installing all the modules and not opening in android studio, i had another build that i was opening with Android studio but now i'm not using that, but still i'm getting issue

**Comment by ips-illuminz** [comment]
Hello Guys,
I have tried branch `mobile-19.5` and it is working fine, but it doesn't have all the new features. I have tried all the builds after that are not working and giving errors, all the issues are coming related to webrtc module. Can anybody let me know which version i have to choose with branch `mobile-20.3`.
Thanks in advance!

**Comment by huzaifaaak** [comment]
None of the branch is working for me. They all throw this error. @saghul I think this has to do something with babel config.

**Comment by saghul** [comment]
@huzaifaaak That's my suspicion as well, but `mobile-20.3` doesn't have those changes.

**Comment by s-xync** [comment]
I was just trying to run the `master` branch and faced the issue mentioned in the issue description and came upon this issue. Now i have switched to `mobile-20.3` and getting this issue mentioned by @ips-illuminz in [this comment](https://github.com/jitsi/jitsi-meet/issues/7450#issuecomment-669829723).

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/pull/7495 fixes it. You can locally delete the babel.config.js file, for the same effect. Now, after doing that you need to reset the transform cache. Currently the easiest way to do this is to run `react-native-start --reset-cache` and quit the bundler afterwards.

**Comment by applejian** [comment]
Build is not running too,

**Comment by saghul** [comment]
Have you reset the transformation cache?

**Comment by ips-illuminz** [comment]
Thanks @saghul , now it's fixed and everything is working fine now.

**Comment by s-xync** [comment]
After removing `babel.config.js` as suggested by @saghul, I had to first do `rm -rf node_modules`, then `npm install` and `npx react-native start --reset-cache` to get it fixed. Thanks @saghul.

**Comment by ips-illuminz** [comment]
Hello Guys,
Again getting the following error while trying to run build with android device

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
```

Thanks in advance for help
