### ISSUE TITLE
Camera & microphone not working in chrome browser in an iframe

### ISSUE THREAD

**Issue by ssaini14** [jitsi/jitsi-meet#7451]
### Description:
We have added Jitsi meet url in an iframe.

<iframe id="iframe_4_canvas" height="0px" width="0px" src="https://meet.jit.si/TestRoom" allow="camera; microphone" style="min-height: 600px; min-width: 1200px; scroll-behavior: auto;"></iframe>

We are getting "Error obtaining camera permission" and "Error obtaining microphone permission" error and not able to access the camera & microphone in the meet.

If we directly open the meet link in chrome, then it is working fine. its only NOT working within iframe.

Its working for us in Firefox.

### Steps to reproduce:

1) Add jitsi meet URL in an iframe, and then open it in chrome browser.

### Expected behavior:

We should be able to attend the jitsi conference and can use camera and microphone

### Actual behavior:

Not able to access camera & microphone.

![image](https://user-images.githubusercontent.com/37363460/89291503-475e3f80-d678-11ea-8fa2-f2e52e8973f1.png)

### Server information:

- Jitsi Meet version: We are using the Jitsi web "https://meet.jit.si/TestRoom"
- Operating System: Windows 10

### Client information:

- Browser / app version: Chrome Version 84.0.4147.105
- Operating System: Windows 10

### Additional information:

Issue not coming on Firefox

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
