### ISSUE TITLE
Jitsi Android does not reconnect to room after losing network connection

### ISSUE THREAD

**Issue by dofl** [jitsi/jitsi-meet#7453]
### Description:

The official Jitsi Android application does not reconnect back to the server after the network is disrupted.

### Steps to reproduce:

1. Start a chat on any server (meet.jit.si or my own server: https://meet.helmchat.eu. I tested both with the same results) with 2 streams. Use for example a PC and and Android phone with the Android application 20.3.2. build 4911829. 
2. Make sure you are in the same chatroom. 
3. Set the phone to flight mode. The Android app will notify that the connection has been lost and it will reconnect. 
4. Turn flight mode back off
5. The app will tell you that it’s reconnected but isn’t and shows that you re the only one in the room. The room in your browser will still say that the connection to the Android phone is lost. The Android app somehow thinks it reconnected but didn’t.

Tested this multiple times, fails every time. Others tested as well, same result.

### Expected behavior:

The Jitsi Android app should reconnect back to the chat room on the server

### Actual behavior:

The Jitsi Android app appears to be back in the room (with no other clients) and does not reconnect anymore. It probably thinks it back in the room

### Server information:

- Jitsi Meet version: 2.0.4857-1
- Operating System: Ubuntu 20.04.1 LTS

### Client information:

- Browser / app version:  20.3.2. build 4911829
- Operating System: Android

**Comment by dofl** [comment]
Found out what breaks the re-connection.

**Comment by dofl** [comment]
@hristoterezov Any news on the horizon on a fix in a future version?

**Comment by saghul** [comment]
We fixed reconnection on 20.5, a dialog will be shown when the connection is lost with the reconnection progress.

**Comment by nsumithradeveloper** [comment]
Issue is still there

**Comment by saghul** [comment]
Please open a new issue and paste the adb logcat output.
