### ISSUE TITLE
JitsiMeetExternalAPI: configOverwrite.tokenAuthUrl is not assigned

### ISSUE THREAD

**Issue by jesusvilla** [jitsi/jitsi-meet#7456]
### Steps to reproduce:

1. Copy from official example:
```js
const domain = 'meet.jit.si';
const options = {
  roomName: 'JitsiMeetAPIExample',
  width: 700,
  height: 700,
  parentNode: document.querySelector('#meet'),
  configOverwrite: {
    tokenAuthUrl: 'https://domain.example.com/auth'
  }
};
const api = new JitsiMeetExternalAPI(domain, options);
```
2. On the embed iframe:
```js
console.log('config', config.tokenAuthUrl)
```

### Expected behavior:

As developed, it should allow token validation by calling that configured url. This should go in here: https://github.com/jitsi/jitsi-meet/blob/master/modules/UI/authentication/AuthHandler.js#L20

https://github.com/jitsi/jitsi-meet/pull/728

### Actual behavior:

That property doesn't work. config.tokenAuthUrl is undefined.

### Client information:

- Browser / app version: Chrome / 83.0.4103.116
- Operating System: Ubuntu 20.04

**Comment by damencho** [comment]
URLs are intentionally not whitelisted to be able to be overwritten as this opens doors for bad behavior and forwarding people to bad locations.
To be able to use that you need to change it on your deployment.
