### ISSUE TITLE
Button/textfield taps inside JitsiMeetView will also tap custom other buttons (on previous routes)

### ISSUE THREAD

**Issue by RicardoDolNL** [jitsi/jitsi-meet#7461]
### Description:

I created a wrapper based on https://github.com/skrafft/react-native-jitsi-meet/ for my react native. I mostly just updated the jitsi-meet-sdk version.

The problem: when pressing buttons within the JitsiMeetView it also presses buttons that are shown above that jitsi view or even buttons from a different route (that was visible before the current route is shown). For example i have a custom share button above the JitsiMeetView that now is also been pressed when I tap the buttons like the video or audio toggle.

### Steps to reproduce:

1. Join conference
2. Click a button (like the toggle video button)
3. You'll see a popup of a calendar (what should not be shown since that is a field on a previous route)

### Expected behavior:

That no other buttons should be activated/pressed when pressing a button within the JitsiMeetView

### Actual behavior:

You see a calendar popup when i hit the video toggle button. This popup should not be shown since it is from a previous route. This route will be shown at the end of the video after I hit the terminate button.

https://i.imgur.com/qhsm5Rk.mp4

### Server information:

- Jitsi Meet version: 2.9.3
- Operating System: -

### Client information:

- Browser / app version: -
- Operating System: Android & iOS

### Additional information:

I also use @react-navigation/native version 5.7.2, but they say it is a Jitsi Meet SDK problem.
There is also an issue at https://github.com/skrafft/react-native-jitsi-meet/issues/85 with a simular problem. But they do not respond (fast).

**Comment by saghul** [comment]
We don't maintain that plugin so we can't really help you, sorry.

**Comment by RicardoDolNL** [comment]
Why not? I know you don't maintain that plugin but it uses the SDK. It just a wrapper for react native, so it's also very likely that the my problem has nothing to do with that plugin and instead has something to do with jitsi-meet-sdk itself.
And since a lot of developers use react native for their jitsi meet app, so they also need to create some sort of wrapper, i think i'm here at one of the best places to ask for some help. Maybe someone also had this problem?

**Comment by hasgardee** [comment]
same issue

**Comment by MjdBh** [comment]
same issue

**Comment by aweffr** [comment]
yeah, we meet the same issue.

**Comment by carlosbpf** [comment]
I also have this issue. I was able to fix it for android by placing another view below (zIndex) the jitsi-view. For iOS it also worked but not for the 14 version.

**Comment by MahmudHasanMenon** [comment]
I am also facing the same issue. When touch jitsi view screen it rediect me somewhere in the app and i can't find the jitsiView screen.
Although it works fine when i call the jitsi view from App.js.

**Comment by MahmudHasanMenon** [comment]
> I also have this issue. I was able to fix it for android by placing another view below (zIndex) the jitsi-view. For iOS it also worked but not for the 14 version.

Is it working now? can you share some code please??
