### ISSUE TITLE
record automatically

### ISSUE THREAD

**Issue by mmdaz** [jitsi/jitsi-meet#7463]
**Is your feature request related to a problem you are facing?**
Because of low limitations for my work, I have to record meets from the server-side.

**Describe the solution you'd like**
I wanna record and save meets from the server-side.

**Comment by Echolon** [comment]
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
