### ISSUE TITLE
iFrame API: conference subject reverts back to room name after a participant changes their display name or media device

### ISSUE THREAD

**Issue by e18r** [jitsi/jitsi-meet#7465]
### Context:

The **conference subject** is the text that appears at the top of the videoconference when you hover your cursor over it.
![Screenshot from 2020-08-05 20-58-25](https://user-images.githubusercontent.com/16065447/89481980-8a92de00-d75e-11ea-812d-fbd6fc09d5ec.png)
Usually, the conference subject is a human-friendly version of the **room name**, i.e. the identifier of the videoconference that you write in the address bar.

When using the [iFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe), though, the conference subject can be set to whatever you want by means of the command

    api.executeCommand('subject', 'New Conference Subject');

### Bug Description:

In a meeting with a custom conference subject, if any participant edits their **display name** during the call, the conference subject reverts back to the room name:
![bernie](https://user-images.githubusercontent.com/16065447/89482541-bfebfb80-d75f-11ea-9a8d-c19c97d90d11.gif)
In this example above the room name is a pseudorandom alphanumeric string, and the conference subject has been customized to the text "pruebita total". However, when the participant changes their display name from "Bernie Sanders" to "aoeu", the conference subject goes back to that alphanumeric string.

Note that this change is visible to all the participants of the call.

### Steps to reproduce:

1. Embed the [iFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe) in a test web application
2. Programatically set up a conference room with a custom conference subject
3. Open your app in a browser
4. Change your display name

### Expected behavior:

The conference subject should remain intact after the display name change

### Actual behavior:

The conference subject unexpectedly reverts back to the room name after the display name change

### Temporary fix

Create an event listener that sets the desired conference subject after each display name change event:

    API.on('displayNameChange', () => {
      API.executeCommand('subject', 'New Conference Subject');
     });

The room name will flicker for a second and then go back to the desired value.

**Edit 2020-08-19:** This also happens when someone changes their media device, as described in #7502. There might be other actions that trigger this. Also, the subject doesn't become the room name, but rather becomes an empty string (as can be seen in the logs and in the `subjectChange` event), so the room name is shown instead.

**Comment by psi-4ward** [comment]
It is because XMPP sends the update message:
```
<S.onMessage>:  Subject is changed to ....
```
and the new subject is the _real_ roomName and not the subject set by external_api

**Comment by psi-4ward** [comment]
My workaround is to ignore the `XMPPEvents.SUBJECT_CHANGED` Message in `https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/ChatRoom.js#L1011`

**Comment by e18r** [comment]
Probably fixed by #7552

**Comment by e18r** [comment]
tested. solved.

**Comment by psi-4ward** [comment]
confirmed.
