### ISSUE TITLE
Firefox not able to establish connection over TURN

### ISSUE THREAD

**Issue by HelloWorldUser123** [jitsi/jitsi-meet#7469]
### Description:

We are using TURN server over TCP/UDP 443. Chrome works well but Firefox doesn't choose the right candidate. It seems to be that the right candidate is not nominated (Screen 1) Somehow after some retries of activating camera/mic in the other browser (i.e. Chrome) sometimes FF choses the right candidate (Screen 2)

![image](https://user-images.githubusercontent.com/63649981/89570541-a19d0300-d826-11ea-8141-6b6d60de1d6b.png)

Here in screen 2 the right one is the ICE on Chrome which is always right and working well. The left one Firefox is only valid after some tries to switch the video on and off in Chrome (when one is Chrome and one is FF)
![image](https://user-images.githubusercontent.com/63649981/89570413-74e8eb80-d826-11ea-81c7-a3d5913b57bf.png)

### Steps to reproduce:

1. One participant with FF and one with Chrome
2. simply open a conference with twp participants

### Expected behavior

Firefox should show video

### Actual behavior

Firefox doesnt show video or audio

### Server information
newest stable jitsi version 4289, with TURN server in front of jvb

### Client information

newest FF and Chrome

**Comment by HelloWorldUser123** [comment]
@jallamsetty1 any ideas?

**Comment by Echolon** [comment]
@HelloWorldUser123 please fill out the issue template properly.

**Comment by HelloWorldUser123** [comment]
@Echolon sorry I added additional information as it is in the template

**Comment by HelloWorldUser123** [comment]
Has anyone an idea?
