### ISSUE TITLE
desktop sharing not work

### ISSUE THREAD

**Issue by sun-hao** [jitsi/jitsi-meet#747]
I have installed jitsi-meet on my local server following the quick-install.  firefox says the https is not safe,so i add the https to the exception.  
But,when i try to share my desktop, jitsi says ERROR!You have not granted permission to share your screen.
what should i do?

**Comment by damencho** [comment]
Please use the dev or users mailinglist before opening issues.
Did you install and configure jidesha extension for firefox? https://github.com/jitsi/jidesha

**Comment by sun-hao** [comment]
I have installed the extension  for firefox from https://addons.mozilla.org/zh-CN/firefox/addon/jidesha1/?src=api and it works well for https://meet.jit.si/,but it doesn't work for my local jitsi-meet.

Do i need build the extension for my local jitsi-meet?

**Comment by damencho** [comment]
Yep its per domain, you need to create a jidesha plugin for your deployment and install it(https://github.com/jitsi/jidesha). For chrome you should deploy it to chrome store. For FF you can configure it at your instance, sample configs from our beta deployment:
desktopSharingFirefoxExtId: "jidesha@meet.jit.si",
desktopSharingFirefoxDisabled: false,
desktopSharingFirefoxMaxVersionExtRequired: -1,
desktopSharingFirefoxExtensionURL: "https://beta.meet.jit.si/jidesha-0.1.1-fx.xpi",

**Comment by sun-hao** [comment]
@damencho My local jitsi-meet works,thank  you for your help!  
I have a another question:  I don't want to use https(SSL),so  i   have  changed site's nginx conf,  but the site has some problems.  Must the jisi-meet works at https or SSL?

**Comment by damencho** [comment]
Yep its a webrtc requirement.

**Comment by pciavald** [comment]
I didn't compile the extension yet, and it is not installed in my Firefox, however I can share my desktop on meet.jit.si . I do not have the button showing in my local install. Why is that I can share my desktop on your hosted version while I don't have the extension installed ? How can I reproduce this behavior on my local install ?

**Comment by damencho** [comment]
You need to create extensions for chrome and firefox, firefox can be installed from a url where you deploy it, chrome need to be in chrome store.
And you need to configure those extensions in the /etc/jitsi/meet/.....-config.js. 
Take a look at https://github.com/jitsi/jidesha

**Comment by pciavald** [comment]
Thank you very much. Is meet.jit.si installing an extension automatically under the hood ? I didn't accept the installation of a plugin, but i'm able to share my screen.

**Comment by damencho** [comment]
It is installing automatically for chrome, while for firefox for meet.jit.si site you do not need an external extension, cause meet.jit.si site is whitelisted inside firefox itself.

**Comment by pciavald** [comment]
How can I whitelist my local site in firefox ?
Also I gave a look to the configuration of meet.jit.si by inspecting the webpage source and it shows : 
```
desktopSharingFirefoxExtId = "",
desktopSharingExtensionURL = ""
```

**Comment by damencho** [comment]
To whitelist it locally you need to open about:config and edit:
media.getusermedia.screensharing.allowed_domains
There is an issue or something on firefox tracker to submit yours, but I do not know the rules there and it takes several iteration of versions to go inside firefox by default.

The id of the extension you need to set it in jidesha when building the extension, the config should be something like:
desktopSharingFirefoxExtId: "jidesha@somedeployment.com,
desktopSharingFirefoxExtensionURL: "https://somedeployment.com/jidesha-somedeployment.xpi",

**Comment by pciavald** [comment]
Thank you. Actually firefox is rolling out the whitelist feature : https://wiki.mozilla.org/Plugins/Firefox_Whitelist
We're really enjoying jitsi and we are willing to contribute once we get a better sense of how it is implemented. If you have some time, could you answer my question on #935 ? Also do you have any documentation on how to avoid guests to create rooms and force user login to a room ?

**Comment by damencho** [comment]
You need to just make sure you enable authentication in prosody, and then configure in config.js:
        anonymousdomain: 'guest.example.com', // the domain that guests will use, the domain configured in prosody as authentication = "anonymous"
        authdomain: 'jitsi-meet.example.com', //and this is the domain that users authenticating and creating conferences will use

**Comment by damencho** [comment]
Please use the mailinglist for questions.

**Comment by sun-hao** [comment]
@damencho Hello ,
   I'm using jitsi for the desktopsharing. i chose aa window  in the firefox extension,like aa.window  to share with attendee.  Jistsi  works well,but  i  click a button to open another window or form like bb.window  in the aa program.  How can  attendee  see the bb.window(aa's child window)? 
Please help me ,thanks very much!

**Comment by manibha-jain** [comment]
Hi i m getting this error  when trying jitsi on a server IP
**features/base/tracks] Failed to create local tracks ["desktop"]0: "desktop"length: 1__proto__: Array(0) Error: Desktop sharing is not supported!**
The code is working on local but on server screen sharing option is not showing. Can anybody help?
