### ISSUE TITLE
Chrome permissions issue

### ISSUE THREAD

**Issue by fred-dev** [jitsi/jitsi-meet#7471]
I am having an issue with chrome not asking for camera permissions on chrome Version 84.0.4147.105 (Official Build) (64-bit). I am using jitsi meet on my site, but also see this exact same behaviour when visiting https://meet.jit.si. In firefox the behaviour is correct. Checking the console I see these errors in this order: 

`[modules/RTC/RTCUtils.js] Failed to get access to local media.  NotAllowedError: Permission denied [object Object] `

`features/base/tracks] Failed to create local tracks `

I know this can be from not using https, but my site and the jitsi meet site are both secure. It seems the method that jitsi meet uses to get camera permissions has been depreciated, it will only get microphone access. When the user tries to enable the camera it will add an access request that can be found by clicking in the camera icon in the address bar of chrome (this does not appear until the enable camera button is pressed in the standard jitsi interface), but no popup or user prompt is triggered.

**Comment by Echolon** [comment]
@fred-dev can you please fill out the issue template?

**Comment by fred-dev** [comment]
Can you share a link to the template?

**Comment by Echolon** [comment]
@fred-dev if you click new issue a template is provided. You can copy that

**Comment by fred-dev** [comment]
Now clearer in #7478 I closing this issue
