### ISSUE TITLE
API Encryption method exists?

### ISSUE THREAD

**Issue by Gerard-ODonnell** [jitsi/jitsi-meet#7482]
Hi,

In the same way we have

`api.executeCommand('password', 'ThePassword');`

which can set the room password, has there been deployed something like

`api.executeCommand('e2eePassword', 'TheE2EEPassword');`

for setting the E2EE password, or at the moment, must it remain a procedure that is done

1. manually or 
2. https://meet.jit.si/theRoomName#e2eekey=TheE2EEPassword

**Comment by damencho** [comment]
There is no option to set that using an API function. There is UI to set it when it is supported.

Please use the community forum for questions before opening new issues.
