### ISSUE TITLE
main-fa.json strings don't match main-enGB.json

### ISSUE THREAD

**Issue by mrphs** [jitsi/jitsi-meet#7483]
### Description:

I have started translating the strings into Persian (Farsi) [here](https://github.com/kandootech/jitsi-meet/tree/persian-translation) and I noticed a bunch of strings in [main-fa.json](https://github.com/jitsi/jitsi-meet/blob/master/lang/main-fa.json) don't match [main-enGB.json](https://github.com/jitsi/jitsi-meet/blob/master/lang/main-enGB.json) which I assume is the main file.

I tried to look around but couldn't find what's the recommended procedure of updating the translation, or the strings to be translated.

### Steps to reproduce:

compare the strings on https://github.com/jitsi/jitsi-meet/blob/master/lang/main-fa.json to 
https://github.com/jitsi/jitsi-meet/blob/master/lang/main-enGB.json

**Comment by mrphs** [comment]
Additionally I was wondering if we could coordinate to add this project under the umbrella of [Localization Lab](https://www.localizationlab.org/) to have the community work more actively on updating the translations.

**Comment by damencho** [comment]
Take a look at https://github.com/jitsi/jitsi-meet/issues/5056
We still haven't managed to transition that ... there were few legal stuff to figure out that slowed it down and now the vacation season ...

**Comment by damencho** [comment]
For now the translation work is done by hand. The main file to check for strings is main.json.

**Comment by mrphs** [comment]
> For now the translation work is done by hand. The main file to check for strings is main.json.

So, does this mean I should over-write the strings that don't match? What's the process like to get them included in the next release? I couldn't find any documentation around this.
