### ISSUE TITLE
AppStore Processing fails and builds are showing "Invalid Build", when using Jitsi SDK in iOS Application

### ISSUE THREAD

**Issue by Rahulin15** [jitsi/jitsi-meet#7484]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by Echolon** [comment]
@Rahulin15 Hello, I will close this until you fill out the issue template. Then I can reopen.
