### ISSUE TITLE
`JitsiMeetExpernalAPI`support persistance of video quality or current device list

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#7486]
**Is your feature request related to a problem you are facing?**
Yes. I want to be able to persist the `videoQuality` between sessions. The problem is that there isn't a way to get the current `videoQuality` nor is there an event that reports a change in `videoQuality`.

I'd also like to be able to persist the current device choices. While `api.getCurrentDevices().then(devices => { ... })` is defined, there isn't an event that reports a change in the current device list.

**Describe the solution you'd like**
Add an event that reports the current video quality when the conference is joined and whenever the user changes the video quality, e.g., `api.on('videoQualityChange', ({ quality: value }) => { ... }))`

The important part is to tigger the event immediately upon creating the conference object (just like `tileViewChanged` fires immediately indicating the default state of `tileViewEnabled` before `videoConferenceJoined` fires).

For the current device list, since there is a "get" function, all that's required is an event that reports the current device list whenever it is changed, e.g., e.g., `api.on('currentDevicesChange', (devices) => { ... }))`

**Describe alternatives you've considered**
N/A

**Comment by hristoterezov** [comment]
Indeed we currently don't have events that notify for video quality changes or current devices changes. I agree that it make sense to implement them!

On the other hand, about persisting the current device choice, I believe this is currently handled anyway inside the iframe in Jitsi Meet. Isn't this working for you? If this is the case please let us know!

**Comment by mrose17** [comment]
This isn't work, briefly: the `'localStorage` for "meet.jit.si" is always empty. i will privately send you a screen shot with a URL to the site that you can examine!  Thank you!

**Comment by mrose17** [comment]
It looks like current device persistence is now working. So i guess that's left is being able to persist video quality...

**Comment by mrose17** [comment]
FYI: this is resolved. i am unsure as to why it wasn't paired with a PR...
