### ISSUE TITLE
`JitsiMeetExpernalAPI options.userInfo.displayName` ignored on prejoin page

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#7487]
### Steps to reproduce:

        const options = {
          "roomName": generateRoomName(),
          "parentNode": document.querySelector('#meet'),
          "configOverwrite": {
            "prejoinPageEnabled": true,
            "startWithAudioMuted": true,
            "startWithVideoMuted": true
          },
          "userInfo": {
            "displayName": "John Q. Public",
            "email": "..."
          }
        }
       
        JitsiMeetJS = new JitsiMeetExternalAPI(domain, options); 

results in this screen:

<img width="1232" alt="Screen Shot 2020-08-07 at 16 45 09" src="https://user-images.githubusercontent.com/400552/89690968-6acdf800-d8cd-11ea-813d-7896344cb369.png">

### Expected behavior:

Instead of an input field of "Please enter your name here", i'd expect to see "John Q. Public"

### Actual behavior:

See image above.

### Server information:

- Jitsi Meet version: [this](https://github.com/jitsi/jitsi-meet/blob/master/package.json) says "0.0.0"
- Operating System: N/A

### Client information:

- Browser / app version: N/A
- Operating System: N/A

### Additional information:

Since this works on meet.jit.si, i suspect that this is a documentation problem.

**Comment by hristoterezov** [comment]
Thanks for the report! 

I've just verified that we are not updating the display name on the prejoin page when you set it trough the Iframe API. We'll be working on fixing it.

**Comment by maxfloden** [comment]
Maybe it is the same thing as iframe api, but it does not work from url either, for example: meet.jit.si/meeting-refererence#userInfo.displayName="nwoodhouse"

**Comment by hristoterezov** [comment]
This is fixed with  https://github.com/jitsi/jitsi-meet/pull/7583
