### ISSUE TITLE
In panel view, show those with video only

### ISSUE THREAD

**Issue by snan** [jitsi/jitsi-meet#7489]
On my puny screen it's annoying that the blank squares of those who aren't connected via video (for example those who have connected via textt jabber clients) take up as much space in the **panel view** as those who do.

Maybe they could be shown smaller (good for when they have icons and such) but giving them as much space as those who have video is kinda hopeless.

**Comment by saghul** [comment]
Jitsi Meet is designed with video conferencing in mind first and foremost. Supporting a different UI for text-only clients is not something we can spend time on, sorry.

**Comment by snan** [comment]
Hold on, the experience is fine who those have text-only clients.

**The problem is for those who do use the app for video conferencing.**
For example I have one guy that connects in with voice only and doesn't
turn on his camera (or maybe he doesn't have a camera, IDK.)

For those of us who _do_ use the app, we just see this big gray square
taking up as much space as the real video feeds (in panel view).

For those who log in with text-only, it's fine— they don't even _have_ a
panel view to be concerned with.

**Comment by snan** [comment]
That guy does use the app. I think mentioning text client in my first post was a red herring and I regret that.
