### ISSUE TITLE
How can i hide video of a specific participant so that i will not receive their stream?

### ISSUE THREAD

**Issue by dyros26** [jitsi/jitsi-meet#7491]
How can i hide video of a specific participant so that i will not receive their stream to lower my bandwidth consumption. It’s like the “low bandwidth” or “audioOnlyMode” feature but for a specific participant only, not all participant.

**Comment by Echolon** [comment]
Hello,

please refer to the Jitsi Meet Community Website with questions. This is only for bugs and feature requests.
