### ISSUE TITLE
I am trying to install jitsi nightly version in ubuntu AWS but i am getting an error

### ISSUE THREAD

**Issue by kushagraagent47** [jitsi/jitsi-meet#7492]
The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-web (= 1.0.4328-1) but 1.0.4337-1 is to be installed
              Depends: jitsi-meet-web-config (= 1.0.4328-1) but 1.0.4337-1 is to be installed
              Depends: jitsi-meet-prosody (= 1.0.4328-1) but 1.0.4337-1 is to be installed
              Recommends: jitsi-meet-turnserver (= 1.0.4328-1) but it is not going to be installed or
                          apache2 but it is not going to be installed

This is the error i am getting, i conifgured universal, installed jdk 8 but still i am getting this error since 10 days

**Comment by Echolon** [comment]
@kushagraagent47 can you please fill out the issue template when clicking new issue?

**Comment by Echolon** [comment]
I will close this until the reporter haven't provided steps to reproduce.
