### ISSUE TITLE
Automatically copy invite URL after creating a room?

### ISSUE THREAD

**Issue by ctheune** [jitsi/jitsi-meet#7501]
**Is your feature request related to a problem you are facing?**

Zoom has the feature where creating a new room will automatically copy the URL (and just the URL) into your system's copy buffer for immediate pasting into chat, mail, etc. I notice that even after having switched to Jitsi a number of months ago I keep pasting (accidentally) whatever is in my buffer because my brain keeps thinking the URL will already be copied ... 

**Describe the solution you'd like**

I'd love if we could add this (optionally, and maybe even just in the Electron app, depending on whether browsers would support this without user interaction).

**Comment by RabeeAbuBaker** [comment]
@Echolon I'd like to start contributing to the project, can I start with this?

**Comment by Echolon** [comment]
@RabeeAbuBaker first you should read and agree to this: https://github.com/jitsi/jitsi-meet/blob/master/CONTRIBUTING.md

Then this might help: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web

and then I suggest you propose your approach to the developers.

Anything else? @saghul

**Comment by RabeeAbuBaker** [comment]
@Echolon I already forked the project and was able to solve it locally. I will sign the Contributor License Agreement before submitting a PR. But who should I discuss the technical side of this with first?

Thank you!

**Comment by Echolon** [comment]
@RabeeAbuBaker if you have the solution already done, you can just create a pull request and then wait for feedback of one if the maintainers.

Thanks you!
