### ISSUE TITLE
Using the iFrame API, the subject resets to "" when someone changes a media device

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#7502]
### Description:

When a conference is running using the iFrame API, if someone changes a media device, the subject is reset to `""`

### Steps to reproduce:

1. Start with

           JitsiMeetJS = new JitsiMeetExternalAPI(domain, options);
           JitsiMeetJS.executeCommand('subject', options.interfaceConfigOverwrite.APP_NAME);

2. Join the conference

3. Change one of your media devices

### Expected behavior:

Nothing should happen to the conference's subject

### Actual behavior:

The subject changes to `""` as reported by the `subjectChange` event:

        }).on('subjectChange', (params) => {
            reportAction('subjectChange', params);
        ...

This results in my `reportAction` putting this in the console

        !!! subjectChange: {
          "subject": ""
        }

### Server information:

- Jitsi Meet version: 0.0.0
- Operating System: Linux

### Client information:

- Browser / app version: Brave / 1.14.27

- Operating System: Mac

### Additional information:

N/A

**Comment by psi-4ward** [comment]
related to https://github.com/jitsi/jitsi-meet/issues/7465 ?

**Comment by e18r** [comment]
@psi-4ward @mrose17 This is definitely the same bug as #7465. I just tested this and indeed the subject resets to "" when someone changes a media device, and also when someone changes their display name. I originally reported it as resetting to the room name because it seems that, when the subject is blank, the room name is shown instead.

**Comment by hristoterezov** [comment]
This is fixed by https://github.com/jitsi/jitsi-meet/pull/7552

**Comment by mrose17** [comment]
@hristoterezov - thank you!
