### ISSUE TITLE
Disable recording popups/notifications

### ISSUE THREAD

**Issue by cesarcorzo** [jitsi/jitsi-meet#7504]
**Is your feature request related to a problem you are facing?**
When a conference recording is started, a popup notification shows. Same when a conference recording is stopped.

![image](https://user-images.githubusercontent.com/65993266/89850945-5c940c00-db59-11ea-9c2d-973c4e36015c.png)

**Describe the solution you'd like**
I would like to enable/disable this through a **interface_config.js** or **config.js** file.

**Describe alternatives you've considered**
Tried to disable it in the code but haven't located the file(s) needed to do that.

**Comment by highvoltage** [comment]
Stalebot how dare you.

**Comment by saghul** [comment]
I'm not sure this should be addressed. Users must know they are being recorded.
