### ISSUE TITLE
Enable Encryption missing from security options

### ISSUE THREAD

**Issue by alternativesurfer** [jitsi/jitsi-meet#7505]
### Steps to reproduce:

1. 
Jitsi meeting
2. 
Shield, enter password.
Encryption key section missing.
![image](https://user-images.githubusercontent.com/10135929/89856993-b0015c80-db4f-11ea-82a1-17f702d1d007.png)

3. 

### Expected behavior:

Last week when I clicked the shield there was a second section under Password for me to enable encryption and set a key.

### Server information:

- Jitsi Meet version:
- Operating System:
### Client information:

- Browser / app version:
Tested in Firefox 79
Chrome 84.0.4147.125
Edge 84.0.522.58
- Operating System:
Windows 10, pro

**Comment by saghul** [comment]
The origina trial had expired, we got it renewed and it's working now.
