### ISSUE TITLE
Tiles are very small in the tile view

### ISSUE THREAD

**Issue by ovvn** [jitsi/jitsi-meet#7509]
**Is your feature request related to a problem you are facing?**
Can't make tile sizes bigger, wasting too much of useful space
<img width="442" alt="Zoom_Meeting" src="https://user-images.githubusercontent.com/2973998/89914169-4dff3080-dbfd-11ea-8ae9-bcb760cf8ac6.png">

**Describe the solution you'd like**
Be able to customize tiles, e.g. via the interface config https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js

**Describe alternatives you've considered**
Google Meet

**Comment by saghul** [comment]
That's really weird, they should be larger indeed. What resolution was that?

**Comment by ovvn** [comment]
@saghul 
<img width="879" alt="localhost_3000_v3_negotiation_cfcecaad-3d08-456c-9392-875815fbfc0a_fiveTricks_fiveTricks1 4" src="https://user-images.githubusercontent.com/2973998/90048797-a822f300-dcdc-11ea-836a-d9dd2a1af5f1.png">
<img width="871" alt="localhost_3000_v3_negotiation_cfcecaad-3d08-456c-9392-875815fbfc0a_fiveTricks_fiveTricks1 3" src="https://user-images.githubusercontent.com/2973998/90048882-c38dfe00-dcdc-11ea-9f37-a43170cd3712.png">

**Comment by Echolon** [comment]
Thank you for reporting @ovvn 

May you change the title into a statement not a question? That would be great!

**Comment by ovvn** [comment]
@Echolon done

**Comment by saghul** [comment]
That is an incredibly small window size. We are not currently ready to work properly at such small sizes. I know strides have been made towards this end though. See:  https://github.com/jitsi/jitsi-meet/pull/7380

**Comment by Echolon** [comment]
@ovvn I will close this so far for now, okay?
Sorry, we couldnt help.

**Comment by ovvn** [comment]
@saghul what minimum window size do you consider appropriate for Jitsi's tile view to look good? The pull request #7380 doesn't solve the tile view issue.
@Echolon, no worries :) Anyway, I set up my own instance and made tile view look better.
