### ISSUE TITLE
Lobby - mobile. When the moderator leaves, no mobile user takes over as the host

### ISSUE THREAD

**Issue by AliKarpuzoglu** [jitsi/jitsi-meet#7514]
### Description:

When Opening a lobby - via the app or the browser, people can join. The moderator can let people in. But if the moderator disconnects, he can not rejoin, because no one can let him back in. A client that is logged in via the browser can take over though

### Steps to reproduce:

1. person1 opens a room with an android/ iOS phone
2. enable the lobby mode
3. person2 joins on mobile
4. person 1 hangs up
5. person 1 or another person 3 tries to join
6. no one can join now, because the app user can not let them in

### Expected behavior:

the last person should be allowed to let people in

### Actual behavior:

no one can join now,

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: newest app release
- Operating System: ios/android

**Comment by saghul** [comment]
I assume you are not using the all moderators plugin? Is participant 2 promoted to a moderator on web?

**Comment by AliKarpuzoglu** [comment]
Yes, Participant 2 is promoted to a moderator on web. I have to ask my team about the moderators plugin

**Comment by saghul** [comment]
Can you reproduce this on beta.meet.jit.si? It has the lobby enabled and the all-moderators plugin disabled.

**Comment by damencho** [comment]
Nope, beta has all-moderators enabled. alpha.jitsi.net is the place with lobby and not all-moderators enabled.

**Comment by AliKarpuzoglu** [comment]
reproduced it on alpha.jitsi.net:

1. open lobby with chrome 
2. join lobby with iphone
3. leave with chrome
4. try to join with chrome

-> the iPhone can not allow the user 

When I reversed the roles (open with iPhone etc), I was  also not able to let the the next users back in via the browser  
> Is participant 2 promoted to a moderator on web? 

So no, not on alpha.jitsi.net

**Comment by damencho** [comment]
I just tested on alpha jitsi net and if the moderator leaves a random person from the meeting is promoted for moderator. You can guess that by the star on the thumbnail.

**Comment by AliKarpuzoglu** [comment]
Did you try entering the lobby with another device? I think(not sure) I saw the star, too...

**Comment by damencho** [comment]
Now, I was checking only the web. I don't think mobile shows the star. And the moderator rights are handled in the backend so ...

**Comment by AliKarpuzoglu** [comment]
But ignoring the star and the moderator permissions, were you able to let new people enter the lobby as a promoted moderator?

**Comment by saghul** [comment]
Mobile does show stars except in the case everyone is a moderator. We might be missing some role update handler perhaps? (on mobile)

**Comment by saghul** [comment]
Ok, I tested and could reproduce the problem. Steps:

- browser: join a meeting on alpha and enable lobby
- mobile: join the same meeting and ask for permission
- mobile: check there is no star for their own thumbnail nor the disable lobby option visible
- browser: leave
- mobile: check the disable lobby option is now visible
- browser: rejoin
- mobile: no notification is received, but we have a star, so we are moderators

**Comment by saghul** [comment]
Actually, I can also reproduce the problem with 2 browsers. I think I have a lead on where the problem is.

**Comment by saghul** [comment]
@damencho This is very weird. When I use the "grant moderator" functionality things work ok. But if the initial owner leaves instead, I do get promoted to moderator, but joining the lobby fails like so:

```
<presence xmlns="jabber:client" to="3937108f-92b1-497e-912f-77fd803efebd@alpha.jitsi.net/OfEqLJPf" type="error" from="saghul@lobby.alpha.jitsi.net/e01ee051"><error type="cancel"><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Room creation is restricted</text></error></presence>
```

**Comment by damencho** [comment]
Hum, I will take a look, I have another lobby bug to track next on my plate. Thanks for the tests.
