### ISSUE TITLE
Participants audible even though muted

### ISSUE THREAD

**Issue by dominikandreas** [jitsi/jitsi-meet#7516]
### Description:

Some users are audible even though their microphone is turned off in jitsi web. Once they turn it on, they sound like a robot (probably duplicate sound stream slightly offset by a couple of ms). I regard this issue as very severe because users can't trust that the rest of the participants can't hear them. There is no indication of transmission (blue dots that are normally visible) and the user icon displays that the mic is muted

### Steps to reproduce:

Unsure. This has happened to different participants but doesn't always happen. On reconnect the issue was often resolved.

### Expected behavior:

If jitsi displays a user as muted (both on his screen and on the other clients), other users should not hear audio transmission from that user.

### Actual behavior:

Other uses can hear audio transmissions from the user that should be muted. When the affected user unmutes, his voice has a robotic tone (probably duplicate transmissions happening simultaneously)

### Server information:

- Jitsi Meet version: Official meet.jit.si server. Don't know the version. We had the bug happen today (2020-08-12) as well as on multiple other occasions during the last two weeks (time frame is a rough guess)
- Operating System: Don't know

### Client information:

- Browser / app version: Unsure about all cases, but happened once on Chrome (not sure which version)
- Operating System: Windows 10 (not sure about other cases)

### Additional information:

Sorry for the lack of information regarding version details. I will try to gather more information next time it happens, but wanted to report this bug as I regard it as very severe

**Comment by folosada** [comment]
Hello!

Same problem here.
When the mic is mute the people still hear me and whether I unmute the mic my audio is duplicated.

**Comment by dominikandreas** [comment]
Seems to happen for users with more than one microphone. Eg laptop users using a headset. I would regard this issue as very serve, there should be more attention to it by the developers

**Comment by folosada** [comment]
> Seems to happen for users with more than one microphone. Eg laptop users using a headset. I would regard this issue as very serve, there should be more attention to it by the developers

Yes, this is my case. I'm using a laptop with built-in mic and a headset. 

In Jitsi's settings I selected headset's mic and it works because I can turn off the headset's mic independently (hardware) and the members doesn't hear the laptop mic. 

But if I turn on the headset's mic even muted in Jitsi the members can hear me.

**Comment by dominikandreas** [comment]
The issue still persists when using the official server (meet.jit.si) for
users with windows laptops having an integrated microphone but using a
separate headset. I still regard the issue as quite severe because of the
privacy implications. I don't quite understand why there doesn't seem to be
any interest by the developers
