### ISSUE TITLE
Jitsi reconnects on hosting meeting

### ISSUE THREAD

**Issue by panwar67** [jitsi/jitsi-meet#7522]
### Description:

 The jitsi call is initiated on loop if i try to create a meeting 

### Steps to reproduce:

1. Open app
2. Enter room name and join
3. After the popup where host can login the app reconnects to the room again and it happens on loop

**Comment by saghul** [comment]
Please provide browser console logs.

**Comment by Echolon** [comment]
@panwar67

**Comment by mitesh-rathod** [comment]
Facing the same issue. @saghul 
![image](https://user-images.githubusercontent.com/37058536/91005166-d6b19f80-e5f3-11ea-8f28-f87f470991b2.png)

**Comment by damencho** [comment]
I'm not seeing all the logs, but I think your error is ice failed. Follow quick install guide the advanced section. A common problem with firewall or port forwarding not working or jvb not announcing its public address.

**Comment by damencho** [comment]
@mitesh-rathod use the community forum when having problems.
I'm closing this issue no response was given for 11 days.
