### ISSUE TITLE
Tile view uses tiny video tiles when low Jitsi window height

### ISSUE THREAD

**Issue by edemaine** [jitsi/jitsi-meet#7526]
### Description:

The tile view seems to have a hard-coded margin of 100px on top and 100px on bottom. This makes the tile view especially useless when the window has low height (say, around 200px), even if the window is wide so could accommodate video quite well.

### Steps to reproduce:

1. Open any Jitsi meeting
2. Enter tile view
3. Shrink the height of the window

### Expected behavior:

Videos use the available vertical space.

### Actual behavior:

Here's a screenshot with two participants and the tools hidden:

![image](https://user-images.githubusercontent.com/2218736/90192112-3f954e00-dd90-11ea-865e-35753bfa815c.png)

Here's a screenshot with two participants and the tools shown:

![image](https://user-images.githubusercontent.com/2218736/90192139-5340b480-dd90-11ea-8a18-45661f42d5d1.png)

Perhaps the tools are the motivation for the 100px margins, but I think it would be much better to use the available vertical space. For comparison, the non-tile view uses the available vertical space, and it looks great even with tools overlaid:

![image](https://user-images.githubusercontent.com/2218736/90192163-62bffd80-dd90-11ea-999e-055f10a457ba.png)

### Server information:

meet.jit.si

### Client information:

- Browser / app version: Chrome 84.0.4147.125
- Operating System: Windows 10 

### Additional information:

This issue is related to #5758, but that is about modal dialogs. The cause here seems to be separate (but the spirit is the same).

I couldn't find an override in https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js but I apologize if I missed it.

**Comment by Echolon** [comment]
related: #7509

**Comment by edemaine** [comment]
It's still an issue, and I've written a PR to fix it.

**Comment by parruc** [comment]
I can confirm that this issue is still present and very annoying. The proposed PR from a quick read seems sensible. Anybody tested it?
