### ISSUE TITLE
When 3rd person joined muted audio and video

### ISSUE THREAD

**Issue by bluecloudRaj** [jitsi/jitsi-meet#7527]
Issue : - When 3rd person joined muted audio and video.

I followed the below steps to resolve.

Google VM Instance system Configuration  
Ubuntu 18.04
4vCPUs, 15GB memory
Allow HTTP traffic
Allow HTTPS traffic
Created

sudo apt update
sudo apt install apt-transport-https 
sudo apt-add-repository universe 
sudo hostnamectl set-hostname meet.example.org
hostname
sudo nano /etc/hosts 
127.0.0.1 localhost meet.example.org

curl https://download.jitsi.org/jitsi-key.gpg.key | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/jitsi-keyring.gpg'

echo 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list > /dev/null
 

sudo nano /etc/hosts
sudo apt install ufw
sudo ufw allow 80/tcp
sudo ufw allow 4443/tcp
sudo ufw allow 10000/udp
sudo ufw allow 10000:20000/udp
sudo ufw allow 22/tcp
sudo ufw enable
sudo ufw status verbose
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo apt update
sudo apt install nginx  
systemctl status nginx   
sudo apt install jitsi-meet 

ip a
ip addre show
sudo nano /etc/jitsi/videobridge/sip-communicator.properties

org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=localIP (Google VPS Internal IP)
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=publicIP

sudo nano /etc/systemd/system.conf
DefaultLimitNOFILE=65000
DefaultLimitNPROC=65000
DefaultTasksMax=65000

systemctl show --property DefaultLimitNPROC
systemctl show --property DefaultLimitNOFILE
systemctl show --property DefaultTasksMax

sudo systemctl daemon-reload
sudo systemctl status jitsi-videobridge2
sudo apt-get install wget
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

sudo systemctl daemon-reload
sudo systemctl restart prosody.service
sudo systemctl restart jicofo.service
sudo systemctl restart jitsi-videobridge2.service
sudo systemctl restart nginx

Please help me on this, did i followed the process anything i did wrong? In my console log there are no errors

**Comment by damencho** [comment]
Check out quick install guide advanced section https://jitsi.org/qi. This is firewall, jvb not announcing public address(you had covered that) or port forwarding not working.

**Comment by damencho** [comment]
Please use community forum before opening new issues.
