### ISSUE TITLE
jitsi-meet not working in Internet Explorer 11

### ISSUE THREAD

**Issue by abadamat** [jitsi/jitsi-meet#753]
I was tried to run video meeting on https://meet.jit.si/test123 in Internet Explorer but i have problem with pluggin (i guess). I installed webRTC plugin, chcecked IE extenssions - it's in good condition - turn on. If i try to follow meet.jit.si link, I have black screen or communicate allow camera and microfon. It's only text i don't see any button to do this. WebRTC plugin work correctly in this portal http://getaroom.io/.

In Google browser it's everythink ok. Anyone can help me?

**Comment by marquetd** [comment]
I also have the same problem.
Is it related to #256 (see comment from thedracle on 5 Apr)

Thanks
