### ISSUE TITLE
Mapping of TURN and Web Requests breaks TLS Handshake

### ISSUE THREAD

**Issue by elanfer** [jitsi/jitsi-meet#7540]
I was wondering why after a new installation the jitsi web frontend was running on port 4444 and I haven't found a 443 listener in sites-enabled. Moreover, openssl_client and ssllabs.com failed in doing a proper SSL Handshake. Aditionally NextGen Firewall blocked our jitsi service, because no proper handshake could be issued.

A test with ssllabs showed: No secure protocols supported, probably because the ssl upstream in the module config is not equipped with an ssl cert. As a workaround I removed the jitsi module from nginx config, and put my configuration in sites-enabled back on, that the interface is listening on 443 with certificate etc. again, like in previous version. After doing so ssllabs was able to check the server and my openssl clients worked too. 

Since turn port is specified by the videobridges, I'm not sure if we need the mapping that is done in the module. If so, we should put the mapping into the site configurations 443 listener instead proxying internally. 

Affected file:
https://github.com/jitsi/jitsi-meet/blob/29c16e42bd9553a5b32728c55a9cc4630e24b3e0/doc/debian/jitsi-meet/jitsi-meet.conf

**Comment by damencho** [comment]
The reason is simple to be able to run nginx on port 443, but to be able to run and coturn on the same address and port. 
coturn is used for relay of tcp media.
We decided sometime ago that we will remove that from the default install and will use standard turn ports and will just add doc how to make coturn use separate dns for the turn connections on port 443.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

**Comment by elanfer** [comment]
I think we're missing the point here. Based on this config from the current master branch, in a nginx setup, the ssl handshakes are not working properly. You can see this by executing `openssl s_client -connect meet.example.com` this is because an initial tls connection is failing before proxying is established, some firewalls and clients will have problems with this behaviour (like checkpoint firewalls).  

Or do you mean that you decided to remove this module?

**Comment by damencho** [comment]
So those requests are not h2 requests so that is the reason. Everything that is http/2 and have alpn web will be served as web the rest will be forwarded to the turn.
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.conf#L14

**Comment by elanfer** [comment]
Okay I understand, thank you. Wouldn't it be better than if web upstream is the default and turn requests are handled seperatly by header? I think the strict checkpoint firewall case I had, is not the only one. It seems like that the firewall is performing a preliminary SSL/TLS check, like OpenSSL client is doing this, with other packet types than http, when this check fails the connection will be blocked.

**Comment by damencho** [comment]
> Wouldn't it be then better, if the web upstream is the default and turn requests are handled seperatly by header?

That would be perfect, and that was how we started doing it, but we needed to open an issue on chrome side reporting they do not set ALPN for the turn tcp connections. They are currently working on that, but even when they fix it it will take 3 to 6 months to propagate that to clients. 



> It seems like that the firewall is performing a preliminary SSL/TLS check, like OpenSSL client is doing this, with other packet types than http, when this check fails the connection will be blocked.

I see. We will be removing that as I said and leave turn on default ports.
