### ISSUE TITLE
Not receiving frameRate for remote users in mobile, in web it's working fine.

### ISSUE THREAD

**Issue by bhavesh18** [jitsi/jitsi-meet#7547]
Hello,
I'm using getTrackByMediaTypeAndParticipant() method for getting users constraints but i'm only receiving values of local user that is same all the time. However, in the case of remote user(mobile/web) I'm getting empty object.

const videoTrack = getTrackByMediaTypeAndParticipant(this.props.state['features/base/tracks'], MEDIA_TYPE.VIDEO, item.id)
        
videoTrack && console.log('track-detail ', videoTrack.jitsiTrack.track. _constraints)

Response:->
------For local user------
{facingMode: "user", frameRate: 30, height: 360, width: 640}

------For remote user------
{}

Also, is there any way where I can get frameRate of all the participants in mobile?

Please help!

**Comment by Echolon** [comment]
Can you please fill out the issue template?
