### ISSUE TITLE
Add Android UI Featureflag

### ISSUE THREAD

**Issue by baijianghai** [jitsi/jitsi-meet#7548]
Can android add a featureflag that hides more (three points) @saghul @jcfischer

**Comment by Echolon** [comment]
@baijianghai please fill out the full issue template if you request a feature.

Please refuse from mentioning the developers.

**Comment by baijianghai** [comment]
Sorry， 
I will pay attention next time

**Comment by Echolon** [comment]
You should just provide more details, that was the question. Not a request to close this. But okay, what ever is good for you.
