### ISSUE TITLE
Adding awareness of physical proximity to jitsi

### ISSUE THREAD

**Issue by derhagen** [jitsi/jitsi-meet#7556]
**Is your feature request related to a problem you are facing?**
The problem is described in detail in this post: https://blog.derhagen.eu/2020/08/19/video-conferencing-is-broken-for-many-physical-scenarios.html
tl;dr we have a classroom with students and some students attending online, i.e. we see them on the beamer and hear them on the room speakers. It's just difficult to talk to them, since we don't have professional room microphones. Each student could fire up a jitsi client on their phone to speak to the online participants, but that makes feedback loops, if the lecturer does not mute the room speakers.

**Describe the solution you'd like**
Described in the same post.
Proposal for this issue: Allow the room host to define, that the current call involves both online and in-class participants. Upon joining, the participants can choose if they want to join in 'remote' mode, i.e. just as usual, or in 'physically attending' mode (called microphone-only in the post). In this mode, the audio is muted by default and the microphone is in a push-to-talk mode, also, it could make sense to hide the video of the other participants, since they are already on the beamer. Audio from 'physically attending'-clients is not played back on the host client, because we assume, that this one is connected to the room speakers.

More general use-cases mentioned in the post should be kept in mind building this.

**Describe alternatives you've considered**
- Have a room-wide microphone installation
- Pass around microphones
- Lecturer repeats all the questions from the audience
- Disable room speakers when students in class use jitsi to speak

**Comment by saghul** [comment]
It is a neat feature indeed!
