### ISSUE TITLE
Callback methods for Chat in IOS

### ISSUE THREAD

**Issue by Nihar8-ops** [jitsi/jitsi-meet#7557]
Having a listener about sending/receiving messages in mobile sdk would be of great help. Also option to enable/disable features like Kick out someone/mute someone.

**Comment by Nihar8-ops** [comment]
@Echolon Can you please check this feature-request on priority basis as my project is under development and it's release is getting delayed due to the requirement of this feature.

**Comment by Echolon** [comment]
This is not how it works here. Please also fillout the issue template.

**Comment by Nihar8-ops** [comment]
@Echolon where can i fillout the issue template?

**Comment by Echolon** [comment]
You see it if you click on `New issue`

**Comment by Nihar8-ops** [comment]
@Echolon please check Issue 7591
