### ISSUE TITLE
bad link on Jitsi doc page

### ISSUE THREAD

**Issue by kloro2006** [jitsi/jitsi-meet#7560]
here it is:

https://jitsi.github.io/handbook/docs/en/intro.html

**Comment by damencho** [comment]
Where do you see that link?

**Comment by kloro2006** [comment]
when you ask about an email from me, always please include a copy of
that email.

as to where i saw the link, the location is contained in the link, is
it not, or do i not understand yr quesiton?

On 8/20/20, Дамян Минков <notifications@github.com> wrote:
> Where do you see that link?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jitsi/jitsi-meet/issues/7560#issuecomment-678004060


-- 
who is now and then at https://meet.mayfirst.org/TomAndFriends

**Comment by Juny-34** [comment]
Link is broken @kloro2006 Please recheck. Seems you misunderstood @damencho's question.
