### ISSUE TITLE
[Mobile App Bug] Error on attempting to reconnect after being disconnected from the server

### ISSUE THREAD

**Issue by zhenghow93** [jitsi/jitsi-meet#7562]
### Description:

Got the following error when attempting to reconnect after being disconnected from the server.
`TypeError: url.replace is not a function`
It happens in both android and ios devices debug build.

### Steps to reproduce:

1. Join any room in Jitsi app.
2. To simulate the disconnection from the server, you may turn off device WIFI/data or restart the prosody service.
3. "You have been disconnected..." modal will appear. Either tap "Reconnect now" or wait for the reconnection countdown to complete.
4. The "url.replace is not a function" error appears.

### Expected behavior:

Reconnection should happen successfully without error.

### Actual behavior:
1. When you tap on the "Reconnect now" or waits for the countdown to complete, the error will appear.
![Simulator Screen Shot - iPhone 11 - 2020-08-21 at 14 42 59](https://user-images.githubusercontent.com/29766936/90863064-fc0a9780-e3c0-11ea-993e-6c8905c47c08.png)

2. This is the error screen:
![Simulator Screen Shot - iPhone 11 - 2020-08-21 at 14 43 07](https://user-images.githubusercontent.com/29766936/90863140-1fcddd80-e3c1-11ea-8f44-bb59009ff99a.png)

### Server information:
- it happens even when the app connects to meet.jit.si

### Client information:
- Browser / app version: 20.3.2 (built from the "mobile-20.3" branch)
- Operating System: Android 10 / iOS 13.4.1

### Additional information:
The issues reported above happened on debug build, never tried if it would crash a release build.

Interesting observation when trying to reproduce the issue using the Jitsi Meet app freshly downloaded from Google Play Store:
- using an android device, enter any room which has another user connected to meet.jit.si server
- turn off wifi/mobile data of the device and wait for the "you are disconnected" modal to appear
- taps "Reconnect now" while wifi/mobile data is off, it won't crash the app, but it will go back to the conference screen, as if it has successfully reconnected (impossible as there is no internet). The other user still sees the thumbnail video of this disconnected user, without video & audio.
- turn on wifi/mobile data of the device, exit the "falsely reconnected" conference screen and re-enter the same room.
- the other user will see 2 duplicated thumbnails of the user that was disconnected before.

**Comment by dofl** [comment]
I have seen the same, although you cam a bit further with debugging: https://github.com/jitsi/jitsi-meet/issues/7453
