### ISSUE TITLE
"Enable Lobby" feature doesn't work with xmpp_password_override in secure domain

### ISSUE THREAD

**Issue by shubham2110** [jitsi/jitsi-meet#7568]
### Description:

"Enable Lobby" doesn't show up when using 'xmpp_username_override' and 'xmpp_password_override'  in local storage to login. 
But when I "Grant Moderator" to some other guest, "Enable Lobby" appears in his windows.

### Steps to reproduce:

1. Set xmpp_username_override and xmpp_password_override in local storage for the domain.
2. Open any conference , you will become administrator by default if password is correct.
3. Clicking on security tab doesn't show "Enable Lobby" option. 

Enable lobby only show up when I don't login through xmpp_username_override and xmpp_password_override

### Expected behavior:

"Enable Lobby" should be visible to all administrator no matter how user has logged in. 

### Actual behavior:

as explained earlier, Enable lobby is not showing in security button if logged in by xmpp_password_override

### Server information:

- Jitsi Meet version: Latest Unstable (on date 23.08.2020)
- Operating System: Ubuntu 18.04 with prosody 11.5

### Client information:

- Browser / app version: Chrome
- Operating System: Any

**Comment by damencho** [comment]
xmpp_username_override uses a specific domain have you enabled lobby for that domain?

Please when you have questions or problems use the community forum before opening new issues.
