### ISSUE TITLE
Jitsi reconnects on hosting meeting in a loop. Meeting reconnect in a half minute. 

### ISSUE THREAD

**Issue by mitesh-rathod** [jitsi/jitsi-meet#7570]
![image](https://user-images.githubusercontent.com/37058536/91005385-65262100-e5f4-11ea-9e33-989f4a9b946d.png)

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/issues/7522#issuecomment-679094321

I'm closing this as this is a configuration problem and not a jitsi-meet issue. Please use the community forum before opening new issues.
