### ISSUE TITLE
not can use android jitsi-meet-sdk-2.9.3.aar 

### ISSUE THREAD

**Issue by baijianghai** [jitsi/jitsi-meet#7573]
### Description:

Use 2.9.3 aar to import the project and the following error occurs

![微信图片_20200825112825](https://user-images.githubusercontent.com/6112837/91119736-92db9a80-e6c6-11ea-9dc5-c60412457cb6.png)

### Steps to reproduce:

1. Open the JitSiSDKTest project import 2.9.3 aar

2. run the JitSiSDKTest project

3. The PermissionAwareActivity class of not found

### Expected behavior:

run successful 

### Actual behavior:
error occurs

### Server information:

- Jitsi Meet version: jitsi-meet-sdk-2.9.3.aar
- Operating System:Android

### Client information:

- Browser / app version:android 9
- Operating System:android system

### Additional information:
 
Please help me for this problem，thanks very much

**Comment by Echolon** [comment]
@baijianghai have you check the community portal for this?

**Comment by baijianghai** [comment]
@Echolon I don't anything,just integrated aar into the demo,
I have a problem with the steps of integrating aar?

**Comment by jayarajm** [comment]
Is anybody get solution for this issue?

**Comment by saghul** [comment]
Please use the latest SDK (3.0) and make sure you either use our pro-guard rules file or disable pro-guard altogether.
