### ISSUE TITLE
Screenshare freezes for one viewer who keeps having to re-enter the meeting

### ISSUE THREAD

**Issue by danmanrana** [jitsi/jitsi-meet#7578]
### Description:

Person can't view another's screenshare without re-entering the meeting.

### Expected behavior:

Person should be able to view other's screenshare without the screenshare freezing on their end.

### Server information:

- Jitsi Meet version: meet.jit.si

### Client information:

- Browser / app version: Safari and Chrome
- Operating System: Mac

Versions unknown (person having issues doesn't have much time to help troubleshoot).

**Comment by Echolon** [comment]
Are you able to reproduce the issue?

**Comment by pgenderson** [comment]
Yup, just did. MacOS 10.13.6 on Safari 13.1.2. Screenshare started on my other computer froze on the Mac when I ended the screenshare, but starting a new screenshare shows the new one fine, until it ends again.

**Comment by alfonsolsl** [comment]
Same issue here,  when i share screen the others only see a black screen, eventually if as the same time i activate my screen the screen sharing goes as expected but if i turn off the camera is a black screen again (i can't be recovered at this point).

This is happening this week.

i'm using firefox on windows 10 and the other clients are using iPad version of the app, iphone versions and desktop version on Mac OS on chrome explorer.

**Comment by rfrelow83** [comment]
Confirmed, I’ve been seeing this for a few days as well.

**Comment by alfonsolsl** [comment]
This is my client view when i share the screen, this time the open camera does not work and was impossible to fix.

I dont know if this is the same bug of the post.

![image](https://user-images.githubusercontent.com/6255385/91594635-d54fe200-e927-11ea-961b-71ac564b1882.png)

When i cancel the sharescreen my webcam image was freeze and i have to leave the room and re-enter and have several video frezzen lapses after that.

**Comment by alfonsolsl** [comment]
#7551 

Maybeeee this is triggering a low quality BW protection and turning off the cast to improve the audio?

Is the only thing was merging in the last 8 days that touch video quality and dimensions.

**Comment by alfonsolsl** [comment]
Confirming the Youtube didn't work either in my case, i see the video playing but the other parts only see a Video Unavailable black screen. Unfortunately this made Jitsi Meet unusable for my needs and have to switch urgently. Sad, and i hope you fix it soon guys.


![image](https://user-images.githubusercontent.com/6255385/91614660-903ba800-e947-11ea-9cc1-5ce265d8b269.png)

**Comment by breversa** [comment]
The same happened to me today from meet.jit.si

I'm using Firefox 80 on Linux Mint 20.
The other person used Firefox 80 on Windows 10.

Their video starts just fine, but during a screen share it would then freeze after a 2-3 minutes.
It also freezes during webcam video but much less frequently.

Audio remains totally fine during the whole session.

**Comment by pgenderson** [comment]
Anyone know if there's a previous build that we can use for the time being that doesn't have this bug?

**Comment by pgenderson** [comment]
It works fine when the screensharer's using Chromium (and I guess Chrome too) and the Mac's using Chrome or Firefox (failed on Safari).

**Comment by nmaludy** [comment]
Confirmed this also happens on 8x8.vc as well. Just had to cancel my subscription because of it.

**Comment by pgenderson** [comment]
@nmaludy have you tried it with the Electron client?

**Comment by nmaludy** [comment]
@pgenderson no i have not, didn't know one existed, i just use my browser (Firefox and Chrome). It's weird because i can see screenshare fine locally, but all others in the meeting have it keep freezing on them, or they have to refresh in order to see it.

**Comment by pgenderson** [comment]
@nmaludy that's the exact same problem I had, so I just told everyone to use Chrome/Chromium and I use the Electron client because I don't want to use Chromium (but it uses the Chromium engine to render the JS and all).

**Comment by asim29** [comment]
We've been facing the same issue, tried with Ubuntu 18.04 using Firefox as well as Chromium. Screenshare freezes and then I'm unable to share the screen again

**Comment by pgenderson** [comment]
@asim29 did you already rule out Wayland? Not sure if this thread's related to that issue.

**Comment by tareefdev** [comment]
We started to face this issue recently. We use different Linux distributions with some uses Mac. All of us face this issue often, where a person needs to keep re-refreshing jitsi window in order to re-see the share screening session. We have our instance of jitsi (the latest version)

**Comment by Basilisvirus** [comment]
I have the same issue, Screen sharing or even during a call, the video freezes. The solution is to refresh the page. I have this issue for a couple of years now.
