### ISSUE TITLE
Jitsi front camera and any camera is not working in Vivo devices

### ISSUE THREAD

**Issue by gauravgg** [jitsi/jitsi-meet#7585]
I have checked after bulk testing jitsi on mobile browser is not working in maximum of Vivo devices and some in motorola devices. Please give me any solution for this. It is creating a serious loss to us.

**Comment by Echolon** [comment]
@gauravgg Please fill out the issue template and provide steps to reproduce.

For the moment I will close this. Please ping me if you have done this.
