### ISSUE TITLE
Firefox android doesn't allow to access the camera when using Jitsi JS API (iFrame).

### ISSUE THREAD

**Issue by olanda0** [jitsi/jitsi-meet#7590]
### Description:

In Firefox Android, when we are using the JS API from our website, the web asks for permissions to use the camera, but the camera is disabled at startup. Also, when we try to activate the camera manually by clicking on the icon, an error appears that doesn't allow the camera to be enabled.

### Steps to reproduce:

1. Use Firefox v79 in Android
2. Use the Jitsi JS API (iFrame)

### Expected behavior:

The video call starts properly (with the camera on).

### Actual behavior:

The video call starts but the camera is disabled, and cannot be enabled manually by clicking on the camera icon.

![join](https://user-images.githubusercontent.com/70322851/91436423-5fd10c80-e868-11ea-815c-5d453103ae0a.jpg)

![jitsierror](https://user-images.githubusercontent.com/70322851/91436491-85f6ac80-e868-11ea-96f8-def39327c9ac.jpg)

![Captura de pantalla de 2020-08-27 13-03-26](https://user-images.githubusercontent.com/70322851/91436538-9870e600-e868-11ea-842d-c91f15848fd0.png)

![Captura de pantalla de 2020-08-27 13-04-10](https://user-images.githubusercontent.com/70322851/91436545-9c046d00-e868-11ea-8f47-8e24bce868ce.png)

### Server information:

- https://meet.jit.si/

### Client information:

- Browser / app version: Firefox for Android Version Version 79.0.5: August 17, 2020
- Operating System: Android Version 10 QKQ1.190910.002
[](url)

**Comment by Echolon** [comment]
rel. Meta - camera issues #5425

**Comment by cicerabrena** [comment]
Hi, i'm facing the same issue, did you find a solution ? The problem still persist even after the update of **firefox for android** for v80
