### ISSUE TITLE
Callback methods for Chat in IOS

### ISSUE THREAD

**Issue by Nihar8-ops** [jitsi/jitsi-meet#7591]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
I want  information about the outgoing chat message as i need to save them in my database for future references but as i am not getting any callbacks for it .. i am not able to do that.
**Describe the solution you'd like**
Please describe the desired behavior.
I just want a callback function with the message body like the conferencedJoined function so that i can save the messages in my database.
**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
I didn't found any alternative solutions or features to be considered for this purpose

**Comment by Nihar8-ops** [comment]
@Echolon As you have told, i have filled the issue template. Please help me out here.

**Comment by Nihar8-ops** [comment]
#7557

**Comment by damencho** [comment]
Is this database local to the device? Or you want in general to store all messages as if its a global database you should do that on the server-side ... a lua module in prosody that saves all the messages.

**Comment by Nihar8-ops** [comment]
@damencho The database is local to the device..so it would be extremely helpful for me and also others developer if there is a callback for the outgoing messages .

**Comment by saghul** [comment]
New APIs are required on the SDK for this. It's already labelled with "feature-request" but we cannot provide an ETA.
