### ISSUE TITLE
Actively shared screen not visible to sharer after also activating&deactivating his/her own camera

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7593]
### Description:

Person A and Person B are in a video conference and both persons have turned their cameras on.
Person A shares his screen. Both Person A and Person B sees Person A's screen instead of his camera (expected).
Now, Person A also turns on his camera. Both Person A and Person B sees Person A's screen and camera (expected).
Now, Person A turns off his camera (but continues sharing the screen). Person B continues sees only Person A's screen (expected).
However, Person A doesn't see his own screen anymore even though he is still sharing the screen. The only indicator that Person A is still sharing is the highlighted sharing button in the bottom left.

### Steps to reproduce:

1. Turn on camera
2. Turn on screen sharing
3. Turn on camera 
4. Turn off camera

### Expected behavior:

When I turn off my own camera, I expect that I as the screen sharer continue to see the shared screen as well.

### Actual behavior:

When I turn off my own camera, I don't see that I am sharing the screen.

### Server information:

- Jitsi Meet version: live on meet.jit.si (as of 27.8.2020)
- Operating System: live on meet.jit.si (as of 27.8.2020)

### Client information:

- Browser / app version: Chrome 85.0.4183.83 (beta)
- Operating System: MacOSX 10.15.5

**Comment by jallamsetty1** [comment]
Thank you for the report, I was able to reproduce it after a few attempts that turning my camera on/off while screenshare is in progress.

**Comment by jallamsetty1** [comment]
This has been fixed in the latest unstable - https://github.com/jitsi/jitsi-meet/pull/7799
