### ISSUE TITLE
P2P conference not changing to JVB conference when third user joins from mobile (on own server)

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7594]
### Description:

On my own server, I have experienced a reproducible issue, where the video conference for two browser users would stop transmitting data if a user from mobile application joins the same conference. The two original users in browser are most likely in P2P mode because the **config.js** has `p2p: { enabled: true }`. However, when the third person joins from mobile it should switch to JVB connection, but somehow it doesn't transmit video/audio anymore.
If a fourth person joins the conference from mobile device, the two mobile user can communicate with each other (audio/video) but the two desktop users are just empty users who don't receive or transmit any audio/video.

The odd thing is that I cannot reproduce this issue on [meet.jit.si](meet.jit.si). So it must be something with my configuration. 

Please find my [config.js](https://gist.github.com/mfts/acefa25d852becc9292cf111d9f43a49#file-config-js) and [interface_config.js](https://gist.github.com/mfts/acefa25d852becc9292cf111d9f43a49#file-interface_config-js) in one gist.  

### Steps to reproduce:

1. Two users join a conference on desktop browser
2. A third user joins the conference from mobile app
3. The two desktop browser users are visible but neither audio nor video works for them and they don't hear anyone else.  

### Expected behavior:

When the third user joins from mobile, he will join the conference and see the other users video/audio and vice versa.

### Actual behavior:

When the third user joins from mobile, he sees two other users but doesn't see their video/audio and they don't see his either.

### Server information:

- Jitsi Meet version: Docker [stable-4857](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4857)
- Operating System: Linux Debian 10

### Client information:

Desktop Client:
- Browser: Chrome 85.0.4183.83 (Official Build) beta (64-bit)
- Operating System: Mac OSX 10.15.3

Mobile Client:
- App Version: 20.3.2 (own application from [ios-20.3.2](https://github.com/jitsi/jitsi-meet/releases/tag/ios-20.3.2) release)
- Operating System: iOS 13.6

**Comment by damencho** [comment]
When you have problems or questions please use the community forum before opening new issues.

Most probably this is a configuration issue firewall, ports not forwarded or jvb not announcing its public address. Follow advanced section of quick install guide. https://jitsi.org/qi.
