### ISSUE TITLE
It is always broken

### ISSUE THREAD

**Issue by seeeeebas** [jitsi/jitsi-meet#7599]
Hello everyone,
I am trying to create some conferences using meet.jit.si

It is always broken. You just cannot have smooth video, also the audio always goes after the video.
When you turn off the video it is more or less OK.

I do not have any internet speed issues it is high enough. But jit always says I do, it is almost always red, jumping up and down.

The other participants are in the same country.

Anyone knows what is wrong and how to fix it? Or I just have to use something else?

I cannot nor I want to reprogram/fix/change code etc.

**Comment by Echolon** [comment]
@seeeeebas can you please fill out the issue template and provide a proper title?

**Comment by seeeeebas** [comment]
> @seeeeebas can you please fill out the issue template and provide a proper title?

Hi there, thanks for the reply. I was really fed up with it. I set up my own server. This is magic.

**Comment by saghul** [comment]
We did have some packet loss issues at our servers a while ago, but that is solved now.
