### ISSUE TITLE
Different view in Mobile browser

### ISSUE THREAD

**Issue by PRAVEENKUMARRAJENDRAN** [jitsi/jitsi-meet#7603]
Dear team 
   When i use meet.jit.si in mobile browser I get different view whereas when I use my self hosted jitsi meet in mobile browser I get different view and also I’m not able to enable and disable
![Screenshot_20200831-110033_Chrome](https://user-images.githubusercontent.com/41237738/91686277-77670880-eb7a-11ea-9453-76d26b31e951.jpg)
![Screenshot_20200831-105114_Chrome](https://user-images.githubusercontent.com/41237738/91686302-851c8e00-eb7a-11ea-8a38-d119fbca40e4.jpg)
I have attached both the views screenshot for your refernece

Thank you team

**Comment by damencho** [comment]
Probably the version is different. We will update stable probably today.

Please when you have some questions or problems use the community forum before opening new issues.

**Comment by PRAVEENKUMARRAJENDRAN** [comment]
Okay sir. Thank you
