### ISSUE TITLE
Safari Screensharing does not go away when stopped from other participant

### ISSUE THREAD

**Issue by razor0001** [jitsi/jitsi-meet#7608]
### Description:

When there are two or more participants and one shares the screen, the one who receives the screen freezes (does not go away) when the other one stops screensharing. Only happens on Safari (Desktop + Mobile). Sometimes it also happens with video that it freezes.

### Steps to reproduce:

1. Open meet.jit.si
2. Join as second participant with Safari
3. Share Screen from first one
4. Stop screensharing
5. Screen stays on Safari

It is everytime reproducable. This is a critical issue because at this point in time when it happens it prevents from starting camera.

It does not happen when the participant who shares the screen first starts the camera

### Expected behavior:

Screenvideo should go away as in Chrome, Firefox..

### Actual behavior:

Screen stays

### Server information:

- Jitsi Meet version: current stable
- Operating System: iOS, Windows..

### Client information:

- Browser / app version: Safari (every version)
- Operating System: iOS, MacOS

**Comment by razor0001** [comment]
I found this bug https://github.com/jitsi/jitsi-meet/issues/7147 which seems to be the same one but was created in June. Is there any investigation here? It seems to be a critical one.

**Comment by razor0001** [comment]
Here are the logs which are different to Chrome:

Chrome and Safari:
`
[modules/xmpp/JingleSessionPC.js] Processing removeRemoteStream
[modules/xmpp/JingleSessionPC.js] ICE connection state:  connected
`
after the logs above only in Safari:
Renegotiate: setting remote description

**Comment by Echolon** [comment]
> I found this bug #7147 which seems to be the same one but was created in June. Is there any investigation here? It seems to be a critical one.

I will close this in favor of this. Please use the search function before opening a new issue.

**Comment by razor0001** [comment]
Thanks, but how do I know if there is any update regarding this? Because in the other issue there was no update since ~3 months for kind of a critical issue.

**Comment by Echolon** [comment]
Please comment then in the related issue.

As you can see there is a ton of open issues and the team has to prioritise on many things :/

However PR are welcome.
