### ISSUE TITLE
Mobile web version shows small icons

### ISSUE THREAD

**Issue by razor0001** [jitsi/jitsi-meet#7609]
### Description:

Current version on meet.jit.si 4370.993 shows small mobile icons (camera, mic). It was fine in the last stable version.

### Steps to reproduce:

1. Open meet.jit.si in mobile web version

### Expected behavior:

Icons should be larger on mobile. Last version (I think 4289) was fine

### Actual behavior:

![image](https://user-images.githubusercontent.com/1540088/91893136-fbf97a00-ec93-11ea-9313-2c9ae1c65085.png)

**Comment by Echolon** [comment]
Can you tell us device and system please? also the resolution?

**Comment by razor0001** [comment]
It's on every device, iOS, Chrome, Android. It's also if you just open devtools and activate mobile view on desktop. It seems to be simple a CSS error

**Comment by ramrami** [comment]
Also the "menu" button is not visible any more 😞

**Comment by beyondlevi** [comment]
Any clue about what is causing this? Or a hotfix?

**Comment by jallamsetty1** [comment]
This has been fixed in the tip of the master - https://github.com/jitsi/jitsi-meet/commit/9379bb3c5b56b1ebac5215a926d4e83beeb6adac.
