### ISSUE TITLE
No audio out if mic and cam permissions has blocked

### ISSUE THREAD

**Issue by mrin** [jitsi/jitsi-meet#7610]
### Description:

Participant who has blocked mic & cam permissions doesn't hear audio from other participants.

### Steps to reproduce:

1. Open Chrome, go to https://meet.jit.si and set permissions of mic & cam to "Ask (default)", then reload page
2. Go to https://meet.jit.si/testnoaudio123, on permission popup click "Block"
3. Connect other participant to the room. The first participant doesn't hear others.

![Annotation 2020-09-03 143738](https://user-images.githubusercontent.com/93999/92110303-29a90500-edf3-11ea-82f4-84e1a295d45f.jpg)

### Expected behavior:

The first participant (with blocked mic & cam) have to hear others.

### Actual behavior:

The first participant (with blocked mic & cam) doesn't hear others.

### Client information:

Win 10
Chrome 84.0.4147.135, 85.0.4183.83

### Additional information:

Seems like error something like that:

`
AbstractAudio.js:84 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
play	@	AbstractAudio.js:84
(anonymous)	@	middleware.js:41
(anonymous)	@	middleware.js:17
(anonymous)	@	middleware.js:24
`

The error goes to "sounds/middleware.js", but the actual track which is in audio element with id="remoteAudio_489cf8a6-a352-4386-b692-89009a864a1d-2" is paused, when I handle audio.play() in console the sound starts play.

The reason why I came across on that bug I tried to set startWithAudioMuted & startWithVideoMuted in true and merged pull request https://github.com/jitsi/jitsi-meet/pull/6638 to hide permissions request popup by default (upon device request). So even if permissions have not prompt - no audio out.

**Comment by Echolon** [comment]
Can you do a webrtc test?

**Comment by mrin** [comment]
test.webrtc.org
Log file: [testrtc-2020-09-03T11_32_15.575Z.log](https://github.com/jitsi/jitsi-meet/files/5168221/testrtc-2020-09-03T11_32_15.575Z.log)
