### ISSUE TITLE
Incorporate maintenance of the JWT plugin Jitsi Meet relies on into the Jitsi project

### ISSUE THREAD

**Issue by dantman** [jitsi/jitsi-meet#7611]
Please move maintenance of the luajwtjitsi Lua library into the Jitsi project (i.e. fork it to the jitsi GitHub org and allow for contributions just like jitsi-meet).

## Background

Token authentication for Jitsi Meet (jitsi-meet-tokens / token related prosody plugins) depends on the `luajwtjitsi` Lua library.

The Lua library luajwtjitsi ([paweldomas/luajwt](https://github.com/paweldomas/luajwt), [luarocks](https://luarocks.org/modules/pawelgawel88/luajwtjitsi)) has not been updated for 3 years. It's a fork of `luajwt` which was abandoned 4 years ago.

luajwtjitsi depends on the [luacrypto](https://luarocks.org/modules/luarocks/luacrypto) library. A project not updated in 6 years and incompatible with the current version of libssl. It appears to be de facto replaced by [luaossl](https://luarocks.org/modules/daurnimator/luaossl).

@ramon-garcia has already kindly done the work of porting luajwtjitsi to using luaossl and made a PR (paweldomas/luajwt#4). But because there is no-one maintaining this jitsi fork of a lua library that is a critical dependency of jitsi-meet's token auth, the contribution has just been left there with no-one to merge it.

Because this is a jitsi-specific fork of a Lua library and is a library that is critical to Jitsi Meet, I think maintenance of it should be under control of the Jitsi community.

**Comment by damencho** [comment]
This already available in jitsi organization https://github.com/jitsi/luajwt, we just need to find time to work on that ...

**Comment by damencho** [comment]
@saghul are you aware of the process of pushing a new lua module for lua rocks?

**Comment by bill2004158** [comment]
any update about this?  I cannot install it on Ubuntu 20.

**Comment by saghul** [comment]
The plugin has since been updated.
