### ISSUE TITLE
Enable to bypass the "choose app/browser" page on mobile

### ISSUE THREAD

**Issue by jibe-b** [jitsi/jitsi-meet#7613]
I use a jitsi room embedded in an iframe and already pass a few configuration keys in the URL : https://jitsi.example.com/room#config.startWithAudioMuted=true&startWithVideoMuted=false&config.requireDisplayName=true

Thanks a lot for having enabled using jitsi directly in the browser on mobile! That makes a big difference.

Is possible to set "Launch in browser" by default on mobile?

My mobile users are annoyed of having to click on the page

![Screenshot from 2020-09-02 08-59-15](https://user-images.githubusercontent.com/6146483/91942168-c2a82500-ecfa-11ea-8901-b8a1100a4b98.png)

and we happen to leave the room & join back a few times a day (saving bandwidth when not actively discussing).

What would fit my needs the easiest way would be a configuration key to be passed in the URL `defaultLaunchInBrowserOnMobile=true`

Thanks a lot for the amazing work you provide! It's time for me to consider support financially the development of Jitsi :)

**Comment by Aokromes** [comment]
maybe duplicate of https://github.com/jitsi/jitsi-meet/issues/7612 ?

**Comment by jibe-b** [comment]
Thanks @Aokromes, you're right! I copied my description of the need in the other issue, let's follow the other thread.
