### ISSUE TITLE
No video shown on mobile when two users on desktop browser are joined by a third mobile app user

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7614]
### Description:

I have run into something strange. When two browser users are using A/V to communicate and then a third user from a mobile application is joining them. When the mobile user joins without video initially, he can see that the browser users have turned their video on (no video off icon) but in fact the video stream is not transmitted. 

Now when the mobile app user turns on his/her own video then the video stream of the other two browser users are also seen.

After the initial turning on of the video for the mobile user, she can turn it off and still see the video streams. But the initial video toggle is required to see any video stream.

This happens on both meet.ji.si and my private instance.    

### Steps to reproduce:

1. Start video conference between two users both on desktop browser
2. Both users turn on their video
3. A third user joins from mobile application without video turned on
4. Mobile user cannot see the video streams
5. Mobile user turns his/her video on, now mobile user can see the other video streams including his/her own

### Expected behavior:

When the mobile user joins a conference with two other users who have their video turned on, she should see the video streams of the other users, even if her own video is turned off.

### Actual behavior:

When mobile user joins a conference with two other users who have their video turned on, she does not see the video streams of the other users unless she also turns on her video.

![IMG_4057](https://user-images.githubusercontent.com/4049052/91942657-f63b7d00-ed03-11ea-9dc2-91324a5736d6.png)

### Server information:

- Jitsi Meet version: meet.jit.si (as of 1.9.2020)
- Operating System: meet.jit.si (as of 1.9.2020)

### Client information:

- Browser: Google Chrome Version 85.0.4183.83 (Official Build) beta (64-bit)
- Operating System: MacOSX 10.15.6

- App: 20.3.2 build 83
- OS: iOS 13.6

**Comment by gocontractdev** [comment]
Hey Marc is my colleague; I take it from here.

The same problem still exists:

// When joining only with sound
// Version of the app: newest on Android

> Internal Report (this is for us):  JITSI-926

Best,

![alt text](https://i.ibb.co/VxZgWLR/photo-2021-03-17-15-02-40.jpg)

**Comment by gunika1321** [comment]
Hi, I am facing a similar issue when one user has joined from jitsi web and the other has joined through app no video stream is visible. I am using my own deployment of jitsi.
