### ISSUE TITLE
Unable to select speaker output in Safari 

### ISSUE THREAD

**Issue by franken300** [jitsi/jitsi-meet#7615]
### Description:
As a user I want to switch to a different speaker when using Jitsi on Safari to hear other participants. 
However, it is not possible to switch to a different speaker as there are no options present in the settings. This issue only occurs in Safari. When switching to Firefox or Chrome I am able to select other speakers. (see screenshot) 
This issue has been reproduced on two seperate devices. 

### Steps to reproduce:
1. Open a random meeting on meet.jit.si using Safari
2. On the prejoin screen select a different audio device 
3. No speaker options are shown

Restarting device does not change behavior 
Deleting cache, cookies or ingocnice does not change behavior 
Reconnecting external audio devices does not change behavior 
Removing all external audio devices does not change behavior 

### Expected behavior:
I should be able to switch to a different speaker. As shown in this screenshot when using Chrome. 

![image](https://user-images.githubusercontent.com/69365535/91967813-09564900-ed14-11ea-80b8-46e8332b233e.png)

### Actual behavior:
The list of speakers is empty as shown below in this screenshot

![image](https://user-images.githubusercontent.com/69365535/91956798-77dfda80-ed05-11ea-9ddc-75fd59144598.png)

### Server information:
Issue persists and can be reproduced in Jitsi Meet :  
 - Selfhosted (1.0.4289 ) 
 - meet.jit.si 
 - beta.meet.jit.si 
 - alpha.jitsi.net 

### Client information:
Browser :
- Safari 14 

Operating System:
 - MacOS 

Device: 
 - iMac (Retina 5K, 27-inch, Late 2015)

Operating System:
MacOS 11.0 bèta (20A5354i)

### Additional information 
DevTools Console included generated from meet.jit.si. Showing a warning `[Warning] 2020-09-02T09:42:02.107Z – "[features/base/devices]" – "Failed to set audio output device.`

[Console-jitsi.txt](https://github.com/jitsi/jitsi-meet/files/5161503/Console-jitsi.txt)

**Comment by jallamsetty1** [comment]
Safari doesn't enumerate the Audio output devices and therefore doesn't let us change/select audio output devices. Closing this issue since it is a browser limitation.
