### ISSUE TITLE
FR: Please provide better Changelogs

### ISSUE THREAD

**Issue by ulab** [jitsi/jitsi-meet#7617]
**Is your feature request related to a problem you are facing?**
It is difficult to figure out what has changed in a new release. Commit messages like "Merge pull request #7508 from abora8x8/abora/vpass" or "fix syntax error" don't say anything helpful in the Changelog.

**Describe the solution you'd like**
Please provide a short summary of important changes / new features or issues to look out for. Updating an installation is a game of luck otherwise.

**Describe alternatives you've considered**
Not upgrading with new packages. ;-)

**Comment by Echolon** [comment]
#6168
