### ISSUE TITLE
Share YouTube video from server

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7620]
**Is your feature request related to a problem you are facing?**
If a participant share a YouTube video, then all clients build up a connection to YouTube.

**Describe the solution you'd like**
For data privacy, it would be better when only the server build up a connection to YouTube and shares the stream to the clients.

**Comment by Echolon** [comment]
#6156

**Comment by heikar** [comment]
Hi @Echolon ,
i mean the way from YouTube to the participants, not the streaming from the meeting to YouTube (`Share a YouTube video`).
