### ISSUE TITLE
IFrame API: readyToClose event notification does not fire anymore

### ISSUE THREAD

**Issue by alariej** [jitsi/jitsi-meet#7628]
**readyToClose** event notification does not fire anymore when pressing the Hangup button. Perhaps related to PR https://github.com/jitsi/jitsi-meet/pull/7449. It was working up to a few weeks ago, and nothing has changed in our Jitsi Meet IFrame API setup since then.

Using latest production API with `<script src="https://meet.jit.si/external_api.js"></script>`

Tested in Chrome and Firefox on Ubuntu 18.04.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

https://community.jitsi.org/t/listening-to-event-readytoclose-in-iframe-jitsi/76610/3?u=damencho

**Comment by jainaakash1002** [comment]
readyToClose event is not working for the latest build

**Comment by saghul** [comment]
This issue is really old. Please open a new one and provide steps to reproeuce it.
