### ISSUE TITLE
iOS participant (on the mobile browser) stops send video after the third participant enter in the room

### ISSUE THREAD

**Issue by crprata** [jitsi/jitsi-meet#7636]
### Description:

With two participants in the room, one using the desktop and the other iOS mobile browser, when the third participant enters the room, everyone’s view is automatically changed to the grid view, and the iOS participant stops send video. He must reload the page/jitsi (iOS participant) to send video again.

This bug happens in meet.jit.si as well.

### Steps to reproduce:

1. Start a meeting (meet.jit.si) with two participants, one on desktop and another on the iOS mobile browser.
2. Join the third participant 
3. Video of the iOS participant stops, after a change to grid view automatically.

### Server information:

- Jitsi Meet version: Latest Stable (same of meet.jit.si)
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: Safari
- Operating System: iOS 13.6.1

**Comment by saghul** [comment]
Can repro. @jallamsetty1 can you PTAL?

**Comment by jallamsetty1** [comment]
@crprata , thank you for the report. This turned about to be a bug in Safari on iOS. When only the lowest 180p stream is enabled, Safari doesn't send video at all. However, if you request higher resolution (by pinning the participant) on one of the clients, you can see that 180p stream is enabled along with the HD streams. I am going to file a bug with webkit and update it here.
The workaround for now is to pin the iOS participant.

**Comment by crprata** [comment]
@jallamsetty1 Thanks for your reply. I've verified that if I use "enableLayerSuspension: false", the problem doesn't happen.

Is it possible to change in my own server the lowest stream to 240p instead of 180p using?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 Thanks for your reply. I've verified that if I use "enableLayerSuspension: false", the problem doesn't happen.
> 
> Is it possible to change in my own server the lowest stream to 240p instead of 180p using?

Yes, if you have your own deployment, you could disable layer suspension. I suspect it doesn't matter if the lowest layer is of a different resolution. I think the act of switching from 3 layers to 1 layer is triggering this issue. If iOS client is the 3rd participant, we start sending only the LD stream and it works in that case. Moreover, in order to have 240p as lowest simulcast stream, the camera needs to be started with 960p which is not a standard resolution supported by all the devices.

**Comment by jallamsetty1** [comment]
I don't see this issue happening on meet.jit.si anymore. Closing the issue, please feel free to re-open it if you still see it.
