### ISSUE TITLE
URL parameters not working on different instances

### ISSUE THREAD

**Issue by jtarrico** [jitsi/jitsi-meet#7637]
While using parameters such as:

startWithVideoMuted=true
startWithAudioMuted=true
userinfo.displayName="My_name"
roomPassword="My_password"

I found that this works on some instances and does not on others:

https://meet.yapbreak.fr/IY1WHZZEO9KP3QWTHY6LWQWZ4G#userInfo.displayName="Jitsiboy" - WORKS
https://meet.nevers-libre.org/D8X5QV2FKL1I4P9GS8LWGBIPCK#userInfo.displayName="Jitsiboy"  - DOES NOT WORK

And this repeats itself with the other remaining parameters.

Is there any way to know if this feature is available or not in advance before choosing an instance ?? 

Thanks

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

You can find the version you need/work and you may check the HTML source which version is running there:
The first one version:
![image](https://user-images.githubusercontent.com/3263098/92250760-7e02c200-ee91-11ea-96bd-035b535b0daa.png)

The second one version:
![image](https://user-images.githubusercontent.com/3263098/92250740-75aa8700-ee91-11ea-9d65-43788d2384a6.png)
