### ISSUE TITLE
UUID or hash as suggested room name

### ISSUE THREAD

**Issue by GinoMalatesta** [jitsi/jitsi-meet#7639]
I installed my first Jitsi instance for a German corporate customer, works great.
The only thing they complain about, are the room name suggestions, which sometimes could look a bit wild, for uptight German executives.

My suggestion would be an option, to either have something like a long hash value as a suggested name, or even better, a simple UUID, which could be generated with uuidgen, available on most Linux distros.

I'm going to make something like that myself in js-utils/random, found a description already, but would be great to have that as a general feature.

**Comment by saghul** [comment]
I'd say it's acceptable, if controlled with a setting in config.js, and the current behavior is retained. Feel free to work on it and send a PR when ready for feedback!
