### ISSUE TITLE
Tile View button missing when `You are the only one in the meeting`

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#7643]
Jitsi Meet no longer has the `Tile view` button when `You are the only one in the meeting`.

This button used to be available, but now only shows when there is someone else also in the meeting.

Having a tiled layout enabled this to be set before people arrived and also made it easier to see when people arrive to a meeting as you don't need to be very close to the computer screen.

Can this button be once again available when when `You are the only one in the meeting`?

Thank you

Linux Mint 20 Cinnamon
Firefox 80.0

**Comment by saghul** [comment]
This change was intentional. We've made some adjustments and if the user doesn't change it, it will switch to tile-view mode when a 3rd participant joins.

The "alone" experience is bad in tile view mode, that's why it's only available when the 2nd participant joins.

We may revisit / fine tune this in the future, but are not planning to do so at this time.

**Comment by ovari** [comment]
If we understanding correctly, `tile view` is now the default when there is 3 or more participants. If participants drop out so that there is only 2 participants, then the `tile view` will toggle off. Please comment if this understanding is incorrect. Thank you very much for making the adjustment to default to tile view when 3 participants join the room.

**Comment by whatwehaveunlearned** [comment]
> This change was intentional. We've made some adjustments and if the user doesn't change it, it will switch to tile-view mode when a 3rd participant joins.
> 
> The "alone" experience is bad in tile view mode, that's why it's only available when the 2nd participant joins.
> 
> We may revisit / fine tune this in the future, but are not planning to do so at this time.

So you say the user can change this? How can it be changed?
