### ISSUE TITLE
Background blur uses significant power

### ISSUE THREAD

**Issue by s4y** [jitsi/jitsi-meet#7647]
### Description:

(To be clear, I'm referring to the blur effect that appears when the aspect ratio of the browser doesn't match the aspect ratio of the video — not the option to blur your video's background. Please feel free to re-title the issue!)

The blur effect costs CPU and, on laptops, battery power. It _might_ be worth reconsidering whether the effect is worth it, or providing a way to disable it.

### Steps to reproduce:

1. Start a meeting. You can be the only participant.
2. Resize the browser window so that a blurred version of your camera is visible around the edges of the window.

### Expected behavior:

If measuring system power consumption with a tool like [syspower](https://github.com/s4y/syspower), it should be relatively similar regardless of the shape of the window.

### Actual behavior:

Power consumption goes up by several watts while the blur effect is visible. This graph shows me starting with the blur visible, then resizing the window slightly to hide the blur, then resizing the window again to show the blur:

<img width="529" alt="" src="https://user-images.githubusercontent.com/111870/92358494-8b00fa80-f0b7-11ea-8967-000c5c84d67e.png">

### Server information:

- Jitsi Meet version: 4370.1002 (is this the right version? I found it in the source of the page at meet.ji.si.)
- Operating System: Unknown.

### Client information:

- Browser / app version: Chrome 85.0.4183.83
- Operating System: macOS 10.15.6 (19G2021)

**Comment by jinixx** [comment]
@saghul background blur is not available on mobile atm, can we get some clarification is it because of performance or any reason behind it? Trying to get some clarification here, if it is not related to this issue, I can create a separate issue, and possibly we could help to implement it on mobile as well.

**Comment by saghul** [comment]
@jinixx Please open a new issue, that's not related with this issue at all.

**Comment by s4y** [comment]
@stale This is still an issue.

**Comment by s4y** [comment]
Stalebot, this is still an issue.

**Comment by tbttbtkregmas** [comment]
Whoever looking this issue, disable canvas called: "large-video-background". 


I'm not sure but _updateBackground() function might be related with this, however if you delete above canvas problem willbe fixed in your case.
