### ISSUE TITLE
ios pod failed 

### ISSUE THREAD

**Issue by lil-heart** [jitsi/jitsi-meet#7652]
when i make object and pod install then warning this :

[!] Invalid `Podfile` file: [!] /usr/local/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'react-native/cli'
Require stack:
- /Users/edz/Desktop/jitsi-meet-stable-jitsi-meet_4966/ios/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:87
    at Script.runInThisContext (vm.js:120:18)
    at Object.runInThisContext (vm.js:309:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/edz/Desktop/jitsi-meet-stable-jitsi-meet_4966/ios/[eval]' ]
}

**Comment by saghul** [comment]
What steps did you follow? Please be specific.

**Comment by lil-heart** [comment]
> What steps did you follow? Please be specific.

brew install node
brew install watchman
npm install -g yarn
install pod
npm install -g ios-deploy

npm install
cd ios
pod install

and failed

**Comment by saghul** [comment]
What cocoapods version did you install?

**Comment by lil-heart** [comment]
Its all work right now.
 Maybe I did an unexpected operation when installing the project.

I redownload this project ,do the same operation and its all right.

thx for yr help.

**Comment by Crabbit-F** [comment]
I got the same quesion and my cocoapods version is 1.11.3.

**Comment by Crabbit-F** [comment]
Thanks a lot. Which version should I use?

**Comment by saghul** [comment]
I am using 1.14.3

**Comment by saghul** [comment]
Please paste the full output you get.

**Comment by Crabbit-F** [comment]
[!] Invalid `Podfile` file: [!] /usr/local/bin/node -p require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  ) /Users/crabbit/Desktop/jitsi-meet/ios

node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'react-native/scripts/react_native_pods.rb'
Require stack:
- /Users/crabbit/Desktop/jitsi-meet/ios/[eval]
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at [eval]:1:9
    at runScriptInThisContext (node:internal/vm:209:10)
    at node:internal/process/execution:109:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:92:62)
    at evalScript (node:internal/process/execution:123:10)
    at node:internal/main/eval_string:51:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/crabbit/Desktop/jitsi-meet/ios/[eval]' ]
}

Node.js v20.12.2
.

 #  from /Users/crabbit/Desktop/jitsi-meet/ios/Podfile:2
 #  -------------------------------------------
 #  # Resolve react_native_pods.rb with node to allow for hoisting.
 >  require Pod::Executable.execute_command('node', ['-p',
 #    'require.resolve(
 #  -------------------------------------------

**Comment by saghul** [comment]
What exactly are you trying to do?

**Comment by Crabbit-F** [comment]
pod install

**Comment by saghul** [comment]
That is just one step. What are you trying to accomplish? Build the mobile app yourself, install the native SDK for a different project...

**Comment by Crabbit-F** [comment]
Thanks. I clone the  jitsi-meet  from https://github.com/jitsi/jitsi-meet.git and cd ios. Then 'pod install'.

**Comment by saghul** [comment]
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet
