### ISSUE TITLE
Unable to hide Splash Screen on app load

### ISSUE THREAD

**Issue by majayjayy** [jitsi/jitsi-meet#7656]
### Description:

I am attempting to replace the black loading screen (on app start) with a customized loading indicator, using the react-native-splash-screen package. I'm currently implementing it on Android, but will later do the same for iOS. I've tried following the instructions and am able to display the customized screen on starting the app, but I am unable to hide it (after the app has loaded) to resume functionality of the app.

### Steps to reproduce:

1. installed package 'npm install react-native-splash-screen'
2. included the project in android/settings.gradle
```
include ':react-native-splash-screen'
project(':react-native-splash-screen').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-splash-screen/android')
```
3. added the dependency in android/app/build.gradle
```
implementation project(':react-native-splash-screen')
```
4. created a layout file launch_screen.xml as required by the 'react-native-splash-screen' package
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background_splash"
    android:gravity="center">

    <ProgressBar
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginTop="200dp" />

</LinearLayout>
```
5. modified the MainActivity (in the overridden onCreate method) to show the customized screen before super.onCreate(savedInstance); **// this works fine as I am able to show the customized screen**
```
import org.devio.rn.splashscreen.SplashScreen;
```
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(savedInstanceState);
}
```
6. Attempting to hide the screen in React Native code in componentDidMount() - tried in many different places but without success i.e. BaseApp.js, AbstractApp.js, App.native.js, WelcomePage.native.js, etc. **// this does not work**

### Expected behavior:

The customized screen should hide once the app is loaded, redirecting to the WelcomePage.native.js

### Actual behavior:

The customized screen is shown while the app is loading, but I get a TypeError: Cannot read property 'hide' of null as shown in the image below once it has loaded. I've tried the same in a simple React Native app and it works flawlessly.
![Screenshot_2020-09-08-09-40-12-956](https://user-images.githubusercontent.com/20032274/92484560-d569a080-f1b7-11ea-958c-237a1284d9a7.jpeg)

### Server information:

- Jitsi Meet version: current
- Operating System: Ubuntu 20.04 LTS

**Comment by saghul** [comment]
What code did you add to Jitsi Meet?

**Comment by majayjayy** [comment]
Hi Saghul, thank you for your response. As per the instructions in `https://github.com/crazycodeboy/react-native-splash-screen`, the use of the code is as shown below:
```
import SplashScreen from 'react-native-splash-screen'

export default class WelcomePage extends Component {

    componentDidMount() {
    	// do stuff while splash screen is shown
        // After having done stuff (such as async tasks) hide the splash screen
        SplashScreen.hide();
    }
}
```
This is the only code that I have added on the React Native side of Jitsi Meet (as mentioned earlier, I have tried adding this code in the componentDidMount() of various different places i.e. BaseApp.js, AbstractApp.js, App.native.js, WelcomePage.native.js, etc.). But it throws the error **TypeError: Cannot read property 'hide' of null** each time.

If there is specific code from the Jitsi Meet project you would like me to share, please let me know and I will do the same.

**Comment by majayjayy** [comment]
@saghul I have edited my issue to include the code on the Android side of things as well. Hopefully that helps :)

Would appreciate it if you can provide any kind of guidance/suggestion.

**Comment by saghul** [comment]
Looks like you haven't linked the react-native-splash-screen library correctly. Our project has a bit of an unusual layout, so you need to do it manually. You need to add the package to this list: https://github.com/jitsi/jitsi-meet/blob/fc75d45c6cb16ac2e0917ba03da35342587c1d53/android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java#L186-L199

**Comment by majayjayy** [comment]
@saghul Thank you Saghul. I greatly appreciate the direction. This fixed the problem.

**Comment by saghul** [comment]
Glad you got it solved!
