### ISSUE TITLE
Jitsi stops sending video-

### ISSUE THREAD

**Issue by cjdg** [jitsi/jitsi-meet#7661]
### Description:
When you start jitsi, stops sending video, it happens on windows, linux, chrome and firefox, any combination.

### Steps to reproduce:

Start camera, share desktop or application
all participants stops getting video

windows, linux, chrome and firefox browsers.

### Expected behavior:

Jitsi shoul share video and/or screen sharing

**Comment by Echolon** [comment]
Can you please test this: https://test.webrtc.org/
