### ISSUE TITLE
Error generating IOS SDK by XCODE 

### ISSUE THREAD

**Issue by ips-illuminz** [jitsi/jitsi-meet#7663]
I have been trying to generate the IOS SDK after some modifications in it. I followed the following proceeder mentioned in url: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk.

`xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive`

When i'm trying with the following command, Xcode is giving error and build is getting failed. Can you please look into this and let me know the way to generate SDK, because we have to use in project.

**Comment by saghul** [comment]
We cannot know what fails unless you show us.

**Comment by ips-illuminz** [comment]
Thanks @saghul for your response, I have fixed the issue it was due to another patch applied into the build.
