### ISSUE TITLE
Unable to overwrite config.js file on ubuntu server.

### ISSUE THREAD

**Issue by Sandeep28633** [jitsi/jitsi-meet#7664]
Hi,

I have installed jitsi meet on my ubuntu server, and i am accessing the files using putty in my windows machine.
I want to change interface_config.js and config.js files.
Changes made to interface_config.js are reflecting simultaneously, but config.js changes are not reflecting, i tried many times.

Fyi, i changing files over remote only, and when i looks for the changes in winscp, file got changed, but not reflecting on web..
please help.

**Comment by saghul** [comment]
Might have to do with permissions. Can you check if your user has permissions to write to that file?

**Comment by Sandeep28633** [comment]
Hi sagul, 
thanks for the quick reply, i figured it out, i was editing wrong config.js file..now its working fine, so closing the issue.
