### ISSUE TITLE
maxFullResolutionParticipants: missing comma

### ISSUE THREAD

**Issue by Commifreak** [jitsi/jitsi-meet#7665]
Just a quick hint: You miss a comma in the default config: https://github.com/jitsi/jitsi-meet/blob/d169bd50079aa71e22917da954286d241be45022/config.js#L131

**Comment by saghul** [comment]
Good GH username :-)

**Comment by Commifreak** [comment]
Thanks for the fix! Another offtopic question: Where do you maintain Changelogs? I installed newest updates but dont know what changed.

**Comment by saghul** [comment]
I'm afraid I don't have a good answer for that. We started to keep at least the references here: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md but failed to keep up with the work :-/
