### ISSUE TITLE
Custom SDK not reflecting changes

### ISSUE THREAD

**Issue by deva-gopalani** [jitsi/jitsi-meet#7666]
i cloned official maven repo and copy the custom repo in com, org folders
```bash
cd jitsi-maven-repository

cp -r $home/jitsi-meet/tmp/repo/org $home/jitsi-maven-repository/releases
cp -r $home/jitsi-meet/tmp/repo/com $home/jitsi-maven-repository/releases
```
 and then

```bash
git add -A .
git commit -m "Jitsi Meet SDK + dependencies: <SDK_VERSION>"
git tag android-sdk-<SDK_VERSION>

// push
git push --tags
```

now you can use your custom sdk with your tag 

but i am not using this method anymore 

now, i am using like in [Rocket.chat/react-native-jitsi-meet](https://github.com/RocketChat/react-native-jitsi-meet)

_Originally posted by @batuhansahan in https://github.com/jitsi/jitsi-meet/issues/5213#issuecomment-627945508_

The link I am using is - https://github.com/deva-gopalani/jitsi-maven-repository/raw/master/releases

I have added a few functions in the JitsiMeetActivity.java file but for some reason they are not reflecting. All the steps which have been mentioned above by @batuhansahan have been done. Is there something I am missing on?

**Comment by saghul** [comment]
You can just reference your own folder instead of copying it, not sure why you'd want to do that. At any rate, we are not the maintainers of Rocket.chat/react-native-jitsi-meet so there is not much we can do to help.

**Comment by deva-gopalani** [comment]
thank you! @saghul it worked out! :D
