### ISSUE TITLE
iOS - No video and audio in conference 

### ISSUE THREAD

**Issue by mocmoc05** [jitsi/jitsi-meet#7668]
Step:
- I download the Jitsi Meet app from AppStore

- I make a video call from our site

- I copy URL of conference and join it in app

- Audio and Video worked

But please help to resolve the below issue:

- I clone the jitsi-meet source from github and run app

- Make call like above

- Audio and Video not working

Anyone faces the issue? Please help me, thanks!

**Comment by saghul** [comment]
How does the URL you are using look like? Does it use a valid TLS certificate?

**Comment by mocmoc05** [comment]
> How does the URL you are using look like? Does it use a valid TLS certificate?

it looks like "https://testcall-enkomm.nislab.vn/EnkommaQYZhgtATF8Z4v3x2dH2CvoG9Yxw57ASr7", I tested with Chrome and it worked, but when I use Chrome and iOS app(built from the jitsi-meet github) I get the issue

**Comment by saghul** [comment]
Can you show the logs? Maybe try to run it in the simulator, it's the easiest.

**Comment by mocmoc05** [comment]
[log.txt](https://github.com/jitsi/jitsi-meet/files/5194741/log.txt)
this is log file when I join call from iOS app

**Comment by kida7** [comment]
This is the screen recording I took from the clone step on Git to the emulator step: https://www.youtube.com/watch?v=7DxbQPt8pdA

**Comment by kida7** [comment]
> Can you show the logs? Maybe try to run it in the simulator, it's the easiest.
This is the screen recording I took from the clone step on Git to the emulator step: https://www.youtube.com/watch?v=7DxbQPt8pdA

**Comment by kida7** [comment]
> Can you show the logs? Maybe try to run it in the simulator, it's the easiest.

This is the screen recording I took from the clone step on Git to the emulator step: https://www.youtube.com/watch?v=7DxbQPt8pdA

**Comment by mocmoc05** [comment]
> > Can you show the logs? Maybe try to run it in the simulator, it's the easiest.
> 
> This is the screen recording I took from the clone step on Git to the emulator step: https://www.youtube.com/watch?v=7DxbQPt8pdA

Yes. I got the same issue

**Comment by psdevss** [comment]
Any update about this issue?

**Comment by WirecardArdy** [comment]
Did you manage to solve this issue?

**Comment by ThanhTrung90** [comment]
@mocmoc05 , @kida7 Have you fixed this issue?

**Comment by mohajerimasoud** [comment]
I have the same issue 
in our company we implemented jitsi call in a web, ios and android app
we can make video call success fully between ios & android and android & web but when we make a call between ios and web we recive voice successfully in both sides and we recive video in ios but in web application we dont recive video from ios client in our web application .
