### ISSUE TITLE
Video-image flipped (mirrored) horizontally on Firefox

### ISSUE THREAD

**Issue by neufeind** [jitsi/jitsi-meet#767]
Using Firefox 48 and Chrome 54.0.x I streamed video using both meet.jitsi.org as well as the beta-version. The video was flipped horizontally, so that in the one browser you shake your hand to the right and it appears to be shaking to the left in the other browser.

I've seen there was a commit in fall 2015 regarding a "flipX"-javascript in jitsi-meet. Could that be related? Was flipping maybe needed in the past for Firefox but not for a current version or so?

**Comment by bgrozev** [comment]
The local video is flipped, this is by design. Is this what you are seeing, or do you see a remote video flipped?

**Comment by neufeind** [comment]
Oh okay. I just had source (local) and remote side-by-side and didn't expect it to be "by design". Thanks for the quick response.

**Comment by porkandbeansboy** [comment]
I am having the same problem with my Webcam having a mirrored image and I need to photograph my I.D. Photo Card and I don't know how to make it so the image is not mirrored and flipping the words on my I.D. card can you please help me neufiend? I am new here and I got no idea how to navigate this place it is confusing beyond all belief.

**Comment by porkandbeansboy** [comment]
Woops I just realized this post was from 2016 I just googled this problem then found this post and didn't realize that part until now my bad.
