### ISSUE TITLE
Iframe integration : The menu button (more actions) is not visible any more and the icons are smaller

### ISSUE THREAD

**Issue by ramrami** [jitsi/jitsi-meet#7670]
### Description:

I was using the iframe integration to load **meet.jit.si** in my app in a **480px** container. Everything was working fine,  but recently the "menu" button (more actions) is not visible any more and the icons are smaller.

<img width="538" alt="Capture d’écran 2020-09-09 à 10 32 40" src="https://user-images.githubusercontent.com/9569590/92581953-41b3d500-f288-11ea-8179-a7070f5566a9.png">

**Comment by saghul** [comment]
Our small screen limit is 500px: https://github.com/jitsi/jitsi-meet/blob/8fa41bebb7bc5d2df7a4a95f0d677dc4b4a2cd38/css/_variables.scss#L284

**Comment by ramrami** [comment]
Thank you
