### ISSUE TITLE
not working. 

### ISSUE THREAD

**Issue by Emilien10** [jitsi/jitsi-meet#7672]
Hello I am due to have a meeting with my physio now and for some reason I am not being allowed in for the conference call. I have no idea what is going on. Please can you sort this out quickly in order to resolve this.

**Comment by damencho** [comment]
Please if you have questions and problems use the community forum before opening new issues.

In order for someone to help you, you need to provide more details. What deployment you were using, is it meet.jit.si? What is the OS and its version and what is the browser and its version?
