### ISSUE TITLE
Unable to hide invite button from JitsiMeetView

### ISSUE THREAD

**Issue by Arohi-Magotra** [jitsi/jitsi-meet#7673]
![621346766 563807](https://user-images.githubusercontent.com/64579245/92597376-ef44d980-f2c4-11ea-89d6-15ef71bc5641.jpg)

Please check the attached screenshot. I m trying to hide the button using config "setFeatureFlag("invite.enabled", withBoolean: false)", but this is still not working. Please check

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by Arohi-Magotra** [comment]
version 2.5.0

**Comment by Arohi-Sharma** [comment]
Can someone plz help me with this?

**Comment by saghul** [comment]
You need to update. I forget on what version we added the flag, but it's on the latest version for sure. That's be 2.10.0.

**Comment by Arohi-Sharma** [comment]
ok thanks

**Comment by Arohi-Sharma** [comment]
@saghul Thanks i have updated the code and its working for me.
