### ISSUE TITLE
Screen Sharing does not work, when I click button

### ISSUE THREAD

**Issue by comerc** [jitsi/jitsi-meet#7675]
![Снимок экрана от 2020-09-09 20-20-14](https://user-images.githubusercontent.com/1025241/92631394-f7f3da80-f2d9-11ea-893f-b4613e4a8692.png)

Ubuntu 18.04.2 LTS
Chrome 73.0.3683.103

with multi monitors

**Comment by damencho** [comment]
Please when you have questions or problems, use the community forum before opening new issues.
I think this is the chrome version, it is too old it relays on extension to share the screen, but those are no longer available in the chrome store.
