### ISSUE TITLE
Firefox: Not possible to open "share screen"-dialog a second time

### ISSUE THREAD

**Issue by neufeind** [jitsi/jitsi-meet#768]
When you opened the "share screen"-dialog once but close it (without sharing something) you can't open it again. Maybe jitsi-meet or the browser-plugin thinks you are already sharing something? Or that the dialog is still open?

**Comment by damencho** [comment]
I can confirm this is an issue. 
Could you please discuss problems and features on the mailinglist before opening an issue.

**Comment by MarcelWaldvogel** [comment]
A similar problem also applies when unsharing the screen: If the user clicks the close button when chosing the camera device to return to, screen sharing cannot be changed or deactivated.

Environment: Firefox 50.0 on Ubuntu 16.04

How to repeat:
1. Click on screen sharing to enable
2. Select a window in the browser pop-up
3. Click on screen sharing to disable
4. Cancel the camera selection dialog
5. Further clicks on the screen sharing button have no effect
