### ISSUE TITLE
iOS Safari screen video freezes (mobile and desktop) when second participant stops sharing screen

### ISSUE THREAD

**Issue by HubertFranz** [jitsi/jitsi-meet#7686]
### Description:

With two or more particpants in the room, one sharing the desktop, other uses Safari. When Chrome stops screensharing and has no video activated before, Screen does not go away on Safari. Issue is evertime reproducable.

### Steps to reproduce:

1. Start a meeting (meet.ji.si) with two or more participants, one Chrome one Safari (iOS or Desktop)
2. Share screen on Chrome (without activating camera before)
3. Stop screensharing
4. Screen freezes/does not go away

### Expected behavior:

Shared screen should go away after stopping sharing screen.

### Server information:

- Jitsi Meet version: Latest Stable (same of meet.jit.si)
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: Safari / Chrome
- Operating System: iOS / Windows

**Comment by pgenderson** [comment]
I've been having this screenshare freezing issue since the start and am currently giving BigBlueButton a try but it's bit harder to install and I'm still not done.

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jakobwoegerbauer** [comment]
I have the same problem. 
For me it looks like in TraceabelPeerConnection.js and JitsiRemoteTrack.js neither of these events fire in Safari?
RTCPeerConnection.ontrack (and therefore MediaStream.onremovetrack), MediaStreamTrack.onmute, RTCPeerConnection.onremovestream (not supported in Safari)

I tried it in Safari 13.1.2 and Safari 14.0 (Technology Preview)

**Comment by jallamsetty1** [comment]
> I have the same problem.
> For me it looks like in TraceabelPeerConnection.js and JitsiRemoteTrack.js neither of these events fire in Safari?
> RTCPeerConnection.ontrack (and therefore MediaStream.onremovetrack), MediaStreamTrack.onmute, RTCPeerConnection.onremovestream (not supported in Safari)
> 
> I tried it in Safari 13.1.2 and Safari 14.0 (Technology Preview)
> 
> Edit: RTCPeerConnection.ontrack does fire, but MediaStream.onremovetrack does not. This is a Safari bug which can also be seen on http://w3c-test.org/webrtc/RTCTrackEvent-fire.html, where the test "Applying a remote description with removed msid should trigger firing a removetrack event on the corresponding stream" fails.

Yes, this is what I am seeing as well, when the remote track is removed, MediaStream.onremovetrack isn't getting fired on Safari which messes up our track removal logic.

**Comment by jallamsetty1** [comment]
Safari bug still persists. However, a workaround has been added in the client that whenever a new remote track is received, the client removes the old track and then creates a new remote track. - https://github.com/jitsi/lib-jitsi-meet/commit/ea33a70f9ccab83496f40c334d0e7d1e9babf290#diff-20e543a222fca71d2e2b99c286bbc60db44e228bb3cfc9d8a083d835140abdb0.
