### ISSUE TITLE
when the app is kill，the other one do not know the other is not online

### ISSUE THREAD

**Issue by HuskarHuang** [jitsi/jitsi-meet#7688]
### Steps to reproduce:

1.Three android phone join in the same room
2. Kill one app in one phone or one app crash
3. The other two do not know the one is kill

### Expected behavior:

The other two should know the one was killed and had left,but they do not know. It seem it need about one minus to to refresh and the one was killed remove from the filmstrip

### Client information:

- mobile-20.3 branch
- android phone:

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening new issues.
It will take up to 1 minute and the "ghost" participant will disappear.

**Comment by HuskarHuang** [comment]
@damencho  It needs about 60 seconds，can we shorter the time to about 10 to 20 seconds，how can i do for this

**Comment by damencho** [comment]
60 secs timeout comes from bosh, this is the default in the protocol and it is hardcoded in few places.

**Comment by HuskarHuang** [comment]
@damencho where is it，it is server code or client code，can you tell me ,thank you very much!

**Comment by damencho** [comment]
There is a property in prosody to control that, you can change it by config. But in the client code it is in the strophe library, you need to rebuild that and then rebuild and lib-jitsi-meet, probably it is this: https://github.com/strophe/strophejs/blob/master/src/bosh.js#L160

**Comment by HuskarHuang** [comment]
Hello @damencho i try this,but it has not take effect
Here is my index.android.bundle code:
`ActiveXObject("Microsoft.XMLHTTP")),e.onreadystatechange=this.func.bind(null,this),e}},P.Bosh=function(e){this._conn=e,this.rid=Math.floor(4294967295*Math.random()),this.sid=null,this.hold=1,this.wait=5,this.window=5,this.errors=0,this.inactivity=null,this.lastResponseHeaders=null,this._requests=[]},P.Bosh.prototype={strip:null,_buildBody:function(){var e=D("body",{rid:this.rid++,xmlns:P.NS.HTTPBIND});return `
Whether i modify the right place
