### ISSUE TITLE
cloud not install the olm commponent from https://packages.matrix.org/npm/olm/olm-3.1.4.tgz

### ISSUE THREAD

**Issue by zhiyu5352** [jitsi/jitsi-meet#7689]
When I init the project, npm install, got this output: 
ResponseError: socket hang up, GET https://packages.matrix.org/npm/olm/olm-3.1.4.tgz.
I browsed this url by chrome, got the response: "Sorry, something went wrong."

What should I do?

**Comment by damencho** [comment]
Please use the community forum before opening new issues. 

Maybe it was a temporary issue? Works here at the moment.
