### ISSUE TITLE
How to remove shadow from Camera overlay in android

### ISSUE THREAD

**Issue by w3technosoft** [jitsi/jitsi-meet#7692]
we getting shadow on Camera. That's overlap camera screen. Can anybody help me how to remove top and bottom shadow.

**Comment by saghul** [comment]
The shadows are only shown when the buttons are displayed. Look for the use of `LinearGradient` here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/conference/components/native/Conference.js Then you'll need to rebuild the app.
