### ISSUE TITLE
Korean translation issue.

### ISSUE THREAD

**Issue by yjhgull** [jitsi/jitsi-meet#7693]
### Description: #7681 

Korean translation issue.

### Steps to reproduce:

1. Enter meeting room.
2. Click on more options.
3. Look at the camera toggle menu.

### Expected behavior:

1. 토그 == Togg : This is an invalid character.
2. Toggle == 토글 : This is right. but, "Toggle" is usually used as "전환" in Korean.

You should be able to see "카메라 전환"

### Actual behavior:

You can see "카메라 토ㄱ"

![스크린샷 2020-09-14 오후 6 51 01](https://user-images.githubusercontent.com/28862513/93073137-6b706000-f6bd-11ea-8b11-1352ec9950dc.png)

### Server information:

- Jitsi Meet version: Latest Stable
- Operating System: Ubuntu 20.04 LTS

### Client information:

- Browser / app version: Android App 20.3.2 build 4911829
- Operating System: Android 9

### Additional information:

I have posted pull requests(#7681 ) for Korean translation, including content related to this issue.
Thank you.

**Comment by saghul** [comment]
PR landed, thanks for the reminder! It should be part of the next-next update (we already have a build on beta).
