### ISSUE TITLE
Notifications overlapping with chat window

### ISSUE THREAD

**Issue by franken300** [jitsi/jitsi-meet#7695]
### Description:
As a user I want to read the chat during a video call without being interrupted by notification pop-ups. 

When you are in a video call and participants are using the chat frequently notifications such as mute, joining/leaving are overlapping with the text in the chat. 

In means that participants are not able to read the messages and need to dismiss (sometimes multiple) notifications.

### Actual behavior & steps to reproduce :
1. open a meeting on meet.jit.si
2. type in a lot of text in the chat 
3. trigger notification by trying to speak while muted or another event that triggers a notification
![image](https://user-images.githubusercontent.com/69365535/93140317-843f3c80-f6e2-11ea-94b7-8fd0aaa728ad.png)

### Expected behavior:
I would expect that the notification are not overlapping with other UI components. Possible fixes would be:
1. Smaller notification boxes when notification text is small
2. change position of notification to left side in video stream when chat is opened 

### Server information:
- meet.jit.si 
- beta.meet.jit.si
- alpha.jitsi.net

### Client information:
Not relevant as this issue is in every browser

**Comment by saghul** [comment]
This is a known issue.
