### ISSUE TITLE
The same meeting URL puts me in two separate meetings when on Mac's Safari and Ubuntu's Firefox

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#7696]
The URL is meet.jit.si/testing. I started it on Ubuntu Desktop 20.04.1's regular latest Firefox version and then opened the same link on a Macbook running High Sierra (10.13) with the latest Safari version. When I opened it on the Mac, it said I was the only one in the meeting even though I have the exact same link open on my desktop.

**Comment by saghul** [comment]
Can you reproduce this consistently? What was the URL?

**Comment by jakobwoegerbauer** [comment]
I have a similar (probably the same) problem. It does look like they are in different meetings, but based on the log output I would say it doesn't even try to connect (from Safari). This happens like 9 out of 10 times with Safari 12.1.1 so it does work sometimes, when I close and reopen the page a few times.
When I try the same URL on the same Macbook with a different browser it does work perfectly fine.

console log output when it does not work:
[log.txt](https://github.com/jitsi/jitsi-meet/files/5223984/log.txt)
console log output when it does work:
[log_working.txt](https://github.com/jitsi/jitsi-meet/files/5224013/log_working.txt)

**Comment by saghul** [comment]
@jakobwoegerbauer That doesn't really mean there are 2 different meetings with the same name, but that you didn't actually join the meeting. The UI is a but confusing in this regard, since it looks like you are alone in a meeting.

**Comment by pgenderson** [comment]
Didn't happen this time, but I also saw that screenshare doesn't even work at all when viewing someone's share on a Mac with Safari 13.1.2.
