### ISSUE TITLE
jitsi 's embed button produces slightly incorrect iframe syntax which makes it unusable

### ISSUE THREAD

**Issue by brunov25** [jitsi/jitsi-meet#7702]
### Steps to reproduce:

1.  meet.jit.si/RandomRoomName
2.  EMBED MEETING
3.  notice the HTML is: 
 `` <iframe allow="camera; microphone; display-capture" src="https://meet.jit.si/RandomRoomNameallowfullscreen="true" style="height: 100%; width: 100%; border: 0px;"></iframe>``

### Expected behavior:

it should be:

 `<iframe allow="camera; microphone; display-capture" src="https://meet.jit.si/RandomRoomName" allowfullscreen="true" style="height: 100%; width: 100%; border: 0px;"></iframe>`

just an extra quote and space between the room name and the allowfullscreen parameter

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Thanks for the report.

**Comment by quitrk** [comment]
Submitted fix here https://github.com/jitsi/jitsi-meet/pull/7704

**Comment by damencho** [comment]
Fixed with 7f67f78db68d808d51603b62ca2ada591b8dd674
