### ISSUE TITLE
Unable to mute the audio through the callkit UI

### ISSUE THREAD

**Issue by Arohi-Sharma** [jitsi/jitsi-meet#7706]
I have implemented Callkit with JitsiMeet, I m unable to mute the audio through the callkit UI.
SDK version used : 2.5.0

Method Used: 

 func performSetMutedCall(UUID: UUID, isMuted: Bool){
        let callMutedAction = CXSetMutedCallAction(call: UUID, muted: isMuted)
        let transaction = CXTransaction(action: callMutedAction)
        
        JMCallKitProxy.request(transaction) { (error) in
            print(error?.localizedDescription)
        }
    }

Please suggest something for implementing this, i want to mute the jitsi call using callkit UI button

**Comment by saghul** [comment]
That works out of the box, you don't need to implement anything.

**Comment by Arohi-Sharma** [comment]
@saghul But the call is not getting mute on callkit ui button click

**Comment by saghul** [comment]
No, that should just work. Are you seeing this in Jitsi Meet or your custom app?

**Comment by Arohi-Sharma** [comment]
In my custom app

**Comment by Arohi-Sharma** [comment]
@saghul I have seen the logs when i click on mute button from callkit ui , only this method is getting called

-->>> [JitsiMeetSDK] [RNCallKit][CXProviderDelegate][provider:performSetMutedCallAction:]

also i m getting this error

-->>> [JitsiMeetSDK] [modules/statistics/AudioOutputProblemDetector.js] A potential problem is detected with the audio output for participant 4c01c0a3, local audio levels: [null,null], remote audio levels: undefined

on clicking mute button from jitsi view, it successfully mute the audio

-->> [JitsiMeetSDK] [modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[2,audio]: true

**Comment by saghul** [comment]
> -->>> [JitsiMeetSDK] [modules/statistics/AudioOutputProblemDetector.js] A potential problem is detected with the audio output for participant 4c01c0a3, local audio levels: [null,null], remote audio levels: undefined

This is unrelated.

> -->>> [JitsiMeetSDK] [RNCallKit][CXProviderDelegate][provider:performSetMutedCallAction:]

I cannot reproduce your problem with the Jitsi Meet app. Did you enable the audio and voip background modes?

**Comment by Arohi-Sharma** [comment]
yes i have enabled that
<img width="378" alt="Screenshot 2020-09-17 at 9 15 04 PM" src="https://user-images.githubusercontent.com/71379048/93494635-de324300-f92a-11ea-8928-b969fa223f35.png">

**Comment by Arohi-Sharma** [comment]
Is there any working example for jitsimeet with callkit which i can see for reference?

**Comment by saghul** [comment]
This very app.

**Comment by saghul** [comment]
I'd suggest you update your SDK to 2.10 first though.

**Comment by Arohi-Sharma** [comment]
ok will try by cloning it again and let you know

**Comment by nsmith1024** [comment]
Can someone please help me with my issue. I built jiti meet from the repository, the IOS version using xcode. It builds successfully, but when xcode tries to install it on the  phone after the build it gives an error, can you help please here it is...

https://github.com/jitsi/jitsi-meet/issues/7734

**Comment by Arohi-Sharma** [comment]
Hi @saghul i have updated the code and its still not working for me.

**Comment by Arohi-Sharma** [comment]
Aldo there is some issue with the audio session, on first call there is no audio when accepted from callkit. it works fine after first time

**Comment by Arohi-Magotra** [comment]
Hi, we have checked the logs and found that an outgoing call has been reported when we answer from callkit UI. The UDID created for start call is different from answer call , hence we are unable to mute that function. Please check the logs given below:

2020-09-29 11:46:15.799590+0530 Demo-3002[10144:1753641] [JitsiMeetSDK] [RNCallKit][startCall] callUUID = BB884266-17D0-4B35-868B-31F08BDE9EAF
2020-09-29 11:46:15.802651+0530 Demo-3002[10144:1753641] [JitsiMeetSDK] [RNCallKit][requestTransaction] transaction = <CXTransaction 0x283c11ec0 UUID=C9181D0A-82C1-46E3-AE60-48B8EB1813C9 isComplete=0 actions=(
    "<CXStartCallAction 0x280e81830 UUID=6DB20FC7-1113-49C6-A187-DDE265C681F4 state=0 commitDate=(null) callUUID=BB884266-17D0-4B35-868B-31F08BDE9EAF handle=<CXHandle 0x283c2e460 type=Generic value=https://meet.hippochat.io/sEDbtExalx> contactIdentifier=(null) video=0 relay=0 upgrade=0 retry=0 emergency=0 isVoicemail=0 ttyType=0 localLandscapeAspectRatio={0, 0} localPortraitAspectRatio={0, 0} dateStarted=(null) localSenderIdentityUUID=(null) shouldSuppressInCallUI=0>"
)>
2020-09-29 11:46:15.810258+0530 Demo-3002[10144:1753641] [JitsiMeetSDK] [modules/xmpp/moderator.js] Focus jid set to:  undefined
2020-09-29 11:46:15.811894+0530 Demo-3002[10144:1752630] [JitsiMeetSDK] [RNCallKit][requestTransaction] Error requesting transaction ((
    "<CXStartCallAction 0x280e81830 UUID=6DB20FC7-1113-49C6-A187-DDE265C681F4 state=0 commitDate=(null) callUUID=BB884266-17D0-4B35-868B-31F08BDE9EAF handle=<CXHandle 0x283c2e460 type=Generic value=https://meet.hippochat.io/sEDbtExalx> contactIdentifier=(null) video=0 relay=0 upgrade=0 retry=0 emergency=0 isVoicemail=0 ttyType=0 localLandscapeAspectRatio={0, 0} localPortraitAspectRatio={0, 0} dateStarted=(null) localSenderIdentityUUID=(null) shouldSuppressInCallUI=0>"


This happens when i answer the call from call kit UI. Please help me with this fix. I m also sharing a video for your reference

**Comment by saghul** [comment]
Ah, so you are handling an incoming call? You should have mentioned that :-) How are you currently handling incoming calls?

**Comment by Arohi-Magotra** [comment]
@saghul Yes, I am answering the incoming call from callkitui and on performAnswerCall delegate method i m calling my methods to join jitsi conference call. I have checked by commenting the calluuid condition in 
[https://github.com/jitsi/jitsi-meet/blob/e8e2b3c34112c7f22e5a3d9e5d835c1d442e59c7/react/features/mobile/call-integration/middleware.js#L372](url) line number 376, its working den. Can u please tell me if there is any way i can pass the calluuid, so that this condition matches

**Comment by Arohi-Magotra** [comment]
@saghul Also i have tried overrideing the calluuid by passing "#config.callUUID=\(uuid)" config with server url. Please let me know what exactly we can do to solve it.

**Comment by saghul** [comment]
> Also i have tried overrideing the calluuid by passing "#config.callUUID=(uuid)" config with server url.

Didn't that work? It should have.

Note that we don't implement the incoming call case so it may have been inadvertently broken.

**Comment by Arohi-Magotra** [comment]
No this doesnot work, its still created another UDID for start call

**Comment by saghul** [comment]
Are you using the CallKit API directly or via our JMCallKitProxy ?

**Comment by Arohi-Magotra** [comment]
via JMCallKitProxy

**Comment by saghul** [comment]
I'm afraid I have no good explanation then. If you have a simple test app which I can use to debug this, it would really help.

**Comment by phaninderkumar** [comment]
Hi @saghul ,

https://github.com/phaninderkumar/JitsiSample

Here is a sample project where you can debug this behaviour. You can initiate an outgoing call or report an incoming call.
When we initiate a outgoing call, the mute actions from call kit screen work fine. But for an incoming call it doesn't.
Let me know if you need anything else or if the sample is not clear enough.
IMO, this issue can be fixed if you can give a provision to supply the CallUUID when initiating a Jitsi call(which will be used for incoming calls).

**Comment by PauMateu** [comment]
@phaninderkumar have you been able to find a solution for this issue? We are currently facing the same problem

**Comment by atereshkov** [comment]
Same issue here
@PauMateu have you found anything?

**Comment by iim-norse** [comment]
Same issue here

**Comment by Aydogdyshka** [comment]
same issue here
