### ISSUE TITLE
Ios JitsiMeet.framework not support armv7,armv7s，how to deal with this

### ISSUE THREAD

**Issue by HuskarHuang** [jitsi/jitsi-meet#7719]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
We dropped support for iOS 10, the last version to support those architectures. You can keep using an old SDK version (2.8 should do I believe).

**Comment by HuskarHuang** [comment]
what the pronlem is , our application with jitsi module could not pass app-store's verification, (which say our app could not be installed successful in armv7 device, like iphone 5s, ipad etc...), any suggestion for it?

**Comment by saghul** [comment]
As I said, use an older version of the Jitsi Meet SDK. We dropped support for iOS 10 on SDK 2.5.0, you'll need to use some older version. See https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#250-2019-12-13
