### ISSUE TITLE
npx pod-install not working for XCode 12

### ISSUE THREAD

**Issue by techiesanjaypathak** [jitsi/jitsi-meet#7722]
<img width="1440" alt="Screenshot 2020-09-18 at 5 19 09 PM" src="https://user-images.githubusercontent.com/7879697/93594618-d5497c00-f9d3-11ea-8195-aa1da8877669.png">
<img width="1440" alt="Screenshot 2020-09-18 at 5 18 53 PM" src="https://user-images.githubusercontent.com/7879697/93594630-daa6c680-f9d3-11ea-9c4a-d5bd0a571239.png">

**Comment by saghul** [comment]
What SDK version are you trying to install?

**Comment by ithaqua** [comment]
same issue with react-native run-ios

**Comment by nsmith1024** [comment]
Here is my issue can you help?

https://github.com/jitsi/jitsi-meet/issues/7734

**Comment by saghul** [comment]
> same issue with react-native run-ios

Does running from Xcode itself work for you?
