### ISSUE TITLE
Use Snap to install Certbot

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#7733]
**Is your feature request related to a problem you are facing?**
I tried using the Let's Encrypt script that comes with jitsi-meet on Ubuntu Desktop 20.04, and it installs a seemingly very old version of Certbot which didn't work (some CAA error) although my new Snap version also failed (nginx restart failed, b'' b'').

**Describe the solution you'd like**
Install the latest stable Certbot (I don't think 0.X is the latest stable).

**Comment by pgenderson** [comment]
@Echolon, I don't know if it's just me but it's weird that no one else seems to be having an issue with the Ubuntu regular Certbot. Anyways, I can create a pull request for the relevant section on the docs if you deem it worthwhile.

**Comment by saghul** [comment]
@pgenderson Looks like https://github.com/jitsi/jitsi-meet/blob/master/resources/install-letsencrypt-cert.sh#L33 needs an update for 20.04 to install it using snap indeed: `sudo snap install --classic certbot` https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx
