### ISSUE TITLE
Cant install jitsi-meet after successful Xcode build

### ISSUE THREAD

**Issue by nsmith1024** [jitsi/jitsi-meet#7734]
### Description:
 
After building jitsi-meet using Xcode from jetsi-meet-master is completed, Xcode tries to install app on iPhone. Then I get this error

Unable to install "jitsi-meet"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652967
--
This app contains a WatchKit app with an invalid bundle identifier. The bundle identifier of a WatchKit app must have a prefix consisting of the companion app's bundle identifier, followed by a '.'.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652967
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE80000D9)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012040093f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000012043f124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000104c67b53 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000012043ee65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x00000001202afd28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000104d962ba __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000104d97edc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff6b6ad6c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff6b6ae658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff6b6b3c44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff6b6b45d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff6b6bdc09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff6b908a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff6b907b77 start_wqthread + 15
);
}

System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 12.0 (17219)
-------------------------------------------------------------------

I followed the instructions, changed the bundle identifier in the watch app to the same a the apps plus the dot. when I do that and try to build again it doesn't build, it complains that WatchKit has no matching bundle identifier matching the one I specified. I tried multiple variations of bundle identifiers, all give same error.

Is there a way to remove the watch app from the build? why is there a watch app in there anyway? i only want the jitsi-meet app but there is a Watch App in the project also. Is it needed? can i remote it because its causing problems with the installation. 

### Steps to reproduce:

1.  build jets meet using Xcode
2. 
3. 

### Actual behavior:

app should build and install

### Server information:

- Jitsi Meet version:
- Operating System: Mac/Xcode/iPhone

**Comment by Echolon** [comment]
Can you please improve the font for reading purposes?

**Comment by nsmith1024** [comment]
> 
> 
> Can you please improve the font for reading purposes?

Can you please tell me how to fix, it compiles but xcode wont install it/

**Comment by nsmith1024** [comment]
Anybody here can help?

**Comment by saghul** [comment]
The error itself explains how to correct the problem: 

> This app contains a WatchKit app with an invalid bundle identifier. The bundle identifier of a WatchKit app must have a prefix consisting of the companion app's bundle identifier, followed by a '.'.

You changed the app bundle ID but you didn't change the Apple Watch and companion extension app IDs.

**Comment by nsmith1024** [comment]
I did, i changed it and tried multiple variations, nothing worked!

**Comment by saghul** [comment]
Grep for org.jitsi.meet in the ios folder, do you see anything?

**Comment by nsmith1024** [comment]
I did a grep here is the result:

Ns-Mac-mini ~ % cd Documents 
Ns-Mac-mini Documents % cd dev
Ns-Mac-mini dev % cd jitsi-meet-master
Ns-Mac-mini jitsi-meet-master % cd ios
Ns-Mac-mini ios % grep -inr org.jitsi.meet *
app/src/AppDelegate.m:33:    jitsiMeet.customUrlScheme = @"org.jitsi.meet";
app/src/Info.plist:29:			<string>org.jitsi.meet</string>
app/src/Info.plist:32:				<string>org.jitsi.meet</string>
grep: sdk/JitsiMeet.framework: No such file or directory
sdk/src/AudioMode.m:34:static NSString * const kDevicesChanged = @"org.jitsi.meet:features/audio-mode#devices-update";
Ns-Mac-mini ios %

**Comment by saghul** [comment]
> app/src/Info.plist:29: org.jitsi.meet
> app/src/Info.plist:32: org.jitsi.meet

These 2 need updating I think.

**Comment by nsmith1024** [comment]
Update it to what?

**Comment by saghul** [comment]
Change to match your bundle ID. They must start the same way, as the error points out. You can of course remove the watch companion app if you want.
