### ISSUE TITLE
sudo dpkg-reconfigure jitsi-videobridge2 doesn't reconfigure Nginx configuration

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#7735]
I had an Nginx configuration issue where I ended up purging and then reinstalling it, but after running the above command (which I'd think would be the right one), e.g. /etc/nginx.conf was still empty, which it wasn't after installing Nginx and then jitsi-meet. I don't want to have to autoremove --purge jitsi-meet every time I have to change an Nginx config. `$ sudo systemctl reload nginx' doesn't do it either (Ubuntu Desktop 20.04).

**Comment by manang** [comment]
Hi, did you solve the issue?

**Comment by damencho** [comment]
Nginx is configured from jitsi-meet-web-config package, which is the one you need to reconfigure.
And in general, the reconfigure procedure is not well tested and may have bugs.
