### ISSUE TITLE
crash when clicking on "More actions"

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#7738]
Hi all,

Just did a fresh git clone and compiled jitsi web.
All works as expected but when I click on the "More actions" button the meeting drops and goes back to the home screen.

This is what shows up in chrome console:

VM170 app.bundle.min.js:92 2020-09-20T20:19:45.328Z [features/base/redux] <Object._listener>:  TypeError: Cannot read property 'id' of undefined
    at Object.listener (VM170 app.bundle.min.js:206)
    at Object._listener (VM170 app.bundle.min.js:1)
    at g (VM170 app.bundle.min.js:36)
    at VM170 app.bundle.min.js:130
    at VM170 app.bundle.min.js:206
    at VM170 app.bundle.min.js:206

I also see some other errors before clicking on "More actions" but I don't believe they're related to this bug but I will post them here anyway:

VM170 app.bundle.min.js:130 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ VM170 app.bundle.min.js:130
Promise.catch (async)
n @ VM170 app.bundle.min.js:130
u.asm @ VM170 app.bundle.min.js:130
u @ VM170 app.bundle.min.js:130
(anonymous) @ VM170 app.bundle.min.js:130
c.init @ VM170 app.bundle.min.js:130
(anonymous) @ VM170 app.bundle.min.js:206
n @ VM170 app.bundle.min.js:1
(anonymous) @ VM170 app.bundle.min.js:1
(anonymous) @ VM170 app.bundle.min.js:1

**Comment by nsmith1024** [comment]
Hello, Is this on IOS? Did you build it with xcode? which language is it? react? objective-c? swift?

Im having problems installing it after building the ios version.

Is there a WatchApp in your xcode project as well?

Did you get the code from this git repository? When i build i get an error when xcode tries to install it on the iPhone see my issue here 

https://github.com/jitsi/jitsi-meet/issues/7734

**Comment by pdarcos** [comment]
Hi,

No this isn't on iOS. It's the web component.
Some code must have been changed recently in jitsi-meet since I've compiled this project numerous times over the years and never ran into this "TypeError: Cannot read property 'id' of undefined" It seems some bug was introduced in recent commits where id is now undefined.

**Comment by nsmith1024** [comment]
Ok, thanks, but the developers are not answering any questions or helping anymore on here it seems. 

I got jitimeet to work before by compiling one of the test projects, and it installed and everything and works on ios on the phone itself. But that version uses nested frameworks and apple refuses to allow nested frameworks on their apple store. I dont know what the big deal with that, but apple complains about everything it seems.

**Comment by nsmith1024** [comment]
Im willing to pay if you can get jitsi-meet compiled and running on the iPhone, how much would you charge me to do that for me?

**Comment by pdarcos** [comment]
Sorry @nsmith1024 I'm busy with other things.

By the way, I just tried clicking the "More actions" button on the same server I compiled yesterday and now I'm no longer getting the "TypeError: Cannot read property 'id' of undefined" error in the console.

Really weird since I didn't change anything from yesterday to today except to restart nginx.

Has anyone else seen this behavior?

**Comment by pdarcos** [comment]
Closing  this since it's almost certainly a mistake on my end.

I'll reopen if I come to the conclusion it's a bug in jitsi.

**Comment by pdarcos** [comment]
Reopening since I'm pretty certain there's a bug when creating debian packages.
I'm on debian 10.5

1) If I install jitsi-meet using the unstable repo but following the quick start guide all works as expected. I see the version installed is jitsi-meet-web 1.0.4420-1
2) If I git clone and then create the deb packages and then manually upload the debs and install them on the server I keep getting the "TypeError: Cannot read property 'id' of undefined" error in the console when clicking on "More actions".

Isn't the unstable repo built on the master branch? I don't understand why installing from unstable works but compiling debs locally seems to break something. I've compiled and installed debs locally in the past and never had this issue so I'm not sure what's going on.

Can someone from the jitsi team compile the debs from master and confirm they're getting the same error please?

Thanks

**Comment by nsmith1024** [comment]
Is the jitsi-team on vacation?

**Comment by pdarcos** [comment]
Closing this again since after I purged everything and tried again from scratch it worked
