### ISSUE TITLE
Static Images or Full name to be shown when user is inactive due to channelLastN.

### ISSUE THREAD

**Issue by SushantGautam** [jitsi/jitsi-meet#7748]
When using **channelLastN** the video of inactive participants will be shown blank.  Also, same when the video is turned off. It is difficult to identify viewers ( for eg, to mute them or know who are in the room.)

We can (maybe) periodically store the image thumbnails of participants in browser/divs and display those images instead of videos if videos are not shown from our side ( the participants have not turned his video on). That might add good experience while viewing inactive viewers (due to channelLastN). 

For inactive viewers (due to channelLastN) / participants with video turned off, we may want to show their **readable names** instead of just container with an image of the initial letter of the name. It will be easy to identify viewers.

**Comment by saghul** [comment]
We show the user's configured avatar. The initials based one is one we generate, but you can set your own either in the JWT token, if you are using that, or by using Gravatar on your email address. Full names will be shown when you hover. Doing it only for some participants would make the UI somewhat inconsistent, so we choose not to do that.
