### ISSUE TITLE
Make "mute everyone else" available on mobile applications 

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7749]
**Is your feature request related to a problem you are facing?**
I would like to mute every participant if I'm a moderator on mobile app. 

**Describe the solution you'd like**
On the user tiles there is a button that let's me mute everyone else but that person

**Describe alternatives you've considered**
No alternatives available, except joining from desktop

**Comment by saghul** [comment]
@muscat1 Any chance you can find some cycles for this?
