### ISSUE TITLE
Speaker's video resolution downgraded in version 2.0.4966-1

### ISSUE THREAD

**Issue by g-vidal** [jitsi/jitsi-meet#7753]
### Description:
When using jitsi with more than 2 users, all videos are downgraded when the 3rd comes in. I have tried to change the parameters in /etc/jitsi/meet/server-name-config.js in the new section videoQuality: {} with no effect. This did not happen in older versions  at least 2.0.4857-1 from which I did the upgrade.

### Steps to reproduce:

1. Open jitsi room
2. invite 2 users as soon as the third comes in the video's resolution  of the speaker is reduced
3.if one clicks on te multiview videos are correct (but smaller of course)

### Expected behavior:

Video of the speaker should remain at maximum possible resolution  according to available bandwidth

### Actual behavior: video is downgraded

- Jitsi Meet version: 2.0.4966-1
- Operating System: linux debian buster

### Client information:

- Browser / app version: chromium 83.0.4103.116
- Operating System: linux debian bullseye

**Comment by damencho** [comment]
This is a known issue which was fixed in latest unstable, we are looking forward to updating stable.
There is a workaround by removing some duplicate libraries that sneaked in latest release and are causing troubles: https://community.jitsi.org/t/jvb-spams-log-with-stack-trace/76864

**Comment by g-vidal** [comment]
Many thanks, sorry to have wasted some of your time I was not able to find the solution by myself in the discusions.
:+1:  for your work :clap:
