### ISSUE TITLE
Screenshare glitches

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#7754]
A participant shared their screen with an Excel sheet open, and the cell values were glitching, kind of like quickly alternating between being slightly blurry and clear.

### Steps to reproduce:

1. Share your full screen (I guess you could with Excel or Libreoffice open) and watch the screenshare from another device.

### Expected behavior:

There should be no glitching.

### Actual behavior:

Cell values alternate between slightly blurry and clear. The top parts of the column letters, e.g. the '-' part of 'E' (top part of the letter) alternate between visible and invisible as well.

### Server information:

- Jitsi Meet version: 2.0.4966-1
- Operating System: Ubuntu Desktop 20.04.1

### Client information:

- Browser / app version: Chromium 85.0.4183.102 snap
- Operating System: Ubuntu Desktop 20.04.1

(Those are my stats. The screensharer was on Windows 10 using Chrome).

**Comment by karniemi** [comment]
We are seeing the same issue on Ubuntu 18.04 and latest Chromium in the viewer side. It seems to be alternating between crisp and blurry image. With Firefox as the viewer, there's no problem.

I noticed an old bug about bandwidth detection issue in Chromium, which had been fixed though. The problem deacription seemed pretty much the same, maybe.

**Comment by vinoykr** [comment]
same here

**Comment by karniemi** [comment]
It seems the cause of the problem was found in https://github.com/jitsi/jitsi-meet-electron/issues/458 ...and a workaround was implemented. Of course, the problem should/could be reported to chrome/chromium?
