### ISSUE TITLE
No E2EE option on server instance

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#7757]
I see the E2EE option on Chromium on meet.jit.si but not when using my server.

### Expected behavior:

I assume the option was removed from the menu and moved to the password creation window because that's where it was when I tried on meet.jit.si.

### Actual behavior:

The E2EE option isn't on the password creation window when using Jitsi Meet running on my server.

### Server information:

- Jitsi Meet version: 2.0.4966-1
- Operating System: Ubuntu Desktop 20.04.1

### Client information:

- Browser / app version: Chromium 85.0.4183.102 snap
- Operating System: Ubuntu Desktop 20.04.1

### Additional information:

I read on the [community forum](https://community.jitsi.org/t/e2ee-option-removed/67432) that it might be because of browser updates that removed support for insertable streams and that it works fine on the Electron app, but I'm not sure about that since the option's present on Chromium using meet.jit.si.

**Comment by damencho** [comment]
https://community.jitsi.org/t/how-to-test-new-e2ee/39543/9?u=damencho
https://community.jitsi.org/t/how-to-test-new-e2ee/39543/11?u=damencho

Please use the community forum for asking questions before opening new issues.
