### ISSUE TITLE
Jitsi-meet + Unity

### ISSUE THREAD

**Issue by nsmith1024** [jitsi/jitsi-meet#7761]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

Integrating Jitsi-meet with Unity-3d

**Describe the solution you'd like**
Please describe the desired behavior.

Jitsi-meet works inside unity

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

using some other video chat software

**Comment by saghul** [comment]
This is too broad of a question, please ask questions in our community. There are some folks using Jitsi with Unity already.
