### ISSUE TITLE
Issues with rendering pixel3a video stream

### ISSUE THREAD

**Issue by pundiramit** [jitsi/jitsi-meet#7762]
Pixel3a video stream is not getting rendered properly. All I see is a garbled output on display. https://usercontent.irccloud-cdn.com/file/6pViqfHT/IMG_20200922_153738.jpg

No issues with video streams from other devices.

Running version 20.3.2 (203020) from fdroid https://f-droid.org/en/packages/org.jitsi.meet/

**Comment by saghul** [comment]
Any chance you can try 20.4.1 from the Play Store? I cannot reproduce it with our latest build.

**Comment by pundiramit** [comment]
I'm trying jitsi-meet on my PocoF1 phone (snapdragon 845 soc) but it is running AOSP (android open source project) with upstream linux kernel and open graphics stack (mesa-freedreno).

I do not have access to playstore. That's why I'm mostly using web launcher or the app from fdroid and I see this issue on both.

Is it possible to download 20.4.1 or latest apk from anywhere? Since I'm building AOSP locally, I suppose I can build this app from source as well but I'm not an app developer, so that might take a while.

**Comment by saghul** [comment]
Maybe the easiest would be to wait for F-Droid to update to 20.4.1.

**Comment by pundiramit** [comment]
Ack
