### ISSUE TITLE
popup chat messages

### ISSUE THREAD

**Issue by monnier** [jitsi/jitsi-meet#7768]
**Is your feature request related to a problem you are facing?**

In some of my video discussions, chat messages are used all the time, so I have the chat window always opened (even though it east up some of the screen, making the rest more difficult to see), but in other discussions chat messages are only used sporadically, and having to open the chat window and then close it to see the message is disruptive.  

**Describe the solution you'd like**
I'd like the chat to have a third state additionally to the current "closed" and "opened" states: in this third state, incoming messages would popup like notifications (and disappear after some timeout).

**Comment by monnier** [comment]
Be vanquished, foul stale robot!

**Comment by monnier** [comment]
Be vanquished, foul stale robot!

**Comment by saghul** [comment]
We now have pop ups for chat messages.
