### ISSUE TITLE
Add a link to https://github.com/imthenachoman/How-To-Secure-A-Linux-Server in the installation docs

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#7772]
Many who look into open-source Zoom alternatives, find Jitsi and run it on their own servers might be new to Linux and not know how to secure their servers beyond only opening needed ports and meeting-centric practices like strong passwords, secure domain and E2EE, with no further configuration. I just found the guide in the title and it seems great and beginner-friendly-enough to inexperienced Linux server newbies to follow.

**Comment by damencho** [comment]
Please use the community forum for questions or problems and topics like this, before opening new issues. Thank you.
