### ISSUE TITLE
More numbers in invite dialog crashes if only one number ist available

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7773]
### Description:

If the dial-in feature is enabled, then the invite dialog shows the link "More numbers".
If you click on the link and only one number ist available for dial in, then a new website appears with "Whoops, something went wrong." as content.

### Steps to reproduce:

1. Create a new room.
2. Open the invite dialog.
3. Click on "More numbers".

### Expected behavior:

If only one number is available, then hide the "More numbers" link.

**Comment by damencho** [comment]
What is the js logs? Which versions are you reproducing it with?

**Comment by heikar** [comment]
- The js console in the browser contains no error. Neither on the page with the "invite dialog" nor on the new page which opens.
- The installed version of jitsi-meet is 2.0.4857-1

**Comment by damencho** [comment]
So the json does not have any numbers is what you say?

**Comment by heikar** [comment]
Right. The json only contains one number.

**Comment by damencho** [comment]
beta .meet.jit.si is currently configured with just one number and works fine. Strange. There should be some error somewhere ...

**Comment by heikar** [comment]
How looks the beta? Is the link invisible or show the dialInInfo.html this one number?

**Comment by damencho** [comment]
You can check it yourself 
![image](https://user-images.githubusercontent.com/3263098/94069840-de14c600-fdb6-11ea-88c8-5bf7324078d2.png)

**Comment by heikar** [comment]
Hm... very strange.
I think, the days i do an test installation with the current nighty. Maybe the error is in the installation/configuration...

**Comment by damencho** [comment]
I would suspect json format 
here is beta one to compare: https://web-cdn.jitsi.net/beta/phoneNumberList.json

**Comment by heikar** [comment]
The format is the same. With other phone number ;) but the format is the same.
Is the right filename important?

**Comment by damencho** [comment]
Nope, maybe the webserver is not returning you the right mime format. Try adding the beta link ...

**Comment by heikar** [comment]
The returned type from my webserver (apache2) is correct.
I use other tools to consume json from the web server and that works.
And the first number (or the only number if no other is in the json) appears correct in the invite dialog :(

**Comment by damencho** [comment]
There should be an error, enable preserve logs and try finding it. Trying to guess without error or example will not work.

**Comment by heikar** [comment]
Now I have found out something.

If i click on the link then e.g. the site dialInInfo.html?room=test12 opens with the error message.
If i modify the url in e.g. dialInInfo.html?room=test then it is correct, like in your beta screenshot.

It seems like there is an error in my conferencemapper.php. Later i will review the code of it.
If i find the error i will update this issue.

At this point, i say thank you, for your time and your help :) Now i have a point where i can search.

**Comment by heikar** [comment]
It went faster than expected :D

The problem was in the table which stores the data.
The columns were not declared as `UNIQUE`.

After `ALTER TABLE` with `UNIQUE` to the columns it works :)
