### ISSUE TITLE
Mute sound of the conference

### ISSUE THREAD

**Issue by niyaz1998** [jitsi/jitsi-meet#7776]
I want to add my phone simply as a camera to the conference, for example to show something, while using my laptop to speak with other people in conference

I would like to have button to disable sound of the conference and feature option to start conference without sound,

**Comment by saghul** [comment]
You can join the conference with this at the end of the URL: #config.startSilent=true

**Comment by niyaz1998** [comment]
> 
> 
> You can join the conference with this at the end of the URL: #config.startSilent=true

Is it possible to add such thing for mobile? Especially for flutter plugin

**Comment by niyaz1998** [comment]
@saghul

**Comment by saghul** [comment]
We don't maintain the flutter plugin, you'd have to ask whoever is responsible for that.

**Comment by niyaz1998** [comment]
@saghul, flutter plugin seems don't have such functionality, so I want to write it by myself
It will be great if you tell me how to pass such thing as `#config.startSilent=true` to the mobile application, or react native application

**Comment by saghul** [comment]
Ah the flutter plugin is using our SDK? Then we'd need some changes, we don't have full support for it on mobile I think.

**Comment by niyaz1998** [comment]
@saghul this feature is really important for us, can you implement it faster? or give me some information, so I can try to do it by myself
