### ISSUE TITLE
Memory leak on jitsimeet sample App

### ISSUE THREAD

**Issue by JacobGbGuan** [jitsi/jitsi-meet#7777]
### Description:
As two rules in a meeting, the one joined via app, other one via web.

And 10 hours later, we find the l G memory leak in the android app side.

As detail memory report please find it in the Additional informationis.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:jitsi-meet 3936
- Operating System:

### Client information:

- Browser / app version:sample android App
- Operating System: android 9.0

### Additional information:

========================================

Applications Memory Usage (in Kilobytes):
Uptime: 277843421 Realtime: 321257266

** MEMINFO in pid 13392 [net.jitsi.sdktest] **
                   Pss  Private  Private  SwapPss     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    76355    76280        0        0   133120    92091    41028
  Dalvik Heap     6601     6580        4       49     8301     4151     4150
 Dalvik Other     3752     3752        0        0                           
        Stack      112      112        0        0                           
       Ashmem        2        0        0        0                           
      Gfx dev     9232     9040      192        0                           
    Other dev       32        0       32        0                           
     .so mmap    17886      840    13964       39                           
    .apk mmap    10209     7944     1644        0                           
    .ttf mmap       28        0        0        0                           
    .dex mmap     7363     4020     1660        0                           
    .oat mmap      133        0       56        0                           
    .art mmap     7109     6488       68        3                           
   Other mmap      115        4       88        1                           
   EGL mtrack    19700    19700        0        0                           
    GL mtrack     7736     7736        0        0                           
      Unknown   **911658**   911652        0        0                           
        TOTAL  **1078115**  1054148    17708       92   141421    96242    45178

========================================================================

**Comment by saghul** [comment]
Alas that report doesn't say much. I know we have a "leak" in that we keep a reference to the current activity in a singleton object. Leak Canary reports this, but it's not a problem in practice because the lifetimes of both objects are in sync.

If this is something else, we are going to need some more details.

**Comment by JacobGbGuan** [comment]
> Alas that report doesn't say much. I know we have a "leak" in that we keep a reference to the current activity in a singleton object. Leak Canary reports this, but it's not a problem in practice because the lifetimes of both objects are in sync.
> 
> If this is something else, we are going to need some more details.

Hi sir ,
it is surely the repo generate from jitsti-meet SDK has memory leak bug.  And the memory type is "unknown".

So the javascript code maybe the memory leak ponter.

If you run the app in more than 10 hours , the app maybe killed  because android lowmemory killer.

**Comment by shoolpani-dubey** [comment]
@saghul You had mentioned in the previous comments that there is a memory leak in the native side where we keep a reference to the current activity in a singleton object. Can you point me to the correct file. I am planning to fix this issue

**Comment by saghul** [comment]
I believe it starts here: https://github.com/jitsi/jitsi-meet/blob/2a321d6b1fdc4f5fc6009e628a18d9e5435c1b39/android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java#L60 because that will hold on to the current activity internally.
