### ISSUE TITLE
Jitsi-meet for Unity-3D Game Engine

### ISSUE THREAD

**Issue by nsmith1024** [jitsi/jitsi-meet#7780]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

I would like to integrate jitsi-meet with Unity-3d Game engine

https://www.unity3d.com

Unity is used my millions of game developers all over the world.

**Describe the solution you'd like**
Please describe the desired behavior.

jitsi-meet integrated with Unity 3D

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

none

**Comment by saghul** [comment]
Please stop posting duplicates. I already replied yesterday this is not the place to ask these questions. https://github.com/jitsi/jitsi-meet/issues/7761#issuecomment-697186029
