### ISSUE TITLE
Cannot remove previous incorrect DNS name on reinstall

### ISSUE THREAD

**Issue by bbrout** [jitsi/jitsi-meet#7782]
#6845 # Description:

using droplet under DigitalOcean, Ubuntu 18.04.5 LTS, 4.15.0-118-generic

attempted an install with incorrect domain name. Cannot reinstall with correct domain name

### Steps to reproduce:

1. install prerequisites
2. run apt install jitsi-meet
3. chose "Generate a new self-signed certificate" during install
4. entered "rasl.ca/meetings for the domain name
5 install failed with error 
  Generating a RSA private key
................++++
.....................++++
writing new private key to '/etc/jitsi/meet/rasl.ca/meetings.key'
req: Can't open "/etc/jitsi/meet/rasl.ca/meetings.key" for writing, No such file or directory
dpkg: error processing package jitsi-meet-web-config (--configure):
 installed jitsi-meet-web-config package post-installation script subprocess returned error exit status 1
6. purged the install with command apt purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2
7. thoroughly repurged everything including /etc/jitsi
8. rebooted
9. reinstalled prerequisites
10. ran apt install jitsi-meet
11. again chose chose "Generate a new self-signed certificate" during install
12. install crashed with same error of attempting to use rasl.ca/meetings without it asking me to enter a new domain name

### Expected behavior:

apt install jitsi-meet should ask for a new domain name

### Actual behavior:

apt install jitsi-meet does not ask for new domain name and crashes

### Server information:

- Jitsi Meet version:  https://download.jitsi.org stable
- Operating System: Ubuntu

### Client information:

- Browser / app version: Chrome
- Operating System: Ubuntu

### Additional information:

I have purged then used locate rasl to remove all mention of this in files
I have used locate jitsi to remove all mention of jitsi from computer
rebooted many times
these attempts have failed. I cannot get the install to ask for a new domain name

**Comment by badirdev** [comment]
Im having the exact same issue. Any luck?

**Comment by bbrout** [comment]
Yes. By the mercy of the gods, I had a droplet backup just before I started
trying to install jitsi. So I restored I backup then went through and
reinstalled. Unfortunately, the only solution was to nuke and pave.

**Comment by Saif-Amer-20** [comment]
Im having the exact same issue.How can I solve this?
