### ISSUE TITLE
Button "More Actions" Missing from bottom toolbar

### ISSUE THREAD

**Issue by corby-github** [jitsi/jitsi-meet#7787]
### Description: Button "More Actions" Missing from bottom toolbar

Running jitsi-meet 2.0.5076-1 I can easily get in a situation where the more actions button is hidden. 

### Steps to reproduce:

Option 1)
1. Start a new meeting on https://meet.jit.si/moreActionsButtonMissing
2. Resize the browser window to around 800px in width
3. Open the "chat" window which will compress the bottom tool bar. The 3-dot "More Actions" button is the first to hide.

Option 2)
1. From a desktop browser, open https://meet.jit.si/moreActionsButtonMissing
2. Resize the window to under 500px
3. Notice the 3-dot "More Actions" button is missing.

Option 3) 
1. From a mobile browser, open https://meet.jit.si/moreActionsButtonMissing
2. Notice the 3-dot "More Actions" button is *sometimes* missing.

### Expected behavior:

With previous releases, the 3-dot menu was not hidden that other actions to the right and left of the `button-group-center` were properly folded into the `overflow-menu`

### Actual behavior:

In option 1) when chat is enabled, icons are overlapping and the `more actions` button is missing. In option 2) the `more actions` button is missing and sometimes missing on option 3).

> Additionally, with this release, as the window is made smaller, icons are compressed so they just too tiny to be useful under 500px

![missing2](https://user-images.githubusercontent.com/63730925/94303925-a9cb1200-ff3c-11ea-93eb-30a5c992bbfa.png)
![missing1](https://user-images.githubusercontent.com/63730925/94303929-aa63a880-ff3c-11ea-82cc-53548185afb0.png)

### Server information:

- Jitsi Meet version: https://meet.jit.si as of 09/25/2020, and observed in jitsi-meet 2.0.5076-1
- Operating System: meet.jit.si  & ubuntu

### Client information:

- Browser / app version: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Operating System: macOS

**Comment by corby-github** [comment]
Looks related to https://github.com/jitsi/jitsi-meet/issues/7609

**Comment by Echolon** [comment]
Thank you for your report @corby-github !

**Comment by jallamsetty1** [comment]
Thanks for the report, will take a look at what’s happening here

**Comment by jallamsetty1** [comment]
This issue has been fixed in the tip of master - https://github.com/jitsi/jitsi-meet/commit/9379bb3c5b56b1ebac5215a926d4e83beeb6adac.
