### ISSUE TITLE
How to disable the "Install the extension..." popup

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#7789]
**Is your feature request related to a problem you are facing?**
Using the Jitsi iframe API, how can the "Install the extension..." popup be disabled (see below).

**Describe the solution you'd like**
Perhaps an optional parameter to `JitsiMeetExpernalAPI`?

**Describe alternatives you've considered**
N/A

![Untitled](https://user-images.githubusercontent.com/400552/94343737-d2f0ae80-ffdf-11ea-98fa-8ce3654fa293.png)

**Comment by izakgl** [comment]
You already have the option to overwrite the interface config, which is where you can find this option.

```
const options = {
    ...
    interfaceConfigOverwrite: { SHOW_CHROME_EXTENSION_BANNER: false },
    ...
};
const api = new JitsiMeetExternalAPI(domain, options);
```

**Comment by mrose17** [comment]
Thank you! I guess i should always look at https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js first !!!
