### ISSUE TITLE
self hosted jitsi-meet isn't working for few clients whose firewall may blocked video streaming however google meet and even http://meet.jit.si are working fine.

### ISSUE THREAD

**Issue by viswa7** [jitsi/jitsi-meet#7790]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Please use the community forum for questions or problems before creating new issues, thank you.

Most probably they need a turn server running on port 443 on that deployment.
