### ISSUE TITLE
jitsi-meet-turnserver 1.0.4184-1 misses `/usr/share/jitsi-meet-turnserver/jitsi-meet.conf`

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#7794]
Upgrading `jitsi-meet-turnserver` from 1.0.4420-1 to 1.0.4434-1 the file `/usr/share/jitsi-meet-turnserver/jitsi-meet.conf` is missing. This causes Nginx fail to start, as `/etc/nginx/modules-enabled/60-jitsi-meet.conf` is a symbolic link to that file.

**Comment by damencho** [comment]
Thanks for the report.

**Comment by paulmenzel** [comment]
Commit 93f4098dc0 (feat: Enable bridge websockets by default for new installs (#7781)) introduced the regression.

**Comment by paulmenzel** [comment]
The symbolic link `/etc/nginx/modules-enabled/60-jitsi-meet.conf` is deleted in the postrm script, but should also be deleted when upgrading.

I’ll read https://jitsi.github.io/handbook/docs/devops-guide/faq#how-to-migrate-away-from-multiplexing-and-enable-bridge-websockets now to fix the setup.

**Comment by damencho** [comment]
> The symbolic link `/etc/nginx/modules-enabled/60-jitsi-meet.conf` is deleted in the postrm script, but should also be deleted when upgrading.

That is removed only on purge. 

> 
> I’ll read https://jitsi.github.io/handbook/docs/devops-guide/faq#how-to-migrate-away-from-multiplexing-and-enable-bridge-websockets now to fix the setup.

👍 


The problem was removed from the package ... but if its used as a symlink we need to keep it for some time before removing it so we do not break peoples deployments, before they have the chance to migrate. I will add that change.
