### ISSUE TITLE
Incoming call JitsiMeetView integration with CallKit

### ISSUE THREAD

**Issue by AndaBucsa** [jitsi/jitsi-meet#7797]
Hi,

Currently when we receive a `PushKit` incoming call notification we invoke `JMCallKitProxy.ReportNewIncomingCallWithUUID` which displays the iOS Accept / Reject UI.

When the user taps on Accept - `PerformAnswerCallWithUUID` is invoked on `JMCallKitListener` and at this point we navigate to our own view controller which creates a `JitsiMeetView` and calls `Join` on it.

However - even when the user ends the call by tapping the end call button in `JitsiMeetView`, the iOS built-in call screen is still displayed. Is there a way to link the `JitsiMeetView` with the `UUID` of the call reported on `JMCallKitProxy.ReportNewIncomingCallWithUUID` so any actions performed on the `JitsiMeetView` are synced with the iOS built-in UI?

I believe this is also the source of several bugs such as the `CallKit` mute / unmute and speaker buttons not working when receiving a call and the device is locked.

Thank you,
Anda

**Comment by Furqankhanzada** [comment]
@AndaBucsa have made progress on it ?

**Comment by saghul** [comment]
What URL did you use to join the conference? You can add `#config.callUUID=YOUR_UUID_IN_UPPERCASE` to the room URL and that should pass it to the internal handling.

We should have a helper for this in JitsiMeetConferenceOptions I think.

**Comment by AndaBucsa** [comment]
Hi @saghul,

I don't see any way to pass the CallKit UUID to the JitsiMeetConferenceOptions. Could you please send me a sample URL that contains the CallKit UUID?

Thanks,
Anda

**Comment by saghul** [comment]
`https://meet.jit.si/test123#config.callUUID=YOUR_UUID_IN_UPPERCASE`

**Comment by AndaBucsa** [comment]
Thank you @saghul 

I tried to pass the complete server url like you said but I got stuck on a loading state in Jitsi, where actually connection is trying to establish to the server url.

I will paste here the code snippet that I used

`  JitsiMeetConferenceOptions *options
        = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
            builder.serverURL = [NSURL URLWithString:@"https://meet.jit.si/call-kit-uuid-test-room#config.callUUID=..."];
        }];
    [jitsiView join:options];` 

with the above option I get stuck in loading state

After I passed room on JitsiMeetConferenceOptions, the connection was established.

  `  JitsiMeetConferenceOptions *options
        = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
            builder.serverURL = [NSURL URLWithString:@"https://meet.jit.si"];
            builder.room = @"call-kit-uuid-test-room";
        }];
    [jitsiView join:options];`

however there's no way to pass the `config.callUUID` since the room is appended to `serverURL`

Thanks,
Anda

**Comment by saghul** [comment]
Pass the full URL as the room, not the serverURL.

**Comment by AndaBucsa** [comment]
Hi @saghul 
Mute/Unmute and Speaker buttons still not working when device is locked, I debugged the code and I checked the #config.CallUUID that is appended to the url I have an callUUID ending in 350BBB and in logs I see that Jitsi starts its own call with a new callUUID.

`--- JITSI --- [RNCallKit][startCall] callUUID = 617D6523-9C61-41BE-9469-3D6A037F9377`

Do you have any other ideas to make it work?

Thanks, 
Anda

**Comment by saghul** [comment]
Can you paste the full logs? This should work in principle, if the option is called `callUUID` (it's case sensitive) but we don't have this usecase ourselves and might have broken it :-/

If you are up for it, modifying one of the sample SDK apps to add a "test incoming call" button to simulate one would really help here.

**Comment by AndaBucsa** [comment]
You can find the logs here https://gist.github.com/AndaBucsa/4389a23d104140e89b8215d18c5c68d7

As for modifying the sample SDK app, we'll try to get back to you by the end of the week.

**Comment by saghul** [comment]
> --- JITSI --- 'Failed to parse URL parameter value: 878389E8-EA38-4D55-A9D9-DF6E51B58862', { [SyntaxError: JSON Parse error: Invalid number]

I think we might need quotes.

**Comment by AndaBucsa** [comment]
Yes, added quotes and mute/unmute button is working now!!! Big thanks for this!

Still having issues with speaker button, it's always enabled and when I tap on it it's not doing anything (it's not switching to earpiece) and it stays enabled all the time even if I press on it.

**Comment by PauMateu** [comment]
Is there an equivalent solution for ConnectionService in Android? It seems that if I use it to summon the native call UI, then it interferes with the jitsi plugin, and I have to end the first call to start the jitsi one.

**Comment by saghul** [comment]
You can disable ConnectionService integration in the Jitsi plugin. Set the `call-integration.enabled` feature flag to false.

**Comment by naive924** [comment]
Hello. Can you tell me any sample code for Incoming call?

**Comment by fbelinic** [comment]
Hey guys, currently working with PushKit incoming call notification which is invoked with JMCallKitProxy.”reportNewIncomingCall”. This method displays the iOS Accept / Reject UI. Our issue is that - when user taps on any action, JMCallKitListener does not trigger method like “performAnswerCall” or decline method “performEndCall”. Our listener is AppDelegate which is extended with JMCallKitListener. Any help would be welcome!

**Comment by eleyanSaad** [comment]
> Hi,
> 
> Currently when we receive a `PushKit` incoming call notification we invoke `JMCallKitProxy.ReportNewIncomingCallWithUUID` which displays the iOS Accept / Reject UI.
> 
> When the user taps on Accept - `PerformAnswerCallWithUUID` is invoked on `JMCallKitListener` and at this point we navigate to our own view controller which creates a `JitsiMeetView` and calls `Join` on it.
> 
> However - even when the user ends the call by tapping the end call button in `JitsiMeetView`, the iOS built-in call screen is still displayed. Is there a way to link the `JitsiMeetView` with the `UUID` of the call reported on `JMCallKitProxy.ReportNewIncomingCallWithUUID` so any actions performed on the `JitsiMeetView` are synced with the iOS built-in UI?
> 
> I believe this is also the source of several bugs such as the `CallKit` mute / unmute and speaker buttons not working when receiving a call and the device is locked.
> 
> Thank you,
> Anda



> You can disable ConnectionService integration in the Jitsi plugin. Set the `call-integration.enabled` feature flag to false.

hi How can I open jitsimeet join vc , when coming call and user enter answer ?

**Comment by ArdyWijaya** [comment]
Hi @saghul, We are currently implement jitsi meet with callkit. So when the user has the phone unlocked, we are able to open our application once the user accepts the call, where the Jitsi View is displayed. However, when the user has the phone locked, we are displaying the native call interface. Then when we click the video button, the phone displays unlock pattern. After user unlocks the phone, jitsi meet view is displayed, but suddenly we got disconnected.  May I know if Is this problem because of Jitsi SDK that doesn't handle it yet or do we need to handle it by myself?

**Comment by saghul** [comment]
When you press the video icon an outgoing call is placed to the same handle / url.

**Comment by ArdyWijaya** [comment]
How about for incoming call @saghul ?

**Comment by saghul** [comment]
Not sure, we don't have that use case. What I do know is that CallKit does not allow you to handle that button, it does its own thing, alas.
