### ISSUE TITLE
Audio notification for waiting room knocking

### ISSUE THREAD

**Issue by aleperotti** [jitsi/jitsi-meet#7800]
It would be nice and useful to add an audio notification for moderator when a guest knocks to enter to a conference with waiting room enabled.

**Comment by amsnek** [comment]
Yes, I absolutely agree. This would be a *very nice to have* feature for the Lobby.

**Comment by daseinzigwahreuwe** [comment]
Hi, I also agree. This would be a very good feature.

**Comment by jpkelly** [comment]
+1 for waiting room knocking audio notification.

**Comment by ektorcaba** [comment]
+1 for waiting room knocking audio notification.

**Comment by d3hof** [comment]
+1 here would be great to have that feature

**Comment by nodiscc** [comment]
https://github.com/jitsi/jitsi-meet/issues/9606
