### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by luckymehndiratta** [jitsi/jitsi-meet#7806]
We Install the JITSI Pod in the project and we face this issue

sent 44344538 bytes  received 3338 bytes  12670821.71 bytes/sec
total size is 44328260  speedup is 1.00
/Users/lucky/Documents/Jitsi/Pods/Target Support Files/Pods-Jitsi/Pods-Jitsi-frameworks.sh: line 144: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code

Please look into this

**Comment by saghul** [comment]
What exact steps are you following?

**Comment by luckymehndiratta** [comment]
Step 1 : Create a iOS Project 
Step 2: Pod init
Step 3: pod 'JitsiMeetSDK' add this pod in pod file
Step 4 : Pod intsall 
Step 5 : Run the code & this error comes up

**Comment by saghul** [comment]
What cocoapods version are you using? What Xcode version?

**Comment by luckymehndiratta** [comment]
Xcode Version -> 11.4
CocoaPods version -> 1.9.3

**Comment by saghul** [comment]
The latest SDK (2.10) was built with Xcode 12. So you can either update, or pin your dependency to an earlier version (2.9).

**Comment by Limitless-Kode** [comment]
> The latest SDK (2.10) was built with Xcode 12. So you can either update, or pin your dependency to an earlier version (2.9).

I use Xcode 15 and I get this same error

**Comment by Limitless-Kode** [comment]
> It will likely be a different error even though the outcome might look the same.
> 
> Please open a new issue and provide as many details as possible.

I am facing the exact same problem and I followed the same 5 steps listed above 

ERROR:

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by saghul** [comment]
The reason for the script failing is 100% not the same because it has changed a lot in the last 3 years

**Comment by Limitless-Kode** [comment]
> The reason for the script failing is 100% not the same because it has changed a lot in the last 3 years

I don't get any extra details just this

Command PhaseScriptExecution failed with a nonzero exit code

It's kinda hard to know where to look, do you have any suggestions on where I could look?

**Comment by saghul** [comment]
Can you paste the full build log in a gist?
