### ISSUE TITLE
Facing Issue with Jibri while trying to record Jitsi-meet conference. #17

### ISSUE THREAD

**Issue by pramod-linux** [jitsi/jitsi-meet#781]
Hi Team,

I have configured jitsi-meet on my local Machine(Ubuntu-16.04) using (#apt-get install jitsi-meet) it's working fine, we are able to video conference successfully but I just want to record conference so just changed **`enableRecording: true`** in jitsi-config.js file and create a directory **.sip-communicator** under jvb user's home directory.

Create a file **sip-communicator.properties** under .sip-communicator and add

```
org.jitsi.videobridge.ENABLE___MEDIA_RECORDING=true
org.jitsi.videobridge.MEDIA___RECORDING_PATH=/srv/recordings
org.jitsi.videobridge.MEDIA___RECORDING_TOKEN=123
```

After making these changes I got Recording Button on jitsi-meet UI but recording button still not working. I got error:-

>  The recording service is currently unavailable. Please try again later.

I have installed Jibri as per this link [https://github.com/jitsi/jibri](url) and unable to record conference session as per documentation.

./scripts/launch_recording.sh https://jitsi.example.com/meeting recording.wav
`
If i am wrong then please correct me and provide me some links or documentation where i can take help and configure Jibri.

Thanks in advanced..

**Comment by tarlesurendra** [comment]
Hello Pramod,

Have you fixed your recording issue?
can you help me regarding video stream?
