### ISSUE TITLE
Creating Welcome Image / Intro

### ISSUE THREAD

**Issue by KaijuDeluxe** [jitsi/jitsi-meet#7815]
While my students are waiting for the start of the session it would be really really cool if i can start a video with music until the session starts, like the "intro" before an apple event starts

**Comment by heikar** [comment]
Maybe it was a nice feature to implement this page (or in another kind), as a "info page" before each meeting with informations about the meeting host (e.g. company informations, link to the company page) and a custom are on the page for as example a small intruction to use the meeting.

**Comment by KaijuDeluxe** [comment]
> Maybe it would be a nice feature to implement this page (or in another kind), as a "info page" before each meeting with informations about the meeting host (e.g. company informations, link to the company page) and a custom are on the page for as example a small intruction to use the meeting.

Also a Great idea which should be more easier to implement.
