### ISSUE TITLE
Program type already present: com.BV.LinearGradient.BuildConfig 

### ISSUE THREAD

**Issue by vinaygoyal20** [jitsi/jitsi-meet#7816]
While i am able to run the project but getting weird issue while making build like

-> Unable to find a matching variant of project :react-native-community_art: - Variant 'debugApiElements' capability pna:react-native-community_art:unspecified: - Incompatible attribute:

-> More than one file was found with OS independent path 'META-INF/react-native-webview_release.kotlin_module'

**Comment by saghul** [comment]
What are you trying to do? What steps did you follow?

**Comment by vinaygoyal20** [comment]
I was able to resolve it after 
 implementation (project(':react-native-jitsi-meet')) {

        exclude group: 'com.facebook.react',module:'react-native-webview'
        exclude group: 'com.facebook.react',module:'react-native-linear-gradient'
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
        exclude group: 'com.facebook.react',module:'@react-native-community/netinfo'

     }

and downgrading the version of  @react-native-community/netinfo  to 5.0.0
