### ISSUE TITLE
On calling JitsiMeetActivity second time starts pip mode Android

### ISSUE THREAD

**Issue by thilagrai-aglab** [jitsi/jitsi-meet#7820]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

On calling JitsiMeetActivity second time starts pip mode Android

**Comment by Echolon** [comment]
@thilagrai-aglab may you fill out the template sufficiently?

**Comment by saghul** [comment]
Did the first activity finish? If not, that is the expected behavior.
