### ISSUE TITLE
Make smart shared video muting-unmuting optional.

### ISSUE THREAD

**Issue by 317070** [jitsi/jitsi-meet#783]
While useful for some tasks, at the moment it is not possible to comment while the video is playing, even when such a thing would be useful.

**Comment by kirkjaa** [comment]
Yes this would be useful since some of my clients do make a request for this. For example teaching music, the instructor usually would make verbal comments over the demo  shared video for student to observed. Or even in business usually clients would like to voice over the video to add commentary.
