### ISSUE TITLE
DEVELOPERS:How can I integrate it to my current react-native app?

### ISSUE THREAD

**Issue by rananajam1** [jitsi/jitsi-meet#7831]
**Is your feature request related to a problem you are facing?**
Need to find the right approach to add this to my React-Native project

**Describe the solution you'd like**
I want to integrate this code into my react-native application. Will be very thankful for any leads

**Describe alternatives you've considered**
Android and IOS SDK but they have limited features

**Comment by Echolon** [comment]
Hi,

please visit the Jitsi Conmunity portal for questions

**Comment by rananajam1** [comment]
@Echolon I have tried posting on the Community portal but hardly any response

**Comment by rananajam1** [comment]
@saghul can you please briefly explain the steps? I am in the learning phase and I want to integrate this awesome library to my existing react-native project while customizing the SDK as per the requirements
