### ISSUE TITLE
Impossible to continue music playback on Samsung phones with bluetooth headphones after leaving Jitsi meet call

### ISSUE THREAD

**Issue by krezzoid** [jitsi/jitsi-meet#7832]
### Steps to reproduce:

1. Connect a bluetooth headphones with mic to Samsung phone with Android 10
2. Start to play music with Deezer/Spotify
3. Run Jitsi SDK Android sample application
4. Join meeting call - in this stage music will be paused automatically
5. Leave meeting call and try to continue play music - impossible to play music till reset bluetooth cache or disconnect/connect headphones

### Expected behavior:

Music continue playback without any additional workaround steps.

### Client information:

- Jitsi Android SDK: 2.10.0
- Operating System: Android 10
- Phone: Samsung S10/S9

**Comment by saghul** [comment]
Did you disable native call integration?

**Comment by krezzoid** [comment]
@saghul did you mean "call-integration.enabled" ? if so, not yet, let me try to confirm.

**Comment by krezzoid** [comment]
@saghul yes, this option solved the problem.
Thanks for advise.
