### ISSUE TITLE
[BUG] Android release SDK is not working

### ISSUE THREAD

**Issue by djorkaeffalexandre** [jitsi/jitsi-meet#7834]
### Description:
I'm trying to self build an Android SDK but with the latest master branch it's not possible. (I'm trying without any change to the code).
I ran the following commands:
```sh
npm install
./android/scripts/release-sdk.sh /tmp/repo
```
For first I've received this build error message:
![Screen Shot 2020-10-02 at 9 17 49 AM](https://user-images.githubusercontent.com/29778115/94922411-8d752b00-0490-11eb-96cf-4df62eb5f3b7.png)
Commenting lines 147 to 150 bypass this error:
https://github.com/jitsi/jitsi-meet/blob/master/android/build.gradle#L147
But when I bypass this error, all the libraries are failing the build, each time that I run the script again it raises an error on a different dependency:
![Screen Shot 2020-10-02 at 9 27 31 AM](https://user-images.githubusercontent.com/29778115/94922995-87337e80-0491-11eb-844a-ef5669b2bb6f.png)

### Steps to reproduce:

1. Clone jitsi-meet
2. Install node dependencies `npm install`
3. Run android release-sdk.sh `./android/scripts/release-sdk.sh /tmp/repo`

### Expected behavior:

SDK should be generated with a successful build.

### Actual behavior:

Build fails with random errors.

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: N/A
- Operating System: N/A

### Additional information:

I've cloned this right now and try again, same result, here are some of my sdk versions, feel free to ask me any question.
![Screen Shot 2020-10-02 at 9 26 47 AM](https://user-images.githubusercontent.com/29778115/94923185-d2e62800-0491-11eb-85f6-3e6540ad3f39.png)

**Comment by saghul** [comment]
Thanks for the report! @tmoldovan8x8 can you repro this?

**Comment by sunilkumarjena21** [comment]
Hi @saghul ,
I have had the same issue & reported this yesterday.

https://github.com/jitsi/jitsi-meet-sdk-samples/issues/56#issuecomment-702608792

**Comment by sunilkumarjena21** [comment]
Hi @saghul  ,

Thanks for your awesome support on this community.

I have followed the step build my own SDK as mentioned in the below link.

Branch used:-https://github.com/jitsi/jitsi-meet/tree/mobile-fix-20.5-build

// Jitsi Meet
`implementation('org.jitsi.react:jitsi-meet-sdk:2.11.0')`

Trying to change `jitsi-meet-sdk` to `connect-lane-sdk`

Step followed:-
Step 1:-Changed the below lines in build.gradle of SDK as per below image.
![image](https://user-images.githubusercontent.com/32553699/94998792-1778dd00-05d2-11eb-99aa-54d3ffe84870.png)


Step -2: npm i
Step -3:./android/scripts/release-sdk.sh /tmp/repo
Step-4:-Uploaded in my repo:https://github.com/sunilkumarjena21/connectlane-android-sdk
Step 5:- Used in my android project `implementation('org.connect.react:connect-lane-sdk:2.11.0')`

Got the below error as mentioned in below screenshot.
![sdk-img](https://user-images.githubusercontent.com/32553699/94998789-1051cf00-05d2-11eb-81b3-8042574e47c3.JPG)


You help will be much appreciated on this.
Thanks in advance!

**Comment by sunilkumarjena21** [comment]
Hi @saghul  ,

Thanks for your awesome support on this community.

I have followed the step build my own SDK as mentioned in the below link.

Branch builds fine:-https://github.com/jitsi/jitsi-meet/tree/mobile-fix-20.5-build

// Jitsi Meet
implementation('org.jitsi.react:jitsi-meet-sdk:2.11.0')

Wanted to achieve the customization as per below:-
Trying to change jitsi-meet-sdk to connect-lane-sdk

Step followed:-
Step 1:-Changed the below lines in build.gradle of SDK as per below image.
Step -2: npm i
Step -3:./android/scripts/release-sdk.sh /tmp/repo
Step-4:-Uploaded in my repo:https://github.com/sunilkumarjena21/connectlane-android-sdk
Step 5:- Used in my android project implementation('org.connect.react:connect-lane-sdk:2.11.0')

Got the below error as mentioned in below screenshot.
![sdk-img](https://user-images.githubusercontent.com/32553699/95071847-ed393380-0727-11eb-8106-338876ece455.JPG)


You help will be much appreciated on this.
Thanks in advance!

**Comment by sunilkumarjena21** [comment]
@saghul ,

Your response will be most appreciated for above Own SDK customisation.
Thanks in advance !

**Comment by sunilkumarjena21** [comment]
Hey @djorkaeffalexandre ,
Thanks for your response.
The steps mentioned by you. Just wanted to clarify..
Is these steps for solving this [issue.(](https://github.com/jitsi/jitsi-meet/issues/7834#issuecomment-703558681) ) ?

Thanks in advance !

**Comment by djorkaeffalexandre** [comment]
@sunilkumarjena21 yep, exactly

**Comment by sunilkumarjena21** [comment]
HI @djorkaeffalexandre ,
Let me try this step & hopefully i will comeback to you with some good news..
Thanks for your great knowledge & continuous support on this forum. 👍

**Comment by sunilkumarjena21** [comment]
Hi @djorkaeffalexandre ,

I have followed the steps suggested by you.

> remove react-native check of VersionNumber on build.gradle

Here is the screenshot:- 
![veersion_check](https://user-images.githubusercontent.com/32553699/95242503-e516ec00-082c-11eb-941b-213d13dc8a61.JPG)

> build each dependency and publish using:
sudo ./gradlew :react-native-background-timer:assembleRelease
sudo ./gradlew :react-native-calendar-events:assembleRelease
sudo ./gradlew :react-native-community-async-storage:assembleRelease
sudo ./gradlew :react-native-community_netinfo:assembleRelease
sudo ./gradlew :react-native-default-preference:assembleRelease
sudo ./gradlew :react-native-immersive:assembleRelease
sudo ./gradlew :react-native-keep-awake:assembleRelease
sudo ./gradlew :react-native-linear-gradient:assembleRelease
sudo ./gradlew :react-native-sound:assembleRelease
sudo ./gradlew :react-native-svg:assembleRelease
sudo ./gradlew :react-native-webrtc:assembleRelease
sudo ./gradlew :react-native-webview:assembleRelease



sudo ./gradlew :react-native-background-timer:publish
sudo ./gradlew :react-native-calendar-events:publish
sudo ./gradlew :react-native-community-async-storage:publish
sudo ./gradlew :react-native-community_netinfo:publish
sudo ./gradlew :react-native-default-preference:publish
sudo ./gradlew :react-native-immersive:publish
sudo ./gradlew :react-native-keep-awake:publish
sudo ./gradlew :react-native-linear-gradient:publish
sudo ./gradlew :react-native-sound:publish
sudo ./gradlew :react-native-svg:publish
sudo ./gradlew :react-native-webrtc:publish
sudo ./gradlew :react-native-webview:publish

> remove the clean of this line https://github.com/jitsi/jitsi-meet/blob/master/android/scripts/release-sdk.sh#L92.

Here is the screenshot:-
![clean_word_removed](https://user-images.githubusercontent.com/32553699/95242682-27402d80-082d-11eb-989b-4af30975ed83.JPG)

> ./android/scripts/release-sdk.sh /tmp/repo/connectlane-android-sdk/releases

Pushed the generated com & org folders to git repo:
https://github.com/sunilkumarjena21/connectlane-android-sdk/raw/main/releases

Used in my test project to see how the custom SDK working.
But sorry to inform you.. I am still facing the same error as mentioned in below screenshot.
![error_on_my_app](https://user-images.githubusercontent.com/32553699/95242990-97e74a00-082d-11eb-8c38-edda1714c787.JPG)

**Comment by tmoldovan8x8** [comment]
Hi,
From what I can tell there seems to be two different issues here. For the one reported by @djorkaeffalexandre I have created this PR https://github.com/jitsi/jitsi-meet/pull/7859.
In what concerns @sunilkumarjena21, I would assume there is a problem with the dependencies in the sample app, I have tried your connect-lane-sdk and it was working fine.

**Comment by djorkaeffalexandre** [comment]
@tmoldovan8x8 thanks! It's awesome.
Can you help me with a specific question also related to the SDK?
I'm building the SDK from source (latest commit from master) and publishing it here https://github.com/RocketChat/jitsi-maven-repository.
Then using this like
```gradle
repositories
  maven {
      url "https://github.com/RocketChat/jitsi-maven-repository/raw/master/releases"
  }

  ...
}
```
but when I use this, my app bundle looks like +10mb than when I use `https://github.com/jitsi/jitsi-maven-repository/raw/master/releases`, is there any step of building I don't know?
Thanks in advance.

**Comment by tmoldovan8x8** [comment]
@djorkaeffalexandre you are not missing any steps, so it should work the same. Could you maybe unzip the 2 apks to compare them and see where the difference is coming from?

**Comment by djorkaeffalexandre** [comment]
For sure @tmoldovan8x8, I'll try and let you know, thanks for your help 😃

**Comment by saghul** [comment]
Closing this now that the release process is fixed. Feel free to continue the discussion, however.

**Comment by sunilkumarjena21** [comment]
> Hi,
> In what concerns @sunilkumarjena21, I would assume there is a problem with the dependencies in the sample app, I have tried your connect-lane-sdk and it was working fine.
 
Hi @tmoldovan8x8 ,
Thanks for your response & happy to know my SDK was working on your side.
But I am still facing issues when I used this SDK in different app.

I am using the below gradle (Module:app)files.

```
  // Jitsi Meet
    implementation('org.connect.react:connect-lane-sdk:2.11.0')
```
Used reference in build.gradle
```
        maven {
            url "https://github.com/sunilkumarjena21/connectlane-android-sdk/raw/main/releases"
        }
```

Is there something i am missing here?

Thanks for your great knowledge & support on this community. 👍

**Comment by djorkaeffalexandre** [comment]
Thanks for the great tip @tmoldovan8x8, looks like my own sdk is generating a `libjsc.so` that is increasing the bundle size, any tips about how I can prevent this?
I'll try to delete the `webkit/android` folder.
Thanks anyway.
Contact Jitsi team is always a good experience for me. 🤗

**Comment by sunilkumarjena21** [comment]
> > Hi,
> > In what concerns @sunilkumarjena21, I would assume there is a problem with the dependencies in the sample app, I have tried your connect-lane-sdk and it was working fine.
> 
> Hi @tmoldovan8x8 ,
> Thanks for your response & happy to know my SDK was working on your side.
> But I am facing one of the strange issues when I used this SDK in one of the other sample app. Even if i have not added any google play dependency in build.gradle.
> 
> `Could not find com.google.android.gms:play-services-auth:17.0. Required by: project :app > com.facebook.react:react-native-google-signin:3.0.1-connect-5570954 Search in build.gradle files`
> 
> ![play-img](https://user-images.githubusercontent.com/32553699/95444365-582e7880-097b-11eb-81a9-622ae88a0d20.JPG)
> 
> Is there something i am missing here?
> 
> Thanks for your great knowledge & support on this community. 👍

Hi @tmoldovan8x8 @djorkaeffalexandre @saghul ,

Your inputs will be greatly appreciated. 👍

**Comment by saghul** [comment]
> `libjsc.so` that is increasing the bundle size, any tips about how I can prevent this?
> I'll try to delete the `webkit/android` folder.

Note that on master we reverted back to JSC instead of Hermes, so you actually need it.

**Comment by djorkaeffalexandre** [comment]
Nice to know @saghul! I've changed ReactInstaceManager to use Hermes as I did before, it has some known issue?

**Comment by djorkaeffalexandre** [comment]
@sunilkumarjena21 is your app a React Native app?

**Comment by saghul** [comment]
> it has some known issue?

It's not faster than JSC on startup (at least for Jitsi Meet) and it's a pain to publish the SDK dependency because the package is not a maven repo.

More importantly, if it's not the default in react-native itself it doesn't give us enough confidence to go forward with it TBH.

**Comment by sunilkumarjena21** [comment]
> @sunilkumarjena21 is your app a React Native app?

No its an Android Native app. The SDK is used in Android Native app

**Comment by djorkaeffalexandre** [comment]
understandable @saghul, thanks for your time :)

**Comment by sunilkumarjena21** [comment]
> Hi @tmoldovan8x8 @djorkaeffalexandre @saghul ,
Hi @tmoldovan8x8 @djorkaeffalexandre @saghul
Your input is required to solve this issue.
Jitsi team is always prvoded their helping hand.

**Comment by sunilkumarjena21** [comment]
Thanks @djorkaeffalexandre @tmoldovan8x8 @saghul 
 ..Now its working for me..

Just needed to add the below line.

` implementation 'com.google.android.gms:play-services-auth:18.1.0'`
