### ISSUE TITLE
BUG: Latest Stable Release not working for Android App: "Gradle Project Sync Failed"

### ISSUE THREAD

**Issue by fremzy** [jitsi/jitsi-meet#7841]
### Description:

Latest release [jitsi-meet-stable-jitsi-meet_5076] not working for the Android app. Can't start metro and project fails on load with error "GRadle Project Sync Failed"

### Steps to reproduce:

Load 'Android' folder in Android Studio. 
### Expected behavior:

Project should load, build and run without errors

### Actual behavior:

Upon opening the 'Android' directory in Android Studio, Gradle sync immediately fails with error "/node_modules/react-native-background-timer/package.json (No such file or directory)"

### Server information:

- Jitsi Meet version: 2.0.5076
- Operating System: Mac OSX 10.13.6 (17G14033)

### Client information:

NA
![Screen Shot 2020-10-02 at 10 44 11 PM](https://user-images.githubusercontent.com/63688942/94981810-407e6c80-0503-11eb-9ea1-fa204ebc5f88.png)
![Screen Shot 2020-10-02 at 10 45 03 PM](https://user-images.githubusercontent.com/63688942/94981811-407e6c80-0503-11eb-992e-f925a0410fe5.png)

**Comment by saghul** [comment]
Might be related to https://github.com/jitsi/jitsi-meet/issues/7834

**Comment by saghul** [comment]
Should be fixed in master now.
