### ISSUE TITLE
Can't see or hear any device outside my LAN using my Debian 10 server

### ISSUE THREAD

**Issue by danmanrana** [jitsi/jitsi-meet#7842]
I can see everyones' names but that's it. I followed the Debian install instructions and have a domain with a TLS cert and all, including forwarding the needed ports on my router.

### Server information:

- Jitsi Meet version: 2.0.5076-1
- Operating System: Debian 10 Stable

### Client information:

- Browser / app version: Latest Ubuntu Desktop 20.04 Firefox, Chromium and Electron 2.4.1 and Android app
- Operating System: Android 10 and Ubuntu Desktop 20.04

**Comment by toby63** [comment]
Still it sounds like a port problem :thinking: 

Double check that for both router and (potencial) firewalls on your system.
Also check whether some ports are already used by some other program and whether the correct computer is applied to the port in the router options (I often have problems with my router assigning ports to different computers, so I have to adjust that very often).
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#setup-and-configure-your-firewall

Most important for your case is `10000 UDP - for general network video/audio communications`.

**Comment by toby63** [comment]
You can also check the **Advanced configuration** `below` this section: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#generate-a-lets-encrypt-certificate-optional-recommended

**Comment by pgenderson** [comment]
All five ports are forwarded fine and allowed on UFW (and my LAN IP still matches that of my router's port-forwarding (called virtual server) rules). Haven't changed any other system firewall settings. The advanced section mentions 3-way calls, but 2-way with at least one out of LAN device doesn't work either. A Redditor gave [this](https://np.reddit.com/r/jitsi/comments/j3u7uk/anyone_having_issues_running_their_server_on/g7iguwx/) advice but I wanted to ask on here before trusting a random dude on there, especially with opening extra ports.

**Comment by toby63** [comment]
:thinking: This one might apply: https://github.com/jitsi/handbook/issues/50

**Comment by pgenderson** [comment]
I noticed that the default listening-port value in my /etc/turnserver.conf is 3478 and tls-listening-port 5349, and I changed them to 4443 and 443, respectively, and rebooted but no difference. Not sure whether to change both values to 4446 or only the tls one.

**Comment by toby63** [comment]
:thinking: I found a tutorial (in german but you can see the configuration): https://blog.wydler.eu/2020/04/04/eigener-turn-server-fuer-jitsi-meet-bereitstellen/.
The author applied port `443` to both, but it seems they changed some files as well:
/etc/jitsi/meet/$FqdnJitsiServer-config.js
/etc/prosody/conf.avail/$FqdnJitsiServer.cfg.lua

**Comment by pgenderson** [comment]
I'll try. Do I have to reload the turn server e.g. `sudo systemctl reload coturn` after every change or is rebooting fine?

**Comment by toby63** [comment]
> Update: making both 443 didn't work either. Will continue this tomorrow.

:thinking: This of course should be investigated, but for now you could try to use Docker instead:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
This is updated more often (last release yesterday) and should include all the correct configuration etc.
This way we might also be able to rule out a configuration error on your side (no offence) :smiley:.

**Comment by pgenderson** [comment]
After running `docker-compose up -d`, I get Error: Couldn't connect to Docker daemon at http+docker://localhost - is it running? Never used Docker before.

**Comment by toby63** [comment]
@pgenderson
> chown: invalid user: ‘turnserver’

 :thinking: Strange error.
Have you followed the instructions correctly? 
If the error persists, open a new issue here: https://github.com/jitsi/docker-jitsi-meet/issues
Maybe the instructions are also outdated, but I guess someone would have reported that :thinking:.

By the way, the situation is not ideal:
The docker container still uses Debian strech: https://github.com/jitsi/docker-jitsi-meet/issues/219
It also seems there are more problems below, like outdated Java compatibility, outdated encryption library etc.
So decide for yourself.

Sry for not having better news, but I guess the team is working as fast as they can.
I assume in some time we might see a newer version.

**Comment by toby63** [comment]
:thinking: Also interesting: https://github.com/jitsi/jitsi-meet/issues/6672
https://github.com/jitsi/jitsi-meet/issues/5589
https://github.com/jitsi/jibri/pull/270/files

**Comment by pgenderson** [comment]
Reinstalled Ubuntu 20.04 since it worked in there before, but same problem. Probably doing something very obviously wrong but I have no idea what it could be. The solutions being all these extra ports to open is interesting, but why do different people have success with different ports?

**Comment by pgenderson** [comment]
https://community.jitsi.org/t/nginx-coturn-port-443/27820/19 saved my butt. Can't have Nginx installed before jitsi-meet. Need to let Jitsi Meet install it itself.

**Comment by toby63** [comment]
> https://community.jitsi.org/t/nginx-coturn-port-443/27820/19 saved my butt. Can't have Nginx installed before jitsi-meet. Need to let Jitsi Meet install it itself.

So now everything is working?
Also only with the usual ports?

In that case, we might have to change the instructions in the handbook.

**Comment by pgenderson** [comment]
Yup! Should get confirmation from others though first, but it definitely seems like it.
