### ISSUE TITLE
Put back SHOW_JITSI_WATERMARK in interfaceConfigWhitelist.js?

### ISSUE THREAD

**Issue by VirginieGarcin** [jitsi/jitsi-meet#7843]
SHOW_JITSI_WATERMARK was removed from the overridable parameters by commit 742f4f10.

Previously when using our own instance it was possible to remove the jitsi.org logo. Now it's not possible anymore to do it in a clean way. 

We were using this parameter, can it be put back please?

**Comment by fschulze** [comment]
This was done via https://github.com/jitsi/jitsi-meet/pull/7025 with no explanation, was there a policy change regarding the logo?

**Comment by damencho** [comment]
Yes, this was done to accommodate the requirements https://jitsi.org/meet-jit-si-terms-of-service/
On a self-hosted environment, you can always change this in the interface config.

**Comment by fschulze** [comment]
@damencho you mean interface_config.js from meet itself? Then one runs into this: https://github.com/jitsi/jitsi-meet/issues/6279

**Comment by damencho** [comment]
You can always create a custom location in nginx config like the one for config.js and store your interface config in /etc/ folder.

**Comment by holema** [comment]
Hello @damencho,

we use our own jitsi-meet deployment and want to change the DEFAULT_LOGO_URL paramter via iFrame. But this Parameter is not allowed to be overwritten by Whitelist.  Is there a possibility to edit the Whitelist in our own deployment, or do we have to rebuild the GUI after changing the whitelist.
