### ISSUE TITLE
Error serving robots.txt to curl, crawlers, and other non-browser clients

### ISSUE THREAD

**Issue by guruatwork** [jitsi/jitsi-meet#7844]
### Description:
Jitsi-meet server cannot serve https://server.domain.tld/robots.txt to curl clients.

The requests from Microsoft "curl", Powershell "Invoke-Webrequest", and other non-browser clients do not include an ALPN identifier recognized by the config so the request is sent to the turn server instead of the web server.

### Steps to reproduce:
On a clean ubuntu 18.04 or 20.04 server installation, download / install jitsi-meet per available instructions.
Select local option for later activation of LetsEncrypt.
Use the included script to set up certbot and acquire certs for this server.
( sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh )

1. Test your installation browsing https://server.domain.tld/ and fix any issues.
2. from a Win 10 command prompt, run "curl https://server.domain.tld/robots.txt"
you will receive and error like "curl: (52) Empty reply from server"

### Expected behavior:

The default robots.txt should be displayed (or at least a proper HTTP response such as 404-Not Found)

### Actual behavior:

The request is directed to the turn server instead of the web server.
An error is logged in nginx/error.log with no trace in nginx/access.log

### Server information:

- Jitsi Meet version: jitsi-meet/stable 2.0.5076-1
- Operating System: Ubuntu 18.04.5 LTS 

### Client information:

- Browser / app version: Win 10 curl
- Operating System:  Win 10 2004

### Additional information:

In file:  /usr/share/jitsi-meet-turnserver/jitsi-meet.conf 
the default routing for traffic is to the turn server. However, the request from many crawlers and non-browser apps is not recognized as http so the request is incorrectly routed to the turn server.

Please change this default config so unrecognized traffic goes to the web server for proper handling and logging. Only send valid XMPP to the turn server. Here is the section from the current default installation.
What is the proper alpn detection for the turn server traffic? Add that and then make the default "web".
```
    # since 1.13.10
    map $ssl_preread_alpn_protocols $upstream {
        ~\bh2\b          web;
        ~\bhttp/1\.      web;
        default          turn;
    }

```

**Comment by damencho** [comment]
This is no longer rhe case in latest versions from unstable repo, alpn multiplexing is no longer used. You can migrate existing deployments using this guide https://jitsi.github.io/handbook/docs/devops-guide/faq#how-to-migrate-away-from-multiplexing-and-enable-bridge-websockets
