### ISSUE TITLE
Jitsi Meet APK size is larger when using react-native 0.61.5

### ISSUE THREAD

**Issue by aviadavi** [jitsi/jitsi-meet#7845]
### Description:

Looks like APK size of Jitsi Meet is much larger than it used to be a moth ago.

Of course i'm using :

`def enableProguardInReleaseBuilds = true`

See differences.  release build APK (20.5) vs store APK (20.4.2). 
![image](https://user-images.githubusercontent.com/11704060/95025426-5cfcdf00-0692-11eb-94dd-0beded42b9a1.png)

From what I read that can be due to react native engine ?

### Expected behavior:

APK size should be around 30MB in total

### Actual behavior:

APK size is almost 88MB 

### Server information:

- Jitsi Meet version: Lastest
- Operating System: Mac

### Client information:

- Browser / app version: Lastest
- Operating System: Android

Thanks,
Aviad

**Comment by djorkaeffalexandre** [comment]
Hey guys, I have a related problem (maybe).
I'm building the SDK from source (latest commit from master) and publishing it here https://github.com/RocketChat/jitsi-maven-repository.
Then using this like
```gradle
repositories
  maven {
      url "https://github.com/RocketChat/jitsi-maven-repository/raw/master/releases"
  }

  ...
}
```
but when I use this, my app bundle looks like +10mb than when I use `https://github.com/jitsi/jitsi-maven-repository/raw/master/releases`, is there any step of building I don't know?
Thanks in advance.

**Comment by jwmh** [comment]
@djorkaeffalexandre:
Please create a new, separate issue,
and then make a link/mention in it,  to this issue (#7845).
Helps make tracking and troubleshooting easier.

**Comment by saghul** [comment]
Sorry, I forgot about this one. We switched back to JSC, so the size is expected. Note there are 4 architectures included in the SDK.

In order to eliminate the unneeded Hermes artifacts you can use this: https://github.com/jitsi/jitsi-meet/blob/be3bc754036d4cb29ce009ae065a1c587d153c02/android/app/build.gradle#L19-L21

**Comment by moriel5** [comment]
In my case, even 40MB is over the top in terms of storage space, however ~15MB is still acceptable.

I can get down to that sizespan by deleting libraries that are meant for other architectures, however I can only do that with the Play Store APK (downloaded via  Aurora Store), not the one from F-Droid (which is important, as I do not run Google's Play Services on my devices).

Is there a reason why I cannot modify the FOSS APK thus, however not the one implementing Google's blobs?

**Comment by saghul** [comment]
Not sure I understand. If you build your own SDK and delete the architectures you don't care about the distribution method should not matter.

**Comment by moriel5** [comment]
Ideally, that would be the case.

However, I have no idea how to compile Android packages, which is why I am reduced to modifying the APK itself.

As such, I am asking why is it possible to modify the Play Store APK, but not the F-Droid APK.

**Comment by saghul** [comment]
Not sure. We don't compile the F-Droid package, but it should be no different.

Why are you not able to modify it?

**Comment by moriel5** [comment]
This is just speculation, however it seems that there is a build option which prevents modification of the compiled APK contents (not just breaks the signature), which while it can be circumvented with some software (such as File Roller on desktop Linux), results in a broken APK that fails to install even with a new signature (like the testing signature).

I have faced this before when attempting to slim down file sizes for APKs that I use, but pretty rarely, and usually (from the few times I have encountered this) with software provided outside the Play Store and F-Droid, but directly from publishers.

**Comment by saghul** [comment]
I think your best course of action is to build the APK yourself.

It seems to me like it would even be simpler than what you are doing already.

Take a look at https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet#android

You can build the app easily with Android Studio once you have the npm dependencies installed.

**Comment by moriel5** [comment]
@saghul Thanks, I guess I'll have to do so in the end (I keep getting stuck after seeing up Android Studio, without understanding what I am doing being that point).

And it is usually much simpler to mod the APK directly in this case, since all I am doing is deleting files from the archive, and then resigning the APK.
