### ISSUE TITLE
Suggestion: When chat is open, allow the main image to fit between the margins

### ISSUE THREAD

**Issue by PhilipOakley** [jitsi/jitsi-meet#7846]
(originally posted as https://github.com/jitsi/handbook/issues/91)

**Is your feature request related to a problem you are facing?**

I used Jitsi on a conference call over the two days recently. Excellent.

One _relatively minor issue_ was that with the chat active, it will hide (the left hand) part of the main screen area, so one can't see part of the presentations, or some of the participants if in gallery view.

The issue sounds similar to notifications covering the chat (https://github.com/jitsi/jitsi-meet/issues/7695 which says it a known issue but without a back reference to the original issue). I.e. a hierarchy of obscuration...

**Describe the solution you'd like**

It would be nice if their was a 'shrink to fit', or similar, so that the chat can be held open as well as seeing the full conference image, likewise for anything showing on the right hand margin. 

**Describe alternatives you've considered**
The chat bar could be detached, to be free-floated, if that was easier. (thus floated outside the main Jitsi window, or even onto a second monitor)

**Comment by damencho** [comment]
This is already the case on meet.jit.si and the latest stable release, chat moves conference content on the right while it stays open.

**Comment by PhilipOakley** [comment]
Thanks, I presume that is on the server side - it was a hosted meeting, rather than being through Jit.si itself. I was on Firefox.
