### ISSUE TITLE
Deafen button (feature request)

### ISSUE THREAD

**Issue by edemaine** [jitsi/jitsi-meet#7855]
**Motivation:**
Many audio/video chat tools (e.g. Discord and Mumble) have a "deafen" feature that silences the incoming audio.  This is useful when people are in a video meeting, but want to take a break and do something else (e.g. take another call) but still see the others in the meeting and not interrupt the flow of the meeting (by leaving and joining).

**Describe the solution you'd like:**
* Add a deafen button (like mute button, but controlling incoming audio instead of outgoing audio), presumably behind an interface flag that enables/disables it. Up to you what the default should be.
* I'm imagining that this would just mute the incoming audio, but it could also stop the audio stream from being sent. This would address #7187 in a nice way, but is also probably beyond what I'd know how to implement.
* The `startSilent` [config.js](https://github.com/jitsi/jitsi-meet/blob/master/config.js) option would now set the initial state of deafen mode. If the deafen button is disabled, changing the state would still require reload.

**Related issues:**
Related to #7187, but there `startSilent` was enough, because a deaf user presumably doesn't need to be able to toggle this feature on/off (except that it would make for a GUI, instead of having to manually change the URL).

**Plan:**
I imagine this wouldn't be hard to implement, and am happy to take a stab at implementing a PR, assuming folks aren't against adding this feature.  I could also use suggestions on what this might best look like in the GUI (where to place the new button).

**Comment by Echolon** [comment]
Can you explain how mute of the browser tab or mute of the system is not sufficient?

**Comment by edemaine** [comment]
You're right that deafen is essentially equivalent to muting the tab. I forgot that (some or all?) browsers have that feature. The only difference in what I wrote is a button in the Jitsi interface vs right-clicking the tab.

(Muting the system wouldn't be the same: it would prevent you from doing other sound-inducing operations like take another call.)

But this reminds me of another key feature of deafen functionality, present in the other systems I mentioned: there is a visual indicator of which users are deafened, in the same way there is a visual indicator of which users are muted. This makes it clear who can hear the current speaker. I assume it would not be difficult to add this kind of metadata to the stream.

**Comment by G4BB3R** [comment]
I am using iframe jitsi API and I would like to deafen the iframe, how can I do it?

**Comment by deliciouslytyped** [comment]
@Echolon
This is also related to these two issues at the least:
#7205 #6399 

The browser tab and system mute aren't sufficient because the android app is not a browser, and android's volume settings are crippled / there is no mute functionality.

**Comment by JoshuaDietz** [comment]
I need that feature on iOS too. Often I participate in a meeting from my PC but want to share my iPad screen too. So I also join the meeting with my iPad and I then have to plug in some headphones into the iPad because else I will hear my own voice out of the iPad and also there's an echo for everyone else when my PC mic picks up the iPad audio again

**Comment by edemaine** [comment]
The issue remains unresolved and I think desirable.

**Comment by saghul** [comment]
I am going to close this not to misled anyone here.

2 years have passed and we still have no plans to implement this feature so keeping it open is just confusing.

We might end up revisiting the topic and implementing it, we've had that happen before, but this is where things stand right now.

**Comment by hartman** [comment]
Ok, i just spent several hours in a workshop using jitsi, and i really do miss this feature which i'm used to from Discord. It's just difficult to focus for a moment on some task if others are talking or even if they can just interrupt. Leaving the entire session takes you out of the social experience which also wasn't really desirable.

The browser mute just isn't easy enough, as it doesn't have a hotkey. I also like to keep my music running, so muting the entire PC also not really an option. I figured i'd leave that feedback in case anyone ever wants to revisit this. thx !
