### ISSUE TITLE
Android: call ends when theme is switched (on battery low level)

### ISSUE THREAD

**Issue by dakur** [jitsi/jitsi-meet#7858]
### Description:

When I'm joined in a room on smartphone with Android and the OS switches from light theme to dark theme automatically due to low battery, the call is ended suddenly. The same when plugged-in phone to charger and the theme is switched back from dark to light theme.

### Steps to reproduce:

1. Join a room in Android app.
2. Wait in the room until you have low battery (15 %) and theme is switched automatically (make sure you have enabled automatic theme switching).

### Expected behavior:

Stay in the room.

### Actual behavior:

Room is left.

### Server information:

- Jitsi Meet version: -
- Operating System: -

### Client information:

- Browser / app version: 20.4.2 build 5465103
- Operating System: Android 10

**Comment by dakur** [comment]
This is still an issue.

**Comment by dakur** [comment]
This bug is still present.

**Comment by saghul** [comment]
Please share adb logs when this happens.
