### ISSUE TITLE
Support for Ubuntu Touch Browser?

### ISSUE THREAD

**Issue by dan-elevate** [jitsi/jitsi-meet#786]
Hello!
I really appreciate the Jitsi Meet Software and since I also use Linux on my Smartphone, namely Ubuntu Touch, I was wondering if there is any chance to support the browser of that operating system.

This is the one: https://launchpad.net/ubuntu/+source/webbrowser-app

Other WEBRTC tools seem to work (example: https://opentokrtc.com/ ), but not Jitsi Meet, which is my favorite.

Any chance of fixing this issue?
Thanks for all your work! Much appreciated!
Dan

**Comment by Dreamsorcerer** [comment]
Duplicate of #680
