### ISSUE TITLE
disableInviteFunctions: true doesn't seams to work

### ISSUE THREAD

**Issue by VirginieGarcin** [jitsi/jitsi-meet#7860]
Hello,

I'm trying to disable any option to invite more people.
(I already removed the big button with `HIDE_INVITE_MORE_HEADER: true` in `interfaceConfigOverwrite`.)

Now I'm trying to remove the button bottom right:  ![image](https://user-images.githubusercontent.com/27735708/95320007-e0dce400-08a9-11eb-92e9-960d96de8a44.png)

When calling API I have: 

```
configOverwrite: {
		disableInviteFunctions: true,
		...
	},
```
According to the comments in code:  
```
// Disables all invite functions from the app (share, invite, dial out...etc)
// disableInviteFunctions: true,
```
I can see in the log that the parameter is passed:
` Extending config with: {"disableInviteFunctions":true,"startWithAudioMuted":false,"startWithVideoMuted":false}`

But it doesn't seam to work, I still get this button.

Thanks for your help.

**Comment by Echolon** [comment]
Hi, for questions please use the community portal!
