### ISSUE TITLE
Kick out doesn't work anymore...

### ISSUE THREAD

**Issue by dr-falsch** [jitsi/jitsi-meet#7871]
Hello,

am I the only one for whom the kick out doesn't work anymore for jitsi `jitsi-meet/stable,now 2.0.5076-1`?

Neither the moderator nor the kicked out person gets a message. For the kicked out participant Jitsi just freezes and the console is full of errors:

![Screenshot 2020-10-09 at 10 30 07](https://user-images.githubusercontent.com/7977829/95572321-101a5f00-0a2a-11eb-86ff-fd44d8143626.png)

The problem appears on our own Jitsi Server installation. On meet.jit.si it is still working.

Any ideas? Because the errors in the console don't help me at all unfortunately.

Thanks,

  alex

**Comment by Echolon** [comment]
For support on this pls go to the community portal.
