### ISSUE TITLE
App crashing on iOS 13+ version when included in the project

### ISSUE THREAD

**Issue by nadesh-git** [jitsi/jitsi-meet#7873]
### Description:

We are using the jitsi sdk on iOS native app project. The app gets crashed on iOS 13+ version but working fine on lower version( 12+ ). Using xcode 12 for building and latest SDK version [2.10.2](https://github.com/jitsi/jitsi-meet-ios-sdk-releases/releases/tag/2.10.2).
The weird thing is your [sample SDK](https://github.com/jitsi/jitsi-meet-sdk-samples) working fine on both iOS 12+ and 13+ version.

Our project have twilio SDK integrated as well. So we tried to add the twilio on your sample, which works fine.

The crash error is: NSInvalidArgumentException nil object[3]

When tried with backtrace, it shows crash at **WebRTCModule.queue**

**Comment by saghul** [comment]
Without more information on the crash there is not much we can do to help you.

**Comment by nadesh-git** [comment]
Hi @saghul ,

Thanks for the response. At last, fixed the issue after 3 days of headache by changing the appdelegate on our project like on your sample on this line

`func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        guard let launchOptions = launchOptions else { return false }`

Crash issue has gone.
