### ISSUE TITLE
SHA problem with callstats.io

### ISSUE THREAD

**Issue by magatz** [jitsi/jitsi-meet#788]
Hi, 
I've seen that you have upgraded SHA to 2.01.breaking the functionality with callstats.io.
I've talked to callstats guys, and they sad:
"Currently, we have not tested with SHA.js 2.01 and it is not in our short term roadmap. The recommended version is 1.5."

My question is: is i really necessary to upgrade to 2.0.1?
Can i recompile jitsi-meet bringing back to 1.5?
thanks

**Comment by bgrozev** [comment]
Where do you see version 2.01? The version we have as an npm dependency is 1.5 specifically because of callstats: https://github.com/jitsi/jitsi-meet/blob/master/package.json#L29

**Comment by magatz** [comment]
in package.json there is a note about version 2.0.1 and  in jitsi-meet/debian/missing-source/libs/strophe/sha1.js the note say version 2.1a

I've tried searching this file since i could not make working the callstats.io integration following the rules here:
https://www.callstats.io/integrate-jitsi/

BTW: what's the meaning of this message:
2016-08-15 14:08:38,597 INFO  (CallStats.java:114) - config file path is /etc/jitsi/videobridge/callstats-java-sdk.properties
2016-08-15 14:08:38,599 ERROR (CallStats.java:138) - intialize: Arguments cannot be null

found in /var/log/jitsi/cs.log

?
thanks

**Comment by bgrozev** [comment]
> in package.json there is a note about version 2.0.1 and in jitsi-meet/debian/missing-source/libs/strophe/sha1.js the note say version 2.1a

I don't think "2.1a" refers to the jssha version. jssha 2.1 was only released recently and the file was last modified two years ago. As far as I can see debian/missing-source isn't used at all anymore. @damencho do you think it is safe to remove it?

https://github.com/Caligatio/jsSHA/releases/tag/v2.1.0

**Comment by damencho** [comment]
Oh yeah definitely, remove it. This was added while trying to prepare jitsi-meet for official debian repo, but the project has changed a lot since then and if we start doing it again, we will start from scratch.

**Comment by vr000m** [comment]
I believe we have now removed the dependency of jssha, @karthikbr82 could you confirm?
