### ISSUE TITLE
Mute button not working randomly 

### ISSUE THREAD

**Issue by vinoykr** [jitsi/jitsi-meet#7881]
### Description:

There is a major Bug we are seeing in last few weeks on the latest stable release. For some users when they go on mute, we are still able to hear them. No matter how many times they toggle, we can hear them. Interestingly the UI updates properly on both sides with the icon changing from unmute/mute. But the we are able to hear in both the cases. This is seen once in a while (once every 10 calls org so) and not consistently reproduced seen. It goes away on reloading the page and appears randomly after few calls.

### Steps to reproduce:

1. Join a meeting
2. Click on mute

### Expected behavior:

On clicking mute, other should not be able to hear my voice. 

### Actual behavior:

On clicking mute, other are able to hear my voice but the UI is updated properly on both sides on toggle.

### Server information:

- Jitsi Meet version: 4289
- Operating System: Ubuntu 

### Client information:

- Browser / app version: Chrome Version 85
- Operating System: Windows 10

### Additional information:

This is happening randomly. Initially we thought it was a temporary glitch with poor internet connection. But its happening repeatedly at random meeting & users. Was not able to collect the logs since it was happening to others and not me.

**Comment by vinoykr** [comment]
This is a major security and privacy issue

**Comment by ahmetkarakaya** [comment]
Have you seen this issue at last version (5076)? And do you have a scenario that you can reproduce the issue when ever you want?
Prejoin screen may cause some sort of problem.

**Comment by Echolon** [comment]
@vinoykr please ensure to reproduce this with the latest version first.

Anyway, thank you for your report!

**Comment by vinoykr** [comment]
It happens with the latest version as well. I had raised this in the Jitsi forum and there is some good discussion happening there. Its seems something related to prejoin screen.
https://community.jitsi.org/t/major-bug-mute-not-working-for-some-users/81095/18

**Comment by vinoykr** [comment]
> Have you seen this issue at last version (5076)? And do you have a scenario that you can reproduce the issue when ever you want?
> Prejoin screen may cause some sort of problem.

I tried hard to reproduce it but its completely random and never happened with me and others are getting it.

**Comment by katiany** [comment]
I've been experiencing the same issue with the latest version as well. Haven't tried to disable prejoin yet

**Comment by damencho** [comment]
Anyone have a repro case to reproduce this regularly?

**Comment by vinoykr** [comment]
I tried several times to reproduce it but it never appeared. I am running jitsi within the company with around 2000 users and around 1000 actively using it daily. And almost every other day I get this complaint from someone facing it.

**Comment by CosmoMyzrailGorynych** [comment]
Here is a log from a chrome browser's console where we encountered this issue. It may or may not be helpful.
[Gp4KYnnJ.txt](https://github.com/jitsi/jitsi-meet/files/5639305/Gp4KYnnJ.txt)

**Comment by paweldomas** [comment]
I think this PR should fix it: https://github.com/jitsi/jitsi-meet/pull/8228

**Comment by 0xnor0** [comment]
Any news on this?

**Comment by damencho** [comment]
This had been fixed. And a new stable release with the fix will be out this week.

**Comment by CosmoMyzrailGorynych** [comment]
So. Maybe close this issue already? :) @vinoykr
