### ISSUE TITLE
Poor Video Quality on Android Devices

### ISSUE THREAD

**Issue by sparmar-atheer** [jitsi/jitsi-meet#7882]
### Description:

We've been using Jitsi in our product. Recently we upgraded Jitsi SDK to latest versions and started seeing very poor video quality on android devices

### Steps to reproduce:

We observed that video quality on bunch of Android devices that we support degraded significantly. After upgrade, users never see 1280x720. Users end up seeing anywhere from 480 to 960. 

We kept all the variable same (Device, Network etc.). The only difference was the new Jitsi SDK version. 

### Expected behavior:

Users should see 1280x720 resolution. 

### Actual behavior:

Users end up seeing resolution anywhere from 480 to 960. Resolution constantly changes this range. 

### Server information:

Latest Jitsi 

### Client information:

Android 8.1 or above.

### Additional information:

We did review what changed recently and found that in latest version of Jitsi, we've made SoftwareEncoder default. In previous version of Jitsi this was not the case. This is the commit...

https://github.com/jitsi/jitsi-meet/commit/b0e7471a8323c3baf8350bf7a0154af378d3e71f#diff-c95c2d5f872615f920f1b5b255df6ed7

If we revert this change, everything works fine and we get proper 1280x720 resolution. 

Is there a plan to revisit this decision?

**Comment by saghul** [comment]
Interesting observation! We had to disable it because we got crashes by the thousands. In addition using the HW encoder means no simulcast either.

I don't know what we'll do in the future TBH, but given how buggy HW codecs have been so far I'd say having SW be the default is the way forward for now.

That said, I'd take a patch which makes this configurable at runtime. It would have to be set very early but that's ok.

**Comment by sparmar-atheer** [comment]
Thanks for the update @saghul. All the devices we support for our product seems to work fine with HW encoder. It will be great if we can make this configurable. I will work on the patch request next week.

**Comment by saghul** [comment]
Sounds good, cheers!

**Comment by hotagu** [comment]
In my case video quality was poor since after installation and I don't have the solution to fix it.
