### ISSUE TITLE
Building one-filed Jitsi-meet android native library

### ISSUE THREAD

**Issue by Topstar88** [jitsi/jitsi-meet#7883]
Hi, We put some customizations to react native source code and need to migrate it to our native android app. Currently we put our native code to /android and imported SDK in gradle so we were able to run successfully. But it seems that it is not professional. Is there any someone who built one-filed android library which can be imported in android native gradle ?
Thank you.

**Comment by saghul** [comment]
You can't build a one file library. You can release the SDK along with its dependencies to your own Maven server and add that to your gradle file. See android/scripts/release-sdk.sh
