### ISSUE TITLE
APP_NAME from configuration only applies post loading

### ISSUE THREAD

**Issue by JayVii** [jitsi/jitsi-meet#7897]
### Description:

When using a different name through `APP_NAME` in `interface_config.js`, the name change is applied as expected, however only AFTER the page has loaded completely. While loading, the tab shows the unaltered name "Jitsi Meet". This has the effect that, when sending conference invitations via messengers that provide an URL-preview, they show "Jitsi Meet" instead of the name set in the server's `APP_NAME`

### Steps to reproduce:

1. Change `APP_NAME` variable in configuration and reload jitsi meet instance
2. Open the webinterface in the webbrowser, taking notice of the sudden name change in the tabs-bar
3. sending the URL via something that generates an URL-preview (telegram, whatsapp, twitter, ...)

### Expected behavior:

The name set in `APP_NAME` is applied consistenly.

### Server information:

- Jitsi Meet version: [Docker-Version stable-4857](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4857)
- Operating System: Ubuntu 18.04

**Comment by damencho** [comment]
You can adjust your custom values for the loading and metadata of the page here: https://github.com/jitsi/jitsi-meet/blob/master/title.html
