### ISSUE TITLE
getReceiverVideoQualityLevel() in video-quality\functions.js returns incorrectly when Windows display scaling is != 100%

### ISSUE THREAD

**Issue by steve-sokolowski** [jitsi/jitsi-meet#7898]
A new feature was added to jitsi-meet sometime in September that broke my installation when I pulled the latest code.

In middleware.js, line 88, there is a new getReceiverVideoQualityLevel function call, which is defined in video-quality\functions.js, line 34.  This function iterates through the constants defined in config.js, minHeightForQualityLevel (line 277), selecting a higher video quality over and over until the video pane's height is smaller than the next higher resolution.

This function works as expected when the display scaling on a Windows monitor is set to 100%, using Chrome 86.0.4240.75.  To reproduce the bug, start a call with three or more participants, open the tile view, type "display settings" in the search box in Windows 10 64-bit to bring up the Display panel, then scroll down to "Scale and layout," choose "Change the size of text, apps, and other items" and set it to "150%."  

Wait for the size to change, then right-click on one of the remote participants' video panels and choose "inspect element."  The height of panel in the debugger will be smaller than it was before.  This change in turn causes thumbnailHeight in the code to change.  In my case, it declined from 874px to 438px.  jitsi-meet incorrectly uses a lower video resolution because it thinks the video panel is smaller, even though the size of the video and the number of pixels it occupies on the screen has not changed.  It is not necessary to live-change the display settings; the bug occurs whenever a browser is started on a display already using these settings.

When the display scaling is at 300%, this bug makes jitsi-meet unusable because the resolution will never increase above the "low" setting on most displays.

**Comment by jallamsetty1** [comment]
Thanks for reporting this issue and for identifying the root cause. We will see if we are able to take the device resolution (esp when when scaled lower or higher) into consideration when the request resolution is calculated for remote videos in tile view.

**Comment by jallamsetty1** [comment]
Leaving this bug open. It is low priority and we may not be able to get to it immediately but we will happy to accept PRs from the community.
