### ISSUE TITLE
Invalid chars in room name are not replaced when using external api

### ISSUE THREAD

**Issue by skolmer** [jitsi/jitsi-meet#7900]
### Description:

There is a [`_fixRoom` utility function](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/util/uri.js#L55) to replace characters in room names that are not supported by Jitsi Meet. This function should be used for generating URLs using the [`generateUrl` external API function](https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js#L132) to replace invalid chars in the `roomName` option.

### Steps to reproduce:

1. Generate a Jitsi Meet URL using the external api `generateURL`
2. Provide a roomName option with one of the invalid characters `:?#[]@!$&\'()*+,;=></`
3. Open generated URL in a Webbrowser

### Expected behavior:

Invalid characters should be replaced by the utility function

### Actual behavior:

Jitsi Meet shows a 404 page

### Server information:

- Jitsi Meet version: Current version at jitsi.riot.im

**Comment by saghul** [comment]
Sounds reasonable. Any chance you could provide a PR?

**Comment by skolmer** [comment]
Thanks for the quick response, I will submit a PR.
