### ISSUE TITLE
Setting Lobby required displayname (requireDisplayName) to false allows user to change name

### ISSUE THREAD

**Issue by c-prompt** [jitsi/jitsi-meet#7905]
I've reviewed #7197 and #7487 (supposed to be fixed with #7583). Perhaps #5707 still being open means this is not a bug... but it sure seems like it.

Upon upgrading to jitsi-meet_2.0.5142-1, I find the pre-join lobby pre-fills but allows you to change a pre-defined display name (i.e., "Please enter your name here"). Unless I'm misunderstanding how this works, if requireDisplayName = false, the user should be unable to enter a DisplayName. Otherwise, it's difficult to understand the purpose of this functionality.

In /etc/jitsi/meet/config.js, I have:

```
// Require users to always specify a display name.
requireDisplayName: false,
```

My meeting token includes:

```
// Create token payload as a JSON string
$payload = json_encode([
	"context" => [
		"user" => [
		"name" => $username
		]
	],
```

My script includes:

```
$script = "<script>
            var domain = 'meet.mydomain.com';
            var options = {
                roomName: '$room',
		userInfo: { 'displayName': '$username' },
                width: '100%',
                height: '100%',
		jwt:'" . $jwt . "',
            }
            var api = new JitsiMeetExternalAPI(domain, options);
        </script>";
```

As the DisplayName  is already defined and requireDisplayName is set to false, why is it the DisplayName can still be changed? The DisplayName is specifically sent to prevent users changing their names to appear as someone else. Is this intended?

**Comment by amsnek** [comment]
having an option to prevent users from setting/changing their display name would be very nice to have indeed! for example, with SAML authentication, the displayname is already passed and should not be changeable for the user.
