### ISSUE TITLE
One participant cannot hear the rest

### ISSUE THREAD

**Issue by SavedPlus** [jitsi/jitsi-meet#7907]
### Description:

The conference is attended by 5 participants. One participant is not heard. At the same time, hi see, that microphones of all participants are marked as off, although the microphones are on and the rest are successfully communicating with each other. 

The situation happened twice, with different participants on different days. The situation can be cured by switching from Chrome to Opera. 

What could be the problem?

**Comment by HasBert** [comment]
We have the same problem. 
Looks like this is problem with Chrome. The problem does **not** appear in Firefox and Safari, so we think this has something to do with Chrome. Maybe the [updates yesterday](https://chromereleases.googleblog.com/) are causing this problem?

**Comment by StanZhuravlev** [comment]
Yes, It's issue only for chrome. And I have a old version. Aproximete ~july 2020.

**Comment by joaofazolo** [comment]
It's happening in Chrome v86 and in Edge because it's based on Chromium.

**Comment by migonr77** [comment]
Hi, we have similar problem reported, where participant can't hear presenter (only one in room sending video/sharing presentation), but he can hear other attenders in room. How to debug this situations? Can this be caused by channelLastN parameter settings? 
Thank you!

**Comment by jallamsetty1** [comment]
Please update to the latest version of jitsi-meet for the fix, more info here - https://community.jitsi.org/t/help-stops-work-with-new-chrome-version-86-0-4240-75/80715.

**Comment by craigmaloney** [comment]
This is not the same issue as Chrome displaying that the microphone isn't operational. This is an instance where one or more of the participants can't be heard in a multi-person chat.

An example of this is here: https://peertube.social/videos/watch/e72dc7c9-d20f-4f0a-8a98-f2c22a9e1ad8

The recording participant (a machine on the same network as me) wasn't able to hear several of the questions, even though I was able to hear those questions.

**Comment by jallamsetty1** [comment]
> Hi, we have similar problem reported, where participant can't hear presenter (only one in room sending video/sharing presentation), but he can hear other attenders in room. How to debug this situations? Can this be caused by channelLastN parameter settings?
> Thank you!

channelLastN setting changes the max number of remote videos that the client can receive from the bridge, it does not have any effect on audio. Did this issue happen on meet.jit.si or your own deployment ?

**Comment by StanZhuravlev** [comment]
> Did this issue happen on meet.jit.si or your own deployment 

For my case - it's own installation.

**Comment by jallamsetty1** [comment]
> > Did this issue happen on meet.jit.si or your own deployment
> 
> For my case - it's own installation.

Are you running the latest JVB from the stable repo ? We recently fixed an issue in the bridge where users were reporting choppy audio and packet loss when viewing a screenshare.

**Comment by migonr77** [comment]
> > Hi, we have similar problem reported, where participant can't hear presenter (only one in room sending video/sharing presentation), but he can hear other attenders in room. How to debug this situations? Can this be caused by channelLastN parameter settings?
> > Thank you!
> 
> channelLastN setting changes the max number of remote videos that the client can receive from the bridge, it does not have any effect on audio. Did this issue happen on meet.jit.si or your own deployment ?

Hi, thank you. We are using our deployment and are using latest stable repo. of course. 

jitsi-meet-prosody/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet-turnserver/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet-web-config/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet-web/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet/stable,now 2.0.5142-1 all [installed]
jitsi-videobridge2/stable,now 2.1-376-g9f12bfe2-1 all [installed,automatic]

**Comment by StanZhuravlev** [comment]
Today I have similar problem on Opera, version 72.0.3815.186

**Comment by StanZhuravlev** [comment]
Is issue not decission? We must use a phone application, but want use browser meets :(

**Comment by migonr77** [comment]
Hi, today we had experienced this in 26 person room, we are starting all rooms with mic/cam muted, presenter asked all attendees to enable their cams and after that there was report to stop hearing  presenter, but affected person can hear all other people in room but presenter.  Leaving the room and joining it again resolved this.

**Comment by jallamsetty1** [comment]
> Hi, today we had experienced this in 26 person room, we are starting all rooms with mic/cam muted, presenter asked all attendees to enable their cams and after that there was report to stop hearing presenter, but affected person can hear all other people in room but presenter. Leaving the room and joining it again resolved this.

When did the issue start happening ? Was the person affected able to hear the presenter in the beginning of the call but then stopped hearing him/her after all the videos were turned on ?

**Comment by migonr77** [comment]
hi Jalla , issue appears after all participants enabled their cameras (almost simultaneously) on teachers advise, he wanted to see his students. Yes, everything was OK on meeting until that camera check. I'm sorry that I cant reproduce this in exact way but it happens sometimes. Yesterday we had peak of 1640 simultaneous participants in jitsi in 108 rooms and this was reported only once. But I've this reports 3-4 time the week so I think it is real problem somewhere.

Thank you for your interest!
