### ISSUE TITLE
Camera doesn´t work

### ISSUE THREAD

**Issue by mukova** [jitsi/jitsi-meet#7910]
Hi, my camera is turn on, but still doesn´t work during meeting. For 5 seconds is go well, but after short time (5 seconds) is turf out and doesnot work. There is text: " Nelze přistupovat ke kameře." Can you help me?

**Comment by saghul** [comment]
Can you please open the browser's JavaScript console and paste the logs you see there?

**Comment by Echolon** [comment]
#5425
