### ISSUE TITLE
Thumbnail scrollbar doesn't work on Firefox

### ISSUE THREAD

**Issue by Arzar** [jitsi/jitsi-meet#7915]
### Description:

The thumbnail scrollbar (Vertical Filmstrip) is stuck, doesn't respond to mouse wheel on Firefox. It's fine on Chrome and Edge.

### Steps to reproduce:

Start a meeting on meet.jit.si with enough people for the thumbnail to not fit the screen. (have to scroll down to see the rest)
Hover the thumbnail and scroll up or down with the mouse wheel

### Expected behavior:

The scrollbar scroll, following the mouse wheel

### Actual behavior:

The scrollbar is stuck

### Server information:

meet.jit.si

### Client information:

Firefox 81.0.2
Windows10

**Comment by TBG-FR** [comment]
Reproduced that issue today, using latest stable release (`2.0.5870`)

**Comment by saghul** [comment]
This should have been fixed already.
