### ISSUE TITLE
[iOS] Unsupported Architectures. The executable for JitsiMeet.framework contains unsupported architectures '[x86_64]'.

### ISSUE THREAD

**Issue by sbukharbay** [jitsi/jitsi-meet#7916]
### Description:
Can't upload my iOS App to TestFlight. Appstore connect and CI/CD gives error: "Unsupported Architectures. The executable for JitsiMeet.framework contains unsupported architectures '[x86_64]'." and ERROR ITMS-90087: "Unsupported Architectures. The executable for WebRTC.framework contains unsupported architectures '[x86_64]'.". I builded SDK myself as written in documentation.

**Comment by softwarebouwer** [comment]
I run the script below after the "Embed Frameworks" phase to remove unsupported architectures.

`echo "Strip unnecessary archs from Embedded Frameworks"
echo "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
cd "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
for file in $(find . -type f -perm +111);
do
    if ! [[ "$(file "$file")" == *"dynamically linked shared library"* ]];
    then
        continue
    fi
    # Get architectures for current file
    archs="$(lipo -info "${file}" | rev | cut -d ':' -f1 | rev)"
    # Strip any archs from frameworks not valid for current app build
    for arch in $archs;
    do
        if ! [[ "${VALID_ARCHS}" == *"$arch"* ]];
        then
            echo "lipo -remove $arch -output $file $file"
            lipo -remove "$arch" -output "$file" "$file" || exit 1
        fi
    done
done
`

**Comment by saghul** [comment]
That's the right answer.

**Comment by sbukharbay** [comment]
> I run the script below after the "Embed Frameworks" phase to remove unsupported architectures.
> 
> ```
> echo "Strip unnecessary archs from Embedded Frameworks"
> echo "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
> 
> cd "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
> 
> for file in $(find . -type f -perm +111);
> do
>     if ! [[ "$(file "$file")" == *"dynamically linked shared library"* ]];
>     then
>         continue
>     fi
>     # Get architectures for current file
>     archs="$(lipo -info "${file}" | rev | cut -d ':' -f1 | rev)"
>     # Strip any archs from frameworks not valid for current app build
>     for arch in $archs;
>     do
>         if ! [[ "${VALID_ARCHS}" == *"$arch"* ]];
>         then
>             echo "lipo -remove $arch -output $file $file"
>             lipo -remove "$arch" -output "$file" "$file" || exit 1
>         fi
>     done
> done
> ```

thanks you very much Raymond, this solution works.
