### ISSUE TITLE
Notification when E2EE is disabled

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7919]
It would be nice, if a notification appears if the E2EE is disabled because a participant doesn't support it.

**Comment by timomayer** [comment]
Will this be considered for one of the upcoming releases? I think this would be a very welcomed addition.

**Comment by saghul** [comment]
This is already implemented. A sound alert is played when E2EE is turned off, if it was on.

**Comment by timomayer** [comment]
thanks
@saghul any way to hook into this and get a javascript event/callback so we can do our own actions when e2ee is disabled?

**Comment by saghul** [comment]
Not at the moment, but adding them wouldn't be very complex. What are you trying to accomplish?
