### ISSUE TITLE
Video quality--for all devices--drops to low definition within one minute of an Android device joining a room.

### ISSUE THREAD

**Issue by coridonhenshaw** [jitsi/jitsi-meet#7929]
### Description:

When an Android or iOS-based mobile device joins a room, the video quality for all participants immediately drops to SD, then drops to LD within one minute.

### Steps to reproduce:

Using Jitsi Meet docker image 5142:
Connect two or more computers to a Jitsi Meet room.
Wait for the video streams between these devices to step up into HD video mode.
Connect one Android device to the room.
Video quality for all devices in the room will drop to SD.
Within one minute, video quality for all devices will drop to LD.
Disconnect the Android device from the room. Video quality for the remaining participants will not improve.

### Expected behavior:

Video quality between connected computers should remain unchanged after the Android device connects.
Video quality shown on mobile devices should reflect the capabilities of the device rather than being forced into low definition. LD is not an appropriate resolution for Android tablets connected via wifi.

### Actual behavior:

Video quality for all devices in the room will drop to the level of capability Jitsi Meet offers to the least capable device in the room.

### Server information:

- Jitsi Meet version: Docker image 5142.
- Operating System: openSUSE Leap 15.1

### Client information:

- Browser / app version: Android app version 20.4.2. Computers are using Firefox 81.
- Operating System: Android / Windows 10 / openSUSE Linux.

### Additional information:

None.

**Comment by lryjnks** [comment]
Can confirm, same problem for me.

**Comment by lryjnks** [comment]
After a few tests I noticed that the quality only deteriorates when two cell phones connect.

PC - PC = HD
PC - Mobile = SD
PC- Mobile - Mobile = LD for all devices

**Comment by etron770** [comment]
Is it the same low resolution  behaviour when using a Browser connection at the smartphone?

I just realized that the app is using only SD even when connectiong to a HD optimized Jtisi server.
The quality is low using the free jitsi server and the jitsi app. So it seemst that HD with smartphone is only possible at an own HD server and not using the app

**Comment by damencho** [comment]
Mobile app defaults to 360p, I think.

**Comment by etron770** [comment]
> Mobile app defaults to 360p, I think.

And there is no way to force HD?

**Comment by damencho** [comment]
Yeah you need to dig into git history to see what was the change, that is what I remember. Sorry, I'm not mobile expert ... But the title of this issue says that it drops ... Which is not the case with some restriction ...

**Comment by dsvk** [comment]
@etron770 this might be late but https://github.com/jitsi/jitsi-meet/issues/5808 for the 360p mobile hardcoding discussion. Seems it's basically the current brute-force solution for mobile apps not respecting server video constraints properly.

**Comment by etron770** [comment]
Is disabled the choice between app and browser at the login screen. Now I will send the link to the participants and they are using the browser also at android devices. And all is working fine - just as the server settings are requiring.

**Comment by dsvk** [comment]
https://github.com/jitsi/jitsi-meet/issues/5808#issuecomment-886534388 could probably resolve this.
