### ISSUE TITLE
prosody/util/serialization.lua:38: Can't serialize function

### ISSUE THREAD

**Issue by ecommerce-technician** [jitsi/jitsi-meet#7932]
### Description:
Error says "please report" so I'm reporting here

```
Oct 19 14:49:20 general error   Top-level error, please report:
/usr/lib/prosody/util/serialization.lua:38: Can't serialize function
Oct 19 14:49:20 general error
stack traceback:
        [C]: in function 'error'
        /usr/lib/prosody/util/serialization.lua:38: in function </usr/lib/prosody/util/serialization.lua:37>
        (...tail calls...)
        /usr/lib/prosody/util/serialization.lua:196: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:220: in function </usr/lib/prosody/util/serialization.lua:218>
        (...tail calls...)
        /usr/lib/prosody/modules/mod_storage_memory.lua:39: in function </usr/lib/prosody/modules/mod_storage_memory.lua:37>
        (...tail calls...)
        /usr/lib/prosody/modules/muc/mod_muc.lua:476: in function '?'
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (...tail calls...)
        /usr/lib/prosody/util/startup.lua:333: in function 'shutdown'
        /usr/lib/prosody/modules/mod_posix.lua:173: in function </usr/lib/prosody/modules/mod_posix.lua:170>
        [C]: in function 'socket_select'
        /usr/lib/prosody/net/server_select.lua:920: in function </usr/lib/prosody/net/server_select.lua:908>
        [C]: in function 'xpcall'
        /usr/bin/prosody:76: in function 'loop'
        /usr/bin/prosody:86: in main chunk
        [C]: in ?
```

### Steps to reproduce:
install and configure jitsi-meet-tokens and token_moderation plugin

### Expected behavior:

No errors
### Actual behavior:

Error above 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:
Most recent jitsi-meet, videobridge

prosody 11.7
lua 5.2

Ubuntu 18.04

### Additional information:

The app actually seems to work as expected

**Comment by damencho** [comment]
Do you see the same error if you disable token_moderation module?

**Comment by ecommerce-technician** [comment]
So it seems intermittent, restarting prosody and the error just went away, we're working on trying to replicate the issue in dev, I'll test that and get back to you

**Comment by aidgab** [comment]
Having the same on Prosody 0.11.4 on a moderate load. Really makes it hard to work with.

**Comment by RockOutLoud** [comment]
@ecommerce-technician @damencho Has there been any progress made on this issue (#7932)?

**Comment by damencho** [comment]
@ecommerce-technician You are not running with this https://github.com/jitsi/jitsi-meet/commit/734631a7a42e5b75d224b22c8d8815cd29f07cc1, right? 
This is jitsi-meet-web package version 4507.

**Comment by photoninger** [comment]
Today I had the same problem, with about 50 conferences active.
Running on Debian buster.
Prosody 0.11.2
with stable-packages:
jitsi-meet                           2.0.5142-1         
jitsi-meet-prosody                   1.0.4466-1         
jitsi-meet-turnserver                1.0.4466-1         
jitsi-meet-web                       1.0.4466-1         
jitsi-meet-web-config                1.0.4466-1         
jitsi-videobridge2                   2.1-376-g9f12bfe2-1

Will try the patch in https://github.com/jitsi/jitsi-meet/commit/734631a7a42e5b75d224b22c8d8815cd29f07cc1
