### ISSUE TITLE
Getting crash on call start in android in stable version 5142

### ISSUE THREAD

**Issue by jatinderana** [jitsi/jitsi-meet#7937]
Hi, 
I am getting error when i start call and other user join android app give me error.

![processed](https://user-images.githubusercontent.com/60269542/96556617-d58cae00-12d6-11eb-8d7e-52f56ec6e811.jpeg)

and after that we get no audio and video.
We are just running jitsi new stable version 5142.

**Comment by saghul** [comment]
Update you app to latest master, we have fixed this last week.
