### ISSUE TITLE
Remote menu is not visible on Safari

### ISSUE THREAD

**Issue by tanvir23** [jitsi/jitsi-meet#7945]
### Description:

When join meeting from safari, if the remote video is on, the remote menu in the filmstrip is not visible when using stage view. It works on the tileview and when remote guest's camera is off. once the camera is turned on remote menu disappears. This can be reproduce in meet.jit.si 

### Steps to reproduce:

1. Join meeting from safari browser
2. Make sure remote participant video is switched on.
3. use stage view
4. hover or click on remote guest's menu button as shown in the video link below,

https://drive.google.com/file/d/1jLJMWoyW-u7yV2k5e7LCoROnKeXpXwQJ/view?usp=sharing

**Comment by tanvir23** [comment]
hi @jallamsetty1  any update on this? Its been almost a month...

**Comment by tanvir23** [comment]
guys any update on this issue?

**Comment by jallamsetty1** [comment]
@tanvir23, sorry for the delay in responding. This is a low priority issue and we may not be able to get to it immediately. Leaving the issue open, we will be happy to accept PRs that will fix this UI issue.

**Comment by saghul** [comment]
The menu has been refactored into a drawer and this is no longer an issue.
