### ISSUE TITLE
Local build is not working

### ISSUE THREAD

**Issue by fmuntean** [jitsi/jitsi-meet#7947]
I am trying to build the jitsi-meet site for debugging locally.
based on this link: https://github.com/jitsi/handbook
we were supposed to just run the npm install followed by npm start
however I get the following error:
$ npm start
npm ERR! missing script: start

Please advise how can I start debugging the site on my local computer.

**Comment by damencho** [comment]
There is no npm start.
Do
npm install
make dev
Make sure you use latest LTS from nodejs.org
When you have questions or problems please use the community forum before opening new issues, thank you!
