### ISSUE TITLE
[ANDROID]Custom SDK published and added to the maven repo, but the UI changes are not visible even after syncing gradle files

### ISSUE THREAD

**Issue by rananajam1** [jitsi/jitsi-meet#7957]
### Description:

Custom SDK published and added to the maven repo, but the UI changes are not visible even after syncing gradle files

### Steps to reproduce:

1. Changes in Custom SDK (react-native)
2. Publish sdk 
3. Add to gradle files and Sync gradle files
4. Run project
5. Changes not visible

### Expected behavior:

The UI changes must appear in the project?

### Actual behavior:

Changes not visible

### Server information:

- Jitsi Meet version:mobile-20.3 branch

### Client information:

- Browser / app version: ?
- Operating System:Android

**Comment by rananajam1** [comment]
I've tried posting in Community Forum plenty of times but none of them was answered. Hence @saghul @damencho I need guidance in solving this.

**Comment by rananajam1** [comment]
I cleaned the project, rebuilt it, and synced the gradle files and it was working then 🔥

**Comment by manishoctal** [comment]
My question is: How to publish to maven? @rananajam1 
Can you elaborate / share screenshot.
2. Publish sdk
3. Add to gradle files and Sync gradle files
?
