### ISSUE TITLE
open this code localhost but it error all.css not found

### ISSUE THREAD

**Issue by mayursancheti** [jitsi/jitsi-meet#7958]
i try open index.html on localhost but some error
how to remove this

 Uh oh! We couldn't fully download everything we needed :(
We will try again shortly. In the mean time, check for problems with your Internet connection!

Missing http://localhost/Mayur/Practice/trialsystem/jitsi-meet-master/css/all.css

show less   reload now

**Comment by izakgl** [comment]
Follow [this guide](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web) if you want to run jitsi meet from source.

**Comment by saghul** [comment]
You need to build it, as the linked guide shows.
