### ISSUE TITLE
No sound under Brave browser event if disabling  all protections

### ISSUE THREAD

**Issue by DCiprut** [jitsi/jitsi-meet#7960]
### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

One should hear participants if their microphone is enabled.

### Actual behavior:

No sound whatsover.  Testing audio speaker delivers no audible result.

![image](https://user-images.githubusercontent.com/9912426/96863996-03552c80-1468-11eb-9992-1a78ad5f2519.png)
![image](https://user-images.githubusercontent.com/9912426/96865470-4b754e80-146a-11eb-959f-9c6e3405518d.png)

### Server information:

- Jitsi Meet version: Don't know
- Operating System: Don't know

### Client information:
- Browser / app version: Brave Version 1.15.76 Chromium: 86.0.4240.111 (Build officiel) (64 bits)
- Operating System: WIndows version 10.0.18362.1082

### Additional information:

On other Labels sound is OK (e.g. YouTube videos or Windows sounds)
Also: On chrome browser, the sound works after disabling AdBlock protection. But unable to make it work under Brave.

**Comment by izakgl** [comment]
If the sound in Chrome works only after disabling AdBlock protection, it might be the same problem in Brave. Brave has an AdBlock built in.

**Comment by Echolon** [comment]
@DCiprut 

can you review with that ibfo?
