### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by YoussF** [jitsi/jitsi-meet#797]
Hi,

This is more a simple question than a real issue but, i was wondering if it is possible to change the default logo at top left corner ?
I'm working in a hospital and we wanted to change to logo by the one of the institution.

Thank you very much.
Youssef.

**Comment by alejandroCOD** [comment]
I'm also looking for this, has anyone found anything?

**Comment by Moubai** [comment]
you can change the file watermark.png by yours or change this line in all.css
`.leftwatermark{display:none;left:50px;margin-left:10px;background-image:url(../images/watermark.png)`

the location of this file is (for debian) : /usr/share/jitsi-meet/css/all.css
the watermark.png location is /usr/share/jitsi-meet/images/watermark.png
have a nice day

**Comment by AndyNormore** [comment]
You must have a self hosted version to do this. From there you can simply edit the config file to change URL and image.

you cannot do this using the jitsi hosted API.

**Comment by krisgermann** [comment]
Where might I find the config files?

/etc/jitsi/ is relatively empty, with just domain-config.js etc...

**Comment by DarkHalo117** [comment]
The files are located in /usr/share/jitsi-meet/css/

**Comment by saghul** [comment]
The provided answers are correct. Closing!

**Comment by vickumar1981** [comment]
I had a question.  Was this a recent change in jitsi where the logo must be shown if hosted externally, and can only be disabled now when hosting the jitsi server locally or on the cloud?

previously, i had been able to disable and change that setting by passing in:

`interfaceConfigOverwrite: {SHOW_JITSI_WATERMARK: false, SHOW_WATERMARK_FOR_GUESTS: false...`

to override the default interface configuration, but I noticed that is no longer working.

**Comment by ollydixon** [comment]
@vickumar1981 where do you pass this setting?

**Comment by vickumar1981** [comment]
@ollydixon   I do this via a javascript function that is called when the page is rendered.

```javascript
function init_firebase() {
var config = {
  apiKey: "$firebaseApiKey",
  authDomain: "$authDomain",
  databaseURL: "$dbUrl"
};
var options = {
  userId: "$participant",
  defaultText: "${langExample.replaceAll("\n", "\\\\n").replaceAll("\"", "\\\\\"")}"
}
if (!firebase.apps.length) {
firebase.initializeApp(config);
}
var ref = firebase.database().ref();
var firepadRef = ref.child("$interviewSession");
var editor = ace.edit("editor");
editor.setTheme("ace/theme/chrome");
editor.session.setMode("ace/mode/$editorMode");
var domain = "meet.jit.si";
var jitsiOptions = {
    roomName: "gotocode_$interviewSession",
    width: "100%",
    height: 350,
    parentNode: document.querySelector('#videoMeeting'),
    interfaceConfigOverwrite: {SHOW_JITSI_WATERMARK: false, SHOW_WATERMARK_FOR_GUESTS: false,
    TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection', 'profile', 'info', 'chat', 'recording',
        'livestreaming', 'etherpad', 'sharedvideo', 'settings', 'raisehand',
        'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
        'tileview'
    ]}
}
var api = new JitsiMeetExternalAPI(domain, jitsiOptions);
api.executeCommand('displayName', '$participantName');

firepad = Firepad.fromACE(firepadRef, editor, options);
}

init_firebase();
```

**Comment by benmargolin** [comment]
Same here, doing it a similar way and can't seem to get it to go away, tried various combinations of the override values... but mine is self-hosted, via docker. I can imagine if you're using meet.jit.si it may not be possible, but definitely should be overrideable with a local install...

**Comment by Arman170616** [comment]
If I want to change the Jitsi logo to my website logo, using backend Django project, but I can't fix it, anyone help me please,
Thanks,
email: arman.170616@s.pust.ac.bd
