### ISSUE TITLE
HTML code for embedding iframe is defect

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#7978]
When using the menu item for "embed conference" during a running conference the generated iframe HTML code lacks a closing quote and a space before "allowfullscreen" like this:

`<iframe allow="camera; microphone; display-capture" src="https://somedomain.de/confname**allowfullscreen="true"** style="height: 100%; width: 100%; border: 0px;"></iframe>`

**Comment by saghul** [comment]
You seem to be running an old version of Jitsi Meet. It got fixed here: https://github.com/jitsi/jitsi-meet/commit/ab21e3cd5e0c2e95fe880fc15ef9d706215b4d2f
