### ISSUE TITLE
Error message "Heath Check Failed" following on from #664

### ISSUE THREAD

**Issue by anatomism** [jitsi/jitsi-meet#798]
Following the closed ticket #664 

I reinstalled Jitsi Meet on a clean Debian Jessie install (complete format and reinstall) - installed Jitsi Meet from stable Debian repo. Nginx running latest mainline version - this is the only change - Java left as default that the Jiti-Meet package installs

The install was working for two days, but not fails with "Jitsi Videobridge is currently unavailable. Please try again later!"

Logs show the health check is failing with error 500 (different error to last time) as below:

`Jicofo 2016-08-13 08:48:30.243 WARNING: [96] org.jitsi.jicofo.JvbDoctor.warn() Health check failed on: jitsi-videobridge.vc.smart-tm.com error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns::xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Too many open files</text></error>`

I have attached the full jicofo log running over at least 10 days - each time I can only temporarily fix the issue by restarting Jicofo.

JVB.log -> http://pastebin.com/UWrDX6zD
Jicofo.log -> http://pastebin.com/GiSK1myH

Could anyone hint at anything - I really want to deploy this but its simply not stable... I am at a complete dead end and an looking for other projects to meet out needs - this is the best out there but I cant leave it alone for a week with out SSH level attention which makes it totally non suitable. 

Thanks in advance

**Comment by gradinaruvasile** [comment]
> Too many open files
What is the output of
`ulimit -n`
?

**Comment by anatomism** [comment]
![ulimit](https://cloud.githubusercontent.com/assets/9029851/17847898/7d1c3912-6848-11e6-84e7-124aa567f1c9.png)

ulimit -n = 65536

I also upped the `max locked memory` and `max memory size` to `unlimited` as attached

**Comment by anatomism** [comment]
Initially nothing I could do would work including new install. Its been running for over a week once I did the following:

You can disable health checks from jicofo by adding this to /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.HEALTH_CHECK_INTERVAL=-1
