### ISSUE TITLE
[FEATURE REQUEST] Save recent link as favorite and display on top

### ISSUE THREAD

**Issue by madmath03** [jitsi/jitsi-meet#7986]
**Is your feature request related to a problem you are facing?**
Not really.

**Describe the solution you'd like**
When you have some regular links, you might want to save them as favorites so that they are always displayed at the top of the list.

**Describe alternatives you've considered**
#4719

**Comment by saghul** [comment]
Isn't that what the recent list already does?

**Comment by madmath03** [comment]
> Isn't that what the recent list already does?

Yes and no.

If you're using the web interface of Jitsi, you only see the latest 3 links.

Let's say you have a meeting every week with always the conference link, but during the week you have other, maybe random, links. Every time you want to join your "_favorite_" link, you need to find back because it might not be available anymore in the recent connections history.

The idea here would be to able to "_pin_" at the top of the list, or maybe in another section, the favorite links that you regularly use.

Alternative to that would be to allow any caldav agenda to be linked to Jitsi Meet and just save the Jitsi link in the invitation to automatically popup the user (cf. #4719), but that's another story and much more complicated.
