### ISSUE TITLE
Need to remove "Help" feature iOS SDK

### ISSUE THREAD

**Issue by JaspreetSingh1986** [jitsi/jitsi-meet#7989]
Need to remove "Help" feature in iOS SDK
![WhatsApp Image 2020-10-28 at 12 13 46 PM](https://user-images.githubusercontent.com/46781429/97401899-a6e68700-1917-11eb-814b-667af3257276.jpeg)

**Comment by saghul** [comment]
Are you using your own deployment or meet.jit.si ? In case of the former, just remove the `userDocumentationURL` option from config.js

**Comment by JaspreetSingh1986** [comment]
We are using our own deployment.

**Comment by JaspreetSingh1986** [comment]
> Are you using your own deployment or meet.jit.si ? In case of the former, just remove the `userDocumentationURL` option from config.js

It is already commented on the own deployed server.

**Comment by saghul** [comment]
Are you sure you are joining your deployment then? Try the invite someone feature and check the URL.

**Comment by JaspreetSingh1986** [comment]
> Are you sure you are joining your deployment then? Try the invite someone feature and check the URL.

Thanks Saghul it is working for Help but now it is showing "Start Showing Subtitle" how I can remove it also.

**Comment by saghul** [comment]
You need to set the "close-captions.enabled" flag to false.
