### ISSUE TITLE
how to remove video button in jitsi-meet cordova plugin?

### ISSUE THREAD

**Issue by allandevs** [jitsi/jitsi-meet#7991]
I implemented a jitsi-meet plugin in my ionic project, but I want to remove the video button, preventing the user from enabling it, can someone help me?

![videoMeet](https://user-images.githubusercontent.com/66088842/97444717-38033100-190b-11eb-944b-48e087e80d88.jpg)

**Comment by Echolon** [comment]
Hello, please reach out to the community forum with questions.

**Comment by AngeloLDias** [comment]
same problem
