### ISSUE TITLE
Support user accounts

### ISSUE THREAD

**Issue by claell** [jitsi/jitsi-meet#7993]
**Is your feature request related to a problem you are facing?**
I know that the website says that no account is needed. But what if I want to have one? Currently there does not seem to be such option, correct?
An account would solve the problem of remembering user settings and possible other things across different machines and sessions.

**Describe the solution you'd like**
Some kind of account system. Might be hard to implement if one also wants to support decentralized solutions and don't want to use too much resources and effort to make it work. I think solutions like matrix, mastodon or diaspora have nice solutions for the decentralized accounts at least, so might be worth looking into them.

**Describe alternatives you've considered**
Not really applicable, I guess.

**Comment by saghul** [comment]
Hi there,

This is already supported, if you self-host Jitsi Meet. It supports "internal" auth, LDAP, JWT based, pretty much anything Prosody (the XMPP server we recommend) supports.

Note that settings synchronization is something we consider to be out of the scope of the project.

**Comment by claell** [comment]
I was mainly talking about the official hosted solution.

Sad to hear that the scope of this project is different to my expectations.

**Comment by saghul** [comment]
> I was mainly talking about the official hosted solution.

Right. Yeah, we don't have any plans to have accounts in meet.jit.si, sorry.

**Comment by claell** [comment]
Alright
