### ISSUE TITLE
Unable to set email in Jitsi External API Iframe

### ISSUE THREAD

**Issue by ultimateakash** [jitsi/jitsi-meet#7995]
```js
this.options = {
		      roomName: this.room, 
                       parentNode: document.querySelector('#meeting-frame'),
                       userInfo: {
                           email: 'akashmjp@gmail.com',
                           displayName: this.user.first_name 
                       }
		}

		this.api = new JitsiMeetExternalAPI(this.domain, this.options);
```

Hello,
I am jitsi iframe api in my angular 10 project. everything works fine. but i am not able to set email in userInfo object.

when i am calling `this.api.getParticipantsInfo()` it doesn't show me email field.

Also is there any way to send extra params in user info object.

Please help.

**Comment by Olie-Chanz** [comment]
Any updates for this?
