### ISSUE TITLE
Headless API for small client bots

### ISSUE THREAD

**Issue by miny1997** [jitsi/jitsi-meet#7999]
**Is your feature request related to a problem you are facing?**
Yes, I would like to run in a headless browser a Jitsi Meet client which has similar features like the iFrame API, but does not work with camera input or microphone thus not requesting any permissions from the browser user.

**Describe the solution you'd like**

A special flag in the iFrame API disabling the need for input devices which need special permissions from the user.

**Describe alternatives you've considered**

A standalone Jitsi Meet client API without the need of a browser.

**Comment by saghul** [comment]
You could use config overrides for that. What exactly are you trying to accomplish? A variation of this might help perhaps: https://gist.github.com/saghul/179feba3df9f12ddf316decd0181b03e#file-stream-js

**Comment by miny1997** [comment]
I would like to run the Jitsi iFrame API without accessing the video camera or the microphone. The problem is that normal browsers ask for permission to grab an audio/video stream and I want to access the API without any user interaction while this headless client is muted and deaf in the room.

**Comment by saghul** [comment]
You should be able to accomplish that with the following config overrides: `startWithAudioMuted=true` `startWithVideoMuted=true` `channelLastN=0` and `prejoinPageEnabled=false`

**Comment by miny1997** [comment]
It works for video cam access to not be queried, but it still asks for microphone access. :(

**Comment by saghul** [comment]
Do you need the incoming audio? If not you can do: `startSilent=true`

**Comment by miny1997** [comment]
I don't need it and I had it set. Still asks for mic access. Maybe there is a bug or mic access prevention is not covered by this flag.

**Comment by miny1997** [comment]
If it helps, here is a small prototype which connects to a room on jitsi.riot.im, scrapes the user list and leaves.

https://madliberteaproject.com/jitsiviewer.html#JitsiConferencePuzzledStandingThunder
