### ISSUE TITLE
Local video stream on jitsi meet react native iOS app not rendering when calls are made continuously

### ISSUE THREAD

**Issue by shashanksavanth** [jitsi/jitsi-meet#8005]
### Description:

Local video stream on  **jitsi meet** react native iOS app not rendering when calls are made continuously for 7 times.After 7th time local video doesn't render until u mute and unmute.

Happening only in **iOS**. Working fine in android

It's happening with jitsi meet production app which is pushed to app store

### Steps to reproduce:

1. open Jitisi meet app and join the conference
2. End the call and join again
3. Do the above steps of joining and ending for 7 times continously. 8th time local stream video will not render on iOS

### Expected behavior:

Local video should render 

### Actual behavior:

Local video doesn't render until u mute and unmute video

### Client information:

- app version: Jitsi Meet **20.4.2**
- Operating System: iOS 13.7

### Additional information:

Happening only in iOS .
Android its working fine

**Comment by ShashankSavanth** [comment]
I checked this issue myself and looks like react-native-webrtc is causing the issue , raised an issue in the repo of react-naitve-webrtc forum also. See if any developer can debug this
