### ISSUE TITLE
Jitsi meet doesn`t work on my macos Chrome

### ISSUE THREAD

**Issue by Topstar88** [jitsi/jitsi-meet#8009]
I am using google chrome Version 86.0.4240.111 (Official Build) (x86_64) on my mac (Catalina 10.15.3).
I cannot hear participant and also cannot see others camera. In a word, it doesnt work completely.
But it works in chrome incognito mode or other browsers.
Anyone has experience in this ?
Please comment on this thread if you know what the reason is.
Thanks.

**Comment by saghul** [comment]
Do you have any Chrome extensions installed? Do you see any errors in the JS console?

**Comment by Topstar88** [comment]
I have this error message in chrome console.

Logger.js:154 2020-10-29T21:32:24.230Z [features/base/tracks] Failed to create local tracks 
(2) ["audio", "video"]
0: "audio"
1: "video"
length: 2
__proto__: Array(0)
 
s {gum: {…}, name: "gum.not_found", message: "Requested device(s) was/were not found: audio, video", stack: "Error↵    at new s (https://vuro-jitsi.us/libs/lib…itsi.us/libs/lib-jitsi-meet.min.js?v=4466:1:93923"}
gum: {error: DOMException: Requested device not found, constraints: {…}, devices: Array(2)}
message: "Requested device(s) was/were not found: audio, video"
name: "gum.not_found"
stack: "Error↵    at new s (https://vuro-jitsi.us/libs/lib-jitsi-meet.min.js?v=4466:1:120050)↵    at https://vuro-jitsi.us/libs/lib-jitsi-meet.min.js?v=4466:1:93923"
__proto__: Error

**Comment by Topstar88** [comment]
It works perfectly on chrome incognito or any other browsers something like firefox, brave etc.

**Comment by Topstar88** [comment]
Another comment is that https://meet.jit.si works well on chrome normal mode tho.

**Comment by saghul** [comment]
We fixed a Chrome compatibility bug recently, it was released in the latest stable build. You may need to tell the people running your server to upgrade, there is nothing we can do from our end in this case.
