### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by 1997louguendell** [jitsi/jitsi-meet#8011]
hallo, my camera doesnt work for my student online class

**Comment by saghul** [comment]
Please check the camera meta issue.

**Comment by 1997louguendell** [comment]
What does that mean

Gesendet von Mail für Windows 10

Von: Saúl Ibarra Corretgé
Gesendet: Freitag, 30. Oktober 2020 15:01
An: jitsi/jitsi-meet
Cc: 1997louguendell; Author
Betreff: Re: [jitsi/jitsi-meet] camera (#8011)

Please check the camera meta issue.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



--
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
