### ISSUE TITLE
Pod Install Failed: 

### ISSUE THREAD

**Issue by muratersin** [jitsi/jitsi-meet#8015]
Hi,
I getting this error after entering `pod install` command in ios directory and I can't resolve this.

RuntimeError - [Xcodeproj] Consistency issue: build setting `BUILD_LIBRARY_FOR_DISTRIBUTION` has multiple values: `{"Debug"=>"NO", "Release"=>"YES"}`

macOS Catalina 10.15.7

--versions
pod: 1.10.0
node: 14.15.0
xcode: 12

**Comment by jegathesan** [comment]
Got same error.

MacOS Mojave 10.14.6
XCode 11.3.1
CocoaPod 1.10.0
Node 12.18.3

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `BUILD_LIBRARY_FOR_DISTRIBUTION` has multiple values: `{"Debug"=>"NO", "Release"=>"YES"}`
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/xcodeproj-1.19.0/lib/xcodeproj/project/object/native_target.rb:95:in `common_resolved_build_setting'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:455:in `block (2 levels) in generate_targets'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:454:in `any?'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:454:in `block in generate_targets'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:443:in `each'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:443:in `generate_targets'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `<main>'
```

**Comment by infosteo** [comment]
Got the same error too!

**Comment by marcelodesouza** [comment]
Same problem here. I spent hours and I could not find a solution yet.

**Comment by saghul** [comment]
What Xcode version are you using? Xcode 12 is the only supported version.

**Comment by infosteo** [comment]
This worked for me:
. I downgraded cocoa pods from 1.10.0 to 1.9.3
. Executed pod install in iOS folder
. Opened project workspace in Xcode
. Compiled app
. Granted execution to run-packager-helper.command in Mac system preferences

**Comment by saghul** [comment]
Interesting, so it might be related to the cocoapods version then. We haven't updated from 1.9.3, so maybe that's why I'm unable to repro.

**Comment by marcelodesouza** [comment]
I found how to solve in my case!
Open the project in Xcode, select SDK project, go to Build Settings -> Build Options
On Build Libraries for Distribution set Debug = true

![Screen Shot 2020-11-03 at 13 22 02](https://user-images.githubusercontent.com/1896685/98012438-dbef4f80-1dd7-11eb-9131-bf50b4c2e3a4.png)

Then, on terminal
```
cd ios
pod install
```

**Comment by infosteo** [comment]
> I found how to solve in my case!
> Open the project in Xcode, select SDK project, go to Build Settings -> Build Options
> On Build Libraries for Distribution set Debug = true
> 
> ![Screen Shot 2020-11-03 at 13 22 02](https://user-images.githubusercontent.com/1896685/98012438-dbef4f80-1dd7-11eb-9131-bf50b4c2e3a4.png)
> 
> Then, on terminal
> 
> ```
> cd ios
> pod install
> ```

Ia also tried to change build options but in didn't work. :-(

**Comment by muratersin** [comment]
> This worked for me:
> . I downgraded cocoa pods from 1.10.0 to 1.9.3
> . Executed pod install in iOS folder
> . Opened project workspace in Xcode
> . Compiled app
> . Granted execution to run-packager-helper.command in Mac system preferences

It's fixed by this method. Thank you.
