### ISSUE TITLE
Broken startWithVideoMuted and startWithAudioMuted

### ISSUE THREAD

**Issue by mrin** [jitsi/jitsi-meet#8016]
This update breaks startWithVideoMuted and startWithAudioMuted config settings.

https://github.com/jitsi/jitsi-meet/blob/9fbb35b6e18536a85fc608b0685c71744880a651/conference.js#L736
https://github.com/jitsi/jitsi-meet/blob/9fbb35b6e18536a85fc608b0685c71744880a651/conference.js#L739
https://github.com/jitsi/jitsi-meet/commit/9c10ac3028548c3e8535d35789b23492b194e9fd

**Comment by AyushmanChatterjee** [comment]
Hello,

Is this issue going to be fixed soon?

Regards,

**Comment by kiliankoller** [comment]
Same Problem here, conflicts with GDPR, so quite important. Thanks!

**Comment by saghul** [comment]
Closing as a duplicate of https://github.com/jitsi/jitsi-meet/issues/8144, which has more context in it. Please follow that issue.
