### ISSUE TITLE
My mic is muted but they can still hear my audio. Unmute is not tappable.

### ISSUE THREAD

**Issue by dyros26** [jitsi/jitsi-meet#8019]
How to reproduce
- turn on your mic
- share chrome tab, check the share audio
- turn off your mic
- stop sharing chrome tab

result: your audio button is muted and you cant tap unmute button.

**Comment by CosmoMyzrailGorynych** [comment]
People can hear us even without these manipulations with sharing. A regular voice conference call without any fancy stuff.
