### ISSUE TITLE
pwa-worker.js missing onb Ubuntu

### ISSUE THREAD

**Issue by kiliankoller** [jitsi/jitsi-meet#8024]
### Description:

On https://meet.jit.si/, this file exists: https://meet.jit.si/pwa-worker.js
On a default installation on Ubuntu it is missing and the browser consoles are reporting errors accordingly.
/usr/share/jitsi-meet/pwa-worker.js is missing

### Steps to reproduce:

Install jitsi via apt on Ubuntu
curl https://meet.domain.com/pwa-worker.js

### Expected behavior:

- No browser erros
- https://meet.domain.com/pwa-worker.js is found
- /usr/share/jitsi-meet/pwa-worker.js exists

### Server information:

- Jitsi Meet version: 2.0.5142-1 / 1.0.4466-1
- Operating System: Ubuntu 18 LTS

### Client information:

- Browser / app version: Any
- Operating System: Any

**Comment by damencho** [comment]
Since jitsi-meet-web version 4480 this is be there: https://github.com/jitsi/jitsi-meet/blob/d067c4e7317126fd01008f5263a511a1efcd4c18/debian/jitsi-meet-web.install#L16

**Comment by kiliankoller** [comment]
I just did another clean install on Ubuntu 20, the file is still missing:

root@meet /usr/share/jitsi-meet # ls -lha
total 692K
drwxr-xr-x 12 root root 4.0K Nov  2 17:59 .
drwxr-xr-x 88 root root 4.0K Nov  2 17:59 ..
-rw-r--r--  1 root root   18 Mar 26  2020 base.html
-rw-r--r--  1 root root    0 Nov 12  2019 body.html
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 connection_optimization
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 css
-rw-r--r--  1 root root 3.6K Feb 26  2017 favicon.ico
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 fonts
-rw-r--r--  1 root root    0 Nov 12  2019 head.html
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 images
-rw-r--r--  1 root root 7.9K Oct 13 13:47 index.html
-rw-r--r--  1 root root 9.4K Aug 12 01:25 interface_config.js
drwxr-xr-x  2 root root  12K Nov  2 17:59 lang
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 libs
-rw-r--r--  1 root root  950 Aug  6  2018 logging_config.js
-rw-r--r--  1 root root 5.4K Oct  9 12:35 package.json
-rw-r--r--  1 root root 585K Oct  9 12:35 package-lock.json
-rw-r--r--  1 root root    0 Feb 26  2017 plugin.head.html
drwxr-xr-x  3 root root 4.0K Nov  2 17:59 prosody-plugins
-rw-r--r--  1 root root   36 Mar 31  2020 robots.txt
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 scripts
drwxr-xr-x  2 root root 4.0K Nov  2 17:59 sounds
drwxr-xr-x  3 root root 4.0K Nov  2 17:59 static
-rw-r--r--  1 root root  608 Mar 14  2019 title.html

root@meet /usr/share/jitsi-meet # dpkg -l | grep jitsi
ii  jitsi-meet                           2.0.5142-1                        all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                   1.0.4466-1                        all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                       1.0.4466-1                        all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                1.0.4466-1                        all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                   2.1-376-g9f12bfe2-1               all          WebRTC compatible Selective Forwarding Unit (SFU)

What am I missing? 

Thanks!

**Comment by damencho** [comment]
> ii jitsi-meet-web 1.0.4466-1 all WebRTC JavaScript video conferences

You are running version 4466, you need 4480.

Try the latest version from the unstable repo.

**Comment by seesturm** [comment]
So it is still broken in stable version?

**Comment by saghul** [comment]
It's not yet on a stable version, no.
