### ISSUE TITLE
Audio and video do not work in IOS Mobile browser

### ISSUE THREAD

**Issue by jpalcanttara** [jitsi/jitsi-meet#8025]
I use the external Jitsi API. Api is unable to request permission to use the device's camera and microphone

**Comment by anjali-b-nair** [comment]
tested on iOS 14.1. Not able to access camera and microphone.

"[features/base/tracks]" – "Failed to create local tracks" (2)
["audio", "video"] (2)
TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')
(anonymous function) — RTCUtils.js:1018
Promise
_newGetUserMediaWithConstraints — RTCUtils.js:1017
[native code]
promiseReactionJob
error
o — Logger.js:182
o
(anonymous function) — functions.js:121
promiseReactionJob
o — Logger.js:182



"[JitsiMeetJS.js]" – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: "
Error: Strophe: Websocket closed unexpectedly
(anonymous function) — strophe.util.js:109
error — strophe.umd.js:1392
_onClose — strophe.umd.js:5676
_onClose
error
o — Logger.js:182
o
getGlobalOnErrorHandler — JitsiMeetJS.js:628
(anonymous function) — middleware.js:118
callErrorHandler — GlobalOnErrorHandler.js:61
(anonymous function) — strophe.util.js:108
error — strophe.umd.js:1392
_onClose — strophe.umd.js:5676
_onClose
o — Logger.js:182

**Comment by jallamsetty1** [comment]
On what browser are you seeing this issue ? Please note that only Safari is supported on iOS and iPadOS since the others browsers on iOS do not support webrtc.

**Comment by anjali-b-nair** [comment]
I am using Safari

**Comment by usamashahid049** [comment]
I am also facing the same issue
Have you found any solution? @anjali-b-nair @jpalcanttara

**Comment by 532910** [comment]
can confirm this issue, outgoing audio and video works ok, but no A/V from other participats
safari, ipad air, 12.5.4

**Comment by AnnaShaleva** [comment]
+1 from Safari, iPhone 12, iOS 14.5 (18E198).
Permissions are requested (and granted), but the audio is missing sometimes.

**Comment by saghul** [comment]
Do you test on meet.jit.si or your own deployment? If so, what versions are you running?

We have made some critical bug fixes in the area in the past 1-2 weeks.

@jallamsetty1 are all fixes deployed already?

**Comment by 532910** [comment]
Own deployment, the latest stable from download.jitsi.org, 2.0.6293-1, debian buster.

**Comment by 532910** [comment]
Unfortunately yes, I have the same problem with meet.jit.si.

**Comment by jallamsetty1** [comment]
Yes, meet.jit.si has our recent fixes. @532910 I have few questions.

1. Are you trying in the browser directly or are you using the external API ? 
2. Did it ever work on that device and you just started experiencing this issue recently ?
3. iPad air, 12.5.4 is running an older version of the iOS. Will you be able to update it to the latest iOS and check ?

**Comment by 532910** [comment]
1. in the browser directly
2. I dunno, on my devices it just doesn't work, I did test after @AnnaShaleva report (personal)
3. same iPad air updated to 12.5.5 has the same issue, moreover, I just note that it shows me as muted:
![image](https://user-images.githubusercontent.com/14617699/135722922-a9fe7aa5-1cac-4cc1-8184-23e15dada838.png)
while this is not true
iphone 8 under 15.0 works fine for me
