### ISSUE TITLE
Error on release-sdk.sh

### ISSUE THREAD

**Issue by wilsongarena** [jitsi/jitsi-meet#8034]
I am currently trying to build and use configure SDK. Followed the instructions on the Handbook but I'm having the error below when executing release-sdk.sh. I've a similar question like this, it said there that i need to remove `node_modules` and run `npm install` again but the problem is persists. 

``Task :sdk:bundleReleaseJsAndAssets
warning: the transform cache was reset.
fs.js:1384
    throw error;
    ^

Error: watch /home/jitsi-meet/node_modules/react-native-keep-awake/android/build/generated/res/pngs/release ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (/home/jitsi-meet/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/jitsi-meet/node_modules/sane/src/common.js:109:31)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at /home/jitsi-meet/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:135:15)

> Task :sdk:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
``

**Comment by zvs001** [comment]
> Error: watch /home/jitsi-meet/node_modules/react-native-keep-awake/android/build/generated/res/pngs/release ENOSPC

Seems you simply don't have space on your disk

**Comment by wilsongarena** [comment]
> > Error: watch /home/jitsi-meet/node_modules/react-native-keep-awake/android/build/generated/res/pngs/release ENOSPC
> 
> Seems you simply don't have space on your disk

I know this might not be directly related to the project. But I do have enough space on my disk. How am i be able to solve this? I hope you dont mind.

**Comment by zvs001** [comment]
It may create files(cache) where you don't expect.
I remember I got same problem and space was enough on my disk. Later I found that it requires space at different place, where space was limited.
I don't remember exactly my case. But you can check both your disks (if you have).
