### ISSUE TITLE
New "Save Logs" feature exposes sensitive information to meeting participants

### ISSUE THREAD

**Issue by fremzy** [jitsi/jitsi-meet#8036]
### Description:

The latest version of Jitsi Meet has a "Save Logs" feature that generates a json file with a bevy of technical information about the meeting. This log contains the server name, server IP address, participant's IP addresses e.t.c. While this may be a useful feature for the admin-like 'moderator', it creates unnecessary exposure when made readily available to all users in the meeting.

### Steps to reproduce:

1. Start a Jitsi Meeting
2. Add participants to the meeting
3. Click on the "Save Logs" link in the user connection details pop-up to download a json file

### Expected behavior:

Only the Moderator should see and have access to save meeting logs

### Actual behavior:

Clicking "Save Logs" automatically downloads a log of the meeting details in json format to the default download directory of the user.

![Screen Shot 2020-11-03 at 11 44 03 PM](https://user-images.githubusercontent.com/63688942/98130912-c5550100-1e88-11eb-8873-00289d37fa82.png)

### Server information:

- Jitsi Meet version: 5142-1
- Operating System: Ubuntu Server LTS 20.04

### Client information:

- Browser / app version: Chromium / 88.0.4299.0 (Developer Build) (x86_64)
- Operating System: Mac os x 10.13.6

### Additional information:

This log file, while potentially useful to the moderator, serves no useful purpose to the ordinary user and creates an easy trove of information for a potential bad player. At the very least, it should be an administrative feature; it's hard to see the use case for making this available to meeting attendants.

**Comment by gpolitis** [comment]
Note that this doesn't include any information that isn't already available in the client. The participant IP address is only visible in the p2p case and in larger calls you only see the server IP address.

**Comment by gene96817** [comment]
Is there a way to save the log automatically to a log file on the server? Does the log include users that have had connection problems? I need a way to review user problems without being the moderator in every session.

**Comment by fremzy** [comment]
> Note that this doesn't include any information that isn't already available in the client.

@gpolitis true, you can get much of this information through the browser console, but most users don’t necessarily go searching through the console. The ready-availability here will spark unnecessary curiosity. And it makes it even less work for a potential bad player to target the system.

The big question remains: what exactly is the use case for participants having this link?

**Comment by saghul** [comment]
> The big question remains: what exactly is the use case for participants having this link?

The use case is simple: make it easier for users to give us information that can help us fix their problems. Many people don't know what the browser console is.

I move for close, since no security sensitive information is disclosed.

**Comment by fremzy** [comment]
> The use case is simple: make it easier for users to give us information that can help us fix their problems.

Hmm..mm so I'm not sure about the strength of this use case. I'm nowhere near being an expert on these things, but the information in the log doesn't quite mimic the information in the browser console. Not to say the information in the log is not useful for troubleshooting purposes.

There are intrinsic risks in having an exposed IP. For those who host their servers in the Cloud on a paid service, the risks may be less, but those of us who have our servers in-house run a greater risk. It's not that hard to track a person's address using their IP, for instance. And that's just one of many concerns.

These logs could be useful, but strictly on an administrative level. I'm not arguing against their presence, I'm arguing against their easy accessibility by mere meeting participants. Perhaps they can just be stored on the server somewhere under a directory like "Meeting Logs" instead? That way, the server administrator can quickly access them, if needed, for troubleshooting client issues (even so, I still think the browser console logs would prove to be more useful in that instance).

There could also be the option to just make this feature a choice to implement? Maybe a check like "Show Log Link"?

**Comment by damencho** [comment]
> Perhaps they can just be stored on the server somewhere under a directory like "Meeting Logs" instead?

These are only client logs and are available only to the client. 

> There could also be the option to just make this feature a choice to implement? Maybe a check like "Show Log Link"?

Any PR is welcome, thanks.

**Comment by fremzy** [comment]
> Any PR is welcome, thanks.

With my level of expertise (or the lack thereof), this can only be a feature request. I'm not a Developer, but as an astute user, I can see when a feature is a concern.

**Comment by saghul** [comment]
> Perhaps they can just be stored on the server somewhere under a directory like "Meeting Logs" instead?

That has very intricate implications on data retention for instance.

@fremzy I get that it may look daunting, as they are not for end user consumption for for helping with troubleshooting, but so far you haven't provided any proof of problems this may cause. IPs are equally accessible. Again, you get your logs, not everyone else's.

**Comment by gene96817** [comment]
There are three kinds of users involved here. (1) the meeting attendee. This person doesn't need the log. this person may have a connection problem or a session quality problem. (2) the meeting host. this person is just another kind of meeting attendee and has the same needs as (1). Then there is (3) the server administrator. This person needs information to help resolve user problems.  I have recently installed a server (<30 days ago). I need tools for understanding the problems encountered by the users.  As always, is the problem (1) the users computer and browser, (2) the internet connection quality, or (3) is the problem in the server code or configuration? Did the server runout of resources? Was it a software quality issue? Was the software misconfigured?

**Comment by fremzy** [comment]
> but so far you haven't provided any proof of problems this may cause.

@saghul I thought I mentioned how this is a concern in my previous comment. Here's my quote:

> There are intrinsic risks in having an exposed IP. For those who host their servers in the Cloud on a paid service, the risks may be less, but those of us who have our servers in-house run a greater risk. It's not that hard to track a person's address using their IP, for instance. And that's just one of many concerns.

Quite a few of us run our servers in-house. So the server IP is often equivalent to our personal IP. You're more knowledgable in this area, so I don't need to elaborate on how this could be a problem. It's the same reason why people often opt for VPNs at home. 

The fact is, this information does not need to be made so accessible to users. Yes, they may still be able to get them through other means, but we shouldn't be providing it to them easily. Security/Privacy/some degree of anonymity are all the reasons why many of us flocked to Jitsi; so anything that even borders on the fringes of discomfort in that area is undesirable.

Again, if we can have an option to turn this on/off, that would be great. Alternatively, perhaps the link can just say "Send Log Files" and instead of downloading the log, it could be set to be automatically transmitted to a designated (admin) email address.

**Comment by saghul** [comment]
@fremzy If someone is **already** connected to your server, which is the only way they can access the functionality they are gaining nothing new from it. They are already connected, they know your IP.

> The fact is, this information does not need to be made so accessible to users. Yes, they may still be able to get them through other means, but we shouldn't be providing it to them easily.

I have to disagree here. You have no idea how many support questions we get.

> Security/Privacy/some degree of anonymity are all the reasons why many of us flocked to Jitsi; so anything that even borders on the fringes of discomfort in that area is undesirable.

Again, this exposes nothing you don't already have, so there are no security implications that we are aware of. If you find any, we have security contact information on the repo. When raising a security problem, there has to be some attack vector or some proof that it is indeed a problem. The fact that very IP the user used to connect to your server is written in the logs only you as a user get is not that, sorry.

> Again, if we can have an option to turn this on/off, that would be great.

Sure, this makes sense.

> Alternatively, perhaps the link can just say "Send Log Files" and instead of downloading the log, it could be set to be automatically transmitted to a designated (admin) email address.

Again, no, this creates liability for whomever stores the logs.

**Comment by fremzy** [comment]
@saghul I think the fact that someone can potentially track me down to my home is a serious enough concern for me. I get that it's a risk I run if they're already connected to my server anyhow, but I'm not quite sure why I'd want to make it easier for a bad player.

> Again, no, this creates liability for whomever stores the logs.

I still struggle to understand the liability here. In the use case you highlighted, in trying to troubleshoot a user's issue, you ask them to download that log and then send it to you, right? How is this any different from them clicking a link that autogenerates the log (like it does now), but additionally auto-transmits it, without downloading a copy to the user's machine? In fact, thinking through it, isn't this the way most applications are debugged? User's system generates a log (error message/log) and (with the user's permission) is then transmitted to the developer.

I don't think we're going to agree on this one, @saghul (and we rarely disagree... lol). So yes, if an option to enable/disable this feature is incorporated, that would be awesome.

**Comment by saghul** [comment]
> I think the fact that someone can potentially track me down to my home is a serious enough concern for me. I get that it's a risk I run if they're already connected to my server anyhow, but I'm not quite sure why I'd want to make it easier for a bad player.

But they can't, that's the whole point here. How would saving the logs help with that? Be specific.

> I still struggle to understand the liability here. In the use case you highlighted, in trying to troubleshoot a user's issue, you ask them to download that log and then send it to you, right? How is this any different from them clicking a link that autogenerates the log (like it does now), but additionally auto-transmits it, without downloading a copy to the user's machine? In fact, thinking through it, isn't this the way most applications are debugged? User's system generates a log (error message/log) and (with the user's permission) is then transmitted to the developer.

The problem is that when you store user logs there are implications such as GDPR. We don't want to store anything more than we need to. And in this case we don't need to store anything to begin with. Also consider that if we made a system to store the logs, organizations having their own Jitsi Meet installations would have to deal with GDPR implications for example. Having no data on a user is the safest path.

I think your heart is on the right place, I really do. Having security and privacy as guiding principles is very useful and it's something I myself do. Things are sometimes different than they seem, however. In this case, those logs don't provide anything which is not readily available for users (developer console). We just want to make it easier for users to help us help them. While your suggestions are most welcome, they make the situation arguably worse, because there would be a central place where user data is stored, as opposed to none. Each user can just take their own data for a given call, and if they don't nothing is stored anywhere.

I do agree that having a setting for it would be useful, and a PR for that would be most welcome. We can keep this open until someone finds the time to do it.

**Comment by fremzy** [comment]
I don't want to drag this, because I think we've come to an agreeable compromise.. lol. But I think you may be misunderstanding my suggestion. I'm not arguing for a central server storage anymore, my suggestion is that instead of the log being generated, downloaded and saved on the client's machine when requested, it can be generated (as it is now), but then sent ON REQUEST (specifically for troubleshooting purposes) through an autoconfigured transmission channel to the 'administrator', without saving it on the client's machine. It's essentially the same thing you have now, the only difference being that rather than "Save log", you have "Send log" or something like that. Am I making sense?

Anyhow, yes, hopefully someone can pick this up as a PR soon. Like I said, my knowledge is quite limited here and sometimes, the problem may well just be that when one doesn't know a lot, the dark areas become even more more scary than they should be... lol

**Comment by gene96817** [comment]
I like the idea that the log is incrementally saved to a target location that is different from the central server. This allows for my three reference points.
1- the server could be a personal machine or in a cloud service and the log can be located anywhere... this avoids/solves the GPDR issues.
2- the server could be run by a coop and the log allows tabulating usage by members
3- the log contains information to troubleshoot problem reports.

Thanks...
