### ISSUE TITLE
unable to resolve module lib-jitsi-meet/lib-jitsi-meet.min

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8037]
i have tried yarn command as suggested in previous issues, but still the issue persists

**Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `react/features/base/lib-jitsi-meet/_.native.js`: lib-jitsi-meet/lib-jitsi-meet.min could not be found within the project**
![Simulator](https://user-images.githubusercontent.com/17109087/98209961-cdcf3980-1f65-11eb-9ee6-1472dc90ec91.JPG)

**Comment by saghul** [comment]
Don't use yarn. Just do `npm install`

**Comment by sachinhunasnale** [comment]
> Don't use yarn. Just do `npm install`

what are the steps i should follow after downloading zip file.
i am using: Node 15.0.1
                  NPM 7.0.3
                  Xcode 11.6
                  cocoapods 1.9.3

**Comment by saghul** [comment]
Please follow: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile

**Comment by sachinhunasnale** [comment]
can i use xcode 11.6

**Comment by sachinhunasnale** [comment]
@saghul
npm install result 
![npm](https://user-images.githubusercontent.com/17109087/98230112-c5d0c300-1f80-11eb-9750-f71d6ccc8d1e.JPG)

**Comment by saghul** [comment]
> can i use xcode 11.6

No.
