### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8038]
@saghul
npm install result 
![npm](https://user-images.githubusercontent.com/17109087/98230112-c5d0c300-1f80-11eb-9750-f71d6ccc8d1e.JPG)

_Originally posted by @sachinhunasnale in https://github.com/jitsi/jitsi-meet/issues/8037#issuecomment-722293002_

**Comment by saghul** [comment]
I cannot reproduce this with Node 12, which is the current LTS, I suggest you use that.

**Comment by sachinhunasnale** [comment]
thanks. it's working fine with node 12 and cocoapod 1.9.3
