### ISSUE TITLE
Android microphone doesn`t work.

### ISSUE THREAD

**Issue by Topstar88** [jitsi/jitsi-meet#8042]
I am using Jitsi for android device and web. So one user will use android and other participant will use web.
But both sides cannot hear. Jitsi doesn`t work at all for audio (other functions such as video, chatting, screen sharing work, just audio doesn`t work)
If I enable native call integration in settings page, web user could hear but android user can hear nothing.
It seems that microphone on android device doesn`t work. 
I found one possible issue from android studio log cat.

2020-11-05 10:27:41.857 23503-23562/org.jitsi.meet E/AudioRecordingConfiguration: Couldn't find device for recording, did recording end already?

Please feel free to comment on this thread if you have experience in this issue.
Thanks.

**Comment by saghul** [comment]
Can you paste the full adb logcat when joining a meeting?

**Comment by Topstar88** [comment]
Hi @saghul . thanks for your quick response.
I attached 2 files.
log1.txt file is just captured under native call integration disabled. (both sides cannot hear)
log2.txt is captured under it is enabled (web user can hear, android user cannot hear)
Please check.
Thanks in advance 
[log1.txt](https://github.com/jitsi/jitsi-meet/files/5496404/log1.txt)
[log2.txt](https://github.com/jitsi/jitsi-meet/files/5496406/log2.txt)

**Comment by Topstar88** [comment]
Hi @saghul , Any updates on this thread? Thank you.

**Comment by saghul** [comment]
Please don't be pushy. This is not the only issue.

I see very similar logs on both cases, nothing particularly stands out.

What kind of device is this? What Android version does it run? Do you use the app or SDK? What version? Last, can you reproduce the problem in meet.jit.si?

**Comment by Topstar88** [comment]
Our device is Qualcomm sdm660 arm64.
Android 9, API 29
We are using Jitsi-meet sdk to build custom maven, and importing this maven to our native app. (we need some customization for UI).
We are using latest Jitsi SDK on github (currently exist in master branch).
The problem happens all the time which means...

Disable Native call integration : Both sides cannot hear each other.
Enable it - Web user can hear, but android app user cannot.

Sending you a log file.
Thank you for your support @saghul .

[log(native call disabled).txt](https://github.com/jitsi/jitsi-meet/files/5500932/log.native.call.disabled.txt)
[log(native call enabled).txt](https://github.com/jitsi/jitsi-meet/files/5500933/log.native.call.enabled.txt)

**Comment by saghul** [comment]
Can you reproduce this issue with the Jitsi Meet app currently on the Play Store?

**Comment by Topstar88** [comment]
I just tested apk downloaded from store.
Result was same. Please check this log file. 

[log.txt](https://github.com/jitsi/jitsi-meet/files/5501445/log.txt)

Thank you.

**Comment by saghul** [comment]
I can't see anything obvious there :-/ Is this a regular phone or some specific hardware? Is there anything special (that you know of) about the audio hardware?

**Comment by Topstar88** [comment]
Hi @saghul . I found that this function is not triggered at all.

AudioDeviceHandlerConnectionService / line 118
public void onCallAudioStateChange(final CallAudioState state) { 

Is this something wrong ? 
Thank you so much for your support.

**Comment by saghul** [comment]
Yeah, that should trigger, assuming you use ConnectionService. I recommend you don't actually, since it's subject to vendor bugs and we now disable it by default on Jitsi Meet for this reason.

**Comment by Topstar88** [comment]
Oh So you mean we cannot use Jitsi meet on our device right ?

**Comment by saghul** [comment]
> Oh So you mean we cannot use Jitsi meet on our device right ?

Not really :-) Jitsi Meet should work on any device, but yours looks to be peculiar, so we're trying to figure out what's wrong.

> Actually RNConnectionService / startCall is not triggered either.
> Thanks.

As I said earlier, I suggest you disable native call integration and try to debug the regular audio device management. We've observed many problems with different vendors when it comes to native call integration.

**Comment by Topstar88** [comment]
Thank you @saghul .

**Comment by hotagu** [comment]
My phone mic didn't work but it work when I plug my earphone to phone.
