### ISSUE TITLE
Don't show screen sharer their own screen in fullscreen, a thumbnail would be better

### ISSUE THREAD

**Issue by gabrc52** [jitsi/jitsi-meet#8044]
### Description:

In order to improve the user experience, when sharing screen, the user who shares their screen should see a message saying "You are sharing your screen". A friend thought screen sharing was broken because this isn't this way, and it recursed "infinitely".

### Steps to reproduce:

1. Go to a meeting on the browser
2. Share the whole screen

### Expected behavior:

A message appears saying, "you are sharing your screen".

See the following screenshots from other video conference apps.

![Screenshot from 2020-11-05 16-50-17](https://user-images.githubusercontent.com/24363938/98305175-03d0e580-1f87-11eb-9166-d560b693afff.png)
Zoom web user interface

![Screenshot from 2020-11-05 16-51-14](https://user-images.githubusercontent.com/24363938/98305264-24993b00-1f87-11eb-8083-27bc1d9ebbc7.png)
Google Meet

### Actual behavior:

User sees their own screen, which shows their own screen, which shows their own screen and so on
![Screenshot from 2020-11-05 16-46-29](https://user-images.githubusercontent.com/24363938/98304974-98871380-1f86-11eb-98ab-5044cfaca0d8.png)

### Server information:

- Jitsi Meet version: Current version on meet.jit.si as of Nov 5, 2020
- Operating System: whatever meet.jit.su is running

### Client information:

- Browser / app version: Chrome
- Operating System: Windows and Linux

**Comment by damencho** [comment]
And if you are screen sharing the whole screen can you preview and see what you are sharing?

**Comment by gabrc52** [comment]
Yes, that's what's shown

**Comment by damencho** [comment]
Can you preview what you are screen sharing in those apps? On jitsi-meet you can see what you are sharing which is essential, the only drawback is that if you are sharing the current screen which shows that screen the loop happens ... But it is important for the user to check what is he sharing, and my questions is there a way to check that in those apps you are referring to? 
And if there is a preview you will be seeing the same screen in screen in screen ..., right?

**Comment by gabrc52** [comment]
No, those apps don't show you what you are sharing, so the screen loop can't happen.

Why do you consider it essential to be able to see what you're sharing?

**Comment by damencho** [comment]
How would you understand what you are sharing? There is no way to check...

**Comment by paweldomas** [comment]
Preview for local screenshare could be displayed in small video thumbnail

**Comment by gabrc52** [comment]
It'd still recurse less and be less annoying

**Comment by gabrc52** [comment]
Hello

**Comment by abhinav700** [comment]
did someone solve this issue? i am a beginner and would like to work on it

**Comment by saghul** [comment]
This was actually solved! Closing.
