### ISSUE TITLE
Fallback to BOSH if Websockets fail

### ISSUE THREAD

**Issue by awlx** [jitsi/jitsi-meet#8049]
Occasionally for whatever reason (we really couldn't tackle it down) some users fail to establish reliable websocket connections towards the frontend. 

It would be awesome if Jitsi-meet could just fallback to BOSH in cases where websockets fail. Otherwise people just stay in a reconnect loop.

Thanks for considering :).

**Comment by damencho** [comment]
Are you seeing this one meet.jit.si or your own deployment. Well if websocket is not possible to be established then video quality can also be affected as there will not be a websocket channel to the bridge

**Comment by awlx** [comment]
We see this issue all the time on multiple platforms. It seems that some times for example Cloudflare or Cloudfront or a ALB/ELB Instance just resets the connection for some users. This leads to endless reconnect loops for affected clients.

**Comment by damencho** [comment]
Is this latest jitsi-meet? There were bugs like that fixed in the past, but we have not seen it with lastest few stable releases. We see websockets more stable than bosh connections and less server resources ...

**Comment by amsnek** [comment]
if an optional fallback would be possible, that would be nice to have. Many proxies block wss by default and need the respective domains would need to be explicitly whitelisted.

**Comment by damencho** [comment]
> We see this issue all the time on multiple platforms. It seems that some times for example Cloudflare or Cloudfront or a ALB/ELB Instance just resets the connection for some users. This leads to endless reconnect loops for affected clients.

That is strange, we have not seen that, running meet.jit.si the exact same way.

**Comment by awlx** [comment]
So this also happens with Clients where some enduser protection proxies run. Some of them seem unable to pass through the HTTP upgrade request and thus the client fails to connect.

**Comment by shubham2110** [comment]
What is problem with falling back to BOSH anyway? if web-socket doesn't work for some reason, Jitsi stops working.. This is happening to almost all organizations client running behind proxy

**Comment by jbg** [comment]
@damencho Would a PR be accepted to implement this fallback? If so, can we re-open this ticket and we'll work to implement it?

We have several clients with users behind strict firewalls that block all WebSocket upgrades. They have to either ask the users to contact the corporate IT to get exceptions added, or switch their config to use BOSH only. Neither solution is as good as an automatic fallback would be. This is why libraries like socket.io that use WS usually have a way to fall back to long polling.

**Comment by saghul** [comment]
I'd say sure, a PR would be welcome, we can look at the fallback approach once ready.
