### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by Pretuer** [jitsi/jitsi-meet#8054]
Is your feature request related to a problem you are facing?

In a meeting with many people, sometimes you want to indicate your approval or dismissal (or another emotion) for an idea without speaking up and disrupting the conversation flow.

Describe the solution you'd like

For this, it would be useful if a user could pick from a list of emoji and that this emoji would be briefly shown on top of the user video (with fade-in and fade-out). It could cover maybe 50% of the area, potentially with some transparency.

Describe alternatives you've considered

The chat could be used as well, but it's persistent, while an approval of an idea is specific to something that was just said and is thus only relevant temporarily.

**Comment by tonibony** [comment]
See also #5217

**Comment by LuNeder** [comment]
Was this added for like 1 day and it was removed? I used it once and next week it wasn't there anymore

**Comment by saghul** [comment]
It is implemented and will be rolled out soon.
