### ISSUE TITLE
Some strings don't have a translation

### ISSUE THREAD

**Issue by gabrc52** [jitsi/jitsi-meet#8055]
### Description:

Some strings don't have a translation.

### Steps to reproduce:

1. Change the language to a non-English one
2. Go to the screens shown in the screenshots.

### Expected behavior:

If using a non-English language, those strings appear in that language.

### Actual behavior:

The strings appear in English.

Embed this meeting, under sharing:
![Embed this meeting](https://user-images.githubusercontent.com/24363938/98485406-c913bb00-21db-11eb-92dd-920114d3c219.png)

Enable lobby and lobby description, under security settings:
![Lobby](https://user-images.githubusercontent.com/24363938/98485419-d7fa6d80-21db-11eb-8e01-2278ea114e0a.png)

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: meet.jit.si

### Client information:

- Browser / app version: Chrome 86
- Operating System: Linux

**Comment by damencho** [comment]
These are not bugs, but missing translations, which are community contributed. For now to fix those you can create a PR with the translations.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues.
