### ISSUE TITLE
[self-assigned] Improve Spanish translation

### ISSUE THREAD

**Issue by gabrc52** [jitsi/jitsi-meet#8056]
The Spanish translation has quite some errors. It could definitely be improved.

**Edit, Note, I'm working on it**

**Comment by gabrc52** [comment]
I'm working on this issue. I'd like to self-assign it in order to avoid extra work (in case someone else wants to do this as well).

**Comment by Echolon** [comment]
Hola @gabrc52,

muchas gracias - esta muy bien!
