### ISSUE TITLE
Authentication Failed 

### ISSUE THREAD

**Issue by AceDabber** [jitsi/jitsi-meet#8065]
Keep getting a status when trying to test the video chat within jane for an appointment upcoming. It says 'authentication failed - sorry youre not allowed to join this call'. It's the test call jane app includes so what the heck is going on here. Appointment is tomorrow I need help! Chrome on a laptop with all specs working fine.

**Comment by saghul** [comment]
Who / what is Jane? You'll need to contact to whoever gave you the meeting information, we just make some software the people running that service use.

**Comment by AceDabber** [comment]
Lol what a poor customer service you offer. This is shameful. The janeapp booking service specifically uses your video call tech and links directly to you for support when this error comes up that im explaining. Quite telling that you can't tell me a single piece of info yet it redirects to this support website. How can it link here because its your tech, and then you act stupid like you've never heard of it before. Get me someone who has heard of it then. This is a joke of a support system.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by damencho** [comment]
This is an Open Source video conferencing solution called Jitsi Meet. There are thousands of uses of this software by different companies or individuals and you are using one of those. Contact that company support or support for that software Jane. This is not a support forum for those companies.

**Comment by saghul** [comment]
>  This is a joke of a support system.

This is not janeapp's support system. They are using our software, as many others are, they must have left some of the contact information pointing here, but we can't help you because your problem is with the janeapp authorization, not us.
