### ISSUE TITLE
CAM is not activated on Safari iOS 14.2

### ISSUE THREAD

**Issue by nehatdedinca** [jitsi/jitsi-meet#8071]
### Description:

Since the iOS have been updated to 14.2, on Safari browser is not possible to access the camera during the call over p2p connection.  

### Steps to reproduce:

1. Peer is using the latest Chrome on MacBook Pro and is able to join the call with working audio and video
2. I am using iOS 14.2 Safari browser on iPhone 11 Pro and I am able to join the call with working audio but **NO** video
3. Hence, the connection is established but no video is sent from the iPhone user 

Additional info, when the call is made over the bridge connection, everything works fine. The problem occurs when we have a p2p connection.

**Comment by jallamsetty1** [comment]
Safari does not use the p2p connection even when you have only 2 people in the conference. This bug has been resolved already in the nightly builds - https://github.com/jitsi/lib-jitsi-meet/commit/1958efd5d78293e29b5d8e030f54f6fd8550bb4c
