### ISSUE TITLE
On iOS Audio mode is by default Speaker. 

### ISSUE THREAD

**Issue by ankita-ecsion** [jitsi/jitsi-meet#8075]
Hi Saghul, 

I need to change my audio mode to ear piece by default, every time I change it it always route it to speaker. Can you help me how should handle this.

I am using i

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
This is by design and cannot be changed, sorry.

**Comment by deva-gopalani** [comment]
@saghul does this default also apply to android devices? Like when we start the call via an android device, is the default sound output through the speaker?

**Comment by saghul** [comment]
Yes.

**Comment by kirtirc** [comment]
Hello
@saghul  do you any solution for this problem ?

**Comment by nguyenNCphpFox** [comment]
same issue.
