### ISSUE TITLE
Feature Request: Deleting individual chat messages

### ISSUE THREAD

**Issue by Asocius** [jitsi/jitsi-meet#8087]
Hello folks, I'd love to see the feature to delete individual chat messages in jitsi. That would open up the possibility to play games like Just One on jitsi. We used to play it in the local church group...

Best regards
Stephan L.

**Comment by queerterpreter** [comment]
I know this feature request is old, but I just accidentally copypasted the wrong message in the chat and it was supremely embarrassing, I really wish it had been possible to delete the message!
