### ISSUE TITLE
"Raise hand" feature should not be shown with a notification toast

### ISSUE THREAD

**Issue by philippejadin** [jitsi/jitsi-meet#8089]
**Is your feature request related to a problem you are facing?**
If some one raises hand multiple times or a lot of users want to speak and thus raise their hand at the same time, we get tons of stacked notifications (worse, they don't fade after some time afaict), and we have no precise idea of who wants to speak because no one look at the notifications.

Asking to speak is light turning on or off a bulb. One might change his/her mind at any point in the discussion. This is poorly reflected by the notification toast currently in use.

**Describe the solution you'd like**
Put a large enough "hand raised" icon right on a corner of the video of the participant who raised hand. Allow user to turn it on/off at will. 

**Describe alternatives you've considered**
Let the icon on the participant video **be** the button to raise hand. 50% opacity = unraised but ready to be pushed, 100% opacity : hand raised; seen by everyone.
Bonus maybe if multiple people raise their hand : add a counter to know who raised hand first

Thank you for the wonderful tool!

**Comment by saghul** [comment]
Raise hand notifications are coalesced now, you'll see at most one.
