### ISSUE TITLE
Phone call not heard by everyone

### ISSUE THREAD

**Issue by jlgenet** [jitsi/jitsi-meet#8091]
Description:
French : Lors d'une conference meet.jit.si ce mardi 10 novembre : nous étions 6 personnes en visio et une en appel telephoniqe sur le numéro en France.
Deux des personnes n'entendaient pas celui qui était en appel telephonique alors que c'était ok pour les autres.

English : During a meet.jit.si conference on Tuesday 10th November: we were 6 people on video and one on the phone on the number in France.
Two of the people couldn't hear the one on the phone, whereas it was ok for the others.

We tried to disconnect and reconnect averyone but it was the same pb.

Server information: meet.jit.si

I used the app v 2.4.1 on GNU Linux Mint and other people were on their browsers (? V ?)

One of them tried with safari but had no video, no sound, bur joined the call so she tried with firefox and it was ok but she didn't hear the person who was on calling.

**Comment by Marcono1234** [comment]
Possibly same as #7124?
