### ISSUE TITLE
Screen share is heavily scaled down in chrome with upload bandwith < 2mbit/s

### ISSUE THREAD

**Issue by TheReal1604** [jitsi/jitsi-meet#8094]
### Description:

Screen Sharing is heavily scaled down in chrome with upload bandwith < 2mbit/s.

I updated our jitsi-meet-web to 1.0.4535-1 today from 1.0.4502-1. The screen sharing resolution is heavily reduced / scaled down if the user who shares has < 2mbit/s upload bandwith. If we use the firefox, the screen share resolution is not downscaled. (1680x1050 -> 400x200~)

I could not reproduce it, with more than 5mbit/s upload bandwith. 

A downgrade to the old version immediately fixed the issue for us.

### Steps to reproduce:

1. limit your upload bandwith, use a small bandwith internet connection
2. start a meeting on a jitsi meet deployment with jitsi-meet-web at version 1.0.4535-1
3. start a screenshare
4. see the heavy compression on the receiving side

### Expected behavior:

The screen share should be adaptive, but in a meaning that you can read some text.

### Actual behavior:

The screen share should be adaptive, but at this amount of downscaling it is unusable because you cant read something.
In our tests, it downscaled a 1680x1050 monitor resolution to around 400x200~ screen share resolution.

### Server information:

- Jitsi Meet version: 1.0.4535-1
- Operating System: Debian Linux

### Client information:

- Browser / app version: Google Chrome 86.0.4240 / Chromium  86.0.4240 (Sender and Receiver)
Not affected: Mozilla Firefox 82.0.3
- Operating System: Linux / Windows (tested)

**Comment by jallamsetty1** [comment]
Are you seeing the issue with jitsi-meet-web 1.0.4538-1 ? Also, do you set the config.js option testting.capScreenshareBitrate to 1 ?

**Comment by TheReal1604** [comment]
@jallamsetty1 Thanks for the quick fix, its working fine now :-).

**Comment by qchn** [comment]
Hello @jallamsetty1 
I can reproduce this bug in jitsi-meet-web 1.0.4556-1 (Debian Buster unstable release).
Shouldn't this be fixed in that version?

The upload bandwith played no role for my tests.

Chrome: 87.0.4280.66 
OS: Ubuntu 20.10 Groovy

Thanks
Robert

**Comment by jallamsetty1** [comment]
> Hello @jallamsetty1
> I can reproduce this bug in jitsi-meet-web 1.0.4556-1 (Debian Buster unstable release).
> Shouldn't this be fixed in that version?
> 
> The upload bandwith played no role for my tests.
> 
> Chrome: 87.0.4280.66
> OS: Ubuntu 20.10 Groovy
> 
> Thanks
> Robert

If you are reproducing the same behavior, it could be a different issue. Can you describe the issue in more detail, how many users and your config.js settings w.r.t testing.capScreenshareBitrate ? Does this work on a previous version of Chrome with the same jitsi-meet version ?

**Comment by qchn** [comment]
Thanks for the fast reply, @jallamsetty1 

We tested this issue with several users (2-5 in one conference). It seems that only Linux Users with the current version of Chrome (87.0.4280.66) are affected.

Mac and Windows Users such as Linux users with older Chrome versions were not affected.

I attached my config.js
[config_js.txt](https://github.com/jitsi/jitsi-meet/files/5597637/config_js.txt)

Thanks in advance
Robert

**Comment by jallamsetty1** [comment]
> Thanks for the fast reply, @jallamsetty1
> 
> We tested this issue with several users (2-5 in one conference). It seems that only Linux Users with the current version of Chrome (87.0.4280.66) are affected.
> 
> Mac and Windows Users such as Linux users with older Chrome versions were not affected.
> 
> I attached my config.js
> [config_js.txt](https://github.com/jitsi/jitsi-meet/files/5597637/config_js.txt)
> 
> Thanks in advance
> Robert

Thanks for confirming that it is a chrome M87 bug affecting only Linux. Will you be able to capture a screenshot of the send resolution for the participant reproducing the issue so that we can file a bug with chrome ?

**Comment by qchn** [comment]
Hi @jallamsetty1 

We can reproduce this on another Jitsi setup with version 1.0.4545-1, thanks to @TheReal1604 for helping us!
 
We recorded the screen, have a look at: https://youtu.be/HN7GEAIWpyo

The Client was using Chrome: 87.0.4280.66 and Ubuntu 20.10 Groovy in this Video.

Thank you for your help

**Comment by qchn** [comment]
Hi @jallamsetty1 
any news on this?

Best
Robert

**Comment by qchn** [comment]
For the record: adding "DISABLE_VIDEO_BACKGROUND: true," to /usr/share/jitsi-meet/interface_config.js solved the issue

Fore more info, see: https://community.jitsi.org/t/screen-share-flickering-in-chrome-83-on-windows-on-many-machines/68277/9 

Thanks again to @TheReal1604 who brought this to my attention!
