### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by krakazyabra** [jitsi/jitsi-meet#8095]
Hi! This is not a bug itselfs, but incorrect meaning in one phrase in Czech translation: 
here https://github.com/jitsi/jitsi-meet/blob/master/lang/main-cs.json#L537 the translation `Všechny připojovat jako skryté` means, that every new user will be connected as hidden user. Better to use here phrase `Při připojení všem vypnout kameru`. This will mean, that all new users will join with disabled camera, what equals original function

**Comment by damencho** [comment]
You can create a PR to fix that.
And we should finally add the translation system as we had planned, so people more easily can contribute ... sorry about that.

**Comment by krakazyabra** [comment]
Hi @damencho 
PR https://github.com/jitsi/jitsi-meet/pull/8101 is on the way!
