### ISSUE TITLE
nack pli

### ISSUE THREAD

**Issue by fippo** [jitsi/jitsi-meet#81]
Just noticed that chrome 35 includes a 
a=rtcp-fb:100 nack pli
line in addition to the nack one (is that legal even?)

This is currently not in 
https://github.com/jitsi/jitsi-meet/blob/master/libs/colibri/colibri.focus.js#L297
(which I think is from chrome 33)

**Comment by gpolitis** [comment]
moved to https://github.com/jitsi/jicofo/issues/16
