### ISSUE TITLE
ios SDK compile errors with xCode 12.2 (12B45b) on Big Sur

### ISSUE THREAD

**Issue by sei-vsarvepalli** [jitsi/jitsi-meet#8106]
### Description:

Xcode 12.2 got release recently with a slightly newer version of swift 5.3.1 causing JitsiMeet SDK to fail.  I am not sure how feasible it is provide libraries that can survive these ongoing updates from Apple.  I know Jitsi meet is very proactive and resolves these issues. Just want to raise this up to you when using the latest available SDK 2.10.2

### Steps to reproduce:

1. Accept Xcode update to 12.2
2. Run the Sample App or your app with JitsiMeet SDK pod file with latest SDK 2.10.2 
3. Get the error below 
Failed to build module 'JitsiMeet' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

### Expected behavior:

Normal compile and run with JitsiMeet SDK

### Actual behavior:

Error on compile attempt

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version:N/A
- Operating System:N/A

### Additional information:
Build environment 
Mac OS Big Sur 11.0.1
Xcode 12.2
SDK 2.10.2
Sample app with pod file pointing to SDX 2.10.2

**Comment by 3dg2r** [comment]
this happening to me also. any workaround for this?

**Comment by ffager83** [comment]
seeing this also. Trying to figure something out..

**Comment by danschlet** [comment]
I had this problem too, I had to build the Jitsi Meet framework myself with Xcode 12.2, then I was able to build my app again.

**Comment by mohdsafadsaal** [comment]
@danschlet how did you build ? running shell script or xcode?

**Comment by danschlet** [comment]
I followed the instructions here https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk. Installing dependencies was initially a bit tricky (for me, as I don't have experience with react native), I think I did this:

brew install node
npm install
pod install showed this error:
RuntimeError - [Xcodeproj] Consistency issue: build setting `BUILD_LIBRARY_FOR_DISTRIBUTION` has multiple values: `{"Debug"=>"NO", "Release"=>"YES"}`
So I had to open ios/jitsi-meet.xcworkspace, select the sdk project and the JitsiMeet target, search for `BUILD_LIBRARY_FOR_DISTRIBUTION` in Build Settings and set it to 'YES' for the debug build as well.
Then pod install should work.
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive
Then I still had the problem that the created archive in Xcode Organizer was empty, but I found JitsiMeet.framework in the DerivedData folder.

**Comment by saghul** [comment]
SDK 2.11.0 has just been released, it's compiled with Xcode 12.2 which should solve the problem.

**Comment by mohdsafadsaal** [comment]
@saghul Im getting following error in new sdk 

**ios/RCTWebRTC/WebRTCModule.h:15:9: fatal error:
      'WebRTC/RTCMediaStream.h' file not found
#import <WebRTC/RTCMediaStream.h>**


Using  "react-native-webrtc": "1.84.1".

Could you please address this issue?

**Comment by saghul** [comment]
Use the script in the react-native-webrtc repo to download the necessary bitcode.
