### ISSUE TITLE
Failed to allocate channels - no bridge configured

### ISSUE THREAD

**Issue by caduellery** [jitsi/jitsi-meet#811]
Hello,

I'm following the quick install guide, but only get "_Jitsi Videobridge is currently unavailable. Please try again later!_" message on the browser.

Jicofo log says:
_Jicofo 2016-08-26 15:24:04.231 SEVERE: [38] org.jitsi.jicofo.ChannelAllocator.**error() Failed to allocate channels for** cadu@conference.10.200.24.41/37d201bb
net.java.sip.communicator.service.protocol.OperationFailedException: **Failed to allocate channels - no bridge configured**_

Here is the full log of the session (jicofo, jvb and prosody):
http://pastebin.com/Ws89kVMn

Thanks in advance!

**Comment by caduellery** [comment]
Tried Oracle java 8, purged jitsi, reinstalled it and same error.

Tried unstable jitsi repo, same error. :(

**Comment by damencho** [comment]
Jicofo do not see a healthy jvb. Jvb on the other side cannot bind to any port as seen in the logs. Do you have any kind of restriction on the machine? Not sure whether selinux can cause this kind of errors, check these problems, not sure what is the config on your system.

**Comment by damencho** [comment]
Could you please discuss problems on the mailinglist before opening issues.
