### ISSUE TITLE
Config option to disable "Rate your meeting experience" prompt

### ISSUE THREAD

**Issue by anoadragon453** [jitsi/jitsi-meet#8111]
Our organisation doesn't need or use the statistics generated by the "Rate your meeting experience" dialog that pops up after hanging up a call. It would be nice if we could skip this screen and go straight back to the Jitsi homepage.

I believe this functionality is triggered by this method:
https://github.com/jitsi/jitsi-meet/blob/12c835dd919ee6da0b0dfc198cce819035a72e82/react/features/feedback/actions.js#L38-L94

It would be nice to have an option in `config.js` that would return early from this function if that option were set to true.

**Comment by damencho** [comment]
Please use the community forum for questions or problems before opening new issues.
There is you can disable callstats or you can set in config.js `feedbackPercentage: 0`

**Comment by Half-Shot** [comment]
It would be absolutely fantastic if you documented this in config.js for the next guy :)

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/pull/8112
