### ISSUE TITLE
prosody[877135]: portmanager: Error binding encrypted port for https

### ISSUE THREAD

**Issue by guymass** [jitsi/jitsi-meet#8115]
Hi,

I am trying to install jitsi on ubuntu 20.4. I have followed your main guid and currently I get the following error:

prosody[877135]: portmanager: Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281

The site url is https://meet.flatearth.co.il and currently I cannot create any conference.

can you please help as there is no other real error in the logs.

**Comment by damencho** [comment]
When you have problems or questions please use the community forum before opening new issues.


> prosody[877135]: portmanager: Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281

You can ignore this, that port is not used.

Did it work before you try to setup securedomain?
