### ISSUE TITLE
Electron "JitsiMeetJS" is not defined

### ISSUE THREAD

**Issue by matteoturini** [jitsi/jitsi-meet#8121]
### Description:

When trying to set an iframe's src to a Jitsi Meet URL, it fails, and says "JitsiMeetJS is undefined"

### Steps to reproduce:

1. Create an index.html with
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      * {
        margin: 0;
        padding: 0;
        /* overflow: hidden; */
      }

      iframe {
        width: 100vw;
        min-height: 100vh;
        max-height: none;
      }
    </style>
  </head>
  <body>
    <!-- the src was my school's online classes link (poorly secured) so i removed it -->
    <iframe
      src="https://example.com"
      frameborder="0"
      allow="microphone camera"
    ></iframe>
    <button onclick="document.querySelector('iframe').src = 'https:\/\/meet.jit.si/bbhhhbhb455ashcdhcbdh'">Test Jitsi!</button>
  </body>
</html>
```
2. creat start.js with
```js
const electron = require("electron");

const { app, BrowserWindow } = electron;

// if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
//   app.quit();
// }

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 1025,
    webPreferences: {
      nodeIntegration: true,
      webSecurity: false,
    },
  });

  mainWindow.loadFile('./index.html');

  mainWindow.webContents.openDevTools();
};

app.on("ready", createWindow);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.commandLine.appendSwitch("disable-site-isolation-trials");
```
3. Launch electron with 'electron start.js'
4. Click 'test jitsi' button
### Expected behavior:

The meeting loading
### Actual behavior:

Error in the console, grey screen

### Server information:

- Jitsi Meet version: the one on meet.jit.si
- Operating System: the one on meet.jit.si

### Client information:

- Browser / app version: electron 11.0.1
- Operating System: macos catalina

### Additional information:

![Screenshot](https://user-images.githubusercontent.com/69425093/99591422-83ba6f00-29cd-11eb-8305-2f8e10f1de3b.png)

**Comment by Echolon** [comment]
@saghul does it belong to a different repository?

**Comment by saghul** [comment]
No, it belongs here.

We fixed an issue with the logger that made Electron 11 fail but I'm not sure it's in production yet. Can you please try Electron 10?

**Comment by matteoturini** [comment]
Will test tomorrow.

**Comment by saghul** [comment]
This was fixed long time ago, we are now shipping Electron 12 no problem.
