### ISSUE TITLE
When my vpn is active then i got no video from jvb on my server, but i open https://meet.jit.si/ new tab it's working fine. Any idea??

### ISSUE THREAD

**Issue by Malik464** [jitsi/jitsi-meet#8123]
![Screenshot_2](https://user-images.githubusercontent.com/64679168/99635943-bbc2c000-2a68-11eb-95e9-4dfbebf64903.png)

**Comment by saghul** [comment]
Is the network where your server is located accessible when you are on the VPN?

**Comment by Malik464** [comment]
The VPN location is US

**Comment by Malik464** [comment]
let me check

**Comment by Malik464** [comment]
![image](https://user-images.githubusercontent.com/64679168/99665693-fd1a9600-2a8f-11eb-8be6-034ed0337231.png)
i checked with nmap through cli it's accessible. I'm using vpn chrome extension

**Comment by saghul** [comment]
I suspect the CLI will be able to access it because the VPN is not used there, since it's a Chrome extension, but not when running from within Chrome itself. Can you access it ok without the VPN?

**Comment by Malik464** [comment]
![image](https://user-images.githubusercontent.com/64679168/99670951-55a16180-2a97-11eb-962a-a8b65db25350.png)

I checked again and it works with normal vpn client and the issue is only with purevpn extension in chrome.

Strangely, our jitsi installation does not work in chrome when this extension is enabled by meet.jit.si works fine. Any ideas?

**Comment by saghul** [comment]
Is your installation on a local network? meet.jit.si is on the public internet, so you should be able to access it from anywhere. If your installation is on a private network, however, you may have the problem you're facing.

**Comment by Echolon** [comment]
@Malik464 can you response to the question?

Would you be so kind and write a proper and clear title describing the issue?

**Comment by liangguohao66** [comment]
video is not connected via VPN...
