### ISSUE TITLE
Mobile screen share not working

### ISSUE THREAD

**Issue by vinodlee** [jitsi/jitsi-meet#8124]
### Description:

Mobile screen share not working, only screen share icons showed. how can i fix this.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Mobile screen share correct behaviour.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by Echolon** [comment]
May you fill out the template a bit more?
