### ISSUE TITLE
I'm trying integrate spacedeck whiteboard with jitsi but it's redirecting me to the jitsi landing page.

### ISSUE THREAD

**Issue by Malik464** [jitsi/jitsi-meet#8125]
here is the link of spacedeck repo https://github.com/spacedeck/spacedeck-open

 jitsi is running on my own server and spacdeck running on the same server on different port. I have added the option to open the spacedeck whiteboard within jitsi menu, When I click on spacedeck login or signup , it redirects me to Jitsi's landing page.

**Comment by Echolon** [comment]
Hi, for support, please reach out to the community portal!
