### ISSUE TITLE
Can't bridge native component (iOS) 

### ISSUE THREAD

**Issue by psdevss** [jitsi/jitsi-meet#8127]
### Steps to reproduce:

1. Create a module or component in app/app.xcodeproj 
2. Use RCT_EXPORT_METHOD or RCT_EXTERN_MODULE

### Expected behavior:

No errors

### Actual behavior:

native component and native event is always null

### Server information:

- Jitsi Meet version: 2.10.0
- Operating System: macOS Catalina 10.15.7 

### Additional information:

[error][tid:com.facebook.react.JavaScript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[JitsiMeetSDK] Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by saghul** [comment]
Please paste the example code you are using. You need to add the module in the sdk target, not the app.

**Comment by psdevss** [comment]
I'm trying to implement the iOS screen share using replaykit and  HoppFoundation's implementation but I can't bridge the ScreenShareController to the react native part. Here is the sample code is an example


#import <Foundation/Foundation.h>
#import <React/RCTConvert.h>
#import "ScreenShareController.h"
#import "Project-Swift.h"


@implementation ScreenShareController

RCT_EXPORT_MODULE();

+ (id)allocWithZone:(NSZone *)zone {
    static ScreenShareController *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [super allocWithZone:zone];
    });
    return sharedInstance;
}

+ (ScreenShareController*) getSingleton {
  return [ScreenShareController allocWithZone:nil];
}

- (NSArray<NSString *> *)supportedEvents
{
  return @[@"ScreenRecState"];
}

-(void) recStarted
{
  NSLog(@"starting recording");
  [self sendEventWithName:@"ScreenRecState" body:@{@"name": @"recStarted"}];
}

-(void) recStopped
{
  NSLog(@"stopping recording");
  [self sendEventWithName:@"ScreenRecState" body:@{@"name": @"recStopped"}];
}

//stopRecording
RCT_EXPORT_METHOD(stopRecording)
{
  RCTLogInfo(@"stopping recording - from react native");
  [SocketShim closeSocket];
}

@end

**Comment by saghul** [comment]
Why are you not doing it the same way they did?

**Comment by psdevss** [comment]
I have an existing app, so I tried to copy their implementation step by step but mine doesn't seem to bridge correctly. It is alway null
