### ISSUE TITLE
Annotation/pointers on shared screens

### ISSUE THREAD

**Issue by inducer** [jitsi/jitsi-meet#8128]
**Is your feature request related to a problem you are facing?**
 
Pointing at things during group discussions of material on a screen shared by a participant

**Describe the solution you'd like**

Less ambitious:
- I can place and clear a pointer (possibly with my name) on each screen shared by myself or another participant, visible to all other participants

More ambitious:
- Multiple annotation tools (e.g. pen, eraser, line, highlighter?) let me draw on each shared screen
- Another handy tool might be more like a real-world laser pointer inherently transient, in that it does not leave a permanent mark.

**Comment by Thatoo** [comment]
That would be a very much needed option to make jitsi even more usable on professional sight.
That's a killing feature indeed (the ambitious description of the feature), maybe the only feature I was missing to switch using jitsi on regular basis for my business.

**Comment by programizer** [comment]
IMO a simple laser pointer would suffice.
xournal is better than zoom whiteboard anyway...

**Comment by Slave2WAF** [comment]
> let me draw on each shared screen
> 
> No sure, but seems that that means that EVERY participant can
> point/click/draw on someone shared screen without resharing own screen.
> 
> This will be VERY useful in education and even regular business meetings.

So very much yes.  I love Jitsi but can't dump Zoom without this.

**Comment by saghul** [comment]
I don't think this can be implemented in the browser.

**Comment by imuli** [comment]
Yeah, browser apps can't draw outside their boxes, but they could draw onto a screen shared by an android or electron client (and maybe iOS?). Doesn't look like there's an issue open on jitsi-meet-electron yet though.

**Comment by Ayko1595** [comment]
Hi! Are there any updates on this feature? This would be very helpful during meetings. 

Btw, @saghul I am curious to know why this would not work in the browser :-)

**Comment by saghul** [comment]
Nobody is working on this at the moment. As I said, I don't even know it's possible.

For this to work in the browser, or anywhere really, it would need to be a tool that allows you to draw on your own screen, which makes this independent from Jitsi altogether.

**Comment by Thatoo** [comment]
No, the idea is not to draw on the screen of the user who is sharing his screen but to draw on the top of the shared screen video like adding a layer to the shared screen to be able for anyone to comment that shared screen.

Like adding https://www.tldraw.com/ with a transparent background on the top of the screen shared flux.

**Comment by ildar** [comment]
Important, don't close

**Comment by saghul** [comment]
Closing, we have no plans to work on this.

**Comment by hhassey** [comment]
It is so sad to see this was closed, as this is a much needed feature.  I use Jitsi every day on my company.
I hope this get's done

**Comment by arslana11** [comment]
So, as of today, is the option to draw on a shared screen still unavailable?

**Comment by matti** [comment]
yes

**Comment by Laurensdc** [comment]
Would really love this option. It's invaluable for pair programming and going over any form of knowledge sharing with someone.

**Comment by WhiskerLogic** [comment]
This would be great to see implemented! We would fully switch from zoom if this became possible.

**Comment by vspinu** [comment]
As far as I can tell there is not even a way to share a pointer when screencasting from a tablet. Zoom has spotlight tool.

**Comment by KevinRossiTC** [comment]
Just noting that my org would appreciate this feature as well

**Comment by pre** [comment]
This is the one feature I miss the most from Slack. 

Even MS Teams doesn't allow you to draw on the shared screen like Slack does. Annotating the other person's display is so important when solving an issue together with a colleague!

**Comment by Mohammedabuamra** [comment]
Hi Jitsi team! 👋

First of all, thank you so much for all your amazing work on Jitsi Meet. I truly appreciate the effort, passion, and dedication you put into building such an open, secure, and high-quality platform. I really love this project and everything you do for the community. ❤️

I would like to emphasize how important the screen-annotation / pointer feature is for many of us. Having tools such as a pointer, pen, highlighter, or basic drawing options on shared screens would significantly improve collaboration, teaching, training, and presentation experiences.

This feature would be extremely valuable for our use cases, and we would be very excited to see it supported in future versions of Jitsi Meet. I sincerely hope you will consider prioritizing it.

Thank you again for your incredible work — we truly appreciate you! 🙏💙

**Comment by saghul** [comment]
A laser pointer is coming in the near future, as part of our Excalidraw update.

**Comment by abmusse** [comment]
> A laser pointer is coming in the near future, as part of our Excalidraw update.

Is there an issue tracking this that we can subscribe to?

@saghul

**Comment by saghul** [comment]
It's already available.

![image](https://github.com/user-attachments/assets/91b6a6f7-de15-4f85-9370-53bd04fb8419)

**Comment by abmusse** [comment]
Having exacali integration is awesome, I tested it and it works in the whiteboard!

I was hoping the same laser pointer was usable on a shared screen but that does seem to be a feature yet and looks like its not planned 😞 

This one of the few features Jitsi lacks (Slack, Zoom, Google has it) and its essential for pair programming and other collab sessions. Hopefully this becomes in plan in the future! 😄
