### ISSUE TITLE
Share a PeerTube Video

### ISSUE THREAD

**Issue by rg-artcom** [jitsi/jitsi-meet#8130]
Instead of "Share a Youtube Video" I would like to have a menu item "Share a Peertube Video"

See also https://joinpeertube.org/

**Comment by heikar** [comment]
Many video producers also work with vimeo.
It would be nice, if there be an interface to add (in a config file) additional video platforms (e.g. PeerTube or vimeo).

**Comment by Aspie96** [comment]
I agree, it would be great to support more platforms.

**Comment by saghul** [comment]
Duplicate of #7601
