### ISSUE TITLE
Disable Recording if User did not agree

### ISSUE THREAD

**Issue by rg-artcom** [jitsi/jitsi-meet#8131]
Topic: privacy by design, privacy by default

Do not allow recording if the user did not agree to it. The default of every user should be "I don't want to be recorded". Or find a way to exclude audio/video/desktop stream of every user  who did not agree to be recorded.

**Comment by toby63** [comment]
In general I agree, but it is of course obvious that everyone can still record it (e.g. recording the window or desktop etc.).

**Comment by fremzy** [comment]
Not sure how this is supposed to work. There's already a very distinct audible notification (in addition to the visual notification) that's played when recording is started. If at all a participant does not wish to be recorded, surely, they can turn off their mic/video. Creating a "Disable Recording" option becomes an unnecessary headache for the meeting organizer - even people who may ordinarily not mind will feel more inclined to disable. Not a useful option, IMO and it takes away from the usefulness of video-conferencing.

**Comment by saghul** [comment]
Indeed, I don't think it's a good idea to implement this. Inexperienced people may think they are safe (on account of declining the recording request), but one can use any screen recording software.

**Comment by toby63** [comment]
> Inexperienced people may think they are safe (on account of declining the recording request), but one can use any screen recording software.

Good point.
I guess the mentioned notification is a good enough method then (I have never seen it, because no one ever clicked recording in my sessions :smile: ).

**Comment by rg-artcom** [comment]
I'm not a Jitsi-developer. That means I can not code my requested feature by myself. But I still ask for the mentioned feature. Even if you can bypass it by using an additional tool, it's what I allways request by modern software: privacy by design and privacy by default.

**Comment by saghul** [comment]
We are not considering implementing this at this time, sorry.
