### ISSUE TITLE
Screen share doesn't work if blur effect enabled but camera stopped

### ISSUE THREAD

**Issue by cketti** [jitsi/jitsi-meet#8132]
### Description:

Sharing the screen doesn't work if blur effect is enabled but camera is stopped.

### Steps to reproduce:

1. Start camera
2. Enable 'blur my background'
3. Stop camera
4. Start screen sharing

### Expected behavior:

Screen sharing should work even if 'blur my background' is enabled. 

### Actual behavior:

Empty warning notification is displayed when screen sharing is started while the blur effect is enabled, but the camera is stopped. The desktop content is not displayed locally (and presumably not for remote participants either).

If the camera is started when the "share your screen" button is pressed things work as expected.

### Server information:

- Jitsi Meet version: meet.jit.si (2020-11-21 17:00 UTC, JitsiMeetJS.version = "3ed4e3caee")

### Client information:

- Browser / app version: Chrome 87.0.4280.66
- Operating System: Linux

### Additional information:

Partial stack trace:
```
[conference.js] <Object._handleScreenSharingError>:  failed to share local desktop TypeError: Cannot read property 'getTracks' of null
    at y._stopStreamEffect (JitsiLocalTrack.js:355)
    at y._switchStreamEffect (JitsiLocalTrack.js:366)
    at y.dispose (JitsiLocalTrack.js:678)
    at actions.js:587
    […]
```

https://github.com/jitsi/lib-jitsi-meet/blob/d2153eb404ddadef6d5b89ae8c499fa144280531/modules/RTC/JitsiLocalTrack.js#L355

`this.stream` is `null` when the camera is stopped.

**Comment by MaxWagener** [comment]
Same here - can reproduce the error. Did you ever find a fix for it?

**Comment by cketti** [comment]
This seems to have been fixed by https://github.com/jitsi/lib-jitsi-meet/pull/1563 :+1:

Things work fine when using Jitsi Meet 2.0.5963.
