### ISSUE TITLE
JITSI_WARTERMARK_LINK does not work properly

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#8134]
### Description:

The value in JITSI_WARTERMARK_LINK ist appended to the base URL (e.g. https://.../<JITSI_WARTERMARK_LINK>).

### Expected behavior:

The link behind the logo should be replaced with JITSI_WARTERMARK_LINK value.

### Server information:

- Jitsi Meet version: 2.0.5269-1
- Operating System: Ubuntu 20.04 LTS

**Comment by damencho** [comment]
Please when you are having questions or problems use the community forum before opening new issues, thank you.

I suspect you are skipping the `https://` part when you are setting the link.
