### ISSUE TITLE
Only YouTube ?!!? Come on Jitsi, I thought you were for OpenSource ;)

### ISSUE THREAD

**Issue by JOduMonT** [jitsi/jitsi-meet#8138]
I saw a few request of adding this or that services to being able to share and watch videos during presentation.
These kind of demand could be infinite, I means today it is YouTube, Vimeo, tommorow [PeerTube](https://github.com/jitsi/jitsi-meet/issues/8130), Bitchute, ... you name it.

### The first question I would like to address is **What is Jitsi Meet?**
It's a video chat and a competing with Skype or a conferencing application that tries to compete with Zoom ?

Because Wiki say it do both, while I'm using it for none.![image](https://user-images.githubusercontent.com/5204724/99934050-6e5b9100-2d8f-11eb-8c0b-728a266c1238.png)
None, because for the Video Chat, I found better and for the conference, it's not enough.

Personally, I think that Jitsi has a huge potential to become the alternative to Zoom, the main missing part is being able to share device and applications.

#### By being able to share a devices (SoundCard, Camera...)

- By being able to share the SoundCard I would be able to play music and speak at the same time, which is a great thing for the introduction, intermission, transition, ... (for now I need to use OBS to do this)
- By being able to share an application such as Netscape Navigator, any source of online video would be fine since all these works via the browser, but also, it could be useful for doing live demo of how to use a software and/or for streaming you playing a game.

#### Here what is looks like under Zoom

![image-153](https://user-images.githubusercontent.com/5204724/99933697-63543100-2d8e-11eb-888e-77f84ce332e5.png)

While Zoom is considered a pioneer (mainly through marketing); I believe it is possible to break his _monopole_. I tested mostly all the [alternative proposed to Zoom](https://alternativeto.net/software/zoom-cloud-meetings/) and these 2 functions are still only available in Zoom, not even Google Meet (which they planned to add them) and Microsoft Team have these functions.

I hope that my explanations are clear and that my message does not sound too arch; I understand that you are probably a small team and that it is difficult to give priority to one request more than another and that you are probably overwhelmed by all these requests. At the end, I just hope to use more Jitsi and be able to proudly promote it in the long run.

**Comment by saghul** [comment]
Everybody wants to save the world, but nobody wants to do the dishes.

Patches are welcome :-)

**Comment by toby63** [comment]
@saghul: Well you could structure this a bit more.

A clear page where you collect useful features and ask for help by the community.
Also better tracking of progress etc.

**Comment by JOduMonT** [comment]
> Patches are welcome :-)

sadly not everybody are developer, my contribution to the OpenSource Community is to use, promote, report bug and support other user.

**Comment by saghul** [comment]
Look, we try to do our best here. We are (and will never be) perfect.

@toby63 We have the feature-request label. Tracking progress doesn't work well for us, sorry.

@JOduMonT If opening issues with passive-aggressive titles is your way to help Open Source, please rethink your actions. Also when you compare things to Zoom, consider doing so when using the browser version. We use the browser and are constrained to what's available there.

I'm closing this. Please open separate issues for each feature-request.

**Comment by JOduMonT** [comment]
> passive-aggressive

@saghul I'm sorry if my title made you upset, for me it was a more cheering up in a joking way.
The title came to me because I found it amusing that an OpenSource project limits sharing to YouTube.

Maybe we don't have the same definition for different situation and obviously we don't think in the same way.
_But I must admit, my humour is sometimes awkward and we don't know each other._

For me your first reply was also kind passive aggressive, but I get over it by focussing on being constructive

> Everybody wants to save the world, but nobody wants to do the dishes.
> 
> Patches are welcome :-)

And now by closing it (simply and probably because you are upset) it kinda makes me laugh.

Of course I'll take your advice and rethink my action by spending my time on other projects which I do since the '90.

> We use the browser and are constrained to what's available there.
Sorry I thought Jitsi was based on WebRTC

@saghul Good Luck in your life
and Long Live to Jitsi

**Comment by toby63** [comment]
@JOduMonT If you do this since the 90s you should probably know, that this is mostly not the way communication works.
Though I saw your post not as aggressive, more like a "intended-to-be-funny" title.

> But my point is instead of adding on demand and one by one (PeerTube, BitChute, Vimeo, ...) why not having a big picture of the issue.

I guess thats what is now implemented with the rtmp patches:
https://jitsi.github.io/handbook/docs/faq#can-i-record-and-save-the-video
You can try to search for the exact pull request, I don't find it right now; but basically it's now possible to share the video with multiple services (Vimeo etc.) and even your own rtmp server and there is also an open issue somewhere for a local recording option.

The jitsi team might be able to improve providing a bit more recent information on their websites and to structure the information in a better and central way.

> And now by closing it (simply and probably because you are upset) it kinda makes me laugh.

I think you shouldn't see it as a childish reaction.
You named three different issues, that may deserve three different "issues" :wink:.
1. Video services: should work now already, so does not need a new issue.
2. Sharing devices
3. Sharing windows of other applications (if I understood it correctly).

@saghul Still you provoke this by saying you are the best open source project for this purpose.
Only providing support for the big companies was not really open source friendly, so a bit passive-aggressiveness, might be deserved :wink:.

**Comment by JOduMonT** [comment]
@toby63 yes it is true. interaction on Internet should blend and without emotion or polarization (but that make us more human).

for the **Sharing Devices** part, (because I opened the same kind of issue under nextcloud spreed too)
they point it would be possible only with [Chrome by using an extension](https://developers.chrome.com/extensions/desktopCapture#method-chooseDesktopMedia) if I understood well (again I'm not god, euh! a developer).
