### ISSUE TITLE
Safari on iPad not showing the mobile Deeplinking page as expected

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#8139]
### Description:

When I open a videoconference in iPad's Safari browser, I should be prompted with the **mobile deeplinking page** like this one:

<img width="689" alt="Screenshot 2020-11-23 at 11 19 33" src="https://user-images.githubusercontent.com/4049052/99945780-ed47ce00-2d7d-11eb-9ecc-df7e493e35f3.png">

**Instead**, it opens directly in the browser without giving me the choice to open in the mobile applications.

![IMG_0137](https://user-images.githubusercontent.com/4049052/99946649-60057900-2d7f-11eb-8e41-e482a2ff61e6.PNG)

Surprisingly, it works as expected in Chrome on iPad.

### Steps to reproduce:

1. Open any meet.jit.si conference on iPad in Safari
2. Click on start a conference 
3. See the lobby or conference window immediately.

### Expected behavior:

Join a conference in Safari, I expect that I will be prompted with the mobile deeplinking page where I can choose to open it in the browser or in the mobile application.

### Actual behavior:

Join a conference in Safari, I start the conference immediately, without being prompted with the mobile deeplinking page.

### Server information:

Selfhosted:
- Jitsi Meet version: stable-5142
- Operating System: debian 10

Jitsi hosted:
- Jitsi Meet version: meet.jit.si (on 23.11.2020)

### Client information:

- Browser / app version: Safari
- Operating System: iPadOS 14.2

### Additional information:

`deeplinking functions`

https://github.com/jitsi/jitsi-meet/blob/7ff41217ac21d76e0e8a502810606b82b1437713/react/features/deep-linking/functions.js#L61

`definition of isMobileBrowser`
https://github.com/jitsi/jitsi-meet/blob/202abf2a9aa2a7fedfbe3f425275a2c2baf8e374/react/features/base/environment/utils.js#L10

`definition of Platform.OS`
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/react/Platform.web.js#L8

**Comment by saghul** [comment]
Ever since the switch to iPadOS (circa iOS 13 IIRC) the Safari browser on iPads identifies itself as the desktop browser. @jallamsetty1 i have a vague memory of chatting about this with you? Do you k one of there is a reliable way to detect iPads now?

**Comment by jallamsetty1** [comment]
Oh right, we talked about using bowser to detect iPadOS, I never got around to trying it out. I will see if I can give that a quick try.

**Comment by mfts** [comment]
#8205
