### ISSUE TITLE
Red video screen for IOS apps

### ISSUE THREAD

**Issue by zvs001** [jitsi/jitsi-meet#8142]
### Description:

I always get red screen when using IOS apps.

![jitsi-red](https://user-images.githubusercontent.com/25595191/99955688-774b6300-2d8d-11eb-9e47-c9fc3294735e.png)

### Steps to reproduce:

1.  clone jitsi-meet repo (for me it is `commit e0d41a30ef7837330b0c3e07be98357a45bab6fd`)
2. use IOS app as a second participant. (appstore: 20.5.0)

Always same scenario.

### Additional information:

1) I can see video of android participant. 
2) IOS video started work, when there are 3 participants
3) when 1 of 3 participant left, video automatically breaks again after ~10 seconds.

**Comment by saghul** [comment]
Yeah this is somewhat known, not sure why it happens but it seems to only happen in the simulator. Have you seen this on a physical device?

**Comment by gauravmehta13** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/51997260/203975204-89f75a2a-4a12-4a3e-a878-235442dcd932.png">
happening in simulator for me, i cant check in real device , are you sure this is not replicable in real devices?

**Comment by saghul** [comment]
Yes.
