### ISSUE TITLE
Incorrect JVB Config on Ubuntu 20.10

### ISSUE THREAD

**Issue by fancyHeat** [jitsi/jitsi-meet#8147]
### Description:

The JVB config file is not populated correctly.

--apis=xmpp,rest in /etc/jitsi/videobridge/config in JVB_OPTS.

### Steps to reproduce:

1. Clean install on 20.10

### Expected behavior:

Should work fine

### Actual behavior:

Crashes whenever a second person joins the call

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Latest Chrome
- Operating System: Latest Windows 10

**Comment by damencho** [comment]
What is the error you see in the js console?

Please, use the community forum before opening new issues. Thank you

**Comment by fancyHeat** [comment]
On a clean install of 20.10 I believe the installer pick OpenJDK 15 however when I install OpenJDK 8 first then run the installer everything works fine.
