### ISSUE TITLE
Additional instance for wiki/Jitsi-Meet-Instances.md

### ISSUE THREAD

**Issue by TechnologyClassroom** [jitsi/jitsi-meet#8150]
https://jitsi.member.fsf.org/ could be added to the list at https://github.com/jitsi/jitsi-meet/wiki/Jitsi-Meet-Instances under United States.

```
* [fsf.org](https://jitsi.member.fsf.org/) -- ✅ -- [SSL Report](https://www.ssllabs.com/ssltest/analyze.html?d=jitsi.member.fsf.org/&latest) - Requires [FSF associate membership](https://my.fsf.org/join).
```

Handbook syntax:

`| jitsi.member.fsf.org/ |  ✅  |    |  [run SSL check!](https://www.ssllabs.com/ssltest/analyze.html?d=jitsi.member.fsf.org&latest) | Free Software Foundation |`

**Comment by saghul** [comment]
We are in the process of moving the document here: https://github.com/jitsi/handbook/pull/111#issuecomment-733090277

**Comment by TechnologyClassroom** [comment]
I updated my comment to that format.

**Comment by saghul** [comment]
Added in https://github.com/jitsi/handbook/commit/72b82a9f12bb05e9158200300e4b3d426cf1f128 cheers!
