### ISSUE TITLE
Screen Sharing not working in react native when built with latest sdk

### ISSUE THREAD

**Issue by pravasok** [jitsi/jitsi-meet#8152]
Screen Sharing option is shown, but when clicked, screen sharing is not working

Additional info:
it is happening when android sdk(2.11.0) is used with react native app

**Comment by pravasok** [comment]
we are using a similar module https://github.com/skrafft/react-native-jitsi-meet

**Comment by pravasok** [comment]
@saghul  can you please help

**Comment by saghul** [comment]
We don't maintain that plugin, please ask the author.

**Comment by pravasok** [comment]
@saghul  it is not about the package, the latest sdk when used in react native is causing the problem.
