### ISSUE TITLE
Android application freezes on start

### ISSUE THREAD

**Issue by deniss-s** [jitsi/jitsi-meet#8154]
After upgrading Jitsi Android to version 20.5.0 application shows splash screen with Jitsu logo on start and freezes. Downgrading back to 20.4.2 works fine.

**Comment by ubergeek77** [comment]
Can confirm. I actually came to this issue seeing if anyone reported the same thing. On a Pixel 3XL with Android 10.

**Comment by dakotagrvtt** [comment]
I am having the same issue. I know it's not exactly helpful to the thread but just to be a third confirmation, it freezes up even after completely wiping data from the app and starting it fresh. On latest OxygenOS (Android 10) for OnePlus 6T.

**Comment by saghul** [comment]
This is happening on F-Droid, right?

**Comment by deniss-s** [comment]
Right. Forgot to mention F-Droid.

**Comment by saghul** [comment]
This was an F-Droid build issue, fix here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7774 I expect it to land shortly and 20.5.0 being available soon after that.
