### ISSUE TITLE
Android App freeze at start since 2.5.0

### ISSUE THREAD

**Issue by mks-85** [jitsi/jitsi-meet#8157]
Hi there,

since update 2.5.0 via F-Droid app freezes at start, see screenshot. 

Delete cache and storage doesn't solve the problem. 

Happens on my Oneplus 5T with Android 10 (Oxygen OS 10.0.1) 

Uninstalled and installed 20.4.2 makes it usable again. 

![Screenshot_20201125-153809](https://user-images.githubusercontent.com/74009667/100241681-3fcaeb00-2f34-11eb-95fd-dd4fb80d2201.jpg)

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/8141#issuecomment-733635638
