### ISSUE TITLE
[Bug] Jitsi mobile SDK ignores server interface settings

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#8163]
### Description:

We user Jitsi as AV part of Rocket.Chat deployment.
Web interface works perfect.
But we have issue with mobile version of Rocket.Chat with Jitsi SDK inside.

I have a few important settings set in `interface_config.js` config file:
```
TOOLBAR_BUTTONS: [
    'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
    'fodeviceselection', 'hangup', 'profile', 'chat', 'settings', 'raisehand',
    'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
    'tileview', 'help', 'mute-everyone', 'security'
    ],
SETTINGS_SECTIONS: [ 'devices', 'language', 'moderator', 'profile' ],
```
I disabled some recording and streaming functions and calendar interface elements.
Web version works perfect and hide (disable) all that disabled in config file features,  but mobile version ignores that settings and shows all available settings, like lobby (disabled for us), recording, streaming and other.

And another one. Since last SDK update 2.10.2 Tale view is default for all calls, before that it was main focus view and our users get used to it. How can we change it back?

### Steps to reproduce:

1. Make some configuration changes in `interface_config.js` config file
2. Check that mobile version ignores it, but web version honored it.

### Expected behavior:

Mobile version should not ignore `interface_config.js` config file settings.

### Actual behavior:

Web version
![image](https://user-images.githubusercontent.com/4023037/100319954-8cb0cf00-2fd1-11eb-810c-c43d89b5edec.png)
Mobile version
![image](https://user-images.githubusercontent.com/4023037/100320619-8111d800-2fd2-11eb-9458-9b40325272cd.png)

### Server information:

- Jitsi Meet version:
jicofo/stable,now 1.0-612-1 all [installed]
jitsi-meet-prosody/stable,now 1.0.4289-1 all [installed]
jitsi-meet-tokens/stable,now 1.0.4289-1 all [installed]
jitsi-meet-web/stable,now 1.0.4289-1 all [installed]
jitsi-meet-web-config/stable,now 1.0.4289-1 all [installed]

- Operating System:
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-101-generic x86_64)

### Client information:

- Browser / app version: Chrome 87 and Rocket.Chat 4.12.1
- Operating System: Windows 10 and Android 10

### Additional information:

And also with black theme some interface elements are not visible.
@djorkaeffalexandre @diegomello please take a look at that issue.

**Comment by saghul** [comment]
> I disabled some recording and streaming functions and calendar interface elements.
> Web version works perfect and hide (disable) all that disabled in config file features, but mobile version ignores that settings and shows all available settings, like lobby (disabled for us), recording, streaming and other.

You can disable those using feature flags. We don't support interface_config.js on mobile.



> And another one. Since last SDK update 2.10.2 Tale view is default for all calls, before that it was main focus view and our users get used to it. How can we change it back?

There is no way to change that, it's the new default. You can exit tile view though and it will be remembered.

**Comment by ankar84** [comment]
> You can disable those using feature flags. We don't support interface_config.js on mobile.

How can I do it to my onw application? Is there any documentation?

> There is no way to change that, it's the new default. You can exit tile view though and it will be remembered.

Unfortunately it's not true for RCRN applications - always default settings, every single call.
@djorkaeffalexandre can you look at this?

**Comment by ankar84** [comment]
Answered https://github.com/jitsi/jitsi-meet/issues/8163#issuecomment-734142613
