### ISSUE TITLE
Participant volume resets whenever someone leaves or enters a meeting

### ISSUE THREAD

**Issue by WarpMee** [jitsi/jitsi-meet#8171]
### Description:

The individual volume controls for participants resets to 100% whenever someone leaves or enters the room.

### Steps to reproduce:

From an active meeting, set the volume of a participant to 50%. 
Have a DIFFERENT participant leave the meeting.
Witness the volume of the first participant return to 100%.

### Expected behavior:

The volume should stay the same once set. This should be the case if the participant leaves and returns, refreshes, etc. but it should definitely not change just because another unrelated participant leaves or enters.

### Actual behavior:

See steps to reproduce

### Server information:

- Jitsi Meet version: latest (https://meet.jit.si as of Nov 27, 2020)
- Operating System: Windows 7

### Client information:

- Browser / app version: latest chrome
- Operating System: same as above

**Comment by WarpMee** [comment]
It sometimes takes a few seconds for the volume to reset, so this may be related to a stream quality change routine

**Comment by fremzy** [comment]
Where are you setting/monitoring the volumes for the clients (participants)?

**Comment by WarpMee** [comment]
![vol](https://user-images.githubusercontent.com/72453105/100525856-b7e21c80-3191-11eb-94db-2a8544fada1d.jpg)

**Comment by fremzy** [comment]
I couldn't replicate this finding. I tried on different browsers (Firefox, Brave, Chromium) and the behavior was consistent - volume stayed at limit set. I just tried on meet.jit.si, for reference. It works as it should. You might want to check again to make sure you didn't overlook something.

**Comment by WarpMee** [comment]
Overlook anything like what? I'm testing on meet.jit.si. Do I really need to make a video of this to prove it?

**Comment by fremzy** [comment]
I don't know, I'm not on your system. So feel free to do whatever you feel you need to do. I'm reporting what I found. I literally just tested this - several times - trying different browsers and couldn't replicate your claim. So rather than being sarcastic, you might want to check what you're doing wrong on your end. You're the one having the problem, not me - and likely, not anyone else.

**Comment by WarpMee** [comment]
Did you try it on Chrome?

I'm not being sarcastic. I really want to know what you think I might be doing wrong.

**Comment by fremzy** [comment]
No, I don't specifically use Chrome, but I tried it on Chromium, Brave and Firefox - they all worked fine for me. Brave and Chromium, as you likely know, are variants of Chrome, so I wouldn't expect a different result if I tried on Chrome. I even tried using the Jitsi Electron desktop app and it worked there too. 

Did you just try using different tabs on Chrome or did you try using different browsers as each client?

**Comment by Echolon** [comment]
@WarpMee please upgrade from Windows 7. It is out of support already.

**Comment by WarpMee** [comment]
This is very much likely an issue with Google Chrome, and not with Windows 7.

Windows 8+ breaks randomly when automatic non-optional updates are pushed, it is not acceptable for use in any kind of work environment. If we were running Windows servers we would care, but we are not, so we'll stick with 7. Security updates are still being released, I installed one just yesterday.
