### ISSUE TITLE
Lobby module doesn't work with multiple virtual hosts

### ISSUE THREAD

**Issue by cketti** [jitsi/jitsi-meet#8173]
### Description:

Adding the `muc_lobby_rooms` module to more than one virtual host leads to the lobby functionality not working properly.

### Steps to reproduce:

1. Add a virtual host for guests (anonymous" login) to the Prosody config.
2. Enable the `muc_lobby_rooms` module for both the `jitsi-meet.example.com` and the `guest.jitsi-meet.example.com` virtual host entries.
3. Try to enable the lobby for a room.

### Expected behavior:

Moderators should be notified when new users try to request access from the lobby.

### Actual behavior:

The browser of the user who enabled the lobby isn't able to join the lobby. Somehow an invalid JID is generated.

Log excerpt from Prosody:
```
Received stanza with invalid destination JID: room@lobby.jitsi.localroom@lobby.jitsi.local/a8489ba9
```

### Server information:

- Jitsi Meet version: 2.0.5142-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Chrome + Firefox, doesn't seem to matter
- Operating System: Ubuntu 20.04

### Additional information:

I don't know what code generates the invalid JID. But since things seems to work okay when only one virtual host has the module enabled, I looked into that. Currently the hooks on the main MUC and lobby MUC components are added multiple times and they interfere with each other. After making sure the hooks are only added once, things seem to work as they should. I'll open a PR with my changes.

**Comment by damencho** [comment]
Why do we need to add it to multiple hosts, do you know? In general, it was designed to be added only to one host ...

**Comment by cketti** [comment]
Without adding the `LOBBY_IDENTITY_TYPE` identity to the host the lobby UI won't show up for users of that host. I believe the stanza filtering also needs to be added in the context of the virtual host.

**Comment by damencho** [comment]
> LOBBY_IDENTITY_TYPE

What is that?

**Comment by cketti** [comment]
https://github.com/jitsi/jitsi-meet/blob/2b6c7a51a3bfc5e94d29700e731746a97ba3fc62/resources/prosody-plugins/mod_muc_lobby_rooms.lua#L217-L218

**Comment by damencho** [comment]
I see, so it seems to me that the problem is just that even when using the guest domain the client should query the main domain for feature discovery.

**Comment by damencho** [comment]
A similar thing probably happens with speaker stats and conference duration.

**Comment by cketti** [comment]
> I see, so it seems to me that the problem is just that even when using the guest domain the client should query the main domain for feature discovery.

There's also some stanza filtering going on. I'm not exactly sure what it's for. It looks like presence messages from lobby users are only sent to moderators. Are design decision like this one documented anywhere?

You could also split the module into two parts. One providing the functionality for the MUC component and one announcing the capabilities/doing the stanza filtering on the virtual host.

**Comment by damencho** [comment]
> There's also some stanza filtering going on. I'm not exactly sure what it's for. It looks like presence messages from lobby users are only sent to moderators.

Yep, there is a filter but this is just inside the lobby room.




> Are design decision like this one documented anywhere?

Nope.



> You could also split the module into two parts. One providing the functionality for the MUC component and one announcing the capabilities/doing the stanza filtering on the virtual host.

Well, that is only one line of code. 
So the guest domain is used in just one case, and should not be used for features discovery and we should not complicate severside code and config for it. 

I will take a look at it when I have time.

**Comment by damencho** [comment]
@cketti Can you test https://github.com/jitsi/lib-jitsi-meet/tree/fix-retrieving-features, does that fixes the problem for you?

It is a [simple change](https://github.com/jitsi/lib-jitsi-meet/compare/fix-retrieving-features), always uses the main domain `this.options.hosts.domain` to query for features (`this.caps.getFeaturesAndIdentities(`).

**Comment by cketti** [comment]
@damencho: Yes, it does fix the problem for me :+1:

**Comment by damencho** [comment]
Thanks I will create a PR

**Comment by damencho** [comment]
https://github.com/jitsi/lib-jitsi-meet/pull/1428

**Comment by damencho** [comment]
This will also fix the problem for conference duration, speaker stats ... I think. Not sure about turn credentials ...
