### ISSUE TITLE
lost channel ownership after internet connection interruption

### ISSUE THREAD

**Issue by edmundlaugasson** [jitsi/jitsi-meet#8175]
**Is your feature request related to a problem you are facing?**
Lobby and other security features are brilliant and long-awaited. Unfortunately these are effective as long as initial channel creator is connected. As soon as there happens any kind of interruption, all settings are lost. Even more worse: someone else will connect first and as we know - first person on channel is its owner and can do whatever she/he wants. Many cases there are vandalism and then the vandal will have lobby rights and basically that channel is lost then for people. This is the main problem!

**Describe the solution you'd like**
There should be similar privacy and security like under [Zoom](https://zoom.us/):
* whoever starts the channel, remains the owner, regardless when she/he connects
* no one connection interruption should not take away the ownership
* only owner can manage channel, allow recording, kicking user out, mute particular or all participants except myself, decide when transmission starts/ends, etc, other participants should have only permission to participate and possibly report about user (like in [Zoom](https://zoom.us/)), but nothing more. You can freely take [Zoom](https://zoom.us/) as a good example, what privacy and security measures needs to be taken in order to remain into use.
* there should be either free webinar mode and dedicated event mode - then it is easier to distinguish just free webinar like currently and dedicated event, that requires fixed, controlled start and end + participation. This should be configurable, when creating a registered channel.
* it would be even good to configure, who can share the screen and who not - there are many vandalism acts, where the vandal participant is sharing violent, pornographic content and there is nothing to do to prevent it as vandal has ownership of the channel, because she/he connected firstly after connection interruption.

In case of having dedicated event mode allows take Jitsi Meet seriously and use it also in case of dedicated events. Currently we need to abandon Jitsi Meet in case of dedicated events due to these disadvantages, that currently exist due to missing dedicated event mode and registered channels. Dedicated event is any event, that is not between friends, who talk at evening about day impressions. As soon as there is a need to record the event, has mission critical status - it is dedicated event. To be honest, especially recently most of events are such ones. Therefore people cannot take Jitsi Meet seriously, as it does not ensure the mentioned features and doesn't prevent criminals to access events.

This actually requires username but don't see any other alternative, than personal account. Current freedom should remain but who needs permament access to registered channel, should be able to register as user and register the channel. Also who needs other restrictions, should be able to configure them and save as default per registered channel.
Certainly, when user management comes, then there should be [MFA](https://en.wikipedia.org/wiki/Multi-factor_authentication) possible to use, e.g. an app on smart device, that generates periodically a new code after short time.
Why not also support [hardware sceurity keys](https://en.wikipedia.org/wiki/Hardware_security_module) for authentication.

**Describe alternatives you've considered**
Well, [Zoom](https://zoom.us/) seems one. Actually [Cyph](https://www.cyph.com/) is more promising due to its high privacy and security + other cool features.

**Comment by saghul** [comment]
Thanks for the feedback.

I assume you have used Jitsi Meet through meet.jit.si. They are not the same thing. The latter is a deployment of the former (the project), which doesn't use authentication, it's anonymous.

You can deploy Jitsi Meet and enable authentication in such a way only authenticated users are moderators and as such have the power to kick other users, set passwords, etc. If deploying it yourself is not an option, you can try the 8x8.vc service (provided by our parent company) or some other.

**Comment by edmundlaugasson** [comment]
I have deployment in organization actually, but don't manage it my own. Does it allow all these restrictions, that I described? Also central user authentication is needed in organizations: OpenLDAP, Active Directory.

**Comment by saghul** [comment]
Yes, pretty much. When authentication is enabled (which can be configured with OpenLDAP  / AD as a backend) guest mode can be enabled too. In such environment guests can't join until a host (authenticated user) joins first, and they won't ever be moderators.

**Comment by edmundlaugasson** [comment]
This is still relevant as unsolved issue. This is the most critical issue, that keeps people away from Jitsi Meet. In organizations there is very critical to own the channel and not lose its ownership.

**Comment by damencho** [comment]
Checkout moderated.jitsi.net, solves exactly this problem on a platform without authentication.
In case of authentication you can check and subscribe for 8x8.vc. 
Im both solutions there is no such problem as loosing ownership.

**Comment by edmundlaugasson** [comment]
Good catch! So far is disturbing, that cannot choose human-friendly link, although I guess even that random hashed link remains usable in future?
 Looks like additional microservice (https://github.com/jitsi/moderated-meetings). Also some discussion about implementation https://community.jitsi.org/t/how-to-enable-moderated-meet/104947
