### ISSUE TITLE
poll feature

### ISSUE THREAD

**Issue by edmundlaugasson** [jitsi/jitsi-meet#8177]
**Is your feature request related to a problem you are facing?**
From time to time there is a need to vote over webinar over certain questions. For instance [Zoom has such poll feature](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-meetings).

**Describe the solution you'd like**
Please allow to initiate polls over Jitsi Meet session either anonymously or collecting names. Also export (save) results.
Such choice and configuring options could be under 3-dot menu in Jitsi Meet.

**Describe alternatives you've considered**
Sounds like [Zoom itself, as it has such feature](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-meetings). Or use any 3rd party questionnaire environment, that is not as comfortable and direct as poll (especially for beginners), but can basically also work.

**Comment by martinpopel** [comment]
See https://github.com/jitsi/jitsi-meet/pull/3827#issuecomment-698333629
