### ISSUE TITLE
Hide Mute Everyone and remote mute enable disable option in constant.js android sdk 

### ISSUE THREAD

**Issue by pravasok** [jitsi/jitsi-meet#8181]
Hide Mute Everyone enable disable option in constant.js android sdk 

and enable disable for remote mute

**Comment by sharafat** [comment]
Without the feature to disable the remote mute and mute everyone options, unruly kids are misusing this to mute the teachers. I'm eagerly waiting for this feature to get implemented.

**Comment by damencho** [comment]
If participants are not moderators they will not be able to mute anyone. This must be controlled from backend not from clients ...

**Comment by sharafat** [comment]
@damencho Thanks. But if one utilizes the https://meet.jit.si site, then everybody is a moderator and hence everyone gets the ability to mute anyone. This is already configurable from the Jitsi Meet iFrame API, but unfortunately not from the native SDKs.

**Comment by damencho** [comment]
This is how meet.jit.si is configured and how it works. If you want control over it you need to host it yourself or subscribe for jaas.8x8.vc.

**Comment by damencho** [comment]
We are adding a moderated part on meet.jit.si where moderators will use a separate link to join.

**Comment by sharafat** [comment]
I see. Sounds good. Thanks for your comments.

**Comment by harryadwani** [comment]
> We are adding a moderated part on meet.jit.si where moderators will use a separate link to join.

This will be great! . Waiting for updates on this.

**Comment by saghul** [comment]
This has already been deployed: https://moderated.jitsi.net
