### ISSUE TITLE
Layout broken on RTL Locale

### ISSUE THREAD

**Issue by maemunman** [jitsi/jitsi-meet#8182]
### Description:

If using a RTL locale such as farsi or arabic, the calendar view is empty, and the sidebar doesn't appear when you swipe in.  Rather than showing the sidebar, the whole screen just darkens a little.

### Steps to reproduce:

1.  Change android locale to farsi (or arabic) in settings
2.  Go into jitsi
3.  Observe missing calendar events
4. Try to open the sidebar menu thing
5. :(

### Expected behavior:

In english, there are calendar events, and it's possible to get into settings and everything

### Actual behavior:

No sidebar.  No calendar events.  Try to bring out the sidebar, and the screen just darkens a little— no sidebar.

In english:  
![Screenshot_20201128-125646_Jitsi Meet](https://user-images.githubusercontent.com/32847759/100525001-62e6dc00-317a-11eb-83f6-7f5a2b9e32c1.jpg)
![Screenshot_20201128-125650_Jitsi Meet](https://user-images.githubusercontent.com/32847759/100525002-64180900-317a-11eb-9710-f802853bc8b9.jpg)

In farsi: 
![Screenshot_20201128-125623_Jitsi Meet](https://user-images.githubusercontent.com/32847759/100525019-71cd8e80-317a-11eb-9d35-86385cb1be9a.jpg)
![Screenshot_20201128-125628_Jitsi Meet](https://user-images.githubusercontent.com/32847759/100525021-72662500-317a-11eb-9649-2325e2ab1e0f.jpg)

### Server information: Default meet.jitsi.com or w/e it is.

- Jitsi Meet version: Idk
- Operating System: Idk

### Client information: Android app

- Browser / app version: Latest fdroid 20.5.0
- Operating System: Android 10

### Additional information:

God bless.  Y'all doing amazing things over here.

**Comment by maemunman** [comment]
Álou, this shouldn't be wontfix.  I admit it's a stale bug report, but I'm at a loss to explain why.

**Comment by maemunman** [comment]
mostly fixed in latest update.  I still don't see anything in the calendar tab, but the menu is working

**Comment by ali-alhaidary** [comment]
Never knew that there is calendar in jitsi-meet. From were it is accessed?

**Comment by saghul** [comment]
It just reads the system calendar and looks for meeting links (if permission is granted).
