### ISSUE TITLE
 where can I get the video stream

### ISSUE THREAD

**Issue by WSX1994** [jitsi/jitsi-meet#8190]
hi!When using jitsi meeting to turn on the camera, where can I get the video stream of every frame delivered by the camera in Android.

**Comment by saghul** [comment]
This is not possible, sorry. You'd need to implement your own VideoSink similar to this: https://github.com/react-native-webrtc/react-native-webrtc/blob/d9525740b1e2b703d6b7362e052d5f058e25403b/android/src/main/java/com/oney/WebRTCModule/VideoTrackAdapter.java#L69

**Comment by WSX1994** [comment]
> This is not possible, sorry. You'd need to implement your own VideoSink similar to this: https://github.com/react-native-webrtc/react-native-webrtc/blob/d9525740b1e2b703d6b7362e052d5f058e25403b/android/src/main/java/com/oney/WebRTCModule/VideoTrackAdapter.java#L69

In jitsi meeting, are Android's SDK and IOS framework generated respectively through the library in react native, because I don't see that jitsi meeting project has a reference to webrtc in Android

**Comment by saghul** [comment]
Yes, both SDKs are built using React Native.

**Comment by WSX1994** [comment]
Well，i konw ，thank you

**Comment by WSX1994** [comment]
> Yes, both SDKs are built using React Native.

Well，i konw ，thank you

**Comment by WSX1994** [comment]
> Yes, both SDKs are built using React Native.

Hi，Under webrtc in jitsimeeting VideoTrackAdapter.java In Android, does every frame call back the onframe (videoframe frame) method? If not, where are the callback method and data of each frame

**Comment by saghul** [comment]
Yes, every video frame calls that adapter. If you want to do something with video frames you'd need to create your own adapter at that level.

**Comment by WSX1994** [comment]
> Yes, every video frame calls that adapter. If you want to do something with video frames you'd need to create your own adapter at that level.

If I create my own adapter, how can I associate it with my jitsimeeting in Android through react native？

**Comment by WSX1994** [comment]
> Yes, every video frame calls that adapter. If you want to do something with video frames you'd need to create your own adapter at that level.

I can't print log in frame method of adapter in Android. Where can I get the value of videoframe of this method and print log

**Comment by saghul** [comment]
The `onFrame` method is called with every video frame, and it gets a video frame as an argument.

**Comment by WSX1994** [comment]
> The `onFrame` method is called with every video frame, and it gets a video frame as an argument.

I add a log to the onframe method, and then run jitsimeeting. In Android, I find that there is no print information
