### ISSUE TITLE
[Admin mute] admin can mute camera, micriphone and it cannot be unmumted by the participant

### ISSUE THREAD

**Issue by bharath-naik** [jitsi/jitsi-meet#8202]
**Is your feature request related to a problem you are facing?**
Yes, which i call it as admin mute

**Describe the solution you'd like**
I am a professor, i love jitsi very much, i often organize debates among students from different university, some times i live stream jitsi in auditorium style, in such situation the need arises that some participants be muted (either by camera or microphone), such that they can't Unmute themselves, if they want to, they can raise hand , 

if admin needs {'Admin Unmute'} then the admin Unmuted participant can be muted  or Unmuted

This is really a new and would be very exciting feature in jitsi, Because i will be organizing a big event in few months on weekly basis. idk wheather anyone accepts my feature request or not, but jitsi is good and a nice open source solution :)

**Describe alternatives you've considered**
 I didn't check any other alternative.  but people said there is an option or whatever called feature in Cisco WebEx that host can unmute or mute anyone in the room.

**Comment by saghul** [comment]
We are implementing that functionality in https://github.com/jitsi/jitsi-meet/pull/7779

**Comment by bharath-naik** [comment]
Wow, that's really cool,  I guess i have a small question that will admin separately mute camera sometimes and sometimes separately microphone, depending on the situation, here is the scenario that

**Scenarios:**
1.  For Debate like, i need the participants  camera turned on, but want audio mute, who is not having the speaking rounds.
2.  A Discussion panel is accepting questions from audience, the audience camera should always be muted.
It is very very convenient feature for all the users.
