### ISSUE TITLE
Cannot deeplink into a conference on iOS if the iOS app is "forced closed" 

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#8203]
### Description:

I want to deeplink into the Jitsi Meet iOS application when I'm join a conference on mobile. However, if the Jitsi Meet app is not already running, the deeplink will only bring me to Jitsi Meet app and not the actual conference I'm trying to join.

### Steps to reproduce:

1. "Force close" Jitsi Meet iOS App
2. Click on any link (e.g. meet.jit.si/ios-deeplink-force-close-test) on mobile Safari
3. Click on "Join this meeting using the app"
4. Click on "Open in Jitsi Meet"
5. Redirect to the Jitsi Meet app; **but it fails to redirect to the conference "ios-deeplink-force-close-test"**

### Expected behavior:

Click on Open in Jitsi Meet app, and I get redirect to the conference regardless whether the Jitsi Meet app was opened recently or force closed (i.e. not in recent applications)

### Actual behavior:

Redirected to Jitsi meet app correctly, but not redirected inside the conference I wanted to go

### Server information:

- Jitsi Meet version: latest meet.jit.si (03. dec 2020)
- Operating System: latest meet.jit.si (03. dec 2020)

### Client information:

- Browser / app version: 20.5.0 build 96
- Operating System: iPhone 11 Pro; iOS 14.2

**Comment by saghul** [comment]
Thanks for the report, we'll take a look.

**Comment by saghul** [comment]
Fixed it in master. A new beta will go out today. Thanks a lot for the report!
