### ISSUE TITLE
Request: audio-only recording option

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#8208]
I would like to sometimes recording audio-only, hoping that it would use less bandwidth and smaller file sizes. For some types of meetings, video content is not worthwhile enough for the extra data use.

I could just record locally the streams and that's fine, but a standard approach might end up higher quality and more convenient.

**Comment by fremzy** [comment]
So are you saying you want to host a meeting with video content BUT only want to record the audio from that meeting?

**Comment by wolftune** [comment]
Yes, exactly

**Comment by fremzy** [comment]
You can use the "Local recording" feature - each participant will activate it on their end and at the end of the meeting, they'll send you the recorded audio files. This gives you the highest quality audio from your meeting.

**Comment by wolftune** [comment]
You mean like each participant uses their own software to record their own audio input right? Not that "local recording" is a feature in Jitsi itself, right? (I'm not aware of such a feature).

I agree that everyone recording locally is the best way to get a publishing-quality audio mix.

But there's another use case: people have a bureaucratic meeting like some organizational procedural thing. They want to see each other during the meeting. And they just want a low-size audio recording in order to have a record that may not even ever get published or listened to. They just want something quick and easy and no extra hassle of mixing multiple recordings.

**Comment by fremzy** [comment]
No, each participant records with Jitsi. Jitsi has a "Local Recording" feature that you can make available, if you're hosting your own server. The feature allows each participant on a call to record audio during the call. You enable it in config.js - https://github.com/jitsi/jitsi-meet/blob/5cae5985c00fd8604d35eaadf2bde92ef0774dc8/config.js#L525

![dcdb780606656f4a0dda417adb388720919ed6f9](https://user-images.githubusercontent.com/63688942/101274096-367a2380-3769-11eb-974b-6e2ea0b9540c.png)


Once enabled, clicking the button will bring up this pop-up where they (participants) can start the recording:

![cd2379b1f50df8cf503fe34fc048edbf58ee20b6](https://user-images.githubusercontent.com/63688942/101274069-fe72e080-3768-11eb-998f-492ae16b2ccc.png)

**Comment by pratik9722** [comment]
But that way you can only record your own voice. how can jitsi frontend combine everyone's voice into one file?

**Comment by saghul** [comment]
We don't have that functionality at the moment, but it can be implemented with the WebAudio or MediaRecorder APIs.

**Comment by wolftune** [comment]
Hi bot, status remains, worth still doing IMO

**Comment by wolftune** [comment]
I still say this should happen, and I'd rather a won't-fix decision (or better fixing it) rather than just going stale

**Comment by saghul** [comment]
We are not planning on adding this feature at this time, sorry.

**Comment by luponata** [comment]
Hey @wolftune, i made a custom build specifically for this

One of my customer also wanted to just record audio in a conference

https://github.com/luponata/jibri_audio_only

Cheers

**Comment by wolftune** [comment]
Thanks @luponata

Please if you ever devise it as a flexible option that can be adjusted per-session by users, submit it as a PR.

For my purposes, I use video enough that the permanent audio-only is not worthwhile.

**Comment by luponata** [comment]
Internally we usually use JWT, maybe we could implement a new option in the body of the JSON that instruct Jitsi to use the  audio-only version while creating the room.

{
"room": "jitsi-room",
"operator": "operator1",
"epoch_start": 1631628667,
"epoch_end": 1651628667,
"audio_only": true
}

In our instance nobody can't open a room before the JWT run, is this your case?

**Comment by wolftune** [comment]
Would there be a front-end user-facing simple method to choose the setting for a room each time it is made?

**Comment by stevennt** [comment]
Someone's problem is someone else's solution? https://stackoverflow.com/questions/72446551/jibri-records-audio-only-without-video

Not a real solution but something worth investigating to find a hack to audio-recording only?

**Comment by saghul** [comment]
A simple hack would be to extract the audio from the video in the finalize script.

Granted that means you might be recording video unnecessarily, but adding another type of recorder would require a lot of changes...
