### ISSUE TITLE
Failed to get the config.js file in some android devices

### ISSUE THREAD

**Issue by ips-illuminz** [jitsi/jitsi-meet#8220]
Hey guys,

I'm getting the error to load the config.js file in some android devices, the app is getting crashed. I have tried to access the url through web and it seems working fine, also through web view in mobile device, it is also working. 

Unable to find the exact issue, I'm getting the following error while starting the meeting.

`from https://meet.example.com/config.js?room=5fcf47cf9595c61a6d8134f5 Error(TypeError){"message":"Network request failed","stack":"onerror@index.android.bundle:137:7285\ndispatchEvent@index.android.bundle:128:5676\nvalue@index.android.bundle:123:6095\nvalue@index.android.bundle:123:2835\nvalue@index.android.bundle:49:1280\nvalue@index.android.bundle:36:3685\nindex.android.bundle:36:841\nvalue@index.android.bundle:36:2939\nvalue@index.android.bundle:36:813\nvalue@[native code]"}
2020-12-08 15:27:06.629 30768-31840/com.gigipo.dev E/JitsiMeetSDK: [features/base/lib-jitsi-meet] Failed to load config from https://meet.example.com/config.js?room=5fcf47cf9595c61a6d8134f5`

Thanks,
Inder

**Comment by saghul** [comment]
What type of TLS certificate does your domain have?

**Comment by ips-illuminz** [comment]
HI @saghul , I'm using default SSL certificates of Letsencrypt, I have docker image installed on the server and i'm through it. It is accessing by web url with secure route (https), but in some android phone it is giving error and build is getting crashed

**Comment by saghul** [comment]
Can you share your config.js ? There might be some logic error there...

**Comment by ips-illuminz** [comment]
Please check the attached file https://ctxt.io/2/AACgosxBEg

**Comment by ips-illuminz** [comment]
Hi @saghul , any comment on the file , re-sharing the file with you: https://we.tl/t-AvmDtyqFzz

**Comment by saghul** [comment]
I cannot see any obvious error. Can you check if you see any errors on the Android side with `adb logcat` ?

**Comment by ips-illuminz** [comment]
Sure @saghul, I will share the logcat with you, because whenever i'm starting meeting the app is getting crashed with the error of "Network request failed" for config.js file

**Comment by ips-illuminz** [comment]
Hi @saghul , I have installed a fresh copy of jitsi docker image on my development server and it's still giving me the same issue on some devices, i'm sharing a logcat file with you, please let me know what could be the issue?
[logcat.txt](https://github.com/jitsi/jitsi-meet/files/5672573/logcat.txt)

**Comment by ips-illuminz** [comment]
Hi @saghul , can you please help me to identify the issue? It really urgent and due to this we can't go live, let me know if other ssl certificates can help us to sort out this issue?

**Comment by saghul** [comment]
What okhttp version are you using in your project? Jitsi Meet (through React Native) requires version 3.12 and looks like you might be using a more recent one and RN is throwing exceptions about it.

**Comment by ips-illuminz** [comment]
Hi @saghul , We are using Retrofit with coroutines and the older version of retrofit doesn't have coroutines support, that is using okhttp as a dependency, so we can't downgrade it please find us some solution. So that we can make it this build work with latest android version. Thanks

**Comment by saghul** [comment]
Sorry I don't know of a solution to this.

**Comment by ips-illuminz** [comment]
Okay @saghul , Thanks for your help, but we are using the same android okhttp version from last 6 months, but the react build was working fine without any issue, it's started happening after 15 Sep, before everything was fine with the server. We have tried the build with Jitsi server and it also seems working fine but the problem is only with our domain, i have tried multiple versions on our side but nothing seems to be working.

**Comment by RaymanMartin** [comment]
Have the same problem. After some normal calls between two participant and then the receiver reject several times. 
That happen again

**Comment by Createst** [comment]
@ips-illuminz hi,I have same issue。how do you resolve it?Thanks

**Comment by ips-illuminz** [comment]
@Createst I had resolved this issue by using okhttp version inside build gradle file.

Path: **android/sdk/build.gradle**

```
implementation 'com.squareup.duktape:duktape-android:1.3.0'
implementation 'com.squareup.okhttp3:okhttp:3.4.1'
```

Please cross verify at your end if you have SSL configured or not.

**Comment by Createst** [comment]
@ips-illuminz  Thanks for your help,。
I donnot resolve it。I do not config jitsi meet server and config ssl。
please help me how to config meet server？thanks

**Comment by Createst** [comment]
hi，how to depploy it at centos?
| |
王军
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/11/2021 ***@***.***> wrote：

@Createst I had resolved this issue by using okhttp version inside build gradle file.

Path: android/sdk/build.gradle

implementation 'com.squareup.duktape:duktape-android:1.3.0'
implementation 'com.squareup.okhttp3:okhttp:3.4.1'


Please cross verify at your end if you have SSL configured or not.
