### ISSUE TITLE
VideoTrackAdapter

### ISSUE THREAD

**Issue by WSX1994** [jitsi/jitsi-meet#8221]
Hi，Is the data in the onframe method of the videotrackadapter local data or remote pushed video data

**Comment by saghul** [comment]
It's remote pushed data. Such adapter can be added to any track really.

**Comment by WSX1994** [comment]
> It's remote pushed data. Such adapter can be added to any track really.
Where can I get the local data？

**Comment by saghul** [comment]
The adapter is generic, you can attach a local track to it too. We don't because our adapter is designed to detect remote mutes only.

**Comment by WSX1994** [comment]
> The adapter is generic, you can attach a local track to it too. We don't because our adapter is designed to detect remote mutes only.

Are there remote and local frame data in JS in react native
