### ISSUE TITLE
Not able to build ios SDK with Reac-Native-Analytics

### ISSUE THREAD

**Issue by tanaev** [jitsi/jitsi-meet#8225]
When building SDK with Reac-native-analytics using xCode 12 I getting next error

`/jitsi/node_modules/@segment/analytics-react-native/ios/RNAnalytics/RNAnalytics.h:12:9: 'React/RCTBridgeModule.h' file not found
`
Most probably this is because Reac-Native-Analytics required reac-native at least 0.62.0

Any thoughts on how to fix this error?

**Comment by saghul** [comment]
I don't know, never tried to use that module. We are currently using RN 0.61.

**Comment by Echolon** [comment]
I will close this for reasons of being out of scale to my understanding. Please refer to the Jitsi Community Portal.
