### ISSUE TITLE
Running on Apache

### ISSUE THREAD

**Issue by snc-klause** [jitsi/jitsi-meet#823]
Hi there,

I llike to run Jitsi Meet on Apache instead of NGNX, but all configurations I have found so far just brings me to a Jitsi Meet website without any function. 
Apache is a common used web server, so I assume you guys already have a running solution for this? 
Thanks.

**Comment by nicolas-san** [comment]
I just finished to install jitsi-meet with apache,
the basic setup works fine, but I have trouble to use the jicofo secure domain : https://github.com/jitsi/jicofo#secure-domain
I think it may be related to the rewrite rules, but I'm not sure

Let me know if it's ok for you :)

<VirtualHost *:80>
    ServerName conference.example.com
    DocumentRoot "/var/www/path/to/jitsi-meet"

    SSLProxyEngine On
    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^/[a-zA-Z0-9]+$
    RewriteRule ^/(.*)$ / [PT]
    RewriteRule ^/http-bind$ https://conference.example.com:5281/http-bind [P,L]

</Virtualhost>

<VirtualHost *:443>
    ServerName conference.example.com

    DocumentRoot "/var/www/path/to/jitsi-meet"

    SSLProxyEngine On
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/ca.crt
    SSLCertificateKeyFile /etc/apache2/ssl/ca.key

    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^/[a-zA-Z0-9]+$
    RewriteRule ^/(.*)$ / [PT]
    RewriteRule ^/http-bind$ https://conference.example.com:5281/http-bind [P,L]

</Virtualhost>

**Comment by AndyNormore** [comment]
Please note if you are using CloudFlare SSL for HTTPS connections - this will NOT WORK. 

You must purchase and install your own SSL certificate on either NginX or Apache to get working. There is absolutely NO WAY it'll work with CloudFlare, which I think is costing people a lot of time and frustration.

**Comment by alfredogt** [comment]
I'm having the same problem,
I would like to disable ssl and enable it from CloudFlare ... 
Is it possible?
How?

Thanks.

**Comment by AndyNormore** [comment]
Hi Alfred, just click the Cloud Icon on your CNAME which is pointing to your server.

So you end up with name servers pointing to CloudFlare, that's fine. I have a subdomain for Jitsi. Just click toggle the CloudFlare icon, which is orange. Now cloudflare will send connections STRAIGHT to the origin IP. Opens you up to DDOS to your origin, which sucks.

It's working for me, come check out www.SkyRooms.IO - it's running through CloudFlare (click the demo link). Ez.

**Comment by saghul** [comment]
Folks, I'm going to close this since there is nothing actionable on our side. The Debian packages also work with Apache, and we do provide standalone examples: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example-apache

Using CloudFlare or not is out of scope here.

If you run into issues please join the mailing list and let's have a discussion there :-)
