### ISSUE TITLE
React-native-file-Picker is not working with android build

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8235]
Hi, i have implemented React-native-file-Picker in Jitsi Code, it works on ios but in android it is throwing null exception. picker is not at all opening. any answers ll be very useful.

**Comment by saghul** [comment]
Without any logs it's impossible to help you.

**Comment by sachinhunasnale** [comment]
Hi saghul, 
  i am facing following error for all document picker libraries i have installed
  **typeerror cannot read property of pickimage of null react native**
i have tried with react-native-file-picker, react-native-document-picker, Image Picker libraries. 
in all cases its throwing null exception only in android build, but with iOS its working fine.
