### ISSUE TITLE
Android: white screen on app launch

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#8237]
White flash burns eyes:
![ScreenRecord-2020-12-12-02-15-23](https://user-images.githubusercontent.com/14617699/101963619-30c88600-3c20-11eb-9eea-60461f72e335.gif)
For example other apps like Orgzly, Binary Eye or Car Report has no flash.
v20.0.5, android 10

**Comment by saghul** [comment]
Are you reporting a UI glitch or does the app not work at all?

**Comment by 532910** [comment]
UI glitch

**Comment by 532910** [comment]
Dear stale bot, please go away

**Comment by 532910** [comment]
still actual

**Comment by saghul** [comment]
@tmoldovan8x8 can you please check if the change you made to delay the splash screen a tad solves this?
