### ISSUE TITLE
Allow users to change their password

### ISSUE THREAD

**Issue by mdosch** [jitsi/jitsi-meet#8238]
I have room creation restricted to authenticated users. Right now I create users and send them the password but they can't change it which is a bit ugly.
As xmpp allows users to change passwords this could also be integrated in jitsi-meet, so that authenticated users can change their password.

**Comment by pratik9722** [comment]
Prosody supports XMPP's in-band registration standard, which allows users to register with an XMPP client from within their client and change their passwords. While this is convenient for users it does not allow administrators to moderate the registration of new users. As such, the register module is enabled in the default configuration but allow_registration is set to false. This allows existing users to change their passwords from within their client but does not allow new users to register themselves.

Please read this
https://wiki.archlinux.org/index.php/Prosody

**Comment by mdosch** [comment]
Thank you for your comment but that's not what I mean. I am very aware 
of the modules and settings needed to allow users to change passwords 
from within their XMPP client as I am running a prosody for 7 years now.

I am asking for password changing from within jitsi-meet as not all 
users of jitsi-meet are using XMPP and therefore don't have an XMPP 
client to change their passwords. Furthermore you don't have the 
possibility to do so if you use the docker bundle without exposing the 
prosody to the outside (which I am doing since integrating jitsi-meet 
with my prosody became troublesome and jitsi-meet broke my nginx and 
coturn config).

**Comment by saghul** [comment]
This is tricky because Jitsi Meet (the front end) doesn't know (or care really) about what authentication mechanism you used. If JWT tokens or LDAP or any other auth mechanism supported by Prosody is used, there is no way to change the password.

**Comment by mdosch** [comment]
Maybe a setting to tell the frontend that prosodys internal auth is used might do it? If you use other auth mechanism as LDAP you won't need this feature anyway.
