### ISSUE TITLE
Cannot choose an application window to share (Firefox and i3)

### ISSUE THREAD

**Issue by kozross** [jitsi/jitsi-meet#8239]
### Description:

I am using Jitsi Meet (as per [the site](https://meet.jit.si/)), in Firefox on i3. I want to share a specific application window (say, my terminal emulator). However, when I go to select it, I don't get this option. Instead, my only choices are:

* The browser; and
* The entire screen.

This seems to be related to i3 workspaces - I can select an application window to share if and only if it's in a workspace which is currently displayed on a monitor.

### Steps to reproduce:

1. Spin up a room on [the site](https://meet.jit.si/).
2. Click on the 'Share your screen' button.
3. Behold your list of options and lament.

### Expected behavior:

I should be able to select applications running in _any_ workspace.

### Actual behavior:

I can only select applications running in a workspace that's currently visible on a monitor.

### Server information:

- Jitsi Meet version: Whatever version [the site](https://meet.jit.si/) uses (last checked December 13th 2020).
- Operating System: Whatever OS [the site](https://meet.jit.si/) uses (last checked December 13th 2020).

### Client information:

- Browser / app version: Firefox 83.0
- Operating System: Arch Linux

### Additional information:

I am using the i3 window manager, version 4.19.

**Comment by Jookia** [comment]
I wonder if this is an inherent limitation of non-compositing X11 window managers? Instead of keeping an off-screen buffer of the applications, the applications are not drawn at all.

**Comment by damencho** [comment]
This part of the screen sharing is implemented in the browser and there is nothing we can do about it. 
You better search the mozilla bugs and if that does not exist file it there. Thank you.
