### ISSUE TITLE
allow to send user back to lobby

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#8241]
The new lobby feature is really nice. We would like it for jury meetings where it is sometimes necessary, to send a person out of a conference and get it back again later.

A moderator should be able to send a user back to the lobby and invite him/her later again to the meeting.

Use cases: A jury is  judging on a grant and the representative of the organization is asked to wait and get back when the decision has been made. Or if a person has a conflict of interest on a specific issue being discussed.

**Comment by ThomasRolland** [comment]
@damencho can u know, how we can do that ? :)

**Comment by damencho** [comment]
There is no such feature at the moment. 
You need to experiment and see will that work: the moderator can kick it from the UI and the logic will modify the room config removing that participant jid from the config ... and see whether that will automatically kick it from the meeting and whether you will need to do and some more changes when that participant detects it to go back to the lobby ... so it is modifying the UI in jitsi-meet to add such and option next to the kick and modifying lobby API and handling in lib-jitsi-meet.

What about if you just kick the participant, when that participant tries to join it will land again in the lobby.

**Comment by ThomasRolland** [comment]
@damencho thanks for your reply.
Ok and can we just cut off the sound and the video from other user. with that the user cannot hear and show somethings.

This can be do?

**Comment by damencho** [comment]
Not as easy as the signaling part ... and that can lead to more unknown problems when you try to enable it ...

**Comment by mustahsin64** [comment]
@ThomasRolland , have you enabled this feature? and how
