### ISSUE TITLE
Implementation of a toggleFullScreen functionality for the IFrame API

### ISSUE THREAD

**Issue by zeuscronos** [jitsi/jitsi-meet#8244]
**Is your feature request related to a problem you are facing?**

It is not a problem, it is something that I think is a common use case.

**Describe the solution you'd like**

In a similar way to you example for: `toggleLobby` on your [IFrame API Guide](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe), it would be very interesting to have the ability to do something like the following:
```
api.executeCommand('toggleFullScreen', true);
```
that toggles the `Full Screen` mode `On / Off`.

**Describe alternatives you've considered**

I think I don't have too much more alternatives than the implementation.

I posted a question about it on:

https://community.jitsi.org/t/how-to-implement-a-togglefullscreen-functionality-for-the-iframe-api/88122

Thanks!

**Comment by duerrsimon** [comment]
I second that this would be very useful!

**Comment by johnwry** [comment]
+1

**Comment by KaloyanYosifov** [comment]
+1
