### ISSUE TITLE
file picker not workin in android

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8245]
Hi saghul,
i am facing following error for all document picker libraries i have installed
typeerror cannot read property of pickimage of null react native
i have tried with react-native-file-picker, react-native-document-picker, Image Picker libraries.
in all cases its throwing null exception only in android build, but with iOS its working fine.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
You need to manually link it by putting it with the rest of the packages in ReactInstanceManagerHolder.java

**Comment by Dphilomath** [comment]
In ReactInstanceManagerHolder.java, 
`import com.filepicker.FilePickerPackage; `
throws an error 

>  error: package com.filepicker does not exist
