### ISSUE TITLE
Packages/Libraries null in Android studio

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8246]
Hi, if i install any library or add package manually in android studio, its remaining null after running with react-native run-android. can i do any changes with the code.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
You need to add it to ReactInstanceManagerHolder.java
