### ISSUE TITLE
JitsiMeetSDK: [features/mobile/pip] Error entering PiP mode: Error: enterPictureInPictureMode: Current activity does not support picture-in-picture.

### ISSUE THREAD

**Issue by raviraj17apr** [jitsi/jitsi-meet#8247]
Hi Team,

Currently picture-in-picture is not working in android. 
Getting the below error continuously

**JitsiMeetSDK: [features/mobile/pip] Error entering PiP mode: Error: enterPictureInPictureMode: Current activity does not support picture-in-picture.**

Settings as suggested in AndroidManifest.xml file
     <activity android:name=".JitsiOnlineConferenceActivity">
            android:label="@string/app_name"
             android:configChanges="screenSize|smallestScreenSize|screenLayout|orientation"
             android:launchMode="singleTask"
             android:resizeableActivity="true"
            android:exported="true"
            android:supportsPictureInPicture="true"
            android:windowSoftInputMode="adjustResize">>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

Activity file
=================

public class JitsiOnlineConferenceActivity extends FragmentActivity  implements JitsiMeetActivityInterface, JitsiMeetViewListener {
    public static final String TAG = "JitsiOnlineConferenceActivity";
    private static final int OVERLAY_PERMISSION_REQUEST_CODE
            = (int) (Math.random() * Short.MAX_VALUE);
public  JitsiMeetFragment fragment;
    public URL serverURL;
    public JitsiMeetConferenceOptions defaultOptions;
  
    protected JitsiMeetView getJitsiView() {
        fragment
                = (JitsiMeetFragment) getSupportFragmentManager().findFragmentById(R.id.myjitsiFragment);

        if(fragment !=null) {
            return fragment.getJitsiView();
        }

        return null;
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        intentArguments = ((IntentArguments) getApplicationContext());
        setContentView(R.layout.activity_jitsi_online_conference);

        getJitsiView().setListener(this);

        if (extraInitialize()) {
            initialize();
        }
    }

**Comment by saghul** [comment]
What device are you running this on? What Android version does it run? Does Jitsi Meet (our app) do PiP successfully?

**Comment by raviraj17apr** [comment]
@saghul thanks for your quick reply.

this problem with all kind of android devices. I am using OnePlus 6T with latest android 10.

The android sdk build version is 29.
This problem is there when i am using JitsiFragmentActivy as we have full functionality avaible with this as "join", "leave" etc. but PIP and "Start Screen Sharing" both functionality is not working here. but when we use JitiMeetActivity, all functionality is working.

As we can not access other functions of JitsiMeetActivity except "launch" , we are using JitsiMeetFragment here

**Comment by raviraj17apr** [comment]
i have closed this issue by mistake. re-opening this again.
Please find my reply in previous thread.

**Comment by saghul** [comment]
Generally speaking we recommend extending JitsiMeetActivity. Any reason why you're not doing that?

**Comment by raviraj17apr** [comment]
I am using JitsiMeetView 
=====================================
layout xml file
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".JitsiOnlineConferenceActivity">
    <fragment
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:name="org.jitsi.meet.sdk.JitsiMeetFragment"
        android:id="@+id/myjitsiFragment"/>
</FrameLayout>

=======================
.java class...
.......
   protected JitsiMeetView getJitsiView() {
        JitsiMeetFragment  fragment
                = (JitsiMeetFragment) getSupportFragmentManager().findFragmentById(R.id.myjitsiFragment);
        if(fragment !=null) {
            fragment.getJitsiView().enterPictureInPicture();
            return fragment.getJitsiView();
        }
        return null;
    }
..........

So why jitsimeetview is not supporting this ?

**Comment by raviraj17apr** [comment]
Thanks for support.

The issue is resolved with existing implementation only. I have not extended JitsiMeetActivity.  I am using JitsiMeetView only

Thakns & reg,
Ravi

**Comment by baijianghai** [comment]
Hello 
I have same this problem, My Simple Activity Extends Fragment Implement JitsiMeetActivityInterface, JitsiMeetViewListener 


Please Help me @raviraj17apr 
Thanks

**Comment by raviraj17apr** [comment]
@baijianghai is your issue solved now? sorry for late reply. i haven't checked github from many months

**Comment by vphutane27** [comment]
Hey @baijianghai I am also facing the same issue could you please let me know your solution
