### ISSUE TITLE
18n language detection in IOS browsers - Safari / Chrome

### ISSUE THREAD

**Issue by ThoBur** [jitsi/jitsi-meet#8261]
### Description:

Jitsi Meet don't detect the correct language on IOS in Safari and Google Chrome. Jitsi always uses english for the main and deeplinking page. Android works fine. Only when i use the following lines to force the ui language, it works for me.

/usr/share/jitsi-meet/interface_config.js
`LANG_DETECTION: false,`

/etc/jitsi/meet/*-config.js
`defaultLanguage: 'de',  `

### Steps to reproduce:

Use the main and deeplinking page on IOS devices - Safari / Chrome

### Expected behavior:

The site should detect the browser language correctly. In my case german.

### Server information:

- Jitsi Meet version: 2.0.5142-1
- Operating System: Ubuntu 18.04.5 LTS

### Client information:

- Browser / app version: Safari / Chrome
- Operating System: IOS 14.2

**Comment by ocarreterom** [comment]
Checking the `lookup` function these are my conclusions: https://github.com/jitsi/jitsi-meet/blob/cecf324023f5a810fb97f7d55d7eb72785de41a4/react/features/base/i18n/customNavigatorDetector.js#L21

`navigator.languages` returns different data depending on browser.

```js
// Safari 14
lookup() // ["eses", "eses"] - Not exists

// Chrome 88
lookup() // ["es", "en", "esES", "es"]

```
