### ISSUE TITLE
Galician translation

### ISSUE THREAD

**Issue by xosecalvo** [jitsi/jitsi-meet#8262]
There's no Galician translation.

I'd like to volunteer. I've been reading the discussions that have taken place this year (Weblate, Crowdin...) and I've (maybe incorrectly) figured out that translations are done here.

Could Galician be included in the translated languages and could I be given the required permissions to start this task?

**Comment by damencho** [comment]
You just need to create a Pull Request with the translation using main.json as template. Do not add the strings that you have not translated ... no empty strings ...

**Comment by xosecalvo** [comment]
The two files (languages-gl.json, main-gl.json) already existed. I've finished the translation and what to upload them, but I have no write access. How do I do this?
