### ISSUE TITLE
iOS problems during a call

### ISSUE THREAD

**Issue by ShangLin-Wu** [jitsi/jitsi-meet#8265]
### Description:

When I was during a call, I'm always stopped at about 20~30 seconds of the call time

### Steps to reproduce:

Use iPhone6 to make calls to iPhone XR

### Expected behavior:

I think it should be normal

### Actual behavior:

Before I updated to version 2.11.0 (Xcode 12.3), the original version was 2.8.1(Xcode 11.7) and calls were normal at this time, but this problem occurred after the update

When I was during a call, I'm always stopped at about 20~30 seconds of the call time
It will show the dialog like this 
![image](https://user-images.githubusercontent.com/38851003/102451077-c7f36a80-4072-11eb-9248-0bb1c1c5a051.png)

![image](https://user-images.githubusercontent.com/38851003/102452138-d0e53b80-4074-11eb-8655-c48e13e6d82d.png)

### Server information:

- Jitsi Meet version: 2.11.0
- Operating System: macOS Big Sur 11.1

### Client information:

- Operating System: iPhone6 (12.4.8) / iPhone XR(13.4.1)

**Comment by saghul** [comment]
We'd need to see more logs, but from what I see there, ICE failed, hence the connection was broken.

**Comment by ShangLin-Wu** [comment]
Okay it's here
![image](https://user-images.githubusercontent.com/38851003/102579978-9ba22180-4138-11eb-8219-a6e4bd6be662.png)

![image](https://user-images.githubusercontent.com/38851003/102579981-9e9d1200-4138-11eb-9101-86099304f639.png)

![image](https://user-images.githubusercontent.com/38851003/102579991-a52b8980-4138-11eb-9b85-f387443ff12a.png)

![image](https://user-images.githubusercontent.com/38851003/102580008-aceb2e00-4138-11eb-8032-1ff4ddf5b044.png)

![image](https://user-images.githubusercontent.com/38851003/102580018-b1afe200-4138-11eb-986e-abb59ce43077.png)

![image](https://user-images.githubusercontent.com/38851003/102580022-b4aad280-4138-11eb-8568-5831f44804d3.png)

**Comment by saghul** [comment]
I see the bridge channel was not up. From what I see it looks like a connectivity problem.

**Comment by ShangLin-Wu** [comment]
Do you have any suggestions? How should I open the bridge channel?  Thank you!

**Comment by saghul** [comment]
That should work out of the box. Could be misconfiguration on the server for example.
