### ISSUE TITLE
Xcode 12.3 built error

### ISSUE THREAD

**Issue by Insfgg99x** [jitsi/jitsi-meet#8266]
Description:
I upgraded to Xcode 12.3,  the error is:

Building for iOS, but the linked and embedded framework 'WebRTC.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'JitsiMeet.framework' was built for iOS + iOS Simulator.

![image](https://user-images.githubusercontent.com/12442442/102452362-333e3c00-4075-11eb-8016-4df24feba4fe.png)
![image](https://user-images.githubusercontent.com/12442442/102452405-451fdf00-4075-11eb-9cb4-a0c8e9e06f4b.png)

Anyone would have an idea on how to fix this issue?

Thank you!

**Comment by luboslav** [comment]
Workaround is to set "Validate Workspace" to "Yes" in BuildSettings.

**Comment by Insfgg99x** [comment]
> Workaround is to set "Validate Workspace" to "Yes" in BuildSettings.
It works! Thanks very much! 🌹
