### ISSUE TITLE
Safari - security options (especially: adding password not possible!)

### ISSUE THREAD

**Issue by S-Forsti** [jitsi/jitsi-meet#8274]
Dear GitHub community,

### Description:

Our school uses KiwiTalk, which is based on Jitsi-meet. To protect our students I started to use passwords for our meetings. Thereby I noticed that it is not possible to set a password, to enable end to end encryption or the lobby feature in Safari. 
While the latter two options are simply not available, the pop up window for setting a password comes up. 
![Screenshot 2020-12-18 at 10 57 31](https://user-images.githubusercontent.com/76203544/102601549-9afd9100-4120-11eb-915e-b6e71a11ab3f.png)
I'm also able to type in a password. However, I can't actually "add" the password, which means nothing happens if I click on the "Hinzufügen"-Button
![Screenshot 2020-12-18 at 11 03 40](https://user-images.githubusercontent.com/76203544/102601612-b49ed880-4120-11eb-912b-8c2ae5fc85a6.png)

 I've just tested if the problem reoccurs on the general meet.jit.si webpage as well. Although here it is possible to enable the lobby feature, I can still only type in but not add a password. 
![Screenshot 2020-12-18 at 11 04 47](https://user-images.githubusercontent.com/76203544/102601791-f039a280-4120-11eb-8578-6707f9ac6e0c.png)

### Steps to reproduce:

Problems on KiwiTalk
1. Open Safari browser
2. access https://demo.kiwitalk.de
3. open a new meeting 
4. access the security options
5. klick "add password" to enable typing in a password
6. klick on "add"   (... nothing happens/changes)

Problems on www.meet.jit.si 
1. Open Safari browser
2. access www.meet.jit.si
3. open a new meeting 
4. access the security options
5. klick "add password" to enable typing in a password
6. klick on "add"   (... nothing happens/changes)

### Expected behavior:

If you open the a meeting in jitsi or via KiwiTalk via Safari, all security options should be available (enable lobby, password, enable ent-to-end encryption).
If you try to set a password via Safari, you should not only be able to type in a password but to actually add and activate it. 
![Screenshot 2020-12-18 at 11 15 31](https://user-images.githubusercontent.com/76203544/102602846-5d9a0300-4122-11eb-8b77-422c8c8fd782.png)

### Actual behavior: (see corresponding screenshots above)
In both, Jitsi-meet and KiwiTalk, you can type in a password but not actually activate it. The pop up window doesn't change at all if you klick on "add" but stays the same and the password isn't set. 

Using KiwiTalk with Safari neither "enable lobby" nor "enable end-to-end encryption" are available as security options. 

Using Jitsi-meet with Safari the security options "enable end-to-end encryption" is not available. 

### Client information:

- Browser / app version: Safari / Version 14.0.2
- Operating System: Mac OS

**Comment by saghul** [comment]
> I'm also able to type in a password. However, I can't actually "add" the password, which means nothing happens if I click on the "Hinzufügen"-Button

I could reproduce this on Safari. Thanks for the report!

> While the latter two options are simply not available,

The lobby is a feature that needs to be supported in the server, I suspect KiwiTalk hasn't enabled it. Also, E2EE is only supported in Chromium based browsers because it depends on a very recent and still Chrome-only API. Safari is looking to implement it too AFAIK, but it's not released yet.

**Comment by saghul** [comment]
FWIW, pressing enter does allow you to set the password. Hopefully this servers as a workaround while we solve the button problem.

**Comment by S-Forsti** [comment]
> > I'm also able to type in a password. However, I can't actually "add" the password, which means nothing happens if I click on the "Hinzufügen"-Button
> 
> I could reproduce this on Safari. Thanks for the report!
> 
> > While the latter two options are simply not available,
> 
> The lobby is a feature that needs to be supported in the server, I suspect KiwiTalk hasn't enabled it. Also, E2EE is only supported in Chromium based browsers because it depends on a very recent and still Chrome-only API. Safari is looking to implement it too AFAIK, but it's not released yet.

Thanks for your quick response and workaround advice. :)
