### ISSUE TITLE
Chaage the meeting background color to black

### ISSUE THREAD

**Issue by jagadish-pattanaik** [jitsi/jitsi-meet#8280]
Change the meeting screen background color to black which will make it look really good as both zoom and google meet are having black and they look awesome in it. it would be a great UI improvement.

**Comment by damencho** [comment]
Please when you have problem or questions use the community forum before opening new issues.

This is already possible: https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js#L47

**Comment by jagadish-pattanaik** [comment]
but is it possible for android? and especially with futter framework? I a using this flutter [plugin ](https://github.com/gunschu/jitsi_meet)

**Comment by damencho** [comment]
There is some work done around css and passing it to the sdk, I think it is possible.

**Comment by jagadish-pattanaik** [comment]
I have tried it and there is now way with SDK for Android and especially with flutter framework plugin. So please inform if there is another way or when background colour change has been added to SDK.
