### ISSUE TITLE
Participant initials should just be the id if it's short enough (3 characters or fewer)

### ISSUE THREAD

**Issue by gasull** [jitsi/jitsi-meet#8282]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

The main screen shows participant initials when they don't have set a profile picture.  For short ids, like "Tim", the id "Tim" should be shown instead of "T".  It also happens that it's common to have several participants with the same initials, which adds to the confusion.

**Describe the solution you'd like**
Please describe the desired behavior.

Show the id instead of the initials if the id is 3 characters or fewer.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
We prefer consistency vs having exceptions for specific cases.

**Comment by gasull** [comment]
What about 2 people in the same room with the same initial?  That happens to me all the time and I don't know who's who.  Even in a room with just a dozen people you're very likely to have at least two people with the same initial.

**Comment by saghul** [comment]
You can always hover and see the full name or open the speaker stats view. I get that it's not perfect, but it's more consistent than the alternatives.
