### ISSUE TITLE
Change the word "kick out" to something decent like "remove"

### ISSUE THREAD

**Issue by jagadish-pattanaik** [jitsi/jitsi-meet#8286]
The word kick out sounds abusive and when someone is kicked out it shows "ouch xyz kicked you out" which is a bit abusive and the person may feel bad please change it to removed you from kicked you.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you. 

I understand, this term comes from the signaling protocol used https://xmpp.org/extensions/xep-0045.html#kick

**Comment by jagadish-pattanaik** [comment]
I mean can it be changed ? Or should I do anything that will change it.? I am suing jitsi sdk (flutter)

**Comment by damencho** [comment]
You can change it on your deployment.

**Comment by pratik9722** [comment]
@jagadish-pattanaik Please don't create any bullshit issues on the Github so that they can peacefully utilize those time into solving an important issue like "enabling fully functional VP9 into Jitsi environment"
