### ISSUE TITLE
Only host should be allowed to kick out and accept lobby requests

### ISSUE THREAD

**Issue by jagadish-pattanaik** [jitsi/jitsi-meet#8287]
Only host should be allowed to kick out any participant or allow them from lobby to join meeting not other participants as in zoom and google meet. It will keep the meeting very safe. Jitsi meet quality is very good just needs some minor changes like this and then it can beat others easily.

**Comment by damencho** [comment]
Please when you have questions or problems using the community forum before opening new issues. 

This is already the case, with default deployment the first to join is a moderator and is the only one that can allow lobby or kick, is authentication is enabled then moderators will be the authenticated users. 
If you are talking about meet.jit.si that is an anonymous environment and is chosen a mode where everyone is moderator, dedicated moderator for a meeting is possible for environments with authentication.

**Comment by jagadish-pattanaik** [comment]
With authentication? How is that done? I want that only host can kick or allow people in lobby like in zoom and meet...how to do that in Jitsi SDK for flutter and meet.jit.si?

**Comment by damencho** [comment]
That is not possible on meet.jit.si, you need to host your own deployment or use the paid service from [8x8](https://www.8x8.com/8/jaas-beta-sign-up)
