### ISSUE TITLE
Screen share issue in android phone

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8290]
i am trying to fix the following issue:

**when camera video is on, if i start the screen share, and when i stop the share. the video state is not getting restored. user has to click on video Button one more time.**

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
This is intentional, for the time being.
