### ISSUE TITLE
Getting issue while building jitsiMeet SDK 2.11.0 on xcode 12.2

### ISSUE THREAD

**Issue by mksmanish** [jitsi/jitsi-meet#8291]
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed: Ld /Users/ankitk/Library/Developer/Xcode/DerivedData/jitsi-meet-cusczvnrhzsgysadgutjwvwofufz/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/JitsiMeetSDK.framework/JitsiMeetSDK normal (1 failure)

I am using xcode 12.2 .Tried cleaning the DerivedData also but failed everytime.

**Comment by Bharagvios** [comment]
@mksmanish , Did you add the Run script?

**Comment by mksmanish** [comment]
how to use that one ,which script you are talking about.please tell.@Bharagvios

**Comment by Bharagvios** [comment]
# Type a script or drag a script file from your workspace to insert its path.
echo "Target architectures: $ARCHS"

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")

FRAMEWORK_TMP_PATH="$FRAMEWORK_EXECUTABLE_PATH-tmp"

# remove simulator's archs if location is not simulator's directory
case "${TARGET_BUILD_DIR}" in
*"iphonesimulator")
    echo "No need to remove archs"
    ;;
*)
    if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "i386") ; then
    lipo -output "$FRAMEWORK_TMP_PATH" -remove "i386" "$FRAMEWORK_EXECUTABLE_PATH"
    echo "i386 architecture removed"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
    fi
    if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "x86_64") ; then
    lipo -output "$FRAMEWORK_TMP_PATH" -remove "x86_64" "$FRAMEWORK_EXECUTABLE_PATH"
    echo "x86_64 architecture removed"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
    fi
    ;;
esac

echo "Completed for executable $FRAMEWORK_EXECUTABLE_PATH"
echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")

done

**Comment by Bharagvios** [comment]
Add this to your Run Script from build Phases

**Comment by mksmanish** [comment]
I used the above script you have given,Still getting the same error .@Bharagvios

**Comment by mason-tranty** [comment]
Hit the same issue, any idea for that?

**Comment by emndeniz** [comment]
I have encountered similar issue and after a little research I found that Apple removed a config from Xcode called **VALID_ARCHS**. That cause Jitsi to not find X86_64 simulator architecture. I did add User-defined setting in Build Settings tab called VALID_ARCHS and leave it empty. After that compile archive succeeded. 

<img width="427" alt="Screen Shot 2020-12-24 at 18 47 08" src="https://user-images.githubusercontent.com/7477031/103103668-ad516080-4633-11eb-9a80-7557067a68aa.png">


Also you can use release release-sdk.sh script from ios/scripts directory. You also need to delete  line `VALID_ARCHS=x86_64 \` from script to have a successful archive.

**Comment by mason-tranty** [comment]
> I have encountered similar issue and after a little research I found that Apple removed a config from Xcode called **VALID_ARCHS**. That cause Jitsi to can not find X86_64 simulator architecture for WebRTC. I did add User-defined setting in Build Settings tab called VALID_ARCHS and leave it empty. After that compile archive succeeded.
> 
> ![Screen Shot 2020-12-24 at 21 59 53](https://user-images.githubusercontent.com/7477031/103103741-4bddc180-4634-11eb-86d3-3497dd1cbead.png)
> 
> Also you can use release release-sdk.sh script from ios/scripts directory. You also need to delete line `VALID_ARCHS=x86_64 \` from script to have a successful archive.
I got this error when remove VALID_ARCHS=x86_64 from script
  Ld /Users/tranty/Library/Developer/Xcode/DerivedData/jitsi-meet-gxphfkijonmtodcrfqvscuuotmxf/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/sdk.build/Release-iphonesimulator/JitsiMeetSDK.build/Objects-normal/x86_64/Binary/JitsiMeetSDK normal x86_64

**Comment by mason-tranty** [comment]
> I have encountered similar issue and after a little research I found that Apple removed a config from Xcode called **VALID_ARCHS**. That cause Jitsi to can not find X86_64 simulator architecture for WebRTC. I did add User-defined setting in Build Settings tab called VALID_ARCHS and leave it empty. After that compile archive succeeded.
> 
> ![Screen Shot 2020-12-24 at 21 59 53](https://user-images.githubusercontent.com/7477031/103103741-4bddc180-4634-11eb-86d3-3497dd1cbead.png)
> 
> Also you can use release release-sdk.sh script from ios/scripts directory. You also need to delete line `VALID_ARCHS=x86_64 \` from script to have a successful archive.

I got this issue while run script 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RTCMediaConstraints", referenced from:
      objc-class-ref in libreact-native-webrtc.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCDataBuffer", referenced from:
      objc-class-ref in libreact-native-webrtc.a(WebRTCModule+RTCDataChannel.o)
  "_OBJC_CLASS_$_RTCDataChannel", referenced from:
      __OBJC_$_CATEGORY_RTCDataChannel_$_React in libreact-native-webrtc.a(WebRTCModule+RTCDataChannel.o)
  "_OBJC_CLASS_$_RTCMediaStreamTrack", referenced from:
      __OBJC_$_CATEGORY_RTCMediaStreamTrack_$_React in libreact-native-webrtc.a(RTCMediaStreamTrack+React.o)
  "_OBJC_CLASS_$_RTCConfiguration", referenced from:
      objc-class-ref in libreact-native-webrtc.a(RCTConvert+WebRTC.o)
  "_OBJC_CLASS_$_RTCIceCandidate", referenced from:
      objc-class-ref in libreact-native-webrtc.a(RCTConvert+WebRTC.o)
  "_OBJC_CLASS_$_RTCIceServer", referenced from:
      objc-class-ref in libreact-native-webrtc.a(RCTConvert+WebRTC.o)
  "_OBJC_CLASS_$_RTCPeerConnectionFactory", referenced from:
      objc-class-ref in libreact-native-webrtc.a(WebRTCModule.o)
  "_OBJC_CLASS_$_RTCSessionDescription", referenced from:
      objc-class-ref in libreact-native-webrtc.a(RCTConvert+WebRTC.o)
      objc-class-ref in libreact-native-webrtc.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCPeerConnection", referenced from:
      __OBJC_$_CATEGORY_RTCPeerConnection_$_VideoTrackAdapter in libreact-native-webrtc.a(WebRTCModule+VideoTrackAdapter.o)
      __OBJC_$_CATEGORY_RTCPeerConnection_$_React in libreact-native-webrtc.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCCameraVideoCapturer", referenced from:
      objc-class-ref in libreact-native-webrtc.a(VideoCaptureController.o)
  "_OBJC_CLASS_$_RTCDefaultVideoEncoderFactory", referenced from:
      objc-class-ref in libreact-native-webrtc.a(WebRTCModule.o)
  "_OBJC_CLASS_$_RTCEAGLVideoView", referenced from:
      objc-class-ref in libreact-native-webrtc.a(RTCVideoViewManager.o)
  "_OBJC_CLASS_$_RTCAudioSessionConfiguration", referenced from:
      objc-class-ref in AudioMode.o
  "_OBJC_CLASS_$_RTCDefaultVideoDecoderFactory", referenced from:
      objc-class-ref in libreact-native-webrtc.a(WebRTCModule.o)
  "_OBJC_CLASS_$_RTCDataChannelConfiguration", referenced from:
      objc-class-ref in libreact-native-webrtc.a(RCTConvert+WebRTC.o)
  "_OBJC_CLASS_$_RTCAudioSession", referenced from:
      objc-class-ref in CallKit.o
      objc-class-ref in AudioMode.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by emndeniz** [comment]
When I deleted line `VALID_ARCHS=x86_64 \ ` from script and run again it succeed.

**Comment by mksmanish** [comment]
Thanks for the reply,@emndeniz you solution worked for me but a new error raised like belowThe following build 

commands failed:
	CompileC /Users/ankitk/Library/Developer/Xcode/DerivedData/jitsi-meet-ferllufkkwhoynapkghzgrlqsqpx/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/app.build/Release-iphoneos/JitsiMeet.build/Objects-normal/arm64/FIRUtilities.o /Users/manishk/Desktop/naya28/jitsi-meet/ios/app/src/FIRUtilities.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)


You have any idea about that??

**Comment by mason-tranty** [comment]
any update on this issue

**Comment by saghul** [comment]
I cannot reproduce it, sorry.
