### ISSUE TITLE
Impossible to change microphone settings in Firefox

### ISSUE THREAD

**Issue by avanhoveceovision** [jitsi/jitsi-meet#8292]
### Description:

Impossible to change microphone settings in Firefox

### Steps to reproduce:

1. Open a visioconference in Firefox
2. Go To settings
3. Try to change microphone parameters

### Server information:

- Jitsi Meet version: Jitsi Cloud

### Client information:

- Browser / app version: Firefox 84.0

### Additional information:

Chrome screenshot

![Parametres_Chrome](https://user-images.githubusercontent.com/65297327/102763420-e78fd900-4379-11eb-8085-3418a7ca4562.JPG)

Firefox Screenshot

![Paramètres_Firefox](https://user-images.githubusercontent.com/65297327/102763440-ee1e5080-4379-11eb-8d19-c96f948cc87e.JPG)

**Comment by zachfedor** [comment]
Ran into this as well today on Firefox 85.0

**Comment by spanezz** [comment]
For those like me who land here and cry at a the issue just being closed by a bot, see #2835
