### ISSUE TITLE
Position of video layout is not changing after close chat 

### ISSUE THREAD

**Issue by Dastnbek** [jitsi/jitsi-meet#8295]
When I open chat, video layout got right sided position and when I close chat it is not positioning at center of window as it before

**Comment by Echolon** [comment]
Please provide more information of your setup and system!

**Comment by JPLynch35** [comment]
I'm seeing this same issue as well.  Seems the same as the issue on the jitsi/jitsi-meet https://github.com/jitsi/jitsi-meet/issues/7889

**Comment by damencho** [comment]
Di you reproduce this on meet.jit.si? What is the version you use? What is the browser and version that you are testing with?
