### ISSUE TITLE
Etherpad Closes automatically

### ISSUE THREAD

**Issue by tusharsonawanes** [jitsi/jitsi-meet#8303]
Hello, I am raising this issue because I didnt find any solution on the community. 

My installation docker-jitsi-meet-5142 and this is what happened

Scenario - 3 users are in a meeting

1st user talks and edits the shared document ( doesnt close )
2nd user talks and edits the shared document ( doesnt close )

3rd user is inactive but keeps the shared document open. The third user might need to **just** type in the shared document 

Etherpad closes automatically for the third user. How do resolve this issue ?

**Comment by saghul** [comment]
Transferring to jitsi-meet, as this is not relevant to the Docker setup but to the frontend project.

**Comment by tusharsonawanes** [comment]
Okaye..

**Comment by Patrick-Vogt** [comment]
Are there any news to this? Unfortunately it still happens.
Could it help to remove the blue frame of the active speaker? (Could have something to do that the focus changes?)

Thank you.

**Comment by kenshin33** [comment]
I noticed that today while testing etherpad. We were about 6  in the meeting, there was no way to use it.
I'm not certain, but it seemed like it was closing everytime the focus was shifting from one persone to the other.

**Comment by saghul** [comment]
Closing in favor of https://github.com/jitsi/jitsi-meet/issues/8109 which was opened earlier.
