### ISSUE TITLE
Jitsimeet.framework is not generated - xcode 12.2 macos Bigsur

### ISSUE THREAD

**Issue by mason-tranty** [jitsi/jitsi-meet#8306]
### Description:
I did build successfully the source code but I could not get the JitsiMeet.framework at ios/sdk.

### Steps to reproduce:
1. sh node_modules/react-native-webrct/tools/donwloadBitCode.sh
2. xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

### Expected behavior:
JitsiMeet.framework should be generated at folder ios/sdk

### Actual behavior:
JitsiMeet.framework is not generated

### Additional information:

Xcode: 12.2
Macos: Bigsur
Node: v13.11.0
NPM: 6.14.10

**Comment by mason-tranty** [comment]
I think we need to update ReadME because now the name of SDK will be JitsiMeetSDK.framework not JitsiMeet.framework anymore. https://github.com/jitsi/jitsi-meet/pull/8270

**Comment by kleeb** [comment]
+1

**Comment by saghul** [comment]
Check the ios/scripts/release-sdk.sh script. We switched to XCFrameworks now.

**Comment by pdarcos** [comment]
I'm also having the same problem, and when I try running the new script I get an error

sh release-sdk.sh 
release-sdk.sh: line 6: realpath: command not found

Any help please?

Thanks

**Comment by kleeb** [comment]
```
npm i -g realpath
```

and the same for all commands that are not found, or apt-get or gem install depends on the command and OS
