### ISSUE TITLE
Cannot type the room name while the Android app is busy fake-typing example room names

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet#8307]
Testing Jitsi Meet's Android app [from the fdroid repositories](https://f-droid.org/en/packages/org.jitsi.meet/) (so currently version 20.5.0 (205001) ...) I noticed that on the home screen, in the text input field where you are supposed to type the room name you want to create or join, typing will NOT work while the app is already typing fake/example room names. It will only work when it stops "fake typing".

This is going to be a pretty big usability issue for non-technical users, who then have to fight with the app for control over typing into that text input field, needing to quickly react and type during the short time interval during which the app actually accepts their input...

**Comment by NicolasGodfather** [comment]
I have the same problems on samsung devices android os-7, models galaxy s6,7,edge, etc. I use version    implementation('org.jitsi.react:jitsi-meet-sdk:2+') { transitive = true }

**Comment by saghul** [comment]
What device are you using? That is just placeholder text, all Android devices I have access to accept typing no problem despite the placeholder changing.

**Comment by nekohayo** [comment]
I don't see what the hardware device would have to do with this, the OS however is LineageOS 16, which is Android 9.

The placeholder interferes with typing "while the placeholder is typing", it does not interfere during the brief moment when it remains still, or if you managed to type in at least one character yourself (because then the placeholder is interrupted).

**Comment by saghul** [comment]
I think  I see what you mean, I'll check what can be done.

**Comment by saghul** [comment]
Should be fixed by https://github.com/jitsi/jitsi-meet/pull/8384
