### ISSUE TITLE
Due to echo calls without headset impossible

### ISSUE THREAD

**Issue by sandoxy** [jitsi/jitsi-meet#8308]
Hi there,

I love FOSS and I know jitsi for many years. Now I am trying to switch with my family from skype to jitsi. We are usually talking with a lot of people sitting on a sofa with more than 5 people in one room and with many children involved. That's important, because it is not possible to use a headset. There where no issues with echo on skype. We tried today a conference on jitsi, but there was a very bad echo. I tried jitsi web on chrome(ubunt) and the jitsi app(android). Both times I heard a bad echo, I heard my voice. Is there a way to get rid of that echo without using a headset?

Best Regards

**Comment by nekohayo** [comment]
As far as I know there _is_ echo cancelling, just that it probably works "for some devices" but not all, depending on how crappy people's microphones and connection latency are (?)

I feel your pain. You might be interested in using push-to-talk, see issue #8322, issue #8324, and issue #8323 that I filed today.

**Comment by sandoxy** [comment]
@nekohayo Thank you for the info.

**Comment by saghul** [comment]
There is not much we can do here since we rely on the hardware echo canceller.
