### ISSUE TITLE
Desktop: Browser Extension For Recording

### ISSUE THREAD

**Issue by trymeouteh** [jitsi/jitsi-meet#8310]
I have a suggestion to allow for recording on the desktop without needing to use a third party service like dropbox. Create browser extension or add a feature the the current browser extension to allow audio or video of a recording and save the recording as a file on the desktop computer. This way no need for third party services like dropbox, no need for the browser webpage to do the recording.

**Comment by davidpgil** [comment]
I would also like to see some way to not need Dropbox. I heard of RecordRTC -- https://chrome.google.com/webstore/detail/recordrtc/ndcljioonkecdnaaihodjgiliohngojp/related but honestly, I think it has some security concerns. Ideally I would prefer local recording with the local app.

**Comment by saghul** [comment]
We will be introducing a "local recording" feature soon, stay tuned ;-)
