### ISSUE TITLE
[Docker image version stable-5142-4] “You have been disconnected” loop on fresh docker installation

### ISSUE THREAD

**Issue by amezioud** [jitsi/jitsi-meet#8318]
Sources :

https://community.jitsi.org/t/you-have-been-disconnected-on-fresh-docker-installation/89121
https://stackoverflow.com/questions/65168702/jitsi-meet-you-have-been-disconnected/65520722#65520722
https://www.synoforum.com/threads/jitsi-meet-container-first-touch-preparation-for-a-final-resource-description.3713/

**Comment by amezioud** [comment]
image: jitsi/{web,prosody,jicofo,jvb}:stable-5076 work perfectly.

**Comment by bo0tzz** [comment]
Can confirm I'm seeing this same issue after pulling the latest docker images, and using the `stable-5076` tag works. Unfortunately I didn't think to save it, but the browser console logging included some errors about being unable to connect to a websocket on `localhost:8443`

**Comment by JohnLukeP** [comment]
I can confirm this issue, the stable-5142-4 doesn't work

**Comment by Klaas-** [comment]
This is fixed for me in 5390-1
