### ISSUE TITLE
Ability to help a participant unmute themselves

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet#8323]
As a moderator for family videoconferencing with 20+ participants who are mostly tech-illiterate, and who need to be muted when they're not talking because they make crazy noises or have bad microphones, I've found the biggest usability problem to be that they don't know how to unmute themselves. EVEN IF YOU TELL THEM, and say "You are muted, uncle! Move the mouse and click the unmute button at the bottom of the screen!" and they spend 5 minutes looking for it (I wish I was exaggerating).

I understand that a participant can't directly unmute another for privacy reasons (I presume), but what would help tremendously here is the ability to _help_ a participant unmute themselves, by having a "Ask participant to unmute" action in the context menu, which would then show a big fat OBVIOUS centered overlay prompt on the participant's screen that says:

> $other_participant_name_if_set is asking you to unmute so they can hear you. Would you like to unmute now? [Unmute] [Stay muted]

If the request comes from someone who has not set their nickname, then obviously the message would be slightly different:

> Another participant is asking you to unmute so they can hear you. Would you like to unmute now? [Unmute] [Stay muted]

And make those "Unmute" and "Stay muted" action buttons BIG, OBVIOUS COLORFUL BUTTONS, not dark-blue hyperlinks (which are tiny and hard to see due to the dark background behind them).

Choosing "Stay muted" would probably dismiss the prompt for a minimum of 20 seconds.

**Comment by gene96817** [comment]
Would it be better to have a feature (as in Zoom) where they can temporarily unmute by holding down the space bar? Basically a push-to-talk (PTT). Then when they are done, releasing the space bar is all that needs to be done.

**Comment by nekohayo** [comment]
Push to talk already is implemented in the web interface, but not easily discovered (issue #8322). It does not seem to be implemented in the mobile version (issue #8324).

But what I am requesting here is something else than push to talk, because not every user is going to be able (or want to) use that, so I still need the ability to mass mute and then help individuals unmute themselves.

**Comment by gjaekel** [comment]
Dear @nekohayo,
we all know that a Moderator is able to mute another participant. Maybe at the same UI location, a Moderator also should be able to unmute. But by the other hand, this is a privacy problem: Especially if your participant isn't able to unmute by self, he probably don't notice that he was pushed "on air"!

BTW: Such an tech-illiterale participant may be unable to unmute because don't know about the "common used" **icons**. To my experience it's better to tell him "Please press the [M] button on you key board!". The same yield for [V]ideo, of course ...

**Comment by nekohayo** [comment]
As I've stated in the problem description above, I am not asking for a force-unmute feature. I'm asking about the ability to send an obvious UI prompt to the participant, right in the center of the screen, that offers them to easily unmute with the message (and button) suggested above. That's a completely different approach which is not a danger to privacy, because they can always decline, it's a conscious action.

**Comment by gjaekel** [comment]
Yes, I understand what you had asked for. I just want to give a suggestion to discuss, that will need much less technical work for sure, but is problematic. I don't vote to go this way, too.

**Comment by MagicFab** [comment]
As a workaround, if you self-host you can force starting all participants muted and let them know about the space bar PTT feature.
I have had better success by having practice sessions in advance and sharing with the participants [a cheat-sheet of shortcuts I put together](https://community.jitsi.org/t/jitsi-meet-keybard-shortcuts-cheatsheets-in-english-and-spanish-possibly-others/21013).

**Comment by gjaekel** [comment]
:+1: for the hint with the PTT feature!
A cheat-sheet of all shortcut will appear on pressing [?] (or invoking it at the menue). This will be localized in the chosen UI language.

**Comment by roccobarbi** [comment]
Actually, there is a different use case where moderator-enforced muting AND unmuting could be beneficial to users.

At least in Italy, jitsi-meet is beeing widely used by schools to guarantee distance learning to children during lockdowns. This often turns messy when children unmute themselves at the wrong time, or fail to do so, or even mute/kick other kids.

It would be extremely useful to give moderators the chance to center all powers on themselves, including the power to force-unmute a participant. The privacy issue is easily solved by enforcing the presence of an overlay stating that "during this call, the moderator has the power to do so and so" when a participant joins the meeting, and by applying some visual indicator that the user has been unmuted.

**Comment by nekohayo** [comment]
Still frequently encountering this issue with participants. (saying this just to make the bot happy)

**Comment by saghul** [comment]
Moderators can now "ask to unmute" in the participants pane.
