### ISSUE TITLE
PTT (press-to-talk) for mobile version of Jitsi Meet on Android and iOS

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet#8324]
I discovered recently that meet.jit.si supports PTT for the desktop/web version, just that it's not "obvious" (issue #8322).

However, I looked everywhere in the Android app version of Jitsi Meet and I couldn't find any PTT feature. I would like to have this feature present and exposed to mobile users as well.

Zoom had that feature, especially for people travelling or in noisy environments, but in their case it's part of the "[safe driving mode](https://support.zoom.us/hc/en-us/articles/201362973-What-is-safe-driving-mode-)", and their PTT button is a huge circle that spanned the whole screen (as it is assumed that video is not be relevant nor safe for use on the road).

Me, I'm thinking rather about the usecase of all my uncles and aunties connecting at home using their tablets.
In Jitsi meet, When they are muted, there could be a "PTT" button next to the unmute button, and when they are trying to talk while muted there could be an overlaid notification on-screen that says "Press & hold the PTT button to temporarily unmute while you are talking"

**Comment by nekohayo** [comment]
Begone, foul robot!

**Comment by dXNlcm5hbWU** [comment]
+1

**Comment by nekohayo** [comment]
Another issue related to this is, I would like the push-to-talk feature to also be available from the lockscreen "notification", if possible; because if you're taking a long walk and listening into a meeting, the screen will eventually turn off and lock by itself, and quickly unlocking the screen is a big time-consuming hassle when you only need to temporarily unmute to answer one or two sentences... but I don't know if/how easily this is feasible, vs PTT is the app UI itself. Should that be a separate ticket?

**Comment by saghul** [comment]
We have plans to implement a "car mode" which would have something like this, but not in the ongoing notification. You are welcome to open a new issue, but just to be fully upfront here there are very low chances of it happening without anyone volunteering to work on it.

**Comment by torrybr** [comment]
I am also running into this problem more broadly where I am unable to mute from the lock screen for any communication within jitsi meet and unable to get any benefit from the Android PiP (picture in picture) feature.

Specially if I am looking at a map, while in jitsi car mode, I want to use the PiP feature to unmute myself and continue to talk. As implemented car mode does not use the PiP only the normal mode. Having both use PiP would be incredibly helpful so I can unmute and mute in both modes

**Comment by saghul** [comment]
Closing this. Car mode has a push to talk functionality.

That cannot be done for PiP since we provide no controls there, just the ability to go back to full view.
