### ISSUE TITLE
Mute status indicator icons overlaid on participant videos are too small and lack a background, so they are almost invisible

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet#8325]
I'll start by illustrating the problem. In this test meeting on meet.jit.si, both participants are muted... but it's nearly impossible to tell:

![jitsi meet muted status icons are impossible to see](https://user-images.githubusercontent.com/479401/103464869-0f315a80-4d05-11eb-8b84-2cff145b3e7c.png)

There are multiple problems with the current "muted" status indicators:

* They are too small
* They are white without a background to provide contrast, so they become totally invisible if the participant has a bright lower-left corner in their video feed. White (or close to white) is a very frequent/natural occurence, especially since that's the color of most walls indoors. Pure black or red walls would be very rare, in comparison.

...and that makes it nearly impossible to moderate/manage a discussion with many participants when you need to quickly find out who is making noise and needs to be muted (no, it won't always show up on the sound volume levels indicator, which also suffers from the nearly same "invisibility" issues anyway). These indicator icons are super important, and I need to see them clearly.

The solution: make the icons bigger, and also encase them against a dark background (a red or black circle? or just a square corner?) of at least 50-70% opacity (if not 100%).

**Comment by MagicFab** [comment]
What to the "other" tools do to indicate muted participants  ?

**Comment by nekohayo** [comment]
Zoom (for what it's worth) does part 2 of what I recommend (red icon and black background, overlayed on the video):

![Screenshot from 2021-01-25 10-27-54](https://user-images.githubusercontent.com/479401/105726737-6091cb80-5ef8-11eb-8e43-35d5f37eaccc.png)

...but I still think it should be at least 2x bigger, for usability/noticeability.

**Comment by nekohayo** [comment]
🦉

**Comment by nekohayo** [comment]
!

**Comment by damencho** [comment]
![image](https://user-images.githubusercontent.com/3263098/148694578-1b955b47-375d-460b-bdba-b7b9d14b977a.png)
