### ISSUE TITLE
Adding methods to native modules is showing undefined when accessed

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8328]
i have added below method in android->sdk->src->main->java->AppInfoModule.java,
public void cancelButtonPressed() {
System.out.println(“Cancel Button Pressed”);
JitsiMeetActivityDelegate.onBackPressed();
}

accessed in react-native with following code

const AppInfo = NativeModules.AppInfo;
AppInfo.cancelButtonPressed();

Error is:
AppInfo.cancelButtonPressed is not a function.

**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
Please ask such questions on our community. You are missing the `@ReactMethod` annotation, otherwise your method won't be visible to RN.
