### ISSUE TITLE
Audio sharing on the mobile

### ISSUE THREAD

**Issue by okensun** [jitsi/jitsi-meet#8333]
**Feature Description:**
The Android10+ and IOS12+ could capture the other app's audio playback and store it into a file or play directly.
Is there any way to create a new audioTrack from WebRtc to send the audio of the other app to all participants?

**Use case**
During sharing the other app's screen (ex: gaming app), we hope could share the app's audio with other participants.

**Comment by maksudur-rahman** [comment]
We can share the screen from android devices during a Jitsi meet. but If we are playing a video on screen, the sound/audio of the video is not shared with the participants. How can I implement this?

**Comment by saghul** [comment]
It's not supported. It might be possible these days, but we haven't looked at how and it's unlikely we'll take a look at it in the foreseeable future.

**Comment by Yolakalemowa** [comment]
> It's not supported. It might be possible these days, but we haven't looked at how and it's unlikely we'll take a look at it in the foreseeable future.

Hi, sorry noob here... I think I saw in the release notes of one of the latest updates that audio sharing is now possible? I didn't know how to check so I thought I'd ask here? Probably mistaken?

**Comment by saghul** [comment]
Where did you see that? This has not been implemented.
