### ISSUE TITLE
Exposed all UI View on native sdk

### ISSUE THREAD

**Issue by Liuchunqi3240** [jitsi/jitsi-meet#8334]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

I am a native dev, not understand react-native , I wash to find some funtion to control all views.

example : hidden toolbar , add some button(create by native) on jitsiview to control camera, and so on .

**Comment by saghul** [comment]
We don't have that capability. All UI controls are driven by React Native.
