### ISSUE TITLE
Can't compile iOS SDK

### ISSUE THREAD

**Issue by immortal79** [jitsi/jitsi-meet#8335]
### Description:
Hello,

I followed the guide to compile the sdk available here:
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile

### Steps to reproduce:

1. npm install
2. pod install
3. xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

I also tried using: `scripts/release-sdk.sh` but I get a missing bitcode error even after using tools/downloadBitcode.sh from the WebRTC node modules also I'm not sure that is required because there are no documentation about this, only issues. 

### Expected behavior:

The sdk is correctly generated at `ios/sdk/JitsiMeet.framework` as described in the handbook.

### Actual behavior:

Nothing is generated. 

### Additional information:

There are multiple issues and mentions about this #8306,  https://github.com/jitsi/jitsi-meet-sdk-samples/issues/33 and https://github.com/jitsi/jitsi-meet/pull/8270 but they are all closed without a proper solution ?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/8306#issuecomment-754888619

**Comment by saghul** [comment]
The handbook is not up to date because we haven't released an SDK off master yet.

**Comment by immortal79** [comment]
> [#8306 (comment)](https://github.com/jitsi/jitsi-meet/issues/8306#issuecomment-754888619)

I should have been maybe more clear but the running the script as suggested in the comments but I get an error about WebRTC missing architecture.
```
ld: warning: ignoring file /jitsi-meet/node_modules/react-native-webrtc/apple/WebRTC.xcframework/ios-arm64/WebRTC.framework/WebRTC, missing required architecture x86_64 in file /jitsi-meet/node_modules/react-native-webrtc/apple/WebRTC.xcframework/ios-arm64/WebRTC.framework/WebRTC (1 slices)
Undefined symbols for architecture x86_64:
```

**Comment by saghul** [comment]
Are you using CocoaPods 1.10?

**Comment by immortal79** [comment]
I checked my CocoaPods version and it was 1.9.4. After upgrading to CocoaPods 1.10 the archiving process is successful thank you for your help.

**Comment by mohyM** [comment]
if you are using CocoPods < 1.10 please use this command to update Cocopods and this will build successfully with  your project 
`sudo gem install cocoapods`
`rm -rf ios/Pods/`
`rm -rf ios/Podfile.lock`
`pod install`
build again will run is a 👌
