### ISSUE TITLE
Provide gender-neutral german translation

### ISSUE THREAD

**Issue by capital-G** [jitsi/jitsi-meet#8345]
Currently the german web-interface of Jitsi is not gender neutral in the german language.
E.g. during login procedure it speaks about *Ich bin der Organisator*, which implies a male organisator.
The german languages often provides alternatives which do not implicit any gender, such an alternative for the example above would be *Ich organisiere das Meeting*.

I am not an expert in this domain, but I could ask a comission at our university for help and organize a PR for the german translation.
But before I do this, I want to have a green light that this could get merged.

**Comment by saghul** [comment]
Sure thing, please and thank you!
