### ISSUE TITLE
V20.6.0 on iOS 11.4.1 crashes on open

### ISSUE THREAD

**Issue by MidlifeRenaissanceMan** [jitsi/jitsi-meet#8347]
### Description:

Recent update via the Apple App Store to version 20.6.0 has left the app unable to run
Crashes on launch. 

IOS version 11.4.1
IPhone 6s

### Steps to reproduce:

1. Launch the app
2. You get a splash screen
3. App goes away
4. App is still in the list of running apps using double tap
5. Select it and the splash screen appears then drops you back on the desktop

### Expected behavior:

More than this

### Actual behavior:

As above:
1. Launch the app
2. You get a splash screen
3. App goes away
4. App is still in the list of running apps using double tap
5. Select it and the splash screen appears then drops you back on the desktop

### Server information:

- Jitsi Meet version: public Jitsi server 
- Operating System: 

### Client information:

- Browser / app version: 20.6.0
- Operating System: iPhone 6s iOS 11.4.1

### Additional information:

Everything was working (mostly) fine.....until now

**Comment by saghul** [comment]
Thanks for the report, I'll check it ASAP.

**Comment by saghul** [comment]
Found the bug. Swift libraries were not embedded, not sure if I inadvertently changed that or we were just lucky up until now. I'll push an update soon.

**Comment by MidlifeRenaissanceMan** [comment]
Cheers.

Any idea when it will become available in the Apple App Store?

Sent by one of an infinite number of monkeys 
Find out more at https://tools.ietf.org/html/rfc2795

On 7 Jan 2021, at 10:03 pm, Saúl Ibarra Corretgé <notifications@github.com <mailto:notifications@github.com> > wrote:


Closed #8347 via #8350.

**Comment by saghul** [comment]
20.6.1 is now on review by Apple.

**Comment by MidlifeRenaissanceMan** [comment]
Cheers
Much appreciated. 

This app has been responsible for many friendships develop across the globe....(or hockey puck if you’re open to such a concept)

It’s getting desperate. Enough for me to drag out the Morse Code key. Though it’s not as reliable as the infinite number of monkeys I use to send email, there is much less cleaning up afterwards 

I’m still hitting the App Store app every 5 minutes, but because of you’re reply, I am refraining from continually posting the corresponding “are we there yet” on the ticket 

Seriously. Thanks for the prompt response and action. Love your work

Sent by one of an infinite number of monkeys 
Find out more at https://tools.ietf.org/html/rfc2795
