### ISSUE TITLE
react-native run-ios error

### ISSUE THREAD

**Issue by Liuchunqi3240** [jitsi/jitsi-meet#8348]
react-native --version 4.13.1
node -v v15.5.0
npm -v 7.3.0

git clone xxxx
npm install 
cd ios/
pod install
cd ..
react-native run-ios

error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?
error Could not find the following native modules: RNCAsyncStorage, RNGoogleSignin, react-native-netinfo, react-native-background-timer, react-native-calendar-events, RNDefaultPreference, RNDeviceInfo, react-native-keep-awake, BVLinearGradient, RNSound, react-native-splash-screen, RNSVG, RNWatch, react-native-webrtc, react-native-webview. Did you forget to run "pod install" ?
info Found Xcode workspace "jitsi-meet.xcworkspace"
info Building (using "xcodebuild -workspace jitsi-meet.xcworkspace -configuration Debug -scheme jitsi-meet -destination id=5A1FA259-B7EA-436F-82CE-55D83B4E4318")
..
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening jitsi-meet.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace jitsi-meet.xcworkspace -configuration Debug -scheme jitsi-meet -destination id=5A1FA259-B7EA-436F-82CE-55D83B4E4318

xcodebuild: error: The workspace named "jitsi-meet" does not contain a scheme named "jitsi-meet". The "-list" option can be used to find the names of the schemes in the workspace.

**Comment by saghul** [comment]
Better use Xcode instead of the react-native CLI. Some of our changes to support XCFramework must have broken support for it.
