### ISSUE TITLE
Installed jitsi-meet stable but no show live stream button

### ISSUE THREAD

**Issue by mirohe** [jitsi/jitsi-meet#835]
Hello,

I installed jitsi-meet (version stable) in my server and work ok, but no show the live stream button.

I do not find this information. how to configure this?

Best regards

**Comment by casualuser** [comment]
hey @mirohe take a look here - https://jitsi.org/Projects/YouTubeLive

it's really not so easy to find this by yourself so I've got that link from a kind man @ibeardslee at Jitsi irc channel

**Comment by damencho** [comment]
Jibri is the way to go.
