### ISSUE TITLE
screen control share 

### ISSUE THREAD

**Issue by TapanKumarBarik** [jitsi/jitsi-meet#8351]
\how can i give my scrren control to otherone in call same as zoom oe microsoft teams

**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by TapanKumarBarik** [comment]
> Is co-browsing available ? something similar like together js or how can i give my scrren control to otherone in call same as zoom oe microsoft teams
> 
> **Is your feature request related to a problem you are facing?**
> Please describe the problem you are trying to solve.
> 
> **Describe the solution you'd like**
> Please describe the desired behavior.
> 
> **Describe alternatives you've considered**
> Please describe alternative solutions or features you have considered.

**Comment by md-work** [comment]
Probably a duplicate of: [jitsi-meet-electron: Remote control return #483](https://github.com/jitsi/jitsi-meet-electron/issues/483)

**Comment by saghul** [comment]
Yep.
