### ISSUE TITLE
camera light remains on when "muting" video in Firefox

### ISSUE THREAD

**Issue by stefansaenger** [jitsi/jitsi-meet#836]
When a participant of a videoconference using Firefox "mutes" his video, the camera light remains on.
I have tested with my installation (using jitsi-meet 1.0.1108-1) and with the public demo at meet.jit.si to confirm this behaviour.
Note: it does not happen with chrome, chromium or safari, only with firefox (I am running 48).

**Comment by sgala** [comment]
This is still going on with Firefox 54 and "testing" jitsi-meet. For me it brings two problems:
* My laptop heats a lot when firefox records through the camera, even when the video is not sent 
  anywhere, it also drains more batteries, all inconvenient for typical use case when one starts a long call with video to say "hi" to everyone, and then switches video off to go to a conference with shared screens, etc.
* I'm never certain if the video stream is "leaking", so I feel uncomfortable to keep talking with the camera led "on"

I checked bandwidth usage, and the video is not streamed to the other party, but I think the proper behavior should be to pause the recording when the video is "muted", and resume it when

Workarounds:
* remove the video permission and give it back again to the browser, as needed
* use chromium instead for video conferencing

**Comment by saghul** [comment]
You are right, this is still an issue. The explanation is relatively long, but it boils down to Chrome / Firefox differences, and how one has to deal with already opened streams.

This limitation may be lifted in the future, but there is currently no ETA for that.
