### ISSUE TITLE
Camera selection on Firefox displays the same device multiple times

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#8361]
### Description:

On Firefox the camera selection popup replicates one device in slots designated for different devices.

### Steps to reproduce:

1. Any meet.jit.si meeting URL
2. Click on the camera selection dropdown
3. Try selecting different camera devices

### Expected behavior:

The camera selection popup should display preview videos for each connected camera device.

### Actual behavior:

The camera selection popup displays preview of 1 camera only in the slots which belong to other cameras.

### Server information:

- Jitsi Meet version: https://beta.meet.jit.si and https://meet.jit.si (as of today Jan the 7th 2020)

### Client information:

- Browser / app version: Firefox 84.0.2 (64-bit)

- Operating System: Mac OS Catalina 10.15.7

### Additional information:

![Screen Shot 2021-01-07 at 10 28 09 AM](https://user-images.githubusercontent.com/2965063/103918014-e4178400-50d3-11eb-97fe-d6056e28a0ab.png)

**Comment by paweldomas** [comment]
It appears that Firefox does this in case the permissions were granted only for one camera which is when the "Remember this decision" checkbox is to not selected:
![Screen Shot 2021-01-21 at 1 41 35 PM](https://user-images.githubusercontent.com/2965063/105403744-c4617f00-5bee-11eb-807b-ef0a7944b65d.png)

**Comment by solarjoe** [comment]
I have a similar or the same issue (Linux Mint 19.3, Firefox 84.0.2). 
There are two cameras, build-in and external Logitech one.

The feed from the first selected camera works fine but when trying to change the
camera I can only see the two empty boxes as shown in the previous post
where the previews should be.

Using the tickbox or not does not change it, I can not change the camera.
Firefox seems to remember which one was picked first at some point.
I tried that by resetting the site permissions.

When clicking on one of the empty boxes there is some delay and
output in the Javascript console. But in the end the camera does not change.

This is maybe related to [this](https://community.jitsi.org/t/problem-with-camera-switching-jitsi-meet/29227/10):

>  have you tried deleting cookies for meet.jit.si? In particular, I notice that the Local Storage for meet.jit.si it records the userSelectedCameraDeviceId.
> 
> Side note: After playing around with the drop downs for a bit, I think they are a bit buggy. In particular, when I stop sharing my screen, my video often reverts to my other camera, but the drop down menu doesn’t reflect that.


When trying to change the camera the JS console shows this entry each time:

```
[modules/RTC/RTCUtils.js] <_newGetUserMediaWithConstraints/</<>:  
Failed to get access to local media. 
NotReadableError: Failed to allocate videosource 
{"video":{"height":{"ideal":720,"max":720,"min":240},"deviceId":"someid"},"audio":false}
```

This is probably related to Firefox only, as it works like a charm in the current versions of Chrome / Chromium 87.0.4280.66 and [Jitsi Meet Electron](https://github.com/jitsi/jitsi-meet-electron) 2.4.2 .

Maybe related:

https://github.com/jitsi/jitsi-meet/issues/4163

**Comment by vmario89** [comment]
have the same issue. works flawlessly in chrome :-(

**Comment by joelbu** [comment]
I can still reproduce this on Firefox 88.0.1 64bit on macOS Big Sur 11.3 on https://beta.meet.jit.si/ today.

If I initially choose the USB Camera in the permissions popup, I can't later switch to the Facetime Camera and vice-versa.

"Remember this the decision" does not seem to make a difference.
