### ISSUE TITLE
[Android] Debug build is not working with physical device

### ISSUE THREAD

**Issue by gouravrc** [jitsi/jitsi-meet#8364]
I tried to run debug build on my android physical device. I point out to the local server host and port. But the metro bundler is not started.

> Could not found development server...

Is there any issue running debug app in physical devices???

**Comment by saghul** [comment]
What environment are you running on? How are you running the app?

**Comment by gouravrc** [comment]
@saghul 
Here are the details

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 21.98 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9 => 16.9.0 
    react-native: github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551 => 0.61.5-jitsi.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by saghul** [comment]
> How are you running the app?

**Comment by gouravrc** [comment]
I am generating a debug signed apk on Android Studio. Then installing on my phone. ( having issues with usb cable ).

**Comment by saghul** [comment]
The bundler starts automatically when you run from Android Studio. Otherwise you can run `react-native start`

**Comment by gouravrc** [comment]
@saghul The bundler is starting. But it seems, the application in the physical device is failing to connect with the development server i,e. 192.168.XX.XX:8081. I am using a Samsung device. I am attaching a log that might help you to understand.


![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/41228535/104432894-7d043e80-55af-11eb-907e-5218ec9e0ddb.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/41228535/104432968-8f7e7800-55af-11eb-9ead-e6e45bc2eb10.png)
