### ISSUE TITLE
[BUG] Mobile App is not reporting bandwidth correctly

### ISSUE THREAD

**Issue by TheReal1604** [jitsi/jitsi-meet#8367]
### Description:

The mobile app is not reporting the used bandwith anymore. (N/A or 1 kbit/s) The connection indicator is turning red immediately if you enable video on the current version.

### Steps to reproduce:

1. Open a meeting
2. Join with the mobile app
3. Turn video on
4. watch the connection info of the mobile user, its just "N/A" or 1kbit/s and is not correctly reported anymore

### Expected behavior:

The mobile app should report the used bandwith correct, or the connection indicator is always red if you turn on video.

### Actual behavior:
The connection indicator is turning red and the used bandwith is not correct displayed.

### Server information:

- Jitsi Meet version: 1.0.4568-1
- Operating System: iOS / Webclient: Chrome

### Client information:

- Browser / app version: latest chrome
- Operating System: Windows / Linux

### Additional information:

![image](https://user-images.githubusercontent.com/5877910/104111261-48a72e80-52e0-11eb-96ce-8b98a7e9388a.png)

Also happened in p2p (turn) mode.

**Comment by saghul** [comment]
Can you reproduce this on meet.jit.si too? We recently switched how stats are generated on mobile, that's my main suspect.

**Comment by TheReal1604** [comment]
hey @saghul ,

yes it is also reproducible on meet.jit.si.

![image](https://user-images.githubusercontent.com/5877910/104154939-5c3cbd00-53e6-11eb-8679-4061e9b9e337.png)

App Version 20.6.0 build 101 iOS

**Comment by TheReal1604** [comment]
Are there some news on this? @saghul 

From my perspective this could be affecting all mobile users with the new app update. :-/

**Comment by saghul** [comment]
I'll be looking into this today.

**Comment by saghul** [comment]
I could reproduce this indeed. I'll be working on a fix shortly.

**Comment by saghul** [comment]
Caught and fixed the bug, new versions are coming to the stores soon.

**Comment by TheReal1604** [comment]
Thanks for the fast fix!

**Comment by saghul** [comment]
Thanks for the report!
