### ISSUE TITLE
In Android Kick-Out isn't working

### ISSUE THREAD

**Issue by Tarikul711** [jitsi/jitsi-meet#8369]
In Android 
`.setFeatureFlag("kick-out.enabled", false)`
this option isn't working.

**Comment by saghul** [comment]
What SDk version are you using?

**Comment by Tarikul711** [comment]
Currently, I am using `2.10.0`  version.
And I used this line of code:
`.setFeatureFlag("kick-out.enabled", false)`
It's not working for me. I want to off the kick-out option.
