### ISSUE TITLE
HSTS enabled by default

### ISSUE THREAD

**Issue by me-marcel** [jitsi/jitsi-meet#8376]
### Description:

The NGINX page config states that an HSTS header should be sent even when a self-signed certificate is present. This blocks the usage of the newly installed Jitsi instance until a Let's Encrypt certificate (or any other valid certificate) is deployed.

### Steps to reproduce:

1. Install Jitsi as described in the official quick start documentation (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)
2. Try opening your servers Jitsi URL without installing a Let's Encrypt certificate prior to accessing the URL. 

### Expected behavior:

If a self-signed certificate is present on the host the HSTS header should not be sent since it will prevent access to the page with most browsers otherwise. Jitsi should be able to run with a self-signed certificate by default.

### Actual behavior:

The HSTS header is set no matter what type of certificate is used. This is due to the line `add_header Strict-Transport-Security "max-age=63072000" always;` within the file `/etc/nginx/sites-available/<domain>.conf`

### Server information:

- _Jitsi Meet version:_
jitsi-meet:all/stable 2.0.5142-1
- _Operating System:_
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

### Client information:

- _Browser / app version:_
Google Chrome
Version 87.0.4280.141 (Offizieller Build) (64-Bit)
- _Operating System:_
Microsoft Windows
Version 1909 (OS Build 18363.1256)

### Additional information:

FYI: I seared the template file within all repos this organization has but couldn't find one. I'll leave that up to you.

**Comment by damencho** [comment]
You are talking about this: https://github.com/jitsi/jitsi-meet/blob/6f5534fcb67d2a3a9650502dc6d44cee6d42133c/doc/debian/jitsi-meet/jitsi-meet.example#L33 ?

**Comment by me-marcel** [comment]
> You are talking about this:
> 
> https://github.com/jitsi/jitsi-meet/blob/6f5534fcb67d2a3a9650502dc6d44cee6d42133c/doc/debian/jitsi-meet/jitsi-meet.example#L33
> 
> ?

Exactly.

**Comment by damencho** [comment]
As this is a security option and we should not drop it by default. It is better to just add a not in the handbook about it, how to solve the HSTS issue while testing.

**Comment by me-marcel** [comment]
A little side-note on this: This makes auto-provisioning Jitsi using scripts very difficult. Either having to do the workaround by disabling the HSTS header every time you provision a new machine or having to wait for your new DNS entry to be globally provisioned to be able to generate a Let's Encrypt certificate is very inconvenient. I definitely see the advantage but there is also a downside to this (as mentioned).

There should at least be an option to disable this during the installation routine (as with docker) so users can willingly choose to not take advantage of HSTS.

**Comment by damencho** [comment]
> There should at least be an option to disable this during the installation routine (as with docker) so users can willingly choose to not take advantage of HSTS.

So docker uses a separate set of configuration files so this can be added there.

**Comment by me-marcel** [comment]
This is not about Docker. I just wanted to give you an example here.

**Comment by damencho** [comment]
Well for docker you can add that as a parameter. For the default debian installation, that should be secure by default, that's why that is there and to handle this case a PR in the handbook is welcome to add the note. 
Currently the debian packages does not have a way to pass parameters to modify the template.

**Comment by me-marcel** [comment]
I know. That was the reason for this issue. It should have an option, shouldn't it.

**Comment by damencho** [comment]
The issue opened is that HSTS is enabled by default, and it should be that way. 
Any PRs are welcome that you can select to not enable it, but that is a huge task and may break many things around the packaging and needs a lot of testing.
