### ISSUE TITLE
enableClosePage on mobile App

### ISSUE THREAD

**Issue by AliKarpuzoglu** [jitsi/jitsi-meet#8383]
**Is your feature request related to a problem you are facing?**
After hanging up on the mobile app there is currently no way to visit a closing page. It's possible on the website though. We want to gather feedback from our users and would like feedback after calls

**Describe the solution you'd like**
Optional redirect on mobile pages

I am just wondering if this is in the current pipeline as I am starting work on this now

**Comment by saghul** [comment]
> I am just wondering if this is in the current pipeline as I am starting work on this now

Not on the immediate future.

**Comment by AliKarpuzoglu** [comment]
I have added this feature to our app, in case anyone still wants it. Hoppfoundation/jitsi-meet 

It Checks the config js and Opens a Modal when hanging up.
