### ISSUE TITLE
head.html, base.html and title.html NOT FOUND from /static/offline.html 

### ISSUE THREAD

**Issue by kiliankoller** [jitsi/jitsi-meet#8396]
### Description:

I see the following errors in my NGINX log:

2021/01/13 09:59:36 [error] 211646#211646: *154066 open() "/usr/share/jitsi-meet/static/head.html" failed (2: No such file or directory), client: 2001:16b8:6635:200:8d2a:8823:72ec:c3c0, server: sichere-videokonferenz.de, request: "GET /static/offline.html HTTP/2.0", subrequest: "/static/head.html", host: "sichere-videokonferenz.de", referrer: "https://sichere-videokonferenz.de/pwa-worker.js"
2021/01/13 09:59:36 [error] 211646#211646: *154066 open() "/usr/share/jitsi-meet/static/base.html" failed (2: No such file or directory), client: 2001:16b8:6635:200:8d2a:8823:72ec:c3c0, server: sichere-videokonferenz.de, request: "GET /static/offline.html HTTP/2.0", subrequest: "/static/base.html", host: "sichere-videokonferenz.de", referrer: "https://sichere-videokonferenz.de/pwa-worker.js"
2021/01/13 09:59:36 [error] 211646#211646: *154066 open() "/usr/share/jitsi-meet/static/title.html" failed (2: No such file or directory), client: 2001:16b8:6635:200:8d2a:8823:72ec:c3c0, server: sichere-videokonferenz.de, request: "GET /static/offline.html HTTP/2.0", subrequest: "/static/title.html", host: "sichere-videokonferenz.de", referrer: "https://sichere-videokonferenz.de/pwa-worker.js"

### Steps to reproduce:

1. 

### Expected behavior:

I think the problem is, that the file https://github.com/jitsi/jitsi-meet/blob/master/static/offline.html is referencing head.html, base.html and title.html in a relative way, but these files are in the folder above: https://github.com/jitsi/jitsi-meet

### Server information:

- Jitsi Meet version: 2.0.5390-1
- Operating System: Ubuntu 20 LTS

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Thank you for the report.
