### ISSUE TITLE
[Question] Different FQDN for JVB

### ISSUE THREAD

**Issue by schadom** [jitsi/jitsi-meet#8405]
Hello, 

i would like jitsi-docker to use a different FQDN for connecting to the JVB, so the Jisi web interface sould be reachable at https://meet.example.com but the JVB address will be meet-jvb.example.com:443/udp (primary jvb address) and meet-jvb.example.com:443/tcp (tcp fallback). I need this in order to work around ports 10000/udp and 4443/tcp which are commonly blocked by corporate firewalls.

Any clues on how this could be configured?  Maybe we would need some addtional configuration parameters in `.env` and `docker-compose.yml`? I see many people having this issue in the community. A solution for this would be quite nice!

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

You can control this with the domain setting in jvb, [more info](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md)
