### ISSUE TITLE
Audio Mute Alert in iOS/android

### ISSUE THREAD

**Issue by sachinhunasnale** [jitsi/jitsi-meet#8408]
Hi,
if user is on mute and try to speak, we need a mute alert in jitsi android/ios.
it supports on web, but in phone i am not able to see that alert message/notification.
if it supports, how should i enable it. I have already enabled the property in config file, but the alert is not showing up.

can I get any help.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by danygutmann** [comment]
but this alarm is very annoying. an "Ignore" flag would be great so that this alarm does not keep coming back

**Comment by sachinhunasnale** [comment]
> but this alarm is very annoying. an "Ignore" flag would be great so that this alarm does not keep coming back

@danygutmann ..., currently its not not showing any alert for me in ios and android app. its only working for web. so, can you please tell me how to enable it for ios/android app also.
Thanks.

**Comment by danygutmann** [comment]
Yes you are right. I'm sorry. Apparently the web client was started on the tablet. Sorry .
Then you can close this here
BR Daniel
