### ISSUE TITLE
JWT token not persisted on refresh

### ISSUE THREAD

**Issue by AjayShivanagol** [jitsi/jitsi-meet#8409]
Hi, I enabled JWT token for prosody and jitsi and I am able to join the conference using the JWT token. However, when I refresh the page since there is no JWT token in the browser it redirects to the login page Dialog. Is there a way to avoid this?

**Comment by disizlapeste** [comment]
hello.. @AjayShivanagol   @stavlevy  i've the same problem on my jitsi installation.... can you tell me how to resolve this please?
thanks in advance for your support..

**Comment by umstek** [comment]
If anyone else is looking for this and is willing to edit the source code, 

edit `react/features/app/middleware.ts` `_connectionEstablished` function or disable that middleware altogether.

https://github.com/jitsi/jitsi-meet/blob/831d39d4475ec0824c8b97f95476f70f22c3de50/react/features/app/middleware.ts#L44
