### ISSUE TITLE
how can change of directory jitsi-meet

### ISSUE THREAD

**Issue by cirelramos** [jitsi/jitsi-meet#841]
i adjunt a screenshot

https://s13.postimg.org/bu6rvyux3/Screenshot_from_2016_09_07_08_38_48.png

for example

https://10.0.0.22/test/videoCall/

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems before opening new issues.
I don't think this is currently possible without any modifications in jitsi-meet and maybe lib-jitsi-meet.
