### ISSUE TITLE
Participants do not see lobby display name when entering

### ISSUE THREAD

**Issue by sat-hub** [jitsi/jitsi-meet#8415]
Hello!

I’ve successfully installed jitsi-meet 2.0.5142 on Ubuntu 20.04 and enabled the lobby feature. Everything is working except for one detail: When a user enters a room from the lobby, the display name is not shown to the other participants. The new user is named “Fellow Jitster”, until he changes his name or re-enters the room a second time.

Steps to reproduce:

    Room admin creates room, activates lobby feature.
    Guest enters lobby, sets display name (“My Name”)
    Room admin gets notification that “My Name” wants to join and accepts.
    “My Name” enters room. It his view his name is “My Name”.
    Room admin and other participants see “Fellow Jitster”.

I am the only one who has this issue? Is this a bug that has been fixed lately?

I can reproduce this with Firefox and Chromium. I suspect that is has something to do with cookie or local storage.

Thank you!

**Comment by damencho** [comment]
Do you reproduce this with the latest stable?

**Comment by sat-hub** [comment]
Of course I will try the latest stable in the next days. I read through the forum and the issues here, but could not find something specific to my issue, so I wanted to create one and get answers if it is a known issue or similar.

**Comment by damencho** [comment]
The latest stable is on meet.jit.si, you can also try whether you repro there.

**Comment by sat-hub** [comment]
I checked meet.jit.si, I don't have my issue there. Interesting.
Today I installed the latest stable and had to update prosody config to re-enable the lobby feature. After testing it again, my issue is still existing. Again, interesting. So it may be no real issue in meet, but some configuration settings anywhere in the Jitsi stack..., or maybe a browser security issue? I don't have any clue.

**Comment by saghul** [comment]
meet.jit.si is ahead of stable. If you are using the Docker setup, the latest stable hasn't made it there yet.

**Comment by gaelgerard** [comment]
Bonjour @damencho and @sat-hub ,

I'm facing the same issue with the same situation.

 I installed the latest stable Jitsi meet and updated prosody to activate the lobby feature.

When a participant asks to join, its selected name appears on Moderator screen but when it is accespted to join, the  new participant appears with the DEFAULT_REMOTE_DISPLAY_NAME instead of the name he created.

If the participant logs in another room, with another name, the new name appears on Moderator screen but when its accepted, the previously created name appears instead of the newly created one and not the DEFAULT_REMOTE_DISPLAY_NAME anymore.

Could it be a cookie error ?

Thank you for your help

**Comment by Seferi** [comment]
Just upgraded the jitsi on my VPS and having the same issue.

**Comment by MarcoScammacca** [comment]
Hi, I compiled the stable version 5390 and I also have this anomaly. I'll give an example of use to explain myself better.
Active lobby:
A participant introduces himself to the moderator with a chosen name before requesting acceptance (for example "Carlo"), but once he enters the room his displayName is "retrieved" by the system. So if the participant logs in for the first time, everyone will see him as a "Fellow jitster".
If the participant then tries to access again as "John", the moderator sees him knock on the room as "John" but once inside the room everyone will see the previous name or "Carlo" ....

Only the participant will always see his name correctly.

Is it a displayName storage problem?

**Comment by damencho** [comment]
Do you reproduce this on meet.jit.si? I just tested there, I enter and enable lobby then open the incognito window so there is no display name set, I enter a new display name, and once the moderator accepts the lobby request and the user joins the moderator sees the correct display name.  Is this the use case you all test?

**Comment by gaelgerard** [comment]
> 
> 
> Is this the use case you all test?

It is! But actually the display name doesn't display on the Participant after it has been accepted. 

Participant gives its user name and asks to joint the room.
Moderator gets an alert with the participant's user name OK! and accepts the participant to join the room
Participant Thumbnail appears in Moderator room but the chosen user name of the participant isn't displayed and Moderator only see DEFAULT_REMOTE_DISPLAY_NAME ("Fellow jister" by default) for all participants.
The participant see his own display name he had chosen.

Let me know for further details.

**Comment by MarcoScammacca** [comment]
> Do you reproduce this on meet.jit.si? I just tested there, I enter and enable lobby then open the incognito window so there is no display name set, I enter a new display name, and once the moderator accepts the lobby request and the user joins the moderator sees the correct display name. Is this the use case you all test?

We just did a test on https://meet.jit.si/ and this anomaly doesn't show up.

https://meet.jit.si/ is one of the stable versions released, or is it part of a parallel development?

**Comment by damencho** [comment]
Normally meet.jit.si is ahead of stable. But at the moment it is the same as the stable.

**Comment by MarcoScammacca** [comment]
> Normally meet.jit.si is ahead of stable. But at the moment it is the same as the stable.

stable5390 ?

I have the stable one but it doesn't work the same way...

**Comment by damencho** [comment]
Yep stable 2.0.5390 which is jitsi-meet-web 4628. The one on meet.jit.si have [few changes](https://github.com/jitsi/jitsi-meet/compare/4628...release-4628-hf) about the iframeAPI, but nothing to the display name handling. 
Do you test the same way? Is there something different than the steps I explained with directly opening the link, any parameters, iframeAPI?

**Comment by gaelgerard** [comment]
> 
> 
> Yep stable 2.0.5390 which is jitsi-meet-web 4628. The one on meet.jit.si have [few changes](https://github.com/jitsi/jitsi-meet/compare/4628...release-4628-hf) about the iframeAPI, but nothing to the display name handling.
> Do you test the same way? Is there something different than the steps I explained with directly opening the link, any parameters, iframeAPI?

I installed the latest version from this link: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

After a Jitsi community user suggested me the How to I used (see my fist answer above) was outdated. But no luck, the problem is still here. Whether I open the room in an iframe or directly in my browser, the Moderator can't get participants names.

I can open a room for you to test if needed. 

Thanks

**Comment by damencho** [comment]
> I installed the latest version from this link: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

When was that? I mean, which version do you use? As there was an update last week.

Yep, send me a link to test it, that will help as I cannot reproduce the problem in any of the environments we have.

**Comment by gaelgerard** [comment]
> 
> 
> > I installed the latest version from this link: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
> 
> When was that? I mean, which version do you use? As there was an update last week.
> 
> Yep, send me a link to test it, that will help as I cannot reproduce the problem in any of the environments we have.

I think there is no way to send PM in github how can I send you the link? Moreover, I use a password to create rooms do I'll need to open it unless I can disable it for a moment perhaps.

I reinstalled from scratch yesterday 20th january 21 jitsi-meet/stable,now 2.0.5390-2

Thank you for your help

**Comment by damencho** [comment]
Send it to damencho AT jitsi dot org.

**Comment by gaelgerard** [comment]
Bonjour @damencho, I sent you an email!

**Comment by MarcoScammacca** [comment]
> Yep stable 2.0.5390 which is jitsi-meet-web 4628. The one on meet.jit.si have [few changes](https://github.com/jitsi/jitsi-meet/compare/4628...release-4628-hf) about the iframeAPI, but nothing to the display name handling.
> Do you test the same way? Is there something different than the steps I explained with directly opening the link, any parameters, iframeAPI?

No, the only difference is that the opening of a room takes place with the Lobby immediately active.
The change I made consists of a few lines as I told you here:

https://community.jitsi.org/t/lobby-room-enabled-by-default/82765/15


From what I have read from the indications of different users, it seems that the stable 5390 (while installing it in different ways (by recompiling the sources, aptget ...) has this anomalous behavior of the displayName, with or without our further developments.

Available for other clarifications
Marco

**Comment by gaelgerard** [comment]
> No, the only difference is that the opening of a room takes place with the Lobby immediately active.
> The change I made consists of a few lines as I told you here:
> 
Also forgot to mention I added a script to enable Lobby by default:

> This is not that difficult, I just added this hook in lobby prosody plugin file.
> 
```
     host_module:hook('muc-set-affiliation', function(event)
               if jid_split(event.jid) ~= 'focus' and event.affiliation == 'owner' then
           	    handle_create_lobby(event);
              end
       end);
```
> 
> This enables lobby whenever a meeting is started.

As described here: https://community.jitsi.org/t/start-a-room-with-lobby-enabled/79279/3

**Comment by gaelgerard** [comment]
Last precision (I think).

When a Participant double click on its display name inside the Room, it is automatically updated for the moderator.

Hope it helps and also available for further details.

**Comment by damencho** [comment]
I think I reproduced this, it happens only if `prejoinPageEnabled: false`. So the workaround till we fix this is to enable pre-join.

**Comment by gaelgerard** [comment]
I can confirm @damencho , enabling pre-join solved the problem for me!

Merci beaucoup, Thank you very much
