### ISSUE TITLE
Shortcuts also for Phone Apps

### ISSUE THREAD

**Issue by danygutmann** [jitsi/jitsi-meet#8420]
Many children are currently using JitsyMeet on the phone / tablet. It would be very helpful here if the shortcuts worked here.

**Comment by saghul** [comment]
You mean keyboard shortcuts? How would one type them on a phone?

**Comment by danygutmann** [comment]
By using a BLE keyboard? It’s more easy for the kids instead tapping on screen

**Comment by saghul** [comment]
Sure, using an external keyboard is about the only way.

> It’s more easy for the kids instead tapping on screen

That's an interesting observation which IIRC nobody has brought up before.

FWIW we have no shortcuts at all on mobile, so they'd need to be added from scratch.

**Comment by danygutmann** [comment]
I can observe it all the time when the teachers tells the kids „you are on mute“ and they have Problems to switch...

by the way, in the main activity is a method onKeyUp - I thought this can be extended

**Comment by AliKarpuzoglu** [comment]
this would also be handy for ipad users that have keyboard covers

**Comment by danygutmann** [comment]
what a bullshit! Now you've made the buttons half the size - no longer usable for a first grader.
one more reason to activate the key control...

**Comment by saghul** [comment]
This attitude won't get you any good results.
