### ISSUE TITLE
Firebase not installed in jitsi project 

### ISSUE THREAD

**Issue by eraArya2601** [jitsi/jitsi-meet#8424]
I am using https://github.com/jitsi/jitsi-meet/issues repo for android 
but 'react-native-firebase' not installed in project when i am adding this plugin issues arises.
**Issue**
A problem occurred evaluating project ':@react-native-firebase_app'.
> Could not find method platform() for arguments [com.google.firebase:firebase-bom:26.2.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

If I am trying to update gradle version then this issue comes 'Cannot get property 'mavenRepo' on extra properties extension as it does not exist in react native jitsi meet'

react-native version:-0.63.0
Android studio version:-4.1.1

Please help me out .Thanks in advance

**Comment by saghul** [comment]
Can you please provide more details on what you are trying to do?

**Comment by eraArya2601** [comment]
@saghul ,I am downloading jitsi project and add react-native-firebase plugin i.e.5.6.0 but when app is running its show error 
**'RNFirebase core module was not found natively on Android, ensure you have correctly added the RNFirebase and Firebase gradle dependencies to your `android/app/build.gradle` file.**

and if change plugin @react-native-firebase/app then show error
**Could not find method platform() for arguments [com.google.firebase:firebase-bom:26.0.0]**

and if changing gradle version 4.10.1 to 5.1.1 or 6 something then show maven error i.e.
**A problem occurred evaluating root project 'jitsi-meet'.
> Cannot get property 'mavenRepo' on extra properties extension as it does not exist**

please suggest what I am doing wrong.

**Comment by saghul** [comment]
Ah that. Our project has some departures from a standard RN project, so you need to link the packages manually. Specifically, here: https://github.com/jitsi/jitsi-meet/blob/b65e61f6330ada760c8352669b361f9d0ed254b9/android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java#L180
