### ISSUE TITLE
Layout issue with DISPLAY_WELCOME_FOOTER: true

### ISSUE THREAD

**Issue by cketti** [jitsi/jitsi-meet#8428]
### Description:

With `DISPLAY_WELCOME_FOOTER: true` in `interface_config.js` the layout of the welcome page is off. The meetings list is aligned to the bottom of the page. Depending on the screen size there can be a huge gap between the header and the meetings list.

![jitsi_welcome_page_layout](https://user-images.githubusercontent.com/218061/104763597-6fdd8000-5766-11eb-83d5-052a88a9be4e.png)

(The dark strip at the bottom of the screenshot is from another window so you can see where the browser window ends)

### Server information:

- Jitsi Meet version: 2.0.5390
- Operating System: Debian

### Client information:

- Browser / app version: Chrome/Firefox
- Operating System: Ubuntu

**Comment by amsnek** [comment]
can confirm, my current workaround is (in case you want to disable the footer), to enable the footer and "hide" it via css

<style>
.welcome .welcome-footer {
    visibility: hidden;
}
</style>

in jitsi-meet/plugin.head.html

**Comment by escribiendocodigo** [comment]
Para no mostrar el footer en la página de bienvenida  debes editar la opción DISPLAY_WELCOME_FOOTER en el archivo interface_config.js

```js
DISPLAY_WELCOME_FOOTER: false,
```

CSS Trick

``` css
#welcome_page {
    justify-content: start;
}
```

**Comment by saghul** [comment]
Ping @muscat1 @vp8x8

**Comment by cketti** [comment]
This seems to be fixed in the latest version :+1:
