### ISSUE TITLE
Jitsi Meet Feature Configuration

### ISSUE THREAD

**Issue by xamlzealot** [jitsi/jitsi-meet#8434]
Having installed jitsi meet per common documentation on Ubuntu 18.04.5 LTS, I have basic functionality, but that's about it. Features that do not seem to work:

- Desktop Sharing
- Set Meeting Password
- Enable Lobby
- E2EE

root@jitsi:~# dpkg -l | grep jitsi
ii  jitsi-meet                       2.0.5390-1                               all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody               1.0.4628-1                               all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver            1.0.4628-1                               all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                   1.0.4628-1                               all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config            1.0.4628-1                               all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2               2.1-416-g2f43d1b4-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)

Presumably I'm missing something simple, but someone with more experience using jitsi on Ubuntu might be able to offer quick solutions. Thanks in advance

**Comment by damencho** [comment]
Please, when you have problems or questions use the community forum before opening new issues, thank you.

What browser do you test the desktop sharing?
Which prosody version do you use, you need prosody 0.11 for lobby?

**Comment by xamlzealot** [comment]
> Please, when you have problems or questions use the community forum before opening new issues, thank you.
> 
> What browser do you test the desktop sharing?
> Which prosody version do you use, you need prosody 0.11 for lobby?

My apologies, I did not intend to skip a step (forum). 0.11.7-1 for prosody version according to grep:

root@jitsi:~# dpkg -l | grep prosody
ii  jitsi-meet-prosody               1.0.4628-1                               all          Prosody configuration for Jitsi Meet
ii  prosody                          0.11.7-1~bionic4                         amd64        Lightweight Jabber/XMPP server
