### ISSUE TITLE
Optional ringing like telephone when room just created and no one else is joined

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#8436]
**Is your feature request related to a problem you are facing?**
We are using Jitsi as a audio and video conferencing system for Rocket.Chat messenger.
Out user frequently ask for a calling feature like in WhatsApp, Telegram or Skype have.
Here is a Rocket.Chat feature request https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2129

**Describe the solution you'd like**
I think technical solution could be like this.
Jitsi gets optional (admin can turn it on/off) feature which is playing some ringing sound when room just created and there is only creator in room. When first participant are joined - ringing is stopped.

**Describe alternatives you've considered**
All popular massagers with conferencing opportunities have ringing functionality (looks like a telephone call).
Jitsi can do a first step to that.
I know, Jitsi is a bit different conferencing system and could be hardly compared to phone calls, but anyway some solution will be appreciated.

**Comment by saghul** [comment]
I think this can be implemented outside of Jitsi, in the embedding app. The next SDK version (3.0) will have participant joined / left events, so you'd be able to start a ringtone when conference is joined, while there is no other participants.

Do you think this would solve your problem?

**Comment by ankar84** [comment]
> Do you think this would solve your problem?

I guess it will!
Thanks a lot fir such quick reply 👍🏻

**Comment by solutionprovider9174** [comment]
Yes. it is not fixed yet. i am waiting also solution.

**Comment by saghul** [comment]
As I said on my comment we won't be implementing this. We do have the aforementioned events so you can implement it outside of the SDK.
