### ISSUE TITLE
Very specific room name causes a crash

### ISSUE THREAD

**Issue by MGelein** [jitsi/jitsi-meet#8438]
### Description:
When opening a room with the following name: `SecretSocietyl3fdnj` you are met with the "Something went wrong screen" upon joining. It will attempt to reconnect in 20 seconds, but start failing in a loop. A `allocateConferenceFocusError` is raised everytime you try to connect. Any other meeting name will not provide issues.

### Steps to reproduce:
1. Go to [https://meet.jit.si/SecretSocietyl3fdnj](https://meet.jit.si/SecretSocietyl3fdnj)
2. Join the meeting, but instead crash

__Optional, to reproduce in app__:
1. Join a meeting with name: `SecretSocietyl3fdnj`
2. Watch the meeting crash.

### Expected behavior:
You should join the meeting

### Actual behavior:
Upon joining you see the "Something went wrong" notification. The console contains the following log:

![console_log](https://interwing.nl/downloads/jitsi_error.png)

A `allocateConferenceFocusError` is raised everytime you try to connect.

### Server information:
This bug occurs using the default meet.ji.si server

### Client information:
Browser: Firefox, Chrome, Edge, __it even happens in the official Android app__
OS: Windows 10, Android

### Additional Information
This bug was initially found by using the IFrame API, but it also occurs in the hosted version on meet.jit.si and the official android app.

**Comment by damencho** [comment]
We are doing a new release to address this instability. 

Please when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by MGelein** [comment]
Sorry for the inconvenience in that case. I thought I had a clear bug, so reasoned that an issue on github was the proper way forward. I thought the forum was for problems with how to use the software.

This is not an instability issue by the way. I am completely unable to connect. I will be looking forward to the next version in that case.

**Comment by damencho** [comment]
Change the room name and you should land on a different shard. 

This particular problem is with the meet.jit.si environment and has nothing to do with jitsi-meet and actually was a bug in jicofo.
This is the reason asking people to rise problems there in the community forum and if we come to a conclusion this is a bug, we then ask people to file the bug in the appropriate repo.

**Comment by MGelein** [comment]
Thanks for your reply and explanation of what was happening. I must have missed or glossed over the part where I should have read that I should post on the community forum first. 

I already noticed that changing the room name resolved the issue, I just found it a very peculair issue that this __one__ name but not any permutation of it crashed.

**Comment by damencho** [comment]
Well that room has stuck to a shard with a problem that's the reason, the new room land on a new healthy shard
