### ISSUE TITLE
Jitsi-Meet Release 2.0.5390: defaultLanguage settings not used for welcomePage and PrejoinPage & modified .json files not being used anymore

### ISSUE THREAD

**Issue by amsnek** [jitsi/jitsi-meet#8444]
### Description:

Since the latest release (2.0.5390) the defaultLanguage setting has no effect on the WelcomePage and PreJoinPage. Thus things like welcomepage.appDescription cannot be modified. Cutomizing welcome Text seems not possible in this release. 

### Steps to reproduce:

1. Edit "config.js" 
2. set (for example): defaultLanguage: 'de',
3. edit interface_config.js -> set LANG_DETECTION: false,  #(just to be sure)
4. edit lang/main-de.json 
5. add for example a custom "appDescription"
6. visit the welcome page -> it will be english and not use the modifications

### Expected behavior:

Visiting the Welcome Page should reflect the changes (example: modified welcome text)

### Actual behavior:

default english welcome Text ist displayed, no modifications are applied. It will say "Secure and high quality meetings" or whatever the default english text is. 

### Server information:

- Jitsi Meet version: 2.0.5390
- Operating System: Linux

### Client information:

- Browser / app version: any (pc/mobile/otherwise)
- Operating System: any

### Additional information:
none

**Comment by saghul** [comment]
Does manually changing the language in the settings panel work?

**Comment by amsnek** [comment]
In the Settings Panel (on Welcome Screen) -> it already has DE selected -> i switched to EN and back to DE ->did not change the Appdescription / Title.

Switching Languages *does* work for menu items in settings and for the "meetings-list" ("Your recent list is currently empty...") but not elements in the header-container it seems (Header Title "Jitsi Meet" and Subtitle "Secure and high quality meetings"). The Enter-Room-Button (from welcome Page) "Start Meeting" does not change either.

**Comment by rasos** [comment]
Confirmed. We've patched the branding meanwhile by adding in `all.css`

```
.welcome .header .header-text-title{visibility: hidden;}
.welcome .header .header-text-title::after{content: 'Videokonferenz jetzt starten';visibility: visible;display: block;}
.welcome .header .header-text-subtitle{visibility: hidden;}
```

**Comment by tgeimer** [comment]
I had the same problem and noticed that some language variables seem to be missing in /usr/share/jitsi-meet/lang/**main-de.json**
Adding them fixed the problem for me.
```
"welcomepage": {
...
        "headerTitle": "Title",
        "headerSubtitle": "My Header Subtitle",

```
They are present in /usr/share/jitsi-meet/lang/**main.json**

**Comment by JtheSaw** [comment]
The tag for `startMeeting` which is displayed on the button is also missing in `/usr/share/jitsi-meet/lang/main-de.json` and can be added manually. (See previous comment by @tgeimer)

**Comment by tgeimer** [comment]
I found another variable which was missing in my _/usr/share/jitsi-meet/lang/main-de.json_.  But looking at the current repo code it seems to be fixed. Anyways - for those who run into this issue like me:
When using authentication if you want to customize the login credential overlay in your language, you need to add the variable _user_ while _userPassword_ was already there.
```
"dialog": { 
        [...],
        "user": "user.name",
        "userPassword": "user.password",
        [...],
}
```

**Comment by saghul** [comment]
These things happen as we change the layout, which thankfully doesn't happen too often. A PR adding the missing tranlations to the language files would help.

**Comment by tgeimer** [comment]
Next time :-) I'm starting to get more into working with github...
