### ISSUE TITLE
Video Disappearing In Group Calls

### ISSUE THREAD

**Issue by behzadhaghgoo** [jitsi/jitsi-meet#8448]
I have created an app hosting video calls on meet.jit.si and we are facing issues with group calls. Basically since two days ago calls with more than 2 people that have video seem to buggy as some participants lose videos of others. I have tried with several internet connections and computers and all seem similar. And it didn't happen in a month long time before that we were using this service. Would really appreciate if you can help.

**Comment by damencho** [comment]
We were having some issues on meet.jit.si for the last few days, those are resolved now.

Please in the future when you have problems or questions use the community forum before opening new issues. Thank you.
For example, this is a problem with meet.jit.si deployment and have nothing to do with jitsi-meet project.
