### ISSUE TITLE
basic-authentication broken on Chromium restart, pwa-worker.js?

### ISSUE THREAD

**Issue by pobv** [jitsi/jitsi-meet#8449]
### Description:

We use basic authentication with apache2 to prevent unauthorized access. In the current version of jitsi this works the first time. But when the browser ist closed, on next start we get a message that access is unauthorized but no possibility to enter authorization. This happens with newer versions of chromium-based browsers. Apparently, there is a bug/feature [https://bugs.chromium.org/p/chromium/issues/detail?id=1055253] in newer chromium browsers that workers do not ask for basic-authentication (and workers have recently been added to jitsi?). As Chromium-Browsers are basically the only ones where all other features work, and the bug/feature is unlikely to be fixed, this is a bummer. After pressing Ctrl-Shift-R (which seems to start everything anew) it works again until the browser is closed and opened again.

### Steps to reproduce:

1. Configure the Use of Basic-Authentication
2. Log in and use a room with a recent Chromium based browser
3. Close the browser
4. Start the browser
5. go to the room again, it shows unauthorized

### Expected behavior:

On step 5 either it should just work or a pop up should ask for authentication

### Actual behavior:

Unauthorized  Message appears, no request for authentication details.

### Server information:

- Jitsi Meet version:
ii  jitsi-meet                           2.0.5390-2                               all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                   1.0.4628-1                               all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                       1.0.4628-1                               all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                1.0.4628-1                               all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                   2.1-416-g2f43d1b4-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)

- Operating System:

debian 10.7
apache 2.4.38-3+deb10u4

### Client information:

- Browser / app version: Chromium, Google Chrome, Microsoft Edge
- Operating System: Windows, Linux, MacOSX

### Additional information:

Workaround appreciated. E.g. a configuration item where one could disable all features preventing basic-authentation (basically, not using pwa-worker.js?)

**Comment by saghul** [comment]
> We use basic authentication with apache2 to prevent unauthorized access.

Have you considered using XMPP internal authentication with Prosody?

> and workers have recently been added to jitsi?

Yes, there is a service worker to make Jitsi Meet a Progressive Web App (PWA).

> As Chromium-Browsers are basically the only ones where all other features work

What features are you trying to use which don't work in browsers other than Chrome? E2EE is the only one I can think of.

As you pointed out, this seems to be a browser bug, I don't see what we can do about it. You can try to edit index.html in /usr/share/jitsi-meet/ and remove this section: https://github.com/jitsi/jitsi-meet/blob/a39905883fffb967f11977edac860784fb127427/index.html#L28-L39 that will prevent the worker from being registered.

Going forward, I'd recommend you use other authentication mechanisms such as Prosody's internal auth.

**Comment by pobv** [comment]
Thanks for the hint. Removing the section did indeed help. Now one has to relogin after the browser has been closed; which is perfectly fine! We would greatly appreciate if that would stay an option for the foreseeable future (so please do not rely on the worker).

We are running the jitsi for a couple of hundred users - no way to restrict browser and os. Chromium actually behaves best when switching rapidly between screensharing and camera as well as behaves best when integrating people with vodafone shared medium internet (RTT fluctuations causing quality reductions). Firefox has greatly improved the last couple of month, but running a meeting for 20 people with chromium and for 20 people with firefox is a huge difference (chromium provides better quality (fewer reductions of quality in a meeting) and is more stable (more quickly recovers after reduction in image quality) and more stable when sharing desktops [which again contain say a live document camera in parallel to an IDE]).

We are experimenting with the other authentication options and are making progress, but as of now, we are asked for the authentication for every room (which is rather annoying as some switch very quickly between breakout rooms by just appending a number on the url. I can check 10 rooms in 2 seconds right now, as basic authentication is kept. Thus, setup and user experience (we want to allow everybody within the orginzation to do everything as in an open environement) is perfect right now as it is.

Thanks for the quick response and thanks for jitsi.

**Comment by xiconfjs** [comment]
@saghul Can you explain, why removing these lines is "fixing" (yes, it's just a workaround) this problem? Would be helpful to forward these information to the Google Chrome team.

Thanks xiconfjs

**Comment by saghul** [comment]
@pobv Thanks for the feedback!

> Thanks for the hint. Removing the section did indeed help. Now one has to relogin after the browser has been closed; which is perfectly fine! We would greatly appreciate if that would stay an option for the foreseeable future (so please do not rely on the worker).

We don't rely on the worker, but it needs to be there so Jitsi Meet can be used as a PWA, and due to how service workers are registered (really early, before any app code has run) there is no way for us to provide an option for this.

> We are experimenting with the other authentication options and are making progress, but as of now, we are asked for the authentication for every room (which is rather annoying as some switch very quickly between breakout rooms by just appending a number on the url. I can check 10 rooms in 2 seconds right now, as basic authentication is kept. Thus, setup and user experience (we want to allow everybody within the orginzation to do everything as in an open environement) is perfect right now as it is.

When you use XMPP auth you can configure Jicofo to do session caching, so your credentials are saved and not required for a given period of time.

> Can you explain, why removing these lines is "fixing" (yes, it's just a workaround) this problem? Would be helpful to forward these information to the Google Chrome team.

My suspicion is that when the worker is loaded, counts as an attempt to load a page and thus use basic auth, which will fail, and Chrome may choose to never ask again until you reload. I wonder if you could just require no auth for the /static/ route...

I'm going to close this since there is nothing actionable from the Jitsi Meet side of things.
