### ISSUE TITLE
How to revert to old start page?

### ISSUE THREAD

**Issue by pandel** [jitsi/jitsi-meet#8452]
Hello!

Is it possible to revert to the old start page without any quirks only by swapping out the web folder from an older version?

We made some heavy script-controlled customizations to the start page which don't work anymore with the new design, so we would like to revert to the old one.

Regards,
Holger

**Comment by damencho** [comment]
Please use the community forum when you have questions and problems before opening new issues, thank you.

You can extract the old code into a subfolder and just change the root folder in the webserver to point there.
