### ISSUE TITLE
Semi-low bandwidth/CPU mode: ability to turn off other participants' videos but keep uploading my video

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet#8457]
In some cases where there are many participants, I've seen computers unable to cope with having video both ways (many symptoms related to issue #5816); the problem is that the audio quality slider only has four levels:

1. Low bandwidth
2. Low definition
3. Medium definition
4. High Definition

The problem are:
* "low bandwidth" forces my webcam to be turned off, but sometimes I'd want to be able to disable others' videos while keeping my own webcam active
* it's not totally clear what the difference between medium definition and the others is (I assume low is SD, medium is 720p and high is 1080p, but it's not written in the UI)

To me, there's an in-between state missing, for less powerful computers: I would like to have a low resources mode where you can upload your video but disable receiving others' videos, to lower your CPU usage. I don't necessarily need to see others, but they would probably appreciate seeing me.

So this is what I'd expect instead:

1. Low bandwidth (disable all video)
2. Low resources (hide others' videos)
3. Low definition
4. Medium definition (720p)
5. High Definition (1080p)

**Comment by saghul** [comment]
>     * it's not totally clear what the difference between medium definition and the others is (I assume low is SD, medium is 720p and high is 1080p, but it's not written in the UI)

It depends on configuration, but by default: High is 720p, Mid is 360p and Low is 180p.

> To me, there's an in-between state missing, for less powerful computers: I would like to have a low resources mode where you can upload your video but disable receiving others' videos, to lower your CPU usage. I don't necessarily need to see others, but they would probably appreciate seeing me.

I beg to differ. Seeing no one on the other side but knowing they can see you is very awkward to me.

Here is another idea: a "single speaker only mode. You'd be able to send your video (or not, by just muting) but received videos would be limited to 1. This way, unless you pin a specific speaker you'd be receiving video for the active speaker always. Or the one you chose of course, but only one.

**Comment by tgeimer** [comment]
I like both approaches. Either way - it would be awesome to have some sort of mode to reduce CPU usage on individual clients.
This would especially help in virtual desktop environments!

In our environment (was designed before covid and the need of everyone wanting to use video conferences) when let's say five sessions run on a citrix worker and one of them starts a jitsi meeting this session hugs about 75 - 90% of the server's CPU power. This CPU hunger not only results in a poor video conference for the single user but also degrades overall performance for the other sessions on the server as well.
This feature could be a major advantage to set jitsi apart from other video conference systems like goToMeeting, MS Teams etc. which all have the same or even worse CPU hunger.

**Comment by aguilalibre** [comment]
> This way, unless you pin a specific speaker you'd be receiving video for the active speaker always. Or the one you chose of course, but only one.

That is an awesome idea. Definitely will set Jitsi apart as tgeimer says. Most of the time the overall quality degrades when more than one participant has a Camera turned on. I'm talking about developing countries with low resources (internet and computers / mobile cappabilities). Hopefully we can see this feature in the future.

**Comment by saghul** [comment]
You can already do this by using `#config.channelLastN=1` in the URL.

**Comment by lma-gh** [comment]
@saghul 

> I beg to differ. Seeing no one on the other side but knowing they can see you is very awkward to me.
For me, it is *essential*. When you are on a limited mobile plan (and no WiFi is available) and you want to "live stream" an event or an object (e.g. house viewing, reporting from a crisis area, or just letting the other participants enjoy the view of the trail you are hiking), you want to save bandwidth, for which switching off other participants' video stream is a perfectly suitable measure.

**Comment by saghul** [comment]
We have a new performance meter now that lets one select between best performance vs best quality.

**Comment by youdontneedtoknow22** [comment]
> We have a new performance meter now that lets one select between best performance vs best quality.

Can you please elaborate on what performance and quality mean?
Best performance: Camera will be disabled so that other participants can hear you more clearly
Best quality: Camera will be turned off to save bandwith
Or how does this work? Didn't find any infos in the jitsi web client too (it would be good to add such description to other users)
