### ISSUE TITLE
Mute Everyone Button appears even when it shouldn't 

### ISSUE THREAD

**Issue by AliKarpuzoglu** [jitsi/jitsi-meet#8464]
### Description:

In the App, even when the participant is not a moderator, the mute everyone button appears

### Steps to reproduce:

join a room as a non moderator - open the overflow menu - you can see the mute everyone button
### Server information:

- Jitsi Meet version: 
- Operating System:

### Client information:

- Browser / app version: 20.6.2 app
- Operating System: iOS

### Additional information:
in MuteEveryoneButton.js we check for
`  visible: visible && isModerator && !disableRemoteMute` 
but visible and disableRemoteMute could be undefined.  When we check for this, visible will often be undefined and thus visible, even if the button has no effect.

to fix this we could invert all the checks to avoid undefined variables:

`!(!visible && disableRemoteMute && !isModerator)` 

seems to be working for me.   
Explanation:

the expression will be true if: visible is true or undefined AND disableremotemenu is true or undefined AND you are a moderator (or it's undefined, which should not happen I think)

**Comment by damencho** [comment]
Where do you reproduce this? I tested on meet.jit.si and I cannot reproduce.

**Comment by saghul** [comment]
`visible` defaults to true (it's in defaultProps of AbstractButton) not sure how it could end up being undefined.

**Comment by AliKarpuzoglu** [comment]
On meet.jit.si I was able to open the Lobby Mode even as a second user, im not sure how I could not have the rights there... maybe you can try on meet.ffmuc.net... 
![F7260947-AF9D-4298-B330-DFBF0FCC5D6B](https://user-images.githubusercontent.com/9629776/105520357-e9332080-5cda-11eb-86b4-7f141dd12e63.png)

here’s a Screenshot...

@saghul that’s a good point.. I think because it gets assigned from ownprops that maybe there is an issue?

**Comment by damencho** [comment]
Try meetings using `moderated` as tenant. https://meet.jit.si/moderated/<someroomname>

**Comment by AliKarpuzoglu** [comment]
> Try meetings using `moderated` as tenant. https://meet.jit.si/moderated/

Ok, so now I did this:

1. on my Computer browser go to https://meet.jit.si/moderated/ali123
2. join on my iPhone with the current Jitsi Meet App

The mute everyone button appears..

**Comment by damencho** [comment]
🤦 I see your screenshot now ... it is no mobile ... So @saghul I reproduce this on jitsi-meet app locally, so its a bug in the mobile app.

**Comment by saghul** [comment]
Gotcha. I'll take a look, cheers!

**Comment by ivorcho** [comment]
Hello 👋  What's the progress on this issue? I can confirm that it is still happening on jitsi official mobile sdks `v3.5.0`. It is the same case with the "Disable everyone's camera" button. Even though I am not a moderator I still see it, but it is not functional.

**Comment by pierreozoux** [comment]
I just checked, this is fixed.
