### ISSUE TITLE
Lobby feature not available anymore

### ISSUE THREAD

**Issue by AlphaDE** [jitsi/jitsi-meet#8466]
Using Jitsi 2..5390-3 on Ubuntu 20.04.1 LTS from repository, prosody 0.11.4

The new lobby feature (requiring guests either to get accepted by a moderator or using a configured password to enter a room) was configured and did work properly in DOMAIN.cfg.lua

`VirtualHost "guest.DOMAIN"`
`    authentication = "anonymous"`
`    c2s_require_encryption = false`
`    modules_enabled = {`
`        "muc_lobby_rooms";`
`    }`
`    lobby_muc = "lobby.DOMAIN"`
`    main_muc = "conference.DOMAIN"`

`Component "lobby.DOMAIN" "muc"`
`    storage = "memory"`
`    restrict_room_creation = true`
`    muc_room_locking = false`
`    muc_room_default_public_jids = false`

From the prosody log, the component is loaded

`Jan 23 15:27:29 conference.DOMAIN:muc_domain_mapper     info    Loading mod_muc_domain_mapper for host lobby.DOMAIN!`
`Jan 23 15:27:29 guest.DOMAIN    info    Lobby component loaded lobby.DOMAIN`

Nevertheless all options for the lobby to activate it after opening the room as moderator are gone and not shown anymore.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues, thank you.

muc_lobby_rooms needs to be enabled only under the main virtual host.

**Comment by AlphaDE** [comment]
Thanks, but that was not mentioned in the Jitsi release notes... and looks I was not the only one running into it.
