### ISSUE TITLE
Conference terminated automatically after some time in Android SDK

### ISSUE THREAD

**Issue by soethan98** [jitsi/jitsi-meet#8467]
### Description:

Conference terminated with error 'focus.left' or some time with error disconnected after spending sometime in meeting room .If there is more than one person in meeting room, above error occur.It only happen in android sdk.

### Expected behavior:
The expected behavior is to stay in room until user leave the meeting.

### Actual behavior:
We are using custom server URL,so if we join the meeting with custom URL, conference terminated with disconnected error if there is one than one user.

### Client information:
I used android sdk version 2.11.0.

### Additional information:
I already checked server certificate validation with https://whatsmychaincert.com. And meeting working well with "meet.jit.si" but not with custom URL.

Any help or suggestions will be helpful.

**Comment by usamawork61** [comment]
@soethan98 did you find anything on this?
