### ISSUE TITLE
Black screen when attempting full-screen-share from Chromium on Debian 10 on meet.jit.si

### ISSUE THREAD

**Issue by pgenderson** [jitsi/jitsi-meet#8472]
Starting a screenshare 'works' (this was only tested with two people, so me and someone else) but only my mouse can be seen; everything else is black. Not sure if this is related to any of the other screenshare issues people have. My PC's a Dell Optiplex 3020. I just upgraded my system to make sure. I also enabled lobby mode before joining from another device and attempting the screenshare.

**Comment by damencho** [comment]
There is nothing we can do about this, the screen sharing is implemented in the browsers. I have seen several issues reported for example incompatibility with wayland xserver or something like that. You can search in your browser issues tracker for problems like this, specific to linux setup and if you cannot find your case reported so the browser's developers can work on it at some point.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues. Thank you.
