### ISSUE TITLE
Allow to enforce apache

### ISSUE THREAD

**Issue by jotoeri** [jitsi/jitsi-meet#8474]
**Is your feature request related to a problem you are facing?**
We have apache as well as nginx installed on our server. This is due to another software (onlyoffice) uses nginx internally, but on the front we use apache to proxy requests. Therefore, apache occupies ports 80/443, which leads the installation of jitsi to fail.

**Describe the solution you'd like**
It would be really nice if one could enforce the usage of apache for postinstallation script.
As it seems to me, the easiest way would be to pre-configure a debconf variable (e.g. `jitsi-meet/enforce_apache`?), which just skips the nginx-check on postinstallation if set.
It's a very short 3-liner, so if you're ok with, i would be happy to create a PR for... 😉 

**Describe alternatives you've considered**
- Uninstall nginx and reinstall afterwards? 👎 
- Reset the whole server and install jitsi first? 😞 

Greets! :)
Jonas

**Comment by damencho** [comment]
This is already the case, we check whether apache2 is installed and if that is the case we configure apache2: 
https://github.com/jitsi/jitsi-meet/blob/d35708815da58bb65a70d98d9ee3aa3d97d0a8e8/debian/jitsi-meet-web-config.postinst#L67
Maybe you are hitting some bug or something.
What is the output of that command: `dpkg-query -f '${Status}' -W 'apache2' 2>/dev/null | awk '{print $3}'`

**Comment by jotoeri** [comment]
Hey @damencho,
thank you for that quick response! :)

The output for your Query is `installed`. But the output for the corresponding nginx-term in Line [#L56](https://github.com/jitsi/jitsi-meet/blob/d35708815da58bb65a70d98d9ee3aa3d97d0a8e8/debian/jitsi-meet-web-config.postinst#L56) is also `installed`. This leads to the situation, where both variables `FORCE_APACHE` and `FORCE_NGINX` are set.

But then in Line [#L167](https://github.com/jitsi/jitsi-meet/blob/d35708815da58bb65a70d98d9ee3aa3d97d0a8e8/debian/jitsi-meet-web-config.postinst#L167), `FORCE_NGINX` is checked in the `if`-statement, while in Line [#L197](https://github.com/jitsi/jitsi-meet/blob/d35708815da58bb65a70d98d9ee3aa3d97d0a8e8/debian/jitsi-meet-web-config.postinst#L197) `FORCE_APACHE` is only checked via the respective `elseif`, so only if `FORCE_NGINX` was **not** true (not installed).

=> This leads to my situation, where both (nginx/apache) are installed and the script just takes nginx, while i am unable to intentionally select apache as server.

Greets, :)
Jonas

**Comment by damencho** [comment]
Well if both are installed we prefer nginx. I see what you mean now ... Sorry. We don't have plans on changing this so any PRs are welcome.

**Comment by jotoeri** [comment]
Yeah, i understand that, it's just that i have an already running system on apache, which occupies ports 80/443 already...

See #8476 :)

**Comment by damencho** [comment]
Implemented in https://github.com/jitsi/jitsi-meet/pull/8476

**Comment by OdairTrujillo** [comment]
Ok, if I want to use that debconf varible how can I use it?
echo jitsi-meet-web-config jitsi-meet/enforce_apache string true | sudo debconf-set-selections ?
echo jitsi-meet-web-config jitsi-meet/enforce_apache select true | sudo debconf-set-selections ?

Thanks for your help.

**Comment by jotoeri** [comment]
Ahm it's a while ago now that i did this, but should be yours just with a boolean:
```
echo jitsi-meet-web-config jitsi-meet/enforce_apache boolean true | sudo debconf-set-selections
```

**Comment by OdairTrujillo** [comment]
Ok thanks @jotoeri. I used bool, my mistake. 

Is it possible that the jitsi team update the documentation with the option described as you did above?
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#debugging-problems

It is just a little bit of additional help.

And yes, I'm using the stable release, and I checked the .postinst file and yes, It has the code to make this work. Saddly I am not able to test it now. I had to remove all nginx related packages in order to force the jitsi installer to select apache as web server and I do not have the intention to uninstallit again, maybe in another chance. 

Thanks.

**Comment by jotoeri** [comment]
Are you sure, you found the code to make this work on your installation? I just installed on a wsl-debian test-system using just the repository as given on the documenation. The necessary code is not included there.
However if i install from the unstable repo, then it works and uses apache.

Concerning your documentation question: The text was intentionally kept without detailed information as nginx is preferred here. I'd suggest to open a separate issue in the repo and discuss your question there. 😉  https://github.com/jitsi/handbook

from current repo, without the necessary code-block:
![grafik](https://user-images.githubusercontent.com/47433654/109547993-5f8e2400-7acc-11eb-97f1-ae01133569d7.png)

from the PR, that implemented this:
![grafik](https://user-images.githubusercontent.com/47433654/109548023-6b79e600-7acc-11eb-9494-4023d9cfcf79.png)

**Comment by OdairTrujillo** [comment]
You're right.
