### ISSUE TITLE
Hide self-view in tile view

### ISSUE THREAD

**Issue by murchu27** [jitsi/jitsi-meet#8477]
**Describe the solution you'd like**
Would like to have the option to hide, or at the very least minimise my own camera/video input in the tile view. 

Seeing my own video can be very distracting, as I find my eyes are drawn to what I'm doing rather than the person I'm speaking to. Also, depending on the number of people, removing your own video can be more space efficient - e.g., at certain resolutions, 4 videos fill up the screen nicely, but a 5th video forces every video to be much smaller.

The focus/spotlight view (showing one person at a time) already does this by putting my video up in the top right corner - this is exactly the kind of thing I'm looking for, except in the tile view instead.

Google Meet's "grid" view also does this, for reference.

**Describe alternatives you've considered**
The spotlight view is an okay alternative when I really don't want to see myself, but there are certain meetings where being able to see everyone at once is much better - e.g. playing role-playing games where you want to be able to see everyone's reactions.

**Comment by saghul** [comment]
We are currently not considering adding this capability. That might change in the future.

**Comment by jucor** [comment]
Flagging that hiding self-view is one of the most recommended "self-care" points to avoid "Zoom fatigue".  See press coverage in:

- [The New York Times](https://www.nytimes.com/2021/04/13/us/zoom-fatigue-burn-out-gender.html)
- [The Times](https://www.thetimes.co.uk/article/the-cure-for-zoom-fatigue-first-turn-off-your-camera-883zlsd3d)
- [Forbes](https://www.forbes.com/sites/kimelsesser/2021/04/19/zoom-fatigue-is-worse-for-women---heres-why/?sh=ff8e20c52259)
- [The Conversation](https://theconversation.com/hide-self-one-tip-on-video-conferencing-good-enough-for-matthew-mcconaughey-136609)

May I suggest reconsidering adding this feature?

**Comment by saghul** [comment]
Thanks for putting together these resources, it certainly helps make your case. We'll take a look.

**Comment by jucor** [comment]
Thanks @saghul , appreciate it :) And thanks for the great work on Jitsi!

**Comment by psychoslave** [comment]
Hello dear Jitsi team,

Here is the scenario that led me here: a videoconference with two friends.

Expected default display: each of my friend taking mostly half of the window split vertically, my own face in a disableable thumbnail in some corner to enable a control that the webcam is well positioned.

Actual result: my own face taking up half the height of the window, and my friends’ video being tiled down to meet the remaining half top of the window space.

This is all the more critical on a smaller screens. The previously referenced session was used on a laptop (14”) plugged to a larger screen. The session was started on the larger screen, and this was less annoying though not really the best experience. But at some point we talked about some organizational point that led me to open some project management window, so the Jitsi window was thrown on the smaller screen (an alternative possibility would have been to use half the screen for each application window, the point on smallest window space staying the same). Once scaled down to such a small size, all display videos were looking more like incidental thumbnails than the main focus points.

This scenario is surely rather common. And even more common might be the scenario of people who actually only have a single small screen available.

And by the way, thank you for delivering such a great FLOSS tool to the world.

**Comment by saghul** [comment]
We are going to be looking into new layouts, but can't provide an ETA yet.

**Comment by jjtiziou** [comment]
+1 for this feature –

Being able to toggle self-view on and off feels pretty key for reasons well enumerated above (layout efficiency, alleviating self-consciousness & zoom fatigue, removing distraction & improving focus) 

I'd love to see this feature prioritized. 

Thanks to all for your work on this great offering!
-jj

**Comment by tg295** [comment]
Have there been any developments on this? thanks!

**Comment by saghul** [comment]
Nothing to report, sorry.

**Comment by tstrijdhorst** [comment]
+100

**Comment by chrisfromredfin** [comment]
I wonder if for at least those using a browser (not Electron app), this could be accomplished with a browser extension or Greasemonkey type script?

**Comment by andreasmjg** [comment]
+1 on this, would be really useful

**Comment by tbutter** [comment]
@WillowP That workaround now leaves an empty spot in the UI were the video was.

**Comment by murchu27** [comment]
> @WillowP That workaround now leaves an empty spot in the UI were the video was.

They already mentioned that in their comment:

> FWIW, a very simple workaround. In tile view, Jitsi has the "self view" in a span with `id="localVideoContainer`. I made a style for `Stylish` that hides it. ***Does not fix the screen space problem***, but at least lets you breathe a sigh of relief at not looking in the mirror while on calls.

**Comment by jbg** [comment]
Nasty nasty hack, but joining with `#config.iAmRecorder=true` removes yourself from the tile view ([ref](https://github.com/jitsi/jitsi-meet/blob/master/react/features/filmstrip/components/web/ThumbnailWrapper.js#L117)). It will almost certainly have other undesirable side-effects though.

Since removing the local participant for Jibri is already implemented, it seems like the patch to add a config option for this should be relatively simple, something like:

```patch
diff --git a/config.js b/config.js
index 1c1dfe71d..f2bfc89c6 100644
--- a/config.js
+++ b/config.js
@@ -995,6 +995,9 @@ var config = {
     // If true, tile view will not be enabled automatically when the participants count threshold is reached.
     // disableTileView: true,
 
+    // If true, the local participant will be hidden in tile view.
+    // hideSelfInTileView: false,
+
     // Controls the visibility and behavior of the top header conference info labels.
     // If a label's id is not in any of the 2 arrays, it will not be visible at all on the header.
     // conferenceInfo: {
diff --git a/react/features/base/config/configWhitelist.js b/react/features/base/config/configWhitelist.js
index 0992fd70b..bf7381192 100644
--- a/react/features/base/config/configWhitelist.js
+++ b/react/features/base/config/configWhitelist.js
@@ -122,6 +122,7 @@ export default [
     'disableSimulcast',
     'disableThirdPartyRequests',
     'disableTileView',
+    'hideSelfInTileView',
     'displayJids',
     'doNotStoreRoom',
     'doNotFlipLocalVideo',
diff --git a/react/features/filmstrip/components/web/ThumbnailWrapper.js b/react/features/filmstrip/components/web/ThumbnailWrapper.js
index 1e4d2a7f2..0405bd1b4 100644
--- a/react/features/filmstrip/components/web/ThumbnailWrapper.js
+++ b/react/features/filmstrip/components/web/ThumbnailWrapper.js
@@ -113,27 +113,27 @@ function _mapStateToProps(state, ownProps) {
         const { columns, rows } = gridDimensions;
         const index = (rowIndex * columns) + columnIndex;
         let horizontalOffset;
-        const { iAmRecorder } = state['features/base/config'];
-        const participantsLenght = remoteParticipantsLength + (iAmRecorder ? 0 : 1);
+        const { iAmRecorder, hideSelfInTileView } = state['features/base/config'];
+        const participantsLength = remoteParticipantsLength + ((iAmRecorder || hideSelfInTileView) ? 0 : 1);
 
         if (rowIndex === rows - 1) { // center the last row
             const { width: thumbnailWidth } = thumbnailSize;
-            const partialLastRowParticipantsNumber = participantsLenght % columns;
+            const partialLastRowParticipantsNumber = participantsLength % columns;
 
             if (partialLastRowParticipantsNumber > 0) {
                 horizontalOffset = Math.floor((columns - partialLastRowParticipantsNumber) * (thumbnailWidth + 4) / 2);
             }
         }
 
-        if (index > participantsLenght - 1) {
+        if (index > participantsLength - 1) {
             return {};
         }
 
         // When the thumbnails are reordered, local participant is inserted at index 0.
         const localIndex = enableThumbnailReordering ? 0 : remoteParticipantsLength;
-        const remoteIndex = enableThumbnailReordering && !iAmRecorder ? index - 1 : index;
+        const remoteIndex = enableThumbnailReordering && !(iAmRecorder || hideSelfInTileView) ? index - 1 : index;
 
-        if (!iAmRecorder && index === localIndex) {
+        if (!(iAmRecorder || hideSelfInTileView) && index === localIndex) {
             return {
                 _participantID: 'local',
                 _horizontalOffset: horizontalOffset
```

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/10531

**Comment by murchu27** [comment]
Awesome, looking forward to trying it out, thanks!

**Comment by murchu27** [comment]
Just had a call on the public jitsi instance, and the feature works beautifully! Thanks to all who worked on this 🤎

**Comment by demitrav** [comment]
There is an unintended bug introduced in this functionality.  If you have the "Settings" button hidden from the toolbar, once you "Hide Self View", you can never "un-hide" yourself.  

Any suggestions other than having to show the settings menu?

**Comment by damencho** [comment]
Yep, or disable hide self-view option, as it doesn't make sense when you cannot revert back.

**Comment by demitrav** [comment]
When I add `disableSelfViewSettings: true` in the config overwrite, it still shows the option in the kabob menu.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/7bcf7bb6864dbe88446b21b9333891485d33f54e/config.js#L97

**Comment by damencho** [comment]
O no this is like selecting it ... hum I just tested disableSelfViewSettings and it works for me.

**Comment by damencho** [comment]
If you want to workaround it you can open the welcomepage and edit the localstorage. 
But if you have disabled settings on the deployment, you better disable and hide self-view to avoid this situation.

**Comment by AndreiCercel** [comment]
yes, but how I can turn my thumbnail back? It's kind of complicated because I have to talk to the devs who are in charge with Jitsi for our company

**Comment by damencho** [comment]
Edit here and set disableSelfView to false and close the tab, better do it on the welcompage ... and hope it works, as the app can override it during unload ... 

![image](https://user-images.githubusercontent.com/3263098/167677734-5855b8a6-a92b-43db-af28-b8f2790803a9.png)

**Comment by AndreiCercel** [comment]
Hello and thank you for your suggestion, but it doesn't work. The parameter remains false indeed in that session but nothing changed. Also when I closed the meeting and started again, the parameter turn back to "true".

**Comment by AndreiCercel** [comment]
A noice friend and dev from our company easily found the solution and works.
On Chrome (because I'm using chrome), go to Privacy and security, than click on "See cookies and site data", and on my side (because we use Jitsi in our app) I deleted the "conference.(ourapp).com". And works, the settings are back :
<img width="282" alt="Screenshot 2022-05-11 at 08 52 26" src="https://user-images.githubusercontent.com/45652982/167778110-90da5717-032f-41ce-baf0-3353a40a4795.png">
D

**Comment by sergiomb2** [comment]
Hi, after click on hide self view , we can not enable (easily) self view again because option disappears , and it is very annoying , and not user friendly

**Comment by saghul** [comment]
So you have any suggestions on how to improve it? The tile is gone so we had to put the control elsewhere.

**Comment by sergiomb2** [comment]
yes , title instead gone should change to "show self view" .
The control is always available on settings -> more -> last item , but is hard to find , TBH I just found it after lose my patience and google on internet

**Comment by saghul** [comment]
That would be too large of a control, specially in tile view.

One of the main points behind the feature was to have more space for other tiles.

**Comment by sergiomb2** [comment]
I don't think change "hide self view" to  "show self view" will occupy more space

**Comment by saghul** [comment]
You miss the point. Where would that menu go? There is no tile for the loca participant, which is where the menu was.

**Comment by b90g** [comment]
> So you have any suggestions on how to improve it? The tile is gone so we had to put the control elsewhere.

Yes, anywhere Startup-Screen, Settings, deactivate after hangup, choose your fighter - , but an option to revert that choice would be preferable.

Thank you for your patience. :)

**Comment by saghul** [comment]
It's already in the settings.

**Comment by b90g** [comment]
Sorry, the server i'm using doesnt seem to use the current version, will check against meet.jit.si in the future before i start typing (:

**Comment by w-sky** [comment]
I'm at a loss, my own video has disappeared from all views somehow and I can't activate it again. All the suggestions above don't work, there is no option under "more" in the settings and I can't find any site setting to change this.
The only way I can actually see that my own video is working is when I click the camera button.

**Comment by sergiomb2** [comment]
![image](https://user-images.githubusercontent.com/1143630/218838558-e18459c5-c606-4743-bc74-ff7983ee96d2.png)

**Comment by sergiomb2** [comment]
IMHO, at least self view option , should be under devices tab

**Comment by w-sky** [comment]
Sorry I have expressed myself wrong: I do not have a "More" tab at settings.
I only have the Devices, Profile and Moderator tabs. Maybe it's an older version on our server?!

**Comment by CristAdela** [comment]
> So you have any suggestions on how to improve it? The tile is gone so we had to put the control elsewhere.

Hello, unfortunatly I used the button "Hide self view" and I can't find any setting to "Unhide self view". How can I see self :) back? PS. I do note have technical, coding background. 

Many thanks for your solution.

**Comment by saghul** [comment]
Open the Settings dialog and there is a way to unhide it in the General section.

**Comment by CristAdela** [comment]
> Open the Settings dialog and there is a way to unhide it in the General section.

manyyyy thants. I find it. I was searching in the video call , never thought to check settings before attenting video call. Higly appreciated your fast reply !!!!

**Comment by saghul** [comment]
Glad I could help!

**Comment by bgstack15** [comment]
My jitsi instance is running docker image jitsi/web:stable-9258 and I was unable to find the checkbox to re-enable self view anywhere in the web app. I checked before joining a call, and during a call. I was able to modify my localstorage key-value pair in developer tools and reload the page to get it to work, though.

**Comment by damencho** [comment]
It is in Settings -> General

**Comment by sergiomb2** [comment]
Hi, 
Just for the record, I haven't had time to look into this and propose some code modification, the original PR 
https://github.com/jitsi/jitsi-meet/pull/10531 , HTH
