### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by trymeouteh** [jitsi/jitsi-meet#8478]
Please add a setting in the mobile apps and the browser to add an avatar that can be displayed in the chat when your camera is off. This avatar will replace your circle with your first initial letter.

**Comment by damencho** [comment]
This is not on the roadmap and implementing temporary storage system for distributed stateless environment is not an easy task.

An easier will be to be able to set image url and store it in local storage for feature conferences ... And then you can use any file upload service for that ...

**Comment by tgeimer** [comment]
When you have LDAP authentication with your MS Active Directory one could use the image saved in the AD account.

**Comment by saghul** [comment]
The application has no knowledge of the authentication system being used.

**Comment by keunes** [comment]
> be able to set image url and store it in local storage for feature conferences ... And then you can use any file upload service for that ...

That'd be great. I'd like to set my avatar for meetings, but I don't want to create an account on a commercial website (Automattic's Gravatar)

**Comment by keunes** [comment]
Shush bot. Volunteers might still be interested in contributing here.

**Comment by saghul** [comment]
Closing. PRs are welcome, but note we currently have no plans to work on this.

**Comment by rasos** [comment]
Draft PR to generate an Avatar https://github.com/jitsi/jitsi-meet/pull/10067/
