### ISSUE TITLE
Meetings list: Sort for last used

### ISSUE THREAD

**Issue by thet** [jitsi/jitsi-meet#8481]
**Is your feature request related to a problem you are facing?**
I do use one meeting room daily and still have multiple others in use. 
The ``.meetings-list`` box in the HTML client's start site seems to be sorted exactly like the entries in the local storage ``features/recent-list``. Until now when I found out the sorting logic behind it (date of using the room for the first time) I did expect to have the last used room on first place.

**Describe the solution you'd like**
I'd like the ``.meetings-list`` / ``features/recent-list`` being updated for the last used date and sorted for last used date in reverse order, so that I have the last used meeting rooms on top.

**Describe alternatives you've considered**
For a quick fix I'll sort the recent-list myself. Also, I added a bookmark for the most important rooms.

**Comment by saghul** [comment]
Sounds reasonable. @vp8x8 can you PTAL when you have some cycles?

**Comment by vp8x8** [comment]
Sure, added to my todo list.

**Comment by thet** [comment]
Thanks a lot, it's working now as expected!
