### ISSUE TITLE
Remote video track does not removes for participants with FireFox 

### ISSUE THREAD

**Issue by bukharin** [jitsi/jitsi-meet#8482]
## Current behavior

When client in FireFox removes video track - this track does not removes from the conference and `TRACK_REVOVED` event does not fires for remote participants. 

You can reproduce this situation on `meet.jit.si`

## Expected Behavior

Video track should be removed and `TRACK_REMOVED` event should be fired for remote participant

## Steps to reproduce

1. Open Jitsi conference in FireFox. 
2. Turn off your camera. 
3. Share desktop
4. Stop desktop sharing

For remote participant (other browser or tab) - the desktop stream will be freezed. Also if remote participants re-join to the conference they will see freezed last frame of desktop stream.

This behavior also applicable to camera tracks.

# Environment details

FireFox version: 84.0.2

**Comment by izakgl** [comment]
This has been a known issue for a while (#7369) but I guess it's just not a priority.
