### ISSUE TITLE
Does not handle HTTPS meeting URLs

### ISSUE THREAD

**Issue by aniqueta** [jitsi/jitsi-meet#8489]
### Description:

If Jitsi-Meet is sent an https:// link it does not handle it appropriately. 

Since the use of jitsi-meet:// protocol links is rare, I was trying to use [another utility](https://www.choosyosx.com) to detect and pass https://meet.jit.si/* links from any app to the Jitsi.meet app. This works to open the Jitsi Meet Electron app, but the app does nothing and does not open the meeting link, as it would if the protocol was jitsi-meet://. 

Unfortunately, I'm not aware of a utility that can rewrite the link to use the protocol handler instead. 

I do not believe this is an issue with the utility that detects and passes these links, since this approach works with other Electron apps.

Thanks for considering.

### Steps to reproduce:

1. On macOS, setup [Choosy](https://www.choosyosx.com) to detect https://meet.jit.si/* URLs and set Jitsi Meet Electron app as the target to send these URLs
2. Click on a https://meet.jit.si/meetingname link 

### Expected behavior:

Jitsi Meet Electron app opens and navigates to the meeting named in the link.

### Actual behavior:

Jitsi Meet Electron app opens but does nothing and **does not navigate** to the meeting named in the link.

### Server information:

- Jitsi Meet version: N/A
- Operating System: N/A

### Client information:

- Browser / app version: Jitsi Meet v2.4.2
- Operating System: macOS 10.15

**Comment by saghul** [comment]
Please open the issue in the electron app repo.

**Comment by aniqueta** [comment]
@saghul So sorry. Thought I was in that repo...
