### ISSUE TITLE
iOS SDK compile error - MacOS 10.15.7, XCode 12.4, HEAD 63f0166f7

### ISSUE THREAD

**Issue by pandel** [jitsi/jitsi-meet#8491]
### Description:

Command line build of Jitsi Meet SDK as described under "Building it yourself", see https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk

### Steps to reproduce:

1. clone repo
2. cd jitsi-meet, npm install
3. (cd ios, pod install)
4. xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

### Expected behavior:

Build SDKs

### Actual behavior:

I get the following error messages and am unable to resolve them. As I did compile the SDK several times over the last half year, I know that it works in general.

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination=generic/platform=iOS -configuration Release archive

User defaults from command line:
    destination = generic/platform=iOS

note: Using new build system
note: Planning build
note: Constructing build description
error: No profiles for 'org.jitsi.meet' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'org.jitsi.meet'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'JitsiMeet' from project 'app')
error: No profiles for 'org.jitsi.meet.watchkit.extension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'org.jitsi.meet.watchkit.extension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'JitsiMeetCompanion Extension' from project 'app')
error: No profiles for 'org.jitsi.meet.watchkit' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'org.jitsi.meet.watchkit'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'JitsiMeetCompanion' from project 'app')

** ARCHIVE FAILED **
```

### Question:

Instead of building the app target, wouldn't it be possible to only build the SDK targets per se? I tried to build the targets `react-native-webrtc` and `JitsiMeetSDK`directly, but that doesn't work:

### Things I tried additionally:

1. xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme react-native-webrtc -destination='generic/platform=iOS' -configuration Release archive
2. xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeetSDK -destination='generic/platform=iOS' -configuration Release archive

The first one builds correctly, but the second leads to the following error:

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/holgerpandel/Library/Developer/Xcode/DerivedData/jitsi-meet-dvobgabsnnvazxbtdjefsbflrvdk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeetSDK.build/Script-26796D8589142D80C8AFDA51.sh (in target 'JitsiMeetSDK' from project 'sdk')
    cd /Users/holgerpandel/Source/jitsi-meet/ios/sdk
    /bin/sh -c /Users/holgerpandel/Library/Developer/Xcode/DerivedData/jitsi-meet-dvobgabsnnvazxbtdjefsbflrvdk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeetSDK.build/Script-26796D8589142D80C8AFDA51.sh
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** ARCHIVE FAILED **
```

I tried to clean up all project data and the DerivedData folder, running only the second command but that leads to another error - clearly because WebRTC framework is missing now:

```
ld: '/Users/holgerpandel/Library/Developer/Xcode/DerivedData/jitsi-meet-dvobgabsnnvazxbtdjefsbflrvdk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/holgerpandel/Library/Developer/Xcode/DerivedData/jitsi-meet-dvobgabsnnvazxbtdjefsbflrvdk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC/WebRTC.framework/WebRTC' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
        Ld /Users/holgerpandel/Library/Developer/Xcode/DerivedData/jitsi-meet-dvobgabsnnvazxbtdjefsbflrvdk/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeetSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/JitsiMeetSDK.framework/JitsiMeetSDK normal
```

My Cocoapods installation (1.10.1) is current and I did a fresh `pod install`.

### So?

What can I do now?

**Comment by pandel** [comment]
Followup:

If I start the compilation with

`xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive ENABLE_BITCODE=NO CODE_SIGNING_ALLOWED=NO`

it does compile, but both frameworks are not being build in a way that I could simply copy them over to my own project.

**Comment by AliKarpuzoglu** [comment]
maybe someone else knows better what's wrong, but I remember I had the same issue and could solve it by using pods version 1.9.3

**Comment by saghul** [comment]
We have just released SDK 3.0 which changes the name of the scheme, but I haven't updated the handbook yet.

The easiest way for you to create a custom build is to use this script: https://github.com/jitsi/jitsi-meet/blob/master/ios/scripts/release-sdk.sh#L31-L56

The process is now longer (3 commands) because it builds an XCFramework now, but that's a more future-proof options for "fat" frameworks such as this one.

**Comment by saghul** [comment]
I updated the docs now.

**Comment by pandel** [comment]
@saghul 
Many thanks! That makes it really clear. I was able to remove old JitsiMeet from my Podfile and integrate both self-compiled XCFrameworks (JitsiMeetSDK+WebRTC) into my project successfully.

Very nice! Keep up your great work :-)
