### ISSUE TITLE
Cached displayName disappears on prejoin-page

### ISSUE THREAD

**Issue by scheibling** [jitsi/jitsi-meet#8493]
### Description:

When I open a meeting either via the iFrame API or directly the cached or provided via JWT displayname shows up in the box at the bottom, only to disappear moments later.

### Steps to reproduce:

Edit: Apparently vanilla Jitsi Meet doesn't throw this error on its own, but after the token authentication plugin is installed. 

1. Open meeting via link
2. Get to pre-join page, cached display name appears for a split second
3. Cached display name disappears

### Expected behavior:

Cached display name or JWT provided displayname should stay in the box and be used as default

### Actual behavior:

Displayname disappears from box

### Server information:

- Jitsi Meet version: 2.1.416-g2f43d1b4
- Operating System: Debian 10.7

### Client information:

- Browser / app version: Tested in Firefox, Chrome, Edge
- Operating System: Windows

### Additional information:

Bug appeared after version update yesterday:

Upgrade: jitsi-meet-turnserver:amd64 (1.0.4466-1, 1.0.4628-1), jitsi-videobridge2:amd64 (2.1-376-g9f12bfe2-1, 2.1-416-g2f43d1b4-1), jicofo:amd64 (1.0-644-1, 1.0-692-hf-1), jitsi-meet-web:amd64 (1.0.4466-1, 1.0.4628-1), jitsi-meet:amd64 (2.0.5142-1, 2.0.5390-3), jitsi-meet-web-config:amd64 (1.0.4466-1, 1.0.4628-1), jitsi-meet-tokens:amd64 (1.0.4466-1, 1.0.4628-1), jitsi-meet-prosody:amd64 (1.0.4466-1, 1.0.4628-1)

**Comment by damencho** [comment]
Do you reproduce this with the latest version?

**Comment by scheibling** [comment]
@damencho Those were the latest compiled packages available for Debian in the repository, I'll setup a test instance with the latest version later today

**Comment by scheibling** [comment]
I've installed Jitsi Meet on a new server, the caching works fine when freshly installed.  
What seems to break it is when I install the token moderation plugin and use a JWT to connect to the meeting

I haven't set any user details in my current setup with JWT, I'm gonna run a few tests and see if that makes any difference.

**Comment by scheibling** [comment]
Right, so it seems that when I set the context:user:name option in the JWT with a name, this is what appears in the box. 

If I leave the option unset, it'll clear the cached name as well. 

I'm not sure if this is intended behaviour, if it is I can close this. I can work around the issue on my end where I generate my JWTs.

**Comment by saghul** [comment]
In general the JWT will override all other sources for the display name.

**Comment by scheibling** [comment]
> 
> 
> In general the JWT will override all other sources for the display name.

Should this be the case even when there is no display name set in JWT? I'm guessing that's where the, in my case, unintended behaviour comes from
