### ISSUE TITLE
Native Tablet Apps not showing Lobby Support on self hosted Jitsi Instance

### ISSUE THREAD

**Issue by bjoerrrrn** [jitsi/jitsi-meet#8494]
The iOS-App is supporting the Lobby at the moment on my iPad 6. Gen - iOS 14.3 - Jitsi Meet App 20.6.2 build 103

I see the option in the app to activate the lobby in a conference, when I join a new session on meet.jit.si.

When I do the same on my own Jitsi Meet Instance I do not see the Start Lobby Mode Option in the App.

My Jitsi is based on the official Docker Images, freshly pulled today.

In the normal Web App in any Browser the Lobby Feature works just fine and without a problem. Only the native Apps for iOS and Android do not offer me the option to toggle the Lobby Feature on.

Am I just blind or is there any switch that I have missed?

**Comment by AliKarpuzoglu** [comment]
The configuration for the self hosted instances has changed. Here's more info

https://community.jitsi.org/t/how-to-how-do-i-use-the-new-lobby-feature/73100/56
