### ISSUE TITLE
JitsiMeet WebRTC.framework Image Not Found exception

### ISSUE THREAD

**Issue by MelihTOKSARI** [jitsi/jitsi-meet#8496]
### Description:
Sample Xcode app inside jitsi-meet-master project throws "image not found" after successfully build and run on device.
I get below error after app installed on device.

dyld: Library not loaded: @rpath/WebRTC.framework/WebRTC
  Referenced from: /private/var/containers/Bundle/Application/8FB8980B-4943-4919-8A94-8D2A7CE21B05/jitsi-meet.app/jitsi-meet
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

<img width="403" alt="Screen Shot 2021-01-28 at 09 53 36" src="https://user-images.githubusercontent.com/21153173/106121600-c97f7a80-6168-11eb-808e-1d0c405e779f.png">

### Steps to I made after download:

1. Download jitsi-meet-master project from GitHub
2. Run npm install inside jitsi-meet-master path
3. Run pod install inside jitsi-meet-master/iOS path
4. Change bundle identifiers
5. Set "Enable Bitcode" to "No" for app and all targets
6. Set "Always Embed Swift Standart Libraries" to "Yes" for app and all targets
7. In Build Phase tab, Embed Frameworks have both "JitsiMeetSDK.framework" and "WebRTC.xcframework"

### Server information:

- Jitsi Meet version: 2.0.5390
- Operating System: macOS Big Sur version 11.1
- Xcode version: 12.4
- Pod version: 1.10.1

### Client information:

- Device: iPhone 7 version 14.4

### Additional screenshots:

<img width="253" alt="Screen Shot 2021-01-28 at 09 53 06" src="https://user-images.githubusercontent.com/21153173/106122574-ecf6f500-6169-11eb-96ea-9ae77dbebf75.png">

<img width="720" alt="Screen Shot 2021-01-28 at 13 07 17" src="https://user-images.githubusercontent.com/21153173/106122711-0f890e00-616a-11eb-96c4-439f0abec033.png">

**Comment by hanifmhd** [comment]
i also get this error.
in the newest xcode (12.4), `WebRTC.framework` is auto deleted by xcode, i dont know why

**Comment by mfts** [comment]
I get a similar issue around the `WebRTC.framework`: 

But nothing has been changed to the source code pulled from [mobile-20.6 branch](https://github.com/jitsi/jitsi-meet/tree/mobile-20.6). 

```
cd /jitsi-meet
npm install
cd /ios
pod install

# change bundle identifier
# Product > Archive
```

Results in the following error:

```
'/Users/[OMITTED]/Library/Developer/Xcode/DerivedData/jitsi-meet-gfptbpdsvxoqbzclsexjlpniequa/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC/WebRTC.framework/WebRTC' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. 
file '/Users/[OMITTED]/Library/Developer/Xcode/DerivedData/jitsi-meet-gfptbpdsvxoqbzclsexjlpniequa/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC/WebRTC.framework/WebRTC' for architecture arm64
```

**Comment by saghul** [comment]
In master we have switched to using XCFrameworks. Are you folks using CocoaPods 1.10 ?

**Comment by mfts** [comment]
Hi @saghul, I just pulled the `master` branch, and `npm install` and then `pod install` in the /ios directory. 

I have the latest podversion
```
$ pod --version
1.10.0
```

However, I get the exact same error message as written above (https://github.com/jitsi/jitsi-meet/issues/8496#issuecomment-773189281)

**Comment by saghul** [comment]
Hum, I'm not using Product -> Archive, so not sure why that fail. We use this script for building XCFrameworks: https://github.com/jitsi/jitsi-meet/blob/master/ios/scripts/release-sdk.sh

**Comment by MelihTOKSARI** [comment]
Hello everyone, I figured out this problem previous week, but I really forget to post solution here (sorry about that). I don't know exact problem or solution but I try to explain what I did step by step. 

Important Note: Before build successfully, there was new  macOS update which was related with "Xcode Command Line Tools"

1- Pulled master branch
2- run npm install and run pod install without deleting Podfile.lock file. Also, version of CocoaPods must be at least 1.10 as @saghul already said.
3- You can check with "open Podfile.lock -a TextEdit" command in Mac
4- In Xcode, change bundle identifier and close and reopen auto sign feature for all targets. (why I did is probably Xcode cannot set Build Settings Signing properly)
5- Set "Enable Bitcode" to No for all targets and project (same for sdk project)

After above steps, I can build jitsi-meet workspace successfully. On the other hand, I get an error after using below command to archive. Unfortunately, I forgot error but it can be one of the "normal" errors.

(saghul share when I write this comment :))
"xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive"
(Note: I remove "VALID_ARCHS" for iphonesimulator but don't know this has some effect)

If you fail after using above command, try next step in Xcode.

6- Set "Always Embed Swift Standart Libraries" to Yes for all targets and project again (same for sdk project) via https://github.com/jitsi/jitsi-meet/issues/3299#issuecomment-408059675

After last step, I can archive successfully via terminal. I hope this will work for you. For now, I close this issue.

**Comment by hanifmhd** [comment]
> In master we have switched to using XCFrameworks. Are you folks using CocoaPods 1.10 ?

i'm using 1.10.1
