### ISSUE TITLE
PreMeetingScreen: Don't show URL Copy Feature if "disableInviteFunctions" is true

### ISSUE THREAD

**Issue by rponline** [jitsi/jitsi-meet#8498]
A friend of mine is teacher and uses jitsi inside an iframe for distance learning.
The CopyMeetingUrl-Component is enabling the kids bombing the meeting.
https://github.com/jitsi/jitsi-meet/blob/478f1a731ec9e37dfd504d1dbcc1728bbfb74efa/react/features/base/premeeting/components/web/PreMeetingScreen.js#L106
 
There is the "disableInviteFunctions" config option. but it doesn't have effect on this UI-Element.
https://github.com/jitsi/jitsi-meet/blob/63f0166f7526b71e3375a9bbf058fa8247480118/config.js#L587

**Comment by saghul** [comment]
Sounds reasonable! Are you up for writing a PR?

**Comment by rponline** [comment]
Sry, I'm not familiar with react ... more into programming vue 🙈
I guess other people could do this in much less time

**Comment by skolmer** [comment]
We will provide a PR. 
We have the requirement to only share the dial in number and hide link sharing and social sharing features. So we are planning to add a new config value to interface_config.js that allows you to disable each sharing feature individually. I thought about a similar configuration like the `TOOLBAR_BUTTONS`. An array that defaults to `SHARING_FEATURES: ["socoalSharing", "urlSharing", "dialInSharing"]`. Any other suggestions are welcome @saghul @rponline
