### ISSUE TITLE
No error message is shown to the user when no audio devices are available.

### ISSUE THREAD

**Issue by neusdan** [jitsi/jitsi-meet#85]
Even if chrome is used i get this error when chrome does not find my microphone (i had it disabled in windows).

 "Failed to get access to local media. Error  NavigatorUserMediaError {constraintName: "", message: "", name: "DevicesNotFoundError"} "

Therefore a meaningful error message would be nice.

Chrome 35
Windows 7

**Comment by bgrozev** [comment]
This is most likely been fixed in the recent work on this (see e.g. #251)
