### ISSUE TITLE
problems configuring a 2nd domain name.

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi-meet#8500]
I had to reinstall jitsi-meet because updating ubuntu packages did not fix this browser issue with chrome >88 (?). I have it now running, but I wanted to link a 2nd domain to jitsi meet 

so added a 2nd config in nginx 
copied the config.js and only changed the bosh host

But still not working. The first domain 

https://meet.good.com/http-bind?room=test shows the "It works" (with link to the bosh config)

however the https://meet.second.com/http-bind?room=test shows "404 Not Found" "Unknown host: meet.second.com"

What else do I need to configure? I already tried cross_domain_bosh = tue;

PS. I am not getting your community password reset email

**Comment by damencho** [comment]
In the second.com nginx config replace $http_host with the domain of meet.good.com here https://github.com/jitsi/jitsi-meet/blob/bf714c1c8b16c7f7ce50d0713e2ae2f185e5c7d0/doc/debian/jitsi-meet/jitsi-meet.example#L81

**Comment by f1-outsourcing** [comment]
Many, many thanks!!!!!
