### ISSUE TITLE
Option to set/override YouTube live stream key in config.js

### ISSUE THREAD

**Issue by byrnehollander** [jitsi/jitsi-meet#8501]
**Is your feature request related to a problem you are facing?**

Yes.

I'm working on [a trivia app](https://trivia.digital) that has both hosts and players. 

I'd like for the host(s) to use a stored YouTube live stream key (requested and saved in my own application), and have the host start streaming to all the players as soon as they join the Jitsi Meet. _Note_: I'm using the IFrame API in my application.

---

**Describe the solution you'd like**

Up to two new config options:
1. `youTubeLiveStreamKey` (string)
2. `startStreamingOnJoin` (boolean)

If `youTubeLiveStreamKey` is set, when a user clicks  `Start live stream`,  `Live Streaming` initiates without requiring the user to enter in their YouTube live stream key manually. 

_Possible addition_: If an error occurs (like `Live Streaming failed to start`), the next time they click `Start live stream`, a user will see the typical dialog box asking for a stream key.

If `youTubeLiveStreamKey` is set _and_ `startStreamingOnJoin` is `true`, then the broadcast will start streaming to YouTube as soon as the meeting has at least one participant.

---

**Describe alternatives you've considered**

There could just be a single config option: `youTubeLiveStreamKey` that would start the stream as soon as the first participant joins. However, users would lose some flexibility.

---

**Anything else?**

Just wanted to give a huge thank you ❤️ to the community and contributors – this is an _excellent_ piece of software and I really love using it.

Also, I'd be happy to try building this feature myself if anyone is interested in pairing with me / pointing me in the right direction.

**Comment by mojtabaghiasi** [comment]
Need this feature.

**Comment by saghul** [comment]
You can start live streaming using the external API and a command.

**Comment by mojtabaghiasi** [comment]
Thanks for the reply, could you explain more about this. and which API you mean?
@saghul

**Comment by saghul** [comment]
Check it out here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands/#startrecording
