### ISSUE TITLE
Jitsi-Meet Release 2.0.5390: Chat shows "Fellow Jitster" on messages for people who join after the chatmessage creator left

### ISSUE THREAD

**Issue by amsnek** [jitsi/jitsi-meet#8508]
### Description:

On the latest release, participants joining after someone left who wrote a message in chat -> will see "Fellow Jitster" instead the original Participants Name for the typed message. 

### Steps to reproduce:

1. Named Participant "Tester A" joins a Meeting.
2. Named Participant enters a Text in Chat. 
3. Named Participant leaves (somone else should remain so the meeting doesnt close)
4. Named Participant "Tester B" joins the Meeting -> will not see "Tester A" in chat, but "Fellow Jitster" (or whatever the default was renamed to) instead. 

### Expected behavior:

Tester B should see "Tester A" as Name in the Chat message instead of "Fellow Jitster"

### Actual behavior:

Tester B sees "Fellow Jitster" as Name in the Chat message for the person that left before he joined. 

### Server information:

- Jitsi Meet version: 2.0.5390
- Operating System: Linux

### Client information:

- Browser / app version: Chrome
- Operating System: any

**Comment by damencho** [comment]
This is expected. As there are some security issues around the name.

**Comment by damencho** [comment]
Please use the community forum for questions or problems before opening new issues.

**Comment by amsnek** [comment]
hmm ah, i assumed this was a bug since this did not occur in previous releases. thanks for the info!
