### ISSUE TITLE
Record in selected / predefined video layout

### ISSUE THREAD

**Issue by Novalis15** [jitsi/jitsi-meet#8509]
**Is your feature request related to a problem you are facing?**
If someone wants to record a session, Jitsi is always recording it in the speaker mode while the participants only see their selected video layout (e.g.: grid mode). However, this layout is not always the one people want to record in.

**Describe the solution you'd like**
 It would be beneficial if Jitsi is recording in the video layout the recording participant has selected or if there is an option to select the video layout for the recording.

**Comment by saghul** [comment]
You can enable "follow me" in the More tab of the settings panel. This way the recorder will follow your every move and if you select tile view for example, that will be recorded.
