### ISSUE TITLE
Avatar images blocked in the browser by CORS

### ISSUE THREAD

**Issue by marcoblancas** [jitsi/jitsi-meet#8510]
After upgrading our jitsi debian server from 1.0.4466-1 to 1.0.4628-1 the avatars we passed by URL are no longer displayed and we see this message in the browser console:

> Access to fetch at 'https://xxxxx.xxxx.es/moodleeval/user/pix.php/7/f1.jpg' from origin 'https://jitsi.xxxx.xx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

As a workaround in our avatar server we have added this in httpd.conf.

> Header set Access-Control-Allow-Origin '*'

but this is not a default configuration in web servers and we don't know what has changed to cause the avatar blocking now.

Related forums are:
https://community.jitsi.org/t/avatarurl-issues-custom-image-url-not-showing-avatar/82880/5
https://community.jitsi.org/t/jibri-problem-avatar-image/91155/2

I don't know how url avatar images are fetched now or how they were fetched before, but maybe something like this could help in order to avoid to set this header in the avatar image servers
https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

**Comment by saghul** [comment]
I wonder if this is because we used to preload then with an img tag but are now using fetch.

**Comment by demiangmz** [comment]
We're having the same issue and there's no way to disable CORS on our source image server due to security restrictions. Any way to resolve this?

**Comment by saghul** [comment]
@demiangmz Since you are in control of the server, how about allowing the meet.jit.si origin?

**Comment by marcoblancas** [comment]
The workaround is OK for people or institutions with full control in their servers.

In our university we are the [jitsi-moodle plugin](https://moodle.org/plugins/mod_jitsi) maintainers and this plugin is very popular in schools over all the word but most of schools outsource their Moodle hosting and they doesn't know or they can't apply the workaround.

In my opinion the way to fetch avatar images should be reviewed in order to avoid CORS block issues.

**Comment by saghul** [comment]
> In my opinion the way to fetch avatar images should be reviewed in order to avoid CORS block issues.

Sure. I just don't know why an `<img>` tag behaves differently than doing a `fetch()`. We can revert to the former for security reasons.

**Comment by demiangmz** [comment]
> @demiangmz Since you are in control of the server, how about allowing the meet.jit.si origin?

The server I use to pull images from does not allow the CORS settings modified, the Jitsi installation we have does have allow from all origins (*) setup but we can't pull images. The devs have changed to request the image with CORS headers but the response comes back empty. 

As a workaround we reverted back to showing initials on the iFrame calls.

**Comment by saghul** [comment]
> > In my opinion the way to fetch avatar images should be reviewed in order to avoid CORS block issues.
> 
> 
> 
> Sure. I just don't know why an `<img>` tag behaves differently than doing a `fetch()`. We can revert to the former for security reasons.

Sorry I meant to write CAN'T here.

**Comment by saghul** [comment]
I think I have found a way around it: https://github.com/jitsi/jitsi-meet/pull/8600

**Comment by modaan** [comment]
I would like to stay on the stable jitsi meet version. Is there a way too change the file preloadImage.web.js (https://github.com/jitsi/jitsi-meet/commit/a3fb996ff020a0984b0851981800a5e106e8a671) by hand?

Where is the preloadImage.web.js located?

**Comment by ludi81** [comment]
I would like to stay on the stable jitsi meet version. Is there a way too change the file preloadImage.web.js (a3fb996) by hand?

Where is the preloadImage.web.js located?

**Comment by saghul** [comment]
All JS files are bundled, you can't change that file.

**Comment by ludi81** [comment]
Thanks for the information. When will this problem be fixed in the stable version?

**Comment by saghul** [comment]
I don't know when we'll make a new stable release. Probably in a couple of weeks or so.

**Comment by dvydruk** [comment]
I've got the same problem loading avatars from Rocketchat and the workaround is to add this line to nginx location block:
        add_header 'Access-Control-Allow-Origin' '*' always;
