### ISSUE TITLE
The text "The meeting needs to use your microphone and camera" is not translated

### ISSUE THREAD

**Issue by marctemp1** [jitsi/jitsi-meet#8515]
### Description:

When visiting meet.jit.si/abcd1234, the text "_The meeting needs to use your microphone and camera_" is not translated. The second line is correctly translated (to Dutch).

### Steps to reproduce:

1. visit meet.jit.si/abcd1234
2. set language to dutch
3. don't allow access to camera and microphone
4. First line is not translated, second line is

### Expected behavior:

The first line should be translated to dutch, same as the second line

### Actual behavior:

First line is not translated to dutch

### Server information:

- Jitsi Meet version: latest stable 
- Operating System: Ubuntu?

### Client information:

- Browser / app version: Chrome 88 / Edge 88
- Operating System: Windows 10

**Comment by chipechop** [comment]
I think you can just open the dutch language file (https://github.com/jitsi/jitsi-meet/blob/master/lang/main-nl.json) and add the missing translations. Use the main.json (https://github.com/jitsi/jitsi-meet/blob/master/lang/main.json) file as reference. You'll see that the main file contains 936 lines, while the dutch, only 904. You can compare the two files side by side and add the missing 28 lines, in the dutch.

Do this:
- open the folder "Lang" into the <> code section
- right click on the dutch language file (main-nl.json) and open it, in a new TAB of your browser
- right click on the main language file (main.json) and open it, in a new TAB of your browser

Scroll them side by side and add any missing line in the dutch file. Place them in the same place where they are in the main file.

When you'll save your modifications, github will create a fork of the project, that will contain your modifications when your done, create a pull request with your modifications and your file will be visible the "pull request" section.

A moderator will then approve your translations, if nobody else adds, or corrects the translations you added.

**Comment by fritzgithub** [comment]
I noticed the same behavior and don't think that it is a matter of the translation.
This should be the section in `main.json`:
`
    "startupoverlay": {
        ...
        "title": "{{app}} needs to use your microphone and camera."
`
This also does exist in the german language file.

But even on https://meet.jit.si it says "_The meeting needs to use your microphone and camera_" whereas all other text is in german.
Since it says "**The meeting**" i assume, that `startupoverlay.title` is not used at all. And therefore cannot be translated

**Comment by chipechop** [comment]
@fritzgithub this is indeed a matter of translation: both in the Dutch main-nl.json and German main-de.json file, there is a missing line that you need to add manually.

Missing lines in a given language file, cause Jitsi to use the default english line.

You just have to add the missing line in your local language main-*.json file.

I did it many times for the Italian translation: I manually added hundreds on lines. You can fix it, in minutes: add it, save changes, that's it.

**Comment by fritzgithub** [comment]
@chipechop 
Thank you!  You are right.
I just have not seen `genericTitle` before. It is nowhere in my (probably outdated) local language files ...
Fix will come (in this case german translation): https://github.com/jitsi/jitsi-meet/pull/8404/files

**Comment by saghul** [comment]
Please feel free to make PRs with the missing translations, we do rely on the community for this ❤️
