### ISSUE TITLE
[iOS] latest version does not build Release: 'WebRTC/RTCMediaStream.h' file not found

### ISSUE THREAD

**Issue by dofl** [jitsi/jitsi-meet#8517]
### Description:

Cannot successfully build a RELEASE version of Jitsi Meet on iOS. Debug version builds without any issues.
xCode returns 'WebRTC/RTCMediaStream.h' file not found in 
/jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+Permissions.m

### Steps to reproduce:

I followed the manual: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile

1. Cloned the most recent version of Jitsi meet (git clone https://github.com/jitsi/jitsi-meet.git)
2. NPM install inside /jitsi-meet folder (successful)
3. POD install inside /jitsi-meet/ios folder (successful)
4. Started xCode and opened /jitsi-meet/ios/jitsi-meet.xcworkspace
5. Build with iPhone 11 as simulator, successful. App loads on the iPhone 11 with Metro terminal in the background.
5. xCode > Product > Scheme Edit Scheme > and set build to Release instead of Debug

<img width="711" alt="Screenshot 2021-01-31 at 13 51 18" src="https://user-images.githubusercontent.com/8161021/106384673-61c96980-63cc-11eb-9d76-a3b6ad2c16a4.png">

6. Pressed the Build button with iPhone 11 as simulator
7. xCode build fails with error  'WebRTC/RTCMediaStream.h' file not found

<img width="857" alt="Screenshot 2021-01-31 at 13 56 49" src="https://user-images.githubusercontent.com/8161021/106384666-58400180-63cc-11eb-92db-8c9ebc9d2fed.png">

### Expected behavior:

It should run the RELEASE version of Jitsi-Meet on the xCode iPhone 11 simulator 

### Version information:

- Jitsi Meet version: latest with git clone, jitsi-meet_5471
- Operating System: macOS Cataline version 10.15.7
- NPM version 7.4.3
- POD version 1.10.1

### NPM install log

```
> jitsi-meet@0.0.0 postinstall
> jetify

Jetifier found 1030 file(s) to forward-jetify. Using 8 workers...

added 2200 packages, and audited 2201 packages in 1m

21 low severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

### POD install log

```
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing AppAuth (1.2.0)
Installing BVLinearGradient (2.5.6)
Installing CocoaLumberjack (3.5.3)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.61.5-jitsi.2)
Installing FBReactNativeSpec (0.61.5-jitsi.2)
Installing Firebase (6.33.0)
Installing FirebaseAnalytics (6.8.3)
Installing FirebaseCore (6.10.3)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing FirebaseCrashlytics (4.6.1)
Installing FirebaseDynamicLinks (4.3.1)
Installing FirebaseInstallations (1.7.0)
Installing Folly (2018.10.22.00)
Installing GTMAppAuth (1.0.0)
Installing GTMSessionFetcher (1.2.2)
Installing GoogleAppMeasurement (6.8.3)
Installing GoogleDataTransport (7.4.0)
Installing GoogleSignIn (5.0.1)
Installing GoogleUtilities (6.7.2)
Installing ObjectiveDropboxOfficial (3.9.4)
Installing PromisesObjC (1.2.10)
Installing RCTRequired (0.61.5-jitsi.2)
Installing RCTTypeSafety (0.61.5-jitsi.2)
Installing RNCAsyncStorage (1.13.2)
Installing RNDefaultPreference (1.4.2)
Installing RNDeviceInfo (8.0.0)
Installing RNGoogleSignin (3.0.1)
Installing RNSVG (12.1.0)
Installing RNSound (0.11.0)
Installing RNWatch (0.4.3)
Installing React (0.61.5-jitsi.2)
Installing React-Core (0.61.5-jitsi.2)
Installing React-CoreModules (0.61.5-jitsi.2)
Installing React-RCTActionSheet (0.61.5-jitsi.2)
Installing React-RCTAnimation (0.61.5-jitsi.2)
Installing React-RCTBlob (0.61.5-jitsi.2)
Installing React-RCTImage (0.61.5-jitsi.2)
Installing React-RCTLinking (0.61.5-jitsi.2)
Installing React-RCTNetwork (0.61.5-jitsi.2)
Installing React-RCTSettings (0.61.5-jitsi.2)
Installing React-RCTText (0.61.5-jitsi.2)
Installing React-RCTVibration (0.61.5-jitsi.2)
Installing React-cxxreact (0.61.5-jitsi.2)
Installing React-jsi (0.61.5-jitsi.2)
Installing React-jsiexecutor (0.61.5-jitsi.2)
Installing React-jsinspector (0.61.5-jitsi.2)
Installing ReactCommon (0.61.5-jitsi.2)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing nanopb (1.30906.0)
Installing react-native-background-timer (2.4.0)
Installing react-native-calendar-events (2.0.0)
Installing react-native-keep-awake (4.0.0)
Installing react-native-netinfo (4.1.5)
Installing react-native-splash-screen (3.2.0)
Installing react-native-webrtc (1.87.3)
Installing react-native-webview (11.0.2)
Generating Pods project
Integrating client projects
Pod installation complete! There are 47 dependencies from the Podfile and 59 total pods installed.

[!] The Podfile contains framework or static library targets (JitsiMeetSDK), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).
```

**Comment by dofl** [comment]
Tried with the recommended versions of Node and NPM, but still fails to build. Anyone got any tips?

npm --version
6.14.10

node --version
v12.20.1

**Comment by dofl** [comment]
Just checked out the latest GIT and compiled it. Debug works fine but still having the issue with the Release build 'WebRTC/RTCCameraVideoCapturer.h' file not found and 'WebRTC/RTCMediaStreamTrack.h' file not found

I appriciate it if anyone could help me out.

**Comment by saghul** [comment]
You need Xcode 12 and CocoaPods 1.10, are you using those?

**Comment by dofl** [comment]
Yes. 

Xcode Version 12.4
CocoaPods 1.10.1

**Comment by estevg** [comment]
![image](https://user-images.githubusercontent.com/28814083/116602808-d17ac200-a8f1-11eb-958a-8c2cf657c792.png)
I have a similar problem 😓

**Comment by SteveSultan** [comment]
Same issue here.

Xcode Version 12.4
CocoaPods 1.10.1
