### ISSUE TITLE
Bad video quality in Firefox when screen sharing and camera are both turned on

### ISSUE THREAD

**Issue by claus-webtek** [jitsi/jitsi-meet#8519]
### Description:

When the presenter is using Firefox (tested with Firefox 85) and screen sharing + camera are turned on at the same time, the video quality gets pretty bad. However, if only screen sharing or only camera is turned on, the quality is fine. For comparison, when the same presenter machine uses Chrome or Edge, the quality is fine in all cases (so the issue is only reproducible in Firefox). This issue was tested with our own installation of the latest Jitsi Meet (i.e. 2.0.5390) and is also reproducible at https://meet.jit.si/

Additionally, I noticed 2 other issues (which might be related):

- If Jitsi is opened in one tab and the user opens a second tab, screen sharing gets interrupted (or stuttering) when the user is working in the second tab (like if Firefox partially suspends the first tab?)
- The desktopSharingFrameRate setting seems to be ignored for Firefox (I was only able to test this with my own Jitsi installation). I have configured a max frame rate of 5 FPS but when watching a video while screen sharing is turned on, it looks like the framerate is more than 20 FPS. For comparison, in Chrome this seems to work as expected (i.e. it limits to 5 FPS).

### Steps to reproduce:

1. Open Chrome, Edge (Chromium) and Firefox and join the same meeting
2. Start screen sharing in Firefox
3. Start sharing camera in Firefox

### Expected behavior:

It should be possible to read what is shown on the shared desktop and also the presenter video should not be blurry. The quality should not get worse if the presenter is already screen sharing and he turns on the camera.

### Actual behavior:

The quality is getting so bad, that you can't barely read anything on the screen.

### Server information:

- Jitsi Meet version: 2.0.5390
- Operating System: Ubuntu 20.04.2

### Client information:

- Browser / app version: Firefox 85, Chrome 88, Edge (Chromium) 88
- Operating System: Windows 10

**Comment by pierreozoux** [comment]
Given [this comment](https://github.com/jitsi/jitsi-meet/issues/7923#issuecomment-742741689) from @jallamsetty1 

There is a workaround which would be to set your screen resolution to 720p, and it should work.
(I know it is not a fix, but a workaround in the meantime :) )
