### ISSUE TITLE
Option to disable "Too Loud" alert

### ISSUE THREAD

**Issue by DmKaleid** [jitsi/jitsi-meet#8520]
that's it

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/blob/8582b25d288fbf25c05f6dee034b3145cd21c5b5/config.js#L103

**Comment by DmKaleid** [comment]
i can't fint it on the interface, where is it?

**Comment by damencho** [comment]
There is no such setting in the ui

**Comment by DmKaleid** [comment]
yeah i know, that's what i was asking
