### ISSUE TITLE
toolbox.alwaysVisible not working in iOS SDK 

### ISSUE THREAD

**Issue by sumit-chauhan** [jitsi/jitsi-meet#8525]
I am trying to hide toolbar but it is not working in ios.

[builder setFeatureFlag:@"toolbox.alwaysVisible" withBoolean:false];

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by saghul** [comment]
Also, false is the default, so there will be no effect.

**Comment by sumit-chauhan** [comment]
I am using jitsi-meet 20.6.1

I have also tried with 
jitsi-meet-sdk-samples/ios/objc/NoPodsSample/

I applied true and false both, but it is not hiding..

**Comment by sumit-chauhan** [comment]
@saghul 

Any luck with toolbox.alwaysVisible, i tried both true and false, nothing works.
[builder setFeatureFlag:@"toolbox.alwaysVisible" withBoolean:true];
[builder setFeatureFlag:@"toolbox.alwaysVisible" withBoolean:false];


For verification i tried raise-hand.enabled, this one works means i am using at right place.
 [builder setFeatureFlag:@"raise-hand.enabled" withBoolean:false];

**Comment by sumit-chauhan** [comment]
It is not working, Any update on this?

**Comment by saghul** [comment]
I think there might be a logic error here: https://github.com/jitsi/jitsi-meet/blob/6a6aeb1d9560f77eb64e54ba459d92922b616147/react/features/toolbox/functions.native.js#L15
