### ISSUE TITLE
IOS Chrome deeplinking issue

### ISSUE THREAD

**Issue by bferster** [jitsi/jitsi-meet#8527]
### Description:

When accessing Jitsi Meet via an iFrame from on IOS/Chrome, it restarts whenever a second person joins the meeting.
This occurs in the hoster version AND the self-hosted version.
Works fine on IOS Safari and Android/Chrome.

### Steps to reproduce:

1. Open a meeting on an iPad
2. Open a meeting on a PC

### Expected behavior:

Meeting as with 2 PCs

### Actual behavior:

PC works fine
iPad puts up screen saying "retrying" and never joins after multiple retries

### Server information:

- Jitsi Meet version: current version
- Operating System: Debian/Apache
- 
### Client information:

- Browser / app version: Chrome latest version
- Operating System: IOS 14.4

**Comment by saghul** [comment]
We have some known issues with Chrome on iOS, right @jallamsetty1 ?

**Comment by jallamsetty1** [comment]
> We have some known issues with Chrome on iOS, right @jallamsetty1 ?

Yes, chrome on iOS is not supported and it shouldn't taken you to the conference directly, instead it should open the conference in the App if it's available. This would happen only on iPadOS where the user agent string is similar to that of macOS and therefore we erroneously assume it as desktop browser. We will have a fix for this soon.

**Comment by dev-assassin** [comment]
Any chance that the fix will fix the error when using iPhone & Chrome to access Jitsi without iOS app through chrome browser, with disabled deep linking?

**Comment by saghul** [comment]
Yes, fixing Chrome on iOS is also on our roadmap.

**Comment by Juceztp** [comment]
Hello, I have doubts if this issue was solved.
I see that creating a meeting from the jitsi found at https://jitsi.org/jitsi-meet seems to work correctly but in our jitsi the error still occurs.

**Comment by jallamsetty1** [comment]
> Hello, I have doubts if this issue was solved.
> I see that creating a meeting from the jitsi found at https://jitsi.org/jitsi-meet seems to work correctly but in our jitsi the error still occurs.

This has been fixed in the master if you are on iOS 14.3 or newer versions.This has been released to stable as well so you might need to update your Jitsi deployment.

**Comment by jallamsetty1** [comment]
Closing this issue as it has been fixed already in the latest stable.
