### ISSUE TITLE
"View full screen" doesn't work in Safari, iOS

### ISSUE THREAD

**Issue by eilrix** [jitsi/jitsi-meet#8531]
### Description:

"View full screen" button doesn't work in Safari, iOS

### Steps to reproduce:

1. Open any meeting in iPhone, Safari browser, https://meet.jit.si/test-meet12345 for example,
2. Press more actions
3. Press "View full screen"

### Expected behavior:

Toggles full-screen mode

### Actual behavior:

Nothing happens

### Client information:

Tested on iPhone 6, iPhone 11, iOS 14

Is there any way to fix this bug? Where in the source code should I look for it?

**Comment by saghul** [comment]
According to https://caniuse.com/fullscreen it looks like it's only supported on iPads and only partially. We might want to hide the button on Safari. @muscat1 can you please take a look?
