### ISSUE TITLE
URL parameters in urls with hashtag lead to errors in helpers.js

### ISSUE THREAD

**Issue by duerrsimon** [jitsi/jitsi-meet#8532]
### Description:

In a vue.js powered app using the vue router in hash mode and the jitsi external api script to create an iframe to host the video when there are two url parameters I get errors that some of the url parameters failed to be parsed. The script breaks gracefully so the jitsi meet session still works but an error shows up in the Developer Console. I did not get an error if there is one URL parameter.

### Steps to reproduce:

I made a github repo reproducing the bug. 
It is a two page Vue.js app with the jitsi component embedded on two pages:
- page with two URL parameters where the bug occurs
- page without url parameters where the bug does not occur. 

https://github.com/duerrsimon/vue-jitsi-bug

![image](https://user-images.githubusercontent.com/16979577/106727214-83646400-660b-11eb-86f8-18abbcaa316c.png)

You can run this example locally by installing using npm.

Surprisingly I do not get the same error on codesandbox.io
https://codesandbox.io/s/vue-jitsi-hashtag-6rwb8

### Expected behavior:

The jitsi meet script should not read/try to parse URL parameters of the page it is embedded in.

### Actual behavior:
Jitsi tries reading the url parameters. In my case the URL looks like this: http://localhost:57900/#/?id=test&foo=bar

And the error is as follows:
```
Failed to parse URL parameter value: test SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseURLParams.js:49
    at Array.forEach (<anonymous>)
    at c (parseURLParams.js:33)
    at Module.<anonymous> (constants.js:12)
    at n (bootstrap:19)
    at Object.<anonymous> (index.js:3)
    at n (bootstrap:19)
    at bootstrap:83
    at external_api.js:1
```

### Server information:

- Jitsi Meet version: Public Jitsi Meet API

### Client information:

- Browser / app version: Tested in Webkit browser (Edge, Google Chrome) latest version
- Operating System: Windows 10

**Comment by gvsakhil** [comment]
I am facing the same issue in Angular 12

**Comment by plokk** [comment]
I am receiving similar errors when having query style parameters in hash part of the URL. It is enough to have eg. `#foo=bar` in the URL of the page that loads [external_api.js](url) to reproduce this issue. Without `=` there is no error.

```
Failed to parse URL parameter value: bar SyntaxError: Unexpected token b in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (index.js:19:22)
    at parseURLParams.js:58:63
    at Array.forEach (<anonymous>)
    at parseURLParams.js:42:16
    at Object.754 (constants.js:12:23)
    at n (bootstrap:19:22)
    at Object.872 (index.js:3:18)
    at n (bootstrap:19:22)
    at startup:4:27
```

It seems that the error comes from `Bourne.parse(decoded)` call in [parseURLParams.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/util/parseURLParams.js#L58)
