### ISSUE TITLE
Mobile completely ignores local streaming video quality changes

### ISSUE THREAD

**Issue by inspifinity** [jitsi/jitsi-meet#8533]
### Description:

when I try to change this [file](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/tracks/functions.js) and set in `createLocalTracksF` different constraints for `createLocalTracks` it does't work. Whatever resolution and constraints i set it always stream the same quality video without any changes.

### Steps to reproduce:

go to this [file](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/tracks/functions.js) change constraints in `createLocalTracks` to 
```
{
              video: {
                aspectRatio: 16 / 9,
                height: {
                    ideal: 480,
                    max: 480,
                    min: 480
                }
              }
} 
```
Run Android sample project streaming video quality didn't change
Then do the change in the same file to
```
{
              video: {
                aspectRatio: 16 / 9,
                height: {
                    ideal: 1080,
                    max: 1080,
                    min: 1080
                }
              }
} 
```
Run again Android sample project streaming video quality still remain the same.
No effect at all.

### Expected behavior:
local video streaming quality must change depending on constraints set in `createLocalTracks`
### Actual behavior:
local video streaming quality never change whatever constraints is set

### Server information:
https://meet.jit.si/

### Client information:
Android 10

**Comment by saghul** [comment]
Yep, this is a limitation we currently have on mobile devices. Video resolution is hardcoded to 360p at 30fps.

**Comment by inspifinity** [comment]
> Yep, this is a limitation we currently have on mobile devices. Video resolution is hardcoded to 360p at 30fps.

How to change this? Where in the code this hardcoded parameter? We have to find solution now. Please help.

**Comment by saghul** [comment]
You can change it here for Android: https://github.com/jitsi/jitsi-meet/blob/5ef60c3a7d6175169dec7fbb1e1aff729b2e3019/android/app/src/main/java/org/jitsi/meet/MainActivity.java#L156 and here for iOS: https://github.com/jitsi/jitsi-meet/blob/99ac60ed741b4bdd811660b41b4ec2b7df358433/ios/app/src/AppDelegate.m#L37

**Comment by atonamy** [comment]
> You can change it here for Android:
> 
> https://github.com/jitsi/jitsi-meet/blob/5ef60c3a7d6175169dec7fbb1e1aff729b2e3019/android/app/src/main/java/org/jitsi/meet/MainActivity.java#L156
> 
> and here for iOS:
> https://github.com/jitsi/jitsi-meet/blob/99ac60ed741b4bdd811660b41b4ec2b7df358433/ios/app/src/AppDelegate.m#L37

But where exactly this change in javascript code? since `setFeatureFlag` still passing this data to javascript

**Comment by saghul** [comment]
> But where exactly this change in javascript code? since `setFeatureFlag` still passing this data to javascript

What are you trying to accomplish? This change accomplishes what was requested.

**Comment by atonamy** [comment]
> > But where exactly this change in javascript code? since `setFeatureFlag` still passing this data to javascript
> 
> What are you trying to accomplish? This change accomplishes what was requested.

I just try to understand logic of javascript code because the core of conference happening there. For example If we use pure react-native app so this `setFeatureFlag` doesn't exists and somewhere in javascript it can be changed right? and `createLocalTracks` constraints doesn't work so what exactly it use instead then?

**Comment by saghul** [comment]
Those flags are an object that gets passed as a prop to the root component. From there, we read them and override the config.

Here is how this feature got implemented: https://github.com/jitsi/jitsi-meet/commit/7d513738d2179b68a8b21233d2bc9e93d3da05ab

**Comment by inspifinity** [comment]
@saghul 
If I understood this code correctly `setFeatureFlag` trigger  `setReceiverVideoConstraint` [here](https://github.com/jitsi/jitsi-meet/blob/9ed1969f7ee160f6f0b392701f1e8a5eb8787c45/react/features/video-quality/middleware.js#L129)
then if we have look implementation of `setReceiverVideoConstraint` [there](https://github.com/jitsi/lib-jitsi-meet/blob/77978f0e621f463ed606fe94dda25ff18f1d5f64/modules/RTC/TraceablePeerConnection.js#L2317) we can see the condition:
```
//XXX: This is not yet supported on mobile.
    if (browser.isReactNative()) {
        return Promise.resolve();
    }
```

Did I get it correctly that even `setFeatureFlag` to change video quality doesn't work as well? Since this condition prevent it?

But react-native-webrtc actually support video constraints. Why u do not support it in Jitsi source code?
```
import {getUserMedia} from 'react-native-webrtc'
 getUserMedia(
      {audio: true, video: vidConstraints}
      stream => { ... },
      err => { ... }
    )
```
Or I miss something? Please help deeply understand this case.

**Comment by saghul** [comment]
Sorry, I don't have the time to walk you through the codebase, I know it's not straightforward, so I'm sorry for that.

Note that there are 2 things here: the sending and receiving. The receiving is applied just fine, and the sending is indeed not being applied to RN in that function, but that's ok because we open the camera at 360p already so there is nothing to apply.
