### ISSUE TITLE
Jitsi stops working when more than two people are in a room

### ISSUE THREAD

**Issue by JaapJoris** [jitsi/jitsi-meet#8534]
### Description:

I have installed Jitsi Meet on my Debian 10 server following the instructions of the [Self-Hosting Guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart). It works perfectly until a third person joins the room. Then the video and audio of the others disappear and only their avatars remain visible.

### Steps to reproduce:

1. Person 1 joins the room
2. Person 2 joins the room
3. Persons 1 and 2 can communicate succesfully
4. Person 3 joins the room
5. Video and audio of others disappear. All everyone sees is themself.
6. One person leaves the room
7. After a few seconds, the video and audio streams reappear and the remaining persons can communicate again.

### Server information:

- Jitsi Meet version: 2.0.5390-3
- Operating System: Debian 10 (default Linode image)

### Client information:

This problem occurs for every client connected to my server,  whether they run Linux, macOS, Windows or Android.

### Additional information:

I have looked at server logs and javascript logs which both contain lots of information, but I am not sure what to look for. I will be happy to provide more information when requested.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This is network configuration problem, you need to forward port udp 10000 to jvb. Check out https://jitsi.org/qi advanced section.
