### ISSUE TITLE
[iOS] Binary rejected because of suspicious link embedded into JitsiMeetSDK

### ISSUE THREAD

**Issue by jsearle** [jitsi/jitsi-meet#8535]
### Description:

There is a **suspicious link** inside a localization file that makes the iOS JitsiMeetSDK v3.0.0 release invalid for production. I have implemented JitsiMeetSDK v3.0.0 into my app and **Apple Review team rejects the binary** because of a forbidden link (pointing to https://blog.bebbin.ir/e2ee/) that is embedded into the iOS framework binary. 

I did some further exploration and it seems like one specific Persian translation file: lang/main-fa.json contains a link to some strange website instead of the intended site: https://jitsi.org/blog/e2ee/

You can find the URL here:
https://github.com/jitsi/jitsi-meet/search?q=bebbin 

### Steps to reproduce:

1. Embed the new v3.0.0 iOS JitsiMeetSDK Framework into an iOS app.
2. Upload to Apple Connect and send for review process.
3. Apple Review team rejects the binary with this message: "In distributing apps on the App Store, Apple must comply with U.S. laws. Under U.S. sanctions regulations, the App Store cannot host, distribute or do business with certain apps or developers connected to U.S. embargoed countries or regions. This also extends to Iran, which is currently subject to comprehensive restrictions."

### Additional information:

1. Some of the JSON files inside /lang/ directory have an entry for "e2eeDescription" that points to https://jitsi.org/blog/e2ee/
https://github.com/jitsi/jitsi-meet/search?q=e2eeDescription
2. The same entry in the Persian file points to a different URL: https://blog.bebbin.ir/e2ee/
3. As this URL is embedded into the SDK iOS framework, Apple considers this as a suspicious link and they reject the binary.

Suspicious URL: https://blog.bebbin.ir/e2ee/ should be changed to the correct URL: https://jitsi.org/blog/e2ee/

**Comment by damencho** [comment]
Fixed with 20c6115c3821b8d12c6d5d334372953c67159486

**Comment by ccs1428** [comment]
@damencho  Same issue noticed by Apple in version 3.0.2

Sharing application version details

pod 'JitsiMeetSDK', '~> 3.0.2'

Please help.

**Comment by damencho** [comment]
Not sure whether 3.0.2 uses that commit, but that should be fixed in latest versions.

**Comment by ccs1428** [comment]
@damencho Latest version getting 3.0.2 as per pod install, please confirm.

**Comment by damencho** [comment]
@saghul help? I have no idea where is that coming from
I know the latest is 4.1.0
https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi/react/jitsi-meet-sdk

**Comment by ccs1428** [comment]
When i try to upgrade to 4.0.0, getting this error message. We are discussing about ios build issue, Maven repository are using basically for android right?

[!] CocoaPods could not find compatible versions for pod "JitsiMeetSDK":
  In Podfile:
    JitsiMeetSDK (~> 4.0.0)

None of your spec sources contain a spec satisfying the dependency: `JitsiMeetSDK (~> 4.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by ccs1428** [comment]
@damencho @saghul Please confirm.

**Comment by jbg** [comment]
@ccs1428 did you try following the suggestions in the error message?

**Comment by ccs1428** [comment]
Yes, As per suggestion, I have manually updated the URL and submitted for review.

**Comment by jbg** [comment]
specifically
> out-of-date source repos **which you can update with pod repo update or with pod install --repo-update**.

4.1.0 installs fine here via CocoaPods.

**Comment by ccs1428** [comment]
@jbg Thank you. Now i am able to update .

@jbg  @damencho Thank you for the kind support.
