### ISSUE TITLE
Missing red frame during screen sharing

### ISSUE THREAD

**Issue by krzyzak687** [jitsi/jitsi-meet#8538]
Hello.

I would like to report that during screen sharing, there is no red frame which points which exactly screen I am sharing to the audience.
In other communication application the red frame is viable on the screen which is shared. Good example is Skype. This feature is very useful if you have more that one screen and you want to know which exactly screen you are sharing right now.

I am now sure if it is lack of feature or bug.

**Comment by pintonava** [comment]
Any update about this?

**Comment by cezariuszmarek** [comment]
Is it a limitation of the screen capture API?

**Comment by saghul** [comment]
If you are using the browser yes, there is nothing we can do.

In Electron others have made a custom build, which we are not keen on doing at this stage. The provided APIs cannot do it yet.
