### ISSUE TITLE
jitsi meet without hermes

### ISSUE THREAD

**Issue by deepakverma4** [jitsi/jitsi-meet#8542]
### Steps to reproduce:

1. set ```enableHermes: false``` in ```android/app/build.gradle```

i dont want to enableHermes in my project but if i disable hermes jitsi meet crashes. for enableHermes: true it works fine.
any way to use jitsi meet with hermes disabled

### Expected behavior:

application crashes on start meeting

### Actual behavior:

jitsi meet should start

### Server information:

- Jitsi Meet version: 
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
We no longer use Hermes. Are you running the latest version?

**Comment by deepakverma4** [comment]
@saghul no I build my custom SDK by taking latest pull in October 2020 i guess.

**Comment by saghul** [comment]
Please use the latest, we don't have resources to support all old versions.

**Comment by deepakverma4** [comment]
@saghul  i want to disable member joining background  sound (that "woosh" one), and "Recording is on" sound. Can you please guide me where to find that code, i am building my own custom sdk.

**Comment by deepakverma4** [comment]
@saghul  yes latest sdk fixed that :)
i am also facing screen sharing problem #8553 
can you please help me in this?
