### ISSUE TITLE
Mobile: Use Websockets instead of BOSH

### ISSUE THREAD

**Issue by awlx** [jitsi/jitsi-meet#8543]
Is there a specific reason why the Mobile App still uses BOSH?

As Websockets are described as more reliable it should be better for flaky connections to utilise them instead of BOSH.

**Comment by paweldomas** [comment]
There's a PR for this change, but not merged yet: https://github.com/jitsi/jitsi-meet/pull/7579

**Comment by nightvisi0n** [comment]
Hey there, any news about this one? Would be great to have websocket support in the mobile app :+1:

**Comment by ankar84** [comment]
Nice to see WS instead of BOSH on Mobile!

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/pull/7579 landed already, we are still testing it but you can enable it with the flag you can see in that PR.
