### ISSUE TITLE
Feature Flag for screen share in android

### ISSUE THREAD

**Issue by ShubhamJuIT** [jitsi/jitsi-meet#8545]
**Is your feature request related to a problem you are facing?**
No

**Describe the solution you'd like**
Right now screen share is open for every users, bu i want it to be open for some users only, not for all. Can we have a feature flag to control the screen share visibility controllable.

**Describe alternatives you've considered**
NA

**Comment by saghul** [comment]
Sure, let's have a feature flag for it. Would you like to submit a PR?

**Comment by ShubhamJuIT** [comment]
@saghul Will create a PR for the same

**Comment by priyankagupta23pg** [comment]
Are we having any featureflag for screen sharing option in jitsi

**Comment by saghul** [comment]
We currently have an iOS specific feature flag since it requires extra setup from the app on that platform. No flag on Android.
