### ISSUE TITLE
[Problem] 'Another you' what's the unique identifier of meet user?

### ISSUE THREAD

**Issue by Liuchunqi3240** [jitsi/jitsi-meet#8554]
I found a couple of me in one room .

1.  xcode join room 
2. xcode restart project and join room 
3. You see another you

what I should do something to avoid it?

**Comment by saghul** [comment]
There is a 60s timeout for "ungraceful" disconnects. In order to avoid it you can just end the call gracefully by pressing the hangup button.

**Comment by Liuchunqi3240** [comment]
60s repeat connect , I will see some not my mind person.
can I change the id , bind to a constant APPID.
what should I do?

**Comment by saghul** [comment]
Sorry I don't understand what you mean. Can you rephrase?
