### ISSUE TITLE
Sorry, I don't have the time to walk you through the codebase, I know it's not straightforward, so I'm sorry for that.

### ISSUE THREAD

**Issue by atonamy** [jitsi/jitsi-meet#8558]
Sorry, I don't have the time to walk you through the codebase, I know it's not straightforward, so I'm sorry for that.

Note that there are 2 things here: the sending and receiving. The receiving is applied just fine, and the sending is indeed not being applied to RN in that function, but that's ok because we open the camera at 360p already so there is nothing to apply.

_Originally posted by @saghul in https://github.com/jitsi/jitsi-meet/issues/8533#issuecomment-773934235_

Maybe you can advise someone who knows codebase very well? My company ready to pay hourly to help with jitsi source code.

**Comment by inspifinity** [comment]
@saghul any updates on this?

**Comment by saghul** [comment]
No updates, sorry can't walk you trough the code. I provided a couple of pointers or where the rabbithole starts.
