### ISSUE TITLE
[iOS] Open camera from CallKit native UI

### ISSUE THREAD

**Issue by PauMateu** [jitsi/jitsi-meet#8559]
**Is your feature request related to a problem you are facing?**
We are currently using jitsi SDK to handle calls in our application. So far everything has worked out great. Now we are trying to integrate iOS callkit (with VoIP notifications) to handle the logic of displaying/answering/rejecting a call. 

When the user has the phone unlocked, we are able to open our application once the user accepts the call, where the Jitsi View is displayed; however, when the user has the phone locked, we are displaying the native call interface, as we have no other choice. Everything works as intended, but we are not able to configure the Camera button displayed in the Native UI so that it forces Jitsi View to open the camera.

**Current Behavior:**
1 - The user has the phone locked and receives an incoming call via VoIP notifications.
2 - User answers the call, we load jitsi URL to join the meeting. Native call UI handler is displayed.
3 - User clicks the video button in the iOS native UI.
4 - The phone displays the unlock pattern/combination, as it is trying to open the app.
5 - User unlocks the phone, Jitsi meet view is displayed, but the video option is not on.

**Describe the solution you'd like**
**Expected behavior**_(1 - 4 are identical)_
_1 - User has the phone locked and receives an incoming call via VoIP notifications.
2 - User answers the call, we load jitsi URL to join the meeting. Native call UI handler is displayed.
3 - User clicks the video button in the iOS native UI.
4 - The phone displays the unlock pattern/combination, as it is trying to open the app._
5 - User unlocks the phone, Jitsi meet view is displayed, **with the video option turned already on**.

Is there any way that we can force Jitsi to change to _video_ call, instead of just audio? We haven't found any SDK functionality to interact with the jitsi View, other than loading the URL. Should we modify the SDK to expose some of the logic, or are we missing something?

Thanks!

**Comment by saghul** [comment]
This is somewhat an iOS limitation. You have no control over the "video" button in the CallKit interface. You'll see that what happens is a new call is made to the same destination when you press it.

Not sure how you could detect that that specific button was pushed. You can use the `startWithVideoMuted` and `startWithAudioOnly` options to start a call with video, but the problem is you need to know when to set them.

**Comment by PauMateu** [comment]
Thanks for the insight!! So, if we are able to detect that the _video_ button is pressed, and we load the same jitsi URL but with the options that you specified, the intial call will be _somehow_ substituted with a new jitsiCall with video?

**Comment by saghul** [comment]
Yep that should do it.

**Comment by Vaib777** [comment]
> Thanks for the insight!! So, if we are able to detect that the _video_ button is pressed, and we load the same jitsi URL but with the options that you specified, the intial call will be _somehow_ substituted with a new jitsiCall with video?

Have you implimented this ,
if yes please help
