### ISSUE TITLE
Camera and Mic no longer working in iframe with Chrome 88

### ISSUE THREAD

**Issue by htcheng** [jitsi/jitsi-meet#8566]
### Description:

Embedding a Jitsi meeting via an iframe results in the mic and camera permissions being rejected by Chrome beginning with Chrome 88. We have verified that this is not a CORS or SSL or allow= issue as identified in previous reports with other versions of Chrome. Visiting outside of an iframe works with Chrome 88. 

Visiting inside the iframe works with Safari, Firefox and other non-Chrome 88-based browsers.

### Steps to reproduce:

1. Go to any page where you previously had an iframe embed with a Jitsi meeting using Chrome 88

e.g  <iframe src="https://meet.jit.si/ewofkfiojdfoijgoidfjhgdofgerg" width="640" height="360" frameborder="0" allow="camera;microphone;display-capture" allowfullscreen allowusermedia></iframe>

2. You will find that the camera and mic permissions are denied access by the local user
3. Visiting the same Jitsi meeting outside of the iframe works
4. Visiting the same Jitsi meeting inside the iframe works with Chrome 87 and prior versions as well as Safari, Firefox and other browsers - but not the latest Edge (which is Chrome-based)
5. Problem occurs on meet.jit.si, beta.meet.jit.si, alpha.jitsi.net and self-hosted Jitsi

### Expected behavior:

Camera and mic should be allowed within the iframe

### Actual behavior:

Camera and Mic permissions are blocked and do not work. Console log indicates the are being rejected by the user even though the user is never prompted for permission.

### Server information:

- Jitsi Meet version: tested on 2/4/20 on meet.jit.si, beta.meet.jit.si, alpha.jitsi.net and self-hosted jitsi running latest master stable as of 2/5/20
- Operating System: Ubuntu 18.04LTS and Ubuntu 20.04LTS

### Client information:

- Browser / app version: Chrome 88, Microsoft Edge
- Operating System: Tested on MacOS 11, MacOS 10.15, Windows 10 using Chrome 88 on all platforms and MS Edge on Windows 10

Works using Chrome 87 on all platforms as well as Safari 14, Firefox

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

I just tested your example and it works, I'm on Chrome Version 88.0.4324.146. What I suspect is that you are serving your HTML from http location, webrtc requires https to be able to work. 
We offer an iframeAPI that you can use: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

**Comment by htcheng** [comment]
We've reviewed the community postings and have tested both the http and https issues and all other issues that were reported in the Community forums. We ran our tests from multiple locations and computers across different countries and continents and were able to reproduce this issue across all locations. We will take another look, but please don't lecture me on RTFM when we actually did RTFM and review the forum.

**Comment by damencho** [comment]
I said `Please, when you have questions or problems use the community forum before opening new issues, thank you.` Which has nothing to do with the manual.
We prefer keeping github issues strictly for issues, and discuss problems and debug possible issues in the forum, before opening new issues. This is already stated in the issue templates, which people ignore.
Send me an example that does not work. I tested the example you provided and was able to see my local camera feed.

**Comment by htcheng** [comment]
OK - we just retested this HTML file in our local browsers on MacOS 11, Chrome Version 88.0.4324.150 and it still has the same issue. I've attached a screenshot of the window along with the javascript console.

![Screen Shot 2021-02-05 at 2 30 12 PM](https://user-images.githubusercontent.com/42881720/107096086-cb77b800-67be-11eb-90aa-0e22375b094b.png)
![Screen Shot 2021-02-05 at 2 30 02 PM](https://user-images.githubusercontent.com/42881720/107096092-d2062f80-67be-11eb-91ad-9538e9ac235e.png)

[Test.txt](https://github.com/jitsi/jitsi-meet/files/5935665/Test.txt)

**Comment by damencho** [comment]
As I said earlier, you need to be serving the file using https, you cannot open it from the local filesystem. 
You need to put it on a webserver on a secure https connections.

**Comment by saghul** [comment]
`file://` might not be treated as a trusted origin. I recommend you server the fie over HTTP in localhost, or better yet over HTTPS as @damencho pointed out earlier. WebRTC APIs only work on secure origins.

**Comment by htcheng** [comment]
Sorry, you're probably right - we did test it previously on two different servers over HTTPS and got the same results - we'll run the test again over https and capture the results so we can document it for you. The frustrating thing is that everything worked perfectly before Chrome 88 (and still does!) as well as on Safari and Firefox, but it's only Chrome 88 causing this issue with an iframe... Will re-run and document... Chrome 88 did introduce a lot of strict security interpretations vs previous versions.

**Comment by htcheng** [comment]
Ok - we ran the tests again on a third virgin server and you are correct, it is working, so we'll debug our configurations on the other two servers. Will update this thread in case someone else runs into this problem in the future. 

Next time, we will ask on the forums first - thanks for your help!

**Comment by htcheng** [comment]
UPDATE: It appears that we had the HTTP Feature-Policy header configured as "feature-policy: geolocation 'self'; midi 'self'; sync-xhr 'self'; microphone 'self'; camera 'self'; magnetometer 'self'; gyroscope 'self'; speaker 'self'; fullscreen 'self'; payment 'self'; usb 'self'" and Chrome 88 seems now to respect this header whereas previously Chrome did not. Safari 14 and Firefox seem to avoid this header for now which explains why those browsers work and Chrome 88 does not...
