### ISSUE TITLE
No Email Client to select

### ISSUE THREAD

**Issue by peternsomerset** [jitsi/jitsi-meet#857]
Hi,
I just used the website to video chat to my friend who is IT literate but quite old (90!) and with poor eyesight!
I then went through the procedure him to send me an email to me but he cannot see his mail client in the list to choose from.
He is using Windows 10 with Chrome but with "MS Mail".
Should Jitsi Meet work with these pieces of S/W?
If so can you suggest what is wrong?
Thanks for your time 

Peter H

**Comment by aamoyg** [comment]
Are you using screensharing to see his desktop?

**Comment by peternsomerset** [comment]
Hi,
This was asked quite a while ago and he uses it with me occasionally (me screen sharing my desktop).

Jitsi seemed to automatically open my client (Thunderbird on Linux OS) with the link already inserted which he could not do.  I have just tried to repeat the action and I seem now to only be able to cut and past a link into my email client,  which he can also do so there is no problem.  

Thanks

**Comment by damencho** [comment]
Yep this is now not relevant, closing it.
