### ISSUE TITLE
how to migrate from JitsiMeet.framework to JitsiMeetSDK.xcframework

### ISSUE THREAD

**Issue by deepakverma4** [jitsi/jitsi-meet#8570]
### Description:

i am using a wrapper of jitsi meet for react native, which is using ```JitsiMeet.framework``` i want to use the newly generated SDK i.e ```JitsiMeetSDK.xcframework``` insted of that. But when i replace ```JitsiMeetSDK``` folder with the newly generated xcframework i get error ```JitsiMeet/JitsiMeet.h``` not found.

### Steps to reproduce:

1. clone latest master branch
2. generate custom SDK
3. replace new SDK with old one
4. run

### Expected behavior:

it should build new SDK
### Actual behavior:

It gives header files not found header

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by G10dRafaFan** [comment]
Hi @deepakverma4 ,
Facing the same issue, did you find any solution to solve the issue?

**Comment by Earvonio** [comment]
Hi, I have the same problem. How can I solve this?

**Comment by saghul** [comment]
You'll need to adjust the imports to `<JitsiMeetSDK/JitsiMeet.h>`

**Comment by shooding** [comment]
You'll need to adjust the imports from
#import <JitsiMeet/JitsiMeet.h>
to
#import <JitsiMeetSDK/JitsiMeetSDK.h>
