### ISSUE TITLE
Issues with config.js and screensharing.

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#8574]
### Steps to reproduce:

It's two issues really. For the first, I set the constraints to 720 and I think Jitsi is totally ignoring it. It's the correct config not the example one.

It is running on a VPS Ubuntu 20.04.

All my screen shares show up at 1920x1080 no matter what browser I try it with.

For the second issue the screen sharing itself sometimes runs at very low FPS. I've tried, over the course of hours, just about every config.js combination imaginable. I'm testing it with a video of a video game (csgo).

It seems to work best when I open two tabs and connect to the same call on the same machine, but when I try it with two different machines it's horribly laggy, the fps is set to 60 max and 15 min in the config.

Using VP8 seems to have the best result but there's still periods of intense low frames and lag.

One thing I noticed was that when the bitrate is about ~2500-2700 it's fine, but the bitrate frequently drops to below 1k and that's when the stuttering starts. 

I thought that maybe it could be not enough resources from the VPS, but I even purchased a more expensive VPS with 4g of ram and 2 cpu from OVH cloud and the issue still persisted.

My connection is about 20-30 MBps down and about half that up. That's why I've thought my internet isn't really an issue here.

Enabling p2p seemed to help a bit, but I like raising the opus to around 128 kbps so I disable p2p.

I have tried both the stable version of jitsi meet and the unstable version, it didn't make a difference.

I've struggled for hours with this. Please if someone could help me I would be so grateful!
### Expected behavior:

Smooth 720p screen sharing

### Actual behavior:

Choppy low frame rate 1080p screen sharing.

### Server information:

- Jitsi Meet version: I tried the current stable versions of the jitsi components as well as the unstable. I can get an exact version tomorrow if it's necessary. But since the issue happens all the way up to the newest nightly version, I doubt it's that important.

- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: firefox/edge/chrome/electron

Yes I tried every one of those!

- Operating System: Windows 10 64x

### Additional information:

Please ask what information you need and I will gladly provide it!

**Comment by saghul** [comment]
> It's two issues really. For the first, I set the constraints to 720 and I think Jitsi is totally ignoring it. It's the correct config not the example one.

Do you use the manage call quality slider? What browser are you using?

> All my screen shares show up at 1920x1080 no matter what browser I try it with.

Note that not all browsers use the DPi multiplier.

> For the second issue the screen sharing itself sometimes runs at very low FPS. I've tried, over the course of hours, just about every config.js combination imaginable. I'm testing it with a video of a video game (csgo).

That's somewhat expected, browsers use flower fps and prefer a higher quality of picture. It's not really designed for high fps shares. @jallamsetty1 did we add settings to try to do high fps?

**Comment by damencho** [comment]
You can turn on your video while screen sharing I thing that uses higher fps

**Comment by jallamsetty1** [comment]
@DillFrescott Please note that the video constraints config has no effect on the resolution of the desktop share. Those options will be used only for camera capture, not for screenshare. The resolution of the desktop stream depends on the resolution of the screen you are sharing, i.e. if you are sharing your entire 1080p display, this will produce a 1080p desktop track.

For higher fps, please make sure you have `testing.capScreenshareBitrate=0` along with the `desktopSharingFrameRate.max` value in your config.js.

We do have an option to resize the desktop share always to 720 when the camera is enabled while screenshare is in progress.
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L293
We added this option since turning on the camera forces the browser to produce the desktopshare+camera stream at 30 fps which can be very cpu intensive and not all machines have that capability degrading the quality of the stream.

**Comment by DillFrescott** [comment]
> 
> 
> > It's two issues really. For the first, I set the constraints to 720 and I think Jitsi is totally ignoring it. It's the correct config not the example one.
> 
> Do you use the manage call quality slider? What browser are you using?
> 
> > All my screen shares show up at 1920x1080 no matter what browser I try it with.
> 
> Note that not all browsers use the DPi multiplier.
> 
> > For the second issue the screen sharing itself sometimes runs at very low FPS. I've tried, over the course of hours, just about every config.js combination imaginable. I'm testing it with a video of a video game (csgo).
> 
> That's somewhat expected, browsers use flower fps and prefer a higher quality of picture. It's not really designed for high fps shares. @jallamsetty1 did we add settings to try to do high fps?

The call quality slider doesn't seem to affect the screen share at all :(

I tried using a few browsers, Firefox, Chrome, Edge, and the electron client.

Ok. Thats understandable. Thank you for the response. I just wasn't sure if it was a bug or not.

**Comment by DillFrescott** [comment]
> 
> 
> You can turn on your video while screen sharing I thing that uses higher fps

Ok. I'll try that. Thank you.

**Comment by DillFrescott** [comment]
> 
> 
> @DillFrescott Please note that the video constraints config has no effect on the resolution of the desktop share. Those options will be used only for camera capture, not for screenshare. The resolution of the desktop stream depends on the resolution of the screen you are sharing, i.e. if you are sharing your entire 1080p display, this will produce a 1080p desktop track.
> 
> For higher fps, please make sure you have `testing.capScreenshareBitrate=0` along with the `desktopSharingFrameRate.max` value in your config.js.
> 
> We do have an option to resize the desktop share always to 720 when the camera is enabled while screenshare is in progress.
> https://github.com/jitsi/jitsi-meet/blob/master/config.js#L293
> We added this option since turning on the camera forces the browser to produce the desktopshare+camera stream at 30 fps which can be very cpu intensive and not all machines have that capability degrading the quality of the stream.

Ok. Thank you. Any plans on allowing the quality slider to affect screen share as well?

**Comment by DillFrescott** [comment]
One last question. When I screen share using Firefox and watch using the electron client on the same machine, the quality is perfect at around 50 fps.

It only deteriorates when on another machine.

Is this indicative of a network issue?

**Comment by jallamsetty1** [comment]
> > @DillFrescott Please note that the video constraints config has no effect on the resolution of the desktop share. Those options will be used only for camera capture, not for screenshare. The resolution of the desktop stream depends on the resolution of the screen you are sharing, i.e. if you are sharing your entire 1080p display, this will produce a 1080p desktop track.
> > For higher fps, please make sure you have `testing.capScreenshareBitrate=0` along with the `desktopSharingFrameRate.max` value in your config.js.
> > We do have an option to resize the desktop share always to 720 when the camera is enabled while screenshare is in progress.
> > https://github.com/jitsi/jitsi-meet/blob/master/config.js#L293
> > We added this option since turning on the camera forces the browser to produce the desktopshare+camera stream at 30 fps which can be very cpu intensive and not all machines have that capability degrading the quality of the stream.
> 
> Ok. Thank you. Any plans on allowing the quality slider to affect screen share as well?

I am afraid not. We had it on for p2p mode but the quality was bad as result of downscaling. Unlike video, text (on desktop tracks) doesn't render properly when it is downscaled, it becomes illegible. We received many complaints about it and decided to remove that functionality.

**Comment by DillFrescott** [comment]
@jallamsetty1 Ok. That makes sense. I have had some issues with my internet connectivity lately, so perhaps that's causing some of the stuttering I've experienced with the screensharing.

As an example, I had the screensharing stuck at 1 fps for a good few minutes, and the minimum in the config is set to 15.
