### ISSUE TITLE
Android App does not support subdirectory installations

### ISSUE THREAD

**Issue by outis151** [jitsi/jitsi-meet#8575]
### Description:

When jitsi is installed at: `http://example.com/meet/` the android app ignores the `/meet/` and still tries to connect to `http://example.com/`

### Expected behavior:

The app should honor the  `/meet/` 

### Server information:

- Jitsi Meet version: docker-jitsi-meet stable-5390-3
- Operating System: Debian 10 / Linux

### Client information:

- App version: 20.6.0
- Operating System: Android 10

**Comment by saghul** [comment]
Historically we haven't supported this scenario very well. With the advent of free TLS certificates thanks to Let's Encrypt, this has not been a priority, sorry.

**Comment by outis151** [comment]
Would a pull request be accepted introducing this?
