### ISSUE TITLE
Volume Control slider in Participant Window disappears

### ISSUE THREAD

**Issue by gjaekel** [jitsi/jitsi-meet#8577]
### Description:

On the three-dots-menu of every participants Local Video window, there's a volume slider to control the local audio level of the corresponding participant.

As a regression, pulling this slider to the left limit, i. e. "zero" make the whole menu entry vanishing. There seems no way to get it back, what is even worse if this happens "unintentional" while adjusting the audio level because this participant is actually full muted. One have to rejoin the session to get it back.

### Steps to reproduce:

1. Join a meeting with participants
2. Open the three dots menu of a Local Video window
3. Adjust the local audio volume to zero by setting the volume slider to left limit.

### Expected behavior:

Volume is set to zero

### Actual behavior:

The menu entry vanishes.

### Server information:

This is a regression in a recent version of the Web UI. Because I don't use this feature very often, I can't determine a date or version.

### Client information:

Probably independent of used client.

- At least Chrome-87 and FF-85.0
- Linux (Ubuntu 16)

### Additional information:

It seems to me that the is a clash between internal volume level and the visible/enable state of the widget, i.e. `enabled :<=> (volume > 0)`. Maybe it's enough to limit the slider lower limit to `1`, because this will make no difference in practical use.
https://github.com/jitsi/jitsi-meet/blob/9f9e192c3ca795826b08e0bfca79a2ea081844e5/react/features/remote-video-menu/components/web/VolumeSlider.js#L85

BTW: In addition this volume control don't seems to be logarithmic: Setting the slider to 50% don't reduce the volume level to the half "in my ears". This is a very common mistake in implementing volume control as a result of the difference between loudness and amplitude. From that one may also raise an independent issue "Make volume control logarithmic".

**Comment by damencho** [comment]
Fixes in https://github.com/jitsi/jitsi-meet/pull/8587
