### ISSUE TITLE
Shows "You have been disconnected" and got errors in console

### ISSUE THREAD

**Issue by dmelechow** [jitsi/jitsi-meet#8580]
<img width="1224" alt="Screenshot 2021-02-07 at 22 59 07" src="https://user-images.githubusercontent.com/11187627/107157963-1698f300-6998-11eb-97e1-7779ec8a6543.png">

I use  `<script src='https://meet.jit.si/external_api.js'></script> ` on my website, I didn't catch that error before, but last several days it reproduces random, sometimes it happens sometimes not. 

Who knows what I can do? Thank you in advance

**Comment by damencho** [comment]
Thank you for the report, we are aware of it and are working on fixing it. Will post updates here.

**Comment by damencho** [comment]
We had pushed a temporary fix that will mitigate the problem for now till we find the cause of it. If it happens again and you see the reload screen and the console log `Detected that shard changed` please re-open the issue.

Thank you for the report.
