### ISSUE TITLE
Jitsi doesn't work on Safari IPhones

### ISSUE THREAD

**Issue by dmelechow** [jitsi/jitsi-meet#8582]
I use <script src='https://meet.jit.si/external_api.js'></script> on my website, 

Jitsi doesn't work on Safari on iPhones,  just nothing happened after opening it. I tried OS versions 14.3 and 13.6.1

I remember It worked before, Should I add something to set up opening JitsiMeetExternalAPI?

Who knows what I can do? Thank you in advance

**Comment by enspireagencia** [comment]
Did you get any solution for the problem? I'm in the same situation.

**Comment by saghul** [comment]
What problem? Jitsi Meet works in Safari.

**Comment by enspireagencia** [comment]
@saghul If I access my Jitsi installation directly it works. But if I integrate it using the Iframe API, the message below appears.
![Imagem do WhatsApp de 2023-05-09 à(s) 15 59 20](https://github.com/jitsi/jitsi-meet/assets/64867055/8ee96615-83c2-4b94-9ffb-7fb7983ade98)

**Comment by saghul** [comment]
That's odd! What version are you running on your deployment?

**Comment by enspireagencia** [comment]
I use vue-jitsi-meet with vue 2 which consumes the external_api from my Jitsi installation.

**Comment by enspireagencia** [comment]
Image Docker - Jitsi Stable 8615
![Captura de tela 2023-05-10 093051](https://github.com/jitsi/jitsi-meet/assets/64867055/b0849390-52c6-462d-ba55-91f310c165fa)

**Comment by enspireagencia** [comment]
Now I'm running the same version in all containers. I did some tests in the browser itself using responsiveness mode. And I checked that whenever the user-agent is from the Iphone the problem occurs.

**Comment by saghul** [comment]
Do you have a publicly accessible URL to test it out?

**Comment by enspireagencia** [comment]
I have published a test version at this URL https://vemdechamada.com/test-stream
To reproduce the error i did the test with the Iphone, and any version the error occurs.
![Captura de tela 2023-05-10 153400](https://github.com/jitsi/jitsi-meet/assets/64867055/ffab30bd-2f95-49f7-9184-4a3a22b52882)

**Comment by saghul** [comment]
Did you try it on a real device? I just did and it worked no problem. Note we only support Safari >= 14 (so iOS 14) for mobile web, any chance you tested with an older device?

**Comment by saghul** [comment]
Oh, I thought your test URL would be using an iframe.
