### ISSUE TITLE
Ugly scroll on Firefox 81

### ISSUE THREAD

**Issue by sc-sycer** [jitsi/jitsi-meet#8586]
On Linux:

![imagen](https://user-images.githubusercontent.com/745842/107278770-7ce44b00-6a56-11eb-9325-ea1ba708054c.png)

On Windows:

![imagen](https://user-images.githubusercontent.com/745842/107279198-06941880-6a57-11eb-8a21-b2c2572dba45.png)

Looks like it works fine on Chrome and Opera.

Thanks for looking into it!

**Comment by licaon-kter** [comment]
Seeing the same on Firefox 88/89, Linux/Windows for HEAD (da7358d5648175c546878e6ec3889d68e93ed8b9)

**Comment by muscat1** [comment]
The initial issue no longer reproduces due to the css changes made by @hristoterezov in the pagination PRs on the filmstrip. Created a PR for the one mentioned above by @licaon-kter and that should solve our scrollbar issues for now 😅
