### ISSUE TITLE
Duplicated rooms?

### ISSUE THREAD

**Issue by DonPicciotto** [jitsi/jitsi-meet#8590]
### Description:

Sometimes the room I create on meet.jit.si seems to be "duplicated" and new guests report they're inside the room but cannot see anyone else, while other people are already logged in the same room. Seems almost like they are in different room with the same name. Sorry if I can't explain myself better.

### Steps to reproduce:

Create a room on meet.jit.si, enter with someone else (like 2-3 people) and after 10-30 minutes tell someone else to log in in this room.

### Expected behavior:

New guests should enter in the same room where you are and see you and the other guests.

### Actual behavior:

New guests report to be in a room with the same name, but seems to be actually in a different room and can't see you or other users.

### Client information:

- Browser / app version: latest chrome and latest firefox
- Operating System: windows 10

**Comment by saghul** [comment]
When did this happen?

**Comment by DonPicciotto** [comment]
> 
> 
> When did this happen?

More or less a couple of days ago, I think

**Comment by saghul** [comment]
We did have this problem recently. @damencho when did you patch it?

**Comment by damencho** [comment]
It was fixed yesterday 11:30PM UTC. Less than 24 hours ago, so it was that and it is fixed now.
If you see the issue reported back, and send the room name and if possible the console logs. You can send it to damencho at jitsi do org.
Thank you for the report
