### ISSUE TITLE
[iOS] Speaker button not behaving correctly with CallKit integration

### ISSUE THREAD

**Issue by PauMateu** [jitsi/jitsi-meet#8599]
### Description:

When trying to integrate JitsiSDK with iOS callkit, we are having trouble making the speaker/earpiece button from the native UI work:
When a user accepts the call, we configure the audioroute to be _earpiece_. If the phone is locked (so the native Ui is displayed) and the user presses the speaker button, the audio is changed to _speaker_, but the UI does not change (still says that speaker is off), and blocks itself no longer working. It seems that this functionality is not behaving correctly. 

After doing some research, I've stumbled upon [this](https://stackoverflow.com/a/49466250) answer, which seems to indicate that configuring audio session before accepting the call should do the trick. The thing is that we are calling JitsiSDK loadURL **after** the user accepts the call, so the audiosession is configured then.

Has anyone had similar issues? Is there a workaround to make JitsiSDK audiosession compatible with callkit?

_NOTE_
We are working on a Cordova app, so we are using a native plugin to implement the callkit functionality. [This](https://github.com/WebsiteBeaver/CordovaCall) plugin is configuring yet another AudioSession (before the call starts), maybe this is interfering with the Jitsi AudioSession? When using this plugin without calling Jitsi loadURL, the button works fine, it starts behaving incorrectly when Jitsi is initiated.

### Client information:
Tested on iPhone 7

**Comment by saghul** [comment]
The Jitsi Meet SDK will switch to speaker when the call starts and enforce that choice. I believe that's why the button seemingly doesn't work, because we will enforce the speaker again. Unless the user chose a different route that is.

This is a similar problem to the video icon in the callkit UI, callkit does not tell you when that button is pressed, and we haven't found a reliable way to detect it and stop enforcing our default. Changes would be necessary around here: https://github.com/jitsi/jitsi-meet/blob/f4d0ec1bb4ec71328536f9329c35060f781811d2/ios/sdk/src/AudioMode.m#L239

**Comment by PauMateu** [comment]
Thanks for the insight!

Indeed, we have seen this behavior, as we needed to start the call with earpiece and Jitsi was enforcing speaker even if we changed the audio-route from native functions. 
We solved this by commenting these lines.   
https://github.com/jitsi/jitsi-meet/blob/f4d0ec1bb4ec71328536f9329c35060f781811d2/ios/sdk/src/AudioMode.m#L265-L273

Now, jitsi does not override the AudioRoute, but the button is still not working...

**Comment by saghul** [comment]
Then I'm out of ideas, sorry.

**Comment by AlvaroBro** [comment]
> Thanks for the insight!
> 
> Indeed, we have seen this behavior, as we needed to start the call with earpiece and Jitsi was enforcing speaker even if we changed the audio-route from native functions.
> We solved this by commenting these lines.
> https://github.com/jitsi/jitsi-meet/blob/f4d0ec1bb4ec71328536f9329c35060f781811d2/ios/sdk/src/AudioMode.m#L265-L273
> 
> Now, jitsi does not override the AudioRoute, but the button is still not working...

Hi @PauMateu !

Did you manage to get the button working? By commenting the lines you pointed out now I can start in earpiece mode, and the speaker button turns correctly changes the route to speaker, but the button itself turns off (to not selected mode) after a few seconds, as if there was something changing its state, which I don't understand!!
Any insight??

Thanks!!

**Comment by Pakile** [comment]
@AlvaroBro Thank you very much for your reply. I have a microphone button but it's not working can you tell me how you handle it

**Comment by AlvaroBro** [comment]
Hi @Pakile 
You mean that the mute/unmute button is not working. For me it is working OK out of the box I think. The only code regarding this is an empty method in my AppDelegate:

```
- (void)performSetMutedCallWithUUID:(NSUUID * _Nonnull)UUID isMuted:(BOOL)isMuted {
    DLogDetail(@"JMCallKitProxy");
}
```

@saghul, @Pakile  , I've noticed a side effect of the `AVAudioSessionModeDefault` change above: there is echo, you hear your own voice when speaking during a conference, so I've reverted this change. Now my speaker button is behaving spookily again :(

Here are some links regarding this issue:

https://stackoverflow.com/questions/49170274/callkit-loudspeaker-bug-how-whatsapp-fixed-it
https://stackoverflow.com/questions/48023629/abnormal-behavior-of-speaker-button-on-system-provided-call-screen?rq=1
https://developer.apple.com/forums/thread/96243
https://github.com/jitsi/jitsi-meet/issues/8599

Regards

**Comment by AlvaroBro** [comment]
BTW, Telegram has the same problem. They use WebRTC.

**Comment by andreipro1002** [comment]
Hello,

@saghul Still no solution for this yet?

@PauMateu Commenting those lines didn't fix the problem for me, the output is still enforced on speaker. What version of sdk were you using?

**Comment by Vantam1601** [comment]
Any Solutions?
