### ISSUE TITLE
[Android] Viewing shared screen does not work (3+ users) if Simulcast is disabled and preferH264 is set

### ISSUE THREAD

**Issue by sschueller** [jitsi/jitsi-meet#8601]
### Description:

If more than 2 users as in a conference and the server has ```preferH264: true``` and ```disableSimulcast: true```. Viewing a shared screen does not work in the Android app. Opening the conference in Brave/Chrome does however work.

### Steps to reproduce:

1. On Server side configure ```preferH264: true``` and ```disableSimulcast: true```
2. Connect more than 2 people into the conference and have a PC user share their screen
3. Android App user gets black screen.

### Expected behavior:

Android user can see shared screens from others.

### Actual behavior:

Black screen

### Server information:

- Jitsi Meet version: 2.0.5390-3 (debian package)
- Operating System: Debian 10.8 - Linux 4.19.0-14-cloud-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

### Client information:

- Browser / app version: 20.6.2 build 6433631
- Operating System: Android 10 (Asus ZenFone Pro), same issue also on Android 9 (Samsung Galaxy S8+)

**Comment by Vamsi-Rayapati** [comment]
> 

Is it resolved ,I am also facing same issue

**Comment by Vamsi-Rayapati** [comment]
> ### Description:
> If more than 2 users as in a conference and the server has `preferH264: true` and `disableSimulcast: true`. Viewing a shared screen does not work in the Android app. Opening the conference in Brave/Chrome does however work.
> 
> ### Steps to reproduce:
> 1. On Server side configure `preferH264: true` and `disableSimulcast: true`
> 2. Connect more than 2 people into the conference and have a PC user share their screen
> 3. Android App user gets black screen.
> 
> ### Expected behavior:
> Android user can see shared screens from others.
> 
> ### Actual behavior:
> Black screen
> 
> ### Server information:
> * Jitsi Meet version: 2.0.5390-3 (debian package)
> * Operating System: Debian 10.8 - Linux 4.19.0-14-cloud-amd64 [Dead rooms #1](https://github.com/jitsi/jitsi-meet/issues/1) SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
> 
> ### Client information:
> * Browser / app version: 20.6.2 build 6433631
> * Operating System: Android 10 (Asus ZenFone Pro), same issue also on Android 9 (Samsung Galaxy S8+)

Is it resolved ,? .. facing same issue
