### ISSUE TITLE
Receiving video quality in chromium much lower than firefox (esp with >2 participants)

### ISSUE THREAD

**Issue by setpill** [jitsi/jitsi-meet#8605]
As title, when testing out some issues with quality I noticed that the incoming video quality is much worse in chromium than it is in firefox. Self-hosted server, using latest debian package; `2.0.5390-3`. Default settings, aside from the ones listed below:

```js
{
  anonymousdomain: 'guest.meet.example.com', // obviously not using example.com
  testing.capScreenshareBitrate: 0,
  requireDisplayName: true,
  prejoinPageEnabled: true,
  gatherStats: false,
  disableThirdPartyRequests: true,
  stunServers: [
    { urls: 'stun:meet.example.com:3478' }, // again, not using example.com
  ]
}
```

**Comment by damencho** [comment]
Attach your console logs, please.

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by setpill** [comment]
Interesting, I seem to have skipped the issue template thing... It was just not there. I wonder what path I took to file this issue.
