### ISSUE TITLE
[MacOS]Copy Meeting-Link to Clipboard wont work

### ISSUE THREAD

**Issue by Ockenheimer** [jitsi/jitsi-meet#8606]
### Description:
While hosting a session, your not able to copy the invite-link to the clipboard
### Steps to reproduce:

1. Open a Jitsi-meeting
2. Click on "Invite more people"
3. Click on "Copy meeting link"
4. Paste link into random place

### Expected behavior:
Pasting the invite link to the meeting

### Actual behavior:

The clipboard still has the previous content.

### Server information:

- Jitsi Meet version: 
- Operating System: 
- official meet.jit.si

### Client information:

- Browser / app version: 2.4.2
- Operating System: MacOS 11.2.1

### Additional information:

Jitsi was installed via homebrew

**Comment by JeffK969** [comment]
Same issue on Feb. 21, 2021.  Only difference was clip board was empty, when I tried to paste into email, blank.
Linux Mint MATE, 20.1.  Dell Laptop.

**Comment by saghul** [comment]
This was fixed in master and will be part of the next release. Thanks for the report!

**Comment by Ockenheimer** [comment]
Version installed and tested.

Issue solved
Thanks for fixing!
