### ISSUE TITLE
Moderator should be able to stop YT videos started by other users

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#8613]
**Is your feature request related to a problem you are facing?**
We face "yt bombing", i.e. users start to play YT videos with inappropriate content (distance schooling).

**Describe the solution you'd like**
Moderators should be able to stop YT videos started by other users.

**Describe alternatives you've considered**
Currently the only alternative is to ask all participants to leave the room and open a new room.

**Comment by tseeling** [comment]
Any chance this will be reviewed and implemented? Imho it's a serious issue, especially in education environments.

**Comment by saghul** [comment]
We have no plans to implement this.
