### ISSUE TITLE
jitsi-meet-web-config creates no nginx config / ssl key if jvb-hostname is preseeded

### ISSUE THREAD

**Issue by merlin1991** [jitsi/jitsi-meet#8618]
### Description:

For an automated installation I've preseeded the debconf database with all questions that are asked on a simple nginx install (jitsi-meet/cert-choice and variations of jvb-hostname)

The installation worked without an error, but no nginx config and no ssl certificate was generated

### Steps to reproduce:

1. follow the steps in the Self-Hosting Guide up to (not including) the [Install Jitsi Meet](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#install-jitsi-meet-1) section
2. preseed the debconf database with the wanted setting
```bash
debconf-set-selections << EOF 
jitsi-meet-web-config   jitsi-meet/cert-choice  select  Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)
jitsi-meet-prosody      jitsi-videobridge/jvb-hostname  string  meet.example.org
jitsi-meet-turnserver   jitsi-videobridge/jvb-hostname  string  meet.example.org
jitsi-meet-web-config   jitsi-videobridge/jvb-hostname  string  meet.example.org
jitsi-videobridge2      jitsi-videobridge/jvb-hostname  string  meet.example.org
jitsi-meet-turnserver   jitsi-meet-turnserver/jvb-hostname      string  meet.example.org
jitsi-meet-prosody      jitsi-meet-prosody/jvb-hostname string  meet.example.org"
EOF
```
3. run ```DEBIAN_FRONTEND=noninteractive apt install jitsi-meet```

### Expected behavior:

Installations happens as if I answered the questions during the installation

### Actual behavior:

Installations happens, but fails to create nginx config aswell as ssl certificate

### Server information:

- Jitsi Meet version: 2.0.5390-3 / 1.0.4628-1
- Operating System: Debian 10.8

### Additional information:

I think this is caused by the way jitsi-meet-web-config.postinst checks for a new / changed installation, because "JVB_HOSTNAME_OLD" is non-empty the nginx aswell as the openssl block are skipped

**Comment by damencho** [comment]
Please use the community forum when having problems or questions before opening new issues, thank you.

I had been using this for quick tests on VMs:

```
  - echo "jitsi-videobridge jitsi-videobridge/jvb-hostname string meet.example.com" | debconf-set-selections
  - echo "jitsi-meet-web-config jitsi-meet/cert-choice select 'Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)'" | debconf-set-selections
  - apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install jitsi-meet
```
That is all you need.

**Comment by saghul** [comment]
> Please use the community forum when having problems or questions before opening new issues, thank you.
> 
> 
> 
> I had been using this for quick tests on VMs:
> 
> 
> 
> ```
> 
>   - echo "jitsi-videobridge jitsi-videobridge/jvb-hostname string meet.example.com" | debconf-set-selections
> 
>   - echo "jitsi-meet-web-config jitsi-meet/cert-choice select 'Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)'" | debconf-set-selections
> 
>   - apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install jitsi-meet
> 
> ```
> 
> That is all you need. 

Does it make sense to put this in the handbook perhaps?

**Comment by damencho** [comment]
Yep. I've been using this with DO to test packaging so it works :)

**Comment by merlin1991** [comment]
sorry for the noise, but I looked into it some more and setting  
jitsi-meet-web-config jitsi-meet/cert-choice
jitsi-videobridge jitsi-videobridge/jvb-hostname

works, but if jitsi-meet-web-config   jitsi-videobridge/jvb-hostname is set too, then it fails. So I'm all in favour of documenting the required questions for an unattended installation.
