### ISSUE TITLE
External local storage leads to URLs growing indefinitely in length in browsers with third-party cookie blocking enabled

### ISSUE THREAD

**Issue by znerol** [jitsi/jitsi-meet#8621]
### Description:

Commit dc6d3daef73b2eda6121feb2728e0796f65aa545 introduced support for jitsi local storage for calls initiated via the external API. The content of jitsi local storage is passed from the external application to jitsi via `appData.localStorageContent` parameter. Whenever jitsi local storage changes, the new state is passed to the external application via `local-storage-changed` event and is saved subsequently in local storage of the external application.

Regrettably local storage seems to be used by jitsi in a way which does not restrict it in size. Also it appears that a history of recent jitsi calls is kept in local storag. This can lead to situations where the URL parameter `appData.localStorageContent` grows to a size which will make external API calls very slow and even break it completely when hitting webserver limits.

Note that this mechanism seems to kick in whenever jitsi detects that it cannot use *its own* local storage, i.e. if a browser blocks third-party cookies (and local storage).

### Steps to reproduce:

1. Use a modern browser with third-party cookie blocking enabled by default and open a new private window (in order to start from a blank slate).
2. Find an application which uses a recent jitsi deployment via external API
3. Open the browser console and inspect the URL used to open the jitsi instance
4. Repeatedly join and leave a conference and observe the URL grow in length each time.

### Expected behavior:

Data sent via `appData.localStorageContent` parameter should be limited in size.

### Actual behavior:

Data sent via `appData.localStorageContent` grows indefinitely with every new jitsi call.

### Server information:

- Jitsi Meet version: any since dc6d3daef73b2eda6121feb2728e0796f65aa545
- Operating System: any

### Client information:

- Browser / app version: any
- Operating System: any

**Comment by sahil-nagpal1** [comment]
yes, this is an issue. We are facing this issue in our site. We are unable to resolve it. Url grows indefinitely and the person is unable to join that jitsi session
