### ISSUE TITLE
Toolbox remains always visible even if you have set a timeout

### ISSUE THREAD

**Issue by AyushmanChatterjee** [jitsi/jitsi-meet#8623]
### Description:

Hi Team, 

This bug is related to the toolbox that has all the icons such as chat, screen sharing, end call, security buttons in it. If a timeout has been set for this to disappear, it should disappear when we leave the mouse pointer idle outside of toolbox area for a few seconds. And it works fine until the following is done.

### Steps to reproduce:

1. Can be tested with single participant.
2. Click on "Invite People" or "Security Options" button on the toolbox.
3. Let the toolbox hide automatically (as per the timeout) in the background while the dialog box is still open.
4. Now, close the dialog box through the close button or by clicking outside the box.

### Expected behavior:

Dialog box should close and toolbox should disappear if mouse is kept idle respecting the timeout value.

### Actual behavior:

The screens jumps a bit and toolbox remains visible throughout the meeting until page is refreshed.

### Server information:

- Jitsi Meet version: Can be reproduced on meet.jit.si and alpha.jitsi.net
- Operating System:

### Client information:

- Browser / app version: Tested with Chrome and Firefox.
- Operating System: Windows 10

### Additional information:

Toolbox timeout is usually set to 2-3 seconds and a person takes longer than that to set a meeting password. So, this bug is faced by anyone who sets a meeting password or takes a while to copy the invite link.

**Comment by damencho** [comment]
The toolbar changed I no longer reproduce this.
