### ISSUE TITLE
can't compile for iOS anymore: There is no XCFramework found at '/jitsi-meet/node_modules/react-native-webrtc/apple/WebRTC.xcframework'.

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#8624]
I've read a bunch of issues here regarding this "new" behavior and unfortunately none of the solutions seem to work.

In fact there are so many tickets regarding this issue with different information that it makes it very hard to understand what exactly the solution is.

I have Catalina with Xcode 12.4, npm 7.5.4 and pod 1.10.0

I clone master like I've done over the years.
I run npm install and then pod install in ios directory.

I try compiling and it fails with the missing XCFramework message in the title.

Ok, so I then cd into ios/scripts directory and run the release-sdk.sh script as instructed by @saghul in an earlier ticket and it complains about the missing jitsi-meet-ios-sdk-releases: No such file or directory
So I then create the directory myself and run the script again.
This time it complains about "cat: JitsiMeetSDK.podspec.tpl: No such file or directory" but it starts compiling until it fails completely.

I do see these errors which is likely why it's failing to compile the sdk
jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule.m:16:9: fatal error: 
      'WebRTC/RTCDefaultVideoDecoderFactory.h' file not found
#import <WebRTC/RTCDefaultVideoDecoderFactory.h>
jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+VideoTrackAdapter.m:11:9: fatal error: 
      'WebRTC/RTCVideoRenderer.h' file not found
#import <WebRTC/RTCVideoRenderer.h>
itsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:15:9: fatal error: 
      'WebRTC/RTCConfiguration.h' file not found
#import <WebRTC/RTCConfiguration.h>

jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m:10:9: fatal error: 
      'WebRTC/RTCCameraVideoCapturer.h' file not found
#import <WebRTC/RTCCameraVideoCapturer.h>
jitsi-meet/node_modules/react-native-webrtc/ios/RCTWebRTC/VideoCaptureController.h:3:9: fatal error: 
      'WebRTC/RTCCameraVideoCapturer.h' file not found
#import <WebRTC/RTCCameraVideoCapturer.h>

and it ends with ** ARCHIVE FAILED **

I'm about to pull my hair out of frustration. I have built the iOS app numerous times over the years but this time it is proving to be a nightmare. Reading through the handbook I don't see any instructions about what has changed and the need (or not?) to run the release-sdk.sh script.

Can someone help please with clear instructions?

Thanks

**Comment by pdarcos** [comment]
Update: The release-sdk.sh  script didn't work for me so I ended up doing a fresh git clone of master and instead used the script in the Build it yourself section from here https://github.com/jitsi/handbook/blob/master/docs/dev-guide/ios-sdk.md

Now the sdk compiles and I was able to build in Xcode for the simulator.

All should be fine right? Unfortunately no for when I try to archive in Xcode I get the dreaded bitcode error:

d: '/Users/user/Library/Developer/Xcode/DerivedData/jitsi-meet-bxshybjinesxlrbnbgsqlcjbfbcc/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/user/Library/Developer/Xcode/DerivedData/jitsi-meet-bxshybjinesxlrbnbgsqlcjbfbcc/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC/WebRTC.framework/WebRTC' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I went back and made sure that ENABLE_BITCODE for the project and the app is set to No for both debug and release, yet archiving the app still fails with the bitcode error.

Don't know what else to do to be able to compile. What used to take me 1 hour has now taken up my whole day and still not able to compile.

Any ideas?

**Comment by pdarcos** [comment]
Update 2

It seems I forgot to also disable bitcode in one of the targets and that's why it wasn't compiling.
Fixed now

**Comment by mfts** [comment]
Hey @pdarcos did you try to upload it to App Store Connect? I receive an Invalid Binary error from Apple the moment it's uploaded. 

---
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK: addStream:, channelId, initWithURLStrings:, isBinary, isPassthrough, onSuccess:, removeValuesForKeys:completion:, sdp, sendData:, setCategoryID:, setChannelId:, setColor:animated:, setConfiguration:error:, streamId, stringForType:, typeForString:, vibrate:, videoSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by saghul** [comment]
This is a false positive. Just tell Apple.

**Comment by radonejr** [comment]
for me this happened only if i set release in build configuration only in simulator . so just go to product > scheme > edit scheme > build configuration and change release to debug
