### ISSUE TITLE
Concerns about sharing informations with Google for advertisement

### ISSUE THREAD

**Issue by Kreyren** [jitsi/jitsi-meet#8627]
Today i had a conversation on https://meet.jit.si where we talked about following topics (not all at the same time selected strategically) that then appeared as video suggestion on my youtube.
- Quinoa
- Ananas
- Chicken
- Citrus

From privacy policy:
> 8×8 is not in the business of selling personal information to third parties. -- https://jitsi.org/meet-jit-si-privacy/

So i decided to report this here as it is seems to be reproducible every time suspecting that this might either be intentional thus requiring update of privacy policy or unwanted side effect of the hosting provider.

### Steps to reproduce
0. Get a microphone, second person to talk with and sign in your youtube account
1. Start a session on https://meet.jit.si
2. Browse your YouTube feed and then select a topic that is not available in the feed such as `Quinoa`.
3. Talk about the topic and have a discussion in the chat about it
4. Wait +- 5 min and then scroll through your youtube feed for occurance of the topic to confirm that the information from jitsi is being relayed to Google.

FWIW i wasn't able to reproduce this behavior on other jitsi instances.

**Comment by saghul** [comment]
We don't share any data with Google, let alone audio / video or chat data.

**Comment by Kreyren** [comment]
@saghul So you don't think it being possible that Google somehow would be able to gain access to this data?

**Comment by saghul** [comment]
I don't think so, we share no data with Google so I don't see how we could have sent it to them.

**Comment by Kreyren** [comment]
> I don't think so, we share no data with Google so I don't see how we could have sent it to them. -- @saghul (https://github.com/jitsi/jitsi-meet/issues/8627#issuecomment-810783938)

Most likely through amplitude, see detailed explanation in https://github.com/jitsi/jitsi-meet/issues/10501

I wasn't able to reproduce the highlighted issue with amplitude.com blocked, with it unblocked it seems to be reproducible around 4/10 times.
