### ISSUE TITLE
Microphone issues on Mac OS 10.14, Chrome with Bluetooth headphones

### ISSUE THREAD

**Issue by rin** [jitsi/jitsi-meet#8633]
### Description:

Microphone issues on Mac OS 10.14, Chrome with Bluetooth headphones on https://meet.jit.si/

First of all, sorry for opening such a vague issue. I'm happy to do more digging/debugging if someone has hints on what to try – which is primarily why I am creating this issue. 

I have several video calls a week on several different platforms without a problem, but every two weeks in my regular Jitsi call (current Chrome on Mac OS 10.14, using https://meet.jit.si/), people either cannot hear me at all or barely understand me. 

Things I checked:
- I've made a recording of just myself alone in a room and the microphones seemed to work fine.
- I've contacted Apple Support and there seems to be no known issue with my headphones/their firmware

Things I noticed:
- Although my environment is pretty quiet, I've seen the "Trying to speak?" hint pop up a few times during these calls.

### Steps to reproduce:

1. Join a meeting with about 6 participants.
2. Discuss for half an hour :)
3. Start wondering why everyone interrupts you / talks over you.
4. Realize that people cannot hear you.
5. :( 

### Expected behavior:

I would love to be able to use my bluetooth headphones with https://meet.jit.si/ without any issues! 

### Actual behavior:

- People can either not hear me at all or I get cut off/become inaudible

### Server information:

- Jitsi Meet version:  https://meet.jit.si/
- Operating System: 

### Client information:

- Browser / app version: current Chrome 88
- Operating System: MacOS 10.14.6 
- Bluetooth device: Apple Airpod Pros, firmware 3​A​283

**Comment by saghul** [comment]
Can you test your device in this page? https://test.webrtc.org

**Comment by rin** [comment]
@saghul I get a beautiful green checkmark
```
[ OK ] Audio track created using device=Rin’s AirPods Pro (Bluetooth)
[ INFO ] Channel 0 levels: -16.2 dB (peak), -23.9 dB (RMS)
[ INFO ] Channel 1 levels: -16.2 dB (peak), -23.9 dB (RMS)
[ OK ] Active audio input channels: 2
[ INFO ] Stereo microphone detected.
```
