### ISSUE TITLE
Task :sdk:mergeReleaseResources FAILED | Error while generating. Android SDK

### ISSUE THREAD

**Issue by gouravrc** [jitsi/jitsi-meet#8634]
### Description:

Getting below error while generating SDK at 98%

***Actual error***
> Task :sdk:mergeReleaseResources FAILED
>FAILURE: Build failed with an exception.

>* Where:
>Build file '/xxx/xxx/xxx/xxx/jitsi-meet-repo/android/sdk/build.gradle' line: 178

>* What went wrong:
>Execution failed for task ':sdk:mergeReleaseResources'.
> No signature of method: java.io.File.get() is applicable for argument types: () values: []
  Possible solutions: grep(), grep(java.lang.Object), getAt(java.lang.String), wait(), list(), any()

After I changed from  ( android > sdk > build.gradle )
```
        if (currentBundleTask.enabled) {
            copy {
                from(resourcesDir)
                 >> into(mergeResourcesTask.outputDir.get())
            }
        }

```
to

```
        if (currentBundleTask.enabled) {
            copy {
                from(resourcesDir)
                >> into(mergeResourcesTask.outputDir.grep())
            }
        }
```
as per the Possible solution. I am getting below error.

> Task :sdk:mergeReleaseResources FAILED
FAILURE: Build failed with an exception.
> * Where:
> Build file '/xxx/xxx/xxx/xxx/jitsi-meet-repo/android/sdk/build.gradle' line: 178
> 
> * What went wrong:
> Execution failed for task ':sdk:mergeReleaseResources'.
> java.io.FileNotFoundException: /xxx/xxx/xxx/xxx/ jitsi-meet-repo/android/sdk/build/intermediates/res/merged/release (Is a directory)

### Steps to reproduce:

1. open terminal in root folder 
2. run `./android/scripts/release-sdk.sh /tmp/repo` 

### Maven information:

Apache Maven 3.6.3 (xxxxxxxxxxxxxxxxxxxxxxxxxx8f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 15.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

### Environment information:

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 84.02 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9 => 16.9.0 
    react-native: github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551 => 0.61.5-jitsi.2 
  npmGlobalPackages:

### Additional information:

[https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#build-and-use-your-own-sdk-artifactsbinaries](url)

**Comment by saghul** [comment]
I suspect the bundling didn't quite work. We generally use Node 12 and npm 6. Any chance you can test with those?

**Comment by gouravrc** [comment]
@saghul I need to downgrade the versions. Will check and let you know. Thanks.

**Comment by gouravrc** [comment]
@saghul 
got some new error

```
Task :sdk:mergeReleaseResources FAILED
FAILURE: Build failed with an exception.
* Where:
Build file '/xxx/xxx/xxx/xxx/jitsi-meet-repo/android/sdk/build.gradle' line: 176  <<-- previously it was 178

* What went wrong:
Execution failed for task ':sdk:mergeReleaseResources'.
Cannot convert the provided notation to a File or URI: [Ljava.lang.String;@7f6281e9.
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
    - A File instance.
    - A Path instance.
    - A Directory instance.
    - A RegularFile instance.
    - A URI or URL instance.
    - A TextResource instance.
```

**Comment by saghul** [comment]
Did you make any changes to the project?

**Comment by gouravrc** [comment]
@saghul I have done customization at the project level. Didn't touch the Gradle files. Can you specify the exact version of node and npm?

**Comment by saghul** [comment]
> Can you specify the exact version of node and npm?

We don't use exact versions, just Node 12 and npm 6.

Does building the vanilla project (a fresh clone from master) not work for you?

**Comment by gouravrc** [comment]
@saghul 
Downloaded a fresh clone

```
Task :sdk:bundleReleaseJsAndAssets FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
Process 'command 'node'' finished with non-zero exit value 1
```
Do you it is an environmental issue with my system?

**Comment by saghul** [comment]
Looks like it, yes. The bundling process which uses Node is failing.

**Comment by gouravrc** [comment]
I will inspect this in a different environment.

**Comment by gouravrc** [comment]
@saghul  
It is successfully built up in the Big Sur OS environment. Looks like Mojave not supporting several packages.
If possible please add an alert in Readme or in the documentation about this. It will be helpful. I am closing off this issue.

**Comment by saghul** [comment]
I don't have Mojave around to verify this. I'm on Catalina myself.
