### ISSUE TITLE
dyld: Library not loaded: @rpath/JitsiMeetSDK.framework/JitsiMeetSDK - image not found

### ISSUE THREAD

**Issue by idrive-pankaj** [jitsi/jitsi-meet#8636]
### Description:

First of all, Thank you so much for creating this very good framework and providing continues support.
We are using jitsimeet SDK in our native ios project and till now everything was working fine until I took a pull and created new xcframework instead of a normal framework.

When I add new xcframewok in my native code, it's working fine in the simulator but when I run the app on the actual device then it's not working and I am getting above error.

### Steps to reproduce:

1. Take latest jitsi code from the master repo
2. add some UI changes
3. create new SDK using this script. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#building-it-yourself
4. removed older framework and added a new one, confirmed that it's there in the Framework, Link and embed binary section of Target -> general. also, it's there in the Link Binaries section of the build phase.
5. Run the app in the simulator, working fine
6. Run in the device and it will throw below error.

`dyld: Library not loaded: @rpath/JitsiMeetSDK.framework/JitsiMeetSDK
  Referenced from: /private/var/containers/Bundle/Application/2CCA0CDB-9D18-49F5-B150-6B3A06627465/Epyc Meeting.app/Epyc Meeting
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
`

![Screenshot 2021-02-17 at 8 38 38 PM](https://user-images.githubusercontent.com/79213346/108229068-76945400-7165-11eb-85ee-3dce23c19a07.png)
![Screenshot 2021-02-17 at 8 38 56 PM](https://user-images.githubusercontent.com/79213346/108229087-7bf19e80-7165-11eb-839a-2049da5a52d3.png)

### Expected behavior:

It should install the app on the actual device and run properly.

### Actual behavior:

Not working in the real device and getting build issue.
![Screenshot 2021-02-17 at 9 03 19 PM](https://user-images.githubusercontent.com/79213346/108229047-71370980-7165-11eb-94e4-a92feae06048.png)

### Server information:

- Jitsi Meet version: "lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#9fdde46694d1c4bc8b7f051cc8d50e0df29ffd07",
- Operating System: Mac OS BigSur
- Xcode version - tested in xcode 11.6, 12.4, 12.2

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

I tried all the issues and solutions which are available for a similar issue on the sample app but still not able to fix this issue. Even tried changing framework settings like embedded and sign or without sign and embedded but still not working.
Sample app issues are related to pod file and frameworks but here I am adding customised framework so I need your help.

Thanks

**Comment by saghul** [comment]
You need to mark both frameworks as "Embed and Sign".

**Comment by idrive-pankaj** [comment]
Hi Saghul, thanks for your reply.
I think I already tried it, let me check it again and update you.

**Comment by idrive-pankaj** [comment]
Hi @saghul thanks for your help, it's working now !!

**Comment by Vantam1601** [comment]
.... solutions ?

**Comment by idrive-pankaj** [comment]
@Vantam1601 You need to mark both frameworks as "Embed and Sign".

**Comment by SwpuEsine** [comment]
<img width="935" alt="截屏2024-09-22 下午5 51 31" src="https://github.com/user-attachments/assets/f702c244-0abf-47c9-85d6-8ec6b6ff71cc">

<img width="725" alt="截屏2024-09-22 下午5 53 13" src="https://github.com/user-attachments/assets/17797e47-82c5-47a9-a875-c3acceb00911">
