### ISSUE TITLE
Date time is not localized in some languages

### ISSUE THREAD

**Issue by cool0707** [jitsi/jitsi-meet#8640]
Some languages do not localize the date and time in the recent list etc.(eg. Japanese)

I think this is due to the fact that some languages are not required by dateUtil.js, even though they are supported by Moment and Jitsi Meet.

https://github.com/jitsi/jitsi-meet/blob/8fcaea9e3d66467843bce57fe3bfaa84b0f861c6/react/features/base/i18n/dateUtil.js#L10-L33

**Comment by seanm** [comment]
I was going to file a similar ticket, but I think it might be the same as this one.

I'm running jitsi meet in English, and the recent list shows dates as mm/dd/yyyy (or maybe it's dd/mm/yyyy, I'm honestly not sure!). As in this image:

![JitsiDateFormat](https://user-images.githubusercontent.com/117260/116110636-e18d6a00-a683-11eb-9068-4944fd61c1fc.png)

I'd like it to always be yyyy-mm-dd as per [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601), but as best as I can tell after much searching, there's no way currently.

**Comment by saghul** [comment]
The list has been expanded to all available languages supported by moment: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/dateUtil.js
