### ISSUE TITLE
Allow moderator to end meeting

### ISSUE THREAD

**Issue by vv9k** [jitsi/jitsi-meet#8641]
**Is your feature request related to a problem you are facing?**
I would like a moderator of a call to be able to end call for all users and kick them all out automatically.

**Describe the solution you'd like**
A button in the bottom toolbox, next to the `Leave Meeting` button that would say `End Meeting` and on press would kick all users and end the meeting freeing up the name for others to use.

**Describe alternatives you've considered**

**Comment by roccobarbi** [comment]
Since Jitsi Meet is widely used by schools to provide distance learning during covid lockdowns (at least in Italy), this feature would help teachers manage their classes and ensure that all students leave at the end of each one.

**Comment by DmDS** [comment]
you can use this prosody module. it disconnects clients after the moderator exits.
I assembled it from the other two.


<details><summary>about those modules here...</summary>

[the first one](https://community.jitsi.org/t/close-room-properly-prosody-custom-module/16066/45) disconnects clients after the moderator exits, but does not disconnect mobile clients, and web clients can reconnect to the conference without a moderator. and there are some problems with disconnecting clients, they are not completely disconnected ...


[the second one ](https://github.com/emrahcom/emrah-buster-templates/blob/master/machines/eb-jitsi/usr/share/jitsi-meet/prosody-plugins/mod_time_restricted.lua) allows you to limit the conference time. and there are no problems with disconnecting mobile clients and all clients are disconnected completely. </details> 



<details><summary>Instructions</summary>

1) Make a new script file "mod_dissconnect.lua" in the Prosody plugins folder (/usr/share/jitsi-meet/prosody-plugins/)

```
local LOGLEVEL = "debug"
local MIN = module:get_option_number("conference_timeout", 10)
local TIMEOUT = MIN
local is_admin = require "core.usermanager".is_admin
local is_healthcheck_room = module:require "util".is_healthcheck_room
local st = require "util.stanza"
local timer = require "util.timer"
local focus_jid = module:get_option_string("focus_user_jid", "focus@auth.ooff.gormost.mos.ru");
module:log(LOGLEVEL, "loaded")

local function _is_admin(jid)
    return is_admin(jid, module.host)
end

module:hook("muc-occupant-left", function (event)
    local room = event.room
    local mods = room:each_affiliation("owner");
    local leaver = event.occupant.bare_jid;


    if is_healthcheck_room(room.jid) then
        module:log(LOGLEVEL, "skip restriction")
        return
    end

    for mod in mods do
        module:log("debug", "owner found: %s", tostring(mod));
            if mod ~= leaver and mod ~= focus_jid then
            -- there is still a moderator in this room, dont kick participants
            module:log("info", "still a moderator present: %s", mod);
                return
        end
    end


    -- announce the expiration time
    room:broadcast_message(
         st.message({ type="groupchat", from=room.jid })
         :tag("body")
         :text("The conference will be terminated in "..MIN.." sec"))

    module:log(LOGLEVEL, "set timeout for conference, %s secs, %s",
                         TIMEOUT, room.jid)

    timer.add_task(TIMEOUT, function()
        if is_healthcheck_room(room.jid) then
            return
        end

        -- kick all participants
        for _, p in room:each_occupant() do
            if not _is_admin(p.jid) then
                room:set_affiliation(true, p.jid, "outcast")
                module:log(LOGLEVEL, "kick the occupant, %s", p.jid)
            end
        end

        module:log(LOGLEVEL, "the conference terminated")
    end)
end)

```

2) Enable module in your prosody config (/etc/prosody/conf.d/meet.mydomain.com.cfg.lua)

      search for:
      Component "conference.meet.mydomain.com" "muc"
      modules_enabled = {
        ...
        ...
        "disconnect";
        }
      conference_timeout = 10 // (timeout before disconnecting)

3) Restart the services

   systemctl restart prosody.service
   systemctl restart jicofo.service
</details>

**Comment by bsimml** [comment]
@DmDS  I tried your prosody module and it works like a charm. I added a check for mods before the actual kicking of users, in case the mod had connection issues. This also works fine, but when the mod reconnects i have 2 mods in the meeting and the 'ghostmod' wont ever be killed. Do you have any pointers on how to prevent this behavior? Any help would be appreciated.

**Comment by DmDS** [comment]
I have updated the module. 
works with ghostmods. 
but if there are several moderators in the room, the room will be closed if one of the moderators leaves!

<details><summary>updated module</summary>

```
local LOGLEVEL = "debug"
local MIN = module:get_option_number("conference_max_minutes", 10)
local TIMEOUT = MIN

local is_admin = require "core.usermanager".is_admin
local is_healthcheck_room = module:require "util".is_healthcheck_room
local st = require "util.stanza"
local timer = require "util.timer"
local focus_jid = module:get_option_string("focus_user_jid", "focus@auth.ooff.gormost.mos.ru");
module:log(LOGLEVEL, "loaded")

local function _is_admin(jid)
    return is_admin(jid, module.host)
end

module:hook("muc-occupant-left", function (event)
    local room = event.room
    local mods = room:each_affiliation("owner");
    local leaver = event.occupant.bare_jid;

    for mod in mods do
        if mod == leaver then

            if is_healthcheck_room(room.jid) then
                module:log(LOGLEVEL, "skip restriction")
                return
            end

            room:broadcast_message(
                 st.message({ type="groupchat", from=room.jid })
                 :tag("body")
                 :text("The conference will be terminated in "..MIN.." sec"))

            module:log(LOGLEVEL, "set timeout for conference, %s secs, %s",
                                 TIMEOUT, room.jid)

            timer.add_task(TIMEOUT, function()
                if is_healthcheck_room(room.jid) then
                    return
                end

                for _, p in room:each_occupant() do
                    room:set_affiliation(true, p.jid, "outcast")
                    module:log("info", "kick the occupant, %s", p.jid)
                    module:log("info", "the conference terminated")
                end
            end)
       end
    end
end)
```

**Comment by saghul** [comment]
Based on the time that has passed here, I don't think we'll ship this. That said, @DmDS you may want to contribute your plugin to https://github.com/jitsi-contrib/prosody-plugins

**Comment by DmDS** [comment]
https://community.jitsi.org/t/destroy-the-room-after-the-last-moderator-leaves-prosody-custom-module/103333

**Comment by saghul** [comment]
Thanks for sharing it with the community! I'd still suggest you PR it to the jitsi-contrib repo, that's the home for Jitsi related community projects. This way it will be easier to find / maintain it further. Up to you though!

**Comment by DmDS** [comment]
i'll try)

**Comment by Visualbench** [comment]
@DmDS Is it possible to achieve the same on a button click?

**Comment by wfleischer** [comment]
Should now be covered by https://github.com/jitsi/jitsi-meet/pull/10838.
