### ISSUE TITLE
Moderator status after broken connection

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#8646]
Starting point is a meeting with enabled lobby.
In this meeting are 5 participants (1 moderator and 4 guests).
If the connection of the moderator is broken and he reconnects, it is not possible for him to rejoin the meeting as moderator.

Therefore it would be nice, if the meeting detects the participant (maybe by a cookie) and let him in as moderator.

**Comment by saghul** [comment]
I assume you used a custom deployment. What authentication did you enable? How did you configure prosody?

**Comment by heikar** [comment]
That is correct.
I use a self hosted jitsi instance.

In prosody i use my "main virtual host" with `authentication = "internal_hashed"`.
In my "guest virtual host" i have a lobby activated (`modules_enabled = { "muc_lobby_rooms"; "turncredentials"; } lobby_muc = "lobby.domain"`).

If a password is set and the moderator rejoin the meeting with the password then it is a moderator again.
But if no password is set and only the lobby is used then the "rejoined" moderator still stucks in the lobby.

**Comment by saiprasad1996** [comment]
@heikar did you find any solution for this issue. 
I've implemented secure domain by making necessary changes in the prosody .lua file and the domain-config.js file, without the `modules_enabled = { "muc_lobby_rooms"; "turncredentials"; } lobby_muc = "lobby.domain"` block in the guest virtualhost section. The moderator is shown to be authenticated and logged in but moderator rights are not granted. One observation worth mentioning is when there are multiple moderators, the other moderator could pass on the moderator rights to other non-moderator participant.
This seems to be a major issue. @saghul please take a look into this, your help is much appreciated.

**Comment by heikar** [comment]
Hi @saiprasad1996 unfortunately i have no solution for this :(
The current workaround for lobby is that each meeting must be password protected, so you can use the lobby also with one moderator.
But i agree with you, that this is a important issue. Maybe in a future release it can be stored in a cookie or something similar.
