### ISSUE TITLE
IFrame API 'largeVideoChanged' Event not receiving object as stated in docs

### ISSUE THREAD

**Issue by LindezaGrey** [jitsi/jitsi-meet#8647]
### Description:

I want to handle the "largeVideoChanged" event, but it seems like the listener doesn't receive the described object, as mentioned in here:
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#largevideochanged

where it says:

> The listener receives an object with the following structure:

```
{
    id: string // id of the participant that is now on large video in the stage view.
}

```

### Steps to reproduce:

I add my event listener (note: several others are working this way):
```js
api.on("largeVideoChanged", e => {
            console.log(e);
        });
```
Whenever the large video changes, the event fires, but e is undefined.

### Additional information:

When i look at the jitsi code, it seems like no additional object is emitted when this event fires:

https://github.com/jitsi/jitsi-meet/blob/1a789130a3b0d3ab99628405c13792ea58bda09e/modules/API/external/external_api.js#L521

Am i missing something, or is the documentation misleading?

**Comment by karlowich** [comment]
I'm having this problem as well. It seems that the 'largeVideoChanged' event is unfinished.

**Comment by techiespace** [comment]
@damencho can e open this or should I create a new issue?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet-torture/blob/b2096d615fb801db1131c1ee4c89f283451b22a2/src/test/java/org/jitsi/meet/test/IFrameAPITest.java#L46

**Comment by tyhayeswbs** [comment]
This is still broken nearly 4 years later
