### ISSUE TITLE
I cannot find the page to setup loadbalanced JVBs? 

### ISSUE THREAD

**Issue by artknight** [jitsi/jitsi-meet#8650]
There used to be a page `jitsi meet load balancing installation Ubuntu 18.04 with MUC and JID` that had a tutorial on how to setup loadbalanced JVBs. Now it seems to be missing. Can anyone point me to the page please?

**Comment by saghul** [comment]
That is no longer necessary since it's configured that way out of the box.

**Comment by artknight** [comment]
@saghul would elaborate please on how it works now. 

Let's assume I have installed jitsi on a single server that is my gateway and I have another server that I want to act as a load-balanced JVB. Do I only install the JVB on that server and how does it know about the gateway JVB? Is there any configuration that needs to be done? 

If there is a document on this please point me to that.

Thank you!

**Comment by artknight** [comment]
@saghul please reply to my previous comment!

**Comment by saghul** [comment]
You can check this: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-scalable

**Comment by artknight** [comment]
@saghul so according to the guide all servers get the full package installed ( jitsi-meet, prosody, jifoco ). Previously, It used to be that the additional video bridges just need the prosody install, not the other two. 

Can you confirm that?
