### ISSUE TITLE
[JitsiMeetSDK] IOS - Xcode 12.4 - compiler version problem

### ISSUE THREAD

**Issue by gigallo** [jitsi/jitsi-meet#8656]
Hi guys

I'm using Xcode 12.4 with Swift 5.3.2 and when I try to import JistiMeetSdk module the compiler raises an error:

`Failed to build module 'JitsiMeetSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'`

In the Pod spec file I've specified:

```
Pod::Spec.new do |s|
    s.name = 'MyAppJitsi'
    s.version = '0.0.1'
    s.summary = 'Join or start Jitsi conferences'
    s.license = 'EUPL-1.1'
    s.homepage = 'www.tr-ec.eu'
    s.author = 'GMG - GmgHealth'
    s.source = { :git => 'www.gitlab.com', :tag => s.version.to_s }
    s.source_files = 'ios/Plugin/**/*.{swift,h,m,c,cc,mm,cpp}'
s.resource_bundles = {
        'Plugin' => [
        'ios/Plugin/*.storyboard'
        ]
    }
    s.ios.deployment_target  = '11.0'
    s.dependency 'Capacitor'
    s.dependency 'JitsiMeetSDK', '3.1.0'
  end
```

The compiler raises the same error also if I don't specify the sdk version.

Any idea on how to solve this problem? It's becoming quite impossible to run behind all Xcode/swift releases

Thanks in advance

**Comment by saghul** [comment]
The SDK is now released compiled with Xcode 12.4.
