### ISSUE TITLE
Feature Request: channelLastN auto-adjustment

### ISSUE THREAD

**Issue by scroom** [jitsi/jitsi-meet#8659]
**Is your feature request related to a problem you are facing?**
We have noticed that our Jitsi servers, especially when many users are in many conferences, generate a (sometimes too) high system load for us. To reduce the load, we have therefore lowered the value for channelLastN. However, the resources are idle outside of peak hours and we could well allow more video streams again.

**Describe the solution you'd like**
It would therefore be welcome if the value could be adjusted automatically, depending on the load, to always offer users the best possible result.

**Comment by damencho** [comment]
That is already available: 
https://github.com/jitsi/jitsi-meet/blob/f69a31d9c6109c6604de4f445d2e6412b63ccb62/config.js#L235
