### ISSUE TITLE
Incorrect starting screen on Chromebook Android app

### ISSUE THREAD

**Issue by andyg1001** [jitsi/jitsi-meet#8661]
### Description:

From time to time the jitsi-meet app shows the wrong screen when the app starts up and doesn't permit starting a meeting from another server other than the official server.  A screenshot of the app window is attached below.

### Steps to reproduce:

1. Install the jitsi-meet app from the Google Play store on a Chromebook (not necessary if already installed!)
2. Open it

### Expected behavior:

I expect to see the "normal" jitsi-meet app screen which traditionally shows, for example, the list of previously accessed rooms and a burger menu allowing access to settings including setting a custom server address.

### Actual behavior:

The wrong screen appears when the app is started, see screenshot for an example:

![Screenshot 2021-02-19 at 19 31 24](https://user-images.githubusercontent.com/21264510/108547808-41b20980-72eb-11eb-8e0d-7ae035fbf31c.png)

From this screen it is not possible to connect to a custom jitsi server, nor access previously used rooms.

I have never seen this happen on a true android tablet or phone, but periodically happens on the Chromebook.

### Client information:

- Browser / app version: According to Google Play, version 1.0.0, last updated 3 Feb 2021
- Operating System: Chrome OS Version 88.0.4324.109 (Official Build) (32-bit)

I note that on my tablet, the app version is 20.6.2 build 6433631 so there is something odd going on here, but uninstalling and reinstalling the app on the Chromebook does not solve this issue.

**Comment by saghul** [comment]
This is intentional. What you see is a TWA, a Trusted Web App, specific to ChromeOS devices. Our Android APK is not (and probably never will be) optimized for such devices so we launched the TWA.

You can still sideload the regular APK if you like though.

**Comment by andyg1001** [comment]
Ok, I understand but this means that I need to change my Chromebook into "Developer Mode" to enable loading of the apk download from F-Droid (or for that matter to install F-Droid as far as I can work out).  Therefore the TWA option effectively prevents jitsi-meet from working on Chromebook.

Would it be possible, therefore, please, to either support alternative jitsi servers in your TWA version (I expect this goes against the idea of a TWA though) or make it possible to use the standard app even if not "optimised" (since it has been working all this time in any case).

**Comment by saghul** [comment]
It's not possible to support the TWA alongside the "normal" APK.

**Comment by saghul** [comment]
Why would you want to use the Android app (which is not really working well) in a Chromebook rather than using the browser directly?
