### ISSUE TITLE
Changing all.css does nothing...

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#8663]
### Description:

Editing the /usr/share/jitsi-meet/css/all.css file fails to reflect the changes on the frontend.

### Steps to reproduce:

1. Open /usr/share/jitsi-meet/css/all.css
2. Edit anything related to the watermark specifically, because that's what I did.
3. Save the file and no matter what you do (restart), et... the old values still reflect on the frontend.

### Expected behavior:

I expect that editing the all.css file would change things on the client/frontend.

### Actual behavior:

Editing the all.css file doesn't do anything.

### Server information:

- Jitsi Meet version: Unstable version 4726
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Electron, chromium, firefox. Tried all.
- Operating System: Windows 10 64x

### Additional information:

n/a

**Comment by saghul** [comment]
Some things are controlled with JS. What did you change specifically?

**Comment by DillFrescott** [comment]
I changed the height and width of the left watermark from its default to 85x85 pixels. I did this because I replaced the logo with a different circular one.

**Comment by saghul** [comment]
@vp8x8 any idea?

**Comment by DillFrescott** [comment]
Its not really that huge of an issue for me. The icon is a decent size as is. Should I leave the issue open?
