### ISSUE TITLE
Screen sharing of presentation window (.pptx file) is broken.

### ISSUE THREAD

**Issue by migonr77** [jitsi/jitsi-meet#8666]
### Description:

Screen sharing of presentation window (.pptx file) is broken when selecting PowerPoint window as screen share source. Screen sharing starts, but keep displaying only first frame of presentation forever. 

### Steps to reproduce:
1. open pptx presentation with PowerPoint
2. select screen sharing source of PowerPoint window.
3. run presentation
4. presentation keeps displaying only first frame of presentation forever to all participants but presenter himself.

1. 
2. 
3. 

### Expected behavior:

Presentation should display all successive frames not only first one.

### Actual behavior:

presentation keeps displaying only first frame of presentation forever.

### Server information:

- Jitsi Meet version: actual stable self-installation and meet.jit.si installation too. 
- Operating System: Debian

### Client information:

- Browser / app version: Chrome, Chromium, Firefox
- Operating System: Windows, Linux

### Additional information:

When selecting whole screen as screen share source participant can see all frames in presentation (.pptx)  Problem only occurs when application window (PowerPoint) is selected as a source for screen sharing.

**Comment by damencho** [comment]
You need to file a bug in the issues page for the browser you use. Screensharing implementation is in the browser and there is nothing we can do about it.
As a workaround try sharing the whole screen, not just the window.

Please use the community forum before opening new issues. Thank you.

**Comment by migonr77** [comment]
Hi Damian, thank you for your reply. Can you tell me please what browser we need to use that works with app. window sharing? We've tested Chrome and Firefox and it doesn't work, but it worked with older Jitsi meet installation before January 12. version.

**Comment by damencho** [comment]
I don't understand what was working with previous versions? All jitsi-meet does is calling getDisplayMedia passing some params. All that had changed are the versions of the browsers, maybe try an older version of the browser.

**Comment by migonr77** [comment]
OK, thank you! Screen sharing of windows was working fine in the past.  I'll request users that reported to me this issue to try older Chrome versions. 
Thank you for your support and awesome jitsi meet!
