### ISSUE TITLE
Requesting for ionic cordova plugin with latest jitsi sdk

### ISSUE THREAD

**Issue by varaprasadreddy9676** [jitsi/jitsi-meet#8669]
**Is your feature request related to a problem you are facing?**
I have tried some different cordova plugins for my project some of them are working fine but have some issues like video quality and some meeting end, destroy, etc.. triggers are not working.

**Describe the solution you'd like**
I request any one here to create a cordova plugin with latest jitsi sdk with all features.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
We have no plans to maintain an "official" Cordova plugin, sorry.
