### ISSUE TITLE
Can't find variable : window

### ISSUE THREAD

**Issue by yasirrose** [jitsi/jitsi-meet#8674]
Hi, 

I want to use Jitsi with in one of my app. So I am running android app in MAC to try some customisation but I am getting an error in simulator when I run the app through react-native run-android. Here is the detail of error. 

Error: Can't find variable : window

Here is the detail screenshots: 

![screenshot-2021-02-23_16 39 21 421](https://user-images.githubusercontent.com/5586359/108838744-de2f2100-75f5-11eb-89c6-f1c96a59dbc0.png)

![screenshot-2021-02-23_16 40 11 052](https://user-images.githubusercontent.com/5586359/108838753-e12a1180-75f5-11eb-9144-aa4ce2f6a981.png)

Can any body help me to fix this issue?

**Comment by saghul** [comment]
What changes have you made? Are you able to run the app straight from master?

**Comment by yasirrose** [comment]
@saghul I didn't made any change. I just cloned the project. Then I have run npm install. After that react-native run-android.

**Comment by Yarkhan** [comment]
I'm also facing this issue (iOS) on Release and Debug builds, running from master.

On debug builds, setting the bundler ip on the phone doesn't work. I had to hardcode my machine IP address on RCTBridgeWrapper for it to load the code from the packager. It works just fine after that.

On release builds I get stuck on the initial screen and the following appears in the xcode debug console:

```
Unhandled JS Exception: Can't find variable : window
/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:714:59
v@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:20:2755
/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:20:3446
v@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:18:38
v@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:7:119
v@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:6:30
v@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
d@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:876
global code@/var/containers/Bundle/Application/8736C9A7-D0CB-4940-99C2-C7E9036AFEB6/jitsi-meet.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2279:4
```

**Comment by Yarkhan** [comment]
After removing node modules, pods, cleaning build and installing everything again it worked (after the many times). Xcode being Xcode?

**Comment by nguyenNCphpFox** [comment]
the some issue

**Comment by crfz123456hsq** [comment]
hey,I also encountered the same problem, how can I solve it？plz.

**Comment by Hin-D** [comment]
Do not delete the file package-lock.json and npm install can solve this error.
https://github.com/jitsi/jitsi-meet/issues/9412

**Comment by ibc** [comment]
@Hin-D, do not mention random people, please.

**Comment by cdcdianne** [comment]
Also having this issue, did anyone already solve this?

**Comment by cdcdianne** [comment]
is there any other solution, other than updating to the latest SDK?

**Comment by saghul** [comment]
I don't know, sorry. So much has changed...

**Comment by cdcdianne** [comment]
Do you think, one of the reason is the npm version? should I downgrade my npm version? I'm currently using npm version 8.1.0 now

**Comment by saghul** [comment]
We make our builds with npm 8 too.
