### ISSUE TITLE
Inappropriate Words in Meeting Name Strings

### ISSUE THREAD

**Issue by 3001io** [jitsi/jitsi-meet#8676]
My company was concerned about some of the strings created by the automated conference naming on our self-hosted instance.
Searching through app.bundle.min.js and app.bundle.min.map and there is a significant number of words that are age inappropriate, work inappropriate, and generally offensive (swear words, for example). There are also trigger words that potentially violate (for example) Debian Code of Conduct.
Is there a purpose for words like "assh*le", "f*ck", "rapist", or "abortion" in these files?
Would it be better if there was a json file for creating random strings? It would be much easier to edit.

Thanks!

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

There are no such words for the room name generation you can check it your self here: https://github.com/jitsi/js-utils/blob/master/random/roomNameGenerator.js

What you are seeing as text is the list of unsecured room names, which has nothing to do with room name generation. For those checks, we use a library by Dropbox called `zxcvbn`. https://www.npmjs.com/package/zxcvbn

You can check its source, I see in there `abortion` for example https://github.com/dropbox/zxcvbn/blob/master/dist/zxcvbn.js.

**Comment by 3001io** [comment]
Then why are those words in "/usr/share/jitsi-meets/libs/app.bundle.min.map" and "app.bundle.min.js"? I'm not making this up, I did a search on the code.

**Comment by damencho** [comment]
Cause we use that library and appbundle is all the code we use, even the dependencies.

**Comment by damencho** [comment]
app.bundle.min is a binary file, this is all the compiled java-script code in it.

**Comment by 3001io** [comment]
Why are these words in the compiled java-script code?
Here is an example random name we had generated for a meeting this morning: "PlayfulDwarfsJokeRapidly". I don't see "Dwarfs" in the roomNameGenerator.js script on github. I also don't see this script "roomNameGenerator.js" on my instance.

**Comment by damencho** [comment]
> Why are these words in the compiled java-script code?
Cause that library is used in the code to check for weak room names.


> Here is an example random name we had generated for a meeting this morning: "PlayfulDwarfsJokeRapidly". I don't see "Dwarfs" in the roomNameGenerator.js script on github. I also don't see this script "roomNameGenerator.js" on my instance.

What version of jitsi-meet do you use? That is strange ... you generate the room name from the welcome page, right?

**Comment by saghul** [comment]
"Dwarfs" got removed about a year ago: https://github.com/jitsi/js-utils/commit/d04ce7d6f81f80c6f98deeae3a1778e7af7e9d3e#diff-0997ea00d4c531af682d2f4b7e837b4b4be5ac1ae5c25fa9027f87f9e2bf7e46L17

**Comment by damencho** [comment]
Ah, I was trying to find whether we had that at some point ... thanks Saul.
So @3001io updating will solve your concerns

**Comment by 3001io** [comment]
I will have to check, but I believe I'm using the Debian Buster repository version.

**Comment by saghul** [comment]
Were you using the Electron app by any chance?
