### ISSUE TITLE
Please bump lodash from 4.17.19 to 4.17.21

### ISSUE THREAD

**Issue by beatquantum** [jitsi/jitsi-meet#8683]
### Description:
Lighthouse shows that lodash 4.17.19 is in use and contains high vulnerability. Also checked it on 
https://snyk.io/vuln/npm:lodash?lh=4.17.19&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

### Steps to reproduce:
1. Install the latest jitsi-meet as per standard installation
2. Control+Shift+I  
3. Run Lighthouse

### Expected behavior:
No such warnings and errors.
![lighthouse-lodash](https://user-images.githubusercontent.com/67234356/109155573-9e884680-7767-11eb-99c2-72ac7e280988.JPG)

**Comment by saghul** [comment]
Sure thing. Kinda weird that the GH security bot hasn't picked it up.
