### ISSUE TITLE
Unable to use react-native-community_cameraroll with jitsimeet

### ISSUE THREAD

**Issue by idrive-pankaj** [jitsi/jitsi-meet#8685]
### Description:

I am trying to integrate react-native-community_cameraroll to save images in the camera roll. I have installed the npm package and everything properly and linked it. it's working fine in the ios but when I link it manually in the android and create an SDK I am getting the below error all the time.

`Execution failed for task ':app:dataBindingMergeDependencyArtifactsEpycDebug'.
> Could not resolve all files for configuration ':app:epycDebugCompileClasspath'.
   > Could not find jitsi-meet:@react-native-community_cameraroll:unspecified.
     Required by:
         project :app > org.jitsi.react:jitsi-meet-sdk:3.0.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

React native code is working fine and I can run the jitsi app in the emulator but after creating android SDK when I use it in the native android code it's giving a build-time error.

I tried many solutions but seems like there is some issue with linking.

I followed all the step to link the manually in the android code.

![Screenshot 2021-02-25 at 7 36 31 PM](https://user-images.githubusercontent.com/79213346/109164741-c6e06700-77a0-11eb-8b20-d3fae7b29597.png)

one uncommon thing I found is when we add a below line of code in the build.settings the android folder created for the camera roll is not added inside the jitsi-meet but it's added outside of that folder.

include ':@react-native-community_cameraroll'
project(':@react-native-community_cameraroll').projectDir = new File(rootProject.projectDir, 	'../node_modules/@react-native-community/cameraroll/android')

check this image for more details.
![Screenshot 2021-02-25 at 6 31 39 PM](https://user-images.githubusercontent.com/79213346/109165125-36565680-77a1-11eb-879b-48dde70fdce6.png)

### Steps to reproduce:

1. Install react native camera roll package from here https://www.npmjs.com/package/@react-native-community/cameraroll
2. follow manual android linking steps, add code in reactnativeInstancemanager.java instead of mainapplication.java
3. create an android SDK and use it in the native code.

### Expected behavior:

The app should build it with the SDK we have created and it should run properly.

### Actual behavior:

Application is not building using the created SDK.
### Server information:

- Jitsi Meet version: latest jitsi code - current release
- Operating System: mac os

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

Please let me know if you need more details on this issue I will share it.

Looking for your support. 

Thanks

**Comment by idrive-pankaj** [comment]
@saghul could you please help me.

**Comment by rcidt** [comment]
@idrive-pankaj and anyone else in the future, you have to manually link them a little differently than in regular RN apps:

https://github.com/jitsi/jitsi-meet/issues/3984
