### ISSUE TITLE
websockets broke after upgrade

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#8687]
Hi,

I decided to upgrade my jitsi-meet install (fresh install on a virgin debian buster) using the unstable packages.

I used to have webscockets working fine before, but on the new installation I see in the console logs that websockets are not working anymore

WebSocket connection to 'wss://my-jitsi.com/xmpp-websocket?room=test4' failed: Error during WebSocket handshake: Unexpected response code: 403

I also noticed that the old openBridgeChannel: 'websocket' parameter is now completely missing from config.js so I tried adding that manually but still getting the 403. Has the openBridgeChannel parameter been deprecated? I can't seem to find any info on that. It's just gone from your repo all of a sudden.

I installed jitsi-meet using the Quick Start guide (with nginx-full) and supposedly websockets now should work out of the box, but it's not working for me....

I have in my jvb.conf:

videobridge {
    http-servers {
        public {
            port = 9090
        }

cc {
        trust-bwe=false
    }

    }
    websockets {
        enabled = true
        domain = "my.jitsi.domain:443"
        server-id = xxx.xxx.xxx.xxx (public IP)
        tls = true
    }

}

In my nginx site.conf file I seem to have proper ws support:

 # xmpp websockets
    location = /xmpp-websocket {
        proxy_pass http://127.0.0.1:5280/xmpp-websocket?prefix=$prefix&$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        tcp_nodelay on;
    }

    # colibri (JVB) websockets for jvb1
    location ~ ^/colibri-ws/default-id/(.*) {
        proxy_pass http://127.0.0.1:9090/colibri-ws/default-id/$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        tcp_nodelay on;
    }

and

# websockets for subdomains
    location ~ ^/([^/?&:'"]+)/xmpp-websocket {
        set $subdomain "$1.";
        set $subdir "$1/";
        set $prefix "$1";

        rewrite ^/(.*)$ /xmpp-websocket;
    }
}

Any idea where I should look further to try and understand why websockets aren't working for me?

Thanks

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you. 

>     server-id = xxx.xxx.xxx.xxx (public IP)

You should remove this line as your config expects as server id `default-id` here: `location ~ ^/colibri-ws/default-id/(.*)`



> WebSocket connection to 'wss://my-jitsi.com/xmpp-websocket?room=test4' failed: Error during WebSocket handshake: Unexpected response code: 403

This means that you have moved from bosh to websockets in your config.js. 
Mind that there are two types of websockets, the one for communicating directly to the bridge(^/colibri-ws/) and one for signaling(/xmpp-websocket). The one for signaling that replace bosh you also need to enable mod_smacks and do few extras settings in prosody there are posts in the community that cover those, but for now you can just revert to using `bosh: '//jitsi-meet.example.com/http-bind',`

**Comment by pdarcos** [comment]
Thanks @damencho 
Will do.
I think I got the server-id from the community in some tutorial somewhere.

There's probably lots of outdated and wrong info in the community forum. I know you don't have time to do this but it would help if the obsolete posts/configs would be marked as such wherever possible in the community, or else copy the up to date ones from the community and post them in the handbook. Just a suggestion.
Thanks again

**Comment by damencho** [comment]
Handbook is already updated: https://jitsi.github.io/handbook/docs/devops-guide/faq#how-to-migrate-away-from-multiplexing-and-enable-bridge-websockets

And on a clean install, this is by default configured and you don't need the instructions. 
The replacing bosh with websocket is not enabled by default and there are no official instructions for that, because in some cases you need to patch prosody ...
