### ISSUE TITLE
Add file & image upload (chat improvements)

### ISSUE THREAD

**Issue by sxiii** [jitsi/jitsi-meet#8700]
**Is your feature request related to a problem you are facing?**
Yes. My problem is that I cannot exchange files and images in text chat. That would be really useful and I've seen WebRTC file exchange implementations.

**Describe the solution you'd like**
I would like to have possibility to upload files and images (ideally, also audio files and videos) to text chat. Would also be nice to have youtube links interactive, adding button like "stream this video from youtube" near someone's youtube link.

**Describe alternatives you've considered**
In other way, we have to use external file storage services. But IMGUR & other centralized file/image hosting services could be also implemented via API. Or we could use IPFS and similar to exchange the files in a torrent-alike way.

**Comment by Nokia808** [comment]
Hi.
Office files like .doc, .docx, .ppt, .odt, ....... & also, .pdf are very needed specially for academic meeting holding online in these bad days of COVID19 pandemic attack !

**Comment by saghul** [comment]
Just to adjust everyone's expectations: this is not something we plan to work on.

That said, this looks like an interesting project for something like Google Summer of Code, which we are hoping to get into this year.

**Comment by HansJK** [comment]
Couldn't you just integrate matrix or something? This is a feature that's expected by everyone coming from zoom and other platforms.

**Comment by saghul** [comment]
Matrix already integrates with Jitsi, we think that is a good Avenue for these features (a service that embeds Jitsi) not the other way around.

**Comment by HansJK** [comment]
If a team is using Matrix, wouldn't it be very handy to be able to synch the matrix room to the Jitsi chat?
Also, it was a suggestion since you didn't seem keen on adding support for images.
