### ISSUE TITLE
Continue to transmit camera picture when the screen (mobile) is switched off

### ISSUE THREAD

**Issue by pzystorm** [jitsi/jitsi-meet#8701]
**Is your feature request related to a problem you are facing?**
I am using Jitsi with two different mobile phones as "baby phone". One is at the kid, one is in my pocket. Both are connected to the same Jitsi conference. Currently if I switch off the mobile screen which is at my kid (f.ex. to save battery or to reduce light in the room) the app is still connected to that jitsi room, but only transmits audio to that room - and no video anymore.

**Describe the solution you'd like**
To save battery it would cool, if the mobile app can continue to transfer camera pictures, if the mobile screen is switched off.

**Describe alternatives you've considered**
Use another product ;)

**Comment by saghul** [comment]
It's not possible to use the camera when the phone is in that state, unfortunately.

**Comment by pzystorm** [comment]
Thats not true.
For example look at this tool:
https://play.google.com/store/apps/details?id=com.dev47apps.droidcam
This tool continues to transmit the picture althought I use the side button to switch off the screen.
