### ISSUE TITLE
Android sdk feature flag

### ISSUE THREAD

**Issue by kaswan24** [jitsi/jitsi-meet#8704]
The newly added feature flag "help.enabled" is not working in android v.10, event after setting this flag false, I am able to see the help button on the call screen

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by kaswan24** [comment]
implementation ('org.jitsi.react:jitsi-meet-sdk:3.0.0')

**Comment by kaswan24** [comment]
Its working now after upgrading to 3.2.0
