### ISSUE TITLE
compilation error for mobile (ios and android) Unexpected string literal

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#8706]
Hi guys,

I just did a fresh git clone and tried to compile the mobile apps (on a linux host for android and on a macbook Big Sur host for iOS).

In both cases I get the following error message and the app doesn't run.

Considering this is a fresh git clone of your repo with no changes whatsoever I believe there's a missing } somewhere.

Unfortunately the error message doesn't really help much. It seems there's a missing curly bracket somewhere after "it" but I don't know where. I looked in the language files (it seems to indicate italian) but I don't see any missing curly brackets anywhere.

Is anyone else seeing this error on a fresh compilation?

Thanks

![compile_error](https://user-images.githubusercontent.com/32959420/109538958-99edc600-7ab8-11eb-97eb-75f717fdc409.png)

**Comment by saghul** [comment]
I just tried ce6debac4 and cannot reproduce this.

**Comment by pdarcos** [comment]
Thanks @saghul 

Strangely, although I could reproduce it yesterday everytime in my mac and linux machines, today I can't reproduce it any longer.

No idea what changed from yesterday to today. But as long as it's gone that's what matters.

I'll close this now and will re-open if it comes back.

Thanks
