### ISSUE TITLE
Self hosted on Azure : No audio ( Reload needed) 

### ISSUE THREAD

**Issue by Emirbz** [jitsi/jitsi-meet#8707]
### Description:
I have a self hosted jitsi running on Azure .
I use jitsi for hosting  meetings for around 20 people 
The instance is working fine, but sometimes some participants are forced to refresh
the page because they stopped hearing everyone else or they can't be heared by others.
I couldn't find any erros in the browser console.
I think the problem comes from Azure because , this never happened when deploying on local server.
[ Jitsi-Azure deployment files - Google Drive](https://drive.google.com/drive/u/4/folders/1n20X8-kY0EAWnnjO7WyKHRGGaZETMegY)
### Deployment files:
https://drive.google.com/drive/u/4/folders/1n20X8-kY0EAWnnjO7WyKHRGGaZETMegY
### Steps to reproduce:

Making a meet with around 20 person.

### Server information:
- VM spec : 16 GB Ram & 4 CPUs
- Jitsi Meet version:  stable-5142-4

### Client information:

- Browser / app version: Most participants uses google chrome
- Operating System: Ubuntu 16.04+ / Windows 10

**Comment by saghul** [comment]
What do you see in the JS console when this happens to those users?

**Comment by Emirbz** [comment]
> What do you see in the JS console when this happens to those users?
Actually the console show no errors

**Comment by Emirbz** [comment]
This is some errors that shows to some participants
[Console logs errors](https://drive.google.com/drive/folders/18ZMNLODQV0JyL1rYGYBER-KtXJg0_POP?usp=sharing)
