### ISSUE TITLE
Duplicated AppAuth classes -> Please add SwiftPM support

### ISSUE THREAD

**Issue by davidevincenzi** [jitsi/jitsi-meet#8717]
**Is your feature request related to a problem you are facing?**
Yes. In our project we cannot use Cocoapods, so we needed to manual import your library. The `AppAuth` library is a dependency of Jitsi and we're also using the AppAuth library via SwiftPM. The issue is that we get several warnings about duplicated code. Basically all the AppAuth classes are duplicated in our binary!

**Describe the solution you'd like**
Please adopt SwiftPM, which is pretty mature now and many companies are already using it in production applications.

**Describe alternatives you've considered**
We had to do several workaround to avoid issues, for example in `NSKeyedUnarchiver`. Also I wonder what's going to happen when we need to update the AppAuth library.

**Comment by saghul** [comment]
Our SDK is built with React Native, which leans heavily on CocoaPods. Both React Native and other external dependencies are kept together using podspec files as follows: https://github.com/jitsi/jitsi-meet/blob/master/ios/Podfile#L17

How would the build work with SwiftPM?

**Comment by ibespaljko** [comment]
We have the exact same problem in our project!
Is there a way to build jitsi without AppAuth and then manually integrate to avoid duplication of AppAuth classes?

**Comment by saghul** [comment]
We don't depend on AppAuth directly, it's an indirect dependency. Maybe it's the Google sign in plugin? We could update to the latest version if that helps.

**Comment by ibespaljko** [comment]
You are correct, since v5.0 Google Sign-In [change log](https://developers.google.com/identity/sign-in/ios/release) states: "Adds dependencies on AppAuth and GTMAppAuth."
Updating to the latest version wont help :(

Can we remove the Google Sign-In feature and rebuild the SDK? I've tried with simple podfile modification to remove Google and running `npx react-native run-ios`, but there are other pods that depend on Google Sign-In...

**Comment by saghul** [comment]
It's not that simple unfortunately.

**Comment by davidevincenzi** [comment]
> Our SDK is built with React Native, which leans heavily on CocoaPods. Both React Native and other external dependencies are kept together using podspec files as follows: https://github.com/jitsi/jitsi-meet/blob/master/ios/Podfile#L17
> 
> How would the build work with SwiftPM?

@saghul ok, I see the problem 🤔. ReactNative doesn't support SwiftPM 👎
This is a major issue for us in adopting Jitsi :/

**Comment by saghul** [comment]
If you have a suggestion please do let us know, but right now I don't know what could be done here.

**Comment by davidevincenzi** [comment]
Neither do I for now 🤷‍♂️ 
Thanks
