### ISSUE TITLE
[Feature Request] Let choose camera with a dropdown menu

### ISSUE THREAD

**Issue by adocampo** [jitsi/jitsi-meet#8727]
**Is your feature request related to a problem you are facing?**
I know this is a corner case, but I will tell you anyway. I faced a problem lately with one of my users. He has installed OBS (https://obsproject.com/es/) on Windows, which installs a "virtual camera". 
When the users disconnect the USB camera, then the OBS virtual camera becomes the primary camera of the OS and jitsi fails (obviously) with an unknown error. The problem is when the user connect back the camera _on another USB port_ (users usually doesn't look where a USB device is connected, because all the ports are the same), then Windows reinstalls the camera with another ID and becomes the secondary camera, making jitsi fail again. In order to use the camera, user needs to connect the camera in the USB port it was connected _before_ installing OBS.
As I said, this is a very corner case, because that user uses that camera on different places, so he's connecting and connecting it often, and besides that, OBS has a virtual camera, which is completely useless outside OBS. Normal users won't plug and unplug the cameras, and if they have 2 or more real cameras, jitsi would work with any of them.

**Describe the solution you'd like**
A simple dropdown letting the user choose the camera would solve this. 

**Describe alternatives you've considered**
The workaround was to uninstall OBS, let jitsi work with the real camera, then install back OBS, see jitsi was working, and finally I said to the user is to connect always the camera on the same USB port. But I really think a dropdown would make easier all this, like skype or other apps are doing, and if you have more than one camera, you can use the one you want without dealing with cables and so

**Comment by saghul** [comment]
We already have 2 dropdown menus were you can select the camera. One in the "arrow menu" in the video mute button and another one in the settings dialog.

<img width="647" alt="Screenshot 2021-03-04 at 11 17 27" src="https://user-images.githubusercontent.com/317464/109949071-3ee7e900-7cdb-11eb-90af-2d3f540f5462.png">
<img width="333" alt="Screenshot 2021-03-04 at 11 17 00" src="https://user-images.githubusercontent.com/317464/109949323-879fa200-7cdb-11eb-8cf5-83d195e90d84.png">

**Comment by adocampo** [comment]
On that computer shows this on the camera configuration.
![image](https://user-images.githubusercontent.com/2266612/109950121-76a36080-7cdc-11eb-8ea8-4eae4e510035.png)

**Comment by saghul** [comment]
Weird indeed!
