### ISSUE TITLE
Strange domain paths appearing - hijacking?

### ISSUE THREAD

**Issue by ollydixon** [jitsi/jitsi-meet#8745]
After installing Jitsi meet under a subdomain very strange websites have suddenly appeared there in their own paths.

I used this guide https://www.digitalocean.com/community/tutorials/how-to-install-jitsi-meet-on-ubuntu-18-04

The subdomain was video.polydelic.com (I have removed this now for obvious reasons)

Sub-paths started to appear (screenshot below), what is going on? The server is no longer running.

Example link: http://video.polydelic.com/in/fireboy+songs+mdundo+com/sugihbareng

<img width="834" alt="Screenshot 2021-03-07 at 08 52 53" src="https://user-images.githubusercontent.com/6940726/110233219-db4ffc80-7f22-11eb-8a2f-333c42c75eea.png">

**Comment by saghul** [comment]
Was your DNS configured correctly?

Our setup does not modify DNS, that is up to you.

**Comment by ollydixon** [comment]
DNS was only one subdomain. It's the Jisti server making subdomains. Cause when I closed the server, it stopped after a while. You guys have a security issue.

**Comment by saghul** [comment]
We don't create any subdomains, we simply can't magically go to your DNS provider and add entries there.

Even if there was a security issue, which you have provided no proof of, it's incredibly irresponsible to report it like this.

I'm not sure what your problem is, but this attitude is not a very good start if you want people to help you.

**Comment by ollydixon** [comment]
@saghul I am simply reporting an issue I have come across. Sorry if you feel like my 'attitude' is a problem (maybe you should look at yourself?)

It's possible to create subdomains without the DNS provider you know that right? If you have access to the root DNS (as the Jitsi server has) you can create any subdomain you wish.

**Comment by saghul** [comment]
Yes, paths are different indeed.

Jitsi is designed to kinda "own" a subdomain.

We do create an entry for the configured subdomain.

I'd start by checking the web server config. It's possible someone hacked into your server and altered the config for instance.

**Comment by ollydixon** [comment]
@saghul it was a standard Ubuntu instance from Digital Ocean with the firewall setup. Never had an issue with that before (in many years, 100 of instances) until I installed Jitsi meet. But could be that they are the ones with issue :-)

**Comment by saghul** [comment]
I don't know what you expect me to do here, I don't have access to your machine. A firewall is irrelevant if SSH is open with a weak password for instance.

Please check your web server config. Also open your JS console log and check what JS / HTML is making calls to that page.

**Comment by ollydixon** [comment]
@saghul next time I'll take a snapshot and share it. I'll close this for now.
