### ISSUE TITLE
Allow to define separate resolution for screen sharing

### ISSUE THREAD

**Issue by martinfrancois** [jitsi/jitsi-meet#8747]
**Is your feature request related to a problem you are facing?**
When we record meetings using Jibri where screen sharing is involved,  a resolution of 720p is not high enough, making the text on the screen that is shared hard to read and blurry. When we increase the resolution in `config.js` to 1080p, the quality is good, but at the same time, all of the participant's cameras are also streamed at 1080p. This puts a substantially higher load on Jibri, especially with more than 2 or 3 participants, since there are a lot of video streams in higher quality. This requires a lot of system resources which are expensive.

Having a webcam in a lower resolution (epecially when a screen is shared) doesn't matter as much, usually 720p is more than enough, if there are 4 or more people even without screen sharing, probably even 480p would be sufficient. But a higher resolution of the screen while screen sharing is much more critical.

**Describe the solution you'd like**
If we could specify the `resolution` attribtue in `config.js` separately for screen sharing, for example:
```
resolution: 720,
screenSharingResolution: 1200,
constraints: {
    video: {
        height: {
            ideal: 720,
            max: 720,
            min: 240
        }
    },
    screen: {
        height: {
            ideal: 1080,
            max: 1200,
            min: 720
        }
    },
},
```

**Describe alternatives you've considered**
Of course, throwing more resources at it always helps - probably with bigger machines they would be able to handle both high resolution video feeds from webcams and screen shares at the same time, but this costs a lot more, and usually meetings are focused a lot on screen shares anyways, which is why it would seem wasteful to me to stream high quality webcam footage if it's only displayed in a very small rectangle anyways.

-----------

Of course, if there's a different way to achieve the same result that I didn't know of, I'd be glad to hear about it.

I don't know the jitsi codebase well, but I had a quick look at it, and if it's just about reading a different `resolution` from the `config` [here](https://github.com/jitsi/jitsi-meet/blob/41e6af3464628659bd080ec4f54802bae32c6a62/react/features/base/tracks/functions.js#L105) and maybe some changes [here](https://github.com/jitsi/jitsi-meet/blob/dcda89012e0af7eba0c1e7d81f6ad8593018d7ca/conference.js#L1718), this could be quite easy to implement, in which case I would consider contributing that feature.

**Comment by mschwehl** [comment]
Still a good idea
