### ISSUE TITLE
jitsi doesn't work after enabeling gravatarBaseURL in config.js

### ISSUE THREAD

**Issue by Gajusbonus** [jitsi/jitsi-meet#8749]
### Description: 
when uncommenting {gravatarBaseURL: 'https://seccdn.libravatar.org/avatar/';}
the welcome page doesn't work anymore.
I noticed the line ends with ;
instead of ending with ,
### Steps to reproduce:

1. edit confis.js
2. uncomment gravatarBaseURL: 'https://seccdn.libravatar.org/avatar/';
3. save and reload page

### Expected behavior:
Welcome page should load as expected

### Actual behavior:
Page turn up without any elements

### Server information:

- Jitsi Meet version: 2.0.5390-3
- Operating System: ubuntu 18.04

### Client information:

- Browser / app version: Firefox / Iron
- Operating System: Linux mint 19.03

**Comment by saghul** [comment]
That's a bug indeed, it should be a comma.
