### ISSUE TITLE
ReferenceError: interfaceConfig is not defined

### ISSUE THREAD

**Issue by ibeardslee** [jitsi/jitsi-meet#875]
Recently upgraded (via .deb) from 1.0.1108-1 to 1.0.1217-1 (according to apt-cache policy) and I'm getting an error that is stopping the interface loading correctly.

Chromium says it is in .. 
https://server/libs/modules/UI/toolbars/ToolbarToggler.js

ToolbarToggler.js:9 Uncaught ReferenceError: interfaceConfig is not defined

`let toolbarTimeout = interfaceConfig.INITIAL_TOOLBAR_TIMEOUT;`

Firefox says ..
view-source:https://server/libs/app.bundle.min.js?v=1217

**Comment by ibeardslee** [comment]
`sudo apt-get install jitsi-meet=1.0.1108-1` resolved the problem and have been able to continue.

**Comment by damencho** [comment]
It seems that interface_config.js is not loaded. Do you have any custom changes, like in the index.html?
Are you using nginx or jetty?
Interface config is currently loaded using ssi, so if your nginx config has no ssi on, it could be the reason.

**Comment by ibeardslee** [comment]
Nginx is installed but just does a redirect from port 80 to port 443
This is a test environment, so I'm going to blow it away and reinstall without nginx and see if it behaves.
I think I would otherwise have to downgrade the rest of the jitsi packages.

**Comment by damencho** [comment]
Hum, but who is serving the meet instance, nginx? If this is the case do you have the ssi on; option there?
If you are serving using the jetty that is inside in videobridge there can be a real problem with the ssi implementation in there, I will test that to see is there a problem.

**Comment by damencho** [comment]
Just tried on clean ubuntu 16.04 vm installing stable jitsi-meet served from jetty, works fine. So it should be some configuration on your side.
Serving from nginx should have ssi on, as in the default nginx config installed by default: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example

**Comment by ibeardslee** [comment]
Although Jitsi meet can directly serve https, is Nginx still recommended?

**Comment by damencho** [comment]
Depends on the deployment, if it is single ip address machine, serving through jvb is recommended to be able to serve media over 443, for restricted corporate networks. But you will definitely need nginx if you have deployment with several jvbs, and nginx jicofo and jvb are on different machines.

**Comment by ibeardslee** [comment]
ta, well I have something else weird and wonderful going on now. But safe to say that the problem (or just the symptoms) I originally logged are sorted. So fair to say I can close this and tackle whatever else has gone boom.

**Comment by white-collar** [comment]
@ibeardslee so, pls, can you add more details how did you solve problem ?
