### ISSUE TITLE
Jitsi android app uses microphone for audio output on Xiaomi Redmi Note 7

### ISSUE THREAD

**Issue by tobip** [jitsi/jitsi-meet#8758]
### Description:

It seems that the Jitsi android app is using the microphone of my phone for audio output.

### Steps to reproduce:

1. Join any Jitsi meeting
2. Hear audio through microphone

### Expected behavior:

Expected to hear audio from the actual phone speaker.

### Actual behavior:

It kind of works but volume is very low, it is hard to hear anything and the sound is coming from the top end of the phone, while the speaker is at the bottom.

At the same time the microphone is working, others can hear my voice.

Choosing "Select the sound device" and switching between "Phone" and "Speaker" doesn't have any effect.

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: 

### Client information:

- Phone: Xiaomi Redmi Note 7
- Browser / app version: Android App version 20.6.2, downloaded from F-Droid
- Operating System: Lineage Android 10; lineage_lavender-userdebug 10 QQ3A.200805.001, including updates from 2 February 2021

**Comment by saghul** [comment]
There are usually 2 speakers, one on the at piece are and one on the bottom. The latter is usually used as a loudspeaker.

We default to the loudspeaker.

Does the volume change when you use the device's volume buttons?

Can you get the output of adb logcat ?

**Comment by tobip** [comment]
Hey thanks for your reply. I just wanted to send you the logfile, but actually now it works fine, jitsi is using the speaker as as expected!
Probably restarting the app several times helped! Thanks anyways :-)

Great app, great service, thank you for your software!

---



> <strike>In my case the loudspeaker at the bottom is not used during a jitsi call.
> 
> Pressing the volume buttons during a jitsi call in my case does change the volume.
> 
> Attached is a logfile of just starting and ending a jitsi test call.
> 
> [adb_logcat.txt](https://github.com/jitsi/jitsi-meet/files/6111379/adb_logcat.txt)</strike>
