### ISSUE TITLE
Stats are not shown in full in Firefox

### ISSUE THREAD

**Issue by missic** [jitsi/jitsi-meet#8765]
In the connection status tooltip, stats such as the following ones:
  Audio/video coding formats
  Resolution
are not shown in Firefox.

In a Firefox-Firefox call they are not shown anywhere.
In a Firefox-Chromium call they are not shown in Firefox neither for the local nor the remote participant, while they are shown in Chromium for both the local and the remote participant.

Tested in Firefox 86.0 on both Fedora and macOS, on self-hosted docker-jitsi-meet-stable-5390-3

**Comment by pdarcos** [comment]
I can confirm this same behavior with Firefox 86.0.1 running on linux
