### ISSUE TITLE
iOS: Private message button showed when chat is disabled

### ISSUE THREAD

**Issue by julian-ladjani** [jitsi/jitsi-meet#8772]
### Description:

Private message button isn't hidden when chat is disabled (flag) on iOS SDK

### Steps to reproduce:

1. Use iOS JitsiMeet iOS SDK
2. setFeatureFlag("chat.enabled", withBoolean: false)
3. Long touch member of conference

### Expected behavior:

Private message button must be hidden

### Actual behavior:

Private message button is not hidden
![image](https://user-images.githubusercontent.com/24625002/110770758-ff307c80-8259-11eb-9d64-b8241d0c9403.png)

### Client information:

- iOS SDK version: 3.2.0
- Operating System: iOS 14.4

**Comment by pedralma** [comment]
I was going to report it, if I can contribute, I would be happy to do so

**Comment by saghul** [comment]
This is fixed in https://github.com/jitsi/jitsi-meet/commit/2587eefefc89a735d4986c9de5480cf9d7991651

**Comment by pedralma** [comment]
it's not in the last release of the ios SDK, right? is there something scheduled?

**Comment by saghul** [comment]
Yeah we'll make a release soon.
