### ISSUE TITLE
External API as NPM package

### ISSUE THREAD

**Issue by matteoturini** [jitsi/jitsi-meet#8778]
**Is your feature request related to a problem you are facing?**
Yes. I'm trying to make an application that uses the Jitsi Meet API.

**Describe the solution you'd like**
Create an NPM package with the external API and TypeScript typings.

**Describe alternatives you've considered**
Loading the JS manually from meet.jit.si/external_api.js. Not a good solution for NextJS/React/Webpack projects.

**Comment by matteoturini** [comment]
I know this has already been discussed, but I want to use meet.jit.si without the jitsi-meet package.

**Comment by damencho** [comment]
It is also not a good solution for embedding it in, as it may totally break your app without any warning.

**Comment by saghul** [comment]
You can just embed it in your project, but as Damencho pointed out things may break.

Packaging the external API is not currently being considered, sorry.

**Comment by matteoturini** [comment]
> 
> 
> It is also not a good solution for embedding it in, as it may totally break your app without any warning.

Why is that? Isn't it just creating a new iframe with the meeting?

**Comment by saghul** [comment]
If it were just an iframe you wouldn't need a package, would you? It runs in an iframe, yes, but there is a communication channel between the meeting in the iframe and the embedding window for sending commands, receiving events, etc.
