### ISSUE TITLE
When we enable DarkMode in Android jitsi UI is messed up

### ISSUE THREAD

**Issue by AjayShivanagol** [jitsi/jitsi-meet#8781]
![jitsi](https://user-images.githubusercontent.com/29257275/110919848-b7d1eb00-8342-11eb-931b-fd1463e62be8.jpeg)

**Comment by saghul** [comment]
What device and Android version is that?

**Comment by AjayShivanagol** [comment]
@saghul It depends upon which OS we are making use it... I am making use of Color OS. I facing this.
but if you check with MIUI OS you will see White buttons converted to black. it depends on Algo written by vendors.

![Phone](https://user-images.githubusercontent.com/29257275/110929004-80b50700-834d-11eb-9a01-c48373417bf0.jpeg)

**Comment by saghul** [comment]
I  tested on MIUI and cannot reproduce it.

**Comment by AjayShivanagol** [comment]
@saghul Maybe happening to RealMe devices then. is there a way to fix them?

**Comment by saghul** [comment]
We have just redesigned the toolbar, maybe it works better. Soon on beta.

**Comment by AjayShivanagol** [comment]
@saghul I checked with the latest jitsi APP still I am facing the same issue.
![1234](https://user-images.githubusercontent.com/29257275/113176791-7f02a300-926a-11eb-91b7-8f8108ab94bc.jpeg)
![123](https://user-images.githubusercontent.com/29257275/113176799-8164fd00-926a-11eb-95eb-29ebef0a9255.jpeg)

**Comment by saghul** [comment]
Looks like inverted colors or something. I cannot reproduce this alas, so I can't even investigate, sorry.
