### ISSUE TITLE
Sharing desktop crashes (stops); page reload helps as workaround for a few seconds

### ISSUE THREAD

**Issue by buti1021** [jitsi/jitsi-meet#8786]
### Description:

Sharing desktop crashes (stops); page reload helps as workaround for a few seconds

### Steps to reproduce:

1. Connect with one client(A) through browser(Firefox)
2. Connect with other client(B) through browser(Vivaldi)
3. A shares his screen (full desktop)

### Expected behavior:

B can see As screen until A stops the sharing

### Actual behavior:

B can see A's screen but sometimes (~every 5 minutes sometimes less sometimes more) the sharing crashes, Screen freezes and after a while the logo of user A appears. After B reloads the page, the sharing works again (for the same random period of time)!

### Server information:

- Jitsi Meet version: Current live version @ https://meet.jit.si
- Operating System:

### Client information:

- Browser / app version: Firefox/Vivaldi
- Operating System: Windows

**Comment by jallamsetty1** [comment]
This looks like a Firefox bug. What version of Firefox are you seeing this issue on ? It would be helpful if you can file a bug report on https://bugzilla.mozilla.org/home.

**Comment by Turbotomate** [comment]
> 
> 
> This looks like a Firefox bug. What version of Firefox are you seeing this issue on ? It would be helpful if you can file a bug report on https://bugzilla.mozilla.org/home.

I think this is not a Firefox-Bug. I played around with different versions of Browsers and Jitsi and the problem only occurs in combination with the "new" Jitsi design (changed button bar for microphone control etc.) and Firefox. The exact same Firefox does work with every other Jitsi instance i found with the older design/button layout.

**Comment by TBG-FR** [comment]
Same issue here, looks like the last release of Jitsi breaks screen sharing ? I noticed that issue on multiple instances

**Comment by M-Reimer** [comment]
Our university uses "WebEx" for lectures and there screen sharing works rock solid.
Maybe still some issue with Firefox, but at least WebEx managed to get used to it somehow.

**Comment by jallamsetty1** [comment]
This should have all been fixed in the latest release on meet.jit.si and stable packages. This indeed was a FF bug and we implemented a workaround for it.
