### ISSUE TITLE
Virtual Background

### ISSUE THREAD

**Issue by artknight** [jitsi/jitsi-meet#8789]
This project here https://grail.cs.washington.edu/projects/background-matting-v2/ is under MIT license now!!!

Their technology seems far more superior to anything I have seen!!!

**Comment by saghul** [comment]
Thanks! We just landed out first version of virtual backgrounds on master, stay tuned! :-)

**Comment by artknight** [comment]
@saghul Thank is fantastic!!! How soon do you think before this could get added to the release?

**Comment by benbro** [comment]
@artknight is there code to use it with Javascript?

**Comment by artknight** [comment]
@benbro I do not know but I believe it is based on python and some other tech.

**Comment by saghul** [comment]
Closing for now, good to have other resources available though.
