### ISSUE TITLE
Virtual background requires canvas access on Firefox

### ISSUE THREAD

**Issue by jacksongoode** [jitsi/jitsi-meet#8791]
### Description:

Firefox, in some protection modes will block access to extract canvas data as it can make the user personally identifiable. The result, on Firefox is that enabling the background will produce some wonky colors.  

### Steps to reproduce:

1. Enable virtual background
2. Refresh the page to have the notification to allow canvas data

### Expected behavior:

The request for canvas data should be made prior to its attempted use on Firefox. It appears that this request only needs to be made once. Another refresh or use of a different room will remember the setting.

### Actual behavior:

Wonky colors from lack of canvas.

### Server information:

- Jitsi Meet version: alpha.jitsi.net/

### Client information:

- Browser / app version: FF 86.0
- Operating System: Ubuntu

**Comment by saghul** [comment]
Interesting! Is this documented anywhere on MDN? /cc @tudor-phd

**Comment by jacksongoode** [comment]
Hmm, all I could really find was this bug thread. https://bugzilla.mozilla.org/show_bug.cgi?id=967895
It seems like the permission is late. Maybe there is some way to see if the canvas can be read and if not disable and ask user to enable?

**Comment by saghul** [comment]
https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting

Do you have that option enabled?

**Comment by saghul** [comment]
Similar issue: https://github.com/vector-im/riot-web/issues/9605 looks like there is nothing we can do here.

**Comment by jacksongoode** [comment]
> https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting
> 
> Do you have that option enabled?

Yes. There should be an site override but perhaps Mozilla hasn't gotten there yet?
