### ISSUE TITLE
Missing license for background segmentation model

### ISSUE THREAD

**Issue by benbro** [jitsi/jitsi-meet#8792]
The virtual background model is missing a license.
https://github.com/jitsi/jitsi-meet/tree/master/react/features/stream-effects/virtual-background/vendor

Please include the model card or official license from Google because it might prevent us from using jitsi-meet.

**Comment by saghul** [comment]
I'll add the license to the vendor README. It's complicated, as you know (but posting here for everyone else): https://github.com/tensorflow/tfjs/issues/4177 It started as Apache 2 but Google has now changed the license, after the original release. IANAL but I'd say it's currently in a bit of a gray area.
