### ISSUE TITLE
Video and Audio not working in some countries

### ISSUE THREAD

**Issue by anilolakkal** [jitsi/jitsi-meet#8796]
Both video and Audio not working in some countries. I tried both peer to peer and through videobridge. No errors in log, chat is working. I tried it with https://meet.jit.si/ its working fine. Im using quick install and using advanced configuration. The network status of participant seems connection lost in grey colour.

**Comment by hkarakose** [comment]
How did you understand it is related to country?

I tried installing using apt and also tried docker version. I am unable to get video and audio of participants

**Comment by anilolakkal** [comment]
> How did you understand it is related to country?
> 
> I tried installing using apt and also tried docker version. I am unable to get video and audio of participants

Video and Audio is working perfectly in all networks available here and other countries but not working in KSA. I have tried turn server also but no use.

**Comment by jbg** [comment]
@anilolakkal Try TURN+TLS (with a real SSL certificate configured in coturn) on port 443. This way it is hard to distinguish from HTTPS traffic.

@hkarakose your problem is likely unrelated to the topic of this issue, consider asking for help on community.jitsi.org or IRC.
