### ISSUE TITLE
Could not find any matches for org.jitsi.react:jitsi-meet-sdk:+ as no versions of org.jitsi.react:jitsi-meet-sdk are available. 

### ISSUE THREAD

**Issue by broshni25** [jitsi/jitsi-meet#8809]
I made my custom SDK following the steps in the handbook and this worked on my previous version of android studio. However, on updating to the latest version, the above mentioned error is coming.

Steps:
git clone https://github.com/jitsi/jitsi-meet.git 29
Navigate to the newly added jitsi-meet folder and execute npm install after that remove video mute button from toolbox.js.
Create a new folder( /tmp/repo ) inside root folder
Copy the react native and JavaScriptCore dependency via
cp -r node_modules/react-native/android/com tmp/repo/
and c p -r node_modules/jsc-android/dist/org tmp/repo/
Run this command ./android/scripts/release-sdk.sh /tmp/repo
Create a new android Project
Copy the /tmp/repo folder into this project
Add maven { url “file:/tmp/repo” } in the build.gradle (Project:MyProject)
Add implementation (‘org.jitsi.react:jitsi-meet-sdk:+’) { transitive = true } to the build.gradle

I also tried using the entire path, but the error persists.
![Screenshot 2021-03-16 at 6 51 58 PM](https://user-images.githubusercontent.com/37378428/111317110-da893a00-8689-11eb-8535-fc66dfeac8b7.png)
![Screenshot 2021-03-16 at 6 49 06 PM](https://user-images.githubusercontent.com/37378428/111317127-dceb9400-8689-11eb-8f53-81d143650f6c.png)

@saghul

**Comment by saghul** [comment]
The manual steps for JSC and RN are no longer necessary, please check the last version: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#build-and-use-your-own-sdk-artifactsbinaries

**Comment by broshni25** [comment]
Yes, that worked, thank you so much!

I also have a few other queries:
1. My apk size after integrating jitsi increased from 4mb to 110mb. Is this proper?
2. I wanted to remove the 'screen sharing' option from the overflow menu. I do not know a JavaScript very well; I removed the <ScreenSharingButton { ...buttonProps } /> from the OverflowMenu.js file. I figured this would remove it from the UI, however this doesn't work. Is there anything else that I need to be doing?
3. Is there a way to remove the room name from being displayed on top?
4. I can't use this in AndroidStudio running on Windows OS, right? Any updates on that?

One again, that you!

**Comment by saghul** [comment]
>     1. My apk size after integrating jitsi increased from 4mb to 110mb. Is this proper?

Add this to your application: https://github.com/jitsi/jitsi-meet/blob/9f9e192c3ca795826b08e0bfca79a2ea081844e5/android/app/build.gradle#L19-L21

>     2\. I wanted to remove the 'screen sharing' option from the overflow menu. I do not know a JavaScript very well; I removed the <ScreenSharingButton { ...buttonProps } /> from the OverflowMenu.js file. I figured this would remove it from the UI, however this doesn't work. Is there anything else that I need to be doing?

Yep, that should be it, any chance your build artifacts were cached?



>     3\. Is there a way to remove the room name from being displayed on top?

Yes, pass the `meeting-name.enabled` feature flag to false.



>     4\. I can't use this in AndroidStudio running on Windows OS, right? Any updates on that?

No, you can't. No plans to support it, sorry.
