### ISSUE TITLE
No sound when a third person leave

### ISSUE THREAD

**Issue by rorist** [jitsi/jitsi-meet#8811]
### Description:

When switching back from 3 people to 2 people, the other participant always appears muted and there's no sound for both participant.

### Steps to reproduce:

1. Two people conference
2. Add a third person
3. A person leaves

### Expected behavior:

- Sound keeps working ;)

### Actual behavior:

- No sound for all participants

### Server information:

- Jitsi Meet version: Since at least jitsi-meet 2.0.5617 (11th march 2021)
- Operating System: 
```
root@meet:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

### Client information:

- Various browser and OS

Some of this logs appears in the client,

`2021-03-16T17:56:20.644Z [modules/statistics/AudioOutputProblemDetector.js] A potential problem is detected with the audio output for participant 7bb1837e, local audio levels: [null,null], remote audio levels: undefined`

**Comment by damencho** [comment]
The participants that are not hearing each other, what happens if they join another meeting ... do they hear each other when they are just two of them in the meeting initially?

**Comment by damencho** [comment]
Maybe attaching the complete logs from one of the participant that do not hear will help to spot a problem...

**Comment by rorist** [comment]
Just upgraded from jitsi-meet 2.0.5659 to 2.0.5671 and it is working again !

**Comment by rorist** [comment]
It's actually been fixed, between last week and this week, can't exactly get the version but it's now working as expected again. 

Cheers
