### ISSUE TITLE
UI elements overlap with options dropdown

### ISSUE THREAD

**Issue by gocontractdev** [jitsi/jitsi-meet#8817]
### Description:

This is a frontend issue happening becasue the UI elements on top and at the very bottom of the video call lay on top of the options in the drop down. As a result, when the screen is small or there are many people in the call some of the drop down options are not clickable.

![alt text](https://i.ibb.co/YNFDvtK/Bildschirmfoto-2021-03-16-um-17-53-02.jpg)

### Steps to reproduce:

1.  Start a jitsi call on https://meet.jit.si
2. Join the call and share the link a few times
3. Join multiple times (4 would be enough for small screen for example our customer had the issue on big screen with 50 people on call).
4. Open the options dropdown.
5. Try clicking on the options  on the lowest or hjighest drop down options will fail

### Expected behavior:

All drop down options should be selectable regardless of placement. Moving the z-index to the front of any other element would be advisable here.

### Actual behavior:

When a user tries to access options of the drop downs on a small screen or with many people joined in the call it is not possible to click on some of the options since the UI elements placement lays on top of the options (so basically you can't click on them). Attached picture sexplain the incidident in a simple example:

![alt text](https://i.ibb.co/yh7JvRH/Bildschirmfoto-2021-03-16-um-18-27-59.png)
-- 2 last options are not cliackable.

![alt text](https://i.ibb.co/nBft0Bc/Bildschirmfoto-2021-03-16-um-17-49-21.jpg)

### Server information:
your main server (https://meet.jit.si)

- Jitsi Meet version: -
- Operating System:  -

### Client information:

- Browser / app version: Safari  -- Version 14.0.3 (16610.4.3.1.7).
- Operating System: BigSur 11.2.3.

### Additional information:

See the attached video.
https://www.mediafire.com/file/a06zkst4ep3e49l/telegram-cloud-document-4-5947149160737147125.mp4/file

- Internal Report (it is for us): JITSI-58

**Comment by saghul** [comment]
@vp8x8 @muscat1 cam either of you PTAL?

**Comment by gocontractdev** [comment]
thoughts?

**Comment by gocontractdev** [comment]
thoughts?

**Comment by muscat1** [comment]
IIRC, @vp8x8 took a look over this and said that the issues no longer occur after the latest updates to the Toolbar.
