### ISSUE TITLE
Combine with 8x8 Meet

### ISSUE THREAD

**Issue by heyakyra** [jitsi/jitsi-meet#8821]
Imagine if zoom, or slack, or gmail, had a separate app for the free service and the paid service. It’s so frustrating that for those who wish to support an open source video conferencing project may spend a good amount of energy promoting Jitsi. Finally, when enough peers are on board and use it enough that they decide to invest in the paid service, it’s an entirely separate application with no cross compatibility! Back to square one for the whole community :frowning_face:

Is there a roadmap to roll these into one?

[forum crosspost](https://community.jitsi.org/t/merge-8x8-and-jitsi/95845)

**Comment by saghul** [comment]
This topic is better suited for the community forum, as it's not an issue with the software itself. I'll follow up on the community post.
