### ISSUE TITLE
 ‘w’ key to change view triggers when hitting ctrl-w to close adjacent tab 

### ISSUE THREAD

**Issue by joshtriplett** [jitsi/jitsi-meet#8837]
(Previously discussed at https://community.jitsi.org/t/w-key-to-change-view-triggers-when-hitting-ctrl-w-to-close-adjacent-tab/95836 .)

### Description:

If I open another tab from a Jitsi conversation (such as by following a link from the chat), and then hit ctrl-w to close the new tab and return to the Jitsi tab, having ‘w’ still momentarily pressed (because I haven’t released it yet, and I happened to release the ctrl before the w) causes Jitsi to receive a keyup event without a corresponding keydown event or keypress event. Jitsi seems to react to the keyup event for ‘w’ by changing the view (from showing everyone to showing one person), which then means I have to switch the view back.

Could Jitsi switch to using keypress rather than keyup, to avoid this? Browsers are careful to not send a keypress event in this scenario.

### Steps to reproduce:

1. Start a Jitsi Meet meeting, with multiple participants.
2. Make sure you're in the default view with equally sized tiles for each participant
3. Open a new tab
4. Hit ctrl-w to close the new tab, and make sure you release ctrl before w
5. Notice that the view has changed to show one large tile for one participant

### Expected behavior:

The view should not change.

### Actual behavior:

The view changes when the 'w' key is released.

### Server information:

- Jitsi Meet version: Latest on meet.jit.si

### Client information:

- Browser / app version: Firefox 86
- Operating System: Linux

**Comment by i-need-to-tell-you-something** [comment]
There might be valid reasons why it is implemented the way it is, but for reference, the code that does what you want removed seems to be [here](https://github.com/jitsi/jitsi-meet/blob/2c9078985f1530cfd40059e1e2fcc09ce8334073/modules/keyboardshortcut/keyboardshortcut.js#L45).

**Comment by i-need-to-tell-you-something** [comment]
@stalebot I still care about this.

**Comment by joshtriplett** [comment]
Bug still exists.

**Comment by joshtriplett** [comment]
This issue still exists.

**Comment by mbrodala** [comment]
One possible solution would be taking modifiers into account, see https://github.com/jitsi/jitsi-meet/issues/7933

Personally I always accidentally trigger the screen share dialog when closing a terminal via `Ctrl`+`D` and focus switches to my browser. (Here Jitsi sees `D` and triggers the screen share dialog.)

**Comment by mbrodala** [comment]
Maybe fixed with https://github.com/jitsi/jitsi-meet/pull/13520?

**Comment by saghul** [comment]
Yes indeed!
