### ISSUE TITLE
iOS SDK setAudioMuted not working ?

### ISSUE THREAD

**Issue by eemi2010** [jitsi/jitsi-meet#8843]
### Description:

calling jitsiMeetView.setAudioMuted(true/false) has no effect. The view always report 0(unmuted)

### Steps to reproduce:

1. Call setAudioMuted(true/false) on an instance  if JitsiMeetView

### Expected behavior:
Audio should be muted when true is passed as argument

### Actual behavior:
Audio still unmuted even with true as parameter

### Server information:

- No server Involded:
- Operating System:

### Client information:

- iOS SDK 3.0.2:

**Comment by saghul** [comment]
Can you reproduce this with the latest SDK?

**Comment by eemi2010** [comment]
I m on 3.0.2 Is there a new version ? 
My pod entry looks like:
pod 'JitsiMeetSDK', '~> 3.0.2'

**Comment by saghul** [comment]
Yep, 3.2.0 is out: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

**Comment by eemi2010** [comment]
Just tried with 3.2.0 Unfortunately bug is still there. setAudioMuted(false) has not effect. Audio is still not muted and the delegate method reports Optional([AnyHashable("muted"): 0]) regardless of if the parameter of setAudioMuted is true or false.

**Comment by saghul** [comment]
@tmoldovan8x8 can you take a look?

**Comment by eemi2010** [comment]
Sorry to bother you guys. Any news on this bug (if that's actually a bug) ?

**Comment by tmoldovan8x8** [comment]
Hi @eemi2010. Yeah, indeed a bug slit into the iOS SDK. I've just pushed the fix for it and see when we can publish a new version

**Comment by eemi2010** [comment]
Hi @tmoldovan8x8 . Thanks a lot. Looking forward to the next released.

**Comment by saghul** [comment]
Closing this as it will be part of the next release.

**Comment by eemi2010** [comment]
Any new when the new release will come out. Off course I' m not trying to rush you. Just so we can plan.

**Comment by saghul** [comment]
We aim to make one next week.

**Comment by eemi2010** [comment]
Thx a million for your awesome work.

**Comment by eemi2010** [comment]
Work perfectly in the new SDK. Merci :)

**Comment by saghul** [comment]
Great to hear!

**Comment by eemi2010** [comment]
Not sure if I should open a bug for this. But you guyz have a typo in the JitsiMeetViewDelegate delegate.
(void)chatMessaageReceived:(NSDictionary *)data;

The second a should not be there no ?  This might also break future apps if you fix the typo. Should I open a new bug ?

**Comment by saghul** [comment]
It's clearly a typo so yeah it should be fixed. Can you please open an issue? Extra props if you can provide a PR.

**Comment by ahmed-classtra** [comment]
@saghul , @tmoldovan8x8 forgive my bugging you guys all over the github issues. 😅. But there's another issue related to this. Steps to reproduce:
1. Use the SDK method `setAudioMuted` or `setVideoMuted`. It will work the first time.
2. Use the same sdk method another time at any point during the meeting, it will not work.
3. If you first toggle the flag, then toggle it again to the desired final state it works.

My hunch is that there's a problem somewhere in the state variable that keeps track of audio and video.

The way to fix this (temporarily) is to make sure you toggle it before changing audio/vidoe to the final desired state:

```swift
self.jitsiMeetView?.setAudioMuted(false)
        self.jitsiMeetView?.setAudioMuted(true)
        self.jitsiMeetView?.setVideoMuted(false)
        self.jitsiMeetView?.setVideoMuted(true)
```
