### ISSUE TITLE
Latest select background option does not show on the web on IOS devices.

### ISSUE THREAD

**Issue by Poufy** [jitsi/jitsi-meet#8844]
I just noticed that the latest option released "Select background" does not show on the web on IOS devices. Even on previous versions (I cloned the project a month ago) I don't see the "Blur my background" option on IOS devices. I can see it on android and PC though and it is working perfectly fine. I am not sure if this is intended, but I thought I'd mention it just in case.

### Server information:

- Jitsi Meet version: Latest commit
- Operating System: Ubuntu

### Client information:

- Browser / app version: Browser

**Comment by saghul** [comment]
Those options rely on applying a filter con the canvas 2d context. That is not currently supported by Safari, which is really the engine used in Chrome for iOS. We detect this at runtime, so if / when Safari decides to implement it we will start to automatically show it.
