### ISSUE TITLE
Chat sidebar makes lobby request invisible

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#8845]
When lobby function is switched on and moderator has chat sidebar open the request for entering cannot be seen.

There should either be a separate icon to signal lobby request (e.g. lower left near the icons for chat, screen sharing and hand) or the lobby popup box should be moved to another screen position so that it doesn't collide with the chat.

**Comment by saghul** [comment]
Thanks for the report! We are currently working on a redesign and the chat panel will be moved to the right.
