### ISSUE TITLE
Need camera instance in JitsiMeet to turn flashlight, Video Zoom feature and video calling brightness.

### ISSUE THREAD

**Issue by andro-yogi7** [jitsi/jitsi-meet#8851]
Unable turn on flash light, video zoom feature and video brightness during jitsi meet call. Please suggest how to take "in use camera instance" in jisti meet project Android.

I am getting camera in use exception while trying camera.open(). I want to modify some things but not able to access camera object.

**Comment by saghul** [comment]
It's not possible to get the currently opened camera object. That is internally managed by WebRTC. You'd have to patch WebRTC to be able to extract it from Camera2Session, then add some API for that in react-native-webrtc, which is the library we use.

Someone had worked on something similar in the past: https://github.com/cmpayc/react-native-webrtc/commit/79d2e998ee72e7bac7eed4c636e141c4a4b7d442 Good luck!
