### ISSUE TITLE
Raise and Screenshare Button Covered by Raise Notification 

### ISSUE THREAD

**Issue by JitsiUser420** [jitsi/jitsi-meet#8860]
### Description:
The Raise and Screenshare Button gets covered by in meeting notifications. If at least 2 in meeting notifications appear the buttons get covered up and if you want to reach them again you are required to delete the notifications. 

![unknown](https://user-images.githubusercontent.com/81237761/112146454-de621280-8bdb-11eb-8e1a-8790a6471913.png)
![unknown](https://user-images.githubusercontent.com/81237761/112146542-fcc80e00-8bdb-11eb-9545-7ffa0d9ab03f.png)

### Steps to reproduce:

1. Meeting with at least 2 People
2. Click on raise multiple times
3. The bug will appear on the other users Screen

### Expected behavior:

The Notifications should appear above the section where the buttons are located and disappear after a the person who raised their hand talked. If this isnt possible the notifications should appear in the top left corner to make sure it doesn't interfere with the UI.  

### Actual behavior:

The notifications cover up the UI buttons, so you're not able to reach the raise nor screenshare button.
![unknown](https://user-images.githubusercontent.com/81237761/112146454-de621280-8bdb-11eb-8e1a-8790a6471913.png)
![unknown](https://user-images.githubusercontent.com/81237761/112146542-fcc80e00-8bdb-11eb-9545-7ffa0d9ab03f.png)

### Server information:

- Jitsi Meet version: meet.jit.si
- Operating System: -

### Client information:

- Browser / app version: Google Chrome latest version
- Operating System: Windows 10 Pro 64 Bit

**Comment by saghul** [comment]
This is fixed in the latest redesign, since the toolbar is now shown centered.
