### ISSUE TITLE
Firefox - Frozen video track when camera not available

### ISSUE THREAD

**Issue by samuelp-mw** [jitsi/jitsi-meet#8864]
### Description:

A bug seems to occur only for Firefox and is related to the availability of the camera.
If the camera is used by another app and the user tries to activate the camera at the same time, the user may not get any error message but a black screen as video track. At that moment the user cannot toggle/un-toggle the camera and is forced to reload the page completely in order to solve the issue.

### Steps to reproduce:

1. Create a Meeting in Firefox
2. Activate the video
3. Deactivate the video
4. Join the meeting from another window with Google Chrome for example
5. Activate the video in Google Chrome window
6. Try to activate the video in Firefox window again

### Expected behavior:

The user gets an error message mentioning that the camera is unavailable.

### Actual behavior:

No error message is given and a black screen replaces the local video track. At that moment, it is as well impossible for the user to toggle/un-toggle the video.
![screenshot](https://user-images.githubusercontent.com/79834730/112161852-cbefd500-8beb-11eb-833a-f8316a15ba42.png)

### Server information:

- Jitsi Meet version: 9f53c439c0 (JitsiMeet.JS.version) reproduced directly on https://meet.jit.si/ (23.03.2021 - 3:38PM UTC+1)
- Operating System:

### Client information:

- Browser / app version: Firefox Version 86.0.1 (64-bit)
- Operating System: Windows 10

### Additional information:

The same steps have been followed with Chrome and Edge but the bug could not be reproduced there.
When the problem occurs, 1 Frame from the camera is sometimes visible before getting the black screen

**Comment by damencho** [comment]
Can you upload the js logs from firefox when this happens? Do you see any errors there?
If there is no error coming from Firefox ... there is nothing we can do and the report should be moved to FF bugzilla ...

**Comment by samuelp-mw** [comment]
> 
> 
> Can you upload the js logs from firefox when this happens? Do you see any errors there?
> If there is no error coming from Firefox ... there is nothing we can do and the report should be moved to FF bugzilla ...

No error is visible in the log. When toggling the video, the only lines I can see then are these ones :
[logs.txt](https://github.com/jitsi/jitsi-meet/files/6190497/logs.txt)

**Comment by samuelp-mw** [comment]
> > Can you upload the js logs from firefox when this happens? Do you see any errors there?
> > If there is no error coming from Firefox ... there is nothing we can do and the report should be moved to FF bugzilla ...
> 
> No error is visible in the log. When toggling the video, the only lines I can see then are these ones :
> [logs.txt](https://github.com/jitsi/jitsi-meet/files/6190497/logs.txt)

@damencho I am trying to report the issue to FF Bugzilla. Do you know which instruction would be expected to fail or throw an exception for that specific issue? (What would be the expected behavior on Firefox side?). I still have a bit trouble to reach the root cause of the bug and where Firefox was supposed to behave differently. Thank you for your help.

**Comment by damencho** [comment]
getUserMedia calls I think, should maybe return an error.

**Comment by samuelp-mw** [comment]
> getUserMedia calls I think, should maybe return an error.

Thanks @damencho for the suggestion. I tried to debug the issue again. The instruction "navigator.mediaDevices.getUserMedia" seems never to be reached so I guess that probably the error is happening elsewhere. No logs "onUserMediaSuccess" or "Failed to get access to local media" are visible neither. I will keep investigating but will probably wait to have a better idea about where the problem is occuring to fill the issue.
