### ISSUE TITLE
Automatic recapturing of video device when currently used by another process

### ISSUE THREAD

**Issue by samuelp-mw** [jitsi/jitsi-meet#8868]
**Is your feature request related to a problem you are facing?**
My goal would be to enable automatic recapturing of audio/video device once released by another process. An example would be a user trying to toggle his camera that is currently not available. I am searching for a solution enabling to recapture the camera once released by the external process.

**Describe the solution you'd like**
* After the user notified his intention to toggle his camera and the requested camera is released by another process, request it again. This assumes that we have the possibility to know the status from the device (used or not by an external process) : I am not aware whether this is easily possible or not?

**Describe alternatives you've considered**
I have currently 2 alternative solutions in mind that currently sound more feasible but also less "clean" :
* Manual retry from the user : The message mentioning that the camera is currently not available is displayed.This notification could also include a small button enabling the user to retry.
* Retry capturing the video device at different interval : Once the user has notified his intention to toggle his camera, retry multiple times at different intervals to recapture the camera. This solution is not really clean I guess but I do not see any "simple" solution currently to implement the feature.

**Comment by saghul** [comment]
We have no way to know a camera is released by another process.

**Comment by samuelp-mw** [comment]
> We have no way to know a camera is released by another process.

@saghul Thanks for you reply. This means that the only way possible to test whether a device is used or not is trial and error approach right? I guess that no really clean approach would then enable to implement the targeted goal..

**Comment by damencho** [comment]
This needs to be implemented in the webrtc API implementations, which means in the major browsers then it will be possible for us to implement it.

**Comment by samuelp-mw** [comment]
> This needs to be implemented in the webrtc API implementations, which means in the major browsers then it will be possible for us to implement it.

Thanks for the information. I will close the issue for now.
