### ISSUE TITLE
Setting a background for the room (image, color)

### ISSUE THREAD

**Issue by samuelp-mw** [jitsi/jitsi-meet#8875]
**Is your feature request related to a problem you are facing?**
New feature : Image/color background for a room

**Describe the solution you'd like**

I am currently working on a feature enabling to provide a user the ability to set a background for a room (image, color).
I already have a potential PR for that based on the external API and currently working on a UI to support this feature (the UI would be really similar to what is currently being implemented in virtual-background feature).

Would this feature be interesting as a new feature for Jitsi Meet?
If yes, are there some thoughts towards creating a common files/images storage so that multiple features could benefit from the work done on the virtual-background feature or eventually extend it?

**Describe alternatives you've considered**

**Comment by saghul** [comment]
We already have the ability to do that on a deployment basis: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L663-L678

Having UI elements for changing the background color individually is not something we think should be part of the user configuration.

**Comment by samuelp-mw** [comment]
> We already have the ability to do that on a deployment basis: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L663-L678
> 
> Having UI elements for changing the background color individually is not something we think should be part of the user configuration.

@saghul Thanks for your answer. I understand that this feature is not wished as part of the project. Just for completeness, I was especially targeting here the possibility to set the background of the room during the meeting for all the participants and not as a parameter of the deployment.
