### ISSUE TITLE
"Connecting you to your..." message is cropped

### ISSUE THREAD

**Issue by AymericLeFeyer** [jitsi/jitsi-meet#8877]
I have an application using the jitsi-meet sdk for Android
When I joined a room, I have a message "Connecting you to your server ..." but it is cropped
Image here :
![image-20210325-091310](https://user-images.githubusercontent.com/19204941/112458027-a2a28680-8d5c-11eb-9f93-61f6ab12cdc1.png)

Do you know how to custom the text cropping or maybe change/remove the message ? Because it's a bit ugly

The problem exists in versions 2.11 and 3.3.0 (at least)

**Comment by FarhatMaher** [comment]
I have the same problem !

**Comment by saghul** [comment]
What device do you see this on?

**Comment by AymericLeFeyer** [comment]
@saghul It's a TECLAST P10HD
A 10.1" screen with a 1920x1200 screen resolution
I can reproduce with devices where the screen is similar

**Comment by saghul** [comment]
I suspect there is something with the hardware, I cannot reproduce it with the Android devices I have at hand. Do you see something similar with the welcome page sliding menu?

**Comment by AymericLeFeyer** [comment]
The problem was my app theme
I put a different theme in my Jitsi Activity, now it's fixed
