### ISSUE TITLE
Unable to invoke on-screen keyboard to enter name in Jitsi app on iOS

### ISSUE THREAD

**Issue by stephendonner** [jitsi/jitsi-meet#8884]
### Description:

Unable to invoke on-screen keyboard to enter name in Jitsi app on iOS; the original Brave Together bug is filed here: https://github.com/brave/brave-together/issues/50

### Steps to reproduce:

(have the `Jitsu Meet` iOS app version `20.6.2` installed, first)

1. create a new meeting via desktop, from `together.bravesoftware.com`
2. copy the URL and open in Chrome or Safari (opening in Brave opens native, and we want Jitsu)
3. click on `Launch Jitsi Meet app`
4. when presented with the `Please enter your name here` dialog, tap on the placeholder text to try entering your name

### Expected behavior:

On-screen keyboard should pop-up and the user should be able to enter their name.

### Actual behavior:

Most of the time, nothing happens; no on-screen keyboard is invoked.

### Client information:

- Browser / app version: Jitsi Meet 20.6.2.
- Operating System: iOS 14.5 public beta

**Comment by tmoldovan8x8** [comment]
Hi @stephendonner thanks for pointing this to us. We have fixed it and will be available in the next release.

**Comment by mrose17** [comment]
8x8 indicates that a fix is available via testflight... when it is on the app store, this issue will be closed!

**Comment by stephendonner** [comment]
@mrose17: I can confirm that this is fixed using `Jitsi Meet` version `21.0.0 (110)` joining from my iPhone 8 Plus (iOS `14.5` public beta) on `https://together.bravesoftware.com/NHVmPZMMOvayi763gxqZs2EGXRXw_EMb00LgZVYSdYk` 👍 

![IMG-4844](https://user-images.githubusercontent.com/387249/113065992-952b3900-916e-11eb-9d40-8e894cabd44c.PNG)
