### ISSUE TITLE
Missing or incomplete Unicode support �

### ISSUE THREAD

**Issue by robert-scheck** [jitsi/jitsi-meet#8893]
### Description:
When using a unicode character such as 🐧, it's displayed wrongly by Jitsi as � (unicode replacement character used to replace an unknown, unrecognized or unrepresentable character):

![image](https://user-images.githubusercontent.com/10982488/112683129-63b22500-8e71-11eb-942a-50c42ccc3ce0.png)

### Steps to reproduce:

1. Visit https://meet.jit.si/
2. Use "R 🐧" as display name
3. See result from description

### Expected behavior:
R 🐧

### Actual behavior:
R �

### Server information:
https://meet.jit.si/ as of today.

### Client information:
Browser: Chrome stable (latest), Chromium stable (latest), Firefox (latest), Firefox ESR (latest)

### Additional information:
The character itself works across the whole system and in the browsers, including in other (non-Jitsi) web meeting solutions. If you look carefully, you can even see the 🐧 in the small box in the upper right corner (`R 🐧 (me)`).

**Comment by lichtheini** [comment]
Hello robert-scheck,
according to [stackoverflow](https://stackoverflow.com/questions/52526719/javascript-substring-without-splitting-emoji) the error lies in the shortening of the string [here (getInitials)](https://github.com/jitsi/jitsi-meet/blob/e38ebc6628f3e1cae852eb03c3e9baaa74d664d8/react/features/base/avatar/functions.js#L50). Also the length check is not always working for all unicode characters.

I tried some variants in codepen with chrome on windows with the following snippet:

```javascript
// needs lodash and this html:
// <code id=log>log</code>
var div = document.getElementById('log');

let s = "द्धeter 🖤 Ⓟarker🤤 🛑⏳ @ ✔";
  div.innerHTML += '<br>input string: ' + s;
const initialsBasis = _.split(s, '@')[0];
  div.innerHTML += '<br>basis: ' + initialsBasis;
const words = _.words(initialsBasis);
  div.innerHTML += '<br>words: ' + words;

let initials = '';
for (const w of words) {
  // original 
  // @source https://github.com/jitsi/jitsi-meet/blob/e38ebc6628f3e1cae852eb03c3e9baaa74d664d8/react/features/base/avatar/functions.js#L50
  // (initials.length < 2) && (initials += w.substr(0, 1).toUpperCase());

  // working version
  // @source https://stackoverflow.com/questions/52526719/javascript-substring-without-splitting-emoji
  (Array.from(initials).length < 2) && (initials += Array.from(w).slice(0, 1).join('').toUpperCase());

  // lodash version
  //(Array.from(initials).length < 2) && (initials += _.truncate(w, {'length': 1,  'omission': ''}).toUpperCase());

  div.innerHTML += '<br> for word ' + w + " the initial is " + initials;
}
```
Maybe it's enough to change line 50 in [functions.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/avatar/functions.js) to 
```
  (Array.from(initials).length < 2) && (initials += Array.from(w).slice(0, 1).join('').toUpperCase());
```

**Comment by robert-scheck** [comment]
Hello @lichtheini, thank you very much for your analysis and that this is likely a multi-byte related issue (at least that's my understanding). Given this issue happens on https://meet.jit.si/, I would be happy if Jitsi upstream could take care about.

**Comment by saghul** [comment]
This has been fixed now, cheers!
