### ISSUE TITLE
Jitsi Meet Iframe Moderation Bug - Cannot Accept Knocking Invite

### ISSUE THREAD

**Issue by Rileymoore25** [jitsi/jitsi-meet#8894]
https://user-images.githubusercontent.com/19480543/112685036-347bc380-8e31-11eb-9dd3-bf8e7e3dd105.mp4

![jitsibug](https://user-images.githubusercontent.com/19480543/112685042-38a7e100-8e31-11eb-8990-101eb4bb797c.png)

Hello,

I have noticed a bug since the recent UI update was released for the Jitsi Meet Iframe.

When using moderation and being the only one in the meeting, the “You are the only one in the meeting” with “Invite More People” button popup covers the Knocking Participant List. This makes it so you cannot accept or decline those looking to join the meeting.

It seems that if the popup saying you are the only one in the meeting is moved back to the top as it previously was, it should resolve the issue. What may be cleanest and make the most sense, is to hide the pop-up when the knocking participant list is present.

I have included a screenshot and video you can see above. I like many others I’m sure have functionality in my project that is now broken because of this and updates we’d love to release that are being held up because of tis.

I appreciate the help and look forward to seeing this resolved.

Thanks,
Riley

**Comment by saghul** [comment]
Ping @vp8x8

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/eb41a306a6dfcecc841aa771ecfb3bd89e341db4
