### ISSUE TITLE
Fullscreen toggling keyboard shortcut ("S") should be switched with thumbnails sidebar shortcut ("F")

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet#8897]
Using the current Jitsi Meet web version from meet.jit.si or the Electron app for desktop (obtained from Flathub on Linux), I noticed today that the keyboard shortcuts for fullscreen and for thumbnails don't really make sense, in the English version at least.

Currently, "F" is for toggling the thumbnails sidebar on/off, and "S" is for fullscreen".

It would make so much more sense if it was F = **F**ullscreen and S = **S**idebar... not only is F a somewhat standard shortcut (alongside "F11") in most other apps, this would also make the shortcuts match the first letters of those words.

**Comment by nekohayo** [comment]
Still an issue, I think F for fullscreen and S for sidebar would make much more sense at least in English and as per established standards from other apps.

**Comment by nekohayo** [comment]
In addition to the `F` key, I'd recommend allowing the `F11` key to be used for fullscreening as well, as both are pretty much standard.

**Comment by saghul** [comment]
I'm going to close this, it shall remain as is, for historical reasons.

F is for filmstrip.
S is for screen.

I know, I know, probably not the best choices, but that's what everyone is used to at this point, and changing it would cause a lot of churn.

**Comment by nekohayo** [comment]
Well, for what it's worth, culturally I don't think most people think "**f**ilmstrip" when they see the **s**idebar of thumbnails... unless they have worked for years in L.A./Hollywood. Those technical enough to know the shortcuts are people who are rather apt to learn, and they can readjust to new shortcuts that are brought in line with other applications' commonly established shortcuts for fullscreen, but anyway that's just my 2¢.

What about also allowing the F11 key for fullscreen though? Would that still be feasible independently of the choice of F vs S?

**Comment by saghul** [comment]
> Well, for what it's worth, culturally I don't think most people think "**f**ilmstrip" when they see the **s**idebar of thumbnails... unless they have worked for years in L.A./Hollywood. Those technical enough to know the shortcuts are people who are rather apt to learn, and they can readjust to new shortcuts that are brought in line with other applications' commonly established shortcuts for fullscreen, but anyway that's just my 2¢.

I agree.



> What about also allowing the F11 key for fullscreen though? Would that still be feasible independently of the choice of F vs S?

Yep, that should be an easy addition I think, care to send  PR?
