### ISSUE TITLE
App do not start with Firefox ESR

### ISSUE THREAD

**Issue by mazhe** [jitsi/jitsi-meet#8900]
### Description:

When using Firefox ESR (currently version 78.9, observed on MacOS and FreeBSD), an empty frame is displayed. The web console will report the following:

```
(TIME) index.html loaded:	 432 (meet.jit.si:56:17)
2021-03-28T09:52:53.507Z [modules/browser/BrowserCapabilities.js] This appears to be firefox, ver: 78.0 (Logger.js:154:22)
Uncaught ReferenceError: WebAssembly is not defined (wasm-check.min.js:1:203)
    <anonymous> wasm-check.min.js:1
    Webpack 47
Uncaught TypeError: JitsiMeetJS.app.entryPoints is undefined (meet.jit.si:29:17)
    <anonymous> https://meet.jit.si/:29
```

Upgrading Firefox is not an option in some cases/configuration, especially since it is then impossible to revert to ESR because user profiles have been updated to a newer version...

### Steps to reproduce:

1. Open Firefox ESR
2. Go to https://meet.jit.si/

### Expected behavior:

Load and use jitsi-meet website

### Actual behavior:

Nothing happens, no errror message. Only the webconsole output above.

### Server information:

- Jitsi Meet version: https://meet.jit.si/
- Operating System: https://meet.jit.si/

### Client information:

- Browser / app version: Firefox ESR 78.9
- Operating System: tested with MacOS 11.4, FreeBSD 13.0

### Additional information:

Obviously seems to be related with webassembly requirements.

**Comment by saghul** [comment]
Looks like WASM is disabled on your build. Did you intentionally do this?

**Comment by mazhe** [comment]
Thanks for looking at this issue,

Oh, the build are regular, but I checked all options and at some point I must have used the about:config javascript.options.wasm option on both system to restrict wasm usage... My bad, I thought the last update bumped the requirements, but everything seems to work again.
