### ISSUE TITLE
Input sensitivity slider

### ISSUE THREAD

**Issue by monstro1** [jitsi/jitsi-meet#8902]
I absolutely love jitsi but, when talking to some of my friends with poorer quality mics, I hear a lot of background noise (where I wouldn't be if I were calling them on Discord.) It's bad enough that it's basically the only thing preventing me from uninstalling Discord and also shilling Jitsi to all my friends as hard as I possibly can. Some way to adjust my input sensitivity (similar to the input sensitivity slider in programs like discord) would be greatly appreciated.

**Comment by fremzy** [comment]
Do you think adjusting the volume of the specific user could help?
