### ISSUE TITLE
Enormous leap in App size from version 20.4.2 -> 20.5.0+ and later versions

### ISSUE THREAD

**Issue by jwmh** [jitsi/jitsi-meet#8903]
Fdroid repo:
* 20.4.2 APK size = ~29mb
* 20.5.0 APK size = ~80mb

See also issue #7845
(Possible duplicate)

I have remained on 20.4.2,
because I cannot afford the extra disk usage.

This is unsustainable for users of low-end and budget devices,
e.g. a cheap $40 phone
(myself).

**Comment by saghul** [comment]
This is indeed a duplicate. See the reasoning in https://github.com/jitsi/jitsi-meet/issues/7845#issuecomment-809143921

I think the Play store build would be smaller because they split it by ABI.
