### ISSUE TITLE
Request: independent setting for recording-quality per recording

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#8912]
**Is your feature request related to a problem you are facing?**

I sometimes care about higher-quality recordings and sometimes it's just to reference the content of a call but the quality doesn't matter. In the latter case, the priority is to have just good enough and minimize file size.

**Describe the solution you'd like**

I imagine a UI control during calls that is similar to the "manage video quality" setting. Perhaps it's just the same exact view, it just adds a second slider for "recording quality". If necessary (I don't know the technical issues), the recording quality could be limited to being only the call quality or lower.

Incidentally, this approach would solve https://github.com/jitsi/jitsi-meet/issues/8208 and that wouldn't need to exist as its own feature.

**Describe alternatives you've considered**

To reduce file sizes, I often separately compress later. I know that a server setting could be adjusted, but that's not practical to adjust on the fly from call to call.

**Comment by wolftune** [comment]
This isn't outdated, I think this is still worth doing!

**Comment by wolftune** [comment]
I still say this should happen, and I'd rather a human won't-fix decision (or better fixing it) rather than just going stale

**Comment by saghul** [comment]
I don't think we have this in our roadmap, sorry.
