### ISSUE TITLE
New Multiple Moderators functionality is not working fine on my Local(working on meet.jit.si).

### ISSUE THREAD

**Issue by shweta21** [jitsi/jitsi-meet#8914]
Multiple Moderators functionality is working on meet.jit.si link but i took clone of same. it's not working on my Local.
![aa](https://user-images.githubusercontent.com/10355195/112949658-1971c200-9157-11eb-9d47-fb5d29f84039.png)
![ss](https://user-images.githubusercontent.com/10355195/112949682-1d9ddf80-9157-11eb-83a6-c055c576d335.png)

**Comment by damencho** [comment]
Please when you have questions or problems use rhe community forum before opening new issues, thank you.

If you are using the dev webpack proxy, that by default uses an environment called alpha.jitsi.net where the default quick install configuration is running woth single moderator.
If you want all moderators, use your deployment and enable allowners prosody module.

**Comment by shweta21** [comment]
> Please when you have questions or problems use rhe community forum before opening new issues, thank you.
> 
> If you are using the dev webpack proxy, that by default uses an environment called alpha.jitsi.net where the default quick install configuration is running woth single moderator.
> If you want all moderators, use your deployment and enable allowners prosody module.

Thank you
