### ISSUE TITLE
Translation when user denied permissions

### ISSUE THREAD

**Issue by veselinovicst** [jitsi/jitsi-meet#8919]
Hi there,

We are using an implementation of Jitsi in Dutch and have modified many translations in our customizations. However, there is one message in English that does not seem to be modifiable.

When a user rejects the permissions to use audio/video the following error message is shown.
This message is part Dutch and part English. We are able to configure the first part (Audio- en videofout:), but it does not seem to be possible to modify the second part (user denied permission to use device(es): audio, video.

Wondering if this is possible to change to Dutch as well?
The screenshot is from meet.jit.see, using a Chrome set to dutch

![sc1](https://user-images.githubusercontent.com/24300198/112999101-f05d2b80-916e-11eb-99a5-9d4fbec06bd9.png)

**Comment by damencho** [comment]
The correct way to handle this is to make publicly accessible [TRACK_ERROR_TO_MESSAGE_MAP](https://github.com/jitsi/lib-jitsi-meet/blob/054fbdf45f2fddad4ca0052be3ca4bb8d528ae0f/JitsiTrackError.js#L3) outside the library and here compare error messages to the value of TRACK_ERROR_TO_MESSAGE_MAP and load it from the i18n translations.

**Comment by damencho** [comment]
We don't have immediate plans to handle this, but any PRs are welcome.
