### ISSUE TITLE
Allow to configure room affiliation in JWT auth

### ISSUE THREAD

**Issue by lunika** [jitsi/jitsi-meet#8923]
**Is your feature request related to a problem you are facing?**

We are using the JWT prosody plugin to authenticate users in our system. We would like to manage affiliation from the token itself

**Describe the solution you'd like**

We would like to assign the affiliation in the payload and change the user affiliation when he joins a room.

```
{
  "context": {
    "user": {
      "avatar": "https:/gravatar.com/avatar/abc123",
      "name": "John Doe",
      "email": "jdoe@example.com",
      "id": "abcd:a1b2c3-d4e5f6-0abc1-23de-abcdef01fedcba"
    },
    "group": "a123-123-456-789"
  },
  "aud": "jitsi",
  "iss": "my_client",
  "sub": "meet.jit.si",
  "room": "*",
  "affiliation": "moderator",
  "exp": 1500006923
}
```

**Comment by ohens** [comment]
If you mean making a user a moderator via JWT, we are doing the same thing with the help of the [token_moderation](https://github.com/nvonahsen/jitsi-token-moderation-plugin) plugin for prosody. Maybe that's what you are looking for? Works well for us.

**Comment by lunika** [comment]
> If you mean making a user a moderator via JWT, we are doing the same thing with the help of the [token_moderation](https://github.com/nvonahsen/jitsi-token-moderation-plugin) plugin for prosody. Maybe that's what you are looking for? Works well for us.

Thank you for your answer. Yes this is the kind of feature we are looking for.
I also found the module [token_affiliation](https://github.com/emrahcom/emrah-buster-templates/blob/master/machines/eb-jitsi/usr/share/jitsi-meet/prosody-plugins/mod_token_affiliation.lua), and it works for my use case. Maybe you can tell the difference between the two modules ?
Thanks

**Comment by ohens** [comment]
No idea, I haven't tried the token_affiliation plugin because it didn't exist when we customized our deployment. But the community forum seems to have some insights on the difference [here](https://community.jitsi.org/t/new-prosody-modules-to-control-a-tokenized-room-token-affiliation-and-token-owner-party/79962/32).
