### ISSUE TITLE
Dim camera

### ISSUE THREAD

**Issue by kousu** [jitsi/jitsi-meet#8929]
### Description:

Jitsi Meet leaves my camera at its darkest setting.

### Steps to reproduce:

1. Make a new meeting on https://meet.jit.si
2. Enable the camera
3. The video is very dark

### Expected behavior:

The video should be usable.

### Actual behavior:

The video is too dark to see.

![Dim in Firefox](https://user-images.githubusercontent.com/987487/113234269-f0445500-926e-11eb-928e-c0f29d45ad8e.png)
![Dim in Chrome](https://user-images.githubusercontent.com/987487/113234271-f1758200-926e-11eb-94ae-1c7fae5a4e5e.png)

My webcam is fine in Cheese:

![Fine in Cheese](https://user-images.githubusercontent.com/987487/113234492-5df08100-926f-11eb-9745-88416f47a5ac.png)

### Server information:

- Jitsi Meet version: whatever is currently on meet.jit.si
- Operating System: ??

### Client information:

- Browser / app version: Firefox 87.0 (64-bit) and Chromium 89.0.4389.114 (64-bit)
- Operating System: ArchLinux

### Additional information:

I'm using `uvcvideo` with an extremely recent kernel.

Jitsi *used* to work fine on this laptop.

```
$ uname -a
Linux requiem 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux
```

```
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

```
$ ls -l /sys/class/video4linux/video*/device/driver/
/sys/class/video4linux/video0/device/driver/:
total 0
lrwxrwxrwx 1 root root    0 Mar 31 22:23 1-1.6:1.0 -> ../../../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6:1.0
lrwxrwxrwx 1 root root    0 Mar 31 22:23 1-1.6:1.1 -> ../../../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6:1.1
--w------- 1 root root 4096 Mar 31 22:23 bind
lrwxrwxrwx 1 root root    0 Mar 31 22:23 module -> ../../../../module/uvcvideo
-rw-r--r-- 1 root root 4096 Mar 31 22:23 new_id
-rw-r--r-- 1 root root 4096 Mar 31 22:23 remove_id
--w------- 1 root root 4096 Mar 31 22:06 uevent
--w------- 1 root root 4096 Mar 31 22:23 unbind

/sys/class/video4linux/video1/device/driver/:
total 0
lrwxrwxrwx 1 root root    0 Mar 31 22:23 1-1.6:1.0 -> ../../../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6:1.0
lrwxrwxrwx 1 root root    0 Mar 31 22:23 1-1.6:1.1 -> ../../../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6:1.1
--w------- 1 root root 4096 Mar 31 22:23 bind
lrwxrwxrwx 1 root root    0 Mar 31 22:23 module -> ../../../../module/uvcvideo
-rw-r--r-- 1 root root 4096 Mar 31 22:23 new_id
-rw-r--r-- 1 root root 4096 Mar 31 22:23 remove_id
--w------- 1 root root 4096 Mar 31 22:06 uevent
--w------- 1 root root 4096 Mar 31 22:23 unbind
```

```
$ sudo dmesg | grep -i video
[    0.165699] ACPI: Added _OSI(Linux-Dell-Video)
[    0.232264] pci 0000:00:02.0: Video device with shadowed ROM at [mem 0x000c0000-0x000dffff]
[    3.771654] thinkpad_acpi: This ThinkPad has standard ACPI backlight brightness control, supported by the ACPI video driver
[    3.990483] videodev: Linux video capture interface: v2.00
[    4.273573] uvcvideo: Found UVC 1.00 device Integrated Camera (04f2:b2da)
[    4.289087] usbcore: registered new interface driver uvcvideo
[    4.289090] USB Video Class driver (1.1.1)
[    4.715484] ACPI: Video Device [VID] (multi-head: yes  rom: no  post: no)
[    4.715746] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input20
[    4.741122] ACPI: Video Device [VID1] (multi-head: yes  rom: yes  post: no)
[    4.741435] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:09/LNXVIDEO:01/input/input21
$ lsusb
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 04f2:b2da Chicony Electronics Co., Ltd thinkpad t430s camera
Bus 001 Device 003: ID 0a5c:21e6 Broadcom Corp. BCM20702 Bluetooth 4.0 [ThinkPad]
Bus 001 Device 005: ID 194f:0102 PreSonus Audio Electronics, Inc. AudioBox 44 VSL
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 045e:0745 Microsoft Corp. Nano Transceiver v1.0 for Bluetooth
Bus 003 Device 002: ID 0518:0001 EzKEY Corp. USB to PS2 Adaptor v1.09
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by kousu** [comment]
I was able to work around it by using `qv4l2` (from [`v4l-utils`](https://archlinux.org/packages/?name=v4l-utils)). My default camera settings are:

![default camera settings](https://user-images.githubusercontent.com/987487/113235597-6053da80-9271-11eb-8180-62f29f2dcf3a.png)

Setting them to:

![improved camera settings](https://user-images.githubusercontent.com/987487/113235593-5fbb4400-9271-11eb-9745-609661835a73.png)

has made Jitsi usable:

![2021-03-31-224504_1888x904_scrot](https://user-images.githubusercontent.com/987487/113236407-c68d2d00-9272-11eb-93f4-f73c6ead1dc5.png)


By the way, if you need to use this workaround, it's important to note that you need to start Jitsi first, or switch back and forth between them, because otherwise `qv4l2` grabs the camera exclusively and doesn't let Jitsi open it.

**Comment by saghul** [comment]
Thanks for the detailed report! We just request the camera to Firefox, there is no brightness API that we have access to. So I'm a bit perplexed by what's happening here. Can you test Chromium? Do you see any difference?

**Comment by saghul** [comment]
Note that in the pre-join screen there is a gradient that will make things look a bit dimmer.

**Comment by kousu** [comment]
I'm perplexed too! The second screenshot above is from Chromium and I took both in the actual chat. I tried out https://test.webrtc.org but it doesn't show any images. I don't know what other app I could test with. Maybe Discord?

But also now after sleeping my laptop now I can't reproduce it. I reset the v4l controls back to their defaults:

```
$ v4l2-ctl --list-ctrls
                     brightness 0x00980900 (int)    : min=-64 max=64 step=1 default=-16 value=-16
                       contrast 0x00980901 (int)    : min=0 max=95 step=1 default=28 value=28
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=40 value=40
                            hue 0x00980903 (int)    : min=-180 max=180 step=1 default=0 value=0
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=48 max=300 step=1 default=100 value=100
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=2 value=2
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=1 default=4600 value=4600 flags=inactive
                      sharpness 0x0098091b (int)    : min=1 max=7 step=1 default=1 value=1
         backlight_compensation 0x0098091c (int)    : min=0 max=2 step=1 default=0 value=0
                  exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute 0x009a0902 (int)    : min=1 max=5000 step=1 default=333 value=333 flags=inactive
         exposure_auto_priority 0x009a0903 (bool)   : default=0 value=0
                   pan_absolute 0x009a0908 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  tilt_absolute 0x009a0909 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  zoom_absolute 0x009a090d (int)    : min=0 max=10 step=1 default=0 value=0
                        privacy 0x009a0910 (bool)   : default=0 value=0
```

and the camera stays fine:

Firefox:

![2021-04-01-083930_1919x1079_scrot](https://user-images.githubusercontent.com/987487/113295316-0fba9c80-92c6-11eb-80b6-922f24cbf22f.png)

Chrome:

![2021-04-01-084010_1916x1059_scrot](https://user-images.githubusercontent.com/987487/113295319-10533300-92c6-11eb-813e-28074b4a0439.png)

I'll try rebooting in a moment to see if I can reproduce it then.

**Comment by kousu** [comment]
By the way, it's always been fine on my Ubuntu laptop:

![ubuntu](https://user-images.githubusercontent.com/987487/113296955-14805000-92c8-11eb-8eb3-9cb340644d5e.png)

This laptop is running an older kernel:

```
$ uname -a
Linux ail 4.16.18-galliumos #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 480M
    |__ Port 3: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 3: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 4: Dev 3, If 1, Class=Wireless, Driver=btusb, 12M
    |__ Port 4: Dev 3, If 0, Class=Wireless, Driver=btusb, 12M

$ ls -l /sys/class/video4linux/video0/device/driver/
total 0
lrwxrwxrwx 1 root root    0 Apr  1 08:07 1-3:1.0 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0
lrwxrwxrwx 1 root root    0 Apr  1 08:07 1-3:1.1 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1
--w------- 1 root root 4096 Apr  1 08:07 bind
lrwxrwxrwx 1 root root    0 Apr  1 08:07 module -> ../../../../module/uvcvideo
-rw-r--r-- 1 root root 4096 Apr  1 08:07 new_id
-rw-r--r-- 1 root root 4096 Apr  1 08:07 remove_id
--w------- 1 root root 4096 Apr  1 08:07 uevent
--w------- 1 root root 4096 Apr  1 08:07 unbind
```

and it has different controls; in particular, the auto exposure control says its default is "3" not "0":

```
$ v4l2-ctl -d /dev/video0 --list-ctrls
                     brightness 0x00980900 (int)    : min=-64 max=64 step=1 default=0 value=0
                       contrast 0x00980901 (int)    : min=0 max=95 step=1 default=0 value=0
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=64 value=64
                            hue 0x00980903 (int)    : min=-2000 max=2000 step=1 default=0 value=0
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=100 max=300 step=1 default=100 value=100
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=1 value=1
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=1 default=4600 value=4600 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=7 step=1 default=2 value=2
         backlight_compensation 0x0098091c (int)    : min=0 max=1 step=1 default=1 value=1
                  exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute 0x009a0902 (int)    : min=10 max=2047 step=1 default=384 value=384 flags=inactive
```

---

--

It's also fine under kali linux. This laptop is running a newer kernel, but not as new as the Arch laptop, and it also has the older controls, particularly, `exposure_auto default=3`.


    kali@kali:~$ uname -a
    Linux kali 5.8.0-kali3-amd64 #1 SMP Debian 5.8.14-1kali1 (2020-10-13) x86_64 GNU/Linux
    kali@kali:~$ lsusb -t
    /:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
        |__ Port 3: Dev 2, If 0, Class=Hub, Driver=hub/3p, 5000M
    /:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/9p, 480M
        |__ Port 3: Dev 2, If 0, Class=Hub, Driver=hub/3p, 480M
        |__ Port 4: Dev 3, If 0, Class=Wireless, Driver=btusb, 12M
        |__ Port 4: Dev 3, If 1, Class=Wireless, Driver=btusb, 12M
        |__ Port 7: Dev 4, If 1, Class=Video, Driver=uvcvideo, 480M
        |__ Port 7: Dev 4, If 0, Class=Video, Driver=uvcvideo, 480M
    /:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/3p, 480M
        |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M

    kali@kali:~$ v4l2-ctl -d /dev/video0 --list-ctrls
                         brightness 0x00980900 (int)    : min=-64 max=64 step=1 default=0 value=0
                           contrast 0x00980901 (int)    : min=0 max=64 step=1 default=32 value=32
                         saturation 0x00980902 (int)    : min=0 max=128 step=1 default=64 value=64
                                hue 0x00980903 (int)    : min=-40 max=40 step=1 default=0 value=0
     white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                              gamma 0x00980910 (int)    : min=72 max=500 step=1 default=100 value=100
               power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=1 value=1
          white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=1 default=4000 value=4000 flags=inactive
                          sharpness 0x0098091b (int)    : min=0 max=5 step=1 default=3 value=3
             backlight_compensation 0x0098091c (int)    : min=0 max=1 step=1 default=0 value=0
                      exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
                  exposure_absolute 0x009a0902 (int)    : min=40 max=10000 step=1 default=1280 value=1280 flags=inactive
             exposure_auto_priority 0x009a0903 (bool)   : default=0 value=1

So I'm leaning towards this not being a Jitsi-specific bug afterall, but something with the latest `uvcvideo`.

**Comment by kousu** [comment]
I've rebooted three times and I can't reproduce this anymore, even with the default settings:

```
$ v4l2-ctl -l
                     brightness 0x00980900 (int)    : min=-64 max=64 step=1 default=-16 value=-16
                       contrast 0x00980901 (int)    : min=0 max=95 step=1 default=28 value=28
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=40 value=40
                            hue 0x00980903 (int)    : min=-180 max=180 step=1 default=0 value=0
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=48 max=300 step=1 default=100 value=100
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=2 value=2
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=1 default=4600 value=4600 flags=inactive
                      sharpness 0x0098091b (int)    : min=1 max=7 step=1 default=1 value=1
         backlight_compensation 0x0098091c (int)    : min=0 max=2 step=1 default=0 value=0
                  exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute 0x009a0902 (int)    : min=1 max=5000 step=1 default=333 value=166 flags=inactive
         exposure_auto_priority 0x009a0903 (bool)   : default=0 value=0
                   pan_absolute 0x009a0908 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  tilt_absolute 0x009a0909 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  zoom_absolute 0x009a090d (int)    : min=0 max=10 step=1 default=0 value=0
                        privacy 0x009a0910 (bool)   : default=0 value=0
```

I don't know what happened. It seems like turning auto exposure on and off a couple times has flicked some state inside my camera hardware itself. If it comes back I'll reopen.

**Comment by saghul** [comment]
Good to know!
