### ISSUE TITLE
Flashing screen on user join

### ISSUE THREAD

**Issue by jacksongoode** [jitsi/jitsi-meet#8933]
I've noticed after some recent updates (maybe with the new UI) the entire webpage flashes/refreshes when a new participant joins on any web browser. My instance is custom, but it only really effecting the audio track. I can't see anything in the logs that might point to the cause.

My instance is at meet.jacksongoo.de.

**Comment by saghul** [comment]
Do you see this in all browsers?

**Comment by jacksongoode** [comment]
> Do you see this in all browsers?

Yes, I've tried on FF and Chrome.
