### ISSUE TITLE
"Trying to speak? You are muted." pops up over and over again in push to talk mode

### ISSUE THREAD

**Issue by Florz** [jitsi/jitsi-meet#8939]
### Description:
When using push to talk mode (space bar) or when unmuting briefly (m key or onscreen button) there is a popup as soon as the user mutes again and makes some noise. Additionally this popup comes with an annoying sound.

### Steps to reproduce:
1. in any jitsi session mute yourself
2. use any method to unmute and speak
3. use any method to mute again
4. make some noise
5. popup "Trying to speak? You are muted." and sound will appear
6. repeat from step 2
7. same effect
…

### Expected behavior:
This notification should only appear if the user is not aware that he might be muted (e.g. if a moderator muted him or if the room is muted by default). The notification should be disabled for the rest of the session if the user correctly uses the space bar or the other options to unmute and then mute again. In most sessions this should happen right after the user joins a channel and says hello.
If a user actively chooses to mute himself in an otherwise unmuted room this should also not lead to a notification.

### Actual behavior:
Frequent notifications which drive experienced users crazy: Users feel patronized by their own computer because they made some noise, although they muted themselves for exactly that reason.

### Server information:
experienced on several servers with recent jitsi versions

### Client information:
Chromium 89, Debian bullseye

### Additional information:
This ticket tries to describe what was missed under https://github.com/jitsi/jitsi-meet/issues/6100#issuecomment-758730014

**Comment by fremzy** [comment]
The other side to this though - and likely the reason behind having the current behavior - is that oftentimes people forget they're muted and then try to speak. The notification is a useful reminder and it only shows up once in a muted state - once dismissed, it doesn't show up again unless the user unmutes and then mutes back. I think it's logical the way it works now.

**Comment by Florz** [comment]
Jitsi allows me to use the space bar for push to talk mode. I deliberately use this to unmute myself while I want to talk. I am totally aware that I am muted. While muted deliberately I want to be able to talk to someone else in the room without being annoyed by this sound and the popup window.
The warning would be fine if it showed up once during a meeting but it becomes extremely annoying if it shows up each time after I let go the space bar. Just imagine an active conversation where you speak every few seconds and each time you are back muted, some noise in your room triggers this sound.

**Comment by n7ipb** [comment]
One of,  if not the most common comment by my meeting users is how do I get rid of this popup.

I understand the rational for some meetings but it still needs an override option.  The default at the start of a meeting should have the popup enabled but if an attendee sets it to disable it should stay that way until a new meeting is joined.  Put a flag in settings or in the popup itself that turns it off.

**Comment by n7ipb** [comment]
Still a problem and just as annoying.
