### ISSUE TITLE
Unable to hide the 3 dot menu in jitsi meet SDK android 

### ISSUE THREAD

**Issue by pareshsahoo902** [jitsi/jitsi-meet#8946]
**.setFeatureFlag("pip.enabled",false)
  .setFeatureFlag("toolbox.enabled",false)**
it must remove the 3-dot-menu in android SDK
![WhatsApp Image 2021-04-05 at 11 29 53 AM](https://user-images.githubusercontent.com/42085222/113545250-7530c500-9607-11eb-8ea3-6cee0476fc93.jpeg)

**Comment by saghul** [comment]
Check the overflow-menu.enabled flag: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js

**Comment by pareshsahoo902** [comment]
@saghul  i have checked it and used the "toolbox.enabled" flag still not working . it must hide the 3dot menu .
is there any other way ??

**Comment by saghul** [comment]
Please read my message, it's a different flag, I have you the name.

You also didn't mention what SDK version you're using, make sure it's the latest.
