### ISSUE TITLE
@saghul  i have checked it and used the "toolbox.enabled" flag still not working . it must hide the 3dot menu .

### ISSUE THREAD

**Issue by pareshsahoo902** [jitsi/jitsi-meet#8947]
@saghul  i have checked it and used the "toolbox.enabled" flag still not working . it must hide the 3dot menu .
is there any other way ??

_Originally posted by @pareshsahoo902 in https://github.com/jitsi/jitsi-meet/issues/8946#issuecomment-813235524_

**Comment by saghul** [comment]
Do NOT post duplicates.
