### ISSUE TITLE
In android ToolBox buttons not working

### ISSUE THREAD

**Issue by priyankahash** [jitsi/jitsi-meet#8948]
[JitsiMeetSDK:](url) [features/app] Error(TypeError){"message":"l.playTouchSound is not a function. facing this issue on clciking these butons #
![113485333-2b48c180-94d7-11eb-8a3c-b32afae4a9b7](https://user-images.githubusercontent.com/72809918/113549653-68b06a80-960f-11eb-8c14-9188d43d0251.png)

**Comment by saghul** [comment]
Please update to the latest SDK (3.3).

**Comment by priyankahash** [comment]
Still same issue

**Comment by dgreasi** [comment]
Any updates?

**Comment by riyas145** [comment]
Any Updates i'm not able view the button after connecting @alphatrl @saghul

**Comment by dgreasi** [comment]
Got the same error with @alphatrl. The solution for me was to update the react-native to **0.64.2** on the **jitsi-meet** project and rebuild the project. **0.64.2** uses the implementation **playTouchSound** from **SoundManager** lib.

**Comment by saghul** [comment]
I just finished updating the project to 0.63. It was a pain. I don't recommend using any version other than the one we explicitly depend on.

**Comment by rizbud** [comment]
> 

what did you mean rebuild the project? did you rebuild the jitsi/react-native?

**Comment by dgreasi** [comment]
I rebuild [jitsi-meet](https://github.com/jitsi/jitsi-meet). It is not a simple process.

You need to run build commands for android and iOS. After building the artifacts for each OS, i use them through [this](https://github.com/skrafft/react-native-jitsi-meet) react-native-wrapper.

**Comment by rizbud** [comment]
> I rebuild [jitsi-meet](https://github.com/jitsi/jitsi-meet). It is not a simple process.
> 
> You need to run build commands for android and iOS. After building the artifacts for each OS, i use them through [this](https://github.com/skrafft/react-native-jitsi-meet) react-native-wrapper.

so, the quick solution is downgrade the react native version?

**Comment by dgreasi** [comment]
> > I rebuild [jitsi-meet](https://github.com/jitsi/jitsi-meet). It is not a simple process.
> > 
> > You need to run build commands for android and iOS. After building the artifacts for each OS, i use them through [this](https://github.com/skrafft/react-native-jitsi-meet) react-native-wrapper.
> 
> so, the quick solution is downgrade the react native version?

Yes. You need react-native < 0.64.0
