### ISSUE TITLE
Android 11 Show white screen after Joining in room

### ISSUE THREAD

**Issue by mssNitish** [jitsi/jitsi-meet#8949]
### Description:

I have got an issue with Android 11 when I try to join with two Android devices OS version 11 then we got a white screen issue(UI of the screen is not rending). please let me know what's issue with Android 11.

### Steps to reproduce:

1.Install Jisti app's on Two Android devices OS11
2. Join a meeting 
3. Showing white screen after joined meeting with OS 11 Android
4. Issue with only Android 11

### Expected behavior:

Need to show complete UI after joining the call 

### Client information:

- Operating System: Android 11 

### Additional information:

Please suggest me what's wrong with Android 11

**Comment by saghul** [comment]
Are you using the SDK in your own app or the Jitsi Meet app? Do you see anything in adb logcat?

**Comment by mssNitish** [comment]
We are using the SDK of Jitsi in our application. In logcat no error is showing please check video this error is facing in android 11
https://drive.google.com/file/d/1tOWS5R96Ixr53gC4B-ba_USHQpR7cii4/view?usp=sharing

**Comment by saghul** [comment]
Can you reproduce this with the Jitsi Meet app?

**Comment by mssNitish** [comment]
we are using code likes as 
try {
view=null
view = JitsiMeetView(this)
val builder = JitsiMeetConferenceOptions.Builder()
.setRoom("https://meet.jit.si/"+mCallParentId)
if(jCalltype.equals("Audio")){
builder.setVideoMuted(true)
// builder.set
}

builder
.setFeatureFlag("chat.enabled",false)
.setFeatureFlag("invite.enabled",false)
.setFeatureFlag("add-people.enabled",false)
.setFeatureFlag("calendar.enabled",false)
.setFeatureFlag("live-streaming.enabled",false)
.setFeatureFlag("raise-hand.enabled",false)
.setFeatureFlag("recording.enabled",false)
// .setFeatureFlag("video-share.enabled",false)
.setFeatureFlag("toggleLobby.enabled",false)
.setFeatureFlag("recording.enabled",false)
.setFeatureFlag("meeting-password.enabled",false)
.setFeatureFlag("desktop.disabled",true)
.setFeatureFlag("tile-view.enabled",true)
.setFeatureFlag("meeting-name.enabled",false)

val jitsiMeetUserInfo = JitsiMeetUserInfo()
jitsiMeetUserInfo.displayName =jUserName
builder.setUserInfo(jitsiMeetUserInfo)
val options = builder.build()
val handler = Handler()
view!!.join(options)


view!!.listener = object : JitsiMeetViewListener {
override fun onConferenceJoined(map: Map<String, Any>) {
Log.e("onConferenceJoined", map.toString())
//mkmk toast.maketext(this@mainactivity,"joined",toast.length_long).show()
rl_video.visibility = View.VISIBLE
viewVisible()
// chronometer.start();

// topview.visibility = View.GONE
}
override fun onConferenceTerminated(map: Map<String, Any>) {
Log.e("onConferenceTerminated", map.toString())
drawer_layout.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);


closeJitsiView()
{
Log.e("JITSIACTIVITY","view not null is called");
view!!.leave()
application.setCallStatus(BaseApplication.CallStatus.CALLEND)
viewVisible()
}
else
{
Log.e("JITSIACTIVITY","view not else else is called");
}*/


}
override fun onConferenceWillJoin(map: Map<String, Any>) {
Log.e("onConferenceWillJoin", map.toString())
}
}
rl_video.addView(view)

}catch (e:Exception){
Log.e("exception",e.toString())
}

Might be an issue in the code please suggest to me. this way is okay or not?

**Comment by saghul** [comment]
You need to wire the view to the activity with the lifecycle methods, via the activity delegate. Have you done that? Any reason why you are not using JitsiMeetActivity directly?

**Comment by mssNitish** [comment]
We need to add some options at top of the page that's why we are using view if you have any suggestion regarding the above code please let us know

**Comment by saghul** [comment]
Then you need to wire the activity lifecycle methods as our activity / fragment does, please check the code.
