### ISSUE TITLE
LIBRE_BUILD sdk still pulls in gms dependencies

### ISSUE THREAD

**Issue by Bubu** [jitsi/jitsi-meet#8956]
I've been investigating the element-android containing proprietary gms libraries again through the use of the jitsi-meet sdk, even though it's explicitly using an sdk built with `LIBRE_BUILD=true`.

I believe this is happening because jitsi-meet sdk is now unconditionally including a library that (optionally?) depends on gms libs and only conditionally excluding these transitive dependencies. Previously it only conditionally included the libs in the not-LIBRE variant. See here: https://github.com/jitsi/jitsi-meet/blob/7a64bf006ea027b77564d8847570e1ac46ff0ec0/android/sdk/build.gradle#L53

Unfortunately the exclusion rules don't propagate to consumers of the sdk, which need to be aware of the latest jitsi exclusion rules and apply them to the jitsi dependency themselves. I'd hope there's a way of excluding these transitive dependencies at the jitsi sdk level, so I'm not sure how exactly. Maybe a modified (excluding the proprietary dependencies from the pom file) version of the `react-native-device-info` dependency could be published to the maven repo if we are doing a libre build?

Fix at element-android side: https://github.com/vector-im/element-android/pull/3125

I'd appreciate your input, @saghul :-).

**Comment by saghul** [comment]
> I believe this is happening because jitsi-meet sdk is now unconditionally including a library that (optionally?) depends on gms libs and only conditionally excluding these transitive dependencies. Previously it only conditionally included the libs in the not-LIBRE variant. See here:

That sounds about right. That library does depend on some non-libre libraries for non-core functionality we don't use. I made a couple of PRs to make sure that library worked to the extent we needed, in a libre build: https://github.com/react-native-device-info/react-native-device-info/commits?author=saghul



> Unfortunately the exclusion rules don't propagate to consumers of the sdk, which need to be aware of the latest jitsi exclusion rules and apply them to the jitsi dependency themselves.

That's unfortunate :-( TBH the libre build was conceived for the F-Droid build, others consuming the SDK this way wasn't in my mind.

> I'd hope there's a way of excluding these transitive dependencies at the jitsi sdk level, so I'm not sure how exactly.

I don't know either, but if there is one, I'd be happy to incorporate it.

> Maybe a modified (excluding the proprietary dependencies from the pom file) version of the `react-native-device-info` dependency could be published to the maven repo if we are doing a libre build?

That means we'd need to maintain the fork and keep up with it and that is not something I'm really looking forward to.

In general, this has happened once, throughout the course of the SDK, so maybe we can try to "fix" it with some docs? If it happens again and becomes a larger problem, we can look into maintaining forks and such, but as it is we do spread ourselves quite thing.

**Comment by Bubu** [comment]
> That's unfortunate :-( TBH the libre build was conceived for the F-Droid build, others consuming the SDK this way wasn't in my mind.

Right. Well, it is primarily used for the f-droid releases of element (and rocketchat).

> That means we'd need to maintain the fork and keep up with it and that is not something I'm really looking forward to.

Understood. I was more thinking about some maven or gradle level magic to coerce the correct dependencies for the lib... Not sure right now if something like this could work right now.

> In general, this has happened once, throughout the course of the SDK, so maybe we can try to "fix" it with some docs?

Right, yes, documenting the build flag together with this dependency gotcha is probably a good idea and might very well be enough for the time being :-).

**Comment by bmarty** [comment]
Thanks to both of you for looking at this problem :)

**Comment by licaon-kter** [comment]
Can this be reopened? Seeing GMS and Dropbox link with 3.10.2

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6599#note_819755175

**Comment by saghul** [comment]
Does Jitsi Meet 21.6 have that problem? It uses the latest SDK too.

We don't release a Libre flavored SDK so if they are using our official builds they are going to have GMS dependencies.

**Comment by bmarty** [comment]
If it helps, we are releasing a Libre flavored SDK on a regular basis (but not *that* often) here: https://github.com/vector-im/jitsi_libre_maven

**Comment by licaon-kter** [comment]
Ok got it but... it's rather odd, so the LIBRE_BUILD flag does what exactly?

It doesn't appear to exclude stuff that's clearly NOT libre, since it still pull Firebase, Google Play Services and InstallReferrer?

Solution was based on Elements build.gradle:
```
    // Jitsi
    implementation('org.jitsi.react:jitsi-meet-sdk:4.1.0') {
        exclude group: 'com.google.firebase'
        exclude group: 'com.google.android.gms'
        exclude group: 'com.android.installreferrer'
    }
```

:slightly_frowning_face:

**Comment by bmarty** [comment]
More context can be found here if it helps: https://github.com/vector-im/element-android/pull/3125

**Comment by saghul** [comment]
I can't speak for builds other than ours.

The flag excludes some dependencies such as Firebase and GMS from the resulting app.

Some of our dependencies, depend on InstallReferrer for example but fail gracefully if it's missing (I upstreamed a patch of the sort). So alas it's still necessary to do some exclusions.

I'll double check nevertheless, when I get the chance.

**Comment by licaon-kter** [comment]
@saghul 
> I can't speak for builds other than ours.

Fair enough, but could you reiterate how to build using the flag?

Now, some apps (Element, Infomaniak Meet) are doing this:
```
- cd $$jitsi-meet$$
- export LIBRE_BUILD=true
- npm install webpack-bundle-analyzer
- npm install
- mkdir -p "$HOME/.m2"
- bash android/scripts/release-sdk.sh "$HOME/.m2/repository"
- mkdir -p "$HOME/.m2/repository/org/webkit"
- cp -r node_modules/jsc-android/dist/org/webkit/android-jsc "$HOME/.m2/repository/org/webkit"
```

I suspect that exported environment is ignored maybe?

Or the whole workflow is wrong?

**Comment by saghul** [comment]
That should be fine, but it's alas not enough due to transitive dependencies.

Look at our build.gradle file and how we exclude some libraries of some of our dependencies.

I wish it was simpler to do, and if there is any obvious way to get rid of those, I'd be happy to make changes, but at the moment it's necessary to apply the same exclusions on the apps using the SDK.

**Comment by licaon-kter** [comment]
@bmarty affects Element as well :( https://gitlab.com/fdroid/fdroiddata/-/issues/2596
