### ISSUE TITLE
Error building for iOS Simulator using jitsi meet SDK 3 on M1 apple silicon system

### ISSUE THREAD

**Issue by datacosmos** [jitsi/jitsi-meet#8969]
### Description:

I am using the  JitsiMeetSDK 3.3.0 iOS XCFramework binaries for my project, when I try to run my project on xcode Version 12.4 on an iPhone Simulator, I get the following error:

`building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64`

This seems to be due to the fact that I am developing on a mac with M1 apple silicon chip - so there should also be a binary for iOS Simulator-arm64 inside the Jitsi Meet SDK.

### Steps to reproduce:

1. Add binary xcframeworks (webrtc and jitsimeetsdk) to project
2.  set embed and sign to embed libraries section of target 
3. under build phases set WebRTC and JitsiMetSDK as required under link lib section
4. Run the project on arbitrary iphone simulator

### Expected behavior:

App is built and iPhone Simulator starts the app.

### Actual behavior:
Above error on linking stage of App build for simulator

### Client information:

- Browser / app version: Jitsi Meet SDK 3.3.0
- Operating System: macOS Big Sur
- Hardware: Chip Apple M1, 2020

### Additional information:

If there a workaround so that I can build the app for simulator and leave out anything with Jitsi? I do not really need jitsi running inside the simulator - it works for me to test this part on hardware - but for the other parts of my app I want to use the simulator to debug...

Any Ideas?

**Comment by saghul** [comment]
Sorry, I have no idea. I guess we'd need to add a new slice to the SDK. Will try to look into this for the next version.
