### ISSUE TITLE
Help menu disable  not working in ios 

### ISSUE THREAD

**Issue by kirtirc** [jitsi/jitsi-meet#8972]
Hello
we are using jitsi  sdk in  ios and android platform. and want to disable some menu option from sdk  
i  tried to disable help menu  and  it not working in ios but working in android

  builder.setFeatureFlag("help.enabled",withBoolean: false)
  builder.setFeatureFlag("help-view.enabled",withBoolean: false)
  
  Please help me how to disable help menu
  Thanks in advance

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by kirtirc** [comment]
Thanks for quick reply
i am installed SDK via  pod   with  JitsiMeetSDK 2.11.0 version

**Comment by saghul** [comment]
Those were added later, please update to the latest version.
