### ISSUE TITLE
Audio "echo" bug between Android + Android/IOS clients. (Not Android-PC)

### ISSUE THREAD

**Issue by hardlycode** [jitsi/jitsi-meet#8981]
Hello, I've found an urgent bug in Jitsi Meet from last week. It appears that when android clients of the newest version connect to IOS clients, the audio comes out of sync and/or has lots of echo (but it's not a true echo, it's more like the audio is being reassembled in the wrong order).
 This problem does not happen between Android clients. Also, the 'end call' button on the new android version doesn't appear to work so I need to power cycle my tablet to end the call.

The problem occurs when connected to meet.jit.si with two different clients, both Apple tablet users.
My Android/Win10 clients have no problems.

The Apple tablet users are direct p2p connections.

This problem does not affect the video of the connection. Only the audio has an echo and is out of sync. The video functions as normal.

Any assistance is greatly appreciated. The apps were just fine at the end of March, 2021 but now they are unusable.

**Comment by hardlycode** [comment]
I just had a session with one client who informed me she is using an iphone 9 with no problems.

It could be this issue is limited to older ipads.

**Comment by saghul** [comment]
WebRTC uses the hardware echo canceller, so it's somewhat out of our hands.

**Comment by hardlycode** [comment]
Can you please be more specific? This wasn't a problem last month.

Is this because apple updated something?

**Comment by saghul** [comment]
We updated WebRTC to the latest release. It's a large library, so there is a chance some bug made it in. Echo cancelling problems, however, are very hard to debug, so I'll be honest: don't keep your hopes up here.

**Comment by hardlycode** [comment]
Ok, thank you. I will look for alternate options in the meantime.

**Comment by 2481632** [comment]
Same problem here, but sadly this "echo" problem also appears on Android - Andorid since the last update. 
Before the update everything worked just fine. But now sometimes it is nearly unusable, because peaces of words or whole sentences get lost or get some kind or reverb.

**Comment by d5xtgr** [comment]
I'm experiencing this with the most recent version on F-Droid, currently 21.1.0.  I think 2481632's description touches on something important - it's more of a reverb than an echo.  What I hear is two copies of the iPhone user's audio (and she hears two copies of mine), which have a time delay that varies during a call from imperceptible up to maybe half a second.  I'm *not* hearing my own audio coming back to me, so I don't think the echo cancellation is at fault.

**Comment by wvffle** [comment]
Same happens on the Android - Android using custom app with sdk. We were using jitsi-meet-sdk:3.3.0 and now we've switched to 3.5.0 in hope that's fixed in this version. I need our testers to give feedback though.

**Comment by wvffle** [comment]
> We updated WebRTC to the latest release. It's a large library, so there is a chance some bug made it in. Echo cancelling problems, however, are very hard to debug, so I'll be honest: don't keep your hopes up here.

@saghul, can you point to the version that uses older WebRTC?

**Comment by hardlycode** [comment]
> I'm experiencing this with the most recent version on F-Droid, currently 21.1.0. I think 2481632's description touches on something important - it's more of a reverb than an echo. What I hear is two copies of the iPhone user's audio (and she hears two copies of mine), which have a time delay that varies during a call from imperceptible up to maybe half a second. I'm _not_ hearing my own audio coming back to me, so I don't think the echo cancellation is at fault.

I am getting the same problem, too. Computer clients to my Android tablet are fine. but clients using android/iOS are getting this weird double echo. It's like it's adding the voices instead of canceling them. On slower links the problem becomes much more noticeable.

**Comment by hardlycode** [comment]
I want to add two notes for developers who might be trying to debug this:

1. The problem gets worse on slower connections, if something is downloaded in the background/bandwidth is limited, the distance between the echo timing is increased.

2. I think this might be a problem with the audio playback itself and not noise cancellation. More than an echo, it seems the audio itself is playing TWICE. Once instantly, and then again at a delayed time.

Is there a possibility that the audio code is duplicating the audio itself somewhere?

**Comment by Joshndroid** [comment]
This continues with android clients and basically makes it unusable as a home based solution to keep away from the likes of facebook/etc.

**Comment by pcvengros** [comment]
please see this issue, it provides more info and narrows it down to commit in libjitsimeet
https://github.com/jitsi/lib-jitsi-meet/issues/1631

**Comment by hardlycode** [comment]
Thank you for posting this!
