### ISSUE TITLE
All start muted option iPad OS app

### ISSUE THREAD

**Issue by MacintoshRescue** [jitsi/jitsi-meet#8985]
The Jitsi Meet iPad OS app is best for me as I can mute all participants other that the main speaker, even when that's not me. I can't find a way to do this on the web interface as I can only mute everyone except my self which means I can't help another speaker.

Unfortunately I can't get into all meeting settings in the iPad OS app like I can through a web browser. I'd like the ability to set all participants start muted within the iPad app, and the ability to set the meeting to follow a specific speaker.

I'm using Jitsi Meet to host a meditation group where a leader focuses on the meditation, and I do the meeting admin so that the leader can just focus on the meditation guidance.

We're very grateful to the Jitsi community for making this platform and our group possible, and just sorry I lack the expertise to contribute more than ideas.

**Comment by saghul** [comment]
> The Jitsi Meet iPad OS app is best for me as I can mute all participants other that the main speaker, even when that's not me. I can't find a way to do this on the web interface as I can only mute everyone except my self which means I can't help another speaker.

You can do this by opening the menu with the 3 dots on a participant's tile.



> Unfortunately I can't get into all meeting settings in the iPad OS app like I can through a web browser. I'd like the ability to set all participants start muted within the iPad app, and the ability to set the meeting to follow a specific speaker.

Yep, those settings are not yet implemented on mobile.



> We're very grateful to the Jitsi community for making this platform and our group possible, and just sorry I lack the expertise to contribute more than ideas.

Thanks for the kind words!
