### ISSUE TITLE
Android SDK cannot detect Chinese language 

### ISSUE THREAD

**Issue by empty117** [jitsi/jitsi-meet#8987]
### Description:

In Android SDK, LocaleDetector.java:

 constants.put("locale", context.getResources().getConfiguration().locale.toString());

In android OS, it may return "zh_cn" or "zh_cn_#hans". In latter format, SDK will show default English.

Seems [https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/languageDetector.native.js](url) will not understand "zh_cn_#hans".

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Thanks for the report! Do you know of this is documented anywhere?

**Comment by empty117** [comment]
I have no idea where is official document, but my HUAWEI mate10pro with android 10 return "zh_CN_#Hans", i do workaround with:

 String locale = context.getResources().getConfiguration().locale.toString();
        int index = locale.indexOf("_"),lastIndex = locale.lastIndexOf("_");
        if(lastIndex>index){
            locale = locale.substring(0,lastIndex);
        }

it works

**Comment by longuto** [comment]
> 我不知道官方文档在哪里，但是我的 HUAWEI mate10pro 和 android 10 返回“zh_CN_#Hans”，我用以下方法解决：
> 
> String locale = context.getResources().getConfiguration().locale.toString();
> int index = locale.indexOf(" _"),lastIndex = locale.lastIndexOf("_ ");
> if(lastIndex>index){
> locale = locale.substring(0,lastIndex);
> }
> 
> 有用

我试过，没效果。用的3.5.0的sdk
