### ISSUE TITLE
Release build  error: Build input file cannot be found:

### ISSUE THREAD

**Issue by kirtirc** [jitsi/jitsi-meet#8991]
Hello
i am getting error when generate release build 
error: Build input file cannot be found: '/Users/Mac/Library/Developer/Xcode/DerivedData/jitsi-meet-eyzafeevvwrwchbrdzhwatthqgkn/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/JitsiMeet.build/jitsi-meet.app-Simulated.xcent' (in target 'JitsiMeetSDK' from project 'sdk')

Xocde version 12.3
Jitsi release Version 3.3.0
Please help me regarding this problem
Thanks

**Comment by saghul** [comment]
How exactly are you building it? Have you tried Xcode 12.4?

**Comment by kirtirc** [comment]
Thanks for quick reply  and it working in xcode 12.4 version
screen sharing not working in newly create xcframework and implemented in my app  but it working your source code app
Please guide me 
Thanks

**Comment by saghul** [comment]
Did you setup the app group? Set the identifiers in the plist files? Added the extension? What did you try?

**Comment by kirtirc** [comment]
yes,i changed bundle identifier  and app group  also  and here attached screenshot  and i am using our hosted server 
 if any missing let me know
Thanks in advance .
<img width="1160" alt="Screenshot 2021-04-14 at 10 47 03 AM" src="https://user-images.githubusercontent.com/80387687/114659060-8321cc80-9d10-11eb-901c-aa1e97a8ce4c.png">
<img width="1159" alt="Screenshot 2021-04-14 at 10 46 07 AM" src="https://user-images.githubusercontent.com/80387687/114659062-8452f980-9d10-11eb-8465-20faf2525c2a.png">

**Comment by kirtirc** [comment]
@saghul can you please help  me

**Comment by saghul** [comment]
Not sure what could be happening. We use Xcode 12.4, not sure if that may be the difference.

**Comment by JijoBose** [comment]
Hi @saghul 

I'm running Xcode 12.4, 

- deleted my node_modules
- `npm install`
- cd ios && pod install
- Build is successful in XCode.

But when I run the command below to compile the SDK

`xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive
`

I get this error

```
WebRTC framework has NO bitcode
~/jitsi-meet/node_modules/react-native-webrtc/ios ~/jitsi-meet/ios/sdk
Downloading files...
tar: Error opening archive: Unrecognized archive format
Command PhaseScriptExecution failed with a nonzero exit code

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Bitcode /Users/Username/Library/Developer/Xcode/DerivedData/jitsi-meet-bzbaecwwohsaphcdyebpejioaybp/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh
(1 failure)

```

**Comment by saghul** [comment]
Are you running the latest Jitsi Meet code? I got rid of the builtin WebRTC bitcode download, it now needs to be run before calling xcodebuild. See the script in ios/scripts/release-sdk.sh

**Comment by JijoBose** [comment]
@saghul 

I'm using an older version.
Let me know the changes I need to add to the existing code here.



```
#!/bin/bash

set -e -u

THIS_DIR=$(cd -P "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)
PROJECT_REPO=$(realpath ${THIS_DIR}/../..)
RELEASE_REPO=$(realpath ${THIS_DIR}/../../../jitsi-meet-ios-sdk-releases)
DEFAULT_SDK_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" ${THIS_DIR}/../sdk/src/Info.plist)
SDK_VERSION=${OVERRIDE_SDK_VERSION:-${DEFAULT_SDK_VERSION}}
DO_GIT_TAG=${GIT_TAG:-0}


echo "Releasing Jitsi Meet SDK ${SDK_VERSION}"

pushd ${RELEASE_REPO}

# Generate podspec file
cat JitsiMeetSDK.podspec.tpl | sed -e s/VERSION/${SDK_VERSION}/g > JitsiMeetSDK.podspec

# Cleanup
rm -rf Frameworks/*

popd

# Build the SDK
pushd ${PROJECT_REPO}
rm -rf ios/sdk/JitsiMeet.framework
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release ENABLE_BITCODE=NO clean archive
if [[ $DO_GIT_TAG == 1 ]]; then
    git tag ios-sdk-${SDK_VERSION}
fi
popd

pushd ${RELEASE_REPO}

# Put the new files in the repo
cp -r ${PROJECT_REPO}/ios/sdk/JitsiMeet.framework Frameworks/
cp -r ${PROJECT_REPO}/node_modules/react-native-webrtc/ios/WebRTC.framework Frameworks/

# Strip bitcode
xcrun bitcode_strip -r Frameworks/JitsiMeet.framework/JitsiMeet -o Frameworks/JitsiMeet.framework/JitsiMeet
xcrun bitcode_strip -r Frameworks/WebRTC.framework/WebRTC -o Frameworks/WebRTC.framework/WebRTC

# Add all files to git
if [[ $DO_GIT_TAG == 1 ]]; then
    git add -A .
    git commit -m "${SDK_VERSION}"
    git tag ${SDK_VERSION}
fi

popd

echo "Finished! Don't forget to push the tags and releases repo artifacts."
echo "The new pod can be pushed to CocoaPods by doing: pod trunk push JitsiMeetSDK.podspec"

```

**Comment by saghul** [comment]
Sorry, a lot has changed not only in that file. I suggest you update your version to our latest and apply your changes on top. It's the only real good way forward.
