### ISSUE TITLE
custom background image is mirrored

### ISSUE THREAD

**Issue by foss-** [jitsi/jitsi-meet#8992]
Set following image as custom background
![test_backgorund](https://user-images.githubusercontent.com/5708172/114414813-76399780-9baf-11eb-8690-f561fb8aa7d8.jpg)

### Expected behavior:
use background image "as is"

### Actual behavior:
image is mirrored
<img width="1419" alt="mirrored" src="https://user-images.githubusercontent.com/5708172/114415033-9ec19180-9baf-11eb-9487-e94d50d26e0a.png">

- Jitsi Meet version: https://meet.jit.si/ as of 2021-04-12
- Browser / app version: Firefox 89

**Comment by damencho** [comment]
This is normal, local view by default is mirrored. You can flip it from the 3 dots many from your local video thumbnail. This is only local.

Please, when you have questions or problems use the community forum before opening new issues, thank you.
