### ISSUE TITLE
[Android 10] Session destroy seems to not work when using hang up button

### ISSUE THREAD

**Issue by kermie** [jitsi/jitsi-meet#8998]
### Description:

As an Android 10 user, I want to be able to use the hang up button to destroy my session.

### Steps to reproduce:

1. Open Jitsi Meet App on an Android 10 device
2. Start a new meeting => talk (even to yourself)
3. Try to cancel this meeting with the hang up button

### Expected behavior:

When using the hang up button, the session for this meeting should be destroyed, one should be off the call.

### Actual behavior:

Using the hang up button seems to not work at all when using Android 10 (tested on Device: LENOVO YT-X70S7) - there's just no action on this button. However, it still seems to work perfectly in Android 9 (tested on Device: Samsung 8).

### Server information:

- Jitsi Meet version: https://meet.jit.si <-- as used on App Jitsi Meet by default 
- I checked another instance as well at https://meet.adminforge.de => same issue
- Operating System: most likely some *nux

### Client information:

- App version: 21.0.0
- Operating System: on both, Android 10 (not working) and Android 9 (working)

### Additional information:

Looks like a bug in present "Jitsi Meet for Android" v21.0.0 where Android 9 is still running and Android 10 is not: Everything seems to be okay but the hang up button to destroy the session. Even if the app is "closed" on Android 10 or the device is re-started  (not entirely tested), one ends up in the same session as you were before.
Same behaviour after cleaning up cache and complete re-installation of the client on Android 10.
As I also ran a test on another instance (meet.adminforge.de and this one is unlikely the same server configuration as meet.jit.si has) it really seems to be a client flaw.

**Comment by saghul** [comment]
Can you try the latest beta? We believe this is solved in version 21.1.0.

**Comment by kermie** [comment]
Sure, am in general up to check it @saghul. Alone, I am not sure if I was able to install a beta client on a working system outside of Google Play Store. Any docs/hint on how to achieve it?

**Comment by saghul** [comment]
Not sure, betas are also distributed through Google Play...

**Comment by kermie** [comment]
Sorry, @saghul it took a while. Unfortunately, in Google Play, I couldn't find any option to run a beta. I couldn't even find a client version there, even when logged in: https://play.google.com/store/apps/details?id=org.jitsi.meet, #gnarf
However, there are already people complaining about this behaviour in their reviews, giving bad ratings (which is not fair, isn't it). Please let me know once this chellange is accomplished. I'll feel happy to react on the reviews on Google Play ;)

**Comment by saghul** [comment]
Here is how to join the beta: https://play.google.com/apps/testing/org.jitsi.meet

We plan to release a new version with a fix this week.

**Comment by kermie** [comment]
Thank @saghul! Joined the beta from my wifey's account. Will let you know about the checks once the kids don't occupy this device any more ^^

**Comment by kermie** [comment]
Alr8. Tested on Android 10 device with beta version: session seems to close properly now. Thanks alot for this and good luck with the next release!
