### ISSUE TITLE
LastN

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#9]
Jitsi Videobridge now has a LastN feature that allows it to only forward the video for the last N active speakers. This is a mandatory feature for large scale conferences.

**Comment by markreg** [comment]
How are stream changes signaled to `lastN` endpoints?

**Comment by bgrozev** [comment]
Through data channels. See [here](https://github.com/jitsi/jitsi-meet/blob/master/modules/RTC/DataChannels.js#L85).
