### ISSUE TITLE
Jitsi Meet Android Hang-Up not working

### ISSUE THREAD

**Issue by vjjw** [jitsi/jitsi-meet#9006]
### Description:

Jitsi Meet 21.0.0 for Android downloaded from the GoogleStore on a Samsung Galaxy A7 Android, 10 with all software and OS up to date.
Once in a room, the hang-up button is not operative. Clicking it has no effect. One has to quit the app to leave the room.
The Hang-up button is almost in the same position as the general back button, but the problem is definitely present even if the three system buttons from the Navigation bar are not on screen.
The system's Navigation bar back "button" does work to quit the room.
If Picture-in-Picture was set for the app one has to reset the tablet to quit the app and thus the room.
No other problems.
(I RTFM'd and searched the forum and the general Internet, I would be the only one having the problem ?)

### Steps to reproduce:

Open the Jitsi Meet App
Start a conference
Use the Hang-up button

### Expected behavior:

Quit the room (I suppose ;-)

### Actual behavior:

Nothing happens, it is as if the big Red Hang-up Button was disabled.

### Server information:

meet.jit.si

### Client information:

- Jitsi Meet for Android 21.0.0 Build 7046084
- Android 10

**Comment by saghul** [comment]
This is fixed in version 21.1.0, currently in beta.
