### ISSUE TITLE
Some errors for 'react-navigation'

### ISSUE THREAD

**Issue by Hin-D** [jitsi/jitsi-meet#9009]
My project needs to use 'react navigation', and I installed it according to docs https://reactnavigation.org/docs/getting-started/ but get some errors like this:

![image](https://user-images.githubusercontent.com/13867945/114803279-c55f1280-9dd1-11eb-87d6-89953e641cfa.png)

These library 'RNCMaskedView, RNGestureHandler, RNReanimated, RNScreens, and react-native-safe-area-context' are necessary for 'react navigation', but they depended upon by 'react-native@0.62'.

Unfortunately, I can't upgrade my react-native
![image](https://user-images.githubusercontent.com/13867945/114803725-92694e80-9dd2-11eb-97af-95189aa00024.png)

Please help!

**Comment by saghul** [comment]
Our version is 0.61.5 plus 1 patch. You can update package.json to point to 0.61.5 instead of our build and the diff should work.

Not sure what other problems you may run into during the update though.

**Comment by Hin-D** [comment]
I solved the problem by delete the folder ’node_modules‘ and reinstall anything
