### ISSUE TITLE
iOS App screensharing no landscape

### ISSUE THREAD

**Issue by PGoridaris** [jitsi/jitsi-meet#9012]
### Description:

Hello,

if you use the iOS App (iPhone and iPad Air) and turn the display to landscape mode while streaming the display, the streamed content won't be rotated as well. It stays in pivot mode.

### Steps to reproduce:

1. Open a new meeting or join an existing meeting via the iOS app. 
2. Join with a second (or more) user via webbrowser from your pc (in my case Chrome from Win10, Ubuntu 20.04 and iOS via app).
2. Start screensharing via the context menu.
3. Allow screensharing.
4. Rotate the iPad or iPhone from pivot to landscape or from landscape to pivot.

### Expected behavior:

The shared picture will be rotated as well into pivot or landscape mode.

### Actual behavior:

The shared picture stays in pivot in web. The content is displayed as landscape (see attached screenshot).
![image](https://user-images.githubusercontent.com/81612433/114860836-c6516d80-9dec-11eb-99f8-f90cef2e7f3a.png)

### Server information:

- Jitsi Meet version: latest docker files (ref: https://github.com/jitsi/docker-jitsi-meet)
- Operating System: Ubuntu 20.04.2 LTS

### Client information:
Streaming Client:
Tested with mutliple app versions:
- App-Version: 21.0.0 build 110
- App-Version: 21.1.0 build 111 (via Testflight)
OS: iOS 14.4.2

Recieving iPhone:
- Browser / app version: APP-Version: 21.0.0 build 110
- Operating System: iOS 14.4.2

Recieving Client Windows:
- Browser: Chrome Version 89.0.4389.114
- OS: Windows 10 20H2 (Build 19042.867) - latest updates

Recieving Client Linux:
- Browser: Chromium Version 89.0.4389.128
- OS: Linux Ubuntu 20.04.2 LTS, latest updates.

### Additional information:

This is fully reproducable in our environment and is not bound to the local network. It occurs in any networks connecting to our server.

**Comment by saghul** [comment]
Yep, this is a known limitation currently.

**Comment by PGoridaris** [comment]
Okay, thanks for the fast reply. Haven't found anything regarding this in the current bugs listed.

**Comment by JoshuaDietz** [comment]
Sure this is no real solution for this limitation but maybe it would make sense to add a "rotate video" button to the receiving clients anyway since there always might be situations where a participant needs to view the stream rotated.

**Comment by saghul** [comment]
Fixed it in #9020, hopefully we can push a beta with it soon.
