### ISSUE TITLE
Recording not working

### ISSUE THREAD

**Issue by user9846cbl** [jitsi/jitsi-meet#9014]
Recording Functionality not working

### Description:

Whenever going to start recording its giving an error "Your recording will be saved by the recording service". Please Let me know what can I do to make it working

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

If you are asking about your deployment it is probably some misconfiguration, gather jicofo and jibri logs and provide them with your question in the community forum.
If you are experiencing this on meet.jit.si, mind that recorders are limited resources and in cases of a high demand you need to wait for some to be available. You can subscribe to 8x8 Meet Pro for a small monthly fee, which will guarantee that there are always free recorders available.
