### ISSUE TITLE
Microphone appears enabled but no audio heard after stopping screen sharing with audio

### ISSUE THREAD

**Issue by stephendonner** [jitsi/jitsi-meet#9024]
### Description:

Microphone appears enabled but no audio heard after stopping screen sharing with audio

### Steps to reproduce:

1. on a desktop/laptop, load `https://meet.jit.si/` using Brave release (latest is `1.23.71`)
2. click on the blue `Start meeting` button
3. enter your name
4. click on the blue `Join meeting` button
5. enable microphone and video camera, if you haven't already
6. on an iOS device, load the meeting URL using Brave release (latest is `1.24 (21.4.1.15)`)
7. tap on the bottom `Launch in web` button
8. tap on Allow when prompted for camera and microphone permissions
9. tap to enter a name
10. tap the blue `Join meeting` button
11. do a quick test to ensure you can hear audio, in both directions (iPad/iPhone <----> desktop/laptop)
12. in a new browser tab on the desktop/laptop, load a movie or video clip - I used `hbomax.com` but probably `hulu.com` `netflix.com` and maybe even `youtube.com` will work
13. on the desktop/laptop, click on `Share your screen`
14. select the `Brave Tab` heading/tab -- the one with media currently playing
15. select the actual Brave tab, just beneath it
16. click the checkbox to enable `Share audio`
17. now click on the orange `Share` button
18. verify you can still hear audio from the desktop/laptop to the iOS device
19. verify that the microphone icon is still enabled on the desktop/laptop
20. now, click again on `Share your screen` to stop sharing your screen
21. verify again that the microphone icon is still enabled on the desktop/laptop

### Expected behavior:

After stopping screen sharing with audio, with the microphone still enabled, the iOS device should still hear audio from the desktop/laptop

### Actual behavior:

1) Even though the microphone is still enabled, no audio is...audible
2) toggling the microphone on/off again has seemingly no effect

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Brave release `1.24` and `1.23.71` on iOS / macOS, respectively
- Operating System: iOS 14.5 (public beta 8) and macOS 11.2.3 (Big Sur), respectively

/cc @mrose17

**Comment by saghul** [comment]
Ping @andrei-gavrilescu

**Comment by andrei-gavrilescu** [comment]
Hello everyone,

@stephendonner  the scenario you mentioned was fixed a while back (1 week ago, I think) and I can't seem to reproduce it on the latest meet-jitsi.
There were also some improvements on this functionality that were delivered this past Thursday, could you try to repro the issue on the latest release? Thank you.

**Comment by stephendonner** [comment]
hi @andrei-gavrilescu as filed, this works for me (which made me realize I left out a key part!) so sorry for missing that 🙏 

I've amended the steps to reproduce now, so if you could try again, that'd be great.

What I omitted when originally filing is that _**the tab you screen-share should be playing media**_ (preferably Widevine content, as that's the only thing I've tested, though it might not be necessary).  I added the following, "12. in a new browser tab on the desktop/laptop, load a movie or video clip - I used `hbomax.com` but probably `hulu.com` `netflix.com` and maybe even `youtube.com` will work"

**Comment by andrei-gavrilescu** [comment]
Hmm I can't seem to reproduce with sharing the tab either. Are you able to consistently reproduce it?

**Comment by stephendonner** [comment]
> Hmm I can't seem to reproduce with sharing the tab either. Are you able to consistently reproduce it?

Yes, sorry for the delay, @andrei-gavrilescu - and I can also confirm that from the iOS device, when unmuted, is able to send audio to the room, and be received/played back by the desktop machine, but not the other way around.

Feels like an audio-channel issue.

**Comment by stephendonner** [comment]
Sorry, yes, putting this on my shorter to-do list for tomorrow, promise 👍

**Comment by stephendonner** [comment]
@andrei-gavrilescu this worked fine for me with a couple tests of laptop <-> desktop, thanks!

**Comment by stephendonner** [comment]
Cannot reproduce this any longer, and haven't heard any reports of it from colleagues, so closing out.
