### ISSUE TITLE
[jitsi-meet/stable] turncredentials not configured with prosody default example

### ISSUE THREAD

**Issue by celogeek** [jitsi/jitsi-meet#9025]
### Description:

The example of prosody use external_service_secret and external_services for turnserver.
When I use it instead of turncredentials_secret and turncredentials, I receive:
`turncredentials not configured`
When I reuse the old config (different from the nightly up to now), it works.

### Steps to reproduce:

1. Edit prodsody config
2. Use external service as in the prosody config example
3. Restart prosody

### Expected behavior:

The config example should works.

### Actual behavior:

The turn service stop working with the default example

### Server information:

- Jitsi Meet version: 2.0.5765-1
- Operating System: debian 10

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

Does the prosody turnserver configuration will move back to turncredential?

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

The default configuration has been tested and works. When moving to the new config you also need to enable and the new module, disabling the old.
In later versions of prosody 0.12+ the extra module will not be needed as this will be internal to prosody.
