### ISSUE TITLE
Shibboleth/SAML Authentication (URL Redirection) broken in 2.0.5765

### ISSUE THREAD

**Issue by amsnek** [jitsi/jitsi-meet#9026]
### Description:

In Release 2.0.5765, when using Shibboleth authentication, the url redirection logic does not work.  It may not have been ported completely. See also: https://community.jitsi.org/t/struggling-with-shibboleth-auth-in-update-2-0-5765/97824 for details regarding the configuration used. 
When using the exact same setup (jicofo, prosody, jitsi-videobridge) and only switching the "jitsi-meet" webapp version  2.0.5390 -> SAML redirection works as expected.
These are self compiled packages, not using debian packages or docker images, as done in the past. 

### Steps to reproduce:

1. Setup Shibboleth: Enable Shibboleth Authentication in jicofo.conf or legacy sip-communicator.properties, enable anonymous auth in prosody configuration 
2. Start a Conference 
3. Click "I am Moderator"

### Expected behavior:

URL Redirection should happen. 

### Actual behavior:

Default Password Username/Password prompt appears (like in XMPP authentication or similiar types)

### Server information:

- Jitsi Meet version: 2.0.5765
- Operating System: Linux

### Client information:

- Browser / app version: Chrome 89.0.4389.128
- Operating System: Windows 10 

### Additional information:

Thanks to Community Analysis (see: https://community.jitsi.org/t/struggling-with-shibboleth-auth-in-update-2-0-5765/97824) it may be that the shibboleth auth configuration was not ported to the new react version of the authentification: https://github.com/jitsi/jitsi-meet/tree/master/react/features/authentication

Thanks to Boris_Grozev and Damien_FETIS for their in-depth support and analysis on the initial posting.

**Comment by SimonMaenaut** [comment]
From our testing, I can confirm this issue.

We similarly tried to upgrade to version 2.0.5765 and were unable to get Shibboleth working, which we rely on to limit starting a call to university students. If testing is required I would be more than willing to assist and run new unstable versions on our instance.

Thank you for figuring the bug that causes this issue!

**Comment by damencho** [comment]
@SimonMaenaut you can try and test: https://github.com/jitsi/jitsi-meet/pull/9049
Thank you.

**Comment by flyinghuman** [comment]
same here.. after update to latest version Shibboleth does not work anymore. i must revert back to last snapshot to get it work again. is there a fix already i can apply? i use the Ubuntu packages with apache2 Webserver. Thanks!

**Comment by damencho** [comment]
There is a RC for stable, which is now in testing repo, you can try that.

**Comment by bertvandepoel** [comment]
I believe this has been fixed in stable and can be closed. Could others in this issue confirm?

**Comment by amsnek** [comment]
sorry for the delay, i thoght i had already acknowledged it 🙈 
yes, I can confirm, this issues has been fixed in stable and thus can be closed

thanks a lot! 👍
