### ISSUE TITLE
Set Display Name by ldap information

### ISSUE THREAD

**Issue by semihdurgun** [jitsi/jitsi-meet#9027]
Hi everyone,
I am using ldap for user-authentication on jitsi. When i logging in I’d like to set the Jitsi “Display Name” by the ldap information. Because ldap information already include that. Is there an option? it would be nice..

**Comment by damencho** [comment]
There is no such option at the moment and such feature is not on the roadmap. Any PRs are welcome.

**Comment by martient** [comment]
I will take a look on it :)

**Comment by 0xnor0** [comment]
> I will take a look on it :)

Did you get any news on this?

**Comment by saghul** [comment]
Closing since we have no plans to work on this. Feel free to reference it in a PR if anyone is up for it.
