### ISSUE TITLE
Sometimes the control bar does not disappear anymore

### ISSUE THREAD

**Issue by JohnProv** [jitsi/jitsi-meet#9029]
### Description:
In some cases, the control bar at the bottom of Jitsi Meet does not disappear after some time of inactivity. Although I think in all cases the control bar should disappear, I found one case which is reproducible.

### Steps to reproduce:

1. Open a meeting with at least 2 participants
2. Toggle tile view, thus (all members >) one member > all members
3. Click on the button _Invite people_
4. Click on the meeting link to copy the link
5. Close the pop-up by pressing the x
6. When not reproducible: try these steps as quick as possible after each other

### Expected behavior:
Nothing specials happens, and the control bar disappears as it did before.

### Actual behavior:
- Most times the control bar does not disappear anymore
- Sometimes the screen is a sort of jumping; a dark blue field at the bottom and the scroll bar is then visible for a second.

### Server information:

- Jitsi Meet version: https://meet.jit.si
- Operating System:

### Client information:

- Browser / app version: Firefox and Chromium
- Operating System: Linux

**Comment by damencho** [comment]
This had been fixed upstream. Updates will follow: https://github.com/jitsi/jitsi-meet/commit/cbeb7b86cc72ebd7d910e06b8012a996092785ef
