### ISSUE TITLE
mute untoggles itself if tapped quickly at the beginning of call

### ISSUE THREAD

**Issue by mailinglists35** [jitsi/jitsi-meet#9036]
### Description:

Mute button unmutes itself

### Steps to reproduce:

1. have slow internet
2. join meeting
3. IMMEDIATELY tap the mute button

### Expected behavior:

mute button remains toggled

### Actual behavior:

mute button untoggles by itself

### Server information:

- Jitsi Meet version:default ipad app
- Operating System: default ipad app

### Client information:

- Browser / app version: iPad App Store, latest
- Operating System: iOS 13.5

### Additional information:

This only happens if I'm quick enough before all members list are finished displaying. If I wait some seconds then I tap it, mute remains muted.

Btw, I should have the option to start muted, so I wouldn't have to be quick to mute myself in the beginning...

**Comment by saghul** [comment]
> Btw, I should have the option to start muted, so I wouldn't have to be quick to mute myself in the beginning...

You can toggle that on in the settings pane, on the initial screen before you join a meeting.
