### ISSUE TITLE
recordingStatusChanged event is not triggered

### ISSUE THREAD

**Issue by mertakdut** [jitsi/jitsi-meet#9039]
### Description:

As described in the [hand-book](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#recordingstatuschanged), _recordingStatusChanged_ event should be triggered when recording has started or ended. However, callback method is not called when I start or end the meeting through the recording toolbar buttons.

### Steps to reproduce:

1. Add your function as an event handler on jitsi api object:
`this.jitsiApi.on("recordingStatusChanged", this.onRecordingStatusChanged);`
2. Check your method is called or not.

### Expected behavior:

The callback function should have been called.

### Actual behavior:

The callback function is not called.

### Server information:

- Jitsi Meet version: Tested out with https://meet.jit.si/external_api.js.

### Client information:

- Browser / app version: Chrome Version 89.0.4389.128 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by izakgl** [comment]
What deployment are you using and if self-hosted what version of jitsi-meet? I tested it with meet.jit.si and it worked for me just now.

**Comment by mertakdut** [comment]
> Jitsi Meet version: Tested out with https://meet.jit.si/external_api.js.

Can you share your example?

**Comment by izakgl** [comment]
Yes, I saw that, but that is just the external api location. I'm asking about the domain you use to setup external api. I'm guessing it's meet.jit.si then?

This is my example:
```html
<!doctype html>
<html>
<head>
<script src="https://meet.jit.si/external_api.js"></script>
</head>
<script>
    var domain = "meet.jit.si";
    var options = {
        roomName: "ThisIsSomeRandomRoomName333111",
        width: 1200,
        height: 800
    }
    var api = new JitsiMeetExternalAPI(domain, options);
	
    api.on('recordingStatusChanged', (status) => {
        console.log('recording_status', status);
    });
</script>
</html>
```

I wasn't able to start the recording through the iframe because dropbox login didn't work for me, but starting it from a different tab directly on meet.jit.si worked and I received the event just fine.

**Comment by mertakdut** [comment]
You're right. It works.

The problem was attaching the listener **after onload event of jitsi.**

```
var options = {
  roomName: "ThisIsSomeRandomRoomName333111",
  width: 1200,
  height: 800,
  onload: this.onJitsiApiLoaded
}
this.jitsiApi = new window.JitsiMeetExternalAPI(this.DOMAIN, options);

onJitsiApiLoaded() {
  this.isLoading = false;
  this.jitsiApi.on("videoConferenceJoined", this.onVideoConferenceJoined);
  this.jitsiApi.on("videoConferenceLeft", this.onVideoConferenceLeft);
  this.jitsiApi.on("participantLeft", this.onParticipantLeft);
  this.jitsiApi.on("participantJoined", this.onParticipantJoined);
  this.jitsiApi.on("readyToClose", this.onReadyToClose);
  this.jitsiApi.on("recordingStatusChanged", this.onRecordingStatusChanged);
},
```

All the other events in there is triggered but _recordingStatusChanged_. It had to be done just after instantiating _jitsiApi_ object.

**Comment by mertakdut** [comment]
No, sorry. I was too eager. That is not problem.

It's domain level. When it's _meet.jit.si,_ no matter where you bind it, it works. It just doesn't with my domain.

I don't have the access to my domain at server level, don't know what version they're using and what configs. What exactly is it supposed to be? Any hints I can drop for them?

**Comment by saghul** [comment]
They need to be running on the latest stable release: https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_5765
