### ISSUE TITLE
Custom invite link

### ISSUE THREAD

**Issue by sekarpdkt** [jitsi/jitsi-meet#9045]
**Is your feature request related to a problem you are facing?**
I want to have custom meeting invite link so that the invitee will be authenticated in that URL and then diverted here.

**Describe the solution you'd like**
In config over ride, would like to have customInviteLink to be included and that link shall be shown in invite link/share instead of standard meet.jit.si/<roomname>

**Describe alternatives you've considered**
I have tried brandingRoomAlias and dynamicBrandingUrl and didnt work.

**Comment by fremzy** [comment]
Are you hosting your own server or running meetings on meet.jit.si?

**Comment by sekarpdkt** [comment]
At present using meet.jit.si. Planning to self host. If steps for self hosting is shared, that is also ok.

thanks

**Comment by Menelion** [comment]
I also would like to have something like _https://meet.jit.si/moderated/my-custom-url_. If it was allowed only in self-hosted, would be also OK.

**Comment by saghul** [comment]
Take a lok at https://moderated.jitsi.net/ It uses this: https://github.com/jitsi/moderated-meetings

**Comment by dberardo-com** [comment]
is there a way to add a query param to the invitation url ?
