### ISSUE TITLE
Admin can stop other user from sharing

### ISSUE THREAD

**Issue by lmat** [jitsi/jitsi-meet#9053]
**Is your feature request related to a problem you are facing?**
no

**Describe the solution you'd like**
When a user is sharing his screen, I can put my mouse over the three dots representing that user's connection, then select "Stop Sharing".

**Describe alternatives you've considered**
I could end the meeting for all users then start the meeting again.

**Comment by limitedAtonement** [comment]
Brutal, cold-hearted little bot. Bad bot.
