### ISSUE TITLE
Firefox isn't supported at all???

### ISSUE THREAD

**Issue by PyroRider** [jitsi/jitsi-meet#9054]
Hello, as the pandemic is ongoing our school began today again as online school where some of our teachers are using jitsi. I am a firefox user and now I am greeted with a huge message that my browser is not supported. Now I have no way of joining the classes today, so why do you block every non chromium browser? 
Btw, no, I will not install any chromium sh*t on my pc, just get it working for firefox as you wrote last year at the same time in a couple issues

**Comment by saghul** [comment]
Firefox is supported just fine.

<img width="1375" alt="Screenshot 2021-04-21 at 09 18 36" src="https://user-images.githubusercontent.com/317464/115512811-a7d2f280-a282-11eb-8dcf-7787359b60e2.png">

Are you running standard Firefox or some other fork? Do you have extensions that may change the UA or disable WebRTC?

PS: Save the accusations before you check the facts.

**Comment by PyroRider** [comment]
Standart firefox, adblock already disabled, nothing that disables WebRTC

**Comment by saghul** [comment]
Can you please share your console logs when you try to join a meeting?

**Comment by PyroRider** [comment]
![jitsi](https://user-images.githubusercontent.com/48856863/115517131-1c0f9500-a287-11eb-9d40-840c06f1daed.PNG)

**Comment by PyroRider** [comment]
I am sorry for beeing rude, we had a lot of problems with multiple video conference tools in the last weeks. For some reason this meeting seems to be the only one affected, gonna contact the school IT administration soon

**Comment by saghul** [comment]
> gonna contact the school IT administration soon

Please do, there is nothing we can do here to help you, since they are using their own deployment.
