### ISSUE TITLE
No requests are sent to TURN server when using Google Chrome

### ISSUE THREAD

**Issue by joushx** [jitsi/jitsi-meet#9056]
## Description
We just upgraded Jitsi from Version 5142 to 5765 and found the video connection not working any more when using chrome. We use the option for XEP-0215 where TURN credentials are stored in the prosody config.

## Current behavior
When monitoring the network requests made by the videobridge, we can see UDP requests to the TURN server after joining the conference. Also manual UDP requests can be seen when made from the pod. However, despite the logs that indicate a request beeing sent to check the candidate, no request can be found in the recorded requests. As a result, the ICE fails and no video can be seen in the room

```
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: Starting ICE connectivity establishment
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: start check for 10.36.0.16:443/udp/host -> 95.217.x.x:60262/udp/relay (stream-d277cdc8.RTP) tid 0xD43AD9F378011C0AD4A2DD80
Apr 21, 2021 11:53:23 AM org.ice4j.stack.StunClientTransaction sendRequest FINE: sending STUN  tid 0xD43AD9F378011C0AD4A2DD80 from 10.36.0.16:443/udp to 95.217.x.x:60262/udp
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: Update remote candidate for stream-b7a659d1.RTP: 95.217.x.x:51004/udp
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: new Pair added: 10.36.0.16:443/udp/host -> 95.217.x.x:51004/udp/relay (stream-b7a659d1.RTP).
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: Transport description:
<transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='7ctu2oeqn82g471pp842rmpubf' ufrag='9c64p1f3ptiecf'><rtcp-mux/><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' setup='passive' hash='sha-256'>94:0E:5F:56:1B:0E:99:43:16:8D:29:DD:BC:E6:DE:7F:0D:47:70:1C:9D:2A:DD:1F:4E:6C:7E:80:8E:77:13:58</fingerprint><web-socket xmlns='http://jitsi.org/protocol/colibri' url='wss://xxx/colibri-ws/jitsitest1/5b899349f0787ae9/b7a659d1?pwd=7ctu2oeqn82g471pp842rmpubf'/><candidate component='1' foundation='1' generation='0' id='5aba16bc3b00190b039e19ad3' network='0' priority='2130706431' protocol='udp' type='host' ip='10.36.0.16' port='443'/><candidate component='1' foundation='2' generation='0' id='7c2fa7183b00190b0ffffffff8f97646c' network='0' priority='1694498815' protocol='udp' type='srflx' ip='95.217.x.x' port='443' rel-addr='10.36.0.16' rel-port='443'/></transport>
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: Pair failed: 10.36.0.16:443/udp/host -> 95.217.x.x:60262/udp/relay (stream-d277cdc8.RTP)
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: start check for 10.36.0.16:443/udp/host -> 95.217.x.x:51004/udp/relay (stream-b7a659d1.RTP) tid 0xE73AD9F37801A50123DA8980
Apr 21, 2021 11:53:23 AM org.ice4j.stack.StunClientTransaction sendRequest FINE: sending STUN  tid 0xE73AD9F37801A50123DA8980 from 10.36.0.16:443/udp to 95.217.x.x:51004/udp
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: Pair failed: 10.36.0.16:443/udp/host -> 95.217.x.x:51004/udp/relay (stream-b7a659d1.RTP)
```

## Expected Behavior
A STUN request should be sent in order to establish a connection via the TURN server

## Possible Solution
Did the behavior change in any way? How can this be depend on the browser? Do we need to change the configuration? Could it be that the request is never sent although the logs?

## Steps to reproduce
1. Open a conference using chrome
2. Join with a second user
3. ICE fails

# Environment details
Kubernetes Cluster with Jitsi Components running in pods

JVB Version: 2.1-478-gc6da57bd-1
CoTurn Version: 4.5.1.3
Chrome Version: 90.0.4430.85

Related JVB-Issue: https://github.com/jitsi/jitsi-videobridge/issues/1637

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues in all repositories, than you.

Have you validated with webrtc-internals that the turn server are received and used for the peerconnections?

**Comment by joushx** [comment]
Yes, the data in the webrtc-internals shows the correct TURN server. But somehow the other side (Videobridge <-> TURN) does not try to connect. I cannot see any connection to the IP of the TURN or a UDP connection at all, although it says `sendRequest FINE: sending STUN  tid 0xE73AD9F37801A50123DA8980 from 10.36.0.16:443/udp to 95.217.x.x:51004/udp`.

Is the JVB-TURN-Connection triggered via the colibri WebSocket or via a XMPP message? It looks like Chrome is sending something different than Firefox that is then discarded by the videobridge.

**Comment by joushx** [comment]
Is the following chart of the flow with `useStunTurn: true` correct? The dashed lines are the requests that I cannot see.

For further debugging: How do the candidates get from the focus component to the videobridge?

![diagram](https://user-images.githubusercontent.com/832178/115689100-0d46e200-a35c-11eb-8aaa-75887b2b8962.png)

**Comment by damencho** [comment]
Jicofo open channels on the bridge and announce them to the clients and it is the clients that connect to the bridge either directly or using the relay/turn server.
Mind that it is the turn server connecting to the bridge using its public address and port, is this connection possible and allowed by your network settings?

**Comment by joushx** [comment]
Currently our bridge does not have a public address, but bridge and turn are in the same private network where connections are working. Because everything works as expected in Firefox, I assume this connection is possible.

**Comment by damencho** [comment]
> Do you by chance have any idea what could be different for Chrome in this process? Or is there an option that could influence this? The only relay candidate always fails in Chrome but always works in Firefox using the exact same setup.

No idea.

The internal connections initiated by the turnserver are disabled by default to drop the possibility for attacks to the internal network from the turnserver. 
You can disable your internal network deniy config, restart turnserver and test: https://github.com/jitsi/jitsi-meet/blob/9724bb17993eb9876866644b0bf18455c39bc710/doc/debian/jitsi-meet-turn/turnserver.conf#L19
If it works maybe use firewall outgoing rules to allow turnserver to be able to connect only to jvb port 10000 udp, so you can protect yourself from malicious use of the tiurnserver.

**Comment by joushx** [comment]
What I found out in the meantime:

* Our TURN server allows local connections
* The pod where TURN is running can connect to JVB 10000/UDP using netcat
* We disabled P2P in the config.js
* We did not set "no-tcp-relay" previously, but if we do also Firefox stops working (`about:webrtc` always said `relay-tcp` when it worked)
* Jicofo only gets a `srflx` and `host` candidate in the allocation response from the bridge, but no `relay` candidate. No difference if "no-tcp-relay" is set or not in the TURN config

**Comment by joushx** [comment]
So sum up:

* The relay candidates are the same for Firefox and Chrome
* Firefox can do TCP and UDP relay
* In Chrome TCP and UDP fail (Pair failed in bridge)
* Probably TURN and JVB cannot connect to each other, but only when Chrome is used

**Comment by joushx** [comment]
Solution: It looks like Chrome does not work if the port behind the TURN server is 443. This setting is from experiments with direct connection to the bridge. Once we changed it back to 10000 everything works as expected.
