### ISSUE TITLE
Guest mode + JWT Auth not working

### ISSUE THREAD

**Issue by MarcelCoding** [jitsi/jitsi-meet#9057]
### Description:

`TOKEN_AUTH_URL` is not working as expected

### Steps to reproduce:

1. Enable Authentication, Set auth type to jwt, Set `TOKEN_AUTH_URL` to e.g. duckduckgo.com
2. Start Jitsi -> you will be redirected to duckduckgo.com
3. Enable Guest Auth (to join your room, after a moderator opened a room)
4. Restart Jitsi -> you will get prompted with a login form

### Expected behavior:

A button in the login form to redirect to the `TOKEN_AUTH_URL`

### Actual behavior:

Due to the fact that you won't get redirected you can't use jitsi.

### Server information:

- Jitsi Meet version: Docker latest (2021-04-21)
- Operating System: Debian 10 / Docker

### Client information:

- Browser / app version: Google Chrome
- Operating System: Ubuntu

**Comment by damencho** [comment]
Will be fixed with https://github.com/jitsi/jitsi-meet/pull/9049

**Comment by MarcelCoding** [comment]
The guest mode is now working as expected.
