### ISSUE TITLE
The option to cut the call not working

### ISSUE THREAD

**Issue by Thewisem** [jitsi/jitsi-meet#9059]
### Description:

I started a call to test jitsi meet. But when I tried ending it, it was hard to cut the call. I had to click back button to close the call rather than clicking the call cut button

### Steps to reproduce:

1.  Open Jitsi meet
2.  Start a call
3.  Click on the cut button

### Expected behavior:

Call being cut off

### Actual behavior:

Nothing.

### Server information:

- Jitsi Meet version: 21.0.0 Fdroid Version
- Operating System: 7 Nougat

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Please search the open issues, this has been reported already.

A new update will go out this week with a fix.
