### ISSUE TITLE
Issues executing api commands

### ISSUE THREAD

**Issue by hasnainbilgrami** [jitsi/jitsi-meet#906]
Hi I am using the Meet Api, and whenever I try to execute the  `api.executeCommand` it gives the following issues: 
`Logger.js:89 [/JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Script error. Script:  Line: 0 Column: 0 StackTrace:  nulllog @ Logger.js:89getGlobalOnErrorHandler @ JitsiMeetJS.js:320window.onerror @ conference.js:493
Logger.js:89 [/modules/statistics/CallStats.js] <CallStats._reportError>:  No error is passed!
conference.js:581 Uncaught TypeError: Cannot read property 'muteVideo' of null`

I think it is because the api can't find the iframe, but I am not sure how to fix that.
Any adivce?

**Comment by maximax123** [comment]
I have the same problem. Сause of the problem in POSTIS and function call.

`listenersForMethod[i].call(null, listenBufferForMethod[j]);`

function is APP.conference.toggleVideoMuted

`toggleVideoMuted () {
        this.muteVideo(!this.videoMuted);
    },`

this = null

**Comment by maximax123** [comment]
https://github.com/jitsi/jitsi-meet/pull/928/files

**Comment by hasnainbilgrami** [comment]
So, if I do again it should work?

**Comment by hosseinsmart** [comment]
i have a same problem on setting display name!
