### ISSUE TITLE
A lock icon at the left corner to make the meeting passwored encrypted and option to password protect by default

### ISSUE THREAD

**Issue by Thewisem** [jitsi/jitsi-meet#9064]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
Yes, when I create a meeting room, it is not password protected. And the option to password protect is not there in the first options. I had unusual guests because I had to search into the options and find the icon in number of them.

**Describe the solution you'd like**
Please describe the desired behavior.
A lock icon to be there when creating the meeting, which has an unlcocked icon and when pressed, opens a tab and asks for password. Or having password protection by default.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Having the option in the settings to have it by default.

**Comment by Thewisem** [comment]
Hmmmmm ok

**Comment by saghul** [comment]
Sorry for the delay. We currently show a warning icon with instructions on how to reach the security dialog. There are no plans to change it at this time.
