### ISSUE TITLE
Automatic user disconection

### ISSUE THREAD

**Issue by WinterOdin** [jitsi/jitsi-meet#9067]
I've doployed my own jitsi app on Ubuntu 18.04 and when somone tries to join my server is automatically disconnected when. this happens i have this error in my console
`[modules/xmpp/xmpp.js] <P.tryParseJSONAndVerify>:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at P.tryParseJSONAndVerify (xmpp.js:804)
    at P._onPrivateMessage (xmpp.js:849)
    at I.Handler.run (strophe.umd.js:1875)
    at strophe.umd.js:3157
    at Object.forEachChild (strophe.umd.js:830)
    at I.Connection._dataRecv (strophe.umd.js:3146)
    at O.Bosh._onRequestStateChange (strophe.umd.js:5012)
o @ Logger.js:154
tryParseJSONAndVerify @ xmpp.js:824
_onPrivateMessage @ xmpp.js:849
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
send @ XmppConnection.js:478
sendDominantSpeakerEvent @ xmpp.js:790
b.sendDominantSpeakerEvent @ statistics.js:573
(anonymous) @ JitsiConferenceEventManager.js:525
a.emit @ events.js:152
e.onmessage @ BridgeChannel.js:321
`

**Comment by mcshaba** [comment]
I am also having this same issue. I recently was able to join with another user however as soon as a second user joins. It gets disconnected. In an attempt to fix that. I can not  even start an event without it automatically disconnecting. Event with Token Authentication and moderator feature
