### ISSUE TITLE
Inverted image. is the error `transform: scaleX(-1)`?

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#9081]
### Description:

Inverted image due to `transform: scaleX(-1)` to the video element.

Could you please advise when the fix is deployed on meet.jit.si?

Thank you

### Steps to reproduce:

Inverted with Jitsi Meet
https://meet.jit.si/

Ipevo VZ-R HDMI/USB Dual Mode Document Camera
https://www.ipevo.com/products/vz-r

### Expected behavior:

> is the image inverted on https://webrtc.github.io/samples/src/content/getusermedia/gum/ as well?
> If not then this is a product choice of applying a `transform: scaleX(-1)` to the video element.
> https://bugs.chromium.org/p/webrtc/issues/detail?id=12703

Image shows correctly, i.e. is not inverted, when using [gum](https://webrtc.github.io/samples/src/content/getusermedia/gum/).
![getUserMediaChromium89 0](https://user-images.githubusercontent.com/17465872/115932881-2d4be200-a4d1-11eb-81cb-c17db5cb5bcb.png)
![getUserMediaFirefox88 0](https://user-images.githubusercontent.com/17465872/115932884-3177ff80-a4d1-11eb-9878-99a5b4e335df.png)

#### Firefox 88.0
![Firefox88.0JitsiMeet](https://user-images.githubusercontent.com/17465872/115933009-6d12c980-a4d1-11eb-9175-26f692451af4.png)

#### Chromium 89.0
![Chromium89.0JitsiMeet](https://user-images.githubusercontent.com/17465872/115933278-e6122100-a4d1-11eb-8fb1-e5b9691a7f52.png)

#### Jitsi Meet App 2.8.5
Same results as Firefox and Chromium

### Server information:

- Jitsi Meet version: https://meet.jit.si/
- Operating System: Provided by 8x8

### Client information:

- Browser: Chromium Version 89.0.4389.128 (Official Build) for Linux Mint (64-bit)
- Browser: Firefox 88.0 (64-bit)
- App version: Jitsi Meet 2.8.5
- Operating System: Linux Mint 20.1 Cinnamon

### Additional information:

https://bugs.chromium.org/p/webrtc/issues/detail?id=12703
https://bugzilla.mozilla.org/show_bug.cgi?id=1192635#c22
https://github.com/jitsi/jitsi-meet/issues/5425

Thank you once again

**Comment by ovari** [comment]
@saghul is Jitsi Meet incorrectly using `transform: scaleX(-1)`? If so, can this be please be fixed? Thank you

**Comment by saghul** [comment]
This is the expected behavior. You see your own image flipped as in a mirror, but other participants see it ok. If you want to see yourself unmirrored, you can right click on the local view and click on Flip.
