### ISSUE TITLE
apt key not verifiable

### ISSUE THREAD

**Issue by Miyamoto72** [jitsi/jitsi-meet#9084]
### Description:

On Debian based systems apt verifies the validity of packages and repositories by checking GPG signatures. Jitsii does provide a repo key, but AFAICS there's no way to check if it really is the correct key I have downloaded: there's no fingerprint nor serial provided for the key. Additionally I didn't find the key that signed your repo (0xB4D2D216F1FD7806) on the keyservers e.g. at keyserver.ubuntu.com

### Expected behavior:

Repo key should be available at keyservers and signed by Jitsi developers. http://download.jitsi.org should provide key serial and fingerprint, preferably in the Jitsi docs (Debian section) and somewhere next to the links to the package repos.

### Actual behavior:

Neither key serial nor fingerprint are listed on the website or in the docs, pubkey of the repo key is not available at the keyservers

### Server information:

- Operating System: Debian 10 (Buster)

### Client information:

irrelevant

**Comment by saghul** [comment]
We rotated the key. You can download it again from the same place, that's the one we use right now.

**Comment by Miyamoto72** [comment]
It's not about the key only - right now there's no way of verifying that I have the correct key. Without fingerprint and serial I have not idea of knowing if I have downloaded the correct key. Without being able to get the key from a public keyserver I can never be sure that the key provided from presumably your website.

So - pls publish serial and fingerprint of the repo key on your webistes, export the public part of the repo key to the public keyservers and pls do revoke the previous key so nobody can mess around with the old key or a faked key.

**Comment by damencho** [comment]
It is already in public keyserver
https://keys.openpgp.org/search?q=dev@jitsi.org
https://community.jitsi.org/t/stable-repo-key-b4d2d216f1fd7806/97752
