### ISSUE TITLE
Can not connect with Android but Web or IOS.Use docker server

### ISSUE THREAD

**Issue by ChenMoGe2** [jitsi/jitsi-meet#9087]
### Description:

Can not connect with Android but Web or IOS.Use docker server

### Steps to reproduce:

1. Open server 5765-1 in docker
2. Connect with my private server at Android jitsi meet
3. Have wrong 'You have been disconnected.You may want to check your network connection' but It's ok for using internet

### Expected behavior:

I can use Android JitsiMeet to video chat with others.

### Actual behavior:

I can't use Android JitsiMeet to video chat with others.
![image](https://user-images.githubusercontent.com/32083531/116023877-a8eb9180-a67f-11eb-9428-a2abe4235bd2.png)

### Server information:

No logs change when I connect with the server using Android Jitsi meet.

### Client information:
[features/base/lib-jitsi-meet] Failed to load config from https://xxxx.xxxx.xx/config.js?room=ipa Error(TypeError){"message":"Network request failed"}

**Comment by ChenMoGe2** [comment]
Update.
I can connect the server using Android JitsiMeet by connecting Charles https proxy.But if I disconnect the proxy,I can not connect the Jitsi server

**Comment by leonard-kawhi** [comment]
i got a same problem. what can i do for this?
