### ISSUE TITLE
Participants can't hear each other upon tab reload

### ISSUE THREAD

**Issue by pabelenda** [jitsi/jitsi-meet#9092]
### Steps to reproduce:

1. Create a meeting
2. Establish at least audio communication between at least two participants
3. One of the participants should reload the tab where the meeting is running

### Expected behavior:

User is back on the meeting, can mute and un-mute, and the rest of the users can hear them and they can hear everyone

### Actual behavior:

1. User is back on the meeting, but can't hear anyone
2. The user that reloaded the page see everyone else as muted
3. The rest of the participants are not muted on their side
4. The rest of the users can hear the user who reloaded

### Server information:

- Jitsi Meet version: 2.0.5745-1
- Operating System: Debian 10

### Client information:

- Browser1: 89.0.4389.114 (Developer Build) built on Debian 10.9, running on Debian 10.9 (64-bit)
- Browser2: Version 90.0.4430.85 (Official Build) snap (64-bit) Ubuntu 20.04

- App version: last one available on flathub
- Operating System: Debian testing

**Comment by damencho** [comment]
Please, when you have questions or problem use the community forum before opening new issues, thank you.

Update to latest stable, and upload js console logs from the user that cannot be heard.
