### ISSUE TITLE
toggleShareScreed doesn't work as expected

### ISSUE THREAD

**Issue by nurSaadat** [jitsi/jitsi-meet#9096]
### Description:

I want to create a separate button to toggle share screen. There is a handleClick function passed to Button class. In that funclion I handle Jitsi event and set screenSharing to true.

```
handleClick={() => {
                    handleJitsiEvent('toggleShareScreen'); 
                    setIsScreenSharing(!isScreenSharing);
                }}
```

To handle Jitsi event I created a context which sets Jitsi API and executes commands

```
export const JitsiAPIContext = createContext();

export const JitsiAPIProvider = (props) => {

    const [jitsiAPI, setJitsiAPI] = useState('');
    const setAPI = (api) => setJitsiAPI(api);

    const handleJitsiEvent = (command, value) => {
        console.log("HERE: ", command, value);
        jitsiAPI.executeCommand(command, value);
    };

    return (
        <JitsiAPIContext.Provider
        value={{
            jitsiAPI,
            setAPI,
            handleJitsiEvent,
        }}
        >
        {props.children}
        </JitsiAPIContext.Provider>
    )
}
```

### Steps to reproduce:

1. Create a Button class and a Context
2. Create a button to toggle screen
3. Run the project and try clicking on the button

### Expected behavior:

A dropdown window appears that suggests available screen share tabs and/or mods

### Actual behavior:

Button changes its color, so, setIsScreenSharing changes its value, but the screen is not actually shared.

### Server information:

- Jitsi Meet version: 0.1.0

### Client information:

- Browser / app version: Chrome/Firefox
- Operating System: Ubuntu

**Comment by saghul** [comment]
The screen-sharing UI is presented by the browser, not us (except in Electron) and the existing button already takes care of opening that dialog.
