### ISSUE TITLE
Login/Authentication not working while in active conference

### ISSUE THREAD

**Issue by AlphaDE** [jitsi/jitsi-meet#9097]
### Description:

Trying to authenticate/login to become moderator after joining a conference as guest is not working anymore. From the 3-dot-menu - Own name - Profile tab - login, no dialog to enter the credentials appears anymore.

### Steps to reproduce:

1. Open a conference (moderator present, lobby active, password protected)
2. Join as a second user
3. Click on 3-dot - own name - Profile tab - login

### Expected behavior:

A login window to enter username and password should appear.

### Actual behavior:

Profile window closes, nothing further happens, no login window appears.

### Server information:

- Jitsi Meet version: 2.0.5765
- Operating System: Ubuntu 20.04.2 LTS

### Client information:

- Browser / app version: Chrome / Firefox
- Operating System: Windows 10 Pro

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

That is fixed in latest versions. You can update from the unstable repo and report back whether it works.
