### ISSUE TITLE
Typo in IFrame API Commands

### ISSUE THREAD

**Issue by p-fruck** [jitsi/jitsi-meet#9098]
https://github.com/jitsi/jitsi-meet/blob/546df558e3428055985deac56526049c83a46449/modules/API/external/external_api.js#L37

Theres a small typo in the external IFrame API - I guess this should be called `initiatePrivateChat`. I suspected this to be a typo in the [documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#initiateprivatechat), but after trying it out I realized the command indeed has a typo.

**Comment by saghul** [comment]
Nice catch! Would you like to send a PR?
