### ISSUE TITLE
Picture-in-Picture (PIP) doesn't work in Android app (with jitsi-meet-sdk) after screen sharing

### ISSUE THREAD

**Issue by xpst** [jitsi/jitsi-meet#9099]
### Description:

It is not possible to switch to PIP mode after screen sharing - when screen sharing is stopped.

### Steps to reproduce:

1. Connect to a room
2. Click Start screen sharing
3. Click Stop screen sharing
4. Try to switch to PIP mode

### Expected behavior:

App is switched to PIP mode

### Actual behavior:

No reaction on PIP button click.

It looks like PIP is disabled during screen sharing and it is not enabled after screen sharing is stopped.

### Server information:

https://meet.jit.si

### Client information:

Verified on the latest JitsiSDKTest with SDK version 3.4.0:
https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/android/java/JitsiSDKTest

### Additional information:

![jitsi_issue_20210428](https://user-images.githubusercontent.com/7100711/116387189-39aea280-a823-11eb-8b21-9a0336c15d3c.gif)

**Comment by saghul** [comment]
Ping @tmoldovan8x8

**Comment by tmoldovan8x8** [comment]
Hi @xpst, thanks for pointing this to us. It is valid and will have a look at it.

**Comment by devashish-gopalani-cognoai** [comment]
Hi @saghul I was not sure if I should be raising a new issue for this question hence I am asking it here... I had disable pip mode using the feature flag. Post that, I had launched a jitsi call from my app. The call launched successfully but after I came back to my app by pressing the back button, the call got disconnected. Is this the expected behavior? I am using jitsi SDK version 3.5.0 and android OS is 8.0

**Comment by kimtrantrong** [comment]
I have the same problem

**Comment by bharathraj-e** [comment]
Got a trick 😊

I just commented out the line which disables Pip during screen share.

> react/features/base/conference/middleware.native.js

line no : 56

> // setPictureInPicture(true)

**Comment by saibotma** [comment]
Same issue on iOS.

**Comment by saibotma** [comment]
The button to minimize Jitsi into “fake” PiP in iOS does not work either, after screen sharing. That's what I wanted to say.

**Comment by saghul** [comment]
Gotcha.

**Comment by saghul** [comment]
@tmoldovan8x8 Can you PTAL?

**Comment by tmoldovan8x8** [comment]
Fixed and it should be available in the next release https://github.com/jitsi/jitsi-meet/pull/10516
