### ISSUE TITLE
Etherpad not working on IOS, opening shared document causes endless loading on IPad

### ISSUE THREAD

**Issue by OneTwoBarbecue** [jitsi/jitsi-meet#9104]
### Description:

When opening a shared document from within the jitsi-meet-app on ipad, the etherpad-interface shows up but results in an endless loading screen without permitting to edit the shared document.
When starting the meeting via safari and opening the meeting via browser everything works fine.
On Android and via PC/laptop/desktop-clients everything works as expected.

### Steps to reproduce:

1. open Jitsi-meeting inside IOS-app
2. try to open shared document
3. -> Etherpad shows up with endless loading screen

### Expected behavior:

Etherpad should show up allowing edit of shared document

### Actual behavior:

Etherpad loads endlessly

### Server information:

- Jitsi Meet version:  2.0.5765
- Operating System: Ubuntu 20.04.02
- Etherpad version 1.8.13 running on Debian 10 buster

### Client information:

- Browser / app version: 21.1.0 build 113
- Operating System: IOS 14.4.2

## Screenshot
![056F0281-B921-4076-A277-72D05799ECD5](https://user-images.githubusercontent.com/59665779/116450970-397ec900-a85c-11eb-91d1-27ce7a6d8a98.jpeg)

**Comment by OneTwoBarbecue** [comment]
Nobody else having this issue? Or did I post it in the wrong issue-section?

**Comment by OneTwoBarbecue** [comment]
Problem persists in Version 21.2.0 build 114

**Comment by pasanediri97** [comment]
Did you able to fix this? I am also having this issue.

**Comment by OneTwoBarbecue** [comment]
Unfortunatley not - problem still persists in version 21.3.0 build 117 :(

**Comment by OneTwoBarbecue** [comment]
Still not working in 21.3.1 build 119.
Any ideas?

**Comment by saghul** [comment]
We have not worked on a fix for this, sorry.

**Comment by saghul** [comment]
I have just tried it with our latest beta (21.4.0) and I didn't get an endless spinner.

**Comment by OneTwoBarbecue** [comment]
Great! I will check it out as soon as 21.4.0 stable is available :)

**Comment by saghul** [comment]
Just to be clear, we haven't fixed anything :-)

You can also opt into the beta, check the README for instructions.

**Comment by OneTwoBarbecue** [comment]
Thank you for the information. I did install the beta and it‘s still behaving like I wrote above on IPad Air 4. When using Safari instead of Jitsi-Meet everything works as expected. Android app works as expected (Samsung Galaxy 7). Windows and LInux apps show correct behavior too.

Do you have a public jitsi-meet instance with etherpad installed which I could try instead of my self hosted one? If this would result in etherpad working it would be clear that I‘d have to check my etherpad instance and/or my reverse proxy/dns configuration.

@pasanediri97 Have you been able to fix the issue?

**Comment by saghul** [comment]
You can test on meet.saghul.net. I think it has Etherpad 1.8.6.

**Comment by OneTwoBarbecue** [comment]
Thank you very very much. This instance works perfectly on IOS. So I‘ll have a look into this. I‘ll comment here and on etherpad as soon as I find a solution for this. Since this is not on the jitsi-side I close this issue.

**Comment by OneTwoBarbecue** [comment]
This is most likely to be an issue with etherpad and not with jitsi.

Etherpad 1.8.12 is the latest version running fine under IOS-Jitsi-app.

I created an issue at the etherpad repository: [https://github.com/ether/etherpad-lite/issues/5198]

**Comment by saghul** [comment]
Thank you!
