### ISSUE TITLE
Enabling mic when watching YouTube doesn't work from the main menu, but works from the toast message

### ISSUE THREAD

**Issue by icekool** [jitsi/jitsi-meet#9112]
### Description:

Have been using youtube video sharing on JaaS, and have noticed that there are issues with enabling your microphone.
When a youtube video is being shared if you attempt to unmute yourself it automatically mutes the youtube video.

If you speak, and unmute yourself from the toast asking you whether you would like to unmute, you are able to unmute while the video audio continues to play.

The functionality would be better to work as per the toast message.

This issue occurs slightly differently for the sharer and the recipients of the youtube share

### Steps to reproduce:

**As the sharer of a youtube video**
1a. Share any youtube video
2a. Click on your mic to unmute
3a. Youtube video audio will automatically mute
4a. Switch back on the Youtube video audio and you will be muted
5a. Speak so the toast message appears.
6a. Unmute from the toast
7a. The Youtube video audio will continue to play and you will be unmuted

**As the receiver of a youtube video**
1b. Wait till youtube video is started
2b.  Click on your mic to unmute
3b. Your audio will temporarily unmute then remute  
4b. Wait till you are remuted
5b. Speak so the toast message appears
6b. Unmute from the toast
7b. You will be successfully unmuted.

### Expected behavior:

User audio and youtube audio should act independently and the mic on and off should not affect each other.
The mic button at the bottom should be able to switch the audio on and off for a user without remuting.

### Actual behavior:

For the Sharer of the video when using the Mic button on the bottom menu the audio for users and youtube is mutually exclusive
For the receiver the audio will away remute if trying to use the mic button on the bottom menu.

The Toast message successful unmuted for both situations.

### Server information:

Jitsi as a Service

### Client information:

Chrome 90.0.4430.93, Windows 10

**Comment by saghul** [comment]
We have no plans to change the current behavior.

**Comment by icekool** [comment]
@saghul actually looking at the newest version of Jitsi I think this is fixed. So this should be closed as fixed I believe.
