### ISSUE TITLE
React Core > Semantic Issue > Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>>*' with an rvalue of type 'NSArray<Class>*'

### ISSUE THREAD

**Issue by egemenkayalidere** [jitsi/jitsi-meet#9115]
After upgrade XCode to 12.5, project started not to work with this error.

React Core > Semantic Issue > Cannot initialize a parameter of type 'NSArray<id<RCTBridgeModule>>*' with an rvalue of type 'NSArray<Class>*'

--

"react-native": "github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551",

"lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#087a8e19eb0126ac48c1fa147aba737c8783bd36",

--

XCode Version 12.5
macOS Big Sur Version 11.3

**Comment by saghul** [comment]
Have you tried latest master? We fixed that yesterday.

**Comment by saghul** [comment]
This was fixed in https://github.com/jitsi/jitsi-meet/commit/399fac78f53ffd0b55ceaaf740c7a036f36b1d58
