### ISSUE TITLE
User login to create a confernce does not work when authenticated user joins the conference 

### ISSUE THREAD

**Issue by qchn** [jitsi/jitsi-meet#9121]
### Description:

Hello,
we use authenticated domains within jitsi, only authenticated (ldap) users can create a conference.

When person A is the first person who is about to create a conference and actually logs in using the login dialog, when another person – who is already logged in – joins the conference, person A is unable to log in using the dialog and when person A is pressing the cancel button, they will be kicked out of the conference.

### Steps to reproduce:

1. person A creates a conference, room: XYZ 
2. person A is hitting the login button
3. person A is about to login
4. person B joins the conference XYZ and is already logged in
5. person A is trapped in the login dialog and can do nothing but cancel
6. person A hits cancel button and is getting kicked out of the room

### Expected behavior:

person A should be able to login.

### Actual behavior:

see "Steps to reproduce"

### Server information:

- Jitsi Meet version: 2.0.5765-1
- Operating System: Debian Buster

### Client information:

- Browser / app version: Firefox latest
- Operating System: Linux

### Additional information:

–

**Comment by saghul** [comment]
What do you mean by "creating" the conference? Are you using the reservation system? Otherwise a conference is created when someone joins.

**Comment by qchn** [comment]
Hey @saghul 

I am talking about this, our setup only allows authenticated users to "create" a conference

![Bildschirmfoto 2021-05-03 um 11 55 39](https://user-images.githubusercontent.com/747735/116863370-81a83d80-ac06-11eb-8542-864c73895fc1.png)

**Comment by saghul** [comment]
So while A is seeing this screen B joins and creates the room, but the dialog doesn't vanish for A?

**Comment by qchn** [comment]
Exactly but actually when the login screen appears 

![Clipboard - May 4, 2021 10_10 AM](https://user-images.githubusercontent.com/747735/116976431-6bab8300-acc1-11eb-9dec-eebb47f976c1.png)

**Comment by saghul** [comment]
What happens when you press cancel? Doesn't it login automatically, since there is another user already in?

**Comment by qchn** [comment]
@saghul Unfortunately, you are trapped in the dialog. 
If you press Login, nothing happens. If you press cancel, you will get kicked out of the room.

**Comment by saghul** [comment]
But if you reload you are able to join, right?

**Comment by qchn** [comment]
@saghul right

**Comment by Calinteodor** [comment]
@qchn I couldn't repro with latest updates. Please try again with latest unstable.

**Comment by Calinteodor** [comment]
@qchn Let me know if you managed to repro after the bug is fixed.

**Comment by saghul** [comment]
No follow-up, closing.
