### ISSUE TITLE
Google calendar integration

### ISSUE THREAD

**Issue by dyros26** [jitsi/jitsi-meet#9132]
Cannot add meeting link in calendar tab. There is and error saying "Cannot read property 'match' of undefined" in the logs when you click the add meeting link button.

![Screen Shot 2021-05-04 at 11 04 32 AM](https://user-images.githubusercontent.com/49423503/116956731-92b98300-acc8-11eb-818e-d955744a18f3.png)

**Comment by damencho** [comment]
Do you reproduce this on meet.jit.si?

**Comment by dyros26** [comment]
> Do you reproduce this on meet.jit.si?

Yes its on meet.jit.si

- click Connect your calendar
- sign in your google account
- create an event on google calendar
- the created event in google calendar will show on jitsi calendar tab
- click add meeting link button
- then nothing happens because of this error

![Screen Shot 2021-05-05 at 9 59 02 AM](https://user-images.githubusercontent.com/49423503/117089683-c0fe9780-ad88-11eb-9795-b0071447ad6e.png)
