### ISSUE TITLE
Could not resolve dependency: npm ERR! peer react@"16.9.0" from react-native@0.61.5-jitsi.2 npm ERR! node_modules/react-native npm ERR!   react-native@"github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551" from the root project

### ISSUE THREAD

**Issue by egemenkayalidere** [jitsi/jitsi-meet#9138]
After upgrade XCode to 12.5, project started not to work with this error.

Could not resolve dependency: npm ERR! peer react@"16.9.0" from react-native@0.61.5-jitsi.2 npm ERR! node_modules/react-native npm ERR!   react-native@"github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551" from the root project

--

"react": "16.12",

"react-native": "github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551",

"lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#087a8e19eb0126ac48c1fa147aba737c8783bd36",

--

XCode Version 12.5
macOS Big Sur Version 11.3

**Comment by saghul** [comment]
This was fixed in https://github.com/jitsi/jitsi-meet/commit/399fac78f53ffd0b55ceaaf740c7a036f36b1d58 and https://github.com/jitsi/jitsi-meet/commit/0fcdb6f2483ab972877280971080b7f56b6288b0

**Comment by egemenkayalidere** [comment]
I applied all fixes. But the same error is going on as below.

--

What I did ?

npm i a-package-name

What I get ?

While resolving: xxx@0.0.0
npm ERR! Found: react@16.12.0
npm ERR! node_modules/react
npm ERR!   react@"16.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.9.0" from react-native@0.61.5-jitsi.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551" from the root project

--

Thanks for your supports.

**Comment by saghul** [comment]
Are you trying to build Jitsi Meet or is it a different project? What Node and npm versions are you using?

**Comment by egemenkayalidere** [comment]
Yes, I try to build Jitsi Meet.

--

Node: v14.15.0
npm: 7.6.3

--

Thanks for your supports @saghul

**Comment by saghul** [comment]
Try to downgrade to Node 12 and npm 6.
