### ISSUE TITLE
Required kid param with shared secret

### ISSUE THREAD

**Issue by d3473r** [jitsi/jitsi-meet#9142]
### Required `kid` param with shared secret

A user opened an [issue](https://github.com/d3473r/jitsi-keycloak/issues/28) on my [jitsi-keycloak](https://github.com/d3473r/jitsi-keycloak) project because he is getting an error using it with the latest jitsi-meet version.
[This](https://github.com/jitsi/jitsi-meet/commit/3a8bd852b277788925bba5f184e59e605f239cf3) commit introduced a check for the `kid` param in the JWT:
https://github.com/jitsi/jitsi-meet/blob/6aae1c024d045faafd097f8f5e61edec23fff04e/react/features/base/jwt/functions.js#L70-L77

Because of this check and no `kid` param present he is getting the following error:

> 2021-04-20T13:09:17.594Z [features/base/conference] JWT parsing error:
Array [ "- Key ID(kid) missing" ]
Logger.js:154:22
2021-04-20T13:09:17.614Z [JitsiMeetJS.js] : UnhandledError: connection.passwordRequired Script: null Line: null Column: null StackTrace: n/a Logger.js:154:22
Uncaught (in promise) connection.passwordRequired

### Steps to reproduce:

1. Use [jitsi-keycloak](https://github.com/d3473r/jitsi-keycloak) to log in to jitsi

### Expected behavior:

The `kid` param should only be required when using private key to sign the JWT as it is stated in the [docs](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#token-structure):

> Alternately the token may be signed by a private key and authorized via public keyserver using RS256 tokens. In this mode, the 'kid' header of the JWT must be set to the name of the public key. The backend server must be configured to fetch and confirm keys from a pre-configured public keyserver.

### Actual behavior:

The `kid` param is required even when using a shared secret with HMAC

Regards,
d3473r

**Comment by saghul** [comment]
Ping @horymury

**Comment by horymury** [comment]
Addressed here:
https://github.com/jitsi/jitsi-meet/pull/9146

**Comment by d3473r** [comment]
> Addressed here:
> https://github.com/jitsi/jitsi-meet/pull/9146
> 
> Please note that the `kid` error is not breaking, it did not prevent the auth flow. 
> So:
> `2021-04-20T13:09:17.614Z [JitsiMeetJS.js] : UnhandledError: connection.passwordRequired Script: null Line: null Column: null StackTrace: n/a Logger.js:154:22
> Uncaught (in promise) connection.passwordRequired`
> 
> might be caused by an actual issue in JWT.

Thanks, good to know. I'll forward this to the user having the issue.
