### ISSUE TITLE
very blurry self video when using virtual backgrounds 

### ISSUE THREAD

**Issue by artknight** [jitsi/jitsi-meet#9144]
### Description:

As far as I understand it Jitsi is using the same technology for virtual backgrounds as Google Meet. https://ai.googleblog.com/2020/10/background-features-in-google-meet.html

However, the quality of the self image is WAY crisper in Google Meet ( and in the article above ) than in Jitsi! Jitsi is blurry, feels like you are in a twilight zone.. a person's body edges are fading out and glowing....

### Steps to reproduce:

Go to meet.jit.si and set a virtual background

### Expected behavior:

The person's image needs to be much crisper, just like shown in the google meet article 
https://ai.googleblog.com/2020/10/background-features-in-google-meet.html

### Actual behavior:

blurry contours of the person, does not look good!

### Additional information:

I do not understand why there would be such a HUGE difference in quality between google meet ( article ) and Jitsi if the same technology is used!

**Comment by saghul** [comment]
Can you provide a sample screenshot of what you mean?

**Comment by artknight** [comment]
<img width="905" alt="Screen Shot 2021-05-04 at 9 54 00 PM" src="https://user-images.githubusercontent.com/157762/117089470-a34b1700-ad23-11eb-9441-40b4c6abce78.png">

**Comment by artknight** [comment]
@saghul no offense but the blur around the edges is terrible compared to the google meet article. :(

**Comment by paweldomas** [comment]
could it be there's no bilateral filter effect applied for smoothing of the low resolution mask?

**Comment by artknight** [comment]
@saghul another issue is that I am always seeing LD whereas the VB is running on my local network and the laptop cam is HD.

my settings in the config.js
```
constraints: {
        video: {
            aspectRatio: 16/9,
            height: {
                ideal: 720,
                max: 720,
                min: 240
            }
        }
    },
```

**Comment by saghul** [comment]
Is your bridge channel working correctly? Check the browser console logs for errors.

**Comment by saghul** [comment]
Do you see a difference between your server and meet.jit.si ?

We do apply edge smoothing but there could be room for improvement there.

While we use same model, the entire pipeline is not exactly the same.

**Comment by artknight** [comment]
@saghul Yes, the rendering is exactly the same on meet.jit.si! 

Btw, I fixed the LD issue, turns out my config.js had a wrong entry in there.

**Comment by artknight** [comment]
I also found another solution that seems amazing https://github.com/PeterL1n/BackgroundMattingV2

However, back to the issue at hand.... we really should to make our virtual backgrounds work at least as good as google meet!

**Comment by saghul** [comment]
> we really should to make our virtual backgrounds work at least as good as google meet!

Sure thing, do you have any ideas?

**Comment by artknight** [comment]
Yeah that link I posted. Implementing that would make us the leader in that space. The technology that is used (MIT licensed) is far more superior than anything I have ever seen!
  
  
  
    
  

  
  
>

**Comment by saghul** [comment]
From the repo:

> Disclaimer: The video conversion script in this repo is not meant be real-time. 

So it doesn't look like we can consume it directly in its current form.

That said, we'd be happy to take patches if a better model / pipeline arises with a compatible license.

**Comment by dbrgn** [comment]
That model does look interesting, but it probably requires some setup by the user:

> Our model requires capturing an additional background image and produces state-of-the-art matting results at 4K 30fps and HD 60fps on an Nvidia RTX 2080 TI GPU.

I could imagine that this would require capturing a still image without you on the image as a setup-step. A lot of users might be quite challenged by something like that. And if they move the camera during the meeting (e.g. when using a laptop or a smartphone) that might break.

**Comment by saghul** [comment]
Closing since there is nothing actionable for now. We just updated the model FWIW: https://github.com/jitsi/jitsi-meet/pull/10256
