### ISSUE TITLE
Wrong resolution when screen sharing in dual-monitor

### ISSUE THREAD

**Issue by apsicsm** [jitsi/jitsi-meet#9147]
Using Chrome on Windows, on a dual-monitor setup, the screen sharing resolution is taken from the monitor Chrome is running, not for the screen you're sharing.

Example: I have a laptop with a 1366x768 resolution, and an external 1920x1080 monitor. When I run Chrome with Jitsi on the laptop and try to share the 1080 screen, other users see a "pixelated" version of my screen. If I stop sharing, move the Chrome window to the bigger screen and share again, the resolution is correct.

Can this be fixed or is it some limitation in Chrome?

**Comment by saghul** [comment]
Looks like a Chrome bug to me.

**Comment by apsicsm** [comment]
I think you are right. I had tried with Chrome and Brave and had the same result, but they're both using Chromium so I guess it was not a very useful test.
I just tried with Firefox and it worked as it should. Sorry for not trying that one before :(
Thank you very much!
