### ISSUE TITLE
Full screen on videos in browser (at least github) stops screen sharing and shows your own video

### ISSUE THREAD

**Issue by chagai95** [jitsi/jitsi-meet#9148]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by chagai95** [comment]
I'll add more info later

**Comment by saghul** [comment]
Please don't open empty issues. What's the point of opening one without any details?

**Comment by chagai95** [comment]
Sorry, i now filled in more details and I will continue to gather info about this...
