### ISSUE TITLE
Save passwords on Android or iPhone

### ISSUE THREAD

**Issue by mghadam** [jitsi/jitsi-meet#9154]
**Is your feature request related to a problem you are facing?**
Every time I want to join a room in jitsi on Android or iPhone, I need to manually enter my username and password :

Jitsi meet Android:
![image](https://user-images.githubusercontent.com/10244293/117289233-9b08ee00-ae81-11eb-9d2f-952605821bf8.png)

Jitsi meet iPhone:
![image](https://user-images.githubusercontent.com/10244293/117289278-a78d4680-ae81-11eb-8267-d5a280ec229e.png)

**Describe the solution you'd like**
I would like to be able to save the username and password on Android or iPhone, similar to Jitsi Web on PC:

![image](https://user-images.githubusercontent.com/10244293/117289489-e3281080-ae81-11eb-85e2-4b039ffde641.png)

The web browser on PC automatically saves username and password for Jitsi room as shown in the above screenshot. 

**Describe alternatives you've considered**
An alternative solution could be to add a  "Keep me logged in" button on the login page so that it does not ask for any username and password again for next sessions in the same room.

**Comment by saghul** [comment]
We have no plans to implement this, sorry.
