### ISSUE TITLE
Audio of some participants cannot be heard by some other participants

### ISSUE THREAD

**Issue by JakeQZ** [jitsi/jitsi-meet#9168]
### Description:

In a meeting with 7 people, audio only (video disabled by participants), some people could not hear the audio of some others.  Typically about 3-4 people could not hear any audio from about 2 participants.  Reloading usuaully fixed the issue, but only temporarily.  The audio of participants would gradually drop out more and more, but only to some other participants, apparently randomly.

This issue seems to be becoming more prevalent.  We have seen it occasionally in the past, but it has now reached the point where the service is almost unusable.

### Expected behavior:

Audio should not drop out.

### Actual behavior:

Audio from some participants drops out completely and permanently until page is reloaded, then drops out again.

### Server information:

https://meet.jit.si/

### Client information:

All browsers are affected.

**Comment by damencho** [comment]
We have discovered an issue with the release from yesterday on meet.jit.si and is fixed at the moment.

Please, when you have questions or problems use the community forum before opening new issues, thank you.
