### ISSUE TITLE
native or closer to native desktop app

### ISSUE THREAD

**Issue by je-vv** [jitsi/jitsi-meet#9170]
I'd like you to consider making a native multi platform desktop jitsi-meet app, based on Qt as my preference.  If not as native, perhaps making it closer to native, like being based on Flutter for example.  As it runs on the desktop right now is just based on electron, which means it runs just on top of chromium.

**Comment by damencho** [comment]
This is a web app and as such needs a browser to run. It is already multiplatform as on all platforms there is a browser that supports webrtc and can run this app. Anything else is out of the scope of this project. 

You can take a look at jitsi-meet-electron, how it uses electron and jitsi-meet to create a multiplatform app, you can use the same approach with any other browser (QT or not) that allow to be embedded in an app and that supports webrtc.

**Comment by je-vv** [comment]
BTW, I use jitsi-meet-electron, and it doesn't allow you to file feature requests.  I guess only jitsi-meet allows that.  My point is jitsi-meet-electron is far from native, and it'd be great if in the future such app gets available.

**Comment by damencho** [comment]
We do not have resources for such an enormous project. Creating a new browser is not our goal, we prefer to concentrate in the video conferencing part of things. Thank you.
