### ISSUE TITLE
Jitsi iOS Compile prematurely ends with WebRTC "file not found" error

### ISSUE THREAD

**Issue by cheturavi3** [jitsi/jitsi-meet#9173]
node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule.h:15:9: 'WebRTC/RTCMediaStream.h' file not found

It gives error with different files in every build under WebRTC. Any ideal or solution would be appreciated. Thanks in advance. 

Xcode version: 12.5
pod version: 1.10.1

**Comment by saghul** [comment]
Did you run npm install and pod install? Or are you using the SDK through CocoaPods directly?

**Comment by cheturavi3** [comment]
I ran npm install and pod install. Not using SDK through CocoaPods directly.

**Comment by saghul** [comment]
What Node and npm versions did you use? Also, are you trying latest master or a specific revision?

**Comment by saghul** [comment]
Can you test Node 12 / npm 6 ? That what we use for our production builds.
