### ISSUE TITLE
Message area masked by system navigationbar

### ISSUE THREAD

**Issue by e4basil** [jitsi/jitsi-meet#9176]
enter message area masked by system navigationbar

### Steps to reproduce:

1. Connect to a room
2. Click the chat icon
3. Type any msg

### Expected behavior:

The message area must be shown without any issue

### Actual behavior:

Enter message area masked system navigationbar

### Server information:

https://meet.jit.si/

### Client information:

- Mobile:  Galaxy s9+

### Additional information:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/9576366/117650044-da02b080-b1ad-11eb-83f6-22855644e0d7.png)

**Comment by saghul** [comment]
This has been fixed in the last version.
