### ISSUE TITLE
Unable to upgrade Jitsi, Debian unstable release: Release is not signed

### ISSUE THREAD

**Issue by qchn** [jitsi/jitsi-meet#9177]
### Description:

We mirror the unstable release in our repository server. 
At the moment, we can not install the nightly release as an error occurs.

### Steps to reproduce:
While doing 'apt update':

W: GPG error: http://INTERNAL-MIRROR/download.jitsi.org unstable/ Release: Detached signature file '/var/lib/apt/lists/partial/INTERNAL-MIRROR_download.jitsi.org_unstable_Release.gpg' is in unsupported binary format
E: The repository 'http://INTERNAL-MIRROR/download.jitsi.org unstable/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Expected behavior:

Release should be signed

### Actual behavior:

Release is not signed

### Server information:

- Operating System: Debian Buster

### Client information:

/

### Additional information:

/

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

https://community.jitsi.org/t/stable-repo-key-b4d2d216f1fd7806/97752

**Comment by qchn** [comment]
Thanks for the hint, @damencho but that did not help, I imported the the dev@jitsi.org key and now get the following error when trying to install an unstable release. There is something wrong with the unstable repository.

```
Release' does not have a Release file.
```

**Comment by saghul** [comment]
Our unstable Docker images are built every day off the unstable repo and I have not seen such error. What steps did you do exactly?
