### ISSUE TITLE
Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules

### ISSUE THREAD

**Issue by 473817087** [jitsi/jitsi-meet#9187]
Why would you prompt such an error, is it where I have no configuration?
Always Embed Swift Standard Libraries is  set to yes!
<img width="847" alt="image" src="https://user-images.githubusercontent.com/12890477/117904030-34615580-b303-11eb-82bb-5d34b32cf3df.png">

**Comment by saghul** [comment]
Don't disable modules. Not sure what else I can say :-)
