### ISSUE TITLE
failed to load config.js from in android >>>> 'Failed to load config from https://domainname/config.js?room=test'

### ISSUE THREAD

**Issue by c80617** [jitsi/jitsi-meet#9188]
### Description:

I use the jitsi android smpale code to create my app,
I can connect to "https://meet.jit.si".

But when I connect to my jitsi service,
My android device has instll my SSL certification,
I have a personal dns server.
I get the error message:
failed to load config.js from in android >>>> 'Failed to load config from https://domainname/config.js?room=test'
the url (domain name) is working fine in web browser but not working in android client.
i can connect to my url when using the jitsi meet app i downloaded from play store

so what should i do to modify my app ssl connection?

![image](https://user-images.githubusercontent.com/18019584/117942728-f7668480-b33d-11eb-8df0-0eacf07fa4c5.png)

**Comment by saghul** [comment]
Is that a valid domain? I cannot resolve it.
