### ISSUE TITLE
Correct way of combining URI parameters

### ISSUE THREAD

**Issue by stevenmos** [jitsi/jitsi-meet#9194]
### Description:

I'm not sure if this is a bug.  #8457 and #5816 describe two url parameters to reduce client cpu load.  I've tried to combine them, as

    https://meet.jit.si/NAME#config.channelLastN=1&disableAudioLevels=true

### Steps to reproduce:
but when I have used this on the meet.ji.si instance I find that either one or both do not work, yet they work separately.

### Expected behaviour:
Both effects should work together.

### Actual behavior:
One or both url parameters do not work.

### Server information:
meet.jit.si

### Client information:
- Browser / app version: Firefox 88.0.1
- Operating System: Solus

**Comment by damencho** [comment]
Please when you have questions or problems, use the community forum, thank you.

It is `https://meet.jit.si/NAME#config.channelLastN=1&config.disableAudioLevels=true`
