### ISSUE TITLE
Screen Share audio feedback bug.

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#9197]
### Description:

I can hear my own voice when another participant screen shares with audio.

### Steps to reproduce:

1. Start a call with a friend (or enemy, I won't judge)
2. Have the other participant share their screen. (with audio)
3. Talk and hear your own voice

### Expected behavior:

I shouldn't be able to hear my own voice like that.

### Actual behavior:

I can hear my own voice.

### Server information:

- Jitsi Meet version: Stable 2.0.5870
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Electron Client 2.8.6
- Operating System: Windows 10 64x

### Additional information:

Sometimes it happens and sometimes it doesn't.

**Comment by cosysun** [comment]
hi， i meet the same issue，could you tell me how to fix it？

**Comment by cosysun** [comment]
@DillFrescott i

**Comment by DillFrescott** [comment]
@cosysun Hello! I never ended up fixing it. I'm not sure why I closed the issue, could have been an accident!

**Comment by saghul** [comment]
Can you reproduce this in meet.jit.si when sharing a tab? Does it only happen when sharing the full screen?

**Comment by andrei-gavrilescu** [comment]
@DillFrescott Hello, is your friend (or enemy) using a headset or speakers?

**Comment by DillFrescott** [comment]
@andrei-gavrilescu They are using a headset

**Comment by DillFrescott** [comment]
@saghul Not sure, I don't have anyone at the moment to test it with but I might be able to later!

**Comment by andrei-gavrilescu** [comment]
@DillFrescott Managed to reproduce the issue, seems to only happen on electron most likely something to do with the echo cancellation parameters. Will investigate further.
Thanks for keeping tabs on this.

**Comment by DillFrescott** [comment]
@andrei-gavrilescu No problem!

**Comment by dann-merlin** [comment]
I also have this issue. The audio received through the screen share includes my own microphone. I don't think this issue should be closed.

For me the screen sharing party used the [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron) client on Windows and the watching party used the linux version of the same client.
