### ISSUE TITLE
Empty security modal

### ISSUE THREAD

**Issue by corby-github** [jitsi/jitsi-meet#9203]
### JitsiMeetSDK - Empty security modal on iOS 

On iOS (using `JitsiMeetSDK`), when `meeting-password` is disabled in `JitsiMeetConferenceOptions` using `setFeatureFlag`, users are presented with an empty dialog when the 'Security Option` menu item is tapped.

![empty_security|25%](https://user-images.githubusercontent.com/63730925/118122206-87e5a900-b3c0-11eb-9203-f73d6b0a5661.png)

### Steps to reproduce:

1. On iOS, using `JitsiMeetSDK`, create a new `JitsiMeetView` with `JitsiMeetConferenceOptions`. 

Example:
```
JitsiMeetConferenceOptions *options
          = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) 
{
            builder.room = self.meetingName;
            [builder setFeatureFlag:@"meeting-password.enabled" withBoolean:NO];
...
}
```

### Expected behavior:

If there is nothing to show in the dialog, the link to open the modal should probably be hidden, or at a minimum there should be some default `nothing to see here` text.

### Actual behavior:

An empty [OK] modal is displayed. (See image)

### Server information:

- Jitsi Meet version: 1.0.4900  / 2.1-478-gc6da57bd-1
- Operating System: self-hosted, ubuntu

### Client information:

- Browser / app version: JitsiMeetSDK as of 5/12/2021
- Operating System: iOS 14.5

### Discussion
https://community.jitsi.org/t/jitsimeetsdk-empty-security-modal-on-ios/99494

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/9215
