### ISSUE TITLE
Add feature flag to disable the Security Options link in JitsiMeetSDK

### ISSUE THREAD

**Issue by corby-github** [jitsi/jitsi-meet#9205]
**New Feature Flag to hide/disable the "Security Options" link**

It would be great to have a feature flag to disable the "Security Options" link. 

> 💡 Depending on how https://github.com/jitsi/jitsi-meet/issues/9203 is resolved, this feature may not be needed if the link is automatically hidden if all available options are disabled.
 
![security-options](https://user-images.githubusercontent.com/63730925/118123790-bfedeb80-b3c2-11eb-867f-1f0a02e25bb0.png)

Something like the following:

1. In `jitsi-meet/react/features/base/flags/constants.js `
```
export const ENABLE_SECURITY_OPTIONS = 'security-options.enabled';
```

2. In `SecurityDialogButton.js` - `jitsi-meet/react/features/security/components/security-dialog/SecurityDialogButton.js` -  around this [line](https://github.com/jitsi/jitsi-meet/blob/bf3726cb93cd4d26d9c135049d7a765a99c951f5/react/features/security/components/security-dialog/SecurityDialogButton.js#L65)
```
class SecurityDialogButton extends AbstractButton<Props, *> {
...

   function _mapStateToProps(state): Object 
   {
      const enabled = getFeatureFlag(state, ENABLE_SECURITY_OPTIONS, true);

      return {
         visible: enabled,
        _locked: locked || lobbyEnabled
      };
   ...
  }
}
```

### Related issue
https://github.com/jitsi/jitsi-meet/issues/9203

### Discussion
https://community.jitsi.org/t/jitsimeetsdk-empty-security-modal-on-ios/99494/9?u=corby

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/9215
