### ISSUE TITLE
Mark several files in /usr/share/jitsi-meet as "Config" Files so they are protected from being overwritten

### ISSUE THREAD

**Issue by ychromosome** [jitsi/jitsi-meet#9208]
I wanted to present a "privacy policy" below the "Conference-History" on the jitsy-main page since I live in Germany and we have to provide this information by law.
To comply with that I edited 
/usr/share/jitsi-meet/interface_config.js
 /usr/share/jitsi-meet/static/welcomePageAdditionalContent.html
/usr/share/jitsi-meet/css/all.css
It works fine but every update these files are overwritten by the defaults from your package.

Would it be possible, that these files would be marked as "config" files so the packager would at least ask me what to do.

The better option would be to allow these modifications in general and move this functionality to /etc/jitsi/meet/ itself.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues, thank you.

interface_config is deprecated and we will try to get rid of it.
all.css cannot be a config as it is needed to be replaced for new updates, and anyway you should not be touching it at all. 
You can use any of the hooks (the empty files like https://github.com/jitsi/jitsi-meet/blob/master/head.html) to add your css overrides. 

Things like head.html and static/welcomePageAdditionalContent.html, you can put your own versions in /etc and do an override similar to the config.js one https://github.com/jitsi/jitsi-meet/blob/2bce5acad35aa6ea865171c75841b2ee7b980b03/doc/debian/jitsi-meet/jitsi-meet.example#L57 and use the versions from etc and don't worry about updating.
