### ISSUE TITLE
Participant Panel knocking user always shows as “Fellow Jitser”

### ISSUE THREAD

**Issue by jsrobinson3** [jitsi/jitsi-meet#9211]
### Description:

The latest build of Jitsi, commit a39f2ae, has all the users who try to join via a lobby showing as “Fellow Jitser”, or the value of DEFAULT_REMOTE_DISPLAY_NAME, in the participant panel instead of the nickname they chose. I tested on a local build and on alpha.jitsi.net 

### Steps to reproduce:

1. Start a meeting
2. Enable Lobby
3. Open the Participant panel
4. In another browser join the meeting and put in a nickname when prompted
5. The participant panel will not show the nickname of the person trying to join. If you close the participant panel, it will.

### Expected behavior:

The participant panel should show the user's nickname when they are "knocking"

### Actual behavior:

The participant panel is instead showing the value of DEFAULT_REMOTE_DISPLAY_NAME instead of the nickname

### Server information:

- Jitsi Meet version: a39f2ae
- Operating System: U20

### Client information:

- Browser / app version: Chrome
- Operating System: Windows 10

### Additional information:

![jitsi-participant_panel2](https://user-images.githubusercontent.com/16910828/118183856-9e175780-b408-11eb-8cb3-bca924b5cbcf.gif)

**Comment by damencho** [comment]
I wonder whether this will fix it https://github.com/jitsi/jitsi-meet/pull/9199

**Comment by fremzy** [comment]
I presume this is fixed, because it works perfectly for me.

**Comment by damencho** [comment]
Hum, I reproduce it on alpha ... but not on meet.jit.si ...

**Comment by fremzy** [comment]
Just checked my server (updated to the latest unstable) and yes, it's not working now. It was fine on the previous version though, 'cos I checked earlier.

**Comment by damencho** [comment]
Thank you @vp8x8 :)
