### ISSUE TITLE
Add sdk api to change output audio device

### ISSUE THREAD

**Issue by wvffle** [jitsi/jitsi-meet#9212]
**Is your feature request related to a problem you are facing?**
As I've said in https://community.jitsi.org/t/the-reason-why-we-cant-change-output-device-with-sdk-api/99584, I don't quite understand the reasoning behind not having this ability in the API.

**Describe the solution you'd like**
Probably `JistsiMeetView` to have a setter for the audio device and getter for all audio devices with their types. 

**Describe alternatives you've considered**
There is always an option to compile sdk yourself. Though maintaining a fork simply to have the ability set the default device to earpiece or to have the power to change the device to something else in the runtime is a bit too much in my opinion.

**Comment by saghul** [comment]
Pull requests are welcome, as long as you keep the current behavior as the default.
