### ISSUE TITLE
App size to big

### ISSUE THREAD

**Issue by BhagirathGadhesariya** [jitsi/jitsi-meet#9213]
Using your demo code form git and create apk that apk size is to big its more then 100 mb How To reduce app size in my app only one page for getting meting id not any other page on app

**Comment by saghul** [comment]
It's not possible to reduce the size at the moment. We ship 4 architectures, if you don't want some of them you can use ABI splitting.

**Comment by harshmange44** [comment]
> 
> 
> It's not possible to reduce the size at the moment. We ship 4 architectures, if you don't want some of them you can use ABI splitting.

How can I perform ABI splitting?
