### ISSUE TITLE
App tries to load Gravatar image with disableThirdPartyRequests set to true

### ISSUE THREAD

**Issue by kiliankoller** [jitsi/jitsi-meet#9214]
### Description:

We are using Jitsi meet with JWT token here: https://sichere-videokonferenz.de/ The tokens do not include an email address.

When I set an email address under "Settings" and start a new conference, I see the following error in the console:

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://www.gravatar.com/avatar/32b38362a4fb8d2dee4e6e1d78668658?d=404&size=200 blockiert ("img-src").

So the browser was trying to load the Gravatar image, even though disableThirdPartyRequests is set to true.

### Steps to reproduce:

1. Open conference
2. Set email address under Settings
3. Open a new conference

### Expected behavior:

Do not load Gravatar image

### Actual behavior:

Browser tries to load Gravatar image

### Server information:

- Jitsi Meet version: jitsi-meet_5870 - 2.0.5870
- Operating System: Ubuntu 20

### Client information:

- Browser / app version: FF current
- Operating System: Mac OS

**Comment by csett86** [comment]
This is a duplicate / confirmation that #5670 still exists in the current stable 2.0.5870.

**Comment by csett86** [comment]
Closed via #9300

**Comment by saghul** [comment]
Fixed by #9300
