### ISSUE TITLE
Remove Cookie jitsiMeetId from local computer

### ISSUE THREAD

**Issue by coccochanel** [jitsi/jitsi-meet#9217]
Hi 
when i login into jitsi meet (installed in my server) i use jwt authentication.
Browsers store the cookie "jitsiMeetId" on local computer, so when i login to a room not created by mine, jitsi "see" that i'm authetnicated with the old jwt (created on room a where i am the admin), so i become tha admin of the room b.

How can i delete this cookie?
Is there a way easy to do that?

Thanks in advance for all who will want to answer me!!

CC

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Can you share your jicofo settings. 

Most probably you have enabled: `org.jitsi.jicofo.auth.URL=EXT_JWT:jitsi-meet.example.com` ? 

Drop that and see does that fixes your problem?

You can also try https://github.com/jitsi/jicofo/blob/b260941bc526b71f44484c18ae1e652828a763c9/src/main/resources/reference.conf#L14
