### ISSUE TITLE
meeting invitation using “Your Default Email”, bad behavior...

### ISSUE THREAD

**Issue by exdiogene** [jitsi/jitsi-meet#9220]
### Description:

When you are in a meeting room and click on “Share meeting invitation” and after select “Your Default Email”, instead of just launching the “mailto” protocol assigned application, it also create a new tab containing the link itself in Firefox URL bar and an empty page.

This seem to relate to the fact that the icon is not a simple link by itself but activate a javascript function when clicked…

### Expected behavior:

Only the assigned application for the “mailto” protocol should be launched!

### Actual behavior:

We always have to close the newly opened page after each invitation...

### Server information:

- Jitsi Meet version: 2.0.4857-1
- Operating System: Debian 9.6

### Client information:

- Browser / app version: FireFox
- Operating System: Windows 10

### Additional information:

This will occur on any browser and/or OS

**Comment by saghul** [comment]
AFAIK mailto link handling is up to Firefox, or whatever other browser, in this case.

**Comment by exdiogene** [comment]
But the problem is not related to Firefox or any other browser, it is "bad" coding for the "mailto" link!

The browsers handling of the "mailto" protocol is properly done.

If you put a simple link in a page like the following, the behavior is correct :

`<a href="mailto:rejean@MyDomain.com?subject=Test from Rej&body=Received correctly...">Send mail</a>`

But your code will open a new empty page instead, what is incorrect!

**Comment by saghul** [comment]
Ah I see what you mean now. I think @quitrk changed that recently to fix some issue. Was that the case Tudor?

**Comment by quitrk** [comment]
HI,

The mailto is already using an anchor link
The 'bad' coding is a target='_blank' applied to all links in that share meeting ui, as you can see [here](https://github.com/jitsi/jitsi-meet/blob/master/react/features/invite/components/add-people-dialog/web/InviteByEmailSection.js#L98)

Now, if we were to remove the '_blank' part just for the mailto link, we would get into another situation where people don't actually have a native application as their default email client, and the result would be replacing the whole meeting page with the web client (e.g Gmail)

**Comment by saghul** [comment]
@quitrk I think it'd be reasonable to not add `target='_blank'` for the `mailto` link, but keep it for the other URLs since they are just `https` URLs. WDYT?

**Comment by quitrk** [comment]
If we're comfortable with having some users be taken away from the meeting when accessing that link, I can update the code to do so

**Comment by exdiogene** [comment]
I have done some test with my Firefox browser and even if I had a link with "target='_blank'" to the "mailto:" it does not open a new tab. It seem that the behavior of Firefox is to not create a new tab even with a different target when it is the "mailto" protocol called!

So it seem that your script is not doing a simple link activation, it do something else...

**Comment by quitrk** [comment]
Please read my earlier comment. For users who do not have a native email app, the behaviour will be to redirect them to the web email client (in my case was Gmail)

**Comment by saghul** [comment]
> Please read my earlier comment. For users who do not have a native email app, the behaviour will be to redirect them to the web email client (in my case was Gmail)

Ah I had missed that myself too, I thought you meant the app.

Then I'm not sure we can do anything here.

**Comment by exdiogene** [comment]
I have check the behavior of Firefox with these 3 links and only the second one create a new tab : 

```
<a href="mailto:rej@MyDomain.com?subject=Test de Rej&body=Recu correctement..." target="_blank" rel ="noopener noreferrer">Send mail</a>

<a href="https://MyDomain.ca" target="_blank" rel ="noopener noreferrer">Test Website</a>

<a class="email" title="Email a friend" href="#" onclick="javascript:window.location='mailto:?subject=Interesting information&body=I thought you might find this information interesting: ' + window.location;">Javascript Email</a>

```
So, there must be a reason why your script is creating a new tab, even with the target argument?

Maybe its worth the try to not add the "target='_blank'" portion for the "mailto:" protocol?

By default, on Windows 10 the "mailto:" protocol is launching an internal "Courrier" application...

**Comment by quitrk** [comment]
I feel like I'm repeating myself. Not adding the `_blank` value will make the `target` to default to `_self`, which in turn, for Chrome users who don't have a native email app configured, replaces the current meeting tab with the web email client page (e.g. Gmail).

When did you start having the issue you're describing?

**Comment by exdiogene** [comment]
From the default installation of Jitsi!

Each time I want to invite someone with the "mailto" protocol, I have to close the newly opened empty page with the "mailto" URL...

I understand your point of view, but we must find a solution for other people in a situation like mine and there is quite a few!

Users already have the gMail, Outlook and Yahoo available for selection in the Jitsi Invite window, isn't it reasonable to disable the "target='_blank' portion in the "mailto" protocol option?

In the worst case scenario, they would need to backup there page to recover the Jisty meeting one...

**Comment by quitrk** [comment]
@saghul maybe we can do something like this https://github.com/jitsi/jitsi-meet/pull/9232

**Comment by exdiogene** [comment]
I understand your reaction...

But I still wonder why the "target='_blank'" is not affecting a normal link with the "mailto:" protocol in Firefox when it is launching an application?

If we could understand why, the solution would be better than the target suppression only for Firefox!

Maybe it would be preferable to test your new code on Firefox before going further?

**Comment by exdiogene** [comment]
I just found a bug report for this Firefox issue , no solution at this time : 

https://bugzilla.mozilla.org/show_bug.cgi?id=646552

It would be preferable that a Jitsi administrator would be able to enable or disable the "target" portion in the configuration file , just in case!

**Comment by quitrk** [comment]
> I understand your reaction...
> 
> But I still wonder why the "target='_blank'" is not affecting a normal link with the "mailto:" protocol in Firefox when it is launching an application?
> 
> If we could understand why, the solution would be better than the target suppression only for Firefox!
> 
> Maybe it would be preferable to test your new code on Firefox before going further?

I did test it, but again I don't like this solution

**Comment by exdiogene** [comment]
There is still the solution of the variable in the configuration file...

Another preferable solution would be to be able to manage the protocol itself in the configuration file. There were people asking for a SMTP mailer for Jitsi, this could be simply implemented with an AJAX call to the server. If a mailto variable could be written, there would the possibilities to implement those situations for a "mailto" variable : 

If "mailto" = "mailto" then

url = "mailto:?subject=${encodedInviteSubject}&body=${encodedInviteText}"

If "mailto" = "https://MyDomain.ca/TheAJAXfilename.php" then

1 - send with AJAX to receive actual email addresses for that room : 
url = "TheAJAXfilename.php?MeetingRoom=${encodedInviteMeetingRoomName}"
2 - send mails with AJAX selected email addresses : 
url = "TheAJAXfilename.php?SelectedEmailsToSend&subject=${encodedInviteSubject}&body=${encodedInviteText}"

This solution have two advantages, first it do not rely on any local protocol and second it permit a lot more possibilities to Jitsi's invitations...

I could write the PHP AJAX file process and give it for free to the project.
