### ISSUE TITLE
ScreenSharing option is not working in android sdk

### ISSUE THREAD

**Issue by raviraj17apr** [jitsi/jitsi-meet#9222]
Hi Team,

I am using jitsi sdk latest version "org.jitsi.react:jitsi-meet-sdk:3.5.0". I am able to see the ScreenShare button in video call. 

When i click on this, MediaProjection permissions being requested and allowed as well.

The problem here is the client side it shows only blackscreen. Is there any configuration missing from presenter side. After some time of tis black screen, presenter icon is diplayed at client. I don't see any logcat exceptions in console.

Thanks in advance.

Reg,
Ravi

**Comment by raviraj17apr** [comment]
client side logs shows that no frame received.
I/org.webrtc.Logging: EglBase14Impl: Using OpenGL ES version 2
2021-05-15 09:06:34.719 27805-29589/in.educoncept.projects.dailyptm I/org.webrtc.Logging: EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2021-05-15 09:06:38.724 27805-29589/in.educoncept.projects.dailyptm I/org.webrtc.Logging: EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by irahulsah** [comment]
yeah, i am also facing the same issue, if u try in same wifi connection, it will work , but it only goes blank on different wifi connection

**Comment by aaaaaaaa212** [comment]
same problem

**Comment by raviraj17apr** [comment]
@saghul could you please help here, which additional flag or option to be included in android to enable screen sharing ?

**Comment by aaaaaaaa212** [comment]
@raviraj17apr 
i solved
The problem is in the service
You need to connect the foreground service.

**Comment by irahulsah** [comment]
> @raviraj17apr
> i solved
> The problem is in the service
> You need to connect the foreground service.

How to connect foregorund servicr? Can u mention the steps.. that would be very helpful

**Comment by raviraj17apr** [comment]
@aaaaaaaa212 It really a great news and thanks for giving  a big relief. Is it possible for you to share the piece of code, how you have used foreground services to enable screen sharing?

A big Thanks in advance

-Ravi

**Comment by aaaaaaaa212** [comment]
@raviraj17apr @irahulsah 

https://github.com/react-native-webrtc/react-native-webrtc/issues/927

I'm looking for a solution to the issue

I saw a question

That question was my problem

look at that part

 static void launch(Context context) {
        OngoingNotification.createOngoingConferenceNotificationChannel();

        Intent intent = new Intent(context, JitsiMeetOngoingConferenceService.class);
        intent.setAction(Action.START.getName());

        ComponentName componentName;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            componentName = context.startForegroundService(intent);
        } else {
            componentName = context.startService(intent);
        }
        if (componentName == null) {
            JitsiMeetLogger.w(TAG + "Ongoing conference service not started");
        }
    }


this part and


    startForeground(OngoingNotification.NOTIFICATION_ID, notification);
                    JitsiMeetLogger.i(TAG + " Service started");


Check if this part works


I have confirmed that the above items do not work in my project.


Getting this to work solved it.

Android Foreground Service Reference

https://developer.android.com/guide/components/foreground-services

**Comment by raviraj17apr** [comment]
@aaaaaaaa212 Thanks for reply. still not clear how did you make it work . This is part of sdk itself
I have added below lines in Manifest file and hope that would work. but failed
 <service
            android:name="org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService"
            android:foregroundServiceType="mediaProjection" />

how did you bind forground service for jitsiview?
startForeground(OngoingNotification.NOTIFICATION_ID, notification);
                JitsiMeetLogger.i(TAG + " Service started");
