### ISSUE TITLE
Activation video by voice

### ISSUE THREAD

**Issue by Va4o4o** [jitsi/jitsi-meet#9231]
### Description:

Activation video by voice, I don't know how I turned it on.
How do I disable it?

### Server information:

- Jitsi Meet version: 5390-3
- Operating System: Ubuntu 18.04.5 LTS

**Comment by saghul** [comment]
Can you please rephrase? I don't understand what your problem really is.

**Comment by Va4o4o** [comment]
> 
> 
> Can you please rephrase? I don't understand what your problem really is.

Hi I don't see videos of people when they stop moving

**Comment by Va4o4o** [comment]
> 
> 
> Can you please rephrase? I don't understand what your problem really is.

When we are going to a conference, the video of the participants appears and disappears. I don't know if it depends on your voice or your movements.

**Comment by saghul** [comment]
What connection quality do they have? You can check on the signal bars icon.

**Comment by Va4o4o** [comment]
> 
> 
> What connection quality do they have? You can check on the signal bars icon.

They had a good connection quality. This appeared unexpectedly, after changing the settings. It manifests itself as follows: The person does not speak or move - the video disappears. The person starts talking/moving the video appears. It looks like a special feature to save traffic. (I'm not sure) But I didn't turn it on.

**Comment by saghul** [comment]
Ah, I think I understand. It's not related to the movement, but to talking. If you don't have enough bandwidth Jitsi will suspend video for some participants. If you start talking you'll become the "dominant speaker" and we prioritise video for it. It's working as intended.
