### ISSUE TITLE
Reset Google Calendar link

### ISSUE THREAD

**Issue by kmaustral** [jitsi/jitsi-meet#9237]
**Is your feature request related to a problem you are facing?**
I need to change the Google Calendar that is linked to my Jitsi account.

**Describe the solution you'd like**
I'd like to delete the connection and start again.

**Describe alternatives you've considered**
I could open a new account with a new email, but this seems a waste.

**Comment by saghul** [comment]
There is no such a thing as a Jitsi account. We just use the calendar you select from your own Google account.

Go to settings (cogwheel on the top left) there is a way to disconnect the calendar.

Is that what you wanted?

**Comment by kmaustral** [comment]
Yes, but after re-connecting, the old one comes up and there is no choice.
Maybe it's in the cookies, then.

By the way, I am a refugee from Zoom. Their passcode system is a nightmare.
It might be good for corporates, but not for small meetings.

I love the four-word addresses too.

**Comment by saghul** [comment]
> Yes, but after re-connecting, the old one comes up and there is no choice. Maybe it's in the cookies, then.

Yep, I believe you might need to do that.

**Comment by kmaustral** [comment]
Thanks. While you are there, I tried my first group video meet yesterday
with nine people. Only the first four were visible, even though the others
had their cameras on. Is there a limit to the number of faces you can see?

**Comment by saghul** [comment]
There is no imposed limit. It varies according to your bandwidth, CPU usage and network conditions.
