### ISSUE TITLE
Problem with disable camera participants as Moderator (Alpha Jitsi)

### ISSUE THREAD

**Issue by cucauthongminh** [jitsi/jitsi-meet#9238]
### Description:

This bug happen on alpha.jitsi.net domain. When moderator open action menu from one participant and choose 'Disable camera'. It is not really disable camera, but only mute audio the participant.

### Steps to reproduce:

1. Open action menu from 1 participant
2. Click on 'Disable camera'

### Expected behavior:

The participant should be video muted

### Actual behavior:

The participant not mute video, but only audio.

### Client information:

- Browser / app version: 90.0.4430.93 (Official Build) (x86_64)
- Operating System: Mac OS

**Comment by damencho** [comment]
Thanks for the report.
