### ISSUE TITLE
Prejoin screen shows "you're microphone is working properly" when permissions are denied

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jitsi-meet#9241]
### Steps to reproduce:

1. In Chrome, open https://beta.meet.jit.si with any room name, but make sure to have the prejoin screen enabled.
2. Click on the padlock icon next to the https address and select "Block" for camera and or mic.

### Expected behavior:

The status bar at the bottom should say that it was unable to access the microphone.

### Actual behavior:

The status bar at the bottom says "It sounds like your microphone is working properly"
![Screen Shot 2021-05-19 at 8 41 19 AM](https://user-images.githubusercontent.com/2965063/118822735-05586000-b87e-11eb-85b6-14353cd14170.png)

### Server information:

- Jitsi Meet version: what's on beta
- Operating System: 

### Client information:

- Browser / app version: Chrome 90.0.4430.212
- Operating System: macOS Big Sur 11.2.3

**Comment by psi-4ward** [comment]
Can confirm that, behave is wired and not fully implemented.

My middleware looks like:

```js
    case DEVICE_PERMISSIONS_CHANGED:
    case TRACK_ADDED:
    case TRACK_NO_DATA_FROM_SOURCE: {
        const state = store.getState();
        let permissions = {};
        if(action.type === DEVICE_PERMISSIONS_CHANGED) {
            permissions = action.permissions;
        } else {
            permissions = state['features/base/devices'].permissions;
        }

        let track;
        if(action.type === TRACK_ADDED || action.type === TRACK_NO_DATA_FROM_SOURCE) {
            track = action.track.jitsiTrack;
        }

        // No permissions granted
        if(!permissions.audio || !permissions.video) {
            store.dispatch(setDeviceStatusWarning('prejoin.errorNoPermissions'))
        // Audio track but not receiving data
        } else if(track && track.isAudioTrack() && !track.isReceivingData()) {
            store.dispatch(setDeviceStatusWarning('prejoin.audioDeviceProblem'));
            // Audio track and receiving data
        } else if (track && track.isAudioTrack() && track.isReceivingData()) {
            store.dispatch(setDeviceStatusOk('prejoin.lookGood'));
        } else if (permissions.audio && permissions.video) {
            store.dispatch(clearDeviceStatus());
        }
        break;
    }
```
