### ISSUE TITLE
Use of '@import' when C++ modules are disabled,

### ISSUE THREAD

**Issue by 473817087** [jitsi/jitsi-meet#9245]
Hello, I'm using cocoapods to import the latest SDK. Enable modules (C and Objective-C modules) are set to yes. But it was wrong. I changed @ import to @ import, but when I called the SDK, it would crash. What should I do?

<img width="759" alt="image" src="https://user-images.githubusercontent.com/12890477/118909454-9cdcb200-b955-11eb-9d98-dfccaf5872d1.png">

<img width="954" alt="image" src="https://user-images.githubusercontent.com/12890477/118910328-dbbf3780-b956-11eb-9db8-4170af55cb07.png">

**Comment by saghul** [comment]
Not sure, but that has nothing to do with the SDK.

**Comment by 473817087** [comment]
The error is reported in the SDK，How come it doesn't matter？

**Comment by saghul** [comment]
I don't know how you configured your project to get that error, but that's not an error I can reproduce.
