### ISSUE TITLE
Separate volume for desktop screen share.

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet#9249]
**Is your feature request related to a problem you are facing?**
Yes. When my friend shares his screen with audio from his desktop, I believe lowering his volume also lowers his voice as well.

**Describe the solution you'd like**
It would be awesome if there were separate volumes to adjust the desktop media as well as the user volume (microphone volume).

**Describe alternatives you've considered**
Discord has this feature, but I'd like to have this on Jitsi Meet as well. An alternative could be to have the person adjust their desktop volume and lower it, but sometimes that's not always feasible.

**Comment by DillFrescott** [comment]
If I am in a call with 3 people and person 1 wants to share his/her screen for person 3 to see and hear, but person 2 doesn't want to also hear the screen share audio, the only options would be for person 2 to turn down person 1, which also turns his/her voice down.

The only way around this is for person 1 and 3 to start another separate call and mute their microphones while person 1 shares his/her screen.

As you might think this can be a bit annoying.

**Comment by DillFrescott** [comment]
:( thanks bot

**Comment by saghul** [comment]
Sorry we didn't back to you earlier 😢  Unfortunately what you ask for is not possible. We only support 1 audio stream per participant, so when you share your screen audio alongside your microphone we mix it locally and then send it as a single stream. As a result, it's not possible for the recipient to adjust the volume separately.

**Comment by dann-merlin** [comment]
Hey,

As I am not involved in the Jitsi Project, I have no Idea, so I thought I'll just ask:
Is this 1 audio stream per participant support a limit that is hard to circumvent?
Would it be a lot of trouble raising that limit?
Might there be a workaround using a "fake user" for the Desktop Share Audio Stream internally?

I would also really like to see that feature implemented!
Depending on your response, I might see if I could implement it myself.

Thanks!

**Comment by DillFrescott** [comment]
@dann-merlin I stopped using Jitsi Meet because it doesn't have this feature. If you could implement it that would be wonderful!

**Comment by saghul** [comment]
@dann-merlin Unfortunately I don't think that's attainable. 1 participant == 1 audio stream is a heavily relied upon assumption all throughout the code. We are lifting a similar limitation for video, but there we can differentiate the camera and desktop streams, this would be harder for audio streams.

**Comment by DillFrescott** [comment]
CTRL + F --> FIND IN FILES --> REPLACE: 1 audio stream --> WITH: 2 audio streams --> REPLACE ALL --> done?

this is a joke lol

**Comment by DillFrescott** [comment]
Are we any closer to implementing this? Or will it never happen?

**Comment by saghul** [comment]
Now that we have separate streams for camera video and screen-share we might be closer, but we are still mixing all participant audio as a single source, so it's still impossible.

I'm not sure if we are planning to ever separate those.

**Comment by DillFrescott** [comment]
Gotcha. Thanks for the info!
