### ISSUE TITLE
participants menu vs moderator menu

### ISSUE THREAD

**Issue by ysthad** [jitsi/jitsi-meet#9256]
### Steps to reproduce:

installation: Jitsi-meet
installation: secure domain

### Expected behavior:

The moderator (person connected as host): displayed menu of the moderator
Participants: reduced menu displayed

### Actual behavior:

The moderator (person connected as host): displayed menu of the moderator 👍 
Participants: menu displayed not reduced 👎  : only two items are hidden (start recording and start live streaming). 3 items are displayed when they should be hidden (turn off everyone’s microphone, turn off everyone’s microphone, control security (password and E2EE)). In my mind these 3 menus are typically menus that should be moderator menus.

### Server information:

- Jitsi Meet version: 2.0.5870-1
- Operating System: Debian 10
-  Kernel: Linux 4.19.0-16-cloud-amd64

### Client information:

- Browser / app version: Chrome Version 90.0.4430.212 (Build officiel) (64 bits)
- Operating System: Windows

**Comment by damencho** [comment]
This is already the case. When a participant is not moderator mute, mute all, set password and menus like that are hidden. 

![image](https://user-images.githubusercontent.com/3263098/119279145-6326d800-bbef-11eb-9635-535eacae579d.png)

You can test it on alpha.jitsi.net where the first one to join is a moderator and all the rest after that are not.

The security menu cannot be hidden for non-moderators as it shows whether a password is set or gives an option to turn on or off E2EE, but does not allow for non-moderators to set a password. 

If you see the menus this means some misconfiguration or you have all owners module enabled.

**Comment by pregalla** [comment]
To add more info, @ysthad was talking about these two menus in rectangle(in red) in below image, for guest users. These are available for guests on meet.jit.si, but seems this is already resolved in alpha.jitsi.net.

![image](https://user-images.githubusercontent.com/39415750/119520096-9b691a80-bd97-11eb-8092-283c45b5a57b.png)
