### ISSUE TITLE
Redirect to home page when clicking outside authentication modal

### ISSUE THREAD

**Issue by andre8244** [jitsi/jitsi-meet#9263]
### Description:

If authentication is enabled, "Waiting for the host..." modal is shown. If the user accidentally clicks outside this modal, they are redirected to the home page.

This behavior is a bit misleading, before Jitsi UI refactoring this didn't happen. I suspect that clicking outside the modal is equivalent to clicking the "Cancel" button (this button wasn't displayed before UI refactoring).

### Steps to reproduce:

1. Enable room authentication
2. Access a room
3. Click outside "Waiting for the host..." modal

### Expected behavior:

Nothing happens, "Waiting for the host..." modal is still shown. If the user wants to go back to home page, they can click "Cancel" button

### Actual behavior:

"Waiting for the host..." modal is closed and the user is redirected to the home page

### Server information:

- Jitsi Meet version: 2.0.5765-1
- Operating System: Ubuntu 20.04

### Client information:

- Browser / app version: Google Chrome 90.0.4430.212 (Official Build) (64-bit)
- Operating System: Fedora 34

**Comment by damencho** [comment]
> 1. What action did the user take that they are Cancelling? The title of the dialog says Waiting for the host. Convention for Cancel is that you are deciding not to take an action (e.g. Save -> Cancel, or Shutdown Computer -> Cancel), whereas the dialog is a state.

Cancel is canceling this operation and going back to homepage to join another meeting. 



> What makes this strange is that both X and Cancel don't dismiss the dialog and show the user what they can see behind the dialog, which is their video (like the prejoin page), similar to nearly all video conferencing apps.

This is a bug for sure. 



> 2\. Rename Cancel to 'Leave Meeting' or 'Leave' and then in that case, it makes a bit more sense and would be less surprising for the user that they are then redirected to the home page.

That is not correct, as you haven't joined anything to leave it.

**Comment by Amygos** [comment]
> If authentication is enabled, "Waiting for the host..." modal is shown. If the user accidentally clicks outside this modal, they are redirected to the home page.

Hi think this one is the main issue here, imagine this scenario:
1. a user receives an invite to join a conference by a link
1. the user clicks on the link and opens the browser with the "Waiting for the host..." dialog
1. the user wait for the host, but in the meantime, click by mistake outside the dialog
1. the user is redirected on the homepage without an apparent reason (for the user)

**Comment by damencho** [comment]
Yep, that is a valid usecase ... and the user needs to open it again. We cannot remove the cancel button as you make it unusable in electron, @Calinteodor if we can just ignore the clicking outside of the dialog ...

**Comment by raghav275** [comment]
Is there a way to redirect it to some other page after clicking on cancel on the modal. Asking this question because I am using external API in my webapp so I want to redirect to some other page.

**Comment by saghul** [comment]
You can do that in your own page when the readyToClose event is fired.

**Comment by raghav275** [comment]
It is not working from that. It works when I use the end call button but when I press the cancel button on this modal it takes me to the jitsi page where we can start our meeting

**Comment by raghav275** [comment]
Nevermind solved it using videoConferenceLeft

**Comment by staryan01** [comment]
starting the jitsi meet and removing the app from background and reopening it redirected me to my meet instead of home screen..i want it to redirect me to homescreen of the app
