### ISSUE TITLE
JitsiMeetExternalAPI is not defined

### ISSUE THREAD

**Issue by MadonnaEssam** [jitsi/jitsi-meet#9272]
I'm trying to embed Jitsi Meet in my application using Jitsi Meet API :
```
<script> window.exports = {}; </script>
<script src='https://meet.jit.si/external_api.js'></script>
```
and in file js 
`window.JitsiMeetExternalAPI = window.JitsiMeetExternalAPI || window.exports.JitsiMeetExternalAPI;
`
and get JitsiMeetExternalAPI is not defined

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Use the example: https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html

**Comment by MadonnaEssam** [comment]
I'm already doing this but not working
