### ISSUE TITLE
Option to disable "you are noisy" notification

### ISSUE THREAD

**Issue by monstro1** [jitsi/jitsi-meet#9273]
Would appreciate the option to disable the notification that says "your microphone appears to be noisy" or at least disable the sound effect it makes

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://github.com/jitsi/jitsi-meet/blob/06110d1dfb72a893f86ecebba9042edf5c0b4393/config.js#L105

**Comment by monstro1** [comment]
is there an option in the GUI of the program to disable this?

**Comment by damencho** [comment]
Nope, sorry.

**Comment by monstro1** [comment]
then add it

**Comment by monstro1** [comment]
> Nope, sorry.


https://user-images.githubusercontent.com/67171463/120144511-05c2f600-c1b0-11eb-9771-3978dac9c3c9.mp4
