### ISSUE TITLE
Allow more than one server URL in the app settings

### ISSUE THREAD

**Issue by tentmaster** [jitsi/jitsi-meet#9275]
As a Jitsi Meet App user I want to be able to manage more than one server URL in the settings so that I can easily create a new meeting on a different server if needed.

**Comment by fremzy** [comment]
You can create a meeting on any server by just entering the full URL. The default server setting is a convenience feature - see it as a 'favorite' link kind of thing.

**Comment by tentmaster** [comment]
Yes, but I want to be able to store multiple 'favorite' servers in the settings so that I don't have to type them manually.

**Comment by saghul** [comment]
We have no plans to implement this, sorry.
