### ISSUE TITLE
Autorecord

### ISSUE THREAD

**Issue by antiuser** [jitsi/jitsi-meet#9278]
Hi there!
We want to use autorecording jitsi conference, only for security purposes.
Because anybody can create room and talk about terror for example.
Please approve this request if its possible.

Thank you!

**Comment by fremzy** [comment]
Security ('privacy') is the very reason why such a feature should not be included out-of-the-box. Surely, you can implement it on your own, if you choose to, but I personally don't think this is something that should be given much thought as a default. If you implement authentication in your deployment "anybody" can't just "create a room and talk about terror".
