### ISSUE TITLE
Resolution and Framerate are not shown in Firefox

### ISSUE THREAD

**Issue by mghadam** [jitsi/jitsi-meet#9281]
### Description:

Resolution and Framerate are not shown in connection info when using Firefox. Tested on MacOS and Linux

### Steps to reproduce:

1. Use Firefox to join a Jitsi meeting
2. Check the connection info bar
3. Resolution and Framerate are not shown

### Expected behavior:

The real Framerate and resolution should be shown instead of N/A .

### Actual behavior:

Here is a screenshot for the sender and tthe receiver connection info 

![image](https://user-images.githubusercontent.com/10244293/119772553-9d84c380-bed4-11eb-84d6-806ed5a916d8.png)

![image](https://user-images.githubusercontent.com/10244293/119772639-c1480980-bed4-11eb-8c3b-1e53df85c8e2.png)

### Server information:

- Jitsi Meet version: jitsi-meet-docker stable-5870
- Operating System: Centos 8

### Client information:

- Browser / app version: Firefox 88.0.1 (64-bit) on Ubuntu, Firefox 88.0.1 (64-bit) on MacOS  with no extra addons.
- Operating System: Tested on both Ubuntu 21.04 and MacOS11.3.1

### Additional information:

This problem does not exist when I use Google Chrome on the same client OS.

**Comment by saghul** [comment]
This should no longer be the case right @jallamsetty1 ?
