### ISSUE TITLE
Display Label not visible for local participants

### ISSUE THREAD

**Issue by JijoBose** [jitsi/jitsi-meet#9288]
### Description:

When a local participant joins the meeting from the mobile, the Display name Label is not visible

This line of code in file `react/features/display-name/components/native/DisplayNameLabel.js`
```
    // Currently we only render the display name if it's not the local
    // participant and there is no video rendered for
    // them.
    const _render = Boolean(participantId)
        && localParticipant?.id !== participantId
        && !shouldRenderParticipantVideo(state, participantId)
        && !isFakeParticipant;
```

Can I remove this condition `localParticipant?.id !== participantId`
Could anyone tell me the reason this restriction was placed for local participants?

Or is there any other workaround for this?

### Steps to reproduce:

1. Join a meeting from mobile with just the meeting ID
2. Notice the user joining from mobile does not display their name.

**Comment by saghul** [comment]
Did you intend to close this?

**Comment by JijoBose** [comment]
> Did you intend to close this?

Yes, I think this should be in the community form. Since it's more of a question and not an issue.
