### ISSUE TITLE
JitsiMeetSDK: Screen dim after few seconds when conference started

### ISSUE THREAD

**Issue by arehman86** [jitsi/jitsi-meet#9289]
I am using JitsiMeetSDK in my iOS app. I am facing an issue that after start a conference screen dims (but not locked out) after few seconds. Is there a way how to prevent it.

### Steps to reproduce:

1. Start the conference
2. Stop the conference
3. Quit the app from the background
4. Start the conference again
5. The screen dims after few seconds

- Jitsi Meet version: 3.5.0
- Operating System: 14.5.1

**Comment by saghul** [comment]
This is by design, in audio-only calls.

**Comment by saghul** [comment]
It's still the case for audio-only calls.
