### ISSUE TITLE
Some client have no video (skype/webex works)

### ISSUE THREAD

**Issue by matclab** [jitsi/jitsi-meet#929]
Some people in big companies can not have video or/and sound. Chat always work.
We do not have problem with other small companies.
I suspect some sort of firewalling/DPI process on the big companies side. Would it be possible to masquerade traffic so as to look like a webex/skype video stream ?

Has anybody looking at this subject or has preliminar idea of what should be done ?

**Comment by damencho** [comment]
Did you try meet.jit.si? Is it the same?
Jitsi-videobridge should be deployed so that it is listening to port 443 tcp, which is how it is working in restricted corporate networks, where https and http are the only allowed outgoing ports.

**Comment by damencho** [comment]
Please when you have questions and problems, first write to the mailinglist prior opening an issue.

**Comment by matclab** [comment]
I'll do.
Sorry for the noise and thank you for your help.
