### ISSUE TITLE
Option to handle our own mic levels when using meet.jit.si.

### ISSUE THREAD

**Issue by Blueshawk** [jitsi/jitsi-meet#9290]
**Is your feature request related to a problem you are facing?**
Jitsi is adjusting Mic levels at pulse audio until room noise it heard, then system complains about the noise. 
Linux Artix/runit/cinnamon
 - also tested in peppermint9, Rocketchat integration(homeserver), Matrix-synapse integration(homeserver) 

**Describe the solution you'd like**

System Mic volume level stays where you put it. 
...as absurd as that sounds. (sarcasm)

**Describe alternatives you've considered**
This is known as AGC or automatic gain control - and it desperately needs to be turned off. the way it is implemented abuses permissions and leaves the system in an unusable state.
I'm not calling this a bug because somebody likely spent time implementing it, and I appreciate the effort, but it needs to be an option. 

Thank you all for what you do and reading my opinion on this.

Ray

[edited for neatness]

**Comment by Blueshawk** [comment]
I would add that having a squelch level adjustment would also help and can enter it as a different enhancement if you like.

**Comment by damencho** [comment]
Not sure you can control that from the browser even if you can, those settings normally are available on the OS level.

**Comment by damencho** [comment]
> **Describe alternatives you've considered**
> This is known as AGC or automatic gain control - and it desperately needs to be turned off. the way it is implemented abuses permissions and leaves the system in an unusable state.

You can disable that: https://github.com/jitsi/jitsi-meet/blob/27481f02705241e5753768c18e8b91437fab3b28/config.js#L779

**Comment by damencho** [comment]
> System Mic volume level stays where you put it.
> ...as absurd as that sounds. (sarcasm)

This is nothing the app controls. This is something between the browser and the OS. So you may search for bugs and issues in the browser's bugtracker for your OS.

**Comment by Blueshawk** [comment]
Thank you for addressing this so quickly.  No other audio chat/record or other system, (mumble - discord, etc.) does this. You can watch the mic level change in the sound manager when using the webapp. Permission must be given to the web app to work. 

Okay, I'll check that out.

**Comment by damencho** [comment]
Do you experience the same in https://appr.tc/?

**Comment by Blueshawk** [comment]
Librewolf doesn't like something. I'll set it up in my rocketchat and see what I get.

**Comment by Blueshawk** [comment]
As a side note: I found this while researching earlier: #config.disableAudioLevels=true 
[https://jitsi.github.io/handbook/docs/user-guide/user-guide-advanced](url)
While this one only disables stat polling, the method seems like it could be used to choose to turn off agc when making a new room at meet.jit.si by adding a command to the list to do so.

  I'll be following and can do more as needed. :)

**Comment by Blueshawk** [comment]
> > **Describe alternatives you've considered**
> > This is known as AGC or automatic gain control - and it desperately needs to be turned off. the way it is implemented abuses permissions and leaves the system in an unusable state.
> 
> You can disable that:
> 
> https://github.com/jitsi/jitsi-meet/blob/27481f02705241e5753768c18e8b91437fab3b28/config.js#L779

Changing mic levels at system level should be considered a severe security issue. If I turn the mic down it better stay down. Since agc can only be controlled on self run servers, I(and many others) have chosen to pursue a different system. I consider choosing not to fix this, and in fact ignoring it, a sign that Jitsi does not have the open source community or privacy in mind which is a show stopper for many.
