### ISSUE TITLE
Picture and picture mode buttons... Is it possible?

### ISSUE THREAD

**Issue by darkcurrent** [jitsi/jitsi-meet#9294]
I think I have an important suggestion to you. I am not sure that this is technically possible or not but I want to explain:

It would be great if jitsi meet can show "_**mute**_, **_open/close cam_**, _**close call**_" buttons in the **"picture in picture"** mode. And it would be nice if double clicking on the small picture opens the main window.

I believe lots of folks are using picture in picture mode during meetings. So lack of these buttons made people use skype or etc. instead of jitsi meet.

**Comment by tmoldovan8x8** [comment]
Hi @darkcurrent thanks for the suggestion. It is something that we indeed though about and partially prepared the app to support, but we did not find the time to finish it. Will try to prioritise it.

**Comment by darkcurrent** [comment]
I see, good luck.
