### ISSUE TITLE
Is it possible in Mobile Apps when we share screen camera is not disabled like the web?

### ISSUE THREAD

**Issue by eraArya2601** [jitsi/jitsi-meet#9297]
Is it possible in Mobile apps when we share screen camera is not disabled?

Please help me out. Thanks in advance

**Comment by tmoldovan8x8** [comment]
Hi @eraArya2601. Not sure what you mean. The behaviour is the same on mobile and on web. When somebody is sharing the screen it will replace the local camera stream.

**Comment by eraArya2601** [comment]
> Hi @eraArya2601. Not sure what you mean. The behaviour is the same on mobile and on web. When somebody is sharing the screen it will replace the local camera stream.

@tmoldovan8x8  when somebody shares screen camera disabled in mobile and not clickable but in web camera off but it should turn on and clickable during screen sharing.

**Comment by tmoldovan8x8** [comment]
Can you describe a bit the scenario you are trying to achieve? On web you can enable the camera, but the stream won't be sent to the others, same as on mobile, since we cannot send at the moment more than one stream.

**Comment by eraArya2601** [comment]
@tmoldovan8x8, On the web During screen sharing video, is shown like below image:-
![1622522589574](https://user-images.githubusercontent.com/77479651/120267750-398e4080-c2c2-11eb-8aaa-516132067e8a.JPEG)

But on Phone During screen sharing video not shown and the camera is disabled and no option to on-camera during screen sharing like below image:-
![1622522848989](https://user-images.githubusercontent.com/77479651/120267952-9a1d7d80-c2c2-11eb-8472-fa7bdfdedb89.JPEG)

I want to show video on a mobile phone during screen sharing. Is it possible?

**Comment by saghul** [comment]
This is not possible, sorry.
