### ISSUE TITLE
jitsi meet notifications

### ISSUE THREAD

**Issue by gstlouisgit** [jitsi/jitsi-meet#9301]
I've been using jitsi meet for a while now and even encourage and implement this in offices for video and conference calls.  I really enjoy it.

However from tablet to tablet do we know if there will ever be, or already does and I just dont kknow?  the ability for direct calling or ringing from the jitsi meet app?

I mean is I would implement this into web development I guess I could probably setup a way that one user would send the string invite and I would make it look like it rings for the other user to accept and join.  I'm just wondering if the app can do this or working on it..

thanks

**Comment by saghul** [comment]
We have no plans to implement direct calling.

**Comment by gstlouisgit** [comment]
Thats is unfortunate. Can we transfer this as feature request?

**Comment by saghul** [comment]
Wouldn't serve any purpose because that feature is not something we plan to add.
