### ISSUE TITLE
Cut meeting leading meet.jit.si/ from meeting ID

### ISSUE THREAD

**Issue by ramack** [jitsi/jitsi-meet#9304]
**Is your feature request related to a problem you are facing?**
I wanted to join a meeting and had the link in the form `meet.jit.si/ABCxxx` which is the URL used in the browser to connect. The app was using the full entered text as meeting ID and I therefore was alone in that meeting.

**Describe the solution you'd like**
The app should cut a leading server name from the meeting ID to enter directly the meeting `ABCxxx` instead of the meeting including the server name.

**Describe alternatives you've considered**
Manually removing the server name, but as it was my first Jitsi meeting where I received the meeting ID in the form including the server name I wondered why I was alone and finally connected with the browser.

**Comment by saghul** [comment]
Using a full URL (including the scheme) will take you to the right meeting.
