### ISSUE TITLE
Notification Channel title is not translated : Ongoing Conference Notifications

### ISSUE THREAD

**Issue by namouchislim** [jitsi/jitsi-meet#9308]
The channel notification title of the ongoing conference is not translatable, it is hard-coded in the OngoingNotification class

_private static final String CHANNEL_NAME = "Ongoing Conference Notifications";_

### Steps to reproduce:
1. Set the phone language to a language other than English.
2. Start a video conference call
3. Check application settings from system settings
4. Go to Notification -> Other 
.

### Expected behavior:

The title of the notification channel must be translatable by placing the string in the Strings file.

### Actual behavior:
Notification channel title is "Ongoing Conference Notifications", not translated.

### Server information:

- Jitsi Meet version: 3.5.0

### Client information:

- Operating System: Android 9

**Comment by namouchislim** [comment]
Hello,

Any update ?

**Comment by saghul** [comment]
@tmoldovan8x8 did we do this in the end?

**Comment by tmoldovan8x8** [comment]
https://github.com/jitsi/jitsi-meet/pull/10075
