### ISSUE TITLE
JitsiMeetSDK' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor,

### ISSUE THREAD

**Issue by Aizaz-Abbasi** [jitsi/jitsi-meet#9310]
bitcode set to no but still it its giving issue in iOS swift app Xcode 12.4.

**Comment by saghul** [comment]
We have no plans to release a bitcode enabled SDK, sit you can build it from source by following the instructions in the handbook.
