### ISSUE TITLE
Impossible to talk during video conference. Cannot unmute and nobody hears me.

### ISSUE THREAD

**Issue by mhamdihajer1** [jitsi/jitsi-meet#9312]
### Description:

User already connected in video conference after some time he try to mute then unmute.
Unmute not work nobody hears him.

### Steps to reproduce:

1. connect to a video conference.
2. click to the mute button  
3. click to the unmute button  

### Expected behavior:

user can talk and other participant should hear him

### Actual behavior:

user can't unmute and nobody hears him.

### Server information:

- Operating System: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-67-generic x86_64)

### Client information:

- Android 
- SDK Jitsi Meet version: 3.5.0

**Comment by saghul** [comment]
We cannot reproduce this.
