### ISSUE TITLE
Be able to make notifications moderator only

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/jitsi-meet#9317]
**Is your feature request related to a problem you are facing?**
Notifications, especially red notifications can be frightening to regular users.
Plus, there are on top of UI.
I got the feedback that some users didn't know what to do and were afraid to close them, and then couldn't mute/unmute themself.

**Describe the solution you'd like**
One possible solution could be to limit all notification/some notification to moderators only.

**Describe alternatives you've considered**
We can train more our users.

**Comment by saghul** [comment]
We have refactored notification quite a bit lately.

There are still some sticky ones, but we believe users need to see them otherwise you'd never know what's wrong.

There is the possibility to hide notifications through the iframe api though.
