### ISSUE TITLE
Add labels under toolbar icons

### ISSUE THREAD

**Issue by jsrobinson3** [jitsi/jitsi-meet#9321]
**Is your feature request related to a problem you are facing?**
Some users do not understand the iconography that exists in Jitsi Meet. While tech savvy people have no issue recognizing a chat or screenshare icon some demographics do not recognize these and would benefit from explicit labeling that does not require a hover.

**Describe the solution you'd like**
My suggestion would be to do similar to other video software and just put a static label under each icon. While I agree that it shouldn't be necessary and that most people will know this without the need for additional labels, I do believe it would simplify the experience for all users as well as avoid the "how do I share my screen" questions that come up often. 

Zoom:
![image](https://user-images.githubusercontent.com/16910828/120546182-8efb4800-c3bd-11eb-8b8b-73dcc95a8f1f.png)

possible Example:
![image](https://user-images.githubusercontent.com/16910828/120547128-adae0e80-c3be-11eb-8513-2534c2c97319.png)

**Describe alternatives you've considered**
I am not a UI/UX person and only going off requests I have received so very open to other suggestions.

**Comment by saghul** [comment]
We are not considering changing our toolbar at this time, sorry.
