### ISSUE TITLE
How to Replace customizable jitsimeetSDK.framework with the existing jitsimeetSDK.framework (IOS)

### ISSUE THREAD

**Issue by 31Karishma** [jitsi/jitsi-meet#9325]
I m using react-native-jitsi-meet in My app, and want a different calling screen UI, so I customized the screen with jitsi/jitsi-meet & build a customized jitsimeetSDK.framework & webRTC.framework.

Now, how can I replace these two frameworks with the existing framework in app?

Anyone can help me Please.
Thank you in Advance

- React-Native Version:-0.63.4
- Operating System: MAC

**Comment by saghul** [comment]
We don't maintain that RN library, you'd need to ask its author.

**Comment by vinay-blueehr** [comment]
@saghul How do we use the newly created framework in RN project?
