### ISSUE TITLE
 Switching speaker issue

### ISSUE THREAD

**Issue by mssNitish** [jitsi/jitsi-meet#9331]
### Steps to reproduce:

1)Attach headphones to the device
2)Join to group call
3)Switch audio mode to the speaker
4)Unplug headphones into the device
5)Plug Headphones into the device
then you can see in Jitsi call automatic mode changed to the microphone but audio still comes in speaker.

### Server information:

- Jitsi Meet version:3.6.0
- Operating System: Android

### Client information:

- Browser / app version:
- Operating System:

**Comment by mssNitish** [comment]
Jitsi Team please look above issue and let us know how to handle this

**Comment by zsinba** [comment]
we encounter the same issue on the android platform;

I make sure this was not the webrtc's bug, it was jitsi's bug;

waiting for the official developer to answer.
