### ISSUE TITLE
There are debug popups in new ios sdk. Need to dismiss them every time causing bad user experience

### ISSUE THREAD

**Issue by Arohi-Magotra** [jitsi/jitsi-meet#9333]
There are debug popups in new ios sdk. Need to dismiss them every time causing bad user experience. Please check the attached screenshot. Please let me know how to remove these.
![uploadingImage](https://user-images.githubusercontent.com/64579245/120802881-9149d780-c560-11eb-9916-2088120b1217.jpg)

**Comment by saghul** [comment]
Yo made a debug build, production / release builds don't show those.
