### ISSUE TITLE
Layout on iOS is sometimes incorrect 

### ISSUE THREAD

**Issue by iccub** [jitsi/jitsi-meet#9341]
### Steps to reproduce:

1. Open together.brave.com
2. Scroll a bit, change a tab

### Actual behavior:

Sometimes layout is wrong, toolbars hide actual buttons making it hard to tap on them

![IMG_7186](https://user-images.githubusercontent.com/6950387/120870823-42b92f00-c59a-11eb-9534-dd0f7931cee8.PNG)
![IMG_7185](https://user-images.githubusercontent.com/6950387/120870825-4482f280-c59a-11eb-914e-d84040364bfc.PNG)

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by stephendonner** [comment]
Verified `FIXED` using `talk.bravesoftware.com` on both an `iPhone 6s` and an `iPhone 8 Plus`, running `iOS 14.4.2` and `public beta 15`, respectively.

Saw no clipping of the bottom browser toolbar, and scrolling the `Meeting participants` list was fine too.

example | example | example | example
---------|---------|----------|----------
![Image from iOS (4)](https://user-images.githubusercontent.com/387249/125683880-a2a54421-7689-4bfb-81b3-7f7b7a7fda30.png) | ![Image from iOS (5)](https://user-images.githubusercontent.com/387249/125683882-a86edd65-232a-4d5f-bece-6c523f91e82e.png) | ![Image from iOS (6)](https://user-images.githubusercontent.com/387249/125683884-0b28e6ec-8f92-4c9e-97bf-29096716e081.png) | ![Image from iOS (7)](https://user-images.githubusercontent.com/387249/125683886-9cffd50b-006c-4d0b-a19c-4b89286fcef0.png)
