### ISSUE TITLE
First participant is not getting Moderator even after enabling lobby in the iOS mobile - React native

### ISSUE THREAD

**Issue by idrive-pankaj** [jitsi/jitsi-meet#9348]
### Description:
When are using our own server and we have added lobby settings and when the first user joins the meeting he will become a moderator.
We are also using JWT token and sending that moderator flag but for now we have commented it as user become not a moderator.

When the user joins the meeting we receive the below event and if it's a moderator event then we are changing the lobby setting for the conference.

{ type: 'PARTICIPANT_UPDATED',
  participant: { id: '9f86b6a7', role: 'moderator' } }

if the local user id is the same as the one in the event then we enable the lobby using the bellow code in the same 
dispatch(conference.enableLobby());

This is the full code block inside the base>participant>middleware

    case PARTICIPANT_UPDATED:
        const { getState, dispatch } = store;
        const { conference } = getState()['features/base/conference'];
        if(action.participant && action.participant.role == 'moderator' && action.participant.id == 
        conference.myUserId()) {
            dispatch(conference.enableLobby());
        }
        return _participantJoinedOrUpdated(store, next, action);

After that, if I check the participant role in the bellow using the bellow function it's always become none.

`export function isLocalParticipantModerator(stateful: Object | Function) {
    const state = toState(stateful);
    const localParticipant = getLocalParticipant(state);

    if (!localParticipant) {
        return false;
    }
    console.log(`========localParticipant==========`,localParticipant.role)
    return localParticipant.role === PARTICIPANT_ROLE.MODERATOR;
}
`

### Steps to reproduce:

1. Make the first participant as a moderator for the lobby
2. Once you receive user update event on base>participant>middleware enable lobby there
3. check user role in the participant>function

### Expected behaviour:
User should be a moderator when we enable the lobby

### Actual behavior:
The participant should be a moderator when we enable lobby 

### Server information:

- Jitsi Meet version: 11th December code we are using
- Operating System: Mac os Big Sur

### Client information:

- Browser / app version:
- Operating System:

### Additional information:
Please help me to resolve this issue as we are stuck with this for the last few days.

**Comment by damencho** [comment]
> ### Expected behaviour:
> User should be a moderator when we enable the lobby
> 
> ### Actual behavior:
> The participant should be a moderator when we enable lobby

It is not clear what is the problem you experience. 

When you have questions or problems please use the community forum before opening new issues, thank you.

**Comment by idrive-pankaj** [comment]
Thanks for your reply @damencho, I have resolved my issue.
