### ISSUE TITLE
iPad : Screen Sharing option not available in app store Jitsi Meet App

### ISSUE THREAD

**Issue by vimalkumarM** [jitsi/jitsi-meet#9350]
Description:

Downloaded Jitsi meet App from iOS app store in iPad. After joining a meet, i tried to do screen share but there is no screen share button available in the overflow menu. 

 Client information:

- Browser / app version: 21.1.0
- Device: iPad Air (3rd generation) 
- Software version : 13.7

Please refer the screenshot for additional details
![1](https://user-images.githubusercontent.com/28982743/121047979-007b3200-c7d4-11eb-9068-76ac659ba6d1.jpeg)
![2](https://user-images.githubusercontent.com/28982743/121047990-0244f580-c7d4-11eb-8edd-dd7fc98b3e14.jpeg)
![3](https://user-images.githubusercontent.com/28982743/121047992-0244f580-c7d4-11eb-8cdc-45c328591ee3.jpeg)

**Comment by vimalkumarM** [comment]
@damencho @saghul can you please let me know if the screen sharing feature is not available in iPad or it is a bug?

**Comment by saghul** [comment]
You need iOS 14.
