### ISSUE TITLE
Android - Feature flags

### ISSUE THREAD

**Issue by Saad-Alareqi** [jitsi/jitsi-meet#9351]
Hi,

I noticed when applying the Feature Flags it will will not effect the initial user who created the conference and only the other invited members are effected. if there was an option to include the initial user with the restriction of flags as i don't want all the features to be usable to any user.
my code for reference:

 JitsiMeetConferenceOptions jitsiMeetConferenceOptions =
                                   new JitsiMeetConferenceOptions.Builder()
                                   .setServerURL(ServerURL)
                                   .setWelcomePageEnabled(false)
                                   .setVideoMuted(isAudioOnly)
                                   .setFeatureFlag("add-people.enabled",false)
                                           .setFeatureFlag("calendar.enabled",false)
                                           .setFeatureFlag("conference-timer.enabled",false)
                                           .setFeatureFlag("help.enabled",false)
                                           .setFeatureFlag("invite.enabled",false)
                                           .setFeatureFlag("kick-out.enabled",false)
                                           .setFeatureFlag("security-options.enabled",false)
                                           .setFeatureFlag("live-streaming.enabled",false)
                                           .setFeatureFlag("toolbox.alwaysVisible",true)
                                           .setFeatureFlag("meeting-name.enabled",false)
                                           .setFeatureFlag("raise-hand.enabled",false)
                                           .setFeatureFlag("recording.enabled",false)
                                           .setFeatureFlag("server-url-change.enabled",false)
                                           .setFeatureFlag("video-share.enabled",false)

                                   .setRoom(getIntent().getStringExtra(Constants.REMOTE_MSG_MEETING_ROOM))
                                   .build();
                           JitsiMeetActivity.launch(IncomingCallActivity.this,jitsiMeetConferenceOptions);

**Comment by saghul** [comment]
All feature flags apply to the user as well.
