### ISSUE TITLE
Android - add the sound device feature flag

### ISSUE THREAD

**Issue by Saad-Alareqi** [jitsi/jitsi-meet#9352]
Hi,

if there is a possibility to add a flag to chose between phone or speaker when starting a meeting, it would be great. because i want to implement a call option while using the phone.
the default is the external speaker.

**Comment by ashar02** [comment]
What is the solution for this? Any release plan for this feature?

**Comment by saghul** [comment]
We have no plans to implement this feature ourselves. A PR adding the functionality would be welcome though.

**Comment by ashar02** [comment]
Okay, got it!
