### ISSUE TITLE
Jitsi keeps saying my microphone is noisy when it clearly isn't.

### ISSUE THREAD

**Issue by monstro1** [jitsi/jitsi-meet#9353]
Please for the love of God let me disable this. And I need an option to disable it within the GUI itself; I'm not running the instance I'm using. My friends are also complaining to me about it and I don't want to go back to crappy proprietary spyware like Discord.

**Comment by monstro1** [comment]
and if this gets closed without being fixed I will screech the loudest screech I've ever screeched

**Comment by nadelicious** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L858

**Comment by monstro1** [comment]
> https://github.com/jitsi/jitsi-meet/blob/master/config.js#L858

what

**Comment by monstro1** [comment]
how hard is it to just add this option to the GUI? You want people to stop using proprietary junk like Skype? One of the first things they're bound to notice and get annoyed by is the constant clicking sounds from this stupid-ass notification. Any time I laugh, I'm too noisy. Every time I move slightly in my chair, I'm too noisy, every time I unmute my mic, I'm too noisy, every time I think about the concept of noise I get hit with this retarded notification. If this bullshit doesn't get fixed I am going to do 50 front flips and then scream as loud as I possibly can and also probably just convince people to not use it because the developers are morons that won't fix their stupid broken shit

**Comment by mdsystems** [comment]
> > https://github.com/jitsi/jitsi-meet/blob/master/config.js#L858
> 
> what

It's giving a hint what needs to be changed in the code to support your request, I think. I am not going to promise anything, but I am going to take a look and see if I can work out how to change it. Don't hold your breath, though, as I have no knowledge of the Jitsi code base yet.

**Comment by mdsystems** [comment]
Do you know who is running the instance? Is it shared or dedicated to you? It looks as though there is an option in config.js to disable the feature ("enableNoisyMicDetection". If this is set to false, the comment against the option implies that it will turn this detection off. I know this is not quite what you're asking for, but maybe it will help whilst someone (or perhaps I, if I am able to) find a way of surfacing the setting as a menu option.

To add the option to the GUI, it would likely be necessary to modify the server side API and add client side code to support a menu option and storage of that option in a browser cookie or the user configuration if they are authenticating (which may not be possible). It looks to me as though react.js is being used and this is not something I am particularly expert in using.

**Comment by saghul** [comment]
This may or may not be implemented, but I'm not going to issues with this tone.

**Comment by mdsystems** [comment]
I think it is quite a good feature request as I also find that Jitsi complains that my mic is noisy if I cough or laugh. Whilst it is technically "correct" - I am being noisy, I think the option to turn it off would be handy. I am not sure if I will have time (or the ability) to implement this myself, but where is the best place to find out about the structure of the system so I can take a look?
