### ISSUE TITLE
add option to download/save meet chats

### ISSUE THREAD

**Issue by tusharnankani** [jitsi/jitsi-meet#9356]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

We have our community meetups weekly on Jitsi Meet. 
- During the conversation, various links are shared: Project Links, GitHub Links, Twitter Handles are shared in every meeting, in the chat.

So to add a feature that helps them download the chat in a `.txt` format.

**Describe the solution you'd like**
Please describe the desired behavior.

I have created a script to easily download the meeting chats.

**Repository Link**: [download-jitsi-chat](https://github.com/tusharnankani/download-jitsi-chat)

I believe, this feature can be implemented on the client-side, without giving much load on the server. A simple button either on the bottom toolbar or an option in the three-dot menu.

![image](https://user-images.githubusercontent.com/61280281/121160216-83020100-c869-11eb-914a-3912306f1964.png)

A simpler position can also be possible, by placing it here.

![jitsi-chat-download-redesign](https://user-images.githubusercontent.com/61280281/121162581-b04fae80-c86b-11eb-9dd9-eb78ba0b07af.png)

Let me know if this feasible, I will start working on it.

**Comment by damencho** [comment]
That makes sense, but make sure that is configurable using the config.js and is disabled by default to keep the current behavior. 
Also make sure you sink with the creators of https://github.com/jitsi/jitsi-meet/pull/9125 maybe you can work together on adding the UI (the button) to that PR.

**Comment by tusharnankani** [comment]
> Also make sure you sink with the creators of #9125 maybe you can work together on adding the UI (the button) to that PR.

Hi. I went through the referenced PR.
I believe a button is much more intuitive and simpler than downloading the chat after hangup. There are some reasons I believe so:
- The chat will be unnecessarily downloaded for users, who don't want the chat to be downloaded. Even if the default behavior remains the same and the proposed behavior in the mentioned PR, is configurable, but it doesn't yield the best User Experience.
- Once a user hangs up, his `Display Name` is changed to `Fellow Jitster`, and when the user who wants to download the chat, leaves the meet at the end (when everyone leaves) - the downloaded chat might not make sense as all users will be named `Fellow Jitster`, hence the messages lose their identity.

Hence, a button gives the flexibility to download the chat for any user at **any point in time.**

Let me know what you think about this?

> That makes sense, but make sure that is configurable using the config.js and is disabled by default to keep the current behavior.

Therefore, I also feel, it can be added to the current behavior, keeping the button as default enabled, and configurable for users who do not want the suggested behavior.

**Comment by damencho** [comment]
> Hi. I went through the referenced PR.
> I believe a button is much more intuitive and simpler than downloading the chat after hangup. There are some reasons I believe so:

I agree, its just pointed that there are people working on the same, and hal of the work is done.





> Therefore, I also feel, it can be added to the current behavior, keeping the button as default enabled, and configurable for users who do not want the suggested behavior.

Well, I need to talk to design and product people first is this ok, and do we want this enabled by default.

**Comment by tusharnankani** [comment]
> Well, I need to talk to design and product people first is this ok, and do we want this enabled by default.

Sure. Will be waiting.

**Comment by damencho** [comment]
On second thought, the polls are still WIP, so you can proceed with your implementation. 
Enable it by default, but add a config.js setting for disabling it.
Thank you. 
And in the meanwhile, if design comes up with something I will update the thread here.

**Comment by tusharnankani** [comment]
Great, thank you!

**Comment by tusharnankani** [comment]
Hi @damencho 
I was facing difficulties while setting up locally. `patch-package` is having some issues.
I am currently investigating.

I was wondering if there is a Windows Installation Guide to set it up locally?

**Comment by damencho** [comment]
Nope, sorry.

**Comment by thaiphison** [comment]
hey, this feature already to used?

**Comment by 0xnor0** [comment]
Any news in this?

**Comment by saghul** [comment]
No news, sorry folks, it has been a busy end of the year.
