### ISSUE TITLE
[iOS] Add feature flag to disable local network usage permission popup 

### ISSUE THREAD

**Issue by ivanBalychev** [jitsi/jitsi-meet#9363]
There is no option to disable local network usage permission popup:

<img width="243" alt="Screenshot 2021-06-09 at 10 03 17" src="https://user-images.githubusercontent.com/18113448/121308650-f3605f00-c909-11eb-8449-efc2092c2b6e.png">

**Comment by saghul** [comment]
It’s not possible to disable it. It’s mandatory and required.
