### ISSUE TITLE
[iOS] Jitsi interface disappears and doesn't restore when reconnection to Internet

### ISSUE THREAD

**Issue by ivanBalychev** [jitsi/jitsi-meet#9364]
Reproduced mainly at old devices:
iPhone 7 ( iOS 13.1.3) + iPhone SE (iOS 14.5.1)
iPhone SE (iOS 14.5.1) + iPhone 11 (iOS 14.4.2)
iPhone 7 ( iOS 13.1.3) + iPhone 11 (iOS 14.4.2)

**Comment by saghul** [comment]
Can you reproduce this in the latest version?

**Comment by saghul** [comment]
We fixed the reload screen not showing, so when the connection is broken you get a chance to reconnect.
