### ISSUE TITLE
android: hangup by bluetooth button

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#9372]
### Description:

I'm pretty sure that some version ago jitsi left the meeting by pressing bluetooth headset button. But now it doesn't work.

### Steps to reproduce:

1. Join the meeting.
2. Press bluetooth headset button (answer / end call)

### Expected behavior:

Hang up.

### Actual behavior:

Just nothing happens.

### Client information:
- v21.1.0 from F-Droid
- LineageOS 18.1 + microG / Android 11

**Comment by 532910** [comment]
Still actual

**Comment by 532910** [comment]
Still actual

**Comment by 532910** [comment]
It's a pity, bluetooth support is poor ):

**Comment by saghul** [comment]
A PR would be welcome, but our time is limited.
