### ISSUE TITLE
Android - Disable 'Video turned off to save bandwidth” in SDK

### ISSUE THREAD

**Issue by namangt68** [jitsi/jitsi-meet#9384]
**Is your feature request related to a problem you are facing?**
We are facing issue of frequent 'video goes black screen' in Jitsi integrated in our Android app using mobile sdk. The video goes black screen Sometimes it does not recover. 
How can we disable this from Android SDK?

**Describe the solution you'd like**
A solution is mentioned here for jitsi videobridge here  - [https://community.jitsi.org/t/jitsi-users-video-turned-off-to-save-bandwidth-on-meet-jit-si/12735](https://community.jitsi.org/t/jitsi-users-video-turned-off-to-save-bandwidth-on-meet-jit-si/12735).
It can be done the same way in Android SDK

**Comment by liangguohao66** [comment]
is there an  answer?

**Comment by hshaharia064** [comment]
i facing the same issue, the video goes of with the message 'the video has been diabled to save bandwidth, i have tried adjusting the simulcast, lastN, resolution, bitrate, i have self hosted on a 10vcpu vps, and its bandwidth is enough (2tb), also the uplink/downlink is 3Gbps
