### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by radimkohout** [jitsi/jitsi-meet#9387]
Hello,
I want to help translate jitsi-meet to my local language(cs). I've looked in files main-cs.json and main.json. 
When I compare cs and default main, there are some translations, that are missing in main, as you can see for example here: 
![image](https://user-images.githubusercontent.com/22203368/121810373-ecff1980-cc60-11eb-93e8-ac4c6a2129bf.png) 
The cs file is even longer than main.json , even that there are some translations missing from default main.
**How does the translation work?**

**Comment by damencho** [comment]
We don't have a translation system at the moment to sync those.
You can use main.json as a template and copy key structures and translate them. Things you don't translate skip the key in your language and it will default to the template.

Please when you have questions or problems use the community forum before opening new issues, thank you.
