### ISSUE TITLE
Message will be accidentally sent when using ENTER to choosing word with Mandarin IM

### ISSUE THREAD

**Issue by danie1Lin** [jitsi/jitsi-meet#9393]
### Description:

I use mandarin IM(Input Method) like pinyin (拼音), or 注音, sometimes using ENTER to chose a word. the message will accidentally be sent

### Steps to reproduce:

1. use mandarin IM like pinyin 
2. typing "pinyin" and hit ENTER

### Expected behavior:

should show literally the "pinyin" English characters in the input

### Actual behavior:

the message will accidentally be sent directly
but the "pinyin" characters still left in the input column

**Comment by daniel840829** [comment]
https://github.com/jitsi/jitsi-meet/blob/60188794b505b913f81d9ec4e781a27021ea42c1/react/features/chat/components/web/ChatInput.js#L212
It should use another way to determine the submission event
