### ISSUE TITLE
[IFRAME API] The video facing mode constraint is not working anymore in IOS safari

### ISSUE THREAD

**Issue by nadelicious** [jitsi/jitsi-meet#9394]
**Problem:** 
 The facing mode constraint config is not working anymore in IOS safari.

**Config:**
```
configOptions.configOverwrite = {
   constraints: {
     video: {
       facingMode: 'environment'
     }
   }
}
```

**Expected:**  
  The facing mode config should be working. 
  Working sample: https://philnash.github.io/mediadevices-camera-selection/
  
  @jallamsetty1

**Comment by jallamsetty1** [comment]
Thanks for the report @nadelicious, I will check if there is a open webkit bug for this issue. I will repro and open a bug if there isn't.

**Comment by nadelicious** [comment]
@jallamsetty1 I think it's not related to the safari version.  We tried it with the lower version and the issue can be still replicated. Maybe it was affected by these changes https://github.com/jitsi/lib-jitsi-meet/commit/ad5692d6aa42800a1c251e05261ef05bfe2a7f79 ? I'm not sure. Any thoughts?

**Comment by jallamsetty1** [comment]
> jitsi/lib-jitsi-meet@ad5692d



> @jallamsetty1 I think it's not related to the safari version. We tried it with the lower version and the issue can be still replicated. Maybe it was affected by these changes [jitsi/lib-jitsi-meet@ad5692d](https://github.com/jitsi/lib-jitsi-meet/commit/ad5692d6aa42800a1c251e05261ef05bfe2a7f79) ? I'm not sure. Any thoughts?

Thanks for the pointer @nadelicious, let me check what changed in the commit and get back to you.

**Comment by jallamsetty1** [comment]
@nadelicious,
Do you use the resolution config.js option for specifying the resolution ?

**Comment by jallamsetty1** [comment]
Can you please check if [this](https://github.com/jitsi/lib-jitsi-meet/commit/46ec23fcdc416f997f766a6b8d197662bc9abf9e) commit fixes your issue ?

**Comment by nadelicious** [comment]
> Can you please check if [this](https://github.com/jitsi/lib-jitsi-meet/commit/46ec23fcdc416f997f766a6b8d197662bc9abf9e) commit fixes your issue ?

I think so. When this will be merged to 8x8.vc?

**Comment by jallamsetty1** [comment]
> > Can you please check if [this](https://github.com/jitsi/lib-jitsi-meet/commit/46ec23fcdc416f997f766a6b8d197662bc9abf9e) commit fixes your issue ?
> 
> I think so. When this will be merged to 8x8.vc?

Thanks for verifying the fix. We pushed out a release on 8x8.vc last Friday. I am not sure when the next release is planned. Until then, you can use a workaround. Instead of using resolution option in config.js, you can specify the resolution under constraints along with the camera facing mode. Something like this.

```
constraints: {
        video: {
            height: {
                ideal: 720
            },
            facingMode: 'environment'
        }
    },
```

**Comment by jallamsetty1** [comment]
Closing the issue since it is fixed by [this](https://github.com/jitsi/lib-jitsi-meet/commit/46ec23fcdc416f997f766a6b8d197662bc9abf9e) commit.

**Comment by nadelicious** [comment]
> > > Can you please check if [this](https://github.com/jitsi/lib-jitsi-meet/commit/46ec23fcdc416f997f766a6b8d197662bc9abf9e) commit fixes your issue ?
> > 
> > 
> > I think so. When this will be merged to 8x8.vc?
> 
> Thanks for verifying the fix. We pushed out a release on 8x8.vc last Friday. I am not sure when the next release is planned. Until then, you can use a workaround. Instead of using resolution option in config.js, you can specify the resolution under constraints along with the camera facing mode. Something like this.
> 
> ```
> constraints: {
>         video: {
>             height: {
>                 ideal: 720
>             },
>             facingMode: 'environment'
>         }
>     },
> ```

I'm using the constraints config and it's on the description of this issue.

**Comment by nadelicious** [comment]
> @nadelicious,
> Do you use the resolution config.js option for specifying the resolution ?

I'm not using resolution. Sorry I didn't notice this reply.

**Comment by jallamsetty1** [comment]
@nadelicious FYI, The fix was deployed on 8x8.vc yesterday.
