### ISSUE TITLE
Disconnected from videoconference when network switches from wifi to 4g

### ISSUE THREAD

**Issue by mhamdihajer1** [jitsi/jitsi-meet#9396]
### Description:

when switching from 4G to WIFI or vise versa the videoconference was stopped

### Steps to reproduce:

1. start video conference
2. switching from 4G to WIFI
3. no sound heard

### Expected behavior:

videoConference should be reconnect again

### Actual behavior:

the popu of reconnect open and directly the videoconference Screen was closed

### Server information:

- Operating System:Operating System: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-67-generic x86_64)

### Client information:

- Android
- SDK Jitsi Meet version: 3.5.0

### Additional information:

Bug happen on 06-15 10:12 see log attached
[JitsiLog.txt](https://github.com/jitsi/jitsi-meet/files/6656331/JitsiLog.txt)

**Comment by mhamdihajer1** [comment]
Hi,
Any update ?

**Comment by shoolpani-dubey** [comment]
+1 
I am also facing the same issue . Good to know that its work in progress.

**Comment by saghul** [comment]
The next SDK version (4.0.0) contains a fix for this. The reload dialog is presented when a meeting fails, with a countdown and the possibility to rejoin immediately.

We hope to release it soon.
