### ISSUE TITLE
Handle virtual background through the IFrame API

### ISSUE THREAD

**Issue by glutzm** [jitsi/jitsi-meet#9399]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

I use the application for customer service, and to create a standardization in my service I need the virtual background to be the same between the attendants.

**Describe the solution you'd like**
Please describe the desired behavior.

I would like it to be possible, through the [IFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe), to set a virtual background using a reference link, like an image on Amazon S3.
This way I can always, through the API, create the attendant's session with a default virtual background.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

Being able to select a default virtual background through the [IFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe), where the file is on the server/container.

**Comment by MarkusPaul1989** [comment]
Nice idea.
I have built a custom prejoin page that passes the user selection to the iframe api and would like to have something like a configOverwrite "startWithVirtualBackground" with parameters for default backgrounds as well as the ability to link to an external resource.

**Comment by beyondlevi** [comment]
Excelent idea.

We could have a command that sets an virtual background passing an image url. Other command to disable could be useful to or just passing null to the other command.

**Comment by saghul** [comment]
@horymury Do you remember if we added API commands for this?
