### ISSUE TITLE
jitsi doesn't work with docker

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#9402]
### Description:

With an active docker container, it's impossible to connect jitsi meeting, or there are no sound from these clients.
This problem reported by several users, I've not tried to reproduce it yet.

### Steps to reproduce:

1. Start some docker containers
2. Try to connect jitsi meeting

### Expected behavior:

It should work.

### Actual behavior:

Jitsi session just ends or there are sound glitches.

### Server information:

- Jitsi Meet version: The latest from official jitsi repository
- Operating System: Debian stable

### Client information:

- Browser / app version: Firefox
- Operating System: Linux

**Comment by 532910** [comment]
Still actual

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

If you still experience it, open an issue in the docker project attaching logs from the js console of the client experiencing the issue.
