### ISSUE TITLE
Destroy Lobby Room: Set Member Only False

### ISSUE THREAD

**Issue by engesin** [jitsi/jitsi-meet#9405]
Hi,

To be able to work with handle_destroy_lobby, we need to set member only to false too.

event.room:set_members_only(false);

Can you check it please.

https://github.com/jitsi/jitsi-meet/blob/be73ed9d191c74b7f57d3124b4bc45a50ec55dd8/resources/prosody-plugins/mod_muc_lobby_rooms.lua#L390

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you!



> To be able to work with handle_destroy_lobby, we need to set member only to false too.

Why is that?

Maybe give an example of what you are trying to accomplish with some code. We are using this with an external module without a problem.

**Comment by damencho** [comment]
Yep, we always use it with calling first set room:set_members_only(false); and then the event, it is just to do the cleanup that the module had created around the room.

**Comment by engesin** [comment]
hmm I use as you said to fix my problem. However I thought firing 'destroy-lobby-room'  is sufficient to disable lobby feature. 

thank you.
