### ISSUE TITLE
Need Call Duration

### ISSUE THREAD

**Issue by cgowthamanmca** [jitsi/jitsi-meet#9406]
Duration option is need because of we can see how many minute discussed .

**Comment by damencho** [comment]
Call duration is already available.

**Comment by ibglobal12** [comment]
Hi @damencho @cgowthamanmca @goblin @jcfischer @monkeydom @ I am still not able to find call duration . Can you help me how to send meeting duration from jitsi meet to external API ? I will be thankful of you .

**Comment by ibglobal12** [comment]
we have to check how many minutes of meeting has happened with users in meeting and saving the duration of every user

**Comment by damencho** [comment]
You need something like this module so you can save stats for meetings and duration
https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync

**Comment by ibglobal12** [comment]
Ready to close function file location with directory where we can see the events with function which are present.? Kindly help me .

**Comment by ibglobal12** [comment]
@damencho @goblin @jcfischer Ready to close function file location with directory where we can see the events with function which are present.? Kindly help me
