### ISSUE TITLE
whiteboard Option  

### ISSUE THREAD

**Issue by cgowthamanmca** [jitsi/jitsi-meet#9407]
The purpose of a whiteboard is to visualize thoughts, concepts, write down ideas, explain and teach, to plan and create in the group and many other things. Online whiteboards can be used for the same purpose as a real whiteboard, but without the limitations of a real whiteboard

**Comment by kenshin33** [comment]
etherpad has a plugin for WBO or you can use WBO instead of etherpad. on your hosterd instance that is ...
