### ISSUE TITLE
A long-standing problem: Can't find variable : window

### ISSUE THREAD

**Issue by Hin-D** [jitsi/jitsi-meet#9412]
I found a problem in this project.
Repeat the steps：
1. clone the project.
2. delete folder node_modules and file package-lock.json
3. npm install & pod install & run
4. then you will find the error like this issue:
https://github.com/jitsi/jitsi-meet/issues/8674

Hope to solve this problem, or give others a prompt can't delete the file package-lock.json.

**Comment by saghul** [comment]
Please don’t open duplicate issues.
