### ISSUE TITLE
Jitsi meet voice echo issue while speaking and playing instrument

### ISSUE THREAD

**Issue by kylemyr** [jitsi/jitsi-meet#9419]
I've just got this issue for whole day, but it didn't exist yesterday. So, I am not sure if that's just an occasional problem or it will remain after all.

I am using jitsi to teach music lesson, and there are certain circumstances that my student will hear his voice echo, or vice verso, I hear my voice or instrument sound echoed. 

For the best experience of instrument lessons, I setted up my audio quality to "stereo" with a 192000 bitrate. It's totally fine and did incredible job for 3 days, and then echo comes today. I tried to add  - disableAEC: true - disableNS: true, in config.js, that didn't work. I try to reinstall / reboot, didn't work as well. 

I surfed around on the internet, I tried many things but nothing work out, and it seems not only myself has this sudden issue, but also many people does and we have no good answer for that. 

So I am here to ask if somebody could give me a hint or something I can do to remove that annoying sound echo?

**Comment by damencho** [comment]
Is this about meet.jit.si or your own deployment?

**Comment by kylemyr** [comment]
@damencho thank you for your reply, I installed the jitsi on Linode, so I am not sure which one it belongs to.

**Comment by kylemyr** [comment]
@damencho thank you for your reply, I am using jitsi for my own deplyment, I intalled it on Linode.com. I don't know if that will make any difference. Thank you.

**Comment by rasos** [comment]
Echo cancellation seems to be not active when there is set
 
  stereo: true,

See also #9447

**Comment by saibotma** [comment]
According to the documentation, echo cancellation should also be disabled when `stereo` is disabled but `opusMaxAverageBitrate` is set. 

https://github.com/jitsi/jitsi-meet/blob/df6eff880485a0b2c56e37c7639bd3212c641ac9/config.js
```
 // Specify audio quality stereo and opusMaxAverageBitrate values in order to enable HD audio.
 // Beware, by doing so, you are disabling echo cancellation, noise suppression and AGC.
 // audioQuality: {
 //     stereo: false,
 //     opusMaxAverageBitrate: null // Value to fit the 6000 to 510000 range.
 // },
```

I tried it out and this is not the case, as echo cancellation is still enabled according to the console logs:

https://meet.jit.si/xxx#config.p2p.enabled=false&config.disableAEC=false&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true&config.opusMaxAverageBitrate=192000
`2022-02-03T20:58:55.471Z [modules/RTC/RTCUtils.js] <6295/obtainAudioAndVideoPermissions/r<>:  Got media constraints:  {"video":false,"audio":{"autoGainControl":false,"echoCancellation":false,"noiseSuppression":false,"channelCount":2}}
`

https://meet.jit.si/xxx#config.p2p.enabled=false&config.disableAEC=false&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.opusMaxAverageBitrate=192000
`2022-02-03T20:56:28.103Z [modules/RTC/RTCUtils.js] <6295/obtainAudioAndVideoPermissions/r<>:  Got media constraints:  {"video":{"height":{"ideal":720,"max":720,"min":180},"width":{"ideal":1280,"max":1280,"min":320},"facingMode":"user"},"audio":{"autoGainControl":false,"echoCancellation":true,"noiseSuppression":false}}`

Is the documentation or the implementation wrong? Or am I confusing some settings?

**Comment by saghul** [comment]
> I tried it out and this is not the case, as echo cancellation is still enabled according to the console logs:
> 
> https://meet.jit.si/xxx#config.p2p.enabled=false&config.disableAEC=false&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true&config.opusMaxAverageBitrate=192000 `2022-02-03T20:58:55.471Z [modules/RTC/RTCUtils.js] <6295/obtainAudioAndVideoPermissions/r<>: Got media constraints: {"video":false,"audio":{"autoGainControl":false,"echoCancellation":false,"noiseSuppression":false,"channelCount":2}} `

Why do you think those logs indicate echo cancellation is still enabled?

**Comment by saibotma** [comment]
> Why do you think those logs indicate echo cancellation is still enabled?

Excuse me for not expressing my self clear enough. I edited my comment. Please take another look.

**Comment by saghul** [comment]
I realize the comment is a bit misleading. It o lot applies to the "stereo" setting.

**Comment by saibotma** [comment]
I think this should not be closed.

**Comment by affanminhas** [comment]
I also faced the same echo issue, but I noticed that I was testing with two devices in the same room, which caused the echo if the headset was not plugged in. I tried with my client testing from far away, and there was no issue, and we had a perfect conversation. I integrate it into Flutterapp.
