### ISSUE TITLE
offer to include a custom CSS file

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#9422]
If you browse through the community forum we can see several questions regarding slight adaptions of the style. This usually requires de-minifying the `all.css` file and apply changes there.  However all the changes get lost after each update. 

The DevOps life would be easier, if a `custom.css` file would be included, which does not get updated automatically.

Two observations with `all.css` when customizing it:

We had to remove the 100% lines two times, otherwise links can not be clicked on the `WelcomePageAdditionalContent.html` page on the bottom:

```
.welcome .welcome-watermark {
    position: absolute;
    width: 100%;
    height: 100%}
```

In order to make use of another font defined later in `all.css` we had to remove `important!` at the end of

```
body, button, input, keygen, select, textarea {
    font-family: -apple-system, BlinkMacSystemFont, open_sanslight, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

**Comment by damencho** [comment]
You can always include your css before or after the all.css file. 
Before it you can include it in https://github.com/jitsi/jitsi-meet/blob/master/head.html
Or after it in https://github.com/jitsi/jitsi-meet/blob/master/plugin.head.html 
You can define your set of files and source them from etc folder in the nginx config similar the config.js file ... 

For the other problems, you have with !important and position you can create a PR with the changes and we can review and merge it to be available in future versions. 
Or include some kind of sample for testing with the PR or here in the issue so we can make sure if we need changes to make it compatible with your example and our branding for meet.jit.si ... Thank you.

**Comment by damencho** [comment]
For the links problem that is strange, but you can check the welcomepage of https://meet.jit.si, there are already links about privacy policy and terms, and the app store/google store links, you can check how that works.
