### ISSUE TITLE
Red End Button not working on landscape mode , OnePlus 5t mobile phone.

### ISSUE THREAD

**Issue by subhra9326** [jitsi/jitsi-meet#9431]
The problem is in landscape mode call end button not working. I have found this issue due to call end button is showing outside the boundary of other buttons view.

**Comment by damencho** [comment]
Which version of jitsi-meet do you use?

**Comment by subhra9326** [comment]
again stripe and Jitsi meet not working together with the latest version
my version is
flutter_stripe: ^1.0.2
  jitsi_meet: ^4.0.0
, can anyone please tell me the reason why it's happening and what is the solution for that.
