### ISSUE TITLE
Remove 3 dot option on flutter

### ISSUE THREAD

**Issue by avonwagle** [jitsi/jitsi-meet#9445]
I am using jitsi_meet 4.0.0 plugin for integrating on my flutter app. I wanted to remove the 3 dot option that appears on the right side of bottom sheet disabling all options to users. Is there a way to do so? Or is there a way to disable all flags which are enabled by default.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

**Comment by saghul** [comment]
There is no way to disable that button.
