### ISSUE TITLE
[iOS] Lots of <br> tags in email body, from share meeting invitation

### ISSUE THREAD

**Issue by stephendonner** [jitsi/jitsi-meet#9446]
### Description:

Lots of `<br>` tags in email body, from share meeting invitation.

Spinning this off from the closed https://github.com/jitsi/jitsi-meet/issues/9114, so it's more targeted.

(This might very well be a bug on Apple's side, and something to work around by sniffing iOS versions, if possible, and for affected versions, only send content as type text/plain, if possible?)

This doesn't appear to happen on either `iOS 12.4` or `iOS 14.4.2`

### Steps to reproduce:

1. launch Safari on `iOS 14.7` ((`18G5042c`), public beta)
2. load `meet.jit.si`
3. tap on `Start meeting`
4. tap on `Launch in web`
5. tap `Allow` when prompted for microphone and camera access
6. tap `Done`
7. enter a name
8. tap `Join meeting`
9. tap on the two-person icon
10. tap `Invite someone`
11. tap `Share meeting invitation`
12. tap on the email icon
13. look at the resulting email markup

### Expected behavior:

No `<br>` tags in the body of the prepopulated email markup, if possible.

### Actual behavior:

![Image from iOS](https://user-images.githubusercontent.com/387249/123351759-b653b980-d512-11eb-9301-4b45991195a4.png)

Lots of `<br`> tags make their way into the prepopulated email body's markup.

### Client information:

- Browser / app version: Safari
- Operating System: `iOS 14.7 (18G5042c)`

/cc @mrose17 @iccub

**Comment by mrose17** [comment]
LGTM.
