### ISSUE TITLE
[ios] Unable to resolve module `../jaas/middleware` from `react/features/app/middlewares.any.js` 

### ISSUE THREAD

**Issue by Faisalkc4u** [jitsi/jitsi-meet#9458]
1. I cloned the repository 
2. npm Install
3. cd ios
4. pod install
5. opened jitsi-meet.xcworkspace in xcode
6. RUIN
7. 
![IMG_5999](https://user-images.githubusercontent.com/12441355/123549240-33806800-d779-11eb-99b9-0de61caca238.PNG)

**Comment by quitrk** [comment]
Solved by https://github.com/jitsi/jitsi-meet/commit/01867ed343cbe8d97acefd2dd0a86e153779cd76 and https://github.com/jitsi/jitsi-meet/commit/c356c2360ce0211a82a8711d7119e12dbfa2c289
