### ISSUE TITLE
iOS Archive not building error flutter jitsi_meet: ^4.0.0

### ISSUE THREAD

**Issue by mayurpatilin** [jitsi/jitsi-meet#9472]
getting this error when I try to archive iOS for App Store flutter jitsi_meet: ^4.0.0

Ld /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/jitsi_meet.framework/jitsi_meet normal (in target 'jitsi_meet' from project 'Pods')
    cd /Users/mayurpatil/Desktop/Projects/Forem\ Meet\ v4/Forem\ Meet/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/jitsi_meet -F/Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/jitsi_meet -F/Users/mayurpatil/Developer/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-armv7_arm64 -F/Users/mayurpatil/Desktop/Projects/Forem\ Meet\ v4/Forem\ Meet/ios/Pods/JitsiMeetSDK/Frameworks -F/Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/JitsiMeetSDK -F/Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC -filelist /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/jitsi_meet.build/Objects-normal/arm64/jitsi_meet.LinkFileList -install_name @rpath/jitsi_meet.framework/jitsi_meet -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/jitsi_meet.build/Objects-normal/arm64/jitsi_meet_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/jitsi_meet -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/jitsi_meet.build/Objects-normal/arm64/jitsi_meet.swiftmodule -framework JitsiMeetSDK -framework WebRTC -framework Flutter -framework Foundation -framework jitsi_meet -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/jitsi_meet.build/Objects-normal/arm64/jitsi_meet_dependency_info.dat -o /Users/mayurpatil/Library/Developer/Xcode/DerivedData/Runner-ezppaeigwyqjymdjakkpzqtuduil/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/jitsi_meet.framework/jitsi_meet

ld: framework not found jitsi_meet
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by saghul** [comment]
We are not the maintainers of the Flutter plugin. Please ask the authors.
