### ISSUE TITLE
Enable Hermes and update react-native version to 0.64.2

### ISSUE THREAD

**Issue by keremoge** [jitsi/jitsi-meet#9481]
**Is your feature request related to a problem you are facing?**
Yes, because Hermes is not enabled in Jitsi SDK, I have to disable Hermes in my react-native app too. 
And also because ReactNative is not up to date, there are possible bugs and performance issues

**Describe the solution you'd like**
Having main project's Hermes option. If user enabled Hermes then Jitsi should use hermes too.
And also ReactNative version should be up to date because of various fixes and bugs

**Describe alternatives you've considered**
Hermes should be optional/parametric or
An Alternate is creating Hermes Disabled and Hermes Enabled SDKs on each build

**Comment by keremoge** [comment]
And also React-Native 0.64.* is introduced Hermes for iOS

**Comment by saghul** [comment]
For the record, we used to have Hermes enabled, and didn’t get good results. We will try again, after updating RN.

**Comment by spidi123q** [comment]
@saghul 
It will be really helpful if at least RN is updated to 64. Due to old version in jitsi SDK , my app also stuck with old one

**Comment by alexstoyanov** [comment]
@saghul Do you have any timeline about when that would happen(enable Hermes for Jitsi)?

**Comment by saghul** [comment]
No timeline, sorry.

**Comment by gigabyteservice** [comment]
@saghul please update the react-native we want to use an updated socket,  Socket.io - 4.0.0 and the older version is creating an issue.
thanks

**Comment by KolissnikBogdan** [comment]
@saghul hi, do you have any news for this update?

**Comment by saghul** [comment]
No update. It won't happen anytime soon is all I can say. We have many other things to do at the moment which have higher priority.

RN updates have been painful in the past and 0.61.5 has been rock solid, we're not in a rush.

**Comment by keremoge** [comment]
Quote on React Native Blog: _"While we will continue supporting other JavaScript engines, we recommend everyone to migrate to **Hermes** to have the best experience and to make sure we can support you better."_
https://reactnative.dev/blog/2022/06/21/version-069#bundled-hermes

**Comment by saghul** [comment]
We are now on 0.68, son once we upgrade to 0.69 we can give it another try perhaps.

We will not be upgrading to 0.69.0, however. I've been bitten by .0 releases far too many times now.

Last, an interesting observation is that prebuilts for Android won't seem to work if you enable new architecture, which they also recommend on doing... I'm honestly not too confident in the proposed combination, so I'll definitely hold on new architecture for a couple more releases.

**Comment by keremoge** [comment]
> We are now on 0.68, son once we upgrade to 0.69 we can give it another try perhaps.
> 
> We will not be upgrading to 0.69.0, however. I've been bitten by .0 releases far too many times now.
> 
> Last, an interesting observation is that prebuilts for Android won't seem to work if you enable new architecture, which they also recommend on doing... I'm honestly not too confident in the proposed combination, so I'll definitely hold on new architecture for a couple more releases.

Wow, thanks for the fast reply :)
