### ISSUE TITLE
Adding an option to play a video playlist or an add to queue option

### ISSUE THREAD

**Issue by ankurg132** [jitsi/jitsi-meet#9485]
**Is your feature request related to a problem you are facing?**
I'm currently using Jitsi Meet share video feature to share a YouTube video in the meet using the "Share Video" option which is working beautifully. However, to change the current video specially when I want to stream a whole playlist is quite cumbersome as I need to stop the video and then start again with a new link.

**Describe the solution you'd like**
I would like to have a feature where you can stream the whole YouTube or any other video playlist through just a single playlist link or an add to queue option where you can add the videos to keep them playing one after another.

**Comment by saghul** [comment]
That's a limitation of the YT iframe API I'm afraid.

**Comment by glenncjblack-CDA** [comment]
I also need this capability in Jitsi.

I see YouTubes API has now been modified, making this possible. See:
https://www.google.com/search?q=youtube+iframe+API+queue+multiple+videos&rlz=1C1CHBF_enCA1190CA1204&oq=youtube+iframe+API+queue+multiple+videos&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigATIHCAQQIRigAdIBCTMyNTgzajBqNKgCALACAQ&sourceid=chrome&ie=UTF-8

https://stackoverflow.com/questions/63684054/recent-changes-to-youtube-api-for-embedding-multiple-videos-in-dynamic-playlist

Can we please do this soon?

**Comment by saghul** [comment]
I don't think we can have it soon. 

Someone still needs to do the work.

Are you up for it?

**Comment by glenncjblack-CDA** [comment]
What do you code in?

Glenn Black
Black's Bay Farm
