### ISSUE TITLE
Hide some features in mobile sdk

### ISSUE THREAD

**Issue by said15904** [jitsi/jitsi-meet#9487]
Hi,
I have some difficulty to hide lobby mode and mute (audio, video) for all participants
i try this setFeatureFlag(“lobby-mode.enabled”, withBoolean: false ) for lobby mode but not working
and for mute everyone i don’t see any features to configure that.
Thank you.

**Comment by ankar84** [comment]
Agree with easy way to configure some interface elements and menu items.

**Comment by saghul** [comment]
These are the implemented flags: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js Note you need to be in the latest SDK version in order to use them.

If you'd like a specific flag implemented please open a specific issue, or better yet, a pull request :-)
