### ISSUE TITLE
Start/stop recording screens need padding on mobile (for Brave on iOS)

### ISSUE THREAD

**Issue by stephendonner** [jitsi/jitsi-meet#9489]
### Steps to reproduce:

1. launch Brave release, `1.27.1 (21.6.22.16)` on iOS 14.7 (18G5052d)
2. load `talk.brave.software`
3. tap on `Start video call`
4. tap `Allow` at the permissions prompt
5. enter your name, tap `Join meeting`
6. tap on the ellipsis at the bottom `...`
7. tap on `Start recording`
8. tap on the ellipsis at the bottom, again 
9. tap on `Stop recording`
10. look at the resulting screen's layout

### Expected behavior:

Should match Meet Jitsi's top padding

### Actual behavior:

Brave Talk's top padding is off, making it look a little odd, and making the tap target for the `x` widget at the top right harder to hit

Brave Talk | Jitsi Meet
-----------|----------
![Image from iOS (1)](https://user-images.githubusercontent.com/387249/124307926-5c0fb580-db1d-11eb-864c-b7f27d8f9bf2.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/124307930-5d40e280-db1d-11eb-9139-666566f23646.png)

### Client information:

- Browser / app version: Brave 1.27.1 on iOS
- Operating System: iOS 14.7

/cc @mrose17 just FYI

**Comment by quitrk** [comment]
Not sure if fixed or iOS difference, but this is how it looks for me on Brave 1.27.1 on iOS 14.6
![IMG_849E70B4C650-1](https://user-images.githubusercontent.com/1556279/124453258-de9fab80-dd8f-11eb-8629-df76bf0fd8a3.jpeg)

**Comment by stephendonner** [comment]
Verified `FIXED` on `talk.bravesoftware.com` using Brave 1.28 (21.7.9.13) on an iPhone 8 Plus running a public beta of iOS 15

iPhone 8 Plus

start recording | end recording
---------------|---------------
![Image from iOS (1)](https://user-images.githubusercontent.com/387249/125679814-446cfcf3-166e-490f-9b22-25737bc2b4d0.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/125679821-88ac0bbf-18f8-41ca-bed5-abbdd777ba0e.png)

iPhone 6s

start recording | end recording
---------------|---------------
![Image from iOS (2)](https://user-images.githubusercontent.com/387249/125680369-3e597bda-9374-4f08-8788-c50d7080824e.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/125680372-74c79573-8734-4f86-9b03-3c9e4bb93469.png)
