### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'scope._metadataStorage.save')

### ISSUE THREAD

**Issue by sagarzala123** [jitsi/jitsi-meet#9493]
While click on Audio on/off, I am getting this error in Android

W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 7):
    TypeError: undefined is not an object (evaluating 'getState(state).audioModerationEnabled')
    isEnabledFromState@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:301335:72
    shouldShowModeratedNotification@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:301398:30
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:339542:69
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:361331:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:361155:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:360703:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:360162:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:359996:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:359911:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:359793:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:357915:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:356999:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:356399:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:356118:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:356053:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:354387:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:354182:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:353715:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:353583:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:353534:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:353452:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:353328:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:353307:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:351497:26
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:351296:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:349789:20
    _callee$@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:349666:54
    tryCatch@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26098:23
    invoke@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26271:32
    tryCatch@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26098:23
    invoke@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26171:30
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26201:19
    tryCallTwo@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:27462:9
    doResolve@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:27626:25
    Promise@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:27485:14
    callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26200:33
    enqueue@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26205:157
    async@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26222:69
    _callee@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:349643:42
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:349583:20
    http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:348872:20
    http://10.0.2.2:8081/ind

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you!

This had been fixed 
https://github.com/jitsi/jitsi-meet/commit/ae9bea1a0cb4d884edd9e0b7bac93bfa4c8021b9

**Comment by sagarzala123** [comment]
Thanks it's working.

**Comment by sagarzala123** [comment]
@daimoc After updating code, I am unable to mute/unmute and video on/off from meeting screen.

**Comment by sagarzala123** [comment]
@damencho I need to create new issue or you give me solution on current issue?

**Comment by damencho** [comment]
Create new issue adding the console logs.

**Comment by sagarzala123** [comment]
@damencho 
I created a new ticket. Please help me.
https://github.com/jitsi/jitsi-meet/issues/9530
