### ISSUE TITLE
Name in chat is changed locally with the wrong one after accessing a second time to a meeting

### ISSUE THREAD

**Issue by jmalarcon** [jitsi/jitsi-meet#9494]
### Description:

When you access the same meeting (that already has previous chat messages) with a different name, even in private tabs, the name for some users in the chat messages change, most of the time using "Fellow Jister". This is just a local change, but very confusing.

### Steps to reproduce:

1. Start a new meeting in https://meet.jit.si/ (in a Private Tab to ensure there is no data left) and name you user as User01. Write a "Hello from User01" message.
2. Access the same meeting (for example from Firefox and Edge, private tabs too, if you're in the same computer, but it doesn't matter: you can use several computers) and add users User02 and User03. Send messages to the chat from them. You'll have at least one message from each user for testing purposes (everything OK 'till now):

![jitsi-chat-bug-01](https://user-images.githubusercontent.com/1775322/124437838-c4f26a00-dd77-11eb-83f0-2bbd40c2ec69.png)

3. Now exit the meeting from one of them, for example User03. Access again to the same meeting but **change your name before accessing**. For example, exit with User03 and access again **with the same browser** (even in a Private tab), entering User04 as the new name. If you open the chat with the old messages, you'll see that in **your chat** your old name appears as "Fellow Jitster", not with the old name or the new. The rest of the chats keep the old name (for now):

![jitsi-chat-bug-02](https://user-images.githubusercontent.com/1775322/124438067-084cd880-dd78-11eb-9b16-42e4a0d34320.png)

4. Now exit the meeting with another user, for example User02. Access the same meeting again with the same browser and use a different name, i.e, User05. Now the same thing happens to your old user in the chat, and, apart from this, the other user that exited and accessed again, shows "Fellow Jitster" in your chat too (nth of you show it):

![jitsi-chat-bug-03](https://user-images.githubusercontent.com/1775322/124438311-5235be80-dd78-11eb-9b8a-f4862a510eec.png)

Most of the times the name that appears is "Fellow Jitster", but many times **the new name of the user is used and ends up in another random user of the chat**, not only in messages previously sent by the same usar. In large meetings (let's say 15 or 20 people) if more users leave the meeting and access it again, the chats end up with all the names totally scrambled.

As long as a user doesn't leave the meeting, the bug goes unnoticed, but if she access the meeting again, the chat gets modified.

### Expected behavior:

The names assigned to chat messages should remain the same for the whole meeting despite the fact some users exit or access it again.

### Actual behavior:

Please, see the steps and the screenshots above.

### Server information:

- Jitsi Meet version: Latest Jitsi version available in https://meet.jit.si/ as of 07/05/2021
- Operating System: Windows 10 Enterprise 19043.1052, but it happens in any OS

### Client information:

- Browser / app version: All latest versions of Chrome, Firefox, Edge, Opera, Vivaldi, Brave...
- Operating System: Windows 10

**Comment by damencho** [comment]
This is as expected. Storing the names was removed as it gives an option for impersonating messages from malicious users.
When the participant is not in the room, we cannot guarantee the display name, and the default name is used.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

**Comment by jmalarcon** [comment]
Hi: I think you didn't understand the issue well, or I explained myself incorrectly (English is not my native language: sorry for that).

The problem is not that the name is not kept. The problem is that, when someone reenters a room, there's a change in the names of the chat, resulting in scrambled names of the real people that wrote them in the first place. It starts just in the re-entering user chat, but as more of them leave and re-enter, it gets worse. A lot of times it changes some names to the default name of the reentering users, but many other times it's a totally different user name. And it doesn't change only the name of the returning user. Sometimes it changes other people names too.

What We've observed in some rooms with 15 to 20 people and a moderate use of the chat, is that attendees end up confused because, as some people go out and return to the room in the middle of a session, the chats start to change the names of already sent messages, and they can't follow the conversation.

I tried to create a simple way to reproduce the case, but in a real room full o people using the chat and some of them entering and leaving several times, the problem is more evident, albeit more difficult to track. Please, do me a favor: read it again paying attention to the screen captures I've used, and I think it's pretty clear it's an issue.

IMHO this is not a support question, but an issue: I'm sorry if you think I'm using the wrong channel, but I did it knowingly 

Thanks.

**Comment by damencho** [comment]
So if someone leaves, its messages for new users will be from Fellow Jitster, this is expected.

**Comment by damencho** [comment]
What is I see from your screenshots the messages from participant that left are shown as Fellow Jitster and is not unexpected

**Comment by jmalarcon** [comment]
Sorry for considering it an issue if it's by design, but it's pretty common that someone leves a room and come back after a while (they need to go and return in a few minutes, or they lost connectivity and return after recovering it). And, in a 2 or 3 hour meeting, in a crowded room with chat, in my experience what happens is that a lot of people end up not knowing who said what in the chat because of this. And in rooms where there's only one person talking (let's say a teacher) and the rest of the attendees (students) are just using the chat, it causes a lot of confusion.

I understand keeping the ID of the user to match the names in the chat can cause some impersonation issues, but this can be a problem too.

Thanks anyway and thanks for your great work.

**Comment by damencho** [comment]
We understand that, but impersonating can bring more harm than the confusion of missing display names. 
There is no way in solving this at the moment.
