### ISSUE TITLE
Cannot open Jitsi Website in Safari/Firefox/Chrome(Handy) 

### ISSUE THREAD

**Issue by Kiagami** [jitsi/jitsi-meet#9495]
### Description:

Hello, our Jitsi Meet is running over Docker with a customize.sh script that writes changes in .jitsi-meet-cfg and a restart script restart.sh that redownloaded the newest version of Jitsi and starts the docker containers , so everything is up to date.

I did not look on the server that much but I tried to go on our Jitsi web site , but there is following web error:

uh oh! we couldn't fully download everything we needed :( we will try again shortly. In the Mean time, check for problems with your internet connection!

Missing https://jitsi.server.de/libs/app.bundle.min.js?v=5056

### Additional information:

In Google Chrome shortly after opening our Jitsi site , I get the error message but will send automatic to the our Jitsi Website. This does not work in Safari or Firefox. If I open our Jitsi Website on my phone via chrome I get the error message and nothing happens. This looks like a bug, because it kinda working properly in chrome on my pc.

Jitsi was running since February this year but now we running in this issue. Updating and restarting nginx and Jitsi did not solve the problem.

**Comment by damencho** [comment]
Please use the community forum before opening new issues, thank you.

This is some misconfiguration on your side as there are missing files that cannot be downloaded. Open the network console in developer tools maybe the errors there can give you an idea what is wrong.
