### ISSUE TITLE
Need to do `npm install` before `make` commands

### ISSUE THREAD

**Issue by inovramadani** [jitsi/jitsi-meet#9496]
I am following instruction on this link https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web, somehow always get can't find module @babel/preset-react when running "make" command and unable to finish.

Then I do `npm install` before `make` command. It executes successfully.
Does the doc page need to be updated?

**Comment by damencho** [comment]
Yes, we had it ... but got dropped at some point, I think by mistake.

https://github.com/jitsi/handbook/commit/cc1f2b50dab514eafe72064db0d8c90cce2b2ef0#diff-18600bdbe8ad04487ad680a5cb87553a21cef6f46b69800258686e3885876d3b
