### ISSUE TITLE
The patch file seens like have some problems.

### ISSUE THREAD

**Issue by eric1023456** [jitsi/jitsi-meet#9498]
When we run the command "npm install", it install all needed modules automatically. But when it goes run patch-package, it display Failed to apply patch for package react-native.
**ERROR** Failed to apply patch for package react-native

  This happened because the patch file patches\react-native+0.61.5-jitsi.2.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\react-native+0.61.5-jitsi.2.patc
    patch -p1 -i h
    npx patch-package react-native
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jitsi-meet@0.0.0 postinstall: `patch-package && jetify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jitsi-meet@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I have no idea on whether some error on the patch file, could you share some your opinion for me? Thx a lot

**Comment by saghul** [comment]
Did you modify any dependency?

**Comment by eric1023456** [comment]
> Did you modify any dependency?
nope, only download the files and run npm install

**Comment by saghul** [comment]
What node and npm versions are you using?

**Comment by eric1023456** [comment]
Hi, the npm versions which I am using is 6.14.10 and node is 14.15.4

**Comment by eric1023456** [comment]
> What node and npm versions are you using?

Hi, the npm versions which I am using is 6.14.10 and node is 14.15.4

**Comment by UserSty** [comment]
Hi, I have the same issue using Windows

node v16.6.1
npm v7.20.3

Have you any updates or fixes for that?

**Comment by saghul** [comment]
We currently only support Node 12 / npm 6. Windows is not a supported environment.

**Comment by wxjv99** [comment]
You can go to <Project Root>\node_modules\patch-package\dist\patch\parse.js and modify it according to the method on [this page](https://github.com/ds300/patch-package/pull/301/commits/75af92ab024c84a880fd5fbbfe6d789498929a60). 
When [ds300/patch-package](https://github.com/ds300/patch-package) publish [this modification](https://github.com/ds300/patch-package/pull/301) and everything will work normally

**Comment by vyomGupta736** [comment]
> You can go to {Project Root}\node_modules\patch-package\dist\patch\parse.js and modify it according to the method on [this page](https://github.com/ds300/patch-package/pull/301/commits/75af92ab024c84a880fd5fbbfe6d789498929a60)(The line may be different).
> When [ds300/patch-package](https://github.com/ds300/patch-package) publish [this modification](https://github.com/ds300/patch-package/pull/301) and everything will work normally

It Worked for me. Thanks a lot:)

**Comment by shane215** [comment]
> 
> 
> You can go to {Project Root}\node_modules\patch-package\dist\patch\parse.js and modify it according to the method on [this page](https://github.com/ds300/patch-package/pull/301/commits/75af92ab024c84a880fd5fbbfe6d789498929a60)(The line may be different).
> When [ds300/patch-package](https://github.com/ds300/patch-package) publish [this modification](https://github.com/ds300/patch-package/pull/301) and everything will work normally

Worked for me too on Windows with:
- node: 12.15.0
- npm: 7.5.4
