### ISSUE TITLE
Centos Install Provedure 

### ISSUE THREAD

**Issue by ghost** [jitsi/jitsi-meet#95]
hello i will like to know or ask or request for a Centos Install Procedure, this app have a great way to be the most powerfull and number 1 for this kind of service.

**Comment by Karen09** [comment]
will also know what happened with idea to make it as debian and centos app?
Greetz

**Comment by andresgmh** [comment]
@Montana357 I was able to execute this amazing app successfully in Centos 7 x64. If you want to know how to install, please contact me andresgmh@gmail.com

**Comment by Karen09** [comment]
@andresgmh please can you push it in gist.githube.com and put here link to repo? or if you have blog share it with us i will also to be able install it in centos 7 and 6.
Greetz
