### ISSUE TITLE
Add a feature where we can store names of all participants in a csv file

### ISSUE THREAD

**Issue by marpit19** [jitsi/jitsi-meet#9503]
I think there should be a button that would make a CSV file and store all the names of the participants so it's easy for attendance and all.

**Comment by manishagarwal99** [comment]
Yes, along with their joining and leaving times. It would be a great addition for students working on any project.

**Comment by gurbuxani** [comment]
Seconded: This is a useful feature for people organizing virtual community meetups. To address privacy concerns, participants should have the option to opt-in to any automated attendance capture.
