### ISSUE TITLE
when I use npm install ,it happen some Error，stay on this:

### ISSUE THREAD

**Issue by 981310384** [jitsi/jitsi-meet#9505]
jitsi-meet#npm install
- extract:hermes-engine: sill extract hermes-engine@0.2.1 extracted to /srv/jitsi-meet/node_modules/.staging
stay on this long time~
how to do ?thanks

**Comment by alim1496** [comment]
facing the same issue on mac

**Comment by saghul** [comment]
What node and npm versions are you using?
