### ISSUE TITLE
[Latest Stable] [BLOCKER] 3 way communication audio not working meet.jit.si

### ISSUE THREAD

**Issue by pravasok** [jitsi/jitsi-meet#9518]
### Description:

3 way communication audio is not working and encountering crashes on leaving the call

### Steps to reproduce:

1. join on a call from 3 devices 
2. speak in one device , audio not received by other devices

### Expected behavior:

audio should be received

### Actual behavior:

audio not received

### Server information:

- Jitsi Meet version: jitsi meet live meet.jit.si
- Operating System:

**Comment by kumaartarun** [comment]
We are also facing same issue .
meet.jit.si works fine with 2 users. 
As soon as 3rd user joins , audio and video stops . 
Jitsi Meet version: jitsi meet live meet.jit.si
Browser :  Chrome Version 91.0.4472.124 (Official Build) (64-bit)
Region: ap-south
[meet.jit.si-1625731791415-Test Logs 3 users.log](https://github.com/jitsi/jitsi-meet/files/6782795/meet.jit.si-1625731791415-Test.Logs.3.users.log)

**Comment by 2357mam** [comment]
+1

we're facing a similar, seeemingly related issue, albeit sporadic: in conferences with more than two participants (i.e. no p2p-conferences), sometimes not every participant receives audio by every other participants.

example: conference with 5 participants, participants 1-4 hear everyone, but #5 doesn't receive the audio stream by one participant (say, #3). note that the statement about the audio stream is an assumption - we don't exactly know what fails.

as of now, we can't reliably reproduce the problem, but it occurs with significant regularity.

running jitsi-meet and jicofo on the latest versions, respectively (2.0.5693).

**Comment by pravasok** [comment]
@saghul  @damencho are you planning to rollback to the older version ?

**Comment by damencho** [comment]
There was an issue on meet.jit.si which is temporary resolved and we are working with the cloud provider for permanent resolution.

**Comment by tseeling** [comment]
> 
> 
> There was an issue on meet.jit.si which is temporary resolved and we are working with the cloud provider for permanent resolution.

Could you please elaborate what the problem was? We're facing the same in our environment. Running on stable 5963 so far but we're willing to upgrade.

**Comment by damencho** [comment]
A problem with the cloud provider, basically no packets from Internet were routed to jvb.
