### ISSUE TITLE
Can add feature for Odysee

### ISSUE THREAD

**Issue by AnantGupta384** [jitsi/jitsi-meet#9524]
Hi team. Great platform. Just wanna give some suggestions regarding streaming on Odysee. You can also have streaming for YouTube as well, but as Odysee is gaining a lot of popularity especially in free & open source community you can also have a streaming key for odysee!

**Comment by damencho** [comment]
You can already use any RTSP link, you just need to paste it in the youtube key dialog

**Comment by damencho** [comment]
Please when you have questions or problems and feature requests discuss them first on the community forum before opening new issues, thank you.

**Comment by AnantGupta384** [comment]
Thanks!

**Comment by skolmer** [comment]
We will provide a PR shortly that allows you to change the Terms & Conditions-, Help-, Privacy Policy-Link and the Regex that is used to validate the input so you can customize it to match the streaming provider you are using.

**Comment by jogood** [comment]
I tried to use an Odysee key as @damencho mentioned, but it doesn't work.

Thank you very much.
