### ISSUE TITLE
Autoplay policy in Chrome prevents audio in conferences?

### ISSUE THREAD

**Issue by tseeling** [jitsi/jitsi-meet#9528]
### Description:

According to Google there was a policy change to expect user interaction before audio is allowed to play.
We suspect this affects some of our users.
Has there been a respective code change?
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

### Steps to reproduce:

1. Open a video conference with 3+ users
2. Try talking (mic works in other applications)
3. Some users can't hear some others (only select connections are affected).
4.  User can be heard by some but not all

### Expected behavior:

Every user should be able to hear every other participant.

### Actual behavior:

Some users can't hear some other users.

### Server information:

- Jitsi Meet version: stable 5963 web, jicofo, jvb
- Operating System: External cloud provider for JVBs, Ubuntu 20 internal data centre

### Client information:

- Browser / app version: latest Chrome/Chromium/Edge Chromium
- Operating System: Windows 10

### Additional information:

We added a prejoin setting to force interaction (enter name, switch on mic) to work around but we're not sure if this is sufficient.

**Comment by damencho** [comment]
> We added a prejoin setting to force interaction (enter name, switch on mic) to work around but we're not sure if this is sufficient.

Yes, this is sufficient as what needs to happen is user interaction and by enabling pre-join screen you force the user to click at least once before opening the page.

**Comment by tanandy** [comment]
Hi @damencho how can we mitigate this without pre-join screen ?

**Comment by saghul** [comment]
Yes and no. IIRC we added a global handler to try and enable it if the user clicks anywhere, but it won't work if the user doesn't. This is alas not in our hands.
