### ISSUE TITLE
Cannot share a WebRtc stream into a meeting

### ISSUE THREAD

**Issue by pengcx123** [jitsi/jitsi-meet#9532]
### Steps to reproduce:
1) Use webrtc-streamer to convert a RTSP stream to WebRtc stream
2) Share the stream to a jitsi meet
### Expected behavior:
1) The user was added into the meet
2) The video was displayed in its window
### Actual behavior:
1) The user was added into the meet, but the video did not displayed in its window
2) The camera and the microphone of the user were disabled

### Server information:

- Jitsi Meet version: Latest
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: Chrome  91.0.4472.124
- Operating System:

### Additional information:

![page3](https://user-images.githubusercontent.com/24951582/125419458-28b1955a-a260-4f4a-aa29-5d0ecc495c85.jpg)
![page4](https://user-images.githubusercontent.com/24951582/125419495-2b0b9e20-135f-4315-bb90-7b3984f4f41a.png)

**Comment by pengcx123** [comment]
![page5](https://user-images.githubusercontent.com/24951582/125419748-6dd3460e-bac1-4d1c-b25f-ea74f1aeb284.png)

The first image is incorrect, please ignore it, sorry

**Comment by gpatel-fr** [comment]
Hello

is this [link](https://community.jitsi.org/t/creating-screen-share-and-video-stream-together/97171/2) not relevant to your question ?

**Comment by pengcx123** [comment]
Thanks for your information, maybe my description was confused, let me try to clarify it.
1) Our purpuse is to share a RTSP video source to a jitsi meeting, all participants are able to see the video.
2) We use this project: https://github.com/mpromonet/webrtc-streamer to try
3) It read the stream from the RTSP source and convert it to RTC stream, and then call the&nbsp;lib-jitsi-meet api to create a muc client to share the RTC stream
4) In the xmpp.html page, it respond to the event&nbsp;TRACK_ADDED, and attach the track
5) It was able to play the video in the xmpp.html page
6) But it was not able to display the video in the desktop of other paerticipants, the muc client window's camera and microphone were disabled&nbsp;


So I would like to ask, is Muc client able to share a video to other participants automatically?


------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Jul 13, 2021 8:21 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [jitsi/jitsi-meet] Cannot share a WebRtc stream into a meeting (#9532)





 
Hello
 
is this link not relevant to your question ?

**Comment by pengcx123** [comment]
I think this is a request, not an issue, so I will close it
