### ISSUE TITLE
Low definition when screen sharing from macOS Safari

### ISSUE THREAD

**Issue by PSiAU** [jitsi/jitsi-meet#9547]
### Description:

When screen sharing from Safari (14.1.1) on macOS (11.4), Low Definition is the maximum quality that all participants can see in the meeting. Text is blurry and unreadable. The LD symbol shows on participants screens indicating low definition.
Switching to Firefox and Chrome is a dramatically different experience and allows the screen to be shared in full high definition. Text is crisp and readable.

### Steps to reproduce:

1. Open Safari
2. Ensure quality is set to high definition
3. Share the screen

### Expected behavior:

Screen sharing in high definition instead of low definition.

### Actual behavior:

Low definition is the maximum quality that can be shared via Safari. Firefox and Chrome are able to screen share in high definition.

### Server information:

- Jitsi Meet version: NA. Running on meet.jit.si
- Operating System: macOS 11.4

### Client information:

- Browser / app version: Safari 14.1.1
- Operating System: macOS 11.4

### Additional information:

NA

**Comment by jallamsetty1** [comment]
This has been fixed in the latest master and has been released to meet.jit.si as well.
