### ISSUE TITLE
the red "REC" indicator disappears about 2s after no mouse/keyboard activity

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#9570]
### Description:
Start recording a meeting. The "REC" indicator appears.

<img width="271" alt="Screen Shot 2021-07-16 at 08 18 30" src="https://user-images.githubusercontent.com/400552/125951285-71c2b4a7-7316-40cd-8794-d6a66ac6a966.png">

Stop moving the mouse/keyboard for two seconds. The "REC" indicator disappears.
<img width="271" alt="Screen Shot 2021-07-16 at 08 18 12" src="https://user-images.githubusercontent.com/400552/125951325-62044640-0f31-471b-a737-4078068281f9.png">

Start moving the mouse/keyboard. The "REC" indicator appears until there are two seconds of inactivity.
<img width="271" alt="Screen Shot 2021-07-16 at 08 18 30" src="https://user-images.githubusercontent.com/400552/125951285-71c2b4a7-7316-40cd-8794-d6a66ac6a966.png">

### Steps to reproduce:

See description above.

### Expected behavior:

The "REC" indicator should always be visible.

### Actual behavior:

See description above.

### Server information:

- Jitsi Meet version: 8x8.vc
- Operating System: 8x8.vc

### Client information:

- Browser / app version: Brave
- Operating System: MacOS, Windows

### Additional information:

If you have the Chat panel open, the "REC" indicator is always visible.
<img width="1552" alt="Screen Shot 2021-07-16 at 08 19 14" src="https://user-images.githubusercontent.com/400552/125951514-e53553fc-cdd8-48c1-a175-104cb38b781a.png">

**Comment by mrose17** [comment]
cc: @stephendonner

**Comment by Freddie-m** [comment]
Does the toolbar also 'disappear'?

**Comment by mrose17** [comment]
@Freddie-m - yes, the toolbar also disappears

**Comment by Freddie-m** [comment]
This is normal (2s is very low though). You can adjust how long you want those elements to be visible by adjusting the values in your interface_config.js:

INITIAL_TOOLBAR_TIMEOUT: 20000,

TOOLBAR_TIMEOUT: 4000,

If you want the toolbar to always be visible, then set this property to "true":

TOOLBAR_ALWAYS_VISIBLE: true,

**Comment by mrose17** [comment]
The work-arounds above apply regardless as to whether the conference is being recorded.

Recording is a dynamic property of the conference, so setting a value in `interface_config.js` (or in our case, since we're a JAAS customer, setting a value in the parameter list when creating the API instance) is too early in the process.

Also, forcing the toolbar at the bottom to be visible is just clutter when all we need is the "REC" indicator to be showing:
<img width="271" alt="125951285-71c2b4a7-7316-40cd-8794-d6a66ac6a966" src="https://user-images.githubusercontent.com/400552/126322863-a341a57a-c7f3-4b72-a440-b01be4922533.png">

I suggest having a separate option (defaulting to `false`) that forces the top-bar on only when recording.

**Comment by Freddie-m** [comment]
I think the driving intention behind the design was to make the interface as 'free' as possible for the actual video elements. Since the UI was redesigned a few versions ago, the video elements now occupy the entire span of the page, which is awesome, because with that, you get larger video tiles. A persistent icon is likely to overlay a video element and that doesn't make for the best visual experience. What you're describing was the way it was implemented several versions back, but that design wastes useful screen real estate.

**Comment by mrose17** [comment]
I am fairly confident that BCP for conferences being recorded is to have a red "REC" indicator showing continuously. The current approach makes Jitsi an outlier in this area... if you want to move the red "REC" icon to another location, independent of the other elements, that's fine.

The primary requirement is when the conferencing is being recorded there there is a persistent red "REC" indicator visible!

**Comment by Freddie-m** [comment]
The primary requirement for who - you? There is a loud audio indicator that announces to everyone in the conference when recording is activated (and to a new participant who joins after recording has been activated). And then you have the visual indicator that's visible for several seconds (configurable) once in a meeting. In addition, you have the option to keep all these elements visible throughout your meeting. You're given SEVERAL configuration options, what more is there to add? 

I just checked another platform to be sure I'm not missing something and sure enough, the indicator is persistent - along with ALL the other elements (toolbar and all). So you want elements to show, but you also don't want them to show. How?

**Comment by mrose17** [comment]
I'll rephrase: the BEST CURRENT PRACTICE for conferencing systems in which the conference is being recorded is to have a persistent red "REC" indicator. If you disagree, then, sadly, we do not have a shared understanding.

I would prefer that the indicator be independent of all the other toolbar chrome, but that's a UI decision for someone else to make...

**Comment by Freddie-m** [comment]
I haven't seen this "BEST CURRENT PRACTICE" as the universal agreement anywhere. What's crucial in any AV conference is that participants are made aware the session is being recorded. Jitsi meets and exceeds this requirement.

The awesome thing about open-source software is that you can customize it however you wish. There is nothing stopping you - or anyone - from making this UI change as you deem fit. But assuming that your preference is a requirement for everyone else is just bizarre. For some of us, useful, icon-free screen real estate is much more valuable.

And again, the option is already there to make the toolbar persistent if you prefer.

**Comment by mrose17** [comment]
Thank you!

**Comment by Freddie-m** [comment]
@robertpin thanks for preserving the option to maintain the status quo.

**Comment by stephendonner** [comment]
Verified `FIXED` using `https://talk.brave.com` with desktop and mobile Brave clients.

Confirmed there is a nice red ever-present`REC` indicator, now.

example | example
---------|---------
<img width="1782" alt="Screen Shot 2021-07-28 at 9 46 11 AM" src="https://user-images.githubusercontent.com/387249/127363652-933b4dc5-01a8-44e9-8107-24e92eb2fba0.png">  | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/127363619-49b1d4c6-3584-44d6-adb1-abb3ec0ae3a9.png)
