### ISSUE TITLE
Jitsi android wait for moderator forever even if moderator has joined the room

### ISSUE THREAD

**Issue by GammaPi** [jitsi/jitsi-meet#9573]
### Description:
For secure domain setup. Android app will wait for authenticated moderator forever even if the moderator has already input his password. Causing the guest won't join the room forever unless manually re-join again.

### Steps to reproduce:

1. Build a server in secure mode (Need moderator password to create rooms)
2. Join room "testRoom" on jitsi android without login
3. Join room "testRoom" on another device and login with moderator password to create room
4. Wait for 1 minute, the android client won't realize the moderator has joined unless you exit and manually join again.
5. Use a webclient on the same phone instead in step 2 and redo step 2-4. The webclient should be able to realize moderator has joined and join the room automatically without user intervention.

### Expected behavior:

Android client should join meeting automatically after moderator input his password and create the room.

### Actual behavior:

Android client hangs in the username/password input interface forever without realizing moderator has joined the room.

### Server information:

- Jitsi Meet version: stable-5963
- Operating System: Deployed on docker

### Client information:

- App version: 21.2.0 build 7762248
- Operating System: Tested on android 9 and 11

**Comment by GammaPi** [comment]
Version 20.4.2 build 5465103 doesn't have this problem fortunately.

**Comment by morgenroth** [comment]
I have the same issue with app version 21.3.0.
My server is also deployed using the latest docker compose.

**Comment by saghul** [comment]
@Calinteodor Please take a look at this when you're back.
