### ISSUE TITLE
Allow moderator to prevent / disable camera/microphone video/audio sharing (and/or: introduce 'viewer' role)

### ISSUE THREAD

**Issue by keunes** [jitsi/jitsi-meet#9575]
**Is your feature request related to a problem you are facing?**
We are looking into using Jitsi for large-scale events, where only a few people will be speaking/presenting. For reasons of capacity, it would be great to be able to disallow participants to enable their video/audio, and just 'view' the meeting (still being able to chat, raise hand, etc - hence external live-streaming wouldn't be a solution).

This has also been requested [on the forum](https://community.jitsi.org/t/disable-camera-for-all-participants-except-moderator/29823), where rather technical solutions were proposed (e.g. using the API).

**Describe the solution you'd like**
Add two new meeting settings:
* `New participants cannot activate their microphone`
* `New participants cannot activate their video`

To ensure consistency with the current situation, these options should be disabled.

In addition, add two options to the contextual menu for users:
* `Allow to unmute` / `Grant microphone permission`
* `Allow to start camera` / `Grant camera permission`

And their counterparts, to remove these options again.

I proposed these here as separate options for audio & video, but they could also be merged into one, to simplify UX/UI.

**Describe alternatives you've considered**
_Existing workaround_: The meeting options already have `Everyone starts muted` and `Everyone starts hidden`. However, this still allows participants to enable audio/video. Since #8630 it is possible to deactivate other users' camera, so this could be used frequently throughout the meeting as regular participants enable their camera.

_Alternative solution_: introduce a new 'viewer' role, which is a role that is similar to Participant, but without the ability to activate their video / audio (camera / microphone). Moderators could then choose in the settings the default role new participants join the meeting with (moderator/participant/viewer), and could upgrade users on the fly (as is already possible with Granting Moderator role).

Related also to #5653.

**Comment by Freddie-m** [comment]
You can relatively easily implement this by using the iFrame API. And no, it's not really that technical. There's a lot that goes into creating user roles that investing effort into it for a use case that already has a solution might be questionable.

**Comment by damencho** [comment]
We had introduced Audio/Video moderation, where the moderator can enable it and users can request from the moderator to unmute Audio or Video and after the moderator allows the operation the unmute can happen. https://github.com/jitsi/jitsi-meet/pull/9195
