### ISSUE TITLE
share computer sound.

### ISSUE THREAD

**Issue by vrgovinda** [jitsi/jitsi-meet#9576]
**Is your feature request related to a problem you are facing?**
When I want to share a video/audio, the participants are unable to hear. Since Jitsi doesn't take computer sound directly. Neither is there a feature to share computer sound. 

**Describe the solution you'd like**
Share computer sound through a button like share screen. 

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by Freddie-m** [comment]
Yes, you can share audio. Click on the 3 ellipsis to the left of the red "end call" button on the toolbar and then click on 'Share Audio" from the pop-up menu.

**Comment by vrgovinda** [comment]
I forgot to add that I'm using Jitsi in Linux Debian Bullseye XFCE.
Regarding the 3 ellipses and "Share Audio" etc., please read the following:

Firstly, it shows up only in Chrome, not in Firefox. 
Secondly, even in Chrome, the share audio option shows up only in "Chromium Tab," not in the other two tabs, namely, "Entire Screen" and "Window."
The link below shows it.
[Jitsi Meet in Chrome - share audio option](https://imgur.com/imotUXS.png)

**Comment by saghul** [comment]
That's unfortunately the best we can do in Linux, it's a platform limitation in Chromium. Firefox doesn't support it yet, nothing we can do about that alas.
