### ISSUE TITLE
Jitsi changes microphone settings and making it not working

### ISSUE THREAD

**Issue by WBurzynski** [jitsi/jitsi-meet#9580]
### Description:

In order to have my microphone working i have to mute one channel in pavucontrol, but jitsi after some time resets muted channel, making microphone not working anymore. This happened both in browser and app

### Steps to reproduce:

1. Join call
2. See microphone settings changed in pavucontrol

### Expected behavior:

Jitsi should respect microphone settings.

### Actual behavior:

Jitsi randomly resets microphone settings.

### Client information:

- Browser / app version: Brave 1.26.77 / Jitsi app 2.8.8
- Operating System: Pop!_OS 21.04

**Comment by Freddie-m** [comment]
When you say the muted channel is reset after some time, do you mean while in an ongoing meeting?

**Comment by WBurzynski** [comment]
ye

**Comment by Freddie-m** [comment]
If I'm not mistaken, devices are handled by the client (browser); Jitsi merely provides an interface for selecting which device to use if there are multiple devices present. So, I'm not sure this issue is due to Jitsi resetting your microphone settings.

**Comment by WBurzynski** [comment]
I'm not sure either, but i noticed same thing in flatpack application as well.

**Comment by Freddie-m** [comment]
> i noticed same thing in flatpack application as well

I think that clarifies it's not a Jitsi issue then.

**Comment by saghul** [comment]
Can you reproduce this with Firefox? The app and Brave are both based in Chromium.

**Comment by WBurzynski** [comment]
actually in firefox i did not have issues so far. So maybe it is problem with chromium

**Comment by saghul** [comment]
This kinda proves it. Not much we can do when there is a problem between Chromium and your system, sorry.
