### ISSUE TITLE
Errors when enabling "token_verification" module in prosody configuration

### ISSUE THREAD

**Issue by raphael10-collab** [jitsi/jitsi-meet#9587]
When enabling in `/etc/prosody/prosody.cfg.lua` the module: `token_verification`:

    plugin_paths = {
      "/usr/lib/prosody/modules",
      "/usr/local/lib/prosody-modules",
      "/usr/share/jitsi-meet/prosody-plugins/",
      "/usr/local/lib/luarocks/rocks"
    }
    
    modules_enabled = {
            -- Other specific functionality
                    "token_verification";
    }

I get these error messages: 

    (base) raphy@pc:~$ sudo systemctl status prosody.service 
    ● prosody.service - Prosody XMPP Server
         Loaded: loaded (/lib/systemd/system/prosody.service; enabled; vendor preset: enabled)
         Active: active (running) since Wed 2021-07-21 10:21:29 CEST; 9s ago
           Docs: https://prosody.im/doc
       Main PID: 5928 (lua5.2)
          Tasks: 1 (limit: 38400)
         Memory: 9.5M
         CGroup: /system.slice/prosody.service
                 └─5928 lua5.2 /usr/bin/prosody
    
    lug 21 10:21:29 pc systemd[1]: Started Prosody XMPP Server.
    lug 21 10:21:29 pc prosody[5928]: modulemanager: Error initializing module 'token_verification' on 'grasp.deals': /usr/lib/prosody/util/startup.lua:145: module 'luajwtjitsi' not found:No LuaRocks module found for luajwtjitsi
                                              no field package.preload['luajwtjitsi']
                                              no file '/usr/lib/prosody/luajwtjitsi.lua'
                                              no file '/usr/local/share/lua/5.2/luajwtjitsi.lua'
                                              no file '/usr/local/share/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/usr/local/lib/lua/5.2/luajwtjitsi.lua'
                                              no file '/usr/local/lib/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/usr/share/lua/5.2/luajwtjitsi.lua'
                                              no file '/usr/share/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/var/lib/prosody/.luarocks/share/lua/5.2/luajwtjitsi.lua'
                                              no file '/var/lib/prosody/.luarocks/share/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/usr/lib/prosody/luajwtjitsi.so'
                                              no file '/usr/local/lib/lua/5.2/luajwtjitsi.so'
                                              no file '/usr/lib/x86_64-linux-gnu/lua/5.2/luajwtjitsi.so'
                                              no file '/usr/lib/lua/5.2/luajwtjitsi.so'
                                              no file '/usr/local/lib/lua/5.2/loadall.so'
                                              no file '/var/lib/prosody/.luarocks/lib/lua/5.2/luajwtjitsi.so'
                                      stack traceback:
                                              [C]: in function '_real_require'
                                              /usr/lib/prosody/util/startup.lua:145: in function 'require'
                                              /usr/share/jitsi-meet/prosody-plugins/token/util.lib.lua:7: in main chunk
                                              (...tail calls...)
                                              ...re/jitsi-meet/prosody-plugins/mod_token_verification.lua:28: in main chunk
                                              [C]: in function 'xpcall'
                                              /usr/lib/prosody/core/modulemanager.lua:183: in function 'do_load_module'
                                              /usr/lib/prosody/core/modulemanager.lua:261: in function 'load'
                                              /usr/lib/prosody/core/modulemanager.lua:83: in function '?'
                                              /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
                                              (...tail calls...)
                                              /usr/lib/prosody/core/hostmanager.lua:108: in function 'activate'
                                              /usr/lib/prosody/core/hostmanager.lua:58: in function '?'
                                              /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
                                              (...tail calls...)
                                              /usr/lib/prosody/util/startup.lua:337: in function 'prepare_to_start'
                                              /usr/lib/prosody/util/startup.lua:558: in function 'f'
                                              /usr/lib/prosody/util/async.lua:139: in function 'func'
                                              /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
    lug 21 10:21:29 pc prosody[5928]: modulemanager: Error initializing module 'token_verification' on 'localhost': /usr/lib/prosody/util/startup.lua:145: module 'luajwtjitsi' not found:No LuaRocks module found for luajwtjitsi
                                              no field package.preload['luajwtjitsi']
                                              no file '/usr/lib/prosody/luajwtjitsi.lua'
                                              no file '/usr/local/share/lua/5.2/luajwtjitsi.lua'
                                              no file '/usr/local/share/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/usr/local/lib/lua/5.2/luajwtjitsi.lua'
                                              no file '/usr/local/lib/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/usr/share/lua/5.2/luajwtjitsi.lua'
                                              no file '/usr/share/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/var/lib/prosody/.luarocks/share/lua/5.2/luajwtjitsi.lua'
                                              no file '/var/lib/prosody/.luarocks/share/lua/5.2/luajwtjitsi/init.lua'
                                              no file '/usr/lib/prosody/luajwtjitsi.so'
                                              no file '/usr/local/lib/lua/5.2/luajwtjitsi.so'
                                              no file '/usr/lib/x86_64-linux-gnu/lua/5.2/luajwtjitsi.so'
                                              no file '/usr/lib/lua/5.2/luajwtjitsi.so'
                                              no file '/usr/local/lib/lua/5.2/loadall.so'
                                              no file '/var/lib/prosody/.luarocks/lib/lua/5.2/luajwtjitsi.so'
                                      stack traceback:
                                              [C]: in function '_real_require'
                                              /usr/lib/prosody/util/startup.lua:145: in function 'require'
                                              /usr/share/jitsi-meet/prosody-plugins/token/util.lib.lua:7: in main chunk
                                              (...tail calls...)
                                              ...re/jitsi-meet/prosody-plugins/mod_token_verification.lua:28: in main chunk
                                              [C]: in function 'xpcall'
                                              /usr/lib/prosody/core/modulemanager.lua:183: in function 'do_load_module'
                                              /usr/lib/prosody/core/modulemanager.lua:261: in function 'load'
                                              /usr/lib/prosody/core/modulemanager.lua:83: in function '?'
                                              /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
                                              (...tail calls...)
                                              /usr/lib/prosody/core/hostmanager.lua:108: in function 'activate'
                                              /usr/lib/prosody/core/hostmanager.lua:58: in function '?'
                                              /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
                                              (...tail calls...)
                                              /usr/lib/prosody/util/startup.lua:337: in function 'prepare_to_start'
                                              /usr/lib/prosody/util/startup.lua:558: in function 'f'
                                              /usr/lib/prosody/util/async.lua:139: in function 'func'
 

OS: Ubuntu 20.04

I asked hints to Prosody people who replied that it's not a prosody issue.

**Comment by damencho** [comment]
You are missing luajwtjitsi, make sure you install it via luarocks (and make sure it is installed for lua 5.2 that you are using if you have multiple lua versions installed).
