### ISSUE TITLE
Add a noise gate like in e.g. TeamSpeak

### ISSUE THREAD

**Issue by Malaber** [jitsi/jitsi-meet#9597]
We currently have the problem, that some people within the Jitsi room have a noisy microphone and don't mute themselves while they are not speaking.

Having a noise gate that only activates the microphone in Jitsi while speaking would reduce the bandwidth used and also the background noise heard by the other participants.
Within the settings you could have a slider to control, when your microphone activates, or you could maybe do that automatically. Teamspeak has had this feature since a long time and while nobody is talking, there is no background noise normally.

You could do that on the client, but then everyone would have to install special software on their computers.

**Comment by Tealk** [comment]
That would be a really great feature

**Comment by Tealk** [comment]
bad bot, go to your corner and leave the issue open

**Comment by saghul** [comment]
We have no plans to work on this, sorry.
