### ISSUE TITLE
invite is missing in default TOOLBAR_BUTTONS constant array

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#9605]
### Description: 
In the config.js, when **toolbarButtons** is undefined, then whole toolbar button are enabled. But in my case Invite option in the prejoin screen was not shown. Going through the code, I just found default (fallback) for toolbarButtons is picked from the constant ```TOOLBAR_BUTTONS``` in ```/jitsi-meet/react/features/base/config/constants.js```. That array does not contain 'invite' value. 

`config.js`

![Screenshot from 2021-07-23 14-18-58](https://user-images.githubusercontent.com/2870845/126758669-ba7ef00f-c21d-4afd-b3a8-4f598a5d7c6a.png)

`constants.js`

![Screenshot from 2021-07-23 14-20-39](https://user-images.githubusercontent.com/2870845/126758844-83919036-64b0-4dc6-80a7-e750c7a48f10.png)

### Expected behavior:
When `toolbarButtons` in the config.js is undefined, then fallback will pick all the values in that array as described in that file.

### Server information:

- Jitsi Meet version: 2.0.5963
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version:
- Operating System:

### Additional information:
Please fix by adding invite value in `/jitsi-meet/react/features/base/config/constants.js`

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/9611
