### ISSUE TITLE
Crash when click security options on android

### ISSUE THREAD

**Issue by alittriutari** [jitsi/jitsi-meet#9609]
When I click on security options menu, the app was crash on android device with this error message
![image](https://user-images.githubusercontent.com/29432760/126924701-585970c3-2b4d-4485-a454-29efc2206749.png)

**Comment by saghul** [comment]
What version of the app are you using? What Android version are you using?

**Comment by Mohamed-Gibreel** [comment]
@saghul I am having the same issue as well, I am using JitsiMeetSDK 3.7.0, Android version 11, Device: Oneplus 7T Pro, Build number: OP7TPro_O2_BETA_5. Do you mind sharing the device details of the android phone you are using ?

**Comment by saghul** [comment]
What have you configured as your `AppTheme` ? It should be something like this: `<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`

**Comment by Mohamed-Gibreel** [comment]
I am not sure how I can check that. Can you tell me which file it is in ? I am using the flutter plugin: https://pub.dev/packages/jitsi_meet.

**Comment by saghul** [comment]
That should be on the native side of the app, in `AndroidManifest.xml`, in the `android:theme=` key.

**Comment by Mohamed-Gibreel** [comment]
For my main activity, it is using:  android:theme="@style/LaunchTheme".

**Comment by saghul** [comment]
Then what do you have in `android/app/src/main/res/values/styles.xml` ? You should find a key for `LaunchTheme` there.

**Comment by Mohamed-Gibreel** [comment]
This is my styles.xml:

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@android:color/white</item>
    </style>
</resources>
`

**Comment by saghul** [comment]
You need to modify that file to make your style inherit from Theme.AppCompat.

**Comment by alittriutari** [comment]
I'm using Android version 8, Device: Redmi 5A
I already set the android theme inherit from `Theme.AppCompat` but it still the same. But i solved this issue by changing the switch to the [Custom Switch](https://www.npmjs.com/package/react-native-switch-with-icons)

**Comment by saghul** [comment]
> I'm using Android version 8, Device: Redmi 5A
> I already set the android theme inherit from `Theme.AppCompat` but it still the same. But i solved this issue by changing the switch to the [Custom Switch](https://www.npmjs.com/package/react-native-switch-with-icons)

That is not really a solution, is it? Other components may fail in the same way.

Can you share your app manifest and style xml files?

**Comment by alittriutari** [comment]
this is my AndroidManifest.xml

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.meeting"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <application
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/launcher_icon">
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="123"/>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/AppTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data 
            android:name="com.facebook.sdk.ApplicationId"
            tools:replace="android:value"
            android:value="@string/facebook_app_id"/>
			
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
    </application>
</manifest>`

and this is my styles.xml

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    
        
        <item name="android:textColor">#1c2025</item>
        <item name="android:navigationBarColor">@color/colorPrimaryDark</item>
        
    </style>
</resources>

`

**Comment by saghul** [comment]
Hum, that looks correct indeed. 🤔

**Comment by alittriutari** [comment]
@kimtrantrong did you build your app using flutter? if yes, you should modify the AndroidManifest file in your jitsi meet plugin at .pub-cache

**Comment by kimtrantrong** [comment]
@alittriutari Yep I cloned plugin jitsi_meet and i can edit it in plugin or should i edit in .pub-cache? If you had a example then i very happy. Thanks

**Comment by alittriutari** [comment]
you should edit in `.pub-cache`
edit the `AndroidManifest.xml` file at /`your-pub-cache-location/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/android/src/main`
and then, configure your AppTheme like this: `<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`

**Comment by kimtrantrong** [comment]
@alittriutari  thank so much you, i fixed it!! :D

**Comment by kimtrantrong** [comment]
@alittriutari If i clone plugin and edit it, i only need edit in plugin and don't need edit in .pub-cache

**Comment by Mohamed-Gibreel** [comment]
@alittriutari Thanks a lot, it fixed the problem :) It's been a while since I've been trying to fix it.
