### ISSUE TITLE
IOS Screen Sharing

### ISSUE THREAD

**Issue by Moh2424** [jitsi/jitsi-meet#9616]
### Description:

The Screen Sharing feature on the IOS isn't working for me. I’ve followed all of the steps mentioned in the documentation, but the problem is I’m not getting any errors at all.

### Steps to reproduce(as per the documentation on https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk):

1. Created Broadcast Upload Extension
2. Set-up and open the socket connection
3. Send Video Frames

### Expected behavior:

Upon clicking 'Start Screen Sharing' and choosing my app as the option, the app will start streaming the user's screen.

### Actual behavior:

The countdown for the sharing begins , and nothing happens after.

### Server information:

Jitsi Meet Public Server

### Client information:

IOS - Tested on iPhone 7( IOS Version 14.6)

**Comment by saghul** [comment]
Do you see any log messages.

**Comment by Moh2424** [comment]
> Do you see any log messages?

Nothing in the log

**Comment by saghul** [comment]
Ping @alexbumbu

**Comment by alexbumbu** [comment]
Did you add the app and the extension to the same group? Make sure the socketFilePath is initialised for this app group identifier.

**Comment by Moh2424** [comment]
> Did you add the app and the extension to the same app group? Make sure the socketFilePath is initialised for this app group identifier.

Yes, the app and extension are linked to the same group. I've initialised the socket file path as per the documentation


`private var socketFilePath: String {
    let sharedContainer = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Constants.appGroupIdentifier)
     
    return sharedContainer?.appendingPathComponent("rtc_SSFD").path ?? ""
}
`

**Comment by alexbumbu** [comment]
Try adding some logs in the SampleHandler class for tracking the broadcast events, then run the extension (not the app) on the device. Let me know if you can see the logs.

**Comment by Faisalkc4u** [comment]
I'm also facing the same problems

**Comment by alexbumbu** [comment]
@Faisalkc4u the last log entry is showing that the app is not added to the app group and filePath is nil in this case. The sample project is for guidance. You need to follow the steps in the documentation to write the extension.

**Comment by Faisalkc4u** [comment]
@alexbumbu  I have removed existing app-group
I created a new app- group

I added assigned the new group for "Jitsi-meet"  and "JitsiMeetBroadcastExtension" 

I updated in code from "JitsiMeetBroadcastExtension" 
```
private enum Constants {
    static let appGroupIdentifier = "my new app group name here"
}

private var socketFilePath: String {
    let sharedContainer = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Constants.appGroupIdentifier)
     
    return sharedContainer?.appendingPathComponent("rtc_SSFD").path ?? ""
}
```

Still I face the same error

**Comment by Faisalkc4u** [comment]
@alexbumbu Thank you
My issue is solved by changing the app group name in info.plist also

File:
ios/app/src/Info.plist
```
	<key>RTCAppGroupIdentifier</key>
	<string> my new app group name here </string>
```

**Comment by ardywijaya** [comment]
Hi @saghul , Why screen sharing button in iOS not working if I put it on the toolbox (outside overflow menu button) ? It's working if it inside overflow menu button. Do you have any suggestions ?
