### ISSUE TITLE
Participant audio failure during the call with working test audio

### ISSUE THREAD

**Issue by zabbal** [jitsi/jitsi-meet#9625]
### Description:

While joining the call on the private instance I immediately see the participants but unable to hear them. When using settings I can see proper list of audio devices on my system. When I press "Test" I correctly hear test audio, however the actual audio from call participants does not go through.

### Steps to reproduce:

1. Join call using Falkon browser
2. Observe absense of the audio
3. Try playing test signal

### Expected behavior:

Sound works.

### Actual behavior:

No sound.

### Server information:

- Jitsi Meet version: latest
- Operating System: GNU/Linux
### Client information:

- Browser / app version: Falkon 3.1.0 (Chrome/87.0.4280.144)
- Operating System: Ubuntu 21.04

### Additional information:

When opening the web inspector there're multiple errors:
`
[features/base/media] Failed to play audio track! retry: 1 ; Error: NotAllowedError: play() can only be initiated by a user gesture.
[features/base/media] Failed to play audio track! retry: 2 ; Error: NotAllowedError: play() can only be initiated by a user gesture.
[features/base/media] Failed to play audio track! retry: 3 ; Error: NotAllowedError: play() can only be initiated by a user gesture.
`
which seem to indicate the reason. Indeed, when I'm explicitly pressing "Test" button the sound is there but there's no button to press which could be used to explicitly enable the regular participant's sound.

**Comment by damencho** [comment]
You can enable preJoin screen and you will not experience the problem. https://github.com/jitsi/jitsi-meet/blob/72d4aa7dd56ad5a99d85371d2129e3f12be5aa58/config.js#L428

Please use the community forum when you have problems or questions before opening new issues, thank you.
