### ISSUE TITLE
Password prompt in the waiting room

### ISSUE THREAD

**Issue by fpesari** [jitsi/jitsi-meet#9637]
**Is your feature request related to a problem you are facing?**
Yes - when I create a room via browser, it is unsecured for a while, until I go through the menus and set the password.

**Describe the solution you'd like**
Currently the waiting room allows you only to pick a name. But why not pick a password as well? So, if the room joined is empty, the password for that room is immediately set. If the room exists already, the password will be used to log into that room. If the password field is empty, everything behaves like it currently does.

This could be a "nudge" to increase the percentage of password-protected rooms, because lazy/absent-minded/tech-unsavy users wouldn't have to do any extra steps to set a password.

**Comment by saghul** [comment]
This has been discussed a number of times already.

Rooms are ephemeral, as such you don't know if a room exists before joining, so attempting to set a password then would create a weird UX.

This is only really a problem with "vanity" room names. If you want to create a room where you are the sole moderator and it's name is virtually unguessable you can use: https://moderated.jitsi.net/
