### ISSUE TITLE
[iOS] Needs a way to set/change default audio output path programmatically, speaker to earpiece.

### ISSUE THREAD

**Issue by Sayeed51** [jitsi/jitsi-meet#9639]
Description:
We are using Jitsi meet iOS SDK in one of our iOS App. But the problem is audio output is always routed to the speaker instead of the earpiece. We can't override this behavior and this audio output path needs to be set programmatically. We are somehow stuck with this problem. And also callkit UI speaker button is not working, it is always open in speaker mode.
We are building an Android app using Jitsi Meet SDK as well. 

Want a solution like the below:

We need an endpoint or api or any option inside 
for iOS llike below
``` 
JitsiMeetConferenceOptions.fromBuilder { builder in
   builder.audioOutput = .speaker / .phone
}
``` 
for Android like below 
```
JitsiMeetConferenceOptions defaultOptions
                    = new JitsiMeetConferenceOptions.Builder()                    
                    .setFeatureFlag("audioOutput", “.speaker / .phone”)
                    .build();
```
is there any way to set audio output to the earpiece?

Any probable solution for this?
Please give us some hints. Thanks in advance

**Comment by saghul** [comment]
That would be a welcome addition, assuming the default behavior is retained. If you feel like working on it, here is where the magic needs to happen: https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/AudioMode.m and thttps://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/AudioMode.m

**Comment by erengms** [comment]
write an action like this, use whenever you want.
[https://github.com/jitsi/jitsi-meet/pull/8862/files](url)

I am using this,
/react/features/mobile/external-api/middleware.js

`eventEmitter.addListener(ExternalAPI.SET_AUDIO_OUTPUT_DEVICE, ({ device }) => {
        dispatch(AudioMode.setAudioDevice(device));
    });`

**Comment by saghul** [comment]
Sure, that will work, but it's also a very low-effort approach and doesn't make it compatible from the SDK perspective.

**Comment by erengms** [comment]
thanks, maybe it will help. Set as default,
 for android sdk
https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java#L350


```java
        boolean bluetoothAvailable = availableDevices.contains(DEVICE_BLUETOOTH);
        boolean headsetAvailable = availableDevices.contains(DEVICE_HEADPHONES);
        boolean earpieceAvailable = availableDevices.contains(DEVICE_EARPIECE);

        // Pick the desired device based on what's available and the mode.
        String audioDevice;
        if (bluetoothAvailable) {
            audioDevice = DEVICE_BLUETOOTH;
        } else if (headsetAvailable) {
            audioDevice = DEVICE_HEADPHONES;
        } else if (mode == AUDIO_CALL && earpieceAvailable){
            audioDevice = DEVICE_EARPIECE;
        } else {
            audioDevice = DEVICE_SPEAKER;
        }
```

for ios I think this part,
 https://github.com/jitsi/jitsi-meet/blob/master/ios/sdk/src/AudioMode.m
```
  - (RTCAudioSessionConfiguration *)configForMode:(int) mode {
    if (mode != kAudioModeDefault && forceEarpiece) {
        return earpieceConfig;
    }

    switch (mode) {
        case kAudioModeAudioCall:
            return earpieceConfig;
        case kAudioModeDefault:
            return defaultConfig;
        case kAudioModeVideoCall:
            return videoCallConfig;
        default:
            return nil;
    }
}  
  ```

**Comment by chrismcclune** [comment]
Was wondering if there was any headway made into adding this functionality. My requirement would be to set the audio route via CallKit also.

**Comment by saghul** [comment]
Nobody seemed to be inclined to do the work, I'm afraid.

**Comment by chrismcclune** [comment]
If I get some time in the near future I will give it a go.

**Comment by andreipro1002** [comment]
Hey, still no updates regarding this feature?

**Comment by panrandahu** [comment]
Why can't this project default earpiece？

**Comment by saghul** [comment]
It's not a matter of ability but of choice. We choose not to use the earpiece by default because our main use case is video calls.

As I've said earlier, I support the change, but nobody has taken the time to actually write the code, and we have no plans to add this ourselves.

**Comment by andreipro1002** [comment]
@panrandahu I managed to modify the framework to use earpiece as default for audio only calls, the sdk used has version 3.10.4 https://github.com/andreipro1002/Jitsi-iOS-SDK-3.10.4

**Comment by panrandahu** [comment]
> 
You are my god，I have spent one month for this function, thanks

**Comment by panrandahu** [comment]
> 
@andreipro1002  Thanks for your kindly help

**Comment by whyaftab** [comment]
> It's not a matter of ability but of choice. We choose not to use the earpiece by default because our main use case is video calls.
> 
> As I've said earlier, I support the change, but nobody has taken the time to actually write the code, and we have no plans to add this ourselves.

is this still not implemneted?

**Comment by adamalexander** [comment]
@andreipro1002 thanks for your help! Were you able to do anything for android?

**Comment by binokbenny77** [comment]
> [@panrandahu](https://github.com/panrandahu) I managed to modify the framework to use earpiece as default for audio only calls, the sdk used has version 3.10.4 https://github.com/andreipro1002/Jitsi-iOS-SDK-3.10.4

i tried to use this one i am getting as video missed in the video calling scenario. please provide some update. but rest working very nicely
