### ISSUE TITLE
[features/base/tracks] Failed to create local tracks Array(2) DOMException: Permission denied

### ISSUE THREAD

**Issue by Ferm9404** [jitsi/jitsi-meet#9642]
### Description:

Permissions are being denied without prompt with HTTPS

### Steps to reproduce:

1.) Using HTTPS in order to make the request.
2.) Pop up window start Jitsi external API.
3.) Camera and Microphone are being blocked without show a permissions prompt.

### Expected behavior:
1) To show the permission prompt to allow use camera and microphone
2) Show the camera and Microphone features

### Actual behavior:

Permissions are being denied automatically without showing a prompt even though its using HTTPS.
![image](https://user-images.githubusercontent.com/80997966/127921630-438db457-6e07-4a93-a420-0cc0b0ae3456.png)

LOGS: 

![image](https://user-images.githubusercontent.com/80997966/127921759-54d8e1e6-4b74-42ab-98fd-0812e876d956.png)

Current Information about window: 

![image](https://user-images.githubusercontent.com/80997966/127922168-d43b5325-fbb0-4b2b-961c-2fcd82e96b8e.png)

### Server information:
https://meet.jit.si/external_api.js

### Client information:
Using External API with `Iframe`

```
const DOMAIN = 'meet.jit.si';
const OPTIONS = {
      roomName: room,
      width: '100%',
      height: '100%',
      configOverwrite: { prejoinPageEnabled: false },
      parentNode: windowWithAPI.document.querySelector('#jitsi-iframe'),
      userInfo: {
        displayName: user
      }
    };
    
    api = new windowWithAPI.JitsiMeetExternalAPI(DOMAIN, OPTIONS);
```

**Comment by saghul** [comment]
You have blocked the devices at the browser level. Click that icon on the top right on the location bar and you should be able to use them.

**Comment by Ferm9404** [comment]
@saghul  it doesn't let me when I open and click on **ask for permissions** on the icon you are saying it doesn't show the prompt it gets blocked again.

**Comment by Ferm9404** [comment]
So Im unable to enable permissions for camera and microphone even if I click on the icon you are mentioning @saghul

**Comment by saghul** [comment]
What browser is that? Can you try opening a tab in incognito mode?

**Comment by Ferm9404** [comment]
Sure thing It's Google  Chrome Version 92.0.4515.107 (Official Build) (64-bit)I opened in Incognito and the same thing. 
![image](https://user-images.githubusercontent.com/80997966/127966809-408218f1-2669-47d8-b047-30564d49c777.png)

**Comment by saghul** [comment]
Can you reproduce this behavior on meet.jit.si? Or does it only happen on your instance?

Why does that screenshot show "about:blank"?

How are you launching that embedded meeting frame?

**Comment by Ferm9404** [comment]
1. @saghul : the script I was embeding to is : https://meet.jit.si/external_api.js.
2. about:blank is `ReactPortal ` https://www.npmjs.com/package/rc-new-window
3. when the API is loaded on `window.JitsiMeetExternalAPI` I create an instance with the following options as above:

```

const DOMAIN = 'meet.jit.si';
const OPTIONS = {
      roomName: room,
      width: '100%',
      height: '100%',
      configOverwrite: { prejoinPageEnabled: false },
      parentNode: windowWithAPI.document.querySelector('#jitsi-iframe'),
      userInfo: {
        displayName: user
      }
    };
    
    api = new windowWithAPI.JitsiMeetExternalAPI(DOMAIN, OPTIONS);
```

**Comment by saghul** [comment]
You haven't answered 1) really. If you use your browser to directly access https://meet.jit.si do you get the problem?

Is the website loading the iframe API in a portal using https itself?

**Comment by Ferm9404** [comment]
@saghul  thanks for the response, yes the App is deployed on Netlify using HTTPS, and also I can open https://meet.jit.si/ directly on my browser

**Comment by Ferm9404** [comment]
If you also check this https://user-images.githubusercontent.com/80997966/127922168-d43b5325-fbb0-4b2b-961c-2fcd82e96b8e.png it belongs to the iframe hosting the `div` of the `Iframe` you can check its **HTTPS**

**Comment by saghul** [comment]
It's really weird. Can you email me some credentials so I can test it out? GH username @ jitsi dot org.

**Comment by Ferm9404** [comment]
@saghul  what email can I send you the credentials?

**Comment by saghul** [comment]
saghul (at) Jitsi (dot) org

**Comment by Ferm9404** [comment]
@saghul  Mail sent.

**Comment by saghul** [comment]
Tested and replied to the email. Cannot reproduce. I suspect the browser is a bit confused because that Window is opened without any origin and then stuff is injected into it. At any rate, nothing we can do on our end.
