### ISSUE TITLE
Add android:exported attribute to ConnectionService (Android 12)

### ISSUE THREAD

**Issue by mehul4795** [jitsi/jitsi-meet#9646]
### Description:

The Android project doesn't build when the app is targeting Android 12 (compileSdkVersion=31, targetSdkVersion=31) and is using the Jitsi SDK. 

The logcat shows the below error.

`Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined.`

### Steps to reproduce:

1. Change the **targetSdkVersion** and **compileSdkVersion** to **31**.
2. Rebuild the project and run the app.

### Expected behavior:

The project should build successfully without showing the error.

### Actual behavior:

The build process fails with error `Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined.`

### Solution

On checking the merged manifest file, I found that `org.jitsi.meet.sdk.ConnectionService` is the reason behind the error. Just adding the **android:exported** to the service solves the error.

**Comment by saghul** [comment]
Sounds about right, care to send a PR?

**Comment by mehul4795** [comment]
Just checked the [manifest file](https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/AndroidManifest.xml) in the SDK and it appears that the `android:exported` attribute is already added to the `ConnectionService` class. I think the latest code is not included in the SDK version 3.7.0.

**Comment by saghul** [comment]
Indeed, it was fixed in https://github.com/jitsi/jitsi-meet/commit/8f81a75a619610d449e280b309875677c4d74367 but it's unreleased.
