### ISSUE TITLE
Don't ban medium and high resolution cameras

### ISSUE THREAD

**Issue by vermeeren** [jitsi/jitsi-meet#9648]
I am using a 1920x1080 30fps camera, in the past I have also used 3840x2160 and 4096x2160 virtual cameras with fantastic resutls. It seems that a change was made within the past few weeks constraining camera resolution severely, Firefox ESR 78 on Debian bullseye.

```
2021-08-03T16:11:54.028Z [modules/RTC/RTCUtils.js] <_getUserMedia/</<>:  Failed to get access to local media. OverconstrainedError: Constraints could be not satisfied. {"video":{"height":{"ideal":720,"max":720,"min":180},"width":{"ideal":1280,"max":1280,"min":320},"facingMode":"user"},"audio":false}
```

Is there some reason why medium and high resolution video sources have been banned? The meetings me and friends have done with it worked absolutely great with very crisp video quality.

I believe it is the same as #1559, except for medium and high resolution cameras, hence the title.

**Comment by jallamsetty1** [comment]
This sounds like a Firefox bug. If the camera supports higher resolution, the browser shouldn't be throwing an overconstrained error when a lower resolution is requested.

**Comment by vermeeren** [comment]
Some additional info: camera in question does not natively support lower resolution, the only video resolution is 1920x1080. I suppose Firefox does not downscale it internally.

Regardless of that however, supporting high resolution on Jitsi meet is very useful for things such as pair programming on 4k displays. I would love to see support return.

**Comment by saghul** [comment]
Can you try appending "#config.resolution=1080" without quotes, to the end of the URL before joining?

**Comment by vermeeren** [comment]
@saghul It seems that the Jitsi configuration was modified between the time of report and time of testing your suggestion, as both medium and high resolution cameras are working nicely again without the `#config.resolution=...` URL suffix.

Closing this for now as it seems fixed, if it occurs again I'll definitely test the URL suffix!

Thanks!

**Comment by saghul** [comment]
Good to hear!

**Comment by L-as** [comment]
Using Firefox 91 I have this problem too. Appending `#config.resolution=1080` to the URL does fix it for me.
