### ISSUE TITLE
[features/base/tracks] Failed to create local tracks Array(2) DOMException: Permission denied 

### ISSUE THREAD

**Issue by Ferm9404** [jitsi/jitsi-meet#9649]
### Description:
Please dont give me quick solutions as this one as I already tried them.... https://github.com/jitsi/jitsi-meet/issues/9642
got closed....
Permissions are being denied without prompt with HTTPS, AND NO IT DOESNT WORKS IF I CLICK ON THE RIGHT CLICK UPPERMOST PART OF THE WINDOW, since when I enable in the uppermost button, it still gets denied automatically.

### Steps to reproduce:

1.) Using HTTPS in order to make the request.
2.) Pop up window start Jitsi external API.
3.) Camera and Microphone are being blocked without show a permissions prompt.

### Expected behavior:
1) To show the permission prompt to allow use camera and microphone
2) Show the camera and Microphone features

### Actual behavior:

Permissions are being denied automatically without showing a prompt even though its using HTTPS.
![image](https://user-images.githubusercontent.com/80997966/127921630-438db457-6e07-4a93-a420-0cc0b0ae3456.png)

LOGS: 

![image](https://user-images.githubusercontent.com/80997966/127921759-54d8e1e6-4b74-42ab-98fd-0812e876d956.png)

Current Information about window: 

![image](https://user-images.githubusercontent.com/80997966/127922168-d43b5325-fbb0-4b2b-961c-2fcd82e96b8e.png)

### Server information:
https://meet.jit.si/external_api.js

### Client information:
Using External API with `Iframe`

```
const DOMAIN = 'meet.jit.si';
const OPTIONS = {
      roomName: room,
      width: '100%',
      height: '100%',
      configOverwrite: { prejoinPageEnabled: false },
      parentNode: windowWithAPI.document.querySelector('#jitsi-iframe'),
      userInfo: {
        displayName: user
      }
    };
    
    api = new windowWithAPI.JitsiMeetExternalAPI(DOMAIN, OPTIONS);
```

**Comment by saghul** [comment]
Do not open duplicate issues.
