### ISSUE TITLE
Allow to create prosody user via config.

### ISSUE THREAD

**Issue by Tinkesh-Kumar** [jitsi/jitsi-meet#9651]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Since prosody user is created before start of prosody, Like we are creating other prosody user. It should take config as an input and allow users to create prosody user.

**Describe alternatives you've considered**
I am using core.usermanager plugin as a muc plugins, but it fails some time with error.

**Comment by saghul** [comment]
Jitsi Meet is just the front end. Where would this config go?
