### ISSUE TITLE
Update the text for the experimental e2ee option

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#9659]
### Description:

Explanatory text for e2ee is slightly out-of-date and should have some links.

### Steps to reproduce:

1. Create a meeting and join it.
2. Click on the "More actions" ellipsis and then "Security options" and you'll get this:
![Screen Shot 2021-08-04 at 15 49 21](https://user-images.githubusercontent.com/400552/128245589-0a23fb84-55d7-4f3a-9bf9-cd1511c2c77a.png)
3. Click on the "more" to get the full text.

### Actual behavior:

Do that and you'll get this:
![Screen Shot 2021-08-04 at 15 47 42](https://user-images.githubusercontent.com/400552/128245700-72eef857-57ae-487d-9d90-b201886bc5eb.png)

The text says that "recording" is disabled. when it isn't.

The "WARNING" about not all participants in this meeting having End-to-End encryption is also wrong (I'm using the Brave Browser, which does support insertable streams.)
 
### Expected behavior:

1. If possible, make the "more" more visible (it's easy to slide past it.
2. "Remove "recording," from the text since thats 
3. If possible, add a link to a page at the Jitsi site that explains what insertable streams are, and how to tell if your browser supports them.
4. Update the algorithm used to determine whether the "WARNING" tetx is displayed.

### Server information:

- Jitsi Meet version: N/A
- Operating System: Version 1.29.46 Chromium: 92.0.4515.115 (Official Build) nightly (arm64)

### Client information:

- Browser / app version: N/A
- Operating System: N/A

### Additional information:

None.

**Comment by saghul** [comment]
I started fixing this in https://github.com/jitsi/jitsi-meet/pull/9748 -- I got 1, 2 and 4 done. I need to double check on 3.

**Comment by mrose17** [comment]
> I started fixing this in #9748 -- I got 1, 2 and 4 done. I need to double check on 3.

Excellent, thanks!

**Comment by saghul** [comment]
Landed #9748. Let's handle item 3 separately since we may want to point users to a site with more information.
