### ISSUE TITLE
In chat, brave://wallet gets converted into brave (:frowning face) /wallet

### ISSUE THREAD

**Issue by stephendonner** [jitsi/jitsi-meet#9661]
### Description:

In chat, `brave://wallet` gets converted into 
<img width="125" alt="Screen Shot 2021-08-04 at 2 36 13 PM" src="https://user-images.githubusercontent.com/387249/128258528-25972348-b044-44e4-a1b8-55079a0b27e1.png">

### Steps to reproduce:

1. load `https://meet.jit.si/`
2. click on `Start meeting`
3. accept permission requests (or not) for audio/video
4. enter username
5. click `Join meeting`
6. on the bottom toolbar, click on `Open chat`
7. type `brave://wallet` and click the paper airplane icon/hit `return`/`Enter`

### Expected behavior:

Should show `brave://wallet` as-is

### Actual behavior:

<img width="1388" alt="Screen Shot 2021-08-04 at 2 36 03 PM" src="https://user-images.githubusercontent.com/387249/128258854-00a7b395-7e2d-4279-b47e-9e35a7c96fa1.png">

### Client information:

- Browser / app version: Brave release `1.27.109`
- Operating System: macOS 11.5.1

**Comment by saghul** [comment]
Proposed fix: https://github.com/jitsi/jitsi-meet/pull/9803
