### ISSUE TITLE
[Android] ParticipantsService expects participant info as Json but gets a stringified hashmap

### ISSUE THREAD

**Issue by ernest3rd** [jitsi/jitsi-meet#9676]
The conference participant info retrieval introduced in commit [d2568b874bf70c3afb27e540863ab666f42a5eac](https://github.com/jitsi/jitsi-meet/commit/d2568b874bf70c3afb27e540863ab666f42a5eac) is expecting to receive data in json format but instead the org.jitsi.meet.sdk.BroadcastEvent [stringifies the incoming HashMap](https://github.com/jitsi/jitsi-meet/blob/834ee22bc3dd26b43e88e97dadfbff00104f2d08/android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java#L47)

**Comment by saghul** [comment]
@tmoldovan8x8 PTAL when you're back.
