### ISSUE TITLE
Fullscreen button on mobile browsers

### ISSUE THREAD

**Issue by maurojs10** [jitsi/jitsi-meet#9688]
Please, can we have an option to restore the fullscreen button on **mobile browsers**?

The commit 62c78950cd5e97366f81d435574eb5f6b35d21e0 removed that button ([line 574 of Toolbox.js](https://github.com/jitsi/jitsi-meet/blob/62c78950cd5e97366f81d435574eb5f6b35d21e0/react/features/toolbox/components/web/Toolbox.js#L574)) and commit c2ad06c5e63be8a5475e3dc933a527b3a34edb41 kept it removed ([line 975 of Toolbox.js](https://github.com/jitsi/jitsi-meet/blob/c2ad06c5e63be8a5475e3dc933a527b3a34edb41/react/features/toolbox/components/web/Toolbox.js#L975)).

**Comment by saghul** [comment]
IIRC that functionality never worked on mobile browsers.

**Comment by maurojs10** [comment]
It works pretty well, actually.

I recently upgraded Jitsi Meet from version 4857 to version 5963 and my customers start complaining this functionality was removed without a reason.

**Comment by saghul** [comment]
@quitrk Hey Tudor do you remember if the change to the full-screen button was intentional?

**Comment by quitrk** [comment]
this was the old code that got refactored

from https://github.com/jitsi/jitsi-meet/commit/62c78950cd5e97366f81d435574eb5f6b35d21e0#diff-47533bbf1025cf2afb92c7ce88e56c9da76743dcb08ec6b7ea9b1ca6c265aad7L1034

`this.props._shouldShowButton('fullscreen')
                && !_isMobile
                && <OverflowMenuItem
                    accessibilityLabel = { t('toolbar.accessibilityLabel.fullScreen') }
                    icon = { _fullScreen ? IconExitFullScreen : IconFullScreen }
                    key = 'fullscreen'
                    onClick = { this._onToolbarToggleFullScreen }
                    text = { _fullScreen ? t('toolbar.exitFullScreen') : `

The new one kept the `isMobile` check in place so I'm not sure at which point it was visible

**Comment by saghul** [comment]
@quitrk could you please give it a test and if it works ok, remove the check?
