### ISSUE TITLE
resetBounds calls exitPictureInPicture.

### ISSUE THREAD

**Issue by durduman** [jitsi/jitsi-meet#9690]
About **PiPViewCoordinator.swift**

When using `resetBounds`, this method will call `exitPictureInPicture` which ends up by calling the delegate's method of `exitPictureInPicture()`.
This is inconvenient and seems like an issue (eg. when trying to preserve a minimised/PIP UI).

**Comment by saghul** [comment]
Yeah, not sure why we did that. I think it makes sense to remove it. Are you up for a PR?

**Comment by saghul** [comment]
This was fixed in https://github.com/jitsi/jitsi-meet/pull/9692
