### ISSUE TITLE
Embed meeting config still picked from interfaceConfig.SHARING_FEATURES

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#9698]
### Description:
**Embed meeting** menu item in more options menu (ToolBox button) is configured by adding/removing ```embedmeeting``` string in ```toolbarButtons``` array in config.js, but the same config not applied for Embed meeting option in **Invite more people** dialog which is available in Participant pane. In that dialog, value takes from Interface_config.

Does jitsi has a plan to remove the checking from interfaceConfig.SHARING_FEATURES In the near future ?

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
> Does jitsi has a plan to remove the checking from interfaceConfig.SHARING_FEATURES In the near future ?

We have plans to merge all config in config.js, yes. It's a slow process though, and pull requests are welcome!

**Comment by skolmer** [comment]
> Does jitsi has a plan to remove the checking from interfaceConfig.SHARING_FEATURES In the near future ?

Just to clarify: these two settings have a different purpose.
You can use `SHARING_FEATURES` to disable/enable individual sharing features in the add-people dialog while removing `embedmeeting` from `toolbarButtons` only removes the embed-meeting button from the toolbox menu. 
`SHARING_FEATURES` is optional so no need to set it if you are fine with the default sharing options that are provided in the add-people dialog.
That means if you want to remove the embedding option completely you have to remove `embed` from `SHARING_FEATURES` and remove the button from the toolbar by removing `embedmeeting` from `toolbarButtons`.

**Comment by saghul** [comment]
That is correct.

**Comment by ashiqhassan95** [comment]
Thank you.
@skolmer 
@saghul
