### ISSUE TITLE
When screen share is ON in participant list video icon is also turning ON

### ISSUE THREAD

**Issue by AjayShivanagol** [jitsi/jitsi-meet#9705]
I hope this is happening because we are making use of Singletrack for screen share and Video.

![Screenshot from 2021-08-10 21-14-39](https://user-images.githubusercontent.com/29257275/129041029-b07fec0a-4b1a-42f7-a289-aa3e636f5ff7.png)

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening new issues, thank you.

Yes, when you are screen sharing you are sending video so you are not video muted.
