### ISSUE TITLE
Better moderation capabilities: asymmetric participants (“speakers” vs “listeners”)

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [jitsi/jitsi-meet#9715]
The Document Foundation is interested in getting this feature implemented, if and only if it is accepted into upstream Jitsi. We will proceed with contracting, if this gets the green light from core devs. Implementation details could then be discussed in this issue. Ping @saghul @damencho

### Scenario

At our virtual LibreOffice conference 2020 we had speakers and regular attendees, and visits from unwelcome people. Another way to deal with this kind of situation is to just not allow everyone to unmute or play video at will, but only allow that for preregistered users while others would have to raise their hand and wait for a moderator to unmute/grant video/screenshare.

### Proposal

Jitsi already has some limited amount of speaker-centric features (everyone follows me, everyone muted except single person), but those features do not extend to a conference, and assume good-will in participants (and small groups). So even when not tied to log-ins/authenticated users: if there was a way to only grant self-unmute/video/screenshare to a subset of attendees this would be helpful.

**Comment by saghul** [comment]
Hey there! We have some "advanced moderation" features coming very soon. In this mode, if you create a meeting where a single user (or group of users) is the moderator, they can mute everyone else and prevent them from unmuting.  They can then ask users to unmute themselves in order to participate.

Do you think this covers your use-case?

**Comment by ilmari-lauhakangas** [comment]
Oh, that is nice to hear :) I discussed with the team and indeed what your describe covers the idea. Thanks for the quick response!
