### ISSUE TITLE
Youtube video is unavailable

### ISSUE THREAD

**Issue by alittriutari** [jitsi/jitsi-meet#9719]
I have a problem when I trying to share a youtube video
![photo_2021-08-14_15-46-34](https://user-images.githubusercontent.com/29432760/129439295-105754a0-da7b-4d6a-90b5-30bc1a4f9d01.jpg)

**Comment by saghul** [comment]
What SDK or app version are you using? This was fixed a while ago and is part of SDK 3.8.0 or the latest app beta.

**Comment by alittriutari** [comment]
I'm using SDK 3.3.0, which part did you change? I want to build my own sdk

**Comment by saghul** [comment]
Please update to SDK 3.8.0, we have fixed the bug in that version.

The fix was an update to the React Native YouTube Player library.

**Comment by alittriutari** [comment]
but on SDK 3.8.0, the camera is not showing well like SDK 3.3.0, that's why I keep using SDK 3.3.0
![Capture](https://user-images.githubusercontent.com/29432760/129997263-e08d6fdc-eeac-423b-b3b4-bb53cba54971.JPG)
