### ISSUE TITLE
No language support for Chinese (China) and Chinese (Taiwan)

### ISSUE THREAD

**Issue by liushuyu** [jitsi/jitsi-meet#972]
Hi, there. I didn't see Chinese (China) and Chinese (Taiwan) language in your project. It seems like your translation system Pootle, also have no relevant language project. But I've see Chinese (China) and Chinese (Taiwan) languages in Jitsi main project. 

So can you add Chinese (China) and Chinese (Taiwan) languages to Jitsi-meet project in Pootle? Thanks

**Comment by sepehr1101** [comment]
The same problem for Persian

**Comment by amerifar** [comment]
How can I add another language?
