### ISSUE TITLE
Constant disconnections on Windows Chrome browser

### ISSUE THREAD

**Issue by dylanhamada** [jitsi/jitsi-meet#9720]
### Description:

After connecting to a room hosted on meet.jit.si, I am disconnected every 30 seconds or so. I have confirmed that this is happening to multiple users also using Chrome on Windows.

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System: 

### Client information:

- Browser / app version: Chrome version 92.0.4515.131 
- Operating System: Windows 10 Build 19043.1165

**Comment by dogsleg** [comment]
I've tried Chromium (90.0.4430.212 from the Debian archive) and Google Chrome (92.0.4515.131 from Google itself) on Debian GNU/Linux testing+unstable. For both browsers I experience disconnections at somewhat short random time (disconnection in every 3-10 minutes).

**Comment by saghul** [comment]
Can you please provide browser console logs?

**Comment by damencho** [comment]
Please when you have questions or problem, use the community forum before opening new issues. Thank you.
More information https://community.jitsi.org/t/frequent-disconnects-on-jitsi-meet/104016/12
