### ISSUE TITLE
(Android) flashlight (and similar) support

### ISSUE THREAD

**Issue by deliciouslytyped** [jitsi/jitsi-meet#9721]
**Please describe the problem you are trying to solve.**

From a user perspective, Android appears to have a very limited and braindead camera interface: it appears that only a single application may access the camera, and tied to it, the device flashlight, at any given time. This means that it's literally impossible for the user to enable their flashlight for any purpose, if the active (communications) application does not support it.

**Please describe the desired behavior.**

It would be useful, and nice, to allow usage of Jitsi in dark places, outdoors contexts, etc. This requires some manner of exposing the camera functionality given/crippled by Android. To allow incremental development, it would be nice to initially start with flashlight support, both because it is useful, and because there are no decent workarounds to the absence of the feature. (other than going and getting a separate flashlight, and why would you do that when you have a perfectly good one already?)

It would also be a nice differentiator for Jitsi, if most other applications don't support this.

**i.e. I would like there to be a button that lets me turn the flashlight on and off.**

**Describe alternatives you've considered**
I see no real viable alternatives.
- get a separate flashlight
- uninstall Jitsi
- uninstall Android

History
----------
https://github.com/jitsi/jitsi-meet/pull/4561 is a pull request from 2019, merging flashlight support for iOS into Jitsi.
The PR was closed because @saghul deemed it out of scope.
> @patidars I see. While I do see some (very narrow) use cases, FaceTime or the builtin camera don't allow video recording with the flashlight on.
> 
> I'm sorry, but this is not something we are willing to integrate into the app.

In a more recent issue (https://github.com/jitsi/jitsi-meet/issues/8851 , from March 2021) the @saghul once again closed an issue asking about the API necessary to do this, and clarified that due to the single camera-object-API, this needs to be done by patching the upstream react-native-webrtc library. They point to https://github.com/cmpayc/react-native-webrtc/commit/79d2e998ee72e7bac7eed4c636e141c4a4b7d442 as being a fork containing work on this:
> It's not possible to get the currently opened camera object. That is internally managed by WebRTC. You'd have to patch WebRTC to be able to extract it from Camera2Session, then add some API for that in react-native-webrtc, which is the library we use.
> 
> Someone had worked on something similar in the past: [cmpayc/react-native-webrtc@79d2e99](https://github.com/cmpayc/react-native-webrtc/commit/79d2e998ee72e7bac7eed4c636e141c4a4b7d442) Good luck!

Path forward
-----------------
Searching for "react native webrtc flashlight" also yields this issue: https://github.com/react-native-webrtc/react-native-webrtc/issues/39 . Note @cmpayc (the author of the above mentioned react-native-webrtc fork) also participates here.

In this issue @zxcpoiu refers to some of the functionality being written in https://github.com/zxcpoiu/react-native-incall-manager/ , which is now at: https://github.com/react-native-webrtc/react-native-incall-manager . You may note this is also under the react-native-webrtc umbrella.

The readme lists the implemented functionality. Notably, what I would like: Android flashlight support, still needs to be implemented. However the iOS support @patidars may want, appears to be included.

So it appears to me, that if the code quality is up to par, the road to getting such functionality in, would be integrating the new react native webrtc module, etc.

Does the Jitsi project see any reasonable path forward?

**Comment by saghul** [comment]
I still have reservations about this. To many it may just sound as "one more button in the UI" but we are already struggling with the amount of options we have as is.

**Comment by deliciouslytyped** [comment]
The OS forces this complexity on you, I understand the reluctance.

**Comment by saghul** [comment]
Jitsi Meet is a video conferencing application. As such, the primary camera is the front facing one, that's why it's the default.

Yes you can use Jitsi or any other application for other purposes, but that doesn't mean we need to support every use case.

The flashlight works primarily on the back facing camera, so I see this as a too niche use case for us to support.

Things are not as simple as adding one more button, otherwise we'd and up with a UI that looks like that car Homer designed in The Simpsons.

Honestly, I don't see this happening at all.

**Comment by cmpayc** [comment]
@deliciouslytyped I agree with @saghul. Flashlight mode is very narrowly applicable and attached to to Android camera. Therefore, to activate it, you need to change the WebRTC library (which goes beyond Jitsi Meet).

I checked out my flashlight solution https://github.com/react-native-webrtc/react-native-webrtc/issues/39#issuecomment-341016563 for the latest version of react-native-webrtc (M92). And it still works (with very minor changes). But the flashlight will only work when the back camera is active. So you can create your own [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) fork and customize it for your needs.

Also, with the camera turned off (when the WebRTC library doesn't take the camera session), you can use another libraries to access the flashlight (for example, [react-native-torch](https://github.com/ludo/react-native-torch))

**Comment by deliciouslytyped** [comment]
@saghul I imagine jitsi can't or wont support plugins 
- on android? 
- on iOS?

**Comment by saghul** [comment]
Can't. Applications are signed and you can't just get random code to add new functionality at runtime.

**Comment by keremoge** [comment]
> @deliciouslytyped I agree with @saghul. Flashlight mode is very narrowly applicable and attached to to Android camera. Therefore, to activate it, you need to change the WebRTC library (which goes beyond Jitsi Meet).
> 
> I checked out my flashlight solution [react-native-webrtc/react-native-webrtc#39 (comment)](https://github.com/react-native-webrtc/react-native-webrtc/issues/39#issuecomment-341016563) for the latest version of react-native-webrtc (M92). And it still works (with very minor changes). But the flashlight will only work when the back camera is active. So you can create your own [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) fork and customize it for your needs.
> 
> Also, with the camera turned off (when the WebRTC library doesn't take the camera session), you can use another libraries to access the flashlight (for example, [react-native-torch](https://github.com/ludo/react-native-torch))

Hi @cmpayc, Thanks for your instructions. As you state there might be minor changes. Can you make a new doc or instructions for implementing flash/torch support :)
