### ISSUE TITLE
sharing Youtube Videos link don't work properly

### ISSUE THREAD

**Issue by atinagrawal** [jitsi/jitsi-meet#9729]
### Steps to reproduce:

1. Start a meeting on Android client
2. From options, choose "Share youtube video"
3. Enter a valid youtube video link
4. The video loads but when played, it stutters (irrespective of video quality).

### Expected behavior:

The video should have played smoothly.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Android SDK: 3.8.0
- Operating System: Android

**Comment by saghul** [comment]
If you try the same video in the system browser, do you get similar results?

**Comment by atinagrawal** [comment]
The same video works fine on system browser.I've verified the issue with multiple videos on YouTube. 
Sent from Yahoo Mail on Android 
 
  On Tue, 17 Aug 2021 at 4:01 pm, Saúl Ibarra ***@***.***> wrote:   


If you try the same video in the system browser, do you get similar results?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
