### ISSUE TITLE
Native apps breaking from master

### ISSUE THREAD

**Issue by prasadkadiyala** [jitsi/jitsi-meet#9730]
Native Apps are breaking when using the master branch.

### Description:

After the implementation of polls, native apps are not working

### Steps to reproduce:

1. User master brach
2. Build Android/IOS app
3. Run the app

### Expected behavior:

App should run properly

### Actual behavior:

App throws error

**Comment by saghul** [comment]
Please see https://github.com/jitsi/jitsi-meet/pull/9722
