### ISSUE TITLE
Multiple instances issue while trying to join new meeting from JitsiMeetSDK

### ISSUE THREAD

**Issue by VinoSimon** [jitsi/jitsi-meet#9737]
### Description:

We have generated android & ios sdk from this  https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_5870
when we try to join a new meeting, app is not allowing to join into new meeting, its joining with existing meeting with new instance.

### Steps to reproduce:

1. create sample screen to join meeting
2. call JitsiMeetActivity.launch() to join new meeting
3. enter picture in picture mode
4. sample screen will be visibile to user
5. try to give new room name & press join meeting(JitsiMeetActivity.launch())
6. now if you click recent app, you will see new instance of jitsimeet, if you press that user can able to join with past meeting.

### Expected behavior:

When already user is in meeting & tries to join new meeting, old meeting should end and user can able to join with new meeting

### Actual behavior:

not joining with new meeting, also new instance created for old meeting

**Comment by saghul** [comment]
The SDK does not impose instance limits. If you launch 2 activities you are going to run into issues, but the SDK won't prevent you from doing that.

You should keep track of your meetings activity and send a new intent to it instead, which will make it replace the existing meeting.

**Comment by VinoSimon** [comment]
in this case when user try to join with new meeting from android sdk, how to leave from existing meeting and join into new meeting?

**Comment by saghul** [comment]
You can send the  intent to the existing JitsiMeetActivity.
