### ISSUE TITLE
Live Streaming unavailable

### ISSUE THREAD

**Issue by Sx3** [jitsi/jitsi-meet#9739]
### Description:
We are trying to test the youtube live streaming on a self-hosted jitsi-meet server. and we are getting the following error

![image](https://user-images.githubusercontent.com/3599933/129852592-64d4ef91-5711-4724-ad92-8af3821e67c1.png)

### Server information:

- Jitsi Meet version: 
![image](https://user-images.githubusercontent.com/3599933/129855612-523cad02-6ac4-489a-96c4-87f3ab897b51.png)

- Operating System:Ubuntu 18.04

### Client information:

- Browser / app version: Tested on Google Chrome latest, Firefox latest
- Operating System: Windows 10

### Additional information:

Logs;

[jvb.log](https://github.com/jitsi/jitsi-meet/files/7005381/jvb.log)
[log.0.txt](https://github.com/jitsi/jitsi-meet/files/7005384/log.0.txt)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/7005385/jicofo.log)

any directions will be very helpful
Thanks.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

For live streaming you need to install and configure jibri, one instance per session.
