### ISSUE TITLE
Wait for the host modal dialog is not closed on first click. But does in the second click.

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#9745]
### Description:
My Jitsi meet instance is secure domain enabled by JWT method, so when ever guest user join the conference before any moderator enter, ```Wait for the host...``` modal dialog is shown. 

The problem is clicking on the ```Cancel``` button doest not close/redirect (enableClosePage in config.js), but it doest in the second click.

### Steps to reproduce:

1. Should be a secure domain instance.
2. Join a conference without any moderator already joined.
3. Click on the ```Cancel``` button of  ```Wait for the host...``` modal dialog.
4. Doesn't close/redirect on the first click, but does on the second click.

![ksnip_20210818-173621](https://user-images.githubusercontent.com/2870845/129896076-e25b529e-3dea-4541-91c3-4b01cdd1d2cf.png)

### Expected behavior:

Should close the modal dialog or redirect to close page on the first click.

### Actual behavior:

It is neither closing nor redirecting to close page on the first click itself.

### Solution

On the first click in cancel button, it is binding onClick event to cancel button, I think is done for avoiding closing/redirecting on clicking outside of a modal dialog. in the second click same ```_onCancelWaitForOwner()``` triggered and ```cancelButton.onclick``` triggered, at this moment only the dialog is closed or redirected.

https://github.com/jitsi/jitsi-meet/blob/595df524b06cbbeab872ab0fbb930afbd774e694/react/features/authentication/components/web/WaitForOwnerDialog.js#L65-L76

I was able to fix this behaviour by adding prop ```disableBlanketClickDismiss``` to true.

```javascript
<Dialog
    disableBlanketClickDismiss = { true }
    hideCloseIconButton = { true }
    okKey = { t('dialog.IamHost') }
    onCancel = { this._onCancelWaitForOwner }
    onSubmit = { this._onIAmHost }
    titleKey = { t('dialog.WaitingForHostTitle') }
    width = { 'small' }>
    <span>
        {
            translateToHTML( t, 'dialog.WaitForHostMsg', { room })
        }
    </span>
</Dialog>
```

and no more need binding onclick event in cancel function, just dispatching redux action.

```javascript
_onCancelWaitForOwner() {
    const { dispatch } = this.props;

    dispatch(cancelWaitForOwner());
}

```

**Comment by saghul** [comment]
Thanks for the report!

@Calinteodor can you please take a look when have some spare cycles?

**Comment by Calinteodor** [comment]
Tested the proposed solution and it worked.
Created a PR that applies for both authentication dialogs. Thanks @saghul and @ashiqhassan95!

**Comment by ashiqhassan95** [comment]
@Calinteodor 
Great.. 
Thankyou...
