### ISSUE TITLE
Document the true meaning of (or rename) DISABLE_FOCUS_INDICATOR

### ISSUE THREAD

**Issue by karniemi** [jitsi/jitsi-meet#9764]
**Is your feature request related to a problem you are facing?**
It seems that nobody would have guessed the effect of DISABLE_FOCUS_INDICATOR
* https://github.com/jitsi/jitsi-meet/issues/5948 and the linked issues there
* users were looking for a way to disable the "moderator rights granted to"-notifications, but they had no idea that DISABLE_FOCUS_INDICATOR would do it
* the parameter seems a bit oddly named for this functionality

**Describe the solution you'd like**
Rename the old option (gracefully?), or at least document the functionality it provides.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by saghul** [comment]
This has been renamed to disableModeratorIndicator and moved to config.js.
