### ISSUE TITLE
Rename enterprise version of jitsi to "Beyond Meet"

### ISSUE THREAD

**Issue by nordurljosahvida** [jitsi/jitsi-meet#9778]
Just think about it. You already know the answer. It's also so damn perfect it almost tears me up.

**Is your feature request related to a problem you are facing?**

Yes, I face many problems each day

**Describe the solution you'd like**
This one

**Describe alternatives you've considered**
None. Nothing gets done when you overthink stuff.

**Comment by fpietrosanti** [comment]
That's a super feature, kudos and support!

**Comment by saghul** [comment]
We are not considering a name change. Thanks for the suggestion though!
