### ISSUE TITLE
Make keyboard shortcuts work in older browsers through fallback selectors

### ISSUE THREAD

**Issue by asdofindia** [jitsi/jitsi-meet#9782]
Today I was in a meeting with a friend who uses [falkon](https://www.falkon.org/) browser. Keyboard shortcuts do not work in that browser.

I checked the console in this browser and found this error line:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': ':focus:is(input,textarea,button,[role=button],[role=menuitem],[role=radio],[role=tab],[role=option],[role=switch],[role=range],[role=log])' is not a valid selector.
    at window.onkeyup (https://web-cdn.jitsi.net/meetjitsi_5216.1883/libs/app.bundle.min.js?v=5211.1878:150:239609)
window.onkeyup  @  keyboardshortcut.js:76
```

I played around in the browser and figured out that the problem is that this browser does not support the `:is()` pseudo class function.

I found that this browser supports only `:-webkit-any`.

As per the [MDN article on it](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) there is a fallback that's possible by try-catching the `:is` call.

I think this maybe a good first bug for someone to work on if the team is willing to make this backwards compatibility change.

An alternative solution would be to attach listeners to the focus and blur events of these elements to disable and enable keyboard shortcuts respectively.

**Comment by saghul** [comment]
Sorry we cannot commit to maintaining support for such old browsers. If you make a PR we'll take it though.
