### ISSUE TITLE
Failed to launch 'org.jitsi.meet://meet.jit.si' while click on lauch app from jitsi meet iframe api

### ISSUE THREAD

**Issue by Swatinfo** [jitsi/jitsi-meet#9799]
### Description:

I am using jitsi iframe API which uses 'meet.jisti.si'
Failed to launch 'org.jitsi.meet://meet.jit.si' while clicking on join this meeting form app

### Steps to reproduce:

1. 
open jitsi on mobile view android with jitsi meet iframe api
2. 
click on join this meeting from app
3. 

### Expected behavior:

it should open the app with the meeting link
### Actual behavior:

it doesn't open the app if it is already installed

### Server information:

- Jitsi Meet version:
- latest jitsi iframe API 
- Operating System:
windows 10 pro
### Client information:

- Browser / app version:
- chrome latest versoin
- Operating System:

**Comment by saghul** [comment]
I don't think intent links are supported inside an iframe, alas.

**Comment by Swatinfo** [comment]
it was working till last week but from this week onwards it has stopped working and we have not changed any code for the same
this is our implementation

const options = {
					roomName: this.consultationObj.classroom_id, // this is classroom_id
					height: 700,
					interfaceConfigOverwrite: {
						TOOLBAR_BUTTONS: [
							'microphone',
							'camera',
							'desktop',
							'fullscreen',
							'fodeviceselection',
							'hangup',
							'chat',
							'raisehand',
							'videoquality',
							'stats',
							'shortcuts',
							'tileview',
						],
						RECENT_LIST_ENABLED: false,
						INVITATION_POWERED_BY: false,
						DISPLAY_WELCOME_PAGE_CONTENT: false,
						TOOLBAR_ALWAYS_VISIBLE: true,
					},
					localRecording: {
						enabled: false,
					},
					userInfo: {
						// email: this.$auth.user.id,
						displayName: personName, // TODO this is the authenitcated user first and last name
					},
					configOverwrite: {
						prejoinPageEnabled: false,
						disableRemoteMute: true,
						startWithAudioMuted: true,
						startWithVideoMuted: true,
						remoteVideoMenu: {
							disableKick: true,
						},
					},
					parentNode: document.querySelector('#meet'),
				};
				const api = new JitsiMeetExternalAPI(domain, options);

				const numberOfParticipants = api.getNumberOfParticipants();

				api.on('videoConferenceJoined', () => {
					console.log('i have joined');
					this.hasLeft = false;
				});
				api.on('videoConferenceLeft', () => {
					console.log('i have left');
					this.hasLeft = true;
				});

**Comment by saghul** [comment]
Do you see any errors in the console logs?

**Comment by Swatinfo** [comment]
Failed to launch 'org.jitsi.meet://meet.jit.si/how-to-manage-general-anxiety-better-including-live-consultation-live-consultation-25-08-2021#jitsi_meet_external_api_id=0&config.prejoinPageEnabled=false&config.disableRemoteMute=true&config.startWithAudioMuted=true&config.startWithVideoMuted=true&config.remoteVideoMenu=%7B%22disableKick%22%3Atrue%7D&interfaceConfig.TOOLBAR_BUTTONS=%5B%22microphone%22%2C%22camera%22%2C%22desktop%22%2C%22fullscreen%22%2C%22fodeviceselection%22%2C%22hangup%22%2C%22chat%22%2C%22raisehand%22%2C%22videoquality%22%2C%22stats%22%2C%22shortcuts%22%2C%22tileview%22%5D&interfaceConfig.RECENT_LIST_ENABLED=false&interfaceConfig.INVITATION_POWERED_BY=false&interfaceConfig.DISPLAY_WELCOME_PAGE_CONTENT=false&interfaceConfig.TOOLBAR_ALWAYS_VISIBLE=true&userInfo.displayName=%22Taras%20Wolczuk%22&appData.localStorageContent=%22%7B%5C%22jitsiMeetId%5C%22%3A%5C%22f62bbf9216a7f03bbea3c4bcfb9328a7%5C%22%2C%5C%22language%5C%22%3A%5C%22en%5C%22%2C%5C%22features%2Fbase%2Fsettings%5C%22%3A%5C%22%7B%5C%5C%5C%22displayName%5C%5C%5C%22%3A%5C%5C%5C%22Taras%20Wolczuk%5C%5C%5C%22%2C%5C%5C%5C%22email%5C%5C%5C%22%3A%5C%5C%5C%22%5C%5C%5C%22%2C%5C%5C%5C%22localFlipX%5C%5C%5C%22%3Atrue%2C%5C%5C%5C%22hideShareAudioHelper%5C%5C%5C%22%3Afalse%2C%5C%5C%5C%22startAudioOnly%5C%5C%5C%22%3Afalse%2C%5C%5C%5C%22startWithAudioMuted%5C%5C%5C%22%3Afalse%2C%5C%5C%5C%22startWithVideoMuted%5C%5C%5C%22%3Afalse%7D%5C%22%2C%5C%22features%2Fvirtual-background%5C%22%3A%5C%22%7B%7D%5C%22%2C%5C%22endpointID%5C%22%3A%5C%2283039369bb3fb8d93ee0f6185a3b6cfcd722db35195f37ed81b50616f1e7838f%5C%22%2C%5C%22features%2Fwelcome%5C%22%3A%5C%22%7B%7D%5C%22%2C%5C%22callStatsUserName%5C%22%3A%5C%22Isabell-cTf%5C%22%2C%5C%22features%2Fdropbox%5C%22%3A%5C%22%7B%7D%5C%22%2C%5C%22features%2Fprejoin%5C%22%3A%5C%22%7B%5C%5C%5C%22skipPrejoinOnReload%5C%5C%5C%22%3Afalse%7D%5C%22%2C%5C%22features%2Fcalendar-sync%5C%22%3A%5C%22%7B%7D%5C%22%2C%5C%22features%2Fbase%2Fknown-domains%5C%22%3A%5C%22%5B%5C%5C%5C%22alpha.jitsi.net%5C%5C%5C%22%2C%5C%5C%5C%22beta.meet.jit.si%5C%5C%5C%22%2C%5C%5C%5C%22meet.jit.si%5C%5C%5C%22%2C%5C%5C%5C%228x8.vc%5C%5C%5C%22%5D%5C%22%2C%5C%22hide_chrome_extension_banner%5C%22%3A%5C%22true%5C%22%2C%5C%22features%2Frecent-list%5C%22%3A%5C%22%5B%7B%5C%5C%5C%22conference%5C%5C%5C%22%3A%5C%5C%5C%22https%3A%2F%2Fmeet.jit.si%2Fwithvipul%5C%5C%5C%22%2C%5C%5C%5C%22date%5C%5C%5C%22%3A1626870526605%2C%5C%5C%5C%22duration%5C%5C%5C%22%3A95737%7D%2C%7B%5C%5C%5C%22conference%5C%5C%5C%22%3A%5C%5C%5C%22https%3A%2F%2Fmeet.jit.si%2Fvipulassigntoorgissue%5C%5C%5C%22%2C%5C%5C%5C%22date%5C%5C%5C%22%3A1629282922559%2C%5C%5C%5C%22duration%5C%5C%5C%22%3A1285789%7D%5D%5C%22%2C%5C%22amplitude_unsent_fafdba4c3b47fe5f151060ca37f02d2f%5C%22%3A%5C%22%5B%5D%5C%22%2C%5C%22amp_fafdba%5C%22%3A%5C%22xt6t_SJAA-9RgVMyL4HsFs...1fduap5ij.1fduap5j2.2c.an.d3%5C%22%2C%5C%22amplitude_unsent_identify_fafdba4c3b47fe5f151060ca37f02d2f%5C%22%3A%5C%22%5B%5D%5C%22%2C%5C%22features%2Fvideo-quality-persistent-storage%5C%22%3A%5C%22%7B%5C%5C%5C%22persistedPrefferedVideoQuality%5C%5C%5C%22%3A180%7D%5C%22%7D%22' because the scheme does not have a registered handler.

**Comment by saghul** [comment]
>  because the scheme does not have a registered handler.

That's out of our control. If the app is installed such a handler exists, not sure why the browser is not picking it up, bit there is nothing we can do about it AFAICT.
