### ISSUE TITLE
Jibri not working with latest stable jitsi

### ISSUE THREAD

**Issue by roshanprince402** [jitsi/jitsi-meet#9815]
I've setup latest jibri and jisti, Everything working fine but when i'm start streaming no audio and video coming to the stream and when click on stop streaming jitsi crashing same thing happening for recording.
Same jibri instance is working fine with older one jisti instance
For jibri setup i've follow this tutorial --> https://community.jitsi.org/t/tutorial-how-to-install-the-new-jibri/88861
--> https://github.com/jitsi/jibri

**Comment by saghul** [comment]
Please open a discussion topic in our community and provide logs.
