### ISSUE TITLE
very old react-native-netinfo package should be upgraded

### ISSUE THREAD

**Issue by keremoge** [jitsi/jitsi-meet#9822]
Hi,

jitsi-meet uses [react-native-netinfo](https://github.com/react-native-netinfo/react-native-netinfo) version [**4.1.5**](https://github.com/react-native-netinfo/react-native-netinfo/releases/tag/v4.1.5), but this version is _**2 years old**_ and may cause some security issues.

should be upgraded to **latest version**.

**Comment by saghul** [comment]
What security problems does it have?

**Comment by keremoge** [comment]
These are All Android and iOS related react-native-netinfo bugfixes till version 4.1.5;
Some of them **_may_** prevent security issues. I said **_may cause_** because I'm not sure, but should be considered;


* Ensure warnings are not shown on React Native 0.65 (#487 by @lubomyr) (ac0ed65)
* android: isConnected is incorrect for wifi networks only the app has access to (#443 by @eliaslecomte) (7084771)
* useNetinfo: return null for initial unknown connection state (#444 by @lisabaut) (4d84f14), closes #295
* useNetinfo: When the connection state is unknown, the isConnected and isInternetReachable properties are now set to null rather than false. This allow you to easily detect the initial "unknown" state before the state is detected and set to a boolean.
* ios,tvos: Remove IPv4-only paths to prevent App Store warnings (#431 by @ greenantdotcom ) (1db98cb)
* ios: Support Mac Catalyst (#415 by @kyle-ssg) (5771efb)
* ios: depend directly on React-Core in podspec for Xcode 12 compatibility (#409) (bcf8bf9)
* android: Add missing isWifiEnabled type definition (#396 by @TimRobinson1) (76d8db5)
* Added missing bssid type definition to Typescript (#370 by @organom) (72ef6cd)
* android: Add another check in ConnectivityReciever to make sure we have ACCESS_WIFI_STATE permission (#379 by @sweggersen) (b0ff1ff)
* added strength wifi property to typescript (#377) (e8cb4d3)
* Android: Do not use getFrequency method for Android lower than LOLLIPOP (#367 by @ObidosDev) (4957aaa)
* android: Avoid unneccesary downoads of Gradle plugins (#358 by @SaeedZhiany) (8479319)
* Fix the provided Jest mock so it works with the instructions in the README (a24ebb1), closes #345 #327
* Ensure the default timeouts are the correct way around (4e3e981)
* Remove use of Promise.prototype.finally to prevent possible compatibility issues (#311 by @davidstritzl) (c0e6f62)
* Correct reachability timeouts in default configuration (#301 by @davidstritzl) (f74b8cc)
* android: Handle invalid networks in network listener (#286) (a153240)
* android: Remove the Android native tests to avoid issues (d9fdf85), closes #276
* android: Fixed connection change bug on Android (#265 by @QuickBase) (8748242)
* Ensure passing no configuration to the hook works correctly (#264 by @lonnylot) (e3fc1b4), closes #262
* Android: Allow using androidXCore together with supportLibVersion (#247 by @euharrison) (37366ee)
* Remove Android Spotless formatter to avoid issues with resolving plugins (1c2de77), closes #243 #213
* Android: Fix build.gradle react-native dependency version (#218 by @friederbluemle) (1bfb425)
* iOS: Crash caused by trace condition when releasing resources (#209 by @tido64) (b43838f)
* iOS: Method definition for 'dictionaryValue' not found (#224) (a5f227c)

**Comment by saghul** [comment]
PRs are welcome.

**Comment by keremoge** [comment]
As I see, it is updated on this #10724
