### ISSUE TITLE
Presenter Mode own camera window position 

### ISSUE THREAD

**Issue by AtomicNess123** [jitsi/jitsi-meet#9824]
Is there a way in the presenter mode while sharing slides, to have my camera showing me, the presenter, window positioned elsewhere? Sometimes it hides important information from the slides I am sharing. Thanks!

**Comment by saghul** [comment]
Not at the moment but we have some changes coming up about that soon :-)

**Comment by AtomicNess123** [comment]
That's wonderful, thank you. Excellent utility, the best video conferencing out there.
