### ISSUE TITLE
User Join notification not displayed when uncommenting notifications array in config.js

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#9825]
### Description:
User join notification is not displayed once I uncommented notifications array in config.js. Jitsi meet allows enabling/disabling certain notifications from config.js file.

### Steps to reproduce:

1. Uncomment the entire notifications array in config.js
2. Create a new conference, a moderator join (any user)
3. In another instance (tab or browser), User XYZ join the same conference.
4. User join notification will not be displayed for moderator users or other users in the conference that XYZ joined.

### Expected behavior:
Every user in the conference should get a notification that XYZ is joined.

### Actual behavior:
No notification is displayed.

### Solution
Just add the following keys in the notifications array in the config.js

```
'notify.connectedOneMember',
'notify.connectedTwoMembers',
'notify.connectedThreePlusMembers',
```

![ksnip_20210830-151316](https://user-images.githubusercontent.com/2870845/131320440-d2c8302a-20bf-4fa0-af32-32e3a0729074.png)

Those keys were missed in the config.js and are used for validation in following functions

https://github.com/jitsi/jitsi-meet/blob/4716bdd3807ac9dc3beb3c652158ccbdf578791d/react/features/notifications/actions.js#L91-L102

https://github.com/jitsi/jitsi-meet/blob/4716bdd3807ac9dc3beb3c652158ccbdf578791d/react/features/notifications/actions.js#L136-L173

**Comment by damencho** [comment]
Can you create a PR fixing it?

**Comment by ashiqhassan95** [comment]
Not yet created a PR in the opensource repo yet.
It would be great if you could provide me instructions for that..

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/5857620d81c40ce27a51ba7f9746dcf5940fd1cd
