### ISSUE TITLE
Failed to get access to local media. NotAllowedError: Permission denied

### ISSUE THREAD

**Issue by Malik464** [jitsi/jitsi-meet#9834]
![image](https://user-images.githubusercontent.com/64679168/131499381-c52e3755-45ff-4300-98e3-d68f9f835636.png)

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Seems there is device which hasn't been granted access for the page.

**Comment by Malik464** [comment]
permission is grated from device
in fresh installation it's working fine , when i'm including bootstrap cdn in index.html then it's stop working don't know why

**Comment by damencho** [comment]
is the cdn link http or https?

**Comment by Malik464** [comment]
yes
https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css

**Comment by Malik464** [comment]
rest everything is fine, only issue with the device selection modal

**Comment by damencho** [comment]
Maybe run chrome with webrtc debug logging and check the logs ... something may ring a bell

**Comment by Malik464** [comment]
Okay, i will try it now
![image](https://user-images.githubusercontent.com/64679168/131508434-87f47da9-3220-421f-93dd-babdd4d73ffb.png)
look at this it's showing like this

**Comment by Malik464** [comment]
![image](https://user-images.githubusercontent.com/64679168/131510868-fdb797c3-d958-4900-8303-8ec3d9753dbe.png)

**Comment by Malik464** [comment]
@daimoc here is the webrtc log

**Comment by Malik464** [comment]
could you please help me , i'm stucked on this from last two days

**Comment by damencho** [comment]
By webrtc log I mean https://webrtc.github.io/webrtc-org/native-code/logging/
And it runs normally if you remove that cdn link?

**Comment by Malik464** [comment]
yes after removing that link it's working fine

**Comment by Malik464** [comment]
![image](https://user-images.githubusercontent.com/64679168/131513388-f02ec223-0d10-4deb-ac55-943271625dc1.png)
in console i'm getting this log, will try with webrtc log also

**Comment by damencho** [comment]
Check in the console do you have any non-https resources, not sure whether that blocks webrtc in any way ...
