### ISSUE TITLE
how change ui when video meeting?

### ISSUE THREAD

**Issue by parinexus** [jitsi/jitsi-meet#9840]
I want to change Ui when video metting. how change it to Custom ui?

**Comment by damencho** [comment]
Please use the community forum for questions before opening new issues, thank you.

**Comment by parinexus** [comment]
Is there a similar case? Please send the link

**Comment by damencho** [comment]
The link is already there:
![image](https://user-images.githubusercontent.com/3263098/131554104-a10c9139-1eca-4858-8393-97cfab324441.png)

https://community.jitsi.org/
