### ISSUE TITLE
Audio signal scrambled in Firefox 91.0.2 on Linux Mint 20.2

### ISSUE THREAD

**Issue by OSevangelist** [jitsi/jitsi-meet#9849]
### Description:

Audio scrumbled from PulseAudio micrphone source if used together with Firefox

### Steps to reproduce:

1. Join a conference with Firefox, Linux and a Microphone connected
2. Ask participants if they can understand you properly

### Expected behavior:

No issues with Audio streams being scrambled

### Actual behavior:

Audio signal is scrambled (i.e. sounds like a robot and isn't understandable)

### Server information:

- Jitsi Version: Most Recent
- Operating System: Ubuntu 20.04.LTS

### Client information:

- Firefox: Update 91.0.2
- Operating System: Linux Mint 20.2 (Uma)

### Additional information:

It works flawelessly with Chrome and Chromium
It is independent of the audio source (as long as it is connected to PulseAudio) at least

**Comment by saghul** [comment]
Given it works fine on Chromium but not on Firefox, it feels like a browser bug. Do you observe similar behavior with other WebRTC products / services?

**Comment by OSevangelist** [comment]
HI @saghul yes this is what i am thinking as well, but before trying other WebRTC services i thought it would be wise to spread the word on my experience with this contemporary FF release. However, just now i installed the FF Update to 92.0 and give that a try

**Comment by BrandonMCMFG** [comment]
**Confirmed an issue with Firefox 92.0.1 (64-bit).**

**Description:**
- Audio sounds like a robot with Pulseaudio if Firefox is open.

**Steps to reproduce:**
1. Play YouTube and open multiple tabs (around 10),
2. switch to another tab, 
3. the audio then becomes all scrambled.

**Operating System:** 
- Linux Mint 20.2 "Uma" (based on Ubuntu 20.04.3 LTS)

**Additional information:**
1. It works properly when as soon as you close Firefox, even if you use Rhythmbox to listen to music that music sounds like a robot but then when you close Firefox it is fine again.
2. Haven't tried it with a chromium based browser yet but tomorrow I'll try it with brave and see if its the same.
