### ISSUE TITLE
After recent update, SIP Dialer no longer does anything

### ISSUE THREAD

**Issue by Fohdeesha** [jitsi/jitsi-meet#986]
ran an apt-get update/upgrade today and it upgraded to the new jitsi UI which I will say is much nicer.

However now the SIP dialing button doesn't do anything. The Jigasi back end is still working well and I can see clearly on my asterisk box where it succesfully registers when the jitsi VM boots:

`-- Contact 900/sip:900@10.0.0.5:5060;registering_acc=10_0_0_4 is now Reachable.  RTT: 4.615 msec
  == Endpoint 900 is now Reachable
  == Extension Changed 900[ext-local] new state Idle for Notify User 100`

However when I load up Jitsi, click the sip dialing button and enter a number and click dial, it does absolutely nothing. Watching my asterisk box in verbose output, there's zero attempts at anything made. No dialing attempt, etc, no traffic at all other than the initial Jigasi register when the box booted. 

Uninstalled and purged jigasi, and reinstalled it and totally reconfigured everything including prosody to ensure all the authentication is correct, and still the same result. 

If it matters I'm on jigasi_1.0-108_amd64.deb as build 107 has a fatal error that makes it incompatible with Asterisk (see here - https://github.com/jitsi/jigasi/pull/36 )

**Comment by damencho** [comment]
There was indeed problem in lib-jitsi-meet which is now fixed in unstable
and we will soon update it and in stable.

Regards
damencho

**Comment by Fohdeesha** [comment]
love how quick you guys are :+1:

**Comment by damencho** [comment]
Could you please use the mailinglist before opening issues.
