### ISSUE TITLE
Virtual background in Android

### ISSUE THREAD

**Issue by UserSty** [jitsi/jitsi-meet#9868]
Does support virtual background Jitsi SDK in Android? I see this option in a web browser but I don't see it in the native mobile app.
If Jitsi doesn't support maybe do you have a plan for that?

**Comment by saghul** [comment]
It's not currently supported on the native SDKs. We'd like to have it but there are no short term plans for it at the moment.

**Comment by UserSty** [comment]
Thanks for the quick answer
