### ISSUE TITLE
[Android] Could not find jitsi-meet:amplitudereactnative:unspecified.

### ISSUE THREAD

**Issue by TamND87** [jitsi/jitsi-meet#9872]
### Description: I've to use my own SDK but can't build an Android app with the latest source code. (Old source code works well without Amplitude React Native)

**Could not find jitsi-meet:amplitudereactnative:unspecified.**
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/jitsi-meet/amplitudereactnative/unspecified/amplitudereactnative-unspecified.pom
       - https://repo.maven.apache.org/maven2/jitsi-meet/amplitudereactnative/unspecified/amplitudereactnative-unspecified.pom
       - https://jcenter.bintray.com/jitsi-meet/amplitudereactnative/unspecified/amplitudereactnative-unspecified.pom
       - **file:/tmp/repo/jitsi-meet/amplitudereactnative/unspecified/amplitudereactnative-unspecified.pom**
     Required by:
         project :app > org.jitsi.react:jitsi-meet-sdk:3.9.0

Android Studio - Arctic Fox | 2020.3.1 Patch 2

**Comment by saghul** [comment]
Yep, this is know, a new updated SDK is coming soon.

**Comment by tmoldovan8x8** [comment]
Published 3.9.1, should be fixed now
