### ISSUE TITLE
How to convert jitsi as react native library using windows?

### ISSUE THREAD

**Issue by VinoSimon** [jitsi/jitsi-meet#9873]
Using customized jitsi meet as jitsi meet react native library 

### Description:

I made some modifications on jitsi meet, I can able to convert as android & iOS library. But there are no steps to generate my customized jitsi meet code as react native library. can anyone help me to figure out?

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
It's not currently supported, sorry.
