### ISSUE TITLE
recent jitsi calls listing on ios devices with video icon and phone icon separately for one audio call even video call disabled

### ISSUE THREAD

**Issue by egemenkayalidere** [jitsi/jitsi-meet#9881]
Hi,

On android devices, it is not listing on recent phone calls when connected and finished a jitsi call.

But on ios devices, it is listing on recent phone calls with the name of room or what we had set (like room id or etc.) 

So, I want to disable listing of jitsi calls on recent phone calls screen (not in app in device recent phone calls screen) on ios devices. Is it possible ?

Because, it is listing an audio call as a phone call with phone icon and a video call with video icon together for only one jitsi call with the same room name. But I do just an audio call not a video call. Is it possible to manage ?

Thanks

**Comment by saghul** [comment]
> On android devices, it is not listing on recent phone calls when connected and finished a jitsi call.

That's correct, because we disabled ConnectionService, which does that, due to iit being too problematic.



> So, I want to disable listing of jitsi calls on recent phone calls screen (not in app in device recent phone calls screen) on ios devices. Is it possible ?

If you are using the SDK you can override `callHandle` and set it empty, that should disable showing the call in the recents list.



> Because, it is listing an audio call as a phone call with phone icon and a video call with video icon together for only one jitsi call with the same room name. But I do just an audio call not a video call. Is it possible to manage ?

Not sure I understand but what you see is what CallKit does. When you report a call as being an audio call it will show the audio icon and when you report  it as a video call it shows with the video icon. We report calls automatically.

**Comment by egemenkayalidere** [comment]
In config.js file, below property exist. 

Does this control showing the calls in the recents list ? I tried to set true and false but nothing happened, the calls still listing in the recents list.

// Disables storing the room name to the recents list
doNotStoreRoom: true,

Thanks

**Comment by saghul** [comment]
That controls the web recents list you see in the welcome page. It does not apply to mobile.

**Comment by saghul** [comment]
It may make sense to make it do that too. Would you like to make a PR?
