### ISSUE TITLE
Add configuration to disable chat emoticons (smileys)

### ISSUE THREAD

**Issue by dimitardelchev93** [jitsi/jitsi-meet#9889]
In some cases the chat emoticons may not be wanted, and currently there does not seem to be a way to achieve that.

It may be a good idea to have `disableChatSmileys` config, which is `false` by default, and if set to `true`, the emoticons will not be available.

With no config set or config set to `false`:

![image](https://user-images.githubusercontent.com/43634401/132500917-04e57e6f-d90b-43cd-90ec-ce412e838738.png)

With config set to `true`:

![image](https://user-images.githubusercontent.com/43634401/132501213-9b1a8402-d07f-4e93-84f6-3d2793453515.png)

**Comment by saghul** [comment]
Honestly, in 2021 who doesn't want emoji? Legit question. If someone doesn't want them they can just ignore them. Why would a setting be necessary here?

**Comment by dmr** [comment]
The feedback we received from some customers with not very technical users is that they are confused by this and they would rather control which emojis people can use etc. So in general sure, emojis are a thing nowadays but some customers want to disable this

**Comment by saghul** [comment]
Nope, feel free to create one.
