### ISSUE TITLE
Confs in /etc/jitsi/videobridge/sip-communicator.properties isn't honored

### ISSUE THREAD

**Issue by filhocf** [jitsi/jitsi-meet#989]
I used the last nightly build deb pkg in a host behind a NAT network. Configuring the /etc/jitsi/videobridge/sip-communicator.properties to mirror my confs, isn't read by JVB.

So, after the help of @bgrozev and @damencho, was observed that in really JVB reads confs from /usr/share/jitsi-videobridge/.sip-communicator/sip-communicator.properties.

The workaround used was to create a symbolic link from this file to /etc/jitsi/videobridge/sip-communicator.properties file.

**Comment by bgrozev** [comment]
The default installation correctly uses /etc/jitsi/videobridge as the jitsi-videobridge configuration directory (this is defined in /etc/jitsi/videobridge/config).

**Comment by filhocf** [comment]
Really. I tried to install directly in a host and works fine. Is some problem using Docker. Thank you.
