### ISSUE TITLE
Add different text when disablePolls is enabled/disabled

### ISSUE THREAD

**Issue by dimitardelchev93** [jitsi/jitsi-meet#9890]
There is a `disablePolls` configuration, which removes the polls tab in the chat container, but there are two texts that are still containing 'polls' even if the configuration is set to `true`.

It may be a good idea to add different text, when polls are enabled/disabled.

![image](https://user-images.githubusercontent.com/43634401/132506233-9a6fd3fe-5484-4049-b8b0-1c74b83d55bd.png)

Another solution is just to remove the 'polls' mentions in those two texts, something like that:

![image](https://user-images.githubusercontent.com/43634401/132511835-17fbf361-d366-449c-b2b7-6e7e2d396d07.png)

**Comment by saghul** [comment]
Good catch.

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/jitsi-meet/commit/11a86a93838314ad7816efffaea8bb0788a7c585

**Comment by Marinaarimany** [comment]
@dimitardelchev93 
how do you go about deactivating the polls please ? Thank you :)

**Comment by Marinaarimany** [comment]
@saghul

**Comment by dimitardelchev93** [comment]
@Marinaarimany there is a `disablePolls` config:

![image](https://user-images.githubusercontent.com/43634401/134889275-c0b20af8-acd9-473e-ac35-5b320d409ad7.png)

**Comment by Marinaarimany** [comment]
> @Marinaarimany il y a une `disablePolls`config :
> 
> ![image](https://user-images.githubusercontent.com/43634401/134889275-c0b20af8-acd9-473e-ac35-5b320d409ad7.png)


Ok thank you for your answer even if it didn't help me ahah I'm working on react native and I'm looking for a solution to remove the polls ^^

**Comment by khaimp** [comment]
Best fix is custom code in /react/features/chat/components/web/Chat.tsx . Change _isPollsEnabled true before render component  ! I try set disablePolls = true in config.js but it not working after i custom code and rebuild -> it working in room (note : it cache config )
![image](https://github.com/jitsi/jitsi-meet/assets/108779587/d55064eb-6e19-442a-bf15-c87b4756e121)

**Comment by staryan01** [comment]
using  .setConfigOverride("disablePolls", true)  disabling only the "create poll" button while still allowing participation in and viewing of polls—this setting i wants in joinee not for moderator ,as moderator should have access for create poll but not for joinee

**Comment by saghul** [comment]
We are in the process of implementing that feature, under a different feature flag.
