### ISSUE TITLE
Screen Share

### ISSUE THREAD

**Issue by domenicocosta** [jitsi/jitsi-meet#9893]
**Is your feature request related to a problem you are facing?**
Due to privacy issues, many times the user connected to a call, can't tell whether he is sharing his screen or application windows or not, if he simply hides the popup circled in red the button in the next image.

![attuale](https://user-images.githubusercontent.com/19182983/132515521-7c4c1703-f562-448c-aae0-04b3be62e269.png)

**Describe the solution you'd like**
To avoid this problem I would like the application to delete the previous popup and display a red square on the shared window or screen, as visible in the next image. Same behavior that the well-known skype performs in screen sharing.

![voluta](https://user-images.githubusercontent.com/19182983/132516340-1898f076-a0cf-4898-a2c6-5f8993d09adb.png)

**Comment by damencho** [comment]
This is something we cannot control, this is controlled by the browsers. So you better open feature requests in Chrome/Firefox/Safari issue trackers.
