### ISSUE TITLE
Error building for iOS Simulator using jitsi meet SDK 3.9.0 on M1 apple silicon system. With suggested fix

### ISSUE THREAD

**Issue by stuartrr** [jitsi/jitsi-meet#9898]
# Description:

This is basically a dup of the wontfix issue https://github.com/jitsi/jitsi-meet/issues/8969 but with a suggestion that should fix it.

I am using the JitsiMeetSDK 3.9.0 iOS XCFramework binaries for my project, when I try to run my project on xcode Version 12.5.1 on an iPhone Simulator, I get the following error:

building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64

This seems to be due to the fact that I am developing on a mac with M1 apple silicon chip - so there should also be a binary for iOS Simulator-arm64 inside the Jitsi Meet SDK.

# Steps to reproduce:

1. Add binary xcframeworks (webrtc and jitsimeetsdk) to project
2. set embed and sign to embed libraries section of target
3. under build phases set WebRTC and JitsiMetSDK as required under link lib section
4. Run the project on arbitrary iphone simulator
5. Expected behavior:
6. App is built and iPhone Simulator starts the app.

# Actual behavior:

Above error on linking stage of App build for simulator

Client information:
Browser / app version: Jitsi Meet SDK 3.9.0
Operating System: macOS Big Sur
Hardware: Chip Apple M1, 2020

# Additional information:

The suggested fix is to change https://github.com/jitsi/jitsi-meet/blob/e38ebc6628f3e1cae852eb03c3e9baaa74d664d8/ios/scripts/release-sdk.sh#L38

from 

VALID_ARCHS=x86_64

to 

VALID_ARCHS='x86_64 arm64'

I haven't tested it because I wasn't able to get that release-sdk.sh to run to completion myself (with and without that change).

It seems like `WebRTC.xcframework` might also need to be updated to support ios-arm64-simulator. Created an issue there as well https://github.com/react-native-webrtc/react-native-webrtc/issues/1063.

```
mkdir -p ios/sdk/out
xcodebuild clean \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphonesimulator \
    -destination='generic/platform=iOS Simulator' \
    -archivePath ios/sdk/out/ios-simulator \
    VALID_ARCHS=x86_64 \ < =============== change to === VALID_ARCHS='x86_64 arm64' \
    ENABLE_BITCODE=NO \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive \
    -workspace ios/jitsi-meet.xcworkspace \
    -scheme JitsiMeetSDK  \
    -configuration Release \
    -sdk iphoneos \
    -destination='generic/platform=iOS' \
    -archivePath ios/sdk/out/ios-device \
    VALID_ARCHS=arm64 \
    ENABLE_BITCODE=NO \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
    -framework ios/sdk/out/ios-device.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -framework ios/sdk/out/ios-simulator.xcarchive/Products/Library/Frameworks/JitsiMeetSDK.framework \
    -output ios/sdk/out/JitsiMeetSDK.xcframework
cp -a node_modules/react-native-webrtc/apple/WebRTC.xcframework ios/sdk/out
```

**Comment by stuartrr** [comment]
Would be really great to get this sorted. It should be a really quick fix. I feel like my m1 is going a bit to waste running xcode under rosetta.

**Comment by saghul** [comment]
I was not a quick fix. Master is fixed and the upcoming SDK 5 release will have M1 simulator support.

**Comment by stuartrr** [comment]
Thank you very, very much!
