### ISSUE TITLE
Local user camera is not showing video output and shows black screen until someone join the meeting in android

### ISSUE THREAD

**Issue by idrive-pankaj** [jitsi/jitsi-meet#9903]
### Description:

I am using Jitsi react native source code to create custom SDK and using that SDK in my application. Everything works fine in iOS but in Android sometimes the local user's camera output is not showing until he mute and un-mutes himself or when someone else joins the meeting.
I have checked that there is no flag or something we are using to mute that video. This is not consistent as sometimes it loads the video and sometimes it's not.

I have checked this post and all the issues related to that but none of them is similar to this one.
https://github.com/jitsi/jitsi-meet/issues/5425

I have checked logs and found something but not sure how can I resolve it. I have added android logs here for the video showing and not showing tasks.

**LOGS WHEN CAMERA IS NOT WORKING**
`D/Camera: Lct package name is ***********
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/org.webrtc.Logging: Camera1Session: Create new camera1 session on camera 1
I/org.webrtc.Logging: Camera1Session: Start capturing
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
    Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/org.webrtc.Logging: CameraCapturer: Create session done. Switch state: IDLE
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/com.oney.WebRTCModule.WebRTCModule: CameraEventsHandler.onFirstFrameAvailable
I/JitsiMeetSDK: [features/base/redux] redux state persisted. 213569b22b5aa20d98dcb1e1b6fa7f83 -> 0b31abcc09ea838b706b1d0761723afb
I/ReactNativeJS: https://meetingwb.remotepc.com/#room=h4lfvy4yv6,I25gM8BYLoZ4lk5Qz8p07g?name=Pankaj
I/ReactNativeJS: updated conference------->`

**LOGS FOR THE WORKIN CAMERA**
`I/org.webrtc.Logging: Camera1Session: Available fps ranges: [[15.0:15.0], [7.5:20.0], [20.0:20.0], [7.5:24.0], [24.0:24.0], [7.0:30.0], [30.0:30.0]]
D/Camera: Lct package name is ************
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CaptureThread: type=1400 audit(0.0:71485): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=19594 scontext=u:r:untrusted_app:s0:c162,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
I/org.webrtc.Logging: Camera1Session: Create new camera1 session on camera 1
I/org.webrtc.Logging: Camera1Session: Start capturing
I/org.webrtc.Logging: CameraCapturer: Create session done. Switch state: IDLE
D/com.oney.WebRTCModule.WebRTCModule: CameraEventsHandler.onFirstFrameAvailable
I/org.webrtc.Logging: SurfaceEglRenderer: : Reporting first rendered frame.
D/com.oney.WebRTCModule.WebRTCModule: First frame rendered.
I/org.webrtc.Logging: SurfaceEglRenderer: : Reporting frame resolution changed to 1280x720 with rotation 270
I/org.webrtc.Logging: SurfaceEglRenderer: : surfaceChanged: format: 4 size: 1074x2024
D/JitsiMeetSDK: [features/base/lastn] There is no active conference, not updating last N
I/org.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 0.53063244
I/JitsiMeetSDK: [modules/e2eping/e2eping.js] Stopping e2eping`

### Steps to reproduce:

1. Start a meeting using the SDK and make the camera enable
2. Check if the camera is showing local view or not 
3. Join or do mute unmute local user's camera and it will work fine

### Expected behavior:
The camera should load the local view even if there is no one In the meeting.

### Actual behavior:

Initially, the camera is not showing local user output on the local user side.

![Screenshot_2021-09-09-12-01-11-948_com remotepc meeting](https://user-images.githubusercontent.com/79213346/132645521-15d4dc88-da6c-4cb8-9754-3c5b308338d5.jpg)

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Can you reproduce this with our official SDK?

**Comment by idrive-pankaj** [comment]
Let me check and confirm.

**Comment by idrive-pankaj** [comment]
@saghul I have checked in the jisti code that I am using right now, Installed Jitsi build using android and it's also occurring in that code.
On the welcome page for the first time when I start a meeting it's working fine but after the relaunch, on a welcome screen camera preview is not showing.

Again I have noticed the same logs here in the preview screen.

`D/Camera: Lct package name is org.jitsi.meet
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/org.webrtc.Logging: Camera1Session: Create new camera1 session on camera 1
I/org.webrtc.Logging: Camera1Session: Start capturing
I/JitsiMeetSDK: [features/base/net-info] Network changed {"isOnline":true,"details":{"cellularGeneration":"4g","isConnectionExpensive":true},"networkType":"cellular"}
D/JitsiMeetSDK: [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
I/JitsiMeetSDK: [features/base/net-info] Network changed {"isOnline":true,"details":{"cellularGeneration":"4g","isConnectionExpensive":true},"networkType":"cellular"}
D/JitsiMeetSDK: [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
I/org.webrtc.Logging: CameraCapturer: Create session done. Switch state: IDLE
D/com.oney.WebRTCModule.WebRTCModule: CameraEventsHandler.onFirstFrameAvailable
I/org.webrtc.Logging: CameraStatistics: Camera fps: 28.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.jitsi.meet: Background concurrent copying GC freed 40818(2MB) AllocSpace objects, 5(96KB) LOS objects, 49% free, 5MB/11MB, paused 151us total 115.474ms
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.`

Could you please help me where should I check for this?

**Comment by saghul** [comment]
Hum. I cannot reproduce that currently :-/ I wonder if it's related to camera 1 vs camera 2...

**Comment by idrive-pankaj** [comment]
the strange thing is, once you change it like mute and unmute then it start working fine, let me check if I am doing something wrong here
