### ISSUE TITLE
CONFENRENCE_TERMINATED {  NativeMap: {"error":"TypeError: Network request failed","url":"https://xxx.xx.xxx/99"} }  in Android

### ISSUE THREAD

**Issue by leonard-kawhi** [jitsi/jitsi-meet#9914]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by leonard-kawhi** [comment]
In my demo, i can load jit.si/test ,but i can't load my personal server  and   i can load my server by browser.
My android version is 7  , JITSI-MEET-SDK version is 3.0.0

**Comment by saghul** [comment]
3.0.0 is very very old, please update fist. Those network errors are usually related to invalid certificates.
