### ISSUE TITLE
apple app store cannot find jitsi-meet app and getting 404

### ISSUE THREAD

**Issue by kiroswu** [jitsi/jitsi-meet#9922]
apple app store cannot find jitsi-meet app and getting 404. how to go normal?

**Comment by saghul** [comment]
I can find it just fine on the store. What is your exact problem?

**Comment by kiroswu** [comment]
> I can find it just fine on the store. What is your exact problem?

cannot got app neither in appstore nor web broswer.
https://apps.apple.com/us/app/jitsi-meet/id1165103905

![Snipaste_2021-09-12_17-44-06](https://user-images.githubusercontent.com/19584792/132982950-4ba1c929-c18a-4f50-ba11-fcb6a9f799c9.jpg)

**Comment by saghul** [comment]
Are you in China? If so, sorry, but unfortunately we don't release the app in the Chinese store.

We'd need to disable CallKit and AFAIK it's not possible to do so on a specific region.
