### ISSUE TITLE
Feature Request: Discord-Like Video/Audio Feed Control Granularity

### ISSUE THREAD

**Issue by jasonmerc** [jitsi/jitsi-meet#9923]
**Is your feature request related to a problem you are facing?**
The screen sharing and camera video sharing functionality is great, but if multiple people are sharing screens/cameras at once, you are forced to watch all of them which could waste bandwidth and compute resources.  On top of this, if all these users have audio sharing enabled (on their screen shares in particular), it turns into a giant mess of a bunch of YouTube videos or game audios all meshing into one, with no way of muting the stream without muting the person doing the streaming entirely.

**Describe the solution you'd like**
It would be great if Jitsi Meet had more granular controls for video streams, like Discord does.  One could then choose to watch a certain person's screen share or camera feed, or opt out of either/both if they don't want to watch it.  This would save bandwidth, resources, and make simultaneous audio-sharing with the screen sharing less of a mess.

To accomplish this, two things could be done:
1) Split up microphone/webcam "normal" feed and screen sharing feed into 2 separate feeds per user
2) Allow users to disable audio/video per feed, per user, instead of just a "disable video/audio on everyone for everyone" option

This would not only allow users to opt out of streaming from particular feeds, but it would also allow users to mute someone's screen sharing audio without having to mute that person entirely (i.e., a scenario of "I'd like to still hear you speak, but I don't want to hear your screen share's audio").  These settings would be on a per-user basis, so individual users could choose to enable or disable feeds if they desire without affecting anyone else.

**Describe alternatives you've considered**
There is no alternative to opting out of video streams or screen shares.  If someone chooses to share their camera or screen, you're forced to watch it.

For audio sharing, one COULD mute the person sharing the screen, but then the person's microphone gets muted as well.  You either have to listen to everything or nothing at all.

**Comment by saghul** [comment]
I'll take the bump as a reminder to close this :-)

Sorry for the belated reply. We have no plans to implement such granular controls.

We are currently working on more flexible video layouts, where the user will be able to "pin" multiple participants. Bandwidth is not something the user should manage, that's why spend a lot of time tweaking our estimations, so users only receive as much (relevant) video as they can.

**Comment by DashieTM** [comment]
No worries, with lots of issues and requests one can forget or overlook one quite easily.
And I am not sure why bandwidth is important here, it's more about muting both "channels" independently as sometimes only one of them is wanted. 
I assume this pinning will essentially do just that? Perhaps I misunderstood something here.

**Comment by jasonmerc** [comment]
Hello, just saw this got closed (didnt see the github emails before).  That's cool, I respect your decision to not implement it.

To hopefully explain it all a little better, my idea of saving bandwidth was, the device that is receiving the streams in the video call would only have to receive the video/audio streams they actually wanted to watch rather than all of them.  To compare it to Discord again, you can choose whose live stream you want to watch, rather than being forced to watch them all.  My thought was, this would save on network bandwidth, since like I was saying, your computer only has to receive the video feeds you actually _want to watch._  Keep in mind I made this request back during a time where my Internet connection was very limited, so being as efficient with the Internet speeds I had was crucial.

I made a point about resources too, although it falls under the same category basically.  I had an old laptop with a 4th gen Haswell U-series processor in it, and while it could watch one video stream without much issue, things got pretty bad when it had to stream like 5 or 6 of them concurrently.

In the end, Dashie's point really nails it though, the bottom line is only seeing what you actually want to see.  I just figured the resources and bandwidth saved could be potential positive side effects for those of us with limited compute power and network speeds.

**Comment by saghul** [comment]
We have the performance selector that also affects this. If you select the lowest setting you'll at most receive 1 video stream.

There is some play to be had with channelLastN (the config setting) too, but this is not something we think should go in the UI.
