### ISSUE TITLE
sharing screen become gray while participants >=3 users

### ISSUE THREAD

**Issue by kiroswu** [jitsi/jitsi-meet#9924]
jitsi server is self-hosted in internal host server, when 2 users join a meeting everything is good including sharing screen. 
But sharing screen become gray when the third participant joining， sharing screen goes back normal when the third participant leaving.

the web console log:

["9c3a1760"],"selectedEndpoints":[]}
Logger.js:154 2021-09-12T08:27:37.408Z [modules/RTC/BridgeChannel.js] <p._send>:  Bridge Channel send: no opened channel.
o @ Logger.js:154
_send @ BridgeChannel.js:406
sendMessage @ BridgeChannel.js:199
sendChannelMessage @ RTC.js:871
ue.sendEndpointMessage @ JitsiConference.js:2645
ue.sendMessage @ JitsiConference.js:2698
(匿名) @ JitsiConference.js:375
sendRequest @ e2eping.js:93
setInterval(异步)
d @ e2eping.js:63
participantJoined @ e2eping.js:299
a.emit @ events.js:157
ue.onMemberJoined @ JitsiConference.js:1633
a.emit @ events.js:152
onPresence @ ChatRoom.js:598
onPresence @ strophe.emuc.js:106
run @ strophe.umd.js:1875
(匿名) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send(异步)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:342
sendPresence @ ChatRoom.js:258
(匿名) @ ChatRoom.js:200
Promise.then(异步)
(匿名) @ ChatRoom.js:199
join @ ChatRoom.js:190
ue.join @ JitsiConference.js:529
connect @ conference.js:404
(匿名) @ conference.js:765
startConference @ conference.js:764
prejoinStart @ conference.js:852
async function(异步)
prejoinStart @ conference.js:850
(匿名) @ middleware.js:60
(匿名) @ middleware.js:24
(匿名) @ middleware.js:20
(匿名) @ middleware.js:15
(匿名) @ middleware.js:23
(匿名) @ middleware.js:20
(匿名) @ middleware.js:25
(匿名) @ middleware.js:74
(匿名) @ middleware.js:196
(匿名) @ middleware.js:198
(匿名) @ middleware.js:147
(匿名) @ middleware.web.js:107
(匿名) @ redux.js:475
_onJoinButtonClick @ Prejoin.js:208
f @ react-dom.production.min.js:15
_ @ react-dom.production.min.js:15
(匿名) @ react-dom.production.min.js:16
S @ react-dom.production.min.js:16
A @ react-dom.production.min.js:17
x @ react-dom.production.min.js:17
D @ react-dom.production.min.js:17
jn @ react-dom.production.min.js:81
ce @ react-dom.production.min.js:285
An @ react-dom.production.min.js:83
Tn @ react-dom.production.min.js:84
Dn @ react-dom.production.min.js:84
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
xn @ react-dom.production.min.js:82
Logger.js:154 2021-09-12T08:27:37.408Z [JitsiConference.js] <u.sendMessage>:  Failed to send E2E ping request or response. undefined
o @ Logger.js:154
(匿名) @ JitsiConference.js:378
sendRequest @ e2eping.js:93
setInterval(异步)
d @ e2eping.js:63
participantJoined @ e2eping.js:299
a.emit @ events.js:157
ue.onMemberJoined @ JitsiConference.js:1633
a.emit @ events.js:152
onPresence @ ChatRoom.js:598
onPresence @ strophe.emuc.js:106
run @ strophe.umd.js:1875
(匿名) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send(异步)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:342
sendPresence @ ChatRoom.js:258
(匿名) @ ChatRoom.js:200
Promise.then(异步)
(匿名) @ ChatRoom.js:199
join @ ChatRoom.js:190
ue.join @ JitsiConference.js:529
connect @ conference.js:404
(匿名) @ conference.js:765
startConference @ conference.js:764
prejoinStart @ conference.js:852
async function(异步)
prejoinStart @ conference.js:850
(匿名) @ middleware.js:60
(匿名) @ middleware.js:24
(匿名) @ middleware.js:20
(匿名) @ middleware.js:15
(匿名) @ middleware.js:23
(匿名) @ middleware.js:20
(匿名) @ middleware.js:25
(匿名) @ middleware.js:74
(匿名) @ middleware.js:196
(匿名) @ middleware.js:198
(匿名) @ middleware.js:147
(匿名) @ middleware.web.js:107
(匿名) @ redux.js:475
_onJoinButtonClick @ Prejoin.js:208
f @ react-dom.production.min.js:15
_ @ react-dom.production.min.js:15
(匿名) @ react-dom.production.min.js:16
S @ react-dom.production.min.js:16
A @ react-dom.production.min.js:17
x @ react-dom.production.min.js:17
D @ react-dom.production.min.js:17
jn @ react-dom.production.min.js:81
ce @ react-dom.production.min.js:285
An @ react-dom.production.min.js:83
Tn @ react-dom.production.min.js:84
Dn @ react-dom.production.min.js:84
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
xn @ react-dom.production.min.js:82
Logger.js:154 2021-09-12T08:27:37.495Z [modules/RTC/BridgeChannel.js] <p._send>:  Bridge Channel send: no opened channel.
o @ Logger.js:154
_send @ BridgeChannel.js:406
sendMessage @ BridgeChannel.js:199
sendChannelMessage @ RTC.js:871
ue.sendEndpointMessage @ JitsiConference.js:2645
ue.sendMessage @ JitsiConference.js:2698
(匿名) @ JitsiConference.js:375
sendRequest @ e2eping.js:93
setInterval(异步)
d @ e2eping.js:63
participantJoined @ e2eping.js:299
a.emit @ events.js:157
ue.onMemberJoined @ JitsiConference.js:1633
a.emit @ events.js:152
onPresence @ ChatRoom.js:598
onPresence @ strophe.emuc.js:106
run @ strophe.umd.js:1875
(匿名) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send(异步)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:342
sendPresence @ ChatRoom.js:258
(匿名) @ ChatRoom.js:200
Promise.then(异步)
(匿名) @ ChatRoom.js:199
join @ ChatRoom.js:190
ue.join @ JitsiConference.js:529
connect @ conference.js:404
(匿名) @ conference.js:765
startConference @ conference.js:764
prejoinStart @ conference.js:852
async function(异步)
prejoinStart @ conference.js:850
(匿名) @ middleware.js:60
(匿名) @ middleware.js:24
(匿名) @ middleware.js:20
(匿名) @ middleware.js:15
(匿名) @ middleware.js:23
(匿名) @ middleware.js:20
(匿名) @ middleware.js:25
(匿名) @ middleware.js:74
(匿名) @ middleware.js:196
(匿名) @ middleware.js:198
(匿名) @ middleware.js:147
(匿名) @ middleware.web.js:107
(匿名) @ redux.js:475
_onJoinButtonClick @ Prejoin.js:208
f @ react-dom.production.min.js:15
_ @ react-dom.production.min.js:15
(匿名) @ react-dom.production.min.js:16
S @ react-dom.production.min.js:16
A @ react-dom.production.min.js:17
x @ react-dom.production.min.js:17
D @ react-dom.production.min.js:17
jn @ react-dom.production.min.js:81
ce @ react-dom.production.min.js:285
An @ react-dom.production.min.js:83
Tn @ react-dom.production.min.js:84
Dn @ react-dom.production.min.js:84
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
xn @ react-dom.production.min.js:82
Logger.js:154 2021-09-12T08:27:37.496Z [JitsiConference.js] <u.sendMessage>:  Failed to send E2E ping request or response. undefined
o @ Logger.js:154
(匿名) @ JitsiConference.js:378
sendRequest @ e2eping.js:93
setInterval(异步)
d @ e2eping.js:63
participantJoined @ e2eping.js:299
a.emit @ events.js:157
ue.onMemberJoined @ JitsiConference.js:1633
a.emit @ events.js:152
onPresence @ ChatRoom.js:598
onPresence @ strophe.emuc.js:106
run @ strophe.umd.js:1875
(匿名) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send(异步)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:342
sendPresence @ ChatRoom.js:258
(匿名) @ ChatRoom.js:200
Promise.then(异步)
(匿名) @ ChatRoom.js:199
join @ ChatRoom.js:190
ue.join @ JitsiConference.js:529
connect @ conference.js:404
(匿名) @ conference.js:765
startConference @ conference.js:764
prejoinStart @ conference.js:852
async function(异步)
prejoinStart @ conference.js:850
(匿名) @ middleware.js:60
(匿名) @ middleware.js:24
(匿名) @ middleware.js:20
(匿名) @ middleware.js:15
(匿名) @ middleware.js:23
(匿名) @ middleware.js:20
(匿名) @ middleware.js:25
(匿名) @ middleware.js:74
(匿名) @ middleware.js:196
(匿名) @ middleware.js:198
(匿名) @ middleware.js:147
(匿名) @ middleware.web.js:107
(匿名) @ redux.js:475
_onJoinButtonClick @ Prejoin.js:208
f @ react-dom.production.min.js:15
_ @ react-dom.production.min.js:15
(匿名) @ react-dom.production.min.js:16
S @ react-dom.production.min.js:16
A @ react-dom.production.min.js:17
x @ react-dom.production.min.js:17
D @ react-dom.production.min.js:17
jn @ react-dom.production.min.js:81
ce @ react-dom.production.min.js:285
An @ react-dom.production.min.js:83
Tn @ react-dom.production.min.js:84
Dn @ react-dom.production.min.js:84
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
xn @ react-dom.production.min.js:82
Logger.js:154 2021-09-12T08:27:38.239Z [modules/statistics/AvgRTPStatsReporter.js] <m.addNext>:  bandwidth_upload - invalid value for idx: 0 undefined
o @ Logger.js:154
addNext @ AvgRTPStatsReporter.js:45
_calculateAvgStats @ AvgRTPStatsReporter.js:639
t._onLocalStatsUpdated @ AvgRTPStatsReporter.js:535
a.emit @ events.js:157
_updateLocalStats @ ConnectionQuality.js:472
a.emit @ events.js:157
h._processAndEmitReport @ RTPStatsCollector.js:400
h.processStatsReport @ RTPStatsCollector.js:674
(匿名) @ RTPStatsCollector.js:247
Promise.then(异步)
t @ RTPStatsCollector.js:241
setInterval(异步)
h.start @ RTPStatsCollector.js:258
b.startRemoteStats @ statistics.js:229
ue._acceptJvbIncomingCall @ JitsiConference.js:2120
ue.onIncomingCall @ JitsiConference.js:2024
a.emit @ events.js:152
onJingle @ strophe.jingle.js:172
run @ strophe.umd.js:1875
(匿名) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send(异步)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(匿名) @ strophe.umd.js:5257
setTimeout(异步)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:498
discoRoomInfo @ ChatRoom.js:304
onPresence @ ChatRoom.js:582
onPresence @ strophe.emuc.js:106
run @ strophe.umd.js:1875
(匿名) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send(异步)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
flush @ strophe.umd.js:2599
flush @ XmppConnection.js:342
sendPresence @ ChatRoom.js:258
(匿名) @ ChatRoom.js:200
Promise.then(异步)
(匿名) @ ChatRoom.js:199
join @ ChatRoom.js:190
ue.join @ JitsiConference.js:529
connect @ conference.js:404
(匿名) @ conference.js:765
startConference @ conference.js:764
prejoinStart @ conference.js:852
async function(异步)
prejoinStart @ conference.js:850
(匿名) @ middleware.js:60
(匿名) @ middleware.js:24
(匿名) @ middleware.js:20
(匿名) @ middleware.js:15
(匿名) @ middleware.js:23
(匿名) @ middleware.js:20
(匿名) @ middleware.js:25
(匿名) @ middleware.js:74
(匿名) @ middleware.js:196
(匿名) @ middleware.js:198
(匿名) @ middleware.js:147
(匿名) @ middleware.web.js:107
(匿名) @ redux.js:475
_onJoinButtonClick @ Prejoin.js:208
f @ react-dom.production.min.js:15
_ @ react-dom.production.min.js:15
(匿名) @ react-dom.production.min.js:16
S @ react-dom.production.min.js:16
A @ react-dom.production.min.js:17
x @ react-dom.production.min.js:17
D @ react-dom.production.min.js:17
jn @ react-dom.production.min.js:81
ce @ react-dom.production.min.js:285
An @ react-dom.production.min.js:83
Tn @ react-dom.production.min.js:84
Dn @ react-dom.production.min.js:84
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
xn @ react-dom.production.min.js:82
Logger.js:154 2021-09-12T08:27:38.242Z [modules/statistics/AvgRTPStatsReporter.js] <m.addNext>:  bandwidth_download - invalid value for idx: 0 undefined

**Comment by saghul** [comment]
The bridge channel was not opened, that's the source of the problem.

Do you have a proper TLS certificate? You can check the network tab to see the WS connection failing.

**Comment by kiroswu** [comment]
> The bridge channel was not opened, that's the source of the problem.
> 
> Do you have a proper TLS certificate? You can check the network tab to see the WS connection failing.

Hi Saghul, Thx for response. My environment is as below:
- self-hosted in internal server with a public ip;
- jitsi service is built in docker way and changed HTTPS_PORT to 20010  ;
- client testing is using latest edge browser, the client is another pc with jitsi public ip for request;

1、I tried to set JVB_WS_DOMAIN=124.16.138.126:20010 in .env file, an the /.jitsi-meet-cfg/jvb/jvb.conf already changed as below,but the WS still requested as wss://**localhost:8443**/xxxxx and failed. one cannot join a meeting.
    websockets {
        enabled = true
        domain = **"124.16.138.126:20010"**
        tls = true
        server-id = "172.24.0.5"
    }
![Snipaste_2021-09-13_09-41-20](https://user-images.githubusercontent.com/19584792/133011860-6aedb55b-776c-43ad-a891-e536f502a230.jpg)


2、Then I also tried to disable WebSocket connections, be set to fallback to HTTP polling for replace, then 2 users can join in a meeting and sharing screen etc. looks good, but 3 users failed to share screen as this issue title saied.
ENABLE_SCTP=1
ENABLE_COLIBRI_WEBSOCKET=0
ENABLE_XMPP_WEBSOCKET=0
![Snipaste_2021-09-13_08-54-49](https://user-images.githubusercontent.com/19584792/133011698-b949a2d1-6409-4bfb-a14d-e334b0fd461a.jpg)

![Snipaste_2021-09-13_08-55-11](https://user-images.githubusercontent.com/19584792/133011645-e7d68705-ee4e-4838-994c-8ec7d22be2e3.jpg)

according to https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-nat-or-on-a-lan-environment , added DOCKER_HOST_ADDRESS=124.16.138.126 still doesn't work.

Any suggest? or i miss something?

**Comment by kiroswu** [comment]
Updated. Now the ws is fine, but >=3 users shareing screen still gray.
![Snipaste_2021-09-13_10-04-52](https://user-images.githubusercontent.com/19584792/133013450-cb22cbd1-134b-4e9f-b933-016e360fc10f.jpg)

Currently 2 users:
![Snipaste_2021-09-13_10-06-30](https://user-images.githubusercontent.com/19584792/133014147-60210d40-c845-41db-b771-76f63de56a5f.jpg)

3users ,sharing screen became gray:
![Snipaste_2021-09-13_10-09-11](https://user-images.githubusercontent.com/19584792/133014152-3d1bbe0c-e90e-45cd-9e50-410e6c72d5a8.jpg)

**Comment by saghul** [comment]
Can you test using HTTPS on the standard port? I wonder if we have some bug there, since that's not a common case.

**Comment by kiroswu** [comment]
> Can you test using HTTPS on the standard port? I wonder if we have some bug there, since that's not a common case.

seems that 10000 udp port cause. Now PC web browser looks fine when >3users.

But ios safari cannot reach to service normal, response **'Connection error. your device maybe offline or our servers may be experiencing problems'**

**Comment by kiroswu** [comment]
> Can you test using HTTPS on the standard port? I wonder if we have some bug there, since that's not a common case.

One more thing,interface_config.js and config.js is auto-generated by docker containers so how do i configure watermark +requireDisplayName in docker .env way?

Remove the Jitsi watermark. Normally you would edit in interface_config.js
SHOW_JITSI_WATERMARK
SHOW_WATERMARK_FOR_GUESTS
JITSI_WATERMARK_LINK
Require users to enter a display name. Normally you would edit config.js
requireDisplayName=true

**Comment by saghul** [comment]
Please don't mix different issues / questions. The original problem is now solved, so let's close this.

You can ask questions about how to customize the configuration in our community.

**Comment by haofanning** [comment]
> > Can you test using HTTPS on the standard port? I wonder if we have some bug there, since that's not a common case.
> 
> seems that 10000 udp port cause. Now PC web browser looks fine when >3users.
> 
> But ios safari cannot reach to service normal, response **'Connection error. your device maybe offline or our servers may be experiencing problems'**

遇到了同样的问题，你解决了吗？这个10000的端口是怎么处理的，现在三个人同时进入，iOS端看不到人。
