### ISSUE TITLE
jitsi-meet-prosody's dependency on prosody >= 0.11 breaks upgrade path from Ubuntu 18.04 -> 20.04

### ISSUE THREAD

**Issue by tpo** [jitsi/jitsi-meet#9928]
### Description:

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

# apt-get install jitsi-meet-prosody 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet-prosody : Depends: prosody (>= 0.11.0) or
                               prosody-trunk but it is not installable or
                               prosody-0.11 but it is not installable
E: Unable to correct problems, you have held broken packages.

# do-release-upgrade --allow-third-party
Checking for a new Ubuntu release
Please install all available updates for your release before upgrading.
```

That means that at this point there is no middle-of-the-road way forward to upgrade jitsi-meet and/or the Ubuntu distro.
 
### Steps to reproduce:

See above.

### Expected behavior:

It should be possible to upgrade Ubuntu and/or Jitsi, without needing to deinstall Jitsi or do package-by-package manual upgrades. 

### Actual behavior:

See above

### Server information:

- Jitsi Meet version: 2.0.6173-1
- Operating System: Ubuntu 18.04

### Client information:

irrelevant in this context

### Additional information:

I'll try to update this bug in case I find a workaround.

**Comment by damencho** [comment]
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#for-ubuntu-1804-add-prosody-package-repository

And make sure your jitsi-meet prosody config has `storage = 'memory'`.

**Comment by tpo** [comment]
:+1: @damencho , thanks a lot!

**Comment by tpo** [comment]
for whomever is following this same path as me. The next hole I fell into is #8388
