### ISSUE TITLE
Add input sensitivity / microphone threshold feature

### ISSUE THREAD

**Issue by alxpettit** [jitsi/jitsi-meet#9934]
In Discord, and a number of other VOIP apps, there is a feature that allows the user to cap minimum volume at an arbitrary threshold. If dB are beneath this threshold, the mic switches off. This means that you can easily tune it so that background noise such as fans, typing, and breathing are ignored by your microphone.

![image](https://user-images.githubusercontent.com/28266167/133160655-80e19a9c-99e2-46b8-9980-b5c9a0a75a14.png)

To make Jitsi Meet more useful for larger business meetings, and to stay competitive with apps like Discord, it seems like a good idea to implement this feature.

**Comment by Wunderharke** [comment]
Is there progress on this? I want to use Jitisi as Discord replacement and this feature would be very much appreciated!

**Comment by alxpettit** [comment]
bump

**Comment by saghul** [comment]
I'm not sure this is possible with web APIs.

**Comment by alxpettit** [comment]
It must be possible somehow, as other people got it working. Does Discord use something other than web APIs?

**Comment by saghul** [comment]
Do they implement that in the browser?

**Comment by alxpettit** [comment]
Yup :)

**Comment by alxpettit** [comment]
This issue is still relevant today. Should I re-open it?

**Comment by schoerg** [comment]
yes

**Comment by alxpettit** [comment]
I don't have privileges to do that, though. :/

I guess I'll just make another identical issue.
