### ISSUE TITLE
[Android] Unable to launch Jitsi Meet on Android 12

### ISSUE THREAD

**Issue by moskaland** [jitsi/jitsi-meet#9942]
### Description:

I'm not able to launch Jitsi Meet on Android 12 (Android S release candidate/beta 5).  Application hang on splash screen. The same behaviour I got when I launch custom app using latest Jitsi SDK. Both Jitsi Meet and SDK works fine on older Android versions. 

### Steps to reproduce:

1. Open Jitsi Meet on Android 12

### Expected behavior:

App launch without and issue, like on previous version of  Android

### Actual behavior:

App freeze on Splash screen
<img width="386" alt="Screenshot 2021-09-14 at 22 36 14" src="https://user-images.githubusercontent.com/75085107/133331392-ba13a451-3807-4437-bc93-b72df5e50ff3.png">

### Client information:

- Browser / app version: Jitsi Meet 21.3.0 (213000) (also reproducible with app using SDK v 3.8.0)
- Operating System:  Android 12, beta 5, launch on emulator

**Comment by saghul** [comment]
Can you try our beta version on the store (version 21.4.0) ? I've been using it on Android 12 for a while already.

**Comment by moskaland** [comment]
Unfortunately, on 21.4.0 I encounter the same behaviour - just splash screen and app never enter lobby. Maybe it's related with the fact that I'm launching it on an emulator, yet on previous versions of Android emulators work just fine with Jitsi.

**Comment by saghul** [comment]
Can you please grab `adb logcat` logs? I cannot reproduce it on a physical device.

**Comment by moskaland** [comment]
Logs seems to lead in some direction: `W/org.jitsi.meet: Unexpected CPU variant for X86 using defaults: x86_64`
Does Jitsi supports x86_64 architecture?

full relevant logs:
I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.jitsi.meet/.MainActivity bnds=[35,84][237,337]} from uid 10129
I/ActivityManager: Start proc 16297:org.jitsi.meet/u0a147 for pre-top-activity {org.jitsi.meet/org.jitsi.meet.MainActivity}
W/org.jitsi.meet: Unexpected CPU variant for X86 using defaults: x86_64
E/org.jitsi.meet: Not starting debugger since process cannot load the jdwp agent.
V/GraphicsEnvironment: ANGLE Developer option for 'org.jitsi.meet' set to: 'default'
W/org.jitsi.meet: Unsupported class loader
W/org.jitsi.meet: Unsupported class loader
D/SoLoader: adding application source: com.facebook.soloader.c[root = /data/app/~~mMvXWt9L62XCWYwA8sAIyg==/org.jitsi.meet-nEU8d1hKW7dcRHdQNOe_0g==/lib/x86_64 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.a[root = /data/data/org.jitsi.meet/lib-main flags = 1]
D/SoLoader: Preparing SO source: com.facebook.soloader.c[root = /data/app/~~mMvXWt9L62XCWYwA8sAIyg==/org.jitsi.meet-nEU8d1hKW7dcRHdQNOe_0g==/lib/x86_64 flags = 0]
D/SoLoader: Preparing SO source: com.facebook.soloader.a[root = /data/data/org.jitsi.meet/lib-main flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/org.jitsi.meet/lib-main
I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/org.jitsi.meet/lib-main
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/org.jitsi.meet/lib-main
D/SoLoader: libreactnativejni.so found on /data/data/org.jitsi.meet/lib-main
D/SoLoader: libglog_init.so found on /data/data/org.jitsi.meet/lib-main
D/SoLoader: libglog.so found on /data/data/org.jitsi.meet/lib-main
D/SoLoader: libc++_shared.so found on /data/data/org.jitsi.meet/lib-main
I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app org.jitsi.meet
D/SoLoader: libc.so not found on /data/data/org.jitsi.meet/lib-main
D/SoLoader: libc.so not found on /data/app/~~mMvXWt9L62XCWYwA8sAIyg==/org.jitsi.meet-nEU8d1hKW7dcRHdQNOe_0g==/lib/x86_64
I/ActivityTaskManager: Displayed org.jitsi.meet/.MainActivity: +640ms
W/InputManager-JNI: Input channel object '8f5abf4 Splash Screen org.jitsi.meet (client)' was disposed without first being removed with the input manager!

**Comment by saghul** [comment]
> Logs seems to lead in some direction: `W/org.jitsi.meet: Unexpected CPU variant for X86 using defaults: x86_64`
> Does Jitsi supports x86_64 architecture?

It does. That is a harmless log. I see React Native being instantiated, but I have no idea why it doesn't make any progress.

**Comment by moskaland** [comment]
True, I just run test on emulator with Android 11 x86_64 and works just fine.

**Comment by moskaland** [comment]
@saghul I was able to test it on real device - fortunately is working fine on Pixel 4a. 
Unfortunately it is still impossible to open Jitsi app(v21.4) nor use sdk (v 3.10.0) on Android Studio emulator with Android 12.    As we do not know what causing it I'm afraid it could be reproducible on some other real device we do not have access to.

**Comment by saghul** [comment]
Thanks for the feedback. I'll give it a try when have some extra time.

**Comment by moskaland** [comment]
Thanks 🙇

**Comment by Bresiu** [comment]
I have same problem. Any update on this?

**Comment by saghul** [comment]
Can you folks give https://github.com/jitsi/jitsi-meet/pull/10065 a try?

**Comment by moskaland** [comment]
Looks promising, JitsitMeet App `v21.4.1` is working fine!
 @saghul could you please deploy sdk `v3.10.3` for Android platform? seems that it's only available on iOS, last version available for Android is `3.10.0` and it's without #10065. Then I'd be able to test it and hopefully close an issue 🤞

**Comment by saghul** [comment]
Sure thing. @tmoldovan8x8 can you please release 3.10.1 (the patch releases need not align across platforms) when you get a chance please?

**Comment by saghul** [comment]
This has been done already.
