### ISSUE TITLE
video not working between two user , here is my jvb log

### ISSUE THREAD

**Issue by Malik464** [jitsi/jitsi-meet#9951]
JVB 2021-09-15 16:46:32.641 INFO: [40] [confId=5b0d3cb740639979 gid=49735 stats_id=Hazel-mbx componentId=1 conf_name=test@conference.meet.dev.weconnect.chat ufrag=4lbdo1ffl5k0lp name=stream-329e2052 epId=329e2052 local_ufrag=4lbdo1ffl5k0lp] MergingDatagramSocket.close#142: Closing.
JVB 2021-09-15 16:46:32.641 INFO: [40] [confId=5b0d3cb740639979 epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] Endpoint.expire#1042: Expired.
JVB 2021-09-15 16:46:32.644 INFO: [38] [confId=8756331a2fc6856d gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] EndpointConnectionStatusMonitor.start#58: Starting connection status monitor
JVB 2021-09-15 16:46:32.644 INFO: [38] Videobridge.createConference#244: create_conf, id=8756331a2fc6856d gid=49735
JVB 2021-09-15 16:46:32.645 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 local_ufrag=dts1i1ffl5kk65 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65] Agent.gatherCandidates#622: Gathering candidates for component stream-329e2052.RTP.
JVB 2021-09-15 16:46:32.652 WARNING: [23] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference df7200236083d2b4)
JVB 2021-09-15 16:46:32.655 INFO: [44] [confId=8756331a2fc6856d gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.dominantSpeakerChanged#424: ds_change ds_id=329e2052
JVB 2021-09-15 16:46:32.659 WARNING: [40] [confId=8756331a2fc6856d gid=49735 type=video conf_name=test@conference.meet.dev.weconnect.chat] ChannelShim.lambda$setSourceGroups$2#289: Ignoring source group with <2 sources: <ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>
JVB 2021-09-15 16:46:32.660 WARNING: [40] MediaSourceFactory.getSourceSsrcs#399: Unprocessed source groups: Optional[<ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>]
JVB 2021-09-15 16:46:32.660 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Endpoint.setTransportInfo#679: Ignoring empty DtlsFingerprint extension: <transport xmlns='urn:xmpp:jingle:transports:ice-udp:1'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' required='false'/></transport>
JVB 2021-09-15 16:46:33.447 WARNING: [40] [confId=8756331a2fc6856d gid=49735 type=video conf_name=test@conference.meet.dev.weconnect.chat] ChannelShim.lambda$setSourceGroups$2#289: Ignoring source group with <2 sources: <ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>
JVB 2021-09-15 16:46:33.447 WARNING: [40] MediaSourceFactory.getSourceSsrcs#399: Unprocessed source groups: Optional[<ssrc-group xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' semantics='SIM'/>]
JVB 2021-09-15 16:46:33.448 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] DtlsTransport.setSetupAttribute#120: The remote side is acting as DTLS client, we'll act as server
JVB 2021-09-15 16:46:33.448 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 local_ufrag=dts1i1ffl5kk65 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] IceTransport.startConnectivityEstablishment#188: Starting the Agent without remote candidates.
JVB 2021-09-15 16:46:33.448 INFO: [40] [confId=8756331a2fc6856d gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65 epId=329e2052 local_ufrag=dts1i1ffl5kk65] Agent.startConnectivityEstablishment#713: Start ICE connectivity establishment.
JVB 2021-09-15 16:46:33.449 INFO: [40] [confId=8756331a2fc6856d gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65 epId=329e2052 local_ufrag=dts1i1ffl5kk65] Agent.initCheckLists#949: Init checklist for stream stream-329e2052
JVB 2021-09-15 16:46:33.449 INFO: [40] [confId=8756331a2fc6856d gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65 epId=329e2052 local_ufrag=dts1i1ffl5kk65] Agent.setState#923: ICE state changed from Waiting to Running.
JVB 2021-09-15 16:46:33.449 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 local_ufrag=dts1i1ffl5kk65 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] IceTransport.iceStateChanged#327: ICE state changed old=Waiting new=Running
JVB 2021-09-15 16:46:33.449 INFO: [40] [confId=8756331a2fc6856d gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65 epId=329e2052 local_ufrag=dts1i1ffl5kk65] ConnectivityCheckClient.startChecks#149: Start connectivity checks.
JVB 2021-09-15 16:46:34.589 WARNING: [23] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 5b0d3cb740639979)
JVB 2021-09-15 16:46:36.460 WARNING: [23] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 5b0d3cb740639979)
JVB 2021-09-15 16:46:38.451 WARNING: [25] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 5b0d3cb740639979)
JVB 2021-09-15 16:46:41.548 INFO: [18] HealthChecker.run#171: Performed a successful health check in PT0S. Sticky failure: false
JVB 2021-09-15 16:46:42.447 WARNING: [23] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 5b0d3cb740639979)
JVB 2021-09-15 16:46:50.445 WARNING: [25] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 5b0d3cb740639979)
JVB 2021-09-15 16:46:51.289 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] AbstractEndpoint.expire#275: Expiring.
JVB 2021-09-15 16:46:51.289 INFO: [44] [confId=8756331a2fc6856d gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.dominantSpeakerChanged#424: ds_change ds_id=null
JVB 2021-09-15 16:46:51.289 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] Endpoint.expire#1024: Spent 0 seconds oversending
JVB 2021-09-15 16:46:51.289 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] Transceiver.teardown#324: Tearing down
JVB 2021-09-15 16:46:51.290 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] RtpReceiverImpl.tearDown#339: Tearing down
JVB 2021-09-15 16:46:51.290 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] RtpSenderImpl.tearDown#315: Tearing down
JVB 2021-09-15 16:46:51.292 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] DtlsTransport.stop#186: Stopping
JVB 2021-09-15 16:46:51.292 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 local_ufrag=dts1i1ffl5kk65 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] IceTransport.stop#241: Stopping
JVB 2021-09-15 16:46:51.292 INFO: [40] [confId=8756331a2fc6856d gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65 epId=329e2052 local_ufrag=dts1i1ffl5kk65] Agent.setState#923: ICE state changed from Running to Terminated.
JVB 2021-09-15 16:46:51.292 INFO: [40] [confId=8756331a2fc6856d gid=49735 stats_id=Hazel-mbx componentId=1 conf_name=test@conference.meet.dev.weconnect.chat ufrag=dts1i1ffl5kk65 name=stream-329e2052 epId=329e2052 local_ufrag=dts1i1ffl5kk65] MergingDatagramSocket.close#142: Closing.
JVB 2021-09-15 16:46:51.293 INFO: [40] [confId=8756331a2fc6856d epId=329e2052 gid=49735 stats_id=Hazel-mbx conf_name=test@conference.meet.dev.weconnect.chat] Endpoint.expire#1042: Expired.
JVB 2021-09-15 16:46:51.548 INFO: [18] HealthChecker.run#171: Performed a successful health check in PT0S. Sticky failure: false
JVB 2021-09-15 16:46:53.155 WARNING: [25] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 8756331a2fc6856d)
JVB 2021-09-15 16:46:55.149 WARNING: [25] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 8756331a2fc6856d)
JVB 2021-09-15 16:46:59.155 WARNING: [23] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 8756331a2fc6856d)
JVB 2021-09-15 16:47:01.548 INFO: [18] HealthChecker.run#171: Performed a successful health check in PT0S. Sticky failure: false
JVB 2021-09-15 16:47:06.645 WARNING: [25] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 5b0d3cb740639979)
JVB 2021-09-15 16:47:07.653 WARNING: [23] ColibriWebSocketServlet.createWebSocket#144: Received request for a nonexistent endpoint: 329e2052(conference 8756331a2fc6856d)
JVB 2021-09-15 16:47:11.523 INFO: [15] VideobridgeExpireThread.expire#140: Running expire()
JVB 2021-09-15 16:47:11.523 INFO: [15] VideobridgeExpireThread.expire#146: Conference df7200236083d2b4 should expire, expiring it
JVB 2021-09-15 16:47:11.523 INFO: [15] VideobridgeExpireThread.expire#146: Conference 8756331a2fc6856d should expire, expiring it
JVB 2021-09-15 16:47:11.523 INFO: [15] VideobridgeExpireThread.expire#146: Conference 5b0d3cb740639979 should expire, expiring it
JVB 2021-09-15 16:47:11.524 INFO: [53] [confId=df7200236083d2b4 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.expire#501: Expiring.
JVB 2021-09-15 16:47:11.524 INFO: [53] [confId=df7200236083d2b4 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] EndpointConnectionStatusMonitor.stop#66: Stopped
JVB 2021-09-15 16:47:11.525 INFO: [53] [confId=df7200236083d2b4 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.updateStatisticsOnExpire#563: expire_conf,duration=82,has_failed=false,has_partially_failed=false
JVB 2021-09-15 16:47:11.525 INFO: [52] [confId=8756331a2fc6856d gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.expire#501: Expiring.
JVB 2021-09-15 16:47:11.525 INFO: [52] [confId=8756331a2fc6856d gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] EndpointConnectionStatusMonitor.stop#66: Stopped
JVB 2021-09-15 16:47:11.526 INFO: [52] [confId=8756331a2fc6856d gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.updateStatisticsOnExpire#563: expire_conf,duration=39,has_failed=false,has_partially_failed=false
JVB 2021-09-15 16:47:11.529 INFO: [56] [confId=5b0d3cb740639979 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.expire#501: Expiring.
JVB 2021-09-15 16:47:11.529 INFO: [56] [confId=5b0d3cb740639979 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] EndpointConnectionStatusMonitor.stop#66: Stopped
JVB 2021-09-15 16:47:11.530 INFO: [56] [confId=5b0d3cb740639979 gid=49735 conf_name=test@conference.meet.dev.weconnect.chat] Conference.updateStatisticsOnExpire#563: expire_conf,duration=59,has_failed=false,has_partially_failed=false
JVB 2021-09-15 16:47:11.548 INFO: [18] HealthChecker.run#171: Performed a successful health check in PT0S. Sticky failure: false

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

You had disabled p2p or? Does it work with 3 participants?

**Comment by Malik464** [comment]
No it's not working, also screen share not working

**Comment by damencho** [comment]
Check https://jitsi.org/qi#advanced-configuration
This question was answered in the forum many times.

**Comment by Malik464** [comment]
Okay thanks
