### ISSUE TITLE
VideoQualityLayerLookup.transform#44: Unable to find encoding matching packet! 

### ISSUE THREAD

**Issue by Xetoxyc** [jitsi/jitsi-meet#9952]
We are experiencing strange behaviour with Firefox and the error above. 

Setup:
3 Participiant (2 are using Chome, 1 is using Firefox, All up to date)
1 Meet (latest release, single server, h264)

Noone has bad connection or low bandwidth.

The Firefox user is always starting to stutter for the chrome users for like 1-2 seconds then its fine for 3-6 seconds and then its starting over and over again.

When the lagg is happening the following log entries are occuring for like 50 times.
If the user is disabling his video the issue will stop immedialty.

```
JVB 2021-09-15 20:13:28.526 WARNING: [64] [confId=14ab7fb946a0add7 epId=f17ad97f gid=175 stats_id=Eve-zWi conf_name=ca6b033449f40743d VideoQualityLayerLookup.transform#44: Unable to find encoding matching packet! packet=RtpPacket: PT=99, Ssrc=4121484905, SeqNum=6773, 91247507 has encodings:
  primary_ssrc=2578856740,secondary_ssrcs={},layers=
    subjective_quality=0,temporal_id=0,spatial_id=-1
    subjective_quality=1,temporal_id=1,spatial_id=-1
    subjective_quality=2,temporal_id=2,spatial_id=-1
JVB 2021-09-15 20:13:28.661 WARNING: [68] [confId=14ab7fb946a0add7 epId=f17ad97f gid=175 stats_id=Eve-zWi conf_name=ca6b033449f40743d VideoQualityLayerLookup.transform#44: Unable to find encoding matching packet! packet=RtpPacket: PT=99, Ssrc=4121484905, SeqNum=6774, 05476773 has encodings:
  primary_ssrc=2578856740,secondary_ssrcs={},layers=
    subjective_quality=0,temporal_id=0,spatial_id=-1
    subjective_quality=1,temporal_id=1,spatial_id=-1
    subjective_quality=2,temporal_id=2,spatial_id=-1
```

**Comment by JonathanLennox** [comment]
I believe this is due to a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1727196.  It should be fixed in Firefox 93. 
Can you see if the problem occurs with the current Firefox Beta?

**Comment by Xetoxyc** [comment]
We did not experienced any problems with 93. But we told our customer to test it with his system.

Thank you for the quick response
