### ISSUE TITLE
jitsi-meet unmet package dependencies Ubuntu 18.06 or 18.05 LTS

### ISSUE THREAD

**Issue by Francis-Yao** [jitsi/jitsi-meet#9954]
### Description:

apt on fresh ubuntu 18.05 LTS or 18.06 LTS can't install jitsi

### Steps to reproduce:
1. echo 'deb https://download.jitsi.org stable/' | sudo tee /etc/apt/sources.list.d/jitsi-stable.list

2.wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add - 

3.sudo apt-get install apt-transport-https 

4.sudo apt update 

5.sudo apt upgrade
6.sudo apt-get -y install jitsi-meet

### Expected behavior:

The same instructions worked a few days ago when I setup a test server. Same OS.

### Actual behavior:
#apt-get install jitsi-meet
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jitsi-meet : Depends: jitsi-meet-prosody (= 1.0.5307-1) but it is not going to be installed
              Recommends: jitsi-meet-turnserver (= 1.0.5307-1) but it is not going to be installed or
                          apache2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

#5872

### Server information:

- Jitsi Meet version: jitsi-meet-prosody (= 1.0.5307-1), jitsi-meet-turnserver (= 1.0.5307-1)
- Operating System:Ubuntu 18.06 or 18.05 LTS

### Client information:

- Browser / app version:
- Operating System:

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

The solution is described here: https://github.com/jitsi/jitsi-meet/issues/5872#issuecomment-917506622

**Comment by Francis-Yao** [comment]
The solution is described here: #5872 (comment) is NOT solved yet. Thanks a lot for your quick reply.

**Comment by damencho** [comment]
What do you mean?
