### ISSUE TITLE
[Android sdk] JitsiMeetView needs and Activity context, but this is not compatible with ReactNative SoLoader.

### ISSUE THREAD

**Issue by jgorozco** [jitsi/jitsi-meet#9956]
### Description:

This issue is related with this thread
https://github.com/facebook/SoLoader/issues/63

### Steps to reproduce:

Create an Android application using last jitsi SDK version (3.9, but tested with 3.8 too) and add LeakCanary (https://square.github.io/leakcanary/) to dump all memory leaks.

1. Open the app
2. Create an JitsiMeetView working. 
3. Close the application

### Expected behavior:

All instances release properly

### Actual behavior:

Leak canary return something like this.
'''
    ┬───
    │ GC Root: Local variable in native code
    │
    ├─ dalvik.system.PathClassLoader instance
    │    Leaking: NO (SoLoader↓ is not leaking and A ClassLoader is never leaking)
    │    ↓ PathClassLoader.runtimeInternalObjects
    ├─ java.lang.Object[] array
    │    Leaking: NO (SoLoader↓ is not leaking)
    │    ↓ Object[].[1432]
    ├─ com.facebook.soloader.SoLoader class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static SoLoader.sBackupSoSources
    │                      ~~~~~~~~~~~~~~~~
    ├─ com.facebook.soloader.UnpackingSoSource[] array
    │    Leaking: UNKNOWN
    │    Retaining 4 bytes in 1 objects
    │    ↓ UnpackingSoSource[].[0]
    │                          ~~~
    ├─ com.facebook.soloader.ApkSoSource instance
    │    Leaking: UNKNOWN
    │    Retaining 139734 bytes in 2777 objects
    │    mContext instance of {my app id}.MyActivity with mDestroyed = true
    │    ↓ ApkSoSource.mContext
    │                  ~~~~~~~~
    ╰→ {my app id}.MyActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because {my app id}.MyActivity received
    ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 138828 bytes in 2736 objects
    ​     key = 18ee22b5-7e11-4791-ace2-31c9100d5100
    ​     watchDurationMillis = 5378
    ​     retainedDurationMillis = 367
    ​     mApplication instance of {my app id}
    ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper, not wrapping known Android context
    
    METADATA
    
    Build.VERSION.SDK_INT: 29
    Build.MANUFACTURER: Xiaomi
    LeakCanary version: 2.5
    App process name: {my app id}
    Stats: LruCache[maxSize=3000,hits=2964,misses=83823,hitRate=3%]
    RandomAccess[bytes=4430896,reads=83823,travel=41969175027,range=27019033,size=32879351]
    Analysis duration: 29543 ms

'''
### Server information:

N/A

### Client information:

 Build.VERSION.SDK_INT: 29
    Build.MANUFACTURER: Xiaomi
    LeakCanary version: 2.5

### Additional information:

As I can see.
- JitsiMeetView needs a Context but instanceOf JitsiMeetActivityInterface (so,must be an activity)
- Then BaseReactView needs a Context too, but cast to activity too  (    ReactInstanceManagerHolder.initReactInstanceManager((Activity)context);)
- But inside SoLoader.init  (in class ReactInstanceManagerHolder is init with activity (            SoLoader.init(activity, false);
)
- and i think this react native class want an application context, not an activity context.

Thanks a lot for your time. I hope it helps.

**Comment by saghul** [comment]
Good catch! Can you please give this patch a try? https://github.com/jitsi/jitsi-meet/pull/9957 (I have not tested it myself yet)

**Comment by jgorozco** [comment]
Hi! wow really fast answer!

I do something similar. But for testing i think is ok.

I had in my project a JitsiMeetView2 (because i want to remove the permission stuff, i want to made for my self)

In this class i create the view this way.
`
   companion object {
        fun constructJitsiMeetView(context: Context):JitsiMeetView2{
            SoLoader.init(context.applicationContext, false)
            return JitsiMeetView2(context)
        }

`

And i just check that now is working, there is no leak.
