### ISSUE TITLE
Hide Scrollbar in chat text input

### ISSUE THREAD

**Issue by jluisfa** [jitsi/jitsi-meet#9958]
In Chrome 93 macOS 11.6, in meet.jit.si chat text input, we see this:

<img width="296" alt="1" src="https://user-images.githubusercontent.com/32515675/133627114-149a763f-9ea0-441a-90d0-3361e890c342.png">

and

<img width="298" alt="2" src="https://user-images.githubusercontent.com/32515675/133627146-ba674418-ca56-46ca-aca2-caf9519e4121.png">

(enlarged)

<img width="118" alt="3" src="https://user-images.githubusercontent.com/32515675/133628356-da3b0318-96a9-4e97-9fbf-0faf3c7ce3ad.png">

Suggestion: Hide Scrollbar in <textarea id="usermsg”> when it's empty.

Thanks!

**Comment by saghul** [comment]
👍  @vp8x8 can you please take a look when you have some time?

**Comment by jluisfa** [comment]
This style works for me:

/* Hide scrollbar for Chrome, Safari and Opera */
#usermsg::-webkit-scrollbar {
  display: none;
}
/* Hide scrollbar for IE, Edge add Firefox */
#usermsg {
  -ms-overflow-style: none;
  scrollbar-width: none; /* Firefox */
}

**Comment by vp8x8** [comment]
@saghul Sure I'll add it to my list.

**Comment by jluisfa** [comment]
Thanks @saghul and @vp8x8
