### ISSUE TITLE
Unhandled JS Exception: Can't find variable: window for master branch lib build

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#9971]
We made upgrade for the jitsi lib, all is fine while compilation.

But on start JitsiMeetView we have black screen
and console is full of the following error

main.jsbundle:2675:4
Unhandled JS Exception: Can't find variable: window

**Comment by saghul** [comment]
Do you have a full backtrace? What commit did you build?

**Comment by iospro** [comment]
Master branch
Commit 7ff3b669ee0a9bbac86ff2efa513a6c011325857

dispatch WatchStateChanged: {
    state = WCSessionActivationStateActivated;
}
[JitsiMeetSDK] Sending `WatchStateChanged` with no listeners registered.
[WC] WCSession counterpart app not installed
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0918 18:08:30.798935 1804185600 NativeToJsBridge.cpp:160] Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
[JitsiMeetSDK] Unhandled JS Exception: Can't find variable: window

/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:825:59
v@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:19:2984
/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:19:3676
v@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:17:38
v@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:7:109
v@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:6:30
v@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:1474
d@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2:876
global code@/var/containers/Bundle/Application/640AE9E3-06BE-4A18-A1D3-8A74EBB54172/OneFChat-test.app/Frameworks/JitsiMeetSDK.framework/main.jsbundle:2675:4
[JitsiMeetSDK] FATAL ERROR: RCTFatalException: Unhandled JS Exception: Can't find variable: window

**Comment by saghul** [comment]
I'll take a look, thanks for the report!

In the meantime you can use the mobile-21.4 branch, which is the next release branch, where all latest betas have built from.
