### ISSUE TITLE
Jit.si pauses screenshare, randomly

### ISSUE THREAD

**Issue by troler36** [jitsi/jitsi-meet#9972]
### Description:

When using screenshare the bandwith auto-save feature is to sensitive. My networks is 70 Mbit/s and it turns it off

### Steps to reproduce:

1. Join a jit.si call
2. Share your screen

### Expected behavior:

It should show the screen without any pauses unless nothing happens

### Actual behavior:

It pauses at random moments

### Server information:

- Jitsi Meet version: 2.0.6293

### Client information:

- Browser / app version: Firefox 92.0 
- Operating System: Arch Linux

**Comment by JYamihud** [comment]
Can confirm the issue

**Comment by damencho** [comment]
We are aware of some FF issues and we are working on fixing those, seems those will fix the issue you experience
For example this one https://github.com/jitsi/jicofo/commit/974617ac9bfd60a7725531abf8ec2d51fd8439b3
