### ISSUE TITLE
jitsi  translation

### ISSUE THREAD

**Issue by sun-hao** [jitsi/jitsi-meet#998]
i have a po file ,eg:test.po,now i want convert  test.po to test.json.
i use commond po2json to convert,but po2json shows  no template.
so  where can i get the template?
thank you!

**Comment by sun-hao** [comment]
@damencho  can you help me

**Comment by damencho** [comment]
Please use the mailinglist for question, before opening issues.
For translation we currently use pootle: http://translate.jitsi.org/

**Comment by sun-hao** [comment]
@damencho  thank you for your help
