### ISSUE TITLE
[Mobile] All buttons except `End call` are invisible in Jitsi Meet app in Dark Mode on Xiaomi

### ISSUE THREAD

**Issue by ankar84** [jitsi/jitsi-meet#9981]
### Description:

All buttons except `End call` are invisible in Jitsi Meet app on Xiaomi smartphone in Dark Mode (Light Mode is all right)

### Steps to reproduce:

1. Setup Dark Mode
2. Start or Join a call in Jitsi Meet app from Play Store
3. See that all buttons except `End Call` button almost invisible
### Expected behavior:

All buttons are visible both in Light mode and Dark mode

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/134133573-90ffe96a-22ef-4443-82c7-d6539315cb31.png)

### Server information:

- Jitsi Meet version: 2.0.6293 (2021-09-10)
- Operating System: Ubuntu 18.04

### Client information:

- Browser / app version: 21.3.0 build 8195380
- Operating System: Android 11

### Additional information:

Tested on Xiaomi Mi 9SE - have issue
Tested on Samsung S8 - no problem

So, it could be some Xiaomi related (maybe MIUI) problem.

**Comment by saghul** [comment]
What MIUI version is that?

**Comment by ankar84** [comment]
> What MIUI version is that?

Latest - 12.5.1

**Comment by saghul** [comment]
I cannot reproduce it with Android's dark mode (tested on Android 12). I'll try to get a colleague with MIUI to test.

**Comment by ankar84** [comment]
> I cannot reproduce it with Android's dark mode (tested on Android 12). I'll try to get a colleague with MIUI to test.

Thank you. Saul!
I confirm that it's not a global Android issue, but local Xiaomi (MIUI) issue.

**Comment by horymury** [comment]
tried on MIUI 12.0.1 dark mode. Does not repro.

**Comment by ahinrichs** [comment]
I have the same issue here. Also on MIUI 12...

App 21.4 the buttons are black on dark gray background. 21.5 it's black on black...

**Comment by saghul** [comment]
Not sure what Xiaomi does, but we don't have this issue with vanilla Android...

**Comment by ankar84** [comment]
It is definitely bug of dark mode of Xiaomi devices (MiUi in general I guess) so I'm closing yhat issue.

If you want to fix that issue, you can do it by disabling dark mode for specific application in smartphone settings.

**Comment by saghul** [comment]
I'd love to fix it in our app, but we set colors explicitly, not sure how to handle this XIaomi thing. If anyone has ideas I'm all ears!
