### ISSUE TITLE
Facing echo in iOS to iOS and iOS to Android 

### ISSUE THREAD

**Issue by MeetSoniBV** [jitsi/jitsi-meet#9982]
Hello Jitsi Team, 

Our team is using Jitsi SDK for Audio/Video calling functionality in our app where we stuck at a point, we are continuously facing echo problem while calling, we have checked all different version of Jitsi SDK but still facing same problem.  

#9963 #9982

**Comment by saghul** [comment]
Don't open duplicate issues.

**Comment by MeetSoniBV** [comment]
Ok, but please do suggest how we can tackel this issue.
