### ISSUE TITLE
[iOS] Audio is not working when joining a call from CallKit when other Jitsi call is in progress

### ISSUE THREAD

**Issue by atereshkov** [jitsi/jitsi-meet#9983]
### Description:

Hi everyone,
there’s an issue we’re experiencing using JitsiMeetSDK on iOS.

Our setup is working fine with the CallKit using JMCallKitProxy, we’re able to answer a call from system CallKit and connect to Jitsi, but the problem with lost audio (only audio, video is working) appears when user answers second call reported by JMCallKitProxy.reportNewIncomingCall while already participating in a call. Other participants can not hear user who has joined to a second call using iOS device, but they are able to see video from this user.

### Steps to reproduce:

1. Start a new call and join it
2. Join to a second call that has been reported by `JMCallKitProxy.reportNewIncomingCall(...)` (in our app it triggered by voip notification)

### Expected behavior:

User joined second call, video and audio is working.

### Actual behavior:

User joined second call, **audio is not working**, but **video is working**.

### Server information:

N/A

### Client information:

- Browser / app version: iOS 1.4, JitsiMeetSDK 3.3.0
- Operating System: iOS

### Additional information:

Here's MRE:

```
// MARK: JitsiMeetProvider

class JitsiMeetProvider: JMCallKitListener {

    func reportIncomingCall(uuid: UUID, payload: MeetPayload, completion: ((Error?) -> Void)?) {
        guard !JMCallKitProxy.hasActiveCallForUUID(uuid.uuidString) else { return }
        
        configureAudioSession()
        
        JMCallKitProxy.reportNewIncomingCall(UUID: uuid, handle: handle, displayName: name, hasVideo: true) { [weak self] error in
            completion?(error)
        }
    }

    func configureAudioSession() {
        let session = AVAudioSession.sharedInstance()
        do {
            try session.setCategory(.playAndRecord)
            try session.setMode(.voiceChat)
            try session.setActive(true)
        } catch let error {
            Swift.print("configureAudioSession error: \(error)")
        }
    }
    
    func performAnswerCall(UUID: UUID) {
        let meetOptions = MeetOptions(payload: call.payload, answer: true)
        
        AppDelegate.shared.router?.answerCall(options: meetOptions) { [weak self] in
            // Call is answered and MeetingView is started showing, establish connection with our backend ...
        }
    }
}

// MARK: AppRouter

class AppRouter {
    
    func answerCall(options: MeetOptions, completion: (() -> Void)?) {
        cancelCall { [weak self] in
            let vc = meetingRouter.initializeMeetingView(options: options) // initialize MeetingViewController with JitsiMeetView inside
            rootViewController?.present(vc, animated: true, completion: completion)
        }
    }
    
    func cancelCall(completion: (() -> Void)?) {
        // What for view dismiss and return completion then or if no current meeting is active then just return immediately
        if let vc = rootViewController?.presentedViewController as? MeetingView {
            vc.close(completion: completion)
        } else {
            completion?()
        }
    }
}

// MARK: MeetingView

class MeetingView: UIViewController {

    @IBOutlet weak var meetView: JitsiMeetView!

    override func viewDidLoad() {
        super.viewDidLoad()

        let stringServerUrl = payload.meetingServerUrl // our server meeting url
        
        let jitsiOptions = JitsiMeetConferenceOptions.fromBuilder { [weak self] (builder) in
            builder.serverURL = URL(string: stringServerUrl)
        }
        
        JitsiMeet.sharedInstance().defaultConferenceOptions = jitsiOptions
        
        meetView.delegate = self
        
        let roomId = payload.roomId // get it from ViewModel, doesn't actually matter
        let jitsiOptions = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.room = roomId
        }
        meetView.join(jitsiOptions)
    }
    
    func close(completion: (() -> Void)?) {
        if meetView != nil {
            meetView.leave()
            meetView.removeFromSuperview()
            meetView = nil
        }
        self.dismiss(animated: true, completion: completion)
    }
}
```

I can also share some other if needed. Or logs (but it appears as a really long log list that not looking informative for me).

**Comment by saghul** [comment]
Can you try not doing `configureAudioSession` ? It's already done internally.

**Comment by atereshkov** [comment]
@saghul I did a try without `configureAudioSession` and it doesn't help.

When I commented it and answered a call using JMCallKitProxy then audio didn't work.
But audio works fine when I start a call (without JMCallKitProxy) and others join the meeting.

That's pretty strange, I can't find a consistent pattern how it reproduces.

**Comment by saghul** [comment]
> Audio didn't work (but it works when `configureAudioSession` used):

I'm a bit confused. What scenarios fail, regardless of what you do? Are your incoming call operations triggered by a VoIP push notification?

**Comment by atereshkov** [comment]
> Are your incoming call operations triggered by a VoIP push notification?

Yes, and then I call `JMCallKitProxy.reportNewIncomingCall`

> What scenarios fail, regardless of what you do?

- If I comment `configureAudioSession()` then call that triggered by a voip push notification and answered using JMCallKitProxy has no audio for the user.
- If I use `configureAudioSession()` (as it was before you asked me to do not use it) then initial issue appears - user audio is not working when user join a call from voip push notification (using JMCallKitProxy) when another Jitsi call in the same app is in progress.
