### ISSUE TITLE
Lost video with more than 2 members

### ISSUE THREAD

**Issue by Mister-Ice** [jitsi/jitsi-meet#9987]
### Description:

I use jitsi meet from Rocket.chat. When the third member connecting somebody lost video picture. If member, who lost video, reconnect, then somebody else lost video picture. 

### Client information:

- Browser / app version: Google Chrome 94
- Operating System: Windows 10 Pro and one member Windows 7 Pro 64 bit

**Comment by saghul** [comment]
Looks like a setup issue in your installation. Please make sure to check the logs, you'll likely find out that there were no video bridges available. You may need to restart it.

**Comment by Mister-Ice** [comment]
> 
> 
> Looks like a setup issue in your installation. Please make sure to check the logs, you'll likely find out that there were no video bridges available. You may need to restart it.

Installation of what ? I have just Rocket.chat server and I connected from Rocket.chat.

**Comment by saghul** [comment]
I don't know what Jitsi Meet deployment your Rocket.Chat installation connects with. That's the one that seems to not work properly.

**Comment by Mister-Ice** [comment]
> 
> 
> I don't know what Jitsi Meet deployment your Rocket.Chat installation connects with. That's the one that seems to not work properly.

When I click on a call, a random room is created and all participants can enter it by pressing the button. Jitsi meet is a side self-webprogram for me.

**Comment by saghul** [comment]
How does that link look like? This is important because as I said it looks like a problem with that deployment, so you need to report it to the prople running that deployment. If the link looks like httpps://meet.jit.si/something, that would be us, but I suspect that's not the case.

**Comment by Mister-Ice** [comment]
> 
> 
> How does that link look like? This is important because as I said it looks like a problem with that deployment, so you need to report it to the prople running that deployment. If the link looks like httpps://meet.jit.si/something, that would be us, but I suspect that's not the case.

Its look like ...
![рок](https://user-images.githubusercontent.com/91180328/134318909-fd7b8253-adf4-48b1-acc0-9baa292c5783.jpg)

**Comment by saghul** [comment]
Oh, that's unexpected! Can you share your browser console logs?

**Comment by Mister-Ice** [comment]
> 
> 
> Oh, that's unexpected! Can you share your browser console logs?

[somelogs.txt](https://github.com/jitsi/jitsi-meet/files/7209566/somelogs.txt)

**Comment by saghul** [comment]
Is that verything you get when the call breaks?

**Comment by Mister-Ice** [comment]
> 
> 
> Is that verything you get when the call breaks?

No.
But today was a videocall with three participants and after the call I saved the logs. Video lost again, including mine.
[some logs 2.txt](https://github.com/jitsi/jitsi-meet/files/7215482/some.logs.2.txt)

**Comment by Mister-Ice** [comment]
> 
> 
> Is that verything you get when the call breaks?

Have any solutions?

**Comment by Symous** [comment]
@Mister-Ice Hi, friend, have you solved this?
