### ISSUE TITLE
Deadlock when selecting audio device with connected bluetooth headphones

### ISSUE THREAD

**Issue by aprocom** [jitsi/jitsi-meet#9996]
### Description:
User couldn't switch audio devices when have connected bluetooth headphones.

### Steps to reproduce:
1. open Jitsi Meet app
2. connect to conference with any other participant (important because doesn't reproduces with not active call)
3. go to "Select sound devices"

### Expected behavior:
User could select any audio device: Phone or Speaker or "connected headphones"

### Actual behavior:
Deadlock same as was fixed here https://github.com/jitsi/jitsi-meet/commit/a4d516ca868a34dc4fd0c712a65e3c78a688db6b
User see black screen

### Server information:
Create conference use default server for app from App Store

### Client information:
iPhone
iOS: 15.0
Jitsi Meet App 21.3.1 build 119
Connected bluetooth headphones

**Comment by saghul** [comment]
We'll release an update soon. In the meantime you can sign up for our beta version since it contains this fix already: https://testflight.apple.com/join/isy6ja7S

**Comment by aprocom** [comment]
@saghul still reproduces on build 21.4.0 build 127
![photo_2021-09-22_18-19-46](https://user-images.githubusercontent.com/8492103/134372488-f13c0728-b1f1-4fc6-adb4-1b72b319720d.jpg)
![photo_2021-09-22_18-19-44](https://user-images.githubusercontent.com/8492103/134372492-cbe3e5a6-cf9b-4b29-8f48-e2b6a2a8fca0.jpg)

**Comment by saghul** [comment]
Weird, I cannot. I can switch devices just fine, including bluetooth 😮

**Comment by saghul** [comment]
Can you check your device logs with Console.app ?

**Comment by aprocom** [comment]
@saghul Please, check that you have active conference with any other user. Problem doesn't reproduces when User start conference and doesn't invite any one else.

**Comment by saghul** [comment]
I did have 2 users in the conference.

**Comment by aprocom** [comment]
@saghul and you checked on iOS 15?

**Comment by saghul** [comment]
No this was iOS 14. Good point I'll test on iOS 15 tomorrow.
