### ISSUE TITLE
Missing Arabic translations

### ISSUE THREAD

**Issue by ali-alhaidary** [jitsi/jitsi-meet#9998]
### Description:

Missing Arabic Translations
![Screenshot 2021-09-23 at 04-18-49 حِـــوار](https://user-images.githubusercontent.com/75235623/134442197-09f11094-f7ef-4be4-a085-294e6dfb8c24.png)
![2 حِـــوار](https://user-images.githubusercontent.com/75235623/134442205-d3272ae5-a7f9-40e0-92ea-4b71299cca80.png)
I am ready and willing to help in translation in Arabic

**Comment by damencho** [comment]
You can create a PR for https://github.com/jitsi/jitsi-meet/blob/master/lang/main-ar.json
You can sync missing keys with https://github.com/jitsi/jitsi-meet/blob/master/lang/main.json

**Comment by damencho** [comment]
It

**Comment by ali-alhaidary** [comment]
@damencho Thank you, creating a PR is not a problem, however, is there a simple way to find missing keys as they are more than 100

**Comment by damencho** [comment]
Not really. We will add a translation system at some point but we haven't got to it yet ...

**Comment by ali-alhaidary** [comment]
So I have to go checking more than 1100 key one by one ?

**Comment by saghul** [comment]
At the moment I'm afraid so :-/ You should be able to script it though, by comparing the 2 JSON files and filling in the missing keys / values.

**Comment by ali-alhaidary** [comment]
PR https://github.com/jitsi/jitsi-meet/compare/master...ali-alhaidary:patch-1

**Comment by ali-alhaidary** [comment]
Signed the CLA, whats next?
